# charvoice.scn

[info]

[characters]

[character_subs]

[script]
# lines: 0

[strings]
# count: 108

0 = ""
48 = "default"
69 = "カズマ"
10 = "KAZUMA"
12 = "KZ"
2 = "AQUA"
1 = "AQ"
56 = "アクア"
49 = "めぐみん"
14 = "MEGUMIN"
15 = "MG"
81 = "ダクネス"
6 = "DS"
5 = "DARKNESS"
4 = "CS"
3 = "CHRIS"
77 = "クリス"
66 = "ウィズ"
18 = "WIZ"
19 = "WZ"
20 = "YN"
54 = "ゆんゆん"
21 = "YUNYUN"
86 = "バニル"
16 = "VA"
17 = "VANIR"
9 = "ETC"
87 = "ルナ"
13 = "LU"
8 = "ER"
68 = "エリス"
85 = "ダスト"
7 = "DT"
76 = "キース"
11 = "KE"
60 = "アクア＆ウィズ＆クリス"
47 = "ZZ"
61 = "アクア＆ダクネス＆めぐみん"
59 = "アクア＆めぐみん＆ダクネス＆ウィズ＆ゆんゆん＆クリス"
58 = "アクア＆めぐみん＆ダクネス"
57 = "アクア＆めぐみん"
67 = "ウィズ＆ゆんゆん＆クリス"
72 = "カズマ＆アクア"
73 = "カズマ＆ウィズ"
75 = "カズマ＆ダクネス＆めぐみん"
74 = "カズマ＆ダクネス"
71 = "カズマ＆めぐみん＆ダクネス"
70 = "カズマ＆めぐみん"
79 = "クリス＆ゆんゆん＆ウィズ"
78 = "クリス＆ゆんゆん"
84 = "ダクネス＆ウィズ"
83 = "ダクネス＆めぐみん＆ゆんゆん＆クリス＆ウィズ"
82 = "ダクネス＆めぐみん"
51 = "めぐみん＆ウィズ"
53 = "めぐみん＆ダクネス＆ウィズ＆クリス＆ゆんゆん"
52 = "めぐみん＆ダクネス"
50 = "めぐみん＆ゆんゆん"
55 = "ゆんゆん＆めぐみん"
65 = "アーチャー風の男冒険者"
25 = "ZA"
26 = "ZB"
88 = "商人風の男"
101 = "聖職者風の男"
27 = "ZC"
102 = "聖職者風の男冒険者"
28 = "ZD"
96 = "戦士風の男冒険者"
29 = "ZE"
30 = "ZF"
100 = "盗賊風の男冒険者"
31 = "ZG"
107 = "魔術師風の男冒険者"
103 = "遊び人風の男冒険者"
32 = "ZH"
33 = "ZJ"
80 = "スカルドラゴン"
34 = "ZK"
106 = "魔術師風の女冒険者"
62 = "アクシズ教徒Ａ"
35 = "ZL"
36 = "ZM"
63 = "アクシズ教徒Ｂ"
64 = "アクシズ教徒Ｃ"
37 = "ZN"
38 = "ZP"
92 = "子供の母親Ａ"
93 = "子供の母親Ｂ"
39 = "ZQ"
40 = "ZR"
89 = "女の子"
90 = "女性"
41 = "ZT"
42 = "ZU"
91 = "女性客"
94 = "審査員"
43 = "ZV"
44 = "ZW"
95 = "審査員長"
45 = "ZX"
97 = "男の子Ａ"
46 = "ZY"
98 = "男の子Ｂ"
99 = "男性客"
22 = "YX"
23 = "YY"
104 = "露天商Ａ"
105 = "露天商Ｂ"
24 = "YZ"
