# ctrl_char.txt.scn

[info]
20 = "CTRL_CHAR"
62 = "キャラクタールート"
60 = "アクアルート"
58 = "めぐみんルート"
64 = "ダクネスルート"
61 = "ウィズルート"
63 = "クリスルート"
59 = "ゆんゆんルート"
65 = "終了"

[characters]

[character_subs]

[script]
# lines: 0

