# pr_04.txt.scn

[info]
124 = "pr_04"

[characters]
197 = "ゆんゆん"
195 = "めぐみん"
201 = "カズマ"
200 = "ウィズ"
203 = "カズマ（Ｍ）"

[character_subs]
# 201 = "カズマ"

[script]
# lines: 36

# ゆんゆん
# わかったわ。\n今日の勝負は、お預けってことにしてあげる。
199 = "わかったわ。\\n今日の勝負は、お預けってことにしてあげる。"

# めぐみん
# やっと納得してくれましたか。\n第一、私たちはゆんゆんの相手をするために\nここに来たわけではないのです。
196 = "やっと納得してくれましたか。\\n第一、私たちはゆんゆんの相手をするために\\nここに来たわけではないのです。"

# ゆんゆん
# そ、そうだよね。\nお買い物だよね。
185 = "そ、そうだよね。\\nお買い物だよね。"

# めぐみん
# いえ、違います。\nカズマ、指輪の鑑定結果はどうなのですか？
177 = "いえ、違います。\\nカズマ、指輪の鑑定結果はどうなのですか？"

# カズマ
# おっとっと、そうだった。\nウィズ、これを鑑定して欲しいんだ。
182 = "おっとっと、そうだった。\\nウィズ、これを鑑定して欲しいんだ。"

# カズマ
# で、価値がある物なら\n買い取ってもらえないかと思ってさ。
189 = "で、価値がある物なら\\n買い取ってもらえないかと思ってさ。"

# ゆんゆん
# わあっ！\n綺麗な指輪ですね！
198 = "わあっ！\\n綺麗な指輪ですね！"

# ウィズ
# 本当に。\nどうしたんですか、これ。
211 = "本当に。\\nどうしたんですか、これ。"

# カズマ
# 拾った。\nなにか問題あるか？
210 = "拾った。\\nなにか問題あるか？"

# ウィズ
# い、いえ、なにも。\nとりあえず、ざっと鑑定してみますね。
175 = "い、いえ、なにも。\\nとりあえず、ざっと鑑定してみますね。"

# ゆんゆん
# ねえめぐみん、ここに持ち込んだってことは、\nあの指輪、マジックアイテムなの？\nそんな感じはしなかったけど。
191 = "ねえめぐみん、ここに持ち込んだってことは、\\nあの指輪、マジックアイテムなの？\\nそんな感じはしなかったけど。"

# めぐみん
# 私に言わないでください。\n拾ったのも、ここに持ち込むと言いだしたのも\nカズマなのですから。
232 = "私に言わないでください。\\n拾ったのも、ここに持ち込むと言いだしたのも\\nカズマなのですから。"

# カズマ
# いやぁ、下手な所に持ち込んで\nややこしい話になるのも面倒だしな。
178 = "いやぁ、下手な所に持ち込んで\\nややこしい話になるのも面倒だしな。"

# ウィズ
# うーん……。
179 = "うーん……。"

# カズマ
# どうだ？\nいい値段で売れそうか？
190 = "どうだ？\\nいい値段で売れそうか？"

# ウィズ
# この指輪、ただの指輪じゃないですね。
183 = "この指輪、ただの指輪じゃないですね。"

# めぐみん
# えっ！\nまさか、本当に呪いの指輪ですか？\nカズマに呪いが降りかかったんですか？
181 = "えっ！\\nまさか、本当に呪いの指輪ですか？\\nカズマに呪いが降りかかったんですか？"

# カズマ（Ｍ）
# display as カズマ
# （なんでテンション上がってんだこの厨二病）
234 = "（なんでテンション上がってんだこの厨二病）"

# ウィズ
# うーん、どうでしょう。\n何かの効果を秘めているのはわかるのですが、\nそれが呪いなのかどうなのか……。
180 = "うーん、どうでしょう。\\n何かの効果を秘めているのはわかるのですが、\\nそれが呪いなのかどうなのか……。"

# ウィズ
# すみません。\n私ではこれ以上は……。
184 = "すみません。\\n私ではこれ以上は……。"

# ウィズ
# あ、ですが、バニルさんなら\n鑑定できるかもしれません。
172 = "あ、ですが、バニルさんなら\\n鑑定できるかもしれません。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、そっか。\n　あいつって悪魔で、\n　すべてを見通す力を持ってるんだったな）
233 = "（ああ、そっか。\\n　あいつって悪魔で、\\n　すべてを見通す力を持ってるんだったな）"

# カズマ（Ｍ）
# display as カズマ
# （バニルってのは、ウィズの友人でここの従業員。\n　そして元・魔王軍幹部の悪魔だ）
235 = "（バニルってのは、ウィズの友人でここの従業員。\\n　そして元・魔王軍幹部の悪魔だ）"

# カズマ（Ｍ）
# display as カズマ
# （俺らでしばき倒してやったんだが、\n　残機が１減って２代目バニルとして復活した、\n　とかいうなめた設定で、ここに住み着いている）
237 = "（俺らでしばき倒してやったんだが、\\n　残機が１減って２代目バニルとして復活した、\\n　とかいうなめた設定で、ここに住み着いている）"

# カズマ（Ｍ）
# display as カズマ
# （今は、ウィズが作り出す赤字を補填するために\n　日々頑張っているわけで……\n　いや、マジで本当にご苦労さんだ）
236 = "（今は、ウィズが作り出す赤字を補填するために\\n　日々頑張っているわけで……\\n　いや、マジで本当にご苦労さんだ）"

# カズマ
# 確かにあいつなら鑑定できそうだな。\nいつ戻ってくるんだ？
231 = "確かにあいつなら鑑定できそうだな。\\nいつ戻ってくるんだ？"

# ウィズ
# それが、いつ戻るのかわからなくて……\nお役に立てず、すみません。
186 = "それが、いつ戻るのかわからなくて……\\nお役に立てず、すみません。"

# カズマ
# そんなに謝ることないって。\nまた日を改めてくるよ。
188 = "そんなに謝ることないって。\\nまた日を改めてくるよ。"

# カズマ
# それじゃ、邪魔して悪かったな、ウィズ。
187 = "それじゃ、邪魔して悪かったな、ウィズ。"

# ウィズ
# いえ、またいつでも来てくださいね。\nあ、それから、その指輪ですが――
176 = "いえ、またいつでも来てくださいね。\\nあ、それから、その指輪ですが――"

# ゆんゆん
# め、めぐみんっ！\n勝負はあくまでおあずけなだけだから、\n忘れないでね！
194 = "め、めぐみんっ！\\n勝負はあくまでおあずけなだけだから、\\n忘れないでね！"

# ゆんゆん
# あと私、たぶんだけど、\n明日もここに居ると思うから！
174 = "あと私、たぶんだけど、\\n明日もここに居ると思うから！"

# めぐみん
# カズマ、あのぼっちが騒ぎ出す前に\n早く帰りましょう。
202 = "カズマ、あのぼっちが騒ぎ出す前に\\n早く帰りましょう。"

# カズマ
# へいへーい。\nそんじゃ、またなー。
193 = "へいへーい。\\nそんじゃ、またなー。"

# ウィズ
# あ、カズマさん！
173 = "あ、カズマさん！"

# ウィズ
# ふう、大丈夫かしら？\n不用意に装備しなければいいのだけど……。
192 = "ふう、大丈夫かしら？\\n不用意に装備しなければいいのだけど……。"

