# pr_03.txt.scn

[info]
174 = "pr_03"

[characters]
298 = "カズマ"
291 = "めぐみん"
297 = "ウィズ"
300 = "カズマ（Ｍ）"
293 = "ゆんゆん"

[character_subs]
# 298 = "カズマ"

[script]
# lines: 72

# カズマ
# よう、ウィズ。
295 = "よう、ウィズ。"

# めぐみん
# お邪魔します。
274 = "お邪魔します。"

# ウィズ
# あら、カズマさん。\nそれにめぐみんさんも、いらっしゃいませ。
261 = "あら、カズマさん。\\nそれにめぐみんさんも、いらっしゃいませ。"

# カズマ（Ｍ）
# display as カズマ
# （彼女はウィズ。\n　この『ウィズ魔道具店』の店主をしている\n　元凄腕のアークウィザードだ）
356 = "（彼女はウィズ。\\n　この『ウィズ魔道具店』の店主をしている\\n　元凄腕のアークウィザードだ）"

# カズマ（Ｍ）
# display as カズマ
# （実はこう見えて、普通の人間ではなくリッチー。\n　ノーライフキングと呼ばれるアンデットの王、\n　そして魔王軍の８人の幹部のひとり――）
353 = "（実はこう見えて、普通の人間ではなくリッチー。\\n　ノーライフキングと呼ばれるアンデットの王、\\n　そして魔王軍の８人の幹部のひとり――）"

# カズマ（Ｍ）
# display as カズマ
# （という、実に濃い設定を持つ人だったりする）
347 = "（という、実に濃い設定を持つ人だったりする）"

# カズマ（Ｍ）
# display as カズマ
# （冒険者という立場上、\n　魔王軍の幹部を放っておくわけにいかない\n　のだが――）
352 = "（冒険者という立場上、\\n　魔王軍の幹部を放っておくわけにいかない\\n　のだが――）"

# カズマ（Ｍ）
# display as カズマ
# （本人曰く、魔王城の結界を維持するためだけの\n　『なんちゃって幹部』らしく――）
358 = "（本人曰く、魔王城の結界を維持するためだけの\\n　『なんちゃって幹部』らしく――）"

# カズマ（Ｍ）
# display as カズマ
# （他の幹部のように、人間に危害を加えるつもりは\n　微塵もないらしい）
351 = "（他の幹部のように、人間に危害を加えるつもりは\\n　微塵もないらしい）"

# カズマ（Ｍ）
# display as カズマ
# （性格はいたって温厚だし、\n　冒険者からは貧乏店主さんと慕われてもいる）
357 = "（性格はいたって温厚だし、\\n　冒険者からは貧乏店主さんと慕われてもいる）"

# カズマ（Ｍ）
# display as カズマ
# （害がないなら無理に討伐をする必要もない\n　だろうと、今はこうして放っておいてると\n　いうわけだ）
354 = "（害がないなら無理に討伐をする必要もない\\n　だろうと、今はこうして放っておいてると\\n　いうわけだ）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、狂犬女神が隙あらば……\n　と目を光らせてはいるが）
349 = "（まあ、狂犬女神が隙あらば……\\n　と目を光らせてはいるが）"

# ウィズ
# 今日はなにかご入り用ですか？
305 = "今日はなにかご入り用ですか？"

# カズマ
# ああ、実はさ……。
256 = "ああ、実はさ……。"

# ゆんゆん
# 店主さん、こんにちは。\n今日もお邪魔しま――
312 = "店主さん、こんにちは。\\n今日もお邪魔しま――"

# めぐみん
# あ。
255 = "あ。"

# ゆんゆん
# あ。
# 255 = "あ。"

# カズマ
# お、ゆんゆんじゃん。
271 = "お、ゆんゆんじゃん。"

# ゆんゆん
# め、め、め、めぐみん！？\nようやく会え――
290 = "め、め、め、めぐみん！？\\nようやく会え――"

# ゆんゆん
# じゃ、じゃなくて！\nここで会ったが１００年目！\nめぐみん、今日こそ決着をつけるわよっ！
277 = "じゃ、じゃなくて！\\nここで会ったが１００年目！\\nめぐみん、今日こそ決着をつけるわよっ！"

# めぐみん
# 嫌です。
309 = "嫌です。"

# ゆんゆん
# なんで！？
287 = "なんで！？"

# めぐみん
# 今日はもう魔力を使い果たしているのです。\nそういうわけですから、またの機会に。
306 = "今日はもう魔力を使い果たしているのです。\\nそういうわけですから、またの機会に。"

# ゆんゆん
# えー！？\nせっかく、久し振りに会えたのに～！
270 = "えー！？\\nせっかく、久し振りに会えたのに～！"

# ウィズ
# そうですね。\nカズマさん達、ここ最近は\nお店にいらっしゃらなかったので――
278 = "そうですね。\\nカズマさん達、ここ最近は\\nお店にいらっしゃらなかったので――"

# ウィズ
# ゆんゆんさん、すっかり待ちぼうけでしたから。
294 = "ゆんゆんさん、すっかり待ちぼうけでしたから。"

# めぐみん
# ええ……。
266 = "ええ……。"

# ゆんゆん
# あああああ～！\nそ、そうじゃなくて！　違うの～！！
257 = "あああああ～！\\nそ、そうじゃなくて！　違うの～！！"

# カズマ（Ｍ）
# display as カズマ
# （そっか、未だにここで\n　めぐみんと偶然会える時を待ってるんだな）
346 = "（そっか、未だにここで\\n　めぐみんと偶然会える時を待ってるんだな）"

# カズマ（Ｍ）
# display as カズマ
# （この紅魔族の女の子の名前は、ゆんゆん。\n　自称・めぐみんのライバルで\n　会う度にこうして勝負を挑んでくる）
345 = "（この紅魔族の女の子の名前は、ゆんゆん。\\n　自称・めぐみんのライバルで\\n　会う度にこうして勝負を挑んでくる）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、めぐみんは\n　まったく相手にしてないんだけどな）
348 = "（まあ、めぐみんは\\n　まったく相手にしてないんだけどな）"

# カズマ（Ｍ）
# display as カズマ
# （職業はアークウィザード。\n　１日１発のどこぞのへっぽこと違って\n　上級魔法を使いこなす優秀な魔法使いだ）
359 = "（職業はアークウィザード。\\n　１日１発のどこぞのへっぽこと違って\\n　上級魔法を使いこなす優秀な魔法使いだ）"

# カズマ
# あのさ、ゆんゆん。\n好きな時に屋敷まで来てくれてもいいんだぞ？
260 = "あのさ、ゆんゆん。\\n好きな時に屋敷まで来てくれてもいいんだぞ？"

# ゆんゆん
# で、でも、たくさんのお菓子とジュースを持って\nおじゃまして――
285 = "で、でも、たくさんのお菓子とジュースを持って\\nおじゃまして――"

# ゆんゆん
# えー、マジで来たの？\n社交辞令に決まってんじゃん、あんなの。
269 = "えー、マジで来たの？\\n社交辞令に決まってんじゃん、あんなの。"

# ゆんゆん
# なんて言われたら、私……。
286 = "なんて言われたら、私……。"

# めぐみん
# はあ……。\nあいかわらず面倒くさい子ですね。\nこれだからぼっちは。
288 = "はあ……。\\nあいかわらず面倒くさい子ですね。\\nこれだからぼっちは。"

# ゆんゆん
# わ、私、ぼっちじゃないもん！
296 = "わ、私、ぼっちじゃないもん！"

# ゆんゆん
# それに、なんで心の準備ができてない時に\n限って来てるの！？\nひどいよ、めぐみん！
280 = "それに、なんで心の準備ができてない時に\\n限って来てるの！？\\nひどいよ、めぐみん！"

# めぐみん
# ひどいとはなんですか。\n私はこの店にお客として来ただけです。
289 = "ひどいとはなんですか。\\n私はこの店にお客として来ただけです。"

# めぐみん
# それに決着もなにも、ほとんどの勝負は\n私が勝っているじゃないですか。
281 = "それに決着もなにも、ほとんどの勝負は\\n私が勝っているじゃないですか。"

# ゆんゆん
# つ、次こそ私が勝つんだもん！
284 = "つ、次こそ私が勝つんだもん！"

# カズマ（Ｍ）
# display as カズマ
# （あー、いいや。\n　こいつらは放っておこう）
343 = "（あー、いいや。\\n　こいつらは放っておこう）"

# カズマ
# あれ？\nそういやウィズ、今日は１人なのか？
262 = "あれ？\\nそういやウィズ、今日は１人なのか？"

# ウィズ
# あ、はい。\nバニルさんは今、買い出しに行っています。
254 = "あ、はい。\\nバニルさんは今、買い出しに行っています。"

# ウィズ
# バニルさん、ずっと働きづめなんです。\n倒れてしまったりしないか、ちょっと心配で。
301 = "バニルさん、ずっと働きづめなんです。\\n倒れてしまったりしないか、ちょっと心配で。"

# カズマ（Ｍ）
# display as カズマ
# （……理由は大体わかる。\n　この店の赤字解消のために\n　奔走しているんだろう）
342 = "（……理由は大体わかる。\\n　この店の赤字解消のために\\n　奔走しているんだろう）"

# ウィズ
# そんな根を詰めなくてもって、\n何度もお伝えしているのですが\n聞いてもらえなくて。
282 = "そんな根を詰めなくてもって、\\n何度もお伝えしているのですが\\n聞いてもらえなくて。"

# ウィズ
# カズマさんからも今度、\nさり気なく言って頂けませんか？
299 = "カズマさんからも今度、\\nさり気なく言って頂けませんか？"

# カズマ（Ｍ）
# display as カズマ
# （この様子じゃ、バニルの苦労の原因が自分だって\n　わかってないんだろうなぁ）
344 = "（この様子じゃ、バニルの苦労の原因が自分だって\\n　わかってないんだろうなぁ）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズは、働けば働くほど貧乏になるという\n　不思議な特技を持っている）
350 = "（ウィズは、働けば働くほど貧乏になるという\\n　不思議な特技を持っている）"

# カズマ（Ｍ）
# display as カズマ
# （店に仕入れる物は、\n　本人だけが自信たっぷりで使えない物ばかり。\n　当然、売れもせず赤字続きってわけだ）
355 = "（店に仕入れる物は、\\n　本人だけが自信たっぷりで使えない物ばかり。\\n　当然、売れもせず赤字続きってわけだ）"

# カズマ（Ｍ）
# display as カズマ
# （魔法使いとしては凄腕なんだが\n　絶望的に商才ってのがないんだよな）
360 = "（魔法使いとしては凄腕なんだが\\n　絶望的に商才ってのがないんだよな）"

# めぐみん
# しつこいです！\n今日は勝負しないと\n何度言ったらわかるのですか！
276 = "しつこいです！\\n今日は勝負しないと\\n何度言ったらわかるのですか！"

# ゆんゆん
# お願い、勝負してよー！
275 = "お願い、勝負してよー！"

# めぐみん
# ええい、離してください！
267 = "ええい、離してください！"

# カズマ
# お前らまだそのコントやってたのかよ。
273 = "お前らまだそのコントやってたのかよ。"

# めぐみん
# 文句ならゆんゆんに言ってください！
313 = "文句ならゆんゆんに言ってください！"

# ゆんゆん
# えっ！？\nご、ごめんなさいっ！
268 = "えっ！？\\nご、ごめんなさいっ！"

# カズマ
# いや、ゆんゆんが謝ることないから。
264 = "いや、ゆんゆんが謝ることないから。"

# めぐみん
# いいですか？\nさっきも言ったとおり――
263 = "いいですか？\\nさっきも言ったとおり――"

# めぐみん
# 私は今日、すでに爆裂魔法を撃って\n魔力が枯渇しているのです。
339 = "私は今日、すでに爆裂魔法を撃って\\n魔力が枯渇しているのです。"

# めぐみん
# そんな私に勝って、\nあなたは胸を張れるのですか？
283 = "そんな私に勝って、\\nあなたは胸を張れるのですか？"

# めぐみん
# その！
279 = "その！"

# ゆんゆん
# あぅ！
259 = "あぅ！"

# めぐみん
# 無駄に！
314 = "無駄に！"

# ゆんゆん
# ううぅ！
265 = "ううぅ！"

# めぐみん
# 育った！
340 = "育った！"

# ゆんゆん
# ああんっ！
258 = "ああんっ！"

# めぐみん
# 胸をっ！！
341 = "胸をっ！！"

# ゆんゆん
# や、やめて！\n自分が育たないからって私に当たらないでー！
292 = "や、やめて！\\n自分が育たないからって私に当たらないでー！"

# カズマ
# おい、なんのプレイだ！\n止めてやれって！
272 = "おい、なんのプレイだ！\\n止めてやれって！"

