# pr_07.txt.scn

[info]
223 = "pr_07"

[characters]
300 = "カズマ"
291 = "めぐみん"
304 = "ダクネス"
295 = "アクア"
301 = "カズマ（Ｍ）"

[character_subs]
# 300 = "カズマ"

[script]
# lines: 56

# カズマ
# アクアッ！
299 = "アクアッ！"

# めぐみん
# あ、おはようございます。
254 = "あ、おはようございます。"

# ダクネス
# おはよう。カズマ。
265 = "おはよう。カズマ。"

# アクア
# ちょっと、昼近くまで寝てるなんて、だらけ過ぎ！\nもっとちゃんとしなさいよ。
276 = "ちょっと、昼近くまで寝てるなんて、だらけ過ぎ！\\nもっとちゃんとしなさいよ。"

# ダクネス
# まあまあ、今日くらいは大目に見てやれ。\n夕べは遅くまで起きていたんだから。
290 = "まあまあ、今日くらいは大目に見てやれ。\\n夕べは遅くまで起きていたんだから。"

# めぐみん
# それよりもカズマ。\n血相を変えてどうしたんですか？
273 = "それよりもカズマ。\\n血相を変えてどうしたんですか？"

# カズマ
# いや、これ！　指輪が！！
258 = "いや、これ！　指輪が！！"

# アクア
# は？　指輪？
284 = "は？　指輪？"

# カズマ
# これだよこれ！\n俺の指にぴったりはまって取れないんだ！
268 = "これだよこれ！\\n俺の指にぴったりはまって取れないんだ！"

# アクア
# え……！
261 = "え……！"

# めぐみん
# なっ……！
278 = "なっ……！"

# ダクネス
# おお……！
264 = "おお……！"

# カズマ
# 取れないって言うか、もうむしろ\n俺の皮膚と一体化しているような感じで！\nマジで呪いなのかもしれない！
309 = "取れないって言うか、もうむしろ\\n俺の皮膚と一体化しているような感じで！\\nマジで呪いなのかもしれない！"

# めぐみん
# ちょ、ちょっと、カズマ。\nもしかして本当に……変態にまで落ちたんですか？
275 = "ちょ、ちょっと、カズマ。\\nもしかして本当に……変態にまで落ちたんですか？"

# カズマ
# は？
283 = "は？"

# アクア
# 正直、ドン引きなんですけど。
316 = "正直、ドン引きなんですけど。"

# カズマ
# へ？
288 = "へ？"

# ダクネス
# そういうことを普通の女子にしたら\n嫌われてしまうぞ。
270 = "そういうことを普通の女子にしたら\\n嫌われてしまうぞ。"

# ダクネス
# わ、私は、受け入れられるが。\nふ、ふふふ。
294 = "わ、私は、受け入れられるが。\\nふ、ふふふ。"

# カズマ（Ｍ）
# display as カズマ
# （し、しまった！\n　パンツを持ったままだったー！！）
348 = "（し、しまった！\\n　パンツを持ったままだったー！！）"

# カズマ
# 違う、これはパンツじゃないんだ！
347 = "違う、これはパンツじゃないんだ！"

# アクア
# へーえ？\nだったらなんだって言うのよ。
287 = "へーえ？\\nだったらなんだって言うのよ。"

# カズマ
# え、えっと、これは……パンツ型の帽子だ！\nナイトキャップとして俺が愛用してるんだ！
262 = "え、えっと、これは……パンツ型の帽子だ！\\nナイトキャップとして俺が愛用してるんだ！"

# アクア
# だったら被ってみなさいよ。
274 = "だったら被ってみなさいよ。"

# カズマ
# へ？　あの、ええと……。
289 = "へ？　あの、ええと……。"

# めぐみん
# アクア、撃っていいですか？\n撃っていいですよね？\nじゃあ、撃ちますね？
296 = "アクア、撃っていいですか？\\n撃っていいですよね？\\nじゃあ、撃ちますね？"

# カズマ
# 嘘です！　これはパンツです！\nディスイズアパンツ！　キャップじゃなくてパンツ！\nだから撃たないでー！
312 = "嘘です！　これはパンツです！\\nディスイズアパンツ！　キャップじゃなくてパンツ！\\nだから撃たないでー！"

# カズマ
# アクアがやらせたんだろ！？\n夕べ、芸をしろって強要して、\nその結果、俺がスティールしたんだろ！？
298 = "アクアがやらせたんだろ！？\\n夕べ、芸をしろって強要して、\\nその結果、俺がスティールしたんだろ！？"

# アクア
# 人のせいにしてんじゃないわよ！\nあんた、ジャイアントトードの真似とかいう\nしょうもない芸をしてたじゃない！
307 = "人のせいにしてんじゃないわよ！\\nあんた、ジャイアントトードの真似とかいう\\nしょうもない芸をしてたじゃない！"

# カズマ
# え？　なにそれ？\n俺そんなことしたの？
263 = "え？　なにそれ？\\n俺そんなことしたの？"

# ダクネス
# ああ、よく似ていたぞ！\n私を見つめる無感情の目は、\n丸呑みにしてやると言わんばかりだった。
256 = "ああ、よく似ていたぞ！\\n私を見つめる無感情の目は、\\n丸呑みにしてやると言わんばかりだった。"

# カズマ
# あ、ああー、そうなんだー。
253 = "あ、ああー、そうなんだー。"

# めぐみん
# それよりも、手に持っている物について\n説明をしてください。\nまあ、どんな内容でも撃ちますが。
272 = "それよりも、手に持っている物について\\n説明をしてください。\\nまあ、どんな内容でも撃ちますが。"

# カズマ
# 言わせといて撃つなよ！
346 = "言わせといて撃つなよ！"

# カズマ
# これも訓練なんだ！
269 = "これも訓練なんだ！"

# アクア
# はぁ？　訓練？
281 = "はぁ？　訓練？"

# カズマ
# ス、スティールの訓練だよー。\nこの技に磨きをかけ、レベル差がある\n相手の武器も盗めるくらいになれば――
303 = "ス、スティールの訓練だよー。\\nこの技に磨きをかけ、レベル差がある\\n相手の武器も盗めるくらいになれば――"

# カズマ
# お前らを守ることだってできるからな！
266 = "お前らを守ることだってできるからな！"

# アクア
# 心にもないこと言ってるんじゃないわよ。
315 = "心にもないこと言ってるんじゃないわよ。"

# カズマ
# 俺渾身のさわやか演技を間髪入れずに否定か！
308 = "俺渾身のさわやか演技を間髪入れずに否定か！"

# めぐみん
# パンツを突きつけられつつ、\nさわやかにそんなこと言われる身にも\nなってください。
305 = "パンツを突きつけられつつ、\\nさわやかにそんなこと言われる身にも\\nなってください。"

# カズマ
# あ、はい、そうですね。\nすみませんでした。
255 = "あ、はい、そうですね。\\nすみませんでした。"

# カズマ
# で！　結局これは誰のパンツなんだよ！？\nアクアか？
277 = "で！　結局これは誰のパンツなんだよ！？\\nアクアか？"

# アクア
# はぁ！？
280 = "はぁ！？"

# カズマ
# めぐみんか！？
292 = "めぐみんか！？"

# めぐみん
# ひうっ！？
285 = "ひうっ！？"

# カズマ
# それともダクネスなのか！？
271 = "それともダクネスなのか！？"

# ダクネス
# ううっ！？
259 = "ううっ！？"

# カズマ
# あれ？\nみんな、スカート押さえてどうしたの？
257 = "あれ？\\nみんな、スカート押さえてどうしたの？"

# カズマ
# もしかして……みんな穿いていないのか？\nそういうことなのか！？
293 = "もしかして……みんな穿いていないのか？\\nそういうことなのか！？"

# アクア
# ねーえ、カズマさん。
279 = "ねーえ、カズマさん。"

# カズマ
# はい。\nなんですか、穿いてない女神様。
282 = "はい。\\nなんですか、穿いてない女神様。"

# アクア
# ふ、ふふふ。\nとりあえず、そのくだらない妄想を\nやめましょうか。
286 = "ふ、ふふふ。\\nとりあえず、そのくだらない妄想を\\nやめましょうか。"

# カズマ
# え……。
260 = "え……。"

# アクア
# ゴッドブローォォォォッ！
302 = "ゴッドブローォォォォッ！"

# カズマ
# ぎゃああああああああああ！
267 = "ぎゃああああああああああ！"

[selections]
# 347 = "違う、これはパンツじゃないんだ！"
297 = "アクアがやらせたんだろ！？"
# 269 = "これも訓練なんだ！"
