# pr_01.txt.scn

[info]
271 = "pr_01"
381 = "プロローグスキップ"
377 = "プロローグ"

[characters]
372 = "カズマ"
369 = "めぐみん"
373 = "カズマ（Ｍ）"

[character_subs]
# 372 = "カズマ"

[script]
# lines: 106

# monologue
# プロローグをスキップしますか？
379 = "プロローグをスキップしますか？"

# カズマ
# これは、今まさに紡がれゆく伝説の物語。
338 = "これは、今まさに紡がれゆく伝説の物語。"

# カズマ
# 非業の事故で命を失った俺、\nサトウカズマは――
426 = "非業の事故で命を失った俺、\\nサトウカズマは――"

# カズマ
# 運命の女神に導かれ、\n剣と魔法の異世界への転生を果たした。
425 = "運命の女神に導かれ、\\n剣と魔法の異世界への転生を果たした。"

# カズマ
# 新たな生を受けた俺に与えられた使命。\nそれは、人々をしいたげる魔王を倒し\n世界に平和をもたらすこと。
403 = "新たな生を受けた俺に与えられた使命。\\nそれは、人々をしいたげる魔王を倒し\\n世界に平和をもたらすこと。"

# カズマ
# 無論、それを１人で成すのは\nあまりにも難しい。\nだが俺には、固い絆で結ばれた仲間達がいる！
406 = "無論、それを１人で成すのは\\nあまりにも難しい。\\nだが俺には、固い絆で結ばれた仲間達がいる！"

# カズマ
# 俺に従い、共にこの世界に来た\nあまねく大地に浄化の光を注ぐ美しい女神。
390 = "俺に従い、共にこの世界に来た\\nあまねく大地に浄化の光を注ぐ美しい女神。"

# カズマ
# 比類無き魔力を有し、恐るべき魔法を操る\n紅き瞳の天才魔法使い。
405 = "比類無き魔力を有し、恐るべき魔法を操る\\n紅き瞳の天才魔法使い。"

# カズマ
# そして、どんな強敵も恐れない\n鉄壁の守りを誇る勇敢な女騎士――
341 = "そして、どんな強敵も恐れない\\n鉄壁の守りを誇る勇敢な女騎士――"

# カズマ
# 俺達４人は、この素晴らしい世界を救うべく\n果てしなき旅路を行く……！
392 = "俺達４人は、この素晴らしい世界を救うべく\\n果てしなき旅路を行く……！"

# カズマ
# ……なんてな。
316 = "……なんてな。"

# カズマ
# なんだろうなー、この大体あってるのに\n全部間違ってる感は……。
360 = "なんだろうなー、この大体あってるのに\\n全部間違ってる感は……。"

# めぐみん
# カズマ？\nなにをブツブツ言っているのですか？
374 = "カズマ？\\nなにをブツブツ言っているのですか？"

# カズマ
# 俺の身の上の復習をしていただけだ。\nはあ、はははははー、人生がオートセーブじゃ\nなけりゃ、今すぐやり直すのに……。
391 = "俺の身の上の復習をしていただけだ。\\nはあ、はははははー、人生がオートセーブじゃ\\nなけりゃ、今すぐやり直すのに……。"

# めぐみん
# なんですか。\n急に訳のわからないことを言って。
362 = "なんですか。\\n急に訳のわからないことを言って。"

# めぐみん
# でも、そんなの初耳ですね。\n一体、誰に復讐したいんです？
353 = "でも、そんなの初耳ですね。\\n一体、誰に復讐したいんです？"

# カズマ
# は？
364 = "は？"

# めぐみん
# 我はめぐみん！\n汝の輩なり！
402 = "我はめぐみん！\\n汝の輩なり！"

# めぐみん
# 我と汝との友誼に従い、その憎き相手に\n我が爆裂魔法をとくと味わわせてやろう！
401 = "我と汝との友誼に従い、その憎き相手に\\n我が爆裂魔法をとくと味わわせてやろう！"

# カズマ
# それ、お前が爆裂魔法を打ちたいだけだろ。\nていうか『ふくしゅう』違いだし。
343 = "それ、お前が爆裂魔法を打ちたいだけだろ。\\nていうか『ふくしゅう』違いだし。"

# カズマ（Ｍ）
# display as カズマ
# （この痛い勘違い厨二病発言をしている\n　ロリっ子は、めぐみん。\n　あー、なんていうか、一応、俺の仲間だ）
429 = "（この痛い勘違い厨二病発言をしている\\n　ロリっ子は、めぐみん。\\n　あー、なんていうか、一応、俺の仲間だ）"

# カズマ（Ｍ）
# display as カズマ
# （魔法能力が高い紅魔族の中でも\n　随一の魔法使い……らしい）
446 = "（魔法能力が高い紅魔族の中でも\\n　随一の魔法使い……らしい）"

# カズマ（Ｍ）
# display as カズマ
# （ちなみに、変な名前は本名。\n　これも紅魔族の特徴って話だ）
436 = "（ちなみに、変な名前は本名。\\n　これも紅魔族の特徴って話だ）"

# カズマ
# それより、爆裂魔法の訓練、\nさっさと済ませようぜ。
345 = "それより、爆裂魔法の訓練、\\nさっさと済ませようぜ。"

# めぐみん
# え？　ここでいいんでしょうか？\nまた守衛さんにうるさいと叱られるのは嫌です。
330 = "え？　ここでいいんでしょうか？\\nまた守衛さんにうるさいと叱られるのは嫌です。"

# カズマ
# 大丈夫だ、ここまでくれば\n街にも迷惑かからないだろ。\nほれ、あそこに手頃な岩もあるし。
396 = "大丈夫だ、ここまでくれば\\n街にも迷惑かからないだろ。\\nほれ、あそこに手頃な岩もあるし。"

# めぐみん
# むう……。
368 = "むう……。"

# カズマ
# なんだよ、あれじゃ不満か？
359 = "なんだよ、あれじゃ不満か？"

# めぐみん
# え、ええ。\nもっと硬くて大きい物じゃないと\n物足りない体になってしまったのです……。
328 = "え、ええ。\\nもっと硬くて大きい物じゃないと\\n物足りない体になってしまったのです……。"

# カズマ
# だーーーっ！\n頬染めながら言うなー！
352 = "だーーーっ！\\n頬染めながら言うなー！"

# カズマ
# 大体、吹っ飛ばしていい古城なんて\nそうそう存在しないから！\nあれで我慢しろ！
397 = "大体、吹っ飛ばしていい古城なんて\\nそうそう存在しないから！\\nあれで我慢しろ！"

# めぐみん
# 仕方ないですね。\nでは、いきます。
389 = "仕方ないですね。\\nでは、いきます。"

# カズマ（Ｍ）
# display as カズマ
# （進み出ためぐみんが杖を構えて\n　眼帯を装備する）
444 = "（進み出ためぐみんが杖を構えて\\n　眼帯を装備する）"

# カズマ（Ｍ）
# display as カズマ
# （この眼帯には特別なマジック効果は無いらしく\n　ただのおしゃれ装備らしい）
430 = "（この眼帯には特別なマジック効果は無いらしく\\n　ただのおしゃれ装備らしい）"

# めぐみん
# 我が名はめぐみん！\nアークウィザードを生業とする\n紅魔族随一の魔法の使い手なり！
400 = "我が名はめぐみん！\\nアークウィザードを生業とする\\n紅魔族随一の魔法の使い手なり！"

# カズマ
# うん知ってる。
327 = "うん知ってる。"

# めぐみん
# さあ、その目に焼き付けるがいい！\n我が力によって放たれる、\n最強の攻撃魔法、爆裂魔法を！
340 = "さあ、その目に焼き付けるがいい！\\n我が力によって放たれる、\\n最強の攻撃魔法、爆裂魔法を！"

# カズマ
# その前置き必要？
342 = "その前置き必要？"

# めぐみん
# 黒より黒く、闇より昏き漆黒に\n我が真紅の混淆を望みたもう。
427 = "黒より黒く、闇より昏き漆黒に\\n我が真紅の混淆を望みたもう。"

# めぐみん
# 覚醒の時、来たれり。\n無謬の境界に堕ちし理、\n無形の歪みとなりて、現出せよ！
422 = "覚醒の時、来たれり。\\n無謬の境界に堕ちし理、\\n無形の歪みとなりて、現出せよ！"

# めぐみん
# エクスプローーーージョンッ！
371 = "エクスプローーーージョンッ！"

# カズマ
# おおー、あいかわらず派手だなー。
334 = "おおー、あいかわらず派手だなー。"

# カズマ（Ｍ）
# display as カズマ
# （なんて悠長に言ってるがこのエクスプロージョン\n　は、この世界で最大の威力を誇る攻撃魔法\n　だったりする）
439 = "（なんて悠長に言ってるがこのエクスプロージョン\\n　は、この世界で最大の威力を誇る攻撃魔法\\n　だったりする）"

# カズマ（Ｍ）
# display as カズマ
# （そして、くる日もくる日も\n　めぐみんのエクスプロージョンを\n　側で見守り続けてきた俺は――）
433 = "（そして、くる日もくる日も\\n　めぐみんのエクスプロージョンを\\n　側で見守り続けてきた俺は――）"

# カズマ（Ｍ）
# display as カズマ
# （すっかり慣れてしまい、それどころか\n　その日の爆裂魔法の出来が\n　わかるまでになっていた）
432 = "（すっかり慣れてしまい、それどころか\\n　その日の爆裂魔法の出来が\\n　わかるまでになっていた）"

# めぐみん
# ……あう。
315 = "……あう。"

# めぐみん
# あー……。\n最高、です……。
321 = "あー……。\\n最高、です……。"

# めぐみん
# それで、どうですか、カズマ。\n今日の出来は……。
344 = "それで、どうですか、カズマ。\\n今日の出来は……。"

# カズマ
# うむ、今日のは悪くないぞ。\n爆裂の衝撃波が皮膚を震わすゾクッとした感覚、\n俺は嫌いじゃない。
326 = "うむ、今日のは悪くないぞ。\\n爆裂の衝撃波が皮膚を震わすゾクッとした感覚、\\n俺は嫌いじゃない。"

# めぐみん
# おお。\nそれは、今までにない感想ですね。
333 = "おお。\\nそれは、今までにない感想ですね。"

# カズマ
# だが、奥深さがまーったく足りてない！\nこれは、飲み込めば味を忘れてしまうような\n薄味過ぎる爆裂だっ！
351 = "だが、奥深さがまーったく足りてない！\\nこれは、飲み込めば味を忘れてしまうような\\n薄味過ぎる爆裂だっ！"

# めぐみん
# くっ……！\n率直な意見、参考になりますよ。\n爆裂道を極めるために精進します。
335 = "くっ……！\\n率直な意見、参考になりますよ。\\n爆裂道を極めるために精進します。"

# カズマ
# で？　おんぶはいるか？
355 = "で？　おんぶはいるか？"

# カズマ
# 今までで一番いい出来だ！
386 = "今までで一番いい出来だ！"

# めぐみん
# ……本当ですか？\n適当に言ってませんか？
319 = "……本当ですか？\\n適当に言ってませんか？"

# カズマ
# ホントだって！\nいいか？　よく聞け？
383 = "ホントだって！\\nいいか？　よく聞け？"

# カズマ
# 爆裂の衝撃波がずんっと骨身に染みるだけじゃなく、\n更に内臓に響いていくかのような奥深さがあり……
408 = "爆裂の衝撃波がずんっと骨身に染みるだけじゃなく、\\n更に内臓に響いていくかのような奥深さがあり……"

# カズマ
# 遅れてくる空気の振動も、肌を撫で\n全身を包み込むかのような柔らかさを伴っている！
424 = "遅れてくる空気の振動も、肌を撫で\\n全身を包み込むかのような柔らかさを伴っている！"

# カズマ
# ナイス爆裂！
376 = "ナイス爆裂！"

# めぐみん
# ……ナイス爆裂。\nカズマも、爆裂道を順調に\n歩んでいるようですね。
317 = "……ナイス爆裂。\\nカズマも、爆裂道を順調に\\n歩んでいるようですね。"

# カズマ
# で？　おんぶはいるか？
# 355 = "で？　おんぶはいるか？"

# カズマ
# 普通だな。
404 = "普通だな。"

# めぐみん
# ……普通ってなんですか、普通って。
318 = "……普通ってなんですか、普通って。"

# カズマ
# だから普通だよ。\n可もなく不可もなく？
350 = "だから普通だよ。\\n可もなく不可もなく？"

# めぐみん
# 無難な感想なんて求めていませんよ。\n私の爆裂への探究心をバカにしているんですか？
407 = "無難な感想なんて求めていませんよ。\\n私の爆裂への探究心をバカにしているんですか？"

# カズマ
# そんなこと言われてもなー。\nホント、今日の爆裂には\n普通って感想しか出てこないんだよ。
346 = "そんなこと言われてもなー。\\nホント、今日の爆裂には\\n普通って感想しか出てこないんだよ。"

# めぐみん
# なるほど。\nカズマにとって、爆裂魔法とは\nその程度のものだったんですね。ガッカリです。
357 = "なるほど。\\nカズマにとって、爆裂魔法とは\\nその程度のものだったんですね。ガッカリです。"

# カズマ（Ｍ）
# display as カズマ
# （なんか、勝手にガッカリされてる？）
438 = "（なんか、勝手にガッカリされてる？）"

# カズマ
# で？　おんぶはいるか？
# 355 = "で？　おんぶはいるか？"

# めぐみん
# あ、はい、お願いします。
320 = "あ、はい、お願いします。"

# めぐみん
# へへ、えへへへ……。\n今日も……すごく……気持ち良かったです。
367 = "へへ、えへへへ……。\\n今日も……すごく……気持ち良かったです。"

# カズマ
# おい、この体勢で、しかも耳元で\nささやくようにそんなことを言うな。
332 = "おい、この体勢で、しかも耳元で\\nささやくようにそんなことを言うな。"

# めぐみん
# え？　なんでですか？
331 = "え？　なんでですか？"

# カズマ
# いいから黙ってろ！\nさもないとここで落として捨ててくぞ！
322 = "いいから黙ってろ！\\nさもないとここで落として捨ててくぞ！"

# めぐみん
# ひ、ひどいです！\nなんのために特訓に付き合ってもらってると\n思ってるんですか！
365 = "ひ、ひどいです！\\nなんのために特訓に付き合ってもらってると\\n思ってるんですか！"

# カズマ
# こうやって、おんぶして街まで連れて行くため。
337 = "こうやって、おんぶして街まで連れて行くため。"

# めぐみん
# ふっ、その通りです！
366 = "ふっ、その通りです！"

# カズマ
# なんでお前がいばってるんだよ！
361 = "なんでお前がいばってるんだよ！"

# カズマ（Ｍ）
# display as カズマ
# （この厨二病アークウィザード、\n　爆裂魔法へのこだわりが\n　もうどうしようもない変人レベルだ）
428 = "（この厨二病アークウィザード、\\n　爆裂魔法へのこだわりが\\n　もうどうしようもない変人レベルだ）"

# カズマ（Ｍ）
# display as カズマ
# （なにしろ、使える魔法は爆裂魔法のみ。\n　アークウィザードは上級職、攻撃魔法なら\n　なんだって覚えられるはずだが……）
437 = "（なにしろ、使える魔法は爆裂魔法のみ。\\n　アークウィザードは上級職、攻撃魔法なら\\n　なんだって覚えられるはずだが……）"

# カズマ（Ｍ）
# display as カズマ
# （爆裂魔法を使うためだけに\n　アークウィザードの道を選んだ、と言い切り、\n　他のスキルは一切身につける気がない）
442 = "（爆裂魔法を使うためだけに\\n　アークウィザードの道を選んだ、と言い切り、\\n　他のスキルは一切身につける気がない）"

# カズマ（Ｍ）
# display as カズマ
# （しかも、爆裂魔法は１日１発が限界。\n　使った後はこのとおり、ひとりで歩くことすら\n　できないというオチまでついている始末だ）
431 = "（しかも、爆裂魔法は１日１発が限界。\\n　使った後はこのとおり、ひとりで歩くことすら\\n　できないというオチまでついている始末だ）"

# カズマ
# はあ……。
363 = "はあ……。"

# めぐみん
# そんなに嫌そうにしなくても\nいいじゃないですか。
347 = "そんなに嫌そうにしなくても\\nいいじゃないですか。"

# カズマ
# いや、俺のため息は\nそういう意味じゃないんだけどな。
323 = "いや、俺のため息は\\nそういう意味じゃないんだけどな。"

# めぐみん
# どうせ、屋敷にいても\n働きもせずダラダラしているだけでしょう？
356 = "どうせ、屋敷にいても\\n働きもせずダラダラしているだけでしょう？"

# めぐみん
# ええと、アクアがよく言う\nヒキニートってやつですよね？
329 = "ええと、アクアがよく言う\\nヒキニートってやつですよね？"

# カズマ
# だ、誰がヒキニートだっ！\n俺は元引きこもりだけど、ニートじゃねーし！\n引きこもりとニートを一緒にすんな！
348 = "だ、誰がヒキニートだっ！\\n俺は元引きこもりだけど、ニートじゃねーし！\\n引きこもりとニートを一緒にすんな！"

# めぐみん
# でも、本当のことじゃないですか。\nお金の心配がなくなってから、\nずーっとグータラしてますし。
354 = "でも、本当のことじゃないですか。\\nお金の心配がなくなってから、\\nずーっとグータラしてますし。"

# カズマ
# 仕方ないだろ？\n今まで散々だったんだから。
388 = "仕方ないだろ？\\n今まで散々だったんだから。"

# カズマ（Ｍ）
# display as カズマ
# （意気揚々と転生してきた俺のこの異世界での\n　生活は……考えていたものとまったく\n　違っていた）
441 = "（意気揚々と転生してきた俺のこの異世界での\\n　生活は……考えていたものとまったく\\n　違っていた）"

# カズマ（Ｍ）
# display as カズマ
# （そもそも、最弱職の『冒険者』スタート\n　ってのからして予想外もいいとこだろ！）
435 = "（そもそも、最弱職の『冒険者』スタート\\n　ってのからして予想外もいいとこだろ！）"

# カズマ（Ｍ）
# display as カズマ
# （駆け出し冒険者の収入は不安定で、\n　馬小屋に寝泊まりするとか普通だし……）
445 = "（駆け出し冒険者の収入は不安定で、\\n　馬小屋に寝泊まりするとか普通だし……）"

# カズマ（Ｍ）
# display as カズマ
# （胸躍る冒険！　どころか、\n　日銭を稼ぐために肉体労働に勤しむ日々）
443 = "（胸躍る冒険！　どころか、\\n　日銭を稼ぐために肉体労働に勤しむ日々）"

# カズマ（Ｍ）
# display as カズマ
# （仲間を集めてクエストをクリアしても、\n　どういうわけか借金を背負うことになったりと\n　いいことなし！）
440 = "（仲間を集めてクエストをクリアしても、\\n　どういうわけか借金を背負うことになったりと\\n　いいことなし！）"

# カズマ（Ｍ）
# display as カズマ
# （その仲間も、このめぐみんといい、\n　連れてきてしまった女神といい……\n　って、まあ、それは置いとくとして）
434 = "（その仲間も、このめぐみんといい、\\n　連れてきてしまった女神といい……\\n　って、まあ、それは置いとくとして）"

# カズマ
# 色々あって、住む場所も確保して借金も完済、\nここから先の収入の心配もなくなったとなれば――
421 = "色々あって、住む場所も確保して借金も完済、\\nここから先の収入の心配もなくなったとなれば――"

# カズマ
# 今まで苦労した分を取り戻したくもなる！\nああ、なるとも！
387 = "今まで苦労した分を取り戻したくもなる！\\nああ、なるとも！"

# めぐみん
# だからといって、\nダメ人間生活をしていいわけではないです。
349 = "だからといって、\\nダメ人間生活をしていいわけではないです。"

# めぐみん
# 第一、カズマは魔王を倒すつもりなんですよね？\nだったら、まずはもっとレベルを上げなければ\n話になりません。
420 = "第一、カズマは魔王を倒すつもりなんですよね？\\nだったら、まずはもっとレベルを上げなければ\\n話になりません。"

# めぐみん
# 資金に余裕のある今こそ、\n討伐に精を出すべきですよ。
423 = "資金に余裕のある今こそ、\\n討伐に精を出すべきですよ。"

# カズマ
# う、うるせー！　正論を振りかざすなぁ！\nマジで捨ててくぞ！？
324 = "う、うるせー！　正論を振りかざすなぁ！\\nマジで捨ててくぞ！？"

# めぐみん
# さ、最低ですね！\nこっちだって絶対に捨てられませんよ！\n呪いの装備並みに引っ付いてやりますから！
339 = "さ、最低ですね！\\nこっちだって絶対に捨てられませんよ！\\n呪いの装備並みに引っ付いてやりますから！"

# カズマ
# ぐえええええ！\n締まってる、首締まってますぅぅ！！
336 = "ぐえええええ！\\n締まってる、首締まってますぅぅ！！"

# めぐみん
# 呪いですから！\nさあ、呪われよ呪われよ呪われよー！\n汝に闇の祝福を与えてやろーう！
395 = "呪いですから！\\nさあ、呪われよ呪われよ呪われよー！\\n汝に闇の祝福を与えてやろーう！"

# カズマ
# なんだそのアグレッシブな呪いはぁ！
358 = "なんだそのアグレッシブな呪いはぁ！"

[selections]
378 = "プロローグをスキップしない"
380 = "プロローグをスキップする"
325 = "うむ、今日のは悪くないぞ。"
# 386 = "今までで一番いい出来だ！"
# 404 = "普通だな。"
