# pr_05.txt.scn

[info]
266 = "pr_05"

[characters]
369 = "カズマ"
360 = "めぐみん"
366 = "アクア"
373 = "ダクネス"
372 = "カズマ（Ｍ）"

[character_subs]
# 369 = "カズマ"

[script]
# lines: 102

# カズマ
# 帰ったぞー。
386 = "帰ったぞー。"

# めぐみん
# ただいま戻りました。
334 = "ただいま戻りました。"

# アクア
# あ、やっと帰ってきたわね。
299 = "あ、やっと帰ってきたわね。"

# ダクネス
# おかえり、ふたりとも。\n先に夕食をいただいているぞ。
315 = "おかえり、ふたりとも。\\n先に夕食をいただいているぞ。"

# カズマ
# なんだよ、ちょっと待っててくれてもいいのに。
345 = "なんだよ、ちょっと待っててくれてもいいのに。"

# アクア
# はあ？　なに言ってんのよ。\n今日の夕食は――
348 = "はあ？　なに言ってんのよ。\\n今日の夕食は――"

# アクア
# この私の稼ぎによるものなんだから！\nカズマを待つ必要なんて、\nこれっぽっちもないのよ！
321 = "この私の稼ぎによるものなんだから！\\nカズマを待つ必要なんて、\\nこれっぽっちもないのよ！"

# カズマ
# お前の稼ぎ？
316 = "お前の稼ぎ？"

# めぐみん
# それにしても、いい匂いですね。\nメニューはなんですか？
331 = "それにしても、いい匂いですね。\\nメニューはなんですか？"

# アクア
# ふふん、見なさい。\n超！　高級肉を使った……すき焼きよ！
350 = "ふふん、見なさい。\\n超！　高級肉を使った……すき焼きよ！"

# めぐみん
# こ、これは！\n本当にすき焼きじゃないですか！
318 = "こ、これは！\\n本当にすき焼きじゃないですか！"

# カズマ
# うおおー！\nしかも霜降り肉がこんもりと！
311 = "うおおー！\\nしかも霜降り肉がこんもりと！"

# カズマ
# って、すき焼き？\nアクアさん、今すき焼きって言いましたか？
339 = "って、すき焼き？\\nアクアさん、今すき焼きって言いましたか？"

# アクア
# 言ったわよ？\nなに、カズマはすき焼き嫌いなの？
420 = "言ったわよ？\\nなに、カズマはすき焼き嫌いなの？"

# カズマ
# いや、そうじゃなくて……すき焼き？\nマジでそれ、すき焼きって料理なのか？
305 = "いや、そうじゃなくて……すき焼き？\\nマジでそれ、すき焼きって料理なのか？"

# アクア
# だから、そう言ってるじゃない。
335 = "だから、そう言ってるじゃない。"

# カズマ
# へえ……。
354 = "へえ……。"

# カズマ（Ｍ）
# display as カズマ
# （鍋で野菜や肉が煮込まれているこの光景……\n　俺もよく知っているすき焼きだ。\n　ファンタジー世界にもすき焼きってあるんだな）
437 = "（鍋で野菜や肉が煮込まれているこの光景……\\n　俺もよく知っているすき焼きだ。\\n　ファンタジー世界にもすき焼きってあるんだな）"

# カズマ（Ｍ）
# display as カズマ
# （これって関東風だよな？\n　もしかして、こっちにも\n　関西風と関東風みたいな差があるのか？）
430 = "（これって関東風だよな？\\n　もしかして、こっちにも\\n　関西風と関東風みたいな差があるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、別にどうでもいいか。\n　言いだしたら、きのこ派とたけのこ派くらいの\n　終わりなき闘争になりかねない）
427 = "（いや、別にどうでもいいか。\\n　言いだしたら、きのこ派とたけのこ派くらいの\\n　終わりなき闘争になりかねない）"

# カズマ（Ｍ）
# display as カズマ
# （それよりも、気になるのは……）
431 = "（それよりも、気になるのは……）"

# カズマ
# アクア。\nお前さっき、今日の夕食は\n自分の稼ぎで用意したって言ったよな？
367 = "アクア。\\nお前さっき、今日の夕食は\\n自分の稼ぎで用意したって言ったよな？"

# アクア
# ふふん、ちょっとした臨時収入があったのよ。
349 = "ふふん、ちょっとした臨時収入があったのよ。"

# アクア
# まあ、ホントなら\n私ひとりですき焼きを堪能するところだけど――
358 = "まあ、ホントなら\\n私ひとりですき焼きを堪能するところだけど――"

# アクア
# この寛大なアクア様が\nみんなにもご馳走してあげるわ。\n感謝しなさい！
320 = "この寛大なアクア様が\\nみんなにもご馳走してあげるわ。\\n感謝しなさい！"

# カズマ
# 何が感謝だ。\nツケを払うために俺から金を借りてたくせに。
378 = "何が感謝だ。\\nツケを払うために俺から金を借りてたくせに。"

# アクア
# さ、最近はしてないでしょ！？
322 = "さ、最近はしてないでしょ！？"

# カズマ
# つーか、食べる前に確認だ。
340 = "つーか、食べる前に確認だ。"

# カズマ
# さっき臨時収入って言ってたけど、\nお前、一体なにをやったんだ。
324 = "さっき臨時収入って言ってたけど、\\nお前、一体なにをやったんだ。"

# アクア
# ……は？\nなにそれ、どういう意味よ？
297 = "……は？\\nなにそれ、どういう意味よ？"

# カズマ
# 非合法なことをやったんじゃないかって\n聞いてるんだよ。
421 = "非合法なことをやったんじゃないかって\\n聞いてるんだよ。"

# アクア
# し、失礼ねっ！\n私は女神よ！？\nそんなことするわけないじゃない！
326 = "し、失礼ねっ！\\n私は女神よ！？\\nそんなことするわけないじゃない！"

# カズマ
# うわー、説得力がまるでないなー。\n日頃の行いって大切だなー。
312 = "うわー、説得力がまるでないなー。\\n日頃の行いって大切だなー。"

# アクア
# どういう意味よ。\n日頃の行いはいいじゃない。\n説得力だって充分でしょ？
344 = "どういう意味よ。\\n日頃の行いはいいじゃない。\\n説得力だって充分でしょ？"

# カズマ
# ああ、そう。
300 = "ああ、そう。"

# カズマ
# 人の物に手をつけたりしてないよな。
377 = "人の物に手をつけたりしてないよな。"

# アクア
# はあ！？　盗んだって言いたいわけ？\nこのヒキニート、女神を侮辱するなんて\nいい根性してるわね！
347 = "はあ！？　盗んだって言いたいわけ？\\nこのヒキニート、女神を侮辱するなんて\\nいい根性してるわね！"

# カズマ
# ね、念のための確認だって！\n変な疑いをかけて悪かったよ。
346 = "ね、念のための確認だって！\\n変な疑いをかけて悪かったよ。"

# アクア
# ふん、もういいわ！\nあんたはすき焼き抜きね。
353 = "ふん、もういいわ！\\nあんたはすき焼き抜きね。"

# アクア
# でも私は寛大だから、\n残り汁を舐めさせてあげる。
342 = "でも私は寛大だから、\\n残り汁を舐めさせてあげる。"

# カズマ
# ぐっ！　あ、ああ、いいぜ！\n不当な手段で手に入れた肉なんて\n食いたくもねーからな！
317 = "ぐっ！　あ、ああ、いいぜ！\\n不当な手段で手に入れた肉なんて\\n食いたくもねーからな！"

# めぐみん
# 明らかに肉に目が釘付けですが。
389 = "明らかに肉に目が釘付けですが。"

# カズマ
# それとも、お前への貢ぎ物か？\nへー、お前って本当に女神だったんだな。
330 = "それとも、お前への貢ぎ物か？\\nへー、お前って本当に女神だったんだな。"

# アクア
# ふふん！\nカズマも私が女神だって\nやーっと自覚したようね。
351 = "ふふん！\\nカズマも私が女神だって\\nやーっと自覚したようね。"

# アクア
# そうよ、この私には\n世界中の信者から貢ぎ物が届けられるの！
328 = "そうよ、この私には\\n世界中の信者から貢ぎ物が届けられるの！"

# カズマ
# え？　マジで？\nお前に貢ぎ物来るの？
314 = "え？　マジで？\\nお前に貢ぎ物来るの？"

# カズマ
# 冗談のつもりだったんだけど。\nそして、痛いとこを突かれて落ち込むお前を\nゲラゲラ笑ってやるつもりだったんだけど。
381 = "冗談のつもりだったんだけど。\\nそして、痛いとこを突かれて落ち込むお前を\\nゲラゲラ笑ってやるつもりだったんだけど。"

# アクア
# う、うう……。
307 = "う、うう……。"

# カズマ
# あー、やっぱり痛いとこだったんだ。\nだよなー、貢ぎ物があるんだったら\n貧乏生活してないもんなぁ。
302 = "あー、やっぱり痛いとこだったんだ。\\nだよなー、貢ぎ物があるんだったら\\n貧乏生活してないもんなぁ。"

# アクア
# う、うるさいうるさいうるさーーーい！
308 = "う、うるさいうるさいうるさーーーい！"

# ダクネス
# カズマ。\n疑う気持ちはわかるが、これは正真正銘、\nアクアが稼いだ金で用意したものだぞ？
371 = "カズマ。\\n疑う気持ちはわかるが、これは正真正銘、\\nアクアが稼いだ金で用意したものだぞ？"

# アクア
# さり気なくひどいこと言ってる！？
325 = "さり気なくひどいこと言ってる！？"

# アクア
# ああもう、ホントになんなのよー！\nもっと私を敬ってよ！　崇めてよーー！
301 = "ああもう、ホントになんなのよー！\\nもっと私を敬ってよ！　崇めてよーー！"

# カズマ（Ｍ）
# display as カズマ
# （……この喚いているのがアクア。\n　俺をこのろくでもない世界に転生させた女神だ）
425 = "（……この喚いているのがアクア。\\n　俺をこのろくでもない世界に転生させた女神だ）"

# カズマ（Ｍ）
# display as カズマ
# （可愛いだけが取り柄、\n　知力が低くて性格もアレ、ぐうたらで\n　まったく使えないダメな女神、略して駄女神だ）
436 = "（可愛いだけが取り柄、\\n　知力が低くて性格もアレ、ぐうたらで\\n　まったく使えないダメな女神、略して駄女神だ）"

# カズマ（Ｍ）
# display as カズマ
# （そんな様子だから、周りは\n　こいつが女神だなんて誰も信じちゃいない）
432 = "（そんな様子だから、周りは\\n　こいつが女神だなんて誰も信じちゃいない）"

# カズマ（Ｍ）
# display as カズマ
# （一応、アークプリーストという上級職で\n　回復とかで役に立つっていえば立つんだが、\n　それ以上にトラブルも引き起こすんだよな……）
435 = "（一応、アークプリーストという上級職で\\n　回復とかで役に立つっていえば立つんだが、\\n　それ以上にトラブルも引き起こすんだよな……）"

# カズマ
# 敬う？　崇める？\nそんな台詞は、普段から\n真面目に女神らしいことをやってから言えよ。
388 = "敬う？　崇める？\\nそんな台詞は、普段から\\n真面目に女神らしいことをやってから言えよ。"

# アクア
# ううう～う！
310 = "ううう～う！"

# めぐみん
# アクアは自分が女神だと\n思い込んでいるだけなのでしょう？\nそんな風に言っては可哀想ですよ。
368 = "アクアは自分が女神だと\\n思い込んでいるだけなのでしょう？\\nそんな風に言っては可哀想ですよ。"

# アクア
# う、うわぁぁぁぁぁんっ！
309 = "う、うわぁぁぁぁぁんっ！"

# ダクネス
# めぐみん、カズマも、もう止めてやれ。\nもし言い足りないのなら……
361 = "めぐみん、カズマも、もう止めてやれ。\\nもし言い足りないのなら……"

# ダクネス
# わ、私に言ってくれ！\n思う存分、罵ってくれていいぞ！\nさあ！　さあ！！
363 = "わ、私に言ってくれ！\\n思う存分、罵ってくれていいぞ！\\nさあ！　さあ！！"

# カズマ（Ｍ）
# display as カズマ
# （……あー、始まったよ）
424 = "（……あー、始まったよ）"

# カズマ（Ｍ）
# display as カズマ
# （この美人はダクネス。\n　職業はクルセイダー、\n　つまり、前線に立ってパーティーを守る騎士だ）
429 = "（この美人はダクネス。\\n　職業はクルセイダー、\\n　つまり、前線に立ってパーティーを守る騎士だ）"

# カズマ（Ｍ）
# display as カズマ
# （だが、ドＭだ。\n　言葉責めから羞恥プレイまで\n　なんでもござれ――）
433 = "（だが、ドＭだ。\\n　言葉責めから羞恥プレイまで\\n　なんでもござれ――）"

# カズマ（Ｍ）
# display as カズマ
# （モンスターからの攻撃を受けるのすら\n　一種のプレイという、生粋の変態だ）
434 = "（モンスターからの攻撃を受けるのすら\\n　一種のプレイという、生粋の変態だ）"

# カズマ（Ｍ）
# display as カズマ
# （防御力は凄まじいが\n　不器用すぎて攻撃はちっとも当たらない。\n　つまり、戦力にならない）
438 = "（防御力は凄まじいが\\n　不器用すぎて攻撃はちっとも当たらない。\\n　つまり、戦力にならない）"

# カズマ（Ｍ）
# display as カズマ
# （このダクネス、アクア、そしてめぐみん。\n　この３人が俺の仲間だ。\n　あはははは、なにこの問題児揃い）
428 = "（このダクネス、アクア、そしてめぐみん。\\n　この３人が俺の仲間だ。\\n　あはははは、なにこの問題児揃い）"

# カズマ
# あー、アクア？\nその臨時収入ってのはどうやって手に入れたんだ？\n商店街のバイトか。
303 = "あー、アクア？\\nその臨時収入ってのはどうやって手に入れたんだ？\\n商店街のバイトか。"

# アクア
# ちっがうわよ！　クエストよ！
336 = "ちっがうわよ！　クエストよ！"

# ダクネス
# 先日、さる商家より\n開かずの宝箱を開けて欲しいという\nクエストが出たんだ。
380 = "先日、さる商家より\\n開かずの宝箱を開けて欲しいという\\nクエストが出たんだ。"

# アクア
# 成功した場合、中身を山分けってなってたのよ！\n開けるだけでオッケーとか、\nこれはもう受けるしかないでしょ？
387 = "成功した場合、中身を山分けってなってたのよ！\\n開けるだけでオッケーとか、\\nこれはもう受けるしかないでしょ？"

# カズマ
# へー、そんなクエストがあったのか。\n楽そうなのに、よく何日も手つかずで残ってたな。
356 = "へー、そんなクエストがあったのか。\\n楽そうなのに、よく何日も手つかずで残ってたな。"

# めぐみん
# それはそうですよ。\n開かずの宝箱なんて、どう考えても面倒ですし。
332 = "それはそうですよ。\\n開かずの宝箱なんて、どう考えても面倒ですし。"

# カズマ
# 面倒？
423 = "面倒？"

# めぐみん
# 例えば、中に妙な物が封印されていたら\n退治まで押しつけられます。
379 = "例えば、中に妙な物が封印されていたら\\n退治まで押しつけられます。"

# カズマ（Ｍ）
# display as カズマ
# （あー、なるほど。\n　後先考えず、楽して高収入なクエストに\n　飛びついたのか、この駄女神）
426 = "（あー、なるほど。\\n　後先考えず、楽して高収入なクエストに\\n　飛びついたのか、この駄女神）"

# アクア
# ま、開かずの宝箱なんて\nこのアクア様にかかればちょちょいのちょいよ。
357 = "ま、開かずの宝箱なんて\\nこのアクア様にかかればちょちょいのちょいよ。"

# カズマ
# へえ、お前、解錠なんてできたんだな。
355 = "へえ、お前、解錠なんてできたんだな。"

# アクア
# そんなわけないでしょ。
333 = "そんなわけないでしょ。"

# アクア
# ちょっと調べたら、\n悪霊がカギに引きこもっていたの。\nそれを浄化したら開いたのよ。
338 = "ちょっと調べたら、\\n悪霊がカギに引きこもっていたの。\\nそれを浄化したら開いたのよ。"

# アクア
# ふふーん、浄化は私の専門分野。\nまさに私のためのクエストって感じだったわね。
352 = "ふふーん、浄化は私の専門分野。\\nまさに私のためのクエストって感じだったわね。"

# カズマ
# さすが腐っても女神だな。
323 = "さすが腐っても女神だな。"

# アクア
# 腐ってないっ！\n私は清浄で清廉な水の女神よ！？\n腐るなんてことから一番縁遠いの！
419 = "腐ってないっ！\\n私は清浄で清廉な水の女神よ！？\\n腐るなんてことから一番縁遠いの！"

# カズマ
# 知ってるか？\n水も淀むと腐るんだぞ？
416 = "知ってるか？\\n水も淀むと腐るんだぞ？"

# アクア
# 私の水は腐らないのー！
417 = "私の水は腐らないのー！"

# カズマ
# とにかく、このすき焼きは\n正しく得た金で買った物ってことか。\nだったら、遠慮なく食うとするか！
343 = "とにかく、このすき焼きは\\n正しく得た金で買った物ってことか。\\nだったら、遠慮なく食うとするか！"

# アクア
# ちょっと、無視しないでったら！
337 = "ちょっと、無視しないでったら！"

# ダクネス
# まあまあ、アクア。\n早く食べないと、せっかくの肉が\n煮え過ぎてしまうぞ？
359 = "まあまあ、アクア。\\n早く食べないと、せっかくの肉が\\n煮え過ぎてしまうぞ？"

# めぐみん
# 肉に罪はありません。\n美味しく食べてあげましょう。
418 = "肉に罪はありません。\\n美味しく食べてあげましょう。"

# アクア
# しょうがないわね。\nじゃあ、みんな席に着きなさい。\n改めて乾杯しましょ。
327 = "しょうがないわね。\\nじゃあ、みんな席に着きなさい。\\n改めて乾杯しましょ。"

# アクア
# ん、んんっ！\nでは、今日のすき焼きパーティー開催を――
365 = "ん、んんっ！\\nでは、今日のすき焼きパーティー開催を――"

# ダクネス
# めぐみん、食べる前に手を洗ってこないと。
362 = "めぐみん、食べる前に手を洗ってこないと。"

# めぐみん
# えー、大丈夫ですよー。
313 = "えー、大丈夫ですよー。"

# アクア
# このアクア様に感謝しつつ――
319 = "このアクア様に感謝しつつ――"

# ダクネス
# いいから行ってこい。\nいただきますは待っててやるから。
304 = "いいから行ってこい。\\nいただきますは待っててやるから。"

# めぐみん
# カズマ、勝手に食べ始めたら怒りますからね。
370 = "カズマ、勝手に食べ始めたら怒りますからね。"

# アクア
# 乾杯を……。
375 = "乾杯を……。"

# カズマ
# わかってるよ。
364 = "わかってるよ。"

# アクア
# う、うぅ……。
306 = "う、うぅ……。"

# カズマ
# で、アクア。\n乾杯がどうしたって？
341 = "で、アクア。\\n乾杯がどうしたって？"

[selections]
422 = "非合法なことをやったんじゃないか？"
376 = "人の物に手をつけたりしてないよな"
329 = "それとも、お前への貢ぎ物か？"
