# pr_09.txt.scn

[info]
213 = "pr_09"

[characters]
301 = "カズマ"
298 = "アクア"
292 = "めぐみん"
309 = "バニル"
307 = "ダクネス"
305 = "カズマ（Ｍ）"
300 = "ウィズ"

[character_subs]
# 301 = "カズマ"

[script]
# lines: 81

# カズマ
# えーっと、この指輪が\nはた迷惑な兄弟によって作られた物だってのは\nわかったけどさ――
263 = "えーっと、この指輪が\\nはた迷惑な兄弟によって作られた物だってのは\\nわかったけどさ――"

# カズマ
# 結局どうすれば取ることができるんだ？\n呪いじゃないからアクアでも無理なんだろ？
358 = "結局どうすれば取ることができるんだ？\\n呪いじゃないからアクアでも無理なんだろ？"

# アクア
# ええ、方向は最低だけど、\nこの指輪にこもっているのは\n怨念とは異なる純粋な願いだから。
262 = "ええ、方向は最低だけど、\\nこの指輪にこもっているのは\\n怨念とは異なる純粋な願いだから。"

# めぐみん
# 本当に最低ですね。
325 = "本当に最低ですね。"

# カズマ
# バニル、どうなんだ？\nなにか方法があるのか？
310 = "バニル、どうなんだ？\\nなにか方法があるのか？"

# バニル
# ふむ。\n思いつく限り、方法はふたつ存在する。
289 = "ふむ。\\n思いつく限り、方法はふたつ存在する。"

# バニル
# まずひとつ。\n指輪にこめられた願いを成就させる。
290 = "まずひとつ。\\n指輪にこめられた願いを成就させる。"

# めぐみん
# え……。\nそれって……。
260 = "え……。\\nそれって……。"

# バニル
# この場合は、男の無念を晴らすこと。\n女性の下着を盗み続けるという念願の達成だ。
270 = "この場合は、男の無念を晴らすこと。\\n女性の下着を盗み続けるという念願の達成だ。"

# めぐみん
# やっぱりですか！
294 = "やっぱりですか！"

# アクア
# 絶対に嫌よ！\nこの先ずっと下着を盗まれるなんて\n冗談じゃないわっ！
359 = "絶対に嫌よ！\\nこの先ずっと下着を盗まれるなんて\\n冗談じゃないわっ！"

# ダクネス
# 私も認められんな。\nそんなプレイは望むところではない。
356 = "私も認められんな。\\nそんなプレイは望むところではない。"

# カズマ
# 俺だって嫌だ、そんなの。
317 = "俺だって嫌だ、そんなの。"

# バニル
# ならば、もうひとつの方法――\n魔法効果の仕組みを解明し、\n強制的に解除するしかあるまい。
285 = "ならば、もうひとつの方法――\\n魔法効果の仕組みを解明し、\\n強制的に解除するしかあるまい。"

# カズマ
# え！？\nそんなことできるのか？
264 = "え！？\\nそんなことできるのか？"

# バニル
# フハハハハハ！\n我輩はこの世のすべてを見通す大悪魔、\nその程度、造作もなし！
311 = "フハハハハハ！\\n我輩はこの世のすべてを見通す大悪魔、\\nその程度、造作もなし！"

# バニル
# と、言いたいところだが、んん～！\nこれは相当に複雑な術式の構造であるなぁ。\nただの人間にしてはやるではないか。
278 = "と、言いたいところだが、んん～！\\nこれは相当に複雑な術式の構造であるなぁ。\\nただの人間にしてはやるではないか。"

# カズマ
# マジで……バニルでも無理なのか。
314 = "マジで……バニルでも無理なのか。"

# バニル
# おっと、無理と言った覚えはないぞ？\nただ、複雑なので色々と手間がかかる分、\n面倒なのだ。
267 = "おっと、無理と言った覚えはないぞ？\\nただ、複雑なので色々と手間がかかる分、\\n面倒なのだ。"

# カズマ
# 頼むっ！\nそこをなんとかしてくれ～！
363 = "頼むっ！\\nそこをなんとかしてくれ～！"

# バニル
# では、３０００万エリスである。
276 = "では、３０００万エリスである。"

# カズマ
# ……は？
256 = "……は？"

# バニル
# 術式の構造を解析する技術費、手間賃、\n魔法効果を解除する秘薬の入手――
360 = "術式の構造を解析する技術費、手間賃、\\n魔法効果を解除する秘薬の入手――"

# バニル
# それらをひとまとめにし、\n３０００万エリスで手を打とうではないか。
274 = "それらをひとまとめにし、\\n３０００万エリスで手を打とうではないか。"

# カズマ
# はああああ！？\nさ、３０００万エリス！？
287 = "はああああ！？\\nさ、３０００万エリス！？"

# バニル
# 言っておくが、今後の出世払いや\n分割払いなど論外。
361 = "言っておくが、今後の出世払いや\\n分割払いなど論外。"

# バニル
# 元手がなければ解析を進めることは不可能、\n秘薬の入手もできぬのだ。
318 = "元手がなければ解析を進めることは不可能、\\n秘薬の入手もできぬのだ。"

# カズマ（Ｍ）
# display as カズマ
# （む、無理だ！\n　今の俺は、多少、懐に余裕はあるが\n　そんな大金を払うほどじゃない！）
372 = "（む、無理だ！\\n　今の俺は、多少、懐に余裕はあるが\\n　そんな大金を払うほどじゃない！）"

# ウィズ
# あの、バニルさん？\nいくらなんでも３０００万エリスはちょっと。
259 = "あの、バニルさん？\\nいくらなんでも３０００万エリスはちょっと。"

# バニル
# この程度、当然である。\nむしろ、今後を考えるとこれでも足りないのだ。
271 = "この程度、当然である。\\nむしろ、今後を考えるとこれでも足りないのだ。"

# ウィズ
# え？　足りない？
265 = "え？　足りない？"

# バニル
# ともかく、どうするのだ小僧。\n我輩としては、これ以上譲ることはできぬな。
279 = "ともかく、どうするのだ小僧。\\n我輩としては、これ以上譲ることはできぬな。"

# カズマ
# ぐ、ぐぐぐぐぐぐ……。
269 = "ぐ、ぐぐぐぐぐぐ……。"

# アクア
# ちょっと待ちなさい！\nこれは私達にとっても由々しき問題なんだから、\n勝手に話を進めないでよ！
275 = "ちょっと待ちなさい！\\nこれは私達にとっても由々しき問題なんだから、\\n勝手に話を進めないでよ！"

# バニル
# なんだ？\n今後、小僧に下着を盗まれ続ける娘よ。
286 = "なんだ？\\n今後、小僧に下着を盗まれ続ける娘よ。"

# アクア
# まだそうと決まってないんですけど！\nていうか、そんな屈辱の日々なんて\nお断りなんですけど！
291 = "まだそうと決まってないんですけど！\\nていうか、そんな屈辱の日々なんて\\nお断りなんですけど！"

# アクア
# ３０００万エリス、払えばいいんでしょ？\nわかったわ、やってあげようじゃない！
379 = "３０００万エリス、払えばいいんでしょ？\\nわかったわ、やってあげようじゃない！"

# アクア
# 私達全員の力を合わせて、\nその顔に札束を叩きつけてあげるわ！
357 = "私達全員の力を合わせて、\\nその顔に札束を叩きつけてあげるわ！"

# カズマ
# あ、アクア？
257 = "あ、アクア？"

# ダクネス
# カズマは私達の仲間だ。\n仲間の危機を放っておくことなど、\nできるわけがない。
304 = "カズマは私達の仲間だ。\\n仲間の危機を放っておくことなど、\\nできるわけがない。"

# めぐみん
# 盗んだ物を売り払って小金を稼いだり、\nとか、悪い予感しかしませんし――
327 = "盗んだ物を売り払って小金を稼いだり、\\nとか、悪い予感しかしませんし――"

# めぐみん
# 一刻も早くお金を貯めて、\nカズマを、指輪の脅威から解放しましょう。
315 = "一刻も早くお金を貯めて、\\nカズマを、指輪の脅威から解放しましょう。"

# カズマ
# ダクネス、めぐみんも……。
308 = "ダクネス、めぐみんも……。"

# カズマ（Ｍ）
# display as カズマ
# （でも、めぐみん、\n　俺のことをそんな風に思ってるのね！）
370 = "（でも、めぐみん、\\n　俺のことをそんな風に思ってるのね！）"

# ウィズ
# よかったですね！\nみなさん、こんなにもカズマさんを\n心配してくれているんですよ？
295 = "よかったですね！\\nみなさん、こんなにもカズマさんを\\n心配してくれているんですよ？"

# カズマ（Ｍ）
# display as カズマ
# （いや、俺への心配じゃなくて\n　単にパンツを盗まれるのが\n　嫌だからだろうけどな）
365 = "（いや、俺への心配じゃなくて\\n　単にパンツを盗まれるのが\\n　嫌だからだろうけどな）"

# カズマ（Ｍ）
# display as カズマ
# （でも、ちょっと意外だ。\n　特にアクアなんて、自分で金を貯めて\n　なんとかしろって言いそうなのに）
369 = "（でも、ちょっと意外だ。\\n　特にアクアなんて、自分で金を貯めて\\n　なんとかしろって言いそうなのに）"

# めぐみん
# んっ、んっ。
297 = "んっ、んっ。"

# アクア
# なに？
284 = "なに？"

# めぐみん
# アクア、もしお金を貯められなかった場合は……\nわかっていますよね？
299 = "アクア、もしお金を貯められなかった場合は……\\nわかっていますよね？"

# アクア
# ええ、任せて。\n私の回復魔法なら、\n切った指くらい元通りにできるはずだわ。
261 = "ええ、任せて。\\n私の回復魔法なら、\\n切った指くらい元通りにできるはずだわ。"

# ダクネス
# そうか。\nさすがはアークプリーストだな。
273 = "そうか。\\nさすがはアークプリーストだな。"

# カズマ
# お前らー、聞こえてるぞー。
268 = "お前らー、聞こえてるぞー。"

# アクア
# や、やだぁ、もう！\nカズマさんってば顔が怖い。
293 = "や、やだぁ、もう！\\nカズマさんってば顔が怖い。"

# アクア
# 大丈夫、今のは最終手段よ。\nいきなりそんなことをするのは寝覚めが悪いし、\nひとまずお金は稼ぐわ。
322 = "大丈夫、今のは最終手段よ。\\nいきなりそんなことをするのは寝覚めが悪いし、\\nひとまずお金は稼ぐわ。"

# カズマ（Ｍ）
# display as カズマ
# （ホント、こいつのどこが女神なんだよ）
374 = "（ホント、こいつのどこが女神なんだよ）"

# ダクネス
# わ、私としては、ダメな男のために\n身を粉にして働く女という感じで……\nふふ、ふふふ、いい……！
296 = "わ、私としては、ダメな男のために\\n身を粉にして働く女という感じで……\\nふふ、ふふふ、いい……！"

# カズマ
# 言ってるお前がダメだろ。
362 = "言ってるお前がダメだろ。"

# バニル
# では商談成立だ。\n３０００万エリスを工面したならば、\n我輩の元に来るがいい。
277 = "では商談成立だ。\\n３０００万エリスを工面したならば、\\n我輩の元に来るがいい。"

# アクア
# ３０００万エリスふっかけといて\n実はできませーん、なんてのはなしよ？
380 = "３０００万エリスふっかけといて\\n実はできませーん、なんてのはなしよ？"

# バニル
# なに、我々悪魔は契約にはうるさいので\n信頼してもらって結構である。\n甘い言葉で人を騙す詐欺集団とは違うのでな！
282 = "なに、我々悪魔は契約にはうるさいので\\n信頼してもらって結構である。\\n甘い言葉で人を騙す詐欺集団とは違うのでな！"

# カズマ（Ｍ）
# display as カズマ
# （いや、まあ、アクア達が\n　やる気になってくれたのは有り難いんだが）
364 = "（いや、まあ、アクア達が\\n　やる気になってくれたのは有り難いんだが）"

# カズマ（Ｍ）
# display as カズマ
# （３０００万エリスなんて大金、\n　どうやって稼げばいいんだ？）
378 = "（３０００万エリスなんて大金、\\n　どうやって稼げばいいんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （コツコツ貯める、なんてのんびり構えてたら\n　マジで指を切られかねないし……\n　手っ取り早く、金を稼ぐ方法を考えないと）
373 = "（コツコツ貯める、なんてのんびり構えてたら\\n　マジで指を切られかねないし……\\n　手っ取り早く、金を稼ぐ方法を考えないと）"

# アクア
# なにしてんのよカズマ！\n早く屋敷に戻って、お金稼ぎの作戦会議よ！
283 = "なにしてんのよカズマ！\\n早く屋敷に戻って、お金稼ぎの作戦会議よ！"

# カズマ
# お、おう。
266 = "お、おう。"

# ウィズ
# カズマさん、頑張ってくださいね。\nなにかお手伝いできることがあったら\n遠慮なく言ってください。
302 = "カズマさん、頑張ってくださいね。\\nなにかお手伝いできることがあったら\\n遠慮なく言ってください。"

# カズマ
# ああ、ありがとな。
258 = "ああ、ありがとな。"

# アクア
# カーズーマー！
306 = "カーズーマー！"

# カズマ
# はいはい、今行く。\nそんじゃなウィズ、バニル。
288 = "はいはい、今行く。\\nそんじゃなウィズ、バニル。"

# バニル
# せいぜい足掻き努力するがいい。\n異邦の地にて、下着泥棒と成り果てた小僧よ。
272 = "せいぜい足掻き努力するがいい。\\n異邦の地にて、下着泥棒と成り果てた小僧よ。"

# カズマ
# なってねーよ！
281 = "なってねーよ！"

# カズマ（Ｍ）
# display as カズマ
# （そういや、俺が今朝持ってたパンツは\n　誰のなんだ？）
368 = "（そういや、俺が今朝持ってたパンツは\\n　誰のなんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （素知らぬ顔をしてるけど……\n　今朝の反応といい、３人のうちの\n　誰かだってのは間違いないよな）
377 = "（素知らぬ顔をしてるけど……\\n　今朝の反応といい、３人のうちの\\n　誰かだってのは間違いないよな）"

# カズマ（Ｍ）
# display as カズマ
# （うーむ、盗まれた方としては\n　なんに使われるか気が気じゃないはず。\n　さっき、めぐみんもそう言ってたし）
366 = "（うーむ、盗まれた方としては\\n　なんに使われるか気が気じゃないはず。\\n　さっき、めぐみんもそう言ってたし）"

# カズマ（Ｍ）
# display as カズマ
# （でも盗んじまうのはあくまで指輪のせいで、\n　どうしようもない。\n　となると……）
371 = "（でも盗んじまうのはあくまで指輪のせいで、\\n　どうしようもない。\\n　となると……）"

# カズマ（Ｍ）
# display as カズマ
# （俺にできるのは、持ち主に返すことだよな？）
375 = "（俺にできるのは、持ち主に返すことだよな？）"

# カズマ（Ｍ）
# display as カズマ
# （盗んでしまった事実を反省し、\n　誠意を持って紳士的にお返しする！\n　そうだ！　それだ！）
376 = "（盗んでしまった事実を反省し、\\n　誠意を持って紳士的にお返しする！\\n　そうだ！　それだ！）"

# カズマ（Ｍ）
# display as カズマ
# （きちんと持ち主に返して自分が紳士であると証明\n　する！　それは決して、己のパンツを前に恥じら\n　う姿をみたいなんてやましい気持ちではなく――）
367 = "（きちんと持ち主に返して自分が紳士であると証明\\n　する！　それは決して、己のパンツを前に恥じら\\n　う姿をみたいなんてやましい気持ちではなく――）"

# アクア
# カズマさん？\n顔がいやらしーく歪んでいますけど、\nなにを考えてらっしゃるのかしらぁ？
303 = "カズマさん？\\n顔がいやらしーく歪んでいますけど、\\nなにを考えてらっしゃるのかしらぁ？"

# カズマ
# な、なんでもないですよっ！？
280 = "な、なんでもないですよっ！？"

