# pr_00.txt.scn

[info]
105 = "pr_00"
156 = "スキップ"
157 = "チュートリアル"

[characters]
162 = "バニル"

[character_subs]

[script]
# lines: 22

# monologue
# チュートリアルをスキップしますか？
159 = "チュートリアルをスキップしますか？"

# バニル
# ふははははははははっ。
152 = "ふははははははははっ。"

# バニル
# 我輩こそは、この世のすべてを見通す大悪魔、\nバニルである。\nこの名、その脳に刻み込んでおくといい。
166 = "我輩こそは、この世のすべてを見通す大悪魔、\\nバニルである。\\nこの名、その脳に刻み込んでおくといい。"

# バニル
# 映像を映す機械の前にいる諸君らから\nなぜチュートリアルに女の子が出てこないのか！との\n憤りを感じる、感じるぞ！
167 = "映像を映す機械の前にいる諸君らから\\nなぜチュートリアルに女の子が出てこないのか！との\\n憤りを感じる、感じるぞ！"

# バニル
# この悪感情。\n大変に美味である。
147 = "この悪感情。\\n大変に美味である。"

# バニル
# わざわざあのポンコツ店主から\nチュートリアル説明の座を奪った\n甲斐があったというものだ。
154 = "わざわざあのポンコツ店主から\\nチュートリアル説明の座を奪った\\n甲斐があったというものだ。"

# バニル
# これで、何の説明もしないままチュートリアルを\n終えてしまうことこそ、我輩に取っては最高に\n楽しい展開になりそうなのだが――
150 = "これで、何の説明もしないままチュートリアルを\\n終えてしまうことこそ、我輩に取っては最高に\\n楽しい展開になりそうなのだが――"

# バニル
# 悪魔は契約には厳しいからな。\nここではきちんと説明してやろう。\nありがたく講釈を聞くが良い。
165 = "悪魔は契約には厳しいからな。\\nここではきちんと説明してやろう。\\nありがたく講釈を聞くが良い。"

# バニル
# このゲームは、異界から来てハーレム状態に\nあるにも関わらず、超奥手で何も進展がない小僧が\nある騒動に巻き込まれる物語を描いたものである。
145 = "このゲームは、異界から来てハーレム状態に\\nあるにも関わらず、超奥手で何も進展がない小僧が\\nある騒動に巻き込まれる物語を描いたものである。"

# バニル
# まあ騒動と言ってもそんな大したことではない。\n生命の危機にさらされるくらいだ。
153 = "まあ騒動と言ってもそんな大したことではない。\\n生命の危機にさらされるくらいだ。"

# バニル
# あの小僧はことあるごとに死んでは\n憎き神に何度も生き返させられている\n生活を送っているらしいからな。
144 = "あの小僧はことあるごとに死んでは\\n憎き神に何度も生き返させられている\\n生活を送っているらしいからな。"

# バニル
# この程度の困難など、なんでもないだろう。
148 = "この程度の困難など、なんでもないだろう。"

# バニル
# 物語は５つの章に分かれて展開する。
169 = "物語は５つの章に分かれて展開する。"

# バニル
# ５章まで無事物語を読み終えられた時、\n親密度の高いヒロインとの物語が展開する。\nというお約束の流れだ。
179 = "５章まで無事物語を読み終えられた時、\\n親密度の高いヒロインとの物語が展開する。\\nというお約束の流れだ。"

# バニル
# 親密度については\nパラメータ画面で確認ができるぞ。\n利用するといいだろう。
178 = "親密度については\\nパラメータ画面で確認ができるぞ。\\n利用するといいだろう。"

# バニル
# 親密度が同じヒロインがいた場合、\n優先度が発動する。\nこれもお約束の流れだ。
177 = "親密度が同じヒロインがいた場合、\\n優先度が発動する。\\nこれもお約束の流れだ。"

# バニル
# なぜこの順番なのか？\nなんてやぼなことは疑問に思わないことだ。
151 = "なぜこの順番なのか？\\nなんてやぼなことは疑問に思わないことだ。"

# バニル
# ヒロインとの物語が始まった後は\n友情度というパラメータが登場する。
163 = "ヒロインとの物語が始まった後は\\n友情度というパラメータが登場する。"

# バニル
# この友情度の数値でエンディングが分かれる。\nこれもお約束の流れだな。
146 = "この友情度の数値でエンディングが分かれる。\\nこれもお約束の流れだな。"

# バニル
# これで、ゲームの簡単な流れはわかっただろう。\nでは、次のチュートリアルで\nまた会おうではないか？
149 = "これで、ゲームの簡単な流れはわかっただろう。\\nでは、次のチュートリアルで\\nまた会おうではないか？"

# バニル
# 次回もきちんと吾輩が\nレクチャーしてやるからな。\nありがたくチュートリアルを拝むがいい！
168 = "次回もきちんと吾輩が\\nレクチャーしてやるからな。\\nありがたくチュートリアルを拝むがいい！"

# バニル
# ふははははははははっ。
# 152 = "ふははははははははっ。"

[selections]
158 = "チュートリアルをスキップしない"
160 = "チュートリアルをスキップする"
