# pr_02.txt.scn

[info]
106 = "pr_02"

[characters]
149 = "カズマ（Ｍ）"
145 = "めぐみん"
148 = "カズマ"

[character_subs]
# 148 = "カズマ"

[script]
# lines: 26

# カズマ（Ｍ）
# display as カズマ
# （あー、マジで死ぬかと思った。\n　こいつ魔法使いのくせに\n　意外に力があるんだよな）
161 = "（あー、マジで死ぬかと思った。\\n　こいつ魔法使いのくせに\\n　意外に力があるんだよな）"

# めぐみん
# ふふふ、最初から柔順にしていれば\n我が呪いをその身に受けることも\nなかったというのに……愚かな男よ。
142 = "ふふふ、最初から柔順にしていれば\\n我が呪いをその身に受けることも\\nなかったというのに……愚かな男よ。"

# カズマ
# ……ん？\nおいめぐみん、ちょっと降ろすぞ、いいか？
126 = "……ん？\\nおいめぐみん、ちょっと降ろすぞ、いいか？"

# めぐみん
# え？　なんでですか？
131 = "え？　なんでですか？"

# カズマ
# なんか地面に落ちてるんだよ。\n気になるんで確認したい。
138 = "なんか地面に落ちてるんだよ。\\n気になるんで確認したい。"

# めぐみん
# ……拾い食いですか。
127 = "……拾い食いですか。"

# カズマ
# しねーよ、そんなこと！
133 = "しねーよ、そんなこと！"

# カズマ
# えーっと、確かこの辺に……\nお、あったあった。
130 = "えーっと、確かこの辺に……\\nお、あったあった。"

# カズマ
# なんだ、これ。\n指輪か？
139 = "なんだ、これ。\\n指輪か？"

# めぐみん
# みたいです。\n落とし物でしょうか？
144 = "みたいです。\\n落とし物でしょうか？"

# カズマ
# おおっ！？\nでっかい宝石がついてるんだけど！\nおいおいおいおい、これ本物か？
132 = "おおっ！？\\nでっかい宝石がついてるんだけど！\\nおいおいおいおい、これ本物か？"

# めぐみん
# それは鑑定して貰わないとわかりませんが、\n装飾も細かく見事です。\n相当な値打ち物に見えますね。
137 = "それは鑑定して貰わないとわかりませんが、\\n装飾も細かく見事です。\\n相当な値打ち物に見えますね。"

# カズマ
# ふ、ふふふふふふふ……。\nそうか、値打ち物か。
140 = "ふ、ふふふふふふふ……。\\nそうか、値打ち物か。"

# カズマ
# よし、こいつは拾っていこう。\n売り払えば生活費の足しになるだろ？
146 = "よし、こいつは拾っていこう。\\n売り払えば生活費の足しになるだろ？"

# めぐみん
# 拾うんですか？
155 = "拾うんですか？"

# カズマ
# 別に、拾っちゃダメってことはないよな？
151 = "別に、拾っちゃダメってことはないよな？"

# めぐみん
# そうですが、むやみやたらに\n物を拾うのは危険ですよ？
135 = "そうですが、むやみやたらに\\n物を拾うのは危険ですよ？"

# めぐみん
# それだって、持てあまされて捨てられた\n呪いの指輪かもしれません。
136 = "それだって、持てあまされて捨てられた\\n呪いの指輪かもしれません。"

# カズマ
# 呪いの指輪……。\nそんな物があるのか、さすがファンタジー。
153 = "呪いの指輪……。\\nそんな物があるのか、さすがファンタジー。"

# めぐみん
# ふぁんたじー？
141 = "ふぁんたじー？"

# カズマ
# あ、いや、なんでもない。
128 = "あ、いや、なんでもない。"

# カズマ
# まあ、こいつは違うだろ。\n呪われたアイテムともなれば、\nもっと禍々しい雰囲気を放ったりしてるだろ。
143 = "まあ、こいつは違うだろ。\\n呪われたアイテムともなれば、\\nもっと禍々しい雰囲気を放ったりしてるだろ。"

# めぐみん
# ん……。\nまあ、それもそうですが。
147 = "ん……。\\nまあ、それもそうですが。"

# カズマ
# じゃ、屋敷に帰る前にウィズに鑑定して貰うか。
134 = "じゃ、屋敷に帰る前にウィズに鑑定して貰うか。"

# カズマ
# 行くぞ、めぐみん。\nもうひとりで歩けるよな？
160 = "行くぞ、めぐみん。\\nもうひとりで歩けるよな？"

# めぐみん
# あ、ちょっとカズマ！\n置いていかないでくださいよ！
129 = "あ、ちょっとカズマ！\\n置いていかないでくださいよ！"

