# pr_06.txt.scn

[info]
131 = "pr_06"

[characters]
179 = "カズマ"
180 = "カズマ（Ｍ）"
178 = "アクア"

[character_subs]
# 179 = "カズマ"

[script]
# lines: 58

# カズマ
# んー、んあ……？
177 = "んー、んあ……？"

# カズマ（Ｍ）
# display as カズマ
# （あー……朝か……。\n　朝日がマジ眩しい……。\n　カーテン閉めるの忘れてた……）
205 = "（あー……朝か……。\\n　朝日がマジ眩しい……。\\n　カーテン閉めるの忘れてた……）"

# カズマ（Ｍ）
# display as カズマ
# （って、あれ？\n　ここって俺の部屋だよな？\n　いつ戻って来たんだ？）
222 = "（って、あれ？\\n　ここって俺の部屋だよな？\\n　いつ戻って来たんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （夕べは、みんなですき焼きを食って……\n　久々の豪華な夕食にすごく盛り上がって……）
236 = "（夕べは、みんなですき焼きを食って……\\n　久々の豪華な夕食にすごく盛り上がって……）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、思い出した。\n　深夜まで飲み食いが続いて、そのまま寝ちまった\n　んだっけ）
203 = "（ああ、思い出した。\\n　深夜まで飲み食いが続いて、そのまま寝ちまった\\n　んだっけ）"

# カズマ（Ｍ）
# display as カズマ
# （あーあ……。\n　喉渇いたな、とりあえず水でも飲むか）
206 = "（あーあ……。\\n　喉渇いたな、とりあえず水でも飲むか）"

# カズマ（Ｍ）
# display as カズマ
# （……あれ、なんだ？\n　俺、なんか握ってる？）
200 = "（……あれ、なんだ？\\n　俺、なんか握ってる？）"

# カズマ（Ｍ）
# display as カズマ
# （布？　ハンカチか？\n　誰かが貸してくれたのかな）
240 = "（布？　ハンカチか？\\n　誰かが貸してくれたのかな）"

# カズマ
# おお！？\nこ、これは……パンツ！\nパンツじゃないですかー！？
166 = "おお！？\\nこ、これは……パンツ！\\nパンツじゃないですかー！？"

# カズマ
# しかも明らかに女物！\n俺のじゃなく女物！\nあ、ちょっといい香りが――
167 = "しかも明らかに女物！\\n俺のじゃなく女物！\\nあ、ちょっといい香りが――"

# カズマ
# って、待て待て待て！\nなんでパンツ握りしめて寝てたんだよ！
171 = "って、待て待て待て！\\nなんでパンツ握りしめて寝てたんだよ！"

# カズマ（Ｍ）
# display as カズマ
# （お、俺は一体……\n　何をしてしまったんだ！？）
209 = "（お、俺は一体……\\n　何をしてしまったんだ！？）"

# カズマ（Ｍ）
# display as カズマ
# （そうだ！\n　きっと、夜の街を徘徊する\n　パンツ泥棒を捕まえたんだ！）
218 = "（そうだ！\\n　きっと、夜の街を徘徊する\\n　パンツ泥棒を捕まえたんだ！）"

# カズマ（Ｍ）
# display as カズマ
# （俺の冒険者としての正義の心が\n　悪の気配を感じ取り、無意識のうちに\n　行動したんだな！）
234 = "（俺の冒険者としての正義の心が\\n　悪の気配を感じ取り、無意識のうちに\\n　行動したんだな！）"

# カズマ（Ｍ）
# display as カズマ
# （そして、その報酬として\n　取り返したパンツを懐に収めて……）
219 = "（そして、その報酬として\\n　取り返したパンツを懐に収めて……）"

# カズマ（Ｍ）
# display as カズマ
# （って、ダメじゃねーか！\n　それってミイラ取りがミイラじゃねーか！）
225 = "（って、ダメじゃねーか！\\n　それってミイラ取りがミイラじゃねーか！）"

# カズマ（Ｍ）
# display as カズマ
# （安眠のために必要なのか！？\n　俺は、女性のパンツを抱かなければ眠れない\n　変態にジョブチェンジしてたのか！？）
239 = "（安眠のために必要なのか！？\\n　俺は、女性のパンツを抱かなければ眠れない\\n　変態にジョブチェンジしてたのか！？）"

# カズマ（Ｍ）
# display as カズマ
# （そんな俺を気づかい、\n　誰かが自分のパンツを差し出してくれたのか！？）
221 = "（そんな俺を気づかい、\\n　誰かが自分のパンツを差し出してくれたのか！？）"

# カズマ（Ｍ）
# display as カズマ
# （って、んな訳あるかー！\n　落ち着け、落ち着くんだ俺！）
224 = "（って、んな訳あるかー！\\n　落ち着け、落ち着くんだ俺！）"

# カズマ（Ｍ）
# display as カズマ
# （女装に目覚めたのか！？\n　そして、街を練り歩き……）
237 = "（女装に目覚めたのか！？\\n　そして、街を練り歩き……）"

# カズマ（Ｍ）
# display as カズマ
# （好奇の視線に晒されることに\n　快感を覚えてしまったというのか！？）
238 = "（好奇の視線に晒されることに\\n　快感を覚えてしまったというのか！？）"

# カズマ（Ｍ）
# display as カズマ
# （……いや、ない。\n　自分で考えといてなんだが、\n　それだけはないわー）
201 = "（……いや、ない。\\n　自分で考えといてなんだが、\\n　それだけはないわー）"

# カズマ（Ｍ）
# display as カズマ
# （ま、まあ、普通に考えてスティールだな。\n　俺がスティールのスキルで、\n　アクア達の誰かから盗んだろう）
230 = "（ま、まあ、普通に考えてスティールだな。\\n　俺がスティールのスキルで、\\n　アクア達の誰かから盗んだろう）"

# カズマ（Ｍ）
# display as カズマ
# （でも俺、スティールを使った\n　覚えなんてないぞ？）
227 = "（でも俺、スティールを使った\\n　覚えなんてないぞ？）"

# カズマ（Ｍ）
# display as カズマ
# （……いや！　そうだ、思い出した！\n　アクアに芸をやれって無茶振りされたな）
202 = "（……いや！　そうだ、思い出した！\\n　アクアに芸をやれって無茶振りされたな）"

# カズマ（Ｍ）
# display as カズマ
# （この宴会は自分がホストなんだから楽しませろ、\n　とか抜かしやがって……）
212 = "（この宴会は自分がホストなんだから楽しませろ、\\n　とか抜かしやがって……）"

# カズマ（Ｍ）
# display as カズマ
# （で、俺、なんの芸をやったんだっけ？\n　全然覚えてないぞ？）
226 = "（で、俺、なんの芸をやったんだっけ？\\n　全然覚えてないぞ？）"

# カズマ（Ｍ）
# display as カズマ
# （もしかして、勢いでスティールを\n　炸裂させちまったのか？）
232 = "（もしかして、勢いでスティールを\\n　炸裂させちまったのか？）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、だったらパンツが\n　今も手元にあるのはおかしい。\n　あいつらが盗られて黙ってるわけがない）
215 = "（しかし、だったらパンツが\\n　今も手元にあるのはおかしい。\\n　あいつらが盗られて黙ってるわけがない）"

# カズマ（Ｍ）
# display as カズマ
# （酔ったノリでやったのだとしても、\n　シュワシュワを飲めないめぐみんが\n　必ず奪い返したはずだ）
241 = "（酔ったノリでやったのだとしても、\\n　シュワシュワを飲めないめぐみんが\\n　必ず奪い返したはずだ）"

# カズマ
# ふっふふふふ。\nなるほど、そういうことか。
174 = "ふっふふふふ。\\nなるほど、そういうことか。"

# カズマ（Ｍ）
# display as カズマ
# （ここで思わず美少女ゲーム的な展開を\n　妄想してしまうのは、健全な思春期男子として\n　当然のことだと言えよう）
211 = "（ここで思わず美少女ゲーム的な展開を\\n　妄想してしまうのは、健全な思春期男子として\\n　当然のことだと言えよう）"

# カズマ（Ｍ）
# display as カズマ
# （そうだろ？　当然だろ！？\n　いくらここがろくでもない世界でも……）
217 = "（そうだろ？　当然だろ！？\\n　いくらここがろくでもない世界でも……）"

# カズマ（Ｍ）
# display as カズマ
# （冒険者として頑張る俺に淡い想いを抱く俺好みで\n　可愛いグラマーな町娘が告白してきてそのまま急\n　展開しちゃったとしても俺は一向に構わんっ！）
235 = "（冒険者として頑張る俺に淡い想いを抱く俺好みで\\n　可愛いグラマーな町娘が告白してきてそのまま急\\n　展開しちゃったとしても俺は一向に構わんっ！）"

# カズマ
# ……！　……！
163 = "……！　……！"

# カズマ
# はい、誰もいませんでしたー！
173 = "はい、誰もいませんでしたー！"

# カズマ（Ｍ）
# display as カズマ
# （うん、そうだよね。\n　そんな都合のいいことなんて起きないよね）
207 = "（うん、そうだよね。\\n　そんな都合のいいことなんて起きないよね）"

# カズマ（Ｍ）
# display as カズマ
# （はあ……。\n　じゃあ、この下着は一体誰の物なんだよ）
229 = "（はあ……。\\n　じゃあ、この下着は一体誰の物なんだよ）"

# カズマ（Ｍ）
# display as カズマ
# （って、あれ？　指輪？）
223 = "（って、あれ？　指輪？）"

# カズマ（Ｍ）
# display as カズマ
# （これって、昨日拾った指輪だよな？\n　俺、いつの間にはめたんだ？）
214 = "（これって、昨日拾った指輪だよな？\\n　俺、いつの間にはめたんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （ええと……\n　そうだ、これは確かアクアの無茶ぶりで……）
208 = "（ええと……\\n　そうだ、これは確かアクアの無茶ぶりで……）"

# アクア
# ちょっとカズマ、その指輪はめてみなさいよ！
169 = "ちょっとカズマ、その指輪はめてみなさいよ！"

# アクア
# 呪い？　なーに言ってんの、\nそれはそれでめちゃくちゃ美味しいじゃない！\nみんなにバカ受けじゃない！
183 = "呪い？　なーに言ってんの、\\nそれはそれでめちゃくちゃ美味しいじゃない！\\nみんなにバカ受けじゃない！"

# アクア
# それに私を誰だと思ってるわけ？\n例え呪われても、私がちょちょいと解いてあげるわ。
168 = "それに私を誰だと思ってるわけ？\\n例え呪われても、私がちょちょいと解いてあげるわ。"

# カズマ（Ｍ）
# display as カズマ
# （あのやろう、とんでもない無茶ぶり\n　しやがって）
204 = "（あのやろう、とんでもない無茶ぶり\\n　しやがって）"

# カズマ（Ｍ）
# display as カズマ
# （ノリと勢いで、はめた俺もどうかと思うが……）
233 = "（ノリと勢いで、はめた俺もどうかと思うが……）"

# カズマ（Ｍ）
# display as カズマ
# （それにしてもこの指輪、俺の指にぴったりだな。\n　昨日見た時はそう思わなかったけど）
220 = "（それにしてもこの指輪、俺の指にぴったりだな。\\n　昨日見た時はそう思わなかったけど）"

# カズマ（Ｍ）
# display as カズマ
# （けど、着飾る趣味はないしな。\n　早いところバニルに鑑定してもらって\n　売り払うなりなんなり――）
210 = "（けど、着飾る趣味はないしな。\\n　早いところバニルに鑑定してもらって\\n　売り払うなりなんなり――）"

# カズマ
# って……あれ？　外れない。
170 = "って……あれ？　外れない。"

# カズマ
# ふんっ！　ふんっ！
176 = "ふんっ！　ふんっ！"

# カズマ（Ｍ）
# display as カズマ
# （ねえ、なんで？\n　なんでそんな、ぴったりしてるの？）
228 = "（ねえ、なんで？\\n　なんでそんな、ぴったりしてるの？）"

# カズマ
# ふぬううううううう！
175 = "ふぬううううううう！"

# カズマ
# いてててててっ！
164 = "いてててててっ！"

# カズマ
# なんだよこれ、ビクともしねーぞ？\nまるで俺の皮膚と一体化してるみたいな！
172 = "なんだよこれ、ビクともしねーぞ？\\nまるで俺の皮膚と一体化してるみたいな！"

# カズマ（Ｍ）
# display as カズマ
# （まさか、まさかマジで呪いの指輪なのか？\n　一度はめたら絶対に外れない、なんて\n　ベタな呪いなのか！？）
231 = "（まさか、まさかマジで呪いの指輪なのか？\\n　一度はめたら絶対に外れない、なんて\\n　ベタな呪いなのか！？）"

# カズマ（Ｍ）
# display as カズマ
# （そ、そうだ、アクア！　アクアがいる！\n　あいつは浄化魔法が使えるんだ、\n　呪いなんて一発で解除できるだろ！）
216 = "（そ、そうだ、アクア！　アクアがいる！\\n　あいつは浄化魔法が使えるんだ、\\n　呪いなんて一発で解除できるだろ！）"

# カズマ
# おおーい！　アクアー！\nアクアさーん！　起きてらっしゃいますかー！
165 = "おおーい！　アクアー！\\nアクアさーん！　起きてらっしゃいますかー！"

# カズマ（Ｍ）
# display as カズマ
# （この時、俺は重大なことを見落としていた。\n　それがまさかあらぬ嫌疑を巻き起こすとは……）
213 = "（この時、俺は重大なことを見落としていた。\\n　それがまさかあらぬ嫌疑を巻き起こすとは……）"

[selections]
181 = "パンツ泥棒を捕まえたんだ！"
185 = "安眠のために必要なのか！？"
184 = "女装に目覚めたのか！？"
