# pr_08.txt.scn

[info]
221 = "pr_08"

[characters]
327 = "バニル"
322 = "カズマ"
321 = "ウィズ"
320 = "アクア"
318 = "めぐみん"
325 = "カズマ（Ｍ）"
326 = "ダクネス"

[character_subs]
# 322 = "カズマ"

[script]
# lines: 79

# バニル
# フハハハハハハ！\nなかなか男前になったではないか、\n女神を自称する娘に打ち据えられた小僧よ！
329 = "フハハハハハハ！\\nなかなか男前になったではないか、\\n女神を自称する娘に打ち据えられた小僧よ！"

# カズマ
# うるせー。\nその高笑いをやめろ、頬に響くんだよ……。
275 = "うるせー。\\nその高笑いをやめろ、頬に響くんだよ……。"

# ウィズ
# カズマさん、本当に大丈夫なんですか？\nすごく腫れていますし、\nアクア様に治療して頂いたほうが良いのでは？
324 = "カズマさん、本当に大丈夫なんですか？\\nすごく腫れていますし、\\nアクア様に治療して頂いたほうが良いのでは？"

# アクア
# ほっときなさい。\nカズマの自業自得なんだから。
308 = "ほっときなさい。\\nカズマの自業自得なんだから。"

# めぐみん
# むしろ爆裂魔法を撃たなかった分、\n優しいと思って欲しいです。
316 = "むしろ爆裂魔法を撃たなかった分、\\n優しいと思って欲しいです。"

# ウィズ
# は、はあ……。
304 = "は、はあ……。"

# バニル
# 我輩が鑑定していれば\nこのような悲劇、起きなかったものの――
343 = "我輩が鑑定していれば\\nこのような悲劇、起きなかったものの――"

# バニル
# いや、あまりに面白いゆえ、\n黙って見過ごしたかもしれぬな。
273 = "いや、あまりに面白いゆえ、\\n黙って見過ごしたかもしれぬな。"

# カズマ（Ｍ）
# display as カズマ
# （こいつ、すべてを見渡す力を持ってるから\n　俺がアクアのゴッドブローで殴られたことも、\n　その理由もお見通しか）
382 = "（こいつ、すべてを見渡す力を持ってるから\\n　俺がアクアのゴッドブローで殴られたことも、\\n　その理由もお見通しか）"

# カズマ（Ｍ）
# display as カズマ
# （でもまあ、それなら話は早いな）
384 = "（でもまあ、それなら話は早いな）"

# カズマ
# おいバニル。\nこの指輪は一体なんなんだ？
281 = "おいバニル。\\nこの指輪は一体なんなんだ？"

# アクア
# とりあえず、悪霊の仕業とか呪いじゃないわね。\n私の浄化魔法でも外れないんだもの。
299 = "とりあえず、悪霊の仕業とか呪いじゃないわね。\\n私の浄化魔法でも外れないんだもの。"

# バニル
# 人間の駆け出しプリーストが使うような魔法では、\nそのあたりに漂う低級霊すらも\n浄化できないのではないか？
333 = "人間の駆け出しプリーストが使うような魔法では、\\nそのあたりに漂う低級霊すらも\\n浄化できないのではないか？"

# アクア
# あらぁ？\nなんでしたら、ここで一発\n浄化魔法を撃って差し上げましょうか？
271 = "あらぁ？\\nなんでしたら、ここで一発\\n浄化魔法を撃って差し上げましょうか？"

# アクア
# 今なら特別サービスでタダでいいわよ？\nそっちのアンデットも込みで。
334 = "今なら特別サービスでタダでいいわよ？\\nそっちのアンデットも込みで。"

# ウィズ
# や、やめてくださーい！
319 = "や、やめてくださーい！"

# カズマ（Ｍ）
# display as カズマ
# （アクアとバニルはとにかく仲が悪い。\n　まあ、女神と悪魔なんだし仕方ないのかも\n　しれないが）
385 = "（アクアとバニルはとにかく仲が悪い。\\n　まあ、女神と悪魔なんだし仕方ないのかも\\n　しれないが）"

# カズマ（Ｍ）
# display as カズマ
# （で、ウィズとアクアも――\n　いや、こっちはアクアがウィズを\n　一方的に敵視している）
383 = "（で、ウィズとアクアも――\\n　いや、こっちはアクアがウィズを\\n　一方的に敵視している）"

# カズマ（Ｍ）
# display as カズマ
# （女神としては、アンデットの存在を\n　許すことができないらしく、\n　隙あらば浄化させようとするんだよな）
386 = "（女神としては、アンデットの存在を\\n　許すことができないらしく、\\n　隙あらば浄化させようとするんだよな）"

# カズマ
# おいアクア、ちょっと黙ってろ。\n話が進まない。
280 = "おいアクア、ちょっと黙ってろ。\\n話が進まない。"

# アクア
# なによっ！\n私の従者がこんな悪魔とアンデットを頼るなんて\n絶対に許さないから！
302 = "なによっ！\\n私の従者がこんな悪魔とアンデットを頼るなんて\\n絶対に許さないから！"

# カズマ
# 誰が従者だ。\n大体、お前が外せてたら\nここに来る必要もなかったんだぞ、この無能。
376 = "誰が従者だ。\\n大体、お前が外せてたら\\nここに来る必要もなかったんだぞ、この無能。"

# アクア
# む、無能！？\nあんたそろそろ罰の１つもあてるわよ！？
314 = "む、無能！？\\nあんたそろそろ罰の１つもあてるわよ！？"

# ダクネス
# まあまあ、アクア落ちつけ。
311 = "まあまあ、アクア落ちつけ。"

# カズマ
# はぁ……。\n話を戻すが、この指輪はなんなんだ？\nマジで呪いじゃないだろうな？
305 = "はぁ……。\\n話を戻すが、この指輪はなんなんだ？\\nマジで呪いじゃないだろうな？"

# バニル
# 呪いではない。\n単純な、とある魔法の効果を封じた物だ。
337 = "呪いではない。\\n単純な、とある魔法の効果を封じた物だ。"

# めぐみん
# 魔法を？\nつまり、マジックアイテムということですか。
380 = "魔法を？\\nつまり、マジックアイテムということですか。"

# バニル
# そういうことであるな、\n頭のおかしな紅魔族の娘よ。
285 = "そういうことであるな、\\n頭のおかしな紅魔族の娘よ。"

# めぐみん
# その通り名はやめろ。\nさもないと、我がいかに頭がおかしいのか\nその身を以て味わうことになるぞ。
290 = "その通り名はやめろ。\\nさもないと、我がいかに頭がおかしいのか\\nその身を以て味わうことになるぞ。"

# カズマ
# おいっ！\nこんな場所で爆裂魔法を撃とうとするな！
279 = "おいっ！\\nこんな場所で爆裂魔法を撃とうとするな！"

# カズマ
# で？　この指輪の魔法ってなんだ？\nはめたら外れなくなる地味な嫌がらせの魔法か？
298 = "で？　この指輪の魔法ってなんだ？\\nはめたら外れなくなる地味な嫌がらせの魔法か？"

# バニル
# ふむ、それを説明するためには、\nその指輪の出自から語らねばならぬ。
306 = "ふむ、それを説明するためには、\\nその指輪の出自から語らねばならぬ。"

# バニル
# その昔――\n下着泥棒の嫌疑に曝された紳士がいた。
288 = "その昔――\\n下着泥棒の嫌疑に曝された紳士がいた。"

# カズマ
# いきなりおかしいだろ！？\nなんでそんな変態紳士の話が出てくるんだ！
272 = "いきなりおかしいだろ！？\\nなんでそんな変態紳士の話が出てくるんだ！"

# アクア
# でも、一言で納得したわ。
297 = "でも、一言で納得したわ。"

# めぐみん
# ですね。
295 = "ですね。"

# ダクネス
# ああ、下着だしな。
270 = "ああ、下着だしな。"

# カズマ
# まだ話が始まったばかりなのに\n納得してんじゃねーよ！
313 = "まだ話が始まったばかりなのに\\n納得してんじゃねーよ！"

# ウィズ
# ま、まあまあ。\nとにかく最後まで聞きましょう？\nでないと対処法もわかりませんし。
309 = "ま、まあまあ。\\nとにかく最後まで聞きましょう？\\nでないと対処法もわかりませんし。"

# バニル
# 紳士は、冤罪を晴らすために\n奔走し続けたが――
374 = "紳士は、冤罪を晴らすために\\n奔走し続けたが――"

# バニル
# 身の潔白を証明する前に、\n不慮の事故でこの世を去った。
377 = "身の潔白を証明する前に、\\n不慮の事故でこの世を去った。"

# カズマ
# ってことは、その呪い？
292 = "ってことは、その呪い？"

# バニル
# 急くな小僧。\n話は続くぞ？
342 = "急くな小僧。\\n話は続くぞ？"

# バニル
# 紳士には弟がいた。\n弟は、兄の無念を晴らすために\nこの指輪――マジックアイテムを作り出したのだ。
373 = "紳士には弟がいた。\\n弟は、兄の無念を晴らすために\\nこの指輪――マジックアイテムを作り出したのだ。"

# カズマ
# 無念を晴らすため？
346 = "無念を晴らすため？"

# バニル
# このマジックアイテムは、\n男性の指に収まることで初めて\n魔法の効果が発動する。
283 = "このマジックアイテムは、\\n男性の指に収まることで初めて\\n魔法の効果が発動する。"

# バニル
# その効果は――\n満月の夜、無意識下で\n女性の下着を奪う、というものである。
287 = "その効果は――\\n満月の夜、無意識下で\\n女性の下着を奪う、というものである。"

# カズマ
# つまり、毎月一度は\n無差別に女性のパンツを盗むってことかよ！
293 = "つまり、毎月一度は\\n無差別に女性のパンツを盗むってことかよ！"

# バニル
# まさにその通りだ。\n酔った勢いで得体の知れぬ指輪を\n身につけてしまったうかつな小僧よ。
312 = "まさにその通りだ。\\n酔った勢いで得体の知れぬ指輪を\\n身につけてしまったうかつな小僧よ。"

# カズマ（Ｍ）
# display as カズマ
# （ぐ、ぐうの音も出ない！）
381 = "（ぐ、ぐうの音も出ない！）"

# アクア
# なにそれ。\n正直、ドン引きなんですけど。
301 = "なにそれ。\\n正直、ドン引きなんですけど。"

# ダクネス
# 私だけに、という事ならば受け入れるが\n無差別なのは問題があるな。
372 = "私だけに、という事ならば受け入れるが\\n無差別なのは問題があるな。"

# めぐみん
# でも、それはおかしいです。
296 = "でも、それはおかしいです。"

# バニル
# おかしいとはどういう理屈であるか、\n頭のおかしな紅魔族の娘よ。
282 = "おかしいとはどういう理屈であるか、\\n頭のおかしな紅魔族の娘よ。"

# めぐみん
# むかっ！
315 = "むかっ！"

# カズマ
# め、めぐみん！\nバニルのことは気にせずに、\nそのおかしいって点を説明よろしく！
317 = "め、めぐみん！\\nバニルのことは気にせずに、\\nそのおかしいって点を説明よろしく！"

# めぐみん
# ……冤罪をこうむったまま亡くなったのなら、\nこのようなマジックアイテムを\n作り出すのはおかしい、ということです。
268 = "……冤罪をこうむったまま亡くなったのなら、\\nこのようなマジックアイテムを\\n作り出すのはおかしい、ということです。"

# アクア
# ああ、そっか。\n汚名返上のためなら、逆の物を作るわね。
269 = "ああ、そっか。\\n汚名返上のためなら、逆の物を作るわね。"

# カズマ
# 逆って、絶対に盗まれない下着とか？
378 = "逆って、絶対に盗まれない下着とか？"

# アクア
# その発想も正直ドン引きだわ。
289 = "その発想も正直ドン引きだわ。"

# カズマ
# なんでだよ。\nそういうことだろ？
303 = "なんでだよ。\\nそういうことだろ？"

# ダクネス
# まあ、内容はともかく、\nそのような女性の身を守るアイテムなら――
310 = "まあ、内容はともかく、\\nそのような女性の身を守るアイテムなら――"

# ダクネス
# 無念を抱えたまま死んでいった紳士の名誉も\n少しは取り戻せるはずだな。
345 = "無念を抱えたまま死んでいった紳士の名誉も\\n少しは取り戻せるはずだな。"

# めぐみん
# それなのに、どうしてこんな\nマジックアイテムを作り出したのでしょう？
291 = "それなのに、どうしてこんな\\nマジックアイテムを作り出したのでしょう？"

# バニル
# フハハハハハハ！\nつまり、そういうことだ！
328 = "フハハハハハハ！\\nつまり、そういうことだ！"

# カズマ
# どういう事なのかさっぱりわかんねーよ。
300 = "どういう事なのかさっぱりわかんねーよ。"

# バニル
# ふむ、察しの悪い小僧とその同類達に\nわかるよう説明してやると――
307 = "ふむ、察しの悪い小僧とその同類達に\\nわかるよう説明してやると――"

# バニル
# つまり、紳士に掛けられた嫌疑は\n冤罪ではなかったのだ。
294 = "つまり、紳士に掛けられた嫌疑は\\n冤罪ではなかったのだ。"

# カズマ
# え？
278 = "え？"

# バニル
# 紳士は正真正銘、下着泥棒だったのだ。
375 = "紳士は正真正銘、下着泥棒だったのだ。"

# カズマ
# ええー……。
277 = "ええー……。"

# バニル
# 地位ある立場ゆえに懸命に身の潔白を訴えたが、\nその間も趣味である下着の収集に\n勤しんでいたようだ。
338 = "地位ある立場ゆえに懸命に身の潔白を訴えたが、\\nその間も趣味である下着の収集に\\n勤しんでいたようだ。"

# バニル
# そして彼の弟は、突然の死により\n下着を盗めなくなった兄の無念を\n少しでも晴らすため――
286 = "そして彼の弟は、突然の死により\\n下着を盗めなくなった兄の無念を\\n少しでも晴らすため――"

# バニル
# このマジックアイテムを作り出したのだ。
284 = "このマジックアイテムを作り出したのだ。"

# カズマ
# うわー……。\nなんてはた迷惑な兄弟だ……。
276 = "うわー……。\\nなんてはた迷惑な兄弟だ……。"

# アクア
# カズマが言えた立場なのかしら？
323 = "カズマが言えた立場なのかしら？"

# ダクネス
# 類は友を呼ぶという言葉を思い出すな。
379 = "類は友を呼ぶという言葉を思い出すな。"

# めぐみん
# 変態は変態を引きよせるんですね。
339 = "変態は変態を引きよせるんですね。"

# カズマ
# いやいや、俺にそんな趣味ないんですけど！？\nなんかお前ら、誤解してないか！？
274 = "いやいや、俺にそんな趣味ないんですけど！？\\nなんかお前ら、誤解してないか！？"

