# rew_e04.txt.scn

[info]
242 = "rew_e04"

[characters]
363 = "カズマ"
357 = "ゆんゆん"
362 = "アクア"
367 = "ダクネス"
355 = "めぐみん"
366 = "カズマ（Ｍ）"

[character_subs]
# 363 = "カズマ"

[script]
# lines: 84

# カズマ
# ご褒美はゆんゆんに貰おうかな。
322 = "ご褒美はゆんゆんに貰おうかな。"

# ゆんゆん
# え、どうして私なんですか？
312 = "え、どうして私なんですか？"

# カズマ
# それは一番俺の期待に\n応えてくれそうだからだ！
335 = "それは一番俺の期待に\\n応えてくれそうだからだ！"

# カズマ
# そこにいる３人は、恥じらいや慎ましさってもんを\nどこかに置き忘れてきてる！
333 = "そこにいる３人は、恥じらいや慎ましさってもんを\\nどこかに置き忘れてきてる！"

# カズマ
# ハッキリ言って見ていて面白くない！\nそこにいくとゆんゆんは見所がある。
368 = "ハッキリ言って見ていて面白くない！\\nそこにいくとゆんゆんは見所がある。"

# アクア
# ちょっと、黙って聞いてれば\n随分なこと言ってくれるじゃない！
337 = "ちょっと、黙って聞いてれば\\n随分なこと言ってくれるじゃない！"

# アクア
# この私に慎ましさがないですって？\nあんた見る目ないんじゃないの！？\n女神なのよ私は！
320 = "この私に慎ましさがないですって？\\nあんた見る目ないんじゃないの！？\\n女神なのよ私は！"

# カズマ
# 女神っていっても三者三様だろうが。
375 = "女神っていっても三者三様だろうが。"

# ダクネス
# カズマ、私はこう見えて慎み深い女だぞ！
364 = "カズマ、私はこう見えて慎み深い女だぞ！"

# カズマ
# うん、ダクネスは黙っていようか。
310 = "うん、ダクネスは黙っていようか。"

# めぐみん
# 別にカズマのために\n何かをしたいとは思いませんが、\n私としても不服です。
371 = "別にカズマのために\\n何かをしたいとは思いませんが、\\n私としても不服です。"

# めぐみん
# これではまるで私がゆんゆんに\n劣っているようではありませんか。
321 = "これではまるで私がゆんゆんに\\n劣っているようではありませんか。"

# ゆんゆん
# 私が、めぐみんより優れている！？
431 = "私が、めぐみんより優れている！？"

# めぐみん
# いいえ、それは違います。\nカズマは普通ではないので、感性が残念なだけです。
304 = "いいえ、それは違います。\\nカズマは普通ではないので、感性が残念なだけです。"

# カズマ
# 人聞きの悪いことを言うな！\nとにかく、ゆんゆんに決めたんだよ！
370 = "人聞きの悪いことを言うな！\\nとにかく、ゆんゆんに決めたんだよ！"

# ゆんゆん
# あの、それで私は何をすればいいんですか？
301 = "あの、それで私は何をすればいいんですか？"

# カズマ
# とりあえず脱いで。
342 = "とりあえず脱いで。"

# ゆんゆん
# え？　ぬ、脱ぐ！？
314 = "え？　ぬ、脱ぐ！？"

# めぐみん
# な、何を言っているのです！
346 = "な、何を言っているのです！"

# ダクネス
# 欲望に忠実なのを責めるつもりはないが、\nそれはさすがにやり過ぎだと思うぞ。
383 = "欲望に忠実なのを責めるつもりはないが、\\nそれはさすがにやり過ぎだと思うぞ。"

# アクア
# 女神の私もさすがにドン引きなんですけど。
376 = "女神の私もさすがにドン引きなんですけど。"

# カズマ
# どうした早く脱がないか。\n俺は穿いていないプレイをしようと言っているんだ。\n脱がないことには始まらないだろ？
343 = "どうした早く脱がないか。\\n俺は穿いていないプレイをしようと言っているんだ。\\n脱がないことには始まらないだろ？"

# めぐみん
# 穿いてないプレイとはなんなのです？
433 = "穿いてないプレイとはなんなのです？"

# ダクネス
# さあ、私にもよくわからないが、\nふふ、どことなく甘美な響きがするな。
323 = "さあ、私にもよくわからないが、\\nふふ、どことなく甘美な響きがするな。"

# カズマ
# 穿いてないプレイというのは、\nつまり穿いてないということだ！
432 = "穿いてないプレイというのは、\\nつまり穿いてないということだ！"

# アクア
# 訳わからないわよ。
437 = "訳わからないわよ。"

# カズマ
# おやぁ、ゆんゆんはどうして\n顔を赤くしてるのかな？
315 = "おやぁ、ゆんゆんはどうして\\n顔を赤くしてるのかな？"

# ゆんゆん
# だ、だって、カズマさんが言う穿いてないって。
336 = "だ、だって、カズマさんが言う穿いてないって。"

# カズマ
# まあ、言葉にしてしまうのはもったいない。\nそういう恥ずかしい気持ちは、心の中にしまって\nおこうか。
354 = "まあ、言葉にしてしまうのはもったいない。\\nそういう恥ずかしい気持ちは、心の中にしまって\\nおこうか。"

# ダクネス
# そうやって乙女を羞恥の表情で染めるのだな。\nカズマの本領発揮という所か。
332 = "そうやって乙女を羞恥の表情で染めるのだな。\\nカズマの本領発揮という所か。"

# めぐみん
# ゆんゆん、そんな不当な要求を聞くことは\nありませんよ。
358 = "ゆんゆん、そんな不当な要求を聞くことは\\nありませんよ。"

# ダクネス
# そうだ。\nいくら褒美とはいえ、こんな無理強いが通って\n許されるわけがない。
329 = "そうだ。\\nいくら褒美とはいえ、こんな無理強いが通って\\n許されるわけがない。"

# ダクネス
# しかし、カズマへの褒美に拒否権が無いというのも\nまたルールの１つ。
324 = "しかし、カズマへの褒美に拒否権が無いというのも\\nまたルールの１つ。"

# ダクネス
# どうしてもというならこの私が代わりに――
344 = "どうしてもというならこの私が代わりに――"

# カズマ
# お前は間に合ってる。
316 = "お前は間に合ってる。"

# ダクネス
# はぅん！
351 = "はぅん！"

# ゆんゆん
# あ、あの、カズマさん。\nさすがに脱げというのは。
299 = "あ、あの、カズマさん。\\nさすがに脱げというのは。"

# めぐみん
# そうですよ。\nどう考えても、人の道から外れてます。
330 = "そうですよ。\\nどう考えても、人の道から外れてます。"

# めぐみん
# 変態、鬼畜に続いて、\n外道の称号まで得たいのですか。
374 = "変態、鬼畜に続いて、\\n外道の称号まで得たいのですか。"

# カズマ
# 待て待て、さっきから聞いてれば、\nどういうつもりだ！
380 = "待て待て、さっきから聞いてれば、\\nどういうつもりだ！"

# ダクネス
# なるほど、そういう説明から始めさせるのか。
347 = "なるほど、そういう説明から始めさせるのか。"

# めぐみん
# 心底腐ってますね。\nゆんゆんには同情しますよ。
381 = "心底腐ってますね。\\nゆんゆんには同情しますよ。"

# カズマ
# お前らなんか勘違いしてるだろ！
317 = "お前らなんか勘違いしてるだろ！"

# ゆんゆん
# え、勘違いとはどういうことですか？
313 = "え、勘違いとはどういうことですか？"

# カズマ
# 脱げとは言ったが、\n何を脱げとまでは言ってないだろ？\nなのにドン引きとか、こっちが引くわ！
435 = "脱げとは言ったが、\\n何を脱げとまでは言ってないだろ？\\nなのにドン引きとか、こっちが引くわ！"

# カズマ
# お前ら全員一体何を想像したんだ？\n物によっては今まで言われたセリフを\nそのまま全部返すからな。
318 = "お前ら全員一体何を想像したんだ？\\n物によっては今まで言われたセリフを\\nそのまま全部返すからな。"

# ゆんゆん
# な、何って、ええと、めぐみん？
345 = "な、何って、ええと、めぐみん？"

# めぐみん
# こっちに話を振らないでください！
319 = "こっちに話を振らないでください！"

# カズマ
# まあ、脱ぐ物はゆんゆんに任せる。\n脱げと言われて連想できる物を脱いでくれ。
353 = "まあ、脱ぐ物はゆんゆんに任せる。\\n脱げと言われて連想できる物を脱いでくれ。"

# ゆんゆん
# 脱げと言われて連想できる物……、\n連想できる物……。
436 = "脱げと言われて連想できる物……、\\n連想できる物……。"

# ゆんゆん
# で、では靴下を脱ぎます。
338 = "で、では靴下を脱ぎます。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、そんなもんだろうな）
442 = "（まあ、そんなもんだろうな）"

# カズマ（Ｍ）
# display as カズマ
# （だが、女の子が靴下を脱ぐ姿も\n　これはこれでなかなか……）
441 = "（だが、女の子が靴下を脱ぐ姿も\\n　これはこれでなかなか……）"

# ゆんゆん
# んしょ、脱ぎ終わりました。\nこれでいいですか？
360 = "んしょ、脱ぎ終わりました。\\nこれでいいですか？"

# カズマ（Ｍ）
# display as カズマ
# （うんうん、恥じらう姿が実にいい！\n　他の３人じゃこうはいかない、\n　ゆんゆんを選んで正解だ）
440 = "（うんうん、恥じらう姿が実にいい！\\n　他の３人じゃこうはいかない、\\n　ゆんゆんを選んで正解だ）"

# カズマ
# ゆんゆんって綺麗な足してるな。
359 = "ゆんゆんって綺麗な足してるな。"

# ゆんゆん
# そ、そうですか？
325 = "そ、そうですか？"

# カズマ
# ああ、白くてスラッとしてて実にいい！
300 = "ああ、白くてスラッとしてて実にいい！"

# ゆんゆん
# ありがとうございます。\nそんな風に言われたのは初めてです。
303 = "ありがとうございます。\\nそんな風に言われたのは初めてです。"

# カズマ
# ん～、もっとよく見せてもらってもいいか？
361 = "ん～、もっとよく見せてもらってもいいか？"

# ゆんゆん
# え、ちょっと、あの。
311 = "え、ちょっと、あの。"

# カズマ
# 頼む！
439 = "頼む！"

# ゆんゆん
# うぅ、嫌だけど、断ったりしたら\nカズマさんに嫌われちゃうかも。
307 = "うぅ、嫌だけど、断ったりしたら\\nカズマさんに嫌われちゃうかも。"

# ゆんゆん
# そうなったら私、もう二度とこのお屋敷に\n入れて貰えなくなって、せっかくできた\nお友達なのに。
331 = "そうなったら私、もう二度とこのお屋敷に\\n入れて貰えなくなって、せっかくできた\\nお友達なのに。"

# カズマ（Ｍ）
# display as カズマ
# （相変わらずめんどうな性格してるな……）
443 = "（相変わらずめんどうな性格してるな……）"

# ゆんゆん
# うぅ、わかりました、見てください……。
306 = "うぅ、わかりました、見てください……。"

# カズマ
# なるほどなるほど、\nこれはなかなか、素晴らしいおみ足だ。
348 = "なるほどなるほど、\\nこれはなかなか、素晴らしいおみ足だ。"

# ゆんゆん
# あのあの、はぅぅ、そんなにマジマジと\n見られると……。
302 = "あのあの、はぅぅ、そんなにマジマジと\\n見られると……。"

# カズマ
# いや、せっかくの機会なんだ。\n目にしっかり焼き付けておかないとな。
305 = "いや、せっかくの機会なんだ。\\n目にしっかり焼き付けておかないとな。"

# ゆんゆん
# うぅ、頑張ってゆんゆん！\nこれもお友達として関係を続けるための\n試練なんだから！
308 = "うぅ、頑張ってゆんゆん！\\nこれもお友達として関係を続けるための\\n試練なんだから！"

# カズマ
# 足もさることながら、\n恥ずかしがってる顔も可愛いぞ。
438 = "足もさることながら、\\n恥ずかしがってる顔も可愛いぞ。"

# ゆんゆん
# そ、そんな、可愛いだなんて。
326 = "そ、そんな、可愛いだなんて。"

# カズマ
# そうそれ！　それが見たかったんだ！\nああ、もうずっと側に置いておきたい！
328 = "そうそれ！　それが見たかったんだ！\\nああ、もうずっと側に置いておきたい！"

# ゆんゆん
# はぅぅ、それは困ります～。
350 = "はぅぅ、それは困ります～。"

# カズマ
# ところでゆんゆんは、最初に脱げと言われて\n何を想像したんだ？
341 = "ところでゆんゆんは、最初に脱げと言われて\\n何を想像したんだ？"

# ゆんゆん
# ふえ！？\nそ、それは、あの。
352 = "ふえ！？\\nそ、それは、あの。"

# カズマ
# なんなのなんなの？\nねえねえ？
349 = "なんなのなんなの？\\nねえねえ？"

# ゆんゆん
# ですから、それはぁ～、\nうぅぅ、助けて、めぐみん！
340 = "ですから、それはぁ～、\\nうぅぅ、助けて、めぐみん！"

# めぐみん
# それくらい自分でどうにかしてください。
334 = "それくらい自分でどうにかしてください。"

# ゆんゆん
# そ、そんな～！
327 = "そ、そんな～！"

# カズマ
# で、どうなのよ？\nほれ、言ってみ言ってみ。
339 = "で、どうなのよ？\\nほれ、言ってみ言ってみ。"

# ゆんゆん
# うぅぅぅ～！！
309 = "うぅぅぅ～！！"

# ダクネス
# 容赦のない言葉責め、さすがだカズマ！
377 = "容赦のない言葉責め、さすがだカズマ！"

# めぐみん
# カズマとの付き合い方は、\n少し考え直した方がよいかもしれませんね。
365 = "カズマとの付き合い方は、\\n少し考え直した方がよいかもしれませんね。"

[selections]
434 = "綺麗な足だと褒めよう"
356 = "もっと良く見せてもいいか？"
382 = "恥ずかしがってる顔も可愛いぞ"
