# rew_f10.txt.scn

[info]
169 = "rew_f10"

[characters]
249 = "カズマ"
246 = "ウィズ"
252 = "カズマ（Ｍ）"

[character_subs]
# 249 = "カズマ"

[script]
# lines: 63

# カズマ
# ぐううおお、お、おお、重い！！
221 = "ぐううおお、お、おお、重い！！"

# ウィズ
# ごめんなさい。\nどうしても私一人だと買う物の量的に大変なので。
222 = "ごめんなさい。\\nどうしても私一人だと買う物の量的に大変なので。"

# カズマ
# 確かにこの量はな……ま、荷物持ちぐらいなら、\nお仕置きとしては楽な方か。
279 = "確かにこの量はな……ま、荷物持ちぐらいなら、\\nお仕置きとしては楽な方か。"

# ウィズ
# でも、本当にカズマさんに手伝ってもらって助かり\nました。
232 = "でも、本当にカズマさんに手伝ってもらって助かり\\nました。"

# カズマ（Ｍ）
# display as カズマ
# （というか、何をどう買えばこんな量になるんだ。\n　これ、本当に全部必要なのか？）
287 = "（というか、何をどう買えばこんな量になるんだ。\\n　これ、本当に全部必要なのか？）"

# ウィズ
# あっ！
209 = "あっ！"

# カズマ（Ｍ）
# display as カズマ
# （どう見てもあの店に必要なさそうな物も\n　いっぱいある気がするんだが……）
289 = "（どう見てもあの店に必要なさそうな物も\\n　いっぱいある気がするんだが……）"

# カズマ
# なあ、ウィズってあれ？　どこ行った？
236 = "なあ、ウィズってあれ？　どこ行った？"

# カズマ（Ｍ）
# display as カズマ
# （まさか、迷子って事はないよな）
292 = "（まさか、迷子って事はないよな）"

# ウィズ
# カズマさーんっ。
251 = "カズマさーんっ。"

# カズマ
# どこ行ってたんだよ？
235 = "どこ行ってたんだよ？"

# ウィズ
# ちょっと気になる物が目に入ったので\n寄ってきちゃいました。
229 = "ちょっと気になる物が目に入ったので\\n寄ってきちゃいました。"

# カズマ
# え、また増えたのか……って、ネックレス？\nふぅん、けっこういい作りっぽいじゃんか。
213 = "え、また増えたのか……って、ネックレス？\\nふぅん、けっこういい作りっぽいじゃんか。"

# ウィズ
# はいっ。しかもこれ、すっごいレアアイテムらしいん\nです。それを、たった３万エリスで譲ってくれて！
242 = "はいっ。しかもこれ、すっごいレアアイテムらしいん\\nです。それを、たった３万エリスで譲ってくれて！"

# カズマ
# なんか一気に胡散臭い話になってきたな。
237 = "なんか一気に胡散臭い話になってきたな。"

# カズマ（Ｍ）
# display as カズマ
# （とはいえ、俺もさすがにアイテムのレア度なんて\n　わからないし、仮にもリッチーのウィズがそう\n　感じたのなら、なんかあるだろ）
288 = "（とはいえ、俺もさすがにアイテムのレア度なんて\\n　わからないし、仮にもリッチーのウィズがそう\\n　感じたのなら、なんかあるだろ）"

# ウィズ
# もしかしたら他にも掘り出し物があるかもしれません\nから、回ってみましょう？
245 = "もしかしたら他にも掘り出し物があるかもしれません\\nから、回ってみましょう？"

# カズマ
# お、おいっ！　これ以上余計な物、\nまだ増やす気かよ！
220 = "お、おいっ！　これ以上余計な物、\\nまだ増やす気かよ！"

# ウィズ
# カズマさん、カズマさん！\nここ、エリス様のお人形が売ってますよ！
250 = "カズマさん、カズマさん！\\nここ、エリス様のお人形が売ってますよ！"

# カズマ
# えりすさまのにんぎょう……。
219 = "えりすさまのにんぎょう……。"

# ウィズ
# とても可愛らしいです。
233 = "とても可愛らしいです。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、確かにエリス様に似てなくはないけど、\n　その『幸福を招く人形』とか、胡散臭いポップは\n　なんなんだ）
291 = "（まあ、確かにエリス様に似てなくはないけど、\\n　その『幸福を招く人形』とか、胡散臭いポップは\\n　なんなんだ）"

# カズマ（Ｍ）
# display as カズマ
# （しかもバカ高いぞ！？\n　どう見てもボッタクリ価格というか、\n　出来と値段が反比例してるだろ！）
283 = "（しかもバカ高いぞ！？\\n　どう見てもボッタクリ価格というか、\\n　出来と値段が反比例してるだろ！）"

# ウィズ
# ああ、どうしましょう。\nお店と、あとカズマさん、\n酒場やお世話になってる皆さんの分と……。
207 = "ああ、どうしましょう。\\nお店と、あとカズマさん、\\n酒場やお世話になってる皆さんの分と……。"

# カズマ
# え、もしかしてそれ、買おうと思ってる数か？
214 = "え、もしかしてそれ、買おうと思ってる数か？"

# ウィズ
# はいっ。こういうのは誰かのが欠けちゃうと\n気まずいじゃないですか。
241 = "はいっ。こういうのは誰かのが欠けちゃうと\\n気まずいじゃないですか。"

# カズマ
# せめて一つにしておきなさい！！
224 = "せめて一つにしておきなさい！！"

# ウィズ
# ええー、でもそれだと……。
218 = "ええー、でもそれだと……。"

# カズマ
# 悩むくらいなら買わない！\nどうしても欲しいのなら自分用に一つ！
261 = "悩むくらいなら買わない！\\nどうしても欲しいのなら自分用に一つ！"

# カズマ
# 他の人のことは、それから考えろ！
255 = "他の人のことは、それから考えろ！"

# ウィズ
# は、はい、確かにそうですね。
238 = "は、はい、確かにそうですね。"

# カズマ
# そんな物買うな！
227 = "そんな物買うな！"

# ウィズ
# え、何でですかっ、エリス様のお人形ですよ！\n幸運の人形ですよ！　これを飾っておけば、\nお店も末代まで繁盛間違い無しです！
215 = "え、何でですかっ、エリス様のお人形ですよ！\\n幸運の人形ですよ！　これを飾っておけば、\\nお店も末代まで繁盛間違い無しです！"

# カズマ
# いや末代も何も、死なないだろウィズ。
211 = "いや末代も何も、死なないだろウィズ。"

# カズマ
# だいたいそんなラッキーアイテムにすがるようじゃ、\n店の繁盛もおぼつかないだろ。
228 = "だいたいそんなラッキーアイテムにすがるようじゃ、\\n店の繁盛もおぼつかないだろ。"

# ウィズ
# ええっ、カズマさんがまともなこと言ってます。
217 = "ええっ、カズマさんがまともなこと言ってます。"

# カズマ
# 失礼だなおいっ！
259 = "失礼だなおいっ！"

# カズマ
# オーケー、ウィズ。まずは買う前に、値段に見合う\nクオリティか確かめようじゃないか。
248 = "オーケー、ウィズ。まずは買う前に、値段に見合う\\nクオリティか確かめようじゃないか。"

# ウィズ
# クオリティですか？\nこんなに可愛いじゃないですか。
253 = "クオリティですか？\\nこんなに可愛いじゃないですか。"

# カズマ
# エリス様は確かに可愛いけど、\nこの人形を見てそう思えるのはどうかと思うぞ？
247 = "エリス様は確かに可愛いけど、\\nこの人形を見てそう思えるのはどうかと思うぞ？"

# カズマ
# それによく見てみろ。縫製や形がみんなバラバラだ。\n手作りにしても出来の差が激しすぎる。
226 = "それによく見てみろ。縫製や形がみんなバラバラだ。\\n手作りにしても出来の差が激しすぎる。"

# ウィズ
# それがハンドメイドの味じゃないですか～。
225 = "それがハンドメイドの味じゃないですか～。"

# カズマ
# 味以前の問題だぞ！\nさらによく観察するんだ。\nこの人形、手に取って買う人いるか？
258 = "味以前の問題だぞ！\\nさらによく観察するんだ。\\nこの人形、手に取って買う人いるか？"

# ウィズ
# ……いないですね。
205 = "……いないですね。"

# カズマ
# つまりはそういうことだ。出来か値段かはわからない\nけど、みんな買うに値しないと判断してるわけだ。
230 = "つまりはそういうことだ。出来か値段かはわからない\\nけど、みんな買うに値しないと判断してるわけだ。"

# ウィズ
# ううう……そう言われるとごもっともです……。
212 = "ううう……そう言われるとごもっともです……。"

# ウィズ
# でも、せめて一つだけ……。
231 = "でも、せめて一つだけ……。"

# カズマ
# ……まあ、どうしても欲しいのなら、一つだけなら\nいいんじゃないか。
206 = "……まあ、どうしても欲しいのなら、一つだけなら\\nいいんじゃないか。"

# ウィズ
# ありがとうございます！\nじゃあ買ってきますね！！
210 = "ありがとうございます！\\nじゃあ買ってきますね！！"

# カズマ
# はあ……。
239 = "はあ……。"

# カズマ（Ｍ）
# display as カズマ
# （……ウィズの店が儲からない理由、\n　よーくわかった気がする）
282 = "（……ウィズの店が儲からない理由、\\n　よーくわかった気がする）"

# ウィズ
# 買ってきました～。\nでも、本当は皆さんにプレゼントしたかったです。\nせっかくの、幸せを呼ぶ人形でしたから……。
280 = "買ってきました～。\\nでも、本当は皆さんにプレゼントしたかったです。\\nせっかくの、幸せを呼ぶ人形でしたから……。"

# カズマ（Ｍ）
# display as カズマ
# （……そうか、出来とかそういうのじゃ無くて、\n　ただそれだけのために買いたかったんだな）
281 = "（……そうか、出来とかそういうのじゃ無くて、\\n　ただそれだけのために買いたかったんだな）"

# カズマ（Ｍ）
# display as カズマ
# （それはウィズのいいところなんだろうが……）
285 = "（それはウィズのいいところなんだろうが……）"

# ウィズ
# はい、カズマさん。\nそういうわけでプレゼントです。
240 = "はい、カズマさん。\\nそういうわけでプレゼントです。"

# カズマ
# え、俺に？
216 = "え、俺に？"

# ウィズ
# はいっ。買い出しに付き合って頂いたお礼です。
243 = "はいっ。買い出しに付き合って頂いたお礼です。"

# カズマ
# はは……そっか、ありがとう。
244 = "はは……そっか、ありがとう。"

# ウィズ
# どう致しまして～。じゃ、帰りましょうか。
234 = "どう致しまして～。じゃ、帰りましょうか。"

# カズマ
# ああ。
208 = "ああ。"

# カズマ（Ｍ）
# display as カズマ
# （ま、ウィズの気持ちだし、ありがたくもらって\n　おこうかな）
290 = "（ま、ウィズの気持ちだし、ありがたくもらって\\n　おこうかな）"

# カズマ（Ｍ）
# display as カズマ
# （でも、この人形……あの駄女神に見つかったら、\n　面倒くさいことになりそうだ……）
286 = "（でも、この人形……あの駄女神に見つかったら、\\n　面倒くさいことになりそうだ……）"

# カズマ（Ｍ）
# display as カズマ
# （そっちの方がお仕置きかもしれないなぁ……）
284 = "（そっちの方がお仕置きかもしれないなぁ……）"

[selections]
223 = "せめてひとつにしておけ！"
# 227 = "そんな物買うな！"
256 = "値段に見合うクオリティか確かめよう"
