# rew_d08.txt.scn

[info]
256 = "rew_d08"

[characters]
361 = "カズマ"
364 = "クリス"
363 = "カズマ（Ｍ）"

[character_subs]
# 361 = "カズマ"

[script]
# lines: 145

# カズマ
# ふぁぁぁ、お仕置きは明日にしようぜ。\nもうこんな時間だしさ。
346 = "ふぁぁぁ、お仕置きは明日にしようぜ。\\nもうこんな時間だしさ。"

# クリス
# 何言ってるの。\n夜はまだこれからだよ。
374 = "何言ってるの。\\n夜はまだこれからだよ。"

# カズマ
# なんだ、夜通しで遊びに付き合えって言うのか。
341 = "なんだ、夜通しで遊びに付き合えって言うのか。"

# クリス
# 夜通しは正解だけど、遊びじゃないかな。
378 = "夜通しは正解だけど、遊びじゃないかな。"

# カズマ
# だったらなんだっていうんだよ。
329 = "だったらなんだっていうんだよ。"

# クリス
# 今夜一晩、夜が明けるまであたしの近くに\n居て欲しいんだ。
371 = "今夜一晩、夜が明けるまであたしの近くに\\n居て欲しいんだ。"

# クリス
# これが、キミに対するお仕置きだよ。
308 = "これが、キミに対するお仕置きだよ。"

# カズマ
# 何その色々期待しちゃいそうなお仕置き！
373 = "何その色々期待しちゃいそうなお仕置き！"

# クリス
# あはは、残念ながら、\nそのご期待には添えないかな。
283 = "あはは、残念ながら、\\nそのご期待には添えないかな。"

# カズマ
# 知ってたよ、そんなこと……。
414 = "知ってたよ、そんなこと……。"

# クリス
# どう説明したらいいかな。\nキミも知っての通りあたしって\nどこのパーティーにも所属してないじゃない？
339 = "どう説明したらいいかな。\\nキミも知っての通りあたしって\\nどこのパーティーにも所属してないじゃない？"

# クリス
# 自由きままに生きる生活は大好きだけど、\nやっぱり女１人だと夜は危険を感じることが\nあったりするんだよね。
417 = "自由きままに生きる生活は大好きだけど、\\nやっぱり女１人だと夜は危険を感じることが\\nあったりするんだよね。"

# クリス
# 職業柄、敵がいないとも言い切れないし。
416 = "職業柄、敵がいないとも言い切れないし。"

# クリス
# だから、あたしがゆっくり休めるように\n見張りをしていて欲しいんだ。
324 = "だから、あたしがゆっくり休めるように\\n見張りをしていて欲しいんだ。"

# カズマ
# 一晩中？
368 = "一晩中？"

# クリス
# うん、さっきも言ったとおり夜が明けるまで。\nって言うよりもあたしが起きるまで。
293 = "うん、さっきも言ったとおり夜が明けるまで。\\nって言うよりもあたしが起きるまで。"

# カズマ（Ｍ）
# display as カズマ
# （なるほど、これは確かにお仕置きだ……）
448 = "（なるほど、これは確かにお仕置きだ……）"

# カズマ
# いや、ちょっと待て！\nまさか廊下で見張ってろって言うんじゃ\nないだろうな。
286 = "いや、ちょっと待て！\\nまさか廊下で見張ってろって言うんじゃ\\nないだろうな。"

# クリス
# この部屋には窓があるんだから、\n廊下での見張りは意味無いよ。
307 = "この部屋には窓があるんだから、\\n廊下での見張りは意味無いよ。"

# カズマ
# だよなー？\nって、もう一回ちょっと待て！
330 = "だよなー？\\nって、もう一回ちょっと待て！"

# カズマ
# 今、この部屋って言わなかったか？
369 = "今、この部屋って言わなかったか？"

# クリス
# うん、キミのベッドを借りるね。
294 = "うん、キミのベッドを借りるね。"

# カズマ
# って、おいおい、言ってる側から\nベッドに潜り込むな！
334 = "って、おいおい、言ってる側から\\nベッドに潜り込むな！"

# クリス
# ふぁぁぁ、もう眠いの。\nそれじゃ、おやすみ……。
347 = "ふぁぁぁ、もう眠いの。\\nそれじゃ、おやすみ……。"

# カズマ（Ｍ）
# display as カズマ
# （おいおい、これはちょっと、\n　いやかなり想定外だぞ）
432 = "（おいおい、これはちょっと、\\n　いやかなり想定外だぞ）"

# カズマ（Ｍ）
# display as カズマ
# （そもそも身の危険を感じるって言うなら\n　男の俺と２人っきりっていうこの状況だって\n　十分危険な状況だと思うんだが）
440 = "（そもそも身の危険を感じるって言うなら\\n　男の俺と２人っきりっていうこの状況だって\\n　十分危険な状況だと思うんだが）"

# カズマ（Ｍ）
# display as カズマ
# （いや、逆に考えるんだ。\n　クリスは俺のことを信頼してくれているからこそ\n　自分の警護を任せてくれたのかもしれない）
428 = "（いや、逆に考えるんだ。\\n　クリスは俺のことを信頼してくれているからこそ\\n　自分の警護を任せてくれたのかもしれない）"

# クリス
# ……すぅ。
279 = "……すぅ。"

# カズマ
# クリス、もう寝たのか？
365 = "クリス、もう寝たのか？"

# クリス
# ……むにゃむにゃ。
280 = "……むにゃむにゃ。"

# カズマ（Ｍ）
# display as カズマ
# （よっぽど疲れてたんだな。\n　もう熟睡してら）
455 = "（よっぽど疲れてたんだな。\\n　もう熟睡してら）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、警護と言っても夜盗や賊なんて\n　絶対に来ないだろ）
453 = "（まあ、警護と言っても夜盗や賊なんて\\n　絶対に来ないだろ）"

# カズマ（Ｍ）
# display as カズマ
# （中身がアレだとはいえ、\n　上位職が３人も暮らしてる屋敷なんだし）
457 = "（中身がアレだとはいえ、\\n　上位職が３人も暮らしてる屋敷なんだし）"

# カズマ（Ｍ）
# display as カズマ
# （それに徹夜も楽勝だな）
441 = "（それに徹夜も楽勝だな）"

# カズマ（Ｍ）
# display as カズマ
# （ふっはっはっは、ネトゲで鍛えた徹夜スキルを\n　今こそ見せつけてやるぜ！）
451 = "（ふっはっはっは、ネトゲで鍛えた徹夜スキルを\\n　今こそ見せつけてやるぜ！）"

# クリス
# ん～……むにゃむにゃ。
359 = "ん～……むにゃむにゃ。"

# カズマ（Ｍ）
# display as カズマ
# （しかし……）
435 = "（しかし……）"

# クリス
# スースースースー……んん……。
366 = "スースースースー……んん……。"

# カズマ（Ｍ）
# display as カズマ
# （無防備にも程が有るだろ……）
459 = "（無防備にも程が有るだろ……）"

# クリス
# んっ、んん～……すーすーすー。
353 = "んっ、んん～……すーすーすー。"

# カズマ（Ｍ）
# display as カズマ
# （って、パジャマが！！）
444 = "（って、パジャマが！！）"

# カズマ
# …………。
277 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （よくよく考えたら、\n　男の部屋に来る格好じゃないだろこれ！）
454 = "（よくよく考えたら、\\n　男の部屋に来る格好じゃないだろこれ！）"

# カズマ（Ｍ）
# display as カズマ
# （しかもその格好のまま男の部屋、男の前で寝るか\n　普通！）
436 = "（しかもその格好のまま男の部屋、男の前で寝るか\\n　普通！）"

# カズマ（Ｍ）
# display as カズマ
# （せめてなんか羽織れよ！\n　あと、なんでそんな無防備に体を開いてるの！）
439 = "（せめてなんか羽織れよ！\\n　あと、なんでそんな無防備に体を開いてるの！）"

# カズマ（Ｍ）
# display as カズマ
# （くっはっ！\n　パジャマがずれてる、ずれてない以前の\n　問題だ！）
433 = "（くっはっ！\\n　パジャマがずれてる、ずれてない以前の\\n　問題だ！）"

# クリス
# すー……すー……すー……。
310 = "すー……すー……すー……。"

# カズマ（Ｍ）
# display as カズマ
# （あー、もう、これどうしたらいいんだ）
425 = "（あー、もう、これどうしたらいいんだ）"

# カズマ（Ｍ）
# display as カズマ
# （クリスの信頼は裏切りたくないし、でも……）
456 = "（クリスの信頼は裏切りたくないし、でも……）"

# クリス
# んっ、んん～……スースー。
354 = "んっ、んん～……スースー。"

# カズマ（Ｍ）
# display as カズマ
# （ああ……頭が痛くなって来た……）
423 = "（ああ……頭が痛くなって来た……）"

# カズマ（Ｍ）
# display as カズマ
# （とりあえず、パジャマの乱れを直してあげよう）
446 = "（とりあえず、パジャマの乱れを直してあげよう）"

# カズマ（Ｍ）
# display as カズマ
# （このまま放っておいたら色々見えちまいそうだし、\n　童貞には刺激が強すぎる……）
434 = "（このまま放っておいたら色々見えちまいそうだし、\\n　童貞には刺激が強すぎる……）"

# カズマ
# というわけで、クリスさん。\nちょっと失礼しますよ。
338 = "というわけで、クリスさん。\\nちょっと失礼しますよ。"

# カズマ（Ｍ）
# display as カズマ
# （ええと、チューブトップだっけ？\n　これって引っ張り上げればいいのか？）
431 = "（ええと、チューブトップだっけ？\\n　これって引っ張り上げればいいのか？）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、ちょっと難易度が高いか……。\n　やっぱり先にズボンのずれを……）
430 = "（うーん、ちょっと難易度が高いか……。\\n　やっぱり先にズボンのずれを……）"

# カズマ（Ｍ）
# display as カズマ
# （って、見えてるし！\n　健全な青少年には刺激が強すぎる薄い布が\n　チラリと！）
445 = "（って、見えてるし！\\n　健全な青少年には刺激が強すぎる薄い布が\\n　チラリと！）"

# カズマ（Ｍ）
# display as カズマ
# （しばらく拝んでいたいけど、\n　それはクリスの信頼を裏切ることだ！）
437 = "（しばらく拝んでいたいけど、\\n　それはクリスの信頼を裏切ることだ！）"

# カズマ（Ｍ）
# display as カズマ
# （そーと、優しく、掴んで……）
442 = "（そーと、優しく、掴んで……）"

# カズマ（Ｍ）
# display as カズマ
# （ううーん、尻を浮かせてくれないと難しいか）
429 = "（ううーん、尻を浮かせてくれないと難しいか）"

# カズマ（Ｍ）
# display as カズマ
# （しゃーない、やっぱりまずは胸の方を……）
438 = "（しゃーない、やっぱりまずは胸の方を……）"

# カズマ
# って、あ……。
331 = "って、あ……。"

# クリス
# おはよう。
305 = "おはよう。"

# カズマ（Ｍ）
# display as カズマ
# （いかん、これは完全に誤解をしてる目だ！）
427 = "（いかん、これは完全に誤解をしてる目だ！）"

# クリス
# いったい、何をしてたのかなー？
285 = "いったい、何をしてたのかなー？"

# カズマ
# それは誤解だクリス！\n俺は、ただ――
320 = "それは誤解だクリス！\\n俺は、ただ――"

# クリス
# ただ、何？
323 = "ただ、何？"

# カズマ
# って、ダガーを握るな！\nまずは俺の話を聞いてくれ！
335 = "って、ダガーを握るな！\\nまずは俺の話を聞いてくれ！"

# クリス
# 話じゃなくて、言い訳でしょ。
419 = "話じゃなくて、言い訳でしょ。"

# カズマ
# だからちがーう！！\n俺は紳士的に、お前のパジャマのずれを直そうと\n思ったんだよ！
326 = "だからちがーう！！\\n俺は紳士的に、お前のパジャマのずれを直そうと\\n思ったんだよ！"

# クリス
# え……。
296 = "え……。"

# カズマ
# こっそりやってた俺にも非はある。\nそれは認めるけど、お前のこの格好もねーからな！
306 = "こっそりやってた俺にも非はある。\\nそれは認めるけど、お前のこの格好もねーからな！"

# カズマ
# せめて、少し動いただけじゃずれない\n強固なパジャマを着てきてくれ！
314 = "せめて、少し動いただけじゃずれない\\n強固なパジャマを着てきてくれ！"

# クリス
# え、ずれ……って。\nきゃっ！！　見えてる！
298 = "え、ずれ……って。\\nきゃっ！！　見えてる！"

# カズマ
# あのな、クリス。\n信頼してくれてるのは嬉しいけどさ。\n俺も一応、男なんだから……。
282 = "あのな、クリス。\\n信頼してくれてるのは嬉しいけどさ。\\n俺も一応、男なんだから……。"

# クリス
# うぅぅぅ、もしかして見た？
289 = "うぅぅぅ、もしかして見た？"

# カズマ
# そりゃ、まあ、チラリと。
319 = "そりゃ、まあ、チラリと。"

# クリス
# エッチ……。
360 = "エッチ……。"

# カズマ
# どこからどう考えても不可抗力ですよね！
340 = "どこからどう考えても不可抗力ですよね！"

# クリス
# そうだね。\n確かに今回のことはあたしの非の方が大きいかも\nしれない。
318 = "そうだね。\\n確かに今回のことはあたしの非の方が大きいかも\\nしれない。"

# クリス
# だからお咎め無しにしてあげる。
325 = "だからお咎め無しにしてあげる。"

# カズマ
# はぁ、それはどーも。
343 = "はぁ、それはどーも。"

# クリス
# でも、もし次見えそうになったら、\nもしくはパジャマがずれそうになったら、\nすぐに起こして！
336 = "でも、もし次見えそうになったら、\\nもしくはパジャマがずれそうになったら、\\nすぐに起こして！"

# カズマ（Ｍ）
# display as カズマ
# （起こした方がいいか……。\n　下手に俺が手を出して誤解されるより\n　そのほうがいいよな）
461 = "（起こした方がいいか……。\\n　下手に俺が手を出して誤解されるより\\n　そのほうがいいよな）"

# カズマ
# おい、クリス。起きろよ。
300 = "おい、クリス。起きろよ。"

# クリス
# ん～……。
358 = "ん～……。"

# カズマ
# おいってば。\n少しでいいから起きろって。\n下着見えてるぞ。
301 = "おいってば。\\n少しでいいから起きろって。\\n下着見えてるぞ。"

# クリス
# ……ううん？
278 = "……ううん？"

# カズマ
# おっ、いい子だ。良く起きられたな。
303 = "おっ、いい子だ。良く起きられたな。"

# クリス
# うう～ん……すーすー。
290 = "うう～ん……すーすー。"

# カズマ
# そういうお約束はいらないから！
317 = "そういうお約束はいらないから！"

# クリス
# もう、なぁに？
349 = "もう、なぁに？"

# カズマ
# 男心をくすぐる薄い布がチラリと見えてる。
381 = "男心をくすぐる薄い布がチラリと見えてる。"

# クリス
# おとこ……ごころ？
304 = "おとこ……ごころ？"

# カズマ
# わかりやすくいうとパンツだな。
352 = "わかりやすくいうとパンツだな。"

# クリス
# ぱん……つ……。
345 = "ぱん……つ……。"

# カズマ
# さらに言うと、上も少しずれてるぞ。
309 = "さらに言うと、上も少しずれてるぞ。"

# クリス
# うえ……。
291 = "うえ……。"

# カズマ
# そう、上。
316 = "そう、上。"

# クリス
# って、ええ！？
333 = "って、ええ！？"

# クリス
# って、うわ、待って！\nなんでずれてるの！
332 = "って、うわ、待って！\\nなんでずれてるの！"

# カズマ
# そんな防御力が低そうなパジャマだからだろ。
322 = "そんな防御力が低そうなパジャマだからだろ。"

# クリス
# う、うう～～～～！！
287 = "う、うう～～～～！！"

# カズマ
# そんな目で見られても困る。\n俺はちゃんと起こして教えたんだからな。
321 = "そんな目で見られても困る。\\n俺はちゃんと起こして教えたんだからな。"

# クリス
# カズマのエッチ……。
362 = "カズマのエッチ……。"

# カズマ
# 俺は何もやってなーい！！
375 = "俺は何もやってなーい！！"

# クリス
# 確かにキミは何も悪くないね。
415 = "確かにキミは何も悪くないね。"

# カズマ
# わかって貰えたようで、何よりだ。
351 = "わかって貰えたようで、何よりだ。"

# クリス
# でも次は、もっと傷が浅いうちに\n起こして欲しいかな。
337 = "でも次は、もっと傷が浅いうちに\\n起こして欲しいかな。"

# カズマ（Ｍ）
# display as カズマ
# （見るくらいなら……いいよな）
460 = "（見るくらいなら……いいよな）"

# カズマ（Ｍ）
# display as カズマ
# （少しご褒美を貰うくらいじゃ、\n　バチは当たらないだろ）
458 = "（少しご褒美を貰うくらいじゃ、\\n　バチは当たらないだろ）"

# カズマ（Ｍ）
# display as カズマ
# （ふっはっはっは！\n　さぁて、じっくり鑑賞させてもらうか！！）
452 = "（ふっはっはっは！\\n　さぁて、じっくり鑑賞させてもらうか！！）"

# クリス
# んん……んん……。
356 = "んん……んん……。"

# カズマ（Ｍ）
# display as カズマ
# （いいねいいね、もっと動いちゃって！\n　そうすれば色々とずれて……）
426 = "（いいねいいね、もっと動いちゃって！\\n　そうすれば色々とずれて……）"

# クリス
# んん……すーすー……んん。
355 = "んん……すーすー……んん。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、もう、クリスさんったら大胆！）
424 = "（ああ、もう、クリスさんったら大胆！）"

# クリス
# すーすー……んん～～。
313 = "すーすー……んん～～。"

# カズマ（Ｍ）
# display as カズマ
# （ちょっと待て、それはサービスし過ぎだ！）
443 = "（ちょっと待て、それはサービスし過ぎだ！）"

# クリス
# んん～……あつ……い……。
357 = "んん～……あつ……い……。"

# カズマ
# はい、ストーーーーープっ！！
344 = "はい、ストーーーーープっ！！"

# クリス
# ええ！？
299 = "ええ！？"

# カズマ
# 起きたな？　起きたよな？
420 = "起きたな？　起きたよな？"

# クリス
# う、うん、起きたけど。
288 = "う、うん、起きたけど。"

# カズマ
# 暑いか？
380 = "暑いか？"

# クリス
# そ、そうだね。\nちょっと汗掻いちゃってるし。
315 = "そ、そうだね。\\nちょっと汗掻いちゃってるし。"

# カズマ
# だからって脱ごうとするな！！
327 = "だからって脱ごうとするな！！"

# クリス
# え……ええ！？
297 = "え……ええ！？"

# クリス
# うわ、どうしてあたし、ズボンに手をかけてるの！
292 = "うわ、どうしてあたし、ズボンに手をかけてるの！"

# カズマ
# いいからっ、今すぐっ、パジャマのずれをっ、直せ！
284 = "いいからっ、今すぐっ、パジャマのずれをっ、直せ！"

# クリス
# わ、わかった！
350 = "わ、わかった！"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、俺ってとことんチキンだな）
450 = "（はぁ、俺ってとことんチキンだな）"

# クリス
# あ、あの、カズマ？\n教えてくれて……ありがと。
281 = "あ、あの、カズマ？\\n教えてくれて……ありがと。"

# カズマ
# なーに、紳士として当然のことをしたまでさ。
342 = "なーに、紳士として当然のことをしたまでさ。"

# クリス
# うん、キミはやっぱり信用できるよ。
295 = "うん、キミはやっぱり信用できるよ。"

# カズマ（Ｍ）
# display as カズマ
# （あ、自分で変な縛りを作っちまった）
422 = "（あ、自分で変な縛りを作っちまった）"

# クリス
# またあたしが変なことをしそうになったら\nたたき起こしてね？
348 = "またあたしが変なことをしそうになったら\\nたたき起こしてね？"

# カズマ
# おい待て……。\nまさかまだここで寝るつもりなのか？
302 = "おい待て……。\\nまさかまだここで寝るつもりなのか？"

# クリス
# 何か問題でもある？
372 = "何か問題でもある？"

# カズマ
# 今、問題が起こったばっかりだろ！\nって、さっそく寝るな！
370 = "今、問題が起こったばっかりだろ！\\nって、さっそく寝るな！"

# クリス
# 問題……確かにそうだね。\nふぁぁぁ、でも、キミはあたしの信頼に\n答えてくれた……か……ら……。
377 = "問題……確かにそうだね。\\nふぁぁぁ、でも、キミはあたしの信頼に\\n答えてくれた……か……ら……。"

# クリス
# すーすー……。
311 = "すーすー……。"

# カズマ
# だから寝付きがよすぎるだろ！
328 = "だから寝付きがよすぎるだろ！"

# クリス
# すーすー……んん……。
312 = "すーすー……んん……。"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、これが一晩中続くのか……）
449 = "（はぁ、これが一晩中続くのか……）"

# カズマ（Ｍ）
# display as カズマ
# （とりあえず毛布を掛けて体を隠しておこう）
447 = "（とりあえず毛布を掛けて体を隠しておこう）"

[selections]
367 = "パジャマの乱れを直してあげよう"
421 = "起こした方がいいか……"
418 = "見るくらいなら……"
