# rew_c08.txt.scn

[info]
239 = "rew_c08"

[characters]
332 = "カズマ"
334 = "ダクネス"
333 = "カズマ（Ｍ）"

[character_subs]
# 332 = "カズマ"

[script]
# lines: 102

# カズマ
# なぁ、早くお仕置きの内容を決めてくれないか？
304 = "なぁ、早くお仕置きの内容を決めてくれないか？"

# ダクネス
# そうは言われても、\n相手が嫌がることを考えるのは、\n意外に難しいものなんだぞ。
287 = "そうは言われても、\\n相手が嫌がることを考えるのは、\\n意外に難しいものなんだぞ。"

# ダクネス
# 自分がされたいことは、すぐに思いつくのだが。
356 = "自分がされたいことは、すぐに思いつくのだが。"

# カズマ
# はいはい、そうだな。
308 = "はいはい、そうだな。"

# ダクネス
# うーん、お仕置きか。\nカズマが屈辱に思うようなこと。
272 = "うーん、お仕置きか。\\nカズマが屈辱に思うようなこと。"

# ダクネス
# そうだ！　私の前に跪くというのはどうだろうか！
286 = "そうだ！　私の前に跪くというのはどうだろうか！"

# ダクネス
# 男は女に跪かされるのを屈辱と感じるものだと\n聞いた事がある。
341 = "男は女に跪かされるのを屈辱と感じるものだと\\n聞いた事がある。"

# カズマ（Ｍ）
# display as カズマ
# （相手がアクアだと、確かに屈辱的に感じるかも\n　しれないけど、ダクネスだとあんまり意味が\n　ないかもな）
379 = "（相手がアクアだと、確かに屈辱的に感じるかも\\n　しれないけど、ダクネスだとあんまり意味が\\n　ないかもな）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスは、アレな所があるけど、\n　良家のお嬢様だけあって、気立ては申し分ない）
378 = "（ダクネスは、アレな所があるけど、\\n　良家のお嬢様だけあって、気立ては申し分ない）"

# カズマ（Ｍ）
# display as カズマ
# （うん、まるで姫にかしずく騎士みたいで\n　ちょっとカッコ良いじゃないか）
364 = "（うん、まるで姫にかしずく騎士みたいで\\n　ちょっとカッコ良いじゃないか）"

# カズマ
# よし、それでいこう！
320 = "よし、それでいこう！"

# ダクネス
# うむ、では、靴下を履かせてくれ。
271 = "うむ、では、靴下を履かせてくれ。"

# カズマ
# は？
310 = "は？"

# ダクネス
# だから、靴下を履かせてくれと言ったんだ。
294 = "だから、靴下を履かせてくれと言ったんだ。"

# カズマ
# ええと、どうしてだ？
275 = "ええと、どうしてだ？"

# ダクネス
# なぜって、跪くだけでは屈辱感が足りないだろう。
305 = "なぜって、跪くだけでは屈辱感が足りないだろう。"

# ダクネス
# だから、少しだけ趣向を凝らしてみた。
293 = "だから、少しだけ趣向を凝らしてみた。"

# カズマ（Ｍ）
# display as カズマ
# （なるほど、自分がやられて嬉しいことを\n　言ってみたのか）
373 = "（なるほど、自分がやられて嬉しいことを\\n　言ってみたのか）"

# カズマ
# わかった、やるからベッドに座ってくれ。
324 = "わかった、やるからベッドに座ってくれ。"

# ダクネス
# では、よろしく頼む。
299 = "では、よろしく頼む。"

# カズマ（Ｍ）
# display as カズマ
# （……これは）
360 = "（……これは）"

# カズマ（Ｍ）
# display as カズマ
# （か、角度が絶妙だな……。\n　それに、目のやり場に困る）
367 = "（か、角度が絶妙だな……。\\n　それに、目のやり場に困る）"

# ダクネス
# どうかしたか、カズマ？
301 = "どうかしたか、カズマ？"

# カズマ
# あ、ああ、悪い。\n思ったよりも屈辱だなーって思ってさ。
262 = "あ、ああ、悪い。\\n思ったよりも屈辱だなーって思ってさ。"

# ダクネス
# そ、そうなのか？\n嫌なら代わってやらなくもないぞ。
285 = "そ、そうなのか？\\n嫌なら代わってやらなくもないぞ。"

# カズマ
# それじゃお仕置きにならないだろ。
289 = "それじゃお仕置きにならないだろ。"

# ダクネス
# た、確かに。
292 = "た、確かに。"

# カズマ
# よし、じゃあいくぞ！
319 = "よし、じゃあいくぞ！"

# カズマ（Ｍ）
# display as カズマ
# （ええと、こうか？）
366 = "（ええと、こうか？）"

# ダクネス
# う、うう……。
270 = "う、うう……。"

# カズマ（Ｍ）
# display as カズマ
# （うーん、かかとが上手く通らないな。\n　ゆっくり、ゆっくりっと……）
365 = "（うーん、かかとが上手く通らないな。\\n　ゆっくり、ゆっくりっと……）"

# ダクネス
# ひゃぁ！　ちょちょ、ちょっと待てくれ！！
312 = "ひゃぁ！　ちょちょ、ちょっと待てくれ！！"

# カズマ
# な、なんだよ！
303 = "な、なんだよ！"

# ダクネス
# あはは、くすぐったいんだ！
267 = "あはは、くすぐったいんだ！"

# カズマ
# こら、足を出すな！　顔にかすったぞ！
281 = "こら、足を出すな！　顔にかすったぞ！"

# ダクネス
# そうは言われても！\nハハ、ハハ、やめてくれ！
288 = "そうは言われても！\\nハハ、ハハ、やめてくれ！"

# カズマ
# あと、足を上げるなっ！
265 = "あと、足を上げるなっ！"

# カズマ（Ｍ）
# display as カズマ
# （見える！　いや、見たい！\n　が、絶妙に隠れて、くそぉぉぉ！！）
380 = "（見える！　いや、見たい！\\n　が、絶妙に隠れて、くそぉぉぉ！！）"

# ダクネス
# と、とにかく、アハハ、一回抜いてくれ！
300 = "と、とにかく、アハハ、一回抜いてくれ！"

# カズマ
# わ、わかったよ！
322 = "わ、わかったよ！"

# ダクネス
# はぁはぁ、私にお仕置きしてどうするんだ！
307 = "はぁはぁ、私にお仕置きしてどうするんだ！"

# カズマ
# そんな意思はねーよ！
291 = "そんな意思はねーよ！"

# カズマ（Ｍ）
# display as カズマ
# （うぬぅ、これじゃ顔に蹴りを入れられるのも\n　時間の問題だな）
363 = "（うぬぅ、これじゃ顔に蹴りを入れられるのも\\n　時間の問題だな）"

# カズマ（Ｍ）
# display as カズマ
# （こうなったら、早く終わらせよう）
368 = "（こうなったら、早く終わらせよう）"

# カズマ
# ダクネス、もう一度行くぞ！
335 = "ダクネス、もう一度行くぞ！"

# ダクネス
# わ、わかった！　ドンとこい！
323 = "わ、わかった！　ドンとこい！"

# カズマ（Ｍ）
# display as カズマ
# （せーのっ！　そいや！！）
371 = "（せーのっ！　そいや！！）"

# ダクネス
# アハ、アハハハハハ！\nだ、だからくすぐったいって言ってるだろ！
326 = "アハ、アハハハハハ！\\nだ、だからくすぐったいって言ってるだろ！"

# カズマ
# だー！　お前は足を動かすな！\n見えちまうぞ！
297 = "だー！　お前は足を動かすな！\\n見えちまうぞ！"

# ダクネス
# アハハハ、見えるって何がだ！
330 = "アハハハ、見えるって何がだ！"

# カズマ
# だーかーらっ！\nこの状況で足を高く上げたら何が見えるか\n考えてみろ！
296 = "だーかーらっ！\\nこの状況で足を高く上げたら何が見えるか\\n考えてみろ！"

# ダクネス
# はっ！？
309 = "はっ！？"

# カズマ
# チャーンス！！
336 = "チャーンス！！"

# カズマ
# よっしっ！！
321 = "よっしっ！！"

# カズマ（Ｍ）
# display as カズマ
# （さすが俺！\n　よれが少しも無い完璧な履かせ方だ！）
369 = "（さすが俺！\\n　よれが少しも無い完璧な履かせ方だ！）"

# ダクネス
# カ、カズマ？　み、見たのか？
331 = "カ、カズマ？　み、見たのか？"

# カズマ（Ｍ）
# display as カズマ
# （……え？）
359 = "（……え？）"

# ダクネス
# 見たんだな！
357 = "見たんだな！"

# カズマ
# いやいや、見てねーよ！
269 = "いやいや、見てねーよ！"

# ダクネス
# そ、そうか、見たのか。\nまったく油断も隙もないものだな。
283 = "そ、そうか、見たのか。\\nまったく油断も隙もないものだな。"

# カズマ
# だから見てねーって言ってるだろ！\n人の話を聞け！
295 = "だから見てねーって言ってるだろ！\\n人の話を聞け！"

# カズマ（Ｍ）
# display as カズマ
# （蹴りを警戒しながらゆっくりと履かせれば）
381 = "（蹴りを警戒しながらゆっくりと履かせれば）"

# ダクネス
# アハハ、くすぐったいっ！\nさ、さては、わざとやっているなぁ！
328 = "アハハ、くすぐったいっ！\\nさ、さては、わざとやっているなぁ！"

# カズマ
# あぶなっ！　足を出すな！
268 = "あぶなっ！　足を出すな！"

# ダクネス
# そ、そうさせているのは、ハハ、カズマだろう！
284 = "そ、そうさせているのは、ハハ、カズマだろう！"

# カズマ
# お前は、剣はあたらないくせに、\nどうして蹴りはこんなに鋭いんだよ！
278 = "お前は、剣はあたらないくせに、\\nどうして蹴りはこんなに鋭いんだよ！"

# ダクネス
# この状況で罵倒までするなんて、\nどんなご褒美だぁ！
280 = "この状況で罵倒までするなんて、\\nどんなご褒美だぁ！"

# カズマ
# そんなつもりねーから！
290 = "そんなつもりねーから！"

# ダクネス
# アハ、アハハ！　やめてくれ！\nくすぐったいのは、私ぃぃぃ！！
327 = "アハ、アハハ！　やめてくれ！\\nくすぐったいのは、私ぃぃぃ！！"

# カズマ（Ｍ）
# display as カズマ
# （も、もうちょっとで全部っ！）
375 = "（も、もうちょっとで全部っ！）"

# ダクネス
# ひああ、も、もう、無理だーーーー！！
311 = "ひああ、も、もう、無理だーーーー！！"

# カズマ（Ｍ）
# display as カズマ
# （よっしっ、入った！）
377 = "（よっしっ、入った！）"

# カズマ
# ぐあっ！！　鼻がっ、鼻がぁぁあああ！！
279 = "ぐあっ！！　鼻がっ、鼻がぁぁあああ！！"

# ダクネス
# あっ、す、すまない、大丈夫か？
264 = "あっ、す、すまない、大丈夫か？"

# カズマ
# お仕置きだとしても、顔に蹴りを入れるのは\nやり過ぎだと思うぞ。
276 = "お仕置きだとしても、顔に蹴りを入れるのは\\nやり過ぎだと思うぞ。"

# ダクネス
# 私にそんなつもりは！
354 = "私にそんなつもりは！"

# カズマ
# まあ、いいよ。\nほら、じゃあ次は逆の足。
315 = "まあ、いいよ。\\nほら、じゃあ次は逆の足。"

# ダクネス
# な！？
306 = "な！？"

# カズマ（Ｍ）
# display as カズマ
# （どうして嬉しそうにしてんだ、こいつ）
372 = "（どうして嬉しそうにしてんだ、こいつ）"

# ダクネス
# ふ、ふふふ、そうかそういう目論見か。
313 = "ふ、ふふふ、そうかそういう目論見か。"

# カズマ（Ｍ）
# display as カズマ
# （はあ？）
374 = "（はあ？）"

# ダクネス
# また、じっくりねっとりなぶるように\n入れるつもりなんだな。
316 = "また、じっくりねっとりなぶるように\\n入れるつもりなんだな。"

# カズマ
# お前っ！　言葉を選べ、言葉を！！
277 = "お前っ！　言葉を選べ、言葉を！！"

# カズマ（Ｍ）
# display as カズマ
# （あえて、くすぐってみよう！）
361 = "（あえて、くすぐってみよう！）"

# カズマ
# さわ、さわ、さわわーっ！！
282 = "さわ、さわ、さわわーっ！！"

# ダクネス
# アハハ、ハ、ハハ、ななな、何をするぅぅ！！
329 = "アハハ、ハ、ハハ、ななな、何をするぅぅ！！"

# カズマ（Ｍ）
# display as カズマ
# （さらに……）
370 = "（さらに……）"

# カズマ
# ゆっくーり、ゆっくーり、まるで舐め上げるように\n履かせて。
318 = "ゆっくーり、ゆっくーり、まるで舐め上げるように\\n履かせて。"

# ダクネス
# え……。
273 = "え……。"

# カズマ
# もちろん足に視線を絡みつけるのも忘れない！
317 = "もちろん足に視線を絡みつけるのも忘れない！"

# ダクネス
# え、ええと、カズマ？
274 = "え、ええと、カズマ？"

# カズマ
# フフフフ、まるで黒い靴下が白い足を\n浸食していくようじゃないか！
337 = "フフフフ、まるで黒い靴下が白い足を\\n浸食していくようじゃないか！"

# カズマ
# どうだ、ダクネス！\n足が汚されていく気持ちは！
302 = "どうだ、ダクネス！\\n足が汚されていく気持ちは！"

# ダクネス
# …………。
261 = "…………。"

# カズマ
# ほーら、もう少しで履かせ終わっちゃうぞ。\nそーれ、そーれ。
314 = "ほーら、もう少しで履かせ終わっちゃうぞ。\\nそーれ、そーれ。"

# カズマ（Ｍ）
# display as カズマ
# （よしっ、完璧だ！）
376 = "（よしっ、完璧だ！）"

# ダクネス
# …………。
# 261 = "…………。"

# カズマ
# ん？　どうかしたか、ダクネス。
325 = "ん？　どうかしたか、ダクネス。"

# ダクネス
# あの、ええと。
266 = "あの、ええと。"

# カズマ（Ｍ）
# display as カズマ
# （あれ？　もしかして引いてる？）
362 = "（あれ？　もしかして引いてる？）"

# ダクネス
# 私はもう、部屋に帰らせて貰う。
355 = "私はもう、部屋に帰らせて貰う。"

# カズマ
# ちょっ、待て！\n今のは違うんだ！　俺の言い分を聞いてくれ！！
298 = "ちょっ、待て！\\n今のは違うんだ！　俺の言い分を聞いてくれ！！"

[selections]
340 = "早く終わらせよう！"
358 = "蹴りを警戒しながらゆっくりと"
263 = "あえて、くすぐってみよう！"
