# rew_c02.txt.scn

[info]
222 = "rew_c02"

[characters]
304 = "カズマ"
306 = "ダクネス"
305 = "カズマ（Ｍ）"

[character_subs]
# 304 = "カズマ"

[script]
# lines: 92

# カズマ
# はぁはぁはぁ。\nちょ、ちょっと休憩。
290 = "はぁはぁはぁ。\\nちょ、ちょっと休憩。"

# ダクネス
# なんだ、もうへばったのか？\nまだ１時間も泳いでいないぞ。
286 = "なんだ、もうへばったのか？\\nまだ１時間も泳いでいないぞ。"

# カズマ
# 前衛職のクルセイダーと体力比べできるほど、\n冒険者は強くねーよ。
312 = "前衛職のクルセイダーと体力比べできるほど、\\n冒険者は強くねーよ。"

# ダクネス
# ふふっ、せっかくだし、私も少し休憩しようか。
294 = "ふふっ、せっかくだし、私も少し休憩しようか。"

# ダクネス
# ほら、さっき沼のほとりで冷やしておいた水だ。\n飲んでおけ。
295 = "ほら、さっき沼のほとりで冷やしておいた水だ。\\n飲んでおけ。"

# カズマ
# おっ、サンキュー！
259 = "おっ、サンキュー！"

# ダクネス
# あっ、もうそれしか無いんだから全部飲むなよ？
247 = "あっ、もうそれしか無いんだから全部飲むなよ？"

# カズマ
# え？　お前、たくさん持って来てただろ。
256 = "え？　お前、たくさん持って来てただろ。"

# ダクネス
# 飲んでしまったんだ。\n熱中症になって、カズマに迷惑をかけるわけには\nいかないからな。
366 = "飲んでしまったんだ。\\n熱中症になって、カズマに迷惑をかけるわけには\\nいかないからな。"

# カズマ（Ｍ）
# display as カズマ
# （あの量をひとりで？\n　さすがにそれは飲み過ぎだろ）
368 = "（あの量をひとりで？\\n　さすがにそれは飲み過ぎだろ）"

# ダクネス
# どうした？　飲まないなら先に貰うぞ。
278 = "どうした？　飲まないなら先に貰うぞ。"

# カズマ（Ｍ）
# display as カズマ
# （あっ！）
367 = "（あっ！）"

# ダクネス
# んっ、んっ、んっ、ふぅぅっ。\nほら、カズマも飲んでおけ。
303 = "んっ、んっ、んっ、ふぅぅっ。\\nほら、カズマも飲んでおけ。"

# カズマ
# いや、でも。\nこれって今、ダクネスが口を……。
252 = "いや、でも。\\nこれって今、ダクネスが口を……。"

# ダクネス
# なんだ、汚いと言いたいのか。\n失礼にも程があるぞ。
287 = "なんだ、汚いと言いたいのか。\\n失礼にも程があるぞ。"

# ダクネス
# だが、さすがカズマだな。\nふ、ふふふ、女性が傷つくところをよく心得ている。
274 = "だが、さすがカズマだな。\\nふ、ふふふ、女性が傷つくところをよく心得ている。"

# カズマ（Ｍ）
# display as カズマ
# （あー、ダクネスが相手だと\n　萌えイベントも何もありゃしないな）
370 = "（あー、ダクネスが相手だと\\n　萌えイベントも何もありゃしないな）"

# ダクネス
# とにかく水分補給はしておけ。\n倒れたりしたら、それこそ事だ。
277 = "とにかく水分補給はしておけ。\\n倒れたりしたら、それこそ事だ。"

# カズマ
# そうだな。\nじゃあ、ありがたく。
270 = "そうだな。\\nじゃあ、ありがたく。"

# カズマ（Ｍ）
# display as カズマ
# （んっ、んっ、んっ。\n　うん、よく冷えてて美味い）
379 = "（んっ、んっ、んっ。\\n　うん、よく冷えてて美味い）"

# ダクネス
# なぁ、カズマ。\n１つ聞きたいのだが、私とこういうことをして\nご褒美になるのか？
282 = "なぁ、カズマ。\\n１つ聞きたいのだが、私とこういうことをして\\nご褒美になるのか？"

# カズマ
# ああ、充分ご褒美になってるよ。
245 = "ああ、充分ご褒美になってるよ。"

# カズマ（Ｍ）
# display as カズマ
# （日本にいたときは、\n　こんな美人で巨乳なお姉さんとデートするなんて\n　あり得なかったからな！）
387 = "（日本にいたときは、\\n　こんな美人で巨乳なお姉さんとデートするなんて\\n　あり得なかったからな！）"

# カズマ
# ダクネスこそ、無理に付き合ってくれてるんじゃ\nないのか？
308 = "ダクネスこそ、無理に付き合ってくれてるんじゃ\\nないのか？"

# ダクネス
# それはないが――
271 = "それはないが――"

# カズマ
# ないが？
285 = "ないが？"

# ダクネス
# 正直言うと、カズマに誘われた時、\nどんなところに連れて行かれるのだろうかと、\n期待――いや、心配して色々と想像したんだ。
318 = "正直言うと、カズマに誘われた時、\\nどんなところに連れて行かれるのだろうかと、\\n期待――いや、心配して色々と想像したんだ。"

# カズマ（Ｍ）
# display as カズマ
# （今、期待って言ったよな）
382 = "（今、期待って言ったよな）"

# ダクネス
# だが、こんな素敵な場所だったとはな。\nちょっと残念――ではなく、意外性に驚かされたぞ。
273 = "だが、こんな素敵な場所だったとはな。\\nちょっと残念――ではなく、意外性に驚かされたぞ。"

# カズマ（Ｍ）
# display as カズマ
# （今の言葉の裏は考えないようにしよう……）
384 = "（今の言葉の裏は考えないようにしよう……）"

# ダクネス
# しかし、２人っきりでというのは\nちょっと勿体なかったかもしれないな。
264 = "しかし、２人っきりでというのは\\nちょっと勿体なかったかもしれないな。"

# ダクネス
# こんなに楽しいなら、皆も誘えばよかった。
262 = "こんなに楽しいなら、皆も誘えばよかった。"

# カズマ
# 何を言ってるんだ。\n２人きりだからいいんじゃないか。
310 = "何を言ってるんだ。\\n２人きりだからいいんじゃないか。"

# ダクネス
# そ、そうなのか？
267 = "そ、そうなのか？"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスは気がついていないだろうが――）
381 = "（ダクネスは気がついていないだろうが――）"

# カズマ（Ｍ）
# display as カズマ
# （俺はここについてから、\n　隙を見つけてはさりげなくちらっと横目で、\n　そのたわわなおっぱいを楽しませて貰ってたんだ）
385 = "（俺はここについてから、\\n　隙を見つけてはさりげなくちらっと横目で、\\n　そのたわわなおっぱいを楽しませて貰ってたんだ）"

# カズマ（Ｍ）
# display as カズマ
# （今だって、胸の谷間を堪能しようと……ん？）
383 = "（今だって、胸の谷間を堪能しようと……ん？）"

# ダクネス
# ん……んん……。
302 = "ん……んん……。"

# カズマ
# ダクネス、どうかしたのか、モジモジして。
307 = "ダクネス、どうかしたのか、モジモジして。"

# ダクネス
# い、いや、なんでもない。\nうん、なんでもないぞ。
249 = "い、いや、なんでもない。\\nうん、なんでもないぞ。"

# カズマ
# ……本当に？
244 = "……本当に？"

# ダクネス
# と、当然だ！
275 = "と、当然だ！"

# カズマ
# とか言いながら、周りをキョロキョロ\n見てるじゃないか。
276 = "とか言いながら、周りをキョロキョロ\\n見てるじゃないか。"

# カズマ
# まるで、身を隠せる草陰を探すように。
297 = "まるで、身を隠せる草陰を探すように。"

# ダクネス
# は、はは、おかしな事を言うな。\n私は、綺麗な景色だなと思って見ていただけだ。
289 = "は、はは、おかしな事を言うな。\\n私は、綺麗な景色だなと思って見ていただけだ。"

# カズマ
# じゃあ、前屈みになってるのはどうして？
265 = "じゃあ、前屈みになってるのはどうして？"

# ダクネス
# そ、それは、体が冷えてしまったから、\n背中に陽の光を少しでも浴びようと……。
268 = "そ、それは、体が冷えてしまったから、\\n背中に陽の光を少しでも浴びようと……。"

# カズマ（Ｍ）
# display as カズマ
# （その言い訳は苦しいぞ、ダクネス）
372 = "（その言い訳は苦しいぞ、ダクネス）"

# カズマ（Ｍ）
# display as カズマ
# （はあ、どうして素直にトイレに行きたいって\n　言わないかな）
376 = "（はあ、どうして素直にトイレに行きたいって\\n　言わないかな）"

# カズマ（Ｍ）
# display as カズマ
# （はっ！　もしかしたらそういうプレイなのか？）
377 = "（はっ！　もしかしたらそういうプレイなのか？）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスならありえる。\n　いや、それしか考えられない）
380 = "（ダクネスならありえる。\\n　いや、それしか考えられない）"

# カズマ（Ｍ）
# display as カズマ
# （だったら……）
373 = "（だったら……）"

# カズマ
# なあ、ダクネス。\nなんか調子が悪そうだぞ？　大丈夫か？
283 = "なあ、ダクネス。\\nなんか調子が悪そうだぞ？　大丈夫か？"

# カズマ
# 仲間なんだし、こういう時は遠慮なく頼ってくれよ。
309 = "仲間なんだし、こういう時は遠慮なく頼ってくれよ。"

# ダクネス
# い、いや、これは私の個人的なことだ。\nだから、カズマには……関係ない。
248 = "い、いや、これは私の個人的なことだ。\\nだから、カズマには……関係ない。"

# カズマ
# 悲しい事を言うなよ。\n困ったときは助け合わなきゃ。
315 = "悲しい事を言うなよ。\\n困ったときは助け合わなきゃ。"

# ダクネス
# いいい、いや、だから、大丈夫だ。
250 = "いいい、いや、だから、大丈夫だ。"

# ダクネス
# あぅ！\nわ、私はクルセイダーだから耐えることに\n慣れているぅ！
246 = "あぅ！\\nわ、私はクルセイダーだから耐えることに\\n慣れているぅ！"

# カズマ
# 耐えるって何に？
365 = "耐えるって何に？"

# ダクネス
# し、しまった！
263 = "し、しまった！"

# カズマ
# え？　何がしまったなの？
257 = "え？　何がしまったなの？"

# ダクネス
# そ、そ、それは……くぅぅ！！
266 = "そ、そ、それは……くぅぅ！！"

# カズマ（Ｍ）
# display as カズマ
# （あれ？　もしかしてこれって\n　プレイじゃない？）
369 = "（あれ？　もしかしてこれって\\n　プレイじゃない？）"

# カズマ
# なあダクネス。そろそろ帰るか。
284 = "なあダクネス。そろそろ帰るか。"

# ダクネス
# えっ！？　い、いいのか？\nまだ来てそんなに経ってないのに？
254 = "えっ！？　い、いいのか？\\nまだ来てそんなに経ってないのに？"

# カズマ
# なんだか、ダクネスが調子悪そうだし、\n帰った方が良いのかなと思ってさ。
288 = "なんだか、ダクネスが調子悪そうだし、\\n帰った方が良いのかなと思ってさ。"

# ダクネス
# き、きき、気遣いは無用だ！\nす、少し耐えてたら、なんとかなる。
260 = "き、きき、気遣いは無用だ！\\nす、少し耐えてたら、なんとかなる。"

# カズマ
# そうか？　でも、少しでも辛いって感じたら\n言うんだぞ？
269 = "そうか？　でも、少しでも辛いって感じたら\\n言うんだぞ？"

# ダクネス
# いっ、言わせるのか！？
251 = "いっ、言わせるのか！？"

# カズマ（Ｍ）
# display as カズマ
# （え？）
371 = "（え？）"

# ダクネス
# ふふ、ふふふ、さすがカズマ、容赦ないな。
293 = "ふふ、ふふふ、さすがカズマ、容赦ないな。"

# カズマ（Ｍ）
# display as カズマ
# （ぶれねー）
378 = "（ぶれねー）"

# カズマ（Ｍ）
# display as カズマ
# （放っておこう。\n　子供じゃ無いんだし、トイレに行きたきゃ\n　自分で行くだろう）
386 = "（放っておこう。\\n　子供じゃ無いんだし、トイレに行きたきゃ\\n　自分で行くだろう）"

# ダクネス
# うぅ、うぅぅぅ～～！！
253 = "うぅ、うぅぅぅ～～！！"

# カズマ
# …………。
243 = "…………。"

# ダクネス
# くぅっ！　くぅぅぅぅ～～～～！！
261 = "くぅっ！　くぅぅぅぅ～～～～！！"

# カズマ
# な、なあ、ダクネス？
279 = "な、なあ、ダクネス？"

# ダクネス
# な、なんだ？
280 = "な、なんだ？"

# カズマ
# 俺、少し散歩してこようか？
311 = "俺、少し散歩してこようか？"

# ダクネス
# 散歩に？\nどど、どうしてだ？
317 = "散歩に？\\nどど、どうしてだ？"

# カズマ
# 理由を言っていいのか？\nいいんだな？
319 = "理由を言っていいのか？\\nいいんだな？"

# ダクネス
# はうっ！？
291 = "はうっ！？"

# カズマ
# お、おい、どうした？
258 = "お、おい、どうした？"

# ダクネス
# ふぅぅっ……い、今のは危なかった。
292 = "ふぅぅっ……い、今のは危なかった。"

# カズマ
# なぁ、もうバレバレなんだし、\nトイレに行きたいなら行きたいって言えよ。
281 = "なぁ、もうバレバレなんだし、\\nトイレに行きたいなら行きたいって言えよ。"

# ダクネス
# わ、私はクルセイダーだぞ！\nクク、クルセイダーは、ト、トイレには！！\nうくぅぅぅ～～～～！！
301 = "わ、私はクルセイダーだぞ！\\nクク、クルセイダーは、ト、トイレには！！\\nうくぅぅぅ～～～～！！"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、まったく、しょうがねーな）
375 = "（はぁ、まったく、しょうがねーな）"

# カズマ
# よし、ダクネス！\nダッシュで帰るぞ！
299 = "よし、ダクネス！\\nダッシュで帰るぞ！"

# ダクネス
# え？　ええ！？
255 = "え？　ええ！？"

# カズマ
# ほら、早く着替えろ！\n今ならまだ間に合うだろ！
296 = "ほら、早く着替えろ！\\n今ならまだ間に合うだろ！"

# ダクネス
# わ、わかった！
300 = "わ、わかった！"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、どうしてこうなるかな……）
374 = "（はぁ、どうしてこうなるかな……）"

[selections]
298 = "もしかしたらそういうプレイなのか？"
272 = "そろそろ帰ろうと提案しよう"
316 = "放っておこう"
