# rew_e07.txt.scn

[info]
209 = "rew_e07"

[characters]
308 = "ゆんゆん"
317 = "カズマ"
320 = "カズマ（Ｍ）"

[character_subs]
# 317 = "カズマ"

[script]
# lines: 103

# ゆんゆん
# あのぉ、カズマさん。\nお仕置きって何をすればいいんですか？
263 = "あのぉ、カズマさん。\\nお仕置きって何をすればいいんですか？"

# カズマ
# いやぁ、お仕置きなんて多種多様だし、\nそれこそ嫌がることなんて人それぞれだからなぁ。
266 = "いやぁ、お仕置きなんて多種多様だし、\\nそれこそ嫌がることなんて人それぞれだからなぁ。"

# カズマ
# もしかして、何も思いつかないのか？
307 = "もしかして、何も思いつかないのか？"

# ゆんゆん
# 私なりに色々考えてはみたんですけど、\n可哀想なことはしたくないなって。
368 = "私なりに色々考えてはみたんですけど、\\n可哀想なことはしたくないなって。"

# ゆんゆん
# それにせっかくお近づきになれたのに、\n嫌われたりしたらショックですし。
290 = "それにせっかくお近づきになれたのに、\\n嫌われたりしたらショックですし。"

# カズマ
# よし、ひとついいことを教えてやろう。
311 = "よし、ひとついいことを教えてやろう。"

# ゆんゆん
# はい、なんでしょう！
304 = "はい、なんでしょう！"

# カズマ
# アクア、めぐみん、そしてダクネス、あの３人には\nそれはもう散々な目にあわされてきてる。
315 = "アクア、めぐみん、そしてダクネス、あの３人には\\nそれはもう散々な目にあわされてきてる。"

# カズマ
# それでも俺はあいつらといる、なぜだかわかるか？
289 = "それでも俺はあいつらといる、なぜだかわかるか？"

# ゆんゆん
# ええと、お友達だからですよね？
270 = "ええと、お友達だからですよね？"

# カズマ
# それもあるが、仲間だからだ！
291 = "それもあるが、仲間だからだ！"

# ゆんゆん
# 仲間！
321 = "仲間！"

# カズマ
# そして俺は、ゆんゆんを友達以上仲間未満だと\n思ってる！
283 = "そして俺は、ゆんゆんを友達以上仲間未満だと\\n思ってる！"

# ゆんゆん
# と、友達以上！
298 = "と、友達以上！"

# カズマ
# だから、ドンと決めてくれて構わないぞ。\nちょっとのことじゃ嫌ったりしないから。
293 = "だから、ドンと決めてくれて構わないぞ。\\nちょっとのことじゃ嫌ったりしないから。"

# ゆんゆん
# 友達ってすごいですね！
323 = "友達ってすごいですね！"

# カズマ
# え、そう？
269 = "え、そう？"

# ゆんゆん
# だって、何をされても嫌わないんですよね？
295 = "だって、何をされても嫌わないんですよね？"

# ゆんゆん
# 空気を読まずに違う意見を言ったり、\n呼ばれてもいないのに話に入ったり――
369 = "空気を読まずに違う意見を言ったり、\\n呼ばれてもいないのに話に入ったり――"

# ゆんゆん
# 相手の都合も考えずにお誕生日会に誘ったりしても\n嫌わないなんてすごいです！
365 = "相手の都合も考えずにお誕生日会に誘ったりしても\\n嫌わないなんてすごいです！"

# カズマ（Ｍ）
# display as カズマ
# （なんなのこの子の思考……）
385 = "（なんなのこの子の思考……）"

# ゆんゆん
# 私ずっと心配してたんです。\nお仕置きっていうのは冗談で、本当は私を貶める\n罠なんじゃないかって。
367 = "私ずっと心配してたんです。\\nお仕置きっていうのは冗談で、本当は私を貶める\\n罠なんじゃないかって。"

# ゆんゆん
# 実は、どこかからみんな見ていて、\nあの子本当にお仕置きしてる、超うけるんだけどー\nって笑い者になってるんじゃないかって。
328 = "実は、どこかからみんな見ていて、\\nあの子本当にお仕置きしてる、超うけるんだけどー\\nって笑い者になってるんじゃないかって。"

# ゆんゆん
# 笑い物になるなんて嫌だけど、\nみんなが楽しんでるなら、その期待に応えない\nといけないし――
370 = "笑い物になるなんて嫌だけど、\\nみんなが楽しんでるなら、その期待に応えない\\nといけないし――"

# ゆんゆん
# それがみんなの中に居られる条件なら、\n私の嫌な気持ちくらい我慢しなきゃなって。
285 = "それがみんなの中に居られる条件なら、\\n私の嫌な気持ちくらい我慢しなきゃなって。"

# カズマ
# だーーーーー！！\nネガティブにも程があるし、なんかへこむわ！！
296 = "だーーーーー！！\\nネガティブにも程があるし、なんかへこむわ！！"

# ゆんゆん
# ええ！？
271 = "ええ！？"

# カズマ
# あいつらは確かにバカだけど、そんなクズみたいな\nことしないから！　俺も含めて！
260 = "あいつらは確かにバカだけど、そんなクズみたいな\\nことしないから！　俺も含めて！"

# ゆんゆん
# そそ、そうですよね！\nご、ごめんなさい！
284 = "そそ、そうですよね！\\nご、ごめんなさい！"

# カズマ
# はい、気持ちをリセットする！\n深呼吸する！
305 = "はい、気持ちをリセットする！\\n深呼吸する！"

# ゆんゆん
# は、はい！\nすーはー、すーはー。
302 = "は、はい！\\nすーはー、すーはー。"

# カズマ
# というわけで話を戻すぞ。
299 = "というわけで話を戻すぞ。"

# カズマ
# お仕置きって考えるから思いつかないんじゃないか？\n純粋にしてもらいたいことで考えてみろ。
275 = "お仕置きって考えるから思いつかないんじゃないか？\\n純粋にしてもらいたいことで考えてみろ。"

# ゆんゆん
# カズマさんにしてもらいたいこと？
319 = "カズマさんにしてもらいたいこと？"

# カズマ
# 命に関わること以外なら、なんでもいいぞ。\n言うだけならタダなんだから言ってみろ！
326 = "命に関わること以外なら、なんでもいいぞ。\\n言うだけならタダなんだから言ってみろ！"

# ゆんゆん
# そ、それなら、ひとつあるかもです。
281 = "そ、それなら、ひとつあるかもです。"

# カズマ
# おっ、なんだ？
274 = "おっ、なんだ？"

# ゆんゆん
# ひ、膝枕……。
306 = "ひ、膝枕……。"

# カズマ（Ｍ）
# display as カズマ
# （え……？）
377 = "（え……？）"

# ゆんゆん
# 膝枕に興味があるかもです。
373 = "膝枕に興味があるかもです。"

# カズマ
# それってゆんゆんがしてくれるのか？\nだとしたらご褒美でしかない！
288 = "それってゆんゆんがしてくれるのか？\\nだとしたらご褒美でしかない！"

# ゆんゆん
# いいえ、そうじゃなくてですね！\nわ、私がしてもらいたいなって！
265 = "いいえ、そうじゃなくてですね！\\nわ、私がしてもらいたいなって！"

# カズマ（Ｍ）
# display as カズマ
# （どっちにしてもお仕置きではないな）
383 = "（どっちにしてもお仕置きではないな）"

# ゆんゆん
# あのあの、こんなお仕置き嫌ですか？\n嫌ですよね。
262 = "あのあの、こんなお仕置き嫌ですか？\\n嫌ですよね。"

# カズマ
# そんなことないって。
292 = "そんなことないって。"

# ゆんゆん
# では、よろしくお願いします！
297 = "では、よろしくお願いします！"

# カズマ
# 寝心地はどうだ？
329 = "寝心地はどうだ？"

# ゆんゆん
# わ、悪くない……です……。
312 = "わ、悪くない……です……。"

# カズマ
# すげーガチガチだな。\nもしかして緊張してる？
278 = "すげーガチガチだな。\\nもしかして緊張してる？"

# ゆんゆん
# は、はい……。
301 = "は、はい……。"

# カズマ
# だけど、またどうして膝枕なんだよ。
294 = "だけど、またどうして膝枕なんだよ。"

# ゆんゆん
# 膝枕って、仲が良くないとできないじゃないですか。\n憧れるというか、いいなってずっと思ってて。
372 = "膝枕って、仲が良くないとできないじゃないですか。\\n憧れるというか、いいなってずっと思ってて。"

# カズマ（Ｍ）
# display as カズマ
# （言ってることは間違えてないんだけど、\n　少し外れてるよな……）
394 = "（言ってることは間違えてないんだけど、\\n　少し外れてるよな……）"

# ゆんゆん
# あ、あああ、あの、カズマさん？
255 = "あ、あああ、あの、カズマさん？"

# カズマ
# 固いって！　固すぎるよゆんゆん！\nそんなんじゃこのシチュエーションを\nちっとも楽しめないだろ！
327 = "固いって！　固すぎるよゆんゆん！\\nそんなんじゃこのシチュエーションを\\nちっとも楽しめないだろ！"

# ゆんゆん
# すすす、す、すみません。
279 = "すすす、す、すみません。"

# カズマ（Ｍ）
# display as カズマ
# （まるで金縛りだ。\n　微動だにしないし）
386 = "（まるで金縛りだ。\\n　微動だにしないし）"

# カズマ（Ｍ）
# display as カズマ
# （本当にこんなんで満足してくれてるのか？）
390 = "（本当にこんなんで満足してくれてるのか？）"

# ゆんゆん
# カ、カズマさん？
316 = "カ、カズマさん？"

# カズマ
# どうした？
300 = "どうした？"

# ゆんゆん
# い、いえ……なんでもありません。
264 = "い、いえ……なんでもありません。"

# カズマ（Ｍ）
# display as カズマ
# （そういえばさっきも何かを言いかけてたよな）
378 = "（そういえばさっきも何かを言いかけてたよな）"

# カズマ（Ｍ）
# display as カズマ
# （本当は何かして欲しいことがあるんじゃ\n　ないのか？）
391 = "（本当は何かして欲しいことがあるんじゃ\\n　ないのか？）"

# カズマ（Ｍ）
# display as カズマ
# （もしかして、次に何をすべきか、\n　俺は試されているのかもしれない！）
387 = "（もしかして、次に何をすべきか、\\n　俺は試されているのかもしれない！）"

# カズマ（Ｍ）
# display as カズマ
# （考えろ、ゆんゆんが望んでいることはなんだ？\n　はっ、もしかして――）
392 = "（考えろ、ゆんゆんが望んでいることはなんだ？\\n　はっ、もしかして――）"

# カズマ（Ｍ）
# display as カズマ
# （膝枕と言えば耳かきだろ！\n　きっとゆんゆんもそれを\n　待っているに違いない！）
393 = "（膝枕と言えば耳かきだろ！\\n　きっとゆんゆんもそれを\\n　待っているに違いない！）"

# カズマ
# ゆんゆんの言いたいことはよくわかった！\nジッとしていてくれ。
309 = "ゆんゆんの言いたいことはよくわかった！\\nジッとしていてくれ。"

# ゆんゆん
# え？　あ、はい……？
272 = "え？　あ、はい……？"

# カズマ
# それじゃ、お邪魔しますっと。
286 = "それじゃ、お邪魔しますっと。"

# ゆんゆん
# え、ええ！？　み、耳かき？
268 = "え、ええ！？　み、耳かき？"

# カズマ
# して欲しかったんだろ？\nあ、あれ、違ったか？
277 = "して欲しかったんだろ？\\nあ、あれ、違ったか？"

# ゆんゆん
# 違いますけど、気持ちいいからこれでいいです。
375 = "違いますけど、気持ちいいからこれでいいです。"

# カズマ（Ｍ）
# display as カズマ
# （違ったか……。\n　俺の読みもまだまだだな）
395 = "（違ったか……。\\n　俺の読みもまだまだだな）"

# ゆんゆん
# んぅぅ……気持ちいい。\n耳かきをしてもらうなんて久しぶりです。
313 = "んぅぅ……気持ちいい。\\n耳かきをしてもらうなんて久しぶりです。"

# カズマ
# こうなったら徹底的に綺麗にするぞ！
276 = "こうなったら徹底的に綺麗にするぞ！"

# ゆんゆん
# あ、そこいいです。\nカズマさん耳かき上手ですね。
259 = "あ、そこいいです。\\nカズマさん耳かき上手ですね。"

# カズマ
# それじゃこれからは、\nゆんゆんの耳かき担当は俺だな！
287 = "それじゃこれからは、\\nゆんゆんの耳かき担当は俺だな！"

# ゆんゆん
# うふふ、カズマさんたら。
267 = "うふふ、カズマさんたら。"

# カズマ（Ｍ）
# display as カズマ
# （あの目は甘い言葉を待っている目だ！）
376 = "（あの目は甘い言葉を待っている目だ！）"

# カズマ（Ｍ）
# display as カズマ
# （それなら期待に応えてあげないと！）
379 = "（それなら期待に応えてあげないと！）"

# カズマ
# ゆんゆんは可愛いな、年の割に落ち着いてるし、\n大人びてる。
310 = "ゆんゆんは可愛いな、年の割に落ち着いてるし、\\n大人びてる。"

# ゆんゆん
# そ、そんな、私なんか全然。
282 = "そ、そんな、私なんか全然。"

# カズマ
# 全然なんてことないって、\nめぐみんと同じ年とは思えないくらい\nシッカリしてるじゃないか。
322 = "全然なんてことないって、\\nめぐみんと同じ年とは思えないくらい\\nシッカリしてるじゃないか。"

# ゆんゆん
# あ、ありがとうございます。
258 = "あ、ありがとうございます。"

# カズマ
# 礼なんていいって本当のことなんだから。\nそんな素敵な女の子を膝枕できるなんて\n俺は幸せ者だな。
366 = "礼なんていいって本当のことなんだから。\\nそんな素敵な女の子を膝枕できるなんて\\n俺は幸せ者だな。"

# ゆんゆん
# カズマさん。
318 = "カズマさん。"

# カズマ（Ｍ）
# display as カズマ
# （思ったほど甘くないぞ、\n　やっぱり言い慣れてない言葉は\n　出てこないもんだ）
389 = "（思ったほど甘くないぞ、\\n　やっぱり言い慣れてない言葉は\\n　出てこないもんだ）"

# カズマ（Ｍ）
# display as カズマ
# （とりあえずここは、黙って見つめてみよう）
381 = "（とりあえずここは、黙って見つめてみよう）"

# カズマ
# …………。
254 = "…………。"

# ゆんゆん
# …………。
# 254 = "…………。"

# カズマ
# …………。
# 254 = "…………。"

# ゆんゆん
# あ、あの、私の顔に何かついてますか？
257 = "あ、あの、私の顔に何かついてますか？"

# カズマ
# 可愛い目鼻がついてるな。
324 = "可愛い目鼻がついてるな。"

# ゆんゆん
# そ、そうですか。
280 = "そ、そうですか。"

# カズマ（Ｍ）
# display as カズマ
# （どうも違ったみたいだぞ）
382 = "（どうも違ったみたいだぞ）"

# ゆんゆん
# あの、カズマさん。\nひ、ひ、ひとつお願いが。
261 = "あの、カズマさん。\\nひ、ひ、ひとつお願いが。"

# カズマ
# おう、なんだ？
273 = "おう、なんだ？"

# ゆんゆん
# あ、あの……頭を撫でてもらえますか？
256 = "あ、あの……頭を撫でてもらえますか？"

# カズマ（Ｍ）
# display as カズマ
# （なるほど、これが正解だったわけだ）
384 = "（なるほど、これが正解だったわけだ）"

# ゆんゆん
# んぅぅ、大きな手、ほっとします。
314 = "んぅぅ、大きな手、ほっとします。"

# カズマ（Ｍ）
# display as カズマ
# （だけど、やっぱり\n　全然お仕置きじゃないよな、\n　これって）
380 = "（だけど、やっぱり\\n　全然お仕置きじゃないよな、\\n　これって）"

# ゆんゆん
# はぁぁぁ、幸せ。
303 = "はぁぁぁ、幸せ。"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんが喜んでるなら、\n　それでいいか）
388 = "（ゆんゆんが喜んでるなら、\\n　それでいいか）"

[selections]
371 = "耳かきをしよう"
331 = "甘い言葉を囁こう"
374 = "見つめてみよう"
