# rew_b07.txt.scn

[info]
205 = "rew_b07"

[characters]
283 = "めぐみん"
289 = "カズマ"
291 = "カズマ（Ｍ）"

[character_subs]
# 289 = "カズマ"

[script]
# lines: 74

# めぐみん
# それでは今回のお仕置きを発表します。\nカズマには洗濯をしてもらいます。
259 = "それでは今回のお仕置きを発表します。\\nカズマには洗濯をしてもらいます。"

# カズマ
# ただ自分でやるのが面倒なだけだろ？
262 = "ただ自分でやるのが面倒なだけだろ？"

# めぐみん
# だからカズマにお願いするんですよ。
263 = "だからカズマにお願いするんですよ。"

# カズマ
# そう言われると返す言葉もないが、\nまた面倒な……。
256 = "そう言われると返す言葉もないが、\\nまた面倒な……。"

# めぐみん
# お仕置きなんですから面倒なことを\n押しつけるのは当たり前じゃないですか。
249 = "お仕置きなんですから面倒なことを\\n押しつけるのは当たり前じゃないですか。"

# めぐみん
# 簡単で楽なことをやらせても罰になりませんからね。
339 = "簡単で楽なことをやらせても罰になりませんからね。"

# めぐみん
# というわけで、つべこべ言わず始めましょう！
268 = "というわけで、つべこべ言わず始めましょう！"

# カズマ（Ｍ）
# display as カズマ
# （やれやれ……）
341 = "（やれやれ……）"

# めぐみん
# では、これを洗ってください。
266 = "では、これを洗ってください。"

# カズマ
# あれ、思ったより少ないな？
236 = "あれ、思ったより少ないな？"

# めぐみん
# 私は基本的に溜め込んだりせず\nこまめに洗いますからね。
337 = "私は基本的に溜め込んだりせず\\nこまめに洗いますからね。"

# カズマ
# これならあっという間に終わるな。\nこの程度でお仕置きとは、楽勝過ぎるぜ！
251 = "これならあっという間に終わるな。\\nこの程度でお仕置きとは、楽勝過ぎるぜ！"

# めぐみん
# 楽勝なのは結構ですが、\nどれも大切に着ている物なので\n丁寧にお願いしますよ？
302 = "楽勝なのは結構ですが、\\nどれも大切に着ている物なので\\n丁寧にお願いしますよ？"

# カズマ
# わかってるわかってる。\n数も大したことないし超丁寧に手洗いしてやるよ。
288 = "わかってるわかってる。\\n数も大したことないし超丁寧に手洗いしてやるよ。"

# カズマ
# そうだ、ついでだから俺の洗濯物と一緒に洗うか。
255 = "そうだ、ついでだから俺の洗濯物と一緒に洗うか。"

# めぐみん
# それはやめてください！
261 = "それはやめてください！"

# カズマ
# どうしてだよ。\n一緒に洗った方が効率がいいだろ？
269 = "どうしてだよ。\\n一緒に洗った方が効率がいいだろ？"

# めぐみん
# なんかバッチィじゃないですか。
275 = "なんかバッチィじゃないですか。"

# カズマ
# 確かに汚れ物だけど、そんなバイ菌みたいに\n言わないでくれよ！
336 = "確かに汚れ物だけど、そんなバイ菌みたいに\\n言わないでくれよ！"

# めぐみん
# カズマには申し訳ないのですが、\n生理的に無理です。
290 = "カズマには申し訳ないのですが、\\n生理的に無理です。"

# カズマ
# 生理的……\nもっともどうしようもなく、\nもっとも地味に傷つく言葉を……。
303 = "生理的……\\nもっともどうしようもなく、\\nもっとも地味に傷つく言葉を……。"

# めぐみん
# 仕方がないじゃないですか、\n嫌なものは嫌なんですから。
295 = "仕方がないじゃないですか、\\n嫌なものは嫌なんですから。"

# カズマ（Ｍ）
# display as カズマ
# （年頃の娘をもった父親の気持ちを\n　今理解したよ）
343 = "（年頃の娘をもった父親の気持ちを\\n　今理解したよ）"

# カズマ
# はぁ～、落ち込んでても仕方がない、\n始めるか。
278 = "はぁ～、落ち込んでても仕方がない、\\n始めるか。"

# カズマ
# なかなか泡立ちがいいな、これならしつこい汚れも\nばっちり取れそうだ。
273 = "なかなか泡立ちがいいな、これならしつこい汚れも\\nばっちり取れそうだ。"

# めぐみん
# 失礼な、カズマじゃないんですから\nそんなに汚れていませんよ。
300 = "失礼な、カズマじゃないんですから\\nそんなに汚れていませんよ。"

# カズマ
# どっちが失礼だよ。
270 = "どっちが失礼だよ。"

# めぐみん
# もっと丁寧に洗ってください。\n生地が傷んでしまうじゃありませんか。
287 = "もっと丁寧に洗ってください。\\n生地が傷んでしまうじゃありませんか。"

# カズマ（Ｍ）
# display as カズマ
# （丁寧にね……はいはい）
342 = "（丁寧にね……はいはい）"

# めぐみん
# そこは揉み洗いにしてください。
257 = "そこは揉み洗いにしてください。"

# カズマ（Ｍ）
# display as カズマ
# （注文が多いやつだな）
345 = "（注文が多いやつだな）"

# めぐみん
# あー、もう、洗剤を入れすぎです！\n無駄に入れれば綺麗になるというものでは\nありません。大切なのは適量です。
237 = "あー、もう、洗剤を入れすぎです！\\n無駄に入れれば綺麗になるというものでは\\nありません。大切なのは適量です。"

# カズマ
# …………。
231 = "…………。"

# めぐみん
# あ……。
232 = "あ……。"

# カズマ
# はぁ、今度はなんだよ。
277 = "はぁ、今度はなんだよ。"

# めぐみん
# あ、あの、今日はそこまででいいですよ。\nお疲れ様でした。
234 = "あ、あの、今日はそこまででいいですよ。\\nお疲れ様でした。"

# カズマ
# まだ洗い物は残ってるぞ？
282 = "まだ洗い物は残ってるぞ？"

# めぐみん
# ですから残りは私がやります。
265 = "ですから残りは私がやります。"

# カズマ
# いいって、ここまできたら最後までやるって。
238 = "いいって、ここまできたら最後までやるって。"

# めぐみん
# いえいえ、お気づかい結構です！
241 = "いえいえ、お気づかい結構です！"

# カズマ
# おい、めぐみん。\n何を慌ててるんだ？
248 = "おい、めぐみん。\\n何を慌ててるんだ？"

# めぐみん
# ななな、なんのことです？\nべ、べべ、別に慌ててなどいませんが？？
274 = "ななな、なんのことです？\\nべ、べべ、別に慌ててなどいませんが？？"

# カズマ
# いや、明らかに慌ててるし、動揺してるだろ。
243 = "いや、明らかに慌ててるし、動揺してるだろ。"

# めぐみん
# と、とにかくもういいですよ！\nしつこい男は嫌われますよ！
267 = "と、とにかくもういいですよ！\\nしつこい男は嫌われますよ！"

# カズマ（Ｍ）
# display as カズマ
# （急にどうしたんだ？\n　このまま続けられたら何か\n　都合の悪いことでも――）
344 = "（急にどうしたんだ？\\n　このまま続けられたら何か\\n　都合の悪いことでも――）"

# カズマ（Ｍ）
# display as カズマ
# （って、ああ、なるほど。\n　めぐみんが慌ててる理由はこれか）
340 = "（って、ああ、なるほど。\\n　めぐみんが慌ててる理由はこれか）"

# めぐみん
# さあさあ、カズマは部屋に戻って\nゆっくりしていてください。
253 = "さあさあ、カズマは部屋に戻って\\nゆっくりしていてください。"

# カズマ
# あはははは、何を恥ずかしがっているんだ。\n俺とめぐみんの仲じゃないか、\nパンツぐらい洗ってやるよ。
235 = "あはははは、何を恥ずかしがっているんだ。\\n俺とめぐみんの仲じゃないか、\\nパンツぐらい洗ってやるよ。"

# めぐみん
# いやーーーーーーーーー！！\nやめてください！　お願いですから！
244 = "いやーーーーーーーーー！！\\nやめてください！　お願いですから！"

# カズマ
# 俺としてもお仕置きを途中で\n放り出すのは忍びないし、\nこれまで以上に丁寧に洗ってやるからな！
296 = "俺としてもお仕置きを途中で\\n放り出すのは忍びないし、\\nこれまで以上に丁寧に洗ってやるからな！"

# めぐみん
# いいですから！\nそんな見え透いたやる気を出さなくて\nいいですから！
239 = "いいですから！\\nそんな見え透いたやる気を出さなくて\\nいいですから！"

# カズマ
# うん、それにしても――
247 = "うん、それにしても――"

# カズマ
# ふむふむ、なるほどなるほど。
280 = "ふむふむ、なるほどなるほど。"

# めぐみん
# な、なんですか！\n感じ悪いですね。
271 = "な、なんですか！\\n感じ悪いですね。"

# カズマ
# いや、このパンツを！
242 = "いや、このパンツを！"

# めぐみん
# ひう！？
279 = "ひう！？"

# カズマ
# めぐみんが！
284 = "めぐみんが！"

# めぐみん
# うぅ！
245 = "うぅ！"

# カズマ
# 穿いてたんだなーって思ってさ。
338 = "穿いてたんだなーって思ってさ。"

# めぐみん
# 交互に見ないでください！\n恥ずかしくて死にそうです！
294 = "交互に見ないでください！\\n恥ずかしくて死にそうです！"

# カズマ
# 大丈夫大丈夫、\n恥ずかしさで人は死なないから。
299 = "大丈夫大丈夫、\\n恥ずかしさで人は死なないから。"

# カズマ
# なかなかいい生地を使ったパンツだな。\n高かったんじゃないかこれ？
272 = "なかなかいい生地を使ったパンツだな。\\n高かったんじゃないかこれ？"

# カズマ
# 刺繍も細かいし、相当奮発しただろ。
297 = "刺繍も細かいし、相当奮発しただろ。"

# めぐみん
# あ、あの、パンツを褒められても\n微妙な気持ちになるだけなんですが。
233 = "あ、あの、パンツを褒められても\\n微妙な気持ちになるだけなんですが。"

# カズマ
# これは気を使って洗わないといけないな！
252 = "これは気を使って洗わないといけないな！"

# めぐみん
# ちょぉぉお！！　撫でないでくださいよ！
264 = "ちょぉぉお！！　撫でないでくださいよ！"

# カズマ
# 丁寧に洗えって言ったのはめぐみんだろ。
293 = "丁寧に洗えって言ったのはめぐみんだろ。"

# カズマ
# ほーら、すーりすーり。
281 = "ほーら、すーりすーり。"

# カズマ
# めぐみんにピッタリのパンツじゃないか。
285 = "めぐみんにピッタリのパンツじゃないか。"

# めぐみん
# そ、そうですか？\n私としては、ちょっと大人っぽいかなと\n思っているのですが。
254 = "そ、そうですか？\\n私としては、ちょっと大人っぽいかなと\\n思っているのですが。"

# カズマ
# それだけの魅力を、\nめぐみんはもう持っていると思うぞ！
258 = "それだけの魅力を、\\nめぐみんはもう持っていると思うぞ！"

# めぐみん
# はぁ、そのさわやかな笑顔も、\nパンツを握っていては台無しですよ。
276 = "はぁ、そのさわやかな笑顔も、\\nパンツを握っていては台無しですよ。"

# カズマ
# このセクシーなパンツも\n俺がしっかりじっくり洗っておくから、\nめぐみんは部屋でくつろいでいてくれ。
250 = "このセクシーなパンツも\\n俺がしっかりじっくり洗っておくから、\\nめぐみんは部屋でくつろいでいてくれ。"

# めぐみん
# うぅ～～～！！\nこれではどっちが\nお仕置きされてるのかわかりません。
246 = "うぅ～～～！！\\nこれではどっちが\\nお仕置きされてるのかわかりません。"

[selections]
292 = "パンツとめぐみんを交互に見よう"
240 = "いい生地だと褒めてやろう"
286 = "めぐみんに似合うと褒めてあげよう"
