# rew_a01.txt.scn

[info]
182 = "rew_a01"

[characters]
258 = "アクア"
259 = "カズマ"
260 = "カズマ（Ｍ）"

[character_subs]
# 259 = "カズマ"

[script]
# lines: 64

# アクア
# じゃあカズマ、うつぶせになって。
229 = "じゃあカズマ、うつぶせになって。"

# カズマ
# なんでだよ。
238 = "なんでだよ。"

# アクア
# なんでって、私からご褒美が欲しいって言ったのは\nカズマじゃない。
239 = "なんでって、私からご褒美が欲しいって言ったのは\\nカズマじゃない。"

# カズマ（Ｍ）
# display as カズマ
# （それはそうだが、なんでうつぶせに……）
285 = "（それはそうだが、なんでうつぶせに……）"

# アクア
# 悪いようにはしないから。\nほーら、早く！
270 = "悪いようにはしないから。\\nほーら、早く！"

# カズマ
# せめて何をするつもりなのか教えてくれ。
230 = "せめて何をするつもりなのか教えてくれ。"

# アクア
# あら、知りたい？　知りたいの？\n興味津々だったりしちゃうわけ？？
211 = "あら、知りたい？　知りたいの？\\n興味津々だったりしちゃうわけ？？"

# カズマ
# いいから言えよ！
213 = "いいから言えよ！"

# アクア
# ふふーん、このアクア様が考えに考え抜いた\nご褒美はズバリ、足踏みマッサージよ！
244 = "ふふーん、このアクア様が考えに考え抜いた\\nご褒美はズバリ、足踏みマッサージよ！"

# アクア
# どう？　嬉しいでしょ？　嬉しいわよね？
237 = "どう？　嬉しいでしょ？　嬉しいわよね？"

# カズマ（Ｍ）
# display as カズマ
# （確かに、マッサージをしてくれるのは\n　嬉しいのだが……）
288 = "（確かに、マッサージをしてくれるのは\\n　嬉しいのだが……）"

# カズマ
# 他意は無いんだよな？
262 = "他意は無いんだよな？"

# アクア
# 他意って例えば？
261 = "他意って例えば？"

# カズマ
# いや、無いならいいんだ。\nじゃあ、よろしく頼む。
215 = "いや、無いならいいんだ。\\nじゃあ、よろしく頼む。"

# アクア
# 任されたわ、ご主人様！
263 = "任されたわ、ご主人様！"

# カズマ
# ご、ご主人！？\nって、う……おっ、ぐっ……がっ！
228 = "ご、ご主人！？\\nって、う……おっ、ぐっ……がっ！"

# アクア
# もしかして痛かった？
250 = "もしかして痛かった？"

# カズマ
# いや、痛くは無いけど。\nお前、結構重いんだな。
216 = "いや、痛くは無いけど。\\nお前、結構重いんだな。"

# アクア
# 何よそれー。\n私の体は羽毛より軽いのよ！
264 = "何よそれー。\\n私の体は羽毛より軽いのよ！"

# カズマ
# はいはい、そうだな。
243 = "はいはい、そうだな。"

# アクア
# ええと、どこか踏んで欲しいところはある？\nご主人様？
222 = "ええと、どこか踏んで欲しいところはある？\\nご主人様？"

# カズマ
# おい、ちょっと待て。\nさっきからご主人様ってなんなんだ。\nそれにどうしてメイド服なんて着てる。
225 = "おい、ちょっと待て。\\nさっきからご主人様ってなんなんだ。\\nそれにどうしてメイド服なんて着てる。"

# アクア
# だってカズマ、こういうの好きでしょ？
234 = "だってカズマ、こういうの好きでしょ？"

# カズマ
# ……そりゃメイド服は好きだけど、\nお前に言われると何か無性に腹が立つな。
209 = "……そりゃメイド服は好きだけど、\\nお前に言われると何か無性に腹が立つな。"

# アクア
# そんなこと言って～。\n本当は嬉しいでしょ？　素直になりなさいよ。
233 = "そんなこと言って～。\\n本当は嬉しいでしょ？　素直になりなさいよ。"

# カズマ
# 俺の上にいるのが\nエリス様だったら良かったんだけどな。
265 = "俺の上にいるのが\\nエリス様だったら良かったんだけどな。"

# アクア
# こいつ、背骨をへし折ってやろうかしら。
227 = "こいつ、背骨をへし折ってやろうかしら。"

# カズマ
# いたたたた！\nやめろっ、マジで折れるから！
214 = "いたたたた！\\nやめろっ、マジで折れるから！"

# アクア
# うふ、嬉しいわよね？
218 = "うふ、嬉しいわよね？"

# カズマ
# 嬉しい、嬉しい！\nめちゃくちゃ嬉しいから！
268 = "嬉しい、嬉しい！\\nめちゃくちゃ嬉しいから！"

# アクア
# うんうん、そうよね。
220 = "うんうん、そうよね。"

# アクア
# んっ……んん、ふんっ……んっ。
257 = "んっ……んん、ふんっ……んっ。"

# アクア
# ふんっ……ん～～、んっ、んん～……ふふん～ふん。
245 = "ふんっ……ん～～、んっ、んん～……ふふん～ふん。"

# カズマ（Ｍ）
# display as カズマ
# （なんかノリノリになってきたな）
286 = "（なんかノリノリになってきたな）"

# アクア
# ふんっふふ～ん、たりらりら～ん♪
246 = "ふんっふふ～ん、たりらりら～ん♪"

# カズマ
# てか、お前！　人の上で踊るな！\n下手したら頭にっ、うぐおっ！
235 = "てか、お前！　人の上で踊るな！\\n下手したら頭にっ、うぐおっ！"

# アクア
# あ、ごめんね。\nわざとじゃないのよ、わざとじゃ。
210 = "あ、ごめんね。\\nわざとじゃないのよ、わざとじゃ。"

# カズマ（Ｍ）
# display as カズマ
# （こいつ言ってる側からっ！）
284 = "（こいつ言ってる側からっ！）"

# カズマ
# わかったから頭から足をどかせ！
255 = "わかったから頭から足をどかせ！"

# アクア
# ねえ、もしかして怒った？
240 = "ねえ、もしかして怒った？"

# カズマ
# わざとじゃないんだろ？
256 = "わざとじゃないんだろ？"

# カズマ
# 別に怒って……ってなんだよ、その顔は。
266 = "別に怒って……ってなんだよ、その顔は。"

# アクア
# えー、なんのことー？
224 = "えー、なんのことー？"

# カズマ（Ｍ）
# display as カズマ
# （こいつ、さてはわざとやったな……）
283 = "（こいつ、さてはわざとやったな……）"

# アクア
# それよりも、感想とか感謝の言葉とか\n何もないわけ？
232 = "それよりも、感想とか感謝の言葉とか\\n何もないわけ？"

# カズマ
# もういいよ。ちょっと雑になってきてるぞ、\n痛いっつーの。
249 = "もういいよ。ちょっと雑になってきてるぞ、\\n痛いっつーの。"

# アクア
# ええっ？\n何よ、やっと調子が出てきたところなのに。
221 = "ええっ？\\n何よ、やっと調子が出てきたところなのに。"

# カズマ
# 調子の波があるマッサージってなんだ。\nだいたい、頭を踏むなよ、頭を！
282 = "調子の波があるマッサージってなんだ。\\nだいたい、頭を踏むなよ、頭を！"

# アクア
# あら、踏まれて気持ち良かったんじゃないの？
212 = "あら、踏まれて気持ち良かったんじゃないの？"

# カズマ
# 誰もそんなこと言ってない！
281 = "誰もそんなこと言ってない！"

# カズマ
# もっと優しくやってくれないか。
253 = "もっと優しくやってくれないか。"

# アクア
# ……あんたにはこれぐらいがちょうどいいんじゃ\nないの？
208 = "……あんたにはこれぐらいがちょうどいいんじゃ\\nないの？"

# カズマ
# どういう基準だよ！　だいたい鼻歌歌い出して、\n雑さ加減全開じゃねーか！
236 = "どういう基準だよ！　だいたい鼻歌歌い出して、\\n雑さ加減全開じゃねーか！"

# アクア
# そ、それは、こうほら、\nリズムに乗るといいじゃない？　ステップとか。
231 = "そ、それは、こうほら、\\nリズムに乗るといいじゃない？　ステップとか。"

# カズマ
# お前がやってるのはダンスか何かかーーーー！
226 = "お前がやってるのはダンスか何かかーーーー！"

# カズマ
# 素晴らしいご褒美だ！\nいいぞ、もっとやってくれ！
280 = "素晴らしいご褒美だ！\\nいいぞ、もっとやってくれ！"

# アクア
# もっとって、こう？
251 = "もっとって、こう？"

# カズマ
# うがっ！　違うっ！\n頭じゃねーよ！
217 = "うがっ！　違うっ！\\n頭じゃねーよ！"

# アクア
# えー、じゃあどこを踏みつけて欲しいのよ。
223 = "えー、じゃあどこを踏みつけて欲しいのよ。"

# カズマ
# まず、踏みつけるって表現をやめろ！
247 = "まず、踏みつけるって表現をやめろ！"

# アクア
# も～、注文多すぎっ！\nこの私が、こんな素晴らしいマッサージをして\nあげてるのに！
254 = "も～、注文多すぎっ！\\nこの私が、こんな素晴らしいマッサージをして\\nあげてるのに！"

# カズマ
# はぁ、もういいから下りてくれ。
242 = "はぁ、もういいから下りてくれ。"

# アクア
# ねえねえ、カズマ。\nこれで一儲けできそうな気がしない？
241 = "ねえねえ、カズマ。\\nこれで一儲けできそうな気がしない？"

# カズマ（Ｍ）
# display as カズマ
# （ふむ、コスプレマッサージ屋か。\n　確かに……ありかもしれないな）
287 = "（ふむ、コスプレマッサージ屋か。\\n　確かに……ありかもしれないな）"

[selections]
248 = "もういいよ"
252 = "もっと優しくやってくれないか"
219 = "うむ、素晴らしいご褒美だ！"
