# rew_e03.txt.scn

[info]
266 = "rew_e03"

[characters]
413 = "ゆんゆん"
422 = "カズマ"
423 = "カズマ（Ｍ）"
410 = "めぐみん"

[character_subs]
# 422 = "カズマ"

[script]
# lines: 139

# ゆんゆん
# あ、あの、着替えてきましたが、\nこんな格好で何を……。
324 = "あ、あの、着替えてきましたが、\\nこんな格好で何を……。"

# カズマ
# 俺だけのアイドルになってくれ！
429 = "俺だけのアイドルになってくれ！"

# ゆんゆん
# え、え～と……。\nすみません、もう少し詳しく説明をして\nいただけると。
349 = "え、え～と……。\\nすみません、もう少し詳しく説明をして\\nいただけると。"

# カズマ
# 俺のために歌って踊って、握手して、\nそして少しだけセクシーなポーズを\nとって欲しいんだ。
430 = "俺のために歌って踊って、握手して、\\nそして少しだけセクシーなポーズを\\nとって欲しいんだ。"

# ゆんゆん
# 握手はいいですけど、歌も踊りも得意じゃ。
437 = "握手はいいですけど、歌も踊りも得意じゃ。"

# カズマ
# それじゃセクシーなポーズは？！
375 = "それじゃセクシーなポーズは？！"

# ゆんゆん
# そ、それって、エ、エッチなポーズのことですか？
370 = "そ、それって、エ、エッチなポーズのことですか？"

# カズマ
# エッチじゃなくてセクシーだよ。
421 = "エッチじゃなくてセクシーだよ。"

# ゆんゆん
# ち、違いがわかりません！\n無理です！　絶対に無理です。\nそんなことをしたらお嫁に行けなくなります。
380 = "ち、違いがわかりません！\\n無理です！　絶対に無理です。\\nそんなことをしたらお嫁に行けなくなります。"

# カズマ
# そうか、さすがにゆんゆんの将来に\n不安を残すことはできないな。\nならセクシーはなしで。
372 = "そうか、さすがにゆんゆんの将来に\\n不安を残すことはできないな。\\nならセクシーはなしで。"

# ゆんゆん
# え、本当にいいんですか？
352 = "え、本当にいいんですか？"

# カズマ
# なんだ、やっぱりしたいのか？
398 = "なんだ、やっぱりしたいのか？"

# ゆんゆん
# そ、そうではなくてですね。
369 = "そ、そうではなくてですね。"

# ゆんゆん
# これはカズマさんへのご褒美なんですから、\n私のわがままを聞いて貰うのはちょっと違う\nかなって。
366 = "これはカズマさんへのご褒美なんですから、\\n私のわがままを聞いて貰うのはちょっと違う\\nかなって。"

# カズマ
# まあそうだけどさ。\n嫌がる女の子に無理強いさせて喜ぶような\n鬼畜じゃないぞ、俺は。
407 = "まあそうだけどさ。\\n嫌がる女の子に無理強いさせて喜ぶような\\n鬼畜じゃないぞ、俺は。"

# ゆんゆん
# でも……めぐみんはカズマさんのことを、\n鬼畜でどうしようもないダメ男だと……。
392 = "でも……めぐみんはカズマさんのことを、\\n鬼畜でどうしようもないダメ男だと……。"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんは、あとで説教だな！）
498 = "（めぐみんは、あとで説教だな！）"

# カズマ
# まっ、セクシーは無しでいいよ。\nせっかくのご褒美なのに、ゆんゆんの嫌そうな顔\nなんて見たくないし。
408 = "まっ、セクシーは無しでいいよ。\\nせっかくのご褒美なのに、ゆんゆんの嫌そうな顔\\nなんて見たくないし。"

# ゆんゆん
# すみません……でも、ありがとうございます。
368 = "すみません……でも、ありがとうございます。"

# カズマ
# 別にいいって。\nあっ、嫌なら歌も踊りもいいからな。
432 = "別にいいって。\\nあっ、嫌なら歌も踊りもいいからな。"

# ゆんゆん
# で、でもそれじゃ、この服を着ている意味が\nないのでは。
388 = "で、でもそれじゃ、この服を着ている意味が\\nないのでは。"

# カズマ
# 確かにそれはそうなんだけど。
474 = "確かにそれはそうなんだけど。"

# ゆんゆん
# アイドルっぽいことをしている私を見るのが、\nカズマさんへのご褒美なんですよね？
419 = "アイドルっぽいことをしている私を見るのが、\\nカズマさんへのご褒美なんですよね？"

# カズマ
# あー、うーん、それは確かに見たいんだけど。
338 = "あー、うーん、それは確かに見たいんだけど。"

# ゆんゆん
# だけど？
377 = "だけど？"

# カズマ
# ぶっちゃけ、ゆんゆんを独占したいっていうのが\n本音の部分なんだよ。
405 = "ぶっちゃけ、ゆんゆんを独占したいっていうのが\\n本音の部分なんだよ。"

# ゆんゆん
# ど、独占ですか！？
394 = "ど、独占ですか！？"

# カズマ
# そう、可愛いゆんゆんを独占したい！\n願わくば、俺だけのアイドルになってもらいたい！
371 = "そう、可愛いゆんゆんを独占したい！\\n願わくば、俺だけのアイドルになってもらいたい！"

# カズマ
# あはは、男ってバカだろ？
337 = "あはは、男ってバカだろ？"

# ゆんゆん
# っ……わ、わかりました！
383 = "っ……わ、わかりました！"

# カズマ
# え、何が？
351 = "え、何が？"

# ゆんゆん
# あの、歌は本当に苦手でして、\nお聞かせしてもカズマさんを不快にさせるだけだと\n思うんです！
335 = "あの、歌は本当に苦手でして、\\nお聞かせしてもカズマさんを不快にさせるだけだと\\n思うんです！"

# カズマ（Ｍ）
# display as カズマ
# （それは逆に聞いてみたいけど）
487 = "（それは逆に聞いてみたいけど）"

# ゆんゆん
# ですが、踊りはなんとかなると思いますので、\nが、頑張らせていただきます！
390 = "ですが、踊りはなんとかなると思いますので、\\nが、頑張らせていただきます！"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、ゆんゆんは本当にいい子だなぁ）
495 = "（はぁ、ゆんゆんは本当にいい子だなぁ）"

# ゆんゆん
# あっ、ですが、あまり期待しないでくださいね。
332 = "あっ、ですが、あまり期待しないでくださいね。"

# カズマ
# 俺だけのアイドルになってくれる。\nそれだけで充分だよ。
428 = "俺だけのアイドルになってくれる。\\nそれだけで充分だよ。"

# ゆんゆん
# で、では、踊らせていただきます！
386 = "で、では、踊らせていただきます！"

# ゆんゆん
# えい！　とぅ！　やぁぁ！
353 = "えい！　とぅ！　やぁぁ！"

# カズマ（Ｍ）
# display as カズマ
# （こ、これは……微妙だ！）
479 = "（こ、これは……微妙だ！）"

# カズマ（Ｍ）
# display as カズマ
# （ずば抜けて下手って程じゃないけど、\n　お世辞にも上手いとは言えない）
485 = "（ずば抜けて下手って程じゃないけど、\\n　お世辞にも上手いとは言えない）"

# カズマ（Ｍ）
# display as カズマ
# （だけど一生懸命に踊ってくれている。\n　これって俺のためなんだよな。\n　そう考えると嬉しいよな）
488 = "（だけど一生懸命に踊ってくれている。\\n　これって俺のためなんだよな。\\n　そう考えると嬉しいよな）"

# ゆんゆん
# え、えーい！　てや！
348 = "え、えーい！　てや！"

# カズマ（Ｍ）
# display as カズマ
# （しかしこの声はどうにかならないのか……）
482 = "（しかしこの声はどうにかならないのか……）"

# ゆんゆん
# う、うわ！\nあっ……足がもつれて……！
342 = "う、うわ！\\nあっ……足がもつれて……！"

# カズマ
# ってっ、危な！
385 = "ってっ、危な！"

# ゆんゆん
# きゃぁぁぁぁぁぁぁっ！
363 = "きゃぁぁぁぁぁぁぁっ！"

# カズマ（Ｍ）
# display as カズマ
# （間に合え！！）
503 = "（間に合え！！）"

# カズマ
# 痛たたたた……だ、大丈夫か、ゆんゆん？
439 = "痛たたたた……だ、大丈夫か、ゆんゆん？"

# ゆんゆん
# は、はい、おかげさまで。
401 = "は、はい、おかげさまで。"

# カズマ
# …………。
322 = "…………。"

# ゆんゆん
# あの、カズマさん？
334 = "あの、カズマさん？"

# カズマ（Ｍ）
# display as カズマ
# （どうしてこんな体勢になった！？）
492 = "（どうしてこんな体勢になった！？）"

# ゆんゆん
# も、もしかして頭を打っちゃいましたか？\nわわわわ、どうしよう！！
411 = "も、もしかして頭を打っちゃいましたか？\\nわわわわ、どうしよう！！"

# ゆんゆん
# え、えっと、めぐみん！　じゃ、ダメだよね。\nじゃあアクアさん？？
347 = "え、えっと、めぐみん！　じゃ、ダメだよね。\\nじゃあアクアさん？？"

# カズマ
# ちょっとストップ！\n大丈夫だから落ちつけ！
381 = "ちょっとストップ！\\n大丈夫だから落ちつけ！"

# ゆんゆん
# はぁ、よかったです。\n何も喋ってくれないから死んじゃったのかなって\n心配になりましたよ。
402 = "はぁ、よかったです。\\n何も喋ってくれないから死んじゃったのかなって\\n心配になりましたよ。"

# カズマ
# これくらいで死んだりしないって。
364 = "これくらいで死んだりしないって。"

# ゆんゆん
# そうですよね。
374 = "そうですよね。"

# カズマ（Ｍ）
# display as カズマ
# （しかし絶景絶景。\n　この見えそうで見えないところがまたいい！！）
483 = "（しかし絶景絶景。\\n　この見えそうで見えないところがまたいい！！）"

# ゆんゆん
# あっ、ごめんなさい！\nすぐにどきますから！
331 = "あっ、ごめんなさい！\\nすぐにどきますから！"

# カズマ
# ちょっと待った！
382 = "ちょっと待った！"

# ゆんゆん
# え？　え？
356 = "え？　え？"

# カズマ（Ｍ）
# display as カズマ
# （こんな美味しいシチュエーションを\n　簡単に手放してたまるか！）
480 = "（こんな美味しいシチュエーションを\\n　簡単に手放してたまるか！）"

# ゆんゆん
# あの、あの、重いですよね？
333 = "あの、あの、重いですよね？"

# カズマ
# いや、まるで羽毛が乗っているようだよ。
341 = "いや、まるで羽毛が乗っているようだよ。"

# ゆんゆん
# は、はあ……。
400 = "は、はあ……。"

# カズマ
# とにかくすぐ動くのはダメ！\nゆんゆん、足を挫いてるかもしれないだろ？
393 = "とにかくすぐ動くのはダメ！\\nゆんゆん、足を挫いてるかもしれないだろ？"

# ゆんゆん
# いえ、痛みはありませんから――
340 = "いえ、痛みはありませんから――"

# カズマ
# 今無理に動いたら、\nあとで腫れてくるかもしれないぞ！
426 = "今無理に動いたら、\\nあとで腫れてくるかもしれないぞ！"

# ゆんゆん
# あう、それは嫌かもです。
326 = "あう、それは嫌かもです。"

# カズマ
# だったら、このまましばらくジッとしてる！\n体勢キープ！　オッケー？
378 = "だったら、このまましばらくジッとしてる！\\n体勢キープ！　オッケー？"

# ゆんゆん
# お、おっけー、です。
360 = "お、おっけー、です。"

# カズマ（Ｍ）
# display as カズマ
# （さって、この状況をどう楽しませて貰おうかな）
481 = "（さって、この状況をどう楽しませて貰おうかな）"

# カズマ（Ｍ）
# display as カズマ
# （まずは、絶妙な仕事をしてるスカートを\n　なんとかするべきか？）
497 = "（まずは、絶妙な仕事をしてるスカートを\\n　なんとかするべきか？）"

# ゆんゆん
# ふふ、やっぱりカズマさんは優しいですね。
403 = "ふふ、やっぱりカズマさんは優しいですね。"

# カズマ
# え、なんでだ？
350 = "え、なんでだ？"

# ゆんゆん
# だってカズマさんだって体を打ってるはずなのに\n私のことを心配してくれてるんですもん。
379 = "だってカズマさんだって体を打ってるはずなのに\\n私のことを心配してくれてるんですもん。"

# カズマ（Ｍ）
# display as カズマ
# （何、この子！\n　なんでこんな真っ白なの！）
501 = "（何、この子！\\n　なんでこんな真っ白なの！）"

# ゆんゆん
# あっ、お腹の上は苦しいですよね！\nちょっと動きますから――
330 = "あっ、お腹の上は苦しいですよね！\\nちょっと動きますから――"

# カズマ
# って、ダメーーーー！！
384 = "って、ダメーーーー！！"

# ゆんゆん
# え？　え？？
358 = "え？　え？？"

# カズマ（Ｍ）
# display as カズマ
# （動いたら見えちゃうから！\n　もう、無防備すぎる！！）
502 = "（動いたら見えちゃうから！\\n　もう、無防備すぎる！！）"

# ゆんゆん
# お腹、苦しくないんですか？
361 = "お腹、苦しくないんですか？"

# カズマ
# これくらい平気！\n普段の怠惰で腹に贅肉蓄えてるから！
365 = "これくらい平気！\\n普段の怠惰で腹に贅肉蓄えてるから！"

# ゆんゆん
# ふふ、少しは運動をした方がいいですよ？
404 = "ふふ、少しは運動をした方がいいですよ？"

# カズマ（Ｍ）
# display as カズマ
# （いかん、スカートをどうにかしようとしてた\n　自分がすっごく汚い人間に思えてきた！）
476 = "（いかん、スカートをどうにかしようとしてた\\n　自分がすっごく汚い人間に思えてきた！）"

# ゆんゆん
# あのぉ、本当に重くありませんか？\nやっぱり少し動いた方が。
336 = "あのぉ、本当に重くありませんか？\\nやっぱり少し動いた方が。"

# カズマ（Ｍ）
# display as カズマ
# （そ、そうなんだよ。\n　実際みぞおちに座られてるから、\n　かなり苦しくて……）
486 = "（そ、そうなんだよ。\\n　実際みぞおちに座られてるから、\\n　かなり苦しくて……）"

# カズマ（Ｍ）
# display as カズマ
# （でも、今動いたら、間違いなく見えちまう！）
491 = "（でも、今動いたら、間違いなく見えちまう！）"

# カズマ（Ｍ）
# display as カズマ
# （じゃあ、そう指摘するか？\n　いや、それは駄目なような気がする！）
484 = "（じゃあ、そう指摘するか？\\n　いや、それは駄目なような気がする！）"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんにゴミを見るような目をされたら、\n　３日は立ち直れないかもしれない！）
500 = "（ゆんゆんにゴミを見るような目をされたら、\\n　３日は立ち直れないかもしれない！）"

# カズマ（Ｍ）
# display as カズマ
# （くっそ、どうしたらいいんだ！）
478 = "（くっそ、どうしたらいいんだ！）"

# ゆんゆん
# よいっしょ。
416 = "よいっしょ。"

# カズマ（Ｍ）
# display as カズマ
# （って、動くなーーーー！！）
490 = "（って、動くなーーーー！！）"

# ゆんゆん
# あう！
328 = "あう！"

# カズマ
# お、おい、どうした？
359 = "お、おい、どうした？"

# ゆんゆん
# す、すみません。\n足が痺れちゃってて、動けなく……。
367 = "す、すみません。\\n足が痺れちゃってて、動けなく……。"

# カズマ
# よかった、怪我をしたわけじゃないんだな？\nそれならしばらくこのままでいいよ。
417 = "よかった、怪我をしたわけじゃないんだな？\\nそれならしばらくこのままでいいよ。"

# ゆんゆん
# ですが、カズマさんに失礼です。
389 = "ですが、カズマさんに失礼です。"

# カズマ
# 気にするなって。\n女の子に座られているのも案外悪くない\nもんだしさ。
438 = "気にするなって。\\n女の子に座られているのも案外悪くない\\nもんだしさ。"

# ゆんゆん
# うふふふ、カズマさんたら。
345 = "うふふふ、カズマさんたら。"

# カズマ（Ｍ）
# display as カズマ
# （くっそ、この超ド級の可愛さは反則だろ！？）
477 = "（くっそ、この超ド級の可愛さは反則だろ！？）"

# ゆんゆん
# あうう、足がぴりぴりしてるぅ～～～～！
327 = "あうう、足がぴりぴりしてるぅ～～～～！"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、願わくばずっと眺めていたい。\n　愛でていたい）
496 = "（はぁ、願わくばずっと眺めていたい。\\n　愛でていたい）"

# ゆんゆん
# あ、あの、カズマさん？\nジッと見て、私どこかおかしいですか？
323 = "あ、あの、カズマさん？\\nジッと見て、私どこかおかしいですか？"

# カズマ
# なあ、ゆんゆん――
397 = "なあ、ゆんゆん――"

# カズマ
# 微笑んでみてくれ！
436 = "微笑んでみてくれ！"

# ゆんゆん
# え？　あ、は、はい……、\nこ、こうでいいですか？
355 = "え？　あ、は、はい……、\\nこ、こうでいいですか？"

# カズマ
# ゆんゆんは素直でいい子だな、\n俺の頼みを嫌がらず聞いてくれるんだから。
414 = "ゆんゆんは素直でいい子だな、\\n俺の頼みを嫌がらず聞いてくれるんだから。"

# ゆんゆん
# 笑うくらい大したことありませんから。
475 = "笑うくらい大したことありませんから。"

# カズマ
# きっと他のお願いをしても応えてくれただろ？
362 = "きっと他のお願いをしても応えてくれただろ？"

# ゆんゆん
# エ、エッチなお願いはダメですよ？
420 = "エ、エッチなお願いはダメですよ？"

# カズマ
# それは残念だな！
376 = "それは残念だな！"

# ゆんゆん
# うふふ、カズマさんたら。
344 = "うふふ、カズマさんたら。"

# カズマ
# 俺の妹になってくれ！
431 = "俺の妹になってくれ！"

# ゆんゆん
# え？　え？　え？\nい、妹ですか？
357 = "え？　え？　え？\\nい、妹ですか？"

# カズマ
# ゆんゆんみたいな可愛い妹が\n昔から欲しかったんだよ！\nどうだ！？
415 = "ゆんゆんみたいな可愛い妹が\\n昔から欲しかったんだよ！\\nどうだ！？"

# ゆんゆん
# どうだと言われても、さすがにそれは無理です。
395 = "どうだと言われても、さすがにそれは無理です。"

# カズマ
# ですよねぇ～。
391 = "ですよねぇ～。"

# カズマ
# もう誰にも渡したくない！
412 = "もう誰にも渡したくない！"

# ゆんゆん
# え？\nカ、カズマさん、そ、それって……。
354 = "え？\\nカ、カズマさん、そ、それって……。"

# カズマ（Ｍ）
# display as カズマ
# （って、あまりにもゆんゆんが可愛くて、\n　つい口が滑っちまったよ！）
489 = "（って、あまりにもゆんゆんが可愛くて、\\n　つい口が滑っちまったよ！）"

# カズマ（Ｍ）
# display as カズマ
# （やばっ、変に思われなかったか？\n　無理だって、どう考えたって変に思っただろ？）
499 = "（やばっ、変に思われなかったか？\\n　無理だって、どう考えたって変に思っただろ？）"

# カズマ（Ｍ）
# display as カズマ
# （なんとかしないと！）
494 = "（なんとかしないと！）"

# カズマ
# あっ、いや、今のは忘れてくれ。
329 = "あっ、いや、今のは忘れてくれ。"

# ゆんゆん
# で、でも。
387 = "で、でも。"

# カズマ
# いいから頼む。
339 = "いいから頼む。"

# ゆんゆん
# わかりました。
418 = "わかりました。"

# めぐみん
# 何をしているのです２人とも！
427 = "何をしているのです２人とも！"

# ゆんゆん
# め、めぐみん！？\nこ、これは倒れそうになった私を\nカズマさんが助けてくれて――
409 = "め、めぐみん！？\\nこ、これは倒れそうになった私を\\nカズマさんが助けてくれて――"

# ゆんゆん
# そうしたら足が痺れて立てなくて……、\nと、とにかくなんでもないから！
373 = "そうしたら足が痺れて立てなくて……、\\nと、とにかくなんでもないから！"

# めぐみん
# へえ、そうなんですか。
406 = "へえ、そうなんですか。"

# カズマ（Ｍ）
# display as カズマ
# （なぜ、俺を睨む）
493 = "（なぜ、俺を睨む）"

# めぐみん
# どうでもいいですが、見えそうになっていますよ。\nパンツが。
396 = "どうでもいいですが、見えそうになっていますよ。\\nパンツが。"

# ゆんゆん
# え……まさか、カズマさんずっと。
346 = "え……まさか、カズマさんずっと。"

# カズマ
# な！？　みみみ、見てないから！\nギリギリセーフだから！
399 = "な！？　みみみ、見てないから！\\nギリギリセーフだから！"

# ゆんゆん
# うぅぅぅ、カズマさん、ひどいですーーーー！！
343 = "うぅぅぅ、カズマさん、ひどいですーーーー！！"

# カズマ
# あああああ、ゆんゆーーーん！！
325 = "あああああ、ゆんゆーーーん！！"

[selections]
# 436 = "微笑んでみてくれ！"
# 431 = "俺の妹になってくれ！"
# 412 = "もう誰にも渡したくない！"
