# rew_e10.txt.scn

[info]
204 = "rew_e10"

[characters]
298 = "ゆんゆん"
300 = "カズマ"
302 = "カズマ（Ｍ）"

[character_subs]
# 300 = "カズマ"

[script]
# lines: 87

# ゆんゆん
# あの、お仕置きなんですが、\nマッサージをお願いしてもいいですか？
250 = "あの、お仕置きなんですが、\\nマッサージをお願いしてもいいですか？"

# カズマ
# ああ、それくらい構わないぞ。
243 = "ああ、それくらい構わないぞ。"

# カズマ
# この俺のテクニックで\nコリも疲労も消し去ってやろう。
280 = "この俺のテクニックで\\nコリも疲労も消し去ってやろう。"

# ゆんゆん
# では、お願いします。
289 = "では、お願いします。"

# カズマ
# うん、それで？
270 = "うん、それで？"

# ゆんゆん
# え？
274 = "え？"

# カズマ
# いや、どこをマッサージして欲しいんだ？
264 = "いや、どこをマッサージして欲しいんだ？"

# ゆんゆん
# あっ、そ、そうですよね！\nええとええと、どこがいいんだろう。
247 = "あっ、そ、そうですよね！\\nええとええと、どこがいいんだろう。"

# カズマ
# 肩はこってるか？
333 = "肩はこってるか？"

# ゆんゆん
# いえ、特には。
263 = "いえ、特には。"

# カズマ
# 腰や背中は？
334 = "腰や背中は？"

# ゆんゆん
# 平気です。
313 = "平気です。"

# カズマ
# じゃあ、足にむくみとかは？
286 = "じゃあ、足にむくみとかは？"

# ゆんゆん
# ありませんよ？
259 = "ありませんよ？"

# カズマ
# うん、じゃあなんでマッサージを？
269 = "うん、じゃあなんでマッサージを？"

# ゆんゆん
# ええと、気持ちいいかなって思いまして。
271 = "ええと、気持ちいいかなって思いまして。"

# カズマ（Ｍ）
# display as カズマ
# （お受験大国の日本じゃないんだから、\n　１３歳で肩こりとか腰痛があるわけないか）
338 = "（お受験大国の日本じゃないんだから、\\n　１３歳で肩こりとか腰痛があるわけないか）"

# カズマ（Ｍ）
# display as カズマ
# （それにゆんゆんはクエストとかで\n　ちゃんと体を動かしてるだろうし）
340 = "（それにゆんゆんはクエストとかで\\n　ちゃんと体を動かしてるだろうし）"

# カズマ（Ｍ）
# display as カズマ
# （あ、それなら！）
336 = "（あ、それなら！）"

# カズマ
# よし、ゆんゆん、ちょっと髪を持ち上げてくれ。
299 = "よし、ゆんゆん、ちょっと髪を持ち上げてくれ。"

# ゆんゆん
# こうですか？
277 = "こうですか？"

# カズマ
# 体は無理にマッサージすると痛めちゃうからさ、\n代わりに耳を――
307 = "体は無理にマッサージすると痛めちゃうからさ、\\n代わりに耳を――"

# ゆんゆん
# きゃ！
276 = "きゃ！"

# カズマ
# あっ、悪い。\n嫌だったか？
249 = "あっ、悪い。\\n嫌だったか？"

# ゆんゆん
# いえ、急だったからびっくりしちゃっただけです。
262 = "いえ、急だったからびっくりしちゃっただけです。"

# カズマ
# えーと、続きはどうする？
273 = "えーと、続きはどうする？"

# ゆんゆん
# ご迷惑で無ければお願いします。
283 = "ご迷惑で無ければお願いします。"

# カズマ
# 迷惑なんてないよ。
335 = "迷惑なんてないよ。"

# ゆんゆん
# あん。
261 = "あん。"

# カズマ（Ｍ）
# display as カズマ
# （色っぽい声を出すな……）
347 = "（色っぽい声を出すな……）"

# ゆんゆん
# うふ、うふふ、くすぐったいですよー。
267 = "うふ、うふふ、くすぐったいですよー。"

# カズマ（Ｍ）
# display as カズマ
# （うーん、なんというか……）
337 = "（うーん、なんというか……）"

# ゆんゆん
# あん、そこはダメですってばー。
260 = "あん、そこはダメですってばー。"

# カズマ（Ｍ）
# display as カズマ
# （この角度も相まって、色々と目のやり場に困る）
339 = "（この角度も相まって、色々と目のやり場に困る）"

# ゆんゆん
# あっ、そこ気持ちいいです。
248 = "あっ、そこ気持ちいいです。"

# カズマ（Ｍ）
# display as カズマ
# （てか、めぐみんと同い年とは思えないな）
341 = "（てか、めぐみんと同い年とは思えないな）"

# ゆんゆん
# カズマさん？
301 = "カズマさん？"

# カズマ（Ｍ）
# display as カズマ
# （何を食って何をすれば、\n　こんな立派に育つんだよ）
343 = "（何を食って何をすれば、\\n　こんな立派に育つんだよ）"

# ゆんゆん
# カーズーマーさん！
303 = "カーズーマーさん！"

# カズマ
# あっ、え？　なんだ？
246 = "あっ、え？　なんだ？"

# ゆんゆん
# それは私が聞きたいですよ。\nボーッとしてどうしたんですか？
288 = "それは私が聞きたいですよ。\\nボーッとしてどうしたんですか？"

# カズマ
# いや、立派だなぁっと。
266 = "いや、立派だなぁっと。"

# ゆんゆん
# え？　立派？
275 = "え？　立派？"

# カズマ
# いや、なんでもない！
265 = "いや、なんでもない！"

# カズマ
# えーと、力加減はどうだ、\n痛かったりしないか？
272 = "えーと、力加減はどうだ、\\n痛かったりしないか？"

# ゆんゆん
# 大丈夫ですよ。\nもう少し強くてもいいくらいです。
309 = "大丈夫ですよ。\\nもう少し強くてもいいくらいです。"

# カズマ
# そうか、それじゃ\nもう少しだけ力を込めてっと。
287 = "そうか、それじゃ\\nもう少しだけ力を込めてっと。"

# ゆんゆん
# あっ……いいです。\nこれくらいの力加減でお願いします。
244 = "あっ……いいです。\\nこれくらいの力加減でお願いします。"

# ゆんゆん
# あぁ～……癒やされます。\n上手ですね。
242 = "あぁ～……癒やされます。\\n上手ですね。"

# カズマ
# この辺はどうだ？
281 = "この辺はどうだ？"

# ゆんゆん
# ひゃぅ！
293 = "ひゃぅ！"

# カズマ
# あ、ダメだったか？
241 = "あ、ダメだったか？"

# ゆんゆん
# うふふ、あははは、くすぐったいですよ～！
268 = "うふふ、あははは、くすぐったいですよ～！"

# カズマ（Ｍ）
# display as カズマ
# （足をバタバタさせて可愛いな）
348 = "（足をバタバタさせて可愛いな）"

# カズマ
# じゃあ、ここはどうだ！
285 = "じゃあ、ここはどうだ！"

# ゆんゆん
# ダメダメぇ、そこもくすぐったいです～！
304 = "ダメダメぇ、そこもくすぐったいです～！"

# カズマ
# じゃ、この辺は？
284 = "じゃ、この辺は？"

# ゆんゆん
# あははははははは！\nくすぐったい……、\n痛いのにくすぐったい！
255 = "あははははははは！\\nくすぐったい……、\\n痛いのにくすぐったい！"

# ゆんゆん
# あははははははは！！
256 = "あははははははは！！"

# カズマ（Ｍ）
# display as カズマ
# （思いがけない反応だ。\n　なんだか面白くなってきた。\n　息を吹きかけたらどうなるんだ？）
345 = "（思いがけない反応だ。\\n　なんだか面白くなってきた。\\n　息を吹きかけたらどうなるんだ？）"

# カズマ
# ふぅ～～～。
294 = "ふぅ～～～。"

# ゆんゆん
# あはは、あはは！\nあははははははは！！
252 = "あはは、あはは！\\nあははははははは！！"

# カズマ
# 耳が敏感なんだな。\nまさか、ここまでくすぐったがるとは。
328 = "耳が敏感なんだな。\\nまさか、ここまでくすぐったがるとは。"

# ゆんゆん
# あはは、へ、変になっちゃいます～。
253 = "あはは、へ、変になっちゃいます～。"

# カズマ
# ふぅ～～～。
# 294 = "ふぅ～～～。"

# カズマ（Ｍ）
# display as カズマ
# （思いがけない反応だ。\n　なんだか面白くなってきた。\n　ちょっと耳の中をくすぐってみよう）
344 = "（思いがけない反応だ。\\n　なんだか面白くなってきた。\\n　ちょっと耳の中をくすぐってみよう）"

# カズマ
# こちょこちょこちょこちょ。
279 = "こちょこちょこちょこちょ。"

# ゆんゆん
# ひゃぁぁ、耳の中にっ、ダ、ダメぇ！！\nくすぐったい、あはははは！
292 = "ひゃぁぁ、耳の中にっ、ダ、ダメぇ！！\\nくすぐったい、あはははは！"

# カズマ
# 耳全体が敏感なんだな。\nこちょこちょこちょこちょ。
332 = "耳全体が敏感なんだな。\\nこちょこちょこちょこちょ。"

# カズマ（Ｍ）
# display as カズマ
# （思いがけない反応だ。\n　なんだか面白くなってきた。\n　耳たぶをぷにぷにしてやろう
346 = "（思いがけない反応だ。\\n　なんだか面白くなってきた。\\n　耳たぶをぷにぷにしてやろう"

# ゆんゆん
# あっ、あっ、く、くすぐったい！\nうふ、うふふふ……！
245 = "あっ、あっ、く、くすぐったい！\\nうふ、うふふふ……！"

# カズマ
# まさかこんなに耳が弱いとは。\nゆんゆんの弱点見つけたり！
296 = "まさかこんなに耳が弱いとは。\\nゆんゆんの弱点見つけたり！"

# ゆんゆん
# あははは、や、やめてくださ～い！
254 = "あははは、や、やめてくださ～い！"

# カズマ
# でも、この感触がたまらないというか。\nむにむにむに。
290 = "でも、この感触がたまらないというか。\\nむにむにむに。"

# ゆんゆん
# あははは！\nダ、ダメですってば、あはははははは！！
257 = "あははは！\\nダ、ダメですってば、あはははははは！！"

# ゆんゆん
# 本当に本当に、はぁはぁ、おかしくなっちゃいます！\nあは、あははははは！！
314 = "本当に本当に、はぁはぁ、おかしくなっちゃいます！\\nあは、あははははは！！"

# カズマ
# やばい、どんどん楽しくなってきた！\nほれ、ほれほれ！
297 = "やばい、どんどん楽しくなってきた！\\nほれ、ほれほれ！"

# ゆんゆん
# あははー、あー、あはは！！\nダメ、本当にこれ以上はっ！！
258 = "あははー、あー、あはは！！\\nダメ、本当にこれ以上はっ！！"

# カズマ
# ほ～れ、ほれほれ、ほれほれー！
295 = "ほ～れ、ほれほれ、ほれほれー！"

# ゆんゆん
# 嫌、お腹が痛いっ！\nやめてぇぇ～～～～！！
310 = "嫌、お腹が痛いっ！\\nやめてぇぇ～～～～！！"

# カズマ
# ここはどうだ！\nうり、うり、うりうり～！！
278 = "ここはどうだ！\\nうり、うり、うりうり～！！"

# ゆんゆん
# あの、本当にやめてください。
251 = "あの、本当にやめてください。"

# カズマ
# え？
# 274 = "え？"

# ゆんゆん
# 嫌って言ってるじゃないですか。
311 = "嫌って言ってるじゃないですか。"

# カズマ
# ご、ごめんなさい。
282 = "ご、ごめんなさい。"

# ゆんゆん
# はふ～、お腹が痛くなっちゃいました。
291 = "はふ～、お腹が痛くなっちゃいました。"

# カズマ（Ｍ）
# display as カズマ
# （もしかしたら、ゆんゆんは一番怒らせちゃ\n　いけない子なのかもしれない）
342 = "（もしかしたら、ゆんゆんは一番怒らせちゃ\\n　いけない子なのかもしれない）"

[selections]
330 = "耳に息を吹きかけてやろう"
331 = "耳の中をくすぐってやろう"
329 = "耳たぶをぷにぷにしてやろう"
