# rew_e06.txt.scn

[info]
216 = "rew_e06"

[characters]
351 = "ゆんゆん"
360 = "カズマ（Ｍ）"
357 = "カズマ"

[character_subs]
# 357 = "カズマ"

[script]
# lines: 108

# ゆんゆん
# そ、それではお仕置きを始めます。
319 = "そ、それではお仕置きを始めます。"

# カズマ（Ｍ）
# display as カズマ
# （お仕置きか。\n　まあ、アクア達と違ってゆんゆんなら\n　無茶なことも言わないだろう）
433 = "（お仕置きか。\\n　まあ、アクア達と違ってゆんゆんなら\\n　無茶なことも言わないだろう）"

# カズマ（Ｍ）
# display as カズマ
# （そういう意味では安心できるな。うんうん！）
437 = "（そういう意味では安心できるな。うんうん！）"

# カズマ
# それで、俺は何をすればいいんだ？
323 = "それで、俺は何をすればいいんだ？"

# ゆんゆん
# お、お友達ごっこをしてください！
310 = "お、お友達ごっこをしてください！"

# カズマ（Ｍ）
# display as カズマ
# （ん？　お友達になってくださいじゃなくて、\n　お友達ごっこ？？）
443 = "（ん？　お友達になってくださいじゃなくて、\\n　お友達ごっこ？？）"

# ゆんゆん
# 嫌なら無理にとは言いませんけど……。
371 = "嫌なら無理にとは言いませんけど……。"

# カズマ
# 嫌じゃないが、\nその前にハッキリさせておきたいことがある。
370 = "嫌じゃないが、\\nその前にハッキリさせておきたいことがある。"

# ゆんゆん
# あ、はい！　なんでしょう！
296 = "あ、はい！　なんでしょう！"

# カズマ
# もしかして俺は友達と思われていないのか？
346 = "もしかして俺は友達と思われていないのか？"

# ゆんゆん
# あ、はい！
295 = "あ、はい！"

# カズマ
# ええ！？
306 = "ええ！？"

# ゆんゆん
# あ、いえ、私はカズマさんとお友達になりたいって\n思っていますけど、お友達になるためには相手の\n了承が必要なんじゃないかなって。
293 = "あ、いえ、私はカズマさんとお友達になりたいって\\n思っていますけど、お友達になるためには相手の\\n了承が必要なんじゃないかなって。"

# カズマ（Ｍ）
# display as カズマ
# （その思考が、なんか不憫だ……）
439 = "（その思考が、なんか不憫だ……）"

# カズマ
# あのなー、俺は、ゆんゆんを友達だと思ってるぞ。
298 = "あのなー、俺は、ゆんゆんを友達だと思ってるぞ。"

# ゆんゆん
# 本当ですか！？
382 = "本当ですか！？"

# カズマ（Ｍ）
# display as カズマ
# （すっごい食いつきだな、おい！）
436 = "（すっごい食いつきだな、おい！）"

# ゆんゆん
# これって、了承を得たってことですよね！
314 = "これって、了承を得たってことですよね！"

# カズマ
# まず、その考え方がおかしい！\n友達ってのは自然になるもんで、お互いに確認を\nとってようやくなるってもんじゃないだろう。
343 = "まず、その考え方がおかしい！\\n友達ってのは自然になるもんで、お互いに確認を\\nとってようやくなるってもんじゃないだろう。"

# ゆんゆん
# そ、そうなんですか。
318 = "そ、そうなんですか。"

# カズマ（Ｍ）
# display as カズマ
# （この子に友達がいない理由が、\n　なんとなくわかるような気がする）
435 = "（この子に友達がいない理由が、\\n　なんとなくわかるような気がする）"

# ゆんゆん
# 私って、仲良くなりたいって思っても\nどうしても昔から友達ができなくて。
426 = "私って、仲良くなりたいって思っても\\nどうしても昔から友達ができなくて。"

# ゆんゆん
# だから、どうしたらもっとたくさんの人と\n友達になれるか知りたいんです！
325 = "だから、どうしたらもっとたくさんの人と\\n友達になれるか知りたいんです！"

# ゆんゆん
# カズマさん、教えてください！\nどうして私を友達だって思ったんですか！
358 = "カズマさん、教えてください！\\nどうして私を友達だって思ったんですか！"

# ゆんゆん
# きっとそこに、私がお友達をたくさん作れる\n打開策が隠れていると思うんです！
312 = "きっとそこに、私がお友達をたくさん作れる\\n打開策が隠れていると思うんです！"

# カズマ
# え、ええと、その前に確認なんだけど。\nどうしてお友達ごっこなんてしようと思ったんだ？
302 = "え、ええと、その前に確認なんだけど。\\nどうしてお友達ごっこなんてしようと思ったんだ？"

# ゆんゆん
# ふたつありまして、ひとつはこれがきっかけで、\nカズマさんとお友達になれたらなって。
341 = "ふたつありまして、ひとつはこれがきっかけで、\\nカズマさんとお友達になれたらなって。"

# カズマ
# な、なるほど、じゃあ、もうひとつは？
332 = "な、なるほど、じゃあ、もうひとつは？"

# ゆんゆん
# 友達を作るヒントを見つけられるんじゃないかって\n思ったんです。
366 = "友達を作るヒントを見つけられるんじゃないかって\\n思ったんです。"

# カズマ（Ｍ）
# display as カズマ
# （そこまでしないと友達を作れないゆんゆんって）
438 = "（そこまでしないと友達を作れないゆんゆんって）"

# ゆんゆん
# あ、あれ？　どうして涙ぐんでるんですか？\nおかしなこと言いましたか？
292 = "あ、あれ？　どうして涙ぐんでるんですか？\\nおかしなこと言いましたか？"

# カズマ
# よし、ゆんゆん、\nたくさん友達ごっこをしよう！\n友達をいっぱい作ろうな！
352 = "よし、ゆんゆん、\\nたくさん友達ごっこをしよう！\\n友達をいっぱい作ろうな！"

# ゆんゆん
# ありがとうございます！
299 = "ありがとうございます！"

# カズマ（Ｍ）
# display as カズマ
# （不憫すぎる……\n　これはもうお仕置きじゃない、\n　ゆんゆん救済イベントだ）
445 = "（不憫すぎる……\\n　これはもうお仕置きじゃない、\\n　ゆんゆん救済イベントだ）"

# カズマ
# 友達を作る上でまず大切なのは会話だ。\n会話も成立しないような相手と\n友達になりたいと思う人間はいないだろ？
367 = "友達を作る上でまず大切なのは会話だ。\\n会話も成立しないような相手と\\n友達になりたいと思う人間はいないだろ？"

# ゆんゆん
# なるほど、会話……。
335 = "なるほど、会話……。"

# カズマ（Ｍ）
# display as カズマ
# （メモを取るのか……）
444 = "（メモを取るのか……）"

# カズマ
# というわけで、\n手始めに自己紹介をしてみようか？
330 = "というわけで、\\n手始めに自己紹介をしてみようか？"

# ゆんゆん
# わ、わかりました！
353 = "わ、わかりました！"

# ゆんゆん
# ええとええと、こ、紅魔族です！\nゆ、ゆ、ゆんゆんです！\nアークウィザードです！
305 = "ええとええと、こ、紅魔族です！\\nゆ、ゆ、ゆんゆんです！\\nアークウィザードです！"

# カズマ
# ストップ、いったん止めて。
361 = "ストップ、いったん止めて。"

# ゆんゆん
# な、何か問題がありましたか？
334 = "な、何か問題がありましたか？"

# カズマ
# 問題だらけだ。\nなんで事実を羅列するだけなんだよ。
369 = "問題だらけだ。\\nなんで事実を羅列するだけなんだよ。"

# ゆんゆん
# 感情にまかせて喋ったら、\n余計なことを言って嫌われちゃうかなって\n思いまして。
376 = "感情にまかせて喋ったら、\\n余計なことを言って嫌われちゃうかなって\\n思いまして。"

# カズマ（Ｍ）
# display as カズマ
# （なるほど、ゆんゆんは繊細……。\n　いや、臆病なんだな）
442 = "（なるほど、ゆんゆんは繊細……。\\n　いや、臆病なんだな）"

# カズマ（Ｍ）
# display as カズマ
# （だったら……）
440 = "（だったら……）"

# カズマ
# もっと弾けてみようか！
348 = "もっと弾けてみようか！"

# ゆんゆん
# 弾けるですか？
373 = "弾けるですか？"

# カズマ
# 怖い気持ちを突き抜けるには、\n勢いが大切なんだよ。
374 = "怖い気持ちを突き抜けるには、\\n勢いが大切なんだよ。"

# カズマ
# 明るく元気に、\n自分の殻を突き破るくらいのつもりで\nドンといってみよう！
379 = "明るく元気に、\\n自分の殻を突き破るくらいのつもりで\\nドンといってみよう！"

# ゆんゆん
# わ、わかりました！\n自分の殻を突き破るくらいに、\n明るく元気に……って、どうすれば。
354 = "わ、わかりました！\\n自分の殻を突き破るくらいに、\\n明るく元気に……って、どうすれば。"

# カズマ（Ｍ）
# display as カズマ
# （確かにきっかけが必要か）
446 = "（確かにきっかけが必要か）"

# カズマ
# じゃあ、最初のきっかけをあげるから。\n俺の言うとおりに喋ってみてくれ。
316 = "じゃあ、最初のきっかけをあげるから。\\n俺の言うとおりに喋ってみてくれ。"

# ゆんゆん
# は、はい！
337 = "は、はい！"

# カズマ
# はーい、私ゆんゆん！
340 = "はーい、私ゆんゆん！"

# ゆんゆん
# え？　ええ！？
308 = "え？　ええ！？"

# カズマ
# ほーら、ゆんゆんもやってみるんだ。
342 = "ほーら、ゆんゆんもやってみるんだ。"

# ゆんゆん
# ええと、はぁ～い、私、ゆんゆん！
304 = "ええと、はぁ～い、私、ゆんゆん！"

# カズマ
# おっ、いいぞ。\nそのテンションで続けて！
311 = "おっ、いいぞ。\\nそのテンションで続けて！"

# ゆんゆん
# えっとえっと、見て見てこの赤い瞳、\n実は私って紅魔族なの。
307 = "えっとえっと、見て見てこの赤い瞳、\\n実は私って紅魔族なの。"

# ゆんゆん
# 生まれ持った魔力の高さを活かして\nアークウィザードをやってるんだ。\n上級魔法ならお手の物なんだから。
384 = "生まれ持った魔力の高さを活かして\\nアークウィザードをやってるんだ。\\n上級魔法ならお手の物なんだから。"

# ゆんゆん
# あっ、今のはダメですよね。\nまるで自慢してるみたいですし。
297 = "あっ、今のはダメですよね。\\nまるで自慢してるみたいですし。"

# カズマ
# 誰もそんな風に考えないって。
428 = "誰もそんな風に考えないって。"

# ゆんゆん
# 本当ですか？
383 = "本当ですか？"

# カズマ
# 本当だよ。\nだから自分に自信を持つ！
381 = "本当だよ。\\nだから自分に自信を持つ！"

# ゆんゆん
# でも、ありもしない自信を持ったりしたら、\n調子に乗ってるって思われたり……。
329 = "でも、ありもしない自信を持ったりしたら、\\n調子に乗ってるって思われたり……。"

# カズマ
# 思わないって……。
375 = "思わないって……。"

# ゆんゆん
# カズマさんは、ですよね？
359 = "カズマさんは、ですよね？"

# カズマ（Ｍ）
# display as カズマ
# （あー、めんどくせー）
431 = "（あー、めんどくせー）"

# カズマ
# めぐみんのような口上で自己紹介してみたらどうだ？\n同じ紅魔族なんだし。
344 = "めぐみんのような口上で自己紹介してみたらどうだ？\\n同じ紅魔族なんだし。"

# ゆんゆん
# こ、口上ですか……。
313 = "こ、口上ですか……。"

# カズマ
# 抵抗が大ありって感じだな。
378 = "抵抗が大ありって感じだな。"

# ゆんゆん
# だって、恥ずかしいじゃないですか。
326 = "だって、恥ずかしいじゃないですか。"

# ゆんゆん
# それに変な女の子って思われたりしたら、\nお友達になって貰えないかもしれません。
324 = "それに変な女の子って思われたりしたら、\\nお友達になって貰えないかもしれません。"

# カズマ
# その程度でゆんゆんを敬遠するようなやつとは\n友達にならない方がいいと思うぞ。
322 = "その程度でゆんゆんを敬遠するようなやつとは\\n友達にならない方がいいと思うぞ。"

# ゆんゆん
# そうなんですか？
320 = "そうなんですか？"

# カズマ
# 自分の駄目な所、弱い部分も受け入れてくれるから\nこそ、友達って言えると俺は思うんだけどな。
427 = "自分の駄目な所、弱い部分も受け入れてくれるから\\nこそ、友達って言えると俺は思うんだけどな。"

# ゆんゆん
# な、なるほど、確かにそうですよね！\nカズマさんってすごいです！
333 = "な、なるほど、確かにそうですよね！\\nカズマさんってすごいです！"

# カズマ（Ｍ）
# display as カズマ
# （うぐ、アニメの受け売りだなんて言えない）
432 = "（うぐ、アニメの受け売りだなんて言えない）"

# ゆんゆん
# で、では、改めて自己紹介をさせていただきます！
327 = "で、では、改めて自己紹介をさせていただきます！"

# ゆんゆん
# わ、我が名はゆんゆん……！\nやがて紅魔族の長となる者……！
355 = "わ、我が名はゆんゆん……！\\nやがて紅魔族の長となる者……！"

# カズマ
# ん～……照れが残ってるぞ。\nめぐみんのように堂々と言ってみろ。
356 = "ん～……照れが残ってるぞ。\\nめぐみんのように堂々と言ってみろ。"

# ゆんゆん
# はい、わかりました。
339 = "はい、わかりました。"

# ゆんゆん
# 我が名はゆんゆん！\nやがて紅魔族の長となる者！！
377 = "我が名はゆんゆん！\\nやがて紅魔族の長となる者！！"

# カズマ
# うん、いい感じだ！
301 = "うん、いい感じだ！"

# カズマ
# もっと自分を深く紹介してみたらどうだ？\n趣味や特技とか、好きな物とか、\nあとアピールしたいこととか。
349 = "もっと自分を深く紹介してみたらどうだ？\\n趣味や特技とか、好きな物とか、\\nあとアピールしたいこととか。"

# カズマ
# 友達になるには、まず自分を見せるってことが\n大切だからな。
365 = "友達になるには、まず自分を見せるってことが\\n大切だからな。"

# ゆんゆん
# なるほど、確かにそうですよね！\nやってみます！
336 = "なるほど、確かにそうですよね！\\nやってみます！"

# ゆんゆん
# え、えっと、ゆんゆんです。\nお、お友達を募集しています。
303 = "え、えっと、ゆんゆんです。\\nお、お友達を募集しています。"

# ゆんゆん
# 優しくてつまらない話でも聞いてくれる人、\n名前が変わっていても笑わない人――
364 = "優しくてつまらない話でも聞いてくれる人、\\n名前が変わっていても笑わない人――"

# ゆんゆん
# 何もない日でも一緒にいてくれる人を\n募集しています。
363 = "何もない日でも一緒にいてくれる人を\\n募集しています。"

# ゆんゆん
# あ、できれば年が近いと嬉しいです。\nわ、私は最近１３歳になったばかりで、\n職業はアークウィザードです。
294 = "あ、できれば年が近いと嬉しいです。\\nわ、私は最近１３歳になったばかりで、\\n職業はアークウィザードです。"

# ゆんゆん
# 一応、上級魔法を操れるので、\nクエストにも同行できますよ？
362 = "一応、上級魔法を操れるので、\\nクエストにも同行できますよ？"

# ゆんゆん
# ですから、パーティーに火力が必要な時とかに\n使って貰えればなって思います。
328 = "ですから、パーティーに火力が必要な時とかに\\n使って貰えればなって思います。"

# ゆんゆん
# 昔から友達が少なくて……\nだ、だからできれば\n一生のお友達になってください。
380 = "昔から友達が少なくて……\\nだ、だからできれば\\n一生のお友達になってください。"

# ゆんゆん
# どんな時も支え合い裏切らず、\nお互いだけを必要とする魂の友達に！
331 = "どんな時も支え合い裏切らず、\\nお互いだけを必要とする魂の友達に！"

# ゆんゆん
# もしこんな私を受け入れてくれるなら、\n毎日掃除やご飯を作りに伺います！
347 = "もしこんな私を受け入れてくれるなら、\\n毎日掃除やご飯を作りに伺います！"

# ゆんゆん
# そ、そうだお揃いの服を着て\nお出かけもしてみたいかな。\n服は私が作りますね！
317 = "そ、そうだお揃いの服を着て\\nお出かけもしてみたいかな。\\n服は私が作りますね！"

# ゆんゆん
# こんな私ですが、\nお気軽に友達になってください。
315 = "こんな私ですが、\\nお気軽に友達になってください。"

# カズマ
# 重い！　重いよ！\n全然お気軽に友達になれないよ！
429 = "重い！　重いよ！\\n全然お気軽に友達になれないよ！"

# ゆんゆん
# はぁ、友達を作るって難しいですね。
338 = "はぁ、友達を作るって難しいですね。"

# ゆんゆん
# その点、誰とでもお友達になれてしまう\nカズマさんって凄いと思います！
321 = "その点、誰とでもお友達になれてしまう\\nカズマさんって凄いと思います！"

# カズマ
# いやいや、俺だって本当は――
300 = "いやいや、俺だって本当は――"

# カズマ（Ｍ）
# display as カズマ
# （あっ、そうだよ……、\n　何を偉そうにしてるんだ俺、\n　自分が何者か忘れてんじゃないのか？）
430 = "（あっ、そうだよ……、\\n　何を偉そうにしてるんだ俺、\\n　自分が何者か忘れてんじゃないのか？）"

# カズマ（Ｍ）
# display as カズマ
# （こっちに来るまで引き籠もりだった俺が、\n　友達を作る方法を教えられるわけないだろ！\n　バカか！）
434 = "（こっちに来るまで引き籠もりだった俺が、\\n　友達を作る方法を教えられるわけないだろ！\\n　バカか！）"

# カズマ（Ｍ）
# display as カズマ
# （どうしてこんな基本的なことを\n　忘れてたんだ？）
441 = "（どうしてこんな基本的なことを\\n　忘れてたんだ？）"

# カズマ
# ……死にたい。
291 = "……死にたい。"

# ゆんゆん
# え？　ど、どうしたんですか、\nカズマさん！？　カズマさん！？
309 = "え？　ど、どうしたんですか、\\nカズマさん！？　カズマさん！？"

[selections]
# 348 = "もっと弾けてみようか！"
345 = "めぐみんのような口上で自己紹介してみては？"
350 = "もっと自分を深く紹介してみては？"
