# rew_a10.txt.scn

[info]
188 = "rew_a10"

[characters]
274 = "アクア"
279 = "カズマ（Ｍ）"
276 = "カズマ"

[character_subs]
# 276 = "カズマ"

[script]
# lines: 81

# アクア
# ふふふふーん。
260 = "ふふふふーん。"

# カズマ（Ｍ）
# display as カズマ
# （こいつ、人の部屋に来たと思ったらニーソを\n　脱ぎ始めて、何をたくらんでるんだ）
299 = "（こいつ、人の部屋に来たと思ったらニーソを\\n　脱ぎ始めて、何をたくらんでるんだ）"

# アクア
# じゃあ、カズマ、よろしくね。
238 = "じゃあ、カズマ、よろしくね。"

# カズマ
# 何を……。
282 = "何を……。"

# アクア
# 足がだるいから、優しく揉みほぐしてくれる？
296 = "足がだるいから、優しく揉みほぐしてくれる？"

# カズマ
# うーん、別に構わないけどさ。
227 = "うーん、別に構わないけどさ。"

# アクア
# これはお仕置きなんだから、\n拒否権がないことくらいわかってるわよね。
236 = "これはお仕置きなんだから、\\n拒否権がないことくらいわかってるわよね。"

# カズマ
# わかってるって。\nでも素人仕事なんだから後でどうなっても\n責任はとれないからな。
268 = "わかってるって。\\nでも素人仕事なんだから後でどうなっても\\n責任はとれないからな。"

# カズマ（Ｍ）
# display as カズマ
# （うーん、よくわからないけど、\n　こんな感じでいいのか？）
297 = "（うーん、よくわからないけど、\\n　こんな感じでいいのか？）"

# アクア
# うんうん、良い感じ。\nでももうちょっと強い方が気持ち良いかも。
226 = "うんうん、良い感じ。\\nでももうちょっと強い方が気持ち良いかも。"

# カズマ
# よっ、これくらいかっ？
266 = "よっ、これくらいかっ？"

# アクア
# んがんはぁ！　痛いっ、いっったいっ！！
271 = "んがんはぁ！　痛いっ、いっったいっ！！"

# カズマ
# お前、女とは思えない悲鳴をあげんな！
230 = "お前、女とは思えない悲鳴をあげんな！"

# アクア
# カズマが力任せに押すからでしょ！\nもっと優しくして！
277 = "カズマが力任せに押すからでしょ！\\nもっと優しくして！"

# カズマ
# あー、面倒だな……。\nじゃあこんなもんか？
219 = "あー、面倒だな……。\\nじゃあこんなもんか？"

# アクア
# ひゃっ！？　あははははは！\nくすぐったいったら！
258 = "ひゃっ！？　あははははは！\\nくすぐったいったら！"

# カズマ
# 加減が難しいな……よっ、これでどうだ！
284 = "加減が難しいな……よっ、これでどうだ！"

# アクア
# ひゃぁぁぁぁ！！
257 = "ひゃぁぁぁぁ！！"

# カズマ
# んしょ。
272 = "んしょ。"

# アクア
# あははははは！
217 = "あははははは！"

# カズマ
# そりゃ！
240 = "そりゃ！"

# アクア
# ひぅあひゃぁ！
256 = "ひぅあひゃぁ！"

# カズマ
# お前、面白いな。
231 = "お前、面白いな。"

# アクア
# こっちはちっとも面白くないわよ！
234 = "こっちはちっとも面白くないわよ！"

# アクア
# もう、足の裏が赤くなっちゃってるし。\nふーふー。
264 = "もう、足の裏が赤くなっちゃってるし。\\nふーふー。"

# カズマ
# って、おい、お前にははじらいってもんが\nないのか！
250 = "って、おい、お前にははじらいってもんが\\nないのか！"

# アクア
# えー、何がよー。
228 = "えー、何がよー。"

# カズマ
# いや、だから、そんな足を広げたら！
222 = "いや、だから、そんな足を広げたら！"

# アクア
# もうやだ、爪の跡がついちゃってるし。
265 = "もうやだ、爪の跡がついちゃってるし。"

# カズマ
# それで、どうすんだよ。\nマッサージはまだ必要なのか？
242 = "それで、どうすんだよ。\\nマッサージはまだ必要なのか？"

# アクア
# 当然でしょ！\nでも、痛くしたら怒るんだからね！
287 = "当然でしょ！\\nでも、痛くしたら怒るんだからね！"

# カズマ
# なるほど、くすぐったいのはいいんだな。
254 = "なるほど、くすぐったいのはいいんだな。"

# アクア
# それもダメ！
244 = "それもダメ！"

# カズマ
# わかってるよ。
269 = "わかってるよ。"

# アクア
# あ～、んふ～、いい感じよ。\n幸せだわ～。
220 = "あ～、んふ～、いい感じよ。\\n幸せだわ～。"

# カズマ
# それはどうも。
243 = "それはどうも。"

# アクア
# んんんん～～～～、そこそこそこ。\nカズマ、マッサージの才能があるんじゃない？
273 = "んんんん～～～～、そこそこそこ。\\nカズマ、マッサージの才能があるんじゃない？"

# カズマ
# なあ、そんなことよりも、アクア。
253 = "なあ、そんなことよりも、アクア。"

# アクア
# ん、何？
270 = "ん、何？"

# カズマ
# そろそろやめたいんだが……。
245 = "そろそろやめたいんだが……。"

# アクア
# どうして？
252 = "どうして？"

# カズマ
# いやだってもう、１時間くらいやってるし。
224 = "いやだってもう、１時間くらいやってるし。"

# アクア
# それがどうしてやめたい理由になるのかしら？
241 = "それがどうしてやめたい理由になるのかしら？"

# カズマ
# 俺の手がどういう状態か簡単に想像できますよね！
283 = "俺の手がどういう状態か簡単に想像できますよね！"

# アクア
# えーと……正直興味無いわ。
229 = "えーと……正直興味無いわ。"

# カズマ（Ｍ）
# display as カズマ
# （こっ、こいつっ……）
301 = "（こっ、こいつっ……）"

# カズマ（Ｍ）
# display as カズマ
# （こうなったらっ、くすぐってやる！）
300 = "（こうなったらっ、くすぐってやる！）"

# カズマ
# うりゃ、くらえっ！
225 = "うりゃ、くらえっ！"

# アクア
# あはははは、ちょっと待って！\n何やってるのよ！　くすぐったいったら！！
216 = "あはははは、ちょっと待って！\\n何やってるのよ！　くすぐったいったら！！"

# カズマ
# ただのマッサージですよ？
246 = "ただのマッサージですよ？"

# アクア
# ウソつかないでよ！　どう見たってくすぐってる\nじゃないっ！\nやーーめーーてーー！！
275 = "ウソつかないでよ！　どう見たってくすぐってる\\nじゃないっ！\\nやーーめーーてーー！！"

# カズマ
# いやいや、今まで強くやってたのを\n優しくやり直しているだけでくすぐったく\n感じてるだけだよ。
223 = "いやいや、今まで強くやってたのを\\n優しくやり直しているだけでくすぐったく\\n感じてるだけだよ。"

# アクア
# 絶対ウソよぉぉぉぉ！\nあはははは、お腹がよじれるぅ！！
294 = "絶対ウソよぉぉぉぉ！\\nあはははは、お腹がよじれるぅ！！"

# カズマ
# ほーら、これはどうだ？
261 = "ほーら、これはどうだ？"

# アクア
# あはっ、あはははっ！\nくぅ、くぅぅ、い、いい加減にしてよね！
215 = "あはっ、あはははっ！\\nくぅ、くぅぅ、い、いい加減にしてよね！"

# カズマ（Ｍ）
# display as カズマ
# （くそっ、思いっきり足つぼを押してやる！）
298 = "（くそっ、思いっきり足つぼを押してやる！）"

# カズマ
# せーのっ！　うりゃぁぁぁぁ！！！
239 = "せーのっ！　うりゃぁぁぁぁ！！！"

# アクア
# ちょ、ちょっとっ、痛い痛い痛いーーーー！！
248 = "ちょ、ちょっとっ、痛い痛い痛いーーーー！！"

# カズマ
# 痛いのはそれだけ凝ってるって証拠だ。\nほぐれるまで我慢しろ。
290 = "痛いのはそれだけ凝ってるって証拠だ。\\nほぐれるまで我慢しろ。"

# アクア
# 絶対嘘！　わざと痛くしてるんでしょ！
295 = "絶対嘘！　わざと痛くしてるんでしょ！"

# カズマ
# いいえ、そんなことはありませんよ？
221 = "いいえ、そんなことはありませんよ？"

# アクア
# 痛いっ、お願いだから、やめてーーーー！！
289 = "痛いっ、お願いだから、やめてーーーー！！"

# カズマ
# ふぅ、いい仕事をしたぜ。
259 = "ふぅ、いい仕事をしたぜ。"

# アクア
# 何が良い仕事よ！\n本当に天罰を与えるわよ！
281 = "何が良い仕事よ！\\n本当に天罰を与えるわよ！"

# カズマ
# こうなったら、この足を凝視してやる。
233 = "こうなったら、この足を凝視してやる。"

# アクア
# あら、もしかして、私の足の虜になっちゃったの？
218 = "あら、もしかして、私の足の虜になっちゃったの？"

# カズマ
# ジーーーー……。
280 = "ジーーーー……。"

# アクア
# カズマの気持ちはよーくわかるわ。\nでもね、それはただのセクハラ……。
278 = "カズマの気持ちはよーくわかるわ。\\nでもね、それはただのセクハラ……。"

# カズマ
# ジーーーー……。
# 280 = "ジーーーー……。"

# アクア
# ねえ、カズマ……聞いてる？
255 = "ねえ、カズマ……聞いてる？"

# カズマ
# ジーーーー……。
# 280 = "ジーーーー……。"

# アクア
# さてはあんた、その目で私を汚すつもりね！！
237 = "さてはあんた、その目で私を汚すつもりね！！"

# カズマ
# ジーーーー……。
# 280 = "ジーーーー……。"

# アクア
# ちょ、ちょっとやめなさいよ！
249 = "ちょ、ちょっとやめなさいよ！"

# カズマ
# ジーーーー……。
# 280 = "ジーーーー……。"

# アクア
# もう、いいかげんにしなさいったらっ！
262 = "もう、いいかげんにしなさいったらっ！"

# カズマ
# わかった、悪かったよ。\nそんな怒るなって。
267 = "わかった、悪かったよ。\\nそんな怒るなって。"

# アクア
# もう、こんなお仕置き頼むんじゃなかったわ。
263 = "もう、こんなお仕置き頼むんじゃなかったわ。"

# カズマ
# でも、足のだるさはなくなったんじゃないか？
251 = "でも、足のだるさはなくなったんじゃないか？"

# アクア
# あっ、まるで羽が生えたみたいに軽くなってる！
214 = "あっ、まるで羽が生えたみたいに軽くなってる！"

# カズマ
# だろー？
247 = "だろー？"

[selections]
232 = "くすぐってやる"
288 = "思いっきり足つぼを押してやる"
235 = "この足を凝視してやる！"
