# rew_b01.txt.scn

[info]
223 = "rew_b01"

[characters]
293 = "めぐみん"
305 = "カズマ"
307 = "カズマ（Ｍ）"

[character_subs]
# 305 = "カズマ"

[script]
# lines: 88

# めぐみん
# カズマ、私にこのような格好をさせて、\n一体何をしようというのです？
306 = "カズマ、私にこのような格好をさせて、\\n一体何をしようというのです？"

# カズマ
# なんだ、めぐみんともあろう者が、\nわからないのか？
287 = "なんだ、めぐみんともあろう者が、\\nわからないのか？"

# めぐみん
# 残念ながらサッパリです。\nいえ、想像もしたくないと言った方が\n正しいかもしれません。
327 = "残念ながらサッパリです。\\nいえ、想像もしたくないと言った方が\\n正しいかもしれません。"

# カズマ
# では、めぐみんの想像をはるかに超える\nご褒美を要求してやろう！
276 = "では、めぐみんの想像をはるかに超える\\nご褒美を要求してやろう！"

# めぐみん
# ま、まさか、この私にいかがわしいことを！？
292 = "ま、まさか、この私にいかがわしいことを！？"

# カズマ
# するわけないだろ。\n俺をなんだと思ってるんだ。
264 = "するわけないだろ。\\n俺をなんだと思ってるんだ。"

# めぐみん
# 無意識にパンツを盗む変態でしょうか。
329 = "無意識にパンツを盗む変態でしょうか。"

# カズマ
# それはマジックアイテムのせいだろ！
269 = "それはマジックアイテムのせいだろ！"

# めぐみん
# 本当にそうなのですか？\n正直、疑わしいですよ。
326 = "本当にそうなのですか？\\n正直、疑わしいですよ。"

# カズマ（Ｍ）
# display as カズマ
# （まったく。\n　俺がどうしてこんな冤罪を被らないと\n　いけないんだ……）
358 = "（まったく。\\n　俺がどうしてこんな冤罪を被らないと\\n　いけないんだ……）"

# めぐみん
# それで、結局私に何をさせたいのです？
267 = "それで、結局私に何をさせたいのです？"

# カズマ
# あー、それなんだけど、いざ何かしてもらおうと\n考えたら逆に何も思いつかないもんだ。\n早い話、ノープランだ。
248 = "あー、それなんだけど、いざ何かしてもらおうと\\n考えたら逆に何も思いつかないもんだ。\\n早い話、ノープランだ。"

# めぐみん
# 胸を張って言うことですか？\nこんな格好までさせておいて。
351 = "胸を張って言うことですか？\\nこんな格好までさせておいて。"

# カズマ
# そうだ、めぐみんが提案してくれよ。
266 = "そうだ、めぐみんが提案してくれよ。"

# めぐみん
# ふむ、確かにそれならいかがわしいことをされる\n心配が減りますね。
290 = "ふむ、確かにそれならいかがわしいことをされる\\n心配が減りますね。"

# カズマ（Ｍ）
# display as カズマ
# （いやだから、そんなことしないって……）
357 = "（いやだから、そんなことしないって……）"

# めぐみん
# でも、ご褒美だから、カズマが喜ぶ何かじゃないと\nいけない……それなら……！
277 = "でも、ご褒美だから、カズマが喜ぶ何かじゃないと\\nいけない……それなら……！"

# カズマ
# おっ、何をするか決まったか？
257 = "おっ、何をするか決まったか？"

# めぐみん
# 膝枕です。\n可愛い女の子の膝枕は男の夢という話を\n聞いたことがあります。
352 = "膝枕です。\\n可愛い女の子の膝枕は男の夢という話を\\n聞いたことがあります。"

# カズマ
# 確かに間違ってはいない。\n間違ってはいないけど……。
350 = "確かに間違ってはいない。\\n間違ってはいないけど……。"

# めぐみん
# なんですかその目は！\n私では不服だと言うのですか！
288 = "なんですかその目は！\\n私では不服だと言うのですか！"

# カズマ
# 不服ではないんだけど……。\n何も思いつかないのも事実だし、\n仕方がないから今回はそれで手を打つか。
312 = "不服ではないんだけど……。\\n何も思いつかないのも事実だし、\\n仕方がないから今回はそれで手を打つか。"

# めぐみん
# 妥協ですか！？\n妥協で私の膝枕を満喫しようというのですか！？
316 = "妥協ですか！？\\n妥協で私の膝枕を満喫しようというのですか！？"

# カズマ
# そんなことないって。\nほら、早くしないと日が暮れちゃうぞ。
271 = "そんなことないって。\\nほら、早くしないと日が暮れちゃうぞ。"

# めぐみん
# わ、わかってますから、\nそう急かさないでください！
302 = "わ、わかってますから、\\nそう急かさないでください！"

# めぐみん
# 言った手前、やりますが……。\nけ、け、結構、照れくさいんですよ。
354 = "言った手前、やりますが……。\\nけ、け、結構、照れくさいんですよ。"

# めぐみん
# ちょぉぉ！　カズマ！　な、なんですかこれは！
274 = "ちょぉぉ！　カズマ！　な、なんですかこれは！"

# カズマ
# 何って膝枕だろ？\nおかしなことを言うなー、めぐみんは。
314 = "何って膝枕だろ？\\nおかしなことを言うなー、めぐみんは。"

# めぐみん
# おかしい？　私がおかしい？\nどう考えてもおかしいのは\nカズマですよね！
256 = "おかしい？　私がおかしい？\\nどう考えてもおかしいのは\\nカズマですよね！"

# カズマ
# おいおい、どうして俺がおかしいんだ？\nちゃんと理由を説明してくれよ。
255 = "おいおい、どうして俺がおかしいんだ？\\nちゃんと理由を説明してくれよ。"

# めぐみん
# 膝枕は普通、仰向けにするもの、\n俯せでする人間がどこにいるというのです！？
353 = "膝枕は普通、仰向けにするもの、\\n俯せでする人間がどこにいるというのです！？"

# カズマ
# ここにいるな。
260 = "ここにいるな。"

# めぐみん
# こんな真似をするのはカズマくらいですよ！
262 = "こんな真似をするのはカズマくらいですよ！"

# カズマ
# いやいや、\n俺の国じゃこれが正式な作法なんだ。
251 = "いやいや、\\n俺の国じゃこれが正式な作法なんだ。"

# めぐみん
# なるほど、そんな国だから、カズマのような\n変態が生まれるんですね。
286 = "なるほど、そんな国だから、カズマのような\\n変態が生まれるんですね。"

# カズマ
# ほほう、そういうことを言うのか。
291 = "ほほう、そういうことを言うのか。"

# めぐみん
# な、なんですか……。
285 = "な、なんですか……。"

# カズマ
# めぐみんには、我が国の作法をもっと教える必要が\nありそうだな！
294 = "めぐみんには、我が国の作法をもっと教える必要が\\nありそうだな！"

# カズマ
# スー……ハー……スー……ハー……。
309 = "スー……ハー……スー……ハー……。"

# めぐみん
# ちょぉぉぉぉおっ！！\nどうしてスーハースーハーしてるんですか！？
273 = "ちょぉぉぉぉおっ！！\\nどうしてスーハースーハーしてるんですか！？"

# カズマ
# どうしてって、これがこの膝枕の作法だからだよ。\nスー……ハー……スー……ハー……。
282 = "どうしてって、これがこの膝枕の作法だからだよ。\\nスー……ハー……スー……ハー……。"

# めぐみん
# や、やめてください、\nみ、みんなに、言いつけますよ！
297 = "や、やめてください、\\nみ、みんなに、言いつけますよ！"

# カズマ
# おや、どうしてだい？\nもしかして、この作法の何かを、\nいかがわしいと思っているのかな？
258 = "おや、どうしてだい？\\nもしかして、この作法の何かを、\\nいかがわしいと思っているのかな？"

# めぐみん
# うぐっ……。
252 = "うぐっ……。"

# カズマ
# ボクはめぐみんの膝に癒されてるだけだよ。\nそれなのに、いかがわしいなんて、\nおかしな話だなー。
311 = "ボクはめぐみんの膝に癒されてるだけだよ。\\nそれなのに、いかがわしいなんて、\\nおかしな話だなー。"

# めぐみん
# いかがわしいなんて思ってませんよ！
250 = "いかがわしいなんて思ってませんよ！"

# めぐみん
# でも、なんか恥ずかしいので、スーハーするのは、\nやめてください。
278 = "でも、なんか恥ずかしいので、スーハーするのは、\\nやめてください。"

# カズマ
# スゥゥゥゥゥゥゥ～～～～～！！
308 = "スゥゥゥゥゥゥゥ～～～～～！！"

# めぐみん
# やめてくださいって言ってるでしょ！
298 = "やめてくださいって言ってるでしょ！"

# カズマ
# 痛っ！！
333 = "痛っ！！"

# カズマ
# どりゃああああああああ！！
283 = "どりゃああああああああ！！"

# めぐみん
# ちょっ！？\nな、何をしているんですか！？
275 = "ちょっ！？\\nな、何をしているんですか！？"

# カズマ
# ん？　顔をグリグリしてるんだが？
303 = "ん？　顔をグリグリしてるんだが？"

# めぐみん
# 当然のように言わないでください！
320 = "当然のように言わないでください！"

# カズマ
# これが俺の国の作法だぞ。\n当然のことを当然と言って何が悪いんだ。\nうりゃああああああああ！！
261 = "これが俺の国の作法だぞ。\\n当然のことを当然と言って何が悪いんだ。\\nうりゃああああああああ！！"

# めぐみん
# 顔が食い込みますっ！\n太ももの間にグリグリ入っちゃってますから！
355 = "顔が食い込みますっ！\\n太ももの間にグリグリ入っちゃってますから！"

# カズマ
# それの何が悪いのか！
268 = "それの何が悪いのか！"

# めぐみん
# 悪いに決まってるでしょう！\n常識的に考えて！！
323 = "悪いに決まってるでしょう！\\n常識的に考えて！！"

# カズマ
# 常識！？\nめぐみんには言われたくない！\n言われたくありませんわ！
318 = "常識！？\\nめぐみんには言われたくない！\\n言われたくありませんわ！"

# めぐみん
# な、なにおう！\nカズマは私に常識が無いと言うんですか！
284 = "な、なにおう！\\nカズマは私に常識が無いと言うんですか！"

# カズマ
# え、お前まさか、\n自分が常識人だとでも思ってたの？
253 = "え、お前まさか、\\n自分が常識人だとでも思ってたの？"

# めぐみん
# 当然です！
319 = "当然です！"

# カズマ
# フッ、そうだな。\n人間案外自分のことは見えないもんだ。\nドンマイ！
310 = "フッ、そうだな。\\n人間案外自分のことは見えないもんだ。\\nドンマイ！"

# めぐみん
# 無性に腹が立ちますね！
328 = "無性に腹が立ちますね！"

# カズマ
# でもあれだ。\nさすが女の子だけあって柔らかいよな、\n寝心地自体は最高だ！
279 = "でもあれだ。\\nさすが女の子だけあって柔らかいよな、\\n寝心地自体は最高だ！"

# カズマ
# あ～、明日の朝までこうしていたい。
249 = "あ～、明日の朝までこうしていたい。"

# めぐみん
# そ、そんなことは絶対に嫌ですよ！
265 = "そ、そんなことは絶対に嫌ですよ！"

# カズマ
# 痛たっ、冗談だって！！
332 = "痛たっ、冗談だって！！"

# カズマ
# よーし、膝枕の感想を言ってやろう。
301 = "よーし、膝枕の感想を言ってやろう。"

# めぐみん
# どうしてそうなるんですか！？
281 = "どうしてそうなるんですか！？"

# カズマ
# 与えられた優しさに、感謝の言葉を返すのが、\nボクの国の礼儀であり作法だからだよ。
313 = "与えられた優しさに、感謝の言葉を返すのが、\\nボクの国の礼儀であり作法だからだよ。"

# めぐみん
# それは素晴らしい文化だと思いますが、\n感想はいりません！
270 = "それは素晴らしい文化だと思いますが、\\n感想はいりません！"

# カズマ
# めぐみんは、俺を感謝の言葉一つ言えない、\n不作法な人間にしたいのか！
295 = "めぐみんは、俺を感謝の言葉一つ言えない、\\n不作法な人間にしたいのか！"

# めぐみん
# くぅぅぅ～～～～っ！\nわ、わかりました。\nでも、手短にすませてくださいね。
259 = "くぅぅぅ～～～～っ！\\nわ、わかりました。\\nでも、手短にすませてくださいね。"

# カズマ
# よし、じゃあ、言うぞ！
299 = "よし、じゃあ、言うぞ！"

# めぐみん
# ど、どうぞ！
280 = "ど、どうぞ！"

# カズマ
# 普通。
325 = "普通。"

# めぐみん
# え？
254 = "え？"

# カズマ
# だから、普通だ。
272 = "だから、普通だ。"

# めぐみん
# あの、カズマ。\n手短にとは言いましたが、もう少し長くしても\nいいんですよ？
247 = "あの、カズマ。\\n手短にとは言いましたが、もう少し長くしても\\nいいんですよ？"

# カズマ
# じゃあ……可も無く不可も無く普通だ。
263 = "じゃあ……可も無く不可も無く普通だ。"

# めぐみん
# イラッ！
304 = "イラッ！"

# カズマ
# 痛たっ、なんで叩くんだよ！
331 = "痛たっ、なんで叩くんだよ！"

# めぐみん
# もう、ご褒美はお終いです！\n早くっ、頭をっ、どけてください！
296 = "もう、ご褒美はお終いです！\\n早くっ、頭をっ、どけてください！"

# カズマ
# 痛いっ、いたたたた！　わかったよ！
330 = "痛いっ、いたたたた！　わかったよ！"

# めぐみん
# はぁぁ……なんかドッと疲れました。
289 = "はぁぁ……なんかドッと疲れました。"

# カズマ
# よし、今度は俺が膝枕をしてやろう！
300 = "よし、今度は俺が膝枕をしてやろう！"

# めぐみん
# 必要ありませんよ！
321 = "必要ありませんよ！"

[selections]
322 = "思いっきり呼吸をしよう"
356 = "顔をグリグリと動かそう"
324 = "感想を言おう"
