# rew_b09.txt.scn

[info]
232 = "rew_b09"

[characters]
301 = "めぐみん"
315 = "カズマ（Ｍ）"
314 = "カズマ"

[character_subs]
# 314 = "カズマ"

[script]
# lines: 105

# めぐみん
# あの、カズマ、\nお仕置きを考えたのですが……。
259 = "あの、カズマ、\\nお仕置きを考えたのですが……。"

# カズマ（Ｍ）
# display as カズマ
# （なんだ、めぐみんのやつ顔を赤くして\n　モジモジと……）
364 = "（なんだ、めぐみんのやつ顔を赤くして\\n　モジモジと……）"

# カズマ
# まさか、一緒に風呂に入って、\n背中を洗って欲しいって言うんじゃないだろうな？
297 = "まさか、一緒に風呂に入って、\\n背中を洗って欲しいって言うんじゃないだろうな？"

# めぐみん
# なっ！？\nそれはご褒美であって、\nお仕置きではないでしょう！
292 = "なっ！？\\nそれはご褒美であって、\\nお仕置きではないでしょう！"

# めぐみん
# だいたい、何をどうしたら\nそんな発想に行きつくんですか。
283 = "だいたい、何をどうしたら\\nそんな発想に行きつくんですか。"

# カズマ
# やけに恥ずかしそうにしてるから\nそうなのかと推理したんだよ。
304 = "やけに恥ずかしそうにしてるから\\nそうなのかと推理したんだよ。"

# めぐみん
# まるで見当違いな推理ですね。
299 = "まるで見当違いな推理ですね。"

# カズマ
# それで？　俺に何をさせたいんだ。
282 = "それで？　俺に何をさせたいんだ。"

# めぐみん
# 実は……お姫様抱っこに興味があるんです！
326 = "実は……お姫様抱っこに興味があるんです！"

# カズマ（Ｍ）
# display as カズマ
# （これは予想もしなかった言葉が飛び出したな）
361 = "（これは予想もしなかった言葉が飛び出したな）"

# めぐみん
# 最近読み始めた恋愛小説の中で、\nお姫様が勇者にしてもらう一説があるのですが――
332 = "最近読み始めた恋愛小説の中で、\\nお姫様が勇者にしてもらう一説があるのですが――"

# めぐみん
# それがなんとも素晴らしくて\nたまらないのです！！
280 = "それがなんとも素晴らしくて\\nたまらないのです！！"

# カズマ
# それで自分も体験してみたくなったわけか。
281 = "それで自分も体験してみたくなったわけか。"

# めぐみん
# つまりそういうことなのですよ！
286 = "つまりそういうことなのですよ！"

# カズマ
# わ、わかったからっ！\n顔を近づけるな！
306 = "わ、わかったからっ！\\n顔を近づけるな！"

# めぐみん
# というわけで、ぜひお姫様抱っこを\n体験させてください！
287 = "というわけで、ぜひお姫様抱っこを\\n体験させてください！"

# カズマ
# するのは構わんが場所を移さないか？
274 = "するのは構わんが場所を移さないか？"

# カズマ
# もししているところをアクアたちに見られたら、\n間違いなく冷やかされるだろ。
303 = "もししているところをアクアたちに見られたら、\\n間違いなく冷やかされるだろ。"

# めぐみん
# 確かにそれは言えますね。
351 = "確かにそれは言えますね。"

# めぐみん
# さあ、カズマ！　私を抱くがいいです！
271 = "さあ、カズマ！　私を抱くがいいです！"

# カズマ
# 誤解を生むような言い方はやめろ！
355 = "誤解を生むような言い方はやめろ！"

# めぐみん
# ん？　誤解とはなんです？
312 = "ん？　誤解とはなんです？"

# カズマ
# そこは突っ込まなくていいからさ……。
277 = "そこは突っ込まなくていいからさ……。"

# めぐみん
# なんですか、煮え切らないですね。\n抱くのか、抱かないのか、\n男ならすぱっと決めたらどうなのです。
293 = "なんですか、煮え切らないですね。\\n抱くのか、抱かないのか、\\n男ならすぱっと決めたらどうなのです。"

# カズマ（Ｍ）
# display as カズマ
# （ああもう、つっこむのもめんどくさい）
358 = "（ああもう、つっこむのもめんどくさい）"

# めぐみん
# まあ、拒否をするなら、\n別のお仕置きを考える必要がありますが……。
296 = "まあ、拒否をするなら、\\n別のお仕置きを考える必要がありますが……。"

# カズマ
# わかった！　やりますっ！\nやらせていただきますよ、お姫様！
310 = "わかった！　やりますっ！\\nやらせていただきますよ、お姫様！"

# めぐみん
# んふ～、いい返事ですよ、カズマ。
311 = "んふ～、いい返事ですよ、カズマ。"

# めぐみん
# お、おお、おおー！！
264 = "お、おお、おおー！！"

# めぐみん
# これはなんというか、予想以上にいいものですね！
270 = "これはなんというか、予想以上にいいものですね！"

# カズマ
# そりゃよかった。\nここまでやって期待外れじゃ報われないからな。
279 = "そりゃよかった。\\nここまでやって期待外れじゃ報われないからな。"

# めぐみん
# しかし、少々恥ずかしいですね。
272 = "しかし、少々恥ずかしいですね。"

# カズマ
# だったらもうお終いにしよう。
284 = "だったらもうお終いにしよう。"

# めぐみん
# いいえ、もったいないのでもう少しお願いします。\nこんな機会滅多にありませんから！
261 = "いいえ、もったいないのでもう少しお願いします。\\nこんな機会滅多にありませんから！"

# カズマ（Ｍ）
# display as カズマ
# （魔力切れのめぐみんをおぶるのは慣れっこだけど、\n　面と向かう形で抱えるのは初めてだな）
374 = "（魔力切れのめぐみんをおぶるのは慣れっこだけど、\\n　面と向かう形で抱えるのは初めてだな）"

# カズマ（Ｍ）
# display as カズマ
# （やばい、なんか意識したとたん\n　俺まで恥ずかしくなってきたぞ）
366 = "（やばい、なんか意識したとたん\\n　俺まで恥ずかしくなってきたぞ）"

# めぐみん
# あの、恥ずかしいので、\nあまりジロジロと見ないでくれませんか。
260 = "あの、恥ずかしいので、\\nあまりジロジロと見ないでくれませんか。"

# カズマ
# あ、悪い、つい……。
257 = "あ、悪い、つい……。"

# カズマ（Ｍ）
# display as カズマ
# （ついってなんだ俺！？）
363 = "（ついってなんだ俺！？）"

# めぐみん
# せっかくこんなチャンスに恵まれたんです。\nもうひとつお願いがあります。
275 = "せっかくこんなチャンスに恵まれたんです。\\nもうひとつお願いがあります。"

# カズマ
# キスでもすればいいのか？
316 = "キスでもすればいいのか？"

# めぐみん
# な、何を言ってるんですか！\nそんなわけないじゃないですか！
290 = "な、何を言ってるんですか！\\nそんなわけないじゃないですか！"

# カズマ
# 冗談だよ、真に受けるなって。\nそれで次は何をしろって？
322 = "冗談だよ、真に受けるなって。\\nそれで次は何をしろって？"

# めぐみん
# ちょっと言ってもらいたいセリフが\nあるのですが――\n耳を貸してください。
285 = "ちょっと言ってもらいたいセリフが\\nあるのですが――\\n耳を貸してください。"

# カズマ
# ２人きりなんだから\nそのまま言えばいいだろ。
375 = "２人きりなんだから\\nそのまま言えばいいだろ。"

# めぐみん
# 恥ずかしいじゃないですか。
330 = "恥ずかしいじゃないですか。"

# カズマ（Ｍ）
# display as カズマ
# （耳元で囁いてもなにも変わらないと思うが、\n　ここは素直に従っておくか）
373 = "（耳元で囁いてもなにも変わらないと思うが、\\n　ここは素直に従っておくか）"

# カズマ
# わかったよ。\nそれで、何を言えって？
307 = "わかったよ。\\nそれで、何を言えって？"

# めぐみん
# ゴニョゴニョゴニョゴニョゴニョ……、\nゴニョゴニョゴニョゴニョゴニョ……。
317 = "ゴニョゴニョゴニョゴニョゴニョ……、\\nゴニョゴニョゴニョゴニョゴニョ……。"

# カズマ
# 待て！\nなんだその恥ずかしいセリフは！？
328 = "待て！\\nなんだその恥ずかしいセリフは！？"

# めぐみん
# 例の小説の中で勇者が姫に言うセリフです。\nぜひお願いします。
321 = "例の小説の中で勇者が姫に言うセリフです。\\nぜひお願いします。"

# カズマ（Ｍ）
# display as カズマ
# （なんて汚れのないキラキラした瞳で\n　見つめてるんだ。\n　よほど好きなシーンなんだろうな）
365 = "（なんて汚れのないキラキラした瞳で\\n　見つめてるんだ。\\n　よほど好きなシーンなんだろうな）"

# カズマ（Ｍ）
# display as カズマ
# （仕方がない……ごねて揉めるのも面倒だし、\n　俺が少しの間我慢すればすむ話か）
368 = "（仕方がない……ごねて揉めるのも面倒だし、\\n　俺が少しの間我慢すればすむ話か）"

# カズマ
# わかったよ。ご要望に応えてやる。\n特別大サービスだからな？\nお仕置きじゃなきゃ絶対に言わないぞ。
308 = "わかったよ。ご要望に応えてやる。\\n特別大サービスだからな？\\nお仕置きじゃなきゃ絶対に言わないぞ。"

# めぐみん
# よ、よろしくお願いします！
305 = "よ、よろしくお願いします！"

# カズマ（Ｍ）
# display as カズマ
# （期待に満ちた顔してんな……\n　こっちは恥ずかしくて死にそうだってのに）
371 = "（期待に満ちた顔してんな……\\n　こっちは恥ずかしくて死にそうだってのに）"

# カズマ（Ｍ）
# display as カズマ
# （ただ普通に言うだけじゃつまらないな、\n　どうやって言おう？）
362 = "（ただ普通に言うだけじゃつまらないな、\\n　どうやって言おう？）"

# カズマ（Ｍ）
# display as カズマ
# （俺だけが恥ずかしい思いをするのは\n　なんか面白くない、\n　こうなったら顔をガン見して言ってやる）
370 = "（俺だけが恥ずかしい思いをするのは\\n　なんか面白くない、\\n　こうなったら顔をガン見して言ってやる）"

# めぐみん
# カ、カズマ……顔が近いですよ？
313 = "カ、カズマ……顔が近いですよ？"

# カズマ
# おお、姫よ。\n貴女の声は春風よりも軽やかで\n清流のように心に染み渡る。
265 = "おお、姫よ。\\n貴女の声は春風よりも軽やかで\\n清流のように心に染み渡る。"

# カズマ
# その瞳には夜空の星々すらも\n嫉妬するほどの輝きを湛え\nその唇は満開の花畑よりもなお色鮮やか。
278 = "その瞳には夜空の星々すらも\\n嫉妬するほどの輝きを湛え\\nその唇は満開の花畑よりもなお色鮮やか。"

# カズマ
# 貴女の微笑みは太陽のように眩しく、\nいつも私の心を照らしてくれる。
356 = "貴女の微笑みは太陽のように眩しく、\\nいつも私の心を照らしてくれる。"

# カズマ
# この身この命、血の一滴、魂が枯れ果てるまで、\n貴女を守り抜くと誓いましょう。
267 = "この身この命、血の一滴、魂が枯れ果てるまで、\\n貴女を守り抜くと誓いましょう。"

# カズマ
# 愛しています。
331 = "愛しています。"

# カズマ（Ｍ）
# display as カズマ
# （ぐわ～、勢いに任せて言ったけど、\n　なんて恥ずかしいんだ！\n　背中にじんましんが！！）
360 = "（ぐわ～、勢いに任せて言ったけど、\\n　なんて恥ずかしいんだ！\\n　背中にじんましんが！！）"

# カズマ（Ｍ）
# display as カズマ
# （痒い！　痒すぎる！\n　そして、めぐみんはどうよ？）
372 = "（痒い！　痒すぎる！\\n　そして、めぐみんはどうよ？）"

# めぐみん
# …………。
256 = "…………。"

# カズマ
# めぐみん？　おーい、どうした？
302 = "めぐみん？　おーい、どうした？"

# めぐみん
# これは、いいですね……。
269 = "これは、いいですね……。"

# カズマ
# どうやら満足してくれたみたいだな。
288 = "どうやら満足してくれたみたいだな。"

# めぐみん
# はい、大変満足です。\n大大、大満足です！
295 = "はい、大変満足です。\\n大大、大満足です！"

# カズマ
# じゃあ、もう終わりでいいな？\nそろそろ腕が痺れて限界だ。
273 = "じゃあ、もう終わりでいいな？\\nそろそろ腕が痺れて限界だ。"

# カズマ（Ｍ）
# display as カズマ
# （俺だけが恥ずかしい思いをするのは\n　なんか面白くない、\n　こうなったら耳元で囁いてやる）
369 = "（俺だけが恥ずかしい思いをするのは\\n　なんか面白くない、\\n　こうなったら耳元で囁いてやる）"

# めぐみん
# な、なんですか？
289 = "な、なんですか？"

# カズマ
# いいからジッとして。
262 = "いいからジッとして。"

# めぐみん
# 耳がこそばゆいですよぉ～。
353 = "耳がこそばゆいですよぉ～。"

# カズマ
# おお、姫よ。\n貴女の声は春風よりも軽やかで\n清流のように心に染み渡る。
# 265 = "おお、姫よ。\\n貴女の声は春風よりも軽やかで\\n清流のように心に染み渡る。"

# カズマ
# その瞳には夜空の星々すらも\n嫉妬するほどの輝きを湛え\nその唇は満開の花畑よりもなお色鮮やか。
# 278 = "その瞳には夜空の星々すらも\\n嫉妬するほどの輝きを湛え\\nその唇は満開の花畑よりもなお色鮮やか。"

# カズマ
# 貴女の微笑みは太陽のように眩しく、\nいつも私の心を照らしてくれる。
# 356 = "貴女の微笑みは太陽のように眩しく、\\nいつも私の心を照らしてくれる。"

# カズマ
# この身この命、血の一滴、魂が枯れ果てるまで、\n貴女を守り抜くと誓いましょう。
# 267 = "この身この命、血の一滴、魂が枯れ果てるまで、\\n貴女を守り抜くと誓いましょう。"

# カズマ
# 愛しています。
# 331 = "愛しています。"

# カズマ（Ｍ）
# display as カズマ
# （ぐわ～、勢いに任せて言ったけど、\n　なんて恥ずかしいんだ！\n　背中にじんましんが！！）
# 360 = "（ぐわ～、勢いに任せて言ったけど、\\n　なんて恥ずかしいんだ！\\n　背中にじんましんが！！）"

# カズマ（Ｍ）
# display as カズマ
# （痒い！　痒すぎる！\n　そして、めぐみんはどうよ？）
# 372 = "（痒い！　痒すぎる！\\n　そして、めぐみんはどうよ？）"

# めぐみん
# 私も……愛しています……。
352 = "私も……愛しています……。"

# カズマ
# め、めぐみん！？
300 = "め、めぐみん！？"

# めぐみん
# あっ、いや！\n今のはカズマに\n言ったわけではありません！
258 = "あっ、いや！\\n今のはカズマに\\n言ったわけではありません！"

# めぐみん
# 姫のセリフですから！\nか、勘違いしないでくださいね！
325 = "姫のセリフですから！\\nか、勘違いしないでくださいね！"

# カズマ
# わかったわかった。
309 = "わかったわかった。"

# カズマ
# じゃあ、もう終わりでいいな？\nそろそろ腕が痺れて限界だ。
# 273 = "じゃあ、もう終わりでいいな？\\nそろそろ腕が痺れて限界だ。"

# カズマ（Ｍ）
# display as カズマ
# （いや、どう言おうと恥ずかしいことに\n　変わりはない……）
359 = "（いや、どう言おうと恥ずかしいことに\\n　変わりはない……）"

# カズマ（Ｍ）
# display as カズマ
# （ダメだ、\n　めぐみんを見ながらなんて\n　不可能だ！）
367 = "（ダメだ、\\n　めぐみんを見ながらなんて\\n　不可能だ！）"

# めぐみん
# なぜ顔を反らすのですか？
291 = "なぜ顔を反らすのですか？"

# カズマ
# これくらい許してくれ！\nいいか？　いくぞ？　いくからな？
268 = "これくらい許してくれ！\\nいいか？　いくぞ？　いくからな？"

# めぐみん
# は、はい。
294 = "は、はい。"

# カズマ
# おお、姫よ。\n貴女の声は春風よりも軽やかで\n清流のように心に染み渡る。
# 265 = "おお、姫よ。\\n貴女の声は春風よりも軽やかで\\n清流のように心に染み渡る。"

# カズマ
# その瞳には夜空の星々すらも\n嫉妬するほどの輝きを湛え\nその唇は満開の花畑よりもなお色鮮やか。
# 278 = "その瞳には夜空の星々すらも\\n嫉妬するほどの輝きを湛え\\nその唇は満開の花畑よりもなお色鮮やか。"

# カズマ
# 貴女の微笑みは太陽のように眩しく、\nいつも私の心を照らしてくれる。
# 356 = "貴女の微笑みは太陽のように眩しく、\\nいつも私の心を照らしてくれる。"

# カズマ
# この身この命、血の一滴、魂が枯れ果てるまで、\n貴女を守り抜くと誓いましょう。
# 267 = "この身この命、血の一滴、魂が枯れ果てるまで、\\n貴女を守り抜くと誓いましょう。"

# カズマ
# 愛しています。
# 331 = "愛しています。"

# カズマ
# こ、これでいいか？
266 = "こ、これでいいか？"

# めぐみん
# 仕方がないですね……、\n及第点としておきましょう。
320 = "仕方がないですね……、\\n及第点としておきましょう。"

# カズマ
# じゃあ、もう終わりでいいな？\nそろそろ腕が痺れて限界だ。
# 273 = "じゃあ、もう終わりでいいな？\\nそろそろ腕が痺れて限界だ。"

# めぐみん
# まだダメですよ！\nもう少し浸らせてください。
298 = "まだダメですよ！\\nもう少し浸らせてください。"

# カズマ
# そ、そんな～……、\n腕が……腕がぁぁぁ～！
276 = "そ、そんな～……、\\n腕が……腕がぁぁぁ～！"

# めぐみん
# うふふふ、癖になってしまうかもです。
263 = "うふふふ、癖になってしまうかもです。"

[selections]
357 = "顔をガン見しながら言ってやろう"
354 = "耳元で囁いてやろう"
329 = "恥ずかしいからそっぽを向こう"
