# rew_f06.txt.scn

[info]
241 = "rew_f06"

[characters]
381 = "ウィズ"
384 = "カズマ"
385 = "カズマ（Ｍ）"

[character_subs]
# 384 = "カズマ"

[script]
# lines: 123

# ウィズ
# わざわざ来ていただいちゃってすみません。
379 = "わざわざ来ていただいちゃってすみません。"

# カズマ
# いや、構わないよ。\nそれで、お仕置きはこの店でやるのか？
310 = "いや、構わないよ。\\nそれで、お仕置きはこの店でやるのか？"

# ウィズ
# あ、はい、マジックアイテムの――
294 = "あ、はい、マジックアイテムの――"

# カズマ
# まさか実験台に！？
372 = "まさか実験台に！？"

# ウィズ
# あ、えっと……。
292 = "あ、えっと……。"

# カズマ
# あれ？　冗談のつもりだったんだけど、\nまさかそうなの？
305 = "あれ？　冗談のつもりだったんだけど、\\nまさかそうなの？"

# ウィズ
# ええとですね。\n頼みたいのはこの箱の中のアイテムを効果ごとに\n整理していただくことなんです。
324 = "ええとですね。\\n頼みたいのはこの箱の中のアイテムを効果ごとに\\n整理していただくことなんです。"

# カズマ
# うわぁ、ごちゃごちゃだな。
319 = "うわぁ、ごちゃごちゃだな。"

# ウィズ
# お恥ずかしい話。\n店の棚に空きが無いからと\nこの箱に置きっ放しにしていたら――
333 = "お恥ずかしい話。\\n店の棚に空きが無いからと\\nこの箱に置きっ放しにしていたら――"

# ウィズ
# その効果を忘れてしまいまして……。
345 = "その効果を忘れてしまいまして……。"

# カズマ
# なあ、ウィズ。
354 = "なあ、ウィズ。"

# ウィズ
# はい、なんでしょう？
360 = "はい、なんでしょう？"

# カズマ
# 置ける場所もないのに仕入れるって\nどうかと思うぞ？
445 = "置ける場所もないのに仕入れるって\\nどうかと思うぞ？"

# ウィズ
# そ、そうですね。\n次からは気をつけます。
343 = "そ、そうですね。\\n次からは気をつけます。"

# カズマ（Ｍ）
# display as カズマ
# （それでもウィズのことだから\n　変なアイテムを買うんだろうな）
453 = "（それでもウィズのことだから\\n　変なアイテムを買うんだろうな）"

# カズマ
# えっと、それで俺にして欲しい事っていうのは、\nアイテム効果を確かめつつ、整理をして欲しいと。
325 = "えっと、それで俺にして欲しい事っていうのは、\\nアイテム効果を確かめつつ、整理をして欲しいと。"

# ウィズ
# あのあの、命に関わるようなアイテムは\n無いはずですので！
300 = "あのあの、命に関わるようなアイテムは\\n無いはずですので！"

# カズマ（Ｍ）
# display as カズマ
# （はず、なのか……）
455 = "（はず、なのか……）"

# ウィズ
# やっぱりこんなお願いはダメですよね？
377 = "やっぱりこんなお願いはダメですよね？"

# カズマ
# いいや、構わないよ。\nでも、変な呪いにかかったら、\n解除料金はウィズがもってくれよ。
308 = "いいや、構わないよ。\\nでも、変な呪いにかかったら、\\n解除料金はウィズがもってくれよ。"

# ウィズ
# はい！　それは当然です！
364 = "はい！　それは当然です！"

# カズマ
# はい、もうひとつ指導！
361 = "はい、もうひとつ指導！"

# ウィズ
# え？　え？
328 = "え？　え？"

# カズマ
# そうやってろくに考えずに返事をするから\nいつまで経っても貧乏なままなの！
344 = "そうやってろくに考えずに返事をするから\\nいつまで経っても貧乏なままなの！"

# ウィズ
# うぅ、それはバニルさんにも良く言われます。
315 = "うぅ、それはバニルさんにも良く言われます。"

# カズマ（Ｍ）
# display as カズマ
# （あいつも色々苦労してるんだな）
449 = "（あいつも色々苦労してるんだな）"

# カズマ
# じゃあ、どれからいく？
341 = "じゃあ、どれからいく？"

# ウィズ
# この指輪からにしましょうか。
339 = "この指輪からにしましょうか。"

# カズマ
# 指輪ぁぁぁ！！　指輪はもうこりごりだぁぁぁ！！
400 = "指輪ぁぁぁ！！　指輪はもうこりごりだぁぁぁ！！"

# ウィズ
# あああ、だ、大丈夫です！　あれほどの魔力はこの\n指輪からは感じませんから！
296 = "あああ、だ、大丈夫です！　あれほどの魔力はこの\\n指輪からは感じませんから！"

# カズマ
# ホントか？　ホントだな？
387 = "ホントか？　ホントだな？"

# ウィズ
# はい、これに関しては大丈夫です！　たぶん。
359 = "はい、これに関しては大丈夫です！　たぶん。"

# カズマ
# たぶんとか言うなよ……。\nまあウィズが言うのなら信じるけど……。\nじゃあ、はめるぞ。
348 = "たぶんとか言うなよ……。\\nまあウィズが言うのなら信じるけど……。\\nじゃあ、はめるぞ。"

# カズマ（Ｍ）
# display as カズマ
# （くっ、何も起こってくれるなよっ！）
451 = "（くっ、何も起こってくれるなよっ！）"

# ウィズ
# ……どうですか？
290 = "……どうですか？"

# カズマ
# いやぁ、特に何も。
311 = "いやぁ、特に何も。"

# ウィズ
# この前のみたいな装着型じゃ無いみたいですね。\nとすると、何かの条件による発動系？
338 = "この前のみたいな装着型じゃ無いみたいですね。\\nとすると、何かの条件による発動系？"

# カズマ
# 発動系？
402 = "発動系？"

# ウィズ
# はい、何らかの条件を満たせば、マジックが発動する\nものですね。何かしてみてもらえますか？
362 = "はい、何らかの条件を満たせば、マジックが発動する\\nものですね。何かしてみてもらえますか？"

# カズマ
# おお、いかにもマジックアイテムっぽい感じだな。\nじゃあまあオーソドックスに、腕を伸ばしたり、\n指を差したり。
329 = "おお、いかにもマジックアイテムっぽい感じだな。\\nじゃあまあオーソドックスに、腕を伸ばしたり、\\n指を差したり。"

# ウィズ
# 出ませんねぇ。\n指輪を擦ってみたらどうでしょう？
391 = "出ませんねぇ。\\n指輪を擦ってみたらどうでしょう？"

# カズマ
# いやいや、魔法のランプじゃないんだから……。\nうん、何も無いな。
312 = "いやいや、魔法のランプじゃないんだから……。\\nうん、何も無いな。"

# ウィズ
# ううーん、どうすれば発動するんでしょう。
316 = "ううーん、どうすれば発動するんでしょう。"

# カズマ（Ｍ）
# display as カズマ
# （……おおっ、ウィズの腕組みで、胸が、胸が溢れん\n　ばかりに！！）
448 = "（……おおっ、ウィズの腕組みで、胸が、胸が溢れん\\n　ばかりに！！）"

# カズマ
# どわぁぁぁぁぁぁぁっ！？
353 = "どわぁぁぁぁぁぁぁっ！？"

# ウィズ
# えっ！？　ど、どうしたんですか、カズマさん！？
327 = "えっ！？　ど、どうしたんですか、カズマさん！？"

# カズマ
# い、今っ、指輪からものすごい電気がビリビリって！
307 = "い、今っ、指輪からものすごい電気がビリビリって！"

# ウィズ
# ええっ！？　カズマさん、どうやって発動させたん\nですか！？
322 = "ええっ！？　カズマさん、どうやって発動させたん\\nですか！？"

# カズマ
# う、その、ちょっと不届きなことを考えていました。
314 = "う、その、ちょっと不届きなことを考えていました。"

# ウィズ
# もっと具体的にお願いします！
376 = "もっと具体的にお願いします！"

# カズマ
# だ、だから、ウィズの……。
349 = "だ、だから、ウィズの……。"

# ウィズ
# 私の？
444 = "私の？"

# カズマ
# おっぱいが……大きいなって。
330 = "おっぱいが……大きいなって。"

# カズマ
# ひんぎゃぁあああああああああ！！
370 = "ひんぎゃぁあああああああああ！！"

# ウィズ
# きっとこれは、カズマさんのような人を\nお仕置きするために作られた\nマジックアイテムなんでしょうね。
334 = "きっとこれは、カズマさんのような人を\\nお仕置きするために作られた\\nマジックアイテムなんでしょうね。"

# カズマ
# お仕置きってレベルの痛みじゃないぞ。
332 = "お仕置きってレベルの痛みじゃないぞ。"

# ウィズ
# ありがとうございます。\nおかげさまで１つ効果がわかりました。
302 = "ありがとうございます。\\nおかげさまで１つ効果がわかりました。"

# カズマ
# あれ、エッチな目で見たことに関しては\nお咎め無し？
303 = "あれ、エッチな目で見たことに関しては\\nお咎め無し？"

# ウィズ
# もう指輪でお仕置きされているじゃないですか。\nさらに私からなんて、カズマさんに悪すぎます。
374 = "もう指輪でお仕置きされているじゃないですか。\\nさらに私からなんて、カズマさんに悪すぎます。"

# カズマ
# ウィズ……。
382 = "ウィズ……。"

# ウィズ
# でも、エッチなのはダメですからね？
351 = "でも、エッチなのはダメですからね？"

# カズマ
# わ、わかりました！
378 = "わ、わかりました！"

# ウィズ
# では次は、この液体をお願いします。
350 = "では次は、この液体をお願いします。"

# カズマ
# うわぁ……いかにも何かありそうと言うか、\nこんなどす黒い液体飲んだら、死ぬんじゃないか。
318 = "うわぁ……いかにも何かありそうと言うか、\\nこんなどす黒い液体飲んだら、死ぬんじゃないか。"

# ウィズ
# 大丈夫です、味見はしました。\n案外悪くない味でしたよ。
394 = "大丈夫です、味見はしました。\\n案外悪くない味でしたよ。"

# カズマ
# それは毒味なのでは……ってかそれで効果がわから\nなかったのか？
347 = "それは毒味なのでは……ってかそれで効果がわから\\nなかったのか？"

# ウィズ
# ええと、規定量以上を飲まないと効果を発揮しない\nみたいでして。
323 = "ええと、規定量以上を飲まないと効果を発揮しない\\nみたいでして。"

# カズマ
# 規定量って薬かーい！\nまあ死ななければいいや。\nんじゃ一気に……ごくごくっ！
447 = "規定量って薬かーい！\\nまあ死ななければいいや。\\nんじゃ一気に……ごくごくっ！"

# カズマ
# うぇ、まるで子供用のシロップだな。
317 = "うぇ、まるで子供用のシロップだな。"

# ウィズ
# あら？　え？　あら？
301 = "あら？　え？　あら？"

# カズマ
# おーい、ウィズー？\nどうした、そんなきょろきょろして。
331 = "おーい、ウィズー？\\nどうした、そんなきょろきょろして。"

# ウィズ
# えっ！？　その声はカズマさん……って、どこに\nいるんですか！？
326 = "えっ！？　その声はカズマさん……って、どこに\\nいるんですか！？"

# カズマ
# ん？　いや別に、ウィズの目の前にいるけど。
380 = "ん？　いや別に、ウィズの目の前にいるけど。"

# ウィズ
# えええ！？　カズマさん、そこにいるんですか？\nあ、ほんとです、何かいます！
321 = "えええ！？　カズマさん、そこにいるんですか？\\nあ、ほんとです、何かいます！"

# カズマ
# あ痛っ！？　た、叩くのは止めろっ！
306 = "あ痛っ！？　た、叩くのは止めろっ！"

# ウィズ
# あっ、す、すみません！
298 = "あっ、す、すみません！"

# カズマ
# すまんウィズ、俺にはわからないんだが、\nもしかして……。
342 = "すまんウィズ、俺にはわからないんだが、\\nもしかして……。"

# ウィズ
# はい、私にカズマさんは見えません。
363 = "はい、私にカズマさんは見えません。"

# カズマ
# いったいどういう意図で作られた物なんだ。
309 = "いったいどういう意図で作られた物なんだ。"

# ウィズ
# 味から察するに子供用ですよね？
393 = "味から察するに子供用ですよね？"

# カズマ
# 確かに甘ったるかったな。
443 = "確かに甘ったるかったな。"

# ウィズ
# もしかしたら、かくれんぼとかで使用することを\n想定した物なのかもしれませんね。
375 = "もしかしたら、かくれんぼとかで使用することを\\n想定した物なのかもしれませんね。"

# ウィズ
# あとは親に怒られたときに隠れるとかにも\n使えそうですし。
299 = "あとは親に怒られたときに隠れるとかにも\\n使えそうですし。"

# カズマ（Ｍ）
# display as カズマ
# （それは反則だろ……）
454 = "（それは反則だろ……）"

# ウィズ
# あれ？\nカズマさん、いらっしゃいます？
304 = "あれ？\\nカズマさん、いらっしゃいます？"

# カズマ（Ｍ）
# display as カズマ
# （ん？　今の状況って実はめちゃくちゃ\n　美味しくないか？）
461 = "（ん？　今の状況って実はめちゃくちゃ\\n　美味しくないか？）"

# ウィズ
# カ、カズマさん？\nもしかして帰っちゃいました？
383 = "カ、カズマさん？\\nもしかして帰っちゃいました？"

# カズマ（Ｍ）
# display as カズマ
# （はは、不安そうにして可愛いな）
456 = "（はは、不安そうにして可愛いな）"

# カズマ（Ｍ）
# display as カズマ
# （よし、それじゃあ――）
460 = "（よし、それじゃあ――）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズをくすぐってやろう！）
462 = "（ウィズをくすぐってやろう！）"

# カズマ
# こちょこちょこちょこちょっ！
337 = "こちょこちょこちょこちょっ！"

# ウィズ
# きゃあっ！？　あっ、あははははっ、\nあっ、やめてっ！　くすぐるの、ダメですよぉ！
335 = "きゃあっ！？　あっ、あははははっ、\\nあっ、やめてっ！　くすぐるの、ダメですよぉ！"

# カズマ
# ははは、悪い悪い。
368 = "ははは、悪い悪い。"

# ウィズ
# はぅ～、アンデットなのに死ぬかと思いました～。
365 = "はぅ～、アンデットなのに死ぬかと思いました～。"

# カズマ（Ｍ）
# display as カズマ
# （よし、ここはちょっと脅かしてみよう！\n　近くまで忍び寄って……）
459 = "（よし、ここはちょっと脅かしてみよう！\\n　近くまで忍び寄って……）"

# カズマ
# ふっ。
371 = "ふっ。"

# ウィズ
# ひゃあぁぁぁぁぁっ！？\nな、何ですかっ、いきなり耳元に息を\n吹きかけないで下さい～～！！
369 = "ひゃあぁぁぁぁぁっ！？\\nな、何ですかっ、いきなり耳元に息を\\n吹きかけないで下さい～～！！"

# カズマ
# はっはっはっ、大成功だ！
366 = "はっはっはっ、大成功だ！"

# ウィズ
# も、もう、カズマさんの意地悪。
373 = "も、もう、カズマさんの意地悪。"

# カズマ（Ｍ）
# display as カズマ
# （この隙に乗じて、家捜しでもしてみようか！）
452 = "（この隙に乗じて、家捜しでもしてみようか！）"

# カズマ（Ｍ）
# display as カズマ
# （もしかしたら、ウィズの部屋でドキドキな体験が\n　出来るかもしれないしな！）
458 = "（もしかしたら、ウィズの部屋でドキドキな体験が\\n　出来るかもしれないしな！）"

# ウィズ
# あ、カズマさん、まさかとは思いますけど、\n勝手に奥へ行こうとしていませんよね？
295 = "あ、カズマさん、まさかとは思いますけど、\\n勝手に奥へ行こうとしていませんよね？"

# カズマ（Ｍ）
# display as カズマ
# （へっ！？　な、なな、なんでわかったんだ？）
457 = "（へっ！？　な、なな、なんでわかったんだ？）"

# ウィズ
# なんでわかったんだって思っていますか？
355 = "なんでわかったんだって思っていますか？"

# カズマ（Ｍ）
# display as カズマ
# （あれ、なんかウィズ怖い……）
450 = "（あれ、なんかウィズ怖い……）"

# ウィズ
# カーズーマーさん。\nいらっしゃるんでしょ？
386 = "カーズーマーさん。\\nいらっしゃるんでしょ？"

# カズマ
# は、はい、すぐ横に控えております。
356 = "は、はい、すぐ横に控えております。"

# ウィズ
# はぁ、よかったです。\n奥に行かれてたら洗濯物が……。
357 = "はぁ、よかったです。\\n奥に行かれてたら洗濯物が……。"

# カズマ
# 洗濯物？
401 = "洗濯物？"

# ウィズ
# あ、いえ、なんでもありませんよ！\nその下着が干してあったりしませんからね！
291 = "あ、いえ、なんでもありませんよ！\\nその下着が干してあったりしませんからね！"

# カズマ
# マジで！
388 = "マジで！"

# ウィズ
# あっ、あっ、勝手に奥へ入ったら怒りますからね！
297 = "あっ、あっ、勝手に奥へ入ったら怒りますからね！"

# カズマ
# はは、そんなことしないって。
367 = "はは、そんなことしないって。"

# ウィズ
# はぁ、ドキドキしちゃいました。
358 = "はぁ、ドキドキしちゃいました。"

# カズマ
# それにしても、これはいったいいつ元に戻るんだ？
346 = "それにしても、これはいったいいつ元に戻るんだ？"

# ウィズ
# 子供用ならそんなに長くは続かないと思いますが。\nあ、でも……。
395 = "子供用ならそんなに長くは続かないと思いますが。\\nあ、でも……。"

# カズマ
# でも？
352 = "でも？"

# ウィズ
# こんな便利なアイテムが安価で投げ売りされている\nなんておかしいですよね？
340 = "こんな便利なアイテムが安価で投げ売りされている\\nなんておかしいですよね？"

# カズマ
# あ、つまり、問題があるから……。
293 = "あ、つまり、問題があるから……。"

# ウィズ
# え、ええと……。
320 = "え、ええと……。"

# カズマ
# 元に……戻るよな？
390 = "元に……戻るよな？"

# ウィズ
# う、うう……。
313 = "う、うう……。"

# カズマ
# 戻るって言ってよ、ウィズさーん！！
399 = "戻るって言ってよ、ウィズさーん！！"

[selections]
336 = "くすぐってやろう"
446 = "脅かしてやろう"
396 = "家捜ししてみよう"
