# rew_a09.txt.scn

[info]
184 = "rew_a09"

[characters]
257 = "アクア"
258 = "カズマ"
260 = "カズマ（Ｍ）"

[character_subs]
# 258 = "カズマ"

[script]
# lines: 79

# アクア
# カズマ！\n寝る私を称える歌を聞かせてちょうだい！
259 = "カズマ！\\n寝る私を称える歌を聞かせてちょうだい！"

# カズマ
# うわっーーーー！？　びっくりした！！\n部屋に入るときはノックぐらいしろって！
215 = "うわっーーーー！？　びっくりした！！\\n部屋に入るときはノックぐらいしろって！"

# アクア
# いいじゃない別に。\nどうせ寝るところだったんでしょ？
214 = "いいじゃない別に。\\nどうせ寝るところだったんでしょ？"

# カズマ
# まあ、そうだけど。\nそれで？　なんか変なこと言ってなかったか？
245 = "まあ、そうだけど。\\nそれで？　なんか変なこと言ってなかったか？"

# アクア
# お仕置きを色々考えたのよ。\nそれで、せっかくだし私を称えさせようかなって\n思ったわけ。
221 = "お仕置きを色々考えたのよ。\\nそれで、せっかくだし私を称えさせようかなって\\n思ったわけ。"

# カズマ
# はぁ、それだったら明日にしてくれ。\n俺はもう眠いんだ。
240 = "はぁ、それだったら明日にしてくれ。\\n俺はもう眠いんだ。"

# アクア
# あんた、何もわかってないわね。
212 = "あんた、何もわかってないわね。"

# カズマ
# 何が……。
264 = "何が……。"

# アクア
# 私はもう多くの信者に称えられなれてるの。
289 = "私はもう多くの信者に称えられなれてるの。"

# カズマ
# へー。
241 = "へー。"

# アクア
# ほ、本当よ！\n嘘じゃないんだからね！
242 = "ほ、本当よ！\\n嘘じゃないんだからね！"

# カズマ
# わかったから、話を先に進めてくれ。
250 = "わかったから、話を先に進めてくれ。"

# アクア
# そんな私が、普通に称えられて満足するわけ\nないでしょ？
229 = "そんな私が、普通に称えられて満足するわけ\\nないでしょ？"

# アクア
# だから、子守歌代わりに、\nカズマに称えて貰おうかなって。
230 = "だから、子守歌代わりに、\\nカズマに称えて貰おうかなって。"

# アクア
# どう？　ナイスアイデアだと思わない！
236 = "どう？　ナイスアイデアだと思わない！"

# カズマ
# 確かに、褒めちぎられて寝るなんて、\nこの上ない贅沢だよな。
288 = "確かに、褒めちぎられて寝るなんて、\\nこの上ない贅沢だよな。"

# アクア
# さっすがカズマ、わかってるじゃない。
224 = "さっすがカズマ、わかってるじゃない。"

# カズマ
# でもこれって、俺に対してお仕置きになってるか？\nなってないだろ。
234 = "でもこれって、俺に対してお仕置きになってるか？\\nなってないだろ。"

# アクア
# そんなの私が気持ちよければ、関係ないわよ。
228 = "そんなの私が気持ちよければ、関係ないわよ。"

# カズマ（Ｍ）
# display as カズマ
# （思いっきりお仕置きの目的を無視してるな）
303 = "（思いっきりお仕置きの目的を無視してるな）"

# アクア
# ほらほら、カズマ。\n早くこっちにいらっしゃいよ。
244 = "ほらほら、カズマ。\\n早くこっちにいらっしゃいよ。"

# カズマ
# ん？
256 = "ん？"

# アクア
# 何、どうかした？
263 = "何、どうかした？"

# カズマ（Ｍ）
# display as カズマ
# （よく考えると、このベッドってシングルサイズ\n　だよな？）
302 = "（よく考えると、このベッドってシングルサイズ\\n　だよな？）"

# アクア
# おーい、カズマさーん。
220 = "おーい、カズマさーん。"

# カズマ（Ｍ）
# display as カズマ
# （それは、つまり……）
296 = "（それは、つまり……）"

# アクア
# カーズーマーさーん、聞こえてますかー？
261 = "カーズーマーさーん、聞こえてますかー？"

# カズマ
# …………。
207 = "…………。"

# アクア
# ねえ、ボーッとしてどうしたのよ？
238 = "ねえ、ボーッとしてどうしたのよ？"

# カズマ（Ｍ）
# display as カズマ
# （うん、ダクネスやウィズならまだしも、\n　こいつじゃ、無理だわ）
292 = "（うん、ダクネスやウィズならまだしも、\\n　こいつじゃ、無理だわ）"

# アクア
# えへへ、ようやく来た。\nさあ、早く私を称えてちょうだい。
218 = "えへへ、ようやく来た。\\nさあ、早く私を称えてちょうだい。"

# カズマ
# うーん、いきなりそう言われてもな。
216 = "うーん、いきなりそう言われてもな。"

# アクア
# 余計な言葉で飾ろうとしないで、\n思ったことをそのまま言えばいいじゃない。
266 = "余計な言葉で飾ろうとしないで、\\n思ったことをそのまま言えばいいじゃない。"

# カズマ
# 邪魔。
290 = "邪魔。"

# アクア
# あんた、称えるの言葉の意味を\n辞書で引いた方がいいんじゃない。
213 = "あんた、称えるの言葉の意味を\\n辞書で引いた方がいいんじゃない。"

# カズマ
# 思ったことをそのまま言えって言ったのは\nお前だろ。
271 = "思ったことをそのまま言えって言ったのは\\nお前だろ。"

# アクア
# もっとキツいお仕置きにしたくなっちゃったかも。
249 = "もっとキツいお仕置きにしたくなっちゃったかも。"

# カズマ
# わかったわかった。\n褒め称えればいいんだろ。
251 = "わかったわかった。\\n褒め称えればいいんだろ。"

# アクア
# それじゃ、よろしくね。
226 = "それじゃ、よろしくね。"

# カズマ
# 嗚呼、美しき我らが女神、アクア様よ！\n……こんな感じでいいのか？
268 = "嗚呼、美しき我らが女神、アクア様よ！\\n……こんな感じでいいのか？"

# アクア
# 思ったよりいい感じじゃない。\nでも、まだ物足りないかしら。
272 = "思ったよりいい感じじゃない。\\nでも、まだ物足りないかしら。"

# アクア
# 感情がこもってないって言うの？\nなんか、取って付けた言い方が気に入らないのよね。
273 = "感情がこもってないって言うの？\\nなんか、取って付けた言い方が気に入らないのよね。"

# カズマ（Ｍ）
# display as カズマ
# （くっ……こいつは……）
293 = "（くっ……こいつは……）"

# カズマ（Ｍ）
# display as カズマ
# （だいたいどうして、添い寝して寝かしつけ\n　なんてやらないといけないんだ！）
297 = "（だいたいどうして、添い寝して寝かしつけ\\n　なんてやらないといけないんだ！）"

# カズマ（Ｍ）
# display as カズマ
# （状況をまったく理解してないみたいだし……）
304 = "（状況をまったく理解してないみたいだし……）"

# カズマ
# なあ、もうちょっと離れろよ。
237 = "なあ、もうちょっと離れろよ。"

# アクア
# えー、この狭いベッドの上で、\nこれ以上離れるなんて不可能じゃない。
219 = "えー、この狭いベッドの上で、\\nこれ以上離れるなんて不可能じゃない。"

# カズマ
# それはそうだけどさ、\nお前は気にならないのか？
227 = "それはそうだけどさ、\\nお前は気にならないのか？"

# アクア
# 何が？
265 = "何が？"

# カズマ
# だから！
232 = "だから！"

# アクア
# あっ、もしかして！！
211 = "あっ、もしかして！！"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、ようやく状況を理解してくれたか）
299 = "（はぁ、ようやく状況を理解してくれたか）"

# アクア
# もしかしてお風呂に入ってないの？\nちょっと、ばっちいからこっち来ないでくれる。
247 = "もしかしてお風呂に入ってないの？\\nちょっと、ばっちいからこっち来ないでくれる。"

# カズマ
# 風呂にはちゃんと入ったよ！
291 = "風呂にはちゃんと入ったよ！"

# カズマ（Ｍ）
# display as カズマ
# （まあ、それがアクアか……）
301 = "（まあ、それがアクアか……）"

# アクア
# ねえねえ、カズマ。
239 = "ねえねえ、カズマ。"

# カズマ
# ん、なんだ？
253 = "ん、なんだ？"

# アクア
# こうやって並んで寝てると、\n昔のこと思い出さない？
223 = "こうやって並んで寝てると、\\n昔のこと思い出さない？"

# カズマ
# ああ、馬小屋生活のことか。
209 = "ああ、馬小屋生活のことか。"

# アクア
# お金を出し合ってシーツを買って、\n寒い夜は凍えそうになって。
222 = "お金を出し合ってシーツを買って、\\n寒い夜は凍えそうになって。"

# アクア
# 散々な毎日だったけど、\nあれはあれで楽しかったわよね。
274 = "散々な毎日だったけど、\\nあれはあれで楽しかったわよね。"

# カズマ
# 二度とあんな生活には戻りたくないけどな。
262 = "二度とあんな生活には戻りたくないけどな。"

# カズマ
# もしかして寂しかったのか？
248 = "もしかして寂しかったのか？"

# アクア
# どうしてよ。
235 = "どうしてよ。"

# カズマ
# ほら、この屋敷意外と広いから、夜とか急に人気が\nないように感じることあるだろ？
243 = "ほら、この屋敷意外と広いから、夜とか急に人気が\\nないように感じることあるだろ？"

# カズマ
# だからもしかしたら\n寂しかったんじゃないのかなーってさ。
231 = "だからもしかしたら\\n寂しかったんじゃないのかなーってさ。"

# アクア
# うーん、たとえ寂しいって思っても\nカズマのところには来ないかしら。
217 = "うーん、たとえ寂しいって思っても\\nカズマのところには来ないかしら。"

# カズマ
# ですよね！
233 = "ですよね！"

# アクア
# んん、むにゃ、なんだか眠くなってきちゃった。
255 = "んん、むにゃ、なんだか眠くなってきちゃった。"

# カズマ
# 寝るなら自分の部屋に戻れって。
269 = "寝るなら自分の部屋に戻れって。"

# アクア
# ん……無理。
252 = "ん……無理。"

# カズマ
# あっ、おい、まさかここで寝るつもりか！
210 = "あっ、おい、まさかここで寝るつもりか！"

# アクア
# ……すう……すう……。
208 = "……すう……すう……。"

# カズマ（Ｍ）
# display as カズマ
# （こいつ、本当に寝やがった……）
294 = "（こいつ、本当に寝やがった……）"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、やれやれ）
298 = "（はぁ、やれやれ）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、こうまで無防備なのは俺を信頼して\n　くれてる証と思っといてやるか）
300 = "（まあ、こうまで無防備なのは俺を信頼して\\n　くれてる証と思っといてやるか）"

# カズマ
# さて、俺も寝るか……って！
225 = "さて、俺も寝るか……って！"

# アクア
# んん……むにゃ……もう食べられないったらぁ。
254 = "んん……むにゃ……もう食べられないったらぁ。"

# カズマ（Ｍ）
# display as カズマ
# （この状況で俺はどこで寝ればいいんだ……）
295 = "（この状況で俺はどこで寝ればいいんだ……）"

[selections]
246 = "もうちょっと離れろよ。"
# 301 = "（まあ、それがアクアか……）"
# 248 = "もしかして寂しかったのか？"
