# rew_e02.txt.scn

[info]
197 = "rew_e02"

[characters]
308 = "ゆんゆん"
316 = "カズマ"
317 = "カズマ（Ｍ）"

[character_subs]
# 316 = "カズマ"

[script]
# lines: 82

# ゆんゆん
# あ、あの……、\n着替え終わりました。
250 = "あ、あの……、\\n着替え終わりました。"

# カズマ
# おー、これは、なんとも素晴らしい！
267 = "おー、これは、なんとも素晴らしい！"

# ゆんゆん
# そんなにジロジロ見られたら恥ずかしいです。
280 = "そんなにジロジロ見られたら恥ずかしいです。"

# カズマ
# もし綺麗な花があったら、ゆんゆんはどうする？
307 = "もし綺麗な花があったら、ゆんゆんはどうする？"

# ゆんゆん
# 見ます。
356 = "見ます。"

# カズマ
# だろ？　それと同じだ。\n俺は美しい花を愛でるような気持ちで\nゆんゆんを見ている。
283 = "だろ？　それと同じだ。\\n俺は美しい花を愛でるような気持ちで\\nゆんゆんを見ている。"

# カズマ
# だから恥ずかしがらず、\nむしろ胸を張っていい！\nさあ、こう胸を張るんだ！　大きく！
282 = "だから恥ずかしがらず、\\nむしろ胸を張っていい！\\nさあ、こう胸を張るんだ！　大きく！"

# ゆんゆん
# こ、こうですか？
269 = "こ、こうですか？"

# カズマ
# いい！　実にいい！\nゆんゆんは素直でいい子だな！
261 = "いい！　実にいい！\\nゆんゆんは素直でいい子だな！"

# ゆんゆん
# そ、そんな……。
275 = "そ、そんな……。"

# カズマ
# その恥じらいの顔！\n何度見てもたまらないな！
278 = "その恥じらいの顔！\\n何度見てもたまらないな！"

# ゆんゆん
# あ、あの、そ、それで。\n私はどんなご褒美をカズマさんにあげれば。
251 = "あ、あの、そ、それで。\\n私はどんなご褒美をカズマさんにあげれば。"

# カズマ
# じゃあ、なわとびをして。
274 = "じゃあ、なわとびをして。"

# ゆんゆん
# え？　なわとびですか？\nそんなことでいいんですか？
264 = "え？　なわとびですか？\\nそんなことでいいんですか？"

# カズマ
# そんなことでいいんだよ！
279 = "そんなことでいいんだよ！"

# ゆんゆん
# ええと……ご褒美なんですよね？
263 = "ええと……ご褒美なんですよね？"

# カズマ
# ゆんゆんにはその理由が\nわからないかもしれないけど、\n俺は確実に喜ぶ！
309 = "ゆんゆんにはその理由が\\nわからないかもしれないけど、\\n俺は確実に喜ぶ！"

# ゆんゆん
# そうなんですね。\nその程度のことでいいなら。
277 = "そうなんですね。\\nその程度のことでいいなら。"

# カズマ
# ありがとう！\nじゃあ、庭に移動するか！
258 = "ありがとう！\\nじゃあ、庭に移動するか！"

# ゆんゆん
# は、はい！
293 = "は、はい！"

# カズマ
# というわけで、はいなわとびな。
288 = "というわけで、はいなわとびな。"

# ゆんゆん
# あ、ありがとうございます！
252 = "あ、ありがとうございます！"

# ゆんゆん
# え、ええと、何回くらい跳べばいいんでしょうか。
262 = "え、ええと、何回くらい跳べばいいんでしょうか。"

# カズマ
# 力の続く限りでお願いします！
324 = "力の続く限りでお願いします！"

# ゆんゆん
# わ、わかりました。\n頑張ってみます。
314 = "わ、わかりました。\\n頑張ってみます。"

# ゆんゆん
# １、２、３、４……。
364 = "１、２、３、４……。"

# カズマ（Ｍ）
# display as カズマ
# （すげー！　ゆんゆんが跳ぶたび\n　胸が上下に激しく揺れる！）
360 = "（すげー！　ゆんゆんが跳ぶたび\\n　胸が上下に激しく揺れる！）"

# カズマ（Ｍ）
# display as カズマ
# （人の体ってあんなに波打つんだな。\n　まるであそこだけ別の生き物だ！）
363 = "（人の体ってあんなに波打つんだな。\\n　まるであそこだけ別の生き物だ！）"

# カズマ（Ｍ）
# display as カズマ
# （これは嫌でも目が釘付けになるな！）
358 = "（これは嫌でも目が釘付けになるな！）"

# ゆんゆん
# はぁはぅ、はふ、１５ぉ、１６ぅ～！
298 = "はぁはぅ、はふ、１５ぉ、１６ぅ～！"

# カズマ（Ｍ）
# display as カズマ
# （くっはぁ！　その表情もいい！\n　サイコーだ！！）
357 = "（くっはぁ！　その表情もいい！\\n　サイコーだ！！）"

# ゆんゆん
# はぁはぅ、す、すごい真剣な眼差し。\n何がそんなにいいのか不思議です。
297 = "はぁはぅ、す、すごい真剣な眼差し。\\n何がそんなにいいのか不思議です。"

# カズマ
# 俺は生まれてから今日まで、\nこんな素晴らしい物を見たことがないぞ！
322 = "俺は生まれてから今日まで、\\nこんな素晴らしい物を見たことがないぞ！"

# ゆんゆん
# はぁはぁ、た、ただなわとびをしているだけ\nなのにですか？
294 = "はぁはぁ、た、ただなわとびをしているだけ\\nなのにですか？"

# カズマ
# 今！　俺の目の前には！\n男のロマンが広がっているんだよ！
321 = "今！　俺の目の前には！\\n男のロマンが広がっているんだよ！"

# ゆんゆん
# なわとびとロマンがどう繋がるのか、\nまったくわかりません。
290 = "なわとびとロマンがどう繋がるのか、\\nまったくわかりません。"

# ゆんゆん
# でもカズマさんが喜んでくれるなら、\n何も考えず跳ぶだけ。
287 = "でもカズマさんが喜んでくれるなら、\\n何も考えず跳ぶだけ。"

# ゆんゆん
# ３７、３８、３９、４０ぅぅ～～～～！！
365 = "３７、３８、３９、４０ぅぅ～～～～！！"

# カズマ
# よ～し、そのまま二重跳びいってみようか。
311 = "よ～し、そのまま二重跳びいってみようか。"

# ゆんゆん
# は、はい！
# 293 = "は、はい！"

# カズマ（Ｍ）
# display as カズマ
# （なんて素直ないい子なんだ。\n　疑うこともせず言われるままに\n　二重跳びを始めたぞ）
361 = "（なんて素直ないい子なんだ。\\n　疑うこともせず言われるままに\\n　二重跳びを始めたぞ）"

# カズマ（Ｍ）
# display as カズマ
# （しかしこれはとてつもないな！\n　今まで以上に大暴れじゃないか！\n　あんなになって痛くないのか？）
359 = "（しかしこれはとてつもないな！\\n　今まで以上に大暴れじゃないか！\\n　あんなになって痛くないのか？）"

# ゆんゆん
# はぁはぁはぁ、はぅ、あぅ、はぅあぅ～～～！！
295 = "はぁはぁはぁ、はぅ、あぅ、はぅあぅ～～～！！"

# カズマ
# さすがに疲れてきたか？
271 = "さすがに疲れてきたか？"

# ゆんゆん
# はい、少しだけ。\nだけどもっと喜んでもらいたいから頑張れますぅ！
301 = "はい、少しだけ。\\nだけどもっと喜んでもらいたいから頑張れますぅ！"

# カズマ
# どこまでいい子なんだ！\nアクアにゆんゆんの爪の垢を煎じて\n飲ませてやりたい！
289 = "どこまでいい子なんだ！\\nアクアにゆんゆんの爪の垢を煎じて\\n飲ませてやりたい！"

# ゆんゆん
# ほ、他に……他にぃ！\nはぅ、あぅ、何かできることはありますか？
305 = "ほ、他に……他にぃ！\\nはぅ、あぅ、何かできることはありますか？"

# カズマ
# そうだな――
276 = "そうだな――"

# カズマ
# 次は走ってみようか！
330 = "次は走ってみようか！"

# ゆんゆん
# なわとびをしながらですか？
291 = "なわとびをしながらですか？"

# カズマ
# 無理そうならいいぞ？
331 = "無理そうならいいぞ？"

# ゆんゆん
# ちょ、ちょっと大変ですけど、\nカズマさんは、はぅ、はぅぅ、\nそうして欲しいんですよね？
284 = "ちょ、ちょっと大変ですけど、\\nカズマさんは、はぅ、はぅぅ、\\nそうして欲しいんですよね？"

# ゆんゆん
# だ、だったら私は、はぅぅ、頑張るだけですぅ！
281 = "だ、だったら私は、はぅぅ、頑張るだけですぅ！"

# ゆんゆん
# はぅ、え、ええーい！
302 = "はぅ、え、ええーい！"

# カズマ
# おおおおお！\nいいぞゆんゆん、俺は今、猛烈に、感動している！
266 = "おおおおお！\\nいいぞゆんゆん、俺は今、猛烈に、感動している！"

# ゆんゆん
# はぁはぁはぁはぁ。\nあり、あり、ありがとうございます～。
296 = "はぁはぁはぁはぁ。\\nあり、あり、ありがとうございます～。"

# ゆんゆん
# でも、でもぉ、私、私、もう～～～～！！
286 = "でも、でもぉ、私、私、もう～～～～！！"

# カズマ
# さらに横の揺れを加えてみようか。
273 = "さらに横の揺れを加えてみようか。"

# ゆんゆん
# わ、わかりました。\nこうですか？
312 = "わ、わかりました。\\nこうですか？"

# カズマ
# いいねいいね。\n今まで以上に大暴れだ！
260 = "いいねいいね。\\n今まで以上に大暴れだ！"

# ゆんゆん
# はぅ、お、大暴れ？\nはぁはぁ、何がですか？
303 = "はぅ、お、大暴れ？\\nはぁはぁ、何がですか？"

# カズマ
# い、いや、なんでもない！
259 = "い、いや、なんでもない！"

# ゆんゆん
# あぅ、はぅ、カズマさぁん。\nこれ、はぅぅ、思ったよりもキツくてぇ～～！！
255 = "あぅ、はぅ、カズマさぁん。\\nこれ、はぅぅ、思ったよりもキツくてぇ～～！！"

# カズマ
# よーし、そのまま前屈みになってみようか！
310 = "よーし、そのまま前屈みになってみようか！"

# ゆんゆん
# わ、わかりました。\n前屈みですね？
313 = "わ、わかりました。\\n前屈みですね？"

# ゆんゆん
# ここ、こういう感じでしょうかぁ！
270 = "ここ、こういう感じでしょうかぁ！"

# カズマ
# もう少し！\nもう少しで見えそうだ。
306 = "もう少し！\\nもう少しで見えそうだ。"

# ゆんゆん
# はぅ、み、見えるって、何がですか？
304 = "はぅ、み、見えるって、何がですか？"

# カズマ
# あ、え、えっと！\nか、かか、体柔らかいんだな！
253 = "あ、え、えっと！\\nか、かか、体柔らかいんだな！"

# ゆんゆん
# あぅ、ありがとうございます。
254 = "あぅ、ありがとうございます。"

# カズマ
# はい、じゃあそのまま脇を締めて！\nこうっ、胸をぎゅってする感じで！
299 = "はい、じゃあそのまま脇を締めて！\\nこうっ、胸をぎゅってする感じで！"

# ゆんゆん
# は、はい、あぅ、はぅ、カズマしゃぁぁん！！
292 = "は、はい、あぅ、はぅ、カズマしゃぁぁん！！"

# カズマ
# お、おう、どうした！
265 = "お、おう、どうした！"

# ゆんゆん
# わ、私、もう！！　げ、げ、限界ですぅ～～！！
315 = "わ、私、もう！！　げ、げ、限界ですぅ～～！！"

# ゆんゆん
# きゃぅ！！
268 = "きゃぅ！！"

# カズマ
# あっ！　ゆんゆん大丈夫か！！
257 = "あっ！　ゆんゆん大丈夫か！！"

# ゆんゆん
# あぅ、転んじゃいました。
256 = "あぅ、転んじゃいました。"

# カズマ
# 怪我は無いか？
327 = "怪我は無いか？"

# ゆんゆん
# はい、大丈夫ですよ。
300 = "はい、大丈夫ですよ。"

# ゆんゆん
# ですが、ちょっと疲れちゃいましたので、\n少しだけ休憩させて欲しいです。
285 = "ですが、ちょっと疲れちゃいましたので、\\n少しだけ休憩させて欲しいです。"

# ゆんゆん
# 息が整ったら、またなわとびをしますので！
328 = "息が整ったら、またなわとびをしますので！"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんって本当にいい子だな。\n　なんだか心苦しくなってきた）
362 = "（ゆんゆんって本当にいい子だな。\\n　なんだか心苦しくなってきた）"

[selections]
329 = "次は走ってみようか"
272 = "さらに横の揺れを加えてみようか"
323 = "前屈みになってみようか"
