# rew_e01.txt.scn

[info]
193 = "rew_e01"

[characters]
314 = "ゆんゆん"
318 = "カズマ"
319 = "カズマ（Ｍ）"

[character_subs]
# 318 = "カズマ"

[script]
# lines: 77

# ゆんゆん
# お、お待たせしました。
282 = "お、お待たせしました。"

# カズマ
# うーん。
278 = "うーん。"

# ゆんゆん
# あの、おかしなところがありましたか？
271 = "あの、おかしなところがありましたか？"

# カズマ
# やっぱりいい！\n最高だ、ゆんゆん！
312 = "やっぱりいい！\\n最高だ、ゆんゆん！"

# ゆんゆん
# あ、ありがとうございます。\nでも、ちょっと恥ずかしいです。
267 = "あ、ありがとうございます。\\nでも、ちょっと恥ずかしいです。"

# カズマ
# その恥じらいの姿がまたいい！\nゆんゆんは期待を裏切らないな！
296 = "その恥じらいの姿がまたいい！\\nゆんゆんは期待を裏切らないな！"

# ゆんゆん
# あのぉ、こんな格好までさせて、\n私に何をさせようというんです？
273 = "あのぉ、こんな格好までさせて、\\n私に何をさせようというんです？"

# カズマ
# それを決めるのは俺じゃない、\nゆんゆんだ。
298 = "それを決めるのは俺じゃない、\\nゆんゆんだ。"

# ゆんゆん
# え、どういうことですか？
280 = "え、どういうことですか？"

# カズマ
# つまりゆんゆんが、\n俺にしてあげたいと思うことを\nしてくれればいい。
300 = "つまりゆんゆんが、\\n俺にしてあげたいと思うことを\\nしてくれればいい。"

# ゆんゆん
# 私がカズマさんにしてあげたいこと。
375 = "私がカズマさんにしてあげたいこと。"

# カズマ
# 難しく考えることはないぞ。\nシンプルに思い浮かんだことを\nしてくれるだけでいいんだ。
380 = "難しく考えることはないぞ。\\nシンプルに思い浮かんだことを\\nしてくれるだけでいいんだ。"

# カズマ
# 何をするかは、ゆんゆん次第。\nそれなら無駄に不安にさせることも\n余計な負担をかけることもないだろ？
327 = "何をするかは、ゆんゆん次第。\\nそれなら無駄に不安にさせることも\\n余計な負担をかけることもないだろ？"

# ゆんゆん
# 優しいんですね。
328 = "優しいんですね。"

# カズマ
# まあな、紳士カズマと呼んでくれ。
309 = "まあな、紳士カズマと呼んでくれ。"

# ゆんゆん
# 紳士カズマさん。
377 = "紳士カズマさん。"

# カズマ
# やっぱり恥ずかしいから\n普通に呼んでくれ！
313 = "やっぱり恥ずかしいから\\n普通に呼んでくれ！"

# ゆんゆん
# え～と、私がカズマさんにしてあげたいこと。\nなんだろう？
281 = "え～と、私がカズマさんにしてあげたいこと。\\nなんだろう？"

# ゆんゆん
# ダメ、どれも何か違うわ。\nそれなら逆に考えてみよう。\nカズマさんが喜んでくれそうなこと。
321 = "ダメ、どれも何か違うわ。\\nそれなら逆に考えてみよう。\\nカズマさんが喜んでくれそうなこと。"

# ゆんゆん
# 何をしたらカズマさんは喜んでくれるの？\nん～～～……。
326 = "何をしたらカズマさんは喜んでくれるの？\\nん～～～……。"

# カズマ（Ｍ）
# display as カズマ
# （思いっきり悩んでるな。\n　選択肢を自由に与えたことが\n　逆に難しくしたか？）
391 = "（思いっきり悩んでるな。\\n　選択肢を自由に与えたことが\\n　逆に難しくしたか？）"

# カズマ（Ｍ）
# display as カズマ
# （だけど俺のためにこんなに真剣に\n　考えてくれるなんてな。\n　他の連中じゃ絶対こうはならない！）
388 = "（だけど俺のためにこんなに真剣に\\n　考えてくれるなんてな。\\n　他の連中じゃ絶対こうはならない！）"

# ゆんゆん
# ダメ、そんな恥ずかしい真似はできないよ！
320 = "ダメ、そんな恥ずかしい真似はできないよ！"

# カズマ（Ｍ）
# display as カズマ
# （い、一体どんなことを考えてるんだ！？）
383 = "（い、一体どんなことを考えてるんだ！？）"

# ゆんゆん
# うう～ん、カズマさんが喜んでくれそうなこと。\n難しいなあ。
276 = "うう～ん、カズマさんが喜んでくれそうなこと。\\n難しいなあ。"

# カズマ
# 何も思いつかないか？
325 = "何も思いつかないか？"

# ゆんゆん
# ごめんなさい、\n男の人に何かしてあげた経験がほとんどなくて。
289 = "ごめんなさい、\\n男の人に何かしてあげた経験がほとんどなくて。"

# カズマ（Ｍ）
# display as カズマ
# （そうか、だったら難しいかもなー）
386 = "（そうか、だったら難しいかもなー）"

# カズマ
# よし、だったら俺のことを抱きしめてくれ！
316 = "よし、だったら俺のことを抱きしめてくれ！"

# ゆんゆん
# あ、はい、それくらいでしたら！
268 = "あ、はい、それくらいでしたら！"

# カズマ
# え、いいの？　本当に？？
279 = "え、いいの？　本当に？？"

# ゆんゆん
# は、はい、ちょっと恥ずかしいですけど、\nそれがご褒美になるって嬉しいかなって。
307 = "は、はい、ちょっと恥ずかしいですけど、\\nそれがご褒美になるって嬉しいかなって。"

# カズマ
# どうしてだ？
305 = "どうしてだ？"

# ゆんゆん
# あっ、いえ、と、とにかく大丈夫です！
270 = "あっ、いえ、と、とにかく大丈夫です！"

# カズマ（Ｍ）
# display as カズマ
# （そうは言うけど、耳まで真っ赤じゃないか。\n　モジモジして可愛いな！）
387 = "（そうは言うけど、耳まで真っ赤じゃないか。\\n　モジモジして可愛いな！）"

# カズマ（Ｍ）
# display as カズマ
# （こんな可愛い子にギュッとして貰えるなんて\n　これ以上のご褒美があるか？\n　いや、ない！）
385 = "（こんな可愛い子にギュッとして貰えるなんて\\n　これ以上のご褒美があるか？\\n　いや、ない！）"

# カズマ
# そ、それじゃ、\nそれでお願いします！
295 = "そ、それじゃ、\\nそれでお願いします！"

# ゆんゆん
# で、では、失礼します！
301 = "で、では、失礼します！"

# カズマ（Ｍ）
# display as カズマ
# （あれ、抱きついてこない？\n　なんだ、首に腕を回して――\n　うわっ！？）
382 = "（あれ、抱きついてこない？\\n　なんだ、首に腕を回して――\\n　うわっ！？）"

# カズマ（Ｍ）
# display as カズマ
# （こ、この柔らかな感触は、\n　ま、まさか……！\n　いや、そのまさかだ！！）
384 = "（こ、この柔らかな感触は、\\n　ま、まさか……！\\n　いや、そのまさかだ！！）"

# カズマ（Ｍ）
# display as カズマ
# （今俺の顔は、ゆんゆんの胸の谷閒に！\n　なんだこれ！\n　ここは天国か！？）
390 = "（今俺の顔は、ゆんゆんの胸の谷閒に！\\n　なんだこれ！\\n　ここは天国か！？）"

# ゆんゆん
# あ、あの……苦しくないですか？
266 = "あ、あの……苦しくないですか？"

# カズマ
# まったく！\nむしろ幸せいっぱいです！
310 = "まったく！\\nむしろ幸せいっぱいです！"

# ゆんゆん
# よかった……、\nこんなことで喜んでもらえて。
315 = "よかった……、\\nこんなことで喜んでもらえて。"

# ゆんゆん
# あ、あの……、\nメイドって他にどんなことを\nしたらいいんでしょう？
265 = "あ、あの……、\\nメイドって他にどんなことを\\nしたらいいんでしょう？"

# ゆんゆん
# できれば、もっとカズマさんに\n喜んでもらいたいです。
303 = "できれば、もっとカズマさんに\\n喜んでもらいたいです。"

# カズマ
# なんていい子なんだ！\nめぐみんたちに聞かせてやりたいな！
306 = "なんていい子なんだ！\\nめぐみんたちに聞かせてやりたいな！"

# ゆんゆん
# めぐみん……。\nあの、遠慮なく言ってください！
311 = "めぐみん……。\\nあの、遠慮なく言ってください！"

# カズマ
# それじゃあ――
297 = "それじゃあ――"

# カズマ
# ご主人様と呼んでくれ。
291 = "ご主人様と呼んでくれ。"

# ゆんゆん
# そんなことでいいんですか？
299 = "そんなことでいいんですか？"

# カズマ
# いい！\nゆんゆんみたいな可愛いメイドに\n言われてみたいんだ！
275 = "いい！\\nゆんゆんみたいな可愛いメイドに\\n言われてみたいんだ！"

# ゆんゆん
# 可愛いだなんて、そんな。\nそれじゃ、えっと――
329 = "可愛いだなんて、そんな。\\nそれじゃ、えっと――"

# ゆんゆん
# ご、ご主人様……。
288 = "ご、ご主人様……。"

# カズマ
# ああ、心が洗われていくようだ！
269 = "ああ、心が洗われていくようだ！"

# ゆんゆん
# くすっ、カズマさんたら。\n他に、何かして欲しいことはありますか？
285 = "くすっ、カズマさんたら。\\n他に、何かして欲しいことはありますか？"

# カズマ
# 頭を撫でてみてはどうだろう？
381 = "頭を撫でてみてはどうだろう？"

# ゆんゆん
# わかりました。\nそれじゃ失礼します。
317 = "わかりました。\\nそれじゃ失礼します。"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんの細い指が俺の頭を！）
389 = "（ゆんゆんの細い指が俺の頭を！）"

# ゆんゆん
# ど、どうですか？
304 = "ど、どうですか？"

# カズマ
# 実に素晴らしいと思います！\nあ～、生きててよかったぁ。
331 = "実に素晴らしいと思います！\\nあ～、生きててよかったぁ。"

# ゆんゆん
# こんなことが嬉しいなんて、\nカズマさんは甘えん坊さんなんですね？
286 = "こんなことが嬉しいなんて、\\nカズマさんは甘えん坊さんなんですね？"

# カズマ
# こんな男は嫌か？
287 = "こんな男は嫌か？"

# ゆんゆん
# い、いえ、とんでもありません！
274 = "い、いえ、とんでもありません！"

# ゆんゆん
# 本当のカズマさんを見せてくれてるみたいで、\nとても嬉しいです！
333 = "本当のカズマさんを見せてくれてるみたいで、\\nとても嬉しいです！"

# ゆんゆん
# あの、ですから、もっと甘えてください！\nして欲しいことを言ってくだされば、\nお応えしますので！
272 = "あの、ですから、もっと甘えてください！\\nして欲しいことを言ってくだされば、\\nお応えしますので！"

# カズマ
# 自分で考えてこその奉仕だ。
379 = "自分で考えてこその奉仕だ。"

# ゆんゆん
# そ、そうですね！\nえ～と、え～と……。
294 = "そ、そうですね！\\nえ～と、え～と……。"

# ゆんゆん
# すみません、何も思いつきません。
293 = "すみません、何も思いつきません。"

# カズマ
# まあ、仕方がないか。
308 = "まあ、仕方がないか。"

# ゆんゆん
# で、でも、要望を言っていただけたら\n全力でお応えしますので！
302 = "で、でも、要望を言っていただけたら\\n全力でお応えしますので！"

# カズマ
# ハハ、これ以上してもらったら贅沢ってもんだよ。
322 = "ハハ、これ以上してもらったら贅沢ってもんだよ。"

# ゆんゆん
# くす、やっぱり優しいですね。
284 = "くす、やっぱり優しいですね。"

# カズマ
# 紳士だからな！
376 = "紳士だからな！"

# ゆんゆん
# さすが紳士カズマさんです。
292 = "さすが紳士カズマさんです。"

# カズマ
# お願いだから、それはやめて！
283 = "お願いだから、それはやめて！"

# ゆんゆん
# うふふ。
277 = "うふふ。"

[selections]
290 = "ご主人様と呼んでくれ"
# 381 = "頭を撫でてみてはどうだろう？"
378 = "自分で考えてこその奉仕だ"
