# rew_b08.txt.scn

[info]
213 = "rew_b08"

[characters]
264 = "めぐみん"
274 = "カズマ"
272 = "アクア"
279 = "ダクネス"
278 = "カズマ（Ｍ）"

[character_subs]
# 274 = "カズマ"

[script]
# lines: 66

# めぐみん
# さあ、カズマ、お待ちかねのお仕置きタイムと\nいきましょうか。
244 = "さあ、カズマ、お待ちかねのお仕置きタイムと\\nいきましょうか。"

# カズマ
# 別に待ってないから！
285 = "別に待ってないから！"

# アクア
# ねえねえ、めぐみん。\nどんなお仕置きをするつもりなの？
260 = "ねえねえ、めぐみん。\\nどんなお仕置きをするつもりなの？"

# カズマ
# なんで、目を爛々とさせてるんだよ。
257 = "なんで、目を爛々とさせてるんだよ。"

# ダクネス
# カズマ、もしどうしてもお仕置きが嫌だと\nいうのなら、わ、私が代わってやらなくもないぞ。
275 = "カズマ、もしどうしてもお仕置きが嫌だと\\nいうのなら、わ、私が代わってやらなくもないぞ。"

# カズマ
# ダクネスは黙っててくれ。
280 = "ダクネスは黙っててくれ。"

# アクア
# なんかあれね、ドキドキしちゃうわね！
256 = "なんかあれね、ドキドキしちゃうわね！"

# カズマ（Ｍ）
# display as カズマ
# （こいつっ……！）
325 = "（こいつっ……！）"

# ダクネス
# なあ、めぐみん。\nいったいどんなお仕置きをするつもりなんだ？
254 = "なあ、めぐみん。\\nいったいどんなお仕置きをするつもりなんだ？"

# めぐみん
# ふっ、ごはんを食べさせて貰おうと思っています。
262 = "ふっ、ごはんを食べさせて貰おうと思っています。"

# カズマ
# ん？　どういうことだ？？
271 = "ん？　どういうことだ？？"

# めぐみん
# ですから、あーんするので\n口の中に料理を入れてください。
252 = "ですから、あーんするので\\n口の中に料理を入れてください。"

# カズマ
# そんなことでいいのか？
251 = "そんなことでいいのか？"

# めぐみん
# なんです、不満なんですか？\nならば、全裸で街中をランニングに\n変更しますか？？
258 = "なんです、不満なんですか？\\nならば、全裸で街中をランニングに\\n変更しますか？？"

# カズマ
# 捕まるわ！\nあーんの方でいいよ。
293 = "捕まるわ！\\nあーんの方でいいよ。"

# カズマ（Ｍ）
# display as カズマ
# （どんな酷いことをさせられるのかと\n　身構えてたせいで、拍子抜けだな）
330 = "（どんな酷いことをさせられるのかと\\n　身構えてたせいで、拍子抜けだな）"

# めぐみん
# さあさあ、さっそくお願いします。
247 = "さあさあ、さっそくお願いします。"

# カズマ
# なんでそんなにテンション高いんだよ。
259 = "なんでそんなにテンション高いんだよ。"

# めぐみん
# いいですから、はーやーく。
236 = "いいですから、はーやーく。"

# カズマ
# わかったわかった。\nはい、あーん。
269 = "わかったわかった。\\nはい、あーん。"

# めぐみん
# あーん。
235 = "あーん。"

# めぐみん
# うん、心なしかいつもより美味しく感じますよ。
237 = "うん、心なしかいつもより美味しく感じますよ。"

# カズマ
# それは何よりだな。
250 = "それは何よりだな。"

# めぐみん
# 次は唐揚げをいただけますか？
294 = "次は唐揚げをいただけますか？"

# カズマ
# はいはい、あーん。
261 = "はいはい、あーん。"

# めぐみん
# あーん。
# 235 = "あーん。"

# めぐみん
# んふ～、これは楽でいいですね。
270 = "んふ～、これは楽でいいですね。"

# カズマ（Ｍ）
# display as カズマ
# （なんか思ってたのと違う！）
331 = "（なんか思ってたのと違う！）"

# カズマ（Ｍ）
# display as カズマ
# （ただ食べさせてるだけなのに、\n　この気恥ずかしさはなんだ？）
327 = "（ただ食べさせてるだけなのに、\\n　この気恥ずかしさはなんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （妙にむず痒いというか、落ち着かない感じが……）
333 = "（妙にむず痒いというか、落ち着かない感じが……）"

# アクア
# これってどう見てもお嬢様に仕える\n使用人にしか見えないわね。
242 = "これってどう見てもお嬢様に仕える\\n使用人にしか見えないわね。"

# ダクネス
# そうか？\n私には娘に甲斐甲斐しく尽くす、\n父親のように映るのだが。
248 = "そうか？\\n私には娘に甲斐甲斐しく尽くす、\\n父親のように映るのだが。"

# ダクネス
# 実に微笑ましい光景ではないか。\nカズマはいい父親になるに違いない。
289 = "実に微笑ましい光景ではないか。\\nカズマはいい父親になるに違いない。"

# アクア
# カズマの場合、相手を見つけるのが問題だと\n思うけど？
277 = "カズマの場合、相手を見つけるのが問題だと\\n思うけど？"

# ダクネス
# 確かに。
319 = "確かに。"

# カズマ
# お前らはちょっと黙ってろよ！
240 = "お前らはちょっと黙ってろよ！"

# カズマ（Ｍ）
# display as カズマ
# （くっ……なんという羞恥プレイ、\n　このままでは俺の心が保たない！）
323 = "（くっ……なんという羞恥プレイ、\\n　このままでは俺の心が保たない！）"

# カズマ
# なあ、めぐみん。\nもうやめてもいいか？
255 = "なあ、めぐみん。\\nもうやめてもいいか？"

# めぐみん
# 何を言っているのです。\nまだ半分以上残っているではありませんか。
284 = "何を言っているのです。\\nまだ半分以上残っているではありませんか。"

# カズマ
# それはそうなんだが、\nこれ以上は辛くて耐えられないんだよ。
249 = "それはそうなんだが、\\nこれ以上は辛くて耐えられないんだよ。"

# めぐみん
# 何が辛いのか、まったく理解できません。\nただ腕を上げ下げしているだけでしょう？
283 = "何が辛いのか、まったく理解できません。\\nただ腕を上げ下げしているだけでしょう？"

# カズマ
# 身体的な問題じゃなくて、\n心にダメージが来るんだよ！
320 = "身体的な問題じゃなくて、\\n心にダメージが来るんだよ！"

# めぐみん
# よくわかりませんが、辛い思いをしているなら\nなお良しです。
267 = "よくわかりませんが、辛い思いをしているなら\\nなお良しです。"

# めぐみん
# さあ、続けてください。\nお仕置きを途中で放り出してはいけませんよ。
246 = "さあ、続けてください。\\nお仕置きを途中で放り出してはいけませんよ。"

# カズマ
# くっ、鬼か！？
241 = "くっ、鬼か！？"

# ダクネス
# ふふ、めぐみんも容赦ないな。
263 = "ふふ、めぐみんも容赦ないな。"

# カズマ
# 今度はアクアに食べさせて貰ったらどうだ？
282 = "今度はアクアに食べさせて貰ったらどうだ？"

# アクア
# えー、どうしてよ。
238 = "えー、どうしてよ。"

# カズマ
# お前も少しはこの恥ずかしさを思いしれ！
239 = "お前も少しはこの恥ずかしさを思いしれ！"

# アクア
# 嫌よ。\nこれはカズマへのお仕置きなんだから\n最後まで続けなさい。
288 = "嫌よ。\\nこれはカズマへのお仕置きなんだから\\n最後まで続けなさい。"

# めぐみん
# アクアの言うとおりですよ。
273 = "アクアの言うとおりですよ。"

# カズマ（Ｍ）
# display as カズマ
# （くっ……なんという屈辱！）
322 = "（くっ……なんという屈辱！）"

# カズマ（Ｍ）
# display as カズマ
# （こうなったら熱いのを食べさせて\n　空気を変えてやる！）
326 = "（こうなったら熱いのを食べさせて\\n　空気を変えてやる！）"

# カズマ
# さあ、めぐみん。\nあーんしてくれ。
243 = "さあ、めぐみん。\\nあーんしてくれ。"

# めぐみん
# 待ってください、\nなんか熱そうなので、\nフーフーして冷ましてからにしてください。
292 = "待ってください、\\nなんか熱そうなので、\\nフーフーして冷ましてからにしてください。"

# カズマ（Ｍ）
# display as カズマ
# （くっ、策士策に溺れる！\n　まさか更に辱めを受けることになろうとは！）
324 = "（くっ、策士策に溺れる！\\n　まさか更に辱めを受けることになろうとは！）"

# めぐみん
# さあ、早くフーフーしてください。
245 = "さあ、早くフーフーしてください。"

# カズマ
# わ、わかったよ。\nフーフー……こんなもんか？
268 = "わ、わかったよ。\\nフーフー……こんなもんか？"

# めぐみん
# では、あーん。
253 = "では、あーん。"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、アクアがニヤニヤして見てるし……）
332 = "（はぁ、アクアがニヤニヤして見てるし……）"

# めぐみん
# やはりこれは楽でいいですね。
266 = "やはりこれは楽でいいですね。"

# カズマ（Ｍ）
# display as カズマ
# （たぶんめぐみんは、\n　楽をしたいから俺をこき使ってる程度にしか\n　考えてないんだろうな）
328 = "（たぶんめぐみんは、\\n　楽をしたいから俺をこき使ってる程度にしか\\n　考えてないんだろうな）"

# カズマ（Ｍ）
# display as カズマ
# （でも……）
329 = "（でも……）"

# めぐみん
# カズマ、カズマ、次はスープが飲みたいです！
276 = "カズマ、カズマ、次はスープが飲みたいです！"

# カズマ（Ｍ）
# display as カズマ
# （ああ、この無邪気な笑顔が\n　さらに羞恥心を掻き立ててくる！）
321 = "（ああ、この無邪気な笑顔が\\n　さらに羞恥心を掻き立ててくる！）"

# カズマ（Ｍ）
# display as カズマ
# （恐るべし、めぐみん！）
334 = "（恐るべし、めぐみん！）"

[selections]
265 = "もうやめてもいいか？"
# 282 = "今度はアクアに食べさせて貰ったらどうだ？"
296 = "熱いのを食べさせよう"
