# rew_e05.txt.scn

[info]
273 = "rew_e05"

[characters]
409 = "カズマ"
397 = "ゆんゆん"
411 = "カズマ（Ｍ）"
390 = "めぐみん"

[character_subs]
# 409 = "カズマ"

[script]
# lines: 113

# カズマ
# はぁ～～～～。
384 = "はぁ～～～～。"

# ゆんゆん
# どうしたんですか？
373 = "どうしたんですか？"

# カズマ
# いや、なんでもないよ。\nはぁ～～～。
336 = "いや、なんでもないよ。\\nはぁ～～～。"

# ゆんゆん
# なにか悩み事ですか？\nわ、私でよければ相談に乗らせてください！
375 = "なにか悩み事ですか？\\nわ、私でよければ相談に乗らせてください！"

# ゆんゆん
# あ、でも、私みたいな世間知らずの子が\n相談に乗るなんてさしでがましいですよね。
328 = "あ、でも、私みたいな世間知らずの子が\\n相談に乗るなんてさしでがましいですよね。"

# カズマ（Ｍ）
# display as カズマ
# （いや、チラチラ見られながら言われても……）
485 = "（いや、チラチラ見られながら言われても……）"

# カズマ
# いや、悩みって程のことじゃないんだけど、\n最近疲れがたまっててさ。
337 = "いや、悩みって程のことじゃないんだけど、\\n最近疲れがたまっててさ。"

# ゆんゆん
# 指輪のこととか、色々ありますからね。
433 = "指輪のこととか、色々ありますからね。"

# カズマ
# 当然それも要因の１つなんだが、\nそれもよりもめぐみんたちかな。
428 = "当然それも要因の１つなんだが、\\nそれもよりもめぐみんたちかな。"

# カズマ
# はぁ、いつもいつも連中の尻ぬぐいばかり\nさせられてストレスは溜まる一方だ。
382 = "はぁ、いつもいつも連中の尻ぬぐいばかり\\nさせられてストレスは溜まる一方だ。"

# ゆんゆん
# で、でも、ああ見えてめぐみんには\nいいところがたくさんあるんですよ？
366 = "で、でも、ああ見えてめぐみんには\\nいいところがたくさんあるんですよ？"

# カズマ
# ゆんゆんは優しいんだな。
400 = "ゆんゆんは優しいんだな。"

# ゆんゆん
# あの、もしめぐみんが何かご迷惑を\nおかけしているなら、私にカズマさんの疲れを\n取るためのお手伝いをさせてください。
329 = "あの、もしめぐみんが何かご迷惑を\\nおかけしているなら、私にカズマさんの疲れを\\n取るためのお手伝いをさせてください。"

# ゆんゆん
# いずれ紅魔族の長になる者として、\n同郷の失敗を放っておけませんので。
335 = "いずれ紅魔族の長になる者として、\\n同郷の失敗を放っておけませんので。"

# カズマ
# こうして話を聞いてくれるだけで十分だよ。\nそれにゆんゆんに迷惑はかけられない。
342 = "こうして話を聞いてくれるだけで十分だよ。\\nそれにゆんゆんに迷惑はかけられない。"

# ゆんゆん
# 迷惑なんて思っていません！\nわ、私じゃ何もできないかもしれないけど、\nカズマさんの力になりたいんです。
484 = "迷惑なんて思っていません！\\nわ、私じゃ何もできないかもしれないけど、\\nカズマさんの力になりたいんです。"

# カズマ
# 本当にそう思ってる？
435 = "本当にそう思ってる？"

# ゆんゆん
# もちろんです！
395 = "もちろんです！"

# カズマ
# 実は、ゆんゆんにしかできない俺の疲れを取る\n方法があるんだよ。
425 = "実は、ゆんゆんにしかできない俺の疲れを取る\\n方法があるんだよ。"

# ゆんゆん
# 私にしかできない！\nなんですかそれは！！
483 = "私にしかできない！\\nなんですかそれは！！"

# カズマ
# えっと……添い寝。
339 = "えっと……添い寝。"

# ゆんゆん
# ふえ？
387 = "ふえ？"

# カズマ
# だから……。\n添い寝。一緒に寝ること。
362 = "だから……。\\n添い寝。一緒に寝ること。"

# ゆんゆん
# え、ええーーーー！？
338 = "え、ええーーーー！？"

# カズマ
# 下心があるわけじゃないぞ！\n今の俺には温もりという癒やしが必要なんだ。\nそしてそれを解決できる唯一の手段が――
413 = "下心があるわけじゃないぞ！\\n今の俺には温もりという癒やしが必要なんだ。\\nそしてそれを解決できる唯一の手段が――"

# ゆんゆん
# そ、添い寝？
352 = "そ、添い寝？"

# カズマ
# しかしそれは、誰にでもできるというわけじゃ\nないんだよ。
347 = "しかしそれは、誰にでもできるというわけじゃ\\nないんだよ。"

# カズマ
# 必要なのは心の温もりで、\nそれをもっている心根の優しい女の子は\nゆんゆんだけなんだ！
430 = "必要なのは心の温もりで、\\nそれをもっている心根の優しい女の子は\\nゆんゆんだけなんだ！"

# ゆんゆん
# そ、そうでしょうか。
350 = "そ、そうでしょうか。"

# カズマ
# それに、友達じゃない人に添い寝されても\n気疲れするだけだろ？
359 = "それに、友達じゃない人に添い寝されても\\n気疲れするだけだろ？"

# ゆんゆん
# と、友達？
371 = "と、友達？"

# カズマ
# そう、友達！
354 = "そう、友達！"

# ゆんゆん
# わ、わかりました\nどれくらいお力になれるかはわかりませんが、\n頑張って添い寝をさせていただきます！
401 = "わ、わかりました\\nどれくらいお力になれるかはわかりませんが、\\n頑張って添い寝をさせていただきます！"

# カズマ（Ｍ）
# display as カズマ
# （ふ、チョロイ）
488 = "（ふ、チョロイ）"

# ゆんゆん
# こ、これでいいですか？
341 = "こ、これでいいですか？"

# カズマ
# いい、実にいい！\n次は耳元で愛の言葉を囁いて欲しい。
332 = "いい、実にいい！\\n次は耳元で愛の言葉を囁いて欲しい。"

# ゆんゆん
# あ、あああああ、愛の言葉ですか？
327 = "あ、あああああ、愛の言葉ですか？"

# カズマ
# 恥ずかしい気持ちはよくわかる。\nだけど、ここは俺を救うと思って！\n頼れるのは、ゆんゆんだけなんだ！
431 = "恥ずかしい気持ちはよくわかる。\\nだけど、ここは俺を救うと思って！\\n頼れるのは、ゆんゆんだけなんだ！"

# カズマ
# 友達として、ここまでは言ってもいいかなぁ\n程度でいいから！
420 = "友達として、ここまでは言ってもいいかなぁ\\n程度でいいから！"

# ゆんゆん
# 友達として……。\nそれにこの私が人に頼られている？
419 = "友達として……。\\nそれにこの私が人に頼られている？"

# ゆんゆん
# わ、わかりました。\n精一杯頑張ります。
402 = "わ、わかりました。\\n精一杯頑張ります。"

# カズマ
# さあ、ゆんゆんの愛を俺に！
345 = "さあ、ゆんゆんの愛を俺に！"

# ゆんゆん
# カ、カズマさんは素敵な人だと思います。\n優しく行動的だし……格好いいと思います。
408 = "カ、カズマさんは素敵な人だと思います。\\n優しく行動的だし……格好いいと思います。"

# カズマ
# なんで、そんな棒読みなんだよ。
378 = "なんで、そんな棒読みなんだよ。"

# ゆんゆん
# だって、変に演技したら――
363 = "だって、変に演技したら――"

# ゆんゆん
# えー、それって本心なの？\n取り入ろうとして、適当言ってるだけなんじゃ\nない？　本当にやらしい女。
340 = "えー、それって本心なの？\\n取り入ろうとして、適当言ってるだけなんじゃ\\nない？　本当にやらしい女。"

# ゆんゆん
# とか、思われそうですし。
372 = "とか、思われそうですし。"

# カズマ
# 俺は嫌味な女か！
417 = "俺は嫌味な女か！"

# ゆんゆん
# それにやっぱり恥ずかしいというのも\nありまして。
360 = "それにやっぱり恥ずかしいというのも\\nありまして。"

# カズマ
# でも、それじゃ俺の心は癒されないんだよ。
369 = "でも、それじゃ俺の心は癒されないんだよ。"

# ゆんゆん
# でしたら、もっと具体的に指示を戴けると\n助かるかなって思います。
368 = "でしたら、もっと具体的に指示を戴けると\\n助かるかなって思います。"

# カズマ
# もっと感情を込めてくれ！
396 = "もっと感情を込めてくれ！"

# ゆんゆん
# ちっとも具体的じゃありませんよ！
364 = "ちっとも具体的じゃありませんよ！"

# カズマ
# 確かにそうだ。\nでもそこはゆんゆんに考えてもらいたいんだ。
482 = "確かにそうだ。\\nでもそこはゆんゆんに考えてもらいたいんだ。"

# カズマ
# なぜなら、その恥ずかしそうな顔も俺にとっては\n大好物、じゃなくて癒やしだから！
374 = "なぜなら、その恥ずかしそうな顔も俺にとっては\\n大好物、じゃなくて癒やしだから！"

# ゆんゆん
# はぅぅ、男の子って、よくわからないです。
385 = "はぅぅ、男の子って、よくわからないです。"

# カズマ
# 俺を恋人だと思うんだ！
418 = "俺を恋人だと思うんだ！"

# ゆんゆん
# カ、カズマさんが恋人！？
407 = "カ、カズマさんが恋人！？"

# カズマ
# そう思えば自然と愛の言葉も出てくるだろ？
355 = "そう思えば自然と愛の言葉も出てくるだろ？"

# ゆんゆん
# で、でも、そんなの恥ずかしすぎます。
367 = "で、でも、そんなの恥ずかしすぎます。"

# カズマ
# 大丈夫、ゆんゆんはできる子だ。\n自信を持って！
423 = "大丈夫、ゆんゆんはできる子だ。\\n自信を持って！"

# ゆんゆん
# わ、私はできる子。
405 = "わ、私はできる子。"

# カズマ
# それに、いずれ紅魔族の長になる者として、\n友達１人癒やせなくてどうするつもりだ！
358 = "それに、いずれ紅魔族の長になる者として、\\n友達１人癒やせなくてどうするつもりだ！"

# ゆんゆん
# そ、そうですよね！\nカズマさんを恋人だと思って、\n精一杯、癒させていただきます！
351 = "そ、そうですよね！\\nカズマさんを恋人だと思って、\\n精一杯、癒させていただきます！"

# カズマ
# 体を寄せてみるのはどうだ？
415 = "体を寄せてみるのはどうだ？"

# ゆんゆん
# そそ、そんなの恥ずかしすぎますよ！
356 = "そそ、そんなの恥ずかしすぎますよ！"

# カズマ
# 癒やしには体の温もりも必要なんだぞ！
441 = "癒やしには体の温もりも必要なんだぞ！"

# ゆんゆん
# それはなんとなくわかりますが。\nでもぉ～。
361 = "それはなんとなくわかりますが。\\nでもぉ～。"

# カズマ
# そっかー、さすがに無理かー。\n友達のっ、ゆんゆんならっ、\nやってくれると思ったんだけどなー。
357 = "そっかー、さすがに無理かー。\\n友達のっ、ゆんゆんならっ、\\nやってくれると思ったんだけどなー。"

# ゆんゆん
# と、友達……。
370 = "と、友達……。"

# カズマ
# そう、ゆんゆんと俺、友達！
353 = "そう、ゆんゆんと俺、友達！"

# ゆんゆん
# わ、わかりました！\n恥ずかしいですけど、がが、頑張ります！
403 = "わ、わかりました！\\n恥ずかしいですけど、がが、頑張ります！"

# カズマ
# さあさあ、密着するぐらい近づいて。
346 = "さあさあ、密着するぐらい近づいて。"

# ゆんゆん
# は、はい！
381 = "は、はい！"

# めぐみん
# 何をしているんですかっ。
416 = "何をしているんですかっ。"

# ゆんゆん
# め、めぐみん！？
389 = "め、めぐみん！？"

# カズマ
# なんでお前がここにいるんだよ！
379 = "なんでお前がここにいるんだよ！"

# めぐみん
# ご褒美にと、カズマの部屋にゆんゆんが\n呼び出されたと聞きまして。
343 = "ご褒美にと、カズマの部屋にゆんゆんが\\n呼び出されたと聞きまして。"

# めぐみん
# なんと言いますか、最低ですねカズマは。
380 = "なんと言いますか、最低ですねカズマは。"

# カズマ
# アホバカっ、これは同意の上だ！\n強要したわけじゃない！
406 = "アホバカっ、これは同意の上だ！\\n強要したわけじゃない！"

# ゆんゆん
# そ、そうだよ！\n友達としてこれくらい普通なんだから！
349 = "そ、そうだよ！\\n友達としてこれくらい普通なんだから！"

# めぐみん
# なるほど、ゆんゆんのチョロい性格に\n付け込んだわけですね。
377 = "なるほど、ゆんゆんのチョロい性格に\\n付け込んだわけですね。"

# ゆんゆん
# チョ、チョロい！？
412 = "チョ、チョロい！？"

# カズマ
# あははははは、友達をそんな言い方しちゃダメだぞー。
330 = "あははははは、友達をそんな言い方しちゃダメだぞー。"

# めぐみん
# カズマ、目が泳いでいますよ。
410 = "カズマ、目が泳いでいますよ。"

# カズマ（Ｍ）
# display as カズマ
# （ぬっは！）
487 = "（ぬっは！）"

# めぐみん
# はぁ、くだらないことに、\nゆんゆんを巻き込まないでください。
383 = "はぁ、くだらないことに、\\nゆんゆんを巻き込まないでください。"

# ゆんゆん
# めぐみん、私を心配してくれるの？
393 = "めぐみん、私を心配してくれるの？"

# めぐみん
# いえ、まったく。\nただ見るに堪えない茶番だったもので。
334 = "いえ、まったく。\\nただ見るに堪えない茶番だったもので。"

# めぐみん
# あまりの大根役者ぶりに、\n呆れて開いた口が塞がりませんよ。\n紅魔族の名を地に落とす気ですか？
331 = "あまりの大根役者ぶりに、\\n呆れて開いた口が塞がりませんよ。\\n紅魔族の名を地に落とす気ですか？"

# ゆんゆん
# ひどいよ、めぐみん！
386 = "ひどいよ、めぐみん！"

# カズマ
# ほほう。\nじゃあ、お前は違うと言うのか？
388 = "ほほう。\\nじゃあ、お前は違うと言うのか？"

# めぐみん
# 当然です。\nそこの腑抜けと一緒にされては困ります。
429 = "当然です。\\nそこの腑抜けと一緒にされては困ります。"

# カズマ
# ならお前が、紅魔族の力とやらを\n見せてみたらどうだ？
376 = "ならお前が、紅魔族の力とやらを\\n見せてみたらどうだ？"

# めぐみん
# 安い挑発ですね。\nですが、その挑発、あえてのりましょう！
424 = "安い挑発ですね。\\nですが、その挑発、あえてのりましょう！"

# めぐみん
# ゆんゆんによって貶められた紅魔族の尊厳を\n私が取り戻してみせますよ！
399 = "ゆんゆんによって貶められた紅魔族の尊厳を\\n私が取り戻してみせますよ！"

# ゆんゆん
# わ、私そこまでのことした？
404 = "わ、私そこまでのことした？"

# めぐみん
# さあ、とくと私の癒やしを食らうがいいです！
344 = "さあ、とくと私の癒やしを食らうがいいです！"

# めぐみん
# ちょっと、カズマ近すぎます。\n私の力を万全にふるえる距離まで離れてください。
365 = "ちょっと、カズマ近すぎます。\\n私の力を万全にふるえる距離まで離れてください。"

# カズマ
# 痛っ！　お、押すなよ！
440 = "痛っ！　お、押すなよ！"

# ゆんゆん
# めぐみん、あまり押さないで、\nカズマさんが、こっちに、ち、近いから！
391 = "めぐみん、あまり押さないで、\\nカズマさんが、こっちに、ち、近いから！"

# カズマ
# 痛たたたたたた！\nゆ、ゆんゆんも押すなって！
438 = "痛たたたたたた！\\nゆ、ゆんゆんも押すなって！"

# ゆんゆん
# す、すみません、でも……。
348 = "す、すみません、でも……。"

# カズマ
# 痛たたたたたた！
437 = "痛たたたたたた！"

# めぐみん
# ゆんゆん、押すんじゃありません！\nカズマとくっついてしまうではありませんか！
398 = "ゆんゆん、押すんじゃありません！\\nカズマとくっついてしまうではありませんか！"

# カズマ
# 押し返すな、めぐみん!
432 = "押し返すな、めぐみん!"

# ゆんゆん
# めぐみんには負けないんだから！
394 = "めぐみんには負けないんだから！"

# めぐみん
# 望むところです！
434 = "望むところです！"

# カズマ
# 痛たたたたたた！！\nお互い押しつけ合うな！
439 = "痛たたたたたた！！\\nお互い押しつけ合うな！"

# カズマ（Ｍ）
# display as カズマ
# （な、なんだこれ？\n　俺はただ癒やされたかっただけなのに！！）
486 = "（な、なんだこれ？\\n　俺はただ癒やされたかっただけなのに！！）"

# ゆんゆん
# めぐみん、勝負だよ！\nカズマさんと３秒くっついたら負けだからね！
392 = "めぐみん、勝負だよ！\\nカズマさんと３秒くっついたら負けだからね！"

# めぐみん
# いいでしょう。\nその勝負受けて立ちますよ！
333 = "いいでしょう。\\nその勝負受けて立ちますよ！"

# カズマ
# 痛い、痛たたたた！\n痛いってーの！
436 = "痛い、痛たたたた！\\n痛いってーの！"

[selections]
# 396 = "もっと感情を込めてくれ！"
# 418 = "俺を恋人だと思うんだ！"
# 415 = "体を寄せてみるのはどうだ？"
