# rew_f03.txt.scn

[info]
211 = "rew_f03"

[characters]
321 = "ウィズ"
326 = "カズマ"

[character_subs]

[script]
# lines: 89

# ウィズ
# あ、あの～、着替えてきましたが。
255 = "あ、あの～、着替えてきましたが。"

# カズマ
# いいね！\nこのちょっとアダルティな香りのするアイドル！！
263 = "いいね！\\nこのちょっとアダルティな香りのするアイドル！！"

# カズマ
# なんて言うか、背徳感というかイケナイ感じが\nぷんぷんとする！
302 = "なんて言うか、背徳感というかイケナイ感じが\\nぷんぷんとする！"

# ウィズ
# か、カズマさんが変態といわれている理由が、\nよくわかりました。
279 = "か、カズマさんが変態といわれている理由が、\\nよくわかりました。"

# カズマ
# し、失礼な！　アイドルは男の、いや女の子にも\n永遠の夢、憧れなんだからな！
283 = "し、失礼な！　アイドルは男の、いや女の子にも\\n永遠の夢、憧れなんだからな！"

# ウィズ
# 今、あからさまに女の子の場合を付け加えました\nよね？
332 = "今、あからさまに女の子の場合を付け加えました\\nよね？"

# カズマ
# き、気のせいだよ！
280 = "き、気のせいだよ！"

# カズマ
# それよりも、うーん、何をしてもらおうかな～。
293 = "それよりも、うーん、何をしてもらおうかな～。"

# ウィズ
# アイドルなら、握手とかサインですか？\nカズマさんがそう仰っていましたよね？
320 = "アイドルなら、握手とかサインですか？\\nカズマさんがそう仰っていましたよね？"

# カズマ
# 仰ったけど、それはただのアイドル活動だから！
334 = "仰ったけど、それはただのアイドル活動だから！"

# ウィズ
# よくわかりませんが、難しいんですね。
317 = "よくわかりませんが、難しいんですね。"

# カズマ
# そう、難しい、難しいのだ！
291 = "そう、難しい、難しいのだ！"

# カズマ
# アイドルとは憧れの存在であり高嶺の花。
319 = "アイドルとは憧れの存在であり高嶺の花。"

# カズマ
# しかし時には幼馴染みのように隣に寄り添い。\nそして時にはまるで可愛い妹のように微笑みかけて\nくれる！
287 = "しかし時には幼馴染みのように隣に寄り添い。\\nそして時にはまるで可愛い妹のように微笑みかけて\\nくれる！"

# ウィズ
# 万能なんですね？
331 = "万能なんですね？"

# カズマ
# しかーしだウィズ！
288 = "しかーしだウィズ！"

# ウィズ
# は、はい、なんでしょう！
306 = "は、はい、なんでしょう！"

# カズマ
# そのアイドルたちは、\nどうやっても、どう足掻いても、俺たちのっ――
292 = "そのアイドルたちは、\\nどうやっても、どう足掻いても、俺たちのっ――"

# ウィズ
# カズマさんたちの？
328 = "カズマさんたちの？"

# カズマ
# 恋人にはなってくれません！
344 = "恋人にはなってくれません！"

# ウィズ
# は、はあ。
303 = "は、はあ。"

# カズマ
# というわけで、導き出された結論はひとつ！\nアイドルのウィズさん、俺と恋人ごっこを\nして下さい！！
299 = "というわけで、導き出された結論はひとつ！\\nアイドルのウィズさん、俺と恋人ごっこを\\nして下さい！！"

# ウィズ
# あ、はい、それくらいでしたら構いませんよ。
257 = "あ、はい、それくらいでしたら構いませんよ。"

# カズマ
# 軽い、軽いよウィズ！\nア、アイドルなんだからもっとガードを堅くしないと！
386 = "軽い、軽いよウィズ！\\nア、アイドルなんだからもっとガードを堅くしないと！"

# ウィズ
# も、もう、始まっているんですね。
315 = "も、もう、始まっているんですね。"

# カズマ
# というわけで、俺の恋人になってください！
298 = "というわけで、俺の恋人になってください！"

# ウィズ
# ええと、嫌です。
272 = "ええと、嫌です。"

# カズマ
# 堅すぎるよ！
340 = "堅すぎるよ！"

# ウィズ
# どうすればいいですか……。
300 = "どうすればいいですか……。"

# カズマ
# じゃあ、こういう設定にしよう。
289 = "じゃあ、こういう設定にしよう。"

# カズマ
# ウィズは俺の幼馴染みだった。
324 = "ウィズは俺の幼馴染みだった。"

# カズマ
# しかしひょんなことから芸能界にデビューして\nあれよあれよと国民的アイドルにまで\n駆けのぼってしまう！
286 = "しかしひょんなことから芸能界にデビューして\\nあれよあれよと国民的アイドルにまで\\n駆けのぼってしまう！"

# カズマ
# しかし、ウィズは気がついてしまうんだ。\n周りの人間は、自分を金を生み出す道具としか\n見ていないことに！
284 = "しかし、ウィズは気がついてしまうんだ。\\n周りの人間は、自分を金を生み出す道具としか\\n見ていないことに！"

# カズマ
# さいぎ心に苛まれる中で、\nウィズ、お前は俺との再会を果たす！
282 = "さいぎ心に苛まれる中で、\\nウィズ、お前は俺との再会を果たす！"

# カズマ
# 俺は知っていた。\nテレビの中で見るお前の笑顔は本物では無いと！
338 = "俺は知っていた。\\nテレビの中で見るお前の笑顔は本物では無いと！"

# カズマ
# 今のウィズには俺が必要だ！\nしかしウィズは今やこの世界の人、全ての物！
333 = "今のウィズには俺が必要だ！\\nしかしウィズは今やこの世界の人、全ての物！"

# カズマ
# ウィズもわかっている。\n自分はもう自分だけの物ではないと！
325 = "ウィズもわかっている。\\n自分はもう自分だけの物ではないと！"

# カズマ
# しかし、俺の顔を見た途端、ウィズ、お前は！
285 = "しかし、俺の顔を見た途端、ウィズ、お前は！"

# ウィズ
# あの、カズマさん、長いです。
261 = "あの、カズマさん、長いです。"

# カズマ
# あ、ごめん。
256 = "あ、ごめん。"

# ウィズ
# だいたい理解しました。\nそういう状況でカズマさんに告白されるわけですね。
294 = "だいたい理解しました。\\nそういう状況でカズマさんに告白されるわけですね。"

# カズマ
# はい、そう！\nというわけで、ウィズ！
311 = "はい、そう！\\nというわけで、ウィズ！"

# ウィズ
# は、はい！
309 = "は、はい！"

# カズマ
# 俺の恋人になってくれ！
337 = "俺の恋人になってくれ！"

# ウィズ
# で、ですが、私は、もう……。
296 = "で、ですが、私は、もう……。"

# カズマ
# 俺だったらお前を幸せにできる！
335 = "俺だったらお前を幸せにできる！"

# ウィズ
# カズマさん……。
327 = "カズマさん……。"

# カズマ
# ウィズ……。
322 = "ウィズ……。"

# ウィズ
# あの、あの！\n顔を近づける理由はなんなのでしょう！
260 = "あの、あの！\\n顔を近づける理由はなんなのでしょう！"

# カズマ
# あ、悪い、入り込みすぎた。
259 = "あ、悪い、入り込みすぎた。"

# ウィズ
# はぁ～、次はどうしたらいいんですか。
310 = "はぁ～、次はどうしたらいいんですか。"

# カズマ
# うーん、そうだなー。\n幼馴染みという設定は破棄！
266 = "うーん、そうだなー。\\n幼馴染みという設定は破棄！"

# ウィズ
# ええ！？
274 = "ええ！？"

# カズマ
# やっぱり高嶺の花だからこそのアイドルだもんな。\nでも、恋人設定は変更無しだからな。
316 = "やっぱり高嶺の花だからこそのアイドルだもんな。\\nでも、恋人設定は変更無しだからな。"

# ウィズ
# ……わかりました。
254 = "……わかりました。"

# カズマ
# じゃあ、俺はアイドルの恋人になりました！
290 = "じゃあ、俺はアイドルの恋人になりました！"

# ウィズ
# は、はい、私はカズマさんの恋人です！
307 = "は、はい、私はカズマさんの恋人です！"

# カズマ
# うーん、アイドルの恋人にして欲しいこと。
267 = "うーん、アイドルの恋人にして欲しいこと。"

# カズマ
# よし、俺のことをお兄ちゃんと呼んでくれ！
318 = "よし、俺のことをお兄ちゃんと呼んでくれ！"

# ウィズ
# えっ、お、お兄ちゃんですか？\nでもそれ、アイドルとなんの関係が？
276 = "えっ、お、お兄ちゃんですか？\\nでもそれ、アイドルとなんの関係が？"

# カズマ
# 需要は多種多様なんだよ。\n幼馴染み風アイドルもいれば妹風アイドルもいる！
387 = "需要は多種多様なんだよ。\\n幼馴染み風アイドルもいれば妹風アイドルもいる！"

# カズマ
# ウィズのキャラ的にはお姉さんアイドルが\n王道なんだろうけど、ここは意表を突いて\n妹アイドルのウィズかなって思ってさ。
323 = "ウィズのキャラ的にはお姉さんアイドルが\\n王道なんだろうけど、ここは意表を突いて\\n妹アイドルのウィズかなって思ってさ。"

# カズマ
# 妹風アイドルのウィズが俺の恋人になった！\nはい、スタート！
342 = "妹風アイドルのウィズが俺の恋人になった！\\nはい、スタート！"

# ウィズ
# え、ええと、それじゃあ。\nお兄――
269 = "え、ええと、それじゃあ。\\nお兄――"

# カズマ
# あ、思いっきり可愛くな！　媚びっ媚びな感じで！\nあと可愛らしいポーズも付けて！
258 = "あ、思いっきり可愛くな！　媚びっ媚びな感じで！\\nあと可愛らしいポーズも付けて！"

# ウィズ
# は、はい……。
305 = "は、はい……。"

# ウィズ
# では、改めて。\nお、お兄ちゃん♪
297 = "では、改めて。\\nお、お兄ちゃん♪"

# カズマ
# うぅ！
264 = "うぅ！"

# ウィズ
# ええ！？　どうして泣いてるんですか？？
275 = "ええ！？　どうして泣いてるんですか？？"

# カズマ
# 最高だ、最高だよ、ウィズ。
345 = "最高だ、最高だよ、ウィズ。"

# ウィズ
# ええと、私には理解をできそうにありません。
273 = "ええと、私には理解をできそうにありません。"

# カズマ
# 歌ってみてくれるか？
346 = "歌ってみてくれるか？"

# ウィズ
# ええ、歌うんですか！？
271 = "ええ、歌うんですか！？"

# カズマ
# 知ってる歌で、\nノリがいいやつならなんでもいいから、\n歌いつつ、こういう風にステップを踏む感じで！
385 = "知ってる歌で、\\nノリがいいやつならなんでもいいから、\\n歌いつつ、こういう風にステップを踏む感じで！"

# ウィズ
# え、ええと、こ、こうですか？\nって言うかカズマさん、変な踊りが上手ですね。
268 = "え、ええと、こ、こうですか？\\nって言うかカズマさん、変な踊りが上手ですね。"

# カズマ
# 変な踊り言うな！\nほら、歌いながらステップ踏んで！
341 = "変な踊り言うな！\\nほら、歌いながらステップ踏んで！"

# ウィズ
# は、はいっ。
308 = "は、はいっ。"

# カズマ
# 俺の事をプロデューサーと呼んでくれ！
336 = "俺の事をプロデューサーと呼んでくれ！"

# ウィズ
# ぷ、ぷろでゅーさー……？
313 = "ぷ、ぷろでゅーさー……？"

# カズマ
# まあなんだ、アイドルの活動方針を決める\nエラい人だ。
314 = "まあなんだ、アイドルの活動方針を決める\\nエラい人だ。"

# カズマ
# なのでこう、尊敬と憧れをこめてだな。
301 = "なのでこう、尊敬と憧れをこめてだな。"

# ウィズ
# は、はあ。ええと……ぷ、プロデューサーさん？
304 = "は、はあ。ええと……ぷ、プロデューサーさん？"

# カズマ
# おおお、いいね！　よし、俺がお前をトップアイドル\nに導いてやるからな！　一緒にアイドルの一番星を\n掴むんだ！
277 = "おおお、いいね！　よし、俺がお前をトップアイドル\\nに導いてやるからな！　一緒にアイドルの一番星を\\n掴むんだ！"

# ウィズ
# はい、プロデューサーさんっ！
312 = "はい、プロデューサーさんっ！"

# カズマ
# うむ、だいぶ恋人アイドルっぽくなったな！
265 = "うむ、だいぶ恋人アイドルっぽくなったな！"

# カズマ
# これも俺の指導の賜物……うん、満足した。\nサンキューな、ウィズ！
281 = "これも俺の指導の賜物……うん、満足した。\\nサンキューな、ウィズ！"

# ウィズ
# え、ええ！？\nこれでお終いでいいんですか！！
270 = "え、ええ！？\\nこれでお終いでいいんですか！！"

# カズマ
# だって店番があるだろ？
295 = "だって店番があるだろ？"

# ウィズ
# あは、あはは、お気遣いありがとうございます。
262 = "あは、あはは、お気遣いありがとうございます。"

[selections]
278 = "お兄ちゃんと呼んでくれ！"
# 346 = "歌ってみてくれるか？"
329 = "プロデューサーと呼んでくれ！"
