# rew_d01.txt.scn

[info]
217 = "rew_d01"

[characters]
300 = "クリス"
298 = "カズマ"
299 = "カズマ（Ｍ）"

[character_subs]
# 298 = "カズマ"

[script]
# lines: 77

# クリス
# 言われたとおり着替えてきたけど。\nこんな格好させて、何をするつもりなのさ。
335 = "言われたとおり着替えてきたけど。\\nこんな格好させて、何をするつもりなのさ。"

# カズマ
# ふふふ、知りたいかい？　知りたいのかい？
293 = "ふふふ、知りたいかい？　知りたいのかい？"

# クリス
# 変なことだったら怒るからね。
305 = "変なことだったら怒るからね。"

# カズマ
# 俺は、男として！
303 = "俺は、男として！"

# クリス
# お、男として！？
258 = "お、男として！？"

# カズマ
# あーん、というものにすごい憧れを持っています。
243 = "あーん、というものにすごい憧れを持っています。"

# クリス
# え？　あ、あ～ん？
255 = "え？　あ、あ～ん？"

# カズマ
# ほら、よくあるだろ？\n恋人同士で食べ物を分けっこする時とか。\nあれだよあれ。
294 = "ほら、よくあるだろ？\\n恋人同士で食べ物を分けっこする時とか。\\nあれだよあれ。"

# クリス
# なるほど、理解したよ。\nつまり、あたしにあーんって食べさせて\n欲しいんだね？
284 = "なるほど、理解したよ。\\nつまり、あたしにあーんって食べさせて\\n欲しいんだね？"

# カズマ
# いや、逆だよ。\n俺がクリスにあーんをしてあげようと\n思ってるんだ！
248 = "いや、逆だよ。\\n俺がクリスにあーんをしてあげようと\\n思ってるんだ！"

# クリス
# ちょ、ちょっと待った！\nなんか色々おかしいよ、それ！
277 = "ちょ、ちょっと待った！\\nなんか色々おかしいよ、それ！"

# カズマ
# そうか？
268 = "そうか？"

# クリス
# だって、これはキミへのご褒美なんだよ？\nそれなのにキミがやるって変じゃない？
273 = "だって、これはキミへのご褒美なんだよ？\\nそれなのにキミがやるって変じゃない？"

# カズマ
# ちっとも変じゃない！\nあーんなんて無防備な姿をさらせるのは\n信頼できる相手にだけだからな！
276 = "ちっとも変じゃない！\\nあーんなんて無防備な姿をさらせるのは\\n信頼できる相手にだけだからな！"

# クリス
# なるほどね。\nつまりキミにはそうやって無防備な姿を\n見せてくれる相手がいないと。
286 = "なるほどね。\\nつまりキミにはそうやって無防備な姿を\\n見せてくれる相手がいないと。"

# カズマ
# うぐっ！
250 = "うぐっ！"

# クリス
# だからご褒美にかこつけて、\nあたしにそんなことをしようって魂胆なんだ。
272 = "だからご褒美にかこつけて、\\nあたしにそんなことをしようって魂胆なんだ。"

# カズマ
# う、うぅ……。
249 = "う、うぅ……。"

# クリス
# つまりキミが望む本当のご褒美は、\n偽りの信頼でその虚栄心を満足させようと――
279 = "つまりキミが望む本当のご褒美は、\\n偽りの信頼でその虚栄心を満足させようと――"

# カズマ
# だー、はっきり言わないでくれ！\nへこむだろ！
274 = "だー、はっきり言わないでくれ！\\nへこむだろ！"

# クリス
# あはは、ごめんごめん。\nまあ、趣旨はわかったからもう何も言わないよ。
241 = "あはは、ごめんごめん。\\nまあ、趣旨はわかったからもう何も言わないよ。"

# クリス
# でも、ひとつだけ質問、いいかな？
280 = "でも、ひとつだけ質問、いいかな？"

# カズマ
# な、なんだよ。
282 = "な、なんだよ。"

# クリス
# この、メイド服を着る理由は？
262 = "この、メイド服を着る理由は？"

# カズマ
# 俺の好みだからだ！
302 = "俺の好みだからだ！"

# クリス
# あは、あはは、正直だねー。
240 = "あは、あはは、正直だねー。"

# カズマ
# じゃあ、行くぞ。\nあーんしてくれ、あーん。
264 = "じゃあ、行くぞ。\\nあーんしてくれ、あーん。"

# クリス
# あーん。
244 = "あーん。"

# カズマ（Ｍ）
# display as カズマ
# （あれ、クリスってこんなに色っぽかったっけ？）
340 = "（あれ、クリスってこんなに色っぽかったっけ？）"

# クリス
# ねえ、ちょっと。\nいつまでこうして待たせるつもりなの？
287 = "ねえ、ちょっと。\\nいつまでこうして待たせるつもりなの？"

# カズマ
# えっ、あっ？　悪い。\nクリスが色っぽくて、つい見とれてた。
254 = "えっ、あっ？　悪い。\\nクリスが色っぽくて、つい見とれてた。"

# クリス
# は、はぁっ！？
288 = "は、はぁっ！？"

# カズマ
# い、いやそうじゃない！\n違う、違うんだ。\nいや、違わなくはないんだけど！
245 = "い、いやそうじゃない！\\n違う、違うんだ。\\nいや、違わなくはないんだけど！"

# クリス
# なるほど、読み違えていたよ。
285 = "なるほど、読み違えていたよ。"

# クリス
# こうやってあたしに恥ずかしい思いをさせるのが、\nキミの本来の目的だったってわけだ。
261 = "こうやってあたしに恥ずかしい思いをさせるのが、\\nキミの本来の目的だったってわけだ。"

# カズマ（Ｍ）
# display as カズマ
# （まずい！　このままじゃ、ドＳの変態に\n　なってしまう！）
344 = "（まずい！　このままじゃ、ドＳの変態に\\n　なってしまう！）"

# カズマ（Ｍ）
# display as カズマ
# （なんとかして誤解を……いや、誤解じゃないけど\n　それを解いてとにかく俺の尊厳を保たないと！）
343 = "（なんとかして誤解を……いや、誤解じゃないけど\\n　それを解いてとにかく俺の尊厳を保たないと！）"

# カズマ
# お、お前ってやっぱり女だったんだな。
257 = "お、お前ってやっぱり女だったんだな。"

# クリス
# え？　何それ、どういう意味。
256 = "え？　何それ、どういう意味。"

# カズマ
# あああ、いや、悪い意味じゃなくて！\n普段はこう、やんちゃって言うか、女の子の\n一面をあんまり見せないだろ！
239 = "あああ、いや、悪い意味じゃなくて！\\n普段はこう、やんちゃって言うか、女の子の\\n一面をあんまり見せないだろ！"

# カズマ
# だから、ドキっとしちゃっていうかさ。\nあっ、きっとあれだな！\n服装補正もあるんだろうな！
271 = "だから、ドキっとしちゃっていうかさ。\\nあっ、きっとあれだな！\\n服装補正もあるんだろうな！"

# カズマ
# やっぱりメイド服はいいよな！\nロングメイドさんもいいけど、\nショートのメイドさんもそれはそれで……。
297 = "やっぱりメイド服はいいよな！\\nロングメイドさんもいいけど、\\nショートのメイドさんもそれはそれで……。"

# クリス
# つまりあたしは、こういう服を着ていないと\n女の子に見えない、そう言いたいわけだね？
278 = "つまりあたしは、こういう服を着ていないと\\n女の子に見えない、そう言いたいわけだね？"

# カズマ
# いや、そういうわけじゃ。
247 = "いや、そういうわけじゃ。"

# クリス
# はいはい、言い訳はいいから。\n早く終わらせちゃって。
291 = "はいはい、言い訳はいいから。\\n早く終わらせちゃって。"

# クリス
# はい、あーん！
290 = "はい、あーん！"

# カズマ
# 髪を伸ばしてみたらどうだ？\nロングも似合うと思うぜ。
337 = "髪を伸ばしてみたらどうだ？\\nロングも似合うと思うぜ。"

# カズマ
# せっかくこんなに綺麗な髪してるんだし、\n短くしてるなんてもったいない。
267 = "せっかくこんなに綺麗な髪してるんだし、\\n短くしてるなんてもったいない。"

# クリス
# 褒めてくれるのは嬉しいけど\n髪を短くしているのには、\nそれなりの理由があるんだよ。
334 = "褒めてくれるのは嬉しいけど\\n髪を短くしているのには、\\nそれなりの理由があるんだよ。"

# クリス
# だいたい、あたしの仕事で髪が長かったら\n動きにくくて仕方ないでしょ。
270 = "だいたい、あたしの仕事で髪が長かったら\\n動きにくくて仕方ないでしょ。"

# カズマ（Ｍ）
# display as カズマ
# （た、確かに……）
342 = "（た、確かに……）"

# クリス
# ほーら、くだらないこと言ってないで、\n早く終わらせちゃってよ。
295 = "ほーら、くだらないこと言ってないで、\\n早く終わらせちゃってよ。"

# クリス
# はい、あーん！
# 290 = "はい、あーん！"

# カズマ
# お前は逸材だ！
260 = "お前は逸材だ！"

# クリス
# ど、どうしたの急に！
281 = "ど、どうしたの急に！"

# カズマ
# クリス、お前は１００年に１度の──\nいや、１０００年に１度のメイドの素質がある！
301 = "クリス、お前は１００年に１度の──\\nいや、１０００年に１度のメイドの素質がある！"

# カズマ
# さあ、俺と一緒にメイド道を極めるため\n新しい世界へ踏み出そう！
263 = "さあ、俺と一緒にメイド道を極めるため\\n新しい世界へ踏み出そう！"

# クリス
# それって、喜んでもいいのかなぁ。
269 = "それって、喜んでもいいのかなぁ。"

# カズマ
# 当然だろ。
307 = "当然だろ。"

# クリス
# じゃあさ、あたしのどういう部分を見て、\nそう思ったのか教えてよ。
265 = "じゃあさ、あたしのどういう部分を見て、\\nそう思ったのか教えてよ。"

# カズマ
# ええと、それは。
253 = "ええと、それは。"

# クリス
# ほーら、言えない。\nやっぱり口からでまかせだったんだ。
296 = "ほーら、言えない。\\nやっぱり口からでまかせだったんだ。"

# カズマ
# ち、違うって！\n普通に可愛いからって思っただけだよ！
275 = "ち、違うって！\\n普通に可愛いからって思っただけだよ！"

# クリス
# え……。
251 = "え……。"

# カズマ（Ｍ）
# display as カズマ
# （あ……）
339 = "（あ……）"

# クリス
# え、ええと、もういいから。\nこんな恥ずかしいこと早く終わらせちゃって！
252 = "え、ええと、もういいから。\\nこんな恥ずかしいこと早く終わらせちゃって！"

# クリス
# は、はい、あーん！
289 = "は、はい、あーん！"

# カズマ
# じゃあ改めていくぞ。
266 = "じゃあ改めていくぞ。"

# クリス
# ふぁーい。
292 = "ふぁーい。"

# カズマ（Ｍ）
# display as カズマ
# （……それにしてもこの姿のクリスは色々と\n　くるものがあるな）
338 = "（……それにしてもこの姿のクリスは色々と\\n　くるものがあるな）"

# カズマ（Ｍ）
# display as カズマ
# （目を閉じて無抵抗のまま与えられた物を\n　疑いもなく咀嚼する女の子……）
345 = "（目を閉じて無抵抗のまま与えられた物を\\n　疑いもなく咀嚼する女の子……）"

# クリス
# あむあむ……んっ。\nこれでいいかな。
242 = "あむあむ……んっ。\\nこれでいいかな。"

# カズマ
# …………。
238 = "…………。"

# クリス
# な、何。
283 = "な、何。"

# カズマ
# いや、あはは、なんでもないって！
246 = "いや、あはは、なんでもないって！"

# クリス
# ？？
346 = "？？"

# カズマ（Ｍ）
# display as カズマ
# （い、いかん、\n　つい見とれてしまった……）
341 = "（い、いかん、\\n　つい見とれてしまった……）"

[selections]
259 = "お前ってやっぱり女だったんだな"
336 = "髪を伸ばしてみたらどうだ？"
# 260 = "お前は逸材だ！"
