# rew_c03.txt.scn

[info]
221 = "rew_c03"

[characters]
296 = "ダクネス"
294 = "カズマ"
295 = "カズマ（Ｍ）"

[character_subs]
# 294 = "カズマ"

[script]
# lines: 89

# ダクネス
# 要望通りに着替えて来たが……。
357 = "要望通りに着替えて来たが……。"

# カズマ
# おう、似合ってるぞ、ダクネス。
256 = "おう、似合ってるぞ、ダクネス。"

# ダクネス
# 本気でそう思ってるのか！\nからかってるんじゃないのか！
308 = "本気でそう思ってるのか！\\nからかってるんじゃないのか！"

# ダクネス
# 本当は、似合いもしない服を着させて、\n私を辱めようという魂胆なのだろう！
307 = "本当は、似合いもしない服を着させて、\\n私を辱めようという魂胆なのだろう！"

# ダクネス
# この後、私を街へ連れ出し、\n年甲斐もない姿を民衆の目に晒して――
258 = "この後、私を街へ連れ出し、\\n年甲斐もない姿を民衆の目に晒して――"

# カズマ
# よし、黙ろうか。\nあと、顔を近づけすぎだ！
290 = "よし、黙ろうか。\\nあと、顔を近づけすぎだ！"

# ダクネス
# あっ、すまない。
247 = "あっ、すまない。"

# カズマ（Ｍ）
# display as カズマ
# （こいつは容姿も気立てもいい。\n　家柄だって申し分ない）
370 = "（こいつは容姿も気立てもいい。\\n　家柄だって申し分ない）"

# カズマ（Ｍ）
# display as カズマ
# （それなのにっ、それなのにっ！）
374 = "（それなのにっ、それなのにっ！）"

# カズマ（Ｍ）
# display as カズマ
# （どうして口を開くと\n　残念になってしまうんだ！）
376 = "（どうして口を開くと\\n　残念になってしまうんだ！）"

# カズマ（Ｍ）
# display as カズマ
# （本当に惜しい！　心底惜しい！\n　アイドルとして逸材なのに！）
382 = "（本当に惜しい！　心底惜しい！\\n　アイドルとして逸材なのに！）"

# ダクネス
# はぁはぁ、黙ったと思ったら、\nその失望しきった視線か。
283 = "はぁはぁ、黙ったと思ったら、\\nその失望しきった視線か。"

# ダクネス
# 本当に引き出しの数が多いな、カズマは。
306 = "本当に引き出しの数が多いな、カズマは。"

# カズマ（Ｍ）
# display as カズマ
# （こいつっ、嬉しそうな顔しやがって！）
369 = "（こいつっ、嬉しそうな顔しやがって！）"

# カズマ（Ｍ）
# display as カズマ
# （だが俺は諦めないぞ！\n　必ずこの素材を活かせる方法を\n　見つけ出してみせる！）
375 = "（だが俺は諦めないぞ！\\n　必ずこの素材を活かせる方法を\\n　見つけ出してみせる！）"

# カズマ（Ｍ）
# display as カズマ
# （そのためにはまず、\n　ダクネスの変態的欲求をどうにかしないとな）
373 = "（そのためにはまず、\\n　ダクネスの変態的欲求をどうにかしないとな）"

# ダクネス
# それで？\nこんな格好をさせて、何をするつもりなんだ？
270 = "それで？\\nこんな格好をさせて、何をするつもりなんだ？"

# カズマ
# では、やることを発表する。\nそれはズバリじゃんけんだ。
277 = "では、やることを発表する。\\nそれはズバリじゃんけんだ。"

# ダクネス
# そんなことでいいのか？
272 = "そんなことでいいのか？"

# カズマ
# ただし、負けた方が罰を受ける。\nそれならスリルがあって面白いだろ？
273 = "ただし、負けた方が罰を受ける。\\nそれならスリルがあって面白いだろ？"

# ダクネス
# ああ、確かに。
245 = "ああ、確かに。"

# カズマ（Ｍ）
# display as カズマ
# （ふふふ、覚悟しておけよ、ダクネス。\n　俺が本当の羞恥というものを教えてやる！）
378 = "（ふふふ、覚悟しておけよ、ダクネス。\\n　俺が本当の羞恥というものを教えてやる！）"

# カズマ
# じゃあ、さっそくいくぞ。\nじゃんけーん、ぽいっと。
265 = "じゃあ、さっそくいくぞ。\\nじゃんけーん、ぽいっと。"

# ダクネス
# あっ……。
246 = "あっ……。"

# カズマ
# 俺の勝ちい！！
298 = "俺の勝ちい！！"

# ダクネス
# くぅぅっ、なんてことだ。
257 = "くぅぅっ、なんてことだ。"

# カズマ
# じゃあ、罰だな。
266 = "じゃあ、罰だな。"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスが本当に恥ずかしがりそうなこと……）
379 = "（ダクネスが本当に恥ずかしがりそうなこと……）"

# ダクネス
# さ、さあ、なんでも命じてくれ！
259 = "さ、さあ、なんでも命じてくれ！"

# カズマ（Ｍ）
# display as カズマ
# （あ、あれ？　何も思いつかないぞ？）
362 = "（あ、あれ？　何も思いつかないぞ？）"

# ダクネス
# どうしたカズマ！\n私はどんな辱めも受け入れる覚悟があるぞ！
279 = "どうしたカズマ！\\n私はどんな辱めも受け入れる覚悟があるぞ！"

# カズマ
# じゃ、じゃあ、えっと……。
263 = "じゃ、じゃあ、えっと……。"

# カズマ
# お、俺に告白するんだ！
255 = "お、俺に告白するんだ！"

# ダクネス
# 告白？\n私はカズマに隠していることなど何もないが。
301 = "告白？\\n私はカズマに隠していることなど何もないが。"

# カズマ
# 罪じゃなくて、愛の告白だよ！
355 = "罪じゃなくて、愛の告白だよ！"

# ダクネス
# な、何ぃ！？
281 = "な、何ぃ！？"

# カズマ（Ｍ）
# display as カズマ
# （おっ、これは結構ダメージを与えられるか？）
367 = "（おっ、これは結構ダメージを与えられるか？）"

# ダクネス
# な、なあ、これはカズマへのご褒美なのだろう？\nそんなことを私に言わせて、何が嬉しいと\nいうんだ。
280 = "な、なあ、これはカズマへのご褒美なのだろう？\\nそんなことを私に言わせて、何が嬉しいと\\nいうんだ。"

# カズマ
# 美人に好きだと言われて喜ばない男がいるか！
356 = "美人に好きだと言われて喜ばない男がいるか！"

# ダクネス
# び、美人！？\nそそ、そういうのはやめてくれ……。
285 = "び、美人！？\\nそそ、そういうのはやめてくれ……。"

# カズマ（Ｍ）
# display as カズマ
# （いいぞいいぞ、この調子だ）
364 = "（いいぞいいぞ、この調子だ）"

# カズマ
# さあさあ、早く告白してくれよ。\nなんだったら俺が台詞を考えてやろうか？
261 = "さあさあ、早く告白してくれよ。\\nなんだったら俺が台詞を考えてやろうか？"

# ダクネス
# それはいい！\n罰だからな、それくらいは自分でやる。
271 = "それはいい！\\n罰だからな、それくらいは自分でやる。"

# カズマ
# じゃあ、お願いします。
264 = "じゃあ、お願いします。"

# ダクネス
# ん……カズマ？
293 = "ん……カズマ？"

# カズマ
# お、おう、なんだ？
254 = "お、おう、なんだ？"

# ダクネス
# 好き……だ。
302 = "好き……だ。"

# カズマ（Ｍ）
# display as カズマ
# （あ、あれ？　これって俺も恥ずかしいんだけど）
360 = "（あ、あれ？　これって俺も恥ずかしいんだけど）"

# ダクネス
# 愛して……いるぞ。
305 = "愛して……いるぞ。"

# カズマ（Ｍ）
# display as カズマ
# （いかん！　俺まで頭が熱くなってきた！）
365 = "（いかん！　俺まで頭が熱くなってきた！）"

# ダクネス
# ふ、ふふふ、なるほど、そういうことか。
286 = "ふ、ふふふ、なるほど、そういうことか。"

# カズマ
# え？
253 = "え？"

# ダクネス
# 偽りの告白をさせて、\n私に罪の意識を与えるつもりなんだな。
299 = "偽りの告白をさせて、\\n私に罪の意識を与えるつもりなんだな。"

# カズマ
# 語尾ににゃんとつけて喋ってくれ！
359 = "語尾ににゃんとつけて喋ってくれ！"

# ダクネス
# え、どういうことだ？
251 = "え、どういうことだ？"

# カズマ
# ちっがーう！\nそこは、どういうことですかにゃん！　だ！
275 = "ちっがーう！\\nそこは、どういうことですかにゃん！　だ！"

# ダクネス
# そ、それはさすがに恥ずかしいのだが。
268 = "そ、それはさすがに恥ずかしいのだが。"

# カズマ
# 恥ずかしくなきゃ罰にならないだろ。\nほーらほーら、早く言ってみてくれよ。
304 = "恥ずかしくなきゃ罰にならないだろ。\\nほーらほーら、早く言ってみてくれよ。"

# ダクネス
# わ、わかった。\nじゃなくて――
291 = "わ、わかった。\\nじゃなくて――"

# ダクネス
# わ、わかりました……にゃん。
292 = "わ、わかりました……にゃん。"

# カズマ
# うっ！？
250 = "うっ！？"

# ダクネス
# どうかしましたかにゃん？
278 = "どうかしましたかにゃん？"

# カズマ（Ｍ）
# display as カズマ
# （くっ、これはなんというか\n　俺にも変なダメージが！！）
368 = "（くっ、これはなんというか\\n　俺にも変なダメージが！！）"

# ダクネス
# ふふ、さすがカズマだな。
287 = "ふふ、さすがカズマだな。"

# カズマ（Ｍ）
# display as カズマ
# （え？）
366 = "（え？）"

# ダクネス
# 私は可愛らしさとはほど遠い。\nその私にこのような罰を与えるとは――
353 = "私は可愛らしさとはほど遠い。\\nその私にこのような罰を与えるとは――"

# ダクネス
# さすが私の見込んだ男だ……にゃん。
262 = "さすが私の見込んだ男だ……にゃん。"

# カズマ
# 結婚してください！
354 = "結婚してください！"

# ダクネス
# ……は？
244 = "……は？"

# カズマ（Ｍ）
# display as カズマ
# （しまったー、勢いのまま言っちまった！！）
372 = "（しまったー、勢いのまま言っちまった！！）"

# ダクネス
# そ、そんな、いくら罰でも、それは。
269 = "そ、そんな、いくら罰でも、それは。"

# カズマ（Ｍ）
# display as カズマ
# （あ、あれ？　意外に効果あり？）
363 = "（あ、あれ？　意外に効果あり？）"

# ダクネス
# だいたいカズマはこれからもっと素敵な女性と\n出会えるかもしれないだろう？
274 = "だいたいカズマはこれからもっと素敵な女性と\\n出会えるかもしれないだろう？"

# ダクネス
# いくら私に罰を与えたいとはいえ、\n人生を棒に振ってまでやることではないと思うぞ。
248 = "いくら私に罰を与えたいとはいえ、\\n人生を棒に振ってまでやることではないと思うぞ。"

# カズマ
# いや、重く受けとめてすぎですよ、ダクネスさん。
249 = "いや、重く受けとめてすぎですよ、ダクネスさん。"

# ダクネス
# そ、それに、ふふ、罰にかこつけて婚姻の強要とは\n男としてどうかと思うぞ。
267 = "そ、それに、ふふ、罰にかこつけて婚姻の強要とは\\n男としてどうかと思うぞ。"

# ダクネス
# まあ、カズマがどうしてもと言うのなら、\nか、か、考えなくもないが。
289 = "まあ、カズマがどうしてもと言うのなら、\\nか、か、考えなくもないが。"

# カズマ（Ｍ）
# display as カズマ
# （あ、あれ？　もしかして喜んでる？）
361 = "（あ、あれ？　もしかして喜んでる？）"

# ダクネス
# さあ、カズマ！\n２回戦目と行こうじゃないか！
260 = "さあ、カズマ！\\n２回戦目と行こうじゃないか！"

# カズマ（Ｍ）
# display as カズマ
# （の、ノリノリだーーーー！！）
377 = "（の、ノリノリだーーーー！！）"

# ダクネス
# 私はチョキを出す！　チョキを出すからな！
352 = "私はチョキを出す！　チョキを出すからな！"

# カズマ（Ｍ）
# display as カズマ
# （しかも負けるつもりだし！）
371 = "（しかも負けるつもりだし！）"

# ダクネス
# では、いくぞ、じゃんけん！
276 = "では、いくぞ、じゃんけん！"

# カズマ
# ま、待った！
288 = "ま、待った！"

# ダクネス
# なんだ、どうした？
282 = "なんだ、どうした？"

# カズマ
# ええと、もういいから、出て行ってくれる？
252 = "ええと、もういいから、出て行ってくれる？"

# ダクネス
# はぁん！　まさかの拒絶！
284 = "はぁん！　まさかの拒絶！"

# カズマ（Ｍ）
# display as カズマ
# （ダメだ。俺には手に負えない……）
380 = "（ダメだ。俺には手に負えない……）"

# カズマ（Ｍ）
# display as カズマ
# （変態アイドルなんて、需要ないよな……）
381 = "（変態アイドルなんて、需要ないよな……）"

[selections]
297 = "俺に告白するんだ！"
358 = "語尾ににゃんとつけてくれ！"
# 354 = "結婚してください！"
