# rew_b03.txt.scn

[info]
219 = "rew_b03"

[characters]
302 = "めぐみん"
308 = "カズマ"
310 = "カズマ（Ｍ）"

[character_subs]
# 308 = "カズマ"

[script]
# lines: 80

# めぐみん
# まったく、またこんな服を着させて\nいったい何をたくらんでいるんですか。
299 = "まったく、またこんな服を着させて\\nいったい何をたくらんでいるんですか。"

# めぐみん
# あっ！　先に言っておきますけど、\nもうアイドルなんてやりませんからね！
245 = "あっ！　先に言っておきますけど、\\nもうアイドルなんてやりませんからね！"

# カズマ
# なんでだよ。\nその格好、結構似合ってるのにもったいない。
289 = "なんでだよ。\\nその格好、結構似合ってるのにもったいない。"

# めぐみん
# そう言ってくれるのは嬉しいのですが、\nやはりこういう服装には抵抗があるのです。
263 = "そう言ってくれるのは嬉しいのですが、\\nやはりこういう服装には抵抗があるのです。"

# カズマ
# 眼帯の方が十分に恥ずかしいと思うが。
353 = "眼帯の方が十分に恥ずかしいと思うが。"

# めぐみん
# むっ、何か言いましたか？
301 = "むっ、何か言いましたか？"

# カズマ
# いーや、なんにも。
248 = "いーや、なんにも。"

# めぐみん
# それで、私は何をすれば良いんですか？
268 = "それで、私は何をすれば良いんですか？"

# カズマ
# ふふふふふ、これからめぐみんには\n俺専用のアイドルになってもらおうと思ってる！
293 = "ふふふふふ、これからめぐみんには\\n俺専用のアイドルになってもらおうと思ってる！"

# めぐみん
# カズマの前で歌ったり踊ったりしろと\n言うのですか？
309 = "カズマの前で歌ったり踊ったりしろと\\n言うのですか？"

# カズマ
# いや、そこはめぐみんに求めていない。
247 = "いや、そこはめぐみんに求めていない。"

# めぐみん
# では、どうしろというのです？
279 = "では、どうしろというのです？"

# カズマ
# 俺の国では、アイドルはみんなの人気者だ。\nそりゃもうみんなに愛されている。
318 = "俺の国では、アイドルはみんなの人気者だ。\\nそりゃもうみんなに愛されている。"

# めぐみん
# ほほ～、この私に相応しいではありませんか。
295 = "ほほ～、この私に相応しいではありませんか。"

# カズマ
# アイドルと呼ばれる人間はたくさんいるが、\nその中でもトップクラスの連中には共通して\n言えることがある。
306 = "アイドルと呼ばれる人間はたくさんいるが、\\nその中でもトップクラスの連中には共通して\\n言えることがある。"

# カズマ
# それは神対応を心掛けているということだ！
270 = "それは神対応を心掛けているということだ！"

# めぐみん
# 神対応？
356 = "神対応？"

# カズマ
# ファン――この場合俺になるわけだが、\nファンを大切にしているという意味だ。
314 = "ファン――この場合俺になるわけだが、\\nファンを大切にしているという意味だ。"

# カズマ
# 大切にしているがゆえ、\n非常に献身的で従順だとも言える。
321 = "大切にしているがゆえ、\\n非常に献身的で従順だとも言える。"

# めぐみん
# なるほど、ただ歌や踊りが上手いだけでは\nトップに立てないというわけですね。
284 = "なるほど、ただ歌や踊りが上手いだけでは\\nトップに立てないというわけですね。"

# カズマ
# よって、めぐみんには\n正しい神対応の作法を教えよう。
305 = "よって、めぐみんには\\n正しい神対応の作法を教えよう。"

# めぐみん
# おー、それを習得すれば、みんなから愛される\n存在になるのですね！
253 = "おー、それを習得すれば、みんなから愛される\\n存在になるのですね！"

# カズマ
# その可能性は極めて高いな！
264 = "その可能性は極めて高いな！"

# めぐみん
# それで何をすればいいのです！
269 = "それで何をすればいいのです！"

# カズマ（Ｍ）
# display as カズマ
# （こんな嘘にまんまとハマるとは、\n　なんてチョロいんだ）
359 = "（こんな嘘にまんまとハマるとは、\\n　なんてチョロいんだ）"

# カズマ（Ｍ）
# display as カズマ
# （チョロすぎて多少の罪悪感が\n　ないわけでもないが、\n　ここはあえていく！）
360 = "（チョロすぎて多少の罪悪感が\\n　ないわけでもないが、\\n　ここはあえていく！）"

# カズマ
# 取り出したるこれは、\n今巷で売れている棒状のお菓子\n『ニョッキー』だ。
319 = "取り出したるこれは、\\n今巷で売れている棒状のお菓子\\n『ニョッキー』だ。"

# めぐみん
# それカリカリとした食感が\nクセになるんですよね。\nそれをどうするんです？
273 = "それカリカリとした食感が\\nクセになるんですよね。\\nそれをどうするんです？"

# カズマ
# ファンとアイドルの定番の交流だ。\n親睦を深めるにはゲームが一番！\nそこで『ニョッキーゲーム』をしようと思う。
315 = "ファンとアイドルの定番の交流だ。\\n親睦を深めるにはゲームが一番！\\nそこで『ニョッキーゲーム』をしようと思う。"

# めぐみん
# ゲームと言うからには\nルールが存在するはず。\n説明してもらいましょうか、カズマ！
311 = "ゲームと言うからには\\nルールが存在するはず。\\n説明してもらいましょうか、カズマ！"

# カズマ
# やる気満々じゃないか。
303 = "やる気満々じゃないか。"

# めぐみん
# 私は常にやる気に満ちていますよ！
357 = "私は常にやる気に満ちていますよ！"

# カズマ
# ニョッキーの両端をくわえて\n同時に食べ進めていくゲームなんだが、\n勝敗はどちらがより多く食べたかで決まる！
313 = "ニョッキーの両端をくわえて\\n同時に食べ進めていくゲームなんだが、\\n勝敗はどちらがより多く食べたかで決まる！"

# めぐみん
# ずいぶんと簡単ですね。
259 = "ずいぶんと簡単ですね。"

# カズマ
# ゲームはシンプルな物ほど\n熱中しやすいもんだからな。
312 = "ゲームはシンプルな物ほど\\n熱中しやすいもんだからな。"

# めぐみん
# なるほど、一理あります。
285 = "なるほど、一理あります。"

# カズマ
# というわけで、\n俺はこっちをくわえるから、\nめぐみんはそっちな。
280 = "というわけで、\\n俺はこっちをくわえるから、\\nめぐみんはそっちな。"

# めぐみん
# ふふふ、負けませんよ！
292 = "ふふふ、負けませんよ！"

# カズマ
# それじゃ――\nスタート！
267 = "それじゃ――\\nスタート！"

# めぐみん
# はむはむはむはむはむはむ……！
291 = "はむはむはむはむはむはむ……！"

# カズマ
# あむあむあむあむあむあむ……！
246 = "あむあむあむあむあむあむ……！"

# めぐみん
# はむはむはむはむ……はむ？
290 = "はむはむはむはむ……はむ？"

# めぐみん
# ちょ、ちょっと待ってください！\nこのままでは\n唇が触れてしまいますよ！！
275 = "ちょ、ちょっと待ってください！\\nこのままでは\\n唇が触れてしまいますよ！！"

# カズマ
# それがアイドルの仕事だよ。
266 = "それがアイドルの仕事だよ。"

# めぐみん
# これが……\nこんな破廉恥なことが\n仕事だというのですか？
256 = "これが……\\nこんな破廉恥なことが\\n仕事だというのですか？"

# カズマ
# そうだぞ、人気者になるのは大変なんだ。\nこの試練を乗り越えた者こそ\n真のアイドルになれる！
262 = "そうだぞ、人気者になるのは大変なんだ。\\nこの試練を乗り越えた者こそ\\n真のアイドルになれる！"

# めぐみん
# 試練を乗り越えれば……、\n乗り越えれば――
358 = "試練を乗り越えれば……、\\n乗り越えれば――"

# カズマ
# ほら早く早くぅ、\nゴールはもう目の前だぞ。
296 = "ほら早く早くぅ、\\nゴールはもう目の前だぞ。"

# めぐみん
# うぅ～うぅ～……！！
250 = "うぅ～うぅ～……！！"

# めぐみん
# こんなの無理に決まっているじゃないですか！
257 = "こんなの無理に決まっているじゃないですか！"

# カズマ
# なんだなんだ、だらしがないぞ、\nこんな試練ひとつ乗り越えられないのか？
287 = "なんだなんだ、だらしがないぞ、\\nこんな試練ひとつ乗り越えられないのか？"

# めぐみん
# な、なにお！\nしかし、これはやはり……。
282 = "な、なにお！\\nしかし、これはやはり……。"

# カズマ
# それもまた結果のひとつだ。
272 = "それもまた結果のひとつだ。"

# めぐみん
# なんですか、それは！？\nこれが、こんなものが\n結果のひとつだと言うのですか！？
288 = "なんですか、それは！？\\nこれが、こんなものが\\n結果のひとつだと言うのですか！？"

# カズマ
# おいおい、俺は別に無理強いをしたわけじゃ\nないだろ？
252 = "おいおい、俺は別に無理強いをしたわけじゃ\\nないだろ？"

# カズマ
# むしろやる気になってたのはめぐみんじゃないか。
300 = "むしろやる気になってたのはめぐみんじゃないか。"

# カズマ
# なのに今更泣き言なんて言わないよな？\nお前はそんな身勝手なやつじゃないだろ？
283 = "なのに今更泣き言なんて言わないよな？\\nお前はそんな身勝手なやつじゃないだろ？"

# めぐみん
# そ、それは……。
260 = "そ、それは……。"

# カズマ
# ほら早く早くぅ、\nゴールはもう目の前だぞ。
# 296 = "ほら早く早くぅ、\\nゴールはもう目の前だぞ。"

# めぐみん
# こ、このままではカズマと、\nキ、キスを――
254 = "こ、このままではカズマと、\\nキ、キスを――"

# カズマ
# さあ、遠慮なく飛び込んでこいよ～。
258 = "さあ、遠慮なく飛び込んでこいよ～。"

# めぐみん
# ついちゃう……、ついてしまう！
276 = "ついちゃう……、ついてしまう！"

# カズマ
# 神対応とはそういうことだ。
355 = "神対応とはそういうことだ。"

# めぐみん
# こ、これが神対応？
255 = "こ、これが神対応？"

# カズマ
# そうだ、これを乗り越えてこそ\nアイドルの頂点に立てるんだぞ！
261 = "そうだ、これを乗り越えてこそ\\nアイドルの頂点に立てるんだぞ！"

# めぐみん
# あ、アイドルの頂点……。
242 = "あ、アイドルの頂点……。"

# カズマ
# ああ、めぐみんにはその素質がある。\nだから一緒にこの試練を乗り越えよう！
244 = "ああ、めぐみんにはその素質がある。\\nだから一緒にこの試練を乗り越えよう！"

# めぐみん
# ですが、このままでは……、\nこのままでは――
278 = "ですが、このままでは……、\\nこのままでは――"

# カズマ
# ほーら、あともう少し、\nゴールはもう目の前だぞー。
297 = "ほーら、あともう少し、\\nゴールはもう目の前だぞー。"

# めぐみん
# どうすれば！\n私はどうすれば！？
281 = "どうすれば！\\n私はどうすれば！？"

# カズマ
# ついちゃうぞ？\nもうあとひと噛みで\n唇がくっついちゃうぞ？
277 = "ついちゃうぞ？\\nもうあとひと噛みで\\n唇がくっついちゃうぞ？"

# めぐみん
# だーーーー、\nやっぱり無理です！\nできるわけないじゃないですか！
274 = "だーーーー、\\nやっぱり無理です！\\nできるわけないじゃないですか！"

# カズマ
# やれやれ、\n立派なアイドルになりたくはないのか？
304 = "やれやれ、\\n立派なアイドルになりたくはないのか？"

# めぐみん
# なれなくて結構です！\n私はアークウィザード、\nこの職業に誇りを持っているのですから！
286 = "なれなくて結構です！\\n私はアークウィザード、\\nこの職業に誇りを持っているのですから！"

# カズマ
# アイドルのめぐみんもいけると思うんだけどなー。
307 = "アイドルのめぐみんもいけると思うんだけどなー。"

# めぐみん
# え……そうですか？
251 = "え……そうですか？"

# カズマ
# あ、今、迷ったろ。
243 = "あ、今、迷ったろ。"

# めぐみん
# ま、迷ってませんよ、失礼な！
298 = "ま、迷ってませんよ、失礼な！"

# カズマ
# へー。
294 = "へー。"

# めぐみん
# うぅ、いじわるなカズマは嫌いです。
249 = "うぅ、いじわるなカズマは嫌いです。"

[selections]
265 = "それがアイドルの仕事だよ"
271 = "それもまた結果のひとつだ"
354 = "神対応とはそういうことだ"
