# rew_d09.txt.scn

[info]
223 = "rew_d09"

[characters]
317 = "クリス"
312 = "カズマ"
314 = "カズマ（Ｍ）"
310 = "ウィズ"

[character_subs]
# 312 = "カズマ"

[script]
# lines: 82

# クリス
# さーて、何を命令したっていいんだよね？
283 = "さーて、何を命令したっていいんだよね？"

# カズマ
# おう、なんでもいいぞ。\nどんとこい。
276 = "おう、なんでもいいぞ。\\nどんとこい。"

# カズマ（Ｍ）
# display as カズマ
# （お仕置きか……。\n　まあ、相手はクリスだしそこまで酷いことは\n　要求してこないだろ）
364 = "（お仕置きか……。\\n　まあ、相手はクリスだしそこまで酷いことは\\n　要求してこないだろ）"

# クリス
# けどさ、特にして欲しいことってないんだよね。\nどうしようかな。
278 = "けどさ、特にして欲しいことってないんだよね。\\nどうしようかな。"

# クリス
# クエストに付き合ってもらうとか……\nううん、ダメだな。\nあたしとカズマじゃ効率悪いや。
316 = "クエストに付き合ってもらうとか……\\nううん、ダメだな。\\nあたしとカズマじゃ効率悪いや。"

# クリス
# あ、でもカズマを囮にしてその間に進めば\nあたしたちだけでもなんとかなるかも？
256 = "あ、でもカズマを囮にしてその間に進めば\\nあたしたちだけでもなんとかなるかも？"

# カズマ（Ｍ）
# display as カズマ
# （前言撤回！\n　やっぱりこの世界の人間にろくなやつはいねえ！）
375 = "（前言撤回！\\n　やっぱりこの世界の人間にろくなやつはいねえ！）"

# クリス
# なーんて、冗談だよ冗談。\nキミには買い物に付き合ってもらうよ。
301 = "なーんて、冗談だよ冗談。\\nキミには買い物に付き合ってもらうよ。"

# カズマ（Ｍ）
# display as カズマ
# （つまり荷物持ちってことか。\n　それならまあ、わからんでもない）
368 = "（つまり荷物持ちってことか。\\n　それならまあ、わからんでもない）"

# カズマ
# じゃあ、どこに行くんだ？
285 = "じゃあ、どこに行くんだ？"

# クリス
# どこ行こうか？
296 = "どこ行こうか？"

# カズマ
# 行きたいところがあるんじゃないのか？
359 = "行きたいところがあるんじゃないのか？"

# クリス
# 別にそういうわけじゃないんだよね。\nただ、たまにはぶらぶらするのもいいかなって。
322 = "別にそういうわけじゃないんだよね。\\nただ、たまにはぶらぶらするのもいいかなって。"

# カズマ
# それ、お仕置きになるのか？
293 = "それ、お仕置きになるのか？"

# クリス
# もちろん。\n時間を浪費するっていうお仕置きだよ。\n今日１日、キミの時間はあたしのものってこと。
308 = "もちろん。\\n時間を浪費するっていうお仕置きだよ。\\n今日１日、キミの時間はあたしのものってこと。"

# カズマ（Ｍ）
# display as カズマ
# （……なんだかよくわからんが、\n　それでクリスが満足するならいいか）
361 = "（……なんだかよくわからんが、\\n　それでクリスが満足するならいいか）"

# クリス
# よし、じゃあ出かけようか！
309 = "よし、じゃあ出かけようか！"

# クリス
# こんにちはー。
280 = "こんにちはー。"

# ウィズ
# あら、クリスさん、それにカズマさんも。\n何かご入り用ですか？
266 = "あら、クリスさん、それにカズマさんも。\\n何かご入り用ですか？"

# カズマ
# いや、俺はただの付き添い。\nクリスがこの店に来たいって言ってたからさ。
267 = "いや、俺はただの付き添い。\\nクリスがこの店に来たいって言ってたからさ。"

# ウィズ
# あら、そうなんですね。\n何かお探しなんですか？
265 = "あら、そうなんですね。\\n何かお探しなんですか？"

# クリス
# これっていうのはないんだけど、\n冒険に役立つ新商品があるかなって思って。
279 = "これっていうのはないんだけど、\\n冒険に役立つ新商品があるかなって思って。"

# ウィズ
# そうですね、それならこちらはいかがでしょう。\n旅先で使える野外宿泊用の簡易トイレです。
292 = "そうですね、それならこちらはいかがでしょう。\\n旅先で使える野外宿泊用の簡易トイレです。"

# カズマ（Ｍ）
# display as カズマ
# （ト、トイレ？）
373 = "（ト、トイレ？）"

# ウィズ
# 箱を開けるだけですぐ完成するんですよ。\n水洗仕様ですしコンパクトにまとまっていて\nおススメです。
358 = "箱を開けるだけですぐ完成するんですよ。\\n水洗仕様ですしコンパクトにまとまっていて\\nおススメです。"

# カズマ
# なあ、ウィズ。\nそれってこの間バニルが返品しようと\nしてたやつじゃないのか？
297 = "なあ、ウィズ。\\nそれってこの間バニルが返品しようと\\nしてたやつじゃないのか？"

# ウィズ
# えっ、せっかく仕入れてきたのに\nどうして返品してしまうんですか？
273 = "えっ、せっかく仕入れてきたのに\\nどうして返品してしまうんですか？"

# ウィズ
# あ、でもなぜか、丁寧に箱に詰められて\nいたんですよね。
255 = "あ、でもなぜか、丁寧に箱に詰められて\\nいたんですよね。"

# カズマ（Ｍ）
# display as カズマ
# （やっぱりそうだ。\n　確かあれ、使うとモンスターをおびき寄せて\n　大量の水が湧き出るってやつだよな）
371 = "（やっぱりそうだ。\\n　確かあれ、使うとモンスターをおびき寄せて\\n　大量の水が湧き出るってやつだよな）"

# カズマ
# なあ、クリス。\nそれ買うのか？
298 = "なあ、クリス。\\nそれ買うのか？"

# クリス
# 便利そうだから気になるけど、\nしばらく遠征する予定はないんだよね。
320 = "便利そうだから気になるけど、\\nしばらく遠征する予定はないんだよね。"

# カズマ
# ならやめとけ。というか、この店で\n目新しいアイテムを買う時はもう１人の店員が\nいる時にしたほうがいいぞ、マジで。
300 = "ならやめとけ。というか、この店で\\n目新しいアイテムを買う時はもう１人の店員が\\nいる時にしたほうがいいぞ、マジで。"

# クリス
# へえ、そうなんだ。
305 = "へえ、そうなんだ。"

# カズマ（Ｍ）
# display as カズマ
# （ウィズの仕入れてくるアイテムは使えない物が\n　多いんだよな。しかも、ただ使えないだけじゃ\n　なくて甚大な被害をもたらす物という……）
372 = "（ウィズの仕入れてくるアイテムは使えない物が\\n　多いんだよな。しかも、ただ使えないだけじゃ\\n　なくて甚大な被害をもたらす物という……）"

# クリス
# ねぇねぇ、カズマ。\nそろそろ何か食べない？\nあたし、お腹すいちゃった。
302 = "ねぇねぇ、カズマ。\\nそろそろ何か食べない？\\nあたし、お腹すいちゃった。"

# カズマ
# そういえばそろそろ昼飯の時間か。
290 = "そういえばそろそろ昼飯の時間か。"

# クリス
# うんうん。\nそれじゃ酒場にでも行こうか。
271 = "うんうん。\\nそれじゃ酒場にでも行こうか。"

# クリス
# カズマ、何食べる？\nあたしはハンバーグにしようかな。
313 = "カズマ、何食べる？\\nあたしはハンバーグにしようかな。"

# カズマ
# 俺も肉がいいな。
321 = "俺も肉がいいな。"

# クリス
# それじゃ、スモークリザードのハンバーグ定食と\nクリムゾンネロイドかな。
294 = "それじゃ、スモークリザードのハンバーグ定食と\\nクリムゾンネロイドかな。"

# カズマ
# クリムゾンビアにしないのか？
318 = "クリムゾンビアにしないのか？"

# クリス
# 少し悩んだけどまだ昼間だしさ。\nカズマも同じ物でいいでしょ？\n注文しちゃうね。
327 = "少し悩んだけどまだ昼間だしさ。\\nカズマも同じ物でいいでしょ？\\n注文しちゃうね。"

# カズマ（Ｍ）
# display as カズマ
# （それにしてもお仕置きって言われてるわりに\n　何もしてないな、俺）
366 = "（それにしてもお仕置きって言われてるわりに\\n　何もしてないな、俺）"

# カズマ（Ｍ）
# display as カズマ
# （てっきり大量の荷物を運ばされるかと思いきや\n　やったことと言えばクリスに連れられて\n　いくつか店を見て飯食ってるくらいだし）
369 = "（てっきり大量の荷物を運ばされるかと思いきや\\n　やったことと言えばクリスに連れられて\\n　いくつか店を見て飯食ってるくらいだし）"

# カズマ（Ｍ）
# display as カズマ
# （……あれ？\n　もしかしてこれ、デートというものなのでは）
360 = "（……あれ？\\n　もしかしてこれ、デートというものなのでは）"

# カズマ
# なあ、クリス。\n今気付いたんだけど、俺達のしてるこれって\nデートってやつじゃないか？
299 = "なあ、クリス。\\n今気付いたんだけど、俺達のしてるこれって\\nデートってやつじゃないか？"

# クリス
# えっ？
274 = "えっ？"

# カズマ
# ウィンドウショッピングに食事って\nデートの定番コースだって聞くぞ。
311 = "ウィンドウショッピングに食事って\\nデートの定番コースだって聞くぞ。"

# クリス
# ふーん。\nじゃあさ、食事代とか全部キミが持ってくれる？\nデートなんでしょ？
304 = "ふーん。\\nじゃあさ、食事代とか全部キミが持ってくれる？\\nデートなんでしょ？"

# カズマ
# ごめんなさい。\n調子に乗りました。\nあまり手持ちがないんです、許してください。
282 = "ごめんなさい。\\n調子に乗りました。\\nあまり手持ちがないんです、許してください。"

# クリス
# そうあっさり嫌だって言われると\nちょっと傷つくんだけど……。\nあたしってそんなに魅力ないかなぁ。
288 = "そうあっさり嫌だって言われると\\nちょっと傷つくんだけど……。\\nあたしってそんなに魅力ないかなぁ。"

# カズマ
# いやほんとに金ないんだよ。\nクリスだって知ってるだろ。
269 = "いやほんとに金ないんだよ。\\nクリスだって知ってるだろ。"

# クリス
# あっ、そっか、そうだったね。
259 = "あっ、そっか、そうだったね。"

# カズマ
# はぁ、金が欲しい。\n心底金が欲しい。
303 = "はぁ、金が欲しい。\\n心底金が欲しい。"

# クリス
# あは、あはは、ここはあたしが持ってあげるからさ、\n元気だしなって。
262 = "あは、あはは、ここはあたしが持ってあげるからさ、\\n元気だしなって。"

# カズマ
# す、すみません。\nごちそうになります。
287 = "す、すみません。\\nごちそうになります。"

# カズマ
# お、おう、まかせておけ！
275 = "お、おう、まかせておけ！"

# カズマ（Ｍ）
# display as カズマ
# （今は金を貯めてる最中だけど、\n　ここの食事代くらいなら）
374 = "（今は金を貯めてる最中だけど、\\n　ここの食事代くらいなら）"

# クリス
# じゃあ、後で新しい洋服も見に行っちゃおうかな。\nそろそろマントを新調したいと思ってたんだよね。
286 = "じゃあ、後で新しい洋服も見に行っちゃおうかな。\\nそろそろマントを新調したいと思ってたんだよね。"

# カズマ（Ｍ）
# display as カズマ
# （は？）
370 = "（は？）"

# クリス
# そうだ、薬草や傷薬も補充しておかなきゃ。
291 = "そうだ、薬草や傷薬も補充しておかなきゃ。"

# カズマ（Ｍ）
# display as カズマ
# （ちょ、待て待て）
367 = "（ちょ、待て待て）"

# クリス
# あとダガーも研ぎに出さないと。\nマジックダガーだから\n研ぐだけでもいい値段するんだよね。
261 = "あとダガーも研ぎに出さないと。\\nマジックダガーだから\\n研ぐだけでもいい値段するんだよね。"

# カズマ
# あああ、あの！　ク、クリスさん！
258 = "あああ、あの！　ク、クリスさん！"

# クリス
# あはは、わかってるよ。\nキミは今、お金を貯めてる途中だもんね。
263 = "あはは、わかってるよ。\\nキミは今、お金を貯めてる途中だもんね。"

# カズマ
# そういうことなので、\nここをおごるだけでお願いします。
289 = "そういうことなので、\\nここをおごるだけでお願いします。"

# クリス
# キミの事情はわかってるからさ。\nそんな顔をしないで。
315 = "キミの事情はわかってるからさ。\\nそんな顔をしないで。"

# カズマ
# いやでも、やっぱ男として情けないっていうか。\n可愛い女の子の前では格好つけたいし。
268 = "いやでも、やっぱ男として情けないっていうか。\\n可愛い女の子の前では格好つけたいし。"

# クリス
# か、可愛いって……。\nやだな、そんなお世辞言わなくてもいいのに。
277 = "か、可愛いって……。\\nやだな、そんなお世辞言わなくてもいいのに。"

# カズマ（Ｍ）
# display as カズマ
# （おっ、照れてる。\n　なんか新鮮だな、こういうの）
363 = "（おっ、照れてる。\\n　なんか新鮮だな、こういうの）"

# クリス
# あっ、ほら。\nハンバーグが来たよ！\n冷めないうちに食べよ、ねっ！
260 = "あっ、ほら。\\nハンバーグが来たよ！\\n冷めないうちに食べよ、ねっ！"

# カズマ
# 割り勘でお願いします……。
324 = "割り勘でお願いします……。"

# クリス
# うーん？　本当に割り勘でいいのかな？
272 = "うーん？　本当に割り勘でいいのかな？"

# カズマ（Ｍ）
# display as カズマ
# （あれ？　もしかして今、\n　男の器のでかさをタメされてる？）
362 = "（あれ？　もしかして今、\\n　男の器のでかさをタメされてる？）"

# カズマ
# じゃ、じゃあ！\nおご、おご、おごっ！！　おごり……でぇっっ！！
284 = "じゃ、じゃあ！\\nおご、おご、おごっ！！　おごり……でぇっっ！！"

# クリス
# あはは、無理しなくていいから。\nキミの事情は知ってるしさ。
264 = "あはは、無理しなくていいから。\\nキミの事情は知ってるしさ。"

# クリス
# まっ、お仕置きとしては甘い判断になっちゃうけど、\nここはあたしがおごってあげる。
306 = "まっ、お仕置きとしては甘い判断になっちゃうけど、\\nここはあたしがおごってあげる。"

# カズマ
# うぅ、クリスさぁん。
270 = "うぅ、クリスさぁん。"

# クリス
# も、もう、こんなことで泣かないの。\n男の子でしょ。
307 = "も、もう、こんなことで泣かないの。\\n男の子でしょ。"

# カズマ
# だってだって、その優しさが嬉しすぎて。
295 = "だってだって、その優しさが嬉しすぎて。"

# クリス
# あ、ほらハンバーグが来たよ。\nあったかいうちに食べようよ、ねっ。
257 = "あ、ほらハンバーグが来たよ。\\nあったかいうちに食べようよ、ねっ。"

# カズマ（Ｍ）
# display as カズマ
# （くっそ、早くこの指輪の呪いを解いて\n　クリスに格好いい所を見せるぞ）
365 = "（くっそ、早くこの指輪の呪いを解いて\\n　クリスに格好いい所を見せるぞ）"

[selections]
281 = "ごめんなさい"
# 275 = "お、おう、まかせておけ！"
323 = "割り勘でお願いします……"
