# rew_d10.txt.scn

[info]
199 = "rew_d10"

[characters]
272 = "カズマ（Ｍ）"
274 = "クリス"
271 = "カズマ"

[character_subs]
# 271 = "カズマ"

[script]
# lines: 76

# カズマ（Ｍ）
# display as カズマ
# （部屋で待ってろって言われたけど、\n　クリスはいつになったら来るんだ……）
320 = "（部屋で待ってろって言われたけど、\\n　クリスはいつになったら来るんだ……）"

# カズマ（Ｍ）
# display as カズマ
# （ふぁぁぁ、さすがに眠い。\n　もうベッドに入っちゃおうかな）
315 = "（ふぁぁぁ、さすがに眠い。\\n　もうベッドに入っちゃおうかな）"

# クリス
# カーズマ、お待たせ。
273 = "カーズマ、お待たせ。"

# カズマ
# うわぁっ！？
236 = "うわぁっ！？"

# クリス
# ど、どうしたの？\nもしかして驚かせちゃったかな。
261 = "ど、どうしたの？\\nもしかして驚かせちゃったかな。"

# カズマ
# 窓から入って来られたら驚くのが普通だろ！
307 = "窓から入って来られたら驚くのが普通だろ！"

# クリス
# あはは、ごめんごめん。\nこの時間だとみんな寝てるかなって思ってさ。
230 = "あはは、ごめんごめん。\\nこの時間だとみんな寝てるかなって思ってさ。"

# カズマ
# それで、こんな時間に何をしようっていうんだ？
251 = "それで、こんな時間に何をしようっていうんだ？"

# クリス
# まず、これから一緒に屋根まで\n上って貰います。
268 = "まず、これから一緒に屋根まで\\n上って貰います。"

# カズマ
# そこから突き落とす！？
249 = "そこから突き落とす！？"

# クリス
# うん、そう。
237 = "うん、そう。"

# カズマ
# マジか！？
279 = "マジか！？"

# クリス
# 嘘に決まってるでしょ。
287 = "嘘に決まってるでしょ。"

# カズマ
# じゃあ何しに屋根の上なんか行くんだよ。\nもう夜も遅いし何も見えないぞ。
244 = "じゃあ何しに屋根の上なんか行くんだよ。\\nもう夜も遅いし何も見えないぞ。"

# クリス
# だからいいんだよ。\n灯りが多い場所じゃ見えにくいから。
255 = "だからいいんだよ。\\n灯りが多い場所じゃ見えにくいから。"

# カズマ
# 何がだ？
282 = "何がだ？"

# クリス
# 星だよ、星。\nたまには空を見るのも悪くないかなって。
289 = "星だよ、星。\\nたまには空を見るのも悪くないかなって。"

# クリス
# 知ってる？\n今日はね、１年に数回しかない\n星がたくさん流れる日なんだ。
305 = "知ってる？\\n今日はね、１年に数回しかない\\n星がたくさん流れる日なんだ。"

# クリス
# ここって街から少し離れていて、\n星を見るにはとてもいい場所なんだよね。
242 = "ここって街から少し離れていて、\\n星を見るにはとてもいい場所なんだよね。"

# クリス
# というわけで、先に上ってるから。
260 = "というわけで、先に上ってるから。"

# カズマ（Ｍ）
# display as カズマ
# （お、おいクリス……行っちまったか）
311 = "（お、おいクリス……行っちまったか）"

# カズマ（Ｍ）
# display as カズマ
# （屋根の上で星を見る、か）
318 = "（屋根の上で星を見る、か）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、それくらいなら付き合ってもいいか。\n　この程度でお仕置きになるならお安いもんだぜ）
316 = "（まあ、それくらいなら付き合ってもいいか。\\n　この程度でお仕置きになるならお安いもんだぜ）"

# カズマ
# ……そんな風に思っていた時期もありました。
225 = "……そんな風に思っていた時期もありました。"

# カズマ（Ｍ）
# display as カズマ
# （高い！　高すぎる！\n　いや、うちの規模から考えたら屋根が高いのは\n　当たり前だったけど忘れてたよちくしょー！！）
321 = "（高い！　高すぎる！\\n　いや、うちの規模から考えたら屋根が高いのは\\n　当たり前だったけど忘れてたよちくしょー！！）"

# カズマ（Ｍ）
# display as カズマ
# （しかも暗いから足元がよく見えない……\n　ここから落ちたらシャレにならんぞ。\n　またエリス様のお世話になっちまう）
313 = "（しかも暗いから足元がよく見えない……\\n　ここから落ちたらシャレにならんぞ。\\n　またエリス様のお世話になっちまう）"

# クリス
# おっ、ようやく来た。
240 = "おっ、ようやく来た。"

# カズマ
# ひ、ひぃ～～！！
265 = "ひ、ひぃ～～！！"

# クリス
# あはは、ちょっとくっつきすぎじゃないかな？
231 = "あはは、ちょっとくっつきすぎじゃないかな？"

# カズマ
# わ、悪い。\n離れたいんだけど、足がすくんで。
270 = "わ、悪い。\\n離れたいんだけど、足がすくんで。"

# クリス
# 暗いし、足場が見辛いからしょうがないよ。\nでも、慣れたら離れてね？
290 = "暗いし、足場が見辛いからしょうがないよ。\\nでも、慣れたら離れてね？"

# カズマ
# 申し訳ない……。
292 = "申し訳ない……。"

# クリス
# おや、なんだか素直だね。\nキミにしては珍しい。
241 = "おや、なんだか素直だね。\\nキミにしては珍しい。"

# カズマ
# そう言うなよ。\n本当に悪いなって思ってるんだからさ。
248 = "そう言うなよ。\\n本当に悪いなって思ってるんだからさ。"

# カズマ
# ただ、その、ここはちょっと、\n慣れてないっつーか怖いって言うか……。
254 = "ただ、その、ここはちょっと、\\n慣れてないっつーか怖いって言うか……。"

# クリス
# ああ、よく考えたらこんな風に高いところなんて\n普段上らないもんね。
228 = "ああ、よく考えたらこんな風に高いところなんて\\n普段上らないもんね。"

# カズマ
# クリスは平気なのか？
275 = "クリスは平気なのか？"

# クリス
# 高所を怖がってたら盗賊はできないでしょ。
310 = "高所を怖がってたら盗賊はできないでしょ。"

# カズマ（Ｍ）
# display as カズマ
# （た、確かに……）
314 = "（た、確かに……）"

# クリス
# ほらほら、私の顔は見てなくてもいいから\n空を見なよ。
267 = "ほらほら、私の顔は見てなくてもいいから\\n空を見なよ。"

# カズマ
# おおっ、これはすごいな！
239 = "おおっ、これはすごいな！"

# クリス
# でしょー？
258 = "でしょー？"

# カズマ
# しかし星空とは、\n意外と女の子っぽい趣味があったんだな。
243 = "しかし星空とは、\\n意外と女の子っぽい趣味があったんだな。"

# クリス
# ちょっとキミ、あたしのことなんだと思ってるの。
257 = "ちょっとキミ、あたしのことなんだと思ってるの。"

# カズマ
# 知り合ってそこそこ経つけど\n結構クリスのこと知らないんだなと思ってさ。
306 = "知り合ってそこそこ経つけど\\n結構クリスのこと知らないんだなと思ってさ。"

# クリス
# どんなに長い付き合いだったとしても、\nお互いを完全に理解することはできないよ。
262 = "どんなに長い付き合いだったとしても、\\nお互いを完全に理解することはできないよ。"

# クリス
# でも、相手のことを知ろうとすることはできる。\nだからね、あたしたちもこれからゆっくり\nお互いのこと、知っていけばいいと思うんだ。
259 = "でも、相手のことを知ろうとすることはできる。\\nだからね、あたしたちもこれからゆっくり\\nお互いのこと、知っていけばいいと思うんだ。"

# カズマ
# それって、プロポーズか？
250 = "それって、プロポーズか？"

# クリス
# あははは、違う違う。
233 = "あははは、違う違う。"

# カズマ
# なんだ、いきなり情熱的な告白を\nされたのかと思ったのに残念だな。
263 = "なんだ、いきなり情熱的な告白を\\nされたのかと思ったのに残念だな。"

# カズマ
# クリスは怖くないのか？\nこんな高いところに上って。
277 = "クリスは怖くないのか？\\nこんな高いところに上って。"

# クリス
# それはまた、斬新な質問だね。\nでも、これくらいならどうってことないかなぁ。\nそんな高いってほどでもないし。
252 = "それはまた、斬新な質問だね。\\nでも、これくらいならどうってことないかなぁ。\\nそんな高いってほどでもないし。"

# カズマ
# いやいやいや、どう考えたって高いだろここ！
234 = "いやいやいや、どう考えたって高いだろここ！"

# カズマ
# 俺を見てみろ。\n足がガクガクしてるんだぞ！
283 = "俺を見てみろ。\\n足がガクガクしてるんだぞ！"

# クリス
# だってあたしは盗賊だもの。\nダンジョン内のトラップだけじゃなくて、\nこういう高いところで仕事をすることもあるし。
256 = "だってあたしは盗賊だもの。\\nダンジョン内のトラップだけじゃなくて、\\nこういう高いところで仕事をすることもあるし。"

# カズマ
# 盗賊ってそんなこともするのか！？
293 = "盗賊ってそんなこともするのか！？"

# クリス
# 身軽なのが売りだからさ。\n頼まれたらなんでもするよ。
309 = "身軽なのが売りだからさ。\\n頼まれたらなんでもするよ。"

# クリス
# 他の人じゃ手出しできないような物でも\nあたしが調べたり解除するのが役割だからね。
281 = "他の人じゃ手出しできないような物でも\\nあたしが調べたり解除するのが役割だからね。"

# カズマ
# ……クリスってすごいんだな。
226 = "……クリスってすごいんだな。"

# クリス
# ふふっ、もっと褒めてもいいんだよ？
266 = "ふふっ、もっと褒めてもいいんだよ？"

# カズマ
# ずっとこうしていたいな……。
247 = "ずっとこうしていたいな……。"

# クリス
# それは困るかな。
253 = "それは困るかな。"

# カズマ
# 即答かよ！
284 = "即答かよ！"

# クリス
# もしかしてこの状況なら\nあたしを口説けると思ったの？
269 = "もしかしてこの状況なら\\nあたしを口説けると思ったの？"

# カズマ
# 否定はしない。
286 = "否定はしない。"

# クリス
# あはは、正直でよろしい。\nでも、そのへっぴり腰じゃ、\nどんなカッコ良い台詞も意味をなさないよね。
232 = "あはは、正直でよろしい。\\nでも、そのへっぴり腰じゃ、\\nどんなカッコ良い台詞も意味をなさないよね。"

# カズマ
# はぁ、わかってるよ。
264 = "はぁ、わかってるよ。"

# クリス
# あっ、カズマ見て！\n今年最大の天体ショーが始まるよ！
229 = "あっ、カズマ見て！\\n今年最大の天体ショーが始まるよ！"

# カズマ
# お、おお、これは！！
238 = "お、おお、これは！！"

# クリス
# すごい、すごいね！\nこんなにたくさんの星が流れるの\n初めて見たよ。
245 = "すごい、すごいね！\\nこんなにたくさんの星が流れるの\\n初めて見たよ。"

# カズマ
# あ、ああ、俺も。
227 = "あ、ああ、俺も。"

# カズマ（Ｍ）
# display as カズマ
# （確かに、この光景は壮観だな。\n　日本じゃここまですごい流星群は\n　なかなか見られないし）
319 = "（確かに、この光景は壮観だな。\\n　日本じゃここまですごい流星群は\\n　なかなか見られないし）"

# クリス
# うわぁ。
235 = "うわぁ。"

# カズマ（Ｍ）
# display as カズマ
# （こんな高い所は勘弁して欲しいけど――）
312 = "（こんな高い所は勘弁して欲しいけど――）"

# クリス
# 綺麗……。
308 = "綺麗……。"

# カズマ（Ｍ）
# display as カズマ
# （クリスのこんな表情が見られるなら、\n　また上ってもいいかもしれないな）
317 = "（クリスのこんな表情が見られるなら、\\n　また上ってもいいかもしれないな）"

[selections]
291 = "申し訳ない……"
276 = "クリスは怖くないのか？"
246 = "ずっとこうしていたいな……"
