# rew_c01.txt.scn

[info]
202 = "rew_c01"

[characters]
289 = "ダクネス"
285 = "カズマ"
287 = "カズマ（Ｍ）"

[character_subs]
# 285 = "カズマ"

[script]
# lines: 89

# ダクネス
# よ、要望通り着替えてきたぞ。
280 = "よ、要望通り着替えてきたぞ。"

# カズマ
# どうしたそんなにモジモジして。\nまだメイド服を着ることには抵抗があるのか？
263 = "どうしたそんなにモジモジして。\\nまだメイド服を着ることには抵抗があるのか？"

# ダクネス
# 違う！　これは、私がメイドだからに\n決まっているだろう！
318 = "違う！　これは、私がメイドだからに\\n決まっているだろう！"

# カズマ（Ｍ）
# display as カズマ
# （えーと、わけわからん……）
325 = "（えーと、わけわからん……）"

# ダクネス
# メイドは主人の従順なシモベ。
293 = "メイドは主人の従順なシモベ。"

# カズマ（Ｍ）
# display as カズマ
# （あ～、もうオチが読めた）
323 = "（あ～、もうオチが読めた）"

# ダクネス
# 主人が雨だと言えば、どんなに澄んだ空の日でも\n雨だと認め。
295 = "主人が雨だと言えば、どんなに澄んだ空の日でも\\n雨だと認め。"

# ダクネス
# 例え人の道から外れることを強要されても、\n主人の命令ならばと従順に膝をつく。
297 = "例え人の道から外れることを強要されても、\\n主人の命令ならばと従順に膝をつく。"

# ダクネス
# それが、女性のプライドを踏みにじられるような\n下衆な行為であってもだ！
251 = "それが、女性のプライドを踏みにじられるような\\n下衆な行為であってもだ！"

# カズマ（Ｍ）
# display as カズマ
# （あ～……）
322 = "（あ～……）"

# ダクネス
# 受け入れられないっ。決して受け入れられないが、\n主人の命令なら従うしかない。
299 = "受け入れられないっ。決して受け入れられないが、\\n主人の命令なら従うしかない。"

# ダクネス
# さ、さあ！\nどんな屈辱的な指示でも出すがいい！
242 = "さ、さあ！\\nどんな屈辱的な指示でも出すがいい！"

# ダクネス
# どこまで耐えられるかはわからないが、\nもしかしたらすぐに心が折れてしまうかも\nしれないが――
264 = "どこまで耐えられるかはわからないが、\\nもしかしたらすぐに心が折れてしまうかも\\nしれないが――"

# ダクネス
# カズマの、いやご主人様の命令ならば、\nどんな屈辱的な要望も受けとめてみせよう！
286 = "カズマの、いやご主人様の命令ならば、\\nどんな屈辱的な要望も受けとめてみせよう！"

# カズマ（Ｍ）
# display as カズマ
# （なんて、頬をゆるゆるにして言われてもな……）
330 = "（なんて、頬をゆるゆるにして言われてもな……）"

# ダクネス
# さあさあ、どんなことでもいい。\n命じてくれ、カズマぁ！
243 = "さあさあ、どんなことでもいい。\\n命じてくれ、カズマぁ！"

# カズマ
# そうだなー。\nじゃあ、一緒に風呂でも入るか。
250 = "そうだなー。\\nじゃあ、一緒に風呂でも入るか。"

# ダクネス
# へっ！？
270 = "へっ！？"

# カズマ
# ほら、行くぞ、ダクネス。
273 = "ほら、行くぞ、ダクネス。"

# ダクネス
# え？　え？
232 = "え？　え？"

# ダクネス
# …………。
225 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスの想像の斜め上を選択したのはいいが、\n　これは、ちょっと大胆すぎたかもな）
334 = "（ダクネスの想像の斜め上を選択したのはいいが、\\n　これは、ちょっと大胆すぎたかもな）"

# ダクネス
# まったく……。\n焦らすこともなく、いきなり全裸に剥くとは\nどういうことだ。
274 = "まったく……。\\n焦らすこともなく、いきなり全裸に剥くとは\\nどういうことだ。"

# ダクネス
# こういうのも嫌いではないが、\nなんと言うか、妙に心がむずむずする。
240 = "こういうのも嫌いではないが、\\nなんと言うか、妙に心がむずむずする。"

# カズマ（Ｍ）
# display as カズマ
# （さて、このままじゃ全然ご褒美にならないし、\n　もっと俺が楽しめる要求を突きつけないとな）
327 = "（さて、このままじゃ全然ご褒美にならないし、\\n　もっと俺が楽しめる要求を突きつけないとな）"

# カズマ
# なぁ、ダクネス。\nせっかくなんだし、もっとこっちに来いよ？
266 = "なぁ、ダクネス。\\nせっかくなんだし、もっとこっちに来いよ？"

# ダクネス
# な、何がせっかくなんだ！\n訳がわからないぞ！
265 = "な、何がせっかくなんだ！\\n訳がわからないぞ！"

# カズマ（Ｍ）
# display as カズマ
# （あ、あれ？　なんか想像してた反応と違うぞ？）
320 = "（あ、あれ？　なんか想像してた反応と違うぞ？）"

# ダクネス
# でも、まあ。\nカズマ……いやご主人様の命令には\n逆らえないからな。
261 = "でも、まあ。\\nカズマ……いやご主人様の命令には\\n逆らえないからな。"

# カズマ
# 俺が言っておいてなんなんだけど、\n無理にする必要は無いんだぞ？
298 = "俺が言っておいてなんなんだけど、\\n無理にする必要は無いんだぞ？"

# ダクネス
# い、いや、私はメイドだからな。\nこれくらいは受け入れて当然だ。
226 = "い、いや、私はメイドだからな。\\nこれくらいは受け入れて当然だ。"

# カズマ（Ｍ）
# display as カズマ
# （なんなんだ、この背中が痒くなるような\n　空気は！）
331 = "（なんなんだ、この背中が痒くなるような\\n　空気は！）"

# ダクネス
# そ、それで、何をするつもりなんだ？\n後ろ手でさりげなく、事故と見せかけて\n触れるつもりなのか？
247 = "そ、それで、何をするつもりなんだ？\\n後ろ手でさりげなく、事故と見せかけて\\n触れるつもりなのか？"

# カズマ
# そんな痴漢みたいな真似するか！
256 = "そんな痴漢みたいな真似するか！"

# ダクネス
# そ、そうか、意外に紳士なんだなカズマは。
246 = "そ、そうか、意外に紳士なんだなカズマは。"

# カズマ（Ｍ）
# display as カズマ
# （あ、あれえ？\n　おーい、いつものダクネスさんは、\n　どこへ行ってしまったんですかー？）
319 = "（あ、あれえ？\\n　おーい、いつものダクネスさんは、\\n　どこへ行ってしまったんですかー？）"

# ダクネス
# ところでカズマ……。
262 = "ところでカズマ……。"

# カズマ
# お、おう、なんだ？
234 = "お、おう、なんだ？"

# ダクネス
# いや、なんでもない……。
229 = "いや、なんでもない……。"

# カズマ
# おい、なんかおかしいぞ？\n熱でもあるんじゃないのか？
235 = "おい、なんかおかしいぞ？\\n熱でもあるんじゃないのか？"

# カズマ（Ｍ）
# display as カズマ
# （しばらくダクネスの様子を観察しよう）
328 = "（しばらくダクネスの様子を観察しよう）"

# ダクネス
# こら、チラチラと見るな！\nは、恥ずかしいだろう。
241 = "こら、チラチラと見るな！\\nは、恥ずかしいだろう。"

# カズマ（Ｍ）
# display as カズマ
# （あ、あれ？　期待してたりアクションと\n　違うんだけど……）
321 = "（あ、あれ？　期待してたりアクションと\\n　違うんだけど……）"

# ダクネス
# まったく、男という生き物は……。
275 = "まったく、男という生き物は……。"

# カズマ（Ｍ）
# display as カズマ
# （もしかして、そういう設定のプレイなのか？\n　それなら……）
333 = "（もしかして、そういう設定のプレイなのか？\\n　それなら……）"

# カズマ
# ジィィィ……。
288 = "ジィィィ……。"

# ダクネス
# ひぅ！？
269 = "ひぅ！？"

# カズマ
# ほほう、これはこれは、ご立派なモノを\nお持ちで。
271 = "ほほう、これはこれは、ご立派なモノを\\nお持ちで。"

# ダクネス
# や、やめてくれ！\nあ、あ、頭が沸騰してしまいそうだ……。
278 = "や、やめてくれ！\\nあ、あ、頭が沸騰してしまいそうだ……。"

# カズマ
# お、おい、さっきからなんなんだよ！\nその初々しいリアクションは！
233 = "お、おい、さっきからなんなんだよ！\\nその初々しいリアクションは！"

# カズマ
# いつものダクネスなら、涎を垂らして\n喜ぶ状況だろ！
227 = "いつものダクネスなら、涎を垂らして\\n喜ぶ状況だろ！"

# ダクネス
# よ、涎！？　それは、ちょっと酷いぞ！
279 = "よ、涎！？　それは、ちょっと酷いぞ！"

# カズマ
# ほら、今もそうだ！\n普段なら、責められたあっはーんって\n悶えるのがお約束じゃないか！
272 = "ほら、今もそうだ！\\n普段なら、責められたあっはーんって\\n悶えるのがお約束じゃないか！"

# ダクネス
# それはそうなのかもしれないが。
254 = "それはそうなのかもしれないが。"

# カズマ（Ｍ）
# display as カズマ
# （うーん、なんかおかしいな……）
324 = "（うーん、なんかおかしいな……）"

# カズマ
# もしかして熱でもあるのか？
276 = "もしかして熱でもあるのか？"

# カズマ（Ｍ）
# display as カズマ
# （メイドらしいことするように命令しよう）
335 = "（メイドらしいことするように命令しよう）"

# カズマ
# なーダクネス。\nちょっとメイドさんらしく、\n背中を流してしてくんないか？
268 = "なーダクネス。\\nちょっとメイドさんらしく、\\n背中を流してしてくんないか？"

# ダクネス
# そ、それはメイドの仕事ではないと思うが。
248 = "そ、それはメイドの仕事ではないと思うが。"

# カズマ
# さっきダクネスが自分で言ったんだろ。\n主人の命令なら従うしかないって。
244 = "さっきダクネスが自分で言ったんだろ。\\n主人の命令なら従うしかないって。"

# ダクネス
# それはそうだが。\nこれはメイドの仕事とは少し違う。
253 = "それはそうだが。\\nこれはメイドの仕事とは少し違う。"

# カズマ
# えー、そうか？
231 = "えー、そうか？"

# ダクネス
# そうだ。
249 = "そうだ。"

# カズマ（Ｍ）
# display as カズマ
# （うーん、なんかおかしいな……）
# 324 = "（うーん、なんかおかしいな……）"

# カズマ
# なあ、ダクネス。\nもしかして熱でもあるんじゃないのか？
267 = "なあ、ダクネス。\\nもしかして熱でもあるんじゃないのか？"

# ダクネス
# 平気だ。
302 = "平気だ。"

# カズマ
# でも、さっきからなんかおかしいぞ？
260 = "でも、さっきからなんかおかしいぞ？"

# ダクネス
# そんなことはない。
255 = "そんなことはない。"

# カズマ
# いや、そんなことあるって。\nこんな淑やかなダクネスを見るのは\n初めてだ。
228 = "いや、そんなことあるって。\\nこんな淑やかなダクネスを見るのは\\n初めてだ。"

# ダクネス
# さらっと、失礼なことを言ってくれたな。
245 = "さらっと、失礼なことを言ってくれたな。"

# カズマ
# 今度はむくれるのかよ。\nいつもなら、両手を挙げて喜ぶのに。
296 = "今度はむくれるのかよ。\\nいつもなら、両手を挙げて喜ぶのに。"

# ダクネス
# うぅぅ……。
230 = "うぅぅ……。"

# カズマ
# ダクネス？\nいったい、どうしたんだ？\n話してくれないとわからないぞ。
291 = "ダクネス？\\nいったい、どうしたんだ？\\n話してくれないとわからないぞ。"

# ダクネス
# メイドとは常に主人の側に控えるものだ。
292 = "メイドとは常に主人の側に控えるものだ。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、理屈はわかる）
332 = "（まあ、理屈はわかる）"

# ダクネス
# だが、今の状況は控えるのとは違う。
258 = "だが、今の状況は控えるのとは違う。"

# ダクネス
# お互いに肌を隠す物を脱ぎ去り、湯船を共にする。\nそれは、主人とメイドの一線を越えた関係だ。
238 = "お互いに肌を隠す物を脱ぎ去り、湯船を共にする。\\nそれは、主人とメイドの一線を越えた関係だ。"

# カズマ
# つまり、どういうことだ？
259 = "つまり、どういうことだ？"

# ダクネス
# だ、だから、もっと親密な関係と言うかだな……。
257 = "だ、だから、もっと親密な関係と言うかだな……。"

# カズマ
# おーい、ダクネス？\n何言ってるのか聞こえないぞ。
237 = "おーい、ダクネス？\\n何言ってるのか聞こえないぞ。"

# ダクネス
# それは、こ、こ、恋人であり、\nあるいは、つ、つ、妻ぁぁ～～～～……。
252 = "それは、こ、こ、恋人であり、\\nあるいは、つ、つ、妻ぁぁ～～～～……。"

# カズマ
# わぁぁっ！？　だ、ダクネス！？\nダクネスさん！？
281 = "わぁぁっ！？　だ、ダクネス！？\\nダクネスさん！？"

# ダクネス
# カ……ズマ……。
284 = "カ……ズマ……。"

# カズマ
# こ、こら、なんで沈んでるんだよ！\nもしかしてのぼせたのか！？
239 = "こ、こら、なんで沈んでるんだよ！\\nもしかしてのぼせたのか！？"

# ダクネス
# んぎゅぅ～～……。
282 = "んぎゅぅ～～……。"

# カズマ
# おいっ、しっかりしろ！！\n溺死するぞ！
236 = "おいっ、しっかりしろ！！\\n溺死するぞ！"

# カズマ（Ｍ）
# display as カズマ
# （このままじゃまずい！\n　誰か呼ばないと！）
326 = "（このままじゃまずい！\\n　誰か呼ばないと！）"

# カズマ（Ｍ）
# display as カズマ
# （でも、こんなところをアクアとめぐみんに\n　見られたら……\n　いや、そんな事言ってる場合じゃねぇ！）
329 = "（でも、こんなところをアクアとめぐみんに\\n　見られたら……\\n　いや、そんな事言ってる場合じゃねぇ！）"

# カズマ
# アクアーー！！　めぐみん！！\n助けてくれーー！！
283 = "アクアーー！！　めぐみん！！\\n助けてくれーー！！"

[selections]
277 = "もっと側に来るように誘ってみよう"
290 = "ダクネスの様子を観察しよう"
294 = "メイドらしいことするように命令しよう"
