# rew_f08.txt.scn

[info]
165 = "rew_f08"

[characters]
234 = "カズマ"
231 = "ウィズ"
237 = "カズマ（Ｍ）"

[character_subs]
# 234 = "カズマ"

[script]
# lines: 62

# カズマ
# 夜の見回りかぁ。\nこれ、別に俺が付き合う必要ないんじゃないのか？
240 = "夜の見回りかぁ。\\nこれ、別に俺が付き合う必要ないんじゃないのか？"

# ウィズ
# そこはそれ、お仕置きの一環ということで。
214 = "そこはそれ、お仕置きの一環ということで。"

# カズマ
# まあそうなんだけど。\nウィズって墓の浄化もしてたよな。\nこれもそれと同じ事なわけ？
226 = "まあそうなんだけど。\\nウィズって墓の浄化もしてたよな。\\nこれもそれと同じ事なわけ？"

# ウィズ
# はい。\n彷徨う霊を導くのも私の務めですから。
223 = "はい。\\n彷徨う霊を導くのも私の務めですから。"

# カズマ
# さすがリッチーだな。\nしかし、そんな見回りするほどの霊ってのは、\nこの世にいるものなの？
211 = "さすがリッチーだな。\\nしかし、そんな見回りするほどの霊ってのは、\\nこの世にいるものなの？"

# ウィズ
# はい、それはもうたくさん。
222 = "はい、それはもうたくさん。"

# カズマ
# たくさんいるのかよ！
220 = "たくさんいるのかよ！"

# ウィズ
# この世が生命で満ちあふれている以上、霊だって同じ\nくらいいて不思議は無いと思いますが？
210 = "この世が生命で満ちあふれている以上、霊だって同じ\\nくらいいて不思議は無いと思いますが？"

# カズマ
# そりゃ理屈で言えばそうなるけど……見えない存在\nだけにタチが悪いな。
217 = "そりゃ理屈で言えばそうなるけど……見えない存在\\nだけにタチが悪いな。"

# ウィズ
# そのほとんどは、\nただ存在するだけの無害な霊ですよ。
216 = "そのほとんどは、\\nただ存在するだけの無害な霊ですよ。"

# ウィズ
# たまに、悪戯をしたり人に取り憑いたりするのも\nいますが……。
221 = "たまに、悪戯をしたり人に取り憑いたりするのも\\nいますが……。"

# カズマ
# 定番だな……そういうのに取り憑かれたらどうなるん\nだ？　発狂したり化け物になっちゃったりするのか？
241 = "定番だな……そういうのに取り憑かれたらどうなるん\\nだ？　発狂したり化け物になっちゃったりするのか？"

# ウィズ
# そこまで強力な悪霊はさすがにそういませんけど、\n取り憑かれた場合は、その霊の無念や心残り、\n現世の執着を晴らす必要がありますね。
215 = "そこまで強力な悪霊はさすがにそういませんけど、\\n取り憑かれた場合は、その霊の無念や心残り、\\n現世の執着を晴らす必要がありますね。"

# カズマ
# お祓いってヤツか。\nま、ウィズが一緒にいるなら、取り憑かれることも\n無いだろうけどさ……ん？
208 = "お祓いってヤツか。\\nま、ウィズが一緒にいるなら、取り憑かれることも\\n無いだろうけどさ……ん？"

# カズマ（Ｍ）
# display as カズマ
# （な、なんだ？　身体がいきなり、動かなくなったん\n　だが……）
271 = "（な、なんだ？　身体がいきなり、動かなくなったん\\n　だが……）"

# ウィズ
# 彼等は、ふっと気の緩みが生じた時に、すっと取り\n憑こうとしますから、カズマさんも危ないところに\n行ったときなどは気を付けて下さいね。
243 = "彼等は、ふっと気の緩みが生じた時に、すっと取り\\n憑こうとしますから、カズマさんも危ないところに\\n行ったときなどは気を付けて下さいね。"

# カズマ（Ｍ）
# display as カズマ
# （頭は……はっきりしてる、ウィズの言葉も聞こえ\n　てるし、地面に立ってる感触だってわかる……）
278 = "（頭は……はっきりしてる、ウィズの言葉も聞こえ\\n　てるし、地面に立ってる感触だってわかる……）"

# カズマ（Ｍ）
# display as カズマ
# （けど、身体の自由だけが効かない！）
266 = "（けど、身体の自由だけが効かない！）"

# カズマ（Ｍ）
# display as カズマ
# （金縛りってやつか？　く、口だけでもせめて動けば\n　ウィズに……）
276 = "（金縛りってやつか？　く、口だけでもせめて動けば\\n　ウィズに……）"

# ウィズ
# カズマさん？　どうかしましたか？
236 = "カズマさん？　どうかしましたか？"

# カズマ
# …………か、身体が、急に動、かなく……なって。\nしゃ、喋るのも精、一杯、で。
195 = "…………か、身体が、急に動、かなく……なって。\\nしゃ、喋るのも精、一杯、で。"

# ウィズ
# ええええっ？　今言ったばっかりなのに、\n取り憑かれちゃったんですかっ？
204 = "ええええっ？　今言ったばっかりなのに、\\n取り憑かれちゃったんですかっ？"

# カズマ
# め、面目、ない……お、あっ……な、何か、変な\n感じが、頭の、中に……。
227 = "め、面目、ない……お、あっ……な、何か、変な\\n感じが、頭の、中に……。"

# カズマ（Ｍ）
# display as カズマ
# （頭の中に、俺じゃない誰かの思考……いや、記憶\n　みたいなものが流れ込んでくる）
277 = "（頭の中に、俺じゃない誰かの思考……いや、記憶\\n　みたいなものが流れ込んでくる）"

# カズマ（Ｍ）
# display as カズマ
# （これは……この、霊の……心残りって、ヤツか？）
269 = "（これは……この、霊の……心残りって、ヤツか？）"

# カズマ（Ｍ）
# display as カズマ
# （走馬燈のように、\n　何かの映像が一気に頭の中を駆け抜けていく）
275 = "（走馬燈のように、\\n　何かの映像が一気に頭の中を駆け抜けていく）"

# ウィズ
# カズマさん、カズマさんっ、大丈夫ですかっ！？
235 = "カズマさん、カズマさんっ、大丈夫ですかっ！？"

# カズマ
# う……な、なんとか……それよりも今、\n俺の頭、の中に、誰かの記憶みたいなのが。
201 = "う……な、なんとか……それよりも今、\\n俺の頭、の中に、誰かの記憶みたいなのが。"

# ウィズ
# それが多分、取り憑いた霊の心残りですっ。\nそれを晴らすことが出来れば、きっとっ。
218 = "それが多分、取り憑いた霊の心残りですっ。\\nそれを晴らすことが出来れば、きっとっ。"

# カズマ
# あ、ああああ……そうなんだけど……。\nう、あっ？　こ、今度は、身体が勝手に……？
198 = "あ、ああああ……そうなんだけど……。\\nう、あっ？　こ、今度は、身体が勝手に……？"

# カズマ（Ｍ）
# display as カズマ
# （俺の意志と関係無く腕や足が勝手に動いていく）
273 = "（俺の意志と関係無く腕や足が勝手に動いていく）"

# ウィズ
# えっ、カズマさん……？
206 = "えっ、カズマさん……？"

# カズマ
# 俺に、取り憑いてるの、どうやら……。\nそ、その、好きな人に告白する前に、死んじゃった\n男らしくて……。
238 = "俺に、取り憑いてるの、どうやら……。\\nそ、その、好きな人に告白する前に、死んじゃった\\n男らしくて……。"

# カズマ
# それだけが未練らしくて、気持ちを、伝えたいって、\nすごい強力な力みたいなのが……俺を動かしてて。
219 = "それだけが未練らしくて、気持ちを、伝えたいって、\\nすごい強力な力みたいなのが……俺を動かしてて。"

# ウィズ
# 確かに、そうですね。カズマさんから、カズマ\nさんとは違う霊の波動みたいなものを感じます。
261 = "確かに、そうですね。カズマさんから、カズマ\\nさんとは違う霊の波動みたいなものを感じます。"

# ウィズ
# わかりました、その未練を晴らすのに協力します。\n私を、その恋人と思って……。
229 = "わかりました、その未練を晴らすのに協力します。\\n私を、その恋人と思って……。"

# カズマ
# ウィ、ウィズ……。
230 = "ウィ、ウィズ……。"

# カズマ（Ｍ）
# display as カズマ
# （意識が少し飛びそうになり……身体が勝手に、\n　胸元で手を握り合わせたウィズを\n　抱き寄せようとした）
274 = "（意識が少し飛びそうになり……身体が勝手に、\\n　胸元で手を握り合わせたウィズを\\n　抱き寄せようとした）"

# ウィズ
# …………。
194 = "…………。"

# カズマ
# ああ……アリーシア……愛しい、アリーシア。\nこうして、お前のことを抱きしめるのが、夢だった。
200 = "ああ……アリーシア……愛しい、アリーシア。\\nこうして、お前のことを抱きしめるのが、夢だった。"

# カズマ
# お前のことが、好きだ……小さい時から、ずっと好き\nだった。返事を、聞かせてくれないか……？
207 = "お前のことが、好きだ……小さい時から、ずっと好き\\nだった。返事を、聞かせてくれないか……？"

# ウィズ
# はい。喜んで……。
225 = "はい。喜んで……。"

# カズマ
# 本当か！？　ああ、何て幸せなんだ……ああ……\nありがとう……見知らぬ人よ……。
244 = "本当か！？　ああ、何て幸せなんだ……ああ……\\nありがとう……見知らぬ人よ……。"

# ウィズ
# …………。
# 194 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （……っ！？　あ、身体の自由が戻った！？）
263 = "（……っ！？　あ、身体の自由が戻った！？）"

# カズマ（Ｍ）
# display as カズマ
# （お、おお……俺の腕の中に、ウィズの……豊満な\n　身体が……！）
265 = "（お、おお……俺の腕の中に、ウィズの……豊満な\\n　身体が……！）"

# カズマ（Ｍ）
# display as カズマ
# （……ごくっ。せ、せっかくのこんなチャンスなんだ\n　から……）
262 = "（……ごくっ。せ、せっかくのこんなチャンスなんだ\\n　から……）"

# カズマ（Ｍ）
# display as カズマ
# （こ、これはもっと強く抱きしめてウィズの身体を\n　堪能するしかない……！？）
267 = "（こ、これはもっと強く抱きしめてウィズの身体を\\n　堪能するしかない……！？）"

# カズマ（Ｍ）
# display as カズマ
# （このチャンスを活かさずして、何が男か……！）
268 = "（このチャンスを活かさずして、何が男か……！）"

# カズマ（Ｍ）
# display as カズマ
# （もうちょっとこのまま、ウィズの柔らかさに浸って\n　いたい……）
272 = "（もうちょっとこのまま、ウィズの柔らかさに浸って\\n　いたい……）"

# カズマ（Ｍ）
# display as カズマ
# （さっきの霊も、これを求めてたんだろうな……）
270 = "（さっきの霊も、これを求めてたんだろうな……）"

# カズマ（Ｍ）
# display as カズマ
# （ああ……ウィズの髪のいい香りが鼻をくすぐってく\n　……もう少しだけこの匂いを……）
264 = "（ああ……ウィズの髪のいい香りが鼻をくすぐってく\\n　……もう少しだけこの匂いを……）"

# カズマ
# くんくん……くんかくんか……。
209 = "くんくん……くんかくんか……。"

# ウィズ
# あ、あの～……そろそろ離れて頂けませんでしょう\nか……？
199 = "あ、あの～……そろそろ離れて頂けませんでしょう\\nか……？"

# カズマ
# ……はっ！？　え、も、もしかしてウィズ、\n俺の身体が動くの、わかってた！？
197 = "……はっ！？　え、も、もしかしてウィズ、\\n俺の身体が動くの、わかってた！？"

# ウィズ
# はい。さっき霊が満足して私にお礼を言って、\n去っていきましたから……。
224 = "はい。さっき霊が満足して私にお礼を言って、\\n去っていきましたから……。"

# カズマ
# うわぁぁぁ……ご、ごめんなさい…………あ、あれ？
202 = "うわぁぁぁ……ご、ごめんなさい…………あ、あれ？"

# ウィズ
# ……どうしました？
196 = "……どうしました？"

# カズマ
# ええと……ま、また……身体が動かなく……。
205 = "ええと……ま、また……身体が動かなく……。"

# ウィズ
# え……えええっ！？\nあっ、本当、またカズマさん、\n霊に身体を乗っ取られて……！？
203 = "え……えええっ！？\\nあっ、本当、またカズマさん、\\n霊に身体を乗っ取られて……！？"

# カズマ
# す、すみませ～～～～ん！！
213 = "す、すみませ～～～～ん！！"

# ウィズ
# も、もう～……。
228 = "も、もう～……。"

[selections]
212 = "さらに強く抱きしめよう！"
232 = "ウィズの柔らかさを堪能しよう！"
233 = "ウィズの髪の香りを堪能しよう！"
