# rew_a04.txt.scn

[info]
214 = "rew_a04"

[characters]
295 = "アクア"
298 = "カズマ（Ｍ）"
296 = "カズマ"

[character_subs]
# 296 = "カズマ"

[script]
# lines: 76

# アクア
# うふふ、カーズマ♪
254 = "うふふ、カーズマ♪"

# カズマ（Ｍ）
# display as カズマ
# （うわ、めっちゃご機嫌だし、\n　悪い予感しかしねー）
341 = "（うわ、めっちゃご機嫌だし、\\n　悪い予感しかしねー）"

# カズマ
# いいか、アクア。\n先に言っておくけど、お仕置きじゃなくて、\nご褒美だからな！
251 = "いいか、アクア。\\n先に言っておくけど、お仕置きじゃなくて、\\nご褒美だからな！"

# カズマ
# そこんとこ勘違いしてないよな。
264 = "そこんとこ勘違いしてないよな。"

# アクア
# あたりまえじゃない。
244 = "あたりまえじゃない。"

# アクア
# もう泣いて、アクア様～ってひれ伏しちゃうような\n最高のご褒美を考えたんだから。
292 = "もう泣いて、アクア様～ってひれ伏しちゃうような\\n最高のご褒美を考えたんだから。"

# カズマ
# それで？　いったい何をしてくれるんだよ。
265 = "それで？　いったい何をしてくれるんだよ。"

# アクア
# ポエムよ！
299 = "ポエムよ！"

# カズマ
# は？
288 = "は？"

# アクア
# だからポエムよ、ポエム。\nカズマへの感謝の気持ちを詩として綴ったの。
271 = "だからポエムよ、ポエム。\\nカズマへの感謝の気持ちを詩として綴ったの。"

# カズマ（Ｍ）
# display as カズマ
# （なんだそれ……）
344 = "（なんだそれ……）"

# アクア
# 丸１日使って作った力作なんだからね。\nほら、座って座って。
300 = "丸１日使って作った力作なんだからね。\\nほら、座って座って。"

# カズマ
# はいはい、わかったよ。
287 = "はいはい、わかったよ。"

# アクア
# では、コホン。\nご神託だと思って、居住まいを正して聞きなさい。
280 = "では、コホン。\\nご神託だと思って、居住まいを正して聞きなさい。"

# アクア
# カズマへ。
297 = "カズマへ。"

# アクア
# あなたと出会い、どれくらいの月日が\n流れたでしょう。
247 = "あなたと出会い、どれくらいの月日が\\n流れたでしょう。"

# アクア
# あなたに異世界に無理矢理連れて来られたときは、\nどうなるかと思いました。
248 = "あなたに異世界に無理矢理連れて来られたときは、\\nどうなるかと思いました。"

# アクア
# だってあなたは生っ粋の引きこもり。\nさらにニートときたものです。
273 = "だってあなたは生っ粋の引きこもり。\\nさらにニートときたものです。"

# カズマ（Ｍ）
# display as カズマ
# （ニートじゃねーよ！）
346 = "（ニートじゃねーよ！）"

# アクア
# 正直、絶望しかありませんでした、\nお先真っ暗でした。
307 = "正直、絶望しかありませんでした、\\nお先真っ暗でした。"

# アクア
# でも、あなたは天賦の才ともいえる\nずる賢さと、とんでもない強運で――
281 = "でも、あなたは天賦の才ともいえる\\nずる賢さと、とんでもない強運で――"

# カズマ
# ちょーーーーーー、待て！！
277 = "ちょーーーーーー、待て！！"

# アクア
# なによー。
285 = "なによー。"

# カズマ
# どこが感謝の言葉なんだよ！\n引きこもりとかずる賢さとか\nけなしてるだけじゃねーか！
284 = "どこが感謝の言葉なんだよ！\\n引きこもりとかずる賢さとか\\nけなしてるだけじゃねーか！"

# アクア
# でも事実でしょ？
282 = "でも事実でしょ？"

# カズマ
# いや、そうだけど。\n人間って、本当のこと言われると、\nマジでへこむもんでさ……。
252 = "いや、そうだけど。\\n人間って、本当のこと言われると、\\nマジでへこむもんでさ……。"

# カズマ
# てか、感謝するなら褒めろよ！\n無理矢理にでもいいところを見つけてさ！
278 = "てか、感謝するなら褒めろよ！\\n無理矢理にでもいいところを見つけてさ！"

# カズマ
# だいたいポエムにもなってないから！
270 = "だいたいポエムにもなってないから！"

# アクア
# もー、今のは前菜よ、前菜。\nこれからがメインディッシュ、本番なんだからね。
294 = "もー、今のは前菜よ、前菜。\\nこれからがメインディッシュ、本番なんだからね。"

# カズマ（Ｍ）
# display as カズマ
# （疑わしい……）
348 = "（疑わしい……）"

# アクア
# ……すぅ。
241 = "……すぅ。"

# アクア
# 異世界から来た者よ、そなたは我らが武器であり\n盾であり――
308 = "異世界から来た者よ、そなたは我らが武器であり\\n盾であり――"

# アクア
# この世界の邪悪の対抗となる、強き助けよ。
262 = "この世界の邪悪の対抗となる、強き助けよ。"

# アクア
# 魔王の軍団がどんな手を使って攻めて来ても、\nあなたがいれば恐るることはない。
340 = "魔王の軍団がどんな手を使って攻めて来ても、\\nあなたがいれば恐るることはない。"

# アクア
# この世界の人の力は弱くて頼りないけれど、\nあなたは女神に選ばれし、神の使い。
261 = "この世界の人の力は弱くて頼りないけれど、\\nあなたは女神に選ばれし、神の使い。"

# カズマ（Ｍ）
# display as カズマ
# （おお……！\n　珍しく、アクアが神々しく見える！）
342 = "（おお……！\\n　珍しく、アクアが神々しく見える！）"

# アクア
# どう！　なかなか良かったでしょ！
283 = "どう！　なかなか良かったでしょ！"

# カズマ
# お、おう。割と本気で感心したぜ。\nアクアはそんな風に俺の事を思ってたのか。
259 = "お、おう。割と本気で感心したぜ。\\nアクアはそんな風に俺の事を思ってたのか。"

# アクア
# ふふん？　感謝しなさいよ？
290 = "ふふん？　感謝しなさいよ？"

# カズマ
# ああ、俺にも礼を言わせてくれ。
243 = "ああ、俺にも礼を言わせてくれ。"

# アクア
# え？　な、何よいきなり。
258 = "え？　な、何よいきなり。"

# カズマ
# 言ったろ、割と本気で感心したって。\nやる時はやるじゃないか、アクア。
338 = "言ったろ、割と本気で感心したって。\\nやる時はやるじゃないか、アクア。"

# アクア
# 見直したかしら？
337 = "見直したかしら？"

# カズマ
# ああ、ちょこっとな！
242 = "ああ、ちょこっとな！"

# アクア
# ちょこっとって、何よー！！
274 = "ちょこっとって、何よー！！"

# カズマ
# ちょっと褒めすぎだって～、\n背中がこそばゆいだろ～。
276 = "ちょっと褒めすぎだって～、\\n背中がこそばゆいだろ～。"

# アクア
# 今のうち堪能しておきなさい。\nこんな出血大サービス、\nこれが最初で最後なんだから。
301 = "今のうち堪能しておきなさい。\\nこんな出血大サービス、\\nこれが最初で最後なんだから。"

# カズマ
# それはそれで何か複雑なんだが。
267 = "それはそれで何か複雑なんだが。"

# アクア
# 大体聞いててわかるでしょ？\n半分くらいは話盛ってるって。
304 = "大体聞いててわかるでしょ？\\n半分くらいは話盛ってるって。"

# カズマ
# おいっ！！
260 = "おいっ！！"

# カズマ
# ま、まあ言われて当然だけどな！
291 = "ま、まあ言われて当然だけどな！"

# アクア
# ええ、そうね。
255 = "ええ、そうね。"

# カズマ
# …………。
240 = "…………。"

# アクア
# ふふふ。
289 = "ふふふ。"

# カズマ
# 頼むから突っ込んでくれよ。\n虚しくなるだろ。
339 = "頼むから突っ込んでくれよ。\\n虚しくなるだろ。"

# カズマ（Ｍ）
# display as カズマ
# （と、そんなわけで、その後もアクアのポエムは\n　続いたのだが……）
343 = "（と、そんなわけで、その後もアクアのポエムは\\n　続いたのだが……）"

# アクア
# ええと、あとは……。
256 = "ええと、あとは……。"

# カズマ（Ｍ）
# display as カズマ
# （俺を褒めるネタはすぐに切れたのか、\n　今は眉間に深いシワを使りながら、\n　必死に持ち上げる言葉を搾り出そうとしている）
347 = "（俺を褒めるネタはすぐに切れたのか、\\n　今は眉間に深いシワを使りながら、\\n　必死に持ち上げる言葉を搾り出そうとしている）"

# アクア
# ぬぐぐぐ、そ、そう！　あれよあれ！\nお金を貸してくれるわよね！
286 = "ぬぐぐぐ、そ、そう！　あれよあれ！\\nお金を貸してくれるわよね！"

# カズマ
# てかお前、貸した金返せよ。
279 = "てかお前、貸した金返せよ。"

# アクア
# あとは、優しい感じがする！
246 = "あとは、優しい感じがする！"

# カズマ
# ずいぶんアバウトだな！
263 = "ずいぶんアバウトだな！"

# アクア
# あー、もう無理！\nこれ以上は搾り出せない！\nもう、カラッカラッ！
249 = "あー、もう無理！\\nこれ以上は搾り出せない！\\nもう、カラッカラッ！"

# カズマ
# いやいや、褒め始めて\nまだ５分も経ってないんですけど！
253 = "いやいや、褒め始めて\\nまだ５分も経ってないんですけど！"

# アクア
# 私だってこんなに褒めるところがないなんて\n思って無かったわ。
335 = "私だってこんなに褒めるところがないなんて\\n思って無かったわ。"

# カズマ
# 持ち上げておいて、いきなり突き落とすとか\nお前は鬼か！
306 = "持ち上げておいて、いきなり突き落とすとか\\nお前は鬼か！"

# アクア
# だいたい、カズマは私のこと、\nちょっと軽く見すぎなのよ！
269 = "だいたい、カズマは私のこと、\\nちょっと軽く見すぎなのよ！"

# アクア
# 私は女神なの。\nこうやって直接言葉を貰えるだけでも\nありがたいことなのよ！
336 = "私は女神なの。\\nこうやって直接言葉を貰えるだけでも\\nありがたいことなのよ！"

# アクア
# それなのに、馬小屋で寝かせるし、\n肉体労働させるし、顎で使うしっ！
266 = "それなのに、馬小屋で寝かせるし、\\n肉体労働させるし、顎で使うしっ！"

# アクア
# もっと私のことを崇めなさいよ！\n褒め称えなさいよ！\n従者のくせに信仰心が足りな過ぎるのよ！
293 = "もっと私のことを崇めなさいよ！\\n褒め称えなさいよ！\\n従者のくせに信仰心が足りな過ぎるのよ！"

# カズマ
# だから従者じゃねーって言ってるだろ！\nお前もいい加減自覚しろ！
272 = "だから従者じゃねーって言ってるだろ！\\nお前もいい加減自覚しろ！"

# アクア
# あー、もう疲れたー、喉もカラカラ～。
250 = "あー、もう疲れたー、喉もカラカラ～。"

# カズマ
# それは俺も同じだ。
268 = "それは俺も同じだ。"

# アクア
# あっ、それならさ！\nまだ時間は早いけど、これからシュワシュワ\n飲みに行かない！
245 = "あっ、それならさ！\\nまだ時間は早いけど、これからシュワシュワ\\n飲みに行かない！"

# アクア
# えへへ、カズマさんのおごりだと\n嬉しいな～。
257 = "えへへ、カズマさんのおごりだと\\n嬉しいな～。"

# カズマ（Ｍ）
# display as カズマ
# （ダメだ、アクアに感謝とかそういう慎ましやかな\n　ことを期待した俺がバカだった……）
345 = "（ダメだ、アクアに感謝とかそういう慎ましやかな\\n　ことを期待した俺がバカだった……）"

[selections]
302 = "俺にも礼を言わせてくれ"
275 = "ちょっと褒めすぎだって～"
# 291 = "ま、まあ言われて当然だけどな！"
