# rew_a06.txt.scn

[info]
179 = "rew_a06"

[characters]
238 = "アクア"
240 = "カズマ（Ｍ）"
239 = "カズマ"

[character_subs]
# 239 = "カズマ"

[script]
# lines: 59

# アクア
# さあカズマお仕置きの時間よ！
207 = "さあカズマお仕置きの時間よ！"

# カズマ（Ｍ）
# display as カズマ
# （うわー、めちゃくちゃテンション\n　高いんだけど……）
282 = "（うわー、めちゃくちゃテンション\\n　高いんだけど……）"

# アクア
# ああ、我ながら恐ろしいお仕置きを\n思いついてしまったわ。
200 = "ああ、我ながら恐ろしいお仕置きを\\n思いついてしまったわ。"

# アクア
# でも、私は心を鬼にするの！\nだってこれはお仕置きだから！
226 = "でも、私は心を鬼にするの！\\nだってこれはお仕置きだから！"

# カズマ（Ｍ）
# display as カズマ
# （しかも目を爛々とさせてるし）
285 = "（しかも目を爛々とさせてるし）"

# カズマ
# それで、いったい何をするつもりなんだよ。
215 = "それで、いったい何をするつもりなんだよ。"

# カズマ
# まさか水責めか？　それとも火あぶり？\nもしかしてアイアンメイデン？？
235 = "まさか水責めか？　それとも火あぶり？\\nもしかしてアイアンメイデン？？"

# アクア
# あんた、私をなんだと思ってるわけ？
201 = "あんた、私をなんだと思ってるわけ？"

# カズマ
# 女神の皮を被った悪魔。
249 = "女神の皮を被った悪魔。"

# アクア
# どうやらその口にゴッドブローを\nぶち込まれたいようね。
228 = "どうやらその口にゴッドブローを\\nぶち込まれたいようね。"

# カズマ
# じじ、冗談だって！
209 = "じじ、冗談だって！"

# アクア
# まあいいわ。私は寛大だから許してあげる。\n感謝しなさい。
234 = "まあいいわ。私は寛大だから許してあげる。\\n感謝しなさい。"

# カズマ
# はいはい、それはどうも。\nそれで？　何をするのかそろそろ教えてくれよ。
231 = "はいはい、それはどうも。\\nそれで？　何をするのかそろそろ教えてくれよ。"

# アクア
# それはズバリ！　私への奉仕よ！
216 = "それはズバリ！　私への奉仕よ！"

# カズマ
# はぁ……お前は今の自堕落生活に\nさらに拍車をかけるつもりか。
230 = "はぁ……お前は今の自堕落生活に\\nさらに拍車をかけるつもりか。"

# アクア
# ちょっと、ご主人様に向かってその口の利き方は\nどうなのかしら？
224 = "ちょっと、ご主人様に向かってその口の利き方は\\nどうなのかしら？"

# カズマ
# もう始まってるのかよ！
236 = "もう始まってるのかよ！"

# アクア
# 当然でしょ。\nでも、うーん、ダメね。
252 = "当然でしょ。\\nでも、うーん、ダメね。"

# カズマ
# 何が。
245 = "何が。"

# アクア
# 格好が私を奉仕するのに相応しくないって\n言ってるの。
255 = "格好が私を奉仕するのに相応しくないって\\n言ってるの。"

# カズマ
# わかったわかった、執事服に着替えるから\nちょっと廊下に出ててくれ。
237 = "わかったわかった、執事服に着替えるから\\nちょっと廊下に出ててくれ。"

# アクア
# その必要は無いわよ。\nちゃんとカズマの服を持ってきたから。
214 = "その必要は無いわよ。\\nちゃんとカズマの服を持ってきたから。"

# アクア
# まあ、問題はサイズが合うかどうかなんだけど、\n最悪、無理矢理着ればいいと思うの。
232 = "まあ、問題はサイズが合うかどうかなんだけど、\\n最悪、無理矢理着ればいいと思うの。"

# カズマ
# ちょっ、待て！　まさかお前！
223 = "ちょっ、待て！　まさかお前！"

# アクア
# うふふふ、カズマならきっと、\nメイド服も似合うわよ。
204 = "うふふふ、カズマならきっと、\\nメイド服も似合うわよ。"

# カズマ
# ぐっ……なるほど、それがお仕置きのメインと\nいうわけか。
206 = "ぐっ……なるほど、それがお仕置きのメインと\\nいうわけか。"

# カズマ（Ｍ）
# display as カズマ
# （マズい、奉仕させられるだけならまだしも\n　女装をさせられるなんて、これ以上無い屈辱だ）
287 = "（マズい、奉仕させられるだけならまだしも\\n　女装をさせられるなんて、これ以上無い屈辱だ）"

# カズマ（Ｍ）
# display as カズマ
# （だが、お仕置きなのは事実だしな……素直に言う\n　ことを聞くしかないか……）
286 = "（だが、お仕置きなのは事実だしな……素直に言う\\n　ことを聞くしかないか……）"

# カズマ
# しょうがない。ここは素直に言うことを聞いて\nやろう。
208 = "しょうがない。ここは素直に言うことを聞いて\\nやろう。"

# アクア
# どうして上から目線なのよ。
227 = "どうして上から目線なのよ。"

# カズマ
# 俺にもこう、引けないラインというものがあってな。\nせめて話を聞く代わりに尊大な態度を取ってる\nだけだ。
247 = "俺にもこう、引けないラインというものがあってな。\\nせめて話を聞く代わりに尊大な態度を取ってる\\nだけだ。"

# アクア
# 本音は？
254 = "本音は？"

# カズマ
# そんなもん着たくねーに決まってるだろ！
218 = "そんなもん着たくねーに決まってるだろ！"

# カズマ
# メイドは愛でるもんであって、\n自分で演じて楽しむもんじゃないんだよ！
243 = "メイドは愛でるもんであって、\\n自分で演じて楽しむもんじゃないんだよ！"

# アクア
# 正直でよろしい。\nでも、これはお仕置きなんだから、\n拒否は許されないわよ。
256 = "正直でよろしい。\\nでも、これはお仕置きなんだから、\\n拒否は許されないわよ。"

# カズマ（Ｍ）
# display as カズマ
# （ここは抵抗するしかない！\n　男の尊厳の問題だ！）
284 = "（ここは抵抗するしかない！\\n　男の尊厳の問題だ！）"

# カズマ
# 嫌だ！　俺は絶対に着ないぞ！！
250 = "嫌だ！　俺は絶対に着ないぞ！！"

# アクア
# ちょっと駄々こねるなんて、男らしくないわよ！
225 = "ちょっと駄々こねるなんて、男らしくないわよ！"

# カズマ
# 男らしくないことされようとしてるのに、\nなりふり構ってられるか！
257 = "男らしくないことされようとしてるのに、\\nなりふり構ってられるか！"

# アクア
# まあ、着ないって言うならそれでも構わないわよ。
233 = "まあ、着ないって言うならそれでも構わないわよ。"

# アクア
# そのかわり、ダクネスやめぐみんにあのことを\nバラすっていうお仕置きに変更するだけだし。
213 = "そのかわり、ダクネスやめぐみんにあのことを\\nバラすっていうお仕置きに変更するだけだし。"

# カズマ
# な、なななな、なんだって！？\n何をバラすって言うんだ！！
229 = "な、なななな、なんだって！？\\n何をバラすって言うんだ！！"

# アクア
# 例えばそうね。\nベッドの下の――
246 = "例えばそうね。\\nベッドの下の――"

# カズマ
# ちょぉぉおお、待てーーーー！！\nおおお、お前は鬼か！　悪魔か！
222 = "ちょぉぉおお、待てーーーー！！\\nおおお、お前は鬼か！　悪魔か！"

# アクア
# 鬼でも悪魔でもなく女神よ。\nほら、わかったなら早く着てきなさい。
281 = "鬼でも悪魔でもなく女神よ。\\nほら、わかったなら早く着てきなさい。"

# カズマ
# メ、メイド服ならアクアの方が似合うはずだ！
242 = "メ、メイド服ならアクアの方が似合うはずだ！"

# アクア
# そんなの当たり前じゃない。\n女なんだから。
217 = "そんなの当たり前じゃない。\\n女なんだから。"

# カズマ
# そ、そうだよな。\n実際、メイド服姿のお前、綺麗だったもんな！
211 = "そ、そうだよな。\\n実際、メイド服姿のお前、綺麗だったもんな！"

# カズマ
# だからこのメイド服も、\nお前に着られた方が幸せだと思うんだ！
220 = "だからこのメイド服も、\\nお前に着られた方が幸せだと思うんだ！"

# アクア
# カズマ？
241 = "カズマ？"

# カズマ
# お、おう、なんだ？
205 = "お、おう、なんだ？"

# アクア
# いいから、着て。
202 = "いいから、着て。"

# カズマ
# 絶対に嫌だ！！
280 = "絶対に嫌だ！！"

# アクア
# じゃあ、これは女神の慈悲。\n下着だけはそのままで許してあげるわ。
210 = "じゃあ、これは女神の慈悲。\\n下着だけはそのままで許してあげるわ。"

# カズマ
# そんな慈悲はいらねえよ！
219 = "そんな慈悲はいらねえよ！"

# アクア
# そうなの？　じゃあやっぱり下着も――
212 = "そうなの？　じゃあやっぱり下着も――"

# カズマ
# いや、うそうそうそ！\nパンツだけは勘弁して下さい！
203 = "いや、うそうそうそ！\\nパンツだけは勘弁して下さい！"

# アクア
# だったら、着ましょうね？\n私の気持ちが変わらないうちに。
221 = "だったら、着ましょうね？\\n私の気持ちが変わらないうちに。"

# カズマ（Ｍ）
# display as カズマ
# （く、く、くそぉぉ～～……）
283 = "（く、く、くそぉぉ～～……）"

[selections]
279 = "素直に言うことを聞こう"
253 = "抵抗をしてみよう"
244 = "メイド服ならアクアの方が似合うはずだ！"
