# rew_c05.txt.scn

[info]
258 = "rew_c05"

[characters]
372 = "カズマ"
378 = "ダクネス"
375 = "カズマ（Ｍ）"

[character_subs]
# 372 = "カズマ"

[script]
# lines: 124

# カズマ
# うーむ。
296 = "うーむ。"

# ダクネス
# カズマどうした。\nさっきから私をジッと見て、唸っている\nだけじゃないか。
374 = "カズマどうした。\\nさっきから私をジッと見て、唸っている\\nだけじゃないか。"

# ダクネス
# ま、まあ、そういう趣旨だというのであれば\n受け入れなくもないが。
357 = "ま、まあ、そういう趣旨だというのであれば\\n受け入れなくもないが。"

# カズマ
# そういう趣旨ってなんだよ。
317 = "そういう趣旨ってなんだよ。"

# ダクネス
# そこまで私に説明をさせるつもりなのか。\nふふ、さすがカズマだな。
319 = "そこまで私に説明をさせるつもりなのか。\\nふふ、さすがカズマだな。"

# カズマ
# はぁ、お前にその妄想癖がなければ、\n女性として完璧なのに、本当にもったいない……。
346 = "はぁ、お前にその妄想癖がなければ、\\n女性として完璧なのに、本当にもったいない……。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、なるほど、そっか。\n　それならそういうご褒美をねだればいいのか）
418 = "（ああ、なるほど、そっか。\\n　それならそういうご褒美をねだればいいのか）"

# カズマ
# よし、ダクネス！\nご褒美の内容を決めたぞ！
366 = "よし、ダクネス！\\nご褒美の内容を決めたぞ！"

# ダクネス
# おお、なんだ、何をさせるつもりだ？
301 = "おお、なんだ、何をさせるつもりだ？"

# カズマ
# それはお前の魅力を最大限に活かせるものだ。
323 = "それはお前の魅力を最大限に活かせるものだ。"

# ダクネス
# なるほど、\n獣の群れを相手に盾として働けというわけだな！
341 = "なるほど、\\n獣の群れを相手に盾として働けというわけだな！"

# ダクネス
# それなら大得意だ。任せておけ。
322 = "それなら大得意だ。任せておけ。"

# カズマ
# 職業的な魅力じゃなくて、女としての魅力だよ。
414 = "職業的な魅力じゃなくて、女としての魅力だよ。"

# ダクネス
# 女としての？\nはっ！？　さては私を――
386 = "女としての？\\nはっ！？　さては私を――"

# カズマ
# その想像は間違いなく外れてるから\n言わなくていい！！
320 = "その想像は間違いなく外れてるから\\n言わなくていい！！"

# ダクネス
# そ、そうか。
313 = "そ、そうか。"

# カズマ
# 残念そうにするなよ。
391 = "残念そうにするなよ。"

# ダクネス
# それで女の魅力を活かすカズマへのご褒美とは\nなんなんだ。
321 = "それで女の魅力を活かすカズマへのご褒美とは\\nなんなんだ。"

# カズマ
# お前って腐ってもお嬢様じゃん。
304 = "お前って腐ってもお嬢様じゃん。"

# ダクネス
# さらりと酷いことを言うな……。
309 = "さらりと酷いことを言うな……。"

# カズマ
# だから俺が知らないお嬢様のダクネスを\nチラっとでもいいから見せて貰えたらって\n思っただけだよ。
327 = "だから俺が知らないお嬢様のダクネスを\\nチラっとでもいいから見せて貰えたらって\\n思っただけだよ。"

# ダクネス
# そんなことでご褒美になるのか？
325 = "そんなことでご褒美になるのか？"

# カズマ
# ああ、なるさ！\nギャップ萌えというやつだ！
289 = "ああ、なるさ！\\nギャップ萌えというやつだ！"

# ダクネス
# ぎゃ、ぎゃっぷもえ？
305 = "ぎゃ、ぎゃっぷもえ？"

# カズマ
# とりあえずそれっぽい服に着替えてきてくれ。
330 = "とりあえずそれっぽい服に着替えてきてくれ。"

# ダクネス
# わ、わかった。\nでもあまり期待をしないでくれよ？
368 = "わ、わかった。\\nでもあまり期待をしないでくれよ？"

# カズマ（Ｍ）
# display as カズマ
# （うむ、我ながら素晴らしいご褒美を考えたな！）
421 = "（うむ、我ながら素晴らしいご褒美を考えたな！）"

# カズマ（Ｍ）
# display as カズマ
# （遅いな。\n　着替えってそんなに時間がかかるもんなのか？）
436 = "（遅いな。\\n　着替えってそんなに時間がかかるもんなのか？）"

# ダクネス
# カズマ？
376 = "カズマ？"

# カズマ
# ん、どうした？　遠慮しないで入ってこいよ。
371 = "ん、どうした？　遠慮しないで入ってこいよ。"

# ダクネス
# いや、だが、やはり抵抗があると言うか。\nこのような格好の私を見ても、カズマへの褒美に\nならないと思うんだ。
291 = "いや、だが、やはり抵抗があると言うか。\\nこのような格好の私を見ても、カズマへの褒美に\\nならないと思うんだ。"

# カズマ
# それを決めるのは俺だよ。\nほーら、いいから入ってこいって。
324 = "それを決めるのは俺だよ。\\nほーら、いいから入ってこいって。"

# ダクネス
# わ、わかった。\nだが、最初は目をつむっていて欲しい。
367 = "わ、わかった。\\nだが、最初は目をつむっていて欲しい。"

# カズマ
# はぁ？　どうして。
347 = "はぁ？　どうして。"

# ダクネス
# は、恥ずかしいんだ！
345 = "は、恥ずかしいんだ！"

# カズマ
# わかったわかった。\n目をつむればいいんだな。
370 = "わかったわかった。\\n目をつむればいいんだな。"

# カズマ
# ほら、つむったぞ。
355 = "ほら、つむったぞ。"

# ダクネス
# じゃあ、入るぞ。\n私がいいと言うまで目を開けたらダメだからな。
312 = "じゃあ、入るぞ。\\n私がいいと言うまで目を開けたらダメだからな。"

# カズマ
# な、なんかすごいドキドキするんですけど！
335 = "な、なんかすごいドキドキするんですけど！"

# ダクネス
# あ、ああ、私も心臓が今にも破裂しそうだ。
286 = "あ、ああ、私も心臓が今にも破裂しそうだ。"

# カズマ
# な、なあ、もう、開けてもいいよな！
333 = "な、なあ、もう、開けてもいいよな！"

# ダクネス
# まだダメだ！\nもう少しだけ、落ち着くための時間をくれ。
361 = "まだダメだ！\\nもう少しだけ、落ち着くための時間をくれ。"

# カズマ（Ｍ）
# display as カズマ
# （ああっ、もうっ、なんなんだよ！\n　じれったいな！）
419 = "（ああっ、もうっ、なんなんだよ！\\n　じれったいな！）"

# ダクネス
# うぅ、ダメだ緊張がまったく取れない。
294 = "うぅ、ダメだ緊張がまったく取れない。"

# カズマ（Ｍ）
# display as カズマ
# （ちょっとだけ、こっそりだったら……）
432 = "（ちょっとだけ、こっそりだったら……）"

# カズマ（Ｍ）
# display as カズマ
# （お、おお、おおーーーー！！\n　なんかエロい！）
425 = "（お、おお、おおーーーー！！\\n　なんかエロい！）"

# ダクネス
# ど、どうしてこんな格好の私が見たいんだ。\nまったく理解できん。
332 = "ど、どうしてこんな格好の私が見たいんだ。\\nまったく理解できん。"

# カズマ（Ｍ）
# display as カズマ
# （どういう表情をしてるんだ……）
433 = "（どういう表情をしてるんだ……）"

# カズマ（Ｍ）
# display as カズマ
# （そうそう、この顔！\n　俺はダクネスのにやけてない、\n　こういう恥ずかしがる顔を見たかったんだ！）
430 = "（そうそう、この顔！\\n　俺はダクネスのにやけてない、\\n　こういう恥ずかしがる顔を見たかったんだ！）"

# ダクネス
# な、なあ、カズマ？
334 = "な、なあ、カズマ？"

# カズマ（Ｍ）
# display as カズマ
# （普段は鎧に隠れてまったくわからないけど\n　体のラインもなかなか……）
434 = "（普段は鎧に隠れてまったくわからないけど\\n　体のラインもなかなか……）"

# ダクネス
# カズマ？　どうかしたか？
377 = "カズマ？　どうかしたか？"

# カズマ（Ｍ）
# display as カズマ
# （さーらーにっ！）
428 = "（さーらーにっ！）"

# カズマ（Ｍ）
# display as カズマ
# （そうこれ！\n　ダクネスといえばここ！！）
429 = "（そうこれ！\\n　ダクネスといえばここ！！）"

# ダクネス
# おーい、カズマー。
303 = "おーい、カズマー。"

# カズマ
# え？　あ、なんだ？
299 = "え？　あ、なんだ？"

# ダクネス
# 考えたのだが、やはりこれは褒美にならないと\n思うんだ。
413 = "考えたのだが、やはりこれは褒美にならないと\\n思うんだ。"

# カズマ
# そんなことないって！\n綺麗な女の子を見て喜ばない男なんていないだろ！
326 = "そんなことないって！\\n綺麗な女の子を見て喜ばない男なんていないだろ！"

# ダクネス
# ど、どうして、\n私が、その、綺麗だと言い切れる。
331 = "ど、どうして、\\n私が、その、綺麗だと言い切れる。"

# カズマ
# いやだって、実際そうだし。
293 = "いやだって、実際そうだし。"

# ダクネス
# こ、こら、勝手に目を開けるな！
307 = "こ、こら、勝手に目を開けるな！"

# カズマ
# なるほど、なるほどねー。\nこれがお嬢様のダクネス。\nふーん、へえ、ほほう。
342 = "なるほど、なるほどねー。\\nこれがお嬢様のダクネス。\\nふーん、へえ、ほほう。"

# ダクネス
# や、やめろ。\nそういう羞恥は私の望む所じゃ無い。
364 = "や、やめろ。\\nそういう羞恥は私の望む所じゃ無い。"

# カズマ（Ｍ）
# display as カズマ
# （こいつのドＭゾーンはいまいちわからないな……）
427 = "（こいつのドＭゾーンはいまいちわからないな……）"

# ダクネス
# もも、もう見たから満足だろう。\n私は着替えてくるぞ。
363 = "もも、もう見たから満足だろう。\\n私は着替えてくるぞ。"

# カズマ
# ちょー、待て！\nこれからが本番なんだよ！
328 = "ちょー、待て！\\nこれからが本番なんだよ！"

# ダクネス
# ほ、ほほう、本番。\nど、どう、辱めるつもりだ。
354 = "ほ、ほほう、本番。\\nど、どう、辱めるつもりだ。"

# カズマ（Ｍ）
# display as カズマ
# （あ、これは嬉しいんだ……）
416 = "（あ、これは嬉しいんだ……）"

# カズマ（Ｍ）
# display as カズマ
# （だけどこれじゃご褒美にならない）
431 = "（だけどこれじゃご褒美にならない）"

# カズマ（Ｍ）
# display as カズマ
# （うーん。\n　ダクネスのお嬢様部分を引きずり出すためには、\n　どうしたらいいんだ？）
423 = "（うーん。\\n　ダクネスのお嬢様部分を引きずり出すためには、\\n　どうしたらいいんだ？）"

# カズマ
# なあ、ダクネス。\nちょっと口調を変えて貰えるか？
338 = "なあ、ダクネス。\\nちょっと口調を変えて貰えるか？"

# ダクネス
# 断る！
390 = "断る！"

# カズマ
# まず、そうだな。\nやっぱりお嬢様と言えばですわ口調かな。
359 = "まず、そうだな。\\nやっぱりお嬢様と言えばですわ口調かな。"

# ダクネス
# 人の話を聞け！
381 = "人の話を聞け！"

# カズマ
# はい、スタート！
350 = "はい、スタート！"

# ダクネス
# え？　え？
300 = "え？　え？"

# カズマ
# ほーら、ですわだよですわ。\n語尾をですわにするの！
356 = "ほーら、ですわだよですわ。\\n語尾をですわにするの！"

# ダクネス
# そ、そんなこと急に言われても……。
316 = "そ、そんなこと急に言われても……。"

# カズマ
# ですわを忘れてる！
329 = "ですわを忘れてる！"

# ダクネス
# ～～～～～～！！
437 = "～～～～～～！！"

# カズマ
# はい、そんなこと急に言われても？
349 = "はい、そんなこと急に言われても？"

# ダクネス
# こ、こ、困ります……ですわ。
306 = "こ、こ、困ります……ですわ。"

# カズマ
# うん、無いわ。
295 = "うん、無いわ。"

# ダクネス
# なっ！？
340 = "なっ！？"

# カズマ（Ｍ）
# display as カズマ
# （うーん、お嬢様って意外に難しいんだな）
422 = "（うーん、お嬢様って意外に難しいんだな）"

# カズマ
# なあ、ダクネス。\n笑顔を見せてくれよ。
339 = "なあ、ダクネス。\\n笑顔を見せてくれよ。"

# ダクネス
# わ、笑えばいいのか？
369 = "わ、笑えばいいのか？"

# カズマ
# ああ、それくらいなら簡単だろ？
288 = "ああ、それくらいなら簡単だろ？"

# ダクネス
# そ、そうだな。\n笑顔、笑顔――
315 = "そ、そうだな。\\n笑顔、笑顔――"

# ダクネス
# ふ、ふふ、こうか？
352 = "ふ、ふふ、こうか？"

# カズマ
# はい、違う。\n求めてるのはそういう笑顔じゃないから。
351 = "はい、違う。\\n求めてるのはそういう笑顔じゃないから。"

# ダクネス
# むぅ、笑うというのは意外に難しいのだぞ。
362 = "むぅ、笑うというのは意外に難しいのだぞ。"

# カズマ
# じゃあ、お前がされて嬉しいことを\n想像してみてくれよ。
310 = "じゃあ、お前がされて嬉しいことを\\n想像してみてくれよ。"

# カズマ
# そうすれば自然に笑えるだろ。
318 = "そうすれば自然に笑えるだろ。"

# ダクネス
# 嬉しいこと……。
387 = "嬉しいこと……。"

# カズマ
# はい、ごめん。\n今のは俺の指示が悪かったわ。
348 = "はい、ごめん。\\n今のは俺の指示が悪かったわ。"

# ダクネス
# なんなんだいったい。
343 = "なんなんだいったい。"

# カズマ
# じゃあ、そうだなー。\n家族と話しをしているときの笑顔ってのはどうだ？
311 = "じゃあ、そうだなー。\\n家族と話しをしているときの笑顔ってのはどうだ？"

# ダクネス
# 家族と話しをしているときか。
388 = "家族と話しをしているときか。"

# ダクネス
# こうか？
308 = "こうか？"

# カズマ
# おおっ、きた！　それ！\n俺が求めてたの、その笑顔！
302 = "おおっ、きた！　それ！\\n俺が求めてたの、その笑顔！"

# ダクネス
# ま、マジマジと見るな。\n恥ずかしいだろ。
358 = "ま、マジマジと見るな。\\n恥ずかしいだろ。"

# カズマ
# あー、その表情も好きだけど、今は笑顔！\nほーら、最高に可愛かったんだからさ！
290 = "あー、その表情も好きだけど、今は笑顔！\\nほーら、最高に可愛かったんだからさ！"

# ダクネス
# やめてくれ。\n背中がむず痒くなる。
365 = "やめてくれ。\\n背中がむず痒くなる。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、いいねー。\n　この笑顔を守るためだったら、\n　俺は余裕で死ねるわ）
417 = "（ああ、いいねー。\\n　この笑顔を守るためだったら、\\n　俺は余裕で死ねるわ）"

# カズマ（Ｍ）
# display as カズマ
# （褒めちぎれば、お嬢様のダクネスを\n　引きずり出せるかもしれないな）
435 = "（褒めちぎれば、お嬢様のダクネスを\\n　引きずり出せるかもしれないな）"

# カズマ
# ダクネス！
379 = "ダクネス！"

# ダクネス
# な、なんだ？
336 = "な、なんだ？"

# カズマ
# 美しい！
412 = "美しい！"

# ダクネス
# え……？
297 = "え……？"

# カズマ
# 声が綺麗だ！
385 = "声が綺麗だ！"

# ダクネス
# は……？
344 = "は……？"

# カズマ
# え、ええと、マツゲが長いですね！
298 = "え、ええと、マツゲが長いですね！"

# ダクネス
# そ、そうか？
314 = "そ、そうか？"

# カズマ
# あ、あと……やさ……しい……です。\nはい。
287 = "あ、あと……やさ……しい……です。\\nはい。"

# カズマ（Ｍ）
# display as カズマ
# （あかん！\n　女の子を褒めるなんて、引きこもりの俺には\n　難易度が高すぎる！）
420 = "（あかん！\\n　女の子を褒めるなんて、引きこもりの俺には\\n　難易度が高すぎる！）"

# ダクネス
# カズマ、無理をするな。
373 = "カズマ、無理をするな。"

# カズマ（Ｍ）
# display as カズマ
# （え……？）
424 = "（え……？）"

# ダクネス
# 何を求めているか知らないが、\n無理が透けて見えているぞ？
382 = "何を求めているか知らないが、\\n無理が透けて見えているぞ？"

# カズマ（Ｍ）
# display as カズマ
# （こ、この笑顔！\n　そう、俺が求めていたのはこれなんだよ！）
426 = "（こ、この笑顔！\\n　そう、俺が求めていたのはこれなんだよ！）"

# ダクネス
# なあ、カズマ、もう満足だろう？\nそろそろ鎧に着替えても……。
337 = "なあ、カズマ、もう満足だろう？\\nそろそろ鎧に着替えても……。"

# カズマ
# まだダメだよ。\nこんな機会はめったにないんだから、\nゆっくり目の保養をさせてもらうぞ。
360 = "まだダメだよ。\\nこんな機会はめったにないんだから、\\nゆっくり目の保養をさせてもらうぞ。"

# ダクネス
# ふふ、やはりそういう趣旨なのだな。
353 = "ふふ、やはりそういう趣旨なのだな。"

# カズマ
# いやいや、違う。\nそうだけど、そうじゃないから。
292 = "いやいや、違う。\\nそうだけど、そうじゃないから。"

[selections]
383 = "口調を変えさせよう"
411 = "笑顔を見せてくれ"
415 = "褒めちぎろう"
