# rew_f09.txt.scn

[info]
173 = "rew_f09"

[characters]
254 = "ウィズ"
258 = "カズマ（Ｍ）"
257 = "カズマ"

[character_subs]
# 257 = "カズマ"

[script]
# lines: 51

# ウィズ
# さ、どうぞ召し上がって下さい。
236 = "さ、どうぞ召し上がって下さい。"

# カズマ（Ｍ）
# display as カズマ
# （お仕置きに手料理を食べてくださいって、\n　何を出されるかと心配だったけど――）
298 = "（お仕置きに手料理を食べてくださいって、\\n　何を出されるかと心配だったけど――）"

# カズマ（Ｍ）
# display as カズマ
# （見た目も匂いも十分食欲を刺激してきて、\n　すっげー腹が減ってくるぞ）
303 = "（見た目も匂いも十分食欲を刺激してきて、\\n　すっげー腹が減ってくるぞ）"

# カズマ（Ｍ）
# display as カズマ
# （これがなんでお仕置きなんだ？）
299 = "（これがなんでお仕置きなんだ？）"

# カズマ
# あのさ、ウィズ。
222 = "あのさ、ウィズ。"

# ウィズ
# どうかしましたか？
244 = "どうかしましたか？"

# カズマ
# これってお仕置きになるのかなって。\nこんなの、お仕置きどころかご褒美だろ。
235 = "これってお仕置きになるのかなって。\\nこんなの、お仕置きどころかご褒美だろ。"

# ウィズ
# ああ、それはですね。\nこれ、実は初めて作った料理なんです。
218 = "ああ、それはですね。\\nこれ、実は初めて作った料理なんです。"

# カズマ
# 初めて？\nあれ、ウィズって普通に料理出来るだろ？
264 = "初めて？\\nあれ、ウィズって普通に料理出来るだろ？"

# ウィズ
# うーん、正確に言うなら、\n初めて使う食材で作った料理ですね。
227 = "うーん、正確に言うなら、\\n初めて使う食材で作った料理ですね。"

# カズマ
# ああなるほど、味見をしてくれっていうことか。\nそういうことなら遠慮なく！
220 = "ああなるほど、味見をしてくれっていうことか。\\nそういうことなら遠慮なく！"

# カズマ（Ｍ）
# display as カズマ
# （ウィズの料理ならハズレは無いだろ、前に飲んだ\n　紅茶なんてすごく美味しかったしな）
300 = "（ウィズの料理ならハズレは無いだろ、前に飲んだ\\n　紅茶なんてすごく美味しかったしな）"

# ウィズ
# はい、どうぞ召し上がって下さい。
246 = "はい、どうぞ召し上がって下さい。"

# カズマ
# ん、もぐもぐ、んぐっ、んむ……。
253 = "ん、もぐもぐ、んぐっ、んむ……。"

# ウィズ
# ど、どうでしょうか……？\n変な味になってたりしませんか？
243 = "ど、どうでしょうか……？\\n変な味になってたりしませんか？"

# カズマ
# うん、平気。美味いよ。
226 = "うん、平気。美味いよ。"

# ウィズ
# 本当ですか？　良かったです～！
268 = "本当ですか？　良かったです～！"

# カズマ
# ウィズはいいお嫁さんになれそうだな。
256 = "ウィズはいいお嫁さんになれそうだな。"

# ウィズ
# え？　え、えっえっ！？　そ、そうでしょうか。
229 = "え？　え、えっえっ！？　そ、そうでしょうか。"

# カズマ
# ああ、こんなに料理はうまいし、その他のことも\n駄女神や他のみんなに比べれば雲泥の差だしな。
217 = "ああ、こんなに料理はうまいし、その他のことも\\n駄女神や他のみんなに比べれば雲泥の差だしな。"

# カズマ
# ウィズなら引く手あまたになりそうだと思うぞ～。
255 = "ウィズなら引く手あまたになりそうだと思うぞ～。"

# ウィズ
# そ、そんな……て、照れちゃうじゃないですか。
239 = "そ、そんな……て、照れちゃうじゃないですか。"

# カズマ
# 俺のメイドになってくれませんか！
262 = "俺のメイドになってくれませんか！"

# ウィズ
# え？　メ、メイドですか？
230 = "え？　メ、メイドですか？"

# カズマ
# ああ。ウィズがメイドになってくれたら、\n毎日こんな美味しい料理を食べ放題じゃんか！
219 = "ああ。ウィズがメイドになってくれたら、\\n毎日こんな美味しい料理を食べ放題じゃんか！"

# ウィズ
# 別にメイドにならなくても、カズマさんさえ\n良かったら作ってあげますよ？
265 = "別にメイドにならなくても、カズマさんさえ\\n良かったら作ってあげますよ？"

# カズマ
# マジか！　割と本気で考えちゃうぞ！
259 = "マジか！　割と本気で考えちゃうぞ！"

# カズマ
# もしかしてこれは、プロポーズ！？
251 = "もしかしてこれは、プロポーズ！？"

# ウィズ
# えええ！？　なんでですかっ！？
228 = "えええ！？　なんでですかっ！？"

# カズマ
# いやあ、俺の国にさ、\n俺のために味噌汁を作ってくれという\nプロポーズの言葉があってさ。
224 = "いやあ、俺の国にさ、\\n俺のために味噌汁を作ってくれという\\nプロポーズの言葉があってさ。"

# カズマ
# あと、女が男を落としたかったら胃袋を掴め！\nなんて言葉もあるくらいで。
221 = "あと、女が男を落としたかったら胃袋を掴め！\\nなんて言葉もあるくらいで。"

# カズマ
# 今、俺の胃袋はウィズにがっちり掴まれた！\nこれはもう、プロポーズと思ったって仕方ない！
261 = "今、俺の胃袋はウィズにがっちり掴まれた！\\nこれはもう、プロポーズと思ったって仕方ない！"

# ウィズ
# ど、どういう理屈ですか！！\nで、でも、そうですか、カズマさんは、そんな\n風に思ってたり？
242 = "ど、どういう理屈ですか！！\\nで、でも、そうですか、カズマさんは、そんな\\n風に思ってたり？"

# カズマ
# あ、いや、冗談だって、冗談！！
216 = "あ、いや、冗談だって、冗談！！"

# ウィズ
# ふふ、冗談でもちょっと嬉しいですね。
249 = "ふふ、冗談でもちょっと嬉しいですね。"

# ウィズ
# それじゃ、腕によりを掛けてもっと作りますね！
241 = "それじゃ、腕によりを掛けてもっと作りますね！"

# カズマ
# おう！　いくらでも食べてやるぞ！
233 = "おう！　いくらでも食べてやるぞ！"

# ウィズ
# それじゃ、次の料理、お出ししますね～。
240 = "それじゃ、次の料理、お出ししますね～。"

# カズマ
# お、おう、まだあるんだ。
232 = "お、おう、まだあるんだ。"

# ウィズ
# はい、まだまだたくさんありますよ。\nおかわりこそないですけど、その分、\nいろんな料理を用意してありますから。
247 = "はい、まだまだたくさんありますよ。\\nおかわりこそないですけど、その分、\\nいろんな料理を用意してありますから。"

# カズマ
# そ、そうなんだ。\nでも、そろそろ限界が……。
238 = "そ、そうなんだ。\\nでも、そろそろ限界が……。"

# カズマ
# う、うっぷ。\nま、待った、ウィズ……。\nも、もう、俺、これ以上は入らないんだけど。
225 = "う、うっぷ。\\nま、待った、ウィズ……。\\nも、もう、俺、これ以上は入らないんだけど。"

# ウィズ
# さあ、次のは今回の目玉なんです！\nなんと、ドラゴンの肉なんですよ！　滅多に手に\n入らない、激レアな食材です！！
237 = "さあ、次のは今回の目玉なんです！\\nなんと、ドラゴンの肉なんですよ！　滅多に手に\\n入らない、激レアな食材です！！"

# カズマ
# は、話を聞いてくれ。
245 = "は、話を聞いてくれ。"

# カズマ（Ｍ）
# display as カズマ
# （全然、出てくる料理が止まる気配が無いぞ！？\n　もう、胃袋のどこにもこれ以上入る隙間が無いん\n　ですけど！？）
301 = "（全然、出てくる料理が止まる気配が無いぞ！？\\n　もう、胃袋のどこにもこれ以上入る隙間が無いん\\n　ですけど！？）"

# ウィズ
# ほらほらカズマさん、まだ手をつけてないお皿が\nあるじゃないですか。全部自信作ですから、\nぜひ食べて下さい！
250 = "ほらほらカズマさん、まだ手をつけてないお皿が\\nあるじゃないですか。全部自信作ですから、\\nぜひ食べて下さい！"

# カズマ
# こ、これ全部とか、もう勘弁して……。
234 = "こ、これ全部とか、もう勘弁して……。"

# ウィズ
# ふふ、こんな料理のし甲斐があるの、初めてです！\n誰かに自分の料理を食べてもらえるのって、\nこんなに幸せなことだったんですね～！
248 = "ふふ、こんな料理のし甲斐があるの、初めてです！\\n誰かに自分の料理を食べてもらえるのって、\\nこんなに幸せなことだったんですね～！"

# カズマ
# お、おう……うぷっ！
231 = "お、おう……うぷっ！"

# カズマ（Ｍ）
# display as カズマ
# （美味しい料理と嬉しそうなウィズを見るのはいいん\n　だけど……俺にとっちゃ、拷問以外の何もんでも\n　ない……）
302 = "（美味しい料理と嬉しそうなウィズを見るのはいいん\\n　だけど……俺にとっちゃ、拷問以外の何もんでも\\n　ない……）"

# カズマ（Ｍ）
# display as カズマ
# （……死ぬかな、俺）
297 = "（……死ぬかな、俺）"

[selections]
223 = "いいお嫁さんになれそうだな"
263 = "俺のメイドにならないか？"
252 = "もしかしてこれはプロポーズ！？"
