# rew_e09.txt.scn

[info]
197 = "rew_e09"

[characters]
297 = "ゆんゆん"
303 = "カズマ"
305 = "カズマ（Ｍ）"

[character_subs]
# 303 = "カズマ"

[script]
# lines: 90

# ゆんゆん
# あ、あのぉ、お仕置きの内容なんですけど。\n本を読んでほしいというのはどうでしょうか？
247 = "あ、あのぉ、お仕置きの内容なんですけど。\\n本を読んでほしいというのはどうでしょうか？"

# カズマ
# 構わないけどなんの本だ？\nまさか、とてつもないページ数の本なのか！？
318 = "構わないけどなんの本だ？\\nまさか、とてつもないページ数の本なのか！？"

# ゆんゆん
# いいえ、１、２時間で読み終わる程度の厚さです。
257 = "いいえ、１、２時間で読み終わる程度の厚さです。"

# カズマ（Ｍ）
# display as カズマ
# （それなら問題ないか、\n　そもそもお仕置きなんだから、\n　分厚い本でも文句は言えないんだが）
377 = "（それなら問題ないか、\\n　そもそもお仕置きなんだから、\\n　分厚い本でも文句は言えないんだが）"

# カズマ
# で、どんな本なんだ？
279 = "で、どんな本なんだ？"

# ゆんゆん
# あの、これです！
250 = "あの、これです！"

# カズマ
# へえ、ずいぶん可愛らしい装丁の本だな。
292 = "へえ、ずいぶん可愛らしい装丁の本だな。"

# ゆんゆん
# この本に、友達を作る秘訣が書かれている\nらしいんです！
265 = "この本に、友達を作る秘訣が書かれている\\nらしいんです！"

# ゆんゆん
# これさえ読破すれば、もう独りぼっちで寂しい思いを\nする必要も……って思ったのですが。
266 = "これさえ読破すれば、もう独りぼっちで寂しい思いを\\nする必要も……って思ったのですが。"

# カズマ
# うん、どうかしたのか？
260 = "うん、どうかしたのか？"

# ゆんゆん
# その秘訣というのがよくわからなくて。
271 = "その秘訣というのがよくわからなくて。"

# カズマ
# なるほど読解できなかったと。
284 = "なるほど読解できなかったと。"

# ゆんゆん
# はい、ですからカズマさんに読んでいただいて、\nその秘訣部分を教えて貰えたらなと。
290 = "はい、ですからカズマさんに読んでいただいて、\\nその秘訣部分を教えて貰えたらなと。"

# カズマ
# わかった。\nじゃああとで感想を言いにいくよ。
301 = "わかった。\\nじゃああとで感想を言いにいくよ。"

# ゆんゆん
# あっ、いえ、読んで欲しいというのは、\n私の前でという意味なんです！
249 = "あっ、いえ、読んで欲しいというのは、\\n私の前でという意味なんです！"

# カズマ
# ああ、構わないぞ。\nでも待ってるだけってのは暇だろ。
248 = "ああ、構わないぞ。\\nでも待ってるだけってのは暇だろ。"

# ゆんゆん
# あの、ですから、声に出して読んで欲しいなと。
252 = "あの、ですから、声に出して読んで欲しいなと。"

# カズマ
# つまり朗読？
278 = "つまり朗読？"

# ゆんゆん
# は、はい、めぐみんがそうした方が良いと。
286 = "は、はい、めぐみんがそうした方が良いと。"

# ゆんゆん
# 読むだけと耳で聞くとでは、受け取れる情報が\n違うって。
363 = "読むだけと耳で聞くとでは、受け取れる情報が\\n違うって。"

# カズマ
# まあ、確かにめぐみんの言うとおりだとは思うけど。
293 = "まあ、確かにめぐみんの言うとおりだとは思うけど。"

# カズマ（Ｍ）
# display as カズマ
# （この可愛らしい装丁は、もう嫌な予感しかしない）
373 = "（この可愛らしい装丁は、もう嫌な予感しかしない）"

# カズマ（Ｍ）
# display as カズマ
# （それがめぐみんの狙いなんだろうけど）
376 = "（それがめぐみんの狙いなんだろうけど）"

# ゆんゆん
# あ、あの、お願いできますか？
245 = "あ、あの、お願いできますか？"

# カズマ
# あ、ああ、お仕置きに拒否権はないしな。
244 = "あ、ああ、お仕置きに拒否権はないしな。"

# カズマ（Ｍ）
# display as カズマ
# （くっそ、やっぱり恋愛小説だ！\n　しかもパラ見しただけなのに、\n　伝わってくるキラキラ感！）
372 = "（くっそ、やっぱり恋愛小説だ！\\n　しかもパラ見しただけなのに、\\n　伝わってくるキラキラ感！）"

# カズマ（Ｍ）
# display as カズマ
# （妙に甘ったるくて胸焼けを起こしそうだ、\n　マジかマジでこれを読めと？）
383 = "（妙に甘ったるくて胸焼けを起こしそうだ、\\n　マジかマジでこれを読めと？）"

# カズマ（Ｍ）
# display as カズマ
# （こんなの音読したら、\n　その瞬間恥ずかしさで死ぬ！\n　間違いなく死ぬ！　とんでもない劇薬だ！）
374 = "（こんなの音読したら、\\n　その瞬間恥ずかしさで死ぬ！\\n　間違いなく死ぬ！　とんでもない劇薬だ！）"

# ゆんゆん
# カズマさん？
304 = "カズマさん？"

# カズマ
# よ、よし、それじゃ読むぞ。
300 = "よ、よし、それじゃ読むぞ。"

# ゆんゆん
# は、はい！　よろしくお願いします！
288 = "は、はい！　よろしくお願いします！"

# カズマ（Ｍ）
# display as カズマ
# （なんて汚れのない瞳をするんだ。\n　なんとかこの試練を乗り切って生き残るぞ！）
379 = "（なんて汚れのない瞳をするんだ。\\n　なんとかこの試練を乗り切って生き残るぞ！）"

# カズマ
# 私はアンナ、\n貴族の家系に生まれた花も恥じらう１４歳の乙女。\n好きな食べ物は甘いケーキ。
361 = "私はアンナ、\\n貴族の家系に生まれた花も恥じらう１４歳の乙女。\\n好きな食べ物は甘いケーキ。"

# カズマ
# 最近ケーキの食べすぎで、\n少しお腹にお肉がついてきちゃって、\nそれが一番の悩みかな、エヘッ♪
317 = "最近ケーキの食べすぎで、\\n少しお腹にお肉がついてきちゃって、\\nそれが一番の悩みかな、エヘッ♪"

# ゆんゆん
# あの、ちょっといいですか？
251 = "あの、ちょっといいですか？"

# カズマ
# 何かな？
312 = "何かな？"

# ゆんゆん
# 読んでもらっておいて言いにくいのですが、\nもう少し感情を込めてくれますか？\nあ、す、すみません。
364 = "読んでもらっておいて言いにくいのですが、\\nもう少し感情を込めてくれますか？\\nあ、す、すみません。"

# カズマ（Ｍ）
# display as カズマ
# （感情を殺すことによって羞恥心を打ち消していた\n　俺には死の宣告だな！）
384 = "（感情を殺すことによって羞恥心を打ち消していた\\n　俺には死の宣告だな！）"

# カズマ
# え～と、それじゃ一緒に読まないか？
263 = "え～と、それじゃ一緒に読まないか？"

# ゆんゆん
# と、カズマさんが提案してきたら断れとめぐみんが。
280 = "と、カズマさんが提案してきたら断れとめぐみんが。"

# カズマ（Ｍ）
# display as カズマ
# （周到だな、おい！）
382 = "（周到だな、おい！）"

# カズマ
# いいか、ゆんゆん。\n自分にとって何が一番大切なのか考えてみるんだ。
259 = "いいか、ゆんゆん。\\n自分にとって何が一番大切なのか考えてみるんだ。"

# ゆんゆん
# 一番大切なのか……ですか？
310 = "一番大切なのか……ですか？"

# カズマ
# めぐみんに言われたとおりすることじゃ無くて、\n友達を作る方法を知ることなんじゃないのか？
294 = "めぐみんに言われたとおりすることじゃ無くて、\\n友達を作る方法を知ることなんじゃないのか？"

# ゆんゆん
# た、確かに！！
274 = "た、確かに！！"

# カズマ
# 耳から聞くのも確かに大切だ。\nでもやっぱり何度も繰り返して読むことで\nわかることっていうのがあると思うんだよ。
362 = "耳から聞くのも確かに大切だ。\\nでもやっぱり何度も繰り返して読むことで\\nわかることっていうのがあると思うんだよ。"

# ゆんゆん
# はい、私もそう思います！
291 = "はい、私もそう思います！"

# カズマ
# それとあれだ。\nこういうのはダラダラしても\n大した効果は得られないもんだ。
273 = "それとあれだ。\\nこういうのはダラダラしても\\n大した効果は得られないもんだ。"

# カズマ
# だから、ここだって所だけピックアップして\n読んだ方がいいと思うぞ！
275 = "だから、ここだって所だけピックアップして\\n読んだ方がいいと思うぞ！"

# ゆんゆん
# なるほど、勉強になります！
282 = "なるほど、勉強になります！"

# カズマ
# それで？\nここかなーって思うところはあるのか？
272 = "それで？\\nここかなーって思うところはあるのか？"

# ゆんゆん
# ええと、ここからなんですけど。
261 = "ええと、ここからなんですけど。"

# カズマ
# じゃあ、一緒に読んでみるか。
268 = "じゃあ、一緒に読んでみるか。"

# ゆんゆん
# どうしよう私には大好きな許嫁がいるのに、\n街でチンピラから助けてくれた\nあの冒険者のことが忘れられない。
281 = "どうしよう私には大好きな許嫁がいるのに、\\n街でチンピラから助けてくれた\\nあの冒険者のことが忘れられない。"

# ゆんゆん
# あの人のことを思い出すだけで、\nこの小さな胸がチクチク痛んじゃう。
253 = "あの人のことを思い出すだけで、\\nこの小さな胸がチクチク痛んじゃう。"

# ゆんゆん
# 同時に２人の人を好きになっちゃうなんて、\n胸が張り裂けそうでご飯も喉を通らないわ。
315 = "同時に２人の人を好きになっちゃうなんて、\\n胸が張り裂けそうでご飯も喉を通らないわ。"

# ゆんゆん
# バカバカ、私のバカ……。
307 = "バカバカ、私のバカ……。"

# カズマ（Ｍ）
# display as カズマ
# （薄々気付いてはいたが、\n　友達を作る秘訣なんてどこにも書いてないな、\n　これ）
385 = "（薄々気付いてはいたが、\\n　友達を作る秘訣なんてどこにも書いてないな、\\n　これ）"

# カズマ（Ｍ）
# display as カズマ
# （どっちかっていうと、\n　まだ恋人を作る系なんじゃ……、\n　いや、それもかなり怪しいけど！）
378 = "（どっちかっていうと、\\n　まだ恋人を作る系なんじゃ……、\\n　いや、それもかなり怪しいけど！）"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんめ、なぜこんなものを俺に読ませようと\n　したんだ）
380 = "（めぐみんめ、なぜこんなものを俺に読ませようと\\n　したんだ）"

# カズマ（Ｍ）
# display as カズマ
# （あいつは過度の爆裂狂だが、決してバカじゃ無い。\n　何も考え無しにこんなことを――）
365 = "（あいつは過度の爆裂狂だが、決してバカじゃ無い。\\n　何も考え無しにこんなことを――）"

# カズマ（Ｍ）
# display as カズマ
# （あっ、も、もしかして！\n　俺のことが好きなゆんゆんの背中を\n　そっと押している！）
366 = "（あっ、も、もしかして！\\n　俺のことが好きなゆんゆんの背中を\\n　そっと押している！）"

# カズマ（Ｍ）
# display as カズマ
# （いつまでも気持ちを伝えられない\n　ゆんゆんを見かねて、\n　こんな手段で取ったとか！！）
368 = "（いつまでも気持ちを伝えられない\\n　ゆんゆんを見かねて、\\n　こんな手段で取ったとか！！）"

# カズマ（Ｍ）
# display as カズマ
# （そう考えれば全てつじつまが合う！\n　ならばどうする、俺！）
375 = "（そう考えれば全てつじつまが合う！\\n　ならばどうする、俺！）"

# カズマ
# もっと感情を込めて読もう！\n俺に告白するつもりで！
296 = "もっと感情を込めて読もう！\\n俺に告白するつもりで！"

# ゆんゆん
# はい……え？\nカ、カズマさんに告白するつもりでですか？
289 = "はい……え？\\nカ、カズマさんに告白するつもりでですか？"

# カズマ
# だって、ゆんゆんは俺のことが好きなんだろ？
277 = "だって、ゆんゆんは俺のことが好きなんだろ？"

# ゆんゆん
# いいえ違います。まったく全然違いますよ？
258 = "いいえ違います。まったく全然違いますよ？"

# カズマ
# あー、違うんだ。\nしかも全然。
255 = "あー、違うんだ。\\nしかも全然。"

# カズマ（Ｍ）
# display as カズマ
# （うわー、めちゃくちゃ引いた顔してるし！）
369 = "（うわー、めちゃくちゃ引いた顔してるし！）"

# カズマ
# い、いや、あれなんだよ。\nそう思うくらいの感情移入した方がいいって\n意味だったんだ！
256 = "い、いや、あれなんだよ。\\nそう思うくらいの感情移入した方がいいって\\n意味だったんだ！"

# カズマ
# そうした方が、頭じゃ無くて心にもすっと\n入ってくると思うんだよね！
269 = "そうした方が、頭じゃ無くて心にもすっと\\n入ってくると思うんだよね！"

# ゆんゆん
# なるほど、確かにそうですね！
283 = "なるほど、確かにそうですね！"

# カズマ
# ゆんゆんの気持ちを受け入れよう。
298 = "ゆんゆんの気持ちを受け入れよう。"

# ゆんゆん
# なんですか、私の気持ちって？
285 = "なんですか、私の気持ちって？"

# カズマ
# ズバリ俺のことが好き！
306 = "ズバリ俺のことが好き！"

# ゆんゆん
# は、はい、好きですよ。\n大切なお友達ですから……。
287 = "は、はい、好きですよ。\\n大切なお友達ですから……。"

# カズマ
# 友達、友達ですか……、\nで、ですよね！
313 = "友達、友達ですか……、\\nで、ですよね！"

# カズマ（Ｍ）
# display as カズマ
# （か、か、肩を抱いてみよう！）
370 = "（か、か、肩を抱いてみよう！）"

# カズマ
# ゆんゆん！
299 = "ゆんゆん！"

# ゆんゆん
# あ、あの、カズマさん？\nど、どうして肩を？？
246 = "あ、あの、カズマさん？\\nど、どうして肩を？？"

# カズマ
# だって、そうなんだろう？
276 = "だって、そうなんだろう？"

# ゆんゆん
# え？　ええ？
262 = "え？　ええ？"

# カズマ（Ｍ）
# display as カズマ
# （あれ、何このドン引きの顔）
367 = "（あれ、何このドン引きの顔）"

# ゆんゆん
# カ、カ、カズマさん、離れていただけると。
302 = "カ、カ、カズマさん、離れていただけると。"

# カズマ
# あは、あはは、なんかくらっとしちゃってさ。
254 = "あは、あはは、なんかくらっとしちゃってさ。"

# カズマ
# ごめんな、つい抱くような形でゆんゆんに\n掴まっちゃったよ。
267 = "ごめんな、つい抱くような形でゆんゆんに\\n掴まっちゃったよ。"

# ゆんゆん
# そうだったんですか。
270 = "そうだったんですか。"

# カズマ（Ｍ）
# display as カズマ
# （くそぉ、なんて恥ずかしい勘違いを！）
371 = "（くそぉ、なんて恥ずかしい勘違いを！）"

# カズマ（Ｍ）
# display as カズマ
# （もう、穴があったら入りたい！）
381 = "（もう、穴があったら入りたい！）"

[selections]
295 = "もっと感情を込めて読もう！"
# 298 = "ゆんゆんの気持ちを受け入れよう。"
264 = "か、か、肩を抱いてみよう！"
