# rew_b04.txt.scn

[info]
262 = "rew_b04"

[characters]
359 = "カズマ"
348 = "めぐみん"
363 = "カズマ（Ｍ）"

[character_subs]
# 359 = "カズマ"

[script]
# lines: 121

# カズマ
# はぁ～～～……。
343 = "はぁ～～～……。"

# めぐみん
# なんですか、\nこれみよがしに溜息なんか吐いて。
339 = "なんですか、\\nこれみよがしに溜息なんか吐いて。"

# カズマ
# いやな、疲れがちっとも抜けないんだよ。
293 = "いやな、疲れがちっとも抜けないんだよ。"

# めぐみん
# 普段あんなにダラダラしておいて\nよく言いますね。
389 = "普段あんなにダラダラしておいて\\nよく言いますね。"

# カズマ
# 別にダラダラしてないだろ！\nそれに肉体的な疲れじゃなくて\n精神的なものなんだよ！
370 = "別にダラダラしてないだろ！\\nそれに肉体的な疲れじゃなくて\\n精神的なものなんだよ！"

# めぐみん
# ますます理解に苦しみますね。\nカズマの生活の中のどこにストレスが溜まる\n要因があるというのですか。
346 = "ますます理解に苦しみますね。\\nカズマの生活の中のどこにストレスが溜まる\\n要因があるというのですか。"

# めぐみん
# 毎日真面目にコツコツ働いているみなさんに\n謝ったらどうですか？
394 = "毎日真面目にコツコツ働いているみなさんに\\n謝ったらどうですか？"

# カズマ
# ストレスを感じる理由なんて\n挙げたらキリがないわ！
364 = "ストレスを感じる理由なんて\\n挙げたらキリがないわ！"

# カズマ
# 自分の胸に手を当てて考えてみろ。\n思い当たる節の１０や１００は\n出てくるはずだぞ。
444 = "自分の胸に手を当てて考えてみろ。\\n思い当たる節の１０や１００は\\n出てくるはずだぞ。"

# めぐみん
# まるで思い当たりませんね。
347 = "まるで思い当たりませんね。"

# めぐみん
# そういうカズマこそ自分の胸に\n手を当ててみたらどうです？
314 = "そういうカズマこそ自分の胸に\\n手を当ててみたらどうです？"

# めぐみん
# 私に対して、謝ることの\n１００や１０００は\n軽く思い当たるはずです。
440 = "私に対して、謝ることの\\n１００や１０００は\\n軽く思い当たるはずです。"

# カズマ
# そんなもんないわ！\nとにかく俺は疲れてるんだよ！
324 = "そんなもんないわ！\\nとにかく俺は疲れてるんだよ！"

# めぐみん
# で、なんですか私に\n愚痴を聞いて欲しいのですか？
327 = "で、なんですか私に\\n愚痴を聞いて欲しいのですか？"

# カズマ
# いや、ちょっと違うな。\n今の俺に必要なものは癒やしなんだ。\nよって、めぐみんには俺を癒やしてもらう！
290 = "いや、ちょっと違うな。\\n今の俺に必要なものは癒やしなんだ。\\nよって、めぐみんには俺を癒やしてもらう！"

# めぐみん
# 肩でも揉めと言うんですか？
443 = "肩でも揉めと言うんですか？"

# カズマ
# それも悪くはないが、\n揉みほぐして欲しいのは\n肩じゃなくて心の方だ。
321 = "それも悪くはないが、\\n揉みほぐして欲しいのは\\n肩じゃなくて心の方だ。"

# めぐみん
# 難解なことを言い出しますね。\nどうやって心を揉めと言うんですか？
448 = "難解なことを言い出しますね。\\nどうやって心を揉めと言うんですか？"

# カズマ
# 簡単なことだよ。\nこの紙に書いてあることを読んでくれればいい、\nそれが今回のご褒美ってわけだ。
441 = "簡単なことだよ。\\nこの紙に書いてあることを読んでくれればいい、\\nそれが今回のご褒美ってわけだ。"

# めぐみん
# おかしなことが\n書いてあるんじゃないでしょうね。
306 = "おかしなことが\\n書いてあるんじゃないでしょうね。"

# カズマ
# 失礼な！\n今の俺に必要な言葉が書いてあるだけだよ。
375 = "失礼な！\\n今の俺に必要な言葉が書いてあるだけだよ。"

# めぐみん
# とりあえず拝見させてもらいます。\nえ～と――
330 = "とりあえず拝見させてもらいます。\\nえ～と――"

# めぐみん
# うぐ、これはなかなか来ますね……。
296 = "うぐ、これはなかなか来ますね……。"

# カズマ
# それは俺も十分理解してるけど、\n疲弊しきった俺の心には、めぐみんのその言葉が\n必要なんだよ。
320 = "それは俺も十分理解してるけど、\\n疲弊しきった俺の心には、めぐみんのその言葉が\\n必要なんだよ。"

# めぐみん
# うぅ、ですが、これは恥ずかしすぎます。
294 = "うぅ、ですが、これは恥ずかしすぎます。"

# カズマ
# 俺を助けると思って頼む。\nそれともお前は、\n心からの頼みを断るのか？
369 = "俺を助けると思って頼む。\\nそれともお前は、\\n心からの頼みを断るのか？"

# カズマ
# いや、めぐみんに限って\nそんな人でなしな真似はしないよな？
291 = "いや、めぐみんに限って\\nそんな人でなしな真似はしないよな？"

# カズマ
# もちろん俺は信じてるとも！\nめぐみんは心優しい女の子だってな。
353 = "もちろん俺は信じてるとも！\\nめぐみんは心優しい女の子だってな。"

# めぐみん
# はぁ～、わかりました。わかりましたよ。\n読めばいいのでしょう、読めば。
342 = "はぁ～、わかりました。わかりましたよ。\\n読めばいいのでしょう、読めば。"

# カズマ
# 耳元で囁きながらな。
442 = "耳元で囁きながらな。"

# めぐみん
# なっ！\nそれは必要なことなんですか？
335 = "なっ！\\nそれは必要なことなんですか？"

# カズマ
# もちろんだ！\nそこが最大のポイントなんだからな！
352 = "もちろんだ！\\nそこが最大のポイントなんだからな！"

# めぐみん
# なるほど、全てを理解しました。\nカズマは私を殺したいんですね。
338 = "なるほど、全てを理解しました。\\nカズマは私を殺したいんですね。"

# カズマ
# そこまで嫌なのかよ。
318 = "そこまで嫌なのかよ。"

# めぐみん
# 嫌です。
376 = "嫌です。"

# カズマ
# 頭を下げてもダメ？
450 = "頭を下げてもダメ？"

# めぐみん
# そういうのは、価値がある人間がやるからこそ\n意味があるのですよ。
313 = "そういうのは、価値がある人間がやるからこそ\\n意味があるのですよ。"

# カズマ（Ｍ）
# display as カズマ
# （くっそっ！）
453 = "（くっそっ！）"

# めぐみん
# とにかく嫌な物は嫌なんです。\nこの紙に書かれた内容を読むだけで満足して\nください。
329 = "とにかく嫌な物は嫌なんです。\\nこの紙に書かれた内容を読むだけで満足して\\nください。"

# カズマ
# そんなささやかな願いも叶えてもらえない\nなんて……。
323 = "そんなささやかな願いも叶えてもらえない\\nなんて……。"

# カズマ
# めぐみんに１０００回以上も\n謝らなきゃいけないことしてるみたいだし\n仕方がないよな。
349 = "めぐみんに１０００回以上も\\n謝らなきゃいけないことしてるみたいだし\\n仕方がないよな。"

# カズマ
# 実は気付いていないだけで傷つけてたんだな。\nそりゃ嫌われても文句も言えない。
378 = "実は気付いていないだけで傷つけてたんだな。\\nそりゃ嫌われても文句も言えない。"

# めぐみん
# い、いえ、そういうわけでは……。
288 = "い、いえ、そういうわけでは……。"

# カズマ
# 俺ってダメなやつだったんだな。\nこれからは日陰を選んで歩くよ。\n悪かったな、めぐみん。
368 = "俺ってダメなやつだったんだな。\\nこれからは日陰を選んで歩くよ。\\n悪かったな、めぐみん。"

# めぐみん
# あー、もう！\nわかりました。\nやればいいんでしょ、やれば！
287 = "あー、もう！\\nわかりました。\\nやればいいんでしょ、やれば！"

# カズマ
# いや、いいよ。\n無理にしてもらっても申し訳ないし。
289 = "いや、いいよ。\\n無理にしてもらっても申し訳ないし。"

# めぐみん
# くっ……無理にじゃないです！\n私がそうしたいんです！
309 = "くっ……無理にじゃないです！\\n私がそうしたいんです！"

# カズマ
# 本当に？　それじゃお願いしちゃおうかな！
391 = "本当に？　それじゃお願いしちゃおうかな！"

# めぐみん
# やれやれ……ではいきますよ。
356 = "やれやれ……ではいきますよ。"

# カズマ
# おう！
305 = "おう！"

# めぐみん
# カズマはイケメンですね。\nその上頭もよく度胸もある。
362 = "カズマはイケメンですね。\\nその上頭もよく度胸もある。"

# めぐみん
# おまけに包容力も兼ね備え、\nまさに完璧な存在です。
307 = "おまけに包容力も兼ね備え、\\nまさに完璧な存在です。"

# カズマ
# 待て待て、ちょっとストップ！
381 = "待て待て、ちょっとストップ！"

# めぐみん
# どうしたんですか、\nなぜ止めるのです？
332 = "どうしたんですか、\\nなぜ止めるのです？"

# カズマ
# うーんと、一体どうしちゃったのかな、めぐみん？
298 = "うーんと、一体どうしちゃったのかな、めぐみん？"

# めぐみん
# 何がです？\nまるで私に問題があるかのような\n口ぶりですね。
367 = "何がです？\\nまるで私に問題があるかのような\\n口ぶりですね。"

# カズマ
# どう考えたってあるだろう！
333 = "どう考えたってあるだろう！"

# めぐみん
# どこにあるというのです。\n読み違いもなくきちんと\n読んでいるではありませんか。
334 = "どこにあるというのです。\\n読み違いもなくきちんと\\n読んでいるではありませんか。"

# カズマ
# 本気か？\n本気で問題がないと思ってるのか？
392 = "本気か？\\n本気で問題がないと思ってるのか？"

# めぐみん
# 面倒くさいですね。\n言いたいことがあるならハッキリ言ってください。
449 = "面倒くさいですね。\\n言いたいことがあるならハッキリ言ってください。"

# カズマ
# なら言わせてもらおう――
337 = "なら言わせてもらおう――"

# カズマ
# もっと真面目にやってくれ。
355 = "もっと真面目にやってくれ。"

# めぐみん
# ほぉ、私が手を抜いているとでも？
344 = "ほぉ、私が手を抜いているとでも？"

# カズマ
# 明らかに抜いてるだろ！\nどうした？　どこかに感情を忘れてきたのか？\nなぜ棒読みなんだ？
388 = "明らかに抜いてるだろ！\\nどうした？　どこかに感情を忘れてきたのか？\\nなぜ棒読みなんだ？"

# めぐみん
# 心にもないことを口にしているんですから\n仕方がないじゃないですか。\n心に嘘はつけません。
383 = "心にもないことを口にしているんですから\\n仕方がないじゃないですか。\\n心に嘘はつけません。"

# カズマ
# え、ええと、まったく思ってないってことはない\nよな？　少しは思ってくれてるんだろ？
300 = "え、ええと、まったく思ってないってことはない\\nよな？　少しは思ってくれてるんだろ？"

# めぐみん
# 残念ながらこれっぽっちも思ってませんね。
393 = "残念ながらこれっぽっちも思ってませんね。"

# めぐみん
# カズマはもう少し自分を知るべきです。\nいくら嘘の言葉を並べてみても\nあなたの価値は上がりませんよ？
361 = "カズマはもう少し自分を知るべきです。\\nいくら嘘の言葉を並べてみても\\nあなたの価値は上がりませんよ？"

# カズマ
# おいおい、これは俺へのご褒美なんだぞ！
304 = "おいおい、これは俺へのご褒美なんだぞ！"

# カズマ
# それなのに、心に消えない傷をつけるようなことを\n言うな！
319 = "それなのに、心に消えない傷をつけるようなことを\\n言うな！"

# カズマ
# そろそろ本気で泣くからな！
322 = "そろそろ本気で泣くからな！"

# めぐみん
# はぁ、わかりましたよ。\n感情を込めれば良いのでしょう、感情を。
341 = "はぁ、わかりましたよ。\\n感情を込めれば良いのでしょう、感情を。"

# カズマ
# ああ、思いっきり可愛らしく頼むな！
284 = "ああ、思いっきり可愛らしく頼むな！"

# めぐみん
# 可愛らしく、可愛らしく……。
373 = "可愛らしく、可愛らしく……。"

# カズマ
# めぐみんの本心も交えてくれ。
351 = "めぐみんの本心も交えてくれ。"

# めぐみん
# どういう意味ですか？
331 = "どういう意味ですか？"

# カズマ
# さっきから聞いてりゃ\n棒読みもいいところじゃないか。
311 = "さっきから聞いてりゃ\\n棒読みもいいところじゃないか。"

# めぐみん
# 心にもないことを言わされているのですから\n無理もありません。
384 = "心にもないことを言わされているのですから\\n無理もありません。"

# カズマ
# そうだろうと思ったよ。\nだから書かれていることを読むだけじゃなくて、\nめぐみんの本心も織り交ぜてくれ。
316 = "そうだろうと思ったよ。\\nだから書かれていることを読むだけじゃなくて、\\nめぐみんの本心も織り交ぜてくれ。"

# カズマ
# あるだろ。\n心に秘めている俺への熱い思いが！
286 = "あるだろ。\\n心に秘めている俺への熱い思いが！"

# めぐみん
# 熱い思い……ですか？
395 = "熱い思い……ですか？"

# カズマ
# そうそう、こんなポンコツの自分に\nいつもよくしてありがとうございますとか。
315 = "そうそう、こんなポンコツの自分に\\nいつもよくしてありがとうございますとか。"

# カズマ
# 常識知らずで迷惑ばかりおかけしています。\nこれからはカズマさんのご迷惑にならないように\n努めます、とかあるだろ。
380 = "常識知らずで迷惑ばかりおかけしています。\\nこれからはカズマさんのご迷惑にならないように\\n努めます、とかあるだろ。"

# めぐみん
# 言いたいことはそれだけですか？
446 = "言いたいことはそれだけですか？"

# めぐみん
# なら今度は私が、\n今、心から言いたい言葉を贈らせて頂きます。
336 = "なら今度は私が、\\n今、心から言いたい言葉を贈らせて頂きます。"

# カズマ
# お、そうこなくっちゃ。
303 = "お、そうこなくっちゃ。"

# めぐみん
# 黒より黒く、闇より昏き漆黒に\n我が真紅の混淆を望みたもう。
451 = "黒より黒く、闇より昏き漆黒に\\n我が真紅の混淆を望みたもう。"

# めぐみん
# 覚醒の時、来たれり。\n無謬の境界に堕ちし理――
445 = "覚醒の時、来たれり。\\n無謬の境界に堕ちし理――"

# カズマ
# 待て待て待てーーー！！\n何をしてるんだ！？
382 = "待て待て待てーーー！！\\n何をしてるんだ！？"

# めぐみん
# くっくっくっ、ですからカズマの\n願いを叶えてあげるのですよ。
310 = "くっくっくっ、ですからカズマの\\n願いを叶えてあげるのですよ。"

# カズマ
# 悪かったー！\n俺が悪かったーーー！！
385 = "悪かったー！\\n俺が悪かったーーー！！"

# カズマ
# 可愛らしい吐息を交えながら言ってくれ。
372 = "可愛らしい吐息を交えながら言ってくれ。"

# カズマ
# さっきから聞いてりゃ\n棒読みもいいところじゃないか。
# 311 = "さっきから聞いてりゃ\\n棒読みもいいところじゃないか。"

# めぐみん
# 心にもないことを言わされているのですから\n無理もありません。
# 384 = "心にもないことを言わされているのですから\\n無理もありません。"

# カズマ
# だから少しでも雰囲気を出すために\n吐息混じりで頼む！
325 = "だから少しでも雰囲気を出すために\\n吐息混じりで頼む！"

# めぐみん
# 嫌ですよ。\nそんな恥ずかしい真似できません！
377 = "嫌ですよ。\\nそんな恥ずかしい真似できません！"

# カズマ
# そう言いながらも今度もまた折れてくれるんだろ？\nめぐみんはチョロ――優しいからな！
317 = "そう言いながらも今度もまた折れてくれるんだろ？\\nめぐみんはチョロ――優しいからな！"

# めぐみん
# 今なにか言いかけて\n訂正しませんでしたか？
366 = "今なにか言いかけて\\n訂正しませんでしたか？"

# カズマ
# し、してないけど？
312 = "し、してないけど？"

# めぐみん
# 疑わしいです……。
396 = "疑わしいです……。"

# カズマ
# と、とにかく頼むよ、めぐみん！\nお前が持つ可愛らしさを全力で発揮してくれ！
328 = "と、とにかく頼むよ、めぐみん！\\nお前が持つ可愛らしさを全力で発揮してくれ！"

# めぐみん
# はぁ……わかりましたよ。\nそこまで言うのなら、叶えてあげましょう。
340 = "はぁ……わかりましたよ。\\nそこまで言うのなら、叶えてあげましょう。"

# めぐみん
# カ、カズマはイケメンですね。\nその上、頭もよく度胸もある。
358 = "カ、カズマはイケメンですね。\\nその上、頭もよく度胸もある。"

# カズマ
# えー、そうかなー？
302 = "えー、そうかなー？"

# めぐみん
# おまけに包容力も兼ね備え、\nまさに完璧な存在です。
# 307 = "おまけに包容力も兼ね備え、\\nまさに完璧な存在です。"

# カズマ
# いやいや、そんなことないってー。
292 = "いやいや、そんなことないってー。"

# めぐみん
# カズマ、私と出会ってくれてありがとう。
360 = "カズマ、私と出会ってくれてありがとう。"

# めぐみん
# あの日、あなたと出会ったあの瞬間から、\n私はカズマのために生きて行こうと決めました。
285 = "あの日、あなたと出会ったあの瞬間から、\\n私はカズマのために生きて行こうと決めました。"

# カズマ
# うんうん、それでそれで？
297 = "うんうん、それでそれで？"

# めぐみん
# え、ええと、それで、あの。
299 = "え、ええと、それで、あの。"

# カズマ
# ほーら、早く言ってぇー。
345 = "ほーら、早く言ってぇー。"

# めぐみん
# うぐ、うぐぐ。
295 = "うぐ、うぐぐ。"

# カズマ
# 早く、早くー。
387 = "早く、早くー。"

# めぐみん
# く、黒より黒く、闇より昏き漆黒に……。
308 = "く、黒より黒く、闇より昏き漆黒に……。"

# カズマ（Ｍ）
# display as カズマ
# （え？）
452 = "（え？）"

# めぐみん
# 我が真紅の混淆を望みたもう。
386 = "我が真紅の混淆を望みたもう。"

# カズマ
# って、何詠唱してんだよ！
326 = "って、何詠唱してんだよ！"

# めぐみん
# 詠唱ってなんです？\n気のせいじゃないですか？
447 = "詠唱ってなんです？\\n気のせいじゃないですか？"

# カズマ
# わかった、もう充分だから！\nあ、ありがとうな、めぐみん！
357 = "わかった、もう充分だから！\\nあ、ありがとうな、めぐみん！"

# めぐみん
# えー、せっかくですし、\n最後まで聞いてくださいよ！
301 = "えー、せっかくですし、\\n最後まで聞いてくださいよ！"

# カズマ
# 本当にもう良いから！
390 = "本当にもう良いから！"

[selections]
354 = "もっと真面目にやってくれ"
350 = "めぐみんの本心も交えてくれ"
371 = "可愛らしい吐息を交えながら言ってくれ"
