# rew_b10.txt.scn

[info]
210 = "rew_b10"

[characters]
278 = "めぐみん"
288 = "カズマ"
290 = "カズマ（Ｍ）"

[character_subs]
# 288 = "カズマ"

[script]
# lines: 76

# めぐみん
# さあ、楽しいお仕置きの時間ですよ。\nカズマ！
249 = "さあ、楽しいお仕置きの時間ですよ。\\nカズマ！"

# カズマ
# お仕置きを楽しみにするような\n趣味はない！
239 = "お仕置きを楽しみにするような\\n趣味はない！"

# めぐみん
# そう言いながら密かに期待しているのでは\nありませんか？
256 = "そう言いながら密かに期待しているのでは\\nありませんか？"

# カズマ
# するか！
252 = "するか！"

# めぐみん
# まあまあ、そう言わず\nどうせするなら楽しんだ方が得じゃないですか。
273 = "まあまあ、そう言わず\\nどうせするなら楽しんだ方が得じゃないですか。"

# カズマ
# まったくそう思わん。
276 = "まったくそう思わん。"

# めぐみん
# やれやれ、カズマも頑ですね。
282 = "やれやれ、カズマも頑ですね。"

# カズマ
# それで今回のお仕置きはなんなんだよ。
259 = "それで今回のお仕置きはなんなんだよ。"

# めぐみん
# ずばり、壁ドンです！
253 = "ずばり、壁ドンです！"

# カズマ
# 断る！
302 = "断る！"

# めぐみん
# 即答ですか。
296 = "即答ですか。"

# カズマ（Ｍ）
# display as カズマ
# （なにを言い出すのかと思えば、\n　よりにもよって壁ドンだと！？）
336 = "（なにを言い出すのかと思えば、\\n　よりにもよって壁ドンだと！？）"

# カズマ（Ｍ）
# display as カズマ
# （あれはイケメンにのみ許された特権だ。\n　どの面下げて俺ができる？\n　恥ずかしすぎるだろ！）
332 = "（あれはイケメンにのみ許された特権だ。\\n　どの面下げて俺ができる？\\n　恥ずかしすぎるだろ！）"

# めぐみん
# そんな、なめくじを素足で踏んだような顔を\nするほど嫌なのですか？
260 = "そんな、なめくじを素足で踏んだような顔を\\nするほど嫌なのですか？"

# カズマ
# お前は、遠回しに人の顔をディスるなよ。
241 = "お前は、遠回しに人の顔をディスるなよ。"

# めぐみん
# 私は、カズマが本気で嫌がっていることを\nさせるつもりはありません。
326 = "私は、カズマが本気で嫌がっていることを\\nさせるつもりはありません。"

# めぐみん
# 見くびらないでください、\n私はそんな人でなしではありませんから！
328 = "見くびらないでください、\\n私はそんな人でなしではありませんから！"

# カズマ
# めぐみん……。
279 = "めぐみん……。"

# めぐみん
# ですが、壁ドンはしてもらいますよ。
265 = "ですが、壁ドンはしてもらいますよ。"

# カズマ
# 言ってることが違いますよね！？
329 = "言ってることが違いますよね！？"

# めぐみん
# 純粋に嫌がっていることなら強要はしません。
327 = "純粋に嫌がっていることなら強要はしません。"

# めぐみん
# しかしカズマの反応を見る限り、\n恥ずかしがっているだけのようですからね。
251 = "しかしカズマの反応を見る限り、\\n恥ずかしがっているだけのようですからね。"

# カズマ
# 恥ずかしいから嫌がってるんだろ！
301 = "恥ずかしいから嫌がってるんだろ！"

# めぐみん
# わかっていませんね。\nカズマの恥ずかしがっている姿を見たいのですよ。
285 = "わかっていませんね。\\nカズマの恥ずかしがっている姿を見たいのですよ。"

# カズマ
# お前、アクアに似てきたな……。
240 = "お前、アクアに似てきたな……。"

# めぐみん
# けど、わかりませんね。\n壁にぶつかることの何が恥ずかしいのです？
243 = "けど、わかりませんね。\\n壁にぶつかることの何が恥ずかしいのです？"

# めぐみん
# まさか壁にぶつかることによって\n快楽を感じる変態なのですか！？
275 = "まさか壁にぶつかることによって\\n快楽を感じる変態なのですか！？"

# めぐみん
# 気持ち悪い！　さすがにそれは引きますよ！
303 = "気持ち悪い！　さすがにそれは引きますよ！"

# カズマ
# ちょっと待て！\nまさかお前、壁ドンが何かわかってないのか？
264 = "ちょっと待て！\\nまさかお前、壁ドンが何かわかってないのか？"

# めぐみん
# 壁にぶつかることを言うのではないんですか？
298 = "壁にぶつかることを言うのではないんですか？"

# カズマ
# 全然ちがーう！\nてか、そもそもそんな知識どこから仕入れた！
295 = "全然ちがーう！\\nてか、そもそもそんな知識どこから仕入れた！"

# めぐみん
# アクアが助言してくれたんですよ。\nカズマなら壁ドンがいいお仕置きになるって。
286 = "アクアが助言してくれたんですよ。\\nカズマなら壁ドンがいいお仕置きになるって。"

# カズマ（Ｍ）
# display as カズマ
# （あいつっ……）
331 = "（あいつっ……）"

# めぐみん
# それで、本当の壁ドンとは\n一体どういったものなのですか？
258 = "それで、本当の壁ドンとは\\n一体どういったものなのですか？"

# めぐみん
# カズマがそこまで恥ずかしがるものとは、\nますます興味が湧いてきました。\nぜひ壁ドンをしてください！
289 = "カズマがそこまで恥ずかしがるものとは、\\nますます興味が湧いてきました。\\nぜひ壁ドンをしてください！"

# めぐみん
# これはお仕置きなんですから\nカズマには拒否権はありませんよ。
247 = "これはお仕置きなんですから\\nカズマには拒否権はありませんよ。"

# カズマ
# よーし、わかった！\nそこまで言うならやってやる！
284 = "よーし、わかった！\\nそこまで言うならやってやる！"

# めぐみん
# おー、それでこそカズマ！\nさあ、私に壁ドンを披露するのです！
238 = "おー、それでこそカズマ！\\nさあ、私に壁ドンを披露するのです！"

# カズマ
# これが本当の壁ドンだ！
246 = "これが本当の壁ドンだ！"

# めぐみん
# き、急になにをするんです？\nビックリするじゃありませんか！
242 = "き、急になにをするんです？\\nビックリするじゃありませんか！"

# カズマ
# やれと言うからやっただけだ。\n文句を言われるなんて心外だな。
281 = "やれと言うからやっただけだ。\\n文句を言われるなんて心外だな。"

# めぐみん
# これが壁ドンなのですか？
245 = "これが壁ドンなのですか？"

# カズマ
# そうだ、この状況で相手を見つめながら\n愛を囁いたりするのが壁ドンだ。
254 = "そうだ、この状況で相手を見つめながら\\n愛を囁いたりするのが壁ドンだ。"

# めぐみん
# なるほど……、\n確かにカズマには似合いませんね。
270 = "なるほど……、\\n確かにカズマには似合いませんね。"

# カズマ
# そんなことは言われなくてもわかってるよ！
261 = "そんなことは言われなくてもわかってるよ！"

# カズマ（Ｍ）
# display as カズマ
# （このまま終わらせたんじゃ\n　悔しさが残るだけだ）
334 = "（このまま終わらせたんじゃ\\n　悔しさが残るだけだ）"

# カズマ（Ｍ）
# display as カズマ
# （なんとかして反撃をしてやりたい！\n　どうしてやろう――）
337 = "（なんとかして反撃をしてやりたい！\\n　どうしてやろう――）"

# カズマ（Ｍ）
# display as カズマ
# （こうなったら\n　ゆっくりと顔を近づけてやろう）
333 = "（こうなったら\\n　ゆっくりと顔を近づけてやろう）"

# めぐみん
# ちょ……な、何をしているのですか？
262 = "ちょ……な、何をしているのですか？"

# カズマ
# 何って正しい壁ドンの有効活用だ。
292 = "何って正しい壁ドンの有効活用だ。"

# めぐみん
# 近い近い、顔が近いですって！
330 = "近い近い、顔が近いですって！"

# カズマ
# 何を照れてるんだ。\n壁ドンをして欲しかったんだろ？
293 = "何を照れてるんだ。\\n壁ドンをして欲しかったんだろ？"

# めぐみん
# お、おお、おかしいですよ！\nなんだかカズマらしくありません！
237 = "お、おお、おかしいですよ！\\nなんだかカズマらしくありません！"

# カズマ
# 確かに俺らしくない。\nしかし、これが壁ドンの作法というものだ。
325 = "確かに俺らしくない。\\nしかし、これが壁ドンの作法というものだ。"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんにも恥ずかしい思いを\n　させてやろう）
338 = "（めぐみんにも恥ずかしい思いを\\n　させてやろう）"

# カズマ
# なあ、めぐみん。\nお前……太っただろ？
269 = "なあ、めぐみん。\\nお前……太っただろ？"

# めぐみん
# し、失礼な！\n太ってなどいません！
250 = "し、失礼な！\\n太ってなどいません！"

# カズマ
# それじゃ、このほっぺたはなんだ？
257 = "それじゃ、このほっぺたはなんだ？"

# めぐみん
# ちょ、ちょっとほっぺたを\n引っ張らないでください！
263 = "ちょ、ちょっとほっぺたを\\n引っ張らないでください！"

# カズマ
# こんなにぷるんぷるんじゃないか、\nほれほれ、ぷるんぷるん。
248 = "こんなにぷるんぷるんじゃないか、\\nほれほれ、ぷるんぷるん。"

# めぐみん
# 太ってない！　太ってませんからね！
299 = "太ってない！　太ってませんからね！"

# カズマ
# あ～、柔らかい。
236 = "あ～、柔らかい。"

# カズマ（Ｍ）
# display as カズマ
# （こんな機会もう二度とないだろうしな、\n　リア充気分を堪能させて貰おう）
335 = "（こんな機会もう二度とないだろうしな、\\n　リア充気分を堪能させて貰おう）"

# カズマ（Ｍ）
# display as カズマ
# （やるからには本気で挑む！\n　俺はイケメン、俺はイケメン！\n　いざ！！）
339 = "（やるからには本気で挑む！\\n　俺はイケメン、俺はイケメン！\\n　いざ！！）"

# カズマ
# こうしてよく見ると可愛いな。
244 = "こうしてよく見ると可愛いな。"

# めぐみん
# な、なにを今更。\n私が可愛いのはわかりきったことでは\nありませんか。
267 = "な、なにを今更。\\n私が可愛いのはわかりきったことでは\\nありませんか。"

# カズマ
# ああ、そうだな。\nどうしてそんな当然のことに今まで\n気付かなかったんだろうな。
235 = "ああ、そうだな。\\nどうしてそんな当然のことに今まで\\n気付かなかったんだろうな。"

# めぐみん
# カ、カズマ？\nど、どうしたのです。\nおかしいですよ？
287 = "カ、カズマ？\\nど、どうしたのです。\\nおかしいですよ？"

# カズマ
# 俺をおかしくさせたのは、お前だ。\nお前の可愛さが俺を狂わせた。\nこの責任どうとってくれるんだ？
294 = "俺をおかしくさせたのは、お前だ。\\nお前の可愛さが俺を狂わせた。\\nこの責任どうとってくれるんだ？"

# めぐみん
# どうと言われましても。
266 = "どうと言われましても。"

# カズマ
# そうだ、一生俺の隣で\n責任をとり続けてもらおうかな。
255 = "そうだ、一生俺の隣で\\n責任をとり続けてもらおうかな。"

# めぐみん
# な、なんだというのです。\nカズマのくせに、やけに強気ではありませんか！
268 = "な、なんだというのです。\\nカズマのくせに、やけに強気ではありませんか！"

# めぐみん
# まさか、これが壁ドンの力！\n壁ドンは男を肉食に変える！？
274 = "まさか、これが壁ドンの力！\\n壁ドンは男を肉食に変える！？"

# めぐみん
# なんというか、たまにはこういうのも悪くは……。
271 = "なんというか、たまにはこういうのも悪くは……。"

# カズマ
# め、めぐみん？
277 = "め、めぐみん？"

# めぐみん
# ふふ、ふふふふ……。
272 = "ふふ、ふふふふ……。"

[selections]
283 = "ゆっくりと顔を近づけてやろう"
280 = "めぐみんにも恥ずかしい思いをさせてやろう"
291 = "リア充気分を堪能させて貰おう"
