# rew_f02.txt.scn

[info]
192 = "rew_f02"

[characters]
284 = "カズマ"
279 = "ウィズ"
285 = "カズマ（Ｍ）"

[character_subs]
# 284 = "カズマ"

[script]
# lines: 85

# カズマ
# 癒されたいです。
299 = "癒されたいです。"

# ウィズ
# それは、まあ、わかるのですが。
262 = "それは、まあ、わかるのですが。"

# ウィズ
# どうしてこんな格好なんですかぁ！？
266 = "どうしてこんな格好なんですかぁ！？"

# カズマ
# え、ご褒美だからだけど？
243 = "え、ご褒美だからだけど？"

# ウィズ
# うぅ……私、いったい何をされちゃうんでしょうか。
236 = "うぅ……私、いったい何をされちゃうんでしょうか。"

# カズマ（Ｍ）
# display as カズマ
# （ふぅむ、このナイスバディ、お色気、羞恥心と\n　三拍子揃ったウィズの水着姿を堪能するには一体\n　何がいいものか……）
320 = "（ふぅむ、このナイスバディ、お色気、羞恥心と\\n　三拍子揃ったウィズの水着姿を堪能するには一体\\n　何がいいものか……）"

# カズマ
# 時に、ウィズはどんなご褒美がしたい？
298 = "時に、ウィズはどんなご褒美がしたい？"

# ウィズ
# そ、その質問はなんか変な気がするんですが。
256 = "そ、その質問はなんか変な気がするんですが。"

# カズマ
# そうか？　これでも一応ウィズの意見を汲もうと\n精一杯の誠意を見せてるんだけど。
257 = "そうか？　これでも一応ウィズの意見を汲もうと\\n精一杯の誠意を見せてるんだけど。"

# ウィズ
# そんなこと言われても、何していいかなんて\nわかりません。
264 = "そんなこと言われても、何していいかなんて\\nわかりません。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、ウィズは本当にこういう初々しいところが\n　可愛らしいなぁ……）
315 = "（ああ、ウィズは本当にこういう初々しいところが\\n　可愛らしいなぁ……）"

# カズマ
# ウィズが決められないなら俺が決めるしか無いな。\nじゃ、膝枕をお願いします。
280 = "ウィズが決められないなら俺が決めるしか無いな。\\nじゃ、膝枕をお願いします。"

# ウィズ
# えっ、こ、この格好でですか！？
250 = "えっ、こ、この格好でですか！？"

# カズマ
# そして耳掃除をお願いします！
259 = "そして耳掃除をお願いします！"

# ウィズ
# う、ううう……はい。
235 = "う、ううう……はい。"

# カズマ
# ウィズの太ももは、張りがあるのに柔らかくて、\nすべすべで最高だ！
281 = "ウィズの太ももは、張りがあるのに柔らかくて、\\nすべすべで最高だ！"

# カズマ
# それにひんやりしてて、暑い今日みたいな日には\nちょうどいい！
261 = "それにひんやりしてて、暑い今日みたいな日には\\nちょうどいい！"

# ウィズ
# うぅ、うぅぅぅ～～～～。
237 = "うぅ、うぅぅぅ～～～～。"

# カズマ（Ｍ）
# display as カズマ
# （そして何よりもこの――）
318 = "（そして何よりもこの――）"

# カズマ
# 絶景！
308 = "絶景！"

# ウィズ
# ええ！？
248 = "ええ！？"

# カズマ（Ｍ）
# display as カズマ
# （ああ、すべすべでぬくぬくでバインバインで）
314 = "（ああ、すべすべでぬくぬくでバインバインで）"

# カズマ（Ｍ）
# display as カズマ
# （もう全てが満たされてる気分だ）
321 = "（もう全てが満たされてる気分だ）"

# ウィズ
# カ、カズマさぁん、あんまり頬をスリスリしないで\n下さい。
282 = "カ、カズマさぁん、あんまり頬をスリスリしないで\\n下さい。"

# カズマ
# いや、無理。\nこれを堪能したいがためにお願いしたんだからな！
232 = "いや、無理。\\nこれを堪能したいがためにお願いしたんだからな！"

# カズマ（Ｍ）
# display as カズマ
# （これこそが最上級のご褒美だ！）
317 = "（これこそが最上級のご褒美だ！）"

# ウィズ
# ううう、カズマさん。\nもういいですか？
240 = "ううう、カズマさん。\\nもういいですか？"

# カズマ
# 何を言ってるんだ。\nまだ耳かきをしてないだろ。
290 = "何を言ってるんだ。\\nまだ耳かきをしてないだろ。"

# ウィズ
# そ、そうでしたね。\nでは、失礼します。
255 = "そ、そうでしたね。\\nでは、失礼します。"

# カズマ
# はい、どーぞ。
273 = "はい、どーぞ。"

# ウィズ
# ええと、こんな感じですか？
247 = "ええと、こんな感じですか？"

# カズマ
# はあぁぁぁぁ、極楽極楽。\n色々な意味で極楽だー。
272 = "はあぁぁぁぁ、極楽極楽。\\n色々な意味で極楽だー。"

# ウィズ
# い、色々な意味ってなんですか！？
229 = "い、色々な意味ってなんですか！？"

# カズマ
# いいね！　驚くのいいよ！
230 = "いいね！　驚くのいいよ！"

# カズマ（Ｍ）
# display as カズマ
# （たまに顔にぺちぺちあたるのが――）
319 = "（たまに顔にぺちぺちあたるのが――）"

# カズマ
# もう最高だ！
278 = "もう最高だ！"

# ウィズ
# な、何がですか！！
267 = "な、何がですか！！"

# カズマ
# 俺のことはいいから耳かきに集中してくれよ。
291 = "俺のことはいいから耳かきに集中してくれよ。"

# ウィズ
# そうですね。\n刺したら大変ですもんね。
258 = "そうですね。\\n刺したら大変ですもんね。"

# カズマ
# はぁ、横を向けばふとももで幸せ。\n上を向けば――
270 = "はぁ、横を向けばふとももで幸せ。\\n上を向けば――"

# ウィズ
# ひっ！？
275 = "ひっ！？"

# カズマ
# 色々な意味で幸せ。
310 = "色々な意味で幸せ。"

# ウィズ
# うぅ～～～～！！
239 = "うぅ～～～～！！"

# カズマ
# はあ、素晴らしい、最高だよウィズ。
271 = "はあ、素晴らしい、最高だよウィズ。"

# ウィズ
# あの、それでしたら、\n幸せな気持ちのまま終わりに……。
228 = "あの、それでしたら、\\n幸せな気持ちのまま終わりに……。"

# カズマ
# いやっ！　まだダメだっ！\nちっとも満たされてないぞ！！
234 = "いやっ！　まだダメだっ！\\nちっとも満たされてないぞ！！"

# ウィズ
# えええっ！\nこれ以上、何をどうすればいいんですか。
245 = "えええっ！\\nこれ以上、何をどうすればいいんですか。"

# カズマ（Ｍ）
# display as カズマ
# （うーん、そうだなぁ……）
316 = "（うーん、そうだなぁ……）"

# カズマ
# 耳元で優しく囁いてくれないかな。
309 = "耳元で優しく囁いてくれないかな。"

# ウィズ
# 囁くって、ええと、どんな言葉を……。
296 = "囁くって、ええと、どんな言葉を……。"

# カズマ
# そりゃもちろん、愛の言葉を。
260 = "そりゃもちろん、愛の言葉を。"

# ウィズ
# ふぇぇぇ！？
276 = "ふぇぇぇ！？"

# カズマ
# さあ、さあっ！
254 = "さあ、さあっ！"

# ウィズ
# え、ええと、その、カズマさん。\n私、カズマさんのこと……。
242 = "え、ええと、その、カズマさん。\\n私、カズマさんのこと……。"

# カズマ
# 俺のこと？
292 = "俺のこと？"

# ウィズ
# あ、あ、愛してます……。
224 = "あ、あ、愛してます……。"

# カズマ
# うおおおおおおおお！！！
241 = "うおおおおおおおお！！！"

# ウィズ
# うぅぅぅ～～～～。\n恥ずかしすぎます。
238 = "うぅぅぅ～～～～。\\n恥ずかしすぎます。"

# カズマ
# はぁ、可愛いなウィズは。
269 = "はぁ、可愛いなウィズは。"

# カズマ
# 頭を抱いてくれる？
313 = "頭を抱いてくれる？"

# ウィズ
# 頭をって、この体勢で頭を抱こうとしたら、\nその……む、胸が当たって。
312 = "頭をって、この体勢で頭を抱こうとしたら、\\nその……む、胸が当たって。"

# カズマ
# ハッ！？　そ、そんな副次効果があったか！！！\nよしっ、すぐっ！　今すぐ頼む！！！
288 = "ハッ！？　そ、そんな副次効果があったか！！！\\nよしっ、すぐっ！　今すぐ頼む！！！"

# ウィズ
# えええっ、気付いてなかったんですか！？\nそんなぁ……。
244 = "えええっ、気付いてなかったんですか！？\\nそんなぁ……。"

# カズマ
# はぁ、可愛いなウィズは。
# 269 = "はぁ、可愛いなウィズは。"

# カズマ
# ジッと俺のこと、見つめて欲しい。
286 = "ジッと俺のこと、見つめて欲しい。"

# ウィズ
# えっ……えええっ！？
249 = "えっ……えええっ！？"

# カズマ
# こう、情熱的に、一心不乱に俺の目を……。
252 = "こう、情熱的に、一心不乱に俺の目を……。"

# ウィズ
# は、はい……じー…………。
268 = "は、はい……じー…………。"

# カズマ
# 見てないよね！
311 = "見てないよね！"

# ウィズ
# だ、だって～。
265 = "だ、だって～。"

# カズマ
# いいよ、だったら俺が見つめちゃうから！\nジーーーーーーー！！
231 = "いいよ、だったら俺が見つめちゃうから！\\nジーーーーーーー！！"

# ウィズ
# カ、カズマさんだって見ていないじゃないですか！
283 = "カ、カズマさんだって見ていないじゃないですか！"

# カズマ
# いや、見てるよ、おっぱいを。
233 = "いや、見てるよ、おっぱいを。"

# ウィズ
# えええ！？
246 = "えええ！？"

# カズマ
# そんなうろたえてるウィズを凝視！
263 = "そんなうろたえてるウィズを凝視！"

# ウィズ
# あうぅ～～。
226 = "あうぅ～～。"

# カズマ
# はぁ、可愛いなウィズは。
# 269 = "はぁ、可愛いなウィズは。"

# ウィズ
# あの、え？　可愛いなんて、そんな！？
227 = "あの、え？　可愛いなんて、そんな！？"

# カズマ
# 可愛い。
294 = "可愛い。"

# ウィズ
# ひぅ！
274 = "ひぅ！"

# カズマ
# 可愛い。
# 294 = "可愛い。"

# ウィズ
# あぅぅ～～。
225 = "あぅぅ～～。"

# カズマ
# かぁんわぃぃ～～！！
251 = "かぁんわぃぃ～～！！"

# ウィズ
# も、もう、やめてください！！\nドレインタッチしちゃいますよ！
277 = "も、もう、やめてください！！\\nドレインタッチしちゃいますよ！"

# カズマ
# ごめん、それは本当に勘弁して……。
253 = "ごめん、それは本当に勘弁して……。"

[selections]
293 = "優しく囁いてくれないかな"
# 313 = "頭を抱いてくれる？"
287 = "ジッと見つめて欲しい"
