# rew_d03.txt.scn

[info]
286 = "rew_d03"

[characters]
415 = "クリス"
413 = "カズマ"
414 = "カズマ（Ｍ）"

[character_subs]
# 413 = "カズマ"

[script]
# lines: 144

# クリス
# はい、言われたとおり着替えてきたよ。
400 = "はい、言われたとおり着替えてきたよ。"

# カズマ
# うんうん、バッチリ。\nさすがクリス、似合ってるな。
340 = "うんうん、バッチリ。\\nさすがクリス、似合ってるな。"

# クリス
# あはは、ありがと。\nそれで、あたしに何させるつもりなのかな？
326 = "あはは、ありがと。\\nそれで、あたしに何させるつもりなのかな？"

# カズマ
# 実はノープランだったんだけど、\nクリスのその姿を見てびびっときた！
433 = "実はノープランだったんだけど、\\nクリスのその姿を見てびびっときた！"

# クリス
# おお、直感の閃きってやつだね。\nなになに？　ちょっと興味あるかも。
349 = "おお、直感の閃きってやつだね。\\nなになに？　ちょっと興味あるかも。"

# カズマ
# あっと、その前に、\nひとつだけ聞いておきたいんだけどいいか？
321 = "あっと、その前に、\\nひとつだけ聞いておきたいんだけどいいか？"

# クリス
# うん、構わないけど？
338 = "うん、構わないけど？"

# カズマ
# これは俺へのご褒美だ。\nそれはつまり――
354 = "これは俺へのご褒美だ。\\nそれはつまり――"

# クリス
# あたしに拒否権は無い、そう言いたいんだね？
318 = "あたしに拒否権は無い、そう言いたいんだね？"

# カズマ
# あっ、変なことをさせるつもりはないからな。\nどんなご褒美を貰おうと、クリスに嫌われるのは\n勘弁して欲しいし。
320 = "あっ、変なことをさせるつもりはないからな。\\nどんなご褒美を貰おうと、クリスに嫌われるのは\\n勘弁して欲しいし。"

# クリス
# 嬉しいことを言ってくれるけどさ、\nいちいちそういう確認をするって事は、\n結構ギリギリのお願いをするつもりなんでしょ？
432 = "嬉しいことを言ってくれるけどさ、\\nいちいちそういう確認をするって事は、\\n結構ギリギリのお願いをするつもりなんでしょ？"

# カズマ（Ｍ）
# display as カズマ
# （さすがクリス、鋭いな）
501 = "（さすがクリス、鋭いな）"

# クリス
# 相手がキミだし、ある程度覚悟は出来てるつもり\nだからさ、とりあえずお願いの内容を言ってみてよ。
489 = "相手がキミだし、ある程度覚悟は出来てるつもり\\nだからさ、とりあえずお願いの内容を言ってみてよ。"

# カズマ
# じゃあ、言うぞ。
358 = "じゃあ、言うぞ。"

# クリス
# ほーら、もったいぶらずに。
405 = "ほーら、もったいぶらずに。"

# カズマ
# ス、スカートをたくし上げてください！
418 = "ス、スカートをたくし上げてください！"

# クリス
# ……え？
315 = "……え？"

# カズマ
# だからスカートだよ、スカート。\nクリスの穿いてるスカートをたくし上げて\nくれって言ってるんだ。
378 = "だからスカートだよ、スカート。\\nクリスの穿いてるスカートをたくし上げて\\nくれって言ってるんだ。"

# クリス
# …………。
313 = "…………。"

# カズマ
# な、なんなんだよその目は！
384 = "な、なんなんだよその目は！"

# クリス
# いやー、どんなお願いをされても対応できるように\n心の準備をしてたつもりなんだけど――
333 = "いやー、どんなお願いをされても対応できるように\\n心の準備をしてたつもりなんだけど――"

# クリス
# あは、あはは、そのさらに上を行かれたなーって。
324 = "あは、あはは、そのさらに上を行かれたなーって。"

# カズマ
# 男の煩悩を侮って貰っては困るな！
445 = "男の煩悩を侮って貰っては困るな！"

# クリス
# そこ、胸を張る所じゃ無いからね。
365 = "そこ、胸を張る所じゃ無いからね。"

# カズマ（Ｍ）
# display as カズマ
# （ですよねー？）
503 = "（ですよねー？）"

# クリス
# それで？　スカートなんてたくし上げて\n何が楽しいのさ。\n正直、意味がわからないんだけど。
372 = "それで？　スカートなんてたくし上げて\\n何が楽しいのさ。\\n正直、意味がわからないんだけど。"

# カズマ
# そこに意味を求める。\nまずそこから間違えてる！
366 = "そこに意味を求める。\\nまずそこから間違えてる！"

# クリス
# は、はあ。
394 = "は、はあ。"

# カズマ
# 意味なんてないんだ。\nむしろ、意味など必要ない！
439 = "意味なんてないんだ。\\nむしろ、意味など必要ない！"

# カズマ
# これはそう、男なら誰もが一度は夢見る\nシチュエーションなんだよ。
353 = "これはそう、男なら誰もが一度は夢見る\\nシチュエーションなんだよ。"

# カズマ
# つまり男の浪漫！！
380 = "つまり男の浪漫！！"

# カズマ
# 見えるか見えないか、そのギリギリを攻める\nチキンレース！
496 = "見えるか見えないか、そのギリギリを攻める\\nチキンレース！"

# カズマ
# 見えてはいけない、でも見たい。\nだが見えてしまっては全てをぶちこわし！
495 = "見えてはいけない、でも見たい。\\nだが見えてしまっては全てをぶちこわし！"

# カズマ
# その胸の高鳴りを堪能をするのが、\nスカートのたくし上げ！
369 = "その胸の高鳴りを堪能をするのが、\\nスカートのたくし上げ！"

# カズマ
# そう、つまり！！
361 = "そう、つまり！！"

# クリス
# 男の浪漫？
444 = "男の浪漫？"

# カズマ
# おおおー、理解してくれたか！！
350 = "おおおー、理解してくれたか！！"

# クリス
# あは、あはは、できるわけないでしょ。
325 = "あは、あはは、できるわけないでしょ。"

# カズマ
# そっかー。\n確かにまあ、女の子には難しいかもしれないな。
367 = "そっかー。\\n確かにまあ、女の子には難しいかもしれないな。"

# クリス
# あのさ、こんなこと言いたくないけど、\nキミって筋金入りの変態だよね。
322 = "あのさ、こんなこと言いたくないけど、\\nキミって筋金入りの変態だよね。"

# カズマ
# し、失礼な！\nこれは男なら誰もが持ち合わせている\n欲望なんだぞ！
356 = "し、失礼な！\\nこれは男なら誰もが持ち合わせている\\n欲望なんだぞ！"

# クリス
# はいはい、わかったよ。\nそういうことにしておいてあげる。
402 = "はいはい、わかったよ。\\nそういうことにしておいてあげる。"

# カズマ（Ｍ）
# display as カズマ
# （くっそ、信じてねーな）
500 = "（くっそ、信じてねーな）"

# クリス
# えーと、それで？\nとりあえず、スカートをたくし上げるだけで\nいいんだよね？
346 = "えーと、それで？\\nとりあえず、スカートをたくし上げるだけで\\nいいんだよね？"

# カズマ
# でも中は見せるなよ？\nむしろ見せちゃ駄目だからな。\nギリギリの所で止めるんだぞ！
382 = "でも中は見せるなよ？\\nむしろ見せちゃ駄目だからな。\\nギリギリの所で止めるんだぞ！"

# カズマ
# 見えそうで見えないってところが\n重要なんだからな。\n本当に見えたらチラリズムの意味がなくなる！
492 = "見えそうで見えないってところが\\n重要なんだからな。\\n本当に見えたらチラリズムの意味がなくなる！"

# クリス
# あのさぁ、中が見えようが見えまいが\nあんまり関係ないと思うんだけど。
323 = "あのさぁ、中が見えようが見えまいが\\nあんまり関係ないと思うんだけど。"

# カズマ
# ん、どういう意味だ？
411 = "ん、どういう意味だ？"

# クリス
# あたし、中にスパッツ穿いてるから。
317 = "あたし、中にスパッツ穿いてるから。"

# カズマ
# なんでそんな物穿いてるんだよ！\nスカートの下は生足っていうのが王道だろう！
391 = "なんでそんな物穿いてるんだよ！\\nスカートの下は生足っていうのが王道だろう！"

# クリス
# だ、だって動くと下着が見えちゃうかも\nしれないし。
376 = "だ、だって動くと下着が見えちゃうかも\\nしれないし。"

# カズマ
# だぁー！！\nそれを気にしながら恥じらう姿がイイんだろうが！\nスカートの下にスパッツとか詐欺だろそれ！
377 = "だぁー！！\\nそれを気にしながら恥じらう姿がイイんだろうが！\\nスカートの下にスパッツとか詐欺だろそれ！"

# カズマ
# クリス、お前自分が何をしたかわかってるか？\nお前は全世界の男の浪漫を踏みにじったんだぞ！
416 = "クリス、お前自分が何をしたかわかってるか？\\nお前は全世界の男の浪漫を踏みにじったんだぞ！"

# クリス
# そんなこと言われても……。
375 = "そんなこと言われても……。"

# カズマ
# 脱げ。
491 = "脱げ。"

# クリス
# えっ？
345 = "えっ？"

# カズマ
# いいからそれを脱げ、クリス。
328 = "いいからそれを脱げ、クリス。"

# クリス
# えええ、嫌だよ！\nなんで脱がなきゃいけないのさ！
343 = "えええ、嫌だよ！\\nなんで脱がなきゃいけないのさ！"

# カズマ
# それが、世界の理だからだよ！
370 = "それが、世界の理だからだよ！"

# クリス
# 意味がわからないよ！
438 = "意味がわからないよ！"

# カズマ
# わからなくていいから脱げ！\n早く脱げ！　今すぐ脱げ！\nさあさあさあー！
409 = "わからなくていいから脱げ！\\n早く脱げ！　今すぐ脱げ！\\nさあさあさあー！"

# カズマ
# スパッツを穿いたアイドルなんて\nさくらんぼをのせないプリンのようなもんだ！\nそんなの俺は認めない！
420 = "スパッツを穿いたアイドルなんて\\nさくらんぼをのせないプリンのようなもんだ！\\nそんなの俺は認めない！"

# クリス
# プリンはちょっとわかるけど、\nスパッツを脱ぐのはお断りだよ！
421 = "プリンはちょっとわかるけど、\\nスパッツを脱ぐのはお断りだよ！"

# カズマ
# そうか、ならば仕方ない。\nこうなったら実力行使するしか！
362 = "そうか、ならば仕方ない。\\nこうなったら実力行使するしか！"

# クリス
# ま、まさかスティールするつもり？
406 = "ま、まさかスティールするつもり？"

# カズマ
# これでスパッツ以外の物を盗ったとしても\n不慮の事故だからな！
352 = "これでスパッツ以外の物を盗ったとしても\\n不慮の事故だからな！"

# クリス
# わわわ、わかった、わかったから！\nスティールだけはやめて！
410 = "わわわ、わかった、わかったから！\\nスティールだけはやめて！"

# カズマ
# だったら――
379 = "だったら――"

# クリス
# 脱ぐよ、脱ぎますっ！\n脱げばいいんでしょ！
490 = "脱ぐよ、脱ぎますっ！\\n脱げばいいんでしょ！"

# カズマ
# 男の浪漫を少しは理解してくれたようだな。
443 = "男の浪漫を少しは理解してくれたようだな。"

# クリス
# はぁ、もう。\nなんでこんなことしないといけないのさ。
396 = "はぁ、もう。\\nなんでこんなことしないといけないのさ。"

# カズマ
# ジー……。
417 = "ジー……。"

# クリス
# ねえ、脱ぐところを見る必要はないよね？
393 = "ねえ、脱ぐところを見る必要はないよね？"

# カズマ
# え、あるけど？
342 = "え、あるけど？"

# クリス
# ないよ、絶対にないっ！　あるわけがない！\nはい、いいから目をつむるっ！
387 = "ないよ、絶対にないっ！　あるわけがない！\\nはい、いいから目をつむるっ！"

# カズマ
# はいはい、これでいいか？
401 = "はいはい、これでいいか？"

# クリス
# 見えてないよね？
494 = "見えてないよね？"

# クリス
# うん、本当に見てないようだね。
337 = "うん、本当に見てないようだね。"

# カズマ
# なんだ今の音？
390 = "なんだ今の音？"

# クリス
# 動かない方がいいよ。\n今、君の目の前にはダガーの切っ先があるから。
430 = "動かない方がいいよ。\\n今、君の目の前にはダガーの切っ先があるから。"

# カズマ（Ｍ）
# display as カズマ
# （なっ！？）
504 = "（なっ！？）"

# クリス
# はぁ、どうしてこんなことしないといけないの。
395 = "はぁ、どうしてこんなことしないといけないの。"

# カズマ（Ｍ）
# display as カズマ
# （ふふ、妄想が捗るぜ。\n　これはこれで、素晴らしいご褒美だな）
505 = "（ふふ、妄想が捗るぜ。\\n　これはこれで、素晴らしいご褒美だな）"

# クリス
# はい、目を開けてもいいよ。
399 = "はい、目を開けてもいいよ。"

# カズマ
# うーん？　本当に脱いだんだろうな。
341 = "うーん？　本当に脱いだんだろうな。"

# クリス
# スパッツ、ここにあるでしょ。
419 = "スパッツ、ここにあるでしょ。"

# カズマ
# それって本当に今まで穿いていたスパッツなのか？
371 = "それって本当に今まで穿いていたスパッツなのか？"

# クリス
# そうは言われても、証明する手段がないんだけど。
364 = "そうは言われても、証明する手段がないんだけど。"

# カズマ
# 俺が触ればわかるだろう。\nぬくもりで。
429 = "俺が触ればわかるだろう。\\nぬくもりで。"

# クリス
# なななっ、そんなのダメ！！
389 = "なななっ、そんなのダメ！！"

# カズマ
# うんうん、いいぞいいぞ。\n俺はその表情が欲しかったんだ。
339 = "うんうん、いいぞいいぞ。\\n俺はその表情が欲しかったんだ。"

# クリス
# はぁ、もしかして冗談？\nそういうのは心臓に悪いからやめて。
397 = "はぁ、もしかして冗談？\\nそういうのは心臓に悪いからやめて。"

# カズマ
# いや、本気。
332 = "いや、本気。"

# クリス
# 怒るよ。
435 = "怒るよ。"

# カズマ
# すみませんでした。
359 = "すみませんでした。"

# クリス
# それで？　スカートを持ち上げればいいの？
373 = "それで？　スカートを持ち上げればいいの？"

# カズマ
# その前に、ちょっとそのままくるっと回ってみ？
368 = "その前に、ちょっとそのままくるっと回ってみ？"

# クリス
# そ、そんなことしたら見えちゃうじゃないか！
360 = "そ、そんなことしたら見えちゃうじゃないか！"

# カズマ（Ｍ）
# display as カズマ
# （うんうん。\n　いつものしっかりしているクリスもいいけど、\n　こういうのも新鮮だ）
499 = "（うんうん。\\n　いつものしっかりしているクリスもいいけど、\\n　こういうのも新鮮だ）"

# カズマ（Ｍ）
# display as カズマ
# （それに、こんな顔をされると、\n　なんていうか、いけない欲求がふつふつと……）
502 = "（それに、こんな顔をされると、\\n　なんていうか、いけない欲求がふつふつと……）"

# カズマ
# なあ、クリス。
385 = "なあ、クリス。"

# カズマ
# もしかしてパンツも脱いだ？
407 = "もしかしてパンツも脱いだ？"

# クリス
# なっ、突然何言い出すのさキミは！？
388 = "なっ、突然何言い出すのさキミは！？"

# カズマ
# いや、なんかすごい顔赤くしてるからさ。\nスパッツと一緒にパンツも脱いじゃったから\n恥ずかしがってるのかなって。
331 = "いや、なんかすごい顔赤くしてるからさ。\\nスパッツと一緒にパンツも脱いじゃったから\\n恥ずかしがってるのかなって。"

# クリス
# そんなことあるわけないでしょ！
374 = "そんなことあるわけないでしょ！"

# カズマ
# 本当か？\nじゃあちょっとその証拠を見せるために\nスカートを上までめくってみようか。
440 = "本当か？\\nじゃあちょっとその証拠を見せるために\\nスカートを上までめくってみようか。"

# クリス
# さっきと言ってることが違うじゃない！\nギリギリを攻めるのが男の浪漫なんでしょ！
355 = "さっきと言ってることが違うじゃない！\\nギリギリを攻めるのが男の浪漫なんでしょ！"

# カズマ
# 男の真の欲望の前に、\nそんな物は無力に等しいんだ。
446 = "男の真の欲望の前に、\\nそんな物は無力に等しいんだ。"

# カズマ
# ふっ、それに男はみんな女の前じゃ、\nただの馬鹿な男になるのさ。
403 = "ふっ、それに男はみんな女の前じゃ、\\nただの馬鹿な男になるのさ。"

# カズマ
# 特に可愛い……女の子の前ではな。
441 = "特に可愛い……女の子の前ではな。"

# クリス
# 何言ってるんだか。\nそんなのカズマくらいだよ。
428 = "何言ってるんだか。\\nそんなのカズマくらいだよ。"

# カズマ
# 恥ずかしがってるクリス可愛いぞ。
437 = "恥ずかしがってるクリス可愛いぞ。"

# クリス
# えっ……。
344 = "えっ……。"

# カズマ
# いつもはなんでも１人でやれます～って\n顔してるから、保護欲をそそられるというか\n守ってやりたくなるっていうか。
330 = "いつもはなんでも１人でやれます～って\\n顔してるから、保護欲をそそられるというか\\n守ってやりたくなるっていうか。"

# カズマ
# なあ、クリス。\nたまには俺に頼ってくれてもいいんだぜ？
386 = "なあ、クリス。\\nたまには俺に頼ってくれてもいいんだぜ？"

# クリス
# 何かたくらんでるんでしょ。
426 = "何かたくらんでるんでしょ。"

# カズマ
# どうしてそういう受け取り方をするかな。
383 = "どうしてそういう受け取り方をするかな。"

# クリス
# 今、無理矢理スパッツを脱がせたのは\nどこの誰かな？
423 = "今、無理矢理スパッツを脱がせたのは\\nどこの誰かな？"

# カズマ
# はい、俺です。
398 = "はい、俺です。"

# クリス
# でも、その、少し嬉しかったかも。\nありがとね、カズマ。
381 = "でも、その、少し嬉しかったかも。\\nありがとね、カズマ。"

# カズマ
# 今の状況を説明してくれ！
425 = "今の状況を説明してくれ！"

# クリス
# 状況って言われても。\n見ての通りいつものままだけど。
442 = "状況って言われても。\\n見ての通りいつものままだけど。"

# カズマ
# そうじゃない。\nそうじゃないだろ、クリス。
363 = "そうじゃない。\\nそうじゃないだろ、クリス。"

# カズマ
# 閉ざされた空間に男と女が１人ずつ……\nとなれば、やることは１つ。\nあとはもう、わかるな？
497 = "閉ざされた空間に男と女が１人ずつ……\\nとなれば、やることは１つ。\\nあとはもう、わかるな？"

# クリス
# 何を言っているのかまったくわかんないんだけど？\nもしかしてキミ、あたしに張り倒されたい？
427 = "何を言っているのかまったくわかんないんだけど？\\nもしかしてキミ、あたしに張り倒されたい？"

# カズマ
# ……あ、すみません。\nなんでもないです。
314 = "……あ、すみません。\\nなんでもないです。"

# クリス
# ああもう、くだらないことしてないで\nさっさと終わらせちゃおうよ！
316 = "ああもう、くだらないことしてないで\\nさっさと終わらせちゃおうよ！"

# クリス
# いつまでもこんな格好してるなんて\n不毛にもほどがあるでしょ！
329 = "いつまでもこんな格好してるなんて\\n不毛にもほどがあるでしょ！"

# カズマ
# んー、でも、似合ってるぞ？
412 = "んー、でも、似合ってるぞ？"

# クリス
# ～～～もうっ！\nとにかく、キミの望みはスカートをたくし上げる\nことだったよね。
506 = "～～～もうっ！\\nとにかく、キミの望みはスカートをたくし上げる\\nことだったよね。"

# クリス
# やるからちゃんと見ててよ。\nあとから見てなかったからやっぱなし、とか\nそういうのは受け付けないんだからね。
408 = "やるからちゃんと見ててよ。\\nあとから見てなかったからやっぱなし、とか\\nそういうのは受け付けないんだからね。"

# カズマ
# おう、ちゃーんと見てるから安心してくれ。\nあ、でもスカートはきちんとギリギリまで\nたくし上げてくれよ？
347 = "おう、ちゃーんと見てるから安心してくれ。\\nあ、でもスカートはきちんとギリギリまで\\nたくし上げてくれよ？"

# カズマ
# 見えそうで見えないギリギリのラインを\n攻めるのが重要なんだからな！
493 = "見えそうで見えないギリギリのラインを\\n攻めるのが重要なんだからな！"

# クリス
# うう、カズマの変態……。
335 = "うう、カズマの変態……。"

# カズマ
# なんとでも言え。
392 = "なんとでも言え。"

# クリス
# じゃあ、やるよ！
357 = "じゃあ、やるよ！"

# カズマ
# おうっ！
348 = "おうっ！"

# クリス
# うっ、くぅ、くぅぅぅっ！
336 = "うっ、くぅ、くぅぅぅっ！"

# カズマ
# おーい、まだ１ｃｍくらいしか上がってないぞー。
351 = "おーい、まだ１ｃｍくらいしか上がってないぞー。"

# クリス
# うぅ、あぅぅ、くぅぅぅ～～～～！！
334 = "うぅ、あぅぅ、くぅぅぅ～～～～！！"

# カズマ
# ほら頑張れー。\nクリスはやれば出来る子だろ。
404 = "ほら頑張れー。\\nクリスはやれば出来る子だろ。"

# クリス
# あーん、もうっ、やっぱり無理ぃっ！！
327 = "あーん、もうっ、やっぱり無理ぃっ！！"

# カズマ
# あっ、おいクリス！
319 = "あっ、おいクリス！"

# カズマ（Ｍ）
# display as カズマ
# （……やっぱりクリスにゃ無理だったか。\n　まあでも、恥ずかしがるクリスも堪能できたし\n　これはこれで美味しかったかな）
498 = "（……やっぱりクリスにゃ無理だったか。\\n　まあでも、恥ずかしがるクリスも堪能できたし\\n　これはこれで美味しかったかな）"

[selections]
# 407 = "もしかしてパンツも脱いだ？"
436 = "恥ずかしがってるクリスも可愛いぞ"
424 = "今の状況を説明してくれ"
