# rew_a07.txt.scn

[info]
202 = "rew_a07"

[characters]
264 = "アクア"
265 = "カズマ"
266 = "カズマ（Ｍ）"

[character_subs]
# 265 = "カズマ"

[script]
# lines: 57

# アクア
# さあ、カズマ！\n私を崇め、褒め称えなさい。
238 = "さあ、カズマ！\\n私を崇め、褒め称えなさい。"

# カズマ
# は？　それがお仕置きなのか？
258 = "は？　それがお仕置きなのか？"

# アクア
# だってカズマ、\nちっとも私のことを褒めないじゃない。
250 = "だってカズマ、\\nちっとも私のことを褒めないじゃない。"

# カズマ
# だからお仕置きにかこつけて褒めさせると。
247 = "だからお仕置きにかこつけて褒めさせると。"

# アクア
# そうよ。\n褒めたくないものを褒めるって、結構屈辱でしょ？
243 = "そうよ。\\n褒めたくないものを褒めるって、結構屈辱でしょ？"

# カズマ（Ｍ）
# display as カズマ
# （そのブーメラン、お前の額に\n　思いっきりぶっささってるぞ、アクア……）
306 = "（そのブーメラン、お前の額に\\n　思いっきりぶっささってるぞ、アクア……）"

# アクア
# ねえ、ほーら、早く褒めてってば。
256 = "ねえ、ほーら、早く褒めてってば。"

# カズマ
# んー……。
263 = "んー……。"

# アクア
# わくわく。
262 = "わくわく。"

# カズマ
# うー……あー……。
229 = "うー……あー……。"

# アクア
# 早く、早く！
275 = "早く、早く！"

# カズマ
# ううーん……。
227 = "ううーん……。"

# アクア
# なになに？\nもしかして褒めるところが多すぎて\n悩んじゃってる？
254 = "なになに？\\nもしかして褒めるところが多すぎて\\n悩んじゃってる？"

# カズマ
# うーん、悩んでるっていうのは正解なんだけど。\n褒めるところが多いから悩んでるんじゃ\nなくてだな。
230 = "うーん、悩んでるっていうのは正解なんだけど。\\n褒めるところが多いから悩んでるんじゃ\\nなくてだな。"

# アクア
# だったらなんでさっきから、\nうーんうーん言ってるのよ。
248 = "だったらなんでさっきから、\\nうーんうーん言ってるのよ。"

# カズマ
# 無いんだよ。
276 = "無いんだよ。"

# アクア
# 何が？
267 = "何が？"

# カズマ
# 褒めるところが。
301 = "褒めるところが。"

# アクア
# え？
232 = "え？"

# カズマ
# お、俺なりに努力したんだぞ！\nでも、どうしても見つけられなかったんだ……。\nごめん。
233 = "お、俺なりに努力したんだぞ！\\nでも、どうしても見つけられなかったんだ……。\\nごめん。"

# アクア
# じょ、冗談よね？
240 = "じょ、冗談よね？"

# カズマ
# 捏造しようともしたんだ！\nけどさ、それも難しくて……。
274 = "捏造しようともしたんだ！\\nけどさ、それも難しくて……。"

# アクア
# 何よそれぇぇ！！　何かあるでしょ！\nこうちょびっとでも！！\n無理矢理搾り出せば！
269 = "何よそれぇぇ！！　何かあるでしょ！\\nこうちょびっとでも！！\\n無理矢理搾り出せば！"

# カズマ
# ごめん……。
237 = "ごめん……。"

# アクア
# 謝らないでよカズマさん！\n髪が綺麗とか、爪の形が整ってるとか、\n歯並びがいいとか、何かしらあるじゃない！
304 = "謝らないでよカズマさん！\\n髪が綺麗とか、爪の形が整ってるとか、\\n歯並びがいいとか、何かしらあるじゃない！"

# カズマ
# じゃ、じゃあ……。
239 = "じゃ、じゃあ……。"

# アクア
# う、うん！
226 = "う、うん！"

# カズマ
# 目が水色。
278 = "目が水色。"

# アクア
# それは事実を言ってるだけだから！
246 = "それは事実を言ってるだけだから！"

# カズマ
# あー、全くもう。\nじゃあ、そうだな。
225 = "あー、全くもう。\\nじゃあ、そうだな。"

# カズマ
# 少しは可愛いかもしれないな。
271 = "少しは可愛いかもしれないな。"

# アクア
# えっ、ほんとっ！！
231 = "えっ、ほんとっ！！"

# カズマ
# な、なんだその食いつきは。
253 = "な、なんだその食いつきは。"

# アクア
# だって、カズマの口からそんなこと、\nウソでも言われたことないから！
249 = "だって、カズマの口からそんなこと、\\nウソでも言われたことないから！"

# カズマ
# そうだっけ？
242 = "そうだっけ？"

# アクア
# うふふ、これは記念すべき日ね！\nヒキニートに可愛いと言われる……。
228 = "うふふ、これは記念すべき日ね！\\nヒキニートに可愛いと言われる……。"

# アクア
# なんか一気にありがたみがなくなったわね。
255 = "なんか一気にありがたみがなくなったわね。"

# カズマ
# お前な。こっちは断腸の思いで可愛いと言って\nやったんだから少しはありがたがれよ。
235 = "お前な。こっちは断腸の思いで可愛いと言って\\nやったんだから少しはありがたがれよ。"

# カズマ
# そこはかとなくぅ……気品があるな。
245 = "そこはかとなくぅ……気品があるな。"

# アクア
# ちょっと、今の間が気になるんですけど。
252 = "ちょっと、今の間が気になるんですけど。"

# カズマ
# 言葉を吟味して出したんだよ！
303 = "言葉を吟味して出したんだよ！"

# アクア
# 疑わしいわね。
277 = "疑わしいわね。"

# カズマ
# これでもちゃんと見てるとこは見てるんだからな。
236 = "これでもちゃんと見てるとこは見てるんだからな。"

# カズマ
# お前が上級魔法を使った時なんかは、\nそれなりに女神らしさが出てたと思うし。
234 = "お前が上級魔法を使った時なんかは、\\nそれなりに女神らしさが出てたと思うし。"

# カズマ
# まあ、親しみやすいかもしれないな。
261 = "まあ、親しみやすいかもしれないな。"

# アクア
# 何よそれ。\nあんまり嬉しくないんですけどー。
268 = "何よそれ。\\nあんまり嬉しくないんですけどー。"

# カズマ
# はあ？\n親しみやすいって、これ以上無い褒め言葉だろ。
257 = "はあ？\\n親しみやすいって、これ以上無い褒め言葉だろ。"

# カズマ
# 性格はもちろん、言葉遣いとか表情とか、\n色々な要素が相まって親しみやすさが\n生まれるんだからさ。
273 = "性格はもちろん、言葉遣いとか表情とか、\\n色々な要素が相まって親しみやすさが\\n生まれるんだからさ。"

# アクア
# 確かに、そう言われてみればそうね。
299 = "確かに、そう言われてみればそうね。"

# カズマ
# だろー？　だからこれで納得しておけ。
251 = "だろー？　だからこれで納得しておけ。"

# アクア
# ふんふん、なるほどつまり……。
260 = "ふんふん、なるほどつまり……。"

# カズマ（Ｍ）
# display as カズマ
# （まーた、変なこと考えてるな）
308 = "（まーた、変なこと考えてるな）"

# アクア
# 私は皆から褒め称えられる存在ってことね！
300 = "私は皆から褒め称えられる存在ってことね！"

# カズマ（Ｍ）
# display as カズマ
# （どうしてそう、思考が飛躍するかな……）
307 = "（どうしてそう、思考が飛躍するかな……）"

# アクア
# ふふふ、なんだか気分が良くなってきちゃった。
259 = "ふふふ、なんだか気分が良くなってきちゃった。"

# アクア
# そうだ、カズマ、これから酒場に行かない？\n今日は私がおごってあげる！
241 = "そうだ、カズマ、これから酒場に行かない？\\n今日は私がおごってあげる！"

# カズマ（Ｍ）
# display as カズマ
# （こういう単純なところもアクアのいいところ\n　なんだろうな）
305 = "（こういう単純なところもアクアのいいところ\\n　なんだろうな）"

[selections]
# 271 = "少しは可愛いかもしれないな。"
244 = "そこはかとなく……気品が。"
302 = "親しみやすいかもしれないな。"
