# rew_b05.txt.scn

[info]
249 = "rew_b05"

[characters]
344 = "めぐみん"
355 = "カズマ"
358 = "カズマ（Ｍ）"

[character_subs]
# 355 = "カズマ"

[script]
# lines: 121

# めぐみん
# 今回は何をさせようというのです？
366 = "今回は何をさせようというのです？"

# カズマ
# ずばりコスプレだ！
300 = "ずばりコスプレだ！"

# めぐみん
# コスプレ？\n聞き覚えのない言葉ですね。\nなんですかそれは？
359 = "コスプレ？\\n聞き覚えのない言葉ですね。\\nなんですかそれは？"

# カズマ
# 例えばそうだな。\nアクアがダクネスの格好や\nギルドの制服を着たりして、扮装を楽しむことだ。
368 = "例えばそうだな。\\nアクアがダクネスの格好や\\nギルドの制服を着たりして、扮装を楽しむことだ。"

# めぐみん
# よくわかりませんね。\nそれにどんな意味があるのです？
350 = "よくわかりませんね。\\nそれにどんな意味があるのです？"

# カズマ
# 人は誰しも変身願望があるもんだ。\n自分ではない誰かになってみたいって気持ち、\nめぐみんにも少なからずあるだろ？
364 = "人は誰しも変身願望があるもんだ。\\n自分ではない誰かになってみたいって気持ち、\\nめぐみんにも少なからずあるだろ？"

# めぐみん
# 確かにまあ、そうですね。\n否定はしませんが……。
403 = "確かにまあ、そうですね。\\n否定はしませんが……。"

# カズマ
# なんだよ、その目は。
332 = "なんだよ、その目は。"

# めぐみん
# これはカズマへのご褒美の筈なのに、\nどうして私の願望の達成を望むんですか。
292 = "これはカズマへのご褒美の筈なのに、\\nどうして私の願望の達成を望むんですか。"

# めぐみん
# 実に疑わしいです。
377 = "実に疑わしいです。"

# カズマ
# それは、俺にも得があるからに決まってるだろ。
311 = "それは、俺にも得があるからに決まってるだろ。"

# めぐみん
# はっ！　さては、いやらしい服を着させるつもりですね！
335 = "はっ！　さては、いやらしい服を着させるつもりですね！"

# カズマ
# 違うわ！\nめぐみんにはこれを着てもらう！
408 = "違うわ！\\nめぐみんにはこれを着てもらう！"

# めぐみん
# 見慣れない服ですね。\nなんですかこれは？
406 = "見慣れない服ですね。\\nなんですかこれは？"

# カズマ
# セーラー服だー。\n俺の生まれた国では\nもっとも愛されている服なんだぞ。
361 = "セーラー服だー。\\n俺の生まれた国では\\nもっとも愛されている服なんだぞ。"

# めぐみん
# 一見、普通の服にしか見えませんね。\nどうしてこれがもっとも愛されている服なのです？
362 = "一見、普通の服にしか見えませんね。\\nどうしてこれがもっとも愛されている服なのです？"

# カズマ
# それは……尊い女性が着る服だからかな？
310 = "それは……尊い女性が着る服だからかな？"

# めぐみん
# ふっふっふ。\nカズマもようやく、私という人間の価値を\n理解したようですね！
338 = "ふっふっふ。\\nカズマもようやく、私という人間の価値を\\n理解したようですね！"

# めぐみん
# そう、私は、紅魔族随一の天才と謳われる者。\nその衣服を着るのに相応しい人間と言えるでしょう！
303 = "そう、私は、紅魔族随一の天才と謳われる者。\\nその衣服を着るのに相応しい人間と言えるでしょう！"

# カズマ
# じゃあ、着てくれるのか！
297 = "じゃあ、着てくれるのか！"

# めぐみん
# ふふーん、当然です。
339 = "ふふーん、当然です。"

# カズマ
# おーい、めぐみーん、まだかー。
286 = "おーい、めぐみーん、まだかー。"

# めぐみん
# そんなに焦らせないで下さい。\n着慣れない服で苦戦をしているんです。
315 = "そんなに焦らせないで下さい。\\n着慣れない服で苦戦をしているんです。"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんのセーラー服姿か。\n　楽しみだなー）
415 = "（めぐみんのセーラー服姿か。\\n　楽しみだなー）"

# めぐみん
# こ、これで、いいんですよね？
289 = "こ、これで、いいんですよね？"

# カズマ（Ｍ）
# display as カズマ
# （おっ、着替え終わったか？）
412 = "（おっ、着替え終わったか？）"

# カズマ（Ｍ）
# display as カズマ
# （どれどれ、めぐみんのセーラー服姿を\n　存分に堪能させてもらうか）
414 = "（どれどれ、めぐみんのセーラー服姿を\\n　存分に堪能させてもらうか）"

# カズマ
# おー、なるほどなるほど、\nそうなるのか。
285 = "おー、なるほどなるほど、\\nそうなるのか。"

# めぐみん
# あまりジロジロ見ないでください、\n恥ずかしいではありませんか。
280 = "あまりジロジロ見ないでください、\\n恥ずかしいではありませんか。"

# カズマ
# せっかくのコスプレなんだ\n見ないと意味がないだろ？
301 = "せっかくのコスプレなんだ\\n見ないと意味がないだろ？"

# めぐみん
# それはそうですが、\nどうも着慣れていないせいか\n落ち着かなくて。
312 = "それはそうですが、\\nどうも着慣れていないせいか\\n落ち着かなくて。"

# めぐみん
# それで、あの、\nお、おかしくないですか？
308 = "それで、あの、\\nお、おかしくないですか？"

# カズマ
# スカートをもっと短くするべきだ！
360 = "スカートをもっと短くするべきだ！"

# めぐみん
# これ以上短くする理由がわかりませんよ！
293 = "これ以上短くする理由がわかりませんよ！"

# カズマ
# わかってないな、めぐみん。\nセーラー服を着こなすトップリーダーは\n短めに穿くんだぞ。
352 = "わかってないな、めぐみん。\\nセーラー服を着こなすトップリーダーは\\n短めに穿くんだぞ。"

# カズマ
# そうすることによって足が長く見えるらしいんだ。
305 = "そうすることによって足が長く見えるらしいんだ。"

# めぐみん
# それは素晴らしいですが、\nさすがに恥ずかしいですよ。
313 = "それは素晴らしいですが、\\nさすがに恥ずかしいですよ。"

# カズマ
# 何言ってんだよ、\nふだんはもっと短いの穿いてるじゃないか。
367 = "何言ってんだよ、\\nふだんはもっと短いの穿いてるじゃないか。"

# めぐみん
# 着慣れてる服は、\nこう、色々とさじ加減がわかるんですよ！
402 = "着慣れてる服は、\\nこう、色々とさじ加減がわかるんですよ！"

# カズマ
# ん？　どういうことだ？
353 = "ん？　どういうことだ？"

# めぐみん
# で、ですから、どれだけ動いて大丈夫だとか、\nそういう意味です。
322 = "で、ですから、どれだけ動いて大丈夫だとか、\\nそういう意味です。"

# カズマ
# ああ、つまり見えるのを気にしていると。
277 = "ああ、つまり見えるのを気にしていると。"

# めぐみん
# 言わないでください！\n本当にデリカシーがありませんね！
407 = "言わないでください！\\n本当にデリカシーがありませんね！"

# カズマ
# わ、悪かったよ。
351 = "わ、悪かったよ。"

# カズマ
# 悩殺的に可愛い！
381 = "悩殺的に可愛い！"

# めぐみん
# 本当ですか？\n本当に本当に本当に、そう思いますか？
383 = "本当ですか？\\n本当に本当に本当に、そう思いますか？"

# カズマ
# なんだよ、やけに疑うじゃないか。
333 = "なんだよ、やけに疑うじゃないか。"

# めぐみん
# カズマが私のことを手放しに褒めるなんて、\nまずありえませんからね。
357 = "カズマが私のことを手放しに褒めるなんて、\\nまずありえませんからね。"

# カズマ
# ずいぶん屈折してるな。
299 = "ずいぶん屈折してるな。"

# めぐみん
# そうさせたのはカズマではありませんか。\nもっと日頃から私を褒め称えてくれれば、\nこうはなりません。
304 = "そうさせたのはカズマではありませんか。\\nもっと日頃から私を褒め称えてくれれば、\\nこうはなりません。"

# カズマ
# 褒められるようなことを\nすればいいだけの話だろ。
405 = "褒められるようなことを\\nすればいいだけの話だろ。"

# めぐみん
# まるでいつもは褒められた行動を\n何もしていないかのような口ぶりですね？
342 = "まるでいつもは褒められた行動を\\n何もしていないかのような口ぶりですね？"

# カズマ
# まるでじゃないだろうが。
343 = "まるでじゃないだろうが。"

# めぐみん
# な、なにお！\nカズマは人を見る目がありませんね！
329 = "な、なにお！\\nカズマは人を見る目がありませんね！"

# カズマ
# じゃあ、今めぐみんを可愛いと思っている\nこの目も間違ってるってことになるな。
296 = "じゃあ、今めぐみんを可愛いと思っている\\nこの目も間違ってるってことになるな。"

# めぐみん
# それに関しては、\n曇りなき正しい判断だと言えるでしょう。
309 = "それに関しては、\\n曇りなき正しい判断だと言えるでしょう。"

# カズマ
# げんきんなやつめ。
287 = "げんきんなやつめ。"

# カズマ
# もっとしっかり見てみないと、わからないな。
348 = "もっとしっかり見てみないと、わからないな。"

# めぐみん
# ちょっ！\n人の前に屈んで何をするつもりですか！
320 = "ちょっ！\\n人の前に屈んで何をするつもりですか！"

# カズマ
# うん、スカートの長さは、うん、うん、\nまあこんなもんだろ。
283 = "うん、スカートの長さは、うん、うん、\\nまあこんなもんだろ。"

# めぐみん
# ひゃ！　太ももに息をかけないでくださいよ！
336 = "ひゃ！　太ももに息をかけないでくださいよ！"

# カズマ（Ｍ）
# display as カズマ
# （胸は、めぐみんに着させる時点で\n　期待はしてなかったし……）
416 = "（胸は、めぐみんに着させる時点で\\n　期待はしてなかったし……）"

# めぐみん
# あ、あの、ちょっと近すぎると思うのです。
275 = "あ、あの、ちょっと近すぎると思うのです。"

# カズマ（Ｍ）
# display as カズマ
# （うん、化粧っ気が無いのはいいな）
411 = "（うん、化粧っ気が無いのはいいな）"

# カズマ（Ｍ）
# display as カズマ
# （これでこそ、セーラー服の清楚さが\n　生きると言うものだ）
413 = "（これでこそ、セーラー服の清楚さが\\n　生きると言うものだ）"

# めぐみん
# あの、カズマ。\n黙っていられると、不安になるのですが。
278 = "あの、カズマ。\\n黙っていられると、不安になるのですが。"

# カズマ
# うん、いいんじゃないのか？
282 = "うん、いいんじゃないのか？"

# めぐみん
# え？　何がです？
284 = "え？　何がです？"

# カズマ
# だから、めぐみんのセーラー服姿がだよ。\n俺は好きだぞ。
318 = "だから、めぐみんのセーラー服姿がだよ。\\n俺は好きだぞ。"

# めぐみん
# そ、そう言ってくれるのは嬉しいのですが、\nちょっと照れくさいです。
302 = "そ、そう言ってくれるのは嬉しいのですが、\\nちょっと照れくさいです。"

# カズマ
# というわけで、これからずーっとセーラー服を\n着ていてくれ。
325 = "というわけで、これからずーっとセーラー服を\\n着ていてくれ。"

# めぐみん
# それは絶対にっ、嫌ですよ！
314 = "それは絶対にっ、嫌ですよ！"

# カズマ
# 即答かよ！
373 = "即答かよ！"

# めぐみん
# もう、いいですよね？\n満足したでしょう？
346 = "もう、いいですよね？\\n満足したでしょう？"

# カズマ
# まだだ！　むしろここからが本番だ！
341 = "まだだ！　むしろここからが本番だ！"

# めぐみん
# この上、何をしろというのです？
291 = "この上、何をしろというのです？"

# カズマ
# 俺に愛の告白をしてくれ！
371 = "俺に愛の告白をしてくれ！"

# めぐみん
# な、なななにを言ってるんですか！？\nカ、カズマに愛の告白をしろなどと、\nどういうつもりですか！？
328 = "な、なななにを言ってるんですか！？\\nカ、カズマに愛の告白をしろなどと、\\nどういうつもりですか！？"

# カズマ
# １度でいいから女の子から\n告白されたいんだよ！\n俺の夢を叶えてくれ！
417 = "１度でいいから女の子から\\n告白されたいんだよ！\\n俺の夢を叶えてくれ！"

# めぐみん
# 確かにカズマに告白しようなどと\n考える女の子はそうそういないでしょうね。
404 = "確かにカズマに告白しようなどと\\n考える女の子はそうそういないでしょうね。"

# カズマ
# 悔しいが反論できん！\nそんなわけだから頼む！
380 = "悔しいが反論できん！\\nそんなわけだから頼む！"

# めぐみん
# 頼むと言われましても、\nさすがに恥ずかしすぎますよ。
410 = "頼むと言われましても、\\nさすがに恥ずかしすぎますよ。"

# カズマ
# 心配するな、今のめぐみんは\nめぐみんであってめぐみんではない！
379 = "心配するな、今のめぐみんは\\nめぐみんであってめぐみんではない！"

# めぐみん
# では、なんだと言うのです。
323 = "では、なんだと言うのです。"

# カズマ
# 女子高生だ！\nいや、めぐみんだと女子中学生になるのか？
376 = "女子高生だ！\\nいや、めぐみんだと女子中学生になるのか？"

# めぐみん
# そんなの知りませんよ。
316 = "そんなの知りませんよ。"

# カズマ
# とにかく、セーラー服は学生が着る制服なんだ。
326 = "とにかく、セーラー服は学生が着る制服なんだ。"

# カズマ
# そして学生のメインイベントと言えば――
307 = "そして学生のメインイベントと言えば――"

# めぐみん
# こ、告白？
290 = "こ、告白？"

# カズマ
# さすがめぐみん！\n紅魔族随一の天才だけあって理解が早いな！
295 = "さすがめぐみん！\\n紅魔族随一の天才だけあって理解が早いな！"

# めぐみん
# ふっ、当然です。
337 = "ふっ、当然です。"

# カズマ
# さあ、来いめぐみん！\n感情を込めて、本当に好きな相手に\n告白するつもりで頼む！
294 = "さあ、来いめぐみん！\\n感情を込めて、本当に好きな相手に\\n告白するつもりで頼む！"

# めぐみん
# そう言われても告白などしたことないので、\n上手くできるかどうか。
306 = "そう言われても告白などしたことないので、\\n上手くできるかどうか。"

# カズマ
# 大丈夫だって、\n心に浮かんだ言葉をそのまま口に出せば。\n大切なのは気持ちなんだから！
375 = "大丈夫だって、\\n心に浮かんだ言葉をそのまま口に出せば。\\n大切なのは気持ちなんだから！"

# めぐみん
# 難しい注文を……。
409 = "難しい注文を……。"

# カズマ
# では、はい！
324 = "では、はい！"

# めぐみん
# カ、カズマ……
354 = "カ、カズマ……"

# カズマ
# なんだい、めぐみん？
331 = "なんだい、めぐみん？"

# めぐみん
# カズマ、実はあなたに\n告白しなければいけないことが\nあります。
356 = "カズマ、実はあなたに\\n告白しなければいけないことが\\nあります。"

# カズマ
# 俺に告白？　一体なんだろう。
370 = "俺に告白？　一体なんだろう。"

# めぐみん
# 普段は憎まれ口ばかり叩いていますが、\n本当に憎いわけではないのです。\nむしろその逆と言いますか……。
382 = "普段は憎まれ口ばかり叩いていますが、\\n本当に憎いわけではないのです。\\nむしろその逆と言いますか……。"

# めぐみん
# 気になる相手だからこそ\n口が出てしまうんです。
385 = "気になる相手だからこそ\\n口が出てしまうんです。"

# めぐみん
# 本当に嫌いな相手なら\n近づくことすらしません。
384 = "本当に嫌いな相手なら\\n近づくことすらしません。"

# カズマ
# つまり、どういうことなんだ？
321 = "つまり、どういうことなんだ？"

# めぐみん
# こ、ここまで言ってもわからないのですか？\n一体どこまであなたは鈍感なんです。
288 = "こ、ここまで言ってもわからないのですか？\\n一体どこまであなたは鈍感なんです。"

# めぐみん
# だから……そのつまり……、\n私は、カズマのことを……。
317 = "だから……そのつまり……、\\n私は、カズマのことを……。"

# カズマ
# 俺のことを？
372 = "俺のことを？"

# めぐみん
# す、好きだって言ってるんですよ。\nそれくらいわかってください！
298 = "す、好きだって言ってるんですよ。\\nそれくらいわかってください！"

# カズマ
# めぐみん……。
345 = "めぐみん……。"

# めぐみん
# あーーー、もう無理です！\nこれ以上は恥ずかしくて\n死んでしまいますよ！
281 = "あーーー、もう無理です！\\nこれ以上は恥ずかしくて\\n死んでしまいますよ！"

# カズマ
# 演技とは言え\n女の子からの告白はいいな……。
386 = "演技とは言え\\n女の子からの告白はいいな……。"

# カズマ
# ああ、こんな学生時代を過ごしたかった……。\n心の底からそう思えるよ……。
276 = "ああ、こんな学生時代を過ごしたかった……。\\n心の底からそう思えるよ……。"

# めぐみん
# ま、まさか泣いているのですか？
340 = "ま、まさか泣いているのですか？"

# カズマ
# ちょっと昔を振り返って虚しくなったんだよ。\nなんて灰色の青春だったんだろうって。
319 = "ちょっと昔を振り返って虚しくなったんだよ。\\nなんて灰色の青春だったんだろうって。"

# カズマ
# やばい……自分からお願いしておいて\n本気で悲しくなってきた。\nなんだこの虚無感は？
349 = "やばい……自分からお願いしておいて\\n本気で悲しくなってきた。\\nなんだこの虚無感は？"

# カズマ
# 俺、この先もずっとこうなのかな……？\nだとしたら、生きていく意味なんてあるのか？
369 = "俺、この先もずっとこうなのかな……？\\nだとしたら、生きていく意味なんてあるのか？"

# めぐみん
# な、何を言ってるんです！\n大丈夫ですよ、世界は広いんです。
330 = "な、何を言ってるんです！\\n大丈夫ですよ、世界は広いんです。"

# めぐみん
# どこかにカズマのことを好きになってくれる\n物好きはきっといます！
327 = "どこかにカズマのことを好きになってくれる\\n物好きはきっといます！"

# カズマ
# あはははは……、\n物好きにしか相手にされないんだな。
279 = "あはははは……、\\n物好きにしか相手にされないんだな。"

# めぐみん
# 今のは言葉のあやです！\nそんなに落ち込まないでくださいよ。
365 = "今のは言葉のあやです！\\nそんなに落ち込まないでくださいよ。"

# カズマ
# はぁ～……幸せになりたい。
334 = "はぁ～……幸せになりたい。"

[selections]
# 360 = "スカートをもっと短くするべきだ！"
# 381 = "悩殺的に可愛い！"
347 = "もっとしっかり見てみないと……"
