# rew_f07.txt.scn

[info]
151 = "rew_f07"

[characters]
229 = "カズマ（Ｍ）"
222 = "ウィズ"
226 = "カズマ"

[character_subs]
# 226 = "カズマ"

[script]
# lines: 68

# カズマ（Ｍ）
# display as カズマ
# （店の掃除とか、楽なお仕置きで良かったー。\n　ま、罰掃除とかある意味、お仕置きの定番だよな）
256 = "（店の掃除とか、楽なお仕置きで良かったー。\\n　ま、罰掃除とかある意味、お仕置きの定番だよな）"

# カズマ（Ｍ）
# display as カズマ
# （店自体も、ウィズの性格からしてそんなひどく\n　汚れてるとこも無いし、助かるぜ）
257 = "（店自体も、ウィズの性格からしてそんなひどく\\n　汚れてるとこも無いし、助かるぜ）"

# カズマ（Ｍ）
# display as カズマ
# （それにしてもウィズはどこ行ったんだ？\n　出掛けたわけじゃないから、店の中にいるん\n　だろうけど……）
250 = "（それにしてもウィズはどこ行ったんだ？\\n　出掛けたわけじゃないから、店の中にいるん\\n　だろうけど……）"

# ウィズ
# カズマさ～～ん！
228 = "カズマさ～～ん！"

# カズマ（Ｍ）
# display as カズマ
# （ん？　今なんか？）
255 = "（ん？　今なんか？）"

# ウィズ
# カズマさぁぁぁぁん！
227 = "カズマさぁぁぁぁん！"

# カズマ（Ｍ）
# display as カズマ
# （なんだなんだ？　どこからだ？　奥の方か？）
253 = "（なんだなんだ？　どこからだ？　奥の方か？）"

# カズマ（Ｍ）
# display as カズマ
# （なんかよくわからないが、行ってみよう）
252 = "（なんかよくわからないが、行ってみよう）"

# カズマ
# 尻だ。
234 = "尻だ。"

# ウィズ
# うぅぅ……。
182 = "うぅぅ……。"

# カズマ
# ウィズが尻だけになっちまった。
223 = "ウィズが尻だけになっちまった。"

# ウィズ
# 違いますよ～！
245 = "違いますよ～！"

# カズマ
# ええと……新手の遊びか？
185 = "ええと……新手の遊びか？"

# ウィズ
# それも違います。
201 = "それも違います。"

# カズマ
# とりあえず何が起こったのか説明してくれ。
206 = "とりあえず何が起こったのか説明してくれ。"

# ウィズ
# マジックアイテムを整理してたら、\nうっかり効果を発動させてしまって。
230 = "マジックアイテムを整理してたら、\\nうっかり効果を発動させてしまって。"

# カズマ
# それで尻だけになってしまったと！
198 = "それで尻だけになってしまったと！"

# ウィズ
# だから違います！\nテレポート効果で壁にはまっちゃったんですよ。
202 = "だから違います！\\nテレポート効果で壁にはまっちゃったんですよ。"

# カズマ
# なんてドジっ子。
210 = "なんてドジっ子。"

# ウィズ
# うう、お願いですから助けてくださーい。
183 = "うう、お願いですから助けてくださーい。"

# カズマ
# そりゃまあ、助けたいけど、\nどうすればいいんだこれ。
197 = "そりゃまあ、助けたいけど、\\nどうすればいいんだこれ。"

# ウィズ
# ええと、足を引っ張ってみてもらえませんか？
187 = "ええと、足を引っ張ってみてもらえませんか？"

# カズマ（Ｍ）
# display as カズマ
# （引っ張って抜けないだろ。\n　隙間が１ｍｍも無いんだし……）
258 = "（引っ張って抜けないだろ。\\n　隙間が１ｍｍも無いんだし……）"

# カズマ（Ｍ）
# display as カズマ
# （でも、まあ、ウィズが言うなら）
251 = "（でも、まあ、ウィズが言うなら）"

# カズマ
# んじゃ、引っ張るぞー。\nよいしょーーーーーー！！
220 = "んじゃ、引っ張るぞー。\\nよいしょーーーーーー！！"

# ウィズ
# きゃっ！　あっ、ダメっ、ダメですっ！！
193 = "きゃっ！　あっ、ダメっ、ダメですっ！！"

# カズマ
# ん？　どうした？
221 = "ん？　どうした？"

# ウィズ
# そ、その……む、胸が引っ掛かってしまって。
195 = "そ、その……む、胸が引っ掛かってしまって。"

# カズマ
# お、おう……。
191 = "お、おう……。"

# カズマ（Ｍ）
# display as カズマ
# （さすがピカイチの巨乳なウィズだけあるな。\n　ちょっと想像してしまって危なかったぞ）
249 = "（さすがピカイチの巨乳なウィズだけあるな。\\n　ちょっと想像してしまって危なかったぞ）"

# カズマ（Ｍ）
# display as カズマ
# （ん、待てよ）
254 = "（ん、待てよ）"

# カズマ
# 胸が引っかかったってことは動いたのか？
244 = "胸が引っかかったってことは動いたのか？"

# ウィズ
# あ、はい、マジックアイテムのテレポート効果は\n空間を歪ませる作用を使用しているらしく――
179 = "あ、はい、マジックアイテムのテレポート効果は\\n空間を歪ませる作用を使用しているらしく――"

# ウィズ
# まだ私の周りには、\n少しだけ空間の歪みが残っているんです。
214 = "まだ私の周りには、\\n少しだけ空間の歪みが残っているんです。"

# カズマ
# つまり動ける隙間みたいなもんがあると。
203 = "つまり動ける隙間みたいなもんがあると。"

# ウィズ
# 空間が完全に固定される前に\n壁から体を抜かないと私。
243 = "空間が完全に固定される前に\\n壁から体を抜かないと私。"

# カズマ
# 尻だけになってしまうと。
235 = "尻だけになってしまうと。"

# ウィズ
# なりませんってばー！
209 = "なりませんってばー！"

# カズマ
# でも引っ張ってダメって事は、\nどうすりゃいいんだ？
204 = "でも引っ張ってダメって事は、\\nどうすりゃいいんだ？"

# ウィズ
# それなら、逆に押してみて下さい。\nそっちの方が抜けやすいかもしれません。
199 = "それなら、逆に押してみて下さい。\\nそっちの方が抜けやすいかもしれません。"

# カズマ
# ん、わかった……って、ええええ！？
219 = "ん、わかった……って、ええええ！？"

# カズマ（Ｍ）
# display as カズマ
# （いや待て、押すと言っても……このウィズの体勢で\n　押せるところなんて……）
247 = "（いや待て、押すと言っても……このウィズの体勢で\\n　押せるところなんて……）"

# カズマ（Ｍ）
# display as カズマ
# （この目の前でふりふり揺れてる、おしりしかないん\n　だが……）
248 = "（この目の前でふりふり揺れてる、おしりしかないん\\n　だが……）"

# カズマ（Ｍ）
# display as カズマ
# （いやいや、さすがにそれはまずいだろ！？　押すの\n　自体も躊躇われるし、実際押したらきっとアウトな\n　展開が待ってる気がする）
246 = "（いやいや、さすがにそれはまずいだろ！？　押すの\\n　自体も躊躇われるし、実際押したらきっとアウトな\\n　展開が待ってる気がする）"

# ウィズ
# どうしたんですか、カズマさん？
207 = "どうしたんですか、カズマさん？"

# カズマ
# ええと……本当にいいのか？
186 = "ええと……本当にいいのか？"

# ウィズ
# はい、押してもらわないと、\n私、ここから出られないですし。
212 = "はい、押してもらわないと、\\n私、ここから出られないですし。"

# カズマ
# わかった。\nウィズがそう言うなら。\nでも、本当にいいのか？
217 = "わかった。\\nウィズがそう言うなら。\\nでも、本当にいいのか？"

# ウィズ
# はい、お願いします。
211 = "はい、お願いします。"

# カズマ
# わかった、じゃあ尻を押すぞ。
216 = "わかった、じゃあ尻を押すぞ。"

# カズマ
# ほ、ほらっ、あのカエルのネバネバがあれば、\n滑りが良くなって！　抜けやすくなるかも！
213 = "ほ、ほらっ、あのカエルのネバネバがあれば、\\n滑りが良くなって！　抜けやすくなるかも！"

# ウィズ
# えっ、ジャイアントトードのですか！？\nそ、そんなの今ここにありませんよ。
190 = "えっ、ジャイアントトードのですか！？\\nそ、そんなの今ここにありませんよ。"

# ウィズ
# それにあれ、ちょっと生臭い匂いが\n残っちゃうんですから、やめて下さい！
200 = "それにあれ、ちょっと生臭い匂いが\\n残っちゃうんですから、やめて下さい！"

# カズマ
# わかったよ。\nじゃあ、尻を押すからな。
218 = "わかったよ。\\nじゃあ、尻を押すからな。"

# カズマ
# いや、ここは素直に助けを呼んだ方が\nいいんじゃないかなって……。
181 = "いや、ここは素直に助けを呼んだ方が\\nいいんじゃないかなって……。"

# ウィズ
# えっ……だ、ダメですっ、こんなみっともない格好を\n他の人に見られちゃうなんて、耐えられません！
189 = "えっ……だ、ダメですっ、こんなみっともない格好を\\n他の人に見られちゃうなんて、耐えられません！"

# カズマ
# ……俺ならいいのか？
178 = "……俺ならいいのか？"

# ウィズ
# か、カズマさんは。\n嫌ですけど、いいです。
192 = "か、カズマさんは。\\n嫌ですけど、いいです。"

# カズマ
# どっちなんだ……。
208 = "どっちなんだ……。"

# ウィズ
# ともかく、他の人を呼ぶのは勘弁して下さい。
205 = "ともかく、他の人を呼ぶのは勘弁して下さい。"

# カズマ
# うーむ、わかった。\nじゃあ、お尻を押させて貰う！
184 = "うーむ、わかった。\\nじゃあ、お尻を押させて貰う！"

# ウィズ
# ええ！？　お尻！！
188 = "ええ！？　お尻！！"

# カズマ
# そりゃそうだろ。\n他にどこを押せって言うんだよ。
196 = "そりゃそうだろ。\\n他にどこを押せって言うんだよ。"

# ウィズ
# ままま、待ってください！\nお尻、お尻はダメですってば！
215 = "ままま、待ってください！\\nお尻、お尻はダメですってば！"

# カズマ
# あっ、こら暴れたら……！
180 = "あっ、こら暴れたら……！"

# カズマ
# ぐわっ！？　け、蹴りがモロに顔に……！？
194 = "ぐわっ！？　け、蹴りがモロに顔に……！？"

# ウィズ
# カ、カズマさんのエッチ！！
224 = "カ、カズマさんのエッチ！！"

# カズマ
# 俺のせいじゃねーだろ！
232 = "俺のせいじゃねーだろ！"

[selections]
236 = "本当にいいのか？"
225 = "カエルのネバネバがあれば滑りがよくなって！"
233 = "助けを呼んだ方がいいんじゃ"
