# rew_e08.txt.scn

[info]
173 = "rew_e08"

[characters]
243 = "ゆんゆん"
252 = "カズマ"
255 = "カズマ（Ｍ）"

[character_subs]
# 252 = "カズマ"

[script]
# lines: 79

# ゆんゆん
# カズマさん！　お仕置きを考えてきました！
254 = "カズマさん！　お仕置きを考えてきました！"

# カズマ
# お、おう……。
224 = "お、おう……。"

# カズマ（Ｍ）
# display as カズマ
# （どうしてこんなにノリノリなんだ）
297 = "（どうしてこんなにノリノリなんだ）"

# カズマ（Ｍ）
# display as カズマ
# （まさかアクアに\n　なにか入れ知恵をされたのか？）
299 = "（まさかアクアに\\n　なにか入れ知恵をされたのか？）"

# カズマ（Ｍ）
# display as カズマ
# （あり得る……むしろ、その線が濃厚だ。\n　でなければ心優しいゆんゆんが、\n　積極的にお仕置きなんて考えるはずがない）
288 = "（あり得る……むしろ、その線が濃厚だ。\\n　でなければ心優しいゆんゆんが、\\n　積極的にお仕置きなんて考えるはずがない）"

# カズマ（Ｍ）
# display as カズマ
# （あの駄女神は、本当ロクなことしないな！）
287 = "（あの駄女神は、本当ロクなことしないな！）"

# ゆんゆん
# …………。
208 = "…………。"

# カズマ
# え、え～と、それでお仕置きって？
221 = "え、え～と、それでお仕置きって？"

# ゆんゆん
# あの、それなんですけど、ええと、その。
213 = "あの、それなんですけど、ええと、その。"

# カズマ
# うん、なんだ？
219 = "うん、なんだ？"

# ゆんゆん
# …………。
# 208 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （どうした、なぜ何も言わない？\n　モジモジと指を絡ませながら\n　上目遣いで見つめたりして……）
296 = "（どうした、なぜ何も言わない？\\n　モジモジと指を絡ませながら\\n　上目遣いで見つめたりして……）"

# カズマ（Ｍ）
# display as カズマ
# （この感じ……\n　もしかしてアクアは関係ないのか？\n　でもだとしたら……？）
290 = "（この感じ……\\n　もしかしてアクアは関係ないのか？\\n　でもだとしたら……？）"

# カズマ
# え～と……話してくれないと、\n俺は何もすることができないんだが？
223 = "え～と……話してくれないと、\\n俺は何もすることができないんだが？"

# ゆんゆん
# あ、あの……もし嫌なら断ってくれても\nいいんですけど。
209 = "あ、あの……もし嫌なら断ってくれても\\nいいんですけど。"

# ゆんゆん
# …………。
# 208 = "…………。"

# カズマ
# ゆんゆん？
245 = "ゆんゆん？"

# ゆんゆん
# わ、私がお願いしたいことは。
247 = "わ、私がお願いしたいことは。"

# カズマ
# お願いしたいことは？
225 = "お願いしたいことは？"

# ゆんゆん
# ね、眠くなるまで手を握っていてもらえませんか？
238 = "ね、眠くなるまで手を握っていてもらえませんか？"

# カズマ
# それがお仕置きなのか？
231 = "それがお仕置きなのか？"

# ゆんゆん
# あっ、やっぱりダメですよね！\nす、すみません……おかしなことを言って。
211 = "あっ、やっぱりダメですよね！\\nす、すみません……おかしなことを言って。"

# カズマ
# ダメってことはないけど、\n全然お仕置きじゃないなって思っただけだよ。
257 = "ダメってことはないけど、\\n全然お仕置きじゃないなって思っただけだよ。"

# カズマ
# でも、ゆんゆんの願いは叶えてあげないとな。
235 = "でも、ゆんゆんの願いは叶えてあげないとな。"

# ゆんゆん
# いいんですか？
216 = "いいんですか？"

# カズマ
# もちろんだ。\nお仕置きされるよりそっちの方がありがたいし。
241 = "もちろんだ。\\nお仕置きされるよりそっちの方がありがたいし。"

# ゆんゆん
# そ、それでは、よ、よろしくお願いします！
229 = "そ、それでは、よ、よろしくお願いします！"

# ゆんゆん
# カズマさんの手、やっぱり大きいですね。
253 = "カズマさんの手、やっぱり大きいですね。"

# カズマ
# それを言うなら、\nゆんゆんの手が小さいんだよ。
233 = "それを言うなら、\\nゆんゆんの手が小さいんだよ。"

# ゆんゆん
# えへへ、１つ願いが叶っちゃいました。
222 = "えへへ、１つ願いが叶っちゃいました。"

# カズマ
# なんてささやかな願いなんだ。\nもっと凄いことを願えばいいものを。
237 = "なんてささやかな願いなんだ。\\nもっと凄いことを願えばいいものを。"

# ゆんゆん
# 私にとっては\n十分凄い願いなんです。
284 = "私にとっては\\n十分凄い願いなんです。"

# ゆんゆん
# うふふ、嬉しい。\nいい夢が見られそうです。
218 = "うふふ、嬉しい。\\nいい夢が見られそうです。"

# カズマ
# 満足そうで何よりだ。
266 = "満足そうで何よりだ。"

# ゆんゆん
# はい、大満足です。\nお願いしてよかった……。\nありがとうございます。
239 = "はい、大満足です。\\nお願いしてよかった……。\\nありがとうございます。"

# カズマ
# 何回もお礼しなくていいって。
259 = "何回もお礼しなくていいって。"

# カズマ（Ｍ）
# display as カズマ
# （人肌を求めるなんて、\n　もしかしたら\n　寂しがり屋なのかもしれないな）
304 = "（人肌を求めるなんて、\\n　もしかしたら\\n　寂しがり屋なのかもしれないな）"

# カズマ（Ｍ）
# display as カズマ
# （それならもっと喜ばせてあげたい。\n　そんな風に思うもんだろ？）
293 = "（それならもっと喜ばせてあげたい。\\n　そんな風に思うもんだろ？）"

# カズマ（Ｍ）
# display as カズマ
# （俺が、ゆんゆんに\n　してあげられることは――）
305 = "（俺が、ゆんゆんに\\n　してあげられることは――）"

# カズマ（Ｍ）
# display as カズマ
# （よし、頭をなでてあげよう）
301 = "（よし、頭をなでてあげよう）"

# ゆんゆん
# あっ！？
212 = "あっ！？"

# カズマ
# 悪い、もしかして頭を撫でられるの嫌だったか？
264 = "悪い、もしかして頭を撫でられるの嫌だったか？"

# ゆんゆん
# いいえ、少し驚いただけです。\nそのまま続けてください。
215 = "いいえ、少し驚いただけです。\\nそのまま続けてください。"

# カズマ
# わかった。\nよしよし、いい子いい子。
248 = "わかった。\\nよしよし、いい子いい子。"

# ゆんゆん
# んぅぅ、なんだかトロンってなっちゃいます。
249 = "んぅぅ、なんだかトロンってなっちゃいます。"

# カズマ
# 眠くなるまでこうしててあげるからな。
283 = "眠くなるまでこうしててあげるからな。"

# ゆんゆん
# 嬉しい……ありがとうございます。
262 = "嬉しい……ありがとうございます。"

# カズマ
# だからお礼はいいって。
234 = "だからお礼はいいって。"

# ゆんゆん
# それでも……、\nありがとうございます。
232 = "それでも……、\\nありがとうございます。"

# カズマ
# いえいえ、\nどういたしまして。
217 = "いえいえ、\\nどういたしまして。"

# カズマ（Ｍ）
# display as カズマ
# （もっと側に行ってあげよう）
300 = "（もっと側に行ってあげよう）"

# カズマ
# よっと。
246 = "よっと。"

# ゆんゆん
# カ、カズマさん、あ、あのぉ。
251 = "カ、カズマさん、あ、あのぉ。"

# カズマ
# なんだい、ゆんゆん？
236 = "なんだい、ゆんゆん？"

# ゆんゆん
# い、いえ、ちょっと近すぎるかなって。
214 = "い、いえ、ちょっと近すぎるかなって。"

# カズマ
# 俺のことなら気にしなくていい。
260 = "俺のことなら気にしなくていい。"

# ゆんゆん
# む、無理です。\n気になって仕方がありません。
240 = "む、無理です。\\n気になって仕方がありません。"

# カズマ
# そうか、よかれと思ったんだが。
230 = "そうか、よかれと思ったんだが。"

# ゆんゆん
# す、すみません。
228 = "す、すみません。"

# カズマ（Ｍ）
# display as カズマ
# （人肌が恋しいなら、\n　もっと感じさせてあげようじゃないか、\n　ここは肩を抱いて）
303 = "（人肌が恋しいなら、\\n　もっと感じさせてあげようじゃないか、\\n　ここは肩を抱いて）"

# ゆんゆん
# カ、カズマさん、あ、あのぉ。
# 251 = "カ、カズマさん、あ、あのぉ。"

# カズマ
# なんだい、ゆんゆん？
# 236 = "なんだい、ゆんゆん？"

# ゆんゆん
# 一体、何をしよとしているんですか？
258 = "一体、何をしよとしているんですか？"

# カズマ
# ゆんゆんが寝付くまで\n肩を抱いていてあげようかなって思ってさ。
244 = "ゆんゆんが寝付くまで\\n肩を抱いていてあげようかなって思ってさ。"

# ゆんゆん
# え、ええと、あの。
220 = "え、ええと、あの。"

# カズマ
# あっ、もしかしてやり過ぎか？
210 = "あっ、もしかしてやり過ぎか？"

# ゆんゆん
# して欲しいなって気持ちはちょっとあるんですけど、\nやっぱり恥ずかしくて……。
227 = "して欲しいなって気持ちはちょっとあるんですけど、\\nやっぱり恥ずかしくて……。"

# ゆんゆん
# ごめんなさい。
226 = "ごめんなさい。"

# カズマ（Ｍ）
# display as カズマ
# （しかしよくよく考えたら、\n　これって凄い状況なんじゃないのか！？）
292 = "（しかしよくよく考えたら、\\n　これって凄い状況なんじゃないのか！？）"

# カズマ（Ｍ）
# display as カズマ
# （ベッドに座って美少女の手を握るなんて、\n　少し前の俺には考えられんリア充ぶりだ！）
302 = "（ベッドに座って美少女の手を握るなんて、\\n　少し前の俺には考えられんリア充ぶりだ！）"

# ゆんゆん
# んっ、んん……。
250 = "んっ、んん……。"

# カズマ（Ｍ）
# display as カズマ
# （あー、言っておくが馬小屋での\n　アクアの寝顔はカウントに含まれない、\n　あんなときめかないもんはノーカウントだ）
289 = "（あー、言っておくが馬小屋での\\n　アクアの寝顔はカウントに含まれない、\\n　あんなときめかないもんはノーカウントだ）"

# カズマ（Ｍ）
# display as カズマ
# （って、誰に言ってるんだ俺？）
295 = "（って、誰に言ってるんだ俺？）"

# ゆんゆん
# スー……スー……、\nんぅぅ～……。
256 = "スー……スー……、\\nんぅぅ～……。"

# カズマ（Ｍ）
# display as カズマ
# （あ、あれ？　寝ちゃったのか）
286 = "（あ、あれ？　寝ちゃったのか）"

# カズマ（Ｍ）
# display as カズマ
# （なんて寝付きの良さだ。\n　それだけ安心してくれてるってことか？）
298 = "（なんて寝付きの良さだ。\\n　それだけ安心してくれてるってことか？）"

# カズマ（Ｍ）
# display as カズマ
# （しかし……なんて素晴らしい光景なんだ。\n　にも関わらず手を出せないとは……）
291 = "（しかし……なんて素晴らしい光景なんだ。\\n　にも関わらず手を出せないとは……）"

# カズマ（Ｍ）
# display as カズマ
# （寝込みを襲うのは\n　紳士のすることじゃないからな！）
306 = "（寝込みを襲うのは\\n　紳士のすることじゃないからな！）"

# カズマ（Ｍ）
# display as カズマ
# （だが、しかし……\n　ぐぉ～、悶々とする！！）
294 = "（だが、しかし……\\n　ぐぉ～、悶々とする！！）"

[selections]
285 = "頭をなでてあげよう"
242 = "もっと側に行ってあげよう"
265 = "添い寝をしてあげよう"
