# rew_d06.txt.scn

[info]
258 = "rew_d06"

[characters]
368 = "クリス"
365 = "カズマ"
367 = "カズマ（Ｍ）"

[character_subs]
# 365 = "カズマ"

[script]
# lines: 113

# クリス
# さて、お仕置きだけど。\nスキルの練習台になってもらおうかな。
320 = "さて、お仕置きだけど。\\nスキルの練習台になってもらおうかな。"

# カズマ
# おい、嫌な予感しかしないぞ。
308 = "おい、嫌な予感しかしないぞ。"

# クリス
# 別に危険なことはないよ。\nあたしの持ってるスキルなんてたかが知れてるし。
375 = "別に危険なことはないよ。\\nあたしの持ってるスキルなんてたかが知れてるし。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、クリスは盗賊だもんな。\n　戦闘職に比べたら安全と言えば安全か……）
434 = "（まあ、クリスは盗賊だもんな。\\n　戦闘職に比べたら安全と言えば安全か……）"

# クリス
# じゃあ、まずは投擲スキルから行こうかな。\nそこに立ってくれる？　ダガーを投げるからさ。
323 = "じゃあ、まずは投擲スキルから行こうかな。\\nそこに立ってくれる？　ダガーを投げるからさ。"

# カズマ
# って、めちゃくちゃ危険じゃねーか！
345 = "って、めちゃくちゃ危険じゃねーか！"

# クリス
# あはははは、冗談冗談。\nいくらお仕置きでもダガーを投げつけたり\nしないって。
294 = "あはははは、冗談冗談。\\nいくらお仕置きでもダガーを投げつけたり\\nしないって。"

# カズマ
# だったらなんのスキルの練習台に\nするつもりなんだよ。
340 = "だったらなんのスキルの練習台に\\nするつもりなんだよ。"

# クリス
# そうだねー、スティールはどうかな。\nこれなら安全だし。
329 = "そうだねー、スティールはどうかな。\\nこれなら安全だし。"

# カズマ
# ははーん、魂胆が読めたぞ。\nまた、財布を盗るつもりなんだろう。
356 = "ははーん、魂胆が読めたぞ。\\nまた、財布を盗るつもりなんだろう。"

# クリス
# それは言わないで。\n思い出したくない過去の一つなんだからさ。
337 = "それは言わないで。\\n思い出したくない過去の一つなんだからさ。"

# カズマ（Ｍ）
# display as カズマ
# （思い出したくない過去？）
439 = "（思い出したくない過去？）"

# カズマ
# ああ、パンツか。
284 = "ああ、パンツか。"

# クリス
# い、言わないでったら！
298 = "い、言わないでったら！"

# クリス
# もう、キミはそういうところいじわるだよね。
360 = "もう、キミはそういうところいじわるだよね。"

# カズマ
# それで？　なんでスティールの練習なんだ？
335 = "それで？　なんでスティールの練習なんだ？"

# クリス
# うん、試しにスキルレベル上げてみたんだよ。\nそれで、どれくらい精度が向上したか\n確認したくってさ。
301 = "うん、試しにスキルレベル上げてみたんだよ。\\nそれで、どれくらい精度が向上したか\\n確認したくってさ。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、なるほどそれで俺を練習台に）
430 = "（ああ、なるほどそれで俺を練習台に）"

# カズマ（Ｍ）
# display as カズマ
# （確かに俺が相手ならレベル差を\n　気にする必要ないし最適かもな）
440 = "（確かに俺が相手ならレベル差を\\n　気にする必要ないし最適かもな）"

# クリス
# お願いできるよね？
317 = "お願いできるよね？"

# カズマ
# おう、何度でも構わないぞ。
313 = "おう、何度でも構わないぞ。"

# クリス
# じゃあ、さっそく！\nスティール！
322 = "じゃあ、さっそく！\\nスティール！"

# カズマ
# あっ、財布！
290 = "あっ、財布！"

# クリス
# おっ、当たりだね。\nよーし、もういっちょ行くよ。\nスティールッ！
315 = "おっ、当たりだね。\\nよーし、もういっちょ行くよ。\\nスティールッ！"

# カズマ
# ああっ、今度は短刀がっ！
285 = "ああっ、今度は短刀がっ！"

# クリス
# うんうん、いい精度だね。
302 = "うんうん、いい精度だね。"

# カズマ
# よし、次は俺が指定した物を盗ってみてくれよ。
363 = "よし、次は俺が指定した物を盗ってみてくれよ。"

# クリス
# あっ、それはちょっと面白い試みかも。
287 = "あっ、それはちょっと面白い試みかも。"

# カズマ
# じゃあ、パンツで。
324 = "じゃあ、パンツで。"

# クリス
# え！？
306 = "え！？"

# カズマ
# 俺のパンツを盗ってみるんだ！\nさあさあ！
374 = "俺のパンツを盗ってみるんだ！\\nさあさあ！"

# クリス
# ええ！！　い、嫌だよ！　絶対にしないからね！
305 = "ええ！！　い、嫌だよ！　絶対にしないからね！"

# クリス
# 何が悲しくて、わざわざ汚い物に率先して\n触れないといけないのさ！
371 = "何が悲しくて、わざわざ汚い物に率先して\\n触れないといけないのさ！"

# カズマ
# な、なんだとー、ちゃんと毎日取り替えて\nるんだからな！
352 = "な、なんだとー、ちゃんと毎日取り替えて\\nるんだからな！"

# クリス
# そんなの普通でしょ！\n偉ぶって言うことじゃないってば！
338 = "そんなの普通でしょ！\\n偉ぶって言うことじゃないってば！"

# クリス
# それとも何？\nもしかしてそういう趣味なの……。
336 = "それとも何？\\nもしかしてそういう趣味なの……。"

# カズマ
# ね、ねーよ！
354 = "ね、ねーよ！"

# クリス
# ふーん、本当かなぁ。
358 = "ふーん、本当かなぁ。"

# カズマ（Ｍ）
# display as カズマ
# （くそ、余計な事言わなきゃよかった）
431 = "（くそ、余計な事言わなきゃよかった）"

# クリス
# はい、お財布と短刀は返しておくよ。
355 = "はい、お財布と短刀は返しておくよ。"

# クリス
# これにかこつけて、また盗まれるのは嫌だから。
318 = "これにかこつけて、また盗まれるのは嫌だから。"

# カズマ
# だから盗まねーって！\n一応弁解しておくけど、\nあれも狙って盗ったわけじゃねーからな！
339 = "だから盗まねーって！\\n一応弁解しておくけど、\\nあれも狙って盗ったわけじゃねーからな！"

# クリス
# それ、あたしちょっと疑わしいって思ってるんだ。
333 = "それ、あたしちょっと疑わしいって思ってるんだ。"

# カズマ
# おいおい、あの時のスティールって\nスキルレベル１だぞ。
309 = "おいおい、あの時のスティールって\\nスキルレベル１だぞ。"

# カズマ
# それで狙った物が盗れないのはクリスも\nわかってるだろ。
334 = "それで狙った物が盗れないのはクリスも\\nわかってるだろ。"

# クリス
# スティールの成功率を上げる要素は３つある。\nキミもそれが何かわかってると思うけど？
370 = "スティールの成功率を上げる要素は３つある。\\nキミもそれが何かわかってると思うけど？"

# カズマ
# あ、ああ、スキルレベルに対象とのレベル差、\nあとは個人の幸運値か。
282 = "あ、ああ、スキルレベルに対象とのレベル差、\\nあとは個人の幸運値か。"

# クリス
# カズマは確か、幸運値がずば抜けて高いんだよね。
366 = "カズマは確か、幸運値がずば抜けて高いんだよね。"

# カズマ
# そうだけど、普通いきなりパンツを\n狙うと思うか？
327 = "そうだけど、普通いきなりパンツを\\n狙うと思うか？"

# クリス
# 普通はね。\nでもキミは――
382 = "普通はね。\\nでもキミは――"

# カズマ
# いやいや俺って結構常識人だよ！\n女の子のパンツは好きだけどさ。
299 = "いやいや俺って結構常識人だよ！\\n女の子のパンツは好きだけどさ。"

# クリス
# あはは、最後の一言は余計だと思うな。
293 = "あはは、最後の一言は余計だと思うな。"

# クリス
# でーも、素敵な自己紹介だったよ。\nパンツ好きのカズマさん。
348 = "でーも、素敵な自己紹介だったよ。\\nパンツ好きのカズマさん。"

# カズマ
# そういう受け取り方は勘弁してくれ！
325 = "そういう受け取り方は勘弁してくれ！"

# クリス
# あはは、ごめんごめん。
291 = "あはは、ごめんごめん。"

# カズマ（Ｍ）
# display as カズマ
# （くそぉ、なんとかやり返したいけど……）
432 = "（くそぉ、なんとかやり返したいけど……）"

# カズマ（Ｍ）
# display as カズマ
# （クリスが嫌がりそうなことか……）
435 = "（クリスが嫌がりそうなことか……）"

# カズマ
# あれ？
296 = "あれ？"

# クリス
# ん、どうかした？
364 = "ん、どうかした？"

# カズマ（Ｍ）
# display as カズマ
# （俺って実はクリスのことを何も知らなくないか？）
436 = "（俺って実はクリスのことを何も知らなくないか？）"

# クリス
# 何ジッと見てるの。\nもしかしてまた狙ってる？
372 = "何ジッと見てるの。\\nもしかしてまた狙ってる？"

# カズマ
# ちっがうわっ！
342 = "ちっがうわっ！"

# カズマ（Ｍ）
# display as カズマ
# （個人的なことを聞いてもはぐらかされそうだし、\n　それなら――）
437 = "（個人的なことを聞いてもはぐらかされそうだし、\\n　それなら――）"

# カズマ
# そうやって異性のハートを盗んできたんだな？
331 = "そうやって異性のハートを盗んできたんだな？"

# カズマ
# おいおい、今まで何人の男をたぶらかしてきたんだ。\nほれほれ、素直に言ってみろ。
310 = "おいおい、今まで何人の男をたぶらかしてきたんだ。\\nほれほれ、素直に言ってみろ。"

# クリス
# そう言うカズマはどれくらい女の子のハートを\n盗んできたのかな？
332 = "そう言うカズマはどれくらい女の子のハートを\\n盗んできたのかな？"

# カズマ
# さりげなく痛いところ突いてくるなよ。
321 = "さりげなく痛いところ突いてくるなよ。"

# クリス
# あたしの話を聞きたいなら、\n自分のことからまず言わなきゃ。
286 = "あたしの話を聞きたいなら、\\n自分のことからまず言わなきゃ。"

# クリス
# 包み隠さずにね。
378 = "包み隠さずにね。"

# カズマ
# お、俺のことはいいだろ、別に。
307 = "お、俺のことはいいだろ、別に。"

# クリス
# もしかして、女の子と付き合ったことない？\nでもさ、手を繋ぐとか、その程度ならしたことある\nでしょ？
362 = "もしかして、女の子と付き合ったことない？\\nでもさ、手を繋ぐとか、その程度ならしたことある\\nでしょ？"

# カズマ（Ｍ）
# display as カズマ
# （こ、こいつ、的確に人の痛いところを\n　突いてきやがる！）
433 = "（こ、こいつ、的確に人の痛いところを\\n　突いてきやがる！）"

# クリス
# あっ、幼少期にっていうのは認めないからね。
289 = "あっ、幼少期にっていうのは認めないからね。"

# カズマ（Ｍ）
# display as カズマ
# （唯一の退路まで断つとか、こいつは鬼か！）
438 = "（唯一の退路まで断つとか、こいつは鬼か！）"

# クリス
# うーん、キミが教えてくれないなら、\nあたしも言えないな。
303 = "うーん、キミが教えてくれないなら、\\nあたしも言えないな。"

# カズマ
# クリスって意地悪だよね！
369 = "クリスって意地悪だよね！"

# カズマ
# これまでで盗んだもっとも高価な物ってなんだ？
319 = "これまでで盗んだもっとも高価な物ってなんだ？"

# クリス
# 高価な物ねぇ。\nあたしが盗む物は大きく分けて２つあるんだ。
429 = "高価な物ねぇ。\\nあたしが盗む物は大きく分けて２つあるんだ。"

# クリス
# １つはモンスターから盗むアイテム。\nダンジョンとかで手に入れるやつだね。
441 = "１つはモンスターから盗むアイテム。\\nダンジョンとかで手に入れるやつだね。"

# クリス
# もう１つは依頼されて盗む物。\nこれに関しては、深く追求しないで欲しいかな。
361 = "もう１つは依頼されて盗む物。\\nこれに関しては、深く追求しないで欲しいかな。"

# カズマ
# おう、わかってるよ。
311 = "おう、わかってるよ。"

# クリス
# 前者はともかく、後者は個人の価値観に\n大きく依存してる物が多いんだ。
376 = "前者はともかく、後者は個人の価値観に\\n大きく依存してる物が多いんだ。"

# クリス
# 実際、二束三文程度の価値しかない物だけど、\n当人からしてみたら命に替えても手に入れたいと\n願う物とかね。
380 = "実際、二束三文程度の価値しかない物だけど、\\n当人からしてみたら命に替えても手に入れたいと\\n願う物とかね。"

# カズマ
# うん、なるほど。\n少しだけクリスのことがわかったような気がする。
300 = "うん、なるほど。\\n少しだけクリスのことがわかったような気がする。"

# クリス
# あれ、もしかしてそういう狙いだった？
295 = "あれ、もしかしてそういう狙いだった？"

# カズマ
# 鎌をかけたりして悪かったな。\nでもほら、話しをしてる相手を何も知らないって\n寂しいじゃん。
427 = "鎌をかけたりして悪かったな。\\nでもほら、話しをしてる相手を何も知らないって\\n寂しいじゃん。"

# クリス
# ちょっとー、あたしもキミのことは\n何も知らないけど？
344 = "ちょっとー、あたしもキミのことは\\n何も知らないけど？"

# カズマ
# え、そうなの？
304 = "え、そうなの？"

# クリス
# あ、訂正。１つだけ知ってる。\n女の子のパンツが好き、そうだよね？
283 = "あ、訂正。１つだけ知ってる。\\n女の子のパンツが好き、そうだよね？"

# カズマ
# そうだけどさ、そういう覚え方はやめてくれる。
328 = "そうだけどさ、そういう覚え方はやめてくれる。"

# カズマ
# どうして盗賊になったんだ？
351 = "どうして盗賊になったんだ？"

# クリス
# どういうこと？
349 = "どういうこと？"

# カズマ
# だって、盗賊ってあまり選ぶやついないじゃん。
341 = "だって、盗賊ってあまり選ぶやついないじゃん。"

# クリス
# 確かに前衛職とか他の職業に比べて\n地味なスキルが多いしね。
426 = "確かに前衛職とか他の職業に比べて\\n地味なスキルが多いしね。"

# クリス
# でも、あたしは華やかな職業よりも\n縁の下の力持ちみたいな職業の方が性にあってると\n思ったんだ。
346 = "でも、あたしは華やかな職業よりも\\n縁の下の力持ちみたいな職業の方が性にあってると\\n思ったんだ。"

# カズマ
# 確かに、誰かをサポートするのとか\n向いてそうだもんな。
425 = "確かに、誰かをサポートするのとか\\n向いてそうだもんな。"

# クリス
# どうしてそう思うの？
350 = "どうしてそう思うの？"

# カズマ
# お前ってなんだかんだで世話好きじゃん。
316 = "お前ってなんだかんだで世話好きじゃん。"

# カズマ
# 俺にスティールスキルの習得を勧めてみたり、\nあのドＭクルセイダーと友達になってみたりさ。
373 = "俺にスティールスキルの習得を勧めてみたり、\\nあのドＭクルセイダーと友達になってみたりさ。"

# クリス
# 前者はキミが向いてると思ったから。\n後者は気が合いそうだと思ったから、それだけだよ。
377 = "前者はキミが向いてると思ったから。\\n後者は気が合いそうだと思ったから、それだけだよ。"

# カズマ
# でもそれって相手をよく観察してるって\nことだよな。
347 = "でもそれって相手をよく観察してるって\\nことだよな。"

# カズマ
# 相手が好きなこと、嫌がることを知らなきゃ\n世話って空回りするもんだと思うし――
424 = "相手が好きなこと、嫌がることを知らなきゃ\\n世話って空回りするもんだと思うし――"

# カズマ
# そういう部分を自然に見つけられるクリスは\n人を思う優しさってものが――
326 = "そういう部分を自然に見つけられるクリスは\\n人を思う優しさってものが――"

# クリス
# あー、もう、わかったからそれ以上言わないで！
297 = "あー、もう、わかったからそれ以上言わないで！"

# クリス
# 顔が熱くなってきちゃったじゃないか、もう。
428 = "顔が熱くなってきちゃったじゃないか、もう。"

# カズマ
# おっ、クリスの新しい一面を発見！
314 = "おっ、クリスの新しい一面を発見！"

# クリス
# な、何それ！？
353 = "な、何それ！？"

# カズマ
# ふむふむ、クリスは思った以上の照れ屋さんっと。
357 = "ふむふむ、クリスは思った以上の照れ屋さんっと。"

# クリス
# あっ、もしかして観察日記的な物？\nそういうのどうかと思うよ。
288 = "あっ、もしかして観察日記的な物？\\nそういうのどうかと思うよ。"

# カズマ
# ちっがうわ！
343 = "ちっがうわ！"

# クリス
# あはは、じゃあそろそろスキルの練習を\n再開しようか。
292 = "あはは、じゃあそろそろスキルの練習を\\n再開しようか。"

# カズマ
# おう、パンツでもなんでも盗んでくれ！
312 = "おう、パンツでもなんでも盗んでくれ！"

# クリス
# もう、そういう物は盗らないってばっ！
359 = "もう、そういう物は盗らないってばっ！"

[selections]
330 = "そうやって異性のハートを盗んできたんだな"
# 319 = "これまでで盗んだもっとも高価な物ってなんだ？"
# 351 = "どうして盗賊になったんだ？"
