# rew_b02.txt.scn

[info]
226 = "rew_b02"

[characters]
298 = "めぐみん"
305 = "カズマ"
307 = "カズマ（Ｍ）"

[character_subs]
# 305 = "カズマ"

[script]
# lines: 94

# めぐみん
# なんですかこの破廉恥な格好は！？
290 = "なんですかこの破廉恥な格好は！？"

# カズマ
# なんだ水着も知らないのか？
288 = "なんだ水着も知らないのか？"

# めぐみん
# そうではなく、\nなぜ私がこのような格好をしなければ\nいけないのかと聞いているのです！
269 = "そうではなく、\\nなぜ私がこのような格好をしなければ\\nいけないのかと聞いているのです！"

# カズマ
# そりゃ、俺へのご褒美だからだろ。
273 = "そりゃ、俺へのご褒美だからだろ。"

# めぐみん
# わかってはいましたが\nどこまで欲望に忠実なんですか、あなたは。
303 = "わかってはいましたが\\nどこまで欲望に忠実なんですか、あなたは。"

# カズマ
# 俺はやりたいことは無理に我慢しないことに\nしてるんだよ。
315 = "俺はやりたいことは無理に我慢しないことに\\nしてるんだよ。"

# めぐみん
# まさに欲望の権化。\n若き乙女にこんな格好をさせて\n一体何をさせるつもりですか！！
296 = "まさに欲望の権化。\\n若き乙女にこんな格好をさせて\\n一体何をさせるつもりですか！！"

# めぐみん
# はっ、まさか……\n卑猥極まりない真似をしようというのでは\nないでしょうね！？
294 = "はっ、まさか……\\n卑猥極まりない真似をしようというのでは\\nないでしょうね！？"

# めぐみん
# いくら私が魅力的だからといって\nそうはさせませんよ！
259 = "いくら私が魅力的だからといって\\nそうはさせませんよ！"

# カズマ
# ん～～～……。
304 = "ん～～～……。"

# めぐみん
# なんですか人のことをジロジロ見て！？\n品定めですか！？
291 = "なんですか人のことをジロジロ見て！？\\n品定めですか！？"

# めぐみん
# それとも私をどう弄ぼうか、\nそのいやらしい頭の中で妄想を膨らませて\nいるのですか！？
275 = "それとも私をどう弄ぼうか、\\nそのいやらしい頭の中で妄想を膨らませて\\nいるのですか！？"

# カズマ（Ｍ）
# display as カズマ
# （なんだろうな、\n　このこれじゃない感じ）
364 = "（なんだろうな、\\n　このこれじゃない感じ）"

# カズマ（Ｍ）
# display as カズマ
# （普通水着といったら、\n　女の子を何倍にも魅力的にする\n　魔法のアイテムだろ？）
374 = "（普通水着といったら、\\n　女の子を何倍にも魅力的にする\\n　魔法のアイテムだろ？）"

# カズマ（Ｍ）
# display as カズマ
# （なのに、な・の・に・だ。\n　俺の心はとても穏やかだ）
363 = "（なのに、な・の・に・だ。\\n　俺の心はとても穏やかだ）"

# カズマ（Ｍ）
# display as カズマ
# （これほど肌が露出しているにも関わらず、\n　まったく何も感じない。\n　恐ろしいまでに何もだ！）
357 = "（これほど肌が露出しているにも関わらず、\\n　まったく何も感じない。\\n　恐ろしいまでに何もだ！）"

# カズマ（Ｍ）
# display as カズマ
# （俺の強靱な妄想力を持ってしても\n　どうにかできる気がしない！）
368 = "（俺の強靱な妄想力を持ってしても\\n　どうにかできる気がしない！）"

# カズマ（Ｍ）
# display as カズマ
# （原因はわかっている。\n　この子供のような体型だ。\n　こんなもんにどう反応しろと言うんだ？）
371 = "（原因はわかっている。\\n　この子供のような体型だ。\\n　こんなもんにどう反応しろと言うんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （俺は変態じゃないんだ。\n　子供の水着姿を見ても。\n　へ～、そうですかとしか思わんわ！）
370 = "（俺は変態じゃないんだ。\\n　子供の水着姿を見ても。\\n　へ～、そうですかとしか思わんわ！）"

# カズマ（Ｍ）
# display as カズマ
# （幼児体型だとは思っていたが、\n　まさかここまで俺の想像の\n　はるか斜め上をいくとは！）
373 = "（幼児体型だとは思っていたが、\\n　まさかここまで俺の想像の\\n　はるか斜め上をいくとは！）"

# カズマ（Ｍ）
# display as カズマ
# （あ～、失敗した。\n　明らかに人選ミスですわ）
356 = "（あ～、失敗した。\\n　明らかに人選ミスですわ）"

# カズマ（Ｍ）
# display as カズマ
# （こんなことならダクネスあたりに\n　お願いすればよかった）
358 = "（こんなことならダクネスあたりに\\n　お願いすればよかった）"

# カズマ（Ｍ）
# display as カズマ
# （少なくともスタイルに関しては、\n　天と地ほどの違いがあるもんな。\n　どうしてそうしなかった、俺！？）
372 = "（少なくともスタイルに関しては、\\n　天と地ほどの違いがあるもんな。\\n　どうしてそうしなかった、俺！？）"

# めぐみん
# 何をうんうん唸っているのです。\nはっ！　私に行う辱めの限りを考えていたのですね！？
310 = "何をうんうん唸っているのです。\\nはっ！　私に行う辱めの限りを考えていたのですね！？"

# カズマ
# してないしてない。
267 = "してないしてない。"

# カズマ
# 俺はめぐみんに対して\n人様に後ろ指を指されるようなことを\n微塵も考えてないぞ。
314 = "俺はめぐみんに対して\\n人様に後ろ指を指されるようなことを\\n微塵も考えてないぞ。"

# めぐみん
# 怪しいものです！\n口ではなんとでも言えますからね。
321 = "怪しいものです！\\n口ではなんとでも言えますからね。"

# カズマ
# 何を言う。\n今の俺の心は青空より澄み渡り清流よりも清い。
311 = "何を言う。\\n今の俺の心は青空より澄み渡り清流よりも清い。"

# めぐみん
# もうなんでもいいですよ。\nそれで私は何をすればいいのですか。
299 = "もうなんでもいいですよ。\\nそれで私は何をすればいいのですか。"

# カズマ
# そうな、それな。\nそこが悩みどころだ。うーん……。
270 = "そうな、それな。\\nそこが悩みどころだ。うーん……。"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんにお色気を求めるのは、\n　アクアに頭の良さを求める並に無理がある）
365 = "（めぐみんにお色気を求めるのは、\\n　アクアに頭の良さを求める並に無理がある）"

# カズマ（Ｍ）
# display as カズマ
# （しかしこのまま何もせず諦めてもいいのか？）
360 = "（しかしこのまま何もせず諦めてもいいのか？）"

# カズマ（Ｍ）
# display as カズマ
# （もしかしたら、めぐみんでも輝ける何かが\n　あるかもしれないじゃないか！）
367 = "（もしかしたら、めぐみんでも輝ける何かが\\n　あるかもしれないじゃないか！）"

# カズマ（Ｍ）
# display as カズマ
# （俺は仲間を見捨てたりしない！\n　めぐみんの可能性に賭ける！）
369 = "（俺は仲間を見捨てたりしない！\\n　めぐみんの可能性に賭ける！）"

# めぐみん
# ずいぶんな長考ですね。\nできればさっさと決めてください。
268 = "ずいぶんな長考ですね。\\nできればさっさと決めてください。"

# カズマ
# よしわかった！\nそれではめぐみん、お前に命じよう！
302 = "よしわかった！\\nそれではめぐみん、お前に命じよう！"

# めぐみん
# ふっ、受けて立ちましょう！\nただし、いかがわしいことを言おうものなら\n爆裂魔法をお見舞いしますからね！
295 = "ふっ、受けて立ちましょう！\\nただし、いかがわしいことを言おうものなら\\n爆裂魔法をお見舞いしますからね！"

# カズマ
# 心配するな。\n俺が命じるのは――
320 = "心配するな。\\n俺が命じるのは――"

# カズマ
# 日焼け止めを塗ってくれ！
322 = "日焼け止めを塗ってくれ！"

# めぐみん
# 今から湖に出かけるんですか？
309 = "今から湖に出かけるんですか？"

# カズマ
# そんな遠出面倒くさくてしていられるか、\nするわけないだろ。
279 = "そんな遠出面倒くさくてしていられるか、\\nするわけないだろ。"

# めぐみん
# では、まさかここでしろと言うのですか？
285 = "では、まさかここでしろと言うのですか？"

# カズマ
# その通り、こんなこともあろうかと\n日焼け止めは用意してある。\nさあ、存分に塗るがいい！
272 = "その通り、こんなこともあろうかと\\n日焼け止めは用意してある。\\nさあ、存分に塗るがいい！"

# めぐみん
# なぜ用意してあるのです！\nそれに屋内で日焼け止めとは\n正気ですか？
287 = "なぜ用意してあるのです！\\nそれに屋内で日焼け止めとは\\n正気ですか？"

# カズマ
# 俺はいつだって本気だ！
313 = "俺はいつだって本気だ！"

# めぐみん
# 言いたいことはありますが、\nいいでしょう。
354 = "言いたいことはありますが、\\nいいでしょう。"

# めぐみん
# そこまで言うならカズマの本気に\n私の本気で応えましょう。\nさあ、上を脱いで横になるのです！
271 = "そこまで言うならカズマの本気に\\n私の本気で応えましょう。\\nさあ、上を脱いで横になるのです！"

# カズマ
# よいしょっと！\nさあ、始めてくれ！
301 = "よいしょっと！\\nさあ、始めてくれ！"

# めぐみん
# この私のテクニックに\n酔いしれさせてあげますよ！
266 = "この私のテクニックに\\n酔いしれさせてあげますよ！"

# カズマ
# お、なかなか上手じゃないか。
265 = "お、なかなか上手じゃないか。"

# めぐみん
# もちろんです。\nモミモミ、モミモミっと。
300 = "もちろんです。\\nモミモミ、モミモミっと。"

# カズマ（Ｍ）
# display as カズマ
# （確かに言うだけあって\n　なかなかの心地よさだ）
376 = "（確かに言うだけあって\\n　なかなかの心地よさだ）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、やっぱり色気は微塵も\n　感じられないな……）
359 = "（しかし、やっぱり色気は微塵も\\n　感じられないな……）"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんを女らしくしてやろうだなんて\n　たいそうな計画は俺の手には余る）
366 = "（めぐみんを女らしくしてやろうだなんて\\n　たいそうな計画は俺の手には余る）"

# カズマ（Ｍ）
# display as カズマ
# （最初から詰んでいたんだな……、\n　無理なものは無理！）
375 = "（最初から詰んでいたんだな……、\\n　無理なものは無理！）"

# カズマ
# 波打ち際で水のかけ合いだな！
324 = "波打ち際で水のかけ合いだな！"

# めぐみん
# 波打ち際？\n今から湖に出かけるんですか？
325 = "波打ち際？\\n今から湖に出かけるんですか？"

# カズマ
# そんな遠出面倒くさくてしてられるか。
281 = "そんな遠出面倒くさくてしてられるか。"

# めぐみん
# では、小川にでも出向きますか？\nあ、いえ、お風呂でという手も。
286 = "では、小川にでも出向きますか？\\nあ、いえ、お風呂でという手も。"

# カズマ
# いや、ここでしよう！
260 = "いや、ここでしよう！"

# めぐみん
# 何を言っているのですか、\nここには水など無いではありませんか！？
312 = "何を言っているのですか、\\nここには水など無いではありませんか！？"

# カズマ
# そんなことはもちろん知ってる。\nバカじゃないんだから当然だろ。
277 = "そんなことはもちろん知ってる。\\nバカじゃないんだから当然だろ。"

# めぐみん
# え、バカじゃなかったんですか？
263 = "え、バカじゃなかったんですか？"

# カズマ
# あのな～……。\nまあ、いい……フリだよフリ。\n水の掛け合いのフリをするんだ！
257 = "あのな～……。\\nまあ、いい……フリだよフリ。\\n水の掛け合いのフリをするんだ！"

# めぐみん
# そんな真似をして\n本当に楽しいと思えるのですか？\n虚しくはなりませんか？
278 = "そんな真似をして\\n本当に楽しいと思えるのですか？\\n虚しくはなりませんか？"

# カズマ
# うん、やっぱりやめておこう。
262 = "うん、やっぱりやめておこう。"

# めぐみん
# それが懸命です。
274 = "それが懸命です。"

# カズマ（Ｍ）
# display as カズマ
# （どうにかしてめぐみんに\n　お色気を身につけさせようと思ったが、\n　不発に終わったな）
362 = "（どうにかしてめぐみんに\\n　お色気を身につけさせようと思ったが、\\n　不発に終わったな）"

# カズマ（Ｍ）
# display as カズマ
# （そもそもないものはないんだ。\n　どんなに手を尽くしてたところで\n　無理なものは無理だよな）
361 = "（そもそもないものはないんだ。\\n　どんなに手を尽くしてたところで\\n　無理なものは無理だよな）"

# カズマ
# 俺を砂に埋めてくれ！
316 = "俺を砂に埋めてくれ！"

# めぐみん
# ……何を言ってるんですか？
256 = "……何を言ってるんですか？"

# カズマ
# だから俺を砂に埋めてくれと\n言ってるんだ！
282 = "だから俺を砂に埋めてくれと\\n言ってるんだ！"

# めぐみん
# それはカズマを亡き者にし、\n埋葬しろということですか？
276 = "それはカズマを亡き者にし、\\n埋葬しろということですか？"

# カズマ
# 違うわ！　なんだ、その物騒な発想は！？
355 = "違うわ！　なんだ、その物騒な発想は！？"

# めぐみん
# カズマが突飛もないことを言い出すからです。\n第一砂はどうするんです？\n今から海にでも行くんですか？
306 = "カズマが突飛もないことを言い出すからです。\\n第一砂はどうするんです？\\n今から海にでも行くんですか？"

# カズマ
# そんな遠出面倒くさくてしていられるか。
280 = "そんな遠出面倒くさくてしていられるか。"

# めぐみん
# では、どうしろというのです？
284 = "では、どうしろというのです？"

# カズマ
# あれだ、魔法で砂を出したりだな。
258 = "あれだ、魔法で砂を出したりだな。"

# めぐみん
# 私は爆裂魔法しか使えません！\nそもそもそんな魔法聞いたことも\nありませんよ。
351 = "私は爆裂魔法しか使えません！\\nそもそもそんな魔法聞いたことも\\nありませんよ。"

# カズマ
# むむむむむ……この案は却下だな。
297 = "むむむむむ……この案は却下だな。"

# めぐみん
# 当然です。
319 = "当然です。"

# カズマ（Ｍ）
# display as カズマ
# （どうにかしてめぐみんに\n　お色気を身につけさせようと思ったが、\n　不発に終わったな）
# 362 = "（どうにかしてめぐみんに\\n　お色気を身につけさせようと思ったが、\\n　不発に終わったな）"

# カズマ（Ｍ）
# display as カズマ
# （そもそもないものはないんだ。\n　どんなに手を尽くしてたところで\n　無理なものは無理だよな）
# 361 = "（そもそもないものはないんだ。\\n　どんなに手を尽くしてたところで\\n　無理なものは無理だよな）"

# めぐみん
# なんですか、\nその哀れみに満ちた眼差しは！？
289 = "なんですか、\\nその哀れみに満ちた眼差しは！？"

# めぐみん
# はっ、さてはよからぬことを\n考えていますね！？
293 = "はっ、さてはよからぬことを\\n考えていますね！？"

# カズマ
# いや、無い物ねだりをした\n俺が愚かだったと\n反省していたところだよ。
261 = "いや、無い物ねだりをした\\n俺が愚かだったと\\n反省していたところだよ。"

# めぐみん
# 無い物とはなんですか？\nこの私に足りぬものなどあるはずも――
327 = "無い物とはなんですか？\\nこの私に足りぬものなどあるはずも――"

# カズマ
# 色気。
353 = "色気。"

# めぐみん
# はうあっ！？
292 = "はうあっ！？"

# カズマ
# 残念だけどそういうことだ。\nめぐみんには色気がない、\nこれはもうどうしようもないことだ。
323 = "残念だけどそういうことだ。\\nめぐみんには色気がない、\\nこれはもうどうしようもないことだ。"

# カズマ
# だけど落ち込むな、\nきっとそのうち良いこともあるさ。
283 = "だけど落ち込むな、\\nきっとそのうち良いこともあるさ。"

# めぐみん
# 色気……色気……我には色気が欠けている。
352 = "色気……色気……我には色気が欠けている。"

# カズマ
# お、おい、めぐみん？
264 = "お、おい、めぐみん？"

# カズマ（Ｍ）
# display as カズマ
# （行ってしまった……）
377 = "（行ってしまった……）"

[selections]
# 322 = "日焼け止めを塗ってくれ！"
# 324 = "波打ち際で水のかけ合いだな！"
# 316 = "俺を砂に埋めてくれ！"
