# rew_a02.txt.scn

[info]
190 = "rew_a02"

[characters]
263 = "アクア"
264 = "カズマ"
267 = "カズマ（Ｍ）"

[character_subs]
# 264 = "カズマ"

[script]
# lines: 74

# アクア
# ふふーん、ご褒美に女神である私の素晴らしい姿を\n存分に堪能させてあげるわ！
254 = "ふふーん、ご褒美に女神である私の素晴らしい姿を\\n存分に堪能させてあげるわ！"

# カズマ
# チェンジで。
269 = "チェンジで。"

# アクア
# ちょっ、私にご褒美を要求したのは\nカズマじゃない！
242 = "ちょっ、私にご褒美を要求したのは\\nカズマじゃない！"

# カズマ
# 誰も、水着姿で来いなんて言ってないだろ！
294 = "誰も、水着姿で来いなんて言ってないだろ！"

# アクア
# なによっ、人がせっかく気を利かせてあげたの\nにっ！
245 = "なによっ、人がせっかく気を利かせてあげたの\\nにっ！"

# アクア
# ありがとうございますアクア様、一生あなたに\nついていきます。\nくらい言いなさいよね、男なら！
213 = "ありがとうございますアクア様、一生あなたに\\nついていきます。\\nくらい言いなさいよね、男なら！"

# カズマ
# いや、性別関係ねーし！\nそれに……！！
216 = "いや、性別関係ねーし！\\nそれに……！！"

# カズマ（Ｍ）
# display as カズマ
# （顔を近づけるな！\n　うおっ、胸の谷間が……）
303 = "（顔を近づけるな！\\n　うおっ、胸の谷間が……）"

# アクア
# あら～、顔を赤くしてどうしたのかしら？\nもしかして、目のやり場に困っちゃってるの？
212 = "あら～、顔を赤くしてどうしたのかしら？\\nもしかして、目のやり場に困っちゃってるの？"

# カズマ（Ｍ）
# display as カズマ
# （くっ、確かに童貞の俺には刺激が強いが――）
296 = "（くっ、確かに童貞の俺には刺激が強いが――）"

# カズマ
# うん、よく考えたら、お前だしな。\n余裕で凝視できたわ。ごめん。
223 = "うん、よく考えたら、お前だしな。\\n余裕で凝視できたわ。ごめん。"

# アクア
# ちょっとカズマさん、謝らないでよ！\n私が惨めになるじゃない！
243 = "ちょっとカズマさん、謝らないでよ！\\n私が惨めになるじゃない！"

# カズマ
# はいはい、わかったから離れろっ！\nうっとうしい！
252 = "はいはい、わかったから離れろっ！\\nうっとうしい！"

# アクア
# くぅぅ～～！　こうなったら見てなさいよ！\nギャフンって言わせてやるんだから！
228 = "くぅぅ～～！　こうなったら見てなさいよ！\\nギャフンって言わせてやるんだから！"

# カズマ（Ｍ）
# display as カズマ
# （ギャフンとか、いつのセンスだよ……）
299 = "（ギャフンとか、いつのセンスだよ……）"

# アクア
# うっふ～ん。\nさあ、どう？　ドキってしちゃったでしょ？
221 = "うっふ～ん。\\nさあ、どう？　ドキってしちゃったでしょ？"

# カズマ
# そうですね。
237 = "そうですね。"

# アクア
# ふふ、さーらーに。\nウィンクのサービス♪
253 = "ふふ、さーらーに。\\nウィンクのサービス♪"

# カズマ
# うわー、セクシー。
222 = "うわー、セクシー。"

# アクア
# なんだったら、もっと近くに来てもいいのよ？
246 = "なんだったら、もっと近くに来てもいいのよ？"

# カズマ
# それは嬉しいなー。
239 = "それは嬉しいなー。"

# アクア
# ねえ、さっきから何難しい顔をしてるのよ。
250 = "ねえ、さっきから何難しい顔をしてるのよ。"

# カズマ
# いやな、悪くはないんだ。\nでもさ、なんか足りないんだよな。
217 = "いやな、悪くはないんだ。\\nでもさ、なんか足りないんだよな。"

# アクア
# ぐぬぬ、今までのは小手調べよ！\nこれから本気を出してあげるんだから見てなさい！
230 = "ぐぬぬ、今までのは小手調べよ！\\nこれから本気を出してあげるんだから見てなさい！"

# カズマ
# へえ、それは楽しみだ。
255 = "へえ、それは楽しみだ。"

# アクア
# 太陽のような笑顔に、さらに胸を寄せて……。\nよっこいしょ、どう？
276 = "太陽のような笑顔に、さらに胸を寄せて……。\\nよっこいしょ、どう？"

# カズマ
# いや、よっこいしょが余計だから……。
215 = "いや、よっこいしょが余計だから……。"

# アクア
# さらに、特別に投げキッスもしちゃうんだから。\nチュッ♪
233 = "さらに、特別に投げキッスもしちゃうんだから。\\nチュッ♪"

# カズマ（Ｍ）
# display as カズマ
# （呪われそうだ……）
301 = "（呪われそうだ……）"

# アクア
# ね、ねえ、カズマ。\nそろそろやせ我慢やめたら？
248 = "ね、ねえ、カズマ。\\nそろそろやせ我慢やめたら？"

# カズマ
# 我慢なんてしてませんけど？
278 = "我慢なんてしてませんけど？"

# アクア
# ううー、カズマのくせにっ、カズマのくせにっ！
219 = "ううー、カズマのくせにっ、カズマのくせにっ！"

# カズマ（Ｍ）
# display as カズマ
# （ありゃ、涙声になっちまった。\n　ちょっとやり過ぎたかな）
295 = "（ありゃ、涙声になっちまった。\\n　ちょっとやり過ぎたかな）"

# カズマ（Ｍ）
# display as カズマ
# （実は、アクアが俺を満足させようと必死になって\n　る姿だけで、すっごい満足してるんだが）
302 = "（実は、アクアが俺を満足させようと必死になって\\n　る姿だけで、すっごい満足してるんだが）"

# アクア
# 次は、うぅ、ええと、ええと……。
280 = "次は、うぅ、ええと、ええと……。"

# カズマ
# わかったから落ちつけ。\nお前はやれば出来る子だろ？
262 = "わかったから落ちつけ。\\nお前はやれば出来る子だろ？"

# アクア
# そうだけど……。\nずっと死んだ魚のような目で見られたら\nさすがに自信が無くなるわ。
236 = "そうだけど……。\\nずっと死んだ魚のような目で見られたら\\nさすがに自信が無くなるわ。"

# カズマ（Ｍ）
# display as カズマ
# （俺、そんな目してたのか……）
300 = "（俺、そんな目してたのか……）"

# アクア
# ねえ、こんなポーズはどう？\n結構、良い感じだと思うんだけど……。
249 = "ねえ、こんなポーズはどう？\\n結構、良い感じだと思うんだけど……。"

# カズマ
# うーん……。
225 = "うーん……。"

# アクア
# じゃあじゃあ、こういうのは？
235 = "じゃあじゃあ、こういうのは？"

# カズマ
# 無い。
281 = "無い。"

# カズマ
# なあ、アクア。\nリクエストしてもいいか？
244 = "なあ、アクア。\\nリクエストしてもいいか？"

# アクア
# 何よ、私にどんな卑猥なポーズをさせるつもり。
272 = "何よ、私にどんな卑猥なポーズをさせるつもり。"

# アクア
# まさか、あんなポーズやこんなポーズを。\nそしてポーズを指示するにかこつけて、\n体をベタベタ触って……。
258 = "まさか、あんなポーズやこんなポーズを。\\nそしてポーズを指示するにかこつけて、\\n体をベタベタ触って……。"

# カズマ
# そんなことしねーよ！
240 = "そんなことしねーよ！"

# アクア
# まあいいわ。\nやるかどうかはリクエストを聞いてから考えるから。
257 = "まあいいわ。\\nやるかどうかはリクエストを聞いてから考えるから。"

# カズマ
# じゃあ、そうだなー。\nそのポーズのまま、上目で俺を見て――
234 = "じゃあ、そうだなー。\\nそのポーズのまま、上目で俺を見て――"

# アクア
# こう？
231 = "こう？"

# カズマ
# それで切なそうに、カズマ……って\n言ってみてくれ。
238 = "それで切なそうに、カズマ……って\\n言ってみてくれ。"

# アクア
# カズマ……？
266 = "カズマ……？"

# カズマ
# あ、ごめん、やっぱ無いわ。
211 = "あ、ごめん、やっぱ無いわ。"

# カズマ
# もういい。\nこれ以上、自分を傷つけるな！
259 = "もういい。\\nこれ以上、自分を傷つけるな！"

# アクア
# カズマ……。
265 = "カズマ……。"

# カズマ
# 人には向き不向きってのがあるからな。\nお前にはさ、あってないんだよ、こういうの。
271 = "人には向き不向きってのがあるからな。\\nお前にはさ、あってないんだよ、こういうの。"

# アクア
# ちっとも慰めになってないわよ！
241 = "ちっとも慰めになってないわよ！"

# アクア
# くぅぅっ、こうなったら意地でも喜ばせて\nやるんだからっ！
227 = "くぅぅっ、こうなったら意地でも喜ばせて\\nやるんだからっ！"

# カズマ（Ｍ）
# display as カズマ
# （そこはムキになるところじゃないだろ……）
298 = "（そこはムキになるところじゃないだろ……）"

# アクア
# うっふーん。
220 = "うっふーん。"

# カズマ
# うん。
224 = "うん。"

# アクア
# カ・ズ・マ♪
268 = "カ・ズ・マ♪"

# カズマ
# なんですか？
247 = "なんですか？"

# アクア
# 甘える上目で悩殺ウィンク。
282 = "甘える上目で悩殺ウィンク。"

# カズマ
# へー、考えましたね。
256 = "へー、考えましたね。"

# アクア
# うぅ、うぅぅぅ……。
218 = "うぅ、うぅぅぅ……。"

# カズマ
# お、おい、アクアどうした？
226 = "お、おい、アクアどうした？"

# アクア
# 喜んで……。
274 = "喜んで……。"

# カズマ
# はあ？
251 = "はあ？"

# アクア
# 嘘でもいいから喜んでって言ってるの……。
275 = "嘘でもいいから喜んでって言ってるの……。"

# カズマ（Ｍ）
# display as カズマ
# （こいつにはプライドが無いのか！）
297 = "（こいつにはプライドが無いのか！）"

# アクア
# 早く喜んでったら！
279 = "早く喜んでったら！"

# カズマ
# わ、わーい、女神様の水着姿を見られて\n嬉しいなー。
260 = "わ、わーい、女神様の水着姿を見られて\\n嬉しいなー。"

# アクア
# ぐす、うぅぅ、ありがとう。
229 = "ぐす、うぅぅ、ありがとう。"

# カズマ
# いえ、どういたしまして……。
214 = "いえ、どういたしまして……。"

[selections]
261 = "わかったから落ちつけ"
270 = "リクエストをしてもいいか？"
232 = "これ以上、自分を傷つけるな！"
