# rew_c10.txt.scn

[info]
230 = "rew_c10"

[characters]
323 = "カズマ"
330 = "ダクネス"
327 = "カズマ（Ｍ）"

[character_subs]
# 323 = "カズマ"

[script]
# lines: 97

# カズマ
# はぁはぁ……危なかった。\nマジで死ぬかと思ったわ！
308 = "はぁはぁ……危なかった。\\nマジで死ぬかと思ったわ！"

# ダクネス
# そ、そうだな。
276 = "そ、そうだな。"

# カズマ
# って、ちょっと嬉しそうにしてんじゃないよ！\nお前は！
291 = "って、ちょっと嬉しそうにしてんじゃないよ！\\nお前は！"

# ダクネス
# 別に嬉しそうになんて……。
334 = "別に嬉しそうになんて……。"

# カズマ
# してるじゃん、思いっきり頬が緩んでるじゃん！
272 = "してるじゃん、思いっきり頬が緩んでるじゃん！"

# カズマ
# 獣の群れに追われてるときも、\n隙あらば突っ込もうとしてたしさ！\n超、信じられないんですけど！
339 = "獣の群れに追われてるときも、\\n隙あらば突っ込もうとしてたしさ！\\n超、信じられないんですけど！"

# ダクネス
# わ、私は、そうでもしないと、\nカズマを無事に逃がせないと思ったんだ。
318 = "わ、私は、そうでもしないと、\\nカズマを無事に逃がせないと思ったんだ。"

# ダクネス
# ほ、本当だぞ？
313 = "ほ、本当だぞ？"

# カズマ
# はぁ、お仕置きだからって高レベルのクエストに\n下位職を連れ出すなんてあり得ないことだからな。
306 = "はぁ、お仕置きだからって高レベルのクエストに\\n下位職を連れ出すなんてあり得ないことだからな。"

# カズマ（Ｍ）
# display as カズマ
# （ノコノコとついていった俺も俺だけどさ）
388 = "（ノコノコとついていった俺も俺だけどさ）"

# ダクネス
# カズマ、もし許せないのであれば\n口汚く罵ってくれて構わないのだぞ。
324 = "カズマ、もし許せないのであれば\\n口汚く罵ってくれて構わないのだぞ。"

# カズマ
# とーにーかーくっ、もう体力が無いから帰るぞ。\n次、獣の群れに遭遇したら、\nそれこそ一巻の終わりだからな。
296 = "とーにーかーくっ、もう体力が無いから帰るぞ。\\n次、獣の群れに遭遇したら、\\nそれこそ一巻の終わりだからな。"

# ダクネス
# そのときこそ私を盾に！
282 = "そのときこそ私を盾に！"

# カズマ
# 真面目に言っておく。\n俺は仲間を置いて逃げられるような、\n人でなしじゃない。
369 = "真面目に言っておく。\\n俺は仲間を置いて逃げられるような、\\n人でなしじゃない。"

# ダクネス
# うぅ、す、すまない。
264 = "うぅ、す、すまない。"

# カズマ（Ｍ）
# display as カズマ
# （まったく、とんだお仕置きだった……）
387 = "（まったく、とんだお仕置きだった……）"

# ダクネス
# あ、あの、カズマ？
258 = "あ、あの、カズマ？"

# カズマ
# なんだ、どうした？
302 = "なんだ、どうした？"

# ダクネス
# 言いにくいのだが、\nどうやら足を挫いてしまったようで……。
372 = "言いにくいのだが、\\nどうやら足を挫いてしまったようで……。"

# カズマ
# おいおい、大丈夫か？
267 = "おいおい、大丈夫か？"

# ダクネス
# くっ……へっ、平気だっ！
268 = "くっ……へっ、平気だっ！"

# カズマ
# そうは見えねーよ。
281 = "そうは見えねーよ。"

# カズマ（Ｍ）
# display as カズマ
# （どうする？\n　街までアクアを呼びに行くか？）
385 = "（どうする？\\n　街までアクアを呼びに行くか？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、それは危険か。\n　また獣の群れが現れるかも\n　わからない状況だし……）
376 = "（いや、それは危険か。\\n　また獣の群れが現れるかも\\n　わからない状況だし……）"

# カズマ
# はぁ、しょうがない、俺がおぶってやるよ。
307 = "はぁ、しょうがない、俺がおぶってやるよ。"

# ダクネス
# いや、さすがにそれは……。
261 = "いや、さすがにそれは……。"

# カズマ
# なんだよ、いつもなら――
304 = "なんだよ、いつもなら――"

# カズマ
# ふ、ふふ、おぶるふりをして私の体を触りまくる\n魂胆なのだろ。カズマはやはり抜け目が無いな、\nハァハァ。
310 = "ふ、ふふ、おぶるふりをして私の体を触りまくる\\n魂胆なのだろ。カズマはやはり抜け目が無いな、\\nハァハァ。"

# カズマ
# とか言って、喜ぶくせに。
295 = "とか言って、喜ぶくせに。"

# ダクネス
# なっ！？
301 = "なっ！？"

# カズマ
# いや、まあ、そのつもりだけどね！
262 = "いや、まあ、そのつもりだけどね！"

# ダクネス
# なぁ！？
297 = "なぁ！？"

# カズマ
# というわけで俺にも得があるんだから、\n遠慮しないで頼れって。
294 = "というわけで俺にも得があるんだから、\\n遠慮しないで頼れって。"

# ダクネス
# わ、わかった。じゃあ、よろしく頼む。
317 = "わ、わかった。じゃあ、よろしく頼む。"

# カズマ
# そうそう素直が一番……って、ダクネス？
280 = "そうそう素直が一番……って、ダクネス？"

# ダクネス
# ん？　どうかしたか？
319 = "ん？　どうかしたか？"

# カズマ
# なんで俺の首に手を回してんの？
305 = "なんで俺の首に手を回してんの？"

# ダクネス
# カズマが、抱えやすいようにと思ったのだが。\n違ったか？
326 = "カズマが、抱えやすいようにと思ったのだが。\\n違ったか？"

# カズマ（Ｍ）
# display as カズマ
# （首に手を回されて顔が近づけられるとか\n　童貞には刺激が強すぎるわ！）
389 = "（首に手を回されて顔が近づけられるとか\\n　童貞には刺激が強すぎるわ！）"

# カズマ（Ｍ）
# display as カズマ
# （てか俺、おぶるって言ったよな？\n　あれ？　もしかして抱っこって言った？）
384 = "（てか俺、おぶるって言ったよな？\\n　あれ？　もしかして抱っこって言った？）"

# ダクネス
# カ、カズマ……この体勢で待つのは\nかなり恥ずかしいのだが。
320 = "カ、カズマ……この体勢で待つのは\\nかなり恥ずかしいのだが。"

# カズマ（Ｍ）
# display as カズマ
# （くっそ、こうなったらやってやる！\n　ふんぎいいいいいいいい！！）
380 = "（くっそ、こうなったらやってやる！\\n　ふんぎいいいいいいいい！！）"

# ダクネス
# だ、大丈夫か？　重くないか？
283 = "だ、大丈夫か？　重くないか？"

# カズマ
# ぐおおおお、へ、へ、平気ぃぃ。
269 = "ぐおおおお、へ、へ、平気ぃぃ。"

# ダクネス
# 無理そうなら、下ろしてくれていいんだぞ？
338 = "無理そうなら、下ろしてくれていいんだぞ？"

# カズマ（Ｍ）
# display as カズマ
# （くぅぅ、このタイミングで上目遣いでお願いとか、\n　狙ってやってるんじゃないだろうな！）
379 = "（くぅぅ、このタイミングで上目遣いでお願いとか、\\n　狙ってやってるんじゃないだろうな！）"

# カズマ（Ｍ）
# display as カズマ
# （うぐお、それにそんな顔でお願いされて、\n　はいわかりましたって下ろせるわけねーだろ！）
378 = "（うぐお、それにそんな顔でお願いされて、\\n　はいわかりましたって下ろせるわけねーだろ！）"

# ダクネス
# なあ、先ほどから１歩も進んでいないようだが。\nもし厳しいなら――
300 = "なあ、先ほどから１歩も進んでいないようだが。\\nもし厳しいなら――"

# カズマ
# ちっとも厳しくない！！
289 = "ちっとも厳しくない！！"

# カズマ
# でも、もっと痩せてくれ！\nお前、重すぎるわ！
293 = "でも、もっと痩せてくれ！\\nお前、重すぎるわ！"

# ダクネス
# そ、それは鎧のせいだ！
278 = "そ、それは鎧のせいだ！"

# カズマ
# だったら脱げ！
287 = "だったら脱げ！"

# ダクネス
# わ、わかった。
316 = "わ、わかった。"

# カズマ
# 冗談だよ、何本気にしてんだ！
333 = "冗談だよ、何本気にしてんだ！"

# ダクネス
# 今のカズマの顔を見て、\n冗談と受け取れという方が無理な話だ。
331 = "今のカズマの顔を見て、\\n冗談と受け取れという方が無理な話だ。"

# カズマ
# え？　俺ってそんなに必死な顔してる？
265 = "え？　俺ってそんなに必死な顔してる？"

# ダクネス
# 頭の血管が切れないか不安になるな。
373 = "頭の血管が切れないか不安になるな。"

# カズマ（Ｍ）
# display as カズマ
# （そ、そんなかー！）
382 = "（そ、そんなかー！）"

# カズマ
# これくらい平気だ！
270 = "これくらい平気だ！"

# ダクネス
# だが、足が震えているぞ。
285 = "だが、足が震えているぞ。"

# カズマ
# へへっ、男は負けるとわかっていても、\n戦わなきゃいけない時があるんだよ。
312 = "へへっ、男は負けるとわかっていても、\\n戦わなきゃいけない時があるんだよ。"

# ダクネス
# 今の状況で負けるとは、どういうことなんだ？
332 = "今の状況で負けるとは、どういうことなんだ？"

# カズマ
# お、お、重いお前を下ろす。
266 = "お、お、重いお前を下ろす。"

# ダクネス
# はっきりと言ってくれたな。
309 = "はっきりと言ってくれたな。"

# カズマ
# なんだ、んぎぃ、気にしてるのか？\n意外に乙女じゃないか。
303 = "なんだ、んぎぃ、気にしてるのか？\\n意外に乙女じゃないか。"

# ダクネス
# 私の誇りのために言っておくが、\n重いのは鎧であって、私の体ではないからな！
371 = "私の誇りのために言っておくが、\\n重いのは鎧であって、私の体ではないからな！"

# カズマ
# そ、そうしておいてやるよ。
275 = "そ、そうしておいてやるよ。"

# カズマ
# だけど、もっとしっかりしがみついてくれると\n助かる！
286 = "だけど、もっとしっかりしがみついてくれると\\n助かる！"

# ダクネス
# わ、わかった、これでどうだ？
315 = "わ、わかった、これでどうだ？"

# カズマ
# ちょぉぉ、顔が近いわ！\nお前はキスするつもりか！
290 = "ちょぉぉ、顔が近いわ！\\nお前はキスするつもりか！"

# ダクネス
# キッ、キス！？
328 = "キッ、キス！？"

# カズマ
# だーーーー、離れるな、腕に体重がかかるだろ！
288 = "だーーーー、離れるな、腕に体重がかかるだろ！"

# ダクネス
# す、すまない！
274 = "す、すまない！"

# カズマ
# だからどうして顔を近づけるんだよ！
284 = "だからどうして顔を近づけるんだよ！"

# ダクネス
# しがみつくと、こうなるのが必然なんだ！
271 = "しがみつくと、こうなるのが必然なんだ！"

# カズマ
# 顔を逸らすとか工夫してくれ！
374 = "顔を逸らすとか工夫してくれ！"

# ダクネス
# そ、そうだな！！
277 = "そ、そうだな！！"

# カズマ
# 嫌われてるみたいでへこむわ！
336 = "嫌われてるみたいでへこむわ！"

# ダクネス
# なあ、もしかしてからかっているのか？
298 = "なあ、もしかしてからかっているのか？"

# カズマ
# そ、そんな余裕ないっての！
279 = "そ、そんな余裕ないっての！"

# カズマ（Ｍ）
# display as カズマ
# （てかやばい、腕が痺れてきた！）
383 = "（てかやばい、腕が痺れてきた！）"

# カズマ（Ｍ）
# display as カズマ
# （そ、それに、こ、こ、腰が！！）
381 = "（そ、それに、こ、こ、腰が！！）"

# カズマ
# ふご、うごおおおおおお！！
311 = "ふご、うごおおおおおお！！"

# ダクネス
# カ、カズマ！？　喉から変な音が出てるぞ！
322 = "カ、カズマ！？　喉から変な音が出てるぞ！"

# カズマ（Ｍ）
# display as カズマ
# （あかん、もう無理……げ、限界！！）
375 = "（あかん、もう無理……げ、限界！！）"

# カズマ
# あぁん。
259 = "あぁん。"

# ダクネス
# カ、カズマ！？
321 = "カ、カズマ！？"

# ダクネス
# カズマ、腰はどうだ？
325 = "カズマ、腰はどうだ？"

# カズマ
# しばらく動けないかも……。\nお前はどうなんだ、ダクネス？
273 = "しばらく動けないかも……。\\nお前はどうなんだ、ダクネス？"

# ダクネス
# クルセイダーの自然治癒力を侮ってはいけないぞ。\n痛みはもう無いし、腫れもすっかり引いた。
329 = "クルセイダーの自然治癒力を侮ってはいけないぞ。\\n痛みはもう無いし、腫れもすっかり引いた。"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、情けねー。\n　ダクネスを助けるどころか腰を痛めて\n　迷惑をかけちまうなんて……）
386 = "（はぁ、情けねー。\\n　ダクネスを助けるどころか腰を痛めて\\n　迷惑をかけちまうなんて……）"

# ダクネス
# なあ、カズマ、１つ提案なのだが。\n街まで私が抱っこして帰るというのはどうだろうか。
299 = "なあ、カズマ、１つ提案なのだが。\\n街まで私が抱っこして帰るというのはどうだろうか。"

# カズマ
# …………。
257 = "…………。"

# ダクネス
# 私のように早期回復は望めないし、\n腰を痛めていたら動けないだろう？
370 = "私のように早期回復は望めないし、\\n腰を痛めていたら動けないだろう？"

# カズマ
# うぅ、ご迷惑をおかけしますが、\nお願いできますか？
263 = "うぅ、ご迷惑をおかけしますが、\\nお願いできますか？"

# ダクネス
# ああ、任せておけ！
260 = "ああ、任せておけ！"

# カズマ（Ｍ）
# display as カズマ
# （うぅぅ、もうちょっと体を鍛えよう）
377 = "（うぅぅ、もうちょっと体を鍛えよう）"

[selections]
292 = "でも、もっと痩せてくれ！"
# 270 = "これくらい平気だ！"
314 = "もっとしっかりしがみついてくれ～！"
