# rew_f01.txt.scn

[info]
194 = "rew_f01"

[characters]
289 = "ウィズ"
293 = "カズマ"
294 = "カズマ（Ｍ）"

[character_subs]
# 293 = "カズマ"

[script]
# lines: 70

# ウィズ
# お、お待たせしました。
256 = "お、お待たせしました。"

# カズマ
# うん、やっぱりいい！
247 = "うん、やっぱりいい！"

# ウィズ
# え、何がですか？
251 = "え、何がですか？"

# カズマ
# ウィズのメイド服姿だよ。\n気品があるっていうかさ、とにかく素晴らしいぞ！
291 = "ウィズのメイド服姿だよ。\\n気品があるっていうかさ、とにかく素晴らしいぞ！"

# ウィズ
# カ、カズマさんの目が恐いですよ？
292 = "カ、カズマさんの目が恐いですよ？"

# カズマ
# あ、いや。ウィズがあまりにも可愛すぎた\nからで、そりゃガン見しちゃうってもんだろ！
237 = "あ、いや。ウィズがあまりにも可愛すぎた\\nからで、そりゃガン見しちゃうってもんだろ！"

# ウィズ
# そ、それであの、この格好で何をすれば。
260 = "そ、それであの、この格好で何をすれば。"

# カズマ
# メイドといえば、ご奉仕です。
297 = "メイドといえば、ご奉仕です。"

# ウィズ
# ええと、ご奉仕というと……。
252 = "ええと、ご奉仕というと……。"

# カズマ
# メイドってのはほら、ご主人様に仕えるものだろ？
296 = "メイドってのはほら、ご主人様に仕えるものだろ？"

# ウィズ
# はぁ、それはそうですね。
275 = "はぁ、それはそうですね。"

# カズマ
# だったら、一番重要なのは、主人を癒すことだ！
264 = "だったら、一番重要なのは、主人を癒すことだ！"

# ウィズ
# そ、そうなんですか？
259 = "そ、そうなんですか？"

# カズマ
# そう！　そうとも！　仕事に疲れ、対人関係に疲れ、\n世界に疲れた男を癒してくれるのは、ただ一つ！\nメイドのご奉仕だけなんだよ！
261 = "そう！　そうとも！　仕事に疲れ、対人関係に疲れ、\\n世界に疲れた男を癒してくれるのは、ただ一つ！\\nメイドのご奉仕だけなんだよ！"

# ウィズ
# つまり甘えさせてくれる相手がいない人のための、\n甘える相手を務める、ということですね！
265 = "つまり甘えさせてくれる相手がいない人のための、\\n甘える相手を務める、ということですね！"

# カズマ
# ま、まあそういうことだな。\nなんかすっごいダメージ負った気がするが。
283 = "ま、まあそういうことだな。\\nなんかすっごいダメージ負った気がするが。"

# カズマ
# ともかく！　甘えさせてもらうぞ！　ウィズ！
268 = "ともかく！　甘えさせてもらうぞ！　ウィズ！"

# ウィズ
# は、はい！\nええと、ご、ご主人様！？
273 = "は、はい！\\nええと、ご、ご主人様！？"

# カズマ
# てーい！！
266 = "てーい！！"

# ウィズ
# え、きゃ！！
250 = "え、きゃ！！"

# カズマ
# ああ、いいわー、柔らかいわー。
238 = "ああ、いいわー、柔らかいわー。"

# ウィズ
# あのあの、これはいったい。
240 = "あのあの、これはいったい。"

# カズマ
# 癒やしですよ？
302 = "癒やしですよ？"

# ウィズ
# え、ええと、胸に顔を埋める意味が。
248 = "え、ええと、胸に顔を埋める意味が。"

# カズマ
# 癒やしなんですよ？
303 = "癒やしなんですよ？"

# ウィズ
# ですが、まるで赤ちゃんのようで……。
267 = "ですが、まるで赤ちゃんのようで……。"

# カズマ
# ウィズ。
290 = "ウィズ。"

# ウィズ
# は、はい！
272 = "は、はい！"

# カズマ
# 頭を抱きしめてください。
332 = "頭を抱きしめてください。"

# ウィズ
# うぅ、わかりました。
246 = "うぅ、わかりました。"

# カズマ
# はぁぁ～～～～、最高だぜウィズ！！
277 = "はぁぁ～～～～、最高だぜウィズ！！"

# ウィズ
# は、はあ。\nカズマさんが気持ちいいのでしたら、\nいいんですが、ちょっと、恥ずかしいです。
270 = "は、はあ。\\nカズマさんが気持ちいいのでしたら、\\nいいんですが、ちょっと、恥ずかしいです。"

# カズマ
# こらっ！　今はカズマじゃなくて、ご主人様だ！
257 = "こらっ！　今はカズマじゃなくて、ご主人様だ！"

# ウィズ
# は、はい！！　申し訳ありません、ご主人様。\nそれじゃ、何かリクエストはありますか？
274 = "は、はい！！　申し訳ありません、ご主人様。\\nそれじゃ、何かリクエストはありますか？"

# カズマ
# ん？　お、いいぞ。ご奉仕の精神がわかってきたな。\nそれじゃ……。
288 = "ん？　お、いいぞ。ご奉仕の精神がわかってきたな。\\nそれじゃ……。"

# カズマ
# それじゃ、そのまま頭を撫でてくれないか？
262 = "それじゃ、そのまま頭を撫でてくれないか？"

# ウィズ
# 頭ですか？　それくらいでしたら、はい。
331 = "頭ですか？　それくらいでしたら、はい。"

# カズマ
# ふう、いいな。\n思わず寝てしまいそうだ。
279 = "ふう、いいな。\\n思わず寝てしまいそうだ。"

# ウィズ
# これくらいでですか？\nもしかして、疲れてます？
258 = "これくらいでですか？\\nもしかして、疲れてます？"

# カズマ
# ああ、毎日毎日、あの面子の相手をしてれば、\nそりゃなあ。
239 = "ああ、毎日毎日、あの面子の相手をしてれば、\\nそりゃなあ。"

# ウィズ
# ふふ、相変わらずご主人様はご苦労されて\nいらっしゃるのですね。
281 = "ふふ、相変わらずご主人様はご苦労されて\\nいらっしゃるのですね。"

# カズマ
# 全くだ。\nこんな俺を癒してくれるのはウィズだけだよ……。
299 = "全くだ。\\nこんな俺を癒してくれるのはウィズだけだよ……。"

# カズマ
# それじゃ、褒めてくれ！
263 = "それじゃ、褒めてくれ！"

# ウィズ
# え、ええ！？
249 = "え、ええ！？"

# カズマ
# なんでもいいから、俺を褒めろ、褒め称えろ！！
269 = "なんでもいいから、俺を褒めろ、褒め称えろ！！"

# ウィズ
# は、はあ。ええと……ご主人様、素敵です！
271 = "は、はあ。ええと……ご主人様、素敵です！"

# ウィズ
# いつも頑張ってらして、度重なる苦労にもめげずに\n格好いいです！　尊敬します！
244 = "いつも頑張ってらして、度重なる苦労にもめげずに\\n格好いいです！　尊敬します！"

# カズマ（Ｍ）
# display as カズマ
# （ぐおおお！！　思った以上に破壊力がひどい！！）
336 = "（ぐおおお！！　思った以上に破壊力がひどい！！）"

# ウィズ
# あ、あれ？\nご主人様、なんで泣いて？
236 = "あ、あれ？\\nご主人様、なんで泣いて？"

# カズマ
# い、いや、何でもないぞ……うう、褒められることが\nこんなに嬉しいなんて。
242 = "い、いや、何でもないぞ……うう、褒められることが\\nこんなに嬉しいなんて。"

# ウィズ
# 苦労してるんですね、カズマさん。
328 = "苦労してるんですね、カズマさん。"

# カズマ
# ほら、抱きしめる力が緩んでるぞ。\nしっかり抱きしめなさい。
282 = "ほら、抱きしめる力が緩んでるぞ。\\nしっかり抱きしめなさい。"

# ウィズ
# わ、わかりました！\nぎゅっ……。
286 = "わ、わかりました！\\nぎゅっ……。"

# カズマ（Ｍ）
# display as カズマ
# （ああ……なんて安らぐんだ。これが、遠い昔……\n　母に抱かれていた時の記憶ってヤツか）
335 = "（ああ……なんて安らぐんだ。これが、遠い昔……\\n　母に抱かれていた時の記憶ってヤツか）"

# カズマ（Ｍ）
# display as カズマ
# （安心させるかのように、ウィズの心音が……\n　あ、この人リッチーだから絶対聞こえねえ）
339 = "（安心させるかのように、ウィズの心音が……\\n　あ、この人リッチーだから絶対聞こえねえ）"

# カズマ
# はぁぁぁ、堪能した。
276 = "はぁぁぁ、堪能した。"

# ウィズ
# あんなので良かったんですか？
241 = "あんなので良かったんですか？"

# カズマ
# ん……い、いや！\n俺は全然満足していないぞ！！
287 = "ん……い、いや！\\n俺は全然満足していないぞ！！"

# ウィズ
# えっ、今、堪能したって言いましたよね？
254 = "えっ、今、堪能したって言いましたよね？"

# カズマ
# いや、まだまだだ！\nこれくらいではご奉仕の神髄に\n迫ったとは言えない。
245 = "いや、まだまだだ！\\nこれくらいではご奉仕の神髄に\\n迫ったとは言えない。"

# カズマ
# もっと、もっとご奉仕してもらわないと！\nそのためには、お仕置きというのも知って\nおかないとな！
284 = "もっと、もっとご奉仕してもらわないと！\\nそのためには、お仕置きというのも知って\\nおかないとな！"

# ウィズ
# え？　カズマさん、なんか目が恐いですよ？
255 = "え？　カズマさん、なんか目が恐いですよ？"

# カズマ
# ふっふふふっ。\nそれじゃ次は、ダメなメイドにご主人様が\nお仕置きをするターンに入ろうか……！
280 = "ふっふふふっ。\\nそれじゃ次は、ダメなメイドにご主人様が\\nお仕置きをするターンに入ろうか……！"

# カズマ
# ひっひひひひ、ほれ、ほれほれ……！
278 = "ひっひひひひ、ほれ、ほれほれ……！"

# ウィズ
# えっ、い、いやっ\n何ですか、その手の動きはぁ！？
253 = "えっ、い、いやっ\\n何ですか、その手の動きはぁ！？"

# カズマ
# 見ての通りだ、これをこうして……。
330 = "見ての通りだ、これをこうして……。"

# カズマ（Ｍ）
# display as カズマ
# （わきわきわき）
338 = "（わきわきわき）"

# ウィズ
# い、いやぁぁぁっ、ち、近寄らないで下さいっ！\n来ないでえぇぇぇぇぇ！！！
243 = "い、いやぁぁぁっ、ち、近寄らないで下さいっ！\\n来ないでえぇぇぇぇぇ！！！"

# カズマ（Ｍ）
# display as カズマ
# （……しまった、やり過ぎたか）
334 = "（……しまった、やり過ぎたか）"

# カズマ（Ｍ）
# display as カズマ
# （まあでも、ものすごくいい体験をしたから良しと\n　しよう！）
337 = "（まあでも、ものすごくいい体験をしたから良しと\\n　しよう！）"

[selections]
333 = "頭を撫でてくれ"
329 = "褒めてくれ！"
285 = "もっと強く抱きしめてくれ"
