# rew_b06.txt.scn

[info]
223 = "rew_b06"

[characters]
307 = "カズマ"
302 = "めぐみん"
309 = "カズマ（Ｍ）"

[character_subs]
# 307 = "カズマ"

[script]
# lines: 83

# カズマ
# で、俺に何をさせようっていうんだ？
284 = "で、俺に何をさせようっていうんだ？"

# めぐみん
# それなのですが、\n実のところまだ決めていません。
278 = "それなのですが、\\n実のところまだ決めていません。"

# カズマ
# あのな～、こっちだって暇じゃないんだから\nしっかりしてくれよ。
249 = "あのな～、こっちだって暇じゃないんだから\\nしっかりしてくれよ。"

# めぐみん
# 何を言ってるんですか、\n一日中ブラブラしているだけのくせに。
315 = "何を言ってるんですか、\\n一日中ブラブラしているだけのくせに。"

# カズマ
# くせにとはなんだくせにとは！\nめぐみんの目にはそう見えるかもしれないが、\n俺は忙しいんだよ！
269 = "くせにとはなんだくせにとは！\\nめぐみんの目にはそう見えるかもしれないが、\\n俺は忙しいんだよ！"

# めぐみん
# へぇ～、そうですか。
297 = "へぇ～、そうですか。"

# カズマ（Ｍ）
# display as カズマ
# （あからさまに興味のない顔しやがって！）
367 = "（あからさまに興味のない顔しやがって！）"

# めぐみん
# じゃあ、仕方がありませんね。\nそれでは肩を揉んでください。
274 = "じゃあ、仕方がありませんね。\\nそれでは肩を揉んでください。"

# カズマ
# はいはい、わかったよ。\nこの俺のテクニックに酔いしれるがいい！
293 = "はいはい、わかったよ。\\nこの俺のテクニックに酔いしれるがいい！"

# カズマ（Ｍ）
# display as カズマ
# （うわっ、細っ！\n　小さい小さいとは思っていたが、\n　なんて細い体なんだ）
369 = "（うわっ、細っ！\\n　小さい小さいとは思っていたが、\\n　なんて細い体なんだ）"

# カズマ（Ｍ）
# display as カズマ
# （おまけにこんなに細いのに柔らかい……\n　こんな幼児体型でもやっぱり男とは\n　違うだな）
370 = "（おまけにこんなに細いのに柔らかい……\\n　こんな幼児体型でもやっぱり男とは\\n　違うだな）"

# めぐみん
# なにを固まっているのです。\n手を動かさなくては肩は揉めませんよ？
290 = "なにを固まっているのです。\\n手を動かさなくては肩は揉めませんよ？"

# カズマ
# いや……、\nめぐみんも一応女の子なんだな。
257 = "いや……、\\nめぐみんも一応女の子なんだな。"

# めぐみん
# 何を当たり前のことを言っているのですか？\nどこからどう見ても立派な乙女ではないですか。
313 = "何を当たり前のことを言っているのですか？\\nどこからどう見ても立派な乙女ではないですか。"

# めぐみん
# それに一応とはなんですか一応とは！！
279 = "それに一応とはなんですか一応とは！！"

# めぐみん
# まるで今の今まで\n異性として見ていなかったかのような\n口ぶりですね！
301 = "まるで今の今まで\\n異性として見ていなかったかのような\\n口ぶりですね！"

# カズマ
# お前のどこに異性を意識する要素があると\n言うんだ？
265 = "お前のどこに異性を意識する要素があると\\n言うんだ？"

# めぐみん
# そんなだからカズマはモテないんですよ。
281 = "そんなだからカズマはモテないんですよ。"

# カズマ（Ｍ）
# display as カズマ
# （く、くそ、正論をぶち込みやがって！）
371 = "（く、くそ、正論をぶち込みやがって！）"

# めぐみん
# それより早くしてください、\nこのままでは夜が明けてしまいます。
280 = "それより早くしてください、\\nこのままでは夜が明けてしまいます。"

# カズマ（Ｍ）
# display as カズマ
# （そうだな。\n　さっさと終わらせてひとっ風呂浴びよう）
372 = "（そうだな。\\n　さっさと終わらせてひとっ風呂浴びよう）"

# カズマ
# じゃあ、始めるぞ。\nよいしょっと！
275 = "じゃあ、始めるぞ。\\nよいしょっと！"

# めぐみん
# あはははは！\nちょ、ちょっと待ってください！
252 = "あはははは！\\nちょ、ちょっと待ってください！"

# カズマ
# なんだよ。\nまだ始めたばかりじゃないか？
291 = "なんだよ。\\nまだ始めたばかりじゃないか？"

# めぐみん
# くすぐったいんですから仕方がないじゃないですか。\nもう少し力を入れてください。
268 = "くすぐったいんですから仕方がないじゃないですか。\\nもう少し力を入れてください。"

# カズマ
# わかったよ。\nくすぐったくないように力強くっ！\nこうか？
305 = "わかったよ。\\nくすぐったくないように力強くっ！\\nこうか？"

# めぐみん
# 痛たたたた！\n痛い、痛たすぎます。\n私の肩を壊す気ですか！？
324 = "痛たたたた！\\n痛い、痛たすぎます。\\n私の肩を壊す気ですか！？"

# カズマ
# 優しくすればくすぐったい、\n力を入れれば痛いって……\nなんてワガママなやつなんだ。
318 = "優しくすればくすぐったい、\\n力を入れれば痛いって……\\nなんてワガママなやつなんだ。"

# めぐみん
# カズマは極端なんですよ。
308 = "カズマは極端なんですよ。"

# カズマ
# じゃあ、少しずつ力を入れていくから\nいいところで声をかけてくれ。
276 = "じゃあ、少しずつ力を入れていくから\\nいいところで声をかけてくれ。"

# めぐみん
# わかりました。
306 = "わかりました。"

# カズマ（Ｍ）
# display as カズマ
# （まずは軽くっと）
375 = "（まずは軽くっと）"

# めぐみん
# あはははは！\nくすぐったい、くすぐったいですってば！
251 = "あはははは！\\nくすぐったい、くすぐったいですってば！"

# カズマ
# 少し我慢しろ。
322 = "少し我慢しろ。"

# めぐみん
# あはははは！
250 = "あはははは！"

# カズマ（Ｍ）
# display as カズマ
# （少しずつ力を入れて――）
376 = "（少しずつ力を入れて――）"

# めぐみん
# おっ、くすぐったくなくなりましたね。\nでももう少し強めの方が私好みです。
264 = "おっ、くすぐったくなくなりましたね。\\nでももう少し強めの方が私好みです。"

# カズマ
# これでどうだ？
272 = "これでどうだ？"

# めぐみん
# お～、いいですね。かなりいい！\nこの強さでお願いします。
266 = "お～、いいですね。かなりいい！\\nこの強さでお願いします。"

# カズマ
# 了解。\n揉み揉み揉み揉み。
312 = "了解。\\n揉み揉み揉み揉み。"

# めぐみん
# くぅ～、なかなか上手いじゃないですか、\n冒険者など辞めてマッサージ師にでも\nなったらどうです？
267 = "くぅ～、なかなか上手いじゃないですか、\\n冒険者など辞めてマッサージ師にでも\\nなったらどうです？"

# カズマ
# へいへい、そうですかそうですか。
296 = "へいへい、そうですかそうですか。"

# めぐみん
# あ～、本当にぃ……気持ちよくてとろけそうです。
253 = "あ～、本当にぃ……気持ちよくてとろけそうです。"

# カズマ（Ｍ）
# display as カズマ
# （気持ちよさそうに目を細めちゃって、\n　だけどこっちは早くも手が疲れてきたぞ、\n　どんどん握力が落ちていく）
377 = "（気持ちよさそうに目を細めちゃって、\\n　だけどこっちは早くも手が疲れてきたぞ、\\n　どんどん握力が落ちていく）"

# カズマ（Ｍ）
# display as カズマ
# （あー、無理！　もう無理だこれ！）
368 = "（あー、無理！　もう無理だこれ！）"

# カズマ
# よし、お終い！　お疲れ！
304 = "よし、お終い！　お疲れ！"

# めぐみん
# 何を言っているのです？\nまだ始まったばかりではありませんか。
314 = "何を言っているのです？\\nまだ始まったばかりではありませんか。"

# カズマ
# 十分ほぐれただろう。
320 = "十分ほぐれただろう。"

# めぐみん
# 全然足りません、満足には程遠すぎます。\nさあ、続けて続けて。
319 = "全然足りません、満足には程遠すぎます。\\nさあ、続けて続けて。"

# カズマ（Ｍ）
# display as カズマ
# （なんとかして終わりにできないものか？\n　なんとか、なんとか――）
373 = "（なんとかして終わりにできないものか？\\n　なんとか、なんとか――）"

# カズマ
# めぐみんって、セクシーなうなじしてるな。
303 = "めぐみんって、セクシーなうなじしてるな。"

# めぐみん
# な、何を急に言い出すんです！？
288 = "な、何を急に言い出すんです！？"

# カズマ
# いや、お子様お子様と思っていたけど、\nそこはかとない色気を感じる。
258 = "いや、お子様お子様と思っていたけど、\\nそこはかとない色気を感じる。"

# めぐみん
# え……そうですか？
262 = "え……そうですか？"

# カズマ
# というわけで、ほーら、もっと密着して。
285 = "というわけで、ほーら、もっと密着して。"

# めぐみん
# ちょっ、くっつく理由がわかりません！
283 = "ちょっ、くっつく理由がわかりません！"

# カズマ
# ほらほら、めぐみん\nうなじをもっと見せて。
299 = "ほらほら、めぐみん\\nうなじをもっと見せて。"

# カズマ
# 直接肌を触った方が\n効果があるんじゃないか？
363 = "直接肌を触った方が\\n効果があるんじゃないか？"

# めぐみん
# な、何を言い出すんですか！？
289 = "な、何を言い出すんですか！？"

# カズマ
# いやなに、手と肌の間に余計な物があると\n邪魔だろ？
260 = "いやなに、手と肌の間に余計な物があると\\n邪魔だろ？"

# カズマ
# せっかくやるなら、１００％の力を\n伝えたいじゃないか。
277 = "せっかくやるなら、１００％の力を\\n伝えたいじゃないか。"

# めぐみん
# い、今のままでも十分ですよ！
254 = "い、今のままでも十分ですよ！"

# カズマ
# 俺の職人魂が妥協を許さないんだよ。
316 = "俺の職人魂が妥協を許さないんだよ。"

# めぐみん
# いつから職人になったんですか、あなたは！？
256 = "いつから職人になったんですか、あなたは！？"

# カズマ
# さあさあ、ちょっと服を脱いでみようか？
273 = "さあさあ、ちょっと服を脱いでみようか？"

# めぐみん
# ほ、本気ですか！？
298 = "ほ、本気ですか！？"

# カズマ
# 俺はいつだって本気さ！
317 = "俺はいつだって本気さ！"

# カズマ
# 肩だけじゃなく腰や足も揉んでやろうか？
366 = "肩だけじゃなく腰や足も揉んでやろうか？"

# めぐみん
# おおー、それは至れり尽くせりですね。
263 = "おおー、それは至れり尽くせりですね。"

# カズマ
# だろ～？\nせっかくだし、全身隅々まで余すところなく\nほぐしてやるよ。
282 = "だろ～？\\nせっかくだし、全身隅々まで余すところなく\\nほぐしてやるよ。"

# めぐみん
# あの、目が怖いんですが……。
248 = "あの、目が怖いんですが……。"

# カズマ
# どうして逃げるのさ。\n俺はただ、全身をくまなく\nマッサージしてやろうって言ってるだけだぞ。
286 = "どうして逃げるのさ。\\n俺はただ、全身をくまなく\\nマッサージしてやろうって言ってるだけだぞ。"

# めぐみん
# いや、ちょっとやめてください！
259 = "いや、ちょっとやめてください！"

# カズマ
# この二の腕のぷにぷにした感覚が\nまた堪らないな。
271 = "この二の腕のぷにぷにした感覚が\\nまた堪らないな。"

# めぐみん
# ひう！？　腕を揉まないでください！
295 = "ひう！？　腕を揉まないでください！"

# カズマ
# いいからいいから、\n遠慮するなって。
255 = "いいからいいから、\\n遠慮するなって。"

# カズマ
# ほ～らほらほら。
300 = "ほ～らほらほら。"

# めぐみん
# はは～ん、読めましたよ。\nさてはドン引きせて肩もみを\n切り上げさせようという魂胆ですね？
294 = "はは～ん、読めましたよ。\\nさてはドン引きせて肩もみを\\n切り上げさせようという魂胆ですね？"

# カズマ
# な、なんのことかサッパリだな。
287 = "な、なんのことかサッパリだな。"

# めぐみん
# バレバレですよ。\n無駄な抵抗をせず大人しく続けてください。
311 = "バレバレですよ。\\n無駄な抵抗をせず大人しく続けてください。"

# カズマ
# くっ……やれやれ……。
270 = "くっ……やれやれ……。"

# めぐみん
# はぁぁ、たまりませんね～。
292 = "はぁぁ、たまりませんね～。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、喜んでくれてるみたいだし、\n　たまにはこんなのもいいか）
374 = "（まあ、喜んでくれてるみたいだし、\\n　たまにはこんなのもいいか）"

[selections]
261 = "うなじがセクシーだな"
364 = "直接肌を触った方が効果があるんじゃないか？"
365 = "肩だけじゃなく腰や足も……"
