# rew_c06.txt.scn

[info]
235 = "rew_c06"

[characters]
312 = "カズマ"
310 = "アクア"
309 = "めぐみん"
319 = "ダクネス"
316 = "カズマ（Ｍ）"

[character_subs]
# 312 = "カズマ"

[script]
# lines: 88

# カズマ
# いたたたたたっ！\nお、お前らっ、やめろって！
264 = "いたたたたたっ！\\nお、お前らっ、やめろって！"

# アクア
# ダメよ！\nこれはお仕置きなんだから受け入れなさい。
321 = "ダメよ！\\nこれはお仕置きなんだから受け入れなさい。"

# めぐみん
# そうですよ。\n罪を犯した者は、相応の罰を受けるのです。
286 = "そうですよ。\\n罪を犯した者は、相応の罰を受けるのです。"

# ダクネス
# な、なあ、いくらなんでも縛るというのは\nやり過ぎじゃないのか？
298 = "な、なあ、いくらなんでも縛るというのは\\nやり過ぎじゃないのか？"

# カズマ
# そうだ、そうだ！
285 = "そうだ、そうだ！"

# アクア
# いいのよ、こいつはそれだけのことを\nやってるんだから。
263 = "いいのよ、こいつはそれだけのことを\\nやってるんだから。"

# めぐみん
# ふん、乙女の下着を盗むなんて言語道断です！
308 = "ふん、乙女の下着を盗むなんて言語道断です！"

# カズマ
# あれは俺の意思じゃ無いってわかってるだろ！
260 = "あれは俺の意思じゃ無いってわかってるだろ！"

# カズマ
# それに今日は満月の夜じゃ無いんだから、\n縛る必要なんてないじゃねーか！
289 = "それに今日は満月の夜じゃ無いんだから、\\n縛る必要なんてないじゃねーか！"

# アクア
# それはわかってるけど、\nいいお仕置きが何も思いつかなかったのよ。
290 = "それはわかってるけど、\\nいいお仕置きが何も思いつかなかったのよ。"

# カズマ
# だからって縛るとかわけわからないから！
291 = "だからって縛るとかわけわからないから！"

# アクア
# これをいい機会だと思って、\n今晩はそのままの格好でじっくり反省しなさい。
278 = "これをいい機会だと思って、\\n今晩はそのままの格好でじっくり反省しなさい。"

# カズマ
# おいおいおいおい！　まさか放置するつもりか！？
272 = "おいおいおいおい！　まさか放置するつもりか！？"

# めぐみん
# あ、トイレに行きたくなったら、\nこの花瓶を使ってください。
258 = "あ、トイレに行きたくなったら、\\nこの花瓶を使ってください。"

# カズマ
# お前っ、き、鬼畜か！
274 = "お前っ、き、鬼畜か！"

# アクア
# あーっ、なんだか今夜はぐっすり眠れそうだわ。
262 = "あーっ、なんだか今夜はぐっすり眠れそうだわ。"

# めぐみん
# それでは、お休みなさい。\nよい夢を。
288 = "それでは、お休みなさい。\\nよい夢を。"

# カズマ
# こんな状況でみられるか！
280 = "こんな状況でみられるか！"

# カズマ（Ｍ）
# display as カズマ
# （くっそっ、本当に行っちまいやがった）
377 = "（くっそっ、本当に行っちまいやがった）"

# カズマ（Ｍ）
# display as カズマ
# （しかも結構しっかり縛ってあるし、\n　くぅ、肌に食い込んで痛てぇ）
381 = "（しかも結構しっかり縛ってあるし、\\n　くぅ、肌に食い込んで痛てぇ）"

# ダクネス
# カズマ、大丈夫か？
314 = "カズマ、大丈夫か？"

# カズマ
# おお！　ダクネス助けに来てくれたか！
273 = "おお！　ダクネス助けに来てくれたか！"

# ダクネス
# いや、そういうわけじゃないんだが。
266 = "いや、そういうわけじゃないんだが。"

# カズマ
# じゃあ、縛られて床を這いずり回る俺を\nせせら笑いに来たのか。
282 = "じゃあ、縛られて床を這いずり回る俺を\\nせせら笑いに来たのか。"

# ダクネス
# 見くびるな。\n仲間を馬鹿にするようなことはしない。
368 = "見くびるな。\\n仲間を馬鹿にするようなことはしない。"

# カズマ
# だったら何しに来たんだよ。
293 = "だったら何しに来たんだよ。"

# ダクネス
# そ、それは……。
283 = "そ、それは……。"

# カズマ
# あー、もうっ！\n今は、お前に構ってる暇はないんだって。
261 = "あー、もうっ！\\n今は、お前に構ってる暇はないんだって。"

# カズマ（Ｍ）
# display as カズマ
# （くぅぅ、このままだとすぐに\n　花瓶のお世話になりそうだ）
371 = "（くぅぅ、このままだとすぐに\\n　花瓶のお世話になりそうだ）"

# カズマ（Ｍ）
# display as カズマ
# （くっそっ、あいつらガッチガチに縛りやがって！）
376 = "（くっそっ、あいつらガッチガチに縛りやがって！）"

# カズマ（Ｍ）
# display as カズマ
# （ここをこうして、手首を抜けばっ……）
380 = "（ここをこうして、手首を抜けばっ……）"

# カズマ
# いででででで！！
265 = "いででででで！！"

# ダクネス
# お、おお。
271 = "お、おお。"

# カズマ（Ｍ）
# display as カズマ
# （無理だ、肩の関節を外さない限り\n　これは抜けられない）
389 = "（無理だ、肩の関節を外さない限り\\n　これは抜けられない）"

# カズマ
# ふぉお！　お、お、おお！！
306 = "ふぉお！　お、お、おお！！"

# ダクネス
# ハァハァハァ。
322 = "ハァハァハァ。"

# カズマ（Ｍ）
# display as カズマ
# （で、でも、早くしないと人としての自尊心が！）
383 = "（で、でも、早くしないと人としての自尊心が！）"

# カズマ（Ｍ）
# display as カズマ
# （くはっ、もうダメっ！　げ、限界が近いっ！！）
379 = "（くはっ、もうダメっ！　げ、限界が近いっ！！）"

# ダクネス
# カ、カズマ？
311 = "カ、カズマ？"

# カズマ
# なんだよ！
304 = "なんだよ！"

# ダクネス
# な、なんだか、楽しそうだな。
299 = "な、なんだか、楽しそうだな。"

# カズマ（Ｍ）
# display as カズマ
# （くっそ、ハァハァしやがって、このドＭ騎士め！）
375 = "（くっそ、ハァハァしやがって、このドＭ騎士め！）"

# カズマ（Ｍ）
# display as カズマ
# （くっはっ、今はダクネスの性癖に\n　つきあってる場合じゃなかった！）
378 = "（くっはっ、今はダクネスの性癖に\\n　つきあってる場合じゃなかった！）"

# カズマ（Ｍ）
# display as カズマ
# （くぅぉお、この窮地から脱するには\n　どうしたらいい考えろ、考えるんだ俺！）
372 = "（くぅぉお、この窮地から脱するには\\n　どうしたらいい考えろ、考えるんだ俺！）"

# カズマ（Ｍ）
# display as カズマ
# （よし、ダクネスが縄をとくように仕向けよう）
387 = "（よし、ダクネスが縄をとくように仕向けよう）"

# カズマ
# な、なぁダクネス。\n悪いけど、少し縄を緩めてくれないか？\n肉に食い込んだ所が痛くて仕方ないんだ。
297 = "な、なぁダクネス。\\n悪いけど、少し縄を緩めてくれないか？\\n肉に食い込んだ所が痛くて仕方ないんだ。"

# ダクネス
# なっ、なに！？　荒縄が肉に食い込むほど\n縛られているのか！！
303 = "なっ、なに！？　荒縄が肉に食い込むほど\\n縛られているのか！！"

# ダクネス
# そ、それはどんな気分なんだ？
284 = "そ、それはどんな気分なんだ？"

# カズマ
# 最低な気分だよ！
333 = "最低な気分だよ！"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、そうだよな。\n　ダクネスならこういう反応するよな）
385 = "（はぁ、そうだよな。\\n　ダクネスならこういう反応するよな）"

# カズマ（Ｍ）
# display as カズマ
# （って、うぉお！　また尿意がっ！）
382 = "（って、うぉお！　また尿意がっ！）"

# カズマ（Ｍ）
# display as カズマ
# （くっ、仕方ない。\n　こうなったら泣いてすがりつこう）
374 = "（くっ、仕方ない。\\n　こうなったら泣いてすがりつこう）"

# カズマ
# うぅ、なあ、ダクネス。\n頼むからこの縄をといてくれよ。
267 = "うぅ、なあ、ダクネス。\\n頼むからこの縄をといてくれよ。"

# カズマ
# こんな屈辱、俺には耐えられないんだ！
279 = "こんな屈辱、俺には耐えられないんだ！"

# ダクネス
# といてやりたいのは山々だが、\n私の一存で決められることではないんだ。
294 = "といてやりたいのは山々だが、\\n私の一存で決められることではないんだ。"

# カズマ
# そこをなんとか折れてくれよ。\nこんな風に情けなく頼めるのは、\nダクネスだからこそなんだ。
287 = "そこをなんとか折れてくれよ。\\nこんな風に情けなく頼めるのは、\\nダクネスだからこそなんだ。"

# ダクネス
# カズマ……。
313 = "カズマ……。"

# カズマ
# うぐおっ、早くしてくれないとっ！
268 = "うぐおっ、早くしてくれないとっ！"

# ダクネス
# ど、どうした？　どこか痛いのか。
295 = "ど、どうした？　どこか痛いのか。"

# カズマ（Ｍ）
# display as カズマ
# （くぅっ、うぉお！\n　も、も、漏れるぅぅ～～！！）
373 = "（くぅっ、うぉお！\\n　も、も、漏れるぅぅ～～！！）"

# カズマ（Ｍ）
# display as カズマ
# （仕方ない、こうなったらダクネスに頼むしか！）
388 = "（仕方ない、こうなったらダクネスに頼むしか！）"

# カズマ
# ダクネス！　１つお願いが！
320 = "ダクネス！　１つお願いが！"

# ダクネス
# な、なんだ？
300 = "な、なんだ？"

# カズマ
# あっ、えっと、その、ええと……。
259 = "あっ、えっと、その、ええと……。"

# ダクネス
# どうした私に出来ることならなんでもするぞ？
296 = "どうした私に出来ることならなんでもするぞ？"

# カズマ
# うっ、はぅ！\nその前にひとつだけ確認してもいいか？
269 = "うっ、はぅ！\\nその前にひとつだけ確認してもいいか？"

# ダクネス
# うむ、なんでも聞いてくれ。
270 = "うむ、なんでも聞いてくれ。"

# カズマ
# 俺たちって仲間だよな？
326 = "俺たちって仲間だよな？"

# ダクネス
# 何を今さらくだらないことを。
325 = "何を今さらくだらないことを。"

# カズマ
# だったら、俺がどんな頼みをしても、\nその、嫌ったりしないよな？
292 = "だったら、俺がどんな頼みをしても、\\nその、嫌ったりしないよな？"

# ダクネス
# 当然だろう。
331 = "当然だろう。"

# カズマ
# じゃ、じゃあ……か、か、かび……んを。
281 = "じゃ、じゃあ……か、か、かび……んを。"

# ダクネス
# かび？　なんだそれは。
275 = "かび？　なんだそれは。"

# カズマ（Ｍ）
# display as カズマ
# （くああああああ、そんなの頼めるわけねー！！）
370 = "（くああああああ、そんなの頼めるわけねー！！）"

# ダクネス
# カズマ？
317 = "カズマ？"

# カズマ
# 悪い、なんでもない、忘れてくれ。
332 = "悪い、なんでもない、忘れてくれ。"

# カズマ（Ｍ）
# display as カズマ
# （とは言ったものの、うおふ！\n　も、もう、尿意がっ！！）
384 = "（とは言ったものの、うおふ！\\n　も、もう、尿意がっ！！）"

# カズマ
# ダ、ダクネス頼む、すぐにこの縄をといてくれ！
318 = "ダ、ダクネス頼む、すぐにこの縄をといてくれ！"

# カズマ（Ｍ）
# display as カズマ
# （あ、あかん、もう先っぽまで来てるぅぅ！！）
369 = "（あ、あかん、もう先っぽまで来てるぅぅ！！）"

# ダクネス
# なあ、カズマ、私なりに色々考えたのだが。
302 = "なあ、カズマ、私なりに色々考えたのだが。"

# カズマ
# な、何をですか！？
301 = "な、何をですか！？"

# ダクネス
# カズマばかりに苦痛を感じさせるのは、\n仲間として忍びない！
315 = "カズマばかりに苦痛を感じさせるのは、\\n仲間として忍びない！"

# ダクネス
# こ、ここは、私も縛るというのはどうだろう！
277 = "こ、ここは、私も縛るというのはどうだろう！"

# カズマ
# はぁぁ？
305 = "はぁぁ？"

# ダクネス
# 私も、その痛みをぜひ味わい――\nいや、仲間としてカズマと分かち合いたいんだ！
366 = "私も、その痛みをぜひ味わい――\\nいや、仲間としてカズマと分かち合いたいんだ！"

# カズマ
# くおおおおおお！　このドＭ騎士めっ！！
276 = "くおおおおおお！　このドＭ騎士めっ！！"

# ダクネス
# ふふ、なるほど、まずは罵倒から再現すると\nいうわけか。
307 = "ふふ、なるほど、まずは罵倒から再現すると\\nいうわけか。"

# カズマ（Ｍ）
# display as カズマ
# （もうやだ。\n　誰かこのドＭ騎士をどうにかして……）
386 = "（もうやだ。\\n　誰かこのドＭ騎士をどうにかして……）"

[selections]
367 = "縄をとくように仕向けよう"
334 = "泣いてすがりつこう"
324 = "仕方ない、ダクネスに頼むか"
