# rew_a08.txt.scn

[info]
187 = "rew_a08"

[characters]
269 = "カズマ"
265 = "アクア"
271 = "カズマ（Ｍ）"

[character_subs]
# 269 = "カズマ"

[script]
# lines: 74

# カズマ
# まったく、なんで俺がアクアのために\n料理なんてしないといけないんだ。
256 = "まったく、なんで俺がアクアのために\\n料理なんてしないといけないんだ。"

# アクア
# カズマさーん、まだですか？\nもう、お腹がぺこぺこで死んじゃい\nそうなんですけど。
270 = "カズマさーん、まだですか？\\nもう、お腹がぺこぺこで死んじゃい\\nそうなんですけど。"

# カズマ
# ちっ、一回死んでエリスさまの爪の垢を\n舐め回してこいっ！
242 = "ちっ、一回死んでエリスさまの爪の垢を\\n舐め回してこいっ！"

# アクア
# なんか言った？
244 = "なんか言った？"

# カズマ
# なんも言ってないって。\nほら、もう少しで出来るから、座って待っててくれ。
245 = "なんも言ってないって。\\nほら、もう少しで出来るから、座って待っててくれ。"

# アクア
# はーい、わっかりました。
249 = "はーい、わっかりました。"

# カズマ
# ほら、出来たぞ！
254 = "ほら、出来たぞ！"

# アクア
# へー、美味しそうじゃない。
253 = "へー、美味しそうじゃない。"

# カズマ
# あっ、先に言っておくけど、\n料理にはあんまり自信が無いからな。
215 = "あっ、先に言っておくけど、\\n料理にはあんまり自信が無いからな。"

# カズマ
# こんなお仕置きを言いだしたのはアクアなんだから、\nあとで文句を言わないでくれよ。
233 = "こんなお仕置きを言いだしたのはアクアなんだから、\\nあとで文句を言わないでくれよ。"

# アクア
# ひょう？　けっこう美味しいけろ。
251 = "ひょう？　けっこう美味しいけろ。"

# カズマ
# もう食ってんのかよ。\nいただきますくらい言えって。
257 = "もう食ってんのかよ。\\nいただきますくらい言えって。"

# アクア
# いただきましゅ！
225 = "いただきましゅ！"

# カズマ
# はぁ、それで味はどうだ？
248 = "はぁ、それで味はどうだ？"

# カズマ
# オーソドックスなメニューのカエルの唐揚げに\nしてみたんだけどさ。
266 = "オーソドックスなメニューのカエルの唐揚げに\\nしてみたんだけどさ。"

# アクア
# ひょうねー、７０点ってとこりょかひら。
250 = "ひょうねー、７０点ってとこりょかひら。"

# カズマ
# おお、結構良い点数つけたな。
230 = "おお、結構良い点数つけたな。"

# アクア
# ……３点。
213 = "……３点。"

# カズマ
# 悔しいからって言い直すな。
280 = "悔しいからって言い直すな。"

# アクア
# ねえ、カジュマ。\nころからあげ、なんらあとをひくんらけろ。
246 = "ねえ、カジュマ。\\nころからあげ、なんらあとをひくんらけろ。"

# カズマ
# 何言ってるか、わかんねーよ！\n口の中の物を飲み込んでから喋ってくれ。
274 = "何言ってるか、わかんねーよ！\\n口の中の物を飲み込んでから喋ってくれ。"

# アクア
# あむあむあむあむ……んぐ。\nあーん、あむあむあむあむ。
221 = "あむあむあむあむ……んぐ。\\nあーん、あむあむあむあむ。"

# カズマ
# 食い直すのかよ！
294 = "食い直すのかよ！"

# アクア
# あむあむ、だかりゃ後を引くの。
219 = "あむあむ、だかりゃ後を引くの。"

# カズマ
# ああ、ショウガみたいなやつが売ってたから\n入れてみたんだ。それのせいじゃないか？
214 = "ああ、ショウガみたいなやつが売ってたから\\n入れてみたんだ。それのせいじゃないか？"

# カズマ
# 結構いけるだろ。
289 = "結構いけるだろ。"

# アクア
# いけりゅ！
224 = "いけりゅ！"

# カズマ
# 肉だけじゃなくて野菜も食えよ？\n食事はバランスが大切なんだからな。
291 = "肉だけじゃなくて野菜も食えよ？\\n食事はバランスが大切なんだからな。"

# アクア
# わっかりまひたー。
258 = "わっかりまひたー。"

# アクア
# んぐんぐんぐ……ぷはぁ～！
262 = "んぐんぐんぐ……ぷはぁ～！"

# カズマ
# いい返事をしておいて、シュワシュワを煽るなって。
223 = "いい返事をしておいて、シュワシュワを煽るなって。"

# アクア
# あむ、んぐ、あむ、わかってないわねカズマ。
217 = "あむ、んぐ、あむ、わかってないわねカズマ。"

# アクア
# 口の中の油っぽさを\nきんきんに冷えたシュワシュワで流すのが、\n最高に気持ち良いんじゃない。
276 = "口の中の油っぽさを\\nきんきんに冷えたシュワシュワで流すのが、\\n最高に気持ち良いんじゃない。"

# カズマ
# だから食べながら喋るなって言ってるだろ。
241 = "だから食べながら喋るなって言ってるだろ。"

# カズマ（Ｍ）
# display as カズマ
# （揚げ物を平気で手で掴んで食べてるし、\n　口の周りは唐揚げのカスをつけてるし――）
298 = "（揚げ物を平気で手で掴んで食べてるし、\\n　口の周りは唐揚げのカスをつけてるし――）"

# カズマ（Ｍ）
# display as カズマ
# （本当に女神なのか？）
299 = "（本当に女神なのか？）"

# アクア
# んぐ、もぐっ……。\nん、なに？　もぐあむ、人の顔をじっと見て。
259 = "んぐ、もぐっ……。\\nん、なに？　もぐあむ、人の顔をじっと見て。"

# カズマ
# ただ、口の周りに食べかすがついてるなって\n思ってただけだよ。
238 = "ただ、口の周りに食べかすがついてるなって\\n思ってただけだよ。"

# アクア
# んー？　じゃあ拭いてくれりゅ？
264 = "んー？　じゃあ拭いてくれりゅ？"

# カズマ
# まったく、しょうがないな。
255 = "まったく、しょうがないな。"

# アクア
# あむあむ、女神にあむはむ、奉仕できることを\nんぐあむ、幸せに思いなさい。
220 = "あむあむ、女神にあむはむ、奉仕できることを\\nんぐあむ、幸せに思いなさい。"

# カズマ
# おいアクア。\nお前が食ってると拭けないんだが。
229 = "おいアクア。\\nお前が食ってると拭けないんだが。"

# アクア
# あむ、はむ、どうしてよ！
216 = "あむ、はむ、どうしてよ！"

# カズマ
# 口が動いてるからだ！\nてかお前、拭かせる気ないだろ。
275 = "口が動いてるからだ！\\nてかお前、拭かせる気ないだろ。"

# アクア
# そんなことないわよ。\nもぐもぐ、ほーら、早く拭いて。
237 = "そんなことないわよ。\\nもぐもぐ、ほーら、早く拭いて。"

# カズマ
# だから食うな！　拭けないだろ！
240 = "だから食うな！　拭けないだろ！"

# アクア
# じゃあ５秒だけ食べるのやめてあげるから、\nさっさとやっちゃって。
235 = "じゃあ５秒だけ食べるのやめてあげるから、\\nさっさとやっちゃって。"

# カズマ（Ｍ）
# display as カズマ
# （どんだけ食い意地張ってるんだ……）
295 = "（どんだけ食い意地張ってるんだ……）"

# カズマ
# んで？　何かこう、美味い以外の感想は無いの\nか？
263 = "んで？　何かこう、美味い以外の感想は無いの\\nか？"

# カズマ
# それくらい自分でやれよ。
236 = "それくらい自分でやれよ。"

# アクア
# んぐんぐ、ぷはぁ、右手にシュワシュワ。\nあむはむ、左手に唐揚げ。
261 = "んぐんぐ、ぷはぁ、右手にシュワシュワ。\\nあむはむ、左手に唐揚げ。"

# アクア
# この状況で、どうやってナプキンを持てって\n言うんでしゅか、カジュマしゃん！
232 = "この状況で、どうやってナプキンを持てって\\n言うんでしゅか、カジュマしゃん！"

# カズマ
# 置けば良いだろ！\nてか、食べカスを飛ばすな！
290 = "置けば良いだろ！\\nてか、食べカスを飛ばすな！"

# カズマ（Ｍ）
# display as カズマ
# （まったく、どんだけ食い意地張ってるんだ……）
297 = "（まったく、どんだけ食い意地張ってるんだ……）"

# カズマ
# んで？　何かこう、美味い以外の感想は無いの\nか？
# 263 = "んで？　何かこう、美味い以外の感想は無いの\\nか？"

# カズマ
# ふへへへ、舐め取ってやろうか！
252 = "ふへへへ、舐め取ってやろうか！"

# アクア
# …………。
212 = "…………。"

# カズマ
# いや、冗談だって、黙るなよ……。
226 = "いや、冗談だって、黙るなよ……。"

# アクア
# …………。
# 212 = "…………。"

# カズマ
# えっと……ナ、ナプキンで拭けばいいか？
227 = "えっと……ナ、ナプキンで拭けばいいか？"

# アクア
# あむ、んぐ、うん、お願いね。
218 = "あむ、んぐ、うん、お願いね。"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、どうしてこんなことまで\n　やらないといけないんだよ……）
296 = "（はぁ、どうしてこんなことまで\\n　やらないといけないんだよ……）"

# カズマ
# んで？　何かこう、美味い以外の感想は無いの\nか？
# 263 = "んで？　何かこう、美味い以外の感想は無いの\\nか？"

# アクア
# んぐもぐ……んぐっ……ん？　そうねぇ～。
260 = "んぐもぐ……んぐっ……ん？　そうねぇ～。"

# アクア
# カラっと揚げつつも、残った油が官能的なまでに\n風味を際立たせてるわね。いい油を使っているわ。
272 = "カラっと揚げつつも、残った油が官能的なまでに\\n風味を際立たせてるわね。いい油を使っているわ。"

# アクア
# カエルの肉も、そこらで討伐して取れるありふれた\n素材の割には下処理が万全で、一部の人が気にする\nような土臭さが欠片も残ってない。
267 = "カエルの肉も、そこらで討伐して取れるありふれた\\n素材の割には下処理が万全で、一部の人が気にする\\nような土臭さが欠片も残ってない。"

# アクア
# 衣の塩と醤油の風味も申し分ないわね。\n高温で揚げれば飛んでしまう風味をよくここまで\n残したものだと賞賛したいくらい。
293 = "衣の塩と醤油の風味も申し分ないわね。\\n高温で揚げれば飛んでしまう風味をよくここまで\\n残したものだと賞賛したいくらい。"

# アクア
# あむはむ、完璧な仕事だったわ。\nんぐ、ぷはー、この女神をも満足させるとは\nやるわね、あむあむあむ。
222 = "あむはむ、完璧な仕事だったわ。\\nんぐ、ぷはー、この女神をも満足させるとは\\nやるわね、あむあむあむ。"

# カズマ
# だから食いながら言うなよ……。\nてか、なんでどっかの料理評論家みたいな\n言葉遣いになってんだ。
239 = "だから食いながら言うなよ……。\\nてか、なんでどっかの料理評論家みたいな\\n言葉遣いになってんだ。"

# アクア
# カジュマしゃん！
268 = "カジュマしゃん！"

# カズマ
# な、なんだよ！
243 = "な、なんだよ！"

# アクア
# おかわり、ありましゅか！
231 = "おかわり、ありましゅか！"

# カズマ
# はぁ……すぐに揚げてやるからちょっと待ってろ。
247 = "はぁ……すぐに揚げてやるからちょっと待ってろ。"

# アクア
# えへへ、はーい。
228 = "えへへ、はーい。"

[selections]
234 = "しょうがないな……。"
# 236 = "それくらい自分でやれよ。"
292 = "舐め取ってやろうか！"
