# rew_d05.txt.scn

[info]
222 = "rew_d05"

[characters]
325 = "クリス"
322 = "カズマ"
323 = "カズマ（Ｍ）"

[character_subs]
# 322 = "カズマ"

[script]
# lines: 115

# クリス
# はい、言われたとおり着替えてきたよ。
315 = "はい、言われたとおり着替えてきたよ。"

# カズマ
# って、普通だな！
304 = "って、普通だな！"

# クリス
# え？　何が？
278 = "え？　何が？"

# カズマ
# 女がパジャマ姿で男の部屋に来てるんだぞ。\nそれが何を意味してるかわかるだろ！
336 = "女がパジャマ姿で男の部屋に来てるんだぞ。\\nそれが何を意味してるかわかるだろ！"

# クリス
# それはまあね、でも相手がキミだし。
299 = "それはまあね、でも相手がキミだし。"

# カズマ
# なるほど、男として見てないと。\nハハハ、わかってたよ、わかってたさ。
308 = "なるほど、男として見てないと。\\nハハハ、わかってたよ、わかってたさ。"

# カズマ
# でも少しくらいは夢を見させてくれても\nいいと思うんだよね。
306 = "でも少しくらいは夢を見させてくれても\\nいいと思うんだよね。"

# クリス
# あはは、ごめんごめん。\n次はもう少し気を持たせるようにするから。
259 = "あはは、ごめんごめん。\\n次はもう少し気を持たせるようにするから。"

# カズマ（Ｍ）
# display as カズマ
# （フォローになってねーよ……）
371 = "（フォローになってねーよ……）"

# クリス
# それで、あたしは何をすればいいのかな。
297 = "それで、あたしは何をすればいいのかな。"

# カズマ
# 添い寝。
340 = "添い寝。"

# クリス
# ん？
319 = "ん？"

# カズマ
# だから、添い寝。
302 = "だから、添い寝。"

# クリス
# うーん、ごめん、もう一回言って。
271 = "うーん、ごめん、もう一回言って。"

# カズマ
# 添い寝してください。
341 = "添い寝してください。"

# クリス
# え、嫌だけど。
273 = "え、嫌だけど。"

# カズマ
# さっき気を持たせるって言ったばっかりだろ！\n少しは努力をしてくれよ！
284 = "さっき気を持たせるって言ったばっかりだろ！\\n少しは努力をしてくれよ！"

# クリス
# ああ、もう、わかったから落ち着いて。
247 = "ああ、もう、わかったから落ち着いて。"

# カズマ
# すまん、つい興奮してしまって。
287 = "すまん、つい興奮してしまって。"

# クリス
# えーと、添い寝？\nそれってつまり、ベッドで一緒に寝てくださいって\nこと？
277 = "えーと、添い寝？\\nそれってつまり、ベッドで一緒に寝てくださいって\\nこと？"

# カズマ
# ああ、その通りだ。
246 = "ああ、その通りだ。"

# クリス
# キミが寝るまでかたわらに居るじゃダメなのかな。
324 = "キミが寝るまでかたわらに居るじゃダメなのかな。"

# カズマ
# 寝付く寝付かないの問題じゃないんだよ。
337 = "寝付く寝付かないの問題じゃないんだよ。"

# カズマ
# 俺が求めてるのは添い寝しながら、\nキャッキャうふふお話したりすることなの。
331 = "俺が求めてるのは添い寝しながら、\\nキャッキャうふふお話したりすることなの。"

# クリス
# 邪な気持ちは？
362 = "邪な気持ちは？"

# カズマ
# 無い！
342 = "無い！"

# クリス
# 神に誓って言える？
358 = "神に誓って言える？"

# カズマ
# 余裕！
330 = "余裕！"

# カズマ（Ｍ）
# display as カズマ
# （ただしアクアにだけど）
368 = "（ただしアクアにだけど）"

# クリス
# わかった、その言葉を信じるよ。\nでも、ダガーは携帯させて貰うからね。
318 = "わかった、その言葉を信じるよ。\\nでも、ダガーは携帯させて貰うからね。"

# カズマ（Ｍ）
# display as カズマ
# （信用してねーだろ、それ！）
374 = "（信用してねーだろ、それ！）"

# カズマ（Ｍ）
# display as カズマ
# （女の子と添い寝。\n　それは選ばれし者にしか許されない\n　リア充限定イベント）
376 = "（女の子と添い寝。\\n　それは選ばれし者にしか許されない\\n　リア充限定イベント）"

# カズマ（Ｍ）
# display as カズマ
# （彼女いない歴＝年齢の俺にまさかこんな\n　イベントが訪れるとは！）
377 = "（彼女いない歴＝年齢の俺にまさかこんな\\n　イベントが訪れるとは！）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、アクア以外の神様ありがとうございます！）
365 = "（ああ、アクア以外の神様ありがとうございます！）"

# クリス
# それで？　キャッキャうふふな話って何？
298 = "それで？　キャッキャうふふな話って何？"

# カズマ
# その前に、ひとついいか？
296 = "その前に、ひとついいか？"

# クリス
# 何かな。
327 = "何かな。"

# カズマ
# ダガー……マジで怖いんだけど。
326 = "ダガー……マジで怖いんだけど。"

# クリス
# 鞘に収めてるじゃない。
363 = "鞘に収めてるじゃない。"

# カズマ
# そ、そうだけどさ……。
288 = "そ、そうだけどさ……。"

# クリス
# そうだ、あたしから一つ話題の提供。
291 = "そうだ、あたしから一つ話題の提供。"

# カズマ
# お、なんだ？？
279 = "お、なんだ？？"

# クリス
# あたし抜刀の速度には結構自信あるんだよね。
256 = "あたし抜刀の速度には結構自信あるんだよね。"

# カズマ
# うん……。
268 = "うん……。"

# クリス
# この前もダンジョンを探索してるときに\n突然モンスターが現れたんだけど――
283 = "この前もダンジョンを探索してるときに\\n突然モンスターが現れたんだけど――"

# クリス
# 素早くダガーを抜いて、それで――
360 = "素早くダガーを抜いて、それで――"

# カズマ
# うん、理解したからもういいや。
270 = "うん、理解したからもういいや。"

# クリス
# あっ、ごめんね。\nベッドでするような話じゃなかったね。
257 = "あっ、ごめんね。\\nベッドでするような話じゃなかったね。"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、どうしてこうなっちゃったかな）
369 = "（はぁ、どうしてこうなっちゃったかな）"

# カズマ（Ｍ）
# display as カズマ
# （添い寝っていうのはもっとこう、\n　甘酸っぱいものであるはずなのに……）
378 = "（添い寝っていうのはもっとこう、\\n　甘酸っぱいものであるはずなのに……）"

# カズマ（Ｍ）
# display as カズマ
# （俺は何か選択を間違えたのか？\n　重要なフラグを見落としたのか？\n　いいや、そんなはずはない！）
375 = "（俺は何か選択を間違えたのか？\\n　重要なフラグを見落としたのか？\\n　いいや、そんなはずはない！）"

# カズマ（Ｍ）
# display as カズマ
# （今日、この日を迎えるために頭の中で\n　何通りもシミュレーションしてきたはずだ。\n　落ち着けカズマ、クールに行くんだ）
372 = "（今日、この日を迎えるために頭の中で\\n　何通りもシミュレーションしてきたはずだ。\\n　落ち着けカズマ、クールに行くんだ）"

# カズマ（Ｍ）
# display as カズマ
# （何か話題を探そう。\n　クリスが俺に対する警戒心を解くような、\n　そんな話題を振らなければ！）
373 = "（何か話題を探そう。\\n　クリスが俺に対する警戒心を解くような、\\n　そんな話題を振らなければ！）"

# カズマ
# いい匂いだ。\nクリス、お前何かつけてるのか？
262 = "いい匂いだ。\\nクリス、お前何かつけてるのか？"

# クリス
# えっ、夕飯に食べてた物の匂いかな。\nごめん、自分じゃわかんないや。
275 = "えっ、夕飯に食べてた物の匂いかな。\\nごめん、自分じゃわかんないや。"

# カズマ
# いや、そういう意味じゃなくてだな。
263 = "いや、そういう意味じゃなくてだな。"

# カズマ
# なんか甘い花みたいな匂いがするんだ。\nてっきり香水でもつけてるのかと思ったんだけど。
311 = "なんか甘い花みたいな匂いがするんだ。\\nてっきり香水でもつけてるのかと思ったんだけど。"

# クリス
# あたし、香水なんかつけてないよ。\n盗賊が匂いをさせてたら仕事にならないもの。
252 = "あたし、香水なんかつけてないよ。\\n盗賊が匂いをさせてたら仕事にならないもの。"

# クリス
# 匂うとしたら誰かの移り香じゃないかな。
333 = "匂うとしたら誰かの移り香じゃないかな。"

# カズマ
# 移り香にしちゃはっきりとしてるんだけどなー。\nうーん、なんだろう。
359 = "移り香にしちゃはっきりとしてるんだけどなー。\\nうーん、なんだろう。"

# クリス
# カ、カズマ！？\nあの、ちょっと顔がちか……。
321 = "カ、カズマ！？\\nあの、ちょっと顔がちか……。"

# カズマ
# くんくん、クリスの髪から香ってる気がする。
280 = "くんくん、クリスの髪から香ってる気がする。"

# クリス
# あ、ああ！　シャンプーの匂いかな？\nさっきお風呂でダクネスのやつ借りたから！
245 = "あ、ああ！　シャンプーの匂いかな？\\nさっきお風呂でダクネスのやつ借りたから！"

# カズマ
# あいつ、こんな匂いしてたかなぁ。\nクリスのほうがいい匂いな気がするけど。
251 = "あいつ、こんな匂いしてたかなぁ。\\nクリスのほうがいい匂いな気がするけど。"

# クリス
# えっ。
276 = "えっ。"

# カズマ
# なんか、いい匂いするのって女の子っぽいよな。\nクリスも似合うんだしつけりゃいいのに。
309 = "なんか、いい匂いするのって女の子っぽいよな。\\nクリスも似合うんだしつけりゃいいのに。"

# クリス
# だから、あたしがつけたら\n仕事にならないって言ってるでしょ。
301 = "だから、あたしがつけたら\\n仕事にならないって言ってるでしょ。"

# カズマ
# まぁ、そうだよな。\nでも、ちょっともったいないなぁ。
317 = "まぁ、そうだよな。\\nでも、ちょっともったいないなぁ。"

# クリス
# ああ、もう！\nわかった！　わかったからちょっと離れてよ！
248 = "ああ、もう！\\nわかった！　わかったからちょっと離れてよ！"

# カズマ
# なんだよ、触ってはいないだろ。
312 = "なんだよ、触ってはいないだろ。"

# クリス
# 触れる触れないの問題じゃないんだよ。\n女の子の匂いを嗅ぐとか、ありえないから。
361 = "触れる触れないの問題じゃないんだよ。\\n女の子の匂いを嗅ぐとか、ありえないから。"

# カズマ
# あ、ああ、そっか、ごめん。
244 = "あ、ああ、そっか、ごめん。"

# クリス
# はぁ、変な汗かいちゃったよ、もう。
314 = "はぁ、変な汗かいちゃったよ、もう。"

# カズマ
# 何か話してくれよ。\nなんでもいいからさ。
329 = "何か話してくれよ。\\nなんでもいいからさ。"

# クリス
# そう言われてもねぇ。
294 = "そう言われてもねぇ。"

# クリス
# あたしが話せることって言ったら\n仕事のこととかダンジョン探索くらいしかないよ？
253 = "あたしが話せることって言ったら\\n仕事のこととかダンジョン探索くらいしかないよ？"

# カズマ
# そういやクリスはダクネスと一緒に\n探索へ行ったりしないのか？
290 = "そういやクリスはダクネスと一緒に\\n探索へ行ったりしないのか？"

# クリス
# あたしは別にいいんだけど、\n２人だとなかなかパーテーィメンバーが\n集まらなくて。
255 = "あたしは別にいいんだけど、\\n２人だとなかなかパーテーィメンバーが\\n集まらなくて。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、そうだよな。\n　あいつはクルセイダーっていう前衛職だが\n　致命的に攻撃が当たらないお荷物だからな）
370 = "（まあ、そうだよな。\\n　あいつはクルセイダーっていう前衛職だが\\n　致命的に攻撃が当たらないお荷物だからな）"

# クリス
# そういうわけで最近は１人で行動することが\n多いかな。
289 = "そういうわけで最近は１人で行動することが\\n多いかな。"

# クリス
# あたしの職業は結構募集があるから、\n突発クエストとか受けやすいしさ。
254 = "あたしの職業は結構募集があるから、\\n突発クエストとか受けやすいしさ。"

# カズマ（Ｍ）
# display as カズマ
# （そういえばダクネスが言ってたな）
367 = "（そういえばダクネスが言ってたな）"

# カズマ（Ｍ）
# display as カズマ
# （盗賊はダンジョン探索に必須な職業のわりに\n　地味だから成り手が多くなくて需要があるって）
379 = "（盗賊はダンジョン探索に必須な職業のわりに\\n　地味だから成り手が多くなくて需要があるって）"

# クリス
# だからあたし、感謝してるんだよ。\nキミがダクネスをパーティーに迎えてくれたこと。\nあの子に仲間ができてよかった。
303 = "だからあたし、感謝してるんだよ。\\nキミがダクネスをパーティーに迎えてくれたこと。\\nあの子に仲間ができてよかった。"

# カズマ
# 俺としてはいつでも返品していいと\n思ってるんだがなー。
332 = "俺としてはいつでも返品していいと\\n思ってるんだがなー。"

# カズマ
# そうだクリス。\nダクネスの代わりに\nうちのパーティーへ入らないか？
293 = "そうだクリス。\\nダクネスの代わりに\\nうちのパーティーへ入らないか？"

# クリス
# え、嫌だけど。
# 273 = "え、嫌だけど。"

# カズマ
# ……だから、気を持たせる努力をだな。
243 = "……だから、気を持たせる努力をだな。"

# クリス
# あはは、わかってるよ、さすがに今のは冗談。
260 = "あはは、わかってるよ、さすがに今のは冗談。"

# カズマ
# じゃあ！
286 = "じゃあ！"

# クリス
# そのときが来たら考えるよ。
295 = "そのときが来たら考えるよ。"

# クリス
# って返事は気を持たせることになるのかな？
305 = "って返事は気を持たせることになるのかな？"

# カズマ
# ああ、充分にな。
249 = "ああ、充分にな。"

# カズマ
# こういうの……夢だったんだ。
282 = "こういうの……夢だったんだ。"

# クリス
# へえ、そうなんだ。
316 = "へえ、そうなんだ。"

# カズマ
# なんかえらい冷めてますね、クリスさん。
310 = "なんかえらい冷めてますね、クリスさん。"

# クリス
# そんなこと言われても\nそうですか、としか答えられないよ。
300 = "そんなこと言われても\\nそうですか、としか答えられないよ。"

# カズマ
# いや、もっとこうあるだろ！
265 = "いや、もっとこうあるだろ！"

# クリス
# うん、例えば？
269 = "うん、例えば？"

# カズマ
# そうだな「私もだよ」とか\n「夢がキミと一緒で嬉しいな」とか。
292 = "そうだな「私もだよ」とか\\n「夢がキミと一緒で嬉しいな」とか。"

# クリス
# 夢がキミと一緒で嬉しいな♪
335 = "夢がキミと一緒で嬉しいな♪"

# カズマ
# え……？
272 = "え……？"

# クリス
# あは、柄じゃなかったね。
258 = "あは、柄じゃなかったね。"

# カズマ
# いや、めちゃくちゃ可愛かったです。
264 = "いや、めちゃくちゃ可愛かったです。"

# クリス
# ええ！？
274 = "ええ！？"

# カズマ
# じゃあじゃあ、次は。\n「早く寝てよ。キミの寝顔を見たいんだからさ」\nこれで！
285 = "じゃあじゃあ、次は。\\n「早く寝てよ。キミの寝顔を見たいんだからさ」\\nこれで！"

# クリス
# いやいやいや、無理無理！\nそれは恥ずかしすぎるよ！
266 = "いやいやいや、無理無理！\\nそれは恥ずかしすぎるよ！"

# カズマ
# 頼むっ！\nこんなお願いこれで最後にするからっ！
364 = "頼むっ！\\nこんなお願いこれで最後にするからっ！"

# クリス
# はぁ、もう、特別だよ？
313 = "はぁ、もう、特別だよ？"

# クリス
# 早く寝てよ。\nキミの寝顔を……見たいんだからさ。
339 = "早く寝てよ。\\nキミの寝顔を……見たいんだからさ。"

# カズマ
# あああああああああああああ！！
250 = "あああああああああああああ！！"

# クリス
# な、何！？　どうしたの？？
307 = "な、何！？　どうしたの？？"

# カズマ
# うああああああああああああ！！
267 = "うああああああああああああ！！"

# クリス
# カ、カズマ！？
320 = "カ、カズマ！？"

# カズマ（Ｍ）
# display as カズマ
# （くっそ、こんな可愛いの卑怯だ！）
366 = "（くっそ、こんな可愛いの卑怯だ！）"

[selections]
261 = "いい匂いだ"
328 = "何か話してくれよ"
281 = "こういうの……夢だったんだ……"
