# rew_c09.txt.scn

[info]
204 = "rew_c09"

[characters]
288 = "ダクネス"
283 = "カズマ"
286 = "カズマ（Ｍ）"

[character_subs]
# 283 = "カズマ"

[script]
# lines: 99

# ダクネス
# よし、カズマ。\nこれからお仕置きとして、私の筋トレに\nつき合ってもらう。
269 = "よし、カズマ。\\nこれからお仕置きとして、私の筋トレに\\nつき合ってもらう。"

# カズマ
# えーっ、面倒くさい。
236 = "えーっ、面倒くさい。"

# ダクネス
# 文句は聞くが受け入れないぞ。\nこれはお仕置きなのだからな。
299 = "文句は聞くが受け入れないぞ。\\nこれはお仕置きなのだからな。"

# カズマ
# わかってるよ。\nそれで筋トレって何をするんだ。
272 = "わかってるよ。\\nそれで筋トレって何をするんだ。"

# ダクネス
# おっと、その前に、ちょっとだけ時間をくれ。
238 = "おっと、その前に、ちょっとだけ時間をくれ。"

# カズマ
# なんだ、鎧を脱ぐのか。
254 = "なんだ、鎧を脱ぐのか。"

# ダクネス
# 普段はつけたままするんだが……。
300 = "普段はつけたままするんだが……。"

# ダクネス
# はっ、な、何か良からぬことを期待してるな！
260 = "はっ、な、何か良からぬことを期待してるな！"

# カズマ
# 良からぬことってなんだよ。
321 = "良からぬことってなんだよ。"

# ダクネス
# 脱ぐのは鎧だけだぞ。\nそれ以上は期待をされても困る！
319 = "脱ぐのは鎧だけだぞ。\\nそれ以上は期待をされても困る！"

# カズマ
# してねーし！\nそんなことし始めたら全力で止めるよ！
242 = "してねーし！\\nそんなことし始めたら全力で止めるよ！"

# ダクネス
# なるほど、ふふ、カズマは無理矢理剥ぐ方が\n好みなんだな。
253 = "なるほど、ふふ、カズマは無理矢理剥ぐ方が\\n好みなんだな。"

# カズマ（Ｍ）
# display as カズマ
# （あー、まったく話が進まねー）
329 = "（あー、まったく話が進まねー）"

# ダクネス
# 待たせたな。\nじゃあまずは腕立て伏せからいこうか。
298 = "待たせたな。\\nじゃあまずは腕立て伏せからいこうか。"

# カズマ
# えー、もうちょっと軽いのからにしようぜ。
235 = "えー、もうちょっと軽いのからにしようぜ。"

# ダクネス
# 軽いのと言うと、腹筋かスクワットか？
323 = "軽いのと言うと、腹筋かスクワットか？"

# カズマ（Ｍ）
# display as カズマ
# （どれもしんどさは変わらねえ）
337 = "（どれもしんどさは変わらねえ）"

# カズマ
# はぁ、もう腕立てでいいです。
257 = "はぁ、もう腕立てでいいです。"

# ダクネス
# よし、では始めるぞ！
268 = "よし、では始めるぞ！"

# カズマ
# うお、すでに腕がしんどいんですけど！
232 = "うお、すでに腕がしんどいんですけど！"

# ダクネス
# まだ１回もやってないじゃないか。
265 = "まだ１回もやってないじゃないか。"

# カズマ
# 最弱職の冒険者をなめるなっ！
301 = "最弱職の冒険者をなめるなっ！"

# ダクネス
# そこは偉ぶるところではないと思うが。
246 = "そこは偉ぶるところではないと思うが。"

# カズマ
# んひっ、い、いいから、早く始めて終わらせてくれ！
278 = "んひっ、い、いいから、早く始めて終わらせてくれ！"

# ダクネス
# じゃあ、いーち。
243 = "じゃあ、いーち。"

# カズマ
# んひぃぃぃ！
277 = "んひぃぃぃ！"

# ダクネス
# にーい！
256 = "にーい！"

# カズマ
# ふおおおおおお！！\nダ、ダクネスさぁん！
263 = "ふおおおおおお！！\\nダ、ダクネスさぁん！"

# ダクネス
# ん？　どうかしたか？
279 = "ん？　どうかしたか？"

# カズマ
# も、もう、限界です！
266 = "も、もう、限界です！"

# ダクネス
# 仕方ないな。\nじゃあ少し休んでから再開だ。
292 = "仕方ないな。\\nじゃあ少し休んでから再開だ。"

# カズマ（Ｍ）
# display as カズマ
# （はぁぁぁ、わかってはいたけど、\n　日本での引きこもり生活も相まって\n　腕が枯れ木みたいでひょろひょろだ）
340 = "（はぁぁぁ、わかってはいたけど、\\n　日本での引きこもり生活も相まって\\n　腕が枯れ木みたいでひょろひょろだ）"

# ダクネス
# んっ、よっ、そういう顔をするな。\n人には、んっ、はっ、得て不得手があるんだからな。
275 = "んっ、よっ、そういう顔をするな。\\n人には、んっ、はっ、得て不得手があるんだからな。"

# カズマ
# はぁ、喋りながらよくできるな。
258 = "はぁ、喋りながらよくできるな。"

# ダクネス
# ハハ、まだ１０回もしてないからな。\nんっ、んっ、はっ！
291 = "ハハ、まだ１０回もしてないからな。\\nんっ、んっ、はっ！"

# カズマ（Ｍ）
# display as カズマ
# （うん……）
331 = "（うん……）"

# ダクネス
# ふぅ、はっ、んっ、１０回っと。
262 = "ふぅ、はっ、んっ、１０回っと。"

# カズマ（Ｍ）
# display as カズマ
# （実に素晴らしい揺れ具合だ！）
343 = "（実に素晴らしい揺れ具合だ！）"

# ダクネス
# どうしたカズマ。\nさっきからジッと見て。
251 = "どうしたカズマ。\\nさっきからジッと見て。"

# カズマ
# あっ、いや、よくそんなにできるなって\n感心してただけだ。
228 = "あっ、いや、よくそんなにできるなって\\n感心してただけだ。"

# ダクネス
# カズマも鍛練を重ねればできるようになるさ。
285 = "カズマも鍛練を重ねればできるようになるさ。"

# カズマ
# 道のりは厳しそうだけどな。
324 = "道のりは厳しそうだけどな。"

# ダクネス
# だがその先には、皆の壁になれるという\n素晴らしい役目が待っているぞ。
248 = "だがその先には、皆の壁になれるという\\n素晴らしい役目が待っているぞ。"

# カズマ（Ｍ）
# display as カズマ
# （お前が求めてる素晴らしさは、\n　他のクルセイダーとは異質のものだろ）
335 = "（お前が求めてる素晴らしさは、\\n　他のクルセイダーとは異質のものだろ）"

# ダクネス
# カズマ、休憩はほどほどにして、\nそろそろ再開したらどうだ？
284 = "カズマ、休憩はほどほどにして、\\nそろそろ再開したらどうだ？"

# カズマ（Ｍ）
# display as カズマ
# （腕立てをしながらだと、\n　この状況を楽しめないよな）
344 = "（腕立てをしながらだと、\\n　この状況を楽しめないよな）"

# カズマ（Ｍ）
# display as カズマ
# （よし、だったら）
342 = "（よし、だったら）"

# カズマ
# ダクネス、そんなんじゃダメだ。\n俺が指導してやるよ。
289 = "ダクネス、そんなんじゃダメだ。\\n俺が指導してやるよ。"

# ダクネス
# ん？　どこかマズいところでもあるか？
280 = "ん？　どこかマズいところでもあるか？"

# カズマ
# 腕への負荷のかかり方が非効率だし、\nそのやり方じゃ別の所を痛めるだけだ。
320 = "腕への負荷のかかり方が非効率だし、\\nそのやり方じゃ別の所を痛めるだけだ。"

# ダクネス
# そ、そうだったのか。\nでは、指導を頼む。
245 = "そ、そうだったのか。\\nでは、指導を頼む。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、俺もそんな知識は皆無だけどな）
341 = "（まあ、俺もそんな知識は皆無だけどな）"

# カズマ
# じゃあまず、ゆっくり腕を曲げていくんだ。
244 = "じゃあまず、ゆっくり腕を曲げていくんだ。"

# ダクネス
# な、なるほど、んっ、んくっ、これは、\n確かに結構来るな。
252 = "な、なるほど、んっ、んくっ、これは、\\n確かに結構来るな。"

# カズマ
# 喜んでないで集中しろよ。
296 = "喜んでないで集中しろよ。"

# ダクネス
# おっと、すまない。
237 = "おっと、すまない。"

# カズマ
# ゆっくーり、ゆっくーり。
267 = "ゆっくーり、ゆっくーり。"

# カズマ（Ｍ）
# display as カズマ
# （いいぞいいぞ、胸が地面に圧迫されて……）
330 = "（いいぞいいぞ、胸が地面に圧迫されて……）"

# カズマ
# はい、そこでキープ！
259 = "はい、そこでキープ！"

# ダクネス
# んっ、んくっ、うぅっ……キツい。
276 = "んっ、んくっ、うぅっ……キツい。"

# カズマ（Ｍ）
# display as カズマ
# （うんうん、ダクネスだからこそ可能な\n　この素晴らしい光景）
332 = "（うんうん、ダクネスだからこそ可能な\\n　この素晴らしい光景）"

# ダクネス
# んぐっ、カズマっ……そろそろ伸ばしても。
273 = "んぐっ、カズマっ……そろそろ伸ばしても。"

# カズマ
# ダメだ。そのままあと１０秒我慢！
290 = "ダメだ。そのままあと１０秒我慢！"

# ダクネス
# うっ、うぐっ、腕が震えてっ。
233 = "うっ、うぐっ、腕が震えてっ。"

# カズマ（Ｍ）
# display as カズマ
# （おおっ、ぷるぷるしてる！）
333 = "（おおっ、ぷるぷるしてる！）"

# ダクネス
# カ、カズマ、私はもう限界だぁ！
282 = "カ、カズマ、私はもう限界だぁ！"

# カズマ（Ｍ）
# display as カズマ
# （開き直って凝視してやろう！）
345 = "（開き直って凝視してやろう！）"

# ダクネス
# ん？　カズマ？
281 = "ん？　カズマ？"

# カズマ
# ジーーーー……。
287 = "ジーーーー……。"

# ダクネス
# ど、どうした、私の顔を見て。
250 = "ど、どうした、私の顔を見て。"

# カズマ
# ジーーーー……。
# 287 = "ジーーーー……。"

# ダクネス
# はっ、違う、見ているのは顔じゃない！？
261 = "はっ、違う、見ているのは顔じゃない！？"

# カズマ
# ジーーーー……。
# 287 = "ジーーーー……。"

# ダクネス
# くぅ、なるほど、\nんっ、くっ、そういう魂胆だったのか。
239 = "くぅ、なるほど、\\nんっ、くっ、そういう魂胆だったのか。"

# ダクネス
# なんていやらしくどう猛な視線。\n私は今、全裸に剥かれ、そして腕立て伏せを\n強要されているのだな。
255 = "なんていやらしくどう猛な視線。\\n私は今、全裸に剥かれ、そして腕立て伏せを\\n強要されているのだな。"

# カズマ（Ｍ）
# display as カズマ
# （なんだよその間抜けな状況は……）
338 = "（なんだよその間抜けな状況は……）"

# ダクネス
# こんな屈辱、耐え難いっ。\nしかし、私が途中でやめたら、\nカズマに示しがつかなくなる。
240 = "こんな屈辱、耐え難いっ。\\nしかし、私が途中でやめたら、\\nカズマに示しがつかなくなる。"

# ダクネス
# んっ、くっ、はぁっ！\nみ、見たければ見続ければいい！
274 = "んっ、くっ、はぁっ！\\nみ、見たければ見続ければいい！"

# ダクネス
# だが、これで私を汚せたと思うなよ。\nどんなに羞恥の目で見られようが――
247 = "だが、これで私を汚せたと思うなよ。\\nどんなに羞恥の目で見られようが――"

# ダクネス
# 騎士の誇りまでは汚せないのだからなぁ！
328 = "騎士の誇りまでは汚せないのだからなぁ！"

# カズマ
# 頼むから黙っててくれよ。\n全てが台無しになるからさ。
327 = "頼むから黙っててくれよ。\\n全てが台無しになるからさ。"

# ダクネス
# ああ、ひどい！
226 = "ああ、ひどい！"

# カズマ
# 頑張るからご褒美ください！
326 = "頑張るからご褒美ください！"

# ダクネス
# いや、これはカズマへのお仕置きなんだぞ？
230 = "いや、これはカズマへのお仕置きなんだぞ？"

# カズマ
# わかってるっ、わかってるけどさ！\nこんなしんどいお仕置き、\n見返り無しじゃできないんだよ！
271 = "わかってるっ、わかってるけどさ！\\nこんなしんどいお仕置き、\\n見返り無しじゃできないんだよ！"

# ダクネス
# 確かに冒険者のカズマには厳しすぎるのかも\nしれないな。
318 = "確かに冒険者のカズマには厳しすぎるのかも\\nしれないな。"

# カズマ
# だろ？　だろ？
249 = "だろ？　だろ？"

# ダクネス
# しかし褒美か。\n私がカズマにやれる物なんて何もないぞ。
241 = "しかし褒美か。\\n私がカズマにやれる物なんて何もないぞ。"

# カズマ
# 別に物じゃ無くてもいいんだ。\n例えば、もっと激しい腕立て伏せを\nやって見せてくれるとかでもいいんだって！
294 = "別に物じゃ無くてもいいんだ。\\n例えば、もっと激しい腕立て伏せを\\nやって見せてくれるとかでもいいんだって！"

# ダクネス
# 良くわからないが、そんなことでいいなら。
322 = "良くわからないが、そんなことでいいなら。"

# ダクネス
# よっ、はっ、んっ、はぁ、んんっ！
270 = "よっ、はっ、んっ、はぁ、んんっ！"

# カズマ（Ｍ）
# display as カズマ
# （おっ、おお！　おおおーーーー！！）
334 = "（おっ、おお！　おおおーーーー！！）"

# カズマ（Ｍ）
# display as カズマ
# （すっごい揺れてるっ、\n　すっごいぷるんぷるんしてるんですけどー！）
336 = "（すっごい揺れてるっ、\\n　すっごいぷるんぷるんしてるんですけどー！）"

# ダクネス
# うっ、くっ、あぅ、さすがにキツク、なってきた。
234 = "うっ、くっ、あぅ、さすがにキツク、なってきた。"

# カズマ
# いいよいいよ、その表情。\nさあ、もっと頑張っちゃって！
229 = "いいよいいよ、その表情。\\nさあ、もっと頑張っちゃって！"

# ダクネス
# あぅ、んんっ、はっ、カズマ、もう私っ……！
227 = "あぅ、んんっ、はっ、カズマ、もう私っ……！"

# カズマ
# まだまだいけるよー！\nダクネス、ガンバ！
264 = "まだまだいけるよー！\\nダクネス、ガンバ！"

# ダクネス
# うああああ！　もう無理だっ！\nう、腕がっ、もたないっ！！！
231 = "うああああ！　もう無理だっ！\\nう、腕がっ、もたないっ！！！"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、いいものを堪能させていただきました）
339 = "（はぁ、いいものを堪能させていただきました）"

[selections]
293 = "俺が指導してやろう！"
325 = "開き直って凝視しよう！"
# 326 = "頑張るからご褒美ください！"
