# rew_f05.txt.scn

[info]
203 = "rew_f05"

[characters]
308 = "カズマ"
304 = "ウィズ"
309 = "カズマ（Ｍ）"

[character_subs]
# 308 = "カズマ"

[script]
# lines: 75

# カズマ
# ウィズ、お願いがあるんだ。
305 = "ウィズ、お願いがあるんだ。"

# ウィズ
# え……な、なんですか、そんな今までに見たことの\n無いくらい真剣な顔をして。
257 = "え……な、なんですか、そんな今までに見たことの\\n無いくらい真剣な顔をして。"

# カズマ
# これは男の一生に一度のお願いと思って下さい。
269 = "これは男の一生に一度のお願いと思って下さい。"

# ウィズ
# えっ、えっ？\n一生に一度のお願いって……ま、まさかっ？
262 = "えっ、えっ？\\n一生に一度のお願いって……ま、まさかっ？"

# カズマ
# ああ……口にするのも恥ずかしいけど、\nこのほとばしる思い、もう止めることが\n出来ないんだ！
247 = "ああ……口にするのも恥ずかしいけど、\\nこのほとばしる思い、もう止めることが\\n出来ないんだ！"

# ウィズ
# あ、あれ？　何か思っていたのと違う感じが。\nっていうかイヤな予感がするんですけど。
244 = "あ、あれ？　何か思っていたのと違う感じが。\\nっていうかイヤな予感がするんですけど。"

# カズマ
# というわけで、ウィズ！\n今回のご褒美なんだが！
282 = "というわけで、ウィズ！\\n今回のご褒美なんだが！"

# カズマ
# 俺と一緒にお風呂に入って下さい！！
312 = "俺と一緒にお風呂に入って下さい！！"

# ウィズ
# えっ……ええええええっ！？
261 = "えっ……ええええええっ！？"

# ウィズ
# ダメですぅっ、\nそれだけはカズマさんのお願いだとしても！！
310 = "ダメですぅっ、\\nそれだけはカズマさんのお願いだとしても！！"

# カズマ
# あ、もちろんちゃんと水着は着てもらうから\n安心してくれ！
246 = "あ、もちろんちゃんと水着は着てもらうから\\n安心してくれ！"

# ウィズ
# そ、そうなんですか……？
273 = "そ、そうなんですか……？"

# カズマ
# ああ。それで、着てもらいたいのが……これだ！！
251 = "ああ。それで、着てもらいたいのが……これだ！！"

# ウィズ
# なんですか、これ？
288 = "なんですか、これ？"

# カズマ
# これはスク水という、俺の世界じゃ由緒正しい水着\nなんだ。
268 = "これはスク水という、俺の世界じゃ由緒正しい水着\\nなんだ。"

# ウィズ
# はあ、由緒正しい。
289 = "はあ、由緒正しい。"

# カズマ
# この水着を着られるのは、許された一部の人間のみ。
267 = "この水着を着られるのは、許された一部の人間のみ。"

# カズマ
# そして俺は、ウィズがこの水着を着るに\n相応しい女の子だと思ってる！
275 = "そして俺は、ウィズがこの水着を着るに\\n相応しい女の子だと思ってる！"

# ウィズ
# わ、わかりました。\nですが念のためチェックさせてください。
301 = "わ、わかりました。\\nですが念のためチェックさせてください。"

# カズマ
# おう、構わないぞ。
265 = "おう、構わないぞ。"

# ウィズ
# 素材は丈夫そうですね。\n水には溶けそうにありません。
336 = "素材は丈夫そうですね。\\n水には溶けそうにありません。"

# カズマ（Ｍ）
# display as カズマ
# （そんなことを警戒してたのか……）
338 = "（そんなことを警戒してたのか……）"

# ウィズ
# ええと、あとは……。\n変な切れ込みも無しと。
260 = "ええと、あとは……。\\n変な切れ込みも無しと。"

# カズマ（Ｍ）
# display as カズマ
# （切れ込みって……）
339 = "（切れ込みって……）"

# ウィズ
# あれ、これは？\n見たことのない文字が書いてありますよ？
252 = "あれ、これは？\\n見たことのない文字が書いてありますよ？"

# カズマ
# ああ、それは俺の世界の文字で\n「うぃず」って書いてあるんだよ。
248 = "ああ、それは俺の世界の文字で\\n「うぃず」って書いてあるんだよ。"

# ウィズ
# へえ、カズマさんの国で私の名前は\nこのような文字で書くんですね。
295 = "へえ、カズマさんの国で私の名前は\\nこのような文字で書くんですね。"

# カズマ
# それで、怪しい所はあったか？
277 = "それで、怪しい所はあったか？"

# ウィズ
# あ、いえ、大丈夫でした！
245 = "あ、いえ、大丈夫でした！"

# カズマ
# よしじゃあ、これを着て一緒に風呂に入ってくれ。
299 = "よしじゃあ、これを着て一緒に風呂に入ってくれ。"

# ウィズ
# はううう、わかりました。
290 = "はううう、わかりました。"

# カズマ
# さあ！　洗ってくれ！
270 = "さあ！　洗ってくれ！"

# ウィズ
# あ、あの～、カズマさん？
243 = "あ、あの～、カズマさん？"

# カズマ
# どうしたウィズ？
285 = "どうしたウィズ？"

# ウィズ
# どうしてカズマさんは水着を着られないのですか？
286 = "どうしてカズマさんは水着を着られないのですか？"

# カズマ
# え、面倒だからだけど。
258 = "え、面倒だからだけど。"

# ウィズ
# 面倒なのは、まあわかりますが、\nできたら私への気遣いを優先してくださると\n嬉しかったです。
337 = "面倒なのは、まあわかりますが、\\nできたら私への気遣いを優先してくださると\\n嬉しかったです。"

# カズマ
# 気遣い……ああ、ぽろりを心配してるのか！
317 = "気遣い……ああ、ぽろりを心配してるのか！"

# ウィズ
# ぽろ！？
297 = "ぽろ！？"

# カズマ
# 平気平気。\nちゃんとタオルを抑えてるからさ！
316 = "平気平気。\\nちゃんとタオルを抑えてるからさ！"

# ウィズ
# も、もう、そういうことを言わないでください！
298 = "も、もう、そういうことを言わないでください！"

# カズマ（Ｍ）
# display as カズマ
# （顔を真っ赤にして、可愛いなぁウィズは）
340 = "（顔を真っ赤にして、可愛いなぁウィズは）"

# ウィズ
# で、では、洗いますね？
280 = "で、では、洗いますね？"

# カズマ
# よろしくお願いします！
300 = "よろしくお願いします！"

# ウィズ
# んしょ、んしょ。\n強さはこのくらいで大丈夫ですか？
303 = "んしょ、んしょ。\\n強さはこのくらいで大丈夫ですか？"

# カズマ
# ああ、最高に気持ちいいよ、ありがとう。
250 = "ああ、最高に気持ちいいよ、ありがとう。"

# ウィズ
# ん……んん……。
302 = "ん……んん……。"

# カズマ
# ウィズ？　どうかしたか？
306 = "ウィズ？　どうかしたか？"

# ウィズ
# その、水着がちょっと突っ張っちゃいまして。
276 = "その、水着がちょっと突っ張っちゃいまして。"

# カズマ
# ほお？　突っ張っちゃった……ですか。
296 = "ほお？　突っ張っちゃった……ですか。"

# ウィズ
# い、いえっ！　水着がきついだけですから！\nそんな変な事にはなってませんから！
253 = "い、いえっ！　水着がきついだけですから！\\nそんな変な事にはなってませんから！"

# カズマ
# いやそう言われても、渡した側としては不備がないか\n気になってしまってだな。
255 = "いやそう言われても、渡した側としては不備がないか\\n気になってしまってだな。"

# ウィズ
# 大丈夫ですから、ちらちら見ないで下さい！
314 = "大丈夫ですから、ちらちら見ないで下さい！"

# カズマ
# ふむ、ちょっとサイズが小さかったかな？
294 = "ふむ、ちょっとサイズが小さかったかな？"

# ウィズ
# ちょっとどころじゃ無い気がするんですが。
278 = "ちょっとどころじゃ無い気がするんですが。"

# カズマ
# いや、でも水着って水の抵抗を無くすために、少し\nきつめの方がいいらしいぞ？
254 = "いや、でも水着って水の抵抗を無くすために、少し\\nきつめの方がいいらしいぞ？"

# ウィズ
# 泳ぐわけじゃありませんよね？
318 = "泳ぐわけじゃありませんよね？"

# カズマ
# ふむ……確かにそのぴちぴち具合は、\n小さかったかもしれないな～。
293 = "ふむ……確かにそのぴちぴち具合は、\\n小さかったかもしれないな～。"

# ウィズ
# ぴちぴち具合とか言わないで下さい！！
291 = "ぴちぴち具合とか言わないで下さい！！"

# カズマ
# ふう……堪能した。\n最高だったぞウィズ！
292 = "ふう……堪能した。\\n最高だったぞウィズ！"

# カズマ
# じーーーーーー……。
271 = "じーーーーーー……。"

# ウィズ
# えっ！？　きゃっ、そ、そんなじっと見ないで\n下さい！！
264 = "えっ！？　きゃっ、そ、そんなじっと見ないで\\n下さい！！"

# カズマ
# じ～～～～～～～。
272 = "じ～～～～～～～。"

# ウィズ
# カカ、カズマさん、ど、どこ見てるんですかぁ！\nだーめーでーすぅ！！\nあっちっ、あっち向いて下さいっ！
307 = "カカ、カズマさん、ど、どこ見てるんですかぁ！\\nだーめーでーすぅ！！\\nあっちっ、あっち向いて下さいっ！"

# カズマ
# ふう……堪能した。\n最高だったぞウィズ！
# 292 = "ふう……堪能した。\\n最高だったぞウィズ！"

# カズマ
# とても似合ってるのに。
284 = "とても似合ってるのに。"

# ウィズ
# えっ、そ、そうですか？
263 = "えっ、そ、そうですか？"

# カズマ
# ああ、俺の見立て通りだ。ウィズならこの平凡な\n水着も着こなしてくれるだろうと信じてたぜ。
249 = "ああ、俺の見立て通りだ。ウィズならこの平凡な\\n水着も着こなしてくれるだろうと信じてたぜ。"

# ウィズ
# なんか褒められてるところが微妙な感じがします\nけど……ありがとうございます。
287 = "なんか褒められてるところが微妙な感じがします\\nけど……ありがとうございます。"

# カズマ
# ふう……堪能した。\n最高だったぞウィズ！
# 292 = "ふう……堪能した。\\n最高だったぞウィズ！"

# ウィズ
# うう、なんか嬉しくありません。
256 = "うう、なんか嬉しくありません。"

# カズマ
# そう言わないでくれよ。\nよし、それじゃ次は何をしてもらおうかな。
274 = "そう言わないでくれよ。\\nよし、それじゃ次は何をしてもらおうかな。"

# ウィズ
# ええ、これで終わりじゃないんですか！？
259 = "ええ、これで終わりじゃないんですか！？"

# カズマ
# おふろを出るまでがご褒美だ！
266 = "おふろを出るまでがご褒美だ！"

# ウィズ
# でしたら、早く出ましょうよ～～～～！
281 = "でしたら、早く出ましょうよ～～～～！"

[selections]
279 = "ちょっとサイズが小さかったかな？"
311 = "何も言わずに凝視しよう"
283 = "とても似合ってるのに……"
