# rew_f04.txt.scn

[info]
155 = "rew_f04"

[characters]
235 = "カズマ"
234 = "ウィズ"
236 = "カズマ（Ｍ）"

[character_subs]
# 235 = "カズマ"

[script]
# lines: 51

# カズマ
# ご褒美にお母さんごっこがしたい！！
216 = "ご褒美にお母さんごっこがしたい！！"

# ウィズ
# ……は、はい？
192 = "……は、はい？"

# カズマ
# お母さんごっこがしたいです！！
212 = "お母さんごっこがしたいです！！"

# ウィズ
# え、えーと……。
205 = "え、えーと……。"

# カズマ
# お母さんごっこがしたいしたいしたい！！
211 = "お母さんごっこがしたいしたいしたい！！"

# ウィズ
# あ、ああ……駄々を捏ねないで下さい。\nでも、お母さんごっこって言われても……。
194 = "あ、ああ……駄々を捏ねないで下さい。\\nでも、お母さんごっこって言われても……。"

# カズマ
# したいんだ、俺……あんまり母さんに甘えたこと、\n無かったからさ。
217 = "したいんだ、俺……あんまり母さんに甘えたこと、\\n無かったからさ。"

# ウィズ
# えっ、カズマさん。\nそんな、可哀想に……。
207 = "えっ、カズマさん。\\nそんな、可哀想に……。"

# カズマ（Ｍ）
# display as カズマ
# （う、ウィズの反応がガチで良心の呵責が……。\n　でもウソは言ってない！）
273 = "（う、ウィズの反応がガチで良心の呵責が……。\\n　でもウソは言ってない！）"

# カズマ（Ｍ）
# display as カズマ
# （単に親に甘えようとしない、\n　スレたガキだっただけなんだが）
275 = "（単に親に甘えようとしない、\\n　スレたガキだっただけなんだが）"

# ウィズ
# わかりました。どんな風にすればいいか\nわかりませんが、教えて頂ければ……。
233 = "わかりました。どんな風にすればいいか\\nわかりませんが、教えて頂ければ……。"

# カズマ
# じゃあ、まずは褒めてくれないかな。
218 = "じゃあ、まずは褒めてくれないかな。"

# ウィズ
# わかりました……こほん……。\nふふ、良く出来ましたね、カズマ。\nお母さんは嬉しいですよ。
232 = "わかりました……こほん……。\\nふふ、良く出来ましたね、カズマ。\\nお母さんは嬉しいですよ。"

# カズマ
# おお、褒めてもらうって、\nこんな嬉しいことだったのか。
209 = "おお、褒めてもらうって、\\nこんな嬉しいことだったのか。"

# ウィズ
# うう、カズマさんってば本当に不憫な人生を送って\nきたんですね。
200 = "うう、カズマさんってば本当に不憫な人生を送って\\nきたんですね。"

# カズマ
# うぐっ、それは俺に大ダメージなんだが。
201 = "うぐっ、それは俺に大ダメージなんだが。"

# ウィズ
# あっ、ごめんなさいっ、古傷をえぐってしまって！
196 = "あっ、ごめんなさいっ、古傷をえぐってしまって！"

# カズマ
# おおう追加ダメージが……っ！！\nそ、そしたら、慰めてくれ。
210 = "おおう追加ダメージが……っ！！\\nそ、そしたら、慰めてくれ。"

# ウィズ
# は、はい……大丈夫よ、カズマ。\nお母さんがついてるから、\nもう泣かなくてもいいのよ？
221 = "は、はい……大丈夫よ、カズマ。\\nお母さんがついてるから、\\nもう泣かなくてもいいのよ？"

# カズマ
# ありがとう、母さん。俺、もう恐くないから。
197 = "ありがとう、母さん。俺、もう恐くないから。"

# ウィズ
# ふふ、強い子ね、カズマ。
229 = "ふふ、強い子ね、カズマ。"

# カズマ
# 母さん……俺、がばっ！
246 = "母さん……俺、がばっ！"

# ウィズ
# きゃっ！？　か、カズマさ……カズマったら、いき\nなり抱きついてくるなんてびっくりするじゃない。
214 = "きゃっ！？　か、カズマさ……カズマったら、いき\\nなり抱きついてくるなんてびっくりするじゃない。"

# カズマ
# ふあぁぁ……母さん。\n温かくて柔らかくて、いい匂いがするぅ……。
226 = "ふあぁぁ……母さん。\\n温かくて柔らかくて、いい匂いがするぅ……。"

# ウィズ
# え、ええと、こら、カズマ。\n甘えん坊すぎますよ？
203 = "え、ええと、こら、カズマ。\\n甘えん坊すぎますよ？"

# カズマ
# すぅぅぅ……。
219 = "すぅぅぅ……。"

# ウィズ
# きゃっ、す、吸わないで下さいぃぃ！\nそ、その、これ、いつまで続ければ\nいいんですか？
213 = "きゃっ、す、吸わないで下さいぃぃ！\\nそ、その、これ、いつまで続ければ\\nいいんですか？"

# カズマ
# 抱っこしてくれなきゃやだ！
245 = "抱っこしてくれなきゃやだ！"

# ウィズ
# だ、抱っこですか？\nえ、えーと、抱っこといっても、\nその、どうすれば……。
220 = "だ、抱っこですか？\\nえ、えーと、抱っこといっても、\\nその、どうすれば……。"

# カズマ
# 頭をこう、抱きかかえて！
272 = "頭をこう、抱きかかえて！"

# ウィズ
# は、はいっ、こ、こうですか？
222 = "は、はいっ、こ、こうですか？"

# カズマ
# うん、そうっ！\nああ、柔らかくていい気持ち……。
202 = "うん、そうっ！\\nああ、柔らかくていい気持ち……。"

# ウィズ
# もう、甘えん坊なんですから。
231 = "もう、甘えん坊なんですから。"

# カズマ
# いい子いい子して。
198 = "いい子いい子して。"

# ウィズ
# ふふ、そのくらいならいくらでも。\nほーら、いい子いい子。
228 = "ふふ、そのくらいならいくらでも。\\nほーら、いい子いい子。"

# カズマ
# ふああ……ボク、いい子？
227 = "ふああ……ボク、いい子？"

# ウィズ
# いい子ですよ～、よーし、よーし。
199 = "いい子ですよ～、よーし、よーし。"

# カズマ
# 眠くなってきちゃった。
271 = "眠くなってきちゃった。"

# ウィズ
# はいはい、ねんねんころりよ～おころりよ～。
223 = "はいはい、ねんねんころりよ～おころりよ～。"

# ウィズ
# 坊やはよい子だねんねしな～……。
242 = "坊やはよい子だねんねしな～……。"

# カズマ
# ふぁぁ、すごく心が満たされたでちゅ。
225 = "ふぁぁ、すごく心が満たされたでちゅ。"

# ウィズ
# 何かカズマさん、どんどん幼児退行してません？
240 = "何かカズマさん、どんどん幼児退行してません？"

# カズマ
# ばぶ～。
224 = "ばぶ～。"

# ウィズ
# えっ、きゃっ！？　そ、そこはダメですっ！！\n本当に怒りますよ！
206 = "えっ、きゃっ！？　そ、そこはダメですっ！！\\n本当に怒りますよ！"

# カズマ
# あ……。
193 = "あ……。"

# カズマ（Ｍ）
# display as カズマ
# （この目は本気だ！\n　ウィズを怒らせるのはマズイ！）
274 = "（この目は本気だ！\\n　ウィズを怒らせるのはマズイ！）"

# カズマ
# え、ええと、調子に乗りすぎました、\nごめんなさい。
204 = "え、ええと、調子に乗りすぎました、\\nごめんなさい。"

# ウィズ
# あ、あの、そんな顔をされると……！
195 = "あ、あの、そんな顔をされると……！"

# ウィズ
# も、もう、本当にカズマは困った子ね？
230 = "も、もう、本当にカズマは困った子ね？"

# カズマ
# お、お母さーーーーん！！
208 = "お、お母さーーーーん！！"

# ウィズ
# きゃ！　抱きつかないでくださーい！！
215 = "きゃ！　抱きつかないでくださーい！！"

[selections]
244 = "抱っこしてくれなきゃやだ。"
# 198 = "いい子いい子して。"
# 271 = "眠くなってきちゃった。"
