# rew_d02.txt.scn

[info]
223 = "rew_d02"

[characters]
324 = "カズマ"
327 = "クリス"
325 = "カズマ（Ｍ）"

[character_subs]
# 324 = "カズマ"

[script]
# lines: 97

# カズマ
# お願いします！\nご褒美に料理を振舞ってください！\n水着にエプロンを着て！！
281 = "お願いします！\\nご褒美に料理を振舞ってください！\\n水着にエプロンを着て！！"

# クリス
# え、ええと、料理はわかるんだけど、\n水着にエプロン？　何それ？
270 = "え、ええと、料理はわかるんだけど、\\n水着にエプロン？　何それ？"

# カズマ
# だから水着の上にエプロンをつけるんだよ。
301 = "だから水着の上にエプロンをつけるんだよ。"

# クリス
# うーん、ごめん。\nあたしの理解の範疇を超えちゃってるみたい。
268 = "うーん、ごめん。\\nあたしの理解の範疇を超えちゃってるみたい。"

# カズマ
# これは男の浪漫なんだし、\n女のクリスがわからなくて当然だ。
285 = "これは男の浪漫なんだし、\\n女のクリスがわからなくて当然だ。"

# カズマ
# 恥じる必要は何ひとつ無いぞ。
340 = "恥じる必要は何ひとつ無いぞ。"

# クリス
# あはは、フォローをありがとう。
258 = "あはは、フォローをありがとう。"

# カズマ
# というわけで改めて！\n水着エプロン姿で料理をご馳走してください！
310 = "というわけで改めて！\\n水着エプロン姿で料理をご馳走してください！"

# クリス
# キミって、自分の欲望に対して本当に貪欲だね。
326 = "キミって、自分の欲望に対して本当に貪欲だね。"

# クリス
# それに普通、こんなことで頭下げるかなー。
297 = "それに普通、こんなことで頭下げるかなー。"

# カズマ
# こんなチャンスは最初で最後かもしれないからな！
286 = "こんなチャンスは最初で最後かもしれないからな！"

# カズマ
# プライドなんてクソくらえだ！
331 = "プライドなんてクソくらえだ！"

# クリス
# はぁ、ご褒美は拒否できないってルールだし、\nあたしはキミの言うことに従うだけだよ。
316 = "はぁ、ご褒美は拒否できないってルールだし、\\nあたしはキミの言うことに従うだけだよ。"

# カズマ
# じゃあ！
289 = "じゃあ！"

# クリス
# はいはい、そんな満面の笑みをしないの。\n着替えるから、外に出ててくれる。
318 = "はいはい、そんな満面の笑みをしないの。\\n着替えるから、外に出ててくれる。"

# カズマ
# りょうかいっす！
321 = "りょうかいっす！"

# カズマ（Ｍ）
# display as カズマ
# （水着にエプロン、そしてクリスの手料理かー）
373 = "（水着にエプロン、そしてクリスの手料理かー）"

# カズマ（Ｍ）
# display as カズマ
# （これは楽しみだ！）
368 = "（これは楽しみだ！）"

# カズマ
# おーい、まだかー？
280 = "おーい、まだかー？"

# クリス
# ええと、これで大丈夫かな。\nおかしいところないよね。
271 = "ええと、これで大丈夫かな。\\nおかしいところないよね。"

# クリス
# うん、入ってきていいよ。
266 = "うん、入ってきていいよ。"

# カズマ
# お、おおー！！
277 = "お、おおー！！"

# クリス
# あは、あはは、部屋で水着姿って\nちょっとおかしいよね。
255 = "あは、あはは、部屋で水着姿って\\nちょっとおかしいよね。"

# カズマ
# それがいいんだ！
294 = "それがいいんだ！"

# クリス
# ごめん、それも理解できないや。
287 = "ごめん、それも理解できないや。"

# カズマ
# おっとそうだ、エプロンを渡すの忘れてた。
279 = "おっとそうだ、エプロンを渡すの忘れてた。"

# クリス
# 忘れてなかったんだね……。
339 = "忘れてなかったんだね……。"

# カズマ
# それがメインだからな！
295 = "それがメインだからな！"

# クリス
# それで料理はリクエストあるの？\nまあ、難しいのを言われても作れないと\n思うけど。
296 = "それで料理はリクエストあるの？\\nまあ、難しいのを言われても作れないと\\n思うけど。"

# カズマ
# クリスに任せる！
329 = "クリスに任せる！"

# クリス
# じゃあ、適当に作るね。
288 = "じゃあ、適当に作るね。"

# クリス
# えっと、鍋は……。
273 = "えっと、鍋は……。"

# カズマ
# お、おお、おおお！！
276 = "お、おお、おおお！！"

# クリス
# え？　え？　何？？　どうしたの？？
274 = "え？　え？　何？？　どうしたの？？"

# クリス
# っていうか、こーら。\n視線の先が怪しいぞ。
305 = "っていうか、こーら。\\n視線の先が怪しいぞ。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、その隠す仕草がまたぐっとくる！）
365 = "（ああ、その隠す仕草がまたぐっとくる！）"

# クリス
# ねえ、暇だったらお風呂にでも入ってきたら？
315 = "ねえ、暇だったらお風呂にでも入ってきたら？"

# カズマ
# そんなもったいないことできるか！
300 = "そんなもったいないことできるか！"

# クリス
# でもさ、見られてると料理に\n集中できないんだよね。
308 = "でもさ、見られてると料理に\\n集中できないんだよね。"

# カズマ
# 別にいいよ、味は二の次だから！
335 = "別にいいよ、味は二の次だから！"

# クリス
# あのねー、料理をしてる女の子を前にして\nその発言はどうかと思うよ。
254 = "あのねー、料理をしてる女の子を前にして\\nその発言はどうかと思うよ。"

# カズマ（Ｍ）
# display as カズマ
# （うぐ、確かに……）
366 = "（うぐ、確かに……）"

# クリス
# というわけで、可能な限り見ない努力を\nしてくれると嬉しいかな。
309 = "というわけで、可能な限り見ない努力を\\nしてくれると嬉しいかな。"

# カズマ
# わかりました！
323 = "わかりました！"

# クリス
# うんうん、いい子いい子。
267 = "うんうん、いい子いい子。"

# カズマ
# ぐあ、もう無理！
283 = "ぐあ、もう無理！"

# クリス
# って、早すぎ！\nちょっと我慢が足りなすぎじゃない？
304 = "って、早すぎ！\\nちょっと我慢が足りなすぎじゃない？"

# カズマ
# だって、水着にエプロンだぞ！\n１秒でも我慢できた俺、かなり偉いと思うんだけど！
302 = "だって、水着にエプロンだぞ！\\n１秒でも我慢できた俺、かなり偉いと思うんだけど！"

# クリス
# そ、そんなにそそる格好なんだね、これって。
292 = "そ、そんなにそそる格好なんだね、これって。"

# カズマ
# 一生見ていられると思う！
332 = "一生見ていられると思う！"

# クリス
# あはは、たぶん１０秒で\n目を潰したくなっちゃうかな。
257 = "あはは、たぶん１０秒で\\n目を潰したくなっちゃうかな。"

# カズマ（Ｍ）
# display as カズマ
# （それはやめてくれ……）
369 = "（それはやめてくれ……）"

# クリス
# あと、本当にあんまり見ないでくれるかな。\n手元が狂って包丁投げちゃいそうになるんだよね。
253 = "あと、本当にあんまり見ないでくれるかな。\\n手元が狂って包丁投げちゃいそうになるんだよね。"

# カズマ
# すんません。
290 = "すんません。"

# クリス
# とか言いながら、まーだ見てるし！
311 = "とか言いながら、まーだ見てるし！"

# カズマ
# これはご褒美なんだぞ！\nクリスに拒否権はないんだからな！
284 = "これはご褒美なんだぞ！\\nクリスに拒否権はないんだからな！"

# クリス
# わ、わかってるよ。
322 = "わ、わかってるよ。"

# クリス
# でも、手元が狂うのは不可抗力だから。\nそれだけは覚えておいて。
306 = "でも、手元が狂うのは不可抗力だから。\\nそれだけは覚えておいて。"

# カズマ（Ｍ）
# display as カズマ
# （むふーん、羞恥に耐えるクリスという絵は\n　なかなか新鮮だな）
370 = "（むふーん、羞恥に耐えるクリスという絵は\\n　なかなか新鮮だな）"

# カズマ（Ｍ）
# display as カズマ
# （包丁が怖いけど、\n　ちょっとちょっかいを出してみるか）
372 = "（包丁が怖いけど、\\n　ちょっとちょっかいを出してみるか）"

# カズマ（Ｍ）
# display as カズマ
# （もしかしたらクリスの違う一面を\n　見られるかもしれない！）
371 = "（もしかしたらクリスの違う一面を\\n　見られるかもしれない！）"

# カズマ
# クリス、水着が食い込んでるぞ。
328 = "クリス、水着が食い込んでるぞ。"

# クリス
# ええ！？
272 = "ええ！？"

# カズマ
# 直した方がいいと思うなー。\nいや、直さなくてもいいけどー。
364 = "直した方がいいと思うなー。\\nいや、直さなくてもいいけどー。"

# クリス
# むかっ。
319 = "むかっ。"

# カズマ
# って、あぶな！？\nお前、包丁投げるなよ！
303 = "って、あぶな！？\\nお前、包丁投げるなよ！"

# クリス
# あはは、あははは。\nごめんね、手元が狂っちゃったみたいっ。
256 = "あはは、あははは。\\nごめんね、手元が狂っちゃったみたいっ。"

# カズマ（Ｍ）
# display as カズマ
# （絶対にわざとだ……目が笑ってないし）
374 = "（絶対にわざとだ……目が笑ってないし）"

# クリス
# ねえ、料理に集中出来ないから、\nちょっと黙っててくれる？
314 = "ねえ、料理に集中出来ないから、\\nちょっと黙っててくれる？"

# クリス
# そうしないと、次は不可抗力で\n命中させちゃうかもしれないから。
293 = "そうしないと、次は不可抗力で\\n命中させちゃうかもしれないから。"

# カズマ
# はい、すみませんでした。
317 = "はい、すみませんでした。"

# クリス
# あ、あと、ちょっと目をつむってて。
252 = "あ、あと、ちょっと目をつむってて。"

# カズマ
# え？　なんで？
275 = "え？　なんで？"

# クリス
# 直したいから……お願い。
363 = "直したいから……お願い。"

# カズマ（Ｍ）
# display as カズマ
# （くっは！　めちゃくちゃかわいい！！）
367 = "（くっは！　めちゃくちゃかわいい！！）"

# カズマ
# 油が飛んだら大変だから俺が守ってやろう。\nその格好じゃ危ないだろ。
344 = "油が飛んだら大変だから俺が守ってやろう。\\nその格好じゃ危ないだろ。"

# クリス
# ありがとう。\nでも、大丈夫だよ。\n今回そんなに油使ってないし。
261 = "ありがとう。\\nでも、大丈夫だよ。\\n今回そんなに油使ってないし。"

# カズマ
# いやいや、そう言わずに。
264 = "いやいや、そう言わずに。"

# クリス
# あはは、大丈夫だって言ってるでしょ？
259 = "あはは、大丈夫だって言ってるでしょ？"

# カズマ
# でもさ、火傷とかしたら大変じゃん。\nだから、側で俺が――
307 = "でもさ、火傷とかしたら大変じゃん。\\nだから、側で俺が――"

# クリス
# それ以上近くに来ない方がいいと思うよ。\nすごい勢いで手元が狂う予感がしてるから。
299 = "それ以上近くに来ない方がいいと思うよ。\\nすごい勢いで手元が狂う予感がしてるから。"

# カズマ
# あははははは、ご冗談を。
260 = "あははははは、ご冗談を。"

# クリス
# 冗談だと思うなら……あと１歩近づいてみたら？
334 = "冗談だと思うなら……あと１歩近づいてみたら？"

# カズマ
# …………。
251 = "…………。"

# クリス
# どうしたのー？\nほーら、もっとこっちにおいでよ。
312 = "どうしたのー？\\nほーら、もっとこっちにおいでよ。"

# カズマ
# え、ええと、座って大人しくしています。
269 = "え、ええと、座って大人しくしています。"

# クリス
# もう、男の子ってエッチだなぁ。
320 = "もう、男の子ってエッチだなぁ。"

# カズマ
# クリスはいいお嫁さんになれるな。
330 = "クリスはいいお嫁さんになれるな。"

# クリス
# きゅ、急になんなのさ！
282 = "きゅ、急になんなのさ！"

# カズマ
# 嫌がりながらも俺のお願いを聞いてくれたじゃん。
337 = "嫌がりながらも俺のお願いを聞いてくれたじゃん。"

# カズマ
# それはきっとクリスは心根が優しいからだと\n思うんだよ。
298 = "それはきっとクリスは心根が優しいからだと\\n思うんだよ。"

# クリス
# そ、そんなことはないと思うけど。
291 = "そ、そんなことはないと思うけど。"

# カズマ
# いや、そんなことあるって。\n料理も美味そうな匂いをしてるし、クリスの\n旦那さんになる人は本当に幸せ者だ。
263 = "いや、そんなことあるって。\\n料理も美味そうな匂いをしてるし、クリスの\\n旦那さんになる人は本当に幸せ者だ。"

# クリス
# う、うーん……。
265 = "う、うーん……。"

# カズマ
# どうした？
313 = "どうした？"

# クリス
# 材料があまりそうだし、もう一品つくってあげるよ。
341 = "材料があまりそうだし、もう一品つくってあげるよ。"

# カズマ
# おお、やった！
278 = "おお、やった！"

[selections]
342 = "水着が食い込んでるぞ"
343 = "油が飛んだら大変だから俺が守ってやろう"
262 = "いいお嫁さんになれるな"
