# rew_a03.txt.scn

[info]
201 = "rew_a03"

[characters]
272 = "アクア"
273 = "カズマ"
275 = "カズマ（Ｍ）"

[character_subs]
# 273 = "カズマ"

[script]
# lines: 69

# アクア
# カズマカズマ、こっちに来て。
274 = "カズマカズマ、こっちに来て。"

# カズマ
# その前に、１つ聞いてもいいか？
248 = "その前に、１つ聞いてもいいか？"

# アクア
# 何かしら。
279 = "何かしら。"

# カズマ
# なんでアイドルの衣装を着てるんだよ。
257 = "なんでアイドルの衣装を着てるんだよ。"

# アクア
# なんでって、あんたアイドル好きでしょ？
256 = "なんでって、あんたアイドル好きでしょ？"

# カズマ
# 俺が好きなのは二次元のだ。\n三次元には興味無し、というわけで\n今すぐ着替えてこい！
283 = "俺が好きなのは二次元のだ。\\n三次元には興味無し、というわけで\\n今すぐ着替えてこい！"

# アクア
# あんた、そのうち友達無くすわよ。
230 = "あんた、そのうち友達無くすわよ。"

# カズマ
# そ、そうですね……。
244 = "そ、そうですね……。"

# アクア
# ほらほら、見つめ合ってあげるから\n早くこっちに来なさいよ。
265 = "ほらほら、見つめ合ってあげるから\\n早くこっちに来なさいよ。"

# カズマ
# あー、俺にはお前が何を言ってるのか理解が\n出来ないんだが。
231 = "あー、俺にはお前が何を言ってるのか理解が\\n出来ないんだが。"

# アクア
# 私にもわからないわよ。
317 = "私にもわからないわよ。"

# アクア
# でも、アイドルに見つめられると天にも昇る気持ち\nになるって、死者の案内をしてるときに聞いたの。
253 = "でも、アイドルに見つめられると天にも昇る気持ち\\nになるって、死者の案内をしてるときに聞いたの。"

# カズマ（Ｍ）
# display as カズマ
# （なるほど、まあ好きな女の子に見つめられたらと\n　考えれば、納得できる話だな）
326 = "（なるほど、まあ好きな女の子に見つめられたらと\\n　考えれば、納得できる話だな）"

# カズマ（Ｍ）
# display as カズマ
# （でも……）
325 = "（でも……）"

# アクア
# あっ、もしかして照れちゃってるの？\n意外にウブなのね、カズマって。
228 = "あっ、もしかして照れちゃってるの？\\n意外にウブなのね、カズマって。"

# カズマ（Ｍ）
# display as カズマ
# （相手がアクアじゃなー……）
329 = "（相手がアクアじゃなー……）"

# アクア
# あ、見つめるだけだからね？\nお喋りや握手は無しだから。
227 = "あ、見つめるだけだからね？\\nお喋りや握手は無しだから。"

# カズマ
# 何でそんなとこだけ妙に現実的なんだ！
280 = "何でそんなとこだけ妙に現実的なんだ！"

# アクア
# もう、さっきから文句ばっかり。\nして欲しいの？　欲しくないの？
267 = "もう、さっきから文句ばっかり。\\nして欲しいの？　欲しくないの？"

# カズマ
# まあ、せっかくだからしては貰うけど……。
266 = "まあ、せっかくだからしては貰うけど……。"

# アクア
# はい、じゃあ私の前に立って。
259 = "はい、じゃあ私の前に立って。"

# カズマ
# はいはい、ほれ。
260 = "はいはい、ほれ。"

# アクア
# それじゃするわよ。\nジーーーーーーーー。
249 = "それじゃするわよ。\\nジーーーーーーーー。"

# カズマ（Ｍ）
# display as カズマ
# （何だこれ。\n　凝視されてるというか、睨まれてるというか）
328 = "（何だこれ。\\n　凝視されてるというか、睨まれてるというか）"

# アクア
# ジィィィィーーーーーっ。
276 = "ジィィィィーーーーーっ。"

# カズマ
# …………。
226 = "…………。"

# アクア
# ちょっと、何か反応しなさいよ。\nアクア様麗しいとか、神々しいとか！\n何かあるでしょ？
252 = "ちょっと、何か反応しなさいよ。\\nアクア様麗しいとか、神々しいとか！\\n何かあるでしょ？"

# カズマ
# いや別に。
234 = "いや別に。"

# アクア
# くぅぅ、こうなったらっ！\nほらっ、もっとこっちに来て！
240 = "くぅぅ、こうなったらっ！\\nほらっ、もっとこっちに来て！"

# カズマ
# うわ！　って、ちち、近いって！
235 = "うわ！　って、ちち、近いって！"

# アクア
# んふ～、どう？\nドキドキしちゃうでしょ？
271 = "んふ～、どう？\\nドキドキしちゃうでしょ？"

# カズマ（Ｍ）
# display as カズマ
# （いくらアクアでも、\n　どどど、童貞には刺激が強すぎる！）
321 = "（いくらアクアでも、\\n　どどど、童貞には刺激が強すぎる！）"

# アクア
# ふっふーん、やっぱりこのアクア様の魅力の前には\nどんな男も抗えないようね。
263 = "ふっふーん、やっぱりこのアクア様の魅力の前には\\nどんな男も抗えないようね。"

# カズマ（Ｍ）
# display as カズマ
# （くそっ、調子に乗りやがって……！）
322 = "（くそっ、調子に乗りやがって……！）"

# カズマ
# おい、小じわがあるぞ。
239 = "おい、小じわがあるぞ。"

# アクア
# えっ！？　う、うそっ！？\nちゃんとお肌のお手入れしてるのに！
237 = "えっ！？　う、うそっ！？\\nちゃんとお肌のお手入れしてるのに！"

# カズマ（Ｍ）
# display as カズマ
# （してたのか。いつも食っちゃ寝してる\n　だけだと思ってたのに）
324 = "（してたのか。いつも食っちゃ寝してる\\n　だけだと思ってたのに）"

# カズマ
# 冗談だよ。でもそんな慌てるってことは、多少\nそういう心当たりでもあるってことだよな。
285 = "冗談だよ。でもそんな慌てるってことは、多少\\nそういう心当たりでもあるってことだよな。"

# アクア
# な、無いわよ！　だいたい女神なんだから、\nそういう肌の劣化なんてないんだからね！
255 = "な、無いわよ！　だいたい女神なんだから、\\nそういう肌の劣化なんてないんだからね！"

# カズマ
# 今、お手入れって……。
278 = "今、お手入れって……。"

# アクア
# それは女子としての最低限のたしなみなの！
250 = "それは女子としての最低限のたしなみなの！"

# カズマ
# よく見ると可愛いな。
270 = "よく見ると可愛いな。"

# アクア
# ふふん、そーでしょ、そーでしょ……って、えっ、\n今なんて……。
264 = "ふふん、そーでしょ、そーでしょ……って、えっ、\\n今なんて……。"

# カズマ
# よぉぉぉぉぉぉぉぉくっ、見ると、可愛いなって。
268 = "よぉぉぉぉぉぉぉぉくっ、見ると、可愛いなって。"

# アクア
# そこ無駄に強調しないでよ！
247 = "そこ無駄に強調しないでよ！"

# カズマ
# いやあ、普段こんなマジマジと見ることなんて\n無かったからな～。いやいや新発見だ。
233 = "いやあ、普段こんなマジマジと見ることなんて\\n無かったからな～。いやいや新発見だ。"

# アクア
# 褒められてるのか、けなされてるのか\n微妙な気分なんですけど。
318 = "褒められてるのか、けなされてるのか\\n微妙な気分なんですけど。"

# カズマ
# けなしてなんていないって。\n褒め言葉は素直に受け取っておけよ。
242 = "けなしてなんていないって。\\n褒め言葉は素直に受け取っておけよ。"

# アクア
# そう？\nじゃあ、えへへ、ありがとう。
246 = "そう？\\nじゃあ、えへへ、ありがとう。"

# カズマ
# 満足したならやめてくれ。
290 = "満足したならやめてくれ。"

# アクア
# あら？　敗北宣言かしら？\nふふん、やっぱりこのアクア様の可愛さは\n罪なのね。
229 = "あら？　敗北宣言かしら？\\nふふん、やっぱりこのアクア様の可愛さは\\n罪なのね。"

# カズマ
# 調子乗ってるようだが、いいか、アクア。
319 = "調子乗ってるようだが、いいか、アクア。"

# アクア
# 何よ。
282 = "何よ。"

# カズマ
# この状況でだな、俺の頭が何かの拍子で動いたり、\nうっかりくしゃみでもしたりしたら……どうなる？
243 = "この状況でだな、俺の頭が何かの拍子で動いたり、\\nうっかりくしゃみでもしたりしたら……どうなる？"

# アクア
# えっ……え、えっ、えええええっ！？
236 = "えっ……え、えっ、えええええっ！？"

# カズマ
# 俺はお前に渾身のヘッドバッドを――
284 = "俺はお前に渾身のヘッドバッドを――"

# カズマ
# ぐあっ！？
241 = "ぐあっ！？"

# アクア
# ふ、ふふふ、フケツよっ、\n女神の唇を奪おうなんて！\nいやぁぁぁ汚されるぅぅぅぅ！！
262 = "ふ、ふふふ、フケツよっ、\\n女神の唇を奪おうなんて！\\nいやぁぁぁ汚されるぅぅぅぅ！！"

# カズマ
# いきなり人の鼻にグーパン入れるやつが、\n汚されるもクソもあるか！
232 = "いきなり人の鼻にグーパン入れるやつが、\\n汚されるもクソもあるか！"

# カズマ
# だいたいお前なんかとキスしたくねーよ！\n呪われたら敵わないからな！
251 = "だいたいお前なんかとキスしたくねーよ！\\n呪われたら敵わないからな！"

# アクア
# ひっどーいっ！\n女神に呪われるとか言うの、\nありえないんですけど！
261 = "ひっどーいっ！\\n女神に呪われるとか言うの、\\nありえないんですけど！"

# アクア
# 謝って！　女神を侮辱したことを謝って！
320 = "謝って！　女神を侮辱したことを謝って！"

# カズマ
# はあぁぁ……。
258 = "はあぁぁ……。"

# アクア
# 何よ、溜め息なんか吐いちゃって。
281 = "何よ、溜め息なんか吐いちゃって。"

# カズマ（Ｍ）
# display as カズマ
# （これがもっと可愛い女の子だったら――\n　なんて言ったら、またうるさくなりそうだし）
323 = "（これがもっと可愛い女の子だったら――\\n　なんて言ったら、またうるさくなりそうだし）"

# カズマ
# とりあえずなんか食わないか、腹減ったし。
254 = "とりあえずなんか食わないか、腹減ったし。"

# アクア
# そうね！\n確か昨日、ダクネスがケーキを買って来てた\nはずよ。
245 = "そうね！\\n確か昨日、ダクネスがケーキを買って来てた\\nはずよ。"

# アクア
# 持ってくるから待ってて！
288 = "持ってくるから待ってて！"

# カズマ（Ｍ）
# display as カズマ
# （まったくご褒美になってねーよ）
327 = "（まったくご褒美になってねーよ）"

[selections]
238 = "おい、小じわがあるぞ"
269 = "よく見ると可愛いな"
289 = "満足したならやめてくれ"
