# rew_a05.txt.scn

[info]
209 = "rew_a05"

[characters]
293 = "アクア"
297 = "カズマ（Ｍ）"
296 = "カズマ"

[character_subs]
# 296 = "カズマ"

[script]
# lines: 88

# アクア
# ねえねえカズマ、ご褒美なんだけど、\nゲームをするっていうのはどうかしら？
281 = "ねえねえカズマ、ご褒美なんだけど、\\nゲームをするっていうのはどうかしら？"

# カズマ（Ｍ）
# display as カズマ
# （ゲーム？　ってまさか……）
335 = "（ゲーム？　ってまさか……）"

# カズマ
# ＰＣとかスマホアプリのことか！？
338 = "ＰＣとかスマホアプリのことか！？"

# アクア
# この世界にそんな物があるわけないでしょ。
254 = "この世界にそんな物があるわけないでしょ。"

# カズマ（Ｍ）
# display as カズマ
# （ですよねー）
332 = "（ですよねー）"

# アクア
# それに知的な私に似合うゲームって言ったら、\nこれしかないじゃない！
264 = "それに知的な私に似合うゲームって言ったら、\\nこれしかないじゃない！"

# カズマ（Ｍ）
# display as カズマ
# （これって将棋？　いや、チェスか？）
329 = "（これって将棋？　いや、チェスか？）"

# カズマ（Ｍ）
# display as カズマ
# （てか、知的な、私に、あう、ゲームだと？）
331 = "（てか、知的な、私に、あう、ゲームだと？）"

# アクア
# 何か言いたそうな顔をしてるわね。
299 = "何か言いたそうな顔をしてるわね。"

# カズマ
# いや、自分がわかってないって可哀想だなって。
241 = "いや、自分がわかってないって可哀想だなって。"

# アクア
# 急にどうしたのよ。\n自己紹介なんて始めて。
313 = "急にどうしたのよ。\\n自己紹介なんて始めて。"

# カズマ（Ｍ）
# display as カズマ
# （こいつはっ）
327 = "（こいつはっ）"

# アクア
# ほーら、カズマここに座って。\n早く、早く！
286 = "ほーら、カズマここに座って。\\n早く、早く！"

# カズマ（Ｍ）
# display as カズマ
# （これってただ、アクアがやりたいだけだろ……）
328 = "（これってただ、アクアがやりたいだけだろ……）"

# アクア
# 何でぇぇぇぇぇ～～～……。
301 = "何でぇぇぇぇぇ～～～……。"

# カズマ
# これで俺の３０戦３０勝っと。\nやばいなー、俺、奨励会に\n入れちゃうんじゃないか？
256 = "これで俺の３０戦３０勝っと。\\nやばいなー、俺、奨励会に\\n入れちゃうんじゃないか？"

# アクア
# あんた、ズルしてないでしょうね！
236 = "あんた、ズルしてないでしょうね！"

# カズマ
# するか！\nっていうかこの手のゲームで\nどうやってズルするんだよ！
261 = "するか！\\nっていうかこの手のゲームで\\nどうやってズルするんだよ！"

# アクア
# くぅぅぅぅ……もう一回！\nもう一回勝負よ！
252 = "くぅぅぅぅ……もう一回！\\nもう一回勝負よ！"

# カズマ
# 懲りないな、お前も……。
314 = "懲りないな、お前も……。"

# アクア
# あっ、ちょっと、それは！
234 = "あっ、ちょっと、それは！"

# カズマ
# 待ったはもうダメだからな。
310 = "待ったはもうダメだからな。"

# アクア
# ん？　ここをこうすればもしかして……。
292 = "ん？　ここをこうすればもしかして……。"

# アクア
# うふふふ、今回は私の勝ちのようね。
242 = "うふふふ、今回は私の勝ちのようね。"

# カズマ
# いいから早くやれよ。
239 = "いいから早くやれよ。"

# アクア
# さあ、私の前にひれ伏しなさい！
258 = "さあ、私の前にひれ伏しなさい！"

# カズマ
# ふむ、なるほど。\nじゃあ、こうだな。
284 = "ふむ、なるほど。\\nじゃあ、こうだな。"

# アクア
# へ？
285 = "へ？"

# カズマ
# 待ったはもう無しだから。
311 = "待ったはもう無しだから。"

# アクア
# 待った！
312 = "待った！"

# カズマ
# だからもう無しだって言っただろ！\nこれで何回目だと思ってんだよ！
269 = "だからもう無しだって言っただろ！\\nこれで何回目だと思ってんだよ！"

# アクア
# まだ１０回かそこらでしょ！
288 = "まだ１０回かそこらでしょ！"

# カズマ
# それはこの対局ではだろ。\nトータルだと数百回は待ったしてるぞ！
265 = "それはこの対局ではだろ。\\nトータルだと数百回は待ったしてるぞ！"

# アクア
# ねえ、ちょっと静かにしてくれない。\n今、考えてるんだから。
280 = "ねえ、ちょっと静かにしてくれない。\\n今、考えてるんだから。"

# カズマ
# お前は人の話を聞けよ！\nあと、勝手に人の駒を動かすな！
251 = "お前は人の話を聞けよ！\\nあと、勝手に人の駒を動かすな！"

# アクア
# えっと、ここがこうなって、ああなって。\nそうしたらぁ。
244 = "えっと、ここがこうなって、ああなって。\\nそうしたらぁ。"

# カズマ（Ｍ）
# display as カズマ
# （はぁぁぁぁ、また長考に入ったよ）
333 = "（はぁぁぁぁ、また長考に入ったよ）"

# アクア
# ぐぬぬぬ、こうしたらこうだから、でも。
253 = "ぐぬぬぬ、こうしたらこうだから、でも。"

# アクア
# あうあう、こうすればもしかして……。
233 = "あうあう、こうすればもしかして……。"

# カズマ
# ふあぁぁぁぁ～～～～～～～。
283 = "ふあぁぁぁぁ～～～～～～～。"

# カズマ（Ｍ）
# display as カズマ
# （さすがに飽きてきたな……）
330 = "（さすがに飽きてきたな……）"

# カズマ
# なあ、なんか面白い話してくれよ。
276 = "なあ、なんか面白い話してくれよ。"

# アクア
# えー、どうしてよ。
246 = "えー、どうしてよ。"

# カズマ
# お前な、これは俺へのご褒美なんだぞ。
248 = "お前な、これは俺へのご褒美なんだぞ。"

# カズマ
# それなのに、お前のワガママに付き合わされる\nばっかりで、何もいいことないじゃねーか。
263 = "それなのに、お前のワガママに付き合わされる\\nばっかりで、何もいいことないじゃねーか。"

# カズマ
# だからせめて、面白い話のひとつでもして\n俺を楽しませろ！
268 = "だからせめて、面白い話のひとつでもして\\n俺を楽しませろ！"

# アクア
# 何よその上から目線。\nちょっと、ムカつくんですけど！
303 = "何よその上から目線。\\nちょっと、ムカつくんですけど！"

# カズマ
# いいから何か話せ。\nそれができないなら、とっとと次の一手を指せよ！
238 = "いいから何か話せ。\\nそれができないなら、とっとと次の一手を指せよ！"

# アクア
# わかったわ。\nでも、怖い話でもいいかしら。
291 = "わかったわ。\\nでも、怖い話でもいいかしら。"

# カズマ
# なんだよ、ずいぶん素直じゃないか……。
279 = "なんだよ、ずいぶん素直じゃないか……。"

# アクア
# この前、なんとなくカズマの部屋に入ったんだけど。
255 = "この前、なんとなくカズマの部屋に入ったんだけど。"

# カズマ
# 入るなよ！
304 = "入るなよ！"

# アクア
# その時ね、ベッドの下からチラっと何かが\n見えてたのよ。
262 = "その時ね、ベッドの下からチラっと何かが\\n見えてたのよ。"

# カズマ（Ｍ）
# display as カズマ
# （！？）
337 = "（！？）"

# アクア
# 何かなって、引っ張ってみたら――
298 = "何かなって、引っ張ってみたら――"

# カズマ
# だーーーーーーーー！！\nわかった、もういい！
271 = "だーーーーーーーー！！\\nわかった、もういい！"

# カズマ
# 好きなだけ長考して良いから、やめてくれっ！！
308 = "好きなだけ長考して良いから、やめてくれっ！！"

# アクア
# 何よ、遠慮することないのに。
302 = "何よ、遠慮することないのに。"

# カズマ（Ｍ）
# display as カズマ
# （こいつ、本当に女神なのか……）
326 = "（こいつ、本当に女神なのか……）"

# カズマ
# なあアクア、もうこれ、お前に勝ち目無いぞ？
277 = "なあアクア、もうこれ、お前に勝ち目無いぞ？"

# アクア
# どうしてそう言い切れるのよ。
274 = "どうしてそう言い切れるのよ。"

# カズマ
# だって、どこからどう見ても、\n逃げ場がないだろ。
270 = "だって、どこからどう見ても、\\n逃げ場がないだろ。"

# アクア
# それは！\nカズマあなたに勝利の道筋が見えていないだけよ！
266 = "それは！\\nカズマあなたに勝利の道筋が見えていないだけよ！"

# カズマ
# じゃあ、お前には見えてるのか？
259 = "じゃあ、お前には見えてるのか？"

# アクア
# えっとぉ～、あともうちょっとで\n見える予定です。
245 = "えっとぉ～、あともうちょっとで\\n見える予定です。"

# カズマ（Ｍ）
# display as カズマ
# （まったく、何時間かかるやら）
334 = "（まったく、何時間かかるやら）"

# カズマ
# お前は、なんでも楽しそうにやるよな。
249 = "お前は、なんでも楽しそうにやるよな。"

# アクア
# むぅ～、そうかしら？
289 = "むぅ～、そうかしら？"

# カズマ
# なんだ、今は楽しくないのか？
278 = "なんだ、今は楽しくないのか？"

# アクア
# じゃあ聞きますけどー、\n今の状況で、私に何を楽しめっていうんですかー。
260 = "じゃあ聞きますけどー、\\n今の状況で、私に何を楽しめっていうんですかー。"

# カズマ（Ｍ）
# display as カズマ
# （確かにこれだけ負け込んでたらなー）
336 = "（確かにこれだけ負け込んでたらなー）"

# カズマ
# まあいいや。\n好きなだけ考えろって。
287 = "まあいいや。\\n好きなだけ考えろって。"

# アクア
# うーん、ここをこうして、あっちをああして……。
243 = "うーん、ここをこうして、あっちをああして……。"

# カズマ
# ふあぁぁぁ……んで、いい加減そろそろ次の手、\n決まったか？
282 = "ふあぁぁぁ……んで、いい加減そろそろ次の手、\\n決まったか？"

# アクア
# あー、もう、話しかけないでよ！\n頭の中の駒がバラバラになっちゃったじゃない！
237 = "あー、もう、話しかけないでよ！\\n頭の中の駒がバラバラになっちゃったじゃない！"

# カズマ
# てかさ、考えるのはけっこうだけど、\nとりあえずそのあぐらかいて肘つくのは\nおっさんくさいからやめろって。
273 = "てかさ、考えるのはけっこうだけど、\\nとりあえずそのあぐらかいて肘つくのは\\nおっさんくさいからやめろって。"

# アクア
# 別に良いじゃない。\n誰かが見てるわけじゃないんだし。
305 = "別に良いじゃない。\\n誰かが見てるわけじゃないんだし。"

# カズマ
# 目の前に俺がいるだろ……。
315 = "目の前に俺がいるだろ……。"

# アクア
# あらぁん、もしかしてカズマさんってぇ、\n私をそういう目で見てたんですか～？
235 = "あらぁん、もしかしてカズマさんってぇ、\\n私をそういう目で見てたんですか～？"

# カズマ
# え？　何言ってるの？\nまったく見てないけど？
247 = "え？　何言ってるの？\\nまったく見てないけど？"

# アクア
# そんな照れ隠しいらないったら～。\nもう、正直に言っちゃいなさいよ、ほらほら～。
267 = "そんな照れ隠しいらないったら～。\\nもう、正直に言っちゃいなさいよ、ほらほら～。"

# カズマ
# いや、ほんとごめん……。\nマジで、ごめん……。
240 = "いや、ほんとごめん……。\\nマジで、ごめん……。"

# アクア
# ちょっとカズマ、本気で謝るとかやめてよ！
272 = "ちょっとカズマ、本気で謝るとかやめてよ！"

# アクア
# 女のプライドが、女神の自尊心が、ズッタズタに\nなっちゃうからぁ！
307 = "女のプライドが、女神の自尊心が、ズッタズタに\\nなっちゃうからぁ！"

# カズマ
# アクア……。
294 = "アクア……。"

# アクア
# な、何？
275 = "な、何？"

# カズマ
# ごめんな。
257 = "ごめんな。"

# アクア
# カァァァズマさぁぁぁん！！！
295 = "カァァァズマさぁぁぁん！！！"

[selections]
300 = "何か面白い話してくれよ"
290 = "もうこれ、勝ち目無いぞ？"
250 = "お前はなんでも楽しそうにやるよな"
