# rew_c07.txt.scn

[info]
237 = "rew_c07"

[characters]
307 = "カズマ"
305 = "アクア"
309 = "カズマ（Ｍ）"
300 = "めぐみん"
311 = "ダクネス"

[character_subs]
# 307 = "カズマ"

[script]
# lines: 76

# カズマ
# いーやーだ！　断固として拒否する！
265 = "いーやーだ！　断固として拒否する！"

# アクア
# これはお仕置きなんだから、カズマに拒否権は\nないの。
275 = "これはお仕置きなんだから、カズマに拒否権は\\nないの。"

# カズマ
# だからって四つん這いになんてなれるか！\n土下座をさせるつもりなんだろ、どうせ！
287 = "だからって四つん這いになんてなれるか！\\n土下座をさせるつもりなんだろ、どうせ！"

# アクア
# ああ、なるほどそれも悪くないわね。
260 = "ああ、なるほどそれも悪くないわね。"

# カズマ（Ｍ）
# display as カズマ
# （藪蛇だったー！！）
391 = "（藪蛇だったー！！）"

# アクア
# じゃあおまけで土下座もやってもらおうかしら。
279 = "じゃあおまけで土下座もやってもらおうかしら。"

# カズマ
# お仕置きはひとつだけ！\nおまけなんて受け付けないからな！
271 = "お仕置きはひとつだけ！\\nおまけなんて受け付けないからな！"

# めぐみん
# アクア、さっきからまったく話が進んでいませんよ。
306 = "アクア、さっきからまったく話が進んでいませんよ。"

# ダクネス
# そろそろカズマに何をさせたいのか教えてくれ。
284 = "そろそろカズマに何をさせたいのか教えてくれ。"

# アクア
# それはズバリ、人間椅子よ！
283 = "それはズバリ、人間椅子よ！"

# カズマ
# は？　なんだそれ？
297 = "は？　なんだそれ？"

# アクア
# だから、四つん這いになったカズマに\n私たちが座ってくつろぐの。
286 = "だから、四つん這いになったカズマに\\n私たちが座ってくつろぐの。"

# アクア
# どう？　最高に屈辱的なお仕置きだと思わない？
293 = "どう？　最高に屈辱的なお仕置きだと思わない？"

# めぐみん
# そんなことをするくらいなら、\n舌を噛み切って自害をしますね。
285 = "そんなことをするくらいなら、\\n舌を噛み切って自害をしますね。"

# ダクネス
# そ、そうだな。\n私もそうするかもしれない。
281 = "そ、そうだな。\\n私もそうするかもしれない。"

# カズマ（Ｍ）
# display as カズマ
# （嘘をつくな……）
389 = "（嘘をつくな……）"

# アクア
# というわけで、ほら、早く四つん這いになって。
290 = "というわけで、ほら、早く四つん這いになって。"

# カズマ（Ｍ）
# display as カズマ
# （ふっ、アクアは俺を甘く見ているな）
384 = "（ふっ、アクアは俺を甘く見ているな）"

# カズマ（Ｍ）
# display as カズマ
# （女の子に座られる！\n　確かに屈辱的だが、見方を変えれば\n　素晴らしいご褒美じゃないか！）
390 = "（女の子に座られる！\\n　確かに屈辱的だが、見方を変えれば\\n　素晴らしいご褒美じゃないか！）"

# カズマ（Ｍ）
# display as カズマ
# （それにこの程度の事態、簡単に避けられるぜ）
381 = "（それにこの程度の事態、簡単に避けられるぜ）"

# カズマ（Ｍ）
# display as カズマ
# （だが、アクアの言いなりになるのだけは、\n　絶対に嫌だ！）
383 = "（だが、アクアの言いなりになるのだけは、\\n　絶対に嫌だ！）"

# カズマ
# よし、わかったやろう。\nただし、俺に座るのはダクネスだけだ。
303 = "よし、わかったやろう。\\nただし、俺に座るのはダクネスだけだ。"

# カズマ
# 俺はダクネスにお仕置きを頼んだんだから、\n何も問題ないだろ？
318 = "俺はダクネスにお仕置きを頼んだんだから、\\n何も問題ないだろ？"

# めぐみん
# 確かに、一理ありますね。
372 = "確かに、一理ありますね。"

# アクア
# うーん、しょうがないから、それで呑んであげるわ。
268 = "うーん、しょうがないから、それで呑んであげるわ。"

# カズマ
# というわけで、そら、ダクネス！
289 = "というわけで、そら、ダクネス！"

# ダクネス
# ほ、本当に良いのか？
299 = "ほ、本当に良いのか？"

# カズマ
# 当然だ！
326 = "当然だ！"

# ダクネス
# じゃ、じゃあ、座るぞ？
278 = "じゃ、じゃあ、座るぞ？"

# カズマ（Ｍ）
# display as カズマ
# （さて、どうするかな）
380 = "（さて、どうするかな）"

# カズマ
# あー、もしかしたら体重がわかっちゃうかもなー。
262 = "あー、もしかしたら体重がわかっちゃうかもなー。"

# ダクネス
# ひぅ！
298 = "ひぅ！"

# カズマ
# どうしたんだ？\n早く座れよ、ダクネス。
291 = "どうしたんだ？\\n早く座れよ、ダクネス。"

# ダクネス
# い、いや、しかし。
263 = "い、いや、しかし。"

# カズマ
# 別に何もしないって。
321 = "別に何もしないって。"

# ダクネス
# うぅ、わ、わかった……。
266 = "うぅ、わ、わかった……。"

# カズマ
# ダクネスの身長だと体重はどれくらいかな？
313 = "ダクネスの身長だと体重はどれくらいかな？"

# ダクネス
# なっ！？
296 = "なっ！？"

# カズマ（Ｍ）
# display as カズマ
# （体重を気にするなんて、\n　ダクネスも女の子なんだな）
388 = "（体重を気にするなんて、\\n　ダクネスも女の子なんだな）"

# カズマ（Ｍ）
# display as カズマ
# （よしっ、背中に意識を集中だ！）
386 = "（よしっ、背中に意識を集中だ！）"

# ダクネス
# え、ええと、この辺でいいのか？
269 = "え、ええと、この辺でいいのか？"

# カズマ（Ｍ）
# display as カズマ
# （これがダクネスのお尻の感触か！）
379 = "（これがダクネスのお尻の感触か！）"

# カズマ（Ｍ）
# display as カズマ
# （ほんのりとお尻の熱が伝わって来て、\n　これはとてもいいものだ！）
385 = "（ほんのりとお尻の熱が伝わって来て、\\n　これはとてもいいものだ！）"

# ダクネス
# カズマ？
310 = "カズマ？"

# カズマ
# ああ、悪い。\nそこはちょっと痛いから少し位置を調整してくれ。
261 = "ああ、悪い。\\nそこはちょっと痛いから少し位置を調整してくれ。"

# ダクネス
# こ、こうか？
274 = "こ、こうか？"

# カズマ（Ｍ）
# display as カズマ
# （お尻の肉が背中に擦れる感触、たまらん！）
378 = "（お尻の肉が背中に擦れる感触、たまらん！）"

# ダクネス
# もっとこっちの方か？
302 = "もっとこっちの方か？"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスはおっぱいだけじゃなかったんだな！）
387 = "（ダクネスはおっぱいだけじゃなかったんだな！）"

# ダクネス
# カズマ、黙っていられるのは困るのだが。
308 = "カズマ、黙っていられるのは困るのだが。"

# カズマ
# ダクネス、お前は最高だ！
312 = "ダクネス、お前は最高だ！"

# ダクネス
# え？　え？
270 = "え？　え？"

# カズマ（Ｍ）
# display as カズマ
# （ああ、この時間が少しでも長く続けばいいのに）
377 = "（ああ、この時間が少しでも長く続けばいいのに）"

# カズマ
# どうせやるなら、馬乗りでもいいんだぞ？
292 = "どうせやるなら、馬乗りでもいいんだぞ？"

# ダクネス
# いや、さすがにそれは。
264 = "いや、さすがにそれは。"

# カズマ
# 遠慮するなって。\n俺がいいって言ってるんだから。
375 = "遠慮するなって。\\n俺がいいって言ってるんだから。"

# ダクネス
# そ、そうか？　じゃあ――
280 = "そ、そうか？　じゃあ――"

# アクア
# ダメよ！　カズマは乗馬プレイをして\n楽しむつもりなんだから！
314 = "ダメよ！　カズマは乗馬プレイをして\\n楽しむつもりなんだから！"

# ダクネス
# 乗馬プレイ！？\nなんだそのいやらしそうな響きは！
316 = "乗馬プレイ！？\\nなんだそのいやらしそうな響きは！"

# カズマ（Ｍ）
# display as カズマ
# （それは俺も知りたい……）
382 = "（それは俺も知りたい……）"

# アクア
# きっとカズマは暴れ馬になって、\nダクネスにも襲いかかるつもりなんだわ。
273 = "きっとカズマは暴れ馬になって、\\nダクネスにも襲いかかるつもりなんだわ。"

# ダクネス
# あ、ああ、暴れ馬で私を無茶苦茶にする！？
259 = "あ、ああ、暴れ馬で私を無茶苦茶にする！？"

# カズマ
# しねーよ！\nそれにお前はちょっと嬉しそうな顔をするな！
277 = "しねーよ！\\nそれにお前はちょっと嬉しそうな顔をするな！"

# ダクネス
# そ、そんな、嬉しそうになんてしてないぞ？
282 = "そ、そんな、嬉しそうになんてしてないぞ？"

# カズマ（Ｍ）
# display as カズマ
# （頬を緩めながら言っても説得力は皆無だよ）
392 = "（頬を緩めながら言っても説得力は皆無だよ）"

# ダクネス
# なあ、アクア。\nやはりこれはやり過ぎだと思うんだ。
295 = "なあ、アクア。\\nやはりこれはやり過ぎだと思うんだ。"

# ダクネス
# お仕置きを通り越して、\n人の権利を踏みにじる行為になっているぞ。
272 = "お仕置きを通り越して、\\n人の権利を踏みにじる行為になっているぞ。"

# めぐみん
# 確かにそうですね。
373 = "確かにそうですね。"

# アクア
# でもそれって、相手が人間ならって理屈でしょ？
288 = "でもそれって、相手が人間ならって理屈でしょ？"

# カズマ
# 俺は人間なんですけど！
319 = "俺は人間なんですけど！"

# アクア
# 冗談よ、冗談。\n確かにちょっとやり過ぎたわ、ごめんね。
320 = "冗談よ、冗談。\\n確かにちょっとやり過ぎたわ、ごめんね。"

# カズマ
# うわー、ちっとも誠意を感じられねー。
267 = "うわー、ちっとも誠意を感じられねー。"

# ダクネス
# な、なあ、カズマ……。
294 = "な、なあ、カズマ……。"

# カズマ
# ん？　どうした？
304 = "ん？　どうした？"

# ダクネス
# もし気が収まらないなら、\n私を椅子のように扱ってくれてもいいんだぞ。
301 = "もし気が収まらないなら、\\n私を椅子のように扱ってくれてもいいんだぞ。"

# カズマ
# しねーよ……。
276 = "しねーよ……。"

[selections]
317 = "体重がわかっちゃうかもなー"
374 = "背中に意識を集中だ！"
376 = "馬乗りでもいいんだぞ？"
