# rew_d07.txt.scn

[info]
296 = "rew_d07"

[characters]
418 = "クリス"
415 = "カズマ"
416 = "カズマ（Ｍ）"

[character_subs]
# 415 = "カズマ"

[script]
# lines: 153

# クリス
# ねぇねぇ、お仕置きってさ。\nなんでも頼んでいいんだよね？
398 = "ねぇねぇ、お仕置きってさ。\\nなんでも頼んでいいんだよね？"

# カズマ
# パンツ一丁で街の中を走って来いとか\nそういう無茶ぶりは勘弁して欲しいけどな。
423 = "パンツ一丁で街の中を走って来いとか\\nそういう無茶ぶりは勘弁して欲しいけどな。"

# クリス
# ああ、それはちょっと面白いかも！
327 = "ああ、それはちょっと面白いかも！"

# カズマ
# おい、今のは冗談だぞ！　本気にするな！
359 = "おい、今のは冗談だぞ！　本気にするな！"

# クリス
# わかってるって。\nいくらなんでもそんなことやらせないよ。\nやってもらったって何の得にもならないしね。
407 = "わかってるって。\\nいくらなんでもそんなことやらせないよ。\\nやってもらったって何の得にもならないしね。"

# カズマ
# はぁ、それで？\nお仕置きって何をやらせるつもりなんだ？
400 = "はぁ、それで？\\nお仕置きって何をやらせるつもりなんだ？"

# クリス
# うん、この服を直して貰おうかなって。
352 = "うん、この服を直して貰おうかなって。"

# カズマ
# ああ、いつもつけてるマントじゃないか。\nどうしたんだこれ、酷くボロボロになってるな。
325 = "ああ、いつもつけてるマントじゃないか。\\nどうしたんだこれ、酷くボロボロになってるな。"

# クリス
# あはは、ちょっとドジしちゃってさ。
336 = "あはは、ちょっとドジしちゃってさ。"

# カズマ
# おいおい、無茶してるんじゃないだろうな。
360 = "おいおい、無茶してるんじゃないだろうな。"

# クリス
# 今回は初心者パーティーのヘルプだったから\nある程度は覚悟してたんだけど――
425 = "今回は初心者パーティーのヘルプだったから\\nある程度は覚悟してたんだけど――"

# クリス
# 予想以上に協調性が皆無でさ。\nさすがに骨が折れたよ。
424 = "予想以上に協調性が皆無でさ。\\nさすがに骨が折れたよ。"

# カズマ
# それは大変だったな。
375 = "それは大変だったな。"

# クリス
# というわけでぐったりなあたしに、\n救いの手をお願いします。
393 = "というわけでぐったりなあたしに、\\n救いの手をお願いします。"

# カズマ
# おう、俺の裁縫スキルが火を噴くぜ！
362 = "おう、俺の裁縫スキルが火を噴くぜ！"

# クリス
# さて、じゃああたしはチューブトップをっと。
367 = "さて、じゃああたしはチューブトップをっと。"

# カズマ
# ん、それも俺が直してやろうか？
408 = "ん、それも俺が直してやろうか？"

# クリス
# いやいや、これはいいよ、あはは。
346 = "いやいや、これはいいよ、あはは。"

# カズマ
# でも、マントの修理はすぐに終わっちまうぞ。\nそれじゃお仕置きにならないんじゃないのか？
392 = "でも、マントの修理はすぐに終わっちまうぞ。\\nそれじゃお仕置きにならないんじゃないのか？"

# クリス
# いやね、時間とかそういう問題じゃなくて。
348 = "いやね、時間とかそういう問題じゃなくて。"

# カズマ
# ほーら、遠慮するなって。
404 = "ほーら、遠慮するなって。"

# クリス
# うぅ、下心はないみたいだし……。
350 = "うぅ、下心はないみたいだし……。"

# クリス
# じゃあ、お願いしちゃおうかな。
370 = "じゃあ、お願いしちゃおうかな。"

# カズマ
# おう、任せておけ！
361 = "おう、任せておけ！"

# クリス
# …………。
317 = "…………。"

# カズマ
# ～～～～♪
505 = "～～～～♪"

# クリス
# …………。
# 317 = "…………。"

# カズマ
# ～～～～♪
# 505 = "～～～～♪"

# クリス
# …………。
# 317 = "…………。"

# カズマ
# あのー、クリスさん。\nさっきから視線が気になるんですけど。
332 = "あのー、クリスさん。\\nさっきから視線が気になるんですけど。"

# クリス
# え、あ、上手いもんだなって思ってさ。
356 = "え、あ、上手いもんだなって思ってさ。"

# カズマ（Ｍ）
# display as カズマ
# （その割には、様子が変だな。\n　顔が赤いし……）
487 = "（その割には、様子が変だな。\\n　顔が赤いし……）"

# クリス
# あ、あの、カズマ？\nやっぱりそれはあたしが直そうかな。
320 = "あ、あの、カズマ？\\nやっぱりそれはあたしが直そうかな。"

# カズマ
# もう途中までやっちゃってるだろ。\nそんなに直したいなら手付かずのマントを\nやってくれよ。
405 = "もう途中までやっちゃってるだろ。\\nそんなに直したいなら手付かずのマントを\\nやってくれよ。"

# クリス
# いやぁ、そういう意味じゃなくてね。
345 = "いやぁ、そういう意味じゃなくてね。"

# カズマ
# だったらなんなんだよ。
379 = "だったらなんなんだよ。"

# クリス
# だ、だからぁ。その服は……。
377 = "だ、だからぁ。その服は……。"

# カズマ（Ｍ）
# display as カズマ
# （この服に何か問題が……ってもしかして！？）
483 = "（この服に何か問題が……ってもしかして！？）"

# カズマ（Ｍ）
# display as カズマ
# （これってクリスの胸を隠してるやつ！？）
484 = "（これってクリスの胸を隠してるやつ！？）"

# カズマ（Ｍ）
# display as カズマ
# （何も考えないで直すって言っちゃったけど、\n　これって、下着みたいなもんじゃねーか！）
496 = "（何も考えないで直すって言っちゃったけど、\\n　これって、下着みたいなもんじゃねーか！）"

# カズマ（Ｍ）
# display as カズマ
# （やばい、どうしよう。\n　でも今さら返したところで気まずいし……）
495 = "（やばい、どうしよう。\\n　でも今さら返したところで気まずいし……）"

# カズマ（Ｍ）
# display as カズマ
# （無心だ。無心になるんだサトウカズマ。\n　とにかく無心でさっさと終わらせるんだ！）
502 = "（無心だ。無心になるんだサトウカズマ。\\n　とにかく無心でさっさと終わらせるんだ！）"

# カズマ
# チクチクチクチク。
422 = "チクチクチクチク。"

# クリス
# う、うぅ……。
349 = "う、うぅ……。"

# カズマ
# チクチクチクチ。
421 = "チクチクチクチ。"

# クリス
# あ、あ、そこは触っちゃダメ！
318 = "あ、あ、そこは触っちゃダメ！"

# カズマ（Ｍ）
# display as カズマ
# （な、なんで！？\n　この部分はクリスのどこが触れる所なの！！）
492 = "（な、なんで！？\\n　この部分はクリスのどこが触れる所なの！！）"

# カズマ
# って、痛っ！
389 = "って、痛っ！"

# カズマ（Ｍ）
# display as カズマ
# （っと、しまった。\n　指に針を刺しちまったな）
490 = "（っと、しまった。\\n　指に針を刺しちまったな）"

# クリス
# ちょっと、大丈夫？\nああ、血が出ちゃってるじゃない。
386 = "ちょっと、大丈夫？\\nああ、血が出ちゃってるじゃない。"

# カズマ
# これくらい平気だよ。
366 = "これくらい平気だよ。"

# クリス
# ほら、指出して。治してあげるから。
402 = "ほら、指出して。治してあげるから。"

# カズマ
# お前、ヒールなんて使えるのか？
364 = "お前、ヒールなんて使えるのか？"

# クリス
# そんな大袈裟な怪我じゃないでしょ。\nこの程度なら民間療法で十分だよ。
376 = "そんな大袈裟な怪我じゃないでしょ。\\nこの程度なら民間療法で十分だよ。"

# カズマ
# 民間療法？　なんだそれ？
433 = "民間療法？　なんだそれ？"

# クリス
# あむ、こういうの。
339 = "あむ、こういうの。"

# カズマ
# ちょぉおおおおおおお！！
384 = "ちょぉおおおおおおお！！"

# クリス
# 何、どうしたの？？
427 = "何、どうしたの？？"

# カズマ（Ｍ）
# display as カズマ
# （それは俺の台詞だって！\n　こいつは急に何すんだ！！）
488 = "（それは俺の台詞だって！\\n　こいつは急に何すんだ！！）"

# クリス
# もしかして、汚いって思ってる？
406 = "もしかして、汚いって思ってる？"

# カズマ
# そ、そうじゃなくてな……。
371 = "そ、そうじゃなくてな……。"

# クリス
# だったらほら指を出して。\nばい菌が入ったら、それこそ大変だよ？
380 = "だったらほら指を出して。\\nばい菌が入ったら、それこそ大変だよ？"

# カズマ
# じゃ、じゃあ、よろしくお願いします。
369 = "じゃ、じゃあ、よろしくお願いします。"

# クリス
# はい、任されました。
401 = "はい、任されました。"

# クリス
# あむ……ちゅ。
337 = "あむ……ちゅ。"

# カズマ（Ｍ）
# display as カズマ
# （くほっ、何この幸せな状況！\n　お仕置きじゃなくてご褒美なんですけど！）
482 = "（くほっ、何この幸せな状況！\\n　お仕置きじゃなくてご褒美なんですけど！）"

# クリス
# あ、トイレ行ってないよね？
323 = "あ、トイレ行ってないよね？"

# カズマ
# 雰囲気台無しだな！
471 = "雰囲気台無しだな！"

# クリス
# 雰囲気？
472 = "雰囲気？"

# カズマ
# あっ、いや、なんでもない！
330 = "あっ、いや、なんでもない！"

# カズマ（Ｍ）
# display as カズマ
# （無意識ってこえー。破壊力抜群だわ）
503 = "（無意識ってこえー。破壊力抜群だわ）"

# クリス
# ん～、なかなか止まらないね。\n吸った方が、いいのかな？
412 = "ん～、なかなか止まらないね。\\n吸った方が、いいのかな？"

# カズマ（Ｍ）
# display as カズマ
# （吸うとかダメ！　絶対ダメ！）
498 = "（吸うとかダメ！　絶対ダメ！）"

# カズマ（Ｍ）
# display as カズマ
# （なんでダメなんだかよくわからないけど、\n　とにかくそれはダメ！！）
493 = "（なんでダメなんだかよくわからないけど、\\n　とにかくそれはダメ！！）"

# カズマ（Ｍ）
# display as カズマ
# （指を抜こう！\n　うん、それがいい。そうしよう！）
499 = "（指を抜こう！\\n　うん、それがいい。そうしよう！）"

# カズマ
# てーい！！
390 = "てーい！！"

# クリス
# ちょっと、乱暴に抜いたら危ないよ！
385 = "ちょっと、乱暴に抜いたら危ないよ！"

# カズマ
# あ、ああ、すまん。
319 = "あ、ああ、すまん。"

# クリス
# ほーら、まだ血が止まってないんだから、\n指を貸して。
403 = "ほーら、まだ血が止まってないんだから、\\n指を貸して。"

# カズマ
# それはダメです！
374 = "それはダメです！"

# クリス
# どうして？
395 = "どうして？"

# カズマ
# ああ、いや、その。\nこれくらいは自分でできるから！
326 = "ああ、いや、その。\\nこれくらいは自分でできるから！"

# カズマ
# あむ、ぺろぺろぺろ。
340 = "あむ、ぺろぺろぺろ。"

# クリス
# ちょっと！？
388 = "ちょっと！？"

# カズマ
# あは、あはは、本当だ、なかなか血が止まらないね。
333 = "あは、あはは、本当だ、なかなか血が止まらないね。"

# クリス
# なるほど、そういう狙いだったわけだね。
397 = "なるほど、そういう狙いだったわけだね。"

# カズマ
# え……何が？
355 = "え……何が？"

# クリス
# しらばっくれないで。\n間接……キス、狙ってやったんでしょ。
368 = "しらばっくれないで。\\n間接……キス、狙ってやったんでしょ。"

# カズマ
# 違うし！\nてか、それは照れるの！？
470 = "違うし！\\nてか、それは照れるの！？"

# クリス
# 何、どういう意味？
426 = "何、どういう意味？"

# カズマ
# だってさっきまで俺の指を舐めてたじゃん。
383 = "だってさっきまで俺の指を舐めてたじゃん。"

# クリス
# うん、それがどうかした？
353 = "うん、それがどうかした？"

# カズマ
# いや、そっちを照れろよ！
344 = "いや、そっちを照れろよ！"

# カズマ（Ｍ）
# display as カズマ
# （いや、しかし！\n　クリスの好意を無下にするのは……）
476 = "（いや、しかし！\\n　クリスの好意を無下にするのは……）"

# カズマ（Ｍ）
# display as カズマ
# （流れに身を任せよう。\n　うん、そうだ。それしかない）
501 = "（流れに身を任せよう。\\n　うん、そうだ。それしかない）"

# クリス
# あむ、うーん、なんで止まらないかなー。
338 = "あむ、うーん、なんで止まらないかなー。"

# カズマ（Ｍ）
# display as カズマ
# （うおっ、くおっ！）
478 = "（うおっ、くおっ！）"

# クリス
# ん～、やっぱり吸わないとダメだね。\nちゅぅぅぅ～～～～！！
414 = "ん～、やっぱり吸わないとダメだね。\\nちゅぅぅぅ～～～～！！"

# カズマ（Ｍ）
# display as カズマ
# （ぬおおおおおおおおお！！）
494 = "（ぬおおおおおおおおお！！）"

# クリス
# ん～、もうちょっとな感じだよ。
413 = "ん～、もうちょっとな感じだよ。"

# カズマ
# そそ、そうですか！
373 = "そそ、そうですか！"

# クリス
# あとはしっかりと舐めて……。
331 = "あとはしっかりと舐めて……。"

# カズマ
# あかーん、それはダメ！！
329 = "あかーん、それはダメ！！"

# クリス
# ちょっと急に抜いたら危ない。
387 = "ちょっと急に抜いたら危ない。"

# カズマ
# 俺は違う意味で危ないわ！
429 = "俺は違う意味で危ないわ！"

# クリス
# え、何それ？
357 = "え、何それ？"

# カズマ
# お前は女の子だろ！
365 = "お前は女の子だろ！"

# クリス
# どうしたの急に。
394 = "どうしたの急に。"

# カズマ
# おおお、女の子が、無防備に指を舐めるとか\n絶対にしちゃいけないことだ！
363 = "おおお、女の子が、無防備に指を舐めるとか\\n絶対にしちゃいけないことだ！"

# クリス
# ああ、なるほど、そういうことか。\nあはは、確かによく考えると恥ずかしいことだね。
328 = "ああ、なるほど、そういうことか。\\nあはは、確かによく考えると恥ずかしいことだね。"

# カズマ
# 気がつかなかったのかよ。
434 = "気がつかなかったのかよ。"

# カズマ（Ｍ）
# display as カズマ
# （駄目だ何も考えられない……。\n　これはもう、欲望のまま突っ走るしか！）
504 = "（駄目だ何も考えられない……。\\n　これはもう、欲望のまま突っ走るしか！）"

# カズマ
# クリス！！
420 = "クリス！！"

# クリス
# ん？
411 = "ん？"

# カズマ（Ｍ）
# display as カズマ
# （……まてまてまて！　落ち着け俺！）
474 = "（……まてまてまて！　落ち着け俺！）"

# カズマ（Ｍ）
# display as カズマ
# （いくらなんでも相手の意思を\n　無視して行くのはマズイだろ）
475 = "（いくらなんでも相手の意思を\\n　無視して行くのはマズイだろ）"

# カズマ（Ｍ）
# display as カズマ
# （これでクリスに悲鳴でもあげられてみろ。\n　アクアたちにこの場面を見られたら\n　童貞乙とか変態とか言われるんだぞ！）
485 = "（これでクリスに悲鳴でもあげられてみろ。\\n　アクアたちにこの場面を見られたら\\n　童貞乙とか変態とか言われるんだぞ！）"

# クリス
# あ、もしかして痛かった？\nごめんね。でも、まだ血が止まってないから\nもう少しだけ我慢してね。
322 = "あ、もしかして痛かった？\\nごめんね。でも、まだ血が止まってないから\\nもう少しだけ我慢してね。"

# クリス
# ん、ん～、ちゅ……。
410 = "ん、ん～、ちゅ……。"

# カズマ（Ｍ）
# display as カズマ
# （くっはぁ！）
481 = "（くっはぁ！）"

# カズマ（Ｍ）
# display as カズマ
# （おおおお、落ち着けサトウカズマ！）
480 = "（おおおお、落ち着けサトウカズマ！）"

# カズマ（Ｍ）
# display as カズマ
# （俺は我慢のできる男だ。\n　鋼の精神を持ち、耐える力を持つ男だ）
497 = "（俺は我慢のできる男だ。\\n　鋼の精神を持ち、耐える力を持つ男だ）"

# カズマ（Ｍ）
# display as カズマ
# （どんなに今の状況が据え前だとしても、\n　ここで手を出して本当の犯罪者になって\n　いいのか！？）
491 = "（どんなに今の状況が据え前だとしても、\\n　ここで手を出して本当の犯罪者になって\\n　いいのか！？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、待てよ。\n　お互い同意の上なら問題ないんじゃないか？\n　むしろ説明できたらオッケーなんじゃ？）
477 = "（いや、待てよ。\\n　お互い同意の上なら問題ないんじゃないか？\\n　むしろ説明できたらオッケーなんじゃ？）"

# カズマ（Ｍ）
# display as カズマ
# （だが、どうやって合意であると証明する？\n　下手をすると悪魔の証明になりかねない。\n　ここはやはり上手いこと言いくるめるしか……）
489 = "（だが、どうやって合意であると証明する？\\n　下手をすると悪魔の証明になりかねない。\\n　ここはやはり上手いこと言いくるめるしか……）"

# クリス
# うーん、なかなか止まらないなぁ。\nごめんねカズマ。
354 = "うーん、なかなか止まらないなぁ。\\nごめんねカズマ。"

# カズマ
# あ、いや……。\n別にクリスのせいじゃないし。
321 = "あ、いや……。\\n別にクリスのせいじゃないし。"

# クリス
# でも、あたしが頼まなかったら、\n怪我しなかったでしょ。
391 = "でも、あたしが頼まなかったら、\\n怪我しなかったでしょ。"

# カズマ（Ｍ）
# display as カズマ
# （うっ、なんか微妙に罪悪感が。\n　クリスは純粋に俺のことを心配してくれて\n　いるんだよな）
479 = "（うっ、なんか微妙に罪悪感が。\\n　クリスは純粋に俺のことを心配してくれて\\n　いるんだよな）"

# カズマ（Ｍ）
# display as カズマ
# （決めた。やっぱり、止めよう）
500 = "（決めた。やっぱり、止めよう）"

# カズマ
# クリス、一回離れてくれ。
419 = "クリス、一回離れてくれ。"

# クリス
# ん、どうかした？
409 = "ん、どうかした？"

# カズマ
# 俺はこれから心を鬼にしてお前を説教するっ！
428 = "俺はこれから心を鬼にしてお前を説教するっ！"

# クリス
# は、はあ、お説教。
399 = "は、はあ、お説教。"

# カズマ
# 男の部屋、お互いにパジャマ姿、\nこんな状況で男の指はぺろぺろするな！
437 = "男の部屋、お互いにパジャマ姿、\\nこんな状況で男の指はぺろぺろするな！"

# クリス
# え？　え？　なんで？？
358 = "え？　え？　なんで？？"

# カズマ
# あれ、もしかして俺のこと好きなの？
341 = "あれ、もしかして俺のこと好きなの？"

# クリス
# ううん、それはないけど？
351 = "ううん、それはないけど？"

# カズマ
# だったらやめろ！\n気を持たせるとか、お前、俺、本当に……泣くぞ。
381 = "だったらやめろ！\\n気を持たせるとか、お前、俺、本当に……泣くぞ。"

# クリス
# 気を持たせる？\nん、ああーー、そういうこと。
436 = "気を持たせる？\\nん、ああーー、そういうこと。"

# クリス
# 確かにこれは、\nそう思われてもしょうがないかもね。
469 = "確かにこれは、\\nそう思われてもしょうがないかもね。"

# カズマ
# 気がつくのおせーよ！
435 = "気がつくのおせーよ！"

# クリス
# だってこんなのしょっちゅうだし。
382 = "だってこんなのしょっちゅうだし。"

# カズマ
# な、なんだと！
396 = "な、なんだと！"

# クリス
# あ、変な意味じゃないよ。
324 = "あ、変な意味じゃないよ。"

# クリス
# クエスト中にかすり傷程度の怪我では、\nいちいち応急セットを出してられないんだよ。
417 = "クエスト中にかすり傷程度の怪我では、\\nいちいち応急セットを出してられないんだよ。"

# クリス
# だから、そういう時は、\nぺろって舐めて止血しちゃうんだ。
378 = "だから、そういう時は、\\nぺろって舐めて止血しちゃうんだ。"

# カズマ
# いやでも、男にやるか、普通。
347 = "いやでも、男にやるか、普通。"

# クリス
# そういえば、女の子にしかやったことないかも。
372 = "そういえば、女の子にしかやったことないかも。"

# カズマ（Ｍ）
# display as カズマ
# （そ、そうなんだ。\n　って俺は何を安心してるんだよ！）
486 = "（そ、そうなんだ。\\n　って俺は何を安心してるんだよ！）"

# クリス
# あはは、これってカズマを男として見てないって\n意味なのかな。
334 = "あはは、これってカズマを男として見てないって\\n意味なのかな。"

# カズマ
# あー、もう、そういうオチはいらないからっ！
342 = "あー、もう、そういうオチはいらないからっ！"

# クリス
# あはは、ごめんごめん。
335 = "あはは、ごめんごめん。"

[selections]
432 = "指を抜こう！"
343 = "いや、しかし！"
473 = "駄目だ何も考えられない……"
