# rew_c04.txt.scn

[info]
230 = "rew_c04"

[characters]
326 = "カズマ"
329 = "ダクネス"
327 = "カズマ（Ｍ）"

[character_subs]
# 326 = "カズマ"

[script]
# lines: 93

# カズマ
# なぁダクネス、\n俺の願いをきいてくれるか？
300 = "なぁダクネス、\\n俺の願いをきいてくれるか？"

# ダクネス
# あ、ああ、私に出来ることだったら\n構わないが――
257 = "あ、ああ、私に出来ることだったら\\n構わないが――"

# ダクネス
# それほどに改まらなければいけないほど、\n切実な願いなのか？
282 = "それほどに改まらなければいけないほど、\\n切実な願いなのか？"

# カズマ
# 俺の今後の人生を左右すると考えて貰っても\nいいかもしれない！
335 = "俺の今後の人生を左右すると考えて貰っても\\nいいかもしれない！"

# ダクネス
# じ、人生を！？
274 = "じ、人生を！？"

# カズマ
# こんなことを頼めるのはお前だけなんだよ、\nダクネス。
269 = "こんなことを頼めるのはお前だけなんだよ、\\nダクネス。"

# カズマ
# だから、願いを聞き届けて欲しい！
285 = "だから、願いを聞き届けて欲しい！"

# ダクネス
# ちょっと待ってくれ。\nそんな重要なことをおいそれと返事できるか。
291 = "ちょっと待ってくれ。\\nそんな重要なことをおいそれと返事できるか。"

# ダクネス
# せめて内容を聞いてから決めさせてくれ。
276 = "せめて内容を聞いてから決めさせてくれ。"

# カズマ
# よし、わかった。\nでは、俺の願いを発表させていただきます！
317 = "よし、わかった。\\nでは、俺の願いを発表させていただきます！"

# ダクネス
# ご、ごくり。
270 = "ご、ごくり。"

# カズマ
# ダクネスさん、俺の奥さんになってください！
330 = "ダクネスさん、俺の奥さんになってください！"

# ダクネス
# は？
304 = "は？"

# カズマ
# これは俺へのご褒美なんだから、拒否権はないぞ。
268 = "これは俺へのご褒美なんだから、拒否権はないぞ。"

# ダクネス
# そ、それはわかっている。\nだが、いくらなんでも籍を入れろというのは……。
277 = "そ、それはわかっている。\\nだが、いくらなんでも籍を入れろというのは……。"

# カズマ
# って、ちっがーう！\n重く考えすぎだ！
292 = "って、ちっがーう！\\n重く考えすぎだ！"

# カズマ
# 俺は、奥さんっぽく振る舞って欲しいって\n意味で言ったんだよ。
336 = "俺は、奥さんっぽく振る舞って欲しいって\\n意味で言ったんだよ。"

# ダクネス
# だ、だったら、人生を左右するとか\n誤解を生むような言い方をするな！
284 = "だ、だったら、人生を左右するとか\\n誤解を生むような言い方をするな！"

# カズマ
# いや、そう言えばお前が面白い反応を見せてくれる\nかなって思って。
261 = "いや、そう言えばお前が面白い反応を見せてくれる\\nかなって思って。"

# ダクネス
# むぅ、言って良い冗談と悪い冗談があるのだぞ。
315 = "むぅ、言って良い冗談と悪い冗談があるのだぞ。"

# カズマ
# なんだよ、いつものお前なら……。
302 = "なんだよ、いつものお前なら……。"

# カズマ
# ふふふ、さすがカズマだな、\n女性が嫌がる事を心得ている、ハァハァ。
310 = "ふふふ、さすがカズマだな、\\n女性が嫌がる事を心得ている、ハァハァ。"

# カズマ
# とか言って、にやにやするくせに。
294 = "とか言って、にやにやするくせに。"

# ダクネス
# わ、私だって最低限の良識くらいは\n持ち合わせているつもりだ。
318 = "わ、私だって最低限の良識くらいは\\n持ち合わせているつもりだ。"

# カズマ
# へー。
312 = "へー。"

# ダクネス
# 信じてないな。
332 = "信じてないな。"

# カズマ
# だって普段のお前がお前だし。
286 = "だって普段のお前がお前だし。"

# ダクネス
# うぐっ！
262 = "うぐっ！"

# カズマ
# まあいいや、それで願いをきいてくれるのか？
314 = "まあいいや、それで願いをきいてくれるのか？"

# ダクネス
# ふりだったらまあ、やってみよう。
311 = "ふりだったらまあ、やってみよう。"

# カズマ
# サンキュー！\nじゃあ今、この瞬間から、\nダクネスは俺の奥さんって事で！
328 = "サンキュー！\\nじゃあ今、この瞬間から、\\nダクネスは俺の奥さんって事で！"

# ダクネス
# わかった。それで私は何をすれば良い。
320 = "わかった。それで私は何をすれば良い。"

# カズマ
# 新妻といったら、ふりふりのエプロンだろう。
343 = "新妻といったら、ふりふりのエプロンだろう。"

# ダクネス
# ふ、ふふ、さすがカズマだな。\nなるほど、そういう方向から攻めてきたか。
305 = "ふ、ふふ、さすがカズマだな。\\nなるほど、そういう方向から攻めてきたか。"

# カズマ
# おいおい、何を想像してるんだよ。
265 = "おいおい、何を想像してるんだよ。"

# ダクネス
# 夫の権力を振りかざして私の服を剥くつもり\nなんだろう！
341 = "夫の権力を振りかざして私の服を剥くつもり\\nなんだろう！"

# ダクネス
# さらに、素肌にエプロンをつけた卑猥な姿を\n晒させるなんて、どこまで鬼畜なんだカズマはぁ！
271 = "さらに、素肌にエプロンをつけた卑猥な姿を\\n晒させるなんて、どこまで鬼畜なんだカズマはぁ！"

# カズマ（Ｍ）
# display as カズマ
# （この妄想の飛躍は、ある意味尊敬できるな）
377 = "（この妄想の飛躍は、ある意味尊敬できるな）"

# ダクネス
# いくら拒否が許されぬ願いでも、\nさすがにそれは受け入れがたい。
258 = "いくら拒否が許されぬ願いでも、\\nさすがにそれは受け入れがたい。"

# ダクネス
# しかしっ、これは夫の命令！\nさらに世には知られたくない弱味を握られていて\n逆らえるわけないじゃないか！
273 = "しかしっ、これは夫の命令！\\nさらに世には知られたくない弱味を握られていて\\n逆らえるわけないじゃないか！"

# カズマ（Ｍ）
# display as カズマ
# （なんか新しい設定が追加されたぞ……）
379 = "（なんか新しい設定が追加されたぞ……）"

# ダクネス
# それが、ふりふりエプロンというやつなんだな！\nす、すぐに着替えてくるから待っていてくれ！
279 = "それが、ふりふりエプロンというやつなんだな！\\nす、すぐに着替えてくるから待っていてくれ！"

# カズマ（Ｍ）
# display as カズマ
# （水着は着るように言っておこう……）
382 = "（水着は着るように言っておこう……）"

# ダクネス
# ま、待たせたな。
313 = "ま、待たせたな。"

# カズマ
# おっ……うおぉぉぉぉっ！？
266 = "おっ……うおぉぉぉぉっ！？"

# ダクネス
# な、なんだ、いきなり変な声を出して。
298 = "な、なんだ、いきなり変な声を出して。"

# カズマ
# ふっ、ふおぉぉぉぉぉぉぉ！！
307 = "ふっ、ふおぉぉぉぉぉぉぉ！！"

# ダクネス
# 訳がわからないぞ！\nせめて人の言葉を喋ってくれ！
371 = "訳がわからないぞ！\\nせめて人の言葉を喋ってくれ！"

# カズマ（Ｍ）
# display as カズマ
# （こ、これは、予想以上の破壊力！！）
376 = "（こ、これは、予想以上の破壊力！！）"

# ダクネス
# な、なるほど、そういうことか。\nカズマは欲望に支配をされた獣という設定なのだな。
296 = "な、なるほど、そういうことか。\\nカズマは欲望に支配をされた獣という設定なのだな。"

# ダクネス
# ふふふ、お前の想像は、常に私の上を行く。
309 = "ふふふ、お前の想像は、常に私の上を行く。"

# カズマ
# それは俺の台詞だ！
281 = "それは俺の台詞だ！"

# ダクネス
# なんだ、違うのか？
301 = "なんだ、違うのか？"

# カズマ
# ちっがうよ！　そんなの俺求めてねーから！
289 = "ちっがうよ！　そんなの俺求めてねーから！"

# カズマ
# 俺は普通の人間で心優しい夫！\nお前は弱味なんて握られていないし、\n俺たちは普通に愛し合って結婚したの！
337 = "俺は普通の人間で心優しい夫！\\nお前は弱味なんて握られていないし、\\n俺たちは普通に愛し合って結婚したの！"

# ダクネス
# な、なるほど、わかった。
297 = "な、なるほど、わかった。"

# カズマ
# それじゃあ、これから俺が指示するから、\n新妻らしく演じてくれ。
280 = "それじゃあ、これから俺が指示するから、\\n新妻らしく演じてくれ。"

# ダクネス
# うむ、お手柔らかに頼むぞ。
263 = "うむ、お手柔らかに頼むぞ。"

# カズマ
# じゃあ、朝、優しく起こすシチュエーションを頼む。
275 = "じゃあ、朝、優しく起こすシチュエーションを頼む。"

# カズマ
# というわけで、さっそく始めてくれ。\nん～っ……むにゃむにゃむにゃ……。
293 = "というわけで、さっそく始めてくれ。\\nん～っ……むにゃむにゃむにゃ……。"

# ダクネス
# カ、カズマ、あ、朝だぞ？\nそ、そろそろ起きなくていいのか？
324 = "カ、カズマ、あ、朝だぞ？\\nそ、そろそろ起きなくていいのか？"

# カズマ
# ちがーう！　もっと甘やかすように！\nそれに、俺のことはアナタと呼んでくれ。\nそう呼ばないと、起きねーからな！
288 = "ちがーう！　もっと甘やかすように！\\nそれに、俺のことはアナタと呼んでくれ。\\nそう呼ばないと、起きねーからな！"

# ダクネス
# ア、アナタ、もう朝ですよ？\n早く起きないと、朝食が冷めてしまうわ。
323 = "ア、アナタ、もう朝ですよ？\\n早く起きないと、朝食が冷めてしまうわ。"

# カズマ
# んぅぅっ、あと５分、５分だけ……。
321 = "んぅぅっ、あと５分、５分だけ……。"

# ダクネス
# もうそんなことを言って、どうせ――
316 = "もうそんなことを言って、どうせ――"

# カズマ（Ｍ）
# display as カズマ
# （ん？）
381 = "（ん？）"

# ダクネス
# 私が一歩近づいた瞬間、\n強引にベッドに引きずり込むつもりなんだろう？
369 = "私が一歩近づいた瞬間、\\n強引にベッドに引きずり込むつもりなんだろう？"

# カズマ
# だー、そこで変な妄想を捗らせるな！
287 = "だー、そこで変な妄想を捗らせるな！"

# カズマ
# いってらっしゃいと見送る\nシチュエーションを頼む。
259 = "いってらっしゃいと見送る\\nシチュエーションを頼む。"

# ダクネス
# 見送る？　あ、ああ、わかった。
370 = "見送る？　あ、ああ、わかった。"

# カズマ
# おほん……じゃあ、俺仕事に行ってくるよ。
267 = "おほん……じゃあ、俺仕事に行ってくるよ。"

# ダクネス
# わかった、気をつけてな。\nあ、護衛として、私がついて行かなくていいのか？
319 = "わかった、気をつけてな。\\nあ、護衛として、私がついて行かなくていいのか？"

# カズマ
# 違う！　全然わかってない！
372 = "違う！　全然わかってない！"

# カズマ
# カズくんとは、まだ離れたくなーい！\nでもぉ、お仕事だから仕方ないよねっ。\nとか、イチャイチャするんだよ！
325 = "カズくんとは、まだ離れたくなーい！\\nでもぉ、お仕事だから仕方ないよねっ。\\nとか、イチャイチャするんだよ！"

# カズマ
# そしてほっぺにチューするの！
278 = "そしてほっぺにチューするの！"

# ダクネス
# え、え？
264 = "え、え？"

# カズマ
# それ違う！　お前が考えてるの絶対に違うから！
283 = "それ違う！　お前が考えてるの絶対に違うから！"

# カズマ
# 俺が言いたいのは小鳥みたいにつつくキスな！\nお前、もっとすげーの想像してただろ！
333 = "俺が言いたいのは小鳥みたいにつつくキスな！\\nお前、もっとすげーの想像してただろ！"

# ダクネス
# な、何を言っているんだ。\nそ、そんな想像なんて――
299 = "な、何を言っているんだ。\\nそ、そんな想像なんて――"

# ダクネス
# し、し、してないぞ。
272 = "し、し、してないぞ。"

# カズマ
# 顔に本音が出てるから！
375 = "顔に本音が出てるから！"

# カズマ
# 頬についたご飯粒を取ってもらうという\nシチュエーションで頼む。
373 = "頬についたご飯粒を取ってもらうという\\nシチュエーションで頼む。"

# ダクネス
# ん？　そんなんでいいのか？\nよっ、ほらっ、簡単じゃないか。
322 = "ん？　そんなんでいいのか？\\nよっ、ほらっ、簡単じゃないか。"

# カズマ
# 倦怠期か！
338 = "倦怠期か！"

# ダクネス
# は、はあ？
303 = "は、はあ？"

# カズマ
# 俺たちは新婚という設定だろ？\nそれなのに「よっ、ほら」は無いだろ！
334 = "俺たちは新婚という設定だろ？\\nそれなのに「よっ、ほら」は無いだろ！"

# ダクネス
# ふふ、なるほど、そういう事か。
308 = "ふふ、なるほど、そういう事か。"

# カズマ
# ……よし、何を考えてるのか言ってみろ。
256 = "……よし、何を考えてるのか言ってみろ。"

# ダクネス
# な、な、舐め取れと言いたいのだろう。
295 = "な、な、舐め取れと言いたいのだろう。"

# ダクネス
# ふ、ふふ、私を獣と蔑むとは、\n本当に容赦ないな、カズマは。
306 = "ふ、ふふ、私を獣と蔑むとは、\\n本当に容赦ないな、カズマは。"

# カズマ
# ちっがーう！\n変な方向に妄想を持っていくなよ！
290 = "ちっがーう！\\n変な方向に妄想を持っていくなよ！"

# カズマ（Ｍ）
# display as カズマ
# （はぁぁぁ、俺はただ、甘ったるい新婚生活を\n　味わってみたかっただけなのに……）
380 = "（はぁぁぁ、俺はただ、甘ったるい新婚生活を\\n　味わってみたかっただけなのに……）"

# カズマ（Ｍ）
# display as カズマ
# （どうしてこうなっちゃうかなぁ）
378 = "（どうしてこうなっちゃうかなぁ）"

[selections]
339 = "優しく起こすシチュエーションを頼む"
260 = "いってらっしゃいと見送るシチュエーションを頼む"
374 = "頬のご飯粒を取るシチュエーションを頼む"
