# rew_d04.txt.scn

[info]
244 = "rew_d04"

[characters]
339 = "カズマ"
344 = "クリス"
340 = "カズマ（Ｍ）"

[character_subs]
# 339 = "カズマ"

[script]
# lines: 102

# カズマ
# あー、なんだか今日はやけに暑いなー。\n汗かいちゃったなー。
275 = "あー、なんだか今日はやけに暑いなー。\\n汗かいちゃったなー。"

# クリス
# …………。
269 = "…………。"

# カズマ
# クリスも暑いと思わないか？\n思うよな？　な？
347 = "クリスも暑いと思わないか？\\n思うよな？　な？"

# クリス
# あー、もう、そういう回りくどいのはいいから。\n何をして欲しいのか、早く言いなよ。
276 = "あー、もう、そういう回りくどいのはいいから。\\n何をして欲しいのか、早く言いなよ。"

# カズマ
# じゃあ、単刀直入に。\n一緒にお風呂に入ってくれませんか？
296 = "じゃあ、単刀直入に。\\n一緒にお風呂に入ってくれませんか？"

# クリス
# はぁぁぁぁぁ！？
327 = "はぁぁぁぁぁ！？"

# カズマ
# というわけで、行こうか。
314 = "というわけで、行こうか。"

# クリス
# いやいやいや、無理だから、\nそんなの絶対に嫌だから！
278 = "いやいやいや、無理だから、\\nそんなの絶対に嫌だから！"

# カズマ
# ほほう、できないと？
332 = "ほほう、できないと？"

# クリス
# な、何？　ご褒美だからって理由で\n強要するつもりなの？
317 = "な、何？　ご褒美だからって理由で\\n強要するつもりなの？"

# カズマ
# あまり見くびらないで欲しいな。
274 = "あまり見くびらないで欲しいな。"

# カズマ
# 俺は人の権利を踏みにじるような\n不出来な人間じゃない！
353 = "俺は人の権利を踏みにじるような\\n不出来な人間じゃない！"

# クリス
# って、ちょっと、カズマ！？
311 = "って、ちょっと、カズマ！？"

# カズマ
# だから、土下座をさせていただきます。
304 = "だから、土下座をさせていただきます。"

# カズマ
# クリスさん、いえクリス様、どうか、なにとぞ\nこのカズマと一緒にお風呂に入ってください！
345 = "クリスさん、いえクリス様、どうか、なにとぞ\\nこのカズマと一緒にお風呂に入ってください！"

# クリス
# は、はは、無理強いをしなかったところは\n立派だと思うんだけど――
323 = "は、はは、無理強いをしなかったところは\\n立派だと思うんだけど――"

# クリス
# 男としては、地に落ちてるよね。
359 = "男としては、地に落ちてるよね。"

# カズマ
# それでも叶えたい夢なんだよ！
301 = "それでも叶えたい夢なんだよ！"

# クリス
# はぁ、わかったよ、そこまで頼まれたら\n断れないよね。
325 = "はぁ、わかったよ、そこまで頼まれたら\\n断れないよね。"

# カズマ
# じゃ、じゃあ！！
293 = "じゃ、じゃあ！！"

# クリス
# でーも、水着は着させて貰うからね。\nそれでいいなら、カズマのその滑稽な夢を叶えて\nあげる。
313 = "でーも、水着は着させて貰うからね。\\nそれでいいなら、カズマのその滑稽な夢を叶えて\\nあげる。"

# カズマ
# それで充分だ！　やっほー！
302 = "それで充分だ！　やっほー！"

# クリス
# はぁ、男って本当に訳わからないよ。
326 = "はぁ、男って本当に訳わからないよ。"

# クリス
# お、お待たせ。
288 = "お、お待たせ。"

# カズマ
# お、おお！！
287 = "お、おお！！"

# クリス
# ちょっと、こっちに来ないで！\nそれ以上近づいたら……。
310 = "ちょっと、こっちに来ないで！\\nそれ以上近づいたら……。"

# カズマ
# なんでダガー持ってるんだよ！
320 = "なんでダガー持ってるんだよ！"

# クリス
# 盗賊の嗜みってやつかな。
360 = "盗賊の嗜みってやつかな。"

# カズマ
# 別に触ったりしないっての。
354 = "別に触ったりしないっての。"

# クリス
# それで、どうして欲しいのさ。\nこれでも一緒にお風呂に入ってるって\n理屈は通るよ？
300 = "それで、どうして欲しいのさ。\\nこれでも一緒にお風呂に入ってるって\\n理屈は通るよ？"

# カズマ
# 確かにそうだけど屁理屈だろ。\nそんなことで納得できるか。
386 = "確かにそうだけど屁理屈だろ。\\nそんなことで納得できるか。"

# クリス
# だったら、何をして欲しいのか早く言って。\n水着を着てるけど、結構恥ずかしいんだからね。
307 = "だったら、何をして欲しいのか早く言って。\\n水着を着てるけど、結構恥ずかしいんだからね。"

# カズマ
# じゃあ、体を洗って貰おうかな。
295 = "じゃあ、体を洗って貰おうかな。"

# クリス
# へ？
331 = "へ？"

# カズマ
# というわけでお願いします！
315 = "というわけでお願いします！"

# クリス
# はぁ……触ったら怒るからね。
324 = "はぁ……触ったら怒るからね。"

# カズマ
# そんな勇気無いっての。
303 = "そんな勇気無いっての。"

# クリス
# ハ、ハハ、それを堂々と言っちゃうかな。
349 = "ハ、ハハ、それを堂々と言っちゃうかな。"

# クリス
# えっと、こんな感じ？　痛くないかな？
284 = "えっと、こんな感じ？　痛くないかな？"

# カズマ
# お、おう。
286 = "お、おう。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、生きてて良かった……。\n　この世界に来たことを後悔したこともあったけど\n　今はただ、この幸せに感謝するっ！）
389 = "（ああ、生きてて良かった……。\\n　この世界に来たことを後悔したこともあったけど\\n　今はただ、この幸せに感謝するっ！）"

# クリス
# しかし、綺麗な体してるね？
292 = "しかし、綺麗な体してるね？"

# カズマ
# そ、そうか？\nククク、クリスだって綺麗な体してるぞ。
297 = "そ、そうか？\\nククク、クリスだって綺麗な体してるぞ。"

# クリス
# はい、そういう目で見ない。
329 = "はい、そういう目で見ない。"

# クリス
# あと、今のは冒険者としてはどうかと思うよって\n意味だからね。
271 = "あと、今のは冒険者としてはどうかと思うよって\\n意味だからね。"

# カズマ（Ｍ）
# display as カズマ
# （くそぉ、勇気を振り絞って褒めたのに！）
393 = "（くそぉ、勇気を振り絞って褒めたのに！）"

# クリス
# ～～～～♪
403 = "～～～～♪"

# カズマ（Ｍ）
# display as カズマ
# （それにしてもクリスの態度、普通だな）
395 = "（それにしてもクリスの態度、普通だな）"

# カズマ（Ｍ）
# display as カズマ
# （水着は水着でいい眺めではあるんだが、\n　反応がいつも通りすぎていまいちつまらん）
402 = "（水着は水着でいい眺めではあるんだが、\\n　反応がいつも通りすぎていまいちつまらん）"

# カズマ（Ｍ）
# display as カズマ
# （普段から露出の高い服を着ているから\n　この程度じゃ気にならないのか？）
401 = "（普段から露出の高い服を着ているから\\n　この程度じゃ気にならないのか？）"

# カズマ（Ｍ）
# display as カズマ
# （せっかく２人きりなんだし\n　もう少し可愛い反応見せて欲しいものだが）
394 = "（せっかく２人きりなんだし\\n　もう少し可愛い反応見せて欲しいものだが）"

# カズマ（Ｍ）
# display as カズマ
# （何か、普段のクリスと違う一面を見る方法は\n　無いかな）
400 = "（何か、普段のクリスと違う一面を見る方法は\\n　無いかな）"

# カズマ
# まるで夫婦みたいだな。\nそうは思わないか？
335 = "まるで夫婦みたいだな。\\nそうは思わないか？"

# クリス
# キミとあたしが？\nあはは、ないない。
343 = "キミとあたしが？\\nあはは、ないない。"

# カズマ
# さらっと流すなよ！
290 = "さらっと流すなよ！"

# クリス
# いやぁ、だってキミ、誰にでもそういうこと\n言ってそうだし。
277 = "いやぁ、だってキミ、誰にでもそういうこと\\n言ってそうだし。"

# カズマ
# 俺、そんな勇気ないし！\nだいたい、誰でも口説くようなナンパな男じゃ\nないから！
352 = "俺、そんな勇気ないし！\\nだいたい、誰でも口説くようなナンパな男じゃ\\nないから！"

# クリス
# じゃあ、今の言葉……。\n本気って受け取っちゃってもいいのかな。
294 = "じゃあ、今の言葉……。\\n本気って受け取っちゃってもいいのかな。"

# カズマ（Ｍ）
# display as カズマ
# （え、何この反応！？　予想外なんですけど！！）
391 = "（え、何この反応！？　予想外なんですけど！！）"

# クリス
# カズマ？
341 = "カズマ？"

# カズマ
# え、えっと、い、いやその……。
283 = "え、えっと、い、いやその……。"

# クリス
# あはは、なーんてね。\nどう？　少しはいい夢を見られたでしょ？
272 = "あはは、なーんてね。\\nどう？　少しはいい夢を見られたでしょ？"

# カズマ
# なっ！？
318 = "なっ！？"

# クリス
# ほら、他も洗ってあげるからこっち向きなよ！
333 = "ほら、他も洗ってあげるからこっち向きなよ！"

# カズマ（Ｍ）
# display as カズマ
# （くそぉ、クリスの方が一枚上手だったか）
392 = "（くそぉ、クリスの方が一枚上手だったか）"

# カズマ
# もっと体を使って洗ってくれ！
338 = "もっと体を使って洗ってくれ！"

# クリス
# 何言ってるの？
351 = "何言ってるの？"

# カズマ
# クリスの洗い方には愛情がこもってない！\nもっとやさし～く、恋人に接するようにしてくれ。
346 = "クリスの洗い方には愛情がこもってない！\\nもっとやさし～く、恋人に接するようにしてくれ。"

# クリス
# どうしてそんな風にしないといけないのさ。
316 = "どうしてそんな風にしないといけないのさ。"

# カズマ
# だーかーらっ、俺はラブラブな雰囲気を\n堪能したいの！
309 = "だーかーらっ、俺はラブラブな雰囲気を\\n堪能したいの！"

# カズマ
# それが俺が求めるご褒美の本質！\n体を綺麗にするだけなら自分でできるわ！
299 = "それが俺が求めるご褒美の本質！\\n体を綺麗にするだけなら自分でできるわ！"

# クリス
# そういうの、あたしには不向きだと思うよ？\nキャラじゃないしね。
298 = "そういうの、あたしには不向きだと思うよ？\\nキャラじゃないしね。"

# カズマ
# だからいいんだよ。\n俺はクリスの新しい一面も見てみたいんだ！
305 = "だからいいんだよ。\\n俺はクリスの新しい一面も見てみたいんだ！"

# クリス
# ラブラブ……ラブラブねぇ。
350 = "ラブラブ……ラブラブねぇ。"

# クリス
# ねえ、かゆいところ……ないかな？
321 = "ねえ、かゆいところ……ないかな？"

# カズマ（Ｍ）
# display as カズマ
# （ぬっは！？）
398 = "（ぬっは！？）"

# クリス
# カズマ？　どうしたの？
342 = "カズマ？　どうしたの？"

# カズマ
# ななな、無いわー！
319 = "ななな、無いわー！"

# クリス
# は、はい？
322 = "は、はい？"

# カズマ
# 無い無い、まったく無い！\nごめん、やっぱり普通のクリスが一番だわ！
358 = "無い無い、まったく無い！\\nごめん、やっぱり普通のクリスが一番だわ！"

# クリス
# くぅぅ、羞恥を捨てて必死にやったのにっ！
289 = "くぅぅ、羞恥を捨てて必死にやったのにっ！"

# カズマ（Ｍ）
# display as カズマ
# （あっぶなっ！\n　マジで心を盗まれるところだった！）
390 = "（あっぶなっ！\\n　マジで心を盗まれるところだった！）"

# カズマ（Ｍ）
# display as カズマ
# （ゲスに頼めば……）
399 = "（ゲスに頼めば……）"

# カズマ
# うひひひひひ、もっと洗いたいところが\nあるんじゃないのかい？
280 = "うひひひひひ、もっと洗いたいところが\\nあるんじゃないのかい？"

# クリス
# えっ？
285 = "えっ？"

# カズマ（Ｍ）
# display as カズマ
# （あ、これ絶対に違う選択肢だったわ）
388 = "（あ、これ絶対に違う選択肢だったわ）"

# クリス
# もう一回言って見て。
336 = "もう一回言って見て。"

# カズマ
# え、ええと。\nごめんなさい、調子に乗りました。
282 = "え、ええと。\\nごめんなさい、調子に乗りました。"

# クリス
# 謝って許されることと許されないことが\nあると思うんだけどー？
387 = "謝って許されることと許されないことが\\nあると思うんだけどー？"

# カズマ
# うぅ、だってクリス普通なんだもん！\n俺はラブラブな雰囲気を楽しみたかったのにさ！
279 = "うぅ、だってクリス普通なんだもん！\\n俺はラブラブな雰囲気を楽しみたかったのにさ！"

# クリス
# あはは、わかってるよ。\nいくらキミでも、そんなゲスなことは\n言わないってね。
273 = "あはは、わかってるよ。\\nいくらキミでも、そんなゲスなことは\\n言わないってね。"

# カズマ（Ｍ）
# display as カズマ
# （な！？）
397 = "（な！？）"

# クリス
# でーも、今のは冗談でもちょっとＮＧかな。\n不快に思ったのは事実だしね。
312 = "でーも、今のは冗談でもちょっとＮＧかな。\\n不快に思ったのは事実だしね。"

# カズマ
# はい、すみませんでした。
328 = "はい、すみませんでした。"

# クリス
# さーて、こんなもんかな？\n洗い残しはないよね。
291 = "さーて、こんなもんかな？\\n洗い残しはないよね。"

# カズマ
# あ、ああ。
270 = "あ、ああ。"

# クリス
# ふうう、ちょっと体が冷えちゃった。\nどうする？　一緒に湯船に浸かる？
330 = "ふうう、ちょっと体が冷えちゃった。\\nどうする？　一緒に湯船に浸かる？"

# カズマ
# え、いいのか？
281 = "え、いいのか？"

# クリス
# 変なことはしないでしょ。\nこれでもキミのこと、信じてるんだからね。
356 = "変なことはしないでしょ。\\nこれでもキミのこと、信じてるんだからね。"

# カズマ
# だったらダガーは置いてきてくれよ。
308 = "だったらダガーは置いてきてくれよ。"

# クリス
# だからこれは、盗賊の嗜み。\nそれ以上でもそれ以下でもないよ。
306 = "だからこれは、盗賊の嗜み。\\nそれ以上でもそれ以下でもないよ。"

# カズマ（Ｍ）
# display as カズマ
# （どうだか……）
396 = "（どうだか……）"

[selections]
334 = "まるで夫婦みたいだな"
337 = "もっと体を使って洗ってくれ"
348 = "ゲスに頼んでみるか"
