# root_f12.txt.scn

[info]
0 = ""

[characters]
185 = "カズマ（Ｍ）"
184 = "カズマ"
182 = "ウィズ"
181 = "アクア"

[character_subs]
# 184 = "カズマ"

[script]
# lines: 38

# カズマ（Ｍ）
# display as カズマ
# （子どもたちと別れた後、俺たちは場所を移して、\n　色んな人に声を掛けてみたんだが……）
216 = "（子どもたちと別れた後、俺たちは場所を移して、\\n　色んな人に声を掛けてみたんだが……）"

# カズマ
# けっこう困ってることや愚痴ってのがあるんだな。
165 = "けっこう困ってることや愚痴ってのがあるんだな。"

# ウィズ
# ええ、平和そうに見えても、\n大なり小なり、何かしら\n問題を抱えてるものなんですね。
161 = "ええ、平和そうに見えても、\\n大なり小なり、何かしら\\n問題を抱えてるものなんですね。"

# カズマ
# ま、大体はどうでもいい話だったけど。\nそれに、ウィズの商売に\n繋がりそうな話も無かったしなぁ。
178 = "ま、大体はどうでもいい話だったけど。\\nそれに、ウィズの商売に\\n繋がりそうな話も無かったしなぁ。"

# ウィズ
# それは仕方ありませんよ。\n冒険者でもないのに、マジックアイテムが\n要り用になるような話はそうないでしょうから。
169 = "それは仕方ありませんよ。\\n冒険者でもないのに、マジックアイテムが\\n要り用になるような話はそうないでしょうから。"

# ウィズ
# ただ、別の意味で気になる話が出てきましたね。
170 = "ただ、別の意味で気になる話が出てきましたね。"

# ウィズ
# 悪霊騒ぎの訴えをこんなにたくさん\n聞かされるとは思いませんでした。
194 = "悪霊騒ぎの訴えをこんなにたくさん\\n聞かされるとは思いませんでした。"

# カズマ（Ｍ）
# display as カズマ
# （そう、噂レベルから本当に見たって話まで\n　かなりの人の口から幽霊とかお化けって単語が\n　出てきたんだよな）
212 = "（そう、噂レベルから本当に見たって話まで\\n　かなりの人の口から幽霊とかお化けって単語が\\n　出てきたんだよな）"

# ウィズ
# お店に来た依頼の数どころじゃありません。\n何が起きてるんでしょう？
164 = "お店に来た依頼の数どころじゃありません。\\n何が起きてるんでしょう？"

# カズマ
# そういやウィズは昨夜、除霊に行ったのか？
168 = "そういやウィズは昨夜、除霊に行ったのか？"

# ウィズ
# ええ。\n依頼にあった通り、\nいくつかの霊がいたので浄化しました。
163 = "ええ。\\n依頼にあった通り、\\nいくつかの霊がいたので浄化しました。"

# ウィズ
# でもまさか、あの場所以外でも\nこんなに発生しているなんて……。
173 = "でもまさか、あの場所以外でも\\nこんなに発生しているなんて……。"

# カズマ
# もしかして、さっき\n子供たちが言っていた家鳴りも\n悪霊の仕業だったりするのか？
179 = "もしかして、さっき\\n子供たちが言っていた家鳴りも\\n悪霊の仕業だったりするのか？"

# ウィズ
# 十分ありえますね。\nただ話を聞いた限り、幸い人に影響を\n及ぼすレベルの悪霊では無いようです。
191 = "十分ありえますね。\\nただ話を聞いた限り、幸い人に影響を\\n及ぼすレベルの悪霊では無いようです。"

# カズマ
# でも、家の中にまで入ってきている霊が\nいるってことだよな？
171 = "でも、家の中にまで入ってきている霊が\\nいるってことだよな？"

# ウィズ
# もしそれが強い悪霊だったら、\n大変なことになりかねません。
180 = "もしそれが強い悪霊だったら、\\n大変なことになりかねません。"

# カズマ
# しかしなんだってそんな急に、\n悪霊騒ぎが起こり始めたんだ。
166 = "しかしなんだってそんな急に、\\n悪霊騒ぎが起こり始めたんだ。"

# カズマ
# 前にアクアが墓地に張った結界は\nもう無いはずだから、それが原因じゃないよな？
190 = "前にアクアが墓地に張った結界は\\nもう無いはずだから、それが原因じゃないよな？"

# ウィズ
# はい、そうですね。
176 = "はい、そうですね。"

# カズマ
# 他に原因になりそうな心当たりはあるか？
188 = "他に原因になりそうな心当たりはあるか？"

# ウィズ
# ありません。\nただ、霊ですから、当然\n人が亡くならなければ発生しません。
158 = "ありません。\\nただ、霊ですから、当然\\n人が亡くならなければ発生しません。"

# ウィズ
# どこかで、大勢の人が亡くなったのかしら？\nこの近辺で大規模な戦いがあったとか。
175 = "どこかで、大勢の人が亡くなったのかしら？\\nこの近辺で大規模な戦いがあったとか。"

# カズマ
# でもさ、そんな大規模な戦いがあったなんて話は\nまったく聞かないよな？
172 = "でもさ、そんな大規模な戦いがあったなんて話は\\nまったく聞かないよな？"

# ウィズ
# ええ、街の中もいつも通りですし……\nもし魔王軍が動くような事があれば、\n一応、私のところにも話は来るはずです。
162 = "ええ、街の中もいつも通りですし……\\nもし魔王軍が動くような事があれば、\\n一応、私のところにも話は来るはずです。"

# カズマ
# ああ、まあそうだよな。
157 = "ああ、まあそうだよな。"

# カズマ（Ｍ）
# display as カズマ
# （ついうっかり忘れるけど、\n　ウィズって魔王軍の幹部だもんな。\n　そりゃ、来るよな）
213 = "（ついうっかり忘れるけど、\\n　ウィズって魔王軍の幹部だもんな。\\n　そりゃ、来るよな）"

# ウィズ
# となると……\nこの街に元々いた霊が、何かのきっかけで\n騒ぎ始めたのかもしれません。
174 = "となると……\\nこの街に元々いた霊が、何かのきっかけで\\n騒ぎ始めたのかもしれません。"

# カズマ
# 元々いた霊？\nそんなにいるもんなのか？
189 = "元々いた霊？\\nそんなにいるもんなのか？"

# ウィズ
# 霊はどこにでもいますから。\nそれに人が多いところには\n引き寄せられてくるんです。
211 = "霊はどこにでもいますから。\\nそれに人が多いところには\\n引き寄せられてくるんです。"

# ウィズ
# 普通に死んだ人の霊なら、\n例え浄化されず留まっていても\n何もしない、無害なものは多いんですよ。
195 = "普通に死んだ人の霊なら、\\n例え浄化されず留まっていても\\n何もしない、無害なものは多いんですよ。"

# カズマ（Ｍ）
# display as カズマ
# （へえ、そういうもんなのか。\n　幽霊がすべて悪霊ってわけじゃないんだな）
214 = "（へえ、そういうもんなのか。\\n　幽霊がすべて悪霊ってわけじゃないんだな）"

# ウィズ
# ほら、悪霊騒ぎの話自体は多いけれど、\n実際の被害は、それほど聞きませんでしたよね？
177 = "ほら、悪霊騒ぎの話自体は多いけれど、\\n実際の被害は、それほど聞きませんでしたよね？"

# カズマ
# あー、言われてみれば確かに。
159 = "あー、言われてみれば確かに。"

# ウィズ
# そういう、大人しい無害な霊が\n騒ぎ始めるようなきっかけがあったんでしょう。\nそれがなんなのかまでは、わかりませんが。
167 = "そういう、大人しい無害な霊が\\n騒ぎ始めるようなきっかけがあったんでしょう。\\nそれがなんなのかまでは、わかりませんが。"

# カズマ
# ウィズでもわからないのか。
183 = "ウィズでもわからないのか。"

# ウィズ
# ええ……。\nでも、なんのきっかけもなく騒ぎ出すなんて\nまず有り得ないんです。
160 = "ええ……。\\nでも、なんのきっかけもなく騒ぎ出すなんて\\nまず有り得ないんです。"

# アクア
# カーズマー！！
186 = "カーズマー！！"

# カズマ（Ｍ）
# display as カズマ
# （ん？　アクア？）
215 = "（ん？　アクア？）"

