# root_c08.txt.scn

[info]
0 = ""

[characters]
229 = "カズマ"
232 = "カズマ（Ｍ）"
233 = "ダクネス"
227 = "アクア"
223 = "めぐみん"

[character_subs]
# 229 = "カズマ"

[script]
# lines: 53

# カズマ
# ただいま。
216 = "ただいま。"

# カズマ（Ｍ）
# display as カズマ
# （気分転換に出かけたはずが、\n　なんか微妙な散歩になっちまったなぁ）
289 = "（気分転換に出かけたはずが、\\n　なんか微妙な散歩になっちまったなぁ）"

# ダクネス
# ん？　どうかしたのか、浮かない顔をして。
226 = "ん？　どうかしたのか、浮かない顔をして。"

# カズマ
# いや、別に。
201 = "いや、別に。"

# ダクネス
# そうか？
211 = "そうか？"

# カズマ（Ｍ）
# display as カズマ
# （本人の前で微妙な散歩なんて\n　言えるわけないだろ）
288 = "（本人の前で微妙な散歩なんて\\n　言えるわけないだろ）"

# ダクネス
# ああ、そうだ！\nカズマ、よかったら――
196 = "ああ、そうだ！\\nカズマ、よかったら――"

# アクア
# 遅かったわね！
277 = "遅かったわね！"

# カズマ
# おわっ！？
207 = "おわっ！？"

# めぐみん
# お帰りなさい。\n散歩は楽しめましたか？
208 = "お帰りなさい。\\n散歩は楽しめましたか？"

# カズマ
# なんで散歩に出かけたって知ってるんだ！
220 = "なんで散歩に出かけたって知ってるんだ！"

# アクア
# そんなこと、どうでもいいじゃない。
213 = "そんなこと、どうでもいいじゃない。"

# カズマ
# いやいや、よくねえだろ。
202 = "いやいや、よくねえだろ。"

# めぐみん
# 小さいことばかり気にする男はモテませんよ。
239 = "小さいことばかり気にする男はモテませんよ。"

# カズマ
# 愛も恋も知らない１３歳児に\nそんな説教されたくねえわ。
243 = "愛も恋も知らない１３歳児に\\nそんな説教されたくねえわ。"

# めぐみん
# ほほお、まるで恋愛について知っているような\n口振りですね。
222 = "ほほお、まるで恋愛について知っているような\\n口振りですね。"

# カズマ
# ふふ、この俺に攻略できなかったキャラクターは\n無し！
221 = "ふふ、この俺に攻略できなかったキャラクターは\\n無し！"

# カズマ
# 嫁も１人や２人じゃないぞ！\nそれはもう作品ごとに――
238 = "嫁も１人や２人じゃないぞ！\\nそれはもう作品ごとに――"

# アクア
# 虚しくならないのあんた。
274 = "虚しくならないのあんた。"

# カズマ
# うっさい……うっさい……。
204 = "うっさい……うっさい……。"

# めぐみん
# よくわかりませんが、カズマに用はありません。\nダクネスだけ来てください。
225 = "よくわかりませんが、カズマに用はありません。\\nダクネスだけ来てください。"

# ダクネス
# えっ？\nしかし私は……。
206 = "えっ？\\nしかし私は……。"

# アクア
# いいから、いいから。
198 = "いいから、いいから。"

# ダクネス
# な、なんなんだいったい。
218 = "な、なんなんだいったい。"

# めぐみん
# カズマは、居間に入ってきてはダメですからね。
231 = "カズマは、居間に入ってきてはダメですからね。"

# アクア
# もちろんあんたの大好きな\n盗み聞きも覗き見も禁止よ。
224 = "もちろんあんたの大好きな\\n盗み聞きも覗き見も禁止よ。"

# カズマ
# そんなもん好きじゃねーよ！
215 = "そんなもん好きじゃねーよ！"

# カズマ（Ｍ）
# display as カズマ
# （なんなんだよ！\n　俺だってこの屋敷の住人なのに\n　閉め出しやがって！）
284 = "（なんなんだよ！\\n　俺だってこの屋敷の住人なのに\\n　閉め出しやがって！）"

# カズマ（Ｍ）
# display as カズマ
# （くっそー、ホントに何を企んでやがるんだ？\n　こうなったら、大好きな盗み聞きしてやる！）
280 = "（くっそー、ホントに何を企んでやがるんだ？\\n　こうなったら、大好きな盗み聞きしてやる！）"

# カズマ
# …………。
195 = "…………。"

# アクア
# それで、どうだったの？
212 = "それで、どうだったの？"

# めぐみん
# いい感じにできましたか？
199 = "いい感じにできましたか？"

# ダクネス
# う、うむ……。\n自分なりに、上手くやったつもりなんだが。
203 = "う、うむ……。\\n自分なりに、上手くやったつもりなんだが。"

# カズマ（Ｍ）
# display as カズマ
# （やっぱり。\n　ダクネスが俺についてきたのは\n　何か裏があったんだな）
287 = "（やっぱり。\\n　ダクネスが俺についてきたのは\\n　何か裏があったんだな）"

# カズマ（Ｍ）
# display as カズマ
# （でも、目的はなんだ？\n　もう少し聞いてみないとわからないな）
283 = "（でも、目的はなんだ？\\n　もう少し聞いてみないとわからないな）"

# ダクネス
# しかし、私から言い出しておいてなんだが、\nこういうことは不慣れで――
209 = "しかし、私から言い出しておいてなんだが、\\nこういうことは不慣れで――"

# ダクネス
# 途中から、どうしたらいいか\nわからなくなってしまった。
276 = "途中から、どうしたらいいか\\nわからなくなってしまった。"

# アクア
# そんなの勢いでいいのよ。\n男なんて単純なんだから。
214 = "そんなの勢いでいいのよ。\\n男なんて単純なんだから。"

# めぐみん
# カズマには、ちょっと強引なぐらい\n押して行くのがちょうどいいと思います。
230 = "カズマには、ちょっと強引なぐらい\\n押して行くのがちょうどいいと思います。"

# ダクネス
# そういうものなのか？\nしかし、強引に仕掛けて引かれでもしたら。
210 = "そういうものなのか？\\nしかし、強引に仕掛けて引かれでもしたら。"

# ダクネス
# いや、それはそれでいいかもしれないな……。
200 = "いや、それはそれでいいかもしれないな……。"

# アクア
# あのカズマが\n女の子に積極的にされて引くわけないでしょ？
197 = "あのカズマが\\n女の子に積極的にされて引くわけないでしょ？"

# めぐみん
# ええ、カズマは実にわかりやすいですからね。
205 = "ええ、カズマは実にわかりやすいですからね。"

# アクア
# だから、ダクネスも覚悟を決めて\nもっとアタックしなきゃダメよ。
217 = "だから、ダクネスも覚悟を決めて\\nもっとアタックしなきゃダメよ。"

# めぐみん
# 当たって砕けろの精神です。
242 = "当たって砕けろの精神です。"

# ダクネス
# なるほど。\n自らもっとぶつかっていくんだな？
219 = "なるほど。\\n自らもっとぶつかっていくんだな？"

# めぐみん
# 言っておきますが、物理的にじゃないですよ？\nダクネスのほうが防御力が高いので、\nカズマが倒れてしまいますからね？
275 = "言っておきますが、物理的にじゃないですよ？\\nダクネスのほうが防御力が高いので、\\nカズマが倒れてしまいますからね？"

# カズマ（Ｍ）
# display as カズマ
# （おいおい……。\n　ちょっと待て、なんだこの会話は）
279 = "（おいおい……。\\n　ちょっと待て、なんだこの会話は）"

# カズマ（Ｍ）
# display as カズマ
# （まるで……\n　気になる男の子にアタックしちゃいなよ？\n　って感じじゃねえか？）
286 = "（まるで……\\n　気になる男の子にアタックしちゃいなよ？\\n　って感じじゃねえか？）"

# カズマ（Ｍ）
# display as カズマ
# （はっ！　まさか、ダクネスは俺に！？）
285 = "（はっ！　まさか、ダクネスは俺に！？）"

# カズマ（Ｍ）
# display as カズマ
# （いやいや、待て、待つんだ俺。\n　そう思うにはまだ早い。\n　勘違いだったら、大恥をかくのはこっちだぞ！）
278 = "（いやいや、待て、待つんだ俺。\\n　そう思うにはまだ早い。\\n　勘違いだったら、大恥をかくのはこっちだぞ！）"

# カズマ（Ｍ）
# display as カズマ
# （そんな勘違いをしたなんて知れ渡ってみろ！\n　もう恥ずかしくて\n　この世界で生きていけなくなる！！）
281 = "（そんな勘違いをしたなんて知れ渡ってみろ！\\n　もう恥ずかしくて\\n　この世界で生きていけなくなる！！）"

# カズマ（Ｍ）
# display as カズマ
# （ちょっと部屋で頭を冷やそう！\n　うん、それがいい！　そうしよう！）
282 = "（ちょっと部屋で頭を冷やそう！\\n　うん、それがいい！　そうしよう！）"

