# root_e09.txt.scn

[info]
0 = ""

[characters]
292 = "カズマ"
287 = "めぐみん"
288 = "ゆんゆん"
294 = "カズマ（Ｍ）"

[character_subs]
# 292 = "カズマ"

[script]
# lines: 55

# カズマ
# なあ、街から大分離れたし、\nここら辺でいいんじゃないか？
279 = "なあ、街から大分離れたし、\\nここら辺でいいんじゃないか？"

# めぐみん
# そうですね。\nおあつらえ向きに大きな岩もあることですし、\nそうしましょう。
273 = "そうですね。\\nおあつらえ向きに大きな岩もあることですし、\\nそうしましょう。"

# めぐみん
# では、ゆんゆん。\n瞬きなどせずしかと見ていなさい。\n私の偉大さを今見せつけてあげますよ！
276 = "では、ゆんゆん。\\n瞬きなどせずしかと見ていなさい。\\n私の偉大さを今見せつけてあげますよ！"

# ゆんゆん
# う、うん。
262 = "う、うん。"

# めぐみん
# エクスプローーーージョンッ！
291 = "エクスプローーーージョンッ！"

# ゆんゆん
# す、凄い……！\n以前よりも威力上がってない？
269 = "す、凄い……！\\n以前よりも威力上がってない？"

# めぐみん
# ふふふ、当然だ。\n我の爆裂魔法は、幾多の経験を積み重ね\n更なる高みへと昇華されているのだ。
284 = "ふふふ、当然だ。\\n我の爆裂魔法は、幾多の経験を積み重ね\\n更なる高みへと昇華されているのだ。"

# めぐみん
# いずれは天を裂き、海を干上がらせ、\n神をも凌駕する力を得ることであろう。
259 = "いずれは天を裂き、海を干上がらせ、\\n神をも凌駕する力を得ることであろう。"

# ゆんゆん
# ……格好付けるのはいいけど、\n倒れて言っても締まらないよ？
250 = "……格好付けるのはいいけど、\\n倒れて言っても締まらないよ？"

# めぐみん
# 己の全てを賭け必殺の一撃を放つ！\n爆裂魔法の素晴らしき開放感の前では、\n取るに足りない問題！
307 = "己の全てを賭け必殺の一撃を放つ！\\n爆裂魔法の素晴らしき開放感の前では、\\n取るに足りない問題！"

# ゆんゆん
# すごく大きな問題だと思うけど……。
270 = "すごく大きな問題だと思うけど……。"

# めぐみん
# ……では、おんぶをお願いします。
248 = "……では、おんぶをお願いします。"

# カズマ
# はいはい、よいしょっと。
281 = "はいはい、よいしょっと。"

# ゆんゆん
# あっ……。
256 = "あっ……。"

# カズマ
# ん？　どうかしたか？
290 = "ん？　どうかしたか？"

# ゆんゆん
# い、いいえ！\nあの、その、カズマさんが\n当然のように背負うんだなって……。
257 = "い、いいえ！\\nあの、その、カズマさんが\\n当然のように背負うんだなって……。"

# カズマ
# ああ、いつものことだしな。\nさっさと回収するにこしたことはないよ。
253 = "ああ、いつものことだしな。\\nさっさと回収するにこしたことはないよ。"

# ゆんゆん
# いつも……こんなことを\nカズマさんにさせているんですか。
261 = "いつも……こんなことを\\nカズマさんにさせているんですか。"

# カズマ
# ああ、ほぼ毎日。\nおかげでずいぶん体力もついたよ。
255 = "ああ、ほぼ毎日。\\nおかげでずいぶん体力もついたよ。"

# ゆんゆん
# ……ねえ、めぐみん？\nカズマさんに迷惑をかけて\n悪いって思わないの？
249 = "……ねえ、めぐみん？\\nカズマさんに迷惑をかけて\\n悪いって思わないの？"

# めぐみん
# 思いませんね。\n我が爆裂魔法の更なる進化のためには\n必要なことです。
308 = "思いませんね。\\n我が爆裂魔法の更なる進化のためには\\n必要なことです。"

# めぐみん
# カズマも、口には出しませんが\n私の役に立てて内心喜んでいるはずです。\n最強への手助けをしていると！
293 = "カズマも、口には出しませんが\\n私の役に立てて内心喜んでいるはずです。\\n最強への手助けをしていると！"

# カズマ（Ｍ）
# display as カズマ
# （……無駄にポジティブな思考だな）
331 = "（……無駄にポジティブな思考だな）"

# めぐみん
# それに、お互いを支え合うのが仲間というもの。\nいちいち申し訳なく思うような\n他人行儀な仲ではないのですよ！
274 = "それに、お互いを支え合うのが仲間というもの。\\nいちいち申し訳なく思うような\\n他人行儀な仲ではないのですよ！"

# カズマ（Ｍ）
# display as カズマ
# （いや、少しは申し訳なく思えよ！）
332 = "（いや、少しは申し訳なく思えよ！）"

# ゆんゆん
# お互い支え合う仲間……か。
265 = "お互い支え合う仲間……か。"

# カズマ
# とにかくやることもやったし、\nとっとと帰ろうぜ――
277 = "とにかくやることもやったし、\\nとっとと帰ろうぜ――"

# カズマ
# って、うおっ！？\nジャイアントトード！？
275 = "って、うおっ！？\\nジャイアントトード！？"

# めぐみん
# いつの間に！？\nカズマ、早く逃げるのです！\nでないとまた食べられてぬるぬるにされます！！
260 = "いつの間に！？\\nカズマ、早く逃げるのです！\\nでないとまた食べられてぬるぬるにされます！！"

# カズマ
# よし、じゃあ下ろすぞ！
289 = "よし、じゃあ下ろすぞ！"

# めぐみん
# 何を言ってるんですか！\n私はまだ動けないんですよ！
300 = "何を言ってるんですか！\\n私はまだ動けないんですよ！"

# カズマ
# お前が餌……じゃなくて囮になれ！\nその間に俺がなんとかする。
266 = "お前が餌……じゃなくて囮になれ！\\nその間に俺がなんとかする。"

# めぐみん
# 今、餌って言いましたよね、餌って！\n聞き逃しませんでしたよ！
299 = "今、餌って言いましたよね、餌って！\\n聞き逃しませんでしたよ！"

# カズマ
# ぐあ、こらっ、離れろ！
268 = "ぐあ、こらっ、離れろ！"

# めぐみん
# 離れません！　こうなったらカズマにも\nジャイアントトードのぬくさを堪能して貰います。
329 = "離れません！　こうなったらカズマにも\\nジャイアントトードのぬくさを堪能して貰います。"

# カズマ
# うおおお、来てる来てる、蛙が来てるって！
263 = "うおおお、来てる来てる、蛙が来てるって！"

# めぐみん
# ふふ、死なば諸共ですよ、カズマ。
283 = "ふふ、死なば諸共ですよ、カズマ。"

# カズマ
# ぎゃああああああああああ！！
267 = "ぎゃああああああああああ！！"

# ゆんゆん
# 私に任せてください！
328 = "私に任せてください！"

# ゆんゆん
# ライト・オブ・セイバー！
297 = "ライト・オブ・セイバー！"

# カズマ
# お、おお、ゆんゆん！
264 = "お、おお、ゆんゆん！"

# ゆんゆん
# ふう。\n大丈夫ですか？　怪我はありませんか？
282 = "ふう。\\n大丈夫ですか？　怪我はありませんか？"

# カズマ
# ああ、おかげさまでかすり傷もないよ。\nサンキュー、ゆんゆん。
254 = "ああ、おかげさまでかすり傷もないよ。\\nサンキュー、ゆんゆん。"

# ゆんゆん
# いえ、お役に立てて良かったです。
258 = "いえ、お役に立てて良かったです。"

# カズマ
# 本当、ゆんゆんがいてくれて助かったよ。\nじゃなきゃ今頃、胃袋の中だ。\nやっぱり魔法使いはこうでなきゃな！
309 = "本当、ゆんゆんがいてくれて助かったよ。\\nじゃなきゃ今頃、胃袋の中だ。\\nやっぱり魔法使いはこうでなきゃな！"

# ゆんゆん
# そ、そんな。\nえへへ。
272 = "そ、そんな。\\nえへへ。"

# めぐみん
# カズマ？\n私も魔法使いなのですが？
295 = "カズマ？\\n私も魔法使いなのですが？"

# カズマ
# 魔力が空っぽの魔法使いなんてただの人だろ。\n何を抜かしてやがりますかねぇ？
330 = "魔力が空っぽの魔法使いなんてただの人だろ。\\n何を抜かしてやがりますかねぇ？"

# カズマ
# まったく、ただの人を\n背負って帰らなきゃならない\n俺の身にもなってくれよなぁ。
285 = "まったく、ただの人を\\n背負って帰らなきゃならない\\n俺の身にもなってくれよなぁ。"

# めぐみん
# むう……。
286 = "むう……。"

# ゆんゆん
# あ、あの、めぐみん？\n私が背負ってあげようか？
251 = "あ、あの、めぐみん？\\n私が背負ってあげようか？"

# カズマ
# ああ、いいっていいって！\nこいつって結構重いからさ。
252 = "ああ、いいっていいって！\\nこいつって結構重いからさ。"

# ゆんゆん
# そ、そうですか？\nそれじゃ……。
271 = "そ、そうですか？\\nそれじゃ……。"

# カズマ
# どっこいせっと！\nそんじゃ、帰ろうぜ。
278 = "どっこいせっと！\\nそんじゃ、帰ろうぜ。"

# めぐみん
# はい……。
280 = "はい……。"

