# root_e15.txt.scn

[info]
0 = ""

[characters]
271 = "ゆんゆん"
269 = "めぐみん"
275 = "カズマ"
274 = "ウィズ"
278 = "クリス"
279 = "ダクネス"
277 = "カズマ（Ｍ）"
273 = "アクア"

[character_subs]
# 275 = "カズマ"

[script]
# lines: 55

# ゆんゆん
# お、美味しい美味しい\n揚げたてのコロッケです……。
243 = "お、美味しい美味しい\\n揚げたてのコロッケです……。"

# ゆんゆん
# 今晩の食卓に是非どうですか？\n本当に美味しくて……ほっぺた落ちちゃいますよ。
282 = "今晩の食卓に是非どうですか？\\n本当に美味しくて……ほっぺた落ちちゃいますよ。"

# ゆんゆん
# お、お、お願いしますぅ～。\nこれが売れないと困るんです！\nた、助けてくださいぃ～！
241 = "お、お、お願いしますぅ～。\\nこれが売れないと困るんです！\\nた、助けてくださいぃ～！"

# めぐみん
# お客に泣きつくとは、なんとも情けない。\n紅魔族としての誇りはないのですか？
244 = "お客に泣きつくとは、なんとも情けない。\\n紅魔族としての誇りはないのですか？"

# めぐみん
# そんな同情心を煽るような姑息な手段で\n売れるなら誰も苦労はしませんよ。
255 = "そんな同情心を煽るような姑息な手段で\\n売れるなら誰も苦労はしませんよ。"

# ゆんゆん
# なら、どうやって売るって言うのよ！？
266 = "なら、どうやって売るって言うのよ！？"

# めぐみん
# 決まっています。\n買いたくなるポイントを\n全面に押し出しアピールするのです！
289 = "決まっています。\\n買いたくなるポイントを\\n全面に押し出しアピールするのです！"

# めぐみん
# さあさあ、道行く皆様方、ご注目あれ！\nこのまま通り過ぎるは愚の骨頂！\n一生を棒に振るに等しい所行！
251 = "さあさあ、道行く皆様方、ご注目あれ！\\nこのまま通り過ぎるは愚の骨頂！\\n一生を棒に振るに等しい所行！"

# めぐみん
# ほんの数分私の言葉に耳を傾けるだけで、\n人生は開け明るい未来は\n約束されたも同然！
268 = "ほんの数分私の言葉に耳を傾けるだけで、\\n人生は開け明るい未来は\\n約束されたも同然！"

# めぐみん
# 騙されたと思って\nしばしの時間お付き合いください。\nけして後悔はさせません！
314 = "騙されたと思って\\nしばしの時間お付き合いください。\\nけして後悔はさせません！"

# めぐみん
# では改めて名乗らせて頂きましょう！
260 = "では改めて名乗らせて頂きましょう！"

# めぐみん
# 我が名はめぐみん！\nアークウイザードを生業とし、\n最強の爆裂魔法を操る者！
287 = "我が名はめぐみん！\\nアークウイザードを生業とし、\\n最強の爆裂魔法を操る者！"

# めぐみん
# そして今は、アクセル随一の売り子！\nコロッケを売らせたら右に出る者なしと\n言われし者！
253 = "そして今は、アクセル随一の売り子！\\nコロッケを売らせたら右に出る者なしと\\n言われし者！"

# めぐみん
# そんな私がお勧めするコロッケが、\nただのコロッケのはずがない！\nこれこそ究極の一品！
257 = "そんな私がお勧めするコロッケが、\\nただのコロッケのはずがない！\\nこれこそ究極の一品！"

# めぐみん
# 甘味が出るまで丁寧に\n炒められたタマネギと挽肉。
291 = "甘味が出るまで丁寧に\\n炒められたタマネギと挽肉。"

# めぐみん
# ホクホクのジャガイモとの\n組み合わせは言うまでもなく最強！
280 = "ホクホクのジャガイモとの\\n組み合わせは言うまでもなく最強！"

# めぐみん
# 新鮮な卵を繋ぎに使いカラッと\n揚げることにより、\nサクサクの食感を生み出しています！
288 = "新鮮な卵を繋ぎに使いカラッと\\n揚げることにより、\\nサクサクの食感を生み出しています！"

# ゆんゆん
# 私だって、負けてないんだから！
311 = "私だって、負けてないんだから！"

# ゆんゆん
# わ、我が名はゆんゆん！\nアークウィザードにして上級魔法を操る者！\nやがては紅魔族の長になる者！
272 = "わ、我が名はゆんゆん！\\nアークウィザードにして上級魔法を操る者！\\nやがては紅魔族の長になる者！"

# ゆんゆん
# これさえ食べれば肉体は喜び、\n全身に魔力が巡り、体力気力共に充実！
247 = "これさえ食べれば肉体は喜び、\\n全身に魔力が巡り、体力気力共に充実！"

# ゆんゆん
# さあ、早い者勝ちですよ！
250 = "さあ、早い者勝ちですよ！"

# カズマ
# ――とまあ、勝負開始からの３０分ですが、\n２人の戦いはいかがでしょう？
234 = "――とまあ、勝負開始からの３０分ですが、\\n２人の戦いはいかがでしょう？"

# ウィズ
# と、とても頑張っていると思いますよ？
263 = "と、とても頑張っていると思いますよ？"

# クリス
# いやいや……。\nこういう売り子って\n頑張ればいいってものじゃないからね？
237 = "いやいや……。\\nこういう売り子って\\n頑張ればいいってものじゃないからね？"

# クリス
# ほら、見てみなよ。\nゆんゆんは必死すぎて、\nお客さんが引いちゃってるもん。
267 = "ほら、見てみなよ。\\nゆんゆんは必死すぎて、\\nお客さんが引いちゃってるもん。"

# クリス
# 関わりたくないオーラが半端ないよね。\nあ、また目をそらされた。
313 = "関わりたくないオーラが半端ないよね。\\nあ、また目をそらされた。"

# カズマ
# 見た目は申し分ないのになぁ。
312 = "見た目は申し分ないのになぁ。"

# クリス
# 可愛い女の子がお願いをするのは\n効果的だけど、あそこまで必死だと逆に怖いよ。
283 = "可愛い女の子がお願いをするのは\\n効果的だけど、あそこまで必死だと逆に怖いよ。"

# ダクネス
# つまり、ゆんゆんは素材の良さを\n活かせていないということか。\n実に惜しいな。
258 = "つまり、ゆんゆんは素材の良さを\\n活かせていないということか。\\n実に惜しいな。"

# クリス
# ……そのセリフ、\nそのままダクネスにプレゼントしてあげたいよ。
236 = "……そのセリフ、\\nそのままダクネスにプレゼントしてあげたいよ。"

# カズマ
# で、めぐみんの方はどうだ？
259 = "で、めぐみんの方はどうだ？"

# ウィズ
# 声もハッキリしてますし、\nちゃんとコロッケのアピールも\nできているのではないでしょうか？
285 = "声もハッキリしてますし、\\nちゃんとコロッケのアピールも\\nできているのではないでしょうか？"

# ダクネス
# 確かに、自信に満ちた声出しだな。
310 = "確かに、自信に満ちた声出しだな。"

# クリス
# でもアピールにはなってないでしょ？\nだってあれ、普通にコロッケの作り方を\n話してるだけだし。
262 = "でもアピールにはなってないでしょ？\\nだってあれ、普通にコロッケの作り方を\\n話してるだけだし。"

# クリス
# どこのジャガイモを使ってる、とか、\nここにこだわっています、っていう\nポイントが１つもない。
265 = "どこのジャガイモを使ってる、とか、\\nここにこだわっています、っていう\\nポイントが１つもない。"

# クリス
# ずば抜けて安いならいざ知れず\nそうじゃないなら主婦は足を止めないよね。
252 = "ずば抜けて安いならいざ知れず\\nそうじゃないなら主婦は足を止めないよね。"

# カズマ（Ｍ）
# display as カズマ
# （……クリス、妙に堂に入った解説をしてるな。\n　ひょっとして経験者なのか？）
316 = "（……クリス、妙に堂に入った解説をしてるな。\\n　ひょっとして経験者なのか？）"

# クリス
# でも、それ以上の\nどうしようもない致命的な問題があるよ。
261 = "でも、それ以上の\\nどうしようもない致命的な問題があるよ。"

# ウィズ
# それは？
254 = "それは？"

# クリス
# この街でのめぐみんのイメージ。\n街の人達って、めぐみんのことを\n名前と頭のおかしな子だって思ってるでしょ？
246 = "この街でのめぐみんのイメージ。\\n街の人達って、めぐみんのことを\\n名前と頭のおかしな子だって思ってるでしょ？"

# クリス
# そんな子が売っている物なんて\n怖くて買えないんじゃないかな？
256 = "そんな子が売っている物なんて\\n怖くて買えないんじゃないかな？"

# カズマ（Ｍ）
# display as カズマ
# （……ものすごい正論だ）
315 = "（……ものすごい正論だ）"

# ダクネス
# うーむ、確かに。\nゆんゆんは地味に売ってはいるが、\nめぐみんの周りには誰も寄りつかないな。
239 = "うーむ、確かに。\\nゆんゆんは地味に売ってはいるが、\\nめぐみんの周りには誰も寄りつかないな。"

# クリス
# これまでしてきた数々のことを考えれば、\nこうなっても仕方ないかな。
249 = "これまでしてきた数々のことを考えれば、\\nこうなっても仕方ないかな。"

# カズマ（Ｍ）
# display as カズマ
# （つまり勝敗は決まっていたわけか。\n　まあ、自業自得だな……）
317 = "（つまり勝敗は決まっていたわけか。\\n　まあ、自業自得だな……）"

# カズマ
# とういうわけで！\nコロッケ早売り勝負は、ゆんゆんの勝利！
264 = "とういうわけで！\\nコロッケ早売り勝負は、ゆんゆんの勝利！"

# ゆんゆん
# やったー！
270 = "やったー！"

# めぐみん
# くっ……！\nこんなはずでは……。
245 = "くっ……！\\nこんなはずでは……。"

# アクア
# これで、私の苦労が少しはわかったでしょう？\nなかなか売れないのよね。
248 = "これで、私の苦労が少しはわかったでしょう？\\nなかなか売れないのよね。"

# カズマ
# ……おいアクア。\nお前、まさか、自分が引き受けたバイトを\n２人にやらせたんじゃないだろうな？
235 = "……おいアクア。\\nお前、まさか、自分が引き受けたバイトを\\n２人にやらせたんじゃないだろうな？"

# アクア
# え～？　な、なんのことかしら？
240 = "え～？　な、なんのことかしら？"

# カズマ（Ｍ）
# display as カズマ
# （図星か！　こいつは本当に……！）
318 = "（図星か！　こいつは本当に……！）"

# めぐみん
# カズマ！\nそれより次の勝負はなんですか？\n次は絶対に勝ちますよ！
276 = "カズマ！\\nそれより次の勝負はなんですか？\\n次は絶対に勝ちますよ！"

# カズマ
# お、おう。\nじゃあ、ダクネス、頼むわ。
242 = "お、おう。\\nじゃあ、ダクネス、頼むわ。"

# ダクネス
# うむ、次は私の考えた勝負に挑んでもらう。\n早速だが、場所を移そう。
238 = "うむ、次は私の考えた勝負に挑んでもらう。\\n早速だが、場所を移そう。"

