# root_b08.txt.scn

[info]
0 = ""

[characters]
217 = "カズマ"
213 = "めぐみん"
218 = "カズマ（Ｍ）"

[character_subs]
# 217 = "カズマ"

[script]
# lines: 44

# カズマ
# しかし、本当にどこもかしこも\n掃除が行き届いてるな。
199 = "しかし、本当にどこもかしこも\\n掃除が行き届いてるな。"

# めぐみん
# これを見るだけで、どれだけエリス様が\n愛されているかわかりますね。
198 = "これを見るだけで、どれだけエリス様が\\n愛されているかわかりますね。"

# カズマ
# だが、これだけエリス様のために\n一生懸命つくしていた信者達も呪いで――
203 = "だが、これだけエリス様のために\\n一生懸命つくしていた信者達も呪いで――"

# めぐみん
# もう、なんなんですか、\nさっきからそんな事ばかり言って。\nそろそろ本気で怒りますよ。
214 = "もう、なんなんですか、\\nさっきからそんな事ばかり言って。\\nそろそろ本気で怒りますよ。"

# カズマ
# いやー、ビビってるめぐみん面白いなって\n思ってさ。
194 = "いやー、ビビってるめぐみん面白いなって\\n思ってさ。"

# めぐみん
# は？　我が恐れているだと？\n笑止！　恐怖とは無知から発生するもの、\nゆえに我はそのような感情とは無縁なり。
209 = "は？　我が恐れているだと？\\n笑止！　恐怖とは無知から発生するもの、\\nゆえに我はそのような感情とは無縁なり。"

# カズマ
# あっ、めぐみんの後ろに誰か居る！
191 = "あっ、めぐみんの後ろに誰か居る！"

# めぐみん
# ひゃああああああああああああ！
210 = "ひゃああああああああああああ！"

# カズマ
# 怖がってるじゃねえか！
226 = "怖がってるじゃねえか！"

# めぐみん
# もう、もうもう！\nカズマなんて嫌いです！
215 = "もう、もうもう！\\nカズマなんて嫌いです！"

# カズマ
# おーい、１人で行動するのは危ないと思うぞ？
197 = "おーい、１人で行動するのは危ないと思うぞ？"

# めぐみん
# な、なんです、怖いんですか？　仕方ないですね。\n私が側に居てあげますよ。
207 = "な、なんです、怖いんですか？　仕方ないですね。\\n私が側に居てあげますよ。"

# カズマ
# いや、その強がりはちっとも意味無いから。
193 = "いや、その強がりはちっとも意味無いから。"

# めぐみん
# う、うるさいですよ。\nそろそろ黙ってください。
195 = "う、うるさいですよ。\\nそろそろ黙ってください。"

# カズマ
# …………。
186 = "…………。"

# めぐみん
# 黙らないでくださいよ！　怖いじゃないですか！
251 = "黙らないでくださいよ！　怖いじゃないですか！"

# カズマ
# どうしろと？
206 = "どうしろと？"

# めぐみん
# 黙りつつ喋ってください。
252 = "黙りつつ喋ってください。"

# カズマ（Ｍ）
# display as カズマ
# （なんて無茶ぶり！）
253 = "（なんて無茶ぶり！）"

# めぐみん
# しかし、誰がなんのために教会に呪いなんて\nかけたんでしょうね。
200 = "しかし、誰がなんのために教会に呪いなんて\\nかけたんでしょうね。"

# めぐみん
# それに、結婚式を挙げれば解ける呪いって、\nちょっと想像したくない心残りですよ。
201 = "それに、結婚式を挙げれば解ける呪いって、\\nちょっと想像したくない心残りですよ。"

# カズマ
# ま、結婚式当日に浮気が発覚したとか、\n結婚式を挙げる直前に事故にでもあっちまったとか、\nその類いだろうな。
212 = "ま、結婚式当日に浮気が発覚したとか、\\n結婚式を挙げる直前に事故にでもあっちまったとか、\\nその類いだろうな。"

# めぐみん
# 想像もしたくないと言っているのに、\nぺらぺらと……。
227 = "想像もしたくないと言っているのに、\\nぺらぺらと……。"

# カズマ
# あ、結婚式を何者かに\nめちゃくちゃにされたってのもありそうだな。
189 = "あ、結婚式を何者かに\\nめちゃくちゃにされたってのもありそうだな。"

# めぐみん
# ですが、今カズマが言った理由だと、\nどれも矛盾が生まれます。
205 = "ですが、今カズマが言った理由だと、\\nどれも矛盾が生まれます。"

# カズマ
# 矛盾？
249 = "矛盾？"

# めぐみん
# だって、呪いは教会にかけられているのでしょう？
204 = "だって、呪いは教会にかけられているのでしょう？"

# めぐみん
# 浮気であれ、不幸な事故であれ、\n教会は無関係の筈です。
228 = "浮気であれ、不幸な事故であれ、\\n教会は無関係の筈です。"

# カズマ（Ｍ）
# display as カズマ
# （確かにそれもそうか）
254 = "（確かにそれもそうか）"

# カズマ
# いかん、俺も腹が減ってきた。
192 = "いかん、俺も腹が減ってきた。"

# めぐみん
# あ、あの、それでしたら……。
187 = "あ、あの、それでしたら……。"

# カズマ
# あ、そうだ。\n教会だし、お供え物があってもおかしくないよな？
188 = "あ、そうだ。\\n教会だし、お供え物があってもおかしくないよな？"

# カズマ
# エリス様へ捧げられたものだけど、\nちょっと食べさせてもらおうぜ。\n緊急事態だから許してもらえるだろ。
216 = "エリス様へ捧げられたものだけど、\\nちょっと食べさせてもらおうぜ。\\n緊急事態だから許してもらえるだろ。"

# カズマ
# 贅沢は言わないから、\nせめてパンのひと欠けでもないかな？
250 = "贅沢は言わないから、\\nせめてパンのひと欠けでもないかな？"

# めぐみん
# …………。
# 186 = "…………。"

# カズマ
# おーい、めぐみん？\nボーッとしてないで探すのを手伝ってくれよ。
196 = "おーい、めぐみん？\\nボーッとしてないで探すのを手伝ってくれよ。"

# めぐみん
# ボーッとしているわけでは……ないです。
221 = "ボーッとしているわけでは……ないです。"

# カズマ
# トイレに行きたいなら、\n我慢しないで行った方がいいぞ？
220 = "トイレに行きたいなら、\\n我慢しないで行った方がいいぞ？"

# めぐみん
# トイレじゃないです！
219 = "トイレじゃないです！"

# カズマ
# ああ、もしかして１人で行くのが怖いのか。
190 = "ああ、もしかして１人で行くのが怖いのか。"

# めぐみん
# だから違いますよ！\nしつこいですね！
202 = "だから違いますよ！\\nしつこいですね！"

# カズマ
# ならいいけど、無理して我慢するなよ？\n体に良くないぜ？
208 = "ならいいけど、無理して我慢するなよ？\\n体に良くないぜ？"

# めぐみん
# 余計なお世話です！
222 = "余計なお世話です！"

# カズマ
# へいへい。\nじゃ、もう少し奥の方を探してみるか。
211 = "へいへい。\\nじゃ、もう少し奥の方を探してみるか。"

