# root_a19.txt.scn

[info]
0 = ""

[characters]
295 = "カズマ（Ｍ）"
285 = "めぐみん"
293 = "カズマ"
296 = "ダクネス"
300 = "ルナ"
313 = "審査員長"
289 = "アクア"
312 = "審査員"

[character_subs]
# 293 = "カズマ"

[script]
# lines: 74

# カズマ（Ｍ）
# display as カズマ
# （そしてコンテストは滞りなく進み、\n　アクアも猫を被ったまま全ての出番を終えた）
365 = "（そしてコンテストは滞りなく進み、\\n　アクアも猫を被ったまま全ての出番を終えた）"

# めぐみん
# うう、結果発表ですよ、カズマ。
255 = "うう、結果発表ですよ、カズマ。"

# カズマ
# わ、わかってるよ！
288 = "わ、わかってるよ！"

# ダクネス
# 自分のことのようにドキドキするな。
359 = "自分のことのようにドキドキするな。"

# ルナ
# それでは、お待たせ致しました。\n優勝者の発表です。
273 = "それでは、お待たせ致しました。\\n優勝者の発表です。"

# ダクネス
# き、きたぞ！\nみんな、心の準備はいいか？
264 = "き、きたぞ！\\nみんな、心の準備はいいか？"

# ルナ
# 『あなたこそ女神エリス様コンテスト』\nの優勝者は……！
245 = "『あなたこそ女神エリス様コンテスト』\\nの優勝者は……！"

# ルナ
# エントリーナンバー１７番、アクアさんです！
292 = "エントリーナンバー１７番、アクアさんです！"

# めぐみん
# おお！？
263 = "おお！？"

# ダクネス
# やった、やったぞ、カズマ！！
287 = "やった、やったぞ、カズマ！！"

# ルナ
# アクアさん！\nどうぞ、前に！
291 = "アクアさん！\\nどうぞ、前に！"

# カズマ
# うおおおおっ！？\nあ、あいつ、マジでやりやがった！！
256 = "うおおおおっ！？\\nあ、あいつ、マジでやりやがった！！"

# ダクネス
# ああ、やってしまったな。\nすごいじゃないか。
247 = "ああ、やってしまったな。\\nすごいじゃないか。"

# めぐみん
# ホントです。\nまさかのまさかでしたが。
299 = "ホントです。\\nまさかのまさかでしたが。"

# カズマ
# 俺達もそれなりに自信持って送り出しはしたが、\n他の参加者のレベルも高かったよな？
304 = "俺達もそれなりに自信持って送り出しはしたが、\\n他の参加者のレベルも高かったよな？"

# ダクネス
# ああ。\nエリス教徒たるもの、やるからには\n本気を出さねば信心が疑われるからな。
248 = "ああ。\\nエリス教徒たるもの、やるからには\\n本気を出さねば信心が疑われるからな。"

# ダクネス
# 動機こそ不純ではあったが、\nどれだけエリス様に近付けて――
307 = "動機こそ不純ではあったが、\\nどれだけエリス様に近付けて――"

# ダクネス
# 信仰心を示せるかという意味では\n有意義なコンテストだったのかもしれない。
303 = "信仰心を示せるかという意味では\\n有意義なコンテストだったのかもしれない。"

# カズマ（Ｍ）
# display as カズマ
# （確かに、出てくる参加者みんな、\n　そのままモデルかアイドルデビューしても\n　おかしくないくらいのレベルだった）
372 = "（確かに、出てくる参加者みんな、\\n　そのままモデルかアイドルデビューしても\\n　おかしくないくらいのレベルだった）"

# カズマ（Ｍ）
# display as カズマ
# （エリス教の女性信者って、\n　あんなに美人揃いだったのか……）
369 = "（エリス教の女性信者って、\\n　あんなに美人揃いだったのか……）"

# めぐみん
# カズマ、鼻の下が伸びてますよ？\n公衆の面前で妙な妄想はやめてくれませんか？
294 = "カズマ、鼻の下が伸びてますよ？\\n公衆の面前で妙な妄想はやめてくれませんか？"

# カズマ
# 妙な妄想って決めつけてんじゃねーよ！
310 = "妙な妄想って決めつけてんじゃねーよ！"

# カズマ（Ｍ）
# display as カズマ
# （にしても、アクアのやつ、\n　あの中でよく優勝できたもんだなぁ。\n　ちょっと見直してやるか）
366 = "（にしても、アクアのやつ、\\n　あの中でよく優勝できたもんだなぁ。\\n　ちょっと見直してやるか）"

# ルナ
# では、順位発表も終わりましたところで、\n改めて審査員長より、総評を頂きたいと思います。
275 = "では、順位発表も終わりましたところで、\\n改めて審査員長より、総評を頂きたいと思います。"

# 審査員長
# えー、お集まりの皆様。\n今回、初めてこのような形でコンテストを\n開きましたが……。
260 = "えー、お集まりの皆様。\\n今回、初めてこのような形でコンテストを\\n開きましたが……。"

# 審査員長
# 蓋を開けてみれば、\nかなりレベルの高いものとなりました。
360 = "蓋を開けてみれば、\\nかなりレベルの高いものとなりました。"

# 審査員長
# 最後まで選考に残った上位５名の方は、\n平均点が軒並み９０点以上。
316 = "最後まで選考に残った上位５名の方は、\\n平均点が軒並み９０点以上。"

# 審査員長
# その中でも、アクアさんは\n審査項目すべてにおいて、\nその平均点を上回りました。
272 = "その中でも、アクアさんは\\n審査項目すべてにおいて、\\nその平均点を上回りました。"

# 審査員長
# そのエリス様に近付かんとする努力、\nそして敬虔な信心に、改めて敬意を表します。
271 = "そのエリス様に近付かんとする努力、\\nそして敬虔な信心に、改めて敬意を表します。"

# カズマ（Ｍ）
# display as カズマ
# （ごめんなさい、審査員長。\n　そんな立派な理由じゃないんだ……）
363 = "（ごめんなさい、審査員長。\\n　そんな立派な理由じゃないんだ……）"

# カズマ（Ｍ）
# display as カズマ
# （ああして褒められると、なんか逆に\n　申し訳ない気分になってくるな）
361 = "（ああして褒められると、なんか逆に\\n　申し訳ない気分になってくるな）"

# ルナ
# 審査員長、ありがとうございました。\nさあ、それでは優勝致しましたアクアさんへの\nインタビューに入りたいと思います。
314 = "審査員長、ありがとうございました。\\nさあ、それでは優勝致しましたアクアさんへの\\nインタビューに入りたいと思います。"

# ルナ
# アクアさん、おめでとうございます！\n今の心境を一言、お願いします。
290 = "アクアさん、おめでとうございます！\\n今の心境を一言、お願いします。"

# アクア
# そうですね。\nまさか、私などが優勝できるとは\n夢にも思っておりませんでしたわ。
269 = "そうですね。\\nまさか、私などが優勝できるとは\\n夢にも思っておりませんでしたわ。"

# ルナ
# 実に謙虚な言葉ですね。\nしかし、こうして見事に優勝です。
311 = "実に謙虚な言葉ですね。\\nしかし、こうして見事に優勝です。"

# アクア
# とても嬉しく思います。\nありがとうございます。
278 = "とても嬉しく思います。\\nありがとうございます。"

# カズマ（Ｍ）
# display as カズマ
# （ギルドのお姉さんが若干頬を引き攣らせてるのは、\n　普段のアクアを知ってるからだろうな）
370 = "（ギルドのお姉さんが若干頬を引き攣らせてるのは、\\n　普段のアクアを知ってるからだろうな）"

# ルナ
# 優勝のために、なにか頑張ったことはありますか？
305 = "優勝のために、なにか頑張ったことはありますか？"

# アクア
# そうですね。\nひどい特訓……。
268 = "そうですね。\\nひどい特訓……。"

# アクア
# いえ、ひとえに女神様のご加護が\nあったものと信じております。
253 = "いえ、ひとえに女神様のご加護が\\nあったものと信じております。"

# ルナ
# いや、本当にエリス様と\n見紛うような印象を受けますね。\n審査員長、いかがですか？
254 = "いや、本当にエリス様と\\n見紛うような印象を受けますね。\\n審査員長、いかがですか？"

# 審査員長
# ええ、アクアさんは\n所作や雰囲気、品格といったところで\n最高点を叩き出していますからね。
259 = "ええ、アクアさんは\\n所作や雰囲気、品格といったところで\\n最高点を叩き出していますからね。"

# 審査員
# そうですね。\nただその中で、目と髪の色が青なところだけが\n惜しかったとの声もありました。
267 = "そうですね。\\nただその中で、目と髪の色が青なところだけが\\n惜しかったとの声もありました。"

# 審査員長
# そこまでエリス様と同じであれば、\nまさにこの地に降臨したエリス様の化身とも……。
270 = "そこまでエリス様と同じであれば、\\nまさにこの地に降臨したエリス様の化身とも……。"

# アクア
# ふふふ。
283 = "ふふふ。"

# カズマ（Ｍ）
# display as カズマ
# （ん？）
367 = "（ん？）"

# めぐみん
# なんだか様子がおかしいですね。
280 = "なんだか様子がおかしいですね。"

# ダクネス
# あれはアクアが何かをたくらんでるときの顔だな。
250 = "あれはアクアが何かをたくらんでるときの顔だな。"

# カズマ
# おい待て、何をやらかすつもりだ。
262 = "おい待て、何をやらかすつもりだ。"

# アクア
# ふふふ、うふふふ、\n勝利の花鳥風月♪
282 = "ふふふ、うふふふ、\\n勝利の花鳥風月♪"

# ルナ
# え？　え？
261 = "え？　え？"

# アクア
# あー、もう、肩こった。\nやっぱりこういうのって私に合わないわね。
251 = "あー、もう、肩こった。\\nやっぱりこういうのって私に合わないわね。"

# カズマ
# うが、あいつ地を出しやがった！
257 = "うが、あいつ地を出しやがった！"

# めぐみん
# どうしてこのタイミングで！？
279 = "どうしてこのタイミングで！？"

# カズマ
# 知るか！\n俺が聞きたいわ！
357 = "知るか！\\n俺が聞きたいわ！"

# アクア
# あっ、ちょっとマイクをいいかしら。
249 = "あっ、ちょっとマイクをいいかしら。"

# ルナ
# は、はい、どうぞ。
281 = "は、はい、どうぞ。"

# アクア
# あーあー、こほん。\nこの度は、エリスのコンテストに\nお越しいただきましてありがとうございました。
252 = "あーあー、こほん。\\nこの度は、エリスのコンテストに\\nお越しいただきましてありがとうございました。"

# アクア
# でも、ごめんなさいね。\n私はエリス信者じゃないの。
276 = "でも、ごめんなさいね。\\n私はエリス信者じゃないの。"

# カズマ
# ぶっちゃけたー！！
284 = "ぶっちゃけたー！！"

# アクア
# じゃあ、私が何者かですって？\nふふふ、知りたい？　知りたいのかしら？
266 = "じゃあ、私が何者かですって？\\nふふふ、知りたい？　知りたいのかしら？"

# カズマ（Ｍ）
# display as カズマ
# （あいつまさか……）
362 = "（あいつまさか……）"

# アクア
# 私はアクア！\nそうアクシズ教団の崇めるご神体\n女神アクアよ！
358 = "私はアクア！\\nそうアクシズ教団の崇めるご神体\\n女神アクアよ！"

# アクア
# というわけで、エリス教もいいけど、\nアクシズ教もよろしくお願いします。
277 = "というわけで、エリス教もいいけど、\\nアクシズ教もよろしくお願いします。"

# カズマ（Ｍ）
# display as カズマ
# （そういえば、あいつ、コンテストに出るって\n　決めたとき、何かをたくらんでる風だったな）
364 = "（そういえば、あいつ、コンテストに出るって\\n　決めたとき、何かをたくらんでる風だったな）"

# カズマ（Ｍ）
# display as カズマ
# （最初からこの場でアクシズ教の\n　宣伝をするつもりだったのか……）
371 = "（最初からこの場でアクシズ教の\\n　宣伝をするつもりだったのか……）"

# めぐみん
# これってどうなるんですか？\nアクアの優勝が取り消されてしまうのでは？
265 = "これってどうなるんですか？\\nアクアの優勝が取り消されてしまうのでは？"

# ダクネス
# 信仰する神が違うからと\n結果を覆したりしたら、それこそエリス教の\n名に傷がつくことになる。
302 = "信仰する神が違うからと\\n結果を覆したりしたら、それこそエリス教の\\n名に傷がつくことになる。"

# カズマ（Ｍ）
# display as カズマ
# （アクアはそれを見越していた？\n　いやいや、ただのノリでやっただけだろうな）
368 = "（アクアはそれを見越していた？\\n　いやいや、ただのノリでやっただけだろうな）"

# めぐみん
# では、カズマ、帰りますか。
274 = "では、カズマ、帰りますか。"

# ダクネス
# 夕飯の買い出しも必要だしな。
309 = "夕飯の買い出しも必要だしな。"

# カズマ
# うん、帰ろう帰ろう。
258 = "うん、帰ろう帰ろう。"

# アクア
# あ、そうだ。\n今、アクシズ教に入信すると、\n素敵な特典がありまして。
246 = "あ、そうだ。\\n今、アクシズ教に入信すると、\\n素敵な特典がありまして。"

# カズマ
# もう、なるようになれ！
286 = "もう、なるようになれ！"

