# root_f14.txt.scn

[info]
0 = ""

[characters]
137 = "カズマ"
136 = "ウィズ"
138 = "カズマ（Ｍ）"

[character_subs]
# 137 = "カズマ"

[script]
# lines: 18

# カズマ
# 出歩いた割には結局、ウィズの商売に\n繋がりそうなヒントは見つからなかったな。\nわざわざ付き合わせたのに、ごめん。
139 = "出歩いた割には結局、ウィズの商売に\\n繋がりそうなヒントは見つからなかったな。\\nわざわざ付き合わせたのに、ごめん。"

# ウィズ
# そんな、謝らないでください。\n子どもたちと遊べて楽しかったですし。
128 = "そんな、謝らないでください。\\n子どもたちと遊べて楽しかったですし。"

# ウィズ
# それに、カズマさんと一緒に過ごせて\n嬉しかったです。
127 = "それに、カズマさんと一緒に過ごせて\\n嬉しかったです。"

# カズマ
# お、おう。
123 = "お、おう。"

# カズマ（Ｍ）
# display as カズマ
# （その笑顔でそのセリフは反則だろ）
158 = "（その笑顔でそのセリフは反則だろ）"

# ウィズ
# どうかしましたか？\n顔が赤いですよ？
129 = "どうかしましたか？\\n顔が赤いですよ？"

# ウィズ
# もしかして熱があるかもしれません。\nおでこをちょっと失礼しますね。
132 = "もしかして熱があるかもしれません。\\nおでこをちょっと失礼しますね。"

# カズマ
# へへへ、平気だって！\nそれよりも、今日の夜の話だけどさ。
131 = "へへへ、平気だって！\\nそれよりも、今日の夜の話だけどさ。"

# ウィズ
# あ、除霊の件ですか？
122 = "あ、除霊の件ですか？"

# カズマ
# そうそう。\nウィズはいつ頃、ここを出るつもりなんだ？
125 = "そうそう。\\nウィズはいつ頃、ここを出るつもりなんだ？"

# ウィズ
# そうですね、日が暮れて早い時間だと\n現れることも無いでしょうから――
126 = "そうですね、日が暮れて早い時間だと\\n現れることも無いでしょうから――"

# ウィズ
# 晩ご飯時がすんで、しばらくしてからでしょうか。\nその頃なら街も静かになって\n霊も少しずつ出始めるでしょうし。
143 = "晩ご飯時がすんで、しばらくしてからでしょうか。\\nその頃なら街も静かになって\\n霊も少しずつ出始めるでしょうし。"

# カズマ
# 意外と早いんだな。\nもっと深夜かと思ってた。
142 = "意外と早いんだな。\\nもっと深夜かと思ってた。"

# ウィズ
# もちろん、霊が最も活発になるのは\n深夜ですけど、今回の件は\n街中の反応も知っておきたいですから。
134 = "もちろん、霊が最も活発になるのは\\n深夜ですけど、今回の件は\\n街中の反応も知っておきたいですから。"

# ウィズ
# もし何かあれば、そのまま\n深夜までかかってしまうかもしれませんけど。
133 = "もし何かあれば、そのまま\\n深夜までかかってしまうかもしれませんけど。"

# カズマ
# わかった、それじゃ俺も\nいったん帰って、飯食ってからまた来るよ。\n集合場所はここでいいよな？
135 = "わかった、それじゃ俺も\\nいったん帰って、飯食ってからまた来るよ。\\n集合場所はここでいいよな？"

# ウィズ
# はい。\nお待ちしております。
130 = "はい。\\nお待ちしております。"

# カズマ
# じゃ、また後でな！
124 = "じゃ、また後でな！"

