# root_f02.txt.scn

[info]
0 = ""

[characters]
239 = "カズマ"
237 = "ウィズ"
241 = "カズマ（Ｍ）"

[character_subs]
# 239 = "カズマ"

[script]
# lines: 56

# カズマ
# おーい。\nウィズ、いるか？
207 = "おーい。\\nウィズ、いるか？"

# ウィズ
# カズマさん。\nいらっしゃいませ。
240 = "カズマさん。\\nいらっしゃいませ。"

# カズマ
# おーす。\nあれ、今日はひとりなのか？
208 = "おーす。\\nあれ、今日はひとりなのか？"

# ウィズ
# バニルさんは、マジックアイテムの買い出しに、\n遠くの街まで出かけてしまったんです。
243 = "バニルさんは、マジックアイテムの買い出しに、\\n遠くの街まで出かけてしまったんです。"

# カズマ
# じゃあひとりで店番か。\n大変だな。
211 = "じゃあひとりで店番か。\\n大変だな。"

# ウィズ
# そうでもないですよ？\nどうせ暇ですし。
215 = "そうでもないですよ？\\nどうせ暇ですし。"

# カズマ（Ｍ）
# display as カズマ
# （そんな、さらっと笑顔で\n　切ないことを言われてもな）
280 = "（そんな、さらっと笑顔で\\n　切ないことを言われてもな）"

# ウィズ
# それに、バニルさんが来るまでは\n私１人でやってましたしね。
219 = "それに、バニルさんが来るまでは\\n私１人でやってましたしね。"

# カズマ
# でも、バニルが来てくれて\n助かったこととかあるだろ？
226 = "でも、バニルが来てくれて\\n助かったこととかあるだろ？"

# ウィズ
# 助かったことですか？
249 = "助かったことですか？"

# カズマ
# 例えば、防犯面とかさ。\n女１人だと色々不安じゃん。
245 = "例えば、防犯面とかさ。\\n女１人だと色々不安じゃん。"

# ウィズ
# そういう心配はあまりしていませんでしたね。
212 = "そういう心配はあまりしていませんでしたね。"

# カズマ（Ｍ）
# display as カズマ
# （そうだよな……。\n　強盗が来てもウィズなら一捻りだろうし）
279 = "（そうだよな……。\\n　強盗が来てもウィズなら一捻りだろうし）"

# ウィズ
# あ、でも、強いて言うのなら――
193 = "あ、でも、強いて言うのなら――"

# ウィズ
# 力仕事なんかは、最近バニルさんに\n頼りっきりになっちゃってましたから、\nそこだけは少し困ってます。
248 = "力仕事なんかは、最近バニルさんに\\n頼りっきりになっちゃってましたから、\\nそこだけは少し困ってます。"

# カズマ
# ああ、さすがにそういうのは\n男手があった方が便利……あっ、それだ！
194 = "ああ、さすがにそういうのは\\n男手があった方が便利……あっ、それだ！"

# ウィズ
# え？　なんでしょうか？
205 = "え？　なんでしょうか？"

# カズマ
# いやさ、今日ここに来たのは、\nこの前の指輪の件の\nお詫びをさせてもらうためなんだ。
200 = "いやさ、今日ここに来たのは、\\nこの前の指輪の件の\\nお詫びをさせてもらうためなんだ。"

# ウィズ
# お詫びですか？\nそんな、どうして……。
209 = "お詫びですか？\\nそんな、どうして……。"

# カズマ
# だって、ウィズにも嫌な思いを\nたくさんさせちゃっただろ？
224 = "だって、ウィズにも嫌な思いを\\nたくさんさせちゃっただろ？"

# ウィズ
# そんな、嫌なんてことは！
222 = "そんな、嫌なんてことは！"

# カズマ
# え、もしかして喜んでたの！？
203 = "え、もしかして喜んでたの！？"

# ウィズ
# そうじゃないですよ？
213 = "そうじゃないですよ？"

# カズマ
# ハハ、わかってるよ。\nでもさ、そういう気の使われ方は\nちょっと困るんだよな。
242 = "ハハ、わかってるよ。\\nでもさ、そういう気の使われ方は\\nちょっと困るんだよな。"

# ウィズ
# どうしてです？
231 = "どうしてです？"

# カズマ
# 俺の勝手な都合で悪いんだけど、\n無意識でやったことといえ、\n罪悪感が無いと言ったら嘘になるんだ。
246 = "俺の勝手な都合で悪いんだけど、\\n無意識でやったことといえ、\\n罪悪感が無いと言ったら嘘になるんだ。"

# カズマ
# だから、あれやれ、これやれって頼んでくれた方が\n俺は気が楽になるんだよ。
223 = "だから、あれやれ、これやれって頼んでくれた方が\\n俺は気が楽になるんだよ。"

# ウィズ
# なるほど、それはちょっとわかるような気がします。\nですが、やっぱり……。
232 = "なるほど、それはちょっとわかるような気がします。\\nですが、やっぱり……。"

# カズマ
# ウィズって、意外に頑固なんだな。
238 = "ウィズって、意外に頑固なんだな。"

# ウィズ
# そうでしょうか？
214 = "そうでしょうか？"

# カズマ
# あっ、もしかして俺の側にいたくないとか！？
197 = "あっ、もしかして俺の側にいたくないとか！？"

# ウィズ
# ち、違いますよ。
225 = "ち、違いますよ。"

# カズマ
# え、何？　じゃあ俺の側にいたいの？
204 = "え、何？　じゃあ俺の側にいたいの？"

# ウィズ
# それも絶対に違います！
221 = "それも絶対に違います！"

# カズマ
# そこまではっきり言わなくても……。
217 = "そこまではっきり言わなくても……。"

# ウィズ
# ああ、すみません！\n嘘をつけない性格なもので！
195 = "ああ、すみません！\\n嘘をつけない性格なもので！"

# カズマ
# いや傷をえぐってるからね？
201 = "いや傷をえぐってるからね？"

# ウィズ
# うぅ、重ね重ねすみません。
202 = "うぅ、重ね重ねすみません。"

# カズマ
# ま、まあ、冗談はもういいとしてだ。
234 = "ま、まあ、冗談はもういいとしてだ。"

# カズマ
# とにかく、このままじゃ\n俺の気が済まないんだ。
229 = "とにかく、このままじゃ\\n俺の気が済まないんだ。"

# カズマ
# わがままを承知で頼む。\n店を手伝わせてくれ。
236 = "わがままを承知で頼む。\\n店を手伝わせてくれ。"

# ウィズ
# このお店の手伝いをですか？
210 = "このお店の手伝いをですか？"

# カズマ
# ああ、力仕事でもなんでもするぞ。
196 = "ああ、力仕事でもなんでもするぞ。"

# ウィズ
# それは少し助かるかもしれません。\nでも……。
220 = "それは少し助かるかもしれません。\\nでも……。"

# カズマ
# でもじゃない、これはもう決定だ！
228 = "でもじゃない、これはもう決定だ！"

# ウィズ
# まま、待ってください！\nそんなことをしたらバニルさんに\n叱られてしまいます！
235 = "まま、待ってください！\\nそんなことをしたらバニルさんに\\n叱られてしまいます！"

# カズマ
# どうしてだよ。\nここの店主はウィズじゃないか。
230 = "どうしてだよ。\\nここの店主はウィズじゃないか。"

# ウィズ
# そうなのですが、余計な出費をすると\nバニルさんすごく怒るんです。
216 = "そうなのですが、余計な出費をすると\\nバニルさんすごく怒るんです。"

# カズマ
# 出費って、もしかして給料の心配をしてる？
247 = "出費って、もしかして給料の心配をしてる？"

# ウィズ
# はい。\nお手伝いしてもらうんですから、\n対価をお支払いするのは当然かと。
233 = "はい。\\nお手伝いしてもらうんですから、\\n対価をお支払いするのは当然かと。"

# カズマ
# いやいやいや！\nだからさ、これは俺のお詫びというか\n恩返しなんだからさ！
199 = "いやいやいや！\\nだからさ、これは俺のお詫びというか\\n恩返しなんだからさ！"

# カズマ（Ｍ）
# display as カズマ
# （あー、もう！\n　どこまで人がいいんだこのウィズは。\n　いや、まあ、人じゃないけど）
278 = "（あー、もう！\\n　どこまで人がいいんだこのウィズは。\\n　いや、まあ、人じゃないけど）"

# ウィズ
# でも、本当にいいんですか？\n無償で働いて頂くなんて……。
227 = "でも、本当にいいんですか？\\n無償で働いて頂くなんて……。"

# カズマ
# いいんだって。\nむしろ受け取れねーよ。
198 = "いいんだって。\\nむしろ受け取れねーよ。"

# ウィズ
# それでは、お願いしちゃっても……。
218 = "それでは、お願いしちゃっても……。"

# カズマ
# おう、任せとけ！\nなんでも遠慮なく言いつけてくれよ。
206 = "おう、任せとけ！\\nなんでも遠慮なく言いつけてくれよ。"

