# root_d07.txt.scn

[info]
0 = ""

[characters]
279 = "カズマ（Ｍ）"
277 = "カズマ"
283 = "ダスト"
280 = "キース"
282 = "ダクネス"
284 = "ルナ"

[character_subs]
# 277 = "カズマ"

[script]
# lines: 69

# カズマ（Ｍ）
# display as カズマ
# （結局、俺の尾行はなんの意味もなかった。\n　というのも、クリスは当てもなく\n　草原や街を散歩するばかりで……）
344 = "（結局、俺の尾行はなんの意味もなかった。\\n　というのも、クリスは当てもなく\\n　草原や街を散歩するばかりで……）"

# カズマ（Ｍ）
# display as カズマ
# （夕方になった頃には、後をつけていた\n　俺の方がクタクタになってしまい、\n　あきらめて屋敷に帰る羽目になったからだ）
343 = "（夕方になった頃には、後をつけていた\\n　俺の方がクタクタになってしまい、\\n　あきらめて屋敷に帰る羽目になったからだ）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、チャンスはまだある。\n　明日にでも、またクリスの様子を\n　探ってみよう）
340 = "（まあ、チャンスはまだある。\\n　明日にでも、またクリスの様子を\\n　探ってみよう）"

# カズマ
# ん……んん、んあ？
275 = "ん……んん、んあ？"

# カズマ（Ｍ）
# display as カズマ
# （うるせーなぁ、なんの音だ？\n　目が覚めちまったじゃねーか）
331 = "（うるせーなぁ、なんの音だ？\\n　目が覚めちまったじゃねーか）"

# カズマ（Ｍ）
# display as カズマ
# （まだ朝も早いってのに……\n　もう一度、寝なおすか）
341 = "（まだ朝も早いってのに……\\n　もう一度、寝なおすか）"

# カズマ
# …………。
236 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （だああああ！！　眠れねえっ！！！\n　朝から一体なんなんだ！？\n　騒音とかご近所迷惑だろーが！）
334 = "（だああああ！！　眠れねえっ！！！\\n　朝から一体なんなんだ！？\\n　騒音とかご近所迷惑だろーが！）"

# カズマ（Ｍ）
# display as カズマ
# （仕方ない。\n　少し早いけど起きるか）
342 = "（仕方ない。\\n　少し早いけど起きるか）"

# カズマ
# おはよー。\nなあ、この音ってなんの音──
249 = "おはよー。\\nなあ、この音ってなんの音──"

# カズマ（Ｍ）
# display as カズマ
# （あれ？　誰もいないのか、珍しいな。\n　いつもこの時間は\n　みんな居間でダラダラしてるのに）
329 = "（あれ？　誰もいないのか、珍しいな。\\n　いつもこの時間は\\n　みんな居間でダラダラしてるのに）"

# カズマ（Ｍ）
# display as カズマ
# （……本当に、さっきからなんなんだ？\n　方角からいって街の方だよな？\n　朝飯がてら、ちょっと見に行ってみるか）
327 = "（……本当に、さっきからなんなんだ？\\n　方角からいって街の方だよな？\\n　朝飯がてら、ちょっと見に行ってみるか）"

# カズマ（Ｍ）
# display as カズマ
# （うおっ？\n　な、なんだ、この人だかり）
330 = "（うおっ？\\n　な、なんだ、この人だかり）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、人が多すぎて中が見えないな。\n　目玉クエストでも発生したのか？\n　それとも何かイベントでもやってるのか？）
332 = "（うーん、人が多すぎて中が見えないな。\\n　目玉クエストでも発生したのか？\\n　それとも何かイベントでもやってるのか？）"

# ダスト
# よ！　カズマ！\n話は聞いたぜ、ずいぶんと太っ腹じゃないか。\nおかげでみんな大盛り上がりだ！
273 = "よ！　カズマ！\\n話は聞いたぜ、ずいぶんと太っ腹じゃないか。\\nおかげでみんな大盛り上がりだ！"

# カズマ
# は？
270 = "は？"

# キース
# ちょうどうまいクエストがなくて暇してたんだよな。\nグッジョブだぜ、カズマ。
262 = "ちょうどうまいクエストがなくて暇してたんだよな。\\nグッジョブだぜ、カズマ。"

# ダスト
# っと、こうして話してる時間がもったいないぜ！\n探しに行くか！
264 = "っと、こうして話してる時間がもったいないぜ！\\n探しに行くか！"

# ダスト
# お前には負けねーぜ、キース。\n賞金は俺がいただく！
251 = "お前には負けねーぜ、キース。\\n賞金は俺がいただく！"

# キース
# それはこっちのセリフだ。\nいくら仲間だからって手加減はしない。\nそれじゃ、またなカズマ。
257 = "それはこっちのセリフだ。\\nいくら仲間だからって手加減はしない。\\nそれじゃ、またなカズマ。"

# カズマ
# あ、おい！\n待ってくれ！
237 = "あ、おい！\\n待ってくれ！"

# カズマ（Ｍ）
# display as カズマ
# （って、行っちまった。\n　ダストが言ってた太っ腹ってなんの話だ？\n　俺、何かしたっけ？）
336 = "（って、行っちまった。\\n　ダストが言ってた太っ腹ってなんの話だ？\\n　俺、何かしたっけ？）"

# ダクネス
# ああ、カズマ！\nちょうどよかった、話がある。
238 = "ああ、カズマ！\\nちょうどよかった、話がある。"

# カズマ
# ああ、ダクネス、ここにいたのか。\nどうしたんだ、珍しく険しい顔して。
239 = "ああ、ダクネス、ここにいたのか。\\nどうしたんだ、珍しく険しい顔して。"

# ダクネス
# クリスにどんな用件があるんだ？
281 = "クリスにどんな用件があるんだ？"

# カズマ
# はい？
269 = "はい？"

# カズマ（Ｍ）
# display as カズマ
# （ああ、そっか。\n　昨日、後をつけてたところを見られたんだっけ）
328 = "（ああ、そっか。\\n　昨日、後をつけてたところを見られたんだっけ）"

# カズマ
# いやまあ、そんな大層なことじゃないんだよ。\nちょっと個人的な用事で探してるだけで。
243 = "いやまあ、そんな大層なことじゃないんだよ。\\nちょっと個人的な用事で探してるだけで。"

# ダクネス
# そうなのか？
254 = "そうなのか？"

# カズマ
# それよりさ、この騒ぎはなんなんだ？
259 = "それよりさ、この騒ぎはなんなんだ？"

# ダクネス
# 何を言っている。\n原因はお前だろう。
286 = "何を言っている。\\n原因はお前だろう。"

# カズマ（Ｍ）
# display as カズマ
# （へっ？　俺？）
338 = "（へっ？　俺？）"

# ダクネス
# お前がクリスを捕まえようとしている。\nだが、クリスはお前から逃げ続けているため\n捕まえることができない。
250 = "お前がクリスを捕まえようとしている。\\nだが、クリスはお前から逃げ続けているため\\n捕まえることができない。"

# ダクネス
# そこでお前が、\nクリスを捕まえた者に報酬を出すと\nクエストを発注したんだろう？
256 = "そこでお前が、\\nクリスを捕まえた者に報酬を出すと\\nクエストを発注したんだろう？"

# ダクネス
# 制限時間は６時間後、\nクエスト達成報酬金額、１００万エリスで。
288 = "制限時間は６時間後、\\nクエスト達成報酬金額、１００万エリスで。"

# カズマ
# はああっ！？
267 = "はああっ！？"

# ダクネス
# ちょうど今はめぼしいクエストもなかったからな。\nみんな、お前の出した緊急クエストに\n大喜びしているぞ。
263 = "ちょうど今はめぼしいクエストもなかったからな。\\nみんな、お前の出した緊急クエストに\\n大喜びしているぞ。"

# ダクネス
# しかし、１００万エリスとは奮発したな。\nそこまで出すからには、その……\n人には言えない深い事情があるのかと思ったのだが。
252 = "しかし、１００万エリスとは奮発したな。\\nそこまで出すからには、その……\\n人には言えない深い事情があるのかと思ったのだが。"

# カズマ
# ま、待て待て待て待てっ！\n一体、なんの話だ！\n俺はそんなクエスト発注した覚えはないぞ！
271 = "ま、待て待て待て待てっ！\\n一体、なんの話だ！\\n俺はそんなクエスト発注した覚えはないぞ！"

# ダクネス
# そうなのか？\nいやしかし、現に掲示板には\nお前の名で新規クエストとして登録されているぞ？
255 = "そうなのか？\\nいやしかし、現に掲示板には\\nお前の名で新規クエストとして登録されているぞ？"

# カズマ
# そ、そんなバカな！\nちょっと確認してくる！！
253 = "そ、そんなバカな！\\nちょっと確認してくる！！"

# カズマ（Ｍ）
# display as カズマ
# （ま、マジだ！\n　確かに俺の名前でクエストが……\n　誰だよ、こんなクエスト勝手に発注した奴は！）
339 = "（ま、マジだ！\\n　確かに俺の名前でクエストが……\\n　誰だよ、こんなクエスト勝手に発注した奴は！）"

# カズマ（Ｍ）
# display as カズマ
# （そ、そうだ。\n　キャンセル、キャンセルを早く……）
333 = "（そ、そうだ。\\n　キャンセル、キャンセルを早く……）"

# ルナ
# あら、おはようございますサトウさん。\n今日はどうされたんですか？
241 = "あら、おはようございますサトウさん。\\n今日はどうされたんですか？"

# カズマ
# ちょうどいいところに！\nあのクリスを探すクエスト、\n誰が発注したんですか！？
261 = "ちょうどいいところに！\\nあのクリスを探すクエスト、\\n誰が発注したんですか！？"

# ルナ
# えっ？
248 = "えっ？"

# カズマ
# いや今はそんなことどうでもいいです！\nそれよりあれ、取り消すことはできますよね！？
244 = "いや今はそんなことどうでもいいです！\\nそれよりあれ、取り消すことはできますよね！？"

# ルナ
# ええと、その、すみません。\nそれはお受けできないんです。
246 = "ええと、その、すみません。\\nそれはお受けできないんです。"

# カズマ
# なんでですか！？
266 = "なんでですか！？"

# ルナ
# 既に受注してしまった方が多いので……。
295 = "既に受注してしまった方が多いので……。"

# カズマ
# 多いって……どれくらいなんですか！
292 = "多いって……どれくらいなんですか！"

# ルナ
# 街の冒険者の人のほとんどですね。
326 = "街の冒険者の人のほとんどですね。"

# カズマ
# なっ、ほとんど！？
265 = "なっ、ほとんど！？"

# ルナ
# 最近は高難度のクエストが多く、\nこの街の駆け出し冒険者が受けられるものが\n少なかったので、街はお祭り騒ぎです。
296 = "最近は高難度のクエストが多く、\\nこの街の駆け出し冒険者が受けられるものが\\n少なかったので、街はお祭り騒ぎです。"

# ルナ
# そんな雰囲気に触発されて、\nついスタートの号砲まで上げてしまったのですが。\n何か問題でもありましたか？
260 = "そんな雰囲気に触発されて、\\nついスタートの号砲まで上げてしまったのですが。\\n何か問題でもありましたか？"

# カズマ
# 問題だらけですよ！\nだって俺が発注したクエストじゃ\nないんですもん！
291 = "問題だらけですよ！\\nだって俺が発注したクエストじゃ\\nないんですもん！"

# ルナ
# ええ！？
247 = "ええ！？"

# カズマ
# いったい誰がこんなふざけたことを！！
242 = "いったい誰がこんなふざけたことを！！"

# ルナ
# それは私にも。\n気がついたら、\nクエストとして受理されていたもので。
258 = "それは私にも。\\n気がついたら、\\nクエストとして受理されていたもので。"

# カズマ
# んがああああああ！\n絶対に犯人を見つけ出してヒーヒー言わせてやる！
276 = "んがああああああ！\\n絶対に犯人を見つけ出してヒーヒー言わせてやる！"

# ダクネス
# カズマ！\n実はこのクエストを発注したのは私なんだ！
278 = "カズマ！\\n実はこのクエストを発注したのは私なんだ！"

# カズマ
# うん、お前じゃないことだけはわかった。
245 = "うん、お前じゃないことだけはわかった。"

# ルナ
# あの、サトウさん。\n今さら、取り消すのは無理ですが――
240 = "あの、サトウさん。\\n今さら、取り消すのは無理ですが――"

# ルナ
# もしサトウさんがご自分で\nクリスさんを捕獲した場合は、サトウさんが\n賞金の権利を獲得することになりますよ。
272 = "もしサトウさんがご自分で\\nクリスさんを捕獲した場合は、サトウさんが\\n賞金の権利を獲得することになりますよ。"

# カズマ
# 俺が他の奴らより先に\nクリスを捕まえることができれば、\n賞金を支払わなくてもすむんですね？
287 = "俺が他の奴らより先に\\nクリスを捕まえることができれば、\\n賞金を支払わなくてもすむんですね？"

# ルナ
# はい、そうなります。\nあとは制限時間までに\nクリスさんご自身が逃げ切った場合ですね。
268 = "はい、そうなります。\\nあとは制限時間までに\\nクリスさんご自身が逃げ切った場合ですね。"

# カズマ
# わ、わかりました！\nありがとうございます。
274 = "わ、わかりました！\\nありがとうございます。"

# カズマ（Ｍ）
# display as カズマ
# （とりあえず、誰よりも先に\n　クリスを見つけ出して状況を説明しないと……）
337 = "（とりあえず、誰よりも先に\\n　クリスを見つけ出して状況を説明しないと……）"

# カズマ（Ｍ）
# display as カズマ
# （ったく、こんな悪質なことをしたのは\n　一体どこのどいつなんだ？\n　見つけたらタダじゃおかねーからなっ！）
335 = "（ったく、こんな悪質なことをしたのは\\n　一体どこのどいつなんだ？\\n　見つけたらタダじゃおかねーからなっ！）"

