# root_c18.txt.scn

[info]
0 = ""

[characters]
353 = "アクア"
345 = "めぐみん"
358 = "ダクネス"
355 = "カズマ（Ｍ）"
354 = "カズマ"

[character_subs]
# 354 = "カズマ"

[script]
# lines: 99

# アクア
# はぁいっ！
338 = "はぁいっ！"

# めぐみん
# おーっ！　凄いですアクア！！
308 = "おーっ！　凄いですアクア！！"

# ダクネス
# 更に技に磨きがかかったな。\nいい芸だった。
372 = "更に技に磨きがかかったな。\\nいい芸だった。"

# カズマ（Ｍ）
# display as カズマ
# （……また無駄なスキルを極めやがって。\n　しかし、これを披露するってことは\n　機嫌も直ったんだな）
412 = "（……また無駄なスキルを極めやがって。\\n　しかし、これを披露するってことは\\n　機嫌も直ったんだな）"

# アクア
# さてさて、お立ち会い。\n笑いすぎて、そろそろ喉が渇いてきたんじゃない？
318 = "さてさて、お立ち会い。\\n笑いすぎて、そろそろ喉が渇いてきたんじゃない？"

# ダクネス
# ああ、確かに飲み物が切れてしまったな。\nでは私が持ってこよう。
289 = "ああ、確かに飲み物が切れてしまったな。\\nでは私が持ってこよう。"

# アクア
# 心配ご無用。\nこのアクア様にお任せあれ。
370 = "心配ご無用。\\nこのアクア様にお任せあれ。"

# アクア
# みんなの空になったコップが、あら不思議～！\n花鳥風月～！
344 = "みんなの空になったコップが、あら不思議～！\\n花鳥風月～！"

# めぐみん
# おおおおー！
307 = "おおおおー！"

# カズマ
# サンキュー、アクア。\nちょうど水が飲みたかったんだ。
357 = "サンキュー、アクア。\\nちょうど水が飲みたかったんだ。"

# ダクネス
# 本当に便利な宴会芸だな。
373 = "本当に便利な宴会芸だな。"

# アクア
# クリエイト・ウォーターより\n華があっていいでしょ？
356 = "クリエイト・ウォーターより\\n華があっていいでしょ？"

# アクア
# そうそう、最近、\nまた新しい宴会芸を思いついたの！\n見て、感想を聞かせてちょうだい？
324 = "そうそう、最近、\\nまた新しい宴会芸を思いついたの！\\n見て、感想を聞かせてちょうだい？"

# カズマ（Ｍ）
# display as カズマ
# （……アクアは\n　いったいどこへ向かおうとしているんだ？）
413 = "（……アクアは\\n　いったいどこへ向かおうとしているんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （まぁ、別にアクアがどうなろうが\n　知ったこっちゃないけどな）
422 = "（まぁ、別にアクアがどうなろうが\\n　知ったこっちゃないけどな）"

# カズマ（Ｍ）
# display as カズマ
# （なにせ俺には、尽きることない愛を\n　注いでくれるダクネスがいる！）
419 = "（なにせ俺には、尽きることない愛を\\n　注いでくれるダクネスがいる！）"

# ダクネス
# どうした、カズマ？
334 = "どうした、カズマ？"

# カズマ
# いやぁ、なんでもないぜ？
296 = "いやぁ、なんでもないぜ？"

# カズマ（Ｍ）
# display as カズマ
# （ああ……。\n　女神という言葉は\n　ダクネスにこそ相応しいよなぁ）
415 = "（ああ……。\\n　女神という言葉は\\n　ダクネスにこそ相応しいよなぁ）"

# カズマ（Ｍ）
# display as カズマ
# （俺はなんて幸せなんだろう。\n　やっぱり愛は最高だ！）
424 = "（俺はなんて幸せなんだろう。\\n　やっぱり愛は最高だ！）"

# カズマ（Ｍ）
# display as カズマ
# （食事が始まってから\n　ずっと隣で世話をしてくれるけど、\n　もっと甘えたい……もっとラブラブしたい……）
425 = "（食事が始まってから\\n　ずっと隣で世話をしてくれるけど、\\n　もっと甘えたい……もっとラブラブしたい……）"

# カズマ
# あ～、なんだか酔っちゃったみたいだなぁ～。
294 = "あ～、なんだか酔っちゃったみたいだなぁ～。"

# ダクネス
# ん？　シュワシュワは飲んでいないだろう？
352 = "ん？　シュワシュワは飲んでいないだろう？"

# カズマ
# 場の雰囲気に酔っちまったのかなぁ。
367 = "場の雰囲気に酔っちまったのかなぁ。"

# ダクネス
# ん？　そ、そうなのか？
350 = "ん？　そ、そうなのか？"

# カズマ
# それに少し眠くなってきたよ、ダクネスぅ。
331 = "それに少し眠くなってきたよ、ダクネスぅ。"

# ダクネス
# それなら、そろそろお開きに――
330 = "それなら、そろそろお開きに――"

# カズマ
# 俺、ダクネスで仮眠したいんだ。
364 = "俺、ダクネスで仮眠したいんだ。"

# ダクネス
# ん？　んん？　私で仮眠？？
351 = "ん？　んん？　私で仮眠？？"

# カズマ
# うん、ダクネスの温もりに包まれて寝たい。
300 = "うん、ダクネスの温もりに包まれて寝たい。"

# めぐみん
# またくだらないことを言ってますよ。
342 = "またくだらないことを言ってますよ。"

# アクア
# もう放っておきましょう。\n関わると腹が立つだけだし。
346 = "もう放っておきましょう。\\n関わると腹が立つだけだし。"

# ダクネス
# ええと、すまん。\nよくわからないのだが、どうしたらいい。
304 = "ええと、すまん。\\nよくわからないのだが、どうしたらいい。"

# カズマ
# じゃあ、床に座ってくれ。
320 = "じゃあ、床に座ってくれ。"

# ダクネス
# わ、わかった。
347 = "わ、わかった。"

# カズマ
# そして、こーう！
327 = "そして、こーう！"

# ダクネス
# う、うわ！？
297 = "う、うわ！？"

# めぐみん
# …………。
283 = "…………。"

# アクア
# …………。
# 283 = "…………。"

# カズマ
# ああ～！\nフカフカで気持ちいい！\nそれになんだか、いい匂いがするよ。
290 = "ああ～！\\nフカフカで気持ちいい！\\nそれになんだか、いい匂いがするよ。"

# ダクネス
# こ、こ、こら！\nどさくさに紛れて何をしている！
312 = "こ、こ、こら！\\nどさくさに紛れて何をしている！"

# カズマ
# こうしていると……\nこの世のありとあらゆる苦痛から\n解放されたような気分になれるんだ。
315 = "こうしていると……\\nこの世のありとあらゆる苦痛から\\n解放されたような気分になれるんだ。"

# ダクネス
# そ、そうなのか？
321 = "そ、そうなのか？"

# カズマ
# なんてちっぽけなことに悩んでいたんだとか、\n明日もがんばろって気持ちが湧いてくる\n感じだ。
337 = "なんてちっぽけなことに悩んでいたんだとか、\\n明日もがんばろって気持ちが湧いてくる\\n感じだ。"

# ダクネス
# なるほど、私にはよくわからないが、\nカズマの役に立てているなら、\nまあ、うん、許容できなくもないか。
335 = "なるほど、私にはよくわからないが、\\nカズマの役に立てているなら、\\nまあ、うん、許容できなくもないか。"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスも少し酔っ払ってるから\n　抵抗も弱いし、これは甘えまくれるぞ！）
423 = "（ダクネスも少し酔っ払ってるから\\n　抵抗も弱いし、これは甘えまくれるぞ！）"

# カズマ
# はああ～！\nダクネス、ふかふかで気持ちい～い！
340 = "はああ～！\\nダクネス、ふかふかで気持ちい～い！"

# アクア
# ちょっと、カズマ。\nそういうくだらないことやめてくれない？
332 = "ちょっと、カズマ。\\nそういうくだらないことやめてくれない？"

# めぐみん
# そうですよ、見ていて不愉快です。
325 = "そうですよ、見ていて不愉快です。"

# カズマ
# うっさい！\n今の俺はアクアに殴られて\n心に深い傷を負ってるんだ！
298 = "うっさい！\\n今の俺はアクアに殴られて\\n心に深い傷を負ってるんだ！"

# カズマ
# この傷を癒やせるのは……。
316 = "この傷を癒やせるのは……。"

# ダクネス
# こ、このような行為だけなのか？
313 = "こ、このような行為だけなのか？"

# カズマ
# ああ、そうだ。\nそしてそれは、ダクネスじゃないと駄目なんだ！
288 = "ああ、そうだ。\\nそしてそれは、ダクネスじゃないと駄目なんだ！"

# ダクネス
# し、しかしだな、その、顔が胸にあたって……。
319 = "し、しかしだな、その、顔が胸にあたって……。"

# カズマ
# ぐっ、心が痛い！\n今、ダクネスに離れられたら\n一生消えない傷として残ってしまう！
311 = "ぐっ、心が痛い！\\n今、ダクネスに離れられたら\\n一生消えない傷として残ってしまう！"

# ダクネス
# うわ、すまない！
299 = "うわ、すまない！"

# アクア
# あんたが治さなきゃならないのは\nその減らず口と腐った根性じゃない？
292 = "あんたが治さなきゃならないのは\\nその減らず口と腐った根性じゃない？"

# めぐみん
# こういう時だけ頭が回るのは、\n呆れを通り越して感心しますね。
314 = "こういう時だけ頭が回るのは、\\n呆れを通り越して感心しますね。"

# カズマ
# ダクネス～。\nもっと俺を癒やしてくれよ～。
359 = "ダクネス～。\\nもっと俺を癒やしてくれよ～。"

# ダクネス
# そうは言われても、どうしたらいいのか。
326 = "そうは言われても、どうしたらいいのか。"

# カズマ
# 頭を撫でて欲しいな。
410 = "頭を撫でて欲しいな。"

# ダクネス
# わかった。\nこ、こんな感じでいいのか？
349 = "わかった。\\nこ、こんな感じでいいのか？"

# カズマ
# ああ……うん……。\nすべてを許された様な気分になってくる。
287 = "ああ……うん……。\\nすべてを許された様な気分になってくる。"

# ダクネス
# ……そんな安らかな顔をされると\n私もなんだか嬉しいぞ。
284 = "……そんな安らかな顔をされると\\n私もなんだか嬉しいぞ。"

# カズマ（Ｍ）
# display as カズマ
# （くぅぅっ！\n　これは毎日やってもらってもいいな！）
418 = "（くぅぅっ！\\n　これは毎日やってもらってもいいな！）"

# カズマ（Ｍ）
# display as カズマ
# （ああ……\n　このまま本当に眠ってしまいたい……）
414 = "（ああ……\\n　このまま本当に眠ってしまいたい……）"

# めぐみん
# なんだか、子供が\n母親に甘えているみたいですね。
336 = "なんだか、子供が\\n母親に甘えているみたいですね。"

# アクア
# 虫ずが走るっていうのは、\nこういうことを言うのね。
408 = "虫ずが走るっていうのは、\\nこういうことを言うのね。"

# カズマ（Ｍ）
# display as カズマ
# （ふふふ、なんとでも言うがいい。\n　この癒やしの前では、\n　お前らの嫌みなど消し飛ぶわ！）
421 = "（ふふふ、なんとでも言うがいい。\\n　この癒やしの前では、\\n　お前らの嫌みなど消し飛ぶわ！）"

# カズマ
# 何か、食べさせて欲しいな。
362 = "何か、食べさせて欲しいな。"

# ダクネス
# えっ、まだ食べるのか？\nもうほとんど食べてしまって、\nつまみぐらいしかないぞ？
305 = "えっ、まだ食べるのか？\\nもうほとんど食べてしまって、\\nつまみぐらいしかないぞ？"

# カズマ
# それでもいいよ。\nあーん！
329 = "それでもいいよ。\\nあーん！"

# ダクネス
# 仕方ないやつだな。\nほら、気をつけて食べろよ？
361 = "仕方ないやつだな。\\nほら、気をつけて食べろよ？"

# カズマ
# あむあむあむあむ……。\nうまーい。
291 = "あむあむあむあむ……。\\nうまーい。"

# ダクネス
# そうか、よかったな。
323 = "そうか、よかったな。"

# アクア
# 餌付けされてるみたい。
411 = "餌付けされてるみたい。"

# めぐみん
# ええ、お母さん鳥から\nエサを与えられているヒナみたいです。
302 = "ええ、お母さん鳥から\\nエサを与えられているヒナみたいです。"

# カズマ（Ｍ）
# display as カズマ
# （ふふ、これも恋人同士の特権というやつだ！）
420 = "（ふふ、これも恋人同士の特権というやつだ！）"

# カズマ
# 甘い言葉でささやいて欲しいな。\n例えば、恋愛戯曲の有名な台詞とか。
376 = "甘い言葉でささやいて欲しいな。\\n例えば、恋愛戯曲の有名な台詞とか。"

# ダクネス
# ええっ！？\nそれは……恥ずかしいのだが……。
303 = "ええっ！？\\nそれは……恥ずかしいのだが……。"

# めぐみん
# これって、恥ずかしいことを言わせる\nプレイですね。
317 = "これって、恥ずかしいことを言わせる\\nプレイですね。"

# アクア
# 暗い悦びを感じる最低なヤツだわ。
371 = "暗い悦びを感じる最低なヤツだわ。"

# カズマ
# あ、そうだ、たまには\n口調を変えてみるのはどうだ？\nお嬢様でいる時っぽく頼むよ。
286 = "あ、そうだ、たまには\\n口調を変えてみるのはどうだ？\\nお嬢様でいる時っぽく頼むよ。"

# ダクネス
# あんな口調がいいのか？
293 = "あんな口調がいいのか？"

# カズマ
# うん、頼むよ。\nちょっとぐらいいいだろ？
301 = "うん、頼むよ。\\nちょっとぐらいいいだろ？"

# ダクネス
# わかっ……わかり……ましたわ。
348 = "わかっ……わかり……ましたわ。"

# カズマ
# それそれ！\nやっぱり、お嬢様なダクネスも可愛いぞ。
328 = "それそれ！\\nやっぱり、お嬢様なダクネスも可愛いぞ。"

# ダクネス
# そ、そんな、恥ずかしいですわ。\nカズマはいつも意地悪ばかりです。
322 = "そ、そんな、恥ずかしいですわ。\\nカズマはいつも意地悪ばかりです。"

# ダクネス
# でも、今は……\n私の胸の中で、まるで子供のようですわね。
333 = "でも、今は……\\n私の胸の中で、まるで子供のようですわね。"

# ダクネス
# ふふっ！\nこんなところがあるなんて、初めて知りました。
341 = "ふふっ！\\nこんなところがあるなんて、初めて知りました。"

# ダクネス
# いいんですよ。\n好きなだけこうしていて。
295 = "いいんですよ。\\n好きなだけこうしていて。"

# カズマ
# まっ、マジで！？
343 = "まっ、マジで！？"

# ダクネス
# くう……。\nそろそろ勘弁してくれ、カズマ。
310 = "くう……。\\nそろそろ勘弁してくれ、カズマ。"

# カズマ
# えー？　可愛かったのに。
306 = "えー？　可愛かったのに。"

# アクア
# はあ……。\nなんだか、しらけてきちゃったわ。\nそろそろお開きにしましょ。
339 = "はあ……。\\nなんだか、しらけてきちゃったわ。\\nそろそろお開きにしましょ。"

# めぐみん
# お腹もいっぱいですし、\nもう寝てしまいましょうか。
309 = "お腹もいっぱいですし、\\nもう寝てしまいましょうか。"

# ダクネス
# あ、ああ、そうだな。\n今日はこの辺にしておくか。
285 = "あ、ああ、そうだな。\\n今日はこの辺にしておくか。"

# カズマ（Ｍ）
# display as カズマ
# （えっ？　もう終わり？\n　楽しい時間というのは、\n　あっという間に過ぎてしまうもんだな）
417 = "（えっ？　もう終わり？\\n　楽しい時間というのは、\\n　あっという間に過ぎてしまうもんだな）"

# カズマ（Ｍ）
# display as カズマ
# （あー！\n　今日はよく眠れそうだ！）
416 = "（あー！\\n　今日はよく眠れそうだ！）"

[selections]
409 = "頭を撫でて欲しいな"
363 = "何か食べさせて欲しいな"
375 = "甘い言葉でささやいて欲しいな"
