# root_d06.txt.scn

[info]
0 = ""

[characters]
92 = "クリス"

[character_subs]

[script]
# lines: 6

# クリス
# ふう……。
91 = "ふう……。"

# クリス
# （まったく、\n　カズマはあれで隠れてるつもりなのかな？\n　バレバレだよ……）
99 = "（まったく、\\n　カズマはあれで隠れてるつもりなのかな？\\n　バレバレだよ……）"

# クリス
# （姿も草の合間から丸見えだし、\n　めぐみんとお喋りしている内容まで\n　ちゃんと聞こえてくるし）
101 = "（姿も草の合間から丸見えだし、\\n　めぐみんとお喋りしている内容まで\\n　ちゃんと聞こえてくるし）"

# クリス
# （何が目的でついてきてるのか知らないけど、\n　尾行するならもっとうまくやらないと。\n　今度、尾行のポイントを教えてあげようかな）
100 = "（何が目的でついてきてるのか知らないけど、\\n　尾行するならもっとうまくやらないと。\\n　今度、尾行のポイントを教えてあげようかな）"

# クリス
# （でもまあ、いい暇つぶしにはなるかな。\n　どうせあたしも暇だし）
98 = "（でもまあ、いい暇つぶしにはなるかな。\\n　どうせあたしも暇だし）"

# クリス
# （さーて、次はどこへ行こうかな～）
97 = "（さーて、次はどこへ行こうかな～）"

