# root_e13.txt.scn

[info]
0 = ""

[characters]
364 = "アクア"
366 = "カズマ"
370 = "ダクネス"
357 = "ゆんゆん"
369 = "カズマ（Ｍ）"
354 = "めぐみん"
355 = "めぐみん＆ゆんゆん"

[character_subs]
# 366 = "カズマ"

[script]
# lines: 82

# アクア
# ぷっは～！\n一仕事した後の一杯は格別ね！
352 = "ぷっは～！\\n一仕事した後の一杯は格別ね！"

# カズマ
# お前何かしたっけ？
326 = "お前何かしたっけ？"

# アクア
# そういうカズマだって\n何もしてないじゃない。
331 = "そういうカズマだって\\n何もしてないじゃない。"

# カズマ
# お前に言われるまでもなくわかってるよ。\n今回は、ダクネスとゆんゆんのお手柄だ。
325 = "お前に言われるまでもなくわかってるよ。\\n今回は、ダクネスとゆんゆんのお手柄だ。"

# ダクネス
# いや、私はただ囮をしただけに過ぎない。\n全ては、ゆんゆんの功績だ。
317 = "いや、私はただ囮をしただけに過ぎない。\\n全ては、ゆんゆんの功績だ。"

# ゆんゆん
# そ、そんな、大したことはしてません。
329 = "そ、そんな、大したことはしてません。"

# アクア
# 謙遜しなくてもいいのよ。\nおかげで、こんなご馳走にありつけたんだから。
440 = "謙遜しなくてもいいのよ。\\nおかげで、こんなご馳走にありつけたんだから。"

# カズマ（Ｍ）
# display as カズマ
# （そうだな。\n　サラダ退治なんて内容の割に\n　思っていた以上に報酬が良くてビックリだ）
441 = "（そうだな。\\n　サラダ退治なんて内容の割に\\n　思っていた以上に報酬が良くてビックリだ）"

# アクア
# というわけで、今日はとことん飲むわよ！\nじゃんじゃん飲むわよ！
341 = "というわけで、今日はとことん飲むわよ！\\nじゃんじゃん飲むわよ！"

# アクア
# って、あら？\nもうコップが空だわ。
337 = "って、あら？\\nもうコップが空だわ。"

# ゆんゆん
# あっ！　いま、お注ぎします。
314 = "あっ！　いま、お注ぎします。"

# アクア
# 悪いわね。\nおっととと……。
390 = "悪いわね。\\nおっととと……。"

# アクア
# 相変わらずシュワシュワの注ぎ方が天才的ね。\n立派な才能よ！　誇りなさい！
434 = "相変わらずシュワシュワの注ぎ方が天才的ね。\\n立派な才能よ！　誇りなさい！"

# ゆんゆん
# あまり嬉しくない才能なような……。\nできればもっと素敵な才能が欲しいです。
315 = "あまり嬉しくない才能なような……。\\nできればもっと素敵な才能が欲しいです。"

# めぐみん
# …………。
309 = "…………。"

# ダクネス
# 何を言う。\nゆんゆんは才能豊かな魔法使いじゃないか。\n言っておくが、これはお世辞ではないぞ？
374 = "何を言う。\\nゆんゆんは才能豊かな魔法使いじゃないか。\\n言っておくが、これはお世辞ではないぞ？"

# ゆんゆん
# そ、そんな……私なんて……。
328 = "そ、そんな……私なんて……。"

# ダクネス
# 謙虚で控えめなのはいいことだが、\nなにも卑下することはない。
439 = "謙虚で控えめなのはいいことだが、\\nなにも卑下することはない。"

# アクア
# ええ、魔法もだけど\n掃除の腕だって大したものよね。\n細かいところまで丁寧にしてくれるもの。
318 = "ええ、魔法もだけど\\n掃除の腕だって大したものよね。\\n細かいところまで丁寧にしてくれるもの。"

# ダクネス
# ああ、そうだな。\n細やかな気配りがきくというのは私も感じていた。
313 = "ああ、そうだな。\\n細やかな気配りがきくというのは私も感じていた。"

# ダクネス
# 常に相手の立場に立ち、どうすれば喜ばれるか\n日頃から考えていなければああはできない。
388 = "常に相手の立場に立ち、どうすれば喜ばれるか\\n日頃から考えていなければああはできない。"

# ダクネス
# それも立派な才能だと私は思う。\n誰でもできることではない。\nだから胸を張っていいんじゃないか？
332 = "それも立派な才能だと私は思う。\\n誰でもできることではない。\\nだから胸を張っていいんじゃないか？"

# ゆんゆん
# あ、ありがとうございます！\nそんな風に言われたの初めてで……\nとっても嬉しい……。
312 = "あ、ありがとうございます！\\nそんな風に言われたの初めてで……\\nとっても嬉しい……。"

# めぐみん
# …………。
# 309 = "…………。"

# アクア
# ねえ、どうせだから\nこのまま私たちのパーティーに入っちゃったら？
347 = "ねえ、どうせだから\\nこのまま私たちのパーティーに入っちゃったら？"

# ゆんゆん
# え？　ええええっ！？
320 = "え？　ええええっ！？"

# めぐみん
# ア、アクア！？\n何を言い出すんですか！
363 = "ア、アクア！？\\n何を言い出すんですか！"

# アクア
# ていうか、今更いなくなられると困るのよね。\nもしゆんゆんがいなくなったら、\n誰が私の面倒を見るのよ？
338 = "ていうか、今更いなくなられると困るのよね。\\nもしゆんゆんがいなくなったら、\\n誰が私の面倒を見るのよ？"

# カズマ
# 自分でやれ。
437 = "自分でやれ。"

# アクア
# 嫌よ。\n前の生活になんか戻りたくないわ。
385 = "嫌よ。\\n前の生活になんか戻りたくないわ。"

# カズマ
# どこまでダメなんだ、お前は！
344 = "どこまでダメなんだ、お前は！"

# アクア
# ねえ、ダクネスはどう？
349 = "ねえ、ダクネスはどう？"

# ダクネス
# 私も構わないぞ？\n仲間は多い方が心強い。
436 = "私も構わないぞ？\\n仲間は多い方が心強い。"

# ゆんゆん
# アクアさん、ダクネスさん……！
365 = "アクアさん、ダクネスさん……！"

# アクア
# カズマはどうなのよ？\n文句あるわけ？
368 = "カズマはどうなのよ？\\n文句あるわけ？"

# カズマ
# 別に、勝手に決めてくれよ。
381 = "別に、勝手に決めてくれよ。"

# アクア
# 何よ、そのどうでもいい感じ。\n興味ないの？
373 = "何よ、そのどうでもいい感じ。\\n興味ないの？"

# カズマ
# 俺はゆんゆんの意思を尊重したいだけだ。\n無理に仲間にするわけにもいかないし。
379 = "俺はゆんゆんの意思を尊重したいだけだ。\\n無理に仲間にするわけにもいかないし。"

# カズマ
# ゆんゆんが入りたいって言うなら\n反対する理由はない。\nそういうことだ。
358 = "ゆんゆんが入りたいって言うなら\\n反対する理由はない。\\nそういうことだ。"

# カズマ
# ていうかさ、問題は\nむしろめぐみんの方じゃないか？
339 = "ていうかさ、問題は\\nむしろめぐみんの方じゃないか？"

# カズマ
# 戦力アップは歓迎だ。\nゆんゆんが入ってくれれば\nこれほど頼もしいことはない。
393 = "戦力アップは歓迎だ。\\nゆんゆんが入ってくれれば\\nこれほど頼もしいことはない。"

# ゆんゆん
# カズマさん！
367 = "カズマさん！"

# アクア
# でしょ？\n家事もできて戦力にもなる、完璧よ！
340 = "でしょ？\\n家事もできて戦力にもなる、完璧よ！"

# カズマ（Ｍ）
# display as カズマ
# （家事は外してやれ……）
443 = "（家事は外してやれ……）"

# アクア
# となると、あとはめぐみんね。
342 = "となると、あとはめぐみんね。"

# カズマ
# 俺はいいけど、めぐみんはどうだ？
378 = "俺はいいけど、めぐみんはどうだ？"

# めぐみん
# 私は反対です。\n１つのパーティーに\n魔法使いは２人もいりませんよ。
435 = "私は反対です。\\n１つのパーティーに\\n魔法使いは２人もいりませんよ。"

# ゆんゆん
# え？
319 = "え？"

# めぐみん
# ゆんゆんを入れるということは、\n私は不要ということですか？　私はクビですか？
359 = "ゆんゆんを入れるということは、\\n私は不要ということですか？　私はクビですか？"

# アクア
# そ、そんなこと言ってないでしょ？\n別に、２人いてもよくない？
330 = "そ、そんなこと言ってないでしょ？\\n別に、２人いてもよくない？"

# めぐみん
# よくありません。\n私１人では戦力にならないから\nゆんゆんを入れたいとしか思えません。
360 = "よくありません。\\n私１人では戦力にならないから\\nゆんゆんを入れたいとしか思えません。"

# めぐみん
# 使い勝手の悪い爆裂魔法より\n上級魔法の方が便利だと……そういうことですね？
375 = "使い勝手の悪い爆裂魔法より\\n上級魔法の方が便利だと……そういうことですね？"

# ダクネス
# 誰もそんなことは言っていないぞ。\nどうしたんだ、めぐみん。
438 = "誰もそんなことは言っていないぞ。\\nどうしたんだ、めぐみん。"

# めぐみん
# ……みんなが、ゆんゆんをパーティーに\n入れたいというなら、それもいいでしょう。
311 = "……みんなが、ゆんゆんをパーティーに\\n入れたいというなら、それもいいでしょう。"

# めぐみん
# 代わりに、私が出て行きます。\nそれで全て上手くいきますよね？
372 = "代わりに、私が出て行きます。\\nそれで全て上手くいきますよね？"

# ゆんゆん
# ちょ、ちょっと、めぐみん！？
335 = "ちょ、ちょっと、めぐみん！？"

# カズマ
# おいおい、何を拗ねてるんだよ。\n子供か？
323 = "おいおい、何を拗ねてるんだよ。\\n子供か？"

# めぐみん
# どうせ子供ですよ。\nカズマだって、胸の大きな方がいいんでしょう？
343 = "どうせ子供ですよ。\\nカズマだって、胸の大きな方がいいんでしょう？"

# カズマ
# そ、それは今関係ないだろ！？
327 = "そ、それは今関係ないだろ！？"

# ゆんゆん
# ねえ、めぐみん。\n本気なの？
348 = "ねえ、めぐみん。\\n本気なの？"

# めぐみん
# 当たり前です。\n冗談でこんなこと言いませんよ。
389 = "当たり前です。\\n冗談でこんなこと言いませんよ。"

# ゆんゆん
# だったら……\n私、パーティーには入りません。\nせっかく誘ってくれたのに、すみません。
334 = "だったら……\\n私、パーティーには入りません。\\nせっかく誘ってくれたのに、すみません。"

# めぐみん
# はあ？\nどうして身を引こうとしてるんですか？
350 = "はあ？\\nどうして身を引こうとしてるんですか？"

# めぐみん
# もしかして哀れみですか？\nゆんゆんごときが、この私に？
356 = "もしかして哀れみですか？\\nゆんゆんごときが、この私に？"

# めぐみん
# 本当は嬉しいのでしょう？\nこんなチャンス、二度とないかもしれませんよ？\nぼっちに仲間ができてよかったですね。
394 = "本当は嬉しいのでしょう？\\nこんなチャンス、二度とないかもしれませんよ？\\nぼっちに仲間ができてよかったですね。"

# めぐみん
# おめでとうございます。\nほら、嬉しいなら素直に喜んだらどうです？\n勝ち誇りたいのでしょう？
324 = "おめでとうございます。\\nほら、嬉しいなら素直に喜んだらどうです？\\n勝ち誇りたいのでしょう？"

# カズマ
# おい、めぐみん！
321 = "おい、めぐみん！"

# ゆんゆん
# な、何よっ！\nめぐみんこそ素直になりなさいよ！\n私は入らないって言ってるでしょ！？
345 = "な、何よっ！\\nめぐみんこそ素直になりなさいよ！\\n私は入らないって言ってるでしょ！？"

# めぐみん
# 情けなどかけられたくありませんよ！
391 = "情けなどかけられたくありませんよ！"

# ゆんゆん
# 変な意地張って！\nめぐみんって昔からそうよね！
384 = "変な意地張って！\\nめぐみんって昔からそうよね！"

# めぐみん
# ぼっちが、何を偉そうに\n人を語ってくれてるんですか！？
353 = "ぼっちが、何を偉そうに\\n人を語ってくれてるんですか！？"

# アクア
# ちょ、ちょっと！\nどうにかなさいよ、カズマ。
336 = "ちょ、ちょっと！\\nどうにかなさいよ、カズマ。"

# カズマ
# 俺かよ！？\n元はと言えばアクアが誘ったからだろ？
376 = "俺かよ！？\\n元はと言えばアクアが誘ったからだろ？"

# アクア
# いいから、頼んだわよ！
316 = "いいから、頼んだわよ！"

# カズマ（Ｍ）
# display as カズマ
# （まったく、人に嫌な役を押しつけやがって！\n　でも確かに、ここはなんとか収めないと\n　マズイよな）
442 = "（まったく、人に嫌な役を押しつけやがって！\\n　でも確かに、ここはなんとか収めないと\\n　マズイよな）"

# カズマ
# おい、２人とも。\nちょっと落ち着け。\nここで言い合っても解決しないぞ。
322 = "おい、２人とも。\\nちょっと落ち着け。\\nここで言い合っても解決しないぞ。"

# めぐみん
# なんですか？\nじゃあ、どうしろというのですか？\n私は譲る気はありませんからね。
346 = "なんですか？\\nじゃあ、どうしろというのですか？\\n私は譲る気はありませんからね。"

# ゆんゆん
# わ、私だって！
361 = "わ、私だって！"

# カズマ
# わかってる。\nお互いの意見が衝突しているのなら、\nとことんまでやりあえばいい。
362 = "わかってる。\\nお互いの意見が衝突しているのなら、\\nとことんまでやりあえばいい。"

# めぐみん
# はあ？\nカズマ、言ってることが矛盾していますよ？
351 = "はあ？\\nカズマ、言ってることが矛盾していますよ？"

# カズマ
# だから、言い合う以外の方法で\n解決しろってことだよ。\nつまり、こういうときこそ勝負だ！
333 = "だから、言い合う以外の方法で\\n解決しろってことだよ。\\nつまり、こういうときこそ勝負だ！"

# めぐみん＆ゆんゆん
# ……え？　勝負？
310 = "……え？　勝負？"

[selections]
380 = "別に、勝手に決めてくれよ"
392 = "戦力アップは歓迎だ"
377 = "俺はいいけど、めぐみんはどうだろ？"
