# root_b16.txt.scn

[info]
0 = ""

[characters]
196 = "カズマ"
192 = "めぐみん"
198 = "カズマ（Ｍ）"

[character_subs]
# 196 = "カズマ"

[script]
# lines: 71

# カズマ
# 君、男のベッドに入ってくるなんて、\n羞恥心というものがないのかね。
205 = "君、男のベッドに入ってくるなんて、\\n羞恥心というものがないのかね。"

# めぐみん
# これは、私が寝る予定だったベッドです。\n非常識なのはカズマの方じゃないですか。
159 = "これは、私が寝る予定だったベッドです。\\n非常識なのはカズマの方じゃないですか。"

# カズマ
# あー、もう狭いんだから動くな！
151 = "あー、もう狭いんだから動くな！"

# めぐみん
# そうやって背中をくっつけてこないでください！
166 = "そうやって背中をくっつけてこないでください！"

# カズマ
# 文句があるなら床で寝ろ！
206 = "文句があるなら床で寝ろ！"

# めぐみん
# か弱い女の子を床に放り出すとは、\n本当にクズですね、カズマは。
155 = "か弱い女の子を床に放り出すとは、\\n本当にクズですね、カズマは。"

# カズマ
# か弱い？
156 = "か弱い？"

# めぐみん
# なんです？
181 = "なんです？"

# カズマ
# か弱い？
# 156 = "か弱い？"

# めぐみん
# はあ、もう疲れるからそういうのは\nやめてください。
185 = "はあ、もう疲れるからそういうのは\\nやめてください。"

# カズマ
# すんません。
161 = "すんません。"

# めぐみん
# ほら、また背中があたりましたよ！
186 = "ほら、また背中があたりましたよ！"

# めぐみん
# またやったら、\nあることないこと言いふらしますからね！
188 = "またやったら、\\nあることないこと言いふらしますからね！"

# カズマ
# せめてあることだけにしてくれませんかね！？
162 = "せめてあることだけにしてくれませんかね！？"

# めぐみん
# はあ、どうしてこんなことになって\nしまったんでしょう。
184 = "はあ、どうしてこんなことになって\\nしまったんでしょう。"

# カズマ
# ベッドはひとつしかないのに、\nめぐみんが先に寝るって譲らないからだろ。
200 = "ベッドはひとつしかないのに、\\nめぐみんが先に寝るって譲らないからだろ。"

# めぐみん
# そうではなく、どうしてこんな所で\n幽霊に怯えながら過ごさないといけないのかって\n意味です。
165 = "そうではなく、どうしてこんな所で\\n幽霊に怯えながら過ごさないといけないのかって\\n意味です。"

# カズマ
# めぐみんが借金を背負ったからじゃないか？
193 = "めぐみんが借金を背負ったからじゃないか？"

# めぐみん
# バニルの言い分は、正直詐欺だと思うのです。
199 = "バニルの言い分は、正直詐欺だと思うのです。"

# カズマ
# 確かにちょっとひどいな。
209 = "確かにちょっとひどいな。"

# めぐみん
# それに、よくよく考えたら\n１０万エリスぐらいクエストをちょっと頑張れば\n簡単に稼げますしね。
170 = "それに、よくよく考えたら\\n１０万エリスぐらいクエストをちょっと頑張れば\\n簡単に稼げますしね。"

# カズマ
# 言うな、むなしくなる。
211 = "言うな、むなしくなる。"

# めぐみん
# というわけで、\nバニルの提案を安請け合いしたカズマが悪いという\n結論に行きつきました。
178 = "というわけで、\\nバニルの提案を安請け合いしたカズマが悪いという\\n結論に行きつきました。"

# カズマ
# 俺のせいかよ。
203 = "俺のせいかよ。"

# めぐみん
# だって、実際そうじゃないですか。
173 = "だって、実際そうじゃないですか。"

# めぐみん
# そもそも、呪われている可能性のある物を\n拾って売ろうという時点で問題ですよ。
168 = "そもそも、呪われている可能性のある物を\\n拾って売ろうという時点で問題ですよ。"

# めぐみん
# あの時、欲を張らずに捨てていれば、\nこんな目にあうこともなかったんですよ？
149 = "あの時、欲を張らずに捨てていれば、\\nこんな目にあうこともなかったんですよ？"

# カズマ
# めぐみんだって強く反対しなかっただろ？
194 = "めぐみんだって強く反対しなかっただろ？"

# めぐみん
# 言っても無駄だと諦めただけです。
212 = "言っても無駄だと諦めただけです。"

# めぐみん
# それにしても、カズマは\nどうしてこうも呪いに縁があるんです？
171 = "それにしても、カズマは\\nどうしてこうも呪いに縁があるんです？"

# めぐみん
# 運のステータスが高いんですよね？\nまったくそうは思えませんよ。
213 = "運のステータスが高いんですよね？\\nまったくそうは思えませんよ。"

# カズマ
# こんな問題児だらけのパーティーを組んでる時点で\n運がいいなんて自分でも思えないしなぁ。
160 = "こんな問題児だらけのパーティーを組んでる時点で\\n運がいいなんて自分でも思えないしなぁ。"

# めぐみん
# 上位職だけを集めておいて何を言うんですか。
201 = "上位職だけを集めておいて何を言うんですか。"

# めぐみん
# むしろ、私を仲間にしたことによって\nカズマの人生の運全てを\n使い果たしてしまったのかもしれませんね。
191 = "むしろ、私を仲間にしたことによって\\nカズマの人生の運全てを\\n使い果たしてしまったのかもしれませんね。"

# カズマ
# うわぁ～。\n俺はなんてことに運を使っちまったんだぁ～。
152 = "うわぁ～。\\n俺はなんてことに運を使っちまったんだぁ～。"

# めぐみん
# な、なにおう！\n私が仲間では不服だと言うのですか！？\n明らかにお買い得じゃないですか！
180 = "な、なにおう！\\n私が仲間では不服だと言うのですか！？\\n明らかにお買い得じゃないですか！"

# めぐみん
# 上級職のアークウィザードであり、\n最強の爆裂魔法を操れるのですよ？\nこれ以上のお買い得ポイントがありますか？
202 = "上級職のアークウィザードであり、\\n最強の爆裂魔法を操れるのですよ？\\nこれ以上のお買い得ポイントがありますか？"

# カズマ
# 確かにこれ以上のポイントはないな、\n主に悪い方に。
208 = "確かにこれ以上のポイントはないな、\\n主に悪い方に。"

# めぐみん
# ……カズマはもう少し\n私のありがたみを理解するべきです。
147 = "……カズマはもう少し\\n私のありがたみを理解するべきです。"

# カズマ
# そうだな、努力する。
164 = "そうだな、努力する。"

# めぐみん
# …………。
145 = "…………。"

# カズマ
# …………。
# 145 = "…………。"

# めぐみん
# カズマ、起きてますか？
197 = "カズマ、起きてますか？"

# カズマ
# ああ。
148 = "ああ。"

# めぐみん
# まだ話をしたいんですけど、いいですか？
190 = "まだ話をしたいんですけど、いいですか？"

# カズマ
# ああ。
# 148 = "ああ。"

# めぐみん
# 先程の、ウエディングドレスを着た骸骨なのですが。
204 = "先程の、ウエディングドレスを着た骸骨なのですが。"

# カズマ（Ｍ）
# display as カズマ
# （よりよって、そんな話かよ）
215 = "（よりよって、そんな話かよ）"

# めぐみん
# あれっていったいなんなんでしょう。
150 = "あれっていったいなんなんでしょう。"

# めぐみん
# やはり、あれが教会に\n呪いをかけた元凶……なのでしょうか？
195 = "やはり、あれが教会に\\n呪いをかけた元凶……なのでしょうか？"

# カズマ
# おいおい、急にどうした？\n考えるだけ無駄なんじゃなかったか？
154 = "おいおい、急にどうした？\\n考えるだけ無駄なんじゃなかったか？"

# めぐみん
# ですが、実際、あんな風に\n出てこられては……\n考えないわけにはいきませんよ。
176 = "ですが、実際、あんな風に\\n出てこられては……\\n考えないわけにはいきませんよ。"

# カズマ
# うーん、そうだなぁ。\n確証はないけど、状況から考えれば\n元凶はあれだろうなぁ。
153 = "うーん、そうだなぁ。\\n確証はないけど、状況から考えれば\\n元凶はあれだろうなぁ。"

# めぐみん
# こうなってくると、カズマの推測も\nあながち的外れではないような気がしますね。
157 = "こうなってくると、カズマの推測も\\nあながち的外れではないような気がしますね。"

# めぐみん
# この教会で式を挙げる予定だった人に\n不幸があった――
158 = "この教会で式を挙げる予定だった人に\\n不幸があった――"

# めぐみん
# という線が濃い、と私は思うのですが。
179 = "という線が濃い、と私は思うのですが。"

# カズマ
# でもさ、それで教会を呪うか？\nそれじゃただの逆恨みじゃないか。
177 = "でもさ、それで教会を呪うか？\\nそれじゃただの逆恨みじゃないか。"

# めぐみん
# 私もそうは思いますが、\n他にこれと言った理由が見当たりません。
210 = "私もそうは思いますが、\\n他にこれと言った理由が見当たりません。"

# カズマ
# はあ……。\nあの骸骨から話が聞ければ早いんだけど。
182 = "はあ……。\\nあの骸骨から話が聞ければ早いんだけど。"

# めぐみん
# そ、そんなの無理です！\n第一、話が通じるとは思えませんよ！
163 = "そ、そんなの無理です！\\n第一、話が通じるとは思えませんよ！"

# カズマ
# だよなぁ。\nこっちからはどうにもできないよな。
174 = "だよなぁ。\\nこっちからはどうにもできないよな。"

# カズマ
# ま、明日までの辛抱だ。\n明日になれば助けも来るさ。
187 = "ま、明日までの辛抱だ。\\n明日になれば助けも来るさ。"

# めぐみん
# 本当にそうでしょうか？\nもし明日も、明後日も助けが\n来なかったら……どうしましょう？
207 = "本当にそうでしょうか？\\nもし明日も、明後日も助けが\\n来なかったら……どうしましょう？"

# カズマ
# その時は結婚式を挙げるしかないだろ。
167 = "その時は結婚式を挙げるしかないだろ。"

# めぐみん
# また軽く言いますね……。\nカズマにとって結婚とは、\nそんなに簡単なものなのですか？
189 = "また軽く言いますね……。\\nカズマにとって結婚とは、\\nそんなに簡単なものなのですか？"

# カズマ
# そりゃ本物の結婚となると話は違うけど、\nただのフリなんだ。\n難しく考えるようなことか？
169 = "そりゃ本物の結婚となると話は違うけど、\\nただのフリなんだ。\\n難しく考えるようなことか？"

# めぐみん
# はあ……。\n男性とはとことん単純なんですね。
183 = "はあ……。\\n男性とはとことん単純なんですね。"

# めぐみん
# って！\nちょっと、また背中が当たってますよ！？
175 = "って！\\nちょっと、また背中が当たってますよ！？"

# カズマ
# だから仕方がないだろ？\n背中が触れるくらい大目に見ろ。
172 = "だから仕方がないだろ？\\n背中が触れるくらい大目に見ろ。"

# めぐみん
# ……わかりましたけど、だけど、\nそれ以上は絶対に触れないでください！
146 = "……わかりましたけど、だけど、\\nそれ以上は絶対に触れないでください！"

# カズマ（Ｍ）
# display as カズマ
# （はいはい。\n　あることないこと噂されたら\n　たまったもんじゃないしな）
214 = "（はいはい。\\n　あることないこと噂されたら\\n　たまったもんじゃないしな）"

