# root_f17.txt.scn

[info]
0 = ""

[characters]
212 = "カズマ"
211 = "ウィズ"
213 = "カズマ（Ｍ）"
214 = "ルナ"

[character_subs]
# 212 = "カズマ"

[script]
# lines: 55

# カズマ
# なあ、ウィズ。\nギルドに何か用があるのか？
203 = "なあ、ウィズ。\\nギルドに何か用があるのか？"

# ウィズ
# 私に来た依頼の１つが、\nギルドからのものなんですよ。
242 = "私に来た依頼の１つが、\\nギルドからのものなんですよ。"

# カズマ
# あれ？　もしかして今回の件って、\nクエストが出てる？
179 = "あれ？　もしかして今回の件って、\\nクエストが出てる？"

# カズマ（Ｍ）
# display as カズマ
# （だったらアクアが受けててもおかしくないな）
248 = "（だったらアクアが受けててもおかしくないな）"

# ウィズ
# いえ、昨夜はまだクエストが出るほどの\n騒ぎではありませんでしたから、あくまでも\n私個人への依頼です。
181 = "いえ、昨夜はまだクエストが出るほどの\\n騒ぎではありませんでしたから、あくまでも\\n私個人への依頼です。"

# カズマ
# というか、なんでウィズに依頼が来るんだよ。\nここに来る冒険者の中には、\nプリーストだっているだろ。
200 = "というか、なんでウィズに依頼が来るんだよ。\\nここに来る冒険者の中には、\\nプリーストだっているだろ。"

# ウィズ
# 冒険者の方達は、\n基本的に報酬が発生しないと動きませんからね。
216 = "冒険者の方達は、\\n基本的に報酬が発生しないと動きませんからね。"

# ウィズ
# それに、ギルドとして冒険者個人に依頼を回すのは\n問題があるのかと。
191 = "それに、ギルドとして冒険者個人に依頼を回すのは\\n問題があるのかと。"

# カズマ（Ｍ）
# display as カズマ
# （確かに俺たちに来た洞窟調査の依頼も\n　内々にって話だったもんな）
252 = "（確かに俺たちに来た洞窟調査の依頼も\\n　内々にって話だったもんな）"

# ウィズ
# その点私は、冒険者の資格こそ持てど、\n今はもう個人商店の店主でしかありませんので。
188 = "その点私は、冒険者の資格こそ持てど、\\n今はもう個人商店の店主でしかありませんので。"

# ルナ
# あっ！　ウィズさん！
175 = "あっ！　ウィズさん！"

# ウィズ
# この度はご依頼ありがとうございました。\nそれで、今夜はどうです？
185 = "この度はご依頼ありがとうございました。\\nそれで、今夜はどうです？"

# ルナ
# あ、あの、その件なのですが……。
171 = "あ、あの、その件なのですが……。"

# ウィズ
# どうかしました？
201 = "どうかしました？"

# ルナ
# 実は、先ほどアクアさんが\nこちらにいらっしゃって。
219 = "実は、先ほどアクアさんが\\nこちらにいらっしゃって。"

# カズマ（Ｍ）
# display as カズマ
# （アクアが……）
249 = "（アクアが……）"

# ルナ
# それで、突然ぴかぴか光る魔法を使って、\n立ち去っていってしまったんです。
190 = "それで、突然ぴかぴか光る魔法を使って、\\n立ち去っていってしまったんです。"

# ルナ
# あれってもしかして……。
178 = "あれってもしかして……。"

# ウィズ
# ええ、除霊ですよ。
184 = "ええ、除霊ですよ。"

# ルナ
# やっぱりそうだったんですね。
209 = "やっぱりそうだったんですね。"

# ウィズ
# 霊の気配は感じません。\nさすがアクア様、完璧な除霊です。
245 = "霊の気配は感じません。\\nさすがアクア様、完璧な除霊です。"

# カズマ
# いやいや、そこは怒る所だろ。
182 = "いやいや、そこは怒る所だろ。"

# ウィズ
# どうしてですか？
202 = "どうしてですか？"

# カズマ
# だって、仕事を横取りされたと同じじゃないか。
196 = "だって、仕事を横取りされたと同じじゃないか。"

# ウィズ
# 確かにそういう考え方もできますね。
241 = "確かにそういう考え方もできますね。"

# ウィズ
# でもギルドとしては、\n少しでも早く除霊をして貰えて\n助かったのでは？
199 = "でもギルドとしては、\\n少しでも早く除霊をして貰えて\\n助かったのでは？"

# ルナ
# はい、それはもう！
205 = "はい、それはもう！"

# ウィズ
# だったら、それでいいじゃないですか。
195 = "だったら、それでいいじゃないですか。"

# カズマ（Ｍ）
# display as カズマ
# （人が良すぎるよ、ウィズ……）
251 = "（人が良すぎるよ、ウィズ……）"

# ウィズ
# ですが、昨日今日と、\nずいぶん霊が騒がしいようです。
197 = "ですが、昨日今日と、\\nずいぶん霊が騒がしいようです。"

# ウィズ
# もしかしたら、またどこかから\n流れてくるかもしれません。
207 = "もしかしたら、またどこかから\\n流れてくるかもしれません。"

# ルナ
# そんな……！\nなんとかなりませんか？
193 = "そんな……！\\nなんとかなりませんか？"

# ウィズ
# ええ、方法はあります。\nカズマさん、すみませんが\nバッグを開けてもらえませんか？
183 = "ええ、方法はあります。\\nカズマさん、すみませんが\\nバッグを開けてもらえませんか？"

# カズマ
# ああ、わかった。
174 = "ああ、わかった。"

# カズマ（Ｍ）
# display as カズマ
# （……なんだ？\n　瓶がいっぱい入ってる？\n　なるほど、こりゃ重いわけだ）
246 = "（……なんだ？\\n　瓶がいっぱい入ってる？\\n　なるほど、こりゃ重いわけだ）"

# ウィズ
# それを１つ、床に置いてください。
192 = "それを１つ、床に置いてください。"

# カズマ
# ああ、この辺か？
173 = "ああ、この辺か？"

# ウィズ
# ありがとうございます。\nでは、こちらをどうぞ。
177 = "ありがとうございます。\\nでは、こちらをどうぞ。"

# ルナ
# これは？
186 = "これは？"

# ウィズ
# 聖水です。\n一晩くらいなら、これで霊を避けられますので\n建物の周りに撒いてみて下さい。
243 = "聖水です。\\n一晩くらいなら、これで霊を避けられますので\\n建物の周りに撒いてみて下さい。"

# ルナ
# あ、ありがとうございます！
172 = "あ、ありがとうございます！"

# カズマ（Ｍ）
# display as カズマ
# （あ、なるほど。\n　バッグの中身は聖水だったのか。\n　そりゃ、持ちたくないよな）
247 = "（あ、なるほど。\\n　バッグの中身は聖水だったのか。\\n　そりゃ、持ちたくないよな）"

# ルナ
# でも、この１本だけで足りますか？\nギルドの建物の回りとなると、かなり広くて。
198 = "でも、この１本だけで足りますか？\\nギルドの建物の回りとなると、かなり広くて。"

# ウィズ
# 建物の四隅に少し多め、\n残りは入口や窓みたいな開くところの下を\n軽く濡らす感じで大丈夫ですよ。
222 = "建物の四隅に少し多め、\\n残りは入口や窓みたいな開くところの下を\\n軽く濡らす感じで大丈夫ですよ。"

# ウィズ
# もし心配なら、少し残して手元に置いてください。
208 = "もし心配なら、少し残して手元に置いてください。"

# ルナ
# は、はい、わかりました。
204 = "は、はい、わかりました。"

# ウィズ
# それじゃ、私たちは次の依頼がありますので。
189 = "それじゃ、私たちは次の依頼がありますので。"

# カズマ
# その前にお姉さん、\nちょっと聞きたいことがあるんですけど。
187 = "その前にお姉さん、\\nちょっと聞きたいことがあるんですけど。"

# ルナ
# はい、なんでしょう。
206 = "はい、なんでしょう。"

# カズマ
# アクアのやつ、金品を要求したりしませんでした？
210 = "アクアのやつ、金品を要求したりしませんでした？"

# ルナ
# いえ、それはありませんよ。\nあ、ただ……。
180 = "いえ、それはありませんよ。\\nあ、ただ……。"

# カズマ
# ただ？
194 = "ただ？"

# ルナ
# 除霊をした後に、\nチラチラと私を見ていましたね。
244 = "除霊をした後に、\\nチラチラと私を見ていましたね。"

# ルナ
# あの目配せはなんだったのかしら。
176 = "あの目配せはなんだったのかしら。"

# カズマ（Ｍ）
# display as カズマ
# （不審だ、不審すぎる。\n　あいつはいったい何をたくらんでるんだ……）
250 = "（不審だ、不審すぎる。\\n　あいつはいったい何をたくらんでるんだ……）"

