# root_b22.txt.scn

[info]
0 = ""

[characters]
349 = "カズマ（Ｍ）"
350 = "ダクネス"
341 = "アクア"
346 = "カズマ"
339 = "めぐみん"
344 = "ウィズ"

[character_subs]
# 346 = "カズマ"

[script]
# lines: 89

# カズマ（Ｍ）
# display as カズマ
# （その日、夜遅くに戻った俺達を\n　心配そうな顔をしたダクネスとアクアが\n　出迎えてくれた）
393 = "（その日、夜遅くに戻った俺達を\\n　心配そうな顔をしたダクネスとアクアが\\n　出迎えてくれた）"

# カズマ（Ｍ）
# display as カズマ
# （当然、なにがあったのかと問い詰められたけど\n　疲れ切っていた俺達に説明する余裕はなくて……）
400 = "（当然、なにがあったのかと問い詰められたけど\\n　疲れ切っていた俺達に説明する余裕はなくて……）"

# カズマ（Ｍ）
# display as カズマ
# （一晩ぐっすり寝た後、朝食の時に話をしたら\n　いつの間にか、その教会に行ってみようという\n　流れになってしまった）
397 = "（一晩ぐっすり寝た後、朝食の時に話をしたら\\n　いつの間にか、その教会に行ってみようという\\n　流れになってしまった）"

# ダクネス
# 帰りが遅いと心配していたが、\nまさか、そんなことになっていようとはな。
362 = "帰りが遅いと心配していたが、\\nまさか、そんなことになっていようとはな。"

# アクア
# ホント、カズマは厄介事ばかり呼び寄せるわね。\n運のパラメーター、間違ってるんじゃない？\n一度、調べてもらったら？
354 = "ホント、カズマは厄介事ばかり呼び寄せるわね。\\n運のパラメーター、間違ってるんじゃない？\\n一度、調べてもらったら？"

# カズマ
# お前に言われたくねーよ！！
300 = "お前に言われたくねーよ！！"

# ダクネス
# しかし、エリス様の教会に呪いをかけるとは\nなんという不届き者だ。\n見つけてとっちめてやらねば。
305 = "しかし、エリス様の教会に呪いをかけるとは\\nなんという不届き者だ。\\n見つけてとっちめてやらねば。"

# めぐみん
# いえ、呪い自体はもう解けていますので\nその必要はないと思います。
292 = "いえ、呪い自体はもう解けていますので\\nその必要はないと思います。"

# カズマ
# でないと、俺達がこうして脱出できてないしな。
319 = "でないと、俺達がこうして脱出できてないしな。"

# アクア
# ところで、どうやって呪いを解いたの？\nカズマもめぐみんも、浄化魔法が使えないわよね。
321 = "ところで、どうやって呪いを解いたの？\\nカズマもめぐみんも、浄化魔法が使えないわよね。"

# カズマ
# 前の指輪の件と同じだよ。\n無念を晴らせば呪いが解ける、ってことだ。
356 = "前の指輪の件と同じだよ。\\n無念を晴らせば呪いが解ける、ってことだ。"

# ダクネス
# ほう、どうやって無念を晴らしたんだ？\n聞くところによると、厄介な呪いだったのだろう？
333 = "ほう、どうやって無念を晴らしたんだ？\\n聞くところによると、厄介な呪いだったのだろう？"

# めぐみん
# そ、それは……。
309 = "そ、それは……。"

# カズマ
# まあ、別にどうだっていいだろ？
338 = "まあ、別にどうだっていいだろ？"

# めぐみん
# そ、そうですよ！\nこうして無事だったんです。\n細かいことなんて気にすべきではありません。
308 = "そ、そうですよ！\\nこうして無事だったんです。\\n細かいことなんて気にすべきではありません。"

# ダクネス
# ん？　２人とも顔が赤くないか？
340 = "ん？　２人とも顔が赤くないか？"

# カズマ
# あ、赤くなんてないって！\nなに言ってんだよ、ダクネス。
284 = "あ、赤くなんてないって！\\nなに言ってんだよ、ダクネス。"

# めぐみん
# そうですよ。\nおかしなことを言わないでください。
312 = "そうですよ。\\nおかしなことを言わないでください。"

# ダクネス
# ……そんなにおかしなことを言っただろうか？
281 = "……そんなにおかしなことを言っただろうか？"

# アクア
# まあ、カズマにどうにかできる時点で\n大した呪いじゃなかったのよ。
337 = "まあ、カズマにどうにかできる時点で\\n大した呪いじゃなかったのよ。"

# カズマ
# そんなことねーよ！\n本当に大変だったんだからな？
313 = "そんなことねーよ！\\n本当に大変だったんだからな？"

# カズマ
# 呪いを解くまでの遠い道のり、\n最後には――
359 = "呪いを解くまでの遠い道のり、\\n最後には――"

# めぐみん
# はっ！　カズマ！\nそれ以上は言わせませんよ？\n秘密だと約束しましたよね！？
330 = "はっ！　カズマ！\\nそれ以上は言わせませんよ？\\n秘密だと約束しましたよね！？"

# アクア
# あら？　なにが秘密なのかしら？
290 = "あら？　なにが秘密なのかしら？"

# カズマ（Ｍ）
# display as カズマ
# （うわぁ……。\n　そんな言い方したら食いつかれるに\n　決まってるだろ）
392 = "（うわぁ……。\\n　そんな言い方したら食いつかれるに\\n　決まってるだろ）"

# めぐみん
# た、ただ、散々な夜だっただけですよ。\nそれ以上でもそれ以下でもありません！
314 = "た、ただ、散々な夜だっただけですよ。\\nそれ以上でもそれ以下でもありません！"

# カズマ
# そ、そうそう。\nだよな、めぐみん。
307 = "そ、そうそう。\\nだよな、めぐみん。"

# めぐみん
# …………。
280 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （またか。\n　どうも、教会を出てから\n　めぐみんの機嫌が悪いんだよな）
395 = "（またか。\\n　どうも、教会を出てから\\n　めぐみんの機嫌が悪いんだよな）"

# カズマ（Ｍ）
# display as カズマ
# （俺の顔を見るたび面白くなさそうな顔をするし。\n　でも、理由が全く思いつかない。\n　本人に聞いてもよけい不機嫌になるだけだしなぁ）
398 = "（俺の顔を見るたび面白くなさそうな顔をするし。\\n　でも、理由が全く思いつかない。\\n　本人に聞いてもよけい不機嫌になるだけだしなぁ）"

# カズマ（Ｍ）
# display as カズマ
# （言いたいことがあるなら、\n　はっきり言えばいいのに）
402 = "（言いたいことがあるなら、\\n　はっきり言えばいいのに）"

# めぐみん
# とにかく、なんでもありません。\nなにもありませんでしたからね！
322 = "とにかく、なんでもありません。\\nなにもありませんでしたからね！"

# ダクネス
# まあ、そこまで言うなら……。\nこうして無事でいるんだ、それでよしとしよう。
336 = "まあ、そこまで言うなら……。\\nこうして無事でいるんだ、それでよしとしよう。"

# アクア
# でも、あからさまにあやしいわよ。\n本当はなにかあったんじゃないの？
320 = "でも、あからさまにあやしいわよ。\\n本当はなにかあったんじゃないの？"

# カズマ
# だから、なにもねーって！
316 = "だから、なにもねーって！"

# アクア
# うーん、ますますあやしい。
294 = "うーん、ますますあやしい。"

# カズマ（Ｍ）
# display as カズマ
# （……言えるわけがない。\n　フリとはいえ結婚式を挙げたなんて）
389 = "（……言えるわけがない。\\n　フリとはいえ結婚式を挙げたなんて）"

# カズマ（Ｍ）
# display as カズマ
# （もしそんなことを知られた日には、\n　しばらくいじられ続けることになる！）
396 = "（もしそんなことを知られた日には、\\n　しばらくいじられ続けることになる！）"

# ダクネス
# 教会にかけられた呪い、か……。
363 = "教会にかけられた呪い、か……。"

# カズマ
# ダクネス？
351 = "ダクネス？"

# ダクネス
# ああ、いや。\nそれよりも、件の教会はまだなのか？
286 = "ああ、いや。\\nそれよりも、件の教会はまだなのか？"

# カズマ
# ああ、もうちょっと先だ。
287 = "ああ、もうちょっと先だ。"

# カズマ
# ついたぜ、ここだ。
318 = "ついたぜ、ここだ。"

# ダクネス
# ほう、なかなか立派な教会だな。\nもっとおどろおどろしいものかと思っていた。
334 = "ほう、なかなか立派な教会だな。\\nもっとおどろおどろしいものかと思っていた。"

# カズマ
# ああ、わかるわかる。\nやっぱ呪いの教会ってなると\nそんなイメージだよな。
288 = "ああ、わかるわかる。\\nやっぱ呪いの教会ってなると\\nそんなイメージだよな。"

# アクア
# あ～、これは……\n完全には浄化できてないわね。
291 = "あ～、これは……\\n完全には浄化できてないわね。"

# カズマ
# え？　マジか？
298 = "え？　マジか？"

# めぐみん
# ど、どういうことです？
323 = "ど、どういうことです？"

# アクア
# カズマが浄化したのは１人だけ。\nまだまだ他にもいるのよ。
348 = "カズマが浄化したのは１人だけ。\\nまだまだ他にもいるのよ。"

# めぐみん
# ……まだまだいるって、\nそんなにたくさん、ですか？
282 = "……まだまだいるって、\\nそんなにたくさん、ですか？"

# アクア
# ええ、びっくりするほどいっぱい。
295 = "ええ、びっくりするほどいっぱい。"

# カズマ
# ええええ……マジかよ……。
296 = "ええええ……マジかよ……。"

# ダクネス
# ここに集まってる霊には、\nなにか共通点があるのか？
303 = "ここに集まってる霊には、\\nなにか共通点があるのか？"

# アクア
# ちょっと待って、話を聞いてみるわ。\nんー……。
317 = "ちょっと待って、話を聞いてみるわ。\\nんー……。"

# アクア
# ……行き遅れたまま死んだ女性の霊が\n救いを求めて集まってきてるのね。
283 = "……行き遅れたまま死んだ女性の霊が\\n救いを求めて集まってきてるのね。"

# ダクネス
# そ、そんな理由が？\nなんというか、切ない話……。
311 = "そ、そんな理由が？\\nなんというか、切ない話……。"

# ダクネス
# はっ！\nおい、気をつけろ！\nなにかの気配が――
329 = "はっ！\\nおい、気をつけろ！\\nなにかの気配が――"

# ダクネス
# うわああっ！？
293 = "うわああっ！？"

# めぐみん
# きゃあああ！
301 = "きゃあああ！"

# アクア
# な、なに、なんなの！？
326 = "な、なに、なんなの！？"

# カズマ
# どうした、３人とも！？
325 = "どうした、３人とも！？"

# ダクネス
# こ、これは……。
302 = "こ、これは……。"

# めぐみん
# ま、またですか！？
335 = "ま、またですか！？"

# アクア
# へえ……。\n女神の私に呪いをかけるなんて、\nそうとう根深い未練のようね。
332 = "へえ……。\\n女神の私に呪いをかけるなんて、\\nそうとう根深い未練のようね。"

# カズマ
# ど、どうするんだよ、これ！？
324 = "ど、どうするんだよ、これ！？"

# アクア
# 決まってるでしょ？\nまとめて浄化してやるわ。
364 = "決まってるでしょ？\\nまとめて浄化してやるわ。"

# ダクネス
# アクア、ちょっと待ってくれないか。\nこの霊はみな、未練があるのだろう？
342 = "アクア、ちょっと待ってくれないか。\\nこの霊はみな、未練があるのだろう？"

# ダクネス
# このまま思いを遂げさせることもなく\n浄化するのは、あまりに酷だろう。
304 = "このまま思いを遂げさせることもなく\\n浄化するのは、あまりに酷だろう。"

# ダクネス
# なんとか、彼女たちの願いを叶えてやることは\nできないだろうか？
327 = "なんとか、彼女たちの願いを叶えてやることは\\nできないだろうか？"

# めぐみん
# じょ、じょ、冗談じゃありませんよ！
306 = "じょ、じょ、冗談じゃありませんよ！"

# めぐみん
# アクア、一刻も早く浄化を！\n何度も結婚式など挙げたくありませんっ！
343 = "アクア、一刻も早く浄化を！\\n何度も結婚式など挙げたくありませんっ！"

# カズマ（Ｍ）
# display as カズマ
# （あー……。\n　ついに言っちまったよ……）
391 = "（あー……。\\n　ついに言っちまったよ……）"

# アクア
# 結婚式？\nめぐみんとカズマ、結婚式をして浄化したの？
388 = "結婚式？\\nめぐみんとカズマ、結婚式をして浄化したの？"

# めぐみん
# あっ……。\nち、ちが！　違いますっ！\nそんなことしてませんからっ！
289 = "あっ……。\\nち、ちが！　違いますっ！\\nそんなことしてませんからっ！"

# ダクネス
# おお……！\n好きでもない男との婚姻を強要される！\nなかなかのシチュエーションだっ！
299 = "おお……！\\n好きでもない男との婚姻を強要される！\\nなかなかのシチュエーションだっ！"

# ダクネス
# だ、だが、仕方がないのだ！\nこれも人助け！　甘んじて羞恥に晒されよう！
315 = "だ、だが、仕方がないのだ！\\nこれも人助け！　甘んじて羞恥に晒されよう！"

# めぐみん
# そ、そんなことしなくてもいいんです！\nアクア、早く浄化魔法を！
310 = "そ、そんなことしなくてもいいんです！\\nアクア、早く浄化魔法を！"

# アクア
# えー？\nこのドレス、高値で売れそうじゃない？\n浄化魔法で消すのはもったいないわよ。
297 = "えー？\\nこのドレス、高値で売れそうじゃない？\\n浄化魔法で消すのはもったいないわよ。"

# めぐみん
# はあっ！？\nなにを言って！！
328 = "はあっ！？\\nなにを言って！！"

# カズマ（Ｍ）
# display as カズマ
# （あの女神、本当にブレないな。\n　女神じゃなくて金の亡者じゃねーか）
390 = "（あの女神、本当にブレないな。\\n　女神じゃなくて金の亡者じゃねーか）"

# ウィズ
# ああ……。\n手遅れでしたか。
285 = "ああ……。\\n手遅れでしたか。"

# カズマ
# ウィズ！？\nどうしてここに？
345 = "ウィズ！？\\nどうしてここに？"

# ウィズ
# バニルさんが、これが入り用になるだろうから\n持って行けと。
352 = "バニルさんが、これが入り用になるだろうから\\n持って行けと。"

# カズマ（Ｍ）
# display as カズマ
# （大量の指輪？\n　あいつ、こうなることを見越してたのか！）
399 = "（大量の指輪？\\n　あいつ、こうなることを見越してたのか！）"

# カズマ
# バニルのことだ。\n当然タダじゃないんだよな？
353 = "バニルのことだ。\\n当然タダじゃないんだよな？"

# ウィズ
# ひとつ５０万エリスでいいと。\n私は、ちょっと高すぎるのではと\n言ったのですが。
331 = "ひとつ５０万エリスでいいと。\\n私は、ちょっと高すぎるのではと\\n言ったのですが。"

# カズマ（Ｍ）
# display as カズマ
# （最初からこうなることがわかってて\n　頼んだんだな！？\n　あいつならそれくらいやりかねない！）
401 = "（最初からこうなることがわかってて\\n　頼んだんだな！？\\n　あいつならそれくらいやりかねない！）"

# めぐみん
# カズマぁ～！\nアクアを説得してください、\nあんな恥ずかしい思いはもう嫌です！
347 = "カズマぁ～！\\nアクアを説得してください、\\nあんな恥ずかしい思いはもう嫌です！"

# カズマ（Ｍ）
# display as カズマ
# （はあ……。\n　まったく、なんで俺の周りは\n　こんなにトラブルだらけなんだよ）
394 = "（はあ……。\\n　まったく、なんで俺の周りは\\n　こんなにトラブルだらけなんだよ）"

