# root_e01.txt.scn

[info]
0 = ""

[characters]
504 = "カズマ（Ｍ）"
500 = "ウィズ"
497 = "アクア"
501 = "カズマ"
506 = "ダクネス"
483 = "めぐみん"
486 = "ゆんゆん"

[character_subs]
# 501 = "カズマ"

[script]
# lines: 123

# カズマ（Ｍ）
# display as カズマ
# （指輪騒動から数日。\n　平穏な日々が俺達の元に戻ってきた）
600 = "（指輪騒動から数日。\\n　平穏な日々が俺達の元に戻ってきた）"

# カズマ（Ｍ）
# display as カズマ
# （つまりそれは、\n　日常が戻ってきたということでもあり……）
598 = "（つまりそれは、\\n　日常が戻ってきたということでもあり……）"

# カズマ（Ｍ）
# display as カズマ
# （自分で言うのもなんだが、\n　俺達は相も変わらず自堕落な日々を送っていた）
603 = "（自分で言うのもなんだが、\\n　俺達は相も変わらず自堕落な日々を送っていた）"

# カズマ（Ｍ）
# display as カズマ
# （そんなある日――）
597 = "（そんなある日――）"

# ウィズ
# いらっしゃいませ。\nみなさん、お揃いですね。
443 = "いらっしゃいませ。\\nみなさん、お揃いですね。"

# アクア
# 別に来たくて来たわけじゃないんですけど？\nそれより、お客さんが来たんだから\nお茶くらい出しなさいよ。
515 = "別に来たくて来たわけじゃないんですけど？\\nそれより、お客さんが来たんだから\\nお茶くらい出しなさいよ。"

# ウィズ
# は、はいっ！\nすぐに用意しますっ！
479 = "は、はいっ！\\nすぐに用意しますっ！"

# カズマ
# 待った、ウィズ。\nアクアの言う事なんて放っておいていいって！
526 = "待った、ウィズ。\\nアクアの言う事なんて放っておいていいって！"

# カズマ（Ｍ）
# display as カズマ
# （……ああ、行っちゃったよ。\n　本当にこの駄女神は態度がでかいな）
589 = "（……ああ、行っちゃったよ。\\n　本当にこの駄女神は態度がでかいな）"

# ダクネス
# ん？\nバニルの姿が見えないようだな。
495 = "ん？\\nバニルの姿が見えないようだな。"

# カズマ
# ああ、あいつならアイテムの買い付けだよ。\nこないだここで会ったとき、\nしばらく街を出るって言ってた。
427 = "ああ、あいつならアイテムの買い付けだよ。\\nこないだここで会ったとき、\\nしばらく街を出るって言ってた。"

# ウィズ
# アクア様、お待たせいたしました！\nお召し上がりください。
499 = "アクア様、お待たせいたしました！\\nお召し上がりください。"

# アクア
# んー？\nお茶請けがないんですけど？
494 = "んー？\\nお茶請けがないんですけど？"

# アクア
# あー、それとこれ、ぬるいわ。\n淹れなおしてくれる？
430 = "あー、それとこれ、ぬるいわ。\\n淹れなおしてくれる？"

# ウィズ
# も、申し訳ありません！
485 = "も、申し訳ありません！"

# カズマ
# いい加減にしろ！
434 = "いい加減にしろ！"

# アクア
# いったぁ！
436 = "いったぁ！"

# カズマ
# いつもながら我が物顔だな、お前は。\nウィズ、気にしなくていいぞ。\nアクアにおもてなしなんて必要無いからな。
438 = "いつもながら我が物顔だな、お前は。\\nウィズ、気にしなくていいぞ。\\nアクアにおもてなしなんて必要無いからな。"

# ウィズ
# いえ、いいんですよ。\nこんな風にいつもどおりにできるのは\n平和な証ですし。
435 = "いえ、いいんですよ。\\nこんな風にいつもどおりにできるのは\\n平和な証ですし。"

# ウィズ
# カズマさんも、みなさんも、\nどうぞゆっくりしていってください。
503 = "カズマさんも、みなさんも、\\nどうぞゆっくりしていってください。"

# カズマ
# うーん、じゃあ、\nお言葉に甘えさせてもらおうかな。
446 = "うーん、じゃあ、\\nお言葉に甘えさせてもらおうかな。"

# ダクネス
# ……それはそうと、\n先程から視線を感じるのだが。
423 = "……それはそうと、\\n先程から視線を感じるのだが。"

# めぐみん
# そうですか？\n何も感じませんが。
458 = "そうですか？\\n何も感じませんが。"

# ダクネス
# いや、棚の後ろから\n明らかにこちらを見ているぞ。
441 = "いや、棚の後ろから\\n明らかにこちらを見ているぞ。"

# めぐみん
# 気のせいですよ。\n誰もいないのに視線を感じるなんて\n疲れているのでは？
530 = "気のせいですよ。\\n誰もいないのに視線を感じるなんて\\n疲れているのでは？"

# カズマ（Ｍ）
# display as カズマ
# （相変わらず、めぐみんも徹底してるな、\n　何もそこまで無視しなくても――）
602 = "（相変わらず、めぐみんも徹底してるな、\\n　何もそこまで無視しなくても――）"

# カズマ（Ｍ）
# display as カズマ
# （……おっと。\n　視線の主が耐えきれずに\n　棚の後ろから出てきたぞ）
590 = "（……おっと。\\n　視線の主が耐えきれずに\\n　棚の後ろから出てきたぞ）"

# ゆんゆん
# あ、あれ～？\nもしかしてそこにいるのは、めぐみん？\nこんな所で会うなんて、凄い偶然ね。
425 = "あ、あれ～？\\nもしかしてそこにいるのは、めぐみん？\\nこんな所で会うなんて、凄い偶然ね。"

# めぐみん
# ……え？
422 = "……え？"

# ゆんゆん
# え？　なんで？\nどうして不思議そうな顔をしてるの？
450 = "え？　なんで？\\nどうして不思議そうな顔をしてるの？"

# めぐみん
# はて、どちら様でしょう？
481 = "はて、どちら様でしょう？"

# ゆんゆん
# わ、私よ私っ！\nあなたの永遠のライバル、ゆんゆんよ！
492 = "わ、私よ私っ！\\nあなたの永遠のライバル、ゆんゆんよ！"

# めぐみん
# 永遠のライバル？　ゆんゆん？\n知りませんね。
531 = "永遠のライバル？　ゆんゆん？\\n知りませんね。"

# ゆんゆん
# そんな！？\n紅魔の里の学校で\n一緒に競い合ったで仲でしょう！？
467 = "そんな！？\\n紅魔の里の学校で\\n一緒に競い合ったで仲でしょう！？"

# ゆんゆん
# いつも私が勝負を挑んで負けて、\nその度、お弁当をとられて――
439 = "いつも私が勝負を挑んで負けて、\\nその度、お弁当をとられて――"

# ゆんゆん
# そうよ、めぐみんが\nここまで大きく……はないけど、\n大きくなったのは、私のお弁当のおかげよ！
459 = "そうよ、めぐみんが\\nここまで大きく……はないけど、\\n大きくなったのは、私のお弁当のおかげよ！"

# ゆんゆん
# つまり私がめぐみんを\nここまで立派に育てたんだわ！
468 = "つまり私がめぐみんを\\nここまで立派に育てたんだわ！"

# カズマ（Ｍ）
# display as カズマ
# （えー……何それ……）
595 = "（えー……何それ……）"

# ダクネス
# なるほど。\nつまりゆんゆんが、\nめぐみんの育ての母だったのか。
474 = "なるほど。\\nつまりゆんゆんが、\\nめぐみんの育ての母だったのか。"

# カズマ（Ｍ）
# display as カズマ
# （いやダクネス、その納得はおかしいから）
592 = "（いやダクネス、その納得はおかしいから）"

# めぐみん
# それで？\nそのにゅんにゅんがなんの用です？
462 = "それで？\\nそのにゅんにゅんがなんの用です？"

# ゆんゆん
# ゆんゆんよ！　ゆんゆん！\nいい加減に泣くからね！？
488 = "ゆんゆんよ！　ゆんゆん！\\nいい加減に泣くからね！？"

# めぐみん
# チッ！\n面倒くさいですね。
508 = "チッ！\\n面倒くさいですね。"

# ゆんゆん
# ねえ、今舌打ちした？\n舌打ちした？
476 = "ねえ、今舌打ちした？\\n舌打ちした？"

# めぐみん
# それより、早く話を進めてくれませんか？\nこちらもヒマではないのですよ。
466 = "それより、早く話を進めてくれませんか？\\nこちらもヒマではないのですよ。"

# ゆんゆん
# あ、ごめんね！\nそれじゃ……。
426 = "あ、ごめんね！\\nそれじゃ……。"

# ゆんゆん
# コホン！\nさあ、勝負よめぐみん！\n今日こそどちらが上か決めましょう！
505 = "コホン！\\nさあ、勝負よめぐみん！\\n今日こそどちらが上か決めましょう！"

# めぐみん
# 今日こそもなにも、\nこれまですべて私の圧勝ではないですか。\n言っていて恥ずかしくはないのですか？
510 = "今日こそもなにも、\\nこれまですべて私の圧勝ではないですか。\\n言っていて恥ずかしくはないのですか？"

# ゆんゆん
# そ、それはいつも、めぐみんが\n自分に有利な勝負にするからでしょ？
454 = "そ、それはいつも、めぐみんが\\n自分に有利な勝負にするからでしょ？"

# めぐみん
# それは聞き捨てなりませんね。\n勝負の内容に不満があるなら\n受けなければいいだけのこと。
465 = "それは聞き捨てなりませんね。\\n勝負の内容に不満があるなら\\n受けなければいいだけのこと。"

# めぐみん
# 受けたということは\n勝負の内容に同意したということでしょう。
519 = "受けたということは\\n勝負の内容に同意したということでしょう。"

# めぐみん
# にも関わらず、\n不正があったかのような物言いをするとは\n見苦しいとは思わないのですか？
475 = "にも関わらず、\\n不正があったかのような物言いをするとは\\n見苦しいとは思わないのですか？"

# めぐみん
# 負けを正当化するために文句を言うなど、\n恥知らずのすることです。
583 = "負けを正当化するために文句を言うなど、\\n恥知らずのすることです。"

# ゆんゆん
# うっ……うぅ～……。
444 = "うっ……うぅ～……。"

# カズマ（Ｍ）
# display as カズマ
# （正論だ。\n　正論だけど、めぐみんに問題があるようにしか\n　思えないのは俺だけじゃないよな？）
601 = "（正論だ。\\n　正論だけど、めぐみんに問題があるようにしか\\n　思えないのは俺だけじゃないよな？）"

# ゆんゆん
# わ、わかったわ。\n今のは私が悪かったわよ。\nごめんなさい。
490 = "わ、わかったわ。\\n今のは私が悪かったわよ。\\nごめんなさい。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、謝っちゃうんだ……）
591 = "（ああ、謝っちゃうんだ……）"

# ゆんゆん
# それはそれとして勝負よ、めぐみん！
464 = "それはそれとして勝負よ、めぐみん！"

# めぐみん
# 嫌です。\n面倒くさいです。
524 = "嫌です。\\n面倒くさいです。"

# ゆんゆん
# 面倒くさいって……、\nそんな冷たいことを言わないでよ！
586 = "面倒くさいって……、\\nそんな冷たいことを言わないでよ！"

# めぐみん
# ああ、そうでした。\n実はこの後、クエストに\n向かわなければならないのです。
428 = "ああ、そうでした。\\n実はこの後、クエストに\\n向かわなければならないのです。"

# めぐみん
# ですから、\nゆんゆんの相手をしている暇はありません。
469 = "ですから、\\nゆんゆんの相手をしている暇はありません。"

# アクア
# え？\nクエストなんて受けてた？
449 = "え？\\nクエストなんて受けてた？"

# めぐみん
# アクア……。\nそこは合わせてくださいよ。
498 = "アクア……。\\nそこは合わせてくださいよ。"

# カズマ
# いいじゃないか、勝負くらい受けてやれよ。\nなあ、ダクネスもそう思うだろ？
432 = "いいじゃないか、勝負くらい受けてやれよ。\\nなあ、ダクネスもそう思うだろ？"

# ダクネス
# そうだな、\nさすがに少し可哀想ではないか？
456 = "そうだな、\\nさすがに少し可哀想ではないか？"

# めぐみん
# ２人までそんなことを言うのですか？
605 = "２人までそんなことを言うのですか？"

# カズマ
# それともなにか、負けるのが怖いのか？\nだから勝負から逃げてるのか？
463 = "それともなにか、負けるのが怖いのか？\\nだから勝負から逃げてるのか？"

# めぐみん
# な、なにおう！？\nバカも休み休み言ってください！
473 = "な、なにおう！？\\nバカも休み休み言ってください！"

# カズマ
# それじゃ問題ないな。\n勝負してやれ。
461 = "それじゃ問題ないな。\\n勝負してやれ。"

# めぐみん
# くっ……！\nいいでしょう。\nどうせ結果は変わらないのですから！
452 = "くっ……！\\nいいでしょう。\\nどうせ結果は変わらないのですから！"

# カズマ
# というわけだ。\nよかったな、ゆんゆん。
471 = "というわけだ。\\nよかったな、ゆんゆん。"

# ゆんゆん
# は、はいっ！\nありがとうございます！
478 = "は、はいっ！\\nありがとうございます！"

# めぐみん
# まったく、カズマはゆんゆんに甘いですよ。
482 = "まったく、カズマはゆんゆんに甘いですよ。"

# カズマ
# そうか？\nなんつーか、ゆんゆんって\n手助けしてやりたくなるんだよな。
455 = "そうか？\\nなんつーか、ゆんゆんって\\n手助けしてやりたくなるんだよな。"

# カズマ（Ｍ）
# display as カズマ
# （そう、めぐみんがいじめてるようにしか\n　見えないから……）
596 = "（そう、めぐみんがいじめてるようにしか\\n　見えないから……）"

# ゆんゆん
# 手助けしたくなる……。\nそれって……仲間みたいな……。
528 = "手助けしたくなる……。\\nそれって……仲間みたいな……。"

# カズマ
# ん？　なんだ？
496 = "ん？　なんだ？"

# ゆんゆん
# い、いえ、なんでもないです！\nそれよりですね、カズマさん！
431 = "い、いえ、なんでもないです！\\nそれよりですね、カズマさん！"

# ゆんゆん
# 勝負の内容、カズマさんが決めてくれませんか？\nカズマさんなら不公平のない提案を\nしてくれると思うんです。
517 = "勝負の内容、カズマさんが決めてくれませんか？\\nカズマさんなら不公平のない提案を\\nしてくれると思うんです。"

# カズマ
# 俺はいいけど、めぐみんはそれでいいのか？
514 = "俺はいいけど、めぐみんはそれでいいのか？"

# めぐみん
# 問題ありませんよ。\nどうせ私が勝つのですから。
521 = "問題ありませんよ。\\nどうせ私が勝つのですから。"

# カズマ
# よし、では決めさせてもらおう！\n２人の勝負は――
489 = "よし、では決めさせてもらおう！\\n２人の勝負は――"

# カズマ
# 大食い勝負だ！\nこれならズルをする余地はないから\n完璧に公平だ！
523 = "大食い勝負だ！\\nこれならズルをする余地はないから\\n完璧に公平だ！"

# ゆんゆん
# え、え～と……。
448 = "え、え～と……。"

# めぐみん
# 却下です。\n大食い勝負なんかして、\n太ったらどうするんですか？
518 = "却下です。\\n大食い勝負なんかして、\\n太ったらどうするんですか？"

# ゆんゆん
# わ、私も太るのは、ちょっと。
491 = "わ、私も太るのは、ちょっと。"

# カズマ（Ｍ）
# display as カズマ
# （なんでだ！？\n　せっかく公平な提案をしたのに！）
599 = "（なんでだ！？\\n　せっかく公平な提案をしたのに！）"

# カズマ
# 魔物退治でどうだ！\nどっちがより大物を仕留められるかで勝負だ！
588 = "魔物退治でどうだ！\\nどっちがより大物を仕留められるかで勝負だ！"

# めぐみん
# 待ってください、\nそれでは私が不利ではありませんか。
527 = "待ってください、\\nそれでは私が不利ではありませんか。"

# めぐみん
# ゆんゆんは何度でもやり直しがききますが、\n私は爆裂魔法一発勝負なんですよ？\n公平でない以上、受けることはできません。
487 = "ゆんゆんは何度でもやり直しがききますが、\\n私は爆裂魔法一発勝負なんですよ？\\n公平でない以上、受けることはできません。"

# カズマ
# 別に魔法で\n仕留めなくてもいいんじゃないか？
516 = "別に魔法で\\n仕留めなくてもいいんじゃないか？"

# ゆんゆん
# でも、仮にも\nアークウィザード同士の勝負なので、\nここで魔法を使わないのでは、ちょっと。
470 = "でも、仮にも\\nアークウィザード同士の勝負なので、\\nここで魔法を使わないのでは、ちょっと。"

# カズマ（Ｍ）
# display as カズマ
# （ええー？\n　せっかく考えたのに……）
594 = "（ええー？\\n　せっかく考えたのに……）"

# カズマ
# 発育勝負だな。どちらの方がいいスタイルを\nしてるかを競うんだ。\nこれなら知力も体力も関係ないし、公平だろ？
534 = "発育勝負だな。どちらの方がいいスタイルを\\nしてるかを競うんだ。\\nこれなら知力も体力も関係ないし、公平だろ？"

# ゆんゆん
# はいっ！\n私は賛成です！
480 = "はいっ！\\n私は賛成です！"

# ダクネス
# いや、明らかに不公平だろう。
440 = "いや、明らかに不公平だろう。"

# アクア
# そうよね。\nめぐみんが勝てるわけないじゃない。
460 = "そうよね。\\nめぐみんが勝てるわけないじゃない。"

# めぐみん
# ２人とも？\nそれはフォローなんですか？
604 = "２人とも？\\nそれはフォローなんですか？"

# カズマ
# ダメかぁ。\nいいアイディアだと思ったんだけどなぁ。
507 = "ダメかぁ。\\nいいアイディアだと思ったんだけどなぁ。"

# めぐみん
# あの、フォローなんですか？\nフォローなんですか！？
429 = "あの、フォローなんですか？\\nフォローなんですか！？"

# アクア
# 仕方がないわね。\n無能なカズマに代わって、\nこの私が決めてあげるわ。
512 = "仕方がないわね。\\n無能なカズマに代わって、\\nこの私が決めてあげるわ。"

# アクア
# ここはズバリ、釣り勝負なんてどう？
453 = "ここはズバリ、釣り勝負なんてどう？"

# ダクネス
# 釣り？\nそれは魚釣りのことか？
585 = "釣り？\\nそれは魚釣りのことか？"

# ウィズ
# 確かにそれでしたら、\n身体能力に左右されることなく公平ですね。
582 = "確かにそれでしたら、\\n身体能力に左右されることなく公平ですね。"

# アクア
# そうでしょそうでしょ？\nリッチーもたまにはいいこと言うじゃない。
457 = "そうでしょそうでしょ？\\nリッチーもたまにはいいこと言うじゃない。"

# ウィズ
# あ、ありがとうございます。\nアクア様。
424 = "あ、ありがとうございます。\\nアクア様。"

# ダクネス
# うむ、カズマの提案より格段にいいな。
445 = "うむ、カズマの提案より格段にいいな。"

# アクア
# めぐみん達は勝負ができて大満足！\n私はタダでおかずがゲットできて大満足！\nこれぞＷｉｎ－Ｗｉｎよね！
484 = "めぐみん達は勝負ができて大満足！\\n私はタダでおかずがゲットできて大満足！\\nこれぞＷｉｎ－Ｗｉｎよね！"

# カズマ（Ｍ）
# display as カズマ
# （うわ……。\n　結局は自分のためかよ）
593 = "（うわ……。\\n　結局は自分のためかよ）"

# ゆんゆん
# カズマさん、うぃんうぃんってなんですか？
502 = "カズマさん、うぃんうぃんってなんですか？"

# カズマ
# 気にするな。\nとりあえず、悪いことではない。
529 = "気にするな。\\nとりあえず、悪いことではない。"

# ゆんゆん
# は、はあ……。
477 = "は、はあ……。"

# めぐみん
# 釣りですか。\n確かに公平かもしれませんが、\nあまりにもアークウィザードらしくないですね。
584 = "釣りですか。\\n確かに公平かもしれませんが、\\nあまりにもアークウィザードらしくないですね。"

# ダクネス
# いや、釣りには集中力が必要不可欠だ。\nそれは魔法にも言えるだろう？
442 = "いや、釣りには集中力が必要不可欠だ。\\nそれは魔法にも言えるだろう？"

# めぐみん
# うーん、ちょっと苦しいですが\nそういう見方もできますか。
447 = "うーん、ちょっと苦しいですが\\nそういう見方もできますか。"

# めぐみん
# いいでしょう。\n他に思いつかないですし、受けて立ちましょう。
433 = "いいでしょう。\\n他に思いつかないですし、受けて立ちましょう。"

# ゆんゆん
# 今日こそ負けないんだから！
511 = "今日こそ負けないんだから！"

# カズマ
# んじゃ、とっとと川に行こうぜ。
493 = "んじゃ、とっとと川に行こうぜ。"

# アクア
# いってらっしゃーい。\n大物を期待して待ってるわ。
437 = "いってらっしゃーい。\\n大物を期待して待ってるわ。"

# カズマ
# 何を寝ぼけたこと言ってんだ、提案者。\n見届ける義務があるだろ？
513 = "何を寝ぼけたこと言ってんだ、提案者。\\n見届ける義務があるだろ？"

# アクア
# え～？\n面倒なんですけど。
451 = "え～？\\n面倒なんですけど。"

# カズマ
# どうせ屋敷に残ってもゴロゴロしてるだけだろ？\nいいから行くぞ！
472 = "どうせ屋敷に残ってもゴロゴロしてるだけだろ？\\nいいから行くぞ！"

[selections]
522 = "大食い勝負だ！"
587 = "魔物退治でどうだ！"
533 = "発育勝負だな"
