# root_f05.txt.scn

[info]
0 = ""

[characters]
207 = "露天商Ａ"
179 = "ウィズ"
180 = "カズマ"
181 = "カズマ（Ｍ）"
188 = "女性客"
190 = "男性客"
208 = "露天商Ｂ"

[character_subs]
# 180 = "カズマ"

[script]
# lines: 38

# 露天商Ａ
# おーい、美人店主さん！
168 = "おーい、美人店主さん！"

# ウィズ
# あら。\nいつもお世話になってます。
160 = "あら。\\nいつもお世話になってます。"

# カズマ
# ん？　この人は？
178 = "ん？　この人は？"

# ウィズ
# いつも色々と、マジックアイテムを\n仕入れてきてくださる商人さんなんです。
162 = "いつも色々と、マジックアイテムを\\n仕入れてきてくださる商人さんなんです。"

# ウィズ
# 入手の難しい物や、珍しい物も\n持ってきてくださるんですよ。
186 = "入手の難しい物や、珍しい物も\\n持ってきてくださるんですよ。"

# カズマ（Ｍ）
# display as カズマ
# （なんか胡散臭い露店だな。\n　どうにもそういうレア物を扱ってる\n　オーラが無いというか）
218 = "（なんか胡散臭い露店だな。\\n　どうにもそういうレア物を扱ってる\\n　オーラが無いというか）"

# 露天商Ａ
# 今日も珍しいのが入ってんだ。\n見てくかい？
184 = "今日も珍しいのが入ってんだ。\\n見てくかい？"

# ウィズ
# はい、ぜひ！
174 = "はい、ぜひ！"

# 露天商Ａ
# よし、それじゃこっちからな。\nモンスター避けのお守りに御札にポーション。\n全部組み合わせて使うと効果も５倍だ！
177 = "よし、それじゃこっちからな。\\nモンスター避けのお守りに御札にポーション。\\n全部組み合わせて使うと効果も５倍だ！"

# ウィズ
# へぇ～。\nそれはすごいですね。
176 = "へぇ～。\\nそれはすごいですね。"

# カズマ（Ｍ）
# display as カズマ
# （……なんだそりゃ。\n　お守りと御札はともかく、それに\n　ポーションを合わせるってどう使うんだ？）
209 = "（……なんだそりゃ。\\n　お守りと御札はともかく、それに\\n　ポーションを合わせるってどう使うんだ？）"

# 露天商Ａ
# それから、アンラッキーを回避するアミュレット。\nこれも付ければ付けるほど効果がアップするぜ。
171 = "それから、アンラッキーを回避するアミュレット。\\nこれも付ければ付けるほど効果がアップするぜ。"

# ウィズ
# そうなんですか！
169 = "そうなんですか！"

# 露天商Ａ
# そして、こいつが今回の目玉だ！\n１回だけ、花鳥風月のスキルが\n使えるようになるスクロール！！
170 = "そして、こいつが今回の目玉だ！\\n１回だけ、花鳥風月のスキルが\\n使えるようになるスクロール！！"

# カズマ（Ｍ）
# display as カズマ
# （うわぁ……いらねぇ……）
212 = "（うわぁ……いらねぇ……）"

# 女性客
# キャー！\nそれ、それくださぁい！！
182 = "キャー！\\nそれ、それくださぁい！！"

# 男性客
# いや、俺だ！\nそのスクロール、是非欲しい！
163 = "いや、俺だ！\\nそのスクロール、是非欲しい！"

# カズマ
# うおっ！？　な、なんだ？
165 = "うおっ！？　な、なんだ？"

# 男性客
# 俺にくれ！
185 = "俺にくれ！"

# 女性客
# 私よ～！　いっぱい買うわよ～！！
205 = "私よ～！　いっぱい買うわよ～！！"

# カズマ（Ｍ）
# display as カズマ
# （ああ、これ、サクラか。\n　ここまで露骨なサクラもある意味レアだな。\n　棒読みだし口だけで全然買ってない）
210 = "（ああ、これ、サクラか。\\n　ここまで露骨なサクラもある意味レアだな。\\n　棒読みだし口だけで全然買ってない）"

# カズマ（Ｍ）
# display as カズマ
# （こんなのに釣られる人がいるとは思えな――）
215 = "（こんなのに釣られる人がいるとは思えな――）"

# ウィズ
# あ、あのっ！\n私にもください！！
158 = "あ、あのっ！\\n私にもください！！"

# カズマ（Ｍ）
# display as カズマ
# （いたよ！？）
211 = "（いたよ！？）"

# カズマ
# ちょ、ウィズ！\nちょっと待て！\nこんなの、あからさま過ぎるだろ！！
172 = "ちょ、ウィズ！\\nちょっと待て！\\nこんなの、あからさま過ぎるだろ！！"

# 男性客
# なんだテメェ！\nちゃんと順番に並びやがれ！
173 = "なんだテメェ！\\nちゃんと順番に並びやがれ！"

# 女性客
# 邪魔ね、あっち行ってよ！！
206 = "邪魔ね、あっち行ってよ！！"

# カズマ
# うおっ、ぐはっ！？
164 = "うおっ、ぐはっ！？"

# カズマ（Ｍ）
# display as カズマ
# （こ、こいつら、\n　買うのを止めようとする奴を\n　排除する役も兼ねてるのか）
213 = "（こ、こいつら、\\n　買うのを止めようとする奴を\\n　排除する役も兼ねてるのか）"

# カズマ（Ｍ）
# display as カズマ
# （っつーか、いつの間に\n　こんなに人が増えたんだ？\n　人波の中のウィズが見えないぞ……）
217 = "（っつーか、いつの間に\\n　こんなに人が増えたんだ？\\n　人波の中のウィズが見えないぞ……）"

# ウィズ
# ふう！\nはあ、やっと出られました。\n凄い人気ですね、毎回さすがです。
175 = "ふう！\\nはあ、やっと出られました。\\n凄い人気ですね、毎回さすがです。"

# カズマ
# あー、ウィズ？\nその手元にある物は？
161 = "あー、ウィズ？\\nその手元にある物は？"

# ウィズ
# ええ！\n今回もいい買い物が出来ました。
166 = "ええ！\\n今回もいい買い物が出来ました。"

# カズマ（Ｍ）
# display as カズマ
# （まあ……\n　本人が満足してるのならいいのか？）
219 = "（まあ……\\n　本人が満足してるのならいいのか？）"

# カズマ（Ｍ）
# display as カズマ
# （それにしても、いったいいくらで買ったんだ？\n　さっき説明されてた物を全部もってるよな？\n　どう見ても、高めな値段設定だった気がするぞ？）
216 = "（それにしても、いったいいくらで買ったんだ？\\n　さっき説明されてた物を全部もってるよな？\\n　どう見ても、高めな値段設定だった気がするぞ？）"

# 露天商Ｂ
# おーい、姉ちゃん！\n久しぶり。
167 = "おーい、姉ちゃん！\\n久しぶり。"

# ウィズ
# あ、お久しぶりです。
159 = "あ、お久しぶりです。"

# カズマ（Ｍ）
# display as カズマ
# （こいつもウィズの顔見知りっぽいが……。\n　なんか嫌な予感がするぜ）
214 = "（こいつもウィズの顔見知りっぽいが……。\\n　なんか嫌な予感がするぜ）"

