# root_b05.txt.scn

[info]
0 = ""

[characters]
319 = "めぐみん"
330 = "カズマ"
333 = "カズマ（Ｍ）"

[character_subs]
# 330 = "カズマ"

[script]
# lines: 91

# めぐみん
# お、お邪魔します。
271 = "お、お邪魔します。"

# カズマ
# そんなに警戒しなくても大丈夫だろ。\n本気でヤバかったら、\nここだって放棄されてるはずだ。
294 = "そんなに警戒しなくても大丈夫だろ。\\n本気でヤバかったら、\\nここだって放棄されてるはずだ。"

# カズマ
# だけど、見てみろ。\n中も綺麗に掃除が行き届いてるじゃないか。
299 = "だけど、見てみろ。\\n中も綺麗に掃除が行き届いてるじゃないか。"

# カズマ
# 毎日、掃除しなきゃこうはならないだろ？\n呪いが恐ろしいものなら\n悠長に掃除なんかしないって。
345 = "毎日、掃除しなきゃこうはならないだろ？\\n呪いが恐ろしいものなら\\n悠長に掃除なんかしないって。"

# カズマ
# つまり、言うほど大した呪いじゃ\nないんじゃないか？
304 = "つまり、言うほど大した呪いじゃ\\nないんじゃないか？"

# めぐみん
# ですが……誰もいないみたいですよ？\n声をかけたのに出てきませんでしたし。
305 = "ですが……誰もいないみたいですよ？\\n声をかけたのに出てきませんでしたし。"

# カズマ
# 話を聞こうかと思ったんだけどなぁ。\n街へ布教活動でもしに出てるのか？
378 = "話を聞こうかと思ったんだけどなぁ。\\n街へ布教活動でもしに出てるのか？"

# めぐみん
# だとしても、誰もいないというのは\nおかしな話です。
301 = "だとしても、誰もいないというのは\\nおかしな話です。"

# めぐみん
# この時間なら、誰かしら\n祈りを捧げているはずなのに。
277 = "この時間なら、誰かしら\\n祈りを捧げているはずなのに。"

# カズマ
# んじゃ、奥で作業をしてるとか。
328 = "んじゃ、奥で作業をしてるとか。"

# めぐみん
# そうだといいのですが……。\nなんだか、嫌な感じです。
289 = "そうだといいのですが……。\\nなんだか、嫌な感じです。"

# カズマ
# すみませーん！！\n誰かいませんかー！？
285 = "すみませーん！！\\n誰かいませんかー！？"

# カズマ
# …………。
262 = "…………。"

# めぐみん
# なんの反応もありませんね。\nそれどころか、気配すら感じませんよ？
312 = "なんの反応もありませんね。\\nそれどころか、気配すら感じませんよ？"

# カズマ
# これはー、もしかしたらー、\nあれかもしれないな。
279 = "これはー、もしかしたらー、\\nあれかもしれないな。"

# めぐみん
# な、なんですか、あれって？
308 = "な、なんですか、あれって？"

# カズマ
# みんな呪いにやられちまったんじゃないか？
317 = "みんな呪いにやられちまったんじゃないか？"

# めぐみん
# さ、さっき大丈夫だって言ったじゃないですか！
280 = "さ、さっき大丈夫だって言ったじゃないですか！"

# カズマ
# いや、よく考えたらさ――
265 = "いや、よく考えたらさ――"

# カズマ
# この依頼って、１０万エリスを\n帳消しにしてもいいほどのものなんだろ？\n相当、やばい依頼だとしてもおかしくはない。
275 = "この依頼って、１０万エリスを\\n帳消しにしてもいいほどのものなんだろ？\\n相当、やばい依頼だとしてもおかしくはない。"

# めぐみん
# むしろ、そう考える方が自然ですよ。
318 = "むしろ、そう考える方が自然ですよ。"

# カズマ
# もしかしたらさ、\n俺、とんでもないことを引き受けた！？
321 = "もしかしたらさ、\\n俺、とんでもないことを引き受けた！？"

# めぐみん
# ここで後悔しても遅いですっ！
273 = "ここで後悔しても遅いですっ！"

# カズマ
# うう……。\n心なしか空気がさっきより重たくなってないか？\nそれに、息苦しいような……。
266 = "うう……。\\n心なしか空気がさっきより重たくなってないか？\\nそれに、息苦しいような……。"

# めぐみん
# カズマ、早く帰りましょう？\nやっぱりここはよくないですよ。
331 = "カズマ、早く帰りましょう？\\nやっぱりここはよくないですよ。"

# カズマ（Ｍ）
# display as カズマ
# （おお、ビビってるビビってる。\n　震えながらキョロキョロしちゃって）
382 = "（おお、ビビってるビビってる。\\n　震えながらキョロキョロしちゃって）"

# カズマ（Ｍ）
# display as カズマ
# （こういうところはまだ子供だな。\n　本当に可愛いもんだ。\n　面白いから、もう少しからかってみるか）
383 = "（こういうところはまだ子供だな。\\n　本当に可愛いもんだ。\\n　面白いから、もう少しからかってみるか）"

# カズマ
# 信仰熱心なエリス教徒が\n誰もいないっていうのは、\nやっぱりどう考えてもおかしい。
337 = "信仰熱心なエリス教徒が\\n誰もいないっていうのは、\\nやっぱりどう考えてもおかしい。"

# カズマ
# １００歩譲って信者がいないのはいいとして、\n司祭がいないってのはどういうことだ？
386 = "１００歩譲って信者がいないのはいいとして、\\n司祭がいないってのはどういうことだ？"

# めぐみん
# 私に言われてもわかりませんよ。
375 = "私に言われてもわかりませんよ。"

# カズマ
# これは、あくまでも俺の想像なんだが――
278 = "これは、あくまでも俺の想像なんだが――"

# カズマ
# 信者はみんなエリス様が大好きなわけだろ？\nそんな人々が、神聖な教会にかけられた呪いを\n手をこまねいて見ているだけなんてあり得るのか？
338 = "信者はみんなエリス様が大好きなわけだろ？\\nそんな人々が、神聖な教会にかけられた呪いを\\n手をこまねいて見ているだけなんてあり得るのか？"

# めぐみん
# だから、あの悪魔に依頼したのでしょう？
297 = "だから、あの悪魔に依頼したのでしょう？"

# カズマ
# それはそうだけどさ、\n信仰深い信者なら自分たちの手で\n解決したいって思うんじゃないか？
292 = "それはそうだけどさ、\\n信仰深い信者なら自分たちの手で\\n解決したいって思うんじゃないか？"

# めぐみん
# 確かに、信仰を試されていると\n思うかもしれません。
374 = "確かに、信仰を試されていると\\n思うかもしれません。"

# カズマ
# バニルに依頼はしたものの、\nできることなら自分達でどうにかしようと\n考えて――
335 = "バニルに依頼はしたものの、\\nできることなら自分達でどうにかしようと\\n考えて――"

# カズマ
# 更なる呪いを受けてしまったんじゃないか？
344 = "更なる呪いを受けてしまったんじゃないか？"

# めぐみん
# え……？\nさ、更なる呪い？
268 = "え……？\\nさ、更なる呪い？"

# カズマ
# この教会は、見たところ\nどこもかしこもピカピカに掃除されている。\n少し前まで誰かがいた証拠だ。
276 = "この教会は、見たところ\\nどこもかしこもピカピカに掃除されている。\\n少し前まで誰かがいた証拠だ。"

# カズマ
# そう、ほんの数分前に……\n信者達は呪いによって\n消えてしまったんじゃないか？
286 = "そう、ほんの数分前に……\\n信者達は呪いによって\\n消えてしまったんじゃないか？"

# カズマ
# ここにいたはずの信者達は今、\nどこでなにをしてるんだろうな？\nもしかして、もうすでに――
274 = "ここにいたはずの信者達は今、\\nどこでなにをしてるんだろうな？\\nもしかして、もうすでに――"

# めぐみん
# も、もういいですっ！\n何もないのなら、これ以上\nここにいても仕方ありませんよ！
320 = "も、もういいですっ！\\n何もないのなら、これ以上\\nここにいても仕方ありませんよ！"

# めぐみん
# さあ、帰りますよ！\n今すぐ帰りますよ！\n早くおいとましましょう！！
281 = "さあ、帰りますよ！\\n今すぐ帰りますよ！\\n早くおいとましましょう！！"

# カズマ
# えー？\n俺はもう少し調べていきたいんだけど。
269 = "えー？\\n俺はもう少し調べていきたいんだけど。"

# めぐみん
# そうですか、\nでは先に帰らせてもらいます！\nこんな所には１秒でもいたくありません！
290 = "そうですか、\\nでは先に帰らせてもらいます！\\nこんな所には１秒でもいたくありません！"

# カズマ
# お、おい、めぐみん！
270 = "お、おい、めぐみん！"

# カズマ（Ｍ）
# display as カズマ
# （涙目であんな早足になって……\n　少し怖がらせすぎたか？）
385 = "（涙目であんな早足になって……\\n　少し怖がらせすぎたか？）"

# めぐみん
# カ、カズマぁぁぁぁぁっ！！
329 = "カ、カズマぁぁぁぁぁっ！！"

# カズマ
# わっ！？\nど、どうしためぐみん！
327 = "わっ！？\\nど、どうしためぐみん！"

# めぐみん
# カズマッ！
332 = "カズマッ！"

# カズマ
# なんで戻ってきたんだよ。\n帰るんじゃなかったのか。
311 = "なんで戻ってきたんだよ。\\n帰るんじゃなかったのか。"

# めぐみん
# わ、私だってそのつもりでした！\nでもダメなんです！
325 = "わ、私だってそのつもりでした！\\nでもダメなんです！"

# カズマ
# ダメって、なにがダメなんだ？
334 = "ダメって、なにがダメなんだ？"

# めぐみん
# い、入り口が……開かないんです！
263 = "い、入り口が……開かないんです！"

# カズマ
# なんだ、からかってるのか？
310 = "なんだ、からかってるのか？"

# めぐみん
# からかってなんていません！\n疑っているのですか！？
272 = "からかってなんていません！\\n疑っているのですか！？"

# カズマ
# だって、普通に入ってこられたのに\n出られないなんてこと、あるはずないだろ？
300 = "だって、普通に入ってこられたのに\\n出られないなんてこと、あるはずないだろ？"

# めぐみん
# そんなことを言われても！\n本当のことなんですから\n仕方がないじゃないですか～！
293 = "そんなことを言われても！\\n本当のことなんですから\\n仕方がないじゃないですか～！"

# カズマ
# そういうのはいいからさ、\n素直に冗談だって認めたらどうだ？\n俺を怖がらせようとしても無駄だぞ。
287 = "そういうのはいいからさ、\\n素直に冗談だって認めたらどうだ？\\n俺を怖がらせようとしても無駄だぞ。"

# めぐみん
# だから本当なんです！\nそんなに疑うなら確かめてみてください！
298 = "だから本当なんです！\\nそんなに疑うなら確かめてみてください！"

# カズマ
# わかったよ。\nそうさせてもらおうじゃないか。
326 = "わかったよ。\\nそうさせてもらおうじゃないか。"

# カズマ
# はいはい、わかったよ。
315 = "はいはい、わかったよ。"

# めぐみん
# な、なんですか、その態度は！\nもしかして、冗談だと思っているのですか！？
309 = "な、なんですか、その態度は！\\nもしかして、冗談だと思っているのですか！？"

# カズマ
# もしかしなくてもそう思ってるぞ。\nあれだろ、俺を驚かせようって魂胆だろ？
322 = "もしかしなくてもそう思ってるぞ。\\nあれだろ、俺を驚かせようって魂胆だろ？"

# めぐみん
# 違いますよ！\nカズマじゃあるまいし、\nそんなくだらない真似しません！
379 = "違いますよ！\\nカズマじゃあるまいし、\\nそんなくだらない真似しません！"

# カズマ
# そこまで言うなら確かめてやろうじゃないか。\nこれであっさり開いたら\nめぐみんはくだらないってことになるからな？
291 = "そこまで言うなら確かめてやろうじゃないか。\\nこれであっさり開いたら\\nめぐみんはくだらないってことになるからな？"

# めぐみん
# いいですよ！\nそんなことには間違ってもなりませんから！
264 = "いいですよ！\\nそんなことには間違ってもなりませんから！"

# カズマ
# 鍵がかかってるんだろ？
381 = "鍵がかかってるんだろ？"

# めぐみん
# だ、誰がかけたっていうんですか？\nここには私達以外、誰もいないんですよ！？
296 = "だ、誰がかけたっていうんですか？\\nここには私達以外、誰もいないんですよ！？"

# カズマ
# し、知らないけど誰かだろ？\nそれ以外考えられないじゃないか。
282 = "し、知らないけど誰かだろ？\\nそれ以外考えられないじゃないか。"

# めぐみん
# だ、だったとしても、\n鍵がかかっているとかそういう感じでは\nないのです。
295 = "だ、だったとしても、\\n鍵がかかっているとかそういう感じでは\\nないのです。"

# カズマ
# はあ？\nじゃあ、どんな感じなんだよ？
313 = "はあ？\\nじゃあ、どんな感じなんだよ？"

# めぐみん
# 自分で確かめてください。\nその方が早いです！　さあ、早く！
376 = "自分で確かめてください。\\nその方が早いです！　さあ、早く！"

# カズマ
# はいはい、わかったよ。
# 315 = "はいはい、わかったよ。"

# カズマ
# うん、開かないね。
267 = "うん、開かないね。"

# めぐみん
# ほら、言ったじゃないですか！
316 = "ほら、言ったじゃないですか！"

# カズマ
# しかし、おかしいな。\nいや、普通に考えてありえないだろ、これ。
284 = "しかし、おかしいな。\\nいや、普通に考えてありえないだろ、これ。"

# めぐみん
# ど、どういう意味ですか。
306 = "ど、どういう意味ですか。"

# カズマ
# 鍵がかかっていたとしてもだ、\nほんの少し、遊び程度には絶対に動くはずだ。
380 = "鍵がかかっていたとしてもだ、\\nほんの少し、遊び程度には絶対に動くはずだ。"

# めぐみん
# そういえば、本当にビクともしませんね。\nまるで壁です。
288 = "そういえば、本当にビクともしませんね。\\nまるで壁です。"

# カズマ
# つまり……。
303 = "つまり……。"

# めぐみん
# つ、つまり？
302 = "つ、つまり？"

# カズマ
# どういうことだ、これ。
307 = "どういうことだ、これ。"

# めぐみん
# し、知りませんよ！\nそれを考えるのもカズマの役目でしょう！
283 = "し、知りませんよ！\\nそれを考えるのもカズマの役目でしょう！"

# カズマ
# 勝手に役割分担すんな！\nだいたい考えるのが俺の役目だって言うなら、\nお前は何をやるんだよ。
340 = "勝手に役割分担すんな！\\nだいたい考えるのが俺の役目だって言うなら、\\nお前は何をやるんだよ。"

# めぐみん
# 撃ちます。
343 = "撃ちます。"

# カズマ（Ｍ）
# display as カズマ
# （今日はもう、魔力がスカスカの役立たずだけどな）
384 = "（今日はもう、魔力がスカスカの役立たずだけどな）"

# めぐみん
# もも、もしかして、これも呪いのせいなのですか？
323 = "もも、もしかして、これも呪いのせいなのですか？"

# カズマ
# 落ち着け。\n呪いのせいにするにしても情報が足りなすぎる。
377 = "落ち着け。\\n呪いのせいにするにしても情報が足りなすぎる。"

# カズマ
# 出入り口はここだけじゃないはずだし、\nとりあえず窓も調べてみようぜ。
339 = "出入り口はここだけじゃないはずだし、\\nとりあえず窓も調べてみようぜ。"

# めぐみん
# わ、わかりました！
324 = "わ、わかりました！"

[selections]
# 310 = "なんだ、からかってるのか？"
314 = "はいはい、わかったよ"
# 381 = "鍵がかかってるんだろ？"
