# root_d22.txt.scn

[info]
0 = ""

[characters]
317 = "カズマ"
320 = "クリス"
318 = "カズマ（Ｍ）"
344 = "盗賊風の男冒険者"
341 = "戦士風の男冒険者"
327 = "ルナ"

[character_subs]
# 317 = "カズマ"
343 = "盗賊冒険者"
340 = "戦士冒険者"

[script]
# lines: 98

# カズマ
# いったたたた……。\nお、おい、クリス、大丈夫か？
261 = "いったたたた……。\\nお、おい、クリス、大丈夫か？"

# クリス
# も、もう、最低だよ！\nパンツだけじゃなくて\nズボンまで脱がそうとするなんて……。
314 = "も、もう、最低だよ！\\nパンツだけじゃなくて\\nズボンまで脱がそうとするなんて……。"

# カズマ
# そうか、脱がそうとするっていう言葉から察するに\n脱げなかったんだな。
284 = "そうか、脱がそうとするっていう言葉から察するに\\n脱げなかったんだな。"

# クリス
# と、当然でしょ！\n脱げなかったよ！　うん、脱げなかった！
298 = "と、当然でしょ！\\n脱げなかったよ！　うん、脱げなかった！"

# カズマ（Ｍ）
# display as カズマ
# （そうか、うん、脱げなかったのか。\n　本人が言うんだからそうなんだろう）
392 = "（そうか、うん、脱げなかったのか。\\n　本人が言うんだからそうなんだろう）"

# クリス
# っていうか、近づかないでくれる？
297 = "っていうか、近づかないでくれる？"

# カズマ
# おいおい、俺はわざとズボンを脱がせようとした\n訳じゃないだろ。
268 = "おいおい、俺はわざとズボンを脱がせようとした\\n訳じゃないだろ。"

# クリス
# 離してって言ってるのに\n離さなかったじゃない！
388 = "離してって言ってるのに\\n離さなかったじゃない！"

# カズマ
# あれは仕方ないだろ？\nあそこで離したら、\n俺だけ落ちることになってたし！
259 = "あれは仕方ないだろ？\\nあそこで離したら、\\n俺だけ落ちることになってたし！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# あー、お取り込み中のところ悪ぃが\nそろそろ観念してもらおうか？
260 = "あー、お取り込み中のところ悪ぃが\\nそろそろ観念してもらおうか？"

# クリス
# えっ？
264 = "えっ？"

# カズマ
# か、囲まれてるだと！？\nくっ、いつの間に！
271 = "か、囲まれてるだと！？\\nくっ、いつの間に！"

# 戦士風の男冒険者
# display as 戦士冒険者
# 屋根の上であれだけ大騒ぎしてりゃ、\n誰だって気付くぞ？
337 = "屋根の上であれだけ大騒ぎしてりゃ、\\n誰だって気付くぞ？"

# カズマ
# あ、はい、ですよねー。
255 = "あ、はい、ですよねー。"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# 散々手間取らせやがって。\nけどもう逃げられねーからな！
342 = "散々手間取らせやがって。\\nけどもう逃げられねーからな！"

# カズマ（Ｍ）
# display as カズマ
# （１，２，３……１０人はさすがにしんどいな）
402 = "（１，２，３……１０人はさすがにしんどいな）"

# カズマ
# なあクリス。\nお前だけでも……ここから逃げられるか？
300 = "なあクリス。\\nお前だけでも……ここから逃げられるか？"

# クリス
# さすがに、ちょっと無理かな。\nいくらあたしでも、これだけの人数に\n囲まれてちゃ、お手上げだよ。
278 = "さすがに、ちょっと無理かな。\\nいくらあたしでも、これだけの人数に\\n囲まれてちゃ、お手上げだよ。"

# 戦士風の男冒険者
# display as 戦士冒険者
# ほう、意外と物分かりいいな。\nそれじゃ、大人しく捕まってもらおうか。
310 = "ほう、意外と物分かりいいな。\\nそれじゃ、大人しく捕まってもらおうか。"

# カズマ
# その前に、俺にチャンスをくれないか？
287 = "その前に、俺にチャンスをくれないか？"

# 戦士風の男冒険者
# display as 戦士冒険者
# は？　チャンス？
306 = "は？　チャンス？"

# カズマ
# そう、チャンス。\nそれは男の夢というチャレンジタイムともいう。
283 = "そう、チャンス。\\nそれは男の夢というチャレンジタイムともいう。"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# その構えはスティールか？\n止めとけ止めとけ、もうあんなくだらない脅しには\n引っかからないぜ。
288 = "その構えはスティールか？\\n止めとけ止めとけ、もうあんなくだらない脅しには\\n引っかからないぜ。"

# 戦士風の男冒険者
# display as 戦士冒険者
# そうそう、この場の誰かから盗んだって無駄だ。\nこの人数から逃げられるわけがないし、\n後で取り返せばいいだけだからな。
285 = "そうそう、この場の誰かから盗んだって無駄だ。\\nこの人数から逃げられるわけがないし、\\n後で取り返せばいいだけだからな。"

# カズマ
# 俺は言ったはずだぜ。\nこれは男の夢というチャレンジタイムだと。
333 = "俺は言ったはずだぜ。\\nこれは男の夢というチャレンジタイムだと。"

# クリス
# ちょ、ちょっとカズマ、\nなんであたしのほう向いてるのさ。
294 = "ちょ、ちょっとカズマ、\\nなんであたしのほう向いてるのさ。"

# カズマ
# それはこれから……\nクリスにスティールをするからだ！！
289 = "それはこれから……\\nクリスにスティールをするからだ！！"

# クリス
# 訳わかんないんだけど……。
387 = "訳わかんないんだけど……。"

# カズマ
# さて、おい男連中。\n交渉の席について貰おうか。
280 = "さて、おい男連中。\\n交渉の席について貰おうか。"

# 戦士風の男冒険者
# display as 戦士冒険者
# ほ、ほほう？　どんな交渉だ。
309 = "ほ、ほほう？　どんな交渉だ。"

# カズマ
# 知っての通り、スティールは\n相手が身につけている物からランダムに\nアイテムを盗むスキルだ。
386 = "知っての通り、スティールは\\n相手が身につけている物からランダムに\\nアイテムを盗むスキルだ。"

# カズマ
# ここに居るクリスは、\nありていに言うと「穿いてない」。\nそれはお前らもよーく知ってるはずだ。
274 = "ここに居るクリスは、\\nありていに言うと「穿いてない」。\\nそれはお前らもよーく知ってるはずだ。"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# だ、だったら、なんだっていうんだよ？
290 = "だ、だったら、なんだっていうんだよ？"

# カズマ
# もし、俺がお前たちの望む物を盗めたら、\n報酬金１００万をなしにしてくれ。
315 = "もし、俺がお前たちの望む物を盗めたら、\\n報酬金１００万をなしにしてくれ。"

# クリス
# あ、あたしを売る気！？
253 = "あ、あたしを売る気！？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# 仲間を売るなんて、なんてクズなんだ！
330 = "仲間を売るなんて、なんてクズなんだ！"

# 戦士風の男冒険者
# display as 戦士冒険者
# さすがクズマと呼ばれる男！\n俺、こんなクズな男、はじめて見たぜ！
279 = "さすがクズマと呼ばれる男！\\n俺、こんなクズな男、はじめて見たぜ！"

# クリス
# ねえカズマ、冗談だよね？\nいくらキミが救いようのないクズでも\nそんなことしないって信じてるよ？
303 = "ねえカズマ、冗談だよね？\\nいくらキミが救いようのないクズでも\\nそんなことしないって信じてるよ？"

# カズマ
# さあ、言え！\nお前らの望む物はなんだ！
277 = "さあ、言え！\\nお前らの望む物はなんだ！"

# 戦士風の男冒険者
# display as 戦士冒険者
# あのダガー、業物っぽいよな？
258 = "あのダガー、業物っぽいよな？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# お、おう、結構な値段がすると思うぜ？
266 = "お、おう、結構な値段がすると思うぜ？"

# カズマ
# だが、１００万エリスの価値はない。
291 = "だが、１００万エリスの価値はない。"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# そ、そうなんだよなぁ。\nあと……価値があるとすれば\nズ、ズ、ズボンとか？
282 = "そ、そうなんだよなぁ。\\nあと……価値があるとすれば\\nズ、ズ、ズボンとか？"

# クリス
# ひっ！？
307 = "ひっ！？"

# 戦士風の男冒険者
# display as 戦士冒険者
# き、奇遇だな！\n俺もあのズボンにはかなりの価値があると\n思ってたんだ！
272 = "き、奇遇だな！\\n俺もあのズボンにはかなりの価値があると\\n思ってたんだ！"

# クリス
# さ、さ、最低だよ、キミたち！！
276 = "さ、さ、最低だよ、キミたち！！"

# クリス
# その中でも、カズマ！\nキミは、本当に……\nあたし、ちょっと信じてたのにっ！
286 = "その中でも、カズマ！\\nキミは、本当に……\\nあたし、ちょっと信じてたのにっ！"

# カズマ
# ふふふははははっ！\nこちとら１００万エリスの借金を回避するためなら\nなんだってしてやるさぁ！
308 = "ふふふははははっ！\\nこちとら１００万エリスの借金を回避するためなら\\nなんだってしてやるさぁ！"

# クリス
# 信じらんない……。
332 = "信じらんない……。"

# カズマ（Ｍ）
# display as カズマ
# （よし、なんとかけん制できたな。\n　こっちに近づく動きが止まった。\n　……ここまでは想定通りだ）
394 = "（よし、なんとかけん制できたな。\\n　こっちに近づく動きが止まった。\\n　……ここまでは想定通りだ）"

# カズマ（Ｍ）
# display as カズマ
# （太陽の位置から考えて、制限時間まであと少し。\n　この調子でこいつらを\n　足止めすることができれば俺の勝ちだ！）
400 = "（太陽の位置から考えて、制限時間まであと少し。\\n　この調子でこいつらを\\n　足止めすることができれば俺の勝ちだ！）"

# クリス
# キミって人は……本当に見損なったよ！
319 = "キミって人は……本当に見損なったよ！"

# カズマ
# おっと、クリスも動くなよ。\n下手に抵抗されたらズボンだけじゃ\nすまないかもしれない。
269 = "おっと、クリスも動くなよ。\\n下手に抵抗されたらズボンだけじゃ\\nすまないかもしれない。"

# クリス
# なっ……！
301 = "なっ……！"

# 戦士風の男冒険者
# display as 戦士冒険者
# 仮にも仲間に向かってなんという仕打ちだ。\nさすがクズマ、噂には聞いていたが\n聞きしに勝る外道だな。
329 = "仮にも仲間に向かってなんという仕打ちだ。\\nさすがクズマ、噂には聞いていたが\\n聞きしに勝る外道だな。"

# カズマ
# ほらほら、みなさん。\n特等席はクリスの正面ですよ。
312 = "ほらほら、みなさん。\\n特等席はクリスの正面ですよ。"

# クリス
# ちょ、ちょっと！！
295 = "ちょ、ちょっと！！"

# カズマ（Ｍ）
# display as カズマ
# （よしよし、クリスの後ろに突破口ができた！）
395 = "（よしよし、クリスの後ろに突破口ができた！）"

# カズマ（Ｍ）
# display as カズマ
# （あとはどうやってクリスに俺の意図を\n　伝えるかなんだけど……）
390 = "（あとはどうやってクリスに俺の意図を\\n　伝えるかなんだけど……）"

# クリス
# う、うう……絶対、後で殴ってやる。\n顔の形が変わるまで殴り続けてやるんだからぁ！
262 = "う、うう……絶対、後で殴ってやる。\\n顔の形が変わるまで殴り続けてやるんだからぁ！"

# カズマ（Ｍ）
# display as カズマ
# （ああ、冷静さを失ってる……。\n　ちょっとやり過ぎたか？）
389 = "（ああ、冷静さを失ってる……。\\n　ちょっとやり過ぎたか？）"

# 戦士風の男冒険者
# display as 戦士冒険者
# ほら、カズマ。\nその男の夢、チャレンジタイムってやつを\n早くやってくれよ。
311 = "ほら、カズマ。\\nその男の夢、チャレンジタイムってやつを\\n早くやってくれよ。"

# カズマ（Ｍ）
# display as カズマ
# （クリス、後ろ！　後ろから逃げられるから！\n　俺のアイコンタクトに気がついてくれ！）
396 = "（クリス、後ろ！　後ろから逃げられるから！\\n　俺のアイコンタクトに気がついてくれ！）"

# クリス
# ちょっと、ウィンクなんて飛ばして\n気持ち悪いんだけど……。
296 = "ちょっと、ウィンクなんて飛ばして\\n気持ち悪いんだけど……。"

# カズマ（Ｍ）
# display as カズマ
# （ちっがうっ、うしろ！\n　うーーしーーろっ！　逃げられるから！！）
393 = "（ちっがうっ、うしろ！\\n　うーーしーーろっ！　逃げられるから！！）"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# おい、何やってんだよ。\n早く、やれって。
267 = "おい、何やってんだよ。\\n早く、やれって。"

# カズマ
# わ、わかってる！\nしかしこういうことには焦らしも大切なんだ！
316 = "わ、わかってる！\\nしかしこういうことには焦らしも大切なんだ！"

# 戦士風の男冒険者
# display as 戦士冒険者
# はあ？　なんだそれ？
304 = "はあ？　なんだそれ？"

# カズマ（Ｍ）
# display as カズマ
# （クリス、頼むから気がついてくれ！！\n　後ろ！　後ろに逃げるの！！）
397 = "（クリス、頼むから気がついてくれ！！\\n　後ろ！　後ろに逃げるの！！）"

# クリス
# ……カズマ。
251 = "……カズマ。"

# カズマ（Ｍ）
# display as カズマ
# （気がついたか！）
401 = "（気がついたか！）"

# クリス
# 何その顔芸、腹立つんだけど。
331 = "何その顔芸、腹立つんだけど。"

# カズマ
# ちがーーーう！！\n後ろに逃げろって合図してんだよ！
292 = "ちがーーーう！！\\n後ろに逃げろって合図してんだよ！"

# クリス
# え？
265 = "え？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# は？
305 = "は？"

# カズマ
# あ……。
252 = "あ……。"

# 戦士風の男冒険者
# display as 戦士冒険者
# なるほど、そういう魂胆だったのか！
302 = "なるほど、そういう魂胆だったのか！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# まあ、俺は最初からわかってたけどな。
313 = "まあ、俺は最初からわかってたけどな。"

# 戦士風の男冒険者
# display as 戦士冒険者
# 当然、俺もだ！
339 = "当然、俺もだ！"

# カズマ（Ｍ）
# display as カズマ
# （嘘をつくな、嘘を……）
399 = "（嘘をつくな、嘘を……）"

# クリス
# あの、ええと、カズマ。\n気がついてあげられなくてごめんね。
257 = "あの、ええと、カズマ。\\n気がついてあげられなくてごめんね。"

# カズマ
# 別にいいよ。\nこれも日頃の行いってやつだ。
335 = "別にいいよ。\\nこれも日頃の行いってやつだ。"

# クリス
# うん、そうだね。
263 = "うん、そうだね。"

# カズマ（Ｍ）
# display as カズマ
# （フォローしてよ！）
398 = "（フォローしてよ！）"

# 戦士風の男冒険者
# display as 戦士冒険者
# さて、年貢の納め時だぜ、カズマ。
281 = "さて、年貢の納め時だぜ、カズマ。"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# これで１００万エリスは俺たちのもんだ！
275 = "これで１００万エリスは俺たちのもんだ！"

# カズマ（Ｍ）
# display as カズマ
# （くそっ！　あの駄女神のせいで\n　また借金が増えるのかよ……。\n　いつかまとめてこの恨み、返してやるからな！）
391 = "（くそっ！　あの駄女神のせいで\\n　また借金が増えるのかよ……。\\n　いつかまとめてこの恨み、返してやるからな！）"

# 戦士風の男冒険者
# display as 戦士冒険者
# ナッハハハハハー！\n１００万いただきぃっ！！
323 = "ナッハハハハハー！\\n１００万いただきぃっ！！"

# カズマ
# ちくしょーーー！！
293 = "ちくしょーーー！！"

# 戦士風の男冒険者
# display as 戦士冒険者
# あっ！！
256 = "あっ！！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# くそっ、マジかよ！！
273 = "くそっ、マジかよ！！"

# カズマ
# な、なんだ！？
299 = "な、なんだ！？"

# ルナ
# 冒険者のみなさん。\nお疲れさまでした。
334 = "冒険者のみなさん。\\nお疲れさまでした。"

# ルナ
# サトウカズマさんが発注した、\nクリスさんを捕まえるクエストは\n現時点をもって終了になります。
322 = "サトウカズマさんが発注した、\\nクリスさんを捕まえるクエストは\\n現時点をもって終了になります。"

# カズマ
# マジ……で？
326 = "マジ……で？"

# ルナ
# クリスさんを捕まえた方は、\nすみやかにご本人を連れてギルド受付まで\nクエスト終了の報告に来てください。
321 = "クリスさんを捕まえた方は、\\nすみやかにご本人を連れてギルド受付まで\\nクエスト終了の報告に来てください。"

# クリス
# おめでとう。\nキミの勝ちだよ、カズマ。
270 = "おめでとう。\\nキミの勝ちだよ、カズマ。"

# カズマ
# あ、あははは、そうか。\n俺の勝ちか、そうかぁ……。
254 = "あ、あははは、そうか。\\n俺の勝ちか、そうかぁ……。"

