# root_f31.txt.scn

[info]
0 = ""

[characters]
237 = "カズマ（Ｍ）"
233 = "アクア"
235 = "カズマ"
229 = "ゆんゆん"
227 = "めぐみん"
234 = "ウィズ"
238 = "ダクネス"

[character_subs]
# 235 = "カズマ"

[script]
# lines: 53

# カズマ（Ｍ）
# display as カズマ
# （そして、数日が過ぎ――\n　俺は、相変わらず\n　ウィズの店の手伝いを続けていた）
265 = "（そして、数日が過ぎ――\\n　俺は、相変わらず\\n　ウィズの店の手伝いを続けていた）"

# カズマ（Ｍ）
# display as カズマ
# （除霊の件でギルドから特別報酬も出て、\n　多少は店の赤字を埋める足しにはなったんだが、\n　閑古鳥の鳴く店内は、さほど変わらなかった）
270 = "（除霊の件でギルドから特別報酬も出て、\\n　多少は店の赤字を埋める足しにはなったんだが、\\n　閑古鳥の鳴く店内は、さほど変わらなかった）"

# カズマ（Ｍ）
# display as カズマ
# （……の、だが）
262 = "（……の、だが）"

# アクア
# ちょっとカズマさーん？\nこの店は客にお茶の１つも出さないわけ？
220 = "ちょっとカズマさーん？\\nこの店は客にお茶の１つも出さないわけ？"

# カズマ
# 品物を買いもしないで\n茶を要求するやつを客とは言わねーよ。
243 = "品物を買いもしないで\\n茶を要求するやつを客とは言わねーよ。"

# ゆんゆん
# だーかーらー！\nまた勝負してって言ってるの～！
218 = "だーかーらー！\\nまた勝負してって言ってるの～！"

# めぐみん
# 未来永劫、ゆんゆんが\n私に勝つなどありえませんからね。\nだから、勝負自体が無意味です。
247 = "未来永劫、ゆんゆんが\\n私に勝つなどありえませんからね。\\nだから、勝負自体が無意味です。"

# ゆんゆん
# そ、そんなことないもん！
212 = "そ、そんなことないもん！"

# カズマ
# ええーい、そっちもうるさーい！
205 = "ええーい、そっちもうるさーい！"

# ゆんゆん
# ご、ごめんなさいっ！
211 = "ご、ごめんなさいっ！"

# めぐみん
# ……どうして私まで叱られるのですか。\n納得いきません。
194 = "……どうして私まで叱られるのですか。\\n納得いきません。"

# カズマ（Ｍ）
# display as カズマ
# （このところ、俺が働いていると知った\n　アクア達が押しかけるようになり、\n　ウィズの店がたまり場となりつつある）
264 = "（このところ、俺が働いていると知った\\n　アクア達が押しかけるようになり、\\n　ウィズの店がたまり場となりつつある）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、賑やかさにつられた客が\n　ちょくちょく店を覗くようになったのは\n　不幸中の幸いだが……）
267 = "（まあ、賑やかさにつられた客が\\n　ちょくちょく店を覗くようになったのは\\n　不幸中の幸いだが……）"

# カズマ
# あのな、お前ら。\nここは魔道具店であって喫茶店じゃ無いんだ。
196 = "あのな、お前ら。\\nここは魔道具店であって喫茶店じゃ無いんだ。"

# ウィズ
# まあまあ、カズマさん。\n賑やかでいいじゃないですか。
226 = "まあまあ、カズマさん。\\n賑やかでいいじゃないですか。"

# カズマ
# いや、ウィズはわかっていない。\nこいつらは黙ってると\nひたすら付け上がるんだ。
200 = "いや、ウィズはわかっていない。\\nこいつらは黙ってると\\nひたすら付け上がるんだ。"

# ウィズ
# いいんです。\n私、賑やかなのは嫌いではありませんよ？
199 = "いいんです。\\n私、賑やかなのは嫌いではありませんよ？"

# ウィズ
# それよりカズマさん。\nこの商品、ここに並べようかなって\n思うんですけど。
216 = "それよりカズマさん。\\nこの商品、ここに並べようかなって\\n思うんですけど。"

# カズマ
# ああ、確かにそこに置いた方が\n見栄えがいいかもな。
195 = "ああ、確かにそこに置いた方が\\n見栄えがいいかもな。"

# ウィズ
# ええ、そうですよね。
204 = "ええ、そうですよね。"

# カズマ
# だったら、元々置いてあるやつは仕舞って……\nいや、こっちのをどかして場所を作るか。
217 = "だったら、元々置いてあるやつは仕舞って……\\nいや、こっちのをどかして場所を作るか。"

# ウィズ
# はい、それは目立たないところに置いても\n大丈夫だと思います。
223 = "はい、それは目立たないところに置いても\\n大丈夫だと思います。"

# カズマ
# よし、じゃあ入れ替えするか。
230 = "よし、じゃあ入れ替えするか。"

# ウィズ
# はい！
224 = "はい！"

# めぐみん
# んー……。
231 = "んー……。"

# カズマ
# なんだよ、ジロジロ見て。
221 = "なんだよ、ジロジロ見て。"

# めぐみん
# 今のカズマとウィズを見ていると、\nまるでお店を始めた新婚夫婦のように\n見えてしまいますね。
240 = "今のカズマとウィズを見ていると、\\nまるでお店を始めた新婚夫婦のように\\n見えてしまいますね。"

# カズマ
# はあ？
222 = "はあ？"

# ウィズ
# え……ええっ！？
203 = "え……ええっ！？"

# カズマ
# いや待て！\n何をわけのわからんことを言ってるんだ！
201 = "いや待て！\\n何をわけのわからんことを言ってるんだ！"

# アクア
# あらら、なに？\nそういうことだったら、私が盛大に\n祝福の儀式をしてさしあげましょうか？
197 = "あらら、なに？\\nそういうことだったら、私が盛大に\\n祝福の儀式をしてさしあげましょうか？"

# ウィズ
# や、やめて下さいっ！\nそんなことされたら、\n儀式の最中に浄化されちゃいますっ！
228 = "や、やめて下さいっ！\\nそんなことされたら、\\n儀式の最中に浄化されちゃいますっ！"

# カズマ（Ｍ）
# display as カズマ
# （夫婦？　祝福の儀式？\n　な、何でそんなことに！？）
269 = "（夫婦？　祝福の儀式？\\n　な、何でそんなことに！？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、でも、嘘から出た誠なんて言葉もある！\n　非モテ童貞の俺にこんなチャンスが来るなんて\n　滅多にないぞ！？）
263 = "（いや、でも、嘘から出た誠なんて言葉もある！\\n　非モテ童貞の俺にこんなチャンスが来るなんて\\n　滅多にないぞ！？）"

# ダクネス
# ん？　なんだ？\nみんながいると聞いてやってきたら、\nカズマとウィズが結婚するのか？
232 = "ん？　なんだ？\\nみんながいると聞いてやってきたら、\\nカズマとウィズが結婚するのか？"

# カズマ
# はい！\nよろしくお願いしますっ！
225 = "はい！\\nよろしくお願いしますっ！"

# ウィズ
# えっ！？\nよ、よろしくって、ええっ！？\nどういうことですか！？
206 = "えっ！？\\nよ、よろしくって、ええっ！？\\nどういうことですか！？"

# めぐみん
# そういうことなのではないでしょうか？
215 = "そういうことなのではないでしょうか？"

# ウィズ
# か、か、カズマさんっ！\n冗談は、その、ええと、\n言って良いときと悪いときがっ！
209 = "か、か、カズマさんっ！\\n冗談は、その、ええと、\\n言って良いときと悪いときがっ！"

# カズマ
# 大丈夫だよ、幸せにするからさ。
244 = "大丈夫だよ、幸せにするからさ。"

# ウィズ
# え……ええええええ～っ！？
202 = "え……ええええええ～っ！？"

# ダクネス
# おお。\n冗談だと思ったら本気だったのか。
208 = "おお。\\n冗談だと思ったら本気だったのか。"

# めぐみん
# そういうことでしたら、まあ、祝福しますよ。\n末永くお幸せに。
214 = "そういうことでしたら、まあ、祝福しますよ。\\n末永くお幸せに。"

# ウィズ
# ちょちょ、ちょっと待って下さい！？\nう、嬉しくないわけじゃないですけど、\n結婚とか、いきなりすぎて……。
219 = "ちょちょ、ちょっと待って下さい！？\\nう、嬉しくないわけじゃないですけど、\\n結婚とか、いきなりすぎて……。"

# アクア
# カズマ、運だけはいいから\n商売下手なウィズとは\nいい組み合わせだと思うわよ？
236 = "カズマ、運だけはいいから\\n商売下手なウィズとは\\nいい組み合わせだと思うわよ？"

# ウィズ
# そういうことじゃなくて！\nあの、あう、あの、はうう～～！！
213 = "そういうことじゃなくて！\\nあの、あう、あの、はうう～～！！"

# ウィズ
# ……あう。
193 = "……あう。"

# カズマ
# おい、ウィズ！？
207 = "おい、ウィズ！？"

# めぐみん
# 混乱しすぎて、\nオーバーヒートしちゃったみたいですね。
248 = "混乱しすぎて、\\nオーバーヒートしちゃったみたいですね。"

# アクア
# この程度の冗談で？\n本当に結婚するってことになったら\n大変ねぇ、カズマ？
210 = "この程度の冗談で？\\n本当に結婚するってことになったら\\n大変ねぇ、カズマ？"

# カズマ
# い、いやいや！\n何言ってんだよアクア！\nそれよりウィズを介抱しないと！
198 = "い、いやいや！\\n何言ってんだよアクア！\\nそれよりウィズを介抱しないと！"

# カズマ（Ｍ）
# display as カズマ
# （俺とウィズが結婚、か。\n　確かに、ここでずっと働くのもいいかなー\n　なんて、一瞬、考えはしたけど）
268 = "（俺とウィズが結婚、か。\\n　確かに、ここでずっと働くのもいいかなー\\n　なんて、一瞬、考えはしたけど）"

# カズマ（Ｍ）
# display as カズマ
# （そんな未来が……あったりするんだろうか？）
266 = "（そんな未来が……あったりするんだろうか？）"

