# root_f22.txt.scn

[info]
0 = ""

[characters]
283 = "カズマ"
279 = "アクア"
280 = "ウィズ"
284 = "カズマ（Ｍ）"

[character_subs]
# 283 = "カズマ"

[script]
# lines: 62

# カズマ
# いいか、貰った金は全部返すんだ。\nそれから、特別報酬が出たらウィズと山分けしろ！
241 = "いいか、貰った金は全部返すんだ。\\nそれから、特別報酬が出たらウィズと山分けしろ！"

# アクア
# な、なんでよっ！？
271 = "な、なんでよっ！？"

# カズマ
# 正式に依頼として受けてたのはウィズだからだ。
299 = "正式に依頼として受けてたのはウィズだからだ。"

# アクア
# そんなこと私、知らなかったもの！
262 = "そんなこと私、知らなかったもの！"

# ウィズ
# あの、私のことは気にしなくて結構ですので。
238 = "あの、私のことは気にしなくて結構ですので。"

# アクア
# ほ、ほら！\nウィズもこう言ってるし！
278 = "ほ、ほら！\\nウィズもこう言ってるし！"

# カズマ
# ウィズは自腹で聖水を買って\n町の人を助けてるんだぞ。
281 = "ウィズは自腹で聖水を買って\\n町の人を助けてるんだぞ。"

# カズマ
# こういうのは、本来なら\nアークプリーストの\nいや、女神のお前がやるべき事だろ。
255 = "こういうのは、本来なら\\nアークプリーストの\\nいや、女神のお前がやるべき事だろ。"

# カズマ
# それをリッチーのウィズに全部させといて\nその上、報酬を掠め取る？\n女神としてのプライドはどこにいったんだ？
260 = "それをリッチーのウィズに全部させといて\\nその上、報酬を掠め取る？\\n女神としてのプライドはどこにいったんだ？"

# アクア
# だ、だってだって！\nこの世はお金がすべてだし！
263 = "だ、だってだって！\\nこの世はお金がすべてだし！"

# カズマ
# 女神のお前がそれを言うなよ……。
294 = "女神のお前がそれを言うなよ……。"

# アクア
# ねえ、お願いよカズマさん。\nスカルドラゴン討伐の報酬がすぐに入ると思って\n私借金しちゃったの！
273 = "ねえ、お願いよカズマさん。\\nスカルドラゴン討伐の報酬がすぐに入ると思って\\n私借金しちゃったの！"

# カズマ（Ｍ）
# display as カズマ
# （は？）
320 = "（は？）"

# アクア
# 酒場のつけも増えちゃったし、\n今すぐお金が必要なの！
317 = "酒場のつけも増えちゃったし、\\n今すぐお金が必要なの！"

# カズマ
# ああ、もう、自業自得だろうが！\nてか、くっつくな鬱陶しい！
236 = "ああ、もう、自業自得だろうが！\\nてか、くっつくな鬱陶しい！"

# アクア
# ねえカズマさん、今回だけは見逃して！
274 = "ねえカズマさん、今回だけは見逃して！"

# カズマ
# だから、くっつくなっ！\nこっちは重たいバッグを持ってて――
264 = "だから、くっつくなっ！\\nこっちは重たいバッグを持ってて――"

# ウィズ
# えっ？　あっ！？
248 = "えっ？　あっ！？"

# カズマ（Ｍ）
# display as カズマ
# （へ？）
321 = "（へ？）"

# カズマ
# うおっ！！\nだ、大丈夫か、ウィズ！？
245 = "うおっ！！\\nだ、大丈夫か、ウィズ！？"

# ウィズ
# きゃあああああっ！！　聖水が、聖水がっ！
252 = "きゃあああああっ！！　聖水が、聖水がっ！"

# カズマ
# うわ！　大丈夫かウィズ！？
246 = "うわ！　大丈夫かウィズ！？"

# ウィズ
# あ、熱いです！\nチリチリしますっ、いや、いやぁっ！
235 = "あ、熱いです！\\nチリチリしますっ、いや、いやぁっ！"

# カズマ
# こ、こら！\n嫁入り前の娘がこんなところで服を脱ぐんじゃない！
253 = "こ、こら！\\n嫁入り前の娘がこんなところで服を脱ぐんじゃない！"

# アクア
# 嫁入り後なら脱いでもいいの？
295 = "嫁入り後なら脱いでもいいの？"

# カズマ
# いや、こんな時に冷静なツッコミいれんなよ！
242 = "いや、こんな時に冷静なツッコミいれんなよ！"

# ウィズ
# 熱い！　熱いです！\n肌が焼けちゃいます！！
300 = "熱い！　熱いです！\\n肌が焼けちゃいます！！"

# カズマ
# 落ち着け！\nいいか、ウィズはやれば出来る子だ、\n頑張って落ち着くんだ！
316 = "落ち着け！\\nいいか、ウィズはやれば出来る子だ、\\n頑張って落ち着くんだ！"

# アクア
# とか言いながら、どこを凝視してるのかしら？
269 = "とか言いながら、どこを凝視してるのかしら？"

# カズマ
# どどど、どこも見てねえよ！
270 = "どどど、どこも見てねえよ！"

# ウィズ
# ひぃぃぃんっ！\n中まで染みこんでて！
275 = "ひぃぃぃんっ！\\n中まで染みこんでて！"

# カズマ
# 待て、ウィズ！\nそれ以上脱いだら！
297 = "待て、ウィズ！\\nそれ以上脱いだら！"

# ウィズ
# だって、だって、だってぇ！
265 = "だって、だって、だってぇ！"

# カズマ（Ｍ）
# display as カズマ
# （……あ、そうだ！\n　だったら聖水を洗い流せば！）
318 = "（……あ、そうだ！\\n　だったら聖水を洗い流せば！）"

# カズマ
# クリエイト・ウォーター！！
287 = "クリエイト・ウォーター！！"

# ウィズ
# ひゃあっ！？\nつ、冷たいですっ！
277 = "ひゃあっ！？\\nつ、冷たいですっ！"

# カズマ
# ちょっと我慢してくれ！\nおいアクア、お前も手伝え！
266 = "ちょっと我慢してくれ！\\nおいアクア、お前も手伝え！"

# アクア
# 私が作り出す水は聖水みたいなものよ？\nそれをかけたらリッチーだろうが\n溶けてなくなるわ。
314 = "私が作り出す水は聖水みたいなものよ？\\nそれをかけたらリッチーだろうが\\n溶けてなくなるわ。"

# カズマ（Ｍ）
# display as カズマ
# （なっ！？\n　無駄に聖属性備えやがって！\n　くそ、どうすればいいんだ！？）
319 = "（なっ！？\\n　無駄に聖属性備えやがって！\\n　くそ、どうすればいいんだ！？）"

# カズマ
# そうだウィズ、川だ、川！！\n川に飛び込め！
257 = "そうだウィズ、川だ、川！！\\n川に飛び込め！"

# ウィズ
# えっ、ええ！？\nこんな暗い中で川に入るなんて怖いです！
247 = "えっ、ええ！？\\nこんな暗い中で川に入るなんて怖いです！"

# カズマ
# 乙女か！
291 = "乙女か！"

# ウィズ
# 私だって女の子ですよ！
315 = "私だって女の子ですよ！"

# カズマ
# あー、もう、死ぬよりはマシだろ！
240 = "あー、もう、死ぬよりはマシだろ！"

# ウィズ
# あっ、ああ～あっ！？
237 = "あっ、ああ～あっ！？"

# カズマ
# お、俺も手伝うっ！！
249 = "お、俺も手伝うっ！！"

# ウィズ
# お気持ちはありがたいですけど、\nさすがにそれは！！
250 = "お気持ちはありがたいですけど、\\nさすがにそれは！！"

# カズマ
# いや、やましい気持ちなんて\nこれっぽっちも無いから！
243 = "いや、やましい気持ちなんて\\nこれっぽっちも無いから！"

# ウィズ
# その割には、手の動きがいやらしいですよ！？
258 = "その割には、手の動きがいやらしいですよ！？"

# カズマ
# そんなことは無い、決して無い！
261 = "そんなことは無い、決して無い！"

# ウィズ
# こ、来ないで下さ～い！！
254 = "こ、来ないで下さ～い！！"

# カズマ
# いやだから、もう時間が無いぞ！\n身体が光り始めてる！
244 = "いやだから、もう時間が無いぞ！\\n身体が光り始めてる！"

# アクア
# あー、これ、聖水に触れ過ぎて\n浄化されかけてるわね。
239 = "あー、これ、聖水に触れ過ぎて\\n浄化されかけてるわね。"

# ウィズ
# ひいいいいっ！\nな、なんとかして下さーい！
276 = "ひいいいいっ！\\nな、なんとかして下さーい！"

# カズマ
# なんとかするから早く脱がせろ！！
272 = "なんとかするから早く脱がせろ！！"

# ウィズ
# それは嫌です！
259 = "それは嫌です！"

# ウィズ
# って、あっ、えっ、ああ～！？
267 = "って、あっ、えっ、ああ～！？"

# カズマ
# クリエイト・ウォーター！\nクリエイト・ウォーター！！\nクリエイト・ウォーター！！！
286 = "クリエイト・ウォーター！\\nクリエイト・ウォーター！！\\nクリエイト・ウォーター！！！"

# ウィズ
# つ、冷たいですけど、熱いですっ！\nあっ、腕が、腕が浄化されかけてます～！
268 = "つ、冷たいですけど、熱いですっ！\\nあっ、腕が、腕が浄化されかけてます～！"

# カズマ（Ｍ）
# display as カズマ
# （ダメだ、クリエイト・ウォーターじゃ\n　いくら掛けても間に合わない！）
322 = "（ダメだ、クリエイト・ウォーターじゃ\\n　いくら掛けても間に合わない！）"

# カズマ
# こうなったら……ウィズ、ごめんっ！！
256 = "こうなったら……ウィズ、ごめんっ！！"

# ウィズ
# きゃ、きゃあっ！？
251 = "きゃ、きゃあっ！？"

[selections]
282 = "ウィズを川に落とす"
298 = "服を脱がせる"
285 = "クリエイト・ウォーターを続ける"
