# root_d16.txt.scn

[info]
0 = ""

[characters]
256 = "カズマ（Ｍ）"
257 = "クリス"
255 = "カズマ"
272 = "戦士風の男冒険者"
276 = "盗賊風の男冒険者"

[character_subs]
# 255 = "カズマ"
271 = "戦士冒険者"
275 = "盗賊冒険者"

[script]
# lines: 57

# カズマ（Ｍ）
# display as カズマ
# （くうう、しつこい奴らだな！\n　どこまで追いかけてくるつもりだ？\n　いい加減、諦めろってんだ！）
298 = "（くうう、しつこい奴らだな！\\n　どこまで追いかけてくるつもりだ？\\n　いい加減、諦めろってんだ！）"

# カズマ（Ｍ）
# display as カズマ
# （っと！\n　こっちは表通りと繋がってるからダメだ。\n　別の道を行かないと……）
302 = "（っと！\\n　こっちは表通りと繋がってるからダメだ。\\n　別の道を行かないと……）"

# クリス
# うう、あう、う、うううう～……。
227 = "うう、あう、う、うううう～……。"

# カズマ
# おいクリス、なんでもたついてるんだよ。\nこのままじゃ捕まっちまうぞ。
235 = "おいクリス、なんでもたついてるんだよ。\\nこのままじゃ捕まっちまうぞ。"

# クリス
# わ、わかってるよ。\nわかってるけど、\n下がスースーして気になっちゃって。
253 = "わ、わかってるよ。\\nわかってるけど、\\n下がスースーして気になっちゃって。"

# カズマ
# スースーする？
259 = "スースーする？"

# クリス
# ちょっと！　どこ見てるのさ！
244 = "ちょっと！　どこ見てるのさ！"

# カズマ
# い、いや、スパッツも穿いてるのに\nそういうの気になるんだって思ってさ。
222 = "い、いや、スパッツも穿いてるのに\\nそういうの気になるんだって思ってさ。"

# クリス
# 普段穿いている物がないんだから\n気になるのは当然でしょ！
273 = "普段穿いている物がないんだから\\n気になるのは当然でしょ！"

# カズマ
# でもその格好なら、\n穿いても穿いていなくても同じじゃないか。
247 = "でもその格好なら、\\n穿いても穿いていなくても同じじゃないか。"

# クリス
# も、もう！\nそ、それ以上言ったら、問答無用で\n投降するからね！
251 = "も、もう！\\nそ、それ以上言ったら、問答無用で\\n投降するからね！"

# カズマ
# すまん、俺が悪かった！\nだからそれだけは止めてください、\nお願いします！
238 = "すまん、俺が悪かった！\\nだからそれだけは止めてください、\\nお願いします！"

# クリス
# うぅぅ、スースーして気持ち悪い……。
226 = "うぅぅ、スースーして気持ち悪い……。"

# カズマ（Ｍ）
# display as カズマ
# （うーむ、クリスの動きが鈍くなるのは\n　予想外だったな）
297 = "（うーむ、クリスの動きが鈍くなるのは\\n　予想外だったな）"

# 戦士風の男冒険者
# display as 戦士冒険者
# おいっ、いたぞ！\nクリスとカズマだ！
234 = "おいっ、いたぞ！\\nクリスとカズマだ！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# 絶対に逃がすな！\n反対側からも回り込めっ！！
294 = "絶対に逃がすな！\\n反対側からも回り込めっ！！"

# カズマ（Ｍ）
# display as カズマ
# （ちっ、気付かれたか！\n　このままじゃ追いつかれるのも時間の問題だ）
301 = "（ちっ、気付かれたか！\\n　このままじゃ追いつかれるのも時間の問題だ）"

# クリス
# うぅ……。
225 = "うぅ……。"

# カズマ（Ｍ）
# display as カズマ
# （けど、肝心のクリスがこの調子じゃ……。\n　走る速度を上げる訳にもいかないし\n　仕方ない、俺が食い止めるか）
299 = "（けど、肝心のクリスがこの調子じゃ……。\\n　走る速度を上げる訳にもいかないし\\n　仕方ない、俺が食い止めるか）"

# カズマ
# クリス、ここは俺に任せろ。\nお前はいつでも逃げられるように\n準備しておけ。
258 = "クリス、ここは俺に任せろ。\\nお前はいつでも逃げられるように\\n準備しておけ。"

# クリス
# ちょ、ちょっとカズマ、何やってるの？\nその構え、まさかとは思うけど……\nまたスティールするつもり？
242 = "ちょ、ちょっとカズマ、何やってるの？\\nその構え、まさかとは思うけど……\\nまたスティールするつもり？"

# カズマ
# だって、このままじゃ追いつかれるだろ！
241 = "だって、このままじゃ追いつかれるだろ！"

# クリス
# 信じられない……！\nあんなことがあったのに\n懲りずにまだやる気！？
266 = "信じられない……！\\nあんなことがあったのに\\n懲りずにまだやる気！？"

# クリス
# 絶対に止めてよ！？\nもし、あたしのズボンが盗まれたら\n一体どうするつもりなわけ！？
293 = "絶対に止めてよ！？\\nもし、あたしのズボンが盗まれたら\\n一体どうするつもりなわけ！？"

# カズマ（Ｍ）
# display as カズマ
# （それはそれで……）
300 = "（それはそれで……）"

# クリス
# 何考えてるのよ！
264 = "何考えてるのよ！"

# カズマ
# つ、次はちゃんと\n狙う相手を決めてやるから大丈夫だ！\nさっきみたいなことは二度とない！　俺を信じろ！
246 = "つ、次はちゃんと\\n狙う相手を決めてやるから大丈夫だ！\\nさっきみたいなことは二度とない！　俺を信じろ！"

# クリス
# そういうのは、信用のある人が言うものなの！
239 = "そういうのは、信用のある人が言うものなの！"

# カズマ
# え……。\n俺、信用がないの？
229 = "え……。\\n俺、信用がないの？"

# クリス
# それは誰よりもキミが知ってるでしょ？\n自分の胸に手を当てて聞いてごらん？
240 = "それは誰よりもキミが知ってるでしょ？\\n自分の胸に手を当てて聞いてごらん？"

# カズマ
# 多少の行き違いはあったかもしれない。\nだが、過去のことを引きずっても仕方ない。\nそうだろう？
268 = "多少の行き違いはあったかもしれない。\\nだが、過去のことを引きずっても仕方ない。\\nそうだろう？"

# クリス
# もし、ここでスティールを使ったら、\nあたしは一生、キミを許さないからね。
252 = "もし、ここでスティールを使ったら、\\nあたしは一生、キミを許さないからね。"

# カズマ
# んなこと言ったって……。
254 = "んなこと言ったって……。"

# クリス
# とにかくダメったらダメ！\n絶対ダメ！！！\n何がなんでもスティールは禁止！！
248 = "とにかくダメったらダメ！\\n絶対ダメ！！！\\n何がなんでもスティールは禁止！！"

# カズマ（Ｍ）
# display as カズマ
# （参ったなぁ。\n　そう言われても俺が使える\n　魔法やスキルなんて限られてる）
303 = "（参ったなぁ。\\n　そう言われても俺が使える\\n　魔法やスキルなんて限られてる）"

# カズマ（Ｍ）
# display as カズマ
# （追いつかれるまでもう時間がない。\n　あいつらを足止めする方法は……）
304 = "（追いつかれるまでもう時間がない。\\n　あいつらを足止めする方法は……）"

# カズマ
# うん……クリスのパンツ。
228 = "うん……クリスのパンツ。"

# クリス
# え？　あたしのパンツ？
232 = "え？　あたしのパンツ？"

# カズマ
# 尊い犠牲に、敬礼！
269 = "尊い犠牲に、敬礼！"

# クリス
# え？　え？　何？？　どういうこと？？
233 = "え？　え？　何？？　どういうこと？？"

# カズマ
# おーい、お前ら！　よぉく聞けっ！\nここにある物が何かわかるかぁ！？
237 = "おーい、お前ら！　よぉく聞けっ！\\nここにある物が何かわかるかぁ！？"

# クリス
# え！？
231 = "え！？"

# 戦士風の男冒険者
# display as 戦士冒険者
# な、なんだ？\nあいつ何を持ってるんだ？
249 = "な、なんだ？\\nあいつ何を持ってるんだ？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# あれは布か？\n遠くてよく見えないな。
221 = "あれは布か？\\n遠くてよく見えないな。"

# カズマ
# 男なら誰もが憧れる、\n脱ぎたてホヤホヤ、盗りたてホヤホヤ、\nその名も……クリスのパンツだーーっ！！
274 = "男なら誰もが憧れる、\\n脱ぎたてホヤホヤ、盗りたてホヤホヤ、\\nその名も……クリスのパンツだーーっ！！"

# クリス
# ちょっと、カズマーー！！
243 = "ちょっと、カズマーー！！"

# カズマ
# 触れたいかぁ！　愛でたいかぁ！\nクリスのパンツを肴に、１杯やりたいかぁ～！
296 = "触れたいかぁ！　愛でたいかぁ！\\nクリスのパンツを肴に、１杯やりたいかぁ～！"

# クリス
# 何言ってんの！\n待ってカズマ、冷静になって！
265 = "何言ってんの！\\n待ってカズマ、冷静になって！"

# カズマ
# ほぉら、行くぞぉ～？\n受け取れーーーーーーーいっ！！
250 = "ほぉら、行くぞぉ～？\\n受け取れーーーーーーーいっ！！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# おおおおおおおお！！\nクリスのパンツだ！！
236 = "おおおおおおおお！！\\nクリスのパンツだ！！"

# クリス
# いぃやあああああああああああああああ！！
223 = "いぃやあああああああああああああああ！！"

# カズマ
# パンツ１枚にあんなに必死になって。\n男とはなんて醜く、さもしい生き物なのだろうか。
260 = "パンツ１枚にあんなに必死になって。\\n男とはなんて醜く、さもしい生き物なのだろうか。"

# クリス
# ちょっと！？\nなんてことしてくれるのさぁ！？
245 = "ちょっと！？\\nなんてことしてくれるのさぁ！？"

# カズマ
# 落ち着け、クリス！\nあいつらがパンツに群がってるうちに\nここから逃げるぞ！
295 = "落ち着け、クリス！\\nあいつらがパンツに群がってるうちに\\nここから逃げるぞ！"

# クリス
# えっ、で、でも、あたしのパンツがっ！！
230 = "えっ、で、でも、あたしのパンツがっ！！"

# カズマ
# いいから行くぞ！
224 = "いいから行くぞ！"

# クリス
# あああ、あたしのパンツーーーー！！
220 = "あああ、あたしのパンツーーーー！！"

