# root_c03.txt.scn

[info]
0 = ""

[characters]
267 = "アクア"
264 = "めぐみん"
272 = "ダクネス"
269 = "カズマ"

[character_subs]

[script]
# lines: 57

# アクア
# ごちそうさま！
240 = "ごちそうさま！"

# めぐみん
# ごちそうさまでした。
239 = "ごちそうさまでした。"

# ダクネス
# しかし、カズマはどうしたんだ？\nまさかまだ寝てるのか？
241 = "しかし、カズマはどうしたんだ？\\nまさかまだ寝てるのか？"

# めぐみん
# 何度も呼んだのですが、\n返事がないんですよね。
275 = "何度も呼んだのですが、\\n返事がないんですよね。"

# アクア
# 死んでたら笑うわね。
286 = "死んでたら笑うわね。"

# めぐみん
# いやいやいや、ちっとも笑えませんよ！
231 = "いやいやいや、ちっとも笑えませんよ！"

# アクア
# 想像してみなさい、めぐみん。\nカズマの体が上半身だけベッドからずり落ちてるの。\nしかも死に顔は極上に間抜けで……。
284 = "想像してみなさい、めぐみん。\\nカズマの体が上半身だけベッドからずり落ちてるの。\\nしかも死に顔は極上に間抜けで……。"

# めぐみん
# ぶふっ！
259 = "ぶふっ！"

# アクア
# ほら、笑えるでしょ？
260 = "ほら、笑えるでしょ？"

# ダクネス
# こらこら、死を愚弄するようなことを言うな。\nエリス様から罰が下るぞ。
237 = "こらこら、死を愚弄するようなことを言うな。\\nエリス様から罰が下るぞ。"

# めぐみん
# そ、そうですね。\nカズマ、安らかに逝ってください。
244 = "そ、そうですね。\\nカズマ、安らかに逝ってください。"

# ダクネス
# いや、死んでないからな？
230 = "いや、死んでないからな？"

# ダクネス
# （しかし、あいつは本当にどうしたんだ。\n　やはり体の調子がどこか悪いのか？）
315 = "（しかし、あいつは本当にどうしたんだ。\\n　やはり体の調子がどこか悪いのか？）"

# カズマ
# ふぁぁぁ～、あぁぁ～。\nおーっす、みんな。
258 = "ふぁぁぁ～、あぁぁ～。\\nおーっす、みんな。"

# ダクネス
# おっ、噂をすれば――
235 = "おっ、噂をすれば――"

# めぐみん
# アクアー！　大変です！\nカズマが化けて出てきましたよ！
268 = "アクアー！　大変です！\\nカズマが化けて出てきましたよ！"

# カズマ
# はあ？
257 = "はあ？"

# アクア
# 安心しなさい、めぐみん。\n私がすぐに浄化するから！
278 = "安心しなさい、めぐみん。\\n私がすぐに浄化するから！"

# カズマ
# ダクネス、飯を用意してくれ。
273 = "ダクネス、飯を用意してくれ。"

# めぐみん
# むむ、ちょっと無視をしないでくださいよ。\nノリが悪いですね。
263 = "むむ、ちょっと無視をしないでくださいよ。\\nノリが悪いですね。"

# カズマ
# 寝起きでそのテンションはキツいんだ。
281 = "寝起きでそのテンションはキツいんだ。"

# カズマ
# だいたい化けて出たとか浄化とかなんなんだ。\n人を勝手に殺すなよ。
250 = "だいたい化けて出たとか浄化とかなんなんだ。\\n人を勝手に殺すなよ。"

# アクア
# こんな時間まで寝てるカズマが悪いんでしょ。\nそれに朝食はもうありませんから。
238 = "こんな時間まで寝てるカズマが悪いんでしょ。\\nそれに朝食はもうありませんから。"

# カズマ
# はあ、なんでだよ！
256 = "はあ、なんでだよ！"

# めぐみん
# 朝食の時間に起きてこなかったからですよ。
285 = "朝食の時間に起きてこなかったからですよ。"

# ダクネス
# まあ、待て。\nカズマの言い分も聞こうじゃないか。
261 = "まあ、待て。\\nカズマの言い分も聞こうじゃないか。"

# カズマ
# そうだ！　俺の言い分も聞け！
247 = "そうだ！　俺の言い分も聞け！"

# ダクネス
# カズマ、具合が悪かったとか、\nそういう事情があるのだろう？
270 = "カズマ、具合が悪かったとか、\\nそういう事情があるのだろう？"

# カズマ
# いや、ただ寝坊しただけだけど。
228 = "いや、ただ寝坊しただけだけど。"

# ダクネス
# そ、そうか、せっかくのフォローが台無しだな。
243 = "そ、そうか、せっかくのフォローが台無しだな。"

# アクア
# とにかく朝食はありませんから。\n食べたかったらダクネスに頼まないで\n自分で用意しなさい。
252 = "とにかく朝食はありませんから。\\n食べたかったらダクネスに頼まないで\\n自分で用意しなさい。"

# めぐみん
# そうですよ。\nダクネスはカズマの召使いじゃないんですからね。
248 = "そうですよ。\\nダクネスはカズマの召使いじゃないんですからね。"

# ダクネス
# 別に、カズマ１人の朝食を作るくらい\nなんでもないことだぞ？
276 = "別に、カズマ１人の朝食を作るくらい\\nなんでもないことだぞ？"

# アクア
# そういう問題じゃなくて、\n甘やかしたらカズマがつけあがるでしょ。
245 = "そういう問題じゃなくて、\\n甘やかしたらカズマがつけあがるでしょ。"

# めぐみん
# 怠惰は罪です。\nカズマ、これは愛の鞭だと思って\nそのだらけ癖を矯正してください。
283 = "怠惰は罪です。\\nカズマ、これは愛の鞭だと思って\\nそのだらけ癖を矯正してください。"

# カズマ
# うん、確かにお前らの言うとおりだ。
234 = "うん、確かにお前らの言うとおりだ。"

# アクア
# ちょっと何よ、随分と素直じゃない。
251 = "ちょっと何よ、随分と素直じゃない。"

# めぐみん
# やはり体調が悪いのでは？
265 = "やはり体調が悪いのでは？"

# アクア
# それともまた\nくだらない呪いにかかったのかしら。
249 = "それともまた\\nくだらない呪いにかかったのかしら。"

# ダクネス
# なっ、今度は何を盗むというんだ！
255 = "なっ、今度は何を盗むというんだ！"

# カズマ
# いや呪いなんてかかってないし。
232 = "いや呪いなんてかかってないし。"

# ダクネス
# そうか……。
246 = "そうか……。"

# カズマ
# がっかりするなよ！
236 = "がっかりするなよ！"

# アクア
# じゃあ、いったい何をたくらんでいるのかしら。
242 = "じゃあ、いったい何をたくらんでいるのかしら。"

# カズマ
# まず、その思考がおかしいだろ？\nなんで俺が素直だと体調不良とか呪いとかのせいに\nなるんだよ！
262 = "まず、その思考がおかしいだろ？\\nなんで俺が素直だと体調不良とか呪いとかのせいに\\nなるんだよ！"

# めぐみん
# カズマだからでは？
271 = "カズマだからでは？"

# カズマ
# うわー、説得力がありすぎて言い返せない。
233 = "うわー、説得力がありすぎて言い返せない。"

# ダクネス
# なあ、カズマ。\n体の調子が悪いとかそういうわけではないのだな？
254 = "なあ、カズマ。\\n体の調子が悪いとかそういうわけではないのだな？"

# カズマ
# ああ、いたって健康だし、\n当然呪いにもかかってないよ。
227 = "ああ、いたって健康だし、\\n当然呪いにもかかってないよ。"

# カズマ
# 寝坊したのは、昨夜\n寝付きが悪かったせいだ。
280 = "寝坊したのは、昨夜\\n寝付きが悪かったせいだ。"

# ダクネス
# 寝付きが？
279 = "寝付きが？"

# カズマ
# 色々考えごとをしててさ。
314 = "色々考えごとをしててさ。"

# ダクネス
# （考えごとを……）
317 = "（考えごとを……）"

# カズマ
# んじゃ、俺は外でなんか食ってくるわ。
266 = "んじゃ、俺は外でなんか食ってくるわ。"

# ダクネス
# いや、朝食を用意するから少し待っていろ。
229 = "いや、朝食を用意するから少し待っていろ。"

# カズマ
# どうせ街に出るつもりだったし、\n気持ちだけで十分だ。\nありがとうな、ダクネス。
253 = "どうせ街に出るつもりだったし、\\n気持ちだけで十分だ。\\nありがとうな、ダクネス。"

# ダクネス
# （なんだ、この妙な違和感は。\n　本当に……カズマは大丈夫なのか？）
316 = "（なんだ、この妙な違和感は。\\n　本当に……カズマは大丈夫なのか？）"

