# root_d04.txt.scn

[info]
0 = ""

[characters]
155 = "カズマ（Ｍ）"
153 = "アクア"
154 = "カズマ"

[character_subs]
# 154 = "カズマ"
188 = "？？？"

[script]
# lines: 28

# カズマ（Ｍ）
# display as カズマ
# （クリスのやつ、\n　結構歩いてるけど色々寄り道してるし\n　特に目的地はないみたいだな）
187 = "（クリスのやつ、\\n　結構歩いてるけど色々寄り道してるし\\n　特に目的地はないみたいだな）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、それならそれでいいか。\n　こうして後をつけていれば、そのうちクリスの\n　欲しい物とか、わかるかもしれないし）
186 = "（まあ、それならそれでいいか。\\n　こうして後をつけていれば、そのうちクリスの\\n　欲しい物とか、わかるかもしれないし）"

# アクア
# display as ？？？
# あ、カズマー！
138 = "あ、カズマー！"

# カズマ（Ｍ）
# display as カズマ
# （こ、この声は……！）
184 = "（こ、この声は……！）"

# アクア
# こんな所で何してるのよ？\n暇なら、ちょっと手伝って欲しいことが\nあるんですけど。
143 = "こんな所で何してるのよ？\\n暇なら、ちょっと手伝って欲しいことが\\nあるんですけど。"

# カズマ
# おい、アクア。\n声が大きい。少し静かにしろ。
142 = "おい、アクア。\\n声が大きい。少し静かにしろ。"

# アクア
# 何、いったい今度は何をたくらんでるわけ？
160 = "何、いったい今度は何をたくらんでるわけ？"

# カズマ
# だから静かにしろって。\n大声で話してると気付かれるだろ？
148 = "だから静かにしろって。\\n大声で話してると気付かれるだろ？"

# アクア
# 気付かれるって、誰によ？
164 = "気付かれるって、誰によ？"

# カズマ
# クリスだよ。\nほら、この先を歩いてるのが見えるだろ？
156 = "クリスだよ。\\nほら、この先を歩いてるのが見えるだろ？"

# アクア
# あんた、ついにストーカーにまで落ちたわけ？
140 = "あんた、ついにストーカーにまで落ちたわけ？"

# アクア
# 引きこもり童貞ニートが犯罪者とか\nマジ引くんですけど。
163 = "引きこもり童貞ニートが犯罪者とか\\nマジ引くんですけど。"

# カズマ
# 人聞きの悪いこと言うな！\nこれには深い事情があるんだよ！
159 = "人聞きの悪いこと言うな！\\nこれには深い事情があるんだよ！"

# アクア
# ああ、自分がストーカーだってわかってないのね。\n勘違い変質者は誰でもそう言うのよ。
139 = "ああ、自分がストーカーだってわかってないのね。\\n勘違い変質者は誰でもそう言うのよ。"

# カズマ
# なんだ、その憐れみに満ちた眼差しは！\n断じて俺はストーカーなんかじゃないからな！
150 = "なんだ、その憐れみに満ちた眼差しは！\\n断じて俺はストーカーなんかじゃないからな！"

# アクア
# ねえ、いいのそんな大きな声出して。\nばれるわよ？
151 = "ねえ、いいのそんな大きな声出して。\\nばれるわよ？"

# カズマ（Ｍ）
# display as カズマ
# （っと！\n　クリスは……良かった、\n　こっちの声は届いていないみたいだな）
185 = "（っと！\\n　クリスは……良かった、\\n　こっちの声は届いていないみたいだな）"

# カズマ
# まあ、その、あれだ。\n諸事情により、クリスのことを\n調べなくちゃならないんだよ。
152 = "まあ、その、あれだ。\\n諸事情により、クリスのことを\\n調べなくちゃならないんだよ。"

# カズマ
# だからこうしてクリスを追いかけているのは\n必然性によるものであるからして、\n決して、俺の趣味によるものじゃない。
147 = "だからこうしてクリスを追いかけているのは\\n必然性によるものであるからして、\\n決して、俺の趣味によるものじゃない。"

# アクア
# 良くわからないけど、\nようはクリスを捕まえたいのね？
181 = "良くわからないけど、\\nようはクリスを捕まえたいのね？"

# カズマ
# そうじゃない！\n誰もそんな話してないだろうが！\nお前、ちゃんと聞いてたのか？
145 = "そうじゃない！\\n誰もそんな話してないだろうが！\\nお前、ちゃんと聞いてたのか？"

# アクア
# あー、もう、わっかんないわね。\nもっとちゃんと説明しなさいよ。
141 = "あー、もう、わっかんないわね。\\nもっとちゃんと説明しなさいよ。"

# カズマ
# だから、このままだと\nそれこそ１００万エリス払った方がマシだったって\n無茶ぶりを――
146 = "だから、このままだと\\nそれこそ１００万エリス払った方がマシだったって\\n無茶ぶりを――"

# カズマ
# ってあれ、クリスは！？
149 = "ってあれ、クリスは！？"

# アクア
# クリスなら向こうに走って行ったけど？
157 = "クリスなら向こうに走って行ったけど？"

# カズマ
# しまった！\nアクア、続きはまた後でな！
144 = "しまった！\\nアクア、続きはまた後でな！"

# カズマ（Ｍ）
# display as カズマ
# （くそ、アクアに気を取られていて\n　気付かなかった……結構遠くまで行ってるな。\n　間に合うか？）
183 = "（くそ、アクアに気を取られていて\\n　気付かなかった……結構遠くまで行ってるな。\\n　間に合うか？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、今は追いかけるしかない。\n　とにかく走らないと！）
182 = "（いや、今は追いかけるしかない。\\n　とにかく走らないと！）"

