# root_a18.txt.scn

[info]
0 = ""

[characters]
209 = "カズマ（Ｍ）"
207 = "カズマ"
204 = "アクア"
200 = "めぐみん"
210 = "ダクネス"

[character_subs]
# 207 = "カズマ"

[script]
# lines: 33

# カズマ（Ｍ）
# display as カズマ
# （そしてついに、コンテストの日がやってきた）
243 = "（そしてついに、コンテストの日がやってきた）"

# カズマ
# おい、準備はいいか、アクア？
192 = "おい、準備はいいか、アクア？"

# アクア
# ええ、問題ありませんわ。
189 = "ええ、問題ありませんわ。"

# カズマ（Ｍ）
# display as カズマ
# （あのアクアがここまで完璧に仕上がるとは、\n　誰が思っただろうか）
240 = "（あのアクアがここまで完璧に仕上がるとは、\\n　誰が思っただろうか）"

# カズマ（Ｍ）
# display as カズマ
# （めぐみん、ダクネス、ウィズ、そして俺。\n　全員が半信半疑だった）
246 = "（めぐみん、ダクネス、ウィズ、そして俺。\\n　全員が半信半疑だった）"

# カズマ（Ｍ）
# display as カズマ
# （それが、どうだ！\n　こうして目の前に立っているアクアは、\n　エリス様のように優雅な佇まいを見せている）
244 = "（それが、どうだ！\\n　こうして目の前に立っているアクアは、\\n　エリス様のように優雅な佇まいを見せている）"

# カズマ（Ｍ）
# display as カズマ
# （ある意味、プライドを捨ててるなとも\n　思うが……）
241 = "（ある意味、プライドを捨ててるなとも\\n　思うが……）"

# カズマ（Ｍ）
# display as カズマ
# （まあ今は、アクアのプライドなどどうでもいい！\n　すべてはコンテストのため、そして\n　駄女神に女神の風格を備えさせるため！）
245 = "（まあ今は、アクアのプライドなどどうでもいい！\\n　すべてはコンテストのため、そして\\n　駄女神に女神の風格を備えさせるため！）"

# カズマ（Ｍ）
# display as カズマ
# （俺たちの苦労は、無駄にはならなかった……！）
248 = "（俺たちの苦労は、無駄にはならなかった……！）"

# カズマ
# さあ、いよいよだ。\nもうすぐコンテストが始まる。\n生まれ変わったお前を見せてくれ！
194 = "さあ、いよいよだ。\\nもうすぐコンテストが始まる。\\n生まれ変わったお前を見せてくれ！"

# アクア
# ええ。\nみなさんのために、必ず優勝致します。
190 = "ええ。\\nみなさんのために、必ず優勝致します。"

# カズマ（Ｍ）
# display as カズマ
# （おお！　まさかアクアから、\n　こんな謙虚な言葉が聞けるなんて！\n　俺は今、猛烈に感動しているっ！）
242 = "（おお！　まさかアクアから、\\n　こんな謙虚な言葉が聞けるなんて！\\n　俺は今、猛烈に感動しているっ！）"

# カズマ
# 本性をさらけ出すんじゃないぞ？
219 = "本性をさらけ出すんじゃないぞ？"

# アクア
# わかってる――
203 = "わかってる――"

# アクア
# いえ、大丈夫ですわよ？\nそんなヘマは致しませんわ。
187 = "いえ、大丈夫ですわよ？\\nそんなヘマは致しませんわ。"

# カズマ（Ｍ）
# display as カズマ
# （今、一瞬だけ地が出たような？\n　おいおい、大丈夫か？）
247 = "（今、一瞬だけ地が出たような？\\n　おいおい、大丈夫か？）"

# カズマ
# 優勝、頼んだぞ！
214 = "優勝、頼んだぞ！"

# アクア
# もちろんですわ。\n今の私なら、誰にも負ける気がしませんもの。\nすべて、お任せください。
201 = "もちろんですわ。\\n今の私なら、誰にも負ける気がしませんもの。\\nすべて、お任せください。"

# カズマ
# 今のお前ならいけるぜ！
213 = "今のお前ならいけるぜ！"

# アクア
# あら、嬉しい言葉ですわね。\nその期待に応えてみせますわ。
186 = "あら、嬉しい言葉ですわね。\\nその期待に応えてみせますわ。"

# カズマ
# だが、油断は禁物だからな。\n最後まで気を緩めずに行ってくれよ？
196 = "だが、油断は禁物だからな。\\n最後まで気を緩めずに行ってくれよ？"

# アクア
# ええ。\n慢心などせず、最後までやり遂げますわ。
191 = "ええ。\\n慢心などせず、最後までやり遂げますわ。"

# カズマ
# よし、それじゃ行ってこい！
202 = "よし、それじゃ行ってこい！"

# アクア
# はい。\n吉報をお待ちください。
198 = "はい。\\n吉報をお待ちください。"

# めぐみん
# カズマ、カズマ、前にお願いされた件なのですが。
208 = "カズマ、カズマ、前にお願いされた件なのですが。"

# カズマ
# おっ、何か動きはあったか？
193 = "おっ、何か動きはあったか？"

# めぐみん
# ええ、ギルドだけではなく、\nエリス教団も動いてくださいまして。
188 = "ええ、ギルドだけではなく、\\nエリス教団も動いてくださいまして。"

# ダクネス
# エリス教団？　なんの話だ。
206 = "エリス教団？　なんの話だ。"

# カズマ
# そういえば、ダクネスには話してなかったな。
195 = "そういえば、ダクネスには話してなかったな。"

# カズマ
# アクアが背負わされた借金の件、\nこのままやられっぱなしっていうのもシャクだろ。
205 = "アクアが背負わされた借金の件、\\nこのままやられっぱなしっていうのもシャクだろ。"

# めぐみん
# ですので、私とカズマで一計を。
197 = "ですので、私とカズマで一計を。"

# ダクネス
# 一計？
211 = "一計？"

# カズマ
# まあ、この話は後にしようぜ。\nとにかく今は、目の前のコンテストに集中だ。
199 = "まあ、この話は後にしようぜ。\\nとにかく今は、目の前のコンテストに集中だ。"

[selections]
# 219 = "本性をさらけ出すんじゃないぞ？"
# 214 = "優勝、頼んだぞ！"
# 213 = "今のお前ならいけるぜ！"
