# root_f13.txt.scn

[info]
0 = ""

[characters]
184 = "アクア"
189 = "カズマ"
188 = "ウィズ"
190 = "カズマ（Ｍ）"

[character_subs]
# 189 = "カズマ"

[script]
# lines: 34

# アクア
# カーズーマー？\nあんたまたウィズと一緒にいるわけ？
191 = "カーズーマー？\\nあんたまたウィズと一緒にいるわけ？"

# カズマ
# 別にいいだろ。
196 = "別にいいだろ。"

# アクア
# あんたが良くても私のメンツが立たないの！\n女神たる私の小間使いが\nリッチーと一緒にいるなんて！
170 = "あんたが良くても私のメンツが立たないの！\\n女神たる私の小間使いが\\nリッチーと一緒にいるなんて！"

# カズマ
# 誰が小間使いだ！\n従者以下になってるじゃねーか！
219 = "誰が小間使いだ！\\n従者以下になってるじゃねーか！"

# アクア
# ねえ、ちょっとウィズ？
181 = "ねえ、ちょっとウィズ？"

# ウィズ
# ひうっ！？\nな、なんでしょうか？
183 = "ひうっ！？\\nな、なんでしょうか？"

# アクア
# 私の所有物を勝手に持っていかれると\n困るんですけど。
218 = "私の所有物を勝手に持っていかれると\\n困るんですけど。"

# ウィズ
# す、す、すみませんっ。
175 = "す、す、すみませんっ。"

# アクア
# あ、待って、そっかレンタル料を取れば……。
165 = "あ、待って、そっかレンタル料を取れば……。"

# カズマ
# ジー……。
192 = "ジー……。"

# アクア
# 何もしなくてもお金が……。
195 = "何もしなくてもお金が……。"

# カズマ
# ジー……。
# 192 = "ジー……。"

# アクア
# ねえウィズ、１日１０００エリスでどうかしら！
182 = "ねえウィズ、１日１０００エリスでどうかしら！"

# カズマ
# 人をモノ扱いすんな！\nてか、安すぎるだろ！
194 = "人をモノ扱いすんな！\\nてか、安すぎるだろ！"

# アクア
# いった！\nあんた今蹴ったわね！　蹴ったわよね！
171 = "いった！\\nあんた今蹴ったわね！　蹴ったわよね！"

# カズマ
# それよりもアクア、聞きたいことがあるんだ。
177 = "それよりもアクア、聞きたいことがあるんだ。"

# アクア
# それよりもって！\n女神を蹴っておいて、それよりもって！
176 = "それよりもって！\\n女神を蹴っておいて、それよりもって！"

# カズマ
# お前、昨日、悪霊に絡まれたって\n話をしてたよな？
173 = "お前、昨日、悪霊に絡まれたって\\n話をしてたよな？"

# カズマ
# あれ、どうやら街全体で\nそういう事件になってるっぽいんだよ。
169 = "あれ、どうやら街全体で\\nそういう事件になってるっぽいんだよ。"

# アクア
# え？　そうなの？
172 = "え？　そうなの？"

# カズマ
# でさ、昨日の夜中に除霊しに出掛けてたろ？\n街中でなんかそういう騒ぎになりそうな\n兆候ってあったか？
180 = "でさ、昨日の夜中に除霊しに出掛けてたろ？\\n街中でなんかそういう騒ぎになりそうな\\n兆候ってあったか？"

# アクア
# さ、さあ、どうだったかしら？\n私はただ絡んできたやつを片っ端から\n除霊していっただけだから。
174 = "さ、さあ、どうだったかしら？\\n私はただ絡んできたやつを片っ端から\\n除霊していっただけだから。"

# カズマ（Ｍ）
# display as カズマ
# （……ん？\n　アクアの目がすっごい泳いでる？）
220 = "（……ん？\\n　アクアの目がすっごい泳いでる？）"

# アクア
# それ以外のことは何もわかんないわよ？\nええ、なんにも知らないわ。
178 = "それ以外のことは何もわかんないわよ？\\nええ、なんにも知らないわ。"

# カズマ（Ｍ）
# display as カズマ
# （怪しい、あからさまに怪しい。\n　もしかして、アクアが絡んでるんじゃ\n　ないだろうな？）
223 = "（怪しい、あからさまに怪しい。\\n　もしかして、アクアが絡んでるんじゃ\\n　ないだろうな？）"

# カズマ
# アクア。\n……昨日の晩の詳しい事を\n聞かせてもらいたいんだが。
185 = "アクア。\\n……昨日の晩の詳しい事を\\n聞かせてもらいたいんだが。"

# アクア
# だ、だから別になにもないわ！\n絡まれた数体を除霊しただけだから！
179 = "だ、だから別になにもないわ！\\n絡まれた数体を除霊しただけだから！"

# カズマ
# アクアさぁん？\n俺の目を真っ直ぐ見てくれるかなぁ？
186 = "アクアさぁん？\\n俺の目を真っ直ぐ見てくれるかなぁ？"

# アクア
# あっといけない。\nまだ私バイトの途中だったんだっけ。\nじゃあ、またね！
168 = "あっといけない。\\nまだ私バイトの途中だったんだっけ。\\nじゃあ、またね！"

# アクア
# あっ、今日も遅くなるからー！
167 = "あっ、今日も遅くなるからー！"

# カズマ（Ｍ）
# display as カズマ
# （チッ、吐かせられなかったか）
222 = "（チッ、吐かせられなかったか）"

# ウィズ
# アクア様、少し様子が変でしたね。\nどうされたんでしょう？
187 = "アクア様、少し様子が変でしたね。\\nどうされたんでしょう？"

# カズマ
# ああ、あからさまに怪しかったな。
166 = "ああ、あからさまに怪しかったな。"

# カズマ（Ｍ）
# display as カズマ
# （また良からぬことを考えて無きゃいいんだが）
221 = "（また良からぬことを考えて無きゃいいんだが）"

