# root_a02.txt.scn

[info]
0 = ""

[characters]
202 = "カズマ"
198 = "めぐみん"
205 = "キース"
206 = "ダスト"
204 = "カズマ（Ｍ）"

[character_subs]
# 202 = "カズマ"

[script]
# lines: 32

# カズマ
# はあ……。
194 = "はあ……。"

# めぐみん
# なんですか、そのため息は。\nまさか、こんな軽くて可憐な女性を相手に\n重いなんて思っているのですか？
193 = "なんですか、そのため息は。\\nまさか、こんな軽くて可憐な女性を相手に\\n重いなんて思っているのですか？"

# カズマ
# 可憐だろうがなんだろうが、\n人ってのはそれなりに重さがあるんだよ。
211 = "可憐だろうがなんだろうが、\\n人ってのはそれなりに重さがあるんだよ。"

# カズマ
# しかも、遠慮なく眠りやがって。\n爆裂魔法を撃っても気を失うほど\n魔力は消費しないだろうが。
188 = "しかも、遠慮なく眠りやがって。\\n爆裂魔法を撃っても気を失うほど\\n魔力は消費しないだろうが。"

# めぐみん
# しかたないじゃないですか、心地いいんですから。
187 = "しかたないじゃないですか、心地いいんですから。"

# カズマ
# だからって、人に迷惑をかけていい道理はない。
191 = "だからって、人に迷惑をかけていい道理はない。"

# めぐみん
# ま、まさかカズマ！\n私を背負うことを迷惑だと思っていたんですか！
196 = "ま、まさかカズマ！\\n私を背負うことを迷惑だと思っていたんですか！"

# カズマ
# 思わない理由があるなら教えて欲しいもんだ。
218 = "思わない理由があるなら教えて欲しいもんだ。"

# めぐみん
# だってカズマ、女の子が好きじゃないですか。\n夜な夜なパンツを盗むくらいに。
192 = "だってカズマ、女の子が好きじゃないですか。\\n夜な夜なパンツを盗むくらいに。"

# カズマ
# だからあれは不可抗力だっての！\nそれに俺が好きなのは女の子であって――
190 = "だからあれは不可抗力だっての！\\nそれに俺が好きなのは女の子であって――"

# めぐみん
# あって、なんですか？\nその先の言葉次第では、\nカズマの命の保証はしかねますよ。
183 = "あって、なんですか？\\nその先の言葉次第では、\\nカズマの命の保証はしかねますよ。"

# カズマ
# があああ！\nまだ何も言ってないのに首を絞めるな！！
186 = "があああ！\\nまだ何も言ってないのに首を絞めるな！！"

# めぐみん
# 女の子であって、なんなのです！\nさあさあ、早く言ってください！
215 = "女の子であって、なんなのです！\\nさあさあ、早く言ってください！"

# カズマ
# あー、お前は！\n人の首を絞める体力があるなら\n自分の足で歩け！
184 = "あー、お前は！\\n人の首を絞める体力があるなら\\n自分の足で歩け！"

# キース
# ん？　カズマじゃないか。
201 = "ん？　カズマじゃないか。"

# ダスト
# ロリっ子をおんぶなんかしやがって。\n犯罪は正直引くぞ？
207 = "ロリっ子をおんぶなんかしやがって。\\n犯罪は正直引くぞ？"

# めぐみん
# ロリ？
208 = "ロリ？"

# キース
# 本当に通報されてもおかしくないから、気をつけろ。\n最近、変な連中がこの街に来てるって話だし。
219 = "本当に通報されてもおかしくないから、気をつけろ。\\n最近、変な連中がこの街に来てるって話だし。"

# カズマ
# 変な連中？　なんだそれ？
214 = "変な連中？　なんだそれ？"

# ダスト
# うーん、俺も直接見たわけじゃないから、\n詳しくは知らないんだけど、\nとにかく不穏な感じがするんだってよ。
185 = "うーん、俺も直接見たわけじゃないから、\\n詳しくは知らないんだけど、\\nとにかく不穏な感じがするんだってよ。"

# キース
# 街外れの一軒家を借りて、ずっと籠もりっ放し。\n全然、街の人と交流しないらしい。
235 = "街外れの一軒家を借りて、ずっと籠もりっ放し。\\n全然、街の人と交流しないらしい。"

# カズマ
# それ、単なる引きこもりじゃないのか？
189 = "それ、単なる引きこもりじゃないのか？"

# ダスト
# ひとりだったら、そういう解釈もできるんだけどな。\nでも、そこに住んでるのは複数人なんだ。
195 = "ひとりだったら、そういう解釈もできるんだけどな。\\nでも、そこに住んでるのは複数人なんだ。"

# カズマ（Ｍ）
# display as カズマ
# （集団引きこもり……嫌すぎる）
238 = "（集団引きこもり……嫌すぎる）"

# キース
# 何か問題を起こしたわけじゃないんだが、\n得体がしれなくて街の人たちが怯えてるんだ。
210 = "何か問題を起こしたわけじゃないんだが、\\n得体がしれなくて街の人たちが怯えてるんだ。"

# ダスト
# まあ、そういう連中がこの街に来てて、\nみんなが神経過敏になってるから、\n一見幼女さらいのお前も気をつけろってことだな。
197 = "まあ、そういう連中がこの街に来てて、\\nみんなが神経過敏になってるから、\\n一見幼女さらいのお前も気をつけろってことだな。"

# めぐみん
# ようじょ……。
199 = "ようじょ……。"

# ダスト
# んじゃなー！
200 = "んじゃなー！"

# めぐみん
# カズマ、１つ提案なのですが、\n明日の爆裂魔法の練習は今の男２人相手に\nやりませんか？
203 = "カズマ、１つ提案なのですが、\\n明日の爆裂魔法の練習は今の男２人相手に\\nやりませんか？"

# カズマ
# 気持ちはわかるがやめておけ。
220 = "気持ちはわかるがやめておけ。"

# カズマ（Ｍ）
# display as カズマ
# （しかし変な連中、ねえ）
236 = "（しかし変な連中、ねえ）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、俺が気にすることじゃないか）
237 = "（まあ、俺が気にすることじゃないか）"

