# root_f03.txt.scn

[info]
0 = ""

[characters]
138 = "ウィズ"
140 = "カズマ"
141 = "カズマ（Ｍ）"

[character_subs]
# 140 = "カズマ"

[script]
# lines: 35

# ウィズ
# ではとりあえず、\nお店の中をよく見ていてくださいますか？
135 = "ではとりあえず、\\nお店の中をよく見ていてくださいますか？"

# ウィズ
# 色々な物がありますので、\nどこにどんな品があるかを\n覚えて頂きたいのです。
156 = "色々な物がありますので、\\nどこにどんな品があるかを\\n覚えて頂きたいのです。"

# ウィズ
# その間、私は店の奥に行ってますので。
133 = "その間、私は店の奥に行ってますので。"

# カズマ
# オーケー、わかった。
139 = "オーケー、わかった。"

# カズマ（Ｍ）
# display as カズマ
# （確かに、ぱっと見だけでも\n　いろんな物があるな。\n　覚えるだけでも一苦労しそうだ）
177 = "（確かに、ぱっと見だけでも\\n　いろんな物があるな。\\n　覚えるだけでも一苦労しそうだ）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、でも、このいかにもアイテム屋って\n　品揃えは、ちょっとワクワクするな）
173 = "（まあ、でも、このいかにもアイテム屋って\\n　品揃えは、ちょっとワクワクするな）"

# カズマ（Ｍ）
# display as カズマ
# （この『ポーションです！』と\n　言わんばかりの形の瓶とか。\n　どれどれ、どんな効能があるんだ？）
164 = "（この『ポーションです！』と\\n　言わんばかりの形の瓶とか。\\n　どれどれ、どんな効能があるんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （『獣に群がられるポーション』）
159 = "（『獣に群がられるポーション』）"

# カズマ（Ｍ）
# display as カズマ
# （なんじゃそりゃ！\n　獣に群がられたら\n　逆にピンチになるじゃねーか！）
168 = "（なんじゃそりゃ！\\n　獣に群がられたら\\n　逆にピンチになるじゃねーか！）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、でも使いようはあるか。\n　獣を一箇所に集めたいような時には\n　有効かも……）
160 = "（ああ、でも使いようはあるか。\\n　獣を一箇所に集めたいような時には\\n　有効かも……）"

# カズマ（Ｍ）
# display as カズマ
# （ねーよ！　どういう状況だよ！！）
169 = "（ねーよ！　どういう状況だよ！！）"

# カズマ（Ｍ）
# display as カズマ
# （えーと、次……\n　『どんな毒でも瞬時に解毒できる解毒剤』\n　へー！　すげーじゃん！）
162 = "（えーと、次……\\n　『どんな毒でも瞬時に解毒できる解毒剤』\\n　へー！　すげーじゃん！）"

# カズマ（Ｍ）
# display as カズマ
# （『ただし解毒のために数時間、麻痺する』……）
157 = "（『ただし解毒のために数時間、麻痺する』……）"

# カズマ（Ｍ）
# display as カズマ
# （意味ねぇ！\n　毒より麻痺の方が危険だろ！）
176 = "（意味ねぇ！\\n　毒より麻痺の方が危険だろ！）"

# カズマ（Ｍ）
# display as カズマ
# （ま、まあ……\n　本当に最後の最後の手段としてはありなのか？）
171 = "（ま、まあ……\\n　本当に最後の最後の手段としてはありなのか？）"

# カズマ（Ｍ）
# display as カズマ
# （役に立ちそうで立たなさそうで、\n　でも決定的に使えないわけじゃない。\n　なんだ、この微妙さ加減は）
175 = "（役に立ちそうで立たなさそうで、\\n　でも決定的に使えないわけじゃない。\\n　なんだ、この微妙さ加減は）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、いいや。\n　次は……『幸運を呼び寄せる亀の甲羅』）
172 = "（まあ、いいや。\\n　次は……『幸運を呼び寄せる亀の甲羅』）"

# カズマ（Ｍ）
# display as カズマ
# （こんなの骨董品屋向けだろ！！\n　次！！）
166 = "（こんなの骨董品屋向けだろ！！\\n　次！！）"

# カズマ（Ｍ）
# display as カズマ
# （『何かが出るかもしれない古代の箱』）
158 = "（『何かが出るかもしれない古代の箱』）"

# カズマ（Ｍ）
# display as カズマ
# （ギリギリ、マジックアイテムというか\n　宝物っぽい感じはあるが……）
174 = "（ギリギリ、マジックアイテムというか\\n　宝物っぽい感じはあるが……）"

# カズマ（Ｍ）
# display as カズマ
# （こういうのって\n　開けたら呪われるのがお約束だよなぁ）
163 = "（こういうのって\\n　開けたら呪われるのがお約束だよなぁ）"

# カズマ（Ｍ）
# display as カズマ
# （はあ……。\n　どうにも胡散臭いアイテムばかりだな）
170 = "（はあ……。\\n　どうにも胡散臭いアイテムばかりだな）"

# カズマ（Ｍ）
# display as カズマ
# （しかも、よく見ればどれも埃を被ってる……\n　というか積もってるレベルだ。\n　このありさまじゃ、売れるものも売れないだろ）
167 = "（しかも、よく見ればどれも埃を被ってる……\\n　というか積もってるレベルだ。\\n　このありさまじゃ、売れるものも売れないだろ）"

# カズマ（Ｍ）
# display as カズマ
# （これは、店を手伝う以前に\n　商品の整理と掃除から\n　してあげた方がいいかもしれないぞ？）
165 = "（これは、店を手伝う以前に\\n　商品の整理と掃除から\\n　してあげた方がいいかもしれないぞ？）"

# ウィズ
# あ、カズマさん。
127 = "あ、カズマさん。"

# カズマ
# ああ、ウィズ。\n提案があるんだけど――
129 = "ああ、ウィズ。\\n提案があるんだけど――"

# ウィズ
# すみません、ちょっとこれから\n買い出しに行こうと思うのですが、\n手伝って頂けませんか？
132 = "すみません、ちょっとこれから\\n買い出しに行こうと思うのですが、\\n手伝って頂けませんか？"

# カズマ
# ん？　買い出し？\nああ、構わないけど。
137 = "ん？　買い出し？\\nああ、構わないけど。"

# ウィズ
# 助かります。\nところで、カズマさん\n何か言いかけていませんでしたか？
143 = "助かります。\\nところで、カズマさん\\n何か言いかけていませんでしたか？"

# カズマ
# ああ、いや。\n大したことじゃ無いから後でいいよ。\nそれで、買い出しってことは、店閉めるのか？
128 = "ああ、いや。\\n大したことじゃ無いから後でいいよ。\\nそれで、買い出しってことは、店閉めるのか？"

# ウィズ
# いえ、このままで大丈夫ですよ。
130 = "いえ、このままで大丈夫ですよ。"

# カズマ
# え？　開けっ放しでいいのか？
131 = "え？　開けっ放しでいいのか？"

# ウィズ
# はい、お客さまは来ないと思いますし。
136 = "はい、お客さまは来ないと思いますし。"

# カズマ（Ｍ）
# display as カズマ
# （いや、だからそこは\n　にっこり言うところじゃなくてだな……。\n　まあ、いいや……）
161 = "（いや、だからそこは\\n　にっこり言うところじゃなくてだな……。\\n　まあ、いいや……）"

# ウィズ
# それじゃ、行きましょうか。
134 = "それじゃ、行きましょうか。"

