# root_f08.txt.scn

[info]
0 = ""

[characters]
259 = "カズマ"
256 = "めぐみん"
261 = "ダクネス"
257 = "アクア"
260 = "カズマ（Ｍ）"

[character_subs]
# 259 = "カズマ"

[script]
# lines: 51

# カズマ
# ただいまー。
246 = "ただいまー。"

# めぐみん
# お帰りなさい、カズマ。
235 = "お帰りなさい、カズマ。"

# ダクネス
# ああ、帰ったか。
225 = "ああ、帰ったか。"

# カズマ
# お！　ちょうどいいところに。\nめぐみん、ダクネス、相談があるんだけど、\n今いいか？
236 = "お！　ちょうどいいところに。\\nめぐみん、ダクネス、相談があるんだけど、\\n今いいか？"

# めぐみん
# おお！\nついに爆裂道に入門する気になったのですね！？
232 = "おお！\\nついに爆裂道に入門する気になったのですね！？"

# カズマ
# ならねーよ！
250 = "ならねーよ！"

# めぐみん
# えー？\n他にどんな相談があるというのですか？
229 = "えー？\\n他にどんな相談があるというのですか？"

# カズマ
# なあ、２人はマジックアイテムについて\n詳しかったりするか？
249 = "なあ、２人はマジックアイテムについて\\n詳しかったりするか？"

# ダクネス
# マジックアイテムか？\nありふれた物ならわかるが、\n正直、あまり詳しくはないな。
262 = "マジックアイテムか？\\nありふれた物ならわかるが、\\n正直、あまり詳しくはないな。"

# めぐみん
# 私もですね。
300 = "私もですね。"

# カズマ
# そうか……。
240 = "そうか……。"

# ダクネス
# しかし、突然どうした？\n何かあったのか？
239 = "しかし、突然どうした？\\n何かあったのか？"

# カズマ
# あー、まあ、ちょっとな。
226 = "あー、まあ、ちょっとな。"

# アクア
# ふんふんふふ～ん♪\nたっだいまー♪
254 = "ふんふんふふ～ん♪\\nたっだいまー♪"

# ダクネス
# ああ、お帰り。\nどうした、随分ごきげんじゃないか。
224 = "ああ、お帰り。\\nどうした、随分ごきげんじゃないか。"

# アクア
# 見て見て！\n余ったコロッケをこんなにもらっちゃったの！\n儲かっちゃったわね。
301 = "見て見て！\\n余ったコロッケをこんなにもらっちゃったの！\\n儲かっちゃったわね。"

# カズマ
# はあ……。
252 = "はあ……。"

# アクア
# ちょっと、人の顔を見ていきなり溜息って\n失礼過ぎると思うんですけど。
247 = "ちょっと、人の顔を見ていきなり溜息って\\n失礼過ぎると思うんですけど。"

# カズマ
# お前は悩みがまったく無さそうでいいなって\n思ってさ。
234 = "お前は悩みがまったく無さそうでいいなって\\n思ってさ。"

# アクア
# 何よ、私にだって悩みくらいあるわ。
266 = "何よ、私にだって悩みくらいあるわ。"

# カズマ
# 借金以外のだぞ。
268 = "借金以外のだぞ。"

# アクア
# あ、あるわよ！
223 = "あ、あるわよ！"

# カズマ
# 今の間はなんだ、今の間は！
265 = "今の間はなんだ、今の間は！"

# アクア
# うーん、微妙なところなのよ。\n悩みといえば悩みだし、\nそうじゃないといえばそうじゃないみたいな。
228 = "うーん、微妙なところなのよ。\\n悩みといえば悩みだし、\\nそうじゃないといえばそうじゃないみたいな。"

# カズマ（Ｍ）
# display as カズマ
# （なんだそれ……）
306 = "（なんだそれ……）"

# アクア
# 実はね、帰りの道で悪霊に襲われたの。
272 = "実はね、帰りの道で悪霊に襲われたの。"

# アクア
# それも一回だけならともかく、\nお店からここに帰る間に何度もよ。
243 = "それも一回だけならともかく、\\nお店からここに帰る間に何度もよ。"

# めぐみん
# それは……ちょっと嫌ですね。
242 = "それは……ちょっと嫌ですね。"

# ダクネス
# お、襲われて、どうしたんだ？\n取り憑かれて、身体の自由を奪われ\n意識も操られたりしたのか！？
231 = "お、襲われて、どうしたんだ？\\n取り憑かれて、身体の自由を奪われ\\n意識も操られたりしたのか！？"

# アクア
# そんなこと私がさせるわけ無いわ。\nちゃちゃっと除霊してやったわよ。
245 = "そんなこと私がさせるわけ無いわ。\\nちゃちゃっと除霊してやったわよ。"

# めぐみん
# さすがアクア！\n頼もしいですね！
238 = "さすがアクア！\\n頼もしいですね！"

# アクア
# ふふん、でしょー？
253 = "ふふん、でしょー？"

# カズマ
# ま、そんな話はどうでもいいや。
255 = "ま、そんな話はどうでもいいや。"

# アクア
# 雑にすませたわね！
302 = "雑にすませたわね！"

# カズマ
# それよりアクア。\nお前、マジックアイテムに詳しくないか？
244 = "それよりアクア。\\nお前、マジックアイテムに詳しくないか？"

# アクア
# え？　マジックアイテム？\nよく知らないけど。
230 = "え？　マジックアイテム？\\nよく知らないけど。"

# カズマ
# 一応、女神だろ？\nそういう知識無いのかよ。
263 = "一応、女神だろ？\\nそういう知識無いのかよ。"

# アクア
# 女神だからこそよ。\n下々のことなんてよく知らないわ。
271 = "女神だからこそよ。\\n下々のことなんてよく知らないわ。"

# カズマ（Ｍ）
# display as カズマ
# （あー……。\n　まあ、そうなるのか？）
304 = "（あー……。\\n　まあ、そうなるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、これじゃどうしようも無いな。\n　多少の知識を身につければウィズの\n　役に立つかと思ったけど、それ以前の話だ）
305 = "（うーん、これじゃどうしようも無いな。\\n　多少の知識を身につければウィズの\\n　役に立つかと思ったけど、それ以前の話だ）"

# カズマ（Ｍ）
# display as カズマ
# （やっぱ、店の手伝いくらいしかできそうにない）
307 = "（やっぱ、店の手伝いくらいしかできそうにない）"

# アクア
# ねえ、カズマの話は終わり？\nだったら私、ちょっと出掛けてくるわ。
251 = "ねえ、カズマの話は終わり？\\nだったら私、ちょっと出掛けてくるわ。"

# ダクネス
# これからか？
237 = "これからか？"

# アクア
# いい加減、むかついたから\nこれから除霊に行ってくる。
227 = "いい加減、むかついたから\\nこれから除霊に行ってくる。"

# アクア
# 寄ってくる悪霊全部、\n浄化しまくってやるんだから！
273 = "寄ってくる悪霊全部、\\n浄化しまくってやるんだから！"

# カズマ（Ｍ）
# display as カズマ
# （あいつがタダで浄化をするなんて。\n　よっぽどしつこく絡まれたんだな……）
303 = "（あいつがタダで浄化をするなんて。\\n　よっぽどしつこく絡まれたんだな……）"

# めぐみん
# アクアですから、\n悪霊相手に後れを取ることはないでしょうし\n放っておきましょう。
258 = "アクアですから、\\n悪霊相手に後れを取ることはないでしょうし\\n放っておきましょう。"

# ダクネス
# そうだな。\nでは、私たちは部屋に戻るとするか。
241 = "そうだな。\\nでは、私たちは部屋に戻るとするか。"

# カズマ
# 俺もコロッケ食ったら、風呂入って寝るわ。
267 = "俺もコロッケ食ったら、風呂入って寝るわ。"

# ダクネス
# では、おやすみ。
248 = "では、おやすみ。"

# めぐみん
# おやすみなさい。
233 = "おやすみなさい。"

