# root_e10.txt.scn

[info]
0 = ""

[characters]
258 = "カズマ"
252 = "めぐみん"
253 = "ゆんゆん"
256 = "アクア"
260 = "ダクネス"
259 = "カズマ（Ｍ）"

[character_subs]
# 258 = "カズマ"

[script]
# lines: 43

# カズマ
# 帰ったぞー。
268 = "帰ったぞー。"

# めぐみん
# ただいま帰りました。
243 = "ただいま帰りました。"

# ゆんゆん
# た、ただいま、です。
242 = "た、ただいま、です。"

# アクア
# あら、帰ったのね。
227 = "あら、帰ったのね。"

# ダクネス
# ああ、３人ともお帰り。
225 = "ああ、３人ともお帰り。"

# カズマ
# はあ、ジャイアントトードに襲われて\n散々だったよ。
249 = "はあ、ジャイアントトードに襲われて\\n散々だったよ。"

# ダクネス
# な、またヌルヌルプレイを楽しんできたのか。
247 = "な、またヌルヌルプレイを楽しんできたのか。"

# カズマ
# そうなる前にゆんゆんが倒してくれたんだ。\nてか、楽しむってなんだよ、楽しむって。
240 = "そうなる前にゆんゆんが倒してくれたんだ。\\nてか、楽しむってなんだよ、楽しむって。"

# ダクネス
# それで怪我は？
241 = "それで怪我は？"

# カズマ
# ああ、大丈夫だ。
224 = "ああ、大丈夫だ。"

# ダクネス
# そうか、よかった。\nふたりを助けてくれてありがとう。\n礼を言う。
239 = "そうか、よかった。\\nふたりを助けてくれてありがとう。\\n礼を言う。"

# ゆんゆん
# いいえ、当然のことをしただけですから。
229 = "いいえ、当然のことをしただけですから。"

# めぐみん
# ……それはそれとして、\nこの散らかりようはなんです？\n汚れた食器やグラスがそこら中に……。
219 = "……それはそれとして、\\nこの散らかりようはなんです？\\n汚れた食器やグラスがそこら中に……。"

# ダクネス
# これは、アクアが――
238 = "これは、アクアが――"

# カズマ
# いや、皆まで言わなくてもわかる。\nアクアが力の限りグータラして\n散らかしまくってるんだな？
231 = "いや、皆まで言わなくてもわかる。\\nアクアが力の限りグータラして\\n散らかしまくってるんだな？"

# ダクネス
# ああ、そういうことだ。
222 = "ああ、そういうことだ。"

# ゆんゆん
# でも、たった数時間の間に\nここまで汚せるなんて。
246 = "でも、たった数時間の間に\\nここまで汚せるなんて。"

# アクア
# 何言ってんの。\n私の本気はまだまだこんなもんじゃないわよ？
262 = "何言ってんの。\\n私の本気はまだまだこんなもんじゃないわよ？"

# めぐみん
# 胸を張って言うことではありませんよ。
294 = "胸を張って言うことではありませんよ。"

# ゆんゆん
# あの、どうしてここまで散らかせるんですか？\n私だったら気になって、途中で片付けを\n始めちゃいますけど。
226 = "あの、どうしてここまで散らかせるんですか？\\n私だったら気になって、途中で片付けを\\n始めちゃいますけど。"

# アクア
# でしょ？\nそう言ってくれるって信じてたわ。\nだからこそ気兼ねなく散らかせるのよね。
245 = "でしょ？\\nそう言ってくれるって信じてたわ。\\nだからこそ気兼ねなく散らかせるのよね。"

# ゆんゆん
# えーと……どういう意味ですか？
233 = "えーと……どういう意味ですか？"

# めぐみん
# つまり、アクアは散らかすだけ散らかして\nゆんゆんに片付けさせる気なのですよ。
244 = "つまり、アクアは散らかすだけ散らかして\\nゆんゆんに片付けさせる気なのですよ。"

# カズマ
# アクア、お前なぁ。\nゆんゆんはメイドじゃないんだぞ？
257 = "アクア、お前なぁ。\\nゆんゆんはメイドじゃないんだぞ？"

# アクア
# わかってないわね。\n適材適所って言葉があるでしょ？
255 = "わかってないわね。\\n適材適所って言葉があるでしょ？"

# アクア
# 私は好きなように振る舞うのが役目。\nゆんゆんは私のお世話をするのが役目。\nこれが世界の仕組みなのよ。
293 = "私は好きなように振る舞うのが役目。\\nゆんゆんは私のお世話をするのが役目。\\nこれが世界の仕組みなのよ。"

# カズマ
# お前は何様だよ！？
237 = "お前は何様だよ！？"

# アクア
# 女神様。
265 = "女神様。"

# カズマ（Ｍ）
# display as カズマ
# （……同じ女神でもエリス様とは大違いだな。\n　むこうは文句なしの女神様なのに、\n　どうしてこうも違うのか！）
295 = "（……同じ女神でもエリス様とは大違いだな。\\n　むこうは文句なしの女神様なのに、\\n　どうしてこうも違うのか！）"

# めぐみん
# ああ、ゆんゆん。\nアクアの発言は気にしないでください。\n女神というのはただの思い込みですので。
223 = "ああ、ゆんゆん。\\nアクアの発言は気にしないでください。\\n女神というのはただの思い込みですので。"

# ゆんゆん
# あ、うん……。
220 = "あ、うん……。"

# カズマ
# ほれ、アクア。\nゆんゆんも呆れてるぞ、もっとしゃんとしろ。
251 = "ほれ、アクア。\\nゆんゆんも呆れてるぞ、もっとしゃんとしろ。"

# ゆんゆん
# いえ、呆れてなんて！\nそれよりも、お片付けしますね。
230 = "いえ、呆れてなんて！\\nそれよりも、お片付けしますね。"

# カズマ
# はあ？\nいいって、そんなのアクアにやらせれば。
250 = "はあ？\\nいいって、そんなのアクアにやらせれば。"

# ゆんゆん
# いいえ、やりたいんです。\nだって、私が片付けると思ってくれた――\n私を頼りにしてくれたってことですよね？
228 = "いいえ、やりたいんです。\\nだって、私が片付けると思ってくれた――\\n私を頼りにしてくれたってことですよね？"

# アクア
# え？\nまあ、そうかしらね。
234 = "え？\\nまあ、そうかしらね。"

# ゆんゆん
# なら期待には応えなきゃ！\n他にも何かあれば遠慮なく言ってくださいね！\nそれじゃ、掃除道具を取ってきます！
248 = "なら期待には応えなきゃ！\\n他にも何かあれば遠慮なく言ってくださいね！\\nそれじゃ、掃除道具を取ってきます！"

# ダクネス
# うーむ……。\n改めて言うのもなんだが、\nゆんゆんは少し変わっているな。
232 = "うーむ……。\\n改めて言うのもなんだが、\\nゆんゆんは少し変わっているな。"

# カズマ
# ああ……。\nなんだろうな、非常に残念というか……。
221 = "ああ……。\\nなんだろうな、非常に残念というか……。"

# めぐみん
# ようやく気付きましたか。\nええそうです、残念な子なんですよ。\nとーってもね。
254 = "ようやく気付きましたか。\\nええそうです、残念な子なんですよ。\\nとーってもね。"

# カズマ
# お、おう……。
235 = "お、おう……。"

# アクア
# 掃除してくれるなら残念でもなんでもいいわ。
269 = "掃除してくれるなら残念でもなんでもいいわ。"

# カズマ
# お前はちょっと黙ってろ！
236 = "お前はちょっと黙ってろ！"

