# root_c09.txt.scn

[info]
0 = ""

[characters]
273 = "カズマ（Ｍ）"
268 = "アクア"
261 = "めぐみん"
270 = "カズマ"
276 = "ダクネス"

[character_subs]
# 270 = "カズマ"

[script]
# lines: 82

# カズマ（Ｍ）
# display as カズマ
# （部屋に引きこもった俺は、その後も\n　悶々とした時間を過ごすはめになった）
364 = "（部屋に引きこもった俺は、その後も\\n　悶々とした時間を過ごすはめになった）"

# カズマ（Ｍ）
# display as カズマ
# （だって仕方ないだろ！？\n　俺は女の子と付き合ったことなんてない\n　童貞なんだぞ！？）
350 = "（だって仕方ないだろ！？\\n　俺は女の子と付き合ったことなんてない\\n　童貞なんだぞ！？）"

# カズマ（Ｍ）
# display as カズマ
# （あんな話を聞かされたら、\n　落ち着いてなんていられるか～！！）
338 = "（あんな話を聞かされたら、\\n　落ち着いてなんていられるか～！！）"

# アクア
# カズマー、夕飯できたんですけどー。
272 = "カズマー、夕飯できたんですけどー。"

# カズマ（Ｍ）
# display as カズマ
# （なっ！？　こんな状況で\n　ダクネスと顔を合わせるなんて\n　どんなお仕置きだよ！）
354 = "（なっ！？　こんな状況で\\n　ダクネスと顔を合わせるなんて\\n　どんなお仕置きだよ！）"

# カズマ（Ｍ）
# display as カズマ
# （うぐ、でも朝から何も食ってないし……）
341 = "（うぐ、でも朝から何も食ってないし……）"

# アクア
# 何やってるのよー。\n朝できなかったんだから、\n夜はみんなでいただきますをするわよー。
283 = "何やってるのよー。\\n朝できなかったんだから、\\n夜はみんなでいただきますをするわよー。"

# カズマ（Ｍ）
# display as カズマ
# （ぐぬぬ、背に腹はかえられないか……）
342 = "（ぐぬぬ、背に腹はかえられないか……）"

# アクア
# あっ、ようやく来たわね。
236 = "あっ、ようやく来たわね。"

# めぐみん
# 今日の食事は、\nダクネスが作ってくれたんですよ。
281 = "今日の食事は、\\nダクネスが作ってくれたんですよ。"

# カズマ
# へ、へえ、そうなのか。
257 = "へ、へえ、そうなのか。"

# ダクネス
# 別に、自慢できるような出来ではないがな。\n期待はしないでくれ。
284 = "別に、自慢できるような出来ではないがな。\\n期待はしないでくれ。"

# カズマ（Ｍ）
# display as カズマ
# （ダクネス、普通だな）
359 = "（ダクネス、普通だな）"

# カズマ（Ｍ）
# display as カズマ
# （俺が部屋に戻った後も\n　特に何もしてこなかったし、\n　俺の自意識過剰なのか？）
361 = "（俺が部屋に戻った後も\\n　特に何もしてこなかったし、\\n　俺の自意識過剰なのか？）"

# ダクネス
# 今日は、カズマが\n好きそうな物を作ってみたんだが。
282 = "今日は、カズマが\\n好きそうな物を作ってみたんだが。"

# カズマ
# え？　そうなの？
244 = "え？　そうなの？"

# ダクネス
# たくさんある、遠慮せず食べてくれ。
250 = "たくさんある、遠慮せず食べてくれ。"

# カズマ
# じゃあ、いただきます！
247 = "じゃあ、いただきます！"

# アクア
# ジー……。
275 = "ジー……。"

# めぐみん
# ジー……。
# 275 = "ジー……。"

# カズマ
# ……なんだよ。
229 = "……なんだよ。"

# アクア
# べ、別になんでもないわよ。\n私もいただきます！
258 = "べ、別になんでもないわよ。\\n私もいただきます！"

# めぐみん
# 私もなんでもありません。\nでは、いただきます！
335 = "私もなんでもありません。\\nでは、いただきます！"

# カズマ（Ｍ）
# display as カズマ
# （どうも、おかしいな。\n　こいつら、顔に出やすいからバレバレだ。\n　やっぱり何か企んでやがるのか？）
351 = "（どうも、おかしいな。\\n　こいつら、顔に出やすいからバレバレだ。\\n　やっぱり何か企んでやがるのか？）"

# ダクネス
# カズマ？　どうかしたのか？\n口に合わなかっただろうか？
274 = "カズマ？　どうかしたのか？\\n口に合わなかっただろうか？"

# カズマ
# い、いや、そんなことはない。\nもぐもぐ……。
239 = "い、いや、そんなことはない。\\nもぐもぐ……。"

# ダクネス
# さあカズマ、これも食べてくれ。\nお前の好物だったろう？
246 = "さあカズマ、これも食べてくれ。\\nお前の好物だったろう？"

# カズマ
# ああ、ありがとう。\nもぐもぐ……お、これ、美味いな！
232 = "ああ、ありがとう。\\nもぐもぐ……お、これ、美味いな！"

# ダクネス
# ふふ、よかった。\n頑張って作った甲斐があるというものだ。
254 = "ふふ、よかった。\\n頑張って作った甲斐があるというものだ。"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスのヤツ、妙に家庭的な雰囲気だな。\n　クルセイダーとして\n　戦場に立つ時とは大違いだ）
360 = "（ダクネスのヤツ、妙に家庭的な雰囲気だな。\\n　クルセイダーとして\\n　戦場に立つ時とは大違いだ）"

# ダクネス
# カズマ、おかわりはどうだ？\n皿を貸してくれ。
271 = "カズマ、おかわりはどうだ？\\n皿を貸してくれ。"

# カズマ
# ああ、頼むよ。
234 = "ああ、頼むよ。"

# ダクネス
# ふふっ！
255 = "ふふっ！"

# カズマ
# ん？　どうかしたか？
267 = "ん？　どうかしたか？"

# ダクネス
# 喜んで食べてくれるのは嬉しいが、\n頬に食べかすがついてるぞ？
287 = "喜んで食べてくれるのは嬉しいが、\\n頬に食べかすがついてるぞ？"

# カズマ
# えっ？　マジか？
243 = "えっ？　マジか？"

# ダクネス
# ほら、いまナプキンを――
260 = "ほら、いまナプキンを――"

# アクア
# んっん！
265 = "んっん！"

# ダクネス
# えっ？
242 = "えっ？"

# アクア
# ダクネス、違うでしょ？
277 = "ダクネス、違うでしょ？"

# ダクネス
# あっ！\nそうか、そうだったな。
237 = "あっ！\\nそうか、そうだったな。"

# ダクネス
# ええと……\nで、では、動くなよ、カズマ。
241 = "ええと……\\nで、では、動くなよ、カズマ。"

# カズマ
# えっ？
# 242 = "えっ？"

# ダクネス
# んっ……あむっ。
264 = "んっ……あむっ。"

# ダクネス
# ほ、ほら、取れたぞ？
259 = "ほ、ほら、取れたぞ？"

# カズマ
# あ、ああ……ありがとう。
230 = "あ、ああ……ありがとう。"

# カズマ（Ｍ）
# display as カズマ
# （なっ、なんだ、今のは～！）
353 = "（なっ、なんだ、今のは～！）"

# カズマ（Ｍ）
# display as カズマ
# （これって、いわゆる、\n　あれ、カズマくんのほっぺにおべんと付いてる、\n　パクッ！　ってやつだよな！？）
344 = "（これって、いわゆる、\\n　あれ、カズマくんのほっぺにおべんと付いてる、\\n　パクッ！　ってやつだよな！？）"

# カズマ（Ｍ）
# display as カズマ
# （そっ、それを、今、ダクネスが？）
349 = "（そっ、それを、今、ダクネスが？）"

# ダクネス
# …………。
228 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （こ、こ、こういうのって、つき合って\n　ラブラブなカップルがするものだろ？\n　俺達はつき合ってないぞ！？）
343 = "（こ、こ、こういうのって、つき合って\\n　ラブラブなカップルがするものだろ？\\n　俺達はつき合ってないぞ！？）"

# カズマ（Ｍ）
# display as カズマ
# （もしかして、ダクネスは本当に俺のことを？）
358 = "（もしかして、ダクネスは本当に俺のことを？）"

# ダクネス
# そ、そんな目で……じろじろ見ないでくれ。
249 = "そ、そんな目で……じろじろ見ないでくれ。"

# カズマ（Ｍ）
# display as カズマ
# （な、なんで、まんざらでもなさそうな感じで\n　頬染めているんですかダクネスさーん！！）
352 = "（な、なんで、まんざらでもなさそうな感じで\\n　頬染めているんですかダクネスさーん！！）"

# ダクネス
# ああ、反対側の頬にはソースが跳ねているな、\n拭いてやるから動くなよ？
233 = "ああ、反対側の頬にはソースが跳ねているな、\\n拭いてやるから動くなよ？"

# カズマ
# は、はひっ！
252 = "は、はひっ！"

# ダクネス
# よし、これで綺麗になったな。
263 = "よし、これで綺麗になったな。"

# カズマ
# あ、ありがとうございます。
231 = "あ、ありがとうございます。"

# ダクネス
# さあ、食事を続けようか。
245 = "さあ、食事を続けようか。"

# カズマ（Ｍ）
# display as カズマ
# （まだ……\n　ダクネスが頬に触れた感触が残ってる）
357 = "（まだ……\\n　ダクネスが頬に触れた感触が残ってる）"

# カズマ（Ｍ）
# display as カズマ
# （そうなのか？\n　やっぱりそうなのか？\n　ダクネスは……俺に惚れてるのか！？）
348 = "（そうなのか？\\n　やっぱりそうなのか？\\n　ダクネスは……俺に惚れてるのか！？）"

# カズマ（Ｍ）
# display as カズマ
# （これはもう、そう思ってもおかしくないよな！？\n　昼間だって、俺に寄り添うように歩いてたり、\n　力になってくれるって言ってくれたり――）
345 = "（これはもう、そう思ってもおかしくないよな！？\\n　昼間だって、俺に寄り添うように歩いてたり、\\n　力になってくれるって言ってくれたり――）"

# カズマ（Ｍ）
# display as カズマ
# （俺の好きな物を作ってくれたり、\n　ほっぺのおべんと食べてくれたり！）
362 = "（俺の好きな物を作ってくれたり、\\n　ほっぺのおべんと食べてくれたり！）"

# カズマ（Ｍ）
# display as カズマ
# （いくらなんでも、ここまで\n　偶然が重なりすぎることはないだろ！？）
340 = "（いくらなんでも、ここまで\\n　偶然が重なりすぎることはないだろ！？）"

# ダクネス
# どうした？\n食べないのか？
251 = "どうした？\\n食べないのか？"

# カズマ
# 食う！　食うさ！\nなんてたって、ダクネスの愛情がたっぷりつまった\n飯だからな！
337 = "食う！　食うさ！\\nなんてたって、ダクネスの愛情がたっぷりつまった\\n飯だからな！"

# ダクネス
# う、うん、ではどんどん食べてくれ。
240 = "う、うん、ではどんどん食べてくれ。"

# カズマ
# あむあむあむあむあむあむあむあむっ！！
238 = "あむあむあむあむあむあむあむあむっ！！"

# アクア
# ああっ！\nちょっと、そのおかずは私が狙ってたのに！
235 = "ああっ！\\nちょっと、そのおかずは私が狙ってたのに！"

# めぐみん
# 私も食べたかったのに！\nずるいです、カズマ！
336 = "私も食べたかったのに！\\nずるいです、カズマ！"

# ダクネス
# ふふっ！\nカズマは本当に子供みたいだな。
256 = "ふふっ！\\nカズマは本当に子供みたいだな。"

# カズマ
# そ、そうか？
248 = "そ、そうか？"

# カズマ（Ｍ）
# display as カズマ
# （なんて嬉しそうな顔をするんだ！\n　もしかして、もしかすると、\n　ダクネスは本当に俺に！！）
355 = "（なんて嬉しそうな顔をするんだ！\\n　もしかして、もしかすると、\\n　ダクネスは本当に俺に！！）"

# ダクネス
# やっぱり、みんなで食事するのは楽しいな。
262 = "やっぱり、みんなで食事するのは楽しいな。"

# カズマ
# えっ？
# 242 = "えっ？"

# カズマ（Ｍ）
# display as カズマ
# （い、今……みんなでと申しましたか？）
339 = "（い、今……みんなでと申しましたか？）"

# カズマ
# はぁ……。
253 = "はぁ……。"

# ダクネス
# ん？　ああ、おかわりか？\nちょっと待っていろ。
266 = "ん？　ああ、おかわりか？\\nちょっと待っていろ。"

# カズマ（Ｍ）
# display as カズマ
# （落ち着け、俺。\n　ここで盛大に自爆したら目も当てられん。\n　冷静になるんだ）
363 = "（落ち着け、俺。\\n　ここで盛大に自爆したら目も当てられん。\\n　冷静になるんだ）"

# カズマ（Ｍ）
# display as カズマ
# （さっきのダクネスの行動は、\n　好意じゃなくて、もしかしたら\n　なんらかのプレイだったのかもしれない）
346 = "（さっきのダクネスの行動は、\\n　好意じゃなくて、もしかしたら\\n　なんらかのプレイだったのかもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （そうだ！　きっと罰ゲームで\n　俺のほっぺに付いたおべんとを無理矢理\n　食べさせられたに違いない！）
347 = "（そうだ！　きっと罰ゲームで\\n　俺のほっぺに付いたおべんとを無理矢理\\n　食べさせられたに違いない！）"

# カズマ（Ｍ）
# display as カズマ
# （ふぅ、危ない危ない。\n　勘違いして大恥をかくところだったぜ……）
356 = "（ふぅ、危ない危ない。\\n　勘違いして大恥をかくところだったぜ……）"

