# root_f09.txt.scn

[info]
0 = ""

[characters]
240 = "カズマ"
237 = "ウィズ"
241 = "カズマ（Ｍ）"

[character_subs]
# 240 = "カズマ"

[script]
# lines: 60

# カズマ
# ウィズ、おはよう。
238 = "ウィズ、おはよう。"

# ウィズ
# あら、カズマさん。\nおはようございます。\n今日は早いですね、どこかにお出掛けですか？
202 = "あら、カズマさん。\\nおはようございます。\\n今日は早いですね、どこかにお出掛けですか？"

# カズマ
# ああ、ここに。
199 = "ああ、ここに。"

# ウィズ
# え？
219 = "え？"

# カズマ
# いやだから、また手伝いに来たんだけど。
209 = "いやだから、また手伝いに来たんだけど。"

# ウィズ
# ええっ？\nお詫びでしたら昨日だけで十分だと\n言ったじゃないですか。
217 = "ええっ？\\nお詫びでしたら昨日だけで十分だと\\n言ったじゃないですか。"

# カズマ
# いや、それじゃやっぱり俺の気が済まないんだ。\nそれに、屋敷にいても暇なだけだしさ。
207 = "いや、それじゃやっぱり俺の気が済まないんだ。\\nそれに、屋敷にいても暇なだけだしさ。"

# ウィズ
# そ、そう言われましても。
222 = "そ、そう言われましても。"

# カズマ
# いいからいいから。\nそれじゃ、また昨日みたいな感じでやればいいか？
204 = "いいからいいから。\\nそれじゃ、また昨日みたいな感じでやればいいか？"

# ウィズ
# え、あ、ええと……はい、お願いします。
212 = "え、あ、ええと……はい、お願いします。"

# カズマ（Ｍ）
# display as カズマ
# （昨日１日一緒に働いてわかったけど、\n　ウィズに対しては、とにかく理屈より\n　強引に押したもん勝ちなんだよな）
283 = "（昨日１日一緒に働いてわかったけど、\\n　ウィズに対しては、とにかく理屈より\\n　強引に押したもん勝ちなんだよな）"

# カズマ（Ｍ）
# display as カズマ
# （こうやってウィズの人の良さを利用するのは、\n　あのクソ商人たちと同じようで\n　気が引けるけど――）
273 = "（こうやってウィズの人の良さを利用するのは、\\n　あのクソ商人たちと同じようで\\n　気が引けるけど――）"

# カズマ（Ｍ）
# display as カズマ
# （これもウィズのためなんだ、\n　許してくれ！）
274 = "（これもウィズのためなんだ、\\n　許してくれ！）"

# カズマ
# うっし！\n掃除は終わったし、看板も外に出したぞ。
210 = "うっし！\\n掃除は終わったし、看板も外に出したぞ。"

# ウィズ
# はい、ありがとうございます。\nでは、こちらの商品を\n棚に並べてもらえますか？
229 = "はい、ありがとうございます。\\nでは、こちらの商品を\\n棚に並べてもらえますか？"

# カズマ
# これ、昨日買ったやつ？
220 = "これ、昨日買ったやつ？"

# ウィズ
# ええ。\nせっかくですし、すぐ出そうかなと。
214 = "ええ。\\nせっかくですし、すぐ出そうかなと。"

# カズマ
# まあ、倉庫に眠らせといても意味ないしな。\n値段は決めてあるのか？
230 = "まあ、倉庫に眠らせといても意味ないしな。\\n値段は決めてあるのか？"

# ウィズ
# あ、はい。\n値札は作ってありますから、これを。
198 = "あ、はい。\\n値札は作ってありますから、これを。"

# カズマ
# ん？　あれ？\nこれって買った値段と\nほぼ同じだけど、いいのか？
235 = "ん？　あれ？\\nこれって買った値段と\\nほぼ同じだけど、いいのか？"

# ウィズ
# ええ、問題ありませんよ。
213 = "ええ、問題ありませんよ。"

# カズマ
# いや、あるだろ！\nそれじゃ儲けなんて出ないぞ！
206 = "いや、あるだろ！\\nそれじゃ儲けなんて出ないぞ！"

# ウィズ
# ですけど、その方が\nお客様も喜んで下さいますから。
226 = "ですけど、その方が\\nお客様も喜んで下さいますから。"

# カズマ（Ｍ）
# display as カズマ
# （ああ……。\n　ここで、その天使の微笑みを浮かべますか）
272 = "（ああ……。\\n　ここで、その天使の微笑みを浮かべますか）"

# カズマ（Ｍ）
# display as カズマ
# （なんとなくわかってたけど、\n　ウィズの商才の無さを闇レベルまで\n　落としてるのは、この性格が原因だ）
280 = "（なんとなくわかってたけど、\\n　ウィズの商才の無さを闇レベルまで\\n　落としてるのは、この性格が原因だ）"

# カズマ（Ｍ）
# display as カズマ
# （ほとんど、ご隠居が趣味や片手間に\n　お店を開くノリじゃないか。\n　しかも、仕入れてくるのは妙な物ばかりだし）
281 = "（ほとんど、ご隠居が趣味や片手間に\\n　お店を開くノリじゃないか。\\n　しかも、仕入れてくるのは妙な物ばかりだし）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、この人の良さ……。\n　本当にウィズはアンデッドの王と呼ばれる\n　リッチーなのか？）
275 = "（しかし、この人の良さ……。\\n　本当にウィズはアンデッドの王と呼ばれる\\n　リッチーなのか？）"

# カズマ（Ｍ）
# display as カズマ
# （ん？　そういやアンデッドってのは\n　何も食べなくても生きていけるのか？）
282 = "（ん？　そういやアンデッドってのは\\n　何も食べなくても生きていけるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （だとしたらウィズが\n　生きる手段としての経営に無頓着でも\n　それなりに納得はいくけど……）
278 = "（だとしたらウィズが\\n　生きる手段としての経営に無頓着でも\\n　それなりに納得はいくけど……）"

# カズマ（Ｍ）
# display as カズマ
# （そのうち聞いてみるか）
277 = "（そのうち聞いてみるか）"

# カズマ（Ｍ）
# display as カズマ
# （相変わらず、全然、まったく、客が来ない。\n　もう昼になるけどひとりも来ない……）
284 = "（相変わらず、全然、まったく、客が来ない。\\n　もう昼になるけどひとりも来ない……）"

# ウィズ
# うーん……。
211 = "うーん……。"

# カズマ
# どうした？\nノートと睨めっこして。
227 = "どうした？\\nノートと睨めっこして。"

# ウィズ
# いえ、ちょっと、今晩の予定を\nどうしようかと思いまして。
205 = "いえ、ちょっと、今晩の予定を\\nどうしようかと思いまして。"

# カズマ
# 今晩？　何かあるのか？
243 = "今晩？　何かあるのか？"

# ウィズ
# 昨日の夜、\n除霊の依頼が立て続けに入ったんです。
248 = "昨日の夜、\\n除霊の依頼が立て続けに入ったんです。"

# ウィズ
# 定期的にやってはいるんですが、\n同じ日に依頼がこんな来るのは珍しくて。
246 = "定期的にやってはいるんですが、\\n同じ日に依頼がこんな来るのは珍しくて。"

# ウィズ
# もしかしたら、私のあずかり知らぬところで\n何か起きたのかもしれません。
232 = "もしかしたら、私のあずかり知らぬところで\\n何か起きたのかもしれません。"

# カズマ（Ｍ）
# display as カズマ
# （そういや、アクアも\n　昨日、悪霊に襲われたとか言ってたな）
276 = "（そういや、アクアも\\n　昨日、悪霊に襲われたとか言ってたな）"

# カズマ（Ｍ）
# display as カズマ
# （という事は、アクア以外にも\n　そういう被害があったんだな）
279 = "（という事は、アクア以外にも\\n　そういう被害があったんだな）"

# カズマ（Ｍ）
# display as カズマ
# （霊相手だと、プリーストでも無きゃ\n　対処しようが無いだろうしなぁ。\n　俺だって会いたくねーよ）
285 = "（霊相手だと、プリーストでも無きゃ\\n　対処しようが無いだろうしなぁ。\\n　俺だって会いたくねーよ）"

# カズマ
# もしかして、その依頼を全部受けたのか。
233 = "もしかして、その依頼を全部受けたのか。"

# ウィズ
# もちろんです。\nそれも私の役目ですから。
234 = "もちろんです。\\nそれも私の役目ですから。"

# ウィズ
# アンデッドの王として、さまよえる魂は\n天に導かねばなりません。
236 = "アンデッドの王として、さまよえる魂は\\n天に導かねばなりません。"

# カズマ
# ウィズは真面目というか、マメだな。
239 = "ウィズは真面目というか、マメだな。"

# ウィズ
# えっ？\nそうでしょうか？
218 = "えっ？\\nそうでしょうか？"

# カズマ
# ああ。\nそれもウィズのいいところだけどさ。
200 = "ああ。\\nそれもウィズのいいところだけどさ。"

# ウィズ
# そ、その……ありがとうございます……。
223 = "そ、その……ありがとうございます……。"

# カズマ
# もう今夜から除霊を始めるのか？
231 = "もう今夜から除霊を始めるのか？"

# ウィズ
# ええ。\n実際、被害に遭われてる方もいますし\nこういうのは早めに行動しないと。
215 = "ええ。\\n実際、被害に遭われてる方もいますし\\nこういうのは早めに行動しないと。"

# カズマ
# そういや、こういう除霊の依頼って\nいくらくらいもらえるんだ？
224 = "そういや、こういう除霊の依頼って\\nいくらくらいもらえるんだ？"

# ウィズ
# 報酬ですか？\nそうですね、霊の強さや状況にもよりますけど、\n数千エリスくらいが平均です。
245 = "報酬ですか？\\nそうですね、霊の強さや状況にもよりますけど、\\n数千エリスくらいが平均です。"

# カズマ（Ｍ）
# display as カズマ
# （高いのか安いのか、判断に困る値段だな。\n　まあ、ウィズにしてみれば、当然のことをして\n　お金がもらえるわけだし、割はいいのか？）
286 = "（高いのか安いのか、判断に困る値段だな。\\n　まあ、ウィズにしてみれば、当然のことをして\\n　お金がもらえるわけだし、割はいいのか？）"

# ウィズ
# あの、報酬がどうかしましたか？
201 = "あの、報酬がどうかしましたか？"

# カズマ
# いや、ちょっと気になっただけだ。\nそれより、除霊には俺も付き合うよ。
208 = "いや、ちょっと気になっただけだ。\\nそれより、除霊には俺も付き合うよ。"

# ウィズ
# ええっ！？\nそ、そんな、そこまでして頂かなくても。
216 = "ええっ！？\\nそ、そんな、そこまでして頂かなくても。"

# カズマ
# これも俺が勝手についてくだけだから。\n気にしないでくれ。
221 = "これも俺が勝手についてくだけだから。\\n気にしないでくれ。"

# ウィズ
# ですが……。
225 = "ですが……。"

# カズマ
# いいからいいから。\nそうと決まればほら、仕事仕事！
203 = "いいからいいから。\\nそうと決まればほら、仕事仕事！"

# ウィズ
# は、はい……。
228 = "は、はい……。"

