# root_a20.txt.scn

[info]
0 = ""

[characters]
269 = "カズマ（Ｍ）"
266 = "カズマ"
271 = "ダクネス"
261 = "めぐみん"
263 = "アクア"
268 = "カズマ＆ダクネス＆めぐみん"

[character_subs]
# 266 = "カズマ"
340 = "３人"

[script]
# lines: 79

# カズマ（Ｍ）
# display as カズマ
# （あのコンテストから数日──）
319 = "（あのコンテストから数日──）"

# カズマ（Ｍ）
# display as カズマ
# （結局、アクアの優勝は取り消されてしまった）
337 = "（結局、アクアの優勝は取り消されてしまった）"

# カズマ（Ｍ）
# display as カズマ
# （理由は簡単だ。\n　それはアクアが女神の名を騙ったこと）
335 = "（理由は簡単だ。\\n　それはアクアが女神の名を騙ったこと）"

# カズマ（Ｍ）
# display as カズマ
# （あいつはもちろん納得していなかったが、\n　女神という証拠を提示できない以上、\n　結果を覆せる訳もなく……）
318 = "（あいつはもちろん納得していなかったが、\\n　女神という証拠を提示できない以上、\\n　結果を覆せる訳もなく……）"

# カズマ（Ｍ）
# display as カズマ
# （結果として、アクアには莫大な借金のみが\n　残ったわけだ）
338 = "（結果として、アクアには莫大な借金のみが\\n　残ったわけだ）"

# カズマ
# おはよー。
240 = "おはよー。"

# ダクネス
# おはよう。\n今日はバイトか？　クエストか？
239 = "おはよう。\\n今日はバイトか？　クエストか？"

# カズマ
# 今日はクエスト、合同のモンスター退治だ。\nそこそこいい報酬だったし、受けといた。
278 = "今日はクエスト、合同のモンスター退治だ。\\nそこそこいい報酬だったし、受けといた。"

# ダクネス
# そうか、私も別口のクエストだ。\nお互い楽にすめばいいな。
245 = "そうか、私も別口のクエストだ。\\nお互い楽にすめばいいな。"

# カズマ（Ｍ）
# display as カズマ
# （と、こんな感じで\n　俺たちもバイトやクエストをこなして、\n　借金返済の足しにしようと頑張っている）
326 = "（と、こんな感じで\\n　俺たちもバイトやクエストをこなして、\\n　借金返済の足しにしようと頑張っている）"

# カズマ（Ｍ）
# display as カズマ
# （というのは、アクアの前でだけの建前で――）
327 = "（というのは、アクアの前でだけの建前で――）"

# カズマ（Ｍ）
# display as カズマ
# （俺とめぐみんとダクネスは、\n　自分たちの生活費を稼ぐために働いている、\n　ただそれだけのことなのだ）
333 = "（俺とめぐみんとダクネスは、\\n　自分たちの生活費を稼ぐために働いている、\\n　ただそれだけのことなのだ）"

# ダクネス
# なあ、カズマ。\nそろそろアクアに本当のことを話してやったら\nどうだ？
254 = "なあ、カズマ。\\nそろそろアクアに本当のことを話してやったら\\nどうだ？"

# カズマ
# まだだめだ、きっちり反省して貰わないと\nいけないからな。
260 = "まだだめだ、きっちり反省して貰わないと\\nいけないからな。"

# ダクネス
# しかし捨てる神あれば拾う神ありとはこのこと\nだ。
244 = "しかし捨てる神あれば拾う神ありとはこのこと\\nだ。"

# ダクネス
# エリス様には感謝の祈りを捧げなければいけない。\nもちろんカズマにもな。
265 = "エリス様には感謝の祈りを捧げなければいけない。\\nもちろんカズマにもな。"

# カズマ
# 俺に祈りは耳に念仏だ。
279 = "俺に祈りは耳に念仏だ。"

# ダクネス
# ハハ、確かに。
274 = "ハハ、確かに。"

# カズマ（Ｍ）
# display as カズマ
# （詐欺集団の思い通りになるのはシャクだと\n　考えた俺は、めぐみんに一計を授けた）
339 = "（詐欺集団の思い通りになるのはシャクだと\\n　考えた俺は、めぐみんに一計を授けた）"

# カズマ（Ｍ）
# display as カズマ
# （それはギルドにクエストの発注をすること）
324 = "（それはギルドにクエストの発注をすること）"

# カズマ（Ｍ）
# display as カズマ
# （その内容はこうだ。\n　アクシズ教を名乗る詐欺集団を捕まえる）
323 = "（その内容はこうだ。\\n　アクシズ教を名乗る詐欺集団を捕まえる）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、俺の用意出来る報酬金なんて\n　たかがしれている）
321 = "（しかし、俺の用意出来る報酬金なんて\\n　たかがしれている）"

# カズマ（Ｍ）
# display as カズマ
# （当然、そんなクエストには冒険者の食いつきも\n　悪い）
334 = "（当然、そんなクエストには冒険者の食いつきも\\n　悪い）"

# カズマ（Ｍ）
# display as カズマ
# （しかしまさに拾う神ありで、なんとエリス教徒が\n　手を貸してくれたのだ）
322 = "（しかしまさに拾う神ありで、なんとエリス教徒が\\n　手を貸してくれたのだ）"

# カズマ（Ｍ）
# display as カズマ
# （アクアの中身はあんなだけど、\n　エリス様とアクアは先輩後輩の間柄だ）
331 = "（アクアの中身はあんなだけど、\\n　エリス様とアクアは先輩後輩の間柄だ）"

# カズマ（Ｍ）
# display as カズマ
# （エリス教徒としては、\n　信仰する女神の先輩であるアクアの名を\n　悪用する奴も許せなかったのだろう）
332 = "（エリス教徒としては、\\n　信仰する女神の先輩であるアクアの名を\\n　悪用する奴も許せなかったのだろう）"

# カズマ（Ｍ）
# display as カズマ
# （ほどなくして詐欺集団は捕まり、\n　当然アクアの借金もチャラになった）
328 = "（ほどなくして詐欺集団は捕まり、\\n　当然アクアの借金もチャラになった）"

# カズマ（Ｍ）
# display as カズマ
# （だが、俺はそれをアクアに話してはいない。\n　それはもちろん、あいつに反省をさせるためだ）
325 = "（だが、俺はそれをアクアに話してはいない。\\n　それはもちろん、あいつに反省をさせるためだ）"

# めぐみん
# ダクネスッ！\nあ、カズマもおはようございます！
272 = "ダクネスッ！\\nあ、カズマもおはようございます！"

# カズマ
# おはよう、めぐみん。\nなんだ、どうしたんだ？
238 = "おはよう、めぐみん。\\nなんだ、どうしたんだ？"

# めぐみん
# ちょっと来てください！\nアクアが、アクアが……。
248 = "ちょっと来てください！\\nアクアが、アクアが……。"

# カズマ
# アクアがいったいどうしたってんだよ。
264 = "アクアがいったいどうしたってんだよ。"

# めぐみん
# 扉の前に座り込んでいるのです。
288 = "扉の前に座り込んでいるのです。"

# ダクネス
# 座り込んでいる？
286 = "座り込んでいる？"

# カズマ
# 貧血にでもなったのか？
316 = "貧血にでもなったのか？"

# めぐみん
# いえ、そういうわけでもなさそうで……\nとにかく様子が変で、怖いのです。
232 = "いえ、そういうわけでもなさそうで……\\nとにかく様子が変で、怖いのです。"

# カズマ
# 怖い？
287 = "怖い？"

# アクア
# 働きたくない、もう疲れた、働きたくない、\nもう疲れた、働きたくない、もう限界、もう無理、\n働きたくない、働きたくない、働きたくない。
280 = "働きたくない、もう疲れた、働きたくない、\\nもう疲れた、働きたくない、もう限界、もう無理、\\n働きたくない、働きたくない、働きたくない。"

# カズマ
# 確かに、これは恐いな。
313 = "確かに、これは恐いな。"

# めぐみん
# でしょう？\n声もかけづらいというか、\nかけたら呪われそうです。
249 = "でしょう？\\n声もかけづらいというか、\\nかけたら呪われそうです。"

# ダクネス
# どうしたんだ、アクア！\nまさか働き過ぎて心が壊れてしまったのか？
252 = "どうしたんだ、アクア！\\nまさか働き過ぎて心が壊れてしまったのか？"

# アクア
# 働きたくない、もう疲れた、働きたくない、\nもう疲れた、働きたくない、もう限界、もう無理、\n働きたくない、働きたくない、働きたくない。
# 280 = "働きたくない、もう疲れた、働きたくない、\\nもう疲れた、働きたくない、もう限界、もう無理、\\n働きたくない、働きたくない、働きたくない。"

# ダクネス
# カズマ、これは……\nさすがに危険ではないか？\nこんなアクア、初めてだぞ。
267 = "カズマ、これは……\\nさすがに危険ではないか？\\nこんなアクア、初めてだぞ。"

# めぐみん
# ええ、反省を促すためとはいえ、\n少し働かせ過ぎたのかもしれません。
236 = "ええ、反省を促すためとはいえ、\\n少し働かせ過ぎたのかもしれません。"

# カズマ
# うーん……そうだなぁ……。
234 = "うーん……そうだなぁ……。"

# アクア
# チラ……。
273 = "チラ……。"

# カズマ（Ｍ）
# display as カズマ
# （……ん？）
317 = "（……ん？）"

# アクア
# は、働きたくないわね、もう疲れたし？\n働きたくない、もう疲れた、働きたくない、\nもう限界、もう無理、働きたくない、働きたくない。
255 = "は、働きたくないわね、もう疲れたし？\\n働きたくない、もう疲れた、働きたくない、\\nもう限界、もう無理、働きたくない、働きたくない。"

# カズマ（Ｍ）
# display as カズマ
# （んんん～？）
330 = "（んんん～？）"

# アクア
# 働きたくない、働きたくない、働きたくない、\n働きたくない、働きたくない、働きたくない、\n働きたくない、働きたくない、働きたくない……。
281 = "働きたくない、働きたくない、働きたくない、\\n働きたくない、働きたくない、働きたくない、\\n働きたくない、働きたくない、働きたくない……。"

# カズマ
# …………。
227 = "…………。"

# ダクネス
# どうした、カズマ？
251 = "どうした、カズマ？"

# カズマ
# ふたりとも、ちょっと耳を貸せ。
258 = "ふたりとも、ちょっと耳を貸せ。"

# めぐみん
# どうしたんです？
253 = "どうしたんです？"

# カズマ
# 今から言うように俺に話を合わせてくれ。
277 = "今から言うように俺に話を合わせてくれ。"

# カズマ
# ごにょごにょ……。
243 = "ごにょごにょ……。"

# カズマ
# いや、そうだな。\nやっぱり、少し休ませないとダメだろ。
233 = "いや、そうだな。\\nやっぱり、少し休ませないとダメだろ。"

# めぐみん
# ええ、そうですね。\nこれは本気で心配です。
235 = "ええ、そうですね。\\nこれは本気で心配です。"

# ダクネス
# では、アクアのバイト先に連絡を入れておくか。\n今日は体調不良で休みにしてもらいたいと。
250 = "では、アクアのバイト先に連絡を入れておくか。\\n今日は体調不良で休みにしてもらいたいと。"

# アクア
# ふふん、計画通り。
259 = "ふふん、計画通り。"

# カズマ＆ダクネス＆めぐみん
# display as ３人
# ジーー……。
270 = "ジーー……。"

# アクア
# あ……。
228 = "あ……。"

# めぐみん
# 今、笑いましたよね？
276 = "今、笑いましたよね？"

# ダクネス
# ああ、笑ったな。\nしてやったりと言わんばかりに笑ったな。
229 = "ああ、笑ったな。\\nしてやったりと言わんばかりに笑ったな。"

# カズマ
# やっぱりな。\n変だと思ったんだ。\n壊れたふりをして、同情を引こうとしてたのか。
262 = "やっぱりな。\\n変だと思ったんだ。\\n壊れたふりをして、同情を引こうとしてたのか。"

# めぐみん
# はあ……。\n心配して損しました。
256 = "はあ……。\\n心配して損しました。"

# アクア
# ち、違うわよっ！\n同情を引くなんて、女神がするはずないでしょ！？\nそれに壊れそうになってるのは事実なんだから！
247 = "ち、違うわよっ！\\n同情を引くなんて、女神がするはずないでしょ！？\\nそれに壊れそうになってるのは事実なんだから！"

# アクア
# 第一、私にこんなことをさせるほど\n追い詰めてるのはそっちじゃない！\n鬼！　悪魔！
315 = "第一、私にこんなことをさせるほど\\n追い詰めてるのはそっちじゃない！\\n鬼！　悪魔！"

# カズマ
# おい、逆ギレかよ！
237 = "おい、逆ギレかよ！"

# アクア
# だいたい女神にこんな肉体労働させて\n恥ずかしくないの！？
246 = "だいたい女神にこんな肉体労働させて\\n恥ずかしくないの！？"

# カズマ
# こうなったすべての元凶はお前だろうが、駄女神！
241 = "こうなったすべての元凶はお前だろうが、駄女神！"

# アクア
# あー、また駄女神って言った！
231 = "あー、また駄女神って言った！"

# めぐみん
# はあ、カズマそろそろ本当のことを話して\nあげては？
257 = "はあ、カズマそろそろ本当のことを話して\\nあげては？"

# ダクネス
# このままだと本当に壊れてしまうぞ。
242 = "このままだと本当に壊れてしまうぞ。"

# カズマ（Ｍ）
# display as カズマ
# （確かにこれ以上は可哀想か）
336 = "（確かにこれ以上は可哀想か）"

# アクア
# 私はもっと楽したいの！\n甘やかされたいの！\nぬくぬくした優しい世界で生きて行きたいの！
314 = "私はもっと楽したいの！\\n甘やかされたいの！\\nぬくぬくした優しい世界で生きて行きたいの！"

# カズマ
# あー、こいつダメだ。
230 = "あー、こいつダメだ。"

# カズマ（Ｍ）
# display as カズマ
# （やっぱりもう少し黙っていよう）
329 = "（やっぱりもう少し黙っていよう）"

# カズマ（Ｍ）
# display as カズマ
# （うん、それがいい）
320 = "（うん、それがいい）"

