# root_f20.txt.scn

[info]
0 = ""

[characters]
243 = "ウィズ"
245 = "カズマ（Ｍ）"
244 = "カズマ"
242 = "アクア"

[character_subs]
# 244 = "カズマ"
290 = "？？？"

[script]
# lines: 57

# ウィズ
# はぁ……。
235 = "はぁ……。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、なるほど。\n　ウィズの顔色が悪かったのは、これか）
285 = "（ああ、なるほど。\\n　ウィズの顔色が悪かったのは、これか）"

# ウィズ
# そ、それでは、浄化の作業、始めましょうか。
218 = "そ、それでは、浄化の作業、始めましょうか。"

# カズマ
# 声が震えてるぞ、ウィズ。
252 = "声が震えてるぞ、ウィズ。"

# ウィズ
# それは、まあ……。
222 = "それは、まあ……。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、実際は声どころか\n　身体もガクガク震えてるんだが。\n　これ、相当、無理してないか？）
288 = "（まあ、実際は声どころか\\n　身体もガクガク震えてるんだが。\\n　これ、相当、無理してないか？）"

# カズマ
# やっぱり教会は苦手なのか。\n入ったら浄化されちまうとか。
239 = "やっぱり教会は苦手なのか。\\n入ったら浄化されちまうとか。"

# ウィズ
# いえ、教会とはいえ、\nさすがにその場所自体に\n私を浄化させるほどの力はありません。
210 = "いえ、教会とはいえ、\\nさすがにその場所自体に\\n私を浄化させるほどの力はありません。"

# ウィズ
# えー、ですが、やはり神聖な場所なので\nちょっとピリピリするというか\nチリチリするというか、そんな感じで。
212 = "えー、ですが、やはり神聖な場所なので\\nちょっとピリピリするというか\\nチリチリするというか、そんな感じで。"

# ウィズ
# あ、でも、本当にそれだけですので。\n大丈夫ですよ、大丈夫。
207 = "あ、でも、本当にそれだけですので。\\n大丈夫ですよ、大丈夫。"

# カズマ
# そう言ってる割には後ずさりしてるし！
221 = "そう言ってる割には後ずさりしてるし！"

# ウィズ
# に、苦手なものは苦手なので……。
233 = "に、苦手なものは苦手なので……。"

# カズマ
# だったら、ここの浄化は\nアクアに任せてもいいんじゃないか？
225 = "だったら、ここの浄化は\\nアクアに任せてもいいんじゃないか？"

# ウィズ
# あ、それはダメなんです。
206 = "あ、それはダメなんです。"

# カズマ
# ん？　何か問題があるのか？
241 = "ん？　何か問題があるのか？"

# ウィズ
# 私のは、言ってみれば、\n霊にお願いして自主的に還ってもらう感じですね。
277 = "私のは、言ってみれば、\\n霊にお願いして自主的に還ってもらう感じですね。"

# ウィズ
# 要は心残りなどを解消して、\n成仏してもらうんです。
280 = "要は心残りなどを解消して、\\n成仏してもらうんです。"

# カズマ
# じゃあ、アクアがやってるのはなんなんだ？
216 = "じゃあ、アクアがやってるのはなんなんだ？"

# ウィズ
# 除霊と言ってもさまざまですが、\nアクア様が私によく向ける殺気のようなもので\n除霊をしているなら――
282 = "除霊と言ってもさまざまですが、\\nアクア様が私によく向ける殺気のようなもので\\n除霊をしているなら――"

# ウィズ
# 霊を天に還すのではなく、消滅させているかと。
284 = "霊を天に還すのではなく、消滅させているかと。"

# カズマ
# 要は、ウィズはお帰り下さいってお願いする、\nアクアは、聞く耳持たずばっさり殺す？
279 = "要は、ウィズはお帰り下さいってお願いする、\\nアクアは、聞く耳持たずばっさり殺す？"

# ウィズ
# 悪霊の類いでしたら、それも致し方無しなんです。\nでも、先ほどの子供たちのように無害な霊も\nいますので。
257 = "悪霊の類いでしたら、それも致し方無しなんです。\\nでも、先ほどの子供たちのように無害な霊も\\nいますので。"

# アクア
# display as ？？？
# つまり、アクア様はそんな可愛らしい霊も\n無慈悲に除霊をしている。\nそう言いたいのね？
226 = "つまり、アクア様はそんな可愛らしい霊も\\n無慈悲に除霊をしている。\\nそう言いたいのね？"

# ウィズ
# ひっ、その声は……。
237 = "ひっ、その声は……。"

# アクア
# 私よ！
278 = "私よ！"

# カズマ
# うおっ！\nお前どこからわいて出た！？
211 = "うおっ！\\nお前どこからわいて出た！？"

# アクア
# 悪いんだけど、\nカズマはちょっと黙っててくれるかしら。
256 = "悪いんだけど、\\nカズマはちょっと黙っててくれるかしら。"

# カズマ（Ｍ）
# display as カズマ
# （あー、変なスイッチが入っちまってる……）
286 = "（あー、変なスイッチが入っちまってる……）"

# アクア
# なるほど、ウィズは\nそういう目で私を見てたのね？\nふ～ん？
231 = "なるほど、ウィズは\\nそういう目で私を見てたのね？\\nふ～ん？"

# ウィズ
# 違います！\nわ、私はですね、除霊と浄化の違いを\n言っていただけで！
281 = "違います！\\nわ、私はですね、除霊と浄化の違いを\\n言っていただけで！"

# アクア
# でも、私が考えなしにジェノサイドをするような\n女神って言ってたじゃない。
229 = "でも、私が考えなしにジェノサイドをするような\\n女神って言ってたじゃない。"

# ウィズ
# そんなこと言ってません！！
224 = "そんなこと言ってません！！"

# カズマ（Ｍ）
# display as カズマ
# （うん、確かに言ってない）
287 = "（うん、確かに言ってない）"

# アクア
# 偶然、こんな神聖な場所に来てみれば\nアンデッドの王がいるなんて。
249 = "偶然、こんな神聖な場所に来てみれば\\nアンデッドの王がいるなんて。"

# アクア
# これはまずいわよね！\n除霊よ、除霊しなくちゃ！
214 = "これはまずいわよね！\\n除霊よ、除霊しなくちゃ！"

# ウィズ
# ひっ！？\nや、やめ、やめて下さい！！
238 = "ひっ！？\\nや、やめ、やめて下さい！！"

# カズマ
# おい、駄女神。
213 = "おい、駄女神。"

# アクア
# あいたっ！？\nほ、本気で殴ったわね！？
208 = "あいたっ！？\\nほ、本気で殴ったわね！？"

# カズマ
# 仮にも女神が神聖な場所で騒ぐなよ。\nてか、お前は何しに来たんだ？
248 = "仮にも女神が神聖な場所で騒ぐなよ。\\nてか、お前は何しに来たんだ？"

# アクア
# 除霊に決まってるでしょ。\nでもここにいる霊は\nエリス教の信者ばっかりだったのよ。
283 = "除霊に決まってるでしょ。\\nでもここにいる霊は\\nエリス教の信者ばっかりだったのよ。"

# ウィズ
# そう言えば、ここはエリス教の教会ですね。
220 = "そう言えば、ここはエリス教の教会ですね。"

# アクア
# で、せっかくだから\nアクシズ教に改宗しなさいって勧めたの。
227 = "で、せっかくだから\\nアクシズ教に改宗しなさいって勧めたの。"

# カズマ（Ｍ）
# display as カズマ
# （霊に改宗を迫るって\n　どういう意味があるんだ……）
289 = "（霊に改宗を迫るって\\n　どういう意味があるんだ……）"

# アクア
# なのに、あいつら\n頑として聞き入れようとしないのよ？\nほんっとにエリス教徒は石頭だわ！
230 = "なのに、あいつら\\n頑として聞き入れようとしないのよ？\\nほんっとにエリス教徒は石頭だわ！"

# カズマ
# で、それがムカついてジェノサイドしちまったと。
228 = "で、それがムカついてジェノサイドしちまったと。"

# アクア
# してないわよ！
215 = "してないわよ！"

# アクア
# 一応、あいつらだってエリスの下僕なんだから。\nここにいるだけで悪さはしてないしね。
246 = "一応、あいつらだってエリスの下僕なんだから。\\nここにいるだけで悪さはしてないしね。"

# ウィズ
# そうだったんですか。\n知らなかったとはいえ、失礼なことを\n言ってしまってすみませんでした。
219 = "そうだったんですか。\\n知らなかったとはいえ、失礼なことを\\n言ってしまってすみませんでした。"

# アクア
# いい、ウィズ。\n女神を愚弄するなんて、\n天罰を受けてしかるべき行いなのよ？
209 = "いい、ウィズ。\\n女神を愚弄するなんて、\\n天罰を受けてしかるべき行いなのよ？"

# アクア
# それを見逃して貰えるんだから、\nありがたく思いなさい。
223 = "それを見逃して貰えるんだから、\\nありがたく思いなさい。"

# ウィズ
# は、はい、ありがとうございます。
234 = "は、はい、ありがとうございます。"

# カズマ
# んで、ここの除霊はどうするんだ？
240 = "んで、ここの除霊はどうするんだ？"

# ウィズ
# 害はなさそうですし\nエリス教の人にお任せしましょう。
253 = "害はなさそうですし\\nエリス教の人にお任せしましょう。"

# カズマ
# じゃあ、次の場所に行くか。
217 = "じゃあ、次の場所に行くか。"

# ウィズ
# あ、これで私のところに来た依頼は全部です。
205 = "あ、これで私のところに来た依頼は全部です。"

# カズマ
# なんだ、終わりか。\n良かった、色々あったけどお疲れ。
232 = "なんだ、終わりか。\\n良かった、色々あったけどお疲れ。"

# ウィズ
# はい、お疲れさまでした、カズマさん。
236 = "はい、お疲れさまでした、カズマさん。"

