# root_a15.txt.scn

[info]
0 = ""

[characters]
316 = "アクア"
320 = "カズマ"
309 = "めぐみん"
328 = "ダクネス"
324 = "カズマ（Ｍ）"
323 = "カズマ＆ダクネス"

[character_subs]
# 320 = "カズマ"
376 = "２人"

[script]
# lines: 66

# アクア
# ちょ、ちょっと、カズマー！
297 = "ちょ、ちょっと、カズマー！"

# アクア
# な、な、なんで！\n走らなきゃいけないのよ！
303 = "な、な、なんで！\\n走らなきゃいけないのよ！"

# カズマ
# 走り込みはすべての基本だ！\nスポ根ものには必須アイテムだ！！
371 = "走り込みはすべての基本だ！\\nスポ根ものには必須アイテムだ！！"

# アクア
# スポ根ってなによ！！\nコンテストに全然関係ないんですけど！？
327 = "スポ根ってなによ！！\\nコンテストに全然関係ないんですけど！？"

# カズマ
# わかってないな。\nミスコンに来るやつはみんな、\n血の滲むような努力をしてるんだぞ。
315 = "わかってないな。\\nミスコンに来るやつはみんな、\\n血の滲むような努力をしてるんだぞ。"

# アクア
# 私は女神なのよ！\nそんなことをする必要なんてないの！
369 = "私は女神なのよ！\\nそんなことをする必要なんてないの！"

# カズマ
# お前はまず、その根性を叩き直す必要がある！
284 = "お前はまず、その根性を叩き直す必要がある！"

# アクア
# あー！　もう！　バカバカしいわ！\nこんな走るのなんて、無駄よ無駄！
273 = "あー！　もう！　バカバカしいわ！\\nこんな走るのなんて、無駄よ無駄！"

# カズマ
# めぐみん、やれ。
310 = "めぐみん、やれ。"

# めぐみん
# 本気ですか？
338 = "本気ですか？"

# カズマ
# あいつを真剣に取り組ませるためには、\n俺たちの本気を示す必要があるんだよ。
272 = "あいつを真剣に取り組ませるためには、\\n俺たちの本気を示す必要があるんだよ。"

# めぐみん
# ですが、いきなりアクアに、というのは\nやり過ぎではありませんか？
299 = "ですが、いきなりアクアに、というのは\\nやり過ぎではありませんか？"

# めぐみん
# アクアはダクネスのように頑丈では\nないのですよ？
318 = "アクアはダクネスのように頑丈では\\nないのですよ？"

# ダクネス
# そうだぞ。\nま、まずは、私にやって、\nこちらの意思を示すのもありだと思うんだ。
290 = "そうだぞ。\\nま、まずは、私にやって、\\nこちらの意思を示すのもありだと思うんだ。"

# カズマ
# お前はただ爆裂魔法をくらいたいだけだろ。
283 = "お前はただ爆裂魔法をくらいたいだけだろ。"

# めぐみん
# では、本当にやりますよ？\nやりますからね？
300 = "では、本当にやりますよ？\\nやりますからね？"

# めぐみん
# 光に覆われし漆黒よ。\n夜を纏いし爆炎よ――
330 = "光に覆われし漆黒よ。\\n夜を纏いし爆炎よ――"

# アクア
# って、ええ！？\nなんで爆裂魔法を詠唱してるの！？
298 = "って、ええ！？\\nなんで爆裂魔法を詠唱してるの！？"

# カズマ
# お前の特訓に取り組む姿勢が不真面目だからだ。\nさあ、爆裂魔法を食らうのが嫌なら走れ！
282 = "お前の特訓に取り組む姿勢が不真面目だからだ。\\nさあ、爆裂魔法を食らうのが嫌なら走れ！"

# アクア
# こんの！！\n後で覚えてなさいよ、クソニート！
287 = "こんの！！\\n後で覚えてなさいよ、クソニート！"

# カズマ
# エリス様はそんな汚い言葉は言わないよな？
319 = "エリス様はそんな汚い言葉は言わないよな？"

# アクア
# あ、後で覚えておいでなさいですわっ！
269 = "あ、後で覚えておいでなさいですわっ！"

# めぐみん
# カズマ？\nこんなことをして本当に意味があるんですか？
325 = "カズマ？\\nこんなことをして本当に意味があるんですか？"

# ダクネス
# コンテストに体力はあまり関係ないと思うのだが。
326 = "コンテストに体力はあまり関係ないと思うのだが。"

# めぐみん
# そうですよ。\nそれよりもまず、言葉遣いとか所作とか\nそういう部分を矯正すべきだと思うのです。
292 = "そうですよ。\\nそれよりもまず、言葉遣いとか所作とか\\nそういう部分を矯正すべきだと思うのです。"

# カズマ
# 確かに走ること事態には何も意味がない。
367 = "確かに走ること事態には何も意味がない。"

# ダクネス
# だったら、どうして。
295 = "だったら、どうして。"

# カズマ
# だが、辛いことをやりきったという事実が\n必ずアクアに何かをもたらすはずだ。
294 = "だが、辛いことをやりきったという事実が\\n必ずアクアに何かをもたらすはずだ。"

# ダクネス
# なるほど。\nこれは精神的な特訓という訳か。
305 = "なるほど。\\nこれは精神的な特訓という訳か。"

# カズマ
# あいつは考え方が、とことんあまちゃんだからな。
271 = "あいつは考え方が、とことんあまちゃんだからな。"

# カズマ
# まずはそこをどうにかしないと、\n何をやっても血肉にならないと思ったんだよ。
308 = "まずはそこをどうにかしないと、\\n何をやっても血肉にならないと思ったんだよ。"

# めぐみん
# 確かに一理ありますね。\nですが……。
366 = "確かに一理ありますね。\\nですが……。"

# カズマ
# なんだ？\nやっぱり、やり過ぎとか言うんじゃないだろうな。
307 = "なんだ？\\nやっぱり、やり過ぎとか言うんじゃないだろうな。"

# めぐみん
# そうではなく、このままだとアクア食べられますよ。
293 = "そうではなく、このままだとアクア食べられますよ。"

# カズマ（Ｍ）
# display as カズマ
# （は？）
374 = "（は？）"

# アクア
# いいいいいやああああああ！\nカズマ、カズマさん！\n蛙、なんか蛙が出てきたんですけど！！
274 = "いいいいいやああああああ！\\nカズマ、カズマさん！\\n蛙、なんか蛙が出てきたんですけど！！"

# カズマ
# なっ！？
304 = "なっ！？"

# アクア
# いや、いやああ、蛙の食べられるの、もう嫌あ！！
275 = "いや、いやああ、蛙の食べられるの、もう嫌あ！！"

# カズマ
# お、おい、ダクネス！
281 = "お、おい、ダクネス！"

# ダクネス
# 私が代わりに食べられろというのだな！
368 = "私が代わりに食べられろというのだな！"

# カズマ
# ちっがう！\nアクアを助けろ！
296 = "ちっがう！\\nアクアを助けろ！"

# アクア
# いやあ、もう無理、もう無理い！\n息が、息があがって――
277 = "いやあ、もう無理、もう無理い！\\n息が、息があがって――"

# カズマ＆ダクネス
# display as ２人
# あ。
270 = "あ。"

# めぐみん
# アクア、食べられちゃいましたよ！？
317 = "アクア、食べられちゃいましたよ！？"

# カズマ
# このまましばらく反省させよう。
286 = "このまましばらく反省させよう。"

# めぐみん
# ええっ！？\nさすがにそれはちょっと……。
280 = "ええっ！？\\nさすがにそれはちょっと……。"

# カズマ（Ｍ）
# display as カズマ
# （確かにそれもそうか）
375 = "（確かにそれもそうか）"

# カズマ
# めぐみん、爆裂魔法だ！\nあそこに撃ち込め！
312 = "めぐみん、爆裂魔法だ！\\nあそこに撃ち込め！"

# めぐみん
# でも、それだとアクアまで！
301 = "でも、それだとアクアまで！"

# カズマ
# 大丈夫だ。\nカエルの口の中だし、直撃しても\n少しはダメージも軽減されるだろ！
333 = "大丈夫だ。\\nカエルの口の中だし、直撃しても\\n少しはダメージも軽減されるだろ！"

# ダクネス
# いや、それは\n一緒に黒コゲになるだけなのでは？
276 = "いや、それは\\n一緒に黒コゲになるだけなのでは？"

# カズマ
# すぐ助けに行くぞ！！\nさすがにヤバい！
289 = "すぐ助けに行くぞ！！\\nさすがにヤバい！"

# ダクネス
# よし！\nならば私が先頭に立って壁になろう！
313 = "よし！\\nならば私が先頭に立って壁になろう！"

# カズマ
# 頼む！\nけど、そのまま勝手に食われるんじゃないぞ？
372 = "頼む！\\nけど、そのまま勝手に食われるんじゃないぞ？"

# ダクネス
# なんだと！？\n防御の甲斐なく、カエルに捕食され\n粘液まみれになってはいけないのか！？
306 = "なんだと！？\\n防御の甲斐なく、カエルに捕食され\\n粘液まみれになってはいけないのか！？"

# カズマ
# 最初っから捕食されること前提じゃねーか！！
336 = "最初っから捕食されること前提じゃねーか！！"

# めぐみん
# とにかく、\nアクアを口から引っ張り出してください！\nそこに爆裂魔法をぶつけます！
302 = "とにかく、\\nアクアを口から引っ張り出してください！\\nそこに爆裂魔法をぶつけます！"

# カズマ
# わかった！\nよしダクネス、突っ込むぞ！！
314 = "わかった！\\nよしダクネス、突っ込むぞ！！"

# ダクネス
# 望むところだ！
337 = "望むところだ！"

# アクア
# うううううう……。\nべとべと気持ち悪い……気持ち悪いよ。
279 = "うううううう……。\\nべとべと気持ち悪い……気持ち悪いよ。"

# カズマ
# う、蛙臭い！
278 = "う、蛙臭い！"

# めぐみん
# カズマ、とりあえず帰りませんか？
321 = "カズマ、とりあえず帰りませんか？"

# ダクネス
# そうだな。\nまずはアクアのこのネチョネチョを落として\nやらないと。
291 = "そうだな。\\nまずはアクアのこのネチョネチョを落として\\nやらないと。"

# アクア
# カズマ、私もう歩けない。\nおんぶして。
322 = "カズマ、私もう歩けない。\\nおんぶして。"

# カズマ
# 絶対に嫌だ！
370 = "絶対に嫌だ！"

# カズマ
# （はぁ……とりあえず風呂には行ったら、\n　誰かにエリス様についての意見を聞いてみるか）
373 = "（はぁ……とりあえず風呂には行ったら、\\n　誰かにエリス様についての意見を聞いてみるか）"

[selections]
285 = "このまましばらく反省させよう"
311 = "めぐみん、爆裂魔法だ！"
288 = "すぐに助けに行くぞ！"
