# root_b01.txt.scn

[info]
0 = ""

[characters]
256 = "カズマ（Ｍ）"
254 = "カズマ"
250 = "めぐみん"

[character_subs]
# 254 = "カズマ"

[script]
# lines: 53

# カズマ（Ｍ）
# display as カズマ
# （指輪騒動から数日――\n　平穏な日々が俺達の元に戻ってきた）
295 = "（指輪騒動から数日――\\n　平穏な日々が俺達の元に戻ってきた）"

# カズマ（Ｍ）
# display as カズマ
# （つまりそれは、\n　日常が戻ってきたということでもあり……）
293 = "（つまりそれは、\\n　日常が戻ってきたということでもあり……）"

# カズマ（Ｍ）
# display as カズマ
# （また、めぐみんの爆裂魔法の練習に\n　付き合わされる日々が始まったわけだ）
294 = "（また、めぐみんの爆裂魔法の練習に\\n　付き合わされる日々が始まったわけだ）"

# カズマ
# おーい、めぐみん。\nここら辺でいいんじゃないか？
235 = "おーい、めぐみん。\\nここら辺でいいんじゃないか？"

# めぐみん
# そうですね。\nこれだけ街から離れれば\n怒られることもないでしょう。
239 = "そうですね。\\nこれだけ街から離れれば\\n怒られることもないでしょう。"

# カズマ
# なあ、今までさんざん付き合ってきて\nこんなことを言うのもなんなんだが、\n練習って必要なのか？
245 = "なあ、今までさんざん付き合ってきて\\nこんなことを言うのもなんなんだが、\\n練習って必要なのか？"

# めぐみん
# 当然ですよ。\n何をおかしなことを言い出すのです？
270 = "当然ですよ。\\n何をおかしなことを言い出すのです？"

# カズマ
# いや、考えてみろよ。\n例えば――
230 = "いや、考えてみろよ。\\n例えば――"

# カズマ
# 今回のスカルドラゴンみたいに\n急な敵襲があったとき、\n魔力切れだったらなにもできないだろ？
262 = "今回のスカルドラゴンみたいに\\n急な敵襲があったとき、\\n魔力切れだったらなにもできないだろ？"

# カズマ
# 備えあればなんとやらだ。\n魔力を温存しといて損はないんじゃないか？
265 = "備えあればなんとやらだ。\\n魔力を温存しといて損はないんじゃないか？"

# めぐみん
# ……それはつまり、\nいつ来るかもわからない相手のために\n爆裂魔法を我慢しろというのですか！？
226 = "……それはつまり、\\nいつ来るかもわからない相手のために\\n爆裂魔法を我慢しろというのですか！？"

# めぐみん
# カズマは私に、悶々とした日々を\n過ごせというのですか！？
255 = "カズマは私に、悶々とした日々を\\n過ごせというのですか！？"

# カズマ
# い、いや、そこまで言ってないけどさぁ。
229 = "い、いや、そこまで言ってないけどさぁ。"

# めぐみん
# 第一、ここは魔王の城から一番遠い街ですよ？\n頻繁にあのような高レベルのモンスターが\n襲ってくることなどありません。
288 = "第一、ここは魔王の城から一番遠い街ですよ？\\n頻繁にあのような高レベルのモンスターが\\n襲ってくることなどありません。"

# めぐみん
# 不確かなもののために我慢するくらいなら、\n我が秘技である爆裂魔法を放ち\nスッキリしたいのです！
260 = "不確かなもののために我慢するくらいなら、\\n我が秘技である爆裂魔法を放ち\\nスッキリしたいのです！"

# カズマ（Ｍ）
# display as カズマ
# （結局はそこかよ……）
296 = "（結局はそこかよ……）"

# めぐみん
# さあ、いきますよ！
238 = "さあ、いきますよ！"

# めぐみん
# 黒より黒く、闇より昏き漆黒に\n我が真紅の混淆を望みたもう。
291 = "黒より黒く、闇より昏き漆黒に\\n我が真紅の混淆を望みたもう。"

# めぐみん
# 覚醒の時、来たれり。\n無謬の境界に堕ちし理、\n無形の歪みとなりて、現出せよ。
289 = "覚醒の時、来たれり。\\n無謬の境界に堕ちし理、\\n無形の歪みとなりて、現出せよ。"

# めぐみん
# 踊れ、踊れ、踊れ、\n我が力の本流に望むは崩壊なり、\n並ぶ者無き崩壊なり。
290 = "踊れ、踊れ、踊れ、\\n我が力の本流に望むは崩壊なり、\\n並ぶ者無き崩壊なり。"

# めぐみん
# 万象等しく灰燼に帰し\n深淵より来たれ！
259 = "万象等しく灰燼に帰し\\n深淵より来たれ！"

# めぐみん
# エクスプローーーージョンッ！
253 = "エクスプローーーージョンッ！"

# めぐみん
# この感覚……、\nいい、実に素晴らしいです……。
237 = "この感覚……、\\nいい、実に素晴らしいです……。"

# めぐみん
# 今日も燃え尽きました。\nもはや、悔いなし……。
263 = "今日も燃え尽きました。\\nもはや、悔いなし……。"

# めぐみん
# ……どうでしたか？\n本日の爆裂魔法は？
227 = "……どうでしたか？\\n本日の爆裂魔法は？"

# カズマ
# うーん、そうだな。\n体の芯までズンと響くいい爆裂魔法だったぜ。\n空気も良い具合に振動して肌がビリビリした。
231 = "うーん、そうだな。\\n体の芯までズンと響くいい爆裂魔法だったぜ。\\n空気も良い具合に振動して肌がビリビリした。"

# めぐみん
# ふふ、そうでしょう？\n我ながら会心の一撃だったと思います。
248 = "ふふ、そうでしょう？\\n我ながら会心の一撃だったと思います。"

# めぐみん
# この一撃なら、デストロイヤーも\n私１人で止められたはずです。
236 = "この一撃なら、デストロイヤーも\\n私１人で止められたはずです。"

# カズマ
# ……さすがにそれは無理だろ。
225 = "……さすがにそれは無理だろ。"

# カズマ
# んじゃ、満足したなら帰るぞ。\nほら、おぶされ。
251 = "んじゃ、満足したなら帰るぞ。\\nほら、おぶされ。"

# めぐみん
# ……大丈夫なのですか？
228 = "……大丈夫なのですか？"

# カズマ
# 大丈夫ってなにがだよ？
268 = "大丈夫ってなにがだよ？"

# めぐみん
# 盗んだりしませんよね？
273 = "盗んだりしませんよね？"

# カズマ
# 盗むって……。
272 = "盗むって……。"

# カズマ（Ｍ）
# display as カズマ
# （頬をほんのり染めながら\n　足をモジモジさせている。\n　……つまりこれは、間違いないか）
297 = "（頬をほんのり染めながら\\n　足をモジモジさせている。\\n　……つまりこれは、間違いないか）"

# カズマ
# おい、言っておくけどな、\n盗んでいたのは俺の意思じゃなかったんだ。\n言うなればこっちだって被害者なんだぞ？
232 = "おい、言っておくけどな、\\n盗んでいたのは俺の意思じゃなかったんだ。\\n言うなればこっちだって被害者なんだぞ？"

# カズマ
# おまけにそんな\n犯罪者を見るような顔をされて……\nとんだ風評被害だ！
234 = "おまけにそんな\\n犯罪者を見るような顔をされて……\\nとんだ風評被害だ！"

# めぐみん
# パンツ裁判なんて下劣なものを開いておいて\nよく言いますよ。
258 = "パンツ裁判なんて下劣なものを開いておいて\\nよく言いますよ。"

# カズマ
# おう、だったら這ってでも１人で帰れ。\n俺は先に戻ってるからな。
233 = "おう、だったら這ってでも１人で帰れ。\\n俺は先に戻ってるからな。"

# めぐみん
# ちょっと待ってください！\n冗談、冗談ですよ！
241 = "ちょっと待ってください！\\n冗談、冗談ですよ！"

# カズマ
# つーかさぁ、そんな風に言うくらいなら\nアクアかダクネスに付き合ってもらえばいいだろ？
242 = "つーかさぁ、そんな風に言うくらいなら\\nアクアかダクネスに付き合ってもらえばいいだろ？"

# めぐみん
# ふたりとも、今日は忙しいと言っていましたから。\n仕方なくカズマに頼んだのです。
247 = "ふたりとも、今日は忙しいと言っていましたから。\\n仕方なくカズマに頼んだのです。"

# カズマ
# 仕方なくかよ！\nここに放り出して帰ってもいいんだぞ？
264 = "仕方なくかよ！\\nここに放り出して帰ってもいいんだぞ？"

# めぐみん
# な、なんてことを言うのですか！\nこんな可憐な少女を捨てていくつもりですか！？
244 = "な、なんてことを言うのですか！\\nこんな可憐な少女を捨てていくつもりですか！？"

# カズマ
# だー！　わかったから抱きつくな！
240 = "だー！　わかったから抱きつくな！"

# めぐみん
# 抱きつくな？　抱きつきますよ！\nこんなところに捨てられるなんて、\nたまったものじゃありませんからね！
271 = "抱きつくな？　抱きつきますよ！\\nこんなところに捨てられるなんて、\\nたまったものじゃありませんからね！"

# カズマ
# てか、首が絞まってる！！\nやーめーろっ！！
243 = "てか、首が絞まってる！！\\nやーめーろっ！！"

# カズマ（Ｍ）
# display as カズマ
# （くそっ、こいつ魔法使いのくせに\n　あいかわらずすごい力を……って）
292 = "（くそっ、こいつ魔法使いのくせに\\n　あいかわらずすごい力を……って）"

# カズマ
# ん？
252 = "ん？"

# めぐみん
# カズマ？\nどうしたんですか？
257 = "カズマ？\\nどうしたんですか？"

# カズマ
# なんか、そこで光ってる物があるんだ。
246 = "なんか、そこで光ってる物があるんだ。"

# めぐみん
# 光ってる物？
266 = "光ってる物？"

# カズマ
# ほら、そこに。
249 = "ほら、そこに。"

