# root_c01.txt.scn

[info]
0 = ""

[characters]
275 = "カズマ（Ｍ）"
271 = "アクア"
268 = "めぐみん"
278 = "ダクネス"
272 = "カズマ"

[character_subs]
# 272 = "カズマ"

[script]
# lines: 55

# カズマ（Ｍ）
# display as カズマ
# （ふう……。\n　こうやって落ち着いた時間を過ごせるのって、\n　久しぶりだな）
324 = "（ふう……。\\n　こうやって落ち着いた時間を過ごせるのって、\\n　久しぶりだな）"

# カズマ（Ｍ）
# display as カズマ
# （今まで散々、俺達を振り回して\n　疎ましいとも感じていた指輪だったが――）
327 = "（今まで散々、俺達を振り回して\\n　疎ましいとも感じていた指輪だったが――）"

# カズマ（Ｍ）
# display as カズマ
# （いざ、なくなってしまうと\n　なぜだか寂しく感じてしまう）
322 = "（いざ、なくなってしまうと\\n　なぜだか寂しく感じてしまう）"

# カズマ（Ｍ）
# display as カズマ
# （本当は、俺はあの状況が\n　嫌いじゃなかったんじゃないか？）
328 = "（本当は、俺はあの状況が\\n　嫌いじゃなかったんじゃないか？）"

# カズマ（Ｍ）
# display as カズマ
# （あの指輪との別れは数日前だったのに、\n　もうずいぶん昔のように感じられるぜ）
321 = "（あの指輪との別れは数日前だったのに、\\n　もうずいぶん昔のように感じられるぜ）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、過去のことは過去のことだ。\n　今はこれからのことを――）
325 = "（まあ、過去のことは過去のことだ。\\n　今はこれからのことを――）"

# アクア
# カズマー、夕食ができたわよー！
274 = "カズマー、夕食ができたわよー！"

# めぐみん
# 早く来ないと全部食べちゃいますよー！
291 = "早く来ないと全部食べちゃいますよー！"

# ダクネス
# 今日はごちそうだぞ。
282 = "今日はごちそうだぞ。"

# カズマ（Ｍ）
# display as カズマ
# （はぁ……。\n　あいつらは悩みがなさそうでいいよな）
323 = "（はぁ……。\\n　あいつらは悩みがなさそうでいいよな）"

# アクア
# んぐんぐっ……ぷはぁっ！
270 = "んぐんぐっ……ぷはぁっ！"

# アクア
# はあ、お風呂上がりの１杯は最高だわ。\nやっぱり平和が１番よね。
264 = "はあ、お風呂上がりの１杯は最高だわ。\\nやっぱり平和が１番よね。"

# めぐみん
# ひどい目にあいましたが、\n結果としては丸く収まって良かったですよ。
265 = "ひどい目にあいましたが、\\n結果としては丸く収まって良かったですよ。"

# アクア
# それでそれで、ダクネス。\n討伐報酬ってどうなったの？
256 = "それでそれで、ダクネス。\\n討伐報酬ってどうなったの？"

# ダクネス
# ああ、まだ精査中らしいぞ。
247 = "ああ、まだ精査中らしいぞ。"

# アクア
# もう、何をのんびりやってるのかしら。\nこっちは首を長くして待ってるのに。
269 = "もう、何をのんびりやってるのかしら。\\nこっちは首を長くして待ってるのに。"

# ダクネス
# 突発的な事態に加え、\nあれだけの冒険者が絡んだことなんだ。
320 = "突発的な事態に加え、\\nあれだけの冒険者が絡んだことなんだ。"

# ダクネス
# 今は、経緯の把握でいっぱいいっぱいなのだろう。
280 = "今は、経緯の把握でいっぱいいっぱいなのだろう。"

# アクア
# ま、私の活躍さえ認めてくれれば\nそれでいいんですけど。
267 = "ま、私の活躍さえ認めてくれれば\\nそれでいいんですけど。"

# めぐみん
# そこが一番の問題だと思うのですが。
255 = "そこが一番の問題だと思うのですが。"

# ダクネス
# 最後はウィズが美味しいところを\n持っていったからな。
292 = "最後はウィズが美味しいところを\\n持っていったからな。"

# めぐみん
# 今やウィズは、街の英雄ですよ。
281 = "今やウィズは、街の英雄ですよ。"

# ダクネス
# それに比べ私たちは、\nその他大勢の扱いだ。
257 = "それに比べ私たちは、\\nその他大勢の扱いだ。"

# めぐみん
# これは報奨金の分配にも響くのでは？
251 = "これは報奨金の分配にも響くのでは？"

# アクア
# うう、大丈夫よ！\nギルドの人は私に偉かったねって言ってくれたし！
249 = "うう、大丈夫よ！\\nギルドの人は私に偉かったねって言ってくれたし！"

# アクア
# ねえ、カズマも聞いてたわよね？
262 = "ねえ、カズマも聞いてたわよね？"

# カズマ
# ああ……。
246 = "ああ……。"

# めぐみん
# カズマ？
276 = "カズマ？"

# カズマ
# うん……。
250 = "うん……。"

# ダクネス
# どうしたんだ、カズマ？\n食欲がないのか？
260 = "どうしたんだ、カズマ？\\n食欲がないのか？"

# カズマ
# ああ……。
# 246 = "ああ……。"

# アクア
# じゃあ、私がカズマの分のお肉、食べていい？
253 = "じゃあ、私がカズマの分のお肉、食べていい？"

# カズマ
# ああ……。
# 246 = "ああ……。"

# めぐみん
# 変ですね。\nいつもなら、絶対に死守して\n逆にアクアのお肉を奪い取るぐらいなのに。
286 = "変ですね。\\nいつもなら、絶対に死守して\\n逆にアクアのお肉を奪い取るぐらいなのに。"

# ダクネス
# （確かに、なんだか様子が変だ。\n　心ここにあらず、といった感じだな。\n　まさか、まだ指輪の影響が残っているのか？）
329 = "（確かに、なんだか様子が変だ。\\n　心ここにあらず、といった感じだな。\\n　まさか、まだ指輪の影響が残っているのか？）"

# カズマ
# はあ……。
263 = "はあ……。"

# アクア
# ねぇ、どうしちゃったのかしら？
261 = "ねぇ、どうしちゃったのかしら？"

# めぐみん
# さっきから返事が上の空ですよ。
252 = "さっきから返事が上の空ですよ。"

# ダクネス
# 何かまだ心配事があるのだろうか？
283 = "何かまだ心配事があるのだろうか？"

# アクア
# カズマがそんな繊細なわけないでしょ？\n多分、悪い物でも食べたのよ。
273 = "カズマがそんな繊細なわけないでしょ？\\n多分、悪い物でも食べたのよ。"

# めぐみん
# 拾い食いですか。\n確かにカズマならありそうですね。
290 = "拾い食いですか。\\n確かにカズマならありそうですね。"

# ダクネス
# いや、さすがにそれはないと思いたいが。
248 = "いや、さすがにそれはないと思いたいが。"

# カズマ
# ふぅ……。
266 = "ふぅ……。"

# アクア
# カズマ？\nあんたのお肉、全部もらうわよ？
277 = "カズマ？\\nあんたのお肉、全部もらうわよ？"

# カズマ
# うん……。
# 250 = "うん……。"

# めぐみん
# あ、私もいただきますね？
245 = "あ、私もいただきますね？"

# カズマ
# ああ……。
# 246 = "ああ……。"

# アクア
# 本当にいいのね？\n後で返せって言っても無駄よ？
293 = "本当にいいのね？\\n後で返せって言っても無駄よ？"

# めぐみん
# では、体調がよくないカズマに代わって、\n極上のお肉は私がいただきますね。
258 = "では、体調がよくないカズマに代わって、\\n極上のお肉は私がいただきますね。"

# ダクネス
# 待て、すべて取り上げるのは可哀想だろう。
289 = "待て、すべて取り上げるのは可哀想だろう。"

# アクア
# でも、こんないいお肉\n残したらもったいないじゃない。
259 = "でも、こんないいお肉\\n残したらもったいないじゃない。"

# めぐみん
# そうですよ。\nお肉だって、美味しく食べてくれる人に\n食べられたいはずです。
254 = "そうですよ。\\nお肉だって、美味しく食べてくれる人に\\n食べられたいはずです。"

# ダクネス
# 確かにそうかもしれないが……。
319 = "確かにそうかもしれないが……。"

# カズマ
# ふぅ……。
# 266 = "ふぅ……。"

# ダクネス
# （カズマ、いったいどうしたんだ。\n　お前らしくないぞ……）
326 = "（カズマ、いったいどうしたんだ。\\n　お前らしくないぞ……）"

