# root_d18.txt.scn

[info]
0 = ""

[characters]
206 = "カズマ"
208 = "クリス"
207 = "カズマ（Ｍ）"

[character_subs]
# 206 = "カズマ"

[script]
# lines: 50

# カズマ
# エリス様、ごめんなさい！\n少しだけこの場をお借りします、\n謝りますから、バチは与えないでください！
203 = "エリス様、ごめんなさい！\\n少しだけこの場をお借りします、\\n謝りますから、バチは与えないでください！"

# カズマ
# どうか俺……達を、魔の手からお守りください！\n外の奴らが気付きませんよーにっ！
193 = "どうか俺……達を、魔の手からお守りください！\\n外の奴らが気付きませんよーにっ！"

# クリス
# いきなり祈ったってムダだよ。\n普段、信仰してないくせに。\nカズマなんてバチが当たっちゃえばいいんだ。
174 = "いきなり祈ったってムダだよ。\\n普段、信仰してないくせに。\\nカズマなんてバチが当たっちゃえばいいんだ。"

# カズマ
# 何言ってるんだ。\nエリス様がそんなことするわけないだろ。
213 = "何言ってるんだ。\\nエリス様がそんなことするわけないだろ。"

# カズマ
# エリス様はな、どこかの駄女神と違って、\n可愛くて、親切で、人の痛みがわかる、\nとっても素敵な女神様なんだぞ。
204 = "エリス様はな、どこかの駄女神と違って、\\n可愛くて、親切で、人の痛みがわかる、\\nとっても素敵な女神様なんだぞ。"

# クリス
# えっ？
179 = "えっ？"

# カズマ
# そんな心の優しいエリス様が、\nこの程度でバチを与えるわけない。
190 = "そんな心の優しいエリス様が、\\nこの程度でバチを与えるわけない。"

# クリス
# へ、へえ、そうなんだ……。
200 = "へ、へえ、そうなんだ……。"

# カズマ
# なんで目を逸らすんだよ、そこ。
197 = "なんで目を逸らすんだよ、そこ。"

# クリス
# いや、キミって信仰心なんて\n持ってないと思ってたから……。
176 = "いや、キミって信仰心なんて\\n持ってないと思ってたから……。"

# クリス
# そういう風に、特定の神様を褒めるのが\nちょっとだけ意外だなって。
184 = "そういう風に、特定の神様を褒めるのが\\nちょっとだけ意外だなって。"

# カズマ（Ｍ）
# display as カズマ
# （褒めるって言うか、事実だからな！\n　なんて、ここでクリスに言っても\n　どんな妄想だって呆れられるのがオチか）
244 = "（褒めるって言うか、事実だからな！\\n　なんて、ここでクリスに言っても\\n　どんな妄想だって呆れられるのがオチか）"

# カズマ
# まあ、それはさておき、\nこれからどうするか考えないと。
201 = "まあ、それはさておき、\\nこれからどうするか考えないと。"

# クリス
# ひとまず、外の人達は\nあたしたちが教会へ逃げ込んだことに\n気付いていないみたいだね。
199 = "ひとまず、外の人達は\\nあたしたちが教会へ逃げ込んだことに\\n気付いていないみたいだね。"

# カズマ
# ああ。\nここで時間を稼ぐことはできそうだな。
171 = "ああ。\\nここで時間を稼ぐことはできそうだな。"

# クリス
# いや、でもさ、\nそれって、あたしたちにも\nここ以外もう逃げ場がないってことだよ？
175 = "いや、でもさ、\\nそれって、あたしたちにも\\nここ以外もう逃げ場がないってことだよ？"

# カズマ
# なんだよなぁ。\nこのままここで制限時間になってくれたら\nありがたいんだけど。
196 = "なんだよなぁ。\\nこのままここで制限時間になってくれたら\\nありがたいんだけど。"

# クリス
# 制限時間まで、後どれくらいかな？
215 = "制限時間まで、後どれくらいかな？"

# カズマ
# 正確な時間はわからないけど\n１時間あるかないかってところじゃないか？
219 = "正確な時間はわからないけど\\n１時間あるかないかってところじゃないか？"

# クリス
# うーん、微妙な時間だね。
178 = "うーん、微妙な時間だね。"

# クリス
# それくらいなら、\nここでやり過ごしたほうがいいのかも。
187 = "それくらいなら、\\nここでやり過ごしたほうがいいのかも。"

# カズマ
# 仮にここを出たとしても\n隠れられる場所が運よく見つかるとは\n限らないしな。
212 = "仮にここを出たとしても\\n隠れられる場所が運よく見つかるとは\\n限らないしな。"

# クリス
# はぁ……。\nどうしてこんなことになっちゃったのかなぁ。
198 = "はぁ……。\\nどうしてこんなことになっちゃったのかなぁ。"

# クリス
# あたしはただ、久しぶりの休日を\nのんびり楽しんでいただけなのに……。
172 = "あたしはただ、久しぶりの休日を\\nのんびり楽しんでいただけなのに……。"

# カズマ
# あ、そうだ！\n逃げることに夢中ですっかり忘れてたけど……。
169 = "あ、そうだ！\\n逃げることに夢中ですっかり忘れてたけど……。"

# カズマ
# こんな状況になっちまったのって\n俺達のせいじゃないんだよなぁ……。
181 = "こんな状況になっちまったのって\\n俺達のせいじゃないんだよなぁ……。"

# カズマ
# いわれのない借金を背負わされそうに\nなってるのも、街中の冒険者から\n追いかけられるはめになったのも……。
177 = "いわれのない借金を背負わされそうに\\nなってるのも、街中の冒険者から\\n追いかけられるはめになったのも……。"

# カズマ
# 全部アクアのせいじゃねーか！！
214 = "全部アクアのせいじゃねーか！！"

# カズマ（Ｍ）
# display as カズマ
# （くそっ！\n　考えれば考えるほど腹立つな！　あの駄女神！）
242 = "（くそっ！\\n　考えれば考えるほど腹立つな！　あの駄女神！）"

# カズマ（Ｍ）
# display as カズマ
# （なんとしてでも見つけだして\n　今までの仕返しをしてやるから\n　覚悟していやがれっ！）
243 = "（なんとしてでも見つけだして\\n　今までの仕返しをしてやるから\\n　覚悟していやがれっ！）"

# クリス
# そういえばアクアさん、どこにいるんだろう？\n今日１日、あちこち走り回ったけど\n１度も見かけなかったよね？
185 = "そういえばアクアさん、どこにいるんだろう？\\n今日１日、あちこち走り回ったけど\\n１度も見かけなかったよね？"

# カズマ（Ｍ）
# display as カズマ
# （……確かに妙だな。\n　あいつだって１００万エリスを\n　狙ってるだろうに、どこ行ったんだ？）
241 = "（……確かに妙だな。\\n　あいつだって１００万エリスを\\n　狙ってるだろうに、どこ行ったんだ？）"

# クリス
# 行きそうな場所に心当たりないの？
240 = "行きそうな場所に心当たりないの？"

# カズマ
# そう言われてもなぁ。\nいつも一緒にいるわけじゃないし。
186 = "そう言われてもなぁ。\\nいつも一緒にいるわけじゃないし。"

# クリス
# でも、街中にいるなら\nどこかですれ違っても\nおかしくなさそうなものだけどね。
191 = "でも、街中にいるなら\\nどこかですれ違っても\\nおかしくなさそうなものだけどね。"

# クリス
# あ、もしかしてクエストに出かけたとか？
170 = "あ、もしかしてクエストに出かけたとか？"

# カズマ
# それはない、絶対にない。\nだって、あいつ１人じゃ何もできないぜ。
189 = "それはない、絶対にない。\\nだって、あいつ１人じゃ何もできないぜ。"

# クリス
# でもアクアさんって、\nアークプリーストだよね？\nしかも、高ステータスなんでしょ？
192 = "でもアクアさんって、\\nアークプリーストだよね？\\nしかも、高ステータスなんでしょ？"

# クリス
# それだけの実力があるなら\nヒーラーとしてだけでなく、\nサポーターとしても引く手数多なんじゃない？
188 = "それだけの実力があるなら\\nヒーラーとしてだけでなく、\\nサポーターとしても引く手数多なんじゃない？"

# カズマ
# あのなクリス。\nお前はダクネスを見ても同じことが言えるか？\nあいつだって、腐ってもクルセイダーだぜ？
173 = "あのなクリス。\\nお前はダクネスを見ても同じことが言えるか？\\nあいつだって、腐ってもクルセイダーだぜ？"

# クリス
# しっ！　静かに。
182 = "しっ！　静かに。"

# カズマ
# な、なんだ？\nどうしたクリス？
195 = "な、なんだ？\\nどうしたクリス？"

# クリス
# 少し離れた場所から、\n複数の気配が近づいて来てる。\n誰かが教会の側まで来てるみたい。
217 = "少し離れた場所から、\\n複数の気配が近づいて来てる。\\n誰かが教会の側まで来てるみたい。"

# クリス
# これは多分、\nあたしたちを捜してる冒険者だろうね。
180 = "これは多分、\\nあたしたちを捜してる冒険者だろうね。"

# カズマ
# やっぱり気付かれたか。\nまぁ、この辺りじゃここ以外隠れる場所もないし、\nバカじゃなきゃわかるよな。
202 = "やっぱり気付かれたか。\\nまぁ、この辺りじゃここ以外隠れる場所もないし、\\nバカじゃなきゃわかるよな。"

# クリス
# どうする？
194 = "どうする？"

# カズマ
# クリス、この教会に人の気配はあるか？
209 = "クリス、この教会に人の気配はあるか？"

# クリス
# 中ってこと？\nううん、今は誰もいないみたいだよ。
211 = "中ってこと？\\nううん、今は誰もいないみたいだよ。"

# カズマ
# じゃあ、奥へ移動しよう。\nこれだけ大きな建物なら隠れる場所があるかも\nしれないし、どこかから逃げられるかもしれない。
183 = "じゃあ、奥へ移動しよう。\\nこれだけ大きな建物なら隠れる場所があるかも\\nしれないし、どこかから逃げられるかもしれない。"

# クリス
# オッケー、わかった。\nそれじゃ、大きな音たてないように\n気をつけてね、カズマ。
205 = "オッケー、わかった。\\nそれじゃ、大きな音たてないように\\n気をつけてね、カズマ。"

