# root_d15.txt.scn

[info]
0 = ""

[characters]
287 = "カズマ（Ｍ）"
285 = "カズマ"
289 = "クリス"
306 = "盗賊風の男冒険者"

[character_subs]
# 285 = "カズマ"
305 = "盗賊冒険者"

[script]
# lines: 72

# カズマ（Ｍ）
# display as カズマ
# （はあっ、はあっ、なんとか逃げ切れたな）
321 = "（はあっ、はあっ、なんとか逃げ切れたな）"

# カズマ
# クリス、大丈夫か？
290 = "クリス、大丈夫か？"

# クリス
# う、ううう、うう……。
240 = "う、ううう、うう……。"

# カズマ
# あれ、どうかしたのか？\nなんだか顔が赤いぞ。
235 = "あれ、どうかしたのか？\\nなんだか顔が赤いぞ。"

# クリス
# う、くう、ううううううう～……。
241 = "う、くう、ううううううう～……。"

# カズマ
# そういえば、この手にある生暖かい感触は？\nいったい俺は何を盗んだんだろう？
254 = "そういえば、この手にある生暖かい感触は？\\nいったい俺は何を盗んだんだろう？"

# クリス
# いや！　見ちゃダメ！！
239 = "いや！　見ちゃダメ！！"

# カズマ
# ぬお、パンツ！
274 = "ぬお、パンツ！"

# カズマ
# これは見間違えることのない、\n何度も拝ませて貰ってるクリスさんの、パンツ！
252 = "これは見間違えることのない、\\n何度も拝ませて貰ってるクリスさんの、パンツ！"

# クリス
# ちょちょちょ、その言い方は変な誤解を生むから！
264 = "ちょちょちょ、その言い方は変な誤解を生むから！"

# カズマ
# んん～？　誤解ってどんな誤解？
284 = "んん～？　誤解ってどんな誤解？"

# クリス
# もう、いいからパンツ返して！\nスケベ！　変態！　カズマぁ！
280 = "もう、いいからパンツ返して！\\nスケベ！　変態！　カズマぁ！"

# カズマ
# お、おう、最後のカズマってなんだ、カズマって。
249 = "お、おう、最後のカズマってなんだ、カズマって。"

# クリス
# とにかく返してよ、パンツ！\nあたしのパンツー！
270 = "とにかく返してよ、パンツ！\\nあたしのパンツー！"

# カズマ
# とりあえず落ち着けって。
271 = "とりあえず落ち着けって。"

# クリス
# パンツを盗まれて、\n落ち着いていられるわけないでしょ！？
291 = "パンツを盗まれて、\\n落ち着いていられるわけないでしょ！？"

# カズマ
# いやでもさ、お前さっきからパンツパンツ言って、\n女の子としてどうかと思うぞ？
238 = "いやでもさ、お前さっきからパンツパンツ言って、\\n女の子としてどうかと思うぞ？"

# クリス
# むっか！
279 = "むっか！"

# カズマ
# お、おう、なんだ？\nや、やるのか！
248 = "お、おう、なんだ？\\nや、やるのか！"

# クリス
# もういい、捕まる。
281 = "もういい、捕まる。"

# カズマ
# は？
277 = "は？"

# クリス
# カズマに協力する理由がなくなったよ。\n逃げるのを止めて、誰かに捕まる。
286 = "カズマに協力する理由がなくなったよ。\\n逃げるのを止めて、誰かに捕まる。"

# カズマ
# いっ！？
237 = "いっ！？"

# クリス
# だって、あたしは捕まったって\n痛くもかゆくもないからね。\n困るのはキミだけだし。
260 = "だって、あたしは捕まったって\\n痛くもかゆくもないからね。\\n困るのはキミだけだし。"

# カズマ（Ｍ）
# display as カズマ
# （うっ！\n　まいったな、本気で怒らせちまったか）
319 = "（うっ！\\n　まいったな、本気で怒らせちまったか）"

# カズマ（Ｍ）
# display as カズマ
# （なんとかクリスを宥めないと）
320 = "（なんとかクリスを宥めないと）"

# カズマ
# とても、可愛いパンツですね。
269 = "とても、可愛いパンツですね。"

# クリス
# ちょ、ちょっと！\nいきなり何言い出すのさ！？
262 = "ちょ、ちょっと！\\nいきなり何言い出すのさ！？"

# カズマ
# 薄いブルー。\nクリスの奥底にある清楚さを\nあらわしていて、素敵。
316 = "薄いブルー。\\nクリスの奥底にある清楚さを\\nあらわしていて、素敵。"

# クリス
# ひっ。
278 = "ひっ。"

# カズマ
# ワンポイントのリボン。\nクリスの可愛らしさを\nさりげなく表現していて、素敵。
293 = "ワンポイントのリボン。\\nクリスの可愛らしさを\\nさりげなく表現していて、素敵。"

# クリス
# ちょっ！
266 = "ちょっ！"

# カズマ
# うん、いい！\n何度見ても、クリスのパンツは素晴らしい！
246 = "うん、いい！\\n何度見ても、クリスのパンツは素晴らしい！"

# クリス
# 怒るよ？
299 = "怒るよ？"

# カズマ
# え？　どうして？
247 = "え？　どうして？"

# クリス
# パンツを評されて喜ぶ女の子が\nこの世界にいると思ってるわけ！？
292 = "パンツを評されて喜ぶ女の子が\\nこの世界にいると思ってるわけ！？"

# カズマ
# 思ってるよ、ダクネスとか。
300 = "思ってるよ、ダクネスとか。"

# クリス
# うぐ……。
243 = "うぐ……。"

# カズマ（Ｍ）
# display as カズマ
# （ふふ、ぐうの音も出まい）
322 = "（ふふ、ぐうの音も出まい）"

# カズマ
# わざとじゃないんだよ、信じてくれ！\nこの俺の、純粋な眼差しを！！
282 = "わざとじゃないんだよ、信じてくれ！\\nこの俺の、純粋な眼差しを！！"

# クリス
# 信じられない。
295 = "信じられない。"

# カズマ
# そんなバッサリ否定しなくてもいいんじゃね！？
258 = "そんなバッサリ否定しなくてもいいんじゃね！？"

# クリス
# だって、キミには前科が山ほどあるもの。\nなのに信用しろって言われたって無理だよ。
261 = "だって、キミには前科が山ほどあるもの。\\nなのに信用しろって言われたって無理だよ。"

# クリス
# だいたい、あたしの、\nパンツ盗んだのだって、本当に偶然なの？
259 = "だいたい、あたしの、\\nパンツ盗んだのだって、本当に偶然なの？"

# カズマ
# 狙って盗めるわけないだろ？\nスティールで盗む物はランダムって\nクリスもよく知ってるはずだ。
304 = "狙って盗めるわけないだろ？\\nスティールで盗む物はランダムって\\nクリスもよく知ってるはずだ。"

# クリス
# でも、人の大事な物を\nずーっと握りしめてる時点で、\n信頼とかあるわけないよね。
267 = "でも、人の大事な物を\\nずーっと握りしめてる時点で、\\n信頼とかあるわけないよね。"

# クリス
# そもそも、それが何かわかってたら\nそんな風にしてられないよね？\nもしかして、最初から狙ってたんじゃない？
256 = "そもそも、それが何かわかってたら\\nそんな風にしてられないよね？\\nもしかして、最初から狙ってたんじゃない？"

# カズマ
# 待て待て！\n本当に盗んだ物がクリスのパンツだって\n気がついてなかっただけなんだ！
298 = "待て待て！\\n本当に盗んだ物がクリスのパンツだって\\n気がついてなかっただけなんだ！"

# カズマ
# 確かに、ほんのり人肌でー、いい匂いがしてー、\n柔らかくてー、気持ちいいなと思ったけど――
315 = "確かに、ほんのり人肌でー、いい匂いがしてー、\\n柔らかくてー、気持ちいいなと思ったけど――"

# カズマ
# それがまさかパンツだとは\n普通、思わないだろ！
257 = "それがまさかパンツだとは\\n普通、思わないだろ！"

# クリス
# ちょ、ちょっと！\nそんな大声で何度もパンツって叫ばないでよ！\nキミには恥じらいってものがないの！？
263 = "ちょ、ちょっと！\\nそんな大声で何度もパンツって叫ばないでよ！\\nキミには恥じらいってものがないの！？"

# カズマ
# 誰も聞いてないから大丈夫だって。
317 = "誰も聞いてないから大丈夫だって。"

# クリス
# そういう問題じゃないったらぁ！
253 = "そういう問題じゃないったらぁ！"

# カズマ
# そうか？
255 = "そうか？"

# カズマ
# 新しいのを買って返すから！\nそれで機嫌直せよ、なっ？
302 = "新しいのを買って返すから！\\nそれで機嫌直せよ、なっ？"

# クリス
# …………。
232 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （あ、あれ？\n　なんだこのクリスの絶対零度な眼差しは。\n　俺、何かまずいこと言ったか？）
318 = "（あ、あれ？\\n　なんだこのクリスの絶対零度な眼差しは。\\n　俺、何かまずいこと言ったか？）"

# クリス
# ねえ、カズマ。\nそれは本気で言ってるのかな？
275 = "ねえ、カズマ。\\nそれは本気で言ってるのかな？"

# カズマ
# なんだよ、パンツだけじゃ足りないのか？\n意外に強欲だな、クリスって。
273 = "なんだよ、パンツだけじゃ足りないのか？\\n意外に強欲だな、クリスって。"

# クリス
# うわぁ……。
244 = "うわぁ……。"

# カズマ
# うわぁってなんだよ、うわぁって。\n人の厚意に対してそれはないだろ。
245 = "うわぁってなんだよ、うわぁって。\\n人の厚意に対してそれはないだろ。"

# クリス
# あのねぇ、何か誤解してるみたいだけど、\n普通さ、彼女でもない女の子に対して\nパンツを買ってあげるなんてしないからね。
234 = "あのねぇ、何か誤解してるみたいだけど、\\n普通さ、彼女でもない女の子に対して\\nパンツを買ってあげるなんてしないからね。"

# クリス
# キミのやってること、それ、セクハラだから。\n訴えられたら負けるから。\nわかってる？
288 = "キミのやってること、それ、セクハラだから。\\n訴えられたら負けるから。\\nわかってる？"

# クリス
# いくら女の子と付き合ったことないからって、\n現実と妄想をごっちゃにしちゃダメだよ。
236 = "いくら女の子と付き合ったことないからって、\\n現実と妄想をごっちゃにしちゃダメだよ。"

# カズマ
# な、な、なんの根拠があって\nそんなことを言うのかね、クリスさん？
272 = "な、な、なんの根拠があって\\nそんなことを言うのかね、クリスさん？"

# クリス
# 根拠はないよ。\nでも、カズマだしそうかなーって。
303 = "根拠はないよ。\\nでも、カズマだしそうかなーって。"

# カズマ
# うぅ、泣きたい！
242 = "うぅ、泣きたい！"

# クリス
# はあ……。\nとにかくパンツ、返してよ。
276 = "はあ……。\\nとにかくパンツ、返してよ。"

# カズマ
# ああ、そうだな。
233 = "ああ、そうだな。"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# おい、いたぞ！　あそこだっ！
250 = "おい、いたぞ！　あそこだっ！"

# カズマ
# げげっ！\nもう追いついてきたのかよ、逃げるぞクリス！
251 = "げげっ！\\nもう追いついてきたのかよ、逃げるぞクリス！"

# クリス
# ちょっとパンツは！？
265 = "ちょっとパンツは！？"

[selections]
268 = "とても、可愛いパンツですね"
283 = "わざとじゃないんだよ！"
301 = "新しいのを買って返すから！"
