# root_b18.txt.scn

[info]
0 = ""

[characters]
266 = "カズマ"
257 = "めぐみん"
269 = "カズマ（Ｍ）"

[character_subs]
# 266 = "カズマ"

[script]
# lines: 75

# カズマ
# ……けどさ、結婚式って\n具体的に何をすればいいんだ？\n初めてだからわかんねーぞ？
215 = "……けどさ、結婚式って\\n具体的に何をすればいいんだ？\\n初めてだからわかんねーぞ？"

# めぐみん
# 私だって初めてなんですから\nわかりませんよ……。
320 = "私だって初めてなんですから\\nわかりませんよ……。"

# めぐみん
# でも、こういうときは\n男性が色々とエスコートするものでしょう？
244 = "でも、こういうときは\\n男性が色々とエスコートするものでしょう？"

# カズマ
# お、おう、そうだよな。
228 = "お、おう、そうだよな。"

# カズマ（Ｍ）
# display as カズマ
# （結婚式ってどうやるんだっけ？\n　ドラマや映画で何回か見ているはずだ。\n　それを思いだせ……）
329 = "（結婚式ってどうやるんだっけ？\\n　ドラマや映画で何回か見ているはずだ。\\n　それを思いだせ……）"

# カズマ
# あ、そうだ！\n新郎は先に祭壇の前で花嫁を待ってるんだ。
218 = "あ、そうだ！\\n新郎は先に祭壇の前で花嫁を待ってるんだ。"

# カズマ
# というわけで、俺はここな。\n次にめぐみんは、ゆっくりと通路を歩いて\n俺の横へ来てくれ。
245 = "というわけで、俺はここな。\\n次にめぐみんは、ゆっくりと通路を歩いて\\n俺の横へ来てくれ。"

# めぐみん
# あ、ちょっと待ってください。
219 = "あ、ちょっと待ってください。"

# めぐみん
# 思い出しましたが、花嫁は\n父親と一緒に歩くものではないのですか？
282 = "思い出しましたが、花嫁は\\n父親と一緒に歩くものではないのですか？"

# カズマ
# あー、言われてみればそんな気がするな。\nだけど、いないものは仕方がないだろ。
222 = "あー、言われてみればそんな気がするな。\\nだけど、いないものは仕方がないだろ。"

# めぐみん
# １人でここを歩くというのは、\nかなり恥ずかしいのですが……。
331 = "１人でここを歩くというのは、\\nかなり恥ずかしいのですが……。"

# カズマ
# ここで足踏みしてたら\nいつまで経っても式が終わらないぞ？
231 = "ここで足踏みしてたら\\nいつまで経っても式が終わらないぞ？"

# めぐみん
# わかっていますけど、\nいざこの場に立つと緊張が……。
263 = "わかっていますけど、\\nいざこの場に立つと緊張が……。"

# カズマ
# そうか。\nじゃあ、もう急かしたりしないから\n自分のタイミングでやってくれ。
236 = "そうか。\\nじゃあ、もう急かしたりしないから\\n自分のタイミングでやってくれ。"

# めぐみん
# スー……ハー……スー……ハー……。
270 = "スー……ハー……スー……ハー……。"

# めぐみん
# よし！\n……では、いきます！
260 = "よし！\\n……では、いきます！"

# カズマ
# ああ、待ってるよ。\n花嫁さん。
221 = "ああ、待ってるよ。\\n花嫁さん。"

# めぐみん
# そそ、そ、その言い方は禁止！\n禁止です、背中がむずがゆくなります！
238 = "そそ、そ、その言い方は禁止！\\n禁止です、背中がむずがゆくなります！"

# カズマ（Ｍ）
# display as カズマ
# （雲に隠れてた月が出てきたな。\n　これで少しは明るく――）
330 = "（雲に隠れてた月が出てきたな。\\n　これで少しは明るく――）"

# カズマ
# …………。
214 = "…………。"

# めぐみん
# どうしたんです？\n人のことをボーッと見つめたりして？\nまだ寝ぼけているのですか？
248 = "どうしたんです？\\n人のことをボーッと見つめたりして？\\nまだ寝ぼけているのですか？"

# カズマ
# わ、悪い、どうやらそうみたいだ。\n寝てるところを叩き起こされたからな。
261 = "わ、悪い、どうやらそうみたいだ。\\n寝てるところを叩き起こされたからな。"

# めぐみん
# ……仕方ないじゃないですか。\n目が覚めたらこんな格好をしていたのですよ？
217 = "……仕方ないじゃないですか。\\n目が覚めたらこんな格好をしていたのですよ？"

# カズマ
# わかってるよ。\nそりゃ誰だって驚くよな。
264 = "わかってるよ。\\nそりゃ誰だって驚くよな。"

# めぐみん
# 起こしてしまったことは\n申し訳ないと思っています。\nですが、集中してください。
322 = "起こしてしまったことは\\n申し訳ないと思っています。\\nですが、集中してください。"

# カズマ
# お、おう。
229 = "お、おう。"

# カズマ（Ｍ）
# display as カズマ
# （……言えない）
324 = "（……言えない）"

# カズマ（Ｍ）
# display as カズマ
# （ステンドガラスから差す月明かりに\n　照らされためぐみんが綺麗で見入ってた、\n　なんて、言えるわけがない）
328 = "（ステンドガラスから差す月明かりに\\n　照らされためぐみんが綺麗で見入ってた、\\n　なんて、言えるわけがない）"

# カズマ（Ｍ）
# display as カズマ
# （でも、本当に綺麗だ。\n　馬子にも衣装とはよく言ったもんだなぁ）
326 = "（でも、本当に綺麗だ。\\n　馬子にも衣装とはよく言ったもんだなぁ）"

# めぐみん
# なんです？\n今度はジロジロと……\n恥ずかしいからあまり見ないでください。
252 = "なんです？\\n今度はジロジロと……\\n恥ずかしいからあまり見ないでください。"

# カズマ
# めぐみんも、その気になればできるんだな。
258 = "めぐみんも、その気になればできるんだな。"

# めぐみん
# はい？\nなにを訳のわからないことを言ってるんです？
254 = "はい？\\nなにを訳のわからないことを言ってるんです？"

# めぐみん
# ところで、カズマ？\n隣に来ましたが、次はどうするんです？
246 = "ところで、カズマ？\\n隣に来ましたが、次はどうするんです？"

# カズマ
# え？\nああ、その……\nまずは、ドレスが脱げないかどうか試してみろよ。
227 = "え？\\nああ、その……\\nまずは、ドレスが脱げないかどうか試してみろよ。"

# めぐみん
# では、少し後ろを向いていてください。
243 = "では、少し後ろを向いていてください。"

# カズマ
# はいはい、わかりましたよ。
253 = "はいはい、わかりましたよ。"

# めぐみん
# ん……。
265 = "ん……。"

# カズマ
# どうだ、脱げそうか？
249 = "どうだ、脱げそうか？"

# めぐみん
# ダメです。\n相変わらず、肌に張り付いたみたいになってます。
271 = "ダメです。\\n相変わらず、肌に張り付いたみたいになってます。"

# カズマ（Ｍ）
# display as カズマ
# （そうか、やっぱりバージンロードを\n　歩くくらいじゃ、呪いは解けないか）
325 = "（そうか、やっぱりバージンロードを\\n　歩くくらいじゃ、呪いは解けないか）"

# めぐみん
# これは、式をもっと\n進めるしかないということですか。\nそれで、次は？
233 = "これは、式をもっと\\n進めるしかないということですか。\\nそれで、次は？"

# カズマ
# うーん……。\n多分、神前で誓いの言葉を交わす、だったような。
224 = "うーん……。\\n多分、神前で誓いの言葉を交わす、だったような。"

# めぐみん
# 誓うって、なにを誓うんですか？
321 = "誓うって、なにを誓うんですか？"

# カズマ
# そりゃ当然、\nお互いの、お互いへの、愛について。
239 = "そりゃ当然、\\nお互いの、お互いへの、愛について。"

# めぐみん
# あ、愛ですか！？\nそそそ、そ、そんな、\nないものを誓えるわけないですよ！？
220 = "あ、愛ですか！？\\nそそそ、そ、そんな、\\nないものを誓えるわけないですよ！？"

# カズマ
# ここまできてごねるなよ。\nフリだからなくてもいいだろ！
232 = "ここまできてごねるなよ。\\nフリだからなくてもいいだろ！"

# めぐみん
# で、ですが、誓いなんて、\nどんなことを言えばいいのか見当もつきません。
240 = "で、ですが、誓いなんて、\\nどんなことを言えばいいのか見当もつきません。"

# カズマ
# 俺だって詳しくはわからないけど、\nとりあえず、お互いのいいところとか\n言えばいいんじゃないか？
275 = "俺だって詳しくはわからないけど、\\nとりあえず、お互いのいいところとか\\n言えばいいんじゃないか？"

# めぐみん
# カズマの……いいところ？
267 = "カズマの……いいところ？"

# カズマ
# そこで考え込むなよ！\nへこむだろ！？
237 = "そこで考え込むなよ！\\nへこむだろ！？"

# めぐみん
# では、まずはお手本を見せてください。
242 = "では、まずはお手本を見せてください。"

# カズマ
# え……？\nええと、うーん……\nめぐみんのいいところなぁ……。
225 = "え……？\\nええと、うーん……\\nめぐみんのいいところなぁ……。"

# めぐみん
# もしかして、ないとか言わないですよね？
259 = "もしかして、ないとか言わないですよね？"

# カズマ
# 迷惑ばかりかけてくれて、\n正直、嫌になることが多いが――
323 = "迷惑ばかりかけてくれて、\\n正直、嫌になることが多いが――"

# めぐみん
# なんですか、それ？\nどこが愛なんですか？
251 = "なんですか、それ？\\nどこが愛なんですか？"

# カズマ
# 待て、まだ途中だ。\n文句は最後まで聞いてからにしろ。
281 = "待て、まだ途中だ。\\n文句は最後まで聞いてからにしろ。"

# カズマ
# えーと……\nだけど、爆裂魔法にかける情熱は\n凄いって、呆れる反面、感心もしてるよ。
226 = "えーと……\\nだけど、爆裂魔法にかける情熱は\\n凄いって、呆れる反面、感心もしてるよ。"

# カズマ
# 周りの言葉に惑わされることなく\n自分の好きなことを貫き通す姿勢は、\n少しいいかなって……。
278 = "周りの言葉に惑わされることなく\\n自分の好きなことを貫き通す姿勢は、\\n少しいいかなって……。"

# カズマ
# まあ、そんな風に思えなくもない！\n以上！
255 = "まあ、そんな風に思えなくもない！\\n以上！"

# めぐみん
# そ、そこまで言われては\n爆裂道を極めねばなりませんね！
234 = "そ、そこまで言われては\\n爆裂道を極めねばなりませんね！"

# カズマ
# いや、ほどほどに頼むぜ？\nじゃあ、めぐみんの番だな。
223 = "いや、ほどほどに頼むぜ？\\nじゃあ、めぐみんの番だな。"

# めぐみん
# くっ……。\nわ、わかりましたよ。
230 = "くっ……。\\nわ、わかりましたよ。"

# めぐみん
# カズマはスケベでだらしがなく、\nドン引きすることも正直少なくありません。
268 = "カズマはスケベでだらしがなく、\\nドン引きすることも正直少なくありません。"

# カズマ
# 悪かったな。
283 = "悪かったな。"

# めぐみん
# ですが、意外と機転がきくというか、\n頼りになるというか……。
241 = "ですが、意外と機転がきくというか、\\n頼りになるというか……。"

# めぐみん
# 爆裂魔法の練習にも付き合ってくれますし、\n面倒見もいいかなーと……。
285 = "爆裂魔法の練習にも付き合ってくれますし、\\n面倒見もいいかなーと……。"

# めぐみん
# なんだかんだ言いながらも\n助けられていることに……\n感謝してはいるんですよ？
250 = "なんだかんだ言いながらも\\n助けられていることに……\\n感謝してはいるんですよ？"

# めぐみん
# わ、私からは以上ですっ！
262 = "わ、私からは以上ですっ！"

# カズマ
# お、おう。
# 229 = "お、おう。"

# カズマ（Ｍ）
# display as カズマ
# （なんか、こうして改めて言われると\n　照れくさいな）
327 = "（なんか、こうして改めて言われると\\n　照れくさいな）"

# カズマ
# そ、それで、ドレスの方はどうだ？
235 = "そ、それで、ドレスの方はどうだ？"

# めぐみん
# ……ダメですね。\n変化が感じられません。
216 = "……ダメですね。\\n変化が感じられません。"

# カズマ
# まだダメか。\nあと残されていることといったら\n指輪の交換ぐらいか？
256 = "まだダメか。\\nあと残されていることといったら\\n指輪の交換ぐらいか？"

# めぐみん
# 指輪？\nそんな物用意していませんよ？
284 = "指輪？\\nそんな物用意していませんよ？"

# カズマ
# とりあえず探してみよう。\nもしかしたら、代わりに使える物が\nあるかもしれない。
247 = "とりあえず探してみよう。\\nもしかしたら、代わりに使える物が\\nあるかもしれない。"

