# root_e07.txt.scn

[info]
0 = ""

[characters]
243 = "アクア"
246 = "ダクネス"
239 = "ゆんゆん"
245 = "カズマ"
234 = "めぐみん"

[character_subs]

[script]
# lines: 50

# アクア
# いただきまーす！
207 = "いただきまーす！"

# ダクネス
# さて、しっかり食べて一日に備えなくてはな。\nゆんゆんも、遠慮することはないぞ。\nたくさん食べてくれ。
213 = "さて、しっかり食べて一日に備えなくてはな。\\nゆんゆんも、遠慮することはないぞ。\\nたくさん食べてくれ。"

# ゆんゆん
# は、はい。\nありがとうございます。
226 = "は、はい。\\nありがとうございます。"

# カズマ
# なあ、みんな。\n食べながらでいいから\n聞いて欲しいことがあるんだ。
222 = "なあ、みんな。\\n食べながらでいいから\\n聞いて欲しいことがあるんだ。"

# めぐみん
# なんですか？\nおかずならあげませんよ。
225 = "なんですか？\\nおかずならあげませんよ。"

# カズマ
# いらんわい！
208 = "いらんわい！"

# アクア
# お金なら貸さないわよ？
212 = "お金なら貸さないわよ？"

# カズマ
# お前をあてにするほど落ちぶれてねえよ！
211 = "お前をあてにするほど落ちぶれてねえよ！"

# アクア
# 落ちぶれ！？\nちょっと今の言葉、愚弄に値するんですけど。
285 = "落ちぶれ！？\\nちょっと今の言葉、愚弄に値するんですけど。"

# カズマ
# だったらなんだっていうんだよ、\n宴会芸の女神さん。
219 = "だったらなんだっていうんだよ、\\n宴会芸の女神さん。"

# アクア
# 水の女神だって言ってるでしょ！
254 = "水の女神だって言ってるでしょ！"

# ダクネス
# おいカズマ、話が脱線しているぞ。
209 = "おいカズマ、話が脱線しているぞ。"

# カズマ
# おっと、すまん。
210 = "おっと、すまん。"

# カズマ
# で、だな？\n実はゆんゆんが、\nしばらくこの屋敷で暮らしたいそうだ。
220 = "で、だな？\\n実はゆんゆんが、\\nしばらくこの屋敷で暮らしたいそうだ。"

# めぐみん
# はあ？\nゆんゆんがですか？
227 = "はあ？\\nゆんゆんがですか？"

# ダクネス
# 何かと思えばそんなことか。\n私は別に構わないぞ？
248 = "何かと思えばそんなことか。\\n私は別に構わないぞ？"

# ゆんゆん
# い、いいんですか、そんな簡単に！？
205 = "い、いいんですか、そんな簡単に！？"

# ダクネス
# めぐみんの友人なんだ、\n歓迎するに決まっているさ。
235 = "めぐみんの友人なんだ、\\n歓迎するに決まっているさ。"

# ダクネス
# それに、あの控えめなゆんゆんが\nそんな頼み事をするなんて、\nよっぽどの事情があるのだろう？
218 = "それに、あの控えめなゆんゆんが\\nそんな頼み事をするなんて、\\nよっぽどの事情があるのだろう？"

# ダクネス
# 詳しくは聞かないが、\n何か手伝えることがあるのなら\n遠慮なく言ってくれ。
286 = "詳しくは聞かないが、\\n何か手伝えることがあるのなら\\n遠慮なく言ってくれ。"

# ゆんゆん
# は、はい。\nありがとうございます。
# 226 = "は、はい。\\nありがとうございます。"

# めぐみん
# 私は反対ですよ。\n一緒に暮らしたいなど、\n急な話にも程があります。
284 = "私は反対ですよ。\\n一緒に暮らしたいなど、\\n急な話にも程があります。"

# ゆんゆん
# や、やっぱりそうだよね。\n突然こんなこと迷惑だよね。
238 = "や、やっぱりそうだよね。\\n突然こんなこと迷惑だよね。"

# めぐみん
# イラっ、どうしてそこで引き下がりますかね。
244 = "イラっ、どうしてそこで引き下がりますかね。"

# カズマ
# まあまあ、めぐみんの言うことももっともだけど、\n俺たちは知らない仲ってわけじゃないだろ。
230 = "まあまあ、めぐみんの言うことももっともだけど、\\n俺たちは知らない仲ってわけじゃないだろ。"

# ダクネス
# 受け入れる理由はすぐに見つかるが、\n断る理由を探すのは難しいな。
250 = "受け入れる理由はすぐに見つかるが、\\n断る理由を探すのは難しいな。"

# めぐみん
# わかりました、わかりましたよ！
241 = "わかりました、わかりましたよ！"

# ゆんゆん
# じゃあいいの？　めぐみん？
214 = "じゃあいいの？　めぐみん？"

# めぐみん
# いえ、まだです。\n決めるのは、ここで暮らしたいと思った\n理由を聞いてからです。
206 = "いえ、まだです。\\n決めるのは、ここで暮らしたいと思った\\n理由を聞いてからです。"

# ゆんゆん
# もちろん、めぐみんに勝つためよ！\n近くであなたのことを観察するの。\nどうすれば勝てるか、その方法を見つけるために！
237 = "もちろん、めぐみんに勝つためよ！\\n近くであなたのことを観察するの。\\nどうすれば勝てるか、その方法を見つけるために！"

# めぐみん
# はあ？　そんな理由なんですか？
228 = "はあ？　そんな理由なんですか？"

# ゆんゆん
# 私にとってはすごく重要なのよ！
282 = "私にとってはすごく重要なのよ！"

# めぐみん
# まったく無駄なことを。\nそんなことをしても私に勝てるわけないのに。
232 = "まったく無駄なことを。\\nそんなことをしても私に勝てるわけないのに。"

# ゆんゆん
# なら、私が側にいても問題ないじゃない。\nそれとも本当は怖いんじゃないの？
223 = "なら、私が側にいても問題ないじゃない。\\nそれとも本当は怖いんじゃないの？"

# めぐみん
# ……怖い？\nこの私が、ゆんゆんを恐れていると？
204 = "……怖い？\\nこの私が、ゆんゆんを恐れていると？"

# ゆんゆん
# もし弱点を知られたらどうしよう、\n負けたらどうしようって不安なのね。\nそれなら、そう言ってもいいのよ？
236 = "もし弱点を知られたらどうしよう、\\n負けたらどうしようって不安なのね。\\nそれなら、そう言ってもいいのよ？"

# めぐみん
# 私に弱点などありませんよ。
283 = "私に弱点などありませんよ。"

# ゆんゆん
# なら私がここにいても問題ないよね？
224 = "なら私がここにいても問題ないよね？"

# めぐみん
# ……今日はやけに絡んできますね。
203 = "……今日はやけに絡んできますね。"

# ゆんゆん
# そう？\nめぐみんこそ、やけに必死にじゃない？
215 = "そう？\\nめぐみんこそ、やけに必死にじゃない？"

# めぐみん
# むむむむ……。\nほ、本気で私に勝てると思っているのですか？
233 = "むむむむ……。\\nほ、本気で私に勝てると思っているのですか？"

# ゆんゆん
# 思ってるわ！\n今度こそ確実に勝ってみせる！
253 = "思ってるわ！\\n今度こそ確実に勝ってみせる！"

# めぐみん
# とんだ思い上がりですね。\nいいでしょう、そこまで言うなら\n勝手にしてください。
221 = "とんだ思い上がりですね。\\nいいでしょう、そこまで言うなら\\n勝手にしてください。"

# めぐみん
# そして知るがいい！\n己がどれほど浅はかだったのかを！
216 = "そして知るがいい！\\n己がどれほど浅はかだったのかを！"

# ゆんゆん
# その言葉、忘れないでね！
217 = "その言葉、忘れないでね！"

# カズマ
# んじゃ、残るはアクアか。\nどうなんだ？
242 = "んじゃ、残るはアクアか。\\nどうなんだ？"

# アクア
# 別にいいんじゃない？\nダメだって言う理由もないもの。
249 = "別にいいんじゃない？\\nダメだって言う理由もないもの。"

# カズマ
# よーし、これで全員の許可が出たな。\n良かったな、ゆんゆん。
240 = "よーし、これで全員の許可が出たな。\\n良かったな、ゆんゆん。"

# ゆんゆん
# はい、ありがとうございます！
229 = "はい、ありがとうございます！"

# めぐみん
# まったく……。\n何を考えているのですか、ゆんゆんは。
231 = "まったく……。\\n何を考えているのですか、ゆんゆんは。"

