# root_d01.txt.scn

[info]
0 = ""

[characters]
118 = "クリス"
116 = "カズマ"
117 = "カズマ（Ｍ）"

[character_subs]
# 116 = "カズマ"

[script]
# lines: 13

# クリス
# ちょっと、キミ！\nくっつきすぎ！
114 = "ちょっと、キミ！\\nくっつきすぎ！"

# カズマ
# 仕方ないだろ、狭いんだから。\n少しくらい我慢しろよ。
119 = "仕方ないだろ、狭いんだから。\\n少しくらい我慢しろよ。"

# クリス
# それは分かってるけど……\nあ、こ、こら！\nどさくさに紛れて変な所を触らないでよっ！！
113 = "それは分かってるけど……\\nあ、こ、こら！\\nどさくさに紛れて変な所を触らないでよっ！！"

# カズマ
# さささ、触ってねえし！
112 = "さささ、触ってねえし！"

# クリス
# あー、もう、離れてったら！
110 = "あー、もう、離れてったら！"

# カズマ
# てか動くな、いえ、動かないでください。\n本当にもう男の子は大変なんですから！
115 = "てか動くな、いえ、動かないでください。\\n本当にもう男の子は大変なんですから！"

# クリス
# うっ……。
111 = "うっ……。"

# カズマ（Ｍ）
# display as カズマ
# （狭い路地裏で可愛い女の子と２人きり。\n　しかもお互い体を密着させ、人目を忍んでいる）
125 = "（狭い路地裏で可愛い女の子と２人きり。\\n　しかもお互い体を密着させ、人目を忍んでいる）"

# カズマ（Ｍ）
# display as カズマ
# （状況だけを見ればとても美味しい場面だ。\n　状況だけならな）
124 = "（状況だけを見ればとても美味しい場面だ。\\n　状況だけならな）"

# カズマ（Ｍ）
# display as カズマ
# （当事者である俺からすれば、\n　今のこの状態は迷惑なことこの上ない）
123 = "（当事者である俺からすれば、\\n　今のこの状態は迷惑なことこの上ない）"

# カズマ（Ｍ）
# display as カズマ
# （なんでこんなことになっちまったんだ……）
121 = "（なんでこんなことになっちまったんだ……）"

# カズマ（Ｍ）
# display as カズマ
# （ひっそりと俺はため息をつき、\n　今から数時間前の出来事を思い出す）
122 = "（ひっそりと俺はため息をつき、\\n　今から数時間前の出来事を思い出す）"

# カズマ（Ｍ）
# display as カズマ
# （あの時はまだ、こんなことになるなんて\n　これっぽっちも考えていなかった──）
120 = "（あの時はまだ、こんなことになるなんて\\n　これっぽっちも考えていなかった──）"

