# root_c17.txt.scn

[info]
0 = ""

[characters]
267 = "アクア"
270 = "カズマ"
264 = "めぐみん"
274 = "ダクネス"
273 = "カズマ（Ｍ）"

[character_subs]
# 270 = "カズマ"

[script]
# lines: 50

# アクア
# それで、カズマ？\nいったいどういうつもりなのかしら？
249 = "それで、カズマ？\\nいったいどういうつもりなのかしら？"

# カズマ
# だから、さっきも言っただろ？\n俺のほうが先に入ってたんだって。
252 = "だから、さっきも言っただろ？\\n俺のほうが先に入ってたんだって。"

# カズマ
# で、お前たちが入ってくる気配がしたから\nとっさに隠れちまったんだ。
254 = "で、お前たちが入ってくる気配がしたから\\nとっさに隠れちまったんだ。"

# めぐみん
# 本当ですか？
286 = "本当ですか？"

# カズマ
# 確かに潜伏スキルを使ったのは事実だけど\n覗きが目的だったわけじゃねーよ。
322 = "確かに潜伏スキルを使ったのは事実だけど\\n覗きが目的だったわけじゃねーよ。"

# めぐみん
# だったら、最初から\n姿を隠さなければよかったんですよ。\nそのほうが、まだ誤解もされなかったはずです。
253 = "だったら、最初から\\n姿を隠さなければよかったんですよ。\\nそのほうが、まだ誤解もされなかったはずです。"

# カズマ
# フッ！\nこの卓越した冒険者である俺の身体が\nとっさに動いてしまったんだ。
275 = "フッ！\\nこの卓越した冒険者である俺の身体が\\nとっさに動いてしまったんだ。"

# アクア
# あらら？\nまだ減らず口をたたけるってことは、\n反省が足りないのかしら？
234 = "あらら？\\nまだ減らず口をたたけるってことは、\\n反省が足りないのかしら？"

# カズマ
# ごめんなさい。\nすごく反省しています。
244 = "ごめんなさい。\\nすごく反省しています。"

# ダクネス
# アクア、めぐみん。\nそれぐらいにしておいてやれ。\nカズマも充分に罰を受けただろう。
268 = "アクア、めぐみん。\\nそれぐらいにしておいてやれ。\\nカズマも充分に罰を受けただろう。"

# カズマ
# そうだそうだー。
247 = "そうだそうだー。"

# アクア
# はあ？
260 = "はあ？"

# カズマ
# ごめんなさい。
243 = "ごめんなさい。"

# ダクネス
# ほらカズマ。\nもう１度ちゃんと謝るんだ。
263 = "ほらカズマ。\\nもう１度ちゃんと謝るんだ。"

# アクア
# 土下座よ。
283 = "土下座よ。"

# めぐみん
# 土下座ですね。
282 = "土下座ですね。"

# カズマ
# なっ！　お前ら、こっちが下手に出てると思って\n調子に乗りやがって！
256 = "なっ！　お前ら、こっちが下手に出てると思って\\n調子に乗りやがって！"

# カズマ
# だいたいめぐみん！\nお前は見られて困るようなもん持ち合わせて\nねえだろうが！
251 = "だいたいめぐみん！\\nお前は見られて困るようなもん持ち合わせて\\nねえだろうが！"

# めぐみん
# なっ！？
257 = "なっ！？"

# カズマ
# アクア！
269 = "アクア！"

# アクア
# な、何よ。\nまさか女神である私まで蔑むつもりなの？
255 = "な、何よ。\\nまさか女神である私まで蔑むつもりなの？"

# カズマ
# ごめんな、お前を妄想に入れるの完全に忘れてた。
241 = "ごめんな、お前を妄想に入れるの完全に忘れてた。"

# アクア
# ええと、それってどういう意味なのかしら？
236 = "ええと、それってどういう意味なのかしら？"

# カズマ
# んー……。\nモブ？
266 = "んー……。\\nモブ？"

# アクア
# 嘘でしょ、カズマさん？\n本当は真っ先に妄想したんでしょ？
281 = "嘘でしょ、カズマさん？\\n本当は真っ先に妄想したんでしょ？"

# アクア
# そしてヒロインである女神の私を汚したのよね？
248 = "そしてヒロインである女神の私を汚したのよね？"

# カズマ
# ごめんな。ごめんな。
242 = "ごめんな。ごめんな。"

# アクア
# 二回も謝らないでよ！\n二回も謝らないでよお！
277 = "二回も謝らないでよ！\\n二回も謝らないでよお！"

# ダクネス
# ほらほら、カズマ。\nそんなことを言っていたら、\nいつまでたっても関係の修復ができないぞ。
262 = "ほらほら、カズマ。\\nそんなことを言っていたら、\\nいつまでたっても関係の修復ができないぞ。"

# カズマ
# 別に壊れてないだろ！
278 = "別に壊れてないだろ！"

# ダクネス
# こういうことはしっかりけじめをつけておかないと、\n後々尾を引くんだ。
240 = "こういうことはしっかりけじめをつけておかないと、\\n後々尾を引くんだ。"

# カズマ
# わかったよ。\n悪かったよ、アクア、めぐみん。\nそれにダクネスも。
265 = "わかったよ。\\n悪かったよ、アクア、めぐみん。\\nそれにダクネスも。"

# めぐみん
# はあ……ダクネスに免じて許してあげますよ。\nですが、さっきの発言は一生根に持ちますからね。
259 = "はあ……ダクネスに免じて許してあげますよ。\\nですが、さっきの発言は一生根に持ちますからね。"

# アクア
# ぐす、私ヒロインなのに。
239 = "ぐす、私ヒロインなのに。"

# ダクネス
# カズマ。\nしっかりと謝れて偉かったな。
272 = "カズマ。\\nしっかりと謝れて偉かったな。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、やっぱりいい。\n　なんでもないこんなことを褒めてくれるなんて、\n　ダクネスはそれだけ俺を気にかけてくれてるんだ）
323 = "（ああ、やっぱりいい。\\n　なんでもないこんなことを褒めてくれるなんて、\\n　ダクネスはそれだけ俺を気にかけてくれてるんだ）"

# カズマ（Ｍ）
# display as カズマ
# （俺は一生、このダクネスの愛に包まれて\n　生きて行きたい）
326 = "（俺は一生、このダクネスの愛に包まれて\\n　生きて行きたい）"

# ダクネス
# さて、少し早いが、夕食の準備に取りかかるか。
245 = "さて、少し早いが、夕食の準備に取りかかるか。"

# アクア
# ふっふっふ！\n実は私、いいお酒を見つけたのよ。
261 = "ふっふっふ！\\n実は私、いいお酒を見つけたのよ。"

# カズマ
# お前、また無駄遣いしやがったな。
238 = "お前、また無駄遣いしやがったな。"

# カズマ（Ｍ）
# display as カズマ
# （金を稼ぐ算段を立てておかなきゃいけないのに。\n　アクアめ……）
327 = "（金を稼ぐ算段を立てておかなきゃいけないのに。\\n　アクアめ……）"

# カズマ（Ｍ）
# display as カズマ
# （金策も全然思いつかないし、\n　このままじゃまたジリ貧生活に戻ってしまう。\n　はぁ、どうしたものか……）
328 = "（金策も全然思いつかないし、\\n　このままじゃまたジリ貧生活に戻ってしまう。\\n　はぁ、どうしたものか……）"

# カズマ
# はぁ～……。
258 = "はぁ～……。"

# ダクネス
# カズマ、どうかしたのか？
271 = "カズマ、どうかしたのか？"

# カズマ
# えっ？\nいや、なんでもない。
237 = "えっ？\\nいや、なんでもない。"

# ダクネス
# しかし、思い詰めたような顔をしていたぞ。
246 = "しかし、思い詰めたような顔をしていたぞ。"

# カズマ
# ありがとう、なんでもないよ。
235 = "ありがとう、なんでもないよ。"

# ダクネス
# それならばいいのだが。
250 = "それならばいいのだが。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、ダクネスは本当に優しいなぁ。\n　俺のことをいつも心配してくれる）
324 = "（ああ、ダクネスは本当に優しいなぁ。\\n　俺のことをいつも心配してくれる）"

# カズマ（Ｍ）
# display as カズマ
# （ちょっとした表情の変化も見逃さないなんて、\n　これはもう愛以上の何かすら感じるぞ！）
325 = "（ちょっとした表情の変化も見逃さないなんて、\\n　これはもう愛以上の何かすら感じるぞ！）"

