# root_e03.txt.scn

[info]
0 = ""

[characters]
393 = "ゆんゆん"
391 = "めぐみん"
404 = "カズマ（Ｍ）"
405 = "ダクネス"
402 = "カズマ"
397 = "ゆんゆん＆めぐみん"

[character_subs]
# 402 = "カズマ"
465 = "２人"

[script]
# lines: 93

# ゆんゆん
# あっ、また釣れた！
331 = "あっ、また釣れた！"

# めぐみん
# ふふん、甘いですね。\nこっちは１度に２匹ヒットですよ？
389 = "ふふん、甘いですね。\\nこっちは１度に２匹ヒットですよ？"

# ゆんゆん
# わ、私だって～！
398 = "わ、私だって～！"

# カズマ（Ｍ）
# display as カズマ
# （最初こそどうなるかと思ったが、\n　アクアの妨害が終わったとたん\n　入れ食い状態で釣れ始めた）
464 = "（最初こそどうなるかと思ったが、\\n　アクアの妨害が終わったとたん\\n　入れ食い状態で釣れ始めた）"

# カズマ（Ｍ）
# display as カズマ
# （もしかして、アクアが触ったことで\n　水が浄化されて魚が集まってきた……\n　なんて、それは考えすぎか）
463 = "（もしかして、アクアが触ったことで\\n　水が浄化されて魚が集まってきた……\\n　なんて、それは考えすぎか）"

# ゆんゆん
# 今のところほぼ互角よね。\n絶対に負けないわ！
411 = "今のところほぼ互角よね。\\n絶対に負けないわ！"

# ゆんゆん
# 今日こそ必ず勝って\n紅魔族の次期族長としての威厳を示すんだから！
412 = "今日こそ必ず勝って\\n紅魔族の次期族長としての威厳を示すんだから！"

# めぐみん
# させませんよ？
360 = "させませんよ？"

# めぐみん
# ……ですが、それはそれとして。\nカズマ達は何をしているのですか。
327 = "……ですが、それはそれとして。\\nカズマ達は何をしているのですか。"

# ダクネス
# ん？\n見ての通り、剣の手入れだ。
401 = "ん？\\n見ての通り、剣の手入れだ。"

# カズマ
# 俺は昼寝ですが？\nまあ、寝てないけど。\n寝転がってるだけだけど。
415 = "俺は昼寝ですが？\\nまあ、寝てないけど。\\n寝転がってるだけだけど。"

# めぐみん
# 人が真剣にやっているというのに、\nなんですかその態度は。\nもっと集中してください。
409 = "人が真剣にやっているというのに、\\nなんですかその態度は。\\nもっと集中してください。"

# カズマ
# そう言われても、こう長いとなぁ。\nつか、アクアはどうした？
363 = "そう言われても、こう長いとなぁ。\\nつか、アクアはどうした？"

# ダクネス
# ああ、水着を取りに帰ってる。
329 = "ああ、水着を取りに帰ってる。"

# カズマ（Ｍ）
# display as カズマ
# （あいつ、ここに来た主旨を完全に忘れてるな）
459 = "（あいつ、ここに来た主旨を完全に忘れてるな）"

# カズマ
# なあ、まだ日没まで時間あるけど\nそろそろ決着を付けようぜ。\nそれ以上は釣っても食べきれないし。
373 = "なあ、まだ日没まで時間あるけど\\nそろそろ決着を付けようぜ。\\nそれ以上は釣っても食べきれないし。"

# カズマ
# というわけで！\nどちらかが、次に釣り上げたら終わりにするぞ！
372 = "というわけで！\\nどちらかが、次に釣り上げたら終わりにするぞ！"

# ゆんゆん
# 私は問題ありません。
454 = "私は問題ありません。"

# めぐみん
# いいでしょう。\nどんなルールであろうと勝つのは私ですからね。
334 = "いいでしょう。\\nどんなルールであろうと勝つのは私ですからね。"

# ダクネス
# おお！\n一気に緊張感が高まったな。
348 = "おお！\\n一気に緊張感が高まったな。"

# カズマ
# さあ、どっちでもいいから\nさっさと釣り上げろ。
359 = "さあ、どっちでもいいから\\nさっさと釣り上げろ。"

# めぐみん
# かかれ、かかれ……。\nとてつもない大物を釣り上げて\nゆんゆんを黙らせるのですよ……！
351 = "かかれ、かかれ……。\\nとてつもない大物を釣り上げて\\nゆんゆんを黙らせるのですよ……！"

# ゆんゆん
# あっ、かかった！！
330 = "あっ、かかった！！"

# めぐみん
# なっ！？\nこの私が先を越された！？
375 = "なっ！？\\nこの私が先を越された！？"

# めぐみん
# いえ、まだ釣り上げたわけではないですからね！\n勝負はついていません！
336 = "いえ、まだ釣り上げたわけではないですからね！\\n勝負はついていません！"

# ゆんゆん
# くぅぅ……大きい……！
355 = "くぅぅ……大きい……！"

# ダクネス
# これはかなりの大物だぞ、\n見ろ、竿があんなにしなっている！
357 = "これはかなりの大物だぞ、\\n見ろ、竿があんなにしなっている！"

# ゆんゆん
# うぅぅ～、お、重い！
341 = "うぅぅ～、お、重い！"

# カズマ
# 頑張れ、ゆんゆん！
457 = "頑張れ、ゆんゆん！"

# ゆんゆん
# は、はい！\nありがとうございます！
380 = "は、はい！\\nありがとうございます！"

# ダクネス
# しかし、これはマズイな、\n明らかに力負けをしている。\nこのままでは引きずり込まれる可能性も……。
361 = "しかし、これはマズイな、\\n明らかに力負けをしている。\\nこのままでは引きずり込まれる可能性も……。"

# ゆんゆん
# ひ、引っ張られる～！
383 = "ひ、引っ張られる～！"

# カズマ
# 言ってるそばから！\n本当に引きずり込まれるぞ？\nゆんゆん、竿を離せ！
456 = "言ってるそばから！\\n本当に引きずり込まれるぞ？\\nゆんゆん、竿を離せ！"

# ゆんゆん
# い、いいえ……！\n今日こそはめぐみんに……！
332 = "い、いいえ……！\\n今日こそはめぐみんに……！"

# ゆんゆん
# きゃっ！
353 = "きゃっ！"

# めぐみん
# ゆんゆん！？
396 = "ゆんゆん！？"

# カズマ（Ｍ）
# display as カズマ
# （あっぶねー！\n　めぐみんが助けに入らなかったら\n　川に落ちてたぞ！？）
460 = "（あっぶねー！\\n　めぐみんが助けに入らなかったら\\n　川に落ちてたぞ！？）"

# めぐみん
# まったく、仕方ありませんね。\n力を貸してあげますから、釣り上げますよ！
390 = "まったく、仕方ありませんね。\\n力を貸してあげますから、釣り上げますよ！"

# ゆんゆん
# いいの、めぐみん？
335 = "いいの、めぐみん？"

# めぐみん
# こんな大物見逃す手はありません。\nほら、力を合わせて一緒に竿を引きますよ！
358 = "こんな大物見逃す手はありません。\\nほら、力を合わせて一緒に竿を引きますよ！"

# ゆんゆん
# う、うん！！
340 = "う、うん！！"

# カズマ（Ｍ）
# display as カズマ
# （にしても、なんて大物なんだ。\n　ふたりがかりでもビクともしない。\n　川の主でもかかったか？）
461 = "（にしても、なんて大物なんだ。\\n　ふたりがかりでもビクともしない。\\n　川の主でもかかったか？）"

# ゆんゆん
# す、すごく暴れてるよ！？
362 = "す、すごく暴れてるよ！？"

# めぐみん
# くっ……。\nこのままでは、こちらの体力が――
356 = "くっ……。\\nこのままでは、こちらの体力が――"

# ゆんゆん＆めぐみん
# display as ２人
# きゃぁぁぁぁぁぁっ！？
352 = "きゃぁぁぁぁぁぁっ！？"

# カズマ
# ふたり揃って落ちた！？\n大丈夫か！？
388 = "ふたり揃って落ちた！？\\n大丈夫か！？"

# めぐみん
# ゆんゆん！　何をやっているのですか！\n私が力を貸したというのに、\nせっかくの大物を取り逃がすなんて！
395 = "ゆんゆん！　何をやっているのですか！\\n私が力を貸したというのに、\\nせっかくの大物を取り逃がすなんて！"

# ゆんゆん
# 私のせいじゃないよ！\nめぐみんがちゃんと支えてくれないのが\n悪いんじゃない！
453 = "私のせいじゃないよ！\\nめぐみんがちゃんと支えてくれないのが\\n悪いんじゃない！"

# めぐみん
# って、ゆんゆん。\nなんかまた成長してません？
370 = "って、ゆんゆん。\\nなんかまた成長してません？"

# ゆんゆん
# え、成長って……。
342 = "え、成長って……。"

# ゆんゆん
# きゃっ！？\nな、何？　何かが服の中にいるー！
354 = "きゃっ！？\\nな、何？　何かが服の中にいるー！"

# めぐみん
# なんですか、そんなにゆらして！\n自慢ですか！　無駄に育ったことを\n露骨にアピールですか！
377 = "なんですか、そんなにゆらして！\\n自慢ですか！　無駄に育ったことを\\n露骨にアピールですか！"

# ゆんゆん
# ち、違うったら！\n服の中に何かがいるのよ！
368 = "ち、違うったら！\\n服の中に何かがいるのよ！"

# めぐみん
# 何か？
414 = "何か？"

# ゆんゆん
# ひゃあああああんっ！\nぬるぬるしてる～～！！
385 = "ひゃあああああんっ！\\nぬるぬるしてる～～！！"

# ダクネス
# ぬ、ぬるぬる！
378 = "ぬ、ぬるぬる！"

# カズマ
# お前は、記号にわざわざ反応するな。
350 = "お前は、記号にわざわざ反応するな。"

# めぐみん
# なっ！
374 = "なっ！"

# ゆんゆん
# え？　え？
344 = "え？　え？"

# ダクネス
# お、おお！！
345 = "お、おお！！"

# カズマ
# なんでお前はちょっと羨ましそうにしてるんだよ。
376 = "なんでお前はちょっと羨ましそうにしてるんだよ。"

# ゆんゆん
# ひゃあああああ、魚が！\nめぐみん取ってー！！
384 = "ひゃあああああ、魚が！\\nめぐみん取ってー！！"

# めぐみん
# い、嫌ですよ。\n手が生臭くなるじゃないですか。
333 = "い、嫌ですよ。\\n手が生臭くなるじゃないですか。"

# ゆんゆん
# ひゃあああんっ！\nますます中に……だ、誰か助けてぇ～！
386 = "ひゃあああんっ！\\nますます中に……だ、誰か助けてぇ～！"

# ダクネス
# ふ、ふふ、なるほど、こういうプレイもあるのか。\n勉強になる。
387 = "ふ、ふふ、なるほど、こういうプレイもあるのか。\\n勉強になる。"

# カズマ
# もう突っ込まないからな……。
392 = "もう突っ込まないからな……。"

# ゆんゆん
# ビチビチしてるよ！\nめぐみん、ビチビチしてるの！
406 = "ビチビチしてるよ！\\nめぐみん、ビチビチしてるの！"

# めぐみん
# カズマ、早くこれをどうにかしてください。
403 = "カズマ、早くこれをどうにかしてください。"

# カズマ（Ｍ）
# display as カズマ
# （はあ？　俺が？）
462 = "（はあ？　俺が？）"

# カズマ
# いや、もう少し様子を見よう。
338 = "いや、もう少し様子を見よう。"

# めぐみん
# そんなこと言って、\nゆんゆんの胸を楽しんでるだけでしょう。
365 = "そんなこと言って、\\nゆんゆんの胸を楽しんでるだけでしょう。"

# ゆんゆん
# ええ！？
343 = "ええ！？"

# カズマ
# いやいやいや、楽しんでなんていないから！
339 = "いやいやいや、楽しんでなんていないから！"

# めぐみん
# だったら、早く取ってあげたらどうですか。
367 = "だったら、早く取ってあげたらどうですか。"

# カズマ
# わかった、わかったよ！\n名残惜しいけど仕方がない。
399 = "わかった、わかったよ！\\n名残惜しいけど仕方がない。"

# めぐみん
# 今、少し本音が出ましたね。
410 = "今、少し本音が出ましたね。"

# カズマ
# ゆんゆん、今行くぞ！\n少しの辛抱だ！
394 = "ゆんゆん、今行くぞ！\\n少しの辛抱だ！"

# ゆんゆん
# お、お願いしますぅ！
346 = "お、お願いしますぅ！"

# カズマ
# はいはい、わかったよ。
382 = "はいはい、わかったよ。"

# ゆんゆん
# ちょちょちょ、ちょっと待ってください、\nカズマさん！
369 = "ちょちょちょ、ちょっと待ってください、\\nカズマさん！"

# カズマ
# ん、どうした？
400 = "ん、どうした？"

# ゆんゆん
# 助けるってつまり、この魚を取るんですよね？
416 = "助けるってつまり、この魚を取るんですよね？"

# めぐみん
# 他に方法がないでしょう。
413 = "他に方法がないでしょう。"

# ゆんゆん
# で、でも、魚は胸にいるんだよ？\nもし、カズマさんの手が少しでもずれたら。
371 = "で、でも、魚は胸にいるんだよ？\\nもし、カズマさんの手が少しでもずれたら。"

# めぐみん
# その時はまあ、同情してあげますよ。
364 = "その時はまあ、同情してあげますよ。"

# ゆんゆん
# お、お願いだから、めぐみんが取ってー！
347 = "お、お願いだから、めぐみんが取ってー！"

# カズマ（Ｍ）
# display as カズマ
# （あ、俺って信用無いんだ）
458 = "（あ、俺って信用無いんだ）"

# カズマ
# 待ってろ、すぐに行くぞ！
421 = "待ってろ、すぐに行くぞ！"

# ゆんゆん
# は、はい、お願いします！
379 = "は、はい、お願いします！"

# ゆんゆん
# あ、あうっ！\nダメだってば！　暴れないで！\nぬるぬるして気持ち悪いよぉ！
328 = "あ、あうっ！\\nダメだってば！　暴れないで！\\nぬるぬるして気持ち悪いよぉ！"

# めぐみん
# そんなに嫌なら、\n服を脱げばいいじゃないですか。
366 = "そんなに嫌なら、\\n服を脱げばいいじゃないですか。"

# カズマ
# おお！　それは名案だな！
349 = "おお！　それは名案だな！"

# ゆんゆん
# 絶対に嫌です！！
455 = "絶対に嫌です！！"

[selections]
337 = "いや、もう少し様子を見よう"
381 = "はいはい、わかったよ"
422 = "待ってろふたりともすぐに行くぞ！"
