# root_e12.txt.scn

[info]
0 = ""

[characters]
380 = "カズマ"
384 = "ダクネス"
369 = "めぐみん"
377 = "アクア"
372 = "ゆんゆん"
381 = "カズマ（Ｍ）"

[character_subs]
# 380 = "カズマ"

[script]
# lines: 85

# カズマ
# はぐれ魔物って、何かと思えばキャベツかよ！
365 = "はぐれ魔物って、何かと思えばキャベツかよ！"

# ダクネス
# いや、キャベツではない、サラダだ。
329 = "いや、キャベツではない、サラダだ。"

# カズマ
# お、おう、サラダ？
335 = "お、おう、サラダ？"

# ダクネス
# ああ、サラダだ。\n綺麗に皿に盛られた野菜達だ。
320 = "ああ、サラダだ。\\n綺麗に皿に盛られた野菜達だ。"

# カズマ
# こいつらって切り刻んでも生きてるのかよ！？\nどうなってるんだ、この世界の野菜は！？
340 = "こいつらって切り刻んでも生きてるのかよ！？\\nどうなってるんだ、この世界の野菜は！？"

# ダクネス
# この世界の？\nおかしなことを言うな、カズマは。
341 = "この世界の？\\nおかしなことを言うな、カズマは。"

# めぐみん
# 野菜の生命力が強いことなど\n子供だって知っている常識ではありませんか。
445 = "野菜の生命力が強いことなど\\n子供だって知っている常識ではありませんか。"

# カズマ
# 悪かったな。\n常識を知らなくて。
401 = "悪かったな。\\n常識を知らなくて。"

# ダクネス
# 強さ自体は大したことないからな、\nそう苦戦することもないだろう。
400 = "強さ自体は大したことないからな、\\nそう苦戦することもないだろう。"

# カズマ
# そりゃ、致命的なダメージを\n食らうことはないだろうけど、\nそんな簡単な話じゃないだろ。
349 = "そりゃ、致命的なダメージを\\n食らうことはないだろうけど、\\nそんな簡単な話じゃないだろ。"

# カズマ
# 数が多い上にすばしっこくて捕らえきれないぞ？
403 = "数が多い上にすばしっこくて捕らえきれないぞ？"

# アクア
# 刻まれてる分、身軽になるんだもの。\nそりゃ速くて当然よ。
393 = "刻まれてる分、身軽になるんだもの。\\nそりゃ速くて当然よ。"

# カズマ
# あー、面倒くさいなぁ……。\nこれって捕獲が前提なのか？
326 = "あー、面倒くさいなぁ……。\\nこれって捕獲が前提なのか？"

# ダクネス
# できれば捕獲が望ましいが、\nそうでなくても構わないそうだ。
359 = "できれば捕獲が望ましいが、\\nそうでなくても構わないそうだ。"

# カズマ
# だったら、無駄に走り回るより\n魔法で処理した方がいいだろう。
356 = "だったら、無駄に走り回るより\\n魔法で処理した方がいいだろう。"

# ゆんゆん
# わかりました。\nライト・オブ・セイバー！
376 = "わかりました。\\nライト・オブ・セイバー！"

# カズマ
# げっ、かわした！？\nマジか！？
339 = "げっ、かわした！？\\nマジか！？"

# ゆんゆん
# もう一回！
371 = "もう一回！"

# カズマ
# おっ、命中した！\nいける！
337 = "おっ、命中した！\\nいける！"

# アクア
# でも、このペースじゃ、\n全部倒す前に魔力が尽きちゃうんじゃない？
360 = "でも、このペースじゃ、\\n全部倒す前に魔力が尽きちゃうんじゃない？"

# カズマ
# お前はなんで他人事なんだよ。
338 = "お前はなんで他人事なんだよ。"

# めぐみん
# まったく、不甲斐ないにもほどがありますね。\n同じ紅魔族として嘆かわしい。\nちまちま倒そうとするからいけないのです。
368 = "まったく、不甲斐ないにもほどがありますね。\\n同じ紅魔族として嘆かわしい。\\nちまちま倒そうとするからいけないのです。"

# めぐみん
# 戦いにおいて最も大切なのは火力！\nそれも圧倒的なまでの火力です！
402 = "戦いにおいて最も大切なのは火力！\\nそれも圧倒的なまでの火力です！"

# めぐみん
# さあ、私がお手本を見せてあげましょう！
343 = "さあ、私がお手本を見せてあげましょう！"

# めぐみん
# エクスプローーーージョンッ！
378 = "エクスプローーーージョンッ！"

# カズマ
# おっ、やったか！！
336 = "おっ、やったか！！"

# ダクネス
# ダメだ！\n半数を吹き飛ばしただけだ！
385 = "ダメだ！\\n半数を吹き飛ばしただけだ！"

# めぐみん
# あの一瞬で、爆裂魔法の範囲外に逃げるとは……\nサラダと言えど侮れませんね……。\nあとは……頼みます……がくっ！
323 = "あの一瞬で、爆裂魔法の範囲外に逃げるとは……\\nサラダと言えど侮れませんね……。\\nあとは……頼みます……がくっ！"

# アクア
# ちょ、ちょっと！\n半分消えたのはいいけど、まだまだいるわよ。\nどうするのよ！
357 = "ちょ、ちょっと！\\n半分消えたのはいいけど、まだまだいるわよ。\\nどうするのよ！"

# ダクネス
# 私に案がある。\n覚えているか、以前のキャベツ捕獲クエストを。
444 = "私に案がある。\\n覚えているか、以前のキャベツ捕獲クエストを。"

# カズマ
# そりゃ、もちろん。\nあんな特殊すぎるクエスト、\n忘れられるわけないだろ？
348 = "そりゃ、もちろん。\\nあんな特殊すぎるクエスト、\\n忘れられるわけないだろ？"

# ダクネス
# あの時、私はとある冒険者の盾となり\n相手の攻撃を一身に受け続けた。
324 = "あの時、私はとある冒険者の盾となり\\n相手の攻撃を一身に受け続けた。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、それも覚えてるよ！\n　キャベツの攻撃を恍惚の表情で浮けとめる\n　ダクネスを見て、こいつダメだなと思ったわ！）
448 = "（ああ、それも覚えてるよ！\\n　キャベツの攻撃を恍惚の表情で浮けとめる\\n　ダクネスを見て、こいつダメだなと思ったわ！）"

# ダクネス
# 大切なのはその先だ。
397 = "大切なのはその先だ。"

# カズマ
# その先？\nあの時は確か――
347 = "その先？\\nあの時は確か――"

# カズマ
# どこかの頭のおかしなアークウィザードが\nダクネスもろとも爆裂魔法で\nキャベツを吹っ飛ばしたな。
362 = "どこかの頭のおかしなアークウィザードが\\nダクネスもろとも爆裂魔法で\\nキャベツを吹っ飛ばしたな。"

# めぐみん
# それは私のことですか？\n私のことですよね！？
351 = "それは私のことですか？\\n私のことですよね！？"

# ダクネス
# 今回もあれでいくぞ！\n私がやつらを引きつけ囮になるから、\n私もろとも魔法で吹き飛ばせ！
390 = "今回もあれでいくぞ！\\n私がやつらを引きつけ囮になるから、\\n私もろとも魔法で吹き飛ばせ！"

# ゆんゆん
# 魔法でって、めぐみんはもう……。
447 = "魔法でって、めぐみんはもう……。"

# めぐみん
# 何を言っているのです、\nあなたが打てばいいじゃないですか。
391 = "何を言っているのです、\\nあなたが打てばいいじゃないですか。"

# ゆんゆん
# ええ、私！？
332 = "ええ、私！？"

# ダクネス
# ああ、すごいのを一発頼むぞ。
318 = "ああ、すごいのを一発頼むぞ。"

# ゆんゆん
# え？　す、すごいの？
334 = "え？　す、すごいの？"

# ダクネス
# ライト・オブ・セイバーだったな？\n私はあれにとても興味があるんだ！
387 = "ライト・オブ・セイバーだったな？\\n私はあれにとても興味があるんだ！"

# ゆんゆん
# え、ええと……。
330 = "え、ええと……。"

# カズマ
# あー、ダクネスはたまにおかしいことを言うけど、\n気にする必要ないからな。
325 = "あー、ダクネスはたまにおかしいことを言うけど、\\n気にする必要ないからな。"

# カズマ
# てかお前、ゆんゆんが引いてるだろ。\n少しは自重しろよ、ド変態が。
358 = "てかお前、ゆんゆんが引いてるだろ。\\n少しは自重しろよ、ド変態が。"

# ダクネス
# それがこれから死地に飛び込む者への言葉か！\nふ、ふふ、カズマは本当に容赦ないな。
350 = "それがこれから死地に飛び込む者への言葉か！\\nふ、ふふ、カズマは本当に容赦ないな。"

# カズマ
# だから喜んでんじゃねえよ。
354 = "だから喜んでんじゃねえよ。"

# ゆんゆん
# あの、カズマさん。\nいくらダクネスさんがクルセイダーといっても、\n知り合いの人？　に魔法を撃つのはちょっと。
322 = "あの、カズマさん。\\nいくらダクネスさんがクルセイダーといっても、\\n知り合いの人？　に魔法を撃つのはちょっと。"

# めぐみん
# あなたはスカルドラゴン戦の時、\nダクネスの硬さを間近で見ていたでしょう。
321 = "あなたはスカルドラゴン戦の時、\\nダクネスの硬さを間近で見ていたでしょう。"

# めぐみん
# ゆんゆんの魔法でどうにかなるほど\nヤワではありませんよ、ダクネスは。
373 = "ゆんゆんの魔法でどうにかなるほど\\nヤワではありませんよ、ダクネスは。"

# ゆんゆん
# そういうことじゃなくて、\nわたしの気持ちの問題なのよ。
344 = "そういうことじゃなくて、\\nわたしの気持ちの問題なのよ。"

# ゆんゆん
# 知り合いの人？　に向かって魔法を撃つなんて、\n気が引けるもの。
443 = "知り合いの人？　に向かって魔法を撃つなんて、\\n気が引けるもの。"

# ゆんゆん
# めぐみんだってそうでしょ？\n知り合いの人？　に魔法を撃つなんて、\nするわけないわよね。
370 = "めぐみんだってそうでしょ？\\n知り合いの人？　に魔法を撃つなんて、\\nするわけないわよね。"

# めぐみん
# ああ、もう、なんなんですか！\nさっきから知り合い、知り合いって！
319 = "ああ、もう、なんなんですか！\\nさっきから知り合い、知り合いって！"

# めぐみん
# 友達と呼びたければ呼べばいいじゃないですか！\n本当に相変わらずめんどくさい子ですね！
394 = "友達と呼びたければ呼べばいいじゃないですか！\\n本当に相変わらずめんどくさい子ですね！"

# ゆんゆん
# わ、私、めんどうじゃないったら！
375 = "わ、私、めんどうじゃないったら！"

# カズマ（Ｍ）
# display as カズマ
# （いや、十分面倒だぞ、ゆんゆん）
449 = "（いや、十分面倒だぞ、ゆんゆん）"

# ダクネス
# なあ、ゆんゆん。\nお前の気持ちは嬉しいが、\nこのクエストを成功させる手段は他にもう無いんだ。
363 = "なあ、ゆんゆん。\\nお前の気持ちは嬉しいが、\\nこのクエストを成功させる手段は他にもう無いんだ。"

# カズマ
# そうか？
346 = "そうか？"

# ダクネス
# 頼む、ここは心を鬼にして、\n渾身の力で私に魔法を打ち込んでくれ！
446 = "頼む、ここは心を鬼にして、\\n渾身の力で私に魔法を打ち込んでくれ！"

# ゆんゆん
# だ、ダクネスさんがそう仰るなら。
353 = "だ、ダクネスさんがそう仰るなら。"

# ダクネス
# そうか。\nでは、行ってくりゅ！
345 = "そうか。\\nでは、行ってくりゅ！"

# カズマ（Ｍ）
# display as カズマ
# （お！　連中、食いついた！\n　一斉にダクネスを襲い始めたぞ！）
450 = "（お！　連中、食いついた！\\n　一斉にダクネスを襲い始めたぞ！）"

# ダクネス
# ははっ！\nそんな軽い攻撃でこの私を倒せると思うな！
366 = "ははっ！\\nそんな軽い攻撃でこの私を倒せると思うな！"

# ダクネス
# だ、だが、しかし……\nこのチクチクする刺激、\n痛がゆさが全身を駆け巡る……！
352 = "だ、だが、しかし……\\nこのチクチクする刺激、\\n痛がゆさが全身を駆け巡る……！"

# ダクネス
# 一撃の重さこそないが、\nジワジワとなぶられる感触もまた……いい！
388 = "一撃の重さこそないが、\\nジワジワとなぶられる感触もまた……いい！"

# ゆんゆん
# ダ、ダクネスさん？
383 = "ダ、ダクネスさん？"

# ダクネス
# さあ、ゆんゆん！　遠慮せず魔法を放て！\n間違っても手を抜くんじゃないぞ？
342 = "さあ、ゆんゆん！　遠慮せず魔法を放て！\\n間違っても手を抜くんじゃないぞ？"

# ダクネス
# 全力でこい！\n半端な魔法では取りこぼす可能性もあるからな！
392 = "全力でこい！\\n半端な魔法では取りこぼす可能性もあるからな！"

# ゆんゆん
# え、え～と……？
331 = "え、え～と……？"

# カズマ
# 渾身の一撃を見舞ってやれ。\n心配はいらないから。
405 = "渾身の一撃を見舞ってやれ。\\n心配はいらないから。"

# ゆんゆん
# わ、わかりました！
374 = "わ、わかりました！"

# ゆんゆん
# ラ、ライト・オブ・セイバー！！
386 = "ラ、ライト・オブ・セイバー！！"

# ダクネス
# あ、熱い！！\n全身が燃えるようだ！！\nうわぁぁぁぁぁぁぁぁぁっ！！
317 = "あ、熱い！！\\n全身が燃えるようだ！！\\nうわぁぁぁぁぁぁぁぁぁっ！！"

# ゆんゆん
# ダ、ダクネスさん！？
382 = "ダ、ダクネスさん！？"

# ダクネス
# いい……とてもいい……、\nこれはなかなかクセになりそうだ……。\nこれが上級魔法の味……悪くない！
328 = "いい……とてもいい……、\\nこれはなかなかクセになりそうだ……。\\nこれが上級魔法の味……悪くない！"

# ゆんゆん
# え？　ええ？　えええ？
333 = "え？　ええ？　えええ？"

# ダクネス
# まだだ、ゆんゆん！\nもっとだ！　もっと魔法を放て！！
367 = "まだだ、ゆんゆん！\\nもっとだ！　もっと魔法を放て！！"

# ゆんゆん
# カ、カズマさん……、\nダクネスさん……よ、喜んでます！\n喜んでますよ！？
379 = "カ、カズマさん……、\\nダクネスさん……よ、喜んでます！\\n喜んでますよ！？"

# カズマ
# だから言ったろ？\n心配いらないって。
355 = "だから言ったろ？\\n心配いらないって。"

# ゆんゆん
# い、いいえ、別な意味で心配です！\n思っていた仲間との戦闘と……ち、違う……。
327 = "い、いいえ、別な意味で心配です！\\n思っていた仲間との戦闘と……ち、違う……。"

# ダクネス
# どうした！？\n早く来ないか、ゆんゆん！！　早くぅっ！！
361 = "どうした！？\\n早く来ないか、ゆんゆん！！　早くぅっ！！"

# ゆんゆん
# は、はい、わかりました！
364 = "は、はい、わかりました！"

