# root_c20.txt.scn

[info]
0 = ""

[characters]
211 = "カズマ"
216 = "ダクネス"
214 = "カズマ（Ｍ）"
209 = "アクア"
207 = "めぐみん"

[character_subs]
# 211 = "カズマ"

[script]
# lines: 43

# カズマ
# なぁ、頼むよダクネス！\n答えてくれ！
199 = "なぁ、頼むよダクネス！\\n答えてくれ！"

# ダクネス
# 誤解させてしまったようで、すまない。
260 = "誤解させてしまったようで、すまない。"

# カズマ（Ｍ）
# display as カズマ
# （え……）
262 = "（え……）"

# ダクネス
# カズマが、あの指輪騒動の後から\n元気がなかったので、心配していたんだ。
212 = "カズマが、あの指輪騒動の後から\\n元気がなかったので、心配していたんだ。"

# ダクネス
# ひどい目にあって、もうこの街に\n嫌気が差してしまったんじゃないか――
201 = "ひどい目にあって、もうこの街に\\n嫌気が差してしまったんじゃないか――"

# ダクネス
# もしかすると、故郷に\n帰りたがっているんじゃないか、と。
208 = "もしかすると、故郷に\\n帰りたがっているんじゃないか、と。"

# カズマ
# 俺がホームシックに\nなってるって、心配したのか？
221 = "俺がホームシックに\\nなってるって、心配したのか？"

# ダクネス
# ああ。\nなんとかお金を貯めるために、\n色々なことをしただろう？
185 = "ああ。\\nなんとかお金を貯めるために、\\n色々なことをしただろう？"

# ダクネス
# 私はその時、カズマの故郷の文化を知って\n多くの驚きを得たが――
259 = "私はその時、カズマの故郷の文化を知って\\n多くの驚きを得たが――"

# ダクネス
# カズマは、望郷の念に\n駆られてしまったのではないかと、\nそう思ったのだ。
213 = "カズマは、望郷の念に\\n駆られてしまったのではないかと、\\nそう思ったのだ。"

# カズマ（Ｍ）
# display as カズマ
# （それで……俺に優しく？）
265 = "（それで……俺に優しく？）"

# カズマ
# ということは……\n今までのことはすべて勘違いで、\n俺の独り相撲だったってこと？
197 = "ということは……\\n今までのことはすべて勘違いで、\\n俺の独り相撲だったってこと？"

# アクア
# 何？　ダクネスの行動を愛情と勘違いしてたの？
220 = "何？　ダクネスの行動を愛情と勘違いしてたの？"

# アクア
# ただ、同情されてただけなのに？
195 = "ただ、同情されてただけなのに？"

# アクア
# プークスクス、うけるんですけど！\n超うけるんですけど！
218 = "プークスクス、うけるんですけど！\\n超うけるんですけど！"

# カズマ（Ｍ）
# display as カズマ
# （くっ、こいつっ！）
264 = "（くっ、こいつっ！）"

# アクア
# あははは、あは、あはははは、可哀想！
186 = "あははは、あは、あはははは、可哀想！"

# めぐみん
# アクア、笑いすぎですよ。\nぷぷっ……き、気持ちはわからなくもありませんが。
210 = "アクア、笑いすぎですよ。\\nぷぷっ……き、気持ちはわからなくもありませんが。"

# カズマ
# くっ……うぅぅぅぅ……。
190 = "くっ……うぅぅぅぅ……。"

# ダクネス
# ２人とも、これは誤解だったんだ。\nそんな風に言ってやるな。
267 = "２人とも、これは誤解だったんだ。\\nそんな風に言ってやるな。"

# カズマ
# なあ、俺って、そんなに落ち込んでる様に\n見えてたのか？
200 = "なあ、俺って、そんなに落ち込んでる様に\\n見えてたのか？"

# ダクネス
# ああ、しょっちゅうため息をついて、\n物思いにふけっていたではないか。
184 = "ああ、しょっちゅうため息をついて、\\n物思いにふけっていたではないか。"

# カズマ（Ｍ）
# display as カズマ
# （えっ？　そうだっけ？\n　確かに考え事はしてたけど……\n　無意識にため息をつきまくっていたのか？）
263 = "（えっ？　そうだっけ？\\n　確かに考え事はしてたけど……\\n　無意識にため息をつきまくっていたのか？）"

# カズマ
# 俺は……\n今回の指輪騒動でそんなに金が稼げなくて、\n今後の生活が不安だったから――
222 = "俺は……\\n今回の指輪騒動でそんなに金が稼げなくて、\\n今後の生活が不安だったから――"

# カズマ
# またどうやって稼ごうか考えていただけなんだ。
205 = "またどうやって稼ごうか考えていただけなんだ。"

# アクア
# そんなのスカルドラゴンの討伐報酬が\n入ってくるんだから、気にする必要ないじゃない。
194 = "そんなのスカルドラゴンの討伐報酬が\\n入ってくるんだから、気にする必要ないじゃない。"

# カズマ
# それだっていくらになるかわからないだろ？
192 = "それだっていくらになるかわからないだろ？"

# カズマ
# だいたい、お前が湯水のように金を使うから、\n俺が頭を悩ませているんだろうが、この駄女神！
196 = "だいたい、お前が湯水のように金を使うから、\\n俺が頭を悩ませているんだろうが、この駄女神！"

# アクア
# あー、駄女神って言った！
187 = "あー、駄女神って言った！"

# ダクネス
# まあまあ。\n勘違いをさせるような行動をしてしまった私にも\n非があるのだし、そう責めてやるな。
203 = "まあまあ。\\n勘違いをさせるような行動をしてしまった私にも\\n非があるのだし、そう責めてやるな。"

# めぐみん
# まったく、ダクネスはどこまで温厚なのですか。
206 = "まったく、ダクネスはどこまで温厚なのですか。"

# アクア
# 私だったらあんなセクハラされた瞬間、\nゴッドブローをぶち込むわね。
258 = "私だったらあんなセクハラされた瞬間、\\nゴッドブローをぶち込むわね。"

# カズマ
# セセセ、セクハラなんてしてねーし？\nただ甘えてただけだ。
215 = "セセセ、セクハラなんてしてねーし？\\nただ甘えてただけだ。"

# アクア
# どうかしら？\n度を超した要求もしてたそうじゃない。
198 = "どうかしら？\\n度を超した要求もしてたそうじゃない。"

# カズマ
# まさか……すべてお前らに筒抜けだったのか？
204 = "まさか……すべてお前らに筒抜けだったのか？"

# めぐみん
# 逆に聞きますが、\nなぜバレていないと思ったのですか？
261 = "逆に聞きますが、\\nなぜバレていないと思ったのですか？"

# カズマ
# うぉぉぉぉぉぉぉぉぉぉぉ……。
189 = "うぉぉぉぉぉぉぉぉぉぉぉ……。"

# ダクネス
# ふふっ！
202 = "ふふっ！"

# アクア
# ダクネスも、このセクハラヒキニートに\nなんか言ってやんなさいよ。
217 = "ダクネスも、このセクハラヒキニートに\\nなんか言ってやんなさいよ。"

# ダクネス
# いいんだ。\n私も私で楽しんでいたからな。
188 = "いいんだ。\\n私も私で楽しんでいたからな。"

# アクア
# そうなの？
191 = "そうなの？"

# ダクネス
# それに、カズマに笑顔が戻ってきて良かった。\nようやく日常が戻ってきた気がするよ。
193 = "それに、カズマに笑顔が戻ってきて良かった。\\nようやく日常が戻ってきた気がするよ。"

# カズマ（Ｍ）
# display as カズマ
# （俺は全然、そんな気がしねーんですけどー！！）
266 = "（俺は全然、そんな気がしねーんですけどー！！）"

