# root_d19.txt.scn

[info]
0 = ""

[characters]
132 = "カズマ"
134 = "クリス"
133 = "カズマ（Ｍ）"

[character_subs]
# 132 = "カズマ"

[script]
# lines: 18

# カズマ
# 結構広いんだな、ここ。
153 = "結構広いんだな、ここ。"

# クリス
# まぁ、この街における\nエリス教団の拠点みたいなものだからね。
129 = "まぁ、この街における\\nエリス教団の拠点みたいなものだからね。"

# クリス
# 建物自体は古いけど、きちんと掃除されてるし\nみんな大事に使ってくれてるよ。
137 = "建物自体は古いけど、きちんと掃除されてるし\\nみんな大事に使ってくれてるよ。"

# カズマ
# そうたくさん知ってるわけでもないけど、\nエリス教徒は穏やかな人が多いよな。
122 = "そうたくさん知ってるわけでもないけど、\\nエリス教徒は穏やかな人が多いよな。"

# カズマ
# それに比べてアクシズ教徒はなんなんだ！\n隙を見れば詐欺ったり、\nネズミ講まがいのことするし……。
124 = "それに比べてアクシズ教徒はなんなんだ！\\n隙を見れば詐欺ったり、\\nネズミ講まがいのことするし……。"

# カズマ
# やっぱり信仰対象の品格が影響してるのか？
130 = "やっぱり信仰対象の品格が影響してるのか？"

# クリス
# あはは、女神アクアと女神エリスは\n先輩と後輩の関係に当たるから、別にいがみ合う\n必要はないんだけどね……困ったもんだよ。
119 = "あはは、女神アクアと女神エリスは\\n先輩と後輩の関係に当たるから、別にいがみ合う\\n必要はないんだけどね……困ったもんだよ。"

# カズマ（Ｍ）
# display as カズマ
# （あれ、なんだかクリスの口調が\n　元に戻ってきた気がするな。\n　もしかして機嫌直してくれたのか？）
154 = "（あれ、なんだかクリスの口調が\\n　元に戻ってきた気がするな。\\n　もしかして機嫌直してくれたのか？）"

# カズマ
# なあ、クリス。\n俺のこと、許してくれたのか？
128 = "なあ、クリス。\\n俺のこと、許してくれたのか？"

# クリス
# そんなわけないでしょ。\nみんなの前でキミにされたこと、\n絶対忘れないんだから。
125 = "そんなわけないでしょ。\\nみんなの前でキミにされたこと、\\n絶対忘れないんだから。"

# カズマ（Ｍ）
# display as カズマ
# （やっぱりさっきより言葉が柔らかくなってる。\n　どうしたんだ？\n　何か機嫌が良くなるようなことあったっけ？）
156 = "（やっぱりさっきより言葉が柔らかくなってる。\\n　どうしたんだ？\\n　何か機嫌が良くなるようなことあったっけ？）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、ずっとプリプリ怒ってるよりは\n　こっちのほうがマシだけどさ）
155 = "（まあ、ずっとプリプリ怒ってるよりは\\n　こっちのほうがマシだけどさ）"

# クリス
# しっ、中に入ってきたみたい。
121 = "しっ、中に入ってきたみたい。"

# カズマ
# わかるのか？
131 = "わかるのか？"

# クリス
# かすかに足音が聞こえたから。
120 = "かすかに足音が聞こえたから。"

# カズマ
# とりあえず、そこの階段上って２階へ行こう。\nここでウダウダしてるより見つかりにくいだろ。
127 = "とりあえず、そこの階段上って２階へ行こう。\\nここでウダウダしてるより見つかりにくいだろ。"

# カズマ
# それに、向こうはまだ\n俺達がここにいるって気付いてないから、\n上手くやればやり過ごせるかもしれない。
123 = "それに、向こうはまだ\\n俺達がここにいるって気付いてないから、\\n上手くやればやり過ごせるかもしれない。"

# クリス
# だといいんだけどね。
126 = "だといいんだけどね。"

