# root_d13.txt.scn

[info]
0 = ""

[characters]
218 = "クリス"
214 = "カズマ"
210 = "めぐみん"
216 = "カズマ（Ｍ）"
236 = "盗賊風の男冒険者"
232 = "戦士風の男冒険者"

[character_subs]
# 214 = "カズマ"
235 = "盗賊冒険者"
231 = "戦士冒険者"

[script]
# lines: 38

# クリス
# ふああああー……。\nんー、おはようカズマ。
209 = "ふああああー……。\\nんー、おはようカズマ。"

# カズマ
# おう、よく寝てたな。
198 = "おう、よく寝てたな。"

# クリス
# それで？\nあたしが寝ている間に何かあった？
203 = "それで？\\nあたしが寝ている間に何かあった？"

# カズマ
# いや、特に何も。\nめぐみんが下で見張っててくれてるけど\n静かなもんだ。
196 = "いや、特に何も。\\nめぐみんが下で見張っててくれてるけど\\n静かなもんだ。"

# クリス
# そっか。\nまあ、それは幸いだけど、これからどうする？
201 = "そっか。\\nまあ、それは幸いだけど、これからどうする？"

# カズマ
# そうだなぁ。\n制限時間まで誰にも捕まらないよう\n逃げ切ることは大前提として――
200 = "そうだなぁ。\\n制限時間まで誰にも捕まらないよう\\n逃げ切ることは大前提として――"

# カズマ
# このくだらない噂を広めて\n勝手にクエスト発注したバカを見つけ出す！
199 = "このくだらない噂を広めて\\n勝手にクエスト発注したバカを見つけ出す！"

# クリス
# 犯人の心当たりはあるの？\nさっきはないようなあるような\n曖昧な感じだったけど。
233 = "犯人の心当たりはあるの？\\nさっきはないようなあるような\\n曖昧な感じだったけど。"

# カズマ
# 状況から考えて、こんなことをする\n大バカ者は１人だけ――アクアだけだ。
234 = "状況から考えて、こんなことをする\\n大バカ者は１人だけ――アクアだけだ。"

# カズマ
# 問題はあいつがどこに行ったかだ。\n当てもなく街の中を探してたら\n俺達が他の奴らに捕まっちまうし。
225 = "問題はあいつがどこに行ったかだ。\\n当てもなく街の中を探してたら\\n俺達が他の奴らに捕まっちまうし。"

# クリス
# だったらさ、\nこのままここでのんびり待とうよ。\nアクアさんもそのうち帰ってくるでしょ。
205 = "だったらさ、\\nこのままここでのんびり待とうよ。\\nアクアさんもそのうち帰ってくるでしょ。"

# カズマ
# そりゃまあ、そうだろうけど。
202 = "そりゃまあ、そうだろうけど。"

# クリス
# どうしたの？\n渋い顔しちゃって。
207 = "どうしたの？\\n渋い顔しちゃって。"

# カズマ
# 俺たちがここに逃げ込んで数時間、\n当然街で俺たちの目撃情報はないわけだろ？
222 = "俺たちがここに逃げ込んで数時間、\\n当然街で俺たちの目撃情報はないわけだろ？"

# クリス
# ああ、なるほど。\nさすがにこの屋敷に逃げ込んだって、\nみんなが察し始める頃ってわけか。
189 = "ああ、なるほど。\\nさすがにこの屋敷に逃げ込んだって、\\nみんなが察し始める頃ってわけか。"

# カズマ
# 大人しく外で待っててくれるだけならいいんだけど、\n相手は血の気だけは無駄に多い冒険者連中だからな。
227 = "大人しく外で待っててくれるだけならいいんだけど、\\n相手は血の気だけは無駄に多い冒険者連中だからな。"

# クリス
# めぐみんが上手く言ってくれたんでしょ？\nだったら平気だよ。
211 = "めぐみんが上手く言ってくれたんでしょ？\\nだったら平気だよ。"

# クリス
# それに、人の家へ無理やり押し入るような人が\nこの街にいるわけないじゃない。
204 = "それに、人の家へ無理やり押し入るような人が\\nこの街にいるわけないじゃない。"

# クリス
# キミは臨時パーティーを組んだりしないから\n知らないかもしれないけど、\nみんないい人ばかりなんだよ？
217 = "キミは臨時パーティーを組んだりしないから\\n知らないかもしれないけど、\\nみんないい人ばかりなんだよ？"

# カズマ
# やめろクリス。\nそれは確実にフラグだ。
212 = "やめろクリス。\\nそれは確実にフラグだ。"

# クリス
# フラグ？
219 = "フラグ？"

# カズマ
# あー、いや、だからな――
192 = "あー、いや、だからな――"

# クリス
# な、なに？\n今の音は……。
208 = "な、なに？\\n今の音は……。"

# めぐみん
# 大変です、カズマ！\n痺れを切らした冒険者達が\n屋敷の扉をこじあけようとしています！
228 = "大変です、カズマ！\\n痺れを切らした冒険者達が\\n屋敷の扉をこじあけようとしています！"

# めぐみん
# 鍵をかけて来ましたけど、そう長くは持ちません。\n突破されるのは時間の問題です！\n早く、ここから逃げてください！
257 = "鍵をかけて来ましたけど、そう長くは持ちません。\\n突破されるのは時間の問題です！\\n早く、ここから逃げてください！"

# カズマ
# あー、もう言わんこっちゃない！
193 = "あー、もう言わんこっちゃない！"

# めぐみん
# カズマ、早く！\n急いでください！
215 = "カズマ、早く！\\n急いでください！"

# カズマ（Ｍ）
# display as カズマ
# （裏口まで行って逃げるか？\n　いや、それには廊下を通らなきゃいけない。\n　部屋から出たらその瞬間、見つかる可能性が……）
259 = "（裏口まで行って逃げるか？\\n　いや、それには廊下を通らなきゃいけない。\\n　部屋から出たらその瞬間、見つかる可能性が……）"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# いたか？
194 = "いたか？"

# 戦士風の男冒険者
# display as 戦士冒険者
# いや、こっちにはいない。
195 = "いや、こっちにはいない。"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# ちっ、手間取らせやがって。\n片っぱしから家探ししろ！
206 = "ちっ、手間取らせやがって。\\n片っぱしから家探ししろ！"

# カズマ（Ｍ）
# display as カズマ
# （裏口まで行く案は却下だ。\n　けど、どうする？\n　ここは２階だ、逃げ道なんて……）
258 = "（裏口まで行く案は却下だ。\\n　けど、どうする？\\n　ここは２階だ、逃げ道なんて……）"

# カズマ
# 仕方ない。\nクリス、こっちに！
221 = "仕方ない。\\nクリス、こっちに！"

# クリス
# えっ、そっちって窓しかないけど？
197 = "えっ、そっちって窓しかないけど？"

# カズマ
# イチかバチかだ！　飛び降りるんだ！
213 = "イチかバチかだ！　飛び降りるんだ！"

# クリス
# あたしは平気だけど、キミは大丈夫なのかな？
190 = "あたしは平気だけど、キミは大丈夫なのかな？"

# カズマ
# 大丈夫！　だと信じたい。
226 = "大丈夫！　だと信じたい。"

# クリス
# あはは、頼もしいね。
191 = "あはは、頼もしいね。"

