# root_e18.txt.scn

[info]
0 = ""

[characters]
372 = "ゆんゆん"
373 = "アクア"
382 = "クリス"
379 = "ウィズ"
380 = "カズマ"
368 = "めぐみん"
381 = "カズマ（Ｍ）"
385 = "ダクネス"

[character_subs]
# 380 = "カズマ"

[script]
# lines: 88

# ゆんゆん
# どうぞっ！\nジャイアントトードの唐揚げとシュワシュワです。
356 = "どうぞっ！\\nジャイアントトードの唐揚げとシュワシュワです。"

# アクア
# 待ってました！\nもうお腹ぺこぺこで死ぬかと思ったわよ。
398 = "待ってました！\\nもうお腹ぺこぺこで死ぬかと思ったわよ。"

# アクア
# というわけで、あーん。
355 = "というわけで、あーん。"

# ゆんゆん
# はい、どうぞ。\nあーん。
360 = "はい、どうぞ。\\nあーん。"

# アクア
# あむあむあむ、ゆんゆんはあれね？\n食べさせ方も天才的ね。
319 = "あむあむあむ、ゆんゆんはあれね？\\n食べさせ方も天才的ね。"

# ゆんゆん
# ありがとうございます！\nささ、シュワシュワもどうぞ。
321 = "ありがとうございます！\\nささ、シュワシュワもどうぞ。"

# アクア
# えっ！？　何これ！？\nこのグラス、キンキンに冷えてるんですけど！
328 = "えっ！？　何これ！？\\nこのグラス、キンキンに冷えてるんですけど！"

# ゆんゆん
# ジョッキをあらかじめ魔法で凍らせて\nおいたんですよ。
383 = "ジョッキをあらかじめ魔法で凍らせて\\nおいたんですよ。"

# アクア
# くうう！　冷えたシュワシュワが\n信じられないくらい美味しいわ！
334 = "くうう！　冷えたシュワシュワが\\n信じられないくらい美味しいわ！"

# アクア
# それにこの唐揚げ！\n外はサクサクで中はジューシー！\nこれぞ至高の一品！
348 = "それにこの唐揚げ！\\n外はサクサクで中はジューシー！\\nこれぞ至高の一品！"

# ゆんゆん
# アクアさん、他にして欲しい事があったら\n遠慮せずに言ってくださいね。
374 = "アクアさん、他にして欲しい事があったら\\n遠慮せずに言ってくださいね。"

# アクア
# そうね、じゃあ次はサラダを貰おうかしら。
343 = "そうね、じゃあ次はサラダを貰おうかしら。"

# ゆんゆん
# はい、どんどん食べてください。
361 = "はい、どんどん食べてください。"

# ゆんゆん
# あっ、ほっぺたにソースがついちゃいましたから、\n拭き取りますね。
318 = "あっ、ほっぺたにソースがついちゃいましたから、\\n拭き取りますね。"

# アクア
# あ～、極楽極楽。\nもうこのまま一生甘やかされて生きていきたい～。
323 = "あ～、極楽極楽。\\nもうこのまま一生甘やかされて生きていきたい～。"

# クリス
# ……見事なまでに甘やかしてるね。
316 = "……見事なまでに甘やかしてるね。"

# ウィズ
# でも楽しそうですよ。\n見てください、ふたりの嬉しそうな顔を。
354 = "でも楽しそうですよ。\\n見てください、ふたりの嬉しそうな顔を。"

# カズマ
# アクアの方は\nただただ締まりがないだけだけどな。\nダメ人間の見本だ。
376 = "アクアの方は\\nただただ締まりがないだけだけどな。\\nダメ人間の見本だ。"

# めぐみん
# ……あれでは、\nアクアのためにはなりませんよ。
315 = "……あれでは、\\nアクアのためにはなりませんよ。"

# カズマ
# ほう？　言うじゃないか。\nなら、お手並みを拝見させてもらおうか。
366 = "ほう？　言うじゃないか。\\nなら、お手並みを拝見させてもらおうか。"

# めぐみん
# 言われるまでもありません。
446 = "言われるまでもありません。"

# カズマ
# それじゃ、ゆんゆんのターンはそこまでだ。
345 = "それじゃ、ゆんゆんのターンはそこまでだ。"

# アクア
# え～、早い！\nもっともっと奉仕されたい！\nもっともっともっと甘やかされたい！
329 = "え～、早い！\\nもっともっと奉仕されたい！\\nもっともっともっと甘やかされたい！"

# カズマ
# だーまーれー！\n心配しなくても、\nめぐみんがお前の面倒を見てくれる。
351 = "だーまーれー！\\n心配しなくても、\\nめぐみんがお前の面倒を見てくれる。"

# めぐみん
# そうですよ。\nゆんゆんなど足下にも及ばない、\n最高のもてなしを約束しましょう。
342 = "そうですよ。\\nゆんゆんなど足下にも及ばない、\\n最高のもてなしを約束しましょう。"

# アクア
# あら、それは楽しみね。
320 = "あら、それは楽しみね。"

# カズマ
# めぐみんがする前に、\nゆんゆんのお世話はどうだったんだ、アクア。
369 = "めぐみんがする前に、\\nゆんゆんのお世話はどうだったんだ、アクア。"

# アクア
# もちろん完璧よ！\n何をやらせてもそつなくこなすし、\nどんなに散らかしても素早く片付けてくれる。
371 = "もちろん完璧よ！\\n何をやらせてもそつなくこなすし、\\nどんなに散らかしても素早く片付けてくれる。"

# アクア
# おかげでゴミ１つ落ちてないじゃない。\nこんないい物件、他にないと思うわ。
332 = "おかげでゴミ１つ落ちてないじゃない。\\nこんないい物件、他にないと思うわ。"

# カズマ（Ｍ）
# display as カズマ
# （どこの不動産屋だ、お前は）
450 = "（どこの不動産屋だ、お前は）"

# クリス
# なるほど。\nアクアさんとしては大満足なわけだね。
358 = "なるほど。\\nアクアさんとしては大満足なわけだね。"

# アクア
# 大満足も大満足、超満足よ！\nあのまま一生を終えても悔いはないわね。
392 = "大満足も大満足、超満足よ！\\nあのまま一生を終えても悔いはないわね。"

# ダクネス
# いや、魔王を倒すのが目的なのだろう？\nここで終えてどうする。
325 = "いや、魔王を倒すのが目的なのだろう？\\nここで終えてどうする。"

# アクア
# 魔王？　誰それ？
447 = "魔王？　誰それ？"

# カズマ（Ｍ）
# display as カズマ
# （うわー、ダメだ。\n　もう女神の立場に戻る気すら\n　なくしてるじゃないか）
449 = "（うわー、ダメだ。\\n　もう女神の立場に戻る気すら\\n　なくしてるじゃないか）"

# クリス
# それじゃ、次はめぐみんだね。
346 = "それじゃ、次はめぐみんだね。"

# アクア
# さあ、存分にお世話なさい！\n言っておくけど、私は甘くないわよ！
335 = "さあ、存分にお世話なさい！\\n言っておくけど、私は甘くないわよ！"

# めぐみん
# 甘くないのは私も同じですよ。\nでは、早速始めましょう。\n終わりの始まりを。
405 = "甘くないのは私も同じですよ。\\nでは、早速始めましょう。\\n終わりの始まりを。"

# アクア
# 終わりの始まり？
444 = "終わりの始まり？"

# めぐみん
# いつまでだらけているのです。\nクエストに向かいますよ。
324 = "いつまでだらけているのです。\\nクエストに向かいますよ。"

# アクア
# はあ？　何言ってんのよ？\n行くわけないじゃない。\nそれより――
359 = "はあ？　何言ってんのよ？\\n行くわけないじゃない。\\nそれより――"

# めぐみん
# 黒より黒く、闇より昏き漆黒に\n我が真紅の混淆を望みたもう――
448 = "黒より黒く、闇より昏き漆黒に\\n我が真紅の混淆を望みたもう――"

# アクア
# ストップストップ！\nどうしてそこで爆裂魔法なの！？
384 = "ストップストップ！\\nどうしてそこで爆裂魔法なの！？"

# めぐみん
# さっさとクエストの準備をしなければ、\n屋敷もろとも吹き飛ばします。
337 = "さっさとクエストの準備をしなければ、\\n屋敷もろとも吹き飛ばします。"

# アクア
# ちょ、ちょっと？\n目が笑ってないんですけど？
352 = "ちょ、ちょっと？\\n目が笑ってないんですけど？"

# めぐみん
# 本気なのですから当然です。
400 = "本気なのですから当然です。"

# アクア
# だ、だけど、急にクエストって言われても。
350 = "だ、だけど、急にクエストって言われても。"

# めぐみん
# 確かに急で申し訳ないのですが、\nアクアにピッタリなクエストだったものですから。
443 = "確かに急で申し訳ないのですが、\\nアクアにピッタリなクエストだったものですから。"

# めぐみん
# そう、これは女神の如き美貌と知性と品性を\n求められるクエストなんですよ。
339 = "そう、これは女神の如き美貌と知性と品性を\\n求められるクエストなんですよ。"

# めぐみん
# 無事やり遂げられるのは、\nアクアを措いて他にはいないと\n私は確信しています。
404 = "無事やり遂げられるのは、\\nアクアを措いて他にはいないと\\n私は確信しています。"

# アクア
# ふふん、そうなの？\nそこまで言うのなら仕方がないわね。\nこのアクア様がひと肌脱いであげようじゃない。
365 = "ふふん、そうなの？\\nそこまで言うのなら仕方がないわね。\\nこのアクア様がひと肌脱いであげようじゃない。"

# めぐみん
# さすがアクアです！\nでは、早速向かいましょうか。
336 = "さすがアクアです！\\nでは、早速向かいましょうか。"

# アクア
# 疲れた～、もう歩けない～。
407 = "疲れた～、もう歩けない～。"

# めぐみん
# お疲れ様です。\n存分に休んでください。
333 = "お疲れ様です。\\n存分に休んでください。"

# アクア
# めぐみん？\nあれのどこに女神の如き\n美貌と知性と品性が必要だって言うのよ。
370 = "めぐみん？\\nあれのどこに女神の如き\\n美貌と知性と品性が必要だって言うのよ。"

# アクア
# あんなの、誰だってできたでしょ？
322 = "あんなの、誰だってできたでしょ？"

# めぐみん
# そうですか？\nですが、依頼主のおじいさんは\nとても喜んでいましたよね？
341 = "そうですか？\\nですが、依頼主のおじいさんは\\nとても喜んでいましたよね？"

# めぐみん
# 何度も何度も頭を下げてくれて、\n感謝してくれていました。
387 = "何度も何度も頭を下げてくれて、\\n感謝してくれていました。"

# アクア
# そりゃ、まあ、悪い気はしなかったけど。
344 = "そりゃ、まあ、悪い気はしなかったけど。"

# めぐみん
# それに、子供達だって嬉しそうに\n笑っていましたよ？
347 = "それに、子供達だって嬉しそうに\\n笑っていましたよ？"

# めぐみん
# アクアは、みんなを幸せにしてあげたんです。\nそれだけで十分ではないですか？
377 = "アクアは、みんなを幸せにしてあげたんです。\\nそれだけで十分ではないですか？"

# めぐみん
# 力を持つ者が力のない者を助ける。\nこれこそ真のＷｉｎ－Ｗｉｎだと私は思います。
389 = "力を持つ者が力のない者を助ける。\\nこれこそ真のＷｉｎ－Ｗｉｎだと私は思います。"

# めぐみん
# アクアの力を、もっと役に立てなくては\nもったいないではありませんか。
375 = "アクアの力を、もっと役に立てなくては\\nもったいないではありませんか。"

# アクア
# まあ、それは、そうね……うん。
367 = "まあ、それは、そうね……うん。"

# クリス
# おおー！\n見事なアメとムチの使い分けだね。
331 = "おおー！\\n見事なアメとムチの使い分けだね。"

# ダクネス
# ああ、結果、誰も損をしていない。\nそれどころか清々しささえある。
317 = "ああ、結果、誰も損をしていない。\\nそれどころか清々しささえある。"

# ウィズ
# アクア様もまんざらではないようですし、\n大変、素晴らしい結果ではないでしょうか？
378 = "アクア様もまんざらではないようですし、\\n大変、素晴らしい結果ではないでしょうか？"

# ゆんゆん
# そうだったのね。\nただ尽くすだけが相手のためじゃない、\n時にはダメにしてしまう。
340 = "そうだったのね。\\nただ尽くすだけが相手のためじゃない、\\n時にはダメにしてしまう。"

# ゆんゆん
# 甘やかすだけではなく時には厳しく\n相手を導いてあげる――\nこれこそ、本当の仲間なんだわ……！
406 = "甘やかすだけではなく時には厳しく\\n相手を導いてあげる――\\nこれこそ、本当の仲間なんだわ……！"

# ゆんゆん
# そんなこともわからないなんて、\n私、まだまだ、めぐみんに敵わないなぁ。
349 = "そんなこともわからないなんて、\\n私、まだまだ、めぐみんに敵わないなぁ。"

# カズマ（Ｍ）
# display as カズマ
# （よし、どうやら上手くいったな。\n　やるじゃないか、めぐみん）
451 = "（よし、どうやら上手くいったな。\\n　やるじゃないか、めぐみん）"

# カズマ
# 終了、ここまで！
445 = "終了、ここまで！"

# カズマ
# では、採点に入るぞ。\nゆんゆんの方が優れていたと思う者は挙手！
353 = "では、採点に入るぞ。\\nゆんゆんの方が優れていたと思う者は挙手！"

# アクア
# はい！\nはいはいはーーーーーい！
363 = "はい！\\nはいはいはーーーーーい！"

# カズマ
# 手を上げているのはアクア１人だけだな。\nよって、この勝負めぐみんの勝ち！
399 = "手を上げているのはアクア１人だけだな。\\nよって、この勝負めぐみんの勝ち！"

# めぐみん
# 当然の結果です。
396 = "当然の結果です。"

# アクア
# え～！　なんで？\nどうしてみんな手を上げないのよ！？
330 = "え～！　なんで？\\nどうしてみんな手を上げないのよ！？"

# カズマ
# 決まったことだ、お前は黙ってろ。
402 = "決まったことだ、お前は黙ってろ。"

# カズマ
# さて、これで２対２の同点だが、\nもう勝負を用意していない。\nよって、今回は引き分けで終了とする。
338 = "さて、これで２対２の同点だが、\\nもう勝負を用意していない。\\nよって、今回は引き分けで終了とする。"

# カズマ
# 当分、パーティーメンバーは\n現状維持ってことで、双方、納得してくれ。
395 = "当分、パーティーメンバーは\\n現状維持ってことで、双方、納得してくれ。"

# ゆんゆん
# はい、構いません。
362 = "はい、構いません。"

# めぐみん
# ええ、今日のところは\nこのくらいにしておいてあげましょう。
327 = "ええ、今日のところは\\nこのくらいにしておいてあげましょう。"

# ゆんゆん
# 次こそは、絶対に勝ってみせるんだから！
401 = "次こそは、絶対に勝ってみせるんだから！"

# めぐみん
# 何度挑もうが無駄ですよ。\n結果は見えています。
388 = "何度挑もうが無駄ですよ。\\n結果は見えています。"

# ダクネス
# うむ、元の鞘に収まったようだな。\nカズマ、やるじゃないか。
326 = "うむ、元の鞘に収まったようだな。\\nカズマ、やるじゃないか。"

# カズマ
# な、なんのことだよ。
357 = "な、なんのことだよ。"

# ダクネス
# ふふふ、照れることはない。\nちゃんとわかっているからな。
364 = "ふふふ、照れることはない。\\nちゃんとわかっているからな。"

# アクア
# 待ちなさいよっ！\nなんでめぐみんの勝ちなのよ！\nもっと私を甘やかしてよぉ～！！
397 = "待ちなさいよっ！\\nなんでめぐみんの勝ちなのよ！\\nもっと私を甘やかしてよぉ～！！"

