# root_b06.txt.scn

[info]
0 = ""

[characters]
262 = "カズマ"
257 = "めぐみん"
263 = "カズマ（Ｍ）"

[character_subs]
# 262 = "カズマ"

[script]
# lines: 64

# カズマ
# ダメだ、この窓も開かない。\nそっちはどうだ？
264 = "ダメだ、この窓も開かない。\\nそっちはどうだ？"

# めぐみん
# こっちもです！\nビクともしません！
232 = "こっちもです！\\nビクともしません！"

# カズマ（Ｍ）
# display as カズマ
# （どういうことだ？\n　どれもこれも、嵌め殺しじゃないのに\n　開く気配がまるでない）
310 = "（どういうことだ？\\n　どれもこれも、嵌め殺しじゃないのに\\n　開く気配がまるでない）"

# カズマ
# 一体どうなってるんだ？\nまさか本当に呪いの仕業なのか？
266 = "一体どうなってるんだ？\\nまさか本当に呪いの仕業なのか？"

# めぐみん
# やっぱり閉じ込められたのですか！？\nどうするのですか！？\nいえ、どうなるのですか！？
260 = "やっぱり閉じ込められたのですか！？\\nどうするのですか！？\\nいえ、どうなるのですか！？"

# カズマ
# 開かないなら壊せばいいだろ。\nそこにある椅子をぶつけて、窓を割って脱出するぞ。
304 = "開かないなら壊せばいいだろ。\\nそこにある椅子をぶつけて、窓を割って脱出するぞ。"

# めぐみん
# そ、そんな！\nここは教会ですよ？\nエリス様の罰が下ります！
235 = "そ、そんな！\\nここは教会ですよ？\\nエリス様の罰が下ります！"

# カズマ
# そんなこと言ってる場合じゃないだろ！\nこのままじゃ罰より先に呪いにやられかねないんだ。
240 = "そんなこと言ってる場合じゃないだろ！\\nこのままじゃ罰より先に呪いにやられかねないんだ。"

# めぐみん
# う……。\nそれはそうですが、でも……。
223 = "う……。\\nそれはそうですが、でも……。"

# カズマ
# 危ないから離れてろ。
271 = "危ないから離れてろ。"

# めぐみん
# は、はい。
254 = "は、はい。"

# カズマ
# いくぞ！\nおりゃあああっ！
221 = "いくぞ！\\nおりゃあああっ！"

# カズマ
# ぐあっ！？
231 = "ぐあっ！？"

# カズマ（Ｍ）
# display as カズマ
# （あ、あっぶねぇ！\n　椅子が跳ね返ってきた！？）
305 = "（あ、あっぶねぇ！\\n　椅子が跳ね返ってきた！？）"

# めぐみん
# か、カズマ？\n今のはどういうことですか？\n窓が椅子を跳ね返しましたよ？
229 = "か、カズマ？\\n今のはどういうことですか？\\n窓が椅子を跳ね返しましたよ？"

# カズマ
# ……わからん。\nわからんが、どうやら窓を破るのも無理そうだな。\nとてもじゃないが壊せる気がしない。
218 = "……わからん。\\nわからんが、どうやら窓を破るのも無理そうだな。\\nとてもじゃないが壊せる気がしない。"

# カズマ
# 参ったぜ。\nこれはマジで閉じ込められちまったみたいだ。
272 = "参ったぜ。\\nこれはマジで閉じ込められちまったみたいだ。"

# めぐみん
# そ、そんなっ！　なんとかしてくださいよ！\nもとはと言えば、カズマが考えもなしに\n中に入ったのがいけないんですから！
234 = "そ、そんなっ！　なんとかしてくださいよ！\\nもとはと言えば、カズマが考えもなしに\\n中に入ったのがいけないんですから！"

# カズマ
# なんとかしろって言われてもなぁ。
253 = "なんとかしろって言われてもなぁ。"

# めぐみん
# お願いですから、\nここから出してください……。
228 = "お願いですから、\\nここから出してください……。"

# めぐみん
# もしこのまま出られなかったら\n一生、恨みますからね？
259 = "もしこのまま出られなかったら\\n一生、恨みますからね？"

# カズマ
# めぐみん、とりあえず落ち着け。\nこういうときこそ冷静になるんだ。
258 = "めぐみん、とりあえず落ち着け。\\nこういうときこそ冷静になるんだ。"

# めぐみん
# 冷静でいられるはずありません。\nなんとかしてください、\n本当に、お願いしますから……。
270 = "冷静でいられるはずありません。\\nなんとかしてください、\\n本当に、お願いしますから……。"

# カズマ（Ｍ）
# display as カズマ
# （予想以上に怯えてるな、\n　少し驚かせすぎたか？）
311 = "（予想以上に怯えてるな、\\n　少し驚かせすぎたか？）"

# カズマ（Ｍ）
# display as カズマ
# （だけど確かに、この状況は不安にもなる。\n　なんとかして脱出しないと）
309 = "（だけど確かに、この状況は不安にもなる。\\n　なんとかして脱出しないと）"

# めぐみん
# カ、カズマぁぁぁっ！
261 = "カ、カズマぁぁぁっ！"

# カズマ
# うおおっ！？\nこ、今度はなんだよ！
224 = "うおおっ！？\\nこ、今度はなんだよ！"

# めぐみん
# あ、あれ……。\n壁を……壁を……見てください……。
220 = "あ、あれ……。\\n壁を……壁を……見てください……。"

# カズマ
# なっ！？　血文字！？
252 = "なっ！？　血文字！？"

# めぐみん
# さ、ささ、さ、さっきまであんな文字は\nありませんでしたよ！
233 = "さ、ささ、さ、さっきまであんな文字は\\nありませんでしたよ！"

# カズマ
# おおおお、落ち着けってぇ！\nとりあえず、なんて書いてあるか確認だ！\nええと……。
225 = "おおおお、落ち着けってぇ！\\nとりあえず、なんて書いてあるか確認だ！\\nええと……。"

# カズマ
# 『ここで結婚式をしないと呪いは解けない』
219 = "『ここで結婚式をしないと呪いは解けない』"

# めぐみん
# は？
255 = "は？"

# カズマ
# ふむ……結婚。
256 = "ふむ……結婚。"

# めぐみん
# ちょっと、どうして私を見るのです。
246 = "ちょっと、どうして私を見るのです。"

# カズマ
# 俺、男。\nお前、女。
269 = "俺、男。\\nお前、女。"

# めぐみん
# だからなんなんです。
243 = "だからなんなんです。"

# カズマ
# 結婚、異性としかできない。
301 = "結婚、異性としかできない。"

# めぐみん
# その口調はやめてください。\n蹴り飛ばしたくなります。
237 = "その口調はやめてください。\\n蹴り飛ばしたくなります。"

# カズマ
# いやでもさ、簡単で良かったじゃないか。\nこれならアクアに頼るまでもないし。
222 = "いやでもさ、簡単で良かったじゃないか。\\nこれならアクアに頼るまでもないし。"

# めぐみん
# ちょっと待ってください！\n何が簡単だと言うんです！？
247 = "ちょっと待ってください！\\n何が簡単だと言うんです！？"

# カズマ
# 男と女が揃ってるんだから\n結婚式を挙げるなんて簡単だろ？
279 = "男と女が揃ってるんだから\\n結婚式を挙げるなんて簡単だろ？"

# めぐみん
# それってまさか、\n私とカズマのことを言っているんじゃない\nでしょうね？
238 = "それってまさか、\\n私とカズマのことを言っているんじゃない\\nでしょうね？"

# カズマ
# 他に誰がいるんだよ。\nほら、さっさと結婚しようぜ。
268 = "他に誰がいるんだよ。\\nほら、さっさと結婚しようぜ。"

# めぐみん
# な、な、何を言い出すんですか！\n冗談じゃありませんよ！
251 = "な、な、何を言い出すんですか！\\n冗談じゃありませんよ！"

# めぐみん
# どうして、私がカズマと\n結婚なんてしなくちゃいけないんですか！\nそんな真似するくらいなら、甘んじて呪われます！
250 = "どうして、私がカズマと\\n結婚なんてしなくちゃいけないんですか！\\nそんな真似するくらいなら、甘んじて呪われます！"

# カズマ
# そこまで言うか！？
236 = "そこまで言うか！？"

# めぐみん
# 結婚だなんて、軽々しく使っていい言葉では……。\nまだ告白だってされていないというのに……。
302 = "結婚だなんて、軽々しく使っていい言葉では……。\\nまだ告白だってされていないというのに……。"

# めぐみん
# と、とにかくあり得ません！\n絶対に絶対に！　あり得ませんっ！
249 = "と、とにかくあり得ません！\\n絶対に絶対に！　あり得ませんっ！"

# カズマ
# だから落ち着けって。\n本気で結婚するわけないだろ？\nフリだよフリ、フリをするだけだって。
244 = "だから落ち着けって。\\n本気で結婚するわけないだろ？\\nフリだよフリ、フリをするだけだって。"

# カズマ
# それで呪いは解けて俺達は出られる。\n何を迷う必要があるんだ。
239 = "それで呪いは解けて俺達は出られる。\\n何を迷う必要があるんだ。"

# めぐみん
# お断りします！\nフリとはいえ結婚なんて！\nカズマは結婚を軽んじていますっ！
227 = "お断りします！\\nフリとはいえ結婚なんて！\\nカズマは結婚を軽んじていますっ！"

# めぐみん
# たとえフリでも、女性にとって\n結婚は重大なことなんです！
241 = "たとえフリでも、女性にとって\\n結婚は重大なことなんです！"

# カズマ（Ｍ）
# display as カズマ
# （そういうもんなのか？\n　男の俺にはわからんが、この状況で\n　そこまで深刻に考えるようなことなのか？）
307 = "（そういうもんなのか？\\n　男の俺にはわからんが、この状況で\\n　そこまで深刻に考えるようなことなのか？）"

# カズマ
# だけどさぁ、それじゃ\nいつまで経っても状況は変わらないぞ？\nここから出たくないのか？
245 = "だけどさぁ、それじゃ\\nいつまで経っても状況は変わらないぞ？\\nここから出たくないのか？"

# めぐみん
# ……そうだ、そうですよ。\nそんな回りくどいことする必要なんかありません。
217 = "……そうだ、そうですよ。\\nそんな回りくどいことする必要なんかありません。"

# めぐみん
# 呪いなど、\n教会ごと破壊してしまいましょう！
276 = "呪いなど、\\n教会ごと破壊してしまいましょう！"

# カズマ
# お前は本当に一回冷静になれ。\nだいたい、魔力がすっからかんなんだから\n爆裂魔法は撃てないだろう。
226 = "お前は本当に一回冷静になれ。\\nだいたい、魔力がすっからかんなんだから\\n爆裂魔法は撃てないだろう。"

# めぐみん
# くっ……！\nこんなことなら\n魔力を温存しておくべきでした。
230 = "くっ……！\\nこんなことなら\\n魔力を温存しておくべきでした。"

# カズマ（Ｍ）
# display as カズマ
# （そう言ったのは俺だが、今回ばかりは\n　むしろ使ってくれてて助かったな）
308 = "（そう言ったのは俺だが、今回ばかりは\\n　むしろ使ってくれてて助かったな）"

# めぐみん
# で、でも、じゃあ、\nどうしろって言うんですか？
248 = "で、でも、じゃあ、\\nどうしろって言うんですか？"

# カズマ
# だから、結婚式をすればいいんだろ。
242 = "だから、結婚式をすればいいんだろ。"

# めぐみん
# 絶対に嫌です！\n断固、お断りします！
303 = "絶対に嫌です！\\n断固、お断りします！"

# カズマ（Ｍ）
# display as カズマ
# （おいおい……。\n　これはそう簡単に頷いてくれそうにないぞ。\n　どうしたらいいんだ？）
306 = "（おいおい……。\\n　これはそう簡単に頷いてくれそうにないぞ。\\n　どうしたらいいんだ？）"

