# root_e16.txt.scn

[info]
0 = ""

[characters]
283 = "ダクネス"
281 = "カズマ（Ｍ）"
273 = "めぐみん"
282 = "クリス"
279 = "ウィズ"
276 = "ゆんゆん"
278 = "アクア"
280 = "カズマ"

[character_subs]
# 280 = "カズマ"

[script]
# lines: 55

# ダクネス
# さて、では、勝負について説明しよう。
251 = "さて、では、勝負について説明しよう。"

# ダクネス
# 魔法使いと言えば、\nパーティーには欠かせない火力だ。\n当然、それなりの攻撃力が求められる。
330 = "魔法使いと言えば、\\nパーティーには欠かせない火力だ。\\n当然、それなりの攻撃力が求められる。"

# ダクネス
# ２人には、ここでそれを示してもらいたい。
335 = "２人には、ここでそれを示してもらいたい。"

# カズマ（Ｍ）
# display as カズマ
# （おっ？\n　思いの外、まともなことを言い出したぞ？）
331 = "（おっ？\\n　思いの外、まともなことを言い出したぞ？）"

# めぐみん
# 火力ですか。\n具体的に何をすればいいのです？
294 = "火力ですか。\\n具体的に何をすればいいのです？"

# ダクネス
# 簡単だ。\n私に膝をつかせるだけでいい。
328 = "簡単だ。\\n私に膝をつかせるだけでいい。"

# クリス
# ああ、なるほどね。\nダクネスの固さは折り紙付き、\n非力な魔法使いが殴ったところでビクともしない。
240 = "ああ、なるほどね。\\nダクネスの固さは折り紙付き、\\n非力な魔法使いが殴ったところでビクともしない。"

# ウィズ
# つまり、強力な魔法で打ち倒せということですか。
261 = "つまり、強力な魔法で打ち倒せということですか。"

# ダクネス
# その通り！\n自慢の魔法を私に放ち、膝をつかせてみろ！
256 = "その通り！\\n自慢の魔法を私に放ち、膝をつかせてみろ！"

# ゆんゆん
# あの、魔法なら、サラダ退治の時に\n何度も放ってますけど。
242 = "あの、魔法なら、サラダ退治の時に\\n何度も放ってますけど。"

# ダクネス
# 何を言う！\nゆんゆんの実力はあの程度ではないだろう！\nここで実力の全てを見せて欲しい！
286 = "何を言う！\\nゆんゆんの実力はあの程度ではないだろう！\\nここで実力の全てを見せて欲しい！"

# ダクネス
# 例え、どのような強力な魔法を放たれようと\n私は簡単に屈したりはしない！
287 = "例え、どのような強力な魔法を放たれようと\\n私は簡単に屈したりはしない！"

# ダクネス
# だから遠慮なく、本気の魔法を撃ち込むがいい！\nさあ！　さあ！　さあ！
259 = "だから遠慮なく、本気の魔法を撃ち込むがいい！\\nさあ！　さあ！　さあ！"

# カズマ（Ｍ）
# display as カズマ
# （それが狙いかよ！？\n　やっぱりまともじゃなかった！\n　一瞬でも感心した俺の気持ちを返せ！！）
333 = "（それが狙いかよ！？\\n　やっぱりまともじゃなかった！\\n　一瞬でも感心した俺の気持ちを返せ！！）"

# ゆんゆん
# ほ、本当にいいんですか？
268 = "ほ、本当にいいんですか？"

# ダクネス
# 私の頑丈さはゆんゆんも知っているだろう？\n全力でこい！
327 = "私の頑丈さはゆんゆんも知っているだろう？\\n全力でこい！"

# ゆんゆん
# わ、わかりました！\nいきます！
277 = "わ、わかりました！\\nいきます！"

# ダクネス
# ああああぁぁぁぁぁ！\nこ、これだ！　この全身を駆け巡る電撃！
241 = "ああああぁぁぁぁぁ！\\nこ、これだ！　この全身を駆け巡る電撃！"

# ダクネス
# な、なんて心地いいんだ……！\nさあ、もっとだ！　私は膝をついていないぞ！
265 = "な、なんて心地いいんだ……！\\nさあ、もっとだ！　私は膝をついていないぞ！"

# ゆんゆん
# は、はい、やあああああ！
266 = "は、はい、やあああああ！"

# ダクネス
# くぉぉぉぉぉぉ！！\nこの身を焦がすほどの灼熱に、\n火照りが止まらない！！
249 = "くぉぉぉぉぉぉ！！\\nこの身を焦がすほどの灼熱に、\\n火照りが止まらない！！"

# ダクネス
# はぁはぁはぁ……、\nやはりいい……この刺激堪らないぞ！！
267 = "はぁはぁはぁ……、\\nやはりいい……この刺激堪らないぞ！！"

# ダクネス
# まだだ……まだまだだ！\nこんなものか！？
269 = "まだだ……まだまだだ！\\nこんなものか！？"

# ゆんゆん
# そ、それじゃ、これならどうですか！？\nライト・オブ・セイバー！
253 = "そ、それじゃ、これならどうですか！？\\nライト・オブ・セイバー！"

# ダクネス
# うわぁぁぁっ！！
244 = "うわぁぁぁっ！！"

# ゆんゆん
# だ、ダクネスさん！？
258 = "だ、ダクネスさん！？"

# ダクネス
# い、今のはなかなか利いたぞ……。\nだが、まだ物足りない！
243 = "い、今のはなかなか利いたぞ……。\\nだが、まだ物足りない！"

# ダクネス
# もっと撃ち込んでこい！\nもっと私を激しくなぶれ！\nさあ！　さあ！　さあ！
275 = "もっと撃ち込んでこい！\\nもっと私を激しくなぶれ！\\nさあ！　さあ！　さあ！"

# ゆんゆん
# え。ええと……。
245 = "え。ええと……。"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆん、思いっきり引いてるな）
334 = "（ゆんゆん、思いっきり引いてるな）"

# アクア
# めぐみんはどうしたの？\nまったく魔法を使おうとしてないわよ？
274 = "めぐみんはどうしたの？\\nまったく魔法を使おうとしてないわよ？"

# カズマ（Ｍ）
# display as カズマ
# （そういやそうだな。\n　もしかして、ゆんゆんが力尽きたところで\n　派手に決めるとか考えてるのか？）
332 = "（そういやそうだな。\\n　もしかして、ゆんゆんが力尽きたところで\\n　派手に決めるとか考えてるのか？）"

# アクア
# ちょっと、めぐみん？\nこのままじゃ、ゆんゆんがダクネスを\n倒しちゃうかもしれないわよ？
260 = "ちょっと、めぐみん？\\nこのままじゃ、ゆんゆんがダクネスを\\n倒しちゃうかもしれないわよ？"

# めぐみん
# ……我が爆裂魔法は、最強にして至高。\n並ぶものなき究極の魔法。\n私は、爆裂魔法を心の底から愛しています。
238 = "……我が爆裂魔法は、最強にして至高。\\n並ぶものなき究極の魔法。\\n私は、爆裂魔法を心の底から愛しています。"

# めぐみん
# それをこんなくだらないことに使うなど……\n私の矜持が許しません。
257 = "それをこんなくだらないことに使うなど……\\n私の矜持が許しません。"

# カズマ
# お前、いつもなにもない平原や岩に\n考え無しに撃ち込んでるじゃないか。\n何が違うって言うんだ？
248 = "お前、いつもなにもない平原や岩に\\n考え無しに撃ち込んでるじゃないか。\\n何が違うって言うんだ？"

# めぐみん
# まったく違います。\nカズマにはわからないのですか？
271 = "まったく違います。\\nカズマにはわからないのですか？"

# カズマ
# まったくわからん！
270 = "まったくわからん！"

# めぐみん
# そうですか。\nいいです、別にわかってもらおうとは\n思っていませんから。
254 = "そうですか。\\nいいです、別にわかってもらおうとは\\n思っていませんから。"

# めぐみん
# とにかく、ここで爆裂魔法は絶対に撃ちません。
264 = "とにかく、ここで爆裂魔法は絶対に撃ちません。"

# ウィズ
# ですが、それでは\nめぐみんさんの負けになってしまいますよ？
263 = "ですが、それでは\\nめぐみんさんの負けになってしまいますよ？"

# めぐみん
# 構いません。\n勝負よりも己のプライドの方が大事です。
293 = "構いません。\\n勝負よりも己のプライドの方が大事です。"

# ゆんゆん
# め、めぐみん……。
272 = "め、めぐみん……。"

# アクア
# えっと、それじゃ、\nこの勝負はゆんゆんの勝ちでいいのね？
247 = "えっと、それじゃ、\\nこの勝負はゆんゆんの勝ちでいいのね？"

# ダクネス
# 何っ！？\nもう終わってしまうのか？\n私はまだいけるぞ！
285 = "何っ！？\\nもう終わってしまうのか？\\n私はまだいけるぞ！"

# カズマ
# 終わりだ、終わり！\nゆんゆんの勝利！
329 = "終わりだ、終わり！\\nゆんゆんの勝利！"

# ウィズ
# ですが、こうなると\nゆんゆんさんが２本先取したことに\nなりますから……。
262 = "ですが、こうなると\\nゆんゆんさんが２本先取したことに\\nなりますから……。"

# アクア
# じゃあ、うちの魔法使いは\nゆんゆんで決定ってこと？
252 = "じゃあ、うちの魔法使いは\\nゆんゆんで決定ってこと？"

# ゆんゆん
# あ……。
239 = "あ……。"

# めぐみん
# …………。
236 = "…………。"

# カズマ
# そう結論を急ぐなって。\n勝負はまだついていないんだからな。
255 = "そう結論を急ぐなって。\\n勝負はまだついていないんだからな。"

# めぐみん
# ……どういうことですか？
237 = "……どういうことですか？"

# カズマ
# 最終対決は、なんと２倍のポイントゲット！\nこれで勝負の行方はわからなくなったぁ！
292 = "最終対決は、なんと２倍のポイントゲット！\\nこれで勝負の行方はわからなくなったぁ！"

# クリス
# ええ？\nじゃあ、今までの対決はなんだったの？
246 = "ええ？\\nじゃあ、今までの対決はなんだったの？"

# カズマ
# こういうのはお約束なんだよ！\nとにかく、最終対決だっ！
250 = "こういうのはお約束なんだよ！\\nとにかく、最終対決だっ！"

