# root_d26.txt.scn

[info]
0 = ""

[characters]
250 = "クリス"
248 = "カズマ"
249 = "カズマ（Ｍ）"

[character_subs]
# 248 = "カズマ"

[script]
# lines: 60

# クリス
# このお店で買う物は、これで終わりかな。\n新しい装備は揃えたし、\n薬草や砥石なんかも買ったし……。
223 = "このお店で買う物は、これで終わりかな。\\n新しい装備は揃えたし、\\n薬草や砥石なんかも買ったし……。"

# クリス
# あっ、そうだ。\nランプオイルもあと少しで\nなくなりそうだったんだっけ。
213 = "あっ、そうだ。\\nランプオイルもあと少しで\\nなくなりそうだったんだっけ。"

# カズマ
# なぁ、クリス？\nもうかなりの量を買ってると思うんだが、\nどんだけ買うつもりなんだよ。
237 = "なぁ、クリス？\\nもうかなりの量を買ってると思うんだが、\\nどんだけ買うつもりなんだよ。"

# クリス
# これくらい、まだまだ序の口！\nせっかくカズマが買い出しに付き合って\nくれるんだから、このチャンスを活用しなくちゃ。
225 = "これくらい、まだまだ序の口！\\nせっかくカズマが買い出しに付き合って\\nくれるんだから、このチャンスを活用しなくちゃ。"

# カズマ
# 確かに、買い出しに付き合うとは言った、\n言ったけどな？\nこれ、どう考えてもただの荷物持ちだよな？
290 = "確かに、買い出しに付き合うとは言った、\\n言ったけどな？\\nこれ、どう考えてもただの荷物持ちだよな？"

# クリス
# 嫌なの？\nあたしにあんな恥ずかしいことさせたくせに。
259 = "嫌なの？\\nあたしにあんな恥ずかしいことさせたくせに。"

# カズマ
# いえ、そんなことはございません！\n誠心誠意、荷物持ちをさせていただきます！
217 = "いえ、そんなことはございません！\\n誠心誠意、荷物持ちをさせていただきます！"

# カズマ（Ｍ）
# display as カズマ
# （くうう……。\n　パンツの件があるから強く出れない……）
296 = "（くうう……。\\n　パンツの件があるから強く出れない……）"

# クリス
# そうそう、保存食も買いに行かなくちゃ。\n消耗品系のストックが切れかけてるんだよね。\nえーっと、あと他に必要な物は……。
229 = "そうそう、保存食も買いに行かなくちゃ。\\n消耗品系のストックが切れかけてるんだよね。\\nえーっと、あと他に必要な物は……。"

# カズマ
# ストップ、ストーーップ！！\nちょっと待てクリス、\nホントどんだけ買うつもりなんだよ。
251 = "ストップ、ストーーップ！！\\nちょっと待てクリス、\\nホントどんだけ買うつもりなんだよ。"

# クリス
# 欲しい物がたくさんあるんだよ。\n普段、こんな風にまとめて買い込むなんて\nできないから。
263 = "欲しい物がたくさんあるんだよ。\\n普段、こんな風にまとめて買い込むなんて\\nできないから。"

# クリス
# 今日はキミっていう荷物持ちを\n思いっきり利用させてもらうよ？
255 = "今日はキミっていう荷物持ちを\\n思いっきり利用させてもらうよ？"

# カズマ
# 容赦ねーなぁ……。
261 = "容赦ねーなぁ……。"

# クリス
# これくらいで根を上げないの。\n男の子でしょ。
226 = "これくらいで根を上げないの。\\n男の子でしょ。"

# カズマ
# はぁ、わかった、付き合う、付き合うから……\nちょっと休憩しないか？
240 = "はぁ、わかった、付き合う、付き合うから……\\nちょっと休憩しないか？"

# カズマ
# さすがに、これ以上持つのは物理的に無理だし、\n一旦休憩して、今ある荷物を運んでから\nもう一度買いに行こう。
227 = "さすがに、これ以上持つのは物理的に無理だし、\\n一旦休憩して、今ある荷物を運んでから\\nもう一度買いに行こう。"

# クリス
# そうだね、そろそろ小腹も空いてきたし……\n休憩にしようか。
231 = "そうだね、そろそろ小腹も空いてきたし……\\n休憩にしようか。"

# カズマ（Ｍ）
# display as カズマ
# （良かった。\n　これ以上、何か持たされたら\n　俺が潰れるところだった）
300 = "（良かった。\\n　これ以上、何か持たされたら\\n　俺が潰れるところだった）"

# クリス
# 実はね、食べたい物があるんだよね。
260 = "実はね、食べたい物があるんだよね。"

# カズマ
# 食べたい物って、こんなところで？\nいつもの酒場じゃ食えないのか？
291 = "食べたい物って、こんなところで？\\nいつもの酒場じゃ食えないのか？"

# クリス
# あそこの料理も美味しいから好きなんだけどね。\nあたしが食べたいのは、そういうのじゃないんだ。
212 = "あそこの料理も美味しいから好きなんだけどね。\\nあたしが食べたいのは、そういうのじゃないんだ。"

# クリス
# えっと……。
221 = "えっと……。"

# クリス
# あ、あった！\nこれだよ、これ！
209 = "あ、あった！\\nこれだよ、これ！"

# クリス
# 前から食べてみたかったんだけど、\nこのお店、営業時間が限られてるから\nなかなか食べに来られなかったんだ。
256 = "前から食べてみたかったんだけど、\\nこのお店、営業時間が限られてるから\\nなかなか食べに来られなかったんだ。"

# カズマ（Ｍ）
# display as カズマ
# （薄く焼いた生地の上に果物やクリーム、\n　カスタード、ソースを載せて……\n　ってこれ、クレープみたいなもんか？）
301 = "（薄く焼いた生地の上に果物やクリーム、\\n　カスタード、ソースを載せて……\\n　ってこれ、クレープみたいなもんか？）"

# クリス
# うーん、どれにしよう？\n種類がたくさんあって悩んじゃうなぁ。
220 = "うーん、どれにしよう？\\n種類がたくさんあって悩んじゃうなぁ。"

# カズマ（Ｍ）
# display as カズマ
# （……クリスって、どちらかと言うと\n　酒好きなイメージがあったけど、\n　こういう女の子らしい物が好きなんだな）
294 = "（……クリスって、どちらかと言うと\\n　酒好きなイメージがあったけど、\\n　こういう女の子らしい物が好きなんだな）"

# カズマ（Ｍ）
# display as カズマ
# （それに、悩んでる顔も\n　普通の女の子みたいだし……）
299 = "（それに、悩んでる顔も\\n　普通の女の子みたいだし……）"

# クリス
# どれも美味しそうだなぁ。\nダメ、決められないや。
236 = "どれも美味しそうだなぁ。\\nダメ、決められないや。"

# クリス
# ねぇ、カズマ。\nあたしじゃあ決められないから、キミが決めてよ。
239 = "ねぇ、カズマ。\\nあたしじゃあ決められないから、キミが決めてよ。"

# カズマ
# いいのか？
216 = "いいのか？"

# クリス
# だって、キミが決めた物なら\nどんな味でも諦めがつくでしょ。
234 = "だって、キミが決めた物なら\\nどんな味でも諦めがつくでしょ。"

# カズマ
# なんじゃそりゃ。\nまあ、それなら向こうで待ってろよ。\n持ってくから。
238 = "なんじゃそりゃ。\\nまあ、それなら向こうで待ってろよ。\\n持ってくから。"

# クリス
# うん、お願い。
218 = "うん、お願い。"

# カズマ
# ほい、お待たせ。\n甘いやつで良かったんだよな？
243 = "ほい、お待たせ。\\n甘いやつで良かったんだよな？"

# クリス
# わぁ、ありがとう！\nいただきまーす。
246 = "わぁ、ありがとう！\\nいただきまーす。"

# クリス
# はむ、はむはむ……うーん、美味しい！\n甘くって冷たくって、でも温かくて。\nこれ、中にアイスクリームも入ってるのかな？
241 = "はむ、はむはむ……うーん、美味しい！\\n甘くって冷たくって、でも温かくて。\\nこれ、中にアイスクリームも入ってるのかな？"

# カズマ
# ああ、初めて食べるなら\n生クリームとカスタードが王道かと思ったけど、\nトッピングにおススメって書いてあったからさ。
211 = "ああ、初めて食べるなら\\n生クリームとカスタードが王道かと思ったけど、\\nトッピングにおススメって書いてあったからさ。"

# クリス
# そうなんだ。\nキミがこういう物よく知ってるって意外かも。\n甘い物、よく食べるの？
232 = "そうなんだ。\\nキミがこういう物よく知ってるって意外かも。\\n甘い物、よく食べるの？"

# カズマ
# そういうわけじゃないけど、\n俺の地元っていうか故郷じゃ\n結構メジャーな食べ物だったからな。
228 = "そういうわけじゃないけど、\\n俺の地元っていうか故郷じゃ\\n結構メジャーな食べ物だったからな。"

# カズマ（Ｍ）
# display as カズマ
# （食ったことなんて、\n　片手で数えるくらいしかないけど）
302 = "（食ったことなんて、\\n　片手で数えるくらいしかないけど）"

# クリス
# へぇ、そうだったんだ。\nあたしの地元には\nこういうお菓子ってなかったんだよね。
242 = "へぇ、そうだったんだ。\\nあたしの地元には\\nこういうお菓子ってなかったんだよね。"

# クリス
# だから１度食べてみたいなって思ってたんだ。\nふふ、想像してた以上に、とっても美味しいや。
233 = "だから１度食べてみたいなって思ってたんだ。\\nふふ、想像してた以上に、とっても美味しいや。"

# クリス
# 甘い物食べて、のんびりして……。\nたまには、こういう日もいいもんだね。
264 = "甘い物食べて、のんびりして……。\\nたまには、こういう日もいいもんだね。"

# カズマ
# そうだなぁ。\n最近、色々忙しかったし。
230 = "そうだなぁ。\\n最近、色々忙しかったし。"

# カズマ（Ｍ）
# display as カズマ
# （……あ、そういえば\n　クレープの代金、もらってないな）
292 = "（……あ、そういえば\\n　クレープの代金、もらってないな）"

# カズマ（Ｍ）
# display as カズマ
# （けど、なんだかすごく嬉しそうだし……\n　ここで言うのも無粋ってもんか）
297 = "（けど、なんだかすごく嬉しそうだし……\\n　ここで言うのも無粋ってもんか）"

# カズマ（Ｍ）
# display as カズマ
# （それに、クレープくらいで\n　これだけ喜んでくれるなら\n　奢るのも悪くないよな？）
298 = "（それに、クレープくらいで\\n　これだけ喜んでくれるなら\\n　奢るのも悪くないよな？）"

# クリス
# あー、美味しかった。\n次はどれを食べようかなー。
215 = "あー、美味しかった。\\n次はどれを食べようかなー。"

# カズマ
# まだ食べるのか！？
245 = "まだ食べるのか！？"

# クリス
# うん、だってとっても美味しかったんだもん。\nさっきはチョコ系だったから、\n次はイチゴ系でもいいよね。
219 = "うん、だってとっても美味しかったんだもん。\\nさっきはチョコ系だったから、\\n次はイチゴ系でもいいよね。"

# クリス
# あ、でも、甘くないやつもあるんだ。\nこっちも気になるなぁ。
210 = "あ、でも、甘くないやつもあるんだ。\\nこっちも気になるなぁ。"

# クリス
# どうしよう、\nいっそのこと両方頼んじゃおうかな。\nねぇ、どう思うカズマ？
235 = "どうしよう、\\nいっそのこと両方頼んじゃおうかな。\\nねぇ、どう思うカズマ？"

# カズマ（Ｍ）
# display as カズマ
# （……やばい、この流れは\n　俺の財布が空になるフラグ！）
293 = "（……やばい、この流れは\\n　俺の財布が空になるフラグ！）"

# カズマ
# あー、その、なんだ！\n一気に食べるのは\nあまり良くないんじゃないか？
214 = "あー、その、なんだ！\\n一気に食べるのは\\nあまり良くないんじゃないか？"

# カズマ
# この店だって期間限定ってわけじゃないんだし、\nまた次の機会でもいいんじゃないか？\nその方が長く楽しめるだろ？
224 = "この店だって期間限定ってわけじゃないんだし、\\nまた次の機会でもいいんじゃないか？\\nその方が長く楽しめるだろ？"

# クリス
# ん？\nそれって、もしかしてあたしを\nデートに誘ってるのかな？
247 = "ん？\\nそれって、もしかしてあたしを\\nデートに誘ってるのかな？"

# カズマ
# えっ？
222 = "えっ？"

# カズマ（Ｍ）
# display as カズマ
# （あれ？　今、そういう流れだったか？\n　いや、でも女の子を誘うのは……あれ？）
295 = "（あれ？　今、そういう流れだったか？\\n　いや、でも女の子を誘うのは……あれ？）"

# クリス
# まぁ、いいや。\nそういうことなら他の味は次に取っておこうかな。\n……楽しみにしてるからね、カズマ。
244 = "まぁ、いいや。\\nそういうことなら他の味は次に取っておこうかな。\\n……楽しみにしてるからね、カズマ。"

