# root_f01.txt.scn

[info]
0 = ""

[characters]
190 = "カズマ（Ｍ）"
189 = "カズマ"
191 = "クリス"

[character_subs]
# 189 = "カズマ"

[script]
# lines: 26

# カズマ（Ｍ）
# display as カズマ
# （スカルドラゴン討伐、\n　そして俺の呪われた指輪の事件が\n　解決してから数日）
214 = "（スカルドラゴン討伐、\\n　そして俺の呪われた指輪の事件が\\n　解決してから数日）"

# カズマ（Ｍ）
# display as カズマ
# （俺は、呪いから解放された\n　喜びを噛み締めつつも、\n　とある行動に勤しんでいた）
215 = "（俺は、呪いから解放された\\n　喜びを噛み締めつつも、\\n　とある行動に勤しんでいた）"

# カズマ
# まあ、そんなわけでさ。\nドラゴン討伐の時には、\nクリスにも世話になったわけだから――
187 = "まあ、そんなわけでさ。\\nドラゴン討伐の時には、\\nクリスにも世話になったわけだから――"

# カズマ
# お詫びさせてくれ、頼む！
175 = "お詫びさせてくれ、頼む！"

# クリス
# お詫びなんて、そんなのいらないよ？
176 = "お詫びなんて、そんなのいらないよ？"

# カズマ
# いや！\n今回ばかりは受けた恩が大きすぎる。\nその借りを返さないなんて、男がすたる！
170 = "いや！\\n今回ばかりは受けた恩が大きすぎる。\\nその借りを返さないなんて、男がすたる！"

# クリス
# ねえ、もしかして\n他の人たちにもお詫びして回ってるの？
182 = "ねえ、もしかして\\n他の人たちにもお詫びして回ってるの？"

# カズマ
# ああ、まあな。\nゆんゆんには甘い物をおごったし、\nギルドのお姉さんにもちゃんと謝った。
168 = "ああ、まあな。\\nゆんゆんには甘い物をおごったし、\\nギルドのお姉さんにもちゃんと謝った。"

# カズマ
# まあ、うちの３人はいつも迷惑をかけられて\nいるから何もしなくていいとしてだ。
186 = "まあ、うちの３人はいつも迷惑をかけられて\\nいるから何もしなくていいとしてだ。"

# カズマ
# 後は、ウィズだ。
195 = "後は、ウィズだ。"

# クリス
# へえ……。\nキミ、意外に律儀だねぇ。\nそこまですることないと思うよ？
183 = "へえ……。\\nキミ、意外に律儀だねぇ。\\nそこまですることないと思うよ？"

# クリス
# みんな、無理矢理手伝わされたわけでもないし、\nキミが呪いで大変だったのはわかってるしさ。
188 = "みんな、無理矢理手伝わされたわけでもないし、\\nキミが呪いで大変だったのはわかってるしさ。"

# カズマ
# けど、今回は俺が迷惑の中心だったし、\nそれなりに責任も感じてるんだよ。
177 = "けど、今回は俺が迷惑の中心だったし、\\nそれなりに責任も感じてるんだよ。"

# クリス
# うーん、反省する気持ちはいいんだけど、\nやり方の方向が間違ってるような……。
172 = "うーん、反省する気持ちはいいんだけど、\\nやり方の方向が間違ってるような……。"

# カズマ
# そうなのか？
179 = "そうなのか？"

# クリス
# とにかく、あたしはいいよ。
181 = "とにかく、あたしはいいよ。"

# カズマ
# そうはいかないって。
180 = "そうはいかないって。"

# クリス
# じゃあ、こうしようか。\nもしあたしに困り事が発生したら、\nその時は無償で助けてくれる、どう？
178 = "じゃあ、こうしようか。\\nもしあたしに困り事が発生したら、\\nその時は無償で助けてくれる、どう？"

# カズマ
# お前がそれでいいっていうならオーケーだ。\nでもせめて、ここのメシ代くらいはおごらせてくれ。
174 = "お前がそれでいいっていうならオーケーだ。\\nでもせめて、ここのメシ代くらいはおごらせてくれ。"

# クリス
# うん、それくらいなら喜んで。
171 = "うん、それくらいなら喜んで。"

# カズマ
# おっし！\nそれじゃ、なんでも頼んでくれよ。
173 = "おっし！\\nそれじゃ、なんでも頼んでくれよ。"

# クリス
# へえ？　なんでも？\nそれじゃ、カニとか頼んで良い？
184 = "へえ？　なんでも？\\nそれじゃ、カニとか頼んで良い？"

# カズマ
# へっ？\nい、いや、それは勘弁してくれ……。
185 = "へっ？\\nい、いや、それは勘弁してくれ……。"

# クリス
# あはは、冗談だって。\nさあ、それじゃ何を頼もうかな～。
169 = "あはは、冗談だって。\\nさあ、それじゃ何を頼もうかな～。"

# カズマ（Ｍ）
# display as カズマ
# （クリスは本当にいいやつだなぁ。\n　正直、この程度でいいのかって感じなのに、\n　こんな嬉しそうにしてくれるし）
213 = "（クリスは本当にいいやつだなぁ。\\n　正直、この程度でいいのかって感じなのに、\\n　こんな嬉しそうにしてくれるし）"

# カズマ（Ｍ）
# display as カズマ
# （さて、クリスが終わったら\n　次はウィズのところに行くか）
212 = "（さて、クリスが終わったら\\n　次はウィズのところに行くか）"

