# root_d23.txt.scn

[info]
0 = ""

[characters]
253 = "カズマ"
258 = "クリス"
254 = "カズマ（Ｍ）"

[character_subs]
# 253 = "カズマ"

[script]
# lines: 72

# カズマ
# あー、しんどかったぁ……。
216 = "あー、しんどかったぁ……。"

# カズマ
# でもこれで、\n余計な借金を抱え込まずにすんだぜ。
239 = "でもこれで、\\n余計な借金を抱え込まずにすんだぜ。"

# クリス
# あはは、お疲れさま。\nこんなに楽しい１日は初めてだったかも。
213 = "あはは、お疲れさま。\\nこんなに楽しい１日は初めてだったかも。"

# カズマ
# パンツを盗られたのに？\nズボンを脱がされて、お尻を出したのに？
260 = "パンツを盗られたのに？\\nズボンを脱がされて、お尻を出したのに？"

# クリス
# ズボンは脱げてない。\nそう言ったよね？
259 = "ズボンは脱げてない。\\nそう言ったよね？"

# カズマ
# そ、そうでしたね。
224 = "そ、そうでしたね。"

# クリス
# まあ、こんな思いは２度としたくないけど、\n楽しかったっていうのは本音。
248 = "まあ、こんな思いは２度としたくないけど、\\n楽しかったっていうのは本音。"

# クリス
# だから、指輪の一件の貸しは\nこれでチャラにしてあげるよ。
235 = "だから、指輪の一件の貸しは\\nこれでチャラにしてあげるよ。"

# カズマ
# これってなんだよ。
221 = "これってなんだよ。"

# クリス
# 楽しい時間の提供、かな？
270 = "楽しい時間の提供、かな？"

# カズマ
# 楽しい時間の提供ね。\n腑に落ちない感じだけど、\n借りがなくなるなら、まぁいいか。
271 = "楽しい時間の提供ね。\\n腑に落ちない感じだけど、\\n借りがなくなるなら、まぁいいか。"

# クリス
# と言うわけで、キミはあたしに\nまた借りが１つできちゃったけど、\nそっちはどうするつもりなのかな？
240 = "と言うわけで、キミはあたしに\\nまた借りが１つできちゃったけど、\\nそっちはどうするつもりなのかな？"

# カズマ
# え？　借り？\nそれは今、チャラにするってことで\n話がついたんじゃなかったのか。
220 = "え？　借り？\\nそれは今、チャラにするってことで\\n話がついたんじゃなかったのか。"

# クリス
# 今のは指輪の件。\nあたしが言ってるのは、今回\nキミがあたしから盗んだ物について、だよ。
263 = "今のは指輪の件。\\nあたしが言ってるのは、今回\\nキミがあたしから盗んだ物について、だよ。"

# クリス
# 散々、人を振り回したくせに\nとぼけようたって、そうはいかないんだからね？
268 = "散々、人を振り回したくせに\\nとぼけようたって、そうはいかないんだからね？"

# カズマ
# もしかして、パンツのことか？
251 = "もしかして、パンツのことか？"

# クリス
# ちょ、ちょっと！\nそう堂々と言わないでよ！\nこっちが恥ずかしくなるから！
236 = "ちょ、ちょっと！\\nそう堂々と言わないでよ！\\nこっちが恥ずかしくなるから！"

# クリス
# まぁ、買って返せば済む話じゃない、\nってことくらいわかってるよね？
247 = "まぁ、買って返せば済む話じゃない、\\nってことくらいわかってるよね？"

# カズマ（Ｍ）
# display as カズマ
# （うっ、また意味深な……。\n　パンツを買って返すだけじゃダメとなると\n　どう答えればいいんだ？）
287 = "（うっ、また意味深な……。\\n　パンツを買って返すだけじゃダメとなると\\n　どう答えればいいんだ？）"

# カズマ
# 何をたくらんでるんだ。
264 = "何をたくらんでるんだ。"

# カズマ
# まさか、これをネタに高額な物を買わせようとか\n無理難題を押し付けようとか\n考えてないだろうな？
250 = "まさか、これをネタに高額な物を買わせようとか\\n無理難題を押し付けようとか\\n考えてないだろうな？"

# クリス
# それもいいかもしれないね。\nなんてったって、あたしには\n１００万エリスの価値があるみたいだし？
233 = "それもいいかもしれないね。\\nなんてったって、あたしには\\n１００万エリスの価値があるみたいだし？"

# カズマ
# それは俺が言いだしたんじゃないだろ！？
232 = "それは俺が言いだしたんじゃないだろ！？"

# クリス
# でも、キミの名前で発注されてたよね？\nだからあれは、キミの依頼だよ。\nいくらキミが否定したとしてもね。
238 = "でも、キミの名前で発注されてたよね？\\nだからあれは、キミの依頼だよ。\\nいくらキミが否定したとしてもね。"

# クリス
# １００万エリスかぁ。\nそれだけあったら、何ができるかなー。\nなんでも買えちゃうよねー。
293 = "１００万エリスかぁ。\\nそれだけあったら、何ができるかなー。\\nなんでも買えちゃうよねー。"

# カズマ
# あの、クリスさん？\n冗談ですよね？
211 = "あの、クリスさん？\\n冗談ですよね？"

# クリス
# ふふん、どうしようかなぁ。\nキミには色々迷惑かけられたしね～。
244 = "ふふん、どうしようかなぁ。\\nキミには色々迷惑かけられたしね～。"

# カズマ（Ｍ）
# display as カズマ
# （確かに、今回クリスには色々迷惑かけたし\n　何かしら詫びはしないといけないとは思う）
291 = "（確かに、今回クリスには色々迷惑かけたし\\n　何かしら詫びはしないといけないとは思う）"

# カズマ（Ｍ）
# display as カズマ
# （けど１００万エリスは無理だ！　無理無理！\n　ただでさえ借金抱えてるっていうのに\n　これ以上増えたら生きていけない！）
290 = "（けど１００万エリスは無理だ！　無理無理！\\n　ただでさえ借金抱えてるっていうのに\\n　これ以上増えたら生きていけない！）"

# カズマ
# よしわかった。\nクリスの言う通りにしよう。
252 = "よしわかった。\\nクリスの言う通りにしよう。"

# クリス
# えっ？
219 = "えっ？"

# カズマ
# ただ、１００万エリスは勘弁してくれ！\n他にも借金を抱えてる状態だから\nこれ以上、借金を増やしたくないんだ。
234 = "ただ、１００万エリスは勘弁してくれ！\\n他にも借金を抱えてる状態だから\\nこれ以上、借金を増やしたくないんだ。"

# カズマ
# その代わり、俺にできることなら\nなんでもするからさ！
229 = "その代わり、俺にできることなら\\nなんでもするからさ！"

# クリス
# なんか、カズマがそういう風に\n真面目に発言するのって珍しいね。
243 = "なんか、カズマがそういう風に\\n真面目に発言するのって珍しいね。"

# カズマ
# 珍しいって……。\nあのなぁ、俺は俺なりに誠意をもって\n応えようとしてるんだぞ？　それはないだろ……。
272 = "珍しいって……。\\nあのなぁ、俺は俺なりに誠意をもって\\n応えようとしてるんだぞ？　それはないだろ……。"

# クリス
# あはは、ごめんごめん。
214 = "あはは、ごめんごめん。"

# カズマ
# ３枚セットで返すから！\nそれで、ここはひとつ穏便に済ませてくれ！
296 = "３枚セットで返すから！\\nそれで、ここはひとつ穏便に済ませてくれ！"

# クリス
# あのねぇ、カズマ？\nキミ、何か勘違いしてるみたいだけど、\nあたしは新しいパンツが欲しいわけじゃないよ？
212 = "あのねぇ、カズマ？\\nキミ、何か勘違いしてるみたいだけど、\\nあたしは新しいパンツが欲しいわけじゃないよ？"

# カズマ
# ３枚じゃ不満か？\nだったらブラもつけるぞ。\nこういうのは上下セットのほうがいいんだよな。
294 = "３枚じゃ不満か？\\nだったらブラもつけるぞ。\\nこういうのは上下セットのほうがいいんだよな。"

# クリス
# な、なんでキミは\nそういう妙な知識を持ってるのさ！\n余計な気遣いしなくていいから！
241 = "な、なんでキミは\\nそういう妙な知識を持ってるのさ！\\n余計な気遣いしなくていいから！"

# カズマ
# 遠慮するなよ。\n今回の件については\n俺も多少なり責任を感じてるんだからさ。
285 = "遠慮するなよ。\\n今回の件については\\n俺も多少なり責任を感じてるんだからさ。"

# クリス
# ふーん……。\nじゃあ、新しい下着を買いに行くの、\n付き合ってもらおうかな。
245 = "ふーん……。\\nじゃあ、新しい下着を買いに行くの、\\n付き合ってもらおうかな。"

# クリス
# キミ、あたしの下着にこだわってるみたいだし。\nいいよね？
255 = "キミ、あたしの下着にこだわってるみたいだし。\\nいいよね？"

# カズマ
# い、いや、それは……！\nクリスが買ってきた物を\n後で清算する……でいいんじゃないか？
217 = "い、いや、それは……！\\nクリスが買ってきた物を\\n後で清算する……でいいんじゃないか？"

# クリス
# 何言ってるの。\nそれじゃ、お仕置きにならないでしょ。
265 = "何言ってるの。\\nそれじゃ、お仕置きにならないでしょ。"

# クリス
# キミには、あたしが体験した恥ずかしさを\n少しでも味わってもらわなきゃ。
257 = "キミには、あたしが体験した恥ずかしさを\\n少しでも味わってもらわなきゃ。"

# クリス
# ああでも、キミと違って、あたしは\n人前でパンツを脱げなんて言わないから安心して。\nあたしは優しいからさ。
210 = "ああでも、キミと違って、あたしは\\n人前でパンツを脱げなんて言わないから安心して。\\nあたしは優しいからさ。"

# カズマ
# ほ、本気か？
246 = "ほ、本気か？"

# クリス
# さあね？\nキミはどう思う？
222 = "さあね？\\nキミはどう思う？"

# カズマ
# 本当に、ごめんなさい！
269 = "本当に、ごめんなさい！"

# クリス
# あれ、言い訳しないんだ？
215 = "あれ、言い訳しないんだ？"

# カズマ
# そりゃ、口だけならなんとでも言えるけどさ。\nクリスが望んでるのはそういうのじゃないだろ？
230 = "そりゃ、口だけならなんとでも言えるけどさ。\\nクリスが望んでるのはそういうのじゃないだろ？"

# カズマ
# それに俺も、逃げるためとはいえ\n正直やり過ぎたって思ってるし……悪かったよ。
231 = "それに俺も、逃げるためとはいえ\\n正直やり過ぎたって思ってるし……悪かったよ。"

# カズマ
# 謝って済む話だとは思ってないけどさ、\nどうすれば許してもらえるかわからないから\nせめてちゃんと言わせてくれ。
284 = "謝って済む話だとは思ってないけどさ、\\nどうすれば許してもらえるかわからないから\\nせめてちゃんと言わせてくれ。"

# カズマ
# 色々、振り回してすまなかった。\n俺に何ができるかわかんないけど、\nクリスの気が済むなら、なんでもする。
281 = "色々、振り回してすまなかった。\\n俺に何ができるかわかんないけど、\\nクリスの気が済むなら、なんでもする。"

# クリス
# キミにしては殊勝な心がけだね。\nてっきり、パンツ買って返すからとか\n言いだすかと思ってたのに。
256 = "キミにしては殊勝な心がけだね。\\nてっきり、パンツ買って返すからとか\\n言いだすかと思ってたのに。"

# クリス
# まあ、そんなこと言ったら\n問答無用で張り倒してたけどね。
249 = "まあ、そんなこと言ったら\\n問答無用で張り倒してたけどね。"

# カズマ（Ｍ）
# display as カズマ
# （言わなくて良かった……！）
292 = "（言わなくて良かった……！）"

# クリス
# でも、ちょっと見直した。\nキミってさ、なんだかんだ言って\n悪人になれないって言うか……いい人だよね。
237 = "でも、ちょっと見直した。\\nキミってさ、なんだかんだ言って\\n悪人になれないって言うか……いい人だよね。"

# クリス
# そういうの、嫌いじゃないよ。
225 = "そういうの、嫌いじゃないよ。"

# カズマ（Ｍ）
# display as カズマ
# （うーむ、クリスの考えが全くわからん。\n　怒ってるって言うわりには\n　冗談っぽいところもあるし……）
288 = "（うーむ、クリスの考えが全くわからん。\\n　怒ってるって言うわりには\\n　冗談っぽいところもあるし……）"

# カズマ
# なぁ、クリス。\n結局、俺はどうしたらいいんだ？
242 = "なぁ、クリス。\\n結局、俺はどうしたらいいんだ？"

# クリス
# うーん、そうだねぇ……。
218 = "うーん、そうだねぇ……。"

# クリス
# せっかくだし、今回の件については\nまた貸しにしといてあげるよ。
223 = "せっかくだし、今回の件については\\nまた貸しにしといてあげるよ。"

# クリス
# 言ったでしょ。\nキミに貸しを作っておくのも悪くないってさ。
283 = "言ったでしょ。\\nキミに貸しを作っておくのも悪くないってさ。"

# カズマ
# マジか！\nそれ、また振り出しに戻ってるんだけど？
261 = "マジか！\\nそれ、また振り出しに戻ってるんだけど？"

# カズマ（Ｍ）
# display as カズマ
# （あれだけ大騒ぎして逃げ回って\n　借りが無くなったって言うのに。\n　今日１日の意味が……）
286 = "（あれだけ大騒ぎして逃げ回って\\n　借りが無くなったって言うのに。\\n　今日１日の意味が……）"

# カズマ（Ｍ）
# display as カズマ
# （くそっ、これも全てはあの駄女神のせいだ！\n　一生怨んでやるからなっ！）
289 = "（くそっ、これも全てはあの駄女神のせいだ！\\n　一生怨んでやるからなっ！）"

# クリス
# そういえば、アクアさんは\nどこにいるんだろうね？\n結局、見かけなかったけど。
226 = "そういえば、アクアさんは\\nどこにいるんだろうね？\\n結局、見かけなかったけど。"

# カズマ
# そうだ、あの駄女神だ！\n一言、文句言ってやらないと俺の気が済まない！
228 = "そうだ、あの駄女神だ！\\n一言、文句言ってやらないと俺の気が済まない！"

# クリス
# 街の中で見かけなかったってことは、\nもしかすると外かもしれないね。\nここまで来たんだし、捜しに行くなら付き合うよ。
282 = "街の中で見かけなかったってことは、\\nもしかすると外かもしれないね。\\nここまで来たんだし、捜しに行くなら付き合うよ。"

# カズマ
# そうか、悪いな。\nじゃあ、街の外まで行ってみるか！
227 = "そうか、悪いな。\\nじゃあ、街の外まで行ってみるか！"

[selections]
# 264 = "何をたくらんでるんだ。"
295 = "３枚セットで返すから！"
# 269 = "本当に、ごめんなさい！"
