# root_e02.txt.scn

[info]
0 = ""

[characters]
334 = "ダクネス"
330 = "カズマ（Ｍ）"
325 = "ゆんゆん"
320 = "めぐみん"
329 = "カズマ"
328 = "アクア"

[character_subs]
# 329 = "カズマ"

[script]
# lines: 66

# ダクネス
# では、これより、\nめぐみんとゆんゆんによる釣り対決を始める！
304 = "では、これより、\\nめぐみんとゆんゆんによる釣り対決を始める！"

# カズマ（Ｍ）
# display as カズマ
# （妙にダクネスが張り切って仕切ってるんだが。\n　勝負事だからクルセイダーの血が騒いでるのか？）
387 = "（妙にダクネスが張り切って仕切ってるんだが。\\n　勝負事だからクルセイダーの血が騒いでるのか？）"

# ゆんゆん
# 今日こそは負けないわ、めぐみん！
339 = "今日こそは負けないわ、めぐみん！"

# めぐみん
# 寝言は寝てから言うものですよ。\n今日も私が勝ちます。
348 = "寝言は寝てから言うものですよ。\\n今日も私が勝ちます。"

# ダクネス
# 制限時間は日没までだ。\nでは、始め！
342 = "制限時間は日没までだ。\\nでは、始め！"

# カズマ（Ｍ）
# display as カズマ
# （おーおー、釣り竿を抱えて走って行く後ろ姿は\n　まだ子供って感じだな）
385 = "（おーおー、釣り竿を抱えて走って行く後ろ姿は\\n　まだ子供って感じだな）"

# ダクネス
# ついに始まったな。\n生涯のライバルが己のプライドを\n賭けて雌雄を決する――
303 = "ついに始まったな。\\n生涯のライバルが己のプライドを\\n賭けて雌雄を決する――"

# ダクネス
# 実に熱い展開じゃないか、カズマ。
346 = "実に熱い展開じゃないか、カズマ。"

# カズマ
# そんなに素晴らしいものじゃないだろ。\nただの釣りだぞ、釣り。
300 = "そんなに素晴らしいものじゃないだろ。\\nただの釣りだぞ、釣り。"

# アクア
# ねえ、２人とも\nぜんぜん動かないんですけど。
311 = "ねえ、２人とも\\nぜんぜん動かないんですけど。"

# カズマ
# そりゃ、釣りだからな。\nここで必要なのは根気だぜ？
298 = "そりゃ、釣りだからな。\\nここで必要なのは根気だぜ？"

# ダクネス
# ああ、だからこそ\nアークウィザード同士の勝負にもなるのだ。
283 = "ああ、だからこそ\\nアークウィザード同士の勝負にもなるのだ。"

# カズマ
# ところでさ、どうして日没までなんて\nルールにしたんだ？
306 = "ところでさ、どうして日没までなんて\\nルールにしたんだ？"

# ダクネス
# ん？　問題でもあるか？
327 = "ん？　問題でもあるか？"

# カズマ
# いや、俺なら、先に魚を釣り上げた方が\n勝ちってルールにするぜ？
290 = "いや、俺なら、先に魚を釣り上げた方が\\n勝ちってルールにするぜ？"

# ダクネス
# それでは簡単に勝負がついてしまうだろう。
299 = "それでは簡単に勝負がついてしまうだろう。"

# カズマ
# でもさ、見てみろ、この状況。
305 = "でもさ、見てみろ、この状況。"

# カズマ
# まったく動きがない！\nまるで時が止まってるみたいだろ？\nこれが日没まで続くんだぞ？
318 = "まったく動きがない！\\nまるで時が止まってるみたいだろ？\\nこれが日没まで続くんだぞ？"

# カズマ
# ハッキリ言って退屈だ！\nその証拠に、ほら。
335 = "ハッキリ言って退屈だ！\\nその証拠に、ほら。"

# アクア
# ねえ、カズマもこっちに来なさいよー！
310 = "ねえ、カズマもこっちに来なさいよー！"

# カズマ
# ……早速、飽きて遊んでやがるだろ。
281 = "……早速、飽きて遊んでやがるだろ。"

# カズマ
# おい、駄女神。\nいったい何やってんだ。
294 = "おい、駄女神。\\nいったい何やってんだ。"

# アクア
# 何って、見ての通り川に入って水遊びよ。
340 = "何って、見ての通り川に入って水遊びよ。"

# めぐみん
# 当たり前のように言わないでください！\nそんなに騒がれては魚が逃げてしまいます！
351 = "当たり前のように言わないでください！\\nそんなに騒がれては魚が逃げてしまいます！"

# アクア
# いいえ、これは試練よ。\nどんな状況であろうと釣り上げてこそ本物なの。
288 = "いいえ、これは試練よ。\\nどんな状況であろうと釣り上げてこそ本物なの。"

# カズマ（Ｍ）
# display as カズマ
# （適当なことを言ってるけど、\n　あれ、自分が遊びたいだけだよなぁ）
388 = "（適当なことを言ってるけど、\\n　あれ、自分が遊びたいだけだよなぁ）"

# めぐみん
# や、やめてください！\nこれでは勝負になりません！
324 = "や、やめてください！\\nこれでは勝負になりません！"

# アクア
# ねえ、これって結構、楽しいわよ？\nカズマとダクネスもいらっしゃいよ！
309 = "ねえ、これって結構、楽しいわよ？\\nカズマとダクネスもいらっしゃいよ！"

# カズマ
# あのなぁ、勝負の最中なんだぞ？
284 = "あのなぁ、勝負の最中なんだぞ？"

# アクア
# スキありっ！
333 = "スキありっ！"

# カズマ
# うわっ、冷てぇっ！？\nいきなり何すんだよお前は！
292 = "うわっ、冷てぇっ！？\\nいきなり何すんだよお前は！"

# アクア
# ふふん、油断したカズマが悪いのよ。\nここは戦場なんだからね！
313 = "ふふん、油断したカズマが悪いのよ。\\nここは戦場なんだからね！"

# カズマ
# なるほど戦場か。\n覚悟はできてんだろうな、アクア。
307 = "なるほど戦場か。\\n覚悟はできてんだろうな、アクア。"

# アクア
# ふふん、私は水の女神なのよ。\nその気になれば、鉄砲水だって\n起こすことができるんだからね。
314 = "ふふん、私は水の女神なのよ。\\nその気になれば、鉄砲水だって\\n起こすことができるんだからね。"

# カズマ
# いや、それは命に関わるからやめろ。
289 = "いや、それは命に関わるからやめろ。"

# アクア
# あら、さっそく弱音？\nいつもの無駄に強気なカズマさんは\nどこへいっちゃったのかしら。
286 = "あら、さっそく弱音？\\nいつもの無駄に強気なカズマさんは\\nどこへいっちゃったのかしら。"

# カズマ
# なんだと！　おらっ！
308 = "なんだと！　おらっ！"

# アクア
# まるでスローモーションね。\nそんな遅いのが当たるわけないでしょ！？\n攻撃っていうのはね、こうやるのよ！
319 = "まるでスローモーションね。\\nそんな遅いのが当たるわけないでしょ！？\\n攻撃っていうのはね、こうやるのよ！"

# カズマ
# ぶはっ！\nやめ、やめろ！
316 = "ぶはっ！\\nやめ、やめろ！"

# アクア
# 水の女神に水かけで挑むなんて１００年早いのよ！\n食らいなさいヒキニート！
352 = "水の女神に水かけで挑むなんて１００年早いのよ！\\n食らいなさいヒキニート！"

# カズマ
# こ、この……！
296 = "こ、この……！"

# ダクネス
# 容赦のない水攻め……羨ましい……！
347 = "容赦のない水攻め……羨ましい……！"

# ダクネス
# い、いや！\n盾となり仲間を守るのがクルセイダーだ、\nカズマ、今助けるぞ！
287 = "い、いや！\\n盾となり仲間を守るのがクルセイダーだ、\\nカズマ、今助けるぞ！"

# ダクネス
# うおっ！\nこ、これは思いの外……いい！
291 = "うおっ！\\nこ、これは思いの外……いい！"

# ダクネス
# さあ、もっとだ！\nもっと私を攻めるがいい！
297 = "さあ、もっとだ！\\nもっと私を攻めるがいい！"

# アクア
# あはははっ！\nくらいなさーい！
285 = "あはははっ！\\nくらいなさーい！"

# カズマ
# スキありぃ！
332 = "スキありぃ！"

# アクア
# うわっぷ！\nつ、冷たぁっ！
293 = "うわっぷ！\\nつ、冷たぁっ！"

# カズマ（Ｍ）
# display as カズマ
# （よし、怯んだ！\n　一気に畳みかけてやる！）
386 = "（よし、怯んだ！\\n　一気に畳みかけてやる！）"

# めぐみん
# もう、いい加減にしてください！\nこれでは魚が逃げてしまって勝負になりません！
323 = "もう、いい加減にしてください！\\nこれでは魚が逃げてしまって勝負になりません！"

# アクア
# めぐみん、スキあり！
321 = "めぐみん、スキあり！"

# めぐみん
# わっぷっ！？
326 = "わっぷっ！？"

# めぐみん
# ……やりましたね？\nいいでしょう、この我の本気を見せてくれよう！\nとりゃーーー！！
279 = "……やりましたね？\\nいいでしょう、この我の本気を見せてくれよう！\\nとりゃーーー！！"

# カズマ
# げふっ！\nかかってる！　俺にかかってるから！
295 = "げふっ！\\nかかってる！　俺にかかってるから！"

# めぐみん
# そ～れそれそれ！
301 = "そ～れそれそれ！"

# ゆんゆん
# めぐみん、楽しそう……。
322 = "めぐみん、楽しそう……。"

# めぐみん
# ……ゆんゆん？
280 = "……ゆんゆん？"

# めぐみん
# コホン！\nさて、バカはここまでにして勝負に戻りましょう。
331 = "コホン！\\nさて、バカはここまでにして勝負に戻りましょう。"

# ゆんゆん
# ……いいの、めぐみん？
278 = "……いいの、めぐみん？"

# めぐみん
# まだ勝負がついていませんからね。\n不戦敗扱いにされでもしたら\nたまったものではありません。
317 = "まだ勝負がついていませんからね。\\n不戦敗扱いにされでもしたら\\nたまったものではありません。"

# ゆんゆん
# あ、ありがとう。
282 = "あ、ありがとう。"

# めぐみん
# 何を勘違いしているんです？\n私のためですよ。
341 = "何を勘違いしているんです？\\n私のためですよ。"

# カズマ
# ふーん。\nなんだかんだ言ってお前ら仲良いな。
315 = "ふーん。\\nなんだかんだ言ってお前ら仲良いな。"

# ゆんゆん
# ち、違いますっ！\n仲なんて良くないです！　ライバルです！
302 = "ち、違いますっ！\\n仲なんて良くないです！　ライバルです！"

# めぐみん
# ライバルでもなく、ただのストーカーですが。
337 = "ライバルでもなく、ただのストーカーですが。"

# ゆんゆん
# ひ、ひどい～！
312 = "ひ、ひどい～！"

