# root_b07.txt.scn

[info]
0 = ""

[characters]
220 = "カズマ（Ｍ）"
219 = "カズマ"
217 = "めぐみん"

[character_subs]
# 219 = "カズマ"

[script]
# lines: 59

# カズマ（Ｍ）
# display as カズマ
# （ここに閉じ込められてから\n　何時間が過ぎただろう）
265 = "（ここに閉じ込められてから\\n　何時間が過ぎただろう）"

# カズマ（Ｍ）
# display as カズマ
# （出られないどころか、\n　誰かがここに来る気配すらない。\n　これも呪いの力なのか？）
271 = "（出られないどころか、\\n　誰かがここに来る気配すらない。\\n　これも呪いの力なのか？）"

# カズマ（Ｍ）
# display as カズマ
# （唯一の救いと言えば、\n　めぐみんが落ち着きを\n　取り戻してくれたことくらいか）
272 = "（唯一の救いと言えば、\\n　めぐみんが落ち着きを\\n　取り戻してくれたことくらいか）"

# カズマ
# なあ、めぐみん？\nもう一度聞くが、俺と結婚――
207 = "なあ、めぐみん？\\nもう一度聞くが、俺と結婚――"

# めぐみん
# 何度言ったらわかってくれるのですか。\nそれだけは絶対に嫌です。
224 = "何度言ったらわかってくれるのですか。\\nそれだけは絶対に嫌です。"

# カズマ
# だ、だったらどうするつもりだ？\nこのままってわけにはいかないだろ？
198 = "だ、だったらどうするつもりだ？\\nこのままってわけにはいかないだろ？"

# めぐみん
# 大丈夫です。\nアクアやダクネスがいます。
228 = "大丈夫です。\\nアクアやダクネスがいます。"

# めぐみん
# さすがに、私達がそろって一晩帰らなかったら、\n心配して捜し始めますよ。
191 = "さすがに、私達がそろって一晩帰らなかったら、\\n心配して捜し始めますよ。"

# カズマ
# あ、そうか。\nアクアなら呪いも解けるだろうしな。
182 = "あ、そうか。\\nアクアなら呪いも解けるだろうしな。"

# カズマ（Ｍ）
# display as カズマ
# （エリス教団の教会だけど、\n　俺とめぐみんを助けるためなら\n　呪いを解くのを嫌とは言わないだろ）
270 = "（エリス教団の教会だけど、\\n　俺とめぐみんを助けるためなら\\n　呪いを解くのを嫌とは言わないだろ）"

# カズマ（Ｍ）
# display as カズマ
# （言わないよな？\n　微妙に不安が残るが……）
273 = "（言わないよな？\\n　微妙に不安が残るが……）"

# カズマ
# ということは、明日まで\nここで過ごすつもりなんだな。
204 = "ということは、明日まで\\nここで過ごすつもりなんだな。"

# めぐみん
# も、もちろん、寝るときは別々ですよ？
218 = "も、もちろん、寝るときは別々ですよ？"

# カズマ
# うん。\n……それってなんの心配だ？
189 = "うん。\\n……それってなんの心配だ？"

# めぐみん
# いくらヘタレなカズマとはいえ、\n実際に寝床を供にしたら、\n何をするかわかりませんし。
187 = "いくらヘタレなカズマとはいえ、\\n実際に寝床を供にしたら、\\n何をするかわかりませんし。"

# カズマ
# そういう心配は\nもっと女性らしくなってからしたまえ！
193 = "そういう心配は\\nもっと女性らしくなってからしたまえ！"

# めぐみん
# なっ、どういう意味ですか！\n事と場合によっては蹴り上げますからね！
208 = "なっ、どういう意味ですか！\\n事と場合によっては蹴り上げますからね！"

# カズマ
# へえ、どこを蹴り上げるの？\nねえ、ねえ、どこを？
212 = "へえ、どこを蹴り上げるの？\\nねえ、ねえ、どこを？"

# めぐみん
# キキ、キ、キッ……キシャーーーーーー！！
221 = "キキ、キ、キッ……キシャーーーーーー！！"

# カズマ
# だー、お前はわけわからんキレ方をすんな！
201 = "だー、お前はわけわからんキレ方をすんな！"

# めぐみん
# まったく、カズマにはデリカシーというものが\nないんですか。
216 = "まったく、カズマにはデリカシーというものが\\nないんですか。"

# めぐみん
# そんなだからモテないんですよ。
197 = "そんなだからモテないんですよ。"

# カズマ
# 大きなお世話だ。\nそれよりも。
227 = "大きなお世話だ。\\nそれよりも。"

# めぐみん
# なんです？
210 = "なんです？"

# カズマ
# 一晩ここで過ごすって本気で言ってるのか？
222 = "一晩ここで過ごすって本気で言ってるのか？"

# めぐみん
# 本気も何も、それ以外の選択肢がありません。\n結婚は絶対に嫌ですし。
231 = "本気も何も、それ以外の選択肢がありません。\\n結婚は絶対に嫌ですし。"

# カズマ
# まあ、俺にわからない\n乙女心ってやつなんだろう？\n結婚を無理強いしたりしない。
215 = "まあ、俺にわからない\\n乙女心ってやつなんだろう？\\n結婚を無理強いしたりしない。"

# めぐみん
# 当然です。
230 = "当然です。"

# カズマ
# だが、ここは呪われた教会だ。\n朝まで何も起こらないなんて保証も\nないんだからな？
199 = "だが、ここは呪われた教会だ。\\n朝まで何も起こらないなんて保証も\\nないんだからな？"

# めぐみん
# へ？
214 = "へ？"

# カズマ
# へ、じゃねえよ、へ、じゃ。\n夜なんて霊の独壇場じゃねーか。
211 = "へ、じゃねえよ、へ、じゃ。\\n夜なんて霊の独壇場じゃねーか。"

# カズマ
# それこそ壁に血文字を書いた奴が\nひゃっはー！　って小躍り始めるわ！
196 = "それこそ壁に血文字を書いた奴が\\nひゃっはー！　って小躍り始めるわ！"

# めぐみん
# あ……。
180 = "あ……。"

# カズマ（Ｍ）
# display as カズマ
# （この顔、いっぱいいっぱいで\n　想像してなかったのか）
266 = "（この顔、いっぱいいっぱいで\\n　想像してなかったのか）"

# めぐみん
# ど、どうしましょうカズマ！？\nそうですよ、呪いの教会で一晩なんて\nどう考えても危険です！
205 = "ど、どうしましょうカズマ！？\\nそうですよ、呪いの教会で一晩なんて\\nどう考えても危険です！"

# カズマ
# 決めたのはお前なんだから、\n気合いで一晩生き抜いてみせろ。
232 = "決めたのはお前なんだから、\\n気合いで一晩生き抜いてみせろ。"

# めぐみん
# ちょ、ちょっと待ってください。\n生き抜けって、この呪いは命を持っていく系の\nやつなんですか？
203 = "ちょ、ちょっと待ってください。\\n生き抜けって、この呪いは命を持っていく系の\\nやつなんですか？"

# カズマ
# 知らん。
263 = "知らん。"

# めぐみん
# …………。
179 = "…………。"

# めぐみん
# 命の危機だというのに、\nやけに落ち着いていますね。\n怖くはないのですか？
226 = "命の危機だというのに、\\nやけに落ち着いていますね。\\n怖くはないのですか？"

# カズマ
# そりゃ、怖いに決まってる。
195 = "そりゃ、怖いに決まってる。"

# カズマ（Ｍ）
# display as カズマ
# （でも、もう何回か死んでるしなぁ。\n　最悪、アクアが蘇らせてくれるだろうし、\n　向こうでエリス様に会えるし）
267 = "（でも、もう何回か死んでるしなぁ。\\n　最悪、アクアが蘇らせてくれるだろうし、\\n　向こうでエリス様に会えるし）"

# めぐみん
# あの、なんとか抜け出す方法は\nないのでしょうか？
185 = "あの、なんとか抜け出す方法は\\nないのでしょうか？"

# カズマ
# さんざん色々試して、\n無理だっていう結論が出ただろ？\nあと試してないことと言ったら――
192 = "さんざん色々試して、\\n無理だっていう結論が出ただろ？\\nあと試してないことと言ったら――"

# めぐみん
# 結婚は嫌です！\nいい加減しつこいですよ！？
264 = "結婚は嫌です！\\nいい加減しつこいですよ！？"

# カズマ（Ｍ）
# display as カズマ
# （はあ……。\n　なんでそこまで頑ななんだよ）
268 = "（はあ……。\\n　なんでそこまで頑ななんだよ）"

# カズマ
# だったら、なんとかして\n一晩、呪いから逃げ続けるしかないな。
200 = "だったら、なんとかして\\n一晩、呪いから逃げ続けるしかないな。"

# めぐみん
# あうっ！？
184 = "あうっ！？"

# カズマ（Ｍ）
# display as カズマ
# （ん？\n　今のってもしかして、めぐみんの腹の音か？）
269 = "（ん？\\n　今のってもしかして、めぐみんの腹の音か？）"

# めぐみん
# い、いまのは、その……。
186 = "い、いまのは、その……。"

# カズマ
# ああ、考えてみれば腹も減って当然だよな。
183 = "ああ、考えてみれば腹も減って当然だよな。"

# めぐみん
# こんな状況でも、お腹は空くのですね。
190 = "こんな状況でも、お腹は空くのですね。"

# カズマ
# そりゃ、俺達は生きてるからな。\nとりあえず、食料がないか探してみようぜ。\n腹が減ってはなんとやらだ。
194 = "そりゃ、俺達は生きてるからな。\\nとりあえず、食料がないか探してみようぜ。\\n腹が減ってはなんとやらだ。"

# めぐみん
# あ、あの……カズマ？
181 = "あ、あの……カズマ？"

# カズマ
# どうした、モジモジして？\nもしかしてトイレ？
206 = "どうした、モジモジして？\\nもしかしてトイレ？"

# めぐみん
# ちち、違います！\n紅魔族はトイレなんて行かないって\n何度言えばわかるんですか！
202 = "ちち、違います！\\n紅魔族はトイレなんて行かないって\\n何度言えばわかるんですか！"

# カズマ
# へー。
213 = "へー。"

# めぐみん
# なんですか、その目は！？
209 = "なんですか、その目は！？"

# カズマ
# いや別に。\nとにかく、食えるもんを探しに行こうぜ。
188 = "いや別に。\\nとにかく、食えるもんを探しに行こうぜ。"

