# root_a21.txt.scn

[info]
0 = ""

[characters]
133 = "カズマ（Ｍ）"
131 = "カズマ"
130 = "アクア"

[character_subs]
# 131 = "カズマ"

[script]
# lines: 49

# カズマ（Ｍ）
# display as カズマ
# （あのコンテストから数日──）
146 = "（あのコンテストから数日──）"

# カズマ（Ｍ）
# display as カズマ
# （結局、アクアの優勝は取り消されてしまった）
167 = "（結局、アクアの優勝は取り消されてしまった）"

# カズマ（Ｍ）
# display as カズマ
# （理由は簡単だ。\n　それはアクアが女神の名を騙ったこと）
166 = "（理由は簡単だ。\\n　それはアクアが女神の名を騙ったこと）"

# カズマ（Ｍ）
# display as カズマ
# （あいつはもちろん納得していなかったが、\n　女神という証拠を提示できない以上、\n　結果を覆せる訳もなく……）
145 = "（あいつはもちろん納得していなかったが、\\n　女神という証拠を提示できない以上、\\n　結果を覆せる訳もなく……）"

# カズマ（Ｍ）
# display as カズマ
# （結果として、アクアには莫大な借金のみが\n　残ったわけだ）
168 = "（結果として、アクアには莫大な借金のみが\\n　残ったわけだ）"

# カズマ（Ｍ）
# display as カズマ
# （そして俺たちは、\n　借金を返済すべく、総出で働きに出ることに\n　なった）
150 = "（そして俺たちは、\\n　借金を返済すべく、総出で働きに出ることに\\n　なった）"

# カズマ（Ｍ）
# display as カズマ
# （ギルドでクエストがあった時は\n　片っ端から取って稼ぎ……）
162 = "（ギルドでクエストがあった時は\\n　片っ端から取って稼ぎ……）"

# カズマ（Ｍ）
# display as カズマ
# （それぞれバイトにも精を出し、\n　借金返済への地道な一歩を踏み出していた──）
152 = "（それぞれバイトにも精を出し、\\n　借金返済への地道な一歩を踏み出していた──）"

# カズマ（Ｍ）
# display as カズマ
# （というのは、あくまでアクアの前でだけの\n　建前なのだが……）
156 = "（というのは、あくまでアクアの前でだけの\\n　建前なのだが……）"

# カズマ
# くっそ、どうして俺がこんなことを！
120 = "くっそ、どうして俺がこんなことを！"

# アクア
# ほーら、文句ばっかり言ってないで\n体を動かしなさい。
127 = "ほーら、文句ばっかり言ってないで\\n体を動かしなさい。"

# カズマ
# お前は、いいよな！\n自分の得意な仕事があるんだから！
119 = "お前は、いいよな！\\n自分の得意な仕事があるんだから！"

# アクア
# カズマだってなかなかツルハシが\n堂に入ってきたじゃない。
132 = "カズマだってなかなかツルハシが\\n堂に入ってきたじゃない。"

# アクア
# 短剣を構えてるより絵になるわよ。
142 = "短剣を構えてるより絵になるわよ。"

# カズマ
# 褒められてる気がしねえよ。
144 = "褒められてる気がしねえよ。"

# カズマ（Ｍ）
# display as カズマ
# （ここだけの話、\n　もうすでにアクアに借金はない）
147 = "（ここだけの話、\\n　もうすでにアクアに借金はない）"

# カズマ（Ｍ）
# display as カズマ
# （詐欺集団の思い通りになるのはシャクだと\n　考えた俺は、めぐみんに一計を授けた）
169 = "（詐欺集団の思い通りになるのはシャクだと\\n　考えた俺は、めぐみんに一計を授けた）"

# カズマ（Ｍ）
# display as カズマ
# （それはギルドにクエストの発注をすること）
153 = "（それはギルドにクエストの発注をすること）"

# カズマ（Ｍ）
# display as カズマ
# （その内容はこうだ。\n　アクシズ教を名乗る詐欺集団を捕まえる）
151 = "（その内容はこうだ。\\n　アクシズ教を名乗る詐欺集団を捕まえる）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、俺の用意出来る報酬金なんて\n　たかがしれている）
148 = "（しかし、俺の用意出来る報酬金なんて\\n　たかがしれている）"

# カズマ（Ｍ）
# display as カズマ
# （当然、そんなクエストには冒険者の食いつきも\n　悪い）
165 = "（当然、そんなクエストには冒険者の食いつきも\\n　悪い）"

# カズマ（Ｍ）
# display as カズマ
# （しかしまさに拾う神ありで、なんとエリス教徒が\n　手を貸してくれたのだ）
149 = "（しかしまさに拾う神ありで、なんとエリス教徒が\\n　手を貸してくれたのだ）"

# カズマ（Ｍ）
# display as カズマ
# （アクアの中身はあんなだけど、\n　エリス様とアクアは先輩後輩の間柄だ）
160 = "（アクアの中身はあんなだけど、\\n　エリス様とアクアは先輩後輩の間柄だ）"

# カズマ（Ｍ）
# display as カズマ
# （エリス教徒としては、\n　信仰する女神の先輩であるアクアの名を\n　悪用する奴も許せなかったのだろう）
161 = "（エリス教徒としては、\\n　信仰する女神の先輩であるアクアの名を\\n　悪用する奴も許せなかったのだろう）"

# カズマ（Ｍ）
# display as カズマ
# （ほどなくして詐欺集団は捕まり、\n　当然アクアの借金もチャラになった）
158 = "（ほどなくして詐欺集団は捕まり、\\n　当然アクアの借金もチャラになった）"

# カズマ（Ｍ）
# display as カズマ
# （だが、俺はそれをアクアに話してはいない。\n　それはもちろん、あいつに反省をさせるためだ）
155 = "（だが、俺はそれをアクアに話してはいない。\\n　それはもちろん、あいつに反省をさせるためだ）"

# カズマ
# それなのにっ！\nどうして俺がっ！\nこんな辛い目にっ！
125 = "それなのにっ！\\nどうして俺がっ！\\nこんな辛い目にっ！"

# アクア
# あっ、カズマ。\n今の作業が終わったら、\n私たちもう上がってもいいって。
115 = "あっ、カズマ。\\n今の作業が終わったら、\\n私たちもう上がってもいいって。"

# カズマ
# マジか！\nそっちの作業はどうなんだ？
136 = "マジか！\\nそっちの作業はどうなんだ？"

# アクア
# こっちももう少しで終わるわ。
122 = "こっちももう少しで終わるわ。"

# カズマ
# うし、じゃあ俺も気合いを入れるぜ。
117 = "うし、じゃあ俺も気合いを入れるぜ。"

# アクア
# 別に急がなくてもいいわよ。\n終わったら待っててあげるし。
138 = "別に急がなくてもいいわよ。\\n終わったら待っててあげるし。"

# カズマ
# それはどうも。\nだが俺は、一刻も早く風呂に入って汗を\n流したいんだ！
126 = "それはどうも。\\nだが俺は、一刻も早く風呂に入って汗を\\n流したいんだ！"

# アクア
# あっ、ねえ、ひさしぶりに大衆浴場に行くのは\nどうかしら？
114 = "あっ、ねえ、ひさしぶりに大衆浴場に行くのは\\nどうかしら？"

# カズマ
# おっ、いいね、それ！
118 = "おっ、いいね、それ！"

# アクア
# それで湯上がりには――
124 = "それで湯上がりには――"

# カズマ
# 腰に手を当てて――
143 = "腰に手を当てて――"

# アクア
# ぐいっと１杯！
121 = "ぐいっと１杯！"

# カズマ
# うおおお、モチベーションが上がってきたー！
116 = "うおおお、モチベーションが上がってきたー！"

# アクア
# そうそう、ダクネスがさっき来て、\n今日はご馳走だって言ってたの。
123 = "そうそう、ダクネスがさっき来て、\\n今日はご馳走だって言ってたの。"

# カズマ
# また実家から何か届いたのか！
128 = "また実家から何か届いたのか！"

# アクア
# めぐみんもニコニコ顔だったわね。
129 = "めぐみんもニコニコ顔だったわね。"

# カズマ
# カニだといいな。
134 = "カニだといいな。"

# アクア
# カニだといいわね。
135 = "カニだといいわね。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、辛くもあるけど、\n　なんだかんだで俺も今の状況を\n　楽しんでるのは事実だ）
159 = "（まあ、辛くもあるけど、\\n　なんだかんだで俺も今の状況を\\n　楽しんでるのは事実だ）"

# カズマ（Ｍ）
# display as カズマ
# （借金がチャラになったことを話したら、\n　またあのダラダラするだけの日々に戻って\n　しまうだろう）
164 = "（借金がチャラになったことを話したら、\\n　またあのダラダラするだけの日々に戻って\\n　しまうだろう）"

# カズマ（Ｍ）
# display as カズマ
# （それも悪くないが、\n　もう少し苦労を楽しんでからでも\n　いいかなって思い始めてる）
154 = "（それも悪くないが、\\n　もう少し苦労を楽しんでからでも\\n　いいかなって思い始めてる）"

# カズマ（Ｍ）
# display as カズマ
# （なんてたって、\n　労働後に食う飯は美味い！）
157 = "（なんてたって、\\n　労働後に食う飯は美味い！）"

# カズマ（Ｍ）
# display as カズマ
# （今の俺たちには、\n　これくらいの小さな幸せの方が\n　似合ってるのかもしれないな）
163 = "（今の俺たちには、\\n　これくらいの小さな幸せの方が\\n　似合ってるのかもしれないな）"

