# root_a04.txt.scn

[info]
0 = ""

[characters]
312 = "ダクネス"
301 = "めぐみん"
306 = "アクア"
309 = "カズマ"
310 = "カズマ（Ｍ）"

[character_subs]
# 309 = "カズマ"

[script]
# lines: 67

# ダクネス
# では、いただくとするか。
286 = "では、いただくとするか。"

# めぐみん
# アクア、いただきますね！
307 = "アクア、いただきますね！"

# アクア
# 遠慮しないで、どんどん食べちゃって。
363 = "遠慮しないで、どんどん食べちゃって。"

# カズマ
# んじゃ、俺もありがたく。\nいただきまーす。
304 = "んじゃ、俺もありがたく。\\nいただきまーす。"

# めぐみん
# ん、ん、んっ、くうううう～～～～！！
303 = "ん、ん、んっ、くうううう～～～～！！"

# カズマ
# くおおお、相変わらず暴力的な美味さだ！
275 = "くおおお、相変わらず暴力的な美味さだ！"

# アクア
# うふふ、私はお味噌をいただこうかしら。
265 = "うふふ、私はお味噌をいただこうかしら。"

# めぐみん
# はあむっ、んん～～！！\nはあむっ、あむ、くうううう～～！！
291 = "はあむっ、んん～～！！\\nはあむっ、あむ、くうううう～～！！"

# ダクネス
# おいおい、めぐみん、\nあまりがっつくと喉につまるぞ。
269 = "おいおい、めぐみん、\\nあまりがっつくと喉につまるぞ。"

# めぐみん
# 大丈夫れふ。\n霜降り赤ガニは口の中に入れた瞬間溶けて\n喉を通る頃には……うぐ！
320 = "大丈夫れふ。\\n霜降り赤ガニは口の中に入れた瞬間溶けて\\n喉を通る頃には……うぐ！"

# ダクネス
# ほら、言わんこっちゃない。
294 = "ほら、言わんこっちゃない。"

# めぐみん
# ごほっ、けほっ！！\nかじゅま、水を！
277 = "ごほっ、けほっ！！\\nかじゅま、水を！"

# カズマ
# まったく何やってんだ。
300 = "まったく何やってんだ。"

# アクア
# ほらぁ、カズマぁ！\nちゃんと食べてるぅ～！？
295 = "ほらぁ、カズマぁ！\\nちゃんと食べてるぅ～！？"

# カズマ
# って、お前はもうできあがってんのかよ！
285 = "って、お前はもうできあがってんのかよ！"

# アクア
# それじゃ、場も温まったことだし\n私がいいもの見せてあげるわね。
281 = "それじゃ、場も温まったことだし\\n私がいいもの見せてあげるわね。"

# めぐみん
# まさかまた、例のアレを！
298 = "まさかまた、例のアレを！"

# アクア
# 機動要塞デストロイヤー。
324 = "機動要塞デストロイヤー。"

# カズマ
# またそれかよ。
299 = "またそれかよ。"

# アクア
# からの。\nスカルドラゴン！
273 = "からの。\\nスカルドラゴン！"

# めぐみん
# おおお、似ています、似ていますよ、アクア！\nなんと言いますか、骨っぽい感じが\nとても良く表現できています！
271 = "おおお、似ています、似ていますよ、アクア！\\nなんと言いますか、骨っぽい感じが\\nとても良く表現できています！"

# カズマ
# 骨っぽい感じってなんだよ。
364 = "骨っぽい感じってなんだよ。"

# アクア
# ふっふっふっ！\n今日の私は絶好調よ！！
292 = "ふっふっふっ！\\n今日の私は絶好調よ！！"

# カズマ（Ｍ）
# display as カズマ
# （さて、俺もそろそろカニ味噌を……）
369 = "（さて、俺もそろそろカニ味噌を……）"

# カズマ
# って、おい、アクア。
284 = "って、おい、アクア。"

# アクア
# どうかした？
287 = "どうかした？"

# カズマ
# お前、もしかしてカニ味噌、\n全部食っちまったのか？
272 = "お前、もしかしてカニ味噌、\\n全部食っちまったのか？"

# アクア
# 少ないんだから早いもん勝ちでしょ？\nおかげで濃いカニ味噌酒になったわ。
321 = "少ないんだから早いもん勝ちでしょ？\\nおかげで濃いカニ味噌酒になったわ。"

# ダクネス
# どうりで随分とできあがっているわけだな。
288 = "どうりで随分とできあがっているわけだな。"

# カズマ（Ｍ）
# display as カズマ
# （おのれ！\n　前も俺、味わい損ねてるってのに！）
368 = "（おのれ！\\n　前も俺、味わい損ねてるってのに！）"

# アクア
# そんな怖い顔しなくても大丈夫よ。\nまだまだカニはあるんだから～。
283 = "そんな怖い顔しなくても大丈夫よ。\\nまだまだカニはあるんだから～。"

# カズマ（Ｍ）
# display as カズマ
# （それにしても、なんでアクアは\n　こんな上機嫌なんだ？）
370 = "（それにしても、なんでアクアは\\n　こんな上機嫌なんだ？）"

# カズマ
# おい、アクア。\n機嫌良すぎて気持ち悪いぞ？
268 = "おい、アクア。\\n機嫌良すぎて気持ち悪いぞ？"

# アクア
# あははは、なんとでも言えばいいわ。\n今日の私はすべてを許す寛大な心を\n持ってるのよ！
261 = "あははは、なんとでも言えばいいわ。\\n今日の私はすべてを許す寛大な心を\\n持ってるのよ！"

# カズマ
# ほーう？\nじゃあ、お前のダメっぷりを\n暴露しても許されるんだな！　よーし！
296 = "ほーう？\\nじゃあ、お前のダメっぷりを\\n暴露しても許されるんだな！　よーし！"

# アクア
# 仏の顔も三度までだからね。
314 = "仏の顔も三度までだからね。"

# カズマ
# いや、お前女神だろ。
262 = "いや、お前女神だろ。"

# アクア
# うふふ、今日は本当にいいお酒だわ。
264 = "うふふ、今日は本当にいいお酒だわ。"

# カズマ
# カニが美味いからか？
311 = "カニが美味いからか？"

# アクア
# やっぱり霜降り赤ガニは最高よね！\nもう、このちゅるんと吸い込めるほどの\n柔らかさがたまらないわ！
302 = "やっぱり霜降り赤ガニは最高よね！\\nもう、このちゅるんと吸い込めるほどの\\n柔らかさがたまらないわ！"

# アクア
# 美味しい物はどう食べても美味しいのよ。\nあは、これが生きてる幸せってものね！
361 = "美味しい物はどう食べても美味しいのよ。\\nあは、これが生きてる幸せってものね！"

# カズマ
# ずいぶん安っぽい幸せだが、\nまあ、俺も同意だな。
279 = "ずいぶん安っぽい幸せだが、\\nまあ、俺も同意だな。"

# カズマ
# 何かいいことでもあったのか？
315 = "何かいいことでもあったのか？"

# アクア
# んっふふ！\nそう見える？
305 = "んっふふ！\\nそう見える？"

# カズマ
# まあ、でないと\nその浮かれようの説明がつかないと思うんだが。
297 = "まあ、でないと\\nその浮かれようの説明がつかないと思うんだが。"

# アクア
# うふふふ、いいカンしてるじゃない。\nここだけの話ね、\nすっごい、いいことがあったの。
266 = "うふふふ、いいカンしてるじゃない。\\nここだけの話ね、\\nすっごい、いいことがあったの。"

# カズマ
# アクアがそこまで手放しに喜ぶってのは\n相当なもんだな。
308 = "アクアがそこまで手放しに喜ぶってのは\\n相当なもんだな。"

# アクア
# そうなのよ。\n私も最初は信じられなかったんだから。
280 = "そうなのよ。\\n私も最初は信じられなかったんだから。"

# カズマ
# それで、いい事ってなんなんだ？
282 = "それで、いい事ってなんなんだ？"

# アクア
# 内緒！\nというか、カズマには関係ないことだし。
316 = "内緒！\\nというか、カズマには関係ないことだし。"

# ダクネス
# うう……。\nさすがに、これ以上は食べられそうにないな。
263 = "うう……。\\nさすがに、これ以上は食べられそうにないな。"

# めぐみん
# ふにゃあ、幸せでぇす。
293 = "ふにゃあ、幸せでぇす。"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスもめぐみんも、\n　もう打ち止めって感じか。\n　ま、さすがに俺以上に食ってればなぁ）
373 = "（ダクネスもめぐみんも、\\n　もう打ち止めって感じか。\\n　ま、さすがに俺以上に食ってればなぁ）"

# カズマ（Ｍ）
# display as カズマ
# （アクアだけがまだまだ飲んで食って……\n　鋼鉄の胃袋だよな。\n　って、あれ？）
372 = "（アクアだけがまだまだ飲んで食って……\\n　鋼鉄の胃袋だよな。\\n　って、あれ？）"

# アクア
# すー、すー。
278 = "すー、すー。"

# カズマ（Ｍ）
# display as カズマ
# （……こいつもいつの間にか撃沈してたよ）
365 = "（……こいつもいつの間にか撃沈してたよ）"

# カズマ
# おいアクア？\n大丈夫か？
270 = "おいアクア？\\n大丈夫か？"

# アクア
# なぁに～～……。\n私を誰だと思ってんのよ～……。
289 = "なぁに～～……。\\n私を誰だと思ってんのよ～……。"

# カズマ
# なんだ、起きてるのか。\nこんな所で寝たら風邪引くぞ、部屋に戻れ。
290 = "なんだ、起きてるのか。\\nこんな所で寝たら風邪引くぞ、部屋に戻れ。"

# アクア
# 大丈夫よぉ。\nまだいけるんだからねぇ。
319 = "大丈夫よぉ。\\nまだいけるんだからねぇ。"

# カズマ（Ｍ）
# display as カズマ
# （いや、どう見てもダメだろ）
367 = "（いや、どう見てもダメだろ）"

# アクア
# えへへ、いい気持ちねぇ～。
267 = "えへへ、いい気持ちねぇ～。"

# アクア
# くー……すう……くぅ……。
276 = "くー……すう……くぅ……。"

# カズマ（Ｍ）
# display as カズマ
# （今度こそ寝ちまったか？）
374 = "（今度こそ寝ちまったか？）"

# カズマ（Ｍ）
# display as カズマ
# （まったく、ガキみたいな寝顔しやがって。\n　っていうか、よだれ垂らすなよ……）
371 = "（まったく、ガキみたいな寝顔しやがって。\\n　っていうか、よだれ垂らすなよ……）"

# アクア
# くう……すぅ……すぅぅ……。
274 = "くう……すぅ……すぅぅ……。"

# カズマ（Ｍ）
# display as カズマ
# （あーあ、このトラブルメーカーも\n　こうしていれば多少はマシなんだけどなぁ）
366 = "（あーあ、このトラブルメーカーも\\n　こうしていれば多少はマシなんだけどなぁ）"

[selections]
325 = "機嫌良すぎて気持ち悪いぞ"
# 311 = "カニが美味いからか？"
362 = "良いことあったのか？"
