# root_b21.txt.scn

[info]
0 = ""

[characters]
160 = "カズマ"
158 = "めぐみん"

[character_subs]

[script]
# lines: 20

# カズマ
# くぅ～、空気が美味い！\nそれに見ろよ、月があんなに綺麗だぜ？
145 = "くぅ～、空気が美味い！\\nそれに見ろよ、月があんなに綺麗だぜ？"

# めぐみん
# 本当ですね……。\nこうして、また月を見上げることができて\nよかったです。
165 = "本当ですね……。\\nこうして、また月を見上げることができて\\nよかったです。"

# カズマ
# まったくだ！\nできればあんな経験は二度とゴメンだな。
157 = "まったくだ！\\nできればあんな経験は二度とゴメンだな。"

# カズマ
# ま、心配しなくても\nそうそうあんな目にはあわないか。
156 = "ま、心配しなくても\\nそうそうあんな目にはあわないか。"

# めぐみん
# そう願いたいものです。\n特にカズマは、今後、\n軽率な行動は控えてもらいたいですね。
147 = "そう願いたいものです。\\n特にカズマは、今後、\\n軽率な行動は控えてもらいたいですね。"

# カズマ
# へいへい、わかってますって。\nにしても、結局、あの呪いはなんだったんだ？
154 = "へいへい、わかってますって。\\nにしても、結局、あの呪いはなんだったんだ？"

# めぐみん
# さあ、わかりません。\nきっとこの教会で、私達には\n想像もできないことがあったのでしょう。
146 = "さあ、わかりません。\\nきっとこの教会で、私達には\\n想像もできないことがあったのでしょう。"

# めぐみん
# それでも、最後にありがとうと……\nとても幸せそうで、でも悲しそうな声でしたね。
148 = "それでも、最後にありがとうと……\\nとても幸せそうで、でも悲しそうな声でしたね。"

# カズマ
# 散々な夜だったけど、\nなにはともあれ、終わりよければすべてよしか。
164 = "散々な夜だったけど、\\nなにはともあれ、終わりよければすべてよしか。"

# めぐみん
# …………。
142 = "…………。"

# カズマ
# なんだよ、その不満そうな目は。
152 = "なんだよ、その不満そうな目は。"

# めぐみん
# カズマにとっては、\nやっぱり、散々な夜だったんですか？
161 = "カズマにとっては、\\nやっぱり、散々な夜だったんですか？"

# カズマ
# それはそうだろ。\n閉じ込められた上に、フリとはいえ\n結婚式なんてやらされたんだから。
149 = "それはそうだろ。\\n閉じ込められた上に、フリとはいえ\\n結婚式なんてやらされたんだから。"

# めぐみん
# なんて？\nなんて、と言いましたか？
153 = "なんて？\\nなんて、と言いましたか？"

# めぐみん
# ていっ！
150 = "ていっ！"

# カズマ
# いってぇ！\nなんで殴るんだよ！？
143 = "いってぇ！\\nなんで殴るんだよ！？"

# めぐみん
# よくわかりません。\n強いて言うのなら、イラッとしたからです。
159 = "よくわかりません。\\n強いて言うのなら、イラッとしたからです。"

# カズマ
# なんだそりゃ！
151 = "なんだそりゃ！"

# めぐみん
# ほら、さっさと帰りますよ！
155 = "ほら、さっさと帰りますよ！"

# カズマ
# おい、待てって！\n置いていくなよ！
144 = "おい、待てって！\\n置いていくなよ！"

