# root_f15.txt.scn

[info]
0 = ""

[characters]
171 = "カズマ"
174 = "ダクネス"
169 = "めぐみん"
172 = "カズマ＆めぐみん"

[character_subs]
193 = "２人"

[script]
# lines: 23

# カズマ
# さて、そろそろ行くか。
159 = "さて、そろそろ行くか。"

# ダクネス
# なんだカズマ、出かけるのか？
164 = "なんだカズマ、出かけるのか？"

# カズマ
# ああ、ちょっと野暮用があってな。
150 = "ああ、ちょっと野暮用があってな。"

# めぐみん
# こんな時間にです？
158 = "こんな時間にです？"

# カズマ
# ほら昨夜、悪霊が出るってアクアが騒いでただろ？\nそれがどうも、街中に出るらしくてさ。
166 = "ほら昨夜、悪霊が出るってアクアが騒いでただろ？\\nそれがどうも、街中に出るらしくてさ。"

# ダクネス
# なるほど。\nそれでアクアを手伝うわけか。
162 = "なるほど。\\nそれでアクアを手伝うわけか。"

# カズマ
# いや違う、ウィズだ。
154 = "いや違う、ウィズだ。"

# めぐみん
# また奇妙な組み合わせですね。
168 = "また奇妙な組み合わせですね。"

# カズマ
# まあ、成り行きでな。
167 = "まあ、成り行きでな。"

# カズマ
# というわけで、今日は遅くなるから先に寝ててくれ。
161 = "というわけで、今日は遅くなるから先に寝ててくれ。"

# めぐみん
# わかりました。
170 = "わかりました。"

# カズマ
# あっ、そうそう。\nアクアも帰りが遅くなるって\n言ってたからさ。
153 = "あっ、そうそう。\\nアクアも帰りが遅くなるって\\n言ってたからさ。"

# ダクネス
# ふむ、アクアも除霊だろうか？
165 = "ふむ、アクアも除霊だろうか？"

# カズマ
# クエストを受けてるとかならわかるけど、\nアクアが無償で動くわけないだろ。
173 = "クエストを受けてるとかならわかるけど、\\nアクアが無償で動くわけないだろ。"

# めぐみん
# ですが、昨夜はずっと\n除霊をしてまわっていたらしいですよ。
160 = "ですが、昨夜はずっと\\n除霊をしてまわっていたらしいですよ。"

# カズマ
# あいつが？　見返りもなしにか？
152 = "あいつが？　見返りもなしにか？"

# めぐみん
# 私も、珍しいこともあるなと思いました。
192 = "私も、珍しいこともあるなと思いました。"

# ダクネス
# お前たちのアクアの印象はどんなものなんだ。
155 = "お前たちのアクアの印象はどんなものなんだ。"

# カズマ＆めぐみん
# display as ２人
# がめつい。
157 = "がめつい。"

# ダクネス
# お前たちは……。
156 = "お前たちは……。"

# カズマ
# なんか裏がありそうな気もするが……\n今はウィズが待ってるからな。\n行ってくる。
163 = "なんか裏がありそうな気もするが……\\n今はウィズが待ってるからな。\\n行ってくる。"

# ダクネス
# 気を付けてな。\nああ、もしアクアに会ったら伝えてくれ。\nせめて夕飯までには帰ってこいと。
178 = "気を付けてな。\\nああ、もしアクアに会ったら伝えてくれ。\\nせめて夕飯までには帰ってこいと。"

# カズマ
# ああ、わかった。
151 = "ああ、わかった。"

