# root_d14.txt.scn

[info]
0 = ""

[characters]
195 = "カズマ"
237 = "魔術師風の男冒険者"
196 = "カズマ（Ｍ）"
197 = "クリス"
208 = "戦士風の男冒険者"
211 = "盗賊風の男冒険者"

[character_subs]
236 = "魔術師冒険者"
# 195 = "カズマ"
207 = "戦士冒険者"
210 = "盗賊冒険者"

[script]
# lines: 42

# カズマ
# はあっ、はあっ、はあっ、はあっ、はあっ……！
191 = "はあっ、はあっ、はあっ、はあっ、はあっ……！"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# 待てー！
206 = "待てー！"

# カズマ（Ｍ）
# display as カズマ
# （待てと言われて待つバカがいるかっての！\n　しつこい奴らだな！）
245 = "（待てと言われて待つバカがいるかっての！\\n　しつこい奴らだな！）"

# クリス
# それで、これからどうするの？
179 = "それで、これからどうするの？"

# カズマ
# とにかく逃げる！
187 = "とにかく逃げる！"

# クリス
# つまり何も考えてないんだ？\nカズマらしいって言えばカズマらしいけどさ……\n制限時間いっぱいまで逃げるつもり？
183 = "つまり何も考えてないんだ？\\nカズマらしいって言えばカズマらしいけどさ……\\n制限時間いっぱいまで逃げるつもり？"

# カズマ（Ｍ）
# display as カズマ
# （そう言えば、だいぶ日が傾いてきたな。\n　正確な時間はわからないけど、これだと\n　制限時間まであと１時間くらいってとこか）
240 = "（そう言えば、だいぶ日が傾いてきたな。\\n　正確な時間はわからないけど、これだと\\n　制限時間まであと１時間くらいってとこか）"

# カズマ（Ｍ）
# display as カズマ
# （……１時間、クリスと一緒に逃げ切れるか？\n　街にいる人間、全員が敵だと考えられる\n　この状況で）
238 = "（……１時間、クリスと一緒に逃げ切れるか？\\n　街にいる人間、全員が敵だと考えられる\\n　この状況で）"

# クリス
# ねえカズマ、止まった方がいいと思うよ？
190 = "ねえカズマ、止まった方がいいと思うよ？"

# カズマ
# そんなことしたら捕まるだろ！
180 = "そんなことしたら捕まるだろ！"

# クリス
# でもさ、ほら、前見てよ。
186 = "でもさ、ほら、前見てよ。"

# カズマ（Ｍ）
# display as カズマ
# （なっ、いつの間に！）
241 = "（なっ、いつの間に！）"

# 戦士風の男冒険者
# display as 戦士冒険者
# さあ、遊びは終わりだ。\nよくもまぁ、手こずらせてくれたな。\n観念して大人しく捕まってもらおうか。
176 = "さあ、遊びは終わりだ。\\nよくもまぁ、手こずらせてくれたな。\\n観念して大人しく捕まってもらおうか。"

# クリス
# だってさカズマ。\nさあ、どうする？
182 = "だってさカズマ。\\nさあ、どうする？"

# カズマ（Ｍ）
# display as カズマ
# （考えろ。\n　この場所から逃げる方法を。\n　何かきっとあるはずだ！）
246 = "（考えろ。\\n　この場所から逃げる方法を。\\n　何かきっとあるはずだ！）"

# カズマ（Ｍ）
# display as カズマ
# （クリエイト・アースで土を作って\n　ウインド・ブレスで目つぶしをする……\n　いやダメだ、それじゃ、この人数は多すぎる）
243 = "（クリエイト・アースで土を作って\\n　ウインド・ブレスで目つぶしをする……\\n　いやダメだ、それじゃ、この人数は多すぎる）"

# カズマ（Ｍ）
# display as カズマ
# （クリエイト・ウォーターで水を撒いて\n　フリーズで凍らせるか？\n　いや、それも俺達の逃げ場がないからダメだ）
244 = "（クリエイト・ウォーターで水を撒いて\\n　フリーズで凍らせるか？\\n　いや、それも俺達の逃げ場がないからダメだ）"

# カズマ（Ｍ）
# display as カズマ
# （落ち着け、落ち着いて考えろ！\n　こいつらは金に目がくらんで\n　クリスを捕まえようとしている金の亡者だ）
247 = "（落ち着け、落ち着いて考えろ！\\n　こいつらは金に目がくらんで\\n　クリスを捕まえようとしている金の亡者だ）"

# カズマ（Ｍ）
# display as カズマ
# （こいつらにとって大事な物はなんだ？\n　大切な物は……そうだ！）
239 = "（こいつらにとって大事な物はなんだ？\\n　大切な物は……そうだ！）"

# カズマ
# クリス、下がってろ。
198 = "クリス、下がってろ。"

# クリス
# その体勢って。\nなんで今、スティールなの！？
177 = "その体勢って。\\nなんで今、スティールなの！？"

# 戦士風の男冒険者
# display as 戦士冒険者
# はっ、スティールだとぉ？\nそんなものしてなんになる。\n往生際の悪いやつだな。
192 = "はっ、スティールだとぉ？\\nそんなものしてなんになる。\\n往生際の悪いやつだな。"

# カズマ
# 俺は魔王軍の幹部、\nデュラハンの首でさえ盗める男だぞ？
205 = "俺は魔王軍の幹部、\\nデュラハンの首でさえ盗める男だぞ？"

# カズマ
# 盗られて惜しい物があるなら、\n逃げたほうが身のためだと思うぜ？
209 = "盗られて惜しい物があるなら、\\n逃げたほうが身のためだと思うぜ？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# だ、誰がそんな脅しに乗るかよ！
181 = "だ、誰がそんな脅しに乗るかよ！"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# ですが……あいつが魔王軍の幹部である\nデュラハンの首をスティールして、\nこの街を救ったのは事実ですよ？
185 = "ですが……あいつが魔王軍の幹部である\\nデュラハンの首をスティールして、\\nこの街を救ったのは事実ですよ？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# なんだと……？
188 = "なんだと……？"

# カズマ
# お前、高そーうなロッド、持ってるじゃないか。
174 = "お前、高そーうなロッド、持ってるじゃないか。"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# ひっ！
193 = "ひっ！"

# カズマ
# その短剣、実は値打ちもんなんだろ？
178 = "その短剣、実は値打ちもんなんだろ？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# う、うっ……。
171 = "う、うっ……。"

# カズマ
# お前、いい装備揃えてるじゃねえか。\nさては、結構金を持ってるなぁ。
173 = "お前、いい装備揃えてるじゃねえか。\\nさては、結構金を持ってるなぁ。"

# 戦士風の男冒険者
# display as 戦士冒険者
# ぬぐ！
189 = "ぬぐ！"

# カズマ
# さあ、さあ！\n誰の何を盗んでやるかな？\nいくぞ、いくぞ、いくぞ……！
175 = "さあ、さあ！\\n誰の何を盗んでやるかな？\\nいくぞ、いくぞ、いくぞ……！"

# カズマ
# スティーーーールッ！！
200 = "スティーーーールッ！！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# お、おお、お、俺の短剣は！？
172 = "お、おお、お、俺の短剣は！？"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# ロッド！\n借金までして買ったロッドは！？
203 = "ロッド！\\n借金までして買ったロッドは！？"

# カズマ（Ｍ）
# display as カズマ
# （よし、みんな自分のことに必死だ！）
242 = "（よし、みんな自分のことに必死だ！）"

# クリス
# ひっ！\nひい……。
194 = "ひっ！\\nひい……。"

# カズマ
# クリス！\n今のうちだ、逃げるぞ！
199 = "クリス！\\n今のうちだ、逃げるぞ！"

# クリス
# で、でも……！
184 = "で、でも……！"

# カズマ
# いいから、走れ！
170 = "いいから、走れ！"

