# root_c16.txt.scn

[info]
0 = ""

[characters]
277 = "カズマ"
280 = "カズマ（Ｍ）"
275 = "アクア"
271 = "めぐみん"
282 = "ダクネス"

[character_subs]
# 277 = "カズマ"

[script]
# lines: 82

# カズマ
# はあ……。
263 = "はあ……。"

# カズマ（Ｍ）
# display as カズマ
# （途中までいい感じのデートだったのに、\n　アクアとめぐみんめ……）
353 = "（途中までいい感じのデートだったのに、\\n　アクアとめぐみんめ……）"

# カズマ（Ｍ）
# display as カズマ
# （あいつらが余計なことをしなければ、\n　俺とダクネスは、もっとキャッキャウフフな\n　展開になっていたはずなのに！）
329 = "（あいつらが余計なことをしなければ、\\n　俺とダクネスは、もっとキャッキャウフフな\\n　展開になっていたはずなのに！）"

# カズマ（Ｍ）
# display as カズマ
# （あとでこの責任はきっちりと取らせてやる！）
330 = "（あとでこの責任はきっちりと取らせてやる！）"

# カズマ（Ｍ）
# display as カズマ
# （アクアのヤツが泣きじゃくりながら\n　抱きついてくるから、こっちまでヌルヌルに\n　なっちまったし！）
344 = "（アクアのヤツが泣きじゃくりながら\\n　抱きついてくるから、こっちまでヌルヌルに\\n　なっちまったし！）"

# カズマ（Ｍ）
# display as カズマ
# （そういや、ダクネスもヌルヌルになって\n　赤い顔をして震えていたけど、大丈夫だろうか？\n　また変な快感に目覚めてなきゃいいんだが）
336 = "（そういや、ダクネスもヌルヌルになって\\n　赤い顔をして震えていたけど、大丈夫だろうか？\\n　また変な快感に目覚めてなきゃいいんだが）"

# アクア
# ああ、もう！\n今日は最悪最低な日だわ！
237 = "ああ、もう！\\n今日は最悪最低な日だわ！"

# カズマ
# なっ！？
261 = "なっ！？"

# めぐみん
# 結局、私も\nまたあのヌルヌルを経験してしまいました。
326 = "結局、私も\\nまたあのヌルヌルを経験してしまいました。"

# ダクネス
# あ、あれは……\n噂には聞いていたが、結構来るものがあるな……。
235 = "あ、あれは……\\n噂には聞いていたが、結構来るものがあるな……。"

# カズマ（Ｍ）
# display as カズマ
# （……え？\n　なんでダクネス達の声がするんだ？\n　あいつら、街の大衆浴場に行ったはずだよな？）
328 = "（……え？\\n　なんでダクネス達の声がするんだ？\\n　あいつら、街の大衆浴場に行ったはずだよな？）"

# アクア
# しかも、こんな時に限って\n大衆浴場が休みだなんて。
253 = "しかも、こんな時に限って\\n大衆浴場が休みだなんて。"

# めぐみん
# 早くヌルヌルを落としたいです……。
294 = "早くヌルヌルを落としたいです……。"

# カズマ（Ｍ）
# display as カズマ
# （ま、まさか、俺が入っているのに\n　気づいてないのか？）
341 = "（ま、まさか、俺が入っているのに\\n　気づいてないのか？）"

# カズマ（Ｍ）
# display as カズマ
# （まずいっ！\n　ここは潜伏スキルで！！）
342 = "（まずいっ！\\n　ここは潜伏スキルで！！）"

# アクア
# あら？\nお湯が沸いてるわね。
238 = "あら？\\nお湯が沸いてるわね。"

# めぐみん
# きっと、カズマが入ったんでしょう。
244 = "きっと、カズマが入ったんでしょう。"

# カズマ（Ｍ）
# display as カズマ
# （俺は壁だー。\n　何も見えないし、何も聞こえない。\n　もちろん何も感じない）
347 = "（俺は壁だー。\\n　何も見えないし、何も聞こえない。\\n　もちろん何も感じない）"

# アクア
# あーあ。\nもうカエルはこりごりだって思ってたのに。
239 = "あーあ。\\nもうカエルはこりごりだって思ってたのに。"

# ダクネス
# 今回は、私も不覚を取ってしまったな。
285 = "今回は、私も不覚を取ってしまったな。"

# カズマ（Ｍ）
# display as カズマ
# （いつもだろ、いつも！）
332 = "（いつもだろ、いつも！）"

# ダクネス
# しかし、ジャイアントトードに\n飲み込まれるというのは、ああも快感……\nいや、おぞましいことだったとは。
251 = "しかし、ジャイアントトードに\\n飲み込まれるというのは、ああも快感……\\nいや、おぞましいことだったとは。"

# カズマ（Ｍ）
# display as カズマ
# （俺は壁。\n　聞こえない、見えない、\n　見えない、聞こえない！）
346 = "（俺は壁。\\n　聞こえない、見えない、\\n　見えない、聞こえない！）"

# めぐみん
# ……ダクネス。\nつかぬことを聞きますが、\nどうすれば、そんなに大きく育つのですか？
233 = "……ダクネス。\\nつかぬことを聞きますが、\\nどうすれば、そんなに大きく育つのですか？"

# カズマ（Ｍ）
# display as カズマ
# （俺は壁！）
348 = "（俺は壁！）"

# ダクネス
# おっ、おい！？　急に触るな！
242 = "おっ、おい！？　急に触るな！"

# カズマ（Ｍ）
# display as カズマ
# （何も聞こえない！）
345 = "（何も聞こえない！）"

# アクア
# ん？\n何か気配がしたような。
274 = "ん？\\n何か気配がしたような。"

# カズマ（Ｍ）
# display as カズマ
# （いかんいかん！\n　ここで集中を解いたら、\n　俺がここにいるのがバレてしまう！）
331 = "（いかんいかん！\\n　ここで集中を解いたら、\\n　俺がここにいるのがバレてしまう！）"

# カズマ（Ｍ）
# display as カズマ
# （集中だ集中！\n　心を無にして壁になりきるんだ！)
354 = "（集中だ集中！\\n　心を無にして壁になりきるんだ！)"

# ダクネス
# こ、こら、めぐみん！\n手つきがいやらしいぞ！
247 = "こ、こら、めぐみん！\\n手つきがいやらしいぞ！"

# カズマ（Ｍ）
# display as カズマ
# （うん、無理！\n　だって男の子だもの！）
334 = "（うん、無理！\\n　だって男の子だもの！）"

# カズマ（Ｍ）
# display as カズマ
# （妄想が捗っても仕方ないよね！）
349 = "（妄想が捗っても仕方ないよね！）"

# ダクネス
# こ、こら、めぐみんくすぐったいだろう。
246 = "こ、こら、めぐみんくすぐったいだろう。"

# めぐみん
# 同じ物を食べているはずなのに、\nどうして私の胸には栄養がいかないのでしょう？
289 = "同じ物を食べているはずなのに、\\nどうして私の胸には栄養がいかないのでしょう？"

# ダクネス
# 心配するな。\nめぐみんはまだ成長過程だ。\nそのうち大きくなる。
293 = "心配するな。\\nめぐみんはまだ成長過程だ。\\nそのうち大きくなる。"

# めぐみん
# そういうものでしょうか。\nああ、こんなふくよかな胸があったら、\n人生が色々と楽しくなるかもしれませんね。
254 = "そういうものでしょうか。\\nああ、こんなふくよかな胸があったら、\\n人生が色々と楽しくなるかもしれませんね。"

# ダクネス
# こ、こらっ！\nだから、そんなに強く触るな。
248 = "こ、こらっ！\\nだから、そんなに強く触るな。"

# めぐみん
# いいではないですか。\n触って減るものではないですし。
240 = "いいではないですか。\\n触って減るものではないですし。"

# ダクネス
# も、もうそれくらいにしておけ。\nくすぐったい……。
272 = "も、もうそれくらいにしておけ。\\nくすぐったい……。"

# めぐみん
# ダクネスの胸にはご利益的な何かがあると\n思うのですよ。
283 = "ダクネスの胸にはご利益的な何かがあると\\n思うのですよ。"

# ダクネス
# そんなものはない。\nちょ、あはは、やめろめぐみん！
257 = "そんなものはない。\\nちょ、あはは、やめろめぐみん！"

# アクア
# はああ～、ねえダクネス？
264 = "はああ～、ねえダクネス？"

# ダクネス
# ん、なんだ？
273 = "ん、なんだ？"

# アクア
# 今日ずっと尾行してて思ったんだけど、\nカズマにあそこまでしてあげる理由が、\n私にはわからないのよねー。
286 = "今日ずっと尾行してて思ったんだけど、\\nカズマにあそこまでしてあげる理由が、\\n私にはわからないのよねー。"

# めぐみん
# それは私も同じですね。
255 = "それは私も同じですね。"

# カズマ（Ｍ）
# display as カズマ
# （ふん！　恋を知らない\n　哀れな駄女神にロリっ娘め！）
339 = "（ふん！　恋を知らない\\n　哀れな駄女神にロリっ娘め！）"

# カズマ（Ｍ）
# display as カズマ
# （なんでもしてあげたいという気持ちこそが\n　愛だろうが！）
337 = "（なんでもしてあげたいという気持ちこそが\\n　愛だろうが！）"

# ダクネス
# ……端から見ていたら滑稽だろうな。\nだが、これは私がしたいからしているだけだ。
234 = "……端から見ていたら滑稽だろうな。\\nだが、これは私がしたいからしているだけだ。"

# カズマ（Ｍ）
# display as カズマ
# （ほら見ろ！\n　ダクネスの俺に対する気持ちは、\n　こんなにも深く強いものなんだぞ！）
340 = "（ほら見ろ！\\n　ダクネスの俺に対する気持ちは、\\n　こんなにも深く強いものなんだぞ！）"

# アクア
# まぁ、ダクネスがそこまで言うんだったら\n私は止めないけどね。
269 = "まぁ、ダクネスがそこまで言うんだったら\\n私は止めないけどね。"

# めぐみん
# しかし、監視は必要なのでは？\nカズマのことです、\n何をしでかすかわかりませんよ？
252 = "しかし、監視は必要なのでは？\\nカズマのことです、\\n何をしでかすかわかりませんよ？"

# カズマ（Ｍ）
# display as カズマ
# （恋人同士を監視してなんの意味がある！）
351 = "（恋人同士を監視してなんの意味がある！）"

# カズマ（Ｍ）
# display as カズマ
# （恋人同士ってのはな、イチャイチャするのが\n　当たり前で、人目に付かないところでは\n　もっと凄いことするんだよ！）
350 = "（恋人同士ってのはな、イチャイチャするのが\\n　当たり前で、人目に付かないところでは\\n　もっと凄いことするんだよ！）"

# アクア
# あ。
236 = "あ。"

# めぐみん
# あ。
# 236 = "あ。"

# ダクネス
# カ、カズマ！？
276 = "カ、カズマ！？"

# カズマ（Ｍ）
# display as カズマ
# （ん……なんか背中に突き刺さるような\n　視線を感じるが……）
343 = "（ん……なんか背中に突き刺さるような\\n　視線を感じるが……）"

# カズマ（Ｍ）
# display as カズマ
# （気のせい気のせい。\n　俺は今、潜伏スキルで完璧に隠れて……）
352 = "（気のせい気のせい。\\n　俺は今、潜伏スキルで完璧に隠れて……）"

# カズマ
# って、解けてるぅー！
259 = "って、解けてるぅー！"

# カズマ（Ｍ）
# display as カズマ
# （しまった、さっき集中力を切らしたときに\n　解けちまったんだ！）
335 = "（しまった、さっき集中力を切らしたときに\\n　解けちまったんだ！）"

# アクア
# ねえ、カズマさん？
262 = "ねえ、カズマさん？"

# カズマ
# ぼくは壁だよ。
267 = "ぼくは壁だよ。"

# アクア
# こんな所で何をやっているのかしら？
249 = "こんな所で何をやっているのかしら？"

# カズマ
# ぼくは壁なんだ。
268 = "ぼくは壁なんだ。"

# めぐみん
# 壁でしたら、殴っても蹴っても\n問題ありませんよね。
290 = "壁でしたら、殴っても蹴っても\\n問題ありませんよね。"

# カズマ
# そんなことをしてはいけないよ。\n修理で費用がかかるじゃないか。
256 = "そんなことをしてはいけないよ。\\n修理で費用がかかるじゃないか。"

# ダクネス
# カズマ……見たのか？
278 = "カズマ……見たのか？"

# カズマ
# 見てないよ。
327 = "見てないよ。"

# ダクネス
# くぅぅ、見たのだな！？
245 = "くぅぅ、見たのだな！？"

# カズマ
# み、見てない！\n本当だ、信じてくれ！
270 = "み、見てない！\\n本当だ、信じてくれ！"

# ダクネス
# ふ、振り向くな！\n見たら……ぶっ、ぶっころすぞ！
266 = "ふ、振り向くな！\\n見たら……ぶっ、ぶっころすぞ！"

# カズマ（Ｍ）
# display as カズマ
# （うお、ダクネス怖い！）
333 = "（うお、ダクネス怖い！）"

# アクア
# さて、カズマさん？\nどういうことか説明して貰いましょうか。
250 = "さて、カズマさん？\\nどういうことか説明して貰いましょうか。"

# カズマ
# おっ、落ち着け！\n俺はお前らより先に風呂に入ってたんだ！
243 = "おっ、落ち着け！\\n俺はお前らより先に風呂に入ってたんだ！"

# めぐみん
# ちょっと、振り向かないでくださいよ！
258 = "ちょっと、振り向かないでくださいよ！"

# カズマ
# と、とにかく話を聞いてくれ！\nこれは事故だ、事故なんだ！
260 = "と、とにかく話を聞いてくれ！\\nこれは事故だ、事故なんだ！"

# アクア
# カズマさぁん？\n言い訳なんて、男らしくないんじゃないかしら？
279 = "カズマさぁん？\\n言い訳なんて、男らしくないんじゃないかしら？"

# カズマ（Ｍ）
# display as カズマ
# （はっ、この背中が焼けるような気配は！！）
338 = "（はっ、この背中が焼けるような気配は！！）"

# カズマ
# おいアクア、やめろ！\n何をするつもりだ！
241 = "おいアクア、やめろ！\\n何をするつもりだ！"

# アクア
# ゴッドブローォォォォッ！
281 = "ゴッドブローォォォォッ！"

# カズマ
# ひぎゃあああああああああああああ！！
265 = "ひぎゃあああああああああああああ！！"

