# root_b11.txt.scn

[info]
0 = ""

[characters]
237 = "カズマ（Ｍ）"
235 = "カズマ"
230 = "めぐみん"

[character_subs]
# 235 = "カズマ"

[script]
# lines: 81

# カズマ（Ｍ）
# display as カズマ
# （しかし、この教会に呪いをかけたのは\n　どこの誰なんだ？）
263 = "（しかし、この教会に呪いをかけたのは\\n　どこの誰なんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （教会で働く人じゃなくて\n　教会自体に呪いをかけるってことは、\n　建物に恨みがあるって考えるべきなのか？）
277 = "（教会で働く人じゃなくて\\n　教会自体に呪いをかけるってことは、\\n　建物に恨みがあるって考えるべきなのか？）"

# カズマ（Ｍ）
# display as カズマ
# （にしても、建物に恨みを持つって\n　どんな状況なんだよ）
273 = "（にしても、建物に恨みを持つって\\n　どんな状況なんだよ）"

# カズマ（Ｍ）
# display as カズマ
# （その上、呪いを解くには\n　結婚式をあげるしかない、なんて……）
265 = "（その上、呪いを解くには\\n　結婚式をあげるしかない、なんて……）"

# カズマ（Ｍ）
# display as カズマ
# （どんな理由で呪いを掛けたのか\n　さっぱりわからん！）
270 = "（どんな理由で呪いを掛けたのか\\n　さっぱりわからん！）"

# カズマ（Ｍ）
# display as カズマ
# （な、なんだ、なんの音だ！？\n　まさか呪いが発動したのか！？）
271 = "（な、なんだ、なんの音だ！？\\n　まさか呪いが発動したのか！？）"

# カズマ（Ｍ）
# display as カズマ
# （もしかして、ここまで何もなかったのは、\n　俺達が離れる時を狙っていたからなのか？）
274 = "（もしかして、ここまで何もなかったのは、\\n　俺達が離れる時を狙っていたからなのか？）"

# カズマ（Ｍ）
# display as カズマ
# （だとしたら、めぐみんが危ない！）
266 = "（だとしたら、めぐみんが危ない！）"

# カズマ（Ｍ）
# display as カズマ
# （！！　誰かがいる？\n　いや、もしかして、呪いで呼び出された\n　幽霊なんて可能性も……）
279 = "（！！　誰かがいる？\\n　いや、もしかして、呪いで呼び出された\\n　幽霊なんて可能性も……）"

# カズマ（Ｍ）
# display as カズマ
# （いや、結論を急ぐな、\n　まだ呪いと決まったわけじゃない）
259 = "（いや、結論を急ぐな、\\n　まだ呪いと決まったわけじゃない）"

# カズマ
# め、めぐみんか！\nどうしたんだよ、\n風呂に入るんじゃなかったのか。
229 = "め、めぐみんか！\\nどうしたんだよ、\\n風呂に入るんじゃなかったのか。"

# カズマ
# それとも、やっぱり怖くなって\n一緒に入って欲しくなったのか？\n仕方ないなぁ！
210 = "それとも、やっぱり怖くなって\\n一緒に入って欲しくなったのか？\\n仕方ないなぁ！"

# カズマ
# …………。
191 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （今ので反応がないってことは、\n　めぐみんじゃない。\n　じゃ、じゃあ、この足音は……誰だよ！）
276 = "（今ので反応がないってことは、\\n　めぐみんじゃない。\\n　じゃ、じゃあ、この足音は……誰だよ！）"

# カズマ（Ｍ）
# display as カズマ
# （どんどん近づいてきてる……）
269 = "（どんどん近づいてきてる……）"

# カズマ（Ｍ）
# display as カズマ
# （こ、このまま黙ってやられてたまるか！\n　振り向いて正体を確かめてやる！）
261 = "（こ、このまま黙ってやられてたまるか！\\n　振り向いて正体を確かめてやる！）"

# カズマ（Ｍ）
# display as カズマ
# （せーの！）
264 = "（せーの！）"

# カズマ
# うぎゃあああああああああああああ！！
196 = "うぎゃあああああああああああああ！！"

# カズマ（Ｍ）
# display as カズマ
# （ハアハアハアハア、あかん、あれはあかん！）
275 = "（ハアハアハアハア、あかん、あれはあかん！）"

# カズマ（Ｍ）
# display as カズマ
# （な、なんだあの宙に浮く白い物は！？\n　まさか幽霊っ！？）
272 = "（な、なんだあの宙に浮く白い物は！？\\n　まさか幽霊っ！？）"

# カズマ（Ｍ）
# display as カズマ
# （ついてきてるし！　しかも早足で！\n　なんで幽霊なのにこんなアクティブなんだよ！）
267 = "（ついてきてるし！　しかも早足で！\\n　なんで幽霊なのにこんなアクティブなんだよ！）"

# カズマ（Ｍ）
# display as カズマ
# （と、とにかく隠れないと！\n　アンデッドだったらシャレにならん！）
268 = "（と、とにかく隠れないと！\\n　アンデッドだったらシャレにならん！）"

# めぐみん
# いやああああああああああ！！
195 = "いやああああああああああ！！"

# カズマ
# うぎゃあああああああああ！！
197 = "うぎゃあああああああああ！！"

# カズマ
# って、めぐみんか、驚かせるなバカ！
216 = "って、めぐみんか、驚かせるなバカ！"

# めぐみん
# いやああああああああああ！！
# 195 = "いやああああああああああ！！"

# カズマ
# って、お前は黙れ！\n気がつかれるだろ！！
215 = "って、お前は黙れ！\\n気がつかれるだろ！！"

# めぐみん
# いやああああああああああ！！
# 195 = "いやああああああああああ！！"

# カズマ
# よーしよしよし、いい子だから落ちつけ。\n大丈夫、何も怖くないからな～？
232 = "よーしよしよし、いい子だから落ちつけ。\\n大丈夫、何も怖くないからな～？"

# めぐみん
# こ、この状況でどう落ちつけと言うのです！\nこんな堂々とした覗き、ありえませんよっ！
204 = "こ、この状況でどう落ちつけと言うのです！\\nこんな堂々とした覗き、ありえませんよっ！"

# めぐみん
# 開き直ったんですか！？\n開き直って、直接間近で凝視してやろうという\n魂胆ですか！
258 = "開き直ったんですか！？\\n開き直って、直接間近で凝視してやろうという\\n魂胆ですか！"

# めぐみん
# 変態の上位職、ド変態に\nクラスアップしたんですか！？\nだから人間の言葉を理解できないのですか！？
242 = "変態の上位職、ド変態に\\nクラスアップしたんですか！？\\nだから人間の言葉を理解できないのですか！？"

# めぐみん
# 見損ないましたよ、ええ、見損ないましたとも！
256 = "見損ないましたよ、ええ、見損ないましたとも！"

# めぐみん
# へたれでクズでも、\nこんな犯罪まがいの行動に走る男だとは\n思っていませんでしたからね！
226 = "へたれでクズでも、\\nこんな犯罪まがいの行動に走る男だとは\\n思っていませんでしたからね！"

# カズマ
# お前、言わせておけば！\n俺にだって選ぶ権利があるんだからな！
201 = "お前、言わせておけば！\\n俺にだって選ぶ権利があるんだからな！"

# めぐみん
# なんです、どういう意味ですか！
223 = "なんです、どういう意味ですか！"

# カズマ
# あー、ゆんゆん！　だったらよかったのに。
193 = "あー、ゆんゆん！　だったらよかったのに。"

# めぐみん
# 言いましたね？\nでは、ゆんゆんに伝えておいてあげますよ。
257 = "言いましたね？\\nでは、ゆんゆんに伝えておいてあげますよ。"

# めぐみん
# カズマがゆんゆんでいやらしい想像をしていたと。
236 = "カズマがゆんゆんでいやらしい想像をしていたと。"

# カズマ
# お前マジでやめろ。\nいや、すんません、本当にやめてください。
202 = "お前マジでやめろ。\\nいや、すんません、本当にやめてください。"

# めぐみん
# とにかく出ていってください！\nさもないと、撃ちますからね！
218 = "とにかく出ていってください！\\nさもないと、撃ちますからね！"

# カズマ
# 待て！　俺の話を聞け！
244 = "待て！　俺の話を聞け！"

# めぐみん
# 節操無しの変態の話などに聞く耳持ちません！
255 = "節操無しの変態の話などに聞く耳持ちません！"

# カズマ
# 俺はロリっ子属性なんて持ち合わせてねえんだよ！
239 = "俺はロリっ子属性なんて持ち合わせてねえんだよ！"

# めぐみん
# な、なにおう！？\n言いましたね？\n今ロリっ子って言いましたね！？
221 = "な、なにおう！？\\n言いましたね？\\n今ロリっ子って言いましたね！？"

# カズマ
# 実際、ロリっ子だろ。
243 = "実際、ロリっ子だろ。"

# めぐみん
# 成長期が少し遅いだけです！\nい、今に見てなさい、\n絶対に謝らせてやりますからね！！
245 = "成長期が少し遅いだけです！\\nい、今に見てなさい、\\n絶対に謝らせてやりますからね！！"

# めぐみん
# それはそうと、\nいつまでそうしているつもりなんですか！\n早く出て行ってください！
211 = "それはそうと、\\nいつまでそうしているつもりなんですか！\\n早く出て行ってください！"

# カズマ
# それはできないんだ！\n頼む、しばらくかくまってくれ！
212 = "それはできないんだ！\\n頼む、しばらくかくまってくれ！"

# めぐみん
# かくまう？\nなにからですか！
203 = "かくまう？\\nなにからですか！"

# カズマ
# 白いなにかが現れたんだよ！\n幽霊かもしれない！
247 = "白いなにかが現れたんだよ！\\n幽霊かもしれない！"

# めぐみん
# ゆ、幽霊……。
231 = "ゆ、幽霊……。"

# カズマ
# それで逃げてきたんだよ。\nこの部屋に入ったのは偶然だ。
209 = "それで逃げてきたんだよ。\\nこの部屋に入ったのは偶然だ。"

# めぐみん
# わ、わかりました。\nなら、せめて後ろを向いてください。
233 = "わ、わかりました。\\nなら、せめて後ろを向いてください。"

# カズマ
# なんで？
224 = "なんで？"

# めぐみん
# 服を着るからですよ！
246 = "服を着るからですよ！"

# カズマ
# わかったよ。
234 = "わかったよ。"

# めぐみん
# あと目もつむってくださいね。
192 = "あと目もつむってくださいね。"

# カズマ（Ｍ）
# display as カズマ
# （注文の多い奴だな）
278 = "（注文の多い奴だな）"

# めぐみん
# まったく、散々な夜です。
228 = "まったく、散々な夜です。"

# カズマ
# それは俺も同意する。
213 = "それは俺も同意する。"

# めぐみん
# それで、幽霊というのは本当の話なんですよね？
208 = "それで、幽霊というのは本当の話なんですよね？"

# カズマ
# 嘘をつく理由がないだろ。
240 = "嘘をつく理由がないだろ。"

# めぐみん
# 堂々と覗きをしたかったからでは？
241 = "堂々と覗きをしたかったからでは？"

# カズマ
# だから違うってさっきから言ってるだろ！
214 = "だから違うってさっきから言ってるだろ！"

# めぐみん
# はあ……このまま、朝までここで\n過ごさなければならないなんて……。
225 = "はあ……このまま、朝までここで\\n過ごさなければならないなんて……。"

# カズマ（Ｍ）
# display as カズマ
# （うん、これはマズイ）
260 = "（うん、これはマズイ）"

# めぐみん
# しかもカズマとふたりっきりだなんて、\nどんな罰ゲームですか。
206 = "しかもカズマとふたりっきりだなんて、\\nどんな罰ゲームですか。"

# カズマ（Ｍ）
# display as カズマ
# （この暗闇と音だけの情報が、\n　俺の妄想力を加速させている）
262 = "（この暗闇と音だけの情報が、\\n　俺の妄想力を加速させている）"

# カズマ
# な、なあ、俺ちょっと様子を見てくる！\nめぐみんはここに隠れてろ！
220 = "な、なあ、俺ちょっと様子を見てくる！\\nめぐみんはここに隠れてろ！"

# めぐみん
# ま、待ってください！
227 = "ま、待ってください！"

# カズマ
# え、なんだよ……。
199 = "え、なんだよ……。"

# めぐみん
# こんな状況でレディを一人きりにするなんて\n非常識だと思うのです。
205 = "こんな状況でレディを一人きりにするなんて\\n非常識だと思うのです。"

# カズマ
# うん、つまり？
198 = "うん、つまり？"

# めぐみん
# １人にしないでください。\nお願いします、一緒にいてください。\n怖いんです……。
280 = "１人にしないでください。\\nお願いします、一緒にいてください。\\n怖いんです……。"

# カズマ
# いや、でもさ、今の状況って\nよくよく考えたら……あれじゃん？
194 = "いや、でもさ、今の状況って\\nよくよく考えたら……あれじゃん？"

# めぐみん
# なんでこのタイミングで冷静になるんですか！
222 = "なんでこのタイミングで冷静になるんですか！"

# カズマ
# す、すまん。
207 = "す、すまん。"

# めぐみん
# と、とにかく、すぐに着ますから。\nちょっとだけ待っていてください！
217 = "と、とにかく、すぐに着ますから。\\nちょっとだけ待っていてください！"

# めぐみん
# どこにも行かないでくださいよ？
219 = "どこにも行かないでくださいよ？"

# カズマ
# お、おう。
200 = "お、おう。"

