# root_b13.txt.scn

[info]
0 = ""

[characters]
164 = "カズマ"
162 = "めぐみん"
166 = "カズマ（Ｍ）"

[character_subs]
# 164 = "カズマ"

[script]
# lines: 26

# カズマ
# …………。
143 = "…………。"

# めぐみん
# 何もありませんね。\nやっぱり見間違えだったのでは？
168 = "何もありませんね。\\nやっぱり見間違えだったのでは？"

# カズマ
# い、い、いや！\n絶対にここにいた……はずなんだけど。
147 = "い、い、いや！\\n絶対にここにいた……はずなんだけど。"

# カズマ
# 正直、自信がなくなってきてた。\nめぐみんの言うように見間違えで、\n幻だったのかも……。
172 = "正直、自信がなくなってきてた。\\nめぐみんの言うように見間違えで、\\n幻だったのかも……。"

# めぐみん
# そうですよ、そうに違いありません！\nやっと認めてくれましたか！
152 = "そうですよ、そうに違いありません！\\nやっと認めてくれましたか！"

# カズマ（Ｍ）
# display as カズマ
# （腑に落ちないものはあるが……\n　めぐみんを無駄に怖がらせる必要もないよな。\n　今はそういうことにしておくか）
188 = "（腑に落ちないものはあるが……\\n　めぐみんを無駄に怖がらせる必要もないよな。\\n　今はそういうことにしておくか）"

# カズマ
# ああ、そうだな。\nやっぱり俺、疲れてるのかもしれない。
146 = "ああ、そうだな。\\nやっぱり俺、疲れてるのかもしれない。"

# めぐみん
# そうですよ。\n今日も１日、色々ありましたからね。
153 = "そうですよ。\\n今日も１日、色々ありましたからね。"

# カズマ
# まあ、そうだな。\n爆裂魔法の訓練ができる場所まで歩いて、\n魔力切れのめぐみんをおぶって帰ってきて……。
160 = "まあ、そうだな。\\n爆裂魔法の訓練ができる場所まで歩いて、\\n魔力切れのめぐみんをおぶって帰ってきて……。"

# カズマ
# あ、そうだ。\nお前、少し太ったか？
145 = "あ、そうだ。\\nお前、少し太ったか？"

# めぐみん
# はあっ！？\nなにを突然、失礼なことを\n口走ってくれてるんですか！
155 = "はあっ！？\\nなにを突然、失礼なことを\\n口走ってくれてるんですか！"

# カズマ
# ほら、こんなに疲れてるのは\n背負っていたものが重いからなんじゃないかって。
159 = "ほら、こんなに疲れてるのは\\n背負っていたものが重いからなんじゃないかって。"

# めぐみん
# 太ってなどいませんよっ！\n紅魔族は体重が増えたりしないのです！
170 = "太ってなどいませんよっ！\\n紅魔族は体重が増えたりしないのです！"

# カズマ
# いやもうそれ人間じゃなくね？
148 = "いやもうそれ人間じゃなくね？"

# めぐみん
# カズマにはわからない、計り知れないことが\nこの世界にはたくさんあるんですよ！
165 = "カズマにはわからない、計り知れないことが\\nこの世界にはたくさんあるんですよ！"

# カズマ
# はあ……。\nどうして女子はそこまで体重にこだわるんだ。
154 = "はあ……。\\nどうして女子はそこまで体重にこだわるんだ。"

# めぐみん
# ふん、そういう女心がわからないから\nカズマはモテないんですよ。
157 = "ふん、そういう女心がわからないから\\nカズマはモテないんですよ。"

# カズマ
# ほっとけ！
158 = "ほっとけ！"

# めぐみん
# まったくカズマときたら――ふぁぁぁ～……。
161 = "まったくカズマときたら――ふぁぁぁ～……。"

# カズマ
# おお、大きなあくびだな。\nもう遅いし、そろそろ寝るか。
149 = "おお、大きなあくびだな。\\nもう遅いし、そろそろ寝るか。"

# めぐみん
# ……さっきみたいに\n勝手に部屋に入って来ないでくださいよ？
144 = "……さっきみたいに\\n勝手に部屋に入って来ないでくださいよ？"

# カズマ
# しねーって。\n気になるなら鍵でもかけとけよ。\nんじゃ、おやすみ。
151 = "しねーって。\\n気になるなら鍵でもかけとけよ。\\nんじゃ、おやすみ。"

# めぐみん
# …………。
# 143 = "…………。"

# カズマ
# ん？\nどうした、部屋に行かないのか？
163 = "ん？\\nどうした、部屋に行かないのか？"

# めぐみん
# こ、怖いので……\n部屋まで連れて行ってください……。
150 = "こ、怖いので……\\n部屋まで連れて行ってください……。"

# カズマ
# はいはい、わかったよ。
156 = "はいはい、わかったよ。"

