# root_a01.txt.scn

[info]
0 = ""

[characters]
219 = "カズマ（Ｍ）"
215 = "めぐみん"
220 = "ダクネス"
218 = "カズマ"

[character_subs]
# 218 = "カズマ"

[script]
# lines: 37

# カズマ（Ｍ）
# display as カズマ
# （あの忌まわしい指輪を\n　やっと外してから数日が経った）
255 = "（あの忌まわしい指輪を\\n　やっと外してから数日が経った）"

# カズマ（Ｍ）
# display as カズマ
# （思い起こすのも面倒というか、\n　正直、思い出したくもない日々が\n　終わったのは何よりなんだが……）
263 = "（思い起こすのも面倒というか、\\n　正直、思い出したくもない日々が\\n　終わったのは何よりなんだが……）"

# カズマ（Ｍ）
# display as カズマ
# （なんだかんだで密度の濃い日々を\n　過ごしていたせいか、それが途切れると\n　今度は逆に暇を持て余すようになっていた）
258 = "（なんだかんだで密度の濃い日々を\\n　過ごしていたせいか、それが途切れると\\n　今度は逆に暇を持て余すようになっていた）"

# めぐみん
# なにもせずにゴロゴロして、\n相変わらず自堕落ですね、カズマは。
213 = "なにもせずにゴロゴロして、\\n相変わらず自堕落ですね、カズマは。"

# ダクネス
# あれだけの戦いだったのだ。\nゆっくり休んで、次に向けて\n英気を養うのも大事だぞ。
200 = "あれだけの戦いだったのだ。\\nゆっくり休んで、次に向けて\\n英気を養うのも大事だぞ。"

# カズマ
# 次の戦いとか想像もしたくないわ。\nあんなレベルのがホイホイ起こったら\n命がいくつあっても足りないだろ。
226 = "次の戦いとか想像もしたくないわ。\\nあんなレベルのがホイホイ起こったら\\n命がいくつあっても足りないだろ。"

# ダクネス
# 確かに、何度も起こっては困るが、\n久々に心のたぎる戦いだったな。
251 = "確かに、何度も起こっては困るが、\\n久々に心のたぎる戦いだったな。"

# カズマ
# 確かにダクネスはイキイキしてたけどな？
252 = "確かにダクネスはイキイキしてたけどな？"

# ダクネス
# ああ！\n攻撃の受け甲斐がある……\nもとい、強烈な攻撃に苦戦したものだ。
199 = "ああ！\\n攻撃の受け甲斐がある……\\nもとい、強烈な攻撃に苦戦したものだ。"

# カズマ
# だったら、しばらくは\nそれで満足してればいいだろ？
209 = "だったら、しばらくは\\nそれで満足してればいいだろ？"

# ダクネス
# そうだな、\nしばらくはあの時のダメージ……ではなく\n戦いのイメージを噛み締めておこう。
207 = "そうだな、\\nしばらくはあの時のダメージ……ではなく\\n戦いのイメージを噛み締めておこう。"

# カズマ
# そういえば、アクアはどうしたんだ？\nまた、どこかでへこんでるのか？
205 = "そういえば、アクアはどうしたんだ？\\nまた、どこかでへこんでるのか？"

# めぐみん
# アクアの機嫌は、もう数日前から治ってますよ。
217 = "アクアの機嫌は、もう数日前から治ってますよ。"

# カズマ
# あれ？　そうなの？
201 = "あれ？　そうなの？"

# めぐみん
# まったく、どれだけアクアに興味が無いんです。
214 = "まったく、どれだけアクアに興味が無いんです。"

# カズマ（Ｍ）
# display as カズマ
# （スカルドラゴンとの１戦のあと、\n　アクアはえらく落ち込んでいた）
261 = "（スカルドラゴンとの１戦のあと、\\n　アクアはえらく落ち込んでいた）"

# カズマ（Ｍ）
# display as カズマ
# （それはそうだろう。\n　作戦的にはアクアが美味しいところ持って行ける\n　ものだったのに――）
256 = "（それはそうだろう。\\n　作戦的にはアクアが美味しいところ持って行ける\\n　ものだったのに――）"

# カズマ（Ｍ）
# display as カズマ
# （よりによって、\n　ウィズに全てを持って行かれちまったん\n　だから）
260 = "（よりによって、\\n　ウィズに全てを持って行かれちまったん\\n　だから）"

# カズマ（Ｍ）
# display as カズマ
# （あのあとウィズはまさに英雄扱いだった）
254 = "（あのあとウィズはまさに英雄扱いだった）"

# カズマ（Ｍ）
# display as カズマ
# （俺たちはその他大勢って感じで、\n　まあ祭り上げられるのは柄じゃないし、\n　俺としてはそれで良かったんだけど――）
262 = "（俺たちはその他大勢って感じで、\\n　まあ祭り上げられるのは柄じゃないし、\\n　俺としてはそれで良かったんだけど――）"

# カズマ（Ｍ）
# display as カズマ
# （でも、アクアは納得がいかないと憤慨して、\n　シュワシュワで荒れて、へこんで――）
257 = "（でも、アクアは納得がいかないと憤慨して、\\n　シュワシュワで荒れて、へこんで――）"

# カズマ（Ｍ）
# display as カズマ
# （まったく忙しいったらありゃしない）
259 = "（まったく忙しいったらありゃしない）"

# ダクネス
# そういえば最近、昼間はほとんど姿を見ないな。
206 = "そういえば最近、昼間はほとんど姿を見ないな。"

# めぐみん
# 毎日、どこかに出かけてるみたいですね。
227 = "毎日、どこかに出かけてるみたいですね。"

# カズマ
# 毎日ね……。\nまたろくでもないことを起こさなきゃいいけど。
228 = "毎日ね……。\\nまたろくでもないことを起こさなきゃいいけど。"

# ダクネス
# 気になるようなら、帰ってきたら\nアクアに聞いてみればいい。
229 = "気になるようなら、帰ってきたら\\nアクアに聞いてみればいい。"

# カズマ
# 聞くと巻き込まれそうだから嫌だ。
253 = "聞くと巻き込まれそうだから嫌だ。"

# ダクネス
# さて、では私は少々出掛けるぞ。\nカズマとめぐみんは何か予定があるのか？
204 = "さて、では私は少々出掛けるぞ。\\nカズマとめぐみんは何か予定があるのか？"

# めぐみん
# ええ、爆裂魔法の練習へ行くつもりですよ。\n当然カズマも。
203 = "ええ、爆裂魔法の練習へ行くつもりですよ。\\n当然カズマも。"

# カズマ
# 決定事項なのかよ。
230 = "決定事項なのかよ。"

# めぐみん
# どうせここにいても、\nゴロゴロとするだけなんでしょう？
212 = "どうせここにいても、\\nゴロゴロとするだけなんでしょう？"

# めぐみん
# そろそろ動かないと、\n見るに堪えない姿になりますよ。
208 = "そろそろ動かないと、\\n見るに堪えない姿になりますよ。"

# めぐみん
# わかりやすく言うと、出ますよ、お腹が。
216 = "わかりやすく言うと、出ますよ、お腹が。"

# カズマ
# うぐ、それは嫌だ。
202 = "うぐ、それは嫌だ。"

# めぐみん
# では、付き合ってくれますよね？
211 = "では、付き合ってくれますよね？"

# カズマ
# ああ、わかったよ。
198 = "ああ、わかったよ。"

# ダクネス
# では、また後でな。
210 = "では、また後でな。"

