# root_b15.txt.scn

[info]
0 = ""

[characters]
236 = "めぐみん"
242 = "カズマ"
244 = "カズマ（Ｍ）"

[character_subs]
# 242 = "カズマ"

[script]
# lines: 60

# めぐみん
# カズマ？\nそこにいますか？
246 = "カズマ？\\nそこにいますか？"

# カズマ
# 心配しなくてもちゃんといるよ。
258 = "心配しなくてもちゃんといるよ。"

# めぐみん
# ならいいんですが。
231 = "ならいいんですが。"

# カズマ
# なあ、まだ終わらないのか？
229 = "なあ、まだ終わらないのか？"

# めぐみん
# そんなに急かされては\n出るものも出ません。
225 = "そんなに急かされては\\n出るものも出ません。"

# めぐみん
# そもそも、女の子のトイレの時間を\n気にするなんて、デリカシーが欠けてますよ。
222 = "そもそも、女の子のトイレの時間を\\n気にするなんて、デリカシーが欠けてますよ。"

# カズマ
# こんなところでひとりで待たされてるんだぞ。\n時間以外に何を気にしろっていうんだよ。
220 = "こんなところでひとりで待たされてるんだぞ。\\n時間以外に何を気にしろっていうんだよ。"

# めぐみん
# 気にしなくても考えるべきことはあるでしょう。\nこれまでの愚行の数々を反省するとか。
260 = "気にしなくても考えるべきことはあるでしょう。\\nこれまでの愚行の数々を反省するとか。"

# カズマ
# もう戻っていいか？
238 = "もう戻っていいか？"

# めぐみん
# いいわけないじゃないですか！\n本当にカズマは空気が読めない人ですね！
211 = "いいわけないじゃないですか！\\n本当にカズマは空気が読めない人ですね！"

# カズマ（Ｍ）
# display as カズマ
# （なんつー言い様だ。\n　ここまで言われて黙ってるのも……。\n　よし、ちょっとからかってやるか）
285 = "（なんつー言い様だ。\\n　ここまで言われて黙ってるのも……。\\n　よし、ちょっとからかってやるか）"

# カズマ
# …………。
207 = "…………。"

# めぐみん
# カズマ？
245 = "カズマ？"

# カズマ
# …………。
# 207 = "…………。"

# めぐみん
# カズマ！？\nい、いないんですか！？
243 = "カズマ！？\\nい、いないんですか！？"

# カズマ
# 大丈夫だ、いるって。\nそんなに慌てるなよ。
253 = "大丈夫だ、いるって。\\nそんなに慌てるなよ。"

# めぐみん
# いるならすぐに返事をしてください！\nなんの嫌がらせですか！
214 = "いるならすぐに返事をしてください！\\nなんの嫌がらせですか！"

# カズマ
# いやぁ、そんなつもりはないぜ？\n考え事すら許されないのか？
212 = "いやぁ、そんなつもりはないぜ？\\n考え事すら許されないのか？"

# めぐみん
# 何を考えていたっていうんです？
249 = "何を考えていたっていうんです？"

# カズマ
# 誰がなんのために、\nこの教会に呪いをかけたんだろうなって。
284 = "誰がなんのために、\\nこの教会に呪いをかけたんだろうなって。"

# めぐみん
# またそれですか？\n呪いをかける人間の思考など\n考えたところでわかるはずありませんよ。
235 = "またそれですか？\\n呪いをかける人間の思考など\\n考えたところでわかるはずありませんよ。"

# めぐみん
# 考えてもわからないことを考えるなんて、\n時間の無駄です。
283 = "考えてもわからないことを考えるなんて、\\n時間の無駄です。"

# カズマ
# まあ、そうかもなぁ。
234 = "まあ、そうかもなぁ。"

# めぐみん
# お、お待たせしました……。
217 = "お、お待たせしました……。"

# カズマ
# おっ？\n出てきたな。
218 = "おっ？\\n出てきたな。"

# カズマ
# もうやり残したことはないな？\nさっさと戻って寝ようぜ。
237 = "もうやり残したことはないな？\\nさっさと戻って寝ようぜ。"

# めぐみん
# わかりました――
240 = "わかりました――"

# めぐみん
# ひっ！？
233 = "ひっ！？"

# カズマ（Ｍ）
# display as カズマ
# （風……？\n　いや、おかしいぞ？\n　どこも完全に締め切られてるはずなのに？）
287 = "（風……？\\n　いや、おかしいぞ？\\n　どこも完全に締め切られてるはずなのに？）"

# めぐみん
# カ、カズマ……！\nう、後ろ……後ろ……！
241 = "カ、カズマ……！\\nう、後ろ……後ろ……！"

# カズマ
# 後ろが一体なんだって――
257 = "後ろが一体なんだって――"

# カズマ
# うわあああああああああああああ！！
215 = "うわあああああああああああああ！！"

# めぐみん
# ちょっと！\nカズマ、置いて行かないでくださいよぉ！！
226 = "ちょっと！\\nカズマ、置いて行かないでくださいよぉ！！"

# カズマ
# あれだ！\n俺がさっき見た白い何かは！\n本当にいただろ！？
210 = "あれだ！\\n俺がさっき見た白い何かは！\\n本当にいただろ！？"

# カズマ（Ｍ）
# display as カズマ
# （やっぱり幻なんかじゃなかったんだ！\n　できれば幻であって欲しかったけどな！）
286 = "（やっぱり幻なんかじゃなかったんだ！\\n　できれば幻であって欲しかったけどな！）"

# めぐみん
# わ、私、ちらっとですけど、\n骸骨みたいなものを見ました……。
239 = "わ、私、ちらっとですけど、\\n骸骨みたいなものを見ました……。"

# めぐみん
# その骸骨が……ウェディングドレスを\n着ていたんです……。
221 = "その骸骨が……ウェディングドレスを\\n着ていたんです……。"

# カズマ
# マジか！？\nな、なんだそれ！　どういうことだよ！
247 = "マジか！？\\nな、なんだそれ！　どういうことだよ！"

# めぐみん
# 私にわかるわけないじゃないですか～っ！
280 = "私にわかるわけないじゃないですか～っ！"

# カズマ
# と、とにかくだ！\nあんなものがいるとわかった以上、\n朝まで一緒にいた方がいい！
227 = "と、とにかくだ！\\nあんなものがいるとわかった以上、\\n朝まで一緒にいた方がいい！"

# めぐみん
# ええ。\n１人で朝までなんて絶対に耐えられません。
216 = "ええ。\\n１人で朝までなんて絶対に耐えられません。"

# カズマ
# というわけで、俺が先に寝るから\nめぐみんは見張りを頼む。
228 = "というわけで、俺が先に寝るから\\nめぐみんは見張りを頼む。"

# めぐみん
# ……言っている意味がよくわからないのですが。
209 = "……言っている意味がよくわからないのですが。"

# カズマ
# このまま夜通しなんて、無理に決まってるだろ。
219 = "このまま夜通しなんて、無理に決まってるだろ。"

# カズマ
# 少しでも体力温存するために、\n交代で寝ようって言ってるんだ。
254 = "少しでも体力温存するために、\\n交代で寝ようって言ってるんだ。"

# めぐみん
# それは確かに理にかなった提案ですね。\nですが、カズマが先に寝る意味がわかりません。
224 = "それは確かに理にかなった提案ですね。\\nですが、カズマが先に寝る意味がわかりません。"

# カズマ
# いやだって俺眠いし。
213 = "いやだって俺眠いし。"

# めぐみん
# 私だって眠いですよ。
279 = "私だって眠いですよ。"

# カズマ
# 俺はお前をおぶった。
250 = "俺はお前をおぶった。"

# めぐみん
# 私は爆裂魔法を撃ちました。
282 = "私は爆裂魔法を撃ちました。"

# カズマ
# それはお前の趣味で勝手にやっただけだろ。
223 = "それはお前の趣味で勝手にやっただけだろ。"

# めぐみん
# 私はカズマよりも３つも年下なんですよ？\n年下の可愛い女の子は労るべきだと思います。
281 = "私はカズマよりも３つも年下なんですよ？\\n年下の可愛い女の子は労るべきだと思います。"

# カズマ
# 可愛い？
251 = "可愛い？"

# めぐみん
# なんです。
232 = "なんです。"

# カズマ
# 可愛い？
# 251 = "可愛い？"

# めぐみん
# ……言いたいことがあるなら聞こうじゃないか。
208 = "……言いたいことがあるなら聞こうじゃないか。"

# カズマ
# …………。
# 207 = "…………。"

# めぐみん
# …………。
# 207 = "…………。"

# カズマ
# 早い者勝ち！
259 = "早い者勝ち！"

# めぐみん
# なっ、ベッドには行かせませんよ！
230 = "なっ、ベッドには行かせませんよ！"

