# root_c19.txt.scn

[info]
0 = ""

[characters]
275 = "アクア"
273 = "めぐみん"
277 = "カズマ"
280 = "ダクネス"
278 = "カズマ（Ｍ）"
276 = "アクア＆めぐみん＆ダクネス"

[character_subs]
# 277 = "カズマ"
334 = "３人"

[script]
# lines: 54

# アクア
# …………。
236 = "…………。"

# めぐみん
# …………。
# 236 = "…………。"

# カズマ
# ダクネス～、\nまた食べさせてくれないか？\nあ～ん。
281 = "ダクネス～、\\nまた食べさせてくれないか？\\nあ～ん。"

# ダクネス
# またか？\nまったく、仕方ないヤツだな。\nほら、あーん。
270 = "またか？\\nまったく、仕方ないヤツだな。\\nほら、あーん。"

# カズマ
# うーん、おーいしーいっ！！\nダクネスが食べさせてくれると\n普通の料理もご馳走に変わるよー！
246 = "うーん、おーいしーいっ！！\\nダクネスが食べさせてくれると\\n普通の料理もご馳走に変わるよー！"

# アクア
# 悪かったわね、普通の料理で。
292 = "悪かったわね、普通の料理で。"

# ダクネス
# まぁまぁ。\nカズマも美味しいと言っているじゃないか？
269 = "まぁまぁ。\\nカズマも美味しいと言っているじゃないか？"

# カズマ
# あれ、ソースがほっぺについちゃった！\nダクネスー、拭いてくれるかー？
241 = "あれ、ソースがほっぺについちゃった！\\nダクネスー、拭いてくれるかー？"

# ダクネス
# まったく、仕方がないな。\nほら、拭いたぞ。
271 = "まったく、仕方がないな。\\nほら、拭いたぞ。"

# カズマ
# ありがと、ダクネス。\n次は食事が終わったら、着替えを手伝ってくれる？
240 = "ありがと、ダクネス。\\n次は食事が終わったら、着替えを手伝ってくれる？"

# ダクネス
# す、すまない、ちょっとやることが\nあるから手伝えないんだが……。
253 = "す、すまない、ちょっとやることが\\nあるから手伝えないんだが……。"

# カズマ
# えっ？\nそ、そうなのか？
249 = "えっ？\\nそ、そうなのか？"

# ダクネス
# すまない、悪いとは思うんだが。
254 = "すまない、悪いとは思うんだが。"

# カズマ
# はぁぁ……。\n着替え、手伝ってもらえないのか。
266 = "はぁぁ……。\\n着替え、手伝ってもらえないのか。"

# カズマ
# ……仕方ないか。\nダクネスは忙しいんだし、\n自分でズボンくらいはかなきゃな。
237 = "……仕方ないか。\\nダクネスは忙しいんだし、\\n自分でズボンくらいはかなきゃな。"

# カズマ
# でも、１人でちゃんとできるかな？\nみんなに笑われちゃったりしないかな？
261 = "でも、１人でちゃんとできるかな？\\nみんなに笑われちゃったりしないかな？"

# ダクネス
# わ、わかったわかった！\n手伝ってやるから、\nそんなに寂しそうな顔をするな！
274 = "わ、わかったわかった！\\n手伝ってやるから、\\nそんなに寂しそうな顔をするな！"

# カズマ
# いやぁ～、ダクネスは優しいなぁ！
243 = "いやぁ～、ダクネスは優しいなぁ！"

# アクア
# ああ、もうっ！\n見ているだけでイライラしてくるわ！
239 = "ああ、もうっ！\\n見ているだけでイライラしてくるわ！"

# めぐみん
# 更にウザキャラとして完成しつつありますね。
294 = "更にウザキャラとして完成しつつありますね。"

# カズマ
# あ、そうだ！　今日は２人で出かけないか？\n外で弁当を食べるのもいいな。\nなんか作ってくれよ？
238 = "あ、そうだ！　今日は２人で出かけないか？\\n外で弁当を食べるのもいいな。\\nなんか作ってくれよ？"

# カズマ
# それとぉ、たまにはいつもの鎧じゃなくて、\n女の子らしい格好も見てみたいな。
257 = "それとぉ、たまにはいつもの鎧じゃなくて、\\n女の子らしい格好も見てみたいな。"

# カズマ
# それっぽい服ぐらい持ってるよな？\n着替えてくれると嬉しいなぁ。
256 = "それっぽい服ぐらい持ってるよな？\\n着替えてくれると嬉しいなぁ。"

# アクア
# カーズーマッ！\nあんた、調子に乗るのもいい加減にしなさい！
279 = "カーズーマッ！\\nあんた、調子に乗るのもいい加減にしなさい！"

# めぐみん
# バカみたいに有頂天になって、\n見ていて痛々しいです。\nそろそろ自覚してください！
282 = "バカみたいに有頂天になって、\\n見ていて痛々しいです。\\nそろそろ自覚してください！"

# カズマ
# なんだとぉ？\n有頂天になって何が悪いっ！！
265 = "なんだとぉ？\\n有頂天になって何が悪いっ！！"

# アクア
# はあっ？
267 = "はあっ？"

# めぐみん
# 見事な逆ギレです……。
330 = "見事な逆ギレです……。"

# カズマ
# 俺にやっと訪れた初めての経験なんだぞ？\nこのくらいは当然だろ！
286 = "俺にやっと訪れた初めての経験なんだぞ？\\nこのくらいは当然だろ！"

# カズマ
# むしろ、ここで遠慮してどうする！\n次はいつ起きるかわからない奇跡なんだぞ！！
272 = "むしろ、ここで遠慮してどうする！\\n次はいつ起きるかわからない奇跡なんだぞ！！"

# アクア
# 奇跡？\nあんた、何言ってんの？
289 = "奇跡？\\nあんた、何言ってんの？"

# カズマ
# うるせーっ！！　俺はやめない！\nやめてたまるかよ！！
245 = "うるせーっ！！　俺はやめない！\\nやめてたまるかよ！！"

# カズマ
# 例え後ろ指を指されようと、ウザがられようと、\nこの一瞬の幸福のためなら俺は世界とでも戦う！
285 = "例え後ろ指を指されようと、ウザがられようと、\\nこの一瞬の幸福のためなら俺は世界とでも戦う！"

# めぐみん
# それは、格好いいことを\n言っているつもりですか？
258 = "それは、格好いいことを\\n言っているつもりですか？"

# アクア
# あんたがやっているのはね、\n人の優しさにつけ込んでいる最低の行為なのよ？
242 = "あんたがやっているのはね、\\n人の優しさにつけ込んでいる最低の行為なのよ？"

# めぐみん
# そうです。\nダクネスの気持ちも考えてあげてください。
255 = "そうです。\\nダクネスの気持ちも考えてあげてください。"

# カズマ（Ｍ）
# display as カズマ
# （はあ？\n　ダクネスは溢れる愛情で\n　すべてを受け入れてくれてるじゃないか！）
332 = "（はあ？\\n　ダクネスは溢れる愛情で\\n　すべてを受け入れてくれてるじゃないか！）"

# カズマ（Ｍ）
# display as カズマ
# （ま、まぁ、少しはやり過ぎたと\n　思わないこともないが……）
333 = "（ま、まぁ、少しはやり過ぎたと\\n　思わないこともないが……）"

# カズマ
# 確かに、調子に乗っていたのかもしれない。\nダクネスにも、迷惑をちょっとだけ\nかけたかもしれないし、悪いとも思っている。
329 = "確かに、調子に乗っていたのかもしれない。\\nダクネスにも、迷惑をちょっとだけ\\nかけたかもしれないし、悪いとも思っている。"

# カズマ
# でも、仕方ないだろ？\n俺だって愛情を求めるお年頃なんだし！
260 = "でも、仕方ないだろ？\\n俺だって愛情を求めるお年頃なんだし！"

# アクア＆めぐみん＆ダクネス
# display as ３人
# えっ？
248 = "えっ？"

# カズマ
# えっ……って、なんだよ。
247 = "えっ……って、なんだよ。"

# アクア
# 愛情って、何よそれ？
293 = "愛情って、何よそれ？"

# カズマ
# いやいや、とぼけんなよ～。\nお前らだってわかってんだろ？\nダクネスが俺に惚れていることぐらい！
244 = "いやいや、とぼけんなよ～。\\nお前らだってわかってんだろ？\\nダクネスが俺に惚れていることぐらい！"

# ダクネス
# はっ！？
268 = "はっ！？"

# めぐみん
# なるほど、そういう勘違いでしたか。
263 = "なるほど、そういう勘違いでしたか。"

# カズマ
# え？　勘違、い？
250 = "え？　勘違、い？"

# アクア
# なんか、一気に可哀想に思えてきたわ。
264 = "なんか、一気に可哀想に思えてきたわ。"

# カズマ
# お、おい、なんで憐れむような目で見てるんだよ。
251 = "お、おい、なんで憐れむような目で見てるんだよ。"

# めぐみん
# これは、最悪の方向に進んだようですね。
252 = "これは、最悪の方向に進んだようですね。"

# カズマ
# ちょっとちょっと？\n話が全然見えねーぞ？
259 = "ちょっとちょっと？\\n話が全然見えねーぞ？"

# カズマ
# なぁ、俺にもわかるように教えてくれよ！\nダクネス！？
262 = "なぁ、俺にもわかるように教えてくれよ！\\nダクネス！？"

# カズマ（Ｍ）
# display as カズマ
# （お前は、どういうつもりで\n　あんなにも俺に優しくしてくれたんだ？）
331 = "（お前は、どういうつもりで\\n　あんなにも俺に優しくしてくれたんだ？）"

# ダクネス
# …………。
# 236 = "…………。"

