# root_d17.txt.scn

[info]
0 = ""

[characters]
202 = "クリス"
199 = "カズマ"
200 = "カズマ（Ｍ）"
212 = "戦士風の男冒険者"
215 = "盗賊風の男冒険者"

[character_subs]
# 199 = "カズマ"
211 = "戦士冒険者"
214 = "盗賊冒険者"

[script]
# lines: 44

# クリス
# う、ううううう……。\n酷い、酷いよ……こんなの信じられない。
173 = "う、ううううう……。\\n酷い、酷いよ……こんなの信じられない。"

# クリス
# 明日からあたし、\nどんな顔して街を歩けばいいの？\nもうお嫁にいけない！
213 = "明日からあたし、\\nどんな顔して街を歩けばいいの？\\nもうお嫁にいけない！"

# カズマ
# 悪かったって。\nあの時はああするしか方法がなかったんだよ。\nパンツはちゃんと買って返すからさ。
210 = "悪かったって。\\nあの時はああするしか方法がなかったんだよ。\\nパンツはちゃんと買って返すからさ。"

# クリス
# そういう問題じゃないんだってば！\nキミ、自分が何をしたかわかってないよね！？
177 = "そういう問題じゃないんだってば！\\nキミ、自分が何をしたかわかってないよね！？"

# クリス
# パンツを盗んだだけじゃ飽き足らず、\nそれを囮に投げつけるなんて……！
203 = "パンツを盗んだだけじゃ飽き足らず、\\nそれを囮に投げつけるなんて……！"

# カズマ
# だからそれは謝ってるだろ。\nもう終わったことなんだしさ、気にするなよ。
183 = "だからそれは謝ってるだろ。\\nもう終わったことなんだしさ、気にするなよ。"

# クリス
# そんなの無理！！\nキミは自分のパンツを晒されても\n平気な顔してられるの！？
181 = "そんなの無理！！\\nキミは自分のパンツを晒されても\\n平気な顔してられるの！？"

# クリス
# しかも、キミのせいで\nあたしがいま、穿いてないってこと\nみんなにバレちゃっんだよ！？
176 = "しかも、キミのせいで\\nあたしがいま、穿いてないってこと\\nみんなにバレちゃっんだよ！？"

# カズマ
# ま、まぁ、そう考えると\nちょっと悪いことしたとは思ってるけどな？
196 = "ま、まぁ、そう考えると\\nちょっと悪いことしたとは思ってるけどな？"

# クリス
# ちょっと？\nあれだけのことをしておいて、ちょっと？
186 = "ちょっと？\\nあれだけのことをしておいて、ちょっと？"

# クリス
# キミってほんっとサイテー。\n自分さえよければ他の人の気持ちなんて\nどうでもいいんだ。
201 = "キミってほんっとサイテー。\\n自分さえよければ他の人の気持ちなんて\\nどうでもいいんだ。"

# クリス
# ──決めた。\nあたし、もうここから動かない。\nもうキミなんて知らない、勝手にすればいいよ。
167 = "──決めた。\\nあたし、もうここから動かない。\\nもうキミなんて知らない、勝手にすればいいよ。"

# カズマ
# ま、待てクリス。\nそれは困る！
197 = "ま、待てクリス。\\nそれは困る！"

# クリス
# そんなのあたしに関係ないもん。\n１００万エリスでもなんでも借金抱えちゃえば？
180 = "そんなのあたしに関係ないもん。\\n１００万エリスでもなんでも借金抱えちゃえば？"

# カズマ（Ｍ）
# display as カズマ
# （ぐっ！　あのクリスがここまで拗ねるとは。\n　他に方法がなかったとはいえ、\n　ちょっとやり過ぎたか）
238 = "（ぐっ！　あのクリスがここまで拗ねるとは。\\n　他に方法がなかったとはいえ、\\n　ちょっとやり過ぎたか）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、ここで他の奴らに見つかったら……\n　今はまだ気付かれていないが、\n　いつ嗅ぎつけてくるかわからない）
239 = "（しかし、ここで他の奴らに見つかったら……\\n　今はまだ気付かれていないが、\\n　いつ嗅ぎつけてくるかわからない）"

# カズマ
# な、なあ、クリス～。\n俺が悪かったって……。
188 = "な、なあ、クリス～。\\n俺が悪かったって……。"

# カズマ
# とりあえず、代わりのパンツを\n買ってきてやるからさ、\nそれ穿いて機嫌直せよ。
187 = "とりあえず、代わりのパンツを\\n買ってきてやるからさ、\\nそれ穿いて機嫌直せよ。"

# クリス
# ふんっ！
194 = "ふんっ！"

# カズマ
# いつまでもノーパンでいるのも嫌だろ？\nすーすーしてるの、気になるだろ？
171 = "いつまでもノーパンでいるのも嫌だろ？\\nすーすーしてるの、気になるだろ？"

# クリス
# ねえキミ、わざとそういう言い方してる？
190 = "ねえキミ、わざとそういう言い方してる？"

# 戦士風の男冒険者
# display as 戦士冒険者
# なぁ、向こうから声が聞こえなかったか？
189 = "なぁ、向こうから声が聞こえなかったか？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# あ？　そうか？
170 = "あ？　そうか？"

# カズマ
# ちっ、もう追いつかれたか。\nクリス、逃げるぞ。
185 = "ちっ、もう追いつかれたか。\\nクリス、逃げるぞ。"

# クリス
# 逃げるなら勝手にどうぞ。\nあたしはもうここにいるって決めたの。
236 = "逃げるなら勝手にどうぞ。\\nあたしはもうここにいるって決めたの。"

# カズマ
# あーもう、そんなふてくされるなよ！\nほんと俺が悪かったって！
169 = "あーもう、そんなふてくされるなよ！\\nほんと俺が悪かったって！"

# カズマ
# このままじゃ見つかって俺の人生終わりだ。\n頼むよクリス、俺を助けると思って！
174 = "このままじゃ見つかって俺の人生終わりだ。\\n頼むよクリス、俺を助けると思って！"

# クリス
# 知らない。
235 = "知らない。"

# カズマ
# ほんとすんませんっした！！\n許してくださいクリスさぁぁぁぁん！
195 = "ほんとすんませんっした！！\\n許してくださいクリスさぁぁぁぁん！"

# 戦士風の男冒険者
# display as 戦士冒険者
# 念のため向こうの方も見てくるか。
209 = "念のため向こうの方も見てくるか。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、もうそこまで来てるのに！）
237 = "（ああ、もうそこまで来てるのに！）"

# クリス
# さて、あたしは冒険者に捕まってくるね。
175 = "さて、あたしは冒険者に捕まってくるね。"

# カズマ
# それでいいのか？
179 = "それでいいのか？"

# クリス
# 別に構わないよ。\n何度も言ってるけど、あたしの懐は痛まないもの。
205 = "別に構わないよ。\\n何度も言ってるけど、あたしの懐は痛まないもの。"

# カズマ
# いやな、そういう意味じゃなくて、\n声の主は男２人なんだぞ。
172 = "いやな、そういう意味じゃなくて、\\n声の主は男２人なんだぞ。"

# クリス
# それがなんだって言うのさ。
178 = "それがなんだって言うのさ。"

# カズマ
# あ、こいつパンツ穿いてないんだ、ニヤニヤ。\nって目で見られるけど、いいのかなって思ってさ。
168 = "あ、こいつパンツ穿いてないんだ、ニヤニヤ。\\nって目で見られるけど、いいのかなって思ってさ。"

# クリス
# ひっ！
192 = "ひっ！"

# カズマ
# もしかしたらー、\nあのパンツ、この子が穿いていたんだ、ニヤニヤ。\nって目で見られるかもしれないなぁ？
198 = "もしかしたらー、\\nあのパンツ、この子が穿いていたんだ、ニヤニヤ。\\nって目で見られるかもしれないなぁ？"

# クリス
# ひぅ！
191 = "ひぅ！"

# カズマ
# そんな目で見られてもいいのか？　いいんだな？\nよし、だったら行ってこい！
182 = "そんな目で見られてもいいのか？　いいんだな？\\nよし、だったら行ってこい！"

# クリス
# 嫌……かも。
207 = "嫌……かも。"

# カズマ
# だったら、こっちに来い！\n教会に逃げ込むぞ！！
184 = "だったら、こっちに来い！\\n教会に逃げ込むぞ！！"

# クリス
# ふぇぇぇぇぇ……。
193 = "ふぇぇぇぇぇ……。"

