# root_b03.txt.scn

[info]
0 = ""

[characters]
386 = "カズマ"
384 = "ウィズ"
374 = "めぐみん"
391 = "カズマ（Ｍ）"
396 = "バニル"
390 = "カズマ＆めぐみん"

[character_subs]
# 386 = "カズマ"
475 = "２人"

[script]
# lines: 115

# カズマ
# よう、ウィズ！
380 = "よう、ウィズ！"

# ウィズ
# あら、カズマさん、めぐみんさん。\nいらっしゃいませ。\n本日は、何をお求めですか？
308 = "あら、カズマさん、めぐみんさん。\\nいらっしゃいませ。\\n本日は、何をお求めですか？"

# カズマ
# いや、また指輪の鑑定をお願いしたくてさ。
311 = "いや、また指輪の鑑定をお願いしたくてさ。"

# ウィズ
# ひっ！？
370 = "ひっ！？"

# カズマ
# いや、もう盗んだりしないから。
312 = "いや、もう盗んだりしないから。"

# ウィズ
# そ、そうですよね、すみません。
330 = "そ、そうですよね、すみません。"

# めぐみん
# 謝る必要はありませんよ。\nカズマは警戒されて当然のことを\nしてきたのですからね。
470 = "謝る必要はありませんよ。\\nカズマは警戒されて当然のことを\\nしてきたのですからね。"

# カズマ
# わざとじゃないって散々言ってるだろ。
382 = "わざとじゃないって散々言ってるだろ。"

# めぐみん
# 意図した行為ではなくても、\nパンツを盗み続けたという純然たる事実からは\n逃げられないのです。
414 = "意図した行為ではなくても、\\nパンツを盗み続けたという純然たる事実からは\\n逃げられないのです。"

# カズマ（Ｍ）
# display as カズマ
# （手厳しいな！）
474 = "（手厳しいな！）"

# ウィズ
# あの、それで、指輪というのは？
306 = "あの、それで、指輪というのは？"

# カズマ
# ああ、これなんだけど。
304 = "ああ、これなんだけど。"

# バニル
# どれどれ我輩が見てやろう。\n貸してみろ。
360 = "どれどれ我輩が見てやろう。\\n貸してみろ。"

# カズマ
# 渡すかー！！\nお前そうやって鑑定料金\nふっかけるつもりだろうが！
418 = "渡すかー！！\\nお前そうやって鑑定料金\\nふっかけるつもりだろうが！"

# バニル
# ふっかけるとは失礼だぞ小僧。\n我輩は当然の対価を要求したまでだ。
371 = "ふっかけるとは失礼だぞ小僧。\\n我輩は当然の対価を要求したまでだ。"

# カズマ
# だからってまた３０００万も要求されても\n払えないからな。
345 = "だからってまた３０００万も要求されても\\n払えないからな。"

# バニル
# そこまで高値にはならんぞ。
334 = "そこまで高値にはならんぞ。"

# バニル
# 見た感じ、呪いマニアにも売れない二束三文の\n代物のようだからな。
467 = "見た感じ、呪いマニアにも売れない二束三文の\\n代物のようだからな。"

# カズマ
# それは本当だろうな？
339 = "それは本当だろうな？"

# ウィズ
# ええ、この前の指輪ほどの力は感じませんから、\nそこまで複雑な呪いはかけられていないと思います。
314 = "ええ、この前の指輪ほどの力は感じませんから、\\nそこまで複雑な呪いはかけられていないと思います。"

# めぐみん
# ちょっと待ってください。\n力の強弱はともかくとして、\nこれにも呪いがかけられているんですか？
349 = "ちょっと待ってください。\\n力の強弱はともかくとして、\\nこれにも呪いがかけられているんですか？"

# バニル
# 呪いと言うよりも、怨念と言った方が\n正しいかもしれん。
405 = "呪いと言うよりも、怨念と言った方が\\n正しいかもしれん。"

# ウィズ
# 怨念ですか？
410 = "怨念ですか？"

# バニル
# 詳しいことは我輩にもわからんが、\n術式で呪いが組み込まれていないというのは\n確かだ。
469 = "詳しいことは我輩にもわからんが、\\n術式で呪いが組み込まれていないというのは\\n確かだ。"

# カズマ（Ｍ）
# display as カズマ
# （うーん、よくわからん）
471 = "（うーん、よくわからん）"

# バニル
# というわけで、買い取りはできん。
359 = "というわけで、買い取りはできん。"

# ウィズ
# でも、とても綺麗な指輪ですよ？
355 = "でも、とても綺麗な指輪ですよ？"

# バニル
# ポンコツ店主よ。\nではこの中途半端な呪いがかかった指輪が\n売れるというのか？
398 = "ポンコツ店主よ。\\nではこの中途半端な呪いがかかった指輪が\\n売れるというのか？"

# ウィズ
# ええ、とても綺麗ですから。
315 = "ええ、とても綺麗ですから。"

# バニル
# 見た目どうこうの問題ではなく、\n呪いがかかっているのだぞ。
468 = "見た目どうこうの問題ではなく、\\n呪いがかかっているのだぞ。"

# バニル
# しかも、呪いマニアが見向きもしないような\n中途半端な呪いがだ。
327 = "しかも、呪いマニアが見向きもしないような\\n中途半端な呪いがだ。"

# ウィズ
# もちろんわかっていますよ？\nですが、とても綺麗ですよね？
376 = "もちろんわかっていますよ？\\nですが、とても綺麗ですよね？"

# バニル
# …………。
303 = "…………。"

# カズマ
# 苦労するな、バニル。
466 = "苦労するな、バニル。"

# バニル
# と、とにかく買い取りはできん。\nあと、鑑定料は１０万エリスだ。
356 = "と、とにかく買い取りはできん。\\nあと、鑑定料は１０万エリスだ。"

# カズマ
# は？
368 = "は？"

# バニル
# なんだその顔は。\nまさか、無料で鑑定してもらえると\n思っていたのか？
363 = "なんだその顔は。\\nまさか、無料で鑑定してもらえると\\n思っていたのか？"

# カズマ
# い、いや、俺は\n鑑定してくれなんて頼んでないし。
309 = "い、いや、俺は\\n鑑定してくれなんて頼んでないし。"

# バニル
# 確かに小僧は我輩に何も頼んではいない。\nしかし、紅魔の娘。
465 = "確かに小僧は我輩に何も頼んではいない。\\nしかし、紅魔の娘。"

# めぐみん
# ぬっ。
367 = "ぬっ。"

# バニル
# お前は我輩に聞いたな。\nこれにも呪いがかけられているのかと。
321 = "お前は我輩に聞いたな。\\nこれにも呪いがかけられているのかと。"

# めぐみん
# た、確かに聞きましたが、\nあれが鑑定依頼として成立するなんて\nあまりにも暴力的な理論ですよ！
342 = "た、確かに聞きましたが、\\nあれが鑑定依頼として成立するなんて\\nあまりにも暴力的な理論ですよ！"

# バニル
# しかし汝が疑問に解釈を求めて来たのは事実。\nそして我輩は、その問いに答えた。
326 = "しかし汝が疑問に解釈を求めて来たのは事実。\\nそして我輩は、その問いに答えた。"

# めぐみん
# ぐ、ぐぬぬ。
322 = "ぐ、ぐぬぬ。"

# バニル
# 我輩は契約による義務を果たしたのだから、\n対価を求めるのは当然のことであろう？
416 = "我輩は契約による義務を果たしたのだから、\\n対価を求めるのは当然のことであろう？"

# めぐみん
# カズマ……。
387 = "カズマ……。"

# カズマ
# じゃあ、俺は帰るわ。\n頑張れよ、めぐみん。
329 = "じゃあ、俺は帰るわ。\\n頑張れよ、めぐみん。"

# めぐみん
# ちょっと待ってください！\nなんで他人事なんですか、力を貸してくださいよ！
350 = "ちょっと待ってください！\\nなんで他人事なんですか、力を貸してくださいよ！"

# めぐみん
# これまでカズマが困っているときに、\nさんざん助けてあげたじゃないですか！
324 = "これまでカズマが困っているときに、\\nさんざん助けてあげたじゃないですか！"

# カズマ
# え？　そうだったっけ？
318 = "え？　そうだったっけ？"

# めぐみん
# なんです、そ知らぬふりですか！
364 = "なんです、そ知らぬふりですか！"

# カズマ
# いやだって記憶にないし。
313 = "いやだって記憶にないし。"

# めぐみん
# 人のパンツを盗んだだけではなく、\n恩を仇で返すとは、変態を通り越してカズマは――
400 = "人のパンツを盗んだだけではなく、\\n恩を仇で返すとは、変態を通り越してカズマは――"

# カズマ
# 俺はなんだよ。
402 = "俺はなんだよ。"

# めぐみん
# クズですね。
392 = "クズですね。"

# カズマ
# クズ！？
393 = "クズ！？"

# めぐみん
# ええ、人間のクズです。\n真性のクズです。\nなんで生きてるんですか？　死ねばいいのに。
316 = "ええ、人間のクズです。\\n真性のクズです。\\nなんで生きてるんですか？　死ねばいいのに。"

# カズマ
# お前、クズ呼ばわりするだけじゃなくて、\n人権まで否定するつもりか！
320 = "お前、クズ呼ばわりするだけじゃなくて、\\n人権まで否定するつもりか！"

# めぐみん
# 恩を仇で返すような人間に、人権なんて\nあるわけないでしょう。
411 = "恩を仇で返すような人間に、人権なんて\\nあるわけないでしょう。"

# ウィズ
# バニルさん！\n今のやり方はちょっとどうかと思いますよ？
397 = "バニルさん！\\n今のやり方はちょっとどうかと思いますよ？"

# バニル
# だが契約が成立したのは事実であろう。\n悪魔に契約の反古はあってはならないことなのだ。
346 = "だが契約が成立したのは事実であろう。\\n悪魔に契約の反古はあってはならないことなのだ。"

# めぐみん
# だいたい、カズマがあんな指輪を拾うのが\nいけないんですよ。
344 = "だいたい、カズマがあんな指輪を拾うのが\\nいけないんですよ。"

# めぐみん
# つまり、鑑定料の９割はカズマが持つべきです。
352 = "つまり、鑑定料の９割はカズマが持つべきです。"

# カズマ
# スカルドラゴンの討伐報酬だって\nまだどうなるかわからないのに、\nそんな金をどこからどう捻出しろって言うんだ！
394 = "スカルドラゴンの討伐報酬だって\\nまだどうなるかわからないのに、\\nそんな金をどこからどう捻出しろって言うんだ！"

# めぐみん
# それは私だって同じですよ！
340 = "それは私だって同じですよ！"

# バニル
# ん？　なにやらお困りのようであるな？\nなんなら、分割でもよいぞ？\n金利は２００％にしておいてやろう。
383 = "ん？　なにやらお困りのようであるな？\\nなんなら、分割でもよいぞ？\\n金利は２００％にしておいてやろう。"

# カズマ＆めぐみん
# display as ２人
# 悪魔か！？
412 = "悪魔か！？"

# バニル
# 悪魔であるが？
413 = "悪魔であるが？"

# ウィズ
# あの、元手はかかっていませんし\n知らない仲というわけでもないんですから、\n無料にしてもいいのでは。
307 = "あの、元手はかかっていませんし\\n知らない仲というわけでもないんですから、\\n無料にしてもいいのでは。"

# めぐみん
# いいですよ、ウィズ！\nもっと言ってください！
310 = "いいですよ、ウィズ！\\nもっと言ってください！"

# バニル
# やれやれ。\n店主は相変わらずの甘さであるな。
378 = "やれやれ。\\n店主は相変わらずの甘さであるな。"

# バニル
# その優しさが、貧乏店主などという\n不名誉な二つ名の原因になっているのだぞ。
335 = "その優しさが、貧乏店主などという\\n不名誉な二つ名の原因になっているのだぞ。"

# ウィズ
# そう言われましても……こういう性格ですから。
333 = "そう言われましても……こういう性格ですから。"

# バニル
# まあ、その点は痛いほど身に染みて\n理解しているが。
373 = "まあ、その点は痛いほど身に染みて\\n理解しているが。"

# バニル
# しかし、我輩は\n店主のように甘い顔をする気はない。\n仕事には対価を支払うものだろう。
325 = "しかし、我輩は\\n店主のように甘い顔をする気はない。\\n仕事には対価を支払うものだろう。"

# めぐみん
# ですが、１０万エリスというのは。
353 = "ですが、１０万エリスというのは。"

# バニル
# ふむ、では、少し妥協してやろうではないか。\n体で支払ってもらっても構わんぞ。
372 = "ふむ、では、少し妥協してやろうではないか。\\n体で支払ってもらっても構わんぞ。"

# めぐみん
# ちょっ！？\n体って、何をさせる気ですか！？
351 = "ちょっ！？\\n体って、何をさせる気ですか！？"

# バニル
# 安心しろ、我輩はそこの\n鬼畜小僧のような無理難題を\n言い出したりはせん。
407 = "安心しろ、我輩はそこの\\n鬼畜小僧のような無理難題を\\n言い出したりはせん。"

# カズマ
# おおお、俺だって言わねーよ！\nだいたいロリ属性なんてねーし！
319 = "おおお、俺だって言わねーよ！\\nだいたいロリ属性なんてねーし！"

# めぐみん
# カズマ、今のロリ属性発言について\n詳しく説明してもらいましょうか。
388 = "カズマ、今のロリ属性発言について\\n詳しく説明してもらいましょうか。"

# カズマ
# ちょ、待て！\nなんでロッドを構える！
348 = "ちょ、待て！\\nなんでロッドを構える！"

# めぐみん
# ウィズ、同時発射です。
385 = "ウィズ、同時発射です。"

# カズマ
# なっ！？
361 = "なっ！？"

# ウィズ
# ええ！？
317 = "ええ！？"

# バニル
# やれやれ、どうしてこうも話が脱線するのか。
377 = "やれやれ、どうしてこうも話が脱線するのか。"

# ウィズ
# カズマさんたちの場合、だいたいそうですよ？
389 = "カズマさんたちの場合、だいたいそうですよ？"

# バニル
# やれやれ。\n紅魔の娘よ、話を戻すがよいか？
379 = "やれやれ。\\n紅魔の娘よ、話を戻すがよいか？"

# めぐみん
# そうでした！\nいったい私に、何をさせるつもりなんです。
331 = "そうでした！\\nいったい私に、何をさせるつもりなんです。"

# バニル
# 我輩に代わり、ちょっとした頼まれ仕事を\n引き受けてくれればよい。
415 = "我輩に代わり、ちょっとした頼まれ仕事を\\n引き受けてくれればよい。"

# めぐみん
# その内容は……。
336 = "その内容は……。"

# バニル
# とある教会にかけられた呪いを解く、それだけだ。
357 = "とある教会にかけられた呪いを解く、それだけだ。"

# バニル
# ただ、高レベルの聖職者でも\n手を焼くほどのものだがな。
343 = "ただ、高レベルの聖職者でも\\n手を焼くほどのものだがな。"

# めぐみん
# なるほど、そこで私の出番なわけですね！
362 = "なるほど、そこで私の出番なわけですね！"

# めぐみん
# 爆裂魔法をその教会に向け、チュドンと一発！
419 = "爆裂魔法をその教会に向け、チュドンと一発！"

# バニル
# ダメだ。
395 = "ダメだ。"

# めぐみん
# では、高レベルのプリーストでも苦戦するような\n難度の高い呪いを、どうやってこの私に\n解けというのです。
354 = "では、高レベルのプリーストでも苦戦するような\\n難度の高い呪いを、どうやってこの私に\\n解けというのです。"

# バニル
# それを考えるのも、お前たちの役目であろう？
341 = "それを考えるのも、お前たちの役目であろう？"

# バニル
# その方法として我輩に頼るというのであれば、\n相談に乗らなくもないがな。
337 = "その方法として我輩に頼るというのであれば、\\n相談に乗らなくもないがな。"

# めぐみん
# ぐぬぅ、これ以上借金は増やしたくありません。
323 = "ぐぬぅ、これ以上借金は増やしたくありません。"

# カズマ
# めぐみん、この話は受けておけ。
375 = "めぐみん、この話は受けておけ。"

# めぐみん
# なんです、めずらしく前向きじゃないですか。
365 = "なんです、めずらしく前向きじゃないですか。"

# カズマ
# そりゃ、勝算があるからな。
338 = "そりゃ、勝算があるからな。"

# めぐみん
# というと？
358 = "というと？"

# カズマ
# なんでそこで首を傾げる。\n俺たちにはアンデッドだけには無類の強さを誇る\nアクアがいるだろ。
366 = "なんでそこで首を傾げる。\\n俺たちにはアンデッドだけには無類の強さを誇る\\nアクアがいるだろ。"

# めぐみん
# ああ、そうでした！
305 = "ああ、そうでした！"

# カズマ（Ｍ）
# display as カズマ
# （忘れてたのかよ）
473 = "（忘れてたのかよ）"

# バニル
# よし、これで話はまとまったな。\nでは、その指輪は今しばらく持っているがいい。
381 = "よし、これで話はまとまったな。\\nでは、その指輪は今しばらく持っているがいい。"

# カズマ
# は？　なんでだよ？\n呪いの指輪なんて持ってるのも嫌だ。
369 = "は？　なんでだよ？\\n呪いの指輪なんて持ってるのも嫌だ。"

# バニル
# そう言うな。\n低級のものであるから実害はない。\nそれに、なにかの役に立つかもしれんぞ。
332 = "そう言うな。\\n低級のものであるから実害はない。\\nそれに、なにかの役に立つかもしれんぞ。"

# カズマ（Ｍ）
# display as カズマ
# （呪いが一体なんの役に立つっていうんだ？\n　まあ、害もないならいいけどさ）
472 = "（呪いが一体なんの役に立つっていうんだ？\\n　まあ、害もないならいいけどさ）"

# カズマ
# じゃ、早速だけど詳しい話を聞かせてくれよ。\nこれから教会まで下見に行ってみるからさ。
328 = "じゃ、早速だけど詳しい話を聞かせてくれよ。\\nこれから教会まで下見に行ってみるからさ。"

# めぐみん
# 今からですか？
401 = "今からですか？"

# カズマ
# 善は急げっていうだろ？\nほら、いくぞ。
406 = "善は急げっていうだろ？\\nほら、いくぞ。"

# めぐみん
# ちょ、ちょっと待ってくださいよ。\nまだちゃんと歩けないんですからぁ。
347 = "ちょ、ちょっと待ってくださいよ。\\nまだちゃんと歩けないんですからぁ。"

