# root_a13.txt.scn

[info]
0 = ""

[characters]
383 = "ダクネス"
379 = "カズマ"
376 = "アクア"
381 = "カズマ（Ｍ）"

[character_subs]
# 379 = "カズマ"

[script]
# lines: 100

# ダクネス
# 戻ったぞ。
394 = "戻ったぞ。"

# カズマ
# おっ！\n帰ってきたか、ダクネス。
328 = "おっ！\\n帰ってきたか、ダクネス。"

# ダクネス
# って、どうして暢気にお茶を飲んでるんだ……。
356 = "って、どうして暢気にお茶を飲んでるんだ……。"

# アクア
# よくわからないけど、ギブアップってカズマが。
373 = "よくわからないけど、ギブアップってカズマが。"

# ダクネス
# ぎぶあっぷ？
331 = "ぎぶあっぷ？"

# カズマ
# それよりもなんで実家に帰ってたんだ？
349 = "それよりもなんで実家に帰ってたんだ？"

# ダクネス
# ああ、これを取りにな。
304 = "ああ、これを取りにな。"

# アクア
# ずいぶんと大きな袋ね？
338 = "ずいぶんと大きな袋ね？"

# ダクネス
# エリス様のイメージに近い物をと\n私のクローゼットから選んできたんだが、\nアクアのサイズに合うかどうか。
378 = "エリス様のイメージに近い物をと\\n私のクローゼットから選んできたんだが、\\nアクアのサイズに合うかどうか。"

# カズマ
# ああ、もしかして！
306 = "ああ、もしかして！"

# アクア
# え？　え？　何どういうこと？
322 = "え？　え？　何どういうこと？"

# ダクネス
# コンテストとなれば衣装が必要だろう？
382 = "コンテストとなれば衣装が必要だろう？"

# ダクネス
# そこで、実家にあるドレスを\nいくつかみつくろってきた。
345 = "そこで、実家にあるドレスを\\nいくつかみつくろってきた。"

# カズマ（Ｍ）
# display as カズマ
# （おお！　これは……\n　まさにお嬢様が着てそうな物ばかりだ）
424 = "（おお！　これは……\\n　まさにお嬢様が着てそうな物ばかりだ）"

# アクア
# へえ、さすがにいい物ばかりね。\nずいぶん可愛らしいのもあるけど、\nダクネス、着たことあるのかしら？
367 = "へえ、さすがにいい物ばかりね。\\nずいぶん可愛らしいのもあるけど、\\nダクネス、着たことあるのかしら？"

# ダクネス
# さあ、どうだったかな。\n袖を通したとしても、一度だけだと思うが。
333 = "さあ、どうだったかな。\\n袖を通したとしても、一度だけだと思うが。"

# アクア
# なんか今、ダクネスとの間に\nすごい溝を感じたわ。
361 = "なんか今、ダクネスとの間に\\nすごい溝を感じたわ。"

# カズマ
# アクア、俺たちは謙虚さを忘れないように\n生きて行こうな。
377 = "アクア、俺たちは謙虚さを忘れないように\\n生きて行こうな。"

# ダクネス
# し、失礼な！\n私は聞かれたことに答えたまでだ。\n家柄をひけらかす意味で言った訳じゃない。
334 = "し、失礼な！\\n私は聞かれたことに答えたまでだ。\\n家柄をひけらかす意味で言った訳じゃない。"

# カズマ
# わかってるから、そう目を尖らせるなって。
374 = "わかってるから、そう目を尖らせるなって。"

# カズマ
# じゃあ、俺は席を外すよ。\n着替え終わったら呼んでくれ。
336 = "じゃあ、俺は席を外すよ。\\n着替え終わったら呼んでくれ。"

# ダクネス
# ああ、わかった。
307 = "ああ、わかった。"

# カズマ（Ｍ）
# display as カズマ
# （ふあああああ。\n　どうして女の着替えってこうも長くなるんだ）
428 = "（ふあああああ。\\n　どうして女の着替えってこうも長くなるんだ）"

# ダクネス
# カズマ。\nそこにいるのか？
380 = "カズマ。\\nそこにいるのか？"

# カズマ
# おう、終わったか？
327 = "おう、終わったか？"

# ダクネス
# ああ、もう入ってくれてかまわない。
305 = "ああ、もう入ってくれてかまわない。"

# カズマ（Ｍ）
# display as カズマ
# （どれどれ、アクアはどう化けたかな）
426 = "（どれどれ、アクアはどう化けたかな）"

# アクア
# どうかしら？
359 = "どうかしら？"

# カズマ
# 女ってこえーーーー！！
390 = "女ってこえーーーー！！"

# アクア
# ちょっとそれ、どういう意味よ。
353 = "ちょっとそれ、どういう意味よ。"

# カズマ
# 化けすぎだろ！\nえ？　何これ？　どんな魔法使ったんだ？
388 = "化けすぎだろ！\\nえ？　何これ？　どんな魔法使ったんだ？"

# ダクネス
# ただ普通にメイクをしただけだ。
350 = "ただ普通にメイクをしただけだ。"

# カズマ
# へ、へえ、そうなんだ。
366 = "へ、へえ、そうなんだ。"

# アクア
# ねえ、ダクネス。\nこのドレス、お腹が締め付けられて辛いんだけど？
362 = "ねえ、ダクネス。\\nこのドレス、お腹が締め付けられて辛いんだけど？"

# ダクネス
# ドレスとはそういうものだ。\n我慢してくれ。
384 = "ドレスとはそういうものだ。\\n我慢してくれ。"

# アクア
# こういうのって、舞踏会とかで着るのよね？\nこれじゃ食事があまり食べられないじゃない。
332 = "こういうのって、舞踏会とかで着るのよね？\\nこれじゃ食事があまり食べられないじゃない。"

# ダクネス
# いや、まあ、そんなに食べたりしないからな。
314 = "いや、まあ、そんなに食べたりしないからな。"

# アクア
# あっ、お持ち帰り！
309 = "あっ、お持ち帰り！"

# ダクネス
# そういうこともしないぞ。
339 = "そういうこともしないぞ。"

# カズマ（Ｍ）
# display as カズマ
# （うん、中身はアクアだ。\n　残念な意味でアクアだ）
423 = "（うん、中身はアクアだ。\\n　残念な意味でアクアだ）"

# アクア
# それで、カズマ？\nどう？　似合ってる？
347 = "それで、カズマ？\\nどう？　似合ってる？"

# カズマ
# あ、ああ、そうだな……。
301 = "あ、ああ、そうだな……。"

# カズマ
# 馬子にも衣装だな。
421 = "馬子にも衣装だな。"

# アクア
# しれっとひどいわね。
335 = "しれっとひどいわね。"

# カズマ
# いや、ほめてるつもりなんだが。
313 = "いや、ほめてるつもりなんだが。"

# アクア
# ほめてないわよ！\nちゃんと言葉の意味調べたら！？
368 = "ほめてないわよ！\\nちゃんと言葉の意味調べたら！？"

# カズマ
# まあ、似合ってるぞ。
370 = "まあ、似合ってるぞ。"

# アクア
# 嬉しいけど、なんか引っかかる言い方ね。
391 = "嬉しいけど、なんか引っかかる言い方ね。"

# カズマ
# 評価しようという思いと、\nそんなことはしたくないという思いで\nせめぎ合いが行われた結果だ。
419 = "評価しようという思いと、\\nそんなことはしたくないという思いで\\nせめぎ合いが行われた結果だ。"

# アクア
# あんた、ケンカ売ってる？
311 = "あんた、ケンカ売ってる？"

# カズマ
# いやいや、正直な気持ちなんだが。
316 = "いやいや、正直な気持ちなんだが。"

# カズマ
# そうやってると、\nそれなりに女神に見えるな。
341 = "そうやってると、\\nそれなりに女神に見えるな。"

# アクア
# ふふん、そうでしょ？
365 = "ふふん、そうでしょ？"

# アクア
# って、ちょっと待ちなさい！\nそれなりってどういうことよ！
355 = "って、ちょっと待ちなさい！\\nそれなりってどういうことよ！"

# カズマ
# いや、普段の姿がどうしてもな？
315 = "いや、普段の姿がどうしてもな？"

# ダクネス
# まあまあ、アクア。\nそんな声を上げてはドレスが泣くぞ？
371 = "まあまあ、アクア。\\nそんな声を上げてはドレスが泣くぞ？"

# ダクネス
# 衣装は器を飾るだけにすぎない。\n相応しい着こなしも身につけねばな。
417 = "衣装は器を飾るだけにすぎない。\\n相応しい着こなしも身につけねばな。"

# カズマ
# そうそう！\nお前はその辺がまったくなってないからな。\nダクネスに鍛え直してもらえよ。
340 = "そうそう！\\nお前はその辺がまったくなってないからな。\\nダクネスに鍛え直してもらえよ。"

# アクア
# えー？\n私の仕草は女神の名にふさわしい\n洗練されたもののはずよ？
320 = "えー？\\n私の仕草は女神の名にふさわしい\\n洗練されたもののはずよ？"

# カズマ（Ｍ）
# display as カズマ
# （どの口が言うんだ、どの口が！）
425 = "（どの口が言うんだ、どの口が！）"

# アクア
# でも、さらに磨いても損はないわよね。\nじゃあダクネス、この格好に相応しい所作、\n教えてくれるかしら。
357 = "でも、さらに磨いても損はないわよね。\\nじゃあダクネス、この格好に相応しい所作、\\n教えてくれるかしら。"

# カズマ（Ｍ）
# display as カズマ
# （やれやれ、この調子で大丈夫か？）
429 = "（やれやれ、この調子で大丈夫か？）"

# アクア
# え、ええと、こうかしら？
318 = "え、ええと、こうかしら？"

# ダクネス
# 力が入り過ぎだ。\nもっと自然体にできないか？
387 = "力が入り過ぎだ。\\nもっと自然体にできないか？"

# アクア
# そう言われても、このきっついドレスで\n力抜くなんて無理よ。
344 = "そう言われても、このきっついドレスで\\n力抜くなんて無理よ。"

# ダクネス
# そこは気合で我慢だ。\n社交界は気合と根性の世界だぞ。
346 = "そこは気合で我慢だ。\\n社交界は気合と根性の世界だぞ。"

# カズマ（Ｍ）
# display as カズマ
# （なるほどな。\n　華やかな世界と思ってたけど、裏では\n　こんな涙ぐましい努力と苦労があったのか）
427 = "（なるほどな。\\n　華やかな世界と思ってたけど、裏では\\n　こんな涙ぐましい努力と苦労があったのか）"

# ダクネス
# じゃあ、次のステップに行くぞ。
337 = "じゃあ、次のステップに行くぞ。"

# アクア
# えー？　ちょっと休憩しない？\nもう疲れちゃったわ。
321 = "えー？　ちょっと休憩しない？\\nもう疲れちゃったわ。"

# ダクネス
# 仕方ないな。\nでは、少し休んでから再開するぞ。
386 = "仕方ないな。\\nでは、少し休んでから再開するぞ。"

# アクア
# ああん、お腹が苦しい。\nもう脱ぎたいんですけどー。
308 = "ああん、お腹が苦しい。\\nもう脱ぎたいんですけどー。"

# ダクネス
# おいおい、これくらいで根を上げていては\nコンテストを乗り切れないぞ。
325 = "おいおい、これくらいで根を上げていては\\nコンテストを乗り切れないぞ。"

# アクア
# わかってるけど。\nああ、もう無理！　やっぱり脱ぐ！
375 = "わかってるけど。\\nああ、もう無理！　やっぱり脱ぐ！"

# カズマ
# ちょっ、待て！　俺がいるんだぞ！
352 = "ちょっ、待て！　俺がいるんだぞ！"

# アクア
# はっ！　さてはその目で私を汚すつもりね！
364 = "はっ！　さてはその目で私を汚すつもりね！"

# カズマ
# お前が勝手に脱ごうとしたんだろうが！
329 = "お前が勝手に脱ごうとしたんだろうが！"

# アクア
# そう言いながら私をジロジロと見ているのは\nどこの誰ですか？
343 = "そう言いながら私をジロジロと見ているのは\\nどこの誰ですか？"

# アクア
# 正直、いい気分しないんですけど。
396 = "正直、いい気分しないんですけど。"

# カズマ
# 目の前に立たれてたら、\nそりゃ嫌でも目に入るだろ！\nこの駄女神が！
397 = "目の前に立たれてたら、\\nそりゃ嫌でも目に入るだろ！\\nこの駄女神が！"

# アクア
# あんた、そろそろ本気で天罰下すわよ。
310 = "あんた、そろそろ本気で天罰下すわよ。"

# カズマ
# おう、できるもんならやってみろよ。\nだが、覚悟しておけよ、俺は真の男女平等を\n願う者だ。
326 = "おう、できるもんならやってみろよ。\\nだが、覚悟しておけよ、俺は真の男女平等を\\n願う者だ。"

# カズマ
# いくら女が相手でもやるときはやるんだからな！
312 = "いくら女が相手でもやるときはやるんだからな！"

# アクア
# 言いたいことはそれだけかしら？
418 = "言いたいことはそれだけかしら？"

# カズマ
# ちょっと待って？\nなんで右手が光ってるの？
354 = "ちょっと待って？\\nなんで右手が光ってるの？"

# アクア
# え？　天罰を下すからだけど？
323 = "え？　天罰を下すからだけど？"

# カズマ
# お、おい、それは洒落にならないって！
324 = "お、おい、それは洒落にならないって！"

# アクア
# 懺悔ならエリスの前でしなさい！\nはああああ、ゴッドブロー！！
393 = "懺悔ならエリスの前でしなさい！\\nはああああ、ゴッドブロー！！"

# カズマ
# ちょっ、待てお前！\nそれくらったらマジで死ぬって！！
351 = "ちょっ、待てお前！\\nそれくらったらマジで死ぬって！！"

# アクア
# あ。
303 = "あ。"

# カズマ
# なんか。
360 = "なんか。"

# ダクネス
# や、破けた音がしたのだが。
372 = "や、破けた音がしたのだが。"

# アクア
# え、ええと、ダクネス……さん？
319 = "え、ええと、ダクネス……さん？"

# アクア
# 本当に申し訳ございませんでした。
395 = "本当に申し訳ございませんでした。"

# カズマ（Ｍ）
# display as カズマ
# （うん、ここまで謝罪が似合う女もまた珍しい）
422 = "（うん、ここまで謝罪が似合う女もまた珍しい）"

# ダクネス
# き、気にするな。\nこれくらいだったら仕立屋が直してくれるだろう。
330 = "き、気にするな。\\nこれくらいだったら仕立屋が直してくれるだろう。"

# アクア
# あ、あの、とても聞きにくいんですが、\n修理代は……。
302 = "あ、あの、とても聞きにくいんですが、\\n修理代は……。"

# ダクネス
# それは、まあ、追々話をしようじゃないか。
348 = "それは、まあ、追々話をしようじゃないか。"

# アクア
# うぅ、カズマ～、また借金があ。
317 = "うぅ、カズマ～、また借金があ。"

# カズマ
# とりあえずアクア。\nお前はもっと清楚さを身につけような。
358 = "とりあえずアクア。\\nお前はもっと清楚さを身につけような。"

# アクア
# はい……。
363 = "はい……。"

[selections]
420 = "馬子にも衣装だな"
369 = "まあ、似合ってるぞ"
342 = "そうやってると女神に見えるな"
