# root_c10.txt.scn

[info]
0 = ""

[characters]
277 = "カズマ（Ｍ）"
273 = "カズマ"
278 = "ダクネス"
276 = "カズマ＆ダクネス"

[character_subs]
# 273 = "カズマ"
374 = "２人"

[script]
# lines: 87

# カズマ（Ｍ）
# display as カズマ
# （はぁ……。\n　色々なことが気になりすぎて、\n　メシの味がわからなくなっちまった……）
365 = "（はぁ……。\\n　色々なことが気になりすぎて、\\n　メシの味がわからなくなっちまった……）"

# カズマ（Ｍ）
# display as カズマ
# （それもこれもアクア達のせいだ！\n　きっとそうだ、そうに違いない！）
357 = "（それもこれもアクア達のせいだ！\\n　きっとそうだ、そうに違いない！）"

# カズマ（Ｍ）
# display as カズマ
# （いったい何を企んでやがるんだ？\n　全然わかんねー）
344 = "（いったい何を企んでやがるんだ？\\n　全然わかんねー）"

# カズマ（Ｍ）
# display as カズマ
# （それと……\n　万が一も、みじんも、これっぽっちも\n　ないとは思うんだが……）
356 = "（それと……\\n　万が一も、みじんも、これっぽっちも\\n　ないとは思うんだが……）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスは……俺に惚れてるのか？）
368 = "（ダクネスは……俺に惚れてるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （……いやいや、でもやっぱりない。\n　俺のささやかな願望が、\n　そうじゃないかって錯覚させてるだけだ！）
339 = "（……いやいや、でもやっぱりない。\\n　俺のささやかな願望が、\\n　そうじゃないかって錯覚させてるだけだ！）"

# カズマ（Ｍ）
# display as カズマ
# （でも、でも、もし本当だとしたら？）
360 = "（でも、でも、もし本当だとしたら？）"

# カズマ（Ｍ）
# display as カズマ
# （むむむ……）
366 = "（むむむ……）"

# カズマ（Ｍ）
# display as カズマ
# （って、だーかーらー！\n　なんで俺は信じようとしてんだ？）
359 = "（って、だーかーらー！\\n　なんで俺は信じようとしてんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （……疲れてるんだな、きっと。\n　だから、優しくされると\n　急に好きになっちまうんだ）
341 = "（……疲れてるんだな、きっと。\\n　だから、優しくされると\\n　急に好きになっちまうんだ）"

# カズマ（Ｍ）
# display as カズマ
# （うん、きっとそうだ！\n　誰にだって１度はある苦い青春の定番だ！）
346 = "（うん、きっとそうだ！\\n　誰にだって１度はある苦い青春の定番だ！）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、ダクネスがもし本当に……）
353 = "（しかし、ダクネスがもし本当に……）"

# カズマ（Ｍ）
# display as カズマ
# （いやいや！　だから止めようぜ俺！\n　自分に都合がいい妄想を信じちまったら\n　勘違いだった時に立ち直れない）
345 = "（いやいや！　だから止めようぜ俺！\\n　自分に都合がいい妄想を信じちまったら\\n　勘違いだった時に立ち直れない）"

# カズマ（Ｍ）
# display as カズマ
# （はぁ……。\n　自分で可能性を全否定したら\n　悲しくなってきた……）
364 = "（はぁ……。\\n　自分で可能性を全否定したら\\n　悲しくなってきた……）"

# カズマ
# ん？\n誰だー？　開いてるぞー。
270 = "ん？\\n誰だー？　開いてるぞー。"

# ダクネス
# 失礼するぞ、カズマ。
290 = "失礼するぞ、カズマ。"

# カズマ
# だ、ダクネス！？
258 = "だ、ダクネス！？"

# カズマ（Ｍ）
# display as カズマ
# （おいおいおいっ！\n　このタイミングで、なんで来るんだ！）
348 = "（おいおいおいっ！\\n　このタイミングで、なんで来るんだ！）"

# ダクネス
# 突然、すまない。\n邪魔だっただろうか。
336 = "突然、すまない。\\n邪魔だっただろうか。"

# カズマ
# いや、そんな事ないけど。
246 = "いや、そんな事ないけど。"

# カズマ（Ｍ）
# display as カズマ
# （ヤバイ、意識しないって決めたのに\n　ダクネスを直視できねぇ……）
369 = "（ヤバイ、意識しないって決めたのに\\n　ダクネスを直視できねぇ……）"

# カズマ（Ｍ）
# display as カズマ
# （だいたい、ダクネスのパジャマ姿が悪い！\n　刺激が強すぎるんだよ！）
358 = "（だいたい、ダクネスのパジャマ姿が悪い！\\n　刺激が強すぎるんだよ！）"

# カズマ（Ｍ）
# display as カズマ
# （しかも、なんかいい匂いがするし！）
354 = "（しかも、なんかいい匂いがするし！）"

# ダクネス
# カズマは、もう寝るところだったのか？
275 = "カズマは、もう寝るところだったのか？"

# カズマ
# そ、そうだな。\nもうやることないし。
253 = "そ、そうだな。\\nもうやることないし。"

# ダクネス
# そうか……。\nでは私は退散するとしよう。
255 = "そうか……。\\nでは私は退散するとしよう。"

# カズマ
# えっ……。
249 = "えっ……。"

# カズマ（Ｍ）
# display as カズマ
# （もう帰っちまうのか？\n　これじゃ、追い返したみたいで\n　ダクネスに申し訳ない気が……）
367 = "（もう帰っちまうのか？\\n　これじゃ、追い返したみたいで\\n　ダクネスに申し訳ない気が……）"

# カズマ
# もう少し話をしようぜ。
267 = "もう少し話をしようぜ。"

# ダクネス
# えっ……。
# 249 = "えっ……。"

# カズマ（Ｍ）
# display as カズマ
# （あああっ！\n　い、勢いで呼び止めてしまった！）
343 = "（あああっ！\\n　い、勢いで呼び止めてしまった！）"

# ダクネス
# そ、そうか。\nカズマがそう言うなら……もう少しだけ。
251 = "そ、そうか。\\nカズマがそう言うなら……もう少しだけ。"

# カズマ（Ｍ）
# display as カズマ
# （ど、ど、どうする？\n　いったい何を話せばいいんだ！？）
361 = "（ど、ど、どうする？\\n　いったい何を話せばいいんだ！？）"

# ダクネス
# …………。
238 = "…………。"

# カズマ
# …………。
# 238 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （くそっ、話題は……\n　なんかこう、気の効いた話題はないか？)
349 = "（くそっ、話題は……\\n　なんかこう、気の効いた話題はないか？)"

# カズマ（Ｍ）
# display as カズマ
# （このままダクネスとお見合いしてたら、\n　気まずさが増すだけだ！）
351 = "（このままダクネスとお見合いしてたら、\\n　気まずさが増すだけだ！）"

# カズマ＆ダクネス
# display as ２人
# あのっ……。
244 = "あのっ……。"

# ダクネス
# あ、カズマから言っていいぞ？
241 = "あ、カズマから言っていいぞ？"

# カズマ
# あ、いや！\nその、何を話そうか……忘れちまった。
240 = "あ、いや！\\nその、何を話そうか……忘れちまった。"

# ダクネス
# なんだ、それは。\nカズマは面白いな。\nふふっ！
261 = "なんだ、それは。\\nカズマは面白いな。\\nふふっ！"

# カズマ
# ダクネスも何か言いかけてたよな？
282 = "ダクネスも何か言いかけてたよな？"

# ダクネス
# 私も色々考えてはいたのだが……\n忘れてしまったようだ。
335 = "私も色々考えてはいたのだが……\\n忘れてしまったようだ。"

# カズマ（Ｍ）
# display as カズマ
# （な、なんだよ！\n　このラブコメもどきの甘酸っぱい会話は！）
362 = "（な、なんだよ！\\n　このラブコメもどきの甘酸っぱい会話は！）"

# カズマ
# え、えーっと、その、\n寝るってさっき言ったけどさ、\n実はまだそんなに眠くないし――
248 = "え、えーっと、その、\\n寝るってさっき言ったけどさ、\\n実はまだそんなに眠くないし――"

# カズマ
# ダクネスが話し相手に\nなってくれるんだったら、助かるよ。
279 = "ダクネスが話し相手に\\nなってくれるんだったら、助かるよ。"

# カズマ
# 今日は楽しかったな。\n一緒に散歩したりしてさ。
286 = "今日は楽しかったな。\\n一緒に散歩したりしてさ。"

# ダクネス
# そ、そうか！\n楽しかったのだな！
252 = "そ、そうか！\\n楽しかったのだな！"

# カズマ
# ああ、たまにはああやって\nのんびり過ごすのもいいもんだな。
243 = "ああ、たまにはああやって\\nのんびり過ごすのもいいもんだな。"

# カズマ
# アクアやめぐみんと散歩に出かけたら、\nまた違ったものになってただろうし。
272 = "アクアやめぐみんと散歩に出かけたら、\\nまた違ったものになってただろうし。"

# ダクネス
# そうなのか？
257 = "そうなのか？"

# カズマ
# アクアは何かとんでもないトラブルに\n巻き込まれてたと思うし――
271 = "アクアは何かとんでもないトラブルに\\n巻き込まれてたと思うし――"

# カズマ
# めぐみんはどこかで爆裂魔法をぶっ放したら\nそれで散歩が終わりになるし。
265 = "めぐみんはどこかで爆裂魔法をぶっ放したら\\nそれで散歩が終わりになるし。"

# ダクネス
# いや、たかが散歩で\nそんな事態になるとは思えないが。
247 = "いや、たかが散歩で\\nそんな事態になるとは思えないが。"

# カズマ
# 絶対にないとは言えないだろ？\nだから今日の散歩は、\nダクネスと一緒でよかったよ。
338 = "絶対にないとは言えないだろ？\\nだから今日の散歩は、\\nダクネスと一緒でよかったよ。"

# ダクネス
# そうか……。\nだったら、また散歩に出かけることがあったら\n私を誘ってくれるか？
254 = "そうか……。\\nだったら、また散歩に出かけることがあったら\\n私を誘ってくれるか？"

# カズマ
# ああ、いいぜ。
242 = "ああ、いいぜ。"

# ダクネス
# 絶対だからな？\n約束だぞ。
337 = "絶対だからな？\\n約束だぞ。"

# カズマ
# ダクネスの料理、美味かったぞ。
281 = "ダクネスの料理、美味かったぞ。"

# ダクネス
# 本当か？\n腕によりをかけて作ったからな。\nそう言ってもらえると張り合いが出る。
292 = "本当か？\\n腕によりをかけて作ったからな。\\nそう言ってもらえると張り合いが出る。"

# カズマ
# 俺の好物ばっかりだったし、すげー嬉しかった。
288 = "俺の好物ばっかりだったし、すげー嬉しかった。"

# ダクネス
# ふふっ！\nこれは次も張り切って作らねばな。
264 = "ふふっ！\\nこれは次も張り切って作らねばな。"

# ダクネス
# そうだ。\nカズマの好みや食べてみたい物を\nもっと教えてもらえるだろうか？
256 = "そうだ。\\nカズマの好みや食べてみたい物を\\nもっと教えてもらえるだろうか？"

# ダクネス
# 次は、それを作ろう。
293 = "次は、それを作ろう。"

# カズマ
# マジで！\nサンキュー、ダクネス！
283 = "マジで！\\nサンキュー、ダクネス！"

# カズマ（Ｍ）
# display as カズマ
# （なんだなんだ？\n　どうしてこんなに優しいんだ？）
363 = "（なんだなんだ？\\n　どうしてこんなに優しいんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （……はっ！？\n　そうか、わかったぞ！）
340 = "（……はっ！？\\n　そうか、わかったぞ！）"

# カズマ（Ｍ）
# display as カズマ
# （好きな男のために、\n　相手の好物を作るってのは定番だ。\n　まさかダクネスも……）
371 = "（好きな男のために、\\n　相手の好物を作るってのは定番だ。\\n　まさかダクネスも……）"

# ダクネス
# どうした、カズマ？
259 = "どうした、カズマ？"

# カズマ
# い、いや、なんでもない。\nあー、それじゃ、お言葉に甘えて……。
245 = "い、いや、なんでもない。\\nあー、それじゃ、お言葉に甘えて……。"

# カズマ
# やっぱ肉かな。\nカニもいいなぁ。
268 = "やっぱ肉かな。\\nカニもいいなぁ。"

# ダクネス
# なるほど。\n次はそれらを使った料理を作ろう。
260 = "なるほど。\\n次はそれらを使った料理を作ろう。"

# ダクネス
# ふ、ふふふふ……。
262 = "ふ、ふふふふ……。"

# カズマ
# ん？\nどうかしたのか、ダクネス？\n急に笑って。
269 = "ん？\\nどうかしたのか、ダクネス？\\n急に笑って。"

# ダクネス
# あ、いや……\n私なんかでも、カズマの役に\n立てているのだな、と思うと……ついな。
239 = "あ、いや……\\n私なんかでも、カズマの役に\\n立てているのだな、と思うと……ついな。"

# カズマ（Ｍ）
# display as カズマ
# （えっ……）
347 = "（えっ……）"

# ダクネス
# お前が笑顔でいてくれたら、私も嬉しいんだ。
250 = "お前が笑顔でいてくれたら、私も嬉しいんだ。"

# カズマ（Ｍ）
# display as カズマ
# （こ、こ、これは……）
350 = "（こ、こ、これは……）"

# カズマ（Ｍ）
# display as カズマ
# （間違いない！　ダクネスは俺に惚れている！\n　勘違いでも妄想でも幻覚でも錯覚でも\n　夢でもない！！)
373 = "（間違いない！　ダクネスは俺に惚れている！\\n　勘違いでも妄想でも幻覚でも錯覚でも\\n　夢でもない！！)"

# カズマ（Ｍ）
# display as カズマ
# （俺を気遣い、好みの食べ物を作ってくれる！\n　それに悦びを感じている！）
370 = "（俺を気遣い、好みの食べ物を作ってくれる！\\n　それに悦びを感じている！）"

# カズマ（Ｍ）
# display as カズマ
# （そして、じっと俺のことを見つめながら\n　頬を染めちゃったりして、\n　可愛いとこを見せたりして――）
355 = "（そして、じっと俺のことを見つめながら\\n　頬を染めちゃったりして、\\n　可愛いとこを見せたりして――）"

# カズマ（Ｍ）
# display as カズマ
# （これだけの状況証拠も揃ってるんだ！\n　疑う余地はない！）
352 = "（これだけの状況証拠も揃ってるんだ！\\n　疑う余地はない！）"

# ダクネス
# カズマ……？
274 = "カズマ……？"

# カズマ
# 何も言うな。
287 = "何も言うな。"

# ダクネス
# ふっ、照れているのか？
263 = "ふっ、照れているのか？"

# カズマ（Ｍ）
# display as カズマ
# （ああ、そうだ！\n　これが照れずにいてなんとする！）
342 = "（ああ、そうだ！\\n　これが照れずにいてなんとする！）"

# カズマ（Ｍ）
# display as カズマ
# （来たっ！\n　ついに俺のモテ期来たーーー！！）
372 = "（来たっ！\\n　ついに俺のモテ期来たーーー！！）"

[selections]
266 = "もう少し話をしようぜ"
285 = "今日は楽しかったな"
280 = "ダクネスの料理、美味かったぞ"
