# root_f07.txt.scn

[info]
0 = ""

[characters]
168 = "ウィズ"
171 = "カズマ"
173 = "カズマ（Ｍ）"

[character_subs]
# 171 = "カズマ"

[script]
# lines: 36

# ウィズ
# カズマさん。\nそろそろ、お店を閉めましょうか。
172 = "カズマさん。\\nそろそろ、お店を閉めましょうか。"

# カズマ
# ああ、もうそんな時間か。\nえっと、俺は何をすればいいかな？
152 = "ああ、もうそんな時間か。\\nえっと、俺は何をすればいいかな？"

# ウィズ
# お店の外に出してある\n看板やサンプルの棚を戻してきてもらえますか？
160 = "お店の外に出してある\\n看板やサンプルの棚を戻してきてもらえますか？"

# カズマ
# オッケー、任せろ。
170 = "オッケー、任せろ。"

# カズマ
# よいしょっと……。
167 = "よいしょっと……。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、なんて平和な職場なんだ。\n　将来、この街でこんなこぢんまりした\n　店を持つのもいいかもなぁ）
197 = "（ああ、なんて平和な職場なんだ。\\n　将来、この街でこんなこぢんまりした\\n　店を持つのもいいかもなぁ）"

# カズマ（Ｍ）
# display as カズマ
# （魔王を倒すなんて俺には無理だろうし……。\n　そんな堅実な人生計画もありっちゃありか）
209 = "（魔王を倒すなんて俺には無理だろうし……。\\n　そんな堅実な人生計画もありっちゃありか）"

# カズマ
# ウィズ。\n外にある物、みんな片づけたぞ。
169 = "ウィズ。\\n外にある物、みんな片づけたぞ。"

# ウィズ
# ありがとうございます。\n重い物なので助かります。
155 = "ありがとうございます。\\n重い物なので助かります。"

# カズマ
# いいっていいって。\nこの程度、土木作業に比べれば\n全然きつくないし。
157 = "いいっていいって。\\nこの程度、土木作業に比べれば\\n全然きつくないし。"

# カズマ
# で、他には何かあるか？
163 = "で、他には何かあるか？"

# ウィズ
# えーっと、\n本来でしたら売上の計算とか\n在庫の確認をお願いしたいのですが。
159 = "えーっと、\\n本来でしたら売上の計算とか\\n在庫の確認をお願いしたいのですが。"

# カズマ
# 今日、なんにも売れてないよな？
176 = "今日、なんにも売れてないよな？"

# ウィズ
# はい。\nなので、お掃除するくらいですね。
164 = "はい。\\nなので、お掃除するくらいですね。"

# カズマ（Ｍ）
# display as カズマ
# （うーむ、楽でいいんだが\n　店としてこういう状況はよろしくないよな）
200 = "（うーむ、楽でいいんだが\\n　店としてこういう状況はよろしくないよな）"

# ウィズ
# 掃除は私１人でもできますので、\nカズマさんはもう帰って頂いても大丈夫ですよ？
179 = "掃除は私１人でもできますので、\\nカズマさんはもう帰って頂いても大丈夫ですよ？"

# カズマ
# ああ、じゃあ、そうさせてもらうよ。
151 = "ああ、じゃあ、そうさせてもらうよ。"

# ウィズ
# それと、手伝いも今日だけで構いませんから。
161 = "それと、手伝いも今日だけで構いませんから。"

# カズマ
# ええっ！？\nもしかして俺、クビ！？
158 = "ええっ！？\\nもしかして俺、クビ！？"

# ウィズ
# ち、違います！\nお手伝いはしてもらいましたけど、\n雇ったわけじゃないですし。
162 = "ち、違います！\\nお手伝いはしてもらいましたけど、\\n雇ったわけじゃないですし。"

# カズマ
# ま、冗談だけどさ、でもいいのか？\nもっとこき使ってくれて構わないんだぞ？
166 = "ま、冗談だけどさ、でもいいのか？\\nもっとこき使ってくれて構わないんだぞ？"

# ウィズ
# 下着を盗まれたのは、\nその、確かに困りましたけど……。
174 = "下着を盗まれたのは、\\nその、確かに困りましたけど……。"

# ウィズ
# あれは、カズマさんが\nわざとやったことではありませんから。\nそこまで気に病む必要はありませんよ。
156 = "あれは、カズマさんが\\nわざとやったことではありませんから。\\nそこまで気に病む必要はありませんよ。"

# カズマ（Ｍ）
# display as カズマ
# （天使がいる……！\n　いや、これはもう女神レベルの優しさだ！）
208 = "（天使がいる……！\\n　いや、これはもう女神レベルの優しさだ！）"

# カズマ（Ｍ）
# display as カズマ
# （でも、ちょっとなぁ。\n　今日の出来事を見てると……）
203 = "（でも、ちょっとなぁ。\\n　今日の出来事を見てると……）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズは優しすぎる。\n　優しすぎて、金の亡者共の\n　格好の餌食にされてる）
206 = "（ウィズは優しすぎる。\\n　優しすぎて、金の亡者共の\\n　格好の餌食にされてる）"

# カズマ（Ｍ）
# display as カズマ
# （これはほっといたらダメだろ。\n　普段なら、バニルがブレーキ役に\n　なってるんだろうが……）
201 = "（これはほっといたらダメだろ。\\n　普段なら、バニルがブレーキ役に\\n　なってるんだろうが……）"

# カズマ（Ｍ）
# display as カズマ
# （あの悪魔がいない今、このままだと\n　生来の経営下手に加えて\n　ボッタクリ被害のいい的で、店自体が終わるぞ！）
199 = "（あの悪魔がいない今、このままだと\\n　生来の経営下手に加えて\\n　ボッタクリ被害のいい的で、店自体が終わるぞ！）"

# カズマ（Ｍ）
# display as カズマ
# （これは良くないよな。\n　バニルがいない今、俺が\n　なんとかしてやらないとダメだよな！）
202 = "（これは良くないよな。\\n　バニルがいない今、俺が\\n　なんとかしてやらないとダメだよな！）"

# ウィズ
# あの、カズマさん？\nどうしました？
154 = "あの、カズマさん？\\nどうしました？"

# カズマ
# あっ、いや、なんでも無いんだ。\nちょっと考え事してただけで。\nじゃ、今日のところはおいとまするよ。
153 = "あっ、いや、なんでも無いんだ。\\nちょっと考え事してただけで。\\nじゃ、今日のところはおいとまするよ。"

# ウィズ
# はい。\n本当に、ありがとうございました。
165 = "はい。\\n本当に、ありがとうございました。"

# カズマ（Ｍ）
# display as カズマ
# （とりあえず、ウィズは素直すぎて\n　なんでも信じちまうところが問題だな）
205 = "（とりあえず、ウィズは素直すぎて\\n　なんでも信じちまうところが問題だな）"

# カズマ（Ｍ）
# display as カズマ
# （でも、止めるためには\n　俺にマジックアイテムに関する\n　知識が必要だよなぁ）
204 = "（でも、止めるためには\\n　俺にマジックアイテムに関する\\n　知識が必要だよなぁ）"

# カズマ（Ｍ）
# display as カズマ
# （今日みたいにあからさまに\n　胡散臭いならともかく、巧妙な詐欺だったら\n　一緒になって騙されちまう可能性だってある）
207 = "（今日みたいにあからさまに\\n　胡散臭いならともかく、巧妙な詐欺だったら\\n　一緒になって騙されちまう可能性だってある）"

# カズマ（Ｍ）
# display as カズマ
# （あいつらなら、多少は知ってるかな？）
198 = "（あいつらなら、多少は知ってるかな？）"

