# root_e08.txt.scn

[info]
0 = ""

[characters]
207 = "カズマ"
206 = "アクア"
209 = "ダクネス"
201 = "めぐみん"
208 = "カズマ（Ｍ）"
205 = "ゆんゆん"

[character_subs]
# 207 = "カズマ"

[script]
# lines: 36

# カズマ
# あー、今日も天気がいいなぁ。
180 = "あー、今日も天気がいいなぁ。"

# アクア
# そうね。\nこういう日は家の中で\nゴロゴロするに限るわね。
192 = "そうね。\\nこういう日は家の中で\\nゴロゴロするに限るわね。"

# カズマ
# だな、今はそこまで金にも困ってないし、\n無駄に体力を使う必要もないよなぁ。
194 = "だな、今はそこまで金にも困ってないし、\\n無駄に体力を使う必要もないよなぁ。"

# ダクネス
# ふたりとも。\n次の冒険のために英気を養うのは重要だが、\n少々、だらけすぎではないか？
200 = "ふたりとも。\\n次の冒険のために英気を養うのは重要だが、\\n少々、だらけすぎではないか？"

# カズマ
# フッ！\n甘いぞダクネス。\nこの程度のだらけっぷりは、すぎって程じゃない。
210 = "フッ！\\n甘いぞダクネス。\\nこの程度のだらけっぷりは、すぎって程じゃない。"

# カズマ
# 本気を出した俺はちょっと違うぜ。\n一ヶ月くらいカーテンを閉め切った部屋で\n過ごすのも余裕だからな！
218 = "本気を出した俺はちょっと違うぜ。\\n一ヶ月くらいカーテンを閉め切った部屋で\\n過ごすのも余裕だからな！"

# アクア
# さすがカズマさん！\nよっ！　引きこもり界のカリスマ！
190 = "さすがカズマさん！\\nよっ！　引きこもり界のカリスマ！"

# カズマ
# う、うん……わかってると思うけど、\nちっとも嬉しくないから。
184 = "う、うん……わかってると思うけど、\\nちっとも嬉しくないから。"

# アクア
# ねえ、ダクネス。\nシュワシュワ持ってきてー。
198 = "ねえ、ダクネス。\\nシュワシュワ持ってきてー。"

# ダクネス
# はあ？\nこんな昼間からシュワシュワか？
199 = "はあ？\\nこんな昼間からシュワシュワか？"

# アクア
# いいでしょ？\nどうせ、クエストに出かけるわけでもないんだし。
181 = "いいでしょ？\\nどうせ、クエストに出かけるわけでもないんだし。"

# めぐみん
# これは、全力でだらける気ですね。
189 = "これは、全力でだらける気ですね。"

# アクア
# やるからにはとことんやる。\nそれが私の流儀なのよ。
203 = "やるからにはとことんやる。\\nそれが私の流儀なのよ。"

# カズマ（Ｍ）
# display as カズマ
# （そこでキリッとした顔をされてもなぁ）
247 = "（そこでキリッとした顔をされてもなぁ）"

# ゆんゆん
# お掃除、終わりました！
187 = "お掃除、終わりました！"

# カズマ
# ああ、お疲れ様。\n少し休んでくれよ。
178 = "ああ、お疲れ様。\\n少し休んでくれよ。"

# ゆんゆん
# いえ、大丈夫です！\nそれより、今日はどんなクエストに挑むんですか？
182 = "いえ、大丈夫です！\\nそれより、今日はどんなクエストに挑むんですか？"

# アクア
# え？　挑まないわよ？\nこれから明日の朝までここでゴロゴロするわ。
186 = "え？　挑まないわよ？\\nこれから明日の朝までここでゴロゴロするわ。"

# ゆんゆん
# ……え？\nそれって本気ですか？
176 = "……え？\\nそれって本気ですか？"

# アクア
# やるからにはとことんやる。\nそれが私の流儀なのよ。
# 203 = "やるからにはとことんやる。\\nそれが私の流儀なのよ。"

# ダクネス
# やれやれ。\nこれはもうテコでも動きそうにないな。
204 = "やれやれ。\\nこれはもうテコでも動きそうにないな。"

# ゆんゆん
# ……噂には聞いていましたが、\n本当の本当に、グータラ生活を\n送っているんですね。
177 = "……噂には聞いていましたが、\\n本当の本当に、グータラ生活を\\n送っているんですね。"

# ゆんゆん
# これがめぐみんの……\nそうですか……なるほど……。
188 = "これがめぐみんの……\\nそうですか……なるほど……。"

# めぐみん
# な、なんですか、その哀れみの眼差しは！\nその、今日のアクア達はいつもよりあれなだけで\nやる時はちゃんとやりますよ！？
197 = "な、なんですか、その哀れみの眼差しは！\\nその、今日のアクア達はいつもよりあれなだけで\\nやる時はちゃんとやりますよ！？"

# ダクネス
# とはいえ、\nここ数日のだらけっぷりは否定できないな。
196 = "とはいえ、\\nここ数日のだらけっぷりは否定できないな。"

# アクア
# 何もしなくても暮らせるなら\nそれが一番いいもの。
212 = "何もしなくても暮らせるなら\\nそれが一番いいもの。"

# ゆんゆん
# めぐみんには……こういうのがあってるのかもね。
202 = "めぐみんには……こういうのがあってるのかもね。"

# めぐみん
# ち、違います！\nアクア達がだらけているからといって\n私まで同類にしないでくださいっ！
195 = "ち、違います！\\nアクア達がだらけているからといって\\n私まで同類にしないでくださいっ！"

# めぐみん
# す、少なくとも私には、\n今日だってすることがありますからね。
191 = "す、少なくとも私には、\\n今日だってすることがありますからね。"

# ゆんゆん
# え？　何をするの？
185 = "え？　何をするの？"

# めぐみん
# だ、だからあれですよ……\nそう、魔法の特訓です！
193 = "だ、だからあれですよ……\\nそう、魔法の特訓です！"

# ゆんゆん
# 魔法の特訓！？\nねえ、だったらついていってもいい？
246 = "魔法の特訓！？\\nねえ、だったらついていってもいい？"

# めぐみん
# 好きにすればいいです。\nというわけで、カズマ行きますよ。
215 = "好きにすればいいです。\\nというわけで、カズマ行きますよ。"

# カズマ
# あー、はいはい。
179 = "あー、はいはい。"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんの前で見栄張っちゃって……\n　こういうとこはまだまだお子様だよな）
248 = "（ゆんゆんの前で見栄張っちゃって……\\n　こういうとこはまだまだお子様だよな）"

# アクア
# いってらっしゃーい。\n気をつけてねー。
183 = "いってらっしゃーい。\\n気をつけてねー。"

