# root_f10.txt.scn

[info]
0 = ""

[characters]
310 = "カズマ（Ｍ）"
304 = "ウィズ"
307 = "カズマ"

[character_subs]
# 307 = "カズマ"

[script]
# lines: 104

# カズマ（Ｍ）
# display as カズマ
# （ということで、\n　仕事に戻ったはいいものの……）
343 = "（ということで、\\n　仕事に戻ったはいいものの……）"

# カズマ（Ｍ）
# display as カズマ
# （もう昼下がりもいいところなのに\n　相変わらず客が来ない。\n　何もしないのが、逆に苦痛になってくるな）
346 = "（もう昼下がりもいいところなのに\\n　相変わらず客が来ない。\\n　何もしないのが、逆に苦痛になってくるな）"

# ウィズ
# カズマさん、よろしければ\nお茶を淹れましょうか？
308 = "カズマさん、よろしければ\\nお茶を淹れましょうか？"

# カズマ
# え、いや、おかまいなく！
247 = "え、いや、おかまいなく！"

# ウィズ
# いえいえ、いいんですよ。\n少し待ってて下さい、準備してきますから。
242 = "いえいえ、いいんですよ。\\n少し待ってて下さい、準備してきますから。"

# ウィズ
# お待たせしました。\nすみません、いいお茶が手に入ったので、\n丁寧に淹れていたら時間がかかってしまいました。
256 = "お待たせしました。\\nすみません、いいお茶が手に入ったので、\\n丁寧に淹れていたら時間がかかってしまいました。"

# カズマ
# 気にすんなよ。\nしかし、いい香りだなぁ。
325 = "気にすんなよ。\\nしかし、いい香りだなぁ。"

# ウィズ
# ふふ、そうでしょう？\nそれじゃ、頂きましょうか。
293 = "ふふ、そうでしょう？\\nそれじゃ、頂きましょうか。"

# ウィズ
# ふう……。
291 = "ふう……。"

# カズマ
# やっぱり、ウィズの\n淹れてくれた紅茶は美味いなぁ。
300 = "やっぱり、ウィズの\\n淹れてくれた紅茶は美味いなぁ。"

# ウィズ
# ありがとうございます。\n別に、大したことはしていないのですが。
239 = "ありがとうございます。\\n別に、大したことはしていないのですが。"

# カズマ
# いや、こういうのは性格が出ると思うぞ。\n俺なんかとてもじゃないが無理だ。
243 = "いや、こういうのは性格が出ると思うぞ。\\n俺なんかとてもじゃないが無理だ。"

# ウィズ
# 何回も練習すれば、きっと大丈夫ですよ。
314 = "何回も練習すれば、きっと大丈夫ですよ。"

# カズマ（Ｍ）
# display as カズマ
# （それにしても……\n　こんな優雅なティータイム、\n　俺の人生には無縁だった時間だ）
342 = "（それにしても……\\n　こんな優雅なティータイム、\\n　俺の人生には無縁だった時間だ）"

# カズマ（Ｍ）
# display as カズマ
# （こうしてまったり紅茶を飲んでいると、\n　心の余裕と共に\n　働こうという意識が消失して――）
339 = "（こうしてまったり紅茶を飲んでいると、\\n　心の余裕と共に\\n　働こうという意識が消失して――）"

# カズマ（Ｍ）
# display as カズマ
# （いや、消失したらダメだろ！）
337 = "（いや、消失したらダメだろ！）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、それだけウィズの\n　淹れてくれた紅茶が美味しいということだ）
344 = "（まあ、それだけウィズの\\n　淹れてくれた紅茶が美味しいということだ）"

# ウィズ
# …………。
232 = "…………。"

# カズマ
# ん？　どうした、ウィズ？
303 = "ん？　どうした、ウィズ？"

# ウィズ
# いえ、その。\nお手伝いをしていただくのは嬉しいのですが……。
241 = "いえ、その。\\nお手伝いをしていただくのは嬉しいのですが……。"

# ウィズ
# カズマさんの貴重な時間を\n使わせてしまっていると思うと、\n申し訳ないな、と。
309 = "カズマさんの貴重な時間を\\n使わせてしまっていると思うと、\\n申し訳ないな、と。"

# カズマ
# だから、そんなこと気にする必要はないよ。\n俺が勝手にやってることなんだから、\nウィズが気に病むことないって。
277 = "だから、そんなこと気にする必要はないよ。\\n俺が勝手にやってることなんだから、\\nウィズが気に病むことないって。"

# ウィズ
# そうでしょうか？
266 = "そうでしょうか？"

# カズマ
# ウィズだって、もし逆の立場だったら\n同じように考えるだろ？
305 = "ウィズだって、もし逆の立場だったら\\n同じように考えるだろ？"

# ウィズ
# それは……そうかもしれませんね。
272 = "それは……そうかもしれませんね。"

# カズマ
# というわけで気にする必要なし！\nあとお茶お代わり！
281 = "というわけで気にする必要なし！\\nあとお茶お代わり！"

# ウィズ
# はい、わかりました。
287 = "はい、わかりました。"

# カズマ
# しかし、穏やかな午後だな。
260 = "しかし、穏やかな午後だな。"

# カズマ
# このお茶を飲めるだけで嬉しいよ。
258 = "このお茶を飲めるだけで嬉しいよ。"

# ウィズ
# そうですか？
267 = "そうですか？"

# カズマ
# ああ、こいつは\n貴重な時間を使うに値すると思うぜ？
236 = "ああ、こいつは\\n貴重な時間を使うに値すると思うぜ？"

# ウィズ
# そ、そんな……。\nこのくらいでしたら、いつでも淹れますよ？
264 = "そ、そんな……。\\nこのくらいでしたら、いつでも淹れますよ？"

# カズマ
# はははっ！\nそんなことしてもらえたら、\nそれこそ毎日通っちまうぜ！
290 = "はははっ！\\nそんなことしてもらえたら、\\nそれこそ毎日通っちまうぜ！"

# ウィズ
# ふふ、カズマさんったら……。
295 = "ふふ、カズマさんったら……。"

# カズマ
# しかし、穏やかな午後だな。
# 260 = "しかし、穏やかな午後だな。"

# カズマ
# 十分楽しんでるよ、目で。
317 = "十分楽しんでるよ、目で。"

# ウィズ
# え？\n目って、どういうことですか？
251 = "え？\\n目って、どういうことですか？"

# カズマ
# ああ、目の保養というか、\nま、まあ、深いことは気にしないでくれ。
237 = "ああ、目の保養というか、\\nま、まあ、深いことは気にしないでくれ。"

# ウィズ
# は、はあ……。
284 = "は、はあ……。"

# カズマ
# しかし、穏やかな午後だな。
# 260 = "しかし、穏やかな午後だな。"

# ウィズ
# ええ、穏やかな午後ですね。
249 = "ええ、穏やかな午後ですね。"

# カズマ
# なんだかまったりしちゃうな。
283 = "なんだかまったりしちゃうな。"

# ウィズ
# ええ、まったりしてしまいます。
248 = "ええ、まったりしてしまいます。"

# カズマ
# …………。
# 232 = "…………。"

# ウィズ
# …………。
# 232 = "…………。"

# カズマ
# って、ちがーう！！
278 = "って、ちがーう！！"

# ウィズ
# え？　え？　何がですか？
252 = "え？　え？　何がですか？"

# カズマ
# 今この店は営業中！\nそうだよな！？
313 = "今この店は営業中！\\nそうだよな！？"

# ウィズ
# あ、はい、そうですね。
233 = "あ、はい、そうですね。"

# カズマ
# お客さまは！　ねえ、お客さまは！\n昨日からひとりも見てないんだけど！
254 = "お客さまは！　ねえ、お客さまは！\\n昨日からひとりも見てないんだけど！"

# ウィズ
# それは、はい、ひとりも来ていませんから。
273 = "それは、はい、ひとりも来ていませんから。"

# カズマ（Ｍ）
# display as カズマ
# （うわ、なんなのこの余裕！）
338 = "（うわ、なんなのこの余裕！）"

# カズマ
# ええと、まさかとは思うけどさ、\n毎日こんな感じってことはないよな。
250 = "ええと、まさかとは思うけどさ、\\n毎日こんな感じってことはないよな。"

# ウィズ
# もちろんです。\nティータイムなんてしていたらバニルさんに\n怒られてしまいます。
299 = "もちろんです。\\nティータイムなんてしていたらバニルさんに\\n怒られてしまいます。"

# カズマ
# そういう意味で聞いたんじゃなくて！\n普段はもう少し忙しいんですよねって聞いたの！
265 = "そういう意味で聞いたんじゃなくて！\\n普段はもう少し忙しいんですよねって聞いたの！"

# ウィズ
# いいえ、毎日がだいたいこんな感じですよ。
240 = "いいえ、毎日がだいたいこんな感じですよ。"

# カズマ（Ｍ）
# display as カズマ
# （言い切ったよ、この人！）
347 = "（言い切ったよ、この人！）"

# カズマ
# あの、ウィズさ。\nもう単刀直入に聞いちゃうけど――
238 = "あの、ウィズさ。\\nもう単刀直入に聞いちゃうけど――"

# ウィズ
# はい、なんでしょう。
286 = "はい、なんでしょう。"

# カズマ
# ウィズは今の店の状況に\n何か思うところはないのか？
306 = "ウィズは今の店の状況に\\n何か思うところはないのか？"

# ウィズ
# 困ったな、とは思っていますね。
320 = "困ったな、とは思っていますね。"

# カズマ
# 子供の感想か！
322 = "子供の感想か！"

# ウィズ
# す、すみません……。
262 = "す、すみません……。"

# カズマ
# ああ、いや、俺こそいつものノリで怒鳴ったりして\n悪かった。
235 = "ああ、いや、俺こそいつものノリで怒鳴ったりして\\n悪かった。"

# ウィズ
# ふふ、アクア様達といるときのカズマさんって\nそんな感じなんですね。
294 = "ふふ、アクア様達といるときのカズマさんって\\nそんな感じなんですね。"

# カズマ
# そんな感じっていうか、\nそうならざるを得ないっていうか、\nあいつらはツッコミどころが多すぎて……。
274 = "そんな感じっていうか、\\nそうならざるを得ないっていうか、\\nあいつらはツッコミどころが多すぎて……。"

# カズマ
# って、俺の愚痴はいいから。
279 = "って、俺の愚痴はいいから。"

# ウィズ
# そう言わずに、どうぞ。\nたまにはガス抜きも必要ですよ。
269 = "そう言わずに、どうぞ。\\nたまにはガス抜きも必要ですよ。"

# カズマ（Ｍ）
# display as カズマ
# （もうなんなのこの天使。\n　眩しすぎて直視できない）
345 = "（もうなんなのこの天使。\\n　眩しすぎて直視できない）"

# ウィズ
# ささ、遠慮なさらずに。
259 = "ささ、遠慮なさらずに。"

# カズマ
# いやいや、俺のことはどうでも良くて、\nウィズの店について考えを聞かせてくれ。
244 = "いやいや、俺のことはどうでも良くて、\\nウィズの店について考えを聞かせてくれ。"

# ウィズ
# お店のことは、そうですね。\nもちろん、繁盛してくれた方がいいとは\n思っていますよ？
255 = "お店のことは、そうですね。\\nもちろん、繁盛してくれた方がいいとは\\n思っていますよ？"

# カズマ
# じゃあ、何かこう、\n繁盛する方法みたいなのは考えたことないのか？
261 = "じゃあ、何かこう、\\n繁盛する方法みたいなのは考えたことないのか？"

# ウィズ
# 無いとは言いませんけど、\nただただ利益を追求するというのは、\nちょっと、がめついかなーと思いまして。
326 = "無いとは言いませんけど、\\nただただ利益を追求するというのは、\\nちょっと、がめついかなーと思いまして。"

# カズマ
# いやいや、確かに繁盛するのと\n利益を追求するのは同じかもしれないけど、\nがめついかどうかは別問題だろ。
245 = "いやいや、確かに繁盛するのと\\n利益を追求するのは同じかもしれないけど、\\nがめついかどうかは別問題だろ。"

# カズマ
# せめて赤字にならないくらいの利益は出そうぜ。
263 = "せめて赤字にならないくらいの利益は出そうぜ。"

# ウィズ
# はい、わかりました。\n努力してみます。
288 = "はい、わかりました。\\n努力してみます。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、ウィズの努力は裏目に出そうで怖い）
336 = "（ああ、ウィズの努力は裏目に出そうで怖い）"

# ウィズ
# ですが、いざ考えるとなると、\nすぐにつまずいてしまうんですよね。
280 = "ですが、いざ考えるとなると、\\nすぐにつまずいてしまうんですよね。"

# ウィズ
# 思い浮かぶことといったら、\n値段を下げるくらいなんです。
324 = "思い浮かぶことといったら、\\n値段を下げるくらいなんです。"

# カズマ
# それで、原価レベルの\n値段設定になるってわけか。
270 = "それで、原価レベルの\\n値段設定になるってわけか。"

# ウィズ
# それでも売れないんですけど。
271 = "それでも売れないんですけど。"

# カズマ
# いやいや、笑顔で言うところじゃないぞ。
246 = "いやいや、笑顔で言うところじゃないぞ。"

# ウィズ
# そうですね。
268 = "そうですね。"

# カズマ
# よし、それじゃあ、\n繁盛するための方法をさ、ふたりで考えてみるか。
301 = "よし、それじゃあ、\\n繁盛するための方法をさ、ふたりで考えてみるか。"

# ウィズ
# ふたりでですか？
292 = "ふたりでですか？"

# カズマ
# あ、やましいことは何も考えてないからな？
234 = "あ、やましいことは何も考えてないからな？"

# ウィズ
# そんな風には思っていませんよ。\nとても素敵なご提案をいただけて嬉しいです。
275 = "そんな風には思っていませんよ。\\nとても素敵なご提案をいただけて嬉しいです。"

# カズマ
# よしじゃあ、俺からの提案だ。
302 = "よしじゃあ、俺からの提案だ。"

# ウィズ
# はい。
289 = "はい。"

# カズマ
# 例えば、ここにある品を\n売り込みに行くのはどうだろう。
315 = "例えば、ここにある品を\\n売り込みに行くのはどうだろう。"

# ウィズ
# む、無理です！\nそういうのは一番苦手でして。
297 = "む、無理です！\\nそういうのは一番苦手でして。"

# カズマ（Ｍ）
# display as カズマ
# （そうか。\n　確かにウィズが営業に向いてるとは思えないな）
340 = "（そうか。\\n　確かにウィズが営業に向いてるとは思えないな）"

# カズマ（Ｍ）
# display as カズマ
# （そもそも、そんなことができれば\n　露店でのぼったくりにも遭わないだろうし）
341 = "（そもそも、そんなことができれば\\n　露店でのぼったくりにも遭わないだろうし）"

# ウィズ
# 人に勧めるのは好きですけど、\nそれを押し通して買ってもらうのは、ちょっと。
312 = "人に勧めるのは好きですけど、\\nそれを押し通して買ってもらうのは、ちょっと。"

# カズマ
# むしろ、売りに行った先で暇人に捕まって、\n延々と世間話に付き合って終わりそうだ。
298 = "むしろ、売りに行った先で暇人に捕まって、\\n延々と世間話に付き合って終わりそうだ。"

# ウィズ
# 否定できませんね。
319 = "否定できませんね。"

# カズマ（Ｍ）
# display as カズマ
# （……ん？　そっか！\n　ウィズはそういう、人の話を\n　上手に聞くって才能があるよな？）
335 = "（……ん？　そっか！\\n　ウィズはそういう、人の話を\\n　上手に聞くって才能があるよな？）"

# カズマ
# なあウィズ、ちょっと外に出ようぜ。
282 = "なあウィズ、ちょっと外に出ようぜ。"

# ウィズ
# え？　でも、お店が。
253 = "え？　でも、お店が。"

# カズマ
# 大丈夫大丈夫、客なんて来ないって。
321 = "大丈夫大丈夫、客なんて来ないって。"

# ウィズ
# 自分で言うのはいいのですが、\n人に言われるのはちょっと。
334 = "自分で言うのはいいのですが、\\n人に言われるのはちょっと。"

# カズマ
# ほらいいから！\n店の鍵を閉め忘れるなよ！
296 = "ほらいいから！\\n店の鍵を閉め忘れるなよ！"

# ウィズ
# は、はい、わかりました！
285 = "は、はい、わかりました！"

[selections]
276 = "だから、そんなこと気にする必要はないよ"
257 = "このお茶を飲めるだけで嬉しいよ"
316 = "十分に楽しんでるよ、目で"
