# root_d12.txt.scn

[info]
0 = ""

[characters]
205 = "カズマ（Ｍ）"
206 = "クリス"
202 = "めぐみん"
204 = "カズマ"

[character_subs]
# 204 = "カズマ"

[script]
# lines: 30

# カズマ（Ｍ）
# display as カズマ
# （とりあえず、ここなら鍵もかかるし\n　しばらくは大丈夫だろ）
237 = "（とりあえず、ここなら鍵もかかるし\\n　しばらくは大丈夫だろ）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、これからどうしたもんかな）
236 = "（しかし、これからどうしたもんかな）"

# カズマ（Ｍ）
# display as カズマ
# （結構集まってきているみたいだったから\n　バレないように屋敷から抜け出すのはなぁ）
239 = "（結構集まってきているみたいだったから\\n　バレないように屋敷から抜け出すのはなぁ）"

# クリス
# あれ？\n外から声が聞こえなくなったね。
185 = "あれ？\\n外から声が聞こえなくなったね。"

# カズマ（Ｍ）
# display as カズマ
# （ん？　そう言えば……）
238 = "（ん？　そう言えば……）"

# めぐみん
# 入りますよ、カズマ。\nまったく、頭の中まで脳筋だと\n説得するのも一苦労ですね。
209 = "入りますよ、カズマ。\\nまったく、頭の中まで脳筋だと\\n説得するのも一苦労ですね。"

# カズマ
# お前が言うか。
188 = "お前が言うか。"

# めぐみん
# 何か言いましたか、カズマ。
208 = "何か言いましたか、カズマ。"

# カズマ
# あ、いや、なんでもないです。\nそれより、もしかして\n外の奴らの対応してくれたのか？
184 = "あ、いや、なんでもないです。\\nそれより、もしかして\\n外の奴らの対応してくれたのか？"

# めぐみん
# ええ、なんとか言いくるめて追い返しました。\nですが、私の言葉をかなり疑っていたので\nおそらく外で見張っているでしょうね。
186 = "ええ、なんとか言いくるめて追い返しました。\\nですが、私の言葉をかなり疑っていたので\\nおそらく外で見張っているでしょうね。"

# カズマ（Ｍ）
# display as カズマ
# （おのれ、金に目がくらんだ醜い奴らめ！）
235 = "（おのれ、金に目がくらんだ醜い奴らめ！）"

# めぐみん
# というわけで！\n爆裂魔法で一掃するのはどうでしょう！？
198 = "というわけで！\\n爆裂魔法で一掃するのはどうでしょう！？"

# めぐみん
# 幸い、今日はまだ撃っていないので\n魔力には十分余裕がありますよ！
214 = "幸い、今日はまだ撃っていないので\\n魔力には十分余裕がありますよ！"

# カズマ
# やめろ、屋敷まで吹っ飛ばすつもりかお前は。\nここで使ったらどうなるかぐらいわかるだろーが。
203 = "やめろ、屋敷まで吹っ飛ばすつもりかお前は。\\nここで使ったらどうなるかぐらいわかるだろーが。"

# めぐみん
# 我ながらいい案だと思ったのですが。
215 = "我ながらいい案だと思ったのですが。"

# カズマ
# くそっ、手詰まりか。\nもうこの屋敷には逃げ場もないし、\n出入り口は見張られてるし、どうしたもんか。
190 = "くそっ、手詰まりか。\\nもうこの屋敷には逃げ場もないし、\\n出入り口は見張られてるし、どうしたもんか。"

# クリス
# まぁ、焦っても仕方ないよ。\nなるようにしかならないって。
200 = "まぁ、焦っても仕方ないよ。\\nなるようにしかならないって。"

# カズマ
# なんでそんなに余裕なんだよ。
199 = "なんでそんなに余裕なんだよ。"

# クリス
# そりゃ、あたしは捕まっても\n自分の懐は少しも痛くならないからね。\n痛むのはカズマのお財布だけだし。
194 = "そりゃ、あたしは捕まっても\\n自分の懐は少しも痛くならないからね。\\n痛むのはカズマのお財布だけだし。"

# カズマ
# それはわかってるけど！
195 = "それはわかってるけど！"

# クリス
# でも、あたしは盗賊だよ。\n盗賊として捕まるというのは、屈辱に値する。
197 = "でも、あたしは盗賊だよ。\\n盗賊として捕まるというのは、屈辱に値する。"

# クリス
# だから、逃げることに\n手を抜いたりはしないから、安心して。
196 = "だから、逃げることに\\n手を抜いたりはしないから、安心して。"

# カズマ
# そ、そうか？
193 = "そ、そうか？"

# クリス
# さて、それじゃ特に今できることもないし\n体力維持でもしようかな。\n少し仮眠するから、何かあったら起こしてね。
192 = "さて、それじゃ特に今できることもないし\\n体力維持でもしようかな。\\n少し仮眠するから、何かあったら起こしてね。"

# カズマ
# えっ？
187 = "えっ？"

# クリス
# くぅ……すぅ……すぅ……すぅ……。
189 = "くぅ……すぅ……すぅ……すぅ……。"

# めぐみん
# この状況で寝ますか。\n頼もしいというか、図太いというか。
191 = "この状況で寝ますか。\\n頼もしいというか、図太いというか。"

# カズマ
# まあ、確かにここで\nオロオロしたってなんにもならないよな。\n今のうちに、俺も腹ごしらえしてくるか。
201 = "まあ、確かにここで\\nオロオロしたってなんにもならないよな。\\n今のうちに、俺も腹ごしらえしてくるか。"

# めぐみん
# 私は、この前カズマが作った\nクリームパスタでいいですよ。\nベーコンとほうれん草も入れてください。
233 = "私は、この前カズマが作った\\nクリームパスタでいいですよ。\\nベーコンとほうれん草も入れてください。"

# カズマ（Ｍ）
# display as カズマ
# （……お前も食うのかよ）
234 = "（……お前も食うのかよ）"

