# root_c12.txt.scn

[info]
0 = ""

[characters]
221 = "ダクネス"
217 = "アクア"
214 = "めぐみん"
219 = "カズマ"

[character_subs]

[script]
# lines: 41

# ダクネス
# では、いただくとするか。
198 = "では、いただくとするか。"

# アクア
# いただきまーす！
188 = "いただきまーす！"

# めぐみん
# いただきます。
187 = "いただきます。"

# カズマ
# なぁ、今日の朝食は誰が作ったんだ？
200 = "なぁ、今日の朝食は誰が作ったんだ？"

# ダクネス
# 私だが、それがどうかしたのか？
258 = "私だが、それがどうかしたのか？"

# カズマ
# さすがだな、ダクネス。\n俺の好物がさりげなく並んでるじゃないか。
191 = "さすがだな、ダクネス。\\n俺の好物がさりげなく並んでるじゃないか。"

# ダクネス
# 褒めてくれるのは嬉しいが\n特別なことはしていないぞ。
259 = "褒めてくれるのは嬉しいが\\n特別なことはしていないぞ。"

# カズマ
# またまたー！\n俺にはわかるぜ？\nダクネスのさりげない優しさが。
212 = "またまたー！\\n俺にはわかるぜ？\\nダクネスのさりげない優しさが。"

# めぐみん
# なんか今日のカズマ、\n斜め上に舞い上がっていませんか？
201 = "なんか今日のカズマ、\\n斜め上に舞い上がっていませんか？"

# アクア
# なんなのかしら。\n完全に調子に乗ってる感じだけれど。
204 = "なんなのかしら。\\n完全に調子に乗ってる感じだけれど。"

# カズマ
# あー、うまい！\nやっぱりダクネスの作った飯が一番だっ！
184 = "あー、うまい！\\nやっぱりダクネスの作った飯が一番だっ！"

# めぐみん
# 朝食なんて誰が作っても変わりませんよ。\nお腹に入ってしまえば、みんな等しく栄養です。
230 = "朝食なんて誰が作っても変わりませんよ。\\nお腹に入ってしまえば、みんな等しく栄養です。"

# カズマ
# はあ？\nお前には情緒ってものがないのかよ？
207 = "はあ？\\nお前には情緒ってものがないのかよ？"

# めぐみん
# いつもとさして変わらない朝に\nどのような情緒を感じろというのです。
189 = "いつもとさして変わらない朝に\\nどのような情緒を感じろというのです。"

# カズマ
# まったく、これだからお子様は。
213 = "まったく、これだからお子様は。"

# めぐみん
# なんですって！
203 = "なんですって！"

# カズマ
# なんだよ！
202 = "なんだよ！"

# ダクネス
# まあまあ。\nこんなに気持ちがいい朝なのに、\n険悪になってどうする。
211 = "まあまあ。\\nこんなに気持ちがいい朝なのに、\\n険悪になってどうする。"

# カズマ
# あ、そうだな。\nじゃあ、このご馳走をいただくとするか！
183 = "あ、そうだな。\\nじゃあ、このご馳走をいただくとするか！"

# アクア
# 何、あれ。\nちょっと鳥肌が立っちゃったんですけど。
225 = "何、あれ。\\nちょっと鳥肌が立っちゃったんですけど。"

# カズマ
# さて、何から食べようかな～。\nどれも美味そうで、目移りするな～。
192 = "さて、何から食べようかな～。\\nどれも美味そうで、目移りするな～。"

# カズマ
# よし、せっかくだし、\nダクネスのお勧めからいただこうかな。
215 = "よし、せっかくだし、\\nダクネスのお勧めからいただこうかな。"

# カズマ
# なぁ、ダクネス。\nお勧めを食べさせてくれないか？
199 = "なぁ、ダクネス。\\nお勧めを食べさせてくれないか？"

# ダクネス
# えっ？　私がか？
190 = "えっ？　私がか？"

# カズマ
# ダクネスに食べさせてもらったら、\nもっと美味く感じると思うんだ。
223 = "ダクネスに食べさせてもらったら、\\nもっと美味く感じると思うんだ。"

# ダクネス
# そ、そういうもの……なのか？
193 = "そ、そういうもの……なのか？"

# アクア
# カズマ？\nあんた、ホントいい加減にしなさいよ？
220 = "カズマ？\\nあんた、ホントいい加減にしなさいよ？"

# めぐみん
# 着替えを手伝わせたあげく、\n今度はご飯食べさせるなんて、\nいったいダクネスをなんだと思っているのです。
257 = "着替えを手伝わせたあげく、\\n今度はご飯食べさせるなんて、\\nいったいダクネスをなんだと思っているのです。"

# ダクネス
# まあまあ、これくらいいいじゃないか。
210 = "まあまあ、これくらいいいじゃないか。"

# ダクネス
# それに、カズマたっての願いだ。\nこれも必要なことなんだろう。
196 = "それに、カズマたっての願いだ。\\nこれも必要なことなんだろう。"

# カズマ
# そうそう、大事なことなんだぞ？\nじゃあ、ダクネス頼むな。
195 = "そうそう、大事なことなんだぞ？\\nじゃあ、ダクネス頼むな。"

# ダクネス
# ほら、あーん。
209 = "ほら、あーん。"

# カズマ
# あーん。あむっ！　んむんむんむんむ……\nあー！　やっぱりダクネスに食わせて貰う飯は\n最高に美味いなぁ～！
185 = "あーん。あむっ！　んむんむんむんむ……\\nあー！　やっぱりダクネスに食わせて貰う飯は\\n最高に美味いなぁ～！"

# ダクネス
# それは気のせいだろ。
197 = "それは気のせいだろ。"

# カズマ
# ダクネスさん、次をお願いします！
222 = "ダクネスさん、次をお願いします！"

# ダクネス
# わかったから、そう急かすな。\nほら、あーん。
216 = "わかったから、そう急かすな。\\nほら、あーん。"

# カズマ
# あーーーん！　んむんむんむんむっ……\nあーっ！　ダクネスの料理は！　最高だ！
186 = "あーーーん！　んむんむんむんむっ……\\nあーっ！　ダクネスの料理は！　最高だ！"

# ダクネス
# そうか、美味しいか。\nカズマが喜んでくれて私も嬉しいぞ。
194 = "そうか、美味しいか。\\nカズマが喜んでくれて私も嬉しいぞ。"

# カズマ
# はあ～、心の底から幸せだ～。
208 = "はあ～、心の底から幸せだ～。"

# アクア
# ねえ、なんなのこれ……。
205 = "ねえ、なんなのこれ……。"

# めぐみん
# はあ……知りませんよ。
206 = "はあ……知りませんよ。"

