# root_f23.txt.scn

[info]
0 = ""

[characters]
123 = "カズマ（Ｍ）"
121 = "ウィズ"
122 = "カズマ"

[character_subs]
# 122 = "カズマ"

[script]
# lines: 19

# カズマ（Ｍ）
# display as カズマ
# （はぁ……。\n　最後の最後で大変な目に遭った……）
140 = "（はぁ……。\\n　最後の最後で大変な目に遭った……）"

# ウィズ
# すみません。\nお店まで送ってもらっちゃって。
116 = "すみません。\\nお店まで送ってもらっちゃって。"

# カズマ
# 気にするなって。\nそれよりさ、聖水がかかったところは\n大丈夫なのか？
127 = "気にするなって。\\nそれよりさ、聖水がかかったところは\\n大丈夫なのか？"

# ウィズ
# はい、川の水で洗い流せましたから。
119 = "はい、川の水で洗い流せましたから。"

# カズマ
# そっか、なら良かった。\nにしても、今日は本当に色々あったよなぁ。
117 = "そっか、なら良かった。\\nにしても、今日は本当に色々あったよなぁ。"

# ウィズ
# こんなことに\n付き合わせてしまって、すみませんでした。
115 = "こんなことに\\n付き合わせてしまって、すみませんでした。"

# カズマ
# いや、俺こそ\n大した力になれなくて悪かったよ。
112 = "いや、俺こそ\\n大した力になれなくて悪かったよ。"

# ウィズ
# そんなことありません。\nとっても楽しかったです。
118 = "そんなことありません。\\nとっても楽しかったです。"

# ウィズ
# 街の中を誰かと一緒に歩くのって、\nこんなにも心躍るものなんですね。
138 = "街の中を誰かと一緒に歩くのって、\\nこんなにも心躍るものなんですね。"

# ウィズ
# このお礼は、必ずしますので。
114 = "このお礼は、必ずしますので。"

# カズマ
# いや、別にそういうのはいいって。
113 = "いや、別にそういうのはいいって。"

# ウィズ
# いえ、これだけお世話になったのに\nお礼をしないわけにはいきません。
111 = "いえ、これだけお世話になったのに\\nお礼をしないわけにはいきません。"

# カズマ（Ｍ）
# display as カズマ
# （はあ……。\n　ほんと、どこまで人がいいんだ）
141 = "（はあ……。\\n　ほんと、どこまで人がいいんだ）"

# ウィズ
# あの、ご迷惑でしょうか？
109 = "あの、ご迷惑でしょうか？"

# カズマ
# いいや。\nまあ、その、無理はしない程度にしてくれよ。
110 = "いいや。\\nまあ、その、無理はしない程度にしてくれよ。"

# ウィズ
# はい！\nカズマさんに喜んで頂けるように\n頑張りますから、待ってて下さいね！
120 = "はい！\\nカズマさんに喜んで頂けるように\\n頑張りますから、待ってて下さいね！"

# カズマ（Ｍ）
# display as カズマ
# （ああ……。\n　ウィズの笑顔って、\n　明るくて、あったかくて……）
139 = "（ああ……。\\n　ウィズの笑顔って、\\n　明るくて、あったかくて……）"

# カズマ（Ｍ）
# display as カズマ
# （人のためにこんなにも頑張れる\n　ウィズだからこそ、\n　こんな、太陽のような笑顔が出来るんだろう）
142 = "（人のためにこんなにも頑張れる\\n　ウィズだからこそ、\\n　こんな、太陽のような笑顔が出来るんだろう）"

# カズマ（Ｍ）
# display as カズマ
# （本当に、この人がアンデッドだなんて\n　信じられないぜ）
143 = "（本当に、この人がアンデッドだなんて\\n　信じられないぜ）"

