# root_b12.txt.scn

[info]
0 = ""

[characters]
168 = "カズマ"
167 = "めぐみん"
169 = "カズマ（Ｍ）"

[character_subs]
# 168 = "カズマ"

[script]
# lines: 24

# カズマ
# ……よし。\nこの部屋も誰もいないな。
151 = "……よし。\\nこの部屋も誰もいないな。"

# めぐみん
# 本当に、本当の本当に幽霊だったんですか？
176 = "本当に、本当の本当に幽霊だったんですか？"

# カズマ
# いや、俺だって幽霊がどんなものなのか\n知らないから断言はできねーけど、\n白い何かは間違いなくいたんだよ。
152 = "いや、俺だって幽霊がどんなものなのか\\n知らないから断言はできねーけど、\\n白い何かは間違いなくいたんだよ。"

# めぐみん
# 見間違え、ということはないのですか？
189 = "見間違え、ということはないのですか？"

# カズマ
# 見間違えじゃない。\n絶対にいた。そこは断言できる。
190 = "見間違えじゃない。\\n絶対にいた。そこは断言できる。"

# めぐみん
# ですが、恐怖は人の目を曇らせるものです。\n普通ではない今なら、見間違いが起きても\nおかしくはありませんよ？
161 = "ですが、恐怖は人の目を曇らせるものです。\\n普通ではない今なら、見間違いが起きても\\nおかしくはありませんよ？"

# カズマ
# なんだよ、信じてくれないのか？
164 = "なんだよ、信じてくれないのか？"

# めぐみん
# だって……\nさっきまで何も起こらなかったんですよ？\nなのに、突然、幽霊だなんて……。
160 = "だって……\\nさっきまで何も起こらなかったんですよ？\\nなのに、突然、幽霊だなんて……。"

# めぐみん
# そうですよ！\nきっと見間違いです、幽霊なんかいませんよ！
158 = "そうですよ！\\nきっと見間違いです、幽霊なんかいませんよ！"

# めぐみん
# ずっと緊張状態が続いて、\nカズマも疲れてますよね？\nだから、ありもしない幻覚を見たんです！
155 = "ずっと緊張状態が続いて、\\nカズマも疲れてますよね？\\nだから、ありもしない幻覚を見たんです！"

# めぐみん
# ですよね！？\nそういうことにしておきましょう！
162 = "ですよね！？\\nそういうことにしておきましょう！"

# カズマ（Ｍ）
# display as カズマ
# （……どんなに否定されても\n　見たものは見たんだ。\n　なかったことにはできない）
191 = "（……どんなに否定されても\\n　見たものは見たんだ。\\n　なかったことにはできない）"

# めぐみん
# そうだ！\nお風呂に入ったらどうですか？\n頭もすっきりしますよ？
157 = "そうだ！\\nお風呂に入ったらどうですか？\\n頭もすっきりしますよ？"

# カズマ
# その間、めぐみんは１人になるがいいのか？
159 = "その間、めぐみんは１人になるがいいのか？"

# めぐみん
# なしです！　なしで！\nお風呂に入ってもいいことありませんよぉ！
163 = "なしです！　なしで！\\nお風呂に入ってもいいことありませんよぉ！"

# カズマ（Ｍ）
# display as カズマ
# （大丈夫か、めぐみん。\n　テンションがおかしなことになってるぞ？）
192 = "（大丈夫か、めぐみん。\\n　テンションがおかしなことになってるぞ？）"

# カズマ
# なんにしても、用心に越したことはないだろ。\n他も見てみようぜ。
165 = "なんにしても、用心に越したことはないだろ。\\n他も見てみようぜ。"

# めぐみん
# うううう……。\nなにも出ませんように……\nなにも出ませんように……！
153 = "うううう……。\\nなにも出ませんように……\\nなにも出ませんように……！"

# めぐみん
# 何もいませんでしたね！\nほら、やっぱりカズマの見間違いだったんですよ！
171 = "何もいませんでしたね！\\nほら、やっぱりカズマの見間違いだったんですよ！"

# カズマ
# 待て。\nまだ一番重要なところが残ってるだろ。
175 = "待て。\\nまだ一番重要なところが残ってるだろ。"

# めぐみん
# え……。
154 = "え……。"

# カズマ
# 俺が白いなにかを見た場所だよ。
172 = "俺が白いなにかを見た場所だよ。"

# カズマ
# ほら、行くぞ。\n絶対に見間違えじゃないんだからな。\nしっかり確認するぞ。
166 = "ほら、行くぞ。\\n絶対に見間違えじゃないんだからな。\\nしっかり確認するぞ。"

# めぐみん
# そ、そんなぁ……。
156 = "そ、そんなぁ……。"

