# root_d09.txt.scn

[info]
0 = ""

[characters]
156 = "戦士風の男冒険者"
145 = "カズマ"
148 = "クリス"
162 = "魔術師風の男冒険者"
158 = "盗賊風の男冒険者"
146 = "カズマ（Ｍ）"
161 = "魔術師風の女冒険者"

[character_subs]
155 = "戦士冒険者"
160 = "魔術師冒険者"
157 = "盗賊冒険者"
# 145 = "カズマ"
153 = "女冒険者"

[script]
# lines: 28

# 戦士風の男冒険者
# display as 戦士冒険者
# まてっ！　逃がすか！\n１００万エリスは俺のもんだぁ！
142 = "まてっ！　逃がすか！\\n１００万エリスは俺のもんだぁ！"

# カズマ
# ひいいいいいい！\nなんなんだよ、この数は！！
138 = "ひいいいいいい！\\nなんなんだよ、この数は！！"

# クリス
# いやあ、みんな怖い顔しちゃって必死だね。
127 = "いやあ、みんな怖い顔しちゃって必死だね。"

# カズマ
# くそっ、金に目が眩んだ亡者ばっかりなのか\nこの街は！
132 = "くそっ、金に目が眩んだ亡者ばっかりなのか\\nこの街は！"

# クリス
# そりゃまあ、命の危険がないクエスト内容で\n１００万エリスだもん。
133 = "そりゃまあ、命の危険がないクエスト内容で\\n１００万エリスだもん。"

# クリス
# あたしが当事者じゃなかったら、\n間違いなく参加してたと思うよ？
126 = "あたしが当事者じゃなかったら、\\n間違いなく参加してたと思うよ？"

# カズマ
# ですよねー！！
135 = "ですよねー！！"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# ファイアーボール！
150 = "ファイアーボール！"

# カズマ
# って、魔法は卑怯だろ！
134 = "って、魔法は卑怯だろ！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# バインド！！
149 = "バインド！！"

# カズマ
# 食らうかボケ！
159 = "食らうかボケ！"

# クリス
# ねえ、カズマ。\nいくらなんでも、振りきるには\n追ってくる人数が多すぎると思うんだけど。
137 = "ねえ、カズマ。\\nいくらなんでも、振りきるには\\n追ってくる人数が多すぎると思うんだけど。"

# カズマ
# わかってる！\n今、考えてるから！
144 = "わかってる！\\n今、考えてるから！"

# クリス
# ほらほら、早くしないと追いつかれちゃうよ。
140 = "ほらほら、早くしないと追いつかれちゃうよ。"

# カズマ（Ｍ）
# display as カズマ
# （考えろ、考えるんだ、こういう時はどうしたら！\n　そうだ！）
164 = "（考えろ、考えるんだ、こういう時はどうしたら！\\n　そうだ！）"

# カズマ
# クリエイト・ウォーターッ！
147 = "クリエイト・ウォーターッ！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# 初級魔法で水なんかばらまいて\nどうするつもり──
152 = "初級魔法で水なんかばらまいて\\nどうするつもり──"

# カズマ
# フリーズッ！！
151 = "フリーズッ！！"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# うわぁっ！？\nじ、地面が凍って、足が動かないっ？
128 = "うわぁっ！？\\nじ、地面が凍って、足が動かないっ？"

# 戦士風の男冒険者
# display as 戦士冒険者
# おい何やって……うわっ！\nな、なんだこれ！！　滑って前に進めな……！
130 = "おい何やって……うわっ！\\nな、なんだこれ！！　滑って前に進めな……！"

# クリス
# へー、初級魔法なんて習得しても使わない人が\nほとんどなのに、工夫次第でこうも使える\nスキルになるんだ。
139 = "へー、初級魔法なんて習得しても使わない人が\\nほとんどなのに、工夫次第でこうも使える\\nスキルになるんだ。"

# カズマ
# 感心してないで逃げるぞ！
154 = "感心してないで逃げるぞ！"

# クリス
# うん、どこに？
129 = "うん、どこに？"

# カズマ
# どこにって！
136 = "どこにって！"

# 魔術師風の女冒険者
# display as 女冒険者
# おーい！\nみんな、こっちにいたよ！！
131 = "おーい！\\nみんな、こっちにいたよ！！"

# カズマ（Ｍ）
# display as カズマ
# （くっそ、前からも！）
163 = "（くっそ、前からも！）"

# クリス
# ほらほら、早く決断しないと、\n人がどんどん集まってきちゃうよ。
141 = "ほらほら、早く決断しないと、\\n人がどんどん集まってきちゃうよ。"

# カズマ
# よし、こっちだ！\n行くぞ、クリス！！
143 = "よし、こっちだ！\\n行くぞ、クリス！！"

