# root_c15.txt.scn

[info]
0 = ""

[characters]
231 = "カズマ"
236 = "ダクネス"
234 = "カズマ（Ｍ）"
230 = "アクア"
228 = "めぐみん"

[character_subs]
# 231 = "カズマ"

[script]
# lines: 51

# カズマ
# …………。
204 = "…………。"

# ダクネス
# …………。
# 204 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （しまったーー！！\n　勢いで乗り切ろうと決めたのはいいが、\n　こんな何もないところに来てしまった！）
284 = "（しまったーー！！\\n　勢いで乗り切ろうと決めたのはいいが、\\n　こんな何もないところに来てしまった！）"

# ダクネス
# な、なぁ、カズマ？\nどこに向かっているのだ？
221 = "な、なぁ、カズマ？\\nどこに向かっているのだ？"

# カズマ
# も、もう少しだ。\nもう少ししたら、多分、いい場所がある。
229 = "も、もう少しだ。\\nもう少ししたら、多分、いい場所がある。"

# ダクネス
# そ、そうか……。
217 = "そ、そうか……。"

# カズマ（Ｍ）
# display as カズマ
# （ううう、そこはかとなくいい感じな場所は\n　なかなかないもんだな――）
282 = "（ううう、そこはかとなくいい感じな場所は\\n　なかなかないもんだな――）"

# アクア
# こそこそこそこそ……。\nこそこそこそこそ……。
212 = "こそこそこそこそ……。\\nこそこそこそこそ……。"

# めぐみん
# こそこそこそこそ……。\nこそこそこそこそ……。
# 212 = "こそこそこそこそ……。\\nこそこそこそこそ……。"

# カズマ（Ｍ）
# display as カズマ
# （……あいつら、まだ尾行してるのか。\n　こんな隠れる場所が少ない開けた場所で\n　見つからないとでも思ってるのか？）
278 = "（……あいつら、まだ尾行してるのか。\\n　こんな隠れる場所が少ない開けた場所で\\n　見つからないとでも思ってるのか？）"

# ダクネス
# なあ、カズマ。
222 = "なあ、カズマ。"

# カズマ
# なんだ？\n疲れたんだったら、この辺で休憩でもするか。
224 = "なんだ？\\n疲れたんだったら、この辺で休憩でもするか。"

# ダクネス
# いや、それは構わないのだが……\nここから先はジャイアントトードの巣だ。\n充分に気をつけろ。
208 = "いや、それは構わないのだが……\\nここから先はジャイアントトードの巣だ。\\n充分に気をつけろ。"

# カズマ
# ええっ！？　マジで！
210 = "ええっ！？　マジで！"

# カズマ（Ｍ）
# display as カズマ
# （どうりで見覚えがある場所だと！\n　そうか、ここがあの忌まわしい場所だったのか）
286 = "（どうりで見覚えがある場所だと！\\n　そうか、ここがあの忌まわしい場所だったのか）"

# ダクネス
# カズマは、ここに来たことがあるのか？
233 = "カズマは、ここに来たことがあるのか？"

# カズマ
# ああ、何度かな。\n報酬につられて、ろくな装備もない状態で\n引き受けたから苦労も倍だったぜ。
206 = "ああ、何度かな。\\n報酬につられて、ろくな装備もない状態で\\n引き受けたから苦労も倍だったぜ。"

# カズマ
# そういやあの時は、アクアとめぐみんが\nカエルに食われかけて大変だったなぁ。
219 = "そういやあの時は、アクアとめぐみんが\\nカエルに食われかけて大変だったなぁ。"

# ダクネス
# なっ、何！？\n食われかけただと！？
223 = "なっ、何！？\\n食われかけただと！？"

# カズマ
# えっ？
211 = "えっ？"

# ダクネス
# 生きたまま食われるというのは、\nどんな感じなんだ？\nそれに、飲み込まれるのはどんな気持ちだ？
246 = "生きたまま食われるというのは、\\nどんな感じなんだ？\\nそれに、飲み込まれるのはどんな気持ちだ？"

# カズマ
# 別に、俺が食われたわけじゃないけど、\nアクアもめぐみんも頭からぱくっと咥えられて\nちょっとずつ飲み込まれていったな。
240 = "別に、俺が食われたわけじゃないけど、\\nアクアもめぐみんも頭からぱくっと咥えられて\\nちょっとずつ飲み込まれていったな。"

# ダクネス
# 頭からぱくっとか！\nそれで、それから！？
277 = "頭からぱくっとか！\\nそれで、それから！？"

# カズマ
# まぁ、やつらは食ってる最中は動きが止まるから、\nなんとか倒して救出したよ。
227 = "まぁ、やつらは食ってる最中は動きが止まるから、\\nなんとか倒して救出したよ。"

# カズマ
# 助け出したアクアとめぐみんは\nヌルヌルした粘液まみれで、\nそりゃひどかったな……。
242 = "助け出したアクアとめぐみんは\\nヌルヌルした粘液まみれで、\\nそりゃひどかったな……。"

# カズマ
# あ、そういえばめぐみんが、\nカエルの中って意外と温いっていってたな。
205 = "あ、そういえばめぐみんが、\\nカエルの中って意外と温いっていってたな。"

# ダクネス
# そ、そうか……カエルの中は\n粘液でヌルヌルとして温いのだな……。
218 = "そ、そうか……カエルの中は\\n粘液でヌルヌルとして温いのだな……。"

# ダクネス
# ふふふ、なるほど、そういうことか。\nここへ私を連れてきたのは、\nそういう行為を求めていたからなんだな？
226 = "ふふふ、なるほど、そういうことか。\\nここへ私を連れてきたのは、\\nそういう行為を求めていたからなんだな？"

# カズマ（Ｍ）
# display as カズマ
# （……ちょっと、ダクネスさん？\n　何言ってんの？）
279 = "（……ちょっと、ダクネスさん？\\n　何言ってんの？）"

# ダクネス
# さりげなく私を誘導するとはさすがだな。\n２人っきりになったとたん、\n鬼畜な一面を見せるなんて人が悪いぞ。
213 = "さりげなく私を誘導するとはさすがだな。\\n２人っきりになったとたん、\\n鬼畜な一面を見せるなんて人が悪いぞ。"

# ダクネス
# しかし、カズマが望むのなら\nジャイアントトードを使った\nヌルヌルプレイを、私も受け入れようっ！
215 = "しかし、カズマが望むのなら\\nジャイアントトードを使った\\nヌルヌルプレイを、私も受け入れようっ！"

# カズマ（Ｍ）
# display as カズマ
# （しまったぁ！\n　ダクネスのスイッチを入れちまった！！）
283 = "（しまったぁ！\\n　ダクネスのスイッチを入れちまった！！）"

# カズマ（Ｍ）
# display as カズマ
# （い、いや、待てよ？\n　ダクネスは今、俺が望むならって言ったよな？）
281 = "（い、いや、待てよ？\\n　ダクネスは今、俺が望むならって言ったよな？）"

# カズマ（Ｍ）
# display as カズマ
# （ということは、俺が頼んだら\n　どんなプレイもオッケーってことか？\n　そうなのか、ダクネス！？）
285 = "（ということは、俺が頼んだら\\n　どんなプレイもオッケーってことか？\\n　そうなのか、ダクネス！？）"

# ダクネス
# ああっ……！\nカズマが私に、期待するような\n眼差しを向けている……！
207 = "ああっ……！\\nカズマが私に、期待するような\\n眼差しを向けている……！"

# ダクネス
# し、しかしダメだ！\nそのような誘惑に……\nいや、要求に屈するわけには！
214 = "し、しかしダメだ！\\nそのような誘惑に……\\nいや、要求に屈するわけには！"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスは、口では嫌がりながらも\n　俺の望みを叶えてくれる。\n　そこまで俺のことを……！）
287 = "（ダクネスは、口では嫌がりながらも\\n　俺の望みを叶えてくれる。\\n　そこまで俺のことを……！）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、これが愛というものなんだな！）
280 = "（ああ、これが愛というものなんだな！）"

# カズマ
# ダクネス、俺は――
237 = "ダクネス、俺は――"

# アクア
# いやぁっ！\n助けてカズマぁー！！
209 = "いやぁっ！\\n助けてカズマぁー！！"

# ダクネス
# はっ！？\nな、なんだ、今のはアクアの声だぞ！
225 = "はっ！？\\nな、なんだ、今のはアクアの声だぞ！"

# アクア
# 助けてってばー！\n早く、早く―――あぷ！
241 = "助けてってばー！\\n早く、早く―――あぷ！"

# ダクネス
# た、大変だカズマ！\nアクアがジャイアントトードに！！
220 = "た、大変だカズマ！\\nアクアがジャイアントトードに！！"

# カズマ
# 見りゃわかる！\n手間とらせやがって、今助けるぞ！！
276 = "見りゃわかる！\\n手間とらせやがって、今助けるぞ！！"

# めぐみん
# カズマ、気をつけてください！\n後ろからもう１匹、近づいてます！
232 = "カズマ、気をつけてください！\\n後ろからもう１匹、近づいてます！"

# カズマ
# 見てないでお前も助けろよ！！
275 = "見てないでお前も助けろよ！！"

# めぐみん
# 今、爆裂魔法を撃ち込んだら\nみんな死んでしまいますよ！
239 = "今、爆裂魔法を撃ち込んだら\\nみんな死んでしまいますよ！"

# ダクネス
# 危ない、カズマッ！
243 = "危ない、カズマッ！"

# カズマ
# しまったっ！
216 = "しまったっ！"

# カズマ
# ダ、ダクネスー！！\nい、今助けるから待ってろー！
235 = "ダ、ダクネスー！！\\nい、今助けるから待ってろー！"

# カズマ（Ｍ）
# display as カズマ
# （初デートだっていうのに、なんなんだよ！\n　トード退治が思い出だなんて俺は認めない、\n　認めねーからなぁ！）
288 = "（初デートだっていうのに、なんなんだよ！\\n　トード退治が思い出だなんて俺は認めない、\\n　認めねーからなぁ！）"

