# root_e19.txt.scn

[info]
0 = ""

[characters]
187 = "ゆんゆん"
192 = "ダクネス"
189 = "アクア"
182 = "めぐみん"
191 = "カズマ（Ｍ）"

[character_subs]
190 = "カズマ"

[script]
# lines: 27

# ゆんゆん
# 今日まで、お世話になりました。
194 = "今日まで、お世話になりました。"

# ダクネス
# 勝負は引き分けだったが……\n何も出ていくことはないのでは？
195 = "勝負は引き分けだったが……\\n何も出ていくことはないのでは？"

# アクア
# そうよ。\n遠慮しないで、もっといていいのよ？
173 = "そうよ。\\n遠慮しないで、もっといていいのよ？"

# ゆんゆん
# ありがとうございます。\nでも、気付いたんです。
165 = "ありがとうございます。\\nでも、気付いたんです。"

# ゆんゆん
# めぐみんの弱点を見つける前に、\nもっと自分を磨かないといけないんだって。
183 = "めぐみんの弱点を見つける前に、\\nもっと自分を磨かないといけないんだって。"

# ゆんゆん
# だから１人でもっと修行をします。\nそして、納得できる成果を上げることができたら、\n必ずまたここへ戻ってきます。
176 = "だから１人でもっと修行をします。\\nそして、納得できる成果を上げることができたら、\\n必ずまたここへ戻ってきます。"

# めぐみん
# え……。\nそれってまさか……。
167 = "え……。\\nそれってまさか……。"

# ダクネス
# ……そうか。\nそれは寂しくなるな。
164 = "……そうか。\\nそれは寂しくなるな。"

# めぐみん
# そ、それで？\nどこまで修行の旅に出るつもりですか？
172 = "そ、それで？\\nどこまで修行の旅に出るつもりですか？"

# ゆんゆん
# え？　旅？\nそれって何？
170 = "え？　旅？\\nそれって何？"

# めぐみん
# そっちが言ったのですよ？\n１人でもっと修行をすると。
174 = "そっちが言ったのですよ？\\n１人でもっと修行をすると。"

# ゆんゆん
# うん、そうだけど。
166 = "うん、そうだけど。"

# めぐみん
# だから……この街を離れて\nどこかにいくのではないのですか？
175 = "だから……この街を離れて\\nどこかにいくのではないのですか？"

# ゆんゆん
# え？　どうして？
169 = "え？　どうして？"

# めぐみん
# どうしてって……。
177 = "どうしてって……。"

# ゆんゆん
# この街でも魔法の修行はできるよ？\nめぐみんだってしてるじゃない。
171 = "この街でも魔法の修行はできるよ？\\nめぐみんだってしてるじゃない。"

# めぐみん
# …………。
163 = "…………。"

# ゆんゆん
# めぐみん？
184 = "めぐみん？"

# めぐみん
# はぁぁぁ？\nそれでなんであんな言い方をするのですか？\nあなたは大げさなのですよ！
179 = "はぁぁぁ？\\nそれでなんであんな言い方をするのですか？\\nあなたは大げさなのですよ！"

# ゆんゆん
# え？　ええ？\nなんで怒られてるの、私？
168 = "え？　ええ？\\nなんで怒られてるの、私？"

# めぐみん
# ゆんゆんが馬鹿だからですよ！
188 = "ゆんゆんが馬鹿だからですよ！"

# ゆんゆん
# ば、馬鹿じゃないもん！\n馬鹿って言う方が馬鹿なんだから！
180 = "ば、馬鹿じゃないもん！\\n馬鹿って言う方が馬鹿なんだから！"

# めぐみん
# もうどこへなり行けばいいんですよ！\nシッシッ！
186 = "もうどこへなり行けばいいんですよ！\\nシッシッ！"

# ゆんゆん
# ひ、酷い！\nめぐみんって昔からそう！
181 = "ひ、酷い！\\nめぐみんって昔からそう！"

# めぐみん
# なんですか？\n文句があるなら聞きましょう。\nその代わり倍にして返しますから！
178 = "なんですか？\\n文句があるなら聞きましょう。\\nその代わり倍にして返しますから！"

# ゆんゆん
# もぅ！　もぅ！　もぅ～～～！！
185 = "もぅ！　もぅ！　もぅ～～～！！"

# カズマ（Ｍ）
# display as カズマ
# （……やれやれ。\n　なんていうか、本当にいつも通りって感じだな。\n　まあ、これが一番なんだろうけど）
220 = "（……やれやれ。\\n　なんていうか、本当にいつも通りって感じだな。\\n　まあ、これが一番なんだろうけど）"

