# root_d21.txt.scn

[info]
0 = ""

[characters]
320 = "クリス"
313 = "カズマ"
319 = "カズマ（Ｍ）"

[character_subs]
# 313 = "カズマ"

[script]
# lines: 119

# クリス
# ～～～～♪
357 = "～～～～♪"

# カズマ
# 尻……。
329 = "尻……。"

# クリス
# ～～～～♪
# 357 = "～～～～♪"

# カズマ
# 尻だ。
330 = "尻だ。"

# クリス
# ん、何か言った？
311 = "ん、何か言った？"

# カズマ
# な、なんでもないっすよ。
290 = "な、なんでもないっすよ。"

# クリス
# ちょっとスピード上げるよ。\nちゃんとあたしの後についてきてね。
283 = "ちょっとスピード上げるよ。\\nちゃんとあたしの後についてきてね。"

# カズマ
# お、おう。
256 = "お、おう。"

# カズマ（Ｍ）
# display as カズマ
# （いかん、なけなしの集中力が\n　クリスの尻に削ぎ落とされていく！）
341 = "（いかん、なけなしの集中力が\\n　クリスの尻に削ぎ落とされていく！）"

# カズマ（Ｍ）
# display as カズマ
# （こんな危険な所を歩いてるんだ、\n　今は目の前のことに集中しろー）
346 = "（こんな危険な所を歩いてるんだ、\\n　今は目の前のことに集中しろー）"

# カズマ（Ｍ）
# display as カズマ
# （目の前のこと、それはつまり、尻！！）
356 = "（目の前のこと、それはつまり、尻！！）"

# カズマ
# って俺はバカかーー！！
284 = "って俺はバカかーー！！"

# クリス
# え？　え？　どうしたの急に。
254 = "え？　え？　どうしたの急に。"

# カズマ（Ｍ）
# display as カズマ
# （いや、ダメだ！\n　今、クリスを見るのはまずい！！）
342 = "（いや、ダメだ！\\n　今、クリスを見るのはまずい！！）"

# カズマ（Ｍ）
# display as カズマ
# （ちょっとこう、健全な青少年的に\n　この格好と角度は色々くるものがある！）
349 = "（ちょっとこう、健全な青少年的に\\n　この格好と角度は色々くるものがある！）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、空はどこまでも澄んでいて\n　心が洗われるなー）
339 = "（ああ、空はどこまでも澄んでいて\\n　心が洗われるなー）"

# クリス
# ねぇ、大丈夫？\nさっきから様子がおかしいよ？\nもしかして、高いところ苦手だったのかな。
295 = "ねぇ、大丈夫？\\nさっきから様子がおかしいよ？\\nもしかして、高いところ苦手だったのかな。"

# カズマ
# そそそ、そんなことはありませんよ？
270 = "そそそ、そんなことはありませんよ？"

# クリス
# それだったらいいけどさ、\nでも、前はちゃんと見た方がいいと\n思うんだよね。
274 = "それだったらいいけどさ、\\nでも、前はちゃんと見た方がいいと\\n思うんだよね。"

# カズマ
# そ、そうか？
268 = "そ、そうか？"

# クリス
# ていうか、こういう所で上を向く意味が\nわからないんだけど。
286 = "ていうか、こういう所で上を向く意味が\\nわからないんだけど。"

# カズマ（Ｍ）
# display as カズマ
# （ごもっともです！）
347 = "（ごもっともです！）"

# クリス
# ほら、ちゃんと前を見る。\n何かあった時に、それじゃとっさに\n行動できないよ？
305 = "ほら、ちゃんと前を見る。\\n何かあった時に、それじゃとっさに\\n行動できないよ？"

# カズマ
# じゃあ、見ますよ？　見ますからね？
266 = "じゃあ、見ますよ？　見ますからね？"

# カズマ
# ごちそうさまです！
264 = "ごちそうさまです！"

# クリス
# へ？　何？　どういうこと？
302 = "へ？　何？　どういうこと？"

# カズマ
# いやなんでもない。\n今のは男の心の叫びみたいなもんだ。
246 = "いやなんでもない。\\n今のは男の心の叫びみたいなもんだ。"

# クリス
# こ、心の叫び？
262 = "こ、心の叫び？"

# カズマ
# しかし、あれですねクリスさん。\nこう、軽快に上っていきますね。
265 = "しかし、あれですねクリスさん。\\nこう、軽快に上っていきますね。"

# カズマ（Ｍ）
# display as カズマ
# （おしりをぷりぷりさせながら！）
343 = "（おしりをぷりぷりさせながら！）"

# クリス
# 職業柄、高所とかでの偵察を\n良く頼まれるからね。
337 = "職業柄、高所とかでの偵察を\\n良く頼まれるからね。"

# カズマ
# ふ、ふーん、そういうときも……\n今みたいに四つん這いになるのかな？
300 = "ふ、ふーん、そういうときも……\\n今みたいに四つん這いになるのかな？"

# クリス
# 場所によるけど……。\n何その質問？
328 = "場所によるけど……。\\n何その質問？"

# カズマ
# あっ、いやほら、俺もそういうことを\n頼まれるかもしれないじゃん？
239 = "あっ、いやほら、俺もそういうことを\\n頼まれるかもしれないじゃん？"

# カズマ
# だから、後学のために聞いておこうかなってさ！
278 = "だから、後学のために聞いておこうかなってさ！"

# クリス
# 勉強熱心なのは素晴らしいけど、\n今は手元を気にしようね。
327 = "勉強熱心なのは素晴らしいけど、\\n今は手元を気にしようね。"

# クリス
# ほら、そこ、瓦が割れてるから気をつけて。
304 = "ほら、そこ、瓦が割れてるから気をつけて。"

# カズマ
# おっと、危ない！
258 = "おっと、危ない！"

# クリス
# ふーん。\nちょっと見直したかも。
301 = "ふーん。\\nちょっと見直したかも。"

# カズマ
# え、どうしてだ？
250 = "え、どうしてだ？"

# クリス
# あたし、てっきり震えて動けなくなるかと\n思ってたから。
238 = "あたし、てっきり震えて動けなくなるかと\\n思ってたから。"

# カズマ
# えっと……。
252 = "えっと……。"

# クリス
# ほら、ここって結構高いじゃない。\n落ちたら死ぬくらいに。
303 = "ほら、ここって結構高いじゃない。\\n落ちたら死ぬくらいに。"

# カズマ（Ｍ）
# display as カズマ
# （そうだったーーーー！！）
348 = "（そうだったーーーー！！）"

# カズマ（Ｍ）
# display as カズマ
# （クリスの尻に夢中で気にする余裕無かったけど、\n　俺は今死と隣り合わせの状況だったんだ！）
354 = "（クリスの尻に夢中で気にする余裕無かったけど、\\n　俺は今死と隣り合わせの状況だったんだ！）"

# カズマ
# お、おおお、おおおおおーーー！
257 = "お、おおお、おおおおおーーー！"

# クリス
# ええと、ごめん。\nもしかしてあたし、余計なこと言っちゃったかな。
251 = "ええと、ごめん。\\nもしかしてあたし、余計なこと言っちゃったかな。"

# カズマ
# そそそそそ、そんなことないですよ。
271 = "そそそそそ、そんなことないですよ。"

# クリス
# その割には足が震えてるように見えるんだけど。
272 = "その割には足が震えてるように見えるんだけど。"

# カズマ
# だって仕方ないじゃない！\n怖いものは怖いんだもの！
280 = "だって仕方ないじゃない！\\n怖いものは怖いんだもの！"

# クリス
# だらしないなぁ。\nほら、あたしの手に捕まりなよ。
281 = "だらしないなぁ。\\nほら、あたしの手に捕まりなよ。"

# カズマ
# すまん、クリス。\n恩にきる……おわっ！？
267 = "すまん、クリス。\\n恩にきる……おわっ！？"

# クリス
# きゃあっ！？
260 = "きゃあっ！？"

# カズマ
# うおおおお、落ちる！　死ぬーーーーー！！
248 = "うおおおお、落ちる！　死ぬーーーーー！！"

# クリス
# ちょっとやめて！　離して！！\n脱げちゃうからぁ！！
282 = "ちょっとやめて！　離して！！\\n脱げちゃうからぁ！！"

# カズマ
# は？
298 = "は？"

# カズマ
# なあ！？
291 = "なあ！？"

# クリス
# カズマっ！！\nどこ掴んでるのさ！
317 = "カズマっ！！\\nどこ掴んでるのさ！"

# カズマ
# どこって、ズボンですっ！
288 = "どこって、ズボンですっ！"

# クリス
# そこ正直に答える所じゃないよ！
269 = "そこ正直に答える所じゃないよ！"

# クリス
# お願いだから離してよ！\n脱げちゃう～～～～！！
259 = "お願いだから離してよ！\\n脱げちゃう～～～～！！"

# カズマ
# 落ちつけクリス！\nお前にはスパッツという最後の盾があるだろ！
338 = "落ちつけクリス！\\nお前にはスパッツという最後の盾があるだろ！"

# クリス
# その最後の盾も掴んでるのはカズマでしょ！？
273 = "その最後の盾も掴んでるのはカズマでしょ！？"

# カズマ
# なんと！\nじゃあ、このまま脱げたら……！
294 = "なんと！\\nじゃあ、このまま脱げたら……！"

# クリス
# 全部、見えちゃうのっ！
326 = "全部、見えちゃうのっ！"

# カズマ（Ｍ）
# display as カズマ
# （全部だと！）
355 = "（全部だと！）"

# カズマ
# それはマズイ！　色々な意味でマズイぞ、クリス！
275 = "それはマズイ！　色々な意味でマズイぞ、クリス！"

# クリス
# わかったなら離してよぉっ！
310 = "わかったなら離してよぉっ！"

# カズマ
# でも離したら俺が死ぬ～！！
287 = "でも離したら俺が死ぬ～！！"

# クリス
# そんなことどうでもいいったらぁ！
276 = "そんなことどうでもいいったらぁ！"

# カズマ
# よくねえだろ！
307 = "よくねえだろ！"

# クリス
# う、うう、ズボンが脱げ……るぅ！！
247 = "う、うう、ズボンが脱げ……るぅ！！"

# カズマ
# よし、わかった。\nせめてスパッツから指を離すから！
308 = "よし、わかった。\\nせめてスパッツから指を離すから！"

# クリス
# きゃっ！　くすぐったいでしょ！\nこのスケベ変態カズマ！
261 = "きゃっ！　くすぐったいでしょ！\\nこのスケベ変態カズマ！"

# カズマ
# だからその最後の\nカズマってなんなんですかね！？
279 = "だからその最後の\\nカズマってなんなんですかね！？"

# カズマ（Ｍ）
# display as カズマ
# （やばい、また滑って！）
352 = "（やばい、また滑って！）"

# クリス
# いやああああああ！\n脱げちゃう、脱げちゃう～っ！！
245 = "いやああああああ！\\n脱げちゃう、脱げちゃう～っ！！"

# カズマ
# うおおおおおおお！\n落ちちゃう、落ちちゃう～っ！！
249 = "うおおおおおおお！\\n落ちちゃう、落ちちゃう～っ！！"

# カズマ（Ｍ）
# display as カズマ
# （と、とりあえず、クリスを落ち着かせなくては！）
350 = "（と、とりあえず、クリスを落ち着かせなくては！）"

# カズマ（Ｍ）
# display as カズマ
# （このままだと、またエリス様に\n　くだらないことで死なないでくれって\n　溜息をつかれることになる！）
344 = "（このままだと、またエリス様に\\n　くだらないことで死なないでくれって\\n　溜息をつかれることになる！）"

# カズマ
# 目をつむるから！\n目をつむっていれば見えないぞ！\nだから落ち着いてくれ！
335 = "目をつむるから！\\n目をつむっていれば見えないぞ！\\nだから落ち着いてくれ！"

# クリス
# はぁっ！？　何言ってんの？\nそんなことで落ちつけると思う！？
296 = "はぁっ！？　何言ってんの？\\nそんなことで落ちつけると思う！？"

# カズマ
# 目をつむればズボンが脱げたとしてもわからない！\nだからクリスも恥ずかしくないだろ！？
336 = "目をつむればズボンが脱げたとしてもわからない！\\nだからクリスも恥ずかしくないだろ！？"

# クリス
# そんなわけないでしょ！！
277 = "そんなわけないでしょ！！"

# カズマ
# な、なんだよ、なんでそんなに怒るんだよ、\n我ながらいい案だと思ったのに！
289 = "な、なんだよ、なんでそんなに怒るんだよ、\\n我ながらいい案だと思ったのに！"

# クリス
# もうもうもうっ！\n離して離して離してー！！
306 = "もうもうもうっ！\\n離して離して離してー！！"

# カズマ
# アホ、そんなに尻振ったら！
312 = "アホ、そんなに尻振ったら！"

# クリス
# ひうっ！？\n脱ーげーるーーーーー！！
299 = "ひうっ！？\\n脱ーげーるーーーーー！！"

# カズマ
# あっかーーーーーん！！
240 = "あっかーーーーーん！！"

# カズマ（Ｍ）
# display as カズマ
# （ああ、空はどこまでも澄んでいて\n　心が洗われるなー）
# 339 = "（ああ、空はどこまでも澄んでいて\\n　心が洗われるなー）"

# カズマ
# 手を離すぞ！\nだから冷静になれ、クリス！
332 = "手を離すぞ！\\nだから冷静になれ、クリス！"

# クリス
# 早くっ！　早く離してっ！\nこのままじゃお嫁に行くどころか\n二度と人前に出られなくなっちゃう～！！
333 = "早くっ！　早く離してっ！\\nこのままじゃお嫁に行くどころか\\n二度と人前に出られなくなっちゃう～！！"

# カズマ（Ｍ）
# display as カズマ
# （どこか掴まる場所は……\n　ああもう、なんでこの世界の屋根は\n　こんなにのっぺりとしてるんだよ！）
351 = "（どこか掴まる場所は……\\n　ああもう、なんでこの世界の屋根は\\n　こんなにのっぺりとしてるんだよ！）"

# クリス
# カズマ、早くぅっ！\nズボンとスパッツがもう限界！！
316 = "カズマ、早くぅっ！\\nズボンとスパッツがもう限界！！"

# カズマ
# わかったから、ちょっと大人しくしてろ！\nお尻が見えたくらいで嫁に行けなくなるって\n言うなら、俺が責任取ってやるから！
309 = "わかったから、ちょっと大人しくしてろ！\\nお尻が見えたくらいで嫁に行けなくなるって\\n言うなら、俺が責任取ってやるから！"

# クリス
# ……えっ？
236 = "……えっ？"

# クリス
# カズマ、それって……。
315 = "カズマ、それって……。"

# カズマ（Ｍ）
# display as カズマ
# （あっ！　この手の感触。\n　ダメなやつだ……）
340 = "（あっ！　この手の感触。\\n　ダメなやつだ……）"

# カズマ
# 俺を置いて、ひとりで逃げてくれ！
324 = "俺を置いて、ひとりで逃げてくれ！"

# クリス
# なら、その手を離してよっ！
292 = "なら、その手を離してよっ！"

# カズマ
# いや、それは無理だ！
244 = "いや、それは無理だ！"

# クリス
# なんでさ！？
293 = "なんでさ！？"

# カズマ
# この手を離す前に……\nクリスに伝えたいことがあるんだ。
263 = "この手を離す前に……\\nクリスに伝えたいことがあるんだ。"

# クリス
# えっ？
253 = "えっ？"

# カズマ
# クリス、もし俺がここで\n志半ばに倒れたとしても、\n決して気に病まないでくれ。
322 = "クリス、もし俺がここで\\n志半ばに倒れたとしても、\\n決して気に病まないでくれ。"

# カズマ
# 俺は……クリスと出会えて幸せだったから。\n俺がいなくなったとしても……\nほんの少しでいいから、それを覚えていて欲しい。
323 = "俺は……クリスと出会えて幸せだったから。\\n俺がいなくなったとしても……\\nほんの少しでいいから、それを覚えていて欲しい。"

# カズマ
# クリス、お前は最高の相棒で……友達だったよ。
321 = "クリス、お前は最高の相棒で……友達だったよ。"

# クリス
# カズマ……。
314 = "カズマ……。"

# カズマ
# って言われると、罪悪感が芽生えないか？
285 = "って言われると、罪悪感が芽生えないか？"

# クリス
# はぁ？
297 = "はぁ？"

# カズマ
# いいのか？\n本当に俺がこの手を離してもいいのか？\n今ならまだ間に合うぞ！？
243 = "いいのか？\\n本当に俺がこの手を離してもいいのか？\\n今ならまだ間に合うぞ！？"

# クリス
# …………。
235 = "…………。"

# カズマ
# あれ、どうしたクリス？
241 = "あれ、どうしたクリス？"

# クリス
# カズマのバカーーーーー！！！！
318 = "カズマのバカーーーーー！！！！"

# カズマ
# お、おい、暴れたりしたら！！
255 = "お、おい、暴れたりしたら！！"

# クリス
# あ……。
237 = "あ……。"

# カズマ（Ｍ）
# display as カズマ
# （この手の感触。\n　ダメなやつだ……）
345 = "（この手の感触。\\n　ダメなやつだ……）"

# クリス
# い、い、いいやあああああああああああああ！！
242 = "い、い、いいやあああああああああああああ！！"

# カズマ（Ｍ）
# display as カズマ
# （エリス様、今会いに行きます）
353 = "（エリス様、今会いに行きます）"

[selections]
334 = "目をつむるから！"
331 = "手を離すぞ！"
325 = "俺を置いてひとりで逃げてくれ"
