# root_b19.txt.scn

[info]
0 = ""

[characters]
164 = "カズマ"
161 = "めぐみん"

[character_subs]

[script]
# lines: 33

# カズマ
# どうだ？\n指輪の代わりになりそうな物、見つかったか？
159 = "どうだ？\\n指輪の代わりになりそうな物、見つかったか？"

# めぐみん
# いいえ、なにも。\nカズマこそどうなんです？
144 = "いいえ、なにも。\\nカズマこそどうなんです？"

# カズマ
# 残念ながらこっちも収穫なしだ。
173 = "残念ながらこっちも収穫なしだ。"

# めぐみん
# そうですか……。
151 = "そうですか……。"

# カズマ
# ダメ元で聞くが、\nドレスは脱げそうにないんだよな？
165 = "ダメ元で聞くが、\\nドレスは脱げそうにないんだよな？"

# めぐみん
# 無理です。\n何度も試しましたが、なにも変わりません。
174 = "無理です。\\n何度も試しましたが、なにも変わりません。"

# カズマ
# だよなぁ。\n呪いを解かない限り、どうしようもないか。
154 = "だよなぁ。\\n呪いを解かない限り、どうしようもないか。"

# めぐみん
# もし、万が一、このまま\n一生脱げなかったらどうしたらいいのでしょう？\nこれではお風呂にも入れません。
163 = "もし、万が一、このまま\\n一生脱げなかったらどうしたらいいのでしょう？\\nこれではお風呂にも入れません。"

# カズマ
# だ、大丈夫だって！\nきっとなんとかなる！
153 = "だ、大丈夫だって！\\nきっとなんとかなる！"

# めぐみん
# ……その根拠はなんなのです？
139 = "……その根拠はなんなのです？"

# カズマ
# 根拠はない！\nきっとなんとかなる！
172 = "根拠はない！\\nきっとなんとかなる！"

# めぐみん
# ……いい加減ですね。
138 = "……いい加減ですね。"

# カズマ
# いい加減でもなんでも、\n今は大丈夫だって思っておけ。\nマイナスのイメージは失敗を生むんだからな。
145 = "いい加減でもなんでも、\\n今は大丈夫だって思っておけ。\\nマイナスのイメージは失敗を生むんだからな。"

# カズマ
# しかし、どうする？\n指輪がないんじゃ――
149 = "しかし、どうする？\\n指輪がないんじゃ――"

# カズマ
# あっ！！
143 = "あっ！！"

# めぐみん
# ひぃっ！？\nな、なんですか、急に！
160 = "ひぃっ！？\\nな、なんですか、急に！"

# カズマ
# そうだ、忘れてた！\nこいつがあるじゃないか！
150 = "そうだ、忘れてた！\\nこいつがあるじゃないか！"

# めぐみん
# ああ、拾った指輪ですか。\n私は一応、覚えていましたけど……。
142 = "ああ、拾った指輪ですか。\\n私は一応、覚えていましたけど……。"

# めぐみん
# それは呪われてるんですよね？\nここで更に呪われようなんて、\n正気とは思えませんね。
152 = "それは呪われてるんですよね？\\nここで更に呪われようなんて、\\n正気とは思えませんね。"

# カズマ
# 逆に考えるんだよ。\nここで呪いが１つ増えたところで同じだって。
191 = "逆に考えるんだよ。\\nここで呪いが１つ増えたところで同じだって。"

# めぐみん
# とてもそんな風には思えませんよ。\nそれに、呪いの件を差し引いても\n根本的な問題が残りますよ？
157 = "とてもそんな風には思えませんよ。\\nそれに、呪いの件を差し引いても\\n根本的な問題が残りますよ？"

# めぐみん
# 指輪交換には、もう１つ必要なんですよね？
171 = "指輪交換には、もう１つ必要なんですよね？"

# カズマ
# ですよね！\nうん、俺も薄々、そう思ってた！
156 = "ですよね！\\nうん、俺も薄々、そう思ってた！"

# カズマ
# けどさ、なにもしないよりは良くないか？\nそれに、めぐみんがする必要はない。\n俺が指輪をつけるよ。
148 = "けどさ、なにもしないよりは良くないか？\\nそれに、めぐみんがする必要はない。\\n俺が指輪をつけるよ。"

# めぐみん
# え、本気ですか？
146 = "え、本気ですか？"

# カズマ
# ああ、この状況をなんとかしたい。\nそれに俺は呪われ慣れてるしな。
141 = "ああ、この状況をなんとかしたい。\\nそれに俺は呪われ慣れてるしな。"

# カズマ
# 低級な呪いらしいから\n死ぬまでのことにはならないって。
168 = "低級な呪いらしいから\\n死ぬまでのことにはならないって。"

# めぐみん
# ですが、なんの確証もないのですよ？\nもしかすると、呪い同士が反応し合って\n大変なことが起こるかもしれません。
155 = "ですが、なんの確証もないのですよ？\\nもしかすると、呪い同士が反応し合って\\n大変なことが起こるかもしれません。"

# カズマ
# お、脅かすなよ！\nでも、元はと言えば俺が悪いんだ。\nこれくらいするのは当然だろ？
147 = "お、脅かすなよ！\\nでも、元はと言えば俺が悪いんだ。\\nこれくらいするのは当然だろ？"

# カズマ
# めぐみんは俺が助けてやる。\n大船に乗ったつもりで安心しろ。
162 = "めぐみんは俺が助けてやる。\\n大船に乗ったつもりで安心しろ。"

# めぐみん
# ど、泥船の間違いでなければいいのですが。
158 = "ど、泥船の間違いでなければいいのですが。"

# カズマ
# 乗ってみればわかるさ。\nうっし、試してみようぜ。
167 = "乗ってみればわかるさ。\\nうっし、試してみようぜ。"

# めぐみん
# ……カズマ。
140 = "……カズマ。"

