# root_e06.txt.scn

[info]
0 = ""

[characters]
266 = "カズマ（Ｍ）"
264 = "カズマ"
261 = "ゆんゆん"

[character_subs]
# 264 = "カズマ"
307 = "？？？"

[script]
# lines: 70

# カズマ（Ｍ）
# display as カズマ
# （……ん？）
292 = "（……ん？）"

# カズマ（Ｍ）
# display as カズマ
# （あれ？　いつのまに俺、部屋に来たんだ？\n　えーっと、みんなでゆんゆん達の\n　釣った魚を食べて、散々騒いで……）
296 = "（あれ？　いつのまに俺、部屋に来たんだ？\\n　えーっと、みんなでゆんゆん達の\\n　釣った魚を食べて、散々騒いで……）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、そっか。\n　お腹も膨れたし、さっさと風呂に入って\n　寝ようって話になっんだっけな）
293 = "（ああ、そっか。\\n　お腹も膨れたし、さっさと風呂に入って\\n　寝ようって話になっんだっけな）"

# カズマ（Ｍ）
# display as カズマ
# （ううー、喉渇いた……。\n　居間に行けばまだ何か残ってるかな）
298 = "（ううー、喉渇いた……。\\n　居間に行けばまだ何か残ってるかな）"

# カズマ
# ええと、飲み物飲み物っと。
233 = "ええと、飲み物飲み物っと。"

# ゆんゆん
# display as ？？？
# あ、ご用意しますね。
224 = "あ、ご用意しますね。"

# カズマ
# うぎゃ！！
232 = "うぎゃ！！"

# ゆんゆん
# ど、どうかしましたか？
249 = "ど、どうかしましたか？"

# カズマ
# なんだ、ゆんゆんか。\n驚かすなよ。
251 = "なんだ、ゆんゆんか。\\n驚かすなよ。"

# カズマ
# てか、こんな所で明かりもつけないで\nどうしたんだ。
247 = "てか、こんな所で明かりもつけないで\\nどうしたんだ。"

# ゆんゆん
# なんだか眠れなくて。
252 = "なんだか眠れなくて。"

# カズマ
# あー、もしかして\n枕が変わると寝られないタイプ？
226 = "あー、もしかして\\n枕が変わると寝られないタイプ？"

# ゆんゆん
# いえ、そうじゃなくて……\n友達の家にお泊まりなんて初めてだから、\n楽しすぎて……まるで夢のようだなって。
230 = "いえ、そうじゃなくて……\\n友達の家にお泊まりなんて初めてだから、\\n楽しすぎて……まるで夢のようだなって。"

# カズマ
# そ、そうか。
239 = "そ、そうか。"

# カズマ（Ｍ）
# display as カズマ
# （うわ……。\n　なんだかこれ以上は聞いてはいけない\n　話な気がする）
299 = "（うわ……。\\n　なんだかこれ以上は聞いてはいけない\\n　話な気がする）"

# ゆんゆん
# カズマさん。\n今日は誘ってくださって、\nありがとうございます。
265 = "カズマさん。\\n今日は誘ってくださって、\\nありがとうございます。"

# カズマ
# 別に大したことじゃないって。\nそんなにお礼を言われても、困っちまうよ。
270 = "別に大したことじゃないって。\\nそんなにお礼を言われても、困っちまうよ。"

# カズマ
# むしろゆんゆんは、\nもう少し図々しくなってもいいと思うぞ？
259 = "むしろゆんゆんは、\\nもう少し図々しくなってもいいと思うぞ？"

# ゆんゆん
# 図々しくですか？
273 = "図々しくですか？"

# カズマ
# まあ、人には向き不向きがあるからな、\n無理にとは言わないけど。
257 = "まあ、人には向き不向きがあるからな、\\n無理にとは言わないけど。"

# ゆんゆん
# あ、あの……、\nそれじゃ少し図々しいことを\n言ってもいい……ですか？
221 = "あ、あの……、\\nそれじゃ少し図々しいことを\\n言ってもいい……ですか？"

# カズマ
# おう、いいぜ！\nなんだ？
237 = "おう、いいぜ！\\nなんだ？"

# ゆんゆん
# 実は折り入ってご相談が……。
276 = "実は折り入ってご相談が……。"

# カズマ（Ｍ）
# display as カズマ
# （なんだ、顔を赤らめてモジモジと……）
304 = "（なんだ、顔を赤らめてモジモジと……）"

# カズマ（Ｍ）
# display as カズマ
# （ちょ、ちょっと待て？\n　このシチュエーション、俺知ってる！\n　画面の向こうでだけど！　見たことある！）
303 = "（ちょ、ちょっと待て？\\n　このシチュエーション、俺知ってる！\\n　画面の向こうでだけど！　見たことある！）"

# カズマ（Ｍ）
# display as カズマ
# （クライマックスで呼び出されて、\n　こういう顔をした女の子に迫られて……）
306 = "（クライマックスで呼び出されて、\\n　こういう顔をした女の子に迫られて……）"

# カズマ（Ｍ）
# display as カズマ
# （あなたが、好きです）
295 = "（あなたが、好きです）"

# カズマ（Ｍ）
# display as カズマ
# （そう！　そうだ！\n　これは愛の告白のシーンだぁぁぁぁ！）
301 = "（そう！　そうだ！\\n　これは愛の告白のシーンだぁぁぁぁ！）"

# カズマ（Ｍ）
# display as カズマ
# （んー、落ち着け俺ー？\n　ここで焦ってはダメだぞー？\n　相手のペースにあわせてあげるのが紳士だぞー？）
305 = "（んー、落ち着け俺ー？\\n　ここで焦ってはダメだぞー？\\n　相手のペースにあわせてあげるのが紳士だぞー？）"

# ゆんゆん
# わ、私……本気なんです！
262 = "わ、私……本気なんです！"

# カズマ（Ｍ）
# display as カズマ
# （ああ、なんて真剣な目なんだ！\n　これはもしかして本当に……）
294 = "（ああ、なんて真剣な目なんだ！\\n　これはもしかして本当に……）"

# カズマ（Ｍ）
# display as カズマ
# （だとしたらどうする？\n　なんて答えたらいい！？）
302 = "（だとしたらどうする？\\n　なんて答えたらいい！？）"

# ゆんゆん
# だ、だから！\nしばらく、ここに住まわせてくれませんか？
245 = "だ、だから！\\nしばらく、ここに住まわせてくれませんか？"

# カズマ
# ……え？\nここに住むって……\nまさかそれって逆プロポーズ！？
218 = "……え？\\nここに住むって……\\nまさかそれって逆プロポーズ！？"

# ゆんゆん
# え？　逆プロポーズ？
235 = "え？　逆プロポーズ？"

# カズマ
# え？　違うの？
236 = "え？　違うの？"

# ゆんゆん
# ……違いますけど。
220 = "……違いますけど。"

# カズマ
# …………。
217 = "…………。"

# ゆんゆん
# …………。
# 217 = "…………。"

# カズマ
# …………。
# 217 = "…………。"

# カズマ
# い、いや、なんでもない！\nいまのは聞かなかったことにして！
227 = "い、いや、なんでもない！\\nいまのは聞かなかったことにして！"

# ゆんゆん
# は、はいっ！
253 = "は、はいっ！"

# カズマ
# と、とにかく、話を戻すと、\nゆんゆんはここに住みたいのか？
248 = "と、とにかく、話を戻すと、\\nゆんゆんはここに住みたいのか？"

# ゆんゆん
# はい。\n少しの間だけでも\n１つ屋根の下に暮らすことで――
255 = "はい。\\n少しの間だけでも\\n１つ屋根の下に暮らすことで――"

# ゆんゆん
# めぐみんをもっとよく\n理解できるんじゃないかって思うんです。
260 = "めぐみんをもっとよく\\n理解できるんじゃないかって思うんです。"

# ゆんゆん
# そうすれば……勝つためのヒントも\n見つけられるんじゃないかって……。
241 = "そうすれば……勝つためのヒントも\\n見つけられるんじゃないかって……。"

# カズマ（Ｍ）
# display as カズマ
# （あー、そういうこと……、\n　ですよね、そうですよね。\n　俺の勘違いですよね！！）
297 = "（あー、そういうこと……、\\n　ですよね、そうですよね。\\n　俺の勘違いですよね！！）"

# ゆんゆん
# あの、勝手なお願いだとは思いますが……\nどうでしょうか？
225 = "あの、勝手なお願いだとは思いますが……\\nどうでしょうか？"

# カズマ
# 好きにすればいい。
275 = "好きにすればいい。"

# ゆんゆん
# えっ！？\nそんなにあっさり、いいんですか？
234 = "えっ！？\\nそんなにあっさり、いいんですか？"

# カズマ
# まあ、部屋なら余ってるし\n１人くらい増えても俺は問題ないぜ。
258 = "まあ、部屋なら余ってるし\\n１人くらい増えても俺は問題ないぜ。"

# ゆんゆん
# あ、ありがとうございます！
223 = "あ、ありがとうございます！"

# カズマ
# だから礼なんかいいって。\n図々しいことを言った方がいいって\n勧めたのは俺だしさ。
246 = "だから礼なんかいいって。\\n図々しいことを言った方がいいって\\n勧めたのは俺だしさ。"

# ゆんゆん
# それでも、ありがとうございます。\nとっても嬉しいです。
242 = "それでも、ありがとうございます。\\nとっても嬉しいです。"

# カズマ
# 他のみんながいいって言うならＯＫ。
269 = "他のみんながいいって言うならＯＫ。"

# ゆんゆん
# ほ、本当ですか？
256 = "ほ、本当ですか？"

# カズマ
# 反対する理由もないしな。\nそれに、やりたいことがあるなら\n協力してあげたいし。
271 = "反対する理由もないしな。\\nそれに、やりたいことがあるなら\\n協力してあげたいし。"

# ゆんゆん
# あ、ありがとうございますっ！
222 = "あ、ありがとうございますっ！"

# カズマ
# いえいえ、どういたしまして。
231 = "いえいえ、どういたしまして。"

# カズマ
# いいぜ！　がんばれよ！
229 = "いいぜ！　がんばれよ！"

# ゆんゆん
# は、はい！\nありがとうございます！
254 = "は、はい！\\nありがとうございます！"

# カズマ
# お礼なんていいって。\n努力しようとしてる人間を応援するのは\n当たり前だろ？
238 = "お礼なんていいって。\\n努力しようとしてる人間を応援するのは\\n当たり前だろ？"

# ゆんゆん
# ……優しいんですね、カズマさん。
219 = "……優しいんですね、カズマさん。"

# カズマ
# そんなことないって、普通だよ普通。
243 = "そんなことないって、普通だよ普通。"

# ゆんゆん
# いいえ……。\nそんな風に言える事自体が素敵だと思います。
228 = "いいえ……。\\nそんな風に言える事自体が素敵だと思います。"

# カズマ
# そ、そうか？\nえーっと……ありがとう。
240 = "そ、そうか？\\nえーっと……ありがとう。"

# ゆんゆん
# どういたしまして。
250 = "どういたしまして。"

# カズマ
# ただ問題は、めぐみんがなんて言うかだなぁ。\n絶対に反対するだろ。
244 = "ただ問題は、めぐみんがなんて言うかだなぁ。\\n絶対に反対するだろ。"

# ゆんゆん
# わ、私が説得してみせます！\n任せてくださいっ！
263 = "わ、私が説得してみせます！\\n任せてくださいっ！"

# カズマ（Ｍ）
# display as カズマ
# （うーん、これほど当てにならない\n　任せてくださいもないな……。\n　大丈夫なんだろうか？）
300 = "（うーん、これほど当てにならない\\n　任せてくださいもないな……。\\n　大丈夫なんだろうか？）"

[selections]
274 = "好きにすればいい"
268 = "他のみんながいいって言うならＯＫ"
# 229 = "いいぜ！　がんばれよ！"
