# root_f19.txt.scn

[info]
0 = ""

[characters]
270 = "カズマ（Ｍ）"
268 = "カズマ"
267 = "ウィズ"

[character_subs]
# 268 = "カズマ"

[script]
# lines: 76

# カズマ（Ｍ）
# display as カズマ
# （さすがにこの辺りは、\n　夜になると人気が全く無いな）
302 = "（さすがにこの辺りは、\\n　夜になると人気が全く無いな）"

# カズマ
# どうだ？\nこのあたりにも除霊された形跡があるのか？
254 = "どうだ？\\nこのあたりにも除霊された形跡があるのか？"

# ウィズ
# いえ、どうやらまだみたいです。\nけっこういっぱいいますね。
229 = "いえ、どうやらまだみたいです。\\nけっこういっぱいいますね。"

# カズマ
# マジかよ！\nだったら、ちゃっちゃと除霊しちまおうぜ。
271 = "マジかよ！\\nだったら、ちゃっちゃと除霊しちまおうぜ。"

# ウィズ
# いえ、少し待ってもらえますか？
230 = "いえ、少し待ってもらえますか？"

# カズマ
# って、ウィズ！？\nな、な、なんだよ、その光！？
251 = "って、ウィズ！？\\nな、な、なんだよ、その光！？"

# カズマ（Ｍ）
# display as カズマ
# （ウィズの周りに、\n　うっすらと光る物がふわふわと漂ってる……）
312 = "（ウィズの周りに、\\n　うっすらと光る物がふわふわと漂ってる……）"

# ウィズ
# 大丈夫ですよ。\n申し訳ないのですが、\n少し静かにしてもらえますか？
275 = "大丈夫ですよ。\\n申し訳ないのですが、\\n少し静かにしてもらえますか？"

# カズマ
# あ、ああ。
224 = "あ、ああ。"

# カズマ（Ｍ）
# display as カズマ
# （よく見ると、１つや２つじゃない。\n　ホタルみたいに、ゆっくり明滅しながら\n　漂って……）
310 = "（よく見ると、１つや２つじゃない。\\n　ホタルみたいに、ゆっくり明滅しながら\\n　漂って……）"

# カズマ（Ｍ）
# display as カズマ
# （も、もしかしてアレか？\n　人魂ってやつなのか！？）
309 = "（も、もしかしてアレか？\\n　人魂ってやつなのか！？）"

# カズマ（Ｍ）
# display as カズマ
# （でも、ウィズはずいぶんと優しい表情だ。\n　なんていうか、それこそ女神というか……）
304 = "（でも、ウィズはずいぶんと優しい表情だ。\\n　なんていうか、それこそ女神というか……）"

# ウィズ
# …………。
222 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （まるで……聖母だな。\n　昼間の、子供に懐かれてる時と同じ顔だ）
308 = "（まるで……聖母だな。\\n　昼間の、子供に懐かれてる時と同じ顔だ）"

# ウィズ
# ふぅん、そうなのね。
258 = "ふぅん、そうなのね。"

# カズマ（Ｍ）
# display as カズマ
# （な、何か話してるぞ！？\n　話が通じるのか？）
305 = "（な、何か話してるぞ！？\\n　話が通じるのか？）"

# ウィズ
# ここでみんなと遊んでたのね。\nふふ、楽しい？
238 = "ここでみんなと遊んでたのね。\\nふふ、楽しい？"

# ウィズ
# ……そう。\n鬼ごっこやかくれんぼをしてたの。
223 = "……そう。\\n鬼ごっこやかくれんぼをしてたの。"

# カズマ（Ｍ）
# display as カズマ
# （ウィズの受け答えからすると、\n　もしかして、これ、子供の霊なのか？）
311 = "（ウィズの受け答えからすると、\\n　もしかして、これ、子供の霊なのか？）"

# ウィズ
# え？　私も混ぜてくれるの？\nじゃあ、お姉ちゃんと一緒に遊びましょうか。
235 = "え？　私も混ぜてくれるの？\\nじゃあ、お姉ちゃんと一緒に遊びましょうか。"

# ウィズ
# あんまり騒げないけれど、踊りましょう。
228 = "あんまり騒げないけれど、踊りましょう。"

# ウィズ
# ほら、そっちの子も。\n恥ずかしがってないで、おいで。
261 = "ほら、そっちの子も。\\n恥ずかしがってないで、おいで。"

# カズマ（Ｍ）
# display as カズマ
# （こ、これは……すごい。\n　ウィズを中心に光が舞い踊ってる……）
301 = "（こ、これは……すごい。\\n　ウィズを中心に光が舞い踊ってる……）"

# カズマ（Ｍ）
# display as カズマ
# （けど、なんて言うのかな。\n　保母さんに群がる幼稚園児、みたいな感じもする）
300 = "（けど、なんて言うのかな。\\n　保母さんに群がる幼稚園児、みたいな感じもする）"

# カズマ（Ｍ）
# display as カズマ
# （感じ、じゃなくて、多分そうなんだろう。\n　この光１つ１つが子供達の魂なんだ）
316 = "（感じ、じゃなくて、多分そうなんだろう。\\n　この光１つ１つが子供達の魂なんだ）"

# カズマ
# よし、俺も一緒に遊ぶぞ！
263 = "よし、俺も一緒に遊ぶぞ！"

# ウィズ
# ええ、どうぞ。\nでもあまり、この子達を\n驚かさないであげてくださいね。
233 = "ええ、どうぞ。\\nでもあまり、この子達を\\n驚かさないであげてくださいね。"

# カズマ
# わ、わかった。\nええと……おっ？
264 = "わ、わかった。\\nええと……おっ？"

# カズマ（Ｍ）
# display as カズマ
# （俺の方に、光がひとつ寄ってきた？）
314 = "（俺の方に、光がひとつ寄ってきた？）"

# ウィズ
# その子、カズマさんに興味があるみたいですよ？
246 = "その子、カズマさんに興味があるみたいですよ？"

# カズマ
# ほほう、見どころのあるやつだ。\nよし、遊ぶぞ！
260 = "ほほう、見どころのあるやつだ。\\nよし、遊ぶぞ！"

# カズマ（Ｍ）
# display as カズマ
# （光の玉が俺にまとわりついてくる。\n　……なんだか不思議な感じだな）
315 = "（光の玉が俺にまとわりついてくる。\\n　……なんだか不思議な感じだな）"

# ウィズ
# あまり激しく動かないでくださいね。\nその子達の存在が、かき消されかねませんから。
227 = "あまり激しく動かないでくださいね。\\nその子達の存在が、かき消されかねませんから。"

# カズマ
# おう。\nじゃあ、ゆっくり……。
237 = "おう。\\nじゃあ、ゆっくり……。"

# カズマ（Ｍ）
# display as カズマ
# （俺の動かす手をくっつくかのように追ってくる。\n　もしかしたら寂しかったのかもな……）
313 = "（俺の動かす手をくっつくかのように追ってくる。\\n　もしかしたら寂しかったのかもな……）"

# ウィズ
# ふふ、気に入られたみたいですね。
259 = "ふふ、気に入られたみたいですね。"

# カズマ
# そうなのか？\nでもこうしてると、けっこう楽しいな。
244 = "そうなのか？\\nでもこうしてると、けっこう楽しいな。"

# ウィズ
# はい。\nこの子たち、ちっとも恐くないでしょう？
256 = "はい。\\nこの子たち、ちっとも恐くないでしょう？"

# カズマ
# ああ。
225 = "ああ。"

# カズマ
# これに聖水を掛けたらどうなるんだ？
240 = "これに聖水を掛けたらどうなるんだ？"

# ウィズ
# ええっ！？\nな、なんてことを考えてるんですか！
234 = "ええっ！？\\nな、なんてことを考えてるんですか！"

# カズマ
# うおっ！？\nびっくりした、そんな怒ることか？
232 = "うおっ！？\\nびっくりした、そんな怒ることか？"

# ウィズ
# 当たり前です！\nこの子達の嫌がることをしようとするなんて！
278 = "当たり前です！\\nこの子達の嫌がることをしようとするなんて！"

# カズマ（Ｍ）
# display as カズマ
# （あ、光が俺から離れて\n　ウィズの後ろに隠れちまった）
298 = "（あ、光が俺から離れて\\n　ウィズの後ろに隠れちまった）"

# ウィズ
# この子たち、カズマさんのことを\n悪い人だって思っちゃいましたよ？
239 = "この子たち、カズマさんのことを\\n悪い人だって思っちゃいましたよ？"

# ウィズ
# やっぱり、変態でヒキニートで\n女の子の敵の、どうしようも無い人だって。
262 = "やっぱり、変態でヒキニートで\\n女の子の敵の、どうしようも無い人だって。"

# カズマ
# おい、待て！？\nなんでそんなうちの連中みたいなことを\n言うんだよ！
236 = "おい、待て！？\\nなんでそんなうちの連中みたいなことを\\n言うんだよ！"

# ウィズ
# その光景を見たことがあるそうです。\n霊なんですから、どこにいても\nおかしくないんですよ。
245 = "その光景を見たことがあるそうです。\\n霊なんですから、どこにいても\\nおかしくないんですよ。"

# カズマ（Ｍ）
# display as カズマ
# （なんてこった！\n　俺の生活、まるっと幽霊に見られてたのかよ！）
306 = "（なんてこった！\\n　俺の生活、まるっと幽霊に見られてたのかよ！）"

# ウィズ
# カズマさん。\nこの子達に、ちゃんと謝って下さい。
269 = "カズマさん。\\nこの子達に、ちゃんと謝って下さい。"

# カズマ
# わ、わかった！\nごめん！　俺が悪かった！　このとおりだ！
265 = "わ、わかった！\\nごめん！　俺が悪かった！　このとおりだ！"

# カズマ
# 取り憑かれたりしないのか？
273 = "取り憑かれたりしないのか？"

# ウィズ
# そんな心配は無用ですよ。\n相手は子どもですから。
249 = "そんな心配は無用ですよ。\\n相手は子どもですから。"

# カズマ
# ん？\nそれはつまり、取り憑こうと思えば\n出来るってことなのか？
266 = "ん？\\nそれはつまり、取り憑こうと思えば\\n出来るってことなのか？"

# ウィズ
# 小さくても霊ですからね。\nただ、思念や力はやっぱり子どもで弱いですから。\nひどい事にはなりません。
276 = "小さくても霊ですからね。\\nただ、思念や力はやっぱり子どもで弱いですから。\\nひどい事にはなりません。"

# ウィズ
# でも、死んだ時の状況にもよります。\n怨念や未練を持った子はちょっと危ないです。
252 = "でも、死んだ時の状況にもよります。\\n怨念や未練を持った子はちょっと危ないです。"

# ウィズ
# そういう子は、半分くらい\n悪霊とか怨霊みたいな感じになってますから。
242 = "そういう子は、半分くらい\\n悪霊とか怨霊みたいな感じになってますから。"

# カズマ（Ｍ）
# display as カズマ
# （それは怖いな……）
303 = "（それは怖いな……）"

# カズマ
# 霊が空に昇っていってる……。
296 = "霊が空に昇っていってる……。"

# ウィズ
# はい。\nまさしく昇天……\n魂が天に還っていくんです。
257 = "はい。\\nまさしく昇天……\\n魂が天に還っていくんです。"

# カズマ
# でも、特に\n浄化の儀式とかやってなかったよな？
253 = "でも、特に\\n浄化の儀式とかやってなかったよな？"

# ウィズ
# いえいえ、さっきの踊りが\nまさにそれなんですよ？
231 = "いえいえ、さっきの踊りが\\nまさにそれなんですよ？"

# ウィズ
# あの子たちは悪霊ではありませんから、\n無理に除霊や浄化をする必要はないんです。
226 = "あの子たちは悪霊ではありませんから、\\n無理に除霊や浄化をする必要はないんです。"

# ウィズ
# ただ、この世に少しだけ心残りがあるから\n留まっているだけ……。
250 = "ただ、この世に少しだけ心残りがあるから\\n留まっているだけ……。"

# ウィズ
# その心残りを解消してあげれば、\n霊は自然と天に還っていくんです。
247 = "その心残りを解消してあげれば、\\n霊は自然と天に還っていくんです。"

# カズマ
# そうなのか。\nてっきり俺は、もっと容赦なく\n送り返すもんだとばかり思ってたぜ。
243 = "そうなのか。\\nてっきり俺は、もっと容赦なく\\n送り返すもんだとばかり思ってたぜ。"

# ウィズ
# 普通の霊なら、あれで十分なんです。\n浄化はともかく除霊は\n霊の存在を消してしまいますから。
280 = "普通の霊なら、あれで十分なんです。\\n浄化はともかく除霊は\\n霊の存在を消してしまいますから。"

# カズマ（Ｍ）
# display as カズマ
# （ふーん、なるほどなぁ）
307 = "（ふーん、なるほどなぁ）"

# ウィズ
# それよりも、あの子たちが\nちょっと気になることを言っていて……。
248 = "それよりも、あの子たちが\\nちょっと気になることを言っていて……。"

# カズマ
# 気になること？　なんだ？
281 = "気になること？　なんだ？"

# ウィズ
# 昨日の夜、\n吸い寄せられるような力を感じた、と。
279 = "昨日の夜、\\n吸い寄せられるような力を感じた、と。"

# カズマ
# はあ？　なんだそりゃ？
255 = "はあ？　なんだそりゃ？"

# ウィズ
# 私にもよくわかりませんが……\nこの騒ぎに関係あることなのかもしれません。
295 = "私にもよくわかりませんが……\\nこの騒ぎに関係あることなのかもしれません。"

# カズマ（Ｍ）
# display as カズマ
# （うーん、確かに。\n　ちょっと心に留めておくか）
299 = "（うーん、確かに。\\n　ちょっと心に留めておくか）"

# ウィズ
# さて、ここの霊は\n全て天に還しましたから……\n次に向かいましょう。
241 = "さて、ここの霊は\\n全て天に還しましたから……\\n次に向かいましょう。"

# カズマ（Ｍ）
# display as カズマ
# （……ウィズの顔色が悪いような\n　気がするが……どうしたんだろう？）
297 = "（……ウィズの顔色が悪いような\\n　気がするが……どうしたんだろう？）"

[selections]
# 263 = "よし、俺も一緒に遊ぶぞ！"
# 240 = "これに聖水を掛けたらどうなるんだ？"
# 273 = "取り憑かれたりしないのか？"
