# root_a12.txt.scn

[info]
0 = ""

[characters]
191 = "カズマ（Ｍ）"
190 = "カズマ"
189 = "アクア"

[character_subs]
# 190 = "カズマ"

[script]
# lines: 43

# カズマ（Ｍ）
# display as カズマ
# （そして、さっそくアクアの特訓が始まった――）
232 = "（そして、さっそくアクアの特訓が始まった――）"

# カズマ
# よーし！\nそれじゃ早速、始めるぞ。
188 = "よーし！\\nそれじゃ早速、始めるぞ。"

# アクア
# はい、よろしくお願いします！\nって、ダクネスとめぐみんはどうしたの？
182 = "はい、よろしくお願いします！\\nって、ダクネスとめぐみんはどうしたの？"

# カズマ
# めぐみんは、ちょっと頼みごとがあって\n走って貰ってる。
186 = "めぐみんは、ちょっと頼みごとがあって\\n走って貰ってる。"

# アクア
# 頼み事？
229 = "頼み事？"

# カズマ
# 俺の私用だよ。
196 = "俺の私用だよ。"

# カズマ
# ダクネスは、なんか用事があるとかで\n実家に戻った。
193 = "ダクネスは、なんか用事があるとかで\\n実家に戻った。"

# アクア
# ふーん、実家に……何かしらね？
183 = "ふーん、実家に……何かしらね？"

# カズマ
# さあ、それは俺にも。
175 = "さあ、それは俺にも。"

# アクア
# まあ、いいわ。\nそれで何かするの？
185 = "まあ、いいわ。\\nそれで何かするの？"

# カズマ
# 俺がエリス様について知ってることなんて\n限られてるからな。
195 = "俺がエリス様について知ってることなんて\\n限られてるからな。"

# アクア
# ちょっと頼りないわね。\nしっかりしてよ。
179 = "ちょっと頼りないわね。\\nしっかりしてよ。"

# カズマ
# いやいや、お前も何か考えろよ。
171 = "いやいや、お前も何か考えろよ。"

# アクア
# うーんじゃあ……。\nそうだ！　胸にサラシを巻くというのは\nどうかしら！
173 = "うーんじゃあ……。\\nそうだ！　胸にサラシを巻くというのは\\nどうかしら！"

# カズマ
# 真面目に考えろ。
225 = "真面目に考えろ。"

# アクア
# 失礼ね。\n私は真面目も真面目、大真面目よ！
198 = "失礼ね。\\n私は真面目も真面目、大真面目よ！"

# カズマ
# へー。
184 = "へー。"

# アクア
# 確かに意味がないと思われても仕方ないわ。
226 = "確かに意味がないと思われても仕方ないわ。"

# アクア
# でもね、サラシを巻いてパットを着けるところから\n始めればエリスの気持ちに近づけると思うのよ。
181 = "でもね、サラシを巻いてパットを着けるところから\\n始めればエリスの気持ちに近づけると思うのよ。"

# アクア
# あの子がどういう気持ちで過ごしてるのか、\nそういうのって動きにも出ると思うのよね。
170 = "あの子がどういう気持ちで過ごしてるのか、\\nそういうのって動きにも出ると思うのよね。"

# カズマ（Ｍ）
# display as カズマ
# （説得力があるような無いような……）
238 = "（説得力があるような無いような……）"

# アクア
# でも、カズマの前でそれはできないわよね。
180 = "でも、カズマの前でそれはできないわよね。"

# カズマ
# 当たり前だ。
200 = "当たり前だ。"

# アクア
# じゃあカズマ、\nエリスの特徴を挙げてみてくれる？
176 = "じゃあカズマ、\\nエリスの特徴を挙げてみてくれる？"

# カズマ（Ｍ）
# display as カズマ
# （エリス様の？\n　うーん、そうだな……）
234 = "（エリス様の？\\n　うーん、そうだな……）"

# カズマ
# 美人で、清楚で、俺のことを\n真剣に心配してくれる優しさがあるよな。
228 = "美人で、清楚で、俺のことを\\n真剣に心配してくれる優しさがあるよな。"

# カズマ
# 気配り上手、それでいてお茶目なところもある。\nうむ、一言で言うならまさにメインヒロインだ！
201 = "気配り上手、それでいてお茶目なところもある。\\nうむ、一言で言うならまさにメインヒロインだ！"

# アクア
# そう……。\nうーん、困ったわね。
177 = "そう……。\\nうーん、困ったわね。"

# カズマ（Ｍ）
# display as カズマ
# （おっと？\n　珍しく謙虚に自分とエリス様の違いを\n　認めるのか？）
230 = "（おっと？\\n　珍しく謙虚に自分とエリス様の違いを\\n　認めるのか？）"

# アクア
# 私に全部当てはまることじゃない。
227 = "私に全部当てはまることじゃない。"

# カズマ
# うん、どうしよう。
172 = "うん、どうしよう。"

# アクア
# 何が？
194 = "何が？"

# カズマ（Ｍ）
# display as カズマ
# （美人はまあ、うん、認めたくはないが、\n　間違えていないだろう）
237 = "（美人はまあ、うん、認めたくはないが、\\n　間違えていないだろう）"

# カズマ（Ｍ）
# display as カズマ
# （俺を心配してくれるって点も、\n　たまにそういう一面を見せてくれてる）
236 = "（俺を心配してくれるって点も、\\n　たまにそういう一面を見せてくれてる）"

# カズマ（Ｍ）
# display as カズマ
# （しかし問題は、清楚だ！）
231 = "（しかし問題は、清楚だ！）"

# カズマ（Ｍ）
# display as カズマ
# （シュワシュワを浴びるまで飲んで\n　道端で吐くやつが清楚と言えるか？）
235 = "（シュワシュワを浴びるまで飲んで\\n　道端で吐くやつが清楚と言えるか？）"

# カズマ（Ｍ）
# display as カズマ
# （隣で男が寝てるのに、腹を出して寝るやつが\n　清楚と言えるか？）
239 = "（隣で男が寝てるのに、腹を出して寝るやつが\\n　清楚と言えるか？）"

# カズマ（Ｍ）
# display as カズマ
# （そして、そんなやつをどうすれば矯正できる！）
233 = "（そして、そんなやつをどうすれば矯正できる！）"

# アクア
# ちょっとなんで黙っちゃうのよ。
178 = "ちょっとなんで黙っちゃうのよ。"

# カズマ
# ギブアップ！
192 = "ギブアップ！"

# アクア
# え？　え？
174 = "え？　え？"

# カズマ
# ギブアップ！
# 192 = "ギブアップ！"

# アクア
# もう、だからそれなんなのよ！
187 = "もう、だからそれなんなのよ！"

