# root_d20.txt.scn

[info]
0 = ""

[characters]
139 = "カズマ（Ｍ）"
140 = "クリス"
138 = "カズマ"
164 = "魔術師風の男冒険者"
148 = "盗賊風の男冒険者"
146 = "戦士風の男冒険者"

[character_subs]
# 138 = "カズマ"
163 = "魔術師冒険者"
147 = "盗賊冒険者"
145 = "戦士冒険者"

[script]
# lines: 21

# カズマ（Ｍ）
# display as カズマ
# （遠くから人の歩く音は聞こえるけど、\n　こっちに来る様子はないな。\n　まだ俺達には気付いてないのか）
169 = "（遠くから人の歩く音は聞こえるけど、\\n　こっちに来る様子はないな。\\n　まだ俺達には気付いてないのか）"

# クリス
# かなり日が傾いてきたね。
129 = "かなり日が傾いてきたね。"

# カズマ
# 外には誰かいるか？\n窓から確認してくれ。
143 = "外には誰かいるか？\\n窓から確認してくれ。"

# クリス
# 見える範囲にはいない。\n潜伏を使われていたらわからないけど。\n念のため、敵感知、使っておく？
162 = "見える範囲にはいない。\\n潜伏を使われていたらわからないけど。\\n念のため、敵感知、使っておく？"

# カズマ
# いや、いいや。\n俺達がここにいるって確信もないのに\nそこまでしないだろ。
126 = "いや、いいや。\\n俺達がここにいるって確信もないのに\\nそこまでしないだろ。"

# カズマ
# それにもう時間も無いんだ。\nそんなまどろっこしいことをしてる余裕は\n向こうにないだろうしな。
133 = "それにもう時間も無いんだ。\\nそんなまどろっこしいことをしてる余裕は\\n向こうにないだろうしな。"

# クリス
# そういうもの？
132 = "そういうもの？"

# カズマ
# ああ。\n俺ならいるかどうかわからない相手を\n待ち構えるより、自分でそいつを捕まえに行く。
124 = "ああ。\\n俺ならいるかどうかわからない相手を\\n待ち構えるより、自分でそいつを捕まえに行く。"

# カズマ
# だいたい、タイムリミットが迫ってるのに\nそんな成功するかどうかわからない\n賭けみたいなことする奴なんていないだろ。
134 = "だいたい、タイムリミットが迫ってるのに\\nそんな成功するかどうかわからない\\n賭けみたいなことする奴なんていないだろ。"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# おい、いたか？
128 = "おい、いたか？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# いや、いないな。
127 = "いや、いないな。"

# 戦士風の男冒険者
# display as 戦士冒険者
# しらみつぶしに探せ！
131 = "しらみつぶしに探せ！"

# クリス
# どうやら本格的に家探しを始めたみたいだね。\nここは教会だっていうのに……不謹慎だなぁ。\nバチが当たっても知らないんだから。
137 = "どうやら本格的に家探しを始めたみたいだね。\\nここは教会だっていうのに……不謹慎だなぁ。\\nバチが当たっても知らないんだから。"

# カズマ（Ｍ）
# display as カズマ
# （かなり足音が近づいて来てるな。\n　このままじゃ、この部屋にやってくるのも\n　時間の問題か）
165 = "（かなり足音が近づいて来てるな。\\n　このままじゃ、この部屋にやってくるのも\\n　時間の問題か）"

# カズマ（Ｍ）
# display as カズマ
# （けど、今、廊下に出たら\n　捕まえてくださいって言ってるようなもんだ）
166 = "（けど、今、廊下に出たら\\n　捕まえてくださいって言ってるようなもんだ）"

# カズマ（Ｍ）
# display as カズマ
# （とすると、残るは窓しか逃げ道がないんだが）
167 = "（とすると、残るは窓しか逃げ道がないんだが）"

# カズマ（Ｍ）
# display as カズマ
# （クリスは外に見張りがいないって言ってたし、\n　それなら行けるか？）
168 = "（クリスは外に見張りがいないって言ってたし、\\n　それなら行けるか？）"

# クリス
# で、これからどうする？
136 = "で、これからどうする？"

# カズマ
# このままここにいたら見つかっちまう。\nだから、今のうちに窓から逃げようと\n思うんだけど、いけるか？
130 = "このままここにいたら見つかっちまう。\\nだから、今のうちに窓から逃げようと\\n思うんだけど、いけるか？"

# クリス
# あたしは問題ないよ。\n見たところ、窓の外は１階部分の屋根に\nなってるみたいだから、逃げやすいんじゃない？
125 = "あたしは問題ないよ。\\n見たところ、窓の外は１階部分の屋根に\\nなってるみたいだから、逃げやすいんじゃない？"

# カズマ
# だよな、俺もそう思ってたんだ。\nよし、そうと決まれば見つからないうちに\nさっさと行くか。
135 = "だよな、俺もそう思ってたんだ。\\nよし、そうと決まれば見つからないうちに\\nさっさと行くか。"

