# root_c14.txt.scn

[info]
0 = ""

[characters]
149 = "カズマ（Ｍ）"
144 = "アクア"
140 = "めぐみん"
150 = "ダクネス"
146 = "カズマ"

[character_subs]
# 146 = "カズマ"

[script]
# lines: 42

# カズマ（Ｍ）
# display as カズマ
# （ダクネスとの初デートに\n　胸をときめかせて街まで来たわけだが――）
171 = "（ダクネスとの初デートに\\n　胸をときめかせて街まで来たわけだが――）"

# カズマ（Ｍ）
# display as カズマ
# （さっきから、その気分に水を差す者が\n　視界にちらちら映り込んでいる）
165 = "（さっきから、その気分に水を差す者が\\n　視界にちらちら映り込んでいる）"

# アクア
# こそこそ、こそこそ……。
133 = "こそこそ、こそこそ……。"

# めぐみん
# こそこそ、こそこそ……。
# 133 = "こそこそ、こそこそ……。"

# カズマ（Ｍ）
# display as カズマ
# （俺達を尾行してるつもりか？\n　バレバレだぞ？）
175 = "（俺達を尾行してるつもりか？\\n　バレバレだぞ？）"

# ダクネス
# ん？\nどうかしたのか、カズマ？
142 = "ん？\\nどうかしたのか、カズマ？"

# カズマ
# ああ、なんでもない。
128 = "ああ、なんでもない。"

# カズマ（Ｍ）
# display as カズマ
# （フッ！　俺も罪な男だ。\n　きっとあいつらは、俺達が\n　ラブラブデートをしているのが悔しいんだな）
174 = "（フッ！　俺も罪な男だ。\\n　きっとあいつらは、俺達が\\n　ラブラブデートをしているのが悔しいんだな）"

# カズマ（Ｍ）
# display as カズマ
# （だったら、イチャラブなところを見せつけて\n　更に悔しがらせてやろうじゃないか！）
169 = "（だったら、イチャラブなところを見せつけて\\n　更に悔しがらせてやろうじゃないか！）"

# ダクネス
# カズマ、どこか行ってみたい場所や\nしたいことはあるか？
147 = "カズマ、どこか行ってみたい場所や\\nしたいことはあるか？"

# カズマ
# ん？　そうだなぁ……。
143 = "ん？　そうだなぁ……。"

# カズマ（Ｍ）
# display as カズマ
# （デートの基本といったら\n　映画や遊園地が鉄板なんだが、\n　この世界にはない）
173 = "（デートの基本といったら\\n　映画や遊園地が鉄板なんだが、\\n　この世界にはない）"

# カズマ（Ｍ）
# display as カズマ
# （それに、カラオケもゲーセンもないし、\n　できることと言えば、ショッピングか\n　どこかでお茶することぐらいか？）
168 = "（それに、カラオケもゲーセンもないし、\\n　できることと言えば、ショッピングか\\n　どこかでお茶することぐらいか？）"

# カズマ（Ｍ）
# display as カズマ
# （デートなんてゲームの中でしか\n　したことないし、他に何をすればいいか\n　全然わからん……）
172 = "（デートなんてゲームの中でしか\\n　したことないし、他に何をすればいいか\\n　全然わからん……）"

# カズマ（Ｍ）
# display as カズマ
# （そもそも、この世界だと選択肢が狭すぎだ！）
167 = "（そもそも、この世界だと選択肢が狭すぎだ！）"

# ダクネス
# だ、大丈夫か？\nそんなに悩ませてしまったか？
135 = "だ、大丈夫か？\\nそんなに悩ませてしまったか？"

# カズマ
# えっ？\nあ、いや、その……。
132 = "えっ？\\nあ、いや、その……。"

# カズマ（Ｍ）
# display as カズマ
# （あれ？\n　なんで悲しそうな顔してんだよ、ダクネス？）
161 = "（あれ？\\n　なんで悲しそうな顔してんだよ、ダクネス？）"

# カズマ（Ｍ）
# display as カズマ
# （まさか、デートすら\n　軽くこなせない男に幻滅してるのか？）
170 = "（まさか、デートすら\\n　軽くこなせない男に幻滅してるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （優柔不断で、今流行のお洒落スポット１つ\n　知らない田舎者だと思ってる？）
176 = "（優柔不断で、今流行のお洒落スポット１つ\\n　知らない田舎者だと思ってる？）"

# カズマ（Ｍ）
# display as カズマ
# （こっ、このままじゃ、\n　俺のモテ期があっけなく終わっちまうぞ！？）
162 = "（こっ、このままじゃ、\\n　俺のモテ期があっけなく終わっちまうぞ！？）"

# カズマ
# ちょっ、ちょっと待ってくれ！
137 = "ちょっ、ちょっと待ってくれ！"

# ダクネス
# ああ、わかった……。
129 = "ああ、わかった……。"

# カズマ（Ｍ）
# display as カズマ
# （女の子を不安にさせてどうする！\n　ここはスマートかつ、チープでもゴージャスな\n　デートをプロデュースしなきゃ男がすたる！）
177 = "（女の子を不安にさせてどうする！\\n　ここはスマートかつ、チープでもゴージャスな\\n　デートをプロデュースしなきゃ男がすたる！）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、情報が足りねぇ。\n　くそ、こんな時のために前もってしっかり\n　リサーチをしておけばよかったぜ）
166 = "（しかし、情報が足りねぇ。\\n　くそ、こんな時のために前もってしっかり\\n　リサーチをしておけばよかったぜ）"

# カズマ（Ｍ）
# display as カズマ
# （このままじゃ、ウィズの店で\n　ウィンドショッピングをして、\n　いつもの酒場でディナー、なんてことに……）
163 = "（このままじゃ、ウィズの店で\\n　ウィンドショッピングをして、\\n　いつもの酒場でディナー、なんてことに……）"

# ダクネス
# カズマ。
148 = "カズマ。"

# カズマ
# は、はいカズマですが！？
138 = "は、はいカズマですが！？"

# ダクネス
# 何を焦っているんだ？
152 = "何を焦っているんだ？"

# カズマ
# い、いや、待ってくれ。\n今、小洒落たスポットを探しているところで――
131 = "い、いや、待ってくれ。\\n今、小洒落たスポットを探しているところで――"

# ダクネス
# 別に慌てて探す必要はない。\n私は、カズマとただ話すだけでも構わないのだ。
153 = "別に慌てて探す必要はない。\\n私は、カズマとただ話すだけでも構わないのだ。"

# ダクネス
# だから無理はするな。\nなんだったら、また川沿いを\n一緒に歩くだけでもいい。
136 = "だから無理はするな。\\nなんだったら、また川沿いを\\n一緒に歩くだけでもいい。"

# カズマ
# べ、別に？\n無理なんてしてねーよ？
139 = "べ、別に？\\n無理なんてしてねーよ？"

# ダクネス
# そうか、それはすまなかった。
134 = "そうか、それはすまなかった。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、ダクネスはなんて優しいんだ。\n　俺がふがいないばかりに、\n　気を遣わせちまった……）
160 = "（ああ、ダクネスはなんて優しいんだ。\\n　俺がふがいないばかりに、\\n　気を遣わせちまった……）"

# カズマ（Ｍ）
# display as カズマ
# （これ以上、無様な姿は見せられん！\n　こうなったら俺のアドリブ力の高さを\n　見せるしかない！！）
164 = "（これ以上、無様な姿は見せられん！\\n　こうなったら俺のアドリブ力の高さを\\n　見せるしかない！！）"

# カズマ（Ｍ）
# display as カズマ
# （絶対に満足させてやるから、\n　楽しみにしてろよ、ダクネス！）
178 = "（絶対に満足させてやるから、\\n　楽しみにしてろよ、ダクネス！）"

# カズマ
# よし、こっちだ！
141 = "よし、こっちだ！"

# ダクネス
# あっ……。
130 = "あっ……。"

# カズマ（Ｍ）
# display as カズマ
# （……お、思わず手を繋いじまったが、\n　デートなんだし、いいよな？）
158 = "（……お、思わず手を繋いじまったが、\\n　デートなんだし、いいよな？）"

# ダクネス
# …………。
127 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （……ダクネスも軽く手を握り返してくれた。\n　くううううう～！　いい、いい雰囲気だ！\n　この勢いで行くぞ！！）
159 = "（……ダクネスも軽く手を握り返してくれた。\\n　くううううう～！　いい、いい雰囲気だ！\\n　この勢いで行くぞ！！）"

