# root_a11.txt.scn

[info]
0 = ""

[characters]
398 = "カズマ（Ｍ）"
399 = "ダクネス"
396 = "カズマ"
387 = "めぐみん"
393 = "アクア"

[character_subs]
# 396 = "カズマ"

[script]
# lines: 113

# カズマ（Ｍ）
# display as カズマ
# （そして、あれから数日が経ち……）
487 = "（そして、あれから数日が経ち……）"

# カズマ（Ｍ）
# display as カズマ
# （アクアは色々なバイトを掛け持ちし、\n　文句を垂れながらも働いている）
493 = "（アクアは色々なバイトを掛け持ちし、\\n　文句を垂れながらも働いている）"

# カズマ（Ｍ）
# display as カズマ
# （あのアクアにしては珍しく、\n　というかやっぱり責任を感じているのか\n　真面目にやっているようだ）
478 = "（あのアクアにしては珍しく、\\n　というかやっぱり責任を感じているのか\\n　真面目にやっているようだ）"

# カズマ（Ｍ）
# display as カズマ
# （……一応、俺も、呪いの指輪の時にみんなに\n　迷惑をかけた後ろめたさもあって、表立っては\n　言わないがクエストなどをこなしていた）
476 = "（……一応、俺も、呪いの指輪の時にみんなに\\n　迷惑をかけた後ろめたさもあって、表立っては\\n　言わないがクエストなどをこなしていた）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスやめぐみんも\n　俺に付き合ってくれて、効率のいいクエストを\n　片付けているのだが……）
494 = "（ダクネスやめぐみんも\\n　俺に付き合ってくれて、効率のいいクエストを\\n　片付けているのだが……）"

# カズマ（Ｍ）
# display as カズマ
# （うーむ……。\n　今週上がってきた、みんなの収入を\n　まとめてみたけど……）
482 = "（うーむ……。\\n　今週上がってきた、みんなの収入を\\n　まとめてみたけど……）"

# ダクネス
# どうだ？\n多少、返済は進みそうか？
370 = "どうだ？\\n多少、返済は進みそうか？"

# カズマ
# いや、焼け石に水だ。\nまったく、何をどうすれば\nこれだけの借金になるんだか。
332 = "いや、焼け石に水だ。\\nまったく、何をどうすれば\\nこれだけの借金になるんだか。"

# めぐみん
# 騙されて念書にサインすれば\nいいんじゃないですか？
475 = "騙されて念書にサインすれば\\nいいんじゃないですか？"

# カズマ
# そういう冷静なツッコミはいらん。
350 = "そういう冷静なツッコミはいらん。"

# めぐみん
# ふ、ふふ、このままだと数日後には食べる物にも\n困る日々がやってくるんですね。
382 = "ふ、ふふ、このままだと数日後には食べる物にも\\n困る日々がやってくるんですね。"

# カズマ（Ｍ）
# display as カズマ
# （くっ、馬小屋生活に戻ることだけは\n　なんとしても避けたい！）
483 = "（くっ、馬小屋生活に戻ることだけは\\n　なんとしても避けたい！）"

# カズマ
# しょうがない。\nこうなったら高難易度のクエストに挑戦するか。
349 = "しょうがない。\\nこうなったら高難易度のクエストに挑戦するか。"

# ダクネス
# そう来ると思って、目処をつけておいたぞ！
352 = "そう来ると思って、目処をつけておいたぞ！"

# カズマ
# 嬉しそうだな、お前。
413 = "嬉しそうだな、お前。"

# アクア
# みんな、いる！
386 = "みんな、いる！"

# めぐみん
# な、なんですか、驚かさないでくださいよ！
371 = "な、なんですか、驚かさないでくださいよ！"

# ダクネス
# それにどうした。\n今はまだバイトの時間の筈だろう。
358 = "それにどうした。\\n今はまだバイトの時間の筈だろう。"

# アクア
# それどころじゃないのよ！\nちょっとこれを見て！
355 = "それどころじゃないのよ！\\nちょっとこれを見て！"

# めぐみん
# チラシ？\nどこかで安売りでもしているのですか？
400 = "チラシ？\\nどこかで安売りでもしているのですか？"

# アクア
# 違うのよ。\nすっごいいい話なの！
473 = "違うのよ。\\nすっごいいい話なの！"

# カズマ
# ……そのすごいいい話で、\nまさについ最近とんでもないことを\nやらかした気がするんだが？
325 = "……そのすごいいい話で、\\nまさについ最近とんでもないことを\\nやらかした気がするんだが？"

# アクア
# 大丈夫！\n今度のはちゃんと裏を取ったから！
412 = "大丈夫！\\n今度のはちゃんと裏を取ったから！"

# カズマ（Ｍ）
# display as カズマ
# （裏を取ったって……）
496 = "（裏を取ったって……）"

# ダクネス
# なになに？\n『あなたこそ女神エリス様コンテスト開催』\nこれは、エリス様を称えるイベントか？
374 = "なになに？\\n『あなたこそ女神エリス様コンテスト開催』\\nこれは、エリス様を称えるイベントか？"

# カズマ
# 何か、どっかの商店街がやってそうな\nしょっぱいイベントっぽいな。
407 = "何か、どっかの商店街がやってそうな\\nしょっぱいイベントっぽいな。"

# アクア
# それがそうでもないのよ。\nほら、まず賞金を見て。
353 = "それがそうでもないのよ。\\nほら、まず賞金を見て。"

# めぐみん
# 優勝賞金５００万エリス！？
408 = "優勝賞金５００万エリス！？"

# カズマ
# いやいやいや、\nこれってつまり美少女コンテストみたいな\nもんなんだろ？
333 = "いやいやいや、\\nこれってつまり美少女コンテストみたいな\\nもんなんだろ？"

# カズマ
# そんなイベントに５００万エリスって、\n胡散臭さしかないだろう！
362 = "そんなイベントに５００万エリスって、\\n胡散臭さしかないだろう！"

# アクア
# ただの美少女コンテストだったらそうね。\nでも、ほら、主催者のところを見てみなさい。
363 = "ただの美少女コンテストだったらそうね。\\nでも、ほら、主催者のところを見てみなさい。"

# ダクネス
# ん？\n『主催：エリス教団アクセル支部』。
391 = "ん？\\n『主催：エリス教団アクセル支部』。"

# カズマ
# えっ！　オフィシャルかよ！
336 = "えっ！　オフィシャルかよ！"

# ダクネス
# なるほど、エリス様の名を冠する以上、\n価値を低く見られるイベントには\nできないということか。
375 = "なるほど、エリス様の名を冠する以上、\\n価値を低く見られるイベントには\\nできないということか。"

# カズマ（Ｍ）
# display as カズマ
# （見栄の世界ってすごいな……）
497 = "（見栄の世界ってすごいな……）"

# めぐみん
# 確かに、エリス教団なら信用できますね。
468 = "確かに、エリス教団なら信用できますね。"

# ダクネス
# エリス教団なら、詐欺などありえないだろうからな。
394 = "エリス教団なら、詐欺などありえないだろうからな。"

# アクア
# なにか今、胸がチクっとしたんだけど\n気のせいかしら。
373 = "なにか今、胸がチクっとしたんだけど\\n気のせいかしら。"

# カズマ
# 気のせいってことにしておけ。\nんで、コンテストの内容は？
420 = "気のせいってことにしておけ。\\nんで、コンテストの内容は？"

# カズマ
# 『あなたこそエリス様の化身！\n　偉大なる女神エリス様の美しさや\n　清楚な内面を体現してみませんか』
327 = "『あなたこそエリス様の化身！\\n　偉大なる女神エリス様の美しさや\\n　清楚な内面を体現してみませんか』"

# カズマ
# 『エリス様がこの世に降臨したらかくや、\n　と自信のある方の参加、お待ちしております！』
328 = "『エリス様がこの世に降臨したらかくや、\\n　と自信のある方の参加、お待ちしております！』"

# カズマ（Ｍ）
# display as カズマ
# （んん？\n　これはつまり……）
492 = "（んん？\\n　これはつまり……）"

# カズマ
# エリス様の化身ってことは、\nただのミスコンじゃなくて、\nよりエリス様に近い人が優勝するってことか？
395 = "エリス様の化身ってことは、\\nただのミスコンじゃなくて、\\nよりエリス様に近い人が優勝するってことか？"

# めぐみん
# 細かい参加基準を読む限り、そうみたいですね。
472 = "細かい参加基準を読む限り、そうみたいですね。"

# アクア
# ふふふ、これで借金を返せる目処が立ったわね！
383 = "ふふふ、これで借金を返せる目処が立ったわね！"

# カズマ
# ……つまり参加をすると？
326 = "……つまり参加をすると？"

# アクア
# 当然じゃない！
417 = "当然じゃない！"

# カズマ
# おい、アクア、ちょっと来い。
339 = "おい、アクア、ちょっと来い。"

# アクア
# な、何よ。
372 = "な、何よ。"

# カズマ
# これってエリス様を真似るコンテストなんだぞ？
347 = "これってエリス様を真似るコンテストなんだぞ？"

# アクア
# うん、知ってるわよ。
334 = "うん、知ってるわよ。"

# カズマ
# お前、プライドないのかよ。
340 = "お前、プライドないのかよ。"

# アクア
# プライドなんて、借金を返した後に\nいくらでも取り返せるわ！
401 = "プライドなんて、借金を返した後に\\nいくらでも取り返せるわ！"

# カズマ（Ｍ）
# display as カズマ
# （うわー、前向きだなー）
481 = "（うわー、前向きだなー）"

# アクア
# それに、私だからこそ\n勝ち目があるってものじゃない。
356 = "それに、私だからこそ\\n勝ち目があるってものじゃない。"

# カズマ
# お前とエリス様じゃ月とすっぽんだろ。\n何を愉快な勘違いしてるんだ。
343 = "お前とエリス様じゃ月とすっぽんだろ。\\n何を愉快な勘違いしてるんだ。"

# アクア
# 今の失言は不問にしておいてあげるわ。
406 = "今の失言は不問にしておいてあげるわ。"

# カズマ
# それはどうも。
359 = "それはどうも。"

# アクア
# 私が言いたいのは、\n私は本物のエリスを知ってるってことよ。
471 = "私が言いたいのは、\\n私は本物のエリスを知ってるってことよ。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、なるほど。\n　確か先輩後輩の仲だもんな）
477 = "（ああ、なるほど。\\n　確か先輩後輩の仲だもんな）"

# アクア
# この世界の人間が知ってるエリスは\n所詮創造物エリスよ。
345 = "この世界の人間が知ってるエリスは\\n所詮創造物エリスよ。"

# アクア
# 想像をして似せただけのエリスに、\n本物を似せて演じる私のエリスが負けるわけ無いわ！
418 = "想像をして似せただけのエリスに、\\n本物を似せて演じる私のエリスが負けるわけ無いわ！"

# カズマ（Ｍ）
# display as カズマ
# （いやいや、審査する人間は\n　想像したエリス様を基準に審査するんだろ）
480 = "（いやいや、審査する人間は\\n　想像したエリス様を基準に審査するんだろ）"

# アクア
# ふふん、勝利は確実ね。
384 = "ふふん、勝利は確実ね。"

# カズマ（Ｍ）
# display as カズマ
# （そういう所まで想像が及ばないのが\n　なんともアクアらしいというか……）
486 = "（そういう所まで想像が及ばないのが\\n　なんともアクアらしいというか……）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、やる気に水を差すのもあれか。\n　このままだと借金を返せないのも事実なんだし）
491 = "（まあ、やる気に水を差すのもあれか。\\n　このままだと借金を返せないのも事実なんだし）"

# カズマ（Ｍ）
# display as カズマ
# （だが――）
489 = "（だが――）"

# カズマ
# 今のままだと優勝は難しいんじゃないか？
405 = "今のままだと優勝は難しいんじゃないか？"

# アクア
# え、どうして？
335 = "え、どうして？"

# カズマ
# これってただ外見を似せればいいってもんじゃ\nないんだよな？
346 = "これってただ外見を似せればいいってもんじゃ\\nないんだよな？"

# ダクネス
# そうだな。\n知性に教養、そして女のつつしみに優麗とした所作。\nさらにはエリス様の知識も求められるだろう。
351 = "そうだな。\\n知性に教養、そして女のつつしみに優麗とした所作。\\nさらにはエリス様の知識も求められるだろう。"

# アクア
# ふーん、そうなんだ。
385 = "ふーん、そうなんだ。"

# カズマ
# おい、なんか人ごとだな。
338 = "おい、なんか人ごとだな。"

# アクア
# そんなことはないわよ。\nでも今言ったのって、私全部持ち合わせてるし。
361 = "そんなことはないわよ。\\nでも今言ったのって、私全部持ち合わせてるし。"

# カズマ
# は？　お前、何言ってるの？\nお前が持ってるのって、エリス様の知識だけだろ。
381 = "は？　お前、何言ってるの？\\nお前が持ってるのって、エリス様の知識だけだろ。"

# アクア
# ちょっとそれ、失礼だと思うんですけど。\n私、女神なのよ、それにエリスの\n先輩なんですからね。
367 = "ちょっとそれ、失礼だと思うんですけど。\\n私、女神なのよ、それにエリスの\\n先輩なんですからね。"

# カズマ（Ｍ）
# display as カズマ
# （いや、先輩後輩は関係ないから）
479 = "（いや、先輩後輩は関係ないから）"

# アクア
# でも、不安が無いと言ったら嘘になるわね。\nそうだ、特訓をするっていうのはどうかしら！
369 = "でも、不安が無いと言ったら嘘になるわね。\\nそうだ、特訓をするっていうのはどうかしら！"

# カズマ
# ああ、頑張れ。
330 = "ああ、頑張れ。"

# アクア
# なんで人ごとなのよ。\nカズマがいないと話にならないでしょ。
379 = "なんで人ごとなのよ。\\nカズマがいないと話にならないでしょ。"

# カズマ
# はあ、なんで？
380 = "はあ、なんで？"

# アクア
# カズマはエリスのこと知ってるじゃない。\n私はあの子、見慣れちゃってるから\n客観的な視点が欲しいのよ。
397 = "カズマはエリスのこと知ってるじゃない。\\n私はあの子、見慣れちゃってるから\\n客観的な視点が欲しいのよ。"

# カズマ
# なんでだよ、嫌だ。
378 = "なんでだよ、嫌だ。"

# アクア
# ためらいなく拒否ったわね。
365 = "ためらいなく拒否ったわね。"

# カズマ
# 当たり前だろ、特訓したところで\n無駄にしかならない可能性が高いからな。
416 = "当たり前だろ、特訓したところで\\n無駄にしかならない可能性が高いからな。"

# アクア
# 大丈夫よ！\n事が事だから、ちゃんと真面目にやる！\nやりますから！
411 = "大丈夫よ！\\n事が事だから、ちゃんと真面目にやる！\\nやりますから！"

# カズマ（Ｍ）
# display as カズマ
# （真面目にやったところで無駄になるんだが……\n　まあ、やる気になってるところは認めるか）
495 = "（真面目にやったところで無駄になるんだが……\\n　まあ、やる気になってるところは認めるか）"

# カズマ
# お前が真面目にやるならいいぞ。
342 = "お前が真面目にやるならいいぞ。"

# アクア
# さすがに今の状況でふざけたりしないわ。\nもう、馬小屋生活なんて二度とごめんだしね。
348 = "さすがに今の状況でふざけたりしないわ。\\nもう、馬小屋生活なんて二度とごめんだしね。"

# カズマ
# お前のその言葉、信じるからな。
344 = "お前のその言葉、信じるからな。"

# アクア
# それじゃ、よろしく頼むわね、カズマ。
354 = "それじゃ、よろしく頼むわね、カズマ。"

# カズマ
# 確かに一理あるな。
470 = "確かに一理あるな。"

# アクア
# でしょー？
368 = "でしょー？"

# カズマ（Ｍ）
# display as カズマ
# （しかし客観的に見て、\n　アクアとエリス様の違いか……）
485 = "（しかし客観的に見て、\\n　アクアとエリス様の違いか……）"

# アクア
# ん？　どうかした？
392 = "ん？　どうかした？"

# カズマ（Ｍ）
# display as カズマ
# （たくさんありすぎて、\n　どこから修正したらいいかわからねー！）
488 = "（たくさんありすぎて、\\n　どこから修正したらいいかわからねー！）"

# カズマ
# それにしても、いくら賞金のためとは言え、\nお前がこんなコンテストに出る気になるなんてな。
357 = "それにしても、いくら賞金のためとは言え、\\nお前がこんなコンテストに出る気になるなんてな。"

# アクア
# え、どうして？
# 335 = "え、どうして？"

# カズマ
# だってお前、エリス様のこと良く思ってないだろ。
366 = "だってお前、エリス様のこと良く思ってないだろ。"

# アクア
# そんなことないけど？\nあれはあれで可愛い後輩だし。
360 = "そんなことないけど？\\nあれはあれで可愛い後輩だし。"

# アクア
# ただ国教として崇拝されるなんて、\nちょっと調子に乗りすぎよねって思ってるだけよ。
364 = "ただ国教として崇拝されるなんて、\\nちょっと調子に乗りすぎよねって思ってるだけよ。"

# カズマ（Ｍ）
# display as カズマ
# （つまり嫉妬か……嘆かわしい）
490 = "（つまり嫉妬か……嘆かわしい）"

# アクア
# あっ、そうだ！\nうんうん、そういうのもありかもしれないわね。
331 = "あっ、そうだ！\\nうんうん、そういうのもありかもしれないわね。"

# カズマ
# なんだ、またくだらないことを思いついたのか。
376 = "なんだ、またくだらないことを思いついたのか。"

# アクア
# え？　な、なんでもないけど？\nそれよりも特訓しないと！
337 = "え？　な、なんでもないけど？\\nそれよりも特訓しないと！"

# アクア
# もちろん、ダクネスとめぐみんも手伝って\nくれるわよね？
389 = "もちろん、ダクネスとめぐみんも手伝って\\nくれるわよね？"

# めぐみん
# 知性でしたら、私に任せておいてください！
467 = "知性でしたら、私に任せておいてください！"

# ダクネス
# 教養など、そういう部分は\n多少なら教えられるかもしれないな。
419 = "教養など、そういう部分は\\n多少なら教えられるかもしれないな。"

# アクア
# よーし、じゃあ、気合いを入れてやるわよ！！
390 = "よーし、じゃあ、気合いを入れてやるわよ！！"

# カズマ（Ｍ）
# display as カズマ
# （さて、俺は俺でできることをやっておくか）
484 = "（さて、俺は俺でできることをやっておくか）"

# カズマ
# めぐみん、ちょっと頼みたい事があるんだけど、\nいいか？
388 = "めぐみん、ちょっと頼みたい事があるんだけど、\\nいいか？"

# めぐみん
# 頼みたい事ですか？
474 = "頼みたい事ですか？"

# カズマ
# ああ、実はな――
329 = "ああ、実はな――"

[selections]
377 = "なんでだよ、嫌だ"
341 = "お前が真面目にやるならいいぞ"
469 = "確かに一理あるな"
