# root_e14.txt.scn

[info]
0 = ""

[characters]
254 = "カズマ"
253 = "ウィズ"
256 = "クリス"
241 = "めぐみん"
247 = "ゆんゆん"
250 = "アクア"
255 = "カズマ（Ｍ）"

[character_subs]
# 254 = "カズマ"

[script]
# lines: 40

# カズマ
# よ～し！\nそれじゃ、張り切って勝負いってみようか！
249 = "よ～し！\\nそれじゃ、張り切って勝負いってみようか！"

# ウィズ
# あ、あの、ちょっと待ってください、カズマさん。\n勝負ってなんですか？
219 = "あ、あの、ちょっと待ってください、カズマさん。\\n勝負ってなんですか？"

# カズマ
# あれ？\n話してなかったっけ？
220 = "あれ？\\n話してなかったっけ？"

# クリス
# 少なくともあたしは、\n頼みたいことがあるから、\n明日、屋敷に来てくれって言われただけだよ？
261 = "少なくともあたしは、\\n頼みたいことがあるから、\\n明日、屋敷に来てくれって言われただけだよ？"

# ウィズ
# 私もです。
289 = "私もです。"

# カズマ
# あー、悪い悪い。\nんじゃ、まずは簡単に説明するよ。\nといっても、難しい話じゃないんだ。
221 = "あー、悪い悪い。\\nんじゃ、まずは簡単に説明するよ。\\nといっても、難しい話じゃないんだ。"

# カズマ
# めぐみんとゆんゆん、\nどっちがうちのパーティーに相応しい\nアークウイザードか、勝負で決める！
243 = "めぐみんとゆんゆん、\\nどっちがうちのパーティーに相応しい\\nアークウイザードか、勝負で決める！"

# カズマ
# で、２人にはその審査員になってほしいんだよ。
234 = "で、２人にはその審査員になってほしいんだよ。"

# クリス
# ふーん、そういうことか。\nまあ、楽しそうだし、あたしは構わないかな。
239 = "ふーん、そういうことか。\\nまあ、楽しそうだし、あたしは構わないかな。"

# クリス
# アークウィザード、\nしかも紅魔族同士の勝負なんて、\nそうそう見られるものじゃないしね。
251 = "アークウィザード、\\nしかも紅魔族同士の勝負なんて、\\nそうそう見られるものじゃないしね。"

# ウィズ
# ええと、私も、\n審査する事自体は構わないのですが……。
225 = "ええと、私も、\\n審査する事自体は構わないのですが……。"

# ウィズ
# めぐみんさん、\nパーティーをやめてしまうのですか？
242 = "めぐみんさん、\\nパーティーをやめてしまうのですか？"

# めぐみん
# まだ決まったわけではありません。\n決めるための勝負なのです。
240 = "まだ決まったわけではありません。\\n決めるための勝負なのです。"

# ウィズ
# そうですか……。
231 = "そうですか……。"

# カズマ
# さて、審査員も揃ったところで\n改めて２人に確認しておこう。\n本当にいいんだな？
229 = "さて、審査員も揃ったところで\\n改めて２人に確認しておこう。\\n本当にいいんだな？"

# めぐみん
# もちろんです。\nゆんゆんに私の実力を見せつけるまでのことです。
245 = "もちろんです。\\nゆんゆんに私の実力を見せつけるまでのことです。"

# めぐみん
# その、思い上がり、伸びきった鼻を\nへし折って差し上げましょう。
232 = "その、思い上がり、伸びきった鼻を\\nへし折って差し上げましょう。"

# ゆんゆん
# それは私のセリフよっ！\n今度こそ絶対に勝つ！\nそして私のことを認めさせてみせる！
233 = "それは私のセリフよっ！\\n今度こそ絶対に勝つ！\\nそして私のことを認めさせてみせる！"

# ゆんゆん
# 私が勝ったら謝ってもらうわよ、めぐみん！
287 = "私が勝ったら謝ってもらうわよ、めぐみん！"

# めぐみん
# 謝る理由など何１つありませんがいいでしょう。\nその代わり私が勝ったら謝罪して\nもらいますからね？
291 = "謝る理由など何１つありませんがいいでしょう。\\nその代わり私が勝ったら謝罪して\\nもらいますからね？"

# カズマ
# うむ、２人の意気込みはよくわかったが……\nもう一度だけ聞く。
222 = "うむ、２人の意気込みはよくわかったが……\\nもう一度だけ聞く。"

# カズマ
# どんな熾烈な勝負になろうとも\n逃げずに最後までやりきるんだな？
236 = "どんな熾烈な勝負になろうとも\\n逃げずに最後までやりきるんだな？"

# めぐみん
# くどいです。\nゆんゆんが逃げ出しでもしない限り、\n最後までやりとおしてみせますよ。
226 = "くどいです。\\nゆんゆんが逃げ出しでもしない限り、\\n最後までやりとおしてみせますよ。"

# ゆんゆん
# 私だって！\nめぐみんが逃げたとしても\n最後までやり遂げてみせます！
288 = "私だって！\\nめぐみんが逃げたとしても\\n最後までやり遂げてみせます！"

# カズマ
# よしよし。\nそれじゃ、勝負の説明に移らせてもらおう。
248 = "よしよし。\\nそれじゃ、勝負の説明に移らせてもらおう。"

# カズマ
# 勝負は３回！\n俺、アクア、ダクネスから１つずつ課題を出す。\n２勝以上した方の勝ち。
258 = "勝負は３回！\\n俺、アクア、ダクネスから１つずつ課題を出す。\\n２勝以上した方の勝ち。"

# カズマ
# これならわかりやすいだろ？
227 = "これならわかりやすいだろ？"

# めぐみん
# ええっ！？\nカズマの考えた課題なんて……\n嫌な予感しかしません。
223 = "ええっ！？\\nカズマの考えた課題なんて……\\n嫌な予感しかしません。"

# カズマ
# やると言った以上もう後戻りはできないぞ。\nそれとも素直に負けを認め、\nゆんゆんに頭を下げるか？
246 = "やると言った以上もう後戻りはできないぞ。\\nそれとも素直に負けを認め、\\nゆんゆんに頭を下げるか？"

# めぐみん
# も、もちろんやるに決まっています！\n頭を下げるなんてあり得ませんね！
244 = "も、もちろんやるに決まっています！\\n頭を下げるなんてあり得ませんね！"

# カズマ
# では最初の勝負だが……\nアクア、発表しろ！
235 = "では最初の勝負だが……\\nアクア、発表しろ！"

# アクア
# はーい！\n私の考えた勝負は『コロッケ早売り対決』よ！
237 = "はーい！\\n私の考えた勝負は『コロッケ早売り対決』よ！"

# クリス
# ……え？\nコロッケ早売り対決？
218 = "……え？\\nコロッケ早売り対決？"

# ウィズ
# ええと、アクア様？\nコロッケの早売りと\nアークウィザードにどんな関係が？
224 = "ええと、アクア様？\\nコロッケの早売りと\\nアークウィザードにどんな関係が？"

# アクア
# ふふん、わかってないわね。\n色々あるのよ色々と！
238 = "ふふん、わかってないわね。\\n色々あるのよ色々と！"

# カズマ
# 色々ってなんだよ？
290 = "色々ってなんだよ？"

# アクア
# アークウイザードに必要なことは、\nだいたいコロッケの早売りに詰まってるのよ？
252 = "アークウイザードに必要なことは、\\nだいたいコロッケの早売りに詰まってるのよ？"

# ゆんゆん
# そ、そうだったんですね！
230 = "そ、そうだったんですね！"

# カズマ（Ｍ）
# display as カズマ
# （いや、明らかに嘘だろ！）
292 = "（いや、明らかに嘘だろ！）"

# アクア
# さあ、場所を移すわよ！\nついてらっしゃい！
228 = "さあ、場所を移すわよ！\\nついてらっしゃい！"

