# root_f11.txt.scn

[info]
0 = ""

[characters]
350 = "ウィズ"
352 = "カズマ"
355 = "カズマ（Ｍ）"
374 = "男の子Ａ"
375 = "男の子Ｂ"
367 = "女の子"
354 = "カズマ＆ウィズ"
370 = "子供の母親Ａ"
371 = "子供の母親Ｂ"

[character_subs]
# 352 = "カズマ"
413 = "２人"

[script]
# lines: 99

# ウィズ
# カズマさん？\n一体、何をするんですか？
353 = "カズマさん？\\n一体、何をするんですか？"

# カズマ
# さっき思ったんだけど、\nウィズって、人の話を聞くのが好きだよな？
317 = "さっき思ったんだけど、\\nウィズって、人の話を聞くのが好きだよな？"

# ウィズ
# え？　ええ、はい。\nたまにお店で、暇な方のお話に付き合って\nつい長話になることはありますね。
301 = "え？　ええ、はい。\\nたまにお店で、暇な方のお話に付き合って\\nつい長話になることはありますね。"

# カズマ
# ゆんゆんとか？
348 = "ゆんゆんとか？"

# ウィズ
# はい、主にゆんゆんさんです。
341 = "はい、主にゆんゆんさんです。"

# カズマ（Ｍ）
# display as カズマ
# （うっ……ゆんゆん……）
401 = "（うっ……ゆんゆん……）"

# ウィズ
# それで、あの、私は何をすれば……。
329 = "それで、あの、私は何をすれば……。"

# カズマ
# ウィズの聞き上手スキルを使って、\n相談に乗ったりとか、愚痴を聞いてあげるんだよ。
351 = "ウィズの聞き上手スキルを使って、\\n相談に乗ったりとか、愚痴を聞いてあげるんだよ。"

# ウィズ
# お話を聞くことが、商売繁盛に繋がるんですか？
307 = "お話を聞くことが、商売繁盛に繋がるんですか？"

# カズマ
# 相談事があったり愚痴があったりするのって、\nつまりは何かしら困ってる事があるわけだろ？
396 = "相談事があったり愚痴があったりするのって、\\nつまりは何かしら困ってる事があるわけだろ？"

# ウィズ
# ええ、そうですね。
294 = "ええ、そうですね。"

# カズマ
# そういうのを聞いて回れば、\nもしかしたら何か必要な物がある、\nなんて話も出るかもしれない。
323 = "そういうのを聞いて回れば、\\nもしかしたら何か必要な物がある、\\nなんて話も出るかもしれない。"

# カズマ
# そうしたら、お店に入荷する\n商品のヒントになるじゃないか。
324 = "そうしたら、お店に入荷する\\n商品のヒントになるじゃないか。"

# ウィズ
# あ！　確かにそうですね。
288 = "あ！　確かにそうですね。"

# カズマ
# しかも、それ自体がウィズの売り込みにもなる。\nいろんな相談に乗ってくれる優しいお姉さん！\nってな。
318 = "しかも、それ自体がウィズの売り込みにもなる。\\nいろんな相談に乗ってくれる優しいお姉さん！\\nってな。"

# カズマ
# そうすれば、話をした人はもちろん、\n評判を聞いた人が、お店にも来てくれるわけだ。
325 = "そうすれば、話をした人はもちろん、\\n評判を聞いた人が、お店にも来てくれるわけだ。"

# ウィズ
# なるほど……。
335 = "なるほど……。"

# カズマ
# この宣伝のためにウィズがするのは\n話を聞くことだけだから、\nウィズの得意分野も活かせる。
316 = "この宣伝のためにウィズがするのは\\n話を聞くことだけだから、\\nウィズの得意分野も活かせる。"

# カズマ
# 一石二鳥どころか、三鳥ってわけだ。
361 = "一石二鳥どころか、三鳥ってわけだ。"

# ウィズ
# すごいですね、カズマさん！\nこれなら私にも出来そうです。
321 = "すごいですね、カズマさん！\\nこれなら私にも出来そうです。"

# カズマ
# だろう？\nそうと決まれば、\n話をして聞いてもらいたそうな人を捜すぞ！
330 = "だろう？\\nそうと決まれば、\\n話をして聞いてもらいたそうな人を捜すぞ！"

# ウィズ
# はい。
342 = "はい。"

# カズマ
# うーん、話を聞いて欲しそうな人って\n意外にいないもんだな。
293 = "うーん、話を聞いて欲しそうな人って\\n意外にいないもんだな。"

# カズマ
# いや、そもそも話を聞いて欲しそうな\n人ってどんな人だ？
291 = "いや、そもそも話を聞いて欲しそうな\\n人ってどんな人だ？"

# カズマ
# じいさん？　ばあさん？\nウィズはどう思う？
319 = "じいさん？　ばあさん？\\nウィズはどう思う？"

# カズマ
# …………。
279 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （って、いねー！）
405 = "（って、いねー！）"

# カズマ（Ｍ）
# display as カズマ
# （まさか迷子か！\n　それともまた怪しい露店商に掴まって――）
408 = "（まさか迷子か！\\n　それともまた怪しい露店商に掴まって――）"

# 男の子Ａ
# えへへ！\nおねえちゃん、おっぱいおっきー！！\nふっかふか～！
300 = "えへへ！\\nおねえちゃん、おっぱいおっきー！！\\nふっかふか～！"

# 男の子Ｂ
# すかーと、すごい長～い。\nこの中って、どうなってるのかな？
320 = "すかーと、すごい長～い。\\nこの中って、どうなってるのかな？"

# 女の子
# えへへ、お手々、繋いでる～。
299 = "えへへ、お手々、繋いでる～。"

# カズマ（Ｍ）
# display as カズマ
# （子供に絡まれてやがる……）
412 = "（子供に絡まれてやがる……）"

# ウィズ
# あら、カズマさん。
287 = "あら、カズマさん。"

# カズマ
# あら、じゃなくてさ。\nどうしたんだこれ？
286 = "あら、じゃなくてさ。\\nどうしたんだこれ？"

# ウィズ
# あ、あのですね？\n私も、困ってる人がいないか\n捜していたのですけど……。
281 = "あ、あのですね？\\n私も、困ってる人がいないか\\n捜していたのですけど……。"

# ウィズ
# この子たちのお母さんに、\n少し子供を見ていて欲しいと頼まれてしまいまして。\n遊び相手になっているところです。
315 = "この子たちのお母さんに、\\n少し子供を見ていて欲しいと頼まれてしまいまして。\\n遊び相手になっているところです。"

# カズマ
# ああ、そういうことか。
282 = "ああ、そういうことか。"

# 男の子Ａ
# おねえちゃん、\nぼくのママよりおっぱい大きいね。
302 = "おねえちゃん、\\nぼくのママよりおっぱい大きいね。"

# カズマ（Ｍ）
# display as カズマ
# （ウィズよりも大きい人を捜す方が\n　難しいんだぞ、ぼく）
409 = "（ウィズよりも大きい人を捜す方が\\n　難しいんだぞ、ぼく）"

# 男の子Ｂ
# かくれんぼできちゃいそう、ごそごそ。
311 = "かくれんぼできちゃいそう、ごそごそ。"

# カズマ（Ｍ）
# display as カズマ
# （うん、なんて羨まけしからんことを）
403 = "（うん、なんて羨まけしからんことを）"

# 女の子
# お姉ちゃん、お姉ちゃん！\nあっち行きましょ？\nほら、ねっ？
304 = "お姉ちゃん、お姉ちゃん！\\nあっち行きましょ？\\nほら、ねっ？"

# ウィズ
# ほらほら、お姉ちゃんの身体は\n１つだけなんだから、\nそんないっぱい言われても困っちゃいますよ。
345 = "ほらほら、お姉ちゃんの身体は\\n１つだけなんだから、\\nそんないっぱい言われても困っちゃいますよ。"

# カズマ（Ｍ）
# display as カズマ
# （これは、保母さんも顔負けの\n　懐かれっぷりだなぁ）
404 = "（これは、保母さんも顔負けの\\n　懐かれっぷりだなぁ）"

# カズマ
# なんか本当の母親みたいだな。
338 = "なんか本当の母親みたいだな。"

# ウィズ
# ええ？　そうでしょうか？
295 = "ええ？　そうでしょうか？"

# カズマ
# 知らない子供にこんな懐かれてるんだし、\n傍から見たらそう見えてもおかしくないぞ。
397 = "知らない子供にこんな懐かれてるんだし、\\n傍から見たらそう見えてもおかしくないぞ。"

# ウィズ
# も、もう。\n褒めても何も出ませんよ？
346 = "も、もう。\\n褒めても何も出ませんよ？"

# カズマ（Ｍ）
# display as カズマ
# （別に褒めてるわけじゃないけど……\n　いや、でもまあ褒めてるのか？）
411 = "（別に褒めてるわけじゃないけど……\\n　いや、でもまあ褒めてるのか？）"

# 女の子
# ねえ、お姉ちゃん。\nこの人、だれ？\nお姉ちゃんのこいびと？
339 = "ねえ、お姉ちゃん。\\nこの人、だれ？\\nお姉ちゃんのこいびと？"

# カズマ＆ウィズ
# display as ２人
# えっ！？
296 = "えっ！？"

# 女の子
# お姉ちゃん、このお兄ちゃんとしゃべってるとき、\nあたしのママがパパとしゃべってるときと\n同じかおしてるー。
305 = "お姉ちゃん、このお兄ちゃんとしゃべってるとき、\\nあたしのママがパパとしゃべってるときと\\n同じかおしてるー。"

# ウィズ
# ち、ち、違うのよっ！？\n確かにお友達だけど、\nそそそそ、そんな関係じゃっ！
331 = "ち、ち、違うのよっ！？\\n確かにお友達だけど、\\nそそそそ、そんな関係じゃっ！"

# カズマ（Ｍ）
# display as カズマ
# （うわぁ、さすが子供。\n　容赦ないというか、純粋過ぎて\n　ド直球な質問してきやがるぜ……）
402 = "（うわぁ、さすが子供。\\n　容赦ないというか、純粋過ぎて\\n　ド直球な質問してきやがるぜ……）"

# カズマ（Ｍ）
# display as カズマ
# （ま、でもそういう風に言われるのは\n　決して悪く……ないな。\n　ふふふ……ふふふ……）
406 = "（ま、でもそういう風に言われるのは\\n　決して悪く……ないな。\\n　ふふふ……ふふふ……）"

# 女の子
# お姉ちゃん、すごいてれてるー。
306 = "お姉ちゃん、すごいてれてるー。"

# ウィズ
# か、カズマさんっ！\nなんとかしてください！！
308 = "か、カズマさんっ！\\nなんとかしてください！！"

# カズマ
# 俺も遊んで欲しい！
364 = "俺も遊んで欲しい！"

# ウィズ
# えっ？\n私、この子たちで手一杯でして。
298 = "えっ？\\n私、この子たちで手一杯でして。"

# カズマ
# いいんだ！\n俺、この子と一緒に遊ぶから！
289 = "いいんだ！\\n俺、この子と一緒に遊ぶから！"

# 男の子Ｂ
# ……え、ぼく？
280 = "……え、ぼく？"

# カズマ
# ああ！　さっきから羨まし……\nではなく、けしからん事をしてるそこのキミ！\nお兄さんと遊ぼう！
284 = "ああ！　さっきから羨まし……\\nではなく、けしからん事をしてるそこのキミ！\\nお兄さんと遊ぼう！"

# 男の子Ｂ
# なにするのー？
334 = "なにするのー？"

# カズマ
# キミが、さっきから覗いてるその中！\nどうなってるのか、お兄さんに教えてくれ！
356 = "キミが、さっきから覗いてるその中！\\nどうなってるのか、お兄さんに教えてくれ！"

# 男の子Ｂ
# んー、お姉ちゃんの足、すっごい細いの。\nモデルさんみたい！
349 = "んー、お姉ちゃんの足、すっごい細いの。\\nモデルさんみたい！"

# カズマ
# うんうん！\nで、その上の方は？　上の方は！？
292 = "うんうん！\\nで、その上の方は？　上の方は！？"

# ウィズ
# かか、カズマさん？\n何を考えてるんですかっ！？
310 = "かか、カズマさん？\\n何を考えてるんですかっ！？"

# カズマ
# 許してくれウィズ。\nこれは抑えきれない知的好奇心の現れなんだ！
400 = "許してくれウィズ。\\nこれは抑えきれない知的好奇心の現れなんだ！"

# カズマ
# で、どうなんだ！\n何色だった！？
332 = "で、どうなんだ！\\n何色だった！？"

# 男の子Ｂ
# 見てないよ。\nだって、女の人のいやがることをするなんて、\n男のかざかみにもおけないしね。
399 = "見てないよ。\\nだって、女の人のいやがることをするなんて、\\n男のかざかみにもおけないしね。"

# カズマ
# なぁっ！？
333 = "なぁっ！？"

# 男の子Ｂ
# お兄ちゃん、\nちょっとガキっぽいんじゃないの～？
303 = "お兄ちゃん、\\nちょっとガキっぽいんじゃないの～？"

# カズマ
# 子供に……ガキっぽいって言われた……。
369 = "子供に……ガキっぽいって言われた……。"

# ウィズ
# もう、自業自得ですよ。
347 = "もう、自業自得ですよ。"

# カズマ
# ママー、ママー！
359 = "ママー、ママー！"

# ウィズ
# えっ！？　な、何ですかっ！？
297 = "えっ！？　な、何ですかっ！？"

# カズマ
# 俺も甘えたい！\nそのおっぱいにダイブしたい！！
363 = "俺も甘えたい！\\nそのおっぱいにダイブしたい！！"

# ウィズ
# か、カズマさん？\n目が、恐いです……。
309 = "か、カズマさん？\\n目が、恐いです……。"

# カズマ
# その子供ばっかりずるい！\n俺も、顔を埋めたい、埋めたいんだぁ！
327 = "その子供ばっかりずるい！\\n俺も、顔を埋めたい、埋めたいんだぁ！"

# ウィズ
# ひっ、あっ、こ、来ないでくださーいっ！
343 = "ひっ、あっ、こ、来ないでくださーいっ！"

# カズマ
# ぎゃああああああ！？\nま、待った！　そんな本気のドレインタッチ\nされたら死んでしまうぅぅぅ……。
313 = "ぎゃああああああ！？\\nま、待った！　そんな本気のドレインタッチ\\nされたら死んでしまうぅぅぅ……。"

# ウィズ
# あああっ！\nすみませんっ！　ついとっさに！
283 = "あああっ！\\nすみませんっ！　ついとっさに！"

# 子供の母親Ａ
# すみません。\n助かりました。
322 = "すみません。\\n助かりました。"

# ウィズ
# いえ、お気になさらず。
290 = "いえ、お気になさらず。"

# 子供の母親Ｂ
# 実はねぇ、ちょっと昨日の夜に起きた事件で、\nこの辺りの住人が集まって会議してたんです。
372 = "実はねぇ、ちょっと昨日の夜に起きた事件で、\\nこの辺りの住人が集まって会議してたんです。"

# カズマ（Ｍ）
# display as カズマ
# （事件？　会議？\n　なんだか穏やかじゃない単語が出てきたぞ）
410 = "（事件？　会議？\\n　なんだか穏やかじゃない単語が出てきたぞ）"

# 男の子Ａ
# あのね、おねえちゃん。\n怖かったんだよー、昨日の夜にねー。
285 = "あのね、おねえちゃん。\\n怖かったんだよー、昨日の夜にねー。"

# 男の子Ｂ
# なんか、急におうちが\nミシミシ言ったり、ピシって音がしたんだ。
336 = "なんか、急におうちが\\nミシミシ言ったり、ピシって音がしたんだ。"

# 女の子
# がたがた部屋の物も動いたりして……。\n怖くておといれ行けなかったの……。
312 = "がたがた部屋の物も動いたりして……。\\n怖くておといれ行けなかったの……。"

# 子供の母親Ａ
# こういうわけでして……\n最初はうちの子だけの話かと思ったんですが。
314 = "こういうわけでして……\\n最初はうちの子だけの話かと思ったんですが。"

# 子供の母親Ｂ
# 聞けば、昨晩たくさんの家で\n同じような騒ぎがあったらしんですよ。
398 = "聞けば、昨晩たくさんの家で\\n同じような騒ぎがあったらしんですよ。"

# 子供の母親Ａ
# 子供だけじゃなく、\n大人にもそういう目に遭った人がいたので、\nこれはちょっとおかしいぞって話に……。
368 = "子供だけじゃなく、\\n大人にもそういう目に遭った人がいたので、\\nこれはちょっとおかしいぞって話に……。"

# ウィズ
# そうだったんですか。
326 = "そうだったんですか。"

# 子供の母親Ｂ
# 冒険者ギルドや街の教会にも\n話を通そうということにはなったんですが、\nすぐには動けませんでしょうし。
365 = "冒険者ギルドや街の教会にも\\n話を通そうということにはなったんですが、\\nすぐには動けませんでしょうし。"

# 子供の母親Ｂ
# ひとまず、今日は子供たちと一緒に\n寝ることにします。
344 = "ひとまず、今日は子供たちと一緒に\\n寝ることにします。"

# ウィズ
# はい、そうですね。\nお子さんたちが怖がらないように、\nついててあげて下さい。
340 = "はい、そうですね。\\nお子さんたちが怖がらないように、\\nついててあげて下さい。"

# 子供の母親Ａ
# それじゃ、お世話になりました。
328 = "それじゃ、お世話になりました。"

# カズマ（Ｍ）
# display as カズマ
# （まさか、そんな話が街で出てたとは。\n　これも悪霊の仕業なのか？）
407 = "（まさか、そんな話が街で出てたとは。\\n　これも悪霊の仕業なのか？）"

# ウィズ
# …………。
# 279 = "…………。"

[selections]
337 = "なんか本当の母親みたいだな"
# 364 = "俺も遊んで欲しい！"
360 = "ママー、ママー！！"
