# root_e21.txt.scn

[info]
0 = ""

[characters]
222 = "アクア"
220 = "ゆんゆん"
225 = "ダクネス"
223 = "カズマ"
218 = "めぐみん"
224 = "カズマ（Ｍ）"

[character_subs]
# 223 = "カズマ"

[script]
# lines: 41

# アクア
# 乾杯～！
227 = "乾杯～！"

# ゆんゆん
# か、乾杯！
199 = "か、乾杯！"

# アクア
# ぷは～、美味しい～！
213 = "ぷは～、美味しい～！"

# ダクネス
# 戦闘で火照った体を\n優しく冷やしてくれるこの感じは、\n何度経験してもいいものだ。
233 = "戦闘で火照った体を\\n優しく冷やしてくれるこの感じは、\\n何度経験してもいいものだ。"

# アクア
# それに料理がまた美味しい！\n本当、ゆんゆんは大した腕前ね。
203 = "それに料理がまた美味しい！\\n本当、ゆんゆんは大した腕前ね。"

# ダクネス
# また腕を上げたな。\nこれなら店を開けるんじゃないか？
216 = "また腕を上げたな。\\nこれなら店を開けるんじゃないか？"

# ゆんゆん
# えへへ、ありがとうございます。\nけど、アークウイザードを極めるのが\n私の目標ですから。
196 = "えへへ、ありがとうございます。\\nけど、アークウイザードを極めるのが\\n私の目標ですから。"

# ダクネス
# そうか、目標があるのは素晴らしいことだ。\n影ながら応援させてもらおう。
201 = "そうか、目標があるのは素晴らしいことだ。\\n影ながら応援させてもらおう。"

# ゆんゆん
# ありがとうございます。\nあ、お皿が空ですね。\n何か取り分けましょうか？
192 = "ありがとうございます。\\nあ、お皿が空ですね。\\n何か取り分けましょうか？"

# ダクネス
# すまない。\nでは、適当にみつくろってくれ。
200 = "すまない。\\nでは、適当にみつくろってくれ。"

# ゆんゆん
# わかりました。\nアクアさんはグラスが空っぽですよ、\nお注ぎしますね。
221 = "わかりました。\\nアクアさんはグラスが空っぽですよ、\\nお注ぎしますね。"

# アクア
# おっとととと……\n相変わらず完璧な注ぎっぷりね。
197 = "おっとととと……\\n相変わらず完璧な注ぎっぷりね。"

# カズマ
# お～い、ゆんゆん、\nついでにこっちも注いでくれるか？
198 = "お～い、ゆんゆん、\\nついでにこっちも注いでくれるか？"

# ゆんゆん
# はい、喜んで！
211 = "はい、喜んで！"

# めぐみん
# …………。
189 = "…………。"

# ゆんゆん
# な、何？\nそんな目で見つめたりして？
207 = "な、何？\\nそんな目で見つめたりして？"

# めぐみん
# なぜ、ゆんゆんが当たり前のように\nこの場にいるのですか？
208 = "なぜ、ゆんゆんが当たり前のように\\nこの場にいるのですか？"

# ゆんゆん
# ええっと、新鮮な魚をたくさんもらったから\nお裾分けにきただけだけど？
195 = "ええっと、新鮮な魚をたくさんもらったから\\nお裾分けにきただけだけど？"

# カズマ
# で、アクアが引き留めて料理までさせたから、\nお礼に夕飯をってことになったんだ。\nお前だって見てただろ？
206 = "で、アクアが引き留めて料理までさせたから、\\nお礼に夕飯をってことになったんだ。\\nお前だって見てただろ？"

# めぐみん
# ……そういう意味ではありません。
190 = "……そういう意味ではありません。"

# めぐみん
# 修行に打ち込み、\n納得のできる成果を上げることができたら\n戻ってくるという話でしたよね？
228 = "修行に打ち込み、\\n納得のできる成果を上げることができたら\\n戻ってくるという話でしたよね？"

# めぐみん
# なのに、ずいぶんと早く戻ってきたものです。\nたったひと月で、私に勝てる程の力を\n身につけてきたとでも言うのですか？
210 = "なのに、ずいぶんと早く戻ってきたものです。\\nたったひと月で、私に勝てる程の力を\\n身につけてきたとでも言うのですか？"

# ゆんゆん
# それは、まだだけど……。\n今回は別にめぐみんに\n用があったわけじゃないもの。
204 = "それは、まだだけど……。\\n今回は別にめぐみんに\\n用があったわけじゃないもの。"

# めぐみん
# ふんっ！\nまったく都合がいいものですね。
212 = "ふんっ！\\nまったく都合がいいものですね。"

# アクア
# 別にいいじゃない。\n何も問題ないでしょ？
229 = "別にいいじゃない。\\n何も問題ないでしょ？"

# ダクネス
# そうだ、私達は友人ではないか。\n友人を訊ねるのに特別な理由などいらない。\nいつでも気軽に遊びに来ればいい。
202 = "そうだ、私達は友人ではないか。\\n友人を訊ねるのに特別な理由などいらない。\\nいつでも気軽に遊びに来ればいい。"

# ゆんゆん
# ゆ、友人……！？\n私のことを友達だと……思ってくれるんですか？
219 = "ゆ、友人……！？\\n私のことを友達だと……思ってくれるんですか？"

# ダクネス
# なにを今更。\n当然じゃないか。
209 = "なにを今更。\\n当然じゃないか。"

# ゆんゆん
# あ、あ、ありがとうございます！\nそれじゃ、お言葉に甘えてもいいですか？
191 = "あ、あ、ありがとうございます！\\nそれじゃ、お言葉に甘えてもいいですか？"

# アクア
# 甘えちゃいなさいよ。\nその代わり私も甘えるから、\nどんどんお世話してちょうだいね。
235 = "甘えちゃいなさいよ。\\nその代わり私も甘えるから、\\nどんどんお世話してちょうだいね。"

# ゆんゆん
# はい、喜んで！
# 211 = "はい、喜んで！"

# カズマ（Ｍ）
# display as カズマ
# （喜んじゃうのかよ。\n　騙されてるぞ、ゆんゆん……）
261 = "（喜んじゃうのかよ。\\n　騙されてるぞ、ゆんゆん……）"

# めぐみん
# まったく。\nなんですか、この状況は？
217 = "まったく。\\nなんですか、この状況は？"

# カズマ
# いいじゃないか、賑やかで。\nそれにしても、ゆんゆんも変わったよなぁ。
193 = "いいじゃないか、賑やかで。\\nそれにしても、ゆんゆんも変わったよなぁ。"

# カズマ
# 前は、ただみんなの世話を焼くだけだったけど、\n今は本人もちゃんと楽しんでるように見える。\nこれって、いいことだろ？
230 = "前は、ただみんなの世話を焼くだけだったけど、\\n今は本人もちゃんと楽しんでるように見える。\\nこれって、いいことだろ？"

# めぐみん
# まあ、多少は人間的に\n成長したと認めなくもありません。
215 = "まあ、多少は人間的に\\n成長したと認めなくもありません。"

# カズマ（Ｍ）
# display as カズマ
# （……本当に、素直じゃないな）
260 = "（……本当に、素直じゃないな）"

# ゆんゆん
# 私が変われたのなら……\nそれはカズマさんのおかげです。\nありがとうございます。
259 = "私が変われたのなら……\\nそれはカズマさんのおかげです。\\nありがとうございます。"

# カズマ
# まあ、俺は別に何もしてないって。
214 = "まあ、俺は別に何もしてないって。"

# めぐみん
# ちょっと待ってください！\nなぜカズマだけなのです？\n礼を言うならまず私にでしょう！？
205 = "ちょっと待ってください！\\nなぜカズマだけなのです？\\n礼を言うならまず私にでしょう！？"

# ゆんゆん
# うふふ！\nだってめぐみんは私のライバルだもん。
194 = "うふふ！\\nだってめぐみんは私のライバルだもん。"

