# root_e20.txt.scn

[info]
0 = ""

[characters]
180 = "カズマ（Ｍ）"
179 = "カズマ"
173 = "ゆんゆん"
169 = "めぐみん"

[character_subs]
# 179 = "カズマ"

[script]
# lines: 48

# カズマ（Ｍ）
# display as カズマ
# （ああ、今日もいい天気だ。\n　こんな日になんの予定もないのが\n　もったいない気がしてくる）
199 = "（ああ、今日もいい天気だ。\\n　こんな日になんの予定もないのが\\n　もったいない気がしてくる）"

# カズマ（Ｍ）
# display as カズマ
# （屋敷に帰ってもすることないしなぁ。\n　そうだ、ウィズの所にでも顔を出し――）
203 = "（屋敷に帰ってもすることないしなぁ。\\n　そうだ、ウィズの所にでも顔を出し――）"

# カズマ（Ｍ）
# display as カズマ
# （あれ？\n　あそこにいるのって……）
200 = "（あれ？\\n　あそこにいるのって……）"

# カズマ
# やっぱり、ゆんゆんとめぐみんか。
171 = "やっぱり、ゆんゆんとめぐみんか。"

# ゆんゆん
# あ、カズマさん。\nこんにちは。
150 = "あ、カズマさん。\\nこんにちは。"

# めぐみん
# 誰かと思えばカズマですか。\n驚かせないでください。
196 = "誰かと思えばカズマですか。\\n驚かせないでください。"

# めぐみん
# 近頃、このあたりに\n変質者が現れるという噂があるのですが、\nもしかしてカズマのことですか？
197 = "近頃、このあたりに\\n変質者が現れるという噂があるのですが、\\nもしかしてカズマのことですか？"

# カズマ
# 違うわい！\nそれより、２人揃って何をしてるんだ？
198 = "違うわい！\\nそれより、２人揃って何をしてるんだ？"

# めぐみん
# 見ての通り、お弁当を食べているのですが？\nもし入浴しているように見えるなら\n正真正銘の変質者ですね。
195 = "見ての通り、お弁当を食べているのですが？\\nもし入浴しているように見えるなら\\n正真正銘の変質者ですね。"

# カズマ
# わかってるよ！\nなんでいちいち変質者って方向に\n持っていこうとするんだよ、お前は！
177 = "わかってるよ！\\nなんでいちいち変質者って方向に\\n持っていこうとするんだよ、お前は！"

# めぐみん
# わかっていることを改めて確認するとは、\nよほど暇なのですね。
176 = "わかっていることを改めて確認するとは、\\nよほど暇なのですね。"

# カズマ
# だから、俺が聞いているのは\nそういう意味じゃなくてだな？
159 = "だから、俺が聞いているのは\\nそういう意味じゃなくてだな？"

# カズマ
# なんで、めぐみんだけが弁当を食べて\nその様子をゆんゆんが\n物悲しそうに見てるのかってことだよ。
164 = "なんで、めぐみんだけが弁当を食べて\\nその様子をゆんゆんが\\n物悲しそうに見てるのかってことだよ。"

# めぐみん
# それは、ゆんゆんが弱者だからです。
158 = "それは、ゆんゆんが弱者だからです。"

# ゆんゆん
# めぐみんが\n自分に有利な勝負をするからでしょ！？
170 = "めぐみんが\\n自分に有利な勝負をするからでしょ！？"

# めぐみん
# 何を言うのです。\n承諾したのですから自己責任です。
184 = "何を言うのです。\\n承諾したのですから自己責任です。"

# めぐみん
# 不満があるならその時点で\n断ればいいじゃないですか。
182 = "不満があるならその時点で\\n断ればいいじゃないですか。"

# ゆんゆん
# わかってるわよ。\nだから、こうしてお弁当を差し出してるんでしょ。
178 = "わかってるわよ。\\nだから、こうしてお弁当を差し出してるんでしょ。"

# カズマ
# あー、つまり、勝負して\nゆんゆんから弁当を巻き上げたのか？
152 = "あー、つまり、勝負して\\nゆんゆんから弁当を巻き上げたのか？"

# めぐみん
# 巻き上げたとは心外ですね。\n勝者に与えられた権利ですよ。
188 = "巻き上げたとは心外ですね。\\n勝者に与えられた権利ですよ。"

# カズマ
# そういえば、紅魔の里にいた頃は\n勝負のたびに弁当を取り上げてたとか言ってたな。
154 = "そういえば、紅魔の里にいた頃は\\n勝負のたびに弁当を取り上げてたとか言ってたな。"

# めぐみん
# 勝負を仕掛けてくるのは、\nいつもゆんゆんからでしたけどね。
186 = "勝負を仕掛けてくるのは、\\nいつもゆんゆんからでしたけどね。"

# ゆんゆん
# よく言うわ。\nこれ見よがしに挑発してきたのは\nめぐみんじゃない。
174 = "よく言うわ。\\nこれ見よがしに挑発してきたのは\\nめぐみんじゃない。"

# めぐみん
# その挑発に乗ってきたのはどこの誰です？\nいつもいつもアッサリ釣れて、\nチョロすぎるんですよ。
155 = "その挑発に乗ってきたのはどこの誰です？\\nいつもいつもアッサリ釣れて、\\nチョロすぎるんですよ。"

# ゆんゆん
# チョ、チョロすぎるって！
181 = "チョ、チョロすぎるって！"

# カズマ
# ……よくわかんねーなぁ。\nゆんゆんに絡まれるのを面倒くさがるくせに、\nどうしてそんな真似をするんだよ。
149 = "……よくわかんねーなぁ。\\nゆんゆんに絡まれるのを面倒くさがるくせに、\\nどうしてそんな真似をするんだよ。"

# めぐみん
# ……そうしなければならない\n切実な理由があったのです。
147 = "……そうしなければならない\\n切実な理由があったのです。"

# めぐみん
# 我が家は経済的に恵まれているとは言い難く、\nゆんゆんのお弁当が生命線だったのです。
189 = "我が家は経済的に恵まれているとは言い難く、\\nゆんゆんのお弁当が生命線だったのです。"

# めぐみん
# つまり、生きるためにやむえなくです！\nって、前にも言いませんでしたか？
162 = "つまり、生きるためにやむえなくです！\\nって、前にも言いませんでしたか？"

# カズマ
# いや、だけどさ、それは\n紅魔の里にいた頃の話だろ？
153 = "いや、だけどさ、それは\\n紅魔の里にいた頃の話だろ？"

# カズマ
# 少なくとも今は、食うには困ってないんだ。\n弁当を取り上げる必要ないだろ。
187 = "少なくとも今は、食うには困ってないんだ。\\n弁当を取り上げる必要ないだろ。"

# めぐみん
# それは……\n嬉しそうにお弁当を広げる\nゆんゆんを見かけたので、なんとなく。
157 = "それは……\\n嬉しそうにお弁当を広げる\\nゆんゆんを見かけたので、なんとなく。"

# ゆんゆん
# なんとなく！\n私、なんとなくでお弁当を取られたの！？
165 = "なんとなく！\\n私、なんとなくでお弁当を取られたの！？"

# ゆんゆん
# ……だ、だけど、その、\n紅魔の里の頃に戻ったみたいで……\nちょっとだけ、楽しかったけど。
148 = "……だ、だけど、その、\\n紅魔の里の頃に戻ったみたいで……\\nちょっとだけ、楽しかったけど。"

# めぐみん
# 勝負に負けて楽しかったのですか？\nどこまで負け犬根性が染みついているのですか。
185 = "勝負に負けて楽しかったのですか？\\nどこまで負け犬根性が染みついているのですか。"

# ゆんゆん
# ま、負け犬じゃないもんっ！
168 = "ま、負け犬じゃないもんっ！"

# めぐみん
# それにしても、料理の腕を上げましたね。
156 = "それにしても、料理の腕を上げましたね。"

# ゆんゆん
# ほ、本当！？\nめぐみんに負け続けたせいで\nどんどん上達しちゃって――
166 = "ほ、本当！？\\nめぐみんに負け続けたせいで\\nどんどん上達しちゃって――"

# ゆんゆん
# あっ！　ち、違うから！\nめぐみんのために\n腕を上げたんじゃないんだから！
151 = "あっ！　ち、違うから！\\nめぐみんのために\\n腕を上げたんじゃないんだから！"

# めぐみん
# わかっています。\n私のためになんて言われたら気持ち悪いですよ。
175 = "わかっています。\\n私のためになんて言われたら気持ち悪いですよ。"

# ゆんゆん
# 気持ち悪いって！\nそ、そこまで言わなくても～！
190 = "気持ち悪いって！\\nそ、そこまで言わなくても～！"

# カズマ（Ｍ）
# display as カズマ
# （はあ、なんだかんだ言いながら\n　本当に仲がいいよなぁ）
201 = "（はあ、なんだかんだ言いながら\\n　本当に仲がいいよなぁ）"

# カズマ（Ｍ）
# display as カズマ
# （もうすっかりふたりの世界だし、\n　俺はひっそり退散するか）
202 = "（もうすっかりふたりの世界だし、\\n　俺はひっそり退散するか）"

# めぐみん
# でもまあ、またお弁当を賭けるのなら\n勝負を受けてあげてもいいかもしれません。
163 = "でもまあ、またお弁当を賭けるのなら\\n勝負を受けてあげてもいいかもしれません。"

# ゆんゆん
# ほ、本当？\nそれじゃ腕によりをかけるねっ！
167 = "ほ、本当？\\nそれじゃ腕によりをかけるねっ！"

# めぐみん
# やれやれ、負ける前提ですか？
172 = "やれやれ、負ける前提ですか？"

# ゆんゆん
# ち、違うわよ！\nもちろん勝つのは私なんだからねっ！
161 = "ち、違うわよ！\\nもちろん勝つのは私なんだからねっ！"

# ゆんゆん
# だからまた勝負よ、めぐみん！
160 = "だからまた勝負よ、めぐみん！"

