# root_a07.txt.scn

[info]
0 = ""

[characters]
112 = "カズマ（Ｍ）"
111 = "カズマ"

[character_subs]
# 111 = "カズマ"

[script]
# lines: 5

# カズマ（Ｍ）
# display as カズマ
# （あれ？　どこに行った？）
118 = "（あれ？　どこに行った？）"

# カズマ（Ｍ）
# display as カズマ
# （くそ、こう暗いと闇に紛れられたら\n　捜しようもないか）
119 = "（くそ、こう暗いと闇に紛れられたら\\n　捜しようもないか）"

# カズマ
# …………。
110 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、いいや、アクアだし）
121 = "（まあ、いいや、アクアだし）"

# カズマ（Ｍ）
# display as カズマ
# （さ、布団に入って寝直そう）
120 = "（さ、布団に入って寝直そう）"

