# root_a09.txt.scn

[info]
0 = ""

[characters]
178 = "カズマ（Ｍ）"
171 = "アクア"
174 = "アクシズ教徒Ａ"
175 = "アクシズ教徒Ｂ"
176 = "アクシズ教徒Ｃ"
177 = "カズマ"

[character_subs]
# 177 = "カズマ"

[script]
# lines: 41

# カズマ（Ｍ）
# display as カズマ
# （そして夜になり、\n　俺は屋敷を抜け出したアクアの尾行を始めた）
207 = "（そして夜になり、\\n　俺は屋敷を抜け出したアクアの尾行を始めた）"

# カズマ（Ｍ）
# display as カズマ
# （俺達の運命がかかっているかもしれないのだから、\n　ここは慎重に事を運ばなければならない）
221 = "（俺達の運命がかかっているかもしれないのだから、\\n　ここは慎重に事を運ばなければならない）"

# カズマ（Ｍ）
# display as カズマ
# （それなのに、あいつは……）
209 = "（それなのに、あいつは……）"

# アクア
# ふんふんふ～ん。
168 = "ふんふんふ～ん。"

# カズマ（Ｍ）
# display as カズマ
# （なんであんなご機嫌なんだよ！\n　俺の緊張感を返せ！）
217 = "（なんであんなご機嫌なんだよ！\\n　俺の緊張感を返せ！）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、どこまで行くんだ？\n　このまま進むと街外れだぞ？\n　こっちに行っても何もないはずなのに）
206 = "（しかし、どこまで行くんだ？\\n　このまま進むと街外れだぞ？\\n　こっちに行っても何もないはずなのに）"

# アクア
# んふふふふ～。
170 = "んふふふふ～。"

# カズマ（Ｍ）
# display as カズマ
# （相変わらず、ご機嫌だな。\n　なんだか尾行するのがバカらしくなってきた）
223 = "（相変わらず、ご機嫌だな。\\n　なんだか尾行するのがバカらしくなってきた）"

# アクア
# こほん、あーあー。
165 = "こほん、あーあー。"

# カズマ（Ｍ）
# display as カズマ
# （ん？　なんだ？\n　あの家になんか用事でもあるのか？）
220 = "（ん？　なんだ？\\n　あの家になんか用事でもあるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （お？　入った！\n　とりあえず、アクアの行き先は\n　この家だったってことか）
204 = "（お？　入った！\\n　とりあえず、アクアの行き先は\\n　この家だったってことか）"

# カズマ（Ｍ）
# display as カズマ
# （って、んん？\n　家の中から歓声が聞こえたぞ？）
213 = "（って、んん？\\n　家の中から歓声が聞こえたぞ？）"

# カズマ（Ｍ）
# display as カズマ
# （なんだ？\n　一体、あの家でなにが起こってるんだ？）
216 = "（なんだ？\\n　一体、あの家でなにが起こってるんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （あの窓から見えそうだな。\n　ちょっと中、覗いてみるか）
202 = "（あの窓から見えそうだな。\\n　ちょっと中、覗いてみるか）"

# アクア
# みんな、待たせたわね！
169 = "みんな、待たせたわね！"

# カズマ（Ｍ）
# display as カズマ
# （って、なんじゃこりゃ！！）
212 = "（って、なんじゃこりゃ！！）"

# アクシズ教徒Ａ
# ああ、麗しき我らが教祖、女神アクア様～。
162 = "ああ、麗しき我らが教祖、女神アクア様～。"

# アクシズ教徒Ｂ
# アクア様～。
173 = "アクア様～。"

# アクシズ教徒Ｃ
# 我らを導く、気高くも麗しきアクア様～。
185 = "我らを導く、気高くも麗しきアクア様～。"

# アクア
# ふっふっふ！\nそう、私が女神アクア！\n私を崇め奉りなさーい！
167 = "ふっふっふ！\\nそう、私が女神アクア！\\n私を崇め奉りなさーい！"

# カズマ（Ｍ）
# display as カズマ
# （な、なんか、いつもにも増して\n　あの駄女神が調子に乗りまくってるぞ？）
214 = "（な、なんか、いつもにも増して\\n　あの駄女神が調子に乗りまくってるぞ？）"

# カズマ（Ｍ）
# display as カズマ
# （もしかして、この建物の中にいるのは\n　アクシズ教徒なのか？）
218 = "（もしかして、この建物の中にいるのは\\n　アクシズ教徒なのか？）"

# カズマ（Ｍ）
# display as カズマ
# （だとしたら、アクアのことを拝むのも\n　わからなくはないが……）
210 = "（だとしたら、アクアのことを拝むのも\\n　わからなくはないが……）"

# カズマ（Ｍ）
# display as カズマ
# （いや、待て待て。\n　いきなり女神が目の前に降臨するなんて、\n　常識的にはあり得ない）
203 = "（いや、待て待て。\\n　いきなり女神が目の前に降臨するなんて、\\n　常識的にはあり得ない）"

# カズマ（Ｍ）
# display as カズマ
# （あいつは確かにあんなのでも\n　本物の女神だけどさ……\n　常識ある人間なら信じないだろ）
201 = "（あいつは確かにあんなのでも\\n　本物の女神だけどさ……\\n　常識ある人間なら信じないだろ）"

# カズマ（Ｍ）
# display as カズマ
# （……それとも、ここにいる人達は\n　ころっと信じちまったってことか？）
200 = "（……それとも、ここにいる人達は\\n　ころっと信じちまったってことか？）"

# カズマ（Ｍ）
# display as カズマ
# （だとしたら、申し訳ないが\n　ここにいる人達も結構、アレだな……）
211 = "（だとしたら、申し訳ないが\\n　ここにいる人達も結構、アレだな……）"

# アクシズ教徒Ａ
# アクア様、また良い品物が手に入りました。\n今日もこの貢物をお収め下さいませ。
172 = "アクア様、また良い品物が手に入りました。\\n今日もこの貢物をお収め下さいませ。"

# アクシズ教徒Ｂ
# これにて、我らに富と繁栄を！！
166 = "これにて、我らに富と繁栄を！！"

# アクア
# 安心なさい。\nあなたたちには、必ずや我が恩恵が施されるわ。
181 = "安心なさい。\\nあなたたちには、必ずや我が恩恵が施されるわ。"

# アクシズ教徒Ｃ
# ありがとうございます、アクア様！
164 = "ありがとうございます、アクア様！"

# アクシズ教徒Ｂ
# 我らに、水の御加護のあらんことを！
184 = "我らに、水の御加護のあらんことを！"

# アクシズ教徒Ａ
# あらんことを～！
163 = "あらんことを～！"

# カズマ（Ｍ）
# display as カズマ
# （……うわぁ。\n　見ちゃいけないものを見た気分だ）
199 = "（……うわぁ。\\n　見ちゃいけないものを見た気分だ）"

# カズマ（Ｍ）
# display as カズマ
# （要するに、これはアクシズ教のミサというか\n　集会みたいなものなんだよな？）
224 = "（要するに、これはアクシズ教のミサというか\\n　集会みたいなものなんだよな？）"

# カズマ（Ｍ）
# display as カズマ
# （それで、アクアが教祖として崇められ、\n　色々な物を供物として受け取っていた、と）
208 = "（それで、アクアが教祖として崇められ、\\n　色々な物を供物として受け取っていた、と）"

# カズマ（Ｍ）
# display as カズマ
# （なるほどな。\n　アクアがやたら上機嫌だったのも、あれだけの\n　高級品を手に入れてた理由もわかったが……）
215 = "（なるほどな。\\n　アクアがやたら上機嫌だったのも、あれだけの\\n　高級品を手に入れてた理由もわかったが……）"

# カズマ（Ｍ）
# display as カズマ
# （嫌な予感は消えない。\n　むしろ、大きくなっていくような……）
222 = "（嫌な予感は消えない。\\n　むしろ、大きくなっていくような……）"

# カズマ
# …………。
161 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （よし！\n　俺はなにも見なかったことにしよう！\n　面倒事に巻き込まれるのは嫌だからな！）
219 = "（よし！\\n　俺はなにも見なかったことにしよう！\\n　面倒事に巻き込まれるのは嫌だからな！）"

# カズマ（Ｍ）
# display as カズマ
# （さあ、帰ろう！\n　帰って寝ちまおう！）
205 = "（さあ、帰ろう！\\n　帰って寝ちまおう！）"

