# root_a03.txt.scn

[info]
0 = ""

[characters]
299 = "カズマ"
296 = "めぐみん"
301 = "ダクネス"
300 = "カズマ（Ｍ）"
298 = "アクア"

[character_subs]
# 299 = "カズマ"

[script]
# lines: 66

# カズマ
# 戻ったぞー。
316 = "戻ったぞー。"

# めぐみん
# ただいま戻りました。
281 = "ただいま戻りました。"

# ダクネス
# ああ、おかえり。\n爆裂魔法の練習はどうだった。
256 = "ああ、おかえり。\\n爆裂魔法の練習はどうだった。"

# めぐみん
# ３０点といったところですね。
364 = "３０点といったところですね。"

# カズマ
# 今日は標的を意識しすぎたな。
306 = "今日は標的を意識しすぎたな。"

# めぐみん
# ええ、火柱の形状、四散する爆風の威力と熱、\n爆音も低音が不足してましたし、\n惨たんたる結果とはこのことですよ。
266 = "ええ、火柱の形状、四散する爆風の威力と熱、\\n爆音も低音が不足してましたし、\\n惨たんたる結果とはこのことですよ。"

# ダクネス
# よく分からないが、\n爆裂魔法と言っても色々あるのだな。
297 = "よく分からないが、\\n爆裂魔法と言っても色々あるのだな。"

# めぐみん
# そうなんですよ、ダクネス！\nそれが爆裂道の奥深い所なんです！
279 = "そうなんですよ、ダクネス！\\nそれが爆裂道の奥深い所なんです！"

# ダクネス
# そ、そうなのか。
277 = "そ、そうなのか。"

# カズマ
# あー、腹減った。\n今日の夕飯の当番は誰だったっけ？
259 = "あー、腹減った。\\n今日の夕飯の当番は誰だったっけ？"

# めぐみん
# 確かアクアですね。
353 = "確かアクアですね。"

# ダクネス
# だが、アクアはまだ帰ってきていないぞ。
283 = "だが、アクアはまだ帰ってきていないぞ。"

# カズマ
# マジか……。
303 = "マジか……。"

# めぐみん
# 私もう、お腹と背中がくっつきそうです。
355 = "私もう、お腹と背中がくっつきそうです。"

# カズマ
# まったく、どこ行ったんだ？\n今まで朝から晩まで外出なんて\n滅多にしなかったのに。
295 = "まったく、どこ行ったんだ？\\n今まで朝から晩まで外出なんて\\n滅多にしなかったのに。"

# ダクネス
# 少し心配だな。\n妙なトラブルに巻き込まれていなければ\nいいのだが。
313 = "少し心配だな。\\n妙なトラブルに巻き込まれていなければ\\nいいのだが。"

# カズマ
# いや、あいつは自分からトラブル呼び込むだろ。
260 = "いや、あいつは自分からトラブル呼び込むだろ。"

# カズマ（Ｍ）
# display as カズマ
# （……待て、そう考えると、\n　心配と言うか不安になってくるな。\n　また変なトラブルを持ち込んで来るんじゃ？）
358 = "（……待て、そう考えると、\\n　心配と言うか不安になってくるな。\\n　また変なトラブルを持ち込んで来るんじゃ？）"

# アクア
# ただまー。
282 = "ただまー。"

# カズマ（Ｍ）
# display as カズマ
# （お、噂をすればなんとやらだ）
361 = "（お、噂をすればなんとやらだ）"

# アクア
# ちょっとー、誰か来てくれないかしら。\n運んで欲しい物があるんですけどー。
286 = "ちょっとー、誰か来てくれないかしら。\\n運んで欲しい物があるんですけどー。"

# カズマ（Ｍ）
# display as カズマ
# （あ？　なんだよいったい）
359 = "（あ？　なんだよいったい）"

# ダクネス
# おかえり、アクア。\n運んで欲しい物というのは、この袋のことか？
269 = "おかえり、アクア。\\n運んで欲しい物というのは、この袋のことか？"

# めぐみん
# 凄い量ですね。\n中身はなんなんです？
310 = "凄い量ですね。\\n中身はなんなんです？"

# アクア
# ふふん、気になる？\n気になるわよね？
293 = "ふふん、気になる？\\n気になるわよね？"

# カズマ
# いや別に。\nじゃあ、俺は風呂に入ってくるわ。
262 = "いや別に。\\nじゃあ、俺は風呂に入ってくるわ。"

# アクア
# あらあ、そんなことを言っちゃっていいのかしら？
257 = "あらあ、そんなことを言っちゃっていいのかしら？"

# カズマ（Ｍ）
# display as カズマ
# （なんだ？　ずいぶんと強気だな）
362 = "（なんだ？　ずいぶんと強気だな）"

# アクア
# さあ、見て驚きなさい！\nじゃじゃーん！！
274 = "さあ、見て驚きなさい！\\nじゃじゃーん！！"

# カズマ
# うおおっ！？　これはまさか！
264 = "うおおっ！？　これはまさか！"

# めぐみん
# 見事な霜降り赤ガニじゃないですか！
357 = "見事な霜降り赤ガニじゃないですか！"

# ダクネス
# 以前、実家から送られてきた物にも\n引けを取らないぞ。
308 = "以前、実家から送られてきた物にも\\n引けを取らないぞ。"

# アクア
# 今日は私が夕飯の当番だったわよね。
307 = "今日は私が夕飯の当番だったわよね。"

# めぐみん
# はっ、まさか！
291 = "はっ、まさか！"

# アクア
# そう、今日の夕飯は……。
278 = "そう、今日の夕飯は……。"

# めぐみん
# きょ、今日の夕飯は……。
271 = "きょ、今日の夕飯は……。"

# アクア
# この霜降り赤ガニよ！
272 = "この霜降り赤ガニよ！"

# めぐみん
# うおおおおおお！　マジですか！
263 = "うおおおおおお！　マジですか！"

# アクア
# さあ、カズマ。\n私に何か言うことがあるんじゃないかしら？
273 = "さあ、カズマ。\\n私に何か言うことがあるんじゃないかしら？"

# カズマ
# お前……なんてことをっ。
270 = "お前……なんてことをっ。"

# アクア
# えっ？
268 = "えっ？"

# カズマ
# どこからかすめてきたんだ。\n今ならまだ遅くないから、返して謝ってこい。
289 = "どこからかすめてきたんだ。\\n今ならまだ遅くないから、返して謝ってこい。"

# アクア
# はあっ！？\nどうしてそうなるのよ！
290 = "はあっ！？\\nどうしてそうなるのよ！"

# ダクネス
# 今の我々の経済状態で、\nこんな物を買えるわけがないだろう。
305 = "今の我々の経済状態で、\\nこんな物を買えるわけがないだろう。"

# めぐみん
# ええ？\nもしかして、これは食べられないんですか？
267 = "ええ？\\nもしかして、これは食べられないんですか？"

# ダクネス
# 残念だが仕方ない。\nこれに手をつけたら同罪だ。
317 = "残念だが仕方ない。\\nこれに手をつけたら同罪だ。"

# アクア
# ま、待ってよ！\nどうして最初から非合法な手段で\n手に入れたことになってるの！？
294 = "ま、待ってよ！\\nどうして最初から非合法な手段で\\n手に入れたことになってるの！？"

# カズマ
# じゃあ聞こう。\nこんな高価な物を、しかもこんなに大量に\nどうやって手に入れた。
276 = "じゃあ聞こう。\\nこんな高価な物を、しかもこんなに大量に\\nどうやって手に入れた。"

# アクア
# ちょっとした臨時収入があったのよ。
284 = "ちょっとした臨時収入があったのよ。"

# カズマ
# 臨時収入だと？
356 = "臨時収入だと？"

# アクア
# そうよ、このアクア様の名においてね。
280 = "そうよ、このアクア様の名においてね。"

# カズマ（Ｍ）
# display as カズマ
# （アクアの名において？）
363 = "（アクアの名において？）"

# カズマ
# つまり、お布施みたいなものがあったと？
287 = "つまり、お布施みたいなものがあったと？"

# アクア
# ええ、そんな感じ。\nこれでわかったでしょ？\n別に後ろめたい物じゃないって。
265 = "ええ、そんな感じ。\\nこれでわかったでしょ？\\n別に後ろめたい物じゃないって。"

# めぐみん
# じゃあ、これは食べられるんですね！
275 = "じゃあ、これは食べられるんですね！"

# アクア
# 焼いても良し、煮ても良し、\nもちろん生で食べても良し。\nめぐみんはどれがお好みかしら。
319 = "焼いても良し、煮ても良し、\\nもちろん生で食べても良し。\\nめぐみんはどれがお好みかしら。"

# めぐみん
# 全部です、全部！
309 = "全部です、全部！"

# アクア
# あらあら、めぐみん。\n強欲は大罪よ。
258 = "あらあら、めぐみん。\\n強欲は大罪よ。"

# めぐみん
# ふっ、この霜降り赤ガニを食べられるならば、\n悪魔にでも魂を差し出そうではないか。
292 = "ふっ、この霜降り赤ガニを食べられるならば、\\n悪魔にでも魂を差し出そうではないか。"

# アクア
# いやいや、それは女神として見逃せないから。
261 = "いやいや、それは女神として見逃せないから。"

# ダクネス
# では、アクア。\n居間に運んでしまうぞ。
288 = "では、アクア。\\n居間に運んでしまうぞ。"

# めぐみん
# ダクネス、私も手伝います！
302 = "ダクネス、私も手伝います！"

# アクア
# 私はお鍋とかの用意をしちゃうわね。\nほら、カズマも手伝って。
354 = "私はお鍋とかの用意をしちゃうわね。\\nほら、カズマも手伝って。"

# カズマ（Ｍ）
# display as カズマ
# （うーん、お布施ね……）
360 = "（うーん、お布施ね……）"

# アクア
# ちょっとカズマ、聞いてるの？
285 = "ちょっとカズマ、聞いてるの？"

# カズマ
# あ、ああ、わかったよ。
255 = "あ、ああ、わかったよ。"

