# root_d10.txt.scn

[info]
0 = ""

[characters]
180 = "盗賊風の男冒険者"
178 = "戦士風の男冒険者"
181 = "魔術師風の女冒険者"
168 = "カズマ"
170 = "クリス"
169 = "カズマ（Ｍ）"

[character_subs]
179 = "盗賊冒険者"
177 = "戦士冒険者"
175 = "女冒険者"
# 168 = "カズマ"

[script]
# lines: 52

# 盗賊風の男冒険者
# display as 盗賊冒険者
# おい、いたか？
141 = "おい、いたか？"

# 戦士風の男冒険者
# display as 戦士冒険者
# いや、見当たらない。\nどこに行ったんだ！
137 = "いや、見当たらない。\\nどこに行ったんだ！"

# 魔術師風の女冒険者
# display as 女冒険者
# こっちに逃げたのは間違いないんだけど……。
146 = "こっちに逃げたのは間違いないんだけど……。"

# カズマ
# ……行ったか？
134 = "……行ったか？"

# クリス
# ちょっと、キミ！\nくっつきすぎ！
159 = "ちょっと、キミ！\\nくっつきすぎ！"

# カズマ
# 仕方ないだろ、狭いんだから。\n少しくらい我慢しろよ。
172 = "仕方ないだろ、狭いんだから。\\n少しくらい我慢しろよ。"

# クリス
# それは分かってるけど……\nあ、こ、こら！\nどさくさに紛れて変な所を触らないでよっ！！
154 = "それは分かってるけど……\\nあ、こ、こら！\\nどさくさに紛れて変な所を触らないでよっ！！"

# カズマ
# さささ、触ってねえし！
150 = "さささ、触ってねえし！"

# クリス
# あー、もう、離れてったら！
136 = "あー、もう、離れてったら！"

# カズマ
# てか動くな、いえ、動かないでください。\n本当にもう男の子は大変なんですから！
160 = "てか動くな、いえ、動かないでください。\\n本当にもう男の子は大変なんですから！"

# クリス
# うっ……。
140 = "うっ……。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、もう、童貞には刺激的な\n　シチュエーションすぎる！）
183 = "（ああ、もう、童貞には刺激的な\\n　シチュエーションすぎる！）"

# カズマ（Ｍ）
# display as カズマ
# （唯一の救いは、クリスの胸が残念なくらいで……）
192 = "（唯一の救いは、クリスの胸が残念なくらいで……）"

# カズマ（Ｍ）
# display as カズマ
# （これがもし、ダクネスやウィズだったらって\n　考えると……うへへ）
185 = "（これがもし、ダクネスやウィズだったらって\\n　考えると……うへへ）"

# クリス
# 今なんか、変なこと考えたでしょ。
171 = "今なんか、変なこと考えたでしょ。"

# カズマ（Ｍ）
# display as カズマ
# （さすが盗賊、勘がいいですね！）
186 = "（さすが盗賊、勘がいいですね！）"

# クリス
# ちょ、ちょっと足を動かさないでったら！
158 = "ちょ、ちょっと足を動かさないでったら！"

# カズマ
# 体勢がキツいんだって。\n少しくらい我慢してくれよ。
173 = "体勢がキツいんだって。\\n少しくらい我慢してくれよ。"

# クリス
# そうは言うけど、これ以上動かされたら！
152 = "そうは言うけど、これ以上動かされたら！"

# カズマ
# お前こそもぞもぞ動くな！
144 = "お前こそもぞもぞ動くな！"

# クリス
# だって、動かないとカズマが密着しようと\nするんだもん！
156 = "だって、動かないとカズマが密着しようと\\nするんだもん！"

# カズマ
# してねえって！
151 = "してねえって！"

# クリス
# あっ、今、チラッと見たでしょ！
135 = "あっ、今、チラッと見たでしょ！"

# カズマ
# どこを！
161 = "どこを！"

# クリス
# む、む、胸だよ……もう、カズマのエッチ！
165 = "む、む、胸だよ……もう、カズマのエッチ！"

# カズマ（Ｍ）
# display as カズマ
# （ドストライク！\n　その仕草と台詞、俺のドストライク！）
190 = "（ドストライク！\\n　その仕草と台詞、俺のドストライク！）"

# クリス
# ねえ、カズマ。\n何か心当たりないの？
163 = "ねえ、カズマ。\\n何か心当たりないの？"

# カズマ
# 心当たり？
176 = "心当たり？"

# クリス
# このクエスト発注した人の心当たり。
147 = "このクエスト発注した人の心当たり。"

# カズマ
# それは……あると言えばあるような？
153 = "それは……あると言えばあるような？"

# クリス
# 何それ？\nあるの？　ないの？
174 = "何それ？\\nあるの？　ないの？"

# カズマ（Ｍ）
# display as カズマ
# （当てはまるのは、\n　俺がクリスを探していたことを知っている人間）
193 = "（当てはまるのは、\\n　俺がクリスを探していたことを知っている人間）"

# カズマ（Ｍ）
# display as カズマ
# （さらに絞り込むとすれば、\n　クエストが掲示される前に俺がクリスを\n　探していた事実を知っている奴になる）
187 = "（さらに絞り込むとすれば、\\n　クエストが掲示される前に俺がクリスを\\n　探していた事実を知っている奴になる）"

# カズマ（Ｍ）
# display as カズマ
# （つまり、俺がクリスを探し始めた昨日、\n　探索途中に出会った人物……）
188 = "（つまり、俺がクリスを探し始めた昨日、\\n　探索途中に出会った人物……）"

# カズマ（Ｍ）
# display as カズマ
# （俺が昨日、クリスを探していると\n　はっきり言った相手は２人だけ。\n　アクアとめぐみん、だ）
191 = "（俺が昨日、クリスを探していると\\n　はっきり言った相手は２人だけ。\\n　アクアとめぐみん、だ）"

# カズマ（Ｍ）
# display as カズマ
# （状況から考えるに、今回の騒動の犯人は\n　あいつらのどっちかだと見て間違いない）
194 = "（状況から考えるに、今回の騒動の犯人は\\n　あいつらのどっちかだと見て間違いない）"

# クリス
# ん、んー……。
167 = "ん、んー……。"

# カズマ
# おい、なんだよクリス。\n変な声出すな！　男の子は敏感だぞ！
142 = "おい、なんだよクリス。\\n変な声出すな！　男の子は敏感だぞ！"

# クリス
# う、うん。ごめん。\nわかってるんだけど、その……。
139 = "う、うん。ごめん。\\nわかってるんだけど、その……。"

# カズマ（Ｍ）
# display as カズマ
# （あれ？　なんで顔赤くしてるんだ？\n　しかも、モジモジして太ももをすり合わせて……\n　あ、もしかして）
184 = "（あれ？　なんで顔赤くしてるんだ？\\n　しかも、モジモジして太ももをすり合わせて……\\n　あ、もしかして）"

# カズマ
# なあ、まさかとは思うが……トイレか？
162 = "なあ、まさかとは思うが……トイレか？"

# クリス
# き、聞かないでったら！\nデリカシーないなぁ、キミって人は！
145 = "き、聞かないでったら！\\nデリカシーないなぁ、キミって人は！"

# カズマ
# この状況でもよおすなよ……。
148 = "この状況でもよおすなよ……。"

# クリス
# そんなこと言っても仕方ないでしょ、\n生理現象なんだからっ！
155 = "そんなこと言っても仕方ないでしょ、\\n生理現象なんだからっ！"

# カズマ
# ば、バカ！　声が大きいっ！\n見つかったらどうすんだ！
164 = "ば、バカ！　声が大きいっ！\\n見つかったらどうすんだ！"

# クリス
# ご、ごめん。
149 = "ご、ごめん。"

# カズマ（Ｍ）
# display as カズマ
# （……どうする？\n　このままじゃ俺はともかく\n　クリスの人としての尊厳が危うくなる）
182 = "（……どうする？\\n　このままじゃ俺はともかく\\n　クリスの人としての尊厳が危うくなる）"

# カズマ（Ｍ）
# display as カズマ
# （できれば街から離れて\n　制限時間までやり過ごしたかったんだが……\n　この状況じゃ、そういう訳にもいかないか）
189 = "（できれば街から離れて\\n　制限時間までやり過ごしたかったんだが……\\n　この状況じゃ、そういう訳にもいかないか）"

# クリス
# う、うう、カズマ、どうしよう……！
138 = "う、うう、カズマ、どうしよう……！"

# カズマ
# おい、クリス。\nもうちょっとだけ我慢できるか？
143 = "おい、クリス。\\nもうちょっとだけ我慢できるか？"

# クリス
# ちょ、ちょっとだけなら、なんとか。
157 = "ちょ、ちょっとだけなら、なんとか。"

# カズマ
# わかった。\nじゃあ、とりあえず俺達の屋敷に行こう。
166 = "わかった。\\nじゃあ、とりあえず俺達の屋敷に行こう。"

