# root_e11.txt.scn

[info]
0 = ""

[characters]
333 = "カズマ（Ｍ）"
329 = "アクア"
331 = "カズマ"
322 = "ゆんゆん"
335 = "ダクネス"
317 = "めぐみん"

[character_subs]
# 331 = "カズマ"

[script]
# lines: 81

# カズマ（Ｍ）
# display as カズマ
# （あれから数日。\n　ゆんゆんは、相変わらずこの屋敷に住んで\n　めぐみんを観察している――）
414 = "（あれから数日。\\n　ゆんゆんは、相変わらずこの屋敷に住んで\\n　めぐみんを観察している――）"

# カズマ（Ｍ）
# display as カズマ
# （いや、していないのかもしれない。\n　そんな暇はなさそうだったからな）
415 = "（いや、していないのかもしれない。\\n　そんな暇はなさそうだったからな）"

# カズマ（Ｍ）
# display as カズマ
# （というのも、うちの駄女神が\n　すっかり調子に乗って\n　やりたい放題グータラしているからだ）
418 = "（というのも、うちの駄女神が\\n　すっかり調子に乗って\\n　やりたい放題グータラしているからだ）"

# アクア
# カズマ、おはよう。\n遅いじゃない、もう昼よ？\n本当だらしないんだから。
332 = "カズマ、おはよう。\\n遅いじゃない、もう昼よ？\\n本当だらしないんだから。"

# カズマ
# ……昼間からゴロゴロ寝転がってる\nお前にだけは言われたくない。
283 = "……昼間からゴロゴロ寝転がってる\\nお前にだけは言われたくない。"

# アクア
# えー？\nこんないい天気の日は、家の中でゴロゴロしながら\nおやつを食べるのが最高じゃない。
293 = "えー？\\nこんないい天気の日は、家の中でゴロゴロしながら\\nおやつを食べるのが最高じゃない。"

# カズマ（Ｍ）
# display as カズマ
# （……もう言葉もないな、このグータラぶり）
410 = "（……もう言葉もないな、このグータラぶり）"

# カズマ
# ところで、他のみんなは？
308 = "ところで、他のみんなは？"

# アクア
# めぐみんとダクネスは出かけてったわよ。\nゆんゆんは私の部屋を掃除中。
319 = "めぐみんとダクネスは出かけてったわよ。\\nゆんゆんは私の部屋を掃除中。"

# カズマ
# お前、またゆんゆんをこき使って……。
297 = "お前、またゆんゆんをこき使って……。"

# アクア
# 言い掛かりをつけないで欲しいんですけど。\nカズマだって知ってるでしょ？\nゆんゆんも喜んでしてくれてるって。
406 = "言い掛かりをつけないで欲しいんですけど。\\nカズマだって知ってるでしょ？\\nゆんゆんも喜んでしてくれてるって。"

# アクア
# 私は楽ができて幸せ。\nゆんゆんは頼りにされて幸せ。\nＷｉｎ－Ｗｉｎで最高じゃない。
404 = "私は楽ができて幸せ。\\nゆんゆんは頼りにされて幸せ。\\nＷｉｎ－Ｗｉｎで最高じゃない。"

# カズマ（Ｍ）
# display as カズマ
# （こ、この駄女神が……！）
416 = "（こ、この駄女神が……！）"

# ゆんゆん
# アクアさん、部屋の掃除終わりました。
330 = "アクアさん、部屋の掃除終わりました。"

# アクア
# あら、ご苦労様。\nそれじゃ、何か用ができるまで\n適当に休んでてちょうだい。
288 = "あら、ご苦労様。\\nそれじゃ、何か用ができるまで\\n適当に休んでてちょうだい。"

# ゆんゆん
# はい、そうさせてもらいますね。
310 = "はい、そうさせてもらいますね。"

# カズマ
# ……ゆんゆん。\nちょっといいか？
281 = "……ゆんゆん。\\nちょっといいか？"

# ゆんゆん
# え？　なんでしょうか？\nカズマさんの部屋も掃除しますか？
294 = "え？　なんでしょうか？\\nカズマさんの部屋も掃除しますか？"

# カズマ
# そうじゃなくて！
303 = "そうじゃなくて！"

# カズマ
# ゆんゆん、アクアはお前を\n頼りにしてるんじゃなくて、利用してるだけだ。\n少し冷静になった方がいいんじゃないか？
323 = "ゆんゆん、アクアはお前を\\n頼りにしてるんじゃなくて、利用してるだけだ。\\n少し冷静になった方がいいんじゃないか？"

# ゆんゆん
# 心配してくださって\nありがとうございます。\nでも、大丈夫です。
354 = "心配してくださって\\nありがとうございます。\\nでも、大丈夫です。"

# ゆんゆん
# ここに来てから１週間、\nみなさんのことを観察させてもらいました。
299 = "ここに来てから１週間、\\nみなさんのことを観察させてもらいました。"

# カズマ（Ｍ）
# display as カズマ
# （あ、ちゃんと観察してたのか。\n　案外、余裕があったんだな）
412 = "（あ、ちゃんと観察してたのか。\\n　案外、余裕があったんだな）"

# ゆんゆん
# めぐみんのことを知るためには、\n本人だけを見ていても意味はありません。
320 = "めぐみんのことを知るためには、\\n本人だけを見ていても意味はありません。"

# ゆんゆん
# 周りの人達や環境も\n考えの中に入れないと、勝てませんから。
349 = "周りの人達や環境も\\n考えの中に入れないと、勝てませんから。"

# ゆんゆん
# それで、観察を続けるうちに\n気付いたことがあるんですけど……。
305 = "それで、観察を続けるうちに\\n気付いたことがあるんですけど……。"

# ゆんゆん
# あの、ちょっと言いにくいんですが……\nこんな状況でいいんでしょうか？
287 = "あの、ちょっと言いにくいんですが……\\nこんな状況でいいんでしょうか？"

# ゆんゆん
# 私は、頼りにされることも\n働くことも嫌いじゃないですけど、\nなんというか……自堕落すぎませんか？
403 = "私は、頼りにされることも\\n働くことも嫌いじゃないですけど、\\nなんというか……自堕落すぎませんか？"

# カズマ（Ｍ）
# display as カズマ
# （ああ、１週間かけて\n　ようやくそこに気付いてくれたか！）
413 = "（ああ、１週間かけて\\n　ようやくそこに気付いてくれたか！）"

# カズマ
# ああ、俺もそう思ってる。\n人のことは言えんが、特にアクアがダメだ。\nあいつは放っておいたら延々と続けるぞ。
285 = "ああ、俺もそう思ってる。\\n人のことは言えんが、特にアクアがダメだ。\\nあいつは放っておいたら延々と続けるぞ。"

# ゆんゆん
# 肝心のめぐみんも、\n訓練以外での外出を見たことがありません。\n今日は、朝から出かけているようですけど……。
405 = "肝心のめぐみんも、\\n訓練以外での外出を見たことがありません。\\n今日は、朝から出かけているようですけど……。"

# ゆんゆん
# その、私が言うのも変ですけど、\nもっときちんと冒険者らしくしてはどうでしょう？
304 = "その、私が言うのも変ですけど、\\nもっときちんと冒険者らしくしてはどうでしょう？"

# ゆんゆん
# せっかく、めぐみんという\n凄い魔法使いがパーティーにいるのに、\nもったいないです。
301 = "せっかく、めぐみんという\\n凄い魔法使いがパーティーにいるのに、\\nもったいないです。"

# カズマ（Ｍ）
# display as カズマ
# （……俺から言わせれば、\n　めぐみんよりゆんゆんの方が優秀だけどな）
411 = "（……俺から言わせれば、\\n　めぐみんよりゆんゆんの方が優秀だけどな）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、凄いは凄いんだろうけど、\n　明らかに力の使いどころを間違ってるし）
419 = "（まあ、凄いは凄いんだろうけど、\\n　明らかに力の使いどころを間違ってるし）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、もっときちんと冒険者らしくかぁ。\n　耳が痛いぜ……）
417 = "（しかし、もっときちんと冒険者らしくかぁ。\\n　耳が痛いぜ……）"

# ゆんゆん
# あ、あの、それと……\n私も、パーティーのみんなと\n仲良く冒険をしてみたいかなって……。
284 = "あ、あの、それと……\\n私も、パーティーのみんなと\\n仲良く冒険をしてみたいかなって……。"

# カズマ（Ｍ）
# display as カズマ
# （……どっちかっていうとそれが本音か？）
409 = "（……どっちかっていうとそれが本音か？）"

# ダクネス
# ゆんゆんの言うとおりだ！
325 = "ゆんゆんの言うとおりだ！"

# ゆんゆん
# ひゃあっ！？
312 = "ひゃあっ！？"

# カズマ
# うおおっ！？\nだ、ダクネス！？
290 = "うおおっ！？\\nだ、ダクネス！？"

# ダクネス
# 我々は、平和に毒され腑抜けになっていた。\nこれでは来たるべく決戦の日に、\n為す術なくやられてしまうに違いない。
355 = "我々は、平和に毒され腑抜けになっていた。\\nこれでは来たるべく決戦の日に、\\n為す術なくやられてしまうに違いない。"

# ダクネス
# よって自堕落はもうお終いにしよう！
327 = "よって自堕落はもうお終いにしよう！"

# カズマ
# 来たるべく日っていつだよ？\nていうか、いきなり登場かよ！\n今までどこに行ってたんだ？
356 = "来たるべく日っていつだよ？\\nていうか、いきなり登場かよ！\\n今までどこに行ってたんだ？"

# ダクネス
# めぐみんとギルドまでな。
318 = "めぐみんとギルドまでな。"

# めぐみん
# 動かない敵が相手では面白くありませんからね。\n動く標的に爆裂魔法をお見舞いしにいきますよ！
342 = "動かない敵が相手では面白くありませんからね。\\n動く標的に爆裂魔法をお見舞いしにいきますよ！"

# カズマ
# ……は？\nまさかクエストを受けてきたのか？
279 = "……は？\\nまさかクエストを受けてきたのか？"

# ダクネス
# ああ、街の近くに現れるはぐれ魔物の退治だ。\nリハビリには丁度いいと思ってな。
286 = "ああ、街の近くに現れるはぐれ魔物の退治だ。\\nリハビリには丁度いいと思ってな。"

# ダクネス
# やはり冒険者たる者、\nいついかなる時も対応出来るよう\n日々鍛え抜かなくては。
321 = "やはり冒険者たる者、\\nいついかなる時も対応出来るよう\\n日々鍛え抜かなくては。"

# ゆんゆん
# そ、そうですよね！\nダクネスさんは真面目な人ですね！
302 = "そ、そうですよね！\\nダクネスさんは真面目な人ですね！"

# カズマ（Ｍ）
# display as カズマ
# （……ああ、その幻想は\n　すぐに死ぬことになるぜ、ゆんゆん）
408 = "（……ああ、その幻想は\\n　すぐに死ぬことになるぜ、ゆんゆん）"

# ダクネス
# さあ、速やかに準備を済ませて\nクエストに向かおう！
300 = "さあ、速やかに準備を済ませて\\nクエストに向かおう！"

# カズマ
# 勝手に受けてくるなよ。\nこっちにも予定ってもんがあるんだぞ？
344 = "勝手に受けてくるなよ。\\nこっちにも予定ってもんがあるんだぞ？"

# めぐみん
# ほう？\nでは、カズマはこれからどのような予定が？
314 = "ほう？\\nでは、カズマはこれからどのような予定が？"

# カズマ
# ……いや、今日は奇跡的になにもないけど。
277 = "……いや、今日は奇跡的になにもないけど。"

# ダクネス
# では問題ないということか？
307 = "では問題ないということか？"

# カズマ
# ……そういうことだな。
278 = "……そういうことだな。"

# カズマ
# 引き受けちまったもんはしょうがない。\n気合いを入れるか。
353 = "引き受けちまったもんはしょうがない。\\n気合いを入れるか。"

# ゆんゆん
# はい！
311 = "はい！"

# ダクネス
# うむ、ふたりともやる気満々だな。\nいいことだ。
291 = "うむ、ふたりともやる気満々だな。\\nいいことだ。"

# めぐみん
# ゆんゆん、気合を入れすぎて\n足を引っ張らないでくださいよ？
324 = "ゆんゆん、気合を入れすぎて\\n足を引っ張らないでくださいよ？"

# ゆんゆん
# わかってるったら！
328 = "わかってるったら！"

# カズマ
# 冒険者らしく行くか！
341 = "冒険者らしく行くか！"

# ダクネス
# ほう、やる気満々じゃないか。
313 = "ほう、やる気満々じゃないか。"

# カズマ
# まあな。\nゆんゆんの忠告もあったし。
316 = "まあな。\\nゆんゆんの忠告もあったし。"

# めぐみん
# ゆんゆんの？\nなんです、それは。
326 = "ゆんゆんの？\\nなんです、それは。"

# ゆんゆん
# た、たいしたことじゃないよ。\n気にしないで。
306 = "た、たいしたことじゃないよ。\\n気にしないで。"

# めぐみん
# ……ふーん。
280 = "……ふーん。"

# カズマ
# ほら、アクア。\n準備しろ。
315 = "ほら、アクア。\\n準備しろ。"

# アクア
# え？　何するの？
295 = "え？　何するの？"

# カズマ
# クエストに向かうんだよ。
334 = "クエストに向かうんだよ。"

# アクア
# え～、面倒くさい。\n今日はダラダラするって決めてるんですけど？
296 = "え～、面倒くさい。\\n今日はダラダラするって決めてるんですけど？"

# カズマ
# 今日もだろうが！\nいいから行くぞ、このヒキニート。
337 = "今日もだろうが！\\nいいから行くぞ、このヒキニート。"

# アクア
# 誰がヒキニートですって！？
407 = "誰がヒキニートですって！？"

# カズマ
# お前しかいないだろ？\nまあ、お前がいなくても問題ないけどな。\nむしろ足を引っ張られずにすんでいいか？
298 = "お前しかいないだろ？\\nまあ、お前がいなくても問題ないけどな。\\nむしろ足を引っ張られずにすんでいいか？"

# カズマ
# うん、そうだな、その可能性は非常に高い。\nお前は留守番でいいぞ。
292 = "うん、そうだな、その可能性は非常に高い。\\nお前は留守番でいいぞ。"

# アクア
# なっ！？　ふざけるんじゃないわよ！\nこのアクア様の実力を見せてあげようじゃない！
309 = "なっ！？　ふざけるんじゃないわよ！\\nこのアクア様の実力を見せてあげようじゃない！"

# ゆんゆん
# ……上手いですね、カズマさん。
282 = "……上手いですね、カズマさん。"

# カズマ
# いや、アクアが単純なだけだ。
289 = "いや、アクアが単純なだけだ。"

# アクア
# 何か言った？
338 = "何か言った？"

# カズマ
# 何も言ってないぞ？\nそれより準備してこい、すぐに出発するぞ！
339 = "何も言ってないぞ？\\nそれより準備してこい、すぐに出発するぞ！"

[selections]
343 = "勝手に受けてくるなよ"
352 = "引き受けちまったもんはしょうがない"
340 = "冒険者らしく行くか"
