# root_f16.txt.scn

[info]
0 = ""

[characters]
136 = "カズマ"
134 = "ウィズ"
137 = "カズマ（Ｍ）"

[character_subs]
# 136 = "カズマ"

[script]
# lines: 15

# カズマ
# ウィズ、来たぜ。
135 = "ウィズ、来たぜ。"

# ウィズ
# あ、カズマさん。\nお待ちしてました。
122 = "あ、カズマさん。\\nお待ちしてました。"

# カズマ
# あれ？　もしかして待たせちゃったか。
126 = "あれ？　もしかして待たせちゃったか。"

# ウィズ
# いえ、ちょうど今、準備が終わったところですよ。
127 = "いえ、ちょうど今、準備が終わったところですよ。"

# カズマ（Ｍ）
# display as カズマ
# （しかし、随分でかいバッグを持ってるな。\n　浄化するのにそんな荷物がいるとも\n　思えないけど、なんだろう？）
151 = "（しかし、随分でかいバッグを持ってるな。\\n　浄化するのにそんな荷物がいるとも\\n　思えないけど、なんだろう？）"

# ウィズ
# あ、カズマさん。\nすみませんが、これだけ持って頂けませんか？
123 = "あ、カズマさん。\\nすみませんが、これだけ持って頂けませんか？"

# カズマ
# ああ、いいよ。
125 = "ああ、いいよ。"

# ウィズ
# ちょっと重いので、気を付けて下さいね。
131 = "ちょっと重いので、気を付けて下さいね。"

# カズマ
# うおお！？\nホントだ、ずっしりくるな。
129 = "うおお！？\\nホントだ、ずっしりくるな。"

# ウィズ
# あ、大変なようでしたら\n自分で持っていきますから。
124 = "あ、大変なようでしたら\\n自分で持っていきますから。"

# カズマ
# いや、この重さはしんどいだろ。\n気にすんなって。
128 = "いや、この重さはしんどいだろ。\\n気にすんなって。"

# カズマ
# それに、除霊のために見回りするのに\n肝心の手が塞がってたら、問題あるだろ？
130 = "それに、除霊のために見回りするのに\\n肝心の手が塞がってたら、問題あるだろ？"

# ウィズ
# では、すみませんが、よろしくお願いします。
132 = "では、すみませんが、よろしくお願いします。"

# カズマ
# 俺はむしろ頼られて嬉しいよ。\nもっとバンバン言いつけてくれ。
139 = "俺はむしろ頼られて嬉しいよ。\\nもっとバンバン言いつけてくれ。"

# ウィズ
# はい、ありがとうございます。
133 = "はい、ありがとうございます。"

