# root_a08.txt.scn

[info]
0 = ""

[characters]
230 = "カズマ（Ｍ）"
229 = "カズマ"
232 = "ダクネス"
221 = "めぐみん"

[character_subs]
# 229 = "カズマ"

[script]
# lines: 49

# カズマ（Ｍ）
# display as カズマ
# （アクアが夜中に出ていく姿を\n　目撃してから数日後――）
274 = "（アクアが夜中に出ていく姿を\\n　目撃してから数日後――）"

# カズマ
# というわけで今日の議題は\nアクアが深夜にどこで何をやっているかだ。
217 = "というわけで今日の議題は\\nアクアが深夜にどこで何をやっているかだ。"

# ダクネス
# あまり他人のプライベートを詮索したくは\nないのだが。
195 = "あまり他人のプライベートを詮索したくは\\nないのだが。"

# めぐみん
# でも、状況が状況ですよ。\n対岸の火事と放っておく訳にもいきません。
215 = "でも、状況が状況ですよ。\\n対岸の火事と放っておく訳にもいきません。"

# カズマ
# 一番面倒なのは、火の粉どころじゃなくて\n大炎上して案件化した何かが予告もなく\n降りかかってくることだからな。
234 = "一番面倒なのは、火の粉どころじゃなくて\\n大炎上して案件化した何かが予告もなく\\n降りかかってくることだからな。"

# カズマ（Ｍ）
# display as カズマ
# （あの日から、アクアは\n　夜に出掛けては\n　朝に帰ってくるようになっていた）
267 = "（あの日から、アクアは\\n　夜に出掛けては\\n　朝に帰ってくるようになっていた）"

# カズマ（Ｍ）
# display as カズマ
# （それで、夜まで寝てから\n　また夜中になって出掛けていくという、\n　その繰り返し）
272 = "（それで、夜まで寝てから\\n　また夜中になって出掛けていくという、\\n　その繰り返し）"

# カズマ（Ｍ）
# display as カズマ
# （さすがに昼夜が逆転すれば、\n　一緒に暮らすめぐみんとダクネスも\n　気がつくというもので――）
270 = "（さすがに昼夜が逆転すれば、\\n　一緒に暮らすめぐみんとダクネスも\\n　気がつくというもので――）"

# カズマ（Ｍ）
# display as カズマ
# （いったいアクアは\n　深夜に外で何をやっているのかと、\n　こうして緊急会議が開かれる運びになったわけだ）
268 = "（いったいアクアは\\n　深夜に外で何をやっているのかと、\\n　こうして緊急会議が開かれる運びになったわけだ）"

# めぐみん
# それで、カズマは、あれをどう見るのです？
209 = "それで、カズマは、あれをどう見るのです？"

# カズマ
# あれなー。
196 = "あれなー。"

# ダクネス
# アクアもいい大人なのだから、\n深夜だろうと外出するのは何も問題ない。\nしかし……。
228 = "アクアもいい大人なのだから、\\n深夜だろうと外出するのは何も問題ない。\\nしかし……。"

# カズマ（Ｍ）
# display as カズマ
# （そう、問題はアクアの部屋に溜め込まれた\n　あれだ）
271 = "（そう、問題はアクアの部屋に溜め込まれた\\n　あれだ）"

# カズマ（Ｍ）
# display as カズマ
# （高級シュワシュワに良くわからん魔道具、\n　そしてアクアの趣味とは思えない衣服類に、\n　なんか怪しい壷やらの調度品）
276 = "（高級シュワシュワに良くわからん魔道具、\\n　そしてアクアの趣味とは思えない衣服類に、\\n　なんか怪しい壷やらの調度品）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスの見立てでは、\n　どれもそれなりに値が張る物らしい）
275 = "（ダクネスの見立てでは、\\n　どれもそれなりに値が張る物らしい）"

# カズマ
# あれについて、\nめぐみんはアクアに問いただしたんだよな？
197 = "あれについて、\\nめぐみんはアクアに問いただしたんだよな？"

# めぐみん
# ええ、でも、眠いからと\nはぐらかされてしまいました
199 = "ええ、でも、眠いからと\\nはぐらかされてしまいました"

# めぐみん
# ですが、あのアクアの態度は、\n明らかに何かを隠していましたね。\n絵に描いたようにうろたえていましたし。
214 = "ですが、あのアクアの態度は、\\n明らかに何かを隠していましたね。\\n絵に描いたようにうろたえていましたし。"

# ダクネス
# アクアは良くも悪くも嘘をつけないからな。
227 = "アクアは良くも悪くも嘘をつけないからな。"

# カズマ
# ひとつだけわかっているのは、\n間違いなく自分の金で買った物じゃない\nということだ。
219 = "ひとつだけわかっているのは、\\n間違いなく自分の金で買った物じゃない\\nということだ。"

# めぐみん
# クエストもバイトもしていませんからね。
231 = "クエストもバイトもしていませんからね。"

# ダクネス
# じゃあ、あの品の数々は\nどう手に入れたというんだ。
205 = "じゃあ、あの品の数々は\\nどう手に入れたというんだ。"

# カズマ
# やっぱ、犯罪だろ。
223 = "やっぱ、犯罪だろ。"

# めぐみん
# でしょうね。
213 = "でしょうね。"

# ダクネス
# お前たち、少しは仲間を信じたらどうなんだ。
201 = "お前たち、少しは仲間を信じたらどうなんだ。"

# カズマ
# じゃあ、ダクネスの意見を訊かせてくれよ。
206 = "じゃあ、ダクネスの意見を訊かせてくれよ。"

# ダクネス
# そ、それは……法に触れないギリギリのラインで\n何かを……。
207 = "そ、それは……法に触れないギリギリのラインで\\n何かを……。"

# カズマ
# アクアはそんな悪知恵を持ち合わせていないだろ。
226 = "アクアはそんな悪知恵を持ち合わせていないだろ。"

# めぐみん
# どんな方法にせよ。\n今のアクアは、後ろ暗い点が多すぎます。
218 = "どんな方法にせよ。\\n今のアクアは、後ろ暗い点が多すぎます。"

# カズマ
# あの浮かれ方もおかしいしな。
194 = "あの浮かれ方もおかしいしな。"

# ダクネス
# そう！　その点が解せないんだ。\n仮に法に触れる何かをやっているのなら、\nあの浮かれ方が説明できない。
208 = "そう！　その点が解せないんだ。\\n仮に法に触れる何かをやっているのなら、\\nあの浮かれ方が説明できない。"

# カズマ
# やっていることが犯罪だと気づいてない\n可能性があるぞ。
222 = "やっていることが犯罪だと気づいてない\\n可能性があるぞ。"

# めぐみん
# アクアですしね。
225 = "アクアですしね。"

# ダクネス
# それは確かに否定をできないな。
211 = "それは確かに否定をできないな。"

# カズマ
# ホント、嫌な予感しかしないんだよ。\nアクアがあんな感じで浮かれてると、\n大抵、足元を掬われるだろ？
233 = "ホント、嫌な予感しかしないんだよ。\\nアクアがあんな感じで浮かれてると、\\n大抵、足元を掬われるだろ？"

# ダクネス
# しかし、何も証拠がないのでは、\nアクアの行動を咎めることもできない。
204 = "しかし、何も証拠がないのでは、\\nアクアの行動を咎めることもできない。"

# めぐみん
# それならば、その証拠を掴むまで！
210 = "それならば、その証拠を掴むまで！"

# カズマ
# おい、火に油をぶちまけるつもりか……。
200 = "おい、火に油をぶちまけるつもりか……。"

# ダクネス
# だが、このまま放っておいたら\n間違いなく大火事になるぞ。
212 = "だが、このまま放っておいたら\\n間違いなく大火事になるぞ。"

# カズマ（Ｍ）
# display as カズマ
# （それもそうなんだよな……）
273 = "（それもそうなんだよな……）"

# めぐみん
# というわけで、\n今夜さっそくアクアを尾行しましょう！
216 = "というわけで、\\n今夜さっそくアクアを尾行しましょう！"

# カズマ
# いや、俺１人で行くよ。\n３人だと目立つし、俺なら潜伏スキルを\n使えるしな。
198 = "いや、俺１人で行くよ。\\n３人だと目立つし、俺なら潜伏スキルを\\n使えるしな。"

# めぐみん
# さては、楽しみを独り占めする気ですね！
203 = "さては、楽しみを独り占めする気ですね！"

# カズマ
# こんなことが楽しいって思えるなら、\nめぐみんが１人でやればいいだろ！
202 = "こんなことが楽しいって思えるなら、\\nめぐみんが１人でやればいいだろ！"

# めぐみん
# 嫌ですよ！\n深夜に１人で歩き回るなんて怖いじゃないですか。
237 = "嫌ですよ！\\n深夜に１人で歩き回るなんて怖いじゃないですか。"

# カズマ（Ｍ）
# display as カズマ
# （このお子様めっ！）
269 = "（このお子様めっ！）"

# ダクネス
# まあ、ここはカズマに任せよう。
220 = "まあ、ここはカズマに任せよう。"

# めぐみん
# わかりました……。
224 = "わかりました……。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、くだらないことに首を突っ込んでなければ\n　いいんだけど……）
266 = "（ああ、くだらないことに首を突っ込んでなければ\\n　いいんだけど……）"

