# root_d02.txt.scn

[info]
0 = ""

[characters]
236 = "カズマ（Ｍ）"
235 = "カズマ"
234 = "ウィズ"
237 = "クリス"

[character_subs]
# 235 = "カズマ"

[script]
# lines: 58

# カズマ（Ｍ）
# display as カズマ
# （スカルドラゴン討伐、\n　そして俺の呪われた指輪の事件が\n　解決してから数日――）
295 = "（スカルドラゴン討伐、\\n　そして俺の呪われた指輪の事件が\\n　解決してから数日――）"

# カズマ（Ｍ）
# display as カズマ
# （俺は、呪いから解放された\n　喜びを噛み締めつつも、\n　とある行動に勤しんでいた）
296 = "（俺は、呪いから解放された\\n　喜びを噛み締めつつも、\\n　とある行動に勤しんでいた）"

# カズマ
# なあウィズ、本当に何もしなくてもいいのか？
226 = "なあウィズ、本当に何もしなくてもいいのか？"

# ウィズ
# はい、お気になさらず。\n下着を盗んでいたのはカズマさんの\n意思ではないと、わかっていますし。
228 = "はい、お気になさらず。\\n下着を盗んでいたのはカズマさんの\\n意思ではないと、わかっていますし。"

# カズマ
# 遠慮なんてしなくていいんだぞ？\nウィズは俺からお詫びを受け取って当然の被害を\n受けたんだからさ。
286 = "遠慮なんてしなくていいんだぞ？\\nウィズは俺からお詫びを受け取って当然の被害を\\n受けたんだからさ。"

# ウィズ
# 被害だなんて思っていませんよ。\n今思い返せば、あれはあれで楽しい毎日でしたし。
284 = "被害だなんて思っていませんよ。\\n今思い返せば、あれはあれで楽しい毎日でしたし。"

# カズマ
# はっ！\nまさかウィズ、そういうのに目覚めて……。
230 = "はっ！\\nまさかウィズ、そういうのに目覚めて……。"

# ウィズ
# ち、違いますよ！
222 = "ち、違いますよ！"

# カズマ
# ははは、わかってるって。
231 = "ははは、わかってるって。"

# カズマ（Ｍ）
# display as カズマ
# （さて、あとはクリスだけなんだけど\n　あいつは基本、所在が不明なんだよな）
288 = "（さて、あとはクリスだけなんだけど\\n　あいつは基本、所在が不明なんだよな）"

# カズマ（Ｍ）
# display as カズマ
# （とりあえず酒場で情報を集めて、\n　それでダメならダクネスに聞いてみるか）
292 = "（とりあえず酒場で情報を集めて、\\n　それでダメならダクネスに聞いてみるか）"

# カズマ（Ｍ）
# display as カズマ
# （さて、クリスを知ってそうなやつは――）
289 = "（さて、クリスを知ってそうなやつは――）"

# クリス
# すみませーん！\nこっちにキンキンに冷えたシュワシュワくださーい！
214 = "すみませーん！\\nこっちにキンキンに冷えたシュワシュワくださーい！"

# カズマ
# って、クリスじゃないか！
223 = "って、クリスじゃないか！"

# クリス
# うわ、びっくりした！\nなんなのもう、急に大声出さないでよ。
205 = "うわ、びっくりした！\\nなんなのもう、急に大声出さないでよ。"

# カズマ
# ああ、悪い。\nこんなにあっさり見つかると思って\nなかったからさ。
199 = "ああ、悪い。\\nこんなにあっさり見つかると思って\\nなかったからさ。"

# クリス
# え……もしかしてあたしを捜してた？
208 = "え……もしかしてあたしを捜してた？"

# カズマ
# そんな警戒するなよ……傷つくだろ。
219 = "そんな警戒するなよ……傷つくだろ。"

# クリス
# いやキミさ、この数ヶ月の間、\nあたしたちに何をしてきたかわかってるの？
203 = "いやキミさ、この数ヶ月の間、\\nあたしたちに何をしてきたかわかってるの？"

# カズマ
# はい、パンツを盗んできました。
229 = "はい、パンツを盗んできました。"

# クリス
# 今はもう指輪の呪いがないってわかってても、\n体が自動的に警戒しちゃうんだよ。
241 = "今はもう指輪の呪いがないってわかってても、\\n体が自動的に警戒しちゃうんだよ。"

# カズマ
# つまりクリスは、\nこの数ヶ月の出来事を迷惑に感じてたって\nことなんだな？
224 = "つまりクリスは、\\nこの数ヶ月の出来事を迷惑に感じてたって\\nことなんだな？"

# クリス
# あたしにパンツを盗まれて喜ぶ趣味なんて\nないからね。
200 = "あたしにパンツを盗まれて喜ぶ趣味なんて\\nないからね。"

# カズマ
# だったらさ、俺にお詫びをさせてくれよ。
220 = "だったらさ、俺にお詫びをさせてくれよ。"

# クリス
# お詫びって何それ？
211 = "お詫びって何それ？"

# カズマ
# 迷惑をかけた埋め合わせだよ。
285 = "迷惑をかけた埋め合わせだよ。"

# クリス
# なるほど、それでこれまでの悪行を\nチャラにしろと？
227 = "なるほど、それでこれまでの悪行を\\nチャラにしろと？"

# カズマ
# もしかしてクリスさん、結構怒ってる？
232 = "もしかしてクリスさん、結構怒ってる？"

# クリス
# 怒ってない方がおかしいと思うんだけど。
247 = "怒ってない方がおかしいと思うんだけど。"

# カズマ
# そうですよね……ごめんなさい！
215 = "そうですよね……ごめんなさい！"

# クリス
# あはは、冗談だよ、冗談。\nま、いい思い出じゃないのは確かだけど、\nキミを避けるほど怒ってはいないから。
202 = "あはは、冗談だよ、冗談。\\nま、いい思い出じゃないのは確かだけど、\\nキミを避けるほど怒ってはいないから。"

# カズマ
# 本当か？　はあ、よかった。
249 = "本当か？　はあ、よかった。"

# クリス
# それで、お詫びだっけ？
217 = "それで、お詫びだっけ？"

# カズマ
# おう、なんでも言ってくれ！\nさあさあ早く！　今すぐに！
209 = "おう、なんでも言ってくれ！\\nさあさあ早く！　今すぐに！"

# クリス
# そう言われてもね。\n今は特に欲しい物も\nお願いしたいこともないんだよ。
216 = "そう言われてもね。\\n今は特に欲しい物も\\nお願いしたいこともないんだよ。"

# カズマ
# 搾り出せば１つや２つあるだろ。
248 = "搾り出せば１つや２つあるだろ。"

# クリス
# うーん、そうだな。\nじゃあ、１００万エリスでいいや。
206 = "うーん、そうだな。\\nじゃあ、１００万エリスでいいや。"

# カズマ
# 俺にそんな金があると思ってるのか？
242 = "俺にそんな金があると思ってるのか？"

# クリス
# だよね？
221 = "だよね？"

# カズマ
# よし、１日執事ってのはどうだろう？
233 = "よし、１日執事ってのはどうだろう？"

# クリス
# いらない。
204 = "いらない。"

# カズマ
# マッサージは！
239 = "マッサージは！"

# クリス
# 絶対、嫌。
283 = "絶対、嫌。"

# カズマ
# お背中流しましょうか、クリスさん。
210 = "お背中流しましょうか、クリスさん。"

# クリス
# 殴るよ？
250 = "殴るよ？"

# カズマ
# すみませんでした。
213 = "すみませんでした。"

# クリス
# うーん、何も思いつかないから\n今は保留にしておいて。
207 = "うーん、何も思いつかないから\\n今は保留にしておいて。"

# クリス
# それに、キミに貸しを作っておくっていうのも\nなかなか悪くないかもしれないしね。
218 = "それに、キミに貸しを作っておくっていうのも\\nなかなか悪くないかもしれないしね。"

# カズマ
# な、何をたくらんでるんだよ。
225 = "な、何をたくらんでるんだよ。"

# クリス
# 別に何もー？\nさーてと、シュワシュワも飲み終わったし\nそろそろ行こうかな。
243 = "別に何もー？\\nさーてと、シュワシュワも飲み終わったし\\nそろそろ行こうかな。"

# カズマ
# あっ、おい、クリス！
201 = "あっ、おい、クリス！"

# クリス
# じゃあ、またね。
212 = "じゃあ、またね。"

# カズマ（Ｍ）
# display as カズマ
# （……参ったな。\n　この展開は予想してなかったぞ）
287 = "（……参ったな。\\n　この展開は予想してなかったぞ）"

# カズマ（Ｍ）
# display as カズマ
# （つーか、借りってなんだ借りって。\n　あいつは一体、俺に何をさせるつもりだ？）
291 = "（つーか、借りってなんだ借りって。\\n　あいつは一体、俺に何をさせるつもりだ？）"

# カズマ（Ｍ）
# display as カズマ
# （クリスのことだから、他のやつらみたいに\n　妙なことは言いださないと信じたい……が、\n　今回のことを盾に無茶ぶりされる可能性もあるな）
294 = "（クリスのことだから、他のやつらみたいに\\n　妙なことは言いださないと信じたい……が、\\n　今回のことを盾に無茶ぶりされる可能性もあるな）"

# カズマ（Ｍ）
# display as カズマ
# （よし！\n　なら何か言われる前に\n　こっちから借りを返しちまおう）
293 = "（よし！\\n　なら何か言われる前に\\n　こっちから借りを返しちまおう）"

# カズマ（Ｍ）
# display as カズマ
# （後になって色々要求されるより、\n　さっさと終わらせたほうが\n　俺の精神的にも楽だしな）
297 = "（後になって色々要求されるより、\\n　さっさと終わらせたほうが\\n　俺の精神的にも楽だしな）"

# カズマ（Ｍ）
# display as カズマ
# （そうと決まればクリスを追っかけて\n　サクッと望みを叶えてやるか！）
290 = "（そうと決まればクリスを追っかけて\\n　サクッと望みを叶えてやるか！）"

