# root_c13.txt.scn

[info]
0 = ""

[characters]
163 = "カズマ（Ｍ）"
164 = "ダクネス"
162 = "カズマ"

[character_subs]
# 162 = "カズマ"

[script]
# lines: 36

# カズマ（Ｍ）
# display as カズマ
# （やっぱり、女の子に食べさせてもらうと\n　数倍増しに飯が美味い！）
206 = "（やっぱり、女の子に食べさせてもらうと\\n　数倍増しに飯が美味い！）"

# カズマ（Ｍ）
# display as カズマ
# （ふふふ！\n　アクア達の嫉妬もまた心地良いぜ！\n　これも勝者の醍醐味ってやつだ！）
203 = "（ふふふ！\\n　アクア達の嫉妬もまた心地良いぜ！\\n　これも勝者の醍醐味ってやつだ！）"

# カズマ（Ｍ）
# display as カズマ
# （でも、出だしが肝心だ。\n　ダクネスに愛想を尽かされないように、\n　本腰を入れて、将来のことも考えていこう）
201 = "（でも、出だしが肝心だ。\\n　ダクネスに愛想を尽かされないように、\\n　本腰を入れて、将来のことも考えていこう）"

# カズマ（Ｍ）
# display as カズマ
# （やっぱり、当面の問題は\n　今ある小金がいつまで保つかだ……）
207 = "（やっぱり、当面の問題は\\n　今ある小金がいつまで保つかだ……）"

# カズマ（Ｍ）
# display as カズマ
# （スカルドラゴンの討伐報酬があるけど、\n　その金もいつはいるか不透明だし）
209 = "（スカルドラゴンの討伐報酬があるけど、\\n　その金もいつはいるか不透明だし）"

# カズマ（Ｍ）
# display as カズマ
# （やっぱり、クエストをこなして、\n　少しずつ蓄えを作っていくしかないか）
205 = "（やっぱり、クエストをこなして、\\n　少しずつ蓄えを作っていくしかないか）"

# カズマ（Ｍ）
# display as カズマ
# （でも、報酬が高額なクエストは\n　モンスターも強いし、\n　うちのパーティーじゃクリアは不可能だろう）
202 = "（でも、報酬が高額なクエストは\\n　モンスターも強いし、\\n　うちのパーティーじゃクリアは不可能だろう）"

# カズマ（Ｍ）
# display as カズマ
# （そろそろ、パーティーメンバーを\n　増やすべきか？）
200 = "（そろそろ、パーティーメンバーを\\n　増やすべきか？）"

# カズマ（Ｍ）
# display as カズマ
# （駆け出し当時と違って、今は知り合いも増えた。\n　そいつらに声をかければ、\n　高レベルのクエストもクリアできそうだが――）
213 = "（駆け出し当時と違って、今は知り合いも増えた。\\n　そいつらに声をかければ、\\n　高レベルのクエストもクリアできそうだが――）"

# カズマ（Ｍ）
# display as カズマ
# （けど、人数が増えた分、\n　個人で得られる報酬が減る恐れもあるな）
196 = "（けど、人数が増えた分、\\n　個人で得られる報酬が減る恐れもあるな）"

# カズマ（Ｍ）
# display as カズマ
# （それじゃ本末転倒だ。\n　うーん、しっかりと考えていかなければ）
199 = "（それじゃ本末転倒だ。\\n　うーん、しっかりと考えていかなければ）"

# ダクネス
# 大丈夫か、カズマ？
169 = "大丈夫か、カズマ？"

# カズマ
# おわっ！？
152 = "おわっ！？"

# ダクネス
# すまない、勝手に入ってしまって。\n何度もノックをしたんだが、\n返事がないので心配になったんだ。
153 = "すまない、勝手に入ってしまって。\\n何度もノックをしたんだが、\\n返事がないので心配になったんだ。"

# カズマ
# そ、そうだったのか。\n悪い、ちょっと考え事をしてたんだ。
155 = "そ、そうだったのか。\\n悪い、ちょっと考え事をしてたんだ。"

# ダクネス
# そのようだな。\nとても真剣な表情をしていたぞ。
157 = "そのようだな。\\nとても真剣な表情をしていたぞ。"

# ダクネス
# なぁ、カズマ。\n私では、力になれないだろうか？
159 = "なぁ、カズマ。\\n私では、力になれないだろうか？"

# ダクネス
# もし、私にできることがあるのなら、\n遠慮なく言って欲しい。
160 = "もし、私にできることがあるのなら、\\n遠慮なく言って欲しい。"

# カズマ
# ああ、わかってるよ。\nありがとな、ダクネス。
149 = "ああ、わかってるよ。\\nありがとな、ダクネス。"

# カズマ（Ｍ）
# display as カズマ
# （これは俺達の問題でもある。\n　ダクネスだけじゃなく、\n　アクアやめぐみんにも話さないと）
198 = "（これは俺達の問題でもある。\\n　ダクネスだけじゃなく、\\n　アクアやめぐみんにも話さないと）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスとのこれからを考えると\n　金はいくらあっても足りないだろう）
211 = "（ダクネスとのこれからを考えると\\n　金はいくらあっても足りないだろう）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスはお嬢様だけど、\n　実家を頼る、なんてことを\n　させるわけにはいかない）
212 = "（ダクネスはお嬢様だけど、\\n　実家を頼る、なんてことを\\n　させるわけにはいかない）"

# カズマ
# 安心しろダクネス。\n俺はちゃんと……考えているからな。
170 = "安心しろダクネス。\\n俺はちゃんと……考えているからな。"

# ダクネス
# そ、そうか？\nなんだかよくわからないが、わかった。
154 = "そ、そうか？\\nなんだかよくわからないが、わかった。"

# カズマ
# それで、俺になんの用？
158 = "それで、俺になんの用？"

# ダクネス
# ああ、そうだった。\n今日は天気もいいし、一緒に出かけないか？
148 = "ああ、そうだった。\\n今日は天気もいいし、一緒に出かけないか？"

# カズマ
# えっ！？
151 = "えっ！？"

# カズマ（Ｍ）
# display as カズマ
# （こ、これってまさか……）
197 = "（こ、これってまさか……）"

# ダクネス
# 今日は街に行ってみようと思うんだが、\nどうだろう？
167 = "今日は街に行ってみようと思うんだが、\\nどうだろう？"

# カズマ（Ｍ）
# display as カズマ
# （もしかして、もしかしなくても！！）
204 = "（もしかして、もしかしなくても！！）"

# カズマ
# わかった。\nつき合おうじゃないか。
161 = "わかった。\\nつき合おうじゃないか。"

# ダクネス
# そうか！\nふぅ、よかった。
156 = "そうか！\\nふぅ、よかった。"

# カズマ
# フッ！\n俺がダクネスの頼みを、断るわけないさ！
165 = "フッ！\\n俺がダクネスの頼みを、断るわけないさ！"

# ダクネス
# ありがとう。\nでは、早速だが出かけよう。
150 = "ありがとう。\\nでは、早速だが出かけよう。"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスからデートに誘ってくるなんて、\n　なんて嬉しいことを！）
210 = "（ダクネスからデートに誘ってくるなんて、\\n　なんて嬉しいことを！）"

# カズマ（Ｍ）
# display as カズマ
# （よーし！　俺達の初デートだ！\n　忘れられない最高のものにしてやるぜ！）
208 = "（よーし！　俺達の初デートだ！\\n　忘れられない最高のものにしてやるぜ！）"

