# root_f06.txt.scn

[info]
0 = ""

[characters]
192 = "露天商Ｂ"
172 = "ウィズ"
174 = "カズマ（Ｍ）"
173 = "カズマ"

[character_subs]
# 173 = "カズマ"

[script]
# lines: 31

# 露天商Ｂ
# な？　すごい代物だろ？\n滅多に手に入らないから買うなら今だぜ？
166 = "な？　すごい代物だろ？\\n滅多に手に入らないから買うなら今だぜ？"

# ウィズ
# ふむふむ……。\nなるほど、確かにこれは貴重ですね。
170 = "ふむふむ……。\\nなるほど、確かにこれは貴重ですね。"

# カズマ（Ｍ）
# display as カズマ
# （うわぁ……。\n　完全におっちゃんの話術にはまってるぞ）
195 = "（うわぁ……。\\n　完全におっちゃんの話術にはまってるぞ）"

# ウィズ
# そちら、買わせて頂きます！\nええと、財布財布……。
160 = "そちら、買わせて頂きます！\\nええと、財布財布……。"

# カズマ
# ちょっ、ちょっと待ったウィズ！
161 = "ちょっ、ちょっと待ったウィズ！"

# ウィズ
# はい？　なんでしょうか？
169 = "はい？　なんでしょうか？"

# カズマ
# 冷静に考えろ。\nそれは買う必要がある物か？
178 = "冷静に考えろ。\\nそれは買う必要がある物か？"

# ウィズ
# と言いますと？
164 = "と言いますと？"

# カズマ
# 似たような物をウィズの店で見たぜ？\nだったら買う必要無いだろ。
176 = "似たような物をウィズの店で見たぜ？\\nだったら買う必要無いだろ。"

# ウィズ
# でも、せっかくこうして\nお薦めしてくれてますし、きっといい物ですよ。
163 = "でも、せっかくこうして\\nお薦めしてくれてますし、きっといい物ですよ。"

# カズマ（Ｍ）
# display as カズマ
# （いやいや、そんななんの保証も無いことを……）
194 = "（いやいや、そんななんの保証も無いことを……）"

# 露天商Ｂ
# へい、どうだろう姉ちゃん。\nそれなら、こっちも付けて\nお得なセット価格で２万エリスだ。
171 = "へい、どうだろう姉ちゃん。\\nそれなら、こっちも付けて\\nお得なセット価格で２万エリスだ。"

# ウィズ
# え？　いいんですか？
157 = "え？　いいんですか？"

# 露天商Ｂ
# おうともよ。\n姉ちゃんにはいつも気前よく\n買ってもらってっからなぁ、サービスだ。
158 = "おうともよ。\\n姉ちゃんにはいつも気前よく\\n買ってもらってっからなぁ、サービスだ。"

# ウィズ
# ありがとうございます！
155 = "ありがとうございます！"

# カズマ（Ｍ）
# display as カズマ
# （おいおいおい……。\n　買っちゃったぞ、この人。\n　いくらなんでもぼったくられすぎだろ）
196 = "（おいおいおい……。\\n　買っちゃったぞ、この人。\\n　いくらなんでもぼったくられすぎだろ）"

# カズマ（Ｍ）
# display as カズマ
# （セット価格とか言ってるけど、\n　他の露店に比べても高すぎるし\n　そもそもセット割引になってない）
200 = "（セット価格とか言ってるけど、\\n　他の露店に比べても高すぎるし\\n　そもそもセット割引になってない）"

# カズマ（Ｍ）
# display as カズマ
# （もうここまで来ると、\n　人を疑うことを知らないってのを\n　通り越してる気がするぞ）
199 = "（もうここまで来ると、\\n　人を疑うことを知らないってのを\\n　通り越してる気がするぞ）"

# カズマ（Ｍ）
# display as カズマ
# （それがウィズのいいところだけど、\n　このままだと付け込まれる一方だ）
197 = "（それがウィズのいいところだけど、\\n　このままだと付け込まれる一方だ）"

# カズマ（Ｍ）
# display as カズマ
# （人の良さに付け込む連中も許せないが、\n　まずはウィズをどうにかしないことには\n　同じことが繰り返されるな）
202 = "（人の良さに付け込む連中も許せないが、\\n　まずはウィズをどうにかしないことには\\n　同じことが繰り返されるな）"

# ウィズ
# お待たせしました。\nカズマさん、買い物終わりました。
159 = "お待たせしました。\\nカズマさん、買い物終わりました。"

# カズマ
# なあウィズ、ひとつ訊いてもいいか？
165 = "なあウィズ、ひとつ訊いてもいいか？"

# ウィズ
# はい、なんでしょう。
167 = "はい、なんでしょう。"

# カズマ
# 余計な出費をするとバニルが怒るんだろ？\nそんなに買っちまって大丈夫なのか？
177 = "余計な出費をするとバニルが怒るんだろ？\\nそんなに買っちまって大丈夫なのか？"

# ウィズ
# はい、今回は利益を出す自信がありますので\n問題ありません。
168 = "はい、今回は利益を出す自信がありますので\\n問題ありません。"

# カズマ
# ええと、自信の根拠は？
156 = "ええと、自信の根拠は？"

# ウィズ
# 露店商のみなさんが、\nすごくお勧めしてくださいましたから。
193 = "露店商のみなさんが、\\nすごくお勧めしてくださいましたから。"

# カズマ（Ｍ）
# display as カズマ
# （ダメだー。\n　ウィズは商才ゼロどころかマイナスだわー）
201 = "（ダメだー。\\n　ウィズは商才ゼロどころかマイナスだわー）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、厳しく叱るのはバニルに任せるとして）
198 = "（まあ、厳しく叱るのはバニルに任せるとして）"

# ウィズ
# では、帰りましょうか、カズマさん。
162 = "では、帰りましょうか、カズマさん。"

# カズマ（Ｍ）
# display as カズマ
# （俺に何かできることってあるのかな）
203 = "（俺に何かできることってあるのかな）"

