# root_c43.txt.scn

[info]
0 = ""

[characters]
184 = "カズマ（Ｍ）"
185 = "ダクネス"
181 = "カズマ"

[character_subs]
# 181 = "カズマ"

[script]
# lines: 52

# カズマ（Ｍ）
# display as カズマ
# （あれから、俺は色々と金策を考え――）
207 = "（あれから、俺は色々と金策を考え――）"

# カズマ（Ｍ）
# display as カズマ
# （俺がこの世界に持ち込んだ\n　メイド喫茶やアイドルといった日本独特の文化が\n　一番稼ぎやすいという結論に達した）
219 = "（俺がこの世界に持ち込んだ\\n　メイド喫茶やアイドルといった日本独特の文化が\\n　一番稼ぎやすいという結論に達した）"

# カズマ（Ｍ）
# display as カズマ
# （今までは、毎回、何かしらの邪魔が入って\n　しまったが、つかみはかなりよかったし\n　着眼点は間違ってないはずだ！）
218 = "（今までは、毎回、何かしらの邪魔が入って\\n　しまったが、つかみはかなりよかったし\\n　着眼点は間違ってないはずだ！）"

# カズマ（Ｍ）
# display as カズマ
# （だから、今度も上手くいくはず！\n　次なるプロデュースは猫喫茶だ！！）
215 = "（だから、今度も上手くいくはず！\\n　次なるプロデュースは猫喫茶だ！！）"

# カズマ（Ｍ）
# display as カズマ
# （これなら勝てる！！\n　しかも、猫だけではなく、犬喫茶、フクロウ喫茶、\n　ペンギン喫茶などなど事業展開も可能！）
210 = "（これなら勝てる！！\\n　しかも、猫だけではなく、犬喫茶、フクロウ喫茶、\\n　ペンギン喫茶などなど事業展開も可能！）"

# カズマ（Ｍ）
# display as カズマ
# （これで極貧生活から脱出できるぞ！）
209 = "（これで極貧生活から脱出できるぞ！）"

# カズマ（Ｍ）
# display as カズマ
# （――と、思っていた時期もありました）
204 = "（――と、思っていた時期もありました）"

# カズマ（Ｍ）
# display as カズマ
# （この計画を成功させるための\n　重要なファクターが\n　足りないことがわかってしまった……）
208 = "（この計画を成功させるための\\n　重要なファクターが\\n　足りないことがわかってしまった……）"

# カズマ（Ｍ）
# display as カズマ
# （そう！　猫不足！\n　野良猫なんて簡単に集められると思ってたのに、\n　全然いなかった！）
214 = "（そう！　猫不足！\\n　野良猫なんて簡単に集められると思ってたのに、\\n　全然いなかった！）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、俺はここで\n　ピンチをチャンスに変える\n　妙案を思いついたのだ！）
213 = "（しかし、俺はここで\\n　ピンチをチャンスに変える\\n　妙案を思いついたのだ！）"

# カズマ（Ｍ）
# display as カズマ
# （……それにしても遅いな）
205 = "（……それにしても遅いな）"

# ダクネス
# カズマ……着替えたぞ……。
182 = "カズマ……着替えたぞ……。"

# カズマ
# おお、待ってたぞ、入ってくれ。
158 = "おお、待ってたぞ、入ってくれ。"

# カズマ
# おっ！\n似合ってるじゃないか。
159 = "おっ！\\n似合ってるじゃないか。"

# カズマ
# よし、ちょっと四つん這いになって\nポーズを取ってくれ。
180 = "よし、ちょっと四つん這いになって\\nポーズを取ってくれ。"

# ダクネス
# こ、こんな感じでいいのか？
164 = "こ、こんな感じでいいのか？"

# カズマ
# うん、悪くない！\nむしろ、いい！　すごくいい！
156 = "うん、悪くない！\\nむしろ、いい！　すごくいい！"

# ダクネス
# そうか……。\nし、しかしこの格好は……\n露出が激しすぎると思うのだが。
168 = "そうか……。\\nし、しかしこの格好は……\\n露出が激しすぎると思うのだが。"

# ダクネス
# こんな格好で接客をさせるなんて……\nこ、これでは、周囲の目が気になって……\nんんっ、仕事にならないぞ？
165 = "こんな格好で接客をさせるなんて……\\nこ、これでは、周囲の目が気になって……\\nんんっ、仕事にならないぞ？"

# ダクネス
# なんて素晴らしい――\nいや、屈辱的なことを思いつくんだ……。
173 = "なんて素晴らしい――\\nいや、屈辱的なことを思いつくんだ……。"

# カズマ
# ダクネスには金を稼ぐために\n頑張ってもらわないといけないし、\n辛いと思うが耐えてくれ。
186 = "ダクネスには金を稼ぐために\\n頑張ってもらわないといけないし、\\n辛いと思うが耐えてくれ。"

# ダクネス
# ああ、任せろ。\n耐えるのはむしろご褒美だ！
151 = "ああ、任せろ。\\n耐えるのはむしろご褒美だ！"

# カズマ
# じゃあ、早速だが\n猫喫茶を開店するにあたって、\n従業員の作法研修をしたいと思う。
167 = "じゃあ、早速だが\\n猫喫茶を開店するにあたって、\\n従業員の作法研修をしたいと思う。"

# ダクネス
# 作法研修？\nなんだそれは？
188 = "作法研修？\\nなんだそれは？"

# カズマ
# お客様に悦んでもらえるように、\n店側が提供するサービス演出みたいなものだ。
160 = "お客様に悦んでもらえるように、\\n店側が提供するサービス演出みたいなものだ。"

# ダクネス
# よ、よし。\n教えて貰おうじゃないか。
179 = "よ、よし。\\n教えて貰おうじゃないか。"

# カズマ
# まずは口調からだ。\nダクネスはちょっと固いからな。
178 = "まずは口調からだ。\\nダクネスはちょっと固いからな。"

# カズマ
# だからこの猫喫茶では、\n語尾に「にゃん」をつけてもらう！
172 = "だからこの猫喫茶では、\\n語尾に「にゃん」をつけてもらう！"

# ダクネス
# に、にゃんだと！？
174 = "に、にゃんだと！？"

# カズマ
# おお、いいじゃないか。\nこれからしばらくは、にゃんをつけて話せ。\nあと、にゃーとにゃんにゃんも使い分けるんだ。
157 = "おお、いいじゃないか。\\nこれからしばらくは、にゃんをつけて話せ。\\nあと、にゃーとにゃんにゃんも使い分けるんだ。"

# ダクネス
# こ、こうかにゃー？\nにゃんにゃん？
161 = "こ、こうかにゃー？\\nにゃんにゃん？"

# カズマ
# うむうむ、グーに握った手を\n頬に寄せながら言うとさらにいい感じだぞ？
154 = "うむうむ、グーに握った手を\\n頬に寄せながら言うとさらにいい感じだぞ？"

# ダクネス
# こ、これでいいのか、にゃん？
162 = "こ、これでいいのか、にゃん？"

# カズマ
# そうそう！\n飲み込みがいいじゃないか、ダクネス。
169 = "そうそう！\\n飲み込みがいいじゃないか、ダクネス。"

# ダクネス
# こ、これでも……\n顔から火が出るほど……恥ずかしいんだぞ？
163 = "こ、これでも……\\n顔から火が出るほど……恥ずかしいんだぞ？"

# ダクネス
# し、しかし……\nこの猫語プレイはなかなかの羞恥だ……。\nなんだか癖になってしまいそうで……。
166 = "し、しかし……\\nこの猫語プレイはなかなかの羞恥だ……。\\nなんだか癖になってしまいそうで……。"

# カズマ
# たまに、猫が顔を洗う仕草をしたり、\n片足立ちでポーズを取って\nアピールするのも忘れるな？
171 = "たまに、猫が顔を洗う仕草をしたり、\\n片足立ちでポーズを取って\\nアピールするのも忘れるな？"

# カズマ
# 慣れてきたら、語尾だけじゃなく\n「な」を「にゃ」に変えて喋るように。
190 = "慣れてきたら、語尾だけじゃなく\\n「な」を「にゃ」に変えて喋るように。"

# ダクネス
# にゃ、にゃるほど……そうにゃのかー。
176 = "にゃ、にゃるほど……そうにゃのかー。"

# カズマ
# うむっ！\nさすがだな、ダクネス！
155 = "うむっ！\\nさすがだな、ダクネス！"

# カズマ（Ｍ）
# display as カズマ
# （これは行ける！\n　猫喫茶改め、猫耳喫茶！\n　千客万来、商売繁盛、一攫千金だぜ！）
212 = "（これは行ける！\\n　猫喫茶改め、猫耳喫茶！\\n　千客万来、商売繁盛、一攫千金だぜ！）"

# カズマ（Ｍ）
# display as カズマ
# （まず手始めにダクネス、\n　そしてアクアとめぐみんにもやらせて、\n　そのあとはバイトの子を雇って――）
217 = "（まず手始めにダクネス、\\n　そしてアクアとめぐみんにもやらせて、\\n　そのあとはバイトの子を雇って――）"

# ダクネス
# カズマ、どうかしたのかにゃ？\nまた何か心配事があるのか……にゃ？
183 = "カズマ、どうかしたのかにゃ？\\nまた何か心配事があるのか……にゃ？"

# ダクネス
# 困った時は私が助けてやるにゃ。
189 = "困った時は私が助けてやるにゃ。"

# カズマ（Ｍ）
# display as カズマ
# （これは予想以上の破壊力だ。\n　しかし――）
211 = "（これは予想以上の破壊力だ。\\n　しかし――）"

# ダクネス
# はぁ、はぁ……。\nカズマ？　なにか、いけなかったか……にゃ？
177 = "はぁ、はぁ……。\\nカズマ？　なにか、いけなかったか……にゃ？"

# カズマ
# いや、そうじゃなくて。\nダクネス、悪いがこの案は破棄する。
152 = "いや、そうじゃなくて。\\nダクネス、悪いがこの案は破棄する。"

# ダクネス
# にゃ、にゃぜ！？
175 = "にゃ、にゃぜ！？"

# カズマ
# いやなんか……\n胸の辺りがモヤモヤするっていうか……\nむかつくんだよな。
153 = "いやなんか……\\n胸の辺りがモヤモヤするっていうか……\\nむかつくんだよな。"

# ダクネス
# そんにゃ……。
170 = "そんにゃ……。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、やっぱり金を稼ぐには、\n　地道にクエストをこなすしかないのか）
206 = "（ああ、やっぱり金を稼ぐには、\\n　地道にクエストをこなすしかないのか）"

# カズマ（Ｍ）
# display as カズマ
# （はぁ……。\n　世の中、なかなか上手くいかないもんだなぁ）
216 = "（はぁ……。\\n　世の中、なかなか上手くいかないもんだなぁ）"

