# root_c21.txt.scn

[info]
0 = ""

[characters]
319 = "カズマ（Ｍ）"
321 = "ダクネス"
316 = "カズマ"
314 = "アクア"
307 = "めぐみん"
315 = "アクア＆めぐみん＆ダクネス"

[character_subs]
# 316 = "カズマ"
392 = "３人"

[script]
# lines: 96

# カズマ（Ｍ）
# display as カズマ
# （はぁ……。\n　あの夢のような日々が幻だったとは）
390 = "（はぁ……。\\n　あの夢のような日々が幻だったとは）"

# カズマ（Ｍ）
# display as カズマ
# （これからの俺の人生が\n　充実して明るいものになると\n　思っていたのになぁ）
386 = "（これからの俺の人生が\\n　充実して明るいものになると\\n　思っていたのになぁ）"

# カズマ（Ｍ）
# display as カズマ
# （こんなことなら、もっと色んなことを\n　しておけばよかったぜ……）
387 = "（こんなことなら、もっと色んなことを\\n　しておけばよかったぜ……）"

# ダクネス
# カズマ、まだここにいたのか。
317 = "カズマ、まだここにいたのか。"

# カズマ
# いいえ、いませんがー？
250 = "いいえ、いませんがー？"

# ダクネス
# そう邪険にするな。
273 = "そう邪険にするな。"

# カズマ
# なんだよ。\nまた俺を笑いに来たのか？
300 = "なんだよ。\\nまた俺を笑いに来たのか？"

# ダクネス
# そんなことをしてなんになる。\n私はただ、お前が心配で――
280 = "そんなことをしてなんになる。\\n私はただ、お前が心配で――"

# カズマ
# あー、もうっ！\nそれがダメなんだよお前は！
248 = "あー、もうっ！\\nそれがダメなんだよお前は！"

# ダクネス
# そ、そうなのか？
269 = "そ、そうなのか？"

# カズマ
# その優しさが俺に変な勘違いをさせたんだろ！\nあー、もう、穴があったら入りたい！
277 = "その優しさが俺に変な勘違いをさせたんだろ！\\nあー、もう、穴があったら入りたい！"

# ダクネス
# 掘るか！
335 = "掘るか！"

# カズマ
# いらんわ！
254 = "いらんわ！"

# ダクネス
# な、なあ、カズマ？\nひとつ訊いてもいいか？
292 = "な、なあ、カズマ？\\nひとつ訊いてもいいか？"

# カズマ
# あ？
249 = "あ？"

# ダクネス
# そんなによかったのか？
281 = "そんなによかったのか？"

# カズマ
# 何が。
324 = "何が。"

# ダクネス
# いやだから、私とのこの数日がだ。
252 = "いやだから、私とのこの数日がだ。"

# カズマ
# 当たり前だろ！\n人生で初めて彼女ができたんだぞ！
334 = "当たり前だろ！\\n人生で初めて彼女ができたんだぞ！"

# ダクネス
# だが、ただ硬いだけが取り柄の\n私が相手なのだぞ？
284 = "だが、ただ硬いだけが取り柄の\\n私が相手なのだぞ？"

# カズマ（Ｍ）
# display as カズマ
# （こいつ……絶対に自分がどれだけ美人で\n　性格もいいのか分かってねえな）
385 = "（こいつ……絶対に自分がどれだけ美人で\\n　性格もいいのか分かってねえな）"

# ダクネス
# なんだ、言いたいことがあるなら言ってくれ。
299 = "なんだ、言いたいことがあるなら言ってくれ。"

# カズマ（Ｍ）
# display as カズマ
# （だが、素直に教えてやるのもシャクだな）
389 = "（だが、素直に教えてやるのもシャクだな）"

# ダクネス
# おいカズマ、黙ってどうしたんだ。
261 = "おいカズマ、黙ってどうしたんだ。"

# カズマ
# どうもしてねえよ。
291 = "どうもしてねえよ。"

# ダクネス
# いや嘘だ。\n絶対今、何かを考えていただろう。
253 = "いや嘘だ。\\n絶対今、何かを考えていただろう。"

# カズマ
# ああ、考えてたよ。\nおっぱい大きいなって。
247 = "ああ、考えてたよ。\\nおっぱい大きいなって。"

# ダクネス
# なっ！？
297 = "なっ！？"

# カズマ
# おっぱい。
264 = "おっぱい。"

# ダクネス
# なぁ！
294 = "なぁ！"

# カズマ
# おっぱい！
265 = "おっぱい！"

# ダクネス
# や、やめろ！\nそれは私の望む羞恥ではない！
309 = "や、やめろ！\\nそれは私の望む羞恥ではない！"

# カズマ
# 凝視！
326 = "凝視！"

# ダクネス
# う、うう……本当に怒るぞ？
255 = "う、うう……本当に怒るぞ？"

# カズマ
# 嫌なら逃げればいいだろう？
330 = "嫌なら逃げればいいだろう？"

# ダクネス
# そうしたいのはやまやまなのだが、\nやっぱりカズマが心配で。
270 = "そうしたいのはやまやまなのだが、\\nやっぱりカズマが心配で。"

# カズマ
# なあ、その他人を最優先に考えるの\nどうにかならないのか？
295 = "なあ、その他人を最優先に考えるの\\nどうにかならないのか？"

# カズマ
# 確かに、それはお前の美徳なのかもしれないけど、\nいつかその性格が原因で痛い目にあうぞ？
378 = "確かに、それはお前の美徳なのかもしれないけど、\\nいつかその性格が原因で痛い目にあうぞ？"

# ダクネス
# そうは言われても、これが私だ。\n今さらどうにもできないし、するつもりもない。
272 = "そうは言われても、これが私だ。\\n今さらどうにもできないし、するつもりもない。"

# カズマ
# どうしてだよ。
289 = "どうしてだよ。"

# ダクネス
# 領主の娘としてこの街の住民を守るのは私の役目。
382 = "領主の娘としてこの街の住民を守るのは私の役目。"

# ダクネス
# それをただの義務として動くか、\n仁を持って動くかでは大きな違いがある。
279 = "それをただの義務として動くか、\\n仁を持って動くかでは大きな違いがある。"

# カズマ
# よくわからんけど、そういうもんなのかね。
311 = "よくわからんけど、そういうもんなのかね。"

# ダクネス
# 私はそうだと信じているよ。
379 = "私はそうだと信じているよ。"

# カズマ
# …………。
245 = "…………。"

# ダクネス
# …………。
# 245 = "…………。"

# カズマ
# ララティーナ。
322 = "ララティーナ。"

# ダクネス
# そっちの名前で呼ぶな！！
276 = "そっちの名前で呼ぶな！！"

# アクア
# さあ、セクハラの現行犯よ、カズマ！
268 = "さあ、セクハラの現行犯よ、カズマ！"

# めぐみん
# ふん、年貢の納め時ってやつですね！
303 = "ふん、年貢の納め時ってやつですね！"

# カズマ
# な、なんだ！？
293 = "な、なんだ！？"

# ダクネス
# どうしたんだふたりとも！
288 = "どうしたんだふたりとも！"

# アクア
# あ、あら？　なんだか普通ね。
246 = "あ、あら？　なんだか普通ね。"

# めぐみん
# でも今、ダクネスの叫び声が聞こえましたよ？
287 = "でも今、ダクネスの叫び声が聞こえましたよ？"

# カズマ
# ははーん、俺がダクネスにセクハラをしてると\n思って乗り込んできたんだな。
302 = "ははーん、俺がダクネスにセクハラをしてると\\n思って乗り込んできたんだな。"

# アクア
# も、もしかして違ったのかしら？
308 = "も、もしかして違ったのかしら？"

# カズマ
# 違うわ！\nいまそんなことしたら恥の上塗りだろ。
381 = "違うわ！\\nいまそんなことしたら恥の上塗りだろ。"

# カズマ
# だいたい、セクハラの現場を押さえて\nどうするつもりだったんだよ。
283 = "だいたい、セクハラの現場を押さえて\\nどうするつもりだったんだよ。"

# めぐみん
# セナさんに突き出してやろうかと。
320 = "セナさんに突き出してやろうかと。"

# カズマ
# やめろ、マジでやめろ。
310 = "やめろ、マジでやめろ。"

# アクア
# なんか予定が狂っちゃったわね。
298 = "なんか予定が狂っちゃったわね。"

# めぐみん
# カズマがセクハラをしていてくれれば、\n今頃楽しい時間を過ごせていたのに。
318 = "カズマがセクハラをしていてくれれば、\\n今頃楽しい時間を過ごせていたのに。"

# アクア
# 空気を読めないって罪よねぇ。
380 = "空気を読めないって罪よねぇ。"

# カズマ
# そんな空気は読めなくて大歓迎だわ。
282 = "そんな空気は読めなくて大歓迎だわ。"

# ダクネス
# なあ、ふたりは時間を持て余しているのか？
296 = "なあ、ふたりは時間を持て余しているのか？"

# めぐみん
# ええ、それがどうかしましたか？
258 = "ええ、それがどうかしましたか？"

# ダクネス
# では、久しぶりにクエストに行かないか？
286 = "では、久しぶりにクエストに行かないか？"

# めぐみん
# おお、いいですね！
263 = "おお、いいですね！"

# アクア
# うん、たまには体を動かさないとね。
256 = "うん、たまには体を動かさないとね。"

# ダクネス
# そうと決まれば、ギルドへ――
271 = "そうと決まれば、ギルドへ――"

# ダクネス
# さあ、いくぞカズマ。
267 = "さあ、いくぞカズマ。"

# カズマ
# ええー、俺腹が減ってるんだけど。
259 = "ええー、俺腹が減ってるんだけど。"

# アクア
# それなら湖絡みのクエストにしましょうよ。
278 = "それなら湖絡みのクエストにしましょうよ。"

# めぐみん
# 魚も捕れますし、一挙両得ですね。
383 = "魚も捕れますし、一挙両得ですね。"

# ダクネス
# どうするカズマ。\n行くのか、行かないのか。
290 = "どうするカズマ。\\n行くのか、行かないのか。"

# カズマ（Ｍ）
# display as カズマ
# （やれやれ、しょうがないな）
391 = "（やれやれ、しょうがないな）"

# カズマ
# 爆裂魔法１発しか撃てないアークウィザード。
337 = "爆裂魔法１発しか撃てないアークウィザード。"

# めぐみん
# むっ。
306 = "むっ。"

# カズマ
# 宴会芸しかできないアークプリースト。
331 = "宴会芸しかできないアークプリースト。"

# アクア
# 回復魔法も使えるわよ！
329 = "回復魔法も使えるわよ！"

# カズマ
# そして攻撃があたらない変態クルセイダー。
275 = "そして攻撃があたらない変態クルセイダー。"

# ダクネス
# へ、変態！？
304 = "へ、変態！？"

# カズマ
# 俺が行かないと攻撃できるやつがいないだろ？
325 = "俺が行かないと攻撃できるやつがいないだろ？"

# めぐみん
# そこまで大口を叩いたのです。\nちゃんと働いてくださいね。
274 = "そこまで大口を叩いたのです。\\nちゃんと働いてくださいね。"

# カズマ
# わかってるよ。
313 = "わかってるよ。"

# アクア
# ねえねえ、カズマ。\n湖の方に行くなら、\nキャンプセット持っていくのはどうかしら？
301 = "ねえねえ、カズマ。\\n湖の方に行くなら、\\nキャンプセット持っていくのはどうかしら？"

# カズマ
# おい、遊びじゃないんだぞ。
260 = "おい、遊びじゃないんだぞ。"

# めぐみん
# いいですね！\nキャンプファイアとかしてみたいです！
251 = "いいですね！\\nキャンプファイアとかしてみたいです！"

# カズマ
# お前まで乗っかるなー！
266 = "お前まで乗っかるなー！"

# カズマ
# まったく、いつになっても成長しない奴らめ。\nこれじゃ、いつもの日常と変わらねーよ。
305 = "まったく、いつになっても成長しない奴らめ。\\nこれじゃ、いつもの日常と変わらねーよ。"

# ダクネス
# だがそれが一番なんだ。\nそう、平穏な日常がな。
285 = "だがそれが一番なんだ。\\nそう、平穏な日常がな。"

# カズマ
# うん、確かにそうかもな。
257 = "うん、確かにそうかもな。"

# カズマ（Ｍ）
# display as カズマ
# （それが本当の\n　得がたい幸せってやつなのかもしれない）
388 = "（それが本当の\\n　得がたい幸せってやつなのかもしれない）"

# カズマ
# よし、お前ら！\n今度こそ一攫千金を掴んで貧乏生活を\n脱出するぞー！
312 = "よし、お前ら！\\n今度こそ一攫千金を掴んで貧乏生活を\\n脱出するぞー！"

# アクア＆めぐみん＆ダクネス
# display as ３人
# おぉー！！
262 = "おぉー！！"

# カズマ（Ｍ）
# display as カズマ
# （ああ……でも、彼女は欲しいぜ……）
384 = "（ああ……でも、彼女は欲しいぜ……）"

