# root_d25.txt.scn

[info]
0 = ""

[characters]
178 = "カズマ（Ｍ）"
177 = "カズマ"
181 = "ルナ"
179 = "クリス"

[character_subs]
# 177 = "カズマ"

[script]
# lines: 52

# カズマ（Ｍ）
# display as カズマ
# （よく晴れた清々しいとある日。\n　街を歩く俺の心は\n　天気とは裏腹にどんよりと曇っていた）
210 = "（よく晴れた清々しいとある日。\\n　街を歩く俺の心は\\n　天気とは裏腹にどんよりと曇っていた）"

# カズマ（Ｍ）
# display as カズマ
# （いつもの光景、明るい街並み。\n　普段なら何もなくとも\n　足取りが軽くなる陽気なのだが……）
204 = "（いつもの光景、明るい街並み。\\n　普段なら何もなくとも\\n　足取りが軽くなる陽気なのだが……）"

# カズマ（Ｍ）
# display as カズマ
# （……はぁ。\n　今は聞こえてくる後ろ指をさされる言葉が\n　痛くて仕方がない）
201 = "（……はぁ。\\n　今は聞こえてくる後ろ指をさされる言葉が\\n　痛くて仕方がない）"

# カズマ（Ｍ）
# display as カズマ
# （人前で女の子のパンツを盗ったとか――）
214 = "（人前で女の子のパンツを盗ったとか――）"

# カズマ（Ｍ）
# display as カズマ
# （そのパンツを高笑いしながら投げたとか――）
207 = "（そのパンツを高笑いしながら投げたとか――）"

# カズマ（Ｍ）
# display as カズマ
# （あまつさえ、人前で女の子の服を脱がすショーを\n　しようとしたとか――）
203 = "（あまつさえ、人前で女の子の服を脱がすショーを\\n　しようとしたとか――）"

# カズマ（Ｍ）
# display as カズマ
# （もう俺、この街でどうやって生きて行けば\n　いいんだろう……）
209 = "（もう俺、この街でどうやって生きて行けば\\n　いいんだろう……）"

# カズマ
# こんにちはー。
160 = "こんにちはー。"

# ルナ
# ……あら、サトウさん？
150 = "……あら、サトウさん？"

# ルナ
# 本日はどういったご用件でしょうか。\nあいにく、サトウさん向きの\n新規クエストはありませんけど。
188 = "本日はどういったご用件でしょうか。\\nあいにく、サトウさん向きの\\n新規クエストはありませんけど。"

# カズマ
# あ、いや、今日は飯を食いに……。
154 = "あ、いや、今日は飯を食いに……。"

# ルナ
# そうですか。\nでしたら、お好きなお席へどうぞ。
163 = "そうですか。\\nでしたら、お好きなお席へどうぞ。"

# カズマ（Ｍ）
# display as カズマ
# （薄々、想像はしていたけど\n　やっぱりこうなるよなぁ……）
218 = "（薄々、想像はしていたけど\\n　やっぱりこうなるよなぁ……）"

# カズマ（Ｍ）
# display as カズマ
# （店中の視線が痛い！\n　こっち見てひそひそ喋りやがって。\n　一体、俺が何をしたってんだ！）
216 = "（店中の視線が痛い！\\n　こっち見てひそひそ喋りやがって。\\n　一体、俺が何をしたってんだ！）"

# クリス
# やあ、カズマ。\nこれからお昼？\nなら、あたしと一緒に食べない？
176 = "やあ、カズマ。\\nこれからお昼？\\nなら、あたしと一緒に食べない？"

# カズマ
# クリス？
180 = "クリス？"

# クリス
# なんだか元気ないね？\nキミらしくもない。
172 = "なんだか元気ないね？\\nキミらしくもない。"

# カズマ
# そりゃ、こんだけ腫れもの扱いされたら\n元気もなくなるわ。
166 = "そりゃ、こんだけ腫れもの扱いされたら\\n元気もなくなるわ。"

# カズマ
# 街を歩けば誰もが俺のことを冷たい目で見るし、\n女の子なんかは目が合っただけで悲鳴をあげるし、\n子供からは石投げられるし……。
199 = "街を歩けば誰もが俺のことを冷たい目で見るし、\\n女の子なんかは目が合っただけで悲鳴をあげるし、\\n子供からは石投げられるし……。"

# カズマ（Ｍ）
# display as カズマ
# （確かに、俺はクリスのパンツを盗んだよ。\n　盗んだけどさ、それは不可抗力だろ？\n　最初から盗もうと思って盗んだわけじゃない！）
217 = "（確かに、俺はクリスのパンツを盗んだよ。\\n　盗んだけどさ、それは不可抗力だろ？\\n　最初から盗もうと思って盗んだわけじゃない！）"

# カズマ（Ｍ）
# display as カズマ
# （パンツを投げたのだって、\n　ちゃんとした理由があるし？）
212 = "（パンツを投げたのだって、\\n　ちゃんとした理由があるし？）"

# カズマ（Ｍ）
# display as カズマ
# （ズボンを脱がせようとしたのは、演技なんだ。\n　それなのに――）
211 = "（ズボンを脱がせようとしたのは、演技なんだ。\\n　それなのに――）"

# カズマ
# なんで俺がこの街始まって以来の変態とか\n歴史に名を残す欲望に忠実な男とか\n言われてるんだよ……。
173 = "なんで俺がこの街始まって以来の変態とか\\n歴史に名を残す欲望に忠実な男とか\\n言われてるんだよ……。"

# クリス
# 噂には尾ひれがつくって言うけど、\n尾ひれどころか背びれ胸びれまで\nついてる感じだよね。
185 = "噂には尾ひれがつくって言うけど、\\n尾ひれどころか背びれ胸びれまで\\nついてる感じだよね。"

# カズマ
# そうだよ！\nおかげで原型ほぼ止めてねーし！
162 = "そうだよ！\\nおかげで原型ほぼ止めてねーし！"

# クリス
# でもまあ、あれだけのことをしたんだからね。\n当然の罰ってやつなんじゃないかな。
169 = "でもまあ、あれだけのことをしたんだからね。\\n当然の罰ってやつなんじゃないかな。"

# カズマ
# ううう……。\n全部俺が意図してやったわけじゃないのに。\nエリス様にも祈ったのに……！
157 = "ううう……。\\n全部俺が意図してやったわけじゃないのに。\\nエリス様にも祈ったのに……！"

# クリス
# そこはさぁ、エリス様も\nカズマの行為を許すほど\n寛大じゃなかったってことじゃない？
164 = "そこはさぁ、エリス様も\\nカズマの行為を許すほど\\n寛大じゃなかったってことじゃない？"

# カズマ（Ｍ）
# display as カズマ
# （ああ……。\n　子供のころ、夢見た世界。\n　剣と魔法が織りなす異世界の話）
202 = "（ああ……。\\n　子供のころ、夢見た世界。\\n　剣と魔法が織りなす異世界の話）"

# カズマ（Ｍ）
# display as カズマ
# （不慮の事故により命を失った少年が\n　美しい女神によって二度目の生を与えられ\n　新たな人生を歩みだす……そんな物語）
213 = "（不慮の事故により命を失った少年が\\n　美しい女神によって二度目の生を与えられ\\n　新たな人生を歩みだす……そんな物語）"

# カズマ（Ｍ）
# display as カズマ
# （これは、日本のどこにでもいるような\n　ごく平凡な引きこもりである俺に訪れた\n　人生逆転のための千載一遇のチャンス！）
205 = "（これは、日本のどこにでもいるような\\n　ごく平凡な引きこもりである俺に訪れた\\n　人生逆転のための千載一遇のチャンス！）"

# カズマ（Ｍ）
# display as カズマ
# （……で、あったはずなのに）
200 = "（……で、あったはずなのに）"

# カズマ
# どうしてこう上手くいかねーのかなぁ。\n俺はただ、平和に、できれば苦労せずに\n楽して生きていくことを願っているだけなのに……。
170 = "どうしてこう上手くいかねーのかなぁ。\\n俺はただ、平和に、できれば苦労せずに\\n楽して生きていくことを願っているだけなのに……。"

# カズマ
# ……あれか。\nあいつと、アクアと出会ったのが\n運の尽きだったのか？
151 = "……あれか。\\nあいつと、アクアと出会ったのが\\n運の尽きだったのか？"

# カズマ
# そもそもあの日、家の外に出なければ！\nああ！　なんで俺はこんな\n取り返しのつかないことをしてしまったんだっ！
165 = "そもそもあの日、家の外に出なければ！\\nああ！　なんで俺はこんな\\n取り返しのつかないことをしてしまったんだっ！"

# クリス
# まあまあ、何言ってるのか\nよくわからないけど、落ち着きなよ。\n今日のご飯は、あたしが奢ってあげるからさ。
174 = "まあまあ、何言ってるのか\\nよくわからないけど、落ち着きなよ。\\n今日のご飯は、あたしが奢ってあげるからさ。"

# カズマ
# え？　いいのか？
159 = "え？　いいのか？"

# クリス
# うん、たまにはね。
158 = "うん、たまにはね。"

# カズマ
# ……これも借りになるのか？
152 = "……これも借りになるのか？"

# クリス
# さぁ、どうだろうね。\nとにかく、冷める前に食べなよ。
161 = "さぁ、どうだろうね。\\nとにかく、冷める前に食べなよ。"

# カズマ（Ｍ）
# display as カズマ
# （そういえば、結局、\n　パンツの借りも返してないな。\n　貸しを作っておくのもいい、とは言われたけど）
206 = "（そういえば、結局、\\n　パンツの借りも返してないな。\\n　貸しを作っておくのもいい、とは言われたけど）"

# カズマ
# なぁ、クリス。\nいま欲しい物とかないか？\n俺にやってもらいたいこととかさ。
171 = "なぁ、クリス。\\nいま欲しい物とかないか？\\n俺にやってもらいたいこととかさ。"

# クリス
# もしかして、この前のこと気にしてる？
175 = "もしかして、この前のこと気にしてる？"

# カズマ
# そりゃまあな。\n意図してやったことじゃないとはいえ、\n迷惑かけたことには変わりないし。
167 = "そりゃまあな。\\n意図してやったことじゃないとはいえ、\\n迷惑かけたことには変わりないし。"

# クリス
# あれについては結構大きな貸しだからねぇ。\n簡単なことで許すつもりはないよ。
156 = "あれについては結構大きな貸しだからねぇ。\\n簡単なことで許すつもりはないよ。"

# カズマ
# ……何をさせるつもりだ？
153 = "……何をさせるつもりだ？"

# クリス
# 今、考え中。\nせっかくなんだし、キミには思いっきり\n役に立ってもらわないと。
183 = "今、考え中。\\nせっかくなんだし、キミには思いっきり\\n役に立ってもらわないと。"

# カズマ
# 嫌な予感しかしないんだが。
186 = "嫌な予感しかしないんだが。"

# クリス
# あはは！\n頼りにしてるよ、カズマ。
155 = "あはは！\\n頼りにしてるよ、カズマ。"

# カズマ（Ｍ）
# display as カズマ
# （俺の知ってる奴の中じゃ\n　クリスは常識人の部類に入るけど\n　時々、突拍子もないことを言い出すからな）
215 = "（俺の知ってる奴の中じゃ\\n　クリスは常識人の部類に入るけど\\n　時々、突拍子もないことを言い出すからな）"

# カズマ（Ｍ）
# display as カズマ
# （また、変なことに\n　巻き込まれないといいんだが）
208 = "（また、変なことに\\n　巻き込まれないといいんだが）"

# カズマ
# ったく、ついてないなぁ……。
168 = "ったく、ついてないなぁ……。"

