# root_b09.txt.scn

[info]
0 = ""

[characters]
347 = "カズマ"
343 = "めぐみん"
348 = "カズマ（Ｍ）"

[character_subs]
# 347 = "カズマ"

[script]
# lines: 101

# カズマ
# よしよし、探せばあるもんだな。\n水とパンがこれだけあれば、なんとかなりそうだ。
345 = "よしよし、探せばあるもんだな。\\n水とパンがこれだけあれば、なんとかなりそうだ。"

# めぐみん
# このパン、いつからここにあったんでしょう？\nそんなに古い物ではありませんよね。
304 = "このパン、いつからここにあったんでしょう？\\nそんなに古い物ではありませんよね。"

# めぐみん
# これを教会に持ってきた信者達は、\nいつから姿を消しているのでしょう？
305 = "これを教会に持ってきた信者達は、\\nいつから姿を消しているのでしょう？"

# カズマ
# うーん、掃除の具合から見て\n長くても昨日あたりじゃないか？
296 = "うーん、掃除の具合から見て\\n長くても昨日あたりじゃないか？"

# めぐみん
# はたして、そうでしょうか？\nここは呪われているのですから、\n目に見える情報が正しいとは限りません。
336 = "はたして、そうでしょうか？\\nここは呪われているのですから、\\n目に見える情報が正しいとは限りません。"

# めぐみん
# 実は荒れ果てていて、この食べ物も\n何日も放置されていた可能性があるのでは？
357 = "実は荒れ果てていて、この食べ物も\\n何日も放置されていた可能性があるのでは？"

# カズマ
# そんなことを言ったらキリがないぜ？\n少なくとも匂いを嗅ぐ限り問題はなさそうだし、\n食べちまおう。
314 = "そんなことを言ったらキリがないぜ？\\n少なくとも匂いを嗅ぐ限り問題はなさそうだし、\\n食べちまおう。"

# めぐみん
# ……呪われた教会に置かれていた物を\n口にする気にはとてもなれませんよ。
283 = "……呪われた教会に置かれていた物を\\n口にする気にはとてもなれませんよ。"

# カズマ
# なら、何も食べずに\n一晩過ごすっていうのか？
326 = "なら、何も食べずに\\n一晩過ごすっていうのか？"

# めぐみん
# それはそれで……嫌です。
312 = "それはそれで……嫌です。"

# カズマ
# はあ、わがままだなぁ。\nじゃあ、どうするっていうんだよ？
334 = "はあ、わがままだなぁ。\\nじゃあ、どうするっていうんだよ？"

# めぐみん
# とりあえず、カズマが食べてください。\nしばらく様子を見て、問題なさそうなら\n私も食べます。
321 = "とりあえず、カズマが食べてください。\\nしばらく様子を見て、問題なさそうなら\\n私も食べます。"

# カズマ
# 俺で毒味すんなよ！
353 = "俺で毒味すんなよ！"

# めぐみん
# 安全かどうかもわからない物を\n食べるほど、私は愚かではありません。
355 = "安全かどうかもわからない物を\\n食べるほど、私は愚かではありません。"

# カズマ
# おい、それって俺が愚かだって\n言ってるようなもんじゃないか？
300 = "おい、それって俺が愚かだって\\n言ってるようなもんじゃないか？"

# めぐみん
# 細かいことは気にしないで\nさあ、遠慮なくいってください。
395 = "細かいことは気にしないで\\nさあ、遠慮なくいってください。"

# カズマ
# 万が一俺になにかあったらどうする？
350 = "万が一俺になにかあったらどうする？"

# めぐみん
# えーっと……\nアクアがなんとかしてくれます。
297 = "えーっと……\\nアクアがなんとかしてくれます。"

# カズマ
# なんともならなかったらどうする？
331 = "なんともならなかったらどうする？"

# めぐみん
# その時は運がなかったと諦めてください。
309 = "その時は運がなかったと諦めてください。"

# カズマ
# 諦められるかっ！
396 = "諦められるかっ！"

# めぐみん
# では、カズマには\n仲間のために身を投げ出す覚悟が\nないのですか？
319 = "では、カズマには\\n仲間のために身を投げ出す覚悟が\\nないのですか？"

# カズマ
# その言葉をそのまま返してやるよ！
311 = "その言葉をそのまま返してやるよ！"

# めぐみん
# いえ、こういう場合、\n犠牲になるのはカズマの方が相応しいと\n思いますよ？
290 = "いえ、こういう場合、\\n犠牲になるのはカズマの方が相応しいと\\n思いますよ？"

# カズマ
# 相応しいってなんだよ？\nここはレディーファーストだ。\n先に食べていいぞ。
393 = "相応しいってなんだよ？\\nここはレディーファーストだ。\\n先に食べていいぞ。"

# めぐみん
# 普段は女性扱いしないくせに\nこういう時ばかりですか！\n最低ですね！
362 = "普段は女性扱いしないくせに\\nこういう時ばかりですか！\\n最低ですね！"

# めぐみん
# もういいです。\n結果がどうであれ、私は食べませんから。\nカズマの好きにしてください。
344 = "もういいです。\\n結果がどうであれ、私は食べませんから。\\nカズマの好きにしてください。"

# カズマ
# そこまで言われて\nはいそうですかって食えるか！
308 = "そこまで言われて\\nはいそうですかって食えるか！"

# カズマ
# １日くらい食べなくても死にはしない！\n助けが来るまで我慢だ我慢！
403 = "１日くらい食べなくても死にはしない！\\n助けが来るまで我慢だ我慢！"

# めぐみん
# あ、あの、ところでですね、カズマ……。
286 = "あ、あの、ところでですね、カズマ……。"

# カズマ
# なんだ？\nさすがにトイレを我慢できなくなったか？
327 = "なんだ？\\nさすがにトイレを我慢できなくなったか？"

# めぐみん
# 違いますよ！\n何回訂正すれば理解するんですか！
397 = "違いますよ！\\n何回訂正すれば理解するんですか！"

# カズマ
# じゃあ、さっきからなんなんだ？\n言ってくれなきゃわかんねーよ。
306 = "じゃあ、さっきからなんなんだ？\\n言ってくれなきゃわかんねーよ。"

# めぐみん
# な、なんでもありません！
324 = "な、なんでもありません！"

# カズマ
# なんでもないってことはないだろ？
330 = "なんでもないってことはないだろ？"

# めぐみん
# なんでもありません！\n気にしないでください！
329 = "なんでもありません！\\n気にしないでください！"

# カズマ（Ｍ）
# display as カズマ
# （本当になんなんだよ。\n　わかってほしいならちゃんと言えよな）
402 = "（本当になんなんだよ。\\n　わかってほしいならちゃんと言えよな）"

# カズマ
# …………。
275 = "…………。"

# めぐみん
# …………。
# 275 = "…………。"

# カズマ
# …………。
# 275 = "…………。"

# めぐみん
# …………。
# 275 = "…………。"

# カズマ
# ……黙っちまうと暇だな。
285 = "……黙っちまうと暇だな。"

# めぐみん
# ……そうですね。\n他にやることもありませんし。
277 = "……そうですね。\\n他にやることもありませんし。"

# カズマ
# よし！\nなにか面白い話をしてくれないか？
346 = "よし！\\nなにか面白い話をしてくれないか？"

# めぐみん
# 何が、よし、なのですか。\n唐突すぎるにもほどがあります。
351 = "何が、よし、なのですか。\\n唐突すぎるにもほどがあります。"

# カズマ
# 暇と空腹、どっちも紛らわせたいという\n気持ちがわからないか？
363 = "暇と空腹、どっちも紛らわせたいという\\n気持ちがわからないか？"

# めぐみん
# なら、カズマが面白い話をしてください。
325 = "なら、カズマが面白い話をしてください。"

# カズマ
# 急に話を振られても、とっさに出てこない！
359 = "急に話を振られても、とっさに出てこない！"

# めぐみん
# どの口が言うんですか！　どの口が！
323 = "どの口が言うんですか！　どの口が！"

# カズマ
# 面白い話がないとわかったとたん空腹が増したぞ。\nあ～、腹減ったぁ。
398 = "面白い話がないとわかったとたん空腹が増したぞ。\\nあ～、腹減ったぁ。"

# めぐみん
# いちいち言わないでください。\nせっかく我慢しているのに。
291 = "いちいち言わないでください。\\nせっかく我慢しているのに。"

# カズマ
# ……なあ、やっぱり\n食べ物まで呪われてるっていうのは\n考えすぎなんじゃないか？
280 = "……なあ、やっぱり\\n食べ物まで呪われてるっていうのは\\n考えすぎなんじゃないか？"

# カズマ
# うん、なんだか\n普通に食べられそうな気がしてきた！\nこの際、少しくらいなら呪われても――
294 = "うん、なんだか\\n普通に食べられそうな気がしてきた！\\nこの際、少しくらいなら呪われても――"

# めぐみん
# まったく、カズマは仕方ありませんね。\nこんなものでも、呪われるよりはマシでしょう。
342 = "まったく、カズマは仕方ありませんね。\\nこんなものでも、呪われるよりはマシでしょう。"

# カズマ
# クッキー？\nこんな物があったのか？
349 = "クッキー？\\nこんな物があったのか？"

# めぐみん
# お供え物ではないですよ。\nこれは……私が作った物です。
301 = "お供え物ではないですよ。\\nこれは……私が作った物です。"

# カズマ
# え？　めぐみんが？
298 = "え？　めぐみんが？"

# めぐみん
# 最近、少しお菓子作りに凝っているんですよ。
364 = "最近、少しお菓子作りに凝っているんですよ。"

# カズマ
# ふーん、それで俺に食べて貰おうと\n持ってきたわけか。\n可愛いところがあるじゃないか。
337 = "ふーん、それで俺に食べて貰おうと\\n持ってきたわけか。\\n可愛いところがあるじゃないか。"

# めぐみん
# ど、どうしてそういう思考になるのか\n理解に苦しみます。
322 = "ど、どうしてそういう思考になるのか\\n理解に苦しみます。"

# めぐみん
# ただ、今日はなんとなく、\nクッキーを持ち歩きたい気分だっただけですよ？
315 = "ただ、今日はなんとなく、\\nクッキーを持ち歩きたい気分だっただけですよ？"

# カズマ
# 何それ、どんな気分？
352 = "何それ、どんな気分？"

# めぐみん
# ……それよりも、どうするんですか？\nいらないなら私１人で食べますが。
278 = "……それよりも、どうするんですか？\\nいらないなら私１人で食べますが。"

# カズマ
# 食う！　ありがたくいただきます！
399 = "食う！　ありがたくいただきます！"

# めぐみん
# あ、味は保証しませんからね。
287 = "あ、味は保証しませんからね。"

# カズマ
# 安心しろ、空腹は最高の調味料なんだ。
356 = "安心しろ、空腹は最高の調味料なんだ。"

# めぐみん
# その表現は、ちょっとムカつくからやめてください。
310 = "その表現は、ちょっとムカつくからやめてください。"

# カズマ
# ではありがたく、いただきます。\nもぐもぐ……。
320 = "ではありがたく、いただきます。\\nもぐもぐ……。"

# めぐみん
# ……どうですか？
279 = "……どうですか？"

# カズマ
# 意外に美味いじゃないか！
361 = "意外に美味いじゃないか！"

# めぐみん
# お、おお……。
299 = "お、おお……。"

# カズマ
# 正直、期待はしてなかったけどいけるって。\nはぁ～、生き返るぅ～。
366 = "正直、期待はしてなかったけどいけるって。\\nはぁ～、生き返るぅ～。"

# めぐみん
# 期待していなかったは余計です。
365 = "期待していなかったは余計です。"

# カズマ
# 悪い悪い。\nだけど本当に美味いぜ？
360 = "悪い悪い。\\nだけど本当に美味いぜ？"

# めぐみん
# ……そうですか。\nまあ、なら、よかったです。
276 = "……そうですか。\\nまあ、なら、よかったです。"

# カズマ
# ほら、めぐみんも見てないで食べようぜ。\nいざというときは体力がものを言うんだぞ？
339 = "ほら、めぐみんも見てないで食べようぜ。\\nいざというときは体力がものを言うんだぞ？"

# カズマ
# うん、まだまだ改善の余地ありだな。
295 = "うん、まだまだ改善の余地ありだな。"

# めぐみん
# つまり、美味しくなかったということですか？
318 = "つまり、美味しくなかったということですか？"

# カズマ
# いや、不味いってわけじゃない。\nどっちかって言えば美味いぜ？
292 = "いや、不味いってわけじゃない。\\nどっちかって言えば美味いぜ？"

# カズマ
# だけど、めぐみんには\nこの程度で満足してもらいたくない。\nやるなら極めようぜ！
317 = "だけど、めぐみんには\\nこの程度で満足してもらいたくない。\\nやるなら極めようぜ！"

# めぐみん
# はあ……。
333 = "はあ……。"

# カズマ
# ほら、めぐみんも見てないで食べようぜ。\nいざというときは体力がものを言うんだぞ？
# 339 = "ほら、めぐみんも見てないで食べようぜ。\\nいざというときは体力がものを言うんだぞ？"

# カズマ
# 飲み物が欲しくなるなぁ。\n粉っぽくて口の中の水分を持ってかれる。
401 = "飲み物が欲しくなるなぁ。\\n粉っぽくて口の中の水分を持ってかれる。"

# めぐみん
# だから……失敗作だと言ったじゃないですか。
316 = "だから……失敗作だと言ったじゃないですか。"

# カズマ
# けど、今は贅沢を言ってる場合じゃないしな。\nありがたくいただくよ。
302 = "けど、今は贅沢を言ってる場合じゃないしな。\\nありがたくいただくよ。"

# めぐみん
# ……なんでしょうね。\nこの湧き上がる複雑な感情は。
281 = "……なんでしょうね。\\nこの湧き上がる複雑な感情は。"

# カズマ
# ほら、めぐみんも見てないで食べようぜ。\nいざというときは体力がものを言うんだぞ？
# 339 = "ほら、めぐみんも見てないで食べようぜ。\\nいざというときは体力がものを言うんだぞ？"

# めぐみん
# そうですね。\nでは、いただきます。
307 = "そうですね。\\nでは、いただきます。"

# カズマ
# ああ、遠慮せずどんどん食べろ。
288 = "ああ、遠慮せずどんどん食べろ。"

# めぐみん
# それは私のセリフだと思いますが？
313 = "それは私のセリフだと思いますが？"

# カズマ
# けどさ、なんでもっと早くクッキーがあるって\n言ってくれなかったんだ？
303 = "けどさ、なんでもっと早くクッキーがあるって\\n言ってくれなかったんだ？"

# めぐみん
# ……忘れていたからです。
284 = "……忘れていたからです。"

# カズマ
# へー。
338 = "へー。"

# めぐみん
# なんですその目は。
328 = "なんですその目は。"

# カズマ
# いやぁ、めぐみんにも可愛いところが\nあるんだなと思っただけだよ。
293 = "いやぁ、めぐみんにも可愛いところが\\nあるんだなと思っただけだよ。"

# めぐみん
# にも、とはなんですか！\n失礼なっ！
332 = "にも、とはなんですか！\\n失礼なっ！"

# カズマ
# あれ？\nもう最後の１枚か。
289 = "あれ？\\nもう最後の１枚か。"

# めぐみん
# 私はいいですから、カズマが食べてください。
394 = "私はいいですから、カズマが食べてください。"

# めぐみん
# はうっ！？\nこ、こここ、これは違うのです！\nなんというか――
335 = "はうっ！？\\nこ、こここ、これは違うのです！\\nなんというか――"

# カズマ
# まあ、なんだ。\n半分にして２人で食べるか。
340 = "まあ、なんだ。\\n半分にして２人で食べるか。"

# めぐみん
# ……はい。
282 = "……はい。"

[selections]
# 361 = "意外に美味いじゃないか！"
341 = "まだまだ改善の余地ありだな"
400 = "飲み物が欲しくなるな"
