# root_c05.txt.scn

[info]
0 = ""

[characters]
213 = "カズマ（Ｍ）"
211 = "アクア＆めぐみん"
210 = "アクア"
208 = "めぐみん"
212 = "カズマ"
214 = "ダクネス"

[character_subs]
# 212 = "カズマ"
258 = "２人"

[script]
# lines: 38

# カズマ（Ｍ）
# display as カズマ
# （さて、外で食うにしても\n　あんまり金は使いたくないし……）
246 = "（さて、外で食うにしても\\n　あんまり金は使いたくないし……）"

# カズマ（Ｍ）
# display as カズマ
# （って、財布持って来てなかった！）
247 = "（って、財布持って来てなかった！）"

# カズマ（Ｍ）
# display as カズマ
# （ボーッとしてていかんな。\n　もう少し気を引き締めないと）
254 = "（ボーッとしてていかんな。\\n　もう少し気を引き締めないと）"

# アクア＆めぐみん
# display as ２人
# えぇーーーっ！？
191 = "えぇーーーっ！？"

# カズマ（Ｍ）
# display as カズマ
# （なっ、なんだ！？）
250 = "（なっ、なんだ！？）"

# アクア
# ちょっと、それ、本気なの？
200 = "ちょっと、それ、本気なの？"

# めぐみん
# ダクネスが本気だというのなら、\n止めはしませんが……。
215 = "ダクネスが本気だというのなら、\\n止めはしませんが……。"

# カズマ（Ｍ）
# display as カズマ
# （妙に深刻そうだな。\n　いったい、なんの話をしているんだ？）
255 = "（妙に深刻そうだな。\\n　いったい、なんの話をしているんだ？）"

# カズマ
# おい、何かあったのか？
194 = "おい、何かあったのか？"

# ダクネス
# なっ、カズマ！？
204 = "なっ、カズマ！？"

# めぐみん
# ど、どど、どうしているんですか！？\nご飯を食べに行ったのでしょう！？
201 = "ど、どど、どうしているんですか！？\\nご飯を食べに行ったのでしょう！？"

# カズマ
# 財布を忘れて取りに戻って来たんだよ。
243 = "財布を忘れて取りに戻って来たんだよ。"

# カズマ
# それよりも、大声を出してどうしたんだ。
199 = "それよりも、大声を出してどうしたんだ。"

# アクア
# 別に何もないわよ。\nええ、何もないわ。
217 = "別に何もないわよ。\\nええ、何もないわ。"

# めぐみん
# そうです、何もありません。\nええ、何もありませんとも。
198 = "そうです、何もありません。\\nええ、何もありませんとも。"

# カズマ（Ｍ）
# display as カズマ
# （怪しい……）
256 = "（怪しい……）"

# カズマ
# おい、ダクネス。
193 = "おい、ダクネス。"

# ダクネス
# な、何もないぞ！
203 = "な、何もないぞ！"

# カズマ（Ｍ）
# display as カズマ
# （あからさまに動揺してやがる）
244 = "（あからさまに動揺してやがる）"

# アクア
# ほ、本当になんでもないわよ？\nただのガールズトークよ。
207 = "ほ、本当になんでもないわよ？\\nただのガールズトークよ。"

# めぐみん
# そうです、ただのガールズトークなんです。\n男子禁制です。
197 = "そうです、ただのガールズトークなんです。\\n男子禁制です。"

# ダクネス
# そういうわけだ。\nカズマは気にしなくていいんだぞ。
196 = "そういうわけだ。\\nカズマは気にしなくていいんだぞ。"

# カズマ（Ｍ）
# display as カズマ
# （絶対に嘘だな……）
257 = "（絶対に嘘だな……）"

# カズマ（Ｍ）
# display as カズマ
# （まぁ、でも、ここで追求して\n　答えがくるとは思えないし、放っておくか）
251 = "（まぁ、でも、ここで追求して\\n　答えがくるとは思えないし、放っておくか）"

# カズマ（Ｍ）
# display as カズマ
# （むしろ、話を聞き出したことで\n　トラブルに巻き込まれるってのもありえるし）
253 = "（むしろ、話を聞き出したことで\\n　トラブルに巻き込まれるってのもありえるし）"

# カズマ（Ｍ）
# display as カズマ
# （まったく。\n　どうしてこの家にはトラブルの種しかないんだ）
252 = "（まったく。\\n　どうしてこの家にはトラブルの種しかないんだ）"

# カズマ
# はぁ……。
205 = "はぁ……。"

# めぐみん
# あ、またため息。\n確かに多いですね。
190 = "あ、またため息。\\n確かに多いですね。"

# アクア
# やっぱり、そうなのかしら？
209 = "やっぱり、そうなのかしら？"

# ダクネス
# …………。
189 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （な、なんだ？\n　なぜそこで俺を見る！\n　やっぱり、俺のことを話してたのか？）
249 = "（な、なんだ？\\n　なぜそこで俺を見る！\\n　やっぱり、俺のことを話してたのか？）"

# めぐみん
# じー……。
195 = "じー……。"

# アクア
# じー……。
# 195 = "じー……。"

# カズマ
# な、なんだよ。
202 = "な、なんだよ。"

# アクア
# へっ、別になんでもないわよ。\nねえ、めぐみん？
206 = "へっ、別になんでもないわよ。\\nねえ、めぐみん？"

# めぐみん
# ええ、なんでもありませんよ？
192 = "ええ、なんでもありませんよ？"

# カズマ（Ｍ）
# display as カズマ
# （うわぁ、嫌な予感しかしねー）
245 = "（うわぁ、嫌な予感しかしねー）"

# カズマ（Ｍ）
# display as カズマ
# （とりあえず、この異様な空気の部屋から\n　脱出だ脱出！）
248 = "（とりあえず、この異様な空気の部屋から\\n　脱出だ脱出！）"

