# root_d03.txt.scn

[info]
0 = ""

[characters]
165 = "カズマ（Ｍ）"
168 = "ダクネス"
164 = "カズマ"
167 = "クリス"

[character_subs]
# 164 = "カズマ"
207 = "？？？"

[script]
# lines: 28

# カズマ（Ｍ）
# display as カズマ
# （クリスは……ああ、いたいた）
206 = "（クリスは……ああ、いたいた）"

# カズマ（Ｍ）
# display as カズマ
# （ばれたら面倒だから\n　念のため、少し距離を取って後をつけるか）
205 = "（ばれたら面倒だから\\n　念のため、少し距離を取って後をつけるか）"

# カズマ（Ｍ）
# display as カズマ
# （それにしても、どこに行くつもりなんだ？\n　適当にぶらぶらしているように見えるけど）
203 = "（それにしても、どこに行くつもりなんだ？\\n　適当にぶらぶらしているように見えるけど）"

# ダクネス
# display as ？？？
# カズマ？\nこんなところで一体、何をしているんだ？
166 = "カズマ？\\nこんなところで一体、何をしているんだ？"

# カズマ（Ｍ）
# display as カズマ
# （うおっ！？）
200 = "（うおっ！？）"

# カズマ
# なんだ、ダクネスか。\nこっちは今取り込み中なんだ。\n用がないなら放っておいてくれ。
157 = "なんだ、ダクネスか。\\nこっちは今取り込み中なんだ。\\n用がないなら放っておいてくれ。"

# ダクネス
# 取り込み中？\n何かクエストでも受けたのか？\n私にできることなら力になるぞ。
170 = "取り込み中？\\n何かクエストでも受けたのか？\\n私にできることなら力になるぞ。"

# カズマ
# あー、いや、\nちょっとクリスを調査しているだけだから\n俺だけで十分だ。
151 = "あー、いや、\\nちょっとクリスを調査しているだけだから\\n俺だけで十分だ。"

# ダクネス
# ふ、ふふ、さすがカズマだな。
160 = "ふ、ふふ、さすがカズマだな。"

# カズマ
# なんで……？
159 = "なんで……？"

# ダクネス
# 直接女を罵倒するだけでは満足できなくなったの\nだろう？
198 = "直接女を罵倒するだけでは満足できなくなったの\\nだろう？"

# ダクネス
# だからこうしてストーキングのスキルを磨き、\n恐怖で女を支配する術を模索し始めた。
154 = "だからこうしてストーキングのスキルを磨き、\\n恐怖で女を支配する術を模索し始めた。"

# ダクネス
# なんてクズなんだ、お前は！\nさすが私の見込んだ男！
158 = "なんてクズなんだ、お前は！\\nさすが私の見込んだ男！"

# カズマ
# お前はどうしてそうやって思考が飛躍するかな？\nそろそろ本気で殴んぞ！
153 = "お前はどうしてそうやって思考が飛躍するかな？\\nそろそろ本気で殴んぞ！"

# ダクネス
# なるほど、\n私にはドメスティックバイオレンスというわけか！
156 = "なるほど、\\n私にはドメスティックバイオレンスというわけか！"

# ダクネス
# 暴力で思考を支配し、心までも組み伏せ、\n部屋の隅で震える私を下卑た笑みで見下ろすのだな！
174 = "暴力で思考を支配し、心までも組み伏せ、\\n部屋の隅で震える私を下卑た笑みで見下ろすのだな！"

# カズマ
# ちょっと黙ろうか！\nここは人がたくさんいますからね！
155 = "ちょっと黙ろうか！\\nここは人がたくさんいますからね！"

# ダクネス
# むご、むご、むご、むご！
162 = "むご、むご、むご、むご！"

# カズマ（Ｍ）
# display as カズマ
# （って、あれ？\n　クリスはどこ行った？）
204 = "（って、あれ？\\n　クリスはどこ行った？）"

# ダクネス
# むごっ、むぐぐ、むぐぐぐ！！
163 = "むごっ、むぐぐ、むぐぐぐ！！"

# カズマ
# いいか、お前はもう屋敷に帰ってろ！
152 = "いいか、お前はもう屋敷に帰ってろ！"

# カズマ
# あと念のため言っておくが、\n変なこと言ってまわったりしたら、本当に――
150 = "あと念のため言っておくが、\\n変なこと言ってまわったりしたら、本当に――"

# ダクネス
# ぷはっ！　ほ、本当に、何をするつもりだ！
161 = "ぷはっ！　ほ、本当に、何をするつもりだ！"

# カズマ
# ああー、もうめんどうなやつだなお前は！
149 = "ああー、もうめんどうなやつだなお前は！"

# カズマ（Ｍ）
# display as カズマ
# （くそっ、クリスはどこに行ったんだ……）
201 = "（くそっ、クリスはどこに行ったんだ……）"

# クリス
# …………。
148 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、いたいた。\n　店を覗いていたのか、助かったぜ）
199 = "（ああ、いたいた。\\n　店を覗いていたのか、助かったぜ）"

# カズマ（Ｍ）
# display as カズマ
# （こっちには気付いていないみたいだな。\n　よし、もう少し後を追うか）
202 = "（こっちには気付いていないみたいだな。\\n　よし、もう少し後を追うか）"

