# root_a06.txt.scn

[info]
0 = ""

[characters]
130 = "カズマ（Ｍ）"
129 = "カズマ"
128 = "アクア"

[character_subs]
# 129 = "カズマ"

[script]
# lines: 22

# カズマ（Ｍ）
# display as カズマ
# （その日、アクアは俺達の前に顔を見せなかった。\n　マジで二日酔いだったのかもしれない）
153 = "（その日、アクアは俺達の前に顔を見せなかった。\\n　マジで二日酔いだったのかもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （そして――）
152 = "（そして――）"

# カズマ
# ぐ―……すー……。
127 = "ぐ―……すー……。"

# カズマ（Ｍ）
# display as カズマ
# （……ん？）
145 = "（……ん？）"

# カズマ（Ｍ）
# display as カズマ
# （なんだ？\n　音が聞こえたような……誰か起きてるのか？）
156 = "（なんだ？\\n　音が聞こえたような……誰か起きてるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （でも、俺が部屋に戻ったときは、\n　もうダクネスもめぐみんも寝てたよな？）
154 = "（でも、俺が部屋に戻ったときは、\\n　もうダクネスもめぐみんも寝てたよな？）"

# カズマ（Ｍ）
# display as カズマ
# （もしかして、泥棒か！？）
157 = "（もしかして、泥棒か！？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、この屋敷には\n　アクアの結界が張ってあるはずだし）
150 = "（いや、この屋敷には\\n　アクアの結界が張ってあるはずだし）"

# カズマ（Ｍ）
# display as カズマ
# （……一応、確かめてくるか）
146 = "（……一応、確かめてくるか）"

# カズマ（Ｍ）
# display as カズマ
# （音がするのは、廊下の先か）
160 = "（音がするのは、廊下の先か）"

# カズマ（Ｍ）
# display as カズマ
# （いきなり不審者に鉢合わせて荒事、\n　ってのも嫌だからな。\n　潜伏スキルで見つからないようにして、と）
149 = "（いきなり不審者に鉢合わせて荒事、\\n　ってのも嫌だからな。\\n　潜伏スキルで見つからないようにして、と）"

# カズマ（Ｍ）
# display as カズマ
# （……これじゃ、俺のほうが不審者だな）
144 = "（……これじゃ、俺のほうが不審者だな）"

# アクア
# …………。
126 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （あれは、アクア……か？）
148 = "（あれは、アクア……か？）"

# アクア
# …………。
# 126 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （なんだ、アクアか。\n　まったく人騒がせな）
155 = "（なんだ、アクアか。\\n　まったく人騒がせな）"

# アクア
# 良かった、誰も気がつかなかったみたいね。
143 = "良かった、誰も気がつかなかったみたいね。"

# カズマ（Ｍ）
# display as カズマ
# （ん？　あいつはどこへいくつもりだ？）
158 = "（ん？　あいつはどこへいくつもりだ？）"

# カズマ（Ｍ）
# display as カズマ
# （あっちはアクアの部屋とは逆方向。\n　玄関しかないはずだ）
147 = "（あっちはアクアの部屋とは逆方向。\\n　玄関しかないはずだ）"

# カズマ（Ｍ）
# display as カズマ
# （こんな時間に外へ？）
151 = "（こんな時間に外へ？）"

# カズマ
# …………。
# 126 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （気になるな。\n　ちょっと追ってみるか）
159 = "（気になるな。\\n　ちょっと追ってみるか）"

