# root_e17.txt.scn

[info]
0 = ""

[characters]
162 = "アクア"
159 = "めぐみん"
160 = "ゆんゆん"
164 = "カズマ"
166 = "クリス"

[character_subs]

[script]
# lines: 19

# アクア
# 屋敷に戻ってきたはいいけど、\n結局、最終対決って何をするのよ。
170 = "屋敷に戻ってきたはいいけど、\\n結局、最終対決って何をするのよ。"

# めぐみん
# カズマの考えることです。\nどうせろくでもない、\nゲスな内容に違いありません。
165 = "カズマの考えることです。\\nどうせろくでもない、\\nゲスな内容に違いありません。"

# ゆんゆん
# えっ！？\nそ、そんな……！
150 = "えっ！？\\nそ、そんな……！"

# カズマ
# 内容を聞く前から散々な言われようだな！
168 = "内容を聞く前から散々な言われようだな！"

# めぐみん
# 日頃の行いが悪いせいですよ。
172 = "日頃の行いが悪いせいですよ。"

# クリス
# まあまあ、ゲスな内容かどうかは\n聞けばわかるんだし、進めて。
157 = "まあまあ、ゲスな内容かどうかは\\n聞けばわかるんだし、進めて。"

# カズマ
# あー、それじゃ発表するぞ。\n俺が考えた最終対決の内容は――
147 = "あー、それじゃ発表するぞ。\\n俺が考えた最終対決の内容は――"

# カズマ
# アクアお世話対決だ！\n２人には、このグータラを自分なりに\n世話してもらう！
163 = "アクアお世話対決だ！\\n２人には、このグータラを自分なりに\\n世話してもらう！"

# めぐみん
# はあ？
154 = "はあ？"

# ゆんゆん
# ええ？
149 = "ええ？"

# アクア
# ちょっとカズマ！　グータラって何よ！
152 = "ちょっとカズマ！　グータラって何よ！"

# カズマ
# まあ聞けって。\n別にお前に何かしろって\n言ってるわけじゃないんだ。
158 = "まあ聞けって。\\n別にお前に何かしろって\\n言ってるわけじゃないんだ。"

# カズマ
# 逆に、２人がお前を\n甲斐甲斐しくお世話してくれるんだぞ？\nお前はただダラダラしてるだけでいい。
187 = "逆に、２人がお前を\\n甲斐甲斐しくお世話してくれるんだぞ？\\nお前はただダラダラしてるだけでいい。"

# カズマ
# こんな美味しい思い、\nそうそうできるもんじゃないだろ？
151 = "こんな美味しい思い、\\nそうそうできるもんじゃないだろ？"

# アクア
# ふふふ、仕方ないわね。\nそういうことなら力を貸してあげるわ。\nさあ、存分にお世話しなさい？
155 = "ふふふ、仕方ないわね。\\nそういうことなら力を貸してあげるわ。\\nさあ、存分にお世話しなさい？"

# カズマ
# まあ、そういうわけだ。\n２人とも頑張れ。
156 = "まあ、そういうわけだ。\\n２人とも頑張れ。"

# めぐみん
# いいでしょう。\nどのような勝負であろうと勝つまでのことです。
148 = "いいでしょう。\\nどのような勝負であろうと勝つまでのことです。"

# ゆんゆん
# わ、私だって！\n絶対に負けないんだから！
161 = "わ、私だって！\\n絶対に負けないんだから！"

# カズマ
# では、最終対決を始める！\nまずはゆんゆんからだ！
153 = "では、最終対決を始める！\\nまずはゆんゆんからだ！"

