# root_a05.txt.scn

[info]
0 = ""

[characters]
178 = "めぐみん"
184 = "カズマ"
186 = "ダクネス"
185 = "カズマ（Ｍ）"

[character_subs]
# 184 = "カズマ"

[script]
# lines: 32

# めぐみん
# おはようございます、カズマ。
162 = "おはようございます、カズマ。"

# カズマ
# ふああああ。\nおはよう、みんな。早いな。
173 = "ふああああ。\\nおはよう、みんな。早いな。"

# ダクネス
# そうでもないぞ。\n私もめぐみんも、今しがた起きたところだ。
166 = "そうでもないぞ。\\n私もめぐみんも、今しがた起きたところだ。"

# カズマ
# そうなのか。\nで、まあ想像はつくが、アクアは？
167 = "そうなのか。\\nで、まあ想像はつくが、アクアは？"

# めぐみん
# まだ寝ているんじゃないですか？
177 = "まだ寝ているんじゃないですか？"

# ダクネス
# あれだけ飲んでいたらな。\nもしかしたら、二日酔いになってるかもしれない。
158 = "あれだけ飲んでいたらな。\\nもしかしたら、二日酔いになってるかもしれない。"

# カズマ（Ｍ）
# display as カズマ
# （あり得るなぁ。\n　まあ、しばらくはほっといてもいいだろ）
214 = "（あり得るなぁ。\\n　まあ、しばらくはほっといてもいいだろ）"

# カズマ
# でだ、ダクネスに\nちょっと訊きたかったんだけどさ。
172 = "でだ、ダクネスに\\nちょっと訊きたかったんだけどさ。"

# ダクネス
# ん、なんだ？
182 = "ん、なんだ？"

# カズマ
# 昨夜の霜降り赤ガニ、\nあれって買ったらいくら位するもんなのかなって。
192 = "昨夜の霜降り赤ガニ、\\nあれって買ったらいくら位するもんなのかなって。"

# ダクネス
# うーん、食べた感じ、かなりの上物だったから、\n十数万エリスはくだらないんじゃないか？
161 = "うーん、食べた感じ、かなりの上物だったから、\\n十数万エリスはくだらないんじゃないか？"

# カズマ
# じゅうすうまん！？
165 = "じゅうすうまん！？"

# ダクネス
# 数日バイトをしたくらいで、\n買える物ではないのは確かだな。
191 = "数日バイトをしたくらいで、\\n買える物ではないのは確かだな。"

# カズマ
# いや、バイトじゃなくて、アクアはお布施って――
159 = "いや、バイトじゃなくて、アクアはお布施って――"

# カズマ（Ｍ）
# display as カズマ
# （ああ、そうか。\n　ダクネスとめぐみんはアクアが女神だってことを\n　信じてないんだっけ）
212 = "（ああ、そうか。\\n　ダクネスとめぐみんはアクアが女神だってことを\\n　信じてないんだっけ）"

# カズマ（Ｍ）
# display as カズマ
# （いや、信じるも何も、\n　アクアにそんな大金を包む変わり者がいるかも\n　怪しいか）
215 = "（いや、信じるも何も、\\n　アクアにそんな大金を包む変わり者がいるかも\\n　怪しいか）"

# カズマ
# じゃあ、あの金の出所はどこなんだ。
164 = "じゃあ、あの金の出所はどこなんだ。"

# ダクネス
# 私もずっとそれが気になっているんだ。
211 = "私もずっとそれが気になっているんだ。"

# カズマ
# やっぱり非合法な手段か。
181 = "やっぱり非合法な手段か。"

# ダクネス
# アクアがそんなことをするとは思えないが。
183 = "アクアがそんなことをするとは思えないが。"

# めぐみん
# それに非合法とはいえ、\nアクアが簡単にお金を稼げると思えません。
170 = "それに非合法とはいえ、\\nアクアが簡単にお金を稼げると思えません。"

# カズマ
# さらっと酷いこと言うなお前は。
163 = "さらっと酷いこと言うなお前は。"

# カズマ
# もしや、大人の世界へ！？
179 = "もしや、大人の世界へ！？"

# ダクネス
# 大人のっ……世界！？\nく、詳しく説明を頼む！
189 = "大人のっ……世界！？\\nく、詳しく説明を頼む！"

# カズマ
# いやいや、ないない。\nあいつに限ってそういうのは絶対無いから。
160 = "いやいや、ないない。\\nあいつに限ってそういうのは絶対無いから。"

# カズマ
# まさか、カニ漁に出ていたとか？
175 = "まさか、カニ漁に出ていたとか？"

# ダクネス
# それはないだろう。\nここから海は遠いぞ？
171 = "それはないだろう。\\nここから海は遠いぞ？"

# めぐみん
# それに、漁となったら\n結構な日数がかかりますよ？\n日帰りでなんて無理です。
169 = "それに、漁となったら\\n結構な日数がかかりますよ？\\n日帰りでなんて無理です。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、それもそうか。\n　というか、そんな簡単に稼げるなら\n　みんなやってるよな）
213 = "（ああ、それもそうか。\\n　というか、そんな簡単に稼げるなら\\n　みんなやってるよな）"

# カズマ
# まあ、なんにせよ\n俺達に迷惑がかかる手段じゃなきゃいいけどなぁ。
174 = "まあ、なんにせよ\\n俺達に迷惑がかかる手段じゃなきゃいいけどなぁ。"

# ダクネス
# そこはなんとも言えんな。\n苦情や取り立てが来ないことを祈るしかない。
168 = "そこはなんとも言えんな。\\n苦情や取り立てが来ないことを祈るしかない。"

# カズマ（Ｍ）
# display as カズマ
# （はあ……。\n　どうにも不安が拭いきれないぜ）
216 = "（はあ……。\\n　どうにも不安が拭いきれないぜ）"

[selections]
180 = "やっぱり非合法な手段か"
# 179 = "もしや、大人の世界へ！？"
176 = "まさかカニ漁に出ていた？"
