# root_a14.txt.scn

[info]
0 = ""

[characters]
217 = "カズマ（Ｍ）"
213 = "アクア"
216 = "カズマ"
211 = "めぐみん"
218 = "ダクネス"

[character_subs]
# 216 = "カズマ"

[script]
# lines: 36

# カズマ（Ｍ）
# display as カズマ
# （そして翌日。\n　ドレスの一件で、アクアにも\n　少しは気合が入ったかと期待したんだが）
261 = "（そして翌日。\\n　ドレスの一件で、アクアにも\\n　少しは気合が入ったかと期待したんだが）"

# アクア
# ねえ、カズマ？
208 = "ねえ、カズマ？"

# カズマ
# なんだよ。
207 = "なんだよ。"

# アクア
# 私、ふと思ったんだけど、\n特訓なんてしなくても優勝できるんじゃないかしら。
257 = "私、ふと思ったんだけど、\\n特訓なんてしなくても優勝できるんじゃないかしら。"

# カズマ
# その根拠は。
196 = "その根拠は。"

# アクア
# だって私、女神だし。
201 = "だって私、女神だし。"

# カズマ
# 根拠は？
228 = "根拠は？"

# アクア
# それに私、エリスの先輩だし。
198 = "それに私、エリスの先輩だし。"

# カズマ（Ｍ）
# display as カズマ
# （どうしよう、殴りたい）
262 = "（どうしよう、殴りたい）"

# カズマ
# おい、アクア。\nお前は３００万の借金に加え、\nドレスの修理代も払わなきゃいけないんだぞ。
194 = "おい、アクア。\\nお前は３００万の借金に加え、\\nドレスの修理代も払わなきゃいけないんだぞ。"

# アクア
# それはわかってるわよ。\nでもね、私、昨夜色々考えてみたんだけど――
199 = "それはわかってるわよ。\\nでもね、私、昨夜色々考えてみたんだけど――"

# カズマ
# ほお、考えてみた。
210 = "ほお、考えてみた。"

# アクア
# 私がどんなに不利な状況の陥っても、\n負けるっていうイメージが湧かなかったのよね。
258 = "私がどんなに不利な状況の陥っても、\\n負けるっていうイメージが湧かなかったのよね。"

# カズマ
# うん、根拠は？
191 = "うん、根拠は？"

# アクア
# 女の勘ってやつよ。
224 = "女の勘ってやつよ。"

# カズマ（Ｍ）
# display as カズマ
# （うん、殴りたい）
260 = "（うん、殴りたい）"

# めぐみん
# アクア。\nそれは自信ではなく慢心ではないのですか？
214 = "アクア。\\nそれは自信ではなく慢心ではないのですか？"

# ダクネス
# それにこれはエリス様の名を冠した\nコンテストなんだぞ。
197 = "それにこれはエリス様の名を冠した\\nコンテストなんだぞ。"

# ダクネス
# ただ容姿が優れていれば、\n優勝できる低俗なものとは違うんだ。
200 = "ただ容姿が優れていれば、\\n優勝できる低俗なものとは違うんだ。"

# アクア
# もう、みんなは何もわかってないわね。
212 = "もう、みんなは何もわかってないわね。"

# ダクネス
# というと？
203 = "というと？"

# アクア
# エリスは何？　女神でしょ？
215 = "エリスは何？　女神でしょ？"

# めぐみん
# 当然じゃないですか。
227 = "当然じゃないですか。"

# アクア
# そして私も女神！
195 = "そして私も女神！"

# めぐみん
# はあ……。
209 = "はあ……。"

# アクア
# 人間がどんなに努力をしても決して出せない、\n崇高さとか神々しさってやつを\n女神は生まれながらにして持ち合わせているの。
220 = "人間がどんなに努力をしても決して出せない、\\n崇高さとか神々しさってやつを\\n女神は生まれながらにして持ち合わせているの。"

# ダクネス
# はあ……。
# 209 = "はあ……。"

# アクア
# つまり私の神気にあてられたら、\n絶対に私以外を選ぶことはできないってわけよ。
202 = "つまり私の神気にあてられたら、\\n絶対に私以外を選ぶことはできないってわけよ。"

# カズマ
# うん、じゃあ特訓をするか。
190 = "うん、じゃあ特訓をするか。"

# アクア
# ええ！\n私の話聞いてた！？
193 = "ええ！\\n私の話聞いてた！？"

# カズマ
# 聞いてた、聞いてた。\n俺も毎日、お前の神気にあてられて大変だわ。
259 = "聞いてた、聞いてた。\\n俺も毎日、お前の神気にあてられて大変だわ。"

# アクア
# 信じてないでしょ！
221 = "信じてないでしょ！"

# カズマ
# というわけで、ダクネスとめぐみんも特訓に\nつきあってくれ。
204 = "というわけで、ダクネスとめぐみんも特訓に\\nつきあってくれ。"

# ダクネス
# どういう訳かはさっぱりわからんが、\n別に構わないぞ。
206 = "どういう訳かはさっぱりわからんが、\\n別に構わないぞ。"

# めぐみん
# ええ、私もです。
192 = "ええ、私もです。"

# カズマ
# というわけで朝飯食ったら特訓だからな。
205 = "というわけで朝飯食ったら特訓だからな。"

