# root_e04.txt.scn

[info]
0 = ""

[characters]
373 = "ゆんゆん"
381 = "カズマ"
369 = "めぐみん"
383 = "カズマ（Ｍ）"
384 = "ダクネス"
378 = "アクア"

[character_subs]
# 381 = "カズマ"

[script]
# lines: 94

# ゆんゆん
# ウインドブレス！
379 = "ウインドブレス！"

# カズマ
# 助かったぜゆんゆん、このまま屋敷まで\n濡れた服で帰る羽目になるかと思った。
388 = "助かったぜゆんゆん、このまま屋敷まで\\n濡れた服で帰る羽目になるかと思った。"

# ゆんゆん
# い、いえ！\n助けてもらったんですから、\nこのくらいに当然です。
318 = "い、いえ！\\n助けてもらったんですから、\\nこのくらいに当然です。"

# めぐみん
# ゆんゆん、よそ見をしていないで\nもっと隅々まで風を当ててください、\n私の服が乾きません。
374 = "ゆんゆん、よそ見をしていないで\\nもっと隅々まで風を当ててください、\\n私の服が乾きません。"

# ゆんゆん
# もう、めぐみんも中級魔法くらい覚えてよ。\nそうすれば自分で魔法を使って乾かせるじゃない。
370 = "もう、めぐみんも中級魔法くらい覚えてよ。\\nそうすれば自分で魔法を使って乾かせるじゃない。"

# めぐみん
# 私のスキルポイントは\n全て爆裂魔法のためにあるのです。
451 = "私のスキルポイントは\\n全て爆裂魔法のためにあるのです。"

# めぐみん
# そんな無駄なことに使うポイントは\n１ポイントだってありませんから？
337 = "そんな無駄なことに使うポイントは\\n１ポイントだってありませんから？"

# カズマ（Ｍ）
# display as カズマ
# （無駄なことって……\n　いや、すごく役に立ってるぞ？）
463 = "（無駄なことって……\\n　いや、すごく役に立ってるぞ？）"

# めぐみん
# まあ、こんなところでしょう。\nようやく服が乾きました。\nご苦労です、ゆんゆん。
368 = "まあ、こんなところでしょう。\\nようやく服が乾きました。\\nご苦労です、ゆんゆん。"

# ゆんゆん
# ど、どういたしまして……。
351 = "ど、どういたしまして……。"

# めぐみん
# では、服も乾いたことですし、\n勝敗を決めようではありませんか！\nダクネス、カズマ、厳正な審査をお願いします！
346 = "では、服も乾いたことですし、\\n勝敗を決めようではありませんか！\\nダクネス、カズマ、厳正な審査をお願いします！"

# カズマ
# へいへい。\nあれ？　ダクネスは？
364 = "へいへい。\\nあれ？　ダクネスは？"

# ダクネス
# カズマ！\n私の服だと魚が入り込む隙間がない！
382 = "カズマ！\\n私の服だと魚が入り込む隙間がない！"

# カズマ
# ……おい、審査だ。\nくだらないこと言ってないでこっちに来い。
314 = "……おい、審査だ。\\nくだらないこと言ってないでこっちに来い。"

# ダクネス
# くだらなっ！
325 = "くだらなっ！"

# カズマ
# ふむ。\n魚の数ではめぐみんが勝るが、\n大きさはゆんゆんの方が上だな。
362 = "ふむ。\\n魚の数ではめぐみんが勝るが、\\n大きさはゆんゆんの方が上だな。"

# ゆんゆん
# ええっと……\nこの場合、どちらの勝ちになるんですか？
321 = "ええっと……\\nこの場合、どちらの勝ちになるんですか？"

# ダクネス
# そういえば、勝敗の基準については\n何も決めていなかったな。
333 = "そういえば、勝敗の基準については\\n何も決めていなかったな。"

# カズマ（Ｍ）
# display as カズマ
# （しまった……。\n　勢いだけで勝負を始めちまってたな）
457 = "（しまった……。\\n　勢いだけで勝負を始めちまってたな）"

# めぐみん
# やはり数でしょう！\nより多く魚を釣り上げた、\nこれほどわかりやすい結果はないのですからね。
372 = "やはり数でしょう！\\nより多く魚を釣り上げた、\\nこれほどわかりやすい結果はないのですからね。"

# めぐみん
# というわけで、今回も私の勝ちで決定です。
350 = "というわけで、今回も私の勝ちで決定です。"

# ゆんゆん
# ま、待って！\n数がどんなに多くても、\nめぐみんは小魚ばかりじゃない！
366 = "ま、待って！\\n数がどんなに多くても、\\nめぐみんは小魚ばかりじゃない！"

# ゆんゆん
# ここは、大きな魚を釣ったかどうかで\n決めるべきだと思うわ！
326 = "ここは、大きな魚を釣ったかどうかで\\n決めるべきだと思うわ！"

# ゆんゆん
# だから今回は私の勝ち！\n素直に負けを認めたらどう？
341 = "だから今回は私の勝ち！\\n素直に負けを認めたらどう？"

# めぐみん
# はあ？\nそのセリフをそのままお返しします。\nゆんゆんこそ負けを認めたらどうです？
359 = "はあ？\\nそのセリフをそのままお返しします。\\nゆんゆんこそ負けを認めたらどうです？"

# ゆんゆん
# だって私、負けてないもん！
342 = "だって私、負けてないもん！"

# めぐみん
# 私だって負けていません！\n負けていない以上、譲るわけにはいきませんね！
449 = "私だって負けていません！\\n負けていない以上、譲るわけにはいきませんね！"

# ゆんゆん
# こっちだって譲れないわ！
327 = "こっちだって譲れないわ！"

# めぐみん
# 審判、どちらが勝者か\nハッキリさせてください。
396 = "審判、どちらが勝者か\\nハッキリさせてください。"

# ダクネス
# ハッキリと言われても私の手には余るな。\nどうしたらいいと思う、カズマ？
385 = "ハッキリと言われても私の手には余るな。\\nどうしたらいいと思う、カズマ？"

# カズマ
# そこで俺に振るのかよ！？
334 = "そこで俺に振るのかよ！？"

# めぐみん
# 勝敗が決まるなら、誰でも構いませんよ。
389 = "勝敗が決まるなら、誰でも構いませんよ。"

# ゆんゆん
# はいっ！\nカズマさんに委ねます！
360 = "はいっ！\\nカズマさんに委ねます！"

# カズマ
# はあ……。\n俺に委ねるって言うなら、\nどんな結果になっても文句は言うなよ？
358 = "はあ……。\\n俺に委ねるって言うなら、\\nどんな結果になっても文句は言うなよ？"

# めぐみん
# 大丈夫です、\n結果にケチを付けるほど子供ではありませんよ。
395 = "大丈夫です、\\n結果にケチを付けるほど子供ではありませんよ。"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんはいざ知らず、\n　めぐみんは絶対に文句つけるだろ……）
461 = "（ゆんゆんはいざ知らず、\\n　めぐみんは絶対に文句つけるだろ……）"

# カズマ（Ｍ）
# display as カズマ
# （とはいえ決めないわけにはいかない。\n　多さを取るか大きさを取るか、\n　さて、どうする？）
458 = "（とはいえ決めないわけにはいかない。\\n　多さを取るか大きさを取るか、\\n　さて、どうする？）"

# カズマ（Ｍ）
# display as カズマ
# （ジャッジを任された以上、\n　私情は挟まず公平にだが――）
462 = "（ジャッジを任された以上、\\n　私情は挟まず公平にだが――）"

# カズマ
# よし、あえて、ここは互角としようじゃないか、\nその上でどちらが勝負に真剣だったかで決めよう。
375 = "よし、あえて、ここは互角としようじゃないか、\\nその上でどちらが勝負に真剣だったかで決めよう。"

# めぐみん
# なら、私の勝ちですね。\nこの勝負にかけた意気込みは\n並々ならないのですから！
353 = "なら、私の勝ちですね。\\nこの勝負にかけた意気込みは\\n並々ならないのですから！"

# ゆんゆん
# 私だって！\n今日こそはめぐみんに勝つんだって、\n気合いは十分だもの！
450 = "私だって！\\n今日こそはめぐみんに勝つんだって、\\n気合いは十分だもの！"

# カズマ
# ふむ、ふたりの言いたいことはわかった。\nだが最後に見せたゆんゆんの勇姿は\nインパクト大だ！
361 = "ふむ、ふたりの言いたいことはわかった。\\nだが最後に見せたゆんゆんの勇姿は\\nインパクト大だ！"

# カズマ
# 服の中に入り激しく暴れる大物を、\nまさに体を張って捕まえた根性は胸を熱くさせる。
400 = "服の中に入り激しく暴れる大物を、\\nまさに体を張って捕まえた根性は胸を熱くさせる。"

# カズマ
# そう、胸だけに胸が熱い！
332 = "そう、胸だけに胸が熱い！"

# めぐみん
# ……もしかして胸ですか？\nこの無駄に大きな胸で\n勝負を決めようというのですか？
315 = "……もしかして胸ですか？\\nこの無駄に大きな胸で\\n勝負を決めようというのですか？"

# ゆんゆん
# えっ、そ、そんなこと……\nな、ないですよね？
322 = "えっ、そ、そんなこと……\\nな、ないですよね？"

# カズマ
# ち、違う！\n確かにいいものを見せてもらったなとは思うけど、\nそういうんじゃなくてだな？
343 = "ち、違う！\\n確かにいいものを見せてもらったなとは思うけど、\\nそういうんじゃなくてだな？"

# ゆんゆん
# カ、カズマさん……。
380 = "カ、カズマさん……。"

# カズマ
# 待て、結論を急ぐな！\nゆんゆんの勝ちとは言ってないだろ！
399 = "待て、結論を急ぐな！\\nゆんゆんの勝ちとは言ってないだろ！"

# めぐみん
# では、私の勝ちということですね？
347 = "では、私の勝ちということですね？"

# カズマ
# だから、結論を急ぐなって言ってるだろ！
340 = "だから、結論を急ぐなって言ってるだろ！"

# カズマ
# いいか？\n俺としては、ゆんゆんを助けようとした\nめぐみんの行動も捨てがたい！
319 = "いいか？\\n俺としては、ゆんゆんを助けようとした\\nめぐみんの行動も捨てがたい！"

# カズマ
# 勝負の最中だというのに、\n勝敗よりも友情をとったんだからな。
390 = "勝負の最中だというのに、\\n勝敗よりも友情をとったんだからな。"

# ゆんゆん
# 友情！
392 = "友情！"

# ダクネス
# 私も同感だ。\n先程のめぐみんは実に輝いていたな。
452 = "私も同感だ。\\n先程のめぐみんは実に輝いていたな。"

# ゆんゆん
# 友情って素敵ね、めぐみん！
391 = "友情って素敵ね、めぐみん！"

# めぐみん
# な、何を変な勘違いをしてるんですか。\nあれだけ大きな魚を取り逃がしたらもったいないと\n思っただけですよ。
352 = "な、何を変な勘違いをしてるんですか。\\nあれだけ大きな魚を取り逃がしたらもったいないと\\n思っただけですよ。"

# ゆんゆん
# ええ、そうなの！
320 = "ええ、そうなの！"

# めぐみん
# ぷい！
363 = "ぷい！"

# カズマ（Ｍ）
# display as カズマ
# （うーん、この実にテンプレなツンデレ反応。\n　いっそ清々しささえ感じるぜ）
456 = "（うーん、この実にテンプレなツンデレ反応。\\n　いっそ清々しささえ感じるぜ）"

# カズマ
# なんだかんだ言っても、\nお前ら、やっぱ仲いいよな。
354 = "なんだかんだ言っても、\\nお前ら、やっぱ仲いいよな。"

# めぐみん
# だ、だから、違うと言っているではないですか！
339 = "だ、だから、違うと言っているではないですか！"

# アクア
# たっだいまー。
338 = "たっだいまー。"

# カズマ
# お前まさか、\nその格好で街から来たんじゃないだろうな。
324 = "お前まさか、\\nその格好で街から来たんじゃないだろうな。"

# アクア
# そこの茂みで着替えたのよ。\nって、随分と釣れたのね。
335 = "そこの茂みで着替えたのよ。\\nって、随分と釣れたのね。"

# めぐみん
# このほとんどが私の釣果なんですよ。
328 = "このほとんどが私の釣果なんですよ。"

# ゆんゆん
# でも、大きいのは私です！
348 = "でも、大きいのは私です！"

# アクア
# ねえ、カズマ。
357 = "ねえ、カズマ。"

# カズマ
# なんだよ。
355 = "なんだよ。"

# アクア
# これは、焼くしかないと思うの。
329 = "これは、焼くしかないと思うの。"

# ゆんゆん
# え？
323 = "え？"

# アクア
# さあ、帰って魚祭りよ！
330 = "さあ、帰って魚祭りよ！"

# めぐみん
# ちょ、ちょっと！\nまだ勝負がついていないんですから！
344 = "ちょ、ちょっと！\\nまだ勝負がついていないんですから！"

# アクア
# もう引き分けでいいじゃない。\n私、パパッと着替えてきちゃうわね。
371 = "もう引き分けでいいじゃない。\\n私、パパッと着替えてきちゃうわね。"

# カズマ（Ｍ）
# display as カズマ
# （あいつはどうして水着を持ってきたんだ……）
455 = "（あいつはどうして水着を持ってきたんだ……）"

# ゆんゆん
# ねえ、めぐみん、これってどうなるの？
356 = "ねえ、めぐみん、これってどうなるの？"

# めぐみん
# 興が削がれてしまいましたし、\n引き分けでいいんじゃないですか？
453 = "興が削がれてしまいましたし、\\n引き分けでいいんじゃないですか？"

# ゆんゆん
# つまり、勝負はおあずけってことね！
345 = "つまり、勝負はおあずけってことね！"

# カズマ（Ｍ）
# display as カズマ
# （なんで嬉しそうにしてるんだ……）
460 = "（なんで嬉しそうにしてるんだ……）"

# ゆんゆん
# 次こそは必ず勝つわっ！\nうん、次こそ絶対に負けないんだから！
401 = "次こそは必ず勝つわっ！\\nうん、次こそ絶対に負けないんだから！"

# カズマ（Ｍ）
# display as カズマ
# （なるほど、次があるのが嬉しいのね）
459 = "（なるほど、次があるのが嬉しいのね）"

# ゆんゆん
# あの、みなさん。\n今日は私とめぐみんの勝負に付き合ってくださり\nありがとうございました。
316 = "あの、みなさん。\\n今日は私とめぐみんの勝負に付き合ってくださり\\nありがとうございました。"

# ダクネス
# 気にするな。\n私たちも暇を持て余していたのだからな。
402 = "気にするな。\\n私たちも暇を持て余していたのだからな。"

# ゆんゆん
# それでは、私はこれで失礼します。
336 = "それでは、私はこれで失礼します。"

# カズマ
# ん、なんでだ？\nゆんゆんも屋敷に来いよ。
377 = "ん、なんでだ？\\nゆんゆんも屋敷に来いよ。"

# ゆんゆん
# え？
# 323 = "え？"

# カズマ
# 魚を釣ったのはゆんゆんなんだ。\n食べるのは当然だろ？
454 = "魚を釣ったのはゆんゆんなんだ。\\n食べるのは当然だろ？"

# ゆんゆん
# でも、突然お邪魔したらご迷惑じゃ。
349 = "でも、突然お邪魔したらご迷惑じゃ。"

# めぐみん
# あーあ、これだからぼっちは。\n夕飯に誘われた程度でうろたえるとは情けない。
317 = "あーあ、これだからぼっちは。\\n夕飯に誘われた程度でうろたえるとは情けない。"

# ゆんゆん
# べ、別にうろたえてなんかないわよっ！\n行くわよ！　お呼ばれされるんだから！
365 = "べ、別にうろたえてなんかないわよっ！\\n行くわよ！　お呼ばれされるんだから！"

# めぐみん
# しかし、食事の前にまずお風呂ですね。\n服は乾いたとはいえ、ほのかに魚臭いです。
331 = "しかし、食事の前にまずお風呂ですね。\\n服は乾いたとはいえ、ほのかに魚臭いです。"

# ゆんゆん
# わかった！\nそれじゃ、急いで着替え取ってくるね！\nあ、パジャマも持ってくるから！
376 = "わかった！\\nそれじゃ、急いで着替え取ってくるね！\\nあ、パジャマも持ってくるから！"

# めぐみん
# 何にも言わないうちから\n泊まる気まんまんですね……。
387 = "何にも言わないうちから\\n泊まる気まんまんですね……。"

# カズマ
# まあ、いいんじゃないか。\n屋敷は広いしさ。
367 = "まあ、いいんじゃないか。\\n屋敷は広いしさ。"

