# root_c11.txt.scn

[info]
0 = ""

[characters]
453 = "カズマ（Ｍ）"
451 = "カズマ"
455 = "ダクネス"
440 = "めぐみん"
449 = "アクア"

[character_subs]
# 451 = "カズマ"

[script]
# lines: 131

# カズマ（Ｍ）
# display as カズマ
# （一睡もできなかった。\n　ダクネスとのこれからを想像していたら、\n　妄想が捗りすぎて止まらなかった……）
549 = "（一睡もできなかった。\\n　ダクネスとのこれからを想像していたら、\\n　妄想が捗りすぎて止まらなかった……）"

# カズマ（Ｍ）
# display as カズマ
# （本当につき合うとなると失敗したくないし、\n　やっぱり最高のシチュエーションで、\n　ラブラブしたいしな！）
550 = "（本当につき合うとなると失敗したくないし、\\n　やっぱり最高のシチュエーションで、\\n　ラブラブしたいしな！）"

# カズマ（Ｍ）
# display as カズマ
# （そんなこんなで、何度も\n　脳内シミュレーションを重ねてたら\n　夜が明けちまったぜ……へへヘヘ……）
544 = "（そんなこんなで、何度も\\n　脳内シミュレーションを重ねてたら\\n　夜が明けちまったぜ……へへヘヘ……）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、まだまだ検証が足りない。\n　相手はあのダクネスだ、どんなイレギュラーで\n　計画がひっくり返されるかわからん）
543 = "（しかし、まだまだ検証が足りない。\\n　相手はあのダクネスだ、どんなイレギュラーで\\n　計画がひっくり返されるかわからん）"

# カズマ（Ｍ）
# display as カズマ
# （よし、今度はまた新しい切り口で考え直すか。\n　ふふふ、待ってろダクネス！\n　俺に惚れたことを感謝させてやる！）
545 = "（よし、今度はまた新しい切り口で考え直すか。\\n　ふふふ、待ってろダクネス！\\n　俺に惚れたことを感謝させてやる！）"

# カズマ
# ん？
448 = "ん？"

# ダクネス
# あ……。\nなんだ、もう起きていたのか。
358 = "あ……。\\nなんだ、もう起きていたのか。"

# カズマ
# おはよう、ダクネス。
375 = "おはよう、ダクネス。"

# ダクネス
# おはよう。\n……カズマ、大丈夫か？\n顔色が悪いようだが。
376 = "おはよう。\\n……カズマ、大丈夫か？\\n顔色が悪いようだが。"

# カズマ
# ふふふ、いい朝だな。
431 = "ふふふ、いい朝だな。"

# ダクネス
# ちゃんと寝たのか？\n夜更かししたんじゃないだろうな？\n健康のためにも、怠惰な生活は改めるべきだぞ。
406 = "ちゃんと寝たのか？\\n夜更かししたんじゃないだろうな？\\n健康のためにも、怠惰な生活は改めるべきだぞ。"

# カズマ（Ｍ）
# display as カズマ
# （ああ！\n　これって、毎朝起こしに来てくれる\n　幼なじみみたいじゃないか！）
538 = "（ああ！\\n　これって、毎朝起こしに来てくれる\\n　幼なじみみたいじゃないか！）"

# カズマ（Ｍ）
# display as カズマ
# （いつにも増した気遣い……。\n　やっぱり、これが愛ってヤツなんだろうか？）
539 = "（いつにも増した気遣い……。\\n　やっぱり、これが愛ってヤツなんだろうか？）"

# ダクネス
# ほら、起きて顔を洗ってシャキっとしろ。\nもう朝食の準備もできているぞ。\n早く着替えろ。
433 = "ほら、起きて顔を洗ってシャキっとしろ。\\nもう朝食の準備もできているぞ。\\n早く着替えろ。"

# カズマ
# ああ、わかったよ。
361 = "ああ、わかったよ。"

# カズマ（Ｍ）
# display as カズマ
# （ん？　待てよ？\n　これは絶好の機会じゃないか？）
547 = "（ん？　待てよ？\\n　これは絶好の機会じゃないか？）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスは俺に惚れてる。\n　だったら、ちょっとしたお願いぐらいなら\n　聞いてくれそうだし）
548 = "（ダクネスは俺に惚れてる。\\n　だったら、ちょっとしたお願いぐらいなら\\n　聞いてくれそうだし）"

# カズマ
# なぁ、ダクネス。\n着替えるの、手伝ってくれないか？
414 = "なぁ、ダクネス。\\n着替えるの、手伝ってくれないか？"

# ダクネス
# なっ、何ぃ！？\nわ、わ、私に、着替えを手伝えというのか！？
416 = "なっ、何ぃ！？\\nわ、わ、私に、着替えを手伝えというのか！？"

# カズマ（Ｍ）
# display as カズマ
# （あ、しまった。\n　これはちょっとハードルが高かったか？）
537 = "（あ、しまった。\\n　これはちょっとハードルが高かったか？）"

# カズマ
# あ、ああ、まだ寝ぼけてたみたいだ。\n変なこと口走って悪かったよ。
359 = "あ、ああ、まだ寝ぼけてたみたいだ。\\n変なこと口走って悪かったよ。"

# ダクネス
# か、カズマ！
379 = "か、カズマ！"

# カズマ
# はっ、はいっ！？
426 = "はっ、はいっ！？"

# ダクネス
# これは……必要なことなのか？
381 = "これは……必要なことなのか？"

# カズマ
# そ、それは――
390 = "そ、それは――"

# カズマ（Ｍ）
# display as カズマ
# （ここは引くな！\n　これぐらいのハードルを乗り越えてもらわないと、\n　夢のラブラブ生活はない！）
542 = "（ここは引くな！\\n　これぐらいのハードルを乗り越えてもらわないと、\\n　夢のラブラブ生活はない！）"

# カズマ
# 着替えを手伝うのは、もちろん基本だ！
527 = "着替えを手伝うのは、もちろん基本だ！"

# ダクネス
# そっ……そうなのか……。
396 = "そっ……そうなのか……。"

# ダクネス
# わかった。\nそういうことならやらせてもらう。
444 = "わかった。\\nそういうことならやらせてもらう。"

# カズマ（Ｍ）
# display as カズマ
# （よーし！\n　俺に惚れてるんだったら、\n　これぐらい普通にこなしてもらわないとな！）
546 = "（よーし！\\n　俺に惚れてるんだったら、\\n　これぐらい普通にこなしてもらわないとな！）"

# ダクネス
# それで、どうやればいいんだ？
399 = "それで、どうやればいいんだ？"

# カズマ
# まずズボンを脱がせます。
438 = "まずズボンを脱がせます。"

# ダクネス
# な！？
421 = "な！？"

# カズマ（Ｍ）
# display as カズマ
# （おっと、いきなりこれはハードルが高すぎるか）
541 = "（おっと、いきなりこれはハードルが高すぎるか）"

# カズマ
# じゃあ、ちょっとあっち向いててくれ、\nいい感じの所までは自分で着替えるからさ。
385 = "じゃあ、ちょっとあっち向いててくれ、\\nいい感じの所までは自分で着替えるからさ。"

# ダクネス
# わ、わかった……。
443 = "わ、わかった……。"

# カズマ
# お待たせ！
378 = "お待たせ！"

# ダクネス
# なんだ、着替えが終わってるじゃないか。
418 = "なんだ、着替えが終わってるじゃないか。"

# カズマ
# うん、冷静に考えたら、\nシャツとかズボンの着替えを手伝うのは、\n介護でしかなかった。
369 = "うん、冷静に考えたら、\\nシャツとかズボンの着替えを手伝うのは、\\n介護でしかなかった。"

# ダクネス
# では、手伝いは無しでいいのだな？
409 = "では、手伝いは無しでいいのだな？"

# カズマ
# 俺をよく見ろ。\nおかしいところがあるだろ？
464 = "俺をよく見ろ。\\nおかしいところがあるだろ？"

# ダクネス
# んん……わからないな。
446 = "んん……わからないな。"

# カズマ
# まあ、間違い探しのレベルだからな。
436 = "まあ、間違い探しのレベルだからな。"

# ダクネス
# それで、おかしいところとはどこなんだ？
398 = "それで、おかしいところとはどこなんだ？"

# カズマ
# マントが曲がってるだろ？
459 = "マントが曲がってるだろ？"

# ダクネス
# ああ、確かに。
362 = "ああ、確かに。"

# カズマ
# このマントの乱れを直していただきたい！
380 = "このマントの乱れを直していただきたい！"

# ダクネス
# ああ、それくらいならお安い御用だぞ。
360 = "ああ、それくらいならお安い御用だぞ。"

# カズマ
# ただし！\n普通に手伝うだけじゃ何もおもしろくない。
402 = "ただし！\\n普通に手伝うだけじゃ何もおもしろくない。"

# ダクネス
# 衣服の乱れを直すのに、\n面白味を求める意味がわからんが。
532 = "衣服の乱れを直すのに、\\n面白味を求める意味がわからんが。"

# カズマ
# そこで、ひとつシチュエーションを考えた。\nそれはずばり、新婚さん！
394 = "そこで、ひとつシチュエーションを考えた。\\nそれはずばり、新婚さん！"

# ダクネス
# し、新婚！？
384 = "し、新婚！？"

# カズマ
# 詳細はこうだ。
534 = "詳細はこうだ。"

# カズマ
# カズマ君は今日も、朝からお仕事です。
452 = "カズマ君は今日も、朝からお仕事です。"

# カズマ
# でも、あらあら？　慌てて着替えたのかな？\nマントが曲がっていますよ。
410 = "でも、あらあら？　慌てて着替えたのかな？\\nマントが曲がっていますよ。"

# カズマ
# ダクネスさんは妻としてそんなことを許せるわけが\nありません。
458 = "ダクネスさんは妻としてそんなことを許せるわけが\\nありません。"

# カズマ
# なぜなら夫の恥は、妻の恥でもあるからです。
415 = "なぜなら夫の恥は、妻の恥でもあるからです。"

# カズマ
# それじゃあダクネス、行ってくるよ。\nあっ、夕飯は家で食べるから。
397 = "それじゃあダクネス、行ってくるよ。\\nあっ、夕飯は家で食べるから。"

# ダクネス
# え、ああ、そうなの、か？
371 = "え、ああ、そうなの、か？"

# カズマ
# ちがーーーーーう！\nカズくん、美味しいご飯を用意して待ってるからね、\nちゅ！　だろうが！
404 = "ちがーーーーーう！\\nカズくん、美味しいご飯を用意して待ってるからね、\\nちゅ！　だろうが！"

# ダクネス
# ちゅ、ちゅうだと！？\nさすがにそれは……。
407 = "ちゅ、ちゅうだと！？\\nさすがにそれは……。"

# カズマ
# わかってる、今のは俺の調子に乗りすぎた妄想だ。
445 = "わかってる、今のは俺の調子に乗りすぎた妄想だ。"

# ダクネス
# では、どうしたらいいんだ？
408 = "では、どうしたらいいんだ？"

# カズマ
# あれ、カズ君、マントが曲がってるよ。\n直してあげるね。
363 = "あれ、カズ君、マントが曲がってるよ。\\n直してあげるね。"

# カズマ
# はい、これ最適解！
424 = "はい、これ最適解！"

# ダクネス
# な、なるほど。
412 = "な、なるほど。"

# カズマ
# じゃあ、もう一度最初から。\nんんっ！　ダクネス、行ってくるぞ。
386 = "じゃあ、もう一度最初から。\\nんんっ！　ダクネス、行ってくるぞ。"

# ダクネス
# え、ええと、カズマ、マントが曲がっているぞ。\nどれ、直してやろう。
372 = "え、ええと、カズマ、マントが曲がっているぞ。\\nどれ、直してやろう。"

# カズマ（Ｍ）
# display as カズマ
# （お、おお、これは、いいものだ！）
540 = "（お、おお、これは、いいものだ！）"

# ダクネス
# うう、マントを直しているだけだというのに\nこの気恥ずかしさはなんなんだ。
367 = "うう、マントを直しているだけだというのに\\nこの気恥ずかしさはなんなんだ。"

# カズマ
# うーん、悪くない、悪くないのだが。
370 = "うーん、悪くない、悪くないのだが。"

# ダクネス
# 何かあるのか？
461 = "何かあるのか？"

# カズマ
# なんか、よそよそしいんだよなぁ。
417 = "なんか、よそよそしいんだよなぁ。"

# ダクネス
# それはそうだろう。\n親密な仲ではないのだから。
400 = "それはそうだろう。\\n親密な仲ではないのだから。"

# カズマ
# はい、その考え方がダメー！
425 = "はい、その考え方がダメー！"

# カズマ
# 俺たちは今夫婦なの、しかも新婚さん！\nまずは役に入りきれよ！
462 = "俺たちは今夫婦なの、しかも新婚さん！\\nまずは役に入りきれよ！"

# ダクネス
# 言うのは簡単だが、\nいざやるとなると結構難しいのだぞ？
533 = "言うのは簡単だが、\\nいざやるとなると結構難しいのだぞ？"

# カズマ
# そこをやりきってこそのクルセイダーだろ！
395 = "そこをやりきってこそのクルセイダーだろ！"

# ダクネス
# そ、そうなのか！？
389 = "そ、そうなのか！？"

# カズマ
# 敵からの攻撃だけに限らず、全てを受けとめる！\nそれがクルセイダーってもんだろうがっ！
469 = "敵からの攻撃だけに限らず、全てを受けとめる！\\nそれがクルセイダーってもんだろうがっ！"

# ダクネス
# 確かに！
528 = "確かに！"

# カズマ（Ｍ）
# display as カズマ
# （納得した！）
551 = "（納得した！）"

# ダクネス
# 私たちは夫婦、そして新婚……。
529 = "私たちは夫婦、そして新婚……。"

# ダクネス
# まったく、だらしがないな。\n朝起きるのが遅いからこうなるんだ。
439 = "まったく、だらしがないな。\\n朝起きるのが遅いからこうなるんだ。"

# カズマ
# ふふ、何を言ってるんだい？\n昨夜眠らせてくれなかったのはお前じゃないか。
429 = "ふふ、何を言ってるんだい？\\n昨夜眠らせてくれなかったのはお前じゃないか。"

# ダクネス
# ……どういう意味だ？
357 = "……どういう意味だ？"

# カズマ
# いや、だからな。
365 = "いや、だからな。"

# ダクネス
# んん？
447 = "んん？"

# カズマ
# いやほら、新婚の夫婦っていったら\nいろいろあるだろ。
366 = "いやほら、新婚の夫婦っていったら\\nいろいろあるだろ。"

# ダクネス
# 新婚夫婦の……色々？
470 = "新婚夫婦の……色々？"

# ダクネス
# な、何を馬鹿なことを！！
413 = "な、何を馬鹿なことを！！"

# ダクネス
# 私はエリス様に使える身！\nそんな汚らわしいことをするなんて！
531 = "私はエリス様に使える身！\\nそんな汚らわしいことをするなんて！"

# カズマ
# 汚らわしいことって、何？\nぼくは夜遅くまで楽しくお喋りしてたって\n考えてただけだよ？
472 = "汚らわしいことって、何？\\nぼくは夜遅くまで楽しくお喋りしてたって\\n考えてただけだよ？"

# ダクネス
# にゃっ！？
422 = "にゃっ！？"

# カズマ
# ふふ、照れたダクネスも可愛いぞ。
430 = "ふふ、照れたダクネスも可愛いぞ。"

# ダクネス
# そ、そういう意地悪はやめてくれ。
387 = "そ、そういう意地悪はやめてくれ。"

# めぐみん
# カズマ？\nまだ寝てるんですか？
454 = "カズマ？\\nまだ寝てるんですか？"

# アクア
# 遅いわよ。\n朝食が冷めちゃうじゃ――って、何やってるの？
535 = "遅いわよ。\\n朝食が冷めちゃうじゃ――って、何やってるの？"

# カズマ
# ははは、着替えを手伝ってもらってたんだ。
427 = "ははは、着替えを手伝ってもらってたんだ。"

# めぐみん
# なんです？\nとうとう自分で服を脱げなくなるまで\n衰えたんですか。
420 = "なんです？\\nとうとう自分で服を脱げなくなるまで\\n衰えたんですか。"

# アクア
# そういえば最近、物忘れが激しいわよね。
393 = "そういえば最近、物忘れが激しいわよね。"

# カズマ
# 俺はおじいちゃんか！\nただ、着替えを通してダクネスの愛情を\n確認していただけだ！
463 = "俺はおじいちゃんか！\\nただ、着替えを通してダクネスの愛情を\\n確認していただけだ！"

# ダクネス
# 私の愛情！？
530 = "私の愛情！？"

# めぐみん
# そういう大義名分で、\nダクネスを辱めて楽しんでいると。
392 = "そういう大義名分で、\\nダクネスを辱めて楽しんでいると。"

# カズマ
# ちがーーーーーう！！
405 = "ちがーーーーーう！！"

# カズマ
# これは同意の上での行為なんだ！
383 = "これは同意の上での行為なんだ！"

# アクア
# へえ……。\nまるでご奉仕させているような\nこの状況が合意の上なの？
432 = "へえ……。\\nまるでご奉仕させているような\\nこの状況が合意の上なの？"

# めぐみん
# ダクネス、またカズマに騙されましたね。
456 = "ダクネス、またカズマに騙されましたね。"

# ダクネス
# えっ？
373 = "えっ？"

# カズマ
# 騙してない！\nダクネスは俺のお願いを聞いてくれただけだ！
536 = "騙してない！\\nダクネスは俺のお願いを聞いてくれただけだ！"

# ダクネス
# そ、そうだぞ？\n無理矢理させられているわけではない。
388 = "そ、そうだぞ？\\n無理矢理させられているわけではない。"

# カズマ
# ほらな？\nわかったか、アクア！
435 = "ほらな？\\nわかったか、アクア！"

# カズマ
# もういい！\nダクネス、気にせず続けてくれ。
441 = "もういい！\\nダクネス、気にせず続けてくれ。"

# ダクネス
# だが、もうマントは直し終わっているぞ。\nそれに……２人の前ではさすがに恥ずかしい。
403 = "だが、もうマントは直し終わっているぞ。\\nそれに……２人の前ではさすがに恥ずかしい。"

# カズマ
# おお、いいね！\nその照れ顔、大好物です！
374 = "おお、いいね！\\nその照れ顔、大好物です！"

# ダクネス
# よ、よくわからんが、カズマが喜んでくれたのなら、\nよかった。
442 = "よ、よくわからんが、カズマが喜んでくれたのなら、\\nよかった。"

# カズマ
# ほらっ、ほらね！\nダクネス嫌がってないじゃん！
434 = "ほらっ、ほらね！\\nダクネス嫌がってないじゃん！"

# めぐみん
# ぬう、確かに。
423 = "ぬう、確かに。"

# カズマ
# お前らも手伝いたいのか？
377 = "お前らも手伝いたいのか？"

# アクア
# は？　何言ってるのよ？
428 = "は？　何言ってるのよ？"

# めぐみん
# いったいどんなウィルスに\n頭をやられてしまったんでしょうか。
364 = "いったいどんなウィルスに\\n頭をやられてしまったんでしょうか。"

# カズマ
# うん、そろそろ本気で怒るよ？
368 = "うん、そろそろ本気で怒るよ？"

# アクア
# とにかく、その辺で止めときなさいよね。\n冗談ですむのは今のうちよ？
411 = "とにかく、その辺で止めときなさいよね。\\n冗談ですむのは今のうちよ？"

# ダクネス
# アクア、めぐみん。\nいいんだ。
450 = "アクア、めぐみん。\\nいいんだ。"

# めぐみん
# えっ？
# 373 = "えっ？"

# アクア
# まさか……\nダクネス、カズマに洗脳されちゃったの？
437 = "まさか……\\nダクネス、カズマに洗脳されちゃったの？"

# ダクネス
# そんなことはない。\nこれは、私がやりたくてやっていることだ。
401 = "そんなことはない。\\nこれは、私がやりたくてやっていることだ。"

# カズマ
# そういうことだよ。\nお前らが心配する必要なんてないんだ。
391 = "そういうことだよ。\\nお前らが心配する必要なんてないんだ。"

# アクア
# 本当かしら？
471 = "本当かしら？"

# めぐみん
# なんだか、腑に落ちませんよね。
419 = "なんだか、腑に落ちませんよね。"

# ダクネス
# …………。
356 = "…………。"

[selections]
382 = "これは同意の上での行為だ！"
457 = "ダクネス、気にせず続けてくれ"
# 377 = "お前らも手伝いたいのか？"
