# root_d08.txt.scn

[info]
0 = ""

[characters]
355 = "ウィズ"
359 = "カズマ"
365 = "クリス"
361 = "カズマ（Ｍ）"
363 = "キース"

[character_subs]
# 359 = "カズマ"

[script]
# lines: 83

# ウィズ
# あら、こんにちはカズマさん。\n今日は何かお探しですか？
305 = "あら、こんにちはカズマさん。\\n今日は何かお探しですか？"

# カズマ
# ウィズ！\nクリスを見かけなかったか？
358 = "ウィズ！\\nクリスを見かけなかったか？"

# ウィズ
# え？\nクリスさんでしたら──
315 = "え？\\nクリスさんでしたら──"

# クリス
# やあ、慌ててどうしたの？
353 = "やあ、慌ててどうしたの？"

# カズマ
# 見つけた！！
418 = "見つけた！！"

# クリス
# えっ？
312 = "えっ？"

# カズマ
# クリス、ここに来るまで誰かに見られたか？\nここで俺以外の誰かと会ったか？
366 = "クリス、ここに来るまで誰かに見られたか？\\nここで俺以外の誰かと会ったか？"

# クリス
# ど、どうしたのさ、意味がわからないんだけど。
340 = "ど、どうしたのさ、意味がわからないんだけど。"

# カズマ
# いいから答えてくれ、クリス。\n頼むから。
307 = "いいから答えてくれ、クリス。\\n頼むから。"

# クリス
# ええと、あんまり覚えてないけど、どうだったかな。\nこのお店では誰とも会ってないけど。
310 = "ええと、あんまり覚えてないけど、どうだったかな。\\nこのお店では誰とも会ってないけど。"

# カズマ
# そうか！\nなあウィズ、頼みがある。\nしばらくクリスを匿ってやってくれないか。
323 = "そうか！\\nなあウィズ、頼みがある。\\nしばらくクリスを匿ってやってくれないか。"

# ウィズ
# えっ？\nクリスさんをですか？
313 = "えっ？\\nクリスさんをですか？"

# クリス
# 匿うって、どういうこと？
376 = "匿うって、どういうこと？"

# カズマ
# 話すと長くなるんだが──\n簡単に説明するとだな、\nクリス、お前に賞金がかけられた。
419 = "話すと長くなるんだが──\\n簡単に説明するとだな、\\nクリス、お前に賞金がかけられた。"

# クリス
# はあっ！？
344 = "はあっ！？"

# カズマ
# 誰かが俺の名前でクエストを出したんだ。\nクリスを捕まえたやつに\n報酬金１００万エリスが支払われるって。
420 = "誰かが俺の名前でクエストを出したんだ。\\nクリスを捕まえたやつに\\n報酬金１００万エリスが支払われるって。"

# カズマ
# それで今、街中の冒険者達が\n血眼になってお前を探してる。
328 = "それで今、街中の冒険者達が\\n血眼になってお前を探してる。"

# カズマ
# ただ、このクエストには時間制限があって\n６時間後がタイムリミットなんだ。\nだから今日さえ乗り切れば、なんとかなる！
336 = "ただ、このクエストには時間制限があって\\n６時間後がタイムリミットなんだ。\\nだから今日さえ乗り切れば、なんとかなる！"

# ウィズ
# そ、そ、それは大変ですね。\n１００万エリスですか。
321 = "そ、そ、それは大変ですね。\\n１００万エリスですか。"

# クリス
# カズマ……。\nキミ、なんてことしてくれたの。\nはっきり言って、こういうのは困るんだけど。
360 = "カズマ……。\\nキミ、なんてことしてくれたの。\\nはっきり言って、こういうのは困るんだけど。"

# カズマ
# 俺だって困ってるんだよ！\n１００万エリスなんて持ってないっつーの！
375 = "俺だって困ってるんだよ！\\n１００万エリスなんて持ってないっつーの！"

# ウィズ
# あ、あの、クリスさん、カズマさん？\nその、もし宜しければお茶でもいかがですか？\nなんとなく、お茶を淹れてみたんですけど。
296 = "あ、あの、クリスさん、カズマさん？\\nその、もし宜しければお茶でもいかがですか？\\nなんとなく、お茶を淹れてみたんですけど。"

# カズマ
# …………。
295 = "…………。"

# クリス
# …………。
# 295 = "…………。"

# ウィズ
# ど、どどど、どうしたんですか、お２人とも。\nそんな不審な者を見るかのような眼差しで。
341 = "ど、どどど、どうしたんですか、お２人とも。\\nそんな不審な者を見るかのような眼差しで。"

# カズマ
# ウィズ。\nそのお茶、自分で飲んでみろ。
356 = "ウィズ。\\nそのお茶、自分で飲んでみろ。"

# ウィズ
# えっ、そ、それは、その。
311 = "えっ、そ、それは、その。"

# クリス
# ウィズさん？
357 = "ウィズさん？"

# ウィズ
# ご、ごめんなさいっ！！！\nつい出来心でお薬を盛っちゃいました！\n許してくださいっ！
319 = "ご、ごめんなさいっ！！！\\nつい出来心でお薬を盛っちゃいました！\\n許してくださいっ！"

# カズマ（Ｍ）
# display as カズマ
# （そんなことだと思ったぜ）
421 = "（そんなことだと思ったぜ）"

# クリス
# それで？\nどうしてこんな騒ぎになったのか\n説明してくれるかな。
329 = "それで？\\nどうしてこんな騒ぎになったのか\\n説明してくれるかな。"

# カズマ
# それは俺が聞きたいよ。\n気がついたらクエストが発注されててさ。
332 = "それは俺が聞きたいよ。\\n気がついたらクエストが発注されててさ。"

# クリス
# クエストの内容は、あたしを捕まえる。\nそれで間違いないんだね？
364 = "クエストの内容は、あたしを捕まえる。\\nそれで間違いないんだね？"

# カズマ
# ああ、間違いない。
302 = "ああ、間違いない。"

# クリス
# これって、\n昨日キミがあたしのあとをつけていたことと\n関係あるのかな？
317 = "これって、\\n昨日キミがあたしのあとをつけていたことと\\n関係あるのかな？"

# カズマ
# え、知ってたのか！？
309 = "え、知ってたのか！？"

# クリス
# 尾行下手すぎ。\nバレたくないなら、潜伏スキルくらいは使わないと。
380 = "尾行下手すぎ。\\nバレたくないなら、潜伏スキルくらいは使わないと。"

# カズマ
# いや、そこまですると犯罪臭がするかなって。
308 = "いや、そこまですると犯罪臭がするかなって。"

# クリス
# へえ、驚いた。\nカズマにもそういう良識があったんだね。
349 = "へえ、驚いた。\\nカズマにもそういう良識があったんだね。"

# カズマ
# むしろ俺は良識の固まりだと思うんですけど！
352 = "むしろ俺は良識の固まりだと思うんですけど！"

# クリス
# え？
314 = "え？"

# ウィズ
# え？
# 314 = "え？"

# カズマ
# やめて、アクアたちならまだしも、\n本当の良識人のふたりから突っ込まれると\n心の底から傷つくから。
354 = "やめて、アクアたちならまだしも、\\n本当の良識人のふたりから突っ込まれると\\n心の底から傷つくから。"

# クリス
# ねえ、あたしを捕まえて\nどうするつもりだったのさ。
343 = "ねえ、あたしを捕まえて\\nどうするつもりだったのさ。"

# カズマ
# ほら、指輪の件で色々世話になったから\nお詫びをしたいって言っただろ？
350 = "ほら、指輪の件で色々世話になったから\\nお詫びをしたいって言っただろ？"

# カズマ
# でもクリスは特にいらないって言うからさ、\nこっちで欲しい物とか、やって欲しいことを調べて\n借りを返そうと思ったんだよ。
339 = "でもクリスは特にいらないって言うからさ、\\nこっちで欲しい物とか、やって欲しいことを調べて\\n借りを返そうと思ったんだよ。"

# クリス
# それを誰かに見られたりした？
334 = "それを誰かに見られたりした？"

# カズマ
# ああ、何人かに。
299 = "ああ、何人かに。"

# クリス
# なるほど、それを知った誰かによって\nクエストが発注されて\n今に至る、ってわけか。
342 = "なるほど、それを知った誰かによって\\nクエストが発注されて\\n今に至る、ってわけか。"

# カズマ
# はあ？　どうしてそんなことを！
345 = "はあ？　どうしてそんなことを！"

# クリス
# それは知らないよ。
333 = "それは知らないよ。"

# クリス
# ただの善意からくるものなのか、\nそれとも悪意なのか、\nカズマなら後者の確率が高いとは思うけどさ。
337 = "ただの善意からくるものなのか、\\nそれとも悪意なのか、\\nカズマなら後者の確率が高いとは思うけどさ。"

# カズマ
# だから傷つくからやめてくれ。
338 = "だから傷つくからやめてくれ。"

# クリス
# それで、これからどうするの？
327 = "それで、これからどうするの？"

# カズマ
# クリスを全力で守る！
368 = "クリスを全力で守る！"

# クリス
# 守るって、キミがあたしを？
379 = "守るって、キミがあたしを？"

# カズマ
# ああ、当然だろ。\n俺がクリスを追いかけてたせいで\nこんなことになっちまったんだし。
300 = "ああ、当然だろ。\\n俺がクリスを追いかけてたせいで\\nこんなことになっちまったんだし。"

# クリス
# へえ、意外。\nキミって結構、責任感あったんだね。
348 = "へえ、意外。\\nキミって結構、責任感あったんだね。"

# カズマ
# そりゃまあ、元をただせば俺が原因だからな。\n勝手にクエスト発注した奴は\n見つけ次第、責任取らせてやるけど。
324 = "そりゃまあ、元をただせば俺が原因だからな。\\n勝手にクエスト発注した奴は\\n見つけ次第、責任取らせてやるけど。"

# クリス
# ふふっ。\nそれじゃ、期待しちゃおうかな。
346 = "ふふっ。\\nそれじゃ、期待しちゃおうかな。"

# カズマ
# 今すぐ街から逃げてくれ！\n街の外なら、そう簡単には見つからないはずだ！
373 = "今すぐ街から逃げてくれ！\\n街の外なら、そう簡単には見つからないはずだ！"

# クリス
# それって、\nあたしだけ逃げろってこと？
326 = "それって、\\nあたしだけ逃げろってこと？"

# カズマ
# ああ、適当に身を隠すのは得意だろ？\nなんてったって盗賊だし。
301 = "ああ、適当に身を隠すのは得意だろ？\\nなんてったって盗賊だし。"

# クリス
# そりゃまあ、得意だけど、さすがに\n何も準備していない状態で外には行けないよ。
325 = "そりゃまあ、得意だけど、さすがに\\n何も準備していない状態で外には行けないよ。"

# クリス
# 今の装備じゃ、行けて\nせいぜい街が見える平原くらいかな。
374 = "今の装備じゃ、行けて\\nせいぜい街が見える平原くらいかな。"

# クリス
# それ以上はモンスターに遭遇する\n可能性があるから無理。
335 = "それ以上はモンスターに遭遇する\\n可能性があるから無理。"

# カズマ
# それはこれから考える！\nとにかく、逃げることを第一に考えよう。
331 = "それはこれから考える！\\nとにかく、逃げることを第一に考えよう。"

# クリス
# ダクネスやアクアさんたちに事情を話して\n匿ってもらうことはできない？
370 = "ダクネスやアクアさんたちに事情を話して\\n匿ってもらうことはできない？"

# カズマ
# クリス、冷静になって考えろ？\nあいつらが金に目をくらませないと\n信じられるか？
367 = "クリス、冷静になって考えろ？\\nあいつらが金に目をくらませないと\\n信じられるか？"

# クリス
# あー……。
306 = "あー……。"

# カズマ
# この、お人よしの代名詞のようなウィズだって\n１００万エリスに目がくらんで\n俺達に薬を盛ろうとしてきたんだぞ。
316 = "この、お人よしの代名詞のようなウィズだって\\n１００万エリスに目がくらんで\\n俺達に薬を盛ろうとしてきたんだぞ。"

# ウィズ
# ご、ごめんなさい、ごめんなさい！\nつい魔が差したんです！\n許してください……うっ、うう……。
318 = "ご、ごめんなさい、ごめんなさい！\\nつい魔が差したんです！\\n許してください……うっ、うう……。"

# クリス
# まあ、それはともかく、\nそう考えると、今信頼できる人は\nこの街にいないってことか。
351 = "まあ、それはともかく、\\nそう考えると、今信頼できる人は\\nこの街にいないってことか。"

# カズマ
# そう、お互い以外はな。
322 = "そう、お互い以外はな。"

# クリス
# キミはあたしのこと、\n信頼できるって思ってるんだ。
362 = "キミはあたしのこと、\\n信頼できるって思ってるんだ。"

# カズマ
# 当たり前だろ？
383 = "当たり前だろ？"

# クリス
# ふーん、そっか。\nふふっ。
347 = "ふーん、そっか。\\nふふっ。"

# ウィズ
# あ、いらっしゃいませ。
297 = "あ、いらっしゃいませ。"

# キース
# あっ！　いたっ！！
303 = "あっ！　いたっ！！"

# カズマ
# しまった、見つかったか！\n逃げるぞクリス！
320 = "しまった、見つかったか！\\n逃げるぞクリス！"

# ウィズ
# あ、カズマさん、裏口からどうぞ！
298 = "あ、カズマさん、裏口からどうぞ！"

# カズマ
# サンキュー、ウィズ！
369 = "サンキュー、ウィズ！"

# クリス
# あはは、なんか盛り上がってきたね。
304 = "あはは、なんか盛り上がってきたね。"

[selections]
# 368 = "クリスを全力で守る！"
372 = "今すぐ街から逃げてくれ！"
330 = "それはこれから考える！"
