# root_a10.txt.scn

[info]
0 = ""

[characters]
378 = "カズマ"
375 = "アクア"
387 = "ダクネス"
371 = "めぐみん"
385 = "カズマ（Ｍ）"
373 = "めぐみん＆ダクネス"

[character_subs]
# 378 = "カズマ"
465 = "２人"

[script]
# lines: 118

# カズマ
# ふあ～……おはよう……。
366 = "ふあ～……おはよう……。"

# アクア
# カズマぁぁぁ！！　カズマさああああん！！
383 = "カズマぁぁぁ！！　カズマさああああん！！"

# カズマ
# うわー、関わりたくねー。
309 = "うわー、関わりたくねー。"

# アクア
# カズマ、大変なの、大変なのよ！
380 = "カズマ、大変なの、大変なのよ！"

# カズマ
# 何がだよ。
391 = "何がだよ。"

# アクア
# それがね、うう、私にもわからないの。
346 = "それがね、うう、私にもわからないの。"

# カズマ
# そっか、じゃあどうすることもできないな。\nよし、飯だ飯。\n今日の朝食は何かなー。
344 = "そっか、じゃあどうすることもできないな。\\nよし、飯だ飯。\\n今日の朝食は何かなー。"

# アクア
# うわあああ、お願いだから見捨てないで、\nカズマさあああああん！！
306 = "うわあああ、お願いだから見捨てないで、\\nカズマさあああああん！！"

# ダクネス
# おいおい、朝からなんの騒ぎだ。
323 = "おいおい、朝からなんの騒ぎだ。"

# めぐみん
# なんです。\nまたアクアを泣かせたんですか？
360 = "なんです。\\nまたアクアを泣かせたんですか？"

# カズマ
# 違うわ！\n起きてきたらいきなり泣きつかれたんだよ。
453 = "違うわ！\\n起きてきたらいきなり泣きつかれたんだよ。"

# めぐみん
# もしかして、昨夜何かあったんです？
374 = "もしかして、昨夜何かあったんです？"

# カズマ
# いや、それは俺にもわからん。
298 = "いや、それは俺にもわからん。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、関係してないとは思えないけど）
460 = "（まあ、関係してないとは思えないけど）"

# ダクネス
# それでいったい何があったんだ。\nアクア、泣いていないで説明を――
348 = "それでいったい何があったんだ。\\nアクア、泣いていないで説明を――"

# カズマ
# しなくていい。\n面倒事に巻き込まれるなんて\nまっぴらごめんだ。
340 = "しなくていい。\\n面倒事に巻き込まれるなんて\\nまっぴらごめんだ。"

# アクア
# ひどい！\nカズマが変態行為を繰り返してたとき、\nあんなに力を貸してあげたのに！
365 = "ひどい！\\nカズマが変態行為を繰り返してたとき、\\nあんなに力を貸してあげたのに！"

# カズマ
# うっ、それを言われると……。
304 = "うっ、それを言われると……。"

# めぐみん
# カズマ。\n話くらい聞いてもいいのでは？
382 = "カズマ。\\n話くらい聞いてもいいのでは？"

# ダクネス
# うむ。恩があるのは事実だろう？
305 = "うむ。恩があるのは事実だろう？"

# カズマ
# はあ……わかった、わかったよ。
362 = "はあ……わかった、わかったよ。"

# カズマ
# それで、アクア。\nいったい何があったんだ、話してみろ。
347 = "それで、アクア。\\nいったい何があったんだ、話してみろ。"

# アクア
# え、ええと、それが……。
311 = "え、ええと、それが……。"

# カズマ（Ｍ）
# display as カズマ
# （泣きついておいてこの歯切れの悪さ。\n　もう悪い予感しかしねー）
462 = "（泣きついておいてこの歯切れの悪さ。\\n　もう悪い予感しかしねー）"

# アクア
# 最近、私が夜に出掛けてたの、知ってるでしょ？
402 = "最近、私が夜に出掛けてたの、知ってるでしょ？"

# ダクネス
# それはまあな。
352 = "それはまあな。"

# アクア
# 実は……とある集会に行ってたの。
398 = "実は……とある集会に行ってたの。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、昨夜の例のあれか）
455 = "（ああ、昨夜の例のあれか）"

# アクア
# その集会で、私、だまされてひどい目にあったのよ！
345 = "その集会で、私、だまされてひどい目にあったのよ！"

# ダクネス
# ひ、ひどい目にあわせられるプレイだと！？
364 = "ひ、ひどい目にあわせられるプレイだと！？"

# カズマ
# いや、プレイなんて一言も言ってないからな？
299 = "いや、プレイなんて一言も言ってないからな？"

# めぐみん
# それで？　そのプレイがどうかしたんですか？
350 = "それで？　そのプレイがどうかしたんですか？"

# カズマ
# いや、お前も乗っかるなよ。
297 = "いや、お前も乗っかるなよ。"

# アクア
# ええとね、スカルドラゴンとの戦いのあと\n私、ちょっと落ち込んでたじゃない？
314 = "ええとね、スカルドラゴンとの戦いのあと\\n私、ちょっと落ち込んでたじゃない？"

# カズマ
# ああ、ウィズに美味しいところを\n持って行かれたからだろ。
293 = "ああ、ウィズに美味しいところを\\n持って行かれたからだろ。"

# アクア
# 今でも納得いかないのよ。\nスカルドラゴンをギリギリまで弱めたのは私なのに、\nリッチーが全部持ってっちゃうんだもの。
390 = "今でも納得いかないのよ。\\nスカルドラゴンをギリギリまで弱めたのは私なのに、\\nリッチーが全部持ってっちゃうんだもの。"

# めぐみん
# 気持ちはわからなくもありませんよ。\n私たち、その他大勢の扱いでしたからね。
403 = "気持ちはわからなくもありませんよ。\\n私たち、その他大勢の扱いでしたからね。"

# カズマ
# お前たちの愚痴はもう聞き飽きた。\nそれよりも続きを話せ。
325 = "お前たちの愚痴はもう聞き飽きた。\\nそれよりも続きを話せ。"

# アクア
# ええとね。\n私が戦う姿を見て、活躍を認めてくれてた人が\nいたのよ。
315 = "ええとね。\\n私が戦う姿を見て、活躍を認めてくれてた人が\\nいたのよ。"

# カズマ
# ほお、お前の活躍を。
368 = "ほお、お前の活躍を。"

# アクア
# うん。\n私の魔力には神々しい何かを感じたって。
310 = "うん。\\n私の魔力には神々しい何かを感じたって。"

# カズマ（Ｍ）
# display as カズマ
# （神々しい何かって……。\n　なんかうさんくせえ）
463 = "（神々しい何かって……。\\n　なんかうさんくせえ）"

# アクア
# 浄化魔法を撃つあの崇高な立ち姿。\nそして何よりも、この世の者とは思えない\nその美貌！
404 = "浄化魔法を撃つあの崇高な立ち姿。\\nそして何よりも、この世の者とは思えない\\nその美貌！"

# アクア
# きっとあなたは、\n女神アクアの生まれ変わりに違いないって！
326 = "きっとあなたは、\\n女神アクアの生まれ変わりに違いないって！"

# ダクネス
# それでよくわからない集会に\nついて行ったというわけだな？
349 = "それでよくわからない集会に\\nついて行ったというわけだな？"

# アクア
# だ、だって、嬉しかったし、\nそれにいろいろ貢ぎ物をくれたから。
353 = "だ、だって、嬉しかったし、\\nそれにいろいろ貢ぎ物をくれたから。"

# めぐみん
# くれたというのは、部屋にある物ですね？
327 = "くれたというのは、部屋にある物ですね？"

# アクア
# う、うん。
300 = "う、うん。"

# ダクネス
# ここまで聞くと、実力を認めて貰い、\nそして崇められ、さらには物までくれる。
329 = "ここまで聞くと、実力を認めて貰い、\\nそして崇められ、さらには物までくれる。"

# ダクネス
# まあ、訝しくはあるが、\n悪者とまでは言い切れないな。
369 = "まあ、訝しくはあるが、\\n悪者とまでは言い切れないな。"

# カズマ
# まったく、これだから世間知らずのお嬢様は。
370 = "まったく、これだから世間知らずのお嬢様は。"

# ダクネス
# なっ！
359 = "なっ！"

# カズマ
# いいか、アクア。\nまずお前は心の隙間に付け込まれたんだ！
295 = "いいか、アクア。\\nまずお前は心の隙間に付け込まれたんだ！"

# アクア
# え？　どういうこと？
317 = "え？　どういうこと？"

# カズマ
# へこんでるやつに優しい言葉で近づくなんて、\n詐欺の常套手段だろうが。
367 = "へこんでるやつに優しい言葉で近づくなんて、\\n詐欺の常套手段だろうが。"

# アクア
# ええ！？
316 = "ええ！？"

# カズマ
# どうせお前のことだ。\nなんでへこんでるのか馬鹿正直に説明したんだろ。
356 = "どうせお前のことだ。\\nなんでへこんでるのか馬鹿正直に説明したんだろ。"

# アクア
# し、したかも……。
338 = "し、したかも……。"

# カズマ
# バカだろお前！　てか、バカなんだよなお前！\n情報をそんなほいほい与えるとか、\nセキュリティが甘すぎるわ！　バカ！
388 = "バカだろお前！　てか、バカなんだよなお前！\\n情報をそんなほいほい与えるとか、\\nセキュリティが甘すぎるわ！　バカ！"

# アクア
# うぅ、バカって三回も言った……。
302 = "うぅ、バカって三回も言った……。"

# めぐみん
# カズマ。\n事実を突き付けるなら\nもう少し言葉を選ぶべきですよ。
381 = "カズマ。\\n事実を突き付けるなら\\nもう少し言葉を選ぶべきですよ。"

# アクア
# めぐみんまでひどい！
372 = "めぐみんまでひどい！"

# カズマ
# はあ……それでいくらなんだ？
361 = "はあ……それでいくらなんだ？"

# ダクネス
# いくらというと？
296 = "いくらというと？"

# カズマ
# アクアの部屋にある物は、決して貢ぎ物じゃない。
377 = "アクアの部屋にある物は、決して貢ぎ物じゃない。"

# めぐみん
# じゃあ、なんだというのです。
342 = "じゃあ、なんだというのです。"

# カズマ
# 商品だよ、商品。\nどうせ昨日の帰りに明細書かなんかを\n押しつけられたんだろ。
397 = "商品だよ、商品。\\nどうせ昨日の帰りに明細書かなんかを\\n押しつけられたんだろ。"

# ダクネス
# そ、そうなのか？
343 = "そ、そうなのか？"

# アクア
# しめて３００万エリスほどでございます……。
341 = "しめて３００万エリスほどでございます……。"

# めぐみん＆ダクネス
# display as ２人
# ３００万！？
466 = "３００万！？"

# カズマ
# この駄女神！\n普通に考えりゃわかるだろ！　わかるよな！
333 = "この駄女神！\\n普通に考えりゃわかるだろ！　わかるよな！"

# カズマ
# あんな街外れで真夜中にやってる集会なんて、\n怪しさ大爆発だろうが！
294 = "あんな街外れで真夜中にやってる集会なんて、\\n怪しさ大爆発だろうが！"

# アクア
# うわあああ、反省してるから助けてよ、カズマさん！\n昨夜からずっと外におっかない男がいるの！
307 = "うわあああ、反省してるから助けてよ、カズマさん！\\n昨夜からずっと外におっかない男がいるの！"

# カズマ
# 自業自得だ。
450 = "自業自得だ。"

# アクア
# うわあああああん、カズマに見捨てられたあああ！
308 = "うわあああああん、カズマに見捨てられたあああ！"

# めぐみん
# カズマ、ここは助けてあげるべきでは？
379 = "カズマ、ここは助けてあげるべきでは？"

# ダクネス
# カズマだって困っているときに助けられただろう。
384 = "カズマだって困っているときに助けられただろう。"

# カズマ（Ｍ）
# display as カズマ
# （それはそうだけど……）
457 = "（それはそうだけど……）"

# アクア
# このままだと馬小屋生活に\n逆戻りになっちゃうーーーー！！
331 = "このままだと馬小屋生活に\\n逆戻りになっちゃうーーーー！！"

# カズマ
# おい、こいつ今、聞き捨てならないことを言ったぞ。
320 = "おい、こいつ今、聞き捨てならないことを言ったぞ。"

# めぐみん
# ええ、聞きました、聞きましたとも。
312 = "ええ、聞きました、聞きましたとも。"

# ダクネス
# 馬小屋生活に戻ると言ったな。
454 = "馬小屋生活に戻ると言ったな。"

# カズマ
# おい、駄女神。\nいったいお前、何をやらかした。
322 = "おい、駄女神。\\nいったいお前、何をやらかした。"

# アクア
# このままだと、この屋敷や\nみんなの武器とか防具とか……\n全部、差し押さえられちゃうの。
330 = "このままだと、この屋敷や\\nみんなの武器とか防具とか……\\n全部、差し押さえられちゃうの。"

# カズマ
# ……はあ？
291 = "……はあ？"

# アクア
# ぐす、昨夜、タダでは帰せないって脅されちゃって。\nそれで、うう、この屋敷を担保するっていう\n念書に……。
328 = "ぐす、昨夜、タダでは帰せないって脅されちゃって。\\nそれで、うう、この屋敷を担保するっていう\\n念書に……。"

# ダクネス
# サインを……したと。
386 = "サインを……したと。"

# めぐみん
# な、なんということを……。
357 = "な、なんということを……。"

# アクア
# ごめん……なさい。
336 = "ごめん……なさい。"

# カズマ
# 謝ってすむ問題じゃねえええええええ！！
452 = "謝ってすむ問題じゃねえええええええ！！"

# カズマ（Ｍ）
# display as カズマ
# （まずい、まずいぞ！\n　これはどう考えても\n　最上級の災厄レベルの事件だ！）
461 = "（まずい、まずいぞ！\\n　これはどう考えても\\n　最上級の災厄レベルの事件だ！）"

# カズマ
# な、なんとかならないのか？\n裁判所に持ち込んでみるとかさ！
358 = "な、なんとかならないのか？\\n裁判所に持ち込んでみるとかさ！"

# ダクネス
# アクア。\nその念書や借金の証書はあるか？
376 = "アクア。\\nその念書や借金の証書はあるか？"

# アクア
# これです。
334 = "これです。"

# ダクネス
# これはダメだな。\n正規の書類、しかも自筆サイン付きとなれば\nどうしようもない。
335 = "これはダメだな。\\n正規の書類、しかも自筆サイン付きとなれば\\nどうしようもない。"

# ダクネス
# さらにこれは……。
337 = "さらにこれは……。"

# カズマ
# おい、今度は何が飛び出すんだ。
321 = "おい、今度は何が飛び出すんだ。"

# ダクネス
# 十日で一割の利子が付くと書いてある。
393 = "十日で一割の利子が付くと書いてある。"

# カズマ（Ｍ）
# display as カズマ
# （といち！？）
459 = "（といち！？）"

# めぐみん
# どうするんです？　どうするんですか？\nとりあえず撃ちますか？
355 = "どうするんです？　どうするんですか？\\nとりあえず撃ちますか？"

# ダクネス
# お、落ちつけめぐみん！\nなんだったら私を罵ってくれて構わない！
319 = "お、落ちつけめぐみん！\\nなんだったら私を罵ってくれて構わない！"

# カズマ
# お前こそ落ちつけ、支離滅裂だ。
324 = "お前こそ落ちつけ、支離滅裂だ。"

# アクア
# うう、カズマ……どうしよう。
303 = "うう、カズマ……どうしよう。"

# カズマ（Ｍ）
# display as カズマ
# （証書は正規の物、\n　そしてご丁寧にアクアのサイン入り）
464 = "（証書は正規の物、\\n　そしてご丁寧にアクアのサイン入り）"

# カズマ（Ｍ）
# display as カズマ
# （といちとなると、時間との勝負だし……）
458 = "（といちとなると、時間との勝負だし……）"

# カズマ
# とりあえず……\n借金を返していく方向で行くしかないだろうな。
354 = "とりあえず……\\n借金を返していく方向で行くしかないだろうな。"

# めぐみん
# この金額をですか！
332 = "この金額をですか！"

# カズマ
# 指輪の解除料、３０００万エリスの１／１０だ！
401 = "指輪の解除料、３０００万エリスの１／１０だ！"

# めぐみん
# お、おお、そう考えると\n行けるような気がしてきました！
318 = "お、おお、そう考えると\\n行けるような気がしてきました！"

# ダクネス
# それはたぶん気のせいだぞ。
351 = "それはたぶん気のせいだぞ。"

# アクア
# あ、あの、カズマさん？\nそれでどうやって借金を返すんですか？
292 = "あ、あの、カズマさん？\\nそれでどうやって借金を返すんですか？"

# カズマ
# 働くに決まってるだろう。
392 = "働くに決まってるだろう。"

# アクア
# ええと、私、１人で？
313 = "ええと、私、１人で？"

# カズマ
# はあ……ダクネス、めぐみん。\n協力してくれるか？
363 = "はあ……ダクネス、めぐみん。\\n協力してくれるか？"

# めぐみん
# しかたありませんよね。
339 = "しかたありませんよね。"

# ダクネス
# 話を聞いてしまった以上、\n放っておくこともできないからな。
451 = "話を聞いてしまった以上、\\n放っておくこともできないからな。"

# アクア
# うぅ、ありがとう。
301 = "うぅ、ありがとう。"

# カズマ（Ｍ）
# display as カズマ
# （こうして、俺たちは\n　明日をも知れぬ境遇に\n　いきなり立たされたのだった……）
456 = "（こうして、俺たちは\\n　明日をも知れぬ境遇に\\n　いきなり立たされたのだった……）"

