# root_f04.txt.scn

[info]
0 = ""

[characters]
264 = "カズマ"
263 = "ウィズ"
265 = "カズマ（Ｍ）"
261 = "アクア"

[character_subs]
# 264 = "カズマ"
312 = "？？？"

[script]
# lines: 58

# カズマ
# おー、賑やかだなぁ。
238 = "おー、賑やかだなぁ。"

# ウィズ
# そうですね。\nふふふ、この賑やかさが、私、大好きなんです。
247 = "そうですね。\\nふふふ、この賑やかさが、私、大好きなんです。"

# カズマ
# わかるわかる！\nなんつーか、ワクワクするよな。
260 = "わかるわかる！\\nなんつーか、ワクワクするよな。"

# ウィズ
# はい、とてもワクワクします。
258 = "はい、とてもワクワクします。"

# カズマ
# それで、買い出しって言ってたけど、\n何か目的の物があるんだよな？
249 = "それで、買い出しって言ってたけど、\\n何か目的の物があるんだよな？"

# ウィズ
# いえ、特には無いですよ？\nあえていうのなら、売れそうな物でしょうか。
225 = "いえ、特には無いですよ？\\nあえていうのなら、売れそうな物でしょうか。"

# カズマ（Ｍ）
# display as カズマ
# （ずいぶんとアバウトだな……）
309 = "（ずいぶんとアバウトだな……）"

# ウィズ
# ふんふん、ふっふ～ん、ふ～ん、ふふっ、ふ～ん。
259 = "ふんふん、ふっふ～ん、ふ～ん、ふふっ、ふ～ん。"

# カズマ（Ｍ）
# display as カズマ
# （あっちの店を覗いたり、\n　こっちの店を冷やかしたり……）
308 = "（あっちの店を覗いたり、\\n　こっちの店を冷やかしたり……）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、これは本当に\n　ただのウィンドウショッピングだな）
307 = "（ああ、これは本当に\\n　ただのウィンドウショッピングだな）"

# カズマ
# 楽しそうだな、ウィズ。
276 = "楽しそうだな、ウィズ。"

# ウィズ
# ええ、買うのもですけど、\nこうして見て回るのが何より好きなんです。
234 = "ええ、買うのもですけど、\\nこうして見て回るのが何より好きなんです。"

# ウィズ
# 見たこと無い物があるかもしれない。\n素敵な掘り出し物があるかもしれない。
304 = "見たこと無い物があるかもしれない。\\n素敵な掘り出し物があるかもしれない。"

# ウィズ
# そんな想像していて、\nいい物を見つけた時には\n本当に嬉しいですから。
251 = "そんな想像していて、\\nいい物を見つけた時には\\n本当に嬉しいですから。"

# カズマ
# 気持ちはわからなくないな。\n俺だって、どこかに埋もれてるお宝に\n巡り会えたらと思うと、ワクワクするし。
278 = "気持ちはわからなくないな。\\n俺だって、どこかに埋もれてるお宝に\\n巡り会えたらと思うと、ワクワクするし。"

# ウィズ
# ええ、ロマンがありますよね。
233 = "ええ、ロマンがありますよね。"

# カズマ
# と言っても、実際にはそんな\n美味い話があるわけもないだろ。\nウィズは、そういうのでガッカリしないのか？
253 = "と言っても、実際にはそんな\\n美味い話があるわけもないだろ。\\nウィズは、そういうのでガッカリしないのか？"

# ウィズ
# そうですねぇ。\n最初から宝物を求めてるわけではないですし――
248 = "そうですねぇ。\\n最初から宝物を求めてるわけではないですし――"

# ウィズ
# 私の直感に合えば、\nそれが掘り出し物ですから。
303 = "私の直感に合えば、\\nそれが掘り出し物ですから。"

# カズマ
# なるほどなぁ。\nそういう考え方もあるかぁ。
255 = "なるほどなぁ。\\nそういう考え方もあるかぁ。"

# カズマ（Ｍ）
# display as カズマ
# （なんか、そういう考え方って綺麗でいいな。\n　俺の周りの連中にはない輝きで、眩しいぜ……）
310 = "（なんか、そういう考え方って綺麗でいいな。\\n　俺の周りの連中にはない輝きで、眩しいぜ……）"

# アクア
# display as ？？？
# いらっしゃい、さぁ、いらっしゃ～い！
230 = "いらっしゃい、さぁ、いらっしゃ～い！"

# カズマ（Ｍ）
# display as カズマ
# （んん？\n　どっかで聞いたような声が……）
311 = "（んん？\\n　どっかで聞いたような声が……）"

# アクア
# 今日のお買い得はコロッケ！\n揚げたてのコロッケが安いよ～！
268 = "今日のお買い得はコロッケ！\\n揚げたてのコロッケが安いよ～！"

# アクア
# アツアツほっくほくで\n美味しいコロッケ、いかがですか～！
262 = "アツアツほっくほくで\\n美味しいコロッケ、いかがですか～！"

# カズマ（Ｍ）
# display as カズマ
# （……ああ、見つけちまった。\n　輝くどころか汚れきったものを）
306 = "（……ああ、見つけちまった。\\n　輝くどころか汚れきったものを）"

# ウィズ
# あら？\nあれは、アクア様ですね。
224 = "あら？\\nあれは、アクア様ですね。"

# カズマ
# そういや、ここの商店街でも\nバイトしてるって言ってたな。
246 = "そういや、ここの商店街でも\\nバイトしてるって言ってたな。"

# ウィズ
# コロッケですか？\n美味しそうな匂いです。
266 = "コロッケですか？\\n美味しそうな匂いです。"

# アクア
# あら、カズマじゃない。
223 = "あら、カズマじゃない。"

# カズマ
# おう、頑張ってるな。
237 = "おう、頑張ってるな。"

# ウィズ
# こんにちは、アクア様。
240 = "こんにちは、アクア様。"

# アクア
# なんでアンデッドが\n真っ昼間から堂々と出歩いてるのよ。
256 = "なんでアンデッドが\\n真っ昼間から堂々と出歩いてるのよ。"

# ウィズ
# すみません、すみません！
243 = "すみません、すみません！"

# アクア
# しかも私の従者を断りもなく\n顎で使ってるなんて、いい度胸してるじゃない。
242 = "しかも私の従者を断りもなく\\n顎で使ってるなんて、いい度胸してるじゃない。"

# カズマ
# 誰が従者だ誰が！
305 = "誰が従者だ誰が！"

# アクア
# いたっ！　ちょっと殴らないでよ！\nコロッケに髪の毛が落ちちゃうじゃない！
226 = "いたっ！　ちょっと殴らないでよ！\\nコロッケに髪の毛が落ちちゃうじゃない！"

# カズマ
# 怒る理由はそこなのかよ！
275 = "怒る理由はそこなのかよ！"

# アクア
# それで？\nなんでカズマとリッチーが一緒にいるのよ。
250 = "それで？\\nなんでカズマとリッチーが一緒にいるのよ。"

# カズマ
# この前の事件の時のお詫びで、\nウィズの手伝いをさせてもらってるだけだよ。
239 = "この前の事件の時のお詫びで、\\nウィズの手伝いをさせてもらってるだけだよ。"

# アクア
# ということは、この後私にも何かあるのね！
252 = "ということは、この後私にも何かあるのね！"

# カズマ
# いや、ないけど？
227 = "いや、ないけど？"

# アクア
# え、どうして？
232 = "え、どうして？"

# カズマ
# いやだってお前だし。
229 = "いやだってお前だし。"

# アクア
# どういう意味かしら。
254 = "どういう意味かしら。"

# カズマ
# いやだって、お前には迷惑しかかけられてないから\nお詫びをする理由なんてこれっぽっちもないし、\nって意味だ。
228 = "いやだって、お前には迷惑しかかけられてないから\\nお詫びをする理由なんてこれっぽっちもないし、\\nって意味だ。"

# アクア
# はあ？　この私がいったいどんな迷惑をかけたって\n言うのよ。
257 = "はあ？　この私がいったいどんな迷惑をかけたって\\n言うのよ。"

# カズマ
# 毎度毎度、華麗に借金をこさえてくるやつは\nどこの誰だ！
277 = "毎度毎度、華麗に借金をこさえてくるやつは\\nどこの誰だ！"

# アクア
# そ、それはあれよ。\n困った時はお互い様ってやつで。
244 = "そ、それはあれよ。\\n困った時はお互い様ってやつで。"

# カズマ
# そう、お互い様だ。\nだからお前には詫びをする気なんて\n爪の先ほどもない。
245 = "そう、お互い様だ。\\nだからお前には詫びをする気なんて\\n爪の先ほどもない。"

# アクア
# 何よ。\nそうやって外面だけよくしちゃってさ。
270 = "何よ。\\nそうやって外面だけよくしちゃってさ。"

# カズマ
# さてウィズ、\nこいつは放っといて行こうぜ。
241 = "さてウィズ、\\nこいつは放っといて行こうぜ。"

# ウィズ
# え、あ、はい。\nアクア様、失礼します。
231 = "え、あ、はい。\\nアクア様、失礼します。"

# アクア
# あ、そうだ、カズマ。\n今日は明日の仕込みで帰り遅くなるから。
222 = "あ、そうだ、カズマ。\\n今日は明日の仕込みで帰り遅くなるから。"

# カズマ
# おう、めぐみん達にも言っておく。\nんじゃな。
236 = "おう、めぐみん達にも言っておく。\\nんじゃな。"

# アクア
# え～、コロッケ、コロッケはいかがですか～！\n揚げたてコロッケ、美味しいですよ～！
235 = "え～、コロッケ、コロッケはいかがですか～！\\n揚げたてコロッケ、美味しいですよ～！"

# カズマ
# 仕込みねぇ。\nあの呼び込みの板に付きっぷりといい、\nあいつは本当に女神なのか？
269 = "仕込みねぇ。\\nあの呼び込みの板に付きっぷりといい、\\nあいつは本当に女神なのか？"

# ウィズ
# あ、あははは……。
221 = "あ、あははは……。"

