# root_d24.txt.scn

[info]
0 = ""

[characters]
247 = "カズマ（Ｍ）"
243 = "アクア"
245 = "カズマ"
249 = "クリス"

[character_subs]
# 245 = "カズマ"

[script]
# lines: 52

# カズマ（Ｍ）
# display as カズマ
# （えっと、あのバカは……）
295 = "（えっと、あのバカは……）"

# アクア
# ちょっとカズマー！
231 = "ちょっとカズマー！"

# カズマ
# おいおい、本当にいたよ。
220 = "おいおい、本当にいたよ。"

# クリス
# あは、あはははは……。
209 = "あは、あはははは……。"

# アクア
# もう、どうして街の外に逃げてこないのよ！
241 = "もう、どうして街の外に逃げてこないのよ！"

# カズマ
# は？
237 = "は？"

# アクア
# カズマがボーッとしてたせいで、\nクエストの時間が終わっちゃったんですけど！\nこの責任、どう取ってくれるんですか？
246 = "カズマがボーッとしてたせいで、\\nクエストの時間が終わっちゃったんですけど！\\nこの責任、どう取ってくれるんですか？"

# カズマ
# うん、その前にひとついいか駄女神。
217 = "うん、その前にひとついいか駄女神。"

# アクア
# あー、駄女神って言った！
213 = "あー、駄女神って言った！"

# カズマ
# このクエストを発注したのは\nお前なんだな？
223 = "このクエストを発注したのは\\nお前なんだな？"

# アクア
# ええ、そうよ。
219 = "ええ、そうよ。"

# カズマ（Ｍ）
# display as カズマ
# （しれっと言いやがった！）
296 = "（しれっと言いやがった！）"

# アクア
# だって、カズマはクリスを\n捕まえたかったんでしょ？
229 = "だって、カズマはクリスを\\n捕まえたかったんでしょ？"

# アクア
# ほら、感謝しなさいよ。\nこうしてクリスを捕まえられたのは、\nクエストを発注してあげた私のおかげなんだから。
239 = "ほら、感謝しなさいよ。\\nこうしてクリスを捕まえられたのは、\\nクエストを発注してあげた私のおかげなんだから。"

# カズマ
# 殴りたい。\nてか、殴るわ！
259 = "殴りたい。\\nてか、殴るわ！"

# クリス
# ちょっと！
232 = "ちょっと！"

# アクア
# 痛いわね！\nいきなり何するのよヒキニート！
260 = "痛いわね！\\nいきなり何するのよヒキニート！"

# カズマ
# うっさい！　お前のおかげで散々だったんだぞ！
216 = "うっさい！　お前のおかげで散々だったんだぞ！"

# カズマ
# だいたい、\n１００万エリスなんて払えもしない報酬額を\nどうして設定したんだよ！
226 = "だいたい、\\n１００万エリスなんて払えもしない報酬額を\\nどうして設定したんだよ！"

# アクア
# そう言ったのカズマじゃない！
224 = "そう言ったのカズマじゃない！"

# カズマ（Ｍ）
# display as カズマ
# （は、俺？）
297 = "（は、俺？）"

# クリス
# キミ、そんなこと言ったの？
248 = "キミ、そんなこと言ったの？"

# カズマ
# いやいやいや、言ってねえよ？
214 = "いやいやいや、言ってねえよ？"

# アクア
# 確かに言いましたー、このまま捕まえられないなら\nそれこそ１００万エリス払った方がマシだって\n言ったんですー。
291 = "確かに言いましたー、このまま捕まえられないなら\\nそれこそ１００万エリス払った方がマシだって\\n言ったんですー。"

# アクア
# だったら払って貰おうじゃないって\nクエストを発注したわけよ。
228 = "だったら払って貰おうじゃないって\\nクエストを発注したわけよ。"

# カズマ
# あー、もしかして――
212 = "あー、もしかして――"

# カズマ
# だから、このままだと\nそれこそ１００万エリス払った方がマシだったって\n無茶ぶりを――
227 = "だから、このままだと\\nそれこそ１００万エリス払った方がマシだったって\\n無茶ぶりを――"

# カズマ
# あれのことか……。
211 = "あれのことか……。"

# クリス
# 心当たりがあるんだね。
257 = "心当たりがあるんだね。"

# カズマ
# このままだと１００万エリスを払った方が\nマシだったって無茶ぶりをされるかも\nしれないって……。
222 = "このままだと１００万エリスを払った方が\\nマシだったって無茶ぶりをされるかも\\nしれないって……。"

# クリス
# もしかして事の発端って、\nお詫びは１００万エリスがいいって\nあたしが言ったせいだったり……する？
242 = "もしかして事の発端って、\\nお詫びは１００万エリスがいいって\\nあたしが言ったせいだったり……する？"

# カズマ
# まあ、そうなるな。
240 = "まあ、そうなるな。"

# クリス
# でも、微妙にアクアさんの話と\n噛み合っていないような。
234 = "でも、微妙にアクアさんの話と\\n噛み合っていないような。"

# カズマ
# アクアのことだから、\n自分に都合のいいキーワードだけを拾って、\nさらに自分に都合良く俺の言葉を解釈したんだろ。
244 = "アクアのことだから、\\n自分に都合のいいキーワードだけを拾って、\\nさらに自分に都合良く俺の言葉を解釈したんだろ。"

# クリス
# あはは、なるほどね。
210 = "あはは、なるほどね。"

# カズマ
# なあ、アクア。\nお前がわざわざクエストを発注したのは\n１００万エリスが欲しいからなんだよな。
235 = "なあ、アクア。\\nお前がわざわざクエストを発注したのは\\n１００万エリスが欲しいからなんだよな。"

# アクア
# だってなんの確約もない状況でクリスを捕まえても\nカズマは１エリスも払わないでしょ。\nケチだし。
230 = "だってなんの確約もない状況でクリスを捕まえても\\nカズマは１エリスも払わないでしょ。\\nケチだし。"

# カズマ
# うん、最後の一言余計な。
218 = "うん、最後の一言余計な。"

# カズマ
# でだ、俺がクリスを連れて逃げるって\n思わなかったのか？
233 = "でだ、俺がクリスを連れて逃げるって\\n思わなかったのか？"

# アクア
# 私だってバカじゃないわ。\nカズマがそうすることくらい計算のうちよ。
292 = "私だってバカじゃないわ。\\nカズマがそうすることくらい計算のうちよ。"

# カズマ
# へー、お前にしては珍しく計算なんてしたんだね。\n偉いね。すごいね。\nそれで？
238 = "へー、お前にしては珍しく計算なんてしたんだね。\\n偉いね。すごいね。\\nそれで？"

# アクア
# それでって？
225 = "それでって？"

# カズマ
# いやだから、俺がクリスを連れて逃げると計算して\nそのあとどうするって思ったんだよ。
215 = "いやだから、俺がクリスを連れて逃げると計算して\\nそのあとどうするって思ったんだよ。"

# アクア
# 街を追われて、この辺に逃げてくると思ったのよ。\nそして油断をしてるところに！
293 = "街を追われて、この辺に逃げてくると思ったのよ。\\nそして油断をしてるところに！"

# カズマ
# お前が捕まえると。
221 = "お前が捕まえると。"

# アクア
# 我ながら完璧な作戦だとほれぼれしちゃったわ。
258 = "我ながら完璧な作戦だとほれぼれしちゃったわ。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、その完璧な作戦は\n　失敗に終わったんだけどな）
298 = "（まあ、その完璧な作戦は\\n　失敗に終わったんだけどな）"

# カズマ
# はあ……。\nこの駄女神と、エリス様をチェンジしたい。
236 = "はあ……。\\nこの駄女神と、エリス様をチェンジしたい。"

# クリス
# あ、あはは。\nさすがのエリス様もカズマのパーティーに\n入るのは嫌がると思うな。
208 = "あ、あはは。\\nさすがのエリス様もカズマのパーティーに\\n入るのは嫌がると思うな。"

# カズマ（Ｍ）
# display as カズマ
# （結局残ったのは、クリスへの新しい貸しだけ）
300 = "（結局残ったのは、クリスへの新しい貸しだけ）"

# カズマ（Ｍ）
# display as カズマ
# （俺は貸しや借金を返すために\n　この世界に来たわけじゃないのに……）
299 = "（俺は貸しや借金を返すために\\n　この世界に来たわけじゃないのに……）"

# カズマ（Ｍ）
# display as カズマ
# （いったい、このくだらない冒険は\n　いつまで続くんだ！！）
294 = "（いったい、このくだらない冒険は\\n　いつまで続くんだ！！）"

