# root_e05.txt.scn

[info]
0 = ""

[characters]
392 = "アクア"
393 = "カズマ"
387 = "ゆんゆん"
394 = "カズマ（Ｍ）"
395 = "ダクネス"
385 = "めぐみん"

[character_subs]
# 393 = "カズマ"

[script]
# lines: 97

# アクア
# ぷは～、美味しい！\nひと仕事した後のシュワシュワは格別ね。
370 = "ぷは～、美味しい！\\nひと仕事した後のシュワシュワは格別ね。"

# カズマ
# お前は何もやってないだろうが。
340 = "お前は何もやってないだろうが。"

# アクア
# あー、もうコップが空っぽ。\nカズマ、注いでよ。
322 = "あー、もうコップが空っぽ。\\nカズマ、注いでよ。"

# カズマ
# はあ、なんで俺が。
366 = "はあ、なんで俺が。"

# ゆんゆん
# あっ、私が注ぎます！
313 = "あっ、私が注ぎます！"

# アクア
# え、いいの？\n悪いわね。
335 = "え、いいの？\\n悪いわね。"

# カズマ（Ｍ）
# display as カズマ
# （悪いと思うなら自分でやれよ……）
458 = "（悪いと思うなら自分でやれよ……）"

# アクア
# おーっととと！\nへえ、ゆんゆんってシュワシュワ注ぐの上手ね。
339 = "おーっととと！\\nへえ、ゆんゆんってシュワシュワ注ぐの上手ね。"

# ゆんゆん
# みなさんよくシュワシュワを飲まれていますから、\nこういう機会があることを想定して\n勉強していたんです。
382 = "みなさんよくシュワシュワを飲まれていますから、\\nこういう機会があることを想定して\\n勉強していたんです。"

# ゆんゆん
# 泡が３でシュワシュワが７なんですよね？
405 = "泡が３でシュワシュワが７なんですよね？"

# アクア
# う、うん、そうね……。
332 = "う、うん、そうね……。"

# ダクネス
# なあ、カズマ。\n魚はどう調理する。
363 = "なあ、カズマ。\\n魚はどう調理する。"

# カズマ
# あー、そうだなー。
321 = "あー、そうだなー。"

# ゆんゆん
# あっ！\n暖炉に火を入れていいなら、\n美味しい塩焼きを作りますよ？
316 = "あっ！\\n暖炉に火を入れていいなら、\\n美味しい塩焼きを作りますよ？"

# カズマ
# へえ、ゆんゆんってそんな料理も作れるのか。
371 = "へえ、ゆんゆんってそんな料理も作れるのか。"

# ゆんゆん
# みんなとキャンプに行くことを想定して、\nお魚の塩焼きの美味しい作り方を\n勉強しておいたんです。
384 = "みんなとキャンプに行くことを想定して、\\nお魚の塩焼きの美味しい作り方を\\n勉強しておいたんです。"

# カズマ
# そ、そうなんだ……。
348 = "そ、そうなんだ……。"

# カズマ（Ｍ）
# display as カズマ
# （さっきから想定ばっかりで、\n　なんか聞いてるのが辛い！）
456 = "（さっきから想定ばっかりで、\\n　なんか聞いてるのが辛い！）"

# めぐみん
# それで、その想定していた事態は起こったんですか？
352 = "それで、その想定していた事態は起こったんですか？"

# カズマ（Ｍ）
# display as カズマ
# （こいつ容赦ねえな！）
455 = "（こいつ容赦ねえな！）"

# ゆんゆん
# そ、それは、まだ起こってないけど……。
349 = "そ、それは、まだ起こってないけど……。"

# ゆんゆん
# でも、ふにふらさんとどどんこさんが\n今度ゆんゆんの奢りでなら行ってもいいわよって\n言ってくれたわ！
360 = "でも、ふにふらさんとどどんこさんが\\n今度ゆんゆんの奢りでなら行ってもいいわよって\\n言ってくれたわ！"

# カズマ
# よし、わかった！\nそれ以上言わなくていい！\n頼むから言わないでくれ！
388 = "よし、わかった！\\nそれ以上言わなくていい！\\n頼むから言わないでくれ！"

# ゆんゆん
# え？　え？
336 = "え？　え？"

# ダクネス
# みんなできたぞ。\nまずは蒸し料理だ。
383 = "みんなできたぞ。\\nまずは蒸し料理だ。"

# ダクネス
# あと、新鮮な野菜も手に入ったから\nサラダを用意した。
317 = "あと、新鮮な野菜も手に入ったから\\nサラダを用意した。"

# アクア
# おっ、待ってましたー。
338 = "おっ、待ってましたー。"

# めぐみん
# それでは、いただきます！
353 = "それでは、いただきます！"

# アクア
# あむあむあむ、うう～ん、これは絶品ね！
318 = "あむあむあむ、うう～ん、これは絶品ね！"

# めぐみん
# はい、ほっぺたが落ちてしまいそうですよ。
367 = "はい、ほっぺたが落ちてしまいそうですよ。"

# カズマ
# んじゃ、俺も――
391 = "んじゃ、俺も――"

# ゆんゆん
# …………。
310 = "…………。"

# カズマ
# ほら、ゆんゆんも食えよ。
376 = "ほら、ゆんゆんも食えよ。"

# ゆんゆん
# い、いいんですか？
324 = "い、いいんですか？"

# めぐみん
# ありがたく食べるといいですよ。\n私が釣り上げた魚を！
319 = "ありがたく食べるといいですよ。\\n私が釣り上げた魚を！"

# ダクネス
# いや、それはゆんゆんの釣った魚だぞ？
330 = "いや、それはゆんゆんの釣った魚だぞ？"

# めぐみん
# ……この場合、偉いのは美味しく育った魚です。\nゆんゆんの手柄というわけではありませんよね。
311 = "……この場合、偉いのは美味しく育った魚です。\\nゆんゆんの手柄というわけではありませんよね。"

# カズマ
# まったく、素直じゃないな。
379 = "まったく、素直じゃないな。"

# めぐみん
# わ、私はいつだって素直ですよ。\n素直が服を着て歩いていると言っても\n過言ではありませんね。
389 = "わ、私はいつだって素直ですよ。\\n素直が服を着て歩いていると言っても\\n過言ではありませんね。"

# ゆんゆん
# あっ！\nカズマさんお皿、空っぽですね。\nお料理、盛り付けます。
315 = "あっ！\\nカズマさんお皿、空っぽですね。\\nお料理、盛り付けます。"

# ゆんゆん
# みなさんもおかわりが欲しかったら\n言ってくださいね？
381 = "みなさんもおかわりが欲しかったら\\n言ってくださいね？"

# カズマ
# いやいや、ゆんゆんはお客さんなんだぜ？\n気を遣わず食事を楽しんてくれよ。\nそういう雑用はアクアに任せておけばいい。
331 = "いやいや、ゆんゆんはお客さんなんだぜ？\\n気を遣わず食事を楽しんてくれよ。\\nそういう雑用はアクアに任せておけばいい。"

# アクア
# んぐんぐんぐ、ぷはー！\nへ？　なんか言った？
390 = "んぐんぐんぐ、ぷはー！\\nへ？　なんか言った？"

# カズマ（Ｍ）
# display as カズマ
# （ダメだこいつ！　もう酔ってやがる！）
457 = "（ダメだこいつ！　もう酔ってやがる！）"

# ゆんゆん
# ほら、めぐみん。\n口の周りについてるよ。\n拭いてあげるからじっとして。
375 = "ほら、めぐみん。\\n口の周りについてるよ。\\n拭いてあげるからじっとして。"

# めぐみん
# 子供じゃないんです。\nそれくらい自分でできますよ。
401 = "子供じゃないんです。\\nそれくらい自分でできますよ。"

# ゆんゆん
# いいから！\nはい、綺麗になった。
326 = "いいから！\\nはい、綺麗になった。"

# めぐみん
# …………。
# 310 = "…………。"

# ゆんゆん
# な、なに？\nじっと見つめたりして？
361 = "な、なに？\\nじっと見つめたりして？"

# めぐみん
# いえ、気持ち悪いなと思って。
328 = "いえ、気持ち悪いなと思って。"

# ゆんゆん
# 酷い！　酷いよめぐみん！
454 = "酷い！　酷いよめぐみん！"

# めぐみん
# ですが、さっきからやけに浮かれて、\n気持ち悪いと思うのも仕方ありませんよ。
359 = "ですが、さっきからやけに浮かれて、\\n気持ち悪いと思うのも仕方ありませんよ。"

# ゆんゆん
# 私、そんなに浮かれてるかな？
449 = "私、そんなに浮かれてるかな？"

# めぐみん
# 誰が見ても明らかに浮かれていますよ。
452 = "誰が見ても明らかに浮かれていますよ。"

# アクア
# そうね、いつもより\nよく笑ってるのは間違いないわね。
351 = "そうね、いつもより\\nよく笑ってるのは間違いないわね。"

# ダクネス
# 私も、いつもは引っ込み思案な印象を受けるが、\n今日は積極的だな。
450 = "私も、いつもは引っ込み思案な印象を受けるが、\\n今日は積極的だな。"

# カズマ
# まあ、いつもよりテンションが高いかな。\n何かいいことでもあったのか？
377 = "まあ、いつもよりテンションが高いかな。\\n何かいいことでもあったのか？"

# ゆんゆん
# あったというか……、\nええと、その……今がまさにそれなんです。
314 = "あったというか……、\\nええと、その……今がまさにそれなんです。"

# アクア
# ははーん、なるほどね。
369 = "ははーん、なるほどね。"

# アクア
# このアクア様と一緒に晩餐を囲めるなんて\n幸せ以外の何ものでもないもの。\nその気持ちは理解できるわ！
343 = "このアクア様と一緒に晩餐を囲めるなんて\\n幸せ以外の何ものでもないもの。\\nその気持ちは理解できるわ！"

# カズマ
# そんなわけあるか。
356 = "そんなわけあるか。"

# ゆんゆん
# いいえ、間違ってません。
325 = "いいえ、間違ってません。"

# ゆんゆん
# こうしてみなさんと食卓を囲めることが、\nお呼ばれしていることが嬉しいんです！
342 = "こうしてみなさんと食卓を囲めることが、\\nお呼ばれしていることが嬉しいんです！"

# ダクネス
# そうなのか？\nこのくらい、そこまで喜ばれるようなことでも\nないと思うが。
350 = "そうなのか？\\nこのくらい、そこまで喜ばれるようなことでも\\nないと思うが。"

# めぐみん
# まあ、ゆんゆんは昔からぼっちでしたからね。\nこういうことに馴れていないのですよ。
378 = "まあ、ゆんゆんは昔からぼっちでしたからね。\\nこういうことに馴れていないのですよ。"

# めぐみん
# 思い返せば、体育の授業では\n組む相手がいなくて\nいつも先生とペアを組んでいましたね。
404 = "思い返せば、体育の授業では\\n組む相手がいなくて\\nいつも先生とペアを組んでいましたね。"

# めぐみん
# それに図書室では、\n『魚類とだって友達になれる』なる本を\n借りるほどのぼっちです。
354 = "それに図書室では、\\n『魚類とだって友達になれる』なる本を\\n借りるほどのぼっちです。"

# ゆんゆん
# ちょ、ちょっとめぐみん！\n余計なこと言わないでよ！
357 = "ちょ、ちょっとめぐみん！\\n余計なこと言わないでよ！"

# めぐみん
# 友と呼べるものを\n持ったことのないゆんゆんが\n舞い上がってしまっても仕方がないですね。
398 = "友と呼べるものを\\n持ったことのないゆんゆんが\\n舞い上がってしまっても仕方がないですね。"

# カズマ
# そ、そうか……うん……。\nなんつーか、それなら仕方がないか？
347 = "そ、そうか……うん……。\\nなんつーか、それなら仕方がないか？"

# ゆんゆん
# み、皆さん、腫れ物に触れるみたいに\n顔を背けないでくださいっ！
380 = "み、皆さん、腫れ物に触れるみたいに\\n顔を背けないでくださいっ！"

# ゆんゆん
# めぐみんも、適当なことを言わないで！\nぼっちじゃないし！\nちゃんと友達だっていたし！
386 = "めぐみんも、適当なことを言わないで！\\nぼっちじゃないし！\\nちゃんと友達だっていたし！"

# めぐみん
# ほほう、友達とは誰のことです？\n言っておきますが、道端の小石は\n友達とは言えませんよ？
374 = "ほほう、友達とは誰のことです？\\n言っておきますが、道端の小石は\\n友達とは言えませんよ？"

# ゆんゆん
# な、何よ！\nそんなに私をぼっちにしたいの！？
362 = "な、何よ！\\nそんなに私をぼっちにしたいの！？"

# めぐみん
# したいも何も事実です。
344 = "したいも何も事実です。"

# ゆんゆん
# そ、そういうめぐみんだって\n昔から色々あれだったくせに！
346 = "そ、そういうめぐみんだって\\n昔から色々あれだったくせに！"

# ゆんゆん
# 今だって、みんなに\n迷惑をかけてないでしょうね？
397 = "今だって、みんなに\\n迷惑をかけてないでしょうね？"

# めぐみん
# はい？\n迷惑どころかみんな私に感謝していますよ。\nありがとうめぐみん、と口々に言うことでしょう。
368 = "はい？\\n迷惑どころかみんな私に感謝していますよ。\\nありがとうめぐみん、と口々に言うことでしょう。"

# カズマ
# ありがとう、めぐみん。
320 = "ありがとう、めぐみん。"

# めぐみん
# ちょっと、どうして無感情なんですか！
358 = "ちょっと、どうして無感情なんですか！"

# カズマ
# じゃあ聞くが、爆裂魔法１発しか撃てないお前に\nどう感謝しろって言うんだ。
345 = "じゃあ聞くが、爆裂魔法１発しか撃てないお前に\\nどう感謝しろって言うんだ。"

# カズマ
# 逆に、魔力切れのお前をいつも背負って帰る\n俺にこそ感謝してほしいわ。
453 = "逆に、魔力切れのお前をいつも背負って帰る\\n俺にこそ感謝してほしいわ。"

# めぐみん
# いつも私を背負って鼻の舌を伸ばしてるくせに\n良く言いますよ！
329 = "いつも私を背負って鼻の舌を伸ばしてるくせに\\n良く言いますよ！"

# カズマ
# のの、伸ばしてねえし！
365 = "のの、伸ばしてねえし！"

# めぐみん
# それに私は、\nカズマよりもこの社会に貢献をしている自信が\nあります。
355 = "それに私は、\\nカズマよりもこの社会に貢献をしている自信が\\nあります。"

# カズマ
# ほお、所構わず爆裂魔法を撃って、\n生態系まで変えてるお前がか？
372 = "ほお、所構わず爆裂魔法を撃って、\\n生態系まで変えてるお前がか？"

# めぐみん
# うぐ、それは……。
334 = "うぐ、それは……。"

# ダクネス
# おいおい、その辺にしておけ。
337 = "おいおい、その辺にしておけ。"

# カズマ
# なんで他人事みたいな顔してんだよ！\nお前だって問題だらけなんだぞ！
364 = "なんで他人事みたいな顔してんだよ！\\nお前だって問題だらけなんだぞ！"

# ダクネス
# ほお、私が問題だらけ……。\nよし、聞こうじゃないか！
373 = "ほお、私が問題だらけ……。\\nよし、聞こうじゃないか！"

# カズマ
# 言わねえよ！
451 = "言わねえよ！"

# アクア
# あーははははははははは！
323 = "あーははははははははは！"

# カズマ
# お前は笑いすぎだ！
341 = "お前は笑いすぎだ！"

# ゆんゆん
# …………。
# 310 = "…………。"

# めぐみん
# ……なんですか？\n人の顔を見つめたりして？
312 = "……なんですか？\\n人の顔を見つめたりして？"

# ゆんゆん
# ううん、なんでもない。
333 = "ううん、なんでもない。"

# ゆんゆん
# いいなぁ……。
327 = "いいなぁ……。"

