# root_b10.txt.scn

[info]
0 = ""

[characters]
271 = "めぐみん"
278 = "カズマ"
280 = "カズマ（Ｍ）"

[character_subs]
# 278 = "カズマ"

[script]
# lines: 64

# めぐみん
# もう真っ暗ですね。
275 = "もう真っ暗ですね。"

# カズマ
# もうというか、やっとというか。\nこんなに１日が長いと思ったのは久しぶりだな。
274 = "もうというか、やっとというか。\\nこんなに１日が長いと思ったのは久しぶりだな。"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんがいてくれて助かったぜ。\n　これでもし１人だったら、\n　耐えられたかわかったもんじゃない）
330 = "（めぐみんがいてくれて助かったぜ。\\n　これでもし１人だったら、\\n　耐えられたかわかったもんじゃない）"

# めぐみん
# あの、カズマ。\n自分で言っておいてなんですが、\nアクア達、助けに来てくれるでしょうか？
236 = "あの、カズマ。\\n自分で言っておいてなんですが、\\nアクア達、助けに来てくれるでしょうか？"

# カズマ
# 大丈夫だって。\nいくらあいつらでも、帰ってこないとなれば\n心配してくれるだろうし。
290 = "大丈夫だって。\\nいくらあいつらでも、帰ってこないとなれば\\n心配してくれるだろうし。"

# めぐみん
# そうですね。\n明日になればきっと、来ますよね。
251 = "そうですね。\\n明日になればきっと、来ますよね。"

# カズマ
# ま、それまではここで２人きりだな。
268 = "ま、それまではここで２人きりだな。"

# めぐみん
# ……なんですか、改めて。
233 = "……なんですか、改めて。"

# めぐみん
# 元はと言えば、こんなことになっているのは\nカズマが軽率だからですよ？
286 = "元はと言えば、こんなことになっているのは\\nカズマが軽率だからですよ？"

# めぐみん
# 気楽に依頼を引き受けず、\nきちんと説明を聞いていれば\nこんなことにはなっていません。
295 = "気楽に依頼を引き受けず、\\nきちんと説明を聞いていれば\\nこんなことにはなっていません。"

# カズマ
# 悪かったよ。\n次からは気をつけるって。
293 = "悪かったよ。\\n次からは気をつけるって。"

# めぐみん
# ふん、言葉が軽いですね。\n本当に反省しているのですか？
267 = "ふん、言葉が軽いですね。\\n本当に反省しているのですか？"

# カズマ
# してるって。\nもっとタチの悪い呪いだったら、\n今頃どうなっているかわからなかったしな。
247 = "してるって。\\nもっとタチの悪い呪いだったら、\\n今頃どうなっているかわからなかったしな。"

# カズマ
# もっとも、このままなにも\n起こらないという保証もないのか。
276 = "もっとも、このままなにも\\n起こらないという保証もないのか。"

# めぐみん
# い、言わないでくださいよ！\nとりあえず、このまま寝ないで朝まで\n頑張りますよ！
239 = "い、言わないでくださいよ！\\nとりあえず、このまま寝ないで朝まで\\n頑張りますよ！"

# カズマ
# さすがに一睡もしないっていうのは厳しいだろ。\nここでうとうとしたら風邪引くぞ？
246 = "さすがに一睡もしないっていうのは厳しいだろ。\\nここでうとうとしたら風邪引くぞ？"

# カズマ
# ベッドが置いてある部屋もあったし、\nそこで寝ちまおうぜ。
284 = "ベッドが置いてある部屋もあったし、\\nそこで寝ちまおうぜ。"

# めぐみん
# い、一緒には寝ませんからね！？
238 = "い、一緒には寝ませんからね！？"

# カズマ
# 当たり前だろ？\nベッドはめぐみんが使えよ。\n俺はここの椅子で寝る。
292 = "当たり前だろ？\\nベッドはめぐみんが使えよ。\\n俺はここの椅子で寝る。"

# めぐみん
# え？　いいのですか？\nこんな固い椅子では\n疲れもとれないのではないですか？
245 = "え？　いいのですか？\\nこんな固い椅子では\\n疲れもとれないのではないですか？"

# カズマ
# 問題ない。\n馬小屋生活に比べれば快適なくらいだ。
288 = "問題ない。\\n馬小屋生活に比べれば快適なくらいだ。"

# カズマ（Ｍ）
# display as カズマ
# （人生なんでも経験してみるもんだ。\n　あの日々のおかげでこんなに\n　たくましくなったんだからな）
331 = "（人生なんでも経験してみるもんだ。\\n　あの日々のおかげでこんなに\\n　たくましくなったんだからな）"

# めぐみん
# そ、それはその……\n私のことを気づかって……。
249 = "そ、それはその……\\n私のことを気づかって……。"

# カズマ
# ん？　なんだ？
277 = "ん？　なんだ？"

# めぐみん
# い、いえ、なんでもないです！\nそれにしても静かですね。
237 = "い、いえ、なんでもないです！\\nそれにしても静かですね。"

# カズマ
# いつもならお前やアクア、\nそれにダクネスが騒いでる時間だしな。\n余計そう思うよ。
242 = "いつもならお前やアクア、\\nそれにダクネスが騒いでる時間だしな。\\n余計そう思うよ。"

# めぐみん
# ちょっと待ってください。\n別に私は騒いだりしていません。
259 = "ちょっと待ってください。\\n別に私は騒いだりしていません。"

# カズマ
# そう思ってるのは本人だけだろ。
253 = "そう思ってるのは本人だけだろ。"

# めぐみん
# それを言うなら、カズマはどうなんです？\nかなりうるさいですよ？\n特に、アクアを相手にしているときとか。
255 = "それを言うなら、カズマはどうなんです？\\nかなりうるさいですよ？\\n特に、アクアを相手にしているときとか。"

# カズマ
# そ、それはアクアに釣られてるからだ！\n俺のせいじゃない！
250 = "そ、それはアクアに釣られてるからだ！\\n俺のせいじゃない！"

# めぐみん
# そう思っているのは本人だけです。
252 = "そう思っているのは本人だけです。"

# めぐみん
# でも……\n賑やかなのは悪いことではないですよ。
260 = "でも……\\n賑やかなのは悪いことではないですよ。"

# めぐみん
# むしろ、団らんの一時に\n会話もないようなパーティーでは息が詰まります。\nそう考えると、私達はうまくいっていますよ。
270 = "むしろ、団らんの一時に\\n会話もないようなパーティーでは息が詰まります。\\nそう考えると、私達はうまくいっていますよ。"

# カズマ
# うまく……いっている？
243 = "うまく……いっている？"

# めぐみん
# なんですか？\n不満があるとでも言うのですか？
265 = "なんですか？\\n不満があるとでも言うのですか？"

# カズマ
# 不満だらけにきまってんだろ！\n言わなきゃわからないのか！？\n言わなきゃダメなのか！？
285 = "不満だらけにきまってんだろ！\\n言わなきゃわからないのか！？\\n言わなきゃダメなのか！？"

# めぐみん
# カズマは自分のことを棚に上げて\n贅沢を言いすぎです。
279 = "カズマは自分のことを棚に上げて\\n贅沢を言いすぎです。"

# カズマ
# そんなことはない！\n俺が求めているのはささやかで当たり前のことだ！
256 = "そんなことはない！\\n俺が求めているのはささやかで当たり前のことだ！"

# めぐみん
# なんですか、それ。\nまるで私達が当たり前のことを\nできていないかのような言いぐさですね？
264 = "なんですか、それ。\\nまるで私達が当たり前のことを\\nできていないかのような言いぐさですね？"

# カズマ
# まるでじゃないからな！\nできてないからな！
269 = "まるでじゃないからな！\\nできてないからな！"

# めぐみん
# …………。
231 = "…………。"

# カズマ
# めぐみん？\nなんだよ、急に黙ったりして。\nトイレに行きたくなったのか？
272 = "めぐみん？\\nなんだよ、急に黙ったりして。\\nトイレに行きたくなったのか？"

# めぐみん
# ち、違いますっ！\nただ、ちょっと汗が気持ち悪いなって\n思っただけです。
258 = "ち、違いますっ！\\nただ、ちょっと汗が気持ち悪いなって\\n思っただけです。"

# カズマ
# ああ、なんだかんだで結構、汗かいたしな。
234 = "ああ、なんだかんだで結構、汗かいたしな。"

# カズマ
# 風呂に入ってきたらどうだ？\n奥にあっただろ。
329 = "風呂に入ってきたらどうだ？\\n奥にあっただろ。"

# めぐみん
# ええ？　こんな状況でですか？
244 = "ええ？　こんな状況でですか？"

# カズマ
# だって気になるんだろ？\nああ、１人が怖いっていうなら\n一緒に入ってやろうか？
257 = "だって気になるんだろ？\\nああ、１人が怖いっていうなら\\n一緒に入ってやろうか？"

# めぐみん
# な、なに馬鹿なことを言い出すんですか！\n１人で大丈夫です！
262 = "な、なに馬鹿なことを言い出すんですか！\\n１人で大丈夫です！"

# カズマ
# 汗、拭いてやろうか？
296 = "汗、拭いてやろうか？"

# めぐみん
# ……それ、本気で言ってるのですか？
232 = "……それ、本気で言ってるのですか？"

# カズマ
# ああ、本気だぞ？
235 = "ああ、本気だぞ？"

# めぐみん
# 変態ですね。
289 = "変態ですね。"

# カズマ
# な、なんでだよっ！\n下心なんてなにもないぞ！？\nむしろ親切心だってーの！
263 = "な、なんでだよっ！\\n下心なんてなにもないぞ！？\\nむしろ親切心だってーの！"

# カズマ
# 第一、めぐみん相手におかしなことなんか\n考えるわけないだろ？
327 = "第一、めぐみん相手におかしなことなんか\\n考えるわけないだろ？"

# めぐみん
# それはそれで失礼極まりないです。
254 = "それはそれで失礼極まりないです。"

# めぐみん
# とにかく、結構です。\nさっき調べた時に見つけた浴室を借りますから。
261 = "とにかく、結構です。\\nさっき調べた時に見つけた浴室を借りますから。"

# カズマ
# クリエイト・ウォーターでいいか？
281 = "クリエイト・ウォーターでいいか？"

# めぐみん
# いいかって、なにがです？
240 = "いいかって、なにがです？"

# カズマ
# クリエイト・ウォーターで水を出すから\nそれを浴びるかってことだけど。
282 = "クリエイト・ウォーターで水を出すから\\nそれを浴びるかってことだけど。"

# めぐみん
# はあ……。\nそれでは、どう考えても風邪を引きますよ。
266 = "はあ……。\\nそれでは、どう考えても風邪を引きますよ。"

# めぐみん
# もうちょっと気を使えないのですか、カズマは。\nそんなこともわからないとは\nどこまで残念なんです？
273 = "もうちょっと気を使えないのですか、カズマは。\\nそんなこともわからないとは\\nどこまで残念なんです？"

# めぐみん
# クリエイト・ウォーターは遠慮します。\nさっき調べた時に見つけた浴室を借りますので。
283 = "クリエイト・ウォーターは遠慮します。\\nさっき調べた時に見つけた浴室を借りますので。"

# めぐみん
# いいですか？\n絶対に覗いたりしないでくださいよ？\n絶対にですよ！
241 = "いいですか？\\n絶対に覗いたりしないでくださいよ？\\n絶対にですよ！"

# カズマ
# するか！
248 = "するか！"

[selections]
328 = "風呂に入ってきたらどうだ？"
294 = "拭いてやろうか？"
# 281 = "クリエイト・ウォーターでいいか？"
