# root_b04.txt.scn

[info]
0 = ""

[characters]
134 = "カズマ"
131 = "めぐみん"
137 = "カズマ（Ｍ）"

[character_subs]
# 134 = "カズマ"

[script]
# lines: 20

# カズマ
# へえ……。\n呪われているとは思えないくらい綺麗な教会だな。\nてっきり、廃墟みたいな所だと思ってたぜ。
130 = "へえ……。\\n呪われているとは思えないくらい綺麗な教会だな。\\nてっきり、廃墟みたいな所だと思ってたぜ。"

# めぐみん
# ここはエリス教団の教会ですから。\n手入れされていて当然ですよ。
124 = "ここはエリス教団の教会ですから。\\n手入れされていて当然ですよ。"

# カズマ（Ｍ）
# display as カズマ
# （エリス教団、つまりエリス様の教会か。\n　そんなに人々に支持されているのか）
154 = "（エリス教団、つまりエリス様の教会か。\\n　そんなに人々に支持されているのか）"

# カズマ
# なあ、今更だけど\nエリス様ってそんなに凄い女神なのか？
129 = "なあ、今更だけど\\nエリス様ってそんなに凄い女神なのか？"

# めぐみん
# カズマ、今まで一体\nどんな生活をしていたんですか？
135 = "カズマ、今まで一体\\nどんな生活をしていたんですか？"

# めぐみん
# エリス様と言えば、幸運を司る女神として\n広く有名で、信者も多く、\n通貨の単位になるほどなのですよ？
132 = "エリス様と言えば、幸運を司る女神として\\n広く有名で、信者も多く、\\n通貨の単位になるほどなのですよ？"

# めぐみん
# それを知らないなんて、\nどんな辺境で育ったのですか？
126 = "それを知らないなんて、\\nどんな辺境で育ったのですか？"

# カズマ
# い、いや、まあ……色々とな？
123 = "い、いや、まあ……色々とな？"

# カズマ（Ｍ）
# display as カズマ
# （まさか、異世界から来ましたなんて言っても\n　信じてもらえないよなぁ）
152 = "（まさか、異世界から来ましたなんて言っても\\n　信じてもらえないよなぁ）"

# めぐみん
# エリス様は世界中で敬われ愛されている、\nまさに女神の中の女神と\n言っても過言ではありませんからね。
133 = "エリス様は世界中で敬われ愛されている、\\nまさに女神の中の女神と\\n言っても過言ではありませんからね。"

# めぐみん
# そんなエリス様の教会が\n汚れているなどもってのほかだって\n思う人も多いでしょうから――
127 = "そんなエリス様の教会が\\n汚れているなどもってのほかだって\\n思う人も多いでしょうから――"

# めぐみん
# 清掃が行き届いていても\n別におかしくはありませんよ。
142 = "清掃が行き届いていても\\n別におかしくはありませんよ。"

# カズマ
# ち、ちなみに、\nアクシズ教の女神アクアはどうなんだ？
128 = "ち、ちなみに、\\nアクシズ教の女神アクアはどうなんだ？"

# めぐみん
# カズマ。\nあの教団には関わらないほうがいいですよ。
136 = "カズマ。\\nあの教団には関わらないほうがいいですよ。"

# めぐみん
# 一部の信者が悪目立ちしすぎていて、\n評判がいいとは、お世辞にも言えないのです。
138 = "一部の信者が悪目立ちしすぎていて、\\n評判がいいとは、お世辞にも言えないのです。"

# カズマ（Ｍ）
# display as カズマ
# （うーん、アクアはエリス様のことを\n　どう思ってるんだ？）
151 = "（うーん、アクアはエリス様のことを\\n　どう思ってるんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （変にライバル視なんてしてたら、\n　除霊を頼むどころの話じゃなくなるし）
155 = "（変にライバル視なんてしてたら、\\n　除霊を頼むどころの話じゃなくなるし）"

# めぐみん
# それで、これからどうするんですか？\n下見を続けるんですか？
125 = "それで、これからどうするんですか？\\n下見を続けるんですか？"

# カズマ
# ああ、ここまで来たんだし\n中の様子も見ていこう。
122 = "ああ、ここまで来たんだし\\n中の様子も見ていこう。"

# カズマ（Ｍ）
# display as カズマ
# （アクアを説得する材料が欲しいからな。\n　中になにかヒントがあるといいんだが）
153 = "（アクアを説得する材料が欲しいからな。\\n　中になにかヒントがあるといいんだが）"

