# root_b17.txt.scn

[info]
0 = ""

[characters]
341 = "カズマ"
329 = "めぐみん"
345 = "カズマ（Ｍ）"

[character_subs]
# 341 = "カズマ"

[script]
# lines: 110

# カズマ
# …………。
271 = "…………。"

# めぐみん
# カズマ……カズマ……。
342 = "カズマ……カズマ……。"

# カズマ（Ｍ）
# display as カズマ
# （んあ？\n　誰か、俺を呼んでる？）
421 = "（んあ？\\n　誰か、俺を呼んでる？）"

# めぐみん
# カズマ、起きてください！\n大変なんです！
344 = "カズマ、起きてください！\\n大変なんです！"

# カズマ（Ｍ）
# display as カズマ
# （あっ！）
419 = "（あっ！）"

# カズマ
# すまん！　寝ちまって……た？
287 = "すまん！　寝ちまって……た？"

# めぐみん
# う、うう……。
280 = "う、うう……。"

# カズマ
# なんだ、夢か。
318 = "なんだ、夢か。"

# めぐみん
# 夢じゃありませんよ、現実です！\n起きてください！
359 = "夢じゃありませんよ、現実です！\\n起きてください！"

# カズマ
# いやいや、今のめぐみんの格好を\n夢以外でどう解釈しろっていうんだよ。
277 = "いやいや、今のめぐみんの格好を\\n夢以外でどう解釈しろっていうんだよ。"

# めぐみん
# それは私が聞きたいです！
302 = "それは私が聞きたいです！"

# カズマ
# ははーん、なるほど？\nなんだかんだ言って、\nウェディングドレスには憧れがあったんだな。
323 = "ははーん、なるほど？\\nなんだかんだ言って、\\nウェディングドレスには憧れがあったんだな。"

# カズマ
# 乙女だな、めぐみん。
349 = "乙女だな、めぐみん。"

# めぐみん
# 憧れがあったのは否定しませんが、\n私が好きで着たわけじゃないんです！
363 = "憧れがあったのは否定しませんが、\\n私が好きで着たわけじゃないんです！"

# カズマ
# は？　どういうことだ？
324 = "は？　どういうことだ？"

# めぐみん
# 目が覚めたら……着ていたんですよ。
366 = "目が覚めたら……着ていたんですよ。"

# カズマ
# マジで？
348 = "マジで？"

# めぐみん
# しかも脱げないんです。\n布が肌に貼り付いたみたいで、\n引っ張ると痛くて。
285 = "しかも脱げないんです。\\n布が肌に貼り付いたみたいで、\\n引っ張ると痛くて。"

# カズマ
# どれ、俺にもやらせてみろ。
315 = "どれ、俺にもやらせてみろ。"

# めぐみん
# ま、まま、待ってください！\nそれは絶対にダメです！
326 = "ま、まま、待ってください！\\nそれは絶対にダメです！"

# カズマ
# は？　なんでだよ。
325 = "は？　なんでだよ。"

# めぐみん
# 脱げたりしたらどうするんですか！
413 = "脱げたりしたらどうするんですか！"

# カズマ
# それはそれでいいことだろ。
300 = "それはそれでいいことだろ。"

# めぐみん
# それはそうですけど、\nウェディングレスをカズマに脱がされるなんて\n屈辱以外の何物でもありません！
299 = "それはそうですけど、\\nウェディングレスをカズマに脱がされるなんて\\n屈辱以外の何物でもありません！"

# カズマ
# 本当に怒るよ？
364 = "本当に怒るよ？"

# めぐみん
# うう……。\nこれはどういうことなのでしょう？
281 = "うう……。\\nこれはどういうことなのでしょう？"

# カズマ
# まあ、普通に考えたら呪いの影響だろうな。
328 = "まあ、普通に考えたら呪いの影響だろうな。"

# めぐみん
# 結婚式を挙げさせるために、\n強硬手段に出たと？
411 = "結婚式を挙げさせるために、\\n強硬手段に出たと？"

# カズマ
# 霊の気も長くないってことなんだろ。\nというわけで、おやすみ。
415 = "霊の気も長くないってことなんだろ。\\nというわけで、おやすみ。"

# めぐみん
# どうしてそこで寝るんですか！\n訳わかりません！
313 = "どうしてそこで寝るんですか！\\n訳わかりません！"

# カズマ
# いやだってドレスは脱げない、\nかといって結婚式も挙げる気もないじゃ\nどうすることもできないだろ。
279 = "いやだってドレスは脱げない、\\nかといって結婚式も挙げる気もないじゃ\\nどうすることもできないだろ。"

# カズマ
# とれる選択肢はただひとつ、それは寝るだ。\nというわけで、おやすみ。
312 = "とれる選択肢はただひとつ、それは寝るだ。\\nというわけで、おやすみ。"

# めぐみん
# もー！　もー！\n寝ないでください！
335 = "もー！　もー！\\n寝ないでください！"

# カズマ
# あーっ、俺にどうして欲しいんだよ！\nまさかウェディングドレスの感想を\n言って欲しいとか言うんじゃないだろうな？
276 = "あーっ、俺にどうして欲しいんだよ！\\nまさかウェディングドレスの感想を\\n言って欲しいとか言うんじゃないだろうな？"

# カズマ
# それを言ってどうなる？\nギャルゲーみたいに好感度が上がって、\nフラグが立ってその先にあるのはなんだ！
303 = "それを言ってどうなる？\\nギャルゲーみたいに好感度が上がって、\\nフラグが立ってその先にあるのはなんだ！"

# カズマ
# 俺に攻略して欲しかったら、\n俺好みの淑女になりたまえ！
354 = "俺に攻略して欲しかったら、\\n俺好みの淑女になりたまえ！"

# カズマ
# 俺は、好きでも無いキャラのルートを\n攻略するほど暇じゃあないんだ！
355 = "俺は、好きでも無いキャラのルートを\\n攻略するほど暇じゃあないんだ！"

# めぐみん
# すみません、言っていることのほとんどを\n理解できませんでした。
288 = "すみません、言っていることのほとんどを\\n理解できませんでした。"

# カズマ
# うん、そうだよね、ごめん。\nあまりにも眠くて取り乱した。
282 = "うん、そうだよね、ごめん。\\nあまりにも眠くて取り乱した。"

# めぐみん
# もう、訳のわからないことばかり言ってないで\n助けてくださいよ！
334 = "もう、訳のわからないことばかり言ってないで\\n助けてくださいよ！"

# カズマ
# そのままでもいいんじゃないか？\n割と似合ってるし。
293 = "そのままでもいいんじゃないか？\\n割と似合ってるし。"

# めぐみん
# 面倒だって思ってるでしょう。
416 = "面倒だって思ってるでしょう。"

# カズマ
# うん。
283 = "うん。"

# めぐみん
# 真面目に考えてください。\nそうしないと……朝日を拝めなくなりますよ？
404 = "真面目に考えてください。\\nそうしないと……朝日を拝めなくなりますよ？"

# カズマ
# それはどういう意味かね？
301 = "それはどういう意味かね？"

# めぐみん
# 魔力はすでに回復しています。
418 = "魔力はすでに回復しています。"

# カズマ
# 察した。\nそれでは解決方法を模索しようじゃないか。
361 = "察した。\\nそれでは解決方法を模索しようじゃないか。"

# めぐみん
# ドレスは脱げません、これは本当です。
346 = "ドレスは脱げません、これは本当です。"

# カズマ
# 体に異変は？
351 = "体に異変は？"

# めぐみん
# そういうのはありませんね。
292 = "そういうのはありませんね。"

# カズマ
# 魔力が増幅してるってのもないよな？
417 = "魔力が増幅してるってのもないよな？"

# めぐみん
# なんですか、その質問。
320 = "なんですか、その質問。"

# カズマ
# 俺がつけてた指輪にはそういう効果があっただろ？
353 = "俺がつけてた指輪にはそういう効果があっただろ？"

# めぐみん
# 確かにそうですね。
406 = "確かにそうですね。"

# カズマ
# 今だから言うけど、あのまま指輪をつけてたら、\nいずれ魔力を使われ尽くして死んでたんだよ。
350 = "今だから言うけど、あのまま指輪をつけてたら、\\nいずれ魔力を使われ尽くして死んでたんだよ。"

# めぐみん
# ええ！？　そうだったんですか？
284 = "ええ！？　そうだったんですか？"

# カズマ
# そういうのがあったら困るだろ？\nだから念のために確認をな。
291 = "そういうのがあったら困るだろ？\\nだから念のために確認をな。"

# めぐみん
# もう、なんなんですかカズマは！
333 = "もう、なんなんですかカズマは！"

# カズマ
# はあ？　なぜこのタイミングで怒る。
322 = "はあ？　なぜこのタイミングで怒る。"

# めぐみん
# どこまでバカなんですか！\n怒って当然でしょう！
314 = "どこまでバカなんですか！\\n怒って当然でしょう！"

# めぐみん
# 命の危機にあったのに、それを言わないとか、\n信じられません！
358 = "命の危機にあったのに、それを言わないとか、\\n信じられません！"

# カズマ
# いやだってみんなを心配させてもあれだし。
278 = "いやだってみんなを心配させてもあれだし。"

# めぐみん
# 私たちは仲間ですよ？\n仲間とは、命を賭けてでも守るものなのです。
408 = "私たちは仲間ですよ？\\n仲間とは、命を賭けてでも守るものなのです。"

# カズマ
# めぐみん……。
330 = "めぐみん……。"

# めぐみん
# カズマ、これからは何かあったら、\nちゃんと言ってくださいね。
343 = "カズマ、これからは何かあったら、\\nちゃんと言ってくださいね。"

# めぐみん
# 私たちは仲間。\n仲間とは命を賭する価値のあるものなのですから。
407 = "私たちは仲間。\\n仲間とは命を賭する価値のあるものなのですから。"

# カズマ
# 何が言いたいのかな？
352 = "何が言いたいのかな？"

# めぐみん
# 私を守ってくださいね。
409 = "私を守ってくださいね。"

# カズマ（Ｍ）
# display as カズマ
# （こいつ……）
420 = "（こいつ……）"

# めぐみん
# というわけで、\nこの呪いから解放される方法を考えてください。
311 = "というわけで、\\nこの呪いから解放される方法を考えてください。"

# カズマ
# 考えるも何も、結婚式を挙げるしかないだろ。
412 = "考えるも何も、結婚式を挙げるしかないだろ。"

# めぐみん
# ちょ、ちょっと待ってください！\n呪いの言いなりになれというのですか！？
307 = "ちょ、ちょっと待ってください！\\n呪いの言いなりになれというのですか！？"

# カズマ
# そんなこと言って、もしこのまま\n一生脱げなかったらどうするんだよ？
304 = "そんなこと言って、もしこのまま\\n一生脱げなかったらどうするんだよ？"

# めぐみん
# アクアがきっとなんとかしてくれますよ。\nですから呪いには屈しませんっ！
340 = "アクアがきっとなんとかしてくれますよ。\\nですから呪いには屈しませんっ！"

# カズマ
# なあ、そんなに結婚が嫌なのか？\nフリだぞ、フリ。
316 = "なあ、そんなに結婚が嫌なのか？\\nフリだぞ、フリ。"

# めぐみん
# 嫌と言ったら嫌です！
360 = "嫌と言ったら嫌です！"

# カズマ
# なんでそんな頑ななんだよ。\nそこまで俺のことが嫌いなのか！
321 = "なんでそんな頑ななんだよ。\\nそこまで俺のことが嫌いなのか！"

# めぐみん
# で、ですから、そういうわけではなくて……。
309 = "で、ですから、そういうわけではなくて……。"

# カズマ
# じゃあ、どういうことなんだよ？
286 = "じゃあ、どういうことなんだよ？"

# めぐみん
# …………。
# 271 = "…………。"

# めぐみん
# 結婚式というのは、女性にとって\n一生に一度の……特別なものなのです。
410 = "結婚式というのは、女性にとって\\n一生に一度の……特別なものなのです。"

# めぐみん
# フリとはいえ、カズマのように\n単純に考えられるものではないのですよ。
347 = "フリとはいえ、カズマのように\\n単純に考えられるものではないのですよ。"

# カズマ
# まあ、その気持ちはわからなくもないけどさ、\nここは折れた方がいいって。
327 = "まあ、その気持ちはわからなくもないけどさ、\\nここは折れた方がいいって。"

# カズマ
# その格好で過ごしてたら、\n一生に一度もなにもなくなるぜ？
294 = "その格好で過ごしてたら、\\n一生に一度もなにもなくなるぜ？"

# カズマ
# つかさ、こんな強硬手段までとってきたんだ。\nなにがなんでも式を挙げさせたいんだろう。
308 = "つかさ、こんな強硬手段までとってきたんだ。\\nなにがなんでも式を挙げさせたいんだろう。"

# カズマ
# それだけ強い思いが\nこの呪いには込められている。\nもし、このまま拒み続けたら――
295 = "それだけ強い思いが\\nこの呪いには込められている。\\nもし、このまま拒み続けたら――"

# めぐみん
# ……どうなるというのですか？
272 = "……どうなるというのですか？"

# カズマ
# あまり考えたくはないが、\n最悪、命に関わってくるかもしれない。
275 = "あまり考えたくはないが、\\n最悪、命に関わってくるかもしれない。"

# めぐみん
# 命に……ですか？
357 = "命に……ですか？"

# カズマ
# あくまでも最悪の場合だけどさ、\nないとは言い切れないぜ？
274 = "あくまでも最悪の場合だけどさ、\\nないとは言い切れないぜ？"

# カズマ
# それに、アクア達が助けに来るまで\n呪いが待ってくれる保証もない。
297 = "それに、アクア達が助けに来るまで\\n呪いが待ってくれる保証もない。"

# めぐみん
# そ、それは……。
290 = "そ、それは……。"

# カズマ
# めぐみんの複雑な乙女心はよーくわかった。\nできれば尊重してやりたい。
331 = "めぐみんの複雑な乙女心はよーくわかった。\\nできれば尊重してやりたい。"

# カズマ
# だけど、それを必死に守って死ぬのは頂けない。\n俺はそう思う。
306 = "だけど、それを必死に守って死ぬのは頂けない。\\n俺はそう思う。"

# めぐみん
# …………。
# 271 = "…………。"

# カズマ
# それにお前は俺に守れって言ったよな。\nだったら、その体を縛ってでも挙式をする。
298 = "それにお前は俺に守れって言ったよな。\\nだったら、その体を縛ってでも挙式をする。"

# カズマ
# それでお前が傷つこうが知ったこっちゃない。\nこの世に命よりも大切な物なんてないんだからな。
296 = "それでお前が傷つこうが知ったこっちゃない。\\nこの世に命よりも大切な物なんてないんだからな。"

# めぐみん
# なんですか……カズマのくせに、生意気ですよ。
319 = "なんですか……カズマのくせに、生意気ですよ。"

# カズマ
# めぐみん？
332 = "めぐみん？"

# めぐみん
# わかりました、わかりましたよ。\nけ、結婚式をします。
339 = "わかりました、わかりましたよ。\\nけ、結婚式をします。"

# カズマ
# わかってくれたか！
338 = "わかってくれたか！"

# めぐみん
# 確かに、ここで意地を張って命を落とすのは\n頂けないと、私も思いますから。
405 = "確かに、ここで意地を張って命を落とすのは\\n頂けないと、私も思いますから。"

# めぐみん
# でも、あくまでもフリですからね！？\nそこのところ勘違いをしないでください！
310 = "でも、あくまでもフリですからね！？\\nそこのところ勘違いをしないでください！"

# カズマ
# そんなに念を押さなくてもわかってるって。
305 = "そんなに念を押さなくてもわかってるって。"

# めぐみん
# わ、わかっているのなら……いいんです。\nそれから、このことは２人だけの\n秘密にしてください。
337 = "わ、わかっているのなら……いいんです。\\nそれから、このことは２人だけの\\n秘密にしてください。"

# めぐみん
# 間違っても\nアクア達には話さないでくださいよ？\n絶対にからかわれます。
414 = "間違っても\\nアクア達には話さないでくださいよ？\\n絶対にからかわれます。"

# カズマ
# ああ、その光景が目に浮かぶな。\n俺だって無駄に冷やかされたくはないし、\n２人だけの秘密だ。
273 = "ああ、その光景が目に浮かぶな。\\n俺だって無駄に冷やかされたくはないし、\\n２人だけの秘密だ。"

# めぐみん
# なら、いいです。\nこうなった以上、さっさと終わらせて\nここから出ましょう！
317 = "なら、いいです。\\nこうなった以上、さっさと終わらせて\\nここから出ましょう！"

# カズマ
# よし、それじゃ早速、結婚するか！
336 = "よし、それじゃ早速、結婚するか！"

# めぐみん
# そ、その言い方は止めてくださいっ！
289 = "そ、その言い方は止めてくださいっ！"

