# root_f18.txt.scn

[info]
0 = ""

[characters]
289 = "カズマ"
288 = "ウィズ"
292 = "カズマ（Ｍ）"

[character_subs]
# 289 = "カズマ"

[script]
# lines: 59

# カズマ
# 昼間の話だと、ここら辺にも\nけっこう現れるってことだったよな？
296 = "昼間の話だと、ここら辺にも\\nけっこう現れるってことだったよな？"

# ウィズ
# ええ、ですが霊の気配を感じられませんね。
249 = "ええ、ですが霊の気配を感じられませんね。"

# カズマ
# もしかして、アクアが除霊をしたのか？
287 = "もしかして、アクアが除霊をしたのか？"

# ウィズ
# そこまではちょっと。
263 = "そこまではちょっと。"

# カズマ（Ｍ）
# display as カズマ
# （アクアが除霊するとしたら、\n　暴れた跡の１つでもありそうな気もするが）
325 = "（アクアが除霊するとしたら、\\n　暴れた跡の１つでもありそうな気もするが）"

# ウィズ
# まあ、ここは、人の住む所ですし、\n今はいなくても\n人恋しさに寄ってくる可能性もありますから――
285 = "まあ、ここは、人の住む所ですし、\\n今はいなくても\\n人恋しさに寄ってくる可能性もありますから――"

# ウィズ
# カズマさん、道端に\n聖水を撒いておいてもらえますか？
291 = "カズマさん、道端に\\n聖水を撒いておいてもらえますか？"

# カズマ
# ああ、わかった。
239 = "ああ、わかった。"

# カズマ
# ふう！\nこのくらい撒いとけば大丈夫かな。
284 = "ふう！\\nこのくらい撒いとけば大丈夫かな。"

# ウィズ
# そうですね、ひとまずは安心だと思います。
262 = "そうですね、ひとまずは安心だと思います。"

# カズマ
# なあ、ウィズ。\n聖水をまきながらふと思ったんだけど。
277 = "なあ、ウィズ。\\n聖水をまきながらふと思ったんだけど。"

# ウィズ
# はい、なんでしょうか？
282 = "はい、なんでしょうか？"

# カズマ
# この聖水、どう調達したんだ？\nまさかウィズが作った……\nわけないよな、アンデッドだし。
254 = "この聖水、どう調達したんだ？\\nまさかウィズが作った……\\nわけないよな、アンデッドだし。"

# ウィズ
# はい、さすがに作れませんから\nエリス教のプリーストさんにお願いして\n生成してもらいました。
281 = "はい、さすがに作れませんから\\nエリス教のプリーストさんにお願いして\\n生成してもらいました。"

# カズマ
# となると、当然、タダじゃないよな？
274 = "となると、当然、タダじゃないよな？"

# ウィズ
# １瓶１０００エリスです。\nお店で買うと倍くらいはしますから、\n助かりました。
327 = "１瓶１０００エリスです。\\nお店で買うと倍くらいはしますから、\\n助かりました。"

# カズマ
# そっか。\nウィズにしては珍しくお得な方を\n選んだんだな。
265 = "そっか。\\nウィズにしては珍しくお得な方を\\n選んだんだな。"

# カズマ
# って、いや待てぇ！\nこのバッグに結構な数が入ってたぞ？
269 = "って、いや待てぇ！\\nこのバッグに結構な数が入ってたぞ？"

# ウィズ
# え？　ええ。\n買った分、すべて持ってきましたので。
251 = "え？　ええ。\\n買った分、すべて持ってきましたので。"

# カズマ
# 今まで惜しげなく使ってたけど……\n全部、ウィズの自腹だったのか？
293 = "今まで惜しげなく使ってたけど……\\n全部、ウィズの自腹だったのか？"

# ウィズ
# ええ、そうですね。\nでも仕方ありません。
248 = "ええ、そうですね。\\nでも仕方ありません。"

# カズマ（Ｍ）
# display as カズマ
# （おいおいおいっ！！\n　自分で買った物をタダでばら撒いてるのか！\n　お人好しにも程ってものが……）
323 = "（おいおいおいっ！！\\n　自分で買った物をタダでばら撒いてるのか！\\n　お人好しにも程ってものが……）"

# ウィズ
# か、カズマさん！？\nいきなり崩れ落ちてどうしたんですか？
253 = "か、カズマさん！？\\nいきなり崩れ落ちてどうしたんですか？"

# カズマ
# そんなことしてるから金が貯まらないんだよ！
268 = "そんなことしてるから金が貯まらないんだよ！"

# ウィズ
# で、でも皆さん困ってますし。
271 = "で、でも皆さん困ってますし。"

# カズマ
# そういうことしてるウィズだって、\n結局赤字で困ってるだろ！？
260 = "そういうことしてるウィズだって、\\n結局赤字で困ってるだろ！？"

# ウィズ
# ご、ごめんなさいっ！
255 = "ご、ごめんなさいっ！"

# カズマ
# すまん、ちょっと説教させてくれ。
257 = "すまん、ちょっと説教させてくれ。"

# ウィズ
# え？　ええ？\nお説教ですか？
252 = "え？　ええ？\\nお説教ですか？"

# カズマ
# ずーっと思ってたがな、ウィズはお人好し過ぎる。\n疑うことを知ら無さ過ぎる！
258 = "ずーっと思ってたがな、ウィズはお人好し過ぎる。\\n疑うことを知ら無さ過ぎる！"

# ウィズ
# は、はあ……。
279 = "は、はあ……。"

# カズマ
# いい機会だから、はっきり言わせてもらう！\nお人好しも過ぎれば身を滅ぼすんだぞ！
244 = "いい機会だから、はっきり言わせてもらう！\\nお人好しも過ぎれば身を滅ぼすんだぞ！"

# ウィズ
# あの、私はリッチーなので、\n身が滅ぶことも、体が朽ちることも……。
240 = "あの、私はリッチーなので、\\n身が滅ぶことも、体が朽ちることも……。"

# カズマ
# そういうお約束はいらん！
259 = "そういうお約束はいらん！"

# ウィズ
# うぅ、すみません。
247 = "うぅ、すみません。"

# カズマ（Ｍ）
# display as カズマ
# （ウィズらしいが、でも……）
326 = "（ウィズらしいが、でも……）"

# カズマ
# あのさ、ウィズ。\nさすがに全部、自腹なのはどうかと思うぞ？
241 = "あのさ、ウィズ。\\nさすがに全部、自腹なのはどうかと思うぞ？"

# ウィズ
# でもこれが、私の役割です。
273 = "でもこれが、私の役割です。"

# カズマ
# いやさぁ、役割だからって\n無理してやるのはおかしいだろ！？
246 = "いやさぁ、役割だからって\\n無理してやるのはおかしいだろ！？"

# ウィズ
# そうでしょうか……。
261 = "そうでしょうか……。"

# カズマ
# ともかくだな？\n俺の言いたいことは２つだ。
276 = "ともかくだな？\\n俺の言いたいことは２つだ。"

# カズマ
# まず、ウィズはお人好し過ぎる。\nこれはもう何度も言ってるよな？
286 = "まず、ウィズはお人好し過ぎる。\\nこれはもう何度も言ってるよな？"

# ウィズ
# は、はい……。
280 = "は、はい……。"

# カズマ
# そして、もう１つ。\nせっかく安く聖水を仕入れられたなら、\n高く売れば商売になるだろう。
264 = "そして、もう１つ。\\nせっかく安く聖水を仕入れられたなら、\\n高く売れば商売になるだろう。"

# ウィズ
# ええ？\nでもそんなことしたら、作って下さった\nプリーストさんに申し訳が……。
250 = "ええ？\\nでもそんなことしたら、作って下さった\\nプリーストさんに申し訳が……。"

# カズマ
# いいんだよ！\nそのプリーストは１０００エリスで\n納得して作ってくれたんだろ？
243 = "いいんだよ！\\nそのプリーストは１０００エリスで\\n納得して作ってくれたんだろ？"

# ウィズ
# あ、はい。
238 = "あ、はい。"

# カズマ
# なら、それはもうそこで終わってる話だ。\n金を払って得た物は、もうウィズの物だ。
278 = "なら、それはもうそこで終わってる話だ。\\n金を払って得た物は、もうウィズの物だ。"

# カズマ
# それを仕入れ値より高く売れば利益になる。\n商売の基本中の基本だぞ。
267 = "それを仕入れ値より高く売れば利益になる。\\n商売の基本中の基本だぞ。"

# ウィズ
# で、でも、皆さん困ってますし……。
270 = "で、でも、皆さん困ってますし……。"

# カズマ
# それもだ！\nそもそも、困っていることを解決するのが\n商売の基本だ！
266 = "それもだ！\\nそもそも、困っていることを解決するのが\\n商売の基本だ！"

# カズマ
# いいか？\nウィズの理屈だと、自分の出来ないことを\n人にしてもらうこと全部が商売にならなくなる！
242 = "いいか？\\nウィズの理屈だと、自分の出来ないことを\\n人にしてもらうこと全部が商売にならなくなる！"

# ウィズ
# ですが、今回の事は急を要しますし、\nここで自分の利益だけに走るのはよくないです。
272 = "ですが、今回の事は急を要しますし、\\nここで自分の利益だけに走るのはよくないです。"

# カズマ（Ｍ）
# display as カズマ
# （だ、ダメだ！\n　話は通じてるのに通じない！\n　これは信念を曲げさせるって次元の話だ……）
324 = "（だ、ダメだ！\\n　話は通じてるのに通じない！\\n　これは信念を曲げさせるって次元の話だ……）"

# ウィズ
# あ、あの、カズマさん？\n頭を抱えてますけど、私、\n困らせてしまっているのでしょうか？
237 = "あ、あの、カズマさん？\\n頭を抱えてますけど、私、\\n困らせてしまっているのでしょうか？"

# カズマ
# いや、いいんだ。\n今さらどうこう言っても始まらないし、\nお人好しだからこそ、ウィズなんだからな。
245 = "いや、いいんだ。\\n今さらどうこう言っても始まらないし、\\nお人好しだからこそ、ウィズなんだからな。"

# ウィズ
# カズマさん……。
290 = "カズマさん……。"

# カズマ
# ともかく、ひとまず除霊を済ませよう。
275 = "ともかく、ひとまず除霊を済ませよう。"

# ウィズ
# はい！
283 = "はい！"

[selections]
# 268 = "そんなことしてるから金が貯まらないんだよ！"
256 = "すまん、ちょっと説教させてくれ"
# 326 = "（ウィズらしいが、でも……）"
