# root_a16.txt.scn

[info]
0 = ""

[characters]
227 = "ダスト"
223 = "カズマ"
222 = "アクア"
225 = "キース"
224 = "カズマ（Ｍ）"

[character_subs]
# 223 = "カズマ"

[script]
# lines: 45

# ダスト
# で？　俺たちに用事ってなんなんだ？
212 = "で？　俺たちに用事ってなんなんだ？"

# カズマ
# ああ、こいつにエリス様っぽい女の子らしさを\n教えてやってほしいんだよ。
194 = "ああ、こいつにエリス様っぽい女の子らしさを\\n教えてやってほしいんだよ。"

# アクア
# 私はそんなことをしても無駄だと\n思うんですけど。
271 = "私はそんなことをしても無駄だと\\n思うんですけど。"

# キース
# 俺もそう思うぞ。\nエリス様がどんな女神かっていうのは\nそれこそ信者の数だけ理想像ってもんがある。
234 = "俺もそう思うぞ。\\nエリス様がどんな女神かっていうのは\\nそれこそ信者の数だけ理想像ってもんがある。"

# カズマ
# だからこそ、２人の意見も訊きたいんだって。
209 = "だからこそ、２人の意見も訊きたいんだって。"

# カズマ
# コンテストを審査するのは所詮、\nエリス様への個人的な強い思い入れを持つ\n人間だからな。
226 = "コンテストを審査するのは所詮、\\nエリス様への個人的な強い思い入れを持つ\\n人間だからな。"

# アクア
# ああ、なるほど。\nだから朝からあっちこっちでエリスのことを\n聞いてまわってるのね、
195 = "ああ、なるほど。\\nだから朝からあっちこっちでエリスのことを\\n聞いてまわってるのね、"

# カズマ
# 今頃気がついたのかよ。
231 = "今頃気がついたのかよ。"

# キース
# うーん、俺が持つエリス様像ね。\nやっぱ、なんでも許してくれる慈悲深さかな。
199 = "うーん、俺が持つエリス様像ね。\\nやっぱ、なんでも許してくれる慈悲深さかな。"

# カズマ
# つまり心優しいと。\nダストは、どうだ？
211 = "つまり心優しいと。\\nダストは、どうだ？"

# ダスト
# 清楚で可愛い！\nこれに限るだろ。
241 = "清楚で可愛い！\\nこれに限るだろ。"

# カズマ
# なんか普通だな。\n期待してたのとちょっと違う。
214 = "なんか普通だな。\\n期待してたのとちょっと違う。"

# キース
# いやいや、お前は俺たちにどんな期待をしてたんだ。
196 = "いやいや、お前は俺たちにどんな期待をしてたんだ。"

# カズマ
# 男ならではの妄想だ。
242 = "男ならではの妄想だ。"

# ダスト
# は？　なんだそれ？
216 = "は？　なんだそれ？"

# カズマ
# お前らならさ、他の敬虔な信者とは違って、\n独自のエリス様像を持っていると思ったんだ。
203 = "お前らならさ、他の敬虔な信者とは違って、\\n独自のエリス様像を持っていると思ったんだ。"

# カズマ
# そういう妄想だけにはたくましそうじゃん。\nあの店のお陰で。
207 = "そういう妄想だけにはたくましそうじゃん。\\nあの店のお陰で。"

# ダスト
# バカ！\nあ、あのことは大声で言うなよ！\n男の冒険者達だけの秘密だって言ったろ！
228 = "バカ！\\nあ、あのことは大声で言うなよ！\\n男の冒険者達だけの秘密だって言ったろ！"

# アクア
# え？　なに、なんの話？
200 = "え？　なに、なんの話？"

# カズマ
# なんでもない、なんでもないぞ！　気にするな！\nそれよりも特訓だろ特訓！\n頼むぜ、キース！　ダスト！
215 = "なんでもない、なんでもないぞ！　気にするな！\\nそれよりも特訓だろ特訓！\\n頼むぜ、キース！　ダスト！"

# キース
# お、おう。\n要は、エリス様の良さについて語ればいいんだな？
201 = "お、おう。\\n要は、エリス様の良さについて語ればいいんだな？"

# ダスト
# まあ、やっぱり\n可憐で清楚なところは外せないよな。\nそれに優しくて慈悲深いんだろ？
217 = "まあ、やっぱり\\n可憐で清楚なところは外せないよな。\\nそれに優しくて慈悲深いんだろ？"

# ダスト
# 信者はもちろん、どんな者にも\n平等に慈愛を注いでくださるとか。
233 = "信者はもちろん、どんな者にも\\n平等に慈愛を注いでくださるとか。"

# キース
# 後は、幸運の女神ってことで、\n俺達みたいな冒険者にとっては\n欠かせない存在だな。
238 = "後は、幸運の女神ってことで、\\n俺達みたいな冒険者にとっては\\n欠かせない存在だな。"

# ダスト
# 総合すると、非の打ち所のない\nまさに完ぺきな女神様だ！
272 = "総合すると、非の打ち所のない\\nまさに完ぺきな女神様だ！"

# カズマ
# だとよ、アクア。
210 = "だとよ、アクア。"

# アクア
# すごく抽象的だし\nカズマの意見と変わんないじゃない。\n参考にならないわよ。
206 = "すごく抽象的だし\\nカズマの意見と変わんないじゃない。\\n参考にならないわよ。"

# アクア
# もっとこう、すぐに実行できる、\n有用な意見ってないのかしら。
220 = "もっとこう、すぐに実行できる、\\n有用な意見ってないのかしら。"

# カズマ（Ｍ）
# display as カズマ
# （こいつはどうして上から目線なんだ……）
273 = "（こいつはどうして上から目線なんだ……）"

# ダスト
# 有用な意見ね。\nじゃあ、口調を直すっていうのはどうだ？
239 = "有用な意見ね。\\nじゃあ、口調を直すっていうのはどうだ？"

# キース
# 今さら性格を直すなんて無理だもんな。\nだったら上辺だけでもなんとか取り繕って\n審査員を騙すしかないだろ。
230 = "今さら性格を直すなんて無理だもんな。\\nだったら上辺だけでもなんとか取り繕って\\n審査員を騙すしかないだろ。"

# アクア
# なんか、気になる言い方ね、それ。
213 = "なんか、気になる言い方ね、それ。"

# カズマ（Ｍ）
# display as カズマ
# （本当だったら、根本的な所から矯正するのが\n　一番なんだけど、もうあんまり時間が無いし）
274 = "（本当だったら、根本的な所から矯正するのが\\n　一番なんだけど、もうあんまり時間が無いし）"

# カズマ
# んじゃ、アクアちょっとやってみてくれ。
221 = "んじゃ、アクアちょっとやってみてくれ。"

# アクア
# うーん、エリスっぽい口調ね。\nええと……。
198 = "うーん、エリスっぽい口調ね。\\nええと……。"

# アクア
# もう帰って寝たいですわ。
219 = "もう帰って寝たいですわ。"

# カズマ
# うん、おかしい、色々おかしい。
197 = "うん、おかしい、色々おかしい。"

# アクア
# 何がよ！
232 = "何がよ！"

# カズマ
# まずエリス様は帰って寝たいなんて\n絶対に言わない。
218 = "まずエリス様は帰って寝たいなんて\\n絶対に言わない。"

# カズマ
# そして俺が知る限り、\nエリス様はですわ口調じゃない。
208 = "そして俺が知る限り、\\nエリス様はですわ口調じゃない。"

# アクア
# じゃ、じゃあ。\nお腹が空きましたので、蛙のからあげを……。
205 = "じゃ、じゃあ。\\nお腹が空きましたので、蛙のからあげを……。"

# カズマ
# お前は真面目にやれよ！
202 = "お前は真面目にやれよ！"

# アクア
# 私はいつでも真剣よ！
270 = "私はいつでも真剣よ！"

# ダスト
# これはなんというか。
204 = "これはなんというか。"

# キース
# 問題が山積みだな。
236 = "問題が山積みだな。"

