# root_f21.txt.scn

[info]
0 = ""

[characters]
248 = "アクア"
251 = "カズマ（Ｍ）"
250 = "カズマ"
249 = "ウィズ"

[character_subs]
# 250 = "カズマ"

[script]
# lines: 47

# アクア
# ふふふ！\nいいことをした後は気持ちがいいわね。
243 = "ふふふ！\\nいいことをした後は気持ちがいいわね。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、アクアが言うとアレだが、\n　確かに達成感というか、充実感はあるな）
279 = "（まあ、アクアが言うとアレだが、\\n　確かに達成感というか、充実感はあるな）"

# カズマ
# それにしても、なんで突然、霊が騒ぎ出したんだ？\n原因がわからないと、また同じ騒ぎが\n起きるんじゃないか？
227 = "それにしても、なんで突然、霊が騒ぎ出したんだ？\\n原因がわからないと、また同じ騒ぎが\\n起きるんじゃないか？"

# ウィズ
# それはですね、多分。
228 = "それはですね、多分。"

# カズマ
# ん？　心当たりがあるのか？
247 = "ん？　心当たりがあるのか？"

# アクア
# さすがアンデッドの王ね。\nけど、わかってるのなら\n最初から匂いの元を断っときなさいよ。
220 = "さすがアンデッドの王ね。\\nけど、わかってるのなら\\n最初から匂いの元を断っときなさいよ。"

# カズマ
# お前はいちいち突っかかんなよ！\nで、何が原因だったんだ、ウィズ？
218 = "お前はいちいち突っかかんなよ！\\nで、何が原因だったんだ、ウィズ？"

# ウィズ
# その、大変言いにくいのですが……\nアクア様の影響かと。
225 = "その、大変言いにくいのですが……\\nアクア様の影響かと。"

# アクア
# なっ！？
237 = "なっ！？"

# カズマ
# おいお前、今度は何をやらかした。
213 = "おいお前、今度は何をやらかした。"

# アクア
# な、何もやってないわよ！\nたぶん……。
236 = "な、何もやってないわよ！\\nたぶん……。"

# カズマ（Ｍ）
# display as カズマ
# （たぶんって……）
278 = "（たぶんって……）"

# ウィズ
# あ、あの、前に洞窟調査をしたときにも\n似たようなことがありましたよね？
209 = "あ、あの、前に洞窟調査をしたときにも\\n似たようなことがありましたよね？"

# カズマ
# なるほど、アンデッドと同じで\n霊もこいつの神気に引き寄せられたってわけか。
239 = "なるほど、アンデッドと同じで\\n霊もこいつの神気に引き寄せられたってわけか。"

# ウィズ
# 正しくは、活発になった、ですね。
257 = "正しくは、活発になった、ですね。"

# カズマ
# おい、アクア？
212 = "おい、アクア？"

# アクア
# は、はい。
240 = "は、はい。"

# カズマ
# お前、この前めずらしく残業してたよな？
216 = "お前、この前めずらしく残業してたよな？"

# アクア
# はい、コロッケの下準備を頼まれまして。
242 = "はい、コロッケの下準備を頼まれまして。"

# カズマ
# おお、下準備を頼まれるところまで来たのか。\n頑張ったじゃないかアクア。
214 = "おお、下準備を頼まれるところまで来たのか。\\n頑張ったじゃないかアクア。"

# アクア
# そうなのよ！\nしかもね、時給をちょっと上げてくれたの！
224 = "そうなのよ！\\nしかもね、時給をちょっと上げてくれたの！"

# カズマ
# さらに、お土産まで貰って\n陽気になったこいつの神気にあてられて\n霊の活動が活発になったわけか。
222 = "さらに、お土産まで貰って\\n陽気になったこいつの神気にあてられて\\n霊の活動が活発になったわけか。"

# ウィズ
# おそらくですが。
215 = "おそらくですが。"

# カズマ
# つまり全部お前のせいじゃねえか！！
233 = "つまり全部お前のせいじゃねえか！！"

# アクア
# ちょっと待ってよ。\n私だって、今初めて知ったんですけど！
232 = "ちょっと待ってよ。\\n私だって、今初めて知ったんですけど！"

# カズマ
# ん？　おいちょっと待て。\nお前は自分自身が今回の騒動の原因だと\n知らなかったのか？
246 = "ん？　おいちょっと待て。\\nお前は自分自身が今回の騒動の原因だと\\n知らなかったのか？"

# アクア
# さっきからそう言ってるじゃない。
221 = "さっきからそう言ってるじゃない。"

# カズマ
# ならなんでお前は\nわざわざ除霊なんて面倒な事をして\n回ってたんだ？
238 = "ならなんでお前は\\nわざわざ除霊なんて面倒な事をして\\n回ってたんだ？"

# アクア
# ぎくっ！
219 = "ぎくっ！"

# カズマ
# １００歩譲って、霊の活性化の原因が自分だと\nわかっていたのなら、\nお前でも率先して除霊をすると納得はできる。
280 = "１００歩譲って、霊の活性化の原因が自分だと\\nわかっていたのなら、\\nお前でも率先して除霊をすると納得はできる。"

# カズマ
# だが、お前は今、この事実を知ったばかりだ。
231 = "だが、お前は今、この事実を知ったばかりだ。"

# カズマ
# お前の性格からして、\nなんの得もなく除霊なんて面倒な作業をするとは\n思えない。
217 = "お前の性格からして、\\nなんの得もなく除霊なんて面倒な作業をするとは\\n思えない。"

# アクア
# わ、私は女神よ。\nさまよえる霊を天に導くのに\n理由なんていらないじゃない。
245 = "わ、私は女神よ。\\nさまよえる霊を天に導くのに\\n理由なんていらないじゃない。"

# カズマ
# では聞こう。\nなんで川べりの除霊をしなかった？
235 = "では聞こう。\\nなんで川べりの除霊をしなかった？"

# アクア
# そ、そ、それは……。
223 = "そ、そ、それは……。"

# カズマ
# 吐け。
254 = "吐け。"

# アクア
# え、ええと……。
211 = "え、ええと……。"

# カズマ
# 吐け。
# 254 = "吐け。"

# アクア
# 昨夜、絡んできた霊を除霊したんですよ。
256 = "昨夜、絡んできた霊を除霊したんですよ。"

# カズマ
# うん、それで？
210 = "うん、それで？"

# アクア
# それを見ていた人がですね。\nお嬢ちゃん偉いねってお小遣いをくれまして……。
229 = "それを見ていた人がですね。\\nお嬢ちゃん偉いねってお小遣いをくれまして……。"

# カズマ
# ふむふむ、それで？
244 = "ふむふむ、それで？"

# アクア
# で、ですから、どうしても\n人がいるところを中心に\n除霊をすることになりまして。
234 = "で、ですから、どうしても\\n人がいるところを中心に\\n除霊をすることになりまして。"

# カズマ
# それだけか？
226 = "それだけか？"

# アクア
# あ、あとは、これだけ頑張れば、\nギルドから特別報酬が出るかなーって\n下心も少しだけ。
208 = "あ、あとは、これだけ頑張れば、\\nギルドから特別報酬が出るかなーって\\n下心も少しだけ。"

# カズマ
# だから真っ先にギルドの除霊に行ったのか！
230 = "だから真っ先にギルドの除霊に行ったのか！"

# アクア
# はい、その通りです……。
241 = "はい、その通りです……。"

