# root_a17.txt.scn

[info]
0 = ""

[characters]
306 = "カズマ"
303 = "ウィズ"
302 = "アクア"

[character_subs]

[script]
# lines: 69

# カズマ
# おーい、ウィズ。\nいるかー？
262 = "おーい、ウィズ。\\nいるかー？"

# ウィズ
# あら、カズマさん、アクア様。\nいらっしゃいませ。
248 = "あら、カズマさん、アクア様。\\nいらっしゃいませ。"

# カズマ
# ごめんな、いきなり押しかけて。
267 = "ごめんな、いきなり押しかけて。"

# ウィズ
# いえいえ、構いませんよ？
250 = "いえいえ、構いませんよ？"

# アクア
# ちょっとカズマ？\nどうしてアンデッドの店に来たのかしら？
284 = "ちょっとカズマ？\\nどうしてアンデッドの店に来たのかしら？"

# カズマ
# もちろんお前の特訓するためだが？
297 = "もちろんお前の特訓するためだが？"

# アクア
# は？
290 = "は？"

# ウィズ
# 特訓……ですか？
319 = "特訓……ですか？"

# カズマ
# ちょっと色々あってさ、\nこいつがまた借金を増やしちまったんだよ。
286 = "ちょっと色々あってさ、\\nこいつがまた借金を増やしちまったんだよ。"

# ウィズ
# そうなんですか。
272 = "そうなんですか。"

# カズマ
# そこで借金返済のために、\n今度開催されるエリス様コンテストってやつに\n出ようと思ってるんだよ。
273 = "そこで借金返済のために、\\n今度開催されるエリス様コンテストってやつに\\n出ようと思ってるんだよ。"

# ウィズ
# ああ、あれですか。\n確か優勝賞金は５００万エリスでしたよね？
245 = "ああ、あれですか。\\n確か優勝賞金は５００万エリスでしたよね？"

# カズマ
# もしかしてウィズも出るのか？
296 = "もしかしてウィズも出るのか？"

# ウィズ
# とんでもありません。\nうちの店にもチラシを置いていたので、\n知っていただけです。
287 = "とんでもありません。\\nうちの店にもチラシを置いていたので、\\n知っていただけです。"

# カズマ
# それならよかったよ。\nウィズが相手じゃ絶対に勝ち目ないし。
277 = "それならよかったよ。\\nウィズが相手じゃ絶対に勝ち目ないし。"

# アクア
# ちょっと今の聞き捨てならないんですけど。
285 = "ちょっと今の聞き捨てならないんですけど。"

# アクア
# まさか女神である私が、\nリッチーに負けるって言うわけ？
294 = "まさか女神である私が、\\nリッチーに負けるって言うわけ？"

# カズマ
# うん、そうだけど？
257 = "うん、そうだけど？"

# アクア
# なんでよ！
288 = "なんでよ！"

# カズマ
# 客観的に見た平等な評価だ。
315 = "客観的に見た平等な評価だ。"

# アクア
# へえ、じゃあその客観的に見た\n平等な評価というのを聞かせて貰いましょうか。
291 = "へえ、じゃあその客観的に見た\\n平等な評価というのを聞かせて貰いましょうか。"

# カズマ
# まず第一に、俺が知る限り、\nエリス様の性格に最も近いのはウィズだ。
295 = "まず第一に、俺が知る限り、\\nエリス様の性格に最も近いのはウィズだ。"

# アクア
# 確かに、それはちょっとだけ納得できるわね。
352 = "確かに、それはちょっとだけ納得できるわね。"

# カズマ
# そして、第二に、\n現在の世間の評価。
274 = "そして、第二に、\\n現在の世間の評価。"

# カズマ
# ウィズは先のスカルドラゴン戦で、\nこの街の人たちの評価を爆上げした。
305 = "ウィズは先のスカルドラゴン戦で、\\nこの街の人たちの評価を爆上げした。"

# アクア
# それは私の活躍があったからで！
280 = "それは私の活躍があったからで！"

# カズマ
# それは俺もわかってる。\nだが世間の見方は違うだろ。
279 = "それは俺もわかってる。\\nだが世間の見方は違うだろ。"

# アクア
# う、うん。
253 = "う、うん。"

# カズマ
# いいか、世間の声はこうだ。
249 = "いいか、世間の声はこうだ。"

# カズマ
# さすが元凄腕アークウィザードの貧乏店主さんだ。\nまた俺たちの街を救ってくれたぜ。
268 = "さすが元凄腕アークウィザードの貧乏店主さんだ。\\nまた俺たちの街を救ってくれたぜ。"

# カズマ
# そんな抜群のインパクトに日頃の行いが相まって\n現在の評価になってるってわけだ。
281 = "そんな抜群のインパクトに日頃の行いが相まって\\n現在の評価になってるってわけだ。"

# アクア
# うぅ、それでも私がリッチーに負けるなんて。
254 = "うぅ、それでも私がリッチーに負けるなんて。"

# カズマ
# 審査員はウィズの淑やかさや滲み出る人格って\nやつを評価するだろう。
316 = "審査員はウィズの淑やかさや滲み出る人格って\\nやつを評価するだろう。"

# カズマ
# そして観客は、ウィズの登場に歓声を上げて\n後押しをする。
275 = "そして観客は、ウィズの登場に歓声を上げて\\n後押しをする。"

# カズマ
# そんな空気の中でも、\nお前が勝てるって思う要素があるなら言ってみろ！
282 = "そんな空気の中でも、\\nお前が勝てるって思う要素があるなら言ってみろ！"

# アクア
# う、うう、私女神だし……。
252 = "う、うう、私女神だし……。"

# ウィズ
# そ、そうですよ。
271 = "そ、そうですよ。"

# ウィズ
# 女神のアクア様にしか出せない、\nこう、なんていいますか、ええと、\n女神っぽい何かというものもありますし。
313 = "女神のアクア様にしか出せない、\\nこう、なんていいますか、ええと、\\n女神っぽい何かというものもありますし。"

# カズマ
# じゃあ、エリス様のコンテストに出たアクアに\nウィズは投票するのか？
270 = "じゃあ、エリス様のコンテストに出たアクアに\\nウィズは投票するのか？"

# ウィズ
# それは、します……よ。
278 = "それは、します……よ。"

# カズマ
# はい、これが世間の素直な反応。
289 = "はい、これが世間の素直な反応。"

# カズマ
# お前を怖がってるウィズでさえ、\n返事に躊躇するんだ。
263 = "お前を怖がってるウィズでさえ、\\n返事に躊躇するんだ。"

# カズマ
# それなのに、お前を女神と知らない世間の人間が\nアクアに投票するわけないだろ。
276 = "それなのに、お前を女神と知らない世間の人間が\\nアクアに投票するわけないだろ。"

# アクア
# う、うう、ううう。\nじゃあ、私、どうすればいいのよ。
251 = "う、うう、ううう。\\nじゃあ、私、どうすればいいのよ。"

# カズマ
# ウィズに礼儀とか作法を習う。
304 = "ウィズに礼儀とか作法を習う。"

# アクア
# 私がリッチーに教えを請うなんて！
353 = "私がリッチーに教えを請うなんて！"

# カズマ
# 嫌なのか？\nだったら借金は地道に働いて返せ！
314 = "嫌なのか？\\nだったら借金は地道に働いて返せ！"

# カズマ
# まあ、トイチだからな。\n気がついたら云千万って額になってるだろうけど！
293 = "まあ、トイチだからな。\\n気がついたら云千万って額になってるだろうけど！"

# アクア
# わ、わかったわよ。
299 = "わ、わかったわよ。"

# カズマ
# じゃあ、ウィズ、よろしく頼むな。
269 = "じゃあ、ウィズ、よろしく頼むな。"

# ウィズ
# わ、わかりました。\nそれでは、まず。
300 = "わ、わかりました。\\nそれでは、まず。"

# アクア
# うん、まず？
258 = "うん、まず？"

# ウィズ
# え、ええと、立ち方から……。
259 = "え、ええと、立ち方から……。"

# アクア
# へえ、立ち方。
292 = "へえ、立ち方。"

# ウィズ
# あの、すみません、アクア様。\nなんか肌がチリチリするので、そのプレッシャーは\nやめていただけると。
247 = "あの、すみません、アクア様。\\nなんか肌がチリチリするので、そのプレッシャーは\\nやめていただけると。"

# アクア
# うふ。\nプレッシャー？　なんのことかしら？
256 = "うふ。\\nプレッシャー？　なんのことかしら？"

# ウィズ
# あ、ああ、それ以上近づかれると、\n私、私、体が焼けて！
244 = "あ、ああ、それ以上近づかれると、\\n私、私、体が焼けて！"

# カズマ
# おい、やめろ。
261 = "おい、やめろ。"

# アクア
# きゃぅ！　痛い～～～～……。
265 = "きゃぅ！　痛い～～～～……。"

# ウィズ
# うう、カズマさん。\nやはり私には荷が重すぎます。
255 = "うう、カズマさん。\\nやはり私には荷が重すぎます。"

# カズマ
# 大丈夫大丈夫。\n何かったら俺がこいつを止めるからさ。
312 = "大丈夫大丈夫。\\n何かったら俺がこいつを止めるからさ。"

# カズマ
# だから、ウィズ、この通りだ！\nこいつに色々教えてやってくれ！
283 = "だから、ウィズ、この通りだ！\\nこいつに色々教えてやってくれ！"

# ウィズ
# わかりました。\nカズマさんがそこまで仰るのでしたら、\nでも……。
301 = "わかりました。\\nカズマさんがそこまで仰るのでしたら、\\nでも……。"

# カズマ
# ああ、わかってるよ。\nアクアが何かやろうとしたら――
246 = "ああ、わかってるよ。\\nアクアが何かやろうとしたら――"

# アクア
# セイクリッド……。
307 = "セイクリッド……。"

# カズマ
# やめろ。
298 = "やめろ。"

# アクア
# きゃい！！
264 = "きゃい！！"

# カズマ
# こうやってちゃんと止めるからさ。
266 = "こうやってちゃんと止めるからさ。"

# ウィズ
# お、お願いしますね？
260 = "お、お願いしますね？"

