# root_d05.txt.scn

[info]
0 = ""

[characters]
152 = "カズマ"
153 = "カズマ（Ｍ）"
151 = "めぐみん"

[character_subs]
# 152 = "カズマ"
178 = "？？？"

[script]
# lines: 29

# カズマ
# はあっ、はあっ、はあっ……。
149 = "はあっ、はあっ、はあっ……。"

# カズマ（Ｍ）
# display as カズマ
# （ようやく追いついた！\n　さすが盗賊だけあって足が速いな。\n　見失うかと思ったぜ）
177 = "（ようやく追いついた！\\n　さすが盗賊だけあって足が速いな。\\n　見失うかと思ったぜ）"

# カズマ（Ｍ）
# display as カズマ
# （それにしても、こんな所で何やってんだ？\n　街の外に出てどこへ行くのかと思えば\n　草の上に寝転んでぼんやりしてるだけだし……）
174 = "（それにしても、こんな所で何やってんだ？\\n　街の外に出てどこへ行くのかと思えば\\n　草の上に寝転んでぼんやりしてるだけだし……）"

# めぐみん
# display as ？？？
# ふっふっふ。\nよくぞここまで来ました、カズマ。\nさすが我が心の輩、全てお見通しという訳ですか。
150 = "ふっふっふ。\\nよくぞここまで来ました、カズマ。\\nさすが我が心の輩、全てお見通しという訳ですか。"

# カズマ
# この声は……！
141 = "この声は……！"

# カズマ
# って、そんなとこに転がって\n何やってんだよ、めぐみん。
145 = "って、そんなとこに転がって\\n何やってんだよ、めぐみん。"

# めぐみん
# 見てわかりませんか？\n我が必殺の爆裂魔法をより至高のものへと\n昇華すべく、技に磨きをかけていたのです。
168 = "見てわかりませんか？\\n我が必殺の爆裂魔法をより至高のものへと\\n昇華すべく、技に磨きをかけていたのです。"

# めぐみん
# 圧倒的なる力の前に、\n何人たりとも立ちはだかることあたわず。\nそれ即ち、この世の真理と知るべきなり！
157 = "圧倒的なる力の前に、\\n何人たりとも立ちはだかることあたわず。\\nそれ即ち、この世の真理と知るべきなり！"

# カズマ（Ｍ）
# display as カズマ
# （……つまり、爆裂魔法を\n　撃ちに来たはいいが力尽きて倒れたのか）
171 = "（……つまり、爆裂魔法を\\n　撃ちに来たはいいが力尽きて倒れたのか）"

# カズマ
# お前なぁ、こうなることはわかってるくせに\nどうして１人で来たんだよ。
139 = "お前なぁ、こうなることはわかってるくせに\\nどうして１人で来たんだよ。"

# めぐみん
# だ、だって……体が疼いて\nどうしようもなくて……\n我慢できなかったんです……。
142 = "だ、だって……体が疼いて\\nどうしようもなくて……\\n我慢できなかったんです……。"

# めぐみん
# 爆裂魔法を撃つ、あの瞬間の快感！\nそれを想うとこの身に滾る欲望には抗えず！
161 = "爆裂魔法を撃つ、あの瞬間の快感！\\nそれを想うとこの身に滾る欲望には抗えず！"

# カズマ（Ｍ）
# display as カズマ
# （それで行き倒れてりゃ世話ないな……）
173 = "（それで行き倒れてりゃ世話ないな……）"

# めぐみん
# というわけでカズマ、\n私の爆裂魔法の練習に付き合ってくれませんか？
147 = "というわけでカズマ、\\n私の爆裂魔法の練習に付き合ってくれませんか？"

# めぐみん
# なに、話は簡単です。\n私を屋敷までおんぶしていってくれたら\nいいだけの話ですから。
148 = "なに、話は簡単です。\\n私を屋敷までおんぶしていってくれたら\\nいいだけの話ですから。"

# カズマ
# あー、すまん。\n今ちょっと取り込み中なんだ。\nまた後でな。
137 = "あー、すまん。\\n今ちょっと取り込み中なんだ。\\nまた後でな。"

# めぐみん
# ちょ、ちょっと待ってください！\n私をこの場へ放置していくつもりですか！？
144 = "ちょ、ちょっと待ってください！\\n私をこの場へ放置していくつもりですか！？"

# カズマ
# 大丈夫だろ、この辺りはモンスターも出ないし。\nそれに今はクリスを追いかけてる最中だから\n無理なんだ。
158 = "大丈夫だろ、この辺りはモンスターも出ないし。\\nそれに今はクリスを追いかけてる最中だから\\n無理なんだ。"

# めぐみん
# 追いかけてるって……ストーキングですか？\nか弱い少女の頼みを断ってまでなんて、\n変態行為に拍車がかかってきましたね。
169 = "追いかけてるって……ストーキングですか？\\nか弱い少女の頼みを断ってまでなんて、\\n変態行為に拍車がかかってきましたね。"

# カズマ
# 違う！　これには事情があるんだよ！\nそんなゴミを見るような目で見るんじゃないっ！！
170 = "違う！　これには事情があるんだよ！\\nそんなゴミを見るような目で見るんじゃないっ！！"

# めぐみん
# ストーキングでないのなら、なんなのです？\nクリスを捕まえて、どうするつもりなのですか。
154 = "ストーキングでないのなら、なんなのです？\\nクリスを捕まえて、どうするつもりなのですか。"

# カズマ
# だから、俺がクリスを追いかけているのは\n自分のためじゃなく、あいつの嗜好を調べる\nためであって……。
143 = "だから、俺がクリスを追いかけているのは\\n自分のためじゃなく、あいつの嗜好を調べる\\nためであって……。"

# めぐみん
# 思考？\n相手の思考を知りたいだなんて、\n相当歪んでますね。
160 = "思考？\\n相手の思考を知りたいだなんて、\\n相当歪んでますね。"

# めぐみん
# こちらの想像以上です。\nさすがですね、カズマ。
140 = "こちらの想像以上です。\\nさすがですね、カズマ。"

# カズマ（Ｍ）
# display as カズマ
# （ああ言えばこう言う……\n　どうあっても俺を変態にしたいようだな）
172 = "（ああ言えばこう言う……\\n　どうあっても俺を変態にしたいようだな）"

# カズマ
# っと、クリスが動き始めた！\nじゃあな、めぐみん。
146 = "っと、クリスが動き始めた！\\nじゃあな、めぐみん。"

# めぐみん
# えっ！？\nあ、ちょ、ちょっと待ってくださいってば！
138 = "えっ！？\\nあ、ちょ、ちょっと待ってくださいってば！"

# カズマ（Ｍ）
# display as カズマ
# （それにしても、クリスは何がしたいんだ？\n　当てもなく、ぶらぶら歩いているだけのように\n　見えるが……）
175 = "（それにしても、クリスは何がしたいんだ？\\n　当てもなく、ぶらぶら歩いているだけのように\\n　見えるが……）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、いい。\n　時間はたっぷりあるんだし、\n　じっくり追いかけるか）
176 = "（まあ、いい。\\n　時間はたっぷりあるんだし、\\n　じっくり追いかけるか）"

