# root_c02.txt.scn

[info]
0 = ""

[characters]
303 = "アクア"
300 = "めぐみん"
304 = "カズマ"
306 = "ダクネス"
305 = "カズマ（Ｍ）"

[character_subs]
# 304 = "カズマ"

[script]
# lines: 63

# アクア
# ふああ、お腹がいっぱい。\nもう食べられないわ。
297 = "ふああ、お腹がいっぱい。\\nもう食べられないわ。"

# めぐみん
# 今日は幸せな気分で眠れそうですね。
310 = "今日は幸せな気分で眠れそうですね。"

# カズマ
# さて、俺は部屋に戻って寝るとするよ。
277 = "さて、俺は部屋に戻って寝るとするよ。"

# ダクネス
# 待て、カズマ。\n風呂には入ったのか？
320 = "待て、カズマ。\\n風呂には入ったのか？"

# カズマ
# あ、今日はまだ入ってなかったっけ。
266 = "あ、今日はまだ入ってなかったっけ。"

# ダクネス
# おいおい、大丈夫か？\n食事中もそうだったが少し様子がおかしいぞ。
275 = "おいおい、大丈夫か？\\n食事中もそうだったが少し様子がおかしいぞ。"

# カズマ
# ん？　そうか？
302 = "ん？　そうか？"

# めぐみん
# そうですよ。
283 = "そうですよ。"

# アクア
# 心ここにあらずって感じだったわよね～。
321 = "心ここにあらずって感じだったわよね～。"

# カズマ
# はは、気のせいだよ。\nんじゃ、サクッと風呂に入ってくるわ。
295 = "はは、気のせいだよ。\\nんじゃ、サクッと風呂に入ってくるわ。"

# めぐみん
# どうやら、こちらの考えすぎだったみたいですね。
292 = "どうやら、こちらの考えすぎだったみたいですね。"

# ダクネス
# （うーん、そうだろうか……）
366 = "（うーん、そうだろうか……）"

# アクア
# さて、私は部屋でとっておきの高級シュワシュワを\n飲んで寝ましょう。
279 = "さて、私は部屋でとっておきの高級シュワシュワを\\n飲んで寝ましょう。"

# めぐみん
# 私はもう横になります。
361 = "私はもう横になります。"

# ダクネス
# ああ、おやすみめぐみん。\nアクアは飲み過ぎるなよ？
267 = "ああ、おやすみめぐみん。\\nアクアは飲み過ぎるなよ？"

# アクア
# わかってるわよ。\nそれじゃ、おやすみー。
301 = "わかってるわよ。\\nそれじゃ、おやすみー。"

# ダクネス
# さて、私はどうするか。
278 = "さて、私はどうするか。"

# ダクネス
# …………。
263 = "…………。"

# ダクネス
# （やっぱりカズマの様子が気になるな）
370 = "（やっぱりカズマの様子が気になるな）"

# カズマ（Ｍ）
# display as カズマ
# （さて、さっさと風呂に入って――）
368 = "（さて、さっさと風呂に入って――）"

# カズマ（Ｍ）
# display as カズマ
# （ん？　誰だ？）
371 = "（ん？　誰だ？）"

# ダクネス
# 失礼するぞ。
317 = "失礼するぞ。"

# カズマ
# どうしたんだ、ダクネス。
291 = "どうしたんだ、ダクネス。"

# ダクネス
# あ……。\nい、いや、その。
264 = "あ……。\\nい、いや、その。"

# カズマ
# なんだよ。\n風呂に入りたいんだから、用件があるなら\n早く言ってくれ。
294 = "なんだよ。\\n風呂に入りたいんだから、用件があるなら\\n早く言ってくれ。"

# ダクネス
# いや、だからな……。
270 = "いや、だからな……。"

# カズマ
# だから、モジモジするだけじゃわからな……ハッ！
288 = "だから、モジモジするだけじゃわからな……ハッ！"

# ダクネス
# なんだ、どうした！
293 = "なんだ、どうした！"

# カズマ
# おい、ダクネス。\n気持ちはわからなくもないけどさ、\nそういうのはどうかと思うぞ。
274 = "おい、ダクネス。\\n気持ちはわからなくもないけどさ、\\nそういうのはどうかと思うぞ。"

# ダクネス
# は？　何がだ？
296 = "は？　何がだ？"

# カズマ
# だから、ほら。\n夜に、男の部屋に来てさ……そういうことを\n想像して楽しんでるんだろ？
287 = "だから、ほら。\\n夜に、男の部屋に来てさ……そういうことを\\n想像して楽しんでるんだろ？"

# ダクネス
# そういう……こと。\nって、そ、そそ、そんなことするか！
281 = "そういう……こと。\\nって、そ、そそ、そんなことするか！"

# カズマ
# いやでも顔が赤いし。
271 = "いやでも顔が赤いし。"

# ダクネス
# これはシュワシュワを飲んだからだ。
276 = "これはシュワシュワを飲んだからだ。"

# カズマ
# じゃあ、モジモジしてるのはどうしてぇ？
280 = "じゃあ、モジモジしてるのはどうしてぇ？"

# ダクネス
# うぐ、それは。
272 = "うぐ、それは。"

# カズマ
# あ、トイレか。\n夜だし、怖いからついてきてって頼みに来たんだ。
265 = "あ、トイレか。\\n夜だし、怖いからついてきてって頼みに来たんだ。"

# ダクネス
# 私は子供か！
362 = "私は子供か！"

# カズマ
# だったら、\nこんな時間にわざわざなんだっていうんだよ。
289 = "だったら、\\nこんな時間にわざわざなんだっていうんだよ。"

# ダクネス
# ただ、悩み事があるんじゃないかと思っただけだ。
285 = "ただ、悩み事があるんじゃないかと思っただけだ。"

# カズマ
# 俺にか？
312 = "俺にか？"

# ダクネス
# 夕飯の席で上の空だっただろう？\nそれで少し気になってな。
316 = "夕飯の席で上の空だっただろう？\\nそれで少し気になってな。"

# カズマ（Ｍ）
# display as カズマ
# （俺、そんなにぼーっとしてたのか？）
372 = "（俺、そんなにぼーっとしてたのか？）"

# カズマ
# 悩みなんてないよ。
324 = "悩みなんてないよ。"

# カズマ
# ただここ数日、バタバタしてたから\n気が抜けてるだけだって。
286 = "ただここ数日、バタバタしてたから\\n気が抜けてるだけだって。"

# ダクネス
# それならばいいのだが。
284 = "それならばいいのだが。"

# カズマ
# 心配かけて悪いな、ダクネス。
322 = "心配かけて悪いな、ダクネス。"

# カズマ
# ダクネスに言うことじゃないから。
308 = "ダクネスに言うことじゃないから。"

# ダクネス
# 何？　それはどういう意味だ。\nまさか、また良からぬことを考えていたのか？
311 = "何？　それはどういう意味だ。\\nまさか、また良からぬことを考えていたのか？"

# カズマ
# 違うって。\n言うほどの悩みなんてないってことだよ。
364 = "違うって。\\n言うほどの悩みなんてないってことだよ。"

# ダクネス
# 本当か？\nまた指輪を手に入れて、\n何か悪事を働こうと考えていなかったのか？
325 = "本当か？\\nまた指輪を手に入れて、\\n何か悪事を働こうと考えていなかったのか？"

# カズマ
# 呪いはもうこりごりだ！\nってか、何かして欲しかったのかよ？
315 = "呪いはもうこりごりだ！\\nってか、何かして欲しかったのかよ？"

# ダクネス
# い、言わせるな！！\nそんな破廉恥なことを！
269 = "い、言わせるな！！\\nそんな破廉恥なことを！"

# カズマ
# まあ、色々とな。
299 = "まあ、色々とな。"

# ダクネス
# 貴様、またみんなを騒動に巻き込むつもりか！\nそんな事は許さないぞ！\nやるなら私だけにしろ！
363 = "貴様、またみんなを騒動に巻き込むつもりか！\\nそんな事は許さないぞ！\\nやるなら私だけにしろ！"

# カズマ
# えっ？
273 = "えっ？"

# ダクネス
# えっ？
# 273 = "えっ？"

# カズマ（Ｍ）
# display as カズマ
# （まったく……\n　様子が変なのは、お前のほうじゃないか）
369 = "（まったく……\\n　様子が変なのは、お前のほうじゃないか）"

# カズマ
# とにかくだ。\n心配させたみたいで悪かったよ。\n本当になんでもないんだ。
290 = "とにかくだ。\\n心配させたみたいで悪かったよ。\\n本当になんでもないんだ。"

# ダクネス
# そうか。\nだが、困ったことがあったら\n遠慮せずに言ってくれ。
282 = "そうか。\\nだが、困ったことがあったら\\n遠慮せずに言ってくれ。"

# カズマ
# ああ、わかったよ。\nありがとな、ダクネス。
268 = "ああ、わかったよ。\\nありがとな、ダクネス。"

# カズマ（Ｍ）
# display as カズマ
# （うーむ、ただ、この間の騒動を\n　思い返していただけのはずが、\n　不審がられてたのか）
365 = "（うーむ、ただ、この間の騒動を\\n　思い返していただけのはずが、\\n　不審がられてたのか）"

# カズマ（Ｍ）
# display as カズマ
# （これ以上、心配をさせないように\n　気をつけないとな）
367 = "（これ以上、心配をさせないように\\n　気をつけないとな）"

[selections]
323 = "悩みなんてないよ"
307 = "ダクネスに言うことじゃないから"
298 = "まあ、色々とな"
