# root_b02.txt.scn

[info]
0 = ""

[characters]
151 = "カズマ"
148 = "めぐみん"
153 = "カズマ（Ｍ）"

[character_subs]
# 151 = "カズマ"

[script]
# lines: 24

# カズマ
# …………。
132 = "…………。"

# めぐみん
# …………。
# 132 = "…………。"

# カズマ
# 指輪だな。
157 = "指輪だな。"

# めぐみん
# 指輪ですね。
158 = "指輪ですね。"

# カズマ
# とりあえず……。
141 = "とりあえず……。"

# めぐみん
# 待ってください！\nまさかつけるつもりですか！？\nまた呪われたりしたらどうするつもりなんです！？
156 = "待ってください！\\nまさかつけるつもりですか！？\\nまた呪われたりしたらどうするつもりなんです！？"

# カズマ
# そんなことしねーって。\nとりあえずバニルに鑑定して貰うかって\n思っただけだよ。
139 = "そんなことしねーって。\\nとりあえずバニルに鑑定して貰うかって\\n思っただけだよ。"

# めぐみん
# また鑑定料金をふっかけられますよ？
147 = "また鑑定料金をふっかけられますよ？"

# カズマ（Ｍ）
# display as カズマ
# （それは勘弁して欲しい……）
169 = "（それは勘弁して欲しい……）"

# めぐみん
# それに、その指輪からは\nとても良くない何かを感じます。
137 = "それに、その指輪からは\\nとても良くない何かを感じます。"

# カズマ
# え？　お前ってそんなこともわかるのか？
133 = "え？　お前ってそんなこともわかるのか？"

# めぐみん
# なんとなくそんな気がするだけです。\n言うなれば、紅魔族に備わった危機感知能力ですね。
145 = "なんとなくそんな気がするだけです。\\n言うなれば、紅魔族に備わった危機感知能力ですね。"

# カズマ
# なんだそりゃ。
144 = "なんだそりゃ。"

# めぐみん
# カズマにもわかるように言うと、カンです。
152 = "カズマにもわかるように言うと、カンです。"

# カズマ
# ただのカンかよ！\n紅魔族関係ねーし！
140 = "ただのカンかよ！\\n紅魔族関係ねーし！"

# めぐみん
# それよりも、そんな物早く捨ててください。\nまた変な呪いにかかりますよ？
138 = "それよりも、そんな物早く捨ててください。\\nまた変な呪いにかかりますよ？"

# カズマ
# おい、なんでスカート押さえてるんだ？\nつけたりしないって言ったよな。
134 = "おい、なんでスカート押さえてるんだ？\\nつけたりしないって言ったよな。"

# カズマ
# それに、このまま放置しておくのも\nあまりよくないだろ。
136 = "それに、このまま放置しておくのも\\nあまりよくないだろ。"

# カズマ
# どこかの誰かが指輪をつけて、\n呪いにかかっちまうかもしれない。
143 = "どこかの誰かが指輪をつけて、\\n呪いにかかっちまうかもしれない。"

# めぐみん
# まあ、呪いの指輪と決まったわけでは\nありませんが。
146 = "まあ、呪いの指輪と決まったわけでは\\nありませんが。"

# カズマ
# とりあえず、\nバニルは無理でもウィズなら安く見てくれるだろ。
142 = "とりあえず、\\nバニルは無理でもウィズなら安く見てくれるだろ。"

# カズマ
# もし珍しい物なら\n高値で引き取ってもらえるかもしれねーし。
149 = "もし珍しい物なら\\n高値で引き取ってもらえるかもしれねーし。"

# めぐみん
# それが本音ですよね？
135 = "それが本音ですよね？"

# カズマ
# よし！\nそうと決まればウィズの店に行こうぜ！
150 = "よし！\\nそうと決まればウィズの店に行こうぜ！"

