# root_d11.txt.scn

[info]
0 = ""

[characters]
308 = "カズマ（Ｍ）"
304 = "カズマ"
310 = "クリス"
298 = "めぐみん"
325 = "戦士風の男冒険者"
332 = "盗賊風の男冒険者"

[character_subs]
# 304 = "カズマ"
374 = "？？？"
324 = "戦士冒険者"
331 = "盗賊冒険者"

[script]
# lines: 79

# カズマ（Ｍ）
# display as カズマ
# （……よし、誰もいないな）
365 = "（……よし、誰もいないな）"

# カズマ
# クリス、今のうちにさっさと行って来い。\n俺はここで見張ってるから。
311 = "クリス、今のうちにさっさと行って来い。\\n俺はここで見張ってるから。"

# クリス
# う、うん。\nごめんね。
257 = "う、うん。\\nごめんね。"

# カズマ（Ｍ）
# display as カズマ
# （さて、これからどうするか。\n　街の中はクリス狙いの奴らばっかだろうから\n　下手に動く訳にはいかないし……）
367 = "（さて、これからどうするか。\\n　街の中はクリス狙いの奴らばっかだろうから\\n　下手に動く訳にはいかないし……）"

# めぐみん
# display as ？？？
# ふふふふふ……。
295 = "ふふふふふ……。"

# カズマ（Ｍ）
# display as カズマ
# （こ、この声は！？）
366 = "（こ、この声は！？）"

# めぐみん
# やはり来ましたね、カズマ。\n私の予想した通りです。
303 = "やはり来ましたね、カズマ。\\n私の予想した通りです。"

# カズマ
# げっ、めぐみん！？
270 = "げっ、めぐみん！？"

# めぐみん
# カズマがクリスと共に逃亡していると聞いて\n必ずこの屋敷に戻って来ると思い\nはり込んでいたのですよ！
306 = "カズマがクリスと共に逃亡していると聞いて\\n必ずこの屋敷に戻って来ると思い\\nはり込んでいたのですよ！"

# めぐみん
# さあ、観念して大人しく我が手中に堕ちるがいい！\nそうすれば、手荒なことはしないと誓いましょう！
273 = "さあ、観念して大人しく我が手中に堕ちるがいい！\\nそうすれば、手荒なことはしないと誓いましょう！"

# カズマ
# さては……あのバカな噂を流して\nクエストを勝手に発注した犯人はお前か！
274 = "さては……あのバカな噂を流して\\nクエストを勝手に発注した犯人はお前か！"

# めぐみん
# ……なんのことですか？\n私も噂を聞いて、ギルドの掲示板を\n見ただけですよ？
249 = "……なんのことですか？\\n私も噂を聞いて、ギルドの掲示板を\\n見ただけですよ？"

# カズマ
# じゃあ、このふざけたクエストを出したのは\nめぐみんじゃないんだな？
275 = "じゃあ、このふざけたクエストを出したのは\\nめぐみんじゃないんだな？"

# めぐみん
# どういうことですか？\nカズマが出したクエストなのでしょう？
289 = "どういうことですか？\\nカズマが出したクエストなのでしょう？"

# カズマ
# それが、俺じゃないんだ。\n俺がクリスを捜していたのは事実なんだけど、\n誰かがあんな話をでっち上げたんだよ。
279 = "それが、俺じゃないんだ。\\n俺がクリスを捜していたのは事実なんだけど、\\n誰かがあんな話をでっち上げたんだよ。"

# カズマ
# つーか、クリスを捕まえてきたら\n１００万エリスとか……。
286 = "つーか、クリスを捕まえてきたら\\n１００万エリスとか……。"

# カズマ
# そんなのどう考えてもおかしいだろ？\n俺にはそんな金なんてないっての！
281 = "そんなのどう考えてもおかしいだろ？\\n俺にはそんな金なんてないっての！"

# めぐみん
# なるほど、理解しました。\n確かに、カズマにしては気前が良すぎると\n思っていましたし。
291 = "なるほど、理解しました。\\n確かに、カズマにしては気前が良すぎると\\n思っていましたし。"

# カズマ（Ｍ）
# display as カズマ
# （わかってくれたか……）
370 = "（わかってくれたか……）"

# カズマ
# ああ、そうだ、めぐみん。\nアクアがどこにいるか知らないか？
250 = "ああ、そうだ、めぐみん。\\nアクアがどこにいるか知らないか？"

# めぐみん
# さぁ？\nそう言えば、今日は朝から見ていませんね。
272 = "さぁ？\\nそう言えば、今日は朝から見ていませんね。"

# カズマ
# そっか、ありがとな。
277 = "そっか、ありがとな。"

# 戦士風の男冒険者
# display as 戦士冒険者
# おーい、こっちだこっち！
263 = "おーい、こっちだこっち！"

# カズマ（Ｍ）
# display as カズマ
# （なっ、嗅ぎつけてきやがった！）
368 = "（なっ、嗅ぎつけてきやがった！）"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# 本当にこっちか？\nでかい屋敷しかないぞ。
327 = "本当にこっちか？\\nでかい屋敷しかないぞ。"

# 戦士風の男冒険者
# display as 戦士冒険者
# こっちで見かけたって情報があるんだよ。\n確かここ、あの冒険者……カズマだっけ？\nあいつが住んでるところだろ。
271 = "こっちで見かけたって情報があるんだよ。\\n確かここ、あの冒険者……カズマだっけ？\\nあいつが住んでるところだろ。"

# カズマ
# おい、クリス！\nまだ終わらないのかっ！？
261 = "おい、クリス！\\nまだ終わらないのかっ！？"

# クリス
# ちょっと待って！\n今、開けたら怒るからね！？
284 = "ちょっと待って！\\n今、開けたら怒るからね！？"

# カズマ
# いいから早くしてくれ！
256 = "いいから早くしてくれ！"

# 戦士風の男冒険者
# display as 戦士冒険者
# おーい、誰かいないのか？
264 = "おーい、誰かいないのか？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# いいから中に入っちまおうぜ。
255 = "いいから中に入っちまおうぜ。"

# 戦士風の男冒険者
# display as 戦士冒険者
# つっても、鍵かかってるし……\n勝手にぶち破る訳にもいかんだろ。
285 = "つっても、鍵かかってるし……\\n勝手にぶち破る訳にもいかんだろ。"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# 何言ってんだよ。\n１００万エリスだぜ１００万エリス。\nそんだけありゃ弁償くらいできんだろ。
315 = "何言ってんだよ。\\n１００万エリスだぜ１００万エリス。\\nそんだけありゃ弁償くらいできんだろ。"

# カズマ（Ｍ）
# display as カズマ
# （まずい、あいつら賞金に目がくらんでやがる。\n　このままじゃ見つかるのも時間の問題だ。\n　どうする？　どうする俺！？）
369 = "（まずい、あいつら賞金に目がくらんでやがる。\\n　このままじゃ見つかるのも時間の問題だ。\\n　どうする？　どうする俺！？）"

# カズマ（Ｍ）
# display as カズマ
# （無理矢理、トイレのドアをあけるしかないな！）
373 = "（無理矢理、トイレのドアをあけるしかないな！）"

# カズマ（Ｍ）
# display as カズマ
# （クリスには悪いが、このままじゃ\n　１００万エリスを払うはめになっちまう。\n　……怨むなよ！）
371 = "（クリスには悪いが、このままじゃ\\n　１００万エリスを払うはめになっちまう。\\n　……怨むなよ！）"

# クリス
# えっ？
259 = "えっ？"

# クリス
# ちょ、ちょっとカズマ！\n何やってるの！？
283 = "ちょ、ちょっとカズマ！\\n何やってるの！？"

# カズマ
# お前がなかなか出て来ないから悪いんだろうが！\nこのままじゃ捕まっちまう！
265 = "お前がなかなか出て来ないから悪いんだろうが！\\nこのままじゃ捕まっちまう！"

# クリス
# なっ、何考えてるわけ、信じらんないっ！
290 = "なっ、何考えてるわけ、信じらんないっ！"

# クリス
# 女の子が用を足してるところを\n無理矢理こじあけようとか、本気で言ってるの！？\nキミ、自分が何やってるかわかってる！？
321 = "女の子が用を足してるところを\\n無理矢理こじあけようとか、本気で言ってるの！？\\nキミ、自分が何やってるかわかってる！？"

# めぐみん
# 変態だとは知っていましたが……\n正直、ドン引きです。
319 = "変態だとは知っていましたが……\\n正直、ドン引きです。"

# カズマ
# ああ、もう！\nそんなこと言ってる場合じゃないだろ！\nいいからここを開けろクリス！
251 = "ああ、もう！\\nそんなこと言ってる場合じゃないだろ！\\nいいからここを開けろクリス！"

# クリス
# 誰が開けるかバカーーーっ！！
364 = "誰が開けるかバカーーーっ！！"

# カズマ（Ｍ）
# display as カズマ
# （冒険者の気を引きつけておく……\n　うん、それしかない）
372 = "（冒険者の気を引きつけておく……\\n　うん、それしかない）"

# カズマ
# おいクリス！\nちょっと行ってくるから、その間にお前は逃げろ！
262 = "おいクリス！\\nちょっと行ってくるから、その間にお前は逃げろ！"

# クリス
# えっ、何？\nどういうこと？
258 = "えっ、何？\\nどういうこと？"

# カズマ
# 外の奴らが屋敷に入ってきて、\nお前を見つけるのは時間の問題だ。\nだから俺が時間を稼ぎに行ってくる！
320 = "外の奴らが屋敷に入ってきて、\\nお前を見つけるのは時間の問題だ。\\nだから俺が時間を稼ぎに行ってくる！"

# クリス
# 時間を稼ぐって……\nたった１人でどうするつもりなの？
326 = "時間を稼ぐって……\\nたった１人でどうするつもりなの？"

# カズマ
# まあ、どうにかするさ。\n元はと言えば、クリスを巻き込んだのだって\n俺のせいだしな、気にしないでくれ。
297 = "まあ、どうにかするさ。\\n元はと言えば、クリスを巻き込んだのだって\\n俺のせいだしな、気にしないでくれ。"

# クリス
# カズマ……。
305 = "カズマ……。"

# めぐみん
# かなり人が集まってますね。\nどうも、１０人以上はいるようですが。
268 = "かなり人が集まってますね。\\nどうも、１０人以上はいるようですが。"

# カズマ
# え！？　そんなに？\nうわぁ、なんだよ、\nみんな賞金に目が眩みすぎだろぉ……。
260 = "え！？　そんなに？\\nうわぁ、なんだよ、\\nみんな賞金に目が眩みすぎだろぉ……。"

# めぐみん
# カズマ１人で立ち向かうつもりですか？\nどう考えても、多勢に無勢ですよ。
309 = "カズマ１人で立ち向かうつもりですか？\\nどう考えても、多勢に無勢ですよ。"

# カズマ
# ま、まあなんとかなるだろ、なんとか。
296 = "ま、まあなんとかなるだろ、なんとか。"

# めぐみん
# 本当に？
328 = "本当に？"

# カズマ
# …………。
248 = "…………。"

# クリス
# はあ……。\nカズマ、無理しないでいいからちょっと待ってて。\nすぐ出るからさ。
293 = "はあ……。\\nカズマ、無理しないでいいからちょっと待ってて。\\nすぐ出るからさ。"

# カズマ
# めぐみんに任せる！
301 = "めぐみんに任せる！"

# めぐみん
# はい？
294 = "はい？"

# カズマ
# めぐみん、お前に任務を与える。\nあいつらをなんとかしてこい！
299 = "めぐみん、お前に任務を与える。\\nあいつらをなんとかしてこい！"

# めぐみん
# お断りします。\nなぜ、私がカズマの代わりに、自ら火の粉を\n浴びに行かなければならないのですか。
267 = "お断りします。\\nなぜ、私がカズマの代わりに、自ら火の粉を\\n浴びに行かなければならないのですか。"

# カズマ
# お前なぁ、クリスが可哀想だと思わないのかよ？
266 = "お前なぁ、クリスが可哀想だと思わないのかよ？"

# めぐみん
# それはまぁ……\nクリスの状況については同情します。
280 = "それはまぁ……\\nクリスの状況については同情します。"

# めぐみん
# ですが、クリスをこの状況に陥らせたのは\nカズマでしょう？
287 = "ですが、クリスをこの状況に陥らせたのは\\nカズマでしょう？"

# めぐみん
# 人に尻拭いをさせるのではなく、\n自分でなんとかしようという気概はないのですか？
313 = "人に尻拭いをさせるのではなく、\\n自分でなんとかしようという気概はないのですか？"

# カズマ
# 爆裂魔法ぶっぱなしては力尽きて、\nその度に俺におんぶされてるアークウィザードは\nどこのどいつだったかな？
330 = "爆裂魔法ぶっぱなしては力尽きて、\\nその度に俺におんぶされてるアークウィザードは\\nどこのどいつだったかな？"

# めぐみん
# ぐぐっ、卑怯な！\nそれとこれは別の話でしょう！
269 = "ぐぐっ、卑怯な！\\nそれとこれは別の話でしょう！"

# めぐみん
# あれは、あくまで善意による協力。\n我が至高の魔術を最適な環境で行使するために\n必要不可欠な儀式なのです！
254 = "あれは、あくまで善意による協力。\\n我が至高の魔術を最適な環境で行使するために\\n必要不可欠な儀式なのです！"

# カズマ
# そういうことなら今度から置いて帰る。\nお前がカエルに食われかけて、\n舐められまくっていても放置して行くからな。
276 = "そういうことなら今度から置いて帰る。\\nお前がカエルに食われかけて、\\n舐められまくっていても放置して行くからな。"

# めぐみん
# 仕方ありませんね。\nクリスとは知らぬ仲という訳でもありませんし、\n多少なり、協力してあげましょう。
314 = "仕方ありませんね。\\nクリスとは知らぬ仲という訳でもありませんし、\\n多少なり、協力してあげましょう。"

# カズマ
# だってよ。\n良かったな、クリス。
282 = "だってよ。\\n良かったな、クリス。"

# クリス
# あのねぇ、カズマ。\nあたしが言うのもあれだけどさ、\nそうやって仲間を脅すのはどうかと思うよ？
253 = "あのねぇ、カズマ。\\nあたしが言うのもあれだけどさ、\\nそうやって仲間を脅すのはどうかと思うよ？"

# カズマ
# でも俺までクリスから離れるわけには\nいかないだろ。\n元はと言えば俺のせいなんだし。
288 = "でも俺までクリスから離れるわけには\\nいかないだろ。\\n元はと言えば俺のせいなんだし。"

# クリス
# もしかして、責任感じてるんだ？
302 = "もしかして、責任感じてるんだ？"

# カズマ
# そりゃまあ、それなりにな。
278 = "そりゃまあ、それなりにな。"

# クリス
# はぁ……。\nトイレの前で話をするとかありえない。\nキミ、本気でデリカシーなさ過ぎだよ。
292 = "はぁ……。\\nトイレの前で話をするとかありえない。\\nキミ、本気でデリカシーなさ過ぎだよ。"

# めぐみん
# カズマ！\nあいつら、入って来る気ですよ！？
307 = "カズマ！\\nあいつら、入って来る気ですよ！？"

# カズマ
# ああ、わかってる！\nクリス、文句は後で聞く。\nとりあえずここから逃げるぞ。
252 = "ああ、わかってる！\\nクリス、文句は後で聞く。\\nとりあえずここから逃げるぞ。"

[selections]
329 = "無理矢理、トイレのドアをあける"
316 = "冒険者の気を引きつけておく"
300 = "めぐみんに任せる"
