# root_b20.txt.scn

[info]
0 = ""

[characters]
354 = "めぐみん"
367 = "カズマ"
371 = "カズマ（Ｍ）"
382 = "女性"

[character_subs]
# 367 = "カズマ"

[script]
# lines: 107

# めぐみん
# カズマ、もう一度だけ、確認させてください。\n本当にいいんですね？
369 = "カズマ、もう一度だけ、確認させてください。\\n本当にいいんですね？"

# カズマ
# ふっ、男の生き様を見せてやろうじゃないか。\n惚れるなよ？
348 = "ふっ、男の生き様を見せてやろうじゃないか。\\n惚れるなよ？"

# めぐみん
# ほ、惚れるわけないじゃないですかっ！\n自意識過剰もいい加減にしてください！
349 = "ほ、惚れるわけないじゃないですかっ！\\n自意識過剰もいい加減にしてください！"

# カズマ
# そ、そんなに怒ることないだろ？
320 = "そ、そんなに怒ることないだろ？"

# めぐみん
# まったく！\nこんな状況で軽口を叩ける\n神経が信じられませんよ。
353 = "まったく！\\nこんな状況で軽口を叩ける\\n神経が信じられませんよ。"

# カズマ
# ま、俺のことは気にしなくていい。\nさあ、指輪を。
352 = "ま、俺のことは気にしなくていい。\\nさあ、指輪を。"

# めぐみん
# では……いきます。
338 = "では……いきます。"

# カズマ
# よっし！\nひと思いにこい！
364 = "よっし！\\nひと思いにこい！"

# めぐみん
# あれ？\nえいっ！　えいっ！
296 = "あれ？\\nえいっ！　えいっ！"

# カズマ
# いててててててて、ストップ！\nめぐみんストーップ！
301 = "いててててててて、ストップ！\\nめぐみんストーップ！"

# めぐみん
# ……入りませんね。\n指輪が小さいみたいです。
291 = "……入りませんね。\\n指輪が小さいみたいです。"

# カズマ
# ああ……。\nそういや、話の勢いに乗っちまって\nサイズの確認してなかったな。
292 = "ああ……。\\nそういや、話の勢いに乗っちまって\\nサイズの確認してなかったな。"

# カズマ（Ｍ）
# display as カズマ
# （せっかく覚悟を決めたのに、\n　なんて間抜けな結果なんだ……！）
432 = "（せっかく覚悟を決めたのに、\\n　なんて間抜けな結果なんだ……！）"

# カズマ（Ｍ）
# display as カズマ
# （ここまできて打つ手なしかよ。\n　なにも起こらないことを祈りつつ\n　アクア達を待つしかないのか？）
430 = "（ここまできて打つ手なしかよ。\\n　なにも起こらないことを祈りつつ\\n　アクア達を待つしかないのか？）"

# カズマ
# 悪いな、めぐみん。\nここまでやらせておいて、\nこんな結果になるなんて。
386 = "悪いな、めぐみん。\\nここまでやらせておいて、\\nこんな結果になるなんて。"

# めぐみん
# 仕方がありません。\nカズマは……よく頑張ってくれたと思いますから。
376 = "仕方がありません。\\nカズマは……よく頑張ってくれたと思いますから。"

# カズマ（Ｍ）
# display as カズマ
# （はは……。\n　そう言ってもらえると少しは報われるぜ）
436 = "（はは……。\\n　そう言ってもらえると少しは報われるぜ）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、指輪のサイズを確認し忘れるなんて\n　実際の結婚式でやらかしたら大惨事だなぁ）
431 = "（しかし、指輪のサイズを確認し忘れるなんて\\n　実際の結婚式でやらかしたら大惨事だなぁ）"

# カズマ（Ｍ）
# display as カズマ
# （……ん？　待てよ？\n　俺の指には小さいけど、\n　めぐみんの指にならはまるんじゃないか？）
429 = "（……ん？　待てよ？\\n　俺の指には小さいけど、\\n　めぐみんの指にならはまるんじゃないか？）"

# カズマ（Ｍ）
# display as カズマ
# （だけど、こんな呪われた指輪を\n　つけてくれるとは考えにくい。\n　やっぱり無理か？）
433 = "（だけど、こんな呪われた指輪を\\n　つけてくれるとは考えにくい。\\n　やっぱり無理か？）"

# カズマ（Ｍ）
# display as カズマ
# （でも、このままっていうわけにもな。\n　ここはダメ元で聞いてみるか！）
434 = "（でも、このままっていうわけにもな。\\n　ここはダメ元で聞いてみるか！）"

# カズマ
# めぐみん、頼みがある！\nこのとおりだ！
355 = "めぐみん、頼みがある！\\nこのとおりだ！"

# めぐみん
# はっ？\nなんですか、突然、頭を下げたりして。
345 = "はっ？\\nなんですか、突然、頭を下げたりして。"

# カズマ
# 無理を承知の上で頼む！\nこの指輪をはめてくれないか？
389 = "無理を承知の上で頼む！\\nこの指輪をはめてくれないか？"

# めぐみん
# あの、カズマ？\n私にこの上、更に呪われろと言うのですか？
294 = "あの、カズマ？\\n私にこの上、更に呪われろと言うのですか？"

# カズマ
# そういうつもりはない。\nだが、結果的にそういうことになる。
322 = "そういうつもりはない。\\nだが、結果的にそういうことになる。"

# カズマ
# けどさ、このままなにも起こらなきゃいいが、\nそんな保証はないんだぜ？\nのんきにもしていられないだろ？
310 = "けどさ、このままなにも起こらなきゃいいが、\\nそんな保証はないんだぜ？\\nのんきにもしていられないだろ？"

# めぐみん
# そんなに、ここから出たいんですか？
332 = "そんなに、ここから出たいんですか？"

# カズマ
# それもあるけどさ、\nウエディングドレスのことから考えて\n呪いの対象はめぐみんなんじゃないか？
331 = "それもあるけどさ、\\nウエディングドレスのことから考えて\\n呪いの対象はめぐみんなんじゃないか？"

# めぐみん
# わ、私ですか！？\nなにもしていないのに！
365 = "わ、私ですか！？\\nなにもしていないのに！"

# カズマ
# これ以上、めぐみんになにかあったら大変だ。\nだから一刻も早くここから出たい。
315 = "これ以上、めぐみんになにかあったら大変だ。\\nだから一刻も早くここから出たい。"

# カズマ
# そんなわけだから、頼む！
333 = "そんなわけだから、頼む！"

# めぐみん
# 私のため……ですか……。
426 = "私のため……ですか……。"

# カズマ
# よし、次はめぐみんの番だな。
363 = "よし、次はめぐみんの番だな。"

# めぐみん
# 何がですか？
377 = "何がですか？"

# カズマ
# 何って指輪に決まってるだろ。\n俺じゃ小さすぎて入らないけど、\nめぐみんなら楽勝じゃないか。
378 = "何って指輪に決まってるだろ。\\n俺じゃ小さすぎて入らないけど、\\nめぐみんなら楽勝じゃないか。"

# カズマ
# ほら、早速試そうぜ。\nさっさと呪いを解いて\nこんなところおさらばだ！
351 = "ほら、早速試そうぜ。\\nさっさと呪いを解いて\\nこんなところおさらばだ！"

# めぐみん
# ……つまり、私に呪われろと言うんですか。
288 = "……つまり、私に呪われろと言うんですか。"

# カズマ
# そういうことになるけど……\n大丈夫だって、俺を信じろ！
321 = "そういうことになるけど……\\n大丈夫だって、俺を信じろ！"

# めぐみん
# カズマのなにを信じろと言うんです？
370 = "カズマのなにを信じろと言うんです？"

# カズマ
# これまで積み上げてきた信頼？
314 = "これまで積み上げてきた信頼？"

# めぐみん
# …………。
285 = "…………。"

# カズマ
# な、なんだよ。\nその微妙な顔は！
341 = "な、なんだよ。\\nその微妙な顔は！"

# めぐみん
# いえ、別に。
299 = "いえ、別に。"

# カズマ
# なあ、何か欲しい物はあるか？
342 = "なあ、何か欲しい物はあるか？"

# めぐみん
# え？　なんですか、唐突に。
306 = "え？　なんですか、唐突に。"

# カズマ
# いいからさ、今なにが欲しい？
297 = "いいからさ、今なにが欲しい？"

# めぐみん
# ジャイアントトードの唐揚げが欲しいです。\nさすがにクッキーだけでは体がもちません。
373 = "ジャイアントトードの唐揚げが欲しいです。\\nさすがにクッキーだけでは体がもちません。"

# カズマ
# ここから出たら好きなだけおごってやる。\nなんならカニもつけてやる。
311 = "ここから出たら好きなだけおごってやる。\\nなんならカニもつけてやる。"

# めぐみん
# ほ、本当ですか！？\nどうしたんです、大盤振る舞いじゃないですか！
350 = "ほ、本当ですか！？\\nどうしたんです、大盤振る舞いじゃないですか！"

# カズマ
# 巻き込んだようなもんだしな。\nそれくらいの誠意は見せるさ。
385 = "巻き込んだようなもんだしな。\\nそれくらいの誠意は見せるさ。"

# めぐみん
# カニって、シモフリアカガニでも\nいいんですよね！？
372 = "カニって、シモフリアカガニでも\\nいいんですよね！？"

# カズマ
# お、おう！\n任せておけ。
307 = "お、おう！\\n任せておけ。"

# めぐみん
# となれば、一刻も早くここから\n抜け出したいです！
339 = "となれば、一刻も早くここから\\n抜け出したいです！"

# カズマ
# そうだろう、そうだろう。\nそのためにも、ちょっと指輪をはめてみようか？
323 = "そうだろう、そうだろう。\\nそのためにも、ちょっと指輪をはめてみようか？"

# めぐみん
# ああ、なるほど。\nそういうことですか。
293 = "ああ、なるほど。\\nそういうことですか。"

# カズマ
# やっぱりダメか？
360 = "やっぱりダメか？"

# めぐみん
# ……カズマは、呪われるリスクを背負ってまで\n指輪をはめようとしてくれたんです。
290 = "……カズマは、呪われるリスクを背負ってまで\\n指輪をはめようとしてくれたんです。"

# めぐみん
# ここで私がなにもしなかったら……\nあんまりじゃないですか。
312 = "ここで私がなにもしなかったら……\\nあんまりじゃないですか。"

# カズマ
# じゃあ、もう一度、確認するぞ？\n本当にいいんだな？
317 = "じゃあ、もう一度、確認するぞ？\\n本当にいいんだな？"

# めぐみん
# つけるように仕向けたのはそっちですよ？
335 = "つけるように仕向けたのはそっちですよ？"

# カズマ
# それはそうだけどさ、\nやけにあっさり引き受けてくれたから。
330 = "それはそうだけどさ、\\nやけにあっさり引き受けてくれたから。"

# めぐみん
# なにかあったら、責任を取ってくださいよ？
343 = "なにかあったら、責任を取ってくださいよ？"

# カズマ
# 責任って？\nフリじゃなくて本当に結婚をしろってことか！？
427 = "責任って？\\nフリじゃなくて本当に結婚をしろってことか！？"

# めぐみん
# ば、ばばばばばば、馬鹿なことを\n言わないでくださいっ！
346 = "ば、ばばばばばば、馬鹿なことを\\n言わないでくださいっ！"

# カズマ
# いや、冗談だって。\nそんな真っ赤になって怒ることないじゃないか。
302 = "いや、冗談だって。\\nそんな真っ赤になって怒ることないじゃないか。"

# めぐみん
# それ、この状況で言っていい\n冗談ではありませんよ！
328 = "それ、この状況で言っていい\\n冗談ではありませんよ！"

# カズマ
# それじゃ、指輪をはめるぞ。\n手を貸してくれ。
329 = "それじゃ、指輪をはめるぞ。\\n手を貸してくれ。"

# めぐみん
# さすがに少し……緊張します。
316 = "さすがに少し……緊張します。"

# カズマ
# そりゃな、呪われるかもしれないんだ。\n緊張くらいするだろう。
327 = "そりゃな、呪われるかもしれないんだ。\\n緊張くらいするだろう。"

# めぐみん
# ……そういう意味では――
287 = "……そういう意味では――"

# めぐみん
# いえ、もうなんだっていいです！\n早くすませてください。
298 = "いえ、もうなんだっていいです！\\n早くすませてください。"

# カズマ
# よし、ピッタリだ！\nどうだ、なにか変化はあるか？
362 = "よし、ピッタリだ！\\nどうだ、なにか変化はあるか？"

# めぐみん
# うーん……。
304 = "うーん……。"

# めぐみん
# 特になにも感じません。\nドレスも張り付いたままですね。
390 = "特になにも感じません。\\nドレスも張り付いたままですね。"

# カズマ
# そっかぁ。\nじゃあ、いったん指輪を外してみようぜ。\n……って、あれ？
325 = "そっかぁ。\\nじゃあ、いったん指輪を外してみようぜ。\\n……って、あれ？"

# めぐみん
# どうかしましたか？
340 = "どうかしましたか？"

# カズマ
# ゆ、指輪が外れない。
361 = "ゆ、指輪が外れない。"

# めぐみん
# ……ウェディングドレスは脱げない、\n指輪もとれないって\n踏んだり蹴ったりじゃないですか！
289 = "……ウェディングドレスは脱げない、\\n指輪もとれないって\\n踏んだり蹴ったりじゃないですか！"

# カズマ
# 安心しろ、アクアが来るまで俺が守ってやるから！
383 = "安心しろ、アクアが来るまで俺が守ってやるから！"

# めぐみん
# もしアクアでもどうにもできなかったら\nどうするんですか！
359 = "もしアクアでもどうにもできなかったら\\nどうするんですか！"

# カズマ
# そ、そのときは……。
319 = "そ、そのときは……。"

# めぐみん
# そのときはなんです！？
326 = "そのときはなんです！？"

# カズマ
# お、俺が、お前のために味噌汁を作ってやる！
308 = "お、俺が、お前のために味噌汁を作ってやる！"

# めぐみん
# カズマ……。
368 = "カズマ……。"

# カズマ
# これが俺の覚悟ってやつだ。
313 = "これが俺の覚悟ってやつだ。"

# めぐみん
# すみません、ミソシルってなんですか？
318 = "すみません、ミソシルってなんですか？"

# カズマ
# ですよねー！？
337 = "ですよねー！？"

# めぐみん
# ですが、悪い気はしませんでした。
336 = "ですが、悪い気はしませんでした。"

# めぐみん
# 正直、よくわかりませんが、\nもし何かあったら、ミソシル作ってください。
388 = "正直、よくわかりませんが、\\nもし何かあったら、ミソシル作ってください。"

# カズマ（Ｍ）
# display as カズマ
# （めぐみん……）
437 = "（めぐみん……）"

# カズマ
# うお！？
303 = "うお！？"

# めぐみん
# きゃあっ！？\nな、な、なんですか！？
309 = "きゃあっ！？\\nな、な、なんですか！？"

# カズマ
# 教会の鐘か。\nだけど、どうして突然、鳴りだしたんだ？
387 = "教会の鐘か。\\nだけど、どうして突然、鳴りだしたんだ？"

# 女性
# ……ありがとう。
286 = "……ありがとう。"

# めぐみん
# え？　だ、誰ですか！？
305 = "え？　だ、誰ですか！？"

# めぐみん
# ひゃあああっ！？
347 = "ひゃあああっ！？"

# カズマ
# めぐみんっ！？
356 = "めぐみんっ！？"

# カズマ（Ｍ）
# display as カズマ
# （なんだ、なにが起こったんだ！？\n　めぐみんの体が光って……\n　目を開けてられない！）
435 = "（なんだ、なにが起こったんだ！？\\n　めぐみんの体が光って……\\n　目を開けてられない！）"

# カズマ
# めぐみん！？
357 = "めぐみん！？"

# めぐみん
# カ、カズマ？\n今の光は一体……？
366 = "カ、カズマ？\\n今の光は一体……？"

# カズマ
# って、おい！\nドレスはどこに行ったんだ！？
334 = "って、おい！\\nドレスはどこに行ったんだ！？"

# めぐみん
# あれ？\nいつの間に元に戻って……。
295 = "あれ？\\nいつの間に元に戻って……。"

# めぐみん
# も、もしかして！\n呪いが解けたのですか！？
358 = "も、もしかして！\\n呪いが解けたのですか！？"

# カズマ
# 多分、そういうことだと思う。
381 = "多分、そういうことだと思う。"

# カズマ
# そうだ！\n呪いが解けたのなら外に出られるはずだ！\n試してみよう！
324 = "そうだ！\\n呪いが解けたのなら外に出られるはずだ！\\n試してみよう！"

# めぐみん
# は、はい！
344 = "は、はい！"

[selections]
428 = "頭を下げて頼む"
300 = "いつもの調子で軽く頼む"
380 = "報酬を提示して頼む"
