# root_b14.txt.scn

[info]
0 = ""

[characters]
231 = "カズマ（Ｍ）"
230 = "カズマ"
227 = "めぐみん"

[character_subs]
# 230 = "カズマ"
261 = "？？？"

[script]
# lines: 62

# カズマ（Ｍ）
# display as カズマ
# （さて、俺もいい加減寝るか。\n　正直、呪われた教会で眠るなんて\n　冗談じゃないって言いたが、もう色々と限界だ）
256 = "（さて、俺もいい加減寝るか。\\n　正直、呪われた教会で眠るなんて\\n　冗談じゃないって言いたが、もう色々と限界だ）"

# カズマ（Ｍ）
# display as カズマ
# （というわけで、おやすみなさいっと）
257 = "（というわけで、おやすみなさいっと）"

# カズマ
# …………。
192 = "…………。"

# カズマ
# ………………。
191 = "………………。"

# カズマ
# ……………………。
190 = "……………………。"

# カズマ（Ｍ）
# display as カズマ
# （……ん？\n　なんだ、今、なにか音がした？）
254 = "（……ん？\\n　なんだ、今、なにか音がした？）"

# カズマ（Ｍ）
# display as カズマ
# （なっ、またかーーーーー！）
258 = "（なっ、またかーーーーー！）"

# カズマ（Ｍ）
# display as カズマ
# （呪い……幽霊なのか？\n　まさか、最初から寝込みを襲うつもりで？）
259 = "（呪い……幽霊なのか？\\n　まさか、最初から寝込みを襲うつもりで？）"

# カズマ（Ｍ）
# display as カズマ
# （くそ、こうなったらやってやろうじぇねえか！）
255 = "（くそ、こうなったらやってやろうじぇねえか！）"

# カズマ（Ｍ）
# display as カズマ
# （幽霊の１匹くらいだったら、俺１人でも！）
260 = "（幽霊の１匹くらいだったら、俺１人でも！）"

# カズマ
# おらあああ、かかって来いよおおおお！
201 = "おらあああ、かかって来いよおおおお！"

# めぐみん
# display as ？？？
# きゃぁぁぁぁっ！？
202 = "きゃぁぁぁぁっ！？"

# カズマ
# うわぁぁぁぁぁぁっ！！
199 = "うわぁぁぁぁぁぁっ！！"

# めぐみん
# うううう、急に大声を出さないでください！
198 = "うううう、急に大声を出さないでください！"

# カズマ
# な、なんだ、めぐみんかよ！\n驚かせるな！
218 = "な、なんだ、めぐみんかよ！\\n驚かせるな！"

# めぐみん
# そそそ、それはこっちのセリフです！\n口から心臓が飛び出るかと思いましたよ！？
207 = "そそそ、それはこっちのセリフです！\\n口から心臓が飛び出るかと思いましたよ！？"

# カズマ
# どうしてここにいるんだよ。\n寝たんじゃなかったのか？
217 = "どうしてここにいるんだよ。\\n寝たんじゃなかったのか？"

# めぐみん
# 寝ようとはしたのですが……。
240 = "寝ようとはしたのですが……。"

# カズマ
# 眠れないのか？\nもしかして、１人で寝るのが怖いから\n一緒に寝て欲しいのか？
245 = "眠れないのか？\\nもしかして、１人で寝るのが怖いから\\n一緒に寝て欲しいのか？"

# めぐみん
# ち、違いますよっ！\nどれだけ自意識過剰なんですか！
212 = "ち、違いますよっ！\\nどれだけ自意識過剰なんですか！"

# カズマ
# 誰が自意識過剰だっ！\nはあ、じゃあ、一体どうしたんだよ？
250 = "誰が自意識過剰だっ！\\nはあ、じゃあ、一体どうしたんだよ？"

# めぐみん
# あ、あのですね……。
195 = "あ、あのですね……。"

# めぐみん
# …………。
# 192 = "…………。"

# めぐみん
# ……………………。
# 190 = "……………………。"

# カズマ
# なぜ黙る。
219 = "なぜ黙る。"

# めぐみん
# で、ですから……なんと言えばいいのか……。
214 = "で、ですから……なんと言えばいいのか……。"

# カズマ
# ズバッと核心を言ってくれよ。\nいまさら気を使う仲でもないだろ？\nほらほら、早く。
232 = "ズバッと核心を言ってくれよ。\\nいまさら気を使う仲でもないだろ？\\nほらほら、早く。"

# めぐみん
# そ、そんなに急かさなくても\nいいじゃないですか！\nカズマは優しさが足りません！
203 = "そ、そんなに急かさなくても\\nいいじゃないですか！\\nカズマは優しさが足りません！"

# カズマ
# んなこと言われてもさぁ。\nこっちは眠ってたのを起こされたんだぜ？
229 = "んなこと言われてもさぁ。\\nこっちは眠ってたのを起こされたんだぜ？"

# めぐみん
# それは……すみません。
208 = "それは……すみません。"

# カズマ
# 謝らなくていいから用件を言ってくれ。\n何かあるんだろ？
251 = "謝らなくていいから用件を言ってくれ。\\n何かあるんだろ？"

# めぐみん
# それは……その……。
209 = "それは……その……。"

# カズマ
# どうしたんだよ、またモジモジして。\nトイレなら早く行けよ、体に良くないぞ？
216 = "どうしたんだよ、またモジモジして。\\nトイレなら早く行けよ、体に良くないぞ？"

# めぐみん
# 行けたら苦労しませんよ……。
247 = "行けたら苦労しませんよ……。"

# カズマ
# え？\nもしかして本当にトイレなのか？
200 = "え？\\nもしかして本当にトイレなのか？"

# めぐみん
# ……はい。
193 = "……はい。"

# カズマ
# 紅魔族はトイレに\n行かないんじゃなかったか？
246 = "紅魔族はトイレに\\n行かないんじゃなかったか？"

# めぐみん
# それは都市伝説です。
210 = "それは都市伝説です。"

# カズマ
# 都合がいいな、お前。
252 = "都合がいいな、お前。"

# カズマ
# つかさ、ここまで来られたんだから\nトイレにも行けただろ。\nむしろ、こっちの方が遠いじゃないか。
213 = "つかさ、ここまで来られたんだから\\nトイレにも行けただろ。\\nむしろ、こっちの方が遠いじゃないか。"

# めぐみん
# だ、だって、１人で暗いトイレに入るなんて\n怖いじゃないですか。
211 = "だ、だって、１人で暗いトイレに入るなんて\\n怖いじゃないですか。"

# カズマ
# ま、今の状況が状況だしな。
225 = "ま、今の状況が状況だしな。"

# めぐみん
# は、はい、そこでカズマを男と見込んで\nお願いがあります。
221 = "は、はい、そこでカズマを男と見込んで\\nお願いがあります。"

# カズマ
# まさか、一緒にトイレに入れっていうのか？
226 = "まさか、一緒にトイレに入れっていうのか？"

# めぐみん
# ……撃っていいですか？
194 = "……撃っていいですか？"

# カズマ
# 撃つな！\nじゃあ、どうしろっていうんだよ？
241 = "撃つな！\\nじゃあ、どうしろっていうんだよ？"

# めぐみん
# と、トイレの前で待っていて欲しいんです。\nあ、でも、音とか聞いたら怒りますからね。
215 = "と、トイレの前で待っていて欲しいんです。\\nあ、でも、音とか聞いたら怒りますからね。"

# カズマ
# ワガママだなお前！
234 = "ワガママだなお前！"

# カズマ
# そこに花瓶があるぞ。
206 = "そこに花瓶があるぞ。"

# めぐみん
# は？
224 = "は？"

# カズマ
# いやだってめぐみん前に俺にさ、\n花瓶をお勧めしたじゃん。
196 = "いやだってめぐみん前に俺にさ、\\n花瓶をお勧めしたじゃん。"

# めぐみん
# 言っていいと冗談と悪い冗談がありますよ！？\n変態な上に最低です！　最悪です！
249 = "言っていいと冗談と悪い冗談がありますよ！？\\n変態な上に最低です！　最悪です！"

# カズマ
# わ、悪かったよ。\nそれで、トイレまでついていくだけでいいのか？
228 = "わ、悪かったよ。\\nそれで、トイレまでついていくだけでいいのか？"

# めぐみん
# 見張りもお願いします。\nあと、もし何か出たら、全力で守ってください。
248 = "見張りもお願いします。\\nあと、もし何か出たら、全力で守ってください。"

# カズマ
# 人を都合よく使うな！
237 = "人を都合よく使うな！"

# カズマ
# 俺にどうして欲しいんだよ。
239 = "俺にどうして欲しいんだよ。"

# めぐみん
# トイレの前で見張りをしてもらえませんか？
233 = "トイレの前で見張りをしてもらえませんか？"

# カズマ
# はあ？\n見張りって、ひとりで立ってろっていうのか？
222 = "はあ？\\n見張りって、ひとりで立ってろっていうのか？"

# めぐみん
# そうです。\nでも音を聞いたら怒りますし、\nあることないこと言いふらします。
204 = "そうです。\\nでも音を聞いたら怒りますし、\\nあることないこと言いふらします。"

# カズマ
# 鬼だなお前！
253 = "鬼だなお前！"

# めぐみん
# うぅ～……。\nそろそろ限界です……早く行きましょう。
197 = "うぅ～……。\\nそろそろ限界です……早く行きましょう。"

# カズマ
# はいはい、わかったよ。
223 = "はいはい、わかったよ。"

[selections]
235 = "一緒にトイレに入れっていうのか？"
205 = "そこに花瓶があるぞ"
238 = "俺にどうして欲しいんだよ"
