# root_c42.txt.scn

[info]
0 = ""

[characters]
268 = "カズマ（Ｍ）"
259 = "めぐみん"
266 = "カズマ"
271 = "ダクネス"
263 = "アクア"

[character_subs]
# 266 = "カズマ"

[script]
# lines: 54

# カズマ（Ｍ）
# display as カズマ
# （それからの俺達は、一攫千金を目指し、\n　クエストで忙しい日々を過ごしていた）
315 = "（それからの俺達は、一攫千金を目指し、\\n　クエストで忙しい日々を過ごしていた）"

# めぐみん
# キノコ採取のクエスト……。\n実に地味ですね。\n爆裂魔法を撃つ機会がありません。
269 = "キノコ採取のクエスト……。\\n実に地味ですね。\\n爆裂魔法を撃つ機会がありません。"

# カズマ
# 仕方ねーだろ？\n他は、俺達の手に余る\n難易度が高いクエストばっかりだったんだから。
274 = "仕方ねーだろ？\\n他は、俺達の手に余る\\n難易度が高いクエストばっかりだったんだから。"

# めぐみん
# 私はそれでも構いませんよ！\n爆裂魔法さえ撃てたら！
310 = "私はそれでも構いませんよ！\\n爆裂魔法さえ撃てたら！"

# カズマ
# お前はいい加減、他にも役に立つ魔法を覚えろ！
240 = "お前はいい加減、他にも役に立つ魔法を覚えろ！"

# めぐみん
# 嫌です！
281 = "嫌です！"

# カズマ
# 即答かよ！！
277 = "即答かよ！！"

# ダクネス
# まぁまぁ、そう言ってやるな。\nそれがめぐみんの個性なんだ。
256 = "まぁまぁ、そう言ってやるな。\\nそれがめぐみんの個性なんだ。"

# ダクネス
# うちのパーティーは\n個性的なメンバーばかりだが、\nそれが強みでもあるんだぞ。
238 = "うちのパーティーは\\n個性的なメンバーばかりだが、\\nそれが強みでもあるんだぞ。"

# カズマ（Ｍ）
# display as カズマ
# （お前も、その個性的すぎるうちの\n　１人だけどな？）
314 = "（お前も、その個性的すぎるうちの\\n　１人だけどな？）"

# アクア
# あら、こんなところにちっちゃいキノコが。\nふふん、あなたもこの私のお金になりなさい？
235 = "あら、こんなところにちっちゃいキノコが。\\nふふん、あなたもこの私のお金になりなさい？"

# ダクネス
# アクア、張り切っているな。
264 = "アクア、張り切っているな。"

# カズマ
# キャベツの時もそうだったけど、\nあいつは金になることには積極的だからなぁ。
270 = "キャベツの時もそうだったけど、\\nあいつは金になることには積極的だからなぁ。"

# アクア
# ふふっ、この毒々しい色！\nきっと素晴らしい効果があるキノコに違いないわ！
254 = "ふふっ、この毒々しい色！\\nきっと素晴らしい効果があるキノコに違いないわ！"

# カズマ（Ｍ）
# display as カズマ
# （いやいや、絶対あれは毒キノコだ。\n　金にならなくて泣く未来が目に浮かぶぜ）
313 = "（いやいや、絶対あれは毒キノコだ。\\n　金にならなくて泣く未来が目に浮かぶぜ）"

# アクア
# ……あ！\n向こうの方から\n何か芳醇なキノコの香りがするわ。
229 = "……あ！\\n向こうの方から\\n何か芳醇なキノコの香りがするわ。"

# カズマ
# おーい、アクアー。\n１人で遠くに行くなよー？
239 = "おーい、アクアー。\\n１人で遠くに行くなよー？"

# アクア
# わかってるわよ。
260 = "わかってるわよ。"

# ダクネス
# そういえば、今回の採取クエストは\nやけに報酬がよかったな。
249 = "そういえば、今回の採取クエストは\\nやけに報酬がよかったな。"

# カズマ
# ああ、基本報酬は\nキノコの取れ高なんだけど――
232 = "ああ、基本報酬は\\nキノコの取れ高なんだけど――"

# カズマ
# この森は強いモンスターが出るって\n言われていて、危険手当も込みなんだよ。
245 = "この森は強いモンスターが出るって\\n言われていて、危険手当も込みなんだよ。"

# めぐみん
# でも、出てくる気配がないじゃないですか。\nこれでは爆裂魔法が撃てません。
252 = "でも、出てくる気配がないじゃないですか。\\nこれでは爆裂魔法が撃てません。"

# カズマ
# 平和に終わるんだったら、それでいいだろ。
284 = "平和に終わるんだったら、それでいいだろ。"

# アクア
# いーーーやぁーーーーーーーっ！！
236 = "いーーーやぁーーーーーーーっ！！"

# カズマ（Ｍ）
# display as カズマ
# （あー……。\n　ものすごく嫌な予感がする）
312 = "（あー……。\\n　ものすごく嫌な予感がする）"

# ダクネス
# これはアクアの悲鳴だ！\n何かあったのか？
247 = "これはアクアの悲鳴だ！\\n何かあったのか？"

# めぐみん
# ふん、ついに我が爆裂魔法の炸裂する時が\nやってきたようですっ！
255 = "ふん、ついに我が爆裂魔法の炸裂する時が\\nやってきたようですっ！"

# アクア
# 助けてっ！　カズマぁっ！
276 = "助けてっ！　カズマぁっ！"

# カズマ
# うおおおおっ！\n変なもん引き連れて来んなーー！！
237 = "うおおおおっ！\\n変なもん引き連れて来んなーー！！"

# ダクネス
# みんな下がっていろっ！！\nはあぁぁぁっ！！
258 = "みんな下がっていろっ！！\\nはあぁぁぁっ！！"

# カズマ
# だっ、ダクネス！？
250 = "だっ、ダクネス！？"

# ダクネス
# みんなを守るのが、クルセイダーの役目だ！！
257 = "みんなを守るのが、クルセイダーの役目だ！！"

# カズマ
# って剣捨ててんじゃねーか！\n戦う気はねーのかよ！？
251 = "って剣捨ててんじゃねーか！\\n戦う気はねーのかよ！？"

# ダクネス
# ぐっ！？\nなかなかいい攻撃じゃないか！
243 = "ぐっ！？\\nなかなかいい攻撃じゃないか！"

# ダクネス
# さあ！\n私がやられて、いや、\n敵を引きつけているうちに逃げろ！！
248 = "さあ！\\n私がやられて、いや、\\n敵を引きつけているうちに逃げろ！！"

# カズマ
# バッ、バカ！　置いていけるかよ！！
272 = "バッ、バカ！　置いていけるかよ！！"

# めぐみん
# ああ、鎧が！
233 = "ああ、鎧が！"

# ダクネス
# くっ、なんて強力な攻撃なんだ……！
242 = "くっ、なんて強力な攻撃なんだ……！"

# ダクネス
# んぅぅっ！\nいいぞぉ……今のはとても気持ち、\nじゃない、危なかったぞっ！
262 = "んぅぅっ！\\nいいぞぉ……今のはとても気持ち、\\nじゃない、危なかったぞっ！"

# カズマ（Ｍ）
# display as カズマ
# （って、こんなピンチな状況なのに\n　悦んでんじゃねーよ！）
316 = "（って、こんなピンチな状況なのに\\n　悦んでんじゃねーよ！）"

# ダクネス
# こ、このモンスターはなかなかの強敵だな！\n想像以上の攻撃力だ！
244 = "こ、このモンスターはなかなかの強敵だな！\\n想像以上の攻撃力だ！"

# ダクネス
# あぁぁっ！！　まだまだぁぁっ！！
231 = "あぁぁっ！！　まだまだぁぁっ！！"

# カズマ（Ｍ）
# display as カズマ
# （ああ、結局はこのパターンなんだな。\n　まったく、この収拾はどうつければいいんだ？）
311 = "（ああ、結局はこのパターンなんだな。\\n　まったく、この収拾はどうつければいいんだ？）"

# アクア
# ね、ねぇダクネス？\n助けなくてもいいの？
253 = "ね、ねぇダクネス？\\n助けなくてもいいの？"

# めぐみん
# カズマ！\n敵のそばにダクネスがいるので\n爆裂魔法で攻撃できません！
267 = "カズマ！\\n敵のそばにダクネスがいるので\\n爆裂魔法で攻撃できません！"

# ダクネス
# 構わんっ！！\n私もろともヤツをぶっ飛ばしてくれ！！
286 = "構わんっ！！\\n私もろともヤツをぶっ飛ばしてくれ！！"

# めぐみん
# ……ええと、どうします？
230 = "……ええと、どうします？"

# カズマ
# 撃て。
285 = "撃て。"

# めぐみん
# わかりました。\n撃った後はよろしくお願いします。
261 = "わかりました。\\n撃った後はよろしくお願いします。"

# めぐみん
# エクスプロージョンッ！！！
265 = "エクスプロージョンッ！！！"

# ダクネス
# ああああっ……こっ、これだぁぁぁぁぁ！！！
234 = "ああああっ……こっ、これだぁぁぁぁぁ！！！"

# ダクネス
# これこそ、クルセイダーの醍醐味っ！！\nあぁぁぁぁぁぁぁ……！
246 = "これこそ、クルセイダーの醍醐味っ！！\\nあぁぁぁぁぁぁぁ……！"

# カズマ
# お前は真面目なクルセイダー達に謝れーー！
241 = "お前は真面目なクルセイダー達に謝れーー！"

# カズマ（Ｍ）
# display as カズマ
# （はぁ……。\n　まともなパーティーメンバーが欲しい）
317 = "（はぁ……。\\n　まともなパーティーメンバーが欲しい）"

