# root_c06.txt.scn

[info]
0 = ""

[characters]
160 = "カズマ（Ｍ）"
161 = "ダクネス"
159 = "カズマ"

[character_subs]
# 159 = "カズマ"

[script]
# lines: 38

# カズマ（Ｍ）
# display as カズマ
# （ったく、何だったんだよ。\n　まぁ、逃げといて正解だろうな。\n　もうトラブルに巻き込まれるのは嫌だ）
196 = "（ったく、何だったんだよ。\\n　まぁ、逃げといて正解だろうな。\\n　もうトラブルに巻き込まれるのは嫌だ）"

# カズマ（Ｍ）
# display as カズマ
# （さて、財布は。\n　って……小銭しか入ってねえし）
195 = "（さて、財布は。\\n　って……小銭しか入ってねえし）"

# カズマ（Ｍ）
# display as カズマ
# （はあ、早くスカルドラゴン討伐の報酬が\n　入ってこねえかな）
204 = "（はあ、早くスカルドラゴン討伐の報酬が\\n　入ってこねえかな）"

# カズマ（Ｍ）
# display as カズマ
# （いや、そんなものを待ってちゃいけないんだ！\n　今からでもクエストを！）
192 = "（いや、そんなものを待ってちゃいけないんだ！\\n　今からでもクエストを！）"

# カズマ（Ｍ）
# display as カズマ
# （でも、気力が湧かねぇ。\n　それもこれも、指輪のせいだよな）
198 = "（でも、気力が湧かねぇ。\\n　それもこれも、指輪のせいだよな）"

# カズマ（Ｍ）
# display as カズマ
# （指輪を外すために、あれやこれやと\n　金を稼ぐ方法を試してみたんだが、\n　どれもいまいちで――）
210 = "（指輪を外すために、あれやこれやと\\n　金を稼ぐ方法を試してみたんだが、\\n　どれもいまいちで――）"

# カズマ（Ｍ）
# display as カズマ
# （結局、体を張った冒険者の仕事が\n　１番稼げる結果になったわけだ）
212 = "（結局、体を張った冒険者の仕事が\\n　１番稼げる結果になったわけだ）"

# カズマ（Ｍ）
# display as カズマ
# （いったい努力ってなんなんだ。\n　体を張ることが一番利益に繋がるって\n　文化が遅れてるにもほどがあるだろ）
191 = "（いったい努力ってなんなんだ。\\n　体を張ることが一番利益に繋がるって\\n　文化が遅れてるにもほどがあるだろ）"

# カズマ（Ｍ）
# display as カズマ
# （なんて文句を言っても仕方ないよな。\n　ここはそういう世界なんだし）
202 = "（なんて文句を言っても仕方ないよな。\\n　ここはそういう世界なんだし）"

# カズマ（Ｍ）
# display as カズマ
# （でも……）
197 = "（でも……）"

# カズマ（Ｍ）
# display as カズマ
# （努力が報われないって辛いわー）
209 = "（努力が報われないって辛いわー）"

# カズマ（Ｍ）
# display as カズマ
# （もうこのまま、部屋でじっとしていたい。\n　一生、俺の面倒を見てくれる誰かが\n　現れないかなぁ……）
207 = "（もうこのまま、部屋でじっとしていたい。\\n　一生、俺の面倒を見てくれる誰かが\\n　現れないかなぁ……）"

# カズマ（Ｍ）
# display as カズマ
# （はっ！？　いかんいかん！！\n　このままじゃ本当にダメになっちまう！）
205 = "（はっ！？　いかんいかん！！\\n　このままじゃ本当にダメになっちまう！）"

# カズマ（Ｍ）
# display as カズマ
# （とりあえず外に出よう！\n　気分転換でもしたら、\n　きっと何かいいことがあるさ！）
199 = "（とりあえず外に出よう！\\n　気分転換でもしたら、\\n　きっと何かいいことがあるさ！）"

# ダクネス
# あっ！？
151 = "あっ！？"

# カズマ
# おっと！　ダクネスいたのか。
154 = "おっと！　ダクネスいたのか。"

# ダクネス
# あ、ああ、カズマに用事があってな。
148 = "あ、ああ、カズマに用事があってな。"

# カズマ
# 俺に？
164 = "俺に？"

# カズマ（Ｍ）
# display as カズマ
# （さっきこそこそ話していた何かのことか？）
194 = "（さっきこそこそ話していた何かのことか？）"

# カズマ（Ｍ）
# display as カズマ
# （正直、関わりたくないわー）
211 = "（正直、関わりたくないわー）"

# ダクネス
# 大した事ではないのだが……その。
166 = "大した事ではないのだが……その。"

# カズマ（Ｍ）
# display as カズマ
# （ん、んん？）
208 = "（ん、んん？）"

# ダクネス
# い、いや、やっぱり、こういうのは……。
152 = "い、いや、やっぱり、こういうのは……。"

# カズマ（Ｍ）
# display as カズマ
# （なんだ？\n　またいつものアレな妄想を\n　俺にぶつけてくるのか？）
201 = "（なんだ？\\n　またいつものアレな妄想を\\n　俺にぶつけてくるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、でもそんなネタ振りしてないぞ？\n　もしかして、さっき\n　３人で話してたことと関係があるのか？）
193 = "（いや、でもそんなネタ振りしてないぞ？\\n　もしかして、さっき\\n　３人で話してたことと関係があるのか？）"

# ダクネス
# と、ところでカズマ、どこかに出かけるのか？
156 = "と、ところでカズマ、どこかに出かけるのか？"

# カズマ
# ああ、ちょっと気分転換しようと思ってさ。
150 = "ああ、ちょっと気分転換しようと思ってさ。"

# ダクネス
# 気分転換だと！？
169 = "気分転換だと！？"

# カズマ
# えっ！？
153 = "えっ！？"

# カズマ（Ｍ）
# display as カズマ
# （な、なんだ？\n　なんでそこに食いついてくるんだ！？）
200 = "（な、なんだ？\\n　なんでそこに食いついてくるんだ！？）"

# ダクネス
# そんなにも、やはり相当……。\nここは私がやるしかない。
155 = "そんなにも、やはり相当……。\\nここは私がやるしかない。"

# カズマ
# ダクネス？\nおーい、どうかしたのか？
162 = "ダクネス？\\nおーい、どうかしたのか？"

# ダクネス
# はっ！？\nいや、大丈夫だ！　なんでもない！
158 = "はっ！？\\nいや、大丈夫だ！　なんでもない！"

# カズマ（Ｍ）
# display as カズマ
# （まったく大丈夫そうに見えないのは\n　気のせいか？）
206 = "（まったく大丈夫そうに見えないのは\\n　気のせいか？）"

# ダクネス
# な、なあ、私も一緒に行っていいだろうか？
157 = "な、なあ、私も一緒に行っていいだろうか？"

# カズマ
# 構わねーけど、ただの散歩みたいなもんだぞ？
168 = "構わねーけど、ただの散歩みたいなもんだぞ？"

# ダクネス
# ああ、それでもいい。
149 = "ああ、それでもいい。"

# カズマ（Ｍ）
# display as カズマ
# （なんなんだよ、いったい）
203 = "（なんなんだよ、いったい）"

