# root_f30.txt.scn

[info]
0 = ""

[characters]
246 = "カズマ（Ｍ）"
242 = "ウィズ"
243 = "カズマ"
247 = "クリス"

[character_subs]
# 243 = "カズマ"

[script]
# lines: 66

# カズマ（Ｍ）
# display as カズマ
# （そして、数日が過ぎ――\n　俺は、相変わらず\n　ウィズの店の手伝いを続けていた）
274 = "（そして、数日が過ぎ――\\n　俺は、相変わらず\\n　ウィズの店の手伝いを続けていた）"

# ウィズ
# カズマさん。
244 = "カズマさん。"

# カズマ
# ん？　なんだ？
240 = "ん？　なんだ？"

# ウィズ
# 先日のお礼です。\nこれ、どうぞ。
250 = "先日のお礼です。\\nこれ、どうぞ。"

# カズマ
# え？\nお礼って、別にそんなのいいのに。\nこれもウィズの自腹だろ？
210 = "え？\\nお礼って、別にそんなのいいのに。\\nこれもウィズの自腹だろ？"

# ウィズ
# 大丈夫ですよ。\nギルドから、あの除霊の特別報酬が出たんです。
256 = "大丈夫ですよ。\\nギルドから、あの除霊の特別報酬が出たんです。"

# ウィズ
# カズマさんもお手伝いくださったのですから、\n遠慮なく受け取ってください。
245 = "カズマさんもお手伝いくださったのですから、\\n遠慮なく受け取ってください。"

# カズマ
# まあ、それじゃ、せっかくの気持ちだし……\nありがたくもらうよ。\n今開けてもいいか？
237 = "まあ、それじゃ、せっかくの気持ちだし……\\nありがたくもらうよ。\\n今開けてもいいか？"

# ウィズ
# ええ、どうぞ。
209 = "ええ、どうぞ。"

# カズマ
# うわっ！　すごいなこれ！\nブレスレットか！
204 = "うわっ！　すごいなこれ！\\nブレスレットか！"

# ウィズ
# はい。\nカズマさんに似合うんじゃないかと思いまして。
232 = "はい。\\nカズマさんに似合うんじゃないかと思いまして。"

# ウィズ
# あ、でも、私が勝手に選んだので、\nカズマさんのセンスに合うかどうか……。
197 = "あ、でも、私が勝手に選んだので、\\nカズマさんのセンスに合うかどうか……。"

# カズマ
# いや、これいいと思うぜ！\n豪華な装飾でカッコいい！
203 = "いや、これいいと思うぜ！\\n豪華な装飾でカッコいい！"

# ウィズ
# ああ、よかった。\n気に入って頂けたみたいで安心しました。
199 = "ああ、よかった。\\n気に入って頂けたみたいで安心しました。"

# カズマ
# でもこれさ、\nけっこういい値段したんじゃないか？\nもしかして、またぼったくられたとか。
224 = "でもこれさ、\\nけっこういい値段したんじゃないか？\\nもしかして、またぼったくられたとか。"

# カズマ
# はっ！？\n下手したら、この前の指輪みたいな\n呪いのアイテムだったりとか！？
233 = "はっ！？\\n下手したら、この前の指輪みたいな\\n呪いのアイテムだったりとか！？"

# ウィズ
# 大丈夫ですよ。\nちゃんとしたところで買いましたから。
255 = "大丈夫ですよ。\\nちゃんとしたところで買いましたから。"

# カズマ
# ははは、冗談だって。\nそれじゃ、ちょっと付けてみるか。
234 = "ははは、冗談だって。\\nそれじゃ、ちょっと付けてみるか。"

# カズマ
# うん、つけ心地もいい感じだ。\n気に入ったよ、ウィズ。
205 = "うん、つけ心地もいい感じだ。\\n気に入ったよ、ウィズ。"

# ウィズ
# ……あら？\nなんでしょう、急に気分が……。
196 = "……あら？\\nなんでしょう、急に気分が……。"

# カズマ
# どうしたんだ？\n顔、真っ青だぞ？
227 = "どうしたんだ？\\n顔、真っ青だぞ？"

# ウィズ
# あっ！\nい、いやっ、きゃああっ！！
201 = "あっ！\\nい、いやっ、きゃああっ！！"

# カズマ
# だ、大丈夫か、ウィズ！？
221 = "だ、大丈夫か、ウィズ！？"

# ウィズ
# こ、来ないでっ。\nこっちに来ないで下さいっ！
214 = "こ、来ないでっ。\\nこっちに来ないで下さいっ！"

# カズマ
# ど、どういうこと？\n俺、何かした？
226 = "ど、どういうこと？\\n俺、何かした？"

# ウィズ
# か、カズマさんのせいではないと思いますけど、\nその、近づかれると……肌がチリチリして！
212 = "か、カズマさんのせいではないと思いますけど、\\nその、近づかれると……肌がチリチリして！"

# カズマ
# チリチリ？\n聖水を被った時にもそんな事言ってたな。
248 = "チリチリ？\\n聖水を被った時にもそんな事言ってたな。"

# ウィズ
# ああ、それです！\nカズマさんが近づくと、\nそれがどんどん強くなるんです！
198 = "ああ、それです！\\nカズマさんが近づくと、\\nそれがどんどん強くなるんです！"

# カズマ（Ｍ）
# display as カズマ
# （まさか、もしかして……）
275 = "（まさか、もしかして……）"

# クリス
# こんにちはー……通報した方がいいかな？
215 = "こんにちはー……通報した方がいいかな？"

# カズマ
# なんもしてねーよ！
228 = "なんもしてねーよ！"

# クリス
# じゃあ、今のこの状況ってなんなのさ。
216 = "じゃあ、今のこの状況ってなんなのさ。"

# カズマ
# それが俺にもよくわからないんだよ。\n俺がこのブレスレットをつけたら、\n急にこんな状況になっちゃったんだ。
219 = "それが俺にもよくわからないんだよ。\\n俺がこのブレスレットをつけたら、\\n急にこんな状況になっちゃったんだ。"

# クリス
# あちゃー。\nそれ、アミュレットじゃないかな。
200 = "あちゃー。\\nそれ、アミュレットじゃないかな。"

# カズマ
# アミュレット？
241 = "アミュレット？"

# クリス
# 魔除けとか、神の加護のあるアイテムだよ。\nロザリオとか、そういうの。
271 = "魔除けとか、神の加護のあるアイテムだよ。\\nロザリオとか、そういうの。"

# カズマ（Ｍ）
# display as カズマ
# （魔除けかよ！　だからウィズが怖がるのか。\n　だったら、いったん外そう）
280 = "（魔除けかよ！　だからウィズが怖がるのか。\\n　だったら、いったん外そう）"

# カズマ
# って、あ、あれ？　抜けない！？
223 = "って、あ、あれ？　抜けない！？"

# ウィズ
# そ、そう言えば、お店の人が、\n一生、災厄から守ってくれる効果があるって\n言ってました……。
217 = "そ、そう言えば、お店の人が、\\n一生、災厄から守ってくれる効果があるって\\n言ってました……。"

# カズマ
# い、一生って……\nもしかしてこれ、取れないのか！？
202 = "い、一生って……\\nもしかしてこれ、取れないのか！？"

# クリス
# うーん、見た感じ、\nかなり強力な効果を持ってるね。\n強すぎて外れなくなっちゃったのかも。
208 = "うーん、見た感じ、\\nかなり強力な効果を持ってるね。\\n強すぎて外れなくなっちゃったのかも。"

# カズマ
# おいおいおいおい！\nそんな強烈な加護はいらねーよ！！
211 = "おいおいおいおい！\\nそんな強烈な加護はいらねーよ！！"

# クリス
# 装飾の紋様からすると、\nエリス様の加護が掛けられてるかな、これは。
270 = "装飾の紋様からすると、\\nエリス様の加護が掛けられてるかな、これは。"

# カズマ（Ｍ）
# display as カズマ
# （良かった、アクアじゃなくて！\n　マジで！！）
279 = "（良かった、アクアじゃなくて！\\n　マジで！！）"

# ウィズ
# ということは、エリス教の方なら\nなんとか出来るんでしょうか？
225 = "ということは、エリス教の方なら\\nなんとか出来るんでしょうか？"

# クリス
# うん、レベルの高いプリーストに頼めば\n外してもらえるんじゃない？
206 = "うん、レベルの高いプリーストに頼めば\\n外してもらえるんじゃない？"

# カズマ（Ｍ）
# display as カズマ
# （そうか、外す手段はあるのか。\n　良かった、呪いのアイテムじゃなくて）
273 = "（そうか、外す手段はあるのか。\\n　良かった、呪いのアイテムじゃなくて）"

# クリス
# ただ、解除料として\nお金は取られるだろうけど。
220 = "ただ、解除料として\\nお金は取られるだろうけど。"

# カズマ
# はああ！？\nまたかよ～！
231 = "はああ！？\\nまたかよ～！"

# クリス
# 大丈夫。\n得体の知れないアイテムじゃ無いし、\nエリス教なら流石にぼったくりはないよ。
254 = "大丈夫。\\n得体の知れないアイテムじゃ無いし、\\nエリス教なら流石にぼったくりはないよ。"

# ウィズ
# そ、そのお金は私が払いますっ！\n払わせて下さい！
218 = "そ、そのお金は私が払いますっ！\\n払わせて下さい！"

# カズマ
# んー、さすがにこれは\nそうさせてもらおうかなぁ。
238 = "んー、さすがにこれは\\nそうさせてもらおうかなぁ。"

# カズマ（Ｍ）
# display as カズマ
# （もちろんウィズが悪いわけじゃないんだが……\n　特別報酬も出たって言ってるしな）
276 = "（もちろんウィズが悪いわけじゃないんだが……\\n　特別報酬も出たって言ってるしな）"

# ウィズ
# ……あ。
195 = "……あ。"

# カズマ
# ん？　どうした？
239 = "ん？　どうした？"

# ウィズ
# 報酬に頂いたお金……\nそのブレスレットを買うのに\n全部使っちゃったんでした。
253 = "報酬に頂いたお金……\\nそのブレスレットを買うのに\\n全部使っちゃったんでした。"

# カズマ
# は？\n特別報酬、全部か？
235 = "は？\\n特別報酬、全部か？"

# ウィズ
# は、はい……。
229 = "は、はい……。"

# カズマ（Ｍ）
# display as カズマ
# （マジかよ……\n　でも、確かにウィズの金銭感覚が\n　一朝一夕で直るわけ無いよな……）
278 = "（マジかよ……\\n　でも、確かにウィズの金銭感覚が\\n　一朝一夕で直るわけ無いよな……）"

# ウィズ
# こ、これから頑張って稼ぎますから！\n任せて下さいっ！
213 = "こ、これから頑張って稼ぎますから！\\n任せて下さいっ！"

# カズマ（Ｍ）
# display as カズマ
# （いったい何ヶ月……\n　いや、何年掛かるんだろうか……）
272 = "（いったい何ヶ月……\\n　いや、何年掛かるんだろうか……）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズがまともに稼げるようになるまで、\n　俺がずっとこの店にいなきゃダメだろうなぁ）
277 = "（ウィズがまともに稼げるようになるまで、\\n　俺がずっとこの店にいなきゃダメだろうなぁ）"

# カズマ
# ま、まあ、なんだ。\n気長に待つからよろしくな、ウィズ。
236 = "ま、まあ、なんだ。\\n気長に待つからよろしくな、ウィズ。"

# ウィズ
# は、はいっ！\n私が必ず、カズマさんを助けますからっ！
230 = "は、はいっ！\\n私が必ず、カズマさんを助けますからっ！"

# ウィズ
# だからそれまでは、近づかないでください！
222 = "だからそれまでは、近づかないでください！"

# カズマ
# うん、泣くよ？
207 = "うん、泣くよ？"

