# root_c04.txt.scn

[info]
0 = ""

[characters]
188 = "アクア"
187 = "めぐみん"
190 = "ダクネス"

[character_subs]

[script]
# lines: 34

# アクア
# 暇ねぇ……。\n私も街に行ってこようかしら。
202 = "暇ねぇ……。\\n私も街に行ってこようかしら。"

# めぐみん
# それなら、私の１日１爆裂に\n付き合ってくださいよ。
176 = "それなら、私の１日１爆裂に\\n付き合ってくださいよ。"

# アクア
# それはカズマに頼みなさいよ。\n多分、そろそろ戻ってくるでしょうし。
179 = "それはカズマに頼みなさいよ。\\n多分、そろそろ戻ってくるでしょうし。"

# めぐみん
# 待ちきれません！\n今日は、昨日補充したカロリーの分、\nすごい爆裂魔法が撃てそうな気がするのです！
200 = "待ちきれません！\\n今日は、昨日補充したカロリーの分、\\nすごい爆裂魔法が撃てそうな気がするのです！"

# アクア
# 魔法とカロリーって関係あったかしら？
227 = "魔法とカロリーって関係あったかしら？"

# めぐみん
# ダクネスでもいいですよ？\n爆裂魔法を撃った後、私をここまで\n連れて帰ってくれるだけでいいですから！
191 = "ダクネスでもいいですよ？\\n爆裂魔法を撃った後、私をここまで\\n連れて帰ってくれるだけでいいですから！"

# ダクネス
# …………。
169 = "…………。"

# めぐみん
# ダクネス？　どうかしたのですか？
192 = "ダクネス？　どうかしたのですか？"

# ダクネス
# 少しカズマの様子が気になってな。
197 = "少しカズマの様子が気になってな。"

# アクア
# うーん、確かにちょっと様子がおかしかったわよね。
173 = "うーん、確かにちょっと様子がおかしかったわよね。"

# めぐみん
# あれは、寝起きで頭が回っていなかったからでは？
172 = "あれは、寝起きで頭が回っていなかったからでは？"

# ダクネス
# はたしてそれだけだろうか。
185 = "はたしてそれだけだろうか。"

# めぐみん
# どういう意味です？
182 = "どういう意味です？"

# ダクネス
# 根拠と言えるものは何もないのだが、\nただ小骨が喉に引っかかるような違和感が\nあるんだ。
203 = "根拠と言えるものは何もないのだが、\\nただ小骨が喉に引っかかるような違和感が\\nあるんだ。"

# ダクネス
# 昨夜は明らかに様子がおかしかったし、\n今朝だって随分と素直だっただろう？
201 = "昨夜は明らかに様子がおかしかったし、\\n今朝だって随分と素直だっただろう？"

# ダクネス
# それに、考えごとで寝付けなかったというのも\n気になる。
177 = "それに、考えごとで寝付けなかったというのも\\n気になる。"

# アクア
# それは気にしすぎよ。
180 = "それは気にしすぎよ。"

# めぐみん
# そうですよ。\nカズマだって一応人間なのですから、\n悩み事のひとつくらいあってもおかしくありません。
175 = "そうですよ。\\nカズマだって一応人間なのですから、\\n悩み事のひとつくらいあってもおかしくありません。"

# ダクネス
# （悩み事か……）
232 = "（悩み事か……）"

# めぐみん
# あ、そういえば。
170 = "あ、そういえば。"

# めぐみん
# カズマの様子がおかしいことに\n関係があるかどうかわかりませんが、\nちょっと思い出したことがあります。
189 = "カズマの様子がおかしいことに\\n関係があるかどうかわかりませんが、\\nちょっと思い出したことがあります。"

# ダクネス
# なんだ、それは？
183 = "なんだ、それは？"

# めぐみん
# 何日か前の夜、カズマが庭でひとり、\nぼーっとしていたのを見ました。\n夜空を見上げて、深いため息をついてましたね。
194 = "何日か前の夜、カズマが庭でひとり、\\nぼーっとしていたのを見ました。\\n夜空を見上げて、深いため息をついてましたね。"

# めぐみん
# なんだか、いつものカズマらしくない\n表情だったので、何かに\n取り憑かれているのかと思いましたよ。
184 = "なんだか、いつものカズマらしくない\\n表情だったので、何かに\\n取り憑かれているのかと思いましたよ。"

# ダクネス
# まさか！\nまた悪霊のたぐいに？
186 = "まさか！\\nまた悪霊のたぐいに？"

# アクア
# それはないわね。\n悪霊やアンデットがこの家に侵入してきたら、\n私、すぐわかるし。
178 = "それはないわね。\\n悪霊やアンデットがこの家に侵入してきたら、\\n私、すぐわかるし。"

# アクア
# きっと、ろくでもない妄想でもしてたのよ。\n俺は天下を取る！　とか\nできもしないことを考えて悦に浸ってたんでしょ。
174 = "きっと、ろくでもない妄想でもしてたのよ。\\n俺は天下を取る！　とか\\nできもしないことを考えて悦に浸ってたんでしょ。"

# ダクネス
# （カズマがそんな行動を取っていたとは。\n　やはり、何か悩み事があるのか？）
230 = "（カズマがそんな行動を取っていたとは。\\n　やはり、何か悩み事があるのか？）"

# ダクネス
# （このまま仲間を放っておくなど\n　私にはできない）
229 = "（このまま仲間を放っておくなど\\n　私にはできない）"

# ダクネス
# （ああ見えて、カズマは繊細なところもある。\n　誰にも相談できないのかもしれない）
228 = "（ああ見えて、カズマは繊細なところもある。\\n　誰にも相談できないのかもしれない）"

# ダクネス
# （共に歩んでいる仲間として、カズマのために\n　何かしてあげられることはないだろうか？）
231 = "（共に歩んでいる仲間として、カズマのために\\n　何かしてあげられることはないだろうか？）"

# ダクネス
# ちょっといいか？\n２人に相談したいことがあるんだが。
181 = "ちょっといいか？\\n２人に相談したいことがあるんだが。"

# めぐみん
# 相談ですか？
226 = "相談ですか？"

# ダクネス
# ああ、実は――
171 = "ああ、実は――"

