# root_b23.txt.scn

[info]
0 = ""

[characters]
211 = "カズマ（Ｍ）"
204 = "めぐみん"
207 = "カズマ"
205 = "ウィズ"

[character_subs]
# 207 = "カズマ"

[script]
# lines: 42

# カズマ（Ｍ）
# display as カズマ
# （その日、夜遅くに戻った俺達を\n　心配そうな顔をしたダクネスとアクアが\n　出迎えてくれた）
240 = "（その日、夜遅くに戻った俺達を\\n　心配そうな顔をしたダクネスとアクアが\\n　出迎えてくれた）"

# カズマ（Ｍ）
# display as カズマ
# （当然だが、なにがあったのかと問い詰められ、\n　結婚式のことは伏せて説明した）
244 = "（当然だが、なにがあったのかと問い詰められ、\\n　結婚式のことは伏せて説明した）"

# カズマ（Ｍ）
# display as カズマ
# （そして数日後……）
239 = "（そして数日後……）"

# めぐみん
# 本当にいいんですか？\n本当にいいんですね？
222 = "本当にいいんですか？\\n本当にいいんですね？"

# カズマ
# ああ、そういう約束だからな。
185 = "ああ、そういう約束だからな。"

# めぐみん
# では、お言葉に甘えて選ばせてもらいます！
196 = "では、お言葉に甘えて選ばせてもらいます！"

# カズマ（Ｍ）
# display as カズマ
# （教会事件から数日、\n　どういうわけか、めぐみんはずっと\n　ご機嫌斜めだった）
246 = "（教会事件から数日、\\n　どういうわけか、めぐみんはずっと\\n　ご機嫌斜めだった）"

# カズマ（Ｍ）
# display as カズマ
# （理由を聞いても頬を膨らませるだけで\n　答えてくれない）
248 = "（理由を聞いても頬を膨らませるだけで\\n　答えてくれない）"

# カズマ（Ｍ）
# display as カズマ
# （わかるのは、原因が俺にあるってことくらい）
241 = "（わかるのは、原因が俺にあるってことくらい）"

# カズマ（Ｍ）
# display as カズマ
# （放っておけばそのうち機嫌も直るだろうと\n　放置してたけど、悪化するばかり）
245 = "（放っておけばそのうち機嫌も直るだろうと\\n　放置してたけど、悪化するばかり）"

# カズマ（Ｍ）
# display as カズマ
# （ギスギスした空気の中\n　一緒に暮らし続ける限界を感じ、\n　こっちから折れることにした）
242 = "（ギスギスした空気の中\\n　一緒に暮らし続ける限界を感じ、\\n　こっちから折れることにした）"

# カズマ（Ｍ）
# display as カズマ
# （早い話、欲しい物をプレゼントして\n　機嫌を取ろう作戦だ）
247 = "（早い話、欲しい物をプレゼントして\\n　機嫌を取ろう作戦だ）"

# カズマ（Ｍ）
# display as カズマ
# （多少、懐にダメージは受けるだろうが\n　この際、仕方がない）
243 = "（多少、懐にダメージは受けるだろうが\\n　この際、仕方がない）"

# めぐみん
# カズマ！\nこのロッドがいいです！
210 = "カズマ！\\nこのロッドがいいです！"

# カズマ
# ああ、それでいいんだな？\nんじゃ、会計を――
186 = "ああ、それでいいんだな？\\nんじゃ、会計を――"

# めぐみん
# まだですよ！\n私の本気はこの程度ではありません！
203 = "まだですよ！\\n私の本気はこの程度ではありません！"

# めぐみん
# これも、あれも捨てがたい！\nおお、これもなかなかの一品！
191 = "これも、あれも捨てがたい！\\nおお、これもなかなかの一品！"

# めぐみん
# どれにするか目移りしますね。\nいえ、この際、１つとは言わず\nすべて買いましょう！
199 = "どれにするか目移りしますね。\\nいえ、この際、１つとは言わず\\nすべて買いましょう！"

# カズマ
# はあっ！？
201 = "はあっ！？"

# めぐみん
# 文句があるんですか？\nカズマ、買う物の個数の制限を\nしませんでしたよね？
221 = "文句があるんですか？\\nカズマ、買う物の個数の制限を\\nしませんでしたよね？"

# カズマ
# そ、それはそうだけどさ……。
194 = "そ、それはそうだけどさ……。"

# めぐみん
# では、そういうことで！\n欲しい物はすべて選ばせてもらいますからね！
197 = "では、そういうことで！\\n欲しい物はすべて選ばせてもらいますからね！"

# カズマ
# ウィズ。\nあれ、いくらするんだ？
206 = "ウィズ。\\nあれ、いくらするんだ？"

# ウィズ
# 物によって値段は異なりますけれど、\n一番高い物で３００万エリスですね。
223 = "物によって値段は異なりますけれど、\\n一番高い物で３００万エリスですね。"

# カズマ
# さ、３００万エリスぅ！？
192 = "さ、３００万エリスぅ！？"

# ウィズ
# カズマさんのおかげで、\n久しぶりに利益を上げることができそうです。\nありがとうございます。
209 = "カズマさんのおかげで、\\n久しぶりに利益を上げることができそうです。\\nありがとうございます。"

# カズマ
# いやいや、待て待て！
187 = "いやいや、待て待て！"

# めぐみん
# ほうほう、これは掘り出し物ですね。\nこんな物が眠っていたなんて驚きです。
202 = "ほうほう、これは掘り出し物ですね。\\nこんな物が眠っていたなんて驚きです。"

# カズマ
# でもお高いんでしょう？
198 = "でもお高いんでしょう？"

# ウィズ
# １５００万エリスになります。
251 = "１５００万エリスになります。"

# カズマ
# １５００万エリスて、\nちょっとした家が買えるぞ！？
250 = "１５００万エリスて、\\nちょっとした家が買えるぞ！？"

# カズマ
# ストップ！\nストップだ、めぐみん！
212 = "ストップ！\\nストップだ、めぐみん！"

# めぐみん
# ええ？\nいいところだというのになんですか？
188 = "ええ？\\nいいところだというのになんですか？"

# カズマ
# さすがにそんな金はない！\nもっと安い物！　安い物にしてくれ！
193 = "さすがにそんな金はない！\\nもっと安い物！　安い物にしてくれ！"

# めぐみん
# 好きな物を買ってやると言ったのは\nカズマじゃないですか。
218 = "好きな物を買ってやると言ったのは\\nカズマじゃないですか。"

# カズマ
# それはそうなんだが、桁が違うだろ！
195 = "それはそうなんだが、桁が違うだろ！"

# カズマ
# あ、そうだ、甘い物にしようぜ？\n腹いっぱいのスイーツなんて最高だろ？
184 = "あ、そうだ、甘い物にしようぜ？\\n腹いっぱいのスイーツなんて最高だろ？"

# めぐみん
# はああ……。\nこの肌触り、最高でぇす……。
200 = "はああ……。\\nこの肌触り、最高でぇす……。"

# めぐみん
# この極上のロッドで打つ爆裂魔法は\nさぞ素晴らしいことでしょう……。
190 = "この極上のロッドで打つ爆裂魔法は\\nさぞ素晴らしいことでしょう……。"

# カズマ（Ｍ）
# display as カズマ
# （聞いちゃいねえ！）
249 = "（聞いちゃいねえ！）"

# めぐみん
# カズマ、さっそく練習に行きましょう！\n今までとは格の違う爆裂魔法を見せてあげますよ！
208 = "カズマ、さっそく練習に行きましょう！\\n今までとは格の違う爆裂魔法を見せてあげますよ！"

# カズマ
# か、勘弁してくれぇぇぇぇぇぇ！！
189 = "か、勘弁してくれぇぇぇぇぇぇ！！"

