# root_c07.txt.scn

[info]
0 = ""

[characters]
292 = "カズマ（Ｍ）"
294 = "ダクネス"
290 = "カズマ"

[character_subs]
# 290 = "カズマ"

[script]
# lines: 92

# カズマ（Ｍ）
# display as カズマ
# （本当は街にでも行こうと思ったけど、\n　なんとなく流れで、街外れの川沿いを\n　２人で散策することになった）
345 = "（本当は街にでも行こうと思ったけど、\\n　なんとなく流れで、街外れの川沿いを\\n　２人で散策することになった）"

# カズマ（Ｍ）
# display as カズマ
# （まぁ、考え事をするなら\n　雑踏より静かなところがいいだろうしな）
335 = "（まぁ、考え事をするなら\\n　雑踏より静かなところがいいだろうしな）"

# カズマ（Ｍ）
# display as カズマ
# （だが……）
326 = "（だが……）"

# ダクネス
# 今日は、いい天気だな。
297 = "今日は、いい天気だな。"

# カズマ（Ｍ）
# display as カズマ
# （なんか距離が近いんですけど！）
331 = "（なんか距離が近いんですけど！）"

# ダクネス
# こんな風に、のんびりと過ごすのも久しぶりだ。\n今までは実に慌ただしかったからな。
260 = "こんな風に、のんびりと過ごすのも久しぶりだ。\\n今までは実に慌ただしかったからな。"

# ダクネス
# 様々な困難に見舞われたが、\nそれも悪い事ばかりではなかったと私は思う。
304 = "様々な困難に見舞われたが、\\nそれも悪い事ばかりではなかったと私は思う。"

# ダクネス
# むしろ、今となっては、\n楽しい思い出の１つになったよ。\nふふっ！
282 = "むしろ、今となっては、\\n楽しい思い出の１つになったよ。\\nふふっ！"

# ダクネス
# 私はそんな時間を\nみんなと過ごせて、とても幸せだ。
316 = "私はそんな時間を\\nみんなと過ごせて、とても幸せだ。"

# カズマ（Ｍ）
# display as カズマ
# （おいおい、なんだこれ？\n　ダクネスのヤツ、\n　変なフラグを立てようとしてんのか？）
321 = "（おいおい、なんだこれ？\\n　ダクネスのヤツ、\\n　変なフラグを立てようとしてんのか？）"

# カズマ（Ｍ）
# display as カズマ
# （こんな風に過去を振り返るなんて、\n　どう考えてもヤバイ兆候だぞ）
323 = "（こんな風に過去を振り返るなんて、\\n　どう考えてもヤバイ兆候だぞ）"

# ダクネス
# カズマも、色々と大変だったな。
291 = "カズマも、色々と大変だったな。"

# カズマ
# そ、そうだな。
263 = "そ、そうだな。"

# ダクネス
# しかし、一緒に困難を乗り越えたことで、\n私達の絆もさらに強まった。
261 = "しかし、一緒に困難を乗り越えたことで、\\n私達の絆もさらに強まった。"

# ダクネス
# だから、これからも……些細なことでも構わない。\n困ったら遠慮せず、私達になんでも相談してくれ。
270 = "だから、これからも……些細なことでも構わない。\\n困ったら遠慮せず、私達になんでも相談してくれ。"

# カズマ
# ああ、うん。\nその時は頼らせてもらうよ。
244 = "ああ、うん。\\nその時は頼らせてもらうよ。"

# カズマ（Ｍ）
# display as カズマ
# （急に優しいこと言い出して……\n　なんか企んでやがるのか？）
343 = "（急に優しいこと言い出して……\\n　なんか企んでやがるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （アクア達と話していたことも、\n　それに関係が――）
339 = "（アクア達と話していたことも、\\n　それに関係が――）"

# ダクネス
# カズマ？\nどうかしたのか？\nさっきから元気がないぞ？
293 = "カズマ？\\nどうかしたのか？\\nさっきから元気がないぞ？"

# カズマ
# どわっ！？
274 = "どわっ！？"

# ダクネス
# なんだ？　どうした？
278 = "なんだ？　どうした？"

# カズマ（Ｍ）
# display as カズマ
# （だ、ダクネスの顔が目の前に！）
324 = "（だ、ダクネスの顔が目の前に！）"

# カズマ
# い、いや、ちょっと、\n顔が近くないでしょうかね、ダクネスさん？
248 = "い、いや、ちょっと、\\n顔が近くないでしょうかね、ダクネスさん？"

# ダクネス
# そうなのか？\n私は意識していなかったが、\nともかく、驚かしたようだな。すまない。
267 = "そうなのか？\\n私は意識していなかったが、\\nともかく、驚かしたようだな。すまない。"

# カズマ
# お、おう。
255 = "お、おう。"

# カズマ（Ｍ）
# display as カズマ
# （というか、近いのは今だけじゃない。\n　今日のダクネスは俺に寄り添う様に歩いてるけど、\n　いったいどういうつもりだ？）
330 = "（というか、近いのは今だけじゃない。\\n　今日のダクネスは俺に寄り添う様に歩いてるけど、\\n　いったいどういうつもりだ？）"

# カズマ（Ｍ）
# display as カズマ
# （これって……\n　デートと言っても\n　おかしくない雰囲気だけど……）
322 = "（これって……\\n　デートと言っても\\n　おかしくない雰囲気だけど……）"

# カズマ（Ｍ）
# display as カズマ
# （はっ！？\n　まさか、俺に色仕掛けを！？）
333 = "（はっ！？\\n　まさか、俺に色仕掛けを！？）"

# カズマ（Ｍ）
# display as カズマ
# （って、ダクネスは\n　そんな演技ができるほど器用じゃないし、\n　何か企んでいるわけじゃなさそうだが……）
328 = "（って、ダクネスは\\n　そんな演技ができるほど器用じゃないし、\\n　何か企んでいるわけじゃなさそうだが……）"

# カズマ（Ｍ）
# display as カズマ
# （意味がわからん！\n　そりゃ、まあ、女の子と並んで歩けるのは\n　すっげー嬉しいけどさ！！）
344 = "（意味がわからん！\\n　そりゃ、まあ、女の子と並んで歩けるのは\\n　すっげー嬉しいけどさ！！）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスは、黙っていればとびきりの美人で\n　スタイルだって抜群だし）
340 = "（ダクネスは、黙っていればとびきりの美人で\\n　スタイルだって抜群だし）"

# ダクネス
# カ、カズマ？\nそんな風に黙られると、\nなんだか恥ずかしくなってしまうのだが。
289 = "カ、カズマ？\\nそんな風に黙られると、\\nなんだか恥ずかしくなってしまうのだが。"

# カズマ
# あ、ああ、悪い。
243 = "あ、ああ、悪い。"

# カズマ（Ｍ）
# display as カズマ
# （なんだろう。\n　いつもと違った反応をされると、\n　妙な気分になっちまう……）
332 = "（なんだろう。\\n　いつもと違った反応をされると、\\n　妙な気分になっちまう……）"

# カズマ（Ｍ）
# display as カズマ
# （もしかしてダクネスも、\n　ちょっとデートっぽいとか\n　思ってるんだろうか？）
338 = "（もしかしてダクネスも、\\n　ちょっとデートっぽいとか\\n　思ってるんだろうか？）"

# ダクネス
# よ、よし。\nでは散歩を続けよう。
284 = "よ、よし。\\nでは散歩を続けよう。"

# カズマ
# そうだな……。
265 = "そうだな……。"

# ダクネス
# …………。
240 = "…………。"

# カズマ
# …………。
# 240 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （だ、ダメだ！\n　ダクネスのことが気になって\n　考え事に集中できない！）
325 = "（だ、ダメだ！\\n　ダクネスのことが気になって\\n　考え事に集中できない！）"

# カズマ
# な、なぁ、ダクネス？
276 = "な、なぁ、ダクネス？"

# ダクネス
# ……なんだ？
241 = "……なんだ？"

# カズマ
# 今日のお前はなんかおかしいぞ？
296 = "今日のお前はなんかおかしいぞ？"

# ダクネス
# 何っ？　おかしいだと！？\nわ、私はいたって普通だぞ！\nどこがおかしいというのだ！
299 = "何っ？　おかしいだと！？\\nわ、私はいたって普通だぞ！\\nどこがおかしいというのだ！"

# カズマ（Ｍ）
# display as カズマ
# （自覚ないのかよ……）
347 = "（自覚ないのかよ……）"

# カズマ
# だってさ、\n急に散歩に付いてきたり、昔話を始めたり、\nいつものダクネスじゃないみたいな感じだし。
271 = "だってさ、\\n急に散歩に付いてきたり、昔話を始めたり、\\nいつものダクネスじゃないみたいな感じだし。"

# ダクネス
# き、き、気のせいだ！\n私は別に何も企んではいない！
256 = "き、き、気のせいだ！\\n私は別に何も企んではいない！"

# ダクネス
# 普段はそうかもしれないが、\n今はエリス様に誓って違う！
301 = "普段はそうかもしれないが、\\n今はエリス様に誓って違う！"

# カズマ
# 普段はそうって認めるのかよ！
302 = "普段はそうって認めるのかよ！"

# ダクネス
# とにかく信じてくれ！\n本当に、今日はカズマと\n普通に過ごしたかっただけなんだ！
272 = "とにかく信じてくれ！\\n本当に、今日はカズマと\\n普通に過ごしたかっただけなんだ！"

# カズマ（Ｍ）
# display as カズマ
# （信じていいものか……\n　まあ、悪気はなさそうだし、\n　そこまで警戒しなくてもいいか）
342 = "（信じていいものか……\\n　まあ、悪気はなさそうだし、\\n　そこまで警戒しなくてもいいか）"

# カズマ
# わかったよ、俺の気のせいなんだな。
285 = "わかったよ、俺の気のせいなんだな。"

# ダクネス
# ああ、そうだとも。\n信じてくれてありがとう。
245 = "ああ、そうだとも。\\n信じてくれてありがとう。"

# カズマ（Ｍ）
# display as カズマ
# （でも、なんか引っかかるんだよなぁ）
329 = "（でも、なんか引っかかるんだよなぁ）"

# カズマ
# もしかして、体調が悪いのか？
283 = "もしかして、体調が悪いのか？"

# ダクネス
# いや、いたって普通だが。\n……気遣ってくれるんだな。
252 = "いや、いたって普通だが。\\n……気遣ってくれるんだな。"

# ダクネス
# ああ、もしかして\nカズマが疲れたから休憩したいのか？
246 = "ああ、もしかして\\nカズマが疲れたから休憩したいのか？"

# カズマ
# いや、そういうわけじゃないんだけどさ。
253 = "いや、そういうわけじゃないんだけどさ。"

# ダクネス
# 遠慮しなくていい。\nどこか座ってゆっくりするか。
317 = "遠慮しなくていい。\\nどこか座ってゆっくりするか。"

# カズマ
# 本当に聞いてみただけだから気にすんなって。
303 = "本当に聞いてみただけだから気にすんなって。"

# ダクネス
# そうか……。\n優しいんだな、カズマは。
264 = "そうか……。\\n優しいんだな、カズマは。"

# カズマ
# そんなんじゃねーって。
269 = "そんなんじゃねーって。"

# カズマ（Ｍ）
# display as カズマ
# （柄もなく気を遣うもんじゃないな。\n　なんだか、照れくさくなっちまった）
346 = "（柄もなく気を遣うもんじゃないな。\\n　なんだか、照れくさくなっちまった）"

# カズマ（Ｍ）
# display as カズマ
# （まぁ、ダクネスは頑丈さが取り柄だし、\n　不思議な幻覚を見ていたり\n　熱に浮かされているわけじゃないみたいだな）
334 = "（まぁ、ダクネスは頑丈さが取り柄だし、\\n　不思議な幻覚を見ていたり\\n　熱に浮かされているわけじゃないみたいだな）"

# カズマ
# こういうのもたまにはいいな。
259 = "こういうのもたまにはいいな。"

# ダクネス
# ああ。\nいつも命をかけた冒険ばかりだからな、\nこういった平和な時間はありがたい。
247 = "ああ。\\nいつも命をかけた冒険ばかりだからな、\\nこういった平和な時間はありがたい。"

# ダクネス
# 今日は、カズマと一緒に散歩ができてよかった。\nありがとう、同行を許してくれて。
298 = "今日は、カズマと一緒に散歩ができてよかった。\\nありがとう、同行を許してくれて。"

# カズマ
# べ、別に散歩ぐらい、いつでも\nついてきてもらっても構わないって。
281 = "べ、別に散歩ぐらい、いつでも\\nついてきてもらっても構わないって。"

# ダクネス
# ふふっ、そうか。
280 = "ふふっ、そうか。"

# カズマ（Ｍ）
# display as カズマ
# （……あれ？\n　なんかいい雰囲気になってる？）
318 = "（……あれ？\\n　なんかいい雰囲気になってる？）"

# カズマ（Ｍ）
# display as カズマ
# （も、もしかして、これって\n　本当にデートなんじゃないのか？）
337 = "（も、もしかして、これって\\n　本当にデートなんじゃないのか？）"

# カズマ（Ｍ）
# display as カズマ
# （だとしたら、ダクネスの態度にも\n　納得がいくし、これは……）
327 = "（だとしたら、ダクネスの態度にも\\n　納得がいくし、これは……）"

# ダクネス
# どうした、カズマ？
273 = "どうした、カズマ？"

# カズマ
# い、いや、なんでもない！
249 = "い、いや、なんでもない！"

# カズマ（Ｍ）
# display as カズマ
# （いや、考えすぎだな。\n　そうだ、きっとそうに違いない！）
320 = "（いや、考えすぎだな。\\n　そうだ、きっとそうに違いない！）"

# ダクネス
# あ……。\nそ、そうだ、突然だが、\n１つ聞いてもいいだろうか？
242 = "あ……。\\nそ、そうだ、突然だが、\\n１つ聞いてもいいだろうか？"

# カズマ
# ん？　なんだ？
286 = "ん？　なんだ？"

# ダクネス
# カ、カズマは今、その……\n寂しかったり困っていたり……\nい、いや……。
288 = "カ、カズマは今、その……\\n寂しかったり困っていたり……\\nい、いや……。"

# ダクネス
# い、今は……どんな気持ちだ？
251 = "い、今は……どんな気持ちだ？"

# カズマ
# はっ？\nどういう意味だよ。
279 = "はっ？\\nどういう意味だよ。"

# ダクネス
# そのままの意味だ！
268 = "そのままの意味だ！"

# カズマ
# どんな気持ちって……いや、普通だけど。
275 = "どんな気持ちって……いや、普通だけど。"

# ダクネス
# そうなのか？
266 = "そうなのか？"

# カズマ（Ｍ）
# display as カズマ
# （あえて言うなら、\n　質問の意味が全然わからないんだけどな）
319 = "（あえて言うなら、\\n　質問の意味が全然わからないんだけどな）"

# ダクネス
# こ、この散歩はどうだった？
257 = "こ、この散歩はどうだった？"

# カズマ（Ｍ）
# display as カズマ
# （またよくわからん質問が飛んできたな）
336 = "（またよくわからん質問が飛んできたな）"

# ダクネス
# 少しは気が紛れたり、元気になったか？
300 = "少しは気が紛れたり、元気になったか？"

# カズマ
# うーん、普通だよ。\nただ、少し気持ちよかったかなって思うぐらいで。
254 = "うーん、普通だよ。\\nただ、少し気持ちよかったかなって思うぐらいで。"

# ダクネス
# そ、そうか。
262 = "そ、そうか。"

# カズマ
# なあダクネス、さっきからどうした？\nわけわかんないことばっか言ってるぞ？
277 = "なあダクネス、さっきからどうした？\\nわけわかんないことばっか言ってるぞ？"

# ダクネス
# い、いや、なんでもない！\n気にするな！
250 = "い、いや、なんでもない！\\n気にするな！"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスはいったい何が言いたいんだ……？）
341 = "（ダクネスはいったい何が言いたいんだ……？）"

[selections]
# 296 = "今日のお前はなんかおかしいぞ？"
# 283 = "もしかして、体調が悪いのか？"
258 = "こういうのもたまにはいいな"
