# saiban.ks.scn

[info]
0 = ""

[characters]

[character_subs]

[script]
# lines: 15

# monologue
# 証言ゲット演出テスト
102 = "証言ゲット演出テスト"

# monologue
# ゲット完了
86 = "ゲット完了"

# monologue
# 裁判開廷
96 = "裁判開廷"

# monologue
# 一般キャラ選択
92 = "一般キャラ選択"

# monologue
# パンツ選択・パンツ番号とルート番号（目的）を指定
91 = "パンツ選択・パンツ番号とルート番号（目的）を指定"

# monologue
# パンツキャラ選択
90 = "パンツキャラ選択"

# monologue
# 証言選択
103 = "証言選択"

# monologue
# 証言選択1
104 = "証言選択1"

# monologue
# 証言選択2
105 = "証言選択2"

# monologue
# 返却成功
107 = "返却成功"

# monologue
# 返却失敗
106 = "返却失敗"

# monologue
# 結果表示
95 = "結果表示"

# monologue
# お仕置き選択
79 = "お仕置き選択"

# monologue
# ご褒美選択
80 = "ご褒美選択"

# monologue
# パラメータ画面確認テスト用
88 = "パラメータ画面確認テスト用"

[selections]
89 = "パンツに見覚えがある"
93 = "今日の夕食はなんだろう"
94 = "友達何人できるかな"
83 = "アクア"
87 = "ダクネス"
84 = "ウィズ"
28 = "1"
29 = "2"
30 = "3"
# 28 = "1"
# 29 = "2"
# 30 = "3"
# 28 = "1"
# 29 = "2"
# 30 = "3"
# 83 = "アクア"
81 = "めぐみん"
# 87 = "ダクネス"
85 = "クリス"
# 84 = "ウィズ"
82 = "ゆんゆん"
97 = "証言1"
98 = "証言2"
99 = "証言3"
100 = "証言4"
101 = "証言5"
# 97 = "証言1"
# 98 = "証言2"
# 99 = "証言3"
# 97 = "証言1"
# 98 = "証言2"
# 99 = "証言3"
# 83 = "アクア"
# 81 = "めぐみん"
# 87 = "ダクネス"
# 85 = "クリス"
# 84 = "ウィズ"
# 82 = "ゆんゆん"
