# st01a_01.txt.scn

[info]
160 = "st01a_01"

[characters]
251 = "カズマ（Ｍ）"
249 = "カズマ"
248 = "ウィズ"
242 = "ゆんゆん"
238 = "めぐみん"
245 = "アクア"
254 = "ダクネス"
252 = "クリス"

[character_subs]
# 249 = "カズマ"

[script]
# lines: 79

# カズマ（Ｍ）
# display as カズマ
# （さて、これからのことを\n　本格的に考えなくちゃ\n　いけなくなってきたわけだが――）
296 = "（さて、これからのことを\\n　本格的に考えなくちゃ\\n　いけなくなってきたわけだが――）"

# カズマ
# どうしてウィズとゆんゆんまで\nここにいるんだ？
223 = "どうしてウィズとゆんゆんまで\\nここにいるんだ？"

# ウィズ
# アクア様に呼ばれまして。
247 = "アクア様に呼ばれまして。"

# ゆんゆん
# わ、私は、めぐみんに呼ばれて仕方なく。
243 = "わ、私は、めぐみんに呼ばれて仕方なく。"

# カズマ
# アクアとめぐみんに？
246 = "アクアとめぐみんに？"

# めぐみん
# その方が安全だと思ったので。
205 = "その方が安全だと思ったので。"

# カズマ
# どういう意味だよ。
221 = "どういう意味だよ。"

# アクア
# 母数が増えれば\nパンツを盗まれる確率が低くなるじゃない。
264 = "母数が増えれば\\nパンツを盗まれる確率が低くなるじゃない。"

# カズマ
# ああ、なるほど、確かに。
192 = "ああ、なるほど、確かに。"

# めぐみん
# カズマが納得してどうするんですか。
250 = "カズマが納得してどうするんですか。"

# カズマ
# でも実際そうだろ？\nパンツを盗まれる確率が、１／３から１／５に\nなったんだからさ。
219 = "でも実際そうだろ？\\nパンツを盗まれる確率が、１／３から１／５に\\nなったんだからさ。"

# めぐみん
# だからってそんなにあっさり納得しないで\nくださいよ。
213 = "だからってそんなにあっさり納得しないで\\nくださいよ。"

# めぐみん
# それともゆんゆんとウィズのパンツも盗めて\nラッキーとか思ってるんですか。
207 = "それともゆんゆんとウィズのパンツも盗めて\\nラッキーとか思ってるんですか。"

# めぐみん
# 本当に墜ちるところまで墜ちましたね。
263 = "本当に墜ちるところまで墜ちましたね。"

# カズマ
# 犠牲者を増やしたお前たちに言われたくないわ！
266 = "犠牲者を増やしたお前たちに言われたくないわ！"

# ゆんゆん
# あ、あの、めぐみん、聞いてもいい？
191 = "あ、あの、めぐみん、聞いてもいい？"

# めぐみん
# なんです？
231 = "なんです？"

# ゆんゆん
# さっきから言ってるパ、パンツって、\nなんのこと？
202 = "さっきから言ってるパ、パンツって、\\nなんのこと？"

# めぐみん
# 非常に嘆かわしいことに、\n変態にジョブチェンジしたカズマが夜な夜な\nパンツを盗む病気にかかってしまったんです。
292 = "非常に嘆かわしいことに、\\n変態にジョブチェンジしたカズマが夜な夜な\\nパンツを盗む病気にかかってしまったんです。"

# カズマ
# 待てい！\nどうしてお前はそうやって\nわざと誤解を生むような言い方をするんだよ！
262 = "待てい！\\nどうしてお前はそうやって\\nわざと誤解を生むような言い方をするんだよ！"

# めぐみん
# ふん！
235 = "ふん！"

# カズマ
# なんだよ。\n俺だって好きでこんなことに\nなったわけじゃないんだからな。
230 = "なんだよ。\\n俺だって好きでこんなことに\\nなったわけじゃないんだからな。"

# ダクネス
# なら早くバニルに頼んで\n指輪を外してもらえばいいだろう。
228 = "なら早くバニルに頼んで\\n指輪を外してもらえばいいだろう。"

# カズマ
# だからそのためには金が！
212 = "だからそのためには金が！"

# アクア
# もう面倒だから借金しちゃいなさいよ。\nお金を借りるのって意外に簡単なのよ。
239 = "もう面倒だから借金しちゃいなさいよ。\\nお金を借りるのって意外に簡単なのよ。"

# カズマ
# 借金を勧めるとか、ほんとお前、駄女神だな！
259 = "借金を勧めるとか、ほんとお前、駄女神だな！"

# カズマ
# そもそも俺の借金の大半は、\nお前のせいでできたもんだろうが！
206 = "そもそも俺の借金の大半は、\\nお前のせいでできたもんだろうが！"

# アクア
# な、何よぉ、悪気があるわけじゃないのに。
225 = "な、何よぉ、悪気があるわけじゃないのに。"

# ウィズ
# あの、ちょっといいですか？
194 = "あの、ちょっといいですか？"

# カズマ
# どうしたウィズ？
222 = "どうしたウィズ？"

# ウィズ
# バニルさんなんですけど、先ほど、\nまた買い出しの旅に出かけてしまいまして。
255 = "バニルさんなんですけど、先ほど、\\nまた買い出しの旅に出かけてしまいまして。"

# カズマ
# は？
234 = "は？"

# ウィズ
# なので、お金を用意していただいても、\nすぐに指輪を外すというわけには……。
226 = "なので、お金を用意していただいても、\\nすぐに指輪を外すというわけには……。"

# カズマ
# あいつ！　こんな状況なのに何考えてんだ！？
193 = "あいつ！　こんな状況なのに何考えてんだ！？"

# めぐみん
# こんな状況だからなのでは？
200 = "こんな状況だからなのでは？"

# カズマ（Ｍ）
# display as カズマ
# （え……？）
293 = "（え……？）"

# ダクネス
# なるほど。\nカズマが苦しむ状況を面白がって、\nあえて姿を消したというわけか。
229 = "なるほど。\\nカズマが苦しむ状況を面白がって、\\nあえて姿を消したというわけか。"

# カズマ
# あの腐れ悪魔が！
195 = "あの腐れ悪魔が！"

# ウィズ
# ま、待ってください。\nいくらバニルさんが悪魔とはいえ、\nそんな意地の悪いことはしませんよ。
236 = "ま、待ってください。\\nいくらバニルさんが悪魔とはいえ、\\nそんな意地の悪いことはしませんよ。"

# カズマ
# なら、出かけた先を聞いてるのか？
227 = "なら、出かけた先を聞いてるのか？"

# ウィズ
# それは何も。
208 = "それは何も。"

# カズマ
# 連絡を取る方法は？
290 = "連絡を取る方法は？"

# ウィズ
# ええと。
199 = "ええと。"

# カズマ
# いつごろ帰って来るかは？
196 = "いつごろ帰って来るかは？"

# ウィズ
# …………。
190 = "…………。"

# カズマ
# やっぱりわざといなくなりやがったんじゃねーか！
241 = "やっぱりわざといなくなりやがったんじゃねーか！"

# ウィズ
# そんなー。
209 = "そんなー。"

# アクア
# ねえ、さっさと指を切っちゃった方が\n話が早くない？
232 = "ねえ、さっさと指を切っちゃった方が\\n話が早くない？"

# めぐみん
# そうですね。今後のためにもなりますし。
204 = "そうですね。今後のためにもなりますし。"

# カズマ（Ｍ）
# display as カズマ
# （くっ、こいつら好き放題言いやがって……）
294 = "（くっ、こいつら好き放題言いやがって……）"

# カズマ（Ｍ）
# display as カズマ
# （だが、このままだと\n　本当に指を落とされかねない）
297 = "（だが、このままだと\\n　本当に指を落とされかねない）"

# カズマ（Ｍ）
# display as カズマ
# （なんとか話の流れを変えないと……）
299 = "（なんとか話の流れを変えないと……）"

# アクア
# 誰か来たのかしら？
289 = "誰か来たのかしら？"

# カズマ
# はいはい。どちら様ですか？
233 = "はいはい。どちら様ですか？"

# クリス
# やっ。
240 = "やっ。"

# カズマ
# クリス？
253 = "クリス？"

# ダクネス
# わざわざ訪ねてくるなんて珍しいな。\nどうしたんだ？
244 = "わざわざ訪ねてくるなんて珍しいな。\\nどうしたんだ？"

# クリス
# いやー、なんかダクネスたちが\n面白いことになってるらしいって話を聞いてさ。
198 = "いやー、なんかダクネスたちが\\n面白いことになってるらしいって話を聞いてさ。"

# カズマ
# さすがは盗賊。早耳だな。
201 = "さすがは盗賊。早耳だな。"

# クリス
# いやいや、それほどでも。
197 = "いやいや、それほどでも。"

# カズマ（Ｍ）
# display as カズマ
# （こいつはクリス。\n　ダクネスの友人で職業は盗賊だ）
295 = "（こいつはクリス。\\n　ダクネスの友人で職業は盗賊だ）"

# カズマ（Ｍ）
# display as カズマ
# （俺にスティールスキルを教えてくれた人であり、\n　最初にパンツを盗まれた犠牲者でもある）
301 = "（俺にスティールスキルを教えてくれた人であり、\\n　最初にパンツを盗まれた犠牲者でもある）"

# カズマ（Ｍ）
# display as カズマ
# （ちなみに白だった）
298 = "（ちなみに白だった）"

# クリス
# で、面白いことって何があったわけ？\n場合によっては一枚噛ませてもらうよ。
218 = "で、面白いことって何があったわけ？\\n場合によっては一枚噛ませてもらうよ。"

# アクア
# 関係ない人たちからしたら\n面白いかもしれないけど、\n私たちにしたら何も面白くないわよ、こんなの。
291 = "関係ない人たちからしたら\\n面白いかもしれないけど、\\n私たちにしたら何も面白くないわよ、こんなの。"

# クリス
# どゆこと？
224 = "どゆこと？"

# めぐみん
# パンツ泥棒が出たんです。
257 = "パンツ泥棒が出たんです。"

# クリス
# パパパ、パンツ泥棒！？
256 = "パパパ、パンツ泥棒！？"

# カズマ
# だからそういう言い方はやめろって。
211 = "だからそういう言い方はやめろって。"

# ダクネス
# だが、指輪のせいとはいえ\nパンツを盗んだのは事実なわけだしな。
214 = "だが、指輪のせいとはいえ\\nパンツを盗んだのは事実なわけだしな。"

# クリス
# まさか、キミなの！？
237 = "まさか、キミなの！？"

# カズマ
# ちがっ……いや、違わないんだけど、\nそんなに怯えることないだろ？
216 = "ちがっ……いや、違わないんだけど、\\nそんなに怯えることないだろ？"

# クリス
# だって前科があるし。
215 = "だって前科があるし。"

# カズマ（Ｍ）
# display as カズマ
# （スティールを教わった時のことを\n　まだ根に持ってるのか）
300 = "（スティールを教わった時のことを\\n　まだ根に持ってるのか）"

# カズマ
# とにかく、今回は俺が盗ろうとして\n盗ったわけじゃないんだって。\n悪いのはこの指輪のせいで――
220 = "とにかく、今回は俺が盗ろうとして\\n盗ったわけじゃないんだって。\\n悪いのはこの指輪のせいで――"

# カズマ
# そうだ。盗賊だったらこの手のアイテムの\n解除方法とか知ってたりしないか？\n外そうとしても外れないんだよ、これ。
203 = "そうだ。盗賊だったらこの手のアイテムの\\n解除方法とか知ってたりしないか？\\n外そうとしても外れないんだよ、これ。"

# クリス
# 知らないよ。\nそんな悪趣味なアイテム聞いたこともないし。
288 = "知らないよ。\\nそんな悪趣味なアイテム聞いたこともないし。"

# クリス
# っていうか、\nそういう話なんだったらあたしもう行くから。
217 = "っていうか、\\nそういう話なんだったらあたしもう行くから。"

# カズマ
# そんな！？
210 = "そんな！？"

