# st01c_09.txt.scn

[info]
147 = "st01c_09"

[characters]
202 = "カズマ（Ｍ）"
200 = "カズマ"
198 = "アクア"
199 = "ウィズ"
203 = "クリス"
195 = "めぐみん"
196 = "ゆんゆん"

[character_subs]
# 200 = "カズマ"

[script]
# lines: 44

# カズマ（Ｍ）
# display as カズマ
# （かくして束の間の栄華を誇ったメイド喫茶は\n　終焉を迎えた）
241 = "（かくして束の間の栄華を誇ったメイド喫茶は\\n　終焉を迎えた）"

# カズマ（Ｍ）
# display as カズマ
# （常連客から閉店を惜しむ声はあったものの、\n　ギルドが取り決めたこととあっては逆らえる\n　はずもない）
246 = "（常連客から閉店を惜しむ声はあったものの、\\n　ギルドが取り決めたこととあっては逆らえる\\n　はずもない）"

# カズマ（Ｍ）
# display as カズマ
# （俺たちは客への説明もそこそこに、\n　持ち込んでいた荷物を抱えて屋敷へと\n　引き上げて来たわけだが……）
245 = "（俺たちは客への説明もそこそこに、\\n　持ち込んでいた荷物を抱えて屋敷へと\\n　引き上げて来たわけだが……）"

# カズマ
# 嘘だろ……残ったのはこれっぽっちかよ。
209 = "嘘だろ……残ったのはこれっぽっちかよ。"

# カズマ（Ｍ）
# display as カズマ
# （あのあと、迷惑料として、\n　これまでの店の使用料やら、\n　もろもろを経費としてギルドに巻き上げられ――）
239 = "（あのあと、迷惑料として、\\n　これまでの店の使用料やら、\\n　もろもろを経費としてギルドに巻き上げられ――）"

# カズマ（Ｍ）
# display as カズマ
# （いや、支払わされてしまったせいだ）
240 = "（いや、支払わされてしまったせいだ）"

# カズマ（Ｍ）
# display as カズマ
# （これじゃ俺の指輪どころの話じゃないわ）
242 = "（これじゃ俺の指輪どころの話じゃないわ）"

# カズマ（Ｍ）
# display as カズマ
# （ただ、結果は無残に終わってしまったが、\n　俺にも商売で金を稼ぐことができるという\n　自信を持てたのは大きい）
244 = "（ただ、結果は無残に終わってしまったが、\\n　俺にも商売で金を稼ぐことができるという\\n　自信を持てたのは大きい）"

# カズマ（Ｍ）
# display as カズマ
# （手元に残った金額はわずかだが、\n　これを元手に新たな商売の可能性を――）
247 = "（手元に残った金額はわずかだが、\\n　これを元手に新たな商売の可能性を――）"

# アクア
# ねえカズマ、\nそろそろお給料を払ってもらいたいんだけど？
191 = "ねえカズマ、\\nそろそろお給料を払ってもらいたいんだけど？"

# カズマ
# え？　給料？
176 = "え？　給料？"

# アクア
# たっぷり儲けたんだから\n少しは色をつけなさいよね。
183 = "たっぷり儲けたんだから\\n少しは色をつけなさいよね。"

# カズマ
# いや、ちょっと待て。\nお前らボランティアじゃ……。
174 = "いや、ちょっと待て。\\nお前らボランティアじゃ……。"

# アクア
# はー？　何言ってるのよ、あんた。\nあんな重労働を無償でやるわけないじゃない。
192 = "はー？　何言ってるのよ、あんた。\\nあんな重労働を無償でやるわけないじゃない。"

# ウィズ
# あのー……私、ずっとお店を閉めて、\nこちらの手伝いをしていたので、\nお給料をいただけないと生活が。
171 = "あのー……私、ずっとお店を閉めて、\\nこちらの手伝いをしていたので、\\nお給料をいただけないと生活が。"

# カズマ（Ｍ）
# display as カズマ
# （そ、そんな切羽詰まったことを言われたら、\n　払わないわけにはいかないじゃないか）
243 = "（そ、そんな切羽詰まったことを言われたら、\\n　払わないわけにはいかないじゃないか）"

# カズマ
# わかったよ。\nこれをみんなで山分けしてくれ。
197 = "わかったよ。\\nこれをみんなで山分けしてくれ。"

# アクア
# 何よこのはした金。
207 = "何よこのはした金。"

# カズマ
# 手元に残った売り上げだ。
214 = "手元に残った売り上げだ。"

# アクア
# 嘘でしょ！？　あんなに儲けてたのに、\nこれっぽっちしか残ってないわけないじゃない！
210 = "嘘でしょ！？　あんなに儲けてたのに、\\nこれっぽっちしか残ってないわけないじゃない！"

# カズマ
# 嘘なんかついてどうする。\nギルドに支払うところはお前も見てただろ？
211 = "嘘なんかついてどうする。\\nギルドに支払うところはお前も見てただろ？"

# アクア
# でも……だって……\n私、がんばって働いてあげてたのに……\n億万長者も夢じゃないって……。
187 = "でも……だって……\\n私、がんばって働いてあげてたのに……\\n億万長者も夢じゃないって……。"

# アクア
# ほ、ほんとは隠してるんでしょ？\n独り占めにしようとして……。\nねえ、ジャンプしてみなさいよ。ほら。
193 = "ほ、ほんとは隠してるんでしょ？\\n独り占めにしようとして……。\\nねえ、ジャンプしてみなさいよ。ほら。"

# カズマ
# お前は昔のヤンキーか！
179 = "お前は昔のヤンキーか！"

# アクア
# いいから、ほら！\nポケットの中を調べさせなさいよ！
173 = "いいから、ほら！\\nポケットの中を調べさせなさいよ！"

# カズマ
# おまっ、ひとのポケットに手ぇ突っ込むとか……\n馬鹿、そこは……あ、ああ！？
177 = "おまっ、ひとのポケットに手ぇ突っ込むとか……\\n馬鹿、そこは……あ、ああ！？"

# アクア
# なんかあったっ！　財布、これは財布ね！
188 = "なんかあったっ！　財布、これは財布ね！"

# カズマ
# だーーーー！！\nそれは財布じゃない！！
184 = "だーーーー！！\\nそれは財布じゃない！！"

# アクア
# ぬぎぎ、問答無用！　よこしなさい！！
190 = "ぬぎぎ、問答無用！　よこしなさい！！"

# クリス
# ああああっ！？
170 = "ああああっ！？"

# アクア
# あんたまさか、お店の売り上げでこれを買ったの？
172 = "あんたまさか、お店の売り上げでこれを買ったの？"

# めぐみん
# カズマならあり得ますね。
201 = "カズマならあり得ますね。"

# カズマ
# お前、わかってて言ってるだろ！\nこれは前に俺が盗っちまったパンツだよ！
178 = "お前、わかってて言ってるだろ！\\nこれは前に俺が盗っちまったパンツだよ！"

# めぐみん
# まだ捨ててなかったんですか。
194 = "まだ捨ててなかったんですか。"

# カズマ
# 捨てるわけないだろ。\nまあ、存在はすっかり忘れてたけど。
215 = "捨てるわけないだろ。\\nまあ、存在はすっかり忘れてたけど。"

# カズマ
# ちょうどいいや。\nせっかく出て来たことだし、持ち主に返しとこう。
185 = "ちょうどいいや。\\nせっかく出て来たことだし、持ち主に返しとこう。"

# ゆんゆん
# え、まさかまたやるんですか？
175 = "え、まさかまたやるんですか？"

# カズマ
# 当然。
213 = "当然。"

# めぐみん
# ですから、そっと置いておいて\n持ち主が取りにくるのを待てばいいじゃないすか。
186 = "ですから、そっと置いておいて\\n持ち主が取りにくるのを待てばいいじゃないすか。"

# カズマ
# そんなの俺の紳士魂が許さないって言ってるだろ！
182 = "そんなの俺の紳士魂が許さないって言ってるだろ！"

# カズマ
# それに、前回のめぐみんの時と同様に\n状況証拠は揃っているんだ。
181 = "それに、前回のめぐみんの時と同様に\\n状況証拠は揃っているんだ。"

# クリス
# な！？
189 = "な！？"

# ウィズ
# 目が活き活きとしてますね。
217 = "目が活き活きとしてますね。"

# カズマ
# さあ、事実の証明を行おうじゃないか！\nパンツ裁判の開廷だ！
180 = "さあ、事実の証明を行おうじゃないか！\\nパンツ裁判の開廷だ！"

[selections]
204 = "コーヒーブレイク"
