# st01c_07.txt.scn

[info]
133 = "st01c_07"

[characters]
202 = "カズマ（Ｍ）"
201 = "カズマ"
204 = "ダクネス"
203 = "クリス"
196 = "ゆんゆん"
194 = "めぐみん"
199 = "ウィズ"
197 = "アクア"

[character_subs]
# 201 = "カズマ"

[script]
# lines: 39

# カズマ（Ｍ）
# display as カズマ
# （そして、さらに数日が経過した――）
243 = "（そして、さらに数日が経過した――）"

# カズマ
# みんなのおかげで、半年はかかる予定だった\n目標金額が、３ヶ月ほどで達成できそうだ。
193 = "みんなのおかげで、半年はかかる予定だった\\n目標金額が、３ヶ月ほどで達成できそうだ。"

# ダクネス
# それは良いが、\n店の評判が大変なことになっているぞ。
179 = "それは良いが、\\n店の評判が大変なことになっているぞ。"

# ダクネス
# 絶賛する客がいる一方で、\n不満を持っている人も少なくないと聞く。
240 = "絶賛する客がいる一方で、\\n不満を持っている人も少なくないと聞く。"

# クリス
# まあ、限られた人数で店を回してる以上、\nどうしても手の届かないトコは出てくるもんだよ。
191 = "まあ、限られた人数で店を回してる以上、\\nどうしても手の届かないトコは出てくるもんだよ。"

# ゆんゆん
# あと、お客さんたちの方でも\n問題が起こってるらしいです。
166 = "あと、お客さんたちの方でも\\n問題が起こってるらしいです。"

# カズマ
# どういうことだ？
186 = "どういうことだ？"

# めぐみん
# オプション料金につぎ込むために、\n借金までしている人がいるらしいんですよ。
200 = "オプション料金につぎ込むために、\\n借金までしている人がいるらしいんですよ。"

# カズマ
# それは俺たちでどうにかできることじゃないだろ。
178 = "それは俺たちでどうにかできることじゃないだろ。"

# めぐみん
# まあ、借金は個人の問題ですからね。\n私もどうでもいいと思ってます。
190 = "まあ、借金は個人の問題ですからね。\\n私もどうでもいいと思ってます。"

# ゆんゆん
# めぐみん冷たい！
195 = "めぐみん冷たい！"

# めぐみん
# では、どうしろと言うのですか、\nこんなことにお金を使ってはいけないと説教するん\nですか？
183 = "では、どうしろと言うのですか、\\nこんなことにお金を使ってはいけないと説教するん\\nですか？"

# めぐみん
# きっとそういうのも彼らにはご褒美にしか\nなりませんよ。
174 = "きっとそういうのも彼らにはご褒美にしか\\nなりませんよ。"

# ゆんゆん
# うぅ、確かにそうだね。
170 = "うぅ、確かにそうだね。"

# めぐみん
# それよりも問題なのは、身近にできつつある\n敵です。
180 = "それよりも問題なのは、身近にできつつある\\n敵です。"

# ゆんゆん
# 最近、酒場のお姉さん達の私たちを見る目が……。
211 = "最近、酒場のお姉さん達の私たちを見る目が……。"

# ウィズ
# メイド喫茶にお客さんを取られて、\n酒場の売り上げが落ちているらしいですからね。
205 = "メイド喫茶にお客さんを取られて、\\n酒場の売り上げが落ちているらしいですからね。"

# クリス
# 酒場はギルドの収入源でもあるんだから、\nまあ当然かな。
242 = "酒場はギルドの収入源でもあるんだから、\\nまあ当然かな。"

# ダクネス
# 近々、賃貸料を要求されるか、\n最悪追い出される事態も念頭に置いておいた方が\nいいだろう。
241 = "近々、賃貸料を要求されるか、\\n最悪追い出される事態も念頭に置いておいた方が\\nいいだろう。"

# アクア
# ねえねえ、いっそのこと、\nこっちから出てっちゃうっていうのはどうかしら。
189 = "ねえねえ、いっそのこと、\\nこっちから出てっちゃうっていうのはどうかしら。"

# めぐみん
# アクアには行く当てがあるんですか？
198 = "アクアには行く当てがあるんですか？"

# アクア
# ないわよ。
188 = "ないわよ。"

# カズマ
# お前な……。
172 = "お前な……。"

# アクア
# でも、これだけハマってる客がいるんだから、\n別のトコに移ってもついてくるでしょ？
184 = "でも、これだけハマってる客がいるんだから、\\n別のトコに移ってもついてくるでしょ？"

# カズマ
# それ以前に店を出す場所がないって言ってんだよ！
181 = "それ以前に店を出す場所がないって言ってんだよ！"

# ウィズ
# 移転が無理なら、ギルドの方とちゃんと話をして、\n場所を共有していける方法を模索した方が良いと\n思います。
239 = "移転が無理なら、ギルドの方とちゃんと話をして、\\n場所を共有していける方法を模索した方が良いと\\n思います。"

# カズマ
# お前たちの心配してることはだいたいわかった。
171 = "お前たちの心配してることはだいたいわかった。"

# カズマ
# だがメイド喫茶は\nこのままの形で続けていくつもりだ。
182 = "だがメイド喫茶は\\nこのままの形で続けていくつもりだ。"

# カズマ
# それに伴い、さらに過激なオプションを\n展開していこうと思っている。
177 = "それに伴い、さらに過激なオプションを\\n展開していこうと思っている。"

# めぐみん
# な、何をさせるつもりですあなたは！！
187 = "な、何をさせるつもりですあなたは！！"

# アクア
# まさか女神である私を\n汚すつもりじゃないでしょうね？
192 = "まさか女神である私を\\n汚すつもりじゃないでしょうね？"

# ウィズ
# あの、体に触れられたりするのはちょっと。
167 = "あの、体に触れられたりするのはちょっと。"

# ゆんゆん
# そそそ、そうですよ！\nエッチなのはいけないと思います！
176 = "そそそ、そうですよ！\\nエッチなのはいけないと思います！"

# カズマ
# いや、さすがにそんなことさせないって。
168 = "いや、さすがにそんなことさせないって。"

# ダクネス
# となると、衣装に手を加えるつもりか！
185 = "となると、衣装に手を加えるつもりか！"

# ダクネス
# さらに布を少なくし、胸の谷間を強調させ、\n太ももをあらわにすると言うのだな！
175 = "さらに布を少なくし、胸の谷間を強調させ、\\n太ももをあらわにすると言うのだな！"

# ダクネス
# ああ、なんといやらしいことを思いつくのだ貴様は。\n金のために男の視線に媚びを売り、痴態を晒せと？
165 = "ああ、なんといやらしいことを思いつくのだ貴様は。\\n金のために男の視線に媚びを売り、痴態を晒せと？"

# カズマ
# お前はそうやって周りを不安にさせるようなことを\n言うな。
173 = "お前はそうやって周りを不安にさせるようなことを\\n言うな。"

# ダクネス
# うぅ、すまない。
169 = "うぅ、すまない。"

