# st01b_10.txt.scn

[info]
175 = "st01b_10"

[characters]
244 = "カズマ"
246 = "クリス"
249 = "ダクネス"
245 = "カズマ（Ｍ）"

[character_subs]
# 244 = "カズマ"

[script]
# lines: 83

# カズマ
# いたいた。\nおーい、ダクネスー！
200 = "いたいた。\\nおーい、ダクネスー！"

# クリス
# おっ、噂をすれば。
211 = "おっ、噂をすれば。"

# ダクネス
# なんだ、ずいぶんと早かったじゃないか。
232 = "なんだ、ずいぶんと早かったじゃないか。"

# カズマ
# ２人の説得が意外にすんなりいってさ。\nええと、クリスには――
335 = "２人の説得が意外にすんなりいってさ。\\nええと、クリスには――"

# ダクネス
# 今、会ったばかりだからまだ何も話してない。
255 = "今、会ったばかりだからまだ何も話してない。"

# クリス
# え……キミがあたしに用事なの？
207 = "え……キミがあたしに用事なの？"

# カズマ
# ああ、とても重要なことなんだ。
195 = "ああ、とても重要なことなんだ。"

# クリス
# ま、まさか、でも、どうして？？
240 = "ま、まさか、でも、どうして？？"

# カズマ
# ん、どうかしたのか？
243 = "ん、どうかしたのか？"

# クリス
# まさか千里眼スキルも強化されてて。\nいやでも、マジックアイテムの効果は満月の夜\n限定だし。
241 = "まさか千里眼スキルも強化されてて。\\nいやでも、マジックアイテムの効果は満月の夜\\n限定だし。"

# カズマ
# なーに、ぶつぶつ言ってるんだよ。
235 = "なーに、ぶつぶつ言ってるんだよ。"

# クリス
# あ、いや、なんでもないよ、あはは。
193 = "あ、いや、なんでもないよ、あはは。"

# カズマ
# さっきから変だぞ、顔も赤いしさ。
215 = "さっきから変だぞ、顔も赤いしさ。"

# カズマ
# あっ、もしかして、体調が悪いのか？
198 = "あっ、もしかして、体調が悪いのか？"

# クリス
# え？
209 = "え？"

# カズマ
# それなら早く言えよ。\nえっと、座って休める所は……。
226 = "それなら早く言えよ。\\nえっと、座って休める所は……。"

# クリス
# ふっ。あははははっ。
237 = "ふっ。あははははっ。"

# カズマ
# な、なんだよ急に笑ったりして？
231 = "な、なんだよ急に笑ったりして？"

# クリス
# ごめんごめん。\nキミって意外と優しい所があるんだなーと思って。
213 = "ごめんごめん。\\nキミって意外と優しい所があるんだなーと思って。"

# カズマ
# 俺はいつだって優しいぞ。女には特にな。
263 = "俺はいつだって優しいぞ。女には特にな。"

# ダクネス
# %fsyogen;そうだな。\nカズマが私に見せる優しさはひと味もふた味も違う。
12 = "%fsyogen;そうだな。\\nカズマが私に見せる優しさはひと味もふた味も違う。"

# カズマ（Ｍ）
# display as カズマ
# （いやいや、ダクネスさん。\n　なんでほほを赤らめているんですか？）
330 = "（いやいや、ダクネスさん。\\n　なんでほほを赤らめているんですか？）"

# カズマ（Ｍ）
# display as カズマ
# （俺、別にダクネスに何もしていないし、\n　何も考えていないからな！）
334 = "（俺、別にダクネスに何もしていないし、\\n　何も考えていないからな！）"

# カズマ（Ｍ）
# display as カズマ
# （って、誰に俺は弁解しているんだ！？）
333 = "（って、誰に俺は弁解しているんだ！？）"

# カズマ（Ｍ）
# display as カズマ
# （だが、唐突にハァハァしているのは\n　かなり怪しいぞ！？\n　証言としてゲットしておこう）
332 = "（だが、唐突にハァハァしているのは\\n　かなり怪しいぞ！？\\n　証言としてゲットしておこう）"

# カズマ
# うん、お前は黙ってようか。
204 = "うん、お前は黙ってようか。"

# ダクネス
# ふふふ、言った側からこれだ。
238 = "ふふふ、言った側からこれだ。"

# クリス
# あははは。\nえっと、あたしに用事があるんだよね？
199 = "あははは。\\nえっと、あたしに用事があるんだよね？"

# カズマ
# そうなんだけど、また今度でいいよ。
221 = "そうなんだけど、また今度でいいよ。"

# クリス
# 体調はいたって普通。\nだから平気だよ。
257 = "体調はいたって普通。\\nだから平気だよ。"

# カズマ
# そっか、それなら、実は頼みがあって。
223 = "そっか、それなら、実は頼みがあって。"

# カズマ
# もしかして、何か悩み事でもあるのか？
242 = "もしかして、何か悩み事でもあるのか？"

# クリス
# 悩みといえば、そうなのかな。
272 = "悩みといえば、そうなのかな。"

# カズマ
# なんだったら、聞くだけは聞くぞ。\nでも気の利いたアドバイスとかは期待するなよ？
233 = "なんだったら、聞くだけは聞くぞ。\\nでも気の利いたアドバイスとかは期待するなよ？"

# クリス
# ぷっ、あはは、キミって本当にカッコ悪いね。
239 = "ぷっ、あはは、キミって本当にカッコ悪いね。"

# カズマ
# なんでだよ！
234 = "なんでだよ！"

# ダクネス
# そこは嘘でも力になるとか、\nそういうことを言うべき所だろう。
222 = "そこは嘘でも力になるとか、\\nそういうことを言うべき所だろう。"

# カズマ
# うるせー。話を聞く前から\nできもしない約束なんかできるか！
203 = "うるせー。話を聞く前から\\nできもしない約束なんかできるか！"

# クリス
# 別に悩みがあるわけじゃないから、心配しないで。\nそれよりもあたしに話があるんでしょ？
264 = "別に悩みがあるわけじゃないから、心配しないで。\\nそれよりもあたしに話があるんでしょ？"

# カズマ
# ああ、実は頼みがあって。
197 = "ああ、実は頼みがあって。"

# カズマ
# さては俺に恋を！\n来た！　モテ期来た！
217 = "さては俺に恋を！\\n来た！　モテ期来た！"

# クリス
# いや、それは絶対にないから。\n変な勘違いとか、本当に困る。
201 = "いや、それは絶対にないから。\\n変な勘違いとか、本当に困る。"

# カズマ
# 何もそんな一刀両断しなくても！
261 = "何もそんな一刀両断しなくても！"

# クリス
# それで？　あたしに何か用事があるんでしょ？\n何もないならもう行くけど。
224 = "それで？　あたしに何か用事があるんでしょ？\\n何もないならもう行くけど。"

# カズマ
# 待て待て！　クリスに頼みたいことがあるんだよ。
271 = "待て待て！　クリスに頼みたいことがあるんだよ。"

# クリス
# ええと、正直嫌な予感しかしないんだけど。
208 = "ええと、正直嫌な予感しかしないんだけど。"

# ダクネス
# 気持ちはわかるが、警戒しすぎだ。
273 = "気持ちはわかるが、警戒しすぎだ。"

# クリス
# 警戒したくもなるよ。\nなんてたって――
325 = "警戒したくもなるよ。\\nなんてたって――"

# カズマ
# 俺、お前に何かしたっけ？
262 = "俺、お前に何かしたっけ？"

# クリス
# あ、ううん、なんでもない！\nそれよりも頼みごとってなんなのさ。
194 = "あ、ううん、なんでもない！\\nそれよりも頼みごとってなんなのさ。"

# カズマ
# 金を稼ぐ手段を思いついてさ、\nぜひクリスにも力を貸して欲しいんだ。
327 = "金を稼ぐ手段を思いついてさ、\\nぜひクリスにも力を貸して欲しいんだ。"

# クリス
# うーん、その内容によるかな。
206 = "うーん、その内容によるかな。"

# ダクネス
# 難しいことは何もない。\n喫茶店のウェイトレスをするだけだ。
328 = "難しいことは何もない。\\n喫茶店のウェイトレスをするだけだ。"

# クリス
# でーも、ただの喫茶店じゃないんだよね？
230 = "でーも、ただの喫茶店じゃないんだよね？"

# ダクネス
# さすが、するどいな。
214 = "さすが、するどいな。"

# クリス
# それで？　どんな喫茶店なわけ？
225 = "それで？　どんな喫茶店なわけ？"

# カズマ
# ずばり！　メイド喫茶だ！
219 = "ずばり！　メイド喫茶だ！"

# クリス
# 何それ……。
260 = "何それ……。"

# ダクネス
# メイド、つまり使用人がご主人様に奉仕をする\n喫茶店だ！
252 = "メイド、つまり使用人がご主人様に奉仕をする\\n喫茶店だ！"

# クリス
# ごめん、そういうの無理だから。
212 = "ごめん、そういうの無理だから。"

# カズマ
# 違う、違う、ちがーう！！
326 = "違う、違う、ちがーう！！"

# クリス
# 何が違うっていうのさ。
259 = "何が違うっていうのさ。"

# カズマ
# ダクネスは、個人の趣味として腐った妄想を\nしてるだけなんだよ！
250 = "ダクネスは、個人の趣味として腐った妄想を\\nしてるだけなんだよ！"

# ダクネス
# 腐った！？
324 = "腐った！？"

# カズマ
# 奉仕をするってのは本当だけど、\nそれはメイドになりきって接客するだけだから！
267 = "奉仕をするってのは本当だけど、\\nそれはメイドになりきって接客するだけだから！"

# クリス
# ああ、なんとなく理解した。\nつまり普通の喫茶店にはない手厚い接客をするって\nことだね？
196 = "ああ、なんとなく理解した。\\nつまり普通の喫茶店にはない手厚い接客をするって\\nことだね？"

# カズマ
# そう、手厚い接客！　まさにそれ！
220 = "そう、手厚い接客！　まさにそれ！"

# クリス
# 確かに男の人が喜びそうではあるね。\nでも、あたしである理由がなくない？
323 = "確かに男の人が喜びそうではあるね。\\nでも、あたしである理由がなくない？"

# カズマ
# メイドの第一条件はなんだと思う。
253 = "メイドの第一条件はなんだと思う。"

# クリス
# そんなの知らないよ。
228 = "そんなの知らないよ。"

# カズマ
# それは可愛いことだ。\nほら、クリスにぴったり。
227 = "それは可愛いことだ。\\nほら、クリスにぴったり。"

# クリス
# ちょっと、可愛いって！
229 = "ちょっと、可愛いって！"

# カズマ
# クリスっ！　この通りだ頼むよ！\n俺が考える喫茶店には、お前が必要不可欠なんだ！
248 = "クリスっ！　この通りだ頼むよ！\\n俺が考える喫茶店には、お前が必要不可欠なんだ！"

# クリス
# う、うーん……。
202 = "う、うーん……。"

# ダクネス
# クリス、せっかくだし一緒にやらないか？
247 = "クリス、せっかくだし一緒にやらないか？"

# クリス
# ダクネスもやるんだよね？
251 = "ダクネスもやるんだよね？"

# ダクネス
# 当然だっ！
270 = "当然だっ！"

# カズマ
# 鼻息を荒くして言うな。\nまた変な誤解をされるだろう。
329 = "鼻息を荒くして言うな。\\nまた変な誤解をされるだろう。"

# クリス
# はぁ、先に言っておくけど、\nあたしに女の子っぽさを求められても無理だからね。
236 = "はぁ、先に言っておくけど、\\nあたしに女の子っぽさを求められても無理だからね。"

# カズマ
# じゃあ！
218 = "じゃあ！"

# クリス
# うん、手伝うよ。\nキミの指が切れられる所なんて見たくないし。
205 = "うん、手伝うよ。\\nキミの指が切れられる所なんて見たくないし。"

# カズマ
# おお、マジか！！\nありがとう、クリス！！
210 = "おお、マジか！！\\nありがとう、クリス！！"

# カズマ（Ｍ）
# display as カズマ
# （さてあとは、\n　ギルドで場所提供の交渉をするだけだな）
331 = "（さてあとは、\\n　ギルドで場所提供の交渉をするだけだな）"

[selections]
256 = "体調でも悪いのか？"
258 = "何か悩み事でもあるのか？"
216 = "さては俺に恋を！"
