# st01b_15.txt.scn

[info]
224 = "st01b_15"

[characters]
311 = "アクア"
313 = "カズマ"
308 = "ゆんゆん"
306 = "めぐみん"
318 = "ダクネス"
316 = "カズマ（Ｍ）"
312 = "ウィズ"
317 = "クリス"

[character_subs]
# 313 = "カズマ"

[script]
# lines: 86

# アクア
# メイド喫茶オープンでーす。\nみなさーん、よろしくお願いしまーす。
322 = "メイド喫茶オープンでーす。\\nみなさーん、よろしくお願いしまーす。"

# カズマ
# なあ、いつまでもそんなところに隠れてないで\nチラシ配りを手伝ってくれよ。
290 = "なあ、いつまでもそんなところに隠れてないで\\nチラシ配りを手伝ってくれよ。"

# ゆんゆん
# で、でもぉ～、この格好で人前に立つのは\n恥ずかしいです。
285 = "で、でもぉ～、この格好で人前に立つのは\\n恥ずかしいです。"

# カズマ
# 気持ちはわかるけど、アクアの羞恥心の無さを\n少しは見習えって。
333 = "気持ちはわかるけど、アクアの羞恥心の無さを\\n少しは見習えって。"

# めぐみん
# それって褒めてるんですか？\n褒めてませんよね？
279 = "それって褒めてるんですか？\\n褒めてませんよね？"

# カズマ
# ほーら、ダクネス。\nお前はこういうの大好物だろ？
303 = "ほーら、ダクネス。\\nお前はこういうの大好物だろ？"

# ダクネス
# %fsyogen;何を言っている！\n年甲斐も無いこんな格好を男共に晒すなんて、\n屈辱でしかないだろう！
24 = "%fsyogen;何を言っている！\\n年甲斐も無いこんな格好を男共に晒すなんて、\\n屈辱でしかないだろう！"

# カズマ（Ｍ）
# display as カズマ
# （いきなりダクネスとは思えない発言だぞ。\n　ただのメイド服じゃないか？\n　いったいどうした？）
394 = "（いきなりダクネスとは思えない発言だぞ。\\n　ただのメイド服じゃないか？\\n　いったいどうした？）"

# カズマ（Ｍ）
# display as カズマ
# （それともララティーナ様は\n　庶民の服が恥ずかしいとでもいうのか？）
397 = "（それともララティーナ様は\\n　庶民の服が恥ずかしいとでもいうのか？）"

# カズマ（Ｍ）
# display as カズマ
# （はっ、もしや、パンツを盗まれているのは\n　ダクネスで正解なのか？）
399 = "（はっ、もしや、パンツを盗まれているのは\\n　ダクネスで正解なのか？）"

# カズマ（Ｍ）
# display as カズマ
# （これは証言ゲットしかないな！）
396 = "（これは証言ゲットしかないな！）"

# ダクネス
# しかも見てみろ。\nアクアを見る、あのいやらしい目を！
274 = "しかも見てみろ。\\nアクアを見る、あのいやらしい目を！"

# ダクネス
# きっとあいつらはこう思っているに違いない。
269 = "きっとあいつらはこう思っているに違いない。"

# ダクネス
# このメイドを家に連れて帰り、世話という名目で\nありとあらゆるプレイをしてやろうと！
271 = "このメイドを家に連れて帰り、世話という名目で\\nありとあらゆるプレイをしてやろうと！"

# ダクネス
# はっ、もしかしてそうなのか！\nメイド喫茶というのは表向きの顔で、\n裏ではメイドを――
300 = "はっ、もしかしてそうなのか！\\nメイド喫茶というのは表向きの顔で、\\n裏ではメイドを――"

# ダクネス
# カズマっ、お前はなんて男なんだ！\nさあ、早くチラシを寄こせ！
315 = "カズマっ、お前はなんて男なんだ！\\nさあ、早くチラシを寄こせ！"

# ダクネス
# １００枚でも２００枚でも配ってやるぅ！
406 = "１００枚でも２００枚でも配ってやるぅ！"

# カズマ
# はいはい、よろしく頼むぞ、ダクネス。
299 = "はいはい、よろしく頼むぞ、ダクネス。"

# ダクネス
# では、行ってくる！！
286 = "では、行ってくる！！"

# ウィズ
# ええと、ダクネスさんが仰ってたことは……。
264 = "ええと、ダクネスさんが仰ってたことは……。"

# カズマ
# あれはダクネスの趣味だ。\n気にするな。
258 = "あれはダクネスの趣味だ。\\n気にするな。"

# ダクネス
# メイド喫茶オープンでぇす！
321 = "メイド喫茶オープンでぇす！"

# めぐみん
# カズマ。\nアクアとダクネスに任せるではダメなのですか？
314 = "カズマ。\\nアクアとダクネスに任せるではダメなのですか？"

# カズマ
# これは、お前たちがその格好で人前に出る\n予行練習も兼ねてるんだよ。
272 = "これは、お前たちがその格好で人前に出る\\n予行練習も兼ねてるんだよ。"

# ウィズ
# 確かにいきなり本番はマズイですもんね。
388 = "確かにいきなり本番はマズイですもんね。"

# カズマ
# だろ？
283 = "だろ？"

# ウィズ
# 私も行ってきますね。\nダクネスさんとアクア様に任せてしまう\n訳にはいきませんし。
389 = "私も行ってきますね。\\nダクネスさんとアクア様に任せてしまう\\n訳にはいきませんし。"

# カズマ
# おう、よろしく頼む。
268 = "おう、よろしく頼む。"

# ゆんゆん
# ねえ、めぐみんどうするの？
297 = "ねえ、めぐみんどうするの？"

# めぐみん
# なぜ私に決定権を押しつけるんですか、\n卑怯ですよ、そういうの。
292 = "なぜ私に決定権を押しつけるんですか、\\n卑怯ですよ、そういうの。"

# ゆんゆん
# べ、別に、そういう意味で聞いたんじゃ！
302 = "べ、別に、そういう意味で聞いたんじゃ！"

# カズマ
# なあ、ふたりも頼むよ。
291 = "なあ、ふたりも頼むよ。"

# カズマ
# むしろ、お前たちにやって貰わないと困るんだって。
305 = "むしろ、お前たちにやって貰わないと困るんだって。"

# ゆんゆん
# どうしてですか？
288 = "どうしてですか？"

# カズマ
# どう考えても、めぐみんとゆんゆんが\n人気を持っていくからな。
289 = "どう考えても、めぐみんとゆんゆんが\\n人気を持っていくからな。"

# カズマ
# つまり、このプロジェクトの成否は\nふたりにかかってるんだ。
284 = "つまり、このプロジェクトの成否は\\nふたりにかかってるんだ。"

# めぐみん
# そ、そうだったのですか。
275 = "そ、そうだったのですか。"

# カズマ
# あー、どっちが店のナンバーワンになるかなー。
259 = "あー、どっちが店のナンバーワンになるかなー。"

# カズマ
# こういうのはスタートダッシュが大切だって聞くし、\nこのチラシ配りが以外に大きな意味を持つかもなー。
270 = "こういうのはスタートダッシュが大切だって聞くし、\\nこのチラシ配りが以外に大きな意味を持つかもなー。"

# ゆんゆん
# わ、私、配ってきますね！
309 = "わ、私、配ってきますね！"

# めぐみん
# あっ、ちょっとずるいですよ、ゆんゆん！
255 = "あっ、ちょっとずるいですよ、ゆんゆん！"

# カズマ（Ｍ）
# display as カズマ
# （ふっ、チョロイ）
401 = "（ふっ、チョロイ）"

# クリス
# ねえ、あれだけ人がいれば、\nあたしまでやる必要は無いよね？
296 = "ねえ、あれだけ人がいれば、\\nあたしまでやる必要は無いよね？"

# カズマ
# さっきも言ったけど、これは予行練習も\n兼ねてるんだよ。
273 = "さっきも言ったけど、これは予行練習も\\n兼ねてるんだよ。"

# カズマ
# それにみんなにどんなメイドがいるかを\n見せる場でもあるんだから、お前も行かないと\nダメだ。
280 = "それにみんなにどんなメイドがいるかを\\n見せる場でもあるんだから、お前も行かないと\\nダメだ。"

# クリス
# うぅ、でも……。
262 = "うぅ、でも……。"

# カズマ
# なんだ、やっぱりスカートが気になるのか？
293 = "なんだ、やっぱりスカートが気になるのか？"

# クリス
# だって、どこから見られてるかわからないし、\nそれに風もちょっと吹いてるから……。
282 = "だって、どこから見られてるかわからないし、\\nそれに風もちょっと吹いてるから……。"

# クリス
# あっ、もしかしてわざと？\n気づいててわざとやってるわけ？
256 = "あっ、もしかしてわざと？\\n気づいててわざとやってるわけ？"

# カズマ
# わざとって何をだよ。
310 = "わざとって何をだよ。"

# クリス
# そ、それは……。
276 = "そ、それは……。"

# クリス
# はぁ、いいよもう、行くから……。
298 = "はぁ、いいよもう、行くから……。"

# クリス
# %fsyogen;でも、もし見えちゃったら、\n責任は取ってもらうからね？
23 = "%fsyogen;でも、もし見えちゃったら、\\n責任は取ってもらうからね？"

# カズマ（Ｍ）
# display as カズマ
# （責任って、パンツを見られたくらいで\n　大袈裟だろ）
405 = "（責任って、パンツを見られたくらいで\\n　大袈裟だろ）"

# カズマ（Ｍ）
# display as カズマ
# （はっ。\n　もしかして、これはパンツ以外のものが\n　見えてしまうフラグなのか！？）
400 = "（はっ。\\n　もしかして、これはパンツ以外のものが\\n　見えてしまうフラグなのか！？）"

# カズマ（Ｍ）
# display as カズマ
# （い、いかんぞ！\n　俺は紳士だ。\n　そんなことを考えてはいけない！）
392 = "（い、いかんぞ！\\n　俺は紳士だ。\\n　そんなことを考えてはいけない！）"

# カズマ（Ｍ）
# display as カズマ
# （い、一応、証言として\n　ゲットしておこう！）
393 = "（い、一応、証言として\\n　ゲットしておこう！）"

# カズマ（Ｍ）
# display as カズマ
# （それにしても責任って、\n　大袈裟だよな……）
398 = "（それにしても責任って、\\n　大袈裟だよな……）"

# カズマ（Ｍ）
# display as カズマ
# （いや女の子にとっては、\n　それくらい重要なことなのかもしれないな）
395 = "（いや女の子にとっては、\\n　それくらい重要なことなのかもしれないな）"

# カズマ
# 安心しろ。\n責任なんていくらでも取ってやるさ！
330 = "安心しろ。\\n責任なんていくらでも取ってやるさ！"

# クリス
# え？
265 = "え？"

# カズマ
# なんだかよくわからないけど、\nそれでクリスがやる気になってくれるなら、\n安いもんだ。
294 = "なんだかよくわからないけど、\\nそれでクリスがやる気になってくれるなら、\\n安いもんだ。"

# クリス
# いや、別に本気で言ったわけじゃ……。
260 = "いや、別に本気で言ったわけじゃ……。"

# クリス
# でもまあ、そこまで言うんだったら行ってあげるよ。\nうん。仕方ないから。
287 = "でもまあ、そこまで言うんだったら行ってあげるよ。\\nうん。仕方ないから。"

# カズマ
# そうか。助かるよ。
277 = "そうか。助かるよ。"

# クリス
# ……じゃ。
253 = "……じゃ。"

# カズマ
# 任せろ。\n見えそうになったら俺が守ってやる！
324 = "任せろ。\\n見えそうになったら俺が守ってやる！"

# クリス
# 守るって……。
329 = "守るって……。"

# カズマ
# なんだったら、俺がずっと抑えててやろうか？
295 = "なんだったら、俺がずっと抑えててやろうか？"

# クリス
# それ、セクハラっ！
278 = "それ、セクハラっ！"

# カズマ
# ハハ、悪い悪い。
320 = "ハハ、悪い悪い。"

# クリス
# もう、しょうがないなぁ。\n本当に気づいてないみたいだし。
307 = "もう、しょうがないなぁ。\\n本当に気づいてないみたいだし。"

# カズマ
# いや、気がついてるよ。
261 = "いや、気がついてるよ。"

# クリス
# ええ、そうなの！？
263 = "ええ、そうなの！？"

# カズマ
# ふふ、俺をいいなって思ってるんだろ？
301 = "ふふ、俺をいいなって思ってるんだろ？"

# クリス
# チラシ配ってくるね。
319 = "チラシ配ってくるね。"

# カズマ
# おい、渾身のボケをスルーするなよ！
267 = "おい、渾身のボケをスルーするなよ！"

# クリス
# ああ、もう、やっぱりスースーするよ。
254 = "ああ、もう、やっぱりスースーするよ。"

# カズマ
# 大丈夫だ。\n見えない構造になってるから！
328 = "大丈夫だ。\\n見えない構造になってるから！"

# クリス
# それは嘘だね。\nダクネスのでちゃんと確かめたんだから。
281 = "それは嘘だね。\\nダクネスのでちゃんと確かめたんだから。"

# カズマ（Ｍ）
# display as カズマ
# （確かめたって何をどうやって！）
404 = "（確かめたって何をどうやって！）"

# クリス
# まあ、本当に気づいてないならもういいよ。\n行けばいいんでしょ、行けば。
304 = "まあ、本当に気づいてないならもういいよ。\\n行けばいいんでしょ、行けば。"

# カズマ
# お、おう。
266 = "お、おう。"

# クリス
# あっ！\nあたしの後ろに立ったら、怒るからね。
257 = "あっ！\\nあたしの後ろに立ったら、怒るからね。"

# カズマ（Ｍ）
# display as カズマ
# （まだスカートを気にしてるし）
402 = "（まだスカートを気にしてるし）"

# カズマ（Ｍ）
# display as カズマ
# （店を開くまでに慣れてくれると助かるんだけど）
403 = "（店を開くまでに慣れてくれると助かるんだけど）"

[selections]
391 = "責任なんていくらでも取ってやるさ！"
390 = "見えそうになったら俺が守ってやる！"
327 = "大丈夫。見えない構造になってるから！"
