# st01b_06.txt.scn

[info]
109 = "st01b_06"

[characters]
152 = "カズマ"
151 = "アクア"
148 = "めぐみん"
153 = "ダクネス"

[character_subs]

[script]
# lines: 31

# カズマ
# みんないるか！
145 = "みんないるか！"

# アクア
# ちょっと、何よ。\nびっくりするじゃない。
136 = "ちょっと、何よ。\\nびっくりするじゃない。"

# めぐみん
# 血相を変えてどうしたんです？\nパンツを盗んだことがバレて、\n警察に捕まりそうになったんですか？
182 = "血相を変えてどうしたんです？\\nパンツを盗んだことがバレて、\\n警察に捕まりそうになったんですか？"

# カズマ
# 違うわ！\n金を稼ぐ方法を思いついたんだよ！
183 = "違うわ！\\n金を稼ぐ方法を思いついたんだよ！"

# ダクネス
# ほう。それはぜひ聞かせて欲しいな。
143 = "ほう。それはぜひ聞かせて欲しいな。"

# カズマ
# まずはこれを見てくれ。
144 = "まずはこれを見てくれ。"

# ダクネス
# ん？　メイドの服に似ているな。
150 = "ん？　メイドの服に似ているな。"

# めぐみん
# それにしては派手ですよ。\nスカートの丈も短いですし。
135 = "それにしては派手ですよ。\\nスカートの丈も短いですし。"

# めぐみん
# こんな格好で給仕なんてできるわけありません。
131 = "こんな格好で給仕なんてできるわけありません。"

# アクア
# ううん、残念ながら、これはメイド服で\n間違いないわ。
128 = "ううん、残念ながら、これはメイド服で\\n間違いないわ。"

# ダクネス
# そうなのか。\n世界は広いのだな。
133 = "そうなのか。\\n世界は広いのだな。"

# アクア
# で、何を考えてるのよ。\n正直、嫌な予感しかしないんですけど。
138 = "で、何を考えてるのよ。\\n正直、嫌な予感しかしないんですけど。"

# めぐみん
# はっ！？　まさか、それを着て\n私たちに使用人として働いて来いと？
141 = "はっ！？　まさか、それを着て\\n私たちに使用人として働いて来いと？"

# カズマ
# んー、おしい。\nこれを着てもらう所までは合ってる。
149 = "んー、おしい。\\nこれを着てもらう所までは合ってる。"

# ダクネス
# 使用人として働くわけでもないのに\nこんな物を着てどうする？
155 = "使用人として働くわけでもないのに\\nこんな物を着てどうする？"

# カズマ
# ふふーん、わからないか。まあ無理もない。\nこの世界にそんな文化はないだろうしな。
142 = "ふふーん、わからないか。まあ無理もない。\\nこの世界にそんな文化はないだろうしな。"

# アクア
# あんた、やっぱりアレをやるつもりなのね。
125 = "あんた、やっぱりアレをやるつもりなのね。"

# カズマ
# お、さすが元日本担当。\n察しが良いじゃないか。
130 = "お、さすが元日本担当。\\n察しが良いじゃないか。"

# アクア
# 元じゃなくて現役なんですけど！
156 = "元じゃなくて現役なんですけど！"

# アクア
# っていうか、女神である私に\nなんてことさせようとしてるのよ、このヒキオタは。
137 = "っていうか、女神である私に\\nなんてことさせようとしてるのよ、このヒキオタは。"

# カズマ
# いいだろ別に。\n何か失うわけでもないんだし。
127 = "いいだろ別に。\\n何か失うわけでもないんだし。"

# カズマ
# むしろ信者が増えるかもしれないぞ？
146 = "むしろ信者が増えるかもしれないぞ？"

# アクア
# え、ほんとに？
129 = "え、ほんとに？"

# カズマ
# そこであっさり信じちまうから\nお前は駄女神なんだよ。
134 = "そこであっさり信じちまうから\\nお前は駄女神なんだよ。"

# アクア
# なんですって！
140 = "なんですって！"

# めぐみん
# 待ってください。\n２人だけで話を進めないでくださいよ。
160 = "待ってください。\\n２人だけで話を進めないでくださいよ。"

# ダクネス
# そうだ。\n私たちにもわかるようにちゃんと説明してくれ。
132 = "そうだ。\\n私たちにもわかるようにちゃんと説明してくれ。"

# カズマ
# あー、つまり、お前たちにはこのメイド服を着て、\n喫茶店の店員として働いてもらいたいわけだ。
126 = "あー、つまり、お前たちにはこのメイド服を着て、\\n喫茶店の店員として働いてもらいたいわけだ。"

# ダクネス
# 喫茶店で働くのに、\nどうして使用人の服を着なくてはならないんだ？
158 = "喫茶店で働くのに、\\nどうして使用人の服を着なくてはならないんだ？"

# カズマ
# どうしてって、\n俺がやろうとしてるのがメイド喫茶だからだ！
139 = "どうしてって、\\n俺がやろうとしてるのがメイド喫茶だからだ！"

# めぐみん
# めいどきっさ？
147 = "めいどきっさ？"

