# st01b_12.txt.scn

[info]
122 = "st01b_12"

[characters]
159 = "カズマ"
156 = "めぐみん"
160 = "ダクネス"
158 = "アクア"

[character_subs]

[script]
# lines: 21

# カズマ
# さて、これで準備の第一段階が終了だ。
147 = "さて、これで準備の第一段階が終了だ。"

# めぐみん
# まだ他にしないといけないことがあるんですか？
154 = "まだ他にしないといけないことがあるんですか？"

# ダクネス
# 人員を集めて場所を確保したのだから、\nあとは店を開くだけだろう。
164 = "人員を集めて場所を確保したのだから、\\nあとは店を開くだけだろう。"

# カズマ
# 甘いっ、甘すぎる！\nお前たちはやっぱりメイドを何もわかってない！\nほんとにもう、がっかりだよ！
168 = "甘いっ、甘すぎる！\\nお前たちはやっぱりメイドを何もわかってない！\\nほんとにもう、がっかりだよ！"

# アクア
# あー、もう、つばが飛んでる！
140 = "あー、もう、つばが飛んでる！"

# カズマ
# というわけで、これからお前たちには\nメイドの作法を身に付けてもらう。
150 = "というわけで、これからお前たちには\\nメイドの作法を身に付けてもらう。"

# ダクネス
# おお！
145 = "おお！"

# カズマ
# お前が考えてるようなことじゃないからな。
146 = "お前が考えてるようなことじゃないからな。"

# ダクネス
# お、おお……。
144 = "お、おお……。"

# カズマ
# いいか、普通に接客するだけだったら、\nそんなのウェイトレスがメイド服を着てるだけの\nちょっと変な喫茶店としか見て貰えない。
141 = "いいか、普通に接客するだけだったら、\\nそんなのウェイトレスがメイド服を着てるだけの\\nちょっと変な喫茶店としか見て貰えない。"

# カズマ
# メイド喫茶というからには、\nメイドさんにお世話してもらえるという\n非日常の空間を提供しなくちゃいけないんだ。
162 = "メイド喫茶というからには、\\nメイドさんにお世話してもらえるという\\n非日常の空間を提供しなくちゃいけないんだ。"

# カズマ
# そうしたこだわりから作られた特異性が、\nリピーターを生み出し、結果として、はいめぐみん！
148 = "そうしたこだわりから作られた特異性が、\\nリピーターを生み出し、結果として、はいめぐみん！"

# めぐみん
# え、ええと、店を潤わす？
142 = "え、ええと、店を潤わす？"

# カズマ
# はい、よくできました。花丸あげます。
152 = "はい、よくできました。花丸あげます。"

# めぐみん
# なんなんですかこの変なテンションは。
151 = "なんなんですかこの変なテンションは。"

# ダクネス
# ハハ、少し付き合おうじゃないか。
161 = "ハハ、少し付き合おうじゃないか。"

# アクア
# ちょっと待って。\nまさか私たちに、もえもえきゅーん、\nとかいうのをやらせるつもりじゃないでしょうね。
149 = "ちょっと待って。\\nまさか私たちに、もえもえきゅーん、\\nとかいうのをやらせるつもりじゃないでしょうね。"

# カズマ
# ふっ、必要とあれば。
153 = "ふっ、必要とあれば。"

# アクア
# えー……。
143 = "えー……。"

# カズマ
# よーし。\nそうと決まれば改めて全員集合だ。\nウィズとゆんゆんとクリスを呼んできてくれ。
157 = "よーし。\\nそうと決まれば改めて全員集合だ。\\nウィズとゆんゆんとクリスを呼んできてくれ。"

# カズマ
# みんなが揃ったらメイドの特訓を始めるぞ！
155 = "みんなが揃ったらメイドの特訓を始めるぞ！"

