# st01b_09.txt.scn

[info]
101 = "st01b_09"

[characters]
193 = "カズマ"
190 = "ウィズ"
181 = "めぐみん"
183 = "ゆんゆん"
197 = "カズマ（Ｍ）"

[character_subs]
# 193 = "カズマ"

[script]
# lines: 61

# カズマ
# よう、ウィズ。\nまた来たぞー。
186 = "よう、ウィズ。\\nまた来たぞー。"

# ウィズ
# あ、カズマさん。\nそれにめぐみんさんもいらっしゃいませ。
150 = "あ、カズマさん。\\nそれにめぐみんさんもいらっしゃいませ。"

# めぐみん
# カズマ、やっぱりいましたよ。
194 = "カズマ、やっぱりいましたよ。"

# ゆんゆん
# え？　え？　なんなのめぐみん？\nもしかして私を捜してたの？
161 = "え？　え？　なんなのめぐみん？\\nもしかして私を捜してたの？"

# めぐみん
# ええ、ちょっとお願いしたいことがありまして。
155 = "ええ、ちょっとお願いしたいことがありまして。"

# ゆんゆん
# もうしょうがないわねー。\n同胞のめぐみんの頼みだもの、なんでも聞いて\nあげるわ。
182 = "もうしょうがないわねー。\\n同胞のめぐみんの頼みだもの、なんでも聞いて\\nあげるわ。"

# めぐみん
# 本当ですか？
207 = "本当ですか？"

# ゆんゆん
# 当然よ！
206 = "当然よ！"

# めぐみん
# じゃあ、メイド服を着てください。
167 = "じゃあ、メイド服を着てください。"

# ゆんゆん
# へ？
178 = "へ？"

# めぐみん
# カズマ、後の説明は任せます。
196 = "カズマ、後の説明は任せます。"

# カズマ
# ゆんゆん、それにウィズ。\n金を稼ぐために２人の力を借りたいんだ！
184 = "ゆんゆん、それにウィズ。\\n金を稼ぐために２人の力を借りたいんだ！"

# ウィズ
# 私にできることでしたら協力を惜しむつもりは\nありませんが――
244 = "私にできることでしたら協力を惜しむつもりは\\nありませんが――"

# ゆんゆん
# できたら先に、何をするのか教えていただけると。
175 = "できたら先に、何をするのか教えていただけると。"

# カズマ
# それはずばり、メイド喫茶だ！
172 = "それはずばり、メイド喫茶だ！"

# ゆんゆん
# め、めいどきっさ？
180 = "め、めいどきっさ？"

# カズマ
# 簡単に言うと、ウェイトレスがメイド服姿で\n接客をしてくれる喫茶店だな。
245 = "簡単に言うと、ウェイトレスがメイド服姿で\\n接客をしてくれる喫茶店だな。"

# カズマ
# その店のウェイトレスをふたりにぜひ頼みたい。
170 = "その店のウェイトレスをふたりにぜひ頼みたい。"

# ウィズ
# ええと、メイド服というのは、\n先ほど購入していただいたあの服のことですよね？
157 = "ええと、メイド服というのは、\\n先ほど購入していただいたあの服のことですよね？"

# カズマ
# ああ、ウィズとゆんゆんがメイド服姿で接客して\nくれれば、繁盛間違い無しだと思うんだよ。
151 = "ああ、ウィズとゆんゆんがメイド服姿で接客して\\nくれれば、繁盛間違い無しだと思うんだよ。"

# ウィズ
# 確かにゆんゆんさんは戦力になると思います。\nですが、私はどうでしょう。
243 = "確かにゆんゆんさんは戦力になると思います。\\nですが、私はどうでしょう。"

# ウィズ
# ああいう服は、可愛らしい女の子が着るからこそ、\n魅力が引き立つものだと思うんです。
152 = "ああいう服は、可愛らしい女の子が着るからこそ、\\n魅力が引き立つものだと思うんです。"

# カズマ
# ウィズだって十分に可愛いじゃないか。
191 = "ウィズだって十分に可愛いじゃないか。"

# ウィズ
# そ、そう言っていただけるのは嬉しいのですが、\nええと、き、着た実感として不相応かなって。
168 = "そ、そう言っていただけるのは嬉しいのですが、\\nええと、き、着た実感として不相応かなって。"

# カズマ（Ｍ）
# display as カズマ
# （着たのか！）
254 = "（着たのか！）"

# ウィズ
# 食器洗いとかお料理でしたら、\n協力を惜しみませんが……。
248 = "食器洗いとかお料理でしたら、\\n協力を惜しみませんが……。"

# カズマ
# ウェイトレスをしてくれないと困るんだよ！
192 = "ウェイトレスをしてくれないと困るんだよ！"

# ウィズ
# ど、どうしてですか？
177 = "ど、どうしてですか？"

# めぐみん
# この世は需要と供給で成り立っているからです。
165 = "この世は需要と供給で成り立っているからです。"

# ウィズ
# え？　え？
159 = "え？　え？"

# カズマ
# 頼むよウィズ！　この通り！！
247 = "頼むよウィズ！　この通り！！"

# ウィズ
# うぅ、わ、わかりました。\nでも本当に似合いませんからね？\n後でがっかりしないでくださいよ？
154 = "うぅ、わ、わかりました。\\nでも本当に似合いませんからね？\\n後でがっかりしないでくださいよ？"

# カズマ（Ｍ）
# display as カズマ
# （よし、これでウィズは確保っと）
252 = "（よし、これでウィズは確保っと）"

# めぐみん
# カズマ、カズマ。
195 = "カズマ、カズマ。"

# カズマ
# ん、どうした？
187 = "ん、どうした？"

# めぐみん
# こっちの説得はどうするんですか？
164 = "こっちの説得はどうするんですか？"

# カズマ（Ｍ）
# display as カズマ
# （こっち？）
250 = "（こっち？）"

# ゆんゆん
# ウ、ウェイトレス……つまり、接客業。
188 = "ウ、ウェイトレス……つまり、接客業。"

# カズマ
# ええと、これ、どうしたんだ？\nゆんゆん、顔が真っ青じゃないか。
156 = "ええと、これ、どうしたんだ？\\nゆんゆん、顔が真っ青じゃないか。"

# めぐみん
# おそらく人見知りが発動して、\nしり込みしているのでしょう。
163 = "おそらく人見知りが発動して、\\nしり込みしているのでしょう。"

# カズマ（Ｍ）
# display as カズマ
# （あー……）
249 = "（あー……）"

# めぐみん
# まったく、しょうがありませんね。
179 = "まったく、しょうがありませんね。"

# めぐみん
# ゆんゆんは戦力になりそうにありませんし、\n誘うのはやめましょう。
185 = "ゆんゆんは戦力になりそうにありませんし、\\n誘うのはやめましょう。"

# ゆんゆん
# え！？
158 = "え！？"

# めぐみん
# 大丈夫ですよ、ゆんゆんの分も私が働きますから。\nそれでいいですよね、カズマ。
203 = "大丈夫ですよ、ゆんゆんの分も私が働きますから。\\nそれでいいですよね、カズマ。"

# ゆんゆん
# ちょ、ちょっと待ってよ！\nまだ私は何も言ってないじゃない！
174 = "ちょ、ちょっと待ってよ！\\nまだ私は何も言ってないじゃない！"

# めぐみん
# 言わなくてもわかります。\n無理なんでしょ？　不可能なんですよね？
246 = "言わなくてもわかります。\\n無理なんでしょ？　不可能なんですよね？"

# めぐみん
# 次の満月まで一ヶ月をもう切っているんです。\n時間を浪費しないためにも、無理なら無理と\n今すぐに言ってください。
208 = "次の満月まで一ヶ月をもう切っているんです。\\n時間を浪費しないためにも、無理なら無理と\\n今すぐに言ってください。"

# めぐみん
# さあさあ、今すぐに！\n無理だと、さあ！
166 = "さあさあ、今すぐに！\\n無理だと、さあ！"

# ゆんゆん
# ウ、ウェイトレスくらいできるったら！
189 = "ウ、ウェイトレスくらいできるったら！"

# めぐみん
# というわけでカズマ。\nゆんゆんも確保です。
176 = "というわけでカズマ。\\nゆんゆんも確保です。"

# ゆんゆん
# え？　え？　ええーー！？
160 = "え？　え？　ええーー！？"

# カズマ
# おいおい、めちゃくちゃ動揺してるんだけど、\n本当にいいのか？
162 = "おいおい、めちゃくちゃ動揺してるんだけど、\\n本当にいいのか？"

# めぐみん
# 問題ありません。
202 = "問題ありません。"

# カズマ
# 何を根拠に……。
199 = "何を根拠に……。"

# めぐみん
# その辺のケアはちゃんとしますから\n心配しないでください。
171 = "その辺のケアはちゃんとしますから\\n心配しないでください。"

# めぐみん
# それよりも今は、クリスの説得を優先すべき\nでしょう。
173 = "それよりも今は、クリスの説得を優先すべき\\nでしょう。"

# めぐみん
# あまりのんびり構えていられる状況でも\nないんですから。
153 = "あまりのんびり構えていられる状況でも\\nないんですから。"

# カズマ
# そうだな。
169 = "そうだな。"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスは街を捜してみるって言ってたよな）
253 = "（ダクネスは街を捜してみるって言ってたよな）"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、ケータイがないのって本当不便）
251 = "（はぁ、ケータイがないのって本当不便）"

