# st01a_07.txt.scn

[info]
37 = "st01a_07"

[characters]
52 = "カズマ（Ｍ）"

[character_subs]
51 = "カズマ"

[script]
# lines: 3

# カズマ（Ｍ）
# display as カズマ
# （結局、その場で\n　アイデアがまとまることはなかった）
55 = "（結局、その場で\\n　アイデアがまとまることはなかった）"

# カズマ（Ｍ）
# display as カズマ
# （無理もない。\n　そんな簡単に大金を稼ぐ手段があるなら、\n　誰も苦労などしていないだろう）
54 = "（無理もない。\\n　そんな簡単に大金を稼ぐ手段があるなら、\\n　誰も苦労などしていないだろう）"

# カズマ（Ｍ）
# display as カズマ
# （ひとまず、しばらくは簡単なクエストをこなし\n　ながら、指輪を外す方法と金を稼ぐ手段を探そう、\n　ということで話は落ち着いたのだが……）
53 = "（ひとまず、しばらくは簡単なクエストをこなし\\n　ながら、指輪を外す方法と金を稼ぐ手段を探そう、\\n　ということで話は落ち着いたのだが……）"

