# st01a_02.txt.scn

[info]
159 = "st01a_02"

[characters]
233 = "ダクネス"
232 = "クリス"
226 = "アクア"
230 = "カズマ"
228 = "ウィズ"
231 = "カズマ（Ｍ）"
223 = "ゆんゆん"
221 = "めぐみん"
227 = "アクア＆めぐみん"

[character_subs]
# 230 = "カズマ"
296 = "２人"

[script]
# lines: 70

# ダクネス
# 待ってくれクリス。\nそう言わずにカズマに力を\n貸してやってくれないか？
245 = "待ってくれクリス。\\nそう言わずにカズマに力を\\n貸してやってくれないか？"

# クリス
# ダクネス。
234 = "ダクネス。"

# ダクネス
# 盗賊であるお前なら、\n私たちには知りようのない\n情報が入って来るかもしれないし。
251 = "盗賊であるお前なら、\\n私たちには知りようのない\\n情報が入って来るかもしれないし。"

# アクア
# 母数が増えるに越したことはないもんね。
249 = "母数が増えるに越したことはないもんね。"

# クリス
# ぼすう？
216 = "ぼすう？"

# カズマ
# だあああ！\nお前は余計なこと言うんじゃないよ！
203 = "だあああ！\\nお前は余計なこと言うんじゃないよ！"

# アクア
# いったーい！\n何もぶつことないでしょー！
187 = "いったーい！\\n何もぶつことないでしょー！"

# カズマ
# いいから黙ってろよ、お前は！\n今大事なところなんだから！
185 = "いいから黙ってろよ、お前は！\\n今大事なところなんだから！"

# アクア
# そ、そんなきつい言い方しなくてもいいじゃない。
201 = "そ、そんなきつい言い方しなくてもいいじゃない。"

# ウィズ
# まあまあ、アクア様。
219 = "まあまあ、アクア様。"

# カズマ
# なあ頼むよクリス。力を貸してくれ。
210 = "なあ頼むよクリス。力を貸してくれ。"

# クリス
# いや、でも……。
188 = "いや、でも……。"

# カズマ
# パンツのことを気にしてるなら心配いらないって。\n指輪の効果が発動するのは満月の夜だけなんだ。
235 = "パンツのことを気にしてるなら心配いらないって。\\n指輪の効果が発動するのは満月の夜だけなんだ。"

# カズマ
# で、それは昨日発動したばかりで、\n次まで一ヵ月ある。\nだから、それまでに解決するために力を貸してくれ。
206 = "で、それは昨日発動したばかりで、\\n次まで一ヵ月ある。\\nだから、それまでに解決するために力を貸してくれ。"

# クリス
# まあ、それなら。
218 = "まあ、それなら。"

# カズマ
# いいのか？
186 = "いいのか？"

# クリス
# あたしにできる範囲でならね。
183 = "あたしにできる範囲でならね。"

# クリス
# でも、情報を集めるにしても、\nそんな訳のわからないアイテムの話なんて\n本当に聞いたことないし、あんま期待しないでよ。
207 = "でも、情報を集めるにしても、\\nそんな訳のわからないアイテムの話なんて\\n本当に聞いたことないし、あんま期待しないでよ。"

# クリス
# あと、自分でもちゃんと行動すること。
184 = "あと、自分でもちゃんと行動すること。"

# カズマ
# わかってるって。
225 = "わかってるって。"

# カズマ
# まあ一ヵ月もあればバニルも帰って来るかも\nしれないし、最悪、金の問題をどうにか\nすればいいわけだしな。
220 = "まあ一ヵ月もあればバニルも帰って来るかも\\nしれないし、最悪、金の問題をどうにか\\nすればいいわけだしな。"

# アクア
# お気楽ねぇ。\nまだ何ひとつ解決したわけでもないっていうのに。
195 = "お気楽ねぇ。\\nまだ何ひとつ解決したわけでもないっていうのに。"

# カズマ
# ほっとけ。
215 = "ほっとけ。"

# カズマ（Ｍ）
# display as カズマ
# （確かに何も解決はしていない）
295 = "（確かに何も解決はしていない）"

# カズマ（Ｍ）
# display as カズマ
# （だが今のクリスとのやり取りのおかげで、\n　みんなが次の満月までになんとかしよう\n　って雰囲気になってくれたことが重要なんだ）
287 = "（だが今のクリスとのやり取りのおかげで、\\n　みんなが次の満月までになんとかしよう\\n　って雰囲気になってくれたことが重要なんだ）"

# カズマ（Ｍ）
# display as カズマ
# （これでひとまず、いきなり指を\n　切られるようなことはなくなった）
284 = "（これでひとまず、いきなり指を\\n　切られるようなことはなくなった）"

# カズマ（Ｍ）
# display as カズマ
# （まあ実際に指輪をどうするかは\n　おいおい考えて行くとして……）
288 = "（まあ実際に指輪をどうするかは\\n　おいおい考えて行くとして……）"

# カズマ（Ｍ）
# display as カズマ
# （そろそろ\n　もうひとつの問題に取りかかるべきだろう）
286 = "（そろそろ\\n　もうひとつの問題に取りかかるべきだろう）"

# カズマ（Ｍ）
# display as カズマ
# （このパンツが\n　いったい誰の物なのかという問題にな）
283 = "（このパンツが\\n　いったい誰の物なのかという問題にな）"

# ゆんゆん
# カ、カズマさん何をしてるんです！？
229 = "カ、カズマさん何をしてるんです！？"

# カズマ
# え？
191 = "え？"

# アクア
# なんでそんな大事そうにパンツ持ってるのよ。\n正直ドン引きなんですけど。
211 = "なんでそんな大事そうにパンツ持ってるのよ。\\n正直ドン引きなんですけど。"

# カズマ
# 待て待て！\nこれはそういうのじゃなくて、\n持ち主を確認するための作業というかだな！
246 = "待て待て！\\nこれはそういうのじゃなくて、\\n持ち主を確認するための作業というかだな！"

# ダクネス
# 名前が書いてあるわけでもあるまいし、\nじろじろ眺めたところで持ち主など\nわかるわけがあるまい。
242 = "名前が書いてあるわけでもあるまいし、\\nじろじろ眺めたところで持ち主など\\nわかるわけがあるまい。"

# ダクネス
# いや、まさかお前、\nひそかに私たちの部屋をあさって、\n下着の色や形を調べていたのか！？
189 = "いや、まさかお前、\\nひそかに私たちの部屋をあさって、\\n下着の色や形を調べていたのか！？"

# ダクネス
# くっ、男の風上にも置けないやつだ。\n許せない。
196 = "くっ、男の風上にも置けないやつだ。\\n許せない。"

# ダクネス
# しかし、そんな性癖を受け入れるのも\n仲間の勤め――
199 = "しかし、そんな性癖を受け入れるのも\\n仲間の勤め――"

# カズマ（Ｍ）
# display as カズマ
# （暴走したドＭ騎士は置いておいてだ）
293 = "（暴走したドＭ騎士は置いておいてだ）"

# カズマ
# よーしわかった、アクア。\nお前は俺とケンカがしたいんだな。\n受けて立つぞ、表出ろ。
224 = "よーしわかった、アクア。\\nお前は俺とケンカがしたいんだな。\\n受けて立つぞ、表出ろ。"

# アクア
# ふん、ヒキニートが生意気よ。\nいいわ、いますぐエリスの顔を拝ませてあげる！
213 = "ふん、ヒキニートが生意気よ。\\nいいわ、いますぐエリスの顔を拝ませてあげる！"

# ウィズ
# お、落ち着いてくださいふたりとも。
193 = "お、落ち着いてくださいふたりとも。"

# カズマ
# これが落ち着いてられるか！\nどいつもこいつも人のことを変態扱いしやがって！
197 = "これが落ち着いてられるか！\\nどいつもこいつも人のことを変態扱いしやがって！"

# めぐみん
# 日頃の行いの結果ですよ。
248 = "日頃の行いの結果ですよ。"

# めぐみん
# というか、カズマが変態だろうと構いませんから、\nもうそんな物は早く捨ててしまってくださいよ。
209 = "というか、カズマが変態だろうと構いませんから、\\nもうそんな物は早く捨ててしまってくださいよ。"

# カズマ
# え？　捨てろってパンツをか？\nなんでだよ？　ちゃんと持ち主に返さないとだろ？
192 = "え？　捨てろってパンツをか？\\nなんでだよ？　ちゃんと持ち主に返さないとだろ？"

# めぐみん
# 返されても困ると言っているんです。
281 = "返されても困ると言っているんです。"

# カズマ
# 困る？
243 = "困る？"

# クリス
# まあ、この前みたいに盗られたその場でなら\n多少はマシだけど、そんなふうに懐にしまわれたり、\n広げて眺めまわされたのを返されてもね……。
217 = "まあ、この前みたいに盗られたその場でなら\\n多少はマシだけど、そんなふうに懐にしまわれたり、\\n広げて眺めまわされたのを返されてもね……。"

# アクア
# 他にどんなふうに使われたかもわからないし。
237 = "他にどんなふうに使われたかもわからないし。"

# カズマ
# 何もしてねーよ！\n紳士として丁重に扱ってたぞ！
238 = "何もしてねーよ！\\n紳士として丁重に扱ってたぞ！"

# アクア＆めぐみん
# display as ２人
# へえ……。
214 = "へえ……。"

# カズマ（Ｍ）
# display as カズマ
# （くっそ、ゴミを見るような目をしやがって！）
282 = "（くっそ、ゴミを見るような目をしやがって！）"

# カズマ
# それでもこのパンツは\n必ず持ち主に返してやるからな！
202 = "それでもこのパンツは\\n必ず持ち主に返してやるからな！"

# カズマ
# 俺の意思で盗んだわけじゃないし、\n本当に変なことなんて何もしてないんだ。
239 = "俺の意思で盗んだわけじゃないし、\\n本当に変なことなんて何もしてないんだ。"

# カズマ
# だから俺の身の潔白の証として、\nこのパンツは持ち主に必ず受け取らせてみせる！
205 = "だから俺の身の潔白の証として、\\nこのパンツは持ち主に必ず受け取らせてみせる！"

# カズマ（Ｍ）
# display as カズマ
# （持ち主捜しなんてやめた方がいいのか？）
292 = "（持ち主捜しなんてやめた方がいいのか？）"

# カズマ（Ｍ）
# display as カズマ
# （確かにみんなの言い分はわかる）
294 = "（確かにみんなの言い分はわかる）"

# カズマ（Ｍ）
# display as カズマ
# （わかる、が――）
290 = "（わかる、が――）"

# カズマ（Ｍ）
# display as カズマ
# （それじゃ俺が本当に\n　このパンツに何かしたみたいじゃねーか！）
285 = "（それじゃ俺が本当に\\n　このパンツに何かしたみたいじゃねーか！）"

# カズマ
# ふざけるな！\n誰がやってもいない罪を認めたりするもんか！
212 = "ふざけるな！\\n誰がやってもいない罪を認めたりするもんか！"

# カズマ
# 俺は身の潔白を証明するために、\n意地でもこのパンツの持ち主を見つけてやるからな！
240 = "俺は身の潔白を証明するために、\\n意地でもこのパンツの持ち主を見つけてやるからな！"

# カズマ
# しらばっくれてられるのも今だけだ！
200 = "しらばっくれてられるのも今だけだ！"

# カズマ
# お前らがそうやって俺を変態扱いするなら、\n本当にこのパンツであーんなことやこーんなことを\nしてやるぞ？　いいのかそれで？
194 = "お前らがそうやって俺を変態扱いするなら、\\n本当にこのパンツであーんなことやこーんなことを\\nしてやるぞ？　いいのかそれで？"

# アクア＆めぐみん
# display as ２人
# うわぁ……。
190 = "うわぁ……。"

# カズマ
# あ、あれ？
182 = "あ、あれ？"

# カズマ（Ｍ）
# display as カズマ
# （より視線が冷たくなったような）
289 = "（より視線が冷たくなったような）"

# カズマ（Ｍ）
# display as カズマ
# （ダメだ。これじゃ誤解が誤解じゃなくなっちまう）
291 = "（ダメだ。これじゃ誤解が誤解じゃなくなっちまう）"

# カズマ
# ごほん。
198 = "ごほん。"

# カズマ
# と、いうのは冗談でだな、\nやっぱり物は大切にするべきだと思うんだ。
208 = "と、いうのは冗談でだな、\\nやっぱり物は大切にするべきだと思うんだ。"

# カズマ
# だから、お前らが恥ずかしがったとしても、\nこのパンツは持ち主に返す。うん。そう決めた。
204 = "だから、お前らが恥ずかしがったとしても、\\nこのパンツは持ち主に返す。うん。そう決めた。"

[selections]
247 = "必ず持ち主に返してやるからな！"
222 = "やめた方がいいのか？"
# 200 = "しらばっくれてられるのも今だけだ！"
