# st01b_11.txt.scn

[info]
101 = "st01b_11"

[characters]
139 = "カズマ（Ｍ）"
137 = "アクア"
138 = "カズマ"
140 = "ルナ"

[character_subs]
# 138 = "カズマ"

[script]
# lines: 28

# カズマ（Ｍ）
# display as カズマ
# （えっと、アクアは……）
168 = "（えっと、アクアは……）"

# アクア
# おじちゃーん！\nキンキンに冷えたシュワシュワちょうだーい！
125 = "おじちゃーん！\\nキンキンに冷えたシュワシュワちょうだーい！"

# カズマ
# おい、こらっ！
124 = "おい、こらっ！"

# アクア
# いったいっ！　何よ急に！
121 = "いったいっ！　何よ急に！"

# カズマ
# お前、なんで昼からシュワシュワを煽ってんだよ！
126 = "お前、なんで昼からシュワシュワを煽ってんだよ！"

# アクア
# え、ここが酒場だからだけど？\nそんなことも知らないの？\nもしかしてバカなの？
122 = "え、ここが酒場だからだけど？\\nそんなことも知らないの？\\nもしかしてバカなの？"

# カズマ
# こいつっ……！
127 = "こいつっ……！"

# カズマ（Ｍ）
# display as カズマ
# （まあいいか。アクアがいたところで、\n　何かの役に立つとも思えないし）
171 = "（まあいいか。アクアがいたところで、\\n　何かの役に立つとも思えないし）"

# カズマ（Ｍ）
# display as カズマ
# （こいつのことは放っておいて、\n　さっさと話をしてきてしまおう）
169 = "（こいつのことは放っておいて、\\n　さっさと話をしてきてしまおう）"

# カズマ
# すみませーん、ちょっといいですか？
130 = "すみませーん、ちょっといいですか？"

# ルナ
# あら、サトウさん。どうしました？
119 = "あら、サトウさん。どうしました？"

# カズマ
# さっそくで悪いんですけど、\nさっきの話、お願いしていいですか？
129 = "さっそくで悪いんですけど、\\nさっきの話、お願いしていいですか？"

# ルナ
# ここの一画をお貸しするっていうお話ですか？\nもちろん構いませんよ。
128 = "ここの一画をお貸しするっていうお話ですか？\\nもちろん構いませんよ。"

# ルナ
# でも、どんなお店を開くのか\nもう決まったんですか？
131 = "でも、どんなお店を開くのか\\nもう決まったんですか？"

# カズマ
# ええ、メイド喫茶です。
123 = "ええ、メイド喫茶です。"

# ルナ
# めいどきっさ？
135 = "めいどきっさ？"

# カズマ
# はい。この世界でも萌えって感覚は\n共通だと思うんで、きっと成功しますよ。\nいや、成功させてみせます。
133 = "はい。この世界でも萌えって感覚は\\n共通だと思うんで、きっと成功しますよ。\\nいや、成功させてみせます。"

# ルナ
# はあ……もえ、ですか？
132 = "はあ……もえ、ですか？"

# ルナ
# 正直よくわかりませんけど、\nそれだけやる気があるなら大丈夫そうですね。
148 = "正直よくわかりませんけど、\\nそれだけやる気があるなら大丈夫そうですね。"

# カズマ
# あ、簡単な調理とかもしたいんで、\n奥も少し貸してもらえると助かるんですけど。
118 = "あ、簡単な調理とかもしたいんで、\\n奥も少し貸してもらえると助かるんですけど。"

# ルナ
# 構いませんよ。
147 = "構いませんよ。"

# ルナ
# 必要な材料などがあったら\n事前に言っておいてくださいね。\n一緒に仕入れてしまった方が安く済みますから。
146 = "必要な材料などがあったら\\n事前に言っておいてくださいね。\\n一緒に仕入れてしまった方が安く済みますから。"

# カズマ
# ほんと何から何まですみません。助かります。
134 = "ほんと何から何まですみません。助かります。"

# ルナ
# いえいえ。
120 = "いえいえ。"

# カズマ（Ｍ）
# display as カズマ
# （よし、これで店を開く場所は確保できたな）
172 = "（よし、これで店を開く場所は確保できたな）"

# カズマ（Ｍ）
# display as カズマ
# （あとは――）
167 = "（あとは――）"

# アクア
# んくんくんくっ、ぷはーっ！\nくぅぅぅ～～、五臓六腑に染み渡る～！！
136 = "んくんくんくっ、ぷはーっ！\\nくぅぅぅ～～、五臓六腑に染み渡る～！！"

# カズマ（Ｍ）
# display as カズマ
# （こいつらの調教だ！）
170 = "（こいつらの調教だ！）"

