# st01b_04.txt.scn

[info]
99 = "st01b_04"

[characters]
137 = "カズマ（Ｍ）"
138 = "キース"
136 = "カズマ"
140 = "ダスト"
142 = "ルナ"

[character_subs]
# 136 = "カズマ"

[script]
# lines: 50

# カズマ（Ｍ）
# display as カズマ
# （さて、これからどうしたもんかな）
185 = "（さて、これからどうしたもんかな）"

# カズマ（Ｍ）
# display as カズマ
# （改めて、みんなの協力を取り付けることはできた）
195 = "（改めて、みんなの協力を取り付けることはできた）"

# カズマ（Ｍ）
# display as カズマ
# （だが、具体的にどうやって金を稼ぐか、\n　その方法が思いつかない）
187 = "（だが、具体的にどうやって金を稼ぐか、\\n　その方法が思いつかない）"

# カズマ（Ｍ）
# display as カズマ
# （少し考えてくると言って外に出て来たものの、\n　さっぱり何も思い浮かばず、\n　こうして飯を食っていたりする）
193 = "（少し考えてくると言って外に出て来たものの、\\n　さっぱり何も思い浮かばず、\\n　こうして飯を食っていたりする）"

# カズマ（Ｍ）
# display as カズマ
# （あ、そういえば今回のパンツって、\n　結局誰のだったんだ？）
181 = "（あ、そういえば今回のパンツって、\\n　結局誰のだったんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （返しそびれて、\n　まだポケットの中に入ったままだけど）
199 = "（返しそびれて、\\n　まだポケットの中に入ったままだけど）"

# キース
# ようカズマ、散々なことになってるみたいだな。
134 = "ようカズマ、散々なことになってるみたいだな。"

# カズマ
# ん？　なんだよいきなり？
135 = "ん？　なんだよいきなり？"

# ダスト
# とぼけるなって。\n夜な夜な女のパンツを盗む\n呪いにかかっちまったんだろ？
126 = "とぼけるなって。\\n夜な夜な女のパンツを盗む\\n呪いにかかっちまったんだろ？"

# カズマ
# だー！？　なんで知ってるんだよ！
125 = "だー！？　なんで知ってるんだよ！"

# ダスト
# なんでって――
128 = "なんでって――"

# カズマ
# いや、言わなくていい。だいたいわかるから。
118 = "いや、言わなくていい。だいたいわかるから。"

# カズマ（Ｍ）
# display as カズマ
# （どうせあの駄女神の仕業だろう）
188 = "（どうせあの駄女神の仕業だろう）"

# カズマ（Ｍ）
# display as カズマ
# （頭だけじゃなくて口まで軽いあのお気楽女神が、\n　あることないこと触れまわっているに違いない）
200 = "（頭だけじゃなくて口まで軽いあのお気楽女神が、\\n　あることないこと触れまわっているに違いない）"

# カズマ（Ｍ）
# display as カズマ
# （これじゃ実際に被害が出る前に\n　噂が広まっちまうじゃねーか）
184 = "（これじゃ実際に被害が出る前に\\n　噂が広まっちまうじゃねーか）"

# キース
# まあ力にはなれないが、愚痴くらいなら\nいつでも聞いてやるからがんばれよ。じゃあな。
131 = "まあ力にはなれないが、愚痴くらいなら\\nいつでも聞いてやるからがんばれよ。じゃあな。"

# カズマ（Ｍ）
# display as カズマ
# （励ますように肩を叩いて去って行く\n　キースとダストをぼんやりと見送る）
191 = "（励ますように肩を叩いて去って行く\\n　キースとダストをぼんやりと見送る）"

# カズマ（Ｍ）
# display as カズマ
# （その視線の先に、たまに見かけるプリーストの\n　女の子の姿があったのだが）
186 = "（その視線の先に、たまに見かけるプリーストの\\n　女の子の姿があったのだが）"

# カズマ（Ｍ）
# display as カズマ
# （彼女は俺に気づいた瞬間、\n　慌てて回れ右をして引き返して行ってしまった）
194 = "（彼女は俺に気づいた瞬間、\\n　慌てて回れ右をして引き返して行ってしまった）"

# カズマ（Ｍ）
# display as カズマ
# （この短時間に、どこまで広まってるんだよ！）
183 = "（この短時間に、どこまで広まってるんだよ！）"

# ルナ
# サトウカズマさん？　ちょっといいですか？
139 = "サトウカズマさん？　ちょっといいですか？"

# カズマ
# は、はいすみません！\n急いでなんとかしますから、\n訴えるとかそういうのは勘弁してください！
130 = "は、はいすみません！\\n急いでなんとかしますから、\\n訴えるとかそういうのは勘弁してください！"

# ルナ
# あー、いえ、そうではなくて、少しお話が\nできればと。
117 = "あー、いえ、そうではなくて、少しお話が\\nできればと。"

# カズマ
# お話？
120 = "お話？"

# ルナ
# 先ほど噂を耳にしたのですが、\nなんだか大変なことになってるみたいですね。
146 = "先ほど噂を耳にしたのですが、\\nなんだか大変なことになってるみたいですね。"

# カズマ
# 俺が悪いわけじゃないんです！\nこの指輪が……。
145 = "俺が悪いわけじゃないんです！\\nこの指輪が……。"

# ルナ
# 別に疑っているわけじゃありませんよ？\nこういう所に勤めていると、何かとおかしな\nマジックアイテムの話を聞くこともありますから。
147 = "別に疑っているわけじゃありませんよ？\\nこういう所に勤めていると、何かとおかしな\\nマジックアイテムの話を聞くこともありますから。"

# カズマ
# じゃあ、これの外し方とか知ってたりしませんか？
122 = "じゃあ、これの外し方とか知ってたりしませんか？"

# ルナ
# そうですねぇ。この手のマジックアイテムだと、\n３０００万エリスほどで\n解除を請け負ってくれる方がいるにはいますけど。
123 = "そうですねぇ。この手のマジックアイテムだと、\\n３０００万エリスほどで\\n解除を請け負ってくれる方がいるにはいますけど。"

# カズマ（Ｍ）
# display as カズマ
# （結局大金が必要なわけか！）
198 = "（結局大金が必要なわけか！）"

# ルナ
# もしくは、作られた方の願いを達成すると、\n自然と外れることもあるそうです。
132 = "もしくは、作られた方の願いを達成すると、\\n自然と外れることもあるそうです。"

# カズマ
# 作ったやつの願い？
144 = "作ったやつの願い？"

# カズマ（Ｍ）
# display as カズマ
# （毎月パンツを盗みたがるようなやつが、\n　いったいどんな願いを持ってるっていうんだ？）
196 = "（毎月パンツを盗みたがるようなやつが、\\n　いったいどんな願いを持ってるっていうんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （満足するまでパンツを盗み続けろとでも？\n　ふざけるな！）
197 = "（満足するまでパンツを盗み続けろとでも？\\n　ふざけるな！）"

# ルナ
# 私個人としては後者はお勧めしないといいますか、\nできれば遠慮していただきたいですね。\nきっと女性にとっては好ましくない願いでしょうし。
178 = "私個人としては後者はお勧めしないといいますか、\\nできれば遠慮していただきたいですね。\\nきっと女性にとっては好ましくない願いでしょうし。"

# ルナ
# その代わりと言ってはなんですが、\n前者に関しては少しお役に立てるかもしれません。
124 = "その代わりと言ってはなんですが、\\n前者に関しては少しお役に立てるかもしれません。"

# カズマ
# どういう意味です？
127 = "どういう意味です？"

# ルナ
# もしよろしければなんですけど、\nここにお店を出してみてはどうですか？
133 = "もしよろしければなんですけど、\\nここにお店を出してみてはどうですか？"

# カズマ
# 店を酒場内にですか？
153 = "店を酒場内にですか？"

# ルナ
# さすがに酒場全体は無理ですが、\nこの一画でよければお貸しできますよ？
121 = "さすがに酒場全体は無理ですが、\\nこの一画でよければお貸しできますよ？"

# ルナ
# 高難易度のクエストをクリアしてもらえるような\n大金を一気にとはいかないと思いますが。
179 = "高難易度のクエストをクリアしてもらえるような\\n大金を一気にとはいかないと思いますが。"

# カズマ（Ｍ）
# display as カズマ
# （ふむ、ここで店を経営か……）
189 = "（ふむ、ここで店を経営か……）"

# ルナ
# 必要な時はいつでも声をかけてください。
154 = "必要な時はいつでも声をかけてください。"

# カズマ（Ｍ）
# display as カズマ
# （女神だ。\n　どこぞのなんちゃって女神と違って、\n　こういう人こそ女神と呼ぶに相応しい）
192 = "（女神だ。\\n　どこぞのなんちゃって女神と違って、\\n　こういう人こそ女神と呼ぶに相応しい）"

# カズマ
# お姉さん！\n俺、がんばりますから！
119 = "お姉さん！\\n俺、がんばりますから！"

# ルナ
# ！？
180 = "！？"

# カズマ
# なんで後ずさりするんです？\n握手してもらおうと思って\n手を伸ばしただけなんですけど。
129 = "なんで後ずさりするんです？\\n握手してもらおうと思って\\n手を伸ばしただけなんですけど。"

# ルナ
# あ、えっと、下着を盗られたらどうしよう、\nと思いまして。
116 = "あ、えっと、下着を盗られたらどうしよう、\\nと思いまして。"

# カズマ（Ｍ）
# display as カズマ
# （くっそーーーーっ！！）
182 = "（くっそーーーーっ！！）"

# カズマ（Ｍ）
# display as カズマ
# （一刻も早くこの指輪をなんとかしてやるからな！）
190 = "（一刻も早くこの指輪をなんとかしてやるからな！）"

