# st01c_04.txt.scn

[info]
79 = "st01c_04"

[characters]
102 = "カズマ"
103 = "カズマ（Ｍ）"
101 = "アクア"

[character_subs]
# 102 = "カズマ"

[script]
# lines: 18

# カズマ
# うーん……。
98 = "うーん……。"

# カズマ（Ｍ）
# display as カズマ
# （思っていた通り、なかなかの売り上げだ）
124 = "（思っていた通り、なかなかの売り上げだ）"

# カズマ（Ｍ）
# display as カズマ
# （メイド喫茶なんてものが受けるかわかなかった\n　この世界で、初日としては大成功と言っていい）
118 = "（メイド喫茶なんてものが受けるかわかなかった\\n　この世界で、初日としては大成功と言っていい）"

# カズマ（Ｍ）
# display as カズマ
# （だがそれは、普通に店を経営するだけの\n　立場だったらの話だ）
116 = "（だがそれは、普通に店を経営するだけの\\n　立場だったらの話だ）"

# カズマ（Ｍ）
# display as カズマ
# （俺たちの……いや、俺の目的は、\n　指輪の呪いを解くための費用を稼ぐことなんだ）
122 = "（俺たちの……いや、俺の目的は、\\n　指輪の呪いを解くための費用を稼ぐことなんだ）"

# カズマ（Ｍ）
# display as カズマ
# （この程度の売り上げじゃ、\n　必要な額が溜るまでに数ヶ月はかかってしまう）
113 = "（この程度の売り上げじゃ、\\n　必要な額が溜るまでに数ヶ月はかかってしまう）"

# カズマ（Ｍ）
# display as カズマ
# （仮に、借金して呪いを解いてもらうとしよう）
120 = "（仮に、借金して呪いを解いてもらうとしよう）"

# カズマ（Ｍ）
# display as カズマ
# （その返済のために店を続けるとして、\n　数ヶ月も続けて行けるだろうか……）
115 = "（その返済のために店を続けるとして、\\n　数ヶ月も続けて行けるだろうか……）"

# カズマ（Ｍ）
# display as カズマ
# （今はギルドの好意で場所を貸してもらえてるが、\n　そんな長々と占有してたら、賃貸料を取られたり\n　するかもしれないし……）
119 = "（今はギルドの好意で場所を貸してもらえてるが、\\n　そんな長々と占有してたら、賃貸料を取られたり\\n　するかもしれないし……）"

# カズマ（Ｍ）
# display as カズマ
# （何より問題なのは、みんなのモチベーションだ）
121 = "（何より問題なのは、みんなのモチベーションだ）"

# アクア
# ねえカズマ、今日の売り上げってどうだったの？
100 = "ねえカズマ、今日の売り上げってどうだったの？"

# カズマ
# いや、まあ……それは……。
96 = "いや、まあ……それは……。"

# アクア
# うわー、すごいじゃない！　こんなに儲かったの？
97 = "うわー、すごいじゃない！　こんなに儲かったの？"

# アクア
# だったら今夜のご飯はおごりでいいわよね？\nカニ食べましょうよ！　あと高級シュワシュワも！
99 = "だったら今夜のご飯はおごりでいいわよね？\\nカニ食べましょうよ！　あと高級シュワシュワも！"

# カズマ（Ｍ）
# display as カズマ
# （普段だったら、\n　ふざけるなと一蹴してるところだが、\n　水を差して機嫌を損なったりしたらと思うと）
125 = "（普段だったら、\\n　ふざけるなと一蹴してるところだが、\\n　水を差して機嫌を損なったりしたらと思うと）"

# カズマ（Ｍ）
# display as カズマ
# （店を続けて行けるかどうかは、\n　メイド役であるアクアたちにかかってるわけだし）
123 = "（店を続けて行けるかどうかは、\\n　メイド役であるアクアたちにかかってるわけだし）"

# カズマ（Ｍ）
# display as カズマ
# （こんなふうに気を遣って、\n　みんなのモチベーションを保ちながら\n　数ヶ月なんて、たまったもんじゃないぞ……）
114 = "（こんなふうに気を遣って、\\n　みんなのモチベーションを保ちながら\\n　数ヶ月なんて、たまったもんじゃないぞ……）"

# カズマ（Ｍ）
# display as カズマ
# （どうにかして\n　もっと短い期間で目標金額を達成しないと……）
117 = "（どうにかして\\n　もっと短い期間で目標金額を達成しないと……）"

