# st01a_04.txt.scn

[info]
180 = "st01a_04"

[characters]
291 = "カズマ"
287 = "アクア"
283 = "めぐみん"
292 = "カズマ（Ｍ）"
295 = "ダクネス"
288 = "ウィズ"
285 = "ゆんゆん"
293 = "クリス"

[character_subs]
# 291 = "カズマ"

[script]
# lines: 105

# カズマ
# じゃあ、まずはアクア。\nお前から話を聞かせてもらうぞ。
247 = "じゃあ、まずはアクア。\\nお前から話を聞かせてもらうぞ。"

# カズマ
# お前は何色が好きだ。
242 = "お前は何色が好きだ。"

# アクア
# 何よその幼稚な質問。
301 = "何よその幼稚な質問。"

# アクア
# もしかして、\n女の子は～、好きな色のパンツを穿いてる～\nとか思っちゃってるわけ？
284 = "もしかして、\\n女の子は～、好きな色のパンツを穿いてる～\\nとか思っちゃってるわけ？"

# カズマ
# い、いいから答えろって！
227 = "い、いいから答えろって！"

# アクア
# そんなの見れば一目瞭然でしょ。\n私は水の女神なのよ。
255 = "そんなの見れば一目瞭然でしょ。\\n私は水の女神なのよ。"

# カズマ
# ああ、淀んで濁った水の色か。
221 = "ああ、淀んで濁った水の色か。"

# アクア
# ちっがうわよ、水色よ！\nほらこの澄んだ目と髪の色！\nどこからどうみても水の女神って感じじゃない！
260 = "ちっがうわよ、水色よ！\\nほらこの澄んだ目と髪の色！\\nどこからどうみても水の女神って感じじゃない！"

# アクア
# だいたい、淀んで濁ってさらに腐ってるのは、\nカズマの目なんじゃないですかー？
258 = "だいたい、淀んで濁ってさらに腐ってるのは、\\nカズマの目なんじゃないですかー？"

# カズマ
# なあアクア。\n澄んだ水って透明らしいぞ。
271 = "なあアクア。\\n澄んだ水って透明らしいぞ。"

# アクア
# え？
238 = "え？"

# カズマ
# そういえば、何かの菌が大量発生した湖って\nそんな色になるよな。
251 = "そういえば、何かの菌が大量発生した湖って\\nそんな色になるよな。"

# カズマ
# ひどい臭いもするし。
277 = "ひどい臭いもするし。"

# アクア
# え、私ってもしかして臭い！？\nお風呂は毎日ちゃんと入ってるんだけど。
236 = "え、私ってもしかして臭い！？\\nお風呂は毎日ちゃんと入ってるんだけど。"

# カズマ
# 髪を嗅ぐな髪を！
351 = "髪を嗅ぐな髪を！"

# カズマ
# てか、お前が濁ってるとか腐ってるとか、\nなんかツンとした匂いがするとか、今はそんなこと\nどうでもいいんだよ！
263 = "てか、お前が濁ってるとか腐ってるとか、\\nなんかツンとした匂いがするとか、今はそんなこと\\nどうでもいいんだよ！"

# アクア
# ツ、ツンとした匂い！？
296 = "ツ、ツンとした匂い！？"

# カズマ
# ああっ、もうっ、話を戻すぞ。\nお前が好きな色は水色でいいんだな？
222 = "ああっ、もうっ、話を戻すぞ。\\nお前が好きな色は水色でいいんだな？"

# アクア
# %fsyogen;ねえねえ、めぐみん。\n私って変な匂いがしてるの？
24 = "%fsyogen;ねえねえ、めぐみん。\\n私って変な匂いがしてるの？"

# めぐみん
# いいえ、無臭ですね。
228 = "いいえ、無臭ですね。"

# カズマ
# 人の話を聞けよっ！
300 = "人の話を聞けよっ！"

# カズマ（Ｍ）
# display as カズマ
# （しかしアクアのこの態度を\n　どう判断したものだろう？）
354 = "（しかしアクアのこの態度を\\n　どう判断したものだろう？）"

# カズマ（Ｍ）
# display as カズマ
# （パンツのことから話をそらすために、\n　大げさに取り乱してみせたという可能性も\n　あるが――）
363 = "（パンツのことから話をそらすために、\\n　大げさに取り乱してみせたという可能性も\\n　あるが――）"

# カズマ（Ｍ）
# display as カズマ
# （アクアにそんな悪知恵が働くとも思えないし）
361 = "（アクアにそんな悪知恵が働くとも思えないし）"

# カズマ（Ｍ）
# display as カズマ
# （こいつは良くも悪くも正直すぎるところが\n　あるからな）
353 = "（こいつは良くも悪くも正直すぎるところが\\n　あるからな）"

# カズマ（Ｍ）
# display as カズマ
# （ひとまず証言としてゲットして、\n　次に行くか）
356 = "（ひとまず証言としてゲットして、\\n　次に行くか）"

# カズマ
# じゃあ次はめぐみんだ。
249 = "じゃあ次はめぐみんだ。"

# めぐみん
# 先に行っておきますが、\n紅魔族にパンツのことを聞くと呪われますよ。
302 = "先に行っておきますが、\\n紅魔族にパンツのことを聞くと呪われますよ。"

# カズマ
# おう。呪えるもんなら呪ってみろよ。\nこっちはすでに指輪に呪われてるんだから、\nもう一個増えたところで怖くなんかねーぞ。
240 = "おう。呪えるもんなら呪ってみろよ。\\nこっちはすでに指輪に呪われてるんだから、\\nもう一個増えたところで怖くなんかねーぞ。"

# めぐみん
# くっ、完全に開き直ってますね。
243 = "くっ、完全に開き直ってますね。"

# カズマ
# さあ、めぐみん。\nこのパンツがお前の物なのかどうか\n答えてもらおうか。
244 = "さあ、めぐみん。\\nこのパンツがお前の物なのかどうか\\n答えてもらおうか。"

# めぐみん
# ドストレートですね！\nアクアの時みたいに好きな色とか\n聞いてくださいよ！
297 = "ドストレートですね！\\nアクアの時みたいに好きな色とか\\n聞いてくださいよ！"

# カズマ
# いやー、推理するのって意外に面倒でさ。
232 = "いやー、推理するのって意外に面倒でさ。"

# めぐみん
# それはわかりますけど、\n答える方の身にもなってください。
254 = "それはわかりますけど、\\n答える方の身にもなってください。"

# ダクネス
# そうだぞ。\nめぐみんは年頃の女の子なんだから、\n少しは乙女心というのを察してやるべきだろう。
252 = "そうだぞ。\\nめぐみんは年頃の女の子なんだから、\\n少しは乙女心というのを察してやるべきだろう。"

# ダクネス
# だからだな、\nそういうことはこの私に聞くべきだと思うんだ。
259 = "だからだな、\\nそういうことはこの私に聞くべきだと思うんだ。"

# カズマ
# じゃあ、ダクネスのか？
248 = "じゃあ、ダクネスのか？"

# ダクネス
# カ、カ、カズマはどう思う？
290 = "カ、カ、カズマはどう思う？"

# カズマ
# どうって。\n色は黒だし？\nちょっと透けててセクシーだし？
266 = "どうって。\\n色は黒だし？\\nちょっと透けててセクシーだし？"

# カズマ
# 大人っぽいからダクネスに似合うとは思うけど。
306 = "大人っぽいからダクネスに似合うとは思うけど。"

# ダクネス
# %fsyogen;に、似合うと思ったということは、\n私がその下着を着けている姿を\n想像したということだよな！
23 = "%fsyogen;に、似合うと思ったということは、\\n私がその下着を着けている姿を\\n想像したということだよな！"

# カズマ
# …………。
218 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （相変わらずだなダクネスは……。\n　しかし、この証言は真実なのか、\n　ダクネスの誘い受けなのか迷うな……）
366 = "（相変わらずだなダクネスは……。\\n　しかし、この証言は真実なのか、\\n　ダクネスの誘い受けなのか迷うな……）"

# カズマ（Ｍ）
# display as カズマ
# （念のため、\n　これも証言としてゲットしておくか……）
364 = "（念のため、\\n　これも証言としてゲットしておくか……）"

# ダクネス
# ふふ、そうか、想像したのか。\nまったくカズマは自分の欲望に忠実だな。
279 = "ふふ、そうか、想像したのか。\\nまったくカズマは自分の欲望に忠実だな。"

# カズマ
# お前に言われたくねーよ！
241 = "お前に言われたくねーよ！"

# めぐみん
# あ、あの、カズマ？\nさっきから下着を握り締めていますが、\nそれはやめた方がよいかと。
220 = "あ、あの、カズマ？\\nさっきから下着を握り締めていますが、\\nそれはやめた方がよいかと。"

# カズマ
# あ、ああ、そうだな。\n持ち主が嫌な思いをするもんな。
219 = "あ、ああ、そうだな。\\n持ち主が嫌な思いをするもんな。"

# めぐみん
# %fsyogen;それによい生地なのですから、\n傷んだりしたらもったいないでしょう。
22 = "%fsyogen;それによい生地なのですから、\\n傷んだりしたらもったいないでしょう。"

# カズマ
# 確かにつるつるすべすべしてて、\nいい値段がしそうだ。
349 = "確かにつるつるすべすべしてて、\\nいい値段がしそうだ。"

# ウィズ
# あの～、広げて見るのはどうかと。
225 = "あの～、広げて見るのはどうかと。"

# アクア
# あんた、わざとやってるんじゃないでしょうね。
226 = "あんた、わざとやってるんじゃないでしょうね。"

# カズマ（Ｍ）
# display as カズマ
# （ん、ちょっと待て。\n　なぜ、一見しただけで生地の内容がわかるんだ？\n　女子はみんなそうなのか？）
359 = "（ん、ちょっと待て。\\n　なぜ、一見しただけで生地の内容がわかるんだ？\\n　女子はみんなそうなのか？）"

# カズマ（Ｍ）
# display as カズマ
# （まぁ、確かにすべすべして\n　肌触りはいいし良い生地っぽいけど、\n　パンツとしてはどうなんだろう……）
357 = "（まぁ、確かにすべすべして\\n　肌触りはいいし良い生地っぽいけど、\\n　パンツとしてはどうなんだろう……）"

# カズマ（Ｍ）
# display as カズマ
# （っと、あまり触り過ぎると\n　変態認定されそうだな。\n　これも証言としてゲットしておこう）
355 = "（っと、あまり触り過ぎると\\n　変態認定されそうだな。\\n　これも証言としてゲットしておこう）"

# ゆんゆん
# ？　めぐみん熱でもあるの？\n顔が赤いよ？
368 = "？　めぐみん熱でもあるの？\\n顔が赤いよ？"

# めぐみん
# な！？　何を言って――
273 = "な！？　何を言って――"

# カズマ（Ｍ）
# display as カズマ
# （ん？）
360 = "（ん？）"

# めぐみん
# いえ、そうですね。\n言われてみればこの部屋、少し暑いかもしれません。
229 = "いえ、そうですね。\\n言われてみればこの部屋、少し暑いかもしれません。"

# めぐみん
# ほら、ゆんゆんも汗をかいてるじゃないですか。\n仕方ありませんね、拭いてあげますよ。
281 = "ほら、ゆんゆんも汗をかいてるじゃないですか。\\n仕方ありませんね、拭いてあげますよ。"

# ゆんゆん
# え？　私は別に――
239 = "え？　私は別に――"

# ゆんゆん
# むぐ！？\n顔、そんなふうに拭かれたら、苦し……んん！
282 = "むぐ！？\\n顔、そんなふうに拭かれたら、苦し……んん！"

# めぐみん
# いやー、今日は暑いですね。
231 = "いやー、今日は暑いですね。"

# カズマ
# …………。
# 218 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （あやしい。\n　だが、あまりにも露骨にあやしすぎて、\n　逆に判断に迷う……）
352 = "（あやしい。\\n　だが、あまりにも露骨にあやしすぎて、\\n　逆に判断に迷う……）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスは……。\n　この反応ではなんとも言えないな）
362 = "（ダクネスは……。\\n　この反応ではなんとも言えないな）"

# カズマ
# うん、もう少し情報が欲しいし、\nやっぱ念のために他のみんなにも話を聞いとくか。
235 = "うん、もう少し情報が欲しいし、\\nやっぱ念のために他のみんなにも話を聞いとくか。"

# クリス
# ちょっ、さっきと言ってることが違うじゃん。
262 = "ちょっ、さっきと言ってることが違うじゃん。"

# ゆんゆん
# 聞かれても答えられるようなことありませんよ。
350 = "聞かれても答えられるようなことありませんよ。"

# ウィズ
# …………。
# 218 = "…………。"

# カズマ
# ウィズは何か心当たりでもあるのか？
289 = "ウィズは何か心当たりでもあるのか？"

# ウィズ
# あの、先ほど素材の話が出たじゃないですか。
224 = "あの、先ほど素材の話が出たじゃないですか。"

# ウィズ
# %fsyogen;同じ素材を使ったハンカチは、\nおそらく数千エリスすると思うんです。
25 = "%fsyogen;同じ素材を使ったハンカチは、\\nおそらく数千エリスすると思うんです。"

# カズマ
# そんな！？
256 = "そんな！？"

# ウィズ
# さらに特筆すべきは刺繍です。\nすごい凝っていますよね？
246 = "さらに特筆すべきは刺繍です。\\nすごい凝っていますよね？"

# カズマ
# 確かに、こんなのやれって言われたら\n気が狂うかもしれない。
348 = "確かに、こんなのやれって言われたら\\n気が狂うかもしれない。"

# ウィズ
# ですから、本当によいお値段がすると思うんです。
264 = "ですから、本当によいお値段がすると思うんです。"

# カズマ
# ねえそれって、経験からの推測？\nウィズもこういうの穿いてるの？
274 = "ねえそれって、経験からの推測？\\nウィズもこういうの穿いてるの？"

# ウィズ
# ふええ！？　い、言えませんよ！
278 = "ふええ！？　い、言えませんよ！"

# カズマ（Ｍ）
# display as カズマ
# （確かにウィズの言うとおり、\n　かなり細かな刺繍がされてる）
367 = "（確かにウィズの言うとおり、\\n　かなり細かな刺繍がされてる）"

# カズマ（Ｍ）
# display as カズマ
# （目立たない所まで作り込まれてるし、\n　俺の世界でいうブランド物ってやつなんだろう）
365 = "（目立たない所まで作り込まれてるし、\\n　俺の世界でいうブランド物ってやつなんだろう）"

# カズマ（Ｍ）
# display as カズマ
# （よし、これも証言としてゲットだ！）
358 = "（よし、これも証言としてゲットだ！）"

# めぐみん
# ちょ、ちょっとカズマ！\n何をマジマジと見ているのですか！
261 = "ちょ、ちょっとカズマ！\\n何をマジマジと見ているのですか！"

# めぐみん
# はっ、まさか匂いを嗅いでっ！
276 = "はっ、まさか匂いを嗅いでっ！"

# カズマ
# 嗅いでませんから！
305 = "嗅いでませんから！"

# カズマ
# いや待てよ、匂いか。\nそれは盲点だったかも。
233 = "いや待てよ、匂いか。\\nそれは盲点だったかも。"

# めぐみん
# ななな、まさか！
272 = "ななな、まさか！"

# クリス
# いやー、さすがにそれはどうかと思うよ。
230 = "いやー、さすがにそれはどうかと思うよ。"

# ダクネス
# うむ、さすがの私もドン引きだ。
234 = "うむ、さすがの私もドン引きだ。"

# カズマ
# じょ、冗談だよ、真に受けるな！
250 = "じょ、冗談だよ、真に受けるな！"

# めぐみん
# はぁ……カズマの言うことは\n冗談に聞こえませんよ。
275 = "はぁ……カズマの言うことは\\n冗談に聞こえませんよ。"

# カズマ
# なあ、めぐみん。\nなんでお前はそんなに必死になってるんだ？
270 = "なあ、めぐみん。\\nなんでお前はそんなに必死になってるんだ？"

# めぐみん
# え！？　そ、それは……。
237 = "え！？　そ、それは……。"

# ゆんゆん
# あっ。
223 = "あっ。"

# カズマ
# どうしたゆんゆん？
265 = "どうしたゆんゆん？"

# ゆんゆん
# な、なんでもないです。
269 = "な、なんでもないです。"

# ゆんゆん
# ただちょっと、その下着に\n見覚えがあるような気がしたっていうか。
257 = "ただちょっと、その下着に\\n見覚えがあるような気がしたっていうか。"

# ゆんゆん
# そっか。それって確か、\nこの前出かけた時に買ってた……。
253 = "そっか。それって確か、\\nこの前出かけた時に買ってた……。"

# めぐみん
# ゆんゆん！\n独り言なら誰にも聞こえないように言ってください！
286 = "ゆんゆん！\\n独り言なら誰にも聞こえないように言ってください！"

# カズマ
# …………。
# 218 = "…………。"

# めぐみん
# な、なんですカズマ？\nそんな目で私を見てると爆裂魔法を撃ちますよ？
267 = "な、なんですカズマ？\\nそんな目で私を見てると爆裂魔法を撃ちますよ？"

# カズマ
# ふふ、なるほど。そういうことか。
280 = "ふふ、なるほど。そういうことか。"

# めぐみん
# な、なんです？
268 = "な、なんです？"

# カズマ
# パズルのピースは全て揃ったということさ。
298 = "パズルのピースは全て揃ったということさ。"

# カズマ
# さあ、事実の証明を行おうじゃないか！\nパンツ裁判の開廷だ！
245 = "さあ、事実の証明を行おうじゃないか！\\nパンツ裁判の開廷だ！"

[selections]
294 = "コーヒーブレイク"
