# st01a_05.txt.scn

[info]
143 = "st01a_05"

[characters]
208 = "カズマ"
200 = "めぐみん"
202 = "ゆんゆん"
207 = "ウィズ"
211 = "ダクネス"
210 = "カズマ（Ｍ）"
206 = "アクア"

[character_subs]
# 208 = "カズマ"

[script]
# lines: 55

# カズマ
# ほら、めぐみん。\nちょっとお高いお前のパンツを返すぞ。
199 = "ほら、めぐみん。\\nちょっとお高いお前のパンツを返すぞ。"

# めぐみん
# 黒より黒く、闇より昏き漆黒に……。
260 = "黒より黒く、闇より昏き漆黒に……。"

# カズマ
# ん？
205 = "ん？"

# めぐみん
# 我が真紅の混淆を望みたもうっ。
224 = "我が真紅の混淆を望みたもうっ。"

# カズマ
# ちょっ！？　おまっ！
189 = "ちょっ！？　おまっ！"

# ゆんゆん
# 嘘でしょめぐみん！？\nこんな所で爆裂魔法なんて撃っちゃダメだってば！
218 = "嘘でしょめぐみん！？\\nこんな所で爆裂魔法なんて撃っちゃダメだってば！"

# めぐみん
# んぐ！？　……んあ！\n離してくださいゆんゆん！
204 = "んぐ！？　……んあ！\\n離してくださいゆんゆん！"

# めぐみん
# こんな辱めを受けたのですから、\n倍にして返さなくては私の気が済みません！
183 = "こんな辱めを受けたのですから、\\n倍にして返さなくては私の気が済みません！"

# カズマ
# 倍で済むか！\n爆裂魔法なんて食らったら死ぬわバカ！
215 = "倍で済むか！\\n爆裂魔法なんて食らったら死ぬわバカ！"

# めぐみん
# ちょうどいいです。死んで詫びてください。
188 = "ちょうどいいです。死んで詫びてください。"

# カズマ
# 無茶苦茶言うなお前！
225 = "無茶苦茶言うなお前！"

# めぐみん
# カズマのしたことが、\nそれ程のことだったというだけですよ！
209 = "カズマのしたことが、\\nそれ程のことだったというだけですよ！"

# めぐみん
# 私の気持ち、わかりますか？
257 = "私の気持ち、わかりますか？"

# めぐみん
# 寝ている間に穿いていたパンツを盗まれ、\n大勢の前で持ち主探しをされ、\n手触りがどうのといじりまわされ……。
219 = "寝ている間に穿いていたパンツを盗まれ、\\n大勢の前で持ち主探しをされ、\\n手触りがどうのといじりまわされ……。"

# めぐみん
# 買ったばかりだったのに……\n奮発してちょっと高めのやつだったのに……\nお気に入りだったのに……。
259 = "買ったばかりだったのに……\\n奮発してちょっと高めのやつだったのに……\\nお気に入りだったのに……。"

# めぐみん
# こうなったら、\nカズマを殺して私も死んでやります！
182 = "こうなったら、\\nカズマを殺して私も死んでやります！"

# ゆんゆん
# も、もう、めぐみん落ち着いて！
201 = "も、もう、めぐみん落ち着いて！"

# カズマ
# そ、そうだぞ！\nだいたいそんなに恥ずかしいなら、\nどうして嘘を突き通さなかったんだよ！
185 = "そ、そうだぞ！\\nだいたいそんなに恥ずかしいなら、\\nどうして嘘を突き通さなかったんだよ！"

# めぐみん
# うぅ、穿けないのですよ。
175 = "うぅ、穿けないのですよ。"

# ゆんゆん
# え、はけ……何？
176 = "え、はけ……何？"

# めぐみん
# パ、パンツが穿けないんですよ！
212 = "パ、パンツが穿けないんですよ！"

# カズマ
# はぁ？
197 = "はぁ？"

# めぐみん
# よくわかりませんが、パンツを穿こうとすると\n頭がポーッとして、気がつくと足から抜いているん\nです。
203 = "よくわかりませんが、パンツを穿こうとすると\\n頭がポーッとして、気がつくと足から抜いているん\\nです。"

# めぐみん
# 何度やってもダメで、だからだから……。
214 = "何度やってもダメで、だからだから……。"

# カズマ
# えーと、ウィズ？
177 = "えーと、ウィズ？"

# ウィズ
# そ、そうですね。\n呪いの影響の可能性は大いにあるかと。
186 = "そ、そうですね。\\n呪いの影響の可能性は大いにあるかと。"

# ダクネス
# つまりカズマに下着を盗まれたら\n２度と穿けなくなるということなのか！
190 = "つまりカズマに下着を盗まれたら\\n２度と穿けなくなるということなのか！"

# めぐみん
# 少なからず、私が持っていた物、\nそして新たに買った物も穿けませんでした。
220 = "少なからず、私が持っていた物、\\nそして新たに買った物も穿けませんでした。"

# カズマ（Ｍ）
# display as カズマ
# （な、なんてこった！）
264 = "（な、なんてこった！）"

# めぐみん
# あの、ちょっと失礼します。
171 = "あの、ちょっと失礼します。"

# ダクネス
# どうかしたのか？
191 = "どうかしたのか？"

# めぐみん
# 廊下で試してこようかと。
223 = "廊下で試してこようかと。"

# カズマ
# ああ、今返したパンツだったらもしかして！
170 = "ああ、今返したパンツだったらもしかして！"

# めぐみん
# い、言わないでくださいよ！
172 = "い、言わないでくださいよ！"

# アクア
# なんか大変そうね。
194 = "なんか大変そうね。"

# カズマ
# お前はどうしてそんな他人事なんだよ。
181 = "お前はどうしてそんな他人事なんだよ。"

# めぐみん
# お、おお！！
178 = "お、おお！！"

# カズマ（Ｍ）
# display as カズマ
# （おっ、もしかして！）
261 = "（おっ、もしかして！）"

# めぐみん
# 穿けました！　穿けましたよ、カズマ！！
258 = "穿けました！　穿けましたよ、カズマ！！"

# カズマ
# おお、良かったな！
179 = "おお、良かったな！"

# めぐみん
# うぅ、これで私はまだ生きていけます。
174 = "うぅ、これで私はまだ生きていけます。"

# カズマ（Ｍ）
# display as カズマ
# （泣くほど辛かったのかよ……）
266 = "（泣くほど辛かったのかよ……）"

# ダクネス
# しかし、まいったな。\nこのままだと一ヶ月後に、またこんな騒ぎが\n起こりかねないということだぞ。
184 = "しかし、まいったな。\\nこのままだと一ヶ月後に、またこんな騒ぎが\\n起こりかねないということだぞ。"

# めぐみん
# はっ、そうでした！
198 = "はっ、そうでした！"

# ゆんゆん
# １度盗まれたらもう大丈夫って保証は……。
267 = "１度盗まれたらもう大丈夫って保証は……。"

# めぐみん
# どうなんですか、カズマ！
192 = "どうなんですか、カズマ！"

# カズマ
# いや、それは蓋を開けてみるまでわからん。
173 = "いや、それは蓋を開けてみるまでわからん。"

# めぐみん
# なんて無責任な。
195 = "なんて無責任な。"

# アクア
# ねえ、なんかもう面倒くさいし、\nやっぱりさっさと指を切り落としちゃいましょうよ。
196 = "ねえ、なんかもう面倒くさいし、\\nやっぱりさっさと指を切り落としちゃいましょうよ。"

# カズマ
# お前、他人事だと思って！
180 = "お前、他人事だと思って！"

# アクア
# だって他人事だもの。
187 = "だって他人事だもの。"

# カズマ（Ｍ）
# display as カズマ
# （くっ……）
262 = "（くっ……）"

# カズマ（Ｍ）
# display as カズマ
# （このままその話を蒸し返されては困る）
263 = "（このままその話を蒸し返されては困る）"

# カズマ（Ｍ）
# display as カズマ
# （少し強引にでも流れを戻さないと……）
265 = "（少し強引にでも流れを戻さないと……）"

# カズマ
# なあみんな、聞いてくれ。
193 = "なあみんな、聞いてくれ。"

