# st01c_03.txt.scn

[info]
273 = "st01c_03"

[characters]
434 = "カズマ（Ｍ）"
433 = "カズマ"
427 = "アクア"
432 = "ウィズ"
452 = "商人風の男"
459 = "戦士風の男冒険者"
466 = "盗賊風の男冒険者"
533 = "聖職者風の男冒険者"
421 = "ゆんゆん"
417 = "めぐみん"
431 = "アーチャー風の男冒険者"
536 = "遊び人風の男冒険者"
436 = "クリス"
438 = "ダクネス"

[character_subs]
# 433 = "カズマ"
458 = "戦士冒険者"
465 = "盗賊冒険者"
532 = "聖職冒険者"
453 = "射手冒険者"
535 = "遊び人風の男"

[script]
# lines: 140

# カズマ（Ｍ）
# display as カズマ
# （よし、さらに追い打ちをかけるぞ！）
550 = "（よし、さらに追い打ちをかけるぞ！）"

# カズマ
# アクア、ウィズ！
428 = "アクア、ウィズ！"

# アクア
# とうとう来たわね。
385 = "とうとう来たわね。"

# ウィズ
# アクア様、本当にやるんですか？
430 = "アクア様、本当にやるんですか？"

# アクア
# なーに、まだ恥ずかしいなんて思ってるわけ？\nこれだから陰気臭いアンデッドはっ！
394 = "なーに、まだ恥ずかしいなんて思ってるわけ？\\nこれだから陰気臭いアンデッドはっ！"

# アクア
# いいわ、私を見てなさい。\nメイドがどういうものかっていうのを\nこの背中で教えてあげる！
342 = "いいわ、私を見てなさい。\\nメイドがどういうものかっていうのを\\nこの背中で教えてあげる！"

# ウィズ
# は、はい、わかりました！
396 = "は、はい、わかりました！"

# アクア
# ご主人様、サービスで料理に絵や文字を書かせて\nいただいているのですが、どうされますか？
367 = "ご主人様、サービスで料理に絵や文字を書かせて\\nいただいているのですが、どうされますか？"

# 商人風の男
# え？　まあ、サービスならお願いしようかな。
356 = "え？　まあ、サービスならお願いしようかな。"

# アクア
# ふふふ、では、どのような物を書きましょう？
409 = "ふふふ、では、どのような物を書きましょう？"

# 商人風の男
# えーと、よくわからないんで、お任せで。
352 = "えーと、よくわからないんで、お任せで。"

# アクア
# はい。\nそれでは、失礼します。
405 = "はい。\\nそれでは、失礼します。"

# アクア
# ～～～～♪
556 = "～～～～♪"

# アクア
# はい、完成です♪
404 = "はい、完成です♪"

# 商人風の男
# おお！？　なんて美しい天使の絵を！\nまるで筆で描いたかのような出来栄えです！
360 = "おお！？　なんて美しい天使の絵を！\\nまるで筆で描いたかのような出来栄えです！"

# アクア
# ご主人様に褒めていただけるなんて、\nアクアは世界一幸せなメイドです。
368 = "ご主人様に褒めていただけるなんて、\\nアクアは世界一幸せなメイドです。"

# 戦士風の男冒険者
# display as 戦士冒険者
# メイドさん俺の料理にも！
444 = "メイドさん俺の料理にも！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# 俺も俺も！！
450 = "俺も俺も！！"

# アクア
# はい、すぐにお伺いしますので、\n少々お待ちください。
403 = "はい、すぐにお伺いしますので、\\n少々お待ちください。"

# カズマ（Ｍ）
# display as カズマ
# （あいつの無駄な器用さが無駄に役立ってるな）
537 = "（あいつの無駄な器用さが無駄に役立ってるな）"

# カズマ（Ｍ）
# display as カズマ
# （さて、ウィズはどうかな）
543 = "（さて、ウィズはどうかな）"

# ウィズ
# わ、私も、頑張らないと！
424 = "わ、私も、頑張らないと！"

# 聖職者風の男冒険者
# display as 聖職冒険者
# 熱っ！？
464 = "熱っ！？"

# ウィズ
# あっ、大丈夫ですかご主人様？
331 = "あっ、大丈夫ですかご主人様？"

# 聖職者風の男冒険者
# display as 聖職冒険者
# いやー、冷めるのを待ってたんだけど、\nまだ熱かったみたいですね。
348 = "いやー、冷めるのを待ってたんだけど、\\nまだ熱かったみたいですね。"

# ウィズ
# お気をつけくださいね。\n火傷をしたら大変ですから。
362 = "お気をつけくださいね。\\n火傷をしたら大変ですから。"

# カズマ（Ｍ）
# display as カズマ
# （ウィズ、メイドはそれだけじゃダメだぞ！）
552 = "（ウィズ、メイドはそれだけじゃダメだぞ！）"

# ウィズ
# %fsyogen;え、ええと、あの、ご主人様？\nお料理を冷ます手伝いをさせていただいても\nよろしいですか？
27 = "%fsyogen;え、ええと、あの、ご主人様？\\nお料理を冷ます手伝いをさせていただいても\\nよろしいですか？"

# カズマ（Ｍ）
# display as カズマ
# （ウィズ、よくやった！\n　それでこそメイドだ！）
551 = "（ウィズ、よくやった！\\n　それでこそメイドだ！）"

# カズマ（Ｍ）
# display as カズマ
# （この感動を証言としてメモして\n　おこう……）
540 = "（この感動を証言としてメモして\\n　おこう……）"

# カズマ（Ｍ）
# display as カズマ
# （って、この証言って意味があるのかな……）
545 = "（って、この証言って意味があるのかな……）"

# 聖職者風の男冒険者
# display as 聖職冒険者
# あ、はい。\nでも、どうやって。
328 = "あ、はい。\\nでも、どうやって。"

# ウィズ
# し、失礼します。\nふー……ふー……。
371 = "し、失礼します。\\nふー……ふー……。"

# 聖職者風の男冒険者
# display as 聖職冒険者
# なぁ！？
391 = "なぁ！？"

# ウィズ
# ふーふー……。\nこれで食べやすくなったかと。
410 = "ふーふー……。\\nこれで食べやすくなったかと。"

# 聖職者風の男冒険者
# display as 聖職冒険者
# …………。
326 = "…………。"

# ウィズ
# あっ、出過ぎた真似でしたね。\n申し訳ございません。
330 = "あっ、出過ぎた真似でしたね。\\n申し訳ございません。"

# 聖職者風の男冒険者
# display as 聖職冒険者
# いえ、最高です！\nむしろもっとして欲しいくらいです！
343 = "いえ、最高です！\\nむしろもっとして欲しいくらいです！"

# ウィズ
# えー！？
353 = "えー！？"

# カズマ
# めぐみん、ゆんゆん！
419 = "めぐみん、ゆんゆん！"

# ゆんゆん
# ど、どうしようめぐみん。\nカズマさんから指示が来ちゃったよ。
386 = "ど、どうしようめぐみん。\\nカズマさんから指示が来ちゃったよ。"

# めぐみん
# どうもこうも、やるしかないでしょう。\nほら、さっさといってください。
388 = "どうもこうも、やるしかないでしょう。\\nほら、さっさといってください。"

# ゆんゆん
# えー！？　なんで私だけー！？
354 = "えー！？　なんで私だけー！？"

# めぐみん
# ほーらっ、早く！
412 = "ほーらっ、早く！"

# ゆんゆん
# あん、もう、押さないでったらぁ！
338 = "あん、もう、押さないでったらぁ！"

# カズマ（Ｍ）
# display as カズマ
# （さて、ゆんゆんは上手にできるかな？）
542 = "（さて、ゆんゆんは上手にできるかな？）"

# ゆんゆん
# あ……あの、ご主人様。\nご注文はお決まりになりましたか？
327 = "あ……あの、ご主人様。\\nご注文はお決まりになりましたか？"

# アーチャー風の男冒険者
# display as 射手冒険者
# いや、まだちょっと迷ってて。
346 = "いや、まだちょっと迷ってて。"

# ゆんゆん
# で、でしたら……。
380 = "で、でしたら……。"

# ゆんゆん
# 今日はね、これがお勧めだよ？
447 = "今日はね、これがお勧めだよ？"

# アーチャー風の男冒険者
# display as 射手冒険者
# え？
355 = "え？"

# ゆんゆん
# すごく美味しいの。\nお兄ちゃんもきっと気に入ると思うな。
375 = "すごく美味しいの。\\nお兄ちゃんもきっと気に入ると思うな。"

# アーチャー風の男冒険者
# display as 射手冒険者
# お、お兄ちゃん！？
357 = "お、お兄ちゃん！？"

# ゆんゆん
# ダメ、かな？
442 = "ダメ、かな？"

# アーチャー風の男冒険者
# display as 射手冒険者
# いや、それにする。\nお兄ちゃんもそれが食べたいと思ってたんだ。うん。
345 = "いや、それにする。\\nお兄ちゃんもそれが食べたいと思ってたんだ。うん。"

# ゆんゆん
# えへ、私ね、お兄ちゃんなら絶対に\nそうだろうなって思ったの。
351 = "えへ、私ね、お兄ちゃんなら絶対に\\nそうだろうなって思ったの。"

# アーチャー風の男冒険者
# display as 射手冒険者
# はぁぁぁぁ～～～～。
400 = "はぁぁぁぁ～～～～。"

# カズマ（Ｍ）
# display as カズマ
# （巨乳の妹！　どうよこの設定は！）
555 = "（巨乳の妹！　どうよこの設定は！）"

# めぐみん
# …………。
# 326 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （それに引き替え、\n　なんだめぐみんのやる気の態度は！）
544 = "（それに引き替え、\\n　なんだめぐみんのやる気の態度は！）"

# 遊び人風の男冒険者
# display as 遊び人風の男
# おーい、ちょっと注文いいか？
361 = "おーい、ちょっと注文いいか？"

# めぐみん
# あーはい。どうぞご主人様。
339 = "あーはい。どうぞご主人様。"

# 遊び人風の男冒険者
# display as 遊び人風の男
# ええと、まずこれと……あとは……。
350 = "ええと、まずこれと……あとは……。"

# めぐみん
# 早くしてくださいよ。\n決まったから呼んだんじゃないんですか？
461 = "早くしてくださいよ。\\n決まったから呼んだんじゃないんですか？"

# 遊び人風の男冒険者
# display as 遊び人風の男
# しょうがないだろ、迷ってるんだから。
372 = "しょうがないだろ、迷ってるんだから。"

# めぐみん
# まったく。優柔不断なご主人様ですね。
415 = "まったく。優柔不断なご主人様ですね。"

# 遊び人風の男冒険者
# display as 遊び人風の男
# じゃあ……これを頼む。
374 = "じゃあ……これを頼む。"

# めぐみん
# 承知しました。少々お待ちくださいませ。
460 = "承知しました。少々お待ちくださいませ。"

# 遊び人風の男冒険者
# display as 遊び人風の男
# ちっ、なんだよその態度は。\nこのハズレメイドがっ！
377 = "ちっ、なんだよその態度は。\\nこのハズレメイドがっ！"

# めぐみん
# はあ？
402 = "はあ？"

# カズマ
# おい、めぐみん！
358 = "おい、めぐみん！"

# めぐみん
# ちょっと、なんですか！\n痛いから引っ張らないでくださいよ！
379 = "ちょっと、なんですか！\\n痛いから引っ張らないでくださいよ！"

# カズマ
# 今のは、最悪の接客態度だぞ。
446 = "今のは、最悪の接客態度だぞ。"

# めぐみん
# わかってますよ。\nでも、あの男、ずっと私をジロジロ見てるんです。
426 = "わかってますよ。\\nでも、あの男、ずっと私をジロジロ見てるんです。"

# カズマ（Ｍ）
# display as カズマ
# （なるほど、それでイライラしてたのか）
547 = "（なるほど、それでイライラしてたのか）"

# めぐみん
# 私がフロアに立ってても\n店の評判を落とすだけですし、奥に引っ込みます。
530 = "私がフロアに立ってても\\n店の評判を落とすだけですし、奥に引っ込みます。"

# カズマ
# 何を言ってる、ここからがお前の可愛らしさの\n生きる所じゃ無いか！
449 = "何を言ってる、ここからがお前の可愛らしさの\\n生きる所じゃ無いか！"

# めぐみん
# か、かわ！？\nな、なんですか、それ。
363 = "か、かわ！？\\nな、なんですか、それ。"

# カズマ
# いいか、これからお前に秘策を授けてやる。
341 = "いいか、これからお前に秘策を授けてやる。"

# めぐみん
# 正直、嫌な予感しかしません。
462 = "正直、嫌な予感しかしません。"

# カズマ
# あの客に、料理を持っていくときにデレろ。
335 = "あの客に、料理を持っていくときにデレろ。"

# めぐみん
# で、でれ？
381 = "で、でれ？"

# カズマ
# 少しだけ好意をおもてに出すんだ。
454 = "少しだけ好意をおもてに出すんだ。"

# カズマ
# でも、出し過ぎるのはダメだぞ！
384 = "でも、出し過ぎるのはダメだぞ！"

# カズマ
# 微妙なさじ加減を求められるが、\nめぐみんならできると俺は信じてる！
457 = "微妙なさじ加減を求められるが、\\nめぐみんならできると俺は信じてる！"

# めぐみん
# はぁ、わかりました。\nやるだけやってみます。
397 = "はぁ、わかりました。\\nやるだけやってみます。"

# カズマ
# よし、行ってこい！
423 = "よし、行ってこい！"

# めぐみん
# ご注文の品をお持ちしました。
369 = "ご注文の品をお持ちしました。"

# 遊び人風の男冒険者
# display as 遊び人風の男
# なんだ、またお前か。
392 = "なんだ、またお前か。"

# めぐみん
# むかっ！
416 = "むかっ！"

# カズマ
# めぐみん、でれる！
418 = "めぐみん、でれる！"

# めぐみん
# ふぅ……。\nだってしょうがないじゃないですか、\nご主人様の顔を見たくなってしまったのですから。
408 = "ふぅ……。\\nだってしょうがないじゃないですか、\\nご主人様の顔を見たくなってしまったのですから。"

# 遊び人風の男冒険者
# display as 遊び人風の男
# へ？
411 = "へ？"

# めぐみん
# な、なんでもありませんよ！\nそれで？　料理は他のメイドに運ばせますか？
390 = "な、なんでもありませんよ！\\nそれで？　料理は他のメイドに運ばせますか？"

# 遊び人風の男冒険者
# display as 遊び人風の男
# い、いや、お前でいい。お前がいい！
340 = "い、いや、お前でいい。お前がいい！"

# めぐみん
# ま、まあ、他のメイドがいいと言っても\nそんな事は私が許しませんけどね。
413 = "ま、まあ、他のメイドがいいと言っても\\nそんな事は私が許しませんけどね。"

# 遊び人風の男冒険者
# display as 遊び人風の男
# どど、どうしてだ！
389 = "どど、どうしてだ！"

# めぐみん
# あなたに尽くしていいメイドは私だけだからですよ。\nもう、こんなこと言わせないでください。
334 = "あなたに尽くしていいメイドは私だけだからですよ。\\nもう、こんなこと言わせないでください。"

# 遊び人風の男冒険者
# display as 遊び人風の男
# はぁぁぁぁぁ～～～～。
399 = "はぁぁぁぁぁ～～～～。"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんめ、アドリブであんなこと言うなんて、\n　やってくれるぜ）
549 = "（めぐみんめ、アドリブであんなこと言うなんて、\\n　やってくれるぜ）"

# カズマ
# ダクネス、クリス！
439 = "ダクネス、クリス！"

# クリス
# はぁ、カズマから合図が来ちゃったよ。
398 = "はぁ、カズマから合図が来ちゃったよ。"

# クリス
# ねえ、ダクネス、本当にやるの？\n正直、気乗りしな――
395 = "ねえ、ダクネス、本当にやるの？\\n正直、気乗りしな――"

# ダクネス
# 行ってくる！
534 = "行ってくる！"

# クリス
# ちょっと、ええ！？
378 = "ちょっと、ええ！？"

# ダクネス
# きゃ！
364 = "きゃ！"

# 戦士風の男冒険者
# display as 戦士冒険者
# あっ！
332 = "あっ！"

# ダクネス
# ああ、ご主人様、申しわけありません。\nすぐに代わりのスプーンをお持ちしますので！
329 = "ああ、ご主人様、申しわけありません。\\nすぐに代わりのスプーンをお持ちしますので！"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスは根が正直なだけに、\n　こういう演技事には向いてないんだよな……）
554 = "（ダクネスは根が正直なだけに、\\n　こういう演技事には向いてないんだよな……）"

# ダクネス
# はぁはぁ、お待たせいたしました。
401 = "はぁはぁ、お待たせいたしました。"

# 戦士風の男冒険者
# display as 戦士冒険者
# ありがとう。\nでも、そんなに急ぐことなかったのに。
337 = "ありがとう。\\nでも、そんなに急ぐことなかったのに。"

# ダクネス
# だ、だって、少しでも遅くなったら\n仕付けが厳しいものになるのでしょう？
376 = "だ、だって、少しでも遅くなったら\\n仕付けが厳しいものになるのでしょう？"

# 戦士風の男冒険者
# display as 戦士冒険者
# は？　しつけ？
406 = "は？　しつけ？"

# ダクネス
# 粗相をした使用人に厳しい仕付けをするのも\n主人の勤めです。
531 = "粗相をした使用人に厳しい仕付けをするのも\\n主人の勤めです。"

# ダクネス
# さあ、遠慮なさらずになんでも言ってください！
370 = "さあ、遠慮なさらずになんでも言ってください！"

# カズマ（Ｍ）
# display as カズマ
# （あのバカ、あれだけ食いつくなって\n　言ったのに！）
538 = "（あのバカ、あれだけ食いつくなって\\n　言ったのに！）"

# 戦士風の男冒険者
# display as 戦士冒険者
# 仕付けだなんて、何かのジョークかな？\nあはははは。
448 = "仕付けだなんて、何かのジョークかな？\\nあはははは。"

# カズマ（Ｍ）
# display as カズマ
# （まあ客は喜んでるみたいだし、\n　あれはあれでいいか）
548 = "（まあ客は喜んでるみたいだし、\\n　あれはあれでいいか）"

# カズマ（Ｍ）
# display as カズマ
# （で、クリスはどうだ？）
546 = "（で、クリスはどうだ？）"

# クリス
# ご主人様、お料理お持ちしました。
366 = "ご主人様、お料理お持ちしました。"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# くく、クリス、なかなか似合ってるぞ。
365 = "くく、クリス、なかなか似合ってるぞ。"

# クリス
# よ、喜んでいただけて何よりです。
422 = "よ、喜んでいただけて何よりです。"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# でも、できたら違うメイドさんに\n持って来て欲しかったかなー。
383 = "でも、できたら違うメイドさんに\\n持って来て欲しかったかなー。"

# クリス
# どういう意味ですか、ご主人様？
387 = "どういう意味ですか、ご主人様？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# いやさ、なんかお前のメイドって\n当たり障りがないっていうか、良くも悪くも\n普通なんだよ。
347 = "いやさ、なんかお前のメイドって\\n当たり障りがないっていうか、良くも悪くも\\n普通なんだよ。"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# まあ、お前に可愛らしい演技をされても\n背中が痒くなるだけど。
414 = "まあ、お前に可愛らしい演技をされても\\n背中が痒くなるだけど。"

# クリス
# では、当店のサービスはいりませんね！
382 = "では、当店のサービスはいりませんね！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# サービス？　なんだそれ。\nタダならやって貰うけど。
437 = "サービス？　なんだそれ。\\nタダならやって貰うけど。"

# クリス
# あっ！　え、ええと……。
333 = "あっ！　え、ええと……。"

# カズマ（Ｍ）
# display as カズマ
# （クリス頑張れ！\n　羞恥を捨てるんだ！）
553 = "（クリス頑張れ！\\n　羞恥を捨てるんだ！）"

# クリス
# わ、笑わないって……約束してくれる？
425 = "わ、笑わないって……約束してくれる？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# なんだよ、やるなら早くやってくれ。\n料理が冷めちまうだろ。
393 = "なんだよ、やるなら早くやってくれ。\\n料理が冷めちまうだろ。"

# クリス
# じゃ、じゃあ、いくよ？
373 = "じゃ、じゃあ、いくよ？"

# クリス
# おいしくな～れ♪　もえもえきゅ～ん♪
359 = "おいしくな～れ♪　もえもえきゅ～ん♪"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# ふぁおはぁ！？
407 = "ふぁおはぁ！？"

# クリス
# ええと……キャラじゃないよね？
349 = "ええと……キャラじゃないよね？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# いや……最高だよ、お前。
344 = "いや……最高だよ、お前。"

# クリス
# あは、あはは、そ、そうかな？\nじゃあ、ごゆっくりどうぞ～。
336 = "あは、あはは、そ、そうかな？\\nじゃあ、ごゆっくりどうぞ～。"

# カズマ（Ｍ）
# display as カズマ
# （いいぞ。その調子だ。\n　メイド姿だけでなくサービスも\n　相乗効果になって、注文が止まることがない）
539 = "（いいぞ。その調子だ。\\n　メイド姿だけでなくサービスも\\n　相乗効果になって、注文が止まることがない）"

# カズマ（Ｍ）
# display as カズマ
# （これは売り上げが楽しみになってきたぞ！）
541 = "（これは売り上げが楽しみになってきたぞ！）"

[selections]
429 = "アクアとウィズにサインを送る"
420 = "めぐみんとゆんゆんにサインを送る"
440 = "ダクネスとクリスにサインを送る"
