# st01b_03.txt.scn

[info]
127 = "st01b_03"

[characters]
180 = "ゆんゆん"
186 = "カズマ"
179 = "めぐみん"
184 = "アクア＆めぐみん＆ダクネス"
185 = "ウィズ"
190 = "クリス＆ゆんゆん＆ウィズ"
188 = "カズマ（Ｍ）"
183 = "アクア"
191 = "ダクネス"
189 = "クリス"

[character_subs]
230 = "３人"
# 186 = "カズマ"

[script]
# lines: 44

# ゆんゆん
# でもそうなると、指輪を外してもらうために、\nお金をどうにかしないといけないんですよね？
173 = "でもそうなると、指輪を外してもらうために、\\nお金をどうにかしないといけないんですよね？"

# カズマ
# ああ。だから改めてみんなに協力を頼みたい。
155 = "ああ。だから改めてみんなに協力を頼みたい。"

# カズマ
# 今度はもう、次まで一ヵ月あるなんて\nのんびりする気はないからな。
193 = "今度はもう、次まで一ヵ月あるなんて\\nのんびりする気はないからな。"

# めぐみん
# 急にやる気を出したりして、どうしたんです？
200 = "急にやる気を出したりして、どうしたんです？"

# めぐみん
# カズマにしてみれば、毎月誰かの下着を\n手に入れることができて本望でしょうに。
187 = "カズマにしてみれば、毎月誰かの下着を\\n手に入れることができて本望でしょうに。"

# カズマ
# 俺が自分の意思で\nやってるような言いがかりはやめろ！
194 = "俺が自分の意思で\\nやってるような言いがかりはやめろ！"

# カズマ
# いいか？　この指輪のせいでスティールが\n強化されて、パンツなんてそこら中から盗みたい\n放題だったのに、前回はめぐみん――
157 = "いいか？　この指輪のせいでスティールが\\n強化されて、パンツなんてそこら中から盗みたい\\n放題だったのに、前回はめぐみん――"

# カズマ
# そして今回も、おそらくこの中の誰かから盗った。\nそれがどういう意味なのか、よーく考えてみろ。
167 = "そして今回も、おそらくこの中の誰かから盗った。\\nそれがどういう意味なのか、よーく考えてみろ。"

# アクア＆めぐみん＆ダクネス
# display as ３人
# ？
231 = "？"

# ウィズ
# あ、もしかしてその指輪は、\n装着した人の知人の下着を欲しがっている\nということなんですか？
153 = "あ、もしかしてその指輪は、\\n装着した人の知人の下着を欲しがっている\\nということなんですか？"

# カズマ
# ああ、たぶんそれが正解だ。
154 = "ああ、たぶんそれが正解だ。"

# ゆんゆん
# でも、どうしてそんな。\n男の人からしたら、女の子の下着なんて\nどれも同じような物なんじゃないですか？
171 = "でも、どうしてそんな。\\n男の人からしたら、女の子の下着なんて\\nどれも同じような物なんじゃないですか？"

# カズマ
# 甘いぞゆんゆん。
204 = "甘いぞゆんゆん。"

# ゆんゆん
# え？
160 = "え？"

# カズマ
# 確かに男は、色とか布の面積とか、\nそういう見た目でしか女の子の下着の\n違いなんてわかっていないのかもしれない。
227 = "確かに男は、色とか布の面積とか、\\nそういう見た目でしか女の子の下着の\\n違いなんてわかっていないのかもしれない。"

# カズマ
# でも、だからこそ、\nその下着が誰の物なのかってことが重要なんだ！
170 = "でも、だからこそ、\\nその下着が誰の物なのかってことが重要なんだ！"

# カズマ
# へー、あんなに大人っぽいお姉様が、\n子供みたいなプリント物のパンツを\n穿いてるのかー、とか――
177 = "へー、あんなに大人っぽいお姉様が、\\n子供みたいなプリント物のパンツを\\n穿いてるのかー、とか――"

# カズマ
# 嘘だろ、あんな地味な子なのに\nパンツはド派手じゃないか！？　とか――
197 = "嘘だろ、あんな地味な子なのに\\nパンツはド派手じゃないか！？　とか――"

# カズマ
# そういうスパイスがあるから下着にも欲情できる\nのであって、誰の物かもわからない下着なんて\nただの布切れ同然というかだな――
166 = "そういうスパイスがあるから下着にも欲情できる\\nのであって、誰の物かもわからない下着なんて\\nただの布切れ同然というかだな――"

# アクア＆めぐみん＆ダクネス
# display as ３人
# …………。
152 = "…………。"

# クリス＆ゆんゆん＆ウィズ
# display as ３人
# …………。
# 152 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （あ、あれ？　何この冷たい空気？）
229 = "（あ、あれ？　何この冷たい空気？）"

# アクア
# ねえ、今回のことって指輪のせいにしてるけど、\nやっぱり本当はカズマがやってるんじゃない？
176 = "ねえ、今回のことって指輪のせいにしてるけど、\\nやっぱり本当はカズマがやってるんじゃない？"

# ダクネス
# あの熱のこもった語り口、確かに疑いたくなるな。
156 = "あの熱のこもった語り口、確かに疑いたくなるな。"

# めぐみん
# 指輪が取れた後も、\n私たちの洗濯物は、部屋干しにした方が\nいいかもしれませんね。
201 = "指輪が取れた後も、\\n私たちの洗濯物は、部屋干しにした方が\\nいいかもしれませんね。"

# カズマ
# ごほん。\nまあ、そういう一般論は置いておくとしてだ。
163 = "ごほん。\\nまあ、そういう一般論は置いておくとしてだ。"

# カズマ
# ここで問題なのは、\n知人て定義がどこまでかってことだな。
161 = "ここで問題なのは、\\n知人て定義がどこまでかってことだな。"

# カズマ
# これが、お前たちみたいなごく身近なやつに\n限られるなら、まだいい。
162 = "これが、お前たちみたいなごく身近なやつに\\n限られるなら、まだいい。"

# アクア
# ぜんぜん良くないんですけどー。
165 = "ぜんぜん良くないんですけどー。"

# カズマ
# いいとしてっ！\nその定義が、もし顔見知り程度にまで\n及ぶようなら、俺の身が破滅しかねないんだよ。
159 = "いいとしてっ！\\nその定義が、もし顔見知り程度にまで\\n及ぶようなら、俺の身が破滅しかねないんだよ。"

# めぐみん
# なるほど。街中の女性から目の敵に。\nいえ、それくらいで済めばまだマシですね。
174 = "なるほど。街中の女性から目の敵に。\\nいえ、それくらいで済めばまだマシですね。"

# ダクネス
# 最悪、下着泥棒として捕まったり、\nセクハラで裁判沙汰になるかもしれないな。
202 = "最悪、下着泥棒として捕まったり、\\nセクハラで裁判沙汰になるかもしれないな。"

# ウィズ
# でも、指輪のせいだって説明すれば。
172 = "でも、指輪のせいだって説明すれば。"

# クリス
# わかってて放置してたら、\nわざとやってるって思われても\n仕方ないんじゃないかな。
182 = "わかってて放置してたら、\\nわざとやってるって思われても\\n仕方ないんじゃないかな。"

# ゆんゆん
# じゃあこのままだとカズマさん、\n街中の人に犯罪者扱いされちゃうかもって\nことなんですね。
164 = "じゃあこのままだとカズマさん、\\n街中の人に犯罪者扱いされちゃうかもって\\nことなんですね。"

# カズマ
# まったくもって不本意だが、そういうことだ。
178 = "まったくもって不本意だが、そういうことだ。"

# アクア
# いいじゃない。\n実際、犯罪行為をしてるんだし。
158 = "いいじゃない。\\n実際、犯罪行為をしてるんだし。"

# カズマ
# 言っとくけど、\nお前らだって他人事じゃないんだぞ！
228 = "言っとくけど、\\nお前らだって他人事じゃないんだぞ！"

# アクア
# なんでよ？
175 = "なんでよ？"

# カズマ
# 犯罪者扱いされてるやつがパーティーメンバーに\nいたら、お前らだって同じように見られるかも\nしれないってことだよ。
203 = "犯罪者扱いされてるやつがパーティーメンバーに\\nいたら、お前らだって同じように見られるかも\\nしれないってことだよ。"

# ダクネス
# わ、私たちも街中の人間から\n蔑まれるかもしれないということか。
181 = "わ、私たちも街中の人間から\\n蔑まれるかもしれないということか。"

# めぐみん
# それはさすがに勘弁してもらいたいんですけど。
168 = "それはさすがに勘弁してもらいたいんですけど。"

# カズマ
# だろう？　だから力を貸してくれよ。な？
169 = "だろう？　だから力を貸してくれよ。な？"

# アクア＆めぐみん＆ダクネス
# display as ３人
# …………。
# 152 = "…………。"

