# st01b_02.txt.scn

[info]
186 = "st01b_02"

[characters]
275 = "めぐみん"
281 = "カズマ"
289 = "ダクネス"
285 = "クリス"
280 = "ウィズ"
277 = "ゆんゆん"
284 = "カズマ（Ｍ）"
279 = "アクア＆めぐみん＆ダクネス"
286 = "クリス＆ゆんゆん＆ウィズ"
278 = "アクア"

[character_subs]
# 281 = "カズマ"
358 = "３人"

[script]
# lines: 88

# めぐみん
# いったいどんな手を使ったんですか！
230 = "いったいどんな手を使ったんですか！"

# カズマ
# はあ？　なんのことだよ。
269 = "はあ？　なんのことだよ。"

# ダクネス
# その手に持っている物のことだ。
246 = "その手に持っている物のことだ。"

# クリス
# えーと、キミは昨夜ずっとこの屋敷にいたん\nだよね？
235 = "えーと、キミは昨夜ずっとこの屋敷にいたん\\nだよね？"

# カズマ
# ああ、一歩も出てないぞ。
226 = "ああ、一歩も出てないぞ。"

# ウィズ
# それなのにどうして、下着を。
250 = "それなのにどうして、下着を。"

# ゆんゆん
# なんだか私、すごく怖いです。
263 = "なんだか私、すごく怖いです。"

# カズマ
# ちょっ、待て待て待て！\nとりあえず状況を説明してくれよ！
253 = "ちょっ、待て待て待て！\\nとりあえず状況を説明してくれよ！"

# めぐみん
# その前に、ひとつ確認しておきたいのですが。\n私の部屋の前で、何をしていたんです？
245 = "その前に、ひとつ確認しておきたいのですが。\\n私の部屋の前で、何をしていたんです？"

# カズマ
# え、いや、別に何もしてないけど。
232 = "え、いや、別に何もしてないけど。"

# めぐみん
# 正直に言ってください。\n今さら隠し立てしても意味なんてないでしょう。
304 = "正直に言ってください。\\n今さら隠し立てしても意味なんてないでしょう。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、確かにそうだな）
351 = "（まあ、確かにそうだな）"

# カズマ
# 実はさ、昨日の夜もこの指輪の力が\n発動したらしくて、起きたらまた\nパンツを握ってたんだ。
298 = "実はさ、昨日の夜もこの指輪の力が\\n発動したらしくて、起きたらまた\\nパンツを握ってたんだ。"

# カズマ
# それで、たぶん誰かのタンスの中から\n盗っちまったんだろうと思ってさ――
249 = "それで、たぶん誰かのタンスの中から\\n盗っちまったんだろうと思ってさ――"

# めぐみん
# その事実を隠蔽するために、\n私の部屋に忍び込もうとしていたわけですか。
244 = "その事実を隠蔽するために、\\n私の部屋に忍び込もうとしていたわけですか。"

# カズマ
# 隠蔽とかやめてくれ。\n犯罪臭がはんぱないだろ。
344 = "隠蔽とかやめてくれ。\\n犯罪臭がはんぱないだろ。"

# ゆんゆん
# 人の下着を盗っているのですから、\n立派な犯罪かと。
291 = "人の下着を盗っているのですから、\\n立派な犯罪かと。"

# カズマ（Ｍ）
# display as カズマ
# （ぐうの音も出ない正論を！）
346 = "（ぐうの音も出ない正論を！）"

# ダクネス
# まあまあ、正直に話したことは\n評価しようじゃないか。
272 = "まあまあ、正直に話したことは\\n評価しようじゃないか。"

# めぐみん
# そうやって甘やかすから調子に乗るんですよ、\nカズマは。
243 = "そうやって甘やかすから調子に乗るんですよ、\\nカズマは。"

# ダクネス
# さて、カズマ。\nもう一度念のために確認をしたいのだが、\n昨夜は一歩もこの屋敷から出ていないんだな？
239 = "さて、カズマ。\\nもう一度念のために確認をしたいのだが、\\n昨夜は一歩もこの屋敷から出ていないんだな？"

# カズマ
# さっきからその質問はなんなんだよ。\nこのパンツはタンスから盗っちまった物なんだろ？
238 = "さっきからその質問はなんなんだよ。\\nこのパンツはタンスから盗っちまった物なんだろ？"

# ウィズ
# それが違うみたいなんです。
248 = "それが違うみたいなんです。"

# カズマ（Ｍ）
# display as カズマ
# （え、どういうこと？）
345 = "（え、どういうこと？）"

# ダクネス
# 昨日、この屋敷には、私たちの下着は一枚も\n置いてなかったんだ。
302 = "昨日、この屋敷には、私たちの下着は一枚も\\n置いてなかったんだ。"

# カズマ
# は？
270 = "は？"

# ダクネス
# タンスから盗られる可能性も考えて、\n出かける前にみんな持ち出しておいた。
288 = "タンスから盗られる可能性も考えて、\\n出かける前にみんな持ち出しておいた。"

# カズマ
# えっと、じゃあこのパンツはいったい。
234 = "えっと、じゃあこのパンツはいったい。"

# カズマ
# あっ、そういえば、さっきアクアが、\nやっぱり俺だったのかって言ってたけど。
227 = "あっ、そういえば、さっきアクアが、\\nやっぱり俺だったのかって言ってたけど。"

# カズマ
# まさかこのパンツは、\nお前たちの誰かが穿いてたやつなのか！？
273 = "まさかこのパンツは、\\nお前たちの誰かが穿いてたやつなのか！？"

# アクア＆めぐみん＆ダクネス
# display as ３人
# …………。
222 = "…………。"

# クリス＆ゆんゆん＆ウィズ
# display as ３人
# …………。
# 222 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （この反応は間違いない。\n　また俺は、寝ている誰かからパンツを盗って\n　しまったんだ！）
348 = "（この反応は間違いない。\\n　また俺は、寝ている誰かからパンツを盗って\\n　しまったんだ！）"

# カズマ（Ｍ）
# display as カズマ
# （でも、いったいどうやって、このパンツを）
350 = "（でも、いったいどうやって、このパンツを）"

# カズマ（Ｍ）
# display as カズマ
# （昨夜、この家にパンツは１枚も置いてなかった。\n　しかし俺はパンツを持っている）
356 = "（昨夜、この家にパンツは１枚も置いてなかった。\\n　しかし俺はパンツを持っている）"

# カズマ（Ｍ）
# display as カズマ
# （この事実が示すことはいったいっ！）
347 = "（この事実が示すことはいったいっ！）"

# ゆんゆん
# あ、あの、カズマさん？\n真面目な顔をして下着を広げたりしてると、\nなんていうか……。
224 = "あ、あの、カズマさん？\\n真面目な顔をして下着を広げたりしてると、\\nなんていうか……。"

# アクア
# まるで変質者ね。
274 = "まるで変質者ね。"

# カズマ
# お前、マジなトーンでそんなこと言うなよ！\n傷つくだろ！
237 = "お前、マジなトーンでそんなこと言うなよ！\\n傷つくだろ！"

# カズマ
# 持ち主さえわかればすぐに返すから、\n早く教えてくれよ。
301 = "持ち主さえわかればすぐに返すから、\\n早く教えてくれよ。"

# ウィズ
# ええと。
233 = "ええと。"

# クリス
# %fsyogen;あのさ、前も言ったと思うけど、\nそんなふうに盗られた下着を返されても、\nたぶんみんな困ると思うんだよね。
22 = "%fsyogen;あのさ、前も言ったと思うけど、\\nそんなふうに盗られた下着を返されても、\\nたぶんみんな困ると思うんだよね。"

# カズマ（Ｍ）
# display as カズマ
# （俺の紳士的な行為で\n　そこまで困るのか……）
354 = "（俺の紳士的な行為で\\n　そこまで困るのか……）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、逆に考えると\n　状況の混乱を企んでいるとも言えるな……。\n　証言としてゲットしておくか……）
349 = "（しかし、逆に考えると\\n　状況の混乱を企んでいるとも言えるな……。\\n　証言としてゲットしておくか……）"

# めぐみん
# %fsyogen;ですから、決めた場所にパンツを置いて、\n持ち主がこっそり回収するというのが\nもっとも合理的な手段だと思うのです。
23 = "%fsyogen;ですから、決めた場所にパンツを置いて、\\n持ち主がこっそり回収するというのが\\nもっとも合理的な手段だと思うのです。"

# カズマ（Ｍ）
# display as カズマ
# （決めた場所にパンツを置いて\n　反応を見る……確かに合理的だが、\n　その行為は紳士的な行為ではない！）
357 = "（決めた場所にパンツを置いて\\n　反応を見る……確かに合理的だが、\\n　その行為は紳士的な行為ではない！）"

# カズマ（Ｍ）
# display as カズマ
# （俺はあくまで紳士的にパンツを\n　返すことが目的なのだ！\n　やましい気持ちなどみじんもないぞ！）
355 = "（俺はあくまで紳士的にパンツを\\n　返すことが目的なのだ！\\n　やましい気持ちなどみじんもないぞ！）"

# カズマ（Ｍ）
# display as カズマ
# （一応、証言としてゲットしておくか……）
353 = "（一応、証言としてゲットしておくか……）"

# カズマ
# だからそれは俺の紳士魂が許さないんだよ！
252 = "だからそれは俺の紳士魂が許さないんだよ！"

# クリス
# はぁ、こっちの乙女心も理解して欲しいよ。
268 = "はぁ、こっちの乙女心も理解して欲しいよ。"

# カズマ
# てかさ、この中の誰かは今、\nパンツを穿いてないんだよな。
257 = "てかさ、この中の誰かは今、\\nパンツを穿いてないんだよな。"

# ゆんゆん
# ひっ！
271 = "ひっ！"

# ウィズ
# あ、あの、カズマさん。\n目がちょっといやらしいですよ？
223 = "あ、あの、カズマさん。\\n目がちょっといやらしいですよ？"

# カズマ
# お、おっと悪い。
236 = "お、おっと悪い。"

# アクア
# なんにせよ、\n思ってた以上に厄介な指輪みたいね。
267 = "なんにせよ、\\n思ってた以上に厄介な指輪みたいね。"

# めぐみん
# ですね。昨夜はみんな一緒にいて、\n誰もこの屋敷には近づかなかったというのに、\nこの結果なんですから。
259 = "ですね。昨夜はみんな一緒にいて、\\n誰もこの屋敷には近づかなかったというのに、\\nこの結果なんですから。"

# ダクネス
# カズマが無意識に街を徘徊して、\n私たちの所にやって来たということなのだろうか？
282 = "カズマが無意識に街を徘徊して、\\n私たちの所にやって来たということなのだろうか？"

# カズマ
# 何それ。\n夢遊病者みたいで別の意味で怖いんだけど。
293 = "何それ。\\n夢遊病者みたいで別の意味で怖いんだけど。"

# ウィズ
# あの、指輪を改めて\n調べさせてもらってもいいですか？
228 = "あの、指輪を改めて\\n調べさせてもらってもいいですか？"

# カズマ
# 何か気になることでもあるのか？
292 = "何か気になることでもあるのか？"

# ウィズ
# いえ、あくまで確認をしてみるだけで。
229 = "いえ、あくまで確認をしてみるだけで。"

# ウィズ
# …………。
# 222 = "…………。"

# ウィズ
# なるほど。そういうことですか。
262 = "なるほど。そういうことですか。"

# カズマ
# そういうことって？
241 = "そういうことって？"

# ウィズ
# どうやらこの指輪は、装着してる人の能力を\n増幅させる効果も持っているようです。
261 = "どうやらこの指輪は、装着してる人の能力を\\n増幅させる効果も持っているようです。"

# カズマ
# 能力を増幅させる？
343 = "能力を増幅させる？"

# ウィズ
# カズマさんの場合だと、\nおそらくスティールの能力を増幅させて\n使ったのではないかと。
283 = "カズマさんの場合だと、\\nおそらくスティールの能力を増幅させて\\n使ったのではないかと。"

# ウィズ
# スティールの効果の及ぶ範囲を拡大して、\n精度を高め、遠方にいる相手から無理やり下着を\n奪ったのではないでしょうか。
287 = "スティールの効果の及ぶ範囲を拡大して、\\n精度を高め、遠方にいる相手から無理やり下着を\\n奪ったのではないでしょうか。"

# ダクネス
# ちょっと待て。\n増幅させると言っても限度というものがあるだろう！
254 = "ちょっと待て。\\n増幅させると言っても限度というものがあるだろう！"

# めぐみん
# ですが実際、\n下着は奪われてしまったわけですし。
258 = "ですが実際、\\n下着は奪われてしまったわけですし。"

# アクア
# その話が本当なら、\n身を隠しても意味がないってことになるわね。
247 = "その話が本当なら、\\n身を隠しても意味がないってことになるわね。"

# アクア＆めぐみん＆ダクネス
# display as ３人
# …………。
# 222 = "…………。"

# カズマ
# なんだよお前ら、その何か言いたそうな目は。
264 = "なんだよお前ら、その何か言いたそうな目は。"

# ダクネス
# いや。本格的に変質者じみてきたと思ってな。
231 = "いや。本格的に変質者じみてきたと思ってな。"

# カズマ
# 俺は好きでやってるわけじゃねーよ！
294 = "俺は好きでやってるわけじゃねーよ！"

# アクア
# とにかく、これ以上\nその指輪を放置しておくわけにはいかないわ。
260 = "とにかく、これ以上\\nその指輪を放置しておくわけにはいかないわ。"

# アクア
# やっぱり切るしかないわね、腕を。
276 = "やっぱり切るしかないわね、腕を。"

# カズマ
# なんで腕なんだよ！　指だろ指！
266 = "なんで腕なんだよ！　指だろ指！"

# アクア
# あ、指ならいいんだ？　じゃあさっそく。
225 = "あ、指ならいいんだ？　じゃあさっそく。"

# カズマ
# そうじゃねーよ！\n勝手に切る方向で話を進めるな！
242 = "そうじゃねーよ！\\n勝手に切る方向で話を進めるな！"

# カズマ
# てか、うきうきしてんじゃねー！
256 = "てか、うきうきしてんじゃねー！"

# めぐみん
# 切られるのが嫌なら消し炭にしますか？\n爆裂魔法で。
295 = "切られるのが嫌なら消し炭にしますか？\\n爆裂魔法で。"

# カズマ
# そんなの指だけじゃ済まないだろうが！
251 = "そんなの指だけじゃ済まないだろうが！"

# カズマ
# ってか、話が進まないから、\n俺の指をどうこうするってことから離れろよ。
255 = "ってか、話が進まないから、\\n俺の指をどうこうするってことから離れろよ。"

# カズマ
# 本当に指を切ったりしたら、治される前に、\nその切断面をお前らに見せつけてやるからな。
303 = "本当に指を切ったりしたら、治される前に、\\nその切断面をお前らに見せつけてやるからな。"

# めぐみん
# なんて地味な嫌がらせを。
265 = "なんて地味な嫌がらせを。"

# アクア
# しょーがないわね。そこまで言うなら\n指を切るのは保留にしといてあげるわ。
240 = "しょーがないわね。そこまで言うなら\\n指を切るのは保留にしといてあげるわ。"

# カズマ（Ｍ）
# display as カズマ
# （まったく。\n　どいつもこいつも好き勝手言いやがって）
352 = "（まったく。\\n　どいつもこいつも好き勝手言いやがって）"

