# st01c_08.txt.scn

[info]
166 = "st01c_08"

[characters]
237 = "カズマ"
234 = "アクア"
230 = "めぐみん"
232 = "ゆんゆん"
236 = "ウィズ"
240 = "クリス"
235 = "アクア＆めぐみん＆ダクネス"
242 = "ダクネス"
247 = "ルナ"
239 = "カズマ（Ｍ）"

[character_subs]
313 = "３人"
314 = "？？？"
# 237 = "カズマ"

[script]
# lines: 53

# カズマ
# みんなにやってもらうことは\n今までと何も変わらないから安心してくれ。
228 = "みんなにやってもらうことは\\n今までと何も変わらないから安心してくれ。"

# カズマ
# 過激なオプションていうのは、\nポイント制で景品を出すってことさ。
308 = "過激なオプションていうのは、\\nポイント制で景品を出すってことさ。"

# アクア
# ポイント制？
246 = "ポイント制？"

# カズマ
# ああ。買い物をしてポイント溜めて、\n景品と交換してもらうってのがあるだろ？
197 = "ああ。買い物をしてポイント溜めて、\\n景品と交換してもらうってのがあるだろ？"

# カズマ
# まあウチの場合は、\nオプションを申し込むことで、\nポイントが溜まる形を考えてるんだけど。
226 = "まあウチの場合は、\\nオプションを申し込むことで、\\nポイントが溜まる形を考えてるんだけど。"

# めぐみん
# ポイントが溜まると何と交換できるんです？
245 = "ポイントが溜まると何と交換できるんです？"

# ゆんゆん
# 料理一品をサービスとか？
257 = "料理一品をサービスとか？"

# カズマ
# そんなので売り上げが変わるなら苦労しないって。
211 = "そんなので売り上げが変わるなら苦労しないって。"

# ウィズ
# ならいったいどんな。
217 = "ならいったいどんな。"

# クリス
# もったいぶらずに早く教えてよ。
231 = "もったいぶらずに早く教えてよ。"

# カズマ
# ふふ。良いだろう。
223 = "ふふ。良いだろう。"

# カズマ
# なんと１０００ポイント溜めると、\n好きなメイドとデートできる権利を！
218 = "なんと１０００ポイント溜めると、\\n好きなメイドとデートできる権利を！"

# カズマ
# そして１００００ポイント溜めると、\n好きなメイドと旅行に行ける権利をプレゼントだ！
209 = "そして１００００ポイント溜めると、\\n好きなメイドと旅行に行ける権利をプレゼントだ！"

# アクア＆めぐみん＆ダクネス
# display as ３人
# はああああ！？
221 = "はああああ！？"

# ダクネス
# 何を考えているんだ貴様は！\nデートに旅行？　そんなことを私たちに――
251 = "何を考えているんだ貴様は！\\nデートに旅行？　そんなことを私たちに――"

# カズマ
# だー、声がでかい！
214 = "だー、声がでかい！"

# ダクネス
# んご！　むぐぐ！
233 = "んご！　むぐぐ！"

# カズマ
# いいか、みんな良く聞け。
200 = "いいか、みんな良く聞け。"

# アクア
# 何よ。
250 = "何よ。"

# カズマ
# デートや旅行の権利をプレゼントするのは\n間違いないが、実際にできるかは別の話だ。
243 = "デートや旅行の権利をプレゼントするのは\\n間違いないが、実際にできるかは別の話だ。"

# めぐみん
# どういう意味です？
216 = "どういう意味です？"

# カズマ
# このメイド喫茶は、\n近々閉めようかなーって思ってるんだよ。
206 = "このメイド喫茶は、\\n近々閉めようかなーって思ってるんだよ。"

# カズマ
# だから、好きなメイドと旅行に行きたいがために\n借金してまでポイントを溜めても――
212 = "だから、好きなメイドと旅行に行きたいがために\\n借金してまでポイントを溜めても――"

# カズマ
# その権利を行使できる頃には、\n好きなメイドもいないかなって。
210 = "その権利を行使できる頃には、\\n好きなメイドもいないかなって。"

# クリス
# ええと……それって詐欺になるんじゃ？
204 = "ええと……それって詐欺になるんじゃ？"

# カズマ
# 詐欺なんて人聞きが悪いなー。\nたまたま、ためたポイントを使う頃に\n店がなくなってるだけじゃないか。
306 = "詐欺なんて人聞きが悪いなー。\\nたまたま、ためたポイントを使う頃に\\n店がなくなってるだけじゃないか。"

# アクア
# あんた、本当に外道ね。\n正直ドン引きだわ。
199 = "あんた、本当に外道ね。\\n正直ドン引きだわ。"

# カズマ
# だが法には抵触していない！\nつまりセーフ！！
213 = "だが法には抵触していない！\\nつまりセーフ！！"

# めぐみん
# この男、まったくもって悪びれてませんよ。
207 = "この男、まったくもって悪びれてませんよ。"

# ダクネス
# むしろ会心の笑みを浮かべてすらいるな。
229 = "むしろ会心の笑みを浮かべてすらいるな。"

# カズマ
# というわけで、閉店までの短い間、\nお前らは客が少しでもオプションを頼みたく\nなるように、全力でサービスしまくってくれ！
215 = "というわけで、閉店までの短い間、\\nお前らは客が少しでもオプションを頼みたく\\nなるように、全力でサービスしまくってくれ！"

# ルナ
# display as ？？？
# まさかそんなことまでするとは予想外です。
227 = "まさかそんなことまでするとは予想外です。"

# カズマ
# へ？
224 = "へ？"

# ルナ
# 話は全て聞かせていただきました。
307 = "話は全て聞かせていただきました。"

# カズマ
# な！？　いつからここに！？
219 = "な！？　いつからここに！？"

# ルナ
# いつからも何も、\nここはギルドの一部なんですから、\n私がいるのは当然じゃないですか。
201 = "いつからも何も、\\nここはギルドの一部なんですから、\\n私がいるのは当然じゃないですか。"

# カズマ
# 言われてみれば！
305 = "言われてみれば！"

# ルナ
# このところ、こちらのお店に関するクレームが\n増えていて、少しお話を伺おうと思っていたの\nですが、こんな話を聞いてしまっては……。
205 = "このところ、こちらのお店に関するクレームが\\n増えていて、少しお話を伺おうと思っていたの\\nですが、こんな話を聞いてしまっては……。"

# カズマ
# あの、お姉さん、今のは全部冗談で。
198 = "あの、お姉さん、今のは全部冗談で。"

# ルナ
# サトウカズマさん。
241 = "サトウカズマさん。"

# カズマ
# は、はい！
220 = "は、はい！"

# ルナ
# 今すぐにお店を閉じることを誓うか、\nそれとも今の企みを白日の下にさらされるか\n選んでください。
249 = "今すぐにお店を閉じることを誓うか、\\nそれとも今の企みを白日の下にさらされるか\\n選んでください。"

# カズマ
# え、ええと……もう少し続けるという選択肢は。
203 = "え、ええと……もう少し続けるという選択肢は。"

# ルナ
# 選んでください。
309 = "選んでください。"

# カズマ（Ｍ）
# display as カズマ
# （せっかく金を貯められるチャンスなのに！）
311 = "（せっかく金を貯められるチャンスなのに！）"

# カズマ（Ｍ）
# display as カズマ
# （でも、街のみんなの信用を無くしちまったら\n　ここに住めなくなるし……）
312 = "（でも、街のみんなの信用を無くしちまったら\\n　ここに住めなくなるし……）"

# めぐみん
# カズマ、あきらめが肝心ですよ。
238 = "カズマ、あきらめが肝心ですよ。"

# カズマ
# う、うぅ、わかりました。\nおとなしく店を閉めます。
202 = "う、うぅ、わかりました。\\nおとなしく店を閉めます。"

# ルナ
# はい、英断だと思いますよ。
222 = "はい、英断だと思いますよ。"

# ダクネス
# まあ、何事も欲をかきすぎるのは罪ということだな。
225 = "まあ、何事も欲をかきすぎるのは罪ということだな。"

# めぐみん
# 反面教師にしないといけませんね。
252 = "反面教師にしないといけませんね。"

# アクア
# さて、ささっと撤収しましょうか。\nカズマ、事後処理はよろしく。
208 = "さて、ささっと撤収しましょうか。\\nカズマ、事後処理はよろしく。"

# カズマ（Ｍ）
# display as カズマ
# （く、くそぉ～……）
310 = "（く、くそぉ～……）"

