# st01c_05.txt.scn

[info]
136 = "st01c_05"

[characters]
192 = "カズマ"
190 = "アクア"
193 = "カズマ（Ｍ）"
188 = "ゆんゆん"
191 = "ウィズ"
194 = "クリス"
195 = "ダクネス"
185 = "めぐみん"

[character_subs]
# 192 = "カズマ"

[script]
# lines: 37

# カズマ
# よーし、みんな集まったな。
189 = "よーし、みんな集まったな。"

# カズマ
# じゃあ２日目の開店前に、\n簡単なミーティングをしておこうと思う。
167 = "じゃあ２日目の開店前に、\\n簡単なミーティングをしておこうと思う。"

# カズマ
# まず、昨日の結果は大成功だったと言っていい。\n売り上げもなかなかのものだった。
184 = "まず、昨日の結果は大成功だったと言っていい。\\n売り上げもなかなかのものだった。"

# アクア
# ほんと、あんなに儲かるなんて思ってなかったわ。
181 = "ほんと、あんなに儲かるなんて思ってなかったわ。"

# アクア
# もしかして、億万長者になれちゃうんじゃない？\nこのままの勢いでフランチャイズな展開とか\nしちゃってさ。
186 = "もしかして、億万長者になれちゃうんじゃない？\\nこのままの勢いでフランチャイズな展開とか\\nしちゃってさ。"

# カズマ（Ｍ）
# display as カズマ
# （この世界で\n　フランチャイズとか理解されるのか？）
231 = "（この世界で\\n　フランチャイズとか理解されるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （確かに、店が軌道に乗ったら、\n　そういう展開を考えてみるのも……）
236 = "（確かに、店が軌道に乗ったら、\\n　そういう展開を考えてみるのも……）"

# カズマ（Ｍ）
# display as カズマ
# （いや、今はそんなこと考えてる余裕ないだろ！）
230 = "（いや、今はそんなこと考えてる余裕ないだろ！）"

# カズマ
# まあ、確かに儲けは出た。\n前例のない店と考えたら十分すぎるほどにな。
183 = "まあ、確かに儲けは出た。\\n前例のない店と考えたら十分すぎるほどにな。"

# カズマ
# でも俺たちの目標はなんだ、ゆんゆん？
177 = "でも俺たちの目標はなんだ、ゆんゆん？"

# ゆんゆん
# え？　カズマさんの指輪を外すための資金を\n稼ぐこと、ですよね？
164 = "え？　カズマさんの指輪を外すための資金を\\n稼ぐこと、ですよね？"

# カズマ
# そう、その通り。
168 = "そう、その通り。"

# カズマ
# しかしだっ！　今後昨日と同じくらいの売り上げを\n続けたとして、目標金額を達成するのに半年近く\nかかる計算になる！
166 = "しかしだっ！　今後昨日と同じくらいの売り上げを\\n続けたとして、目標金額を達成するのに半年近く\\nかかる計算になる！"

# ウィズ
# 半年ですか。
197 = "半年ですか。"

# クリス
# それはさすがに付き合いきれないっていうか。
172 = "それはさすがに付き合いきれないっていうか。"

# ダクネス
# だったらクエストで\n一攫千金を狙った方がマシだろう。
174 = "だったらクエストで\\n一攫千金を狙った方がマシだろう。"

# めぐみん
# そもそも半年もかかるなら、\nその間の満月の日をどうするつもりなんです？
171 = "そもそも半年もかかるなら、\\nその間の満月の日をどうするつもりなんです？"

# カズマ
# そういう問題もあるから、もっと短い期間で\nどうにかならないかと考えてみたわけだ。
169 = "そういう問題もあるから、もっと短い期間で\\nどうにかならないかと考えてみたわけだ。"

# アクア
# もしかして！\nさらにお金を稼げちゃういい案があるの！
187 = "もしかして！\\nさらにお金を稼げちゃういい案があるの！"

# カズマ
# ああ、まずは客単価を上げる作戦を取ろうと\n思ってる。
162 = "ああ、まずは客単価を上げる作戦を取ろうと\\n思ってる。"

# ダクネス
# 商品の値段を上げるということか？
200 = "商品の値段を上げるということか？"

# カズマ
# いや、それくらいじゃ売り上げなんて\nたいして変わらないし、高くて注文を渋られたら\n本末転倒だ。
163 = "いや、それくらいじゃ売り上げなんて\\nたいして変わらないし、高くて注文を渋られたら\\n本末転倒だ。"

# クリス
# だったらどうするのさ？
173 = "だったらどうするのさ？"

# カズマ
# そこら辺はメイド喫茶ならではの\nやり方ってものがあるんだよ。
170 = "そこら辺はメイド喫茶ならではの\\nやり方ってものがあるんだよ。"

# ウィズ
# ですが、昨日開店したばかりで、\nいきなり料金を変えるというのは……。
176 = "ですが、昨日開店したばかりで、\\nいきなり料金を変えるというのは……。"

# ゆんゆん
# %fsyogen;それに、ここは駆け出しの冒険者たちが集まってる\n街なんですよ？
20 = "%fsyogen;それに、ここは駆け出しの冒険者たちが集まってる\\n街なんですよ？"

# カズマ（Ｍ）
# display as カズマ
# （どうした、ゆんゆん。\n　ここは攻め時なんだぞ！）
232 = "（どうした、ゆんゆん。\\n　ここは攻め時なんだぞ！）"

# カズマ（Ｍ）
# display as カズマ
# （どうもお金を集めるってことに\n　集中していないように感じるな……）
233 = "（どうもお金を集めるってことに\\n　集中していないように感じるな……）"

# カズマ（Ｍ）
# display as カズマ
# （怪しいな……。\n　ここは証言としてゲットしておくか……）
235 = "（怪しいな……。\\n　ここは証言としてゲットしておくか……）"

# めぐみん
# 娯楽にお金を使える人なんて、一握りしかいない\nでしょうね。
201 = "娯楽にお金を使える人なんて、一握りしかいない\\nでしょうね。"

# カズマ
# お前たちは男の欲望を侮りすぎだ！
165 = "お前たちは男の欲望を侮りすぎだ！"

# ゆんゆん
# べ、別に侮ったりは。
180 = "べ、別に侮ったりは。"

# アクア
# なんかよくわかんないんだけどさ、\nカズマの言う通りにすれば、\n億万長者も夢じゃないってことなのよね？
179 = "なんかよくわかんないんだけどさ、\\nカズマの言う通りにすれば、\\n億万長者も夢じゃないってことなのよね？"

# カズマ
# まあ、そういうことだ。
182 = "まあ、そういうことだ。"

# アクア
# だったら良いわよ、それで。\nカズマに全部任せるわ。
175 = "だったら良いわよ、それで。\\nカズマに全部任せるわ。"

# カズマ（Ｍ）
# display as カズマ
# （アクアが素直に乗ってくると逆に不安になるが、\n　細かく説明して反対されると面倒だし、\n　ここは勢いで押し切ってしまおう）
234 = "（アクアが素直に乗ってくると逆に不安になるが、\\n　細かく説明して反対されると面倒だし、\\n　ここは勢いで押し切ってしまおう）"

# カズマ
# とにかくそういうことだから、みんな頼んだぞ！
178 = "とにかくそういうことだから、みんな頼んだぞ！"

