# st01c_02.txt.scn

[info]
177 = "st01c_02"

[characters]
294 = "キース"
285 = "アクア"
289 = "アクア＆めぐみん＆ダクネス"
291 = "ウィズ＆ゆんゆん＆クリス"
298 = "ダスト"
293 = "カズマ（Ｍ）"
292 = "カズマ"
297 = "ダクネス"
282 = "めぐみん"
284 = "ゆんゆん"
316 = "盗賊風の男冒険者"
380 = "魔術師風の男冒険者"
295 = "クリス"
306 = "商人風の男"
290 = "ウィズ"
312 = "戦士風の男冒険者"
375 = "聖職者風の男冒険者"

[character_subs]
421 = "３人"
# 292 = "カズマ"
315 = "盗賊冒険者"
379 = "魔術師冒険者"
311 = "戦士冒険者"
374 = "聖職冒険者"

[script]
# lines: 121

# キース
# おーす、カズマ来たぞー！
239 = "おーす、カズマ来たぞー！"

# アクア
# せーの。
255 = "せーの。"

# アクア＆めぐみん＆ダクネス
# display as ３人
# お帰りなさいませ。
241 = "お帰りなさいませ。"

# ウィズ＆ゆんゆん＆クリス
# display as ３人
# ご主人様。
247 = "ご主人様。"

# ダスト
# なっ！？　こ、これは……。
268 = "なっ！？　こ、これは……。"

# キース
# い、いい……。
231 = "い、いい……。"

# カズマ（Ｍ）
# display as カズマ
# （メイドの一礼による出迎えを予想したか？\n　してなかっただろ？）
410 = "（メイドの一礼による出迎えを予想したか？\\n　してなかっただろ？）"

# カズマ（Ｍ）
# display as カズマ
# （ふははは、客のリアクションも予想通りだ！\n　しかしこれだけがメイド喫茶にあらず！）
403 = "（ふははは、客のリアクションも予想通りだ！\\n　しかしこれだけがメイド喫茶にあらず！）"

# カズマ
# お前ら、やれ。
240 = "お前ら、やれ。"

# アクア
# 任されたわ。
303 = "任されたわ。"

# アクア
# ご主人様。
# 247 = "ご主人様。"

# キース
# え、俺！？
237 = "え、俺！？"

# アクア
# どうぞこちらへ。
266 = "どうぞこちらへ。"

# ダスト
# あ、はい！
224 = "あ、はい！"

# アクア
# お疲れのようですね。\n今日はゆっくりと休んでいってください。
242 = "お疲れのようですね。\\n今日はゆっくりと休んでいってください。"

# キース
# はい、喜んで！
272 = "はい、喜んで！"

# カズマ（Ｍ）
# display as カズマ
# （どうよ、このアクアは！）
401 = "（どうよ、このアクアは！）"

# カズマ（Ｍ）
# display as カズマ
# （泥酔して宴会芸を披露している姿しか知らない\n　お前たちには、破壊力が抜群だろう！）
416 = "（泥酔して宴会芸を披露している姿しか知らない\\n　お前たちには、破壊力が抜群だろう！）"

# ダクネス
# ご主人様、おしぼりをどうぞ。
245 = "ご主人様、おしぼりをどうぞ。"

# めぐみん
# ご注文はお決まりですか、ご主人様。
249 = "ご注文はお決まりですか、ご主人様。"

# ゆんゆん
# ご主人様、ご注文の品をお持ちしました。
246 = "ご主人様、ご注文の品をお持ちしました。"

# カズマ（Ｍ）
# display as カズマ
# （みんな、度肝を抜かれたって顔をしてるな！）
405 = "（みんな、度肝を抜かれたって顔をしてるな！）"

# カズマ（Ｍ）
# display as カズマ
# （それはそうだろう。\n　お前たちが話をしていた内容は\n　俺の耳にも届いていたからな）
395 = "（それはそうだろう。\\n　お前たちが話をしていた内容は\\n　俺の耳にも届いていたからな）"

# カズマ（Ｍ）
# display as カズマ
# （『どうせ、ちょっと変わった喫茶店\n　なんでしょー』）
381 = "（『どうせ、ちょっと変わった喫茶店\\n　なんでしょー』）"

# カズマ（Ｍ）
# display as カズマ
# （そう思いたければ思っていればいいと\n　俺は余計な説明をしなかった）
392 = "（そう思いたければ思っていればいいと\\n　俺は余計な説明をしなかった）"

# カズマ（Ｍ）
# display as カズマ
# （それはなぜか！）
396 = "（それはなぜか！）"

# カズマ（Ｍ）
# display as カズマ
# （全てはこの瞬間の驚きの力を最大限にまで\n　引き出すためだ！）
412 = "（全てはこの瞬間の驚きの力を最大限にまで\\n　引き出すためだ！）"

# カズマ（Ｍ）
# display as カズマ
# （そしてたたみかけるように\n　さらなる奉仕接客で客共を虜にする！）
394 = "（そしてたたみかけるように\\n　さらなる奉仕接客で客共を虜にする！）"

# めぐみん
# な、なんだとー！
267 = "な、なんだとー！"

# カズマ（Ｍ）
# display as カズマ
# （って、いきなりトラブルか！？）
399 = "（って、いきなりトラブルか！？）"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# いや、だって普段を知ってると\n無理してる感が……くくっ……。
233 = "いや、だって普段を知ってると\\n無理してる感が……くくっ……。"

# めぐみん
# だったら他のメイドに頼めばいいじゃないですか！
263 = "だったら他のメイドに頼めばいいじゃないですか！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# え……。
234 = "え……。"

# めぐみん
# では、私は他のご主人様がお待ちなので失礼します！
265 = "では、私は他のご主人様がお待ちなので失礼します！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# ままま、待った！
281 = "ままま、待った！"

# めぐみん
# なんです？
269 = "なんです？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# い……いい。
230 = "い……いい。"

# めぐみん
# は？
277 = "は？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# メイドさんに叱られるって、\nなんか、来る……。
301 = "メイドさんに叱られるって、\\nなんか、来る……。"

# めぐみん
# は？
# 277 = "は？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# 頼む、もっと叱ってくれ！
377 = "頼む、もっと叱ってくれ！"

# めぐみん
# はーーーー！？\n何おかしなことを言ってるんですあなたは！？
276 = "はーーーー！？\\n何おかしなことを言ってるんですあなたは！？"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# もっと口汚く！
283 = "もっと口汚く！"

# カズマ（Ｍ）
# display as カズマ
# （何をやってるんだ、あいつらは……）
411 = "（何をやってるんだ、あいつらは……）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、結果オーライだ。\n　良しとしよう）
404 = "（まあ、結果オーライだ。\\n　良しとしよう）"

# ゆんゆん
# え、ええとええと。
236 = "え、ええとええと。"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんが挙動不審だ……）
406 = "（ゆんゆんが挙動不審だ……）"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# あの……すみません。
228 = "あの……すみません。"

# ゆんゆん
# は、はひ！？
270 = "は、はひ！？"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# 注文が来ていないんですが……。
314 = "注文が来ていないんですが……。"

# ゆんゆん
# え、え、ちゅ、注文？　注文！？\nすすす、すみません、忘れてました！
235 = "え、え、ちゅ、注文？　注文！？\\nすすす、すみません、忘れてました！"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# いえ、そんな……謝らなくても……。
232 = "いえ、そんな……謝らなくても……。"

# ゆんゆん
# すす、すぐにお持ちしますのでお待ちくださ――
254 = "すす、すぐにお持ちしますのでお待ちくださ――"

# ゆんゆん
# ひゃあ！？
278 = "ひゃあ！？"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# だ、大丈夫ですか？
261 = "だ、大丈夫ですか？"

# ゆんゆん
# ちょっとつまずいちゃっただけなので……。
264 = "ちょっとつまずいちゃっただけなので……。"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# 怪我は無いです？
309 = "怪我は無いです？"

# ゆんゆん
# ありがとうございます、ご主人様。
229 = "ありがとうございます、ご主人様。"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんの甲斐甲斐しさと、\n　背伸びしている感じが客に受けているか）
407 = "（ゆんゆんの甲斐甲斐しさと、\\n　背伸びしている感じが客に受けているか）"

# カズマ（Ｍ）
# display as カズマ
# （さらに世話好きは、ボッチオーラを出しまくる\n　ゆんゆんを放ってはおけないんだろう）
390 = "（さらに世話好きは、ボッチオーラを出しまくる\\n　ゆんゆんを放ってはおけないんだろう）"

# カズマ（Ｍ）
# display as カズマ
# （これはこれでいい武器になるかもしれないな）
388 = "（これはこれでいい武器になるかもしれないな）"

# ダクネス
# …………。
220 = "…………。"

# カズマ
# …………。
# 220 = "…………。"

# ダクネス
# …………。
# 220 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （あいつは店の真ん中に突っ立って\n　何をやってるんだ）
382 = "（あいつは店の真ん中に突っ立って\\n　何をやってるんだ）"

# ダクネス
# 感じる、感じるぞ。\nこの身を舐め回すような視線を。
310 = "感じる、感じるぞ。\\nこの身を舐め回すような視線を。"

# ダクネス
# まったく、男という生き物は本当に\nんん……なんといやらしい……。
280 = "まったく、男という生き物は本当に\\nんん……なんといやらしい……。"

# ダクネス
# 見るなと言ったところでどうせ無理なのだろうな。\nこのような服を着ているのだから仕方ない。
376 = "見るなと言ったところでどうせ無理なのだろうな。\\nこのような服を着ているのだから仕方ない。"

# ダクネス
# だが、この姿で給仕をするのが役目な以上、\nこの恥辱に耐えねば……ああ……。
262 = "だが、この姿で給仕をするのが役目な以上、\\nこの恥辱に耐えねば……ああ……。"

# カズマ（Ｍ）
# display as カズマ
# （あのダクネスの妄想癖はどうにかならないのか？）
383 = "（あのダクネスの妄想癖はどうにかならないのか？）"

# カズマ（Ｍ）
# display as カズマ
# （でもまあ、そんなハァハァするダクネスを見て\n　周りの男達もハァハァしてるようだし、\n　しばらくは様子を見ることにしよう）
400 = "（でもまあ、そんなハァハァするダクネスを見て\\n　周りの男達もハァハァしてるようだし、\\n　しばらくは様子を見ることにしよう）"

# クリス
# ご主人様、おしぼりをどうぞ。
# 245 = "ご主人様、おしぼりをどうぞ。"

# 商人風の男
# あ、ありがとうございます。
222 = "あ、ありがとうございます。"

# クリス
# ご注文はお決まりですか？
250 = "ご注文はお決まりですか？"

# 商人風の男
# はい。これをお願いします。
274 = "はい。これをお願いします。"

# クリス
# かしこまりました。では少々お待ちください。
243 = "かしこまりました。では少々お待ちください。"

# クリス
# それから、ご主人様はご主人様なんですから、\nもっと気を楽になさってくださっていいんですよ。
258 = "それから、ご主人様はご主人様なんですから、\\nもっと気を楽になさってくださっていいんですよ。"

# カズマ（Ｍ）
# display as カズマ
# （いいぞ、クリス。\n　緊張してる客にそういう心遣いは大切だ）
384 = "（いいぞ、クリス。\\n　緊張してる客にそういう心遣いは大切だ）"

# カズマ（Ｍ）
# display as カズマ
# （客達の表情から察するに\n　すっかりメイドたちの虜になっているようだな）
414 = "（客達の表情から察するに\\n　すっかりメイドたちの虜になっているようだな）"

# カズマ（Ｍ）
# display as カズマ
# （そしてあいつらが与えたメイドインパクトは、\n　男連中の理性を根こそぎ持って行く――）
393 = "（そしてあいつらが与えたメイドインパクトは、\\n　男連中の理性を根こそぎ持って行く――）"

# ウィズ
# ご注文は以上でよろしいですか、ご主人様？
251 = "ご注文は以上でよろしいですか、ご主人様？"

# 戦士風の男冒険者
# display as 戦士冒険者
# あ、あの！\nウィズ魔道具店の店主さんですよね！
221 = "あ、あの！\\nウィズ魔道具店の店主さんですよね！"

# ウィズ
# はい。そうですが？
275 = "はい。そうですが？"

# 戦士風の男冒険者
# display as 戦士冒険者
# あ、やっぱり！\n普段と違う服装だから他人の空似かと思いました！
225 = "あ、やっぱり！\\n普段と違う服装だから他人の空似かと思いました！"

# 戦士風の男冒険者
# display as 戦士冒険者
# そそそ、そういうのもお似合いですね！
257 = "そそそ、そういうのもお似合いですね！"

# ウィズ
# お、恐れ入ります。
238 = "お、恐れ入ります。"

# カズマ（Ｍ）
# display as カズマ
# （照れくさそうにはにかむウィズは\n　相変わらずの破壊力だな）
417 = "（照れくさそうにはにかむウィズは\\n　相変わらずの破壊力だな）"

# カズマ（Ｍ）
# display as カズマ
# （客もすっかりやられてるようだ。\n　呆けた顔でウィズを見上げてる）
413 = "（客もすっかりやられてるようだ。\\n　呆けた顔でウィズを見上げてる）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズはこの中で知名度が抜群に高い）
408 = "（ウィズはこの中で知名度が抜群に高い）"

# カズマ（Ｍ）
# display as カズマ
# （貧乏店主さんと呼ばれているのは、\n　揶揄ではなく親しみを込めてだろう）
419 = "（貧乏店主さんと呼ばれているのは、\\n　揶揄ではなく親しみを込めてだろう）"

# カズマ（Ｍ）
# display as カズマ
# （さらにウィズは凄腕アークウィザードという\n　過去を持っている）
389 = "（さらにウィズは凄腕アークウィザードという\\n　過去を持っている）"

# カズマ（Ｍ）
# display as カズマ
# （駆け出し冒険者が集まるこの街では\n　まさに高嶺の花の存在というわけだ！）
420 = "（駆け出し冒険者が集まるこの街では\\n　まさに高嶺の花の存在というわけだ！）"

# カズマ（Ｍ）
# display as カズマ
# （そんな高嶺の花のウィズが今は、\n　ミニスカ姿で寄り添うように立っている）
398 = "（そんな高嶺の花のウィズが今は、\\n　ミニスカ姿で寄り添うように立っている）"

# カズマ（Ｍ）
# display as カズマ
# （そんな美味しい状況を簡単に手放していいのか？\n　いや手放せるのか？）
397 = "（そんな美味しい状況を簡単に手放していいのか？\\n　いや手放せるのか？）"

# ウィズ
# すぐにお待ちしますので、少々お待ちください、\nご主人様。
253 = "すぐにお待ちしますので、少々お待ちください、\\nご主人様。"

# 戦士風の男冒険者
# display as 戦士冒険者
# あっ、ままま、待ってください！\nええと、まだ注文しますんで、もう少しここに！
227 = "あっ、ままま、待ってください！\\nええと、まだ注文しますんで、もう少しここに！"

# ウィズ
# はい、お待ちしています。
271 = "はい、お待ちしています。"

# カズマ（Ｍ）
# display as カズマ
# （ウィズを側に置いておきたいと思う客は、\n　さらなる注文をせざるを得なくなる！）
409 = "（ウィズを側に置いておきたいと思う客は、\\n　さらなる注文をせざるを得なくなる！）"

# カズマ（Ｍ）
# display as カズマ
# （くくく、計画通り）
387 = "（くくく、計画通り）"

# カズマ（Ｍ）
# display as カズマ
# （さらに！）
391 = "（さらに！）"

# カズマ
# アクア。
286 = "アクア。"

# アクア
# 承知。
313 = "承知。"

# アクア
# ご主人様、\nご注文はお決まりになられましたか？
244 = "ご主人様、\\nご注文はお決まりになられましたか？"

# 聖職者風の男冒険者
# display as 聖職冒険者
# あ、はい。これとこれをお願いします。
223 = "あ、はい。これとこれをお願いします。"

# アクア
# シュワシュワと\n蛙の唐揚げですね？
296 = "シュワシュワと\\n蛙の唐揚げですね？"

# アクア
# 食後にケーキはいかがですか？\n私の手作りなんですよ？
378 = "食後にケーキはいかがですか？\\n私の手作りなんですよ？"

# 聖職者風の男冒険者
# display as 聖職冒険者
# じゃ、じゃあ、それもお願いしちゃおうかな。
252 = "じゃ、じゃあ、それもお願いしちゃおうかな。"

# カズマ（Ｍ）
# display as カズマ
# （本当は俺が作ったんだけどな！）
415 = "（本当は俺が作ったんだけどな！）"

# アクア
# あ、申し訳ございません。\n甘い物にシュワシュワはあいませんよね。
226 = "あ、申し訳ございません。\\n甘い物にシュワシュワはあいませんよね。"

# アクア
# アクアは本当に不出来なメイドです。\nどうぞ強くお叱りください、ご主人様。
288 = "アクアは本当に不出来なメイドです。\\nどうぞ強くお叱りください、ご主人様。"

# カズマ（Ｍ）
# display as カズマ
# （はい、アクアさん！　そこで上目遣い！）
402 = "（はい、アクアさん！　そこで上目遣い！）"

# 聖職者風の男冒険者
# display as 聖職冒険者
# そんな叱るだなんて！\nええと、ケーキと一緒にこの苦くて黒い飲み物も\nください！
260 = "そんな叱るだなんて！\\nええと、ケーキと一緒にこの苦くて黒い飲み物も\\nください！"

# アクア
# ご主人様はお優しいんですね。
248 = "ご主人様はお優しいんですね。"

# カズマ（Ｍ）
# display as カズマ
# （いいね！　その小首をかしげての微笑み！\n　あざとくていいよ！）
386 = "（いいね！　その小首をかしげての微笑み！\\n　あざとくていいよ！）"

# 聖職者風の男冒険者
# display as 聖職冒険者
# そ、そんなことは。
256 = "そ、そんなことは。"

# アクア
# アクアはご主人様のメイドになれて幸せです。\nあっ、そうだ、今日は新鮮なお魚も\nご用意できますよ？
287 = "アクアはご主人様のメイドになれて幸せです。\\nあっ、そうだ、今日は新鮮なお魚も\\nご用意できますよ？"

# 聖職者風の男冒険者
# display as 聖職冒険者
# それもください！
259 = "それもください！"

# アクア
# はい、承知しました。\nすぐにお持ちしますので、少々お待ちください。
273 = "はい、承知しました。\\nすぐにお持ちしますので、少々お待ちください。"

# カズマ（Ｍ）
# display as カズマ
# （いいぞアクア、素晴らしい注文の誘導だ！）
385 = "（いいぞアクア、素晴らしい注文の誘導だ！）"

# アクア
# ふっ……。
279 = "ふっ……。"

# カズマ（Ｍ）
# display as カズマ
# （良くやったが、その邪悪な笑みはやめろ……）
418 = "（良くやったが、その邪悪な笑みはやめろ……）"

