# st01b_01.txt.scn

[info]
133 = "st01b_01"

[characters]
171 = "カズマ"
172 = "カズマ（Ｍ）"
170 = "アクア"

[character_subs]
# 171 = "カズマ"

[script]
# lines: 31

# カズマ
# ……っ……んん……。
163 = "……っ……んん……。"

# カズマ（Ｍ）
# display as カズマ
# （もう朝か……）
201 = "（もう朝か……）"

# カズマ（Ｍ）
# display as カズマ
# （良く寝たな。\n　こんなにぐっすり寝たのは久しぶりな気がするわ）
208 = "（良く寝たな。\\n　こんなにぐっすり寝たのは久しぶりな気がするわ）"

# カズマ
# ？　なんだこれ？
209 = "？　なんだこれ？"

# カズマ
# ！？　これってまさか……はあ？　パンツ！？
186 = "！？　これってまさか……はあ？　パンツ！？"

# カズマ（Ｍ）
# display as カズマ
# （くそっ、またこの指輪かっ！）
190 = "（くそっ、またこの指輪かっ！）"

# カズマ（Ｍ）
# display as カズマ
# （あれ？　でも昨日の夜は、\n　俺の他に誰も屋敷にはいなかったはず）
187 = "（あれ？　でも昨日の夜は、\\n　俺の他に誰も屋敷にはいなかったはず）"

# カズマ（Ｍ）
# display as カズマ
# （ははーん。そうか。\n　あいつらあんなこと言ってたくせに、\n　俺のことを心配して帰って来てくれたんだな）
197 = "（ははーん。そうか。\\n　あいつらあんなこと言ってたくせに、\\n　俺のことを心配して帰って来てくれたんだな）"

# カズマ（Ｍ）
# display as カズマ
# （まったく。それならそうと、\n　寝る前に声をかけてくれればよかったのに）
200 = "（まったく。それならそうと、\\n　寝る前に声をかけてくれればよかったのに）"

# カズマ（Ｍ）
# display as カズマ
# （もしかして俺ってけっこう人望あったりするのか）
203 = "（もしかして俺ってけっこう人望あったりするのか）"

# カズマ
# おっはよー！
166 = "おっはよー！"

# カズマ（Ｍ）
# display as カズマ
# （なんだよ。まだ誰も起きて来てないのか）
196 = "（なんだよ。まだ誰も起きて来てないのか）"

# カズマ（Ｍ）
# display as カズマ
# （いや、もしかしたらダクネス辺りが、\n　庭で朝の訓練なんかをしてるかもしれない）
188 = "（いや、もしかしたらダクネス辺りが、\\n　庭で朝の訓練なんかをしてるかもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、いないか）
189 = "（うーん、いないか）"

# カズマ（Ｍ）
# display as カズマ
# （だったら……）
192 = "（だったら……）"

# カズマ（Ｍ）
# display as カズマ
# （朝風呂に入ってるやつもいない、と）
207 = "（朝風呂に入ってるやつもいない、と）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、いたらボコボコにされてた\n　だろうけど……）
198 = "（まあ、いたらボコボコにされてた\\n　だろうけど……）"

# カズマ
# おかしい。誰も起きて来ない。
165 = "おかしい。誰も起きて来ない。"

# カズマ
# というか、人のいる気配がまるでしない。
167 = "というか、人のいる気配がまるでしない。"

# カズマ（Ｍ）
# display as カズマ
# （寝てるにしても、寝息とか寝返りの音とか、\n　何かしら聞こえて来そうなものなのに）
206 = "（寝てるにしても、寝息とか寝返りの音とか、\\n　何かしら聞こえて来そうなものなのに）"

# カズマ（Ｍ）
# display as カズマ
# （もしかして、実は誰も帰って来てないとか？）
202 = "（もしかして、実は誰も帰って来てないとか？）"

# カズマ（Ｍ）
# display as カズマ
# （だったらこのパンツはいったい……）
193 = "（だったらこのパンツはいったい……）"

# カズマ（Ｍ）
# display as カズマ
# （まさか、タンスの中のパンツを\n　盗ったのか俺は！？）
199 = "（まさか、タンスの中のパンツを\\n　盗ったのか俺は！？）"

# カズマ（Ｍ）
# display as カズマ
# （そこまでしてパンツが欲しいのか、この指輪は。\n　勘弁してくれよ……）
191 = "（そこまでしてパンツが欲しいのか、この指輪は。\\n　勘弁してくれよ……）"

# カズマ（Ｍ）
# display as カズマ
# （とりあえず、みんなが帰って来る前に、\n　パンツを元に戻さないと）
195 = "（とりあえず、みんなが帰って来る前に、\\n　パンツを元に戻さないと）"

# カズマ（Ｍ）
# display as カズマ
# （わざわざタンスの中から盗ったなんてバレたら、\n　あいつらに何言われるかわかったもんじゃないし）
204 = "（わざわざタンスの中から盗ったなんてバレたら、\\n　あいつらに何言われるかわかったもんじゃないし）"

# カズマ（Ｍ）
# display as カズマ
# （とはいえ、このパンツは誰のパンツなんだ？\n　それがわからないことには戻しようがないぞ）
194 = "（とはいえ、このパンツは誰のパンツなんだ？\\n　それがわからないことには戻しようがないぞ）"

# カズマ（Ｍ）
# display as カズマ
# （何か手がかりは……名前なんて書いてないし）
205 = "（何か手がかりは……名前なんて書いてないし）"

# カズマ
# な、なんだ？
168 = "な、なんだ？"

# アクア
# あー！　やっぱりカズマだったのね！
164 = "あー！　やっぱりカズマだったのね！"

# カズマ
# へ？
169 = "へ？"

