# st01a_09.txt.scn

[info]
84 = "st01a_09"

[characters]
103 = "カズマ（Ｍ）"

[character_subs]
102 = "カズマ"

[script]
# lines: 6

# カズマ（Ｍ）
# display as カズマ
# （まったく。あの駄女神は、\n　いつもほんとロクなことしねーんだから）
111 = "（まったく。あの駄女神は、\\n　いつもほんとロクなことしねーんだから）"

# カズマ（Ｍ）
# display as カズマ
# （おかげでせっかくのお楽しみが……はぁ）
107 = "（おかげでせっかくのお楽しみが……はぁ）"

# カズマ（Ｍ）
# display as カズマ
# （それもこれも、全部この指輪が！）
109 = "（それもこれも、全部この指輪が！）"

# カズマ（Ｍ）
# display as カズマ
# （くそっ……外れるわけねーよな）
108 = "（くそっ……外れるわけねーよな）"

# カズマ（Ｍ）
# display as カズマ
# （もういいや。今日は寝て、\n　明日から真面目に金策を考えよう）
112 = "（もういいや。今日は寝て、\\n　明日から真面目に金策を考えよう）"

# カズマ（Ｍ）
# display as カズマ
# （はぁ……）
110 = "（はぁ……）"

