# st01b_08.txt.scn

[info]
118 = "st01b_08"

[characters]
152 = "カズマ"
151 = "アクア"
154 = "ダクネス"
149 = "めぐみん"
153 = "カズマ（Ｍ）"

[character_subs]
# 152 = "カズマ"

[script]
# lines: 25

# カズマ
# 店員が３人いれば\nとりあえず店を開けるだろうけど、\nもう少し人手が欲しいところだな。
161 = "店員が３人いれば\\nとりあえず店を開けるだろうけど、\\nもう少し人手が欲しいところだな。"

# アクア
# 私がいたら、すぐにお店がてんやわんやの\n大騒ぎになっちゃうもんね！
187 = "私がいたら、すぐにお店がてんやわんやの\\n大騒ぎになっちゃうもんね！"

# カズマ
# ああ、そうだな。
136 = "ああ、そうだな。"

# アクア
# ちょっと、返事がてきとー！
144 = "ちょっと、返事がてきとー！"

# カズマ
# 確かに忙しくなったときの対処のためにも\n人員は必要なんだけど、それよりも重要なのは\n客のニーズに応えるってことなんだよ。
186 = "確かに忙しくなったときの対処のためにも\\n人員は必要なんだけど、それよりも重要なのは\\n客のニーズに応えるってことなんだよ。"

# ダクネス
# どういう意味だ？
145 = "どういう意味だ？"

# カズマ
# お前たちは客がメイド喫茶に何を求めて来ると\n考えてる。
140 = "お前たちは客がメイド喫茶に何を求めて来ると\\n考えてる。"

# めぐみん
# 喫茶店なのですから、食事の味なのでは？
157 = "喫茶店なのですから、食事の味なのでは？"

# カズマ
# 外れてはいないが、正解でもない。
158 = "外れてはいないが、正解でもない。"

# カズマ
# 奴らが何に金を落としているのか、\nそれは好きなメイドと過ごす時間にだ！
159 = "奴らが何に金を落としているのか、\\nそれは好きなメイドと過ごす時間にだ！"

# ダクネス
# なるほど、客が求めるメイドを用意しないと\nスタート地点にも立てないというわけか。
147 = "なるほど、客が求めるメイドを用意しないと\\nスタート地点にも立てないというわけか。"

# カズマ
# そのためにも、ゆんゆん、クリス、そしてウィズを\nこの計画に引きずり込まなくてはいけない！
143 = "そのためにも、ゆんゆん、クリス、そしてウィズを\\nこの計画に引きずり込まなくてはいけない！"

# めぐみん
# 引きずり込むって、\nもう少し言葉を選んでくださいよ。
162 = "引きずり込むって、\\nもう少し言葉を選んでくださいよ。"

# カズマ
# じゃあ、さっそくみんなに声をかけるとして、\nめぐみん、ゆんゆんってどこにいるんだ？
141 = "じゃあ、さっそくみんなに声をかけるとして、\\nめぐみん、ゆんゆんってどこにいるんだ？"

# めぐみん
# 特に用事がなければ、またウィズの店にでも\n顔を出していそうですけど。
165 = "特に用事がなければ、またウィズの店にでも\\n顔を出していそうですけど。"

# めぐみん
# あ、行くなら私も付き合いますよ。\nゆんゆんを説得するなら\n私がいた方が話が早いと思いますし。
135 = "あ、行くなら私も付き合いますよ。\\nゆんゆんを説得するなら\\n私がいた方が話が早いと思いますし。"

# カズマ
# おお、助かる！
139 = "おお、助かる！"

# ダクネス
# なら私はクリスを捜すのを手伝おう。
146 = "なら私はクリスを捜すのを手伝おう。"

# カズマ
# おう、任せた！
138 = "おう、任せた！"

# アクア
# じゃあ私は、酒場にでも行ってるわね。
142 = "じゃあ私は、酒場にでも行ってるわね。"

# カズマ
# 昼から酒かよ！\nお前も手伝えっ！
163 = "昼から酒かよ！\\nお前も手伝えっ！"

# アクア
# えー、でも、やることないじゃない。\nウィズはどうせ店にいるんだし。
137 = "えー、でも、やることないじゃない。\\nウィズはどうせ店にいるんだし。"

# カズマ
# はぁ、じゃあ、酒場で待っててくれ。\n場所を借りることをギルドのお姉さんに\n相談しないといけないからさ。
148 = "はぁ、じゃあ、酒場で待っててくれ。\\n場所を借りることをギルドのお姉さんに\\n相談しないといけないからさ。"

# アクア
# わかったわ！
150 = "わかったわ！"

# カズマ（Ｍ）
# display as カズマ
# （んじゃまずは、ウィズの店に行ってみるか）
188 = "（んじゃまずは、ウィズの店に行ってみるか）"

