# st01c_01.txt.scn

[info]
167 = "st01c_01"

[characters]
240 = "カズマ（Ｍ）"
230 = "めぐみん"
239 = "カズマ"
242 = "ダクネス"
235 = "ゆんゆん"
238 = "ウィズ"
237 = "アクア"
241 = "クリス"

[character_subs]
# 239 = "カズマ"

[script]
# lines: 69

# カズマ（Ｍ）
# display as カズマ
# （あれから数日――）
304 = "（あれから数日――）"

# カズマ（Ｍ）
# display as カズマ
# （俺たちはメイドの作法の特訓、\n　そして宣伝活動に奔走した）
312 = "（俺たちはメイドの作法の特訓、\\n　そして宣伝活動に奔走した）"

# カズマ（Ｍ）
# display as カズマ
# （その甲斐あってみんなはどこに出しても\n　恥ずかしくないメイドに仕上がったし――）
310 = "（その甲斐あってみんなはどこに出しても\\n　恥ずかしくないメイドに仕上がったし――）"

# カズマ（Ｍ）
# display as カズマ
# （至る所でメイド喫茶の話を耳にするくらいに、\n　知名度も跳ね上がった）
316 = "（至る所でメイド喫茶の話を耳にするくらいに、\\n　知名度も跳ね上がった）"

# カズマ（Ｍ）
# display as カズマ
# （この世界でもメイド喫茶が受け入れられる\n　手応えは十分にあった）
307 = "（この世界でもメイド喫茶が受け入れられる\\n　手応えは十分にあった）"

# カズマ（Ｍ）
# display as カズマ
# （あとは蓋を開けてどうなるか。\n　それはもうあいつらを信じるしかない）
303 = "（あとは蓋を開けてどうなるか。\\n　それはもうあいつらを信じるしかない）"

# カズマ（Ｍ）
# display as カズマ
# （開店までもうちょっとか、\n　やべぇ、なんか緊張してきたんですけど！）
317 = "（開店までもうちょっとか、\\n　やべぇ、なんか緊張してきたんですけど！）"

# カズマ（Ｍ）
# display as カズマ
# （そういえば、あいつらはどうしたんだ？\n　更衣室に入って、もう３０分くらい経つぞ）
309 = "（そういえば、あいつらはどうしたんだ？\\n　更衣室に入って、もう３０分くらい経つぞ）"

# めぐみん
# あー、あの、カズマ……。
196 = "あー、あの、カズマ……。"

# カズマ
# お、やっと来たか。他のみんなはどうした？
202 = "お、やっと来たか。他のみんなはどうした？"

# めぐみん
# まだ着替えの途中ですよ。\nすぐに来るとは思いますけど。
227 = "まだ着替えの途中ですよ。\\nすぐに来るとは思いますけど。"

# めぐみん
# それより、本当にやるんですか？
213 = "それより、本当にやるんですか？"

# カズマ
# ここまで来て何言ってるんだよ。\n店の準備は出来てるし、お前だって\nもうメイド服着てるじゃないか。
207 = "ここまで来て何言ってるんだよ。\\n店の準備は出来てるし、お前だって\\nもうメイド服着てるじゃないか。"

# めぐみん
# それはそうなんですけど……。
212 = "それはそうなんですけど……。"

# カズマ（Ｍ）
# display as カズマ
# （こいつ、土壇場に来て怖気づいてるのか？）
306 = "（こいつ、土壇場に来て怖気づいてるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （普段、俺のことをへたれだなんだって言うくせに、\n　まったく……）
314 = "（普段、俺のことをへたれだなんだって言うくせに、\\n　まったく……）"

# カズマ
# めぐみんは可愛いから大丈夫だって。
233 = "めぐみんは可愛いから大丈夫だって。"

# めぐみん
# なな、な、何をいきなり！？
220 = "なな、な、何をいきなり！？"

# カズマ
# 心配するなってことだよ。\n別に失敗したっていいんだから。
255 = "心配するなってことだよ。\\n別に失敗したっていいんだから。"

# カズマ
# むしろ可愛い子の失敗は、\n人によってはご褒美に感じることもあるんだぞ？
229 = "むしろ可愛い子の失敗は、\\n人によってはご褒美に感じることもあるんだぞ？"

# めぐみん
# 何を訳のわからないことを……。
248 = "何を訳のわからないことを……。"

# カズマ
# 俺だったら\nめぐみんに給仕してもらいたいけどな。
249 = "俺だったら\\nめぐみんに給仕してもらいたいけどな。"

# めぐみん
# な、なんですいきなり！？
219 = "な、なんですいきなり！？"

# カズマ
# どうだい、めぐみん。\n俺だけのメイドにならないか？
218 = "どうだい、めぐみん。\\n俺だけのメイドにならないか？"

# めぐみん
# お断りです。
205 = "お断りです。"

# カズマ
# はは、そっか、残念だ。
225 = "はは、そっか、残念だ。"

# めぐみん
# まったく、調子の良いことを言って。
228 = "まったく、調子の良いことを言って。"

# カズマ
# 終わったら爆裂魔法を撃って来て良いからさ。\n頼むよ、この通り。
300 = "終わったら爆裂魔法を撃って来て良いからさ。\\n頼むよ、この通り。"

# めぐみん
# そんなのカズマに許してもらわなくても、\nあとで勝手に撃ちに行きますよ。
214 = "そんなのカズマに許してもらわなくても、\\nあとで勝手に撃ちに行きますよ。"

# めぐみん
# というか、爆裂魔法を引き合いに出せば、\n私がなんでも言うことを聞くと思ってませんか？
216 = "というか、爆裂魔法を引き合いに出せば、\\n私がなんでも言うことを聞くと思ってませんか？"

# カズマ
# 違うのか？
302 = "違うのか？"

# めぐみん
# くっ……違うと言い切れないのが\n悔しい所ではありますね。
206 = "くっ……違うと言い切れないのが\\n悔しい所ではありますね。"

# カズマ
# まあ、どうしても嫌だって言うなら\n無理強いはしないけどな。
226 = "まあ、どうしても嫌だって言うなら\\n無理強いはしないけどな。"

# めぐみん
# 急にどうしたんです？
256 = "急にどうしたんです？"

# カズマ
# だって原因は俺にあるわけで、\n本来ならみんなには関係ないことだろ？
215 = "だって原因は俺にあるわけで、\\n本来ならみんなには関係ないことだろ？"

# めぐみん
# 確かにそうですね。\nじゃあ、私はもう下ります。
297 = "確かにそうですね。\\nじゃあ、私はもう下ります。"

# カズマ
# いやいや、少しは悩めよ！\nいえ、悩んでください！\nそして助けてください！
197 = "いやいや、少しは悩めよ！\\nいえ、悩んでください！\\nそして助けてください！"

# めぐみん
# もう、思ってもいないことを言って格好つけないで\nください。気持ち悪い。
234 = "もう、思ってもいないことを言って格好つけないで\\nください。気持ち悪い。"

# カズマ（Ｍ）
# display as カズマ
# （気持ち……悪い！？）
315 = "（気持ち……悪い！？）"

# めぐみん
# それに無関係というわけではないでしょう。\n盗まれるのは私たちのパンツなんですから。
211 = "それに無関係というわけではないでしょう。\\n盗まれるのは私たちのパンツなんですから。"

# カズマ
# ごもっともです。
208 = "ごもっともです。"

# ダクネス
# すまない、少し化粧に手間取った。
210 = "すまない、少し化粧に手間取った。"

# カズマ
# おお、見違えたな！
203 = "おお、見違えたな！"

# ゆんゆん
# お化粧なんて滅多にしませんから、\nちょっと新鮮な気分です。
204 = "お化粧なんて滅多にしませんから、\\nちょっと新鮮な気分です。"

# ウィズ
# 私、少しは血色が良くなったでしょうか。
298 = "私、少しは血色が良くなったでしょうか。"

# カズマ（Ｍ）
# display as カズマ
# （うんうん、いい感じだ！）
305 = "（うんうん、いい感じだ！）"

# カズマ（Ｍ）
# display as カズマ
# （俺は声を大にして言いたい！\n　この豊満な山々をぜひ見てくれと！）
313 = "（俺は声を大にして言いたい！\\n　この豊満な山々をぜひ見てくれと！）"

# めぐみん
# 何をにやけてるんです？
247 = "何をにやけてるんです？"

# カズマ
# に、にやけてなんかないぞ！
222 = "に、にやけてなんかないぞ！"

# めぐみん
# …………。
194 = "…………。"

# カズマ
# …………。
# 194 = "…………。"

# ゆんゆん
# あ、めぐみん。がんばろうね！
195 = "あ、めぐみん。がんばろうね！"

# めぐみん
# うるさいですよ！　これみよがしに、\n脂肪の塊を重そうにゆっさゆっささせて！
199 = "うるさいですよ！　これみよがしに、\\n脂肪の塊を重そうにゆっさゆっささせて！"

# ゆんゆん
# えー！？　なんで怒ってるのー！？
201 = "えー！？　なんで怒ってるのー！？"

# カズマ（Ｍ）
# display as カズマ
# （やれやれ……）
311 = "（やれやれ……）"

# アクア
# ねえねえ、なんか外、すごいことになってるわよ？
223 = "ねえねえ、なんか外、すごいことになってるわよ？"

# クリス
# ドン引きするくらい、列ができてるんだけど。
244 = "ドン引きするくらい、列ができてるんだけど。"

# カズマ
# マジか！？
245 = "マジか！？"

# カズマ（Ｍ）
# display as カズマ
# （これはもしかして、\n　予想以上のことになるんじゃないか？）
308 = "（これはもしかして、\\n　予想以上のことになるんじゃないか？）"

# カズマ
# ええと、みんなの準備は――
200 = "ええと、みんなの準備は――"

# アクア
# 問題なしよ！
252 = "問題なしよ！"

# カズマ
# よよよ、よし、じゃあ、開店するぞ！
236 = "よよよ、よし、じゃあ、開店するぞ！"

# ダクネス
# なんでカズマが緊張してるんだ。
221 = "なんでカズマが緊張してるんだ。"

# めぐみん
# チキンですね。
243 = "チキンですね。"

# カズマ
# うっさい！\nほら、最初のご主人様をお迎えするから、\nそこに並べ！
198 = "うっさい！\\nほら、最初のご主人様をお迎えするから、\\nそこに並べ！"

# ゆんゆん
# はぁ、緊張する。
224 = "はぁ、緊張する。"

# ウィズ
# 私もです。
299 = "私もです。"

# クリス
# どうか見えませんように、見えませんように。
217 = "どうか見えませんように、見えませんように。"

# カズマ
# じゃあ、開けるぞ！\nみんな背筋を伸ばして！
209 = "じゃあ、開けるぞ！\\nみんな背筋を伸ばして！"

[selections]
232 = "めぐみんは可愛いから大丈夫だって"
231 = "めぐみんに給仕をしてもらいたい"
301 = "終わったら爆裂魔法撃って来ていいから"
