# st01b_05.txt.scn

[info]
91 = "st01b_05"

[characters]
161 = "ウィズ"
165 = "カズマ"
166 = "カズマ（Ｍ）"

[character_subs]
# 165 = "カズマ"

[script]
# lines: 58

# ウィズ
# いらっしゃいませー。
133 = "いらっしゃいませー。"

# カズマ
# ようウィズ。もう戻ってたんだな。
160 = "ようウィズ。もう戻ってたんだな。"

# ウィズ
# はい。\nカズマさんがお出かけになったあと、すぐに。
156 = "はい。\\nカズマさんがお出かけになったあと、すぐに。"

# カズマ
# ええと、バニルってまだ戻って来てないんだよな。
135 = "ええと、バニルってまだ戻って来てないんだよな。"

# ウィズ
# はい。\n行き先にも見当がつかない状況でして。
157 = "はい。\\n行き先にも見当がつかない状況でして。"

# カズマ
# そうか。
142 = "そうか。"

# ウィズ
# あの、元気出してください。\n私もできる範囲で解除する方法を調べてみますから。
128 = "あの、元気出してください。\\n私もできる範囲で解除する方法を調べてみますから。"

# カズマ
# ウィズだけだよ、俺のことを真面目に\n心配してくれるのは。
162 = "ウィズだけだよ、俺のことを真面目に\\n心配してくれるのは。"

# ウィズ
# そんなことありません。アクア様たちだって\n心の底では心配してくださっていると思いますよ。
146 = "そんなことありません。アクア様たちだって\\n心の底では心配してくださっていると思いますよ。"

# カズマ
# あいつらが？
124 = "あいつらが？"

# ウィズ
# はい。昨夜だって、遅くまで指輪の対策を\n話し合っていたんですから。
158 = "はい。昨夜だって、遅くまで指輪の対策を\\n話し合っていたんですから。"

# カズマ（Ｍ）
# display as カズマ
# （ウィズの言葉を疑いたくはないが……）
214 = "（ウィズの言葉を疑いたくはないが……）"

# カズマ
# ありえないだろ、そんなの。
129 = "ありえないだろ、そんなの。"

# カズマ
# どうせアクアなんて、シュワシュワでも飲んで\n気持ち良く泥酔してたんじゃないのか？
151 = "どうせアクアなんて、シュワシュワでも飲んで\\n気持ち良く泥酔してたんじゃないのか？"

# ウィズ
# そ、そんなことは……。
139 = "そ、そんなことは……。"

# カズマ
# いいっていいって。\n無理にあいつらのフォローなんかしなくて。
130 = "いいっていいって。\\n無理にあいつらのフォローなんかしなくて。"

# ウィズ
# そういうつもりじゃ……。
140 = "そういうつもりじゃ……。"

# カズマ
# ああ、悪い、困らせちまったな。
123 = "ああ、悪い、困らせちまったな。"

# ウィズ
# いえ、カズマさんが苛つく気持ちも\nわかりますので。
132 = "いえ、カズマさんが苛つく気持ちも\\nわかりますので。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、ウィズは本当にいい子だ）
204 = "（ああ、ウィズは本当にいい子だ）"

# カズマ（Ｍ）
# display as カズマ
# （きっと昨夜の話し合いの時も、\n　ウィズは真剣に意見を出してくれたに違いない）
206 = "（きっと昨夜の話し合いの時も、\\n　ウィズは真剣に意見を出してくれたに違いない）"

# ウィズ
# そうだ、珍しいお茶の葉が手に入ったんです。\n良かったら飲んでいってください。
143 = "そうだ、珍しいお茶の葉が手に入ったんです。\\n良かったら飲んでいってください。"

# カズマ
# 怪しい効果はないだろうな……。
171 = "怪しい効果はないだろうな……。"

# ウィズ
# ただの紅茶ですよ～。
148 = "ただの紅茶ですよ～。"

# カズマ
# それだったらありがたくいただくよ。
144 = "それだったらありがたくいただくよ。"

# ウィズ
# それでは着替えてきますので、\n待っていてください。
145 = "それでは着替えてきますので、\\n待っていてください。"

# カズマ
# え、着替え？　なんで？
134 = "え、着替え？　なんで？"

# ウィズ
# お茶の葉を譲ってくれた行商人の方が、\nこの服を着ておもてなしするのが作法だと教えて\n下さったんです。
137 = "お茶の葉を譲ってくれた行商人の方が、\\nこの服を着ておもてなしするのが作法だと教えて\\n下さったんです。"

# カズマ
# はぁ？　メイド服！？
155 = "はぁ？　メイド服！？"

# ウィズ
# ど、どうかされましたか？
150 = "ど、どうかされましたか？"

# カズマ（Ｍ）
# display as カズマ
# （落ちつけ俺。\n　この世界にだって使用人の文化はあるはずだ）
215 = "（落ちつけ俺。\\n　この世界にだって使用人の文化はあるはずだ）"

# カズマ（Ｍ）
# display as カズマ
# （いやだが、ミニスカートでこれでもかと\n　言わんばかりのフリルでの装飾は、\n　給仕するに相応しくない）
205 = "（いやだが、ミニスカートでこれでもかと\\n　言わんばかりのフリルでの装飾は、\\n　給仕するに相応しくない）"

# カズマ
# なあ、ウィズ。\nこういう服って、その辺で普通に売ってるのか？
152 = "なあ、ウィズ。\\nこういう服って、その辺で普通に売ってるのか？"

# ウィズ
# 似たような服はありますが、\nこのようなデザインの物は、とても珍しいと\n思いますよ。
168 = "似たような服はありますが、\\nこのようなデザインの物は、とても珍しいと\\n思いますよ。"

# ウィズ
# 行商人の方が言うには、遠方の国の礼服だとか。
202 = "行商人の方が言うには、遠方の国の礼服だとか。"

# カズマ（Ｍ）
# display as カズマ
# （れ、れいふく？）
212 = "（れ、れいふく？）"

# ウィズ
# そんな珍しい服が１０着で２０万エリスなんて、\nとてもお得な買い物でした。
147 = "そんな珍しい服が１０着で２０万エリスなんて、\\nとてもお得な買い物でした。"

# カズマ
# ちょぉぉ、待て！\nこれ買ったの？？　しかも１０着も！
149 = "ちょぉぉ、待て！\\nこれ買ったの？？　しかも１０着も！"

# ウィズ
# あっ、もちろんその分お茶の葉も買いましたよ？
125 = "あっ、もちろんその分お茶の葉も買いましたよ？"

# カズマ
# そういう問題じゃなくて！\nメイド服をそんなに持っててどうするんだよ！
141 = "そういう問題じゃなくて！\\nメイド服をそんなに持っててどうするんだよ！"

# カズマ
# まさかウィズ魔道具店の制服にするつもりなのか？\nそうなったら俺、絶対に毎日通うけどさ！
159 = "まさかウィズ魔道具店の制服にするつもりなのか？\\nそうなったら俺、絶対に毎日通うけどさ！"

# カズマ（Ｍ）
# display as カズマ
# （ん？　この店に通う？）
213 = "（ん？　この店に通う？）"

# ウィズ
# いえ、あの、珍しい服ですし、\nお店で売れないかなと。
131 = "いえ、あの、珍しい服ですし、\\nお店で売れないかなと。"

# カズマ（Ｍ）
# display as カズマ
# （ふむ、珍しい服か……）
211 = "（ふむ、珍しい服か……）"

# ウィズ
# あの、カズマさん？　どうかされましたか？
127 = "あの、カズマさん？　どうかされましたか？"

# カズマ（Ｍ）
# display as カズマ
# （それにウィズみたいに、普段足を見せない服を\n　着てる子が、こういうのを着たところを\n　想像するだけでも正直たまらない……）
209 = "（それにウィズみたいに、普段足を見せない服を\\n　着てる子が、こういうのを着たところを\\n　想像するだけでも正直たまらない……）"

# カズマ（Ｍ）
# display as カズマ
# （それはどんな世界であろうと、\n　ぶれることのない共通の見解に違いない）
210 = "（それはどんな世界であろうと、\\n　ぶれることのない共通の見解に違いない）"

# カズマ（Ｍ）
# display as カズマ
# （そう日本であろうと、この世界であろうとだ！）
207 = "（そう日本であろうと、この世界であろうとだ！）"

# ウィズ
# カ、カズマさーん。
164 = "カ、カズマさーん。"

# カズマ
# ウィズ！！
163 = "ウィズ！！"

# ウィズ
# は、はい、なんでしょう！？
154 = "は、はい、なんでしょう！？"

# カズマ
# このメイド服、３着は俺が買い取ろう！
138 = "このメイド服、３着は俺が買い取ろう！"

# ウィズ
# え？　ええ！？
136 = "え？　ええ！？"

# カズマ
# あっ、やっぱり全部買い取るわ。\n何かあった時に替えが必要だからな。
126 = "あっ、やっぱり全部買い取るわ。\\n何かあった時に替えが必要だからな。"

# ウィズ
# あ、あの、ご購入いただけるのは嬉しいですけど、\n今は少しでもお金が必要なはずじゃ。
122 = "あ、あの、ご購入いただけるのは嬉しいですけど、\\n今は少しでもお金が必要なはずじゃ。"

# カズマ
# 金を稼ぐために、このメイド服を使うんだよ。
203 = "金を稼ぐために、このメイド服を使うんだよ。"

# ウィズ
# は、はあ、この服を。
153 = "は、はあ、この服を。"

# カズマ（Ｍ）
# display as カズマ
# （そのためにはまず、あいつらを説得しないと！）
208 = "（そのためにはまず、あいつらを説得しないと！）"

