# st01b_07.txt.scn

[info]
170 = "st01b_07"

[characters]
239 = "カズマ"
241 = "ダクネス"
233 = "めぐみん"
240 = "カズマ（Ｍ）"
236 = "アクア"

[character_subs]
# 239 = "カズマ"

[script]
# lines: 64

# カズマ
# そう！　可愛らしいメイド服に身を包んだ\n女の子たちに、ご主人様としてかいがいしく\nお世話をしてもらえる素敵空間――
205 = "そう！　可愛らしいメイド服に身を包んだ\\n女の子たちに、ご主人様としてかいがいしく\\nお世話をしてもらえる素敵空間――"

# カズマ
# それがメイド喫茶だ。
206 = "それがメイド喫茶だ。"

# ダクネス
# メイドになって世話をするだと！？
242 = "メイドになって世話をするだと！？"

# ダクネス
# なんていかがわしい店を開こうとしているんだ\nお前は！
221 = "なんていかがわしい店を開こうとしているんだ\\nお前は！"

# カズマ
# お世話からそんな想像をするお前の思考の方が\nいかがわしいわ！
194 = "お世話からそんな想像をするお前の思考の方が\\nいかがわしいわ！"

# ダクネス
# な！？
222 = "な！？"

# カズマ
# まあ、世話って言っても、注文された物を運んだり、\n簡単なゲームの相手をするだけだけどな。
230 = "まあ、世話って言っても、注文された物を運んだり、\\n簡単なゲームの相手をするだけだけどな。"

# めぐみん
# それだけ聞くと、普通の喫茶店と\nあまり変わらないように思えるのですが。
207 = "それだけ聞くと、普通の喫茶店と\\nあまり変わらないように思えるのですが。"

# カズマ
# だからこそ雰囲気作りが大事なわけだ。
213 = "だからこそ雰囲気作りが大事なわけだ。"

# カズマ
# 衣装はもちろん、言葉遣いや立ち居振る舞い、\nその他もろもろメイドになりきって、\n心からご主人様に奉仕する――
300 = "衣装はもちろん、言葉遣いや立ち居振る舞い、\\nその他もろもろメイドになりきって、\\n心からご主人様に奉仕する――"

# カズマ
# そんなメイドのいるメイド喫茶に俺は行きたい！
208 = "そんなメイドのいるメイド喫茶に俺は行きたい！"

# めぐみん
# 自分の欲望を垂れ流しているだけじゃないですか。
299 = "自分の欲望を垂れ流しているだけじゃないですか。"

# カズマ
# ちっがーう！\nこれは全世界のメイド喫茶好きの総意なんだよ！
216 = "ちっがーう！\\nこれは全世界のメイド喫茶好きの総意なんだよ！"

# めぐみん
# 総意とは大きく出ましたね。
297 = "総意とは大きく出ましたね。"

# カズマ（Ｍ）
# display as カズマ
# （まあ実際には好みなんて人それぞれだし、\n　あくまで今のは俺の気持ちでしかないけど、\n　ハッタリは大きくかましてこそ意味があるもんだ）
304 = "（まあ実際には好みなんて人それぞれだし、\\n　あくまで今のは俺の気持ちでしかないけど、\\n　ハッタリは大きくかましてこそ意味があるもんだ）"

# ダクネス
# しかし、ようは使用人なのだろう？\nそこまで熱くなる者が大勢いるとも思えないのだが？
198 = "しかし、ようは使用人なのだろう？\\nそこまで熱くなる者が大勢いるとも思えないのだが？"

# カズマ
# はっ。これだから\nお世話されることに慣れてるお嬢様は。
224 = "はっ。これだから\\nお世話されることに慣れてるお嬢様は。"

# ダクネス
# そ、それとこれとは話が別だろう！
199 = "そ、それとこれとは話が別だろう！"

# カズマ
# まあ確かに、この世界でメイドの存在自体は\n珍しいものじゃないかもしれない。
231 = "まあ確かに、この世界でメイドの存在自体は\\n珍しいものじゃないかもしれない。"

# カズマ
# だが、当たり前のように存在してるからといって、\n誰もが実際にお世話をしてもらってるわけじゃない。
215 = "だが、当たり前のように存在してるからといって、\\n誰もが実際にお世話をしてもらってるわけじゃない。"

# カズマ
# だからこそ、それに憧れ、需要が生まれるんだ。
212 = "だからこそ、それに憧れ、需要が生まれるんだ。"

# カズマ
# 加えて、そのメイドがめぐみんのように可愛らしく、\nダクネスみたいに美しかったらどうだ？
244 = "加えて、そのメイドがめぐみんのように可愛らしく、\\nダクネスみたいに美しかったらどうだ？"

# カズマ
# そう！\n誰もがこぞって通い詰めるに決まってるだろう！
204 = "そう！\\n誰もがこぞって通い詰めるに決まってるだろう！"

# めぐみん
# か、可愛らしいとか、\n面と向かってそういうこと言わないでください。\n恥ずかしいじゃないですか。
196 = "か、可愛らしいとか、\\n面と向かってそういうこと言わないでください。\\n恥ずかしいじゃないですか。"

# ダクネス
# 美しいなどと、らしくないことを言うな。\nまったく。
298 = "美しいなどと、らしくないことを言うな。\\nまったく。"

# カズマ
# だからさ、この通り頼むよ。\nメイド喫茶の店員をやってくれないか？
214 = "だからさ、この通り頼むよ。\\nメイド喫茶の店員をやってくれないか？"

# めぐみん
# まあ、いいでしょう。\n物は試しと言いますし、今のところ他に良い案が\nあるわけでもありませんしね。
228 = "まあ、いいでしょう。\\n物は試しと言いますし、今のところ他に良い案が\\nあるわけでもありませんしね。"

# ダクネス
# お前がそこまで言うのなら、\n仕方ないから付き合ってやる。
195 = "お前がそこまで言うのなら、\\n仕方ないから付き合ってやる。"

# カズマ
# わかってるって。恩に着るよ。
235 = "わかってるって。恩に着るよ。"

# カズマ
# アクア、お前もやってくれるよな？
237 = "アクア、お前もやってくれるよな？"

# アクア
# えー。
192 = "えー。"

# カズマ
# なんだよ、嫌なのか？
220 = "なんだよ、嫌なのか？"

# アクア
# 嫌に決まってるじゃない。\nどうして女神の私が\n他人の世話なんてしなくちゃいけないのよ。
247 = "嫌に決まってるじゃない。\\nどうして女神の私が\\n他人の世話なんてしなくちゃいけないのよ。"

# アクア
# むしろ私がしてもらう側でしょ、女神なんだから。
232 = "むしろ私がしてもらう側でしょ、女神なんだから。"

# カズマ（Ｍ）
# display as カズマ
# （さて、こいつをどう説得するか……）
301 = "（さて、こいつをどう説得するか……）"

# カズマ
# やってみたら、アクアが１番人気になるかも\nしれないぞ？
234 = "やってみたら、アクアが１番人気になるかも\\nしれないぞ？"

# アクア
# え、１番人気？
190 = "え、１番人気？"

# カズマ
# ああ。何しろアクアは女神なんだからな。\nその神々しさに惹かれて通い詰める客だって\n出てくるかもしれない。
188 = "ああ。何しろアクアは女神なんだからな。\\nその神々しさに惹かれて通い詰める客だって\\n出てくるかもしれない。"

# カズマ
# そうして人気を獲得できれば、\n店のアイドルとして\n好きなだけちやほやしてもらえるぞ？
202 = "そうして人気を獲得できれば、\\n店のアイドルとして\\n好きなだけちやほやしてもらえるぞ？"

# アクア
# べ、別に、ちやほやなんて\nしてもらいたいわけじゃないけど。
226 = "べ、別に、ちやほやなんて\\nしてもらいたいわけじゃないけど。"

# アクア
# そうね。どうしても私の女神としての\n威光に頼りたいって言うなら、\n少しくらいは手伝ってあげてもいいわよ？
203 = "そうね。どうしても私の女神としての\\n威光に頼りたいって言うなら、\\n少しくらいは手伝ってあげてもいいわよ？"

# カズマ（Ｍ）
# display as カズマ
# （思いっきり顔がニヤけてるぞ。\n　そんなにちやほやしてもらいたいのか、お前は）
306 = "（思いっきり顔がニヤけてるぞ。\\n　そんなにちやほやしてもらいたいのか、お前は）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、普段が普段だし、\n　たまにはちゃんと女神扱いされたいんだろう）
303 = "（まあ、普段が普段だし、\\n　たまにはちゃんと女神扱いされたいんだろう）"

# カズマ
# 店が軌道に乗れば一気に大金持ちだぞ？
249 = "店が軌道に乗れば一気に大金持ちだぞ？"

# アクア
# お、おおお、大金持ち！
193 = "お、おおお、大金持ち！"

# カズマ
# ああそうだ。指輪の呪いを解いた後も、\n順調だったらそのまま続けて、\n左うちわの生活だって夢じゃない！
189 = "ああそうだ。指輪の呪いを解いた後も、\\n順調だったらそのまま続けて、\\n左うちわの生活だって夢じゃない！"

# アクア
# そ、そんな簡単にうまくいくとは思わないけど。
200 = "そ、そんな簡単にうまくいくとは思わないけど。"

# アクア
# でも、やってみる価値はあるわよね、うん。\n失敗したらカズマが責任取ればいいだけだし。
217 = "でも、やってみる価値はあるわよね、うん。\\n失敗したらカズマが責任取ればいいだけだし。"

# アクア
# あ、でも、\nもしうまくいったら取り分は山分けだからね？
187 = "あ、でも、\\nもしうまくいったら取り分は山分けだからね？"

# カズマ
# はいはい、わかってるよ。
223 = "はいはい、わかってるよ。"

# カズマ
# たまには汗水たらして働けよ。
211 = "たまには汗水たらして働けよ。"

# アクア
# たまにはって何よ、たまにはって！\n私はいつも真面目に働いてあげてるでしょ！
209 = "たまにはって何よ、たまにはって！\\n私はいつも真面目に働いてあげてるでしょ！"

# カズマ
# 真面目にねぇ。
296 = "真面目にねぇ。"

# カズマ（Ｍ）
# display as カズマ
# （それでいつも迷惑かけてばかりなんだから、\n　余計にどうしようもないっていうか）
302 = "（それでいつも迷惑かけてばかりなんだから、\\n　余計にどうしようもないっていうか）"

# カズマ
# どうしてもダメか？
219 = "どうしてもダメか？"

# アクア
# ふん。３べん回ってワンて鳴いたら\n考えてあげなくもないわよ。
225 = "ふん。３べん回ってワンて鳴いたら\\n考えてあげなくもないわよ。"

# カズマ
# そうか。じゃあ――
201 = "そうか。じゃあ――"

# カズマ
# くるくるくるっと……わん。
197 = "くるくるくるっと……わん。"

# アクア
# ええ！？　そんなあっさりしちゃうの！？\nカズマさんてばプライドないわけ！？
191 = "ええ！？　そんなあっさりしちゃうの！？\\nカズマさんてばプライドないわけ！？"

# カズマ
# 女神のくせにほいほい土下座する\nお前に言われたくねーよ。
246 = "女神のくせにほいほい土下座する\\nお前に言われたくねーよ。"

# アクア
# ほいほいはしてないわよ！
227 = "ほいほいはしてないわよ！"

# カズマ
# とにかく、これでいいか？
218 = "とにかく、これでいいか？"

# アクア
# まあ、そこまでされちゃったら\n仕方ないっていうか、もう、なんなのよ。
229 = "まあ、そこまでされちゃったら\\n仕方ないっていうか、もう、なんなのよ。"

# カズマ（Ｍ）
# display as カズマ
# （よし。これでどうにか店を開く目処は立ったな）
305 = "（よし。これでどうにか店を開く目処は立ったな）"

[selections]
238 = "アクアが１番人気になるかもしれないぞ？"
# 249 = "店が軌道に乗れば一気に大金持ちだぞ？"
210 = "たまには汗水たらして働けよ"
