# st01b_13.txt.scn

[info]
227 = "st01b_13"

[characters]
371 = "カズマ"
367 = "アクア"
373 = "カズマ（Ｍ）"
354 = "めぐみん"
374 = "クリス"
375 = "ダクネス"
370 = "ウィズ"
358 = "ゆんゆん"
368 = "アクア＆めぐみん＆ダクネス＆ウィズ＆ゆんゆん＆クリス"
369 = "アクア＆ウィズ＆クリス"

[character_subs]
# 371 = "カズマ"
473 = "６人"
472 = "３人"

[script]
# lines: 131

# カズマ
# おーい、まだ準備できないのかよ？
301 = "おーい、まだ準備できないのかよ？"

# アクア
# うるさいわねー。\n女の子の支度を急かすんじゃない……の。
292 = "うるさいわねー。\\n女の子の支度を急かすんじゃない……の。"

# アクア
# って、ぶふっ！！　何よその服！\nあははは、受けるんですけど！\n超うけるんですけど！
327 = "って、ぶふっ！！　何よその服！\\nあははは、受けるんですけど！\\n超うけるんですけど！"

# カズマ
# うっさい、似合ってないのは\n自分でもわかってるわ！
289 = "うっさい、似合ってないのは\\n自分でもわかってるわ！"

# カズマ
# でも、いつもの格好で店に立つわけに\nいかねーんだよ！
330 = "でも、いつもの格好で店に立つわけに\\nいかねーんだよ！"

# アクア
# あははははははははははは！\nひぃ、ひぃぃ、お腹痛い～～～～！！
278 = "あははははははははははは！\\nひぃ、ひぃぃ、お腹痛い～～～～！！"

# カズマ（Ｍ）
# display as カズマ
# （聞いてねーしっ！）
471 = "（聞いてねーしっ！）"

# めぐみん
# ちょっとアクア、早く閉めてくださいよ！
326 = "ちょっとアクア、早く閉めてくださいよ！"

# クリス
# あたしたちはまだ着替え終わってないんだからさ！
276 = "あたしたちはまだ着替え終わってないんだからさ！"

# アクア
# あは、ひっ、ひぃぃ、お腹痛い！\n攣るっ、あはははは、お腹が攣る～～！！
277 = "あは、ひっ、ひぃぃ、お腹痛い！\\n攣るっ、あはははは、お腹が攣る～～！！"

# カズマ
# だー、いいから閉めろ！
322 = "だー、いいから閉めろ！"

# アクア
# はぁ、はひ、ひぃぃ～。\nはぁはぁはぁはぁ、笑い死ぬところだったわ。
340 = "はぁ、はひ、ひぃぃ～。\\nはぁはぁはぁはぁ、笑い死ぬところだったわ。"

# カズマ
# ようやく落ち着いたか。
361 = "ようやく落ち着いたか。"

# アクア
# ぶふっ！
347 = "ぶふっ！"

# カズマ
# もういい、やめろ。
356 = "もういい、やめろ。"

# アクア
# いたーい、ぶたないでったらっ！
284 = "いたーい、ぶたないでったらっ！"

# カズマ
# しかし、結構時間がかかるもんなんだな。
307 = "しかし、結構時間がかかるもんなんだな。"

# アクア
# それはそうよ、これって結構面倒な服だもの。
319 = "それはそうよ、これって結構面倒な服だもの。"

# カズマ（Ｍ）
# display as カズマ
# （他にも化粧とかあるだろうし、\n　店に入る時間は考えた方がいいかもしれないな）
466 = "（他にも化粧とかあるだろうし、\\n　店に入る時間は考えた方がいいかもしれないな）"

# アクア
# ところでカズマ？
333 = "ところでカズマ？"

# カズマ
# ん、なんだ？
364 = "ん、なんだ？"

# アクア
# 私を見て、何か言うことがあるんじゃないの？
452 = "私を見て、何か言うことがあるんじゃないの？"

# カズマ
# ぶふっ！
# 347 = "ぶふっ！"

# アクア
# ちょっと、笑うなんて失礼過ぎる！
325 = "ちょっと、笑うなんて失礼過ぎる！"

# カズマ
# はぁぁ？　どの口が言うか！\nこの口か！　この口かぁぁぁぁぁ！
341 = "はぁぁ？　どの口が言うか！\\nこの口か！　この口かぁぁぁぁぁ！"

# アクア
# 痛いっ！　いひゃい～！\nほっぺた引っ張らないっでったりゃぁ！
387 = "痛いっ！　いひゃい～！\\nほっぺた引っ張らないっでったりゃぁ！"

# ダクネス
# 何を騒いでいるんだ騒々しい。
378 = "何を騒いでいるんだ騒々しい。"

# カズマ
# おっ、ダクネスも終わったか。\nなかなか似合ってるぞ。
300 = "おっ、ダクネスも終わったか。\\nなかなか似合ってるぞ。"

# ダクネス
# そ、そうか？\nカズマもそういう服を着てると男前に見えるな。
313 = "そ、そうか？\\nカズマもそういう服を着てると男前に見えるな。"

# カズマ（Ｍ）
# display as カズマ
# （そういう服を着てると、か……）
461 = "（そういう服を着てると、か……）"

# カズマ
# それで、もう中に入ってもいいのか？
318 = "それで、もう中に入ってもいいのか？"

# ダクネス
# ああ、問題ないぞ。
272 = "ああ、問題ないぞ。"

# カズマ
# お、おおお！！
297 = "お、おおお！！"

# めぐみん
# なんです？　じろじろ見ないでくださいよ。\nひらひらしてて恥ずかしいんですから。
338 = "なんです？　じろじろ見ないでくださいよ。\\nひらひらしてて恥ずかしいんですから。"

# ダクネス
# そうだぞ。こうもスカートが短いと……。
316 = "そうだぞ。こうもスカートが短いと……。"

# ダクネス
# まあ、これはこれでと思わないこともないが。
349 = "まあ、これはこれでと思わないこともないが。"

# カズマ
# んー。
366 = "んー。"

# カズマ（Ｍ）
# display as カズマ
# （恥じらっているめぐみんは\n　なかなかにポイントが高いが、\n　妙な興奮に頬を赤らめているダクネスは……）
469 = "（恥じらっているめぐみんは\\n　なかなかにポイントが高いが、\\n　妙な興奮に頬を赤らめているダクネスは……）"

# カズマ（Ｍ）
# display as カズマ
# （そういうのが好きな層もいるかもしれないし、\n　今は放っておこう）
460 = "（そういうのが好きな層もいるかもしれないし、\\n　今は放っておこう）"

# ウィズ
# お待たせしましたー。
305 = "お待たせしましたー。"

# クリス
# うぅ……\nまたこんなすぐに呼び出されるなんて……\nせめて一回帰るくらいの時間があってくれれば……。
288 = "うぅ……\\nまたこんなすぐに呼び出されるなんて……\\nせめて一回帰るくらいの時間があってくれれば……。"

# ゆんゆん
# ？　どうかしたんですかクリスさん？
474 = "？　どうかしたんですかクリスさん？"

# カズマ
# ほう。
348 = "ほう。"

# カズマ（Ｍ）
# display as カズマ
# （続いて現れたウィズ、クリス、ゆんゆんを見て、\n　自然と顔がにやけてしまう）
470 = "（続いて現れたウィズ、クリス、ゆんゆんを見て、\\n　自然と顔がにやけてしまう）"

# カズマ（Ｍ）
# display as カズマ
# （いい！　実にいい！\n　より取り見取りっていうのはこういうことか！）
457 = "（いい！　実にいい！\\n　より取り見取りっていうのはこういうことか！）"

# アクア
# ねえ。なんかカズマが変な顔してるんだけど。
339 = "ねえ。なんかカズマが変な顔してるんだけど。"

# めぐみん
# 良からぬことを想像してる顔ですね、あれは。
454 = "良からぬことを想像してる顔ですね、あれは。"

# ダクネス
# よ、良からぬことだと？\nまさか私たちのことを頭の中で……。
360 = "よ、良からぬことだと？\\nまさか私たちのことを頭の中で……。"

# カズマ
# じゃあそろそろ特訓を始めるぞ！
308 = "じゃあそろそろ特訓を始めるぞ！"

# アクア
# あ、ごまかした。
271 = "あ、ごまかした。"

# カズマ
# うるさい！
293 = "うるさい！"

# カズマ
# まずは言葉遣いから行くとするか。
351 = "まずは言葉遣いから行くとするか。"

# カズマ
# 基本的に、男の客はご主人様、\n女の客はお嬢様と呼ぶこと。
382 = "基本的に、男の客はご主人様、\\n女の客はお嬢様と呼ぶこと。"

# ゆんゆん
# ご、ご主人様？
306 = "ご、ご主人様？"

# ウィズ
# お嬢様、ですか……。
302 = "お嬢様、ですか……。"

# カズマ
# それを踏まえた上で、出迎えの挨拶は、\nお帰りなさいませご主人様、\nもしくはお嬢様ってことになる。
320 = "それを踏まえた上で、出迎えの挨拶は、\\nお帰りなさいませご主人様、\\nもしくはお嬢様ってことになる。"

# クリス
# ふーん。店を家として見立ててるわけだ。
346 = "ふーん。店を家として見立ててるわけだ。"

# カズマ
# そういうこと。
315 = "そういうこと。"

# カズマ
# というわけで、まずはみんなで挨拶の練習だ。
331 = "というわけで、まずはみんなで挨拶の練習だ。"

# カズマ
# いいか？　せーの！
283 = "いいか？　せーの！"

# アクア＆めぐみん＆ダクネス＆ウィズ＆ゆんゆん＆クリス
# display as ６人
# お帰りなさいませご主人様。
303 = "お帰りなさいませご主人様。"

# カズマ
# おいおい。ちゃんとやる気を出してくれよ。
299 = "おいおい。ちゃんとやる気を出してくれよ。"

# めぐみん
# そう言われても、\n急にこんなことをやらされるのは\n気恥ずかしいというか……。
317 = "そう言われても、\\n急にこんなことをやらされるのは\\n気恥ずかしいというか……。"

# カズマ
# 練習でできないことが本番でできるか。
453 = "練習でできないことが本番でできるか。"

# カズマ
# ちゃんとできるようになるまで、\n何度だってやり直すからな。
323 = "ちゃんとできるようになるまで、\\n何度だってやり直すからな。"

# カズマ
# いいか？\nその服を着てる間は、お前たちはメイドなんだ。
282 = "いいか？\\nその服を着てる間は、お前たちはメイドなんだ。"

# カズマ
# ちゃんとメイドになりきって、\n心からご主人様を出迎えてみせろ。
324 = "ちゃんとメイドになりきって、\\n心からご主人様を出迎えてみせろ。"

# カズマ
# じゃあ行くぞ？　せーの！
312 = "じゃあ行くぞ？　せーの！"

# アクア＆めぐみん＆ダクネス＆ウィズ＆ゆんゆん＆クリス
# display as ６人
# お帰りなさいませご主人様！
304 = "お帰りなさいませご主人様！"

# カズマ（Ｍ）
# display as カズマ
# （こうして特訓は始まった）
459 = "（こうして特訓は始まった）"

# カズマ（Ｍ）
# display as カズマ
# （みんな照れくさそうにしてたものの、\n　飲み込み自体は早く、俺の指示を問題なく\n　こなしていく）
465 = "（みんな照れくさそうにしてたものの、\\n　飲み込み自体は早く、俺の指示を問題なく\\n　こなしていく）"

# カズマ（Ｍ）
# display as カズマ
# （いろんな挨拶から、\n　メイドらしい立ち居振る舞いなど……）
458 = "（いろんな挨拶から、\\n　メイドらしい立ち居振る舞いなど……）"

# カズマ（Ｍ）
# display as カズマ
# （だが、そうして順調に進んで行く中で、\n　俺は密かに焦っていた）
462 = "（だが、そうして順調に進んで行く中で、\\n　俺は密かに焦っていた）"

# カズマ（Ｍ）
# display as カズマ
# （なぜって、このあとに教えることを\n　まだ何も思いついていなかったからだ）
464 = "（なぜって、このあとに教えることを\\n　まだ何も思いついていなかったからだ）"

# カズマ（Ｍ）
# display as カズマ
# （だってしょーがないだろ。\n　メイド喫茶のイメージなんて、\n　漫画やネットで得た表面上の知識しかない）
463 = "（だってしょーがないだろ。\\n　メイド喫茶のイメージなんて、\\n　漫画やネットで得た表面上の知識しかない）"

# カズマ（Ｍ）
# display as カズマ
# （実際に店をやるために必要なことなんて、\n　俺にはこれっぽっちもわかっちゃいないんだ）
468 = "（実際に店をやるために必要なことなんて、\\n　俺にはこれっぽっちもわかっちゃいないんだ）"

# アクア
# カズマ、次は？　ねえ次はどんなことするの？
372 = "カズマ、次は？　ねえ次はどんなことするの？"

# カズマ
# ええと……。
296 = "ええと……。"

# カズマ（Ｍ）
# display as カズマ
# （何かないか……何か……）
467 = "（何かないか……何か……）"

# カズマ
# 萌え……そう、萌えだ！
455 = "萌え……そう、萌えだ！"

# ダクネス
# もえ？
357 = "もえ？"

# めぐみん
# なんです、その、もえというのは？
337 = "なんです、その、もえというのは？"

# カズマ
# 改めて聞かれると説明するのが難しいが、\n属性とか個性とか、もろもろの要素で、\nくーってなる感覚っていうかだな……。
385 = "改めて聞かれると説明するのが難しいが、\\n属性とか個性とか、もろもろの要素で、\\nくーってなる感覚っていうかだな……。"

# カズマ
# まあとにかく、\n試しに教えてみるからやってみてくれ。
350 = "まあとにかく、\\n試しに教えてみるからやってみてくれ。"

# カズマ
# じゃあ代表してめぐみんに教えてみるか。
309 = "じゃあ代表してめぐみんに教えてみるか。"

# めぐみん
# 私ですか？
451 = "私ですか？"

# カズマ
# ああ。そうだな。\nめぐみんだったら……\n定番のツンデレなんか良いかもな。
273 = "ああ。そうだな。\\nめぐみんだったら……\\n定番のツンデレなんか良いかもな。"

# めぐみん
# つんでれ？
328 = "つんでれ？"

# カズマ
# うむ。オーソドックスに、\n注文を受ける時はツンで、\n渡す時にデレる感じで行ってみよう。
290 = "うむ。オーソドックスに、\\n注文を受ける時はツンで、\\n渡す時にデレる感じで行ってみよう。"

# カズマ
# 俺がやってみせるから、続けてマネしてみてくれ。
379 = "俺がやってみせるから、続けてマネしてみてくれ。"

# めぐみん
# はあ……。
342 = "はあ……。"

# カズマ
# うーんと、じゃあ……。
295 = "うーんと、じゃあ……。"

# カズマ
# はい、メニューを持ってきてあげたわよ。\nさっさと選びなさいよ。
343 = "はい、メニューを持ってきてあげたわよ。\\nさっさと選びなさいよ。"

# めぐみん
# そ、そんなに高圧的な態度で大丈夫なんですか？
314 = "そ、そんなに高圧的な態度で大丈夫なんですか？"

# カズマ
# いいから早く言ってみろって。
281 = "いいから早く言ってみろって。"

# めぐみん
# …………。
268 = "…………。"

# めぐみん
# はい、メニューを持ってきてあげましたよ。\nさっさと選びなさい。
344 = "はい、メニューを持ってきてあげましたよ。\\nさっさと選びなさい。"

# カズマ
# で、注文を渡す時はだ……。
329 = "で、注文を渡す時はだ……。"

# カズマ
# ありがたく思いなさいよね。\n私が……持ってきてあげたんだから。
280 = "ありがたく思いなさいよね。\\n私が……持ってきてあげたんだから。"

# めぐみん
# あ、ありがたく思ってください。\n私が持ってきてあげたのですから……？
270 = "あ、ありがたく思ってください。\\n私が持ってきてあげたのですから……？"

# カズマ
# みたいな感じのを\nもっと感情を込めてやるんだ。いいな？
352 = "みたいな感じのを\\nもっと感情を込めてやるんだ。いいな？"

# めぐみん
# ……はあ。
269 = "……はあ。"

# カズマ
# じゃあ代表してゆんゆんに教えてみるか。
310 = "じゃあ代表してゆんゆんに教えてみるか。"

# ゆんゆん
# わわ、私に？
363 = "わわ、私に？"

# カズマ
# ああ。そうだな。\nゆんゆんだったら……\n甘えん坊なキャラなんて良いかもな。
274 = "ああ。そうだな。\\nゆんゆんだったら……\\n甘えん坊なキャラなんて良いかもな。"

# ゆんゆん
# あまえんぼう？
279 = "あまえんぼう？"

# カズマ
# うむ。注文を受ける時とかに、\n思いっきり甘えてみせるんだ。
291 = "うむ。注文を受ける時とかに、\\n思いっきり甘えてみせるんだ。"

# ゆんゆん
# そんなこと言われても、\n甘えるなんてどうやったら……。
321 = "そんなこと言われても、\\n甘えるなんてどうやったら……。"

# カズマ
# んー、例えば……。
365 = "んー、例えば……。"

# カズマ
# 私ぃ、これがすご～くおいしくてお気に入りなんだ。\nお兄ちゃんも試しに食べてみて欲しいな～。
449 = "私ぃ、これがすご～くおいしくてお気に入りなんだ。\\nお兄ちゃんも試しに食べてみて欲しいな～。"

# ゆんゆん
# お、お兄ちゃん！？
298 = "お、お兄ちゃん！？"

# カズマ
# いや、呼び方はどうでもいいんだけど、\n甘えるっていったらこんな感じかと思ってな。
286 = "いや、呼び方はどうでもいいんだけど、\\n甘えるっていったらこんな感じかと思ってな。"

# カズマ
# とにかく、ほら、さっさとやる。
334 = "とにかく、ほら、さっさとやる。"

# ゆんゆん
# ええと……。
# 296 = "ええと……。"

# ゆんゆん
# 私ぃ、これがすご～くおいしくてお気に入りなんだ。\nお兄ちゃんも試しに食べてみて欲しいな～。
# 449 = "私ぃ、これがすご～くおいしくてお気に入りなんだ。\\nお兄ちゃんも試しに食べてみて欲しいな～。"

# カズマ
# よしよし。そんな感じで、\n本番はもっと感情を込めてやるんだぞ。いいな？
362 = "よしよし。そんな感じで、\\n本番はもっと感情を込めてやるんだぞ。いいな？"

# ゆんゆん
# ……はあ。
# 269 = "……はあ。"

# カズマ
# じゃあ代表してダクネスに教えてみるか。
311 = "じゃあ代表してダクネスに教えてみるか。"

# ダクネス
# 私か？
450 = "私か？"

# カズマ
# ああ。そうだな。ダクネスだったら……。
275 = "ああ。そうだな。ダクネスだったら……。"

# カズマ
# …………。
# 268 = "…………。"

# ダクネス
# な、なんだ？　何をじっと見つめている？
335 = "な、なんだ？　何をじっと見つめている？"

# カズマ
# いや、なんていうか……\nお前は黙ってた方がいいんじゃないかと思ってな。
285 = "いや、なんていうか……\\nお前は黙ってた方がいいんじゃないかと思ってな。"

# ダクネス
# は？
345 = "は？"

# カズマ
# うん。そうしよう。\nダクネスは黙って微笑んでるだけでいい。\nそうすれば深窓の令嬢に見えるからな。
294 = "うん。そうしよう。\\nダクネスは黙って微笑んでるだけでいい。\\nそうすれば深窓の令嬢に見えるからな。"

# ダクネス
# なんだそれは！　私をバカにしてるのか！
336 = "なんだそれは！　私をバカにしてるのか！"

# カズマ
# いやいや。むしろ褒めてるくらいだぞ。\n何しろお前は見てくれだけなら申し分ないからな。
287 = "いやいや。むしろ褒めてるくらいだぞ。\\n何しろお前は見てくれだけなら申し分ないからな。"

# カズマ
# 黙って微笑みかけるだけで、\n大抵の男ならイチコロだと思うぞ？\nだから余計なことはしないでくれ、頼む。
456 = "黙って微笑みかけるだけで、\\n大抵の男ならイチコロだと思うぞ？\\nだから余計なことはしないでくれ、頼む。"

# ダクネス
# むぅ……。
353 = "むぅ……。"

# カズマ
# という具合にだ、他のみんなにも\nあとでそれぞれに合いそうな萌え要素を\n教えるから、そのつもりでいてくれ。
332 = "という具合にだ、他のみんなにも\\nあとでそれぞれに合いそうな萌え要素を\\n教えるから、そのつもりでいてくれ。"

# アクア＆ウィズ＆クリス
# display as ３人
# …………。
# 268 = "…………。"

[selections]
355 = "めぐみんに教えてみる"
359 = "ゆんゆんに教えてみる"
376 = "ダクネスに教えてみる"
