# st01b_14.txt.scn

[info]
194 = "st01b_14"

[characters]
341 = "カズマ"
334 = "アクア"
336 = "ウィズ"
321 = "めぐみん"
348 = "ダクネス"
323 = "ゆんゆん"
343 = "クリス"
342 = "カズマ（Ｍ）"

[character_subs]
# 341 = "カズマ"

[script]
# lines: 145

# カズマ
# じゃあそろそろ実地訓練と行くか。
274 = "じゃあそろそろ実地訓練と行くか。"

# アクア
# えー、そんなことやるのー？
253 = "えー、そんなことやるのー？"

# カズマ
# 俺たちは商売をしようとしてるんだから、当然だろ。
352 = "俺たちは商売をしようとしてるんだから、当然だろ。"

# アクア
# 訓練なんてしなくても、\n私のこの溢れ出さんばかりの魅力があれば――
435 = "訓練なんてしなくても、\\n私のこの溢れ出さんばかりの魅力があれば――"

# カズマ
# じゃあ、まずは接客に慣れたウィズから！
271 = "じゃあ、まずは接客に慣れたウィズから！"

# ウィズ
# あ、はい！
231 = "あ、はい！"

# カズマ
# はい、お客さまが来ました！
309 = "はい、お客さまが来ました！"

# ウィズ
# あ、ええと、いらっしゃいませ。\nお客さま、今日は何かご入り用ですか？
230 = "あ、ええと、いらっしゃいませ。\\nお客さま、今日は何かご入り用ですか？"

# カズマ
# 違う！　いらっしゃいませじゃなくて、\nおかえりなさいませ！
436 = "違う！　いらっしゃいませじゃなくて、\\nおかえりなさいませ！"

# カズマ
# それにご主人様な！\n客じゃなくて、ご主人様！\nさっき言っただろ！
286 = "それにご主人様な！\\n客じゃなくて、ご主人様！\\nさっき言っただろ！"

# めぐみん
# それはわかっているのですが、\nご主人様と呼ぶ理由がさっぱりですよ。
288 = "それはわかっているのですが、\\nご主人様と呼ぶ理由がさっぱりですよ。"

# カズマ
# 客をご主人様と呼ぶのがメイド喫茶の作法なんだよ。
356 = "客をご主人様と呼ぶのがメイド喫茶の作法なんだよ。"

# ダクネス
# なんというか、特殊な世界なんだな。
303 = "なんというか、特殊な世界なんだな。"

# カズマ
# そう！　だからこそ客、いや世のご主人様達は\n世知辛くストレスばかりの現実から逃避するために\nメイド喫茶に足を運ぶんだ！
279 = "そう！　だからこそ客、いや世のご主人様達は\\n世知辛くストレスばかりの現実から逃避するために\\nメイド喫茶に足を運ぶんだ！"

# ゆんゆん
# へえ、奥が深いんですね～。
316 = "へえ、奥が深いんですね～。"

# クリス
# あはは、そこ感心する所じゃないと思うよ？
236 = "あはは、そこ感心する所じゃないと思うよ？"

# カズマ
# じゃあ、改めてもう一度！\nはい、お客さまが来ましたっ！
272 = "じゃあ、改めてもう一度！\\nはい、お客さまが来ましたっ！"

# ウィズ
# お帰りなさいませご主人様。
261 = "お帰りなさいませご主人様。"

# カズマ
# いい！　さすがウィズ。\nそこはかとなく品のある仕草に、\n優しい出迎え方がすごくいいぞ！
239 = "いい！　さすがウィズ。\\nそこはかとなく品のある仕草に、\\n優しい出迎え方がすごくいいぞ！"

# ウィズ
# そうですか？　ありがとうございます。
277 = "そうですか？　ありがとうございます。"

# カズマ
# よし、今のウィズを参考に、次はアクアやってみろ。
328 = "よし、今のウィズを参考に、次はアクアやってみろ。"

# アクア
# ちょっと、なんで私がこんな腐れアンデッドを\n参考にしなくちゃいけないのよ。
293 = "ちょっと、なんで私がこんな腐れアンデッドを\\n参考にしなくちゃいけないのよ。"

# ウィズ
# 腐れ！？
431 = "腐れ！？"

# カズマ
# だったらお前は、皆の参考になる接客が\nできるっていうのか？
292 = "だったらお前は、皆の参考になる接客が\\nできるっていうのか？"

# アクア
# 当然じゃない、商店街のバイトで鍛えた\n接客スキルを見せてあげるわ。
360 = "当然じゃない、商店街のバイトで鍛えた\\n接客スキルを見せてあげるわ。"

# カズマ
# はい、じゃあ、客が来ました。
310 = "はい、じゃあ、客が来ました。"

# アクア
# いらっしゃいませー。\n今揚げたてを用意しますから、\nちょっと待ってくださいね。
243 = "いらっしゃいませー。\\n今揚げたてを用意しますから、\\nちょっと待ってくださいね。"

# カズマ
# 明るくていい、笑顔も及第点だ……。
362 = "明るくていい、笑顔も及第点だ……。"

# アクア
# でしょー？
295 = "でしょー？"

# カズマ
# だが違う！\n俺たちがやろうとしてるのはメイド喫茶で\nお総菜屋さんじゃねーんだよ！
291 = "だが違う！\\n俺たちがやろうとしてるのはメイド喫茶で\\nお総菜屋さんじゃねーんだよ！"

# アクア
# でも、この接客でコロッケが売れ残らなく\nなったのよ？\n店長も最高の笑顔だって褒めてくれたし。
296 = "でも、この接客でコロッケが売れ残らなく\\nなったのよ？\\n店長も最高の笑顔だって褒めてくれたし。"

# カズマ
# 確かにいい笑顔だし、客も喜ぶだろう。
428 = "確かにいい笑顔だし、客も喜ぶだろう。"

# カズマ
# しかしだっ、メイド喫茶に来るのは\n財布の紐のきついおばちゃん達じゃない！
270 = "しかしだっ、メイド喫茶に来るのは\\n財布の紐のきついおばちゃん達じゃない！"

# アクア
# つまりどういうことよ。
294 = "つまりどういうことよ。"

# カズマ
# 俺たちがターゲットにする客は、\nそういう庶民的なのを求めてないんだ。
351 = "俺たちがターゲットにする客は、\\nそういう庶民的なのを求めてないんだ。"

# カズマ
# 親しみやすさも確かに大切だが、\nもっと重要視しないといけないのは\n気品なんだよ、気品っ！
434 = "親しみやすさも確かに大切だが、\\nもっと重要視しないといけないのは\\n気品なんだよ、気品っ！"

# アクア
# なんだ、それなら普段の私を見せれば\nいいだけじゃない。
301 = "なんだ、それなら普段の私を見せれば\\nいいだけじゃない。"

# カズマ
# ほほう。\nじゃあ、やってみろ。
317 = "ほほう。\\nじゃあ、やってみろ。"

# アクア
# こほん。\nいらっしゃいませ、ご主人様？
267 = "こほん。\\nいらっしゃいませ、ご主人様？"

# カズマ
# うーん。
247 = "うーん。"

# アクア
# どうよ、なかなかのもんでしょ！
298 = "どうよ、なかなかのもんでしょ！"

# カズマ（Ｍ）
# display as カズマ
# （悪くないけど、やっぱり気品がないな。\n　というよりも知性に欠ける？）
449 = "（悪くないけど、やっぱり気品がないな。\\n　というよりも知性に欠ける？）"

# アクア
# あら～、もしかして見とれちゃった？
237 = "あら～、もしかして見とれちゃった？"

# アクア
# それともこの極上の気品を形容する褒め言葉が\n見つからないのかしら。
285 = "それともこの極上の気品を形容する褒め言葉が\\n見つからないのかしら。"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、アクアに気品を求めるのは酷だったか）
441 = "（はぁ、アクアに気品を求めるのは酷だったか）"

# アクア
# ほーら、黙ってないで何か言いなさいよ。
319 = "ほーら、黙ってないで何か言いなさいよ。"

# カズマ
# うん、お前はそれでいいや。
245 = "うん、お前はそれでいいや。"

# アクア
# ふふん、当然よ！
315 = "ふふん、当然よ！"

# カズマ
# じゃあ、次はクリスな。
273 = "じゃあ、次はクリスな。"

# クリス
# ええ、あたしもやるの！？
251 = "ええ、あたしもやるの！？"

# カズマ
# 当然だろ。\nじゃあ、お紅茶を運んだシチュエーションで\nよろしく。
361 = "当然だろ。\\nじゃあ、お紅茶を運んだシチュエーションで\\nよろしく。"

# クリス
# はいはい、わかったよ。
312 = "はいはい、わかったよ。"

# カズマ
# ふふふーん、ここは綺麗なメイドさんが\nいっぱいだなー。
314 = "ふふふーん、ここは綺麗なメイドさんが\\nいっぱいだなー。"

# クリス
# ご主人様、お待たせしました。
268 = "ご主人様、お待たせしました。"

# カズマ
# うむ、ありがとう。
244 = "うむ、ありがとう。"

# クリス
# お熱くなっていますから、お気をつけください。\nそれでは、失礼いたします。
264 = "お熱くなっていますから、お気をつけください。\\nそれでは、失礼いたします。"

# カズマ
# はい、ストップ！
311 = "はい、ストップ！"

# クリス
# え、何？
250 = "え、何？"

# カズマ
# お辞儀がなってない！\nなんだその首だけの挨拶は！
265 = "お辞儀がなってない！\\nなんだその首だけの挨拶は！"

# カズマ
# それにスカートばっかり気にして\n動きがぎこちないぞ。
287 = "それにスカートばっかり気にして\\n動きがぎこちないぞ。"

# クリス
# だ、だって。
289 = "だ、だって。"

# カズマ
# なんだ、気になることでもあるのか？
302 = "なんだ、気になることでもあるのか？"

# クリス
# いや、スカートの中が、見えないかなって。
241 = "いや、スカートの中が、見えないかなって。"

# カズマ
# 確かにそれだけ短いと、お辞儀をしたときに\nちらっと見えちゃうかもな。
429 = "確かにそれだけ短いと、お辞儀をしたときに\\nちらっと見えちゃうかもな。"

# クリス
# そそそそ、それは困るよ！\n絶対にダメ！！
280 = "そそそそ、それは困るよ！\\n絶対にダメ！！"

# カズマ
# お、おう、すごい拒否反応だな。
256 = "お、おう、すごい拒否反応だな。"

# クリス
# だ、だって！\nだって……だって……。
290 = "だ、だって！\\nだって……だって……。"

# カズマ（Ｍ）
# display as カズマ
# （普段はショーパンにスパッツだし、\n　スカートじゃ心許ないんだろうな）
450 = "（普段はショーパンにスパッツだし、\\n　スカートじゃ心許ないんだろうな）"

# カズマ
# よし、わかった。\nみんなのスカートの中が覗かれないように\n対策を立てるよ。
325 = "よし、わかった。\\nみんなのスカートの中が覗かれないように\\n対策を立てるよ。"

# クリス
# 絶対だよ！　約束だからね！
430 = "絶対だよ！　約束だからね！"

# カズマ
# お、おう、わかってるって。
257 = "お、おう、わかってるって。"

# クリス
# はぁ、こんな服だってわかってたら\n引き受けなかったのに……。
306 = "はぁ、こんな服だってわかってたら\\n引き受けなかったのに……。"

# カズマ（Ｍ）
# display as カズマ
# （ウィズ、アクア、クリス。\n　３人とも基本的な作法は問題なさそうだな）
445 = "（ウィズ、アクア、クリス。\\n　３人とも基本的な作法は問題なさそうだな）"

# カズマ（Ｍ）
# display as カズマ
# （だが、あえてアドバイスをするとしたら……）
440 = "（だが、あえてアドバイスをするとしたら……）"

# カズマ（Ｍ）
# display as カズマ
# （アクアにアドバイスすることか……）
443 = "（アクアにアドバイスすることか……）"

# アクア
# ねえねえカズマ、お店の名前なんだけど、\n特別に私の名前を使ってもいいわよ。
304 = "ねえねえカズマ、お店の名前なんだけど、\\n特別に私の名前を使ってもいいわよ。"

# カズマ
# お前それ、名前の使用料を取るつもりだろ。
258 = "お前それ、名前の使用料を取るつもりだろ。"

# アクア
# そそそそ、そんなことしないったら。
281 = "そそそそ、そんなことしないったら。"

# カズマ（Ｍ）
# display as カズマ
# （こいつは、こういう小ずるいところを\n　馬鹿正直におもてに出すからなー）
438 = "（こいつは、こういう小ずるいところを\\n　馬鹿正直におもてに出すからなー）"

# カズマ
# なあ、アクア。
300 = "なあ、アクア。"

# アクア
# ん？　何？
333 = "ん？　何？"

# カズマ（Ｍ）
# display as カズマ
# （アドバイス、アドバイス……）
444 = "（アドバイス、アドバイス……）"

# アクア
# どうしたのよ。\n人の顔をジーッと見て。
297 = "どうしたのよ。\\n人の顔をジーッと見て。"

# カズマ
# うーん、頑張れ。
246 = "うーん、頑張れ。"

# アクア
# はあ？
308 = "はあ？"

# カズマ
# いやな、何かアドバイスをしようと思ったんだけど\nなんも思いつかなかったわ。
242 = "いやな、何かアドバイスをしようと思ったんだけど\\nなんも思いつかなかったわ。"

# カズマ（Ｍ）
# display as カズマ
# （下手にアドバイスしたら、\n　それで頭がいっぱいになって空回りしそうだし）
447 = "（下手にアドバイスしたら、\\n　それで頭がいっぱいになって空回りしそうだし）"

# アクア
# それってダメ出しする隙もないくらい\n完璧ってこと？
283 = "それってダメ出しする隙もないくらい\\n完璧ってこと？"

# アクア
# まあ、当然よね、だって私だし。
320 = "まあ、当然よね、だって私だし。"

# カズマ（Ｍ）
# display as カズマ
# （こうやってすぐに調子に乗るところも不安だ）
439 = "（こうやってすぐに調子に乗るところも不安だ）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズにアドバイスか……）
446 = "（ウィズにアドバイスか……）"

# ウィズ
# ？？　カズマさん、どうかしましたか？
451 = "？？　カズマさん、どうかしましたか？"

# カズマ
# ウィズ……。
337 = "ウィズ……。"

# ウィズ
# はい？
313 = "はい？"

# カズマ
# お母さん……。
262 = "お母さん……。"

# ウィズ
# え？
254 = "え？"

# カズマ
# お母さん！！
263 = "お母さん！！"

# ウィズ
# え、えっ？
248 = "え、えっ？"

# カズマ
# よし、ウィズはお母さんを前面に押し出そう。
326 = "よし、ウィズはお母さんを前面に押し出そう。"

# ウィズ
# あの～、言っている意味がよく……。
233 = "あの～、言っている意味がよく……。"

# カズマ
# ああ、悪い。\nどうやったらウィズの魅力をさらに引き出せるかを\n考えてたんだよ。
232 = "ああ、悪い。\\nどうやったらウィズの魅力をさらに引き出せるかを\\n考えてたんだよ。"

# ウィズ
# それでどうしてお母さんなんでしょう。
284 = "それでどうしてお母さんなんでしょう。"

# カズマ
# ウィズってすごく気が利くだろ？\nそういう優しい所がお母さんっぽいかなって。
338 = "ウィズってすごく気が利くだろ？\\nそういう優しい所がお母さんっぽいかなって。"

# ウィズ
# はぁ、なるほど。
307 = "はぁ、なるほど。"

# カズマ
# ウィズのおおらかな雰囲気はそれだけで癒しだから、\n意識してもっと前面に押していこうぜ。
340 = "ウィズのおおらかな雰囲気はそれだけで癒しだから、\\n意識してもっと前面に押していこうぜ。"

# ウィズ
# わ、わかりました。やってみます。
331 = "わ、わかりました。やってみます。"

# カズマ（Ｍ）
# display as カズマ
# （うん、ウィズならうまくやってくれるだろう）
437 = "（うん、ウィズならうまくやってくれるだろう）"

# カズマ
# クリスにアドバイスか……。
345 = "クリスにアドバイスか……。"

# クリス
# ん？　あたしが何？
332 = "ん？　あたしが何？"

# カズマ
# お前ってさ、クールなところがあるじゃん？
259 = "お前ってさ、クールなところがあるじゃん？"

# クリス
# え、そうかな？
249 = "え、そうかな？"

# カズマ
# クールなメイドさんも悪くないけど、\nそれだけじゃ火力不足なんだよ。
347 = "クールなメイドさんも悪くないけど、\\nそれだけじゃ火力不足なんだよ。"

# クリス
# あの～、話が見えないんだけど～。
234 = "あの～、話が見えないんだけど～。"

# カズマ
# よし、ギャップ萌えでいこう！
327 = "よし、ギャップ萌えでいこう！"

# クリス
# 何それ？
350 = "何それ？"

# カズマ
# 普段ツンケンしてる子がたまに見せる優しさには\nそれはもうすごい価値があるんだ。
363 = "普段ツンケンしてる子がたまに見せる優しさには\\nそれはもうすごい価値があるんだ。"

# クリス
# は、はあ。
305 = "は、はあ。"

# カズマ
# クリスにはそれを意図的に狙って貰おうと思ってさ。
344 = "クリスにはそれを意図的に狙って貰おうと思ってさ。"

# クリス
# ええと、やっぱりよくわからないや。
252 = "ええと、やっぱりよくわからないや。"

# カズマ
# 具体的に言うと、普段はクールに接客して\nそしてときどき可愛らしい一面を見せる。
353 = "具体的に言うと、普段はクールに接客して\\nそしてときどき可愛らしい一面を見せる。"

# カズマ
# そうやって客の心を鷲づかみにするんだ！
278 = "そうやって客の心を鷲づかみにするんだ！"

# クリス
# 理屈はなんとなくわかったけど、\nあたしに可愛いとか無理じゃない？
365 = "理屈はなんとなくわかったけど、\\nあたしに可愛いとか無理じゃない？"

# カズマ
# 自分でそういう風に思ってることも重要なんだ！
432 = "自分でそういう風に思ってることも重要なんだ！"

# クリス
# そ、そうなの？
275 = "そ、そうなの？"

# カズマ
# 自分を可愛いと思ってる子は、\nどうしたって可愛いオーラを出しちまうからな。
433 = "自分を可愛いと思ってる子は、\\nどうしたって可愛いオーラを出しちまうからな。"

# カズマ
# それじゃギャップ萌えの威力が半減しちまう。
282 = "それじゃギャップ萌えの威力が半減しちまう。"

# クリス
# よくわからないけど、難しいんだね。
324 = "よくわからないけど、難しいんだね。"

# カズマ
# よし、試しに、おいしくなーれ、って言ってみて\nくれよ？
329 = "よし、試しに、おいしくなーれ、って言ってみて\\nくれよ？"

# クリス
# あ、うん。\nおいしくなーれ？
229 = "あ、うん。\\nおいしくなーれ？"

# カズマ
# そうそう。\nそれをもっと気持ちを込めて――
276 = "そうそう。\\nそれをもっと気持ちを込めて――"

# カズマ
# さらに、もえもえきゅーんとかつけてみようぜ。
269 = "さらに、もえもえきゅーんとかつけてみようぜ。"

# クリス
# も、もえもえ？？？
322 = "も、もえもえ？？？"

# カズマ
# ほら。言ってみてくれよ。\nおいしくな～れ♪　もえもえきゅ～ん♪　って。
318 = "ほら。言ってみてくれよ。\\nおいしくな～れ♪　もえもえきゅ～ん♪　って。"

# クリス
# いや、そういうのはちょっと……。
240 = "いや、そういうのはちょっと……。"

# カズマ
# いいから言う。ほらほら。
238 = "いいから言う。ほらほら。"

# クリス
# お、おいしくな～れ♪　もえもえきゅ～ん♪
255 = "お、おいしくな～れ♪　もえもえきゅ～ん♪"

# カズマ
# くはっ！？
266 = "くはっ！？"

# クリス
# な、何！？
299 = "な、何！？"

# カズマ
# お前は天使か！　いや女神か！
260 = "お前は天使か！　いや女神か！"

# クリス
# あは、あはは……。\n男の子っていったいなんなの……。
235 = "あは、あはは……。\\n男の子っていったいなんなの……。"

# カズマ（Ｍ）
# display as カズマ
# （よし、クリスはこれでばっちりだな）
442 = "（よし、クリスはこれでばっちりだな）"

# カズマ（Ｍ）
# display as カズマ
# （他のみんなにも\n　あとで個別にアドバイスはするとして）
448 = "（他のみんなにも\\n　あとで個別にアドバイスはするとして）"

# カズマ
# よしっ、次は広報活動をしておくか。
330 = "よしっ、次は広報活動をしておくか。"

# ウィズ
# 広報？
359 = "広報？"

# クリス
# 活動？
364 = "活動？"

[selections]
335 = "アクアにアドバイスをしてやろう"
339 = "ウィズにアドバイスをしてやろう"
346 = "クリスにアドバイスをしてやろう"
