# st01a_03.txt.scn

[info]
171 = "st01a_03"

[characters]
254 = "アクア"
245 = "めぐみん"
257 = "カズマ"
261 = "ダクネス"
247 = "ゆんゆん"
260 = "クリス"
256 = "ウィズ"
255 = "アクア＆めぐみん"
259 = "カズマ（Ｍ）"

[character_subs]
315 = "２人"
# 257 = "カズマ"

[script]
# lines: 70

# アクア
# うわー。\nなんか変にやる気出しちゃってるんですけど。\nそういうのすごく迷惑なんですけど。
207 = "うわー。\\nなんか変にやる気出しちゃってるんですけど。\\nそういうのすごく迷惑なんですけど。"

# めぐみん
# そんなことをしても\n誰も幸せにならないというのに。
227 = "そんなことをしても\\n誰も幸せにならないというのに。"

# カズマ
# うるさいうるさい！\nこれは俺のプライドの問題なんだ！
206 = "うるさいうるさい！\\nこれは俺のプライドの問題なんだ！"

# ダクネス
# わかっているぞカズマ。\nそしてのそのプライドは、\nこの私が責任を持って受け止める！
249 = "わかっているぞカズマ。\\nそしてのそのプライドは、\\nこの私が責任を持って受け止める！"

# カズマ
# ……どういう意味だよ。
197 = "……どういう意味だよ。"

# ダクネス
# だから、お前の性癖を私が責任を持って\n受け止めると言っているんだ。
230 = "だから、お前の性癖を私が責任を持って\\n受け止めると言っているんだ。"

# ダクネス
# さ、さあ、私の下着の色や形を好きなだけ\nあてるがいい！
218 = "さ、さあ、私の下着の色や形を好きなだけ\\nあてるがいい！"

# カズマ
# とにかく、まずは聞き込みだな。\n捜査の基本は情報収集だって言うし。
235 = "とにかく、まずは聞き込みだな。\\n捜査の基本は情報収集だって言うし。"

# ダクネス
# 無視！？
275 = "無視！？"

# ゆんゆん
# わ、私は関係ありませんからね？
248 = "わ、私は関係ありませんからね？"

# クリス
# あー、あたしもね。
200 = "あー、あたしもね。"

# ウィズ
# ええと、たぶん私も。
209 = "ええと、たぶん私も。"

# カズマ
# まあそうだろうな。\nみんなさっき来たばかりなんだし。
244 = "まあそうだろうな。\\nみんなさっき来たばかりなんだし。"

# カズマ
# つまり、このパンツの持ち主は――
234 = "つまり、このパンツの持ち主は――"

# カズマ
# お前たち３人の中にいる！
211 = "お前たち３人の中にいる！"

# アクア＆めぐみん
# display as ２人
# はぁ……。
241 = "はぁ……。"

# ダクネス
# ふ、ふふ、ふふふ。
242 = "ふ、ふふ、ふふふ。"

# カズマ
# なんだお前ら、そのあきれきった顔は？
239 = "なんだお前ら、そのあきれきった顔は？"

# めぐみん
# そんなわかりきっていることを\n偉そうに言われても。
229 = "そんなわかりきっていることを\\n偉そうに言われても。"

# めぐみん
# まあ、それでもどうしてもと言うのなら。
243 = "まあ、それでもどうしてもと言うのなら。"

# めぐみん
# わー、名推理ですね。すごいすごい。
251 = "わー、名推理ですね。すごいすごい。"

# カズマ（Ｍ）
# display as カズマ
# （くっ、バカにしやがって）
312 = "（くっ、バカにしやがって）"

# クリス
# っていうか、これって当てようなくない？
232 = "っていうか、これって当てようなくない？"

# カズマ
# どうしてだよ。
236 = "どうしてだよ。"

# クリス
# だってさ、その子は、\nたくさんの中の１枚を盗まれただけなんでしょ？
231 = "だってさ、その子は、\\nたくさんの中の１枚を盗まれただけなんでしょ？"

# クリス
# そんなの違う下着を穿いておけばすむ話だもん。\nその１枚に固執する理由がない限りね。
228 = "そんなの違う下着を穿いておけばすむ話だもん。\\nその１枚に固執する理由がない限りね。"

# カズマ
# うっ、確かに自分からそれは私のパンツです\nなんて名乗り出る物好きはいないよな。
205 = "うっ、確かに自分からそれは私のパンツです\\nなんて名乗り出る物好きはいないよな。"

# ダクネス
# そうか？
220 = "そうか？"

# カズマ
# そうなんだよっ！
221 = "そうなんだよっ！"

# ウィズ
# それに仮に当てられても\n違うと言い通せば済む話ですもんね。
225 = "それに仮に当てられても\\n違うと言い通せば済む話ですもんね。"

# カズマ（Ｍ）
# display as カズマ
# （くっそ、さっそく計画が頓挫しやがった）
313 = "（くっそ、さっそく計画が頓挫しやがった）"

# めぐみん
# うぅ……。
204 = "うぅ……。"

# ダクネス
# ん、どうかしたのかめぐみん。
253 = "ん、どうかしたのかめぐみん。"

# めぐみん
# い、いえ、なんでもありませんよ！
201 = "い、いえ、なんでもありませんよ！"

# カズマ
# しょうがない。\nこれから俺が盗んじまったパンツは供養をして\nそれで終わりにしよう。
219 = "しょうがない。\\nこれから俺が盗んじまったパンツは供養をして\\nそれで終わりにしよう。"

# カズマ
# なあ、アクア。\nお前女神なんだからそういうの得意だろ？
238 = "なあ、アクア。\\nお前女神なんだからそういうの得意だろ？"

# アクア
# パンツの供養なんてできるわけないでしょ！
262 = "パンツの供養なんてできるわけないでしょ！"

# カズマ
# そっかー、じゃあ、燃やすしかないな。
223 = "そっかー、じゃあ、燃やすしかないな。"

# めぐみん
# 待ってください！
271 = "待ってください！"

# カズマ
# な、なんだよ。
237 = "な、なんだよ。"

# めぐみん
# カズマは、それで本当にいいんですか？
258 = "カズマは、それで本当にいいんですか？"

# めぐみん
# このままでは、\n変態のレッテルを貼られたままなのですよ。
215 = "このままでは、\\n変態のレッテルを貼られたままなのですよ。"

# カズマ（Ｍ）
# display as カズマ
# （確かにそれは勘弁して欲しい）
314 = "（確かにそれは勘弁して欲しい）"

# めぐみん
# それに燃すなんて、\n証拠を隠滅しているようなものじゃありませんか！
226 = "それに燃すなんて、\\n証拠を隠滅しているようなものじゃありませんか！"

# めぐみん
# 私は、カズマの男のプライドがそれを許すとは\n到底思えません！
310 = "私は、カズマの男のプライドがそれを許すとは\\n到底思えません！"

# カズマ
# ああ、俺もそう思うぞ、めぐみん！
198 = "ああ、俺もそう思うぞ、めぐみん！"

# めぐみん
# こほん、そこで私から提案なのですが――
216 = "こほん、そこで私から提案なのですが――"

# カズマ
# やっぱり俺は、パンツの持ち主を見つけ出すぞ！
246 = "やっぱり俺は、パンツの持ち主を見つけ出すぞ！"

# めぐみん
# なんでそうなるのです！
240 = "なんでそうなるのです！"

# めぐみん
# ここに置いておいて、誰かが取りにくるのを待てば\n全て解決するじゃないですか！
214 = "ここに置いておいて、誰かが取りにくるのを待てば\\n全て解決するじゃないですか！"

# カズマ
# いや、それではダメだ！
202 = "いや、それではダメだ！"

# カズマ
# 意図した行為で無いとはいえ、俺が盗ったのは事実。
272 = "意図した行為で無いとはいえ、俺が盗ったのは事実。"

# カズマ
# 俺は紳士として、この手でパンツを持ち主に返し、\nしっかりと謝罪をしたい！
264 = "俺は紳士として、この手でパンツを持ち主に返し、\\nしっかりと謝罪をしたい！"

# ダクネス
# 感心するべきか呆れるべきか、判断に迷うな。
273 = "感心するべきか呆れるべきか、判断に迷うな。"

# アクア
# っていうかさ、そろそろご飯にしない？\n私もうおなかぺこぺこなんだけど。
233 = "っていうかさ、そろそろご飯にしない？\\n私もうおなかぺこぺこなんだけど。"

# カズマ
# お前は、少しは協力しろよ！
213 = "お前は、少しは協力しろよ！"

# アクア
# 嫌よ。めんどくさいもの。
268 = "嫌よ。めんどくさいもの。"

# カズマ
# そっか、じゃあやっぱり借金するしかないな。
222 = "そっか、じゃあやっぱり借金するしかないな。"

# アクア
# 最初からそうすればよかったのよ。
274 = "最初からそうすればよかったのよ。"

# カズマ
# 言っておくけど、借金はパーティー内で\n均等に分けるからな。
311 = "言っておくけど、借金はパーティー内で\\n均等に分けるからな。"

# アクア
# え……。
208 = "え……。"

# カズマ
# これまでだってそうだったじゃないか。
217 = "これまでだってそうだったじゃないか。"

# カズマ
# お前が街の外壁をぶっ壊してできた借金も――
210 = "お前が街の外壁をぶっ壊してできた借金も――"

# カズマ
# お前っ、ひとりにはっ、背負わせずにっ！\nみんなでっ、仲良くっ、均等にっ、わけただろ？
212 = "お前っ、ひとりにはっ、背負わせずにっ！\\nみんなでっ、仲良くっ、均等にっ、わけただろ？"

# アクア
# う、うぅっ……。
203 = "う、うぅっ……。"

# カズマ
# それじゃあ、アクア。\nいい業者を紹介してくれよ。
224 = "それじゃあ、アクア。\\nいい業者を紹介してくれよ。"

# アクア
# わーかったわよ！　協力するから！\nいいえ、協力させていただきますっ！
252 = "わーかったわよ！　協力するから！\\nいいえ、協力させていただきますっ！"

# カズマ
# わかればいいんだわかれば。
250 = "わかればいいんだわかれば。"

# クリス
# あたし、このパーティーには\n絶対に入りたくないかも。
199 = "あたし、このパーティーには\\n絶対に入りたくないかも。"

# ウィズ
# 同感です。
267 = "同感です。"

