# st01c_06.txt.scn

[info]
117 = "st01c_06"

[characters]
167 = "アクア"
165 = "めぐみん"
172 = "カズマ（Ｍ）"
213 = "遊び人風の男冒険者"
166 = "ゆんゆん"
169 = "アーチャー風の男冒険者"
170 = "ウィズ"
182 = "戦士風の男冒険者"
173 = "クリス"
179 = "商人風の男"
174 = "ダクネス"
185 = "盗賊風の男冒険者"
211 = "聖職者風の男"

[character_subs]
171 = "カズマ"
212 = "遊び人風の男"
180 = "射手冒険者"
181 = "戦士冒険者"
184 = "盗賊冒険者"

[script]
# lines: 41

# アクア
# お帰りなさいませご主人様！
150 = "お帰りなさいませご主人様！"

# めぐみん
# こちらの席へどうぞ。
152 = "こちらの席へどうぞ。"

# カズマ（Ｍ）
# display as カズマ
# （こうして始まったメイド喫茶２日目）
215 = "（こうして始まったメイド喫茶２日目）"

# カズマ（Ｍ）
# display as カズマ
# （新しい料金体系のお知らせを\n　表に貼り出してスタートしたわけだが……）
228 = "（新しい料金体系のお知らせを\\n　表に貼り出してスタートしたわけだが……）"

# カズマ（Ｍ）
# display as カズマ
# （みんなの心配もなんのその、\n　開店と同時に昨日同様の賑わいを見せている）
223 = "（みんなの心配もなんのその、\\n　開店と同時に昨日同様の賑わいを見せている）"

# カズマ（Ｍ）
# display as カズマ
# （いや、むしろ昨日以上の賑わいかもしれない）
214 = "（いや、むしろ昨日以上の賑わいかもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （ちなみに、新しく追加されたことが、\n　どんなふうになっているのかというと）
221 = "（ちなみに、新しく追加されたことが、\\n　どんなふうになっているのかというと）"

# 遊び人風の男冒険者
# display as 遊び人風の男
# ねえ、指名ってどういう意味？
158 = "ねえ、指名ってどういう意味？"

# ゆんゆん
# はい。ご主人様のお世話をさせていただくメイドを\nご主人様自身に選んでいただくサービスだそうです。
161 = "はい。ご主人様のお世話をさせていただくメイドを\\nご主人様自身に選んでいただくサービスだそうです。"

# 遊び人風の男冒険者
# display as 遊び人風の男
# そっか。\nじゃあ、キミにお願いしよっかな。
156 = "そっか。\\nじゃあ、キミにお願いしよっかな。"

# ゆんゆん
# あ……はい。\nではご主人様、こちらへどうぞ。
144 = "あ……はい。\\nではご主人様、こちらへどうぞ。"

# カズマ（Ｍ）
# display as カズマ
# （新しく追加されたのは、メイドの指名制度だ）
229 = "（新しく追加されたのは、メイドの指名制度だ）"

# カズマ（Ｍ）
# display as カズマ
# （初日で客にもメイド喫茶がどういうものか\n　わかっただろうし、好みのメイドも見つかった\n　だろう）
227 = "（初日で客にもメイド喫茶がどういうものか\\n　わかっただろうし、好みのメイドも見つかった\\n　だろう）"

# カズマ（Ｍ）
# display as カズマ
# （だが、普通に入店しただけじゃ、\n　また同じメイドに接客してもらえるとは限らない）
220 = "（だが、普通に入店しただけじゃ、\\n　また同じメイドに接客してもらえるとは限らない）"

# カズマ（Ｍ）
# display as カズマ
# （そこで、自分で選んだメイドに接客を\n　頼めるようにと、指名制度を作ったわけだ）
217 = "（そこで、自分で選んだメイドに接客を\\n　頼めるようにと、指名制度を作ったわけだ）"

# カズマ（Ｍ）
# display as カズマ
# （そして追加されたことはもうひとつある）
218 = "（そして追加されたことはもうひとつある）"

# アーチャー風の男冒険者
# display as 射手冒険者
# これ、頼んだら本当にやってもらえるんですか？
154 = "これ、頼んだら本当にやってもらえるんですか？"

# ウィズ
# は、はい。
159 = "は、はい。"

# アーチャー風の男冒険者
# display as 射手冒険者
# じゃ、じゃあ、ふーふーサービスお願いします。
155 = "じゃ、じゃあ、ふーふーサービスお願いします。"

# ウィズ
# ふー……ふー……。\nはい、ご主人様召し上がれ。
164 = "ふー……ふー……。\\nはい、ご主人様召し上がれ。"

# 戦士風の男冒険者
# display as 戦士冒険者
# この、おまじないサービスお願いします！
153 = "この、おまじないサービスお願いします！"

# クリス
# ええと……。
147 = "ええと……。"

# クリス
# おいしくなーれ♪　もえもえきゅーん♪
149 = "おいしくなーれ♪　もえもえきゅーん♪"

# 商人風の男
# お願いします！　あーんてしてください！
151 = "お願いします！　あーんてしてください！"

# ダクネス
# どうせならちゃんとしたお仕置きが……。
157 = "どうせならちゃんとしたお仕置きが……。"

# 商人風の男
# え？
148 = "え？"

# ダクネス
# い、いや、なんでもない！
145 = "い、いや、なんでもない！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# 罵ってください！
210 = "罵ってください！"

# めぐみん
# 昨日からなんなんですかあなたは！
183 = "昨日からなんなんですかあなたは！"

# めぐみん
# 卑しめられて興奮するなんて、\nどれだけ変態なんですか！
178 = "卑しめられて興奮するなんて、\\nどれだけ変態なんですか！"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# はぁ～ん……。
160 = "はぁ～ん……。"

# 聖職者風の男
# アクア様、どうか一筆お願いします。
168 = "アクア様、どうか一筆お願いします。"

# アクア
# ふっ。芸というのは乞われてするものではないと\nはいえ、求められること自体は悪い気がしないわ。
163 = "ふっ。芸というのは乞われてするものではないと\\nはいえ、求められること自体は悪い気がしないわ。"

# アクア
# いいでしょう。今日は特別に描いてあげるわ。
146 = "いいでしょう。今日は特別に描いてあげるわ。"

# アクア
# はー！
162 = "はー！"

# カズマ（Ｍ）
# display as カズマ
# （まあ、つまり個々のサービスを明確に\n　オプションとして選べるようにしたわけだ）
222 = "（まあ、つまり個々のサービスを明確に\\n　オプションとして選べるようにしたわけだ）"

# カズマ（Ｍ）
# display as カズマ
# （もちろん料金は発生するが、\n　客は躊躇うことなくサービスを求めている）
225 = "（もちろん料金は発生するが、\\n　客は躊躇うことなくサービスを求めている）"

# カズマ（Ｍ）
# display as カズマ
# （むしろ金を払っているのだからと、\n　遠慮なくサービスを要求している感じだ）
224 = "（むしろ金を払っているのだからと、\\n　遠慮なくサービスを要求している感じだ）"

# カズマ（Ｍ）
# display as カズマ
# （これなら想定通り、目標金額達成までの\n　期間を縮められるかもしれない）
216 = "（これなら想定通り、目標金額達成までの\\n　期間を縮められるかもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （だが、これくらいで満足なんてしていられない）
219 = "（だが、これくらいで満足なんてしていられない）"

# カズマ（Ｍ）
# display as カズマ
# （他にもどんどん稼ぐ方法を考えて行ってやるぞ！）
226 = "（他にもどんどん稼ぐ方法を考えて行ってやるぞ！）"

