# st01a_08.txt.scn

[info]
169 = "st01a_08"

[characters]
267 = "カズマ"
269 = "カズマ（Ｍ）"
263 = "アクア"
260 = "めぐみん"
271 = "ダクネス"
270 = "クリス"
261 = "ゆんゆん"
265 = "アクア＆めぐみん＆ダクネス"
266 = "ウィズ"

[character_subs]
# 267 = "カズマ"
337 = "３人"

[script]
# lines: 89

# カズマ
# どうしてこうなった……。
244 = "どうしてこうなった……。"

# カズマ（Ｍ）
# display as カズマ
# （深い深い溜め息を吐きながら、\n　俺はテーブルに突っ伏していた）
334 = "（深い深い溜め息を吐きながら、\\n　俺はテーブルに突っ伏していた）"

# アクア
# おじさーん！\nキンキンに冷えたシュワシュワちょうだーい！
218 = "おじさーん！\\nキンキンに冷えたシュワシュワちょうだーい！"

# カズマ
# お前な！\n金がないのに気軽に注文してるんじゃねー！
220 = "お前な！\\n金がないのに気軽に注文してるんじゃねー！"

# カズマ（Ｍ）
# display as カズマ
# （そう。金がない）
328 = "（そう。金がない）"

# カズマ（Ｍ）
# display as カズマ
# （あれから一ヵ月が経ったというのに、\n　俺たちの手元に数万エリス程度しか\n　蓄えができていないのだ）
325 = "（あれから一ヵ月が経ったというのに、\\n　俺たちの手元に数万エリス程度しか\\n　蓄えができていないのだ）"

# カズマ
# 本当に、どうしてこうなった……。
287 = "本当に、どうしてこうなった……。"

# めぐみん
# どうしても何も、細々と簡単なクエストを\n繰り返していただけなんですから、\nこうなることはわかりきっていたじゃないですか。
245 = "どうしても何も、細々と簡単なクエストを\\n繰り返していただけなんですから、\\nこうなることはわかりきっていたじゃないですか。"

# カズマ
# 細々とじゃなくて、堅実にって言えよ。
321 = "細々とじゃなくて、堅実にって言えよ。"

# ダクネス
# どういう言い方をしたところで、\n結果に変わりはあるまい。
243 = "どういう言い方をしたところで、\\n結果に変わりはあるまい。"

# クリス
# まあ、あたしたちも途中から、\nちょっと気が抜けてたしね。
255 = "まあ、あたしたちも途中から、\\nちょっと気が抜けてたしね。"

# ゆんゆん
# 満月の日以来、\n本当に何も起きませんでしたからね。
289 = "満月の日以来、\\n本当に何も起きませんでしたからね。"

# カズマ
# だが今日の夜は、その問題の満月だ。
239 = "だが今日の夜は、その問題の満月だ。"

# アクア＆めぐみん＆ダクネス
# display as ３人
# …………。
200 = "…………。"

# カズマ
# こうなったら本当に借金をしてでも。
222 = "こうなったら本当に借金をしてでも。"

# カズマ
# と思ったのに、\nバニルのやつはどうしたんだウィズ！
241 = "と思ったのに、\\nバニルのやつはどうしたんだウィズ！"

# ウィズ
# す、すみません！　まだ戻って来てないですー！
228 = "す、すみません！　まだ戻って来てないですー！"

# カズマ
# あのやろう！　やっぱりわざと姿を消してるんだろ！
206 = "あのやろう！　やっぱりわざと姿を消してるんだろ！"

# クリス
# まあまあ、落ち着きなって。
258 = "まあまあ、落ち着きなって。"

# ゆんゆん
# そうですよ。\nウィズさんに怒っても仕方ないじゃないですか。
231 = "そうですよ。\\nウィズさんに怒っても仕方ないじゃないですか。"

# カズマ
# あ、すまん。\n今のはウィズに言ったわけじゃなくて。
202 = "あ、すまん。\\n今のはウィズに言ったわけじゃなくて。"

# ウィズ
# 大丈夫ですよ。わかってますから。
279 = "大丈夫ですよ。わかってますから。"

# カズマ
# それより今夜をどうするかだが――
236 = "それより今夜をどうするかだが――"

# ダクネス
# 屋敷中に下着をバラまいておけば、\n私たちの付けている物を直接脱がされる\n確率は減るのではないか？
282 = "屋敷中に下着をバラまいておけば、\\n私たちの付けている物を直接脱がされる\\n確率は減るのではないか？"

# めぐみん
# それじゃ誰かの下着が盗られることに変わりない\nじゃないですか。
234 = "それじゃ誰かの下着が盗られることに変わりない\\nじゃないですか。"

# めぐみん
# 私としては、確実にパンツが盗まれない方法を\n確立したいところです！
320 = "私としては、確実にパンツが盗まれない方法を\\n確立したいところです！"

# カズマ
# さすが犠牲者、言葉が重い。
224 = "さすが犠牲者、言葉が重い。"

# めぐみん
# あんな思いは、もう二度としたく\nありませんからね。
208 = "あんな思いは、もう二度としたく\\nありませんからね。"

# ゆんゆん
# そ、そうだよね。\n下着を着けられなくなるなんて、\n考えただけでゾっとするもの。
229 = "そ、そうだよね。\\n下着を着けられなくなるなんて、\\n考えただけでゾっとするもの。"

# めぐみん
# あんな屈辱、２度とごめんです！
207 = "あんな屈辱、２度とごめんです！"

# ダクネス
# うーん、確実に盗まれない方法か。
212 = "うーん、確実に盗まれない方法か。"

# めぐみん
# 寝る前にカズマを縛っておくのはどうです？
281 = "寝る前にカズマを縛っておくのはどうです？"

# アクア
# そんなことより、\nすぱーっと物理的に元を絶っちゃいましょうよ。
237 = "そんなことより、\\nすぱーっと物理的に元を絶っちゃいましょうよ。"

# カズマ
# お前はそればっかりだな！
221 = "お前はそればっかりだな！"

# クリス
# あ、あのさ、さすがにそれは、\n本当にどうしようもなくなった時の\n最終手段にしときなよ。
201 = "あ、あのさ、さすがにそれは、\\n本当にどうしようもなくなった時の\\n最終手段にしときなよ。"

# ゆんゆん
# そうですよ。\n指を切るなんて、そんな痛そうなこと。
232 = "そうですよ。\\n指を切るなんて、そんな痛そうなこと。"

# アクア
# じゃあどうしろっていうんですかー？
225 = "じゃあどうしろっていうんですかー？"

# ウィズ
# あの、カズマさんから距離を取ってみる\nというのはどうでしょうか。
205 = "あの、カズマさんから距離を取ってみる\\nというのはどうでしょうか。"

# ダクネス
# 距離を取る？
324 = "距離を取る？"

# めぐみん
# なるほど。カズマの手の届かない所にいれば、\n下着を盗られようがないというわけですね。
249 = "なるほど。カズマの手の届かない所にいれば、\\n下着を盗られようがないというわけですね。"

# アクア
# 言われてみれば、確かにそうね。\nなんでそんな簡単なこと思いつかなかったのかしら。
323 = "言われてみれば、確かにそうね。\\nなんでそんな簡単なこと思いつかなかったのかしら。"

# アクア
# じゃあカズマ、\n私たち今夜は他のトコに泊まることにするわ。
226 = "じゃあカズマ、\\n私たち今夜は他のトコに泊まることにするわ。"

# カズマ
# え？
215 = "え？"

# めぐみん
# これで安心して今夜は眠れそうですね。
223 = "これで安心して今夜は眠れそうですね。"

# カズマ
# いや、あの……。
210 = "いや、あの……。"

# ダクネス
# 下着を盗みに来るかもしれないカズマを待ちつつ、\n眠れぬ夜を過ごすというのも捨てがたいが、\n今日のところはみんなと行動を共にするとしよう。
272 = "下着を盗みに来るかもしれないカズマを待ちつつ、\\n眠れぬ夜を過ごすというのも捨てがたいが、\\n今日のところはみんなと行動を共にするとしよう。"

# カズマ
# ええと……。
214 = "ええと……。"

# カズマ
# じゃあ今夜はあの広い屋敷に俺１人ってことか？\nそれはちょっと寂しいというか……。
227 = "じゃあ今夜はあの広い屋敷に俺１人ってことか？\\nそれはちょっと寂しいというか……。"

# アクア
# カズマってばなに殊勝なこと言っちゃってるわけ？\nそういうの似合わないんですけどー。
268 = "カズマってばなに殊勝なこと言っちゃってるわけ？\\nそういうの似合わないんですけどー。"

# カズマ
# おまっ！
219 = "おまっ！"

# カズマ（Ｍ）
# display as カズマ
# （人が珍しく素直な気持ちを\n　口に出してやったというのに、こいつは……）
333 = "（人が珍しく素直な気持ちを\\n　口に出してやったというのに、こいつは……）"

# カズマ
# ふん。好きにすればいいさ。\n俺は１人でのんびりさせてもらうからな！
252 = "ふん。好きにすればいいさ。\\n俺は１人でのんびりさせてもらうからな！"

# めぐみん
# そんなふうに意地を張らずに、\n寂しいなら寂しいと言えばいいものを。
238 = "そんなふうに意地を張らずに、\\n寂しいなら寂しいと言えばいいものを。"

# カズマ
# な、何言ってるんだよ。別に寂しくなんかねーし！
248 = "な、何言ってるんだよ。別に寂しくなんかねーし！"

# カズマ（Ｍ）
# display as カズマ
# （そりゃあ、あれだけ広い屋敷に１人ってのは、\n　少し心細くはあるけど……）
329 = "（そりゃあ、あれだけ広い屋敷に１人ってのは、\\n　少し心細くはあるけど……）"

# カズマ（Ｍ）
# display as カズマ
# （こいつらが屋敷にいないっていうなら、\n　いろいろやりたい放題だな）
326 = "（こいつらが屋敷にいないっていうなら、\\n　いろいろやりたい放題だな）"

# カズマ（Ｍ）
# display as カズマ
# （これでも一応、\n　普段は気を遣ってやってるんだぞ？）
327 = "（これでも一応、\\n　普段は気を遣ってやってるんだぞ？）"

# カズマ（Ｍ）
# display as カズマ
# （風呂上りにパンツ一丁でいたりもできないし、\n　他にもデリケートがことが山ほど……）
336 = "（風呂上りにパンツ一丁でいたりもできないし、\\n　他にもデリケートがことが山ほど……）"

# ダクネス
# おいカズマ。\n少しは寂しがったりしたらどうなんだ？
217 = "おいカズマ。\\n少しは寂しがったりしたらどうなんだ？"

# カズマ
# え？　いや、別に寂しくないし。
216 = "え？　いや、別に寂しくないし。"

# カズマ（Ｍ）
# display as カズマ
# （は！？　待てよ。\n　今夜、屋敷に１人きりということは……）
332 = "（は！？　待てよ。\\n　今夜、屋敷に１人きりということは……）"

# カズマ（Ｍ）
# display as カズマ
# （誰にも邪魔されずサキュバスの子を呼ぶ\n　最大のチャンスなんじゃないか！？）
335 = "（誰にも邪魔されずサキュバスの子を呼ぶ\\n　最大のチャンスなんじゃないか！？）"

# カズマ
# よっしゃー！
262 = "よっしゃー！"

# アクア
# 何よいきなり大きな声なんか出して？
274 = "何よいきなり大きな声なんか出して？"

# カズマ
# な、なんでもないよ。
247 = "な、なんでもないよ。"

# カズマ
# あー、そんなことより、\nお前らは本当に薄情なやつらだな。
209 = "あー、そんなことより、\\nお前らは本当に薄情なやつらだな。"

# カズマ
# まあいいさ。\nどこかに行くならさっさと行っちまえ。
257 = "まあいいさ。\\nどこかに行くならさっさと行っちまえ。"

# アクア
# 行けって言われても、\nまだ泊まる場所なんて決めてないし、\n夜までまだ時間もあるし。
322 = "行けって言われても、\\nまだ泊まる場所なんて決めてないし、\\n夜までまだ時間もあるし。"

# カズマ
# 悠長なこと言ってて大丈夫なのか？\n指輪の力が発動するのが夜だけとは限らないぞ？
285 = "悠長なこと言ってて大丈夫なのか？\\n指輪の力が発動するのが夜だけとは限らないぞ？"

# クリス
# ええ、そうなの！？
213 = "ええ、そうなの！？"

# ウィズ
# どうなんでしょう？\nその辺のことは私にはなんとも。
246 = "どうなんでしょう？\\nその辺のことは私にはなんとも。"

# めぐみん
# まあ、用心するに越したことはなさそうですね。
256 = "まあ、用心するに越したことはなさそうですね。"

# ダクネス
# 出かける準備もあるわけだし、\n今のうちに屋敷に戻っておくのもいいだろう。
275 = "出かける準備もあるわけだし、\\n今のうちに屋敷に戻っておくのもいいだろう。"

# アクア
# あっ、カズマは少し時間をつぶしてから\n戻りなさいよ。
203 = "あっ、カズマは少し時間をつぶしてから\\n戻りなさいよ。"

# カズマ
# へいへい。
253 = "へいへい。"

# カズマ（Ｍ）
# display as カズマ
# （ちょうどいい。\n　こいつらの姿が見えなくなったら、\n　さっそくサキュバスさんたちのお店に――）
330 = "（ちょうどいい。\\n　こいつらの姿が見えなくなったら、\\n　さっそくサキュバスさんたちのお店に――）"

# アクア
# そうそう。\n夜は１人でも心配いらないようにしとくからね。
230 = "そうそう。\\n夜は１人でも心配いらないようにしとくからね。"

# カズマ
# どういう意味だ？
242 = "どういう意味だ？"

# アクア
# ほら、前にサキュバスが\n屋敷に忍び込んで来たことがあったでしょう？
254 = "ほら、前にサキュバスが\\n屋敷に忍び込んで来たことがあったでしょう？"

# アクア
# またあんなことがあったら大変だから、\n出かける前に結界を強化しておくわ。
259 = "またあんなことがあったら大変だから、\\n出かける前に結界を強化しておくわ。"

# カズマ
# は？
250 = "は？"

# アクア
# ふふ。私ってば気が利く女神よね。\nいいのよ？　感謝して好きなだけ崇め奉っても。
251 = "ふふ。私ってば気が利く女神よね。\\nいいのよ？　感謝して好きなだけ崇め奉っても。"

# めぐみん
# アクア、何をしてるんです？
264 = "アクア、何をしてるんです？"

# ダクネス
# 早く来ないと置いて行くぞ？
286 = "早く来ないと置いて行くぞ？"

# アクア
# あっ、待ってよー！
204 = "あっ、待ってよー！"

# クリス
# それじゃあたしもそろそろ行くね。
233 = "それじゃあたしもそろそろ行くね。"

# ゆんゆん
# 夜、何も起きないといいですね。
278 = "夜、何も起きないといいですね。"

# ウィズ
# では失礼します。
240 = "では失礼します。"

# カズマ（Ｍ）
# display as カズマ
# （どうしてこうなった……本当に、どうして）
331 = "（どうしてこうなった……本当に、どうして）"

[selections]
235 = "それはちょっと寂しい"
280 = "好きにすればいいさ"
211 = "いろいろやりたい放題だな"
