# st01a_06.txt.scn

[info]
147 = "st01a_06"

[characters]
203 = "アクア"
207 = "カズマ"
212 = "ダクネス"
204 = "ウィズ"
210 = "クリス"
209 = "カズマ（Ｍ）"
196 = "めぐみん"
200 = "ゆんゆん"
197 = "めぐみん＆ダクネス"

[character_subs]
# 207 = "カズマ"
269 = "２人"

[script]
# lines: 54

# アクア
# 何よ急に真面目な顔しちゃって。
221 = "何よ急に真面目な顔しちゃって。"

# カズマ
# ええと、今回はこんなことになっちまったが、\nこれ以上被害を出さないためにも、一刻も早く\nこの指輪をどうにかしたいと俺は思ってる。
177 = "ええと、今回はこんなことになっちまったが、\\nこれ以上被害を出さないためにも、一刻も早く\\nこの指輪をどうにかしたいと俺は思ってる。"

# カズマ
# ウィズを信じるなら、バニルだって\nそう遠くないうちに戻って来るだろうし。
206 = "ウィズを信じるなら、バニルだって\\nそう遠くないうちに戻って来るだろうし。"

# カズマ
# だからその時までに、なんとか金を貯めて\nおきたいんだ。
186 = "だからその時までに、なんとか金を貯めて\\nおきたいんだ。"

# カズマ
# 頼む、みんなの知恵を貸してくれ！
266 = "頼む、みんなの知恵を貸してくれ！"

# ダクネス
# つまり、金を稼ぐための手段を考えて欲しいと、\nそういうわけだな？
189 = "つまり、金を稼ぐための手段を考えて欲しいと、\\nそういうわけだな？"

# カズマ
# ああ、そういうことだ。
171 = "ああ、そういうことだ。"

# ウィズ
# やはり地道に働く他にないと思うのですが？
199 = "やはり地道に働く他にないと思うのですが？"

# カズマ
# それはもちろんわかってるさ。
182 = "それはもちろんわかってるさ。"

# カズマ
# その上で、短時間で稼げる方法がないかって\n話なわけで……。
180 = "その上で、短時間で稼げる方法がないかって\\n話なわけで……。"

# ウィズ
# 値段が値段ですもんね。
223 = "値段が値段ですもんね。"

# クリス
# だったらやっぱ、\n定番のあれが一番なんじゃない？
188 = "だったらやっぱ、\\n定番のあれが一番なんじゃない？"

# カズマ
# あれって？
174 = "あれって？"

# クリス
# 一攫千金のお宝探しだよ。
214 = "一攫千金のお宝探しだよ。"

# クリス
# 実はさ、まだあんまり広まってないけど、\nこの近くで新しいダンジョンが見つかった\nらしいんだ。
226 = "実はさ、まだあんまり広まってないけど、\\nこの近くで新しいダンジョンが見つかった\\nらしいんだ。"

# クリス
# で、そのダンジョンが、この辺りにしては\nずいぶんな難易度らしくて、まだ最下層まで\n踏破されてないんだって。
190 = "で、そのダンジョンが、この辺りにしては\\nずいぶんな難易度らしくて、まだ最下層まで\\n踏破されてないんだって。"

# クリス
# だからさ、そこを狙ってみるのはどうかな？\n今なら思いもよらないお宝が手に入るかも\nしれないよ？
185 = "だからさ、そこを狙ってみるのはどうかな？\\n今なら思いもよらないお宝が手に入るかも\\nしれないよ？"

# カズマ（Ｍ）
# display as カズマ
# （なるほど、ダンジョンか）
268 = "（なるほど、ダンジョンか）"

# めぐみん
# 待ってください。\nダンジョンの中では爆裂魔法が使えないじゃ\nないですか。
229 = "待ってください。\\nダンジョンの中では爆裂魔法が使えないじゃ\\nないですか。"

# カズマ
# 爆裂魔法を基準に考えるのはやめろ！
237 = "爆裂魔法を基準に考えるのはやめろ！"

# めぐみん
# どうせ一攫千金を狙うなら、\n高レベルのモンスターを倒しに行きましょう！
193 = "どうせ一攫千金を狙うなら、\\n高レベルのモンスターを倒しに行きましょう！"

# ダクネス
# うむ、そうだな。\n私もどちらかというとめぐみんの案に賛成だ。
175 = "うむ、そうだな。\\n私もどちらかというとめぐみんの案に賛成だ。"

# ダクネス
# ダンジョンの中で罠にかかっていたぶられるのも\n悪くはないが、やはり屈強なモンスターの一撃を\nこの身で受け止める方が好まし――
213 = "ダンジョンの中で罠にかかっていたぶられるのも\\n悪くはないが、やはり屈強なモンスターの一撃を\\nこの身で受け止める方が好まし――"

# カズマ
# 他に何かないか？
216 = "他に何かないか？"

# ダクネス
# んん！　華麗に受け流すとはさすがカズマ。
202 = "んん！　華麗に受け流すとはさすがカズマ。"

# ウィズ
# あの、一攫千金とはいきませんが、\n何か値打ちのある物を探してきて、\nウチの店で売るというのはどうですか？
172 = "あの、一攫千金とはいきませんが、\\n何か値打ちのある物を探してきて、\\nウチの店で売るというのはどうですか？"

# カズマ
# 値打ちのある物って、例えば？
222 = "値打ちのある物って、例えば？"

# ウィズ
# そうですね。\n保存状態の良い骨董品などが\n高値でよく売れているという話を聞きますよ。
179 = "そうですね。\\n保存状態の良い骨董品などが\\n高値でよく売れているという話を聞きますよ。"

# カズマ
# 骨董品か。
267 = "骨董品か。"

# ゆんゆん
# カズマさん、相づちばかりじゃなくて、\n何か言ってくださいよ。\nみんなでこんなにアイデアを出してるんですから。
208 = "カズマさん、相づちばかりじゃなくて、\\n何か言ってくださいよ。\\nみんなでこんなにアイデアを出してるんですから。"

# カズマ
# うーん……。
176 = "うーん……。"

# カズマ
# どの意見も、悪くはないと思うぞ。
194 = "どの意見も、悪くはないと思うぞ。"

# アクア
# 何その上から目線の言い方は。\nアイデア出してもらっといて何様のつもり？
218 = "何その上から目線の言い方は。\\nアイデア出してもらっといて何様のつもり？"

# カズマ
# あのな、これでも頼んでる側だから、\nツッコミを入れたいのを我慢してやってるんだぞ。
173 = "あのな、これでも頼んでる側だから、\\nツッコミを入れたいのを我慢してやってるんだぞ。"

# めぐみん
# 我慢しているとは聞き捨てなりませんね。\nいったいどこにツッコミ所があったと言うんです？
231 = "我慢しているとは聞き捨てなりませんね。\\nいったいどこにツッコミ所があったと言うんです？"

# カズマ
# じゃあ言わせてもらうけどな……。
178 = "じゃあ言わせてもらうけどな……。"

# カズマ
# クリスやウィズはともかく、めぐみんとダクネス、\nお前らが言ってることはいつもと同じじゃねーか！
211 = "クリスやウィズはともかく、めぐみんとダクネス、\\nお前らが言ってることはいつもと同じじゃねーか！"

# めぐみん＆ダクネス
# display as ２人
# な！？
195 = "な！？"

# カズマ
# 爆裂魔法が撃ちたいとか、\n屈強なモンスターと戦いたいとか、\n普段のお前らの欲望そのままだろ。
236 = "爆裂魔法が撃ちたいとか、\\n屈強なモンスターと戦いたいとか、\\n普段のお前らの欲望そのままだろ。"

# めぐみん
# それはそうかもしれませんが、\n効率が良いことは確かですし。
181 = "それはそうかもしれませんが、\\n効率が良いことは確かですし。"

# ダクネス
# 文句を言うなら、\nお前も何かアイデアを出してみせろ。
232 = "文句を言うなら、\\nお前も何かアイデアを出してみせろ。"

# カズマ
# 何も思いつかないから、\n文句も言わずに黙っててやってたんだろうが。
220 = "何も思いつかないから、\\n文句も言わずに黙っててやってたんだろうが。"

# カズマ
# 無理なことばっか言いやがって。
235 = "無理なことばっか言いやがって。"

# アクア
# 何が無理だっていうのよ？
217 = "何が無理だっていうのよ？"

# カズマ
# 何もかも全部だよ。
219 = "何もかも全部だよ。"

# カズマ
# 踏破されてないダンジョン？\n高レベルのモンスター？\nそんなの俺たちにどうにかできるわけないだろ。
265 = "踏破されてないダンジョン？\\n高レベルのモンスター？\\nそんなの俺たちにどうにかできるわけないだろ。"

# カズマ
# ウィズのは売り物を探すハードルが高いし。
205 = "ウィズのは売り物を探すハードルが高いし。"

# めぐみん
# そんなことを言っていたら\n何もできないじゃないですか。
183 = "そんなことを言っていたら\\n何もできないじゃないですか。"

# カズマ
# わかってるよ。だから俺も、\nみんなの話を聞きながら黙って考えてたんだろ。
201 = "わかってるよ。だから俺も、\\nみんなの話を聞きながら黙って考えてたんだろ。"

# ダクネス
# で、何か考えついたのか？
191 = "で、何か考えついたのか？"

# カズマ
# だったらこんなに悩んでねーよ。
187 = "だったらこんなに悩んでねーよ。"

# アクア
# もうさ、私がギャンブルでもして\nぱぱーっと稼いで来てあげようか？\nあ、もちろん元手はカズマが出してね。
198 = "もうさ、私がギャンブルでもして\\nぱぱーっと稼いで来てあげようか？\\nあ、もちろん元手はカズマが出してね。"

# カズマ
# そんな金をドブに捨てるようなマネ誰がするか！
184 = "そんな金をドブに捨てるようなマネ誰がするか！"

# アクア
# どういう意味よー！
192 = "どういう意味よー！"

[selections]
230 = "悪くはないと思うぞ"
234 = "無理なことばっか言いやがって"
