# st02c_06.txt.scn

[info]
0 = ""

[characters]
290 = "カズマ"
296 = "カズマ（Ｍ）"
287 = "アクア"
282 = "めぐみん"
300 = "ダクネス"
283 = "ゆんゆん"
289 = "ウィズ"
297 = "クリス"

[character_subs]
# 290 = "カズマ"

[script]
# lines: 149

# カズマ
# はぁっはぁっ。\nトップの集団とだいぶ差が縮まったな。
269 = "はぁっはぁっ。\\nトップの集団とだいぶ差が縮まったな。"

# カズマ（Ｍ）
# display as カズマ
# （しかし、駆け出しと行ってもさすが冒険者だ）
380 = "（しかし、駆け出しと行ってもさすが冒険者だ）"

# カズマ（Ｍ）
# display as カズマ
# （トップ集団にいるということは、\n　それなりに飛ばして走って来たはずなのに\n　ちっともペースが落ちない）
384 = "（トップ集団にいるということは、\\n　それなりに飛ばして走って来たはずなのに\\n　ちっともペースが落ちない）"

# アクア
# カズマ、遅いわよ。
293 = "カズマ、遅いわよ。"

# カズマ
# お前、どうして戻ってくるんだよ！
213 = "お前、どうして戻ってくるんだよ！"

# アクア
# だって、ひとりで泳いでてもつまらないんですもの。
246 = "だって、ひとりで泳いでてもつまらないんですもの。"

# カズマ
# つまらないってお前な――
253 = "つまらないってお前な――"

# カズマ
# この大会は全員の合計タイムで優勝が\n決まるんだぞ。
229 = "この大会は全員の合計タイムで優勝が\\n決まるんだぞ。"

# カズマ
# アクアが早くゴールすればするほど、\n優勝に近づけるんだ！
288 = "アクアが早くゴールすればするほど、\\n優勝に近づけるんだ！"

# カズマ
# そこんとこ、わかってるのか！
238 = "そこんとこ、わかってるのか！"

# アクア
# 当然じゃない。
318 = "当然じゃない。"

# カズマ
# だったら戻ってくるなよ！　先に行けって！\nお前だって優勝賞金が欲しいんだろうが！
245 = "だったら戻ってくるなよ！　先に行けって！\\nお前だって優勝賞金が欲しいんだろうが！"

# アクア
# あのね、私は水の女神なのよ。\n本気を出せば、この程度の広さの湖くらい\nひとかきで泳げちゃうんだからね。
196 = "あのね、私は水の女神なのよ。\\n本気を出せば、この程度の広さの湖くらい\\nひとかきで泳げちゃうんだからね。"

# カズマ
# お前、もしかして、わざと俺たちのペースに\n合わせて泳いでるのか？
214 = "お前、もしかして、わざと俺たちのペースに\\n合わせて泳いでるのか？"

# アクア
# うん、そうだけど？
206 = "うん、そうだけど？"

# カズマ
# なんで。
264 = "なんで。"

# アクア
# ひとりじゃつまらないから。
274 = "ひとりじゃつまらないから。"

# カズマ
# どんだけ寂しがり屋さんなんだよ！
260 = "どんだけ寂しがり屋さんなんだよ！"

# カズマ（Ｍ）
# display as カズマ
# （くそ、こっちはいっぱいいっぱいで\n　泳いでるってのに、余裕顔しやがって）
378 = "（くそ、こっちはいっぱいいっぱいで\\n　泳いでるってのに、余裕顔しやがって）"

# カズマ（Ｍ）
# display as カズマ
# （ん？）
383 = "（ん？）"

# カズマ（Ｍ）
# display as カズマ
# （てか、なんで息一つきれてないんだ？）
381 = "（てか、なんで息一つきれてないんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （いくら女神だからって、\n　体を動かせば疲れがたまるだろう）
377 = "（いくら女神だからって、\\n　体を動かせば疲れがたまるだろう）"

# カズマ（Ｍ）
# display as カズマ
# （実際、陸を走ってるときは顔を真っ青にして\n　ヒーヒー言ってたし……）
387 = "（実際、陸を走ってるときは顔を真っ青にして\\n　ヒーヒー言ってたし……）"

# アクア
# 何よ、ジロジロ見て。\nまさか、女神の私でいやらしい想像を！
307 = "何よ、ジロジロ見て。\\nまさか、女神の私でいやらしい想像を！"

# カズマ（Ｍ）
# display as カズマ
# （今だってそうだ。\n　後ずさる動きがスムーズすぎる）
385 = "（今だってそうだ。\\n　後ずさる動きがスムーズすぎる）"

# カズマ（Ｍ）
# display as カズマ
# （体を動かしているように、\n　ちっとも見えないし……）
386 = "（体を動かしているように、\\n　ちっとも見えないし……）"

# カズマ（Ｍ）
# display as カズマ
# （こいつまさか……）
379 = "（こいつまさか……）"

# カズマ
# おい、水の女神。
210 = "おい、水の女神。"

# アクア
# 何よ。
308 = "何よ。"

# カズマ
# ちょっと直立に立ってみろ。
251 = "ちょっと直立に立ってみろ。"

# アクア
# 直立って、こう？
370 = "直立って、こう？"

# カズマ
# 微動だにしないな。
320 = "微動だにしないな。"

# アクア
# それはそうよ。\n水で支えてるもん。
242 = "それはそうよ。\\n水で支えてるもん。"

# カズマ（Ｍ）
# display as カズマ
# （水で支えるとかわけわかんねー）
388 = "（水で支えるとかわけわかんねー）"

# カズマ
# よしじゃあ、そのまま動いてみてくれ。
284 = "よしじゃあ、そのまま動いてみてくれ。"

# アクア
# なんなのよ、さっきから。
265 = "なんなのよ、さっきから。"

# カズマ
# 気持ち悪っ！　何その移動！
323 = "気持ち悪っ！　何その移動！"

# アクア
# はぁ？\nあんたがやれって言ったんじゃない！
270 = "はぁ？\\nあんたがやれって言ったんじゃない！"

# カズマ
# つまり、お前はあれか――
255 = "つまり、お前はあれか――"

# カズマ
# 水を操ってる。そういうわけだな？
324 = "水を操ってる。そういうわけだな？"

# アクア
# 当然じゃない。
# 318 = "当然じゃない。"

# カズマ
# 汚ぇ！　そんなのズルじゃねえか！
326 = "汚ぇ！　そんなのズルじゃねえか！"

# アクア
# ズルなんかじゃないわよ。\n水を操ってるのは私の力なんだもの。\nちゃんと自分の力で泳いでることになるじゃない。
299 = "ズルなんかじゃないわよ。\\n水を操ってるのは私の力なんだもの。\\nちゃんと自分の力で泳いでることになるじゃない。"

# アクア
# それとも、ルールで自分の力を使うのは\n禁止されてるの？
241 = "それとも、ルールで自分の力を使うのは\\n禁止されてるの？"

# カズマ（Ｍ）
# display as カズマ
# （確かにアクアは自分自身の力で泳いでるわけだし、\n　ルール的には問題はないはずだ）
389 = "（確かにアクアは自分自身の力で泳いでるわけだし、\\n　ルール的には問題はないはずだ）"

# カズマ（Ｍ）
# display as カズマ
# （魔法等の使用を禁止するとは聞いてないし）
391 = "（魔法等の使用を禁止するとは聞いてないし）"

# カズマ（Ｍ）
# display as カズマ
# （でも、なんか納得いかないよな、こういうの）
382 = "（でも、なんか納得いかないよな、こういうの）"

# アクア
# ねえカズマ、\nみんなもだいぶ追いついて来たみたいよ？
268 = "ねえカズマ、\\nみんなもだいぶ追いついて来たみたいよ？"

# カズマ
# うん、この調子なら心配なさそうだし、\n俺たちは先にゴールして少しでもタイムを縮めるか。
205 = "うん、この調子なら心配なさそうだし、\\n俺たちは先にゴールして少しでもタイムを縮めるか。"

# アクア
# ねえねえ、カズマ。\nもし優勝したら、私の貢献度はそうとうなものだと\n思わない？
267 = "ねえねえ、カズマ。\\nもし優勝したら、私の貢献度はそうとうなものだと\\n思わない？"

# カズマ
# 確かにそうだな。\nお前は間違いなくこのチームのエースなわけだし。
372 = "確かにそうだな。\\nお前は間違いなくこのチームのエースなわけだし。"

# アクア
# だったらさ、均等に賞金を分けるのは不平等だと\n思うのよね。
244 = "だったらさ、均等に賞金を分けるのは不平等だと\\n思うのよね。"

# カズマ
# 何が言いたい……。
306 = "何が言いたい……。"

# アクア
# ええとね？　私が、６割？　ううん、７割貰っても\n罰は当たらないと思うんだけど。\nカズマはどう思う？
208 = "ええとね？　私が、６割？　ううん、７割貰っても\\n罰は当たらないと思うんだけど。\\nカズマはどう思う？"

# カズマ
# お前は本当に強欲だなって思う。
217 = "お前は本当に強欲だなって思う。"

# アクア
# うわあああん、カズマー！\n酒場のツケが貯まりすぎたせいで、\n注文しても料理を出してくれないの！
204 = "うわあああん、カズマー！\\n酒場のツケが貯まりすぎたせいで、\\n注文しても料理を出してくれないの！"

# アクア
# カズマが払うって言っても信じてくれないし！
294 = "カズマが払うって言っても信じてくれないし！"

# カズマ
# お前、人に借金を背負わせるつもりだったのか！
215 = "お前、人に借金を背負わせるつもりだったのか！"

# アクア
# 私はもっとシュワシュワを飲みたいの！\n好き勝手に飲み食いしたいの！
373 = "私はもっとシュワシュワを飲みたいの！\\n好き勝手に飲み食いしたいの！"

# アクア
# ねえお願いだから、賞金の８割は私にちょうだい！
266 = "ねえお願いだから、賞金の８割は私にちょうだい！"

# カズマ
# こっそり１割増やすな！
228 = "こっそり１割増やすな！"

# アクア
# それだけお金があれば酒場のツケだけじゃなくて、\n色々な借金を返せるのよー。
240 = "それだけお金があれば酒場のツケだけじゃなくて、\\n色々な借金を返せるのよー。"

# カズマ（Ｍ）
# display as カズマ
# （色々って……）
390 = "（色々って……）"

# アクア
# カズマ、一生のお願いだからー！
292 = "カズマ、一生のお願いだからー！"

# カズマ
# ああ、もう、鬱陶しい！　くっつくな！
190 = "ああ、もう、鬱陶しい！　くっつくな！"

# アクア
# きゃあ！？
222 = "きゃあ！？"

# カズマ
# おい、どうした？
209 = "おい、どうした？"

# アクア
# ど、どど、どうしたじゃないわよ！\nこんな時に何考えてるのよあんたは！\n今、私の水着を脱がそうとしたでしょ！
258 = "ど、どど、どうしたじゃないわよ！\\nこんな時に何考えてるのよあんたは！\\n今、私の水着を脱がそうとしたでしょ！"

# カズマ
# は？　そんなことするわけないだろ？
271 = "は？　そんなことするわけないだろ？"

# アクア
# とぼけないでよ！\n水着の紐を引っぱったじゃない！\nほどけちゃったらどうするつもりだったのよ！
257 = "とぼけないでよ！\\n水着の紐を引っぱったじゃない！\\nほどけちゃったらどうするつもりだったのよ！"

# カズマ
# いや、俺じゃないって。
199 = "いや、俺じゃないって。"

# めぐみん
# ふぅっ……っ……はぁっ……\nこんな所で、何を騒いでいるんです？
277 = "ふぅっ……っ……はぁっ……\\nこんな所で、何を騒いでいるんです？"

# ダクネス
# ケンカなら……陸に上がってからにしろ。\n溺れても知らんぞ……。
298 = "ケンカなら……陸に上がってからにしろ。\\n溺れても知らんぞ……。"

# カズマ
# それが、俺にも訳がわからなくてさ。
239 = "それが、俺にも訳がわからなくてさ。"

# アクア
# だから今、カズマが――
243 = "だから今、カズマが――"

# ゆんゆん
# ひゃあ！？　水着が！
275 = "ひゃあ！？　水着が！"

# ウィズ
# ああ！　まさか、またカズマさんですか！？
191 = "ああ！　まさか、またカズマさんですか！？"

# クリス
# ちょっとキミ、状況を考えてよ。
250 = "ちょっとキミ、状況を考えてよ。"

# カズマ
# 落ち着けって！\n俺の手がそんなに伸びるわけないだろ！
374 = "落ち着けって！\\n俺の手がそんなに伸びるわけないだろ！"

# めぐみん
# 待ってください。今、何か見えたような。
319 = "待ってください。今、何か見えたような。"

# ダクネス
# む！　あの影は！
281 = "む！　あの影は！"

# アクア
# ひいいいい！　ワニよ！　ワニだわあれ！！
272 = "ひいいいい！　ワニよ！　ワニだわあれ！！"

# めぐみん
# そうですね、確かにブルータルアリゲーターの\nようです。
236 = "そうですね、確かにブルータルアリゲーターの\\nようです。"

# ダクネス
# あの影形、間違いないだろう。
197 = "あの影形、間違いないだろう。"

# ゆんゆん
# で、でも……。
256 = "で、でも……。"

# クリス
# 小さいね。
314 = "小さいね。"

# ダクネス
# 小さいな。
313 = "小さいな。"

# めぐみん
# ええ、小さいです。
207 = "ええ、小さいです。"

# カズマ
# 手乗りサイズだな。
322 = "手乗りサイズだな。"

# ウィズ
# きっと生まれたてなんでしょう。
220 = "きっと生まれたてなんでしょう。"

# アクア
# かじゅま、かじゅまぁぁ！\n助けてぇぇぇぇ！！
219 = "かじゅま、かじゅまぁぁ！\\n助けてぇぇぇぇ！！"

# カズマ
# あー、もう、落ちつけ！\nあんなちびっこいやつに、水の女神が怯えて\nどうするんだ！
198 = "あー、もう、落ちつけ！\\nあんなちびっこいやつに、水の女神が怯えて\\nどうするんだ！"

# アクア
# そ、そうは言うけど。
234 = "そ、そうは言うけど。"

# ウィズ
# あの、カズマさん。\n油断はしない方がいいですよ？
195 = "あの、カズマさん。\\n油断はしない方がいいですよ？"

# カズマ
# どういうことだ？
259 = "どういうことだ？"

# ウィズ
# 幼いといっても、あのどう猛な\nブルータルアリゲーターなのですから。
317 = "幼いといっても、あのどう猛な\\nブルータルアリゲーターなのですから。"

# ウィズ
# おそらく、木を噛み切るほどの顎の力は\n持っているかと。
211 = "おそらく、木を噛み切るほどの顎の力は\\n持っているかと。"

# アクア
# ひっ！？\nいやぁぁぁぁあああ！
273 = "ひっ！？\\nいやぁぁぁぁあああ！"

# カズマ
# わざわざアクアを怖がらせるようなことを\n言ってどうすんだよ！
286 = "わざわざアクアを怖がらせるようなことを\\n言ってどうすんだよ！"

# ウィズ
# あっ、すみません！
193 = "あっ、すみません！"

# アクア
# かじゅま、かじゅま、かじゅまさぁぁぁん！
218 = "かじゅま、かじゅま、かじゅまさぁぁぁん！"

# カズマ
# って、アクア、こらっ！\nこんなとこでくっつくなっ！！
252 = "って、アクア、こらっ！\\nこんなとこでくっつくなっ！！"

# アクア
# いやああああああああ！！
201 = "いやああああああああ！！"

# アクア
# 助けてカズマさん！　ワニは無理！\n無理だから！　助けてよカズマさああああん！
310 = "助けてカズマさん！　ワニは無理！\\n無理だから！　助けてよカズマさああああん！"

# カズマ
# うごぼっ、おい、離れろ駄女神！\n溺れるっ、うがあ、俺を殺す気か！
202 = "うごぼっ、おい、離れろ駄女神！\\n溺れるっ、うがあ、俺を殺す気か！"

# アクア
# 別に死んだっていいじゃない。\nカズマはもう何回も死んでるんだから。
309 = "別に死んだっていいじゃない。\\nカズマはもう何回も死んでるんだから。"

# カズマ
# ごぼぶ！　か、回数の問題じゃねー！
231 = "ごぼぶ！　か、回数の問題じゃねー！"

# アクア
# また死んじゃっても生き返らせてあげるから\n助けてよ。\n私、本当にワニはダメなのぉ！
279 = "また死んじゃっても生き返らせてあげるから\\n助けてよ。\\n私、本当にワニはダメなのぉ！"

# カズマ
# お前、俺の命をなんだと思ってるんだ！
216 = "お前、俺の命をなんだと思ってるんだ！"

# アクア
# 怖い、怖い、怖い！　誰か助けてーーーー！！
321 = "怖い、怖い、怖い！　誰か助けてーーーー！！"

# ゆんゆん
# きゃっ、また誰かが水着を！
223 = "きゃっ、また誰かが水着を！"

# アクア
# きゃぁぁぁぁああああ！
221 = "きゃぁぁぁぁああああ！"

# めぐみん
# ちょっと、カズマ、この非常時に何を！
248 = "ちょっと、カズマ、この非常時に何を！"

# カズマ
# うごぼぼぼぼぼ！
203 = "うごぼぼぼぼぼ！"

# ゆんゆん
# カズマさんじゃないみたいだね。
295 = "カズマさんじゃないみたいだね。"

# めぐみん
# じゃあ、犯人は……。
233 = "じゃあ、犯人は……。"

# アクア
# カズマ、カズマさん！\nどんどん集まってくる！\nなんなのこれ！
291 = "カズマ、カズマさん！\\nどんどん集まってくる！\\nなんなのこれ！"

# ウィズ
# あっ、なるほど、そういうことですか。
194 = "あっ、なるほど、そういうことですか。"

# めぐみん
# 何かわかったんですか？
305 = "何かわかったんですか？"

# ウィズ
# おそらくですけど、孵ったばかりの\nブルータルアリゲーターは狩りの練習を\nしているのではないかと。
212 = "おそらくですけど、孵ったばかりの\\nブルータルアリゲーターは狩りの練習を\\nしているのではないかと。"

# ダクネス
# 生き残るための本能というやつか。
328 = "生き残るための本能というやつか。"

# ウィズ
# きゃっ、私も水着が取られそうに！
224 = "きゃっ、私も水着が取られそうに！"

# ゆんゆん
# あうう、このままだと脱がされちゃう！
192 = "あうう、このままだと脱がされちゃう！"

# ダクネス
# くっ。子供のワニと思って甘く見すぎていたか。\nこいつら意外と……こら、そんな所に潜り込むな！
226 = "くっ。子供のワニと思って甘く見すぎていたか。\\nこいつら意外と……こら、そんな所に潜り込むな！"

# めぐみん
# なぜでしょう。\nやたらと狙いが偏っているように感じるのですが。
261 = "なぜでしょう。\\nやたらと狙いが偏っているように感じるのですが。"

# クリス
# まあ、助かるって言えば助かるけど。
278 = "まあ、助かるって言えば助かるけど。"

# アクア
# ひゃいあ！
276 = "ひゃいあ！"

# カズマ
# ぐぼ、アグア、死ぬ！
227 = "ぐぼ、アグア、死ぬ！"

# アクア
# 水着、水着の中にっ！\nもそもそって、いやあああ！！
325 = "水着、水着の中にっ！\\nもそもそって、いやあああ！！"

# めぐみん
# ちょっとアクア！　脱いだりしたら！
249 = "ちょっとアクア！　脱いだりしたら！"

# カズマ
# ！？
376 = "！？"

# アクア
# だってだって、ワニがお尻の方に！！
247 = "だってだって、ワニがお尻の方に！！"

# カズマ
# ダクネス、いるか！
301 = "ダクネス、いるか！"

# ダクネス
# なんだ！
263 = "なんだ！"

# カズマ
# 今の俺たちには盾が必要だ！
304 = "今の俺たちには盾が必要だ！"

# ダクネス
# 盾が！？
371 = "盾が！？"

# カズマ
# ダクネス、頼まれてくれるか！
302 = "ダクネス、頼まれてくれるか！"

# ダクネス
# くっ、しかし、子ワニとはいえこれだけの数を\n相手にしたら水着が。
225 = "くっ、しかし、子ワニとはいえこれだけの数を\\n相手にしたら水着が。"

# カズマ
# そう、それにじきにここにも、\n出遅れた男冒険者たちがやってくるだろう！
235 = "そう、それにじきにここにも、\\n出遅れた男冒険者たちがやってくるだろう！"

# ダクネス
# 男冒険者たちが！？
329 = "男冒険者たちが！？"

# カズマ
# そうなったら、お前の肌を男冒険者たちに！
237 = "そうなったら、お前の肌を男冒険者たちに！"

# ダクネス
# つまり、いやらしい視線の下に、\n私の痴態が晒されると言うことなのだな！
254 = "つまり、いやらしい視線の下に、\\n私の痴態が晒されると言うことなのだな！"

# カズマ
# ごぼぶ、や、やっぱり無理か、ダクネス！
230 = "ごぼぶ、や、やっぱり無理か、ダクネス！"

# ダクネス
# み、見くびられては困るぞカズマ！
280 = "み、見くびられては困るぞカズマ！"

# ダクネス
# 騎士の誇りの前では女の体裁など\nゴミみたいなものだ！
375 = "騎士の誇りの前では女の体裁など\\nゴミみたいなものだ！"

# カズマ
# なら、早くしてくれ！\nでないと、うごぼ、死ぬ！！
262 = "なら、早くしてくれ！\\nでないと、うごぼ、死ぬ！！"

# ダクネス
# さあ、ワニ共こい！\n私の水着を好きなだけ食いちぎれ！
232 = "さあ、ワニ共こい！\\n私の水着を好きなだけ食いちぎれ！"

# アクア
# いやぁぁぁ、かじゅま、かじゅまぁぁぁ！\n助けてぇぇ！！
200 = "いやぁぁぁ、かじゅま、かじゅまぁぁぁ！\\n助けてぇぇ！！"

# カズマ
# わかったから、少し離れろ、お前はっ！
285 = "わかったから、少し離れろ、お前はっ！"

