# st02a_07.txt.scn

[info]
0 = ""

[characters]
96 = "カズマ"
98 = "ダクネス"
95 = "ウィズ"
97 = "カズマ（Ｍ）"

[character_subs]
# 96 = "カズマ"

[script]
# lines: 14

# カズマ
# …………。
90 = "…………。"

# ダクネス
# …………。
# 90 = "…………。"

# ウィズ
# …………。
# 90 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （なんなんだろう、この妙な雰囲気は）
117 = "（なんなんだろう、この妙な雰囲気は）"

# カズマ（Ｍ）
# display as カズマ
# （ふたりともずっと黙ったままだし、\n　話を振っても帰ってくるのは空返事だし）
118 = "（ふたりともずっと黙ったままだし、\\n　話を振っても帰ってくるのは空返事だし）"

# ダクネス
# はぁ……はぁ……はぁ……はぁ。
93 = "はぁ……はぁ……はぁ……はぁ。"

# カズマ（Ｍ）
# display as カズマ
# （てか、こいつはなんでずっと\n　ハァハァしてるんだよ……）
115 = "（てか、こいつはなんでずっと\\n　ハァハァしてるんだよ……）"

# カズマ
# なあダクネス、もしかして熱でもあるのか？
92 = "なあダクネス、もしかして熱でもあるのか？"

# ダクネス
# はぁはぁ、そんなことはないが。
94 = "はぁはぁ、そんなことはないが。"

# カズマ
# でもさ……。
91 = "でもさ……。"

# ダクネス
# 心配はいらん！\nむしろ絶好調なくらいだ！
102 = "心配はいらん！\\nむしろ絶好調なくらいだ！"

# カズマ（Ｍ）
# display as カズマ
# （これはアレか？　もしかして。\n　いつもの変なスイッチが入ってるのか？）
114 = "（これはアレか？　もしかして。\\n　いつもの変なスイッチが入ってるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （でも、いったい何が原因で……）
116 = "（でも、いったい何が原因で……）"

# カズマ（Ｍ）
# display as カズマ
# （ま、放っておくのが一番だろう。\n　律儀に相手すると、\n　面倒くさいことになりそうだし）
119 = "（ま、放っておくのが一番だろう。\\n　律儀に相手すると、\\n　面倒くさいことになりそうだし）"

