# st02a_05.txt.scn

[info]
0 = ""

[characters]
132 = "キース"
129 = "カズマ"
133 = "ダスト"
134 = "ルナ"
131 = "カズマ（Ｍ）"

[character_subs]
# 129 = "カズマ"

[script]
# lines: 31

# キース
# カズマは知らないだろうけど、\nもうすぐ運動会が開催されるんだ。
130 = "カズマは知らないだろうけど、\\nもうすぐ運動会が開催されるんだ。"

# カズマ
# それがどうして金儲けになるんだよ。\nまさかちびっ子たちの競技でオッズ屋でも\nやれっていうのか。
121 = "それがどうして金儲けになるんだよ。\\nまさかちびっ子たちの競技でオッズ屋でも\\nやれっていうのか。"

# キース
# お前は、この街の運動会を侮っている。
112 = "お前は、この街の運動会を侮っている。"

# ダスト
# 聞いて驚け！\nこの街の運動会は、ギルドが主催する\nガチの競技会なんだ！！
165 = "聞いて驚け！\\nこの街の運動会は、ギルドが主催する\\nガチの競技会なんだ！！"

# カズマ
# はあ、ギルドがどうしてそんなことを。
126 = "はあ、ギルドがどうしてそんなことを。"

# ルナ
# もともとは冒険者のみなさんのやる気を\n促すために始めたらしいんです。
127 = "もともとは冒険者のみなさんのやる気を\\n促すために始めたらしいんです。"

# カズマ
# あっ、お姉さん！
109 = "あっ、お姉さん！"

# ルナ
# すみません、話が聞こえたもので、つい。
117 = "すみません、話が聞こえたもので、つい。"

# ダスト
# か、構いませんよ！\n何か飲みますか？
113 = "か、構いませんよ！\\n何か飲みますか？"

# ルナ
# いえ、まだ勤務中ですので。
110 = "いえ、まだ勤務中ですので。"

# カズマ
# しかし、冒険者のやる気を促すための手段が、\nどうして運動会なんですか。
116 = "しかし、冒険者のやる気を促すための手段が、\\nどうして運動会なんですか。"

# ルナ
# 昔、まだ街の周りの魔物を駆逐できてなかった頃、\n少しお金が貯まっただけで街に引きこもる冒険者が\n多くいたらしいんです。
140 = "昔、まだ街の周りの魔物を駆逐できてなかった頃、\\n少しお金が貯まっただけで街に引きこもる冒険者が\\n多くいたらしいんです。"

# ルナ
# それで身体が鈍り、次のクエストでケガをしたり、\nそもそもクエストに行かなくなるという人たちが\n出てきて――
123 = "それで身体が鈍り、次のクエストでケガをしたり、\\nそもそもクエストに行かなくなるという人たちが\\n出てきて――"

# ルナ
# このままではいけないということになり、\n体力作りや意識向上を促すため運動会を\n企画したと。
115 = "このままではいけないということになり、\\n体力作りや意識向上を促すため運動会を\\n企画したと。"

# カズマ
# それが慣例行事になったというわけですか。
122 = "それが慣例行事になったというわけですか。"

# ルナ
# そういうことですね。
118 = "そういうことですね。"

# カズマ（Ｍ）
# display as カズマ
# （そんな理由で運動会って……\n　もっと他に何かなかったのかよ？）
167 = "（そんな理由で運動会って……\\n　もっと他に何かなかったのかよ？）"

# カズマ
# だけど、運動会と儲け話に何の関係があるんだ？
124 = "だけど、運動会と儲け話に何の関係があるんだ？"

# キース
# その運動会で優勝すると賞金が出るんだよ。
119 = "その運動会で優勝すると賞金が出るんだよ。"

# カズマ
# 賞金？
166 = "賞金？"

# キース
# ああ、高額のな。
108 = "ああ、高額のな。"

# カズマ
# ええと、いくらくらいなんです？
111 = "ええと、いくらくらいなんです？"

# ルナ
# 今年の賞金額はまだ決めていませんが、\n予算として４０００万エリスほど確保していますよ。
136 = "今年の賞金額はまだ決めていませんが、\\n予算として４０００万エリスほど確保していますよ。"

# カズマ
# なっ、そんな大金が動くんですか！？
125 = "なっ、そんな大金が動くんですか！？"

# ダスト
# そりゃそうだろ。\n実入りが良くなきゃ、冒険者なんて職は\n選ばないだろうし。
120 = "そりゃそうだろ。\\n実入りが良くなきゃ、冒険者なんて職は\\n選ばないだろうし。"

# キース
# 基本俺たちは、金で動くからな。
138 = "基本俺たちは、金で動くからな。"

# ルナ
# こちらとしては、もう少し志を高く\n持っていただきたいんですが。
114 = "こちらとしては、もう少し志を高く\\n持っていただきたいんですが。"

# カズマ（Ｍ）
# display as カズマ
# （予算で４０００万エリス）
170 = "（予算で４０００万エリス）"

# カズマ（Ｍ）
# display as カズマ
# （ってことは、\n　優勝で２０００万は計算できるか？）
168 = "（ってことは、\\n　優勝で２０００万は計算できるか？）"

# ルナ
# よかったら、サトウさんも参加してくださいね。
128 = "よかったら、サトウさんも参加してくださいね。"

# カズマ（Ｍ）
# display as カズマ
# （とりあえずあいつらに話をしてみるか）
169 = "（とりあえずあいつらに話をしてみるか）"

