# st02a_03.txt.scn

[info]
0 = ""

[characters]
253 = "カズマ"
252 = "ウィズ"
254 = "カズマ（Ｍ）"
256 = "バニル"

[character_subs]
# 253 = "カズマ"

[script]
# lines: 111

# カズマ
# おーい！　バニルは帰ったかー？
194 = "おーい！　バニルは帰ったかー？"

# ウィズ
# ひゃああああ、カズマさん！？
242 = "ひゃああああ、カズマさん！？"

# カズマ
# な、なんだよ。びっくりするじゃないか。
230 = "な、なんだよ。びっくりするじゃないか。"

# ウィズ
# あっ、すみません。\nちょっとボーッとしていたもので。
175 = "あっ、すみません。\\nちょっとボーッとしていたもので。"

# カズマ
# だからって驚きすぎだろ。
218 = "だからって驚きすぎだろ。"

# ウィズ
# そ、そうですね。
200 = "そ、そうですね。"

# カズマ
# あ、そうだ。
173 = "あ、そうだ。"

# ウィズ
# はい！
237 = "はい！"

# カズマ
# えっと……
191 = "えっと……"

# ウィズ
# はい！
# 237 = "はい！"

# カズマ
# 話が……。
332 = "話が……。"

# ウィズ
# はは、はい！
238 = "はは、はい！"

# カズマ
# えーと、なんか俺を避けてない？
192 = "えーと、なんか俺を避けてない？"

# ウィズ
# そ、そんなことはありませんよ？
201 = "そ、そんなことはありませんよ？"

# カズマ（Ｍ）
# display as カズマ
# （どうしたんだウィズのやつ？\n　なんか顔が赤いし、モジモジしてるし……）
341 = "（どうしたんだウィズのやつ？\\n　なんか顔が赤いし、モジモジしてるし……）"

# カズマ（Ｍ）
# display as カズマ
# （やけに落ち着かない様子で、\n　俺の顔をまっすぐ見ようとせずに、\n　ちらちらと横目で窺うようにしてて……）
344 = "（やけに落ち着かない様子で、\\n　俺の顔をまっすぐ見ようとせずに、\\n　ちらちらと横目で窺うようにしてて……）"

# カズマ（Ｍ）
# display as カズマ
# （はっ、もしかして恋！　これって恋煩い！）
342 = "（はっ、もしかして恋！　これって恋煩い！）"

# カズマ（Ｍ）
# display as カズマ
# （それにこの目、もしかして俺って今、\n　誘われちゃってる！）
340 = "（それにこの目、もしかして俺って今、\\n　誘われちゃってる！）"

# カズマ（Ｍ）
# display as カズマ
# （ええと、こういう時はどうするんだー。\n　思い出せ俺）
337 = "（ええと、こういう時はどうするんだー。\\n　思い出せ俺）"

# カズマ（Ｍ）
# display as カズマ
# （ネットやゲームでかき集めた恋愛のテクを\n　駆使してハッピーエンドのフラグを立てるんだ）
345 = "（ネットやゲームでかき集めた恋愛のテクを\\n　駆使してハッピーエンドのフラグを立てるんだ）"

# バニル
# 妙な期待に胸を高鳴らせている小僧よ、\n残念ながら、そのポンコツ店主から\n汝が望む言葉が返って来ることはないぞ。
267 = "妙な期待に胸を高鳴らせている小僧よ、\\n残念ながら、そのポンコツ店主から\\n汝が望む言葉が返って来ることはないぞ。"

# ウィズ
# え、望む言葉ですか？
189 = "え、望む言葉ですか？"

# カズマ
# あははは、なんでもないぞ、なんでも。
176 = "あははは、なんでもないぞ、なんでも。"

# カズマ
# てか、お前帰ってたのかよ！
221 = "てか、お前帰ってたのかよ！"

# バニル
# うむ、昨夜にな。
183 = "うむ、昨夜にな。"

# カズマ
# だったら声かけろよ！　朝一番に！
219 = "だったら声かけろよ！　朝一番に！"

# バニル
# なんだ我輩に用があるのか？
234 = "なんだ我輩に用があるのか？"

# カズマ
# しらばっくれるなっ！\nこの状況を楽しんで長旅に出てたくせに！
198 = "しらばっくれるなっ！\\nこの状況を楽しんで長旅に出てたくせに！"

# バニル
# フハハハハ、なんのことだかさっぱりだな。
257 = "フハハハハ、なんのことだかさっぱりだな。"

# カズマ
# とにかくっ！\nこの指輪のことで話があるんだよ！
224 = "とにかくっ！\\nこの指輪のことで話があるんだよ！"

# バニル
# そういえば昨夜は満月であったな。
203 = "そういえば昨夜は満月であったな。"

# ウィズ
# ！！
336 = "！！"

# カズマ
# どうしたウィズ？
226 = "どうしたウィズ？"

# ウィズ
# なんでもないですよ。\n私のことはお気になさらず、どうぞ。
235 = "なんでもないですよ。\\n私のことはお気になさらず、どうぞ。"

# カズマ
# まあ、とにかくだ。\nバニル、この指輪どうなってるんだよ。
247 = "まあ、とにかくだ。\\nバニル、この指輪どうなってるんだよ。"

# バニル
# どうとは？
228 = "どうとは？"

# カズマ
# なんか今日はさ、\n起きたら２枚もパンツを持ってたんだ。
232 = "なんか今日はさ、\\n起きたら２枚もパンツを持ってたんだ。"

# ウィズ
# え、２枚ですか？
190 = "え、２枚ですか？"

# カズマ
# まあ、パンツを盗った相手が、\nたまたま重ねて２枚穿いてたって\nだけかもしれないけど。
248 = "まあ、パンツを盗った相手が、\\nたまたま重ねて２枚穿いてたって\\nだけかもしれないけど。"

# ウィズ
# そんな……２枚なんて。
215 = "そんな……２枚なんて。"

# カズマ
# やっぱりウィズもおかしいって思うか？
250 = "やっぱりウィズもおかしいって思うか？"

# ウィズ
# え、あ、はい！\n２枚というのは、ええと、おかしいかなと思います。
185 = "え、あ、はい！\\n２枚というのは、ええと、おかしいかなと思います。"

# カズマ
# そうだよな、前の満月の時は１枚だったし、\nこれっていったいどういうことなんだろ。
204 = "そうだよな、前の満月の時は１枚だったし、\\nこれっていったいどういうことなんだろ。"

# バニル
# どれ、指輪を見せてみろ。
229 = "どれ、指輪を見せてみろ。"

# カズマ
# 金ならねーぞ。
334 = "金ならねーぞ。"

# バニル
# これは我の温情だ。
197 = "これは我の温情だ。"

# カズマ
# それだったら、頼む。
210 = "それだったら、頼む。"

# バニル
# ふむふむ。なるほど。
245 = "ふむふむ。なるほど。"

# カズマ
# 何かわかったのか？
263 = "何かわかったのか？"

# バニル
# はは！　この世の全てを見通す大悪魔である\n我輩に、わからぬことなどあるはずがあるまい。
239 = "はは！　この世の全てを見通す大悪魔である\\n我輩に、わからぬことなどあるはずがあるまい。"

# バニル
# なぜ汝が目覚めた時に、\n２枚の下着を持っていたかだと？
231 = "なぜ汝が目覚めた時に、\\n２枚の下着を持っていたかだと？"

# バニル
# 至極単純。\nこの指輪が真の力を発揮し始めただけのこと。
330 = "至極単純。\\nこの指輪が真の力を発揮し始めただけのこと。"

# カズマ
# は？　真の力？
240 = "は？　真の力？"

# バニル
# 心当たりがあるのではないか小僧。
273 = "心当たりがあるのではないか小僧。"

# カズマ
# そういえばウィズも言ってたよな！
202 = "そういえばウィズも言ってたよな！"

# ウィズ
# え、え？　何をです！？
187 = "え、え？　何をです！？"

# カズマ
# ほら、前の満月の時、俺の力が増幅されてるって。
246 = "ほら、前の満月の時、俺の力が増幅されてるって。"

# ウィズ
# そ、そうですね。
# 200 = "そ、そうですね。"

# バニル
# どういう術式なのかは指輪を細かに分析してみない\nとわからんが――
225 = "どういう術式なのかは指輪を細かに分析してみない\\nとわからんが――"

# バニル
# その力が少しずつ発揮されるよう\n小細工が施されていると見て間違いなかろう。
208 = "その力が少しずつ発揮されるよう\\n小細工が施されていると見て間違いなかろう。"

# バニル
# そして、トリガーとなるのは、おそらく満月。
206 = "そして、トリガーとなるのは、おそらく満月。"

# カズマ
# その結果、今回は２枚盗っちまったって\nことなのか……。
209 = "その結果、今回は２枚盗っちまったって\\nことなのか……。"

# バニル
# どうだ、我に術式の解析を依頼してみんか？\nそうすればこの指輪の力をコントロールできる\nようになるかもしれんぞ。
227 = "どうだ、我に術式の解析を依頼してみんか？\\nそうすればこの指輪の力をコントロールできる\\nようになるかもしれんぞ。"

# カズマ
# それって温情か？
211 = "それって温情か？"

# バニル
# うむ、その通り。\n本来は５０００万エリスほど請求するところだが、\n温情で４５００万エリスに負けてやろう。
182 = "うむ、その通り。\\n本来は５０００万エリスほど請求するところだが、\\n温情で４５００万エリスに負けてやろう。"

# カズマ
# ふっざけんな！\n解除料金を貯めるのにだって、\nこっちは四苦八苦してんだぞ！
243 = "ふっざけんな！\\n解除料金を貯めるのにだって、\\nこっちは四苦八苦してんだぞ！"

# バニル
# ずいぶんと暢気なものだな小僧。
199 = "ずいぶんと暢気なものだな小僧。"

# カズマ
# は、なんでだよ。
236 = "は、なんでだよ。"

# バニル
# ふむ、邪魔だな。
244 = "ふむ、邪魔だな。"

# カズマ（Ｍ）
# display as カズマ
# （は？）
343 = "（は？）"

# バニル
# ポンコツ店主よ。
259 = "ポンコツ店主よ。"

# ウィズ
# あ、はい。\nって、ええ！？　どうして殺人光線の構えを！
174 = "あ、はい。\\nって、ええ！？　どうして殺人光線の構えを！"

# カズマ
# ちょっ、お前、何やってんだよ！
220 = "ちょっ、お前、何やってんだよ！"

# バニル
# 少し眠って貰うだけだ。
268 = "少し眠って貰うだけだ。"

# ウィズ
# え、え、バニルさん！？
186 = "え、え、バニルさん！？"

# ウィズ
# ひゃぁぁぁぁぁぁぁぁ！！！
241 = "ひゃぁぁぁぁぁぁぁぁ！！！"

# カズマ
# うわ、ウィズ！！
184 = "うわ、ウィズ！！"

# バニル
# では、話の続きをしようか。
223 = "では、話の続きをしようか。"

# カズマ
# いやいや、ウィズがなんかこんがりしてんだけど！
179 = "いやいや、ウィズがなんかこんがりしてんだけど！"

# カズマ
# てか、なんなんだよお前！\nやるっていうなら、うちの狂犬女神をけしかけんぞ！
222 = "てか、なんなんだよお前！\\nやるっていうなら、うちの狂犬女神をけしかけんぞ！"

# バニル
# 落ちつけ。\nこの程度でアンデッドの王はくたばりはせん。
331 = "落ちつけ。\\nこの程度でアンデッドの王はくたばりはせん。"

# ウィズ
# うきゅぅ～～～～。
181 = "うきゅぅ～～～～。"

# カズマ
# いや、でも……
178 = "いや、でも……"

# バニル
# 店主が目を覚ます前に話を終わらせるぞ。
272 = "店主が目を覚ます前に話を終わらせるぞ。"

# カズマ
# なんだよ、ウィズに聞かれたら困ることなのか？
233 = "なんだよ、ウィズに聞かれたら困ることなのか？"

# バニル
# この女のことだ。\n事実を知ったら、無償で解除をしてやれと\nしつこく言ってくる。
196 = "この女のことだ。\\n事実を知ったら、無償で解除をしてやれと\\nしつこく言ってくる。"

# カズマ
# それは俺にとって願ったり叶ったりなんだけど。
213 = "それは俺にとって願ったり叶ったりなんだけど。"

# バニル
# 我は、技術を安売りするような間抜けではない。
274 = "我は、技術を安売りするような間抜けではない。"

# カズマ
# それで？　ウィズに聞かれたら困る話って\nなんなんだよ。
212 = "それで？　ウィズに聞かれたら困る話って\\nなんなんだよ。"

# バニル
# 簡潔に言おう、このままでは小僧、お前は死ぬ。
329 = "簡潔に言おう、このままでは小僧、お前は死ぬ。"

# カズマ
# あははは、またまたご冗談を。
177 = "あははは、またまたご冗談を。"

# バニル
# 信じるか否かは小僧、お前の自由だ。
264 = "信じるか否かは小僧、お前の自由だ。"

# カズマ
# え、もしかして本当なの？\nな、なんでだよ！
188 = "え、もしかして本当なの？\\nな、なんでだよ！"

# カズマ
# もしかして、\nパンツを盗まれたことに怒ったあいつらに\nフルボッコにされるのか！？
249 = "もしかして、\\nパンツを盗まれたことに怒ったあいつらに\\nフルボッコにされるのか！？"

# バニル
# それも間違えてはいないな。
214 = "それも間違えてはいないな。"

# カズマ（Ｍ）
# display as カズマ
# （間違えてないのかよ！？）
346 = "（間違えてないのかよ！？）"

# バニル
# よくよく考えてみればわかることだろう。\nお前は、自分が本来持つ以上の力を\nその指輪によって引き出されているのだぞ。
251 = "よくよく考えてみればわかることだろう。\\nお前は、自分が本来持つ以上の力を\\nその指輪によって引き出されているのだぞ。"

# バニル
# そしてその効果は、\n満月の夜が訪れるたびに増していく。
207 = "そしてその効果は、\\n満月の夜が訪れるたびに増していく。"

# バニル
# 今は気怠さを感じる程度の疲れで\n済んでるかもしれぬが――
262 = "今は気怠さを感じる程度の疲れで\\n済んでるかもしれぬが――"

# バニル
# このままその指輪にいいように力を使われ続けたら。
195 = "このままその指輪にいいように力を使われ続けたら。"

# カズマ
# キャパシティ以上の魔力を引っ張り出されて、\n死ぬ？
255 = "キャパシティ以上の魔力を引っ張り出されて、\\n死ぬ？"

# バニル
# 長けた魔術師なら、数年は生きられるかも\nしれぬが、お主の魔力量なら数ヶ月といった所か。
335 = "長けた魔術師なら、数年は生きられるかも\\nしれぬが、お主の魔力量なら数ヶ月といった所か。"

# カズマ（Ｍ）
# display as カズマ
# （そ、そんな……）
339 = "（そ、そんな……）"

# バニル
# そこで提案だ。\n先ほど言った、術式の解析を我輩に依頼をしろ。
205 = "そこで提案だ。\\n先ほど言った、術式の解析を我輩に依頼をしろ。"

# カズマ
# お、温情を……。
193 = "お、温情を……。"

# バニル
# 一億エリスで手を打とうではないか。
260 = "一億エリスで手を打とうではないか。"

# カズマ
# 足元見てんじゃねーよ！\nこの、鬼、悪魔、アクア！
333 = "足元見てんじゃねーよ！\\nこの、鬼、悪魔、アクア！"

# ウィズ
# う、うう～ん、なんなんですか急に。
180 = "う、うう～ん、なんなんですか急に。"

# バニル
# ただの息抜きだ、気にするな。
217 = "ただの息抜きだ、気にするな。"

# ウィズ
# そんなことで殺人光線を撃たないでください！
216 = "そんなことで殺人光線を撃たないでください！"

# カズマ（Ｍ）
# display as カズマ
# （お、俺が死ぬ？\n　ははは、夢なら早く覚めてくれ……）
338 = "（お、俺が死ぬ？\\n　ははは、夢なら早く覚めてくれ……）"

