# st02c_04.txt.scn

[info]
0 = ""

[characters]
264 = "カズマ"
268 = "クリス"
267 = "カズマ（Ｍ）"
256 = "めぐみん"
269 = "ダクネス"
263 = "ウィズ"
259 = "ゆんゆん"
271 = "ダスト"

[character_subs]
# 264 = "カズマ"

[script]
# lines: 85

# カズマ
# あっさり終わったな。
209 = "あっさり終わったな。"

# クリス
# 駆け出しばかりといっても、\nこれだけの冒険者が集まってればね。
334 = "駆け出しばかりといっても、\\nこれだけの冒険者が集まってればね。"

# カズマ（Ｍ）
# display as カズマ
# （そういえば、トラウマ組は……）
340 = "（そういえば、トラウマ組は……）"

# めぐみん
# 何を油を売っているんですか、\n先頭はかなり先を走っていますよ！
276 = "何を油を売っているんですか、\\n先頭はかなり先を走っていますよ！"

# カズマ
# …………。
206 = "…………。"

# カズマ
# 殴っていい？
289 = "殴っていい？"

# クリス
# あは、あはは、気持ちはわかるけど、\nやめておきなって。
214 = "あは、あはは、気持ちはわかるけど、\\nやめておきなって。"

# ダクネス
# う、うう、ううう……。
220 = "う、うう、ううう……。"

# カズマ
# で？　お前はなんでいじけてんだ。
243 = "で？　お前はなんでいじけてんだ。"

# ダクネス
# あのカエル共、なぜ私を食おうとしなかったんだ。
213 = "あのカエル共、なぜ私を食おうとしなかったんだ。"

# カズマ（Ｍ）
# display as カズマ
# （食われたかったのか……）
346 = "（食われたかったのか……）"

# めぐみん
# ダクネス、無事なら早く行きましょう。
270 = "ダクネス、無事なら早く行きましょう。"

# カズマ
# そうだな。\nいくら湖に着いてからが本番だからって、\nあまり離されると逆転するのがきつくなる。
235 = "そうだな。\\nいくら湖に着いてからが本番だからって、\\nあまり離されると逆転するのがきつくなる。"

# ウィズ
# カズマさん。あの……アクア様が……。
266 = "カズマさん。あの……アクア様が……。"

# カズマ
# アクアがどうした？
262 = "アクアがどうした？"

# ウィズ
# いえ、さっきから見当たらないんです。
216 = "いえ、さっきから見当たらないんです。"

# カズマ
# なっ！？　まさか逃げ出してそのまま――
248 = "なっ！？　まさか逃げ出してそのまま――"

# ゆんゆん
# 捜してみますか？
287 = "捜してみますか？"

# カズマ
# うーん……捜すって言ってもな……。
222 = "うーん……捜すって言ってもな……。"

# カズマ（Ｍ）
# display as カズマ
# （先に行ったのか、引き返したのかも\n　わからないんだから捜しようがない）
345 = "（先に行ったのか、引き返したのかも\\n　わからないんだから捜しようがない）"

# カズマ（Ｍ）
# display as カズマ
# （まさかコースアウトして\n　逃げたとは思いたくないが……）
343 = "（まさかコースアウトして\\n　逃げたとは思いたくないが……）"

# カズマ
# 仕方ない。\nアクアはもう先に行ってると信じよう。
275 = "仕方ない。\\nアクアはもう先に行ってると信じよう。"

# カズマ
# 最悪、失格とかリタイアしてなければ、\nどこかで合流できるはずだ。
288 = "最悪、失格とかリタイアしてなければ、\\nどこかで合流できるはずだ。"

# カズマ
# てことで、行くぞ！
242 = "てことで、行くぞ！"

# カズマ
# いてっ！？
217 = "いてっ！？"

# ダスト
# おっと、悪いな。\nぶつかっちまった。
226 = "おっと、悪いな。\\nぶつかっちまった。"

# カズマ
# ダストか。気を付けろよ。
272 = "ダストか。気を付けろよ。"

# ダスト
# へへ、すまんすまん。
255 = "へへ、すまんすまん。"

# カズマ（Ｍ）
# display as カズマ
# （なんだこの、薄ら笑い……）
341 = "（なんだこの、薄ら笑い……）"

# カズマ
# …………。
# 206 = "…………。"

# ダスト
# …………。
# 206 = "…………。"

# カズマ
# お前、今わざとぶつかっただろ？
229 = "お前、今わざとぶつかっただろ？"

# ダスト
# なんのことだ？
252 = "なんのことだ？"

# カズマ
# こんな広い道なのに、\n他人と肩がぶつかるような所を\nわざわざ通って行く必要がないだろ？
232 = "こんな広い道なのに、\\n他人と肩がぶつかるような所を\\nわざわざ通って行く必要がないだろ？"

# ダスト
# ……はっ。お前が女をはべらせて、\nこんなところでたむろってるのが悪いんだよ！
207 = "……はっ。お前が女をはべらせて、\\nこんなところでたむろってるのが悪いんだよ！"

# カズマ
# って、危なっ！　友達を蹴るな！
241 = "って、危なっ！　友達を蹴るな！"

# ダスト
# 友達っ、友達だと？
280 = "友達っ、友達だと？"

# カズマ
# な、なんだよ。
244 = "な、なんだよ。"

# ダスト
# 俺に、リア充の友達なんていねーからっ！
277 = "俺に、リア充の友達なんていねーからっ！"

# カズマ
# そんなんじゃねえよ！　お前の目は節穴か！
239 = "そんなんじゃねえよ！　お前の目は節穴か！"

# ダスト
# お前がどう言おうが、\nはたから見てる分には羨ましいんだよ！
230 = "お前がどう言おうが、\\nはたから見てる分には羨ましいんだよ！"

# ダスト
# おらっ、もう一発くらえ！
227 = "おらっ、もう一発くらえ！"

# カズマ
# お前、だから蹴るなって！
228 = "お前、だから蹴るなって！"

# クリス
# ちょっと、さっきから何してるの？
240 = "ちょっと、さっきから何してるの？"

# カズマ
# こらクリス、俺の前に出るな！！
231 = "こらクリス、俺の前に出るな！！"

# ダスト
# なぁぁぁ、しまった！？
245 = "なぁぁぁ、しまった！？"

# クリス
# え？
224 = "え？"

# カズマ
# 避けろ、クリス！\nこのままじゃ顔に――
333 = "避けろ、クリス！\\nこのままじゃ顔に――"

# クリス
# よっと。
260 = "よっと。"

# カズマ（Ｍ）
# display as カズマ
# （あっさり避けた！！）
335 = "（あっさり避けた！！）"

# クリス
# いやいや、こんなハエが止まるようなスピードの\n蹴りにあたるなんて不可能でしょ。
219 = "いやいや、こんなハエが止まるようなスピードの\\n蹴りにあたるなんて不可能でしょ。"

# ダスト
# なっ！？
247 = "なっ！？"

# カズマ（Ｍ）
# display as カズマ
# （しかも軽く心をえぐった！！）
338 = "（しかも軽く心をえぐった！！）"

# クリス
# ねえ、キミ。\nどんな理由があるのかは知らないけど、\nそういう妨害は男としてどうかと思うよ？
253 = "ねえ、キミ。\\nどんな理由があるのかは知らないけど、\\nそういう妨害は男としてどうかと思うよ？"

# ダスト
# うぐっ……。
221 = "うぐっ……。"

# クリス
# それにやるなら、もっと狡猾にやらないとね。\nそうしないと――
237 = "それにやるなら、もっと狡猾にやらないとね。\\nそうしないと――"

# ウィズ
# あの、そういうのはとても恥ずかしいことだと\n思いますよ？
212 = "あの、そういうのはとても恥ずかしいことだと\\n思いますよ？"

# ダスト
# なぁぁぁぁ！　ち、違うんだーーーー！！
246 = "なぁぁぁぁ！　ち、違うんだーーーー！！"

# クリス
# さっ、行こうか。
234 = "さっ、行こうか。"

# カズマ
# あ、ああ……。
208 = "あ、ああ……。"

# クリス
# 結局、なんだったのアレ？
332 = "結局、なんだったのアレ？"

# カズマ
# 別に気にしなくて良いよ。
278 = "別に気にしなくて良いよ。"

# カズマ
# それより――
238 = "それより――"

# カズマ
# なんか変なことに巻き込んで悪かったな。
250 = "なんか変なことに巻き込んで悪かったな。"

# クリス
# なになに？\nキミがそういう素直な態度なの珍しいじゃん？
249 = "なになに？\\nキミがそういう素直な態度なの珍しいじゃん？"

# カズマ
# 別に珍しくはない……だろ？　たぶん。\n実際、巻き込んじゃったわけだし。
279 = "別に珍しくはない……だろ？　たぶん。\\n実際、巻き込んじゃったわけだし。"

# カズマ
# なんにせよ助かったよ。ありがとな。
251 = "なんにせよ助かったよ。ありがとな。"

# クリス
# ふーん。
254 = "ふーん。"

# カズマ
# …………。
# 206 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （なんだよ。その面白がってる顔は）
342 = "（なんだよ。その面白がってる顔は）"

# カズマ（Ｍ）
# display as カズマ
# （くそ。素直に礼なんて言うんじゃなかった）
336 = "（くそ。素直に礼なんて言うんじゃなかった）"

# カズマ
# あとで何かおごらせてくれ。
211 = "あとで何かおごらせてくれ。"

# クリス
# え？　なんか悪いね。\n別に何かしたってわけでもないのに。
225 = "え？　なんか悪いね。\\n別に何かしたってわけでもないのに。"

# カズマ
# いや、クリスが来てくれなかったら、\nあれがいつまで続いてたかわかんないし。
218 = "いや、クリスが来てくれなかったら、\\nあれがいつまで続いてたかわかんないし。"

# カズマ
# もっと面倒なことになってたかも\nしれないからな。礼くらいさせてくれ。
257 = "もっと面倒なことになってたかも\\nしれないからな。礼くらいさせてくれ。"

# クリス
# そう？　じゃあ遠慮なくおごってもらおうっと。
236 = "そう？　じゃあ遠慮なくおごってもらおうっと。"

# カズマ
# 不意打ちの蹴りだったのに、\nあんな簡単にかわしちまうなんて、\nさすがの身のこなしだな。
273 = "不意打ちの蹴りだったのに、\\nあんな簡単にかわしちまうなんて、\\nさすがの身のこなしだな。"

# クリス
# あはは、不意打ちなんかじゃないって。\nわかっててキミの前に入ったんだよ。
215 = "あはは、不意打ちなんかじゃないって。\\nわかっててキミの前に入ったんだよ。"

# カズマ
# え、そうなの？
223 = "え、そうなの？"

# クリス
# やるなら狡猾に。\n盗賊業の基本だからね。
258 = "やるなら狡猾に。\\n盗賊業の基本だからね。"

# カズマ（Ｍ）
# display as カズマ
# （じゃあ、ウィズのあの言葉も……）
339 = "（じゃあ、ウィズのあの言葉も……）"

# クリス
# ん？　何？
261 = "ん？　何？"

# カズマ（Ｍ）
# display as カズマ
# （クリス、恐ろしい子！）
344 = "（クリス、恐ろしい子！）"

# めぐみん
# カズマ、湖が見えてきましたよ。
265 = "カズマ、湖が見えてきましたよ。"

# カズマ（Ｍ）
# display as カズマ
# （ここからが勝負の本番だな）
337 = "（ここからが勝負の本番だな）"

[selections]
286 = "巻き込んで悪かったな"
210 = "あとで何かおごらせてくれ"
233 = "さすがの身のこなしだな"
