# st02a_04.txt.scn

[info]
0 = ""

[characters]
164 = "カズマ（Ｍ）"
163 = "カズマ"
166 = "ダスト"
165 = "キース"

[character_subs]
# 163 = "カズマ"

[script]
# lines: 62

# カズマ（Ｍ）
# display as カズマ
# （いくらなんでも、くだらなすぎるだろ。\n　死因がパンツ盗んだことによる衰弱なんて\n　ほんとありえねーよ……）
209 = "（いくらなんでも、くだらなすぎるだろ。\\n　死因がパンツ盗んだことによる衰弱なんて\\n　ほんとありえねーよ……）"

# カズマ（Ｍ）
# display as カズマ
# （それ以前に、盗むパンツの数が増えてくなんて\n　あいつらに言ったらどうなるか……）
212 = "（それ以前に、盗むパンツの数が増えてくなんて\\n　あいつらに言ったらどうなるか……）"

# カズマ（Ｍ）
# display as カズマ
# （バカにされるくらいならまだいいが、\n　本格的に強硬手段に出られたら、\n　さすが逆らいようがないぞ）
213 = "（バカにされるくらいならまだいいが、\\n　本格的に強硬手段に出られたら、\\n　さすが逆らいようがないぞ）"

# カズマ（Ｍ）
# display as カズマ
# （今日盗った２枚のパンツのことだって、\n　まだ話してないっていうのに……）
214 = "（今日盗った２枚のパンツのことだって、\\n　まだ話してないっていうのに……）"

# カズマ
# まったく。\nこの指輪のせいで、\nロクな目に遭ってないな最近……。
157 = "まったく。\\nこの指輪のせいで、\\nロクな目に遭ってないな最近……。"

# ダスト
# ようカズマ。なにブツブツ言ってんだよ？
159 = "ようカズマ。なにブツブツ言ってんだよ？"

# キース
# なんか変なことでも企んでるのか？
143 = "なんか変なことでも企んでるのか？"

# カズマ
# なんだ、ダストとキースか。
144 = "なんだ、ダストとキースか。"

# ダスト
# なんだとはご挨拶だな。
145 = "なんだとはご挨拶だな。"

# キース
# どうかしたのか？\nやけに暗い顔してるけど。
140 = "どうかしたのか？\\nやけに暗い顔してるけど。"

# カズマ
# まあ、なんていうか……。
156 = "まあ、なんていうか……。"

# ダスト
# おいおい。\nお前がそんなだと調子が狂うじゃねーか。
126 = "おいおい。\\nお前がそんなだと調子が狂うじゃねーか。"

# ダスト
# よーし。元気が出るように、\nこれからサキュバスの店にでも行くか？\nなんならおごってやってもいいぜ？
160 = "よーし。元気が出るように、\\nこれからサキュバスの店にでも行くか？\\nなんならおごってやってもいいぜ？"

# キース
# ダストのやつ、\n珍しくギャンブルで勝ったらしくてさ、\n俺もこんな調子で誘われたんだよ。
167 = "ダストのやつ、\\n珍しくギャンブルで勝ったらしくてさ、\\n俺もこんな調子で誘われたんだよ。"

# キース
# ま、嫌なことを忘れるには\n良いことで上書きするのがてっとり早いしな。\nカズマも一緒にどうだ？
155 = "ま、嫌なことを忘れるには\\n良いことで上書きするのがてっとり早いしな。\\nカズマも一緒にどうだ？"

# カズマ
# お前ら……。
129 = "お前ら……。"

# カズマ（Ｍ）
# display as カズマ
# （気遣ってくれる２人の言葉が身に染みるぜ。\n　こういう時、男友達っていうのは良いもんだな）
217 = "（気遣ってくれる２人の言葉が身に染みるぜ。\\n　こういう時、男友達っていうのは良いもんだな）"

# カズマ
# ありがと。気持ちだけもらっとくよ。\nどうせウチにはサキュバスの子は呼べないし。
123 = "ありがと。気持ちだけもらっとくよ。\\nどうせウチにはサキュバスの子は呼べないし。"

# ダスト
# そうか？　まあ、それなら仕方ないけど。
133 = "そうか？　まあ、それなら仕方ないけど。"

# キース
# なら話を聞くくらいはさせてくれ。\n何かあったのか？
142 = "なら話を聞くくらいはさせてくれ。\\n何かあったのか？"

# カズマ
# そうだな。お前らになら話しても良いか。
136 = "そうだな。お前らになら話しても良いか。"

# キース
# おうおう、なんでも話してくれ！
128 = "おうおう、なんでも話してくれ！"

# カズマ
# 実はな……俺、このままだと死ぬんだ。
174 = "実はな……俺、このままだと死ぬんだ。"

# ダスト
# はあ？
149 = "はあ？"

# カズマ（Ｍ）
# display as カズマ
# （俺は、バニルから聞いた話を\n　ふたりに説明をした）
215 = "（俺は、バニルから聞いた話を\\n　ふたりに説明をした）"

# カズマ（Ｍ）
# display as カズマ
# （指輪の力が強くなっていること、\n　そしてこのままだと指輪の力によって死ぬことも）
216 = "（指輪の力が強くなっていること、\\n　そしてこのままだと指輪の力によって死ぬことも）"

# カズマ（Ｍ）
# display as カズマ
# （その結果――）
211 = "（その結果――）"

# ダスト
# ふはははは！\nパンツ盗んで死ぬってお前、\nさすがに間抜けにもほどがあるだろ！
152 = "ふはははは！\\nパンツ盗んで死ぬってお前、\\nさすがに間抜けにもほどがあるだろ！"

# キース
# おいダスト、別にカズマだって\n自分の意思でやってるわけじゃないんだから、\nそんなふうに笑わなくても……ぶふっ！
127 = "おいダスト、別にカズマだって\\n自分の意思でやってるわけじゃないんだから、\\nそんなふうに笑わなくても……ぶふっ！"

# カズマ
# 笑ってんじゃねーよ！\nこっちは真剣に悩んでんだぞ！
207 = "笑ってんじゃねーよ！\\nこっちは真剣に悩んでんだぞ！"

# ダスト
# わかってるわかってるって。\nあっ、お姉さん、シュワシュワ追加でー。
161 = "わかってるわかってるって。\\nあっ、お姉さん、シュワシュワ追加でー。"

# カズマ
# もういいっ、俺は帰る！
158 = "もういいっ、俺は帰る！"

# ダスト
# 待て待て。悪かったって。\nお前の話が面白すぎたから、\nつい我慢できなくなっちまってさ。
176 = "待て待て。悪かったって。\\nお前の話が面白すぎたから、\\nつい我慢できなくなっちまってさ。"

# カズマ
# 悪気がなけりゃ笑っていいわけじゃないんだぞ。
177 = "悪気がなけりゃ笑っていいわけじゃないんだぞ。"

# ダスト
# ほーら、唐揚げやるから拗ねるなよ。
154 = "ほーら、唐揚げやるから拗ねるなよ。"

# カズマ
# こんなもんで懐柔されるか！\n貰うけど！
132 = "こんなもんで懐柔されるか！\\n貰うけど！"

# ダスト
# とにかく、お前が大変だってことは\n良くわかったよ。
139 = "とにかく、お前が大変だってことは\\n良くわかったよ。"

# キース
# でもまだ、数ヶ月は命が持つんだろ？
138 = "でもまだ、数ヶ月は命が持つんだろ？"

# カズマ
# そうだけどさ……。
135 = "そうだけどさ……。"

# キース
# 今は数ヶ月後の死よりも、\n目の前の危機をどうにかすべきだろ。
170 = "今は数ヶ月後の死よりも、\\n目の前の危機をどうにかすべきだろ。"

# ダスト
# このままだと、\nその指輪にトドメを刺されるよりも先に、\nパーティーの女の子にやられるぞ。
130 = "このままだと、\\nその指輪にトドメを刺されるよりも先に、\\nパーティーの女の子にやられるぞ。"

# キース
# 俺は、あんな可愛い子たちにいじめられるなら\n大歓迎だけど♪
171 = "俺は、あんな可愛い子たちにいじめられるなら\\n大歓迎だけど♪"

# ダスト
# んで、んで？\n今回盗んだパンツってどんなのなんだ？
162 = "んで、んで？\\n今回盗んだパンツってどんなのなんだ？"

# カズマ
# あー、それは……。
124 = "あー、それは……。"

# ダスト
# ほら、もったいぶらずに早く見せろって。
153 = "ほら、もったいぶらずに早く見せろって。"

# カズマ
# ……悪い、それは無理だわ。
121 = "……悪い、それは無理だわ。"

# キース
# はあ、どうしてだよ。\n楽しみは共有しようぜ、親友！
148 = "はあ、どうしてだよ。\\n楽しみは共有しようぜ、親友！"

# カズマ
# 無理なもんは無理なんだ。
178 = "無理なもんは無理なんだ。"

# カズマ（Ｍ）
# display as カズマ
# （あいつらを裏切るような真似はしたくねーし）
208 = "（あいつらを裏切るような真似はしたくねーし）"

# ダスト
# なあ、親友。\nちょこっとだけ見せてくれよ。
141 = "なあ、親友。\\nちょこっとだけ見せてくれよ。"

# カズマ（Ｍ）
# display as カズマ
# （しつこいな……）
210 = "（しつこいな……）"

# カズマ
# 別にいいけど、命を賭けられるのか？
172 = "別にいいけど、命を賭けられるのか？"

# キース
# は？
150 = "は？"

# カズマ
# うちの連中はお前たちが思ってる以上に凶暴だぞ。
125 = "うちの連中はお前たちが思ってる以上に凶暴だぞ。"

# ダスト
# ひっ！
151 = "ひっ！"

# カズマ
# パンツを見られたと知ったら……。
168 = "パンツを見られたと知ったら……。"

# キース
# あは、あははは、冗談に決まってるだろ！\n真に受けるなよ、カズマー。
122 = "あは、あははは、冗談に決まってるだろ！\\n真に受けるなよ、カズマー。"

# カズマ
# はぁ、お前らは悩みがなくて羨ましいよ。
146 = "はぁ、お前らは悩みがなくて羨ましいよ。"

# ダスト
# そうだ。\nカズマは、とにかく金が必要なんだよな？
134 = "そうだ。\\nカズマは、とにかく金が必要なんだよな？"

# カズマ
# この指輪を外してもらうためにな。
131 = "この指輪を外してもらうためにな。"

# キース
# だったら良い儲け話があるぜ？
137 = "だったら良い儲け話があるぜ？"

# カズマ
# はぁ？　儲け話？
147 = "はぁ？　儲け話？"

