# st02c_03.txt.scn

[info]
0 = ""

[characters]
291 = "アクア"
294 = "カズマ"
292 = "ウィズ"
299 = "カズマ（Ｍ）"
288 = "めぐみん"
303 = "ダクネス"
289 = "ゆんゆん"
300 = "クリス"
319 = "戦士風の男冒険者"
378 = "魔術師風の男冒険者"

[character_subs]
# 294 = "カズマ"
318 = "戦士冒険者"
377 = "魔術師冒険者"

[script]
# lines: 78

# アクア
# ひぃっ……ふぅっ……\nカズマさん、もう辛いんですけど\n私、リタイアしちゃいたいんですけど。
281 = "ひぃっ……ふぅっ……\\nカズマさん、もう辛いんですけど\\n私、リタイアしちゃいたいんですけど。"

# カズマ
# そんなのダメに決まってるだろ。
269 = "そんなのダメに決まってるだろ。"

# アクア
# ふぇ～ん……カズマの意地悪ぅ。
285 = "ふぇ～ん……カズマの意地悪ぅ。"

# カズマ
# ほら、引っ張ってやるから。
287 = "ほら、引っ張ってやるから。"

# アクア
# ふぇぇ、ありがとう、かじゅま～。
284 = "ふぇぇ、ありがとう、かじゅま～。"

# カズマ
# 良いかみんな、無理はするなよ。\nこのままの順位をキープしてけばいいからな。
373 = "良いかみんな、無理はするなよ。\\nこのままの順位をキープしてけばいいからな。"

# ウィズ
# あの、カズマさん、ダクネスさんが。
248 = "あの、カズマさん、ダクネスさんが。"

# カズマ
# ダクネスがどうした？\nまさかあいつ、遅れてるのか？
304 = "ダクネスがどうした？\\nまさかあいつ、遅れてるのか？"

# ウィズ
# いえ、そうではなくて。
250 = "いえ、そうではなくて。"

# カズマ（Ｍ）
# display as カズマ
# （あれ？　いない。\n　あいつ、いったいどこに……）
379 = "（あれ？　いない。\\n　あいつ、いったいどこに……）"

# めぐみん
# あっ、カズマ、あそこです！　先頭！
247 = "あっ、カズマ、あそこです！　先頭！"

# カズマ
# って、あいつ！\nなんで先頭走ってんだよ！
270 = "って、あいつ！\\nなんで先頭走ってんだよ！"

# ダクネス
# はぁっ……はぁっ……\n先頭に立つことで、後ろから追って来る\n全員の視線が、私に集まって。
280 = "はぁっ……はぁっ……\\n先頭に立つことで、後ろから追って来る\\n全員の視線が、私に集まって。"

# ダクネス
# 感じる。感じるぞ。\n体の至る所に獲物に飛び掛かろうとする獣のような\n鋭い眼差しを！
317 = "感じる。感じるぞ。\\n体の至る所に獲物に飛び掛かろうとする獣のような\\n鋭い眼差しを！"

# ダクネス
# くっ、しかし耐えなければいけない！
264 = "くっ、しかし耐えなければいけない！"

# ダクネス
# 私はまだ泳ぐことが未熟。\n陸上の競技で時間を稼がなければ！
372 = "私はまだ泳ぐことが未熟。\\n陸上の競技で時間を稼がなければ！"

# ダクネス
# あぁっ、どこを見ているんだ！\n胸かっ、それともっ、ああっ、下半身はいけない！\nそこは今っ、くっ、くぅぅ、やめてくれぇぇ！！
245 = "あぁっ、どこを見ているんだ！\\n胸かっ、それともっ、ああっ、下半身はいけない！\\nそこは今っ、くっ、くぅぅ、やめてくれぇぇ！！"

# カズマ
# 楽しそうだな、あいつ。
321 = "楽しそうだな、あいつ。"

# ウィズ
# あの、カズマさん。\n放っておいていいんですか？
249 = "あの、カズマさん。\\n放っておいていいんですか？"

# カズマ（Ｍ）
# display as カズマ
# （いくらダクネスに体力があるとはいえ、\n　チームの和を乱されるのは困るか）
380 = "（いくらダクネスに体力があるとはいえ、\\n　チームの和を乱されるのは困るか）"

# カズマ
# 作戦があるんだから、\n戻って来いよ変態クルセイダー！
310 = "作戦があるんだから、\\n戻って来いよ変態クルセイダー！"

# ダクネス
# なっ！　この大勢の前で変態呼ばわりするとは！
275 = "なっ！　この大勢の前で変態呼ばわりするとは！"

# ダクネス
# ふふ、カズマめ。\n日に日に鬼畜度に磨きをかけていくな。
286 = "ふふ、カズマめ。\\n日に日に鬼畜度に磨きをかけていくな。"

# カズマ
# なんか良くわからんが、\n見られたくないなら下がればいいだろ！
278 = "なんか良くわからんが、\\n見られたくないなら下がればいいだろ！"

# ダクネス
# それは、そうなのだが。
268 = "それは、そうなのだが。"

# ダクネス
# 今、スピードを落としたら獣共に掴まって、\n私はぁぁぁ！！
309 = "今、スピードを落としたら獣共に掴まって、\\n私はぁぁぁ！！"

# カズマ
# おいダクネス！　無理するなよ！
260 = "おいダクネス！　無理するなよ！"

# ダクネス
# 無理などしていない！\nむしろこうしていると、\nなぜだか力が湧いてくるんだ！
324 = "無理などしていない！\\nむしろこうしていると、\\nなぜだか力が湧いてくるんだ！"

# カズマ
# ダメだあいつ。早くなんとかしないと。
305 = "ダメだあいつ。早くなんとかしないと。"

# カズマ（Ｍ）
# display as カズマ
# （とはいえ、わざわざ隣にまで行って、\n　無理やり引っ張って来るのは俺が疲れるし――）
386 = "（とはいえ、わざわざ隣にまで行って、\\n　無理やり引っ張って来るのは俺が疲れるし――）"

# カズマ
# うおっ！？\nな、なんだこの地響きは？　地震か？
256 = "うおっ！？\\nな、なんだこの地響きは？　地震か？"

# ゆんゆん
# カズマさん、あそこ！
296 = "カズマさん、あそこ！"

# カズマ
# なっ！？
276 = "なっ！？"

# アクア
# ひいっ！？
282 = "ひいっ！？"

# めぐみん
# あ、あれは……。
243 = "あ、あれは……。"

# カズマ
# ジャイアントトードじゃねーか！？\nなんでこんな所に……。
301 = "ジャイアントトードじゃねーか！？\\nなんでこんな所に……。"

# クリス
# あたしたちの足音に驚いて出て来たんじゃ\nないかな？　これだけ大勢で走ってると、\n振動もすごいだろうし。
246 = "あたしたちの足音に驚いて出て来たんじゃ\\nないかな？　これだけ大勢で走ってると、\\n振動もすごいだろうし。"

# カズマ
# なるほどな。\nでも、よりにもよって、\n俺たちの向かってる先に出て来るなんて。
277 = "なるほどな。\\nでも、よりにもよって、\\n俺たちの向かってる先に出て来るなんて。"

# アクア
# いやー！　カエルはいやああああ！
252 = "いやー！　カエルはいやああああ！"

# めぐみん
# カカカカ、カズマ、引き返しましょう！
293 = "カカカカ、カズマ、引き返しましょう！"

# カズマ
# おい待て。落ち着けお前ら。
261 = "おい待て。落ち着けお前ら。"

# アクア
# 落ち着くなんて無理よ！！
374 = "落ち着くなんて無理よ！！"

# めぐみん
# ネバネバ、ほどよく生温かいネバネバ……。
306 = "ネバネバ、ほどよく生温かいネバネバ……。"

# カズマ（Ｍ）
# display as カズマ
# （くそっ、ネバネバトラウマ組が\n　完全にパニックになっちまってる！）
383 = "（くそっ、ネバネバトラウマ組が\\n　完全にパニックになっちまってる！）"

# クリス
# カズマ、ダクネスがジャイアントトードに！
295 = "カズマ、ダクネスがジャイアントトードに！"

# カズマ
# 食われたのか！
376 = "食われたのか！"

# クリス
# ううん、向かって行ってる……。
254 = "ううん、向かって行ってる……。"

# カズマ
# なんだと！？
279 = "なんだと！？"

# ダクネス
# ええい！\nせっかくいい所なのに邪魔をしおって！
258 = "ええい！\\nせっかくいい所なのに邪魔をしおって！"

# ダクネス
# うおおおおおおおおお！
255 = "うおおおおおおおおお！"

# カズマ
# 無闇に突っ込むな！\nそいつに物理攻撃はききにくいんだよ！！
325 = "無闇に突っ込むな！\\nそいつに物理攻撃はききにくいんだよ！！"

# ダクネス
# あ、ああ～～～～。
242 = "あ、ああ～～～～。"

# カズマ（Ｍ）
# display as カズマ
# （いわんこっちゃない……）
381 = "（いわんこっちゃない……）"

# 戦士風の男冒険者
# display as 戦士冒険者
# くそ！　あのカエル、\nレースを守ろうとしたダクネスさんをよくも！
263 = "くそ！　あのカエル、\\nレースを守ろうとしたダクネスさんをよくも！"

# カズマ（Ｍ）
# display as カズマ
# （ん？）
387 = "（ん？）"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# 俺たちもダクネスさんを見習いましょう！\nこのレース、中止になんてさせません！
311 = "俺たちもダクネスさんを見習いましょう！\\nこのレース、中止になんてさせません！"

# カズマ（Ｍ）
# display as カズマ
# （おお、冒険者たちがジャイアントトードに\n　向かっていく）
382 = "（おお、冒険者たちがジャイアントトードに\\n　向かっていく）"

# カズマ（Ｍ）
# display as カズマ
# （これはある意味、結果オーライか？）
385 = "（これはある意味、結果オーライか？）"

# ウィズ
# カズマさん、私たちも参戦しますか？
298 = "カズマさん、私たちも参戦しますか？"

# カズマ
# いや、待て。
251 = "いや、待て。"

# カズマ（Ｍ）
# display as カズマ
# （この棚ぼたの状況を\n　美味しくいただかない理由はないよな）
384 = "（この棚ぼたの状況を\\n　美味しくいただかない理由はないよな）"

# カズマ
# なあ、この隙に俺たちは先に――
273 = "なあ、この隙に俺たちは先に――"

# ダクネス
# あぁぁぁぁぁぁ～～～！！
244 = "あぁぁぁぁぁぁ～～～！！"

# ウィズ
# カズマさん、上！
297 = "カズマさん、上！"

# カズマ
# なっ、飛ばされたダクネスがこっちに！
274 = "なっ、飛ばされたダクネスがこっちに！"

# ウィズ
# このままでは地面に直撃ですよ！
265 = "このままでは地面に直撃ですよ！"

# カズマ
# よ、よし、俺が受けとめてっ！！
290 = "よ、よし、俺が受けとめてっ！！"

# ダクネス
# あぁぁぁぁぁぁ～～～！！
# 244 = "あぁぁぁぁぁぁ～～～！！"

# カズマ
# う、うう……ごめん、無理っ！
253 = "う、うう……ごめん、無理っ！"

# クリス
# ダ、ダクネス！
302 = "ダ、ダクネス！"

# カズマ
# おい、大丈夫か！
259 = "おい、大丈夫か！"

# ダクネス
# ふ、ふふ、受けとめると安心させておいての\nこの仕打ち――
283 = "ふ、ふふ、受けとめると安心させておいての\\nこの仕打ち――"

# ダクネス
# お前は本当に男の風上にも置けないな！
262 = "お前は本当に男の風上にも置けないな！"

# カズマ
# うん、ダクネスが喜んでくれて良かったよ。
257 = "うん、ダクネスが喜んでくれて良かったよ。"

# ダクネス
# というわけで、もう一度行ってくりゅ！\nうっひょぉぉぉぉぉ！！
271 = "というわけで、もう一度行ってくりゅ！\\nうっひょぉぉぉぉぉ！！"

# カズマ
# このバカーーーー！
266 = "このバカーーーー！"

# ウィズ
# ど、どうしますか？
272 = "ど、どうしますか？"

# カズマ
# しょうがない……俺たちも行こう。
267 = "しょうがない……俺たちも行こう。"

[selections]
320 = "戻って来いよ変態クルセイダー！"
375 = "見られたくないなら下がれば良いだろ！"
323 = "無理するなよ！"
