# st02c_05.txt.scn

[info]
0 = ""

[characters]
333 = "カズマ（Ｍ）"
315 = "めぐみん"
328 = "ウィズ"
318 = "ゆんゆん"
330 = "カズマ"
336 = "ダクネス"
335 = "クリス"
325 = "アクア"
316 = "めぐみん＆ゆんゆん"

[character_subs]
# 330 = "カズマ"
448 = "２人"

[script]
# lines: 134

# カズマ（Ｍ）
# display as カズマ
# （どうやらまだ誰も湖に入ってないようだな）
440 = "（どうやらまだ誰も湖に入ってないようだな）"

# カズマ（Ｍ）
# display as カズマ
# （くくく、これも予想通りだ）
431 = "（くくく、これも予想通りだ）"

# めぐみん
# はぁはぁ、ここまでで結構体力を\n使ってしまいましたね。
306 = "はぁはぁ、ここまでで結構体力を\\n使ってしまいましたね。"

# ウィズ
# わ、私、もうダメかもです。
323 = "わ、私、もうダメかもです。"

# ゆんゆん
# 私も～。
420 = "私も～。"

# カズマ
# なんだよ、もうばててるのか？
299 = "なんだよ、もうばててるのか？"

# ダクネス
# 情けないぞ３人とも。
356 = "情けないぞ３人とも。"

# クリス
# 魔法職に体力を求めるのは酷だよダクネス。
427 = "魔法職に体力を求めるのは酷だよダクネス。"

# カズマ
# まあいいや。\nさっさと着替えて一気に逆転するぞ！
310 = "まあいいや。\\nさっさと着替えて一気に逆転するぞ！"

# ウィズ
# でも、どこで着替えたら良いんでしょう？
293 = "でも、どこで着替えたら良いんでしょう？"

# ゆんゆん
# あそこのテントじゃないですか？
244 = "あそこのテントじゃないですか？"

# めぐみん
# なるほど。\n女性はあそこで着替えろということですね。
298 = "なるほど。\\n女性はあそこで着替えろということですね。"

# カズマ（Ｍ）
# display as カズマ
# （ん？　女性は？）
446 = "（ん？　女性は？）"

# カズマ
# ええと、男はどこで着替えるんだよ？
258 = "ええと、男はどこで着替えるんだよ？"

# ダクネス
# 見た所、その場で着替えているようだぞ。
424 = "見た所、その場で着替えているようだぞ。"

# カズマ
# 雑な扱いだなぁ、おい！\nそういう男女差別は良くないだろ！
425 = "雑な扱いだなぁ、おい！\\nそういう男女差別は良くないだろ！"

# めぐみん
# 良いじゃないですか。\n別に見られて困るわけでなし。
423 = "良いじゃないですか。\\n別に見られて困るわけでなし。"

# カズマ（Ｍ）
# display as カズマ
# （それはそうだけどさ……）
437 = "（それはそうだけどさ……）"

# めぐみん
# でも、ちょっとおかしいですね。
292 = "でも、ちょっとおかしいですね。"

# カズマ
# おかしいって何が。
262 = "おかしいって何が。"

# めぐみん
# 脱ぐだけでほとんど着替えの済むはずの\n男性冒険者たちが、なぜこんなに手間取って\nいるのでしょう？
421 = "脱ぐだけでほとんど着替えの済むはずの\\n男性冒険者たちが、なぜこんなに手間取って\\nいるのでしょう？"

# カズマ
# なぜって、\nチームの仲間を待ってるだけだろ。
297 = "なぜって、\\nチームの仲間を待ってるだけだろ。"

# ダクネス
# 感じる、感じるぞ。\n男共の邪な気配を！
357 = "感じる、感じるぞ。\\n男共の邪な気配を！"

# カズマ
# それはお前の思い込み――
283 = "それはお前の思い込み――"

# ウィズ
# というわけでもなさそうですが。
294 = "というわけでもなさそうですが。"

# ゆんゆん
# 着替えが終わった男の方たち、\nみなさんチラチラとテントを気にしていますね。
417 = "着替えが終わった男の方たち、\\nみなさんチラチラとテントを気にしていますね。"

# カズマ
# 女の水着が見たくて待ってるのかよ！
350 = "女の水着が見たくて待ってるのかよ！"

# めぐみん
# なんと浅ましい。
302 = "なんと浅ましい。"

# クリス
# 飢えてるねぇ。
426 = "飢えてるねぇ。"

# カズマ
# いや、それならそれで都合が良いや。\nお前ら、ちょっと耳を貸せ。
251 = "いや、それならそれで都合が良いや。\\nお前ら、ちょっと耳を貸せ。"

# めぐみん
# なんです？
301 = "なんです？"

# カズマ
# ごにょごにょ。
270 = "ごにょごにょ。"

# めぐみん
# ！？　正気ですか！
429 = "！？　正気ですか！"

# ゆんゆん
# 私、そんな恥ずかしいことできません。
419 = "私、そんな恥ずかしいことできません。"

# カズマ
# お前たちが着替える時間を稼ぐためだよ。\n着替えがすぐに終われば\nさっさと切り上げて出てくれば良いだけだ。
266 = "お前たちが着替える時間を稼ぐためだよ。\\n着替えがすぐに終われば\\nさっさと切り上げて出てくれば良いだけだ。"

# めぐみん
# ですが……。
289 = "ですが……。"

# カズマ
# ゆんゆんも嫌か？
320 = "ゆんゆんも嫌か？"

# ゆんゆん
# 恥ずかしいです……。
354 = "恥ずかしいです……。"

# カズマ
# そうか、この大会で優勝すれば\n賞金ががっぽり入って、指輪が外せるかも\nしれないのに。
275 = "そうか、この大会で優勝すれば\\n賞金ががっぽり入って、指輪が外せるかも\\nしれないのに。"

# カズマ
# 俺だったら、\n友達のために少しの恥ずかしい思いくらい\n耐えられるんだけど。
346 = "俺だったら、\\n友達のために少しの恥ずかしい思いくらい\\n耐えられるんだけど。"

# ゆんゆん
# 友達のため！？
347 = "友達のため！？"

# カズマ
# はぁ、しょうがない。\nこの大会で金を稼ぐのは諦めるか。
305 = "はぁ、しょうがない。\\nこの大会で金を稼ぐのは諦めるか。"

# ゆんゆん
# わ、私、やります！
324 = "わ、私、やります！"

# カズマ
# いやでも、恥ずかしいんだろ？
253 = "いやでも、恥ずかしいんだろ？"

# ゆんゆん
# お友達のためですもん！\nやります！　いいえ、やらせてください。
268 = "お友達のためですもん！\\nやります！　いいえ、やらせてください。"

# めぐみん
# あなたはどうしてそう、\n毎度毎度チョロイんですか！
245 = "あなたはどうしてそう、\\n毎度毎度チョロイんですか！"

# ゆんゆん
# な、何それ！\n私ちっともチョロくなんてないよ！
295 = "な、何それ！\\n私ちっともチョロくなんてないよ！"

# ウィズ
# まあまあ、落ち着いてください。
311 = "まあまあ、落ち着いてください。"

# ダクネス
# カズマのこういういやらしいところは\n今に始まったわけじゃないだろう。
332 = "カズマのこういういやらしいところは\\n今に始まったわけじゃないだろう。"

# クリス
# そうだよ。\nそれに優勝するためには、そういう策略も\n必要だと思うんだよね。
277 = "そうだよ。\\nそれに優勝するためには、そういう策略も\\n必要だと思うんだよね。"

# めぐみん
# それはそうですが。
284 = "それはそうですが。"

# ダクネス
# それとも、これからもカズマに下着を盗まれる\n恐怖に怯え続けるか？
282 = "それとも、これからもカズマに下着を盗まれる\\n恐怖に怯え続けるか？"

# めぐみん
# それは嫌ですよ！　絶対に！
285 = "それは嫌ですよ！　絶対に！"

# ゆんゆん
# だったらやるしかないよ、めぐみん！\nお友達のために！
286 = "だったらやるしかないよ、めぐみん！\\nお友達のために！"

# めぐみん
# 殴りたくなるので、\nあなたはもう喋らないでください。
358 = "殴りたくなるので、\\nあなたはもう喋らないでください。"

# ゆんゆん
# ええ、どうして！？
257 = "ええ、どうして！？"

# カズマ
# じゃあ、よろしく頼むぞ、みんな。
272 = "じゃあ、よろしく頼むぞ、みんな。"

# ゆんゆん
# では、カズマさん行ってきますね！
290 = "では、カズマさん行ってきますね！"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんのあのキラキラしたひとみを見てると、\n　ちょっとだけ罪悪感に苛まれるな……）
443 = "（ゆんゆんのあのキラキラしたひとみを見てると、\\n　ちょっとだけ罪悪感に苛まれるな……）"

# カズマ（Ｍ）
# display as カズマ
# （しかしこれも優勝するため！\n　頼むぞ、ゆんゆん、そしてみんな！）
436 = "（しかしこれも優勝するため！\\n　頼むぞ、ゆんゆん、そしてみんな！）"

# ゆんゆん
# わ、わー。めぐみん、カワイイ水着だねー。
322 = "わ、わー。めぐみん、カワイイ水着だねー。"

# めぐみん
# ゆんゆんこそ……\nおや？　また胸が大きくなったんじゃないですか？
319 = "ゆんゆんこそ……\\nおや？　また胸が大きくなったんじゃないですか？"

# ゆんゆん
# きゃー、揉まないでよ、めぐみーん！
269 = "きゃー、揉まないでよ、めぐみーん！"

# ウィズ
# はしたないですよ、おふたりとも。\n裸でそんなことをして。
307 = "はしたないですよ、おふたりとも。\\n裸でそんなことをして。"

# クリス
# そういうウィズだって、\n注意する前に、自分も早く水着を着ちゃいなよ。
274 = "そういうウィズだって、\\n注意する前に、自分も早く水着を着ちゃいなよ。"

# ダクネス
# まさか、見せびらかしているわけではあるまい？\nお、大きさでは私だって……負けては、おらんぞ。
312 = "まさか、見せびらかしているわけではあるまい？\\nお、大きさでは私だって……負けては、おらんぞ。"

# カズマ（Ｍ）
# display as カズマ
# （悲しくなるくらいの棒演技だな）
447 = "（悲しくなるくらいの棒演技だな）"

# カズマ（Ｍ）
# display as カズマ
# （でも、ほとんどの男たちが、\n　あいつらの会話に聞き耳を立てて、\n　着替える手さえ止まってる）
438 = "（でも、ほとんどの男たちが、\\n　あいつらの会話に聞き耳を立てて、\\n　着替える手さえ止まってる）"

# カズマ（Ｍ）
# display as カズマ
# （よしよし。\n　俺はこの隙に着替えて……）
445 = "（よしよし。\\n　俺はこの隙に着替えて……）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、水着は最初から下に着ちゃってるん\n　だけどな）
442 = "（まあ、水着は最初から下に着ちゃってるん\\n　だけどな）"

# カズマ（Ｍ）
# display as カズマ
# （よいしょ）
444 = "（よいしょ）"

# カズマ
# さて、これからどうするか？\nみんなを待ってても良いけど。
271 = "さて、これからどうするか？\\nみんなを待ってても良いけど。"

# カズマ（Ｍ）
# display as カズマ
# （でも、足止めを食らっている男たちとは違って\n　着替えを終えて出て来た女性陣が、\n　どんどん湖を渡り始めてるし）
439 = "（でも、足止めを食らっている男たちとは違って\\n　着替えを終えて出て来た女性陣が、\\n　どんどん湖を渡り始めてるし）"

# カズマ（Ｍ）
# display as カズマ
# （このままみんなを待つのも良いが、\n　俺だけ先に行ってタイムを稼ぐって\n　いうのも手ではあるか……よし）
432 = "（このままみんなを待つのも良いが、\\n　俺だけ先に行ってタイムを稼ぐって\\n　いうのも手ではあるか……よし）"

# カズマ
# おーい！　俺、先に行って――
264 = "おーい！　俺、先に行って――"

# めぐみん
# まったく、ゆんゆんは本当にけしからん体ですね。
313 = "まったく、ゆんゆんは本当にけしからん体ですね。"

# カズマ
# …………。
243 = "…………。"

# ゆんゆん
# あれ？　めぐみん。\nちょっと大きくなったんじゃない？
248 = "あれ？　めぐみん。\\nちょっと大きくなったんじゃない？"

# めぐみん
# なんですか、それ。嫌味ですか。\nたゆんたゆん弾ませて、\n私に見せつけているんですか！
300 = "なんですか、それ。嫌味ですか。\\nたゆんたゆん弾ませて、\\n私に見せつけているんですか！"

# ゆんゆん
# ちょ、ちょっとおっぱいを叩かないでよ！
287 = "ちょ、ちょっとおっぱいを叩かないでよ！"

# カズマ
# ！！
428 = "！！"

# めぐみん
# まったく。\nいったい何を食べたらこんな身体に\n育つのやら……。
314 = "まったく。\\nいったい何を食べたらこんな身体に\\n育つのやら……。"

# クリス
# ほんとだよ。羨ましいなー。
309 = "ほんとだよ。羨ましいなー。"

# ダクネス
# お、おいクリス？　同性とはいえ、\nそんなにまじまじと見られると、\nさすがに恥ずかしいというか。
259 = "お、おいクリス？　同性とはいえ、\\nそんなにまじまじと見られると、\\nさすがに恥ずかしいというか。"

# ウィズ
# ダクネスさん、私を盾にしないでください。\n私もまだ水着を着てないんですからー。
337 = "ダクネスさん、私を盾にしないでください。\\n私もまだ水着を着てないんですからー。"

# カズマ
# …………。
# 243 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （ねえ、なんなの？\n　もしかしてまだみんな裸なの？）
441 = "（ねえ、なんなの？\\n　もしかしてまだみんな裸なの？）"

# カズマ（Ｍ）
# display as カズマ
# （この布一枚隔てた向こうの世界は、\n　夢の国ですか！　桃源郷ですか！）
433 = "（この布一枚隔てた向こうの世界は、\\n　夢の国ですか！　桃源郷ですか！）"

# アクア
# 何してるのよ？　早く行かなくていいの？
343 = "何してるのよ？　早く行かなくていいの？"

# カズマ
# いま忙しいから、あとにしてくれるか。
250 = "いま忙しいから、あとにしてくれるか。"

# アクア
# なんなのよ。\n用事があるなら中に入ればいいじゃない。
303 = "なんなのよ。\\n用事があるなら中に入ればいいじゃない。"

# カズマ
# アホかお前は！\nそんなことしたら――って、アクア！
327 = "アホかお前は！\\nそんなことしたら――って、アクア！"

# カズマ
# お前、今までどこに行ってた！
265 = "お前、今までどこに行ってた！"

# アクア
# カエルが出たからちょっと避難してたのよ。
329 = "カエルが出たからちょっと避難してたのよ。"

# アクア
# 心配しなくても、失格になんてなってないわ。\nコースの隅で少しの間、ジッとしてただけだから。
353 = "心配しなくても、失格になんてなってないわ。\\nコースの隅で少しの間、ジッとしてただけだから。"

# カズマ
# そうか、ならいいけど。
276 = "そうか、ならいいけど。"

# カズマ
# でも、あとから来たのに、\nなんでもう着替えが済んでるんだ？\nテントはここのひとつしかないみたいなのに。
291 = "でも、あとから来たのに、\\nなんでもう着替えが済んでるんだ？\\nテントはここのひとつしかないみたいなのに。"

# アクア
# 着替えならそこでしたわよ？
418 = "着替えならそこでしたわよ？"

# カズマ
# そこって……草むらで？
278 = "そこって……草むらで？"

# アクア
# うん、もちろん。
255 = "うん、もちろん。"

# カズマ
# うん、もちろんって、お前はバカかー！
256 = "うん、もちろんって、お前はバカかー！"

# アクア
# な、何よ！
296 = "な、何よ！"

# カズマ
# お前は、腐っても一応女だよな！
267 = "お前は、腐っても一応女だよな！"

# アクア
# 腐ってないわよ、まだピチピチよ！
422 = "腐ってないわよ、まだピチピチよ！"

# カズマ
# そのピチピチが、面前で全裸になるな！\n女として終わってるだろ！
279 = "そのピチピチが、面前で全裸になるな！\\n女として終わってるだろ！"

# アクア
# あんた、なんか変な勘違いしてない？
249 = "あんた、なんか変な勘違いしてない？"

# カズマ
# は？　勘違い。
308 = "は？　勘違い。"

# アクア
# 水着は服の下に着て来たのよ。\nそんなの基本中の基本じゃない。
359 = "水着は服の下に着て来たのよ。\\nそんなの基本中の基本じゃない。"

# カズマ
# お、おう、そうだよな。
260 = "お、おう、そうだよな。"

# カズマ（Ｍ）
# display as カズマ
# （さすが元日本担当の女神。\n　良くわかっていらっしゃる）
434 = "（さすが元日本担当の女神。\\n　良くわかっていらっしゃる）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、あんな所で服を脱ぐとか、\n　こいつには恥じらいってものがないのか？）
435 = "（しかし、あんな所で服を脱ぐとか、\\n　こいつには恥じらいってものがないのか？）"

# カズマ（Ｍ）
# display as カズマ
# （いくら下に水着を着てるからって、\n　こいつ女を捨ててるんじゃないかって\n　心配になるな）
430 = "（いくら下に水着を着てるからって、\\n　こいつ女を捨ててるんじゃないかって\\n　心配になるな）"

# アクア
# 何よ。その可哀想な物を見る目は？
344 = "何よ。その可哀想な物を見る目は？"

# カズマ
# いや、なんでも……。
252 = "いや、なんでも……。"

# アクア
# あらあら、もしかして、\n水着姿の私に見とれちゃったのかしら？
247 = "あらあら、もしかして、\\n水着姿の私に見とれちゃったのかしら？"

# カズマ
# おい、ピチピチのアクア。
261 = "おい、ピチピチのアクア。"

# アクア
# 何？
345 = "何？"

# カズマ
# 今の言い方、ちょっとおばさんっぽかったぞ。
342 = "今の言い方、ちょっとおばさんっぽかったぞ。"

# アクア
# な！？
304 = "な！？"

# ダクネス
# カズマ、待たせたな！
331 = "カズマ、待たせたな！"

# めぐみん
# おや、アクアじゃないですか。
263 = "おや、アクアじゃないですか。"

# ウィズ
# アクア様、なんだか固まってません？
326 = "アクア様、なんだか固まってません？"

# カズマ
# ちょっとショックなことがあったらしい。
288 = "ちょっとショックなことがあったらしい。"

# クリス
# キミが、また何かやったんじゃないの？
334 = "キミが、また何かやったんじゃないの？"

# カズマ
# やってないって。
317 = "やってないって。"

# めぐみん
# それで、成果はどうだったんですか？
280 = "それで、成果はどうだったんですか？"

# カズマ
# バッチリ！
338 = "バッチリ！"

# クリス
# あはは、私たちがやったことの効果は\nまだ続いてるみたいだよ。
246 = "あはは、私たちがやったことの効果は\\nまだ続いてるみたいだよ。"

# ゆんゆん
# うぅぅ、ジロジロ見られて恥ずかしいよ。
254 = "うぅぅ、ジロジロ見られて恥ずかしいよ。"

# ダクネス
# そ、そうだな！
273 = "そ、そうだな！"

# クリス
# それで？　あたしたちはスタートしなくても\nいいのかな？
281 = "それで？　あたしたちはスタートしなくても\\nいいのかな？"

# ウィズ
# 恥ずかしい思いをしてまで作った時間なのですから、\n有効利用をしたいです。
355 = "恥ずかしい思いをしてまで作った時間なのですから、\\n有効利用をしたいです。"

# カズマ
# よし、じゃあ、行くか！！
321 = "よし、じゃあ、行くか！！"

# めぐみん＆ゆんゆん
# display as ２人
# …………。
# 243 = "…………。"

