# st02a_02.txt.scn

[info]
0 = ""

[characters]
151 = "カズマ（Ｍ）"
148 = "めぐみん"
149 = "カズマ"

[character_subs]
# 149 = "カズマ"

[script]
# lines: 31

# カズマ（Ｍ）
# display as カズマ
# （さて、どうするかな。\n　ここに居てもあいつらに問い詰められるだけ\n　だろうし……）
182 = "（さて、どうするかな。\\n　ここに居てもあいつらに問い詰められるだけ\\n　だろうし……）"

# カズマ（Ｍ）
# display as カズマ
# （そういえば、バニルは帰ってきたのか？）
183 = "（そういえば、バニルは帰ってきたのか？）"

# カズマ（Ｍ）
# display as カズマ
# （よし、まずはウィズの店に行ってみるか）
185 = "（よし、まずはウィズの店に行ってみるか）"

# カズマ（Ｍ）
# display as カズマ
# （いやでも、このパンツがウィズのだったら、\n　色々と気まずいよな――）
180 = "（いやでも、このパンツがウィズのだったら、\\n　色々と気まずいよな――）"

# めぐみん
# カズマ。
150 = "カズマ。"

# カズマ
# うひょー！？
133 = "うひょー！？"

# めぐみん
# なんです、そのおかしな悲鳴は？
145 = "なんです、そのおかしな悲鳴は？"

# カズマ
# あはははは、なんでもないぞ。
132 = "あはははは、なんでもないぞ。"

# めぐみん
# そうですか。\nそれで？　今、何を隠したんです？
140 = "そうですか。\\nそれで？　今、何を隠したんです？"

# カズマ
# おかしなこと言うなめぐみんは。\n常にフルオープンな俺が、いったい何を隠すって\nいうのさ。
134 = "おかしなこと言うなめぐみんは。\\n常にフルオープンな俺が、いったい何を隠すって\\nいうのさ。"

# めぐみん
# そういえば昨夜は、それは見事な満月でしたね。
139 = "そういえば昨夜は、それは見事な満月でしたね。"

# カズマ
# ……そうですね。
129 = "……そうですね。"

# めぐみん
# それで？　何を隠したんです？
142 = "それで？　何を隠したんです？"

# カズマ
# ぐ、ぐぬぬ……。
136 = "ぐ、ぐぬぬ……。"

# めぐみん
# さあさあ、早く見せてください、さあ！
137 = "さあさあ、早く見せてください、さあ！"

# カズマ
# ああ、そうさ！　パンツさパンツだよ！\nもちろん女物だ！\nなんか文句あるかロリっ子！！
130 = "ああ、そうさ！　パンツさパンツだよ！\\nもちろん女物だ！\\nなんか文句あるかロリっ子！！"

# めぐみん
# 開き直った上にロリっ子呼ばわりするとは！\nどうやら地獄に落とされたいようですね！
178 = "開き直った上にロリっ子呼ばわりするとは！\\nどうやら地獄に落とされたいようですね！"

# カズマ
# へいへい、できるもんならやってみな。\n爆裂魔法の詠唱が終わる前に、\n渾身の右ストレートをお見舞いしてやるぜ。
146 = "へいへい、できるもんならやってみな。\\n爆裂魔法の詠唱が終わる前に、\\n渾身の右ストレートをお見舞いしてやるぜ。"

# めぐみん
# 黒より黒く、闇より昏き漆黒に――
179 = "黒より黒く、闇より昏き漆黒に――"

# カズマ
# って、本当に詠唱するな、バカー！！
143 = "って、本当に詠唱するな、バカー！！"

# めぐみん
# むご、むぐぐ！！
147 = "むご、むぐぐ！！"

# カズマ（Ｍ）
# display as カズマ
# （くそ、これ以上めぐみんを怒らせたら、\n　状況がややこしくなるだけだ）
181 = "（くそ、これ以上めぐみんを怒らせたら、\\n　状況がややこしくなるだけだ）"

# カズマ（Ｍ）
# display as カズマ
# （ひとまず、今は逃げるか！）
184 = "（ひとまず、今は逃げるか！）"

# めぐみん
# あっ、どこへ行くんですか！
131 = "あっ、どこへ行くんですか！"

# カズマ
# お前に言う必要はない！
135 = "お前に言う必要はない！"

# めぐみん
# 逃げおおせると思っているんですか！
177 = "逃げおおせると思っているんですか！"

# めぐみん
# そっちは玄関とは逆方向、\n外に出たければ私を倒していくといいです！
141 = "そっちは玄関とは逆方向、\\n外に出たければ私を倒していくといいです！"

# カズマ
# 出入り口が玄関だけだと思うなよ！\nとう！
154 = "出入り口が玄関だけだと思うなよ！\\nとう！"

# めぐみん
# なっ、窓からっ！
144 = "なっ、窓からっ！"

# カズマ
# しゅた！！
138 = "しゅた！！"

# カズマ（Ｍ）
# display as カズマ
# （よし、まずはウィズの店に避難だ！）
186 = "（よし、まずはウィズの店に避難だ！）"

