# st02b_04.txt.scn

[info]
0 = ""

[characters]
205 = "カズマ"
198 = "めぐみん"
202 = "ゆんゆん"
206 = "カズマ（Ｍ）"
204 = "アクア"

[character_subs]
# 205 = "カズマ"

[script]
# lines: 61

# カズマ
# うーん、ゆんゆんは……。
163 = "うーん、ゆんゆんは……。"

# めぐみん
# ……うっ。
153 = "……うっ。"

# カズマ
# どうした？
185 = "どうした？"

# めぐみん
# あー、もう、どうしてすぐに声をかけて\nこないんですか！
156 = "あー、もう、どうしてすぐに声をかけて\\nこないんですか！"

# ゆんゆん
# だ、だって、私が急に入って場がしらけたら嫌だし。
181 = "だ、だって、私が急に入って場がしらけたら嫌だし。"

# めぐみん
# あーっ、もうっ、あいかわらずめんどうですね！\nこのぼっちは！
157 = "あーっ、もうっ、あいかわらずめんどうですね！\\nこのぼっちは！"

# ゆんゆん
# ぼっちなんて酷い！\n私だってお友達がいるんだからね！
194 = "ぼっちなんて酷い！\\n私だってお友達がいるんだからね！"

# めぐみん
# それは興味深いですね。\nどこの誰なんです？　私に紹介してくださいよ。
179 = "それは興味深いですね。\\nどこの誰なんです？　私に紹介してくださいよ。"

# ゆんゆん
# う、うう、それは……。
160 = "う、うう、それは……。"

# めぐみん
# さあさあ、早く。\nお友達ができたんでしょう？\n喜ばしいことじゃないですか！
171 = "さあさあ、早く。\\nお友達ができたんでしょう？\\n喜ばしいことじゃないですか！"

# ゆんゆん
# う、うぅ、うぅぅ……。
159 = "う、うぅ、うぅぅ……。"

# カズマ
# めぐみん、それ以上追い詰めるな。\nマジ泣きしそうだから。
199 = "めぐみん、それ以上追い詰めるな。\\nマジ泣きしそうだから。"

# めぐみん
# わかってますよ。
203 = "わかってますよ。"

# カズマ
# ええと、ゆんゆん？\nちょっと話を聞いて欲しいんだけどいいかな？
169 = "ええと、ゆんゆん？\\nちょっと話を聞いて欲しいんだけどいいかな？"

# ゆんゆん
# 私にお話！　な、なんでしょう！
256 = "私にお話！　な、なんでしょう！"

# めぐみん
# どうして嬉しそうにするんですか……。
186 = "どうして嬉しそうにするんですか……。"

# カズマ
# 実はまた、頼みがあるんだ。
213 = "実はまた、頼みがあるんだ。"

# ゆんゆん
# え……。
164 = "え……。"

# めぐみん
# 今一瞬、嫌そうな顔をしましたよね。
208 = "今一瞬、嫌そうな顔をしましたよね。"

# ゆんゆん
# し、してないよ！
172 = "し、してないよ！"

# めぐみん
# まあいいです。\nカズマ話の続きを。
196 = "まあいいです。\\nカズマ話の続きを。"

# カズマ
# また金を稼ぐ方法を思いついたんだけど、\nそれをするにはどうしてもゆんゆんの協力が\n必要なんだよ。
197 = "また金を稼ぐ方法を思いついたんだけど、\\nそれをするにはどうしてもゆんゆんの協力が\\n必要なんだよ。"

# ゆんゆん
# え、ええと、今度は何をさせられるのでしょう。
165 = "え、ええと、今度は何をさせられるのでしょう。"

# めぐみん
# 水着を着て貰います。
216 = "水着を着て貰います。"

# ゆんゆん
# ええー、水着！？
170 = "ええー、水着！？"

# めぐみん
# なんです、嫌なんですか？
187 = "なんです、嫌なんですか？"

# ゆんゆん
# だって、恥ずかしい。
183 = "だって、恥ずかしい。"

# めぐみん
# はぁ、しょうがありませんね。\nゆんゆんは諦めましょう、カズマ。
189 = "はぁ、しょうがありませんね。\\nゆんゆんは諦めましょう、カズマ。"

# カズマ
# ええ、そんなあっさり！
166 = "ええ、そんなあっさり！"

# めぐみん
# だって本人にやる気がないんですよ。\n無理強いも悪いじゃないですか。
184 = "だって本人にやる気がないんですよ。\\n無理強いも悪いじゃないですか。"

# ゆんゆん
# そんな！\n話を聞かされてもいないのに。
180 = "そんな！\\n話を聞かされてもいないのに。"

# めぐみん
# はぁ、本当に残念です。\n友達のゆんゆんなら何も聞かずとも\n引き受けてくれると思っていたのに。
190 = "はぁ、本当に残念です。\\n友達のゆんゆんなら何も聞かずとも\\n引き受けてくれると思っていたのに。"

# ゆんゆん
# 友達！？
210 = "友達！？"

# めぐみん
# 私は、ゆんゆんが困っていると知ったら、\nどんなに困難が待っているとわかっていても\n助けに向かいますよ。
257 = "私は、ゆんゆんが困っていると知ったら、\\nどんなに困難が待っているとわかっていても\\n助けに向かいますよ。"

# ゆんゆん
# 私も同じだよ、めぐみん！
258 = "私も同じだよ、めぐみん！"

# めぐみん
# じゃあ、引き受けてくれますね？
173 = "じゃあ、引き受けてくれますね？"

# ゆんゆん
# もちろんだよ！
201 = "もちろんだよ！"

# めぐみん
# はい、交渉成立です。
192 = "はい、交渉成立です。"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんのチョロさも大概だが、\n　めぐみんの手綱さばきも恐ろしい）
261 = "（ゆんゆんのチョロさも大概だが、\\n　めぐみんの手綱さばきも恐ろしい）"

# ゆんゆん
# それで、あの、私は何をしたらいいんでしょうか。
178 = "それで、あの、私は何をしたらいいんでしょうか。"

# カズマ
# その前に、この街で毎年行われてる運動会を\n知ってるか？
174 = "その前に、この街で毎年行われてる運動会を\\n知ってるか？"

# ゆんゆん
# いえ、初耳です。
158 = "いえ、初耳です。"

# カズマ
# その大会の賞金の額が結構すごいらしいんだよ。
175 = "その大会の賞金の額が結構すごいらしいんだよ。"

# アクア
# ２０００万エリスよ！
262 = "２０００万エリスよ！"

# カズマ
# うん、ありがとうな、アクア。
162 = "うん、ありがとうな、アクア。"

# カズマ
# その２０００万エリスを獲得するために、\nゆんゆんの力を貸して欲しいんだ。
176 = "その２０００万エリスを獲得するために、\\nゆんゆんの力を貸して欲しいんだ。"

# ゆんゆん
# 具体的に何をしたらいいんでしょう。
209 = "具体的に何をしたらいいんでしょう。"

# めぐみん
# なんです。\nその内容次第では断るつもりなんですか？
188 = "なんです。\\nその内容次第では断るつもりなんですか？"

# ゆんゆん
# 違うよ、準備とか必要かもしれないでしょ！
259 = "違うよ、準備とか必要かもしれないでしょ！"

# めぐみん
# だったら水着を用意しておいてください。\n今日の午後から水泳の特訓を始めますから。
182 = "だったら水着を用意しておいてください。\\n今日の午後から水泳の特訓を始めますから。"

# ゆんゆん
# ええ、急すぎる！
167 = "ええ、急すぎる！"

# カズマ
# もしかして予定があるのか？
200 = "もしかして予定があるのか？"

# めぐみん
# ぼっちのゆんゆんに、\n予定なんてあるわけないじゃないですか。
195 = "ぼっちのゆんゆんに、\\n予定なんてあるわけないじゃないですか。"

# ゆんゆん
# ひ、酷いよめぐみん。私にだって予定くらい――
193 = "ひ、酷いよめぐみん。私にだって予定くらい――"

# めぐみん
# あるんですか？
155 = "あるんですか？"

# ゆんゆん
# ……ないけど。
154 = "……ないけど。"

# カズマ
# ええと、じゃあ、午後からの特訓には\n来て貰えるか？
168 = "ええと、じゃあ、午後からの特訓には\\n来て貰えるか？"

# ゆんゆん
# はい、もちろんです！
191 = "はい、もちろんです！"

# カズマ
# それじゃ、昼過ぎくらいに、\n街の入り口の辺りに集まってくれ。
177 = "それじゃ、昼過ぎくらいに、\\n街の入り口の辺りに集まってくれ。"

# ゆんゆん
# うぅ、急いで水着を買いに行かないと。
161 = "うぅ、急いで水着を買いに行かないと。"

# カズマ（Ｍ）
# display as カズマ
# （さて、次はクリスか）
260 = "（さて、次はクリスか）"

