# st02b_05.txt.scn

[info]
0 = ""

[characters]
140 = "カズマ"
138 = "アクア"
142 = "カズマ（Ｍ）"
134 = "めぐみん"
144 = "ダクネス"

[character_subs]
# 140 = "カズマ"

[script]
# lines: 23

# カズマ
# よし。これで７人揃ったな。
136 = "よし。これで７人揃ったな。"

# カズマ
# クリスとゆんゆんにも言ったが、\n水泳の特訓は午後からやるつもりだから、\n昼飯を食ったら街の入り口に集まってくれ。
143 = "クリスとゆんゆんにも言ったが、\\n水泳の特訓は午後からやるつもりだから、\\n昼飯を食ったら街の入り口に集まってくれ。"

# アクア
# はーい、お昼ご飯はカズマのおごりがいいです。
132 = "はーい、お昼ご飯はカズマのおごりがいいです。"

# カズマ
# なんでおごらなくちゃいけないんだよ。
131 = "なんでおごらなくちゃいけないんだよ。"

# アクア
# こんな面倒なことに巻き込んでるんだから、\nご飯くらいおごっても罰は当たらないと思うわよ？
128 = "こんな面倒なことに巻き込んでるんだから、\\nご飯くらいおごっても罰は当たらないと思うわよ？"

# カズマ（Ｍ）
# display as カズマ
# （ふざけるなと言いたい所だが、\n　実際、アクアたちの協力が無いと\n　どうしようもないわけだし……）
171 = "（ふざけるなと言いたい所だが、\\n　実際、アクアたちの協力が無いと\\n　どうしようもないわけだし……）"

# カズマ
# わかった、今回だけだぞ。
137 = "わかった、今回だけだぞ。"

# アクア
# やったー！　何を食べようかしら。
135 = "やったー！　何を食べようかしら。"

# めぐみん
# アクア、正気ですか？\nこのあと私たちは水着になるんですよ？
139 = "アクア、正気ですか？\\nこのあと私たちは水着になるんですよ？"

# アクア
# うん、だから何？
126 = "うん、だから何？"

# めぐみん
# 知りませんよ？　おなかがぽっこりしても。
167 = "知りませんよ？　おなかがぽっこりしても。"

# アクア
# あっ……。
125 = "あっ……。"

# めぐみん
# カズマ、言っておきますが、\n紅魔族はいくら暴飲暴食をしたところで\nプロポーションが崩れたりはしないんですからね？
141 = "カズマ、言っておきますが、\\n紅魔族はいくら暴飲暴食をしたところで\\nプロポーションが崩れたりはしないんですからね？"

# めぐみん
# ですが念のためといいますか……\n今日はあまりおなかが減っていないので、\nお昼は我慢することにしておきます。
130 = "ですが念のためといいますか……\\n今日はあまりおなかが減っていないので、\\nお昼は我慢することにしておきます。"

# アクア
# め、女神だってそういうのは大丈夫だけど、\n我慢しておくわ。
133 = "め、女神だってそういうのは大丈夫だけど、\\n我慢しておくわ。"

# カズマ
# お前ら面倒くさいな。
127 = "お前ら面倒くさいな。"

# ダクネス
# 女にはいろいろあるということだ。
148 = "女にはいろいろあるということだ。"

# カズマ
# そういうダクネスは昼飯どうするんだよ？
129 = "そういうダクネスは昼飯どうするんだよ？"

# ダクネス
# 私は普通に食べるつもりだが？
169 = "私は普通に食べるつもりだが？"

# アクア
# 自分だけズルいわよダクネス！
170 = "自分だけズルいわよダクネス！"

# めぐみん
# 私たちに付き合ってくださいよ。
168 = "私たちに付き合ってくださいよ。"

# ダクネス
# 昼食を抜いたら、力を出せないだろう。
151 = "昼食を抜いたら、力を出せないだろう。"

# カズマ（Ｍ）
# display as カズマ
# （女っていうのは大変なんだな。本当に）
172 = "（女っていうのは大変なんだな。本当に）"

