# st02b_02.txt.scn

[info]
0 = ""

[characters]
137 = "カズマ"
142 = "ダクネス"
131 = "めぐみん"
138 = "カズマ（Ｍ）"
136 = "アクア"

[character_subs]
# 137 = "カズマ"

[script]
# lines: 21

# カズマ
# というわけで、人数が足りない。どうしよう。
127 = "というわけで、人数が足りない。どうしよう。"

# ダクネス
# １チーム７人ということは、あと２人必要だな。
165 = "１チーム７人ということは、あと２人必要だな。"

# カズマ
# メイド喫茶の時も協力をしてくれたし、\nまずはクリスとゆんゆんに声をかけてみるか。
143 = "メイド喫茶の時も協力をしてくれたし、\\nまずはクリスとゆんゆんに声をかけてみるか。"

# めぐみん
# ゆんゆんに頼むんですか？
132 = "ゆんゆんに頼むんですか？"

# カズマ
# なんだよ、そんな嫌そうな顔して？
129 = "なんだよ、そんな嫌そうな顔して？"

# めぐみん
# あまりあの子に頼み事はしたくないんですよね。\nめんどくさいですし。
123 = "あまりあの子に頼み事はしたくないんですよね。\\nめんどくさいですし。"

# カズマ
# 友達なんだからそういう言い方するな。
146 = "友達なんだからそういう言い方するな。"

# めぐみん
# 友達だから言ってるんですよ。
145 = "友達だから言ってるんですよ。"

# めぐみん
# そもそも、カズマに協力してくれそうな\n友達は他にいないんですか？
126 = "そもそも、カズマに協力してくれそうな\\n友達は他にいないんですか？"

# カズマ（Ｍ）
# display as カズマ
# （そう言われると、\n　ダストやキースたち以外の友達なんて……）
164 = "（そう言われると、\\n　ダストやキースたち以外の友達なんて……）"

# カズマ（Ｍ）
# display as カズマ
# （いや、突き詰めて考えてみると、\n　あいつらが俺のことを友達と\n　思ってくれてるとは限らないわけで……）
163 = "（いや、突き詰めて考えてみると、\\n　あいつらが俺のことを友達と\\n　思ってくれてるとは限らないわけで……）"

# めぐみん
# カズマ？
139 = "カズマ？"

# カズマ
# あ、あはは……友達？\n何それ？　おいしいの？
122 = "あ、あはは……友達？\\n何それ？　おいしいの？"

# めぐみん
# …………。
121 = "…………。"

# めぐみん
# わかりましたよ。\nゆんゆんに頼んでみますから、\nしっかりしてください。
135 = "わかりましたよ。\\nゆんゆんに頼んでみますから、\\nしっかりしてください。"

# カズマ
# しくしく……。
124 = "しくしく……。"

# ダクネス
# とりあえず２人を誘いに行ってみないか？
128 = "とりあえず２人を誘いに行ってみないか？"

# アクア
# ほら、カズマ。\nへこんでないで行きましょう。
130 = "ほら、カズマ。\\nへこんでないで行きましょう。"

# カズマ
# そうだな……。\nじゃあ、まずは――
125 = "そうだな……。\\nじゃあ、まずは――"

# カズマ
# クリスを誘いに行ってみるか。
141 = "クリスを誘いに行ってみるか。"

# カズマ
# ゆんゆんを誘ってみるか。
134 = "ゆんゆんを誘ってみるか。"

[selections]
140 = "クリスの所に行こう"
133 = "ゆんゆんの所に行こう"
