# st02b_03.txt.scn

[info]
0 = ""

[characters]
173 = "カズマ"
180 = "ダクネス"
176 = "クリス"
170 = "めぐみん"
171 = "アクア"
174 = "カズマ（Ｍ）"

[character_subs]
# 173 = "カズマ"

[script]
# lines: 45

# カズマ
# クリスはこの辺にいるのか？
179 = "クリスはこの辺にいるのか？"

# ダクネス
# 特に用事がない時は、\nこの辺りをぶらついてることがあるらしい。
194 = "特に用事がない時は、\\nこの辺りをぶらついてることがあるらしい。"

# クリス
# あれ？　こんな所で何してるの？
148 = "あれ？　こんな所で何してるの？"

# カズマ
# 良かった。本当に会えた。
224 = "良かった。本当に会えた。"

# クリス
# え？　あたしに用事？
154 = "え？　あたしに用事？"

# カズマ
# うん、また頼みたいことがあるんだよ。
150 = "うん、また頼みたいことがあるんだよ。"

# クリス
# 頼みたいことって、何さ。
225 = "頼みたいことって、何さ。"

# ダクネス
# クリス、気持ちはわかるが、\nそんな警戒をしないでくれ。
177 = "クリス、気持ちはわかるが、\\nそんな警戒をしないでくれ。"

# クリス
# そうは言うけどさ、\n前回のメイド喫茶の件もあるし。
157 = "そうは言うけどさ、\\n前回のメイド喫茶の件もあるし。"

# めぐみん
# 今回はあのような変な格好をしたりしませんから、\n安心してください。
182 = "今回はあのような変な格好をしたりしませんから、\\n安心してください。"

# クリス
# 本当に？
192 = "本当に？"

# ダクネス
# ただ、水着を着ることにはなるかな。
160 = "ただ、水着を着ることにはなるかな。"

# クリス
# それくらいだったら構わないけど、\n今度はいったい、何をするつもりなのさ。
159 = "それくらいだったら構わないけど、\\n今度はいったい、何をするつもりなのさ。"

# ダクネス
# クリスは、この街で年に１度行われる\n運動会を知ってるか？
178 = "クリスは、この街で年に１度行われる\\n運動会を知ってるか？"

# クリス
# うん、知ってるよ。\n結構な額の賞金が出るんだよね。
151 = "うん、知ってるよ。\\n結構な額の賞金が出るんだよね。"

# アクア
# ２０００万エリスよ！
229 = "２０００万エリスよ！"

# カズマ
# 目の色を変えるな、目の色を。
195 = "目の色を変えるな、目の色を。"

# クリス
# あっ、話が読めた。\n私にもその大会に参加して欲しいんだね。
147 = "あっ、話が読めた。\\n私にもその大会に参加して欲しいんだね。"

# アクア
# そうよ、私の２０００万エリスのために！
158 = "そうよ、私の２０００万エリスのために！"

# カズマ
# アクア、悪いけど少し黙っててくれるか？
172 = "アクア、悪いけど少し黙っててくれるか？"

# クリス
# つまり、２０００万エリスをゲットするため、\n少しでも味方の参加者を増やして確率を上げたい。
161 = "つまり、２０００万エリスをゲットするため、\\n少しでも味方の参加者を増やして確率を上げたい。"

# クリス
# キミの考えは、これであってるかな？
175 = "キミの考えは、これであってるかな？"

# カズマ
# うーん、去年までみたいな個人戦だったら、\nそれもできたんだろうけど――
152 = "うーん、去年までみたいな個人戦だったら、\\nそれもできたんだろうけど――"

# ダクネス
# 今年から、７人１チームのチーム戦に変更された\nらしいんだ。
183 = "今年から、７人１チームのチーム戦に変更された\\nらしいんだ。"

# クリス
# なるほど、チームの頭数が足りないと。
165 = "なるほど、チームの頭数が足りないと。"

# カズマ
# 頼むクリス！\n俺たちに力を貸してくれ！
226 = "頼むクリス！\\n俺たちに力を貸してくれ！"

# アクア
# ２０００万エリスよ、２０００万エリス！\n断る理由なんてないわよね！
228 = "２０００万エリスよ、２０００万エリス！\\n断る理由なんてないわよね！"

# クリス
# う、うーん……。
149 = "う、うーん……。"

# ダクネス
# 私からも、この通りだ。\nクリスに協力してもらえると助かる。
223 = "私からも、この通りだ。\\nクリスに協力してもらえると助かる。"

# クリス
# 念のための確認。\n水着は、自分で選んでいいんだよね？
189 = "念のための確認。\\n水着は、自分で選んでいいんだよね？"

# カズマ
# あ、当たり前だろ！
146 = "あ、当たり前だろ！"

# めぐみん
# でも特訓を名目にいやらしい目で見られますよ。
163 = "でも特訓を名目にいやらしい目で見られますよ。"

# カズマ
# みみみ、見ねーから！
169 = "みみみ、見ねーから！"

# クリス
# まあ、指輪をどうにかしようと真面目にやってる\nみたいだし、手伝うのは構わないよ。
167 = "まあ、指輪をどうにかしようと真面目にやってる\\nみたいだし、手伝うのは構わないよ。"

# カズマ
# おお、ありがとう！
155 = "おお、ありがとう！"

# ダクネス
# 助かるよ、クリス。
184 = "助かるよ、クリス。"

# カズマ
# じゃあ、午後からみんなで水泳の特訓をする\n予定だから、それにクリスも参加してくれないか？
156 = "じゃあ、午後からみんなで水泳の特訓をする\\n予定だから、それにクリスも参加してくれないか？"

# クリス
# ええ！　そんな急なの！？
153 = "ええ！　そんな急なの！？"

# カズマ
# 昼過ぎくらいに、\n街の入り口の辺りで待ち合わせな。
190 = "昼過ぎくらいに、\\n街の入り口の辺りで待ち合わせな。"

# クリス
# はいはい。
166 = "はいはい。"

# めぐみん
# では、次はゆんゆんですね。
162 = "では、次はゆんゆんですね。"

# アクア
# またウィズの店かしら？
168 = "またウィズの店かしら？"

# めぐみん
# どうでしょう。
164 = "どうでしょう。"

# めぐみん
# 最近は、川の方でぼっちを患っていると\nこの前言ってましたし、まずはそっちへ\n行ってみましょう。
191 = "最近は、川の方でぼっちを患っていると\\nこの前言ってましたし、まずはそっちへ\\n行ってみましょう。"

# カズマ（Ｍ）
# display as カズマ
# （ぼっちを患うって……）
227 = "（ぼっちを患うって……）"

