# st02c_02.txt.scn

[info]
0 = ""

[characters]
298 = "ダクネス"
295 = "クリス"
293 = "カズマ"
282 = "ゆんゆん"
279 = "めぐみん"
288 = "アクア"
292 = "ウィズ"
299 = "ルナ"
294 = "カズマ（Ｍ）"

[character_subs]
# 293 = "カズマ"

[script]
# lines: 94

# ダクネス
# ここもすごい人出だな。
240 = "ここもすごい人出だな。"

# クリス
# ほとんどが冒険者だから、\n全員ライバルになるんだけどね。
273 = "ほとんどが冒険者だから、\\n全員ライバルになるんだけどね。"

# カズマ
# こういうのを見ると、\nいよいよ始まるって感じがするな。
238 = "こういうのを見ると、\\nいよいよ始まるって感じがするな。"

# ゆんゆん
# うぅ、胃に効くお薬持ってくればよかった。
231 = "うぅ、胃に効くお薬持ってくればよかった。"

# めぐみん
# な、な、情けないですよ、ゆんゆん。\nこれくらいのことで緊張なんて！
264 = "な、な、情けないですよ、ゆんゆん。\\nこれくらいのことで緊張なんて！"

# アクア
# よし、なんかテンションが上がってきたわ！
283 = "よし、なんかテンションが上がってきたわ！"

# ウィズ
# ええとええと、準備運動をしないと。
232 = "ええとええと、準備運動をしないと。"

# カズマ
# まとまりねー。\n大丈夫なのかこれ。
277 = "まとまりねー。\\n大丈夫なのかこれ。"

# ダクネス
# はは、少し不安ではあるな。
271 = "はは、少し不安ではあるな。"

# カズマ
# はぁ、お前まで緊張してたりしないよな？
268 = "はぁ、お前まで緊張してたりしないよな？"

# ダクネス
# 緊張？　しているさ！
366 = "緊張？　しているさ！"

# ダクネス
# なんと言っても、\nこんな大勢に水着姿を凝視される上に、\nいやらしい妄想をされるのだから！
266 = "なんと言っても、\\nこんな大勢に水着姿を凝視される上に、\\nいやらしい妄想をされるのだから！"

# カズマ
# お前は、その発想はおかしいといい加減気づけ！
235 = "お前は、その発想はおかしいといい加減気づけ！"

# アクア
# ねえねえ、カズマ。
267 = "ねえねえ、カズマ。"

# カズマ
# なんだよ？
265 = "なんだよ？"

# アクア
# お腹すいたんだけど、お弁当はないの？
236 = "お腹すいたんだけど、お弁当はないの？"

# カズマ
# あるわけないだろ。\nあったとしても食うのは大会の後だ。
224 = "あるわけないだろ。\\nあったとしても食うのは大会の後だ。"

# アクア
# えー、どうしてよ。\nお腹が空いてたら力がでないじゃない。
233 = "えー、どうしてよ。\\nお腹が空いてたら力がでないじゃない。"

# ウィズ
# アクア様、朝食を食べられなかったのですか？
291 = "アクア様、朝食を食べられなかったのですか？"

# アクア
# 寝坊したから\nちょっとしか食べてないのよね。
307 = "寝坊したから\\nちょっとしか食べてないのよね。"

# カズマ
# 食いすぎで走れなくなるよりはマシだ。\n我慢しろ。
369 = "食いすぎで走れなくなるよりはマシだ。\\n我慢しろ。"

# ルナ
# あー、あー。\nお集りの皆様、お待たせいたしました。
225 = "あー、あー。\\nお集りの皆様、お待たせいたしました。"

# カズマ（Ｍ）
# display as カズマ
# （お？　そろそろ始まるか？）
371 = "（お？　そろそろ始まるか？）"

# ルナ
# 本日はギルド主催の運動会にご参加いただき、\n誠にありがとうございます。
314 = "本日はギルド主催の運動会にご参加いただき、\\n誠にありがとうございます。"

# ルナ
# まもなくスタートの時刻となりますが、\nその前に、あらためてルール等の説明を\nさせていただきます。
278 = "まもなくスタートの時刻となりますが、\\nその前に、あらためてルール等の説明を\\nさせていただきます。"

# ルナ
# まず、コースに関してですが、\nこの正門をスタート地点として、\n湖までを道に沿って走っていただきます。
275 = "まず、コースに関してですが、\\nこの正門をスタート地点として、\\n湖までを道に沿って走っていただきます。"

# ルナ
# その際、道から逸れて\nショートカット等をした場合は\n失格とさせていただきますのでご注意ください。
248 = "その際、道から逸れて\\nショートカット等をした場合は\\n失格とさせていただきますのでご注意ください。"

# ルナ
# 仮に遠回りなどをした場合も、\nこちらとしては判断が難しいので、\n同様に失格という形にさせていただきます。
301 = "仮に遠回りなどをした場合も、\\nこちらとしては判断が難しいので、\\n同様に失格という形にさせていただきます。"

# ルナ
# 湖に到着したら、\n持参した水着に着替えていただき、\n対岸まで渡ると、そこがゴールとなります。
318 = "湖に到着したら、\\n持参した水着に着替えていただき、\\n対岸まで渡ると、そこがゴールとなります。"

# ルナ
# その際、服のまま湖に入るのは\n危険なので禁止とさせていただきます。
247 = "その際、服のまま湖に入るのは\\n危険なので禁止とさせていただきます。"

# ルナ
# また、着替えの時間も\n最終的なタイムに含まれますのでご注意ください。
276 = "また、着替えの時間も\\n最終的なタイムに含まれますのでご注意ください。"

# ルナ
# そうしてチーム全員がゴールし、合計した\nタイムがもっとも早かったチームが優勝となります。
245 = "そうしてチーム全員がゴールし、合計した\\nタイムがもっとも早かったチームが優勝となります。"

# カズマ（Ｍ）
# display as カズマ
# （ルールは聞いていた通りだな）
373 = "（ルールは聞いていた通りだな）"

# カズマ
# よし、みんな！\n緊張するのはここまでだ！
284 = "よし、みんな！\\n緊張するのはここまでだ！"

# カズマ
# そろそろ気合いを……。
254 = "そろそろ気合いを……。"

# アクア
# …………。
221 = "…………。"

# カズマ
# って、おい、アクア。\nなんだよ、その顔。
258 = "って、おい、アクア。\\nなんだよ、その顔。"

# アクア
# 忘れた。
312 = "忘れた。"

# カズマ
# 忘れたって何を？
313 = "忘れたって何を？"

# アクア
# 水着……持ってきてないの。
317 = "水着……持ってきてないの。"

# カズマ
# はぁぁぁぁぁ？\n何やってんだよお前は！
269 = "はぁぁぁぁぁ？\\n何やってんだよお前は！"

# アクア
# だ、だって、屋敷を出る時、\n誰も言ってくれなかったから……。
255 = "だ、だって、屋敷を出る時、\\n誰も言ってくれなかったから……。"

# カズマ
# それはお前が寝坊したせいもあるだろ！\n時間があれば、ちゃんと荷物の確認を\nできたんだよ！
253 = "それはお前が寝坊したせいもあるだろ！\\n時間があれば、ちゃんと荷物の確認を\\nできたんだよ！"

# アクア
# うぅ、ど、どうしようカズマ、\nこのままじゃ私の２０００万エリスが……。
230 = "うぅ、ど、どうしようカズマ、\\nこのままじゃ私の２０００万エリスが……。"

# カズマ
# こうなったら、もうそのまま泳げ！
239 = "こうなったら、もうそのまま泳げ！"

# ダクネス
# いや、それは危険だから禁止されているだろう？
229 = "いや、それは危険だから禁止されているだろう？"

# カズマ
# あ、そうか。
222 = "あ、そうか。"

# カズマ
# じゃあ……全裸だ！
242 = "じゃあ……全裸だ！"

# アクア
# それってカズマが私の裸を見たいだけでしょ……。
250 = "それってカズマが私の裸を見たいだけでしょ……。"

# カズマ
# 俺にだって選ぶ権利あるわ！
303 = "俺にだって選ぶ権利あるわ！"

# アクア
# 何それ、どういう意味！\nちょっと失礼だと思うんですけど！
302 = "何それ、どういう意味！\\nちょっと失礼だと思うんですけど！"

# めぐみん
# ふたりとも、今はくだらない言い合いを\nしている時じゃないでしょう。
272 = "ふたりとも、今はくだらない言い合いを\\nしている時じゃないでしょう。"

# カズマ
# わ、わかってる！
287 = "わ、わかってる！"

# カズマ（Ｍ）
# display as カズマ
# （とりあえず落ちつけ俺。\n　この大会で優勝するのにアクアは必要不可欠\n　なんだ）
372 = "（とりあえず落ちつけ俺。\\n　この大会で優勝するのにアクアは必要不可欠\\n　なんだ）"

# カズマ（Ｍ）
# display as カズマ
# （服のままはダメ、全裸は当然却下）
374 = "（服のままはダメ、全裸は当然却下）"

# カズマ
# そうだ、下着！
246 = "そうだ、下着！"

# アクア
# 正気？
316 = "正気？"

# カズマ
# ですよねー？
260 = "ですよねー？"

# めぐみん
# どこかで買うというのはどうでしょう？
263 = "どこかで買うというのはどうでしょう？"

# カズマ
# それだ！
249 = "それだ！"

# クリス
# 着替えることになるから\n貴重品は必要最低限って話じゃなかった？
365 = "着替えることになるから\\n貴重品は必要最低限って話じゃなかった？"

# カズマ
# 屋台で飲み食いするくらいの金しか\n持ってきてねー！
308 = "屋台で飲み食いするくらいの金しか\\n持ってきてねー！"

# カズマ（Ｍ）
# display as カズマ
# （ああ、もう、八方ふさがりじゃねえか！！）
370 = "（ああ、もう、八方ふさがりじゃねえか！！）"

# ルナ
# サトウさん、何かトラブルですか？
296 = "サトウさん、何かトラブルですか？"

# カズマ
# あ、ちょうど良かった。
223 = "あ、ちょうど良かった。"

# カズマ
# アクアが水着を忘れちゃったらしくて、\nこいつが取りに行って戻るまで待って貰うことは。
290 = "アクアが水着を忘れちゃったらしくて、\\nこいつが取りに行って戻るまで待って貰うことは。"

# ルナ
# さすがに、個人の事情でスタートを遅らせる\nわけには……。
241 = "さすがに、個人の事情でスタートを遅らせる\\nわけには……。"

# カズマ
# そ、そうですよね。
243 = "そ、そうですよね。"

# ルナ
# スタートまでまだ少し時間がありますし、\n急いで取りに行くというのは……。
297 = "スタートまでまだ少し時間がありますし、\\n急いで取りに行くというのは……。"

# カズマ
# よし、アクア走れ！
285 = "よし、アクア走れ！"

# アクア
# あーん！　なんで私がー！
226 = "あーん！　なんで私がー！"

# カズマ
# いいからダッシュ！\n２０００万エリスがかかってるんだぞ！
228 = "いいからダッシュ！\\n２０００万エリスがかかってるんだぞ！"

# アクア
# もー、やだー。
281 = "もー、やだー。"

# カズマ
# 遅い。遅すぎる。
368 = "遅い。遅すぎる。"

# ダクネス
# 屋敷までの距離を考えたら仕方ないと思うが。
309 = "屋敷までの距離を考えたら仕方ないと思うが。"

# ルナ
# では皆様、準備はよろしいですか？
261 = "では皆様、準備はよろしいですか？"

# めぐみん
# もう始まってしまいますよ！？
280 = "もう始まってしまいますよ！？"

# カズマ
# 肝心な時に足引っぱりやがって、\n本当に迷惑な駄女神だな、あいつは！
367 = "肝心な時に足引っぱりやがって、\\n本当に迷惑な駄女神だな、あいつは！"

# ゆんゆん
# どうします？　置いてっちゃうんですか？
262 = "どうします？　置いてっちゃうんですか？"

# クリス
# そういうわけにもいかないよ。\nチームの合計タイムが重要なんだから。
244 = "そういうわけにもいかないよ。\\nチームの合計タイムが重要なんだから。"

# ウィズ
# だからといって、\n全員で出遅れてしまうのも大変ですが。
256 = "だからといって、\\n全員で出遅れてしまうのも大変ですが。"

# アクア
# か、か、かじゅまぁ～～～～！
237 = "か、か、かじゅまぁ～～～～！"

# カズマ
# 来たか！
315 = "来たか！"

# アクア
# はぁっ……はぁっ……はぁっ……うぷっ！
270 = "はぁっ……はぁっ……はぁっ……うぷっ！"

# カズマ
# よーし、偉いぞアクア。良く間に合わせた。
286 = "よーし、偉いぞアクア。良く間に合わせた。"

# アクア
# でしょう？\n私だって……やる時は、やるんだから。
259 = "でしょう？\\n私だって……やる時は、やるんだから。"

# アクア
# だけど、限界っていうか、\n少し休まないと、競争とか無理。\nちょっと吐きそうだし。
257 = "だけど、限界っていうか、\\n少し休まないと、競争とか無理。\\nちょっと吐きそうだし。"

# ルナ
# それでは時間です。行きますよ？
252 = "それでは時間です。行きますよ？"

# カズマ
# アクア。\n残念だけど休んでる時間はないみたいだ。
289 = "アクア。\\n残念だけど休んでる時間はないみたいだ。"

# アクア
# え？　そんな――
234 = "え？　そんな――"

# ルナ
# それでは、スタートです！！
251 = "それでは、スタートです！！"

# カズマ
# ほら行くぞ！
274 = "ほら行くぞ！"

# アクア
# あーん！　カズマのバカぁ！　鬼ぃ！　変態ぃ！
227 = "あーん！　カズマのバカぁ！　鬼ぃ！　変態ぃ！"

# カズマ
# 変態は関係ないよね！
306 = "変態は関係ないよね！"

