# st02c_07.txt.scn

[info]
0 = ""

[characters]
226 = "カズマ"
223 = "アクア"
228 = "カズマ（Ｍ）"
244 = "戦士風の男冒険者"
276 = "魔術師風の男冒険者"
249 = "盗賊風の男冒険者"
230 = "ダクネス"
216 = "めぐみん"
222 = "ゆんゆん"
229 = "クリス"
224 = "ウィズ"

[character_subs]
# 226 = "カズマ"
243 = "戦士冒険者"
275 = "魔術師冒険者"
248 = "盗賊冒険者"

[script]
# lines: 42

# カズマ
# あー、死ぬかと思った。
196 = "あー、死ぬかと思った。"

# アクア
# ぐすっ……ありがとね、カズマ。\nおかげで助かったわ、本当に良かった。
204 = "ぐすっ……ありがとね、カズマ。\\nおかげで助かったわ、本当に良かった。"

# カズマ
# 泣くほど怖かったのかよ、お前。
246 = "泣くほど怖かったのかよ、お前。"

# アクア
# だって、ワニは無理だもん。
207 = "だって、ワニは無理だもん。"

# カズマ
# でだ、そろそろ離れてくれると\nありがたいんだが。
209 = "でだ、そろそろ離れてくれると\\nありがたいんだが。"

# アクア
# もうちょっとだけこうさせてて。\n人肌って落ち着くの。
219 = "もうちょっとだけこうさせてて。\\n人肌って落ち着くの。"

# カズマ
# なんなんだよ、お前は。
212 = "なんなんだよ、お前は。"

# カズマ（Ｍ）
# display as カズマ
# （おっと、そういえばダクネスは……）
278 = "（おっと、そういえばダクネスは……）"

# 戦士風の男冒険者
# display as 戦士冒険者
# おお！　ダクネスさんが素手で\nあんなにも大量のモンスターと渡り合ってるぞ！
201 = "おお！　ダクネスさんが素手で\\nあんなにも大量のモンスターと渡り合ってるぞ！"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# 水着一枚しか身に付けていないのに、\n鋭い牙に物怖じもせず、なんて勇敢なんだ。
245 = "水着一枚しか身に付けていないのに、\\n鋭い牙に物怖じもせず、なんて勇敢なんだ。"

# 盗賊風の男冒険者
# display as 盗賊冒険者
# 見ろ、あの紅潮した顔を。\nあんなにも必死にみんなの盾になろうとして、\n格好良すぎる！　憧れちまうぜ！
273 = "見ろ、あの紅潮した顔を。\\nあんなにも必死にみんなの盾になろうとして、\\n格好良すぎる！　憧れちまうぜ！"

# ダクネス
# くうっ！　ワニ共が群がって……\n身体が揉みくちゃに……牙も当たって……\n痛っ……ああっ、なんて屈辱！
203 = "くうっ！　ワニ共が群がって……\\n身体が揉みくちゃに……牙も当たって……\\n痛っ……ああっ、なんて屈辱！"

# カズマ（Ｍ）
# display as カズマ
# （うん、放っておいて良いんじゃないかな。\n　あいつは）
277 = "（うん、放っておいて良いんじゃないかな。\\n　あいつは）"

# めぐみん
# 待たせましたね、カズマ。
240 = "待たせましたね、カズマ。"

# カズマ
# …………。
194 = "…………。"

# めぐみん
# なんです。人をジロジロと見て。
211 = "なんです。人をジロジロと見て。"

# カズマ
# どうしてお前は、杖を持ってるんだよ。\nしかも眼帯まで装備して。
210 = "どうしてお前は、杖を持ってるんだよ。\\nしかも眼帯まで装備して。"

# めぐみん
# ふっ。知れたこと。
215 = "ふっ。知れたこと。"

# めぐみん
# 我が名はめぐみん！\n紅魔族随一の魔法の使い手にして、\n爆裂魔法をこよなく愛する者！
242 = "我が名はめぐみん！\\n紅魔族随一の魔法の使い手にして、\\n爆裂魔法をこよなく愛する者！"

# めぐみん
# 皆の楽しむ行事を妨げる下等な魔物たちよ！\nその身の滅びをもって詫びるが良い！
247 = "皆の楽しむ行事を妨げる下等な魔物たちよ！\\nその身の滅びをもって詫びるが良い！"

# ゆんゆん
# ちょっとめぐみん！？\nまさか爆裂魔法を撃つつもりなの！？
208 = "ちょっとめぐみん！？\\nまさか爆裂魔法を撃つつもりなの！？"

# クリス
# 待った待った！\nあの真ん中にはダクネスだっているんだからね！
241 = "待った待った！\\nあの真ん中にはダクネスだっているんだからね！"

# ウィズ
# カズマさん！\nめぐみんさんを止めてください！
227 = "カズマさん！\\nめぐみんさんを止めてください！"

# カズマ
# ええと……。
198 = "ええと……。"

# カズマ（Ｍ）
# display as カズマ
# （辺りを見回してみると、\n　すでにダクネス以外の参加者は\n　湖から上がって避難を終えているようだ）
281 = "（辺りを見回してみると、\\n　すでにダクネス以外の参加者は\\n　湖から上がって避難を終えているようだ）"

# カズマ（Ｍ）
# display as カズマ
# （それなら、問題なのはダクネスだけだな）
279 = "（それなら、問題なのはダクネスだけだな）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、ダクネスの硬さなら、\n　爆裂魔法の直撃にも耐えられるだろうが）
280 = "（まあ、ダクネスの硬さなら、\\n　爆裂魔法の直撃にも耐えられるだろうが）"

# カズマ
# めぐみん、やるなら全力でやっちまえ！
217 = "めぐみん、やるなら全力でやっちまえ！"

# めぐみん
# ふっ、では遠慮なく……。
213 = "ふっ、では遠慮なく……。"

# カズマ
# めぐみん、余計な被害は出すなよ？
218 = "めぐみん、余計な被害は出すなよ？"

# めぐみん
# そんなのわかっていますとも。
206 = "そんなのわかっていますとも。"

# カズマ
# やめろめぐみん！\n運動会が中止になっちまうだろ！
220 = "やめろめぐみん！\\n運動会が中止になっちまうだろ！"

# めぐみん
# 問答無用です！
237 = "問答無用です！"

# カズマ
# おい！　めぐみん！
200 = "おい！　めぐみん！"

# めぐみん
# エクスプローーーージョンっ！！！
225 = "エクスプローーーージョンっ！！！"

# ダクネス
# ああああああああああああああっ！！！！
195 = "ああああああああああああああっ！！！！"

# めぐみん
# ふっ、完璧です。
214 = "ふっ、完璧です。"

# ゆんゆん
# きゃあ、めぐみん！
202 = "きゃあ、めぐみん！"

# クリス
# ダクネス大丈夫！？
231 = "ダクネス大丈夫！？"

# アクア
# うぅ、ぐす、怖かった、怖かったよぉ。
197 = "うぅ、ぐす、怖かった、怖かったよぉ。"

# ウィズ
# ええと、カズマさん。
199 = "ええと、カズマさん。"

# カズマ
# これ、大会どうなっちまうんだ。
205 = "これ、大会どうなっちまうんだ。"

[selections]
221 = "やるなら全力でやっちまえ！"
234 = "余計な被害は出すなよ？"
274 = "運動会が中止になっちまうだろ！"
