# st02a_06.txt.scn

[info]
0 = ""

[characters]
231 = "カズマ（Ｍ）"
225 = "ウィズ"
227 = "カズマ"
233 = "ダクネス"

[character_subs]
# 227 = "カズマ"

[script]
# lines: 72

# カズマ（Ｍ）
# display as カズマ
# （それにしても、運動会って\n　予想の斜め上を行くにも程があるだろ）
295 = "（それにしても、運動会って\\n　予想の斜め上を行くにも程があるだろ）"

# カズマ（Ｍ）
# display as カズマ
# （日本のいろんな物が持ち込まれてる世界だし、\n　そこら辺が影響してるのかもな）
304 = "（日本のいろんな物が持ち込まれてる世界だし、\\n　そこら辺が影響してるのかもな）"

# カズマ（Ｍ）
# display as カズマ
# （なんにせよ、優勝したら賞金が出るって\n　いうなら全力で行くしかないな）
298 = "（なんにせよ、優勝したら賞金が出るって\\n　いうなら全力で行くしかないな）"

# カズマ（Ｍ）
# display as カズマ
# （問題はあいつらが協力をしてくれるかだ……）
303 = "（問題はあいつらが協力をしてくれるかだ……）"

# ウィズ
# はぁはぁはぁ、カズマさーん。
214 = "はぁはぁはぁ、カズマさーん。"

# カズマ（Ｍ）
# display as カズマ
# （あれ、ウィズ？）
292 = "（あれ、ウィズ？）"

# ウィズ
# はぁぁ、ようやく見つかりました。
213 = "はぁぁ、ようやく見つかりました。"

# カズマ
# 何か用事があるのか？
237 = "何か用事があるのか？"

# ウィズ
# いえその、カズマさんが上の空で出て行かれたので、\nちょっと心配だったといいますか。
192 = "いえその、カズマさんが上の空で出て行かれたので、\\nちょっと心配だったといいますか。"

# カズマ（Ｍ）
# display as カズマ
# （だから俺を捜しててくれたのか！\n　なんていい子なんだ！）
296 = "（だから俺を捜しててくれたのか！\\n　なんていい子なんだ！）"

# ウィズ
# 私が倒れてるとき、\nバニルさんと何かお話をしたんですか？
288 = "私が倒れてるとき、\\nバニルさんと何かお話をしたんですか？"

# カズマ
# ええと……別に何もしてないよ。
197 = "ええと……別に何もしてないよ。"

# ウィズ
# 本当ですか？
248 = "本当ですか？"

# カズマ（Ｍ）
# display as カズマ
# （ウィズに本当のことを話して、\n　解除金を負けさせるっていうのも\n　ありだけど――）
301 = "（ウィズに本当のことを話して、\\n　解除金を負けさせるっていうのも\\n　ありだけど――）"

# カズマ（Ｍ）
# display as カズマ
# （バニルの機嫌を損ねちまったら、\n　解除をしてくれなくなるかもしれないし……）
302 = "（バニルの機嫌を損ねちまったら、\\n　解除をしてくれなくなるかもしれないし……）"

# ウィズ
# カズマさん？
230 = "カズマさん？"

# カズマ
# 実はウィズが倒れてるときに。
243 = "実はウィズが倒れてるときに。"

# ウィズ
# わ、私が倒れてるときに？
221 = "わ、私が倒れてるときに？"

# カズマ
# スカートの中をちらっと！
232 = "スカートの中をちらっと！"

# ウィズ
# ええーーーー！！\nみみみみ、見たんですか！！
198 = "ええーーーー！！\\nみみみみ、見たんですか！！"

# カズマ
# ふふふ、あんなセクシーなのを穿いてるなんて、\nウィズったら、もう！
216 = "ふふふ、あんなセクシーなのを穿いてるなんて、\\nウィズったら、もう！"

# ウィズ
# へ？　セクシー？
217 = "へ？　セクシー？"

# カズマ
# あれ、もしかして可愛い系だった？
188 = "あれ、もしかして可愛い系だった？"

# ウィズ
# そういう意味じゃ無くてですね！\nもう、そういう冗談は困ります。
202 = "そういう意味じゃ無くてですね！\\nもう、そういう冗談は困ります。"

# カズマ
# ハハハ、悪い悪い。\nバニルとはたいした話をしてないから、\n平気だよ。
235 = "ハハハ、悪い悪い。\\nバニルとはたいした話をしてないから、\\n平気だよ。"

# ウィズ
# それならいいんですけど。
206 = "それならいいんですけど。"

# カズマ
# んじゃ、俺は用事があるから。
223 = "んじゃ、俺は用事があるから。"

# ウィズ
# あっ、待ってください！
184 = "あっ、待ってください！"

# カズマ（Ｍ）
# display as カズマ
# （ん？）
300 = "（ん？）"

# ウィズ
# あの、ええと、スカートの中、\n本当に見ていないんですよね？
185 = "あの、ええと、スカートの中、\\n本当に見ていないんですよね？"

# カズマ
# まさかクマさんプリントとは！
219 = "まさかクマさんプリントとは！"

# ウィズ
# カズマさん……。
229 = "カズマさん……。"

# カズマ
# いくらなんでも、そんなことしないって。\n信じてくれよ。
193 = "いくらなんでも、そんなことしないって。\\n信じてくれよ。"

# ウィズ
# そうですよね。\n疑ったりしてすみませんでした。
205 = "そうですよね。\\n疑ったりしてすみませんでした。"

# ダクネス
# カズマ、こんなところにいたのか。
228 = "カズマ、こんなところにいたのか。"

# カズマ
# なんだ、お前も俺を捜してたのか？
211 = "なんだ、お前も俺を捜してたのか？"

# ダクネス
# ああ、話があって――
183 = "ああ、話があって――"

# カズマ
# ちょうど良かった、俺もお前たちに話したいことが\nあったんだよ。
207 = "ちょうど良かった、俺もお前たちに話したいことが\\nあったんだよ。"

# ダクネス
# ん、なんだ？
222 = "ん、なんだ？"

# カズマ
# いや俺の用事はあとでいいから。\nお前の用事はなんなんだ？
195 = "いや俺の用事はあとでいいから。\\nお前の用事はなんなんだ？"

# ダクネス
# え、ええと、実はだな――
196 = "え、ええと、実はだな――"

# ウィズ
# あのぉ、私が聞いていても大丈夫なお話\nなのでしょうか。
186 = "あのぉ、私が聞いていても大丈夫なお話\\nなのでしょうか。"

# ダクネス
# ！？　ウィズ、いたのか！？
291 = "！？　ウィズ、いたのか！？"

# ウィズ
# は、はい。すみません。
212 = "は、はい。すみません。"

# カズマ
# いや、別に謝る必要はないと思うけど？
194 = "いや、別に謝る必要はないと思うけど？"

# ウィズ
# そうですね。あはは。
204 = "そうですね。あはは。"

# ダクネス
# …………。
181 = "…………。"

# カズマ
# どうした？\nウィズがいると話せないようなことなのか？
210 = "どうした？\\nウィズがいると話せないようなことなのか？"

# ダクネス
# そういうわけでは。\nだが、その、なんというか。
201 = "そういうわけでは。\\nだが、その、なんというか。"

# ダクネス
# くっ、無自覚に辱めてくるとは、\nさすがはカズマと言うべきか、\nいや、わかっていて言っているのか？
199 = "くっ、無自覚に辱めてくるとは、\\nさすがはカズマと言うべきか、\\nいや、わかっていて言っているのか？"

# カズマ（Ｍ）
# display as カズマ
# （いったい何が引き金になって、\n　面白妄想にスイッチが入ったんだ……）
293 = "（いったい何が引き金になって、\\n　面白妄想にスイッチが入ったんだ……）"

# ダクネス
# や、やめろ馬鹿者ぉ！\n舐め回すように身体を見るなぁ！
220 = "や、やめろ馬鹿者ぉ！\\n舐め回すように身体を見るなぁ！"

# カズマ
# とかいいながら、両手を広げんてるんじゃないよ！\nてか、見てねーし！
209 = "とかいいながら、両手を広げんてるんじゃないよ！\\nてか、見てねーし！"

# ウィズ
# あ、ダクネスさんももしかして。
182 = "あ、ダクネスさんももしかして。"

# カズマ
# ダクネスがどうかしたか？
234 = "ダクネスがどうかしたか？"

# ウィズ
# いえ、なんでもないです。
190 = "いえ、なんでもないです。"

# カズマ（Ｍ）
# display as カズマ
# （なんかさっきから様子が変だな）
297 = "（なんかさっきから様子が変だな）"

# カズマ（Ｍ）
# display as カズマ
# （いや、今はそんなことよりも\n　みんなから運動会の情報を聞き出さないとな）
294 = "（いや、今はそんなことよりも\\n　みんなから運動会の情報を聞き出さないとな）"

# カズマ
# じゃあウィズ、俺たちはこれで。\n心配してくれてありがとな。
200 = "じゃあウィズ、俺たちはこれで。\\n心配してくれてありがとな。"

# ウィズ
# 待ってください。私もお邪魔して良いですか？
247 = "待ってください。私もお邪魔して良いですか？"

# カズマ
# 遠慮するなよ。\n俺だってウィズの店には良く行ってるんだし、\nウィズだって来たい時に来てくれて構わないさ。
290 = "遠慮するなよ。\\n俺だってウィズの店には良く行ってるんだし、\\nウィズだって来たい時に来てくれて構わないさ。"

# ウィズ
# ありがとうございます。
187 = "ありがとうございます。"

# カズマ
# 別に構わないぜ。\nたいしたもてなしはできないけどな。
239 = "別に構わないぜ。\\nたいしたもてなしはできないけどな。"

# ウィズ
# いえいえ、お気遣いなく。
191 = "いえいえ、お気遣いなく。"

# カズマ
# ウチに来るとアクアがいるけど大丈夫か？
226 = "ウチに来るとアクアがいるけど大丈夫か？"

# ウィズ
# はい。最近はアクア様にも\n良くしていただいていますし。
215 = "はい。最近はアクア様にも\\n良くしていただいていますし。"

# カズマ
# そうかなぁ……。
203 = "そうかなぁ……。"

# カズマ（Ｍ）
# display as カズマ
# （確かに出会った頃と比べたら、\n　いきなり確保やら浄化やらしようと\n　しなくなったとは思うけど……）
305 = "（確かに出会った頃と比べたら、\\n　いきなり確保やら浄化やらしようと\\n　しなくなったとは思うけど……）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、ウィズがいいって言うなら、\n　俺が気にする必要もないか）
299 = "（まあ、ウィズがいいって言うなら、\\n　俺が気にする必要もないか）"

# カズマ
# でも、急にどうしたんだ？\nアクアかめぐみんに用でもあるのか？
208 = "でも、急にどうしたんだ？\\nアクアかめぐみんに用でもあるのか？"

# ウィズ
# い、いえ、ただ、なんとなくと言いますか。
189 = "い、いえ、ただ、なんとなくと言いますか。"

# カズマ
# まあいいや。\nじゃあ、屋敷に戻ろうぜ。
218 = "まあいいや。\\nじゃあ、屋敷に戻ろうぜ。"

[selections]
289 = "遠慮するなよ"
238 = "別に構わないぜ"
224 = "アクアがいるけど大丈夫か？"
