# st02c_08.txt.scn

[info]
0 = ""

[characters]
161 = "アクア"
163 = "カズマ"
167 = "ダクネス"
168 = "ルナ"
162 = "ウィズ"
159 = "めぐみん"
166 = "クリス"
165 = "カズマ（Ｍ）"

[character_subs]
# 163 = "カズマ"

[script]
# lines: 29

# アクア
# それで、結局どうなるわけ？
151 = "それで、結局どうなるわけ？"

# カズマ
# その説明をこれからギルドがしてくれるんだろ。
149 = "その説明をこれからギルドがしてくれるんだろ。"

# アクア
# このまま中止になっちゃうのかしら？\nその場合、優勝賞金はどうなっちゃうの？
146 = "このまま中止になっちゃうのかしら？\\nその場合、優勝賞金はどうなっちゃうの？"

# カズマ
# だから！　それもギルドからの説明を待てって！
154 = "だから！　それもギルドからの説明を待てって！"

# アクア
# むー……。
158 = "むー……。"

# ダクネス
# おい、説明が始まるようだぞ。
143 = "おい、説明が始まるようだぞ。"

# ルナ
# えー、本来でしたら、モンスターが出ようと、\nそれも障害の一つだとし、レースを続ける\n規則なのですが――
142 = "えー、本来でしたら、モンスターが出ようと、\\nそれも障害の一つだとし、レースを続ける\\n規則なのですが――"

# ルナ
# 今回につきましては、\nモンスターが爆裂魔法による極度のストレスにより\n凶暴化してしまいましたので――
170 = "今回につきましては、\\nモンスターが爆裂魔法による極度のストレスにより\\n凶暴化してしまいましたので――"

# ルナ
# 冒険者の皆さまの安全を第一に考え\n大会は中止とさせていただきます。
173 = "冒険者の皆さまの安全を第一に考え\\n大会は中止とさせていただきます。"

# カズマ
# やっぱりそうなるか……。
160 = "やっぱりそうなるか……。"

# ルナ
# それと同時に、ギルドからの謝罪と、\nモンスター討伐の報酬ということで――
152 = "それと同時に、ギルドからの謝罪と、\\nモンスター討伐の報酬ということで――"

# ルナ
# 参加者全員に、優勝賞金を分配して\nお渡しすることも決定いたしました。
174 = "参加者全員に、優勝賞金を分配して\\nお渡しすることも決定いたしました。"

# アクア
# 賞金の分配！！\nねえねえ、それってどれくらいの額になるの？
199 = "賞金の分配！！\\nねえねえ、それってどれくらいの額になるの？"

# ウィズ
# そうですね……これだけ参加者が居ると、\n食事一食分にでもなればいい方なんじゃ\nないでしょうか？
148 = "そうですね……これだけ参加者が居ると、\\n食事一食分にでもなればいい方なんじゃ\\nないでしょうか？"

# カズマ
# それっぽっちかよ。
150 = "それっぽっちかよ。"

# アクア
# なんて顔をしてるのよ。\n一食分の食費が浮いたんだから、\nよかったじゃない。
156 = "なんて顔をしてるのよ。\\n一食分の食費が浮いたんだから、\\nよかったじゃない。"

# カズマ
# お前って、変にポジティブだよな。
144 = "お前って、変にポジティブだよな。"

# めぐみん
# それに、不届きな魔物を成敗することが\nできましたしね。
153 = "それに、不届きな魔物を成敗することが\\nできましたしね。"

# カズマ
# お前はそりゃすっきりだろうよ！\n爆裂魔法をモンスターの群れに撃てたんだから！
145 = "お前はそりゃすっきりだろうよ！\\n爆裂魔法をモンスターの群れに撃てたんだから！"

# めぐみん
# 今回に関しては、それだけじゃないんですよっ！
171 = "今回に関しては、それだけじゃないんですよっ！"

# カズマ
# どういう意味だよ。
155 = "どういう意味だよ。"

# めぐみん
# そ、それは……。
147 = "そ、それは……。"

# クリス
# あのワニたちにさ、\nぜんぜん相手にされなかったんだよ、\nあたしとめぐみんだけ。
140 = "あのワニたちにさ、\\nぜんぜん相手にされなかったんだよ、\\nあたしとめぐみんだけ。"

# カズマ
# ああ。あいつら、巨乳好きだったのか。
139 = "ああ。あいつら、巨乳好きだったのか。"

# めぐみん
# 何か言いましたか？
172 = "何か言いましたか？"

# カズマ
# い、いや、別に何も。
141 = "い、いや、別に何も。"

# アクア
# カズマ。\n早く打ち上げに行きましょう。
164 = "カズマ。\\n早く打ち上げに行きましょう。"

# カズマ
# はいはい、わかったよ。
157 = "はいはい、わかったよ。"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、結局今回も徒労に終わっちまったな）
200 = "（はぁ、結局今回も徒労に終わっちまったな）"

