# st02b_10.txt.scn

[info]
0 = ""

[characters]
313 = "カズマ（Ｍ）"
299 = "ゆんゆん"
296 = "めぐみん"
308 = "カズマ"
314 = "クリス"
315 = "ダクネス"
302 = "アクア"
307 = "ウィズ"

[character_subs]
# 308 = "カズマ"

[script]
# lines: 102

# カズマ（Ｍ）
# display as カズマ
# （あの騒ぎ以降、これといったトラブルも無く、\n　俺はどうにか信頼を取り戻すことが出来た）
397 = "（あの騒ぎ以降、これといったトラブルも無く、\\n　俺はどうにか信頼を取り戻すことが出来た）"

# カズマ（Ｍ）
# display as カズマ
# （そして特訓も滞りなく進み、\n　日が落ちて来たのでお開きということになった）
398 = "（そして特訓も滞りなく進み、\\n　日が落ちて来たのでお開きということになった）"

# ゆんゆん
# ふぁ～、疲れた～。
292 = "ふぁ～、疲れた～。"

# めぐみん
# ゆんゆん、ちゃんと髪を拭きなさい。\n風邪をひいても知りませんよ？
300 = "ゆんゆん、ちゃんと髪を拭きなさい。\\n風邪をひいても知りませんよ？"

# ゆんゆん
# そういうめぐみんだって、\nまだ髪が濡れてるじゃない。
262 = "そういうめぐみんだって、\\nまだ髪が濡れてるじゃない。"

# めぐみん
# こんなの放っておけばすぐに乾きますから。
253 = "こんなの放っておけばすぐに乾きますから。"

# ゆんゆん
# 私に言ってることと違うじゃないの！
389 = "私に言ってることと違うじゃないの！"

# ゆんゆん
# ほら、拭いてあげるから頭こっちに向けて。
294 = "ほら、拭いてあげるから頭こっちに向けて。"

# めぐみん
# 余計なことはしなくて良いですから。\nさっさと自分の髪を拭いてしまいなさい。
324 = "余計なことはしなくて良いですから。\\nさっさと自分の髪を拭いてしまいなさい。"

# ゆんゆん
# わかったから。めぐみんもちゃんと拭く。
301 = "わかったから。めぐみんもちゃんと拭く。"

# めぐみん
# 仕方ありませんね。
323 = "仕方ありませんね。"

# カズマ
# お前ら、仲が良いのか悪いのかはっきりしろよ。
248 = "お前ら、仲が良いのか悪いのかはっきりしろよ。"

# クリス
# あはは。キミはまだずいぶん元気そうだね。
237 = "あはは。キミはまだずいぶん元気そうだね。"

# カズマ
# 俺は教えるだけであんまり泳がなかったからな。
325 = "俺は教えるだけであんまり泳がなかったからな。"

# カズマ
# そういうクリスはどうなんだ？
263 = "そういうクリスはどうなんだ？"

# クリス
# 見ての通りくたくただよ。\nベッドがあったらすぐにでも\n横になって寝たいくらいにね。
394 = "見ての通りくたくただよ。\\nベッドがあったらすぐにでも\\n横になって寝たいくらいにね。"

# カズマ
# 水泳は全身運動だから、くたくたになるのも当然さ。
337 = "水泳は全身運動だから、くたくたになるのも当然さ。"

# ダクネス
# そうか？　私はまだまだ泳げるぞ？
264 = "そうか？　私はまだまだ泳げるぞ？"

# カズマ
# お前のペースに合わせてたら\n大会前に全員潰れちゃうだろ。
246 = "お前のペースに合わせてたら\\n大会前に全員潰れちゃうだろ。"

# ダクネス
# では、私だけ個人メニューを組むというのは\nどうだろうか！
280 = "では、私だけ個人メニューを組むというのは\\nどうだろうか！"

# クリス
# そんなことしなくても\nだいぶ泳げるようになったじゃない。
272 = "そんなことしなくても\\nだいぶ泳げるようになったじゃない。"

# ダクネス
# それはそうなのだが、やはり不安は拭いきれない。
270 = "それはそうなのだが、やはり不安は拭いきれない。"

# ダクネス
# アクアまでとはいかないまでも、なんとかクリスや\nめぐみんのレベルまでは自分を持っていきたいんだ。
306 = "アクアまでとはいかないまでも、なんとかクリスや\\nめぐみんのレベルまでは自分を持っていきたいんだ。"

# クリス
# 相変わらず真面目だね、ダクネスは。
386 = "相変わらず真面目だね、ダクネスは。"

# ダクネス
# 騎士として皆の足を引っ張るわけに行かないからな。
396 = "騎士として皆の足を引っ張るわけに行かないからな。"

# カズマ
# だったら剣術の腕を上げる努力もしてくれ。
276 = "だったら剣術の腕を上げる努力もしてくれ。"

# ダクネス
# そ、それは、人には得手不得手があるということに\nしておいてくれ。
260 = "そ、それは、人には得手不得手があるということに\\nしておいてくれ。"

# カズマ
# とにかく、お前に泳げる目処がついてくれて\n助かったよ。
281 = "とにかく、お前に泳げる目処がついてくれて\\n助かったよ。"

# カズマ（Ｍ）
# display as カズマ
# （最初はどうなるものかと思ったが、\n　これなら本番は期待しても良いかもしれない）
399 = "（最初はどうなるものかと思ったが、\\n　これなら本番は期待しても良いかもしれない）"

# アクア
# ねえ、カズマ。
290 = "ねえ、カズマ。"

# カズマ
# どうした？
284 = "どうした？"

# アクア
# おんぶしてくれない？
245 = "おんぶしてくれない？"

# カズマ
# ごめん、話がまったく見えない。
254 = "ごめん、話がまったく見えない。"

# アクア
# もう疲れて動きたくないのよ。\nだから、おんぶして欲しいなって。
298 = "もう疲れて動きたくないのよ。\\nだから、おんぶして欲しいなって。"

# カズマ
# 後先考えずに、\n泳ぎまくってるからそうなるんだろ。
333 = "後先考えずに、\\n泳ぎまくってるからそうなるんだろ。"

# カズマ
# ペース配分くらい計算しろ。
319 = "ペース配分くらい計算しろ。"

# アクア
# 次からそうするから、おんぶしてよ。\nほーら、早く早く。
335 = "次からそうするから、おんぶしてよ。\\nほーら、早く早く。"

# めぐみん
# それは容認できませんよ。
271 = "それは容認できませんよ。"

# カズマ
# なぜお前の許しを得ないといけないんだ。
288 = "なぜお前の許しを得ないといけないんだ。"

# めぐみん
# カズマにおぶってもらえるのは\n私だけの特権だからです。
312 = "カズマにおぶってもらえるのは\\n私だけの特権だからです。"

# カズマ
# そんな特権を与えた覚えはない。
273 = "そんな特権を与えた覚えはない。"

# カズマ
# あと、何さりげなく背中によじ登ろうとしてるんだ！
236 = "あと、何さりげなく背中によじ登ろうとしてるんだ！"

# めぐみん
# 私も疲れたんですよ。\nさあさあ、遠慮無くおぶるといいです。
390 = "私も疲れたんですよ。\\nさあさあ、遠慮無くおぶるといいです。"

# アクア
# あー、ずるい、私も私も！
238 = "あー、ずるい、私も私も！"

# カズマ
# だー、くっつくな、うっとうしい！
277 = "だー、くっつくな、うっとうしい！"

# ウィズ
# お待たせしました。
249 = "お待たせしました。"

# カズマ
# さて、これで全員の着替えも終わったし、\nそろそろ帰るとするか。
255 = "さて、これで全員の着替えも終わったし、\\nそろそろ帰るとするか。"

# アクア
# えー、カズマ、おんぶは？
243 = "えー、カズマ、おんぶは？"

# ウィズ
# お、おんぶ？
244 = "お、おんぶ？"

# カズマ
# ただ、だらけてるだけだから気にしなくていいよ。
274 = "ただ、だらけてるだけだから気にしなくていいよ。"

# ウィズ
# ですがアクア様、座り込んでしまっていますよ。
278 = "ですがアクア様、座り込んでしまっていますよ。"

# カズマ
# 腹が減ったら動く。
392 = "腹が減ったら動く。"

# ウィズ
# そ、そうですね。
258 = "そ、そうですね。"

# ダクネス
# では、帰るとするか。
279 = "では、帰るとするか。"

# クリス
# ふああ、今日は良く眠れそう。
293 = "ふああ、今日は良く眠れそう。"

# アクア
# きゃああああああああっ！？
251 = "きゃああああああああっ！？"

# カズマ
# な、なんだ？
287 = "な、なんだ？"

# カズマ
# どうしたアクア！
283 = "どうしたアクア！"

# アクア
# かじゅま～～～～っ！
250 = "かじゅま～～～～っ！"

# カズマ
# はいはい、なんですか女神様？
291 = "はいはい、なんですか女神様？"

# アクア
# カズマさーん！
311 = "カズマさーん！"

# カズマ
# どうせ演技だろ？\nそこまでして興味を惹こうとするか普通。
286 = "どうせ演技だろ？\\nそこまでして興味を惹こうとするか普通。"

# ダクネス
# いやしかし、\n演技のようには聞こえなかったが……。
240 = "いやしかし、\\n演技のようには聞こえなかったが……。"

# めぐみん
# カズマ、アクアが！
309 = "カズマ、アクアが！"

# カズマ
# アクアがどうした？
304 = "アクアがどうした？"

# アクア
# カズマさん！　カズマさんカズマさーん！
310 = "カズマさん！　カズマさんカズマさーん！"

# アクア
# 出たの、出たの、出たのよ！
327 = "出たの、出たの、出たのよ！"

# カズマ
# 出たって何が？
326 = "出たって何が？"

# アクア
# あいつよ！　あいつ！
235 = "あいつよ！　あいつ！"

# カズマ
# だからなんだよ！
275 = "だからなんだよ！"

# アクア
# ワニよワニ！　ワニがいたんだってば！
321 = "ワニよワニ！　ワニがいたんだってば！"

# カズマ
# ワニって、ブルータルアリゲーターか？
320 = "ワニって、ブルータルアリゲーターか？"

# ウィズ
# それはおかしいです。\nブルータルアリゲーターは劣悪な水質環境を好む\nモンスターですよ？
269 = "それはおかしいです。\\nブルータルアリゲーターは劣悪な水質環境を好む\\nモンスターですよ？"

# ゆんゆん
# ここの水は澄んでて綺麗ですもんね。
252 = "ここの水は澄んでて綺麗ですもんね。"

# カズマ
# それに今日は１日、\nこいつを湖に浸けてたわけで。
268 = "それに今日は１日、\\nこいつを湖に浸けてたわけで。"

# ウィズ
# そうですよね。\nアクア様を浸けていたなら、\n水は自動的に浄化される筈です。
265 = "そうですよね。\\nアクア様を浸けていたなら、\\n水は自動的に浄化される筈です。"

# クリス
# 浸けるって、もう少し言葉を選んであげなよ。
338 = "浸けるって、もう少し言葉を選んであげなよ。"

# ウィズ
# そ、そうですね、すみません。
257 = "そ、そうですね、すみません。"

# カズマ
# とにかく結論だ。
282 = "とにかく結論だ。"

# アクア
# うんうん！
242 = "うんうん！"

# カズマ
# お前の気のせい。
247 = "お前の気のせい。"

# アクア
# 本当にいたんだってば！\n信じてよ、カズマ！
334 = "本当にいたんだってば！\\n信じてよ、カズマ！"

# カズマ
# じゃあ、実際見たのか？
256 = "じゃあ、実際見たのか？"

# アクア
# そ、それは……。
259 = "そ、それは……。"

# ゆんゆん
# 見たわけじゃないんですか？
393 = "見たわけじゃないんですか？"

# アクア
# 気配を感じたのよ！
336 = "気配を感じたのよ！"

# カズマ
# 説得力が一気に皆無になったな。
395 = "説得力が一気に皆無になったな。"

# ダクネス
# そう、断言するには早計すぎるぞ。
261 = "そう、断言するには早計すぎるぞ。"

# ダクネス
# アクアはブルータルアリゲーターにトラウマが\nあるのだから、私たちより気配に敏感になっても\nおかしくないだろ。
305 = "アクアはブルータルアリゲーターにトラウマが\\nあるのだから、私たちより気配に敏感になっても\\nおかしくないだろ。"

# アクア
# うんうん！
# 242 = "うんうん！"

# カズマ
# 確かに直感はバカにできないけどさ。\nそういうバケモンがいたら、まずお前が\n気がつくだろ。
388 = "確かに直感はバカにできないけどさ。\\nそういうバケモンがいたら、まずお前が\\n気がつくだろ。"

# クリス
# ダクネスは探索スキルを持ってないでしょ。
316 = "ダクネスは探索スキルを持ってないでしょ。"

# カズマ
# いや、そうじゃなくて、こいつのドＭアンテナが\n目敏く察知するんじゃないかなって思ってさ。
239 = "いや、そうじゃなくて、こいつのドＭアンテナが\\n目敏く察知するんじゃないかなって思ってさ。"

# ダクネス
# な！？
289 = "な！？"

# めぐみん
# 確かにそうですね。
387 = "確かにそうですね。"

# ダクネス
# めぐみんまで！
297 = "めぐみんまで！"

# カズマ
# それにあんなでかいのが泳いでたら、\n俺たちの誰かが絶対に気がつくよ。
267 = "それにあんなでかいのが泳いでたら、\\n俺たちの誰かが絶対に気がつくよ。"

# クリス
# 職業柄、私たち冒険者は危険に敏感だしね。
391 = "職業柄、私たち冒険者は危険に敏感だしね。"

# カズマ
# アクア、ブルータルアリゲーターの気配は\n気のせいだったんだって。
303 = "アクア、ブルータルアリゲーターの気配は\\n気のせいだったんだって。"

# アクア
# そうなのかしら……。
266 = "そうなのかしら……。"

# カズマ
# ほら、特別におぶってやるから、\n早く帰ろうぜ。
295 = "ほら、特別におぶってやるから、\\n早く帰ろうぜ。"

# アクア
# う、うん……。
241 = "う、うん……。"

[selections]
# 283 = "どうしたアクア！"
# 291 = "はいはい、なんですか女神様？"
285 = "どうせ演技だろ？"
