# st02c_09.txt.scn

[info]
0 = ""

[characters]
186 = "カズマ"
184 = "アクア"
178 = "めぐみん"
187 = "カズマ（Ｍ）"
188 = "クリス"
185 = "ウィズ"
190 = "ダクネス"
179 = "めぐみん＆ダクネス＆ウィズ＆クリス＆ゆんゆん"

[character_subs]
# 186 = "カズマ"
177 = "みんな"

[script]
# lines: 31

# カズマ
# おつかれー！
162 = "おつかれー！"

# アクア
# おつかれさまー！
161 = "おつかれさまー！"

# めぐみん
# おつかれさまでした。
160 = "おつかれさまでした。"

# カズマ（Ｍ）
# display as カズマ
# （ギルドからの分配金は、\n　本当に夕食一食分くらいでしかなかったので、\n　打ち上げでまとめて使ってしまうことにした）
228 = "（ギルドからの分配金は、\\n　本当に夕食一食分くらいでしかなかったので、\\n　打ち上げでまとめて使ってしまうことにした）"

# カズマ（Ｍ）
# display as カズマ
# （ケチくさく取っておくより、\n　こうやってみんなの機嫌を取っておいた方が、\n　今後のためにもなるだろうからな）
229 = "（ケチくさく取っておくより、\\n　こうやってみんなの機嫌を取っておいた方が、\\n　今後のためにもなるだろうからな）"

# カズマ
# はぁ、結局は一銭もたまらなかったな。
173 = "はぁ、結局は一銭もたまらなかったな。"

# クリス
# まあまあ、仕方ないって。\nこういうこともあるよ。
176 = "まあまあ、仕方ないって。\\nこういうこともあるよ。"

# ウィズ
# そうですよ、それに悪いことばかりでは\nありませんでしたし。
166 = "そうですよ、それに悪いことばかりでは\\nありませんでしたし。"

# カズマ
# そうなのか？
167 = "そうなのか？"

# ウィズ
# はい、私、泳げるようになって嬉しかったです。\nこれもカズマさんのおかげですね。
174 = "はい、私、泳げるようになって嬉しかったです。\\nこれもカズマさんのおかげですね。"

# めぐみん
# 私も、少しだけ早く泳げるようになりましたしね。\nカズマには感謝をしています。少しだけですが。
226 = "私も、少しだけ早く泳げるようになりましたしね。\\nカズマには感謝をしています。少しだけですが。"

# カズマ
# 少しだけかよ。
198 = "少しだけかよ。"

# ダクネス
# 私は多大な感謝をしているぞ！
225 = "私は多大な感謝をしているぞ！"

# カズマ
# なんで……。
172 = "なんで……。"

# ダクネス
# ふふ、まさか爆裂魔法の直撃を受けられるとは。
175 = "ふふ、まさか爆裂魔法の直撃を受けられるとは。"

# ダクネス
# 一瞬で視界が暗転した後の、\n水中で上下さえもわからなくなるあの恐怖は――
193 = "一瞬で視界が暗転した後の、\\n水中で上下さえもわからなくなるあの恐怖は――"

# ダクネス
# 正直たまらなかった！
201 = "正直たまらなかった！"

# カズマ
# やめろ、想像もしたくない。
180 = "やめろ、想像もしたくない。"

# アクア
# かーずま、飲んでる？
164 = "かーずま、飲んでる？"

# カズマ
# って、できあがるの早いわ！
171 = "って、できあがるの早いわ！"

# アクア
# だって、だってぇ。
169 = "だって、だってぇ。"

# カズマ
# だってなんだよ。
170 = "だってなんだよ。"

# アクア
# ただ酒最高ですから！
168 = "ただ酒最高ですから！"

# カズマ
# お前、いい加減女神を名乗るのやめろ。
163 = "お前、いい加減女神を名乗るのやめろ。"

# アクア
# んー？\nねえカズマ、ポケットから何か出てるわよ？
182 = "んー？\\nねえカズマ、ポケットから何か出てるわよ？"

# カズマ
# ん？　ポケットから？？
183 = "ん？　ポケットから？？"

# カズマ
# ！？　こ、これは！！
227 = "！？　こ、これは！！"

# めぐみん＆ダクネス＆ウィズ＆クリス＆ゆんゆん
# display as みんな
# …………。
158 = "…………。"

# アクア
# 一瞬で酔いが覚めたわ。
194 = "一瞬で酔いが覚めたわ。"

# カズマ
# ええと……。
159 = "ええと……。"

# カズマ
# じゃあ、とりあえず行っとくか、パンツ裁判。
165 = "じゃあ、とりあえず行っとくか、パンツ裁判。"

[selections]
189 = "コーヒーブレイク"
