# st02b_09.txt.scn

[info]
0 = ""

[characters]
155 = "カズマ"
153 = "アクア"
150 = "めぐみん"
156 = "クリス"
154 = "ウィズ"
151 = "ゆんゆん"
157 = "ダクネス"
158 = "ダクネス＆ウィズ"

[character_subs]
179 = "２人"

[script]
# lines: 20

# カズマ
# うぅ、顔が痛い。
135 = "うぅ、顔が痛い。"

# アクア
# 胸を揉んだり水着を盗ったりした当然の天罰よ。\n猛省しなさい。
177 = "胸を揉んだり水着を盗ったりした当然の天罰よ。\\n猛省しなさい。"

# カズマ
# 水着の件は俺じゃないんだよ。
164 = "水着の件は俺じゃないんだよ。"

# めぐみん
# そういう嘘は人望を失うだけですよ。\nまあ、もともとそんなものはありませんが。
140 = "そういう嘘は人望を失うだけですよ。\\nまあ、もともとそんなものはありませんが。"

# カズマ
# お前、あとで覚えてろよ。
138 = "お前、あとで覚えてろよ。"

# めぐみん
# なんです、今度は私のを揉むつもりですか！\nそれとも全裸に剥くとでも！
147 = "なんです、今度は私のを揉むつもりですか！\\nそれとも全裸に剥くとでも！"

# カズマ
# そんなことしたら、それこそ犯罪者だろ！
142 = "そんなことしたら、それこそ犯罪者だろ！"

# アクア
# え、カズマってそうよね？
136 = "え、カズマってそうよね？"

# カズマ
# 違うわ！
178 = "違うわ！"

# クリス
# ねえ、さっきのって、\nその指輪のせいだったりしないよね？
148 = "ねえ、さっきのって、\\nその指輪のせいだったりしないよね？"

# ウィズ
# ええ！？　それってまさか、\n指輪が水着にも反応したってことですか！？
137 = "ええ！？　それってまさか、\\n指輪が水着にも反応したってことですか！？"

# クリス
# わかんないけど、他人が着てる物を\nあんな器用に脱がせるなんておかしいし。
152 = "わかんないけど、他人が着てる物を\\nあんな器用に脱がせるなんておかしいし。"

# カズマ
# だから俺はやってないって！
144 = "だから俺はやってないって！"

# ゆんゆん
# でも今日は満月の日じゃないですよね？
145 = "でも今日は満月の日じゃないですよね？"

# ダクネス
# ならカズマが狙って脱がせたということか？
146 = "ならカズマが狙って脱がせたということか？"

# カズマ
# だから俺は、やってないんだよ！
143 = "だから俺は、やってないんだよ！"

# ダクネス＆ウィズ
# display as ２人
# …………。
134 = "…………。"

# めぐみん
# まあ、信じましょう。いくら普段の言動が\nアレなカズマでも、あんなわかりやすい悪さを\nする度胸があるとも思えませんし。
149 = "まあ、信じましょう。いくら普段の言動が\\nアレなカズマでも、あんなわかりやすい悪さを\\nする度胸があるとも思えませんし。"

# ダクネス
# そうだな。\nいつも肝心な所でへたれるカズマが、\n直接私たちに手を出せるはずもあるまい。
141 = "そうだな。\\nいつも肝心な所でへたれるカズマが、\\n直接私たちに手を出せるはずもあるまい。"

# カズマ
# くそぉ、お前ら好き放題言いやがって……。
139 = "くそぉ、お前ら好き放題言いやがって……。"

