# st02b_01.txt.scn

[info]
0 = ""

[characters]
151 = "カズマ"
153 = "ダクネス"
150 = "アクア"
147 = "めぐみん"
152 = "カズマ（Ｍ）"
155 = "ルナ"

[character_subs]
# 151 = "カズマ"

[script]
# lines: 38

# カズマ
# もー。事前にエントリーが必要なんだったら、\n昨日のうちに言っとけよ。\n朝から特訓のはずだったのに予定が狂うだろ。
149 = "もー。事前にエントリーが必要なんだったら、\\n昨日のうちに言っとけよ。\\n朝から特訓のはずだったのに予定が狂うだろ。"

# ダクネス
# 私たちが呼びに行くまで寝ていたくせに、\nどの口が言うんだ。
187 = "私たちが呼びに行くまで寝ていたくせに、\\nどの口が言うんだ。"

# アクア
# 昨日、あんなに特訓特訓て言ってたくせにね。
163 = "昨日、あんなに特訓特訓て言ってたくせにね。"

# めぐみん
# そもそもカズマがいる理由がありませんよ。\n私たちはアクアに教えて貰うんですから。
135 = "そもそもカズマがいる理由がありませんよ。\\n私たちはアクアに教えて貰うんですから。"

# カズマ
# お前、アクアが人に物を教えられると\n思ってるのか？
131 = "お前、アクアが人に物を教えられると\\n思ってるのか？"

# めぐみん
# うっ、それは……。
127 = "うっ、それは……。"

# カズマ
# あいつの言葉には一応説得力がある。
123 = "あいつの言葉には一応説得力がある。"

# カズマ（Ｍ）
# display as カズマ
# （腐っても本物の水の女神だし）
190 = "（腐っても本物の水の女神だし）"

# カズマ
# だけど俺は、あいつが泳ぎ方を上手く教えられると\n思わない。
137 = "だけど俺は、あいつが泳ぎ方を上手く教えられると\\n思わない。"

# カズマ
# それはアクアがバカだからとか\nそういう問題じゃなくて、あいつは泳げることを\n普通だと言ったからだ。
136 = "それはアクアがバカだからとか\\nそういう問題じゃなくて、あいつは泳げることを\\n普通だと言ったからだ。"

# ダクネス
# どういう意味だ？
141 = "どういう意味だ？"

# カズマ
# ダクネスは、人に歩き方のコツを上手く教えられる\n自信があるか？
154 = "ダクネスは、人に歩き方のコツを上手く教えられる\\n自信があるか？"

# ダクネス
# うーん、難しいかもしれないな。
128 = "うーん、難しいかもしれないな。"

# カズマ
# 人は普通にできることのコツを意識したり\nしないだろ？
158 = "人は普通にできることのコツを意識したり\\nしないだろ？"

# カズマ
# できないことなら練習を積む過程で色々考えたり\nするけどさ。
139 = "できないことなら練習を積む過程で色々考えたり\\nするけどさ。"

# めぐみん
# なるほど。\nアクアは普通にできる分、\nそういうことを知らないというわけですね。
144 = "なるほど。\\nアクアは普通にできる分、\\nそういうことを知らないというわけですね。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、知ってても教えられないと思うけど）
188 = "（まあ、知ってても教えられないと思うけど）"

# アクア
# ねえ、早くエントリーをすませちゃいなさいよ。
145 = "ねえ、早くエントリーをすませちゃいなさいよ。"

# カズマ
# ええと、ギルドのカウンターで聞けばいいんだな？\nすみませーん！
130 = "ええと、ギルドのカウンターで聞けばいいんだな？\\nすみませーん！"

# ルナ
# あら、みなさんご一緒で。\n今日はどうなさったんですか？
125 = "あら、みなさんご一緒で。\\n今日はどうなさったんですか？"

# カズマ
# もうすぐある運動会に参加したいんで、\nそのエントリーに来ました。
148 = "もうすぐある運動会に参加したいんで、\\nそのエントリーに来ました。"

# ルナ
# でしたら、エントリーシートをお渡ししますので、\nチームメンバー全員のお名前を記入してください。
140 = "でしたら、エントリーシートをお渡ししますので、\\nチームメンバー全員のお名前を記入してください。"

# カズマ
# ええと、カズマ、アクア、めぐみん、ダクネスに\nウィズ――ん？
129 = "ええと、カズマ、アクア、めぐみん、ダクネスに\\nウィズ――ん？"

# カズマ（Ｍ）
# display as カズマ
# （チームメンバー？）
189 = "（チームメンバー？）"

# ダクネス
# どうかしたか？
142 = "どうかしたか？"

# カズマ
# 今までのこの運動会ってチーム戦だったのか？
159 = "今までのこの運動会ってチーム戦だったのか？"

# ダクネス
# いや、そんなことはないぞ。
126 = "いや、そんなことはないぞ。"

# ルナ
# あっ、もしかして、ルールの変更を\nご存じゃありません？
124 = "あっ、もしかして、ルールの変更を\\nご存じゃありません？"

# カズマ
# ルールの……変更？
156 = "ルールの……変更？"

# ルナ
# 今回から少しルールが変わったんですよ。
160 = "今回から少しルールが変わったんですよ。"

# ルナ
# これまでは個人戦だったんですけど、\n今回からは１チーム７人で組んでいただいて、\n全員の合計タイムで競う形になったんです。
133 = "これまでは個人戦だったんですけど、\\n今回からは１チーム７人で組んでいただいて、\\n全員の合計タイムで競う形になったんです。"

# カズマ（Ｍ）
# display as カズマ
# （７人！？）
191 = "（７人！？）"

# カズマ
# な、なんでそんな変更を？
143 = "な、なんでそんな変更を？"

# ルナ
# このイベントも長く続けて来て、少しマンネリに\nなっていたのと、冒険者の皆さんの横の繋がりを\n強められたらと思いまして。
132 = "このイベントも長く続けて来て、少しマンネリに\\nなっていたのと、冒険者の皆さんの横の繋がりを\\n強められたらと思いまして。"

# カズマ
# そうですか……。
134 = "そうですか……。"

# アクア
# ねえねえ、カズマ。\nエントリーはすんだの？
146 = "ねえねえ、カズマ。\\nエントリーはすんだの？"

# アクア
# だったら早く特訓に行きましょうよ。
138 = "だったら早く特訓に行きましょうよ。"

# カズマ
# ……とりあえず、みんな集合。
122 = "……とりあえず、みんな集合。"

