# st02b_08.txt.scn

[info]
0 = ""

[characters]
322 = "ゆんゆん"
315 = "めぐみん"
333 = "カズマ"
336 = "カズマ（Ｍ）"
340 = "ダクネス"
330 = "ウィズ"
338 = "クリス"

[character_subs]
# 333 = "カズマ"

[script]
# lines: 98

# ゆんゆん
# ありがとね、めぐみん。\n私のために怒ってくれて。
265 = "ありがとね、めぐみん。\\n私のために怒ってくれて。"

# めぐみん
# 私は別にゆんゆんのために怒ったわけではなく、\nこの男の卑劣な行為が許せなかっただけです。
412 = "私は別にゆんゆんのために怒ったわけではなく、\\nこの男の卑劣な行為が許せなかっただけです。"

# めぐみん
# それにしても、\n油断も隙もあったものじゃないですね。
296 = "それにしても、\\n油断も隙もあったものじゃないですね。"

# カズマ
# わざとやったわけじゃないのに。
328 = "わざとやったわけじゃないのに。"

# めぐみん
# あんなにがっちり鷲掴みにしておいて、\nそんな言い訳が通じるとでも思っているんですか？
267 = "あんなにがっちり鷲掴みにしておいて、\\nそんな言い訳が通じるとでも思っているんですか？"

# めぐみん
# 仮に、本当にわざとじゃなかったとしても、\nあんなにイヤらしく揉みしだいていたのですから、\n罰を受けるのは当然のことです。
348 = "仮に、本当にわざとじゃなかったとしても、\\nあんなにイヤらしく揉みしだいていたのですから、\\n罰を受けるのは当然のことです。"

# カズマ（Ｍ）
# display as カズマ
# （悔しいけど、何も言い返せないっ！）
423 = "（悔しいけど、何も言い返せないっ！）"

# めぐみん
# ほら、ゆんゆんに何か言うことはないんですか？
312 = "ほら、ゆんゆんに何か言うことはないんですか？"

# カズマ
# その……。
295 = "その……。"

# カズマ
# 本当にごめん……。
363 = "本当にごめん……。"

# ゆんゆん
# いえ、私の方こそ取り乱しちゃって。
269 = "いえ、私の方こそ取り乱しちゃって。"

# カズマ
# あんなことしちゃったんだから仕方ないって。
266 = "あんなことしちゃったんだから仕方ないって。"

# カズマ
# ほんと悪かった。\nお詫びに何かした方が良いか？
313 = "ほんと悪かった。\\nお詫びに何かした方が良いか？"

# ゆんゆん
# そんな！　私ならもう大丈夫ですから！！
298 = "そんな！　私ならもう大丈夫ですから！！"

# ゆんゆん
# あ、でも、出来れば……\nさっきのことは、忘れてもらえると嬉しいです。
263 = "あ、でも、出来れば……\\nさっきのことは、忘れてもらえると嬉しいです。"

# カズマ
# 今後は気を付けます。ごめんなさい。
347 = "今後は気を付けます。ごめんなさい。"

# ゆんゆん
# もう、大丈夫ですから。\n済んじゃったことは仕方ないですし。
316 = "もう、大丈夫ですから。\\n済んじゃったことは仕方ないですし。"

# ゆんゆん
# でも、さっきのことは\n出来れば忘れてもらえると嬉しいです。
303 = "でも、さっきのことは\\n出来れば忘れてもらえると嬉しいです。"

# カズマ
# ごちそうさまでした！
287 = "ごちそうさまでした！"

# ゆんゆん
# ええ！？
277 = "ええ！？"

# めぐみん
# 反省する気がないようですね。
353 = "反省する気がないようですね。"

# カズマ
# 待て待て！　冗談だ！\n悪かったって！　この通り謝るからさ！
361 = "待て待て！　冗談だ！\\n悪かったって！　この通り謝るからさ！"

# めぐみん
# ゆんゆん、どうします？
324 = "ゆんゆん、どうします？"

# ゆんゆん
# わ、私ならもう大丈夫だよ。
326 = "わ、私ならもう大丈夫だよ。"

# ゆんゆん
# でも、カズマさん、さっきのことは、\n出来れば忘れてもらえると助かります。
304 = "でも、カズマさん、さっきのことは、\\n出来れば忘れてもらえると助かります。"

# カズマ（Ｍ）
# display as カズマ
# （いや、忘れろって言われても、\n　まず不可能だから！）
418 = "（いや、忘れろって言われても、\\n　まず不可能だから！）"

# めぐみん
# ゆんゆん、ここは危険ですから向こうで\n練習しましょう。
323 = "ゆんゆん、ここは危険ですから向こうで\\n練習しましょう。"

# カズマ
# ……ここの何が危険なんだよ。
262 = "……ここの何が危険なんだよ。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、結果オーライか。\n　めぐみんをゆんゆんに押しつけられたし）
420 = "（まあ、結果オーライか。\\n　めぐみんをゆんゆんに押しつけられたし）"

# ダクネス
# カズマ、そろそろ特訓の続きを頼む！
334 = "カズマ、そろそろ特訓の続きを頼む！"

# カズマ
# えー、俺まだ休憩してないんだけど。
278 = "えー、俺まだ休憩してないんだけど。"

# ダクネス
# 大会はもう目の前なんだぞ。\n悠長に構えててどうする。
357 = "大会はもう目の前なんだぞ。\\n悠長に構えててどうする。"

# カズマ
# やる気になってくれるのは嬉しいけどさ……。
321 = "やる気になってくれるのは嬉しいけどさ……。"

# ウィズ
# カズマさん、次は何をしたらいいですか？
335 = "カズマさん、次は何をしたらいいですか？"

# カズマ
# ウィズもか……。
331 = "ウィズもか……。"

# ウィズ
# 今の私はお荷物でしかありませんからね。\n少しでも練習時間を増やさないと。
345 = "今の私はお荷物でしかありませんからね。\\n少しでも練習時間を増やさないと。"

# ダクネス
# それは私も同じだな。
297 = "それは私も同じだな。"

# カズマ
# わかった、わかったよ。\nじゃあ、ウィズは手と足の動きに気をつけて\nさっきまでの復習をしてくれるか？
327 = "わかった、わかったよ。\\nじゃあ、ウィズは手と足の動きに気をつけて\\nさっきまでの復習をしてくれるか？"

# ウィズ
# はい、わかりました。
310 = "はい、わかりました。"

# カズマ
# ダクネスはもうバタ足できるし、\n次は手の動きだな。
341 = "ダクネスはもうバタ足できるし、\\n次は手の動きだな。"

# ダクネス
# よろしく指導を頼む！
325 = "よろしく指導を頼む！"

# カズマ
# 良いか？\nこうやって手を動かして水をかくんだ。
413 = "良いか？\\nこうやって手を動かして水をかくんだ。"

# ダクネス
# こうか？
286 = "こうか？"

# カズマ
# もっと大きく円を描くようにだな。\n水に入れるときは指の先から。
320 = "もっと大きく円を描くようにだな。\\n水に入れるときは指の先から。"

# ダクネス
# ひっ！？
311 = "ひっ！？"

# カズマ
# そして、水から出すときは、こうっ！
294 = "そして、水から出すときは、こうっ！"

# ダクネス
# カ、カ、カズマ？
332 = "カ、カ、カズマ？"

# カズマ（Ｍ）
# display as カズマ
# （ん？　なんか指に引っかかったような。\n　この感触は水草か？）
422 = "（ん？　なんか指に引っかかったような。\\n　この感触は水草か？）"

# ダクネス
# ええとだな。\n確かにそういう趣旨の辱めも嫌いじゃないが。
276 = "ええとだな。\\n確かにそういう趣旨の辱めも嫌いじゃないが。"

# カズマ（Ｍ）
# display as カズマ
# （はずかしめぇ？）
419 = "（はずかしめぇ？）"

# ダクネス
# だが、水着まで取るというのはどうかと思うぞ？
299 = "だが、水着まで取るというのはどうかと思うぞ？"

# カズマ
# え……？
275 = "え……？"

# ダクネス
# さすがにこの格好では丘に上がれない。\nか、返してくれると助かる。
288 = "さすがにこの格好では丘に上がれない。\\nか、返してくれると助かる。"

# カズマ
# まさか、今、俺が持ってるのって、水着の……。
314 = "まさか、今、俺が持ってるのって、水着の……。"

# ダクネス
# つまりそういうことだ。
302 = "つまりそういうことだ。"

# クリス
# ちょっと、キミ！
301 = "ちょっと、キミ！"

# カズマ
# なっ、クリス！
306 = "なっ、クリス！"

# クリス
# さすがに水着まで盗むっていうのはどうかと思うよ！
289 = "さすがに水着まで盗むっていうのはどうかと思うよ！"

# カズマ
# いや、違う、これは俺がやったんじゃなくて！
271 = "いや、違う、これは俺がやったんじゃなくて！"

# クリス
# 言い訳なんかしてないで、早く返してあげなよ！
415 = "言い訳なんかしてないで、早く返してあげなよ！"

# カズマ
# 信じてくれ！　俺は本当に！！
350 = "信じてくれ！　俺は本当に！！"

# クリス
# ちょっと、その手は何！\nまさか、あたしの水着まで！
300 = "ちょっと、その手は何！\\nまさか、あたしの水着まで！"

# カズマ
# 違うっ！　話を聞いてくれ！
417 = "違うっ！　話を聞いてくれ！"

# クリス
# きゃ、きゃあ！
284 = "きゃ、きゃあ！"

# カズマ
# え？
279 = "え？"

# クリス
# う、う、うううううううっ！！
273 = "う、う、うううううううっ！！"

# カズマ
# な、なんで、クリスの水着が取れてるんだ？
305 = "な、なんで、クリスの水着が取れてるんだ？"

# クリス
# キ、キミがスティールしたんでしょ！
337 = "キ、キミがスティールしたんでしょ！"

# カズマ
# いやいやいや、俺は一言もスティールなんて\n言ってないだろ！
272 = "いやいやいや、俺は一言もスティールなんて\\n言ってないだろ！"

# ダクネス
# なんという悪魔の所業！　そしてその手際！\nカズマ、お前はその道を極めてしまったのだな。
308 = "なんという悪魔の所業！　そしてその手際！\\nカズマ、お前はその道を極めてしまったのだな。"

# カズマ
# なんの道だよ！　極めた覚えはねえよ！
309 = "なんの道だよ！　極めた覚えはねえよ！"

# クリス
# なんでもいいから早く返してよあたしの水着！
307 = "なんでもいいから早く返してよあたしの水着！"

# ダクネス
# 私は……クリスのあとでもいいぞ。
411 = "私は……クリスのあとでもいいぞ。"

# カズマ
# お前は、\nこっそりとこの状況を楽しんでんじゃねーよ！
281 = "お前は、\\nこっそりとこの状況を楽しんでんじゃねーよ！"

# クリス
# もういいから、早く返して！
317 = "もういいから、早く返して！"

# カズマ
# 返すよ！\nだけど、その前にちゃんと話を聞いてくれ！
416 = "返すよ！\\nだけど、その前にちゃんと話を聞いてくれ！"

# ダクネス
# そうやって時間を稼ぎ、\n私たちが羞恥に震える様を楽しむつもりなんだな！
293 = "そうやって時間を稼ぎ、\\n私たちが羞恥に震える様を楽しむつもりなんだな！"

# カズマ
# お前はちっとも恥ずかしがってないじゃん！\nむしろ楽しんでるじゃん！
282 = "お前はちっとも恥ずかしがってないじゃん！\\nむしろ楽しんでるじゃん！"

# クリス
# もうもうもうっ！　話があるなら早く！
319 = "もうもうもうっ！　話があるなら早く！"

# カズマ
# いいか、俺は神に誓ってお前たちの水着を\n取ってない！
268 = "いいか、俺は神に誓ってお前たちの水着を\\n取ってない！"

# クリス
# 信じられないんだけど……。
351 = "信じられないんだけど……。"

# カズマ
# 冷静に考えてみてくれ、おかしいだろ。
352 = "冷静に考えてみてくれ、おかしいだろ。"

# カズマ
# クリスの時は距離が離れてたし。\nスティールだったら俺の手の中に水着がある筈だ。
339 = "クリスの時は距離が離れてたし。\\nスティールだったら俺の手の中に水着がある筈だ。"

# クリス
# 盗ってすぐに放ったんでしょ……。
364 = "盗ってすぐに放ったんでしょ……。"

# カズマ
# じゃあ、ダクネス。\n思い出してくれ。
290 = "じゃあ、ダクネス。\\n思い出してくれ。"

# ダクネス
# 実に素晴らしい手際だった。
358 = "実に素晴らしい手際だった。"

# カズマ
# そうじゃなくて！
292 = "そうじゃなくて！"

# カズマ
# お前の水着が取れたとき、\n俺の手はお前の肌に触れたか？
280 = "お前の水着が取れたとき、\\n俺の手はお前の肌に触れたか？"

# ダクネス
# 何かが肌に触れた感触はあったが、\nそれがカズマの手とは断言できない。
349 = "何かが肌に触れた感触はあったが、\\nそれがカズマの手とは断言できない。"

# クリス
# じゃあ何？\nあたしとダクネスの水着は勝手に取れたって言うの？
291 = "じゃあ何？\\nあたしとダクネスの水着は勝手に取れたって言うの？"

# カズマ
# いや、それはわからないけど……。
270 = "いや、それはわからないけど……。"

# クリス
# もういいから、水着を返してっ！
318 = "もういいから、水着を返してっ！"

# カズマ
# お前バカ！\nこの状況で手を伸ばしたりしたら！
283 = "お前バカ！\\nこの状況で手を伸ばしたりしたら！"

# クリス
# きゃっ！
285 = "きゃっ！"

# カズマ
# 見てない、見てない！\n神、いやエリス様に誓って見てないから！
414 = "見てない、見てない！\\n神、いやエリス様に誓って見てないから！"

# クリス
# う、うう、ううう！\nカズマのバカーーーーーーーーー！！
274 = "う、うう、ううう！\\nカズマのバカーーーーーーーーー！！"

# カズマ
# あぁん！
264 = "あぁん！"

# カズマ（Ｍ）
# display as カズマ
# （もう、なんなのこの天丼）
421 = "（もう、なんなのこの天丼）"

[selections]
362 = "本当にごめん……"
346 = "今後は気を付けます"
# 287 = "ごちそうさまでした！"
