# st02a_01.txt.scn

[info]
0 = ""

[characters]
203 = "アクア"
204 = "カズマ"
201 = "めぐみん"
207 = "ダクネス"
206 = "カズマ（Ｍ）"

[character_subs]
# 204 = "カズマ"

[script]
# lines: 39

# アクア
# さあカズマ、その指を差しだして貰いましょうか。
195 = "さあカズマ、その指を差しだして貰いましょうか。"

# カズマ
# い、いやいや、悪い冗談はやめろって。
190 = "い、いやいや、悪い冗談はやめろって。"

# めぐみん
# 大丈夫ですよ。\nちょっとチクってするだけです。
212 = "大丈夫ですよ。\\nちょっとチクってするだけです。"

# カズマ
# そんなわけあるかー！
197 = "そんなわけあるかー！"

# ダクネス
# すまない、カズマ。\nこれはみんなの総意なんだ。
196 = "すまない、カズマ。\\nこれはみんなの総意なんだ。"

# カズマ
# お、おい、まさかその大剣で斬るつもりか！
192 = "お、おい、まさかその大剣で斬るつもりか！"

# めぐみん
# カズマ。
205 = "カズマ。"

# ダクネス
# お前は調子に乗りすぎた。
193 = "お前は調子に乗りすぎた。"

# アクア
# これは、当然の天罰よ。\n受け入れなさい。
194 = "これは、当然の天罰よ。\\n受け入れなさい。"

# カズマ
# ひ、ひ、ひぃぃぃぃ――
199 = "ひ、ひ、ひぃぃぃぃ――"

# カズマ
# うぎゃあああああああああああ！！
191 = "うぎゃあああああああああああ！！"

# カズマ
# 指っ、指っ、俺の指！！
215 = "指っ、指っ、俺の指！！"

# カズマ（Ｍ）
# display as カズマ
# （あれ？　ある。\n　って！？）
231 = "（あれ？　ある。\\n　って！？）"

# カズマ
# パンツもあるー！！
208 = "パンツもあるー！！"

# カズマ（Ｍ）
# display as カズマ
# （そ、そうだった、昨夜は満月だったんだっけ）
238 = "（そ、そうだった、昨夜は満月だったんだっけ）"

# カズマ（Ｍ）
# display as カズマ
# （だからあんな物騒な夢を見たのか）
240 = "（だからあんな物騒な夢を見たのか）"

# カズマ（Ｍ）
# display as カズマ
# （ちくしょうあいつら、\n　夢の中だからって好き放題やりやがって――）
241 = "（ちくしょうあいつら、\\n　夢の中だからって好き放題やりやがって――）"

# カズマ（Ｍ）
# display as カズマ
# （あとで地味な嫌がらせをしてやる）
230 = "（あとで地味な嫌がらせをしてやる）"

# カズマ（Ｍ）
# display as カズマ
# （おっと、今はそれよりもだ――）
233 = "（おっと、今はそれよりもだ――）"

# カズマ（Ｍ）
# display as カズマ
# （ディテールまでじっくりと観察して、\n　誰のパンツなのか考察しなければいけないな）
248 = "（ディテールまでじっくりと観察して、\\n　誰のパンツなのか考察しなければいけないな）"

# カズマ（Ｍ）
# display as カズマ
# （ほほぅ、これはこれはずいぶんとアダルティな\n　デザインですね）
247 = "（ほほぅ、これはこれはずいぶんとアダルティな\\n　デザインですね）"

# カズマ（Ｍ）
# display as カズマ
# （丁寧に施された刺繍には、作り手のこだわりを\n　感じますね。うん、まさに匠の技、見習いたい）
250 = "（丁寧に施された刺繍には、作り手のこだわりを\\n　感じますね。うん、まさに匠の技、見習いたい）"

# カズマ（Ｍ）
# display as カズマ
# （さらに特筆すべきは、この紐でしょうか）
237 = "（さらに特筆すべきは、この紐でしょうか）"

# カズマ（Ｍ）
# display as カズマ
# （いやらしくもなく子供っぽくもない、\n　この全てが計算尽くされた感のある紐の太さは\n　黄金比と言ってもよいでしょう）
232 = "（いやらしくもなく子供っぽくもない、\\n　この全てが計算尽くされた感のある紐の太さは\\n　黄金比と言ってもよいでしょう）"

# カズマ（Ｍ）
# display as カズマ
# （素材の手触りもよく、\n　おそらく数千エリスはくだらないのでは\n　ないでしょうか）
251 = "（素材の手触りもよく、\\n　おそらく数千エリスはくだらないのでは\\n　ないでしょうか）"

# カズマ（Ｍ）
# display as カズマ
# （そしてもう一枚は――）
239 = "（そしてもう一枚は――）"

# カズマ
# って、はぁぁ？　もう一枚！？
198 = "って、はぁぁ？　もう一枚！？"

# カズマ（Ｍ）
# display as カズマ
# （な、なんで２枚あるんだ。\n　もしかして……重ね穿き？）
245 = "（な、なんで２枚あるんだ。\\n　もしかして……重ね穿き？）"

# カズマ（Ｍ）
# display as カズマ
# （なるほど冷え性！）
246 = "（なるほど冷え性！）"

# カズマ（Ｍ）
# display as カズマ
# （重ね穿きには、サイズに若干の不安があるけど、\n　女の子のパンツは良く伸びるって聞くし）
252 = "（重ね穿きには、サイズに若干の不安があるけど、\\n　女の子のパンツは良く伸びるって聞くし）"

# カズマ（Ｍ）
# display as カズマ
# （でもこの２枚のパンツ、系統が違うような）
242 = "（でもこの２枚のパンツ、系統が違うような）"

# カズマ（Ｍ）
# display as カズマ
# （さっきの大人っぽいパンツを選ぶ子なら、\n　冷え性対策に重ね穿きするにしても、\n　もうちょっといい物をチョイスするような）
236 = "（さっきの大人っぽいパンツを選ぶ子なら、\\n　冷え性対策に重ね穿きするにしても、\\n　もうちょっといい物をチョイスするような）"

# カズマ（Ｍ）
# display as カズマ
# （どう見てもこれって、\n　３枚、千円くらいで売ってそうな安物……\n　ってわけでもないか？）
244 = "（どう見てもこれって、\\n　３枚、千円くらいで売ってそうな安物……\\n　ってわけでもないか？）"

# カズマ（Ｍ）
# display as カズマ
# （デザインこそ素っ気ないけど、\n　使ってる素材は悪くなさそうだ）
249 = "（デザインこそ素っ気ないけど、\\n　使ってる素材は悪くなさそうだ）"

# カズマ（Ｍ）
# display as カズマ
# （おっと、本気で考察してる場合じゃない！）
234 = "（おっと、本気で考察してる場合じゃない！）"

# カズマ（Ｍ）
# display as カズマ
# （こんなところをあいつらに見つかったら、\n　それこそ指を落とされかねねーし）
235 = "（こんなところをあいつらに見つかったら、\\n　それこそ指を落とされかねねーし）"

# カズマ（Ｍ）
# display as カズマ
# （とりあえずパンツは丁寧に畳ませていただいて。\n　折り折りっと）
243 = "（とりあえずパンツは丁寧に畳ませていただいて。\\n　折り折りっと）"

# カズマ
# よし、まずは着替えちまうか。
202 = "よし、まずは着替えちまうか。"

# カズマ
# ふぁぁ、寝起きが最悪だったせいか体が重い。
200 = "ふぁぁ、寝起きが最悪だったせいか体が重い。"

