# st02c_01.txt.scn

[info]
0 = ""

[characters]
226 = "カズマ"
224 = "アクア"
230 = "クリス"
231 = "ダクネス"
219 = "めぐみん"
225 = "ウィズ"
221 = "ゆんゆん"
228 = "カズマ（Ｍ）"
232 = "ダスト"
229 = "キース"

[character_subs]
# 226 = "カズマ"

[script]
# lines: 56

# カズマ
# おー、すげー。出店まで出てるじゃん。
198 = "おー、すげー。出店まで出てるじゃん。"

# アクア
# ふわぁぁぁ、ねむい。
215 = "ふわぁぁぁ、ねむい。"

# カズマ
# おいおい。まだ寝ボケてるのか？
195 = "おいおい。まだ寝ボケてるのか？"

# アクア
# だって昨日、よく眠れなかったんですもの。
208 = "だって昨日、よく眠れなかったんですもの。"

# カズマ
# 前日に眠れないとか、お前は遠足前の子供か。
237 = "前日に眠れないとか、お前は遠足前の子供か。"

# アクア
# うるさいわねー。
192 = "うるさいわねー。"

# クリス
# おーい！
199 = "おーい！"

# ダクネス
# やあ、クリス。
220 = "やあ、クリス。"

# クリス
# いやー、それにしても、賑わってるね。
188 = "いやー、それにしても、賑わってるね。"

# ダクネス
# 恒例行事として親しまれている証拠だな。
247 = "恒例行事として親しまれている証拠だな。"

# カズマ
# おっちゃん、この唐揚げ串１本くれ。
196 = "おっちゃん、この唐揚げ串１本くれ。"

# めぐみん
# カズマ、これから走るのに\n何を買い食いなんてしているんです。
227 = "カズマ、これから走るのに\\n何を買い食いなんてしているんです。"

# カズマ
# いいだろこれくらい。\n今すぐ走るわけでもないんだし。
187 = "いいだろこれくらい。\\n今すぐ走るわけでもないんだし。"

# めぐみん
# 途中でお腹が痛くなってもしりませんよ。\n優勝出来なくて困るのはカズマなんですからね。
288 = "途中でお腹が痛くなってもしりませんよ。\\n優勝出来なくて困るのはカズマなんですからね。"

# カズマ
# その場合、指輪の問題が先延ばしになって、\n結果的にお前たちも困るわけだが？
205 = "その場合、指輪の問題が先延ばしになって、\\n結果的にお前たちも困るわけだが？"

# めぐみん
# …………。
184 = "…………。"

# めぐみん
# はぐっ！　はぐはぐはぐっ！
214 = "はぐっ！　はぐはぐはぐっ！"

# カズマ
# お前、勝手に人のもん食うな！
200 = "お前、勝手に人のもん食うな！"

# めぐみん
# 周りに迷惑をかけてる自覚のないカズマへの罰です。
241 = "周りに迷惑をかけてる自覚のないカズマへの罰です。"

# カズマ
# くそ、半分以上食いやがって。
203 = "くそ、半分以上食いやがって。"

# ウィズ
# みなさん、おはようございます。
217 = "みなさん、おはようございます。"

# ゆんゆん
# おはようございまーす。
197 = "おはようございまーす。"

# カズマ
# ああ、おはよう。
185 = "ああ、おはよう。"

# ゆんゆん
# どうしたんです？　元気なさそうですけど。
210 = "どうしたんです？　元気なさそうですけど。"

# カズマ
# それが、めぐみんに襲われて、\n大事な物を無理やり奪われちまってさ。
206 = "それが、めぐみんに襲われて、\\n大事な物を無理やり奪われちまってさ。"

# めぐみん
# 誤解を生むような言い回しはやめてください。\nどこかの世間知らずが変な勘違いしますから。
287 = "誤解を生むような言い回しはやめてください。\\nどこかの世間知らずが変な勘違いしますから。"

# ゆんゆん
# め、めぐみん、あなたカズマさんに何したの！？
218 = "め、めぐみん、あなたカズマさんに何したの！？"

# めぐみん
# ほら。
216 = "ほら。"

# カズマ
# いいだろ、これくらいの仕返し。
186 = "いいだろ、これくらいの仕返し。"

# カズマ（Ｍ）
# display as カズマ
# （あーあ、もう１本買うかなー）
289 = "（あーあ、もう１本買うかなー）"

# ダスト
# ようカズマ。\n買い食いだなんて余裕じゃねーか。
222 = "ようカズマ。\\n買い食いだなんて余裕じゃねーか。"

# カズマ
# なんだ、やっぱりふたりも参加するのか？
211 = "なんだ、やっぱりふたりも参加するのか？"

# キース
# 当然だろ。\nこんな美味しいイベントを逃すかっての。
245 = "当然だろ。\\nこんな美味しいイベントを逃すかっての。"

# カズマ
# お前らも賞金目当てなのか。
201 = "お前らも賞金目当てなのか。"

# キース
# 当然それもあるが。
244 = "当然それもあるが。"

# ダスト
# それよりも競技に参加しないと\n間近で貴重な水着姿を見られないからな。
207 = "それよりも競技に参加しないと\\n間近で貴重な水着姿を見られないからな。"

# カズマ
# 下心全開だな。
233 = "下心全開だな。"

# キース
# 美女ばっかりをはべらせてるお前に\n言われたくねーよ！
286 = "美女ばっかりをはべらせてるお前に\\n言われたくねーよ！"

# ダスト
# くぅぅぅっ、いつもの３人だけならまだしも！
202 = "くぅぅぅっ、いつもの３人だけならまだしも！"

# キース
# 快活でボーイッシュが魅力のクリス！
246 = "快活でボーイッシュが魅力のクリス！"

# クリス
# ん？
223 = "ん？"

# ダスト
# ちょっとシャイだけどそこが魅力のゆんゆん！
209 = "ちょっとシャイだけどそこが魅力のゆんゆん！"

# ゆんゆん
# え？
194 = "え？"

# キース
# 何よりも俺たちのアイドル貧乏店主さんまで！
235 = "何よりも俺たちのアイドル貧乏店主さんまで！"

# ウィズ
# はい？
213 = "はい？"

# ダスト
# うらやましくないし悔しくない！\nけど、ぜってーお前には負けねー！！
191 = "うらやましくないし悔しくない！\\nけど、ぜってーお前には負けねー！！"

# キース
# この命が尽きようとも、\nお前を優勝させないからな！
204 = "この命が尽きようとも、\\nお前を優勝させないからな！"

# カズマ
# ええと……つまりうらやましいし悔しいんだろ？
193 = "ええと……つまりうらやましいし悔しいんだろ？"

# ダスト
# う、うう、カズマなんて嫌いだーーーーー！！
189 = "う、うう、カズマなんて嫌いだーーーーー！！"

# カズマ（Ｍ）
# display as カズマ
# （は、ははは……）
290 = "（は、ははは……）"

# ウィズ
# 先ほどのおふたりどうかしたんですか？
236 = "先ほどのおふたりどうかしたんですか？"

# ゆんゆん
# 私の名前を言っていたようですけど。
284 = "私の名前を言っていたようですけど。"

# カズマ
# なんでもないよ。\nそれよりも大会頑張ろうぜ。
212 = "なんでもないよ。\\nそれよりも大会頑張ろうぜ。"

# ウィズ
# うぅ、胃が痛くなって来ました……。
190 = "うぅ、胃が痛くなって来ました……。"

# ゆんゆん
# 私もです……。
285 = "私もです……。"

# カズマ（Ｍ）
# display as カズマ
# （大丈夫なのか、これ）
291 = "（大丈夫なのか、これ）"

