# st02a_08.txt.scn

[info]
0 = ""

[characters]
318 = "カズマ"
309 = "めぐみん"
320 = "カズマ（Ｍ）"
317 = "ウィズ"
315 = "アクア"
324 = "ダクネス"

[character_subs]
# 318 = "カズマ"

[script]
# lines: 141

# カズマ
# ただいまー。
273 = "ただいまー。"

# めぐみん
# おや、カズマじゃないですか。\nよく帰って来られましたね。
262 = "おや、カズマじゃないですか。\\nよく帰って来られましたね。"

# カズマ
# うっ、めぐみん。
251 = "うっ、めぐみん。"

# カズマ（Ｍ）
# display as カズマ
# （そういえば、朝のことをすっかり忘れてた）
429 = "（そういえば、朝のことをすっかり忘れてた）"

# めぐみん
# %fsyogen;そんな警戒しなくてもいいですよ。\nもう怒ってませんから。
21 = "%fsyogen;そんな警戒しなくてもいいですよ。\\nもう怒ってませんから。"

# カズマ
# またまたー。\nそんなこと言って、後ろからブスッと\nやってくる気なんだろ？
308 = "またまたー。\\nそんなこと言って、後ろからブスッと\\nやってくる気なんだろ？"

# めぐみん
# カズマじゃないんですからそんな卑怯な\n真似はしませんよ。
319 = "カズマじゃないんですからそんな卑怯な\\n真似はしませんよ。"

# カズマ
# 俺だってしねーよ！
335 = "俺だってしねーよ！"

# カズマ（Ｍ）
# display as カズマ
# （うーん、めぐみんがこんなにあっさりと\n　俺を許すなんて怪しい……ような気がする）
423 = "（うーん、めぐみんがこんなにあっさりと\\n　俺を許すなんて怪しい……ような気がする）"

# カズマ（Ｍ）
# display as カズマ
# （念のため証言としてゲットしておくか）
438 = "（念のため証言としてゲットしておくか）"

# めぐみん
# とにかく、今日はもう何もする気はありませんよ。
281 = "とにかく、今日はもう何もする気はありませんよ。"

# めぐみん
# いちいちカズマの言うことに腹を立ててたら\nキリがありませんからね。
248 = "いちいちカズマの言うことに腹を立ててたら\\nキリがありませんからね。"

# カズマ
# うむ。わかれば良いんだ、わかれば。
253 = "うむ。わかれば良いんだ、わかれば。"

# めぐみん
# やはり一度、何かしらの制裁を\n与えるべきかもしれませんね、この男には。
312 = "やはり一度、何かしらの制裁を\\n与えるべきかもしれませんね、この男には。"

# ウィズ
# ええと、お邪魔します。
258 = "ええと、お邪魔します。"

# アクア
# はあああああああああ？
298 = "はあああああああああ？"

# ウィズ
# ひっ、アクア様！！
299 = "ひっ、アクア様！！"

# アクア
# %fsyogen;腐れアンデッドがどうしてここにいるのよ。
25 = "%fsyogen;腐れアンデッドがどうしてここにいるのよ。"

# ウィズ
# いえ、あの、それは。
246 = "いえ、あの、それは。"

# アクア
# はああああ、何か言いなさいったら。\n黙られてると話が進まないのよ。
297 = "はああああ、何か言いなさいったら。\\n黙られてると話が進まないのよ。"

# カズマ
# お前は客を威圧するな。
265 = "お前は客を威圧するな。"

# アクア
# いた～～～～い。
247 = "いた～～～～い。"

# カズマ（Ｍ）
# display as カズマ
# （アクアのやつ、\n　いつにも増して気が立っているような\n　気がするな）
435 = "（アクアのやつ、\\n　いつにも増して気が立っているような\\n　気がするな）"

# カズマ（Ｍ）
# display as カズマ
# （念のため証言として押さえておくか）
439 = "（念のため証言として押さえておくか）"

# カズマ
# だいたい、ウィズがここに来るのは\n初めてじゃないだろ。
274 = "だいたい、ウィズがここに来るのは\\n初めてじゃないだろ。"

# アクア
# だって今までウィズがここに入る時は、\n私が結界を解除してたんだもの。
279 = "だって今までウィズがここに入る時は、\\n私が結界を解除してたんだもの。"

# ウィズ
# %fsyogen;あ、結界でしたら、\n入る時にちょっとピリッとしましたけど――
18 = "%fsyogen;あ、結界でしたら、\\n入る時にちょっとピリッとしましたけど――"

# アクア
# へえええええ、ちょっとだけなんだ。
302 = "へえええええ、ちょっとだけなんだ。"

# カズマ
# だからやめろ。
277 = "だからやめろ。"

# アクア
# あう！
239 = "あう！"

# カズマ（Ｍ）
# display as カズマ
# （ん？　アクアを怖がってるウィズにしては\n　軽はずみな発言だったような……）
434 = "（ん？　アクアを怖がってるウィズにしては\\n　軽はずみな発言だったような……）"

# カズマ（Ｍ）
# display as カズマ
# （念のため証言として押さえておこう）
440 = "（念のため証言として押さえておこう）"

# めぐみん
# そうそう、カズマ。\n今回のパンツはどうでしたか？
268 = "そうそう、カズマ。\\n今回のパンツはどうでしたか？"

# カズマ
# ああ、大人っぽいのと――
236 = "ああ、大人っぽいのと――"

# カズマ（Ｍ）
# display as カズマ
# （はっ！？）
433 = "（はっ！？）"

# めぐみん
# ふっ、やはり盗んでいたんですね。
300 = "ふっ、やはり盗んでいたんですね。"

# カズマ
# お前、卑怯だぞ！
263 = "お前、卑怯だぞ！"

# めぐみん
# %fsyogen;毎月寝込みを襲ってるカズマに言われたく\nありません。
24 = "%fsyogen;毎月寝込みを襲ってるカズマに言われたく\\nありません。"

# カズマ
# 人聞きの悪い言い方をするな！
330 = "人聞きの悪い言い方をするな！"

# アクア
# なーに、また盗んだの？\nほんと、好きなのね。
291 = "なーに、また盗んだの？\\nほんと、好きなのね。"

# カズマ
# だから、違うし！
276 = "だから、違うし！"

# カズマ（Ｍ）
# display as カズマ
# （待てよ、毎月、寝込みを襲う？）
437 = "（待てよ、毎月、寝込みを襲う？）"

# カズマ（Ｍ）
# display as カズマ
# （毎月と言えるのは、\n　被害者だからこその言葉なんじゃ無いのか？）
441 = "（毎月と言えるのは、\\n　被害者だからこその言葉なんじゃ無いのか？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、そんなことないか。\n　でも念のため証言としてゲットっと）
420 = "（いや、そんなことないか。\\n　でも念のため証言としてゲットっと）"

# ウィズ
# あの、カズマさん。\nみなさんにあのことを報告しなくても\nいいんですか？
240 = "あの、カズマさん。\\nみなさんにあのことを報告しなくても\\nいいんですか？"

# カズマ
# あのこと？
241 = "あのこと？"

# ウィズ
# 指輪の力のことですよ。
349 = "指輪の力のことですよ。"

# カズマ（Ｍ）
# display as カズマ
# （うぅ、やっぱり話さないとダメだよな）
421 = "（うぅ、やっぱり話さないとダメだよな）"

# カズマ
# あー、みんな、話があるんだ。
245 = "あー、みんな、話があるんだ。"

# ダクネス
# なんだ？
289 = "なんだ？"

# カズマ
# 実は、この指輪について\n新しいことがわかったんだ。
344 = "実は、この指輪について\\n新しいことがわかったんだ。"

# アクア
# まさか今度はパンツだけじゃなくて、\nブラまで盗むようになっちゃったとか？
307 = "まさか今度はパンツだけじゃなくて、\\nブラまで盗むようになっちゃったとか？"

# カズマ
# それに近いことではある、かな？
271 = "それに近いことではある、かな？"

# めぐみん
# へ？
303 = "へ？"

# カズマ
# どうやら、満月の夜が来るたびに\n少しずつ、この指輪の力が解放されていくらしい\nんだ。
284 = "どうやら、満月の夜が来るたびに\\n少しずつ、この指輪の力が解放されていくらしい\\nんだ。"

# めぐみん
# もう、嫌な予感しかしませんね。
310 = "もう、嫌な予感しかしませんね。"

# カズマ
# それでな、昨夜なんですけど……。\nパンツを２枚、盗っちゃったみたいでしてぇ。
270 = "それでな、昨夜なんですけど……。\\nパンツを２枚、盗っちゃったみたいでしてぇ。"

# ダクネス
# は、２枚！？
295 = "は、２枚！？"

# カズマ
# えへ♪
259 = "えへ♪"

# めぐみん
# 可愛くありませんよ！
341 = "可愛くありませんよ！"

# カズマ
# よーし、よしよしよし、とりあえず、落ちつけ！\nその握った拳を下ろすんだ！
313 = "よーし、よしよしよし、とりあえず、落ちつけ！\\nその握った拳を下ろすんだ！"

# めぐみん
# 今朝のカズマの行動に納得しましたよ。\nその事実を知られたくないから、\n急いで逃げ出したんですね。
332 = "今朝のカズマの行動に納得しましたよ。\\nその事実を知られたくないから、\\n急いで逃げ出したんですね。"

# カズマ
# 仕方ないだろ。原因もわからず\n２枚もパンツ持ってたら、お前らに\n何言われるかわかったもんじゃなかったし。
333 = "仕方ないだろ。原因もわからず\\n２枚もパンツ持ってたら、お前らに\\n何言われるかわかったもんじゃなかったし。"

# アクア
# ねえねえ、やっぱり指を切っちゃわない？
293 = "ねえねえ、やっぱり指を切っちゃわない？"

# カズマ
# お前はまたそれか！\nこのバカのひとつ覚えが！
264 = "お前はまたそれか！\\nこのバカのひとつ覚えが！"

# アクア
# バカって何よ！　このバカ！
326 = "バカって何よ！　このバカ！"

# カズマ
# とにかくっ、こうなったからには、\nこれまで以上に本気になって、\n指輪を外すための資金を稼ぐつもりだ。
282 = "とにかくっ、こうなったからには、\\nこれまで以上に本気になって、\\n指輪を外すための資金を稼ぐつもりだ。"

# アクア
# 何よ、稼ぐ宛てがあるような言い方じゃない。
334 = "何よ、稼ぐ宛てがあるような言い方じゃない。"

# ダクネス
# %fsyogen;またおかしなことに\n手を出すのではないだろうな？
22 = "%fsyogen;またおかしなことに\\n手を出すのではないだろうな？"

# カズマ（Ｍ）
# display as カズマ
# （おかしなことなら率先してやりそうな\n　ダクネスらしからぬ発言のような……）
424 = "（おかしなことなら率先してやりそうな\\n　ダクネスらしからぬ発言のような……）"

# カズマ（Ｍ）
# display as カズマ
# （自信は無いけど、一応証言として押さえておこう）
442 = "（自信は無いけど、一応証言として押さえておこう）"

# カズマ
# なーに、今回は心配いらないって。\n何しろギルドが仕切ってるイベントらしいからな。
292 = "なーに、今回は心配いらないって。\\n何しろギルドが仕切ってるイベントらしいからな。"

# ダクネス
# ギルド仕切りのイベント？
323 = "ギルド仕切りのイベント？"

# カズマ
# ああ。\nもうすぐこの街の運動会があるらしいじゃないか。\nしかも優勝すると賞金が出るんだろ？
238 = "ああ。\\nもうすぐこの街の運動会があるらしいじゃないか。\\nしかも優勝すると賞金が出るんだろ？"

# ダクネス
# ああ、毎年恒例のあれか。
237 = "ああ、毎年恒例のあれか。"

# めぐみん
# なんです、その運動会というのは？
290 = "なんです、その運動会というのは？"

# カズマ
# あれ？　めぐみんは知らないのか？
244 = "あれ？　めぐみんは知らないのか？"

# めぐみん
# 私は、まだそれほど、\nこの街に長くいるわけではありませんので。
413 = "私は、まだそれほど、\\nこの街に長くいるわけではありませんので。"

# カズマ
# まあ、簡単に言うと、\nみんなで運動をするイベントだよ。
305 = "まあ、簡単に言うと、\\nみんなで運動をするイベントだよ。"

# カズマ
# 今回は、そのイベントに参加して\n賞金を狙おうと思ってる！
331 = "今回は、そのイベントに参加して\\n賞金を狙おうと思ってる！"

# アクア
# ふーん、頑張ってね。
301 = "ふーん、頑張ってね。"

# めぐみん
# 健闘を祈りますよ。
337 = "健闘を祈りますよ。"

# カズマ
# 待て待て待て！\nこの俺があの屈強な冒険者と競って勝てるわけ\nないだろ！
347 = "待て待て待て！\\nこの俺があの屈強な冒険者と競って勝てるわけ\\nないだろ！"

# アクア
# だったら、なんなのよ。
278 = "だったら、なんなのよ。"

# カズマ
# だから、みんなで参加してだな――
275 = "だから、みんなで参加してだな――"

# アクア
# 運動なんてめんどくさいから嫌ですー。
417 = "運動なんてめんどくさいから嫌ですー。"

# めぐみん
# 私も遠慮したいですね。\n運動をするイベントじゃ爆裂魔法も撃てない\nでしょうし。
415 = "私も遠慮したいですね。\\n運動をするイベントじゃ爆裂魔法も撃てない\\nでしょうし。"

# カズマ（Ｍ）
# display as カズマ
# （くそっ、わかっていたこととはいえ、\n　やっぱり素直には協力してもらえないか）
425 = "（くそっ、わかっていたこととはいえ、\\n　やっぱり素直には協力してもらえないか）"

# カズマ
# 参加したら運動不足解消になるぞ。
339 = "参加したら運動不足解消になるぞ。"

# アクア
# 無駄に疲れるくらいなら、\n運動不足になった方がマシだわ。
353 = "無駄に疲れるくらいなら、\\n運動不足になった方がマシだわ。"

# めぐみん
# 私は爆裂魔法さえ撃てれば、\n運動不足になろうと関係ありませんので。
414 = "私は爆裂魔法さえ撃てれば、\\n運動不足になろうと関係ありませんので。"

# カズマ
# お前ら、それで良いのか……。
266 = "お前ら、それで良いのか……。"

# カズマ
# 参加すればギルドの心証が良くなるぞ？
340 = "参加すればギルドの心証が良くなるぞ？"

# アクア
# 心証が良くなったら何か得でもあるの？
348 = "心証が良くなったら何か得でもあるの？"

# カズマ
# え？　ええと……。
260 = "え？　ええと……。"

# カズマ
# 割の良いクエストを\n優先的に回してもらえる……とか？
338 = "割の良いクエストを\\n優先的に回してもらえる……とか？"

# めぐみん
# 自分でも良くわかっていないことで\n興味を惹こうとしないでくださいよ。
416 = "自分でも良くわかっていないことで\\n興味を惹こうとしないでくださいよ。"

# カズマ
# いや、だって……。
249 = "いや、だって……。"

# カズマ（Ｍ）
# display as カズマ
# （ここは泣き落としでもしてみるか）
427 = "（ここは泣き落としでもしてみるか）"

# カズマ
# なあ、頼むよアクア、めぐみん。\nこの通りだ、協力してくれ。\nお前たちがいてくれないとダメなんだよ俺。
287 = "なあ、頼むよアクア、めぐみん。\\nこの通りだ、協力してくれ。\\nお前たちがいてくれないとダメなんだよ俺。"

# アクア
# うわ、キモっ。そんな顔して\nすがりついて来るのやめてくれない？
254 = "うわ、キモっ。そんな顔して\\nすがりついて来るのやめてくれない？"

# めぐみん
# 正直キツいです。\n演技にしても気持ち悪いですよ？
350 = "正直キツいです。\\n演技にしても気持ち悪いですよ？"

# カズマ
# なんだよ、そこまで言うことないだろ！
288 = "なんだよ、そこまで言うことないだろ！"

# ダクネス
# %fsyogen;アクア、めぐみん、\nそう言わずにカズマに協力してやったらどうだ？
23 = "%fsyogen;アクア、めぐみん、\\nそう言わずにカズマに協力してやったらどうだ？"

# カズマ（Ｍ）
# display as カズマ
# （いつもの協力的なダクネスだな。\n　でも、念のため証言として押さえよう）
419 = "（いつもの協力的なダクネスだな。\\n　でも、念のため証言として押さえよう）"

# めぐみん
# まさかダクネスは、\nその運動会とやらに参加するつもりなのですか？
306 = "まさかダクネスは、\\nその運動会とやらに参加するつもりなのですか？"

# ダクネス
# %fsyogen;ああ。いつまでも、そのくだらない指輪に\n振り回されるのは御免だからな。
19 = "%fsyogen;ああ。いつまでも、そのくだらない指輪に\\n振り回されるのは御免だからな。"

# カズマ（Ｍ）
# display as カズマ
# （なんだろう、さっきまでとは打って変わって、\n　そこはかとなく喜んでいるように見える……）
432 = "（なんだろう、さっきまでとは打って変わって、\\n　そこはかとなく喜んでいるように見える……）"

# カズマ（Ｍ）
# display as カズマ
# （うん、証言としてゲット……）
422 = "（うん、証言としてゲット……）"

# ダクネス
# %fsyogen;それに、今の状態で衆人の前にこの身を晒す\nというのもなかなか……。
20 = "%fsyogen;それに、今の状態で衆人の前にこの身を晒す\\nというのもなかなか……。"

# カズマ
# は、なんだって？
294 = "は、なんだって？"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスが頬を緩めるような今の状態……）
436 = "（ダクネスが頬を緩めるような今の状態……）"

# カズマ（Ｍ）
# display as カズマ
# （これは証言として押さえざるを得ないか……）
428 = "（これは証言として押さえざるを得ないか……）"

# ダクネス
# と、とにかくだ！\nこういう時は協力し合うのが\nパーティーというものだろう！
280 = "と、とにかくだ！\\nこういう時は協力し合うのが\\nパーティーというものだろう！"

# ウィズ
# そうですよ。\nみなさんで力を合わせて優勝を目指すべきです！
269 = "そうですよ。\\nみなさんで力を合わせて優勝を目指すべきです！"

# ウィズ
# ダクネスさんが言うとおり、\n助け合ってこそのパーティーなんですから！
325 = "ダクネスさんが言うとおり、\\n助け合ってこそのパーティーなんですから！"

# アクア
# もしかしてそれ、\n参加を渋ってる私にっ、説教をしてるのかしら？
311 = "もしかしてそれ、\\n参加を渋ってる私にっ、説教をしてるのかしら？"

# ウィズ
# お、お説教だなんて、そんな！
261 = "お、お説教だなんて、そんな！"

# アクア
# あらぁ、さっきまでの勢いは\nどこへ行っちゃったの？
242 = "あらぁ、さっきまでの勢いは\\nどこへ行っちゃったの？"

# アクア
# ほらほら、もっと説教をしてみなさいよ。\nさーさー、早く。
304 = "ほらほら、もっと説教をしてみなさいよ。\\nさーさー、早く。"

# ウィズ
# え、ええと、ゆ、優勝を……みんなで優勝を！
255 = "え、ええと、ゆ、優勝を……みんなで優勝を！"

# アクア
# な、何よ、珍しく食い下がるじゃない。
285 = "な、何よ、珍しく食い下がるじゃない。"

# めぐみん
# …………。
235 = "…………。"

# ダクネス
# どうした、めぐみん。
283 = "どうした、めぐみん。"

# めぐみん
# はぁ、しょうがありませんね。\n私も協力しますよ。
296 = "はぁ、しょうがありませんね。\\n私も協力しますよ。"

# カズマ
# え、どういう心境の変化だ？？
256 = "え、どういう心境の変化だ？？"

# めぐみん
# ただ、カズマの犠牲者をこれ以上増やしたくない\nだけです。
272 = "ただ、カズマの犠牲者をこれ以上増やしたくない\\nだけです。"

# めぐみん
# あれは……本当に……地獄の日々ですからね。
243 = "あれは……本当に……地獄の日々ですからね。"

# カズマ
# うっ、なんかすまん。
250 = "うっ、なんかすまん。"

# ダクネス
# アクアはどうするんだ？
316 = "アクアはどうするんだ？"

# アクア
# え、参加しないけど？\nだって私にはなんの得もないじゃない。
257 = "え、参加しないけど？\\nだって私にはなんの得もないじゃない。"

# カズマ（Ｍ）
# display as カズマ
# （こいつの行動基準は、\n　自分に利益があるかどうかだもんな）
426 = "（こいつの行動基準は、\\n　自分に利益があるかどうかだもんな）"

# カズマ
# なあ、アクア。\n賞金だが、２０００万エリスは出ると睨んでる。
286 = "なあ、アクア。\\n賞金だが、２０００万エリスは出ると睨んでる。"

# アクア
# ２０００万エリス。
443 = "２０００万エリス。"

# カズマ
# 俺ひとりの取り分にするのはさすがに気が引けるし、\nある程度は山分けしようと思ってるんだ。
336 = "俺ひとりの取り分にするのはさすがに気が引けるし、\\nある程度は山分けしようと思ってるんだ。"

# アクア
# わかった、参加するわ！
314 = "わかった、参加するわ！"

# カズマ（Ｍ）
# display as カズマ
# （たく、わかりやすいやつだな）
430 = "（たく、わかりやすいやつだな）"

# アクア
# うふふ、２０００万エリス手に入ったら\n何を買おうかしら。
252 = "うふふ、２０００万エリス手に入ったら\\n何を買おうかしら。"

# カズマ（Ｍ）
# display as カズマ
# （って、独り占めする気かよ）
431 = "（って、独り占めする気かよ）"

# ダクネス
# これで全員参加だな。
267 = "これで全員参加だな。"

# カズマ
# ギルドへの参加申請はあとにするとして、\nまずは情報の収集と整理をするか。
322 = "ギルドへの参加申請はあとにするとして、\\nまずは情報の収集と整理をするか。"

[selections]
418 = "運動不足解消になるぞ"
321 = "ギルドの心証が良くなるぞ"
351 = "泣き落としをしてみるか"
