# st02a_09.txt.scn

[info]
0 = ""

[characters]
204 = "めぐみん"
213 = "カズマ"
217 = "ダクネス"
214 = "カズマ（Ｍ）"
208 = "アクア"
212 = "ウィズ"
211 = "アクア＆めぐみん＆ダクネス"

[character_subs]
# 213 = "カズマ"
287 = "３人"

[script]
# lines: 64

# めぐみん
# 情報収集は勝負事の基本ですね。
226 = "情報収集は勝負事の基本ですね。"

# カズマ
# でだ、ダクネス。\n具体的にどんなことをするんだ、この運動会は。
192 = "でだ、ダクネス。\\n具体的にどんなことをするんだ、この運動会は。"

# ダクネス
# まだそういう段階なのか。
203 = "まだそういう段階なのか。"

# カズマ
# 仕方ないだろ。\n詳しい話を聞きそびれたんだから。
220 = "仕方ないだろ。\\n詳しい話を聞きそびれたんだから。"

# ダクネス
# まあ、簡単に言うと、みんなで競争をして\n順位を競うものだと思ってくれればいい。
202 = "まあ、簡単に言うと、みんなで競争をして\\n順位を競うものだと思ってくれればいい。"

# ダクネス
# 街の入り口をスタート地点として、\n近くにある湖へと走って向かい、\nその湖を泳いで横断するとゴールというコースだ。
276 = "街の入り口をスタート地点として、\\n近くにある湖へと走って向かい、\\nその湖を泳いで横断するとゴールというコースだ。"

# カズマ
# え、それだけ？\n他に玉入れとか騎馬戦とか、部活対抗のリレーとか\nそういうのはないのか？
178 = "え、それだけ？\\n他に玉入れとか騎馬戦とか、部活対抗のリレーとか\\nそういうのはないのか？"

# ダクネス
# ？？\nよくわからないが、競技はそれだけだぞ。
288 = "？？\\nよくわからないが、競技はそれだけだぞ。"

# カズマ（Ｍ）
# display as カズマ
# （運動会っていうよりマラソン？\n　いや、自転車のないトライアスロンて感じだな）
286 = "（運動会っていうよりマラソン？\\n　いや、自転車のないトライアスロンて感じだな）"

# アクア
# ちょっと待って！\n湖ってまさか、私が浄化した……。
189 = "ちょっと待って！\\n湖ってまさか、私が浄化した……。"

# ダクネス
# ああ、あそこだ。
172 = "ああ、あそこだ。"

# アクア
# 嫌よ！　絶対に嫌！\nあそこに行ったらまたブルータルアリゲーターに\n襲われるじゃない！
222 = "嫌よ！　絶対に嫌！\\nあそこに行ったらまたブルータルアリゲーターに\\n襲われるじゃない！"

# カズマ
# そういえば、そんなトラウマ設定があったな。
182 = "そういえば、そんなトラウマ設定があったな。"

# アクア
# 設定じゃないったら！
277 = "設定じゃないったら！"

# めぐみん
# 安心してくださいアクア。\nブルータルアリゲーターの目撃情報は、\nあれ以来ありませんから。
224 = "安心してくださいアクア。\\nブルータルアリゲーターの目撃情報は、\\nあれ以来ありませんから。"

# アクア
# でも……。
193 = "でも……。"

# カズマ
# てか、ちょっと待て。\n去年まではあの湖を泳いで渡ってたのか？
191 = "てか、ちょっと待て。\\n去年まではあの湖を泳いで渡ってたのか？"

# ダクネス
# そうだぞ、ブルータルアリゲーターが\nうようよいたからな。\nまさに阿鼻叫喚の地獄絵図だった。
185 = "そうだぞ、ブルータルアリゲーターが\\nうようよいたからな。\\nまさに阿鼻叫喚の地獄絵図だった。"

# カズマ
# 嬉しそうに言うなよ。
223 = "嬉しそうに言うなよ。"

# ダクネス
# そういえば今年は、\n例年以上に参加希望者が多いと聞いたな。
184 = "そういえば今年は、\\n例年以上に参加希望者が多いと聞いたな。"

# めぐみん
# あっ、ブルータルアリゲーターが\nいなくなったからですね。
173 = "あっ、ブルータルアリゲーターが\\nいなくなったからですね。"

# ダクネス
# アクアが湖を浄化する前は、\nいかにブルータルアリゲーターを討伐しつつ\n前に進めるかが勝負の決め手だった。
209 = "アクアが湖を浄化する前は、\\nいかにブルータルアリゲーターを討伐しつつ\\n前に進めるかが勝負の決め手だった。"

# ダクネス
# しかし今年は、単純なスピード勝負になりそうだ。
181 = "しかし今年は、単純なスピード勝負になりそうだ。"

# カズマ
# スピード勝負か、泳ぎにはあんまり自信が\n無いんだよな。
215 = "スピード勝負か、泳ぎにはあんまり自信が\\n無いんだよな。"

# めぐみん
# 私は泳げはしますが、\nスピードには自信がありませんね。
274 = "私は泳げはしますが、\\nスピードには自信がありませんね。"

# ウィズ
# 私は、冒険者時代に少し川遊びをした程度です。
273 = "私は、冒険者時代に少し川遊びをした程度です。"

# カズマ
# つまり泳げないと？
190 = "つまり泳げないと？"

# ウィズ
# 浮くことはできるのですが。
228 = "浮くことはできるのですが。"

# カズマ
# ダ、ダクネスは？
216 = "ダ、ダクネスは？"

# ダクネス
# 泳ぎは未経験だな。\nだが、沈む苦しさには耐える自信があるぞ！
227 = "泳ぎは未経験だな。\\nだが、沈む苦しさには耐える自信があるぞ！"

# カズマ
# お前は湖底を歩いていくつもりか……。
180 = "お前は湖底を歩いていくつもりか……。"

# カズマ（Ｍ）
# display as カズマ
# （これは特訓の必要がありそうだ……）
280 = "（これは特訓の必要がありそうだ……）"

# アクア
# ねえねえ、カズマカズマ。\n私にも聞いて。
197 = "ねえねえ、カズマカズマ。\\n私にも聞いて。"

# カズマ
# そういえばお前って一応水の女神だったよな。
183 = "そういえばお前って一応水の女神だったよな。"

# アクア
# 一応じゃないったら！
218 = "一応じゃないったら！"

# カズマ
# はいはい。\nそれで、お前はどうなんだよ。
198 = "はいはい。\\nそれで、お前はどうなんだよ。"

# アクア
# ふふん、私にとって水の中は陸地と\n同じようなものよ。
200 = "ふふん、私にとって水の中は陸地と\\n同じようなものよ。"

# カズマ
# うん、そういう見栄はいらないから。
177 = "うん、そういう見栄はいらないから。"

# アクア
# あら、そんなこと言っちゃっていいのかしら？
174 = "あら、そんなこと言っちゃっていいのかしら？"

# カズマ
# え、まさか本当に泳ぎが得意なのか？
179 = "え、まさか本当に泳ぎが得意なのか？"

# アクア
# ねえ、カズマは地面を歩くのが得意だって\nわざわざ言う？
196 = "ねえ、カズマは地面を歩くのが得意だって\\nわざわざ言う？"

# カズマ
# いや、言わないけど、それはできて普通だし。
176 = "いや、言わないけど、それはできて普通だし。"

# アクア
# 私もそうなのよ。\nどうしてできて当然のことを得意だなんて\n言わないといけないの。
275 = "私もそうなのよ。\\nどうしてできて当然のことを得意だなんて\\n言わないといけないの。"

# カズマ（Ｍ）
# display as カズマ
# （マジかー！！\n　悔しいけどアクアが光って見えるぜ！）
282 = "（マジかー！！\\n　悔しいけどアクアが光って見えるぜ！）"

# めぐみん
# アクアアクア、私に泳ぎ方を教えてくださいよ！
210 = "アクアアクア、私に泳ぎ方を教えてくださいよ！"

# ダクネス
# 私にも頼む！
272 = "私にも頼む！"

# アクア
# もう、しょうがないわね。
205 = "もう、しょうがないわね。"

# カズマ
# よーし。じゃあ優勝を目指して、\nさっそく明日から水泳の特訓を始めるぞ！
207 = "よーし。じゃあ優勝を目指して、\\nさっそく明日から水泳の特訓を始めるぞ！"

# めぐみん
# そんなことを言って、実は私たちの\n水着姿が目当てなんてことはないでしょうね？
187 = "そんなことを言って、実は私たちの\\n水着姿が目当てなんてことはないでしょうね？"

# カズマ
# へ？
201 = "へ？"

# カズマ（Ｍ）
# display as カズマ
# （水着姿、だと……）
283 = "（水着姿、だと……）"

# カズマ（Ｍ）
# display as カズマ
# （言われてみれば、水泳の特訓てことになれば、\n　当然みんな水着姿になるわけで……）
285 = "（言われてみれば、水泳の特訓てことになれば、\\n　当然みんな水着姿になるわけで……）"

# カズマ（Ｍ）
# display as カズマ
# （あれ？　もしかして俺、ドキドキしてる？\n　普段の言動はともかく、見た目だけなら\n　平均以上なこいつらが普段以上の薄着で……）
278 = "（あれ？　もしかして俺、ドキドキしてる？\\n　普段の言動はともかく、見た目だけなら\\n　平均以上なこいつらが普段以上の薄着で……）"

# カズマ（Ｍ）
# display as カズマ
# （というか水着なんて、\n　ぶっちゃけ下着も同然だよな！）
281 = "（というか水着なんて、\\n　ぶっちゃけ下着も同然だよな！）"

# カズマ（Ｍ）
# display as カズマ
# （泳ぐためとか言ったところで、\n　あんないろいろ丸出しな格好をされたら、\n　健全な童貞男子にはたまらないというか……）
284 = "（泳ぐためとか言ったところで、\\n　あんないろいろ丸出しな格好をされたら、\\n　健全な童貞男子にはたまらないというか……）"

# カズマ（Ｍ）
# display as カズマ
# （ええい、まったくけしからん！）
279 = "（ええい、まったくけしからん！）"

# アクア
# あんた、下品なこと考えてるでしょ。
175 = "あんた、下品なこと考えてるでしょ。"

# カズマ
# は！？
199 = "は！？"

# めぐみん
# やっぱりそうですよ。\nこの男、水着姿が目当てに違いありません。
206 = "やっぱりそうですよ。\\nこの男、水着姿が目当てに違いありません。"

# アクア
# どうせ水着なんて\n下着と同じとか思ってるでしょう？\nやめてよね。そういう汚らわしい目で見るの。
195 = "どうせ水着なんて\\n下着と同じとか思ってるでしょう？\\nやめてよね。そういう汚らわしい目で見るの。"

# ダクネス
# そうだぞ。腹をすかせた肉食獣のような\nギラつく眼差しで、肌を舐めるように眺め\nまわされては、いかに私といえども……。
186 = "そうだぞ。腹をすかせた肉食獣のような\\nギラつく眼差しで、肌を舐めるように眺め\\nまわされては、いかに私といえども……。"

# カズマ
# ち、違うわ！\nあくまで勝つために……そう、優勝するための\n特訓なんだから、変な誤解はやめろ！
188 = "ち、違うわ！\\nあくまで勝つために……そう、優勝するための\\n特訓なんだから、変な誤解はやめろ！"

# カズマ
# とにかく明日から水泳の特訓だからな！\nいいな？　わかったな？
194 = "とにかく明日から水泳の特訓だからな！\\nいいな？　わかったな？"

# アクア＆めぐみん＆ダクネス
# display as ３人
# …………。
171 = "…………。"

