# st02b_06.txt.scn

[info]
0 = ""

[characters]
249 = "カズマ"
247 = "アクア"
251 = "カズマ（Ｍ）"
241 = "めぐみん"
253 = "ダクネス"
252 = "クリス"
248 = "ウィズ"
244 = "ゆんゆん"

[character_subs]
# 249 = "カズマ"

[script]
# lines: 90

# カズマ
# １、２、３、４。\n２、２、３、４。
344 = "１、２、３、４。\\n２、２、３、４。"

# カズマ
# ふー。こんなふうに準備運動をしてると、\nなんか学生時代を思い出して懐かしい気分に――
237 = "ふー。こんなふうに準備運動をしてると、\\nなんか学生時代を思い出して懐かしい気分に――"

# カズマ
# ならないな、特に。
229 = "ならないな、特に。"

# アクア
# なーにぶつぶつ言ってるのよ？
232 = "なーにぶつぶつ言ってるのよ？"

# カズマ
# おう、アク――
210 = "おう、アク――"

# カズマ
# うおおおお！？
202 = "うおおおお！？"

# アクア
# ど、どうしたのよいきなり変な声出して？
225 = "ど、どうしたのよいきなり変な声出して？"

# カズマ
# いや、なんていうか……。
201 = "いや、なんていうか……。"

# カズマ（Ｍ）
# display as カズマ
# （まぶしい……\n　こいつが、こんなにまぶしく見えるなんて。\n　恐ろしきは水着効果）
337 = "（まぶしい……\\n　こいつが、こんなにまぶしく見えるなんて。\\n　恐ろしきは水着効果）"

# カズマ（Ｍ）
# display as カズマ
# （普段、だらしない格好をしてるから、\n　わりと際どい姿を見てるつもりだったけど、\n　太陽の下でこういうのを見ると印象が……）
340 = "（普段、だらしない格好をしてるから、\\n　わりと際どい姿を見てるつもりだったけど、\\n　太陽の下でこういうのを見ると印象が……）"

# アクア
# あ、もしかしてカズマ、\n私のあまりの美しさに見とれちゃってるの？
198 = "あ、もしかしてカズマ、\\n私のあまりの美しさに見とれちゃってるの？"

# カズマ
# ななな、何言ってんだ！　そんなわけないだろ！
227 = "ななな、何言ってんだ！　そんなわけないだろ！"

# めぐみん
# 何を騒いでいるんです？
257 = "何を騒いでいるんです？"

# アクア
# 聞いてよめぐみん。カズマったら、\n私に見とれてこーんなイヤらしい顔してるのよ？
320 = "聞いてよめぐみん。カズマったら、\\n私に見とれてこーんなイヤらしい顔してるのよ？"

# カズマ
# 誰がイヤらしい顔なんて――
322 = "誰がイヤらしい顔なんて――"

# ダクネス
# 周りに人がいないからといって、\nあまり騒ぐものではないぞ。
262 = "周りに人がいないからといって、\\nあまり騒ぐものではないぞ。"

# クリス
# でも、今日は練習だから良いけど、\n本番は人がいっぱいいるんだよね？\nこういう格好するのはちょっと恥ずかしいかも。
224 = "でも、今日は練習だから良いけど、\\n本番は人がいっぱいいるんだよね？\\nこういう格好するのはちょっと恥ずかしいかも。"

# ウィズ
# 大丈夫ですよ。\nみなさん、順位を競っているんですから、\n周りを気にする余裕なんてないですよきっと。
264 = "大丈夫ですよ。\\nみなさん、順位を競っているんですから、\\n周りを気にする余裕なんてないですよきっと。"

# ゆんゆん
# ですよね！　じゃないと私、\n泳ぐのに集中なんてできなくなっちゃいます。
222 = "ですよね！　じゃないと私、\\n泳ぐのに集中なんてできなくなっちゃいます。"

# カズマ
# ぐは！？
213 = "ぐは！？"

# カズマ（Ｍ）
# display as カズマ
# （何この夢みたいな光景！？）
339 = "（何この夢みたいな光景！？）"

# カズマ（Ｍ）
# display as カズマ
# （貧乳から巨乳まで、\n　どれでもお好きなのをどうぞって感じで\n　取り揃えられた、そういうお店か何かか？）
342 = "（貧乳から巨乳まで、\\n　どれでもお好きなのをどうぞって感じで\\n　取り揃えられた、そういうお店か何かか？）"

# カズマ（Ｍ）
# display as カズマ
# （しかも悔しいことに、\n　やっぱりこいつら黙ってれば美少女だからな。\n　こんなふうに並んでると絵になりやがって！）
331 = "（しかも悔しいことに、\\n　やっぱりこいつら黙ってれば美少女だからな。\\n　こんなふうに並んでると絵になりやがって！）"

# カズマ（Ｍ）
# display as カズマ
# （くそっ、童貞には刺激が強すぎる……\n　どこに目をやれば良いんだよ？\n　どこを見ても目の毒だろ、こんなの）
329 = "（くそっ、童貞には刺激が強すぎる……\\n　どこに目をやれば良いんだよ？\\n　どこを見ても目の毒だろ、こんなの）"

# めぐみん
# ふむ。確かにカズマの様子がおかしいですね。
236 = "ふむ。確かにカズマの様子がおかしいですね。"

# カズマ
# お、おかしくねーし。
208 = "お、おかしくねーし。"

# めぐみん
# なら、ちゃんと私の方を見てくださいよ。
228 = "なら、ちゃんと私の方を見てくださいよ。"

# カズマ
# お前、女の子だったらもっと恥じらいを持てよ！\nそんな薄着で胸を張ったりするんじゃない！
211 = "お前、女の子だったらもっと恥じらいを持てよ！\\nそんな薄着で胸を張ったりするんじゃない！"

# めぐみん
# 水着を着ているのに変に恥ずかしがったら、\nその方がいかがわしく見えるじゃないですか。
270 = "水着を着ているのに変に恥ずかしがったら、\\nその方がいかがわしく見えるじゃないですか。"

# めぐみん
# ほら、ちゃんと見て、\n水着の感想を言ってみてください。
238 = "ほら、ちゃんと見て、\\n水着の感想を言ってみてください。"

# カズマ
# か、感想とか言われても……。
212 = "か、感想とか言われても……。"

# カズマ（Ｍ）
# display as カズマ
# （面白がって無茶ぶりしやがって……）
343 = "（面白がって無茶ぶりしやがって……）"

# カズマ（Ｍ）
# display as カズマ
# （お、落ち着け。めぐみんとは\n　一緒に風呂に入ったことだってあるんだ。\n　水着姿くらいで今さら動揺なんて……）
328 = "（お、落ち着け。めぐみんとは\\n　一緒に風呂に入ったことだってあるんだ。\\n　水着姿くらいで今さら動揺なんて……）"

# カズマ（Ｍ）
# display as カズマ
# （いやしかし、ロリボディではあるものの、\n　あるべき所に肉がないだけで、全体的には\n　女の子らしい柔らかいラインなのが意外と……）
327 = "（いやしかし、ロリボディではあるものの、\\n　あるべき所に肉がないだけで、全体的には\\n　女の子らしい柔らかいラインなのが意外と……）"

# めぐみん
# カズマ、どうしました？
250 = "カズマ、どうしました？"

# カズマ
# その……似合ってるんじゃないか？
218 = "その……似合ってるんじゃないか？"

# めぐみん
# ふむ。
235 = "ふむ。"

# めぐみん
# では、こちらはどうです？
223 = "では、こちらはどうです？"

# ゆんゆん
# え？　めぐみんてば何？
207 = "え？　めぐみんてば何？"

# カズマ
# うおっ！？
203 = "うおっ！？"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんとはまったく違う、\n　確かなボリュームのある胸のふくらみ……）
338 = "（めぐみんとはまったく違う、\\n　確かなボリュームのある胸のふくらみ……）"

# めぐみん
# さあ、次はゆんゆんを見ての感想を言ってください。
215 = "さあ、次はゆんゆんを見ての感想を言ってください。"

# ゆんゆん
# や、やめてよ、恥ずかしいでしょ！
243 = "や、やめてよ、恥ずかしいでしょ！"

# カズマ（Ｍ）
# display as カズマ
# （ああ、なんて無慈悲な。\n　世の中はなんでこんなに不公平なのか）
324 = "（ああ、なんて無慈悲な。\\n　世の中はなんでこんなに不公平なのか）"

# めぐみん
# なんですか、その同情するような目は。
231 = "なんですか、その同情するような目は。"

# カズマ
# めぐみん、強く生きて行こうな？
242 = "めぐみん、強く生きて行こうな？"

# めぐみん
# 良くわかりませんが、腹が立ちますね。
321 = "良くわかりませんが、腹が立ちますね。"

# ゆんゆん
# あ、あの、カズマさん。\n無理に感想とか、言う必要はありませんので。
196 = "あ、あの、カズマさん。\\n無理に感想とか、言う必要はありませんので。"

# めぐみん
# 何を言っているんですか。\nこれは一種の儀式なんですよ。
256 = "何を言っているんですか。\\nこれは一種の儀式なんですよ。"

# めぐみん
# さあ、カズマ、言ってください！
214 = "さあ、カズマ、言ってください！"

# カズマ
# あ……うん。似合ってると思うぞ。
195 = "あ……うん。似合ってると思うぞ。"

# ゆんゆん
# ……ありがとうございます。
194 = "……ありがとうございます。"

# クリス
# さっきから似合ってるばっかで、\nもっと違う褒め方はないの？
216 = "さっきから似合ってるばっかで、\\nもっと違う褒め方はないの？"

# カズマ
# いや、そんなこと言われても。
200 = "いや、そんなこと言われても。"

# カズマ（Ｍ）
# display as カズマ
# （てか、前屈みで覗き込んで来ないでくれ）
334 = "（てか、前屈みで覗き込んで来ないでくれ）"

# カズマ（Ｍ）
# display as カズマ
# （いくらクリスの胸が無いといっても、\n　視線の置き場に困るだろ）
325 = "（いくらクリスの胸が無いといっても、\\n　視線の置き場に困るだろ）"

# クリス
# それで、私の水着の感想は？
219 = "それで、私の水着の感想は？"

# カズマ
# それ以前にお前、恥ずかしくないのか？
220 = "それ以前にお前、恥ずかしくないのか？"

# クリス
# 普段から露出のある服を着てるからね。\n平気じゃないと嘘になるけどさ。
267 = "普段から露出のある服を着てるからね。\\n平気じゃないと嘘になるけどさ。"

# カズマ（Ｍ）
# display as カズマ
# （確かにクリスは普段から腹を出してるし、\n　いつもの服だと思えば……）
341 = "（確かにクリスは普段から腹を出してるし、\\n　いつもの服だと思えば……）"

# クリス
# ん？
246 = "ん？"

# カズマ（Ｍ）
# display as カズマ
# （って、見られるか！！）
332 = "（って、見られるか！！）"

# クリス
# ほら、感想は？
239 = "ほら、感想は？"

# カズマ
# ええと……か、可愛いんじゃないか？
204 = "ええと……か、可愛いんじゃないか？"

# クリス
# あはは。\n無難な言葉だけど、まあ、ありがと。
199 = "あはは。\\n無難な言葉だけど、まあ、ありがと。"

# カズマ（Ｍ）
# display as カズマ
# （くっ、自分の語彙力の無さが情けない）
330 = "（くっ、自分の語彙力の無さが情けない）"

# カズマ（Ｍ）
# display as カズマ
# （でも、でかいとか、小さいとか\n　口走るよりはマシだろ、さすがに）
335 = "（でも、でかいとか、小さいとか\\n　口走るよりはマシだろ、さすがに）"

# カズマ（Ｍ）
# display as カズマ
# （いくら俺だってそれくらいの分別は……）
326 = "（いくら俺だってそれくらいの分別は……）"

# ダクネス
# どうした？
226 = "どうした？"

# カズマ
# でか！？
221 = "でか！？"

# ダクネス
# なんだと！？
230 = "なんだと！？"

# カズマ
# あ、しまった！
197 = "あ、しまった！"

# カズマ（Ｍ）
# display as カズマ
# （つい本音が漏れちまった）
333 = "（つい本音が漏れちまった）"

# ダクネス
# 貴様、やはりそういう邪な気持ちで\n私たちのことを見ているのだな！
323 = "貴様、やはりそういう邪な気持ちで\\n私たちのことを見ているのだな！"

# カズマ
# お、お前が無駄にけしからん身体を\nしてるのが悪いんだろ！
209 = "お、お前が無駄にけしからん身体を\\nしてるのが悪いんだろ！"

# カズマ
# 変な気なんかなくても、\n男はそういう所に目が行っちゃう生き物なんだよ！
263 = "変な気なんかなくても、\\n男はそういう所に目が行っちゃう生き物なんだよ！"

# ダクネス
# 無駄とはなんだ無駄とは！
271 = "無駄とはなんだ無駄とは！"

# ダクネス
# は！？　そうやって上に注意を向けておいて、\nまさか、これまで剥ぐつもりではないだろうな！
234 = "は！？　そうやって上に注意を向けておいて、\\nまさか、これまで剥ぐつもりではないだろうな！"

# ウィズ
# み、水着まで！？　ダメですよ！
240 = "み、水着まで！？　ダメですよ！"

# カズマ
# 剥ぐって水着をか？　するかバカ！\n俺をどんだけ変質者に仕立て上げたいんだ！
258 = "剥ぐって水着をか？　するかバカ！\\n俺をどんだけ変質者に仕立て上げたいんだ！"

# アクア
# ねえねえ、カズマ、私はどうかしら？\nこの水着選ぶのにけっこう時間がかかったの。
233 = "ねえねえ、カズマ、私はどうかしら？\\nこの水着選ぶのにけっこう時間がかかったの。"

# カズマ
# そうだな。
217 = "そうだな。"

# アクア
# わくわく。
245 = "わくわく。"

# カズマ
# ええと、なんていうか普通？
205 = "ええと、なんていうか普通？"

# アクア
# 普通ってどういうことよ。
269 = "普通ってどういうことよ。"

# カズマ
# 可もなく不可もなくっていうか、\nとにかく普通だなーと。
259 = "可もなく不可もなくっていうか、\\nとにかく普通だなーと。"

# アクア
# 何よそれ！\n悪く言われるよりもショックなんですけど！
255 = "何よそれ！\\n悪く言われるよりもショックなんですけど！"

# カズマ
# 普通ってことは似合ってるってことだろ。\n言葉の裏を変に読まないでくれ。
268 = "普通ってことは似合ってるってことだろ。\\n言葉の裏を変に読まないでくれ。"

# アクア
# えへへ、似合ってるならいいわ。\nありがと、カズマ。
206 = "えへへ、似合ってるならいいわ。\\nありがと、カズマ。"

# カズマ（Ｍ）
# display as カズマ
# （はあ、すでに疲れた……）
336 = "（はあ、すでに疲れた……）"

