# st02b_07.txt.scn

[info]
0 = ""

[characters]
430 = "ダクネス"
419 = "カズマ"
409 = "アクア"
397 = "めぐみん"
399 = "ゆんゆん"
423 = "カズマ（Ｍ）"
425 = "クリス"
413 = "ウィズ"

[character_subs]
# 419 = "カズマ"

[script]
# lines: 175

# ダクネス
# それで、私たちは何をすればいいんだ？
344 = "それで、私たちは何をすればいいんだ？"

# カズマ
# そうだな。\nみんながどれくらいのレベルかを確認して\nおきたいから、ひとりずつ泳いでもらうか。
341 = "そうだな。\\nみんながどれくらいのレベルかを確認して\\nおきたいから、ひとりずつ泳いでもらうか。"

# アクア
# はいはい！　私！　私からやらせて！
386 = "はいはい！　私！　私からやらせて！"

# カズマ
# 珍しくやる気満々だな。
458 = "珍しくやる気満々だな。"

# めぐみん
# 自分の得意分野ですからね。\n私も爆裂魔法を撃てと言われたら、\n指名される前に詠唱を始めますよ。
541 = "自分の得意分野ですからね。\\n私も爆裂魔法を撃てと言われたら、\\n指名される前に詠唱を始めますよ。"

# カズマ
# それは物騒だからやめろ。
351 = "それは物騒だからやめろ。"

# アクア
# じゃあ、行くわよ！
336 = "じゃあ、行くわよ！"

# ダクネス
# おお、これは！
323 = "おお、これは！"

# めぐみん
# なんと言いますか、目を奪われる美しさですね。
378 = "なんと言いますか、目を奪われる美しさですね。"

# カズマ
# あいつ、本当に泳げたんだな。
301 = "あいつ、本当に泳げたんだな。"

# ダクネス
# なんだ、信じてなかったのか？
374 = "なんだ、信じてなかったのか？"

# カズマ
# 逆に訊くが、ダクネスは信じてたのか？
542 = "逆に訊くが、ダクネスは信じてたのか？"

# ダクネス
# それは……まあ少しだけだが。
348 = "それは……まあ少しだけだが。"

# アクア
# どう？　なかなかのものでしょ。
368 = "どう？　なかなかのものでしょ。"

# カズマ
# ああ、正直驚いた。\nでもだ！
299 = "ああ、正直驚いた。\\nでもだ！"

# アクア
# 何よ。
438 = "何よ。"

# カズマ
# レベルが高すぎて参考にならん！
434 = "レベルが高すぎて参考にならん！"

# アクア
# ええ！！　そうなの！！
318 = "ええ！！　そうなの！！"

# カズマ
# じゃあ次はめぐみん、泳いでみてくれ。
337 = "じゃあ次はめぐみん、泳いでみてくれ。"

# めぐみん
# 仕方ありませんね。
436 = "仕方ありませんね。"

# ダクネス
# 泳いでいる。
452 = "泳いでいる。"

# カズマ
# 泳いではいるが。
453 = "泳いではいるが。"

# ゆんゆん
# 遅いですね。
543 = "遅いですね。"

# カズマ
# ああ、予想以上に遅い。
298 = "ああ、予想以上に遅い。"

# めぐみん
# はぁはぁ、どうでしたか？
384 = "はぁはぁ、どうでしたか？"

# カズマ
# うんまあ、悪くなかったぞ。\nでも、お前が自分で言ったとおり、\nスピードに難ありだ。
313 = "うんまあ、悪くなかったぞ。\\nでも、お前が自分で言ったとおり、\\nスピードに難ありだ。"

# めぐみん
# むむ、やはりそうですか。
396 = "むむ、やはりそうですか。"

# カズマ
# じゃあ、次は――
334 = "じゃあ、次は――"

# カズマ（Ｍ）
# display as カズマ
# （ウィズとダクネスは泳げないってわかってるし）
560 = "（ウィズとダクネスは泳げないってわかってるし）"

# ゆんゆん
# 情けないわね、めぐみん！
448 = "情けないわね、めぐみん！"

# カズマ（Ｍ）
# display as カズマ
# （ん？）
559 = "（ん？）"

# めぐみん
# なんです、その勝ち誇った顔は。\nまさか、泳げるとでも？
376 = "なんです、その勝ち誇った顔は。\\nまさか、泳げるとでも？"

# ゆんゆん
# 当然じゃない。
447 = "当然じゃない。"

# めぐみん
# 本当ですか？　疑わしいですね。
451 = "本当ですか？　疑わしいですね。"

# ゆんゆん
# 本当だもん！
450 = "本当だもん！"

# ゆんゆん
# みんなで川遊びに行ったりしたとき、\n誰かが溺れても助けられるように練習したんだから！
393 = "みんなで川遊びに行ったりしたとき、\\n誰かが溺れても助けられるように練習したんだから！"

# めぐみん
# でも、まだ、みんなで川遊びに行く機会すらも\nないんですよね。
364 = "でも、まだ、みんなで川遊びに行く機会すらも\\nないんですよね。"

# ゆんゆん
# そ、そうだけど、準備をするにこしたことは\nないじゃない！
340 = "そ、そうだけど、準備をするにこしたことは\\nないじゃない！"

# めぐみん
# ゆんゆんには、\nそういう準備よりも他にすべきことがあると\n思うのですが。
400 = "ゆんゆんには、\\nそういう準備よりも他にすべきことがあると\\n思うのですが。"

# ゆんゆん
# た、例えば？
353 = "た、例えば？"

# めぐみん
# そうですね、人を遊びに誘う練習でしょうか。
342 = "そうですね、人を遊びに誘う練習でしょうか。"

# ゆんゆん
# でもでも、こっちの都合だけで誘ったりしたら、\n相手に断るための気を使わせちゃったりしない？
366 = "でもでも、こっちの都合だけで誘ったりしたら、\\n相手に断るための気を使わせちゃったりしない？"

# ゆんゆん
# それに、約束の日に雨が降ったら、\nがっかりさせちゃうかもだし……。
347 = "それに、約束の日に雨が降ったら、\\nがっかりさせちゃうかもだし……。"

# めぐみん
# あー、もう、面倒な子ですね！
307 = "あー、もう、面倒な子ですね！"

# めぐみん
# そんなだから、いつまで経っても友達が\nできないんですよ！
352 = "そんなだから、いつまで経っても友達が\\nできないんですよ！"

# ゆんゆん
# だ、だって～～。
354 = "だ、だって～～。"

# カズマ（Ｍ）
# display as カズマ
# （この２人が絡むと、\n　どうしてこうも騒がしくなるんだ……）
548 = "（この２人が絡むと、\\n　どうしてこうも騒がしくなるんだ……）"

# カズマ（Ｍ）
# display as カズマ
# （でもまあ、ゆんゆんは泳げるようで安心した）
553 = "（でもまあ、ゆんゆんは泳げるようで安心した）"

# カズマ
# あとは……。
305 = "あとは……。"

# クリス
# ん？　あたし？\nあたしも泳げるよ。
408 = "ん？　あたし？\\nあたしも泳げるよ。"

# カズマ
# おお、マジか！
324 = "おお、マジか！"

# クリス
# でも、競技には向いてないかも。
365 = "でも、競技には向いてないかも。"

# クリス
# あたしのは斥候目的の泳法だから、\n水音を立てないことが大前提なんだよね。
302 = "あたしのは斥候目的の泳法だから、\\n水音を立てないことが大前提なんだよね。"

# カズマ
# つまりスピードは出せないと……。
360 = "つまりスピードは出せないと……。"

# クリス
# がっかりされるのは心外だな。\nあくまで私は、そういう目的での泳法しか\n練習してないってだけなのに。
329 = "がっかりされるのは心外だな。\\nあくまで私は、そういう目的での泳法しか\\n練習してないってだけなのに。"

# カズマ
# じゃあ、スピードを出すことを目的に\nちゃんと練習すれば！
333 = "じゃあ、スピードを出すことを目的に\\nちゃんと練習すれば！"

# クリス
# うん、いけると思うよ。\n過剰な期待も困るけどね。
312 = "うん、いけると思うよ。\\n過剰な期待も困るけどね。"

# カズマ（Ｍ）
# display as カズマ
# （ええと、じゃあ、問題がないのは\n　アクアとゆんゆん――）
545 = "（ええと、じゃあ、問題がないのは\\n　アクアとゆんゆん――）"

# カズマ（Ｍ）
# display as カズマ
# （一応泳げるのは、めぐみんとクリス――）
562 = "（一応泳げるのは、めぐみんとクリス――）"

# カズマ（Ｍ）
# display as カズマ
# （まったく泳げないのは、ダクネスとウィズっと）
555 = "（まったく泳げないのは、ダクネスとウィズっと）"

# カズマ
# ダクネスとウィズには、\n基礎から教えるしかないか。
431 = "ダクネスとウィズには、\\n基礎から教えるしかないか。"

# ダクネス
# よろしく頼む！
402 = "よろしく頼む！"

# ウィズ
# お願いします！
328 = "お願いします！"

# クリス
# あたしはゆんゆんに教えて貰うから。
303 = "あたしはゆんゆんに教えて貰うから。"

# ゆんゆん
# ええ、私ですか！？
315 = "ええ、私ですか！？"

# クリス
# 泳ぐ練習をしたってことは、\nコツを知ってるのと同義じゃない。
455 = "泳ぐ練習をしたってことは、\\nコツを知ってるのと同義じゃない。"

# ゆんゆん
# それはまあ、はい。\n私なりのコツになっちゃいますが。
349 = "それはまあ、はい。\\n私なりのコツになっちゃいますが。"

# クリス
# それで十分。\n頼りにしてるからね、先生。
346 = "それで十分。\\n頼りにしてるからね、先生。"

# ゆんゆん
# せ、先生！？\nは、はい、頑張ります！
339 = "せ、先生！？\\nは、はい、頑張ります！"

# めぐみん
# じゃあ、私は……。
335 = "じゃあ、私は……。"

# カズマ
# お前もゆんゆんに教えて貰えばいいじゃん。
327 = "お前もゆんゆんに教えて貰えばいいじゃん。"

# めぐみん
# 嫌ですよ。
443 = "嫌ですよ。"

# カズマ（Ｍ）
# display as カズマ
# （即答かよ……）
563 = "（即答かよ……）"

# アクア
# カーズマ。\n私も泳げるわよ？
424 = "カーズマ。\\n私も泳げるわよ？"

# カズマ（Ｍ）
# display as カズマ
# （さっき見た、アクアの泳ぎを見て確信した。\n　こいつは絶対に感覚だけで泳いでる）
549 = "（さっき見た、アクアの泳ぎを見て確信した。\\n　こいつは絶対に感覚だけで泳いでる）"

# カズマ（Ｍ）
# display as カズマ
# （そんなやつが、人に教えられるはずがねー）
550 = "（そんなやつが、人に教えられるはずがねー）"

# カズマ
# アクア、お前にはして欲しいことがあるんだ！
410 = "アクア、お前にはして欲しいことがあるんだ！"

# アクア
# なになに？
371 = "なになに？"

# カズマ
# コースの下見をしてきて欲しい。
429 = "コースの下見をしてきて欲しい。"

# アクア
# 泳ぎを教えるんじゃなくて？
454 = "泳ぎを教えるんじゃなくて？"

# カズマ
# これは下見を兼ねた練習でもあるんだよ。\n実際にコースを泳いで感覚を掴むのって\n大切だからさ。
331 = "これは下見を兼ねた練習でもあるんだよ。\\n実際にコースを泳いで感覚を掴むのって\\n大切だからさ。"

# アクア
# だったら、私だけじゃなくて\nみんなもするべきじゃない。
356 = "だったら、私だけじゃなくて\\nみんなもするべきじゃない。"

# カズマ
# お前には自分のペースで泳いで貰う必要が\nあるんだって。
326 = "お前には自分のペースで泳いで貰う必要が\\nあるんだって。"

# アクア
# どうして？
367 = "どうして？"

# カズマ
# アクア、ちょい耳を貸せ。
411 = "アクア、ちょい耳を貸せ。"

# アクア
# え、何？
314 = "え、何？"

# カズマ
# みんなのモチベーションが落ちるかもしれないから\n言えなかったんだけど。
394 = "みんなのモチベーションが落ちるかもしれないから\\n言えなかったんだけど。"

# アクア
# う、うん。
310 = "う、うん。"

# カズマ
# 俺は、お前をこのチームのエースだと考えてる！
439 = "俺は、お前をこのチームのエースだと考えてる！"

# アクア
# エース！？
418 = "エース！？"

# カズマ
# エースのアクアには\nその力を１００％発揮して欲しいんだよ。
417 = "エースのアクアには\\nその力を１００％発揮して欲しいんだよ。"

# アクア
# なるほど、だから、誰も気にする必要が無いように\nひとりで行くのね！
373 = "なるほど、だから、誰も気にする必要が無いように\\nひとりで行くのね！"

# カズマ
# みんなの泳ぎの練習は、俺とゆんゆんで見るから、\nお前は自分の力を１００％発揮できる準備を\n進めてくれ！
395 = "みんなの泳ぎの練習は、俺とゆんゆんで見るから、\\nお前は自分の力を１００％発揮できる準備を\\n進めてくれ！"

# アクア
# わかったわ！
404 = "わかったわ！"

# カズマ（Ｍ）
# display as カズマ
# （よし、これでアクアはオッケーっと）
557 = "（よし、これでアクアはオッケーっと）"

# カズマ
# 泳げない連中には、\nもうつきっきりで手取り足取り教えるしか\nないよな。
456 = "泳げない連中には、\\nもうつきっきりで手取り足取り教えるしか\\nないよな。"

# めぐみん
# 手取り足取り？
449 = "手取り足取り？"

# カズマ
# なんだよ？
375 = "なんだよ？"

# めぐみん
# いえ、今の言葉に良からぬ響きを感じたもので。
308 = "いえ、今の言葉に良からぬ響きを感じたもので。"

# カズマ
# 俺は純粋に、少しでも早くお前たちに\n泳ぎを覚えてもらおうと思ってるだけだ！
440 = "俺は純粋に、少しでも早くお前たちに\\n泳ぎを覚えてもらおうと思ってるだけだ！"

# めぐみん
# なら良いんですけど……。
372 = "なら良いんですけど……。"

# カズマ（Ｍ）
# display as カズマ
# （まったく、邪なことなんて本当にこれっぽっちも\n　考えてなかったのに……）
554 = "（まったく、邪なことなんて本当にこれっぽっちも\\n　考えてなかったのに……）"

# ゆんゆん
# ええと、腕はこう動かしてください。
316 = "ええと、腕はこう動かしてください。"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆん、そんな腕を回したら胸が揺れて……）
556 = "（ゆんゆん、そんな腕を回したら胸が揺れて……）"

# クリス
# ゆんゆんは教え方が上手だね。\nこれならすぐに習得できそうだよ。
401 = "ゆんゆんは教え方が上手だね。\\nこれならすぐに習得できそうだよ。"

# カズマ（Ｍ）
# display as カズマ
# （クリスは足が綺麗だし……）
561 = "（クリスは足が綺麗だし……）"

# ダクネス
# ウィズ、準備体操をしてしまおう。
414 = "ウィズ、準備体操をしてしまおう。"

# ウィズ
# はい、わかりました。
385 = "はい、わかりました。"

# カズマ（Ｍ）
# display as カズマ
# （このふたりは、なんて暴力的な胸をしてるんだ！）
546 = "（このふたりは、なんて暴力的な胸をしてるんだ！）"

# カズマ（Ｍ）
# display as カズマ
# （ってダメだ。変なトコを見てるのがバレたら、\n　何を言われるかわかったもんじゃない）
552 = "（ってダメだ。変なトコを見てるのがバレたら、\\n　何を言われるかわかったもんじゃない）"

# カズマ（Ｍ）
# display as カズマ
# （落ち着けー。落ち着け俺。平常心だ）
564 = "（落ち着けー。落ち着け俺。平常心だ）"

# めぐみん
# カズマ、私はどうしたらいいんですか？
421 = "カズマ、私はどうしたらいいんですか？"

# カズマ
# …………。
295 = "…………。"

# めぐみん
# な、なんです、人の顔をジッと見て。
369 = "な、なんです、人の顔をジッと見て。"

# カズマ
# ふっ、俺にそっちの属性がなくて良かったよ。
389 = "ふっ、俺にそっちの属性がなくて良かったよ。"

# めぐみん
# は、はい？
381 = "は、はい？"

# カズマ
# よーし、ストップ！
403 = "よーし、ストップ！"

# ウィズ
# ぷはー！
390 = "ぷはー！"

# ダクネス
# ふぅ、水泳というのは意外に体力を使うもの\nなんだな。
387 = "ふぅ、水泳というのは意外に体力を使うもの\\nなんだな。"

# カズマ
# でも、さすがダクネス。\nまだまだ余裕そうじゃないか。
363 = "でも、さすがダクネス。\\nまだまだ余裕そうじゃないか。"

# ダクネス
# 体力は自慢のひとつだからな。
437 = "体力は自慢のひとつだからな。"

# カズマ
# ウィズはどんな手応えだ？
416 = "ウィズはどんな手応えだ？"

# ウィズ
# ちょっと苦労しそうですね。\nですが、なんとか間に合わせます。
358 = "ちょっと苦労しそうですね。\\nですが、なんとか間に合わせます。"

# カズマ
# ウィズの課題は、腕と足のばたつきだろうな。
415 = "ウィズの課題は、腕と足のばたつきだろうな。"

# ウィズ
# 自分でもわかってはいるのですが、\n顔を水につけると少し混乱してしまうんです。
539 = "自分でもわかってはいるのですが、\\n顔を水につけると少し混乱してしまうんです。"

# ウィズ
# ですがこれは慣れの問題だと思いますので、\n練習を積み重ねれば、泳げるようになると\n思いますよ。
362 = "ですがこれは慣れの問題だと思いますので、\\n練習を積み重ねれば、泳げるようになると\\n思いますよ。"

# カズマ
# そっか、安心したよ。
343 = "そっか、安心したよ。"

# カズマ
# で、問題はお前だ。
361 = "で、問題はお前だ。"

# ダクネス
# なっ、私だって上達してるだろう。
370 = "なっ、私だって上達してるだろう。"

# カズマ
# 確かにしてる。\n今日だけでバタ足をできるようになったのは\n立派なもんだ。
537 = "確かにしてる。\\n今日だけでバタ足をできるようになったのは\\n立派なもんだ。"

# ダクネス
# だったら、何が問題だと言うんだ。
355 = "だったら、何が問題だと言うんだ。"

# カズマ
# お前、苦しくなっても息継ぎしてないだろ。
325 = "お前、苦しくなっても息継ぎしてないだろ。"

# ダクネス
# へ！？
391 = "へ！？"

# カズマ
# 自分にそんなご褒美を与えるなバカ！\n何かあったらどうするつもりだ！
540 = "自分にそんなご褒美を与えるなバカ！\\n何かあったらどうするつもりだ！"

# ダクネス
# す、すまない。\n次からできるだけ気をつける。
338 = "す、すまない。\\n次からできるだけ気をつける。"

# カズマ
# はぁ、じゃあ、ちょっと休憩な。
382 = "はぁ、じゃあ、ちょっと休憩な。"

# ゆんゆん
# カズマさぁん。
422 = "カズマさぁん。"

# カズマ
# ん、どうした？
407 = "ん、どうした？"

# ゆんゆん
# クリスさんが、クリスさんが。
426 = "クリスさんが、クリスさんが。"

# カズマ
# クリスに何かあったのか！？
428 = "クリスに何かあったのか！？"

# ゆんゆん
# もう私よりも上手になっちゃいました。
398 = "もう私よりも上手になっちゃいました。"

# カズマ
# な！？
379 = "な！？"

# クリス
# ほら、ゆんゆん、まだ練習の途中だよ。
392 = "ほら、ゆんゆん、まだ練習の途中だよ。"

# ゆんゆん
# は、はい、すみません！
380 = "は、はい、すみません！"

# クリス
# ちょっと試してみたんだけどさ、\n腕はこう動かした方が、効率よく水をかけるん\nじゃないかな？
359 = "ちょっと試してみたんだけどさ、\\n腕はこう動かした方が、効率よく水をかけるん\\nじゃないかな？"

# ゆんゆん
# わかりました、試してみます！
405 = "わかりました、試してみます！"

# カズマ（Ｍ）
# display as カズマ
# （って、立場が逆転してる！）
551 = "（って、立場が逆転してる！）"

# めぐみん
# カズマ、そろそろ私にも教えてくださいよ。
420 = "カズマ、そろそろ私にも教えてくださいよ。"

# カズマ
# えー、俺も休みたいんだけど。
320 = "えー、俺も休みたいんだけど。"

# めぐみん
# だったら私に教えてからにしてください。
357 = "だったら私に教えてからにしてください。"

# カズマ
# なんでそんなにゆんゆんに教えられるのが\n嫌なんだよ。
377 = "なんでそんなにゆんゆんに教えられるのが\\n嫌なんだよ。"

# ゆんゆん
# クリスさん言ってたよ？\n私、教え方が上手だって。
427 = "クリスさん言ってたよ？\\n私、教え方が上手だって。"

# めぐみん
# それでも、嫌なものは嫌なんです！\nさあ、カズマ、早く泳げるようになるには\nどうしたらいいんですか！
345 = "それでも、嫌なものは嫌なんです！\\nさあ、カズマ、早く泳げるようになるには\\nどうしたらいいんですか！"

# カズマ
# ええとじゃあ、腕の動かし方からだ。
317 = "ええとじゃあ、腕の動かし方からだ。"

# めぐみん
# それはわかります。\nずっとみんなの泳ぎを見ていましたからね。
350 = "それはわかります。\\nずっとみんなの泳ぎを見ていましたからね。"

# めぐみん
# えっと、こうですよね？
319 = "えっと、こうですよね？"

# ゆんゆん
# あっ、違うよ。\n腕はね、こうお腹の方へ持っていくの。
304 = "あっ、違うよ。\\n腕はね、こうお腹の方へ持っていくの。"

# めぐみん
# あなたには聞いていません。
306 = "あなたには聞いていません。"

# ゆんゆん
# うぅ……。
311 = "うぅ……。"

# めぐみん
# さあ、カズマ。\n何が悪いのか教えてください。
332 = "さあ、カズマ。\\n何が悪いのか教えてください。"

# カズマ
# はぁ、ゆんゆんの指摘通りだよ。
383 = "はぁ、ゆんゆんの指摘通りだよ。"

# カズマ
# 腕はこうお腹の方からかいて、\n後ろから抜く！
538 = "腕はこうお腹の方からかいて、\\n後ろから抜く！"

# ゆんゆん
# あ……。
296 = "あ……。"

# カズマ
# え？
321 = "え？"

# めぐみん
# イラっ！
412 = "イラっ！"

# カズマ（Ｍ）
# display as カズマ
# （ん？　なんだこれ？）
558 = "（ん？　なんだこれ？）"

# ゆんゆん
# あ、え、へ？
297 = "あ、え、へ？"

# カズマ（Ｍ）
# display as カズマ
# （この感触、タコ的な何かか？）
547 = "（この感触、タコ的な何かか？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、それにしてはハリがありすぎるような）
544 = "（いや、それにしてはハリがありすぎるような）"

# ゆんゆん
# あああ、あ、あの、カズマさん。\nどど、どうして、胸を。
300 = "あああ、あ、あの、カズマさん。\\nどど、どうして、胸を。"

# カズマ
# え？　むね？
322 = "え？　むね？"

# ゆんゆん
# ふえ、ふええ、めぐみーん。
388 = "ふえ、ふええ、めぐみーん。"

# カズマ
# いや、違うんだこれは！\nわざとじゃなくて――
309 = "いや、違うんだこれは！\\nわざとじゃなくて――"

# めぐみん
# わざとじゃないなら、\nさっさと手を離したらどうなんですか！
406 = "わざとじゃないなら、\\nさっさと手を離したらどうなんですか！"

# カズマ
# ぐはっ！！
330 = "ぐはっ！！"

