# st03b_12.txt.scn

[info]
0 = ""

[characters]
292 = "カズマ（Ｍ）"
279 = "ゆんゆん"
287 = "ウィズ"
289 = "カズマ"
276 = "めぐみん"
293 = "クリス"
295 = "ダクネス"
282 = "アクア"

[character_subs]
# 289 = "カズマ"

[script]
# lines: 89

# カズマ（Ｍ）
# display as カズマ
# （なんだかんだで、夜も更けてきたな）
366 = "（なんだかんだで、夜も更けてきたな）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、これで準備もだいぶ進んだ。\n　今やれることは、最大限やったつもりだ）
365 = "（しかし、これで準備もだいぶ進んだ。\\n　今やれることは、最大限やったつもりだ）"

# ゆんゆん
# ふぅ、さっぱりしました。
272 = "ふぅ、さっぱりしました。"

# ウィズ
# あっ、カズマさん。\n先にお風呂をいただいちゃってすみません。
229 = "あっ、カズマさん。\\n先にお風呂をいただいちゃってすみません。"

# カズマ
# よし、全員出たな。
281 = "よし、全員出たな。"

# めぐみん
# まさか、これからまた何かの特訓を\nするつもりじゃないでしょうね。
274 = "まさか、これからまた何かの特訓を\\nするつもりじゃないでしょうね。"

# カズマ
# いや、もう特訓は終了だ。\nみんな、ゆっくり休んでくれ。
235 = "いや、もう特訓は終了だ。\\nみんな、ゆっくり休んでくれ。"

# クリス
# はぁぁ、そうしてくれると助かるよ。
269 = "はぁぁ、そうしてくれると助かるよ。"

# ダクネス
# さすがに精神が疲弊してきたからな。
246 = "さすがに精神が疲弊してきたからな。"

# ゆんゆん
# あ、今日はめぐみんの部屋に\n泊まらせてもらっていい？
226 = "あ、今日はめぐみんの部屋に\\n泊まらせてもらっていい？"

# めぐみん
# いいですけど、宿泊料取りますよ。
234 = "いいですけど、宿泊料取りますよ。"

# ゆんゆん
# えーっ！！
244 = "えーっ！！"

# ウィズ
# ええと、私は……。
242 = "ええと、私は……。"

# ダクネス
# クリスとウィズは、私の部屋で寝るといい。
294 = "クリスとウィズは、私の部屋で寝るといい。"

# クリス
# うん、助かるよ、ダクネス。
239 = "うん、助かるよ、ダクネス。"

# カズマ（Ｍ）
# display as カズマ
# （ふふ、今まで苦難を共にしてきた仲間だから、\n　ちょっとは連帯感も出てきたかな）
368 = "（ふふ、今まで苦難を共にしてきた仲間だから、\\n　ちょっとは連帯感も出てきたかな）"

# カズマ（Ｍ）
# display as カズマ
# （俺も、頑張ってみんなをプロデュースして、\n　トップアイドルにしてやらねーとな）
370 = "（俺も、頑張ってみんなをプロデュースして、\\n　トップアイドルにしてやらねーとな）"

# アクア
# あーーーーーーっ！！
232 = "あーーーーーーっ！！"

# カズマ
# ど、どうした、アクア！
262 = "ど、どうした、アクア！"

# アクア
# ねぇ、大切な事決めてないんじゃない！
267 = "ねぇ、大切な事決めてないんじゃない！"

# カズマ
# えっ、なんかあったっけ？
243 = "えっ、なんかあったっけ？"

# アクア
# もうっ！　名前よ名前！\n私たちのアイドルユニットの名前！
277 = "もうっ！　名前よ名前！\\n私たちのアイドルユニットの名前！"

# カズマ
# あ、そっか、すっかり忘れてた。
225 = "あ、そっか、すっかり忘れてた。"

# カズマ（Ｍ）
# display as カズマ
# （お客さんに認知して貰うには、\n　ユニット名を覚えて貰う必要があったぜ）
362 = "（お客さんに認知して貰うには、\\n　ユニット名を覚えて貰う必要があったぜ）"

# めぐみん
# あの、もしかしてまだ寝られません？
230 = "あの、もしかしてまだ寝られません？"

# カズマ
# そうだな。\nユニット名は決めちまおうぜ。
250 = "そうだな。\\nユニット名は決めちまおうぜ。"

# ダクネス
# そういうのは意外に難しいと思うのだが。
249 = "そういうのは意外に難しいと思うのだが。"

# アクア
# ねえねえ、カズマ。\nアクアと愉快な信者たちっていうのはどうかしら！
268 = "ねえねえ、カズマ。\\nアクアと愉快な信者たちっていうのはどうかしら！"

# カズマ
# 却下だ。
298 = "却下だ。"

# めぐみん
# 超覇権アイドル！　やがてこの世を支配する者！
358 = "超覇権アイドル！　やがてこの世を支配する者！"

# カズマ
# なんでサブタイトルみたいのがついてるんだよ。
266 = "なんでサブタイトルみたいのがついてるんだよ。"

# アクア
# アクアと楽しい仲間たち！
285 = "アクアと楽しい仲間たち！"

# カズマ
# 愉快を楽しいにしただけだよな、それ！
310 = "愉快を楽しいにしただけだよな、それ！"

# めぐみん
# 存在証明の残響！
306 = "存在証明の残響！"

# カズマ
# うん、なんか格好いいだけで意味がわからない。
238 = "うん、なんか格好いいだけで意味がわからない。"

# アクア
# アクアと――
284 = "アクアと――"

# カズマ
# そろそろ殴るぞ、お前！
258 = "そろそろ殴るぞ、お前！"

# アクア
# 文句ばっかりでなんなのよ。\nじゃあ、あんたも何か案を出しなさいったら。
311 = "文句ばっかりでなんなのよ。\\nじゃあ、あんたも何か案を出しなさいったら。"

# カズマ
# うーん、そうだな。
240 = "うーん、そうだな。"

# カズマ（Ｍ）
# display as カズマ
# （ユニット名、ユニット名。\n　意外に難しいもんだな）
369 = "（ユニット名、ユニット名。\\n　意外に難しいもんだな）"

# アクア
# あら、カズマさん、文句を言うだけで、\n案一つ出せないんですか？
231 = "あら、カズマさん、文句を言うだけで、\\n案一つ出せないんですか？"

# カズマ（Ｍ）
# display as カズマ
# （くっ、こいつ、\n　自分はバカでも出せるような案しか\n　出してないくせに！）
363 = "（くっ、こいつ、\\n　自分はバカでも出せるような案しか\\n　出してないくせに！）"

# アクア
# ほらほら、早く。\nもうみんな疲れて眠いんだから。
273 = "ほらほら、早く。\\nもうみんな疲れて眠いんだから。"

# カズマ
# カ、カズマと……。
288 = "カ、カズマと……。"

# アクア
# カズマと？
291 = "カズマと？"

# カズマ
# 愉快な仲間たち……。
309 = "愉快な仲間たち……。"

# めぐみん
# よくもまあ、恥ずかしげもなく言えましたね。
280 = "よくもまあ、恥ずかしげもなく言えましたね。"

# カズマ
# だってしょうがないだろ！\nいい案が浮かばなかったんだから！
259 = "だってしょうがないだろ！\\nいい案が浮かばなかったんだから！"

# カズマ
# じゃ、じゃあ、『アクセルエンジェルズ！』\nこれでどうだ！
247 = "じゃ、じゃあ、『アクセルエンジェルズ！』\\nこれでどうだ！"

# ダクネス
# なんだか強そうな名前だな。\n私は好きだぞ。
265 = "なんだか強そうな名前だな。\\n私は好きだぞ。"

# カズマ
# ああ、それに地元の名前を入れておけば、\n街のみんなも応援しやすいし、バッチリだろ？
227 = "ああ、それに地元の名前を入れておけば、\\n街のみんなも応援しやすいし、バッチリだろ？"

# ゆんゆん
# それに、可愛くてとてもいいと思います。
256 = "それに、可愛くてとてもいいと思います。"

# めぐみん
# 頭に、爆裂っ！　は付きませんか？\n爆裂っ！　アクセルエンジェルズ！
360 = "頭に、爆裂っ！　は付きませんか？\\n爆裂っ！　アクセルエンジェルズ！"

# ダクネス
# それならば、\n守護者アクセルエンジェルズ！\nというのもいいんじゃないか！
255 = "それならば、\\n守護者アクセルエンジェルズ！\\nというのもいいんじゃないか！"

# クリス
# 解決っ！　アクセルエンジェルズ！　も\nいいと思わない？
357 = "解決っ！　アクセルエンジェルズ！　も\\nいいと思わない？"

# アクア
# 女神っ！　アクセルエンジェルズ！\nで決まりよ！
305 = "女神っ！　アクセルエンジェルズ！\\nで決まりよ！"

# めぐみん
# それでは、女神と天使がケンカして、\nよくわからなくなってしまいますよ？
254 = "それでは、女神と天使がケンカして、\\nよくわからなくなってしまいますよ？"

# アクア
# いいじゃないそれくらい。\nなんだったら、華麗な女神とアクセルエンジェルズ！\nでもいいわよ？
233 = "いいじゃないそれくらい。\\nなんだったら、華麗な女神とアクセルエンジェルズ！\\nでもいいわよ？"

# カズマ
# だーーーっ！！　お前ら勝手に頭に付けて\n変なタイトルもどきにするな！\nこれはアニメじゃねぇんだよ！
260 = "だーーーっ！！　お前ら勝手に頭に付けて\\n変なタイトルもどきにするな！\\nこれはアニメじゃねぇんだよ！"

# カズマ
# 『名前はまだない』だな。
224 = "『名前はまだない』だな。"

# アクア
# は？　思いつかないってこと？
270 = "は？　思いつかないってこと？"

# カズマ
# 違うって、あえて名前が無いっていう\nユニット名にするの。
359 = "違うって、あえて名前が無いっていう\\nユニット名にするの。"

# クリス
# 変わってるけど、斬新かもね。
303 = "変わってるけど、斬新かもね。"

# カズマ
# 最初は名前のないアイドル達だか、\n徐々にみんなに応援されはじめ、\n個性も伸びてきた頃に相応しい名前にするんだ。
312 = "最初は名前のないアイドル達だか、\\n徐々にみんなに応援されはじめ、\\n個性も伸びてきた頃に相応しい名前にするんだ。"

# めぐみん
# それまで、名無しなんですか。
257 = "それまで、名無しなんですか。"

# カズマ
# いやだから、「名前はまだない」だ。
236 = "いやだから、「名前はまだない」だ。"

# アクア
# ややこしいわね。
278 = "ややこしいわね。"

# ウィズ
# と言うことは、名乗る時は\n名前はまだないのウィズですと\n言えばいいのでしょうか？
261 = "と言うことは、名乗る時は\\n名前はまだないのウィズですと\\n言えばいいのでしょうか？"

# カズマ
# ああ、そんな感じだな。
228 = "ああ、そんな感じだな。"

# ダクネス
# 名前が決まるまで、ちょっと落ち着かないな。
301 = "名前が決まるまで、ちょっと落ち着かないな。"

# アクア
# うーん、ピンとこないわね。
241 = "うーん、ピンとこないわね。"

# ダクネス
# なあ、カズマ。\n無理に今決めなくてもいいんじゃないか？
263 = "なあ、カズマ。\\n無理に今決めなくてもいいんじゃないか？"

# ウィズ
# みなさん疲れて、考えが上手くまとまらない\nでしょうしね。
275 = "みなさん疲れて、考えが上手くまとまらない\\nでしょうしね。"

# カズマ（Ｍ）
# display as カズマ
# （確かにそうだな）
371 = "（確かにそうだな）"

# カズマ
# じゃあみんな、ユニット案を明日の朝までに\n考えておいてくれ。
248 = "じゃあみんな、ユニット案を明日の朝までに\\n考えておいてくれ。"

# カズマ
# その中から話し合って決めよう。
252 = "その中から話し合って決めよう。"

# めぐみん
# ふぁぁぁ、ようやく眠れます。
271 = "ふぁぁぁ、ようやく眠れます。"

# ゆんゆん
# 私もう、目を開けてられないよ。
356 = "私もう、目を開けてられないよ。"

# ダクネス
# それじゃあ、おやすみ、カズマ。
253 = "それじゃあ、おやすみ、カズマ。"

# ウィズ
# おやすみなさい、カズマさん。
245 = "おやすみなさい、カズマさん。"

# クリス
# 夜這いはダメだからね？
304 = "夜這いはダメだからね？"

# カズマ
# そそそ、そんなことしねーから！
251 = "そそそ、そんなことしねーから！"

# カズマ（Ｍ）
# display as カズマ
# （さて、俺も風呂に……）
364 = "（さて、俺も風呂に……）"

# アクア
# ううーん。
237 = "ううーん。"

# カズマ
# なんだ、お前はまだ寝ないのか？
264 = "なんだ、お前はまだ寝ないのか？"

# アクア
# ユニット名を考えようかなって思ったのよ！
296 = "ユニット名を考えようかなって思ったのよ！"

# カズマ（Ｍ）
# display as カズマ
# （ああ、センターアピールね）
361 = "（ああ、センターアピールね）"

# アクア
# アクア、アクシズ、水の女神……。\nうーん、難しいわね。
283 = "アクア、アクシズ、水の女神……。\\nうーん、難しいわね。"

# カズマ（Ｍ）
# display as カズマ
# （ふぁぁぁ、俺も風呂から出たら寝よう）
367 = "（ふぁぁぁ、俺も風呂から出たら寝よう）"

[selections]
290 = "カズマと……"
286 = "アクセルエンジェルズ"
302 = "名前はまだない"
