# st03b_06.txt.scn

[info]
0 = ""

[characters]
216 = "カズマ（Ｍ）"
214 = "カズマ"
212 = "アクア"
213 = "ウィズ"
210 = "ゆんゆん"
208 = "めぐみん"
218 = "ダクネス"
217 = "クリス"

[character_subs]
# 214 = "カズマ"

[script]
# lines: 55

# カズマ（Ｍ）
# display as カズマ
# （そんなこんなで、レッスン２日目）
269 = "（そんなこんなで、レッスン２日目）"

# カズマ
# 遅いぞこらーー！　ダッシュダッシュー！！
267 = "遅いぞこらーー！　ダッシュダッシュー！！"

# アクア
# はぁはぁはぁはぁ……ひぃひぃふぅ、はひぃ。
203 = "はぁはぁはぁはぁ……ひぃひぃふぅ、はひぃ。"

# ウィズ
# はぁ、ひぃ、ふぅ……わ、私、もう限界です。
201 = "はぁ、ひぃ、ふぅ……わ、私、もう限界です。"

# カズマ
# まだ始めたばかりなのに、何を言ってるんだよ。
206 = "まだ始めたばかりなのに、何を言ってるんだよ。"

# カズマ
# こんな事で根を上げてたら、\n厳しいアイドルの世界では生きていけないぞ！
186 = "こんな事で根を上げてたら、\\n厳しいアイドルの世界では生きていけないぞ！"

# カズマ
# 全員が完走出来なかった場合、連帯責任として\nみんなで腕立て伏せ２０回だからな！
223 = "全員が完走出来なかった場合、連帯責任として\\nみんなで腕立て伏せ２０回だからな！"

# アクア
# ええ～～～！？
177 = "ええ～～～！？"

# カズマ（Ｍ）
# display as カズマ
# （みんなの体力不足を感じた俺は、アイドルの\n　レッスンとは別に、基礎体力をつけさせる為に\n　ランニングをさせていた）
272 = "（みんなの体力不足を感じた俺は、アイドルの\\n　レッスンとは別に、基礎体力をつけさせる為に\\n　ランニングをさせていた）"

# カズマ
# こらー、紅魔族コンビ、歩くな！
183 = "こらー、紅魔族コンビ、歩くな！"

# ゆんゆん
# は、は、はい～。
200 = "は、は、はい～。"

# めぐみん
# わ、わかっていますが、息がぁ。
211 = "わ、わかっていますが、息がぁ。"

# カズマ
# こらっ、アクアどこにいくつもりだ！
182 = "こらっ、アクアどこにいくつもりだ！"

# アクア
# 無理、もう無理、吐くぅ。\n誰か、はぅ、背中、あぅ、さすっ、さすってぇ。
231 = "無理、もう無理、吐くぅ。\\n誰か、はぅ、背中、あぅ、さすっ、さすってぇ。"

# ダクネス
# お、おい、大丈夫か？
180 = "お、おい、大丈夫か？"

# カズマ
# 前の大会の時に思ったけど、\nこいつら体力はからっきしだな。
224 = "前の大会の時に思ったけど、\\nこいつら体力はからっきしだな。"

# クリス
# 魔法職と支援職に体力を求めるのは\n酷というものだよ。
268 = "魔法職と支援職に体力を求めるのは\\n酷というものだよ。"

# カズマ
# それはわかってるけど。\nこんな体力じゃ１曲踊って終わりだぞ。
191 = "それはわかってるけど。\\nこんな体力じゃ１曲踊って終わりだぞ。"

# ゆんゆん
# はぁはぁ……アイドルってこんなに辛いものなの？
202 = "はぁはぁ……アイドルってこんなに辛いものなの？"

# めぐみん
# それはわかりませんが、\nカズマが調子に乗っていることだけは確かです。
192 = "それはわかりませんが、\\nカズマが調子に乗っていることだけは確かです。"

# カズマ
# いいか！\nアイドルに必要な物は、１に体力、２に笑顔！\n３、４が無くて、５にルックスだ！！
175 = "いいか！\\nアイドルに必要な物は、１に体力、２に笑顔！\\n３、４が無くて、５にルックスだ！！"

# カズマ
# まずは、何事においても体力が必要なんだ！\n四の五の言わずに走れーー！！
205 = "まずは、何事においても体力が必要なんだ！\\n四の五の言わずに走れーー！！"

# アクア
# 自分こそ走んなさいよね、\n最弱職のあんたこそ体力が必要よ！
266 = "自分こそ走んなさいよね、\\n最弱職のあんたこそ体力が必要よ！"

# カズマ
# 今はプロデューサーだから良いんだ！\nアクアは、もう１周追加！！
220 = "今はプロデューサーだから良いんだ！\\nアクアは、もう１周追加！！"

# アクア
# もぉぉぉっ！　こんな苦しい思いまでして、\nアイドルなんてやってられないわ！
209 = "もぉぉぉっ！　こんな苦しい思いまでして、\\nアイドルなんてやってられないわ！"

# カズマ
# おっ、おい落ち着けって。\n俺はみんなのことを思って言ってるだけで。
181 = "おっ、おい落ち着けって。\\n俺はみんなのことを思って言ってるだけで。"

# カズマ
# それに、こうやってみんなで励まし合いながら\n走ってたら、連帯感や絆も生まれるだろ？
190 = "それに、こうやってみんなで励まし合いながら\\n走ってたら、連帯感や絆も生まれるだろ？"

# アクア
# だったら、あんたも仲間なんだし、\n一緒に走りなさいよ！
195 = "だったら、あんたも仲間なんだし、\\n一緒に走りなさいよ！"

# めぐみん
# そうですよ！　１人だけ高いところから偉そうに\n命令しているだけなんて感じ悪いです。
188 = "そうですよ！　１人だけ高いところから偉そうに\\n命令しているだけなんて感じ悪いです。"

# ゆんゆん
# こんなに辛いなら、もうついていけません！
185 = "こんなに辛いなら、もうついていけません！"

# めぐみん
# ただでさえ、大変なんですから私たちは！
194 = "ただでさえ、大変なんですから私たちは！"

# ダクネス
# まぁまぁ、\n確かにカズマはやり過ぎたところもあるが、\nみんなのことを思って言っていることもある。
204 = "まぁまぁ、\\n確かにカズマはやり過ぎたところもあるが、\\nみんなのことを思って言っていることもある。"

# クリス
# 体力がある子、無い子をちゃんと見極めて\n走らせた方がいのかもね。
221 = "体力がある子、無い子をちゃんと見極めて\\n走らせた方がいのかもね。"

# ウィズ
# カズマさん、流石に厳しすぎたのでは\nないでしょうか？
215 = "カズマさん、流石に厳しすぎたのでは\\nないでしょうか？"

# カズマ
# うっ……確かに、\nちょっとやり過ぎてたのかもしれない。
176 = "うっ……確かに、\\nちょっとやり過ぎてたのかもしれない。"

# カズマ
# 俺はなんだか焦っていたみたいだ。\nみんな、すまなかった。
222 = "俺はなんだか焦っていたみたいだ。\\nみんな、すまなかった。"

# アクア
# 本当に反省しているの？
229 = "本当に反省しているの？"

# カズマ
# これからは、方針を変えて個人の能力に合わせて、\n無理のないトレーニングを考えるからさ。
184 = "これからは、方針を変えて個人の能力に合わせて、\\n無理のないトレーニングを考えるからさ。"

# めぐみん
# むぅぅぅ……。
207 = "むぅぅぅ……。"

# ゆんゆん
# …………。
171 = "…………。"

# カズマ
# な、なんだ？　そ、それでも不服なのか？
199 = "な、なんだ？　そ、それでも不服なのか？"

# カズマ
# でも、２人とも体力が不足しているから、\nその弱点を今のうちに克服しておきたいんだ。
197 = "でも、２人とも体力が不足しているから、\\nその弱点を今のうちに克服しておきたいんだ。"

# めぐみん
# そ、それはわかりますが。
187 = "そ、それはわかりますが。"

# ゆんゆん
# ……うん。
172 = "……うん。"

# カズマ（Ｍ）
# display as カズマ
# （なんだ？　まだ何か不満でもあるのか？）
270 = "（なんだ？　まだ何か不満でもあるのか？）"

# ウィズ
# あの、先ほどからモジモジされてますが、\nもしかして……。
174 = "あの、先ほどからモジモジされてますが、\\nもしかして……。"

# カズマ
# あ、トイレに行きたかったのか？
173 = "あ、トイレに行きたかったのか？"

# めぐみん
# ちち、違いますよ！！　前にも言ったはずですよ、\n紅魔族はトイレに行かないって！
196 = "ちち、違いますよ！！　前にも言ったはずですよ、\\n紅魔族はトイレに行かないって！"

# ゆんゆん
# えっ、そ、そうなの？
178 = "えっ、そ、そうなの？"

# めぐみん
# そこは話を合わせてください。\nまったく、本当に使えない子ですね。
189 = "そこは話を合わせてください。\\nまったく、本当に使えない子ですね。"

# ゆんゆん
# えーっ、その言い方酷いよめぐみん！
179 = "えーっ、その言い方酷いよめぐみん！"

# めぐみん
# そんなだから、友達もいないんですよ？\nもっと機転を利かせてください。
193 = "そんなだから、友達もいないんですよ？\\nもっと機転を利かせてください。"

# ゆんゆん
# と、友達ぐらいいるよー！\n馬鹿にしないで！！
198 = "と、友達ぐらいいるよー！\\n馬鹿にしないで！！"

# カズマ（Ｍ）
# display as カズマ
# （みんなの言うとおり、\n　このトレーニングは厳しすぎたかもしれない）
273 = "（みんなの言うとおり、\\n　このトレーニングは厳しすぎたかもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （みんなにも出来そうな、\n　何か別のトレーニングを考えなきゃな……）
271 = "（みんなにも出来そうな、\\n　何か別のトレーニングを考えなきゃな……）"

