# st03c_02.txt.scn

[info]
0 = ""

[characters]
232 = "アクア"
235 = "カズマ（Ｍ）"
237 = "ダクネス"
226 = "めぐみん"
234 = "カズマ"
233 = "ウィズ"
236 = "クリス"
228 = "ゆんゆん"

[character_subs]
# 234 = "カズマ"

[script]
# lines: 74

# アクア
# いえーい、みんな盛り上がってるー！
199 = "いえーい、みんな盛り上がってるー！"

# カズマ（Ｍ）
# display as カズマ
# （こうしてシャイニーブルーのステージは\n　始まった！）
311 = "（こうしてシャイニーブルーのステージは\\n　始まった！）"

# ダクネス
# 短い時間のライブだが、\nみんな楽しんでいってくれ。
305 = "短い時間のライブだが、\\nみんな楽しんでいってくれ。"

# めぐみん
# ふっ、私という闇に抱かれ、\nもだえ苦しむがいいです！
218 = "ふっ、私という闇に抱かれ、\\nもだえ苦しむがいいです！"

# カズマ（Ｍ）
# display as カズマ
# （やはり最初のステージということもあり、\n　失敗が多く見られた）
322 = "（やはり最初のステージということもあり、\\n　失敗が多く見られた）"

# カズマ（Ｍ）
# display as カズマ
# （でも、あいつらはそれを少しも気にしてないよう\n　だった）
316 = "（でも、あいつらはそれを少しも気にしてないよう\\n　だった）"

# カズマ（Ｍ）
# display as カズマ
# （ただ、今、目の前のステージを楽しむことだけに\n　没頭し、そしてシャイニーブルーという輝きで\n　客たちを照らし続けたのだ）
315 = "（ただ、今、目の前のステージを楽しむことだけに\\n　没頭し、そしてシャイニーブルーという輝きで\\n　客たちを照らし続けたのだ）"

# カズマ（Ｍ）
# display as カズマ
# （楽しい時間というのは、\n　どうしてこうも早く過ぎてしまうのだろう）
333 = "（楽しい時間というのは、\\n　どうしてこうも早く過ぎてしまうのだろう）"

# カズマ（Ｍ）
# display as カズマ
# （楽しい時間は永遠に続けばいいのに）
334 = "（楽しい時間は永遠に続けばいいのに）"

# カズマ（Ｍ）
# display as カズマ
# （頬を紅潮させ、息を切らせながら\n　観客に手を振るあいつらも\n　きっとそう思っていたに違いない）
338 = "（頬を紅潮させ、息を切らせながら\\n　観客に手を振るあいつらも\\n　きっとそう思っていたに違いない）"

# カズマ
# みんな！　とってもよかったぞ！！
225 = "みんな！　とってもよかったぞ！！"

# カズマ
# やっぱり、俺の目に狂いはなかった。\nお前ら最高だ！！
227 = "やっぱり、俺の目に狂いはなかった。\\nお前ら最高だ！！"

# アクア
# はぁはぁ、あったり前じゃない！
214 = "はぁはぁ、あったり前じゃない！"

# ダクネス
# ああっ……。\nこのステージは、癖になってしまいそうだ。
198 = "ああっ……。\\nこのステージは、癖になってしまいそうだ。"

# ウィズ
# し、失敗しなくて良かったです。
207 = "し、失敗しなくて良かったです。"

# クリス
# なんだか、あっという間だったね。
213 = "なんだか、あっという間だったね。"

# ゆんゆん
# よかったぁぁ……終わったよめぐみんー。
229 = "よかったぁぁ……終わったよめぐみんー。"

# めぐみん
# な、なんとか、乗り切れましたね。\n爆裂魔法は撃てませんでしたが。
212 = "な、なんとか、乗り切れましたね。\\n爆裂魔法は撃てませんでしたが。"

# カズマ
# 客の顔は見たか！\nみんな、満足そうな笑顔をしてたぞ。
246 = "客の顔は見たか！\\nみんな、満足そうな笑顔をしてたぞ。"

# カズマ
# しかし、まだこれで終わりじゃないぞ。\nすぐこの後に、握手会が控えている。
208 = "しかし、まだこれで終わりじゃないぞ。\\nすぐこの後に、握手会が控えている。"

# ゆんゆん
# こ、このあと、すぐにですか！？
205 = "こ、このあと、すぐにですか！？"

# カズマ
# 今日掴んだファンを、これからも応援してくれる\n心強い味方にする為に頑張ってくれ！！
242 = "今日掴んだファンを、これからも応援してくれる\\n心強い味方にする為に頑張ってくれ！！"

# ダクネス
# みんな、やろう！
223 = "みんな、やろう！"

# クリス
# そうだね、\nファンの皆さんが喜んでくれるんだったら。
210 = "そうだね、\\nファンの皆さんが喜んでくれるんだったら。"

# ウィズ
# わ、私も頑張ります！
230 = "わ、私も頑張ります！"

# カズマ
# ほら、アクアもいくぞ。
221 = "ほら、アクアもいくぞ。"

# アクア
# 私、さっきのステージで\n全てを出し切っちゃったんですけど。
306 = "私、さっきのステージで\\n全てを出し切っちゃったんですけど。"

# カズマ
# ほら、頑張れ。\nお前はこのユニットのなんだ。
222 = "ほら、頑張れ。\\nお前はこのユニットのなんだ。"

# アクア
# うぅ、センター。
201 = "うぅ、センター。"

# カズマ
# わかってるならよし！\nみんな、自分のキャラを忘れるな？
231 = "わかってるならよし！\\nみんな、自分のキャラを忘れるな？"

# カズマ（Ｍ）
# display as カズマ
# （おおっ、凄い行列が出来ているな）
310 = "（おおっ、凄い行列が出来ているな）"

# カズマ（Ｍ）
# display as カズマ
# （アイドルと握手出来るんだもんな。\n　その文化を知らないこの世界の住人に\n　とっちゃ凄いことなんだろう）
327 = "（アイドルと握手出来るんだもんな。\\n　その文化を知らないこの世界の住人に\\n　とっちゃ凄いことなんだろう）"

# アクア
# 応援ありがとうございまーす！\nまた来てくださいね？
249 = "応援ありがとうございまーす！\\nまた来てくださいね？"

# カズマ（Ｍ）
# display as カズマ
# （流石、人なつっこいアクアは上手にファンと\n　交流しているよな）
335 = "（流石、人なつっこいアクアは上手にファンと\\n　交流しているよな）"

# めぐみん
# フッ、この私に触れた者がどうなるか\nわかっているのか？ それでもいいなら、\n触ってみるがよい。あ、手です……手。
238 = "フッ、この私に触れた者がどうなるか\\nわかっているのか？ それでもいいなら、\\n触ってみるがよい。あ、手です……手。"

# カズマ（Ｍ）
# display as カズマ
# （やはり、ロリっ子厨二病は強い。\n　凄い人気だ）
321 = "（やはり、ロリっ子厨二病は強い。\\n　凄い人気だ）"

# カズマ（Ｍ）
# display as カズマ
# （もっとのびのびやってくれても良いんだけど、\n　なんかモジモジしているのが無くならないのが\n　残念だ）
320 = "（もっとのびのびやってくれても良いんだけど、\\n　なんかモジモジしているのが無くならないのが\\n　残念だ）"

# ダクネス
# 応援感謝する、これからも頼むぞ。
250 = "応援感謝する、これからも頼むぞ。"

# ダクネス
# みんなの応援は、私の力になるだろう。
224 = "みんなの応援は、私の力になるだろう。"

# カズマ（Ｍ）
# display as カズマ
# （こっちは、客層ががらっと変わったな。\n　女の子も結構多いし、クール系はいいチョイス\n　だったのかもしれない）
312 = "（こっちは、客層ががらっと変わったな。\\n　女の子も結構多いし、クール系はいいチョイス\\n　だったのかもしれない）"

# クリス
# はいはい、これでいい？\nはい、次ー。
216 = "はいはい、これでいい？\\nはい、次ー。"

# カズマ（Ｍ）
# display as カズマ
# （塩対応でも嫌われないって、結構才能がいるし\n　クリスは適任だったのかもな）
331 = "（塩対応でも嫌われないって、結構才能がいるし\\n　クリスは適任だったのかもな）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、このジャンルは奥が深いぜ）
313 = "（しかし、このジャンルは奥が深いぜ）"

# ゆんゆん
# おねえちゃん、恥ずかしいよぉ。
202 = "おねえちゃん、恥ずかしいよぉ。"

# ウィズ
# ふふふ、大丈夫よっ、ほらっ、良い子良い子。\n一緒にファンの人に、ありがとうって\n言いましょうね。
219 = "ふふふ、大丈夫よっ、ほらっ、良い子良い子。\\n一緒にファンの人に、ありがとうって\\n言いましょうね。"

# カズマ（Ｍ）
# display as カズマ
# （おお、ここは姉妹設定を活かしての\n　２人同時握手！）
309 = "（おお、ここは姉妹設定を活かしての\\n　２人同時握手！）"

# カズマ（Ｍ）
# display as カズマ
# （とっさにアドリブで対処するなんて、\n　さすがウィズ）
317 = "（とっさにアドリブで対処するなんて、\\n　さすがウィズ）"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんの守ってあげたくなるキャラは、\n　本当にファンの保護欲をかき立てるぜ）
323 = "（ゆんゆんの守ってあげたくなるキャラは、\\n　本当にファンの保護欲をかき立てるぜ）"

# カズマ（Ｍ）
# display as カズマ
# （よし、みんなそれぞれのキャラを押し出して、\n　ファンを掴んでいるみたいだな）
325 = "（よし、みんなそれぞれのキャラを押し出して、\\n　ファンを掴んでいるみたいだな）"

# カズマ（Ｍ）
# display as カズマ
# （あ、そういや、普段のみんなを知る人たちは、\n　違った性格のキャラでアイドルしているのを\n　どんな思いで見てるんだろう？）
307 = "（あ、そういや、普段のみんなを知る人たちは、\\n　違った性格のキャラでアイドルしているのを\\n　どんな思いで見てるんだろう？）"

# カズマ（Ｍ）
# display as カズマ
# （芝居やミュージカルの登場人物に\n　なりきっているって感じで見ているのかな？）
336 = "（芝居やミュージカルの登場人物に\\n　なりきっているって感じで見ているのかな？）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、不評ではないみたいだし、\n　これからも上手くやっていけそうだ！）
314 = "（しかし、不評ではないみたいだし、\\n　これからも上手くやっていけそうだ！）"

# ゆんゆん
# きゃ、あ、あの、そろそろ手を。
204 = "きゃ、あ、あの、そろそろ手を。"

# カズマ（Ｍ）
# display as カズマ
# （ん？　トラブルか？）
326 = "（ん？　トラブルか？）"

# カズマ
# はいはい、そこのお客さん。\nアイドルを独り占めしちゃダメですよ？
217 = "はいはい、そこのお客さん。\\nアイドルを独り占めしちゃダメですよ？"

# カズマ
# きちんとルールを守って、握手しましょうね。
203 = "きちんとルールを守って、握手しましょうね。"

# ゆんゆん
# あ、すみません、プロデューサーさん。
196 = "あ、すみません、プロデューサーさん。"

# カズマ
# いやいや、がんばれ、ゆんゆん。
200 = "いやいや、がんばれ、ゆんゆん。"

# ゆんゆん
# はいっ！
215 = "はいっ！"

# カズマ（Ｍ）
# display as カズマ
# （ククク、人前でプロデューサーと呼ばれるのも\n　気持ちいいな！）
328 = "（ククク、人前でプロデューサーと呼ばれるのも\\n　気持ちいいな！）"

# カズマ（Ｍ）
# display as カズマ
# （よし、これからは、人前では絶対プロデューサーと\n　呼ぶようにしておこう）
324 = "（よし、これからは、人前では絶対プロデューサーと\\n　呼ぶようにしておこう）"

# アクア
# あ、カズマ！
197 = "あ、カズマ！"

# カズマ
# こら、プロデューサーと呼べ！
206 = "こら、プロデューサーと呼べ！"

# アクア
# あ、うん、プロデューサー。
195 = "あ、うん、プロデューサー。"

# アクア
# どう、このアクア信者の数！\nこの女神アクア様と握手したくて、\n押し寄せて来てるわ。
211 = "どう、このアクア信者の数！\\nこの女神アクア様と握手したくて、\\n押し寄せて来てるわ。"

# カズマ
# そうだな、みんなアイドルと握手したいからな。
209 = "そうだな、みんなアイドルと握手したいからな。"

# アクア
# ふふふっ、やっぱりそうよね？\nじゃんじゃん握手して信者をもっと増やすわよー！
220 = "ふふふっ、やっぱりそうよね？\\nじゃんじゃん握手して信者をもっと増やすわよー！"

# カズマ（Ｍ）
# display as カズマ
# （ファンを信者とか言ってるが、\n　これはキャラ付けの応用なんだよな？）
329 = "（ファンを信者とか言ってるが、\\n　これはキャラ付けの応用なんだよな？）"

# カズマ（Ｍ）
# display as カズマ
# （ふふ、そういや、以前握手会の練習を\n　ギルドのたまり場でやっておいて正解だったな）
319 = "（ふふ、そういや、以前握手会の練習を\\n　ギルドのたまり場でやっておいて正解だったな）"

# カズマ（Ｍ）
# display as カズマ
# （あの時、キースとダストだけで、\n　他の人には絶対に握手をさせなかったから、\n　今日は握手したいってヤツが結構来ている）
308 = "（あの時、キースとダストだけで、\\n　他の人には絶対に握手をさせなかったから、\\n　今日は握手したいってヤツが結構来ている）"

# カズマ（Ｍ）
# display as カズマ
# （ふっ、俺のプロデュースもなかなか的確だな）
318 = "（ふっ、俺のプロデュースもなかなか的確だな）"

# カズマ（Ｍ）
# display as カズマ
# （今日の握手会は、デビュー直後の\n　ファンサービスって位置づけだが、これから\n　は色んな付加価値が付けられそうだ）
330 = "（今日の握手会は、デビュー直後の\\n　ファンサービスって位置づけだが、これから\\n　は色んな付加価値が付けられそうだ）"

# カズマ（Ｍ）
# display as カズマ
# （握手券を売り出して、持っている枚数の時間だけ\n　握手やおしゃべりが出来るようにするとかな）
332 = "（握手券を売り出して、持っている枚数の時間だけ\\n　握手やおしゃべりが出来るようにするとかな）"

# カズマ（Ｍ）
# display as カズマ
# （金儲けのチャンス到来だな！\n　この機を逃さず、稼いで稼いで稼ぎまくって\n　やるぞ！）
337 = "（金儲けのチャンス到来だな！\\n　この機を逃さず、稼いで稼いで稼ぎまくって\\n　やるぞ！）"

