# st03c_03.txt.scn

[info]
0 = ""

[characters]
196 = "クリス"
197 = "ダクネス"
189 = "めぐみん"
190 = "ゆんゆん"
191 = "アクア"
193 = "カズマ"
195 = "カズマ（Ｍ）"
192 = "ウィズ"

[character_subs]
# 193 = "カズマ"

[script]
# lines: 27

# クリス
# ふーっ……体が重いけど心地良い疲れだね。
186 = "ふーっ……体が重いけど心地良い疲れだね。"

# ダクネス
# ああ……あの時の興奮が身体から抜けきっていない\n様だ。
174 = "ああ……あの時の興奮が身体から抜けきっていない\\n様だ。"

# めぐみん
# ふぃぃぃ、もう動けないです。
184 = "ふぃぃぃ、もう動けないです。"

# ゆんゆん
# 何だか意識失いそうだよ。
199 = "何だか意識失いそうだよ。"

# アクア
# みんな魂まで抜けきってるって感じね。
188 = "みんな魂まで抜けきってるって感じね。"

# カズマ
# そりゃそうだろ。\n初めてのステージを終えた後なんだから。
180 = "そりゃそうだろ。\\n初めてのステージを終えた後なんだから。"

# カズマ
# 俺からしてみれば、\n平気そうにしてるお前の方が信じられないわ。
200 = "俺からしてみれば、\\n平気そうにしてるお前の方が信じられないわ。"

# アクア
# 確かに疲れたけど、あんなに信者が\n集まってくれたのよ！
232 = "確かに疲れたけど、あんなに信者が\\n集まってくれたのよ！"

# アクア
# 本当に女神冥利に尽きるってやつよ。
204 = "本当に女神冥利に尽きるってやつよ。"

# カズマ（Ｍ）
# display as カズマ
# （女神ってやつは、声援を貰えると、\n　力が増大したりするんだろうか？）
237 = "（女神ってやつは、声援を貰えると、\\n　力が増大したりするんだろうか？）"

# カズマ
# てかお前は、ファンを信者って呼ぶのやめろ。
183 = "てかお前は、ファンを信者って呼ぶのやめろ。"

# ダクネス
# それにしても、カズマの読みは凄かったな。
181 = "それにしても、カズマの読みは凄かったな。"

# クリス
# うん、どれもこれも、大盛り上がりだったね。
177 = "うん、どれもこれも、大盛り上がりだったね。"

# ゆんゆん
# 歌やダンスの特訓をしておいて、\n本当に良かったです。
205 = "歌やダンスの特訓をしておいて、\\n本当に良かったです。"

# カズマ
# だろ？　この名プロデューサーは\n色んな事をお見通しなんだよ。
182 = "だろ？　この名プロデューサーは\\n色んな事をお見通しなんだよ。"

# めぐみん
# 素直に凄いと思ってしまいました。
234 = "素直に凄いと思ってしまいました。"

# ウィズ
# カズマさんは、本当に色々な知識と経験を\n持っているんですね。
194 = "カズマさんは、本当に色々な知識と経験を\\n持っているんですね。"

# アクア
# その割には、いつまで経っても弱小冒険者の\nままだけどね。
179 = "その割には、いつまで経っても弱小冒険者の\\nままだけどね。"

# カズマ
# うるせー！　プロデューサーって言う職業が\nギルドに登録されたら、すぐにでも転職してやる！
176 = "うるせー！　プロデューサーって言う職業が\\nギルドに登録されたら、すぐにでも転職してやる！"

# カズマ（Ｍ）
# display as カズマ
# （もしそうなったら、新しいアイドルを発掘して、\n　じゃんじゃんプロデュースして、アイドル文化を\n　この世界に広めてやるぜ！）
236 = "（もしそうなったら、新しいアイドルを発掘して、\\n　じゃんじゃんプロデュースして、アイドル文化を\\n　この世界に広めてやるぜ！）"

# カズマ（Ｍ）
# display as カズマ
# （そして、大もうけして、\n　一生、面白おかしく生きてやるんだ！）
235 = "（そして、大もうけして、\\n　一生、面白おかしく生きてやるんだ！）"

# カズマ
# さて、今回のライブは予想以上の入場料が\n手に入ったことだし――
178 = "さて、今回のライブは予想以上の入場料が\\n手に入ったことだし――"

# カズマ
# みんな、これから打ち上げをするぞ！\n思う存分飲み食いしていいからな。\n今日の疲れを吹き飛ばしてくれ！
187 = "みんな、これから打ち上げをするぞ！\\n思う存分飲み食いしていいからな。\\n今日の疲れを吹き飛ばしてくれ！"

# アクア
# 待ってました！\nとりあえずシュワシュワくださーい。
203 = "待ってました！\\nとりあえずシュワシュワくださーい。"

# めぐみん
# 私はからあげを大盛りで！
233 = "私はからあげを大盛りで！"

# クリス
# ふふふっ、今日のシュワシュワはとびきり\n美味しいかも。
185 = "ふふふっ、今日のシュワシュワはとびきり\\n美味しいかも。"

# ダクネス
# ああ、みんなで乾杯しよう。
175 = "ああ、みんなで乾杯しよう。"

