# st03b_01.txt.scn

[info]
0 = ""

[characters]
224 = "カズマ"
225 = "カズマ（Ｍ）"
226 = "クリス"
222 = "アクア"
227 = "ダクネス"
218 = "めぐみん"
223 = "ウィズ"
219 = "ゆんゆん"

[character_subs]
# 224 = "カズマ"

[script]
# lines: 52

# カズマ
# んっ……あ……も、もう朝なのか？
221 = "んっ……あ……も、もう朝なのか？"

# カズマ（Ｍ）
# display as カズマ
# （そういえば、夜明け前になんとか衣装が完成して、\n　それからすぐ意識が飛んじまったのか）
277 = "（そういえば、夜明け前になんとか衣装が完成して、\\n　それからすぐ意識が飛んじまったのか）"

# カズマ（Ｍ）
# display as カズマ
# （あ、ゆんゆんはソファーで、ウィズは机に\n　突っ伏して寝てる）
276 = "（あ、ゆんゆんはソファーで、ウィズは机に\\n　突っ伏して寝てる）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスとめぐみんは自分の部屋があるのに、\n　床で寝っ転がってるな）
284 = "（ダクネスとめぐみんは自分の部屋があるのに、\\n　床で寝っ転がってるな）"

# カズマ（Ｍ）
# display as カズマ
# （みんな、協力してくれてありがとうな！）
282 = "（みんな、協力してくれてありがとうな！）"

# カズマ（Ｍ）
# display as カズマ
# （疲れているだろうし、\n　目が覚めるまでそっとしておこう）
285 = "（疲れているだろうし、\\n　目が覚めるまでそっとしておこう）"

# クリス
# あ、おはようカズマ。\n勝手にお風呂借りちゃったよ？
188 = "あ、おはようカズマ。\\n勝手にお風呂借りちゃったよ？"

# カズマ
# ああ、それは構わないけど。\nずいぶん元気だな？
189 = "ああ、それは構わないけど。\\nずいぶん元気だな？"

# カズマ
# ふぁぁぁぁ、俺はまだ眠くてたまらないのに。
212 = "ふぁぁぁぁ、俺はまだ眠くてたまらないのに。"

# クリス
# 職業柄、徹夜には慣れてるからね。
275 = "職業柄、徹夜には慣れてるからね。"

# カズマ
# え、まさか、一睡もしてないのか？
197 = "え、まさか、一睡もしてないのか？"

# クリス
# 獣と同じ檻の中で眠るほど、\nあたしは無謀じゃないからね。
239 = "獣と同じ檻の中で眠るほど、\\nあたしは無謀じゃないからね。"

# カズマ
# 何それ、もしかして俺のこと言ってる？
232 = "何それ、もしかして俺のこと言ってる？"

# クリス
# あはは、どうだろうね。
191 = "あはは、どうだろうね。"

# アクア
# ふぁぁぁっ……おはよう……。\n衣装の方はどうなった？
213 = "ふぁぁぁっ……おはよう……。\\n衣装の方はどうなった？"

# カズマ
# ああ、なんとか完成したぞ。
190 = "ああ、なんとか完成したぞ。"

# アクア
# 本当に？\n私にも見せて見せて。
237 = "本当に？\\n私にも見せて見せて。"

# クリス
# しかし驚いたよ。\nまさかアクアさんにあんな特技があったなんてね。
200 = "しかし驚いたよ。\\nまさかアクアさんにあんな特技があったなんてね。"

# アクア
# みんなも言ってたけど、そんなに凄いことかしら。\n別に普通だと思うんだけど。
217 = "みんなも言ってたけど、そんなに凄いことかしら。\\n別に普通だと思うんだけど。"

# カズマ
# いや、お前のキャラ的に考えて、\n裁縫ができるなんてどう考えても普通じゃない。
194 = "いや、お前のキャラ的に考えて、\\n裁縫ができるなんてどう考えても普通じゃない。"

# アクア
# 何それ、どういう意味よ。
231 = "何それ、どういう意味よ。"

# カズマ（Ｍ）
# display as カズマ
# （まさかこいつが、あんなに裁縫が上手いなんて\n　本当に予想外だ）
281 = "（まさかこいつが、あんなに裁縫が上手いなんて\\n　本当に予想外だ）"

# カズマ（Ｍ）
# display as カズマ
# （１日で完成させるなんて無茶なスケジュールも\n　こいつが居なかったら実現しなかっただろう）
286 = "（１日で完成させるなんて無茶なスケジュールも\\n　こいつが居なかったら実現しなかっただろう）"

# カズマ（Ｍ）
# display as カズマ
# （でも、素直に褒めてやるのは\n　なんか悔しいんだよな）
279 = "（でも、素直に褒めてやるのは\\n　なんか悔しいんだよな）"

# カズマ（Ｍ）
# display as カズマ
# （みんなは完成するまで起きてたのに、\n　こいつはさっさと風呂に入って寝ちまうし）
283 = "（みんなは完成するまで起きてたのに、\\n　こいつはさっさと風呂に入って寝ちまうし）"

# アクア
# まあ、私がいなければ一晩で完成するなんて\n不可能だったわけだし――
215 = "まあ、私がいなければ一晩で完成するなんて\\n不可能だったわけだし――"

# アクア
# ほらほら、カズマさん。\n遠慮しないでお褒めの言葉をくれちゃっても\nいいのよ。
214 = "ほらほら、カズマさん。\\n遠慮しないでお褒めの言葉をくれちゃっても\\nいいのよ。"

# カズマ（Ｍ）
# display as カズマ
# （そしてこの言い草、むかつくっ！）
278 = "（そしてこの言い草、むかつくっ！）"

# カズマ
# 何お前、もしかして部屋で寝てたの？
230 = "何お前、もしかして部屋で寝てたの？"

# アクア
# うん、そうよ。\nそれがどうかした？
196 = "うん、そうよ。\\nそれがどうかした？"

# カズマ
# いやー、途中からお前のこと忘れてたなーって\n思ってさ。
195 = "いやー、途中からお前のこと忘れてたなーって\\n思ってさ。"

# カズマ
# お前って存在感が薄いんだな。\nあれ、それってアイドルとして致命的じゃね？
199 = "お前って存在感が薄いんだな。\\nあれ、それってアイドルとして致命的じゃね？"

# アクア
# 私は女神なのよ！\n存在感の固まりみたいなものじゃない！
274 = "私は女神なのよ！\\n存在感の固まりみたいなものじゃない！"

# カズマ
# お前がそう思ってるなら、そうなんじゃないか？
198 = "お前がそう思ってるなら、そうなんじゃないか？"

# アクア
# ねえ、冗談よね、嘘よね、カズマ！\n存在が空気みたいって、女神としては致命的に\nマズいんですけど！
206 = "ねえ、冗談よね、嘘よね、カズマ！\\n存在が空気みたいって、女神としては致命的に\\nマズいんですけど！"

# カズマ
# あー、もう、鬱陶しいからくっつくな！
193 = "あー、もう、鬱陶しいからくっつくな！"

# ダクネス
# なんの騒ぎだ、騒々しい。
204 = "なんの騒ぎだ、騒々しい。"

# めぐみん
# ふぁぁぁ。またアクアを泣かせたんですか。\nもうカズマのライフワークみたいなものですね。
211 = "ふぁぁぁ。またアクアを泣かせたんですか。\\nもうカズマのライフワークみたいなものですね。"

# アクア
# ねえ、ダクネス、めぐみん。\n私って空気なの？　違うわよね？
205 = "ねえ、ダクネス、めぐみん。\\n私って空気なの？　違うわよね？"

# ダクネス
# は、はあ？
207 = "は、はあ？"

# ウィズ
# ふぁぁぁ、おはようございます。
210 = "ふぁぁぁ、おはようございます。"

# ゆんゆん
# ……んっ……あ、す、すみません、\n寝ちゃってました。
187 = "……んっ……あ、す、すみません、\\n寝ちゃってました。"

# カズマ
# よし、これで全員起きたな。
220 = "よし、これで全員起きたな。"

# ゆんゆん
# まだ……眠いですよ。
216 = "まだ……眠いですよ。"

# カズマ
# それはみんな一緒だよ。\n時間が無いんだから、さっそく完成した衣装を\n試着してくれ。
201 = "それはみんな一緒だよ。\\n時間が無いんだから、さっそく完成した衣装を\\n試着してくれ。"

# カズマ
# 不具合があったら、俺とアクアで直すからさ。
228 = "不具合があったら、俺とアクアで直すからさ。"

# アクア
# はいはい！　私から着ます！
209 = "はいはい！　私から着ます！"

# カズマ
# って、立ち直るの早っ！
203 = "って、立ち直るの早っ！"

# クリス
# あはは、もう全員ぶんできてるんだから、\n順番なんてないよ。
192 = "あはは、もう全員ぶんできてるんだから、\\n順番なんてないよ。"

# アクア
# それもそうね。\nじゃあカズマは廊下に出ててくれる？
202 = "それもそうね。\\nじゃあカズマは廊下に出ててくれる？"

# カズマ
# はいはい、わかってるよ。
208 = "はいはい、わかってるよ。"

# カズマ（Ｍ）
# display as カズマ
# （どうせまた時間がかかるだろうし、\n　風呂をすませちまうか）
280 = "（どうせまた時間がかかるだろうし、\\n　風呂をすませちまうか）"

