# st03c_01.txt.scn

[info]
0 = ""

[characters]
368 = "カズマ（Ｍ）"
365 = "ウィズ"
367 = "カズマ"
362 = "アクア"
356 = "ゆんゆん"
351 = "めぐみん"
372 = "ダクネス"
369 = "クリス"
373 = "ダクネス＆めぐみん＆ゆんゆん＆クリス＆ウィズ"

[character_subs]
# 367 = "カズマ"
349 = "みんな"

[script]
# lines: 144

# カズマ（Ｍ）
# display as カズマ
# （それからしばらく、俺はプロデューサーとして\n　多忙な日々を過ごしていった）
501 = "（それからしばらく、俺はプロデューサーとして\\n　多忙な日々を過ごしていった）"

# カズマ（Ｍ）
# display as カズマ
# （楽曲の提供先を探して走り回り、\n　振り付けと共に練習させたり――）
510 = "（楽曲の提供先を探して走り回り、\\n　振り付けと共に練習させたり――）"

# カズマ（Ｍ）
# display as カズマ
# （街の有力者やギルドと交渉し、\n　ライブを開く許可を貰ったり――）
511 = "（街の有力者やギルドと交渉し、\\n　ライブを開く許可を貰ったり――）"

# カズマ（Ｍ）
# display as カズマ
# （レッスンが厳しくて、アイドルをやめたいって\n　言う子をみんなで説得して、更に絆を深めたりと\n　涙無しでは語れない出来事の連続だった）
506 = "（レッスンが厳しくて、アイドルをやめたいって\\n　言う子をみんなで説得して、更に絆を深めたりと\\n　涙無しでは語れない出来事の連続だった）"

# カズマ（Ｍ）
# display as カズマ
# （そして今……）
500 = "（そして今……）"

# カズマ（Ｍ）
# display as カズマ
# （ついに、俺たちのアイドルプロジェクトの\n　お披露目の時がやってきたのだ！）
502 = "（ついに、俺たちのアイドルプロジェクトの\\n　お披露目の時がやってきたのだ！）"

# カズマ（Ｍ）
# display as カズマ
# （元はと言えば、\n　呪いの指輪を外す為に何か金策は無いかと\n　考えたアイディアだったけど――）
509 = "（元はと言えば、\\n　呪いの指輪を外す為に何か金策は無いかと\\n　考えたアイディアだったけど――）"

# カズマ（Ｍ）
# display as カズマ
# （今はこれが本業だって思えるくらいに、\n　楽しくなってきたんだよな）
507 = "（今はこれが本業だって思えるくらいに、\\n　楽しくなってきたんだよな）"

# ウィズ
# あ、あの、カズマさん。\n私、おかしなところはありませんか？
272 = "あ、あの、カズマさん。\\n私、おかしなところはありませんか？"

# ウィズ
# ボタンを掛け違えてたり、髪が跳ねてたり、\nあとはあとは、ああ、お化粧をして\n顔色を良く見せた方がいいでしょうか。
376 = "ボタンを掛け違えてたり、髪が跳ねてたり、\\nあとはあとは、ああ、お化粧をして\\n顔色を良く見せた方がいいでしょうか。"

# カズマ
# あはは、そんなに緊張するな。\nいつも通りで大丈夫だからさ。
280 = "あはは、そんなに緊張するな。\\nいつも通りで大丈夫だからさ。"

# アクア
# ちょっとウィズ。\nこの期に及んでまだビビってるの？
329 = "ちょっとウィズ。\\nこの期に及んでまだビビってるの？"

# アクア
# アンデッドの王なんだから、\n堂々としてなさいよ。
363 = "アンデッドの王なんだから、\\n堂々としてなさいよ。"

# ウィズ
# そうは言われましても……。
320 = "そうは言われましても……。"

# ゆんゆん
# カ、カズマさん、\nお、おトイレ行ってもいいですか？
366 = "カ、カズマさん、\\nお、おトイレ行ってもいいですか？"

# めぐみん
# 全く、何度目なんですか？\n仕方ないですね、特別に私もつき合ってあげます。
386 = "全く、何度目なんですか？\\n仕方ないですね、特別に私もつき合ってあげます。"

# カズマ（Ｍ）
# display as カズマ
# （この２人は、結局激しいトレーニングや、\n　ダンスにはついてこられなかった）
497 = "（この２人は、結局激しいトレーニングや、\\n　ダンスにはついてこられなかった）"

# カズマ（Ｍ）
# display as カズマ
# （まぁその分、トークやキャラ性で\n　このユニットを支えてくれるだろう）
504 = "（まぁその分、トークやキャラ性で\\n　このユニットを支えてくれるだろう）"

# ゆんゆん
# うぅ、今日はちょっと風があるね。
293 = "うぅ、今日はちょっと風があるね。"

# めぐみん
# 確かにこれはまいりましたね。
486 = "確かにこれはまいりましたね。"

# カズマ（Ｍ）
# display as カズマ
# （そういえばモジモジしているのは\n　最後まで変わらなかったな）
499 = "（そういえばモジモジしているのは\\n　最後まで変わらなかったな）"

# ダクネス
# いよいよだな、プロデューサー。
292 = "いよいよだな、プロデューサー。"

# カズマ
# ああ、そうだな。
273 = "ああ、そうだな。"

# クリス
# なんだか嬉しそうだね？
339 = "なんだか嬉しそうだね？"

# カズマ
# みんなの華々しいデビューステージなんだから、\n嬉しくないわけがないだろ。
350 = "みんなの華々しいデビューステージなんだから、\\n嬉しくないわけがないだろ。"

# ダクネス
# 思い返すと、色々なことがあったな。
397 = "思い返すと、色々なことがあったな。"

# ダクネス
# 大衆の面前での発声練習は\n羞恥心を煽る出来事の連続だったし――
392 = "大衆の面前での発声練習は\\n羞恥心を煽る出来事の連続だったし――"

# ダクネス
# 強風が吹く中での衣装を着たダンスレッスンには\n生きた心地がしなかった。
396 = "強風が吹く中での衣装を着たダンスレッスンには\\n生きた心地がしなかった。"

# ダクネス
# 極めつけは、見られることを意識する練習だ。
400 = "極めつけは、見られることを意識する練習だ。"

# クリス
# ああ、酒場のテーブルの上にのってダンスをした\nやつ……。
275 = "ああ、酒場のテーブルの上にのってダンスをした\\nやつ……。"

# クリス
# あれには生きた心地がしなかったね。\nみんな体が固まって動けなくなっちゃったし。
281 = "あれには生きた心地がしなかったね。\\nみんな体が固まって動けなくなっちゃったし。"

# ダクネス
# 私はいつ見られるのかって気が気じゃなかったぞ。
491 = "私はいつ見られるのかって気が気じゃなかったぞ。"

# カズマ
# お前は嬉々として前に出て踊ってただろうが。
302 = "お前は嬉々として前に出て踊ってただろうが。"

# ダクネス
# あれは、恥ずかしがる皆を守るために、\n致し方なくやったことだ。
282 = "あれは、恥ずかしがる皆を守るために、\\n致し方なくやったことだ。"

# カズマ
# まったく、お前はクールキャラなんだぞ。\n少しは行動ってもんを考えてくれよ。
348 = "まったく、お前はクールキャラなんだぞ。\\n少しは行動ってもんを考えてくれよ。"

# クリス
# そういう意味では、\nあたしがちゃんとできるか心配だよ。
317 = "そういう意味では、\\nあたしがちゃんとできるか心配だよ。"

# クリス
# 演技とはいえ、わざわざ集まってくれた人に\n素っ気ない態度取るなんてさ。
404 = "演技とはいえ、わざわざ集まってくれた人に\\n素っ気ない態度取るなんてさ。"

# カズマ
# なんだ、まだ抵抗があるのか？
337 = "なんだ、まだ抵抗があるのか？"

# クリス
# それはそうでしょ。
325 = "それはそうでしょ。"

# カズマ
# 大丈夫だって。\nマニアはちゃんとわかった上で、\n応援してくれるから。
391 = "大丈夫だって。\\nマニアはちゃんとわかった上で、\\n応援してくれるから。"

# クリス
# まあ、そういうのを嗜好する人がいるのは、\n酒場とかの練習でなんとなくわかったけどさ。
347 = "まあ、そういうのを嗜好する人がいるのは、\\n酒場とかの練習でなんとなくわかったけどさ。"

# ダクネス
# 私は、素っ気ない態度を取るクリスが好きだぞ！
490 = "私は、素っ気ない態度を取るクリスが好きだぞ！"

# クリス
# あは、あはは、ありがと。
278 = "あは、あはは、ありがと。"

# アクア
# ねえねえ、カズマ。
341 = "ねえねえ、カズマ。"

# カズマ
# ん、どうした？
360 = "ん、どうした？"

# アクア
# そういえばなんだけど、\nユニット名ってどうなったのかしら。
318 = "そういえばなんだけど、\\nユニット名ってどうなったのかしら。"

# ダクネス
# あっ、すっかり忘れていたな。
276 = "あっ、すっかり忘れていたな。"

# アクア
# もしかして決めていないとかないわよね。
354 = "もしかして決めていないとかないわよね。"

# カズマ
# それだったら安心しろ。\nみんなが納得できるユニット名を考えておいた。
323 = "それだったら安心しろ。\\nみんなが納得できるユニット名を考えておいた。"

# ウィズ
# ぜひ、きかせてください。
314 = "ぜひ、きかせてください。"

# めぐみん
# ふふふ、もしカズマの案がダメでしたら、\n私がこっそりと考えておいたユニット名を\n披露しましょう。
346 = "ふふふ、もしカズマの案がダメでしたら、\\n私がこっそりと考えておいたユニット名を\\n披露しましょう。"

# カズマ
# お前、トイレ行ったんじゃなかったのかよ。
299 = "お前、トイレ行ったんじゃなかったのかよ。"

# めぐみん
# 何度も言わせないでください。\n紅魔族はトイレに行かないんですよ。
384 = "何度も言わせないでください。\\n紅魔族はトイレに行かないんですよ。"

# カズマ
# なるほど、トイレに行かずにそのへんでするのか。
335 = "なるほど、トイレに行かずにそのへんでするのか。"

# ゆんゆん
# そそ、そんなことしませんよ！
322 = "そそ、そんなことしませんよ！"

# クリス
# どうしてキミたちはすぐに話を脱線させるかな。
333 = "どうしてキミたちはすぐに話を脱線させるかな。"

# クリス
# はい、カズマ。話を戻して。
343 = "はい、カズマ。話を戻して。"

# カズマ
# こほん、では発表をするぞ。\nお前たちのユニット名は――
307 = "こほん、では発表をするぞ。\\nお前たちのユニット名は――"

# カズマ
# シャイニーブルーだ！
370 = "シャイニーブルーだ！"

# めぐみん
# うん、響きは悪くないですね。
295 = "うん、響きは悪くないですね。"

# ダクネス
# それに、どことなく清楚さを感じる。
324 = "それに、どことなく清楚さを感じる。"

# アクア
# 何よりもブルーっていうのがいいわ！
383 = "何よりもブルーっていうのがいいわ！"

# カズマ
# 直訳すると、輝く青って感じだな。
485 = "直訳すると、輝く青って感じだな。"

# ウィズ
# 何か意味はあるんでしょうか。
382 = "何か意味はあるんでしょうか。"

# カズマ
# 青ってのは安らぎとか、\nあとは若いってイメージがあるだろ？
496 = "青ってのは安らぎとか、\\nあとは若いってイメージがあるだろ？"

# カズマ
# だから安らぎの光を与える人たち。\nあとは若い芽がこれから輝きを放つって\n意味でつけてみたんだよ。
328 = "だから安らぎの光を与える人たち。\\nあとは若い芽がこれから輝きを放つって\\n意味でつけてみたんだよ。"

# カズマ
# 決して、アクアがどうこうって意味じゃない。
402 = "決して、アクアがどうこうって意味じゃない。"

# アクア
# わかってるわよ！
359 = "わかってるわよ！"

# カズマ
# 異論がなければ、これでいくけどどうかな。
405 = "異論がなければ、これでいくけどどうかな。"

# めぐみん
# 悔しいですが、\n私が考えたルナティックナイトメアよりも\n断然いいです。
398 = "悔しいですが、\\n私が考えたルナティックナイトメアよりも\\n断然いいです。"

# カズマ（Ｍ）
# display as カズマ
# （なんておそろしいユニット名を考えたんだ\n　こいつは……）
503 = "（なんておそろしいユニット名を考えたんだ\\n　こいつは……）"

# カズマ
# んじゃ、異論なしということで、\nシャイニーブルーでいくぞ。
361 = "んじゃ、異論なしということで、\\nシャイニーブルーでいくぞ。"

# ウィズ
# ユニット名も決まって、\nなんだかさらに現実感が増しました。
377 = "ユニット名も決まって、\\nなんだかさらに現実感が増しました。"

# ゆんゆん
# 私も緊張が。
492 = "私も緊張が。"

# めぐみん
# も、もう一度、トイレへ……。
352 = "も、もう一度、トイレへ……。"

# アクア
# ねえねえ、そういえばカズマさん。
340 = "ねえねえ、そういえばカズマさん。"

# カズマ
# 今度はなんだよ。
379 = "今度はなんだよ。"

# アクア
# あのですね、センターの件なんですが。
277 = "あのですね、センターの件なんですが。"

# カズマ
# はぁ、言わなくても普段の練習の立ち位置から\nなんとなくわかるだろ。
342 = "はぁ、言わなくても普段の練習の立ち位置から\\nなんとなくわかるだろ。"

# アクア
# そこはほら、\nちゃんと明言をして欲しいと言いますか。
321 = "そこはほら、\\nちゃんと明言をして欲しいと言いますか。"

# カズマ
# はいはい、それじゃみんなもう一度集合。
344 = "はいはい、それじゃみんなもう一度集合。"

# ダクネス
# 今度はなんだ？
380 = "今度はなんだ？"

# カズマ
# センターはアクアな。\n以上。
371 = "センターはアクアな。\\n以上。"

# アクア
# ええ！？　軽い、軽すぎるよ、カズマさん！\nもっとこう、もったいぶる感じで\n発表して欲しかったんですけど！
296 = "ええ！？　軽い、軽すぎるよ、カズマさん！\\nもっとこう、もったいぶる感じで\\n発表して欲しかったんですけど！"

# カズマ
# 別にもったいぶる理由がないだろ。
388 = "別にもったいぶる理由がないだろ。"

# めぐみん
# そうですよ、普段の練習から察しがついて\nいたんですから。
319 = "そうですよ、普段の練習から察しがついて\\nいたんですから。"

# ダクネス
# うむ、その通りだ。\n今はこんなことに時間を取られている時じゃない。
294 = "うむ、その通りだ。\\n今はこんなことに時間を取られている時じゃない。"

# アクア
# こんなこと！？
308 = "こんなこと！？"

# カズマ
# さて、くだらないことに時間を取られた。
310 = "さて、くだらないことに時間を取られた。"

# アクア
# くだらないこと！？
305 = "くだらないこと！？"

# カズマ
# もう少しでステージの時間だ。\n各々、歌や踊りの復習をしたり、\n昂ぶる気持ちを落ち着かせることに努めてくれ。
353 = "もう少しでステージの時間だ。\\n各々、歌や踊りの復習をしたり、\\n昂ぶる気持ちを落ち着かせることに努めてくれ。"

# ダクネス
# それもいいのだが、\nカズマ、いやプロデューサーから一言あっても\nいいんじゃないか？
326 = "それもいいのだが、\\nカズマ、いやプロデューサーから一言あっても\\nいいんじゃないか？"

# カズマ
# あ、ああ、そうだな。
271 = "あ、ああ、そうだな。"

# カズマ
# 肩の力を抜け！\nそうすれば、お前たちの本当の実力を\n発揮できるはずだ！
494 = "肩の力を抜け！\\nそうすれば、お前たちの本当の実力を\\n発揮できるはずだ！"

# ダクネス
# もっと気の利いた言葉を期待していたのだが。
355 = "もっと気の利いた言葉を期待していたのだが。"

# めぐみん
# なんか普通でしたね。\nカズマに何かを期待した私がバカでしたよ。
336 = "なんか普通でしたね。\\nカズマに何かを期待した私がバカでしたよ。"

# カズマ
# いやいや、これ以上何を言えっていうんだよ！
290 = "いやいや、これ以上何を言えっていうんだよ！"

# クリス
# あは、あははは、キミたちには本当に緊張感って\nものがないんだね。
279 = "あは、あははは、キミたちには本当に緊張感って\\nものがないんだね。"

# ゆんゆん
# でもおかげで、肩の力が抜けました。
332 = "でもおかげで、肩の力が抜けました。"

# カズマ
# このライブが失敗したら見捨てるぞ。
306 = "このライブが失敗したら見捨てるぞ。"

# ダクネス
# いきなり追い込むスタイルか。\nふ、ふふ、やるじゃないか！
289 = "いきなり追い込むスタイルか。\\nふ、ふふ、やるじゃないか！"

# カズマ（Ｍ）
# display as カズマ
# （何を……）
508 = "（何を……）"

# ゆんゆん
# どどど、どうしよう、めぐみん\nライブに失敗したらカズマさんに捨てられちゃうよ。
334 = "どどど、どうしよう、めぐみん\\nライブに失敗したらカズマさんに捨てられちゃうよ。"

# めぐみん
# 別にいいじゃないですか、\n困るのはカズマなんですし。
387 = "別にいいじゃないですか、\\n困るのはカズマなんですし。"

# カズマ（Ｍ）
# display as カズマ
# （そういえば、そうだったー！！）
498 = "（そういえば、そうだったー！！）"

# ゆんゆん
# でも、カズマさんの指輪がそのままだと\n私たち、また下着を……。
331 = "でも、カズマさんの指輪がそのままだと\\n私たち、また下着を……。"

# カズマ
# そ、そうだぞ！\n結果として、被害を受けるのは\nお前たちなんだからな！
315 = "そ、そうだぞ！\\n結果として、被害を受けるのは\\nお前たちなんだからな！"

# クリス
# いやー、ここまで開き直られると\n逆にすがすがしい気持ちになるね。
291 = "いやー、ここまで開き直られると\\n逆にすがすがしい気持ちになるね。"

# めぐみん
# 殴りたくもなりますが。
401 = "殴りたくもなりますが。"

# ウィズ
# ふ、ふふ、こんなときまでみなさんは\nいつも通りなんですね。
345 = "ふ、ふふ、こんなときまでみなさんは\\nいつも通りなんですね。"

# クリス
# おかげで肩の力が少し抜けたよ。
298 = "おかげで肩の力が少し抜けたよ。"

# カズマ
# 俺は、お前らの事を信じてるからな。
385 = "俺は、お前らの事を信じてるからな。"

# ゆんゆん
# 任せておいてください、とは胸を張れませんが、\nカズマさんの期待に応えられるように頑張ります。
381 = "任せておいてください、とは胸を張れませんが、\\nカズマさんの期待に応えられるように頑張ります。"

# カズマ
# ああ、期待しているよ。
274 = "ああ、期待しているよ。"

# めぐみん
# 期待されては、応えないわけにはいきませんね。\n我が紅魔族の力、とくと見せてやります！
399 = "期待されては、応えないわけにはいきませんね。\\n我が紅魔族の力、とくと見せてやります！"

# カズマ
# わかっているとは思うが、爆裂魔法は禁止な。
358 = "わかっているとは思うが、爆裂魔法は禁止な。"

# めぐみん
# ……チッ。
270 = "……チッ。"

# カズマ
# お前は、客を吹っ飛ばす気だったのか！
301 = "お前は、客を吹っ飛ばす気だったのか！"

# めぐみん
# それもまた、熱いステージになると思ったんですよ。
327 = "それもまた、熱いステージになると思ったんですよ。"

# カズマ
# 阿鼻叫喚で熱くなるわ！
495 = "阿鼻叫喚で熱くなるわ！"

# ウィズ
# ふ、ふふ、こんなときまでみなさんは\nいつも通りなんですね。
# 345 = "ふ、ふふ、こんなときまでみなさんは\\nいつも通りなんですね。"

# クリス
# おかげで肩の力が少し抜けたよ。
# 298 = "おかげで肩の力が少し抜けたよ。"

# カズマ
# よし、そろそろ時間だ。\nお前ら、思いっきり楽しんでこい！
357 = "よし、そろそろ時間だ。\\nお前ら、思いっきり楽しんでこい！"

# アクア
# じゃあ、みんな輪になって！
311 = "じゃあ、みんな輪になって！"

# カズマ
# なんだお前もう立ち直ったのか。
338 = "なんだお前もう立ち直ったのか。"

# アクア
# あんなことでいつまでも落ち込んでられないわ。
283 = "あんなことでいつまでも落ち込んでられないわ。"

# カズマ
# お前のそういう前向きなところ、\n本当に尊敬できるわ。
300 = "お前のそういう前向きなところ、\\n本当に尊敬できるわ。"

# アクア
# じゃあ、みんな！\nステージ前の気合い入れいくわよ！
312 = "じゃあ、みんな！\\nステージ前の気合い入れいくわよ！"

# ゆんゆん
# え？　え？　気合い入れって何？
297 = "え？　え？　気合い入れって何？"

# ウィズ
# さ、さあ、それは私にも。
309 = "さ、さあ、それは私にも。"

# アクア
# かけ声は『イエーイ』ね。わかった？
304 = "かけ声は『イエーイ』ね。わかった？"

# めぐみん
# い、いえーい、ですか？
287 = "い、いえーい、ですか？"

# アクア
# そう、イエーイ、なんかノリがいいでしょ？
316 = "そう、イエーイ、なんかノリがいいでしょ？"

# カズマ
# いいから早くやれ。
288 = "いいから早くやれ。"

# アクア
# では、改めて、こほん。
330 = "では、改めて、こほん。"

# アクア
# 私たちはできる！
487 = "私たちはできる！"

# めぐみん
# い、いえい！
285 = "い、いえい！"

# アクア
# 私たちは強い子！
488 = "私たちは強い子！"

# ゆんゆん
# い、いえい！？
286 = "い、いえい！？"

# アクア
# 私たちは輝ける！
489 = "私たちは輝ける！"

# ウィズ
# い、い、いえい！
284 = "い、い、いえい！"

# アクア
# すぅ～～、シャイニーブルーファイトー！！
313 = "すぅ～～、シャイニーブルーファイトー！！"

# ダクネス＆めぐみん＆ゆんゆん＆クリス＆ウィズ
# display as みんな
# イエーイ！！
364 = "イエーイ！！"

# カズマ（Ｍ）
# display as カズマ
# （よし！　ステージ開始だ！！）
505 = "（よし！　ステージ開始だ！！）"

[selections]
493 = "肩の力を抜け"
393 = "失敗したら見捨てるぞ"
303 = "お前らのことを信じてるからな"
