# st03b_04.txt.scn

[info]
0 = ""

[characters]
305 = "アクア"
310 = "カズマ"
313 = "クリス"
312 = "カズマ（Ｍ）"
316 = "ダクネス"
295 = "めぐみん"
309 = "ウィズ"
299 = "ゆんゆん"

[character_subs]
# 310 = "カズマ"

[script]
# lines: 126

# アクア
# あーん、声を出しすぎて喉が痛い。\nもう一言も喋れないよ、カズマさーん。
233 = "あーん、声を出しすぎて喉が痛い。\\nもう一言も喋れないよ、カズマさーん。"

# カズマ
# おいおい、あの程度でかよ。
244 = "おいおい、あの程度でかよ。"

# クリス
# そうは言われても、普段からあんなことを\nしてるわけじゃないんだからさ。
257 = "そうは言われても、普段からあんなことを\\nしてるわけじゃないんだからさ。"

# カズマ
# もしかしてクリスもなのか？
296 = "もしかしてクリスもなのか？"

# クリス
# うん、少し痛いかな。
238 = "うん、少し痛いかな。"

# カズマ（Ｍ）
# display as カズマ
# （まったく、しょうがないな）
418 = "（まったく、しょうがないな）"

# カズマ
# ちょっと待ってろ。\n今、温かい物をいれてやるからさ。
266 = "ちょっと待ってろ。\\n今、温かい物をいれてやるからさ。"

# アクア
# ど、どうしたのよ、カズマ。\nもしかして熱でもあるの？
272 = "ど、どうしたのよ、カズマ。\\nもしかして熱でもあるの？"

# アクア
# それだったら部屋で寝てなさいよ。\nお茶なんて自分たちでいれるから。
260 = "それだったら部屋で寝てなさいよ。\\nお茶なんて自分たちでいれるから。"

# カズマ
# お前は、俺が親切なのがそんなに珍しいか！
247 = "お前は、俺が親切なのがそんなに珍しいか！"

# ダクネス
# カズマが自ら進んで家事をやるのは稀だろう。
311 = "カズマが自ら進んで家事をやるのは稀だろう。"

# めぐみん
# それがアクアのためというなら尚更ですよ。
259 = "それがアクアのためというなら尚更ですよ。"

# カズマ
# お前たちの体調を管理するのも\nプロデューサーである俺の仕事なんだよ。
245 = "お前たちの体調を管理するのも\\nプロデューサーである俺の仕事なんだよ。"

# カズマ
# だったらやりたくないこともやらないとだろ。
264 = "だったらやりたくないこともやらないとだろ。"

# アクア
# 今の言い方、すごく棘を感じるんですけど。
323 = "今の言い方、すごく棘を感じるんですけど。"

# カズマ
# 気のせいだ。
343 = "気のせいだ。"

# カズマ（Ｍ）
# display as カズマ
# （そうか、食事とかそういうことにも\n　気を使わないといけないんだよな）
412 = "（そうか、食事とかそういうことにも\\n　気を使わないといけないんだよな）"

# カズマ（Ｍ）
# display as カズマ
# （アクアは放っておいたら暴飲暴食しそうだし）
420 = "（アクアは放っておいたら暴飲暴食しそうだし）"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんは爆裂魔法を無計画に撃って\n　練習にならなくなるかもしれない）
419 = "（めぐみんは爆裂魔法を無計画に撃って\\n　練習にならなくなるかもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、プロデューサーって\n　色々な事に気を使わないといけないから大変だ）
417 = "（はぁ、プロデューサーって\\n　色々な事に気を使わないといけないから大変だ）"

# アクア
# ねえ、ダクネス。\nまだシュワシュワってあったわよね？
284 = "ねえ、ダクネス。\\nまだシュワシュワってあったわよね？"

# カズマ
# お前は、バカかー！
246 = "お前は、バカかー！"

# アクア
# ど、どうしてよ！
273 = "ど、どうしてよ！"

# カズマ
# アクアは、このプロジェクトが終わるまで\nシュワシュワは禁止な！
308 = "アクアは、このプロジェクトが終わるまで\\nシュワシュワは禁止な！"

# アクア
# なんでよ！\n私の唯一の楽しみなのに！
278 = "なんでよ！\\n私の唯一の楽しみなのに！"

# カズマ
# アクアだけじゃない、他のみんなも同じだからな。\n特にめぐみん！
307 = "アクアだけじゃない、他のみんなも同じだからな。\\n特にめぐみん！"

# めぐみん
# 私は飲みませんよ！
405 = "私は飲みませんよ！"

# カズマ
# 爆裂魔法を撃つのは、\nアイドルの特訓が終わった後に時間を限定する。
346 = "爆裂魔法を撃つのは、\\nアイドルの特訓が終わった後に時間を限定する。"

# めぐみん
# なんでですか！
277 = "なんでですか！"

# カズマ
# 爆裂魔法を撃ったら\nしばらく動けなくなるだろ。
345 = "爆裂魔法を撃ったら\\nしばらく動けなくなるだろ。"

# カズマ
# 禁止にされないだけありがたく思え。
404 = "禁止にされないだけありがたく思え。"

# めぐみん
# あなたは何もわかっていませんよ、カズマ！
229 = "あなたは何もわかっていませんよ、カズマ！"

# カズマ
# 何を……。
326 = "何を……。"

# めぐみん
# 日の出に希望を見いだしながら爆裂したり、\n空に向かい命あることに感謝をしながら爆裂したり、\nおぼろ月に哀愁を感じながら爆裂したり――
339 = "日の出に希望を見いだしながら爆裂したり、\\n空に向かい命あることに感謝をしながら爆裂したり、\\nおぼろ月に哀愁を感じながら爆裂したり――"

# めぐみん
# そういう、季節の移ろいを楽しみながら\n爆裂するのも爆裂道のあり方なのです！
256 = "そういう、季節の移ろいを楽しみながら\\n爆裂するのも爆裂道のあり方なのです！"

# カズマ
# 適当な理由を並べるな。\nお前はただストレスを発散したいときに\n爆裂できないのが嫌なだけだろうが。
409 = "適当な理由を並べるな。\\nお前はただストレスを発散したいときに\\n爆裂できないのが嫌なだけだろうが。"

# めぐみん
# ぬぐぐ。
281 = "ぬぐぐ。"

# カズマ
# 他のみんなにも細かいところで色々あるからな。
324 = "他のみんなにも細かいところで色々あるからな。"

# アクア
# 横暴よ！　これは、あれよ、あれ！\nしょ、しょっけ？？
341 = "横暴よ！　これは、あれよ、あれ！\\nしょ、しょっけ？？"

# ウィズ
# 職権濫用ですか？
407 = "職権濫用ですか？"

# アクア
# そう、それ！\n私はそれをとても酷いことだと思うの！
255 = "そう、それ！\\n私はそれをとても酷いことだと思うの！"

# カズマ
# 俺だってやり過ぎだとは思ってるよ。\nでも、この中からセンターを張れるやつを\n決めないといけないんだぞ。
327 = "俺だってやり過ぎだとは思ってるよ。\\nでも、この中からセンターを張れるやつを\\n決めないといけないんだぞ。"

# カズマ
# そのためにはある程度縛り付けて\n体調を崩さないように管理する必要も\nあるんだって。
258 = "そのためにはある程度縛り付けて\\n体調を崩さないように管理する必要も\\nあるんだって。"

# ゆんゆん
# あの、すみません、センターってなんですか？
230 = "あの、すみません、センターってなんですか？"

# カズマ
# 簡単に言えば、そのグループの看板であり\nメインで歌うアイドルのことだよ。
406 = "簡単に言えば、そのグループの看板であり\\nメインで歌うアイドルのことだよ。"

# ダクネス
# つまり、中心人物と言うことか。
268 = "つまり、中心人物と言うことか。"

# めぐみん
# 何だか主役っぽいですね。
325 = "何だか主役っぽいですね。"

# カズマ
# 普通、誰がセンターになるかは、\n歌やダンスの実力、カリスマ性やルックス、\nそして人間性が参考にされるんだ。
340 = "普通、誰がセンターになるかは、\\n歌やダンスの実力、カリスマ性やルックス、\\nそして人間性が参考にされるんだ。"

# カズマ
# もちろん看板である以上、\n体調が悪いからって活動を休まれちゃ困る。
297 = "もちろん看板である以上、\\n体調が悪いからって活動を休まれちゃ困る。"

# クリス
# ふーん、なんか大変なんだね。
288 = "ふーん、なんか大変なんだね。"

# ゆんゆん
# 上手に歌や踊りを披露できればそれでいいと\n思っていました。
320 = "上手に歌や踊りを披露できればそれでいいと\\n思っていました。"

# アクア
# ねえねえ。\nそれで、今センターに一番近いのは誰なの？
285 = "ねえねえ。\\nそれで、今センターに一番近いのは誰なの？"

# カズマ（Ｍ）
# display as カズマ
# （うーん、現時点でのセンターの筆頭か）
410 = "（うーん、現時点でのセンターの筆頭か）"

# カズマ（Ｍ）
# display as カズマ
# （キャラクター性ならめぐみん）
422 = "（キャラクター性ならめぐみん）"

# カズマ（Ｍ）
# display as カズマ
# （容姿、体のパーツならダクネス、ゆんゆんかな）
425 = "（容姿、体のパーツならダクネス、ゆんゆんかな）"

# カズマ（Ｍ）
# display as カズマ
# （でもクリスのリーダーシップも捨てがたいし――）
414 = "（でもクリスのリーダーシップも捨てがたいし――）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズの知名度、そして包容力も\n　十分にセンターを張れる武器になるだろう）
421 = "（ウィズの知名度、そして包容力も\\n　十分にセンターを張れる武器になるだろう）"

# アクア
# わくわく。
304 = "わくわく。"

# カズマ（Ｍ）
# display as カズマ
# （そう、こいつが問題なんだよ）
411 = "（そう、こいつが問題なんだよ）"

# カズマ（Ｍ）
# display as カズマ
# （単純なアイドルとしての資質で選ぶなら、\n　やっぱりアクアが頭１つ抜けてる）
424 = "（単純なアイドルとしての資質で選ぶなら、\\n　やっぱりアクアが頭１つ抜けてる）"

# カズマ（Ｍ）
# display as カズマ
# （でもこいつは人間性に難がありすぎる。\n　何よりもサボり癖が問題だ）
413 = "（でもこいつは人間性に難がありすぎる。\\n　何よりもサボり癖が問題だ）"

# カズマ（Ｍ）
# display as カズマ
# （センターの人間は、\n　周りを引っ張っていくカリスマ性も必要だし）
423 = "（センターの人間は、\\n　周りを引っ張っていくカリスマ性も必要だし）"

# アクア
# ほらほら、焦らさないで早く言いなさいったら。
291 = "ほらほら、焦らさないで早く言いなさいったら。"

# カズマ
# うーん、アクアかなぁ。
240 = "うーん、アクアかなぁ。"

# アクア
# やっぱりそうよね！\n女神である私がやらないで、いったい誰がやるって\n話よ。
298 = "やっぱりそうよね！\\n女神である私がやらないで、いったい誰がやるって\\n話よ。"

# カズマ
# といいたいところだけど、トータルで見ると\nウィズだろうな。
270 = "といいたいところだけど、トータルで見ると\\nウィズだろうな。"

# アクア
# ええ！？
242 = "ええ！？"

# ウィズ
# わ、私ですか！
302 = "わ、私ですか！"

# アクア
# ちょっとカズマ！\nなんで私じゃなくて、ウィズなのよ！
265 = "ちょっとカズマ！\\nなんで私じゃなくて、ウィズなのよ！"

# ウィズ
# わ、私には分不相応だと思います！
303 = "わ、私には分不相応だと思います！"

# アクア
# だいたい、わかってるの？\nウィズはアンデッドなのよ！
262 = "だいたい、わかってるの？\\nウィズはアンデッドなのよ！"

# アクア
# 薄暗くてじめじめしたところが大好きな\nなめくじの親戚みたいな存在が――
408 = "薄暗くてじめじめしたところが大好きな\\nなめくじの親戚みたいな存在が――"

# ウィズ
# ひ、ひどい！
287 = "ひ、ひどい！"

# アクア
# 夢や希望を与えるアイドル、しかもセンターなんて\nできるわけないじゃない。
332 = "夢や希望を与えるアイドル、しかもセンターなんて\\nできるわけないじゃない。"

# カズマ
# じゃあお前だったらセンターを張れるって\nいうのかよ。
252 = "じゃあお前だったらセンターを張れるって\\nいうのかよ。"

# アクア
# 当然じゃない、私は女神なのよ。
337 = "当然じゃない、私は女神なのよ。"

# カズマ
# 女神って言ってもピンキリだろうが。\nもちろんお前はキリな。
333 = "女神って言ってもピンキリだろうが。\\nもちろんお前はキリな。"

# アクア
# なんですって！\nカズマなんて、人としての底辺じゃない！
276 = "なんですって！\\nカズマなんて、人としての底辺じゃない！"

# カズマ
# て、底辺！？
269 = "て、底辺！？"

# アクア
# ねえ、なんで生きてるの？\nどうして太陽の下を歩いていられるのかしら？
282 = "ねえ、なんで生きてるの？\\nどうして太陽の下を歩いていられるのかしら？"

# カズマ
# この駄女神っ、人としての権利まで否定すんのか！\n引きこもりにだって人権があるんだぞ！
250 = "この駄女神っ、人としての権利まで否定すんのか！\\n引きこもりにだって人権があるんだぞ！"

# アクア
# へえ。
289 = "へえ。"

# カズマ
# へー、じゃねえよ！\nよし、だったらお前がなんでセンター張れねーのか、\n教えてやろうじゃねーか！
290 = "へー、じゃねえよ！\\nよし、だったらお前がなんでセンター張れねーのか、\\n教えてやろうじゃねーか！"

# カズマ
# お前はすぐに楽を選ぶよな！
248 = "お前はすぐに楽を選ぶよな！"

# アクア
# それの何が悪いのよ。
261 = "それの何が悪いのよ。"

# カズマ
# じゃあ、逆に訊くけど、お前はそんなやつに\nついていきたいと思うのか！
251 = "じゃあ、逆に訊くけど、お前はそんなやつに\\nついていきたいと思うのか！"

# アクア
# そ、それは……。
254 = "そ、それは……。"

# カズマ
# センターっていうのはつまりリーダーだ！\nお前みたいに怠惰を絵に描いたようなやつを\n選べるわけねえだろ！
314 = "センターっていうのはつまりリーダーだ！\\nお前みたいに怠惰を絵に描いたようなやつを\\n選べるわけねえだろ！"

# アクア
# ぬぐ、ぐぬぅ。
280 = "ぬぐ、ぐぬぅ。"

# カズマ
# だいたいお前は、放っておいたらずーーーーっと、\nだらだらだらだら、屋敷で食っちゃ寝してる\nだろうが！
263 = "だいたいお前は、放っておいたらずーーーーっと、\\nだらだらだらだら、屋敷で食っちゃ寝してる\\nだろうが！"

# カズマ
# あれ？　それって引きこもりと一緒じゃね？
231 = "あれ？　それって引きこもりと一緒じゃね？"

# カズマ
# ねえ、なんで生きてるの？\nどうして太陽の下を歩けるんですかぁ？
283 = "ねえ、なんで生きてるの？\\nどうして太陽の下を歩けるんですかぁ？"

# アクア
# ぬ、ぬぎぎ、カズマなんてこうしてやる！\nこうしてやるんだから！
279 = "ぬ、ぬぎぎ、カズマなんてこうしてやる！\\nこうしてやるんだから！"

# カズマ
# ぐあ、お前は髪を引っ張るな！
249 = "ぐあ、お前は髪を引っ張るな！"

# ダクネス
# まあまあ、ふたりとも落ちつけ。
292 = "まあまあ、ふたりとも落ちつけ。"

# クリス
# 今のはどっちも悪いよ。\nだからここは喧嘩両成敗ってことにしておきなよ。
322 = "今のはどっちも悪いよ。\\nだからここは喧嘩両成敗ってことにしておきなよ。"

# カズマ
# はぁはぁ、そうだな。
286 = "はぁはぁ、そうだな。"

# ウィズ
# あ、あの、カズマさん？\n先ほどのことは冗談ですよね？
227 = "あ、あの、カズマさん？\\n先ほどのことは冗談ですよね？"

# カズマ
# いや、本気だよ。\nと言っても、現時点での評価だけどさ。
236 = "いや、本気だよ。\\nと言っても、現時点での評価だけどさ。"

# ウィズ
# そ、そうですよね。
253 = "そ、そうですよね。"

# カズマ
# みんな聞いてくれ。
294 = "みんな聞いてくれ。"

# カズマ
# センターってのは、選ぶ基準が色々あるんだ。\n歌や踊りがどれだけ上手かろうが、\nセンターを張れるわけじゃない。
315 = "センターってのは、選ぶ基準が色々あるんだ。\\n歌や踊りがどれだけ上手かろうが、\\nセンターを張れるわけじゃない。"

# カズマ
# 客を引き寄せる吸引力。\nそして皆をまとめるカリスマ性も\n大切な要素の１つなんだ。
334 = "客を引き寄せる吸引力。\\nそして皆をまとめるカリスマ性も\\n大切な要素の１つなんだ。"

# アクア
# あーあーあー。
232 = "あーあーあー。"

# カズマ
# って感じで、努力をひけらかすイヤらしい奴は\nセンターになれない。
267 = "って感じで、努力をひけらかすイヤらしい奴は\\nセンターになれない。"

# アクア
# なっ！？
274 = "なっ！？"

# カズマ
# というのは半分冗談で。
271 = "というのは半分冗談で。"

# クリス
# 半分は本気なんだね。
328 = "半分は本気なんだね。"

# カズマ
# いいか、アクア、お前は歌唱力で群を抜いてる。\n踊りはまだ見ていないが、普段のお前を見る限り\n問題ないだろう。
234 = "いいか、アクア、お前は歌唱力で群を抜いてる。\\n踊りはまだ見ていないが、普段のお前を見る限り\\n問題ないだろう。"

# アクア
# うんうん。
239 = "うんうん。"

# カズマ
# アクア、お前はこのまま負けっ放しでいいのか？\nしかも相手は、アンデッドの王、リッチーだ。
306 = "アクア、お前はこのまま負けっ放しでいいのか？\\nしかも相手は、アンデッドの王、リッチーだ。"

# アクア
# いいわけないじゃない！\nこれは女神とリッチーのプライドを賭けた戦いよ。
235 = "いいわけないじゃない！\\nこれは女神とリッチーのプライドを賭けた戦いよ。"

# カズマ
# まさかとは思うが、エリート女神のお前が\n負けたりしないよな？
293 = "まさかとは思うが、エリート女神のお前が\\n負けたりしないよな？"

# アクア
# 当然よ！\nセンターは私のものなんだから！
338 = "当然よ！\\nセンターは私のものなんだから！"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、こいつがバカで助かった）
416 = "（はぁ、こいつがバカで助かった）"

# カズマ
# よーし、油を売るのもここまでだ。
301 = "よーし、油を売るのもここまでだ。"

# ゆんゆん
# 次は何をするんですか？
342 = "次は何をするんですか？"

# カズマ
# 喉はあまり酷使したくないから、\n次は踊り、ダンスレッスンかな。
331 = "喉はあまり酷使したくないから、\\n次は踊り、ダンスレッスンかな。"

# ゆんゆん
# えぇぇっ！？　ダンス！？
241 = "えぇぇっ！？　ダンス！？"

# カズマ
# ああ、みんなは歌って踊れるアイドルだから、\nダンスももちろんやってもらうつもりだぞ。
228 = "ああ、みんなは歌って踊れるアイドルだから、\\nダンスももちろんやってもらうつもりだぞ。"

# めぐみん
# ハァハァハァハァ……今の状況でダンス。
317 = "ハァハァハァハァ……今の状況でダンス。"

# カズマ
# お、おい、顔が真っ青だぞ。
243 = "お、おい、顔が真っ青だぞ。"

# めぐみん
# ななな、なんでもありませんよ！\nええ、なんでもありませんとも！
275 = "ななな、なんでもありませんよ！\\nええ、なんでもありませんとも！"

# カズマ（Ｍ）
# display as カズマ
# （なんなんだ、いったい）
415 = "（なんなんだ、いったい）"

# カズマ
# よしじゃあ、ダンスの特訓を始めるぞ。
300 = "よしじゃあ、ダンスの特訓を始めるぞ。"

# アクア
# うおおおお、みなぎってきたわ！
237 = "うおおおお、みなぎってきたわ！"

