# st03b_08.txt.scn

[info]
0 = ""

[characters]
237 = "めぐみん"
239 = "ゆんゆん"
251 = "ダクネス"
249 = "クリス"
245 = "カズマ"
243 = "アクア"
244 = "ウィズ"
246 = "カズマ（Ｍ）"

[character_subs]
# 245 = "カズマ"

[script]
# lines: 70

# めぐみん
# はぁぁ、疲れました。
233 = "はぁぁ、疲れました。"

# ゆんゆん
# 私ももうぐったりだよ。
313 = "私ももうぐったりだよ。"

# ダクネス
# 身体はそんなに疲れていないのだが、\n精神的にくるものだな。
314 = "身体はそんなに疲れていないのだが、\\n精神的にくるものだな。"

# クリス
# あ、わかるよ。\n気を遣うから、精神的に疲れちゃうんだね。
195 = "あ、わかるよ。\\n気を遣うから、精神的に疲れちゃうんだね。"

# カズマ
# ほら、水を用意したから\nちゃんと喉を湿らせておけよ。
236 = "ほら、水を用意したから\\nちゃんと喉を湿らせておけよ。"

# カズマ
# すぐに次の練習に移るぞ。
217 = "すぐに次の練習に移るぞ。"

# アクア
# ええー、少しくらい休ませてよ。
206 = "ええー、少しくらい休ませてよ。"

# カズマ
# 酒場から戻るまでの間に十分休めただろ。
316 = "酒場から戻るまでの間に十分休めただろ。"

# クリス
# いやいや、街中をずっとこの格好で\n歩いてきたんだよ。
204 = "いやいや、街中をずっとこの格好で\\n歩いてきたんだよ。"

# ウィズ
# もう、恥ずかしくて恥ずかしくて、\n酒場で握手の練習をしているときよりも\n疲れました。
238 = "もう、恥ずかしくて恥ずかしくて、\\n酒場で握手の練習をしているときよりも\\n疲れました。"

# カズマ
# しょうがないな。\nじゃあ５分だけ休憩。
214 = "しょうがないな。\\nじゃあ５分だけ休憩。"

# めぐみん
# 鬼です。ここに鬼がいますよ！
317 = "鬼です。ここに鬼がいますよ！"

# アクア
# それでこの後はどんな特訓をするのかしら？
223 = "それでこの後はどんな特訓をするのかしら？"

# アクア
# 私は休憩なんていらないわよ。\nなんなら今すぐにでもいいわ！
312 = "私は休憩なんていらないわよ。\\nなんなら今すぐにでもいいわ！"

# カズマ
# さっき、少しくらい休ませろって文句を言ったのは\nどこの誰だ。
212 = "さっき、少しくらい休ませろって文句を言ったのは\\nどこの誰だ。"

# アクア
# 過去は過去、今は今じゃない。\nそれにセンターを狙うのに疲れたなんて\n言っていられないでしょ。
315 = "過去は過去、今は今じゃない。\\nそれにセンターを狙うのに疲れたなんて\\n言っていられないでしょ。"

# カズマ（Ｍ）
# display as カズマ
# （やる気は買うんだけど、普段があれだけに\n　あざとさしか強調されないな）
320 = "（やる気は買うんだけど、普段があれだけに\\n　あざとさしか強調されないな）"

# カズマ（Ｍ）
# display as カズマ
# （ま、どんな理由であれ、\n　やる気になるのはいいことだ）
319 = "（ま、どんな理由であれ、\\n　やる気になるのはいいことだ）"

# カズマ
# じゃあ、次の特訓について説明するな。\n休憩しながらでいいから聞いてくれ。
216 = "じゃあ、次の特訓について説明するな。\\n休憩しながらでいいから聞いてくれ。"

# カズマ
# これから１人ずつ、キャラ付けをしていく。
211 = "これから１人ずつ、キャラ付けをしていく。"

# ダクネス
# キャラ付けというのはメイド喫茶の時にもやった\nあれのことか？
248 = "キャラ付けというのはメイド喫茶の時にもやった\\nあれのことか？"

# カズマ
# ああ、そうだ。
196 = "ああ、そうだ。"

# クリス
# あはは、またあれをやらないといけないのか。
200 = "あはは、またあれをやらないといけないのか。"

# カズマ
# 気持ちは痛いほどわかるけど、必要なことだからさ。
267 = "気持ちは痛いほどわかるけど、必要なことだからさ。"

# ゆんゆん
# あのそれで、キャラ付け？　というのは\nメイド喫茶の時にやったものでいいですか？
199 = "あのそれで、キャラ付け？　というのは\\nメイド喫茶の時にやったものでいいですか？"

# カズマ
# いいや、今回はもっと極端なものにする。
201 = "いいや、今回はもっと極端なものにする。"

# カズマ
# それは、より個性的な方が目を引きやすく、\n記憶に残りやすいという意味があるからだ。
224 = "それは、より個性的な方が目を引きやすく、\\n記憶に残りやすいという意味があるからだ。"

# カズマ
# なんせアイドルは、国民的スターになり得る\n存在だからな。特徴があってこそだ。
231 = "なんせアイドルは、国民的スターになり得る\\n存在だからな。特徴があってこそだ。"

# アクア
# こ、国民的！！
210 = "こ、国民的！！"

# カズマ
# ああ、みんなは国民的アイドルになれる\n可能性を秘めている。だから、このキャラ付けも\n体得して欲しい！
197 = "ああ、みんなは国民的アイドルになれる\\n可能性を秘めている。だから、このキャラ付けも\\n体得して欲しい！"

# カズマ
# それじゃあ、ダクネスお前からいくぞ。
222 = "それじゃあ、ダクネスお前からいくぞ。"

# ダクネス
# 私からか！
311 = "私からか！"

# カズマ
# お前のキャラ付けは、そうだな。\nうん、クール系でいくか。
208 = "お前のキャラ付けは、そうだな。\\nうん、クール系でいくか。"

# カズマ
# いつもの口調は、変えなくて良いから、\n他人に関心が無いように振る舞ってくれ。\n「私に関わるな」……とか、言葉短めにな。
203 = "いつもの口調は、変えなくて良いから、\\n他人に関心が無いように振る舞ってくれ。\\n「私に関わるな」……とか、言葉短めにな。"

# ダクネス
# わ、わかった。\nやってみよう。
242 = "わ、わかった。\\nやってみよう。"

# ダクネス
# ……私に関わるな。
192 = "……私に関わるな。"

# めぐみん
# おお、これはなかなか！
207 = "おお、これはなかなか！"

# ゆんゆん
# とても格好いいです！
230 = "とても格好いいです！"

# ダクネス
# そ、そうか？
219 = "そ、そうか？"

# カズマ
# 次は、「ついて来るな、これは私の戦いだ」って\n言ってみてくれ。
265 = "次は、「ついて来るな、これは私の戦いだ」って\\n言ってみてくれ。"

# ダクネス
# ついて来るな、これは私の戦いだ。
228 = "ついて来るな、これは私の戦いだ。"

# クリス
# 凄いね、いつものダクネスじゃないみたい。
257 = "凄いね、いつものダクネスじゃないみたい。"

# ウィズ
# はい、とっても素敵な騎士様に見えちゃいます。
235 = "はい、とっても素敵な騎士様に見えちゃいます。"

# ダクネス
# そう言ってくれるのは嬉しいのだが、\n少し複雑な気分だぞ。
220 = "そう言ってくれるのは嬉しいのだが、\\n少し複雑な気分だぞ。"

# カズマ
# じゃあ、ダクネスはそんな感じでよろしくな。
215 = "じゃあ、ダクネスはそんな感じでよろしくな。"

# カズマ
# 次はクリスなんだけど……。
266 = "次はクリスなんだけど……。"

# クリス
# あたしはいじりようないでしょ。
198 = "あたしはいじりようないでしょ。"

# カズマ
# そんなことないぞ。\nクリスの普段は、明るくて可愛い系だから。
226 = "そんなことないぞ。\\nクリスの普段は、明るくて可愛い系だから。"

# クリス
# マジマジ見られながらそういうことを\nハッキリと言われるのは。
254 = "マジマジ見られながらそういうことを\\nハッキリと言われるのは。"

# カズマ
# よし、クリスは塩対応キャラでいこう！
240 = "よし、クリスは塩対応キャラでいこう！"

# クリス
# し、塩対応？\nなにそれ？
213 = "し、塩対応？\\nなにそれ？"

# カズマ
# それはな、愛想の無い対応をするってことだよ。
225 = "それはな、愛想の無い対応をするってことだよ。"

# クリス
# でも、さっき国民的スターになれる存在って\n言ってたのに、そんな愛想が悪くていいのかな？
229 = "でも、さっき国民的スターになれる存在って\\n言ってたのに、そんな愛想が悪くていいのかな？"

# カズマ
# いいんだよ。\nその素っ気なさがたまらん！\nという人も結構いるんだ。
202 = "いいんだよ。\\nその素っ気なさがたまらん！\\nという人も結構いるんだ。"

# カズマ
# 俺の住んでた所じゃ、\n塩対応するアイドルは人気だからな。
256 = "俺の住んでた所じゃ、\\n塩対応するアイドルは人気だからな。"

# クリス
# そ、そういうことだったら、やってみてもいいけど、\n難しそうだなぁ。\n愛想が無い……愛想が無いか。
218 = "そ、そういうことだったら、やってみてもいいけど、\\n難しそうだなぁ。\\n愛想が無い……愛想が無いか。"

# カズマ
# ちょっと練習してみようか。\nじゃあ、俺はファンの役で。
227 = "ちょっと練習してみようか。\\nじゃあ、俺はファンの役で。"

# カズマ
# クリスさん！　応援してますよ！
250 = "クリスさん！　応援してますよ！"

# クリス
# そう？　ふーん。
221 = "そう？　ふーん。"

# カズマ
# あ、あの、握手してもらってもいいですか？
193 = "あ、あの、握手してもらってもいいですか？"

# クリス
# はい……握手。
234 = "はい……握手。"

# カズマ
# あ、ありがとうございます。
194 = "あ、ありがとうございます。"

# クリス
# 別にいいけど。
258 = "別にいいけど。"

# カズマ（Ｍ）
# display as カズマ
# （う、心が痛い。\n　それに涙がこぼれ落ちそうだ）
318 = "（う、心が痛い。\\n　それに涙がこぼれ落ちそうだ）"

# クリス
# か、カズマ、どうしたの？\nなんか目に涙がたまってるけど。
209 = "か、カズマ、どうしたの？\\nなんか目に涙がたまってるけど。"

# カズマ
# なんでもない、なんでもないぞ。\nクリスはそんな感じで頼む。
232 = "なんでもない、なんでもないぞ。\\nクリスはそんな感じで頼む。"

# クリス
# キミがそういうならやるけどさ。\nこれって本当に正解なのかな。
247 = "キミがそういうならやるけどさ。\\nこれって本当に正解なのかな。"

# カズマ
# 大丈夫だ。\nでも、たまには優しくしてくれよな。\n愛想笑いでもいいからさ。
261 = "大丈夫だ。\\nでも、たまには優しくしてくれよな。\\n愛想笑いでもいいからさ。"

# クリス
# う、うん、わかった。
205 = "う、うん、わかった。"

# カズマ
# よし、気を取り直して、\n次はゆんゆんにキャラ付けするぞ。
241 = "よし、気を取り直して、\\n次はゆんゆんにキャラ付けするぞ。"

