# st03b_09.txt.scn

[info]
0 = ""

[characters]
324 = "ゆんゆん"
341 = "カズマ"
320 = "めぐみん"
339 = "ウィズ"
343 = "カズマ（Ｍ）"
344 = "クリス"
338 = "アクア"

[character_subs]
# 341 = "カズマ"

[script]
# lines: 126

# ゆんゆん
# は、はい、よろしくお願いします！
307 = "は、はい、よろしくお願いします！"

# カズマ
# ゆんゆんは王道の不思議ちゃんぶりっこだ！
329 = "ゆんゆんは王道の不思議ちゃんぶりっこだ！"

# ゆんゆん
# ふ、不思議ちゃん！？
312 = "ふ、不思議ちゃん！？"

# カズマ
# ああそれと、一人称は「ゆんゆん」だ！\n出来るだけ可愛く頼むぞ！
239 = "ああそれと、一人称は「ゆんゆん」だ！\\n出来るだけ可愛く頼むぞ！"

# ゆんゆん
# えぇぇっ！？　わ、私に出来るかなぁ。
259 = "えぇぇっ！？　わ、私に出来るかなぁ。"

# めぐみん
# 一人称は、ゆんゆんですよ。
349 = "一人称は、ゆんゆんですよ。"

# ゆんゆん
# わ、わかったよ。\nで、でも何を言えばいいのかわからないよ。
334 = "わ、わかったよ。\\nで、でも何を言えばいいのかわからないよ。"

# めぐみん
# 私は生涯ぼっちです。\nはい、どうぞ！
419 = "私は生涯ぼっちです。\\nはい、どうぞ！"

# ゆんゆん
# ぜ、絶対に違うよね！
277 = "ぜ、絶対に違うよね！"

# カズマ
# とりあえず、自己紹介をしてみるか。\n可愛い女の子を演じるって思えばきっと出来る！
296 = "とりあえず、自己紹介をしてみるか。\\n可愛い女の子を演じるって思えばきっと出来る！"

# ゆんゆん
# ええと、不思議ちゃんでぶりっこで、\n一人称はゆんゆんか。
261 = "ええと、不思議ちゃんでぶりっこで、\\n一人称はゆんゆんか。"

# ゆんゆん
# はっ、はーい！　ゆんゆんでぇすっ！\nゆんゆんはねぇ、実は紅魔族なんだよぉ？
310 = "はっ、はーい！　ゆんゆんでぇすっ！\\nゆんゆんはねぇ、実は紅魔族なんだよぉ？"

# ゆんゆん
# えーっ、みんな紅魔族を知らないの？\nえーんっ、ゆんゆんかなしいよー！
267 = "えーっ、みんな紅魔族を知らないの？\\nえーんっ、ゆんゆんかなしいよー！"

# ゆんゆん
# 紅魔族っていうのは、とっても頭が良くて\n魔法が得意な人が多い種族なんだよ？
421 = "紅魔族っていうのは、とっても頭が良くて\\n魔法が得意な人が多い種族なんだよ？"

# ゆんゆん
# ゆんゆんは魔法の力で、\nみんなを幸せにしているのぉ！
330 = "ゆんゆんは魔法の力で、\\nみんなを幸せにしているのぉ！"

# ゆんゆん
# ゆんゆん、これからアイドルとして頑張るから、\nみんなも応援ガンバだぞっ？
325 = "ゆんゆん、これからアイドルとして頑張るから、\\nみんなも応援ガンバだぞっ？"

# ゆんゆん
# という、感じでしょうか。
294 = "という、感じでしょうか。"

# カズマ
# いや、まだまだいけるだろ。
245 = "いや、まだまだいけるだろ。"

# ゆんゆん
# ええ！？\nこれ以上は何をしたらいいのかわかりませんよ。
264 = "ええ！？\\nこれ以上は何をしたらいいのかわかりませんよ。"

# カズマ
# んー、そうだな。\n決めぜりふを用意して、語尾にくっつけるとか。
336 = "んー、そうだな。\\n決めぜりふを用意して、語尾にくっつけるとか。"

# めぐみん
# 語尾に「ゆんゆん」って付けたらいいと思います。\nちょっと、自己紹介でやってみてください。
423 = "語尾に「ゆんゆん」って付けたらいいと思います。\\nちょっと、自己紹介でやってみてください。"

# ゆんゆん
# う、うん、わかったよ。
251 = "う、うん、わかったよ。"

# ゆんゆん
# みんなー、ゆんゆんだゆんゆん！\nゆんゆんは紅魔族なんだゆんゆん！
319 = "みんなー、ゆんゆんだゆんゆん！\\nゆんゆんは紅魔族なんだゆんゆん！"

# めぐみん
# なんだか、ゆんゆんゆんゆんうるさいだけですね。
302 = "なんだか、ゆんゆんゆんゆんうるさいだけですね。"

# ゆんゆん
# ひどいよ！\nめぐみんがやってみろって言ったから、\nやっただけなのに！
311 = "ひどいよ！\\nめぐみんがやってみろって言ったから、\\nやっただけなのに！"

# カズマ
# ゆんゆん、頑張ったな！
326 = "ゆんゆん、頑張ったな！"

# カズマ
# ぶっつけでやった割には、\nいいキャラが出来ていたぞ！
315 = "ぶっつけでやった割には、\\nいいキャラが出来ていたぞ！"

# ゆんゆん
# そ、そうですか？\nありがとうございます！
280 = "そ、そうですか？\\nありがとうございます！"

# カズマ
# 後は、何か突拍子も無いことを言い出したり、\nボケてみると不思議感がもっと出るぞ。
360 = "後は、何か突拍子も無いことを言い出したり、\\nボケてみると不思議感がもっと出るぞ。"

# めぐみん
# それって空気を読もうと必死になりすぎて、\n空回りするゆんゆんには難易度が高いのでは。
287 = "それって空気を読もうと必死になりすぎて、\\n空回りするゆんゆんには難易度が高いのでは。"

# ゆんゆん
# か、空回りなんてしてないったら！\n私、自然に空気を読めてるよ！
270 = "か、空回りなんてしてないったら！\\n私、自然に空気を読めてるよ！"

# めぐみん
# へえ、それは知りませんでしたよ。
317 = "へえ、それは知りませんでしたよ。"

# カズマ
# どう思う、めぐみん？
298 = "どう思う、めぐみん？"

# めぐみん
# 殴りたくなりますね。
362 = "殴りたくなりますね。"

# ゆんゆん
# ええ！？
263 = "ええ！？"

# めぐみん
# ですが、私がそう思ったということは\n正解なんじゃないですか。
291 = "ですが、私がそう思ったということは\\n正解なんじゃないですか。"

# ゆんゆん
# そうなの？
285 = "そうなの？"

# カズマ
# このキャラは人を選ぶからな。\nウィズは可愛いと思っただろ？
271 = "このキャラは人を選ぶからな。\\nウィズは可愛いと思っただろ？"

# ウィズ
# はい、許されるならお持ち帰りしたいと思いました。
309 = "はい、許されるならお持ち帰りしたいと思いました。"

# ゆんゆん
# そ、そうなんですか？
281 = "そ、そうなんですか？"

# ゆんゆん
# あ、でも、鵜呑みにしちゃいけないよね。
235 = "あ、でも、鵜呑みにしちゃいけないよね。"

# ゆんゆん
# 今のは私に自信をつけさせるための\nリップサービスかもしれないんだし！
351 = "今のは私に自信をつけさせるための\\nリップサービスかもしれないんだし！"

# めぐみん
# カズマ、こういう面倒な所も受けるんですかね。
342 = "カズマ、こういう面倒な所も受けるんですかね。"

# カズマ
# さ、さあ、どうだろうな。
274 = "さ、さあ、どうだろうな。"

# カズマ（Ｍ）
# display as カズマ
# （うーん、ゆんゆんひとりに\n　こういう突飛なキャラを演じさせるのは\n　不安があるな）
426 = "（うーん、ゆんゆんひとりに\\n　こういう突飛なキャラを演じさせるのは\\n　不安があるな）"

# カズマ（Ｍ）
# display as カズマ
# （誰かをフォロー役に……）
433 = "（誰かをフォロー役に……）"

# めぐみん
# なんです、ジロジロ見て。
304 = "なんです、ジロジロ見て。"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんが適任かもしれないけど、\n　こいつとゆんゆんを絡ませるのは\n　ちょっと危険かもしれない）
429 = "（めぐみんが適任かもしれないけど、\\n　こいつとゆんゆんを絡ませるのは\\n　ちょっと危険かもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （だったら……）
428 = "（だったら……）"

# カズマ
# ウィズ、ゆんゆんと２人で、\nぶりっこキャピキャピ系百合姉妹なんてどうだ？
340 = "ウィズ、ゆんゆんと２人で、\\nぶりっこキャピキャピ系百合姉妹なんてどうだ？"

# ウィズ
# ええ、私がぶりっこでキャピキャピ！？
260 = "ええ、私がぶりっこでキャピキャピ！？"

# クリス
# そ、それはいくらなんでも\n無茶なキャラ付けじゃないかな？
282 = "そ、それはいくらなんでも\\n無茶なキャラ付けじゃないかな？"

# カズマ
# いいや、自分に持ってないキャラ性だからこそ、\n逆に上手くいくかもしれないし、２人でやれば\n凄い化学反応を起こすかもしれない。
243 = "いいや、自分に持ってないキャラ性だからこそ、\\n逆に上手くいくかもしれないし、２人でやれば\\n凄い化学反応を起こすかもしれない。"

# カズマ
# よし、ウィズはお姉様で、ゆんゆんは妹役な。\nさっそくだが、やってみてくれ。
333 = "よし、ウィズはお姉様で、ゆんゆんは妹役な。\\nさっそくだが、やってみてくれ。"

# ウィズ
# そうは言われましても、どうしたらよいのか。
286 = "そうは言われましても、どうしたらよいのか。"

# カズマ
# じゃあくっつこう。
276 = "じゃあくっつこう。"

# ゆんゆん
# ええ！　くっつく！
262 = "ええ！　くっつく！"

# カズマ
# そう、ほっぺたを密着させて、\n手を握りあうんだ。
284 = "そう、ほっぺたを密着させて、\\n手を握りあうんだ。"

# めぐみん
# なんですその、\nカズマの趣味が丸出しのシチュエーションは。
305 = "なんですその、\\nカズマの趣味が丸出しのシチュエーションは。"

# カズマ
# いやいや、俺の趣味じゃねえから！\n嫌いでもないけど！
248 = "いやいや、俺の趣味じゃねえから！\\n嫌いでもないけど！"

# ウィズ
# あの、では、ゆんゆんさん。
240 = "あの、では、ゆんゆんさん。"

# ゆんゆん
# は、はい、失礼します！
308 = "は、はい、失礼します！"

# ゆんゆん
# お、おねぇ様。\nゆんゆんは、どうやったらお姉様みたいに\nなれるんですかぁ？
268 = "お、おねぇ様。\\nゆんゆんは、どうやったらお姉様みたいに\\nなれるんですかぁ？"

# ウィズ
# えっ、ええっと……そ、それはねぇ、普段から\nいっぱいご飯食べて、いっぱい遊んで、\nきちんと眠ることなのよぉ？
266 = "えっ、ええっと……そ、それはねぇ、普段から\\nいっぱいご飯食べて、いっぱい遊んで、\\nきちんと眠ることなのよぉ？"

# ゆんゆん
# いいなぁ。お姉様は、魔法も凄いし、\nみんなの人気者じゃないですかぁー？\nゆんゆんも早くそうなりたいですー。
241 = "いいなぁ。お姉様は、魔法も凄いし、\\nみんなの人気者じゃないですかぁー？\\nゆんゆんも早くそうなりたいですー。"

# めぐみん
# 絶対無理ですね。
422 = "絶対無理ですね。"

# カズマ
# 余計なことを言うな。
354 = "余計なことを言うな。"

# ウィズ
# ゆんちゃんは、今のままでも充分可愛いわ。\n素直な気持ちを忘れなかったら、いつか\nすごいアイドルになれるわよ。
323 = "ゆんちゃんは、今のままでも充分可愛いわ。\\n素直な気持ちを忘れなかったら、いつか\\nすごいアイドルになれるわよ。"

# ゆんゆん
# 本当ですかー？\nよーしっ、ゆんゆん頑張っちゃいます！
361 = "本当ですかー？\\nよーしっ、ゆんゆん頑張っちゃいます！"

# ウィズ
# ふふふ、可愛いゆんちゃん。
314 = "ふふふ、可愛いゆんちゃん。"

# ゆんゆん
# こんな感じでしょうか。
273 = "こんな感じでしょうか。"

# カズマ
# うん、いい……。
253 = "うん、いい……。"

# ウィズ
# ではそろそろ離れても。
292 = "ではそろそろ離れても。"

# カズマ
# いや、ダメだ！\nもう少しそのままでいてくれ！
246 = "いや、ダメだ！\\nもう少しそのままでいてくれ！"

# ウィズ
# どうしてですか～。
297 = "どうしてですか～。"

# カズマ
# 俺が見ていたいからだけど？
355 = "俺が見ていたいからだけど？"

# ゆんゆん
# ええ！？　そんな理由！
265 = "ええ！？　そんな理由！"

# カズマ
# ああ、いいわー。\n目の保養になるわー。
236 = "ああ、いいわー。\\n目の保養になるわー。"

# ウィズ
# う、うう、そろそろ許してください。
250 = "う、うう、そろそろ許してください。"

# カズマ
# いいね、その照れた顔最高だ！
242 = "いいね、その照れた顔最高だ！"

# ゆんゆん
# 私、私、頭が沸騰しそうです。
418 = "私、私、頭が沸騰しそうです。"

# カズマ
# よし、そのまま気を失って、\nウィズお姉様に介抱されるシチュエーションを\nやってみようか！
332 = "よし、そのまま気を失って、\\nウィズお姉様に介抱されるシチュエーションを\\nやってみようか！"

# ウィズ
# 介抱はアクア様が適任かと。
352 = "介抱はアクア様が適任かと。"

# カズマ
# ヒールなんてかけてどうするんだよ！\nこういう時の介抱は膝枕であり、\nおでこへの優しいちゅぅだろ！
346 = "ヒールなんてかけてどうするんだよ！\\nこういう時の介抱は膝枕であり、\\nおでこへの優しいちゅぅだろ！"

# ゆんゆん
# ちゅ、ちゅぅ！？
290 = "ちゅ、ちゅぅ！？"

# カズマ
# というわけで、はい！\nおでこへのちゅぅ！
295 = "というわけで、はい！\\nおでこへのちゅぅ！"

# ウィズ
# え、ええと……。
257 = "え、ええと……。"

# ゆんゆん
# うぅ、ウィズさん……。
252 = "うぅ、ウィズさん……。"

# ウィズ
# や、やっぱり無理ですー！
322 = "や、やっぱり無理ですー！"

# ゆんゆん
# 私もですー！
420 = "私もですー！"

# カズマ
# なんだよこれくらいで、情けないな。
303 = "なんだよこれくらいで、情けないな。"

# めぐみん
# だったらカズマがやったらどうですか。
289 = "だったらカズマがやったらどうですか。"

# カズマ
# え、ゆんゆんと？　それともウィズと？
258 = "え、ゆんゆんと？　それともウィズと？"

# カズマ
# いや、気持ちは嬉しいけど、プロデューサーが\nそういうことをやっちゃダメだと思うんだよね。
247 = "いや、気持ちは嬉しいけど、プロデューサーが\\nそういうことをやっちゃダメだと思うんだよね。"

# カズマ
# でも、どうしてもって言うなら、\nや、や、やるよ？
293 = "でも、どうしてもって言うなら、\\nや、や、やるよ？"

# めぐみん
# 何を幸せな勘違いをしているんです。\nふたりは女同士でやったんですから、\nカズマは当然男冒険者とでしょう。
353 = "何を幸せな勘違いをしているんです。\\nふたりは女同士でやったんですから、\\nカズマは当然男冒険者とでしょう。"

# カズマ
# なっ！？
301 = "なっ！？"

# めぐみん
# ゆんゆんとウィズに強制をしたんですから、\n当然できますよね？　まさか、できないんですか？
327 = "ゆんゆんとウィズに強制をしたんですから、\\n当然できますよね？　まさか、できないんですか？"

# カズマ
# よし、じゃあ次はめぐみんのキャラ付けな。
331 = "よし、じゃあ次はめぐみんのキャラ付けな。"

# めぐみん
# なっ、無視をするだけならまだしも\n矛先を私に向けますか！
300 = "なっ、無視をするだけならまだしも\\n矛先を私に向けますか！"

# カズマ
# めぐみんのキャラ付けだが――
321 = "めぐみんのキャラ付けだが――"

# めぐみん
# ぶりっことか、\nそういうのは絶対にやりませんからね！
316 = "ぶりっことか、\\nそういうのは絶対にやりませんからね！"

# カズマ
# うーん、めぐみんは、そのままでいいかな。\n厨二病キャラを活かしていこうぜ。
256 = "うーん、めぐみんは、そのままでいいかな。\\n厨二病キャラを活かしていこうぜ。"

# めぐみん
# そ、そうですか。
278 = "そ、そうですか。"

# めぐみん
# まぁ、付け焼き刃で、この世の理を理解し、\n悠久の時を経て受け継がれる魔道の技を\n行使出来る者などいませんからね。
318 = "まぁ、付け焼き刃で、この世の理を理解し、\\n悠久の時を経て受け継がれる魔道の技を\\n行使出来る者などいませんからね。"

# カズマ
# うん、言ってる意味は良くわからないけど、\nだいたいそういう感じのやつ。
254 = "うん、言ってる意味は良くわからないけど、\\nだいたいそういう感じのやつ。"

# めぐみん
# し、しかし、少しぐらいでしたら、わ、私も\nキャラ付けしてもらってもいいのですよ？
275 = "し、しかし、少しぐらいでしたら、わ、私も\\nキャラ付けしてもらってもいいのですよ？"

# めぐみん
# ゆんゆんにはあって、私にだけ無いなんて、\nちょっと不公平ですし。
328 = "ゆんゆんにはあって、私にだけ無いなんて、\\nちょっと不公平ですし。"

# カズマ
# いやだって、お前は今のままでも充分キャラが\n立っているし、これ以上何か付け加えたら、\nせっかくの厨二病が薄れちまうよ。
249 = "いやだって、お前は今のままでも充分キャラが\\n立っているし、これ以上何か付け加えたら、\\nせっかくの厨二病が薄れちまうよ。"

# めぐみん
# そ、そうですか。\nそ、それなら仕方がありませんね。
279 = "そ、そうですか。\\nそ、それなら仕方がありませんね。"

# アクア
# それで私は私は？
288 = "それで私は私は？"

# カズマ
# お前は……そうだな、\nもっと女神というのをアピールしてくれ。
269 = "お前は……そうだな、\\nもっと女神というのをアピールしてくれ。"

# アクア
# わかったわ！\n私の溢れんばかりの神々しさを前面に\n押し出せってことね？
335 = "わかったわ！\\n私の溢れんばかりの神々しさを前面に\\n押し出せってことね？"

# カズマ（Ｍ）
# display as カズマ
# （自分のことを女神だって豪語している人間が\n　どんな風に見られているか、わかってるのか？）
432 = "（自分のことを女神だって豪語している人間が\\n　どんな風に見られているか、わかってるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （答えは、『痛い』だ）
431 = "（答えは、『痛い』だ）"

# カズマ（Ｍ）
# display as カズマ
# （アクアは、そんな痛いキャラクターで\n　売りだす事にする。もちろん、本人にそのことを\n　言うつもりはない）
430 = "（アクアは、そんな痛いキャラクターで\\n　売りだす事にする。もちろん、本人にそのことを\\n　言うつもりはない）"

# アクア
# ふっふっふ、私は女神！　女神アクアよ！\nみんな私を崇めなさい！！
313 = "ふっふっふ、私は女神！　女神アクアよ！\\nみんな私を崇めなさい！！"

# アクア
# うーん、ちょっと神々しさが足りないかしら。\nポーズから考えた方がいいかもしれないわね。
255 = "うーん、ちょっと神々しさが足りないかしら。\\nポーズから考えた方がいいかもしれないわね。"

# カズマ（Ｍ）
# display as カズマ
# （これで、みんなからあだ名で女神と呼ばれたら、\n　アクアも調子に乗って頑張るだろう）
427 = "（これで、みんなからあだ名で女神と呼ばれたら、\\n　アクアも調子に乗って頑張るだろう）"

# カズマ
# ああそうだ。アクア、\n前にも言ったがＮＧなことを改めて言っておく。
238 = "ああそうだ。アクア、\\n前にも言ったがＮＧなことを改めて言っておく。"

# カズマ
# これはみんなのアイドル活動なんだし、\nアクシズ教へ勧誘は絶対ダメだからな。\nいいか絶対するなよ？
272 = "これはみんなのアイドル活動なんだし、\\nアクシズ教へ勧誘は絶対ダメだからな。\\nいいか絶対するなよ？"

# アクア
# そ、そんなことするわけないでしょ！
283 = "そ、そんなことするわけないでしょ！"

# カズマ（Ｍ）
# display as カズマ
# （……本当に大丈夫なんだろうか？）
425 = "（……本当に大丈夫なんだろうか？）"

# クリス
# ねぇ、色々なキャラクター付けをしているけど、\n何だかまとまりが無いような気がするんだよね。\nこれで本当に大丈夫なのかな？
306 = "ねぇ、色々なキャラクター付けをしているけど、\\n何だかまとまりが無いような気がするんだよね。\\nこれで本当に大丈夫なのかな？"

# カズマ
# ああ、これでいいんだ。\n将来的には、そういう個性を武器に戦い抜く、\nセンターを決める総選挙というイベントがあるしな。
237 = "ああ、これでいいんだ。\\n将来的には、そういう個性を武器に戦い抜く、\\nセンターを決める総選挙というイベントがあるしな。"

# カズマ
# アイドル同士、\n切磋琢磨して競い合うのも面白いんだ！
337 = "アイドル同士、\\n切磋琢磨して競い合うのも面白いんだ！"

[selections]
244 = "いや、まだまだいけるだろ"
424 = "頑張ったな！"
299 = "どう思うめぐみん？"
