# st03b_05.txt.scn

[info]
0 = ""

[characters]
440 = "カズマ"
448 = "ダクネス"
445 = "カズマ（Ｍ）"
421 = "めぐみん"
425 = "ゆんゆん"
446 = "クリス"
438 = "ウィズ"
436 = "アクア"

[character_subs]
# 440 = "カズマ"

[script]
# lines: 168

# カズマ
# というわけで、ダンスの特訓なわけだが。
394 = "というわけで、ダンスの特訓なわけだが。"

# ダクネス
# カズマは、ダンスの心得があるのか？
444 = "カズマは、ダンスの心得があるのか？"

# カズマ（Ｍ）
# display as カズマ
# （無い！）
581 = "（無い！）"

# カズマ（Ｍ）
# display as カズマ
# （持ち合わせる知識もゲームやアニメなんかで\n　見た程度だ！）
579 = "（持ち合わせる知識もゲームやアニメなんかで\\n　見た程度だ！）"

# めぐみん
# ちょっと、黙っていないで何か言ってくださいよ。
388 = "ちょっと、黙っていないで何か言ってくださいよ。"

# カズマ
# ああ、ええと、\nこの中でダンスの経験があるやつは？
324 = "ああ、ええと、\\nこの中でダンスの経験があるやつは？"

# ゆんゆん
# 学校の行事でちょっとやったくらいです。
460 = "学校の行事でちょっとやったくらいです。"

# めぐみん
# 私も同じですね。
547 = "私も同じですね。"

# クリス
# あたしは、まったく経験無し。
327 = "あたしは、まったく経験無し。"

# ウィズ
# すみません、私もです。
366 = "すみません、私もです。"

# アクア
# 私は任せて！\n踊りならお手の物よ！
546 = "私は任せて！\\n踊りならお手の物よ！"

# カズマ
# 宴会芸レベルだけどな。
461 = "宴会芸レベルだけどな。"

# ダクネス
# それでも花鳥風月を披露しているときの\nアクアの動きは見事なものだ。
381 = "それでも花鳥風月を披露しているときの\\nアクアの動きは見事なものだ。"

# めぐみん
# 何よりも、あのデストロイヤーの指芸！\nあんなに精細に指を動かせるなんて、\n尊敬してしまいます！
454 = "何よりも、あのデストロイヤーの指芸！\\nあんなに精細に指を動かせるなんて、\\n尊敬してしまいます！"

# アクア
# 私は、芸に関しては妥協をしないの！
545 = "私は、芸に関しては妥協をしないの！"

# カズマ
# いやいや、その努力を違う所に向けろよ。
341 = "いやいや、その努力を違う所に向けろよ。"

# クリス
# そういえば、ダクネスはどうなの？\nあたし的には、ダクネスが本命なんだけど。
373 = "そういえば、ダクネスはどうなの？\\nあたし的には、ダクネスが本命なんだけど。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、そうか。\n　中身はアレだけど、名家のお嬢様だもんな）
556 = "（ああ、そうか。\\n　中身はアレだけど、名家のお嬢様だもんな）"

# ダクネス
# ま、まあ、それなりに経験はあるが、\nアイドルがするダンスとはまた違うものだと思うぞ。
416 = "ま、まあ、それなりに経験はあるが、\\nアイドルがするダンスとはまた違うものだと思うぞ。"

# カズマ
# それでも経験があるのは頼もしいさ。
380 = "それでも経験があるのは頼もしいさ。"

# ダクネス
# あまり期待をされても困るのだが。
331 = "あまり期待をされても困るのだが。"

# カズマ（Ｍ）
# display as カズマ
# （さて問題はここからだ。\n　発声の特訓の時はどうにかなったが、踊りは……）
564 = "（さて問題はここからだ。\\n　発声の特訓の時はどうにかなったが、踊りは……）"

# クリス
# それで？　アイドルがするダンスって\nどういうものなのかな。
382 = "それで？　アイドルがするダンスって\\nどういうものなのかな。"

# カズマ
# ああ、ええと。
325 = "ああ、ええと。"

# カズマ（Ｍ）
# display as カズマ
# （くっ、こうなったらあたって砕けろだ！）
561 = "（くっ、こうなったらあたって砕けろだ！）"

# カズマ
# と、とりあえず、簡単な振り付けを考えたから\nみんなも真似してみてくれ。
393 = "と、とりあえず、簡単な振り付けを考えたから\\nみんなも真似してみてくれ。"

# カズマ
# よっ……んっ……で、ここで、腕をくるくるっと！
429 = "よっ……んっ……で、ここで、腕をくるくるっと！"

# カズマ
# そして、ここで軽くジャンプして、決めっと！！
377 = "そして、ここで軽くジャンプして、決めっと！！"

# カズマ
# わ、わかったかみんな？
431 = "わ、わかったかみんな？"

# クリス
# え、ええと……。
347 = "え、ええと……。"

# ゆんゆん
# た、タコ……かな？
386 = "た、タコ……かな？"

# めぐみん
# いえ、違いますよ。\nあれはデストロイヤーの動きを模していたんです。\nたぶん。
335 = "いえ、違いますよ。\\nあれはデストロイヤーの動きを模していたんです。\\nたぶん。"

# アクア
# あんた、本当にダメね。\nデストロイヤーはこうっ！　そしてこうっ！！
333 = "あんた、本当にダメね。\\nデストロイヤーはこうっ！　そしてこうっ！！"

# めぐみん
# おお、またその指芸にお目にかかれるとは！
357 = "おお、またその指芸にお目にかかれるとは！"

# ゆんゆん
# す、すごい、本当にデストロイヤーに\nそっくりです！
364 = "す、すごい、本当にデストロイヤーに\\nそっくりです！"

# カズマ
# って、違う！\n俺はデストロイヤーの真似をしてたんじゃないの！
390 = "って、違う！\\n俺はデストロイヤーの真似をしてたんじゃないの！"

# ウィズ
# そ、そうですよ！\nアイドルのダンスというのは、先ほどみたいな\n変な動きをするものなんですよね？
367 = "そ、そうですよ！\\nアイドルのダンスというのは、先ほどみたいな\\n変な動きをするものなんですよね？"

# カズマ
# へ、変な！
413 = "へ、変な！"

# ウィズ
# あ、あれ？　違いましたか！？
322 = "あ、あれ？　違いましたか！？"

# クリス
# まさかとは思うけど、\nキミってダンスの素人だったりする？
418 = "まさかとは思うけど、\\nキミってダンスの素人だったりする？"

# カズマ
# は、はい……。
401 = "は、はい……。"

# めぐみん
# それなのに、私たちにダンスを\n教えるつもりだったのですか？
383 = "それなのに、私たちにダンスを\\n教えるつもりだったのですか？"

# カズマ
# はい、すみません。
405 = "はい、すみません。"

# カズマ（Ｍ）
# display as カズマ
# （あぁぁーー！！\n　今すぐ消えてなくなりたい！！）
555 = "（あぁぁーー！！\\n　今すぐ消えてなくなりたい！！）"

# アクア
# まったく、しょうがないわね。\nじゃあ、私がお手本を見せてあげるわっ！
419 = "まったく、しょうがないわね。\\nじゃあ、私がお手本を見せてあげるわっ！"

# カズマ（Ｍ）
# display as カズマ
# （どうして俺を見る）
567 = "（どうして俺を見る）"

# アクア
# カズマの代わりに、私が、見せて、あげるわっ！
443 = "カズマの代わりに、私が、見せて、あげるわっ！"

# カズマ（Ｍ）
# display as カズマ
# （なるほど、センターアピールか……うざい）
568 = "（なるほど、センターアピールか……うざい）"

# アクア
# ダンスなんてものはね、難しく考えないで\n表現したいことを思いながら体を動かせば\nそれっぽくなるのよ。
449 = "ダンスなんてものはね、難しく考えないで\\n表現したいことを思いながら体を動かせば\\nそれっぽくなるのよ。"

# カズマ
# おお、確かにそれっぽい！
358 = "おお、確かにそれっぽい！"

# めぐみん
# ええ、とてもそれっぽいです！
348 = "ええ、とてもそれっぽいです！"

# アクア
# さっきのカズマのタコ踊りは、\nきっとこういう動きをしたかったのよね？\nよっと。
363 = "さっきのカズマのタコ踊りは、\\nきっとこういう動きをしたかったのよね？\\nよっと。"

# カズマ
# そう、それ！
372 = "そう、それ！"

# ゆんゆん
# あの、うねうねした気持ち悪い動きは、\nこんな可愛らしいダンスだったんですね。
329 = "あの、うねうねした気持ち悪い動きは、\\nこんな可愛らしいダンスだったんですね。"

# カズマ（Ｍ）
# display as カズマ
# （気持ち悪いって……）
580 = "（気持ち悪いって……）"

# アクア
# ほっ、はぁっ。\nそして、最後に、花鳥風月！！
415 = "ほっ、はぁっ。\\nそして、最後に、花鳥風月！！"

# カズマ（Ｍ）
# display as カズマ
# （それはいらんっ）
565 = "（それはいらんっ）"

# ダクネス
# いやあ、見事だったぞアクア！
339 = "いやあ、見事だったぞアクア！"

# ウィズ
# とても良い物を見せていただきました。
395 = "とても良い物を見せていただきました。"

# アクア
# ねえ、カズマ。\nこれならアクシズ教の宣伝になると思わない？
400 = "ねえ、カズマ。\\nこれならアクシズ教の宣伝になると思わない？"

# カズマ
# は？　アクシズ教？
410 = "は？　アクシズ教？"

# アクア
# あ……。
321 = "あ……。"

# カズマ
# おい、お前まさか、くだらない宣伝のために\nセンターを狙ってるわけじゃないだろうな。
354 = "おい、お前まさか、くだらない宣伝のために\\nセンターを狙ってるわけじゃないだろうな。"

# アクア
# え？　ち、違うわよ！\nただ、ウィズに負けたくないだけよ。\nほ、本当よ！
352 = "え？　ち、違うわよ！\\nただ、ウィズに負けたくないだけよ。\\nほ、本当よ！"

# カズマ（Ｍ）
# display as カズマ
# （こいつ、何かたくらんでやがるな……）
562 = "（こいつ、何かたくらんでやがるな……）"

# カズマ
# あのなぁ、１つ注意しておくが、あからさまな\nアクシズ教への勧誘はやめてくれよ。
330 = "あのなぁ、１つ注意しておくが、あからさまな\\nアクシズ教への勧誘はやめてくれよ。"

# カズマ
# それに、今はみんなとダンスをすることに\n集中するんだ。
384 = "それに、今はみんなとダンスをすることに\\n集中するんだ。"

# アクア
# わ、わかってるわよ。
432 = "わ、わかってるわよ。"

# カズマ
# よし、みんなもさっきアクアがやった通りに\n踊ってみてくれ。
427 = "よし、みんなもさっきアクアがやった通りに\\n踊ってみてくれ。"

# ウィズ
# わ、私にも出来るでしょうか……。
433 = "わ、私にも出来るでしょうか……。"

# カズマ
# アクア、お前が手本になってみんなに\n教えてやってくれないか？
437 = "アクア、お前が手本になってみんなに\\n教えてやってくれないか？"

# アクア
# 任されたわ！
452 = "任されたわ！"

# カズマ（Ｍ）
# display as カズマ
# （ふぅ、アクアがダンスが得意で良かったぜ。\n　俺のへっぽこダンスをそのまま踊らせたら、\n　笑い物になっちまうしな）
569 = "（ふぅ、アクアがダンスが得意で良かったぜ。\\n　俺のへっぽこダンスをそのまま踊らせたら、\\n　笑い物になっちまうしな）"

# カズマ（Ｍ）
# display as カズマ
# （俺も、プロデューサーとして、\n　ちゃんと指導出来るようしっかりしないとな）
576 = "（俺も、プロデューサーとして、\\n　ちゃんと指導出来るようしっかりしないとな）"

# めぐみん
# んっ、よっ、むむむ……これは。
435 = "んっ、よっ、むむむ……これは。"

# ゆんゆん
# めぐみん、やっぱり厳しいよ。
422 = "めぐみん、やっぱり厳しいよ。"

# カズマ
# なんだなんだ？　２人とも動きが固いぞ。\nアイドルって言うのは、ファンを元気にしてくれる\n存在なんだ。
399 = "なんだなんだ？　２人とも動きが固いぞ。\\nアイドルって言うのは、ファンを元気にしてくれる\\n存在なんだ。"

# カズマ
# そんなモジモジした踊りだと、見ているみんなが\n楽しめないだろ。
385 = "そんなモジモジした踊りだと、見ているみんなが\\n楽しめないだろ。"

# カズマ（Ｍ）
# display as カズマ
# （うーん……めぐみんとゆんゆんは、このアイドル\n　プロジェクトの要でもあるんだし、ここは居残り\n　特訓でしごくしかないな）
559 = "（うーん……めぐみんとゆんゆんは、このアイドル\\n　プロジェクトの要でもあるんだし、ここは居残り\\n　特訓でしごくしかないな）"

# クリス
# はっ……んっと、そしてここでターンっ！
409 = "はっ……んっと、そしてここでターンっ！"

# カズマ
# おーっ、なかなかやるじゃないかクリス。\nさすが盗賊だな、軽快で時に豪快な動きは、\n見ていて気持ちいいぞ。
359 = "おーっ、なかなかやるじゃないかクリス。\\nさすが盗賊だな、軽快で時に豪快な動きは、\\n見ていて気持ちいいぞ。"

# クリス
# 体を動かすことには自信があるからね。\nほっと！
453 = "体を動かすことには自信があるからね。\\nほっと！"

# カズマ（Ｍ）
# display as カズマ
# （おおっ、スカートがひらりと！）
560 = "（おおっ、スカートがひらりと！）"

# クリス
# どう？　見事なもんでしょ？
397 = "どう？　見事なもんでしょ？"

# めぐみん
# ちょっとクリス、\nそんなに足を高く上げたら見えてしまいますよ。
389 = "ちょっとクリス、\\nそんなに足を高く上げたら見えてしまいますよ。"

# クリス
# ひゃああっ！　み、見たの！？
411 = "ひゃああっ！　み、見たの！？"

# カズマ
# いやいや、見てない見てない！\nというか、ギリギリで見えなかった！
343 = "いやいや、見てない見てない！\\nというか、ギリギリで見えなかった！"

# クリス
# ほ、本当だね。\nその言葉、信じるよ。
414 = "ほ、本当だね。\\nその言葉、信じるよ。"

# カズマ（Ｍ）
# display as カズマ
# （やっぱり、スカートにはもう一工夫必要か）
571 = "（やっぱり、スカートにはもう一工夫必要か）"

# ウィズ
# はぁはぁっ……んっ……あらら……\nど、どうしましょう……。
404 = "はぁはぁっ……んっ……あらら……\\nど、どうしましょう……。"

# カズマ
# ウィズ、大丈夫か？\nなんか苦戦しているみたいだけど。
439 = "ウィズ、大丈夫か？\\nなんか苦戦しているみたいだけど。"

# ウィズ
# は、はい……アクア様の動きを一生懸命\n真似しているんですが、難しすぎて……。
402 = "は、はい……アクア様の動きを一生懸命\\n真似しているんですが、難しすぎて……。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、なるほど。\n　俺がダンスを見せてるときって\n　みんなこういう気持ちだったんだな）
557 = "（ああ、なるほど。\\n　俺がダンスを見せてるときって\\n　みんなこういう気持ちだったんだな）"

# ウィズ
# 私、下手ですよね？\n才能が無いのかもしれません。
544 = "私、下手ですよね？\\n才能が無いのかもしれません。"

# カズマ
# いやいや、そこそこ出来てるぞ。
340 = "いやいや、そこそこ出来てるぞ。"

# ウィズ
# そ、そうなんですか？
368 = "そ、そうなんですか？"

# カズマ
# ああ、最初は誰でもそんなもんなんだし、\n真面目に取り組んでいるウィズだったら、\nちゃんと出来るようになるさ。
326 = "ああ、最初は誰でもそんなもんなんだし、\\n真面目に取り組んでいるウィズだったら、\\nちゃんと出来るようになるさ。"

# ウィズ
# そうだといいのですが。
374 = "そうだといいのですが。"

# カズマ
# 大丈夫だって。\n正直に言って、俺より上手いしさ。
459 = "大丈夫だって。\\n正直に言って、俺より上手いしさ。"

# ウィズ
# そ、そんな……カズマさんも、お上手でしたよ。
371 = "そ、そんな……カズマさんも、お上手でしたよ。"

# カズマ
# いや、そのフォローは傷をえぐるだけだから……。
337 = "いや、そのフォローは傷をえぐるだけだから……。"

# ウィズ
# す、すみません！
365 = "す、すみません！"

# カズマ
# と、とにかく、その調子で頑張ってくれ。
392 = "と、とにかく、その調子で頑張ってくれ。"

# カズマ
# 出来るように、もっと練習しよう！
455 = "出来るように、もっと練習しよう！"

# ウィズ
# は、はい！
403 = "は、はい！"

# カズマ
# 努力は決して裏切らない！\nわからない時はそのままにせず、\n仲間に質問したり、色々考えるんだ！
456 = "努力は決して裏切らない！\\nわからない時はそのままにせず、\\n仲間に質問したり、色々考えるんだ！"

# カズマ
# その努力が、\nウィズを何倍にも輝かせてくれる。
378 = "その努力が、\\nウィズを何倍にも輝かせてくれる。"

# ウィズ
# カズマさんって、\n人を持ち上げるのはとてもお上手ですよね？
442 = "カズマさんって、\\n人を持ち上げるのはとてもお上手ですよね？"

# カズマ（Ｍ）
# display as カズマ
# （持ち上げるの……は？）
578 = "（持ち上げるの……は？）"

# ウィズ
# みなさんの足を引っ張らないように、\n私、もっともっと努力しますね。
420 = "みなさんの足を引っ張らないように、\\n私、もっともっと努力しますね。"

# カズマ
# お、おう、頑張れ！
353 = "お、おう、頑張れ！"

# カズマ
# いいか、ダンスのコツは笑顔だ！
334 = "いいか、ダンスのコツは笑顔だ！"

# カズマ
# 踊ってるアクアを見てみろ。\n終始笑顔だろう？
553 = "踊ってるアクアを見てみろ。\\n終始笑顔だろう？"

# カズマ
# 自信なさげに踊っても、\n見る側も踊る側も楽しくない。\n下手でも、一生懸命笑顔でやれば道は開ける！
551 = "自信なさげに踊っても、\\n見る側も踊る側も楽しくない。\\n下手でも、一生懸命笑顔でやれば道は開ける！"

# ウィズ
# 笑顔でいたら道は開ける。
549 = "笑顔でいたら道は開ける。"

# ウィズ
# ありがとうございます！　私頑張ります！
332 = "ありがとうございます！　私頑張ります！"

# カズマ
# いつか、ウィズの笑顔に癒やされたり、\n励まされるファンがきっと出来る。\nだから笑え！　笑うんだ！
336 = "いつか、ウィズの笑顔に癒やされたり、\\n励まされるファンがきっと出来る。\\nだから笑え！　笑うんだ！"

# ウィズ
# はい！　ふふふっ。
408 = "はい！　ふふふっ。"

# カズマ
# よーし、いい笑顔だ！
430 = "よーし、いい笑顔だ！"

# ウィズ
# では、もう一度最初からやってみます。\nよっ……ええっと次は……。
391 = "では、もう一度最初からやってみます。\\nよっ……ええっと次は……。"

# カズマ
# 腕は、もうちょっと上げたほうが、\n綺麗に見えると思うぞ。
550 = "腕は、もうちょっと上げたほうが、\\n綺麗に見えると思うぞ。"

# ウィズ
# はい！　ありがとうございます。
406 = "はい！　ありがとうございます。"

# カズマ
# ああ、あとこのポーズの時は、\nもっと……そう腰を突き出して。
323 = "ああ、あとこのポーズの時は、\\nもっと……そう腰を突き出して。"

# ウィズ
# こ、こうですか？　んぅっ！
361 = "こ、こうですか？　んぅっ！"

# カズマ
# おーっ、結構様になってきたぞウィズ。
360 = "おーっ、結構様になってきたぞウィズ。"

# ウィズ
# ふふふ、これもみんな、\nカズマさんのご指導のおかげです。
412 = "ふふふ、これもみんな、\\nカズマさんのご指導のおかげです。"

# カズマ
# いやいや、ウィズが頑張った成果だよ。
342 = "いやいや、ウィズが頑張った成果だよ。"

# ダクネス
# カズマ、私のダンスも見てくれないか？\nよっ、はっ、んっ……。
441 = "カズマ、私のダンスも見てくれないか？\\nよっ、はっ、んっ……。"

# カズマ
# おお、さすが経験者。\nアクアにはない優雅さを感じるぞ。
356 = "おお、さすが経験者。\\nアクアにはない優雅さを感じるぞ。"

# ダクネス
# そ、それは褒めすぎだろう。
370 = "そ、それは褒めすぎだろう。"

# ダクネス
# ええと、確かここは、足をこう運んで、腕は……。
349 = "ええと、確かここは、足をこう運んで、腕は……。"

# カズマ
# …………。
320 = "…………。"

# ダクネス
# ここでターンをして……。
362 = "ここでターンをして……。"

# カズマ
# うまいじゃないか、ララティーナ。
345 = "うまいじゃないか、ララティーナ。"

# ダクネス
# そ、その名前で呼ぶな！！
369 = "そ、その名前で呼ぶな！！"

# カズマ（Ｍ）
# display as カズマ
# （ふーむ、ダクネスはやはり貴族のたしなみとして\n　ダンスをやっていただけはあるな）
570 = "（ふーむ、ダクネスはやはり貴族のたしなみとして\\n　ダンスをやっていただけはあるな）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズは、まだまだ努力が必要だけど、\n　これなら最低限には仕上げてくれるだろう）
574 = "（ウィズは、まだまだ努力が必要だけど、\\n　これなら最低限には仕上げてくれるだろう）"

# カズマ（Ｍ）
# display as カズマ
# （アクアは言わずもがな――）
573 = "（アクアは言わずもがな――）"

# カズマ（Ｍ）
# display as カズマ
# （クリスは動きこそ雑だけど、\n　それがいい味になってるからよし！）
575 = "（クリスは動きこそ雑だけど、\\n　それがいい味になってるからよし！）"

# カズマ（Ｍ）
# display as カズマ
# （さて、問題は……）
563 = "（さて、問題は……）"

# めぐみん
# よっ……くっ……んんっ……。
428 = "よっ……くっ……んんっ……。"

# ゆんゆん
# あっ……きゃっ……ダメっ……。
328 = "あっ……きゃっ……ダメっ……。"

# カズマ
# おい、それは紅魔族のコントか？
355 = "おい、それは紅魔族のコントか？"

# ゆんゆん
# コント！？
447 = "コント！？"

# めぐみん
# ま、真面目にやっていますよ。
417 = "ま、真面目にやっていますよ。"

# カズマ
# %fsyogen;そのわりに、さっきと全然変わってないじゃないか。\nモジモジして、動きがぎこちないぞ。
25 = "%fsyogen;そのわりに、さっきと全然変わってないじゃないか。\\nモジモジして、動きがぎこちないぞ。"

# カズマ（Ｍ）
# display as カズマ
# （ん？　モジモジして動きがぎこちない？\n　それはどういう理由でだ？）
572 = "（ん？　モジモジして動きがぎこちない？\\n　それはどういう理由でだ？）"

# カズマ（Ｍ）
# display as カズマ
# （……これは重要な証拠になるかもしれない。\n　情況証拠として覚えておこう）
554 = "（……これは重要な証拠になるかもしれない。\\n　情況証拠として覚えておこう）"

# カズマ
# もっと足を上げて躍動感を出すんだ！\nそして、ジャンプの時はもっと高く飛ぶ事を\n意識しろ！
424 = "もっと足を上げて躍動感を出すんだ！\\nそして、ジャンプの時はもっと高く飛ぶ事を\\n意識しろ！"

# めぐみん
# だそうですよ、ゆんゆん。
387 = "だそうですよ、ゆんゆん。"

# ゆんゆん
# わ、私に振らないでよ！
434 = "わ、私に振らないでよ！"

# カズマ（Ｍ）
# display as カズマ
# （２人とも、\n　やる気は無いわけじゃないみたいなんだが、\n　全然結果に繋がってないな）
582 = "（２人とも、\\n　やる気は無いわけじゃないみたいなんだが、\\n　全然結果に繋がってないな）"

# カズマ（Ｍ）
# display as カズマ
# （動きがぎこちなくて、\n　なんか無理しているみたいなんだが）
577 = "（動きがぎこちなくて、\\n　なんか無理しているみたいなんだが）"

# カズマ
# なぁ、実は紅魔族って、\n身体を動かすのが苦手なのか？
398 = "なぁ、実は紅魔族って、\\n身体を動かすのが苦手なのか？"

# めぐみん
# はい！　はいはい！　実はそうなんです！
407 = "はい！　はいはい！　実はそうなんです！"

# ゆんゆん
# うんうん！
346 = "うんうん！"

# めぐみん
# 苦手と言うより、弱点だと言っても\n差し支えないでしょう！
552 = "苦手と言うより、弱点だと言っても\\n差し支えないでしょう！"

# めぐみん
# 私を見てください！\nひ弱なので魔法使いを選ばざるを得なかったのが\nいい証拠じゃないですか！
548 = "私を見てください！\\nひ弱なので魔法使いを選ばざるを得なかったのが\\nいい証拠じゃないですか！"

# カズマ
# えっ、お前、爆裂魔法が好きだから、\n魔法使いになったんじゃなかったっけ？
351 = "えっ、お前、爆裂魔法が好きだから、\\n魔法使いになったんじゃなかったっけ？"

# めぐみん
# うぉほん！　それは置いといて、\n私が爆裂魔法を撃つとどうなります？
344 = "うぉほん！　それは置いといて、\\n私が爆裂魔法を撃つとどうなります？"

# カズマ
# そりゃあ、魔力切れでぶっ倒れるけど……。
379 = "そりゃあ、魔力切れでぶっ倒れるけど……。"

# めぐみん
# そうです！　魔法１つで倒れてしまうほど\n紅魔族はか弱いんです！
375 = "そうです！　魔法１つで倒れてしまうほど\\n紅魔族はか弱いんです！"

# カズマ
# いや、それは爆裂魔法を撃つから――
338 = "いや、それは爆裂魔法を撃つから――"

# めぐみん
# とにかく！\n紅魔族にはダンスはハードすぎるので、\nご了承ください。
396 = "とにかく！\\n紅魔族にはダンスはハードすぎるので、\\nご了承ください。"

# めぐみん
# ゆんゆんもそうですよね？
426 = "ゆんゆんもそうですよね？"

# ゆんゆん
# えっ……あ、はい、そうみたいです！
350 = "えっ……あ、はい、そうみたいです！"

# カズマ（Ｍ）
# display as カズマ
# （だからといって、アイドルなんだし\n　ダンスをしなくていいってわけには\n　いかないしなぁ……）
566 = "（だからといって、アイドルなんだし\\n　ダンスをしなくていいってわけには\\n　いかないしなぁ……）"

# カズマ（Ｍ）
# display as カズマ
# （うーむ……\n　これは基礎体力をつける必要がありそうだな）
558 = "（うーむ……\\n　これは基礎体力をつける必要がありそうだな）"

[selections]
376 = "そこそこ出来てるぜ"
423 = "もっと練習しよう"
450 = "ダンスのコツは笑顔だ！"
