# st03a_07.txt.scn

[info]
0 = ""

[characters]
402 = "ダクネス"
396 = "カズマ"
383 = "めぐみん"
386 = "ゆんゆん"
394 = "アクア"
400 = "クリス"
399 = "カズマ（Ｍ）"

[character_subs]
# 396 = "カズマ"

[script]
# lines: 163

# ダクネス
# それで、具体的にはどんなこと考えているんだ？
335 = "それで、具体的にはどんなこと考えているんだ？"

# カズマ
# ああ、それなんだが――
280 = "ああ、それなんだが――"

# カズマ
# お前達を、歌って踊れる超接近アイドルとして\n売り出すことにする！
311 = "お前達を、歌って踊れる超接近アイドルとして\\n売り出すことにする！"

# めぐみん
# 歌って踊れる――
425 = "歌って踊れる――"

# ゆんゆん
# 超接近アイドル？
510 = "超接近アイドル？"

# ダクネス
# 歌って踊るというのはなんとなくわかるのだが、\nその超接近とはどういうことだ？
424 = "歌って踊るというのはなんとなくわかるのだが、\\nその超接近とはどういうことだ？"

# アクア
# まさか、\nいかがわしいことじゃないでしょうね。
377 = "まさか、\\nいかがわしいことじゃないでしょうね。"

# カズマ
# 大切なアイドルにそんなことさせるわけないだろ。
414 = "大切なアイドルにそんなことさせるわけないだろ。"

# カズマ
# 超接近というのはだな、高嶺の花っぽく感じる\nアイドルが、寄り添えるぐらい身近な距離に\nいてくれることだ。
509 = "超接近というのはだな、高嶺の花っぽく感じる\\nアイドルが、寄り添えるぐらい身近な距離に\\nいてくれることだ。"

# カズマ
# アイドルを応援してくれる人たちにとっては、\n目の前でアイドルと交流出来て嬉しいし――
393 = "アイドルを応援してくれる人たちにとっては、\\n目の前でアイドルと交流出来て嬉しいし――"

# カズマ
# アイドルも、自分たちのファンの熱気を直に\n感じられて励みになるって、お互いＷｉｎ－Ｗｉｎな\n関係を生み出せる効果もある……はずだ。
392 = "アイドルも、自分たちのファンの熱気を直に\\n感じられて励みになるって、お互いＷｉｎ－Ｗｉｎな\\n関係を生み出せる効果もある……はずだ。"

# クリス
# へぇ、ちゃんと意味があるんだね。
369 = "へぇ、ちゃんと意味があるんだね。"

# カズマ（Ｍ）
# display as カズマ
# （日本ではもう当たり前すぎる事なんだが、\n　こっちでは、みんな初めて経験するだろうし、\n　確実に受けるはずだ！）
522 = "（日本ではもう当たり前すぎる事なんだが、\\n　こっちでは、みんな初めて経験するだろうし、\\n　確実に受けるはずだ！）"

# カズマ
# まぁ難しく考えなくていいよ。\nサイン会や握手会でちょっと楽しくおしゃべりを\nするぐらいだし。
370 = "まぁ難しく考えなくていいよ。\\nサイン会や握手会でちょっと楽しくおしゃべりを\\nするぐらいだし。"

# ゆんゆん
# わ、私にできるかな。\nどう思う？　めぐみん。
390 = "わ、私にできるかな。\\nどう思う？　めぐみん。"

# めぐみん
# 知りませんし、興味ありません。
502 = "知りませんし、興味ありません。"

# ゆんゆん
# ええ、友達でしょ！\nアドバイスくらいしてよ！
301 = "ええ、友達でしょ！\\nアドバイスくらいしてよ！"

# ダクネス
# まあまあ。\n不安があるなら、後で一緒に特訓しようじゃないか。
375 = "まあまあ。\\n不安があるなら、後で一緒に特訓しようじゃないか。"

# ゆんゆん
# え、でも、ご迷惑じゃないんですか？
298 = "え、でも、ご迷惑じゃないんですか？"

# ダクネス
# そんなことはないぞ。\nゆんゆんとはもっと親しくなりたいと\n思っていたしな。
338 = "そんなことはないぞ。\\nゆんゆんとはもっと親しくなりたいと\\n思っていたしな。"

# ゆんゆん
# あっ、もしかして、今のはリップサービスなのかな。\nだったら、真に受けちゃダメだよね。
285 = "あっ、もしかして、今のはリップサービスなのかな。\\nだったら、真に受けちゃダメだよね。"

# ゆんゆん
# でも、ダクネスさんはとても優しい人だし。
352 = "でも、ダクネスさんはとても優しい人だし。"

# ゆんゆん
# ううん、そういう人は色々抱え込んでそうだから、\n本当の気持ちでも、お断りした方が……。
294 = "ううん、そういう人は色々抱え込んでそうだから、\\n本当の気持ちでも、お断りした方が……。"

# ダクネス
# い、いや、ゆんゆん？
290 = "い、いや、ゆんゆん？"

# ゆんゆん
# そうだ、近い日は予定が埋まってるかも\nしれないから、ずっと先の予定で約束すれば！
329 = "そうだ、近い日は予定が埋まってるかも\\nしれないから、ずっと先の予定で約束すれば！"

# めぐみん
# …………。
276 = "…………。"

# ゆんゆん
# うぅ、それもダメかも。
293 = "うぅ、それもダメかも。"

# ゆんゆん
# なんだゆんゆんは、私との約束を後回しにするのか。
358 = "なんだゆんゆんは、私との約束を後回しにするのか。"

# ゆんゆん
# とか、思われそうだし。
353 = "とか、思われそうだし。"

# めぐみん
# イラっ！
395 = "イラっ！"

# カズマ
# 気持ちはわかるが、抑えろめぐみん。\n収拾がつかなくなる。
426 = "気持ちはわかるが、抑えろめぐみん。\\n収拾がつかなくなる。"

# めぐみん
# わかっていますよっ。
391 = "わかっていますよっ。"

# カズマ
# はいはい、話を戻すぞ！
366 = "はいはい、話を戻すぞ！"

# ゆんゆん
# あ、話の腰を折っちゃってすみませんでした！
279 = "あ、話の腰を折っちゃってすみませんでした！"

# カズマ
# これからが肝心な事なんだが、\nアイドルに必要不可欠な物がある。
315 = "これからが肝心な事なんだが、\\nアイドルに必要不可欠な物がある。"

# めぐみん
# なんですか、それは？
360 = "なんですか、それは？"

# カズマ
# さっきも少し話が出たけど衣装だ！
319 = "さっきも少し話が出たけど衣装だ！"

# ゆんゆん
# 来たよ、めぐみん。
423 = "来たよ、めぐみん。"

# めぐみん
# ええ、わかっています、わかっていますとも。
300 = "ええ、わかっています、わかっていますとも。"

# カズマ
# みんな、メイド喫茶のことを思いだしてくれ。
381 = "みんな、メイド喫茶のことを思いだしてくれ。"

# カズマ
# メイド喫茶に客が押し寄せたのは、メイドさんに\nお世話して貰えるからだけじゃない。
403 = "メイド喫茶に客が押し寄せたのは、メイドさんに\\nお世話して貰えるからだけじゃない。"

# カズマ
# 理由は他にもあって、メイド服の女の子が\n可愛いすぎて、また会いに行きたいって\n気持ちになっていたからなんだ。
429 = "理由は他にもあって、メイド服の女の子が\\n可愛いすぎて、また会いに行きたいって\\n気持ちになっていたからなんだ。"

# ダクネス
# つまり、愛らしい衣装は必要不可欠だと。
347 = "つまり、愛らしい衣装は必要不可欠だと。"

# カズマ
# その通り！
332 = "その通り！"

# めぐみん
# 異議ありです！
431 = "異議ありです！"

# カズマ
# 却下する！
410 = "却下する！"

# ゆんゆん
# 私も異議ありです！
506 = "私も異議ありです！"

# カズマ
# なんだい、ゆんゆん。\n友達の俺に何を意見するつもりなのかな？
357 = "なんだい、ゆんゆん。\\n友達の俺に何を意見するつもりなのかな？"

# ゆんゆん
# え、ええと、それは……。\nな、なんでもありません。
297 = "え、ええと、それは……。\\nな、なんでもありません。"

# めぐみん
# まったく、頼りないですね、あなたって人はっ！
379 = "まったく、頼りないですね、あなたって人はっ！"

# ゆんゆん
# だって、友達に意見するなんていけないことだよ！
343 = "だって、友達に意見するなんていけないことだよ！"

# ゆんゆん
# 否定をしないで、相手の言うことにはただ頷く。\nそれが人間関係を上手に保つコツなんだからね！
413 = "否定をしないで、相手の言うことにはただ頷く。\\nそれが人間関係を上手に保つコツなんだからね！"

# めぐみん
# そんなんだから、\nいつまで経ってもぼっちなんですよ！
339 = "そんなんだから、\\nいつまで経ってもぼっちなんですよ！"

# ゆんゆん
# 私ぼっちじゃないよ！\nだってめぐみんがいるもの！
505 = "私ぼっちじゃないよ！\\nだってめぐみんがいるもの！"

# めぐみん
# うっ、うぬぅ……。\nき、気恥ずかしいことを大声で言わないでください！
296 = "うっ、うぬぅ……。\\nき、気恥ずかしいことを大声で言わないでください！"

# ゆんゆん
# きゃぁ！\nちょっとめぐみん、叩かないでよー！
313 = "きゃぁ！\\nちょっとめぐみん、叩かないでよー！"

# ダクネス
# また始まってしまったな。
378 = "また始まってしまったな。"

# カズマ
# ああ、困ったもんだ。
283 = "ああ、困ったもんだ。"

# カズマ（Ｍ）
# display as カズマ
# （ふふ、だが俺にとっては好都合だ）
517 = "（ふふ、だが俺にとっては好都合だ）"

# カズマ
# よしじゃあ、時間も無いし、\nとっとと衣装を決めちまうぞ。
389 = "よしじゃあ、時間も無いし、\\nとっとと衣装を決めちまうぞ。"

# アクア
# ねえねえ、私に決めさせて！
362 = "ねえねえ、私に決めさせて！"

# カズマ
# いや、ここはダクネスだろう。
292 = "いや、ここはダクネスだろう。"

# ダクネス
# 私か？
503 = "私か？"

# カズマ
# お前は色々な服やドレスを見てきただろ？\nだったら適任じゃないか。
310 = "お前は色々な服やドレスを見てきただろ？\\nだったら適任じゃないか。"

# ダクネス
# それはそうだが。\nデザインはまた、別の話だろう。
336 = "それはそうだが。\\nデザインはまた、別の話だろう。"

# カズマ
# 難しく考える必要はないんだって。
512 = "難しく考える必要はないんだって。"

# カズマ
# お前がどんな服を着たくて、\nどんな服で興奮するかを言えばいいんだよ。
307 = "お前がどんな服を着たくて、\\nどんな服で興奮するかを言えばいいんだよ。"

# ダクネス
# 私が興奮する！？
504 = "私が興奮する！？"

# カズマ
# そうだ、興奮だ。\nそして男の目を誘う物ならなお良し！
328 = "そうだ、興奮だ。\\nそして男の目を誘う物ならなお良し！"

# クリス
# ちょっとまさか！
345 = "ちょっとまさか！"

# ダクネス
# 男達の淫欲に満ちた視線を\nこの体だけに集める衣装……。
430 = "男達の淫欲に満ちた視線を\\nこの体だけに集める衣装……。"

# クリス
# ちょっとダクネス。\nこういうことはみんなで話し合って決めた方が！
346 = "ちょっとダクネス。\\nこういうことはみんなで話し合って決めた方が！"

# カズマ
# まあ、ミニスカートは基本だよな？
372 = "まあ、ミニスカートは基本だよな？"

# ダクネス
# カズマは、私に太ももを晒して、\nいつ中を見られるかもしれない状況に怯えながら\n踊り歌い続けろと言うのか！
398 = "カズマは、私に太ももを晒して、\\nいつ中を見られるかもしれない状況に怯えながら\\n踊り歌い続けろと言うのか！"

# カズマ
# しかし男達は、そんなダクネスに釘付けになり\n金を落とすんだ。
322 = "しかし男達は、そんなダクネスに釘付けになり\\n金を落とすんだ。"

# ダクネス
# くっ、この体を男達の卑猥な視線に晒し\n金を取れなんて――
314 = "くっ、この体を男達の卑猥な視線に晒し\\n金を取れなんて――"

# ダクネス
# お前は私に、騎士と女の誇りを同時に捨てろと\n言うんだな！
309 = "お前は私に、騎士と女の誇りを同時に捨てろと\\n言うんだな！"

# ダクネス
# ああ、なんて汚らわしい思考。\n理解なんてできない、できるわけがない。
281 = "ああ、なんて汚らわしい思考。\\n理解なんてできない、できるわけがない。"

# ダクネス
# しかし私は決断をしなければいけないんだ。
323 = "しかし私は決断をしなければいけないんだ。"

# ダクネス
# 皆が満月の夜に怯えないように、\nまた平和の中で笑って暮らせるように！
432 = "皆が満月の夜に怯えないように、\\nまた平和の中で笑って暮らせるように！"

# カズマ
# さあ、ダクネス、答えを聞かせて貰おうか。
318 = "さあ、ダクネス、答えを聞かせて貰おうか。"

# ダクネス
# 当然、スカートはミニだろう！\nミニに決まっている！
420 = "当然、スカートはミニだろう！\\nミニに決まっている！"

# クリス
# ああ、もう、言っちゃったよ。
282 = "ああ、もう、言っちゃったよ。"

# カズマ
# はい、じゃあスカートはミニで決定な。
365 = "はい、じゃあスカートはミニで決定な。"

# アクア
# ねえねえ、そういう細部よりも先に全体像を\n決めた方がいいんじゃないかしら？
361 = "ねえねえ、そういう細部よりも先に全体像を\\n決めた方がいいんじゃないかしら？"

# カズマ
# 至極まっとうなご意見をありがとう。
507 = "至極まっとうなご意見をありがとう。"

# アクア
# さっきも言ったけど、\n私は水をイメージした物がいいと思うの。
320 = "さっきも言ったけど、\\n私は水をイメージした物がいいと思うの。"

# カズマ
# 抽象的すぎてわからん。\n具体的に言ってくれ。
421 = "抽象的すぎてわからん。\\n具体的に言ってくれ。"

# アクア
# だから、こうスラ～っとしてて、シュワシュワー\nって感じよ。
340 = "だから、こうスラ～っとしてて、シュワシュワー\\nって感じよ。"

# カズマ
# だから具体的に言えよ！
341 = "だから具体的に言えよ！"

# アクア
# だーかーらっ、こうスラーって感じで！
344 = "だーかーらっ、こうスラーって感じで！"

# カズマ
# お前はもういい！\n次はクリス！
308 = "お前はもういい！\\n次はクリス！"

# クリス
# よくわからないけど、\nたぶん清楚さを感じさせる方がいいんだよね？
387 = "よくわからないけど、\\nたぶん清楚さを感じさせる方がいいんだよね？"

# カズマ
# まあ、そうだな。
371 = "まあ、そうだな。"

# クリス
# だったら色は青なんてどうかな？
342 = "だったら色は青なんてどうかな？"

# カズマ
# ふむ、色から入るのも確かにありだな。
368 = "ふむ、色から入るのも確かにありだな。"

# めぐみん
# はぁはぁ、席を外してしまいすみませんでした。
363 = "はぁはぁ、席を外してしまいすみませんでした。"

# カズマ
# おっ、ケンカは終わったのか？
306 = "おっ、ケンカは終わったのか？"

# ゆんゆん
# これくらいのケンカは日常茶飯事ですから、\n収拾のさせ方も慣れたものなんです。
316 = "これくらいのケンカは日常茶飯事ですから、\\n収拾のさせ方も慣れたものなんです。"

# めぐみん
# まあ、確かに、お互いに引きどころは心得ている\n感じですね。
374 = "まあ、確かに、お互いに引きどころは心得ている\\n感じですね。"

# カズマ（Ｍ）
# display as カズマ
# （仲がいいのか悪いのか……）
521 = "（仲がいいのか悪いのか……）"

# めぐみん
# それで、なんの話をしていたんです？
334 = "それで、なんの話をしていたんです？"

# カズマ
# 衣装の全体像をどうするかって話だよ。
508 = "衣装の全体像をどうするかって話だよ。"

# めぐみん
# 全体像ですか、難しそうですね。\nゆんゆんは何かあります？
408 = "全体像ですか、難しそうですね。\\nゆんゆんは何かあります？"

# ゆんゆん
# そうね。\nお姫様っぽい衣装がいいんじゃないかな。
331 = "そうね。\\nお姫様っぽい衣装がいいんじゃないかな。"

# めぐみん
# ずいぶんと少女趣味ですね。
324 = "ずいぶんと少女趣味ですね。"

# ゆんゆん
# でも、お姫様みたいな衣装なら\nスカートが長くなると思うよ？
351 = "でも、お姫様みたいな衣装なら\\nスカートが長くなると思うよ？"

# めぐみん
# はい！\n私もお姫様のような衣装がいいと思います！
367 = "はい！\\n私もお姫様のような衣装がいいと思います！"

# クリス
# ええと、ふたりに悲しい知らせなんだけど。
302 = "ええと、ふたりに悲しい知らせなんだけど。"

# ゆんゆん
# あ、はい、なんでしょう？
278 = "あ、はい、なんでしょう？"

# クリス
# スカートはミニって決定してるから。
401 = "スカートはミニって決定してるから。"

# ゆんゆん
# ええ、どうしてですか！？
299 = "ええ、どうしてですか！？"

# めぐみん
# さては、カズマ。\nあなたの仕業ですね。
321 = "さては、カズマ。\\nあなたの仕業ですね。"

# カズマ
# 違う、決めたのはダクネスだ。
511 = "違う、決めたのはダクネスだ。"

# めぐみん
# どうしてですか、ダクネス！\nスカートがミニということは――
354 = "どうしてですか、ダクネス！\\nスカートがミニということは――"

# ダクネス
# ああ、見えてしまうかもしれない！\nしかしこれも皆のためなんだ！
284 = "ああ、見えてしまうかもしれない！\\nしかしこれも皆のためなんだ！"

# めぐみん
# まったくわけがわかりませんよ！
380 = "まったくわけがわかりませんよ！"

# ダクネス
# 不満に思うなら私に文句を言ってくれ。\nなんなら口汚く罵ってくれても構わない。
404 = "不満に思うなら私に文句を言ってくれ。\\nなんなら口汚く罵ってくれても構わない。"

# ゆんゆん
# そ、そんなことできるわけないじゃないですか。
325 = "そ、そんなことできるわけないじゃないですか。"

# カズマ（Ｍ）
# display as カズマ
# （ダクネス、ナイススケープゴート！）
520 = "（ダクネス、ナイススケープゴート！）"

# アクア
# 来た、来たわよ、カズマ！\n天啓を得たわ！
422 = "来た、来たわよ、カズマ！\\n天啓を得たわ！"

# カズマ
# いや、おい、え？　女神のお前が天啓を得たの？
291 = "いや、おい、え？　女神のお前が天啓を得たの？"

# アクア
# 清楚感溢れる天女のような衣装！\nこれでどうかしら！
428 = "清楚感溢れる天女のような衣装！\\nこれでどうかしら！"

# カズマ
# なるほど。\nそういうのもありだな。
356 = "なるほど。\\nそういうのもありだな。"

# アクア
# でしょ？
350 = "でしょ？"

# カズマ（Ｍ）
# display as カズマ
# （ふむ、色々な意見が出てきたが、\n　どれがいいだろう……）
518 = "（ふむ、色々な意見が出てきたが、\\n　どれがいいだろう……）"

# カズマ
# 今出た意見の中では、お姫様の衣装が\nいいかもしれないな。
406 = "今出た意見の中では、お姫様の衣装が\\nいいかもしれないな。"

# ゆんゆん
# やっぱりそうですよね！
384 = "やっぱりそうですよね！"

# めぐみん
# カズマならわかってくれると思っていましたよ！
397 = "カズマならわかってくれると思っていましたよ！"

# ゆんゆん
# あの、それでスカートも衣装のイメージに合わせて\n長くするのが良いかと……。
287 = "あの、それでスカートも衣装のイメージに合わせて\\n長くするのが良いかと……。"

# カズマ
# あ、それはもう決定事項だから却下で。
277 = "あ、それはもう決定事項だから却下で。"

# ゆんゆん
# そ、そんな～。
326 = "そ、そんな～。"

# カズマ（Ｍ）
# display as カズマ
# （お姫様案で進めたら、\n　またスカートの話が再燃しそうだな）
513 = "（お姫様案で進めたら、\\n　またスカートの話が再燃しそうだな）"

# カズマ（Ｍ）
# display as カズマ
# （しょうがない、俺がデザインを考えるか）
515 = "（しょうがない、俺がデザインを考えるか）"

# カズマ
# 天女のイメージがいいかもしれないな。
416 = "天女のイメージがいいかもしれないな。"

# アクア
# でしょでしょ？\nさすがカズマ、わかってるじゃない！
349 = "でしょでしょ？\\nさすがカズマ、わかってるじゃない！"

# カズマ
# で、細部のデザインまで詰めていきたいんだけど、\n何か案はあるか？
348 = "で、細部のデザインまで詰めていきたいんだけど、\\n何か案はあるか？"

# アクア
# え？　無いわよ？
305 = "え？　無いわよ？"

# カズマ
# はあ？
364 = "はあ？"

# アクア
# そういうのはカズマに任せるわ。\nあ、でも、羽衣は必須だからね。
327 = "そういうのはカズマに任せるわ。\\nあ、でも、羽衣は必須だからね。"

# カズマ（Ｍ）
# display as カズマ
# （こいつは言いたい事だけ言って、\n　あとは投げっぱなしかよ！）
514 = "（こいつは言いたい事だけ言って、\\n　あとは投げっぱなしかよ！）"

# カズマ（Ｍ）
# display as カズマ
# （しょうがない。俺が一から考えるか）
516 = "（しょうがない。俺が一から考えるか）"

# カズマ
# よし、しょうがない。\nここは全て俺に任せておけ！
388 = "よし、しょうがない。\\nここは全て俺に任せておけ！"

# アクア
# ええ！　私が出したアイデアは！
303 = "ええ！　私が出したアイデアは！"

# ゆんゆん
# あの、お姫様っぽい服という意見は。
286 = "あの、お姫様っぽい服という意見は。"

# めぐみん
# どんな衣装でも着ますから、\nスカートだけは長くしてください！
355 = "どんな衣装でも着ますから、\\nスカートだけは長くしてください！"

# カズマ
# あのなー、お前らの言うことがバラバラだから\n俺がまとめないといけないんだろ。
288 = "あのなー、お前らの言うことがバラバラだから\\n俺がまとめないといけないんだろ。"

# カズマ
# こんな話し合いを続けてたら、\nあっという間に次の満月になっちまうぞ。
317 = "こんな話し合いを続けてたら、\\nあっという間に次の満月になっちまうぞ。"

# めぐみん
# うぐっ、それは困ります。
295 = "うぐっ、それは困ります。"

# カズマ
# まあ、悪いようにはしないから安心しろって。
373 = "まあ、悪いようにはしないから安心しろって。"

# ダクネス
# やれやれ、何かが決まったようで、\n何も決まっていないな。
385 = "やれやれ、何かが決まったようで、\\n何も決まっていないな。"

# カズマ
# それを言うなよ。
337 = "それを言うなよ。"

# アクア
# それで、この後はどうするの？
333 = "それで、この後はどうするの？"

# カズマ
# そうだな。\nなんとか衣装のデザインは俺が夜までに\n決めるとして。
330 = "そうだな。\\nなんとか衣装のデザインは俺が夜までに\\n決めるとして。"

# カズマ
# みんなで衣装の材料を買いに行くか。
382 = "みんなで衣装の材料を買いに行くか。"

# クリス
# え？　デザインが決まってないのに？
304 = "え？　デザインが決まってないのに？"

# カズマ
# 店がやってる時間のうちにデザインを\n決められる自信がないんだよ。
419 = "店がやってる時間のうちにデザインを\\n決められる自信がないんだよ。"

# カズマ
# まあ最悪、買い集めた材料から考えるって。
376 = "まあ最悪、買い集めた材料から考えるって。"

# クリス
# なんていうか、行き当たりばったりだね。
359 = "なんていうか、行き当たりばったりだね。"

# アクア
# 別に良いじゃない。\nなんか楽しいし。
409 = "別に良いじゃない。\\nなんか楽しいし。"

# クリス
# あは、あはは、そうかな？
289 = "あは、あはは、そうかな？"

# カズマ（Ｍ）
# display as カズマ
# （買い出しついでにウィズにも声をかけてみるか）
523 = "（買い出しついでにウィズにも声をかけてみるか）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズの知名度を使わない手はないからな）
519 = "（ウィズの知名度を使わない手はないからな）"

[selections]
312 = "お姫様衣装かな"
415 = "天女がいいかもしれない"
407 = "全て俺に任せておけ！"
