# st03a_09.txt.scn

[info]
0 = ""

[characters]
254 = "カズマ（Ｍ）"
255 = "クリス"
251 = "カズマ"
256 = "ダクネス"
250 = "ウィズ"
245 = "ゆんゆん"
242 = "めぐみん"
249 = "アクア"

[character_subs]
# 251 = "カズマ"

[script]
# lines: 68

# カズマ（Ｍ）
# display as カズマ
# （遅い、遅すぎる……）
310 = "（遅い、遅すぎる……）"

# カズマ（Ｍ）
# display as カズマ
# （あいつらは、いつまで待たせるんだよ）
301 = "（あいつらは、いつまで待たせるんだよ）"

# カズマ（Ｍ）
# display as カズマ
# （なんか、キャッキャウフフと楽しそうな\n　声が聞こえて来てるけど、\n　ちゃんと採寸しているんだろうな？）
304 = "（なんか、キャッキャウフフと楽しそうな\\n　声が聞こえて来てるけど、\\n　ちゃんと採寸しているんだろうな？）"

# クリス
# カズマ、そこにいるの？
252 = "カズマ、そこにいるの？"

# カズマ
# ああ、もう待ちくたびれたぞ。
203 = "ああ、もう待ちくたびれたぞ。"

# クリス
# もう入って来ても大丈夫だからどうぞ。
244 = "もう入って来ても大丈夫だからどうぞ。"

# カズマ（Ｍ）
# display as カズマ
# （ふう、ようやくか）
305 = "（ふう、ようやくか）"

# クリス
# ごめんね、だいぶ待たせちゃったみたいで。
221 = "ごめんね、だいぶ待たせちゃったみたいで。"

# カズマ
# それで、採寸は終わったのか？
226 = "それで、採寸は終わったのか？"

# クリス
# これが採寸したメモ。\n当然、外部には漏らさないこと、わかったね？
220 = "これが採寸したメモ。\\n当然、外部には漏らさないこと、わかったね？"

# カズマ
# ああ、なるほど。\nそういう商売も考えられるよな。
202 = "ああ、なるほど。\\nそういう商売も考えられるよな。"

# ダクネス
# カズマ、それを本気で言っているなら、\n私もさすがに付き合い方を考えるぞ。
253 = "カズマ、それを本気で言っているなら、\\n私もさすがに付き合い方を考えるぞ。"

# カズマ
# 冗談だよ、本気にするなって。
262 = "冗談だよ、本気にするなって。"

# カズマ（Ｍ）
# display as カズマ
# （だいたい、こんなもん売っても\n　日銭程度の稼ぎにしかならないだろ）
303 = "（だいたい、こんなもん売っても\\n　日銭程度の稼ぎにしかならないだろ）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、欲しがるやつはそれなりにいるとは\n　思うけど）
308 = "（まあ、欲しがるやつはそれなりにいるとは\\n　思うけど）"

# カズマ
# …………。
198 = "…………。"

# ウィズ
# あの、カズマさん。\nメモをマジマジと見て、どうしたんですか？
208 = "あの、カズマさん。\\nメモをマジマジと見て、どうしたんですか？"

# カズマ
# へー、ウィズってこんなにあるのか。
239 = "へー、ウィズってこんなにあるのか。"

# ウィズ
# え！？
217 = "え！？"

# カズマ
# ゆんゆんは、実にけしからん、けしからんぞ！
246 = "ゆんゆんは、実にけしからん、けしからんぞ！"

# ゆんゆん
# ええ！？
215 = "ええ！？"

# カズマ
# めぐみん……。
243 = "めぐみん……。"

# めぐみん
# なんです！\n言いたいことがあるなら\nはっきりと言ったらどうですか！
236 = "なんです！\\n言いたいことがあるなら\\nはっきりと言ったらどうですか！"

# カズマ
# 頑張れ！
300 = "頑張れ！"

# めぐみん
# なっ！？
231 = "なっ！？"

# クリス
# あのさ、数値と実物を比べて楽しむっていうのは、\n人としてどうかと思うよ？
210 = "あのさ、数値と実物を比べて楽しむっていうのは、\\n人としてどうかと思うよ？"

# めぐみん
# 本当に最低ですね。\n死ねばいいのに。
267 = "本当に最低ですね。\\n死ねばいいのに。"

# カズマ
# ばっ、ばっか！　そんなんじゃねぇよ！\nこれは衣装を作るのに必要なことなんだ！
238 = "ばっ、ばっか！　そんなんじゃねぇよ！\\nこれは衣装を作るのに必要なことなんだ！"

# めぐみん
# じゃあ、その行為にどんな意味があるのか\n納得のいく説明をしてください。
222 = "じゃあ、その行為にどんな意味があるのか\\n納得のいく説明をしてください。"

# カズマ
# そ、それはだな。
225 = "そ、それはだな。"

# カズマ
# 人の目なんて実はいい加減なものなんだ。\n実際に見えている物と、調べてみた物に差が\nある事なんてよくある事なんだ。
259 = "人の目なんて実はいい加減なものなんだ。\\n実際に見えている物と、調べてみた物に差が\\nある事なんてよくある事なんだ。"

# カズマ
# だから、衣装作りも数字と見た目の差をちゃんと\n理解した上で、イメージしていかなければ\nいけないのだ！
227 = "だから、衣装作りも数字と見た目の差をちゃんと\\n理解した上で、イメージしていかなければ\\nいけないのだ！"

# めぐみん
# なんかそれっぽくは聞こえますが、\nこのそこはかとなく漂う胡散臭さは\nいったいなんなのでしょう。
232 = "なんかそれっぽくは聞こえますが、\\nこのそこはかとなく漂う胡散臭さは\\nいったいなんなのでしょう。"

# カズマ
# とにかくこれも必要なことなんだよ！
230 = "とにかくこれも必要なことなんだよ！"

# クリス
# まったく、その言葉を信じるからね。
241 = "まったく、その言葉を信じるからね。"

# カズマ
# じゃあ、次はクリスな。
224 = "じゃあ、次はクリスな。"

# クリス
# はぁ、お手柔らかに頼むよ。
237 = "はぁ、お手柔らかに頼むよ。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、上は見た目通りだな）
307 = "（まあ、上は見た目通りだな）"

# クリス
# う、うう……。
211 = "う、うう……。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、おっぱい枠はウィズにゆんゆん、\n　それにダクネスがいるから問題ない）
306 = "（まあ、おっぱい枠はウィズにゆんゆん、\\n　それにダクネスがいるから問題ない）"

# カズマ（Ｍ）
# display as カズマ
# （クリスが武器にすべきなのは――）
309 = "（クリスが武器にすべきなのは――）"

# カズマ（Ｍ）
# display as カズマ
# （この健康的な腰！　足！　そして尻！）
302 = "（この健康的な腰！　足！　そして尻！）"

# クリス
# あ、あの、カズマ？\nどうして近づいてくるのさ。
200 = "あ、あの、カズマ？\\nどうして近づいてくるのさ。"

# カズマ
# ああ、悪い、入り込みすぎた。
204 = "ああ、悪い、入り込みすぎた。"

# クリス
# あたしはもういいでしょ。\nはい！　もうお終い！
206 = "あたしはもういいでしょ。\\nはい！　もうお終い！"

# カズマ
# じゃあ、次は――
223 = "じゃあ、次は――"

# アクア
# まさか、女神である私まで\nその卑猥な目で汚すつもり！
240 = "まさか、女神である私まで\\nその卑猥な目で汚すつもり！"

# カズマ
# お前は、なるほど、うん、だいたいわかった。
218 = "お前は、なるほど、うん、だいたいわかった。"

# アクア
# ええ！？　なんか適当！！
216 = "ええ！？　なんか適当！！"

# カズマ
# よし、大体イメージも固まってきたし、\nそろそろ衣装作りに取りかかるとするか。
248 = "よし、大体イメージも固まってきたし、\\nそろそろ衣装作りに取りかかるとするか。"

# ウィズ
# あのぉ、できれば私にもあいどる？　というものを\n詳しく教えていただけると。
209 = "あのぉ、できれば私にもあいどる？　というものを\\n詳しく教えていただけると。"

# カズマ
# ああ、じゃあそれは衣装のデザインを起こしながら\n説明するよ。
201 = "ああ、じゃあそれは衣装のデザインを起こしながら\\n説明するよ。"

# めぐみん
# なんです、まだできていなかったんですか？
235 = "なんです、まだできていなかったんですか？"

# カズマ
# 俺のどこにそんな時間があった。
261 = "俺のどこにそんな時間があった。"

# クリス
# これからデザイン、そして衣装作り。\n１週間くらいは見ておいた方がいいかもね。
219 = "これからデザイン、そして衣装作り。\\n１週間くらいは見ておいた方がいいかもね。"

# カズマ
# 何言ってるんだよ。\n明日の朝までに全部仕上げるぞ。
260 = "何言ってるんだよ。\\n明日の朝までに全部仕上げるぞ。"

# クリス
# ええ、そうなの！？
213 = "ええ、そうなの！？"

# ダクネス
# 間違いなく徹夜だな。
299 = "間違いなく徹夜だな。"

# カズマ
# ああそうだ。\nもう食材のストックが無いから、\nみんなの分も含めた買い出しを誰か頼む。
205 = "ああそうだ。\\nもう食材のストックが無いから、\\nみんなの分も含めた買い出しを誰か頼む。"

# ダクネス
# よし、それは私が任された。
247 = "よし、それは私が任された。"

# クリス
# あたしも付き合うよ、ダクネス。
207 = "あたしも付き合うよ、ダクネス。"

# めぐみん
# では、私は衣装の材料を\nわかりやすく分けておきますね。
228 = "では、私は衣装の材料を\\nわかりやすく分けておきますね。"

# ゆんゆん
# ええと私は、勝手に人の家の中を\n歩き回るのはマズイし。
214 = "ええと私は、勝手に人の家の中を\\n歩き回るのはマズイし。"

# ゆんゆん
# でも、何もしないと、\nあんた何しにここに来たの？\nとか思われそうだし。
229 = "でも、何もしないと、\\nあんた何しにここに来たの？\\nとか思われそうだし。"

# めぐみん
# ……ゆんゆんも私の手伝いをしてくださいっ！
199 = "……ゆんゆんも私の手伝いをしてくださいっ！"

# ゆんゆん
# う、うん、わかったよ、めぐみん！
212 = "う、うん、わかったよ、めぐみん！"

# アクア
# なんだか、みんな大変そうね。
233 = "なんだか、みんな大変そうね。"

# カズマ
# なんでお前だけ人ごとなんだよ。
234 = "なんでお前だけ人ごとなんだよ。"

