# st03b_10.txt.scn

[info]
0 = ""

[characters]
256 = "カズマ"
253 = "ウィズ"
252 = "アクア"
245 = "めぐみん＆ゆんゆん"
258 = "カズマ（Ｍ）"
244 = "めぐみん"
247 = "ゆんゆん"
261 = "ダクネス"
259 = "クリス"

[character_subs]
319 = "２人"
# 256 = "カズマ"

[script]
# lines: 68

# カズマ
# さて、キャラ付けも終わったことだし、\n次のステップへ行こう。
216 = "さて、キャラ付けも終わったことだし、\\n次のステップへ行こう。"

# ウィズ
# 息つく暇もありませんね。
272 = "息つく暇もありませんね。"

# カズマ
# 時間が無いからな。
273 = "時間が無いからな。"

# アクア
# そうよ、ウィズ！\nアイドルとは並々ならぬ努力の上に\n成り立ってるんだから！
219 = "そうよ、ウィズ！\\nアイドルとは並々ならぬ努力の上に\\n成り立ってるんだから！"

# カズマ
# はいはい、そういうセンターアピールはいいから。
236 = "はいはい、そういうセンターアピールはいいから。"

# ウィズ
# それで、次はどのような特訓なんでしょう。
223 = "それで、次はどのような特訓なんでしょう。"

# カズマ
# それはだな、サインの練習だ！
224 = "それはだな、サインの練習だ！"

# めぐみん＆ゆんゆん
# display as ２人
# サイン？
260 = "サイン？"

# カズマ
# アイドルのサインは、レアアイテムと\n同じぐらいの価値がある貴重な物なんだ。
251 = "アイドルのサインは、レアアイテムと\\n同じぐらいの価値がある貴重な物なんだ。"

# カズマ
# それこそファンの間じゃ、何百万って値段で\n取引される場合もあるんだぞ。
221 = "それこそファンの間じゃ、何百万って値段で\\n取引される場合もあるんだぞ。"

# アクア
# じゃあ、アイドルなんてやらないで、\nサインを売ればいいじゃない！
217 = "じゃあ、アイドルなんてやらないで、\\nサインを売ればいいじゃない！"

# カズマ
# まだアイドルとして売れても\nいないヤツのサインなんて１エリスにも\nなりゃしないだろ。
241 = "まだアイドルとして売れても\\nいないヤツのサインなんて１エリスにも\\nなりゃしないだろ。"

# アクア
# 何言ってるの。\n私のサインだったら、信者は全財産をはたいても\n買うはずよ！
265 = "何言ってるの。\\n私のサインだったら、信者は全財産をはたいても\\n買うはずよ！"

# カズマ（Ｍ）
# display as カズマ
# （だったらいいなー）
318 = "（だったらいいなー）"

# カズマ
# とにかく、サインは有名になるにつれ\n求められるものなんだ。
230 = "とにかく、サインは有名になるにつれ\\n求められるものなんだ。"

# カズマ
# いわゆるファンサービスの１つだが、\nバカにも出来ない。\nだから、今のうちから練習しておこう。
204 = "いわゆるファンサービスの１つだが、\\nバカにも出来ない。\\nだから、今のうちから練習しておこう。"

# めぐみん
# 自分の名前を書くだけなのに、\n練習なんていりますか？
315 = "自分の名前を書くだけなのに、\\n練習なんていりますか？"

# カズマ
# おおありだ。\nサインとはだな――
208 = "おおありだ。\\nサインとはだな――"

# カズマ
# こうして、こんな感じて、こーやって……。
211 = "こうして、こんな感じて、こーやって……。"

# カズマ
# ふっ、これが完成形だ。
237 = "ふっ、これが完成形だ。"

# ゆんゆん
# こ、これって何て読むんですか？
210 = "こ、これって何て読むんですか？"

# ウィズ
# 小さい子の落書きにしか見えません。
269 = "小さい子の落書きにしか見えません。"

# カズマ
# まぁ、みんなは初めて見る物だから\n読めなくてもしょうがないが、\nこれはサトウカズマと書いてある。
238 = "まぁ、みんなは初めて見る物だから\\n読めなくてもしょうがないが、\\nこれはサトウカズマと書いてある。"

# めぐみん
# これがカズマの名前？\nどう見てもミミズが這った跡にしか\n見えません。
212 = "これがカズマの名前？\\nどう見てもミミズが這った跡にしか\\n見えません。"

# ダクネス
# ああ、なるほど。\nサインとはその人間性も表すものなんだな。
199 = "ああ、なるほど。\\nサインとはその人間性も表すものなんだな。"

# カズマ
# 何、俺をミミズみたいって言いたいの？
264 = "何、俺をミミズみたいって言いたいの？"

# めぐみん
# ダクネス、それだと説明がつきません。
262 = "ダクネス、それだと説明がつきません。"

# カズマ
# さすが、めぐみん。\n俺のことをわかってるな。
215 = "さすが、めぐみん。\\n俺のことをわかってるな。"

# めぐみん
# カズマの人間性を出すなら、もっとへたれ感を\n出すべきです。
257 = "カズマの人間性を出すなら、もっとへたれ感を\\n出すべきです。"

# カズマ
# なっ！
231 = "なっ！"

# アクア
# あとはニート感もね。
200 = "あとはニート感もね。"

# カズマ
# ねえ、ニート感って何！\nてか、俺ニートじゃないから！
235 = "ねえ、ニート感って何！\\nてか、俺ニートじゃないから！"

# クリス
# まあまあ、落ち着いて。\nつまりみんなサインがどういう物なのか\nわかってないんだよ。
240 = "まあまあ、落ち着いて。\\nつまりみんなサインがどういう物なのか\\nわかってないんだよ。"

# カズマ
# いいか、字を崩すにはちゃんと理由があるんだ。
203 = "いいか、字を崩すにはちゃんと理由があるんだ。"

# カズマ
# ただ普通に自分の名前を書いただけじゃ、\n簡単に真似されちまうだろ。
225 = "ただ普通に自分の名前を書いただけじゃ、\\n簡単に真似されちまうだろ。"

# カズマ
# だから、こうやって特徴的なサインを\n書くってわけだ。
226 = "だから、こうやって特徴的なサインを\\n書くってわけだ。"

# クリス
# なるほど、偽造防止も兼ねているわけだね。
232 = "なるほど、偽造防止も兼ねているわけだね。"

# カズマ
# まあ、理由は他にも色々あるが、\n俺の故郷では、有名人のサインは\nみんなこんな感じだ。
239 = "まあ、理由は他にも色々あるが、\\n俺の故郷では、有名人のサインは\\nみんなこんな感じだ。"

# カズマ
# というわけで、みんなも自分のサインを作って、\nそれを練習するんだ！
229 = "というわけで、みんなも自分のサインを作って、\\nそれを練習するんだ！"

# めぐみん
# そうは言われても難しいですよ。
218 = "そうは言われても難しいですよ。"

# カズマ
# だったらまず、方向性を決めるのはどうだ？
227 = "だったらまず、方向性を決めるのはどうだ？"

# ゆんゆん
# 私は、可愛いサインにしようかな。
314 = "私は、可愛いサインにしようかな。"

# めぐみん
# では私は、爆裂という感じで！
228 = "では私は、爆裂という感じで！"

# クリス
# うーん、こんな感じかな？
205 = "うーん、こんな感じかな？"

# めぐみん
# よっ、はっ！\nここに爆裂マークを入れてっ！
249 = "よっ、はっ！\\nここに爆裂マークを入れてっ！"

# ウィズ
# あの……私、いつもお店の納品書や領収書に\nサインをしているんですが、こんな感じで\nいいんでしょうか？
201 = "あの……私、いつもお店の納品書や領収書に\\nサインをしているんですが、こんな感じで\\nいいんでしょうか？"

# カズマ
# んーーっ、やっぱり、なんか受け取りサインって\n感じがするな。
250 = "んーーっ、やっぱり、なんか受け取りサインって\\n感じがするな。"

# カズマ
# ウィズのキャラ付けから考えて――
254 = "ウィズのキャラ付けから考えて――"

# カズマ
# こんな感じの、流麗な感じがいいだろうな。
214 = "こんな感じの、流麗な感じがいいだろうな。"

# ウィズ
# なるほど、勉強になります。
233 = "なるほど、勉強になります。"

# カズマ
# みんな、頑張って自分の個性を前面に押し出した\nサインを作ってくれ！
242 = "みんな、頑張って自分の個性を前面に押し出した\\nサインを作ってくれ！"

# アクア
# よしっ、完成っ！！　カズマーこれを見て？
248 = "よしっ、完成っ！！　カズマーこれを見て？"

# カズマ
# なんだ？　もう出来たのか？\nって、ずいぶんな長文に見えるんだが。
234 = "なんだ？　もう出来たのか？\\nって、ずいぶんな長文に見えるんだが。"

# アクア
# そりゃそうよ、私のありがたいお言葉ってやつを\n添えたんだから。
220 = "そりゃそうよ、私のありがたいお言葉ってやつを\\n添えたんだから。"

# カズマ
# ありがたいかどうかはともかく、\nそういう一言を添えるのはいいことだぞ。
202 = "ありがたいかどうかはともかく、\\nそういう一言を添えるのはいいことだぞ。"

# ゆんゆん
# お友達募集中？
209 = "お友達募集中？"

# ウィズ
# ウィズ魔道具店をよろしくお願いします？
255 = "ウィズ魔道具店をよろしくお願いします？"

# カズマ
# 違う、違う。\n好きな言葉とか座右の銘だ。
317 = "違う、違う。\\n好きな言葉とか座右の銘だ。"

# めぐみん
# 爆裂！
275 = "爆裂！"

# カズマ
# もうお前はそれでいいよ。
246 = "もうお前はそれでいいよ。"

# クリス
# それで、アクアさんはなんて書いたの？
222 = "それで、アクアさんはなんて書いたの？"

# アクア
# えっとね。\n迷える子羊たちよ、今すぐアクシズ教団の\n門戸を叩け。さすれば汝は救われよう！
207 = "えっとね。\\n迷える子羊たちよ、今すぐアクシズ教団の\\n門戸を叩け。さすれば汝は救われよう！"

# カズマ
# 却下。
266 = "却下。"

# アクア
# ええ、どうしてよ！
206 = "ええ、どうしてよ！"

# カズマ
# これだと趣旨が変わっちまってるじゃないか。\nまずは、お前自身のサインからだ。
213 = "これだと趣旨が変わっちまってるじゃないか。\\nまずは、お前自身のサインからだ。"

# アクア
# むぅぅぅっ……だ、だったら、女神アクア様って\n書いてもいいわよね？
243 = "むぅぅぅっ……だ、だったら、女神アクア様って\\n書いてもいいわよね？"

# カズマ
# ああ、それだったら問題ない。\nお前は自称女神様キャラだからな。
198 = "ああ、それだったら問題ない。\\nお前は自称女神様キャラだからな。"

# アクア
# 自称じゃないわよ！
316 = "自称じゃないわよ！"

