# st03a_04.txt.scn

[info]
0 = ""

[characters]
342 = "カズマ（Ｍ）"
326 = "めぐみん"
331 = "ゆんゆん"
338 = "カズマ"
337 = "アクア"
343 = "クリス"
345 = "ダクネス"

[character_subs]
# 338 = "カズマ"

[script]
# lines: 146

# カズマ（Ｍ）
# display as カズマ
# （さて、今は自分のことを考えないと）
450 = "（さて、今は自分のことを考えないと）"

# カズマ（Ｍ）
# display as カズマ
# （金を稼ぐ手段……金を稼ぐ手段か）
474 = "（金を稼ぐ手段……金を稼ぐ手段か）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、また日本のオタク文化の知識を利用した\n　商売を考えるか？）
447 = "（うーん、また日本のオタク文化の知識を利用した\\n　商売を考えるか？）"

# カズマ（Ｍ）
# display as カズマ
# （メイド喫茶は大盛況だったし、\n　この世界にはない目新しいサービスを提供すれば\n　足がかりになるくらいの金は稼げるだろう）
467 = "（メイド喫茶は大盛況だったし、\\n　この世界にはない目新しいサービスを提供すれば\\n　足がかりになるくらいの金は稼げるだろう）"

# カズマ（Ｍ）
# display as カズマ
# （いや、足がかり程度のはした金じゃダメだ！）
445 = "（いや、足がかり程度のはした金じゃダメだ！）"

# めぐみん
# カズマの体だけに結界を張って、\n爆裂魔法を当てるというのはどうでしょう？
341 = "カズマの体だけに結界を張って、\\n爆裂魔法を当てるというのはどうでしょう？"

# ゆんゆん
# だったら、カズマさんの体に結界を張って、\n火口に！
304 = "だったら、カズマさんの体に結界を張って、\\n火口に！"

# カズマ（Ｍ）
# display as カズマ
# （早くバニルに解除してもらわないと、\n　それこそ何をされるかわからん）
472 = "（早くバニルに解除してもらわないと、\\n　それこそ何をされるかわからん）"

# カズマ（Ｍ）
# display as カズマ
# （でも、元手がない状況で\n　大金を一気に稼ぐ方法なんて……）
457 = "（でも、元手がない状況で\\n　大金を一気に稼ぐ方法なんて……）"

# カズマ（Ｍ）
# display as カズマ
# （それでなくてもメイド喫茶の一件で、\n　ギルドから目をつけられてるのに……）
455 = "（それでなくてもメイド喫茶の一件で、\\n　ギルドから目をつけられてるのに……）"

# カズマ（Ｍ）
# display as カズマ
# （サキュバスのお姉さんのお店みたいに、\n　こっそりひっそりとアンダーグラウンド的に\n　商売できて――）
465 = "（サキュバスのお姉さんのお店みたいに、\\n　こっそりひっそりとアンダーグラウンド的に\\n　商売できて――）"

# カズマ（Ｍ）
# display as カズマ
# （さらにがぼっと金を稼げる商売なんて……）
451 = "（さらにがぼっと金を稼げる商売なんて……）"

# カズマ
# う、うう、うーーーーーん！！
264 = "う、うう、うーーーーーん！！"

# アクア
# カズマ、ここはトイレじゃないわよ？
339 = "カズマ、ここはトイレじゃないわよ？"

# カズマ
# わかってるし、きばってるわけじゃねーよ！
335 = "わかってるし、きばってるわけじゃねーよ！"

# アクア
# だったら何をうーんうーん言ってるの？
305 = "だったら何をうーんうーん言ってるの？"

# カズマ
# お前らが物騒な話しかしてねーから、\nなんとか金を稼ごうって知恵を絞り出してるんだよ！
279 = "お前らが物騒な話しかしてねーから、\\nなんとか金を稼ごうって知恵を絞り出してるんだよ！"

# クリス
# それで、いいアイディアは浮かびそう？
295 = "それで、いいアイディアは浮かびそう？"

# カズマ
# やっぱり、俺の住んでた所で人気だったものは、\nここでも充分需要があるってわかったし、\n次もそれでやってみようかと思う。
330 = "やっぱり、俺の住んでた所で人気だったものは、\\nここでも充分需要があるってわかったし、\\n次もそれでやってみようかと思う。"

# ゆんゆん
# 次は……どんなことをするんですか？
368 = "次は……どんなことをするんですか？"

# カズマ
# ん～……何かを売るなんていいかもな。\n手頃なグッズとか。
336 = "ん～……何かを売るなんていいかもな。\\n手頃なグッズとか。"

# カズマ（Ｍ）
# display as カズマ
# （グラスや、このシュワシュワが入っている\n　ジョッキになにか可愛い絵を彫るなんて\n　どうだろう？）
464 = "（グラスや、このシュワシュワが入っている\\n　ジョッキになにか可愛い絵を彫るなんて\\n　どうだろう？）"

# カズマ（Ｍ）
# display as カズマ
# （あとは、バッジとかキーホルダーとか）
444 = "（あとは、バッジとかキーホルダーとか）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、そういった物は職人に頼むしかないけど、\n　一定のクオリティで量産できるんだろうか？\n　んー、これは一考の余地があるな……）
452 = "（しかし、そういった物は職人に頼むしかないけど、\\n　一定のクオリティで量産できるんだろうか？\\n　んー、これは一考の余地があるな……）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、視点を変えて娯楽を考えてみるか）
448 = "（うーん、視点を変えて娯楽を考えてみるか）"

# カズマ（Ｍ）
# display as カズマ
# （娯楽、娯楽。\n　メイド喫茶みたいにこの世界にはない\n　金を稼げる娯楽）
471 = "（娯楽、娯楽。\\n　メイド喫茶みたいにこの世界にはない\\n　金を稼げる娯楽）"

# カズマ（Ｍ）
# display as カズマ
# （なおかつ、ギルドに迷惑をかけない娯楽）
458 = "（なおかつ、ギルドに迷惑をかけない娯楽）"

# カズマ
# ううーーーーん！！
266 = "ううーーーーん！！"

# クリス
# ねえねえ、カズマ。\nすごく、怖い顔になってるよ？
315 = "ねえねえ、カズマ。\\nすごく、怖い顔になってるよ？"

# カズマ
# そりゃそういう顔にだってなるだろ。\nこのままだと火口に放り込まれちまうんだぞ。
294 = "そりゃそういう顔にだってなるだろ。\\nこのままだと火口に放り込まれちまうんだぞ。"

# ダクネス
# いかに私が頑丈だとはいえ、\n熔岩の中に飛び込むのはさすがにためらわれるな。
259 = "いかに私が頑丈だとはいえ、\\n熔岩の中に飛び込むのはさすがにためらわれるな。"

# カズマ
# そんなことするって言いだしたら、\n全身縛り付けて三日三晩説教してやるわ。
302 = "そんなことするって言いだしたら、\\n全身縛り付けて三日三晩説教してやるわ。"

# ダクネス
# ここから一番近い火山はどこだったか……。
280 = "ここから一番近い火山はどこだったか……。"

# カズマ
# 冗談でもやめろっ！
357 = "冗談でもやめろっ！"

# ダクネス
# 見くびるな！　私はいつだって本気だ！
438 = "見くびるな！　私はいつだって本気だ！"

# カズマ
# 余計、質が悪いわ！
352 = "余計、質が悪いわ！"

# クリス
# あはは、それで難しい顔をして、\n何を考えていたのかな？
256 = "あはは、それで難しい顔をして、\\n何を考えていたのかな？"

# カズマ
# いやさ、この世界にはない娯楽って\nなんなのかなーってさ。
263 = "いやさ、この世界にはない娯楽って\\nなんなのかなーってさ。"

# クリス
# この前やったメイド喫茶みたいなやつだね？
281 = "この前やったメイド喫茶みたいなやつだね？"

# カズマ
# そういうのをまた考えてるんだけど、\n行き詰まって何もアイデアが出てこないんだよ。
289 = "そういうのをまた考えてるんだけど、\\n行き詰まって何もアイデアが出てこないんだよ。"

# クリス
# うーん、そういう時は、\n自分が好きなことを考えてみるのはどう？
269 = "うーん、そういう時は、\\n自分が好きなことを考えてみるのはどう？"

# カズマ
# 俺が好きなこと……。
354 = "俺が好きなこと……。"

# めぐみん
# パンツですね。
347 = "パンツですね。"

# アクア
# 間違いないわ。
440 = "間違いないわ。"

# ダクネス
# カズマのライフワークみたいなものだからな。
340 = "カズマのライフワークみたいなものだからな。"

# カズマ
# ちっがうわっ！
306 = "ちっがうわっ！"

# クリス
# はいはい、キミたちは横槍を入れない。
318 = "はいはい、キミたちは横槍を入れない。"

# カズマ（Ｍ）
# display as カズマ
# （俺が好きなことっていったら、\n　当然ゲームだけど、さすがにそんな物は\n　この世界じゃ作れないし）
468 = "（俺が好きなことっていったら、\\n　当然ゲームだけど、さすがにそんな物は\\n　この世界じゃ作れないし）"

# カズマ（Ｍ）
# display as カズマ
# （だったら……）
456 = "（だったら……）"

# カズマ
# 本っていうのはどうかな？
365 = "本っていうのはどうかな？"

# クリス
# 本っていってもいろいろあるじゃない。
366 = "本っていってもいろいろあるじゃない。"

# アクア
# ！？
443 = "！？"

# カズマ
# いや、お前が想像したようなもんじゃないから。
261 = "いや、お前が想像したようなもんじゃないから。"

# アクア
# な、何を言ってるのかしら。\nわ、私、何も想像してないわよ。
310 = "な、何を言ってるのかしら。\\nわ、私、何も想像してないわよ。"

# カズマ
# へー。
321 = "へー。"

# ダクネス
# それで、カズマが考えるのはどのような本なんだ？
296 = "それで、カズマが考えるのはどのような本なんだ？"

# カズマ
# それはもちろん！　ライトノベルだ！
299 = "それはもちろん！　ライトノベルだ！"

# ダクネス
# 始めて聞く本の名前だな。
360 = "始めて聞く本の名前だな。"

# めぐみん
# 私も初耳です。
436 = "私も初耳です。"

# ゆんゆん
# うん、私も。
268 = "うん、私も。"

# ダクネス
# らいとのべるだったか？\nそれはどういう物なんだ？
333 = "らいとのべるだったか？\\nそれはどういう物なんだ？"

# カズマ
# まぁ、簡単に言っちまえば若い子に読みやすく\n描かれた娯楽小説だな。
324 = "まぁ、簡単に言っちまえば若い子に読みやすく\\n描かれた娯楽小説だな。"

# カズマ
# 俺の故郷では、血湧き肉躍る冒険活劇の話や\n恋愛青春物のラブストーリーみたいな話が\n中心だった。
355 = "俺の故郷では、血湧き肉躍る冒険活劇の話や\\n恋愛青春物のラブストーリーみたいな話が\\n中心だった。"

# めぐみん
# 冒険活劇！\nそれは確かに面白そうですね！
356 = "冒険活劇！\\nそれは確かに面白そうですね！"

# ゆんゆん
# 私は恋愛青春物っていうのを読んでみたいかも。
434 = "私は恋愛青春物っていうのを読んでみたいかも。"

# カズマ
# うん、ふたりに好感触なら芽があるかもしれない。
267 = "うん、ふたりに好感触なら芽があるかもしれない。"

# ダクネス
# なるほど、めぐみんとゆんゆんくらいの子が\n読む物なのか。
313 = "なるほど、めぐみんとゆんゆんくらいの子が\\n読む物なのか。"

# アクア
# ねえねえ、カズマ。\n私が主役っていうのはどうかしら！
316 = "ねえねえ、カズマ。\\n私が主役っていうのはどうかしら！"

# カズマ
# よし、聞くだけ聞いてやる。
332 = "よし、聞くだけ聞いてやる。"

# アクア
# 水の女神である私が世界を救う話よ。\n私は実名で出してくれていいからね。
370 = "水の女神である私が世界を救う話よ。\\n私は実名で出してくれていいからね。"

# カズマ
# いや、実名はマズイだろ。\n何があるかわかんないんだし。
262 = "いや、実名はマズイだろ。\\n何があるかわかんないんだし。"

# アクア
# そうしないと信者が集まらないでしょ。
291 = "そうしないと信者が集まらないでしょ。"

# カズマ（Ｍ）
# display as カズマ
# （そういう狙いか……）
454 = "（そういう狙いか……）"

# アクア
# 信者がたくさんできれば、\n念願の貢ぎ物生活も夢じゃなくなるわ！
353 = "信者がたくさんできれば、\\n念願の貢ぎ物生活も夢じゃなくなるわ！"

# カズマ
# そういう胡散臭いのは却下だ。
290 = "そういう胡散臭いのは却下だ。"

# クリス
# じゃあ、欲望渦巻く裏社会で、\n華麗に立ち回る１人の女盗賊のお話なんてどうかな？
288 = "じゃあ、欲望渦巻く裏社会で、\\n華麗に立ち回る１人の女盗賊のお話なんてどうかな？"

# カズマ
# まぁ、アクアの話よりは面白そうだな。
323 = "まぁ、アクアの話よりは面白そうだな。"

# アクア
# ええー。
272 = "ええー。"

# ダクネス
# おいカズマ！　私も１つアイディアがあるぞ。
276 = "おいカズマ！　私も１つアイディアがあるぞ。"

# ダクネス
# 正義のクルセイダーが魔王に囚われて、\nありとあらゆる拷問を受けるが、\n心までは支配されないという話はどうだ！
369 = "正義のクルセイダーが魔王に囚われて、\\nありとあらゆる拷問を受けるが、\\n心までは支配されないという話はどうだ！"

# カズマ
# なんか、聞いてるだけで痛くなるわ！
314 = "なんか、聞いてるだけで痛くなるわ！"

# ゆんゆん
# 私は！\n友達がいない魔法使いの女の子に、\nいっぱい友達が出来るお話がいいと思います！
435 = "私は！\\n友達がいない魔法使いの女の子に、\\nいっぱい友達が出来るお話がいいと思います！"

# カズマ
# それは、心が痛いからやめて。
297 = "それは、心が痛いからやめて。"

# アクア
# ダメよ！！　主人公は絶対に私なんだからね！
346 = "ダメよ！！　主人公は絶対に私なんだからね！"

# ダクネス
# いいや、私だ！
258 = "いいや、私だ！"

# ゆんゆん
# わ、私がいいです！
334 = "わ、私がいいです！"

# カズマ（Ｍ）
# display as カズマ
# （んー、いまいちぴんとこないものばかりだなぁ。\n　もっと斬新でキャッチーなものはないのかな）
463 = "（んー、いまいちぴんとこないものばかりだなぁ。\\n　もっと斬新でキャッチーなものはないのかな）"

# めぐみん
# ふっ……みんなのアイディアは普通ですね。\nそんなことでは、読者の興味をひけませんよ。
319 = "ふっ……みんなのアイディアは普通ですね。\\nそんなことでは、読者の興味をひけませんよ。"

# カズマ
# おっ、なんかいいネタでもあるのか？
278 = "おっ、なんかいいネタでもあるのか？"

# めぐみん
# もちろんです！\nこのアイディアは必ず売れますよ！
329 = "もちろんです！\\nこのアイディアは必ず売れますよ！"

# カズマ
# 自信満々だな。\nさっそく聞かせてくれ。
437 = "自信満々だな。\\nさっそく聞かせてくれ。"

# めぐみん
# コホン。\nでは、まずは主人公は、魔王と人間のハーフ！！
344 = "コホン。\\nでは、まずは主人公は、魔王と人間のハーフ！！"

# カズマ
# えっ……？
273 = "えっ……？"

# めぐみん
# 魔族にも人間にも疎まれ、居場所が無い主人公は\nとあるきっかけで、世界最強の力を手に入れて、\n自分を迫害した世界に復讐するのです！
441 = "魔族にも人間にも疎まれ、居場所が無い主人公は\\nとあるきっかけで、世界最強の力を手に入れて、\\n自分を迫害した世界に復讐するのです！"

# めぐみん
# 主人公は、一見平凡な男ですが、\n実は光速の斬撃を放つ大剣を持つ黒い剣士！
351 = "主人公は、一見平凡な男ですが、\\n実は光速の斬撃を放つ大剣を持つ黒い剣士！"

# めぐみん
# 疼く右手からは、霊力の籠もった光の矢が飛び出し、\nいつも閉じている片目を開けると、絶対服従の\n魔眼の呪いが発動する――
372 = "疼く右手からは、霊力の籠もった光の矢が飛び出し、\\nいつも閉じている片目を開けると、絶対服従の\\n魔眼の呪いが発動する――"

# めぐみん
# 謎の暗殺拳を使い指先１つで敵を倒したり、\n魔法を拳で打ち消しながら敵を説教したり！
439 = "謎の暗殺拳を使い指先１つで敵を倒したり、\\n魔法を拳で打ち消しながら敵を説教したり！"

# めぐみん
# さらに、ヒロインのキスで封印されていた力が\n目覚めるのです！
286 = "さらに、ヒロインのキスで封印されていた力が\\n目覚めるのです！"

# めぐみん
# あとは、自分のトラウマから発生した守護霊に\n守られていて、カードから幻獣を召喚して\n戦ったりもします。
255 = "あとは、自分のトラウマから発生した守護霊に\\n守られていて、カードから幻獣を召喚して\\n戦ったりもします。"

# めぐみん
# あ、そうそう、本人も最強の魔法使いですが、\n神官、氷の魔術師、エルフを\n従えて最強の軍団を作ったりもします！
253 = "あ、そうそう、本人も最強の魔法使いですが、\\n神官、氷の魔術師、エルフを\\n従えて最強の軍団を作ったりもします！"

# アクア
# な、なんか盛りすぎじゃない？
308 = "な、なんか盛りすぎじゃない？"

# ゆんゆん
# 魔王と人間のハーフって、そんなのありなの？
442 = "魔王と人間のハーフって、そんなのありなの？"

# クリス
# さっき、剣士だったのが、いつの間にか魔法使いに\nなってるしね。
285 = "さっき、剣士だったのが、いつの間にか魔法使いに\\nなってるしね。"

# カズマ（Ｍ）
# display as カズマ
# （流石めぐみん。\n　厨二病は厨二病を知ると言ったところなのか）
473 = "（流石めぐみん。\\n　厨二病は厨二病を知ると言ったところなのか）"

# めぐみん
# まだまだ続きますよ！\n敵はこうです！！
325 = "まだまだ続きますよ！\\n敵はこうです！！"

# カズマ
# めぐみん、もうやめてくれ。\nお前が言いたいことは、充分わかった。
328 = "めぐみん、もうやめてくれ。\\nお前が言いたいことは、充分わかった。"

# めぐみん
# なぜ止めるんですか？\nここからがいいところなのに。
311 = "なぜ止めるんですか？\\nここからがいいところなのに。"

# カズマ
# いっぺんに聞いても、\n憶えきれそうにないんだよ。
260 = "いっぺんに聞いても、\\n憶えきれそうにないんだよ。"

# めぐみん
# そうですか、わかりました。\n今回はこの辺にしておきます。
293 = "そうですか、わかりました。\\n今回はこの辺にしておきます。"

# カズマ
# う、うん、また今度聞かせて貰うよ。
265 = "う、うん、また今度聞かせて貰うよ。"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんの厨二病を侮っていたぜ！\n　ぽんぽんぽんぽん、湯水のように\n　設定が出てきやがる）
461 = "（めぐみんの厨二病を侮っていたぜ！\\n　ぽんぽんぽんぽん、湯水のように\\n　設定が出てきやがる）"

# カズマ
# 悪くないな……。
364 = "悪くないな……。"

# めぐみん
# でしょう？　流石カズマ、\nわかってくれると思っていました！
307 = "でしょう？　流石カズマ、\\nわかってくれると思っていました！"

# カズマ
# だけど、アクアが言ったとおり盛りすぎだから、\n少し調整する必要があるかもな。
303 = "だけど、アクアが言ったとおり盛りすぎだから、\\n少し調整する必要があるかもな。"

# めぐみん
# なるほど、まだ荒削りなので、\n更に設定を煮詰めるわけですね。
312 = "なるほど、まだ荒削りなので、\\n更に設定を煮詰めるわけですね。"

# カズマ
# まぁ、そうだな。
322 = "まぁ、そうだな。"

# カズマ（Ｍ）
# display as カズマ
# （厨二病設定はアクセントの１つにはなるが、\n　下手に使うとギャグになっちまうからな）
470 = "（厨二病設定はアクセントの１つにはなるが、\\n　下手に使うとギャグになっちまうからな）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、驚いたな。\n　ここまで厨二病設定に造詣が深いとは）
453 = "（しかし、驚いたな。\\n　ここまで厨二病設定に造詣が深いとは）"

# カズマ（Ｍ）
# display as カズマ
# （やっぱり、素で厨二病のヤツは違うなぁ）
462 = "（やっぱり、素で厨二病のヤツは違うなぁ）"

# カズマ
# さすめぐみんだな！
284 = "さすめぐみんだな！"

# めぐみん
# ふっ、当然です。
320 = "ふっ、当然です。"

# カズマ
# しかしまだまだだ。\nめぐみんがまだたどり着いていない設定が、\n俺の中にはある！
287 = "しかしまだまだだ。\\nめぐみんがまだたどり着いていない設定が、\\n俺の中にはある！"

# めぐみん
# な、なんですとー！？\nお、教えてくださいその設定を！
309 = "な、なんですとー！？\\nお、教えてくださいその設定を！"

# カズマ
# それは別の機会をもうけて\nじっくりと話をしよう。
300 = "それは別の機会をもうけて\\nじっくりと話をしよう。"

# めぐみん
# 楽しみにしていますよ、カズマ。
367 = "楽しみにしていますよ、カズマ。"

# カズマ
# ああ、俺もだ、めぐみん。
254 = "ああ、俺もだ、めぐみん。"

# アクア
# ねえねえ、思ったことを言ってもいいかしら？
317 = "ねえねえ、思ったことを言ってもいいかしら？"

# カズマ
# おう、意見は大歓迎だぞ。
277 = "おう、意見は大歓迎だぞ。"

# アクア
# ごちゃごちゃしててわかりにくいわ。\nそれに、そんな設定の本を誰が読むの？
282 = "ごちゃごちゃしててわかりにくいわ。\\nそれに、そんな設定の本を誰が読むの？"

# めぐみん
# それはもちろん、我が同士たちです！
298 = "それはもちろん、我が同士たちです！"

# ゆんゆん
# 確かにそうね。\nみんなこういう話し好きそうだし。
433 = "確かにそうね。\\nみんなこういう話し好きそうだし。"

# クリス
# うーん、ダクネスは今のめぐみんが考えた\n設定をどう思う？
270 = "うーん、ダクネスは今のめぐみんが考えた\\n設定をどう思う？"

# ダクネス
# そうだな。\n私にはちょっと難しすぎるかもしれない。
292 = "そうだな。\\n私にはちょっと難しすぎるかもしれない。"

# クリス
# あはは、実は私もなんだよね。
257 = "あはは、実は私もなんだよね。"

# めぐみん
# フッ、至高の物語とは万人に受け入れられぬ物。\nでも安心してください、紅魔族には売れますから！
348 = "フッ、至高の物語とは万人に受け入れられぬ物。\\nでも安心してください、紅魔族には売れますから！"

# カズマ
# おいおいおいおい！　大ヒット狙ってんのに、\n紅魔族にしか売れないなんて商売になるかー！
275 = "おいおいおいおい！　大ヒット狙ってんのに、\\n紅魔族にしか売れないなんて商売になるかー！"

# めぐみん
# えぇぇっ！？\nこの本が出たら、私が３冊買いますから！\nゆんゆんは１００冊買うそうです！
271 = "えぇぇっ！？\\nこの本が出たら、私が３冊買いますから！\\nゆんゆんは１００冊買うそうです！"

# ゆんゆん
# えっ！？　な、何で私が１００冊なの！？
274 = "えっ！？　な、何で私が１００冊なの！？"

# カズマ
# 中止だ中止！\nライトノベル計画は中止だ！
350 = "中止だ中止！\\nライトノベル計画は中止だ！"

# めぐみん
# そんなぁ！！\nせっかく良いアイディアを出したのに！
301 = "そんなぁ！！\\nせっかく良いアイディアを出したのに！"

# カズマ（Ｍ）
# display as カズマ
# （はぁぁ、マニアックすぎると、\n　一般には広まらないということか）
459 = "（はぁぁ、マニアックすぎると、\\n　一般には広まらないということか）"

# カズマ（Ｍ）
# display as カズマ
# （冷静に考えてみると、\n　この世界の出版事情ってどうなってんだ？）
469 = "（冷静に考えてみると、\\n　この世界の出版事情ってどうなってんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （まずは、本屋という物がメジャーじゃ\n　なさそうだし、どこで売るかとか色々\n　問題がありそうだな……）
460 = "（まずは、本屋という物がメジャーじゃ\\n　なさそうだし、どこで売るかとか色々\\n　問題がありそうだな……）"

# カズマ（Ｍ）
# display as カズマ
# （うーむ。\n　そこら辺の事情に詳しそうなヤツは）
446 = "（うーむ。\\n　そこら辺の事情に詳しそうなヤツは）"

# カズマ（Ｍ）
# display as カズマ
# （おっ、そういや、\n　商才に溢れたヤツがいたっけ）
449 = "（おっ、そういや、\\n　商才に溢れたヤツがいたっけ）"

# カズマ（Ｍ）
# display as カズマ
# （バニルのヤツに話を聞いてみるか）
466 = "（バニルのヤツに話を聞いてみるか）"

[selections]
327 = "めぐみん、もうやめてくれ"
363 = "悪くないな……"
283 = "さすがめぐみんだな！"
