# st03b_07.txt.scn

[info]
0 = ""

[characters]
367 = "カズマ"
355 = "ゆんゆん"
366 = "ウィズ"
351 = "めぐみん"
373 = "クリス"
374 = "ダクネス"
369 = "カズマ（Ｍ）"
375 = "ダスト"
370 = "キース"
365 = "アクア"

[character_subs]
# 367 = "カズマ"

[script]
# lines: 121

# カズマ
# よーし、次の特訓を始めるぞ。
362 = "よーし、次の特訓を始めるぞ。"

# ゆんゆん
# あ、あの！　こんなところでいったい何を……。
272 = "あ、あの！　こんなところでいったい何を……。"

# ウィズ
# 周りからの視線が恥ずかしいです。
388 = "周りからの視線が恥ずかしいです。"

# めぐみん
# カズマ、特訓なら人が居ないところで\nやりましょうよ。
368 = "カズマ、特訓なら人が居ないところで\\nやりましょうよ。"

# カズマ
# おいおい、これくらいで腰が引けてどうするんだ。
302 = "おいおい、これくらいで腰が引けてどうするんだ。"

# カズマ
# アイドルは、もっと沢山の人の前で歌や踊りを\n披露しないといけないんだぞ。
364 = "アイドルは、もっと沢山の人の前で歌や踊りを\\n披露しないといけないんだぞ。"

# クリス
# もういいからさ、早く特訓をやっちゃおうよ。\nそうすれば帰れるんだし。
353 = "もういいからさ、早く特訓をやっちゃおうよ。\\nそうすれば帰れるんだし。"

# カズマ
# 特訓ならもう始まってるぞ。
396 = "特訓ならもう始まってるぞ。"

# クリス
# え、そうなの？
290 = "え、そうなの？"

# カズマ
# お前たちが恥ずかしがるのはわかっていた。\nだから――
305 = "お前たちが恥ずかしがるのはわかっていた。\\nだから――"

# ダクネス
# はっ！
345 = "はっ！"

# クリス
# え？　どうしたのダクネス！？
297 = "え？　どうしたのダクネス！？"

# ダクネス
# そうか、なるほど、そういうことか。
324 = "そうか、なるほど、そういうことか。"

# クリス
# だから、どうしたのさ。
328 = "だから、どうしたのさ。"

# ダクネス
# 事前に内容を知らせないとは、\nさすがカズマ、いたぶられる側の心理を\nしっかりと把握している。
382 = "事前に内容を知らせないとは、\\nさすがカズマ、いたぶられる側の心理を\\nしっかりと把握している。"

# クリス
# い、いたぶる！？
279 = "い、いたぶる！？"

# カズマ
# お、おおおい、変態クルセイダー！\n誤解を生むような言い方をするな！
300 = "お、おおおい、変態クルセイダー！\\n誤解を生むような言い方をするな！"

# ダクネス
# つまりこういうことなのだろう、カズマ。
331 = "つまりこういうことなのだろう、カズマ。"

# ダクネス
# お前は、羞恥に耐えるという名目で、\n私たちを野獣の檻の中に放り込んだ。
310 = "お前は、羞恥に耐えるという名目で、\\n私たちを野獣の檻の中に放り込んだ。"

# ダクネス
# 何も知らされていない私たちは、\n未知の恐怖に怯えることしかできない。
385 = "何も知らされていない私たちは、\\n未知の恐怖に怯えることしかできない。"

# ダクネス
# お前には最高のご褒美だったのだろうな。
307 = "お前には最高のご褒美だったのだろうな。"

# ダクネス
# 気の強い女冒険者たちが肩を寄せ合い怯える姿は、\nそれはもう至極の光景だっただろう。
394 = "気の強い女冒険者たちが肩を寄せ合い怯える姿は、\\nそれはもう至極の光景だっただろう。"

# ダクネス
# ふ、ふふ、私たちは、カズマのそんな思惑に\n見事に踊らされてしまったというわけだ。
346 = "ふ、ふふ、私たちは、カズマのそんな思惑に\\n見事に踊らされてしまったというわけだ。"

# ダクネス
# これから何をさせられるんだろう。\nもしかして借金の形として売られるのか？
315 = "これから何をさせられるんだろう。\\nもしかして借金の形として売られるのか？"

# ダクネス
# 売られた貴族の屋敷で私たちは、\nメイドとしてこき使われ――
389 = "売られた貴族の屋敷で私たちは、\\nメイドとしてこき使われ――"

# ダクネス
# そ、そ、そして、言葉にすることも\nためらわれるような辱めを――
321 = "そ、そ、そして、言葉にすることも\\nためらわれるような辱めを――"

# カズマ
# というわけでみんなには、\nその衣装を着ても大勢の前に立てるように、\n握手会の真似事をしてもらいます。
334 = "というわけでみんなには、\\nその衣装を着ても大勢の前に立てるように、\\n握手会の真似事をしてもらいます。"

# ウィズ
# あ、握手会とは？
274 = "あ、握手会とは？"

# カズマ
# まあ、ファンと交流する手段のひとつだよ。
349 = "まあ、ファンと交流する手段のひとつだよ。"

# ゆんゆん
# ええと、つまり。\nただ握手をするだけなんですね。
292 = "ええと、つまり。\\nただ握手をするだけなんですね。"

# カズマ
# そう、ただそれだけ、簡単だろ。
322 = "そう、ただそれだけ、簡単だろ。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、何百人もと\n　しなくちゃいけないんだけどな）
480 = "（まあ、何百人もと\\n　しなくちゃいけないんだけどな）"

# カズマ
# というわけで、そのファンの役目だが、\nダストとキースにやってもらおうと思う。
333 = "というわけで、そのファンの役目だが、\\nダストとキースにやってもらおうと思う。"

# ダスト
# し、しょうがねぇな。
319 = "し、しょうがねぇな。"

# キース
# お、俺は忙しいんだが、\nカズマがどうしてもっていうから仕方なく。
301 = "お、俺は忙しいんだが、\\nカズマがどうしてもっていうから仕方なく。"

# カズマ
# よし、じゃあ早速アクアからやってみろ。\nキース相手を頼む。
357 = "よし、じゃあ早速アクアからやってみろ。\\nキース相手を頼む。"

# アクア
# ええと、こうかしら？
291 = "ええと、こうかしら？"

# キース
# あ、ああ、どうも。
271 = "あ、ああ、どうも。"

# アクア
# いいえ、どういたしまして。
282 = "いいえ、どういたしまして。"

# カズマ
# ちっがーう！！　アクアお前舐めてんのか？
329 = "ちっがーう！！　アクアお前舐めてんのか？"

# アクア
# な、なによ！　ちゃんと握手したじゃない？
336 = "な、なによ！　ちゃんと握手したじゃない？"

# カズマ
# お前は、この握手の意味を\nちっともわかってねーだろ！
309 = "お前は、この握手の意味を\\nちっともわかってねーだろ！"

# アクア
# 意味って何よ。\nただ手を握るだけでしょ。
393 = "意味って何よ。\\nただ手を握るだけでしょ。"

# カズマ
# よし、みんなも聞いてくれ。\nこの握手会は、ただファンと交流するだけが\n目的じゃない。
359 = "よし、みんなも聞いてくれ。\\nこの握手会は、ただファンと交流するだけが\\n目的じゃない。"

# クリス
# 他にどんな目的があるっていうのさ。
384 = "他にどんな目的があるっていうのさ。"

# カズマ
# プレゼン、つまり自分の売り込みだ。
378 = "プレゼン、つまり自分の売り込みだ。"

# カズマ
# 男ってのは、笑顔で手を握られただけで\nあっ、もしかして俺に惚れてる？\nなんて、幸せな勘違いをする生き物。
398 = "男ってのは、笑顔で手を握られただけで\\nあっ、もしかして俺に惚れてる？\\nなんて、幸せな勘違いをする生き物。"

# ウィズ
# な、なるほど、愛想を振りまけというわけですね。
337 = "な、なるほど、愛想を振りまけというわけですね。"

# カズマ
# そう、ファンを取り込むために！
323 = "そう、ファンを取り込むために！"

# クリス
# なんていうか、あざといねー。
339 = "なんていうか、あざといねー。"

# カズマ
# というわけで、おい、変態クルセイダー！
332 = "というわけで、おい、変態クルセイダー！"

# ダクネス
# ふふ、なるほど、そういうプレイを望むか。\nいいだろう、ただ体は自由にできても心までは――
347 = "ふふ、なるほど、そういうプレイを望むか。\\nいいだろう、ただ体は自由にできても心までは――"

# カズマ
# こっちに戻って来い！
314 = "こっちに戻って来い！"

# ダクネス
# ぬはっ！　な、なんだ！
340 = "ぬはっ！　な、なんだ！"

# カズマ
# キースと握手をしてくれるか？
372 = "キースと握手をしてくれるか？"

# ダクネス
# どうしてそんなことを。
335 = "どうしてそんなことを。"

# カズマ
# いいから握るんだ。
283 = "いいから握るんだ。"

# ダクネス
# 理由くらい説明してくれ。
397 = "理由くらい説明してくれ。"

# カズマ
# お前なんかに、必要ない。
306 = "お前なんかに、必要ない。"

# ダクネス
# お前、なんかっ！
304 = "お前、なんかっ！"

# カズマ
# ほら、早くやれよ。
348 = "ほら、早くやれよ。"

# ダクネス
# くっ、手を握るだけでいいんだな。
311 = "くっ、手を握るだけでいいんだな。"

# カズマ
# さあ、それだけで済めばいいけどな。
317 = "さあ、それだけで済めばいいけどな。"

# ダクネス
# な、何！？
338 = "な、何！？"

# キース
# え、ええと、じゃあ握手を……。
289 = "え、ええと、じゃあ握手を……。"

# ダクネス
# ハァハァハァハァ……。
376 = "ハァハァハァハァ……。"

# キース
# う、うう！？
286 = "う、うう！？"

# ダクネス
# こ、これで、いいのか？
312 = "こ、これで、いいのか？"

# カズマ
# おう、ごくろうさん。
303 = "おう、ごくろうさん。"

# カズマ
# キース、どんな感じだった。
371 = "キース、どんな感じだった。"

# キース
# いい……すごくいい。\nドキドキした。
280 = "いい……すごくいい。\\nドキドキした。"

# カズマ
# はい、つまりこれ！
344 = "はい、つまりこれ！"

# クリス
# あは、あはは、なんとなくわかったけど、\nあたしたちにはハードルが高すぎるかな。
278 = "あは、あはは、なんとなくわかったけど、\\nあたしたちにはハードルが高すぎるかな。"

# カズマ
# ここまですることはないさ。\nただ、相手を喜ばせるってことは\n常に意識しておいてくれ。
313 = "ここまですることはないさ。\\nただ、相手を喜ばせるってことは\\n常に意識しておいてくれ。"

# ウィズ
# わ、私にできるでしょうか。
363 = "わ、私にできるでしょうか。"

# カズマ
# よし、じゃあ次はウィズな。
358 = "よし、じゃあ次はウィズな。"

# ウィズ
# ええ！？
294 = "ええ！？"

# カズマ
# 相手はダスト、頼んだぞ。
475 = "相手はダスト、頼んだぞ。"

# ダスト
# お、おう。
298 = "お、おう。"

# ウィズ
# えっと……ダストさんっ、\nあ、あの、あ、あ、握手を……。
296 = "えっと……ダストさんっ、\\nあ、あの、あ、あ、握手を……。"

# ダスト
# は、はい、いえ！
341 = "は、はい、いえ！"

# ウィズ
# あ、やっぱり私とじゃ嫌ですよね。
273 = "あ、やっぱり私とじゃ嫌ですよね。"

# ダスト
# いえ、そうではなく！\n恐れ多いと言いますか！
284 = "いえ、そうではなく！\\n恐れ多いと言いますか！"

# ウィズ
# そんな、お気になさらず、握手を。
326 = "そんな、お気になさらず、握手を。"

# ダスト
# は、はい！
342 = "は、はい！"

# ウィズ
# ～～～～～～～～！
484 = "～～～～～～～～！"

# ダスト
# はぁぁぁぁぁ。
343 = "はぁぁぁぁぁ。"

# カズマ
# これだこれ！　わかるか！
316 = "これだこれ！　わかるか！"

# めぐみん
# よくわかりません。
356 = "よくわかりません。"

# カズマ
# 笑顔を振りまくだけじゃダメ。\nこういう羞恥を見せるのも手段のひとつなんだ。
476 = "笑顔を振りまくだけじゃダメ。\\nこういう羞恥を見せるのも手段のひとつなんだ。"

# カズマ
# 頬の紅潮、上目遣い、強ばる肩の仕草まで\nもう完璧！　非の打ち所無し！
477 = "頬の紅潮、上目遣い、強ばる肩の仕草まで\\nもう完璧！　非の打ち所無し！"

# カズマ
# もっともいいのは握手の仕方！
354 = "もっともいいのは握手の仕方！"

# カズマ
# 相手の手を自分の両手で優しく包み込むように、\n握る！　俺なら間違いなく惚れてる！
474 = "相手の手を自分の両手で優しく包み込むように、\\n握る！　俺なら間違いなく惚れてる！"

# ゆんゆん
# む、難しすぎるよ～。
350 = "む、難しすぎるよ～。"

# めぐみん
# 今すぐ逃げ出したいですよ、私は。
383 = "今すぐ逃げ出したいですよ、私は。"

# ウィズ
# あっ、あのっ、ダストさん？\nそ、そろそろ手を離していただけると……。
276 = "あっ、あのっ、ダストさん？\\nそ、そろそろ手を離していただけると……。"

# カズマ
# あっ、こら、お前！\nいつまでウィズの手を握ってるんだ！\n握手は３秒までなんだよ！
277 = "あっ、こら、お前！\\nいつまでウィズの手を握ってるんだ！\\n握手は３秒までなんだよ！"

# キース
# し、知らねーよそんなルールなんか！
320 = "し、知らねーよそんなルールなんか！"

# カズマ
# ああもぅ、次だ次！　今度はキースな！\nウィズすまないが、もう１回みんなに手本を\n見せてやってくれ。
275 = "ああもぅ、次だ次！　今度はキースな！\\nウィズすまないが、もう１回みんなに手本を\\n見せてやってくれ。"

# アクア
# いいえ、ここは私がやるわ！
281 = "いいえ、ここは私がやるわ！"

# カズマ
# ちゃんとできるのか？
330 = "ちゃんとできるのか？"

# アクア
# 当然よ！\nなんてたって私は、センターの筆頭なのよ！
392 = "当然よ！\\nなんてたって私は、センターの筆頭なのよ！"

# カズマ（Ｍ）
# display as カズマ
# （なるほど、ウィズへの対抗心か）
478 = "（なるほど、ウィズへの対抗心か）"

# アクア
# うふ、さあ、私と握手しましょう？
287 = "うふ、さあ、私と握手しましょう？"

# アクア
# そうだ、特別に癒し魔法のオプションを\nつけてあげる。
325 = "そうだ、特別に癒し魔法のオプションを\\nつけてあげる。"

# アクア
# さらに今ならなんと、\n１日だけ効果が続く祝福つきよ。
318 = "さらに今ならなんと、\\n１日だけ効果が続く祝福つきよ。"

# アクア
# だから、このアクア様を崇めなさい。
327 = "だから、このアクア様を崇めなさい。"

# キース
# ええ？　何この胡散臭い勧誘。
295 = "ええ？　何この胡散臭い勧誘。"

# カズマ
# お前は、くだらないことすんな！
308 = "お前は、くだらないことすんな！"

# アクア
# いったぁぁい！
285 = "いったぁぁい！"

# カズマ
# よーし、みんな横一列に並んで、\nダストとキースに握手をするんだ。
361 = "よーし、みんな横一列に並んで、\\nダストとキースに握手をするんだ。"

# ゆんゆん
# よっ、よろしくお願いします。
360 = "よっ、よろしくお願いします。"

# ダスト
# お、おう！　こっちこそよろしく！
299 = "お、おう！　こっちこそよろしく！"

# クリス
# ええと、よろしくね。
293 = "ええと、よろしくね。"

# キース
# も、もちろんだぜ！　俺に任せとけって！
352 = "も、もちろんだぜ！　俺に任せとけって！"

# めぐみん
# フフフ、よろしく頼むのです。
377 = "フフフ、よろしく頼むのです。"

# ダスト
# うん、応援するよ、頑張れよな。
288 = "うん、応援するよ、頑張れよな。"

# カズマ（Ｍ）
# display as カズマ
# （みんなぎこちないけど、\n　上手くやっているようだな）
481 = "（みんなぎこちないけど、\\n　上手くやっているようだな）"

# カズマ（Ｍ）
# display as カズマ
# （ふふ、ここで握手会の練習をしたのは\n　正解だったな）
479 = "（ふふ、ここで握手会の練習をしたのは\\n　正解だったな）"

# カズマ（Ｍ）
# display as カズマ
# （興味を持った連中から、クチコミでうちの\n　アイドル達のウワサも広がりそうだし）
483 = "（興味を持った連中から、クチコミでうちの\\n　アイドル達のウワサも広がりそうだし）"

# カズマ（Ｍ）
# display as カズマ
# （よしよし、\n　これはいい宣伝になりそうだぜ）
482 = "（よしよし、\\n　これはいい宣伝になりそうだぜ）"

