# st03c_04.txt.scn

[info]
0 = ""

[characters]
98 = "カズマ（Ｍ）"
97 = "カズマ"
99 = "ルナ"

[character_subs]
# 97 = "カズマ"

[script]
# lines: 26

# カズマ（Ｍ）
# display as カズマ
# （アクセルの街に衝撃をもたらした、\n　伝説のファーストライブから数日後――）
125 = "（アクセルの街に衝撃をもたらした、\\n　伝説のファーストライブから数日後――）"

# カズマ（Ｍ）
# display as カズマ
# （俺たちは、勢いに任せて突っ走った）
129 = "（俺たちは、勢いに任せて突っ走った）"

# カズマ（Ｍ）
# display as カズマ
# （アイドルグループシャイニーブルーは\n　毎日ライブを行い、サイン会や握手会も\n　精力的にやった）
124 = "（アイドルグループシャイニーブルーは\\n　毎日ライブを行い、サイン会や握手会も\\n　精力的にやった）"

# カズマ（Ｍ）
# display as カズマ
# （噂が噂を呼び、郊外からもファンが\n　押し寄せて会場は大混乱）
130 = "（噂が噂を呼び、郊外からもファンが\\n　押し寄せて会場は大混乱）"

# カズマ（Ｍ）
# display as カズマ
# （一時、街の警備兵から注意を受けたが、\n　ファンの協力もあり、ライブはなんとか\n　続行出来た）
126 = "（一時、街の警備兵から注意を受けたが、\\n　ファンの協力もあり、ライブはなんとか\\n　続行出来た）"

# カズマ（Ｍ）
# display as カズマ
# （まぁ、トラブルがあったとしても、\n　そのくらいの方が人気アイドルっぽいし、\n　むしろウェルカムだ）
121 = "（まぁ、トラブルがあったとしても、\\n　そのくらいの方が人気アイドルっぽいし、\\n　むしろウェルカムだ）"

# カズマ（Ｍ）
# display as カズマ
# （そう俺たちは、さらにファンを獲得するために\n　頑張った）
115 = "（そう俺たちは、さらにファンを獲得するために\\n　頑張った）"

# カズマ（Ｍ）
# display as カズマ
# （そう、頑張ったんだ！！）
114 = "（そう、頑張ったんだ！！）"

# カズマ（Ｍ）
# display as カズマ
# （しかし……）
113 = "（しかし……）"

# カズマ（Ｍ）
# display as カズマ
# （この間、ついに恐れていたことが発覚した。\n　転売ヤーの登場。そして偽造チケットの横行。\n　さらには無許可グッズの販売だ）
112 = "（この間、ついに恐れていたことが発覚した。\\n　転売ヤーの登場。そして偽造チケットの横行。\\n　さらには無許可グッズの販売だ）"

# カズマ（Ｍ）
# display as カズマ
# （他人の景気が良いと、甘い汁を吸おうと\n　絡んでくるヤツが後を絶たないのはわかっては\n　いたが、いざ相手にするとやっかいだった）
128 = "（他人の景気が良いと、甘い汁を吸おうと\\n　絡んでくるヤツが後を絶たないのはわかっては\\n　いたが、いざ相手にするとやっかいだった）"

# カズマ（Ｍ）
# display as カズマ
# （まぁ、その対策も考えつつ、新たな試みとして\n　有料イベントを開催してみたのだが――）
120 = "（まぁ、その対策も考えつつ、新たな試みとして\\n　有料イベントを開催してみたのだが――）"

# カズマ（Ｍ）
# display as カズマ
# （なぜか、以前よりファンの数が減ってきた\n　という報告を受けた）
117 = "（なぜか、以前よりファンの数が減ってきた\\n　という報告を受けた）"

# カズマ（Ｍ）
# display as カズマ
# （その原因は何だ？\n　もう飽きられてしまったのか？）
116 = "（その原因は何だ？\\n　もう飽きられてしまったのか？）"

# カズマ（Ｍ）
# display as カズマ
# （もしかしてチケットを強気の値段設定にした\n　せいか？）
123 = "（もしかしてチケットを強気の値段設定にした\\n　せいか？）"

# カズマ（Ｍ）
# display as カズマ
# （このままではまずい……）
111 = "（このままではまずい……）"

# カズマ（Ｍ）
# display as カズマ
# （今回は、街の有力者やギルドにも根回しをして、\n　そこからの圧力は無いというのに……）
127 = "（今回は、街の有力者やギルドにも根回しをして、\\n　そこからの圧力は無いというのに……）"

# カズマ（Ｍ）
# display as カズマ
# （このままじゃ、俺のプロデューサーとしての\n　面目にもかかってくる）
110 = "（このままじゃ、俺のプロデューサーとしての\\n　面目にもかかってくる）"

# カズマ（Ｍ）
# display as カズマ
# （なんとか状況を整理して立て直さねば……）
119 = "（なんとか状況を整理して立て直さねば……）"

# カズマ
# ぐぬぬ、客が減った原因がさっぱりわからん。
95 = "ぐぬぬ、客が減った原因がさっぱりわからん。"

# ルナ
# あ、あの……サトウさん。
93 = "あ、あの……サトウさん。"

# カズマ
# えっ？\nああ、なんですか？
94 = "えっ？\\nああ、なんですか？"

# ルナ
# ちょっと相談事があるのですが。
96 = "ちょっと相談事があるのですが。"

# カズマ
# 俺に？
101 = "俺に？"

# カズマ（Ｍ）
# display as カズマ
# （なんだろう、相談事って？）
118 = "（なんだろう、相談事って？）"

# カズマ（Ｍ）
# display as カズマ
# （もしかして、アイドルグループに\n　入れて欲しいって相談かな？）
122 = "（もしかして、アイドルグループに\\n　入れて欲しいって相談かな？）"

