# st03b_11.txt.scn

[info]
0 = ""

[characters]
211 = "カズマ"
206 = "ゆんゆん"
203 = "めぐみん"
210 = "ウィズ"
213 = "ダクネス"
209 = "アクア"
212 = "クリス"

[character_subs]

[script]
# lines: 41

# カズマ
# さて、次のレッスンだ。
190 = "さて、次のレッスンだ。"

# ゆんゆん
# ねぇめぐみん、今までのレッスンのこと\n全部憶えてる？
198 = "ねぇめぐみん、今までのレッスンのこと\\n全部憶えてる？"

# めぐみん
# も、もちろんですよ！\nゆんゆんと一緒にしないでください。
204 = "も、もちろんですよ！\\nゆんゆんと一緒にしないでください。"

# ゆんゆん
# 沢山憶えることがありすぎて、\n一晩眠ったら忘れちゃいそうだよ。
229 = "沢山憶えることがありすぎて、\\n一晩眠ったら忘れちゃいそうだよ。"

# めぐみん
# ふっ、それがゆんゆんの限界って事ですね。
199 = "ふっ、それがゆんゆんの限界って事ですね。"

# ゆんゆん
# もーっ、意地悪言わないでよ。
205 = "もーっ、意地悪言わないでよ。"

# カズマ
# ほらほら、今から大事なことを言うんだから、\nちゃんと聞いてくれ。
201 = "ほらほら、今から大事なことを言うんだから、\\nちゃんと聞いてくれ。"

# カズマ
# 次のレッスンは、卒業式の練習だ！
228 = "次のレッスンは、卒業式の練習だ！"

# ウィズ
# ええ！？\nまだ始まってもいないのに卒業の練習ですか！？
185 = "ええ！？\\nまだ始まってもいないのに卒業の練習ですか！？"

# ダクネス
# そ、それはどういう意味だカズマ？\nわ、私に何か落ち度でもあったのか？
193 = "そ、それはどういう意味だカズマ？\\nわ、私に何か落ち度でもあったのか？"

# カズマ
# まぁまぁ、みんな落ち着け。\n何事にも始まりがあれば、終わりが来る。\n人生もそうだし、アイドルももちろんそうなんだ。
202 = "まぁまぁ、みんな落ち着け。\\n何事にも始まりがあれば、終わりが来る。\\n人生もそうだし、アイドルももちろんそうなんだ。"

# カズマ
# なぜデビュー前に、卒業式の練習をするか\nというのはだな、アイドル卒業後には、\n次のステップへの道があるからだ。
197 = "なぜデビュー前に、卒業式の練習をするか\\nというのはだな、アイドル卒業後には、\\n次のステップへの道があるからだ。"

# カズマ
# 例えば、留学だったり、女優の道へ進むだったり、\n結婚だったり、卒業は終わりなんかじゃ無い、\n長い人生の通過点なんだ！
216 = "例えば、留学だったり、女優の道へ進むだったり、\\n結婚だったり、卒業は終わりなんかじゃ無い、\\n長い人生の通過点なんだ！"

# カズマ
# アイドル人生には限りがあるということを理解して、\nその短い時間で完全燃焼するという\n覚悟を持つ為にも、卒業式の練習をする！
208 = "アイドル人生には限りがあるということを理解して、\\nその短い時間で完全燃焼するという\\n覚悟を持つ為にも、卒業式の練習をする！"

# アクア
# な、なんかカズマがマジになっちゃってるん\nですけど。
196 = "な、なんかカズマがマジになっちゃってるん\\nですけど。"

# めぐみん
# そうですね……なんか怖いです。
194 = "そうですね……なんか怖いです。"

# ダクネス
# しかし、カズマが言っていることは、\n私にもわかるぞ。
191 = "しかし、カズマが言っていることは、\\n私にもわかるぞ。"

# カズマ
# 卒業の際、大切なのはファンに残す最後の\nスピーチだ。
217 = "卒業の際、大切なのはファンに残す最後の\\nスピーチだ。"

# カズマ
# 惜しまれつつも、最後の言葉はファンの胸に\n残り続け、そして人々に語り継がれる。
224 = "惜しまれつつも、最後の言葉はファンの胸に\\n残り続け、そして人々に語り継がれる。"

# カズマ
# だから、みんなもアイドルを経験してきたことを\n振り返りながら、自分の気持ちを、\n真心を言葉にして残して欲しい。
195 = "だから、みんなもアイドルを経験してきたことを\\n振り返りながら、自分の気持ちを、\\n真心を言葉にして残して欲しい。"

# クリス
# いやあ、まだ始めてもいないことの経験を\n言葉にしろと言われても……。
180 = "いやあ、まだ始めてもいないことの経験を\\n言葉にしろと言われても……。"

# めぐみん
# 本当ですよ。\n振り返るアイドル人生も無いというのに。
227 = "本当ですよ。\\n振り返るアイドル人生も無いというのに。"

# カズマ
# 今から考えておいて損はないんだって。\nいざ卒業するときに困らないだろ？
215 = "今から考えておいて損はないんだって。\\nいざ卒業するときに困らないだろ？"

# カズマ
# あ、１人ずつ発表してもらうからな。\nそうそう、自分のキャラ付けを忘れるなよ。
176 = "あ、１人ずつ発表してもらうからな。\\nそうそう、自分のキャラ付けを忘れるなよ。"

# カズマ
# よし、みんないいか？\nじゃあ、アクアから発表だ！
207 = "よし、みんないいか？\\nじゃあ、アクアから発表だ！"

# アクア
# ええと、そうね。\n私は普通の女神に戻ります。
183 = "ええと、そうね。\\n私は普通の女神に戻ります。"

# カズマ
# 普通の女神ってなんだ。
226 = "普通の女神ってなんだ。"

# アクア
# さあ、何かしら。
189 = "さあ、何かしら。"

# カズマ
# ああ、もうっ！　じゃあ、めぐみん！
177 = "ああ、もうっ！　じゃあ、めぐみん！"

# めぐみん
# 我の顕現の刻はこれにて終了。\nだが、伝説はこれからも語り継がれる！\n努々忘れるな！　我が覇業を！
225 = "我の顕現の刻はこれにて終了。\\nだが、伝説はこれからも語り継がれる！\\n努々忘れるな！　我が覇業を！"

# カズマ
# おお、いいじゃないか、さすがめぐみんだな。
187 = "おお、いいじゃないか、さすがめぐみんだな。"

# めぐみん
# ふっ、当たり前じゃないですか、\n私を誰だと思っているんですか？
200 = "ふっ、当たり前じゃないですか、\\n私を誰だと思っているんですか？"

# カズマ
# じゃ、ダクネスいってみよう！
192 = "じゃ、ダクネスいってみよう！"

# ダクネス
# 夢から覚める時間が来たようだ。\nよもや会うことも叶わぬだろう。
221 = "夢から覚める時間が来たようだ。\\nよもや会うことも叶わぬだろう。"

# カズマ
# うんうん、良い雰囲気が出てるぞ。\nクリス次頼む。
182 = "うんうん、良い雰囲気が出てるぞ。\\nクリス次頼む。"

# クリス
# あー、飽きたからやめるね。
178 = "あー、飽きたからやめるね。"

# カズマ
# おお！　最後まで塩対応、\nファンも大喜びしそうだな。\nウィズ、ゆんゆん続けてやってくれ。
188 = "おお！　最後まで塩対応、\\nファンも大喜びしそうだな。\\nウィズ、ゆんゆん続けてやってくれ。"

# ウィズ
# ええと、私のこと、忘れないでくださいね？\n忘れたら、お仕置きですよ？
184 = "ええと、私のこと、忘れないでくださいね？\\n忘れたら、お仕置きですよ？"

# ゆんゆん
# お、おねぇちゃんがやめるなら、\n私もやめちゃうよー！
186 = "お、おねぇちゃんがやめるなら、\\n私もやめちゃうよー！"

# カズマ
# うむ、大体決まったな。\nみんな、卒業式は大々的に行われるから、\n楽しみにしてろよ。
181 = "うむ、大体決まったな。\\nみんな、卒業式は大々的に行われるから、\\n楽しみにしてろよ。"

# めぐみん
# い、いや……まずはデビューしましょうよ。
179 = "い、いや……まずはデビューしましょうよ。"

