# st03b_03.txt.scn

[info]
0 = ""

[characters]
318 = "ダクネス"
317 = "クリス"
306 = "ゆんゆん"
303 = "めぐみん"
314 = "カズマ"
313 = "ウィズ"
316 = "カズマ（Ｍ）"
312 = "アクア"

[character_subs]
# 314 = "カズマ"

[script]
# lines: 129

# ダクネス
# 庭で何をするんだ？　筋トレか？
335 = "庭で何をするんだ？　筋トレか？"

# クリス
# それはマズイでしょ。\n苦労して作った衣装が汚れちゃうしさ。
279 = "それはマズイでしょ。\\n苦労して作った衣装が汚れちゃうしさ。"

# ゆんゆん
# それに、どうしてこの衣装を着ていないと\nダメなんですか？
278 = "それに、どうしてこの衣装を着ていないと\\nダメなんですか？"

# めぐみん
# そうですよ。\n朝食の時、汚さないようにとわざわざ普段着に\n着替えたのに。
273 = "そうですよ。\\n朝食の時、汚さないようにとわざわざ普段着に\\n着替えたのに。"

# カズマ
# まだ服に着られてる感じがするだろ？
302 = "まだ服に着られてる感じがするだろ？"

# ダクネス
# 確かに。
403 = "確かに。"

# カズマ
# 体に馴染ませるためには、\n着続けることが一番なんだ。
327 = "体に馴染ませるためには、\\n着続けることが一番なんだ。"

# ウィズ
# あのそれで、お庭でいったい何を。
247 = "あのそれで、お庭でいったい何を。"

# カズマ
# 歌の練習だ。
338 = "歌の練習だ。"

# クリス
# ええと、庭に出る理由がわからないんだけど。
255 = "ええと、庭に出る理由がわからないんだけど。"

# カズマ
# お前たちにはまだ照れがある！
260 = "お前たちにはまだ照れがある！"

# ダクネス
# 当然だろう。\nこんな服を着せられているのだから。
336 = "当然だろう。\\nこんな服を着せられているのだから。"

# カズマ
# そういう不安や不満は、観客に伝わるものなんだ。
268 = "そういう不安や不満は、観客に伝わるものなんだ。"

# カズマ
# 最初は初々しいと思われるかもしれないけど、\nいつまでもそんなんじゃ客も嫌気が差しちまう。
337 = "最初は初々しいと思われるかもしれないけど、\\nいつまでもそんなんじゃ客も嫌気が差しちまう。"

# ゆんゆん
# だから、お庭で特訓なんですね？
280 = "だから、お庭で特訓なんですね？"

# カズマ
# さすがにいきなり街中ってのは嫌だろ？
263 = "さすがにいきなり街中ってのは嫌だろ？"

# めぐみん
# 全力で拒否しますよ！
329 = "全力で拒否しますよ！"

# カズマ（Ｍ）
# display as カズマ
# （さて、問題はここからだ）
424 = "（さて、問題はここからだ）"

# カズマ（Ｍ）
# display as カズマ
# （歌の練習っていったい何をすれば良いんだ？）
440 = "（歌の練習っていったい何をすれば良いんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （そんなもんの知識は皆無だし、\n　そもそも歌うにも俺はこの世界の歌を\n　何ひとつしらない……）
428 = "（そんなもんの知識は皆無だし、\\n　そもそも歌うにも俺はこの世界の歌を\\n　何ひとつしらない……）"

# めぐみん
# どうしたんですか、カズマ？\n歌の特訓をしないんですか？
288 = "どうしたんですか、カズマ？\\n歌の特訓をしないんですか？"

# カズマ
# えっ……あ、いや……。
256 = "えっ……あ、いや……。"

# クリス
# まさか、勢いで言ったわけじゃないよね？
301 = "まさか、勢いで言ったわけじゃないよね？"

# カズマ（Ｍ）
# display as カズマ
# （すみません、その通りです……）
426 = "（すみません、その通りです……）"

# ゆんゆん
# まさか、そうなんですか？
300 = "まさか、そうなんですか？"

# アクア
# ちょっと、しっかりしてよ。\nアイドルについて詳しいのは、\nカズマだけなんだからね。
284 = "ちょっと、しっかりしてよ。\\nアイドルについて詳しいのは、\\nカズマだけなんだからね。"

# カズマ（Ｍ）
# display as カズマ
# （さっきまでキラキラしていたみんなの目が、\n　冷たく突き刺さる物に変わっていく！）
423 = "（さっきまでキラキラしていたみんなの目が、\\n　冷たく突き刺さる物に変わっていく！）"

# カズマ（Ｍ）
# display as カズマ
# （このままじゃいかん！　プロデューサーとしての\n　立場が危うくなる前に、なんとかしなければ！）
422 = "（このままじゃいかん！　プロデューサーとしての\\n　立場が危うくなる前に、なんとかしなければ！）"

# カズマ
# よ、よーし！　まずは発声練習をするぞ！
307 = "よ、よーし！　まずは発声練習をするぞ！"

# クリス
# 発声練習？
340 = "発声練習？"

# カズマ
# いきなり歌ったら、喉を潰しちまうからな。
251 = "いきなり歌ったら、喉を潰しちまうからな。"

# カズマ（Ｍ）
# display as カズマ
# （たぶん……）
429 = "（たぶん……）"

# ウィズ
# それで、発声練習とは、\nどのようなことをすればいいんですか？
277 = "それで、発声練習とは、\\nどのようなことをすればいいんですか？"

# カズマ
# じゃあ、ええと、俺がやってることを真似てくれ。
265 = "じゃあ、ええと、俺がやってることを真似てくれ。"

# カズマ
# あーあーあーーーーー。
249 = "あーあーあーーーーー。"

# ゆんゆん
# あーあーあー……こ、こんな感じかなぁ。
248 = "あーあーあー……こ、こんな感じかなぁ。"

# ダクネス
# あーあーあー！！　ふむ、なかなか難しいな。
250 = "あーあーあー！！　ふむ、なかなか難しいな。"

# カズマ（Ｍ）
# display as カズマ
# （音程はおいといて、\n　みんないい喉をしているっぽいな）
442 = "（音程はおいといて、\\n　みんないい喉をしているっぽいな）"

# カズマ
# ん？　ど、どうしためぐみん？
311 = "ん？　ど、どうしためぐみん？"

# めぐみん
# まさか、ずっとあーあー言っているだけですか？
299 = "まさか、ずっとあーあー言っているだけですか？"

# カズマ
# ち、違うぞ！\nじゃあ、次の発声練習だが……。
282 = "ち、違うぞ！\\nじゃあ、次の発声練習だが……。"

# カズマ（Ｍ）
# display as カズマ
# （えっと、確か前に読んだマンガに\n　なんかあったような）
418 = "（えっと、確か前に読んだマンガに\\n　なんかあったような）"

# カズマ
# そうだ！　マリアだ！！\nいいか、まーりーあーー！！\nって感じで声を出してくれ。
272 = "そうだ！　マリアだ！！\\nいいか、まーりーあーー！！\\nって感じで声を出してくれ。"

# クリス
# ええと、マーリーアー！\nこんな感じ？
254 = "ええと、マーリーアー！\\nこんな感じ？"

# めぐみん
# マーマーマーー！！
322 = "マーマーマーー！！"

# カズマ
# ちっがーう！　まーりーあー！　だ！
283 = "ちっがーう！　まーりーあー！　だ！"

# めぐみん
# さっきの例と変わってますよ？
264 = "さっきの例と変わってますよ？"

# カズマ
# ハッ！？　そ、そうだっけ？
320 = "ハッ！？　そ、そうだっけ？"

# ゆんゆん
# あの、１つ訊いてもいいですか？
246 = "あの、１つ訊いてもいいですか？"

# カズマ
# お、おう、なんだ？
258 = "お、おう、なんだ？"

# ゆんゆん
# どうして、まりあ？　なんでしょう。
289 = "どうして、まりあ？　なんでしょう。"

# カズマ（Ｍ）
# display as カズマ
# （ええ、そこが気になるの！？）
416 = "（ええ、そこが気になるの！？）"

# めぐみん
# その反応、もしかして理由はないんですか？
276 = "その反応、もしかして理由はないんですか？"

# カズマ
# あ、あるぞ！
242 = "あ、あるぞ！"

# カズマ（Ｍ）
# display as カズマ
# （そう、確かにある！　ある筈なんだ！\n　だが思い出せない！）
427 = "（そう、確かにある！　ある筈なんだ！\\n　だが思い出せない！）"

# ゆんゆん
# もしかして私、余計なことを聞いちゃいましたか？
304 = "もしかして私、余計なことを聞いちゃいましたか？"

# カズマ（Ｍ）
# display as カズマ
# （い、いかーん、みんなの目が\n　冷ややかなものへと変わっていくー！）
411 = "（い、いかーん、みんなの目が\\n　冷ややかなものへと変わっていくー！）"

# カズマ（Ｍ）
# display as カズマ
# （ええと、なんだったっけか。\n　確か……）
417 = "（ええと、なんだったっけか。\\n　確か……）"

# カズマ
# あ、だ。
243 = "あ、だ。"

# ゆんゆん
# あ、ですか。
244 = "あ、ですか。"

# カズマ
# ぼ、母音の「あ」と\n子音のぉ……何かが良い感じになって――
296 = "ぼ、母音の「あ」と\\n子音のぉ……何かが良い感じになって――"

# ゆんゆん
# あ、あの、もう大丈夫です！
241 = "あ、あの、もう大丈夫です！"

# カズマ
# へ？　そうなの？
295 = "へ？　そうなの？"

# ゆんゆん
# 聞いても多分理解できないと思いますので。
408 = "聞いても多分理解できないと思いますので。"

# クリス
# 確かに専門的なことみたいだしね。
405 = "確かに専門的なことみたいだしね。"

# ダクネス
# なぜだろう、カズマが少し輝いて見える。
291 = "なぜだろう、カズマが少し輝いて見える。"

# めぐみん
# ちょっと見直しましたよ、カズマ。\nただノリと勢いだけでやってたわけじゃ\nないんですね。
285 = "ちょっと見直しましたよ、カズマ。\\nただノリと勢いだけでやってたわけじゃ\\nないんですね。"

# カズマ
# と、当然だろ！\n俺はプロデューサーなんだぞ！
287 = "と、当然だろ！\\n俺はプロデューサーなんだぞ！"

# ウィズ
# プロデューサーって、何でも知ってるんですねぇ。
321 = "プロデューサーって、何でも知ってるんですねぇ。"

# カズマ
# ふっ、お世辞を言ってないで練習だ！
294 = "ふっ、お世辞を言ってないで練習だ！"

# カズマ（Ｍ）
# display as カズマ
# （ふーっ、やっべー、なんとかごまかせたけど、\n　これは早急になんとかしなきゃな）
432 = "（ふーっ、やっべー、なんとかごまかせたけど、\\n　これは早急になんとかしなきゃな）"

# ウィズ
# ま、ま、まーりーあー……。
297 = "ま、ま、まーりーあー……。"

# カズマ（Ｍ）
# display as カズマ
# （ウィズはこういうことが苦手なのかな。\n　周りを気にしてるし、発生も弱々しい）
435 = "（ウィズはこういうことが苦手なのかな。\\n　周りを気にしてるし、発生も弱々しい）"

# クリス
# マーリーアー！
323 = "マーリーアー！"

# カズマ（Ｍ）
# display as カズマ
# （おお、クリス良いじゃないか！\n　まるで女神のような甘い声だ。\n　これはセンターを張れるダークホースだな！）
419 = "（おお、クリス良いじゃないか！\\n　まるで女神のような甘い声だ。\\n　これはセンターを張れるダークホースだな！）"

# アクア
# マーリーアー！！
324 = "マーリーアー！！"

# カズマ
# え？
257 = "え？"

# ウィズ
# わ、アクア様、すごいです！\nつい、聞き惚れてしまいました。
308 = "わ、アクア様、すごいです！\\nつい、聞き惚れてしまいました。"

# アクア
# そ、そんな、褒めすぎよ。
267 = "そ、そんな、褒めすぎよ。"

# ダクネス
# いやいや、謙遜することはないぞ。\nとても美しい声だった。
253 = "いやいや、謙遜することはないぞ。\\nとても美しい声だった。"

# アクア
# そうかしら？
270 = "そうかしら？"

# カズマ（Ｍ）
# display as カズマ
# （今回はなんなのこいつ！）
437 = "（今回はなんなのこいつ！）"

# カズマ（Ｍ）
# display as カズマ
# （裁縫の時といい、今回といい、\n　なんかちっともアクアらしくないんだけど！）
441 = "（裁縫の時といい、今回といい、\\n　なんかちっともアクアらしくないんだけど！）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、今の所、センター候補の筆頭は\n　アクアだよな）
415 = "（うーん、今の所、センター候補の筆頭は\\n　アクアだよな）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、どんなに歌がどんなに上手かろうが\n　アクアなことにかわりはないし――）
425 = "（しかし、どんなに歌がどんなに上手かろうが\\n　アクアなことにかわりはないし――）"

# カズマ（Ｍ）
# display as カズマ
# （こいつにセンターを任せるのは不安すぎる！）
421 = "（こいつにセンターを任せるのは不安すぎる！）"

# カズマ（Ｍ）
# display as カズマ
# （なぁぁ、他の連中はどうなんだ！）
431 = "（なぁぁ、他の連中はどうなんだ！）"

# めぐみん
# ま、まぁりぃあぁ……。
298 = "ま、まぁりぃあぁ……。"

# カズマ
# お前、真面目にやれよ。
259 = "お前、真面目にやれよ。"

# めぐみん
# や、やってますよ！
305 = "や、やってますよ！"

# カズマ
# だったらもっと背中をシャンと伸ばせ。\nそんな丸まってたら出る声も出ないだろ。
281 = "だったらもっと背中をシャンと伸ばせ。\\nそんな丸まってたら出る声も出ないだろ。"

# めぐみん
# そうは言われても、風が……。
275 = "そうは言われても、風が……。"

# カズマ
# そういえば今日はちょっと強いか。
269 = "そういえば今日はちょっと強いか。"

# ゆんゆん
# きゃっ、また！
261 = "きゃっ、また！"

# カズマ
# なんだ、ゆんゆんもか？\nそんなスカートばっかり気にしてちゃ、\n練習にならないぞ。
292 = "なんだ、ゆんゆんもか？\\nそんなスカートばっかり気にしてちゃ、\\n練習にならないぞ。"

# ゆんゆん
# す、すみません。
266 = "す、すみません。"

# ウィズ
# ですがカズマさん。\nこの風の中声を出す練習をするのは\nあまり良くないかと。
286 = "ですがカズマさん。\\nこの風の中声を出す練習をするのは\\nあまり良くないかと。"

# カズマ
# 確かに喉を痛める危険があるか。
404 = "確かに喉を痛める危険があるか。"

# ゆんゆん
# そうですよ！
274 = "そうですよ！"

# めぐみん
# 絶対そうです！
407 = "絶対そうです！"

# ゆんゆん
# 屋敷に戻りましょう！
332 = "屋敷に戻りましょう！"

# めぐみん
# 今戻らなければ大変なことに！
326 = "今戻らなければ大変なことに！"

# カズマ
# わかったよ、じゃあ、屋敷に――
309 = "わかったよ、じゃあ、屋敷に――"

# ウィズ
# きゃ！　か、風でスカートがぁぁっ！？
262 = "きゃ！　か、風でスカートがぁぁっ！？"

# カズマ
# 何っ！？
328 = "何っ！？"

# カズマ（Ｍ）
# display as カズマ
# （くっ、見えなかった！！）
420 = "（くっ、見えなかった！！）"

# ゆんゆん
# わわ、私先に戻ってます！
310 = "わわ、私先に戻ってます！"

# めぐみん
# ああぁっ、ずるい！　私も戻りますっ！
245 = "ああぁっ、ずるい！　私も戻りますっ！"

# アクア
# %fsyogen;へきしっ！！　うーっ、\nなんだが身体が冷えてきちゃったみたい。\n私も戻ろっと。
24 = "%fsyogen;へきしっ！！　うーっ、\\nなんだが身体が冷えてきちゃったみたい。\\n私も戻ろっと。"

# カズマ（Ｍ）
# display as カズマ
# （アクアがくしゃみ？\n　馬鹿は風邪を引かないというけど……）
434 = "（アクアがくしゃみ？\\n　馬鹿は風邪を引かないというけど……）"

# カズマ（Ｍ）
# display as カズマ
# （いや、こいつがくしゃみをするなんて\n　しょっちゅうか）
412 = "（いや、こいつがくしゃみをするなんて\\n　しょっちゅうか）"

# カズマ（Ｍ）
# display as カズマ
# （でも念のため、証言としてゲットしておこう）
430 = "（でも念のため、証言としてゲットしておこう）"

# クリス
# カズマ、あたしも戻っていいよね？
315 = "カズマ、あたしも戻っていいよね？"

# カズマ
# そうだな。発声練習はこの辺にしておくか。
271 = "そうだな。発声練習はこの辺にしておくか。"

# ウィズ
# はぁ、助かりました。
293 = "はぁ、助かりました。"

# カズマ
# ダクネス、ほら中に入ろうぜ。
319 = "ダクネス、ほら中に入ろうぜ。"

# ダクネス
# %fsyogen;いや、私はここに残る。\nそしてぜひ、カズマにも残って欲しい。
23 = "%fsyogen;いや、私はここに残る。\\nそしてぜひ、カズマにも残って欲しい。"

# カズマ
# なぜ……。
290 = "なぜ……。"

# ダクネス
# 風が！
409 = "風が！"

# カズマ
# 風が？
410 = "風が？"

# ダクネス
# 私にここにいろと語りかけているからだ！
406 = "私にここにいろと語りかけているからだ！"

# カズマ（Ｍ）
# display as カズマ
# （うん、よくわからないが……風？）
413 = "（うん、よくわからないが……風？）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスが風にハァハァする理由はなんだ？\n　それに俺に残って欲しい理由は？）
436 = "（ダクネスが風にハァハァする理由はなんだ？\\n　それに俺に残って欲しい理由は？）"

# カズマ（Ｍ）
# display as カズマ
# （怪しいな。\n　証言としてゲットしておこう）
439 = "（怪しいな。\\n　証言としてゲットしておこう）"

# カズマ
# いたけりゃひとりでいろ。\n俺は中に入ってるぞ。
252 = "いたけりゃひとりでいろ。\\n俺は中に入ってるぞ。"

# ダクネス
# %fsyogen;ほ、放置プレイか。\nそういう扱いも嫌いではないぞ。
25 = "%fsyogen;ほ、放置プレイか。\\nそういう扱いも嫌いではないぞ。"

# カズマ（Ｍ）
# display as カズマ
# （何言ってんだよ、まったく……）
438 = "（何言ってんだよ、まったく……）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、でも念のため証言として\n　ゲットしておくか）
414 = "（うーん、でも念のため証言として\\n　ゲットしておくか）"

# カズマ（Ｍ）
# display as カズマ
# （もしかしたら、\n　重要な証拠になるかもしれないしな）
433 = "（もしかしたら、\\n　重要な証拠になるかもしれないしな）"

