# st03a_08.txt.scn

[info]
0 = ""

[characters]
358 = "ダクネス"
353 = "カズマ"
356 = "クリス"
348 = "アクア"
351 = "ウィズ"
340 = "めぐみん"
355 = "カズマ（Ｍ）"
342 = "ゆんゆん"

[character_subs]
# 353 = "カズマ"

[script]
# lines: 120

# ダクネス
# よいっしょ。\nふう、これは買いすぎなんじゃないのか？
343 = "よいっしょ。\\nふう、これは買いすぎなんじゃないのか？"

# カズマ
# 何言ってるんだよ、６人分の衣装を作るんだぞ。
361 = "何言ってるんだよ、６人分の衣装を作るんだぞ。"

# クリス
# 確かに失敗することを考えると、\nこの量でも不安かもしれないね。
430 = "確かに失敗することを考えると、\\nこの量でも不安かもしれないね。"

# カズマ
# そういうことだ。
298 = "そういうことだ。"

# アクア
# むぅぅ～。
339 = "むぅぅ～。"

# カズマ
# お前はまだ怒ってるのか。
290 = "お前はまだ怒ってるのか。"

# アクア
# これが怒らないでいられると思ってるの！\n私たちがやるのは清楚なアイドルなのよ！
293 = "これが怒らないでいられると思ってるの！\\n私たちがやるのは清楚なアイドルなのよ！"

# アクア
# それなのにどうして、\nアンデッドをメンバーに入れるのよ！
308 = "それなのにどうして、\\nアンデッドをメンバーに入れるのよ！"

# ウィズ
# うぅ、すみません！　すみません！\nこんな私が、よくわかりませんけど、\nあいどるをやろうとしてすみません！
272 = "うぅ、すみません！　すみません！\\nこんな私が、よくわかりませんけど、\\nあいどるをやろうとしてすみません！"

# カズマ
# ウィズが謝る必要は無いよ。\n無理に誘ったのは俺なんだしさ。
352 = "ウィズが謝る必要は無いよ。\\n無理に誘ったのは俺なんだしさ。"

# アクア
# ねえ、カズマ。\n今からでも遅くないから考え直しなさいよ。
325 = "ねえ、カズマ。\\n今からでも遅くないから考え直しなさいよ。"

# アクア
# アンデッドなんて入れたら、\n私たちの価値が下がるのよ。
350 = "アンデッドなんて入れたら、\\n私たちの価値が下がるのよ。"

# アクア
# あんたでもそれくらいはわかるでしょ。
264 = "あんたでもそれくらいはわかるでしょ。"

# カズマ
# いや、わからん。
267 = "いや、わからん。"

# アクア
# なんでよ！
324 = "なんでよ！"

# カズマ
# 酒場でも説明したけど、まずはみんなにお前らの\n存在を認知させなければいけないんだよ。
434 = "酒場でも説明したけど、まずはみんなにお前らの\\n存在を認知させなければいけないんだよ。"

# カズマ
# そのためには、ウィズの知名度が必須なんだ。
304 = "そのためには、ウィズの知名度が必須なんだ。"

# アクア
# 知名度が必要なら私がいるじゃない。
428 = "知名度が必要なら私がいるじゃない。"

# カズマ
# はぁ……あまりこれは言いたくなかったんだけどさ。
327 = "はぁ……あまりこれは言いたくなかったんだけどさ。"

# アクア
# 何よ。
360 = "何よ。"

# カズマ
# お前の名前ってさ、悪い意味で有名じゃん？
289 = "お前の名前ってさ、悪い意味で有名じゃん？"

# アクア
# うっ！
277 = "うっ！"

# カズマ
# ええと、アクシズ教団は、なんだっけ？
282 = "ええと、アクシズ教団は、なんだっけ？"

# カズマ
# 頭がおかしい人が多く？\n関わり合いにならない方がいい？
435 = "頭がおかしい人が多く？\\n関わり合いにならない方がいい？"

# カズマ
# 確かこんな感じだったよな。
429 = "確かこんな感じだったよな。"

# アクア
# うっ、うぅ、うぅぅ～～～～！！
276 = "うっ、うぅ、うぅぅ～～～～！！"

# カズマ
# それに引き替えウィズは、\nみんなに慕われてるからな。
309 = "それに引き替えウィズは、\\nみんなに慕われてるからな。"

# カズマ
# 固定ファンも絶対にいるはずだし。\n本当に頼もしい限りだ。
367 = "固定ファンも絶対にいるはずだし。\\n本当に頼もしい限りだ。"

# ウィズ
# あ、あの、カズマさん。\nアクア様の様子が……。
261 = "あ、あの、カズマさん。\\nアクア様の様子が……。"

# アクア
# うぅぅ、うぅぅぅ……。
274 = "うぅぅ、うぅぅぅ……。"

# カズマ
# な、なんだよ、ただ事実を言っただけだろ。
321 = "な、なんだよ、ただ事実を言っただけだろ。"

# アクア
# うぅぅ、くぅぅぅ……うぅぅぅ！！
275 = "うぅぅ、くぅぅぅ……うぅぅぅ！！"

# ダクネス
# どうした。何か問題か？
318 = "どうした。何か問題か？"

# カズマ
# いや、アクアがちょっと。
268 = "いや、アクアがちょっと。"

# めぐみん
# またアクアを泣かせたんですか。\n言葉の暴力も大概にしてください。
337 = "またアクアを泣かせたんですか。\\n言葉の暴力も大概にしてください。"

# カズマ
# いやいや、俺にそんなつもりはなかったんだって！
269 = "いやいや、俺にそんなつもりはなかったんだって！"

# ダクネス
# しかしアクアが泣いているという事実があるだろう。
294 = "しかしアクアが泣いているという事実があるだろう。"

# カズマ
# うぅ、わかったよ。\nあとで謝っておくから。
273 = "うぅ、わかったよ。\\nあとで謝っておくから。"

# ダクネス
# うん、それがいい。
279 = "うん、それがいい。"

# ウィズ
# あ、あの、アクア様？\nもしお気に召さないなら、\n私は参加を取り下げますので。
260 = "あ、あの、アクア様？\\nもしお気に召さないなら、\\n私は参加を取り下げますので。"

# アクア
# 別にいいわよ……。
363 = "別にいいわよ……。"

# ウィズ
# そうなんですか？
301 = "そうなんですか？"

# アクア
# あんたより、絶対に売れてやるわ。\nそして見返してやるんだから！
265 = "あんたより、絶対に売れてやるわ。\\nそして見返してやるんだから！"

# カズマ
# おお、なんかやる気スイッチが入ったみたいだ。
287 = "おお、なんかやる気スイッチが入ったみたいだ。"

# めぐみん
# やけくそのようにも思えますが。
341 = "やけくそのようにも思えますが。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、どんな理由であれ、\n　やる気がさらに上がるのはいいことだ）
442 = "（まあ、どんな理由であれ、\\n　やる気がさらに上がるのはいいことだ）"

# カズマ
# よし、時間も無いし、早速衣装作りに取りかかるぞ。
344 = "よし、時間も無いし、早速衣装作りに取りかかるぞ。"

# ダクネス
# その前に聞きたいのだが、\n衣装はいったい誰が作るんだ？
305 = "その前に聞きたいのだが、\\n衣装はいったい誰が作るんだ？"

# カズマ
# 俺だけど？
362 = "俺だけど？"

# ゆんゆん
# えーっ！！　カズマさんが作るんですか？
286 = "えーっ！！　カズマさんが作るんですか？"

# カズマ
# 裁縫スキル持ってるし。\n俺がプロデュースするからには、\n衣装にこだわりたいしな。
432 = "裁縫スキル持ってるし。\\n俺がプロデュースするからには、\\n衣装にこだわりたいしな。"

# ウィズ
# カズマさんって、本当に器用なんですね。
354 = "カズマさんって、本当に器用なんですね。"

# めぐみん
# 器用貧乏とも言いますがね。
366 = "器用貧乏とも言いますがね。"

# カズマ
# うるさいよ、お前は！
278 = "うるさいよ、お前は！"

# ゆんゆん
# それで、何から始めたらいいんでしょう。
306 = "それで、何から始めたらいいんでしょう。"

# カズマ
# まずは、採寸からだな。
336 = "まずは、採寸からだな。"

# ゆんゆん
# え……。
280 = "え……。"

# カズマ
# １人１人体格が違うし、それに合わせた服を\n作らなきゃいけないし――
445 = "１人１人体格が違うし、それに合わせた服を\\n作らなきゃいけないし――"

# カズマ
# スリーサイズはプロフィールとして必須事項だから、\nこれを機にきっちり計っておこうと思ってる。
357 = "スリーサイズはプロフィールとして必須事項だから、\\nこれを機にきっちり計っておこうと思ってる。"

# カズマ
# それで、誰から計る？　ゆんゆんか？
307 = "それで、誰から計る？　ゆんゆんか？"

# ゆんゆん
# ひっ！？
330 = "ひっ！？"

# めぐみん
# わ、私は最後でいいです。
345 = "わ、私は最後でいいです。"

# クリス
# あ、あたしも後でいいかな。
259 = "あ、あたしも後でいいかな。"

# アクア
# 採寸するとかなんとか言いながら、\n私たちの身体をベタベタ触って\nセクハラしたいだけなんじゃないの？
370 = "採寸するとかなんとか言いながら、\\n私たちの身体をベタベタ触って\\nセクハラしたいだけなんじゃないの？"

# カズマ
# ちげーよ！\nこれは衣装作りに必要な事なんだ！\nやましい気持ちなんて、全くないからな！
314 = "ちげーよ！\\nこれは衣装作りに必要な事なんだ！\\nやましい気持ちなんて、全くないからな！"

# アクア
# ふん、どうだか！\n変態クソニートの言葉なんて信用できないわ！
331 = "ふん、どうだか！\\n変態クソニートの言葉なんて信用できないわ！"

# カズマ
# お前、まだ怒ってるのか……。
288 = "お前、まだ怒ってるのか……。"

# アクア
# ふん！
332 = "ふん！"

# ダクネス
# か、カズマ、採寸が必要だったら、\nまずは私から始めてくれ！
292 = "か、カズマ、採寸が必要だったら、\\nまずは私から始めてくれ！"

# ダクネス
# そして溜め込んだ鬱憤を\n私の体に触りながら晴らすといい！
303 = "そして溜め込んだ鬱憤を\\n私の体に触りながら晴らすといい！"

# カズマ
# だから、誤解されそうな言い方をするな！\nみんながどん引きしてるだろ！！
313 = "だから、誤解されそうな言い方をするな！\\nみんながどん引きしてるだろ！！"

# ウィズ
# み、みなさん、そんなに警戒しないで、\nカズマさんを信用して採寸を。
338 = "み、みなさん、そんなに警戒しないで、\\nカズマさんを信用して採寸を。"

# アクア
# あんた、その男に洗脳でもされたの？\n甘い言葉に騙されて、泣き寝入りした女の子が\nごまんといるのよ。
263 = "あんた、その男に洗脳でもされたの？\\n甘い言葉に騙されて、泣き寝入りした女の子が\\nごまんといるのよ。"

# ウィズ
# ひいぃ！？　そ、そうなんですか？
329 = "ひいぃ！？　そ、そうなんですか？"

# カズマ
# んなわけあるかーー！
347 = "んなわけあるかーー！"

# カズマ
# たく、これじゃあ作業が進まねーじゃんか。\nほらっ、めぐみん、パパッと終わらせるから\n協力してくれ。
312 = "たく、これじゃあ作業が進まねーじゃんか。\\nほらっ、めぐみん、パパッと終わらせるから\\n協力してくれ。"

# めぐみん
# お断りします！
291 = "お断りします！"

# カズマ
# なっ！？
323 = "なっ！？"

# めぐみん
# 紅魔族は、そう簡単に身体を許したり\nしないのです！
431 = "紅魔族は、そう簡単に身体を許したり\\nしないのです！"

# カズマ
# なっ、何言ってんだよ！\nただ採寸するだけだって言ってるだろ！
322 = "なっ、何言ってんだよ！\\nただ採寸するだけだって言ってるだろ！"

# めぐみん
# いやです！　どうしてもと言うなら、\n爆裂魔法を食らってからにしてください。
270 = "いやです！　どうしてもと言うなら、\\n爆裂魔法を食らってからにしてください。"

# カズマ
# 死ぬわ！
371 = "死ぬわ！"

# めぐみん
# と、とにかく……今は無理なんですよ！
315 = "と、とにかく……今は無理なんですよ！"

# カズマ
# はぁ、なんでだよ。
328 = "はぁ、なんでだよ。"

# めぐみん
# そ、それは……。\n紅魔族は異性に触れられると死ぬからです！
297 = "そ、それは……。\\n紅魔族は異性に触れられると死ぬからです！"

# カズマ
# へー。
334 = "へー。"

# めぐみん
# %fsyogen;とにかく今は都合が悪いんです！\nやるなら、そうですね、\nゆんゆんからにしてください！
24 = "%fsyogen;とにかく今は都合が悪いんです！\\nやるなら、そうですね、\\nゆんゆんからにしてください！"

# カズマ（Ｍ）
# display as カズマ
# （都合が悪い？\n　機転の利くめぐみんらしからぬ\n　苦しい言い訳だな……）
444 = "（都合が悪い？\\n　機転の利くめぐみんらしからぬ\\n　苦しい言い訳だな……）"

# カズマ（Ｍ）
# display as カズマ
# （これは証言として押さえておく価値が\n　あるかもしれない）
440 = "（これは証言として押さえておく価値が\\n　あるかもしれない）"

# カズマ
# しょうがねぇなぁ……。\nじゃあゆんゆん、先に採寸させてもらっても\nいいか？
296 = "しょうがねぇなぁ……。\\nじゃあゆんゆん、先に採寸させてもらっても\\nいいか？"

# ゆんゆん
# えっ、わ、わわ、私が！？\n嫌です！！
284 = "えっ、わ、わわ、私が！？\\n嫌です！！"

# カズマ
# えーっ、ゆんゆんまでなんでだよ。
285 = "えーっ、ゆんゆんまでなんでだよ。"

# ゆんゆん
# %fsyogen;だ、だって、採寸をすると言うことは\nカズマさんが近づくと言うことですよね？
23 = "%fsyogen;だ、だって、採寸をすると言うことは\\nカズマさんが近づくと言うことですよね？"

# カズマ
# まあ、そうしないと測れないからな。
335 = "まあ、そうしないと測れないからな。"

# ゆんゆん
# ということは、あのあの、見えてしまう可能性が\n高くなるといいますか……。
316 = "ということは、あのあの、見えてしまう可能性が\\n高くなるといいますか……。"

# カズマ
# いや、ちょっと待て。\nいったい何を警戒してるのか、さっぱりわからん。
266 = "いや、ちょっと待て。\\nいったい何を警戒してるのか、さっぱりわからん。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、男の俺に体を触れられたくないのは\n　わかる）
443 = "（まあ、男の俺に体を触れられたくないのは\\n　わかる）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、見えるだと？\n　採寸をするだけで何が見えるって言うんだ？）
441 = "（しかし、見えるだと？\\n　採寸をするだけで何が見えるって言うんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （これは証言としてゲットしておく価値が\n　あるかもな！）
439 = "（これは証言としてゲットしておく価値が\\n　あるかもな！）"

# アクア
# ぷぷ、カズマってば、まったく信用が無いのね。
333 = "ぷぷ、カズマってば、まったく信用が無いのね。"

# カズマ（Ｍ）
# display as カズマ
# （こいつ、今の状況を楽しんでやがるな）
438 = "（こいつ、今の状況を楽しんでやがるな）"

# アクア
# どうしたんですか、カズマさん。\n採寸しないと衣装は作れませんよ？
319 = "どうしたんですか、カズマさん。\\n採寸しないと衣装は作れませんよ？"

# カズマ（Ｍ）
# display as カズマ
# （くっそ、腹立つわー！\n　こうなったら――）
437 = "（くっそ、腹立つわー！\\n　こうなったら――）"

# カズマ
# アクア、お前から採寸するぞ。
349 = "アクア、お前から採寸するぞ。"

# アクア
# えっ……私から？
283 = "えっ……私から？"

# カズマ
# ああ、アクアがバシッと手本を見せてくれ。\nそしたら、みんなも従ってくれると思うし。
262 = "ああ、アクアがバシッと手本を見せてくれ。\\nそしたら、みんなも従ってくれると思うし。"

# アクア
# えぇぇーーっ！　嫌よ！\nウィズ！！　あんたからやってもらいなさいよ！
281 = "えぇぇーーっ！　嫌よ！\\nウィズ！！　あんたからやってもらいなさいよ！"

# ウィズ
# う、うぅぅっ……アクア様のご命令でしたら、\nご命令でしたら、ご、ごご、ご命令でしたらっ。
271 = "う、うぅぅっ……アクア様のご命令でしたら、\\nご命令でしたら、ご、ごご、ご命令でしたらっ。"

# カズマ
# そこまで嫌なのかー！！
302 = "そこまで嫌なのかー！！"

# クリス
# しょうがないよ。\nやっぱり男の子に体を触られるのは\n抵抗があるもん。
295 = "しょうがないよ。\\nやっぱり男の子に体を触られるのは\\n抵抗があるもん。"

# カズマ
# それはそうだけど、これじゃ衣装を作れないだろ。
310 = "それはそうだけど、これじゃ衣装を作れないだろ。"

# クリス
# ねえ、キミが測る意味って何かあるの？
326 = "ねえ、キミが測る意味って何かあるの？"

# カズマ（Ｍ）
# display as カズマ
# （あ……）
436 = "（あ……）"

# めぐみん
# そうですよ！\n別にカズマじゃなくてもいいじゃないですか！
300 = "そうですよ！\\n別にカズマじゃなくてもいいじゃないですか！"

# ゆんゆん
# そういえば、そうだよね？
299 = "そういえば、そうだよね？"

# アクア
# どうしてそんなことに気がつかなかったのかしら。
320 = "どうしてそんなことに気がつかなかったのかしら。"

# クリス
# というわけで結論が出たね。\n採寸はあたしたちでやるから、\nキミは呼ばれるまで廊下で待機。
317 = "というわけで結論が出たね。\\n採寸はあたしたちでやるから、\\nキミは呼ばれるまで廊下で待機。"

# カズマ
# わかったよ。\nじゃあよろしく頼むな。
346 = "わかったよ。\\nじゃあよろしく頼むな。"

# クリス
# 覗いたら、わかってるよね？
433 = "覗いたら、わかってるよね？"

# カズマ
# そんなことしねーから！
311 = "そんなことしねーから！"

