# st03a_01.txt.scn

[info]
0 = ""

[characters]
142 = "カズマ（Ｍ）"
141 = "カズマ"

[character_subs]
# 141 = "カズマ"

[script]
# lines: 14

# カズマ（Ｍ）
# display as カズマ
# （ええと……）
147 = "（ええと……）"

# カズマ（Ｍ）
# display as カズマ
# （くそ、順調に盗むパンツが増えてやがる。\n　今回は３枚かよ）
149 = "（くそ、順調に盗むパンツが増えてやがる。\\n　今回は３枚かよ）"

# カズマ（Ｍ）
# display as カズマ
# （ふっ、それにしても、\n　女の子のパンツはいつ見ても可愛いな）
154 = "（ふっ、それにしても、\\n　女の子のパンツはいつ見ても可愛いな）"

# カズマ（Ｍ）
# display as カズマ
# （こんな小さい布きれに、心を揺り動かされるのは\n　どうしてなんだろう）
153 = "（こんな小さい布きれに、心を揺り動かされるのは\\n　どうしてなんだろう）"

# カズマ（Ｍ）
# display as カズマ
# （色や穿いてる女の子によって受ける感情が\n　全然違うし、本当に不思議だよなぁ）
157 = "（色や穿いてる女の子によって受ける感情が\\n　全然違うし、本当に不思議だよなぁ）"

# カズマ
# って、しみじみとパンツを眺めてる場合じゃねー！
140 = "って、しみじみとパンツを眺めてる場合じゃねー！"

# カズマ（Ｍ）
# display as カズマ
# （先月は２枚、そして今月は３枚だ）
155 = "（先月は２枚、そして今月は３枚だ）"

# カズマ（Ｍ）
# display as カズマ
# （これってバニルが言った通り、\n　俺の魔力がさらに使われたってことなんだよな）
152 = "（これってバニルが言った通り、\\n　俺の魔力がさらに使われたってことなんだよな）"

# カズマ（Ｍ）
# display as カズマ
# （このまま満月を迎える度に\n　力が増幅し続けたら、俺は……）
151 = "（このまま満月を迎える度に\\n　力が増幅し続けたら、俺は……）"

# カズマ（Ｍ）
# display as カズマ
# （くそっ！　パンツを盗み続ける人生なんて\n　まっぴらごめんだし、そんなくだらないことで\n　死にたくなんてねー！）
150 = "（くそっ！　パンツを盗み続ける人生なんて\\n　まっぴらごめんだし、そんなくだらないことで\\n　死にたくなんてねー！）"

# カズマ（Ｍ）
# display as カズマ
# （早くこの状況をどうにかしないと！）
156 = "（早くこの状況をどうにかしないと！）"

# カズマ
# そのためには、とにかく金を稼ぐ手段を\n見つけることが先決だよな。
139 = "そのためには、とにかく金を稼ぐ手段を\\n見つけることが先決だよな。"

# カズマ（Ｍ）
# display as カズマ
# （おっとその前に）
148 = "（おっとその前に）"

# カズマ
# ３枚のパンツは丁寧に畳んでっと。
158 = "３枚のパンツは丁寧に畳んでっと。"

