# st03c_05.txt.scn

[info]
0 = ""

[characters]
327 = "カズマ"
322 = "アクア"
331 = "ダクネス"
317 = "めぐみん"
329 = "クリス"
320 = "ゆんゆん"
326 = "ウィズ"
333 = "ルナ"
328 = "カズマ（Ｍ）"

[character_subs]
# 327 = "カズマ"

[script]
# lines: 102

# カズマ
# くぅら、アクア！\nどういうことか、説明しろー！！
270 = "くぅら、アクア！\\nどういうことか、説明しろー！！"

# アクア
# え？　え？　何よ急に！
264 = "え？　え？　何よ急に！"

# ダクネス
# おいおい、いきなりがなり立ててどうしたんだ。
265 = "おいおい、いきなりがなり立ててどうしたんだ。"

# めぐみん
# 何かトラブルですか？
336 = "何かトラブルですか？"

# カズマ
# トラブルなんて軽い問題じゃないわ！
332 = "トラブルなんて軽い問題じゃないわ！"

# クリス
# とりあえず、説明をしてよ。
305 = "とりあえず、説明をしてよ。"

# カズマ
# そうだな。\nさっき、ギルドから聞かされたんだが――
285 = "そうだな。\\nさっき、ギルドから聞かされたんだが――"

# カズマ
# 俺たちのアイドルグループ『シャイニーブルー』が、\n強引にアクシズ教団への勧誘を行って、\n困っているという苦情が多数寄せられているそうだ。
340 = "俺たちのアイドルグループ『シャイニーブルー』が、\\n強引にアクシズ教団への勧誘を行って、\\n困っているという苦情が多数寄せられているそうだ。"

# アクア
# なっ！？
307 = "なっ！？"

# カズマ
# シャイニーブルーのメンバーは冒険者だから、\nギルドとしても、この件は見逃せない状況だと\n言われた。
330 = "シャイニーブルーのメンバーは冒険者だから、\\nギルドとしても、この件は見逃せない状況だと\\n言われた。"

# カズマ
# 誰だ？　面倒事を起こしてくれたヤツは？\nこの中で、そんな事をするヤツは\n１人しかいないと思うんだが？
406 = "誰だ？　面倒事を起こしてくれたヤツは？\\nこの中で、そんな事をするヤツは\\n１人しかいないと思うんだが？"

# アクア
# ～～♪　～～♪
411 = "～～♪　～～♪"

# ダクネス
# アクア、いったい何をやったんだ？
323 = "アクア、いったい何をやったんだ？"

# めぐみん
# 正直に言ってください。
351 = "正直に言ってください。"

# ゆんゆん
# ご、強引な勧誘っていったい。
277 = "ご、強引な勧誘っていったい。"

# ウィズ
# あ、アクア様……本当にそんな事したんですか？
244 = "あ、アクア様……本当にそんな事したんですか？"

# クリス
# ちゃんと認めたら、\n今からでもまだやり直せるかもしれないよ？
299 = "ちゃんと認めたら、\\n今からでもまだやり直せるかもしれないよ？"

# アクア
# むっ、うぅぅぅぅっ……。
316 = "むっ、うぅぅぅぅっ……。"

# アクア
# そ、そうだわ！\nこれは、私たちの成功を妬む性格の悪いやつの\n仕業なのよ！！
283 = "そ、そうだわ！\\nこれは、私たちの成功を妬む性格の悪いやつの\\n仕業なのよ！！"

# カズマ
# しらばっくれるか、そうか。\nお姉さん、説明を。
281 = "しらばっくれるか、そうか。\\nお姉さん、説明を。"

# ルナ
# は、はい。
309 = "は、はい。"

# ルナ
# あのですね。\n握手会の時に、このようなチラシをアクアさんから\n渡されたと証言する人もいまして。
250 = "あのですね。\\n握手会の時に、このようなチラシをアクアさんから\\n渡されたと証言する人もいまして。"

# アクア
# なぁっ！？
306 = "なぁっ！？"

# めぐみん
# アクシズ教団を宣伝するチラシですね。
325 = "アクシズ教団を宣伝するチラシですね。"

# ダクネス
# 見事なまでにアクアの筆跡だ。
404 = "見事なまでにアクアの筆跡だ。"

# クリス
# ご丁寧に、アクアさんのサインも入ってるよ。
278 = "ご丁寧に、アクアさんのサインも入ってるよ。"

# アクア
# うぁぁぁぁぁぁぁっ！！！\nあむっ、むぐっ、もぐっ、んぐぅぅぅ！！
255 = "うぁぁぁぁぁぁぁっ！！！\\nあむっ、むぐっ、もぐっ、んぐぅぅぅ！！"

# カズマ
# おいバカ！　そんなもん食うな！！
267 = "おいバカ！　そんなもん食うな！！"

# アクア
# おふ、これで、証拠が……。
269 = "おふ、これで、証拠が……。"

# ルナ
# あの、まだ何枚もあるんですが……。
248 = "あの、まだ何枚もあるんですが……。"

# アクア
# う、うぅ、うぅぅ……。
254 = "う、うぅ、うぅぅ……。"

# カズマ
# そんな物食べたらお腹壊すぞ。\nとりあえず、出そうな。
293 = "そんな物食べたらお腹壊すぞ。\\nとりあえず、出そうな。"

# アクア
# うぅ、はい……。
256 = "うぅ、はい……。"

# カズマ
# さて、全部吐いてもらおうか。
280 = "さて、全部吐いてもらおうか。"

# アクア
# くっ、うぅぅぅっ……。\nわ……わだじがやりました……。
271 = "くっ、うぅぅぅっ……。\\nわ……わだじがやりました……。"

# カズマ
# それで？
289 = "それで？"

# アクア
# さ、サインにアクシズ教の宣伝文句を入れたり、\n握手をした人に、さっきのチラシを渡したり\nしてました。
279 = "さ、サインにアクシズ教の宣伝文句を入れたり、\\n握手をした人に、さっきのチラシを渡したり\\nしてました。"

# カズマ
# 他にはないのか？
335 = "他にはないのか？"

# アクア
# え、えっと、いつかはアクシズ教の\nオンリーイベントが出来たらいいなって。
260 = "え、えっと、いつかはアクシズ教の\\nオンリーイベントが出来たらいいなって。"

# カズマ
# そうファンに言ったのか？
286 = "そうファンに言ったのか？"

# アクア
# い、言ったような……言わなかったような？
251 = "い、言ったような……言わなかったような？"

# カズマ
# 言ったんだな。
405 = "言ったんだな。"

# アクア
# は、はい、そのようなことを\n言ったかもしれません。
308 = "は、はい、そのようなことを\\n言ったかもしれません。"

# カズマ
# だから『シャイニーブルー』は、アクシズ教団が\n洗脳の為に立ち上げたアイドルという噂が\n広まったわけだな。
295 = "だから『シャイニーブルー』は、アクシズ教団が\\n洗脳の為に立ち上げたアイドルという噂が\\n広まったわけだな。"

# めぐみん
# えぇぇっ！？
261 = "えぇぇっ！？"

# カズマ
# この駄女神がぁぁぁ！！！\nどうしてそんなことを！！
275 = "この駄女神がぁぁぁ！！！\\nどうしてそんなことを！！"

# アクア
# だって、上手くやれば私だけ大もうけできると\n思ったんだもの！
298 = "だって、上手くやれば私だけ大もうけできると\\n思ったんだもの！"

# カズマ
# 最低だな、お前。
350 = "最低だな、お前。"

# アクア
# えっぐえっぐ……それにあんなにみんなから\nキャーキャー言われるなんて事、最近無かったし。
263 = "えっぐえっぐ……それにあんなにみんなから\\nキャーキャー言われるなんて事、最近無かったし。"

# アクア
# 私女神なのに、普段は誰も全然これっぽっちも\n敬ってくれないし……\nだから……だから……うわぁぁぁぁん！！
403 = "私女神なのに、普段は誰も全然これっぽっちも\\n敬ってくれないし……\\nだから……だから……うわぁぁぁぁん！！"

# めぐみん
# 女神って、キャラ付けじゃなかったんですか？
346 = "女神って、キャラ付けじゃなかったんですか？"

# ダクネス
# 可哀想に、寂しさが生んだ罪だったという訳か。
343 = "可哀想に、寂しさが生んだ罪だったという訳か。"

# アクア
# だから！　本物の女神なんだってばぁ！！
296 = "だから！　本物の女神なんだってばぁ！！"

# めぐみん
# という夢を今も見続けているんですね。
303 = "という夢を今も見続けているんですね。"

# アクア
# うわぁぁぁぁぁん！！
258 = "うわぁぁぁぁぁん！！"

# カズマ
# 何度も言ったよな？\nアクシズ教への勧誘は禁止だって！
338 = "何度も言ったよな？\\nアクシズ教への勧誘は禁止だって！"

# アクア
# だって、あんなに人が集まったんだし、\n勧誘しなきゃ勿体ないじゃない！！
297 = "だって、あんなに人が集まったんだし、\\n勧誘しなきゃ勿体ないじゃない！！"

# アクア
# でも、大々的にやったら、みんなに迷惑が\nかかるのもわかってるから、\nこっそりとやったのよ。
302 = "でも、大々的にやったら、みんなに迷惑が\\nかかるのもわかってるから、\\nこっそりとやったのよ。"

# カズマ
# おいこら！　俺との約束は無視か！！\nこっそりでもするんじゃねぇよ！！
266 = "おいこら！　俺との約束は無視か！！\\nこっそりでもするんじゃねぇよ！！"

# ウィズ
# あの、もしかしてセンターを狙っていたのも。
249 = "あの、もしかしてセンターを狙っていたのも。"

# アクア
# うん、一番目立つし、ファンも増えるって\n思ったから。
259 = "うん、一番目立つし、ファンも増えるって\\n思ったから。"

# クリス
# アクアさん、やるならさ、\nカズマみたいにずる賢くやらないと。
324 = "アクアさん、やるならさ、\\nカズマみたいにずる賢くやらないと。"

# カズマ
# それ、褒めてないよな。
288 = "それ、褒めてないよな。"

# アクア
# そっか、最初からカズマに\n頼めば良かったのね！
287 = "そっか、最初からカズマに\\n頼めば良かったのね！"

# カズマ
# いやいや、頼まれてもしねーから！
253 = "いやいや、頼まれてもしねーから！"

# カズマ
# みんなもなんとか言ってやれ！！
314 = "みんなもなんとか言ってやれ！！"

# ダクネス
# まったく、しょうがないヤツだな、お前は。
313 = "まったく、しょうがないヤツだな、お前は。"

# アクア
# あぅ、うぁぁぁ、ごめんなさい、ごめんなさい。
247 = "あぅ、うぁぁぁ、ごめんなさい、ごめんなさい。"

# めぐみん
# もう泣かないでください。\n誰も怒ったりしてませんから。
319 = "もう泣かないでください。\\n誰も怒ったりしてませんから。"

# カズマ
# 俺が激怒してますけど！
339 = "俺が激怒してますけど！"

# アクア
# うわぁぁぁぁ、カズマが怒ってるぅぅぅ！！
257 = "うわぁぁぁぁ、カズマが怒ってるぅぅぅ！！"

# めぐみん
# だいたいずるいですよアクアだけなんて。
294 = "だいたいずるいですよアクアだけなんて。"

# カズマ
# 何がだよ。
337 = "何がだよ。"

# めぐみん
# 好き放題やっていいなら、\n私だってステージの上から爆裂魔法を\n撃ちたかったのに！
347 = "好き放題やっていいなら、\\n私だってステージの上から爆裂魔法を\\n撃ちたかったのに！"

# カズマ
# そんなことやってなんの意味が\nあるっていうんだ！
291 = "そんなことやってなんの意味が\\nあるっていうんだ！"

# めぐみん
# 爆裂道の良さを示すんです！
353 = "爆裂道の良さを示すんです！"

# カズマ
# こいつもダメだ……。
273 = "こいつもダメだ……。"

# カズマ
# とにかく、このままじゃ悪評は広がる一方だ。\nそうなったら金稼ぎどころじゃなくなってくるぞ。
304 = "とにかく、このままじゃ悪評は広がる一方だ。\\nそうなったら金稼ぎどころじゃなくなってくるぞ。"

# ルナ
# それに、あまりにも評判が悪くなってしまったら、\nみなさんがこの街に住めなくなってしまうかも\nしれません。
290 = "それに、あまりにも評判が悪くなってしまったら、\\nみなさんがこの街に住めなくなってしまうかも\\nしれません。"

# ゆんゆん
# えぇーっ！？　ど、どうしようめぐみん？
262 = "えぇーっ！？　ど、どうしようめぐみん？"

# ウィズ
# そんな事になったら、\n私お店があるから困ります。
292 = "そんな事になったら、\\n私お店があるから困ります。"

# カズマ（Ｍ）
# display as カズマ
# （誰かが被害に遭う可能性があるなら、\n　これ以上、アイドル活動はやらない方が\n　いいのか？）
410 = "（誰かが被害に遭う可能性があるなら、\\n　これ以上、アイドル活動はやらない方が\\n　いいのか？）"

# カズマ（Ｍ）
# display as カズマ
# （これからの展開と金儲けの算段も立てて\n　いたというのに……）
407 = "（これからの展開と金儲けの算段も立てて\\n　いたというのに……）"

# めぐみん
# ここにいられなくるのは、\nどうにか避けたいです！
274 = "ここにいられなくるのは、\\nどうにか避けたいです！"

# カズマ
# ああ……そうだな、ここは決断するしかないか。\n本当に残念だが――
245 = "ああ……そうだな、ここは決断するしかないか。\\n本当に残念だが――"

# アクア
# ちょっ、ちょっと待って、\nまさかやめるつもりなの！
300 = "ちょっ、ちょっと待って、\\nまさかやめるつもりなの！"

# アクア
# 私……これからアイドルでバンバン稼げると思って、\n借金して色々買っちゃったんですけど！！
402 = "私……これからアイドルでバンバン稼げると思って、\\n借金して色々買っちゃったんですけど！！"

# カズマ
# はぁ！？
310 = "はぁ！？"

# アクア
# アイドルやめちゃうと、お金を返すあてが\n無くなっちゃうんですけどー！！
321 = "アイドルやめちゃうと、お金を返すあてが\\n無くなっちゃうんですけどー！！"

# カズマ
# こ、こいつは……。
272 = "こ、こいつは……。"

# カズマ（Ｍ）
# display as カズマ
# （どうして毎回後先考えずに、行動するんだよ！）
408 = "（どうして毎回後先考えずに、行動するんだよ！）"

# アクア
# おっ、お願いよ、カズマさん！\n借金が返済するまでもうちょっとアイドルで\nいさせてーーー！
268 = "おっ、お願いよ、カズマさん！\\n借金が返済するまでもうちょっとアイドルで\\nいさせてーーー！"

# ルナ
# ですが、これ以上は……。
301 = "ですが、これ以上は……。"

# ダクネス
# ああ、そうだな。
246 = "ああ、そうだな。"

# クリス
# まっ、仕方が無いね。
312 = "まっ、仕方が無いね。"

# アクア
# ま、まさか……みんな、まさか！？
311 = "ま、まさか……みんな、まさか！？"

# ウィズ
# すみません……アクア様。
282 = "すみません……アクア様。"

# ゆんゆん
# めぐみん……やっぱり……こうなったら。
318 = "めぐみん……やっぱり……こうなったら。"

# めぐみん
# 卒業しましょう。
342 = "卒業しましょう。"

# カズマ
# そうだな。
284 = "そうだな。"

# アクア
# いやぁぁぁぁぁぁぁ！！！
252 = "いやぁぁぁぁぁぁぁ！！！"

# カズマ（Ｍ）
# display as カズマ
# （アクアの断末魔の叫びが響き渡る中、\n　満場一致で『シャイニーブルー』は解散すると\n　決まった）
409 = "（アクアの断末魔の叫びが響き渡る中、\\n　満場一致で『シャイニーブルー』は解散すると\\n　決まった）"

[selections]
276 = "この駄女神が！"
341 = "勧誘は禁止だって言ったよな！"
315 = "みんなも何とか言ってやれ！"
