# st03a_02.txt.scn

[info]
0 = ""

[characters]
142 = "カズマ（Ｍ）"
141 = "カズマ"

[character_subs]
# 141 = "カズマ"

[script]
# lines: 39

# カズマ（Ｍ）
# display as カズマ
# （あー、またパンツ泥棒って罵られるイベントが\n　始まるのか）
171 = "（あー、またパンツ泥棒って罵られるイベントが\\n　始まるのか）"

# カズマ（Ｍ）
# display as カズマ
# （まったくあいつらは、パンツを盗まれるのも\n　もう４度目なんだからいい加減慣れろよな）
192 = "（まったくあいつらは、パンツを盗まれるのも\\n　もう４度目なんだからいい加減慣れろよな）"

# カズマ（Ｍ）
# display as カズマ
# （それこそ――）
184 = "（それこそ――）"

# カズマ
# ねえねえ、今度のパンツはどんな感じだったの？
139 = "ねえねえ、今度のパンツはどんな感じだったの？"

# カズマ（Ｍ）
# display as カズマ
# （くらいのライトな感じで聞いてこいっての！）
178 = "（くらいのライトな感じで聞いてこいっての！）"

# カズマ
# …………。
132 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （いや、無理だろ。\n　俺だってパンツを盗まれたら普通に取り乱すわ）
174 = "（いや、無理だろ。\\n　俺だってパンツを盗まれたら普通に取り乱すわ）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、もうやだ。\n　指輪の効果よりも先に胃が痛くて死にそうだ）
170 = "（ああ、もうやだ。\\n　指輪の効果よりも先に胃が痛くて死にそうだ）"

# カズマ
# え、ええと、みんな、おはよう……。
134 = "え、ええと、みんな、おはよう……。"

# カズマ
# …………。
# 132 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （って、あれ？　いない）
186 = "（って、あれ？　いない）"

# カズマ（Ｍ）
# display as カズマ
# （まだみんな寝てんのか？）
190 = "（まだみんな寝てんのか？）"

# カズマ（Ｍ）
# display as カズマ
# （まったくあいつらは……。\n　こんなに日が高くなるまで寝てるなんて\n　だらけるにも程があるってもんだろ）
191 = "（まったくあいつらは……。\\n　こんなに日が高くなるまで寝てるなんて\\n　だらけるにも程があるってもんだろ）"

# カズマ（Ｍ）
# display as カズマ
# （いや今は、あいつらの怠けっぷりに\n　感謝すべきか）
175 = "（いや今は、あいつらの怠けっぷりに\\n　感謝すべきか）"

# カズマ（Ｍ）
# display as カズマ
# （まずは、パンツを盗んだ言い訳を考えて、\n　ご機嫌取りに朝食を作っておいた方がいいだろう）
189 = "（まずは、パンツを盗んだ言い訳を考えて、\\n　ご機嫌取りに朝食を作っておいた方がいいだろう）"

# カズマ（Ｍ）
# display as カズマ
# （よし、誰かが怒鳴り込んでくる前に実行だ！）
194 = "（よし、誰かが怒鳴り込んでくる前に実行だ！）"

# カズマ（Ｍ）
# display as カズマ
# （さて、食材は何があるかな？）
182 = "（さて、食材は何があるかな？）"

# カズマ
# …………。
# 132 = "…………。"

# カズマ
# おいおい！\n全然食材が残ってねーじゃねーか！
135 = "おいおい！\\n全然食材が残ってねーじゃねーか！"

# カズマ（Ｍ）
# display as カズマ
# （これじゃ、ご機嫌を取ることもままならねぇ！\n　ひとっ走り、街に何か食べ物を買いに行くか？）
180 = "（これじゃ、ご機嫌を取ることもままならねぇ！\\n　ひとっ走り、街に何か食べ物を買いに行くか？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、それじゃあ逃げたと\n　思われるかもしれない）
173 = "（いや、それじゃあ逃げたと\\n　思われるかもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （そうだ！　酒！　酒だ！\n　飲ませて酔っ払わせちまえば――）
183 = "（そうだ！　酒！　酒だ！\\n　飲ませて酔っ払わせちまえば――）"

# カズマ（Ｍ）
# display as カズマ
# （い、いや……絡み酒で暴れられたら、\n　それこそ手がつけられなくなる……）
172 = "（い、いや……絡み酒で暴れられたら、\\n　それこそ手がつけられなくなる……）"

# カズマ（Ｍ）
# display as カズマ
# （でも、ある食材は傷んで変色した\n　野菜の残りだけだし）
187 = "（でも、ある食材は傷んで変色した\\n　野菜の残りだけだし）"

# カズマ（Ｍ）
# display as カズマ
# （うぅ、こ、こうなったら……先手必勝だ！）
176 = "（うぅ、こ、こうなったら……先手必勝だ！）"

# カズマ
# あーだこーだ文句を言われる前に、\n土下座をして何も言えなくしてやるぜ！
133 = "あーだこーだ文句を言われる前に、\\n土下座をして何も言えなくしてやるぜ！"

# カズマ
# おかしい。\n誰も部屋にいやがらねぇ。
136 = "おかしい。\\n誰も部屋にいやがらねぇ。"

# カズマ（Ｍ）
# display as カズマ
# （これはいったいどうなってんだ！？）
181 = "（これはいったいどうなってんだ！？）"

# カズマ（Ｍ）
# display as カズマ
# （はっ、まさか……）
188 = "（はっ、まさか……）"

# カズマ（Ｍ）
# display as カズマ
# （無意識にとはいえ変態行為を繰り返す俺に\n　とうとう愛想を尽かせちまったのか！？）
195 = "（無意識にとはいえ変態行為を繰り返す俺に\\n　とうとう愛想を尽かせちまったのか！？）"

# カズマ（Ｍ）
# display as カズマ
# （それとも、指輪の呪いを解除する為の金策生活に\n　疲れてたか……）
185 = "（それとも、指輪の呪いを解除する為の金策生活に\\n　疲れてたか……）"

# カズマ
# ハ、ハハ……ハハハ。\n全てを失うのって、一瞬なんだな。
143 = "ハ、ハハ……ハハハ。\\n全てを失うのって、一瞬なんだな。"

# カズマ
# でも、涙の１つも出てきやしねぇ。
138 = "でも、涙の１つも出てきやしねぇ。"

# カズマ
# って、何悲観的になってんだよ！\nこれは、ある意味転機が訪れたって事だよな！
137 = "って、何悲観的になってんだよ！\\nこれは、ある意味転機が訪れたって事だよな！"

# カズマ（Ｍ）
# display as カズマ
# （みんなが出て行ったのは、\n　むしろラッキーなんじゃないか！）
193 = "（みんなが出て行ったのは、\\n　むしろラッキーなんじゃないか！）"

# カズマ（Ｍ）
# display as カズマ
# （特にあの駄女神は、\n　稼いだ金以上に浪費しやがって、\n　いたらむしろ損！　不幸の元凶だ！）
196 = "（特にあの駄女神は、\\n　稼いだ金以上に浪費しやがって、\\n　いたらむしろ損！　不幸の元凶だ！）"

# カズマ（Ｍ）
# display as カズマ
# （これから１人で\n　指輪の呪いの解除料を稼ぐのは大変だが、\n　駄女神を返品したと考えれば安いもんだ！）
179 = "（これから１人で\\n　指輪の呪いの解除料を稼ぐのは大変だが、\\n　駄女神を返品したと考えれば安いもんだ！）"

# カズマ（Ｍ）
# display as カズマ
# （きっとここからの俺の運は上向きだ！\n　いや、きっと今まで不幸だった分、\n　幸せになれる！）
177 = "（きっとここからの俺の運は上向きだ！\\n　いや、きっと今まで不幸だった分、\\n　幸せになれる！）"

# カズマ
# よぉし！\n新しい生活の始まりに祝杯を挙げにいこう！！
140 = "よぉし！\\n新しい生活の始まりに祝杯を挙げにいこう！！"

