# st03a_05.txt.scn

[info]
0 = ""

[characters]
350 = "ウィズ"
347 = "アクア"
352 = "カズマ"
335 = "めぐみん"
361 = "バニル"
356 = "カズマ（Ｍ）"
360 = "ダクネス"
357 = "クリス"
341 = "ゆんゆん"

[character_subs]
# 352 = "カズマ"

[script]
# lines: 141

# ウィズ
# あ、いらっしゃいませ、カズマさん。
254 = "あ、いらっしゃいませ、カズマさん。"

# アクア
# 何？　ウィズの店に用でもあるの？
371 = "何？　ウィズの店に用でもあるの？"

# ウィズ
# ひゃぁっ！？　あ、アクア様！？
321 = "ひゃぁっ！？　あ、アクア様！？"

# カズマ
# 何でお前らまでついてくるんだよ。
370 = "何でお前らまでついてくるんだよ。"

# めぐみん
# まだ話足りないからですよ。
331 = "まだ話足りないからですよ。"

# カズマ
# ここまでの道すがら、\nずっと設定を語ってたのはどこの誰だ。
284 = "ここまでの道すがら、\\nずっと設定を語ってたのはどこの誰だ。"

# めぐみん
# ふっ、まだまだありますよ。\n聞きますか？
323 = "ふっ、まだまだありますよ。\\n聞きますか？"

# カズマ
# 聞かねーよ。
458 = "聞かねーよ。"

# ウィズ
# あのぉ、今日はどのようなご用件で……。
269 = "あのぉ、今日はどのようなご用件で……。"

# カズマ
# ああ、悪い。\n用事があるのはウィズにじゃなくて――
263 = "ああ、悪い。\\n用事があるのはウィズにじゃなくて――"

# バニル
# 我輩の知恵を拝借したいのであろう。
386 = "我輩の知恵を拝借したいのであろう。"

# アクア
# ちょっと待ちなさいよカズマ！\nまさか、これに助言を求めようって\n言うんじゃないでしょうね。
306 = "ちょっと待ちなさいよカズマ！\\nまさか、これに助言を求めようって\\n言うんじゃないでしょうね。"

# カズマ
# ああ、その通りだけど。
261 = "ああ、その通りだけど。"

# アクア
# 悪魔に頼るなんて、\n女神としては見逃すわけにいかないんですけど！
385 = "悪魔に頼るなんて、\\n女神としては見逃すわけにいかないんですけど！"

# バニル
# それならば女、お前が力になってやればよかろう。
297 = "それならば女、お前が力になってやればよかろう。"

# アクア
# うふふ、私に指図するなんて悪魔の分際で\nどういうつもりなのかしら？
275 = "うふふ、私に指図するなんて悪魔の分際で\\nどういうつもりなのかしら？"

# カズマ（Ｍ）
# display as カズマ
# （ああ、始まっちまった……）
464 = "（ああ、始まっちまった……）"

# バニル
# よくよく考えてみよ。\n汝らがその小僧が求める知識を持ち合わせていれば\n我輩に頼ることも無かったのだぞ。
342 = "よくよく考えてみよ。\\n汝らがその小僧が求める知識を持ち合わせていれば\\n我輩に頼ることも無かったのだぞ。"

# アクア
# うーん、それって私たちがあんたよりも\n無能だって聞こえるんだけど……気のせいかしら。
276 = "うーん、それって私たちがあんたよりも\\n無能だって聞こえるんだけど……気のせいかしら。"

# バニル
# 言わずもがな。
460 = "言わずもがな。"

# アクア
# ねえ、カズマ。\nやっぱり害虫は駆除すべきだと思うのよね。
313 = "ねえ、カズマ。\\nやっぱり害虫は駆除すべきだと思うのよね。"

# アクア
# これもそれを望んでるみたいだし……。
285 = "これもそれを望んでるみたいだし……。"

# カズマ
# アクア、顔が怖いから！
349 = "アクア、顔が怖いから！"

# バニル
# ふははは、駆け出しプリーストが我を祓うとは\n片腹痛いわ。
325 = "ふははは、駆け出しプリーストが我を祓うとは\\n片腹痛いわ。"

# カズマ
# バニルも火に油を注ぐなって！
364 = "バニルも火に油を注ぐなって！"

# ウィズ
# あのあの、アクア様、落ち着いてください。
268 = "あのあの、アクア様、落ち着いてください。"

# アクア
# 今、私の前に出ると、死ぬわよ。
369 = "今、私の前に出ると、死ぬわよ。"

# ウィズ
# ひ、ひいい！！
319 = "ひ、ひいい！！"

# カズマ
# いいからお前は落ちつけよっ！
271 = "いいからお前は落ちつけよっ！"

# アクア
# さあ、覚悟はできてるんでしょうね。
286 = "さあ、覚悟はできてるんでしょうね。"

# カズマ（Ｍ）
# display as カズマ
# （あれ？　いつもなら強く叩けば止まるのに）
465 = "（あれ？　いつもなら強く叩けば止まるのに）"

# バニル
# 覚悟とは？\nお前のジョークで笑い死ぬ覚悟か？
459 = "覚悟とは？\\nお前のジョークで笑い死ぬ覚悟か？"

# アクア
# ふふ、ふふふふ、ふふふふふ！
326 = "ふふ、ふふふふ、ふふふふふ！"

# カズマ（Ｍ）
# display as カズマ
# （うーん、だったら……）
467 = "（うーん、だったら……）"

# アクア
# セイクリット・エクソシズ――
359 = "セイクリット・エクソシズ――"

# アクア
# ムきゃ！
367 = "ムきゃ！"

# カズマ
# おっ、止まった。
281 = "おっ、止まった。"

# アクア
# ちょっとヒキニート！\nこんなときに何すんのよ！
305 = "ちょっとヒキニート！\\nこんなときに何すんのよ！"

# カズマ
# お前が前に出てると話が進まないんだよ。
282 = "お前が前に出てると話が進まないんだよ。"

# バニル
# フハハハハ、我輩は話が進まなくても\n一向に構わないが。
365 = "フハハハハ、我輩は話が進まなくても\\n一向に構わないが。"

# ウィズ
# もう、バニルさんもいい加減にしてください！
337 = "もう、バニルさんもいい加減にしてください！"

# バニル
# ふむ、確かにこんなくだらない遊びに\nいつまでも付き合うほど我輩は暇でも愚かでもない。
327 = "ふむ、確かにこんなくだらない遊びに\\nいつまでも付き合うほど我輩は暇でも愚かでもない。"

# アクア
# はぁぁぁ？　遊びですってぇ？
316 = "はぁぁぁ？　遊びですってぇ？"

# カズマ
# やめろっ！
340 = "やめろっ！"

# アクア
# きゃい！　い、痛い～～～～……。
283 = "きゃい！　い、痛い～～～～……。"

# カズマ
# でだ、バニル。\n聞きたいことがあるんだよ。
307 = "でだ、バニル。\\n聞きたいことがあるんだよ。"

# バニル
# 相談料を取るが？
453 = "相談料を取るが？"

# ウィズ
# バニルさん、\n相談くらいでしたら無償で聞いてあげてください。
362 = "バニルさん、\\n相談くらいでしたら無償で聞いてあげてください。"

# バニル
# そんな人の良さだから、\n貧乏店主などと言われるのだぞ、\nポンコツ店主よ。
301 = "そんな人の良さだから、\\n貧乏店主などと言われるのだぞ、\\nポンコツ店主よ。"

# ウィズ
# 貧乏とかポンコツとかひどいです。
461 = "貧乏とかポンコツとかひどいです。"

# バニル
# まあいい。\n今回は特別に無償で相談に乗ってやろうではないか。
330 = "まあいい。\\n今回は特別に無償で相談に乗ってやろうではないか。"

# カズマ
# 本当だろうな。
387 = "本当だろうな。"

# バニル
# 悪魔が契約事にうるさいのは小僧も\n知っているだろう。
384 = "悪魔が契約事にうるさいのは小僧も\\n知っているだろう。"

# アクア
# カズマ！\nそんなやつに相談したら絶交だからね！
355 = "カズマ！\\nそんなやつに相談したら絶交だからね！"

# カズマ
# じゃあ、遠慮無く相談させて貰うけどさ。
289 = "じゃあ、遠慮無く相談させて貰うけどさ。"

# アクア
# ちょっとカズマさん！\n絶交よ、絶交なのよ！　私本気なんだからね！\n一生口を利いてあげないんだから！
304 = "ちょっとカズマさん！\\n絶交よ、絶交なのよ！　私本気なんだからね！\\n一生口を利いてあげないんだから！"

# カズマ
# 悪い、ダクネス。\nそいつを黙らせてくれるか。
383 = "悪い、ダクネス。\\nそいつを黙らせてくれるか。"

# ダクネス
# アクア、話が終わるまで外に出ていような。
348 = "アクア、話が終わるまで外に出ていような。"

# アクア
# カズマ、カズマさぁん！\n付き合いが長い私よりも、\nそいつに寄生をされることを選ぶの！
354 = "カズマ、カズマさぁん！\\n付き合いが長い私よりも、\\nそいつに寄生をされることを選ぶの！"

# アクア
# ねえ、カズマさん答えてってばぁ！\nカズマさーーーーん！！
314 = "ねえ、カズマさん答えてってばぁ！\\nカズマさーーーーん！！"

# カズマ
# よし、これで落ち着いて話ができるな。
343 = "よし、これで落ち着いて話ができるな。"

# バニル
# それで質問とはなんだ、小僧。
296 = "それで質問とはなんだ、小僧。"

# カズマ
# ああ、この世界の本の事情って\nどうなってるのかなってのを聞きたくてさ。
259 = "ああ、この世界の本の事情って\\nどうなってるのかなってのを聞きたくてさ。"

# バニル
# なるほど、次は書物で一儲けということか。
311 = "なるほど、次は書物で一儲けということか。"

# カズマ
# さすが話が早い。
287 = "さすが話が早い。"

# バニル
# では、単刀直入に言おう。\n勧めることはできぬ。
308 = "では、単刀直入に言おう。\\n勧めることはできぬ。"

# カズマ
# はあ？　なんでだよ。
317 = "はあ？　なんでだよ。"

# バニル
# 無償で提供できる情報はここまでだな。\nこれ以上の情報は、相応の対価を求めるぞ。
390 = "無償で提供できる情報はここまでだな。\\nこれ以上の情報は、相応の対価を求めるぞ。"

# カズマ
# うぐ、わかったよ。
274 = "うぐ、わかったよ。"

# めぐみん
# いきなり頓挫ですか。\n見るに堪えない結果ですね。
272 = "いきなり頓挫ですか。\\n見るに堪えない結果ですね。"

# カズマ
# 心をえぐるようなことを言うなよ。
382 = "心をえぐるようなことを言うなよ。"

# バニル
# その様子ではろくに稼げてないようだな。
292 = "その様子ではろくに稼げてないようだな。"

# カズマ
# ああ、悲しい事に１０万エリスもたまってない。
264 = "ああ、悲しい事に１０万エリスもたまってない。"

# バニル
# 努力ができるのは命があるうちだけだ。\nせいぜい足掻き苦しめ。
373 = "努力ができるのは命があるうちだけだ。\\nせいぜい足掻き苦しめ。"

# クリス
# ん？　命ってどういうこと？
344 = "ん？　命ってどういうこと？"

# カズマ
# あああ！　今のは物の例えだよ！
265 = "あああ！　今のは物の例えだよ！"

# クリス
# ふーん……。
328 = "ふーん……。"

# カズマ
# ウィズ、じゃあまたな。
351 = "ウィズ、じゃあまたな。"

# ウィズ
# あ、はい。
256 = "あ、はい。"

# カズマ
# バニルもありがとな。助かったよ。
363 = "バニルもありがとな。助かったよ。"

# バニル
# 礼には及ばぬ。
454 = "礼には及ばぬ。"

# カズマ
# 待たせて悪かったな。
381 = "待たせて悪かったな。"

# ダクネス
# 私は構わないのだが……アクアが。
455 = "私は構わないのだが……アクアが。"

# カズマ
# ああ、ええと、アクア？
258 = "ああ、ええと、アクア？"

# アクア
# 絶交したんですから、\n話しかけないでくれますか？
457 = "絶交したんですから、\\n話しかけないでくれますか？"

# カズマ
# シュワシュワ２杯で許してくれ。
358 = "シュワシュワ２杯で許してくれ。"

# アクア
# もうしょうがないわね、特別よ。
338 = "もうしょうがないわね、特別よ。"

# カズマ（Ｍ）
# display as カズマ
# （ふう、安い女で助かった）
472 = "（ふう、安い女で助かった）"

# ダクネス
# それで、話はどうなったんだ？\n進展はあったのか？
294 = "それで、話はどうなったんだ？\\n進展はあったのか？"

# カズマ
# 進展どころか後退だ。
462 = "進展どころか後退だ。"

# クリス
# どうやら計画が頓挫したみたいなんだよね。
310 = "どうやら計画が頓挫したみたいなんだよね。"

# アクア
# ん？　本を作るって話、止めちゃうの？
345 = "ん？　本を作るって話、止めちゃうの？"

# カズマ
# ああ、いけると思ったけどな。
257 = "ああ、いけると思ったけどな。"

# アクア
# ふ～ん、まぁ、私もそうなんじゃないかと\n思っていたのよね。
329 = "ふ～ん、まぁ、私もそうなんじゃないかと\\n思っていたのよね。"

# カズマ
# 嘘をつくな！！\nさっきまでノリノリだったくせに！
377 = "嘘をつくな！！\\nさっきまでノリノリだったくせに！"

# アクア
# それで、次はどうするの？\n私早くシュワシュワ飲みたいんですけどー。
293 = "それで、次はどうするの？\\n私早くシュワシュワ飲みたいんですけどー。"

# カズマ
# あのなぁ、お前もちょっとは何か考えろよな。
270 = "あのなぁ、お前もちょっとは何か考えろよな。"

# アクア
# じゃあ……指を切る。
288 = "じゃあ……指を切る。"

# カズマ
# それはもう聞き飽きたわ！
298 = "それはもう聞き飽きたわ！"

# アクア
# ねえ、なんで嫌なのよ。
312 = "ねえ、なんで嫌なのよ。"

# カズマ
# 痛いからに決まってんだろうが！
391 = "痛いからに決まってんだろうが！"

# アクア
# そんなの一瞬でしょ。
300 = "そんなの一瞬でしょ。"

# アクア
# その後も、私が傷跡も残らないくらい綺麗に\nくっつけてあげるんだから、拒否する理由なんて\n何ひとつないじゃない。
291 = "その後も、私が傷跡も残らないくらい綺麗に\\nくっつけてあげるんだから、拒否する理由なんて\\n何ひとつないじゃない。"

# カズマ
# それでも嫌なもんは、嫌なんだ！
295 = "それでも嫌なもんは、嫌なんだ！"

# アクア
# ああ、もう、指が嫌ならじゃあ……腕。
262 = "ああ、もう、指が嫌ならじゃあ……腕。"

# カズマ
# ふっざけんなよ、この駄女神っ！
324 = "ふっざけんなよ、この駄女神っ！"

# カズマ
# 馬鹿の１つ覚えみたいに指に腕って！\n次はなんだ首か、あぁん！
463 = "馬鹿の１つ覚えみたいに指に腕って！\\n次はなんだ首か、あぁん！"

# アクア
# ああ！
266 = "ああ！"

# カズマ
# あ、それもあったわね！\nみたいなリアクションすんな！　怖いだろうが！
255 = "あ、それもあったわね！\\nみたいなリアクションすんな！　怖いだろうが！"

# アクア
# もう、あれもやだこれもやだじゃ、\n話が進まないんですけどー。
336 = "もう、あれもやだこれもやだじゃ、\\n話が進まないんですけどー。"

# カズマ
# だったら……。
302 = "だったら……。"

# カズマ
# もし、どうしようも無くなった場合、\nお前がスパッとやれよな？
339 = "もし、どうしようも無くなった場合、\\nお前がスパッとやれよな？"

# アクア
# え？
278 = "え？"

# カズマ
# 俺の指はお前が切るんだ。\nそれ以外は絶対に受け入れねえから。
372 = "俺の指はお前が切るんだ。\\nそれ以外は絶対に受け入れねえから。"

# アクア
# 嫌よ！！\nそんな汚れ仕事なんて、この可憐な女神の\nアクア様がすることじゃないわ！
378 = "嫌よ！！\\nそんな汚れ仕事なんて、この可憐な女神の\\nアクア様がすることじゃないわ！"

# カズマ
# だったら、そうならないように\nお前も真剣になんか考えろ！
303 = "だったら、そうならないように\\nお前も真剣になんか考えろ！"

# アクア
# むぅぅぅぅっ。
334 = "むぅぅぅぅっ。"

# カズマ
# みんなも、何か良いアイディアがあったら――
333 = "みんなも、何か良いアイディアがあったら――"

# めぐみん
# カズマ、ちょっと店内を見てきますね。
353 = "カズマ、ちょっと店内を見てきますね。"

# カズマ（Ｍ）
# display as カズマ
# （は？）
471 = "（は？）"

# ゆんゆん
# 私も行ってきますね。
456 = "私も行ってきますね。"

# カズマ（Ｍ）
# display as カズマ
# （おい……）
468 = "（おい……）"

# クリス
# ふぁぁぁぁ、暇。
322 = "ふぁぁぁぁ、暇。"

# カズマ（Ｍ）
# display as カズマ
# （くっ、みんなもう飽きていやがる）
469 = "（くっ、みんなもう飽きていやがる）"

# カズマ
# おいアクア！！　何か思いついたか！
280 = "おいアクア！！　何か思いついたか！"

# アクア
# ひっ！？　あ、えっと、その。
320 = "ひっ！？　あ、えっと、その。"

# アクア
# う、歌なんてどうかしら？
273 = "う、歌なんてどうかしら？"

# カズマ
# 歌ぁ？\nこの世界の歌はどんな感じで流通しているんだ？
388 = "歌ぁ？\\nこの世界の歌はどんな感じで流通しているんだ？"

# アクア
# ええと、それは私にも。
277 = "ええと、それは私にも。"

# カズマ
# まったく、適当なことばっかり――
332 = "まったく、適当なことばっかり――"

# カズマ（Ｍ）
# display as カズマ
# （いや、歌？）
466 = "（いや、歌？）"

# カズマ
# ああ、そうか！　歌だよ歌！！\nあはは、俺としたことがすっかり忘れてたぜ！
260 = "ああ、そうか！　歌だよ歌！！\\nあはは、俺としたことがすっかり忘れてたぜ！"

# アクア
# え？　え？　いいアイデアが浮かんだの！
279 = "え？　え？　いいアイデアが浮かんだの！"

# カズマ（Ｍ）
# display as カズマ
# （そうだ、この手だ！　この手があった！！）
470 = "（そうだ、この手だ！　この手があった！！）"

# ダクネス
# どうやら何か思いついたようだな。
309 = "どうやら何か思いついたようだな。"

# アクア
# ねえねえ、次は何をやるのよ。
315 = "ねえねえ、次は何をやるのよ。"

# カズマ
# それはズバリ――
299 = "それはズバリ――"

# カズマ
# アイドルだ！
346 = "アイドルだ！"

# アクア
# は？
318 = "は？"

# ダクネス
# あいどる？
267 = "あいどる？"

# カズマ
# そうだ！\n俺が、お前達をアイドルとしてプロデュースする！
290 = "そうだ！\\n俺が、お前達をアイドルとしてプロデュースする！"

