# st03c_06.txt.scn

[info]
0 = ""

[characters]
154 = "カズマ"
152 = "アクア"
160 = "ダクネス"
150 = "めぐみん"
158 = "クリス"
151 = "ゆんゆん"
157 = "カズマ（Ｍ）"
153 = "ウィズ"

[character_subs]
# 154 = "カズマ"

[script]
# lines: 25

# カズマ
# はぁぁぁ……。
147 = "はぁぁぁ……。"

# アクア
# あ、あの……カズマさん、\nお茶なんていかがかしら？
134 = "あ、あの……カズマさん、\\nお茶なんていかがかしら？"

# カズマ
# くれ。
140 = "くれ。"

# アクア
# はい、喜んで！！
149 = "はい、喜んで！！"

# ダクネス
# カズマ、そう落ち込むな。
155 = "カズマ、そう落ち込むな。"

# めぐみん
# そうですよ、大事になる前にやめられて\nよかったじゃないですか。
143 = "そうですよ、大事になる前にやめられて\\nよかったじゃないですか。"

# クリス
# 短い期間だけど、結構楽しかったしさ。
190 = "短い期間だけど、結構楽しかったしさ。"

# ゆんゆん
# はい、いい思い出になりました。
148 = "はい、いい思い出になりました。"

# カズマ
# すまない。\nせっかくみんなが手伝ってくれたのに。
142 = "すまない。\\nせっかくみんなが手伝ってくれたのに。"

# カズマ（Ｍ）
# display as カズマ
# （アイドルプロジェクトが軌道に乗ってたら、\n　今頃は……）
193 = "（アイドルプロジェクトが軌道に乗ってたら、\\n　今頃は……）"

# ウィズ
# カズマさん。\nえっと今回の件の経費と売り上げを\n計算してみたのですが……。
156 = "カズマさん。\\nえっと今回の件の経費と売り上げを\\n計算してみたのですが……。"

# ウィズ
# 衣装代等の準備費、舞台の設営費、そしてあの、\n連日の打ち上げ代と……アクア様の借金の補填を\n合わせますと……。
191 = "衣装代等の準備費、舞台の設営費、そしてあの、\\n連日の打ち上げ代と……アクア様の借金の補填を\\n合わせますと……。"

# ウィズ
# 売り上げは……マイナスになっちゃいます。
164 = "売り上げは……マイナスになっちゃいます。"

# カズマ
# くっ、わかってたけど、わかってたけどさ！
139 = "くっ、わかってたけど、わかってたけどさ！"

# ウィズ
# あ、あの……アクア様の借金を除いても計算した\nのですが、やっぱりどうしても赤字になって\nしまって……すみませんすみません。
133 = "あ、あの……アクア様の借金を除いても計算した\\nのですが、やっぱりどうしても赤字になって\\nしまって……すみませんすみません。"

# カズマ
# いや、ウィズが謝る必要はないんだ。
136 = "いや、ウィズが謝る必要はないんだ。"

# カズマ
# それもこれも、\n大金持ちになれる計画が破綻したのは――
144 = "それもこれも、\\n大金持ちになれる計画が破綻したのは――"

# アクア
# か、カズマさん……お、お茶が入りました。\n熱いのでお気をつけて……。
138 = "か、カズマさん……お、お茶が入りました。\\n熱いのでお気をつけて……。"

# カズマ
# こいつが、全てをぶち壊してくれたおかげだ！
141 = "こいつが、全てをぶち壊してくれたおかげだ！"

# アクア
# うぅ……ぐす……うぅぅ……。
137 = "うぅ……ぐす……うぅぅ……。"

# カズマ（Ｍ）
# display as カズマ
# （これはまずい……呪いの指輪の解除費用も\n　貯められずに、呪いがもう３回も発動して\n　しまっているというのに！）
192 = "（これはまずい……呪いの指輪の解除費用も\\n　貯められずに、呪いがもう３回も発動して\\n　しまっているというのに！）"

# カズマ（Ｍ）
# display as カズマ
# （被害者の女の子は、もうそろそろ我慢の\n　限界が近いだろうし、マジでなんとかしないと\n　いけないのに……）
194 = "（被害者の女の子は、もうそろそろ我慢の\\n　限界が近いだろうし、マジでなんとかしないと\\n　いけないのに……）"

# カズマ
# あ、そうだ。
135 = "あ、そうだ。"

# ウィズ
# どうかしましたか？
146 = "どうかしましたか？"

# カズマ
# そろそろ、今回のパンツ裁判やっておくか。
145 = "そろそろ、今回のパンツ裁判やっておくか。"

[selections]
159 = "コーヒーブレイク"
