# st03a_06.txt.scn

[info]
0 = ""

[characters]
297 = "ゆんゆん"
292 = "めぐみん"
311 = "ダクネス"
310 = "クリス"
306 = "カズマ"
303 = "アクア"
309 = "カズマ（Ｍ）"

[character_subs]
# 306 = "カズマ"

[script]
# lines: 140

# ゆんゆん
# ねえ、めぐみん。\nあいどるってなんなの？
280 = "ねえ、めぐみん。\\nあいどるってなんなの？"

# めぐみん
# そんなの私にもわかりませんよ。\nダクネスは何か知っていますか？
255 = "そんなの私にもわかりませんよ。\\nダクネスは何か知っていますか？"

# ダクネス
# いや、私も初めて耳にする名称だ。
217 = "いや、私も初めて耳にする名称だ。"

# クリス
# 私も初耳だね。
415 = "私も初耳だね。"

# カズマ
# よしじゃあ、アイドルについて簡単に説明するぞ。
298 = "よしじゃあ、アイドルについて簡単に説明するぞ。"

# アクア
# その必要は無いわ！\nだって、アイドルって言ったら、\nこの私の事じゃない！
248 = "その必要は無いわ！\\nだって、アイドルって言ったら、\\nこの私の事じゃない！"

# めぐみん
# そうなんですか？
241 = "そうなんですか？"

# ダクネス
# まさか、アークプリーストが、\nあいどるだというのか？
289 = "まさか、アークプリーストが、\\nあいどるだというのか？"

# アクア
# そうよ！　というか私がアイドルで、\nアイドルと言えばこの私なの！
243 = "そうよ！　というか私がアイドルで、\\nアイドルと言えばこの私なの！"

# カズマ
# あー、もうっ、ややこしくなるから\nお前は少し黙ってろ。
215 = "あー、もうっ、ややこしくなるから\\nお前は少し黙ってろ。"

# アクア
# もーっ！　間違ったことは言ってないでしょ？
296 = "もーっ！　間違ったことは言ってないでしょ？"

# カズマ（Ｍ）
# display as カズマ
# （確かに、アクアはアクシズ教団の神様だから、\n　ご本尊（アイドル）といっても、\n　間違いじゃないかもしれないが――）
428 = "（確かに、アクアはアクシズ教団の神様だから、\\n　ご本尊（アイドル）といっても、\\n　間違いじゃないかもしれないが――）"

# カズマ（Ｍ）
# display as カズマ
# （俺が目指しているアイドルとは\n　全然違うんだよ！）
426 = "（俺が目指しているアイドルとは\\n　全然違うんだよ！）"

# カズマ
# では、改めて。\nわかりやすく例を出すと、\nアイドルとは歌って踊れる可愛い女の子のことだ。
266 = "では、改めて。\\nわかりやすく例を出すと、\\nアイドルとは歌って踊れる可愛い女の子のことだ。"

# ゆんゆん
# 歌って踊れる？
338 = "歌って踊れる？"

# クリス
# 可愛い女の子？
324 = "可愛い女の子？"

# ダクネス
# そんなものでどうやって金を稼ぐというんだ。
256 = "そんなものでどうやって金を稼ぐというんだ。"

# カズマ
# それは追々話をするよ。
253 = "それは追々話をするよ。"

# カズマ
# 今は、みんなにアイドルがなんなのかを\n理解して貰うのが先だ。
317 = "今は、みんなにアイドルがなんなのかを\\n理解して貰うのが先だ。"

# めぐみん
# ええとつまり、\n歌って踊れ、さらに可愛らしい女の子が\nあいどるというものになれるんですね？
224 = "ええとつまり、\\n歌って踊れ、さらに可愛らしい女の子が\\nあいどるというものになれるんですね？"

# カズマ
# いいや、今のは一例だからな。\n別に歌が下手で基本のステップができなくても\nアイドルにはなれるんだよ。
216 = "いいや、今のは一例だからな。\\n別に歌が下手で基本のステップができなくても\\nアイドルにはなれるんだよ。"

# ダクネス
# んん？　ではいったいあいどるとはなんなんだ。
302 = "んん？　ではいったいあいどるとはなんなんだ。"

# カズマ
# 一番わかりやすいアイドルってのは、\nやっぱり高嶺の花の存在だろうな。
315 = "一番わかりやすいアイドルってのは、\\nやっぱり高嶺の花の存在だろうな。"

# カズマ
# しかし最近では、\n身近さを感じさせるアイドル像というのも\n流行ってるんだ。
237 = "しかし最近では、\\n身近さを感じさせるアイドル像というのも\\n流行ってるんだ。"

# ダクネス
# んんん？　さらにわからなくなったぞ。
301 = "んんん？　さらにわからなくなったぞ。"

# アクア
# カズマの説明は、いちいちややこしいのよ。
307 = "カズマの説明は、いちいちややこしいのよ。"

# カズマ
# そうか？
239 = "そうか？"

# アクア
# つまりアイドルっていうのは、\n異性に夢を与え、喜ばせる存在なの。
262 = "つまりアイドルっていうのは、\\n異性に夢を与え、喜ばせる存在なの。"

# めぐみん
# ということは、私たちに異性を喜ばせる何かを\nしろということなんですね？
268 = "ということは、私たちに異性を喜ばせる何かを\\nしろということなんですね？"

# カズマ
# つまりそういうことだな。
261 = "つまりそういうことだな。"

# ダクネス
# それは私にもできるのか？\n可愛いとはほど遠い、硬さだけが取り柄の\n女なのだが。
252 = "それは私にもできるのか？\\n可愛いとはほど遠い、硬さだけが取り柄の\\n女なのだが。"

# カズマ
# ダクネスは、自分を過小評価しすぎだろ。\n見た目だけならお前は十分にアイドルとして\n通用する逸材だぞ。
312 = "ダクネスは、自分を過小評価しすぎだろ。\\n見た目だけならお前は十分にアイドルとして\\n通用する逸材だぞ。"

# ダクネス
# そ、そうだろうか。
238 = "そ、そうだろうか。"

# カズマ
# めぐみんとゆんゆん、そしてクリスも同様だ。
293 = "めぐみんとゆんゆん、そしてクリスも同様だ。"

# ゆんゆん
# っ…………。
260 = "っ…………。"

# めぐみん
# 私はお世辞と受け取っておきます。
410 = "私はお世辞と受け取っておきます。"

# クリス
# あたしは素直に喜んでおくよ。
209 = "あたしは素直に喜んでおくよ。"

# カズマ
# しかし可愛いだけでは、\nアイドルとしての要素が不足してるのも\n事実なんだよ。
236 = "しかし可愛いだけでは、\\nアイドルとしての要素が不足してるのも\\n事実なんだよ。"

# ダクネス
# さらなる付加価値が、\n踊りであったり、歌であったりするわけか。
235 = "さらなる付加価値が、\\n踊りであったり、歌であったりするわけか。"

# カズマ
# あとは演技とか、人間性とか、話す力とか\nそれこそ仕草の作り方１つも要素になるのかな？
211 = "あとは演技とか、人間性とか、話す力とか\\nそれこそ仕草の作り方１つも要素になるのかな？"

# ダクネス
# どうして疑問系になるんだ。\n頼りはカズマだけなんだから\nしっかりしてくれ。
273 = "どうして疑問系になるんだ。\\n頼りはカズマだけなんだから\\nしっかりしてくれ。"

# カズマ
# そうは言われても、本当に多種多様なんだって。
242 = "そうは言われても、本当に多種多様なんだって。"

# ダクネス
# つまり要素の組み合わせで\n多様なアイドルというものが生まれるというわけ\nなんだろ？
263 = "つまり要素の組み合わせで\\n多様なアイドルというものが生まれるというわけ\\nなんだろ？"

# カズマ
# そう！　そういういことだ！
244 = "そう！　そういういことだ！"

# クリス
# うーん、いまいち想像できないんだけど、\nそれで本当にお金を稼げるの？
220 = "うーん、いまいち想像できないんだけど、\\nそれで本当にお金を稼げるの？"

# カズマ
# みんな、メイド喫茶を思い出してくれ。
291 = "みんな、メイド喫茶を思い出してくれ。"

# めぐみん
# できれば一生封印しておきたい記憶なんですが。
265 = "できれば一生封印しておきたい記憶なんですが。"

# カズマ
# 最後は欲を出してこけちまったけど、\n途中までは大盛況でかなり儲かってだろ？
335 = "最後は欲を出してこけちまったけど、\\n途中までは大盛況でかなり儲かってだろ？"

# カズマ
# 今回はあの時みたいに客を集めて、\n歌と踊りで盛り上げるんだ。
318 = "今回はあの時みたいに客を集めて、\\n歌と踊りで盛り上げるんだ。"

# クリス
# ということは、\n踊り子さんみたいなことをするってことかな？
267 = "ということは、\\n踊り子さんみたいなことをするってことかな？"

# めぐみん
# アクアの花鳥風月みたいなものですね。
304 = "アクアの花鳥風月みたいなものですね。"

# カズマ
# あれは宴会芸だろ。
214 = "あれは宴会芸だろ。"

# カズマ
# 俺たちが提供する価値は、もっとクオリティの高い\nエンターテインメント性に富んだものなんだよ。
319 = "俺たちが提供する価値は、もっとクオリティの高い\\nエンターテインメント性に富んだものなんだよ。"

# アクア
# ちょっと、私の芸を馬鹿にしないで\n欲しいんですけど！
259 = "ちょっと、私の芸を馬鹿にしないで\\n欲しいんですけど！"

# アクア
# 現場の親方達や商店街のおじさんおばさんに\nドッカンドッカン大受けなんですからね！
340 = "現場の親方達や商店街のおじさんおばさんに\\nドッカンドッカン大受けなんですからね！"

# カズマ
# 別にお前の芸を馬鹿にしてるんじゃないって。\nあくまでも目指す方向性が別だって言いたいんだ。
321 = "別にお前の芸を馬鹿にしてるんじゃないって。\\nあくまでも目指す方向性が別だって言いたいんだ。"

# ゆんゆん
# なんだか、難しそうですね。
278 = "なんだか、難しそうですね。"

# カズマ
# とにかく、まずはみんなに認知されることが重要だ。
269 = "とにかく、まずはみんなに認知されることが重要だ。"

# カズマ
# そして人を集める！\nそうすればそこに何かしらの需要が生まれる。
247 = "そして人を集める！\\nそうすればそこに何かしらの需要が生まれる。"

# カズマ
# そこからがアイドル活動の本番というわけだな。
245 = "そこからがアイドル活動の本番というわけだな。"

# ダクネス
# そんなに上手くいくとは思えないが。
254 = "そんなに上手くいくとは思えないが。"

# カズマ
# 確かに難しいかもしれないが、\nしかし可能性は０じゃない。
409 = "確かに難しいかもしれないが、\\nしかし可能性は０じゃない。"

# カズマ
# いやむしろ、俺は高確率で成功すると見ている。
218 = "いやむしろ、俺は高確率で成功すると見ている。"

# めぐみん
# また根拠のない自信を。
290 = "また根拠のない自信を。"

# カズマ
# 根拠はあるぞ。\nそれはメイド喫茶の成功だ。
337 = "根拠はあるぞ。\\nそれはメイド喫茶の成功だ。"

# カズマ
# メイド喫茶をやってわかったが、\nこの世界の男共は女の子とキャッキャッうふふする\n娯楽に飢えている。
314 = "メイド喫茶をやってわかったが、\\nこの世界の男共は女の子とキャッキャッうふふする\\n娯楽に飢えている。"

# カズマ（Ｍ）
# display as カズマ
# （サキュバスのお姉さんの店が繁盛しているのも\n　男を欲望をターゲットにした娯楽が少ないから\n　だろう）
425 = "（サキュバスのお姉さんの店が繁盛しているのも\\n　男を欲望をターゲットにした娯楽が少ないから\\n　だろう）"

# カズマ
# だから、このアイドルプロデュースも、\n必ずいける！！
257 = "だから、このアイドルプロデュースも、\\n必ずいける！！"

# クリス
# うーん、でもねぇ。
221 = "うーん、でもねぇ。"

# ゆんゆん
# 大勢の前で歌って踊るなんて、恥ずかしいですよ。
329 = "大勢の前で歌って踊るなんて、恥ずかしいですよ。"

# クリス
# あたしもかなり抵抗があるかな。\nやっぱりキャラじゃないしね。
210 = "あたしもかなり抵抗があるかな。\\nやっぱりキャラじゃないしね。"

# カズマ
# そこをなんとか頼むよ！
246 = "そこをなんとか頼むよ！"

# ゆんゆん
# う、うーん。\n申し訳ありませんけど。
219 = "う、うーん。\\n申し訳ありませんけど。"

# クリス
# 悪いけど、今回はパスさせて。
334 = "悪いけど、今回はパスさせて。"

# カズマ
# ええー！
225 = "ええー！"

# ダクネス
# ふたりとも、本当にそれでいいのか？
286 = "ふたりとも、本当にそれでいいのか？"

# ダクネス
# お前たちは、これ以上下着を盗まれる快感を\n味わいたくないと言ってただろ。
229 = "お前たちは、これ以上下着を盗まれる快感を\\n味わいたくないと言ってただろ。"

# カズマ（Ｍ）
# display as カズマ
# （しれっと快感って言いやがった……）
422 = "（しれっと快感って言いやがった……）"

# クリス
# そうなんだよね。\n下着を盗まれることと天秤にかけると、\nやっぱり手伝いをするしかないのかなとは思うよ？
240 = "そうなんだよね。\\n下着を盗まれることと天秤にかけると、\\nやっぱり手伝いをするしかないのかなとは思うよ？"

# ゆんゆん
# で、でも、何かあったら困りますし。
264 = "で、でも、何かあったら困りますし。"

# カズマ
# 大丈夫だよ。\n変な男共からは俺が絶対に守ってやるから！
328 = "大丈夫だよ。\\n変な男共からは俺が絶対に守ってやるから！"

# クリス
# あはは、そういう意味じゃないと思うんだけどな。
213 = "あはは、そういう意味じゃないと思うんだけどな。"

# カズマ
# なあ、頼むよ！\n絶対に悪いようにはしないから。
275 = "なあ、頼むよ！\\n絶対に悪いようにはしないから。"

# クリス
# わかった、今回もあたしが折れるよ。
300 = "わかった、今回もあたしが折れるよ。"

# ゆんゆん
# はぁ、私も協力します。
283 = "はぁ、私も協力します。"

# カズマ
# おお、サンキューな！
228 = "おお、サンキューな！"

# ダクネス
# めぐみんはどうする。
294 = "めぐみんはどうする。"

# めぐみん
# 私は裏方に徹しようかと思います。
413 = "私は裏方に徹しようかと思います。"

# カズマ
# 却下だ。
323 = "却下だ。"

# めぐみん
# なんでです！\n手伝うことに変わりは無いじゃないですか！
279 = "なんでです！\\n手伝うことに変わりは無いじゃないですか！"

# カズマ
# おい、ロリっ子！
227 = "おい、ロリっ子！"

# めぐみん
# ろり！？
299 = "ろり！？"

# カズマ
# お前は、貴重なロリ枠なんだぞ。\nそれをおいそれと手放せるわけないだろ。
230 = "お前は、貴重なロリ枠なんだぞ。\\nそれをおいそれと手放せるわけないだろ。"

# めぐみん
# 訳がわかりませんし、失礼にも程がありますよ！
419 = "訳がわかりませんし、失礼にも程がありますよ！"

# カズマ
# とにかくお前の参加は絶対だ！\n拒否は許さん！
270 = "とにかくお前の参加は絶対だ！\\n拒否は許さん！"

# ゆんゆん
# それにめぐみんは、\nまた下着を盗まれても平気なの？
250 = "それにめぐみんは、\\nまた下着を盗まれても平気なの？"

# カズマ
# ああ、なるほど、そういう快感に目覚めちまった\nわけか。
208 = "ああ、なるほど、そういう快感に目覚めちまった\\nわけか。"

# カズマ
# だから俺に解除料金を稼がれたら困ると。
258 = "だから俺に解除料金を稼がれたら困ると。"

# めぐみん
# なっ！？\n人を露出好みの変態のように言わないでください！
277 = "なっ！？\\n人を露出好みの変態のように言わないでください！"

# ダクネス
# 変態！？
327 = "変態！？"

# ゆんゆん
# 私は知ってるよ。\nめぐみんはそんな変態じゃないって。
412 = "私は知ってるよ。\\nめぐみんはそんな変態じゃないって。"

# ダクネス
# ぐは！
234 = "ぐは！"

# カズマ
# おい、なんかわからないけど、\nダクネスがダメージを受けてるからやめてやれ。
226 = "おい、なんかわからないけど、\\nダクネスがダメージを受けてるからやめてやれ。"

# ダクネス
# な、なんだろうな、これは。\n純粋な言葉の刃は心を深くえぐるという\nことなのだろうか。
274 = "な、なんだろうな、これは。\\n純粋な言葉の刃は心を深くえぐるという\\nことなのだろうか。"

# カズマ
# アンデッドが回復魔法でダメージを\n受けるようなもんだろ。
305 = "アンデッドが回復魔法でダメージを\\n受けるようなもんだろ。"

# ダクネス
# 失礼な！\n私が腐っているとでも言うのか！
330 = "失礼な！\\n私が腐っているとでも言うのか！"

# ダクネス
# 本当にお前はもう、ふふ、たまらないな。
336 = "本当にお前はもう、ふふ、たまらないな。"

# カズマ（Ｍ）
# display as カズマ
# （十分腐ってんだろ）
427 = "（十分腐ってんだろ）"

# ゆんゆん
# ねえ、めぐみん。\n気持ちはわかるけど、一緒に頑張ろうよ。
281 = "ねえ、めぐみん。\\n気持ちはわかるけど、一緒に頑張ろうよ。"

# めぐみん
# ぐぬぅ、わかりました。\nですが、本当に、今回が最後ですからね！
233 = "ぐぬぅ、わかりました。\\nですが、本当に、今回が最後ですからね！"

# カズマ
# 俺だってそうするつもりだ。\nいつまでも下着泥棒扱いされるのはごめんだからな。
320 = "俺だってそうするつもりだ。\\nいつまでも下着泥棒扱いされるのはごめんだからな。"

# めぐみん
# はぁ、結局こうなるんですね。
284 = "はぁ、結局こうなるんですね。"

# カズマ
# ええと、ダクネスの参加も強制な。
223 = "ええと、ダクネスの参加も強制な。"

# ダクネス
# 別に構わないが、理由くらい聞かせてくれ。
322 = "別に構わないが、理由くらい聞かせてくれ。"

# カズマ
# 美人だからだけど。
417 = "美人だからだけど。"

# ダクネス
# なっ！？
276 = "なっ！？"

# カズマ
# 美人。
416 = "美人。"

# ダクネス
# ひっ！
285 = "ひっ！"

# カズマ
# ダクネスは美しい！
313 = "ダクネスは美しい！"

# ダクネス
# ももも、もう、やめろ！\nそういう羞恥は私の好むところではない！
295 = "ももも、もう、やめろ！\\nそういう羞恥は私の好むところではない！"

# カズマ（Ｍ）
# display as カズマ
# （おお、本気で照れてるダクネスって\n　貴重かも！）
421 = "（おお、本気で照れてるダクネスって\\n　貴重かも！）"

# アクア
# ねえねえ、カズマ。
282 = "ねえねえ、カズマ。"

# カズマ
# どうした？
271 = "どうした？"

# アクア
# 衣装はどうするの？\n私としては水をイメージした優雅なのが\nいいと思うんだけど。
418 = "衣装はどうするの？\\n私としては水をイメージした優雅なのが\\nいいと思うんだけど。"

# めぐみん
# え、衣装！？\nまさかメイド喫茶の時のような\n短いスカートをまた穿かされるのですか！？
222 = "え、衣装！？\\nまさかメイド喫茶の時のような\\n短いスカートをまた穿かされるのですか！？"

# アクア
# それはそうよ、アイドルだもの。
251 = "それはそうよ、アイドルだもの。"

# ゆんゆん
# あのあの、短いスカートはちょっと困るかもです。
212 = "あのあの、短いスカートはちょっと困るかもです。"

# クリス
# 踊るってことは激しく動くってことだからね。\nあたしもそれは嫌だよ。
420 = "踊るってことは激しく動くってことだからね。\\nあたしもそれは嫌だよ。"

# めぐみん
# 私もミニスカートは\n断固として拒否させていただきます！
414 = "私もミニスカートは\\n断固として拒否させていただきます！"

# カズマ
# まあ、衣装のことはあとでしっかり話し合おうぜ。
288 = "まあ、衣装のことはあとでしっかり話し合おうぜ。"

# カズマ（Ｍ）
# display as カズマ
# （なし崩しでミニにするけどな）
424 = "（なし崩しでミニにするけどな）"

# アクア
# カズマ！\nこの計画は絶対に成功させましょうね！
308 = "カズマ！\\nこの計画は絶対に成功させましょうね！"

# カズマ
# どうしてお前はそんなに乗り気なんだ。
272 = "どうしてお前はそんなに乗り気なんだ。"

# アクア
# お金が欲しいからよ！　当然じゃない！
232 = "お金が欲しいからよ！　当然じゃない！"

# カズマ
# お前はどんだけ自分の欲に正直なんだよ。
231 = "お前はどんだけ自分の欲に正直なんだよ。"

# アクア
# 私はこの世界に来て思い知ったの。\n世の中は、しょせんお金だって！
411 = "私はこの世界に来て思い知ったの。\\n世の中は、しょせんお金だって！"

# カズマ
# 待て待て、崇められる対象のお前が\nそんな身も蓋もないことを言うな。
333 = "待て待て、崇められる対象のお前が\\nそんな身も蓋もないことを言うな。"

# アクア
# それに、これで私の名前が広まれば、\n信者が一気に増えるわ。
249 = "それに、これで私の名前が広まれば、\\n信者が一気に増えるわ。"

# アクア
# ふふ、そうなったら夢の貢ぎ物生活よ。
287 = "ふふ、そうなったら夢の貢ぎ物生活よ。"

# カズマ（Ｍ）
# display as カズマ
# （どうしてこの世の中には、\n　こんなやつを信仰してるやつがいるんだろう）
423 = "（どうしてこの世の中には、\\n　こんなやつを信仰してるやつがいるんだろう）"

