# st03a_03.txt.scn

[info]
0 = ""

[characters]
270 = "カズマ（Ｍ）"
268 = "カズマ"
260 = "めぐみん"
266 = "アクア"
273 = "ダクネス"
262 = "ゆんゆん"
271 = "クリス"

[character_subs]
# 268 = "カズマ"

[script]
# lines: 98

# カズマ（Ｍ）
# display as カズマ
# （おっ、こんな時間から賑やかだな）
340 = "（おっ、こんな時間から賑やかだな）"

# カズマ
# おねーさーんっ、唐揚げをお願いしまーす！
229 = "おねーさーんっ、唐揚げをお願いしまーす！"

# カズマ（Ｍ）
# display as カズマ
# （ああ、なんて清々しい！\n　憑き物が落ちるってたぶんこういうことを\n　言うんだろうな！）
335 = "（ああ、なんて清々しい！\\n　憑き物が落ちるってたぶんこういうことを\\n　言うんだろうな！）"

# めぐみん
# ……あ。
209 = "……あ。"

# カズマ
# ……あ、憑き物。
208 = "……あ、憑き物。"

# めぐみん
# なんです、それ。
256 = "なんです、それ。"

# カズマ
# い、いやこっちの話だ。
219 = "い、いやこっちの話だ。"

# カズマ
# てか、お前こんなところで何やってんだよ。
249 = "てか、お前こんなところで何やってんだよ。"

# アクア
# 何って、朝食を食べに来たのよ。
278 = "何って、朝食を食べに来たのよ。"

# カズマ
# アクア！？
267 = "アクア！？"

# ダクネス
# まあ、それだけではないのだがな。
259 = "まあ、それだけではないのだがな。"

# カズマ
# ダクネスまで！！
274 = "ダクネスまで！！"

# ゆんゆん
# あ、あの、カズマさんおはようございます。
210 = "あ、あの、カズマさんおはようございます。"

# クリス
# いやもう、おはようって時間でも無いけどね。
222 = "いやもう、おはようって時間でも無いけどね。"

# カズマ
# ゆんゆん、それにクリスまで！
263 = "ゆんゆん、それにクリスまで！"

# アクア
# それでカズマはこんなところで何やってるの？
243 = "それでカズマはこんなところで何やってるの？"

# カズマ
# 俺は朝食を――
280 = "俺は朝食を――"

# カズマ
# じゃなくて、お前ら何も言わないで\n出て行きやがって！
239 = "じゃなくて、お前ら何も言わないで\\n出て行きやがって！"

# アクア
# あら、もしかして心配したの？\nそれとも寂しかったのかしら？
216 = "あら、もしかして心配したの？\\nそれとも寂しかったのかしら？"

# カズマ
# いや、憑き物が落ちたと思ってすっきりしてた。
221 = "いや、憑き物が落ちたと思ってすっきりしてた。"

# アクア
# 自分のことを棚に上げて随分な言い草ね。
334 = "自分のことを棚に上げて随分な言い草ね。"

# めぐみん
# %fsyogen;そうですよ。\nこっちは落としても落とせない憑き物を\n抱えているんですからね。
21 = "%fsyogen;そうですよ。\\nこっちは落としても落とせない憑き物を\\n抱えているんですからね。"

# カズマ
# うぐっ。
223 = "うぐっ。"

# カズマ（Ｍ）
# display as カズマ
# （ん？　めぐみんにしては辛辣な言い方だな）
347 = "（ん？　めぐみんにしては辛辣な言い方だな）"

# カズマ（Ｍ）
# display as カズマ
# （いや、いつも通りか？\n　念のため証言としてゲットしておくか）
338 = "（いや、いつも通りか？\\n　念のため証言としてゲットしておくか）"

# アクア
# はぁ、もうシュワシュワでも飲まないと\nやってられないのよ。
258 = "はぁ、もうシュワシュワでも飲まないと\\nやってられないのよ。"

# めぐみん
# あっ、アクア！\nそれは私の唐揚げですよ！
214 = "あっ、アクア！\\nそれは私の唐揚げですよ！"

# ゆんゆん
# めぐみん、手づかみなんてはしたないよ。
261 = "めぐみん、手づかみなんてはしたないよ。"

# カズマ
# ええと、クリス。\nこれってどういう状況なんだ？
227 = "ええと、クリス。\\nこれってどういう状況なんだ？"

# クリス
# なんか家に食べる物が何もなかった\nらしいんだよ。
254 = "なんか家に食べる物が何もなかった\\nらしいんだよ。"

# カズマ
# なんだ、ただ飯を食いに来てただけなのか。
255 = "なんだ、ただ飯を食いに来てただけなのか。"

# ダクネス
# それは目的の一つだがな。
245 = "それは目的の一つだがな。"

# クリス
# そうだね。\n朝食を食べるだけだったら、私とゆんゆんが\n呼ばれる理由が無いわけだし。
240 = "そうだね。\\n朝食を食べるだけだったら、私とゆんゆんが\\n呼ばれる理由が無いわけだし。"

# カズマ
# じゃあ、飯以外の目的ってなんなんだ？
238 = "じゃあ、飯以外の目的ってなんなんだ？"

# アクア
# カズマの未来についての話し合いをするためよ。
269 = "カズマの未来についての話し合いをするためよ。"

# カズマ
# 俺の未来？　なんだそれ？
279 = "俺の未来？　なんだそれ？"

# アクア
# あんた、何をしでかしてるかわかってるわよね？
217 = "あんた、何をしでかしてるかわかってるわよね？"

# カズマ
# それは、まあ。
244 = "それは、まあ。"

# クリス
# 少しは想像できると思うんだけどさ――
283 = "少しは想像できると思うんだけどさ――"

# クリス
# 満月の夜が来るたびに下着を盗まれるんじゃない\nかって怯えるのって、精神的にくるんだよね。
288 = "満月の夜が来るたびに下着を盗まれるんじゃない\\nかって怯えるのって、精神的にくるんだよね。"

# ダクネス
# 私は嫌いではないが。
333 = "私は嫌いではないが。"

# ゆんゆん
# %fsyogen;私、朝起きたらパンツを穿いてないなんて、\n恥ずかしくて耐えられません！
23 = "%fsyogen;私、朝起きたらパンツを穿いてないなんて、\\n恥ずかしくて耐えられません！"

# カズマ（Ｍ）
# display as カズマ
# （このゆんゆんの恥ずかしがり方、\n　ちょっと普通じゃ無いな）
343 = "（このゆんゆんの恥ずかしがり方、\\n　ちょっと普通じゃ無いな）"

# カズマ（Ｍ）
# display as カズマ
# （怪しい……証言としてゲットしておくか）
352 = "（怪しい……証言としてゲットしておくか）"

# ダクネス
# 私は嫌いではないが。
# 333 = "私は嫌いではないが。"

# めぐみん
# しかも、パンツを盗まれてしまったら、\n別のパンツを穿くことが出来なくなるのは\n非常に困ります。
236 = "しかも、パンツを盗まれてしまったら、\\n別のパンツを穿くことが出来なくなるのは\\n非常に困ります。"

# ダクネス
# 私は嫌いではないが。
# 333 = "私は嫌いではないが。"

# アクア
# わかった？　みんなこんなに困ってるの。
265 = "わかった？　みんなこんなに困ってるの。"

# カズマ（Ｍ）
# display as カズマ
# （くっそー！！　不可抗力とはいえ\n　迷惑かけているのは事実だから反論の余地もねー）
342 = "（くっそー！！　不可抗力とはいえ\\n　迷惑かけているのは事実だから反論の余地もねー）"

# ゆんゆん
# %fsyogen;もう……指輪もろとも\n火口に放り込んじゃいませんか？
22 = "%fsyogen;もう……指輪もろとも\\n火口に放り込んじゃいませんか？"

# めぐみん
# え……何を言っているんですか。
226 = "え……何を言っているんですか。"

# アクア
# うーん、良い案だとは思うけど、\nさすがに溶けちゃったらリザレクションしても\n再生できないわ。
225 = "うーん、良い案だとは思うけど、\\nさすがに溶けちゃったらリザレクションしても\\n再生できないわ。"

# ゆんゆん
# いいじゃないですか、それで。
220 = "いいじゃないですか、それで。"

# カズマ
# よくないから！\nねえ、どうしちゃったの、ゆんゆん！\n目が底光りしてるよ！
264 = "よくないから！\\nねえ、どうしちゃったの、ゆんゆん！\\n目が底光りしてるよ！"

# ゆんゆん
# え！？　あ、私、何か変なこといいましたか？
228 = "え！？　あ、私、何か変なこといいましたか？"

# めぐみん
# とりあえず、何か食べて落ち着いてください。
251 = "とりあえず、何か食べて落ち着いてください。"

# ゆんゆん
# うん、ありがとうね、めぐみん。
224 = "うん、ありがとうね、めぐみん。"

# カズマ（Ｍ）
# display as カズマ
# （火口に放り込むなんて、\n　心優しいゆんゆんらしからぬ\n　物騒な発言だったな）
353 = "（火口に放り込むなんて、\\n　心優しいゆんゆんらしからぬ\\n　物騒な発言だったな）"

# カズマ（Ｍ）
# display as カズマ
# （それに今のゆんゆんの目、冗談とは思えない、\n　本気の目だった）
345 = "（それに今のゆんゆんの目、冗談とは思えない、\\n　本気の目だった）"

# カズマ（Ｍ）
# display as カズマ
# （これは証言としてゲットしておいた方が\n　いいだろう）
344 = "（これは証言としてゲットしておいた方が\\n　いいだろう）"

# アクア
# ねえ、やっぱりさ。\n指をすぱっと落としちゃいましょうよ。
257 = "ねえ、やっぱりさ。\\n指をすぱっと落としちゃいましょうよ。"

# カズマ
# それだけは絶対に嫌だ！
242 = "それだけは絶対に嫌だ！"

# アクア
# じゃあ、腕？
237 = "じゃあ、腕？"

# カズマ
# 殴るぞ、お前！
286 = "殴るぞ、お前！"

# めぐみん
# では、私の爆裂魔法でっ！
250 = "では、私の爆裂魔法でっ！"

# カズマ
# 爆裂魔法で何するんだよ！
290 = "爆裂魔法で何するんだよ！"

# めぐみん
# こう、カズマが差し出した指輪に向かって\nチュドーンっと。
235 = "こう、カズマが差し出した指輪に向かって\\nチュドーンっと。"

# カズマ
# そんな微調整がきく魔法じゃねーだろ！
246 = "そんな微調整がきく魔法じゃねーだろ！"

# めぐみん
# ちっ、気がつきましたか。
247 = "ちっ、気がつきましたか。"

# カズマ
# お前、指輪が取れたら\n絶対にヒーヒー言わせてやるからなっ！
230 = "お前、指輪が取れたら\\n絶対にヒーヒー言わせてやるからなっ！"

# めぐみん
# 火口に放り込みましょう。\n今すぐに。
289 = "火口に放り込みましょう。\\n今すぐに。"

# カズマ
# なっ！？
253 = "なっ！？"

# アクア
# 確かウィズがテレポートを使えたわよね。
332 = "確かウィズがテレポートを使えたわよね。"

# カズマ
# お前は余計なことを言うな！
232 = "お前は余計なことを言うな！"

# クリス
# ああ、それだったら、運ぶ手間が省けるね。
213 = "ああ、それだったら、運ぶ手間が省けるね。"

# カズマ
# クリスまで！！
272 = "クリスまで！！"

# クリス
# あはは、ごめんごめん、冗談だよ、冗談。
215 = "あはは、ごめんごめん、冗談だよ、冗談。"

# めぐみん
# ちょっとウィズのお店に行ってきます。
248 = "ちょっとウィズのお店に行ってきます。"

# カズマ
# お前は本気なのか！！
233 = "お前は本気なのか！！"

# カズマ（Ｍ）
# display as カズマ
# （くぅっ、みんなに殺されるか、\n　指輪に殺されるかの２択しかないのか？）
341 = "（くぅっ、みんなに殺されるか、\\n　指輪に殺されるかの２択しかないのか？）"

# カズマ（Ｍ）
# display as カズマ
# （何か妙案を、打開策を！\n　考えろ、考えるんだ、俺！！）
350 = "（何か妙案を、打開策を！\\n　考えろ、考えるんだ、俺！！）"

# ダクネス
# ハァハァハァハァ……。
275 = "ハァハァハァハァ……。"

# カズマ（Ｍ）
# display as カズマ
# （何かいい案を！！）
349 = "（何かいい案を！！）"

# ダクネス
# ハァハァハァハァ。
276 = "ハァハァハァハァ。"

# カズマ（Ｍ）
# display as カズマ
# （い、いい案を……）
337 = "（い、いい案を……）"

# ダクネス
# くはぁ、たまらん！
234 = "くはぁ、たまらん！"

# カズマ
# お前はうるさいわ！！\n何をハァハァ言ってんだよ！
231 = "お前はうるさいわ！！\\n何をハァハァ言ってんだよ！"

# ダクネス
# %fsyogen;い、いや、今日は冷えるなと。\n特に腰のあたりが！
20 = "%fsyogen;い、いや、今日は冷えるなと。\\n特に腰のあたりが！"

# カズマ
# あ、ええと、そうなの？
211 = "あ、ええと、そうなの？"

# カズマ（Ｍ）
# display as カズマ
# （冷えるだけで興奮するとかわけわからん）
351 = "（冷えるだけで興奮するとかわけわからん）"

# カズマ（Ｍ）
# display as カズマ
# （あっ、もしかして寒気でハァハァしてたのか？）
336 = "（あっ、もしかして寒気でハァハァしてたのか？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、違う。\n　中に穿いていないから、\n　ということも考えられる）
339 = "（いや、違う。\\n　中に穿いていないから、\\n　ということも考えられる）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスの考えていることはよくわからないけど、\n　念のため証言として押さえておくか）
348 = "（ダクネスの考えていることはよくわからないけど、\\n　念のため証言として押さえておくか）"

# カズマ
# なあ、寒いなら何か温かい物でも頼もうか？
252 = "なあ、寒いなら何か温かい物でも頼もうか？"

# ダクネス
# い、いや、心遣いには感謝するが、\nこのままでいいんだ。
218 = "い、いや、心遣いには感謝するが、\\nこのままでいいんだ。"

# カズマ
# そうなのか？
241 = "そうなのか？"

# ダクネス
# ああ、ありがとうカズマ。
212 = "ああ、ありがとうカズマ。"

# カズマ（Ｍ）
# display as カズマ
# （まぁ、ダクネスがそういうんだったら、\n　いいけど……）
346 = "（まぁ、ダクネスがそういうんだったら、\\n　いいけど……）"

