# st03b_02.txt.scn

[info]
0 = ""

[characters]
347 = "カズマ（Ｍ）"
346 = "カズマ"
343 = "アクア"
335 = "ゆんゆん"
348 = "クリス"
333 = "めぐみん"
345 = "ウィズ"
351 = "ダクネス"

[character_subs]
# 346 = "カズマ"

[script]
# lines: 140

# カズマ（Ｍ）
# display as カズマ
# （ふう、さっぱりした）
449 = "（ふう、さっぱりした）"

# カズマ（Ｍ）
# display as カズマ
# （さて、あいつらの試着はどうなったかな）
447 = "（さて、あいつらの試着はどうなったかな）"

# カズマ
# おーい、もう入っても大丈夫なのか？
263 = "おーい、もう入っても大丈夫なのか？"

# アクア
# うん、平気よ。
257 = "うん、平気よ。"

# カズマ
# どれどれ、どんな具合――
308 = "どれどれ、どんな具合――"

# アクア
# どう？　カズマ。\nなかなかいい感じだと思わない？
307 = "どう？　カズマ。\\nなかなかいい感じだと思わない？"

# カズマ（Ｍ）
# display as カズマ
# （あれ、おかしいぞ。\n　アクアが可愛く見える）
443 = "（あれ、おかしいぞ。\\n　アクアが可愛く見える）"

# ゆんゆん
# はぁ、肌の露出が少なくて少し安心しました。
321 = "はぁ、肌の露出が少なくて少し安心しました。"

# クリス
# でもやっぱり、スカートが短いよね。
306 = "でもやっぱり、スカートが短いよね。"

# めぐみん
# これ、どうにか長くできません？
268 = "これ、どうにか長くできません？"

# カズマ（Ｍ）
# display as カズマ
# （ああ、なるほど、そういうことか――）
441 = "（ああ、なるほど、そういうことか――）"

# ウィズ
# うう、こんな格好で人前に立てなんて無理です。
254 = "うう、こんな格好で人前に立てなんて無理です。"

# ダクネス
# メイド服もそうだったが、\n私たちには不相応の衣装かもしれないな。
354 = "メイド服もそうだったが、\\n私たちには不相応の衣装かもしれないな。"

# カズマ（Ｍ）
# display as カズマ
# （アクアが可愛いく見えたのは、\n　衣装補正が入ったからなんだな）
452 = "（アクアが可愛いく見えたのは、\\n　衣装補正が入ったからなんだな）"

# カズマ（Ｍ）
# display as カズマ
# （うん、よかった、なんか安心した）
444 = "（うん、よかった、なんか安心した）"

# カズマ
# よしじゃあ、２人ずつ確認するからな。
339 = "よしじゃあ、２人ずつ確認するからな。"

# めぐみん
# な、なんでですか！
310 = "な、なんでですか！"

# カズマ
# 突貫作業で作った衣装なんだから、\nどこかに不具合があるかもしれないだろ。
434 = "突貫作業で作った衣装なんだから、\\nどこかに不具合があるかもしれないだろ。"

# カズマ
# それこそ、縫い目がほつれて\nスカートが脱げたりしたら\nどうするつもりだ。
285 = "それこそ、縫い目がほつれて\\nスカートが脱げたりしたら\\nどうするつもりだ。"

# めぐみん
# そ、それは困ります！
276 = "そ、それは困ります！"

# カズマ
# だろ？　だったら我慢してくれ。
303 = "だろ？　だったら我慢してくれ。"

# めぐみん
# う、うぐぐ、覗き込んだら記憶がなくなるまで\n殴り続けますからね。
253 = "う、うぐぐ、覗き込んだら記憶がなくなるまで\\n殴り続けますからね。"

# カズマ
# そんなことしないって。
293 = "そんなことしないって。"

# カズマ
# じゃあ、クリスもこっちに来てくれ。
274 = "じゃあ、クリスもこっちに来てくれ。"

# クリス
# ええ、めぐみんと並ぶのって、\n結構勇気がいるんだけど。
261 = "ええ、めぐみんと並ぶのって、\\n結構勇気がいるんだけど。"

# めぐみん
# なんですかそれは。
318 = "なんですかそれは。"

# クリス
# メイド服のときもそうだったけどさ、\nめぐみんはこういう衣装が映えるんだよ。
353 = "メイド服のときもそうだったけどさ、\\nめぐみんはこういう衣装が映えるんだよ。"

# クリス
# だから、どうしてもこっちが\n引き立て役になっちゃうんだよね。
297 = "だから、どうしてもこっちが\\n引き立て役になっちゃうんだよね。"

# めぐみん
# それは私のセリフですよ。\nクリスはすらっとしていて足も長いですし、\n羨ましいです。
291 = "それは私のセリフですよ。\\nクリスはすらっとしていて足も長いですし、\\n羨ましいです。"

# クリス
# あはは、ありがとう。
246 = "あはは、ありがとう。"

# カズマ
# 見た限りは問題なさそうだけど、\n着た感じどうだ？
437 = "見た限りは問題なさそうだけど、\\n着た感じどうだ？"

# めぐみん
# スカートが短いです！
350 = "スカートが短いです！"

# カズマ
# 我慢してくれ。
367 = "我慢してくれ。"

# めぐみん
# そこをなんとか！
283 = "そこをなんとか！"

# カズマ
# はい、じゃあ次は、ゆんゆんとウィズな。
323 = "はい、じゃあ次は、ゆんゆんとウィズな。"

# めぐみん
# 無視ですか！　無視するんですね！
372 = "無視ですか！　無視するんですね！"

# めぐみん
# いいでしょう、それならば寝るときまでずっと\n耳元で囁き続けてあげますよ。
250 = "いいでしょう、それならば寝るときまでずっと\\n耳元で囁き続けてあげますよ。"

# カズマ
# うっとうしいからやめてくれ。
256 = "うっとうしいからやめてくれ。"

# めぐみん
# ほら、ゆんゆんも何か言ってください。
328 = "ほら、ゆんゆんも何か言ってください。"

# ゆんゆん
# あ、あの、カズマさん！\n私もスカートを長くしていただきたいです！
240 = "あ、あの、カズマさん！\\n私もスカートを長くしていただきたいです！"

# カズマ
# うーん、ゆんゆんはミニスカートがよく似合うね。\nこれなら絶対に友達がたくさんできるよ。
258 = "うーん、ゆんゆんはミニスカートがよく似合うね。\\nこれなら絶対に友達がたくさんできるよ。"

# ゆんゆん
# めぐみん、私はこの格好で頑張るね！
334 = "めぐみん、私はこの格好で頑張るね！"

# めぐみん
# あなたに期待した私がバカでしたよ。
243 = "あなたに期待した私がバカでしたよ。"

# カズマ
# しかしあれだな、ふたりとも。
273 = "しかしあれだな、ふたりとも。"

# ウィズ
# な、なんですか？
309 = "な、なんですか？"

# カズマ（Ｍ）
# display as カズマ
# （はちきれんばかりだ！）
448 = "（はちきれんばかりだ！）"

# ウィズ
# あの、カズマさん？\n目がちょっと怖いんですが。
244 = "あの、カズマさん？\\n目がちょっと怖いんですが。"

# カズマ
# ああ、悪い、なんでもないんだ。
242 = "ああ、悪い、なんでもないんだ。"

# カズマ
# それよりも衣装に何かおかしいところはないか？
292 = "それよりも衣装に何かおかしいところはないか？"

# ウィズ
# そうですね。\nやはりスカートの短さがちょっと気になります。
279 = "そうですね。\\nやはりスカートの短さがちょっと気になります。"

# めぐみん
# そうですよ！\nこれでは、少し屈んだだけで\n見えてしまうじゃないですか！
280 = "そうですよ！\\nこれでは、少し屈んだだけで\\n見えてしまうじゃないですか！"

# ウィズ
# そ、それは！
277 = "そ、それは！"

# ゆんゆん
# 困ります！
363 = "困ります！"

# ダクネス
# さらに、この衣装で踊るのだろう？
272 = "さらに、この衣装で踊るのだろう？"

# クリス
# あれだね、見てくださいって\n言ってるようなものだよね。
247 = "あれだね、見てくださいって\\n言ってるようなものだよね。"

# めぐみん
# まさかカズマはそれを狙って！
332 = "まさかカズマはそれを狙って！"

# カズマ
# そんなわけねーだろ！
295 = "そんなわけねーだろ！"

# カズマ（Ｍ）
# display as カズマ
# （あるけど……）
442 = "（あるけど……）"

# めぐみん
# でしたら、スカートが短い意味を\n論理的に説明してください！
304 = "でしたら、スカートが短い意味を\\n論理的に説明してください！"

# カズマ（Ｍ）
# display as カズマ
# （ぐっ、論理的にだと……）
446 = "（ぐっ、論理的にだと……）"

# カズマ
# これくらい、アイドルにとっては普通だからだ！
270 = "これくらい、アイドルにとっては普通だからだ！"

# ウィズ
# えぇぇっ！？　これが普通なんですか？
259 = "えぇぇっ！？　これが普通なんですか？"

# カズマ
# まぁ、アイドル文化を知らないから、\n戸惑うのも無理は無いけどさ――
331 = "まぁ、アイドル文化を知らないから、\\n戸惑うのも無理は無いけどさ――"

# カズマ
# アイドルの子たちはこういう衣装で\n普通に歌って踊ってるんだぞ。
342 = "アイドルの子たちはこういう衣装で\\n普通に歌って踊ってるんだぞ。"

# めぐみん
# なんですかそれ。\n見えないように動く熟練の技のようなものが\nあるんですか。
317 = "なんですかそれ。\\n見えないように動く熟練の技のようなものが\\nあるんですか。"

# カズマ
# ま、まあ、そんなところだろうな。
330 = "ま、まあ、そんなところだろうな。"

# カズマ（Ｍ）
# display as カズマ
# （本当は衣装に工夫がされてるんだけど、\n　そこまで気が回らなかったなんて言えない）
453 = "（本当は衣装に工夫がされてるんだけど、\\n　そこまで気が回らなかったなんて言えない）"

# クリス
# いやいや、こんな格好で踊るなんて、\n世の中にはすごい仕事があるものだね。
252 = "いやいや、こんな格好で踊るなんて、\\n世の中にはすごい仕事があるものだね。"

# カズマ
# 剣士が剣を、魔術師がロッドを持つように、\nアイドルは丈の短いスカートを穿くもんなんだ。
360 = "剣士が剣を、魔術師がロッドを持つように、\\nアイドルは丈の短いスカートを穿くもんなんだ。"

# カズマ
# これがスカートが短い論理的な説明だ！
269 = "これがスカートが短い論理的な説明だ！"

# めぐみん
# それのどこに論理性が！
289 = "それのどこに論理性が！"

# カズマ（Ｍ）
# display as カズマ
# （無いっ、確かに無いっ！　欠片も無い！\n　だから、ここは勢いで押し切る！）
454 = "（無いっ、確かに無いっ！　欠片も無い！\\n　だから、ここは勢いで押し切る！）"

# カズマ
# じゃああれか？\nお前は魔術師なのにロッドを持たないのか！
275 = "じゃああれか？\\nお前は魔術師なのにロッドを持たないのか！"

# カズマ
# くだらない自己満足のために眼帯とかつけるくせに、\nアイドル様のスカートを馬鹿にするなんて\n何様のつもりだよ、あぁん！
265 = "くだらない自己満足のために眼帯とかつけるくせに、\\nアイドル様のスカートを馬鹿にするなんて\\n何様のつもりだよ、あぁん！"

# めぐみん
# 誰もバカになんてしてませんよ！\nそれに眼帯がくだらないとは言ってくれますね！
439 = "誰もバカになんてしてませんよ！\\nそれに眼帯がくだらないとは言ってくれますね！"

# カズマ
# よーし、だったら眼帯の意味を論理的に\n説明してみろよ！
340 = "よーし、だったら眼帯の意味を論理的に\\n説明してみろよ！"

# カズマ
# ほらほら、早く！\n最初に論理性を求めたのはお前だろ！
329 = "ほらほら、早く！\\n最初に論理性を求めたのはお前だろ！"

# めぐみん
# ぐ、ぐぬぬ、ああ言えばこう言う……。
266 = "ぐ、ぐぬぬ、ああ言えばこう言う……。"

# カズマ（Ｍ）
# display as カズマ
# （ふっ、論点のすり替え成功）
451 = "（ふっ、論点のすり替え成功）"

# アクア
# ねえねえ、カズマ。
319 = "ねえねえ、カズマ。"

# カズマ
# なんだ、お前も意見があるのかよ。
315 = "なんだ、お前も意見があるのかよ。"

# アクア
# あのね、女神の私には羽衣が必要だと思うの。\n華やかさが増すし、それに受けると思うのよね。
245 = "あのね、女神の私には羽衣が必要だと思うの。\\n華やかさが増すし、それに受けると思うのよね。"

# カズマ
# そんもん自分で作れよ！\nあと空気読め！
296 = "そんもん自分で作れよ！\\nあと空気読め！"

# アクア
# な、何よ、怒鳴らなくてもいいじゃない。
311 = "な、何よ、怒鳴らなくてもいいじゃない。"

# カズマ
# はぁぁ、よし、これで衣装は問題なしだな。
322 = "はぁぁ、よし、これで衣装は問題なしだな。"

# カズマ
# 見せるのがアイドルの仕事なんだ！
436 = "見せるのがアイドルの仕事なんだ！"

# ダクネス
# そうなのか！
281 = "そうなのか！"

# カズマ
# よし、ダクネス。\nお前はそれ以上喋るな。\n話がややこしくなる。
337 = "よし、ダクネス。\\nお前はそれ以上喋るな。\\n話がややこしくなる。"

# ダクネス
# なぁ！？
312 = "なぁ！？"

# カズマ
# いいか、誤解が生まれないように言っておく。\n俺が言ってる見せるというのは、\n別に薄いひらひらした布地のことじゃないぞ。
249 = "いいか、誤解が生まれないように言っておく。\\n俺が言ってる見せるというのは、\\n別に薄いひらひらした布地のことじゃないぞ。"

# クリス
# いや、そこは普通にパンツって言おうよ。
251 = "いや、そこは普通にパンツって言おうよ。"

# カズマ
# 俺たちが見せるのは、エンターテインメント！\n歌、踊り、演技、そしてトーク！
358 = "俺たちが見せるのは、エンターテインメント！\\n歌、踊り、演技、そしてトーク！"

# カズマ
# その中に、スカートの短さも含まれているんだ！
284 = "その中に、スカートの短さも含まれているんだ！"

# めぐみん
# ……わけがわかりません。
239 = "……わけがわかりません。"

# カズマ
# そうだろうな。\nそして理由を聞いても理解はできないだろう。
278 = "そうだろうな。\\nそして理由を聞いても理解はできないだろう。"

# ゆんゆん
# い、一応、聞かせて貰えますか？
248 = "い、一応、聞かせて貰えますか？"

# カズマ
# ふっ、チラリズムだ。
326 = "ふっ、チラリズムだ。"

# ゆんゆん
# へ？
327 = "へ？"

# カズマ
# スカートがひらりと浮くが、見えそうで見えない。\nしかし男は、そこに何かを見る！
349 = "スカートがひらりと浮くが、見えそうで見えない。\\nしかし男は、そこに何かを見る！"

# ゆんゆん
# ええと、太もも……とかですか？
262 = "ええと、太もも……とかですか？"

# カズマ
# 違う……ロマンだ。
440 = "違う……ロマンだ。"

# めぐみん
# バカなんですか？
352 = "バカなんですか？"

# カズマ
# ああ、バカだよ！\nでも男ってのはそういう生き物なんだ！
241 = "ああ、バカだよ！\\nでも男ってのはそういう生き物なんだ！"

# カズマ
# なんだよ、めぐみんならわかってくれると\n思ってたのに。
316 = "なんだよ、めぐみんならわかってくれると\\n思ってたのに。"

# めぐみん
# 今の話のどこに賛同できる要素があったと\nいうのです。
357 = "今の話のどこに賛同できる要素があったと\\nいうのです。"

# カズマ
# お前はなんのために爆裂魔法を撃つ。
264 = "お前はなんのために爆裂魔法を撃つ。"

# めぐみん
# はっ！
324 = "はっ！"

# カズマ
# そこに何がある！
282 = "そこに何がある！"

# めぐみん
# ロ、ロマン……。
355 = "ロ、ロマン……。"

# カズマ
# だろ？
301 = "だろ？"

# めぐみん
# です！
305 = "です！"

# ゆんゆん
# なんか言いくるめられてるような。
314 = "なんか言いくるめられてるような。"

# クリス
# 話がややこしくなるから、それは黙ってよう？
438 = "話がややこしくなるから、それは黙ってよう？"

# カズマ
# よし、これで衣装は問題なしだな。
336 = "よし、これで衣装は問題なしだな。"

# カズマ
# そんなもんはない！
294 = "そんなもんはない！"

# めぐみん
# この男、開き直りましたよ。
267 = "この男、開き直りましたよ。"

# カズマ
# よしじゃあ、聞こう！\nお前が爆裂魔法を撃つことに、\n論理性があるのか？
338 = "よしじゃあ、聞こう！\\nお前が爆裂魔法を撃つことに、\\n論理性があるのか？"

# めぐみん
# それは、ありませんけど。
290 = "それは、ありませんけど。"

# カズマ
# だろ？　この世の中には、論理なんてもんで\n説明できないことは山ほどあるんだよ。
302 = "だろ？　この世の中には、論理なんてもんで\\n説明できないことは山ほどあるんだよ。"

# カズマ
# それにさ、なんにでも理由付けするなんて\n寂しいじゃないか。
288 = "それにさ、なんにでも理由付けするなんて\\n寂しいじゃないか。"

# カズマ
# 俺は、なんでもかんでも論理論理って言う\nそんなつまらない大人にはなりたくないな。
359 = "俺は、なんでもかんでも論理論理って言う\\nそんなつまらない大人にはなりたくないな。"

# めぐみん
# それで、スカートが短い論理的な理由は？
287 = "それで、スカートが短い論理的な理由は？"

# カズマ（Ｍ）
# display as カズマ
# （くっ、こいつ……）
445 = "（くっ、こいつ……）"

# めぐみん
# 無いのなら、今すぐ長く調整してください。
371 = "無いのなら、今すぐ長く調整してください。"

# カズマ
# 嫌だ。
364 = "嫌だ。"

# めぐみん
# は？
325 = "は？"

# カズマ
# だって俺、短いスカートの方が好きだもん。
299 = "だって俺、短いスカートの方が好きだもん。"

# めぐみん
# だもんって子供ですかあなたは！\nそれに個人の趣味に走るなんてどうかしてます！
300 = "だもんって子供ですかあなたは！\\nそれに個人の趣味に走るなんてどうかしてます！"

# カズマ
# だったら自分でどうにかすればいいだろ。\n俺は絶対に手伝わないからな！
298 = "だったら自分でどうにかすればいいだろ。\\n俺は絶対に手伝わないからな！"

# めぐみん
# アクア、スカートの丈を長くしてもらっても\nいいですか？
344 = "アクア、スカートの丈を長くしてもらっても\\nいいですか？"

# アクア
# ええ、かまわないわよ。
260 = "ええ、かまわないわよ。"

# カズマ
# 本当にいいのかなー。\nもしかしたらそれが理由でお金を稼げなくなるかも\nしれないのに。
369 = "本当にいいのかなー。\\nもしかしたらそれが理由でお金を稼げなくなるかも\\nしれないのに。"

# めぐみん
# なっ！？
313 = "なっ！？"

# カズマ
# はぁ、次の満月もパンツを盗んじまうのか。\n次は誰のかな。もしかしたらまためぐみんかも。
320 = "はぁ、次の満月もパンツを盗んじまうのか。\\n次は誰のかな。もしかしたらまためぐみんかも。"

# めぐみん
# うぐ、ぐぬぬ。
255 = "うぐ、ぐぬぬ。"

# カズマ
# それで、どうする？\nスカートを長くするのか？
286 = "それで、どうする？\\nスカートを長くするのか？"

# めぐみん
# わ、わかりましたよ。\nあんな惨めな思いは２度としたくありませんからね。
341 = "わ、わかりましたよ。\\nあんな惨めな思いは２度としたくありませんからね。"

# カズマ（Ｍ）
# display as カズマ
# （ふっ、余裕の勝利）
450 = "（ふっ、余裕の勝利）"

# カズマ
# よし、これで衣装は問題なしだな。
# 336 = "よし、これで衣装は問題なしだな。"

# カズマ
# 朝飯食ったら、さっそく特訓を開始するぞ。
368 = "朝飯食ったら、さっそく特訓を開始するぞ。"

[selections]
271 = "これくらい普通だからだ！"
435 = "見せるのがアイドルの仕事だ！"
# 294 = "そんなもんはない！"
