# st04c_05.txt.scn

[info]
0 = ""

[characters]
209 = "ダクネス"
206 = "カズマ"
204 = "アクア"
199 = "ゆんゆん"
197 = "めぐみん"
208 = "カズマ（Ｍ）"

[character_subs]
# 206 = "カズマ"

[script]
# lines: 35

# ダクネス
# カズマ、見ろっ！\n出口だっ！
207 = "カズマ、見ろっ！\\n出口だっ！"

# カズマ
# よしっ！\nやっぱりここが出口に通じてたんだな！
202 = "よしっ！\\nやっぱりここが出口に通じてたんだな！"

# カズマ
# みんな、あとちょっとだ！\n走れっ！
196 = "みんな、あとちょっとだ！\\n走れっ！"

# アクア
# 言われなくても走ってるわよ！
247 = "言われなくても走ってるわよ！"

# ゆんゆん
# ひゃあっ！？
194 = "ひゃあっ！？"

# カズマ
# ゆんゆん！？\n大丈夫か、いま行く！
200 = "ゆんゆん！？\\n大丈夫か、いま行く！"

# ゆんゆん
# ええっ！？\nこ、来ないでくださいっ！
186 = "ええっ！？\\nこ、来ないでくださいっ！"

# カズマ
# 俺の命の心配をしてくれるのは嬉しい。\nでも、ゆんゆんを置いてはいけない！
216 = "俺の命の心配をしてくれるのは嬉しい。\\nでも、ゆんゆんを置いてはいけない！"

# ゆんゆん
# ちが、違うんです！\n今はスカートが乱れて！
192 = "ちが、違うんです！\\n今はスカートが乱れて！"

# カズマ
# そんな心配してる場合か！？\n命がかかってるんだぞ！？
191 = "そんな心配してる場合か！？\\n命がかかってるんだぞ！？"

# ゆんゆん
# でも、でも！
193 = "でも、でも！"

# カズマ
# うおおっ！？　なんだこの揺れ！\nスカルドラゴンが暴れてんのか！
184 = "うおおっ！？　なんだこの揺れ！\\nスカルドラゴンが暴れてんのか！"

# ゆんゆん
# きゃああっ！？　めぐみん、助けて！
189 = "きゃああっ！？　めぐみん、助けて！"

# めぐみん
# ふっ、その願い聞き届けましたよ。
195 = "ふっ、その願い聞き届けましたよ。"

# カズマ
# おい、お前、何する気だ。
187 = "おい、お前、何する気だ。"

# めぐみん
# レッツ爆裂！
211 = "レッツ爆裂！"

# カズマ
# 今日一番の笑顔！
214 = "今日一番の笑顔！"

# ゆんゆん
# えええ、この状況で爆裂魔法って、どうしてよ！
185 = "えええ、この状況で爆裂魔法って、どうしてよ！"

# めぐみん
# 入り口は見えているんですから、\n洞窟が多少崩壊しても問題ないでしょう。
217 = "入り口は見えているんですから、\\n洞窟が多少崩壊しても問題ないでしょう。"

# カズマ
# 多少ですめばいいけどね！
219 = "多少ですめばいいけどね！"

# カズマ（Ｍ）
# display as カズマ
# （財宝を見つけられない可能性が高くなるけど、\n　あんな化け物を野放しにするよりはマシか）
251 = "（財宝を見つけられない可能性が高くなるけど、\\n　あんな化け物を野放しにするよりはマシか）"

# カズマ
# よし、めぐみん、やってやれ！
201 = "よし、めぐみん、やってやれ！"

# めぐみん
# 任されました！
215 = "任されました！"

# めぐみん
# 黒より黒く、闇より昏き漆黒に\n我が真紅の混淆を望みたもう。
249 = "黒より黒く、闇より昏き漆黒に\\n我が真紅の混淆を望みたもう。"

# めぐみん
# 覚醒の時、来たれり。\n無謬の境界に堕ちし理、\n無形の歪みとなりて、現出せよ！
246 = "覚醒の時、来たれり。\\n無謬の境界に堕ちし理、\\n無形の歪みとなりて、現出せよ！"

# めぐみん
# 踊れ、踊れ、踊れ――
248 = "踊れ、踊れ、踊れ――"

# めぐみん
# 我が力の奔流に望むは崩壊なり。\n並ぶ者なき崩壊なり。
222 = "我が力の奔流に望むは崩壊なり。\\n並ぶ者なき崩壊なり。"

# めぐみん
# 万象等しく灰燼に帰し、深淵より来たれ。
212 = "万象等しく灰燼に帰し、深淵より来たれ。"

# めぐみん
# エクスプローーーージョンッ！
205 = "エクスプローーーージョンッ！"

# カズマ（Ｍ）
# display as カズマ
# （うお！　相変わらずの威力！）
250 = "（うお！　相変わらずの威力！）"

# めぐみん
# ……あう。
183 = "……あう。"

# ゆんゆん
# か、カズマさんっ！\nめぐみんがっ！
188 = "か、カズマさんっ！\\nめぐみんがっ！"

# カズマ
# わかってる！\nいま回収するから！
203 = "わかってる！\\nいま回収するから！"

# めぐみん
# すみません、お手数をおかけします。
190 = "すみません、お手数をおかけします。"

# カズマ
# もう慣れっこだよ！
198 = "もう慣れっこだよ！"

