# st04a_04.txt.scn

[info]
0 = ""

[characters]
227 = "カズマ"
225 = "アクア"
228 = "カズマ（Ｍ）"
222 = "めぐみん"
229 = "ダクネス"

[character_subs]
# 227 = "カズマ"

[script]
# lines: 73

# カズマ
# はあ～。\nとんだ無駄足だったな。
214 = "はあ～。\\nとんだ無駄足だったな。"

# アクア
# 何よ。\n私が悪いってこと？
232 = "何よ。\\n私が悪いってこと？"

# カズマ
# そうは言ってねーだろ？\nとにかく、結界の件はこれで終わりにしようぜ。
200 = "そうは言ってねーだろ？\\nとにかく、結界の件はこれで終わりにしようぜ。"

# カズマ（Ｍ）
# display as カズマ
# （結局、本当に侵入者がいたのか\n　バニルに詳しい事を聞けずじまいだな。\n　まあ、素直に教えてくれたとも思えないけど）
293 = "（結局、本当に侵入者がいたのか\\n　バニルに詳しい事を聞けずじまいだな。\\n　まあ、素直に教えてくれたとも思えないけど）"

# めぐみん
# ところで、カズマ。\n朝はバタバタしていて\nはっきりとは確認できませんでしたが――
208 = "ところで、カズマ。\\n朝はバタバタしていて\\nはっきりとは確認できませんでしたが――"

# カズマ（Ｍ）
# display as カズマ
# （うっ、今度は俺が問い詰められる番か）
288 = "（うっ、今度は俺が問い詰められる番か）"

# めぐみん
# また例の物を盗んだのですよね？
220 = "また例の物を盗んだのですよね？"

# ダクネス
# しかも４枚も。
197 = "しかも４枚も。"

# カズマ
# え、ええ、その通りです。
191 = "え、ええ、その通りです。"

# めぐみん
# ……アクア、ダクネス。\nちょっといいですか？
182 = "……アクア、ダクネス。\\nちょっといいですか？"

# めぐみん
# これはもう、けじめを付けたほうが\nいいのではないですか？
194 = "これはもう、けじめを付けたほうが\\nいいのではないですか？"

# ダクネス
# うむ。\n４人もの犠牲者が出ているとなると\n見過ごせないぞ。
188 = "うむ。\\n４人もの犠牲者が出ているとなると\\n見過ごせないぞ。"

# アクア
# こうなってくると、私達まで\n見逃しているから共犯だって見られそうだし。
192 = "こうなってくると、私達まで\\n見逃しているから共犯だって見られそうだし。"

# めぐみん
# 爆裂魔法ならいつでもいけますよ！
249 = "爆裂魔法ならいつでもいけますよ！"

# カズマ
# 待て待て待て！\n物騒な相談はそこまでにしてくれ！
245 = "待て待て待て！\\n物騒な相談はそこまでにしてくれ！"

# カズマ
# な、なあ、前向きに金儲けの話をしようぜ。\nアクアも、さっきバニルに大見得切ったんだし\n稼がないとまずいだろ？
210 = "な、なあ、前向きに金儲けの話をしようぜ。\\nアクアも、さっきバニルに大見得切ったんだし\\n稼がないとまずいだろ？"

# アクア
# でも、今までやってきたことって\n全部失敗したじゃない。\n今更、上手くいく商売なんて思いつくの？
207 = "でも、今までやってきたことって\\n全部失敗したじゃない。\\n今更、上手くいく商売なんて思いつくの？"

# カズマ
# それをこれから考えるんだ。\nなんかないか？
202 = "それをこれから考えるんだ。\\nなんかないか？"

# アクア
# さっき言ったセキュリティサービスはどうかしら。
195 = "さっき言ったセキュリティサービスはどうかしら。"

# めぐみん
# 目の付け所は良いと思いますけど、\n多くの結界を維持し続けるのはアクアですよ。
250 = "目の付け所は良いと思いますけど、\\n多くの結界を維持し続けるのはアクアですよ。"

# アクア
# あー……それは面倒ね。\nやっぱり今の案は無しで。
184 = "あー……それは面倒ね。\\nやっぱり今の案は無しで。"

# カズマ（Ｍ）
# display as カズマ
# （はあ、そんなことだろうと思ったよ）
290 = "（はあ、そんなことだろうと思ったよ）"

# カズマ
# はい、他に一攫千金の案がある人は挙手。
215 = "はい、他に一攫千金の案がある人は挙手。"

# めぐみん
# …………。
180 = "…………。"

# ダクネス
# …………。
# 180 = "…………。"

# カズマ
# なんだ、何もないのか？
212 = "なんだ、何もないのか？"

# ダクネス
# 金を稼ぐ手段は思いつくが、\nさすがに一攫千金となるとな。
286 = "金を稼ぐ手段は思いつくが、\\nさすがに一攫千金となるとな。"

# めぐみん
# 地道に働いてコツコツと貯めていくのが\n一番でしょうね。
240 = "地道に働いてコツコツと貯めていくのが\\n一番でしょうね。"

# カズマ
# 別にそれでもいいけど、お前らパンツを盗られる\n恐怖に怯え続けるんだぞ。
234 = "別にそれでもいいけど、お前らパンツを盗られる\\n恐怖に怯え続けるんだぞ。"

# めぐみん
# うぐ、そうでした。
187 = "うぐ、そうでした。"

# アクア
# うーん、楽でぱーっと稼げる方法ねえ。
190 = "うーん、楽でぱーっと稼げる方法ねえ。"

# カズマ
# どうしてお前は、\n楽をすることが最初に来るんだよ。
209 = "どうしてお前は、\\n楽をすることが最初に来るんだよ。"

# ダクネス
# なあ、１度一攫千金から離れないか？
211 = "なあ、１度一攫千金から離れないか？"

# めぐみん
# では、コツコツ貯めるとなると、\nどんな方法がありますかね？
205 = "では、コツコツ貯めるとなると、\\nどんな方法がありますかね？"

# カズマ（Ｍ）
# display as カズマ
# （コツコツとか、そうだなぁ）
291 = "（コツコツとか、そうだなぁ）"

# カズマ
# アクアの芸で小銭を稼ぐのはどうだ？
226 = "アクアの芸で小銭を稼ぐのはどうだ？"

# アクア
# 嫌よ。
241 = "嫌よ。"

# カズマ
# 即答かよ！
236 = "即答かよ！"

# アクア
# 前にも言ったでしょ？\n芸は請われて見せるものではないわ。\n魂が命じる時、自ずから披露してしまうものなの。
235 = "前にも言ったでしょ？\\n芸は請われて見せるものではないわ。\\n魂が命じる時、自ずから披露してしまうものなの。"

# カズマ
# 建前はどうでもいいんだ。\nお前にはそれくらいしか能がないんだから、\n自分にできることをやれ、宴会芸の女神。
244 = "建前はどうでもいいんだ。\\nお前にはそれくらいしか能がないんだから、\\n自分にできることをやれ、宴会芸の女神。"

# アクア
# しっつれいね！　私は水の女神よ！\nだいたい、どうしてすぐに人に頼るのよ。
198 = "しっつれいね！　私は水の女神よ！\\nだいたい、どうしてすぐに人に頼るのよ。"

# アクア
# まずは、模範として\n自分が動くべきなんじゃないですかー。
219 = "まずは、模範として\\n自分が動くべきなんじゃないですかー。"

# カズマ（Ｍ）
# display as カズマ
# （くっそ、核心を突く正論をいいやがって！）
289 = "（くっそ、核心を突く正論をいいやがって！）"

# カズマ
# 肉体労働かな。\n土木工事とか左官とか。
285 = "肉体労働かな。\\n土木工事とか左官とか。"

# めぐみん
# ほう？\nこの紅魔族随一の魔法の使い手に\n肉体労働をしろと？
217 = "ほう？\\nこの紅魔族随一の魔法の使い手に\\n肉体労働をしろと？"

# めぐみん
# 愚かな。\n貴様は己が手にした力の使い方すらわからぬのか？
246 = "愚かな。\\n貴様は己が手にした力の使い方すらわからぬのか？"

# カズマ
# ……つまり？
181 = "……つまり？"

# めぐみん
# た、体力に自信がないので無理です。
203 = "た、体力に自信がないので無理です。"

# カズマ（Ｍ）
# display as カズマ
# （最初からそう言え、ロリッ子厨二病）
292 = "（最初からそう言え、ロリッ子厨二病）"

# カズマ
# みんなで出稼ぎとか？
221 = "みんなで出稼ぎとか？"

# ダクネス
# 出稼ぎか。\n悪くない意見だが――。
233 = "出稼ぎか。\\n悪くない意見だが――。"

# ダクネス
# この季節は稼げそうな街はないな。\n農作物の収穫時期ならば、\n臨時雇いも発生するんだが。
193 = "この季節は稼げそうな街はないな。\\n農作物の収穫時期ならば、\\n臨時雇いも発生するんだが。"

# カズマ
# あー、そういうもんなのか。
185 = "あー、そういうもんなのか。"

# めぐみん
# そういえば、カズマの故郷の仕事は\n他になにかないのですか？\n以前にやったメイドとかアイドル以外で。
199 = "そういえば、カズマの故郷の仕事は\\n他になにかないのですか？\\n以前にやったメイドとかアイドル以外で。"

# カズマ
# うーん、ないことはないけどなぁ。\n正直、上手くいく気がしないんだよ。
189 = "うーん、ないことはないけどなぁ。\\n正直、上手くいく気がしないんだよ。"

# ダクネス
# 確かに、結果は散々だったからな。\nもう一度と言われても、私も気は進まない。
281 = "確かに、結果は散々だったからな。\\nもう一度と言われても、私も気は進まない。"

# アクア
# 私もー。
283 = "私もー。"

# カズマ
# アイドルプロジェクトをご破算にしてくれた\nお前が言うな。
224 = "アイドルプロジェクトをご破算にしてくれた\\nお前が言うな。"

# アクア
# いつまで過去のことを言い続けるのよ。\n男なら未来を見て行動しなさいよね。
186 = "いつまで過去のことを言い続けるのよ。\\n男なら未来を見て行動しなさいよね。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、こいつ殴りてぇ）
287 = "（ああ、こいつ殴りてぇ）"

# ダクネス
# しかし、こうなると――
196 = "しかし、こうなると――"

# ダクネス
# 原点に戻って、\n討伐クエストで稼ぐしかないだろう！
237 = "原点に戻って、\\n討伐クエストで稼ぐしかないだろう！"

# ダクネス
# あえて屈強なモンスターどもに挑んでいくんだ！\nそ、そして、私は何度も打ち据えられ……！\nああっ！
183 = "あえて屈強なモンスターどもに挑んでいくんだ！\\nそ、そして、私は何度も打ち据えられ……！\\nああっ！"

# カズマ
# 手強いモンスターに挑むのはなしだが、\n確かに討伐クエストが確実かぁ。
247 = "手強いモンスターに挑むのはなしだが、\\n確かに討伐クエストが確実かぁ。"

# アクア
# ま、待って！\nカエルは嫌よ！　絶対に嫌！\nこれ以上、汚されてたまるもんですか！
218 = "ま、待って！\\nカエルは嫌よ！　絶対に嫌！\\nこれ以上、汚されてたまるもんですか！"

# めぐみん
# 私もカエルは……ちょっと。
282 = "私もカエルは……ちょっと。"

# カズマ
# なんだ、逃げるのか、\n紅魔族随一の魔法の使い手さんよ。
213 = "なんだ、逃げるのか、\\n紅魔族随一の魔法の使い手さんよ。"

# めぐみん
# ち、違いますよ！\n紅魔族は敵から逃げたりはしませんが、\n残念ながら魔法にも相性というものがあるのです！
204 = "ち、違いますよ！\\n紅魔族は敵から逃げたりはしませんが、\\n残念ながら魔法にも相性というものがあるのです！"

# カズマ
# はいはい、そういうことにしておいてやるよ。
216 = "はいはい、そういうことにしておいてやるよ。"

# アクア
# そもそも、ジャイアントトード討伐じゃ、\n大金を稼ぐための足がかりにもならないわ。
201 = "そもそも、ジャイアントトード討伐じゃ、\\n大金を稼ぐための足がかりにもならないわ。"

# カズマ
# やっぱり、危険を伴うクエストを受けるしかないか。
223 = "やっぱり、危険を伴うクエストを受けるしかないか。"

# ダクネス
# では、思い立ったが吉日だ！\nさっそく、ギルドの討伐クエストを\n確認しに行こう！
206 = "では、思い立ったが吉日だ！\\nさっそく、ギルドの討伐クエストを\\n確認しに行こう！"

# カズマ
# ダクネス、もう一度言うが、\n強いモンスターに挑むのはなしだぞ。\nちゃんと俺達の身の丈に合ったものを選ぶからな？
230 = "ダクネス、もう一度言うが、\\n強いモンスターに挑むのはなしだぞ。\\nちゃんと俺達の身の丈に合ったものを選ぶからな？"

[selections]
# 226 = "アクアの芸で小銭を稼ぐのはどうだ？"
284 = "肉体労働かな……"
# 221 = "みんなで出稼ぎとか？"
