# st04c_06.txt.scn

[info]
0 = ""

[characters]
287 = "カズマ"
277 = "めぐみん"
281 = "ゆんゆん"
300 = "ダクネス"
286 = "ウィズ"
285 = "アクア"
291 = "カズマ（Ｍ）"
293 = "クリス"
294 = "スカルドラゴン"

[character_subs]
# 287 = "カズマ"

[script]
# lines: 81

# カズマ
# はあ、はあ……。\nなんとか全員、ギリギリで脱出できたな。
265 = "はあ、はあ……。\\nなんとか全員、ギリギリで脱出できたな。"

# めぐみん
# はぁぁ、すっきりしました。\nもう思い残すことはありません。
264 = "はぁぁ、すっきりしました。\\nもう思い残すことはありません。"

# カズマ
# ゆんゆん、めぐみんを頼んでもいいか。
282 = "ゆんゆん、めぐみんを頼んでもいいか。"

# ゆんゆん
# はい、もちろんです！
266 = "はい、もちろんです！"

# ダクネス
# いやはや、見事に埋まったな。
236 = "いやはや、見事に埋まったな。"

# ウィズ
# ええ、ここに洞窟があったなんて\n思えないくらいですね。
238 = "ええ、ここに洞窟があったなんて\\n思えないくらいですね。"

# カズマ
# 逃げ遅れていたらと思うとぞっとするな。
349 = "逃げ遅れていたらと思うとぞっとするな。"

# ダクネス
# しかし、スカルドラゴンは\nどうなってしまったのだ？\nまさか生き埋めか？
247 = "しかし、スカルドラゴンは\\nどうなってしまったのだ？\\nまさか生き埋めか？"

# めぐみん
# ふっ、我が爆裂魔法に耐えられたとは思えん。\nその身は大地へと還ったに違いない。
268 = "ふっ、我が爆裂魔法に耐えられたとは思えん。\\nその身は大地へと還ったに違いない。"

# アクア
# 嘘でしょ、死んじゃったの？\nめぐみん！　もっと手加減してよ！
308 = "嘘でしょ、死んじゃったの？\\nめぐみん！　もっと手加減してよ！"

# カズマ（Ｍ）
# display as カズマ
# （爆裂魔法って手加減できるもんなのか？）
351 = "（爆裂魔法って手加減できるもんなのか？）"

# ウィズ
# あっ！\nみ、みなさん、空を！　空を見てください！
232 = "あっ！\\nみ、みなさん、空を！　空を見てください！"

# カズマ
# あ……！
224 = "あ……！"

# クリス
# スカルドラゴン！？
299 = "スカルドラゴン！？"

# カズマ
# ええええ！？　待て待て待て！\nあいつ、骨なのに飛べるのか！？
239 = "ええええ！？　待て待て待て！\\nあいつ、骨なのに飛べるのか！？"

# ダクネス
# あれはそういうものだ。\n我々の常識が通じる存在ではない。
234 = "あれはそういうものだ。\\n我々の常識が通じる存在ではない。"

# カズマ（Ｍ）
# display as カズマ
# （そうか、ここってファンタジー世界だもんな。\n　羽根じゃなくて、魔法かなにかで飛んでるのか）
350 = "（そうか、ここってファンタジー世界だもんな。\\n　羽根じゃなくて、魔法かなにかで飛んでるのか）"

# ゆんゆん
# ど、どうしますか？\n明らかに、こっちを見てますよね？
260 = "ど、どうしますか？\\n明らかに、こっちを見てますよね？"

# ダクネス
# ああ、これは敵と認識されていると思って\n間違いないだろう。
228 = "ああ、これは敵と認識されていると思って\\n間違いないだろう。"

# カズマ
# マジかよ！
302 = "マジかよ！"

# ダクネス
# カズマ、どうする？\nもう爆裂魔法も使えないが、戦うか？
289 = "カズマ、どうする？\\nもう爆裂魔法も使えないが、戦うか？"

# カズマ
# すぐ逃げよう！
248 = "すぐ逃げよう！"

# クリス
# そうだね、正直、この状況で\n勝ち目があるとは思えないよ。\n逃げるのが一番いいと思う。
249 = "そうだね、正直、この状況で\\n勝ち目があるとは思えないよ。\\n逃げるのが一番いいと思う。"

# アクア
# むしろ逃げるべきよ！\n街に帰って、さっさとあいつに\n懸賞金をかけてもらわないと！
276 = "むしろ逃げるべきよ！\\n街に帰って、さっさとあいつに\\n懸賞金をかけてもらわないと！"

# ダクネス
# しかし、すんなり逃がしてくれるとは思えない。\n私達がどんなに必死に走ったところで、\n簡単に追いつかれるだろう。
246 = "しかし、すんなり逃がしてくれるとは思えない。\\n私達がどんなに必死に走ったところで、\\n簡単に追いつかれるだろう。"

# アクア
# それは……そうだけど。
251 = "それは……そうだけど。"

# ダクネス
# 戦って死ぬか、逃げて死ぬか。\n冒険者ならば選ぶ道は１つだ。
314 = "戦って死ぬか、逃げて死ぬか。\\n冒険者ならば選ぶ道は１つだ。"

# ダクネス
# だが、心配するな。\n死ぬのは私だけでいい、\n皆が逃げる時間くらいなら稼いでみせよう。
253 = "だが、心配するな。\\n死ぬのは私だけでいい、\\n皆が逃げる時間くらいなら稼いでみせよう。"

# カズマ
# だ、ダメだろそんなの！\n俺は絶対にお前を見捨てねーぞ！
252 = "だ、ダメだろそんなの！\\n俺は絶対にお前を見捨てねーぞ！"

# ダクネス
# カズマ……。
288 = "カズマ……。"

# カズマ
# やってやるか。
280 = "やってやるか。"

# ダクネス
# ああ、ここで引くのは冒険者失格だろう。
227 = "ああ、ここで引くのは冒険者失格だろう。"

# クリス
# この状況、勝ち目があるとは思えないよ？\nそれでもやるの？
243 = "この状況、勝ち目があるとは思えないよ？\\nそれでもやるの？"

# ゆんゆん
# スカルドラゴンに対抗できる魔法もありませんし、\n逃げたほうがいいですよ！
297 = "スカルドラゴンに対抗できる魔法もありませんし、\\n逃げたほうがいいですよ！"

# カズマ
# まあ、俺も逃げられるもんなら逃げたい。\nでも全力で走っても、\nあっさり追いつかれて終わりだろ。
274 = "まあ、俺も逃げられるもんなら逃げたい。\\nでも全力で走っても、\\nあっさり追いつかれて終わりだろ。"

# カズマ
# だったら俺は、アクアの浄化魔法に賭けて\n戦ってみるほうを選ぶぜ。
254 = "だったら俺は、アクアの浄化魔法に賭けて\\n戦ってみるほうを選ぶぜ。"

# アクア
# え？　なんで？\nここはさっさと逃げて、\nあいつに懸賞金を賭けてもらいましょうよ。
240 = "え？　なんで？\\nここはさっさと逃げて、\\nあいつに懸賞金を賭けてもらいましょうよ。"

# カズマ
# お前な！\n俺の話、聞いてなかったのか！？
241 = "お前な！\\n俺の話、聞いてなかったのか！？"

# カズマ
# ほっとくわけにはいかねーよな。
271 = "ほっとくわけにはいかねーよな。"

# ダクネス
# カズマならそう言うと思ったよ。
290 = "カズマならそう言うと思ったよ。"

# ダクネス
# このドラゴンを放置すれば、いずれは\n街を襲うなどの被害が出るかもしれない。
242 = "このドラゴンを放置すれば、いずれは\\n街を襲うなどの被害が出るかもしれない。"

# カズマ
# だよな。\nそれを知っての上で逃げるってのは、\nさすがに格好悪すぎるよな。
255 = "だよな。\\nそれを知っての上で逃げるってのは、\\nさすがに格好悪すぎるよな。"

# クリス
# 心意気は立派だけどさ、どう戦うつもりなの？\n正直、勝ち目があるとは思えないよ？
313 = "心意気は立派だけどさ、どう戦うつもりなの？\\n正直、勝ち目があるとは思えないよ？"

# ゆんゆん
# 効くとしたら、\nアクアさんの浄化魔法だけですよね？
305 = "効くとしたら、\\nアクアさんの浄化魔法だけですよね？"

# ゆんゆん
# でも、飛んでいる相手に当てるのは\n難しいんじゃないでしょうか？\n避けられちゃいそうですし。
259 = "でも、飛んでいる相手に当てるのは\\n難しいんじゃないでしょうか？\\n避けられちゃいそうですし。"

# カズマ
# そこは根性で当てろ。\nいいな、アクア。
250 = "そこは根性で当てろ。\\nいいな、アクア。"

# アクア
# 嫌よ、せっかく生きてたんだから\n街に帰って懸賞金をかけてもらってからに\nするわ。
309 = "嫌よ、せっかく生きてたんだから\\n街に帰って懸賞金をかけてもらってからに\\nするわ。"

# カズマ
# この状況でまだ言うのか、お前は！
244 = "この状況でまだ言うのか、お前は！"

# スカルドラゴン
# …………。
222 = "…………。"

# ウィズ
# あら？\nなんだか、ドラゴンの様子が……。
233 = "あら？\\nなんだか、ドラゴンの様子が……。"

# ダクネス
# なんだ？\n急に向きを変えて……。
262 = "なんだ？\\n急に向きを変えて……。"

# アクア
# ああっ！？\nちょっと待ちなさいよ、どこに行く気！？
230 = "ああっ！？\\nちょっと待ちなさいよ、どこに行く気！？"

# ウィズ
# ……行ってしまいましたね。
223 = "……行ってしまいましたね。"

# カズマ
# どうなってんだ？\nあいつ、なんで俺達に\n襲いかかってこなかったんだ？
261 = "どうなってんだ？\\nあいつ、なんで俺達に\\n襲いかかってこなかったんだ？"

# クリス
# わからない。\n気まぐれ……なのかな？
284 = "わからない。\\n気まぐれ……なのかな？"

# めぐみん
# ふふふふふ。\n恐らく、我の強大な魔力を畏れて\n逃げ出したのであろう。
269 = "ふふふふふ。\\n恐らく、我の強大な魔力を畏れて\\n逃げ出したのであろう。"

# カズマ
# いや、それはない。
235 = "いや、それはない。"

# アクア
# もうっ！\nせっかく懸賞金を手に入れるチャンスだったのに！\n報酬とあわせて、一生遊んで暮らせるお金が……。
278 = "もうっ！\\nせっかく懸賞金を手に入れるチャンスだったのに！\\n報酬とあわせて、一生遊んで暮らせるお金が……。"

# アクア
# って、財宝！　財宝はどうなったの！？\n財宝を見つけなきゃ、報酬が跳ね上がらない\nじゃない！
256 = "って、財宝！　財宝はどうなったの！？\\n財宝を見つけなきゃ、報酬が跳ね上がらない\\nじゃない！"

# カズマ
# あ、そういえばそうだった。\n俺達、洞窟の調査に来たんだった。
225 = "あ、そういえばそうだった。\\n俺達、洞窟の調査に来たんだった。"

# ゆんゆん
# スカルドラゴンが現れたので、\nすっかり忘れてましたね。
295 = "スカルドラゴンが現れたので、\\nすっかり忘れてましたね。"

# クリス
# でも、これじゃあねぇ。\n洞窟は埋まっちゃったし、\nもう調査や財宝どころじゃないよ。
258 = "でも、これじゃあねぇ。\\n洞窟は埋まっちゃったし、\\nもう調査や財宝どころじゃないよ。"

# アクア
# ま、まだいけるわっ！\nみんなで頑張って掘り起こせば！　ね！
272 = "ま、まだいけるわっ！\\nみんなで頑張って掘り起こせば！　ね！"

# ダクネス
# 待て、アクア！\n危ないぞ、近づくんじゃない！
312 = "待て、アクア！\\n危ないぞ、近づくんじゃない！"

# カズマ
# ダクネス、いいよ。\nもうあいつは放っておこう。
301 = "ダクネス、いいよ。\\nもうあいつは放っておこう。"

# カズマ
# にしても、俺もさすがにショックだなぁ。\nこれだけの目にあって、結局、収入ゼロかよ。
263 = "にしても、俺もさすがにショックだなぁ。\\nこれだけの目にあって、結局、収入ゼロかよ。"

# クリス
# スカルドラゴンと\n正面きって戦わなくてすんだことが、\n唯一の救いだね。
296 = "スカルドラゴンと\\n正面きって戦わなくてすんだことが、\\n唯一の救いだね。"

# めぐみん
# ああ、そうです。\n気になっていたのですが――
229 = "ああ、そうです。\\n気になっていたのですが――"

# めぐみん
# スカルドラゴンの側を通る時、\nカズマの指輪、光りましたよね？\nどうして光ったんですか？
298 = "スカルドラゴンの側を通る時、\\nカズマの指輪、光りましたよね？\\nどうして光ったんですか？"

# ゆんゆん
# あ、それ、私も気になっていました。\nもしかしてスカルドラゴンに反応したんですか？
226 = "あ、それ、私も気になっていました。\\nもしかしてスカルドラゴンに反応したんですか？"

# カズマ
# さあ、わからない。
245 = "さあ、わからない。"

# クリス
# まあ、そうだよね。\nキミだってうっかり身につけちゃっただけで、\n持ち主じゃないんだし。
273 = "まあ、そうだよね。\\nキミだってうっかり身につけちゃっただけで、\\n持ち主じゃないんだし。"

# ウィズ
# ですけど、あんな反応を見せたのには\nなにか理由があるはずです。
257 = "ですけど、あんな反応を見せたのには\\nなにか理由があるはずです。"

# カズマ
# 理由ねえ……。
316 = "理由ねえ……。"

# アクア
# ひゃあああああっ！
267 = "ひゃあああああっ！"

# カズマ
# うおっ！？\nな、なんだ、どうしたアクア！？
237 = "うおっ！？\\nな、なんだ、どうしたアクア！？"

# クリス
# まさか、モンスター！？
275 = "まさか、モンスター！？"

# アクア
# 助けてぇ！\nガレキに挟まって動けなくなったぁ！
304 = "助けてぇ！\\nガレキに挟まって動けなくなったぁ！"

# カズマ
# ああもう、なにやってんだお前はっ！！\nこっちが真剣に考えてる時に！
231 = "ああもう、なにやってんだお前はっ！！\\nこっちが真剣に考えてる時に！"

# アクア
# カーズーマーさーん！\n助けてー！　助けてよぉー！
292 = "カーズーマーさーん！\\n助けてー！　助けてよぉー！"

# カズマ
# わかったから叫ぶな！\nいま行くから待ってろ！！
283 = "わかったから叫ぶな！\\nいま行くから待ってろ！！"

[selections]
# 248 = "すぐ逃げよう！"
279 = "やってやるか"
270 = "ほっとくわけにはいかねーよな"
