# st04c_02.txt.scn

[info]
0 = ""

[characters]
337 = "カズマ（Ｍ）"
338 = "クリス"
335 = "カズマ"
324 = "ゆんゆん"
320 = "めぐみん"
341 = "ダクネス"
331 = "アクア"
332 = "ウィズ"

[character_subs]
# 335 = "カズマ"

[script]
# lines: 97

# カズマ（Ｍ）
# display as カズマ
# （それから俺達は、来た道を戻りながら\n　隠し通路がないか丁寧に調べていった）
412 = "（それから俺達は、来た道を戻りながら\\n　隠し通路がないか丁寧に調べていった）"

# カズマ（Ｍ）
# display as カズマ
# （だけど――）
413 = "（だけど――）"

# クリス
# ダメだね、ここにも何もないよ。\nキミはどう？
342 = "ダメだね、ここにも何もないよ。\\nキミはどう？"

# カズマ
# いや、俺もダメだ。
273 = "いや、俺もダメだ。"

# クリス
# 探索スキルでも見つからないってことは、\nやっぱり隠された出口っていうのは\nないのかもね。
359 = "探索スキルでも見つからないってことは、\\nやっぱり隠された出口っていうのは\\nないのかもね。"

# カズマ（Ｍ）
# display as カズマ
# （盗賊が根城にしてたってくらいだから、\n　隠し通路とかを期待してたんだけど）
419 = "（盗賊が根城にしてたってくらいだから、\\n　隠し通路とかを期待してたんだけど）"

# ゆんゆん
# もう、いけるところは探し尽くしましたよね。
321 = "もう、いけるところは探し尽くしましたよね。"

# めぐみん
# ということは、\n閉じ込められた……ということですか？
304 = "ということは、\\n閉じ込められた……ということですか？"

# クリス
# ううん、閉じ込められてはいないよ。\nカズマやゆんゆんには説明したけど、\nここには空気の流れがあるから。
278 = "ううん、閉じ込められてはいないよ。\\nカズマやゆんゆんには説明したけど、\\nここには空気の流れがあるから。"

# ダクネス
# しかし、あるのが\nほんのわずかな隙間なのかもしれないぞ。\nそれこそ、空気しか出入りできないような。
289 = "しかし、あるのが\\nほんのわずかな隙間なのかもしれないぞ。\\nそれこそ、空気しか出入りできないような。"

# クリス
# それは否定できないけど……。
297 = "それは否定できないけど……。"

# アクア
# じょ、冗談じゃないわ！\nこんなところで女神が死んだなんてことに\nなったら、私の可愛い教徒達に顔向けできない！
291 = "じょ、冗談じゃないわ！\\nこんなところで女神が死んだなんてことに\\nなったら、私の可愛い教徒達に顔向けできない！"

# カズマ（Ｍ）
# display as カズマ
# （おお？　アクアにしてはまともなことを言ったな。\n　てっきり、財宝の報酬を手に入れずに死ねないとか\n　言いだすかと思ったぜ）
411 = "（おお？　アクアにしてはまともなことを言ったな。\\n　てっきり、財宝の報酬を手に入れずに死ねないとか\\n　言いだすかと思ったぜ）"

# アクア
# カズマ！　なんとかしなさいよ！\n一攫千金のチャンスなのよ！？\nニートのあんたが私に楽させるチャンスなのよ！
336 = "カズマ！　なんとかしなさいよ！\\n一攫千金のチャンスなのよ！？\\nニートのあんたが私に楽させるチャンスなのよ！"

# カズマ
# ですよね！！
301 = "ですよね！！"

# アクア
# は？\nなによ、その反応。
312 = "は？\\nなによ、その反応。"

# カズマ
# いや気にするな、なんでもない。
276 = "いや気にするな、なんでもない。"

# めぐみん
# やれやれ、仕方ありません。\nこうなったら最後の手段です。
323 = "やれやれ、仕方ありません。\\nこうなったら最後の手段です。"

# アクア
# 最後の手段って？
360 = "最後の手段って？"

# めぐみん
# もちろん、爆裂魔法です！\n爆裂魔法で壁を壊して外に出ましょう、\nそれしかありませんよ！
322 = "もちろん、爆裂魔法です！\\n爆裂魔法で壁を壊して外に出ましょう、\\nそれしかありませんよ！"

# カズマ
# ま、待て！\n待つんだ、めぐみん！
317 = "ま、待て！\\n待つんだ、めぐみん！"

# カズマ
# 俺達を生き埋めにする気か？
347 = "俺達を生き埋めにする気か？"

# めぐみん
# え？　なぜですか？\n壁を壊すだけですよ？
282 = "え？　なぜですか？\\n壁を壊すだけですよ？"

# カズマ
# お前には想像力ってものがないのか？\n爆裂魔法をぶっ放したら、\n壊れるのは壁どころじゃないだろ。
283 = "お前には想像力ってものがないのか？\\n爆裂魔法をぶっ放したら、\\n壊れるのは壁どころじゃないだろ。"

# めぐみん
# ……そこに気がつくとは。\nさすが、我が認めた男よ。
264 = "……そこに気がつくとは。\\nさすが、我が認めた男よ。"

# カズマ
# いや、普通、気がつくから。
274 = "いや、普通、気がつくから。"

# めぐみん
# では、こうしましょう。\n壁を壊した瞬間、天井が崩れ始める前に\n逃げ出すのです！
302 = "では、こうしましょう。\\n壁を壊した瞬間、天井が崩れ始める前に\\n逃げ出すのです！"

# カズマ
# できるかっ！
300 = "できるかっ！"

# カズマ
# 力の使い方を誤るな……。
350 = "力の使い方を誤るな……。"

# めぐみん
# はっ！？\nその言い方、ついにカズマも紅魔族というものが\nわかってきたようですね！
311 = "はっ！？\\nその言い方、ついにカズマも紅魔族というものが\\nわかってきたようですね！"

# カズマ
# まあな。\n伊達に、紅魔族随一の魔法の使い手と\n行動を共にしてないさ。
319 = "まあな。\\n伊達に、紅魔族随一の魔法の使い手と\\n行動を共にしてないさ。"

# めぐみん
# 力の使い方か……。\n確かに、我が爆裂魔法は\nかの呪われし竜にこそ振るわれるべきか。
348 = "力の使い方か……。\\n確かに、我が爆裂魔法は\\nかの呪われし竜にこそ振るわれるべきか。"

# カズマ
# その通りだ！\nこんな壁を壊すためものではないはずだ！
296 = "その通りだ！\\nこんな壁を壊すためものではないはずだ！"

# めぐみん
# ふっ！\n今回ばかりはカズマに教えられたようですね。
315 = "ふっ！\\n今回ばかりはカズマに教えられたようですね。"

# カズマ（Ｍ）
# display as カズマ
# （よしっ！\n　なんとかごまかせたな！）
415 = "（よしっ！\\n　なんとかごまかせたな！）"

# カズマ
# お前は切り札だ！\nここで魔法を無駄撃ちすんじゃねー！
286 = "お前は切り札だ！\\nここで魔法を無駄撃ちすんじゃねー！"

# めぐみん
# ということは、カズマは\nスカルドラゴンと戦うつもりなんですね！？
306 = "ということは、カズマは\\nスカルドラゴンと戦うつもりなんですね！？"

# カズマ
# いや、なるべく戦いたくないけどさ、\nいざって時はやっぱり爆裂魔法は頼りになるし。
272 = "いや、なるべく戦いたくないけどさ、\\nいざって時はやっぱり爆裂魔法は頼りになるし。"

# めぐみん
# 任せてください！\n我らの前に立ちふさがる者は、\nすべて灰にしてくれますよ！
346 = "任せてください！\\n我らの前に立ちふさがる者は、\\nすべて灰にしてくれますよ！"

# ゆんゆん
# あの、変にたきつけると\n本当に洞窟の中で魔法を使いかねませんよ？
269 = "あの、変にたきつけると\\n本当に洞窟の中で魔法を使いかねませんよ？"

# アクア
# 大丈夫よ。\n私、タダ働きは絶対にしないから。\nその時は女神の全力をもって止めるわ。
355 = "大丈夫よ。\\n私、タダ働きは絶対にしないから。\\nその時は女神の全力をもって止めるわ。"

# カズマ
# そういう時だけ全力出すのか、お前。
294 = "そういう時だけ全力出すのか、お前。"

# ウィズ
# ……あっ！\nみなさん、モンスターが！
262 = "……あっ！\\nみなさん、モンスターが！"

# カズマ
# げげっ！？\nさっきまでいなかったのに、いつの間に！
287 = "げげっ！？\\nさっきまでいなかったのに、いつの間に！"

# クリス
# うわ、なにこれ！\nアンデッドモンスターの群れ！？
279 = "うわ、なにこれ！\\nアンデッドモンスターの群れ！？"

# ゆんゆん
# 気持ち悪いです……！
361 = "気持ち悪いです……！"

# カズマ（Ｍ）
# display as カズマ
# （アンデッド？\n　ってことは……）
417 = "（アンデッド？\\n　ってことは……）"

# アクア
# ……なんで私を見るのよ。
266 = "……なんで私を見るのよ。"

# カズマ
# 理由の説明が必要か？
364 = "理由の説明が必要か？"

# アクア
# わ、私だって好きで引きよせてるんじゃないわ！\n女神の神聖さが罪なのよ！
328 = "わ、私だって好きで引きよせてるんじゃないわ！\\n女神の神聖さが罪なのよ！"

# カズマ
# （まったくこいつはトラブルの種ばっかり\n　まきやがって）
414 = "（まったくこいつはトラブルの種ばっかり\\n　まきやがって）"

# カズマ
# （ん……ちょっと待てよ……）
416 = "（ん……ちょっと待てよ……）"

# カズマ
# （スカルドラゴンもアンデッド……ということは、\n　まさか……）
418 = "（スカルドラゴンもアンデッド……ということは、\\n　まさか……）"

# アクア
# な、何よ、恐い顔して睨まないでよ。
308 = "な、何よ、恐い顔して睨まないでよ。"

# カズマ
# あのドラゴンを引きよせたのもお前かっ！\n本当に！　はた迷惑な女神だな！！
270 = "あのドラゴンを引きよせたのもお前かっ！\\n本当に！　はた迷惑な女神だな！！"

# アクア
# ええ！？　私のせい！！
281 = "ええ！？　私のせい！！"

# クリス
# しゃべってる暇はないよ！\nアンデッドがアクアさんに向かってる！
290 = "しゃべってる暇はないよ！\\nアンデッドがアクアさんに向かってる！"

# アクア
# ひいいっ！？\nちょ、ちょっと、来ないでぇぇぇ！
314 = "ひいいっ！？\\nちょ、ちょっと、来ないでぇぇぇ！"

# カズマ（Ｍ）
# display as カズマ
# （うわー……。\n　アンデッドと女神の追いかけっこが始まったぞ）
410 = "（うわー……。\\n　アンデッドと女神の追いかけっこが始まったぞ）"

# ゆんゆん
# 助けなくていいんですか！？\nあのままじゃ、アクアさんが！
351 = "助けなくていいんですか！？\\nあのままじゃ、アクアさんが！"

# カズマ
# 大丈夫大丈夫、しばらく反省させよう。
356 = "大丈夫大丈夫、しばらく反省させよう。"

# アクア
# いいいいいいやあああああああ！！
271 = "いいいいいいやあああああああ！！"

# ダクネス
# ……ちょっと楽しそうだな。
265 = "……ちょっと楽しそうだな。"

# クリス
# あたしには、ちっともそうは見えないんだけど？
268 = "あたしには、ちっともそうは見えないんだけど？"

# アクア
# うわあああああああん！\nカズマさん、カズマさーん！　助けてよー！
280 = "うわあああああああん！\\nカズマさん、カズマさーん！　助けてよー！"

# ゆんゆん
# ああ言ってますし、助けましょう！
267 = "ああ言ってますし、助けましょう！"

# クリス
# まあ、仕方ないね。
318 = "まあ、仕方ないね。"

# めぐみん
# では、私も。
303 = "では、私も。"

# カズマ
# お前は何もするな。
284 = "お前は何もするな。"

# カズマ
# ゆんゆん、さっきの魔法で\nモンスターを斬りまくってくれ。\nあいつらはアクアに夢中だから簡単に当たるだろ。
325 = "ゆんゆん、さっきの魔法で\\nモンスターを斬りまくってくれ。\\nあいつらはアクアに夢中だから簡単に当たるだろ。"

# ゆんゆん
# はいっ！
310 = "はいっ！"

# カズマ
# ウィズ、ゆんゆんの支援をしてくれるか？
333 = "ウィズ、ゆんゆんの支援をしてくれるか？"

# ウィズ
# わかりました。
330 = "わかりました。"

# カズマ
# クリス、俺と一緒に、\nゆんゆんの魔法にビビって\n足を止めた奴を仕留めてくれ。
339 = "クリス、俺と一緒に、\\nゆんゆんの魔法にビビって\\n足を止めた奴を仕留めてくれ。"

# クリス
# オッケー。
334 = "オッケー。"

# ダクネス
# わ、私はどうすればいい？\nなんなら、アンデッドの群れに突っ込んで\nアクアの盾になるぞ！
329 = "わ、私はどうすればいい？\\nなんなら、アンデッドの群れに突っ込んで\\nアクアの盾になるぞ！"

# カズマ
# よし、みんないくぞ！
327 = "よし、みんないくぞ！"

# ダクネス
# 無っ視！
363 = "無っ視！"

# アクア
# ひいいいいいい！\nカズマさーん！　早くしてーー！
313 = "ひいいいいいい！\\nカズマさーん！　早くしてーー！"

# ゆんゆん
# ライト・オブ・セイバー！
344 = "ライト・オブ・セイバー！"

# カズマ
# ナイス、ゆんゆん！\nいまので最後だな！
343 = "ナイス、ゆんゆん！\\nいまので最後だな！"

# ダクネス
# 大丈夫か、アクア。
354 = "大丈夫か、アクア。"

# アクア
# はあ、はあ……。\nもう嫌……早く帰りたい……。
309 = "はあ、はあ……。\\nもう嫌……早く帰りたい……。"

# カズマ
# ほら、アクア。\n疲れてんのはわかるが、ここで座り込んでると\nまたアンデッドが寄ってくるぞ。
316 = "ほら、アクア。\\n疲れてんのはわかるが、ここで座り込んでると\\nまたアンデッドが寄ってくるぞ。"

# アクア
# うう……。\nでも、どうするのよ。\n出口なんてないんでしょ？
277 = "うう……。\\nでも、どうするのよ。\\n出口なんてないんでしょ？"

# クリス
# そうなんだよねぇ。\n調べられるところは調べちゃったし。
295 = "そうなんだよねぇ。\\n調べられるところは調べちゃったし。"

# ウィズ
# ということは、やはりスカルドラゴンが眠る場所に\n行くしかありませんね。
305 = "ということは、やはりスカルドラゴンが眠る場所に\\n行くしかありませんね。"

# カズマ
# いやまあそうなんだけどさ。\nどうやってあのデカ物が眠ってる場所を\n調べるっていうんだよ。
275 = "いやまあそうなんだけどさ。\\nどうやってあのデカ物が眠ってる場所を\\n調べるっていうんだよ。"

# ウィズ
# そ、それは……。
292 = "そ、それは……。"

# ダクネス
# だからといって、ここで\nぐずぐずしているわけにもいかないぞ。
299 = "だからといって、ここで\\nぐずぐずしているわけにもいかないぞ。"

# クリス
# このままじゃ、下手したら\nこっちがアンデッドモンスターの\n仲間入りをしちゃう。
288 = "このままじゃ、下手したら\\nこっちがアンデッドモンスターの\\n仲間入りをしちゃう。"

# めぐみん
# となると、覚悟を決めて\nスカルドラゴンのいる場所を\n調べるしかないですね。
307 = "となると、覚悟を決めて\\nスカルドラゴンのいる場所を\\n調べるしかないですね。"

# カズマ
# スカルドラゴンに殺されるか、\nこの洞窟で朽ち果てるか。\n究極の２択だな。
340 = "スカルドラゴンに殺されるか、\\nこの洞窟で朽ち果てるか。\\n究極の２択だな。"

# ウィズ
# そんな。\n死ぬと決まったわけではありませんし。
298 = "そんな。\\n死ぬと決まったわけではありませんし。"

# アクア
# ……あんたが言うと、\n色々と含みがあるように聞こえるんですけど。
263 = "……あんたが言うと、\\n色々と含みがあるように聞こえるんですけど。"

# ウィズ
# そ、そんなつもりはありませんよ。
293 = "そ、そんなつもりはありませんよ。"

# カズマ
# よし、ひとまず\nスカルドラゴンのところに行ってみるぞ。\nまずは、そこに出口があるのかを確かめよう。
326 = "よし、ひとまず\\nスカルドラゴンのところに行ってみるぞ。\\nまずは、そこに出口があるのかを確かめよう。"

[selections]
# 347 = "俺達を生き埋めにする気か？"
349 = "力の使い方を誤るな……"
285 = "お前は切り札だ"
