# st04a_05.txt.scn

[info]
0 = ""

[characters]
281 = "カズマ"
274 = "めぐみん"
290 = "ルナ"
283 = "カズマ（Ｍ）"
280 = "アクア"
288 = "ダクネス"

[character_subs]
371 = "？？？"
# 281 = "カズマ"

[script]
# lines: 104

# カズマ
# じゃ、さっそく\nクエストの張り紙をチェックするか。
240 = "じゃ、さっそく\\nクエストの張り紙をチェックするか。"

# めぐみん
# ふふ、任せるがいい。\n我が力を振るうにふさわしいクエストを\n選び出してやろう。
271 = "ふふ、任せるがいい。\\n我が力を振るうにふさわしいクエストを\\n選び出してやろう。"

# ルナ
# display as ？？？
# あっ！？
217 = "あっ！？"

# カズマ
# ……ん？
211 = "……ん？"

# カズマ（Ｍ）
# display as カズマ
# （受け付けのお姉さん？\n　なんでこっちをじっと見てるんだ？）
369 = "（受け付けのお姉さん？\\n　なんでこっちをじっと見てるんだ？）"

# アクア
# どうしたのよ、カズマ。
265 = "どうしたのよ、カズマ。"

# カズマ
# 受け付けのお姉さんが\nこっちを見てるんだけど……\nお前、なんかやったのか？
295 = "受け付けのお姉さんが\\nこっちを見てるんだけど……\\nお前、なんかやったのか？"

# アクア
# やってないわよ。\nカズマこそ、なにやったの？
277 = "やってないわよ。\\nカズマこそ、なにやったの？"

# カズマ
# 俺も何もしてねーよ。
294 = "俺も何もしてねーよ。"

# ルナ
# あ、あの？\nサトウカズマさん？
212 = "あ、あの？\\nサトウカズマさん？"

# カズマ
# あ、はいっ！\nなんですか？　俺、なにかしました？
213 = "あ、はいっ！\\nなんですか？　俺、なにかしました？"

# ルナ
# …………。
210 = "…………。"

# ルナ
# い、いえ、別に、\nそういうわけではないのですが。
218 = "い、いえ、別に、\\nそういうわけではないのですが。"

# カズマ（Ｍ）
# display as カズマ
# （じゃ、最初の間はなんなんだよ！\n　それに、用もないのに声をかけてくれるほど\n　仲が良いわけでもないし）
367 = "（じゃ、最初の間はなんなんだよ！\\n　それに、用もないのに声をかけてくれるほど\\n　仲が良いわけでもないし）"

# ルナ
# 今日は……どういったご用件ですか？\nよろしければ伺いますよ？
293 = "今日は……どういったご用件ですか？\\nよろしければ伺いますよ？"

# カズマ
# ああ、ギルドに用事ってわけじゃないんです。\nなにかいいクエストがないか\n見に来ただけなんで。
215 = "ああ、ギルドに用事ってわけじゃないんです。\\nなにかいいクエストがないか\\n見に来ただけなんで。"

# ルナ
# クエストを……ですか。
287 = "クエストを……ですか。"

# めぐみん
# カズマー。\nダメです、私達にもできてお金になりそうな\nクエストなんてありませんよ。
282 = "カズマー。\\nダメです、私達にもできてお金になりそうな\\nクエストなんてありませんよ。"

# ダクネス
# いや、はぐれリザード達を\n退治するクエストは行けると思うぞ！\n盾役は私に任せて欲しい！
220 = "いや、はぐれリザード達を\\n退治するクエストは行けると思うぞ！\\n盾役は私に任せて欲しい！"

# カズマ
# おい、ダクネス。\n俺がさっき言ったことをもう忘れたのか？
230 = "おい、ダクネス。\\n俺がさっき言ったことをもう忘れたのか？"

# ルナ
# ああ、なるほど。\n呪い解除ために、高額のクエストを\nお探しなんですね。
214 = "ああ、なるほど。\\n呪い解除ために、高額のクエストを\\nお探しなんですね。"

# めぐみん
# そうです。\n一刻も早くカズマから指輪を外さないと、\n今後、犠牲者が増える一方なので。
247 = "そうです。\\n一刻も早くカズマから指輪を外さないと、\\n今後、犠牲者が増える一方なので。"

# ルナ
# 犠牲者が……増えるとは？
312 = "犠牲者が……増えるとは？"

# ダクネス
# 実はな、カズマが盗む……\nその、例の物の枚数が月ごとに増えているんだ。
300 = "実はな、カズマが盗む……\\nその、例の物の枚数が月ごとに増えているんだ。"

# ルナ
# ええっ！？
226 = "ええっ！？"

# カズマ
# 誤解しないでくださいよ！？\n指輪の呪いがどんどん強まってるらしくて、\n俺にはどうすることもできないんです！
362 = "誤解しないでくださいよ！？\\n指輪の呪いがどんどん強まってるらしくて、\\n俺にはどうすることもできないんです！"

# ルナ
# %fsyogen;な、なるほど。\nだから……なんですね。
17 = "%fsyogen;な、なるほど。\\nだから……なんですね。"

# カズマ
# え？　だからって？
229 = "え？　だからって？"

# ルナ
# な、なんでもありません！
266 = "な、なんでもありません！"

# カズマ（Ｍ）
# display as カズマ
# （んん～？　なんだこのお姉さんの態度は。\n　それに、だから？）
368 = "（んん～？　なんだこのお姉さんの態度は。\\n　それに、だから？）"

# カズマ（Ｍ）
# display as カズマ
# （気になるな。\n　証言として押さえておくか）
370 = "（気になるな。\\n　証言として押さえておくか）"

# ルナ
# それよりも、そのような事情でしたら\nギルドとしてもなにかお手伝いをすべきですね。
256 = "それよりも、そのような事情でしたら\\nギルドとしてもなにかお手伝いをすべきですね。"

# カズマ
# 本当ですか！？\nすっげー助かります！
309 = "本当ですか！？\\nすっげー助かります！"

# ルナ
# ここではなんですので、あちらにどうぞ。
234 = "ここではなんですので、あちらにどうぞ。"

# ルナ
# お話の前にひとつ、みなさんにお約束して\n頂きたいこと事があるのですが、\nよろしいでしょうか？
232 = "お話の前にひとつ、みなさんにお約束して\\n頂きたいこと事があるのですが、\\nよろしいでしょうか？"

# ダクネス
# 約束？　なんだ？
361 = "約束？　なんだ？"

# ルナ
# まず、ご存じと思いますが、\n冒険者ギルドはすべての冒険者のための組織。
273 = "まず、ご存じと思いますが、\\n冒険者ギルドはすべての冒険者のための組織。"

# ルナ
# ギルドに登録されている方々には\n平等に接することが正しい姿勢です。
285 = "ギルドに登録されている方々には\\n平等に接することが正しい姿勢です。"

# カズマ
# はあ……。
268 = "はあ……。"

# ルナ
# つまり、特定のパーティーを支援するのは\nギルドとしては問題のあることなんです。
260 = "つまり、特定のパーティーを支援するのは\\nギルドとしては問題のあることなんです。"

# ルナ
# ですから、これからお話しすることは\n他の冒険者の方々には\nくれぐれも内密にお願いします。
262 = "ですから、これからお話しすることは\\n他の冒険者の方々には\\nくれぐれも内密にお願いします。"

# カズマ（Ｍ）
# display as カズマ
# （おいおい、やけに重い感じだぞ？\n　話を聞いて大丈夫か？）
366 = "（おいおい、やけに重い感じだぞ？\\n　話を聞いて大丈夫か？）"

# アクア
# つまり、他の冒険者にばれなければいいのよね？
259 = "つまり、他の冒険者にばれなければいいのよね？"

# ルナ
# え、ええ、まあ、そうなのですが。\n……だ、大丈夫ですよね？
224 = "え、ええ、まあ、そうなのですが。\\n……だ、大丈夫ですよね？"

# カズマ（Ｍ）
# display as カズマ
# （うわー、お姉さん、\n　めちゃくちゃ訝しげにアクアを見てる……）
365 = "（うわー、お姉さん、\\n　めちゃくちゃ訝しげにアクアを見てる……）"

# ダクネス
# しかし、あなたが我々に\nそんな話を持ちかけてくれるとは思わなかったな。
239 = "しかし、あなたが我々に\\nそんな話を持ちかけてくれるとは思わなかったな。"

# めぐみん
# 確かに、ちょっと驚きです。
359 = "確かに、ちょっと驚きです。"

# ルナ
# そ、それは、その、えーっとですね？\nあの……。
244 = "そ、それは、その、えーっとですね？\\nあの……。"

# ルナ
# そうです、魔王軍の幹部ベルティアや\nデストロイヤー撃破など、\nみなさんの街への貢献は確かなものですから！
246 = "そうです、魔王軍の幹部ベルティアや\\nデストロイヤー撃破など、\\nみなさんの街への貢献は確かなものですから！"

# ルナ
# 特に、サトウカズマさんがいなければ\nこの街が消し飛ばされていても\nおかしくなかったわけですし。
311 = "特に、サトウカズマさんがいなければ\\nこの街が消し飛ばされていても\\nおかしくなかったわけですし。"

# カズマ
# いやぁ～。\nそんな風に言われてると照れますなぁ！
221 = "いやぁ～。\\nそんな風に言われてると照れますなぁ！"

# アクア
# 待ちなさい！\nベルティアを倒したのは私の魔法よ！\nカズマだけの手柄じゃないわ！
303 = "待ちなさい！\\nベルティアを倒したのは私の魔法よ！\\nカズマだけの手柄じゃないわ！"

# めぐみん
# それに、デストロイヤーの動きを止めたのは\n私の爆裂魔法です。
254 = "それに、デストロイヤーの動きを止めたのは\\n私の爆裂魔法です。"

# カズマ（Ｍ）
# display as カズマ
# （いや、めぐみんだけじゃなくてウィズもだろ）
363 = "（いや、めぐみんだけじゃなくてウィズもだろ）"

# ルナ
# もちろん、心得ていますよ？\nみなさんが、この街を救ってくださった\n救世主です！
276 = "もちろん、心得ていますよ？\\nみなさんが、この街を救ってくださった\\n救世主です！"

# ルナ
# ですので、困ってらっしゃるみなさんに、\nギルドからもなんらかの援助を、と思いまして。
264 = "ですので、困ってらっしゃるみなさんに、\\nギルドからもなんらかの援助を、と思いまして。"

# アクア
# 援助？\nもしかして、お金くれるの？
306 = "援助？\\nもしかして、お金くれるの？"

# ルナ
# さ、さすがにそれは無理ですが。
238 = "さ、さすがにそれは無理ですが。"

# ルナ
# 実は、先ほど届いたばかりのクエストがありまして、\nそちらを優先にご紹介できたらと思いまして。
299 = "実は、先ほど届いたばかりのクエストがありまして、\\nそちらを優先にご紹介できたらと思いまして。"

# カズマ
# そうやって俺たちに回してくれるってことは、\n割のいいクエストなんですよね？
249 = "そうやって俺たちに回してくれるってことは、\\n割のいいクエストなんですよね？"

# ルナ
# はい、そうなりますね。
269 = "はい、そうなりますね。"

# アクア
# それでそれで、どんなクエストなのかしら。
252 = "それでそれで、どんなクエストなのかしら。"

# ルナ
# 最近、この街の近くで洞窟が見つかったんです。
308 = "最近、この街の近くで洞窟が見つかったんです。"

# ルナ
# ギルドで調べたところ、\nこの洞窟はとある盗賊団が\n根城にしていたとわかりました。
284 = "ギルドで調べたところ、\\nこの洞窟はとある盗賊団が\\n根城にしていたとわかりました。"

# カズマ
# まさか、その盗賊団を壊滅させるクエストなんて\n言うんじゃ……。
272 = "まさか、その盗賊団を壊滅させるクエストなんて\\n言うんじゃ……。"

# ルナ
# 我々も詳しい事情は把握していないのですが、\nどうやらその盗賊団はもう存在していない\nようなんです。
304 = "我々も詳しい事情は把握していないのですが、\\nどうやらその盗賊団はもう存在していない\\nようなんです。"

# ルナ
# これが本当に不思議なことでして、\nここ数ヶ月、盗賊団が活動をした形跡がまったく\n無くて、いったいどうしてなのか。
236 = "これが本当に不思議なことでして、\\nここ数ヶ月、盗賊団が活動をした形跡がまったく\\n無くて、いったいどうしてなのか。"

# カズマ
# ええとじゃあ、どんなクエストなんですか？
227 = "ええとじゃあ、どんなクエストなんですか？"

# ルナ
# その盗賊団は、\n博物館をターゲットに行動をしていました。
251 = "その盗賊団は、\\n博物館をターゲットに行動をしていました。"

# ルナ
# それはもう、多数の財宝が盗まれまして、\n盗難にあった物の中には、数十億エリスの\n価値の物もあったと聞いています。
255 = "それはもう、多数の財宝が盗まれまして、\\n盗難にあった物の中には、数十億エリスの\\n価値の物もあったと聞いています。"

# アクア
# す、数十億エリス……。
242 = "す、数十億エリス……。"

# ルナ
# 今回の依頼内容はこうです。\n事前調査として、盗賊団が根城にしていた\n洞窟を調べろ。
292 = "今回の依頼内容はこうです。\\n事前調査として、盗賊団が根城にしていた\\n洞窟を調べろ。"

# アクア
# え、洞窟の調査？
225 = "え、洞窟の調査？"

# カズマ
# そんなクエストじゃろくな金にならないんじゃ。
257 = "そんなクエストじゃろくな金にならないんじゃ。"

# ルナ
# そうですね。\n調査だけでしたら、５０万エリスと\n設定されています。
248 = "そうですね。\\n調査だけでしたら、５０万エリスと\\n設定されています。"

# ルナ
# ですが、財宝を見つけてくれたら――
263 = "ですが、財宝を見つけてくれたら――"

# アクア
# 数十億エリスが私たちの物になるのね！
307 = "数十億エリスが私たちの物になるのね！"

# カズマ
# 声が大きいってアクア！
298 = "声が大きいってアクア！"

# アクア
# あっ、ごめんなさい。
216 = "あっ、ごめんなさい。"

# ルナ
# 盗まれた財宝のほとんどは博物館の所蔵品ですので、\nさすがにその物をお渡しすることはできません。\nですが――
313 = "盗まれた財宝のほとんどは博物館の所蔵品ですので、\\nさすがにその物をお渡しすることはできません。\\nですが――"

# アクア
# で、ですが？
261 = "で、ですが？"

# ルナ
# この国の過去の文化を示す重大な財宝を\n取り戻すんですから、\n相応の報酬金が用意されてると思いますよ。
235 = "この国の過去の文化を示す重大な財宝を\\n取り戻すんですから、\\n相応の報酬金が用意されてると思いますよ。"

# カズマ
# その口振りだと、\nまだ金額まで決まっていないんですね。
250 = "その口振りだと、\\nまだ金額まで決まっていないんですね。"

# ルナ
# ギルド本部からは、\nこのクエストに２億エリスの用意があると\n知らされています。
286 = "ギルド本部からは、\\nこのクエストに２億エリスの用意があると\\n知らされています。"

# めぐみん
# におくっ！？
267 = "におくっ！？"

# ルナ
# もちろん、\n見つけ出した財宝で金額が上下しますので、\nそこだけは注意をしてくださいね。
275 = "もちろん、\\n見つけ出した財宝で金額が上下しますので、\\nそこだけは注意をしてくださいね。"

# めぐみん
# やりましたね、カズマ！\nまさかの、一攫千金の大チャンスですよ！
278 = "やりましたね、カズマ！\\nまさかの、一攫千金の大チャンスですよ！"

# ダクネス
# うまくやれば、バニルに\n３０００万エリスを払うことができそうだな！
222 = "うまくやれば、バニルに\\n３０００万エリスを払うことができそうだな！"

# アクア
# それどころか、おつりが来るかもしれないわ！\nもう、あくせく働かなくてもいいのよ！
253 = "それどころか、おつりが来るかもしれないわ！\\nもう、あくせく働かなくてもいいのよ！"

# アクア
# すみませーん！\nこっちにシュワシュワと、\nあとカエルの唐揚げ大盛りお願いしまーす！
243 = "すみませーん！\\nこっちにシュワシュワと、\\nあとカエルの唐揚げ大盛りお願いしまーす！"

# カズマ
# い、いや、ちょっと待て、お前ら！\n特にアクア！　さっそくシュワシュワを\n注文しようとするんじゃない！
219 = "い、いや、ちょっと待て、お前ら！\\n特にアクア！　さっそくシュワシュワを\\n注文しようとするんじゃない！"

# カズマ
# えーっと、すみません。\n確認したいんですけど……。
228 = "えーっと、すみません。\\n確認したいんですけど……。"

# ルナ
# はい、なんでしょう？
270 = "はい、なんでしょう？"

# カズマ
# これって、相当おいしいクエストですよね？\nそんなのを、お姉さんの判断で俺達みたいな\nへっぽこパーティーに流しちゃっていいんですか？
237 = "これって、相当おいしいクエストですよね？\\nそんなのを、お姉さんの判断で俺達みたいな\\nへっぽこパーティーに流しちゃっていいんですか？"

# ルナ
# そ、それは、なんと言いますか、\n正直言ってしまうと、良くはないのですが。
245 = "そ、それは、なんと言いますか、\\n正直言ってしまうと、良くはないのですが。"

# ルナ
# こ、困った時はお互い様と言いますから。\nみなさんには、この街全体が困った時に\nお世話になったわけですしね？
233 = "こ、困った時はお互い様と言いますから。\\nみなさんには、この街全体が困った時に\\nお世話になったわけですしね？"

# ルナ
# 私自身、いつか恩を返さなくてはと\n思っていましたから。\nですので、今回は、特別ということで。
360 = "私自身、いつか恩を返さなくてはと\\n思っていましたから。\\nですので、今回は、特別ということで。"

# カズマ（Ｍ）
# display as カズマ
# （う、ううううううっ！\n　俺のためにここまでしてくれるなんて！\n　いい人過ぎるだろ！）
364 = "（う、ううううううっ！\\n　俺のためにここまでしてくれるなんて！\\n　いい人過ぎるだろ！）"

# カズマ
# よーし、お前ら！\nギルドからの有り難い支援なんだ！\nここは一発逆転を狙って、心して挑むぞ！
279 = "よーし、お前ら！\\nギルドからの有り難い支援なんだ！\\nここは一発逆転を狙って、心して挑むぞ！"

# アクア
# おー！
231 = "おー！"

# ダクネス
# うむ、気を引き締めて行こう。
223 = "うむ、気を引き締めて行こう。"

# めぐみん
# 我が力、見せてあげますよ！
305 = "我が力、見せてあげますよ！"

# ルナ
# ちょ、ちょっと！？\n静かにしてください、周りが注目しますから！
258 = "ちょ、ちょっと！？\\n静かにしてください、周りが注目しますから！"

# カズマ
# す、すみませんっ！
241 = "す、すみませんっ！"

