# st04b_04.txt.scn

[info]
0 = ""

[characters]
313 = "ゆんゆん"
320 = "カズマ"
323 = "カズマ（Ｍ）"
324 = "クリス"

[character_subs]
# 320 = "カズマ"

[script]
# lines: 121

# ゆんゆん
# ずいぶん深い森ですね。\nなんだか、ちょっと不気味です。
276 = "ずいぶん深い森ですね。\\nなんだか、ちょっと不気味です。"

# カズマ
# ゆんゆん、足元に気をつけろよ。
315 = "ゆんゆん、足元に気をつけろよ。"

# ゆんゆん
# あ、はい。\nありがとうございます。
243 = "あ、はい。\\nありがとうございます。"

# カズマ（Ｍ）
# display as カズマ
# （湖を出発した後、俺達は森の中に踏み込んだ）
404 = "（湖を出発した後、俺達は森の中に踏み込んだ）"

# カズマ（Ｍ）
# display as カズマ
# （草木がうっそうと茂り、\n　陽の光もあまり届かない深い森――）
405 = "（草木がうっそうと茂り、\\n　陽の光もあまり届かない深い森――）"

# カズマ（Ｍ）
# display as カズマ
# （正直、歩きたいとは思えない場所だ。\n　でも、目的の洞窟に行くには\n　ここを横断しなくちゃならない）
403 = "（正直、歩きたいとは思えない場所だ。\\n　でも、目的の洞窟に行くには\\n　ここを横断しなくちゃならない）"

# カズマ（Ｍ）
# display as カズマ
# （ただでさえ森の中を進むのは危険が多い。\n　だから、念のためにクリスが辺りを\n　調べてくれている）
395 = "（ただでさえ森の中を進むのは危険が多い。\\n　だから、念のためにクリスが辺りを\\n　調べてくれている）"

# カズマ（Ｍ）
# display as カズマ
# （女の子にこんなことをさせるのは気が引けるが、\n　クリスは本職の盗賊だからな）
399 = "（女の子にこんなことをさせるのは気が引けるが、\\n　クリスは本職の盗賊だからな）"

# クリス
# うん、やっぱり。\nこの森、人が通った痕跡がはっきり残ってるよ。
260 = "うん、やっぱり。\\nこの森、人が通った痕跡がはっきり残ってるよ。"

# カズマ
# はあ！？\n俺達以外にも、洞窟に向かった奴が\nいるってことか？
306 = "はあ！？\\n俺達以外にも、洞窟に向かった奴が\\nいるってことか？"

# クリス
# ううん、そうじゃない。\nこの森で日常的に狩りをしている人達がいるんだよ。
258 = "ううん、そうじゃない。\\nこの森で日常的に狩りをしている人達がいるんだよ。"

# ゆんゆん
# こんな森でですか？
273 = "こんな森でですか？"

# クリス
# こんな森だからじゃない？\n動物が生活してる痕跡も多いしね。
272 = "こんな森だからじゃない？\\n動物が生活してる痕跡も多いしね。"

# クリス
# となると、気をつけないと。\n狩人が仕掛けた動物用の罠あるかもしれない。
294 = "となると、気をつけないと。\\n狩人が仕掛けた動物用の罠あるかもしれない。"

# カズマ
# ああ、確かに。\n引っかかったら笑えねーもんな。
247 = "ああ、確かに。\\n引っかかったら笑えねーもんな。"

# クリス
# それと、当然だけどモンスターにも気をつけて。\n今のところ気配はないけど、\nどこかに潜んでいるかもしれないよ。
283 = "それと、当然だけどモンスターにも気をつけて。\\n今のところ気配はないけど、\\nどこかに潜んでいるかもしれないよ。"

# ゆんゆん
# は、はい。
302 = "は、はい。"

# クリス
# ああ、そんなに緊張しなくても大丈夫。\nあたし達は３人なんだから、\n協力しあって進んでいこう。
245 = "ああ、そんなに緊張しなくても大丈夫。\\nあたし達は３人なんだから、\\n協力しあって進んでいこう。"

# カズマ
# その通り！\nそれぞれのスキルを活かす！\nパーティーってのはそういうもんだからな。
282 = "その通り！\\nそれぞれのスキルを活かす！\\nパーティーってのはそういうもんだからな。"

# カズマ
# じゃ、さっそくだけど\nクリスに先頭を頼んでいいか？\nゆんゆんは俺の後ろについてきてくれ。
275 = "じゃ、さっそくだけど\\nクリスに先頭を頼んでいいか？\\nゆんゆんは俺の後ろについてきてくれ。"

# クリス
# はあっ！？
305 = "はあっ！？"

# カズマ
# いや、気持ちはわかるけどさ、\n俺が先頭を歩いて罠にかかったりしたら\n目も当てられないだろ。
253 = "いや、気持ちはわかるけどさ、\\n俺が先頭を歩いて罠にかかったりしたら\\n目も当てられないだろ。"

# カズマ
# その点、クリスは盗賊スキルに長けてるからな。\n安心できる。
281 = "その点、クリスは盗賊スキルに長けてるからな。\\n安心できる。"

# クリス
# ああ、ごめん、そういう意味か。
244 = "ああ、ごめん、そういう意味か。"

# カズマ
# 他にどんな意味があるっていうんだ……。
331 = "他にどんな意味があるっていうんだ……。"

# クリス
# な、なんでもないよ。\nそれじゃ……ついてきてね？
297 = "な、なんでもないよ。\\nそれじゃ……ついてきてね？"

# クリス
# …………。
240 = "…………。"

# カズマ
# …………。
# 240 = "…………。"

# クリス
# …………。
# 240 = "…………。"

# カズマ
# クリス？\nなんでそんなに後ろを気にしてるんだ？
325 = "クリス？\\nなんでそんなに後ろを気にしてるんだ？"

# クリス
# えっ！？\nいや、その、えーっと……なんでもないよ？
262 = "えっ！？\\nいや、その、えーっと……なんでもないよ？"

# クリス
# …………。
# 240 = "…………。"

# カズマ
# …………。
# 240 = "…………。"

# クリス
# …………。
# 240 = "…………。"

# カズマ
# あのー、クリスさん？\nやっぱり後ろ、気にしてますよね？
251 = "あのー、クリスさん？\\nやっぱり後ろ、気にしてますよね？"

# クリス
# う……。
254 = "う……。"

# カズマ
# 俺とゆんゆんで警戒してるから大丈夫だって。\n前に集中してくれよ。
332 = "俺とゆんゆんで警戒してるから大丈夫だって。\\n前に集中してくれよ。"

# クリス
# そうじゃなくてさ……後ろに立たれると。
279 = "そうじゃなくてさ……後ろに立たれると。"

# カズマ（Ｍ）
# display as カズマ
# （後ろに立たれると、なんなんだ？\n　俺が何かするとでも思ってるのか？）
401 = "（後ろに立たれると、なんなんだ？\\n　俺が何かするとでも思ってるのか？）"

# カズマ
# 大丈夫だって。\n変なイタズラしてる場合じゃないってことくらい\nわかってるよ。
337 = "大丈夫だって。\\n変なイタズラしてる場合じゃないってことくらい\\nわかってるよ。"

# クリス
# そういうのでもなくて……。\nただ、後ろにキミがいると気になって……。
278 = "そういうのでもなくて……。\\nただ、後ろにキミがいると気になって……。"

# カズマ（Ｍ）
# display as カズマ
# （そんなに俺が後ろにいると不安なのか？\n　じゃあ……）
394 = "（そんなに俺が後ろにいると不安なのか？\\n　じゃあ……）"

# カズマ
# ゆんゆん、場所を交代しよう。\nクリスの後ろをついて行ってくれ。
314 = "ゆんゆん、場所を交代しよう。\\nクリスの後ろをついて行ってくれ。"

# ゆんゆん
# そ、そ、それは困りますっ！
277 = "そ、そ、それは困りますっ！"

# カズマ
# へ？　なんで？
310 = "へ？　なんで？"

# ゆんゆん
# だ、だって、そうすると、\n私の後ろにカズマさんが……。
284 = "だ、だって、そうすると、\\n私の後ろにカズマさんが……。"

# カズマ
# ゆんゆんまでそんなこと言うのかよ！
316 = "ゆんゆんまでそんなこと言うのかよ！"

# クリス
# ……あ。
241 = "……あ。"

# カズマ
# え？
263 = "え？"

# ゆんゆん
# え？
# 263 = "え？"

# クリス
# カズマ！　逃げてっ！！
322 = "カズマ！　逃げてっ！！"

# カズマ
# うわあっ！？\nな、なんだ！？
259 = "うわあっ！？\\nな、なんだ！？"

# クリス
# ひゃあああっ！？
309 = "ひゃあああっ！？"

# ゆんゆん
# きゃあ！？
267 = "きゃあ！？"

# カズマ（Ｍ）
# display as カズマ
# （思い返せば――）
402 = "（思い返せば――）"

# カズマ
# （俺は、この世界に来て初めて\n　冒険らしい冒険に出たのかもしれない）
397 = "（俺は、この世界に来て初めて\\n　冒険らしい冒険に出たのかもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （俺は待ち望んでいたんだ。\n　冒険者として、こんなハプニングに\n　遭遇する日をっ！）
398 = "（俺は待ち望んでいたんだ。\\n　冒険者として、こんなハプニングに\\n　遭遇する日をっ！）"

# クリス
# うう、こんな古典的な罠に掛かるなんてっ！
257 = "うう、こんな古典的な罠に掛かるなんてっ！"

# ゆんゆん
# きゃあああっ！？\nな、な、なんですか、これー！！
266 = "きゃあああっ！？\\nな、な、なんですか、これー！！"

# カズマ（Ｍ）
# display as カズマ
# （うん、絶景かな！）
390 = "（うん、絶景かな！）"

# ゆんゆん
# ああっ！\nみ、みみ、見えちゃう！！\nスカートが捲れちゃいます！
248 = "ああっ！\\nみ、みみ、見えちゃう！！\\nスカートが捲れちゃいます！"

# カズマ（Ｍ）
# display as カズマ
# （スカートが！？）
396 = "（スカートが！？）"

# クリス
# ちょ、ちょっと待って、ゆんゆん！\nそんなに暴れないで、\n縄がズボンに引っかかって……。
287 = "ちょ、ちょっと待って、ゆんゆん！\\nそんなに暴れないで、\\n縄がズボンに引っかかって……。"

# カズマ（Ｍ）
# display as カズマ
# （引っかかってどうなるんですかね！）
400 = "（引っかかってどうなるんですかね！）"

# クリス
# ぬ、脱げちゃう！\n脱げちゃうからっ！！
301 = "ぬ、脱げちゃう！\\n脱げちゃうからっ！！"

# カズマ（Ｍ）
# display as カズマ
# （そうなったら見えちゃいますね！）
393 = "（そうなったら見えちゃいますね！）"

# クリス
# って、カズマ！\n何、ニヤニヤして見てるのさ！
289 = "って、カズマ！\\n何、ニヤニヤして見てるのさ！"

# カズマ
# ににに、ニヤニヤなんてしてませんけど！
300 = "ににに、ニヤニヤなんてしてませんけど！"

# クリス
# と、とにかく助けてったら！\nこっち、ちょっと動いただけで！
292 = "と、とにかく助けてったら！\\nこっち、ちょっと動いただけで！"

# ゆんゆん
# ス、ス、スカートがぁぁぁぁ！！
326 = "ス、ス、スカートがぁぁぁぁ！！"

# カズマ（Ｍ）
# display as カズマ
# （くお、おしいっ！）
391 = "（くお、おしいっ！）"

# クリス
# ズボンだけじゃなくてスパッツまでぇぇ！！
327 = "ズボンだけじゃなくてスパッツまでぇぇ！！"

# カズマ（Ｍ）
# display as カズマ
# （うほおおおおおお！！）
389 = "（うほおおおおおお！！）"

# クリス
# お願い、カズマ助けて！！
264 = "お願い、カズマ助けて！！"

# カズマ
# しかし、違う罠があるかもしれない！
274 = "しかし、違う罠があるかもしれない！"

# クリス
# とか言いながら、なんでチラチラ見てるのさ。
293 = "とか言いながら、なんでチラチラ見てるのさ。"

# カズマ
# 見てないって！　ああ、見てないぞ。
386 = "見てないって！　ああ、見てないぞ。"

# カズマ（Ｍ）
# display as カズマ
# （くっ、ゆんゆんのスカートは鋼鉄製なのか！）
392 = "（くっ、ゆんゆんのスカートは鋼鉄製なのか！）"

# ゆんゆん
# ひっ、とてもいやらしい顔をしてます！
307 = "ひっ、とてもいやらしい顔をしてます！"

# クリス
# うぅぅ、ズボンがずれるーーーー！！
255 = "うぅぅ、ズボンがずれるーーーー！！"

# カズマ（Ｍ）
# display as カズマ
# （いいぞ、もっと、もっとだ！）
388 = "（いいぞ、もっと、もっとだ！）"

# クリス
# カズマ、お願いだから助けてよ！\n早くー！！
321 = "カズマ、お願いだから助けてよ！\\n早くー！！"

# ゆんゆん
# でで、で、でも、近くには来ないでくださいっ！
290 = "でで、で、でも、近くには来ないでくださいっ！"

# カズマ
# ほお、なかなかの難題だね。\nでは、状況を把握するため、もう少し、じっくりと、\n君たちを観察しつつ、考える時間を貰おうかな。
311 = "ほお、なかなかの難題だね。\\nでは、状況を把握するため、もう少し、じっくりと、\\n君たちを観察しつつ、考える時間を貰おうかな。"

# ゆんゆん
# でも、あの、見えちゃうのは困ります！
291 = "でも、あの、見えちゃうのは困ります！"

# クリス
# 下！　下を見ながら助けて！
328 = "下！　下を見ながら助けて！"

# カズマ
# あのさ、２人とも本当に助けてほしいの？
250 = "あのさ、２人とも本当に助けてほしいの？"

# クリス
# こっちにも都合があるの！\nいいから言うことをきいて！
271 = "こっちにも都合があるの！\\nいいから言うことをきいて！"

# カズマ
# どうやって助ければいいんだ！？
295 = "どうやって助ければいいんだ！？"

# クリス
# 網を下ろすための仕掛けがあるはず！\nそれを探してみて！
385 = "網を下ろすための仕掛けがあるはず！\\nそれを探してみて！"

# カズマ
# そう言われても見当がつかないぞ。\nなにかヒントないか？
280 = "そう言われても見当がつかないぞ。\\nなにかヒントないか？"

# クリス
# ええっと、そうだね、\n網を引き上げている装置に手がかりがあると思う。
261 = "ええっと、そうだね、\\n網を引き上げている装置に手がかりがあると思う。"

# カズマ
# わかった！\nすぐに調べるから待ってろ！
319 = "わかった！\\nすぐに調べるから待ってろ！"

# ゆんゆん
# 宜しくお願いします！
339 = "宜しくお願いします！"

# カズマ
# くっ！　カメラが欲しい！
268 = "くっ！　カメラが欲しい！"

# ゆんゆん
# か、かめら？\nなんですか、それ。
265 = "か、かめら？\\nなんですか、それ。"

# クリス
# なんなのかはわからないけど、\nあの顔からして、\nろくでもないことを考えたのは確かね。
298 = "なんなのかはわからないけど、\\nあの顔からして、\\nろくでもないことを考えたのは確かね。"

# カズマ
# 人の顔を見て失礼だな！？
330 = "人の顔を見て失礼だな！？"

# クリス
# だったら、いやらしい顔で\nやましいことなんて考えてないで、\n早く助けてっ！
286 = "だったら、いやらしい顔で\\nやましいことなんて考えてないで、\\n早く助けてっ！"

# カズマ
# わ、わかったよ！
317 = "わ、わかったよ！"

# クリス
# はあ、はあ。\nとんでもない目にあった。
303 = "はあ、はあ。\\nとんでもない目にあった。"

# ゆんゆん
# うう……。\n怖かった……恥ずかしかった……。
256 = "うう……。\\n怖かった……恥ずかしかった……。"

# カズマ
# 大丈夫か、２人とも。\nケガは？
336 = "大丈夫か、２人とも。\\nケガは？"

# クリス
# あたしは平気。\nゆんゆんは？
249 = "あたしは平気。\\nゆんゆんは？"

# ゆんゆん
# だ、大丈夫、です……けど……。
285 = "だ、大丈夫、です……けど……。"

# カズマ
# けど？　なんだ？
269 = "けど？　なんだ？"

# ゆんゆん
# 見てませんよね？
387 = "見てませんよね？"

# カズマ
# え？
# 263 = "え？"

# ゆんゆん
# みみみ、見てませんよね！？
312 = "みみみ、見てませんよね！？"

# カズマ
# ああ、スカートの中か？
246 = "ああ、スカートの中か？"

# ゆんゆん
# ひっ！？
308 = "ひっ！？"

# カズマ
# 安心しろ。\nギリギリ、見えなかった。
338 = "安心しろ。\\nギリギリ、見えなかった。"

# クリス
# 格好つけて言うところじゃないでしょ。\nもう、なんでキミだけ罠から逃げられたのかな？
342 = "格好つけて言うところじゃないでしょ。\\nもう、なんでキミだけ罠から逃げられたのかな？"

# カズマ
# 偶然だろうけど、\n無駄に高い幸運が働いたのかもな。
333 = "偶然だろうけど、\\n無駄に高い幸運が働いたのかもな。"

# カズマ
# にしても！\nいやー、感激だよ！
299 = "にしても！\\nいやー、感激だよ！"

# クリス
# ちょっと？\n人が罠に掛かって感激って、どういうこと？
288 = "ちょっと？\\n人が罠に掛かって感激って、どういうこと？"

# カズマ
# いや、勘違いしないでくれよ？\n俺はただ純粋に――
252 = "いや、勘違いしないでくれよ？\\n俺はただ純粋に――"

# カズマ
# こういう、ムフフなハプニングイベントが\n欲しかったんだよ！\n冒険者の醍醐味ってやつだ！！
270 = "こういう、ムフフなハプニングイベントが\\n欲しかったんだよ！\\n冒険者の醍醐味ってやつだ！！"

# クリス
# ……ああ、そう。
242 = "……ああ、そう。"

# ゆんゆん
# わ、私も、楽しい冒険には憧れていましたけど、\nこういうのは困ります。
318 = "わ、私も、楽しい冒険には憧れていましたけど、\\nこういうのは困ります。"

# クリス
# はあ、やっぱり来なければよかったなぁ。
304 = "はあ、やっぱり来なければよかったなぁ。"

[selections]
# 274 = "しかし、違う罠があるかもしれない！"
296 = "どうやって助ければ良いんだ！？"
# 268 = "くっ！　カメラが欲しい！"
