# st04a_03.txt.scn

[info]
0 = ""

[characters]
273 = "アクア"
274 = "ウィズ"
275 = "カズマ"
277 = "ダクネス"
276 = "カズマ（Ｍ）"
279 = "バニル"
266 = "めぐみん"

[character_subs]
# 275 = "カズマ"

[script]
# lines: 71

# アクア
# いるんでしょ、出てきなさい！
230 = "いるんでしょ、出てきなさい！"

# ウィズ
# は、はい、ただいま！
258 = "は、はい、ただいま！"

# ウィズ
# あら、アクア様？
225 = "あら、アクア様？"

# アクア
# ちょっと、なんであんたが出て来るのよ。\nもしかして私のこと、馬鹿にしてるんですか？
253 = "ちょっと、なんであんたが出て来るのよ。\\nもしかして私のこと、馬鹿にしてるんですか？"

# ウィズ
# え、ええ！？　あの、アクア様？\nここは、私のお店……ですよね？
235 = "え、ええ！？　あの、アクア様？\\nここは、私のお店……ですよね？"

# アクア
# そうよ、だからなんだって言うのよ。
247 = "そうよ、だからなんだって言うのよ。"

# カズマ
# お前はウィズにすごむなっ！
239 = "お前はウィズにすごむなっ！"

# アクア
# あぅ！　痛い～～～～。
224 = "あぅ！　痛い～～～～。"

# カズマ
# 悪いな、うちの駄女神、今気が立っててさ。
294 = "悪いな、うちの駄女神、今気が立っててさ。"

# ウィズ
# か、かか、カズマさんっ！？
240 = "か、かか、カズマさんっ！？"

# カズマ
# ん？　どうかしたか？
272 = "ん？　どうかしたか？"

# ウィズ
# いえ、別に、なんでも。
229 = "いえ、別に、なんでも。"

# ウィズ
# え、ええと、それで、\nどういったご用件でしょうか。
233 = "え、ええと、それで、\\nどういったご用件でしょうか。"

# アクア
# 害虫の首をさし出しなさい。\nかくまってもあんたに得は何もないわよ。
289 = "害虫の首をさし出しなさい。\\nかくまってもあんたに得は何もないわよ。"

# カズマ
# だから、ウィズにすごむな！
251 = "だから、ウィズにすごむな！"

# アクア
# ひぅ！　痛い～～～～！！
262 = "ひぅ！　痛い～～～～！！"

# ウィズ
# え、ええと、害虫というのは。
234 = "え、ええと、害虫というのは。"

# ダクネス
# バニルのことだ。\nもしや、また買い出しの旅に出ているのか？
280 = "バニルのことだ。\\nもしや、また買い出しの旅に出ているのか？"

# ウィズ
# いえ、バニルさんでしたら、今日はいますよ。
228 = "いえ、バニルさんでしたら、今日はいますよ。"

# アクア
# ……そう、いるの、いるのね。
223 = "……そう、いるの、いるのね。"

# カズマ（Ｍ）
# display as カズマ
# （うわー、めちゃくちゃやる気だよこの子）
337 = "（うわー、めちゃくちゃやる気だよこの子）"

# バニル
# そう殺気を放つな。駆け出しプリースト。
248 = "そう殺気を放つな。駆け出しプリースト。"

# めぐみん
# わっ！？\nいつの間に現れたんですか、この人！
270 = "わっ！？\\nいつの間に現れたんですか、この人！"

# バニル
# 人ではなく悪魔である。\n間違えるでないぞ、頭の足りない紅魔族の娘よ。
284 = "人ではなく悪魔である。\\n間違えるでないぞ、頭の足りない紅魔族の娘よ。"

# めぐみん
# ほほう、どうやら本当に\n我の真の力を見たいようだな。\n良い覚悟だが、愚かなことよ。
265 = "ほほう、どうやら本当に\\n我の真の力を見たいようだな。\\n良い覚悟だが、愚かなことよ。"

# カズマ
# ダクネス、止めろ。
278 = "ダクネス、止めろ。"

# めぐみん
# わっ！？\nダクネス、なにをするのですか！\nつまみ上げないでください！
271 = "わっ！？\\nダクネス、なにをするのですか！\\nつまみ上げないでください！"

# ダクネス
# ここで爆裂魔法は勘弁してくれ。\nそれに、我々は話し合いに来たんだぞ？
242 = "ここで爆裂魔法は勘弁してくれ。\\nそれに、我々は話し合いに来たんだぞ？"

# バニル
# ほう、話し合いであるか。\n言っておくが３０００万エリスは動かないぞ？
263 = "ほう、話し合いであるか。\\n言っておくが３０００万エリスは動かないぞ？"

# カズマ
# わかってる。\nまけてくれとか言う気はねーよ。
269 = "わかってる。\\nまけてくれとか言う気はねーよ。"

# バニル
# ほうほう。\nでは、どういった用件であるか？
264 = "ほうほう。\\nでは、どういった用件であるか？"

# カズマ（Ｍ）
# display as カズマ
# （ニヤニヤしやがって。\n　どうせ、全部見通してるんだろ？）
341 = "（ニヤニヤしやがって。\\n　どうせ、全部見通してるんだろ？）"

# アクア
# あらぁ？　超強い悪魔様がしらを切るおつもり？\nどうしましょう、そんな小物だったなんて\nガッカリですわぁ。
226 = "あらぁ？　超強い悪魔様がしらを切るおつもり？\\nどうしましょう、そんな小物だったなんて\\nガッカリですわぁ。"

# バニル
# おやおや、まさかこの駆け出しプリーストに\n尊敬されているとは思わなかったぞ。\nガッカリさせてしまったことは謝ろう。
237 = "おやおや、まさかこの駆け出しプリーストに\\n尊敬されているとは思わなかったぞ。\\nガッカリさせてしまったことは謝ろう。"

# アクア
# …………。
222 = "…………。"

# カズマ
# ダクネス、止めろ。
# 278 = "ダクネス、止めろ。"

# ダクネス
# わかった。
268 = "わかった。"

# アクア
# きゃあっ！？\nちょっと、離しなさいよっ！
241 = "きゃあっ！？\\nちょっと、離しなさいよっ！"

# カズマ
# お前が余計な事を言うと話が進まないんだよ。
238 = "お前が余計な事を言うと話が進まないんだよ。"

# バニル
# 屋敷に闖入者か。\nそれは物騒な話であるなぁ、店主よ。
290 = "屋敷に闖入者か。\\nそれは物騒な話であるなぁ、店主よ。"

# ウィズ
# は、はいっ！？\nえ、ええ、物騒ですね、はい。
259 = "は、はいっ！？\\nえ、ええ、物騒ですね、はい。"

# バニル
# %fsyogen;この店も、泥棒に気をつけたほうが\nいいのではないか？
20 = "%fsyogen;この店も、泥棒に気をつけたほうが\\nいいのではないか？"

# ウィズ
# そ、そう、ですね。\nええ、まったくです。
245 = "そ、そう、ですね。\\nええ、まったくです。"

# カズマ（Ｍ）
# display as カズマ
# （この店も泥棒に気をつける？\n　魔王軍の幹部になれるようなやつが\n　２人もいるのにか？）
339 = "（この店も泥棒に気をつける？\\n　魔王軍の幹部になれるようなやつが\\n　２人もいるのにか？）"

# カズマ（Ｍ）
# display as カズマ
# （バニルらしからぬ考えのない発言に思える）
342 = "（バニルらしからぬ考えのない発言に思える）"

# カズマ（Ｍ）
# display as カズマ
# （よし、証言としてゲットしておこう）
340 = "（よし、証言としてゲットしておこう）"

# ダクネス
# どうしたんだ？\nソワソワしているが、\n何か気になることもでもあるのか？
256 = "どうしたんだ？\\nソワソワしているが、\\n何か気になることもでもあるのか？"

# ウィズ
# な、なんでもありません！\nその、物騒なのでちょっと怖くなってしまって！\n泥棒対策、ちゃんと考えますね！
257 = "な、なんでもありません！\\nその、物騒なのでちょっと怖くなってしまって！\\n泥棒対策、ちゃんと考えますね！"

# カズマ（Ｍ）
# display as カズマ
# （いや、この店に泥棒が入ることは\n　ないと思うけどなぁ）
336 = "（いや、この店に泥棒が入ることは\\n　ないと思うけどなぁ）"

# アクア
# ちょっとそこの悪魔、まだしらを切るわけ？\nあんたなんでしょ？　なにしに来てたの？\nさっさと吐きなさいよ。
254 = "ちょっとそこの悪魔、まだしらを切るわけ？\\nあんたなんでしょ？　なにしに来てたの？\\nさっさと吐きなさいよ。"

# バニル
# 吐くものなど何ひとつ無いのに、無茶を言う。
288 = "吐くものなど何ひとつ無いのに、無茶を言う。"

# カズマ
# だってよ、アクア。\nやっぱりバニルじゃ無いんじゃないか？
252 = "だってよ、アクア。\\nやっぱりバニルじゃ無いんじゃないか？"

# アクア
# いいえ、絶対にこの害虫よ！\n私の結界に耐えられるのは、\nこいつしか考えられないもの！
227 = "いいえ、絶対にこの害虫よ！\\n私の結界に耐えられるのは、\\nこいつしか考えられないもの！"

# カズマ
# ていうか、お前の結界はこの指輪の効果を\n防げないじゃんか。\nなんで、そこまで自信満々になれるんだ？
255 = "ていうか、お前の結界はこの指輪の効果を\\n防げないじゃんか。\\nなんで、そこまで自信満々になれるんだ？"

# めぐみん
# そういえばそうですね。\nこの指輪の呪いって、かなり強いものなんですね。
246 = "そういえばそうですね。\\nこの指輪の呪いって、かなり強いものなんですね。"

# アクア
# はっ！？\nねえ、気がついてしまったのだけど――
261 = "はっ！？\\nねえ、気がついてしまったのだけど――"

# アクア
# 私の結界を最大出力にして\nカズマの周りに張り巡らせれば、\nはた迷惑な行為もしなくなるじゃない！
334 = "私の結界を最大出力にして\\nカズマの周りに張り巡らせれば、\\nはた迷惑な行為もしなくなるじゃない！"

# ダクネス
# おお、そんな手段があるのか。\nぜひとも試してみるべきだろう。
236 = "おお、そんな手段があるのか。\\nぜひとも試してみるべきだろう。"

# カズマ
# 俺の周りに結界って……\nそれ、身動き取れなくなるんじゃないか？
285 = "俺の周りに結界って……\\nそれ、身動き取れなくなるんじゃないか？"

# アクア
# 身動きどころじゃないわね。\n空気さえ通さなくなるから、\nいずれ呼吸困難になって死ぬわ。
335 = "身動きどころじゃないわね。\\n空気さえ通さなくなるから、\\nいずれ呼吸困難になって死ぬわ。"

# カズマ
# さらっと怖いこと言ってんじゃねーよ！\n俺を殺す気か！
243 = "さらっと怖いこと言ってんじゃねーよ！\\n俺を殺す気か！"

# アクア
# うん。
231 = "うん。"

# カズマ
# うん！？
232 = "うん！？"

# バニル
# やれやれ。\n朝から騒がしい限りであるな。
267 = "やれやれ。\\n朝から騒がしい限りであるな。"

# バニル
# そんなことで騒ぎ立てる余裕があるのなら、\n３０００万エリスを我輩に叩きつけてくれる日も\n近いようで、実に楽しみである。
250 = "そんなことで騒ぎ立てる余裕があるのなら、\\n３０００万エリスを我輩に叩きつけてくれる日も\\n近いようで、実に楽しみである。"

# アクア
# 当たり前じゃない。\nすぐにでも持ってきてあげるから、\n大人しく待ってなさい！
293 = "当たり前じゃない。\\nすぐにでも持ってきてあげるから、\\n大人しく待ってなさい！"

# カズマ（Ｍ）
# display as カズマ
# （おいおい、そんな大見得切ってどうすんだよ。\n　全然稼げてないってのに……\n　この駄女神が余計な事を言う前に退散だ！）
338 = "（おいおい、そんな大見得切ってどうすんだよ。\\n　全然稼げてないってのに……\\n　この駄女神が余計な事を言う前に退散だ！）"

# カズマ
# じゃ、じゃあ、俺達はもう行くから。\nまたな、ウィズ、バニル。
244 = "じゃ、じゃあ、俺達はもう行くから。\\nまたな、ウィズ、バニル。"

# ウィズ
# はい。\nまた、いつでも来てくださいね。
260 = "はい。\\nまた、いつでも来てくださいね。"

# バニル
# 期待して待っているぞ。\n昨夜も呪いにその身を蝕まれた小僧よ。
295 = "期待して待っているぞ。\\n昨夜も呪いにその身を蝕まれた小僧よ。"

# カズマ
# その言い方やめろ！\n怖いだろ！
249 = "その言い方やめろ！\\n怖いだろ！"

