# st04b_06.txt.scn

[info]
0 = ""

[characters]
237 = "カズマ"
239 = "クリス"
234 = "ゆんゆん"
238 = "カズマ（Ｍ）"

[character_subs]
# 237 = "カズマ"

[script]
# lines: 65

# カズマ
# う、うう……。\nいててててて……。
199 = "う、うう……。\\nいててててて……。"

# カズマ
# って、クリス！？　ゆんゆん！？\nどこだ！？
219 = "って、クリス！？　ゆんゆん！？\\nどこだ！？"

# クリス
# あたしはここだよ。\nゆんゆんもいる。
196 = "あたしはここだよ。\\nゆんゆんもいる。"

# カズマ
# 大丈夫か？　ケガは？
249 = "大丈夫か？　ケガは？"

# クリス
# 驚いたことに、ケガはないんだ。\nゆんゆんは？
292 = "驚いたことに、ケガはないんだ。\\nゆんゆんは？"

# ゆんゆん
# 私もです。\n痛いところもないし、大丈夫だと思います。
288 = "私もです。\\n痛いところもないし、大丈夫だと思います。"

# カズマ
# 俺もだ。\nよかった、不幸中の幸いだな。
246 = "俺もだ。\\nよかった、不幸中の幸いだな。"

# クリス
# とりあえず、現状の確認をしようか。\nあたし達、落とし穴の罠にかかって\nここまで落ちてきたんだよね？
223 = "とりあえず、現状の確認をしようか。\\nあたし達、落とし穴の罠にかかって\\nここまで落ちてきたんだよね？"

# カズマ
# ああ、俺がスイッチに触っちまったんだよな。\nごめん。
193 = "ああ、俺がスイッチに触っちまったんだよな。\\nごめん。"

# クリス
# 謝る必要ないよ。\nあんな狭い通路に仕掛けてあったら、\n避けることも難しかったと思う。
291 = "謝る必要ないよ。\\nあんな狭い通路に仕掛けてあったら、\\n避けることも難しかったと思う。"

# ゆんゆん
# あ、あの、落ちてきたってことは、\nつまり戻れないってこと、ですよね？
191 = "あ、あの、落ちてきたってことは、\\nつまり戻れないってこと、ですよね？"

# クリス
# うーん、そうなるね。
201 = "うーん、そうなるね。"

# ゆんゆん
# じゃ、じゃあ、私達、\nこの洞窟に閉じ込められちゃったんですか！？
212 = "じゃ、じゃあ、私達、\\nこの洞窟に閉じ込められちゃったんですか！？"

# ゆんゆん
# どうしましょう！？\n死ぬまでここで過ごさなくちゃ\nいけないんですか！？
224 = "どうしましょう！？\\n死ぬまでここで過ごさなくちゃ\\nいけないんですか！？"

# クリス
# ゆんゆん、落ち着いて。\nまだ閉じ込められたって決まったわけじゃないよ。
235 = "ゆんゆん、落ち着いて。\\nまだ閉じ込められたって決まったわけじゃないよ。"

# ゆんゆん
# で、でも！
220 = "で、でも！"

# クリス
# こういう時は焦っちゃダメ。\n焦ると、どんどん悪い方に考えちゃうから。\nとりあえず前向きに考えてみよう。
209 = "こういう時は焦っちゃダメ。\\n焦ると、どんどん悪い方に考えちゃうから。\\nとりあえず前向きに考えてみよう。"

# カズマ
# 前向きって言われてもなぁ。\nそうなれる要素があるのか？
247 = "前向きって言われてもなぁ。\\nそうなれる要素があるのか？"

# クリス
# あるよ？\n財宝がある可能性が大きくなったじゃない。
197 = "あるよ？\\n財宝がある可能性が大きくなったじゃない。"

# カズマ
# ……あ、そうか！\n罠が仕掛けてあったのは、\n侵入者に備えてたってことだもんな。
189 = "……あ、そうか！\\n罠が仕掛けてあったのは、\\n侵入者に備えてたってことだもんな。"

# クリス
# その通り。
217 = "その通り。"

# ゆんゆん
# でも、でも、財宝を見つけても\n出られないんじゃ……意味がないです。
221 = "でも、でも、財宝を見つけても\\n出られないんじゃ……意味がないです。"

# クリス
# ほーら、また後ろ向きになってる。\n他にも前向きになれるポイントはあるんだから。
230 = "ほーら、また後ろ向きになってる。\\n他にも前向きになれるポイントはあるんだから。"

# クリス
# ねえキミ、ここの洞窟って、\n見た感じからして自然にできたものだよね？
226 = "ねえキミ、ここの洞窟って、\\n見た感じからして自然にできたものだよね？"

# カズマ
# あ、ああ、多分、そうだと思うけど。
190 = "あ、ああ、多分、そうだと思うけど。"

# クリス
# 自然の洞窟なんだから、\n絶対に外に繋がっているはずだよ。
289 = "自然の洞窟なんだから、\\n絶対に外に繋がっているはずだよ。"

# クリス
# その証拠に……\n風ってほどじゃないけど、空気の流れを感じない？
216 = "その証拠に……\\n風ってほどじゃないけど、空気の流れを感じない？"

# ゆんゆん
# 言われてみれば確かに……微かだけど感じます。
290 = "言われてみれば確かに……微かだけど感じます。"

# クリス
# ね？\nどこにも出口がないんだったら、\nもっと空気が淀んでいるはずなんだよ。
227 = "ね？\\nどこにも出口がないんだったら、\\nもっと空気が淀んでいるはずなんだよ。"

# カズマ
# なるほど！\nさすがだな、クリス。
225 = "なるほど！\\nさすがだな、クリス。"

# クリス
# ふふふっ！\n褒めてくれてありがと。\nそれじゃ、ひとまず風上に行って――
229 = "ふふふっ！\\n褒めてくれてありがと。\\nそれじゃ、ひとまず風上に行って――"

# カズマ
# クリス？\nどうしたんだ、急に。
241 = "クリス？\\nどうしたんだ、急に。"

# クリス
# まずい！\nモンスターが来た！
232 = "まずい！\\nモンスターが来た！"

# ゆんゆん
# ああっ！？\n見てください、あっち！　たくさんいます！
194 = "ああっ！？\\n見てください、あっち！　たくさんいます！"

# カズマ
# そっか、俺達が落ちてきた音で\n引きつけちまったのか！
214 = "そっか、俺達が落ちてきた音で\\n引きつけちまったのか！"

# クリス
# あいつら、１体１体は弱いけど……\nここで騒ぐのは避けたいよね？
195 = "あいつら、１体１体は弱いけど……\\nここで騒ぐのは避けたいよね？"

# カズマ
# ああ、ますます敵を集めることになる。\n……どうする？
192 = "ああ、ますます敵を集めることになる。\\n……どうする？"

# ゆんゆん
# だったら、私に任せてください。\n騒ぎにならないように、魔法で一気に倒します。
218 = "だったら、私に任せてください。\\n騒ぎにならないように、魔法で一気に倒します。"

# カズマ
# え？　魔法でって……。
203 = "え？　魔法でって……。"

# クリス
# うん、それが一番よさそうだね。
200 = "うん、それが一番よさそうだね。"

# カズマ（Ｍ）
# display as カズマ
# （あ！　そうだった、めぐみんは無理だけど\n　ゆんゆんならできるよな。\n　つい、爆裂魔法を基準に考えちまったぜ）
293 = "（あ！　そうだった、めぐみんは無理だけど\\n　ゆんゆんならできるよな。\\n　つい、爆裂魔法を基準に考えちまったぜ）"

# クリス
# とはいえ、詠唱する時間が必要だよね。\nそこはあたしとカズマでなんとかしよう。
222 = "とはいえ、詠唱する時間が必要だよね。\\nそこはあたしとカズマでなんとかしよう。"

# カズマ
# おう！\nゆんゆん、魔法の準備、頼むぜ！
207 = "おう！\\nゆんゆん、魔法の準備、頼むぜ！"

# ゆんゆん
# はいっ！
228 = "はいっ！"

# クリス
# じゃ、あたしはあいつらをかく乱しに突っ込む。\nカズマはゆんゆんのほうに向かってきたやつを\n確実に足止めして。
211 = "じゃ、あたしはあいつらをかく乱しに突っ込む。\\nカズマはゆんゆんのほうに向かってきたやつを\\n確実に足止めして。"

# カズマ
# お、おいおい！？\nつっこむって、大丈夫なのか？
204 = "お、おいおい！？\\nつっこむって、大丈夫なのか？"

# クリス
# そっちこそ、ちゃんとゆんゆんを守ってよ？
215 = "そっちこそ、ちゃんとゆんゆんを守ってよ？"

# カズマ（Ｍ）
# display as カズマ
# （そう言うやいなや、\n　クリスがマジックダガーを抜いて走り出す）
294 = "（そう言うやいなや、\\n　クリスがマジックダガーを抜いて走り出す）"

# クリス
# ほーら！\nこっちだよーっと！
231 = "ほーら！\\nこっちだよーっと！"

# カズマ（Ｍ）
# display as カズマ
# （そのまま、ひらひらと\n　モンスターをからかうように\n　素早く動き回るクリス）
295 = "（そのまま、ひらひらと\\n　モンスターをからかうように\\n　素早く動き回るクリス）"

# カズマ（Ｍ）
# display as カズマ
# （つか、ホントに早っ！？\n　さすが盗賊、身のこなしが半端ないな！）
296 = "（つか、ホントに早っ！？\\n　さすが盗賊、身のこなしが半端ないな！）"

# ゆんゆん
# クリスさん、カズマさん！\n準備できました！
240 = "クリスさん、カズマさん！\\n準備できました！"

# カズマ
# お、おうっ！\nクリス、戻れ！
205 = "お、おうっ！\\nクリス、戻れ！"

# クリス
# オッケー！
236 = "オッケー！"

# カズマ（Ｍ）
# display as カズマ
# （クリスが身をひるがえしてこっちに来る。\n　それと同時に――）
298 = "（クリスが身をひるがえしてこっちに来る。\\n　それと同時に――）"

# ゆんゆん
# ライト・オブ・セイバーーーッ！
244 = "ライト・オブ・セイバーーーッ！"

# カズマ
# お、おお……！
206 = "お、おお……！"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんが放った光が、俺達に\n　群がろうとしていたモンスターの群れを一閃！\n　すべてを真っ二つにしていた）
297 = "（ゆんゆんが放った光が、俺達に\\n　群がろうとしていたモンスターの群れを一閃！\\n　すべてを真っ二つにしていた）"

# カズマ
# やるなぁ、ゆんゆん！\nこの数を一撃でなんて。
233 = "やるなぁ、ゆんゆん！\\nこの数を一撃でなんて。"

# クリス
# さすがは紅魔族だね。
210 = "さすがは紅魔族だね。"

# ゆんゆん
# いえ、そんな。\nクリスさんとカズマさんが\n時間を稼いでくれたお陰ですから。
198 = "いえ、そんな。\\nクリスさんとカズマさんが\\n時間を稼いでくれたお陰ですから。"

# カズマ（Ｍ）
# display as カズマ
# （俺は何もしてないけどな）
299 = "（俺は何もしてないけどな）"

# ゆんゆん
# えへへ……。\nこういうの、パーティーの戦いっぽくて\nいいですよね。
202 = "えへへ……。\\nこういうの、パーティーの戦いっぽくて\\nいいですよね。"

# クリス
# おっと、喜んでる暇はないよ。\nまたモンスターが来る前に、早くここを離れよう。
208 = "おっと、喜んでる暇はないよ。\\nまたモンスターが来る前に、早くここを離れよう。"

# カズマ
# そうだな、行こう！
213 = "そうだな、行こう！"

