# st04a_02.txt.scn

[info]
0 = ""

[characters]
360 = "カズマ（Ｍ）"
348 = "アクア"
357 = "カズマ"
338 = "めぐみん"
362 = "ダクネス"
352 = "アクア＆めぐみん＆ダクネス"

[character_subs]
# 357 = "カズマ"
459 = "３人"

[script]
# lines: 144

# カズマ（Ｍ）
# display as カズマ
# （……ん？\n　声が聞こえるけど、アクア達か？\n　なにを騒いでるんだ？）
446 = "（……ん？\\n　声が聞こえるけど、アクア達か？\\n　なにを騒いでるんだ？）"

# アクア
# あっ！　カズマ！
254 = "あっ！　カズマ！"

# カズマ
# おう、おはよう。
272 = "おう、おはよう。"

# めぐみん
# よかった、無事みたいですね。
344 = "よかった、無事みたいですね。"

# ダクネス
# 体はなんともないか？\n気分が悪いとか、そういうことはないな？
369 = "体はなんともないか？\\n気分が悪いとか、そういうことはないな？"

# カズマ
# いや、いつも通りだけど。\nてか、何を朝から騒いでるんだ。
261 = "いや、いつも通りだけど。\\nてか、何を朝から騒いでるんだ。"

# ダクネス
# どうやら明け方に\n誰かがこの屋敷に侵入したようなんだ。
323 = "どうやら明け方に\\n誰かがこの屋敷に侵入したようなんだ。"

# カズマ
# はぁ、この金目の物が何ひとつ無い屋敷にか！？
329 = "はぁ、この金目の物が何ひとつ無い屋敷にか！？"

# めぐみん
# 言わないでください、悲しくなるじゃないですか。
444 = "言わないでください、悲しくなるじゃないですか。"

# カズマ
# てか、この屋敷にはアクアが結界を張ってたよな。
316 = "てか、この屋敷にはアクアが結界を張ってたよな。"

# カズマ
# そんな簡単に突破されるなんて、\nお前の結界はどんだけ貧弱なんだ。
304 = "そんな簡単に突破されるなんて、\\nお前の結界はどんだけ貧弱なんだ。"

# アクア
# ちょっと、\nその言い方聞き捨てならないんですけど。
311 = "ちょっと、\\nその言い方聞き捨てならないんですけど。"

# カズマ
# でも事実だろうが。
318 = "でも事実だろうが。"

# ダクネス
# カズマ、話は最後まで聞け。
359 = "カズマ、話は最後まで聞け。"

# めぐみん
# 被害は何もないんですよ。\nおそらく屋敷の中にも侵入されてはいないと\n思うのです。
443 = "被害は何もないんですよ。\\nおそらく屋敷の中にも侵入されてはいないと\\n思うのです。"

# カズマ
# ん？　だったらどうして侵入者がいるって\nわかったんだ？
347 = "ん？　だったらどうして侵入者がいるって\\nわかったんだ？"

# アクア
# 私が張った結界に、\n何者かが引っかかった形跡があったの。
441 = "私が張った結界に、\\n何者かが引っかかった形跡があったの。"

# めぐみん
# 前に引っかかったサキュバスは\n身動きが取れなくなっていたのですが、\n今回は逃げられてしまったようなんです。
374 = "前に引っかかったサキュバスは\\n身動きが取れなくなっていたのですが、\\n今回は逃げられてしまったようなんです。"

# カズマ（Ｍ）
# display as カズマ
# （明け方にねぇ……全然気がつかなかったな）
456 = "（明け方にねぇ……全然気がつかなかったな）"

# カズマ
# てか、逃げてったんなら\n放っておいてもいいだろ。
317 = "てか、逃げてったんなら\\n放っておいてもいいだろ。"

# アクア
# よくないわ！　おかしいじゃない！\nこの私、アクア様の神聖な結界から\n逃げられる存在なんていないはずなのに！
345 = "よくないわ！　おかしいじゃない！\\nこの私、アクア様の神聖な結界から\\n逃げられる存在なんていないはずなのに！"

# カズマ
# いや、でも実際逃げられてるし。
262 = "いや、でも実際逃げられてるし。"

# アクア
# そこはほら、あれよ。\nなんか、こう、網の目をくぐる感じで、\nスポっと抜けられたんじゃないかしら。
293 = "そこはほら、あれよ。\\nなんか、こう、網の目をくぐる感じで、\\nスポっと抜けられたんじゃないかしら。"

# カズマ（Ｍ）
# display as カズマ
# （わけわからん）
452 = "（わけわからん）"

# めぐみん
# ひとまずカズマの無事は確認できたわけです。\n念のため、屋敷の中に異常がないか、\nもう一度確認してみませんか？
332 = "ひとまずカズマの無事は確認できたわけです。\\n念のため、屋敷の中に異常がないか、\\nもう一度確認してみませんか？"

# カズマ
# それもそうだな。\nじゃあ、念のため４人で固まって行こうぜ。
303 = "それもそうだな。\\nじゃあ、念のため４人で固まって行こうぜ。"

# アクア
# う、うん、不審者がまだ隠れてるかも\nしれないもんね。
264 = "う、うん、不審者がまだ隠れてるかも\\nしれないもんね。"

# ダクネス
# みんな安心しろ。\n何者かが飛び出して来たら私が守ってやる。
337 = "みんな安心しろ。\\n何者かが飛び出して来たら私が守ってやる。"

# カズマ
# ああ、肉壁を期待してるぞ。
253 = "ああ、肉壁を期待してるぞ。"

# ダクネス
# にっくぅ！
327 = "にっくぅ！"

# めぐみん
# うーん。\n特におかしな所はなかったですね。
267 = "うーん。\\n特におかしな所はなかったですね。"

# アクア
# やっぱり私の結界にびっくりして\n逃げ出したんじゃないかしら。
340 = "やっぱり私の結界にびっくりして\\n逃げ出したんじゃないかしら。"

# カズマ
# 確かに、そう考えるべきか。\nあのバニルの体をぼろぼろにするくらいの力が\nアクアの結界にはあるんだし。
437 = "確かに、そう考えるべきか。\\nあのバニルの体をぼろぼろにするくらいの力が\\nアクアの結界にはあるんだし。"

# アクア
# それにこの前ウィズにサクッと突破されたから、\nさらに強化したのよ。
301 = "それにこの前ウィズにサクッと突破されたから、\\nさらに強化したのよ。"

# カズマ
# それだと屋敷の中にまで入ってきてるっていうのは\n考えにくいな。
296 = "それだと屋敷の中にまで入ってきてるっていうのは\\n考えにくいな。"

# ダクネス
# だが、突破されていたのは事実なのだろう？
306 = "だが、突破されていたのは事実なのだろう？"

# アクア
# それはそうだけど、\n結界を突破したときのダメージは深刻なはずよ。
302 = "それはそうだけど、\\n結界を突破したときのダメージは深刻なはずよ。"

# アクア
# なんてたって、この前来たサキュバス程度なら、\n一瞬で塵にできるくらい強力なやつなんだから。
325 = "なんてたって、この前来たサキュバス程度なら、\\n一瞬で塵にできるくらい強力なやつなんだから。"

# カズマ
# お前、こわっ！\nそんな結界でこの屋敷を守ってるのかよ。
274 = "お前、こわっ！\\nそんな結界でこの屋敷を守ってるのかよ。"

# アクア
# それくらいやらないと、\n私のプライドが守れないのよ。
295 = "それくらいやらないと、\\n私のプライドが守れないのよ。"

# カズマ
# バニルとウィズにサクッと突破されたのを\nまだ根に持ってんのかよ。
363 = "バニルとウィズにサクッと突破されたのを\\nまだ根に持ってんのかよ。"

# アクア
# サクッとじゃないでしょ。\n害虫の体はぼろぼろにしたし、\nウィズは……。
361 = "サクッとじゃないでしょ。\\n害虫の体はぼろぼろにしたし、\\nウィズは……。"

# カズマ
# ウィズはなんだ、言ってみろ。
354 = "ウィズはなんだ、言ってみろ。"

# アクア
# あの時はあれよ。\n結界のメンテをサボってたから。
256 = "あの時はあれよ。\\n結界のメンテをサボってたから。"

# カズマ
# さっきはこう言ってたよな。\nウィズに楽々通られたから結界を強化したって。
285 = "さっきはこう言ってたよな。\\nウィズに楽々通られたから結界を強化したって。"

# アクア
# と、とにかく、今回の結界は完璧なの！\nそれこそ蟻の子一匹通れないわ。
320 = "と、とにかく、今回の結界は完璧なの！\\nそれこそ蟻の子一匹通れないわ。"

# カズマ（Ｍ）
# display as カズマ
# （普段のダメっぷりに忘れたくなるが\n　こいつは一応、本物の女神なんだよな）
457 = "（普段のダメっぷりに忘れたくなるが\\n　こいつは一応、本物の女神なんだよな）"

# カズマ（Ｍ）
# display as カズマ
# （女神が作った結界から逃れたって\n　確かにそれはおかしい）
455 = "（女神が作った結界から逃れたって\\n　確かにそれはおかしい）"

# カズマ（Ｍ）
# display as カズマ
# （あのバニルでさえ、体が崩れかかるくらい\n　ぼろぼろになったんだ）
447 = "（あのバニルでさえ、体が崩れかかるくらい\\n　ぼろぼろになったんだ）"

# カズマ（Ｍ）
# display as カズマ
# （つまり、魔王軍の元幹部であるバニルと\n　同じくらいの実力者が\n　この屋敷に入ってきたってことなのか？）
448 = "（つまり、魔王軍の元幹部であるバニルと\\n　同じくらいの実力者が\\n　この屋敷に入ってきたってことなのか？）"

# カズマ（Ｍ）
# display as カズマ
# （何それ！　超怖いんだけど！）
454 = "（何それ！　超怖いんだけど！）"

# アクア
# どうやら、カズマも気がついてしまったようね。
322 = "どうやら、カズマも気がついてしまったようね。"

# カズマ
# くっ、やっぱりそうなのか。
282 = "くっ、やっぱりそうなのか。"

# アクア
# ええ。\n私は、絶対に成功するって睨んでいるの。
269 = "ええ。\\n私は、絶対に成功するって睨んでいるの。"

# カズマ（Ｍ）
# display as カズマ
# （は？　成功？）
449 = "（は？　成功？）"

# アクア
# つまり、こうよ。
315 = "つまり、こうよ。"

# アクア
# アクア印の安心セキュリティサービス。\nどんな悪霊からもあなたの大切な家をお守りします！
351 = "アクア印の安心セキュリティサービス。\\nどんな悪霊からもあなたの大切な家をお守りします！"

# アクア
# いまなら、アクシズ教団の崇めるご神体。\nアクア様からのありがたいお言葉つき！
260 = "いまなら、アクシズ教団の崇めるご神体。\\nアクア様からのありがたいお言葉つき！"

# カズマ
# お前は、まだ懲りもせずに\nくだらない勧誘活動をするつもりか！
276 = "お前は、まだ懲りもせずに\\nくだらない勧誘活動をするつもりか！"

# アクア
# 最後のは冗談よ。\nでも、セキュリティサービスっていうのは\nありだと思うのよね。
381 = "最後のは冗談よ。\\nでも、セキュリティサービスっていうのは\\nありだと思うのよね。"

# カズマ
# 確かにいい案だけど、今俺が考えてたことは違う！
438 = "確かにいい案だけど、今俺が考えてたことは違う！"

# めぐみん
# なんです、昨夜盗んだパンツのことでも\n考えていたんですか。
326 = "なんです、昨夜盗んだパンツのことでも\\n考えていたんですか。"

# カズマ
# 参っちゃうよね、今回は４枚なんだもん。\nって、ちがーう！
375 = "参っちゃうよね、今回は４枚なんだもん。\\nって、ちがーう！"

# ダクネス
# よ、４枚も！\nさすが匠の技！
343 = "よ、４枚も！\\nさすが匠の技！"

# カズマ
# こんなこと匠って言われても嬉しくないわ！
284 = "こんなこと匠って言われても嬉しくないわ！"

# アクア
# ねえめぐみん。\n朝食のメニューは何かしら。
328 = "ねえめぐみん。\\n朝食のメニューは何かしら。"

# カズマ
# お前は、不審者のことをさらっと過去のことに\nしてんじゃねーよ！
277 = "お前は、不審者のことをさらっと過去のことに\\nしてんじゃねーよ！"

# めぐみん
# そうですよ。\nパンツを盗んだ不審者の腕を一刻も早く\n爆裂してしまいましょう。
292 = "そうですよ。\\nパンツを盗んだ不審者の腕を一刻も早く\\n爆裂してしまいましょう。"

# カズマ
# って、俺は不審者じゃねーから！\nお前たちの大切な仲間だから！
314 = "って、俺は不審者じゃねーから！\\nお前たちの大切な仲間だから！"

# アクア＆めぐみん＆ダクネス
# display as ３人
# 大切な仲間？
378 = "大切な仲間？"

# カズマ
# やめろ、そういうのは本当に傷つくだろ。
342 = "やめろ、そういうのは本当に傷つくだろ。"

# ダクネス
# す、すまない、ついノリで。
287 = "す、すまない、ついノリで。"

# めぐみん
# それで、いったい何を考えていたんですか。
298 = "それで、いったい何を考えていたんですか。"

# カズマ
# 冷静になって考えてみるとさ、アクアの結界って\n悪魔の体に深刻なダメージを与えるくらいに\n強力なやつだろ。
373 = "冷静になって考えてみるとさ、アクアの結界って\\n悪魔の体に深刻なダメージを与えるくらいに\\n強力なやつだろ。"

# めぐみん
# 確かにそうですね。
439 = "確かにそうですね。"

# カズマ
# しかし昨夜のそいつは、\nそんな結界に引っかかって、無事に逃げおおせた。\nそれってつまり――
286 = "しかし昨夜のそいつは、\\nそんな結界に引っかかって、無事に逃げおおせた。\\nそれってつまり――"

# ダクネス
# バニルと同等、もしくはそれ以上の何者かが\nこの屋敷への侵入を試みたと、そう言いたいのだな。
364 = "バニルと同等、もしくはそれ以上の何者かが\\nこの屋敷への侵入を試みたと、そう言いたいのだな。"

# カズマ
# それってさ、結構やばいことじゃないか？
297 = "それってさ、結構やばいことじゃないか？"

# めぐみん
# そ、そうですね。
288 = "そ、そうですね。"

# アクア
# だ、大丈夫よ！\nなんてたって、私の結界があるんだから！
305 = "だ、大丈夫よ！\\nなんてたって、私の結界があるんだから！"

# カズマ
# へー。
334 = "へー。"

# アクア
# ちょっと、カズマ。\nもしかして私の力を信じてないの！
313 = "ちょっと、カズマ。\\nもしかして私の力を信じてないの！"

# カズマ
# 信じられる要素がないんだが？
371 = "信じられる要素がないんだが？"

# アクア
# あるじゃない！\n私は女神よ！
257 = "あるじゃない！\\n私は女神よ！"

# カズマ
# 他には？
368 = "他には？"

# アクア
# え？
271 = "え？"

# カズマ
# 例えば過去にこういう実績があります、とか。\nそういうの。
370 = "例えば過去にこういう実績があります、とか。\\nそういうの。"

# アクア
# そういうのは、ない……けど。
289 = "そういうのは、ない……けど。"

# カズマ
# だったら信じるのは無理だ、諦めろ。
308 = "だったら信じるのは無理だ、諦めろ。"

# カズマ
# エリス教徒の人に結界を頼むか。
355 = "エリス教徒の人に結界を頼むか。"

# アクア
# ええ！？
270 = "ええ！？"

# ダクネス
# それならば、いい人を紹介できるぞ。
300 = "それならば、いい人を紹介できるぞ。"

# アクア
# ま、待ってよ！\nどうしてよりにもよってエリス教徒なのよ。
336 = "ま、待ってよ！\\nどうしてよりにもよってエリス教徒なのよ。"

# カズマ
# 信頼できるからだけど。
372 = "信頼できるからだけど。"

# アクア
# アクシズ教だって信頼！\nで、できるわよね？
353 = "アクシズ教だって信頼！\\nで、できるわよね？"

# カズマ
# いやいや、ご神体のお前が\n不安に思ってどうするんだ。
263 = "いやいや、ご神体のお前が\\n不安に思ってどうするんだ。"

# カズマ
# お前は仮にも女神なんだし、疑ってはないよ。
279 = "お前は仮にも女神なんだし、疑ってはないよ。"

# アクア
# ふふん、わかればいいのよ。
333 = "ふふん、わかればいいのよ。"

# カズマ（Ｍ）
# display as カズマ
# （仮にもってところは気にならないんだな）
453 = "（仮にもってところは気にならないんだな）"

# ダクネス
# とにかく、もう一度屋敷を調べておくか。
321 = "とにかく、もう一度屋敷を調べておくか。"

# めぐみん
# アクアは結界の張り直しを頼みますよ。
350 = "アクアは結界の張り直しを頼みますよ。"

# アクア
# ええ、任せておいてちょうだい！
268 = "ええ、任せておいてちょうだい！"

# ダクネス
# やはり、何もないようだな。
341 = "やはり、何もないようだな。"

# カズマ
# ああ、なくなった物もないし、\n置き場所が変わってる物もないな。
252 = "ああ、なくなった物もないし、\\n置き場所が変わってる物もないな。"

# めぐみん
# おかしな魔力の痕跡もありませんでしたね。
273 = "おかしな魔力の痕跡もありませんでしたね。"

# カズマ
# そういえばアクアはどうした？\n結界の補修はすぐに終わったんだろ？
290 = "そういえばアクアはどうした？\\n結界の補修はすぐに終わったんだろ？"

# ダクネス
# アクアなら自分の部屋を調べに――
349 = "アクアなら自分の部屋を調べに――"

# アクア
# いいいいいやああああああ！
258 = "いいいいいやああああああ！"

# カズマ
# な、なんだ！
324 = "な、なんだ！"

# ダクネス
# くっ、まさかアクアの部屋に潜んでいたのか！
281 = "くっ、まさかアクアの部屋に潜んでいたのか！"

# アクア
# カズマ、カズマぁぁぁぁぁあああ！！\n大変、大変よ！！
358 = "カズマ、カズマぁぁぁぁぁあああ！！\\n大変、大変よ！！"

# カズマ
# よし、まずは酒瓶を持ってる理由を\n簡潔に説明してくれ！
346 = "よし、まずは酒瓶を持ってる理由を\\n簡潔に説明してくれ！"

# アクア
# ベッドの下に隠しておいた、\n私の秘蔵のお酒の量が減ってるのよ。
365 = "ベッドの下に隠しておいた、\\n私の秘蔵のお酒の量が減ってるのよ。"

# カズマ
# はい、みんな撤収。
331 = "はい、みんな撤収。"

# アクア
# ちょっと、どうしてそんな人ごとなのよ！
312 = "ちょっと、どうしてそんな人ごとなのよ！"

# カズマ
# だって、酒がどこまで残ってたか俺知らねえし、\n酒を飲んだ後のお前の記憶も信用できねえもん。
309 = "だって、酒がどこまで残ってたか俺知らねえし、\\n酒を飲んだ後のお前の記憶も信用できねえもん。"

# アクア
# 本当に減ってるのよ。\n私が前に飲んだときは、ラベルのちょっと上まで\nあったんだから。
382 = "本当に減ってるのよ。\\n私が前に飲んだときは、ラベルのちょっと上まで\\nあったんだから。"

# カズマ
# うん、それが今は？
266 = "うん、それが今は？"

# アクア
# ラベルのほんのちょっと上までしかないの！
366 = "ラベルのほんのちょっと上までしかないの！"

# カズマ
# 気化したんだろう。
383 = "気化したんだろう。"

# めぐみん
# 気化したんでしょうね。
385 = "気化したんでしょうね。"

# ダクネス
# 気化したんだろうな。
384 = "気化したんだろうな。"

# アクア
# ええ！？
# 270 = "ええ！？"

# カズマ
# もしくは記憶違いのどちらかだ。
339 = "もしくは記憶違いのどちらかだ。"

# アクア
# いいえ、これは間違いなく侵入者の仕業よ！\nそしてそんなことをできるのは、\n１人、いえ、１匹しかいないわ！
259 = "いいえ、これは間違いなく侵入者の仕業よ！\\nそしてそんなことをできるのは、\\n１人、いえ、１匹しかいないわ！"

# カズマ（Ｍ）
# display as カズマ
# （まさか……）
450 = "（まさか……）"

# アクア
# あの害虫は、きっとこの私の力に恐れをなして\n闇討ちに来たのよ！
255 = "あの害虫は、きっとこの私の力に恐れをなして\\n闇討ちに来たのよ！"

# アクア
# でも偶然、この銘酒をみつけてしまった。
319 = "でも偶然、この銘酒をみつけてしまった。"

# カズマ
# それでお前を討つのを忘れて、\n舐める程度の量の酒を飲んだと？
299 = "それでお前を討つのを忘れて、\\n舐める程度の量の酒を飲んだと？"

# アクア
# その通りよ！
294 = "その通りよ！"

# めぐみん
# 色々破綻していますが、\n突っ込んだ方がいいんですかね。
442 = "色々破綻していますが、\\n突っ込んだ方がいいんですかね。"

# カズマ
# 面倒だからいい。\n放っておけ。
445 = "面倒だからいい。\\n放っておけ。"

# アクア
# 私、ちょっと出かけてくる。
440 = "私、ちょっと出かけてくる。"

# カズマ
# ちょっ、待て待て待て！\nまさかバニルの所に行くんじゃないだろうな！
310 = "ちょっ、待て待て待て！\\nまさかバニルの所に行くんじゃないだろうな！"

# アクア
# お酒が、私に飲まれたかったって、泣いているのよ。
280 = "お酒が、私に飲まれたかったって、泣いているのよ。"

# カズマ
# お前とバニルがやりあったら大事になるだろうが！\n少しは頭を使え、この駄女神っ！
275 = "お前とバニルがやりあったら大事になるだろうが！\\n少しは頭を使え、この駄女神っ！"

# アクア
# うぅ、なによ。\nカズマはあの害虫の肩を持つの。
265 = "うぅ、なによ。\\nカズマはあの害虫の肩を持つの。"

# カズマ
# そうじゃなくて。\nバニルがやったって証拠がないだろ。
291 = "そうじゃなくて。\\nバニルがやったって証拠がないだろ。"

# アクア
# だったらその証拠を探しに行きましょう！
307 = "だったらその証拠を探しに行きましょう！"

# めぐみん
# これは止められませんよ、カズマ。
283 = "これは止められませんよ、カズマ。"

# アクア
# ほら、ちゃっちゃと行くわよ！
335 = "ほら、ちゃっちゃと行くわよ！"

# カズマ
# はあ、わかった、わかったよ。
330 = "はあ、わかった、わかったよ。"

# カズマ（Ｍ）
# display as カズマ
# （まず間違いなくバニルじゃないだろうが、\n　あいつの見通す力で詳しいことが\n　わかるかもしれない）
451 = "（まず間違いなくバニルじゃないだろうが、\\n　あいつの見通す力で詳しいことが\\n　わかるかもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （行って損はないだろうし、\n　ここは付き合ってやるか）
458 = "（行って損はないだろうし、\\n　ここは付き合ってやるか）"

[selections]
# 371 = "信じられる要素がないんだが？"
356 = "エリス教徒の人に頼むか"
278 = "お前は仮にも女神なんだし……"
