# st04c_03.txt.scn

[info]
0 = ""

[characters]
193 = "ゆんゆん"
191 = "めぐみん"
197 = "カズマ"
199 = "カズマ（Ｍ）"
201 = "クリス"
194 = "アクア"
196 = "ウィズ"
203 = "ダクネス"

[character_subs]
# 197 = "カズマ"

[script]
# lines: 56

# ゆんゆん
# 気をつけてくださいね。
216 = "気をつけてくださいね。"

# めぐみん
# 安心してください。\nいざとなれば、爆裂魔法で\nあのドラゴンを吹き飛ばしますから。
211 = "安心してください。\\nいざとなれば、爆裂魔法で\\nあのドラゴンを吹き飛ばしますから。"

# カズマ
# やめろ、マジでやめろ。\nなんのために俺とクリスが体を張ると思ってんだ。
192 = "やめろ、マジでやめろ。\\nなんのために俺とクリスが体を張ると思ってんだ。"

# カズマ（Ｍ）
# display as カズマ
# （俺達は、スカルドラゴンがいる場所まで\n　やってきていた）
253 = "（俺達は、スカルドラゴンがいる場所まで\\n　やってきていた）"

# カズマ（Ｍ）
# display as カズマ
# （隠れながら見えるわずかな範囲には、\n　出口らしきものは見当たらない）
255 = "（隠れながら見えるわずかな範囲には、\\n　出口らしきものは見当たらない）"

# カズマ（Ｍ）
# display as カズマ
# （だから俺とクリスが潜伏スキルを使い、\n　スカルドラゴンに近づいて\n　確認することになったわけだが……）
250 = "（だから俺とクリスが潜伏スキルを使い、\\n　スカルドラゴンに近づいて\\n　確認することになったわけだが……）"

# カズマ
# なあ、本当に大丈夫なんだよな？\n見つかったりしないよな？
186 = "なあ、本当に大丈夫なんだよな？\\n見つかったりしないよな？"

# クリス
# 大丈夫。\n盗賊のスキルはこういう時のために\nあるんだからね？
208 = "大丈夫。\\n盗賊のスキルはこういう時のために\\nあるんだからね？"

# クリス
# 大声を出すとか、そんな初歩的なドジを\n踏まなければ見つからないよ。
209 = "大声を出すとか、そんな初歩的なドジを\\n踏まなければ見つからないよ。"

# クリス
# じゃ、行こう。
176 = "じゃ、行こう。"

# カズマ
# お、おう。
171 = "お、おう。"

# カズマ（Ｍ）
# display as カズマ
# （うおおお……。\n　すぐ近くにドラゴンがいる……）
247 = "（うおおお……。\\n　すぐ近くにドラゴンがいる……）"

# カズマ（Ｍ）
# display as カズマ
# （生きた心地がしねーってのは\n　こういうことを言うんだな）
254 = "（生きた心地がしねーってのは\\n　こういうことを言うんだな）"

# カズマ（Ｍ）
# display as カズマ
# （つか、この状況で周りを探れとか\n　どんな無茶振りだよ！\n　俺には無理だっ！）
251 = "（つか、この状況で周りを探れとか\\n　どんな無茶振りだよ！\\n　俺には無理だっ！）"

# カズマ（Ｍ）
# display as カズマ
# （頼むから気がつかないでくれよ？\n　こんなところで死にたくねー！）
256 = "（頼むから気がつかないでくれよ？\\n　こんなところで死にたくねー！）"

# クリス
# ねえ、キミ。
189 = "ねえ、キミ。"

# カズマ
# ！？！？！？！？！？！
244 = "！？！？！？！？！？！"

# クリス
# ちょっ！\n声出しちゃダメだって！
182 = "ちょっ！\\n声出しちゃダメだって！"

# カズマ
# むぐぐ！？
190 = "むぐぐ！？"

# カズマ（Ｍ）
# display as カズマ
# （あ、危ねぇ！\n　クリスが口を押さえてくれなきゃ、\n　大声上げるところだった！）
245 = "（あ、危ねぇ！\\n　クリスが口を押さえてくれなきゃ、\\n　大声上げるところだった！）"

# クリス
# 驚かしちゃった？\nごめん。\nでも、ほら、あれを見てほしくて。
242 = "驚かしちゃった？\\nごめん。\\nでも、ほら、あれを見てほしくて。"

# カズマ（Ｍ）
# display as カズマ
# （クリスが指さした先、\n　スカルドラゴンの向こう側を見ると……）
252 = "（クリスが指さした先、\\n　スカルドラゴンの向こう側を見ると……）"

# カズマ
# あっ！\nあれってもしかして通路か？
167 = "あっ！\\nあれってもしかして通路か？"

# クリス
# だね。\nやっぱり、洞窟から出る道は\nあったってことだよ。
181 = "だね。\\nやっぱり、洞窟から出る道は\\nあったってことだよ。"

# カズマ（Ｍ）
# display as カズマ
# （あったけど、これは……\n　どうやってあそこまで行けばいいんだ？）
246 = "（あったけど、これは……\\n　どうやってあそこまで行けばいいんだ？）"

# クリス
# キミ、考えるのは後だよ。\n先に報告に行こう。
200 = "キミ、考えるのは後だよ。\\n先に報告に行こう。"

# ゆんゆん
# お帰りなさい、クリスさん、カズマさん！
173 = "お帰りなさい、クリスさん、カズマさん！"

# アクア
# どうだった？\nなにかあった？
184 = "どうだった？\\nなにかあった？"

# カズマ
# ああ、あったぜ。\nスカルドラゴンの向こうに、先に続く通路がな。
165 = "ああ、あったぜ。\\nスカルドラゴンの向こうに、先に続く通路がな。"

# ゆんゆん
# え？\nドラゴンの向こうって……。
170 = "え？\\nドラゴンの向こうって……。"

# クリス
# どうにかしてスカルドラゴンをやり過ごさないと、\n通路に入れそうにないんだ。
185 = "どうにかしてスカルドラゴンをやり過ごさないと、\\n通路に入れそうにないんだ。"

# ウィズ
# それは……困りましたね。
180 = "それは……困りましたね。"

# カズマ
# アクア、話は聞いたな？\nこうなったら浄化するしかないだろ？
195 = "アクア、話は聞いたな？\\nこうなったら浄化するしかないだろ？"

# アクア
# 嫌よ。
210 = "嫌よ。"

# カズマ
# こっ、この駄女神！\nどこまで強欲なんだっ！
174 = "こっ、この駄女神！\\nどこまで強欲なんだっ！"

# アクア
# 強欲なわけじゃないわ。\nタダ働きが嫌なの。
214 = "強欲なわけじゃないわ。\\nタダ働きが嫌なの。"

# ダクネス
# カズマ、諦めろ。\nアクアが折れない以上、\n他の方法を考えるしかない。
198 = "カズマ、諦めろ。\\nアクアが折れない以上、\\n他の方法を考えるしかない。"

# クリス
# 他の方法って言っても、なにかある？
205 = "他の方法って言っても、なにかある？"

# ウィズ
# スカルドラゴンをうまくおびき出して、\n移動させるのはどうでしょう？
202 = "スカルドラゴンをうまくおびき出して、\\n移動させるのはどうでしょう？"

# カズマ
# 誰かが囮役になるのか？\nいや、それは命の保証ができないぞ？
241 = "誰かが囮役になるのか？\\nいや、それは命の保証ができないぞ？"

# クリス
# それに、こんな狭い洞窟じゃ\n移動させるのも難しいよ。
179 = "それに、こんな狭い洞窟じゃ\\n移動させるのも難しいよ。"

# カズマ（Ｍ）
# display as カズマ
# （うーん、こういう場合、\n　ゲームでよくあるパターンだと――）
248 = "（うーん、こういう場合、\\n　ゲームでよくあるパターンだと――）"

# カズマ
# そうだ、あのドラゴンを\n深く眠らせることはできないか？\nそういうアイテムとか魔法でさ。
177 = "そうだ、あのドラゴンを\\n深く眠らせることはできないか？\\nそういうアイテムとか魔法でさ。"

# クリス
# 正直、あの巨体に\n普通の眠り薬や魔法が効くとは思えないね。
215 = "正直、あの巨体に\\n普通の眠り薬や魔法が効くとは思えないね。"

# ゆんゆん
# というか、相手は骨ですよね？\n眠ることってあるんでしょうか？
183 = "というか、相手は骨ですよね？\\n眠ることってあるんでしょうか？"

# カズマ
# いや、寝てるって！\n心地よさそうな寝息が聞こえたし！
168 = "いや、寝てるって！\\n心地よさそうな寝息が聞こえたし！"

# ダクネス
# 骨も疲れるのか。
243 = "骨も疲れるのか。"

# めぐみん
# 肉がない分、体力にも乏しいのかもしれませんね。
240 = "肉がない分、体力にも乏しいのかもしれませんね。"

# カズマ（Ｍ）
# display as カズマ
# （こんな会話を真面目にしているのが悲しい……）
249 = "（こんな会話を真面目にしているのが悲しい……）"

# クリス
# うーん、となると、やっぱり潜伏スキルかな？
169 = "うーん、となると、やっぱり潜伏スキルかな？"

# クリス
# あたしとキミで潜伏スキルを使って、\nみんなで固まってスカルドラゴンの横を\nこっそり通る――
166 = "あたしとキミで潜伏スキルを使って、\\nみんなで固まってスカルドラゴンの横を\\nこっそり通る――"

# クリス
# これが確実だと思う。
175 = "これが確実だと思う。"

# カズマ
# そうなるかぁ。
178 = "そうなるかぁ。"

# アクア
# なんだ、考えるまでもないじゃない。\nそれで行きましょ。
187 = "なんだ、考えるまでもないじゃない。\\nそれで行きましょ。"

# カズマ
# おい、アクア。\nお前はここに置いていっていいか？
172 = "おい、アクア。\\nお前はここに置いていっていいか？"

# アクア
# なんでよ！？
188 = "なんでよ！？"

