# st04b_05.txt.scn

[info]
0 = ""

[characters]
237 = "カズマ（Ｍ）"
227 = "ゆんゆん"
236 = "カズマ"
241 = "クリス"

[character_subs]
# 236 = "カズマ"

[script]
# lines: 85

# カズマ（Ｍ）
# display as カズマ
# （森を抜けてすぐ、\n　俺達は目的の洞窟を発見した）
293 = "（森を抜けてすぐ、\\n　俺達は目的の洞窟を発見した）"

# カズマ（Ｍ）
# display as カズマ
# （さっそく中に入って少し――\n　今、クリスが先に進んで\n　おかしな点がないか調べてくれてる）
287 = "（さっそく中に入って少し――\\n　今、クリスが先に進んで\\n　おかしな点がないか調べてくれてる）"

# カズマ（Ｍ）
# display as カズマ
# （つーか、ここまでクリス様々って感じだよな。\n　やっぱり、報酬は少しでも渡したほうが\n　いいよなぁ）
289 = "（つーか、ここまでクリス様々って感じだよな。\\n　やっぱり、報酬は少しでも渡したほうが\\n　いいよなぁ）"

# ゆんゆん
# クリスさん、大丈夫でしょうか？
243 = "クリスさん、大丈夫でしょうか？"

# カズマ
# 場慣れしてるから大丈夫だろ、多分。\nそれに、さっきの罠のこともあって\n改めて気を引き締めるって言ってしたし。
249 = "場慣れしてるから大丈夫だろ、多分。\\nそれに、さっきの罠のこともあって\\n改めて気を引き締めるって言ってしたし。"

# ゆんゆん
# はい……。
220 = "はい……。"

# カズマ（Ｍ）
# display as カズマ
# （俺の言葉を聞いても、ゆんゆんは心配そうに\n　クリスが消えていった洞窟の奥を見続けている）
292 = "（俺の言葉を聞いても、ゆんゆんは心配そうに\\n　クリスが消えていった洞窟の奥を見続けている）"

# カズマ（Ｍ）
# display as カズマ
# （すっかりクリスのことを\n　仲間だって思ってる感じだ。\n　もちろん、それは俺も同じなんだけど）
288 = "（すっかりクリスのことを\\n　仲間だって思ってる感じだ。\\n　もちろん、それは俺も同じなんだけど）"

# クリス
# お待たせ。
189 = "お待たせ。"

# ゆんゆん
# あ、クリスさん！\nお帰りなさい！
177 = "あ、クリスさん！\\nお帰りなさい！"

# カズマ
# お疲れ。\n大丈夫か？　ケガとかしてないか？
190 = "お疲れ。\\n大丈夫か？　ケガとかしてないか？"

# クリス
# 平気、平気。\nただの偵察だもん、ケガをする理由もないよ。
254 = "平気、平気。\\nただの偵察だもん、ケガをする理由もないよ。"

# クリス
# それじゃ、調べたことを報告するね。\n見たところ、目立って不審な点はないかな。
204 = "それじゃ、調べたことを報告するね。\\n見たところ、目立って不審な点はないかな。"

# クリス
# 当然、財宝を隠した痕跡もなし。
255 = "当然、財宝を隠した痕跡もなし。"

# カズマ
# ちょっと期待してたんだけど、\nこんな浅い場所に隠すわけないか。
210 = "ちょっと期待してたんだけど、\\nこんな浅い場所に隠すわけないか。"

# クリス
# それと、魔物の気配もなかったよ。\nねぐらにしている形跡もなし。
205 = "それと、魔物の気配もなかったよ。\\nねぐらにしている形跡もなし。"

# ゆんゆん
# それじゃ、奥に行ったら\nいきなり大物に遭遇、なんてことはないんですね。
202 = "それじゃ、奥に行ったら\\nいきなり大物に遭遇、なんてことはないんですね。"

# クリス
# うーん、でもね。
184 = "うーん、でもね。"

# カズマ
# どうした？\nなにか問題があったのか？
214 = "どうした？\\nなにか問題があったのか？"

# クリス
# ええとね……。
186 = "ええとね……。"

# ゆんゆん
# ？？\n私がどうかしましたか。
295 = "？？\\n私がどうかしましたか。"

# クリス
# ちょっと同情しちゃうなって。
209 = "ちょっと同情しちゃうなって。"

# ゆんゆん
# え？　え？\n私になにかあるんですか？
187 = "え？　え？\\n私になにかあるんですか？"

# クリス
# 進めばわかるよ。
286 = "進めばわかるよ。"

# ゆんゆん
# はあ……。
219 = "はあ……。"

# カズマ
# ああ、進めばわかるってこれか。
179 = "ああ、進めばわかるってこれか。"

# クリス
# うん、これ。
183 = "うん、これ。"

# ゆんゆん
# これって……行き止まりですか？
195 = "これって……行き止まりですか？"

# クリス
# それがそうじゃないんだよね。
201 = "それがそうじゃないんだよね。"

# カズマ
# よく見てみろ。\n足元のここの部分、隙間があるだろ？\n多分、これが奥に繋がってるんだ。
231 = "よく見てみろ。\\n足元のここの部分、隙間があるだろ？\\n多分、これが奥に繋がってるんだ。"

# ゆんゆん
# こ、これがですか？\nすごく狭いですけど……。
193 = "こ、これがですか？\\nすごく狭いですけど……。"

# カズマ
# ギルドのお姉さんが言ってたんだよ。\nこの洞窟は通路がとても狭くなってるって。
240 = "ギルドのお姉さんが言ってたんだよ。\\nこの洞窟は通路がとても狭くなってるって。"

# クリス
# まさか、ここまで狭いとはね。\n確かにダクネスじゃ、相当、苦労しそう。
225 = "まさか、ここまで狭いとはね。\\n確かにダクネスじゃ、相当、苦労しそう。"

# カズマ
# ダクネスじゃなくてもキツいぞ。\n四つん這いでないと進めそうにないな。
245 = "ダクネスじゃなくてもキツいぞ。\\n四つん這いでないと進めそうにないな。"

# ゆんゆん
# よよよ、四つん這い！？
232 = "よよよ、四つん這い！？"

# クリス
# ゆんゆんに同情するって意味がわかった？
230 = "ゆんゆんに同情するって意味がわかった？"

# カズマ
# はっ！！\nそうだよ！　あなたはスカートですよ！？
221 = "はっ！！\\nそうだよ！　あなたはスカートですよ！？"

# ゆんゆん
# ひいいっ！？
223 = "ひいいっ！？"

# クリス
# キミ、それは思っても口に出さないのが\n紳士ってものじゃない？
238 = "キミ、それは思っても口に出さないのが\\n紳士ってものじゃない？"

# カズマ
# そう、俺は紳士だから進む順番も平等に決めるさ！\nじゃんけんで！
197 = "そう、俺は紳士だから進む順番も平等に決めるさ！\\nじゃんけんで！"

# ゆんゆん
# 嫌ですっ！\nぜーったいに！　嫌です！
251 = "嫌ですっ！\\nぜーったいに！　嫌です！"

# カズマ
# ゆんゆん、俺は真の男女平等主義者だ。\nゆえに、ここでも平等に\nじゃんけんで決めるべきだと提案する。
228 = "ゆんゆん、俺は真の男女平等主義者だ。\\nゆえに、ここでも平等に\\nじゃんけんで決めるべきだと提案する。"

# ゆんゆん
# な、何を言われても譲りません！\n私は最後でお願いします！\nそうじゃないと、奥には行きませんからっ！
215 = "な、何を言われても譲りません！\\n私は最後でお願いします！\\nそうじゃないと、奥には行きませんからっ！"

# クリス
# ちょっと、２人とも。\n言い合っても決着つかないって。
208 = "ちょっと、２人とも。\\n言い合っても決着つかないって。"

# ゆんゆん
# で、でも、私、最後じゃないと嫌ですから！\nカズマさんの前なんて絶対に嫌ですからー！
212 = "で、でも、私、最後じゃないと嫌ですから！\\nカズマさんの前なんて絶対に嫌ですからー！"

# クリス
# それじゃ、話し合いにならないよ。\nそれにあたしも、できることなら最後が\nいいんだけど……。
203 = "それじゃ、話し合いにならないよ。\\nそれにあたしも、できることなら最後が\\nいいんだけど……。"

# カズマ
# は？　クリスもか？
222 = "は？　クリスもか？"

# カズマ
# クリスはスカートじゃないし、\n最後じゃなくてもいいだろ？\nそれに、しんがりって危険じゃね？
244 = "クリスはスカートじゃないし、\\n最後じゃなくてもいいだろ？\\nそれに、しんがりって危険じゃね？"

# クリス
# それは撤退の時だよ。\nとにかく、あたしもキミの前は絶対に嫌だからね？
206 = "それは撤退の時だよ。\\nとにかく、あたしもキミの前は絶対に嫌だからね？"

# ゆんゆん
# 私も嫌です！\n最後がいいですっ！
283 = "私も嫌です！\\n最後がいいですっ！"

# カズマ（Ｍ）
# display as カズマ
# （はあ……。\n　これじゃ話が進まないな）
290 = "（はあ……。\\n　これじゃ話が進まないな）"

# カズマ（Ｍ）
# display as カズマ
# （男女平等主義しては非常に不本意だが仕方ない。\n　ここは俺が折れておくか）
294 = "（男女平等主義しては非常に不本意だが仕方ない。\\n　ここは俺が折れておくか）"

# カズマ
# わかった。\nじゃあ、俺が先頭を行くから、\n２人の順番は任せる。
233 = "わかった。\\nじゃあ、俺が先頭を行くから、\\n２人の順番は任せる。"

# クリス
# キミが先に？\nうーん、だったらあたしはその次でいいよ。
239 = "キミが先に？\\nうーん、だったらあたしはその次でいいよ。"

# ゆんゆん
# じゃあ！　私が最後で！
196 = "じゃあ！　私が最後で！"

# カズマ
# 決まりだな。\n行こうぜ。
257 = "決まりだな。\\n行こうぜ。"

# カズマ
# うう……。\nマジで狭いな……。
181 = "うう……。\\nマジで狭いな……。"

# クリス
# 大丈夫？　進めそう？
250 = "大丈夫？　進めそう？"

# カズマ
# ああ、つっかかったりすることはなさそうだ。\nでも服がかなり汚れるな、これ。
178 = "ああ、つっかかったりすることはなさそうだ。\\nでも服がかなり汚れるな、これ。"

# クリス
# そこは我慢だね。
199 = "そこは我慢だね。"

# ゆんゆん
# うう……。
180 = "うう……。"

# カズマ
# ゆんゆん、大丈夫か？
229 = "ゆんゆん、大丈夫か？"

# クリス
# ちょっと！？\n後ろを見ようとしないでよっ！
211 = "ちょっと！？\\n後ろを見ようとしないでよっ！"

# ゆんゆん
# 見ないでください！\n絶対に振り返らないでください！
284 = "見ないでください！\\n絶対に振り返らないでください！"

# カズマ
# この状況で振り返るなんで無理だし。\nそれに、なんでそんなに嫌がるんだよ。\n前からなら見たって問題ないだろ？
194 = "この状況で振り返るなんで無理だし。\\nそれに、なんでそんなに嫌がるんだよ。\\n前からなら見たって問題ないだろ？"

# クリス
# そうだとしても、四つん這いなんて\n恥ずかしいポーズを男の子に見られたくないの！
198 = "そうだとしても、四つん這いなんて\\n恥ずかしいポーズを男の子に見られたくないの！"

# カズマ（Ｍ）
# display as カズマ
# （はあ、そういうもんか。\n　女の子って、気を使うポイントが\n　たくさんあるもんなんだな）
291 = "（はあ、そういうもんか。\\n　女の子って、気を使うポイントが\\n　たくさんあるもんなんだな）"

# クリス
# ん？\nねえ、なにか音がしなかった？
235 = "ん？\\nねえ、なにか音がしなかった？"

# カズマ
# お、おわっ！\nちょ、ちょっと待て、なんだこれ！？
188 = "お、おわっ！\\nちょ、ちょっと待て、なんだこれ！？"

# ゆんゆん
# どうしたんですか！？
213 = "どうしたんですか！？"

# カズマ
# 通路に穴が開いた！\nいや、今も穴が広がって、\nこっちに迫ってきて――
285 = "通路に穴が開いた！\\nいや、今も穴が広がって、\\nこっちに迫ってきて――"

# カズマ
# まずい！　落とし穴だっ！
226 = "まずい！　落とし穴だっ！"

# ゆんゆん
# ええええ！？
185 = "ええええ！？"

# カズマ
# クリス、ゆんゆん、後退だ後退！！
242 = "クリス、ゆんゆん、後退だ後退！！"

# クリス
# 後退って！　この順番で反転したら！
256 = "後退って！　この順番で反転したら！"

# ゆんゆん
# そそそ、それは絶対にダメです！！
200 = "そそそ、それは絶対にダメです！！"

# カズマ
# なんで！
218 = "なんで！"

# ゆんゆん
# なんででもです！
217 = "なんででもです！"

# クリス
# なんででもだよ！
216 = "なんででもだよ！"

# カズマ
# わけわかんねーよ！\nてか、急がないと！！
234 = "わけわかんねーよ！\\nてか、急がないと！！"

# クリス
# うわ！　穴が！
182 = "うわ！　穴が！"

# ゆんゆん
# きゃぁ！！　このままだと！
191 = "きゃぁ！！　このままだと！"

# カズマ
# だから落ちるって言っただろ！！
207 = "だから落ちるって言っただろ！！"

# クリス
# ひゃあああああ！？
224 = "ひゃあああああ！？"

# ゆんゆん
# きゃあああああーーっ！
192 = "きゃあああああーーっ！"

