# st04b_08.txt.scn

[info]
0 = ""

[characters]
138 = "カズマ"
137 = "ゆんゆん"
139 = "クリス"

[character_subs]

[script]
# lines: 20

# カズマ
# この先だよな？\n俺達が落っこちてきたところって。
128 = "この先だよな？\\n俺達が落っこちてきたところって。"

# ゆんゆん
# はい、間違いないです。
136 = "はい、間違いないです。"

# クリス
# それじゃ、そっと様子を見てみよう。\nなにがあるかわからないし、慎重にね。
131 = "それじゃ、そっと様子を見てみよう。\\nなにがあるかわからないし、慎重にね。"

# カズマ
# 誰もいないな。
160 = "誰もいないな。"

# ゆんゆん
# 見た感じ、さっきと変わりありませんね。
159 = "見た感じ、さっきと変わりありませんね。"

# カズマ
# うん、特に妙な気配もないみたいだな。\nクリスはどう思う？
123 = "うん、特に妙な気配もないみたいだな。\\nクリスはどう思う？"

# クリス
# うーん……。
124 = "うーん……。"

# ゆんゆん
# なにか気になりますか？
135 = "なにか気になりますか？"

# クリス
# うん、ちょっとね。\n少し調べてみるよ。
122 = "うん、ちょっとね。\\n少し調べてみるよ。"

# カズマ
# どうだ、クリス。\n何か見つかったか？
134 = "どうだ、クリス。\\n何か見つかったか？"

# クリス
# ううん、何も。\nあたし達以外の誰かがここに来た痕跡もないみたい。
121 = "ううん、何も。\\nあたし達以外の誰かがここに来た痕跡もないみたい。"

# ゆんゆん
# じゃあ、さっきのは\nなにかが落ちてきた音じゃ\nなかったんでしょうか？
130 = "じゃあ、さっきのは\\nなにかが落ちてきた音じゃ\\nなかったんでしょうか？"

# カズマ
# ああ、そうなるよな。
120 = "ああ、そうなるよな。"

# クリス
# うーん、でも引っかかるんだよね。\nうまく言えないんだけど、\nここに不思議な気配が漂ってるんだよ。
125 = "うーん、でも引っかかるんだよね。\\nうまく言えないんだけど、\\nここに不思議な気配が漂ってるんだよ。"

# クリス
# しかも、なんだか覚えがあるような\n気がするんだ。
129 = "しかも、なんだか覚えがあるような\\n気がするんだ。"

# カズマ
# お、おい、怖いこと言わないでくれよ！\nこんな洞窟の中でホラー展開なんて勘弁してくれ！
126 = "お、おい、怖いこと言わないでくれよ！\\nこんな洞窟の中でホラー展開なんて勘弁してくれ！"

# ゆんゆん
# そんな風に言われると、私もなんだか\n背筋がぞくぞくして……。
132 = "そんな風に言われると、私もなんだか\\n背筋がぞくぞくして……。"

# クリス
# ああ、ごめん。\n脅かすつもりはなかったんだけど。
119 = "ああ、ごめん。\\n脅かすつもりはなかったんだけど。"

# クリス
# とにかく、先に進もうか。
133 = "とにかく、先に進もうか。"

# カズマ
# お、おう。
127 = "お、おう。"

