# st04a_09.txt.scn

[info]
0 = ""

[characters]
203 = "カズマ"
205 = "クリス"
207 = "ダクネス"
202 = "アクア"
199 = "ゆんゆん"
198 = "めぐみん"
204 = "カズマ（Ｍ）"

[character_subs]
# 203 = "カズマ"

[script]
# lines: 43

# カズマ
# おーい、クリスー！
174 = "おーい、クリスー！"

# クリス
# ああ、戻ってきたんだ。\nゆんゆんもいるってことは……話がついたの？
169 = "ああ、戻ってきたんだ。\\nゆんゆんもいるってことは……話がついたの？"

# カズマ
# ああ、一緒に行ってくれるってさ。
168 = "ああ、一緒に行ってくれるってさ。"

# クリス
# う……そうなんだ。
171 = "う……そうなんだ。"

# ダクネス
# どうだ？\nこれならクリスも安心だろ？
191 = "どうだ？\\nこれならクリスも安心だろ？"

# クリス
# そうだね。\n考えてみるって約束しちゃったし、\nここで断ったらゆんゆんが困っちゃうか。
182 = "そうだね。\\n考えてみるって約束しちゃったし、\\nここで断ったらゆんゆんが困っちゃうか。"

# クリス
# わかったよ。\nあたしも一緒に行く。
201 = "わかったよ。\\nあたしも一緒に行く。"

# カズマ
# ありがとうっ！\n助かるよ、クリス！
170 = "ありがとうっ！\\n助かるよ、クリス！"

# アクア
# これで３人ね。\nパーティーのバランスも悪くないし、\n充分なんじゃないかしら。
175 = "これで３人ね。\\nパーティーのバランスも悪くないし、\\n充分なんじゃないかしら。"

# ダクネス
# 盗賊のクリス、\n中級から上級までの魔法を使えるゆんゆん、\n小回りの利くカズマ――
218 = "盗賊のクリス、\\n中級から上級までの魔法を使えるゆんゆん、\\n小回りの利くカズマ――"

# ダクネス
# うむ、洞窟の調査には適しているな。
172 = "うむ、洞窟の調査には適しているな。"

# クリス
# でも、ダクネスみたいな前衛がいないから\n大物の魔物が出てきた時、\nちょっとまずそうだけどね。
190 = "でも、ダクネスみたいな前衛がいないから\\n大物の魔物が出てきた時、\\nちょっとまずそうだけどね。"

# カズマ
# その時は、ゆんゆんの魔法で目くらましして\n逃げればいいだろ。
183 = "その時は、ゆんゆんの魔法で目くらましして\\n逃げればいいだろ。"

# ゆんゆん
# はいっ！\n任せてください！
194 = "はいっ！\\n任せてください！"

# カズマ
# さて！\nそれじゃ、２人の取り分について\nちゃんと話しておくか。
177 = "さて！\\nそれじゃ、２人の取り分について\\nちゃんと話しておくか。"

# クリス
# 取り分？
210 = "取り分？"

# アクア
# ちょっと！？\nあんた、まさか話す気なの！？
188 = "ちょっと！？\\nあんた、まさか話す気なの！？"

# カズマ
# 当然だろ。\n洞窟調査だって危険がないわけじゃない。\nそこについてきてくれるんだからさ。
216 = "当然だろ。\\n洞窟調査だって危険がないわけじゃない。\\nそこについてきてくれるんだからさ。"

# アクア
# そ、そうだけどぉ……。
179 = "そ、そうだけどぉ……。"

# クリス
# ねえ、取り分って？\nクエスト報酬のこと？
192 = "ねえ、取り分って？\\nクエスト報酬のこと？"

# カズマ
# それもなんだけど、実はな――
184 = "それもなんだけど、実はな――"

# クリス
# 財宝が眠ってるんだ！\nそれは、聞き捨てならない話だよ。
249 = "財宝が眠ってるんだ！\\nそれは、聞き捨てならない話だよ。"

# ゆんゆん
# ビックリです。\nそんな場所がこの街の近くにあったなんて。
208 = "ビックリです。\\nそんな場所がこの街の近くにあったなんて。"

# カズマ
# まあ、あくまで見つけた財宝によっては\n報酬が出るかもってレベルの話だけどさ。
197 = "まあ、あくまで見つけた財宝によっては\\n報酬が出るかもってレベルの話だけどさ。"

# カズマ
# でも、あとでゴタゴタするのも嫌だし、\n先に報酬の取り分を決めておきたいんだよ。
189 = "でも、あとでゴタゴタするのも嫌だし、\\n先に報酬の取り分を決めておきたいんだよ。"

# クリス
# うーん。
173 = "うーん。"

# カズマ
# クリス？
206 = "クリス？"

# クリス
# さっき言ったこととは矛盾するけどさ、\nあたし、報酬はいいや。
176 = "さっき言ったこととは矛盾するけどさ、\\nあたし、報酬はいいや。"

# カズマ
# はあっ！？\nいらないのか？
193 = "はあっ！？\\nいらないのか？"

# クリス
# だって、あたしが受け取ったら\nキミ達の取り分が減っちゃうよね。
187 = "だって、あたしが受け取ったら\\nキミ達の取り分が減っちゃうよね。"

# クリス
# 呪いが解けるまで、\nますます時間がかかることになるわけじゃない。\nそれはキミとしては困るでしょ？
213 = "呪いが解けるまで、\\nますます時間がかかることになるわけじゃない。\\nそれはキミとしては困るでしょ？"

# クリス
# そ、それにさ？\nパンツを盗まれるなんてことから\n早く解放されたいんだよね。
181 = "そ、それにさ？\\nパンツを盗まれるなんてことから\\n早く解放されたいんだよね。"

# ゆんゆん
# そ、そうです！\nだから私も、報酬は必要ありません。
180 = "そ、そうです！\\nだから私も、報酬は必要ありません。"

# カズマ
# ゆんゆん、クリス……！\nありがとう、本当にありがとうっ！
200 = "ゆんゆん、クリス……！\\nありがとう、本当にありがとうっ！"

# ダクネス
# ふふ、私は本当にいい友人を持ったよ。
195 = "ふふ、私は本当にいい友人を持ったよ。"

# クリス
# そんな言い方やめてよ。\n恥ずかしくなるじゃない。
185 = "そんな言い方やめてよ。\\n恥ずかしくなるじゃない。"

# ゆんゆん
# じー……。
178 = "じー……。"

# めぐみん
# ……言いませんからね？
167 = "……言いませんからね？"

# ゆんゆん
# べべ、別に、期待なんかしてないよ！？\n何を勘違いしてるの、めぐみん！
196 = "べべ、別に、期待なんかしてないよ！？\\n何を勘違いしてるの、めぐみん！"

# アクア
# だったら、なんの心配もないわ。\n私達の代わりに、ちゃんと財宝を見つけてきて。\nついでにカズマのサポートもね。
186 = "だったら、なんの心配もないわ。\\n私達の代わりに、ちゃんと財宝を見つけてきて。\\nついでにカズマのサポートもね。"

# カズマ（Ｍ）
# display as カズマ
# （こ、この駄女神に、２人の爪の垢を\n　煎じて飲ませてやりたいっ！）
250 = "（こ、この駄女神に、２人の爪の垢を\\n　煎じて飲ませてやりたいっ！）"

# カズマ（Ｍ）
# display as カズマ
# （にしても、呪いのせいとはいえ、\n　こんなことを言わせるくらいに\n　迷惑をかけてんだよな、俺……）
252 = "（にしても、呪いのせいとはいえ、\\n　こんなことを言わせるくらいに\\n　迷惑をかけてんだよな、俺……）"

# カズマ（Ｍ）
# display as カズマ
# （ここは一刻も早く呪いを解かないと。\n　そのためにも、このクエストは\n　絶対に成功させるんだ！）
251 = "（ここは一刻も早く呪いを解かないと。\\n　そのためにも、このクエストは\\n　絶対に成功させるんだ！）"

