# st04a_06.txt.scn

[info]
0 = ""

[characters]
251 = "カズマ"
248 = "アクア"
257 = "ルナ"
255 = "ダクネス"
244 = "めぐみん"
253 = "カズマ（Ｍ）"

[character_subs]
# 251 = "カズマ"

[script]
# lines: 87

# カズマ
# それじゃ、さっそく洞窟調査の計画を立てるぞ！
219 = "それじゃ、さっそく洞窟調査の計画を立てるぞ！"

# アクア
# 財宝を持ち出すとなると、馬車とか必要かしら？\n少なくとも荷車は必要よね。\nダクネスとカズマに押してもらえばなんとか……。
314 = "財宝を持ち出すとなると、馬車とか必要かしら？\\n少なくとも荷車は必要よね。\\nダクネスとカズマに押してもらえばなんとか……。"

# カズマ
# もう持ち出す心配かよ。\n第一、財宝自体はギルド側が管理するんだし\n俺達は調べるだけだぞ？
245 = "もう持ち出す心配かよ。\\n第一、財宝自体はギルド側が管理するんだし\\n俺達は調べるだけだぞ？"

# アクア
# ふふん、甘いわねカズマ。\nさっさと持ち出しちゃえばこっちのものじゃない。
241 = "ふふん、甘いわねカズマ。\\nさっさと持ち出しちゃえばこっちのものじゃない。"

# アクア
# たとえ全部持ち出せなくても、\n一部でも頂いちゃえば\nこっちの取り分が多くなるわ。
222 = "たとえ全部持ち出せなくても、\\n一部でも頂いちゃえば\\nこっちの取り分が多くなるわ。"

# ルナ
# あの？\nここで聞いていますので、\n滅多なことは口に出さないで頂けますと。
198 = "あの？\\nここで聞いていますので、\\n滅多なことは口に出さないで頂けますと。"

# カズマ
# このバカ！\nせっかくのチャンスを棒に振る気かよ！\n真面目にやれ！
211 = "このバカ！\\nせっかくのチャンスを棒に振る気かよ！\\n真面目にやれ！"

# アクア
# 私はいつだって真面目で本気よ。
308 = "私はいつだって真面目で本気よ。"

# カズマ
# だったらなお、質が悪いわ！
224 = "だったらなお、質が悪いわ！"

# ダクネス
# 財宝も目的ではあるが、\nなによりも全員が無事に生還することが大切だ。
312 = "財宝も目的ではあるが、\\nなによりも全員が無事に生還することが大切だ。"

# ダクネス
# 調査として派遣される――\nつまり、我々が初めて\n洞窟の奥に踏み込むのだからな。
311 = "調査として派遣される――\\nつまり、我々が初めて\\n洞窟の奥に踏み込むのだからな。"

# ルナ
# はい、そうです。\nギルド側では、まだ洞窟の\nごく浅いところまでしか調査していません。
240 = "はい、そうです。\\nギルド側では、まだ洞窟の\\nごく浅いところまでしか調査していません。"

# めぐみん
# むむ……。\nでは、未知のモンスターが\n潜んでいる可能性もあるのですか？
243 = "むむ……。\\nでは、未知のモンスターが\\n潜んでいる可能性もあるのですか？"

# ルナ
# そうですね。\nゼロとは言えませんが……\nしかし、確率は低いと思います。
213 = "そうですね。\\nゼロとは言えませんが……\\nしかし、確率は低いと思います。"

# ルナ
# もし未知のモンスターが潜んでいるのなら、\n根城にするわけがありませんし。
246 = "もし未知のモンスターが潜んでいるのなら、\\n根城にするわけがありませんし。"

# ダクネス
# となると、この辺りで見かけるモンスターが\nいるかもしれない、くらいの備えでいいのか？
233 = "となると、この辺りで見かけるモンスターが\\nいるかもしれない、くらいの備えでいいのか？"

# カズマ
# ああ、それでいいだろ。\nただしアクア、お前は留守番だ。
195 = "ああ、それでいいだろ。\\nただしアクア、お前は留守番だ。"

# アクア
# ええっ！？　なんでよ！\nちゃんと真面目にやるって言ったでしょ！？\nポケットに入るくらいしか持ち出さないから――
206 = "ええっ！？　なんでよ！\\nちゃんと真面目にやるって言ったでしょ！？\\nポケットに入るくらいしか持ち出さないから――"

# ルナ
# …………。
193 = "…………。"

# アクア
# う、ううん、財宝には指一本触れない！\n女神アクアの名に誓うわ！
204 = "う、ううん、財宝には指一本触れない！\\n女神アクアの名に誓うわ！"

# ルナ
# アクア様の名に……ですか。
249 = "アクア様の名に……ですか。"

# アクア
# な、なによ！\nなんでそんな顔するのよ！
236 = "な、なによ！\\nなんでそんな顔するのよ！"

# カズマ（Ｍ）
# display as カズマ
# （この駄女神アクアを崇めるアクシズ教は\n　頭のおかしい人が多いって評判だ。\n　まあ、そんな女神に誓われても困るよな）
317 = "（この駄女神アクアを崇めるアクシズ教は\\n　頭のおかしい人が多いって評判だ。\\n　まあ、そんな女神に誓われても困るよな）"

# めぐみん
# 安心してください。\nアクアがおかしな行動を取ったら、\n私達が全力で止めます。
263 = "安心してください。\\nアクアがおかしな行動を取ったら、\\n私達が全力で止めます。"

# カズマ
# つか、連れてかねーって言ってるだろ。
226 = "つか、連れてかねーって言ってるだろ。"

# アクア
# だから、なんでよ！
223 = "だから、なんでよ！"

# カズマ
# 忘れたのか？\nお前を連れてダンジョンに行ったら――
267 = "忘れたのか？\\nお前を連れてダンジョンに行ったら――"

# カズマ
# アンデッドモンスターが寄ってきて\n大変なことになるだろ。
250 = "アンデッドモンスターが寄ってきて\\n大変なことになるだろ。"

# カズマ（Ｍ）
# display as カズマ
# （そう、こいつは腐っても女神だ）
318 = "（そう、こいつは腐っても女神だ）"

# カズマ（Ｍ）
# display as カズマ
# （洞窟に潜んでいる幽霊などの\n　アンデッドモンスターは、\n　女神の浄化能力を求めて近寄ってくる）
326 = "（洞窟に潜んでいる幽霊などの\\n　アンデッドモンスターは、\\n　女神の浄化能力を求めて近寄ってくる）"

# カズマ（Ｍ）
# display as カズマ
# （アクアがいると、それだけで\n　アンデッドモンスターとの遭遇率が上がるのだ）
322 = "（アクアがいると、それだけで\\n　アンデッドモンスターとの遭遇率が上がるのだ）"

# カズマ（Ｍ）
# display as カズマ
# （その分、無駄な戦いをして消耗すれば、\n　いざって時に動けない、なんてことに\n　なりかねない）
320 = "（その分、無駄な戦いをして消耗すれば、\\n　いざって時に動けない、なんてことに\\n　なりかねない）"

# アクア
# 確かに、そうだけど……でも財宝が……。
307 = "確かに、そうだけど……でも財宝が……。"

# カズマ
# 財宝を取りに行くわけじゃない。\nあくまで調査なんだって。
313 = "財宝を取りに行くわけじゃない。\\nあくまで調査なんだって。"

# アクア
# うう……。
205 = "うう……。"

# カズマ
# おい、返事は？
209 = "おい、返事は？"

# アクア
# ……絶対に財宝を独り占めしないでよ？
194 = "……絶対に財宝を独り占めしないでよ？"

# カズマ
# 調査だって何度言えばわかるんだよ！
310 = "調査だって何度言えばわかるんだよ！"

# めぐみん
# では、アクアは留守番ですか。
229 = "では、アクアは留守番ですか。"

# カズマ
# ああ、めぐみん、お前もだ。
196 = "ああ、めぐみん、お前もだ。"

# めぐみん
# まあ、そうなりますよね。\n洞窟で爆裂魔法は使えませんし、\n足手まといになってしまいますから。
242 = "まあ、そうなりますよね。\\n洞窟で爆裂魔法は使えませんし、\\n足手まといになってしまいますから。"

# カズマ（Ｍ）
# display as カズマ
# （凄まじい破壊力を誇る爆裂魔法を\n　洞窟の中で使ったら、\n　その場に生き埋めになって終わりだ）
324 = "（凄まじい破壊力を誇る爆裂魔法を\\n　洞窟の中で使ったら、\\n　その場に生き埋めになって終わりだ）"

# カズマ（Ｍ）
# display as カズマ
# （それ以外の魔法を使えないめぐみんは、\n　自然とメンバーから外れることになるわけだ）
321 = "（それ以外の魔法を使えないめぐみんは、\\n　自然とメンバーから外れることになるわけだ）"

# ダクネス
# では、私とカズマの２人で行くことになるのか。\n……カズマと２人とは、危機を感じるな。
230 = "では、私とカズマの２人で行くことになるのか。\\n……カズマと２人とは、危機を感じるな。"

# カズマ
# いや、その必要はまったくないから。
200 = "いや、その必要はまったくないから。"

# ルナ
# いえ、待ってください。\nダクネスさんも、洞窟に入るのは難しいかと。
199 = "いえ、待ってください。\\nダクネスさんも、洞窟に入るのは難しいかと。"

# ダクネス
# なに？　どういうことだ？
238 = "なに？　どういうことだ？"

# ルナ
# ギルドで調査した範囲で確認されたのですが、\n洞窟は非常に狭い部分があるんです。
254 = "ギルドで調査した範囲で確認されたのですが、\\n洞窟は非常に狭い部分があるんです。"

# ルナ
# ですので、鎧で身を固めたクルセイダーでは\n通行できないかもしれません。
228 = "ですので、鎧で身を固めたクルセイダーでは\\n通行できないかもしれません。"

# カズマ
# マジですか。\nじゃあ、ダクネスもダメか。
256 = "マジですか。\\nじゃあ、ダクネスもダメか。"

# ダクネス
# なにを言う！\n私は鎧なしでも構わないぞ！　むしろ大歓迎だっ！
237 = "なにを言う！\\n私は鎧なしでも構わないぞ！　むしろ大歓迎だっ！"

# カズマ
# いやいや、いくらお前が丈夫でも\n鎧なしは危険すぎる。\n連れて行けない。
202 = "いやいや、いくらお前が丈夫でも\\n鎧なしは危険すぎる。\\n連れて行けない。"

# ダクネス
# そ、そうか。\n鎧を通さず魔物の一撃を堪能するのも\nいいかと思ったんだが。
212 = "そ、そうか。\\n鎧を通さず魔物の一撃を堪能するのも\\nいいかと思ったんだが。"

# カズマ（Ｍ）
# display as カズマ
# （そういうのは別の機会にやってくれ。\n　俺に関わらないところで）
319 = "（そういうのは別の機会にやってくれ。\\n　俺に関わらないところで）"

# アクア
# となると、カズマ１人で洞窟に行くってこと？
234 = "となると、カズマ１人で洞窟に行くってこと？"

# ダクネス
# 待て、それこそ危険だろう！\nカズマには大した攻撃方法もないんだぞ？
266 = "待て、それこそ危険だろう！\\nカズマには大した攻撃方法もないんだぞ？"

# めぐみん
# そうですよ。\nカズマ１人では、\n洞窟の入り口にもたどり着けませんよ。
214 = "そうですよ。\\nカズマ１人では、\\n洞窟の入り口にもたどり着けませんよ。"

# カズマ（Ｍ）
# display as カズマ
# （心配してくれるのは嬉しいけど！\n　なんだか、ものすごくバカにされてる気がする！）
325 = "（心配してくれるのは嬉しいけど！\\n　なんだか、ものすごくバカにされてる気がする！）"

# ルナ
# でしたら、臨時で他の方と\nパーティーを組まれてはいかがでしょう？
227 = "でしたら、臨時で他の方と\\nパーティーを組まれてはいかがでしょう？"

# カズマ
# 他の奴？\nダストやキースとか？
260 = "他の奴？\\nダストやキースとか？"

# アクア
# それはダメ！　絶対ダメ！
221 = "それはダメ！　絶対ダメ！"

# ルナ
# え？　どうしてです？
208 = "え？　どうしてです？"

# アクア
# だって、どうして組むのか\n説明しなくちゃならないでしょ？\n財宝のことがバレちゃうじゃない！
225 = "だって、どうして組むのか\\n説明しなくちゃならないでしょ？\\n財宝のことがバレちゃうじゃない！"

# カズマ
# いや、財宝のことは伏せて\n頼んでもいいんじゃないか？\n単なる洞窟の調査だって言うんだよ。
201 = "いや、財宝のことは伏せて\\n頼んでもいいんじゃないか？\\n単なる洞窟の調査だって言うんだよ。"

# アクア
# でも、財宝が見つかったら同じことでしょ？
232 = "でも、財宝が見つかったら同じことでしょ？"

# アクア
# %fsyogen;それで取り分を要求されたら、\n私の分が減っちゃうわ！\n絶対に嫌よ！
17 = "%fsyogen;それで取り分を要求されたら、\\n私の分が減っちゃうわ！\\n絶対に嫌よ！"

# カズマ（Ｍ）
# display as カズマ
# （今、私の分って言いやがったぞ、こいつ）
323 = "（今、私の分って言いやがったぞ、こいつ）"

# カズマ（Ｍ）
# display as カズマ
# （こいつが金にうるさいのは前からだ。\n　しかし今回はいつもよりも\n　執着しているように思える）
316 = "（こいつが金にうるさいのは前からだ。\\n　しかし今回はいつもよりも\\n　執着しているように思える）"

# カズマ（Ｍ）
# display as カズマ
# （……念のため証言として押さえておくか）
315 = "（……念のため証言として押さえておくか）"

# めぐみん
# そもそも、このクエストのことは\n別の冒険者には黙っておいたほうがいいです。
217 = "そもそも、このクエストのことは\\n別の冒険者には黙っておいたほうがいいです。"

# めぐみん
# 一緒に行動しているうちに、\nなにかボロが出てしまうかもしれませんよ。
258 = "一緒に行動しているうちに、\\nなにかボロが出てしまうかもしれませんよ。"

# ルナ
# 確かに……そうですね。\nすみません、少し気が急いてしまったようです。
306 = "確かに……そうですね。\\nすみません、少し気が急いてしまったようです。"

# ダクネス
# となると、事情を知った上で\n協力してくれる人を頼るしかないな。
235 = "となると、事情を知った上で\\n協力してくれる人を頼るしかないな。"

# カズマ
# それって、ゆんゆんと\nクリスくらいしかいなくね？
220 = "それって、ゆんゆんと\\nクリスくらいしかいなくね？"

# めぐみん
# う……。\nまたゆんゆんですか。
203 = "う……。\\nまたゆんゆんですか。"

# アクア
# そうね、あの２人なら、報酬の分け前なしでも\n協力してくれるんじゃないかしら？
215 = "そうね、あの２人なら、報酬の分け前なしでも\\n協力してくれるんじゃないかしら？"

# カズマ
# お前はなにを言ってるんだ。\n協力してもらうからには、ある程度は渡すべきだろ。
210 = "お前はなにを言ってるんだ。\\n協力してもらうからには、ある程度は渡すべきだろ。"

# アクア
# カズマ、やっぱり１人で行きなさい。
252 = "カズマ、やっぱり１人で行きなさい。"

# カズマ
# 無茶言うなっ！\nとにかく、俺はゆんゆんとクリスを\n捜しに行ってくる。
269 = "無茶言うなっ！\\nとにかく、俺はゆんゆんとクリスを\\n捜しに行ってくる。"

# ダクネス
# では、私も行こう。\nクリスの居場所なら見当がつく。
231 = "では、私も行こう。\\nクリスの居場所なら見当がつく。"

# めぐみん
# 私も行きますよ。\nゆんゆんの首を縦に振らせるのは得意ですから。
309 = "私も行きますよ。\\nゆんゆんの首を縦に振らせるのは得意ですから。"

# カズマ
# その言い方、物騒だからやめろ。
216 = "その言い方、物騒だからやめろ。"

# アクア
# えー？　協力してもらうのー？
207 = "えー？　協力してもらうのー？"

# ダクネス
# そもそも、カズマがこのクエストを\n無事にこなさなければ、\n報酬さえ手に入らないんだぞ？
218 = "そもそも、カズマがこのクエストを\\n無事にこなさなければ、\\n報酬さえ手に入らないんだぞ？"

# アクア
# はあ……。\nわかったわよ、行きましょ。
239 = "はあ……。\\nわかったわよ、行きましょ。"

# カズマ
# んじゃ、まずはクリスから行くか。\nダクネス、案内頼むわ。
247 = "んじゃ、まずはクリスから行くか。\\nダクネス、案内頼むわ。"

# ダクネス
# ああ、任せてくれ。
197 = "ああ、任せてくれ。"

