# st04c_04.txt.scn

[info]
0 = ""

[characters]
374 = "カズマ（Ｍ）"
348 = "めぐみん"
352 = "ゆんゆん"
370 = "カズマ"
387 = "ダクネス"
376 = "クリス"
359 = "アクア"
365 = "ウィズ"
384 = "スカルドラゴン"

[character_subs]
# 370 = "カズマ"

[script]
# lines: 139

# カズマ（Ｍ）
# display as カズマ
# （今の俺達の状況は、\n　端から見ればかなり面白いと思う）
477 = "（今の俺達の状況は、\\n　端から見ればかなり面白いと思う）"

# カズマ（Ｍ）
# display as カズマ
# （全員が黙りこくったまま、\n　ひとかたまりになってじりじりと進んでいく）
478 = "（全員が黙りこくったまま、\\n　ひとかたまりになってじりじりと進んでいく）"

# カズマ（Ｍ）
# display as カズマ
# （しかも、この上なく必死な顔に\n　なっていることも間違いない）
464 = "（しかも、この上なく必死な顔に\\n　なっていることも間違いない）"

# カズマ（Ｍ）
# display as カズマ
# （想像していたら……\n　命懸けの状況だってのに、\n　なんだか笑えてきたぞ？）
479 = "（想像していたら……\\n　命懸けの状況だってのに、\\n　なんだか笑えてきたぞ？）"

# カズマ（Ｍ）
# display as カズマ
# （もしかして、俺、緊張しすぎて\n　おかしくなってるのかもしれない）
472 = "（もしかして、俺、緊張しすぎて\\n　おかしくなってるのかもしれない）"

# めぐみん
# ふ、ふふ、ふふふふ……。
340 = "ふ、ふふ、ふふふふ……。"

# ゆんゆん
# めぐみん？\nどうしたの？
349 = "めぐみん？\\nどうしたの？"

# めぐみん
# いえ、なんだか、この状況が\n面白く感じられてきてしまって。
286 = "いえ、なんだか、この状況が\\n面白く感じられてきてしまって。"

# カズマ
# 気持ちはなんとなくわかるけどさ、\n見つかったらヤバいんだ。\n我慢しろ。
403 = "気持ちはなんとなくわかるけどさ、\\n見つかったらヤバいんだ。\\n我慢しろ。"

# めぐみん
# わ、わかっていますが……く、くくく……。
355 = "わ、わかっていますが……く、くくく……。"

# ゆんゆん
# ふふふっ！
342 = "ふふふっ！"

# カズマ
# おい、ゆんゆんまで。
298 = "おい、ゆんゆんまで。"

# ゆんゆん
# すみません、めぐみんにつられちゃって。\nふふふふっ。
313 = "すみません、めぐみんにつられちゃって。\\nふふふふっ。"

# ダクネス
# ふ、ふふふふふふ。
341 = "ふ、ふふふふふふ。"

# カズマ
# ダクネスまで！？
388 = "ダクネスまで！？"

# ダクネス
# いや、つい想像してしまってな。\nこのままスカルドラゴンに見つかって、\n蹂躙される姿を……。
288 = "いや、つい想像してしまってな。\\nこのままスカルドラゴンに見つかって、\\n蹂躙される姿を……。"

# カズマ
# やめろ、不吉な想像をするな。
351 = "やめろ、不吉な想像をするな。"

# クリス
# みんな、おしゃべりしすぎ。\n静かにして。
346 = "みんな、おしゃべりしすぎ。\\n静かにして。"

# ゆんゆん
# は、はい。\nすみません。
332 = "は、はい。\\nすみません。"

# めぐみん
# …………。
277 = "…………。"

# ゆんゆん
# …………。
# 277 = "…………。"

# めぐみん
# ……ぷっ！
278 = "……ぷっ！"

# カズマ（Ｍ）
# display as カズマ
# （おいっ！\n　めぐみん、なに笑ってるんだ！？）
461 = "（おいっ！\\n　めぐみん、なに笑ってるんだ！？）"

# カズマ（Ｍ）
# display as カズマ
# （と、焦った俺は、とっさに\n　めぐみんの口を塞いで……）
468 = "（と、焦った俺は、とっさに\\n　めぐみんの口を塞いで……）"

# めぐみん
# んー！？　んー！　んー！
358 = "んー！？　んー！　んー！"

# カズマ
# いいか、めぐみん。\n笑うのは禁止だ。\nわかったな？　絶対だぞ？
285 = "いいか、めぐみん。\\n笑うのは禁止だ。\\nわかったな？　絶対だぞ？"

# めぐみん
# んっ！
357 = "んっ！"

# カズマ
# よし。
353 = "よし。"

# めぐみん
# ぷはっ！\nな、なにするんですかいきなり！\nこれはセクハラですよ、後で訴えます！
343 = "ぷはっ！\\nな、なにするんですかいきなり！\\nこれはセクハラですよ、後で訴えます！"

# カズマ
# なんで！？\n今のはむしろ俺のファインプレイだろ！
331 = "なんで！？\\n今のはむしろ俺のファインプレイだろ！"

# クリス
# だから、静かにってば。
322 = "だから、静かにってば。"

# カズマ
# う……。\nす、すまん。
289 = "う……。\\nす、すまん。"

# クリス
# じゃ、進むよ。\n足元に気をつけてね。
311 = "じゃ、進むよ。\\n足元に気をつけてね。"

# アクア
# わきゃっ！？
356 = "わきゃっ！？"

# カズマ（Ｍ）
# display as カズマ
# （って、言ってるそばからつまづくなよ、\n　この駄女神！！）
467 = "（って、言ってるそばからつまづくなよ、\\n　この駄女神！！）"

# カズマ
# 大丈夫か、アクア。\n気をつけろよ。
398 = "大丈夫か、アクア。\\n気をつけろよ。"

# アクア
# カズマ。\nいま、触ったわね。
372 = "カズマ。\\nいま、触ったわね。"

# アクア
# どさくさにまぎれて\nなにしてくれてんのよ。
328 = "どさくさにまぎれて\\nなにしてくれてんのよ。"

# カズマ
# お前の自意識過剰だ。\n第一、助けてもらったってのに\n礼のひとつも言えないのか。
302 = "お前の自意識過剰だ。\\n第一、助けてもらったってのに\\n礼のひとつも言えないのか。"

# アクア
# 助けられたつもりはないんですけどー？
395 = "助けられたつもりはないんですけどー？"

# クリス
# だから、ね？\n静かにしよう？
320 = "だから、ね？\\n静かにしよう？"

# クリス
# はあ……。\nみんな、緊張感なさ過ぎだよ。\n見つかったらどうするつもりなの？
335 = "はあ……。\\nみんな、緊張感なさ過ぎだよ。\\n見つかったらどうするつもりなの？"

# ダクネス
# その時は私が盾になって時間を稼ぐ。\n他の皆は、あの通路に走って逃げてくれ。
316 = "その時は私が盾になって時間を稼ぐ。\\n他の皆は、あの通路に走って逃げてくれ。"

# クリス
# そんな事態には絶対させないから。\nだよね、みんな？
319 = "そんな事態には絶対させないから。\\nだよね、みんな？"

# カズマ
# お、おう。\nそうだな、もっと慎重に行こうぜ。
295 = "お、おう。\\nそうだな、もっと慎重に行こうぜ。"

# カズマ（Ｍ）
# display as カズマ
# （ゆっくりゆっくり、\n　これでもかってほど慎重に進み――）
473 = "（ゆっくりゆっくり、\\n　これでもかってほど慎重に進み――）"

# カズマ（Ｍ）
# display as カズマ
# （気がつけば、あれほど遠くに感じた\n　通路の入り口がすぐ近くになっていた）
480 = "（気がつけば、あれほど遠くに感じた\\n　通路の入り口がすぐ近くになっていた）"

# カズマ（Ｍ）
# display as カズマ
# （スカルドラゴンが\n　こっちに気がついた様子はない）
475 = "（スカルドラゴンが\\n　こっちに気がついた様子はない）"

# カズマ（Ｍ）
# display as カズマ
# （よしっ！\n　これなら行ける！）
474 = "（よしっ！\\n　これなら行ける！）"

# カズマ
# はっ？\nな、なんだ！？
337 = "はっ？\\nな、なんだ！？"

# クリス
# なに、この光？\nどこから！？
329 = "なに、この光？\\nどこから！？"

# めぐみん
# カズマ！\n指輪が光ってます！
373 = "カズマ！\\n指輪が光ってます！"

# カズマ
# うわっ！？　マジだ！\nなんでだよ、こんな時に！
293 = "うわっ！？　マジだ！\\nなんでだよ、こんな時に！"

# アクア
# ちょ、ちょ、ちょっと！？\nなんとかしなさいよ、気がつかれるでしょ！？
324 = "ちょ、ちょ、ちょっと！？\\nなんとかしなさいよ、気がつかれるでしょ！？"

# カズマ（Ｍ）
# display as カズマ
# （なんとかって言われても！\n　どうして光ってるのかもわかんねーのに！）
471 = "（なんとかって言われても！\\n　どうして光ってるのかもわかんねーのに！）"

# ウィズ
# アクア様！\nそんな大声を出したら見つかってしまいます。
362 = "アクア様！\\nそんな大声を出したら見つかってしまいます。"

# スカルドラゴン
# グルル……。
380 = "グルル……。"

# アクア
# ひいっ！？
339 = "ひいっ！？"

# ゆんゆん
# ああっ！\nスカルドラゴンが反応してますよ！？
281 = "ああっ！\\nスカルドラゴンが反応してますよ！？"

# スカルドラゴン
# グルルルル……！
381 = "グルルルル……！"

# アクア
# きゃああああああ！\nこ、こ、こっち見たあああああ！
304 = "きゃああああああ！\\nこ、こ、こっち見たあああああ！"

# ウィズ
# これは、完全に見つかりましたね。
309 = "これは、完全に見つかりましたね。"

# カズマ
# アクアっ！\nお前は本当に、いちいちトラブルを起こさないと\n気が済まないのか！？
361 = "アクアっ！\\nお前は本当に、いちいちトラブルを起こさないと\\n気が済まないのか！？"

# アクア
# いまのはカズマのせいでしょ！\nなんで指輪光らせたのよ～！
287 = "いまのはカズマのせいでしょ！\\nなんで指輪光らせたのよ～！"

# カズマ
# 俺がやったんじゃねーよ！\n勝手に光ったんだ！
393 = "俺がやったんじゃねーよ！\\n勝手に光ったんだ！"

# クリス
# 言い合ってる場合じゃないよ！
459 = "言い合ってる場合じゃないよ！"

# カズマ（Ｍ）
# display as カズマ
# （そうだよ、どうする？\n　こうなったら戦うしかないか！？）
465 = "（そうだよ、どうする？\\n　こうなったら戦うしかないか！？）"

# ゆんゆん
# ええーいっ！！
294 = "ええーいっ！！"

# スカルドラゴン
# グガッ！？
378 = "グガッ！？"

# ゆんゆん
# ウィズさんっ！
368 = "ウィズさんっ！"

# ウィズ
# あ、なるほど！　わかりました！\nたあっ！
279 = "あ、なるほど！　わかりました！\\nたあっ！"

# スカルドラゴン
# ググググググ……。
379 = "ググググググ……。"

# カズマ（Ｍ）
# display as カズマ
# （な、なんだ？\n　スカルドラゴンの動きが止まった？）
470 = "（な、なんだ？\\n　スカルドラゴンの動きが止まった？）"

# ゆんゆん
# ううううう～っ！
292 = "ううううう～っ！"

# ウィズ
# くうっ……。
307 = "くうっ……。"

# カズマ
# ウィズ、ゆんゆん？\n何してるんだ？
367 = "ウィズ、ゆんゆん？\\n何してるんだ？"

# めぐみん
# そうか！\n束縛魔法で、スカルドラゴンの動きを\n止めてるんですよ！
315 = "そうか！\\n束縛魔法で、スカルドラゴンの動きを\\n止めてるんですよ！"

# カズマ
# そんなことできんの！\n本物のアークウィザードすげー！
318 = "そんなことできんの！\\n本物のアークウィザードすげー！"

# めぐみん
# それ、どういう意味ですか。
317 = "それ、どういう意味ですか。"

# ゆんゆん
# ちょ、長時間の拘束は無理です！
325 = "ちょ、長時間の拘束は無理です！"

# ウィズ
# 今も２人がかりでギリギリで……！
392 = "今も２人がかりでギリギリで……！"

# カズマ（Ｍ）
# display as カズマ
# （だったら、この隙になんとかしないと！）
466 = "（だったら、この隙になんとかしないと！）"

# カズマ
# アクア！　浄化魔法だ！\nもう懸賞金にこだわってる場合じゃないだろ！
364 = "アクア！　浄化魔法だ！\\nもう懸賞金にこだわってる場合じゃないだろ！"

# アクア
# 絶対に嫌よ！\nここまで来てタダ働きなんて冗談じゃないわ！
458 = "絶対に嫌よ！\\nここまで来てタダ働きなんて冗談じゃないわ！"

# ダクネス
# おい、アクア！？\n待て！
299 = "おい、アクア！？\\n待て！"

# カズマ（Ｍ）
# display as カズマ
# （マジかよ、逃げやがった！\n　こ、こ、この、駄女神中の駄女神がぁ！）
476 = "（マジかよ、逃げやがった！\\n　こ、こ、この、駄女神中の駄女神がぁ！）"

# めぐみん
# カズマ、アクアはもうダメです！\nここは爆裂魔法で吹き飛ばしましょう！\nええ、そうしましょう！
371 = "カズマ、アクアはもうダメです！\\nここは爆裂魔法で吹き飛ばしましょう！\\nええ、そうしましょう！"

# カズマ
# って、さくっと眼帯装備してんじゃねーよ！\nそれこそダメに決まってんだろが！
327 = "って、さくっと眼帯装備してんじゃねーよ！\\nそれこそダメに決まってんだろが！"

# ダクネス
# やはりここは私が壁になってだな。
350 = "やはりここは私が壁になってだな。"

# カズマ
# こんな状況で寒い冗談言ってんじゃねー！
310 = "こんな状況で寒い冗談言ってんじゃねー！"

# ダクネス
# じょ、冗談ではない！　私は本気だ！
312 = "じょ、冗談ではない！　私は本気だ！"

# カズマ
# あー、もうっ、クリス！\nアクアを捕まえてくれ！
284 = "あー、もうっ、クリス！\\nアクアを捕まえてくれ！"

# クリス
# オッケー！\n盗賊のスピードから\n逃げられると思わないでよねっ！
369 = "オッケー！\\n盗賊のスピードから\\n逃げられると思わないでよねっ！"

# アクア
# きゃあっ！？
306 = "きゃあっ！？"

# アクア
# は、離してよぉ～っ！\n私はもう帰るの～！
334 = "は、離してよぉ～っ！\\n私はもう帰るの～！"

# クリス
# １人だけ先に帰るのはなしでしょ？\nパーティーは一蓮托生なんだからね？
481 = "１人だけ先に帰るのはなしでしょ？\\nパーティーは一蓮托生なんだからね？"

# カズマ
# アクア。\nお前、本当にいい加減にしろよ？\nここで逃げるとか、人として終わってるだろ！
360 = "アクア。\\nお前、本当にいい加減にしろよ？\\nここで逃げるとか、人として終わってるだろ！"

# アクア
# 私は女神なんですけどー？
457 = "私は女神なんですけどー？"

# カズマ
# 屁理屈こねてんじゃねーよ！\nとにかく、逃げられると思うなよ？\n助かりたいのなら、さっさと浄化魔法を使え！！
399 = "屁理屈こねてんじゃねーよ！\\nとにかく、逃げられると思うなよ？\\n助かりたいのなら、さっさと浄化魔法を使え！！"

# アクア
# お、脅す気なの！？\n無駄よ、私はあんたみたいな奴の脅しに\n屈しないから！
297 = "お、脅す気なの！？\\n無駄よ、私はあんたみたいな奴の脅しに\\n屈しないから！"

# ウィズ
# か、カズマさんっ！\nもう限界が近いです！
303 = "か、カズマさんっ！\\nもう限界が近いです！"

# ゆんゆん
# ううううううう～！！
291 = "ううううううう～！！"

# カズマ
# お前、あんなに必死になってる\nゆんゆんとウィズを見て、なんとも思わないのか？
300 = "お前、あんなに必死になってる\\nゆんゆんとウィズを見て、なんとも思わないのか？"

# アクア
# そ、それはまあ、アンデッドはともかく\nゆんゆんにはちょっと良心が痛むけど……\nでもタダ働きは嫌だし……。
314 = "そ、それはまあ、アンデッドはともかく\\nゆんゆんにはちょっと良心が痛むけど……\\nでもタダ働きは嫌だし……。"

# カズマ
# 生きて帰れなければ金もなにもねーだろーがっ！\nそこのとこ、よく考えろっ！
405 = "生きて帰れなければ金もなにもねーだろーがっ！\\nそこのとこ、よく考えろっ！"

# アクア
# わ、わかったわよぉ。
354 = "わ、わかったわよぉ。"

# カズマ（Ｍ）
# display as カズマ
# （この期に及んで渋々やるのかよ……）
462 = "（この期に及んで渋々やるのかよ……）"

# アクア
# はーい、そこの２人。\n浄化魔法を打つから、\nそのままもうちょっと踏ん張ってねー。
338 = "はーい、そこの２人。\\n浄化魔法を打つから、\\nそのままもうちょっと踏ん張ってねー。"

# ウィズ
# お、お願いしますっ！
296 = "お、お願いしますっ！"

# アクア
# セイクリッド・ターンアンデッドー。
386 = "セイクリッド・ターンアンデッドー。"

# ダクネス
# なに！？\n効いてないぞ！
330 = "なに！？\\n効いてないぞ！"

# めぐみん
# 相手は大物です。\n１発では足りていないのかもしれません。
456 = "相手は大物です。\\n１発では足りていないのかもしれません。"

# カズマ
# くっ、アクア、もう一発頼む！
308 = "くっ、アクア、もう一発頼む！"

# アクア
# セイクリッド・ターンアンデッドー。
# 386 = "セイクリッド・ターンアンデッドー。"

# ダクネス
# まだダメか！
345 = "まだダメか！"

# カズマ（Ｍ）
# display as カズマ
# （いや、これは……）
460 = "（いや、これは……）"

# カズマ
# お前っ、ここまで来て手を抜くとは\nいい根性してんな！
301 = "お前っ、ここまで来て手を抜くとは\\nいい根性してんな！"

# アクア
# だって！　だって！\n浄化したら懸賞金がー！
323 = "だって！　だって！\\n浄化したら懸賞金がー！"

# カズマ
# クエストの報奨金だけで充分だろ！
375 = "クエストの報奨金だけで充分だろ！"

# アクア
# はあ……。\nセイクリッド・ターンアンデッド……。
336 = "はあ……。\\nセイクリッド・ターンアンデッド……。"

# スカルドラゴン
# グルルルルルァァ！！
382 = "グルルルルルァァ！！"

# めぐみん
# あ、苦しみだしました。
280 = "あ、苦しみだしました。"

# カズマ（Ｍ）
# display as カズマ
# （さすが、駄目さが極まっていても女神だな。\n　あれだけ手を抜いていても効くとは）
463 = "（さすが、駄目さが極まっていても女神だな。\\n　あれだけ手を抜いていても効くとは）"

# カズマ
# アクア！\nこの勢いで押し切れ！
363 = "アクア！\\nこの勢いで押し切れ！"

# アクア
# ううう……。\n懸賞金がぁ……。
290 = "ううう……。\\n懸賞金がぁ……。"

# カズマ
# だから、押し切れって！！
321 = "だから、押し切れって！！"

# アクア
# セイクリッド・ターンアンデッド……。
385 = "セイクリッド・ターンアンデッド……。"

# スカルドラゴン
# グルルルルルァァ！！\nグアアアアアアアルルルルルァァ！！
383 = "グルルルルルァァ！！\\nグアアアアアアアルルルルルァァ！！"

# ウィズ
# あうっ！
282 = "あうっ！"

# ゆんゆん
# きゃあっ！
305 = "きゃあっ！"

# カズマ
# ウィズ、ゆんゆん！？\nどうした！
366 = "ウィズ、ゆんゆん！？\\nどうした！"

# ウィズ
# 束縛魔法が弾かれました！
402 = "束縛魔法が弾かれました！"

# アクア
# ちょっとぉ！？\nすっごい暴れたしたんですけど！？
326 = "ちょっとぉ！？\\nすっごい暴れたしたんですけど！？"

# ダクネス
# あちらにとっても消滅の危機だ。\n黙ってやられるわけにはいかない、ということか。
283 = "あちらにとっても消滅の危機だ。\\n黙ってやられるわけにはいかない、ということか。"

# スカルドラゴン
# グアアアアアアアルルルルルァァ！！
377 = "グアアアアアアアルルルルルァァ！！"

# ダクネス
# まずいっ！\nこのままでは洞窟が崩れるぞ！
344 = "まずいっ！\\nこのままでは洞窟が崩れるぞ！"

# カズマ
# みんな、逃げるぞっ！\nあそこの通路に逃げ込めっ！！
347 = "みんな、逃げるぞっ！\\nあそこの通路に逃げ込めっ！！"

# ゆんゆん
# は、はいっ！
333 = "は、はいっ！"

# カズマ（Ｍ）
# display as カズマ
# （どこに通じているかはわからないが……\n　いや、信じるんだ！\n　絶対にこの先に出口があるって！）
469 = "（どこに通じているかはわからないが……\\n　いや、信じるんだ！\\n　絶対にこの先に出口があるって！）"

