# st04b_01.txt.scn

[info]
0 = ""

[characters]
254 = "カズマ（Ｍ）"
251 = "カズマ"
249 = "アクア"
257 = "ダクネス"
255 = "クリス"
247 = "ゆんゆん"
245 = "めぐみん"
250 = "アクア＆ダクネス＆めぐみん"

[character_subs]
# 251 = "カズマ"
317 = "３人"

[script]
# lines: 58

# カズマ（Ｍ）
# display as カズマ
# （翌日――\n　俺とゆんゆん、クリスは\n　待ち合わせた正門前に集まっていた）
316 = "（翌日――\\n　俺とゆんゆん、クリスは\\n　待ち合わせた正門前に集まっていた）"

# カズマ（Ｍ）
# display as カズマ
# （いや、正確に言うと俺達だけではない。\n　いつもの３人まで、なぜかついてきていた）
312 = "（いや、正確に言うと俺達だけではない。\\n　いつもの３人まで、なぜかついてきていた）"

# カズマ
# あのなぁ、別に見送りに来なくても\nよかったんだぞ？
220 = "あのなぁ、別に見送りに来なくても\\nよかったんだぞ？"

# アクア
# なに言ってんのよ。\n仲間が旅立つんだから、見送りくらい当然じゃない。
242 = "なに言ってんのよ。\\n仲間が旅立つんだから、見送りくらい当然じゃない。"

# カズマ
# お前の口から\nそんな言葉を聞く日が来るとは思わなかったぜ。
227 = "お前の口から\\nそんな言葉を聞く日が来るとは思わなかったぜ。"

# アクア
# あっ、そうだ、カズマ。\n財宝が見つからないからって、無理はしなくても\nいいからね。
216 = "あっ、そうだ、カズマ。\\n財宝が見つからないからって、無理はしなくても\\nいいからね。"

# アクア
# でもちょっとくらいなら頑張ってもいいのよ。\n何かあってもとりあえず帰って来られれば、\n私が治癒魔法をかけられるんだし。
240 = "でもちょっとくらいなら頑張ってもいいのよ。\\n何かあってもとりあえず帰って来られれば、\\n私が治癒魔法をかけられるんだし。"

# カズマ
# つまり、多少の怪我くらいでは帰ってくるなと。
238 = "つまり、多少の怪我くらいでは帰ってくるなと。"

# アクア
# ち、違うわよ。\nもう、変な受け取り方しないでったら、いやねー。
236 = "ち、違うわよ。\\nもう、変な受け取り方しないでったら、いやねー。"

# カズマ（Ｍ）
# display as カズマ
# （あー、殴りてー）
310 = "（あー、殴りてー）"

# ダクネス
# クリス。\nカズマをよろしく頼む。
256 = "クリス。\\nカズマをよろしく頼む。"

# クリス
# うん、任せておいて。
223 = "うん、任せておいて。"

# カズマ（Ｍ）
# display as カズマ
# （いや、普通なら、ここで男の俺が\n　クリスを頼まれるパターンだよな？\n　なんで逆になってるの？）
311 = "（いや、普通なら、ここで男の俺が\\n　クリスを頼まれるパターンだよな？\\n　なんで逆になってるの？）"

# ダクネス
# あと、勝手な行動を取らないように。\nクリスは自由なところがあるからな。\nそれから――
218 = "あと、勝手な行動を取らないように。\\nクリスは自由なところがあるからな。\\nそれから――"

# クリス
# もう、ダクネス。\nあたしは子どもじゃないんだから、わかってるよ。
246 = "もう、ダクネス。\\nあたしは子どもじゃないんだから、わかってるよ。"

# クリス
# それに、自由に行動してるんじゃないよ。\n盗賊として、先行して\n偵察したりしてるんだからね？
231 = "それに、自由に行動してるんじゃないよ。\\n盗賊として、先行して\\n偵察したりしてるんだからね？"

# クリス
# 今回は、クエストの内容が内容だし、\nあたしの力もより役立ちそうだよ。
260 = "今回は、クエストの内容が内容だし、\\nあたしの力もより役立ちそうだよ。"

# カズマ（Ｍ）
# display as カズマ
# （確かに。\n　俺も盗賊スキルはいくつか持ってるけど、\n　本業には敵わないもんな）
315 = "（確かに。\\n　俺も盗賊スキルはいくつか持ってるけど、\\n　本業には敵わないもんな）"

# カズマ（Ｍ）
# display as カズマ
# （そう考えると、確かに\n　俺よりもクリスにああ言いたくなるか。\n　情けないぜ……）
314 = "（そう考えると、確かに\\n　俺よりもクリスにああ言いたくなるか。\\n　情けないぜ……）"

# ゆんゆん
# あの、めぐみん！\n私、頑張ってくるからね！
219 = "あの、めぐみん！\\n私、頑張ってくるからね！"

# めぐみん
# はいはい、せいぜい頑張ってきてください。\n張り切りすぎてカズマに迷惑をかけたらダメですよ。
243 = "はいはい、せいぜい頑張ってきてください。\\n張り切りすぎてカズマに迷惑をかけたらダメですよ。"

# ゆんゆん
# 迷惑かけたりなんてしないよっ！
309 = "迷惑かけたりなんてしないよっ！"

# ゆんゆん
# ……あ、あのね、めぐみん。\n私、このクエストを通して、\nもっと強くなれる気がしてるんだ。
211 = "……あ、あのね、めぐみん。\\n私、このクエストを通して、\\nもっと強くなれる気がしてるんだ。"

# ゆんゆん
# だから、戻ってきたら勝負だよ！\n今度こそ、めぐみんを超えてみせるんだから！
234 = "だから、戻ってきたら勝負だよ！\\n今度こそ、めぐみんを超えてみせるんだから！"

# めぐみん
# カズマ曰く、そういうのをフラグと言うらしいです。
253 = "カズマ曰く、そういうのをフラグと言うらしいです。"

# めぐみん
# ああ、これでゆんゆんが\nこの街の門をくぐることは\n二度となくなったわけですね。
214 = "ああ、これでゆんゆんが\\nこの街の門をくぐることは\\n二度となくなったわけですね。"

# ゆんゆん
# 勝手に決めないでよー！
262 = "勝手に決めないでよー！"

# めぐみん
# 第一、魔物退治ならともかく、\n洞窟の調査で強くなるって\nどういうことなのですか。
305 = "第一、魔物退治ならともかく、\\n洞窟の調査で強くなるって\\nどういうことなのですか。"

# ゆんゆん
# そ、それは……その……\n一緒にいることで、\n精神的に強くなるっていうか……。
230 = "そ、それは……その……\\n一緒にいることで、\\n精神的に強くなるっていうか……。"

# カズマ（Ｍ）
# display as カズマ
# （え？　なんでそこで俺を見るの？\n　昨日からなんなんだよ、ゆんゆん！？）
313 = "（え？　なんでそこで俺を見るの？\\n　昨日からなんなんだよ、ゆんゆん！？）"

# めぐみん
# ……カズマ？\nこのクエスト、日帰りなんですよね？
212 = "……カズマ？\\nこのクエスト、日帰りなんですよね？"

# カズマ
# おう、そうだ。\n洞窟もそう遠くないしな。
225 = "おう、そうだ。\\n洞窟もそう遠くないしな。"

# クリス
# いや、カズマとキャンプなんて不可能でしょ。
222 = "いや、カズマとキャンプなんて不可能でしょ。"

# ゆんゆん
# ちょっと、怖いですよね。
237 = "ちょっと、怖いですよね。"

# カズマ
# あっ、もしかして、強くなるって\n俺と一緒にいれば強制的に\n精神が鍛えられるってことなの！？
217 = "あっ、もしかして、強くなるって\\n俺と一緒にいれば強制的に\\n精神が鍛えられるってことなの！？"

# ゆんゆん
# え、えーっと……。
224 = "え、えーっと……。"

# クリス
# まあ、否定はしないよ。
244 = "まあ、否定はしないよ。"

# めぐみん
# それは確かに、絶大な効果がありそうですね。
232 = "それは確かに、絶大な効果がありそうですね。"

# カズマ
# お前、今度、日帰りじゃすまないクエストに\n連れて行ってやろうか？
226 = "お前、今度、日帰りじゃすまないクエストに\\n連れて行ってやろうか？"

# めぐみん
# な、なにを考えてるんですか！？\nさては、妙なことをするつもりですね！
241 = "な、なにを考えてるんですか！？\\nさては、妙なことをするつもりですね！"

# カズマ
# そんなことしねーよ！
233 = "そんなことしねーよ！"

# ダクネス
# カズマ、妙なことについて詳しく！
252 = "カズマ、妙なことについて詳しく！"

# カズマ
# だからしねーって言ってんだろ！
235 = "だからしねーって言ってんだろ！"

# クリス
# さて、騒ぐのはこれくらいにしておこうか。\n出発が遅れると、それこそ日帰りじゃ\nすまなくなっちゃうしさ。
228 = "さて、騒ぐのはこれくらいにしておこうか。\\n出発が遅れると、それこそ日帰りじゃ\\nすまなくなっちゃうしさ。"

# カズマ
# あ、ああ、そうだな。\nそれじゃ、ちょっくら行ってくる。
213 = "あ、ああ、そうだな。\\nそれじゃ、ちょっくら行ってくる。"

# アクア
# いってらっしゃーい。
221 = "いってらっしゃーい。"

# ゆんゆん
# 行ってきます、めぐみん。
307 = "行ってきます、めぐみん。"

# めぐみん
# フラグの回収を楽しみにしていますよ。
258 = "フラグの回収を楽しみにしていますよ。"

# ゆんゆん
# し、しなくていいから！
229 = "し、しなくていいから！"

# めぐみん
# …………。
209 = "…………。"

# ダクネス
# ……。
210 = "……。"

# アクア
# 行ったわね。
306 = "行ったわね。"

# ダクネス
# ああ、行ったな。
215 = "ああ、行ったな。"

# めぐみん
# 行ってしまいましたね。
308 = "行ってしまいましたね。"

# ダクネス
# では――
239 = "では――"

# めぐみん
# 私達も――
304 = "私達も――"

# アクア
# 作戦開始よ。
261 = "作戦開始よ。"

# アクア＆ダクネス＆めぐみん
# display as ３人
# んっ！
248 = "んっ！"

