# st04b_03.txt.scn

[info]
0 = ""

[characters]
310 = "カズマ"
313 = "クリス"
299 = "ゆんゆん"
311 = "カズマ（Ｍ）"

[character_subs]
# 310 = "カズマ"

[script]
# lines: 107

# カズマ
# よし。\nモンスターはいないみたいだな。
306 = "よし。\\nモンスターはいないみたいだな。"

# クリス
# あたしも特に妙な気配は感じないし、\nゆっくり休憩できそうだね。
240 = "あたしも特に妙な気配は感じないし、\\nゆっくり休憩できそうだね。"

# ゆんゆん
# あ、あの、すみません。\n私、何もできなくて。
234 = "あ、あの、すみません。\\n私、何もできなくて。"

# クリス
# 気にしないの。\nこういうのが盗賊の仕事なんだからさ。
325 = "気にしないの。\\nこういうのが盗賊の仕事なんだからさ。"

# カズマ
# それにしても、休憩だと思ったら\n急に腹減ってきたぜ。
277 = "それにしても、休憩だと思ったら\\n急に腹減ってきたぜ。"

# ゆんゆん
# え！？
257 = "え！？"

# クリス
# じゃあ、魚でもとろうか。
270 = "じゃあ、魚でもとろうか。"

# ゆんゆん
# あ、あの……。
232 = "あ、あの……。"

# カズマ
# クリスそんなことまでできるのか。
314 = "クリスそんなことまでできるのか。"

# ゆんゆん
# あの、あの、あの……。
242 = "あの、あの、あの……。"

# クリス
# まあね。\nじゃあ、サクッと泳いでとってくるよ。
294 = "まあね。\\nじゃあ、サクッと泳いでとってくるよ。"

# カズマ（Ｍ）
# display as カズマ
# （お、泳ぐ！？　まさか着替えるのか？）
387 = "（お、泳ぐ！？　まさか着替えるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、荷物を見る限り必要最低限の物しか\n　持ってきてないよな）
386 = "（いや、荷物を見る限り必要最低限の物しか\\n　持ってきてないよな）"

# カズマ（Ｍ）
# display as カズマ
# （ということは、その服のまま！\n　もしかして全部脱いで！）
390 = "（ということは、その服のまま！\\n　もしかして全部脱いで！）"

# クリス
# あっと、そういえば携帯食があったのよ。
241 = "あっと、そういえば携帯食があったのよ。"

# カズマ
# そうでしたね。
274 = "そうでしたね。"

# ゆんゆん
# あ、あ、あの！！
231 = "あ、あ、あの！！"

# カズマ
# お、おう、どうした、ゆんゆん。
259 = "お、おう、どうした、ゆんゆん。"

# ゆんゆん
# お、お腹、空いたんですか！？
261 = "お、お腹、空いたんですか！？"

# カズマ
# お、おお、そうだけど。\nなんでそんなに食いついてくるんだ？
260 = "お、おお、そうだけど。\\nなんでそんなに食いついてくるんだ？"

# ゆんゆん
# 私、お弁当、作ってきたんです。\nよければ食べてください。
377 = "私、お弁当、作ってきたんです。\\nよければ食べてください。"

# カズマ
# マジで！？
315 = "マジで！？"

# クリス
# わざわざ作ってくれたの？
308 = "わざわざ作ってくれたの？"

# ゆんゆん
# はい。\nこういうことがあるんじゃないかと思って。
289 = "はい。\\nこういうことがあるんじゃないかと思って。"

# ゆんゆん
# お口に合うかわかりませんけど……\nお弁当作りには、それなりに自信がありますから。
264 = "お口に合うかわかりませんけど……\\nお弁当作りには、それなりに自信がありますから。"

# カズマ
# いや、マジでありがたいよ。
250 = "いや、マジでありがたいよ。"

# クリス
# うんうん！\n遠慮なくいただいちゃおうかな。
253 = "うんうん！\\n遠慮なくいただいちゃおうかな。"

# ゆんゆん
# で、では、広げますね。
279 = "で、では、広げますね。"

# カズマ（Ｍ）
# display as カズマ
# （おいおい、シートまで持ってきたのか。\n　まるでピクニックだな）
388 = "（おいおい、シートまで持ってきたのか。\\n　まるでピクニックだな）"

# クリス
# へえ、うまく彩りをつけるものだね。
292 = "へえ、うまく彩りをつけるものだね。"

# ゆんゆん
# み、見た目も大切かなって思いまして。
295 = "み、見た目も大切かなって思いまして。"

# クリス
# これ作るのに、結構時間がかかったんじゃない？
267 = "これ作るのに、結構時間がかかったんじゃない？"

# ゆんゆん
# いえ、いつもよりも\n２時間早く起きるだけでしたから。
248 = "いえ、いつもよりも\\n２時間早く起きるだけでしたから。"

# カズマ（Ｍ）
# display as カズマ
# （いや、そこはクエストのために\n　しっかり寝ておけよ）
385 = "（いや、そこはクエストのために\\n　しっかり寝ておけよ）"

# クリス
# じゃあ、遠慮なくいただくね。
269 = "じゃあ、遠慮なくいただくね。"

# ゆんゆん
# ど、どうぞ！
281 = "ど、どうぞ！"

# クリス
# もぐもぐ……。
297 = "もぐもぐ……。"

# カズマ
# むぐむぐ……。
296 = "むぐむぐ……。"

# ゆんゆん
# どうですか？
282 = "どうですか？"

# クリス
# 美味しい！\nすごく美味しいよ！
381 = "美味しい！\\nすごく美味しいよ！"

# ゆんゆん
# あ、あの、お世辞なんて、\n言わなくていいんですよ？
233 = "あ、あの、お世辞なんて、\\n言わなくていいんですよ？"

# クリス
# いや、そんなことは――
249 = "いや、そんなことは――"

# ゆんゆん
# 本当のことを言ってくれないと、\n次も同じ味付けにして来ちゃいますし、\nそうなったら――
324 = "本当のことを言ってくれないと、\\n次も同じ味付けにして来ちゃいますし、\\nそうなったら――"

# ゆんゆん
# えー、この前と同じ味付け？\n私にはちょっと薄味なんだけどー。
256 = "えー、この前と同じ味付け？\\n私にはちょっと薄味なんだけどー。"

# ゆんゆん
# なんてことになりかねませんから。
283 = "なんてことになりかねませんから。"

# クリス
# あは、あはは、本当にあたし好みの味だからさ。
243 = "あは、あはは、本当にあたし好みの味だからさ。"

# ゆんゆん
# よかったぁ。\n実は、ご迷惑になったらどうしようかと\n思ってたんです。
305 = "よかったぁ。\\n実は、ご迷惑になったらどうしようかと\\n思ってたんです。"

# クリス
# 迷惑だなんて、なんでそんな心配してたの？\n色々気にしすぎだよ。
382 = "迷惑だなんて、なんでそんな心配してたの？\\n色々気にしすぎだよ。"

# クリス
# ねえ、キミだってそう思うでしょ？\nゆんゆんのお弁当、美味しいもんね。
285 = "ねえ、キミだってそう思うでしょ？\\nゆんゆんのお弁当、美味しいもんね。"

# カズマ
# 美味しいけど、彩りが俺の好みじゃないかな。
380 = "美味しいけど、彩りが俺の好みじゃないかな。"

# ゆんゆん
# うぅ、すみません。
251 = "うぅ、すみません。"

# クリス
# キミ～。\nそこは、もうちょっと気が利いたことを\n言ってあげたほうがいいんじゃない？
312 = "キミ～。\\nそこは、もうちょっと気が利いたことを\\n言ってあげたほうがいいんじゃない？"

# カズマ
# あれ？　なんかマズかったか？
245 = "あれ？　なんかマズかったか？"

# クリス
# マズいって事はないけどね？
316 = "マズいって事はないけどね？"

# ゆんゆん
# うう～……。
252 = "うう～……。"

# カズマ
# ああ、気が利くよな。\nクエスト中にお弁当にありつけるなんて\n思いもしなかったよ。
238 = "ああ、気が利くよな。\\nクエスト中にお弁当にありつけるなんて\\n思いもしなかったよ。"

# ゆんゆん
# 喜んでもらえて嬉しいです。\n余計な事だったらどうしようって。
320 = "喜んでもらえて嬉しいです。\\n余計な事だったらどうしようって。"

# カズマ
# ゆんゆんは心配性だなぁ。\nむしろ、こういう気遣いをアクアやめぐみんに\n見習わせたいくらいだよ。
301 = "ゆんゆんは心配性だなぁ。\\nむしろ、こういう気遣いをアクアやめぐみんに\\n見習わせたいくらいだよ。"

# ゆんゆん
# は、恥ずかしいですから、もうやめてください。
287 = "は、恥ずかしいですから、もうやめてください。"

# カズマ
# ゆんゆん可愛い。
304 = "ゆんゆん可愛い。"

# ゆんゆん
# ええ！？
255 = "ええ！？"

# カズマ
# ゆんゆん、最高！
300 = "ゆんゆん、最高！"

# ゆんゆん
# ちょ、ちょっとカズマさん！\nほ、本当にやめてくださいってば！
278 = "ちょ、ちょっとカズマさん！\\nほ、本当にやめてくださいってば！"

# カズマ
# あはは、悪い悪い。
244 = "あはは、悪い悪い。"

# ゆんゆん
# あうう～～。
239 = "あうう～～。"

# カズマ
# ゆんゆんは料理上手なんだな。
303 = "ゆんゆんは料理上手なんだな。"

# ゆんゆん
# ええっ！？\nわ、私なんてまだまだです！
254 = "ええっ！？\\nわ、私なんてまだまだです！"

# カズマ
# そうか？\nこの慣れた感じ、普段から作ってないと\n出せないだろ。
273 = "そうか？\\nこの慣れた感じ、普段から作ってないと\\n出せないだろ。"

# クリス
# これだけの料理の腕があるなら\nいつでもお嫁にいけるんじゃない？
266 = "これだけの料理の腕があるなら\\nいつでもお嫁にいけるんじゃない？"

# ゆんゆん
# お、お、お嫁さん！？\nそそ、そんなの、考えたこともありませんから！
258 = "お、お、お嫁さん！？\\nそそ、そんなの、考えたこともありませんから！"

# ゆんゆん
# わ、わ、私はいずれ\n紅魔族の長にならなくちゃいけないので！\nそんなことしてる暇なんてないんです！
307 = "わ、わ、私はいずれ\\n紅魔族の長にならなくちゃいけないので！\\nそんなことしてる暇なんてないんです！"

# カズマ
# おいおい、落ち着けって。\nクリスの冗談だよ、冗談。
263 = "おいおい、落ち着けって。\\nクリスの冗談だよ、冗談。"

# ゆんゆん
# あわわわわ！
246 = "あわわわわ！"

# カズマ
# ごちそうさま。\nはぁぁ、満足満足。
268 = "ごちそうさま。\\nはぁぁ、満足満足。"

# クリス
# すっかりご馳走になっちゃったね。
272 = "すっかりご馳走になっちゃったね。"

# ゆんゆん
# いえ、いいんです。\n私、夢が一つ叶いましたから。
247 = "いえ、いいんです。\\n私、夢が一つ叶いましたから。"

# カズマ
# 夢？
321 = "夢？"

# ゆんゆん
# こうして、草の上にみんなで座ってお弁当を\n食べながら他愛ない話をするのがです。
265 = "こうして、草の上にみんなで座ってお弁当を\\n食べながら他愛ない話をするのがです。"

# カズマ
# …………。
230 = "…………。"

# ゆんゆん
# 今日は楽しかったね、とか、\nそういえばこの前のテストどうだった、とか、\nこの本がお勧めだよ、とか――
318 = "今日は楽しかったね、とか、\\nそういえばこの前のテストどうだった、とか、\\nこの本がお勧めだよ、とか――"

# ゆんゆん
# でも、やっぱりお話をするって難しいですね。
280 = "でも、やっぱりお話をするって難しいですね。"

# ゆんゆん
# 昨日から会話の内容を考えて、\n用意もして、練習もしてきたんですけど、\nいざとなったら頭が真っ白になっちゃいました。
323 = "昨日から会話の内容を考えて、\\n用意もして、練習もしてきたんですけど、\\nいざとなったら頭が真っ白になっちゃいました。"

# カズマ（Ｍ）
# display as カズマ
# （なんだろう、胸が痛い……）
391 = "（なんだろう、胸が痛い……）"

# クリス
# じゃあさ、\n今度はみんなでピクニックでもしようか。
271 = "じゃあさ、\\n今度はみんなでピクニックでもしようか。"

# ゆんゆん
# ぴ、ピクニックですか！
290 = "ぴ、ピクニックですか！"

# クリス
# もちろん、ゆんゆんのお弁当を期待してるからね。
298 = "もちろん、ゆんゆんのお弁当を期待してるからね。"

# ゆんゆん
# は、はい！　任せておいてください！
286 = "は、はい！　任せておいてください！"

# カズマ
# おいおい、今は一応クエスト中なんだぞ。\n気を抜きすぎだろ。
262 = "おいおい、今は一応クエスト中なんだぞ。\\n気を抜きすぎだろ。"

# クリス
# 確かにクエスト中だけどさ、今は休憩時間でしょ。
376 = "確かにクエスト中だけどさ、今は休憩時間でしょ。"

# クリス
# それに、常に肩肘張ってたら疲れちゃうよね？\nキミだってそう思わない？
276 = "それに、常に肩肘張ってたら疲れちゃうよね？\\nキミだってそう思わない？"

# カズマ
# まあ、それもそうか。
293 = "まあ、それもそうか。"

# ゆんゆん
# 私もそう思います！
378 = "私もそう思います！"

# クリス
# ふふっ！\n今のゆんゆん、すごくいい笑顔だよ。
291 = "ふふっ！\\n今のゆんゆん、すごくいい笑顔だよ。"

# カズマ（Ｍ）
# display as カズマ
# （ああ……！\n　いい！　ゆんゆんの笑顔もだけど、\n　この空気も最高だっ！！）
383 = "（ああ……！\\n　いい！　ゆんゆんの笑顔もだけど、\\n　この空気も最高だっ！！）"

# カズマ（Ｍ）
# display as カズマ
# （そうだよ！\n　俺はこんな雰囲気に憧れてたんだよ！）
389 = "（そうだよ！\\n　俺はこんな雰囲気に憧れてたんだよ！）"

# カズマ（Ｍ）
# display as カズマ
# （仲間と助け合い、励ましあって\n　クエストに立ち向かっていく！\n　これぞまさに冒険者パーティーじゃないか！）
394 = "（仲間と助け合い、励ましあって\\n　クエストに立ち向かっていく！\\n　これぞまさに冒険者パーティーじゃないか！）"

# カズマ（Ｍ）
# display as カズマ
# （ん？　今、なにか音がしたか？）
393 = "（ん？　今、なにか音がしたか？）"

# カズマ（Ｍ）
# display as カズマ
# （まただ！\n　後ろから……モンスターか！？）
392 = "（まただ！\\n　後ろから……モンスターか！？）"

# カズマ（Ｍ）
# display as カズマ
# （あれ？　何もいない？\n　気のせいだったのか？）
384 = "（あれ？　何もいない？\\n　気のせいだったのか？）"

# クリス
# ん？　どうかした？
309 = "ん？　どうかした？"

# カズマ
# あ、いや……。
235 = "あ、いや……。"

# カズマ（Ｍ）
# display as カズマ
# （盗賊のクリスが気がついてないのなら、\n　俺の気のせいか）
395 = "（盗賊のクリスが気がついてないのなら、\\n　俺の気のせいか）"

# カズマ
# なんでもない。\nそれより、そろそろ出発しようぜ。
284 = "なんでもない。\\nそれより、そろそろ出発しようぜ。"

# クリス
# ああ、そうだね。\nあんまりのんびりしてると、\n洞窟を調べる時間が足りなくなりそう。
236 = "ああ、そうだね。\\nあんまりのんびりしてると、\\n洞窟を調べる時間が足りなくなりそう。"

# ゆんゆん
# それじゃ、急いで片付けますね。
275 = "それじゃ、急いで片付けますね。"

# クリス
# １人でやろうとしないの。\n手伝うよ、ゆんゆん。
396 = "１人でやろうとしないの。\\n手伝うよ、ゆんゆん。"

# ゆんゆん
# はい、ありがとうございます。
288 = "はい、ありがとうございます。"

[selections]
379 = "美味しいけど……"
237 = "ああ、気が利くよな"
302 = "ゆんゆんは料理上手なんだな"
