# st04b_02.txt.scn

[info]
0 = ""

[characters]
237 = "カズマ（Ｍ）"
236 = "カズマ"
234 = "ゆんゆん"
238 = "クリス"

[character_subs]
# 236 = "カズマ"

[script]
# lines: 98

# カズマ（Ｍ）
# display as カズマ
# （街を出て数時間後……。\n　俺は心の中で、うめくような声を上げた）
332 = "（街を出て数時間後……。\\n　俺は心の中で、うめくような声を上げた）"

# カズマ（Ｍ）
# display as カズマ
# （空気が――重いっ！！）
331 = "（空気が――重いっ！！）"

# カズマ
# …………。
190 = "…………。"

# ゆんゆん
# …………。
# 190 = "…………。"

# クリス
# …………。
# 190 = "…………。"

# カズマ
# な、なあ！\n洞窟ってこっちの方角であってるんだよな？
219 = "な、なあ！\\n洞窟ってこっちの方角であってるんだよな？"

# クリス
# ああ、うん、あってるはずだよ。
194 = "ああ、うん、あってるはずだよ。"

# カズマ
# そ、そっか、それならよかった。
209 = "そ、そっか、それならよかった。"

# クリス
# うん。
203 = "うん。"

# カズマ（Ｍ）
# display as カズマ
# （会話が続かねー！\n　街を出てから、しゃべってた時間のほうが\n　少ないぞ！？）
325 = "（会話が続かねー！\\n　街を出てから、しゃべってた時間のほうが\\n　少ないぞ！？）"

# カズマ（Ｍ）
# display as カズマ
# （それも全部、俺が話しかけて\n　クリスかゆんゆんが返事をして終わり。\n　会話とも言えないレベルだし！）
306 = "（それも全部、俺が話しかけて\\n　クリスかゆんゆんが返事をして終わり。\\n　会話とも言えないレベルだし！）"

# カズマ（Ｍ）
# display as カズマ
# （でも、まあ、考えてみれば――\n　クリスとゆんゆんは面識こそあるけど、\n　親しく話すような間柄じゃない）
307 = "（でも、まあ、考えてみれば――\\n　クリスとゆんゆんは面識こそあるけど、\\n　親しく話すような間柄じゃない）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスやめぐみんを通して話していただけで、\n　この２人が直接、言葉を交わしたことなんて\n　ほとんどなかったかもしれない）
321 = "（ダクネスやめぐみんを通して話していただけで、\\n　この２人が直接、言葉を交わしたことなんて\\n　ほとんどなかったかもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （しかも、ゆんゆんは不器用で、\n　ドがつくほどに友達を作るのが下手だ）
303 = "（しかも、ゆんゆんは不器用で、\\n　ドがつくほどに友達を作るのが下手だ）"

# カズマ（Ｍ）
# display as カズマ
# （クリスは愛想がいいほうだと思うけど、\n　さすがに相手が悪いよなぁ）
318 = "（クリスは愛想がいいほうだと思うけど、\\n　さすがに相手が悪いよなぁ）"

# カズマ（Ｍ）
# display as カズマ
# （となると、ここは俺がなんとかしないと。\n　これから洞窟の調査をするんだ、\n　連携を良くしておくべきだしな）
308 = "（となると、ここは俺がなんとかしないと。\\n　これから洞窟の調査をするんだ、\\n　連携を良くしておくべきだしな）"

# カズマ（Ｍ）
# display as カズマ
# （会話、会話……。\n　一般的な、差し障りのない会話……）
324 = "（会話、会話……。\\n　一般的な、差し障りのない会話……）"

# カズマ（Ｍ）
# display as カズマ
# （よし、これだっ！）
314 = "（よし、これだっ！）"

# カズマ
# い、いや、それにしてもいい天気だな！
199 = "い、いや、それにしてもいい天気だな！"

# クリス
# そうだね。
211 = "そうだね。"

# ゆんゆん
# そうですね。
212 = "そうですね。"

# カズマ（Ｍ）
# display as カズマ
# （ダメだー！\n　つか、そもそも天気から話題を広げられるほど、\n　俺は会話スキルに長けてるわけじゃねーし！）
322 = "（ダメだー！\\n　つか、そもそも天気から話題を広げられるほど、\\n　俺は会話スキルに長けてるわけじゃねーし！）"

# カズマ（Ｍ）
# display as カズマ
# （こんなところに、長期の引きこもりの弊害が\n　未だに残っているとは！！）
302 = "（こんなところに、長期の引きこもりの弊害が\\n　未だに残っているとは！！）"

# カズマ（Ｍ）
# display as カズマ
# （思い出せー、思い出せー。\n　まだ外に出ていた頃、\n　俺は人となんについて話してたー？）
329 = "（思い出せー、思い出せー。\\n　まだ外に出ていた頃、\\n　俺は人となんについて話してたー？）"

# カズマ（Ｍ）
# display as カズマ
# （そうだ、友達！\n　共通の友達の話題！　これならいける！）
304 = "（そうだ、友達！\\n　共通の友達の話題！　これならいける！）"

# カズマ（Ｍ）
# display as カズマ
# （俺達の共通の知り合いって言えば、\n　アクア、ダクネス、めぐみんだよな。\n　ここは……）
326 = "（俺達の共通の知り合いって言えば、\\n　アクア、ダクネス、めぐみんだよな。\\n　ここは……）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスの話をしよう。\n　ゆんゆんよりクリスのほうが、\n　きっと話題を拾ってくれる！）
319 = "（ダクネスの話をしよう。\\n　ゆんゆんよりクリスのほうが、\\n　きっと話題を拾ってくれる！）"

# カズマ
# なあ、クリス。\nダクネスって、なんであんなに\n攻撃が当たらないんだ？
222 = "なあ、クリス。\\nダクネスって、なんであんなに\\n攻撃が当たらないんだ？"

# クリス
# ……え？　急にどうしたの？
191 = "……え？　急にどうしたの？"

# カズマ
# いや、あのヘッポコ剣術は\n不器用なだけじゃ説明がつかないだろ。
200 = "いや、あのヘッポコ剣術は\\n不器用なだけじゃ説明がつかないだろ。"

# カズマ
# 昔、なにかあったのか？\n剣を振るのが苦手になったきっかけとかさ。
250 = "昔、なにかあったのか？\\n剣を振るのが苦手になったきっかけとかさ。"

# クリス
# ううん、聞いたことないな。\nあれは本当に不器用なだけなんじゃない？
202 = "ううん、聞いたことないな。\\nあれは本当に不器用なだけなんじゃない？"

# カズマ
# マジか。\nそれでなんで両手剣を装備しようと\n思ったんだかなぁ。
241 = "マジか。\\nそれでなんで両手剣を装備しようと\\n思ったんだかなぁ。"

# クリス
# それは……多分だけど、\n剣のほうが相手との間合いが近いからじゃない？\n相手の攻撃が当たる機会も多くなるし。
215 = "それは……多分だけど、\\n剣のほうが相手との間合いが近いからじゃない？\\n相手の攻撃が当たる機会も多くなるし。"

# カズマ
# 徹底的に変態だな、あいつは。
249 = "徹底的に変態だな、あいつは。"

# クリス
# あはは。\nそうと決まったわけじゃないけどさ。
197 = "あはは。\\nそうと決まったわけじゃないけどさ。"

# ゆんゆん
# …………。
# 190 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （はっ！？　蚊帳の外のゆんゆんが\n　羨ましそうに見てるー！）
309 = "（はっ！？　蚊帳の外のゆんゆんが\\n　羨ましそうに見てるー！）"

# カズマ（Ｍ）
# display as カズマ
# （アクアの話をするか。\n　あいつについてなら、\n　言っておきたいことが山ほどあるしな）
316 = "（アクアの話をするか。\\n　あいつについてなら、\\n　言っておきたいことが山ほどあるしな）"

# カズマ
# あのさ、昨日のアクア、ひどい態度だったよな。\n俺が謝っても仕方ないけど、悪かったよ。
196 = "あのさ、昨日のアクア、ひどい態度だったよな。\\n俺が謝っても仕方ないけど、悪かったよ。"

# ゆんゆん
# え？　アクアさんがですか？
206 = "え？　アクアさんがですか？"

# クリス
# 謝られるような覚えはないよ？
296 = "謝られるような覚えはないよ？"

# カズマ
# ほら、自分の取り分を増やしたいからって\n２人に財宝のことを話そうとしなかっただろ？
231 = "ほら、自分の取り分を増やしたいからって\\n２人に財宝のことを話そうとしなかっただろ？"

# クリス
# ああ、それか。\nでもアクアさんって、いつもあんな感じじゃない。
195 = "ああ、それか。\\nでもアクアさんって、いつもあんな感じじゃない。"

# ゆんゆん
# そうですよね。\nなので、気にしてませんでした。
213 = "そうですよね。\\nなので、気にしてませんでした。"

# カズマ（Ｍ）
# display as カズマ
# （アクア、お前はこんな評価でいいのか？\n　無駄だろうが、もうちょっと\n　考えるように言っとこう）
315 = "（アクア、お前はこんな評価でいいのか？\\n　無駄だろうが、もうちょっと\\n　考えるように言っとこう）"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんの話をしてみるか。\n　ゆんゆんは、めぐみんの話なら\n　すぐに食いついてきそうだし）
311 = "（めぐみんの話をしてみるか。\\n　ゆんゆんは、めぐみんの話なら\\n　すぐに食いついてきそうだし）"

# カズマ
# そう言えばさ、めぐみんの眼帯って\nオシャレでつけてるらしいけど、\nゆんゆんはしないのか？
214 = "そう言えばさ、めぐみんの眼帯って\\nオシャレでつけてるらしいけど、\\nゆんゆんはしないのか？"

# ゆんゆん
# えっ！？\nい、いえ、その、私は、\n特にそういう趣味はないので。
204 = "えっ！？\\nい、いえ、その、私は、\\n特にそういう趣味はないので。"

# ゆんゆん
# 確かに紅魔族は、伊達眼帯とか\n穴あきグローブとか好きな人が多いけど、\n私は恥ずかしいんです。
294 = "確かに紅魔族は、伊達眼帯とか\\n穴あきグローブとか好きな人が多いけど、\\n私は恥ずかしいんです。"

# ゆんゆん
# はあ、私がおかしいのかな。\nこんなだからお友達できないのかも。
227 = "はあ、私がおかしいのかな。\\nこんなだからお友達できないのかも。"

# カズマ（Ｍ）
# display as カズマ
# （ああっ！？\n　しまった、うっかり触れてはいけない部分に\n　触れてしまった！？）
300 = "（ああっ！？\\n　しまった、うっかり触れてはいけない部分に\\n　触れてしまった！？）"

# ゆんゆん
# …………。
# 190 = "…………。"

# クリス
# …………。
# 190 = "…………。"

# カズマ
# …………。
# 190 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （憎い！　自分の対人スキルのなさが憎い！\n　スキルポイントをこっちに割り振れねーのか！？）
330 = "（憎い！　自分の対人スキルのなさが憎い！\\n　スキルポイントをこっちに割り振れねーのか！？）"

# ゆんゆん
# …………。
# 190 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （……ん？\n　なんか２人とも歩くの遅いな）
297 = "（……ん？\\n　なんか２人とも歩くの遅いな）"

# カズマ
# なあ、２人とも遅れがちだけどさ、\n俺、歩くの速いかな？\nアクアたちと歩いてる時はこんなもんなんだけど。
223 = "なあ、２人とも遅れがちだけどさ、\\n俺、歩くの速いかな？\\nアクアたちと歩いてる時はこんなもんなんだけど。"

# クリス
# あ、ああ、そんなことはないよ。\nキミのペースで歩いていいからね。
192 = "あ、ああ、そんなことはないよ。\\nキミのペースで歩いていいからね。"

# ゆんゆん
# 私も問題ないです。\nちゃんとついていきます。
295 = "私も問題ないです。\\nちゃんとついていきます。"

# カズマ
# 本当に？\nこんなところで遠慮しなくていいからな？
251 = "本当に？\\nこんなところで遠慮しなくていいからな？"

# ゆんゆん
# はい。\nありがとうございます。
228 = "はい。\\nありがとうございます。"

# カズマ（Ｍ）
# display as カズマ
# （問題ないって言うけど、なんか変なような。\n　俺が気を使いすぎなのか？）
328 = "（問題ないって言うけど、なんか変なような。\\n　俺が気を使いすぎなのか？）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、もしかして、\n　単に緊張してるだけなのかもしれない）
299 = "（ああ、もしかして、\\n　単に緊張してるだけなのかもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （顔見知りとは言え、\n　こうしてパーティーを組むのは初めてなんだ）
333 = "（顔見知りとは言え、\\n　こうしてパーティーを組むのは初めてなんだ）"

# カズマ（Ｍ）
# display as カズマ
# （そっか、そうだよな！\n　俺の対人スキルの問題じゃなかったんだな！）
305 = "（そっか、そうだよな！\\n　俺の対人スキルの問題じゃなかったんだな！）"

# ゆんゆん
# …………。
# 190 = "…………。"

# クリス
# ん？　ゆんゆん、どうかした？
235 = "ん？　ゆんゆん、どうかした？"

# ゆんゆん
# えっ？
205 = "えっ？"

# クリス
# 今、こっちを見てたような気がしてさ。
243 = "今、こっちを見てたような気がしてさ。"

# ゆんゆん
# な、なんでも、ないです。\n気にしないでください。
220 = "な、なんでも、ないです。\\n気にしないでください。"

# カズマ（Ｍ）
# display as カズマ
# （いや、そんなに真っ赤になって\n　気にするなって、無理な話だろ）
301 = "（いや、そんなに真っ赤になって\\n　気にするなって、無理な話だろ）"

# ゆんゆん
# …………。
# 190 = "…………。"

# クリス
# …………。
# 190 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （また見てる。\n　クリスも気にしないようにはしてるけど……\n　どうしたんだろう？）
310 = "（また見てる。\\n　クリスも気にしないようにはしてるけど……\\n　どうしたんだろう？）"

# カズマ（Ｍ）
# display as カズマ
# （あ、そっか！\n　これはもしかして！）
298 = "（あ、そっか！\\n　これはもしかして！）"

# カズマ
# なあ、ゆんゆん。
221 = "なあ、ゆんゆん。"

# ゆんゆん
# は、はい！？\nなんでしょうか？
226 = "は、はい！？\\nなんでしょうか？"

# カズマ
# ちょっといいか？
218 = "ちょっといいか？"

# ゆんゆん
# ひううっ！？
230 = "ひううっ！？"

# カズマ
# いやいや、何もしないから。
201 = "いやいや、何もしないから。"

# ゆんゆん
# す、すみません、つい。
207 = "す、すみません、つい。"

# カズマ
# もしかしてなんだけどさ、\nゆんゆんはクリスと友達になりたいのか？
232 = "もしかしてなんだけどさ、\\nゆんゆんはクリスと友達になりたいのか？"

# ゆんゆん
# はへ？
229 = "はへ？"

# カズマ
# あれ、違うのか？\nじゃあ、他にどんな理由が……。
198 = "あれ、違うのか？\\nじゃあ、他にどんな理由が……。"

# ゆんゆん
# ち、ちち、違いません！\nそそ、そうですね、はい、そうです！
217 = "ち、ちち、違いません！\\nそそ、そうですね、はい、そうです！"

# カズマ
# やっぱりそうか！\nじゃないかと思ったんだよ。
233 = "やっぱりそうか！\\nじゃないかと思ったんだよ。"

# クリス
# ねえ、どうしたの？\nなんの話をしてるの？
224 = "ねえ、どうしたの？\\nなんの話をしてるの？"

# カズマ
# あ、ああ、別になんでもない。
193 = "あ、ああ、別になんでもない。"

# ゆんゆん
# そ、そうです、なんでもないんです！
208 = "そ、そうです、なんでもないんです！"

# クリス
# だったらいいんだけど……。
216 = "だったらいいんだけど……。"

# クリス
# そうだ、この近くに湖があるでしょ？\n先は長いし、ちょっと休憩しない？
210 = "そうだ、この近くに湖があるでしょ？\\n先は長いし、ちょっと休憩しない？"

# カズマ
# 休憩か。\n確かにそろそろ休んだほうがいいな。\n行ってみるか。
244 = "休憩か。\\n確かにそろそろ休んだほうがいいな。\\n行ってみるか。"

# ゆんゆん
# は、はい。\nそうしましょうか。
225 = "は、はい。\\nそうしましょうか。"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆん、やっぱり友達がほしいのか）
313 = "（ゆんゆん、やっぱり友達がほしいのか）"

# カズマ（Ｍ）
# display as カズマ
# （今回のお礼にもなるだろうし、\n　ここで俺が一肌脱いで\n　なにかきっかけを作れたら……）
323 = "（今回のお礼にもなるだろうし、\\n　ここで俺が一肌脱いで\\n　なにかきっかけを作れたら……）"

# カズマ（Ｍ）
# display as カズマ
# （元引きこもりの俺にできるかどうか、\n　微妙に自信ないけどな）
327 = "（元引きこもりの俺にできるかどうか、\\n　微妙に自信ないけどな）"

[selections]
320 = "（ダクネスの話をしよう）"
317 = "（アクアの話をするか）"
312 = "（めぐみんの話をしてみるか）"
