# st04a_10.txt.scn

[info]
0 = ""

[characters]
191 = "ルナ"
187 = "カズマ"
189 = "クリス"
184 = "ゆんゆん"
183 = "めぐみん"
186 = "アクア"
190 = "ダクネス"
188 = "カズマ（Ｍ）"

[character_subs]
# 187 = "カズマ"

[script]
# lines: 20

# ルナ
# あ、サトウさん。\nどうですか、同行する方は見つかりましたか？
170 = "あ、サトウさん。\\nどうですか、同行する方は見つかりましたか？"

# カズマ
# はい、クリスとゆんゆんが\n協力してくれることになったんで、\nさっきのクエスト、正式に引き受けます。
179 = "はい、クリスとゆんゆんが\\n協力してくれることになったんで、\\nさっきのクエスト、正式に引き受けます。"

# ルナ
# まあ、よかったですね！\nそれでは、ご健闘をお祈りします。
182 = "まあ、よかったですね！\\nそれでは、ご健闘をお祈りします。"

# カズマ
# はいっ！
180 = "はいっ！"

# ルナ
# 頑張ってくださいね。\n何かあれば、こちらも協力致しますので。
212 = "頑張ってくださいね。\\n何かあれば、こちらも協力致しますので。"

# カズマ
# いえ、そんな。\nもう充分ですよ、あとは俺達次第です。
172 = "いえ、そんな。\\nもう充分ですよ、あとは俺達次第です。"

# カズマ
# な？　クリス、ゆんゆん。
178 = "な？　クリス、ゆんゆん。"

# クリス
# うん、任せて。
175 = "うん、任せて。"

# ゆんゆん
# 精一杯、頑張ります！
211 = "精一杯、頑張ります！"

# カズマ
# へへっ！　頼もしいぜ。\nさっそく明日、洞窟に行くつもりだから\nよろしくな！
181 = "へへっ！　頼もしいぜ。\\nさっそく明日、洞窟に行くつもりだから\\nよろしくな！"

# めぐみん
# ……なんだか、私達とクエストに出る時と\n雰囲気が違いません？
169 = "……なんだか、私達とクエストに出る時と\\n雰囲気が違いません？"

# アクア
# あからさまに張り切ってるわね。\n大丈夫なのかしら、あんなにはしゃいで……。\nちゃんと財宝を見つけられるのかしら？
171 = "あからさまに張り切ってるわね。\\n大丈夫なのかしら、あんなにはしゃいで……。\\nちゃんと財宝を見つけられるのかしら？"

# ダクネス
# うむ、浮かれていると足元をすくわれる。
174 = "うむ、浮かれていると足元をすくわれる。"

# カズマ
# ん？　お前ら、どうした？
185 = "ん？　お前ら、どうした？"

# めぐみん
# いえ、なんでもないですよ？
173 = "いえ、なんでもないですよ？"

# アクア
# そうそう、なんでもないのよ？
177 = "そうそう、なんでもないのよ？"

# ダクネス
# %fsyogen;それよりも明日の準備を進めよう。\n洞窟まで行くんだ、携帯食なども必要だろう？
20 = "%fsyogen;それよりも明日の準備を進めよう。\\n洞窟まで行くんだ、携帯食なども必要だろう？"

# カズマ（Ｍ）
# display as カズマ
# （ダクネス、今、何かをごまかしたか？）
214 = "（ダクネス、今、何かをごまかしたか？）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、気のせいかもしれないけど、\n　念のため証言として押さえておくか）
213 = "（うーん、気のせいかもしれないけど、\\n　念のため証言として押さえておくか）"

# カズマ
# おう、そうだな。\nんじゃ、行くか。
176 = "おう、そうだな。\\nんじゃ、行くか。"

