# st04b_07.txt.scn

[info]
0 = ""

[characters]
259 = "クリス"
256 = "カズマ"
250 = "ゆんゆん"
257 = "カズマ（Ｍ）"

[character_subs]
# 256 = "カズマ"

[script]
# lines: 74

# クリス
# ふう。\n結構来たけど、出口も財宝もないか。
243 = "ふう。\\n結構来たけど、出口も財宝もないか。"

# カズマ
# この洞窟、思った以上に広いな。\nちょっと休憩しようぜ。
220 = "この洞窟、思った以上に広いな。\\nちょっと休憩しようぜ。"

# ゆんゆん
# はい……。
241 = "はい……。"

# クリス
# ゆんゆん、大丈夫？\n疲れちゃった？
251 = "ゆんゆん、大丈夫？\\n疲れちゃった？"

# ゆんゆん
# あ、大丈夫です。\nまたモンスターが出てくるかもしれないって、\n緊張しちゃっただけで。
200 = "あ、大丈夫です。\\nまたモンスターが出てくるかもしれないって、\\n緊張しちゃっただけで。"

# カズマ
# そっか。\nさっきの魔法で疲れたのかと思ったぜ。
224 = "そっか。\\nさっきの魔法で疲れたのかと思ったぜ。"

# ゆんゆん
# あのくらいの魔法なら、\n何回使っても問題ありませんから。
204 = "あのくらいの魔法なら、\\n何回使っても問題ありませんから。"

# カズマ
# ゆんゆん！
252 = "ゆんゆん！"

# ゆんゆん
# な、なんでしょう！
235 = "な、なんでしょう！"

# カズマ
# アークウィザードって……すごいんだな。
255 = "アークウィザードって……すごいんだな。"

# ゆんゆん
# え？　え？\nこれくらい普通だと思いますよ？
216 = "え？　え？\\nこれくらい普通だと思いますよ？"

# カズマ
# 俺は、その普通がとても嬉しい。\n俺のパーティーにいるアークウィザードなんて\nアレだぞ。
267 = "俺は、その普通がとても嬉しい。\\n俺のパーティーにいるアークウィザードなんて\\nアレだぞ。"

# クリス
# あはは、めぐみんはねぇ、\nとてもいい子なんだけど――
205 = "あはは、めぐみんはねぇ、\\nとてもいい子なんだけど――"

# カズマ
# え？　そうか？
217 = "え？　そうか？"

# クリス
# 爆裂魔法しか使えないって聞いた時は\n極端すぎて、びっくりしたよ。
274 = "爆裂魔法しか使えないって聞いた時は\\n極端すぎて、びっくりしたよ。"

# カズマ
# だよなー！\nホント、極端すぎるんだよ！
229 = "だよなー！\\nホント、極端すぎるんだよ！"

# クリス
# でも、キミのパーティーには\nアクアさんとダクネスもいるでしょ？\n２人がなんとかしてくれるんじゃない？
234 = "でも、キミのパーティーには\\nアクアさんとダクネスもいるでしょ？\\n２人がなんとかしてくれるんじゃない？"

# カズマ
# クリス……。\nそれ、本気で言ってるのか？
260 = "クリス……。\\nそれ、本気で言ってるのか？"

# カズマ
# ダクネスが攻撃で頼りになるわけないだろ？\nいつもの調子で敵につっこんで、\n状況をめちゃくちゃにするに決まってる。
261 = "ダクネスが攻撃で頼りになるわけないだろ？\\nいつもの調子で敵につっこんで、\\n状況をめちゃくちゃにするに決まってる。"

# カズマ
# アクアはアクアで、\n攻撃もしないで無駄に大騒ぎして\n余計にモンスターを引きつけるんだ。
253 = "アクアはアクアで、\\n攻撃もしないで無駄に大騒ぎして\\n余計にモンスターを引きつけるんだ。"

# カズマ
# それに比べて、２人は本当に頼りになるぜ。\nゆんゆんは的確に魔法を使ってくれるし、\nクリスは臨機応変に動いてくれる、何よりも……。
226 = "それに比べて、２人は本当に頼りになるぜ。\\nゆんゆんは的確に魔法を使ってくれるし、\\nクリスは臨機応変に動いてくれる、何よりも……。"

# ゆんゆん
# 何よりも？
264 = "何よりも？"

# カズマ
# 俺の話をちゃんと聞いてくれる。
266 = "俺の話をちゃんと聞いてくれる。"

# クリス
# ええ？　そこから？
213 = "ええ？　そこから？"

# カズマ
# そう！　そこからなんだよ！
223 = "そう！　そこからなんだよ！"

# カズマ
# アクアは作戦立てても無視するし、\nダクネスは自分の趣味優先で動くし、\nめぐみんも爆裂魔法が絡むと暴走するし！
254 = "アクアは作戦立てても無視するし、\\nダクネスは自分の趣味優先で動くし、\\nめぐみんも爆裂魔法が絡むと暴走するし！"

# カズマ
# はああ～。\nあいつらは、俺の苦労も知らないでさぁ。
239 = "はああ～。\\nあいつらは、俺の苦労も知らないでさぁ。"

# クリス
# ……ふふっ！\nふふふふふふっ！
199 = "……ふふっ！\\nふふふふふふっ！"

# カズマ
# なんで笑ってるんだよ。
238 = "なんで笑ってるんだよ。"

# クリス
# だって、キミが面白くて。
228 = "だって、キミが面白くて。"

# カズマ
# 俺が？　面白い？
265 = "俺が？　面白い？"

# クリス
# キミね、盛大に愚痴ってるけど\n顔はなんだか楽しそうだよ？
258 = "キミね、盛大に愚痴ってるけど\\n顔はなんだか楽しそうだよ？"

# カズマ
# え？\n楽しそうって、そんなわけないだろ。
215 = "え？\\n楽しそうって、そんなわけないだろ。"

# ゆんゆん
# いえ、本当に楽しそうですよ？
208 = "いえ、本当に楽しそうですよ？"

# クリス
# だよねぇ。\nふふふふっ！
230 = "だよねぇ。\\nふふふふっ！"

# カズマ
# 楽しくなんてないんだけど？
272 = "楽しくなんてないんだけど？"

# クリス
# あれ？　そうなの？\nもしかして照れてるのかな？
206 = "あれ？　そうなの？\\nもしかして照れてるのかな？"

# カズマ
# 照れてない。\nホント、できることならこのまま２人と\nパーティーを組みたいくらいなんだって。
273 = "照れてない。\\nホント、できることならこのまま２人と\\nパーティーを組みたいくらいなんだって。"

# クリス
# ふーん、そうなんだ。\nキミ達、結構いいパーティーだと思うのになぁ。
246 = "ふーん、そうなんだ。\\nキミ達、結構いいパーティーだと思うのになぁ。"

# カズマ
# ぱっと見だと上級職３人で豪華だから\n羨ましがる連中もいるけど、\nホント、ろくでもないんだって。
242 = "ぱっと見だと上級職３人で豪華だから\\n羨ましがる連中もいるけど、\\nホント、ろくでもないんだって。"

# クリス
# そういう意味じゃないよ。\nまあ、いいけどね。
222 = "そういう意味じゃないよ。\\nまあ、いいけどね。"

# カズマ
# まあ、たまには楽しいかな。
248 = "まあ、たまには楽しいかな。"

# クリス
# たまには、なんだ。
227 = "たまには、なんだ。"

# カズマ
# でも、さっきのは戦ってる時の話で、\n命懸けなんだぜ？\n文句も言いたくなるって。
232 = "でも、さっきのは戦ってる時の話で、\\n命懸けなんだぜ？\\n文句も言いたくなるって。"

# クリス
# それじゃ、屋敷にいる時は楽しい？
225 = "それじゃ、屋敷にいる時は楽しい？"

# カズマ（Ｍ）
# display as カズマ
# （……そうじゃないって言えば嘘になるか。\n　みんなでメシ食ったりしてる時は\n　それなりに楽しいもんな）
313 = "（……そうじゃないって言えば嘘になるか。\\n　みんなでメシ食ったりしてる時は\\n　それなりに楽しいもんな）"

# クリス
# ふふーん、その顔は図星みたいだね。
245 = "ふふーん、その顔は図星みたいだね。"

# カズマ
# あいつらには言うなよ？\n特にアクアなんて、それ聞いたら\nどんな顔するか、想像しただけで腹が立つぜ。
202 = "あいつらには言うなよ？\\n特にアクアなんて、それ聞いたら\\nどんな顔するか、想像しただけで腹が立つぜ。"

# クリス
# ふふ、わかったよ。
244 = "ふふ、わかったよ。"

# カズマ
# 案外、気に入ってるのかもなぁ。
271 = "案外、気に入ってるのかもなぁ。"

# カズマ（Ｍ）
# display as カズマ
# （そうじゃなきゃ、前にもう一度死んだ時、\n　アクアの言うことなんて聞かないで\n　転生してただろうし）
315 = "（そうじゃなきゃ、前にもう一度死んだ時、\\n　アクアの言うことなんて聞かないで\\n　転生してただろうし）"

# クリス
# やっぱりそうなんだ。\nキミって案外、正直なんだね。
249 = "やっぱりそうなんだ。\\nキミって案外、正直なんだね。"

# カズマ
# ここで嘘をついても意味ないだろ。
219 = "ここで嘘をついても意味ないだろ。"

# クリス
# うんうん、キミがそういう風だから、\nダクネスやアクアさん、めぐみんも\n一緒にいようって思えるんだろうね。
211 = "うんうん、キミがそういう風だから、\\nダクネスやアクアさん、めぐみんも\\n一緒にいようって思えるんだろうね。"

# カズマ
# はあ？\nそういう風ってなんだ？
240 = "はあ？\\nそういう風ってなんだ？"

# クリス
# いいんだよ、わからなくても。\nキミはそのままでいればいいの。
207 = "いいんだよ、わからなくても。\\nキミはそのままでいればいいの。"

# カズマ
# っていうか、クリスこそ\nゆんゆんとずいぶん仲良くなってんじゃん。
231 = "っていうか、クリスこそ\\nゆんゆんとずいぶん仲良くなってんじゃん。"

# ゆんゆん
# えっ！？\nわ、私とクリスさんが友達ですか！？
214 = "えっ！？\\nわ、私とクリスさんが友達ですか！？"

# カズマ
# いや、そこまで言ってないぞ？
209 = "いや、そこまで言ってないぞ？"

# ゆんゆん
# きゃあ！？
218 = "きゃあ！？"

# カズマ
# なんだなんだ！？\nなんの音だ！？
237 = "なんだなんだ！？\\nなんの音だ！？"

# クリス
# しっ！　静かに！\nモンスターかもしれない。
221 = "しっ！　静かに！\\nモンスターかもしれない。"

# ゆんゆん
# …………。
198 = "…………。"

# カズマ
# …………。
# 198 = "…………。"

# クリス
# モンスターの気配はしないね。
262 = "モンスターの気配はしないね。"

# ゆんゆん
# 音自体、遠くから聞こえた感じでしたよね？\n何かが落ちてきたような……。
312 = "音自体、遠くから聞こえた感じでしたよね？\\n何かが落ちてきたような……。"

# カズマ（Ｍ）
# display as カズマ
# （……落ちてきた？）
314 = "（……落ちてきた？）"

# カズマ
# なあ、もしかして、俺達と同じように\n通路の仕掛けに引っかかった誰かが\n落ちてきたんじゃないか？
236 = "なあ、もしかして、俺達と同じように\\n通路の仕掛けに引っかかった誰かが\\n落ちてきたんじゃないか？"

# ゆんゆん
# でも、それって一体誰なんですか？\nこんな洞窟に入ってくる人なんて\nそうそういないと思いますよ？
233 = "でも、それって一体誰なんですか？\\nこんな洞窟に入ってくる人なんて\\nそうそういないと思いますよ？"

# クリス
# 考えられるとしたら……\n街であたし達の話を盗み聞きした連中とか？
311 = "考えられるとしたら……\\n街であたし達の話を盗み聞きした連中とか？"

# ゆんゆん
# ええっ！？
212 = "ええっ！？"

# クリス
# あくまで想像だよ。\nけど、あり得ない話じゃない。
203 = "あくまで想像だよ。\\nけど、あり得ない話じゃない。"

# カズマ
# ああ、このまま放っておいても\n面倒なことになりそうだし、戻って確かめておくか。
201 = "ああ、このまま放っておいても\\n面倒なことになりそうだし、戻って確かめておくか。"

# クリス
# うん、そうしよう。
210 = "うん、そうしよう。"

[selections]
# 272 = "楽しくなんてないんだけど？"
247 = "まぁ、たまには楽しいかな"
270 = "案外、気に入ってるのかもなぁ"
