# st04c_01.txt.scn

[info]
0 = ""

[characters]
404 = "カズマ"
399 = "アクア"
390 = "めぐみん"
415 = "ダクネス"
400 = "ウィズ"
408 = "カズマ（Ｍ）"
416 = "ダクネス＆めぐみん"
409 = "クリス"
394 = "ゆんゆん"

[character_subs]
# 404 = "カズマ"
511 = "２人"

[script]
# lines: 161

# カズマ
# おい、アクア。\nどういうことなのか説明しろ。\nなんでお前らがここにいるんだ。
311 = "おい、アクア。\\nどういうことなのか説明しろ。\\nなんでお前らがここにいるんだ。"

# アクア
# なんで私を名指しするのよ。\n別にダクネスやめぐみんでもいいと思うんですけど。
375 = "なんで私を名指しするのよ。\\n別にダクネスやめぐみんでもいいと思うんですけど。"

# カズマ
# それは、どう考えても、お前が言い出したとしか\n思えないからだよっ！
340 = "それは、どう考えても、お前が言い出したとしか\\n思えないからだよっ！"

# アクア
# な、何を根拠に言い張ってるのかしらぁ？
368 = "な、何を根拠に言い張ってるのかしらぁ？"

# カズマ
# 自分が今まで言ってきたことを\nよーく思い出してみろ。
486 = "自分が今まで言ってきたことを\\nよーく思い出してみろ。"

# カズマ
# お前、財宝報酬、財宝報酬って\n何度も何度も繰り返してたよな？
317 = "お前、財宝報酬、財宝報酬って\\n何度も何度も繰り返してたよな？"

# カズマ
# だから、留守番してろって言ったのも聞かずに\nここまで来たんだろ？
348 = "だから、留守番してろって言ったのも聞かずに\\nここまで来たんだろ？"

# アクア
# 私とカズマは、この世界に共に来た\n強い絆で結ばれている仲間じゃない。
483 = "私とカズマは、この世界に共に来た\\n強い絆で結ばれている仲間じゃない。"

# アクア
# そんな仲間の心配をして何が悪いって\nいうのかしら。
347 = "そんな仲間の心配をして何が悪いって\\nいうのかしら。"

# カズマ
# お前が心配してたのは自分の取り分だろ！
318 = "お前が心配してたのは自分の取り分だろ！"

# アクア
# だから違うわよ！\nあんたこそ、財宝とか報酬に\nこだわりすぎなんじゃない！
349 = "だから違うわよ！\\nあんたこそ、財宝とか報酬に\\nこだわりすぎなんじゃない！"

# めぐみん
# カズマ、カズマ。\nアクアは、盗賊がいるんじゃ\n信用できないって言ってましたよ。
405 = "カズマ、カズマ。\\nアクアは、盗賊がいるんじゃ\\n信用できないって言ってましたよ。"

# アクア
# な！？
376 = "な！？"

# ダクネス
# カズマなら見つけた財宝をくすねるに違いない、\n私ならそうする、とも言っていたな。
406 = "カズマなら見つけた財宝をくすねるに違いない、\\n私ならそうする、とも言っていたな。"

# アクア
# ちょっと！\nふたりだって、こっそりとあとをつけることに\n賛成したじゃない！
356 = "ちょっと！\\nふたりだって、こっそりとあとをつけることに\\n賛成したじゃない！"

# ダクネス
# クリスが心配だったからな。
410 = "クリスが心配だったからな。"

# めぐみん
# 私もまあ、同胞を心配するぐらいの優しさは\n持ち合わせているつもりなので。
485 = "私もまあ、同胞を心配するぐらいの優しさは\\n持ち合わせているつもりなので。"

# カズマ
# うーん、君たちはなんの心配をしていたのかな？
306 = "うーん、君たちはなんの心配をしていたのかな？"

# ダクネス
# それはまあ、色々だ。
342 = "それはまあ、色々だ。"

# めぐみん
# ええ、色々です。
307 = "ええ、色々です。"

# カズマ
# お前ら帰ったらヒーヒー言わせてやるから、\n覚悟しておけよ。
320 = "お前ら帰ったらヒーヒー言わせてやるから、\\n覚悟しておけよ。"

# めぐみん
# ひ、ひーひー！？
382 = "ひ、ひーひー！？"

# ダクネス
# カズマ！\nその、ヒーヒーについて詳しく！
407 = "カズマ！\\nその、ヒーヒーについて詳しく！"

# カズマ
# で？　お前らがここに来た理由はわかったけどさ、\nなんでウィズまで。
361 = "で？　お前らがここに来た理由はわかったけどさ、\\nなんでウィズまで。"

# ウィズ
# それはですね。\n今回のクエストのことを知ったからには\n生かしてはおけないと、アクア様が強引に。
341 = "それはですね。\\n今回のクエストのことを知ったからには\\n生かしてはおけないと、アクア様が強引に。"

# カズマ
# おい。
314 = "おい。"

# アクア
# それは冗談よ。
344 = "それは冗談よ。"

# アクア
# 女神の私がアンデッドに、\n戦力が不安だからついてきてなんて、\n言えるわけないじゃない。
425 = "女神の私がアンデッドに、\\n戦力が不安だからついてきてなんて、\\n言えるわけないじゃない。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、確かに）
503 = "（まあ、確かに）"

# めぐみん
# なんです？
374 = "なんです？"

# ダクネス
# なんだ？
372 = "なんだ？"

# カズマ（Ｍ）
# display as カズマ
# （このふたりじゃな）
498 = "（このふたりじゃな）"

# カズマ（Ｍ）
# display as カズマ
# （だが、いくら戦力に不安があるとはいえ、\n　アクアがウィズに頼むなんて信じられん）
500 = "（だが、いくら戦力に不安があるとはいえ、\\n　アクアがウィズに頼むなんて信じられん）"

# カズマ
# おい、駄女神。
313 = "おい、駄女神。"

# アクア
# 何よ。
420 = "何よ。"

# カズマ
# お前、どうウィズに頼んだ。\nまさか脅したんじゃないだろうな。
315 = "お前、どうウィズに頼んだ。\\nまさか脅したんじゃないだろうな。"

# アクア
# 逆に聞きますけど、どうして女神の私が、\nアンデッドなんかに頭を下げないといけないん\nですか。
490 = "逆に聞きますけど、どうして女神の私が、\\nアンデッドなんかに頭を下げないといけないん\\nですか。"

# カズマ（Ｍ）
# display as カズマ
# （こいつ、開き直りやがった！）
496 = "（こいつ、開き直りやがった！）"

# アクア
# 仕方なかったのよ。\nダクネスとめぐみんだけじゃ不安だし。
419 = "仕方なかったのよ。\\nダクネスとめぐみんだけじゃ不安だし。"

# ダクネス＆めぐみん
# display as ２人
# おい。
# 314 = "おい。"

# アクア
# それにひきかえ、\nウィズは今こそ腐ってはいるけど、\n元は凄腕のアークウィザードだったんでしょ？
337 = "それにひきかえ、\\nウィズは今こそ腐ってはいるけど、\\n元は凄腕のアークウィザードだったんでしょ？"

# ウィズ
# まだ腐ってはいません！
388 = "まだ腐ってはいません！"

# アクア
# 財宝のことを言いふらされても困るっていうのは\n正直あったからそれは否定しないわ。
489 = "財宝のことを言いふらされても困るっていうのは\\n正直あったからそれは否定しないわ。"

# アクア
# でも、戦力として助けてほしいっていうのは\n本音だったの。
360 = "でも、戦力として助けてほしいっていうのは\\n本音だったの。"

# カズマ（Ｍ）
# display as カズマ
# （はぁ、まったく……）
502 = "（はぁ、まったく……）"

# カズマ
# わかった、信じてやる。
396 = "わかった、信じてやる。"

# アクア
# それでそれで？\n財宝は見つかったのかしら。
335 = "それでそれで？\\n財宝は見つかったのかしら。"

# カズマ
# ちゃんとお守りしてくれよ、\nダクネスにめぐみん……。
354 = "ちゃんとお守りしてくれよ、\\nダクネスにめぐみん……。"

# めぐみん
# それはカズマの役目でしょう。
343 = "それはカズマの役目でしょう。"

# ダクネス
# うむ。\n私達の手に負えるものではない。
302 = "うむ。\\n私達の手に負えるものではない。"

# カズマ
# いつから俺は駄女神の介護役になったんだよ！
299 = "いつから俺は駄女神の介護役になったんだよ！"

# アクア
# そうよ！\nこの私がカズマを導いてるんですけど！？
331 = "そうよ！\\nこの私がカズマを導いてるんですけど！？"

# カズマ
# ちっとも導かれてねーし！\nむしろ全力で足引っ張ってるから！
352 = "ちっとも導かれてねーし！\\nむしろ全力で足引っ張ってるから！"

# アクア
# まあいいわ。
387 = "まあいいわ。"

# カズマ（Ｍ）
# display as カズマ
# （よくねーよ）
504 = "（よくねーよ）"

# アクア
# それで、財宝あったの？　あったのよね？
334 = "それで、財宝あったの？　あったのよね？"

# カズマ
# ウィズ、断ってくれてよかったんだぞ。
401 = "ウィズ、断ってくれてよかったんだぞ。"

# ウィズ
# お店がありますし、そうしたかったのですが。
321 = "お店がありますし、そうしたかったのですが。"

# カズマ
# 断れない理由が何かあったと。
432 = "断れない理由が何かあったと。"

# ウィズ
# 手を握られて笑顔ですごまれては。
431 = "手を握られて笑顔ですごまれては。"

# アクア
# ～～～～♪
512 = "～～～～♪"

# カズマ（Ｍ）
# display as カズマ
# （こいつ、女神の皮を被った\n　悪魔なんじゃねーか？）
495 = "（こいつ、女神の皮を被った\\n　悪魔なんじゃねーか？）"

# ダクネス
# それで？　調査の方はどうなんだ？
336 = "それで？　調査の方はどうなんだ？"

# アクア
# そうよ、それよ！\n財宝はどこにあるの！
330 = "そうよ、それよ！\\n財宝はどこにあるの！"

# カズマ（Ｍ）
# display as カズマ
# （切り替え早っ！）
507 = "（切り替え早っ！）"

# クリス
# 残念ながら、まだ見つかってないんだ。
435 = "残念ながら、まだ見つかってないんだ。"

# アクア
# だったらすぐに探しましょうよ！
350 = "だったらすぐに探しましょうよ！"

# ゆんゆん
# それがそうもいかないんです。
333 = "それがそうもいかないんです。"

# ウィズ
# そういえば、慌てて戻って来た様子でしたが。
327 = "そういえば、慌てて戻って来た様子でしたが。"

# ダクネス
# この奥に何かあったのか？
323 = "この奥に何かあったのか？"

# カズマ
# ああ、やばいのが寝てた。
292 = "ああ、やばいのが寝てた。"

# アクア
# そんなこと言っちゃってー。\n本当は財宝があって、\n私たちに隠してるんでしょ。
346 = "そんなこと言っちゃってー。\\n本当は財宝があって、\\n私たちに隠してるんでしょ。"

# カズマ（Ｍ）
# display as カズマ
# （あー、頭がお花畑のやつはいいなー）
492 = "（あー、頭がお花畑のやつはいいなー）"

# クリス
# あはは、それだったらよかったんだけどね。
296 = "あはは、それだったらよかったんだけどね。"

# ゆんゆん
# ここ、この奥に、スカルドラゴンがいるんです。
322 = "ここ、この奥に、スカルドラゴンがいるんです。"

# ウィズ
# スカルドラゴンって、\n死竜のスカルドラゴンですか？
412 = "スカルドラゴンって、\\n死竜のスカルドラゴンですか？"

# クリス
# うん、間違いないと思うよ。
305 = "うん、間違いないと思うよ。"

# ダクネス
# なぜ、そんな大物がここに？\n私達は何も聞かされていないぞ？
369 = "なぜ、そんな大物がここに？\\n私達は何も聞かされていないぞ？"

# ウィズ
# それほどの大物なら\nギルドが把握しているはずです。
345 = "それほどの大物なら\\nギルドが把握しているはずです。"

# クリス
# ということは、最近、住み着いたんじゃない？
362 = "ということは、最近、住み着いたんじゃない？"

# カズマ
# 最近？
434 = "最近？"

# クリス
# ん？　どうかした？
398 = "ん？　どうかした？"

# カズマ（Ｍ）
# display as カズマ
# （あ、わかっちゃった……）
491 = "（あ、わかっちゃった……）"

# ダクネス
# どうかしたか、カズマ。
367 = "どうかしたか、カズマ。"

# カズマ
# いや、なんでもない。
300 = "いや、なんでもない。"

# カズマ（Ｍ）
# display as カズマ
# （盗賊団が急に静かになったのは、\n　あのスカルドラゴンに……）
508 = "（盗賊団が急に静かになったのは、\\n　あのスカルドラゴンに……）"

# めぐみん
# ふふん。\nそのようなことは些事に過ぎん。\n肝心なのは、今、ここに奴が存在する事実。
386 = "ふふん。\\nそのようなことは些事に過ぎん。\\n肝心なのは、今、ここに奴が存在する事実。"

# めぐみん
# ふっふっふ、、相手にとって不足なし！\n我が爆裂魔法がどれほどのものか、\n腐りし魂を孕む不浄の竜に見せつけてくれる！
385 = "ふっふっふ、、相手にとって不足なし！\\n我が爆裂魔法がどれほどのものか、\\n腐りし魂を孕む不浄の竜に見せつけてくれる！"

# めぐみん
# という訳なので、討伐してしまいましょうっ！
364 = "という訳なので、討伐してしまいましょうっ！"

# カズマ
# どういう訳だよ。\nお前は爆裂魔法を撃ちたいだけだろ。
366 = "どういう訳だよ。\\nお前は爆裂魔法を撃ちたいだけだろ。"

# めぐみん
# それの何が悪いんですか！
339 = "それの何が悪いんですか！"

# カズマ（Ｍ）
# display as カズマ
# （言い切ったよ、こいつ！）
509 = "（言い切ったよ、こいつ！）"

# ダクネス
# スカルドラゴンはアンデッドモンスターだ。\nめぐみんではなく、アクアの出番じゃないか？
413 = "スカルドラゴンはアンデッドモンスターだ。\\nめぐみんではなく、アクアの出番じゃないか？"

# クリス
# あ、そうだよ！\n魔王軍の幹部だって浄化できたんだから、\nスカルドラゴンもいけるんじゃない？
291 = "あ、そうだよ！\\n魔王軍の幹部だって浄化できたんだから、\\nスカルドラゴンもいけるんじゃない？"

# アクア
# えー？
308 = "えー？"

# カズマ
# なんだ、その不満そうな顔は。\nいつものお前なら喜んで浄化するじゃないか。\nそれが女神の役目だって。
370 = "なんだ、その不満そうな顔は。\\nいつものお前なら喜んで浄化するじゃないか。\\nそれが女神の役目だって。"

# アクア
# だって、そのドラゴンって\n懸賞金かかってないでしょ？
351 = "だって、そのドラゴンって\\n懸賞金かかってないでしょ？"

# カズマ
# は？　懸賞金？
381 = "は？　懸賞金？"

# アクア
# せっかくの大物なんだし、\nギルドに報告して懸賞金がかかってから\n討伐しましょうよ。
325 = "せっかくの大物なんだし、\\nギルドに報告して懸賞金がかかってから\\n討伐しましょうよ。"

# アクア
# うん、それがいいわ。\n街の近くにスカルドラゴンがいるとなれば、\n高額な懸賞金がかかると思うし。
304 = "うん、それがいいわ。\\n街の近くにスカルドラゴンがいるとなれば、\\n高額な懸賞金がかかると思うし。"

# カズマ
# はあああああ！？\nお前、なに言ってるんだ？
380 = "はあああああ！？\\nお前、なに言ってるんだ？"

# クリス
# 確かに、スカルドラゴンともなれば\nかなりの額の懸賞金がかかりそうだけど。
482 = "確かに、スカルドラゴンともなれば\\nかなりの額の懸賞金がかかりそうだけど。"

# アクア
# でしょ？\nここで勝手に倒したところで\n誰も褒めてくれないわ。
358 = "でしょ？\\nここで勝手に倒したところで\\n誰も褒めてくれないわ。"

# アクア
# でも、懸賞金がかかれば……。
359 = "でも、懸賞金がかかれば……。"

# カズマ
# お前の行動動機の最優先はとことんまで金か！
319 = "お前の行動動機の最優先はとことんまで金か！"

# アクア
# そうよ！　それの何が悪いのかしら！
332 = "そうよ！　それの何が悪いのかしら！"

# カズマ
# いや、悪い……だろ？\nあれ？　悪くないのか？
301 = "いや、悪い……だろ？\\nあれ？　悪くないのか？"

# アクア
# ねえ、これまでお金のことで、\n私に苦労をかけてきたのはどこの誰。
377 = "ねえ、これまでお金のことで、\\n私に苦労をかけてきたのはどこの誰。"

# カズマ（Ｍ）
# display as カズマ
# （え、何その言い方。\n　まるで俺が悪いみたいじゃん）
494 = "（え、何その言い方。\\n　まるで俺が悪いみたいじゃん）"

# アクア
# 女神の私を馬小屋に寝かせるだけでも\n許しがたい罪なのに肉体労働までさせて。
426 = "女神の私を馬小屋に寝かせるだけでも\\n許しがたい罪なのに肉体労働までさせて。"

# アクア
# さらには、コロッケの手売りに造花の内職。
324 = "さらには、コロッケの手売りに造花の内職。"

# アクア
# ねえ、造花の単価知ってる？\n５エリスよ、５エリス。
378 = "ねえ、造花の単価知ってる？\\n５エリスよ、５エリス。"

# アクア
# 手がカサカサに荒れるまで頑張っても、\n１日、５００エリスも稼げないの。
430 = "手がカサカサに荒れるまで頑張っても、\\n１日、５００エリスも稼げないの。"

# カズマ
# …………。
290 = "…………。"

# アクア
# 私はもっと楽したいの、甘やかされたいの！\nみんなにちやほやされながら生きて行きたいのよ！
484 = "私はもっと楽したいの、甘やかされたいの！\\nみんなにちやほやされながら生きて行きたいのよ！"

# カズマ（Ｍ）
# display as カズマ
# （駄目な発想のオンパレードだ！）
510 = "（駄目な発想のオンパレードだ！）"

# アクア
# というわけで、懸賞金がかかるまで\nスカルドラゴンの討伐には手を貸しませんから。
363 = "というわけで、懸賞金がかかるまで\\nスカルドラゴンの討伐には手を貸しませんから。"

# カズマ
# 今はそんなこと言ってる場合か？\nホントに空気読めよ！　この駄女神！
418 = "今はそんなこと言ってる場合か？\\nホントに空気読めよ！　この駄女神！"

# ダクネス
# 言い争っている場合でもないぞ、カズマ。
487 = "言い争っている場合でもないぞ、カズマ。"

# カズマ
# あん、なんでだよ！
298 = "あん、なんでだよ！"

# ダクネス
# めぐみんが洞窟の奥へ向かおうとしてる。
391 = "めぐみんが洞窟の奥へ向かおうとしてる。"

# めぐみん
# ふっ、スカルドラゴンだろうと、\n我が爆裂魔法の前ではひれ伏すことしか叶わず。
383 = "ふっ、スカルドラゴンだろうと、\\n我が爆裂魔法の前ではひれ伏すことしか叶わず。"

# カズマ
# って、お前は事態をややこしくするな！
357 = "って、お前は事態をややこしくするな！"

# クリス
# あのさ、みんな。\nこんなところでもたもたしてたら\nスカルドラゴンに見つかっちゃうよ？
295 = "あのさ、みんな。\\nこんなところでもたもたしてたら\\nスカルドラゴンに見つかっちゃうよ？"

# カズマ
# そうだよ！\n今ってかなりピンチなんだぞ！？
329 = "そうだよ！\\n今ってかなりピンチなんだぞ！？"

# カズマ
# おい、アクア。\n懸賞金よりも命のほうが大事だろ？\nスカルドラゴンを浄化してくれよ。
312 = "おい、アクア。\\n懸賞金よりも命のほうが大事だろ？\\nスカルドラゴンを浄化してくれよ。"

# アクア
# 嫌よ！
427 = "嫌よ！"

# カズマ（Ｍ）
# display as カズマ
# （こいつっ……）
497 = "（こいつっ……）"

# ダクネス
# やれやれ。\nこれはもう、アクアの浄化魔法は\n諦めたほうがいいな。
393 = "やれやれ。\\nこれはもう、アクアの浄化魔法は\\n諦めたほうがいいな。"

# めぐみん
# スチャ！\n眼帯を装備しました。
414 = "スチャ！\\n眼帯を装備しました。"

# カズマ
# わけわかんねーから！
397 = "わけわかんねーから！"

# めぐみん
# ふっ、本気モードです。
384 = "ふっ、本気モードです。"

# カズマ
# お前、本当に奥歯がたがたいわせんぞ！
316 = "お前、本当に奥歯がたがたいわせんぞ！"

# ダクネス
# そ、その、奥歯がたがたについて詳しく！
326 = "そ、その、奥歯がたがたについて詳しく！"

# カズマ
# もうやだ、帰りたい……。
392 = "もうやだ、帰りたい……。"

# クリス
# あはは、苦労するね。
297 = "あはは、苦労するね。"

# ゆんゆん
# あのあの、とりあえず状況を整理しませんか？
294 = "あのあの、とりあえず状況を整理しませんか？"

# カズマ（Ｍ）
# display as カズマ
# （うぅ、ゆんゆんが頼もしい）
493 = "（うぅ、ゆんゆんが頼もしい）"

# ゆんゆん
# 出口は、入ってきたところ以外には\nなさそうですよね。
422 = "出口は、入ってきたところ以外には\\nなさそうですよね。"

# クリス
# ちゃんとは調べていないけどね。
355 = "ちゃんとは調べていないけどね。"

# ダクネス
# 最悪、スカルドラゴンが眠る先へと\n進まないといけないわけか。
433 = "最悪、スカルドラゴンが眠る先へと\\n進まないといけないわけか。"

# ウィズ
# スカルドラゴンが眠る場所を通り抜けるのは、\n至難の業ですよ。
411 = "スカルドラゴンが眠る場所を通り抜けるのは、\\n至難の業ですよ。"

# カズマ
# そうだ、ウィズがいるじゃないか！
328 = "そうだ、ウィズがいるじゃないか！"

# ウィズ
# え？　私ですか？
309 = "え？　私ですか？"

# カズマ
# ウィズはアンデッドの王なんだから、\nスカルドラゴンも言うことを聞くだろ。
403 = "ウィズはアンデッドの王なんだから、\\nスカルドラゴンも言うことを聞くだろ。"

# ウィズ
# 元とはいえ、ドラゴン族ですからね。\n彼らはプライドが高いので、\n耳も貸してくれないかと。
421 = "元とはいえ、ドラゴン族ですからね。\\n彼らはプライドが高いので、\\n耳も貸してくれないかと。"

# カズマ（Ｍ）
# display as カズマ
# （なんなのそれ、\n　モンスターにも意識高い系とかあるわけ！）
501 = "（なんなのそれ、\\n　モンスターにも意識高い系とかあるわけ！）"

# ウィズ
# それに私……リッチーがいると知ったら、\n戦いを挑んでくる可能性もあります。
338 = "それに私……リッチーがいると知ったら、\\n戦いを挑んでくる可能性もあります。"

# カズマ（Ｍ）
# display as カズマ
# （マジかー）
506 = "（マジかー）"

# ウィズ
# 負ける気はしませんが、\nさすがに近隣の街に、\n甚大な被害が出るのではないかと。
488 = "負ける気はしませんが、\\nさすがに近隣の街に、\\n甚大な被害が出るのではないかと。"

# カズマ
# あの、今さらっとすごいこと言いませんでした？
293 = "あの、今さらっとすごいこと言いませんでした？"

# ウィズ
# え？　負ける気はしないと言っただけですが……\nそれが何か？
310 = "え？　負ける気はしないと言っただけですが……\\nそれが何か？"

# カズマ（Ｍ）
# display as カズマ
# （そうですよね！\n　ウィズって魔王軍の幹部であり\n　アンデッドの王ですもんね！）
499 = "（そうですよね！\\n　ウィズって魔王軍の幹部であり\\n　アンデッドの王ですもんね！）"

# ダクネス
# 現有戦力では倒せる方法はなさそうだ。\nとなると、やはり出口を探すしかないか。
437 = "現有戦力では倒せる方法はなさそうだ。\\nとなると、やはり出口を探すしかないか。"

# クリス
# とりあえずさ、スカルドラゴンの場所は\n後にして、まずはこの辺で出口を探してみようよ。
365 = "とりあえずさ、スカルドラゴンの場所は\\n後にして、まずはこの辺で出口を探してみようよ。"

# ゆんゆん
# は、はい！\nこういう時こそ前向きですね。
379 = "は、はい！\\nこういう時こそ前向きですね。"

# クリス
# うん、そうだよ。
303 = "うん、そうだよ。"

# めぐみん
# むう……。
389 = "むう……。"

# カズマ
# なんだ、めぐみん。\nゆんゆんをクリスに取られたと思ってるのか？
371 = "なんだ、めぐみん。\\nゆんゆんをクリスに取られたと思ってるのか？"

# めぐみん
# なんですかそれ？\nわけわかりませんよ。
373 = "なんですかそれ？\\nわけわかりませんよ。"

# カズマ（Ｍ）
# display as カズマ
# （ホント、素直じゃないよなぁ）
505 = "（ホント、素直じゃないよなぁ）"

[selections]
395 = "わかった、信じてやる"
353 = "ちゃんとお守りしてくれよ……"
402 = "ウィズ、断ってくれてよかったんだぞ？"
