# st04a_01.txt.scn

[info]
0 = ""

[characters]
137 = "カズマ"
138 = "カズマ（Ｍ）"

[character_subs]
# 137 = "カズマ"

[script]
# lines: 17

# カズマ
# …………。
135 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、この感触は……）
144 = "（ああ、この感触は……）"

# カズマ
# はあ……。\nやっぱりそうなるよなぁ。
136 = "はあ……。\\nやっぱりそうなるよなぁ。"

# カズマ（Ｍ）
# display as カズマ
# （なんて声を出してしまうのを止められない。\n　その原因はもちろん――）
152 = "（なんて声を出してしまうのを止められない。\\n　その原因はもちろん――）"

# カズマ（Ｍ）
# display as カズマ
# （４枚、４枚か。\n　着実に増えてるな）
158 = "（４枚、４枚か。\\n　着実に増えてるな）"

# カズマ（Ｍ）
# display as カズマ
# （つまり、確実に命を削り取られてるわけで。\n　このままだとバニルが言ったとおり、\n　俺は死ぬことになるのか）
150 = "（つまり、確実に命を削り取られてるわけで。\\n　このままだとバニルが言ったとおり、\\n　俺は死ぬことになるのか）"

# カズマ（Ｍ）
# display as カズマ
# （ホント、冗談じゃねーぞ！？\n　パンツで死ぬなんて、\n　そんなバカバカしい死因があってたまるかよ！）
155 = "（ホント、冗談じゃねーぞ！？\\n　パンツで死ぬなんて、\\n　そんなバカバカしい死因があってたまるかよ！）"

# カズマ（Ｍ）
# display as カズマ
# （って、そういや、このろくでもない世界に\n　来ることになった俺の死因って……）
148 = "（って、そういや、このろくでもない世界に\\n　来ることになった俺の死因って……）"

# カズマ（Ｍ）
# display as カズマ
# （ダメだ、思いださないようにしよう。\n　うん、そうしよう）
154 = "（ダメだ、思いださないようにしよう。\\n　うん、そうしよう）"

# カズマ（Ｍ）
# display as カズマ
# （ともかく、この４枚も\n　ちゃんと持ち主に返さないと。\n　紳士である俺にできるのはそれだけだ）
151 = "（ともかく、この４枚も\\n　ちゃんと持ち主に返さないと。\\n　紳士である俺にできるのはそれだけだ）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、パンツを返すだけじゃなくて\n　本気で金を稼ぐ方法を考えないとな）
147 = "（しかし、パンツを返すだけじゃなくて\\n　本気で金を稼ぐ方法を考えないとな）"

# カズマ（Ｍ）
# display as カズマ
# （別に、今まで\n　本気じゃなかったわけじゃねーけど！\n　すっげー真面目にやってたけど！）
157 = "（別に、今まで\\n　本気じゃなかったわけじゃねーけど！\\n　すっげー真面目にやってたけど！）"

# カズマ（Ｍ）
# display as カズマ
# （にしても、元の世界の商売方法は\n　もう弾切れって感じだしな）
153 = "（にしても、元の世界の商売方法は\\n　もう弾切れって感じだしな）"

# カズマ（Ｍ）
# display as カズマ
# （何をやるにしても\n　全てのレベルが中世水準のこの世界じゃ\n　どれもハードルが高すぎる）
156 = "（何をやるにしても\\n　全てのレベルが中世水準のこの世界じゃ\\n　どれもハードルが高すぎる）"

# カズマ（Ｍ）
# display as カズマ
# （って、俺がそんなに後ろ向きになってどうする！\n　他の連中はあてにできないんだ。\n　俺がなんとかしないと）
149 = "（って、俺がそんなに後ろ向きになってどうする！\\n　他の連中はあてにできないんだ。\\n　俺がなんとかしないと）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、でも俺だけで\n　なんとかできるもんでもないんだよなぁ）
145 = "（ああ、でも俺だけで\\n　なんとかできるもんでもないんだよなぁ）"

# カズマ（Ｍ）
# display as カズマ
# （ここで悩んでいても仕方ない。\n　とりあえず、起きてみんなと相談するか）
146 = "（ここで悩んでいても仕方ない。\\n　とりあえず、起きてみんなと相談するか）"

