# st04b_09.txt.scn

[info]
0 = ""

[characters]
222 = "カズマ（Ｍ）"
221 = "カズマ"
225 = "クリス"
214 = "ゆんゆん"
219 = "アクア"
213 = "めぐみん"
226 = "ダクネス"
220 = "ウィズ"

[character_subs]
# 221 = "カズマ"
270 = "？？？"

[script]
# lines: 57

# カズマ（Ｍ）
# display as カズマ
# （結局、音の正体はわからないまま、\n　俺達は慎重に洞窟を進んでいった）
269 = "（結局、音の正体はわからないまま、\\n　俺達は慎重に洞窟を進んでいった）"

# カズマ（Ｍ）
# display as カズマ
# （幸い、モンスターに遭遇することもなく\n　順調だったんだけど……）
268 = "（幸い、モンスターに遭遇することもなく\\n　順調だったんだけど……）"

# カズマ（Ｍ）
# display as カズマ
# （そこに足を踏み入れた瞬間、\n　クリスも俺も、そしてゆんゆんも足を止めた）
262 = "（そこに足を踏み入れた瞬間、\\n　クリスも俺も、そしてゆんゆんも足を止めた）"

# カズマ
# ……なあ、感じるよな？
180 = "……なあ、感じるよな？"

# クリス
# うん。\nこれは……ちょっとまずいね。
187 = "うん。\\nこれは……ちょっとまずいね。"

# ゆんゆん
# はい。\nすごく嫌な予感がします。
209 = "はい。\\nすごく嫌な予感がします。"

# カズマ（Ｍ）
# display as カズマ
# （はっきりとわかるくらいに異様な気配がする。\n　まるで空気が体にまとわりついてくるみたいだ）
266 = "（はっきりとわかるくらいに異様な気配がする。\\n　まるで空気が体にまとわりついてくるみたいだ）"

# カズマ
# なんなんだ、これ。\nまた罠なのか？
206 = "なんなんだ、これ。\\nまた罠なのか？"

# クリス
# わからない。\n何か、モンスターがいるんじゃないかと\n思うんだけど。
216 = "わからない。\\n何か、モンスターがいるんじゃないかと\\n思うんだけど。"

# ゆんゆん
# モンスター……ですか？
229 = "モンスター……ですか？"

# カズマ
# でも、俺もクリスも、ここに来るまで\nまったくモンスターの気配を感じなかったよな？
203 = "でも、俺もクリスも、ここに来るまで\\nまったくモンスターの気配を感じなかったよな？"

# クリス
# そうなんだよね。\nだから、もしモンスターだとしたら――
196 = "そうなんだよね。\\nだから、もしモンスターだとしたら――"

# クリス
# 自分自身の気配を消せるような、\n知能のある大物だってことになるよ。
258 = "自分自身の気配を消せるような、\\n知能のある大物だってことになるよ。"

# カズマ
# はああ！？\nここには大物のモンスターなんていないって\n聞いてたぞ！？
208 = "はああ！？\\nここには大物のモンスターなんていないって\\n聞いてたぞ！？"

# クリス
# ギルドも、落とし穴から先については\nまったく考慮に入れてなかったってことだね。
224 = "ギルドも、落とし穴から先については\\nまったく考慮に入れてなかったってことだね。"

# ゆんゆん
# と、とりあえず、確認してみませんか？\nモンスターと決まったわけじゃないですから。
204 = "と、とりあえず、確認してみませんか？\\nモンスターと決まったわけじゃないですから。"

# カズマ
# お、おう、そうだな。
189 = "お、おう、そうだな。"

# カズマ（Ｍ）
# display as カズマ
# （うなずき合った俺達は、\n　おそるおそる先に進んで――）
261 = "（うなずき合った俺達は、\\n　おそるおそる先に進んで――）"

# カズマ（Ｍ）
# display as カズマ
# （それを見つけてしまった）
263 = "（それを見つけてしまった）"

# カズマ
# ん？　なんだ？\nあれって骨？　恐竜かなんかの骨か？
218 = "ん？　なんだ？\\nあれって骨？　恐竜かなんかの骨か？"

# クリス
# 静かに！
260 = "静かに！"

# ゆんゆん
# う、嘘……！\nあれって、まさか！？
184 = "う、嘘……！\\nあれって、まさか！？"

# クリス
# ちょっと、これは……\nシャレになってないじゃない！
201 = "ちょっと、これは……\\nシャレになってないじゃない！"

# カズマ
# ん？　どうしたんだ？\nあの骨がどうかしたのか？
217 = "ん？　どうしたんだ？\\nあの骨がどうかしたのか？"

# カズマ
# しかし、キレイに残ってるなぁ。\nまるで生きてるみたいだ。
194 = "しかし、キレイに残ってるなぁ。\\nまるで生きてるみたいだ。"

# ゆんゆん
# みたいじゃなくて生きてます。
210 = "みたいじゃなくて生きてます。"

# ゆんゆん
# あ、でも、アンデッドだから生きてるとは\n言わないのかな？
181 = "あ、でも、アンデッドだから生きてるとは\\n言わないのかな？"

# ゆんゆん
# こ、細かいことはわかりませんけど！\nとにかく、あれはモンスターなんです！
192 = "こ、細かいことはわかりませんけど！\\nとにかく、あれはモンスターなんです！"

# カズマ
# モンスター？
230 = "モンスター？"

# クリス
# キミ、もしかして\nあれがなんだかわかってない？
223 = "キミ、もしかして\\nあれがなんだかわかってない？"

# クリス
# あれはスカルドラゴン。\nアンデッドモンスターだけど、普通のドラゴンと\n変わらない強さの、大物だよ。
182 = "あれはスカルドラゴン。\\nアンデッドモンスターだけど、普通のドラゴンと\\n変わらない強さの、大物だよ。"

# カズマ
# は……。\nはああああああっ！？\nド、ド、ド、ドラゴン！？
207 = "は……。\\nはああああああっ！？\\nド、ド、ド、ドラゴン！？"

# クリス
# こら！　声が大きい！\n気がつかれたらどうするのよ！？
193 = "こら！　声が大きい！\\n気がつかれたらどうするのよ！？"

# カズマ
# っていうか、気がつかれる前に逃げるぞ！\nドラゴンなんて相手にしてられるかっ！
202 = "っていうか、気がつかれる前に逃げるぞ！\\nドラゴンなんて相手にしてられるかっ！"

# クリス
# だから、落ち着きなさい。\n慌てて行動したら見つかるから。
198 = "だから、落ち着きなさい。\\n慌てて行動したら見つかるから。"

# クリス
# すぐにでも逃げたい気持ちはわかるけど、\nなるべく静かに、ゆっくり戻るの。\nゆんゆんも、いい？
195 = "すぐにでも逃げたい気持ちはわかるけど、\\nなるべく静かに、ゆっくり戻るの。\\nゆんゆんも、いい？"

# ゆんゆん
# わ、わかりました。
215 = "わ、わかりました。"

# カズマ
# …………。
179 = "…………。"

# クリス
# …………。
# 179 = "…………。"

# ゆんゆん
# …………。
# 179 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （スカルドラゴンからは結構離れたはず。\n　でも俺達は、黙りこくったまま\n　そろそろと来た道を戻っていた）
267 = "（スカルドラゴンからは結構離れたはず。\\n　でも俺達は、黙りこくったまま\\n　そろそろと来た道を戻っていた）"

# カズマ（Ｍ）
# display as カズマ
# （つか、なんだよドラゴンって！\n　なんでそんな大物が出てくるんだよ！\n　空気読めよ～！！）
264 = "（つか、なんだよドラゴンって！\\n　なんでそんな大物が出てくるんだよ！\\n　空気読めよ～！！）"

# カズマ
# うわっ！？
186 = "うわっ！？"

# アクア
# display as ？？？
# きゃあああああああああ！！
190 = "きゃあああああああああ！！"

# カズマ
# うおおおっ！　なんだ！？
185 = "うおおおっ！　なんだ！？"

# めぐみん
# display as ？？？
# いやあああああああああああ！！
183 = "いやあああああああああああ！！"

# クリス
# な、なに！？
205 = "な、なに！？"

# ダクネス
# 貴様、何者だっ！\n仲間に手を出すのなら、\nまずこの私を倒してからにしてもらおう！
259 = "貴様、何者だっ！\\n仲間に手を出すのなら、\\nまずこの私を倒してからにしてもらおう！"

# クリス
# ダクネス！？
227 = "ダクネス！？"

# カズマ
# それにアクアと――
197 = "それにアクアと――"

# めぐみん
# く、黒より、黒く、\nや、や、闇より、昏き、漆黒に――
191 = "く、黒より、黒く、\\nや、や、闇より、昏き、漆黒に――"

# カズマ
# ちょっ、お前、バカーー！！
200 = "ちょっ、お前、バカーー！！"

# ゆんゆん
# め、めぐみん、落ち着いて！\nこんなところで爆裂魔法はダメだよ！
212 = "め、めぐみん、落ち着いて！\\nこんなところで爆裂魔法はダメだよ！"

# めぐみん
# え、ゆんゆん？
188 = "え、ゆんゆん？"

# ウィズ
# みなさん、ご無事なようで安心しました。
211 = "みなさん、ご無事なようで安心しました。"

# カズマ（Ｍ）
# display as カズマ
# （はあ？　ウィズまで！？）
265 = "（はあ？　ウィズまで！？）"

# カズマ
# ちょ、ちょっと待て！\nなんでお前ら、ここにいるんだよ！？
199 = "ちょ、ちょっと待て！\\nなんでお前ら、ここにいるんだよ！？"

