# st04a_07.txt.scn

[info]
0 = ""

[characters]
256 = "ダクネス"
242 = "めぐみん"
253 = "クリス"
250 = "カズマ"
248 = "アクア"
252 = "カズマ（Ｍ）"

[character_subs]
# 250 = "カズマ"

[script]
# lines: 71

# ダクネス
# ああ、やはりここだったな。
207 = "ああ、やはりここだったな。"

# めぐみん
# あの後ろ姿は確かにクリスですね。
210 = "あの後ろ姿は確かにクリスですね。"

# ダクネス
# クリス！
255 = "クリス！"

# クリス
# ん？\nその声はダクネス？
247 = "ん？\\nその声はダクネス？"

# クリス
# ええっ！？\nな、なんでキミまでいるの！？
216 = "ええっ！？\\nな、なんでキミまでいるの！？"

# カズマ
# え？　俺？\nなんでって言われても。
218 = "え？　俺？\\nなんでって言われても。"

# ダクネス
# 別に、カズマが私達と一緒にいても\nおかしくはないだろう。
263 = "別に、カズマが私達と一緒にいても\\nおかしくはないだろう。"

# めぐみん
# 一応、同じパーティーなのですからね。
258 = "一応、同じパーティーなのですからね。"

# カズマ
# 一応ってなんだ、一応って。
259 = "一応ってなんだ、一応って。"

# クリス
# あ、ああ、そうだよね。\nうん、ごめん、なんか混乱しちゃって。\nあはははは。
205 = "あ、ああ、そうだよね。\\nうん、ごめん、なんか混乱しちゃって。\\nあはははは。"

# クリス
# ところで……あたしになにか用なのかな？
230 = "ところで……あたしになにか用なのかな？"

# アクア
# %fsyogen;ねえ、カズマ？\nあんた、クリスに何かしたの？\n妙に不機嫌じゃない。
17 = "%fsyogen;ねえ、カズマ？\\nあんた、クリスに何かしたの？\\n妙に不機嫌じゃない。"

# カズマ
# いや、身に覚えはないんだけど。
213 = "いや、身に覚えはないんだけど。"

# カズマ（Ｍ）
# display as カズマ
# （本当になんでなんだ？\n　クリスって普段はニコニコしてるから、\n　ああいう態度を取られると堪えるぜ）
316 = "（本当になんでなんだ？\\n　クリスって普段はニコニコしてるから、\\n　ああいう態度を取られると堪えるぜ）"

# カズマ（Ｍ）
# display as カズマ
# （ん、待てよ。\n　もしかしたら不機嫌の原因は……）
313 = "（ん、待てよ。\\n　もしかしたら不機嫌の原因は……）"

# カズマ（Ｍ）
# display as カズマ
# （よし、証言としてゲットしておこう！）
312 = "（よし、証言としてゲットしておこう！）"

# ダクネス
# クリス。\n実は、折り入って頼みがあるんだ。
254 = "クリス。\\n実は、折り入って頼みがあるんだ。"

# クリス
# ……頼み？
204 = "……頼み？"

# クリス
# って、まあ、なんとなくわかるけどね。\n呪いの指輪関連でしょ。
228 = "って、まあ、なんとなくわかるけどね。\\n呪いの指輪関連でしょ。"

# カズマ
# ああ、そうなんだ。\n話が早くて助かるよ。
206 = "ああ、そうなんだ。\\n話が早くて助かるよ。"

# クリス
# まあ、もう慣れてきたから。
240 = "まあ、もう慣れてきたから。"

# カズマ（Ｍ）
# display as カズマ
# （うう、やっぱり俺への態度が硬い！\n　パンツを盗んでしまった前科があるとはいえ、\n　ここまであからさまにされるとキツイ！）
311 = "（うう、やっぱり俺への態度が硬い！\\n　パンツを盗んでしまった前科があるとはいえ、\\n　ここまであからさまにされるとキツイ！）"

# カズマ
# ダクネス、説明頼むわ。
257 = "ダクネス、説明頼むわ。"

# ダクネス
# 実は、ギルドから実入りの良いクエストを\n紹介してもらったんだ。
268 = "実は、ギルドから実入りの良いクエストを\\n紹介してもらったんだ。"

# ダクネス
# ただ、私達だけでは力不足なので、\n手を貸してもらえないだろうか。
225 = "ただ、私達だけでは力不足なので、\\n手を貸してもらえないだろうか。"

# クリス
# へえ、どんなクエストなの？
238 = "へえ、どんなクエストなの？"

# ダクネス
# 盗賊団が根城にしていた洞窟の調査だ。\nどうやらそこに、奴らが盗んだ財宝が――
274 = "盗賊団が根城にしていた洞窟の調査だ。\\nどうやらそこに、奴らが盗んだ財宝が――"

# アクア
# あーあーあーあーあー！
211 = "あーあーあーあーあー！"

# ダクネス
# な、なんだ？\nどうしたんだ、アクア。
234 = "な、なんだ？\\nどうしたんだ、アクア。"

# アクア
# 私から説明するわ！\nあのね、詳しい事はまだ話せないんだけど、\nギルドが最近発見した、とある洞窟の調査なのよ！
307 = "私から説明するわ！\\nあのね、詳しい事はまだ話せないんだけど、\\nギルドが最近発見した、とある洞窟の調査なのよ！"

# クリス
# は、はあ。
236 = "は、はあ。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、財宝のことを極力話したくないんだな。\n　このがめつい女神め）
309 = "（ああ、財宝のことを極力話したくないんだな。\\n　このがめつい女神め）"

# クリス
# 洞窟の調査ってそんなに難しくないよね？\nどうして、あたしの力が欲しいのかな？
272 = "洞窟の調査ってそんなに難しくないよね？\\nどうして、あたしの力が欲しいのかな？"

# アクア
# 事情があって、\n洞窟に行けるのがカズマだけなのよ。\nだから、カズマと２人で行ってきて欲しいの。
261 = "事情があって、\\n洞窟に行けるのがカズマだけなのよ。\\nだから、カズマと２人で行ってきて欲しいの。"

# クリス
# え？　今、なんて言ったの？
217 = "え？　今、なんて言ったの？"

# アクア
# カズマと２人で、\n洞窟の調査に行ってきて欲しいの。
251 = "カズマと２人で、\\n洞窟の調査に行ってきて欲しいの。"

# クリス
# %fsyogen;ふ、２人きりで！？\n無理！　絶対に無理！　引き受けないから！
18 = "%fsyogen;ふ、２人きりで！？\\n無理！　絶対に無理！　引き受けないから！"

# カズマ（Ｍ）
# display as カズマ
# （いやいや、クリス、ちょっと嫌がりすぎだろう）
310 = "（いやいや、クリス、ちょっと嫌がりすぎだろう）"

# カズマ（Ｍ）
# display as カズマ
# （俺が意識してないだけで、\n　もしかしたら何かしたのか？）
315 = "（俺が意識してないだけで、\\n　もしかしたら何かしたのか？）"

# カズマ（Ｍ）
# display as カズマ
# （ん？　意識してない……。\n　よし、証言としてゲットしておこう！）
314 = "（ん？　意識してない……。\\n　よし、証言としてゲットしておこう！）"

# ダクネス
# そんなに嫌なのか？
224 = "そんなに嫌なのか？"

# アクア
# まあ、気持ちはわかるけど。\nこんな男と２人でって、キツいわよね。\nうん、わかる、わかるわよ。
241 = "まあ、気持ちはわかるけど。\\nこんな男と２人でって、キツいわよね。\\nうん、わかる、わかるわよ。"

# クリス
# わかるのなら頼まないでよっ！
246 = "わかるのなら頼まないでよっ！"

# カズマ
# あの、クリスさん？\n俺のこと、そんなに嫌いなんですか？
209 = "あの、クリスさん？\\n俺のこと、そんなに嫌いなんですか？"

# クリス
# き、嫌いじゃないんだけど！\nでも……その、２人きりはマズイでしょ！\n色々な意味で。
219 = "き、嫌いじゃないんだけど！\\nでも……その、２人きりはマズイでしょ！\\n色々な意味で。"

# カズマ
# 俺、みんなが思ってるような男じゃないからね！
262 = "俺、みんなが思ってるような男じゃないからね！"

# クリス
# ぱ、ぱ、パンツを盗んでおいてよく言うよ！
237 = "ぱ、ぱ、パンツを盗んでおいてよく言うよ！"

# カズマ
# それは呪いのせいで俺の意志じゃないし！
223 = "それは呪いのせいで俺の意志じゃないし！"

# クリス
# とにかく、いくらダクネスの頼みでも無理！
231 = "とにかく、いくらダクネスの頼みでも無理！"

# ダクネス
# いや、待ってくれ、クリス。\n本当に困っているんだ。
212 = "いや、待ってくれ、クリス。\\n本当に困っているんだ。"

# めぐみん
# このままでは、カズマ１人で\n洞窟に行くことになってしまうのです。
220 = "このままでは、カズマ１人で\\n洞窟に行くことになってしまうのです。"

# クリス
# どうして？\nあたしじゃなくて、ダクネス達が\nついていけばいいじゃない。
233 = "どうして？\\nあたしじゃなくて、ダクネス達が\\nついていけばいいじゃない。"

# ダクネス
# それが、洞窟内が非常に狭いらしくてな。\n鎧を身につける私は不向きなんだ。
222 = "それが、洞窟内が非常に狭いらしくてな。\\n鎧を身につける私は不向きなんだ。"

# ダクネス
# わ、私としては、鎧なしでも問題ないんだがな。
244 = "わ、私としては、鎧なしでも問題ないんだがな。"

# クリス
# ちょ、ダメダメ！\nそんなの危険すぎるから！
227 = "ちょ、ダメダメ！\\nそんなの危険すぎるから！"

# めぐみん
# 私は爆裂魔法しか使えませんから、\n同じく洞窟探検には向いていないのです。
308 = "私は爆裂魔法しか使えませんから、\\n同じく洞窟探検には向いていないのです。"

# クリス
# ああ、確かにそうだね。
208 = "ああ、確かにそうだね。"

# ダクネス
# アクアは、なぜか\nアンデッドモンスターに好かれやすいんだ。\nだから洞窟に連れて行くには問題があってな。
249 = "アクアは、なぜか\\nアンデッドモンスターに好かれやすいんだ。\\nだから洞窟に連れて行くには問題があってな。"

# アクア
# 好かれやすいんじゃないんですけど！\n女神だからなんですけど！
267 = "好かれやすいんじゃないんですけど！\\n女神だからなんですけど！"

# めぐみん
# という思い込みです。\n気にしないでください。
229 = "という思い込みです。\\n気にしないでください。"

# クリス
# そ、そう。\n大変だね、アンデッドに好かれるなんて。
221 = "そ、そう。\\n大変だね、アンデッドに好かれるなんて。"

# アクア
# 同情の目で見ないでよー！
266 = "同情の目で見ないでよー！"

# ダクネス
# とまあ、そういうわけだ。\n無理を言って本当に申し訳ないんだが、\n力になってくれないだろうか。
232 = "とまあ、そういうわけだ。\\n無理を言って本当に申し訳ないんだが、\\n力になってくれないだろうか。"

# クリス
# うーん……。\nそう言われても……やっぱり２人きりは……。
215 = "うーん……。\\nそう言われても……やっぱり２人きりは……。"

# カズマ
# なあ、それってさ、\n２人きりじゃなければいいのか？
235 = "なあ、それってさ、\\n２人きりじゃなければいいのか？"

# クリス
# ま、まあ、そうだね。\n２人きりじゃないのなら考えてもいい……かなって\nレベルだけど。
239 = "ま、まあ、そうだね。\\n２人きりじゃないのなら考えてもいい……かなって\\nレベルだけど。"

# カズマ
# 実はさ、ゆんゆんにも\n頼んでみようかと思ってるんだよ。
269 = "実はさ、ゆんゆんにも\\n頼んでみようかと思ってるんだよ。"

# カズマ
# だから、もしゆんゆんがオッケーだったら\nクリスも入れて３人だし、問題ないんじゃないかな。
226 = "だから、もしゆんゆんがオッケーだったら\\nクリスも入れて３人だし、問題ないんじゃないかな。"

# クリス
# ゆんゆんもか。\nうーん、そうだなぁ、\nゆんゆんがいいって言ったら考えるよ。
243 = "ゆんゆんもか。\\nうーん、そうだなぁ、\\nゆんゆんがいいって言ったら考えるよ。"

# カズマ
# わかった！\n俺達、今からゆんゆんのところに\n行ってくるから、また後で。
245 = "わかった！\\n俺達、今からゆんゆんのところに\\n行ってくるから、また後で。"

# クリス
# うん……。
214 = "うん……。"

