# st04c_07.txt.scn

[info]
0 = ""

[characters]
195 = "ルナ"
186 = "カズマ"
187 = "カズマ（Ｍ）"
183 = "めぐみん"
193 = "ダクネス"
185 = "アクア"
188 = "クリス"

[character_subs]
# 186 = "カズマ"

[script]
# lines: 42

# ルナ
# みなさん、お帰りなさいっ！\nお疲れ様です！
182 = "みなさん、お帰りなさいっ！\\nお疲れ様です！"

# カズマ
# ああ、どうも……。
155 = "ああ、どうも……。"

# ルナ
# 洞窟はどうでした！？\n財宝、見つかりました！？
202 = "洞窟はどうでした！？\\n財宝、見つかりました！？"

# カズマ
# うおっ！？
159 = "うおっ！？"

# カズマ（Ｍ）
# display as カズマ
# （なんでお姉さん、こんなに前のめりなんだ？\n　ギルドとしては財宝がそんなに重要なのか？）
228 = "（なんでお姉さん、こんなに前のめりなんだ？\\n　ギルドとしては財宝がそんなに重要なのか？）"

# カズマ
# え、えーっとですね？\n実は色々ありまして――
160 = "え、えーっとですね？\\n実は色々ありまして――"

# ルナ
# スカルドラゴン……！\nまさか、そんなモンスターが潜んでいたなんて。
191 = "スカルドラゴン……！\\nまさか、そんなモンスターが潜んでいたなんて。"

# カズマ（Ｍ）
# display as カズマ
# （潜んでいたっていうか、アクアに\n　引きよせられた可能性もあるんだけど……\n　黙っておくしかないよな）
229 = "（潜んでいたっていうか、アクアに\\n　引きよせられた可能性もあるんだけど……\\n　黙っておくしかないよな）"

# ルナ
# それで、なんとか逃げ出したものの、\n洞窟が崩れてしまったわけですか。
174 = "それで、なんとか逃げ出したものの、\\n洞窟が崩れてしまったわけですか。"

# カズマ
# すみません。\n爆裂魔法を使わなければ、\n崩れることはなかったかもしれないんですけど。
168 = "すみません。\\n爆裂魔法を使わなければ、\\n崩れることはなかったかもしれないんですけど。"

# ルナ
# そこは、仕方ないでしょう。\n使わなければ、みなさんが\n犠牲になっていたかもしれません。
173 = "そこは、仕方ないでしょう。\\n使わなければ、みなさんが\\n犠牲になっていたかもしれません。"

# ルナ
# それに、爆裂魔法の威力に警戒して\nスカルドラゴンが逃げていった可能性も\nありますから。
175 = "それに、爆裂魔法の威力に警戒して\\nスカルドラゴンが逃げていった可能性も\\nありますから。"

# めぐみん
# やっぱり、私の判断が\n的確だったんじゃないですか。
184 = "やっぱり、私の判断が\\n的確だったんじゃないですか。"

# ダクネス
# しかし、財宝が洞窟ごと埋まってしまったのは\nこちらの責任だと思うが……。
166 = "しかし、財宝が洞窟ごと埋まってしまったのは\\nこちらの責任だと思うが……。"

# ルナ
# いえ、ギルドとしては\nみなさんの責任を問うことは致しません。
157 = "いえ、ギルドとしては\\nみなさんの責任を問うことは致しません。"

# ルナ
# スカルドラゴンの存在を把握していなかったのは、\nこちらの落ち度ですので。
192 = "スカルドラゴンの存在を把握していなかったのは、\\nこちらの落ち度ですので。"

# アクア
# そうよねぇ。\nただの調査だっていうから引き受けたんだもの。
172 = "そうよねぇ。\\nただの調査だっていうから引き受けたんだもの。"

# ルナ
# ところで、洞窟にはサトウさん達３人で\n向かうと聞いていたのですが、\nなぜ他のみなさんも一緒に？
178 = "ところで、洞窟にはサトウさん達３人で\\n向かうと聞いていたのですが、\\nなぜ他のみなさんも一緒に？"

# アクア
# えっ！？\nそ、それは、えーっとぉ……。
162 = "えっ！？\\nそ、それは、えーっとぉ……。"

# カズマ
# こ、こいつら、俺のことが心配で\n結局ついてきちゃったんですよ！
165 = "こ、こいつら、俺のことが心配で\\n結局ついてきちゃったんですよ！"

# アクア
# そ、そうそう！\n別に財宝をもらっちゃおうとか、\nそんなつもりはまったくなかったのよ！
169 = "そ、そうそう！\\n別に財宝をもらっちゃおうとか、\\nそんなつもりはまったくなかったのよ！"

# カズマ
# お前はもう黙ってろ！
164 = "お前はもう黙ってろ！"

# ルナ
# ああ、そうです。\n財宝もなのですが――
154 = "ああ、そうです。\\n財宝もなのですが――"

# ルナ
# 結局、調査は失敗になりますので、\n報酬もお支払いすることができないのです。\nすみません。
226 = "結局、調査は失敗になりますので、\\n報酬もお支払いすることができないのです。\\nすみません。"

# カズマ
# いえ、そんな！\nこっちこそ、せっかくクエストを\n紹介してもらったのに、すみません。
156 = "いえ、そんな！\\nこっちこそ、せっかくクエストを\\n紹介してもらったのに、すみません。"

# ルナ
# 謝らないでください。\n本当に、みなさん、ご無事でなによりでした。
227 = "謝らないでください。\\n本当に、みなさん、ご無事でなによりでした。"

# ルナ
# と、ところで……\nサトウさんにお聞きしたいことがあるのですが。
176 = "と、ところで……\\nサトウさんにお聞きしたいことがあるのですが。"

# カズマ
# へ？　なんですか？\n本当に財宝は見つけてませんよ？
181 = "へ？　なんですか？\\n本当に財宝は見つけてませんよ？"

# ルナ
# いえ、クエストについてではなくですね？\nその……。
158 = "いえ、クエストについてではなくですね？\\nその……。"

# ルナ
# サトウさんが……\nぬ、盗んだ物について……\n裁判を行っていると小耳に挟んだのですが……。
190 = "サトウさんが……\\nぬ、盗んだ物について……\\n裁判を行っていると小耳に挟んだのですが……。"

# カズマ
# あ、ああ。\nやってますけど、それがなにか？
152 = "あ、ああ。\\nやってますけど、それがなにか？"

# ルナ
# ……私も、裁判に参加したいんです。
151 = "……私も、裁判に参加したいんです。"

# カズマ
# はあっ！？\nな、なんでですか？
180 = "はあっ！？\\nな、なんでですか？"

# ルナ
# えっ！？\nええと、ええと……それはですね……。
161 = "えっ！？\\nええと、ええと……それはですね……。"

# ルナ
# そうです、ギルドとして、\nそういった行為を監視しておく必要がありまして！
171 = "そうです、ギルドとして、\\nそういった行為を監視しておく必要がありまして！"

# ダクネス
# ということは、ギルドに迷惑をかけていたのか？
177 = "ということは、ギルドに迷惑をかけていたのか？"

# ルナ
# そ、そんなことはありません！\nただ、その、今後、問題にならないこともないと\n思いますので、一度、見ておこうかと！！
170 = "そ、そんなことはありません！\\nただ、その、今後、問題にならないこともないと\\n思いますので、一度、見ておこうかと！！"

# クリス
# ……ああ、これってもしかして。
150 = "……ああ、これってもしかして。"

# クリス
# ねえ、キミ。\n参加させてあげたら？\n特に断る理由もないでしょ？
179 = "ねえ、キミ。\\n参加させてあげたら？\\n特に断る理由もないでしょ？"

# カズマ
# お、おう、そうだな。
163 = "お、おう、そうだな。"

# ルナ
# あ、ありがとうございます……。
153 = "あ、ありがとうございます……。"

# カズマ
# じゃあ、今回はお姉さんも参加で\nパンツ裁判いってみようか！
167 = "じゃあ、今回はお姉さんも参加で\\nパンツ裁判いってみようか！"

[selections]
189 = "コーヒーブレイク"
