# st04a_08.txt.scn

[info]
0 = ""

[characters]
398 = "カズマ"
396 = "ウィズ"
385 = "めぐみん"
387 = "ゆんゆん"
400 = "カズマ（Ｍ）"
393 = "アクア"
401 = "ダクネス"

[character_subs]
# 398 = "カズマ"

[script]
# lines: 142

# カズマ
# よう、ウィズ。\n１日に何度もお邪魔しちゃって、悪いな。
389 = "よう、ウィズ。\\n１日に何度もお邪魔しちゃって、悪いな。"

# ウィズ
# 構いませんけど、どうしたんですか？\nバニルさんでしたら、\n先ほど出かけてしまったのですが。
422 = "構いませんけど、どうしたんですか？\\nバニルさんでしたら、\\n先ほど出かけてしまったのですが。"

# めぐみん
# いえ、今回は、あっちに隠れている\nぼっちに用がありまして。
326 = "いえ、今回は、あっちに隠れている\\nぼっちに用がありまして。"

# ゆんゆん
# あ……！\nみ、見つかってた！
312 = "あ……！\\nみ、見つかってた！"

# カズマ（Ｍ）
# display as カズマ
# （あれで隠れたつもりだったのか。\n　棚の隙間から丸見えだったけど）
498 = "（あれで隠れたつもりだったのか。\\n　棚の隙間から丸見えだったけど）"

# めぐみん
# ゆんゆん、なにをしているのですか。\nそんな態度、営業妨害で訴えられても\nおかしくありませんよ。
388 = "ゆんゆん、なにをしているのですか。\\nそんな態度、営業妨害で訴えられても\\nおかしくありませんよ。"

# ゆんゆん
# うう……すみません、ウィズさん。
332 = "うう……すみません、ウィズさん。"

# ウィズ
# 気にすることはありませんよ。\n今は、他にお客さんもいませんから。
423 = "気にすることはありませんよ。\\n今は、他にお客さんもいませんから。"

# カズマ（Ｍ）
# display as カズマ
# （つか、他に客がいるところを\n　見たことないけどな。\n　本当に大丈夫なのか、この店）
511 = "（つか、他に客がいるところを\\n　見たことないけどな。\\n　本当に大丈夫なのか、この店）"

# めぐみん
# 甘やかしてはダメです。\nぼっちは、すぐにつけあがります。
426 = "甘やかしてはダメです。\\nぼっちは、すぐにつけあがります。"

# ゆんゆん
# 私、ぼっちじゃないって言ってるでしょ！
486 = "私、ぼっちじゃないって言ってるでしょ！"

# めぐみん
# へー、そうなんですか、へー。
380 = "へー、そうなんですか、へー。"

# ゆんゆん
# ほ、本当なんだからね！\n今だって、ええと、ウィズさんがいるし！
381 = "ほ、本当なんだからね！\\n今だって、ええと、ウィズさんがいるし！"

# ウィズ
# そうですね。\nゆんゆんさんがお話相手になってくれますので、\n暇を持て余すこともありません。
353 = "そうですね。\\nゆんゆんさんがお話相手になってくれますので、\\n暇を持て余すこともありません。"

# ゆんゆん
# というわけで、めぐみん！\n勝負……は、次の機会にしましょう。
371 = "というわけで、めぐみん！\\n勝負……は、次の機会にしましょう。"

# めぐみん
# は？
379 = "は？"

# アクア
# ねえ、ゆんゆん、なんだか変じゃない？
374 = "ねえ、ゆんゆん、なんだか変じゃない？"

# カズマ（Ｍ）
# display as カズマ
# （確かにそうだな。\n　なんかモジモジしてるし、それに……）
519 = "（確かにそうだな。\\n　なんかモジモジしてるし、それに……）"

# ゆんゆん
# チラ、チラチラ。
402 = "チラ、チラチラ。"

# カズマ（Ｍ）
# display as カズマ
# （なんか俺を気にしているような）
512 = "（なんか俺を気にしているような）"

# カズマ（Ｍ）
# display as カズマ
# （はっ、ゆんゆんは俺に！）
514 = "（はっ、ゆんゆんは俺に！）"

# アクア
# よくわからないけど、それはないと思うわ。
390 = "よくわからないけど、それはないと思うわ。"

# カズマ
# 人の考えを勝手に読まないでくれますか！
405 = "人の考えを勝手に読まないでくれますか！"

# めぐみん
# %fsyogen;どうしたのですか、ゆんゆん。\nなぜカズマを見ているのですか？
22 = "%fsyogen;どうしたのですか、ゆんゆん。\\nなぜカズマを見ているのですか？"

# ゆんゆん
# み、み、見てないよっ！？\n私、何も見てないよ！
383 = "み、み、見てないよっ！？\\n私、何も見てないよ！"

# めぐみん
# ほほう、何も見てない？\nでは、その瞳はガラス玉ですか？\nそれは知りませんでした。
382 = "ほほう、何も見てない？\\nでは、その瞳はガラス玉ですか？\\nそれは知りませんでした。"

# ゆんゆん
# ち、違うけど……。\nでも私、別に見たりなんか……。
365 = "ち、違うけど……。\\nでも私、別に見たりなんか……。"

# カズマ（Ｍ）
# display as カズマ
# （いや、見てますよね？\n　思いっきり俺を見てますよね？）
500 = "（いや、見てますよね？\\n　思いっきり俺を見てますよね？）"

# カズマ（Ｍ）
# display as カズマ
# （この視線の理由、そしてゆんゆんの焦り方……）
507 = "（この視線の理由、そしてゆんゆんの焦り方……）"

# カズマ（Ｍ）
# display as カズマ
# （何かありそうだな。\n　めぐみんの指摘を証言として押さえておこう）
517 = "（何かありそうだな。\\n　めぐみんの指摘を証言として押さえておこう）"

# ゆんゆん
# う、うう……。
329 = "う、うう……。"

# カズマ（Ｍ）
# display as カズマ
# （なんなんだ？\n　女の子の意味深な視線とか、\n　童貞の俺には刺激が強すぎるんですけど！？）
513 = "（なんなんだ？\\n　女の子の意味深な視線とか、\\n　童貞の俺には刺激が強すぎるんですけど！？）"

# ゆんゆん
# うう……ううう……。
331 = "うう……ううう……。"

# カズマ（Ｍ）
# display as カズマ
# （落ち着け、落ち着け俺。\n　こんなことに動揺してどうする！）
520 = "（落ち着け、落ち着け俺。\\n　こんなことに動揺してどうする！）"

# カズマ（Ｍ）
# display as カズマ
# （思い出すんだ！\n　女の子の視線なんて大抵が勘違いだ！\n　俺じゃなくて、その向こうの誰か見てるんだ！）
518 = "（思い出すんだ！\\n　女の子の視線なんて大抵が勘違いだ！\\n　俺じゃなくて、その向こうの誰か見てるんだ！）"

# カズマ（Ｍ）
# display as カズマ
# （いや待て！\n　今、俺の向こうには誰もいない。\n　ってことはマジで俺を見てる！？）
501 = "（いや待て！\\n　今、俺の向こうには誰もいない。\\n　ってことはマジで俺を見てる！？）"

# カズマ（Ｍ）
# display as カズマ
# （こ、こ、こういう時はどうするんだ？\n　にっこり微笑み返すのが正しいのか？\n　情熱的に見つめ返すべきか！？）
504 = "（こ、こ、こういう時はどうするんだ？\\n　にっこり微笑み返すのが正しいのか？\\n　情熱的に見つめ返すべきか！？）"

# アクア
# なんでゆんゆんとカズマは見つめ合ってるの？
373 = "なんでゆんゆんとカズマは見つめ合ってるの？"

# めぐみん
# 私が知るわけないです。
487 = "私が知るわけないです。"

# ダクネス
# 私にもわからないな。\nカズマの顔に何かついているのか？
489 = "私にもわからないな。\\nカズマの顔に何かついているのか？"

# めぐみん
# ええ、ついてますよね。\n目が２つと鼻が１つと口が１つ。
335 = "ええ、ついてますよね。\\n目が２つと鼻が１つと口が１つ。"

# アクア
# それがなかったら人間じゃないわね。
356 = "それがなかったら人間じゃないわね。"

# ウィズ
# あ、あの、みなさん？\nよろしければ、お茶でもお入れしましょうか？
314 = "あ、あの、みなさん？\\nよろしければ、お茶でもお入れしましょうか？"

# ゆんゆん
# えっ！？
338 = "えっ！？"

# ウィズ
# みなさん、ゆんゆんさんに\nお話があっていらしたようですし。\nせっかくですから、ゆっくりしていってください。
384 = "みなさん、ゆんゆんさんに\\nお話があっていらしたようですし。\\nせっかくですから、ゆっくりしていってください。"

# カズマ（Ｍ）
# display as カズマ
# （しまった！\n　妙な空気になってたから、\n　ウィズに余計な気を使わせたか？）
509 = "（しまった！\\n　妙な空気になってたから、\\n　ウィズに余計な気を使わせたか？）"

# カズマ
# 別にそんなことしなくていいって。
408 = "別にそんなことしなくていいって。"

# ウィズ
# いえ、私が勝手にやることですから、\n気にしないでください。
327 = "いえ、私が勝手にやることですから、\\n気にしないでください。"

# アクア
# っていうか、遅いと思うんですけど。\nお茶は、私がドアを開ける前に用意しておくべき\nなんじゃないですか？
366 = "っていうか、遅いと思うんですけど。\\nお茶は、私がドアを開ける前に用意しておくべき\\nなんじゃないですか？"

# カズマ
# 姑みたいな難癖はやめろ。
413 = "姑みたいな難癖はやめろ。"

# カズマ
# 悪いな、気を使わせちゃって。
420 = "悪いな、気を使わせちゃって。"

# ウィズ
# えっ？\n気を使ってなんて、そんな。
339 = "えっ？\\n気を使ってなんて、そんな。"

# ウィズ
# でも、こうすることで少しでも\nカズマさんのお役に立てるのなら、嬉しいです。
369 = "でも、こうすることで少しでも\\nカズマさんのお役に立てるのなら、嬉しいです。"

# カズマ
# 少しなんてもんじゃない。\nホント、ウィズにはすごく助けられてるよ。
416 = "少しなんてもんじゃない。\\nホント、ウィズにはすごく助けられてるよ。"

# ウィズ
# そ、そうですか？
351 = "そ、そうですか？"

# アクア
# 真顔で恥ずかしい台詞言っちゃって。\n見ててむずがゆいんですけど？
485 = "真顔で恥ずかしい台詞言っちゃって。\\n見ててむずがゆいんですけど？"

# カズマ
# そ、そういうことは思っても\n口に出すんじゃねー！
350 = "そ、そういうことは思っても\\n口に出すんじゃねー！"

# カズマ（Ｍ）
# display as カズマ
# （ここはウィズに合わせるか。\n　きっと、雰囲気を変えようとしてくれてるんだ）
505 = "（ここはウィズに合わせるか。\\n　きっと、雰囲気を変えようとしてくれてるんだ）"

# カズマ
# じゃあ、頼んでいいか？\nちょうど喉が渇いてたんだ。
349 = "じゃあ、頼んでいいか？\\nちょうど喉が渇いてたんだ。"

# ウィズ
# でしたら、すぐに用意しますね。\nお茶を飲んで、ゆっくり落ち着いて話してください。
368 = "でしたら、すぐに用意しますね。\\nお茶を飲んで、ゆっくり落ち着いて話してください。"

# ゆんゆん
# あ、ありがとうございます。
315 = "あ、ありがとうございます。"

# アクア
# 私は、リッチーの入れるお茶じゃ\n全然くつろげないんですけど？
491 = "私は、リッチーの入れるお茶じゃ\\n全然くつろげないんですけど？"

# カズマ
# お前は黙ってろ、アクア。
343 = "お前は黙ってろ、アクア。"

# ウィズ
# お待たせしました。\nどうぞ。
345 = "お待たせしました。\\nどうぞ。"

# カズマ
# おっ！\nいい香りだなぁ。
341 = "おっ！\\nいい香りだなぁ。"

# ダクネス
# これは……\n良い茶葉を使っているだけではなく、\n淹れ方にも一工夫あるようだな。
347 = "これは……\\n良い茶葉を使っているだけではなく、\\n淹れ方にも一工夫あるようだな。"

# ゆんゆん
# はい、ウィズさんのお茶は\nいつも本当に美味しいです。
377 = "はい、ウィズさんのお茶は\\nいつも本当に美味しいです。"

# ウィズ
# いえ、そんなことは。\nごく普通に淹れているだけですよ。
325 = "いえ、そんなことは。\\nごく普通に淹れているだけですよ。"

# アクア
# アンデッドのくせに\n褒められて嬉しそうにしちゃって。\n第一、アンデッドか温かいお茶っておかしいでしょ。
395 = "アンデッドのくせに\\n褒められて嬉しそうにしちゃって。\\n第一、アンデッドか温かいお茶っておかしいでしょ。"

# カズマ
# お前は姑みたいな言い方しかできないのか。\n素直に美味しいって言えよ。
342 = "お前は姑みたいな言い方しかできないのか。\\n素直に美味しいって言えよ。"

# めぐみん
# あの、砂糖はありますか？
322 = "あの、砂糖はありますか？"

# ウィズ
# はい。\nこちらのシュガーポットに入っていますよ。
378 = "はい。\\nこちらのシュガーポットに入っていますよ。"

# カズマ
# 苦くて飲めないなんて、まだまだお子様舌だな。
493 = "苦くて飲めないなんて、まだまだお子様舌だな。"

# めぐみん
# お子様とは失礼な！
344 = "お子様とは失礼な！"

# めぐみん
# それに、苦くて飲めないなんて言ってません。\n少し甘くした方がより美味しくなりそうだなって\n思っただけです。
358 = "それに、苦くて飲めないなんて言ってません。\\n少し甘くした方がより美味しくなりそうだなって\\n思っただけです。"

# ウィズ
# そこは好みですね。\nどうぞ、このスプーンを使ってください。
354 = "そこは好みですね。\\nどうぞ、このスプーンを使ってください。"

# めぐみん
# ……あっ！
309 = "……あっ！"

# めぐみん
# ああっ！\nすみません、落としちゃって。
321 = "ああっ！\\nすみません、落としちゃって。"

# ウィズ
# 大丈夫ですよ。\nすぐに洗ってきます、か、ら……。
412 = "大丈夫ですよ。\\nすぐに洗ってきます、か、ら……。"

# ウィズ
# …………。
308 = "…………。"

# カズマ
# ん？　どうしたんだ、ウィズ。\nスプーン、拾わないのか？
392 = "ん？　どうしたんだ、ウィズ。\\nスプーン、拾わないのか？"

# ウィズ
# いえ、その……\n拾いますけど、でも、身を屈めるのが……。
324 = "いえ、その……\\n拾いますけど、でも、身を屈めるのが……。"

# カズマ
# 腰が痛いのか？\n曲げるのがつらいとか。
492 = "腰が痛いのか？\\n曲げるのがつらいとか。"

# ウィズ
# そんなことは、ないのですが……。
361 = "そんなことは、ないのですが……。"

# カズマ（Ｍ）
# display as カズマ
# （じゃあ、なんで拾おうとしないんだ？）
510 = "（じゃあ、なんで拾おうとしないんだ？）"

# ウィズ
# …………。
# 308 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （まさか、これは――）
515 = "（まさか、これは――）"

# カズマ（Ｍ）
# display as カズマ
# （お前が拾えという無言のプレッシャー！？\n　男たるもの、それくらいは\n　サラッとこなしてみせろと！？）
503 = "（お前が拾えという無言のプレッシャー！？\\n　男たるもの、それくらいは\\n　サラッとこなしてみせろと！？）"

# カズマ（Ｍ）
# display as カズマ
# （オーケー。\n　そういうことなら……）
516 = "（オーケー。\\n　そういうことなら……）"

# カズマ
# ウィズ、落としたぜ。
397 = "ウィズ、落としたぜ。"

# ウィズ
# あ、ありがとうございます。\nそれじゃ、洗ってきますね。
316 = "あ、ありがとうございます。\\nそれじゃ、洗ってきますね。"

# カズマ
# ああ、気をつけて。
320 = "ああ、気をつけて。"

# ダクネス
# な、なんだ今のカズマは。
372 = "な、なんだ今のカズマは。"

# めぐみん
# ええ、過去最高に気持ち悪かったです。
336 = "ええ、過去最高に気持ち悪かったです。"

# ダクネス
# だ、だか、その気持ち悪さが\nまたいいとも感じるな。
363 = "だ、だか、その気持ち悪さが\\nまたいいとも感じるな。"

# カズマ
# そそそ、そこまで気持ち悪くはねーだろ！
355 = "そそそ、そこまで気持ち悪くはねーだろ！"

# めぐみん
# 気持ち悪いカズマは放っておいて、\n本題に移りましょう。
424 = "気持ち悪いカズマは放っておいて、\\n本題に移りましょう。"

# カズマ（Ｍ）
# display as カズマ
# （おい）
502 = "（おい）"

# ダクネス
# 実はゆんゆんに頼みがあるんだ。
415 = "実はゆんゆんに頼みがあるんだ。"

# ゆんゆん
# 私にですか？
488 = "私にですか？"

# アクア
# 待って、説明は私からするわ！
418 = "待って、説明は私からするわ！"

# カズマ（Ｍ）
# display as カズマ
# （あー、また始まったな……）
499 = "（あー、また始まったな……）"

# アクア
# あのね、ギルドで洞窟調査のクエストを\n引き受けたんだけど、\n事情があって行けるのがカズマだけなの。
323 = "あのね、ギルドで洞窟調査のクエストを\\n引き受けたんだけど、\\n事情があって行けるのがカズマだけなの。"

# アクア
# でもカズマ１人じゃ不安だから、\nゆんゆんにも同行してもらえないかと思って。
370 = "でもカズマ１人じゃ不安だから、\\nゆんゆんにも同行してもらえないかと思って。"

# ゆんゆん
# ええええっ！？\nか、か、カズマさんと\n２人で行けってことですか？
337 = "ええええっ！？\\nか、か、カズマさんと\\n２人で行けってことですか？"

# カズマ
# ……ゆんゆんまでそんな反応なんだ。\nねえ、俺、そこまで信用されてないの？
311 = "……ゆんゆんまでそんな反応なんだ。\\nねえ、俺、そこまで信用されてないの？"

# めぐみん
# 今までの自分の所行を思い返してください。
406 = "今までの自分の所行を思い返してください。"

# カズマ
# はい、すみませんでした。
376 = "はい、すみませんでした。"

# ゆんゆん
# で、でも、どうして私なんですか？\nみなさんは行かないんですか？
367 = "で、でも、どうして私なんですか？\\nみなさんは行かないんですか？"

# めぐみん
# 行けないのですよ。
494 = "行けないのですよ。"

# めぐみん
# 実に残念なことだが、我が究極の爆裂魔法は\n昏き奈落ではその効力を発揮できぬのだ。
414 = "実に残念なことだが、我が究極の爆裂魔法は\\n昏き奈落ではその効力を発揮できぬのだ。"

# ゆんゆん
# ……そういう時のために、\n他の上級魔法、覚えたほうがいいんじゃない？
310 = "……そういう時のために、\\n他の上級魔法、覚えたほうがいいんじゃない？"

# ダクネス
# それに、洞窟は非常に狭いらしくてな。\n鎧を身につけた私では、\n身動きが取れなくなる可能性があるそうだ。
357 = "それに、洞窟は非常に狭いらしくてな。\\n鎧を身につけた私では、\\n身動きが取れなくなる可能性があるそうだ。"

# ダクネス
# アクアも……\nその、ちょっと事情があっていけないんだ。
394 = "アクアも……\\nその、ちょっと事情があっていけないんだ。"

# アクア
# だから！\nその同情いっぱいの視線は\nやめてほしいんですけど！？
364 = "だから！\\nその同情いっぱいの視線は\\nやめてほしいんですけど！？"

# ゆんゆん
# あ、あの、こうしてお願いされるのは、\nとっても嬉しいんですけど、\nでも、今は、ちょっと困るんです。
313 = "あ、あの、こうしてお願いされるのは、\\nとっても嬉しいんですけど、\\nでも、今は、ちょっと困るんです。"

# めぐみん
# 困るって、なぜですか？\n他に予定が――
411 = "困るって、なぜですか？\\n他に予定が――"

# めぐみん
# ああ、ゆんゆんに予定なんて\nあるわけないですよね。
319 = "ああ、ゆんゆんに予定なんて\\nあるわけないですよね。"

# ゆんゆん
# あ、あることだってあるもんっ！
317 = "あ、あることだってあるもんっ！"

# めぐみん
# 見栄を張ると後で後悔しますよ。
496 = "見栄を張ると後で後悔しますよ。"

# ゆんゆん
# 見栄でもなくて！\n今は、その、本当に困るの！！
495 = "見栄でもなくて！\\n今は、その、本当に困るの！！"

# ウィズ
# カズマさん、無理強いはしないほうがいいのでは？
399 = "カズマさん、無理強いはしないほうがいいのでは？"

# カズマ
# それはわかってるんだけどな……。
359 = "それはわかってるんだけどな……。"

# ダクネス
# 困ったな。\nゆんゆんもダメとなるとクリスもダメだ。
410 = "困ったな。\\nゆんゆんもダメとなるとクリスもダメだ。"

# ダクネス
# こ、こうなったら、やはり私が鎧を脱いで\n同行するしかあるまいっ！
346 = "こ、こうなったら、やはり私が鎧を脱いで\\n同行するしかあるまいっ！"

# カズマ
# それは危ないって何度も言ってるだろ！
360 = "それは危ないって何度も言ってるだろ！"

# めぐみん
# 本当に困りましたね。\nええ、困りました。ああ、困りましたねー。
421 = "本当に困りましたね。\\nええ、困りました。ああ、困りましたねー。"

# ゆんゆん
# うう……。
330 = "うう……。"

# めぐみん
# 私のライバルを自称する人は、\nこういう時に助けてくれたりしないんですかねー。\n困った時はお互い様と言いますよねー。
490 = "私のライバルを自称する人は、\\nこういう時に助けてくれたりしないんですかねー。\\n困った時はお互い様と言いますよねー。"

# ゆんゆん
# うううう……。
333 = "うううう……。"

# めぐみん
# あ、それとも本当は予定があるのですか？\nこれはすみません、無神経でしたね。\nよかったですね、予定が埋まるようになって。
318 = "あ、それとも本当は予定があるのですか？\\nこれはすみません、無神経でしたね。\\nよかったですね、予定が埋まるようになって。"

# ゆんゆん
# ううううううう～！
334 = "ううううううう～！"

# ゆんゆん
# わ、わかったっ！\n手伝う！　手伝うわよ！
391 = "わ、わかったっ！\\n手伝う！　手伝うわよ！"

# カズマ
# いや、助かるけどさ、無理しないでくれよ？\n本当にいいのか？
328 = "いや、助かるけどさ、無理しないでくれよ？\\n本当にいいのか？"

# ゆんゆん
# やりますっ！
386 = "やりますっ！"

# めぐみん
# そう、紅魔族に二言はありませんからね。
352 = "そう、紅魔族に二言はありませんからね。"

# ゆんゆん
# そんなの初めて聞いたよ！？
362 = "そんなの初めて聞いたよ！？"

# カズマ（Ｍ）
# display as カズマ
# （これって明らかに無理矢理巻きこんでるよな？\n　これは、ちゃんとお礼しないと……）
508 = "（これって明らかに無理矢理巻きこんでるよな？\\n　これは、ちゃんとお礼しないと……）"

# アクア
# じゃあ、これでクリスも協力してくれるはずよね。\nさっそく知らせに行きましょ！
348 = "じゃあ、これでクリスも協力してくれるはずよね。\\nさっそく知らせに行きましょ！"

# ゆんゆん
# え？　クリスさん……ですか？
340 = "え？　クリスさん……ですか？"

# カズマ
# 詳しい説明は歩きながらするよ。\nとにかく、一緒に来てくれ。
497 = "詳しい説明は歩きながらするよ。\\nとにかく、一緒に来てくれ。"

# ゆんゆん
# は、はい。
375 = "は、はい。"

[selections]
407 = "別にそんなことしなくていいって"
419 = "悪いな、気を使わせちゃって"
506 = "（ここはウィズに合わせるか）"
