# st05c_01.txt.scn

[info]
0 = ""

[characters]
248 = "ルナ"
241 = "カズマ（Ｍ）"
232 = "ゆんゆん"
236 = "アクア"
238 = "ウィズ"
239 = "カズマ"
229 = "めぐみん"
242 = "クリス"
244 = "ダクネス"
240 = "カズマ＆めぐみん＆ダクネス"

[character_subs]
# 239 = "カズマ"
325 = "３人"

[script]
# lines: 83

# ルナ
# では、みなさん。\n改めて状況の整理をしましょう。
218 = "では、みなさん。\\n改めて状況の整理をしましょう。"

# カズマ（Ｍ）
# display as カズマ
# （しばらく後――\n　景気づけの乾杯が一段落ついたところで、\n　お姉さんが話を始めた）
322 = "（しばらく後――\\n　景気づけの乾杯が一段落ついたところで、\\n　お姉さんが話を始めた）"

# ルナ
# 現在、ギルドから偵察を飛ばし\nスカルドラゴンの動向を見張らせています。
267 = "現在、ギルドから偵察を飛ばし\\nスカルドラゴンの動向を見張らせています。"

# ルナ
# その報告によると、この街へ向かい\n一定の速度で進んできているようです。
205 = "その報告によると、この街へ向かい\\n一定の速度で進んできているようです。"

# ルナ
# スピードはかなりゆっくりで、\n数時間、準備をする余裕があると\n思ってくださって問題ありません。
243 = "スピードはかなりゆっくりで、\\n数時間、準備をする余裕があると\\n思ってくださって問題ありません。"

# ゆんゆん
# あの、余裕があるのは有り難いですけど……\nどうしてそんなにゆっくりなんでしょう？
188 = "あの、余裕があるのは有り難いですけど……\\nどうしてそんなにゆっくりなんでしょう？"

# ゆんゆん
# 人間への復讐に燃えているにしては\nのん気すぎませんか？
250 = "人間への復讐に燃えているにしては\\nのん気すぎませんか？"

# アクア
# 本調子じゃないんじゃないかしら。
264 = "本調子じゃないんじゃないかしら。"

# カズマ（Ｍ）
# display as カズマ
# （体調不良のレベルかよ……）
323 = "（体調不良のレベルかよ……）"

# ウィズ
# きっと、ふたつの魂が戦っているんですよ。
198 = "きっと、ふたつの魂が戦っているんですよ。"

# ゆんゆん
# ああ、この世界を滅ぼしたい考えと、\n違う考えが戦っているんですね。
185 = "ああ、この世界を滅ぼしたい考えと、\\n違う考えが戦っているんですね。"

# ウィズ
# おそらくですけどね。
197 = "おそらくですけどね。"

# ルナ
# あの、それで、サトウさんたちの作戦を\nお聞きしたいのですが。
187 = "あの、それで、サトウさんたちの作戦を\\nお聞きしたいのですが。"

# カズマ
# 単純ですよ。\nデストロイヤーの時と同じ戦い方をします。
255 = "単純ですよ。\\nデストロイヤーの時と同じ戦い方をします。"

# ルナ
# ああ、爆裂魔法による同時攻撃ですね。
186 = "ああ、爆裂魔法による同時攻撃ですね。"

# カズマ
# ただし、あの時とは順番が違います。\nまずはめぐみんとウィズで爆裂魔法を撃って、\nその後にアクアの浄化魔法をぶち込みます。
212 = "ただし、あの時とは順番が違います。\\nまずはめぐみんとウィズで爆裂魔法を撃って、\\nその後にアクアの浄化魔法をぶち込みます。"

# めぐみん
# ちょっと待ってください、カズマ。
216 = "ちょっと待ってください、カズマ。"

# めぐみん
# デストロイヤーは猪突猛進でしたから、\n爆裂魔法を打ち込めましたけどスカルドラゴンは\n自由に空を飛んでいるんですよ？
247 = "デストロイヤーは猪突猛進でしたから、\\n爆裂魔法を打ち込めましたけどスカルドラゴンは\\n自由に空を飛んでいるんですよ？"

# ウィズ
# 確かに爆裂魔法を的確にあてるのは\n難しいかもしれませんね。
314 = "確かに爆裂魔法を的確にあてるのは\\n難しいかもしれませんね。"

# クリス
# それだったらやっぱり、浄化魔法から爆裂魔法の\n流れの方がいいんじゃないかな。
208 = "それだったらやっぱり、浄化魔法から爆裂魔法の\\n流れの方がいいんじゃないかな。"

# カズマ
# それだと倒せない可能性があると思うんだ。
209 = "それだと倒せない可能性があると思うんだ。"

# ウィズ
# それも一理ありますね。\nスカルドラゴンにはもう生命という概念は\nありません。
211 = "それも一理ありますね。\\nスカルドラゴンにはもう生命という概念は\\nありません。"

# ダクネス
# 魂を滅するのには、\n浄化魔法がもっとも適しているということか。
317 = "魂を滅するのには、\\n浄化魔法がもっとも適しているということか。"

# カズマ
# だから爆裂魔法で弱ったところに\nアクアが浄化魔法をぶち込むんだよ
213 = "だから爆裂魔法で弱ったところに\\nアクアが浄化魔法をぶち込むんだよ"

# めぐみん
# 理解はしましたが、やっぱり根本的な問題が\n解決していませんよ。
269 = "理解はしましたが、やっぱり根本的な問題が\\n解決していませんよ。"

# カズマ
# いかにして爆裂魔法をあてるかだろ？\n俺たちにはゆんゆんがいるじゃないか。
191 = "いかにして爆裂魔法をあてるかだろ？\\n俺たちにはゆんゆんがいるじゃないか。"

# ゆんゆん
# ええ！？　私ですか！？
195 = "ええ！？　私ですか！？"

# カズマ
# ゆんゆんはちゃんとしたアークウィザードだ。
234 = "ゆんゆんはちゃんとしたアークウィザードだ。"

# めぐみん
# は？
227 = "は？"

# カズマ
# 確かに爆裂魔法みたいな高火力の魔法は\nまだ持ってないかもしれない。
313 = "確かに爆裂魔法みたいな高火力の魔法は\\nまだ持ってないかもしれない。"

# カズマ
# だけど、ふたりの詠唱時間とスカルドラゴンを\n足止めするくらいの時間は稼げるんじゃないかって\n考えたんだよ。
214 = "だけど、ふたりの詠唱時間とスカルドラゴンを\\n足止めするくらいの時間は稼げるんじゃないかって\\n考えたんだよ。"

# ゆんゆん
# 確かに魔力を最大放出にしての\nライト・オブ・セイバーでしたら\nなんとかなるかもしれません。
315 = "確かに魔力を最大放出にしての\\nライト・オブ・セイバーでしたら\\nなんとかなるかもしれません。"

# めぐみん
# ですが、ゆんゆんをひとりで\nスカルドラゴンに向かわせるなんて、\nいくらなんでもそれは危険すぎます！
217 = "ですが、ゆんゆんをひとりで\\nスカルドラゴンに向かわせるなんて、\\nいくらなんでもそれは危険すぎます！"

# ゆんゆん
# めぐみん……。
230 = "めぐみん……。"

# ダクネス
# 理には適った作戦だが、\nひとりの命を危険に晒していい理由などないぞ。
268 = "理には適った作戦だが、\\nひとりの命を危険に晒していい理由などないぞ。"

# カズマ
# おい、お前がそれを言っていいのか？
196 = "おい、お前がそれを言っていいのか？"

# ダクネス
# どういうことだ？
222 = "どういうことだ？"

# カズマ
# ダクネスがゆんゆんを守るんだよ。\nそれがクルセイダーの仕事だろ。
245 = "ダクネスがゆんゆんを守るんだよ。\\nそれがクルセイダーの仕事だろ。"

# ダクネス
# はっ！？
226 = "はっ！？"

# カズマ
# それともクルセイダーは\n命の危険があると盾にはなれないのか？
210 = "それともクルセイダーは\\n命の危険があると盾にはなれないのか？"

# ダクネス
# 愚弄する気かカズマ！\nそんな名誉なご褒美がなくても、\n私はこの命を賭する覚悟があるぞ！
261 = "愚弄する気かカズマ！\\nそんな名誉なご褒美がなくても、\\n私はこの命を賭する覚悟があるぞ！"

# カズマ
# 名誉なご褒美ってなんだよ。
258 = "名誉なご褒美ってなんだよ。"

# クリス
# うーん、残念だけど、\nあたしの出番はなさそうだね。
193 = "うーん、残念だけど、\\nあたしの出番はなさそうだね。"

# カズマ
# 何言ってるんだよ。\nこの作戦の成功の有無は、クリスが握ってると\n言っても過言じゃないんだからな。
252 = "何言ってるんだよ。\\nこの作戦の成功の有無は、クリスが握ってると\\n言っても過言じゃないんだからな。"

# クリス
# え、そうなの？
194 = "え、そうなの？"

# カズマ
# これだけの冒険者が一気に戦うんだ。\n状況が混乱するのは目に見えてるじゃないか。
199 = "これだけの冒険者が一気に戦うんだ。\\n状況が混乱するのは目に見えてるじゃないか。"

# カズマ
# そこでクリスには、盗賊のスキルを活かして\nみんなの目となり耳になって貰う。
203 = "そこでクリスには、盗賊のスキルを活かして\\nみんなの目となり耳になって貰う。"

# カズマ
# さらには戦場での作戦の伝達役も頼みたい。
201 = "さらには戦場での作戦の伝達役も頼みたい。"

# クリス
# あはは、これは確かに責任重大だね。
190 = "あはは、これは確かに責任重大だね。"

# カズマ
# 以上が、作戦の全てだ！\n意見がある者を挙手を！
251 = "以上が、作戦の全てだ！\\n意見がある者を挙手を！"

# アクア
# はいはーい。
225 = "はいはーい。"

# カズマ
# よし、ないな。
235 = "よし、ないな。"

# アクア
# ちょっとカズマ、無視しないでよ！
215 = "ちょっとカズマ、無視しないでよ！"

# カズマ
# なんだよ。\nシュワシュワなら作戦が終わるまでダメだからな。
224 = "なんだよ。\\nシュワシュワなら作戦が終わるまでダメだからな。"

# アクア
# そうじゃなくて、\nいくら女神の私でもスカルドラゴンは\n簡単に倒せないと思うの。
202 = "そうじゃなくて、\\nいくら女神の私でもスカルドラゴンは\\n簡単に倒せないと思うの。"

# カズマ＆めぐみん＆ダクネス
# display as ３人
# は？
# 227 = "は？"

# アクア
# もちろん、浄化する自信はあるわよ？\n女神の名に賭けて絶対にやってみせるわ。
231 = "もちろん、浄化する自信はあるわよ？\\n女神の名に賭けて絶対にやってみせるわ。"

# アクア
# でも、ぱぱっと簡単に、\nってわけにはいきそうにないのよね。
220 = "でも、ぱぱっと簡単に、\\nってわけにはいきそうにないのよね。"

# カズマ（Ｍ）
# display as カズマ
# （おいおいおいおいおい！！）
321 = "（おいおいおいおいおい！！）"

# アクア
# 前に、洞窟であいつを浄化しようとしたでしょ？\nその時、私、割と本気でやってたのよ。
254 = "前に、洞窟であいつを浄化しようとしたでしょ？\\nその時、私、割と本気でやってたのよ。"

# カズマ
# ……あれでか？\nものすっごい手を抜いてるように見えたんだが。
184 = "……あれでか？\\nものすっごい手を抜いてるように見えたんだが。"

# アクア
# 抜いてないわよ。\nちゃんと真面目にやってたわ。
262 = "抜いてないわよ。\\nちゃんと真面目にやってたわ。"

# カズマ（Ｍ）
# display as カズマ
# （微妙に信じられないが、\n　今、この状況で言い出したってことは\n　マジなのか）
324 = "（微妙に信じられないが、\\n　今、この状況で言い出したってことは\\n　マジなのか）"

# カズマ
# でも、あのドラゴン、めっちゃ苦しんでたし、\nあのまま続けてたらいけたんじゃないか？
219 = "でも、あのドラゴン、めっちゃ苦しんでたし、\\nあのまま続けてたらいけたんじゃないか？"

# アクア
# 認めたくないけど、あの魔法だと\n足止めするのが精一杯って感じなのよね。
316 = "認めたくないけど、あの魔法だと\\n足止めするのが精一杯って感じなのよね。"

# カズマ
# な、なあ、アクア。\n魔力増し増しでならなんとかなるんじゃないか？
223 = "な、なあ、アクア。\\n魔力増し増しでならなんとかなるんじゃないか？"

# アクア
# 魔力増し増し……。\nうーん、やってみないとわからないわね。
318 = "魔力増し増し……。\\nうーん、やってみないとわからないわね。"

# ダクネス
# アクア、洞窟で戦ったときとは状況が違う。
237 = "アクア、洞窟で戦ったときとは状況が違う。"

# ダクネス
# ゆんゆんが足止めするときにもダメージを\n与えられるだろうし――
233 = "ゆんゆんが足止めするときにもダメージを\\n与えられるだろうし――"

# ダクネス
# その後に待つのは、爆裂魔法の同時攻撃だ。\n瀕死とまではいかないが相当な傷を\n負わせられるだろう。
207 = "その後に待つのは、爆裂魔法の同時攻撃だ。\\n瀕死とまではいかないが相当な傷を\\n負わせられるだろう。"

# アクア
# うん、そうね。\nそう聞いたら、なんだかいけそうな気がしてきたわ！
192 = "うん、そうね。\\nそう聞いたら、なんだかいけそうな気がしてきたわ！"

# カズマ
# 本当に大丈夫なのかよ……。
263 = "本当に大丈夫なのかよ……。"

# クリス
# さて、それじゃああたしは、\nさっそく仕事に取りかかるね。
200 = "さて、それじゃああたしは、\\nさっそく仕事に取りかかるね。"

# ダクネス
# 偵察なら私も同行しよう。
253 = "偵察なら私も同行しよう。"

# クリス
# ダクネスにはゆんゆんを守る役目があるじゃない。
246 = "ダクネスにはゆんゆんを守る役目があるじゃない。"

# ダクネス
# そのための情報収集だ。
204 = "そのための情報収集だ。"

# ダクネス
# その姿をしっかり確認すれば、\n物理攻撃の手段は少なくとも把握できるだろう。
206 = "その姿をしっかり確認すれば、\\n物理攻撃の手段は少なくとも把握できるだろう。"

# ダクネス
# 爪で切り裂くのか、尾でなぎ払うのか、\nそれとも強靱な顎でかみ砕くのか……。
266 = "爪で切り裂くのか、尾でなぎ払うのか、\\nそれとも強靱な顎でかみ砕くのか……。"

# ダクネス
# ふ、ふふ、武者震いが止まらないぞ。
228 = "ふ、ふふ、武者震いが止まらないぞ。"

# カズマ（Ｍ）
# display as カズマ
# （いや、絶対に違う震えだろ、それ……）
320 = "（いや、絶対に違う震えだろ、それ……）"

# ダクネス
# というわけでカズマ、ちょっと行ってくりゅ！
221 = "というわけでカズマ、ちょっと行ってくりゅ！"

# クリス
# あは、あはは、それじゃまた後でね。
189 = "あは、あはは、それじゃまた後でね。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、もう、不安しかねー）
319 = "（ああ、もう、不安しかねー）"

