# st05a_02.txt.scn

[info]
0 = ""

[characters]
190 = "カズマ"
187 = "アクア"
183 = "めぐみん"
191 = "カズマ（Ｍ）"
193 = "ダクネス"

[character_subs]
# 190 = "カズマ"

[script]
# lines: 51

# カズマ
# いいか、お前ら。\n正直言って、何度も何度も同じ話をすることに\nうんざりしている気持ちはわかる。
159 = "いいか、お前ら。\\n正直言って、何度も何度も同じ話をすることに\\nうんざりしている気持ちはわかる。"

# カズマ
# だが、事態が解決しない限り俺達は前に進めない！\n未来はやってこないんだ！
172 = "だが、事態が解決しない限り俺達は前に進めない！\\n未来はやってこないんだ！"

# アクア
# つまり、何が言いたいのよ。
173 = "つまり、何が言いたいのよ。"

# カズマ
# ……金儲けの方法を考えるぞ。
155 = "……金儲けの方法を考えるぞ。"

# アクア
# えー、またー。
160 = "えー、またー。"

# めぐみん
# はっきり言って、時間の無駄にしか思えません。
179 = "はっきり言って、時間の無駄にしか思えません。"

# カズマ（Ｍ）
# display as カズマ
# （ぐぐぐ……。\n　今までのことを考えると、なにも言い返せない）
247 = "（ぐぐぐ……。\\n　今までのことを考えると、なにも言い返せない）"

# ダクネス
# まあ、そう言うな。\n今日こそ良い案が出るかもしれないだろう？
181 = "まあ、そう言うな。\\n今日こそ良い案が出るかもしれないだろう？"

# アクア
# どうかしらね？\nでないと思うけど。
175 = "どうかしらね？\\nでないと思うけど。"

# ダクネス
# 確かにそうかもしれないが、\nやる前から諦めていたら、出るものも出ないだろう。
241 = "確かにそうかもしれないが、\\nやる前から諦めていたら、出るものも出ないだろう。"

# アクア
# それはそうだけど。
170 = "それはそうだけど。"

# めぐみん
# はあ、仕方ありませんね。\nもう一度、考えてみますか。
178 = "はあ、仕方ありませんね。\\nもう一度、考えてみますか。"

# カズマ
# おう、頼むぜ。
163 = "おう、頼むぜ。"

# ダクネス
# ああ、そうだ。\n考える前に、１つ問題があるのだが。
156 = "ああ、そうだ。\\n考える前に、１つ問題があるのだが。"

# カズマ（Ｍ）
# display as カズマ
# （問題？）
251 = "（問題？）"

# ダクネス
# 金策のために何かやるとしても、\n元手となる金がない。
245 = "金策のために何かやるとしても、\\n元手となる金がない。"

# カズマ
# そっか、前回の洞窟調査の準備で\n色々買ったりしたもんな。
167 = "そっか、前回の洞窟調査の準備で\\n色々買ったりしたもんな。"

# ダクネス
# その上、報酬が手に入らなかっただろう？\n結果として収入ゼロどころかマイナスだったんだ。
168 = "その上、報酬が手に入らなかっただろう？\\n結果として収入ゼロどころかマイナスだったんだ。"

# アクア
# えー？\nじゃあ、ますます\nどうすることもできないじゃない。
161 = "えー？\\nじゃあ、ますます\\nどうすることもできないじゃない。"

# めぐみん
# 何をするにしても、お金は必要ですからね。
198 = "何をするにしても、お金は必要ですからね。"

# アクア
# どうするのよ、カズマ。\n私もう、肉体労働は嫌よ。
176 = "どうするのよ、カズマ。\\n私もう、肉体労働は嫌よ。"

# カズマ（Ｍ）
# display as カズマ
# （俺だってあんなきつい仕事はもうしたくない）
250 = "（俺だってあんなきつい仕事はもうしたくない）"

# カズマ（Ｍ）
# display as カズマ
# （考えろ！　なにか考えるんだ！\n　金を稼ぐ方法を！）
252 = "（考えろ！　なにか考えるんだ！\\n　金を稼ぐ方法を！）"

# カズマ
# アクアの出張宴会芸！\nこれだ！
189 = "アクアの出張宴会芸！\\nこれだ！"

# アクア
# あんたは、私をなんだと思ってるのよ。
158 = "あんたは、私をなんだと思ってるのよ。"

# カズマ
# 回復魔法の使える宴会芸の女神。
202 = "回復魔法の使える宴会芸の女神。"

# アクア
# せめて逆にしなさいよ！\n宴会芸の使える回復魔法の女神に！
164 = "せめて逆にしなさいよ！\\n宴会芸の使える回復魔法の女神に！"

# カズマ
# 言っとくけどな、割と真面目に考えてるぞ？\nお前、よくギルドとか街中でも宴会芸やってるし、\n評判良いし、意外に儲かりそうだ。
244 = "言っとくけどな、割と真面目に考えてるぞ？\\nお前、よくギルドとか街中でも宴会芸やってるし、\\n評判良いし、意外に儲かりそうだ。"

# アクア
# 絶対に嫌よ！\n私は、芸を安売りしない女なんですからね。
243 = "絶対に嫌よ！\\n私は、芸を安売りしない女なんですからね。"

# カズマ（Ｍ）
# display as カズマ
# （マジ使えねー女神だな）
249 = "（マジ使えねー女神だな）"

# カズマ
# ダクネスのメイン盾代理！
195 = "ダクネスのメイン盾代理！"

# ダクネス
# 私か？\nそれに、メイン盾とはなんだ？
242 = "私か？\\nそれに、メイン盾とはなんだ？"

# カズマ
# まあ、優れた防御役ってことだな。
182 = "まあ、優れた防御役ってことだな。"

# カズマ
# ダクネスの頑丈さを欲しがるパーティーは\n多いと思うし、そういうところに\n１回いくらかで雇ってもらうのはどうだ？
196 = "ダクネスの頑丈さを欲しがるパーティーは\\n多いと思うし、そういうところに\\n１回いくらかで雇ってもらうのはどうだ？"

# ダクネス
# それは気が進まないな。
171 = "それは気が進まないな。"

# カズマ
# え？　ダメか？
162 = "え？　ダメか？"

# ダクネス
# クルセイダーとは、仲間や弱き者を守るのだ。\nそこに直接、金銭のやりとりを\n発生させるのは、私の信念にそわない。
192 = "クルセイダーとは、仲間や弱き者を守るのだ。\\nそこに直接、金銭のやりとりを\\n発生させるのは、私の信念にそわない。"

# カズマ（Ｍ）
# display as カズマ
# （うーん、そういうもんか。\n　まあ、なんとなくはわかるけど）
246 = "（うーん、そういうもんか。\\n　まあ、なんとなくはわかるけど）"

# カズマ
# めぐみんのレンタル大砲！\nこれでどうだ？
185 = "めぐみんのレンタル大砲！\\nこれでどうだ？"

# めぐみん
# 大砲？\nどういうことですか？
203 = "大砲？\\nどういうことですか？"

# カズマ
# もちろん爆裂魔法だよ。\n他にないだろ？
186 = "もちろん爆裂魔法だよ。\\n他にないだろ？"

# カズマ
# ほら、爆裂魔法ってさ、\n身につけるのはなんだけど\n使ってみたいって人も多そうだろ？
180 = "ほら、爆裂魔法ってさ、\\n身につけるのはなんだけど\\n使ってみたいって人も多そうだろ？"

# カズマ
# そういう人の元にめぐみんを派遣して、\n爆裂魔法をお試ししてもらうんだよ。
165 = "そういう人の元にめぐみんを派遣して、\\n爆裂魔法をお試ししてもらうんだよ。"

# めぐみん
# 嫌ですよ、そんなの。\n爆裂魔法とは、そんなに軽々しく\n扱われるべきではないのです。
204 = "嫌ですよ、そんなの。\\n爆裂魔法とは、そんなに軽々しく\\n扱われるべきではないのです。"

# カズマ（Ｍ）
# display as カズマ
# （こいつ、普段はポンポン撃つくせに！）
248 = "（こいつ、普段はポンポン撃つくせに！）"

# ダクネス
# なあ、カズマ。\nここはやはり、クエストが\n一番希望があるんじゃないか？
177 = "なあ、カズマ。\\nここはやはり、クエストが\\n一番希望があるんじゃないか？"

# めぐみん
# そうでしょうか？\n前に見に行った時、ろくなものが\nありませんでしたよね？
166 = "そうでしょうか？\\n前に見に行った時、ろくなものが\\nありませんでしたよね？"

# ダクネス
# あの後、新しいクエストが\n追加されたかもしれないぞ？
157 = "あの後、新しいクエストが\\n追加されたかもしれないぞ？"

# ダクネス
# それに、はぐれリザード退治のクエストは\n昨日の時点でもまだあったんだ！\nやはり、あれに挑戦すべきだろう！
169 = "それに、はぐれリザード退治のクエストは\\n昨日の時点でもまだあったんだ！\\nやはり、あれに挑戦すべきだろう！"

# カズマ
# 却下だ。
199 = "却下だ。"

# カズマ
# でもまあ、ここで顔をつきあわせてても\n意味なさそうだし、\nダメ元で見に行ってみるか。
174 = "でもまあ、ここで顔をつきあわせてても\\n意味なさそうだし、\\nダメ元で見に行ってみるか。"

[selections]
188 = "アクアの出張宴会芸"
194 = "ダクネスのメイン盾代理"
184 = "めぐみんのレンタル大砲"
