# st05a_10.txt.scn

[info]
0 = ""

[characters]
53 = "カズマ（Ｍ）"

[character_subs]
52 = "カズマ"

[script]
# lines: 5

# カズマ（Ｍ）
# display as カズマ
# （そして、次の日。\n　このろくでもない世界に来たばかり頃のような、\n　労働三昧の日々がスタートした）
54 = "（そして、次の日。\\n　このろくでもない世界に来たばかり頃のような、\\n　労働三昧の日々がスタートした）"

# カズマ（Ｍ）
# display as カズマ
# （久々の肉体労働……。\n　ぶっちゃけ、ここまでキツイもんだとは\n　思わなかった……）
57 = "（久々の肉体労働……。\\n　ぶっちゃけ、ここまでキツイもんだとは\\n　思わなかった……）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、最近はろくに冒険にも\n　出れてなかったわけだし、\n　なまってたってことなのかもなぁ）
55 = "（まあ、最近はろくに冒険にも\\n　出れてなかったわけだし、\\n　なまってたってことなのかもなぁ）"

# カズマ（Ｍ）
# display as カズマ
# （夕方、ようやくその日のノルマを終えた俺は\n　めぐみんとゆんゆんが働いている食堂に\n　行ってみることにした）
58 = "（夕方、ようやくその日のノルマを終えた俺は\\n　めぐみんとゆんゆんが働いている食堂に\\n　行ってみることにした）"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんはともかく、めぐみんが\n　ちゃんとやれてるのか、ちょっと心配だしな）
56 = "（ゆんゆんはともかく、めぐみんが\\n　ちゃんとやれてるのか、ちょっと心配だしな）"

