# st05c_05.txt.scn

[info]
0 = ""

[characters]
124 = "カズマ"
122 = "エリス"
125 = "カズマ（Ｍ）"
121 = "アクア"

[character_subs]
# 124 = "カズマ"

[script]
# lines: 35

# カズマ
# ……………………。
103 = "……………………。"

# カズマ
# ………………。
104 = "………………。"

# カズマ
# …………。
105 = "…………。"

# カズマ
# はっ！！
118 = "はっ！！"

# エリス
# …………。
# 105 = "…………。"

# カズマ
# なっ！？
114 = "なっ！？"

# カズマ（Ｍ）
# display as カズマ
# （ちょっと待て！　エリス様がいるってことは俺！）
138 = "（ちょっと待て！　エリス様がいるってことは俺！）"

# カズマ
# もしかして、俺、死んだんですか？
120 = "もしかして、俺、死んだんですか？"

# エリス
# はい、そうなりますね。
117 = "はい、そうなりますね。"

# カズマ
# ええ！？　なんで！
109 = "ええ！？　なんで！"

# エリス
# 原因は、知らないほうがいいです。
130 = "原因は、知らないほうがいいです。"

# カズマ
# え……。
108 = "え……。"

# エリス
# 知らないほうがいいです。
135 = "知らないほうがいいです。"

# カズマ
# ２回言った！？
145 = "２回言った！？"

# カズマ（Ｍ）
# display as カズマ
# （れ、冷静に思い出せ？\n　あの時、みんなが笑顔で迫ってきて、\n　その後の記憶がない）
141 = "（れ、冷静に思い出せ？\\n　あの時、みんなが笑顔で迫ってきて、\\n　その後の記憶がない）"

# カズマ（Ｍ）
# display as カズマ
# （ってことは、パンツを盗られたみんなに……？）
139 = "（ってことは、パンツを盗られたみんなに……？）"

# アクア
# カーズーマー！\nもう戻ってきていいわよー！
126 = "カーズーマー！\\nもう戻ってきていいわよー！"

# カズマ
# おわっ！？\nア、アクア！？
110 = "おわっ！？\\nア、アクア！？"

# アクア
# 今、あんたの体に復活魔法をかけたから！\nさっさと帰ってきなさい！
129 = "今、あんたの体に復活魔法をかけたから！\\nさっさと帰ってきなさい！"

# エリス
# ああ……。\nまたアクア先輩は……こういうのは困るのに。
106 = "ああ……。\\nまたアクア先輩は……こういうのは困るのに。"

# カズマ（Ｍ）
# display as カズマ
# （エリス様が頭を抱えてるんだが。\n　いいのか、このまま生き返っちまって）
142 = "（エリス様が頭を抱えてるんだが。\\n　いいのか、このまま生き返っちまって）"

# アクア
# エリスがあーだこーだ言いそうなら、\nパットをスティールしてやりなさい！
123 = "エリスがあーだこーだ言いそうなら、\\nパットをスティールしてやりなさい！"

# エリス
# ちょっ！？
112 = "ちょっ！？"

# カズマ
# マジで！？\nいいの？　やっちゃっていいの！？
127 = "マジで！？\\nいいの？　やっちゃっていいの！？"

# エリス
# だ、ダメです！
111 = "だ、ダメです！"

# エリス
# もう、アクア先輩は本当に勝手な。
119 = "もう、アクア先輩は本当に勝手な。"

# エリス
# では、カズマさん。\n今からあなたを現世に送ります。
113 = "では、カズマさん。\\n今からあなたを現世に送ります。"

# カズマ
# なんか、すみません……。\nアクアの奴が……。
115 = "なんか、すみません……。\\nアクアの奴が……。"

# エリス
# いえ、あなたが謝ることはありませんよ。\nそれでは、お気をつけて。\nあなたに祝福があらんことを。
107 = "いえ、あなたが謝ることはありませんよ。\\nそれでは、お気をつけて。\\nあなたに祝福があらんことを。"

# カズマ
# は、はい！\nありがとうございます。
116 = "は、はい！\\nありがとうございます。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、やっぱりいいなぁエリス様は。\n　この笑顔！　この優しさ！\n　これぞ真のヒロインだよ！）
136 = "（ああ、やっぱりいいなぁエリス様は。\\n　この笑顔！　この優しさ！\\n　これぞ真のヒロインだよ！）"

# カズマ（Ｍ）
# display as カズマ
# （それにしても――\n　このままじゃ、みんなに合わせる顔がないよな）
137 = "（それにしても――\\n　このままじゃ、みんなに合わせる顔がないよな）"

# カズマ（Ｍ）
# display as カズマ
# （つい、いいことをした気になってたけど\n　勝手に、あのドラゴンに\n　パンツを差し出しちまったんだ）
140 = "（つい、いいことをした気になってたけど\\n　勝手に、あのドラゴンに\\n　パンツを差し出しちまったんだ）"

# カズマ（Ｍ）
# display as カズマ
# （盗んでしまった物を返せないなんて、\n　紳士としてあるまじき行為じゃないか！）
144 = "（盗んでしまった物を返せないなんて、\\n　紳士としてあるまじき行為じゃないか！）"

# カズマ（Ｍ）
# display as カズマ
# （戻ったら、ちゃんとパンツを\n　買って返してあげよう。\n　それが紳士の務めだ、そうだとも！）
143 = "（戻ったら、ちゃんとパンツを\\n　買って返してあげよう。\\n　それが紳士の務めだ、そうだとも！）"

