# st05a_08.txt.scn

[info]
0 = ""

[characters]
273 = "めぐみん"
281 = "クリス"
279 = "カズマ（Ｍ）"
277 = "アクア"
280 = "キース"
278 = "カズマ"
284 = "ダスト"
283 = "ダクネス"
274 = "ゆんゆん"

[character_subs]
# 278 = "カズマ"

[script]
# lines: 63

# めぐみん
# バイトの募集って、結構、あるものなのですね。
285 = "バイトの募集って、結構、あるものなのですね。"

# クリス
# この街はそこそこ栄えてるからね。\n魔王の城から一番遠くて平和だから、\n日常的な仕事が多いんだよ。
245 = "この街はそこそこ栄えてるからね。\\n魔王の城から一番遠くて平和だから、\\n日常的な仕事が多いんだよ。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、平和なお陰で稼ぎの良いクエストが\n　なかなか出なかったりもするんだろうけどな）
342 = "（まあ、平和なお陰で稼ぎの良いクエストが\\n　なかなか出なかったりもするんだろうけどな）"

# アクア
# けど、どれもお給料安いわね。\nこれなら私と一緒に呼び込みのバイトした方が\nいいんじゃないかしら。
243 = "けど、どれもお給料安いわね。\\nこれなら私と一緒に呼び込みのバイトした方が\\nいいんじゃないかしら。"

# めぐみん
# えっ！？\nあれはちょっと、私には難易度が高いのですが！
235 = "えっ！？\\nあれはちょっと、私には難易度が高いのですが！"

# アクア
# さすがめぐみん、わかってるわね。\n呼び込みって簡単なように見えて、\n声の張り方１つにもコツってものが必要なのよ。
247 = "さすがめぐみん、わかってるわね。\\n呼び込みって簡単なように見えて、\\n声の張り方１つにもコツってものが必要なのよ。"

# カズマ（Ｍ）
# display as カズマ
# （何を得意げに語ってるんだ、こいつは）
344 = "（何を得意げに語ってるんだ、こいつは）"

# キース
# ん？\nカズマじゃないか。
276 = "ん？\\nカズマじゃないか。"

# カズマ
# ああ、キース、それにダストか。
228 = "ああ、キース、それにダストか。"

# ダスト
# なんつーか、\nあいかわらずの良いご身分だなぁ。
257 = "なんつーか、\\nあいかわらずの良いご身分だなぁ。"

# カズマ
# は？　何がだ？
261 = "は？　何がだ？"

# ダスト
# ちょっと耳貸せ。
250 = "ちょっと耳貸せ。"

# カズマ
# お、おう。
237 = "お、おう。"

# ダスト
# こんだけ女の子を引き連れといて、\nしれっとしてんじゃねーよ。
246 = "こんだけ女の子を引き連れといて、\\nしれっとしてんじゃねーよ。"

# カズマ
# はあ……できることなら代わってやりたいぜ。
259 = "はあ……できることなら代わってやりたいぜ。"

# ダスト
# ぐぐっ！\nまた余裕ぶっこいた発言をっ！
242 = "ぐぐっ！\\nまた余裕ぶっこいた発言をっ！"

# アクア
# ねえ、ちょっとカズマー？\nそんなことしてる暇ないんですけどー？
258 = "ねえ、ちょっとカズマー？\\nそんなことしてる暇ないんですけどー？"

# カズマ
# へいへい。
263 = "へいへい。"

# キース
# ああ、そういやさ、割引交渉はどうだったんだ？\nうまくいったのか？
226 = "ああ、そういやさ、割引交渉はどうだったんだ？\\nうまくいったのか？"

# カズマ
# いや、全然。
231 = "いや、全然。"

# ダスト
# んじゃ、どうすんだよ。\n方法がないから交渉に行ったんだろ？
275 = "んじゃ、どうすんだよ。\\n方法がないから交渉に行ったんだろ？"

# カズマ
# そうなんだけどさ、結局、\nコツコツと貯めてくしかないって\n結論に至ったんだ。
248 = "そうなんだけどさ、結局、\\nコツコツと貯めてくしかないって\\n結論に至ったんだ。"

# キース
# １周回って元に戻ったわけか。\nにしても、３０００万エリスをコツコツとは\n気が遠くなる話だ。
345 = "１周回って元に戻ったわけか。\\nにしても、３０００万エリスをコツコツとは\\n気が遠くなる話だ。"

# カズマ
# まあ、やるしかねーよ。
267 = "まあ、やるしかねーよ。"

# ダスト
# なんだよ、いきなりいい顔しやがって。\nでも、そうなると、こっちとしても\nちょっとは協力してやらねーとな！
254 = "なんだよ、いきなりいい顔しやがって。\\nでも、そうなると、こっちとしても\\nちょっとは協力してやらねーとな！"

# ダスト
# あっちの食堂でウェイトレスを募集してたぜ。\nしかも、割と給料もいいんだ。
229 = "あっちの食堂でウェイトレスを募集してたぜ。\\nしかも、割と給料もいいんだ。"

# カズマ
# お、本当か！？
238 = "お、本当か！？"

# ダスト
# ほら、早く行ってこいよ、枠が埋まっちまうぞ？
265 = "ほら、早く行ってこいよ、枠が埋まっちまうぞ？"

# カズマ
# サンキュー！\n助かるよ、持つべき者は友達だな！
282 = "サンキュー！\\n助かるよ、持つべき者は友達だな！"

# キース
# まあ、貸しにしとく。\nいつか返してくれよ？
269 = "まあ、貸しにしとく。\\nいつか返してくれよ？"

# カズマ
# みんな、聞いたか？\nウェイトレスのバイトだってさ。
271 = "みんな、聞いたか？\\nウェイトレスのバイトだってさ。"

# ダクネス
# うむ、悪くない話だな。\nひとまず行ってみるとするか。
234 = "うむ、悪くない話だな。\\nひとまず行ってみるとするか。"

# めぐみん
# 本当に行くんですか？
293 = "本当に行くんですか？"

# カズマ
# なんだよ、その嫌そうな顔は。\nせっかくキース達が教えてくれたんだぜ？
255 = "なんだよ、その嫌そうな顔は。\\nせっかくキース達が教えてくれたんだぜ？"

# めぐみん
# けど、ウェイトレスなんですよね？
244 = "けど、ウェイトレスなんですよね？"

# アクア
# え？　ウェイトレスは嫌なの？
236 = "え？　ウェイトレスは嫌なの？"

# めぐみん
# いえ、その、\nあまり好みではないと言いますか。
230 = "いえ、その、\\nあまり好みではないと言いますか。"

# カズマ
# は？　なんで？
260 = "は？　なんで？"

# めぐみん
# 昔、ちょっと。
292 = "昔、ちょっと。"

# ゆんゆん
# ああ、そっか。\n前に――
227 = "ああ、そっか。\\n前に――"

# ゆんゆん
# 痛いっ！？
295 = "痛いっ！？"

# ダクネス
# どうした！？
252 = "どうした！？"

# ゆんゆん
# め、めぐみんが足を踏んで、いたたたっ！
272 = "め、めぐみんが足を踏んで、いたたたっ！"

# めぐみん
# 踏んでなどいませんよ？\nたまたま、踏み出した先に\nゆんゆんの足があっただけです。
338 = "踏んでなどいませんよ？\\nたまたま、踏み出した先に\\nゆんゆんの足があっただけです。"

# ゆんゆん
# で、でも、今、\n思いっきりグリグリって。
251 = "で、でも、今、\\n思いっきりグリグリって。"

# めぐみん
# 私のせいだと言うんですか？\nたまたま、そこにあっただけですよ？\nつまりこれは事故です。
335 = "私のせいだと言うんですか？\\nたまたま、そこにあっただけですよ？\\nつまりこれは事故です。"

# カズマ
# なあ、めぐみん。\nウェイトレスが好みじゃないって\nつまり、やりたくないってことか？
253 = "なあ、めぐみん。\\nウェイトレスが好みじゃないって\\nつまり、やりたくないってことか？"

# めぐみん
# まあ、そうとも言いますね。
266 = "まあ、そうとも言いますね。"

# カズマ
# お前、向いてなさそうだもんな。
240 = "お前、向いてなさそうだもんな。"

# めぐみん
# ほほう？\nそれはどういった根拠に基づいた判断なのか、\nぜひ聞かせて頂きたいですね。
264 = "ほほう？\\nそれはどういった根拠に基づいた判断なのか、\\nぜひ聞かせて頂きたいですね。"

# カズマ
# なんだよ。\n図星をさされて逆ギレか？
256 = "なんだよ。\\n図星をさされて逆ギレか？"

# めぐみん
# 違うわい！
339 = "違うわい！"

# カズマ
# 難しいもんじゃないぞ。\n苦手意識を持ってるから、\nうまくいかないのかもしれないぞ？
341 = "難しいもんじゃないぞ。\\n苦手意識を持ってるから、\\nうまくいかないのかもしれないぞ？"

# めぐみん
# そうなんでしょうか？
249 = "そうなんでしょうか？"

# カズマ
# まあ、１回苦手だって思っちまってから\n考え直すのは難しいだろうけどさ――
270 = "まあ、１回苦手だって思っちまってから\\n考え直すのは難しいだろうけどさ――"

# カズマ
# 挑戦しないと、ずっとそのままだぜ？\nそれでいいのかよ、めぐみん。
291 = "挑戦しないと、ずっとそのままだぜ？\\nそれでいいのかよ、めぐみん。"

# めぐみん
# うう、カズマのくせに正論を。
232 = "うう、カズマのくせに正論を。"

# カズマ
# 紅魔族流の接客を見せてくれよ。
337 = "紅魔族流の接客を見せてくれよ。"

# めぐみん
# ふふ、なるほど。\n禁じられた我が技を見たいというのか。
262 = "ふふ、なるほど。\\n禁じられた我が技を見たいというのか。"

# めぐみん
# くくく、だが好奇心は猫を殺すのだ。\n身の程を知るがいい！
241 = "くくく、だが好奇心は猫を殺すのだ。\\n身の程を知るがいい！"

# カズマ（Ｍ）
# display as カズマ
# （チッ、いつも通り\n　厨二病のノリでその気にさせようと\n　思ったんだが、うまくいかなかったな）
343 = "（チッ、いつも通り\\n　厨二病のノリでその気にさせようと\\n　思ったんだが、うまくいかなかったな）"

# クリス
# まあ、引き受けるかは別として、\n話だけでも聞いてみようよ。\nせっかく教えてもらったんだしさ。
268 = "まあ、引き受けるかは別として、\\n話だけでも聞いてみようよ。\\nせっかく教えてもらったんだしさ。"

# ダクネス
# うむ、そうだな。\n行ってみよう。
233 = "うむ、そうだな。\\n行ってみよう。"

[selections]
239 = "お前、向いてなさそうだもんな"
340 = "難しいもんじゃないぞ"
336 = "紅魔族流の接客を見せてくれよ"
