# st05b_02.txt.scn

[info]
0 = ""

[characters]
280 = "カズマ"
285 = "バニル"
278 = "アクア"
279 = "ウィズ"
282 = "カズマ（Ｍ）"
284 = "ダクネス"
269 = "めぐみん"
274 = "ゆんゆん"
283 = "クリス"

[character_subs]
# 280 = "カズマ"

[script]
# lines: 99

# カズマ
# バニルッ！　いるか！？
286 = "バニルッ！　いるか！？"

# バニル
# おお、ようやく来たか。\n遅かったではないか。
229 = "おお、ようやく来たか。\\n遅かったではないか。"

# カズマ
# その様子だと、\n今、何がどうなってるのかも\nしっかり見通してるみたいだな。
245 = "その様子だと、\\n今、何がどうなってるのかも\\nしっかり見通してるみたいだな。"

# バニル
# フハハハハッ！\n愚問であるぞ、小僧。
288 = "フハハハハッ！\\n愚問であるぞ、小僧。"

# バニル
# そこの紅魔の娘が洞窟を壊し、\n追い出されることとなった\n哀れなスカルドラゴン――
241 = "そこの紅魔の娘が洞窟を壊し、\\n追い出されることとなった\\n哀れなスカルドラゴン――"

# バニル
# そやつが、この街に\n向かってきているのであろう？
248 = "そやつが、この街に\\n向かってきているのであろう？"

# カズマ
# ああ、その通りだよ！\nそれで、聞きたいのはこの指輪のことだ！
214 = "ああ、その通りだよ！\\nそれで、聞きたいのはこの指輪のことだ！"

# バニル
# その指輪がどうかしたのか？
243 = "その指輪がどうかしたのか？"

# カズマ
# この期に及んでしらばっくれるなよ。\nスカルドラゴンはこの指輪に反応してるんだろ。
234 = "この期に及んでしらばっくれるなよ。\\nスカルドラゴンはこの指輪に反応してるんだろ。"

# バニル
# どこかの駆け出しプリーストと違い、\nその程度を推測する力は持っているか。
262 = "どこかの駆け出しプリーストと違い、\\nその程度を推測する力は持っているか。"

# アクア
# はぁ？　なんですって？
265 = "はぁ？　なんですって？"

# ウィズ
# もうバニルさん。\nいちいちアクア様を挑発するのはやめてください。
271 = "もうバニルさん。\\nいちいちアクア様を挑発するのはやめてください。"

# カズマ
# お前もいちいち噛みつくな。
233 = "お前もいちいち噛みつくな。"

# ウィズ
# それで、スカルドラゴンがどうしてカズマさんの\n指輪に反応を？
251 = "それで、スカルドラゴンがどうしてカズマさんの\\n指輪に反応を？"

# バニル
# ふむ。\nそうであるな、どこから説明すべきか\n迷うところではあるが。
268 = "ふむ。\\nそうであるな、どこから説明すべきか\\n迷うところではあるが。"

# バニル
# 小僧よ、その指輪の来歴を覚えているか？
296 = "小僧よ、その指輪の来歴を覚えているか？"

# カズマ（Ｍ）
# display as カズマ
# （来歴って……）
367 = "（来歴って……）"

# ダクネス
# 確か、下着泥棒の貴族の弟が\n兄の無念を晴らすために\n作り出した物だったはずだな。
353 = "確か、下着泥棒の貴族の弟が\\n兄の無念を晴らすために\\n作り出した物だったはずだな。"

# バニル
# うむ、その通り。
223 = "うむ、その通り。"

# アクア
# それで？\nスカルドラゴンとどう結びつくのよ。\nもったいぶってないで、とっとと話しなさい。
253 = "それで？\\nスカルドラゴンとどう結びつくのよ。\\nもったいぶってないで、とっとと話しなさい。"

# バニル
# やれやれ、せっかちな女であるな。\nせっかくこちらが、汝らにもわかるよう、\n懇切丁寧に話してやろうとしているのに。
273 = "やれやれ、せっかちな女であるな。\\nせっかくこちらが、汝らにもわかるよう、\\n懇切丁寧に話してやろうとしているのに。"

# アクア
# あらぁ、そうでしたのね？\nお優しいこと！　おほほほほほ！
219 = "あらぁ、そうでしたのね？\\nお優しいこと！　おほほほほほ！"

# カズマ
# おいアクア、ちょっと黙ってろ。\nいいから黙ってろ。\nホント、黙ってくれ。
228 = "おいアクア、ちょっと黙ってろ。\\nいいから黙ってろ。\\nホント、黙ってくれ。"

# アクア
# ３回も言う！？
369 = "３回も言う！？"

# カズマ
# それで、バニル。\nこの指輪とドラゴンの関係はなんなんだ？
252 = "それで、バニル。\\nこの指輪とドラゴンの関係はなんなんだ？"

# カズマ
# もう、ズバッと言ってくれ。\nこうしている間にも、\nドラゴンがこの街に迫ってきてるんだよ。
270 = "もう、ズバッと言ってくれ。\\nこうしている間にも、\\nドラゴンがこの街に迫ってきてるんだよ。"

# バニル
# では、お望み通りに結論から言おう。\nあのスカルドラゴンは――
260 = "では、お望み通りに結論から言おう。\\nあのスカルドラゴンは――"

# バニル
# 兄のために指輪を作った弟、\nそのなれの果てである。
291 = "兄のために指輪を作った弟、\\nそのなれの果てである。"

# カズマ
# ……はあ？
212 = "……はあ？"

# バニル
# んん？　聞こえなかったのであるか？\n兄のために指輪を作った弟。\nそれがあのスカルドラゴンの正体だ。
276 = "んん？　聞こえなかったのであるか？\\n兄のために指輪を作った弟。\\nそれがあのスカルドラゴンの正体だ。"

# アクア
# ねえ、あんた、\n自分がなに言ってるかわかってる？
264 = "ねえ、あんた、\\n自分がなに言ってるかわかってる？"

# バニル
# 当然であるぞ？\n我輩はどこぞの連中と違って\nあやふやなことは口にしないのでな。
301 = "当然であるぞ？\\n我輩はどこぞの連中と違って\\nあやふやなことは口にしないのでな。"

# めぐみん
# あの、念のために聞きますが――
218 = "あの、念のために聞きますが――"

# めぐみん
# 貴族の兄弟は人間だったんですよね？\nスカルドラゴンの兄弟だった、なんて\nオチではありませんよね？
355 = "貴族の兄弟は人間だったんですよね？\\nスカルドラゴンの兄弟だった、なんて\\nオチではありませんよね？"

# バニル
# 無論、人間である。
306 = "無論、人間である。"

# カズマ
# いやいや、おかしいだろ。\n今こっちに来てるのはスカルドラゴンだぞ？
221 = "いやいや、おかしいだろ。\\n今こっちに来てるのはスカルドラゴンだぞ？"

# カズマ
# いったい何をどうやれば、\n人間がドラゴンになれるっていうんだよ。
220 = "いったい何をどうやれば、\\n人間がドラゴンになれるっていうんだよ。"

# ウィズ
# あっ、もしかして魂の憑依ですか！？
216 = "あっ、もしかして魂の憑依ですか！？"

# バニル
# その通り！
247 = "その通り！"

# バニル
# 指輪に組み込まれた術式の複雑さから、\n作成者がその道、つまり呪いの知識に長けていたと\nわかる。
303 = "指輪に組み込まれた術式の複雑さから、\\n作成者がその道、つまり呪いの知識に長けていたと\\nわかる。"

# バニル
# おそらくだがその者は生前、\n黒魔術師か死霊使いの類いであったのだろう。
230 = "おそらくだがその者は生前、\\n黒魔術師か死霊使いの類いであったのだろう。"

# カズマ（Ｍ）
# display as カズマ
# （その力を使って、こんな変態指輪を作ったのか。\n　なんて才能の無駄遣い！）
360 = "（その力を使って、こんな変態指輪を作ったのか。\\n　なんて才能の無駄遣い！）"

# ゆんゆん
# あ、あの、魂の憑依ってそんなに簡単に\nできるものなんですか？
213 = "あ、あの、魂の憑依ってそんなに簡単に\\nできるものなんですか？"

# バニル
# %fsyogen;黒魔術に興味があるのか？\n孤独に愛される娘よ。
26 = "%fsyogen;黒魔術に興味があるのか？\\n孤独に愛される娘よ。"

# カズマ（Ｍ）
# display as カズマ
# （孤独に愛される娘……。\n　怪しい！　いや、怪しいか？）
366 = "（孤独に愛される娘……。\\n　怪しい！　いや、怪しいか？）"

# カズマ（Ｍ）
# display as カズマ
# （まあでも念のため証言として押さえておこう）
363 = "（まあでも念のため証言として押さえておこう）"

# ゆんゆん
# そ、そんなものに愛されていません！
237 = "そ、そんなものに愛されていません！"

# ゆんゆん
# 私はただ、紅魔族の長となる者として、\n少しでも魔術に関する知識を得たいだけなんです！
354 = "私はただ、紅魔族の長となる者として、\\n少しでも魔術に関する知識を得たいだけなんです！"

# バニル
# 娘、お前の質問の答えはこうだ。\n人間が想像できる程度のことは、\nだいたいが実現可能。
295 = "娘、お前の質問の答えはこうだ。\\n人間が想像できる程度のことは、\\nだいたいが実現可能。"

# バニル
# それこそ不老不死になることもな。
250 = "それこそ不老不死になることもな。"

# ゆんゆん
# そ、そうなんですか！？
236 = "そ、そうなんですか！？"

# めぐみん
# あなたが不死を求めてどうするんです。\n終わることのないぼっち生活が\n待ってるだけなんですよ。
217 = "あなたが不死を求めてどうするんです。\\n終わることのないぼっち生活が\\n待ってるだけなんですよ。"

# ゆんゆん
# ひ、ひどいよ、めぐみん！
267 = "ひ、ひどいよ、めぐみん！"

# カズマ
# てか、なんで、魂の憑依なんてやったんだよ。\n大人しく死んどけっての。
259 = "てか、なんで、魂の憑依なんてやったんだよ。\\n大人しく死んどけっての。"

# バニル
# 弟は、指輪を作って兄の無念を晴らそうとした。\nしかし、それだけでは気持ちが収まらなかったのだ。
300 = "弟は、指輪を作って兄の無念を晴らそうとした。\\nしかし、それだけでは気持ちが収まらなかったのだ。"

# カズマ
# はあ？　この指輪だけでも相当に迷惑なんだが？
266 = "はあ？　この指輪だけでも相当に迷惑なんだが？"

# バニル
# それはあくまで第三者から見た場合だ。\n弟は、さらなる復讐を望んだ。
254 = "それはあくまで第三者から見た場合だ。\\n弟は、さらなる復讐を望んだ。"

# バニル
# 下着を収集する、という\nささやかな趣味を否定した世界への復讐をな。
289 = "下着を収集する、という\\nささやかな趣味を否定した世界への復讐をな。"

# カズマ
# え、ええと……。
225 = "え、ええと……。"

# めぐみん
# すみません。\nもはや、どこからツッコめばいいのか\nわからないのですが。
235 = "すみません。\\nもはや、どこからツッコめばいいのか\\nわからないのですが。"

# カズマ
# 大丈夫だ。\n俺もまったく同じ気持ちだ。
294 = "大丈夫だ。\\n俺もまったく同じ気持ちだ。"

# ゆんゆん
# %fsyogen;し、下着泥棒は犯罪ですよっ！\nささやかな趣味なんかじゃありませんっ！
25 = "%fsyogen;し、下着泥棒は犯罪ですよっ！\\nささやかな趣味なんかじゃありませんっ！"

# カズマ（Ｍ）
# display as カズマ
# （そう！　下着泥棒も立派な犯罪だ！）
359 = "（そう！　下着泥棒も立派な犯罪だ！）"

# カズマ（Ｍ）
# display as カズマ
# （でも、無意識にとはいえ\n　それをしちゃってる人間を目の前に\n　言い切ることないだろ……）
361 = "（でも、無意識にとはいえ\\n　それをしちゃってる人間を目の前に\\n　言い切ることないだろ……）"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんらしくなく、冷静さを失ってる？\n　証言としてゲットしておくか）
364 = "（ゆんゆんらしくなく、冷静さを失ってる？\\n　証言としてゲットしておくか）"

# バニル
# それもまた、第三者の価値観である。
255 = "それもまた、第三者の価値観である。"

# クリス
# いやいや、常識でしょ？
222 = "いやいや、常識でしょ？"

# バニル
# フハハッ！\n弟が憤ったのは、\nまさにその常識に対してであるのだぞ？
287 = "フハハッ！\\n弟が憤ったのは、\\nまさにその常識に対してであるのだぞ？"

# バニル
# 常識という枷が兄を殺した！\n弟は怒り、世界ごと常識を壊そうと企んだのだ！
299 = "常識という枷が兄を殺した！\\n弟は怒り、世界ごと常識を壊そうと企んだのだ！"

# めぐみん
# もしかして今って、\nもの凄くマズイ状況なんじゃないですか？
272 = "もしかして今って、\\nもの凄くマズイ状況なんじゃないですか？"

# カズマ
# ん、そんなことないだろ。
275 = "ん、そんなことないだろ。"

# めぐみん
# なんです、ずいぶんと余裕ですね。
263 = "なんです、ずいぶんと余裕ですね。"

# カズマ
# そいつが憑依してるってことは\n意識っていうか、自我があるってことだろ。
238 = "そいつが憑依してるってことは\\n意識っていうか、自我があるってことだろ。"

# カズマ
# だったら説得できるんじゃないかなってさ。
258 = "だったら説得できるんじゃないかなってさ。"

# めぐみん
# ああ、なるほど確かに！
215 = "ああ、なるほど確かに！"

# バニル
# 浅はかなり、人間よ。\n魂を定着させるというのは、\n決して容易なことではないのだぞ。
304 = "浅はかなり、人間よ。\\n魂を定着させるというのは、\\n決して容易なことではないのだぞ。"

# カズマ
# どういうことだよ。
261 = "どういうことだよ。"

# バニル
# 魂の定着にはそれなりの時間と力を要する。
357 = "魂の定着にはそれなりの時間と力を要する。"

# バニル
# それが誇り高いドラゴン族の屍なら尚更。\n本来の主である魂が、\nおいそれと体を明け渡すわけがなかろう。
249 = "それが誇り高いドラゴン族の屍なら尚更。\\n本来の主である魂が、\\nおいそれと体を明け渡すわけがなかろう。"

# カズマ
# ええと、つまり。\n今もあの体の中ではふたつの魂がやりあってて、\n体の支配権はそいつの意識下にはないと……。
227 = "ええと、つまり。\\n今もあの体の中ではふたつの魂がやりあってて、\\n体の支配権はそいつの意識下にはないと……。"

# バニル
# その通りである。
246 = "その通りである。"

# カズマ（Ｍ）
# display as カズマ
# （マジかー！！）
365 = "（マジかー！！）"

# バニル
# そしてその人間は、\nこうなることを見越していたようだな。
242 = "そしてその人間は、\\nこうなることを見越していたようだな。"

# ダクネス
# 魂をすぐには定着させられないことをか？
358 = "魂をすぐには定着させられないことをか？"

# バニル
# うむ。\nここでようやく最初の質問の答えに戻る。
224 = "うむ。\\nここでようやく最初の質問の答えに戻る。"

# カズマ
# そうだった！\nこの指輪がどうしてスカルドラゴンに\n反応してるんだよ！
239 = "そうだった！\\nこの指輪がどうしてスカルドラゴンに\\n反応してるんだよ！"

# バニル
# その指輪は道標の役目も果たしている。
244 = "その指輪は道標の役目も果たしている。"

# バニル
# 指輪が何者かを支配し力を発動させたとき、\nその術者の魂を強制的に導く役目をな。
302 = "指輪が何者かを支配し力を発動させたとき、\\nその術者の魂を強制的に導く役目をな。"

# カズマ
# え、ええと、つまり、スカルドラゴンが\nここに向かっているのは。
226 = "え、ええと、つまり、スカルドラゴンが\\nここに向かっているのは。"

# ダクネス
# カズマがここにいるから。
281 = "カズマがここにいるから。"

# カズマ（Ｍ）
# display as カズマ
# （な、なんてこったー！！）
362 = "（な、なんてこったー！！）"

# めぐみん
# だったら話は簡単じゃないですか。\n今からでも遅くありません、\nカズマを人里離れた野に放置しましょう。
257 = "だったら話は簡単じゃないですか。\\n今からでも遅くありません、\\nカズマを人里離れた野に放置しましょう。"

# カズマ
# お前に人間の血は通ってないのか！
231 = "お前に人間の血は通ってないのか！"

# アクア
# そんなことはダメよ、めぐみん！
256 = "そんなことはダメよ、めぐみん！"

# カズマ
# ア、アクア、俺を守って――
277 = "ア、アクア、俺を守って――"

# アクア
# 餌がなくなったらスカルドラゴンが\nここに来なくなっちゃうじゃない！
356 = "餌がなくなったらスカルドラゴンが\\nここに来なくなっちゃうじゃない！"

# カズマ（Ｍ）
# display as カズマ
# （餌……だと？）
368 = "（餌……だと？）"

# アクア
# そうなったら特別報酬も懸賞金も\n貰えなくなっちゃうわ！
240 = "そうなったら特別報酬も懸賞金も\\n貰えなくなっちゃうわ！"

# カズマ
# お前は俺の感動を返せよ。
232 = "お前は俺の感動を返せよ。"

