# st05a_12.txt.scn

[info]
0 = ""

[characters]
225 = "カズマ"
223 = "めぐみん"
224 = "アクア"
227 = "カズマ（Ｍ）"
229 = "ダクネス"
228 = "クリス"

[character_subs]
# 225 = "カズマ"

[script]
# lines: 62

# カズマ
# 帰ったぞー。
246 = "帰ったぞー。"

# めぐみん
# ただいま戻りました。
207 = "ただいま戻りました。"

# アクア
# あら、２人一緒に帰ってきたの？
186 = "あら、２人一緒に帰ってきたの？"

# めぐみん
# カズマが、わざわざ私達のバイト先に来て\n仕事の邪魔をしていたのです。
226 = "カズマが、わざわざ私達のバイト先に来て\\n仕事の邪魔をしていたのです。"

# カズマ
# してねーだろ！\nむしろ心配してやったってのに、\nホントひどいな！？
201 = "してねーだろ！\\nむしろ心配してやったってのに、\\nホントひどいな！？"

# めぐみん
# ところで、アクアだけなのですか？\nダクネスは？
212 = "ところで、アクアだけなのですか？\\nダクネスは？"

# アクア
# ダクネスは、夜までには戻るって話だったから、\nそろそろ帰ってくるんじゃないかしら。
230 = "ダクネスは、夜までには戻るって話だったから、\\nそろそろ帰ってくるんじゃないかしら。"

# めぐみん
# そうですか。\nじゃあ、私は先にお風呂をいただいちゃいますね。
203 = "そうですか。\\nじゃあ、私は先にお風呂をいただいちゃいますね。"

# カズマ（Ｍ）
# display as カズマ
# （あいつ、大丈夫かな？\n　雇ってくれたパーティーに\n　迷惑かけてないといいが）
283 = "（あいつ、大丈夫かな？\\n　雇ってくれたパーティーに\\n　迷惑かけてないといいが）"

# アクア
# ねえねえ、それよりも聞いてよカズマ。
216 = "ねえねえ、それよりも聞いてよカズマ。"

# カズマ
# なんだ？
215 = "なんだ？"

# アクア
# 今日はね、なんとコロッケが全部売り切れたの！\n店長から、よく頑張ったねって褒められちゃった！
234 = "今日はね、なんとコロッケが全部売り切れたの！\\n店長から、よく頑張ったねって褒められちゃった！"

# カズマ
# そっか、それは良かったな。\nじゃあ俺は風呂に入ってくるから。
204 = "そっか、それは良かったな。\\nじゃあ俺は風呂に入ってくるから。"

# めぐみん
# ちょっと待ってください。\nお風呂は私が先ですよ。
210 = "ちょっと待ってください。\\nお風呂は私が先ですよ。"

# カズマ
# 何言ってんだ。\nどう考えても俺が先だろ。
235 = "何言ってんだ。\\nどう考えても俺が先だろ。"

# めぐみん
# どうしてですか。\n納得のいく説明をしてください。
213 = "どうしてですか。\\n納得のいく説明をしてください。"

# カズマ
# 俺は肉体労働をしてきて、\n体中が汗でべとべとしてるんだ。
237 = "俺は肉体労働をしてきて、\\n体中が汗でべとべとしてるんだ。"

# めぐみん
# 私はもう帽子とマントを取ってしまっています。\nつまり私の方が入浴の準備に近い！
279 = "私はもう帽子とマントを取ってしまっています。\\nつまり私の方が入浴の準備に近い！"

# カズマ
# そんなこと知るか！\nてか、こんなところで脱ぎ出すな！\n痴女認定すんぞ！
206 = "そんなこと知るか！\\nてか、こんなところで脱ぎ出すな！\\n痴女認定すんぞ！"

# めぐみん
# べ、別に全てを脱ぐとは言ってないでしょう！\nこの帽子とマントは意外に重たいんです！\n疲れた体には苦痛なんですよ！
221 = "べ、別に全てを脱ぐとは言ってないでしょう！\\nこの帽子とマントは意外に重たいんです！\\n疲れた体には苦痛なんですよ！"

# カズマ
# だったらそんなかさばるもん着けるなよ。
208 = "だったらそんなかさばるもん着けるなよ。"

# めぐみん
# おしゃれと不自由は漏れなくセット。\nこんなこともわからないからモテないんですよ、\nカズマは。
195 = "おしゃれと不自由は漏れなくセット。\\nこんなこともわからないからモテないんですよ、\\nカズマは。"

# カズマ
# 大きなお世話だ。
240 = "大きなお世話だ。"

# めぐみん
# というわけで、お風呂は私が先にいただきます。
211 = "というわけで、お風呂は私が先にいただきます。"

# カズマ
# ふっ、めぐみん。\n悪いことは言わない、ここは俺に譲っておけ。\nそうしないと……。
220 = "ふっ、めぐみん。\\n悪いことは言わない、ここは俺に譲っておけ。\\nそうしないと……。"

# めぐみん
# ごくり、そうしないと？
198 = "ごくり、そうしないと？"

# カズマ
# 俺の汗をたっぷり含んだ、\nこの服の香ばしい匂いを堪能することになるぜ。
236 = "俺の汗をたっぷり含んだ、\\nこの服の香ばしい匂いを堪能することになるぜ。"

# ダクネス
# 望むところだ！
247 = "望むところだ！"

# カズマ
# お前は帰ったら、まずただいまだろ！
197 = "お前は帰ったら、まずただいまだろ！"

# ダクネス
# そんなことよりも\n服についた獣のような汗の臭いを\n強要されることについて詳しく！
205 = "そんなことよりも\\n服についた獣のような汗の臭いを\\n強要されることについて詳しく！"

# カズマ
# だー！　話がややこしくなるから話を盛るな！
209 = "だー！　話がややこしくなるから話を盛るな！"

# ダクネス
# 詳しくー！！
280 = "詳しくー！！"

# クリス
# あはは、相変わらず賑やかだね。
185 = "あはは、相変わらず賑やかだね。"

# カズマ
# おっ、クリスも一緒だったのか。\n今日のクエストはどうだったんだ？
196 = "おっ、クリスも一緒だったのか。\\n今日のクエストはどうだったんだ？"

# クリス
# うん、バッチリ！\nダクネスのお陰でうまくいったよ。
193 = "うん、バッチリ！\\nダクネスのお陰でうまくいったよ。"

# カズマ
# え……？
194 = "え……？"

# ダクネス
# なんだ、その意外そうな顔は。
214 = "なんだ、その意外そうな顔は。"

# カズマ
# いや、ダクネスのせいでめちゃくちゃなった、\nってのなら納得なんだが。
191 = "いや、ダクネスのせいでめちゃくちゃなった、\\nってのなら納得なんだが。"

# クリス
# さり気なくひどいね、キミ。\nでも今日は本当に、\nダクネスが大活躍だったんだよ？
200 = "さり気なくひどいね、キミ。\\nでも今日は本当に、\\nダクネスが大活躍だったんだよ？"

# ダクネス
# い、いや、そんなことは。\n大げさだぞ、クリス。
189 = "い、いや、そんなことは。\\n大げさだぞ、クリス。"

# クリス
# 大げさじゃないよ。\nダクネスがいなかったら、\nパーティーが全滅してたかもしれないよ？
241 = "大げさじゃないよ。\\nダクネスがいなかったら、\\nパーティーが全滅してたかもしれないよ？"

# カズマ
# はあっ！？\nそんなに危険なクエストだったのか？
217 = "はあっ！？\\nそんなに危険なクエストだったのか？"

# クリス
# ううん、むしろ簡単な方。\nでも想定外の強い魔物に襲われちゃって。
192 = "ううん、むしろ簡単な方。\\nでも想定外の強い魔物に襲われちゃって。"

# クリス
# まだ駆け出しのパーティーだから\nパニックになっちゃったんだけど、\nダクネスが盾になって守ってくれたの。
222 = "まだ駆け出しのパーティーだから\\nパニックになっちゃったんだけど、\\nダクネスが盾になって守ってくれたの。"

# カズマ（Ｍ）
# display as カズマ
# （いや、それはむしろ、ダクネスとしては\n　喜んで突っ込んでいっただけなんじゃ）
284 = "（いや、それはむしろ、ダクネスとしては\\n　喜んで突っ込んでいっただけなんじゃ）"

# めぐみん
# 大丈夫なのですか、ダクネス。\n怪我してませんか？
243 = "大丈夫なのですか、ダクネス。\\n怪我してませんか？"

# ダクネス
# 大丈夫だ、見ての通り問題ない。
242 = "大丈夫だ、見ての通り問題ない。"

# ダクネス
# そ、それにしてもだな！\n聞いてくれカズマ！
202 = "そ、それにしてもだな！\\n聞いてくれカズマ！"

# カズマ（Ｍ）
# display as カズマ
# （ああ、聞きたくねー）
282 = "（ああ、聞きたくねー）"

# ダクネス
# あんなに重厚なタックルを\n当ててくるモンスターに初めて出会ったぞ！\nもう一度、もう一度、味わいたい！
188 = "あんなに重厚なタックルを\\n当ててくるモンスターに初めて出会ったぞ！\\nもう一度、もう一度、味わいたい！"

# ダクネス
# 今度、あのモンスターが\n出て来そうなクエストに行こう！
233 = "今度、あのモンスターが\\n出て来そうなクエストに行こう！"

# ダクネス
# ふ、ふふ、ふふふふ……。\nあの、体の芯まで響く衝撃を\n思い出しただけで……ああっ！
219 = "ふ、ふふ、ふふふふ……。\\nあの、体の芯まで響く衝撃を\\n思い出しただけで……ああっ！"

# カズマ（Ｍ）
# display as カズマ
# （ほら、やっぱり楽しんでた）
286 = "（ほら、やっぱり楽しんでた）"

# クリス
# ああ、そうそう、報酬なんだけどね。\nダクネスの活躍の分、上乗せしてもらえたんだよ。
183 = "ああ、そうそう、報酬なんだけどね。\\nダクネスの活躍の分、上乗せしてもらえたんだよ。"

# カズマ
# マジか！
231 = "マジか！"

# クリス
# はい、報酬は渡しておくね。\nあっ、あたしの取り分はもう抜いてあるから。
218 = "はい、報酬は渡しておくね。\\nあっ、あたしの取り分はもう抜いてあるから。"

# カズマ
# ありがたく、ちょうだいします。
187 = "ありがたく、ちょうだいします。"

# カズマ（Ｍ）
# display as カズマ
# （にしても、これは初日から幸先がいい。\n　コツコツ貯める、なんて無理かと思ったが\n　意外になんとかなるかもしれないな）
285 = "（にしても、これは初日から幸先がいい。\\n　コツコツ貯める、なんて無理かと思ったが\\n　意外になんとかなるかもしれないな）"

# ダクネス
# さ、さて、私は風呂に入ってくるかな。
199 = "さ、さて、私は風呂に入ってくるかな。"

# カズマ
# ああ、ゆっくり浸かって、\n今日の疲れを取ってこいよ。
184 = "ああ、ゆっくり浸かって、\\n今日の疲れを取ってこいよ。"

# ダクネス
# いや、そうじゃなくてだな\n私にも、さっき言ってた香ばしい獣のような\n臭いとやらを。
190 = "いや、そうじゃなくてだな\\n私にも、さっき言ってた香ばしい獣のような\\n臭いとやらを。"

# カズマ
# 頼むからこれ以上疲れさせないでくれ……。
281 = "頼むからこれ以上疲れさせないでくれ……。"

