# st05a_11.txt.scn

[info]
0 = ""

[characters]
156 = "カズマ"
152 = "めぐみん"
155 = "ゆんゆん"
157 = "カズマ（Ｍ）"

[character_subs]
# 156 = "カズマ"

[script]
# lines: 62

# カズマ
# おーい、めぐみん、ゆんゆん、様子を見に――
124 = "おーい、めぐみん、ゆんゆん、様子を見に――"

# めぐみん
# お客様。\n営業妨害になりますので、出ていってください。
126 = "お客様。\\n営業妨害になりますので、出ていってください。"

# カズマ
# それが、いらっしゃいませより先に言う台詞か！
135 = "それが、いらっしゃいませより先に言う台詞か！"

# めぐみん
# いらっしゃいませ、邪魔です。
119 = "いらっしゃいませ、邪魔です。"

# ゆんゆん
# ちょっと、めぐみん！\nカズマさんも一応お客さまなんだから。
139 = "ちょっと、めぐみん！\\nカズマさんも一応お客さまなんだから。"

# カズマ（Ｍ）
# display as カズマ
# （一応……ね）
173 = "（一応……ね）"

# めぐみん
# それで何しに来たんですか。\n私とゆんゆんはまだ仕事中なんですよ。
136 = "それで何しに来たんですか。\\n私とゆんゆんはまだ仕事中なんですよ。"

# カズマ
# ただ、様子を見に来ただけなんだから、\nそう邪険にするな。
137 = "ただ、様子を見に来ただけなんだから、\\nそう邪険にするな。"

# ゆんゆん
# 忙しい時間はもう終わりましたから、\n見るものは何も無いと思いますが。
159 = "忙しい時間はもう終わりましたから、\\n見るものは何も無いと思いますが。"

# カズマ（Ｍ）
# display as カズマ
# （確かに他のウェイトレスさんも\n　暇そうにしてるな）
176 = "（確かに他のウェイトレスさんも\\n　暇そうにしてるな）"

# カズマ（Ｍ）
# display as カズマ
# （ん？　あれ？）
170 = "（ん？　あれ？）"

# カズマ（Ｍ）
# display as カズマ
# （そういや、他の店員はエプロンがカラフルなのに、\n　めぐみんとゆんゆんだけ黒だな）
162 = "（そういや、他の店員はエプロンがカラフルなのに、\\n　めぐみんとゆんゆんだけ黒だな）"

# カズマ
# なあ、めぐみん。
142 = "なあ、めぐみん。"

# めぐみん
# なんですか？　注文ですか？\nお勧めは当店特製\nスペシャルディナーセットです。
144 = "なんですか？　注文ですか？\\nお勧めは当店特製\\nスペシャルディナーセットです。"

# カズマ
# さり気なく一番高い物を勧めるなっ！
129 = "さり気なく一番高い物を勧めるなっ！"

# カズマ
# じゃなくてさ、\nお前らだけエプロンが黒いけど、なんでだ？
131 = "じゃなくてさ、\\nお前らだけエプロンが黒いけど、なんでだ？"

# めぐみん
# はっ！？\nど、どうしてそんなことを聞くんですか！
146 = "はっ！？\\nど、どうしてそんなことを聞くんですか！"

# ゆんゆん
# く、く、黒だとおかしいんですか！？
127 = "く、く、黒だとおかしいんですか！？"

# カズマ
# いや、おかしくはないけど、\n他のみんなは結構カラフルなのに、\nなんでかなって。
117 = "いや、おかしくはないけど、\\n他のみんなは結構カラフルなのに、\\nなんでかなって。"

# カズマ
# ああ、もしかして、めぐみんやゆんゆんは\n黒が好きだから黒いエプロンにしてるとか？
114 = "ああ、もしかして、めぐみんやゆんゆんは\\n黒が好きだから黒いエプロンにしてるとか？"

# めぐみん
# %fsyogen;だ、だ、だったらなんですか！？\nまさか黒が好きだから、いつも黒いのを\n身につけてるとでも思ってるんですか！
5 = "%fsyogen;だ、だ、だったらなんですか！？\\nまさか黒が好きだから、いつも黒いのを\\n身につけてるとでも思ってるんですか！"

# カズマ（Ｍ）
# display as カズマ
# （ん？　めぐみん焦りすぎだろ）
171 = "（ん？　めぐみん焦りすぎだろ）"

# カズマ（Ｍ）
# display as カズマ
# （それに、黒が好きだからいつも黒を\n　身につけている？\n　身につけているは、何を指しているんだ？）
163 = "（それに、黒が好きだからいつも黒を\\n　身につけている？\\n　身につけているは、何を指しているんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （引っかかるな。\n　証言として押さえておくか）
174 = "（引っかかるな。\\n　証言として押さえておくか）"

# ゆんゆん
# めぐみん！？
153 = "めぐみん！？"

# めぐみん
# はうっ！？
145 = "はうっ！？"

# カズマ
# おい、大丈夫か？\nなんかめっちゃ混乱してるけど、\n俺、そんなに悪いこと言ったか？
123 = "おい、大丈夫か？\\nなんかめっちゃ混乱してるけど、\\n俺、そんなに悪いこと言ったか？"

# めぐみん
# そう思うのなら黙っていてください。\n仕事の邪魔です。
133 = "そう思うのなら黙っていてください。\\n仕事の邪魔です。"

# カズマ
# お、おう。
122 = "お、おう。"

# カズマ（Ｍ）
# display as カズマ
# （なんで、あんなに慌ててるんだ？\n　別に黒が好きだからって\n　恥ずかしがる必要もないだろうに）
166 = "（なんで、あんなに慌ててるんだ？\\n　別に黒が好きだからって\\n　恥ずかしがる必要もないだろうに）"

# カズマ（Ｍ）
# display as カズマ
# （とりあえず、エプロンのことは\n　もう話題に出さないほうがよさそうだな）
165 = "（とりあえず、エプロンのことは\\n　もう話題に出さないほうがよさそうだな）"

# めぐみん
# なんですか、じっと見て。\n本当に営業妨害で追い出しますよ？
143 = "なんですか、じっと見て。\\n本当に営業妨害で追い出しますよ？"

# カズマ
# いやさぁ、なんか今日のゆんゆんに\n違和感があるんだよな。
118 = "いやさぁ、なんか今日のゆんゆんに\\n違和感があるんだよな。"

# ゆんゆん
# え？　私ですか？
121 = "え？　私ですか？"

# カズマ
# さっき気がついて、\nなんでかなーって考えてるんだけど――
128 = "さっき気がついて、\\nなんでかなーって考えてるんだけど――"

# カズマ
# あっ！　わかった！
115 = "あっ！　わかった！"

# ゆんゆん
# ひうっ！？\nな、なんですか！？
148 = "ひうっ！？\\nな、なんですか！？"

# カズマ
# リボンの色だ！\n今日は青いリボンなんだな。
158 = "リボンの色だ！\\n今日は青いリボンなんだな。"

# ゆんゆん
# %fsyogen;青いリボン！？\nど、どうしてそれをっ！？
6 = "%fsyogen;青いリボン！？\\nど、どうしてそれをっ！？"

# カズマ（Ｍ）
# display as カズマ
# （んんんー？\n　何をそんなに焦る理由があるんだ？）
169 = "（んんんー？\\n　何をそんなに焦る理由があるんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （確かにゆんゆんが青いリボンをつけてるのは\n　めずらしい）
175 = "（確かにゆんゆんが青いリボンをつけてるのは\\n　めずらしい）"

# カズマ（Ｍ）
# display as カズマ
# （でもゆんゆんは紅魔族に毒されてない\n　良識を持つ女の子だ）
164 = "（でもゆんゆんは紅魔族に毒されてない\\n　良識を持つ女の子だ）"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんみたいに、\n　黒や赤にこだわる厨二的な理由も無いはずだし、\n　好きな色のリボンをつければ……）
167 = "（めぐみんみたいに、\\n　黒や赤にこだわる厨二的な理由も無いはずだし、\\n　好きな色のリボンをつければ……）"

# カズマ（Ｍ）
# display as カズマ
# （ん？　好きな色のリボン？\n　もしかして……）
172 = "（ん？　好きな色のリボン？\\n　もしかして……）"

# カズマ（Ｍ）
# display as カズマ
# （よし、証言として押さえておこう！）
168 = "（よし、証言として押さえておこう！）"

# カズマ
# どうしてって、そりゃ、目の前にいるから。\n見ればわかるぜ？
141 = "どうしてって、そりゃ、目の前にいるから。\\n見ればわかるぜ？"

# ゆんゆん
# み、み、見ればわかるんですか！？
151 = "み、み、見ればわかるんですか！？"

# カズマ
# まあ、うん。\n一目瞭然だし？
150 = "まあ、うん。\\n一目瞭然だし？"

# ゆんゆん
# うそっ！\nまさか、み、み、見えてたんですか！？
120 = "うそっ！\\nまさか、み、み、見えてたんですか！？"

# カズマ
# は？　見えてたって、今も見えてるぞ？\n髪の毛のリボン。
147 = "は？　見えてたって、今も見えてるぞ？\\n髪の毛のリボン。"

# ゆんゆん
# ……髪の毛の？
112 = "……髪の毛の？"

# カズマ
# そう。\nいつもは赤いリボンで髪をまとめてるだろ？\nでも今日は青いんだな。
132 = "そう。\\nいつもは赤いリボンで髪をまとめてるだろ？\\nでも今日は青いんだな。"

# ゆんゆん
# あ、ああ！\nこれのことですか！
113 = "あ、ああ！\\nこれのことですか！"

# ゆんゆん
# いえ、その、別に青いリボンが好きとか\nそういうわけではなくてですね！？
116 = "いえ、その、別に青いリボンが好きとか\\nそういうわけではなくてですね！？"

# ゆんゆん
# そう！　店長の趣味なんです！\n決して私の好みじゃありませんから！
134 = "そう！　店長の趣味なんです！\\n決して私の好みじゃありませんから！"

# カズマ
# へ、へえ、そうなのか。
149 = "へ、へえ、そうなのか。"

# めぐみん
# やっぱり邪魔してばかりじゃないですか。\nもう出ていってくれませんか？
154 = "やっぱり邪魔してばかりじゃないですか。\\nもう出ていってくれませんか？"

# カズマ
# お前な。\n仮にも客に向かってひどくないか、その態度。
125 = "お前な。\\n仮にも客に向かってひどくないか、その態度。"

# めぐみん
# でしたら、邪魔した分、\nお金を使っていってください。\nお勧めは超豪華ゴールデンスイーツセットです。
140 = "でしたら、邪魔した分、\\nお金を使っていってください。\\nお勧めは超豪華ゴールデンスイーツセットです。"

# カズマ
# だから、さり気なく\n高い物を勧めるんじゃねーよ！
138 = "だから、さり気なく\\n高い物を勧めるんじゃねーよ！"

# めぐみん
# しかし、このメニュー名は……\n店長、ネーミングセンスがよくないですよね。
130 = "しかし、このメニュー名は……\\n店長、ネーミングセンスがよくないですよね。"

# カズマ（Ｍ）
# display as カズマ
# （お前が言うな、お前が）
161 = "（お前が言うな、お前が）"

