# st05a_09.txt.scn

[info]
0 = ""

[characters]
197 = "カズマ"
192 = "めぐみん"
201 = "ダクネス"
199 = "クリス"
198 = "カズマ（Ｍ）"
194 = "ゆんゆん"

[character_subs]
# 197 = "カズマ"

[script]
# lines: 45

# カズマ
# いやぁ、よかったな！\nこんなにあっさりウェイトレス採用が決まるとは！
171 = "いやぁ、よかったな！\\nこんなにあっさりウェイトレス採用が決まるとは！"

# カズマ
# めぐみん！　ゆんゆん！\n明日から頑張ってくれよ！
193 = "めぐみん！　ゆんゆん！\\n明日から頑張ってくれよ！"

# めぐみん
# い、痛いです、カズマ。\nそんなに肩を叩かないでください。
167 = "い、痛いです、カズマ。\\nそんなに肩を叩かないでください。"

# カズマ
# ああ、悪い悪い。\nついテンションが上がっちまった。
165 = "ああ、悪い悪い。\\nついテンションが上がっちまった。"

# めぐみん
# まったく、どうしてカズマのテンションが\nそこまで高くなるんですか。
191 = "まったく、どうしてカズマのテンションが\\nそこまで高くなるんですか。"

# カズマ
# いや、ほらさ、メイド喫茶も\n無駄じゃなかったんだなと思ったら\n嬉しくなっちまって。
169 = "いや、ほらさ、メイド喫茶も\\n無駄じゃなかったんだなと思ったら\\n嬉しくなっちまって。"

# ダクネス
# 本当だな。\nまさか、あれがこんなところで\n活きてくるとは思わなかった。
210 = "本当だな。\\nまさか、あれがこんなところで\\n活きてくるとは思わなかった。"

# クリス
# まさか、店主があの喫茶店の常連だったなんてね。\nちょっと不安を感じなくもないんだけど。
190 = "まさか、店主があの喫茶店の常連だったなんてね。\\nちょっと不安を感じなくもないんだけど。"

# カズマ
# まあまあ！\nこの際、気にしないで行こうぜ！
189 = "まあまあ！\\nこの際、気にしないで行こうぜ！"

# カズマ（Ｍ）
# display as カズマ
# （そう、雇い主となる食堂の店長は\n　なんと、俺達が開いたメイド喫茶を\n　よく知っていたんだ）
237 = "（そう、雇い主となる食堂の店長は\\n　なんと、俺達が開いたメイド喫茶を\\n　よく知っていたんだ）"

# カズマ（Ｍ）
# display as カズマ
# （当然、そこで働いていた\n　めぐみんやゆんゆんも覚えていて……）
239 = "（当然、そこで働いていた\\n　めぐみんやゆんゆんも覚えていて……）"

# カズマ（Ｍ）
# display as カズマ
# （あの働きぶりなら、ってことで\n　細かい面接もなしで即、採用決定！\n　しかも――）
235 = "（あの働きぶりなら、ってことで\\n　細かい面接もなしで即、採用決定！\\n　しかも――）"

# カズマ
# いいか、めぐみん、ゆんゆん。\nよく聞け？
168 = "いいか、めぐみん、ゆんゆん。\\nよく聞け？"

# カズマ
# 店長は、お前達目当ての客が\n掴めそうだってことで、\n給料よくしてくれたんだ。
209 = "店長は、お前達目当ての客が\\n掴めそうだってことで、\\n給料よくしてくれたんだ。"

# カズマ
# その期待に応えるよう、\n自分達にできる精一杯の接客をすること！\nいいな！？
179 = "その期待に応えるよう、\\n自分達にできる精一杯の接客をすること！\\nいいな！？"

# ゆんゆん
# はいっ！
187 = "はいっ！"

# めぐみん
# はあ……。
186 = "はあ……。"

# カズマ
# おい、なんだ、その気のない返事は。\n本当に頑張ってくれよ？
175 = "おい、なんだ、その気のない返事は。\\n本当に頑張ってくれよ？"

# ゆんゆん
# 大丈夫ですっ！\n私がちゃんとフォローしますから。
206 = "大丈夫ですっ！\\n私がちゃんとフォローしますから。"

# ゆんゆん
# ね、めぐみん！\n一緒に頑張ろうねっ！
185 = "ね、めぐみん！\\n一緒に頑張ろうねっ！"

# めぐみん
# そうですねー。\n頑張りましょうねー。
178 = "そうですねー。\\n頑張りましょうねー。"

# ゆんゆん
# ね、ねえ、もうちょっと\n心を込めてくれてもいいんだよ？
184 = "ね、ねえ、もうちょっと\\n心を込めてくれてもいいんだよ？"

# カズマ
# さて、次はダクネスとクリスだな。
177 = "さて、次はダクネスとクリスだな。"

# クリス
# ああ、それなんだけど。\nさっきは忘れてたんだけど、今、\nあたしを雇いたがってるパーティーがいるんだった。
163 = "ああ、それなんだけど。\\nさっきは忘れてたんだけど、今、\\nあたしを雇いたがってるパーティーがいるんだった。"

# カズマ
# 雇いたがってる？\nどういうことだ？\n誰かとパーティーを組むのか？
233 = "雇いたがってる？\\nどういうことだ？\\n誰かとパーティーを組むのか？"

# クリス
# ううん、組むわけじゃなくて\nあくまで一時的に雇われるの。
172 = "ううん、組むわけじゃなくて\\nあくまで一時的に雇われるの。"

# クリス
# んー、そうだなぁ。\n言ってみれば、傭兵みたいな感じかな。
196 = "んー、そうだなぁ。\\n言ってみれば、傭兵みたいな感じかな。"

# カズマ
# 傭兵って、なんだか物騒だな。
203 = "傭兵って、なんだか物騒だな。"

# ダクネス
# いや、特に物騒ではないぞ？\nめずらしいことでもないしな。
170 = "いや、特に物騒ではないぞ？\\nめずらしいことでもないしな。"

# クリス
# 駆け出しの冒険者が、\nそこそこのレベルの冒険者を雇って\n護衛兼手本になってもらう――
234 = "駆け出しの冒険者が、\\nそこそこのレベルの冒険者を雇って\\n護衛兼手本になってもらう――"

# クリス
# たまにあるんだよ、こういう依頼。
181 = "たまにあるんだよ、こういう依頼。"

# カズマ
# ああ、なるほどなぁ。\nそういう仕事もあるのか。
164 = "ああ、なるほどなぁ。\\nそういう仕事もあるのか。"

# クリス
# で、雇われるからには、\n当然、報酬がもらえるってわけ。
182 = "で、雇われるからには、\\n当然、報酬がもらえるってわけ。"

# クリス
# あたしも生活があるから\n全部ってわけにはいかないけど、\nいくらかはキミに渡すよ。
166 = "あたしも生活があるから\\n全部ってわけにはいかないけど、\\nいくらかはキミに渡すよ。"

# カズマ
# あ、ありがとうっ！
162 = "あ、ありがとうっ！"

# クリス
# それと、ついでにダクネスも\n雇ってもらえないか交渉してみる。
180 = "それと、ついでにダクネスも\\n雇ってもらえないか交渉してみる。"

# カズマ
# え、お前正気か？
173 = "え、お前正気か？"

# ダクネス
# おい、どういう意味だ。
174 = "おい、どういう意味だ。"

# クリス
# ま、まあ、心配する気持ちはわかるよ？
188 = "ま、まあ、心配する気持ちはわかるよ？"

# ダクネス
# クリスまで！
200 = "クリスまで！"

# クリス
# でも、このまま当てもなくバイトを探すよりも\n手っ取り早いでしょ。
183 = "でも、このまま当てもなくバイトを探すよりも\\n手っ取り早いでしょ。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、腐ってもクルセイダーだしなぁ）
238 = "（まあ、腐ってもクルセイダーだしなぁ）"

# カズマ
# おい、わかってるとは思うが、\n俺たちのパーティーの名を汚すようなことは\n絶対にするなよ。
176 = "おい、わかってるとは思うが、\\n俺たちのパーティーの名を汚すようなことは\\n絶対にするなよ。"

# ダクネス
# わかっている！　わかっているとも！\n立派に壁役を務めてくるぞ！
195 = "わかっている！　わかっているとも！\\n立派に壁役を務めてくるぞ！"

# カズマ（Ｍ）
# display as カズマ
# （あー、不安しかねー）
236 = "（あー、不安しかねー）"

