# st05a_07.txt.scn

[info]
0 = ""

[characters]
202 = "カズマ（Ｍ）"
199 = "アクア"
193 = "めぐみん"
201 = "カズマ"
204 = "クリス"
195 = "ゆんゆん"
206 = "ダクネス"

[character_subs]
# 201 = "カズマ"

[script]
# lines: 51

# カズマ（Ｍ）
# display as カズマ
# （酒場に戻ってきた俺達は、\n　クリスとゆんゆんを交えて金策の相談をしていた）
249 = "（酒場に戻ってきた俺達は、\\n　クリスとゆんゆんを交えて金策の相談をしていた）"

# カズマ（Ｍ）
# display as カズマ
# （といっても、特に良い案も出なくて、\n　ぐだぐだと話し続けた結論は――）
248 = "（といっても、特に良い案も出なくて、\\n　ぐだぐだと話し続けた結論は――）"

# アクア
# また私に造花の内職をやれっていうの！\n嫌よ、３０００万エリス溜めるまでに……\nええと、何本くらい作る必要があるのかしら？
192 = "また私に造花の内職をやれっていうの！\\n嫌よ、３０００万エリス溜めるまでに……\\nええと、何本くらい作る必要があるのかしら？"

# めぐみん
# ６００万本ですね。
250 = "６００万本ですね。"

# アクア
# ろ、ろっぴゃくぅ！？
197 = "ろ、ろっぴゃくぅ！？"

# カズマ
# 俺は地道に稼ごうって言ってるだけで、\n内職をやれなんて言ってないだろ。
213 = "俺は地道に稼ごうって言ってるだけで、\\n内職をやれなんて言ってないだろ。"

# めぐみん
# でもですね。\nそれではいつになったら呪いの解除料金が\n貯まるかわかりません。
185 = "でもですね。\\nそれではいつになったら呪いの解除料金が\\n貯まるかわかりません。"

# クリス
# めぐみんの言い分もわかるけどさ、\nハイリスク、ハイリターンばかり狙った結果が\n今なわけだし。
194 = "めぐみんの言い分もわかるけどさ、\\nハイリスク、ハイリターンばかり狙った結果が\\n今なわけだし。"

# ゆんゆん
# でも、ローリスク、ローリターンというのは\n気が遠くなる話です。
184 = "でも、ローリスク、ローリターンというのは\\n気が遠くなる話です。"

# ダクネス
# とりあえず、みんなで堅実に働いて\n足固めをしようじゃ無いか。
186 = "とりあえず、みんなで堅実に働いて\\n足固めをしようじゃ無いか。"

# めぐみん
# そして資金が貯まったら、\n勝負に打って出ると？
178 = "そして資金が貯まったら、\\n勝負に打って出ると？"

# ダクネス
# それはそのときの状況によるだろうな。
179 = "それはそのときの状況によるだろうな。"

# めぐみん
# わかりました。\n納得はしかねますが、今は衣食を満たすのも\n怪しい状況ですしね。
198 = "わかりました。\\n納得はしかねますが、今は衣食を満たすのも\\n怪しい状況ですしね。"

# ダクネス
# アクアもそれでいいか？
200 = "アクアもそれでいいか？"

# アクア
# 嫌……。
217 = "嫌……。"

# カズマ
# 他に方法もないだろ？　ああん？
212 = "他に方法もないだろ？　ああん？"

# アクア
# うう、わかったわよ……。
170 = "うう、わかったわよ……。"

# カズマ
# よし、決まりだな！\nじゃあ今度は、それぞれがどんな方法で\n稼ぐことができるか考えようぜ。
196 = "よし、決まりだな！\\nじゃあ今度は、それぞれがどんな方法で\\n稼ぐことができるか考えようぜ。"

# クリス
# 一番わかりやすいのはやっぱりクエストかな？
209 = "一番わかりやすいのはやっぱりクエストかな？"

# ダクネス
# 今の時期なら、\nジャイアントトード狩りのクエストが常にあるぞ！
211 = "今の時期なら、\\nジャイアントトード狩りのクエストが常にあるぞ！"

# アクア
# あわわわわわわ。
166 = "あわわわわわわ。"

# めぐみん
# あうううううう。
165 = "あうううううう。"

# カズマ
# ダクネスやめてやれ。\nこの２人は一生取れないトラウマを抱えてるんだ。
207 = "ダクネスやめてやれ。\\nこの２人は一生取れないトラウマを抱えてるんだ。"

# ダクネス
# うぅ、私も粘液まみれになってみたいのに。
168 = "うぅ、私も粘液まみれになってみたいのに。"

# アクア
# ねんっ！
190 = "ねんっ！"

# めぐみん
# えきっ！
174 = "えきっ！"

# カズマ
# クエストは受けられるときに受けるとして。\nあとはやっぱり街でのバイトだな。\n商店街とか、工事現場とか。
203 = "クエストは受けられるときに受けるとして。\\nあとはやっぱり街でのバイトだな。\\n商店街とか、工事現場とか。"

# クリス
# 商店街を探せばいくらでもあると思うから、\nあたしもやってみるよ。
215 = "商店街を探せばいくらでもあると思うから、\\nあたしもやってみるよ。"

# カズマ
# うう……すまん……。
169 = "うう……すまん……。"

# めぐみん
# では、ゆんゆんも手伝うということで\nいいのですよね？
182 = "では、ゆんゆんも手伝うということで\\nいいのですよね？"

# ゆんゆん
# ええっ！？\nわ、私はそこまで考えてなかったんだけど。
173 = "ええっ！？\\nわ、私はそこまで考えてなかったんだけど。"

# めぐみん
# はい？\nここまできて断るなんて、\nそんな空気の読めないことをする気ですか？
191 = "はい？\\nここまできて断るなんて、\\nそんな空気の読めないことをする気ですか？"

# ゆんゆん
# う、ううんっ！　手伝うよ！\n決まってるじゃない！
167 = "う、ううんっ！　手伝うよ！\\n決まってるじゃない！"

# めぐみん
# ですよね。\nさすが我が友ゆんゆんです。
180 = "ですよね。\\nさすが我が友ゆんゆんです。"

# カズマ（Ｍ）
# display as カズマ
# （……ゆんゆん、それでいいのか）
246 = "（……ゆんゆん、それでいいのか）"

# クリス
# じゃあ、誰がどんなバイトができそうか\n考えてみようか。
177 = "じゃあ、誰がどんなバイトができそうか\\n考えてみようか。"

# カズマ
# あ、俺は前にやってた工事現場をあたってみるよ。\n顔も利くしさ。
164 = "あ、俺は前にやってた工事現場をあたってみるよ。\\n顔も利くしさ。"

# めぐみん
# 大丈夫なんですか？　体力的に。
216 = "大丈夫なんですか？　体力的に。"

# カズマ
# ダメだけどやるしかないだろ。
208 = "ダメだけどやるしかないだろ。"

# ダクネス
# では、私も自分の長所を活かした\n体力仕事がいいだろうか。
183 = "では、私も自分の長所を活かした\\n体力仕事がいいだろうか。"

# ダクネス
# しかし、工事現場では刺激が少なそうだな。
176 = "しかし、工事現場では刺激が少なそうだな。"

# カズマ
# なんでバイトに刺激を求めるんだ。
188 = "なんでバイトに刺激を求めるんだ。"

# ゆんゆん
# ね、ねえ、めぐみんは\nどんなバイトをするつもりなの？\nよ、よければ一緒に……。
189 = "ね、ねえ、めぐみんは\\nどんなバイトをするつもりなの？\\nよ、よければ一緒に……。"

# めぐみん
# うーん、バイトですか。\n我にふさわしい職が果たして\nこの街にあるのか……。
172 = "うーん、バイトですか。\\n我にふさわしい職が果たして\\nこの街にあるのか……。"

# ゆんゆん
# 聞いてない！？
245 = "聞いてない！？"

# めぐみん
# え？　なんですか、ゆんゆん。
175 = "え？　なんですか、ゆんゆん。"

# ゆんゆん
# な、なんでもないよ！
187 = "な、なんでもないよ！"

# カズマ
# クリスはどうするんだ？\nあてはあるのか？
205 = "クリスはどうするんだ？\\nあてはあるのか？"

# クリス
# うーん、なくはないかな。\nでもちゃんと聞いてみないと、\nなんとも言えない。
171 = "うーん、なくはないかな。\\nでもちゃんと聞いてみないと、\\nなんとも言えない。"

# ダクネス
# では、せっかくだ。\n今から街に行って探してみないか？
181 = "では、せっかくだ。\\n今から街に行って探してみないか？"

# カズマ（Ｍ）
# display as カズマ
# （うん、今はとにかく行動あるのみか）
247 = "（うん、今はとにかく行動あるのみか）"

