# st05c_03.txt.scn

[info]
0 = ""

[characters]
103 = "アクア"
106 = "カズマ"
110 = "スカルドラゴン"
105 = "ウィズ"
99 = "めぐみん"
101 = "ゆんゆん"
108 = "クリス"
112 = "ダクネス"
107 = "カズマ（Ｍ）"

[character_subs]
121 = "？？？"
# 106 = "カズマ"

[script]
# lines: 26

# アクア
# やったの？　やったのよね？
100 = "やったの？　やったのよね？"

# カズマ
# わからん……。
102 = "わからん……。"

# スカルドラゴン
# グルル……グルルル………。
109 = "グルル……グルルル………。"

# カズマ
# うおおい！\nアクア、浄化魔法！\n早く、早くーーーーー！！
87 = "うおおい！\\nアクア、浄化魔法！\\n早く、早くーーーーー！！"

# アクア
# ああ、もう、こうなったらやけよ！
86 = "ああ、もう、こうなったらやけよ！"

# アクア
# セイクリッド――
111 = "セイクリッド――"

# スカルドラゴン
# display as ？？？
# アンデッドの王か……。
104 = "アンデッドの王か……。"

# カズマ
# は？
96 = "は？"

# アクア
# へ？
97 = "へ？"

# スカルドラゴン
# display as ？？？
# それに貴様は、ただの人ではないな。
93 = "それに貴様は、ただの人ではないな。"

# アクア
# は？
# 96 = "は？"

# カズマ
# へ？
# 97 = "へ？"

# アクア
# ええと、誰？
89 = "ええと、誰？"

# スカルドラゴン
# display as ？？？
# 我だ。
115 = "我だ。"

# カズマ
# ワレダ？
113 = "ワレダ？"

# スカルドラゴン
# display as ？？？
# 我だ。
# 115 = "我だ。"

# カズマ
# うーんと……まさかとは思うのですが\nスカルドラゴンさん？
88 = "うーんと……まさかとは思うのですが\\nスカルドラゴンさん？"

# スカルドラゴン
# そうだ。
90 = "そうだ。"

# ウィズ
# はぁはぁ、どうやら魂が定着したようですね。
94 = "はぁはぁ、どうやら魂が定着したようですね。"

# カズマ
# そうなの！？
92 = "そうなの！？"

# めぐみん
# はあ、さすがに死を覚悟しましたよ。
95 = "はあ、さすがに死を覚悟しましたよ。"

# ゆんゆん
# 私も……。
119 = "私も……。"

# クリス
# まだ油断はできないよ。
98 = "まだ油断はできないよ。"

# ダクネス
# そうだぞ、このドラゴン。\nいや魂の主は、この世界を蹂躙するのが\n目的なんだからな。
91 = "そうだぞ、このドラゴン。\\nいや魂の主は、この世界を蹂躙するのが\\n目的なんだからな。"

# スカルドラゴン
# 汝らと話し合いをしたい。\n正直、寝起きにこれ以上爆裂魔法や\n浄化魔法ををぶつけられるのは堪えるのだ。
116 = "汝らと話し合いをしたい。\\n正直、寝起きにこれ以上爆裂魔法や\\n浄化魔法ををぶつけられるのは堪えるのだ。"

# カズマ（Ｍ）
# display as カズマ
# （話し合い？\n　おいおい、なんか斜め上の展開に\n　なってきたぞ？）
120 = "（話し合い？\\n　おいおい、なんか斜め上の展開に\\n　なってきたぞ？）"

