# st05c_06.txt.scn

[info]
0 = ""

[characters]
205 = "めぐみん"
215 = "カズマ"
208 = "ゆんゆん"
221 = "ダクネス"
214 = "ウィズ"
218 = "カズマ（Ｍ）"
213 = "アクア"
219 = "クリス"

[character_subs]
260 = "？？？"
# 215 = "カズマ"

[script]
# lines: 41

# めぐみん
# display as ？？？
# カズマ！　カズマ！\nしっかりしてください、カズマッ！
217 = "カズマ！　カズマ！\\nしっかりしてください、カズマッ！"

# カズマ
# ん、んん……。
212 = "ん、んん……。"

# ゆんゆん
# だ、大丈夫ですか？\nちゃんと生き返ってますか？
193 = "だ、大丈夫ですか？\\nちゃんと生き返ってますか？"

# カズマ
# お、おう。\n生きてるけど……。
185 = "お、おう。\\n生きてるけど……。"

# ゆんゆん
# よ、よかったです！
209 = "よ、よかったです！"

# ダクネス
# すまん、その……\n少々やり過ぎてしまったようだ。
189 = "すまん、その……\\n少々やり過ぎてしまったようだ。"

# ゆんゆん
# ごめんなさいっ！\n本当にごめんなさい！
188 = "ごめんなさいっ！\\n本当にごめんなさい！"

# めぐみん
# すみません……。
190 = "すみません……。"

# ウィズ
# 私も……すみません。
258 = "私も……すみません。"

# カズマ（Ｍ）
# display as カズマ
# （な、なにが起こったんだ？\n　知りたいような知りたくないような）
259 = "（な、なにが起こったんだ？\\n　知りたいような知りたくないような）"

# アクア
# えー？　このくらい当然じゃない？\nねえ、カズマ？
184 = "えー？　このくらい当然じゃない？\\nねえ、カズマ？"

# カズマ
# 俺に同意を求めるんじゃねーよ！\nつか、お前は盗られてないだろ？\nだから言う権利もない！
223 = "俺に同意を求めるんじゃねーよ！\\nつか、お前は盗られてないだろ？\\nだから言う権利もない！"

# ウィズ
# えっ！？
183 = "えっ！？"

# めぐみん
# もしかしてカズマ、知ってるんですか？\nその、私達が……盗られているって。
206 = "もしかしてカズマ、知ってるんですか？\\nその、私達が……盗られているって。"

# カズマ
# ああ、伊達に盗み続けてないからな！\n態度でわかる！
179 = "ああ、伊達に盗み続けてないからな！\\n態度でわかる！"

# クリス
# なんでそこで堂々としてるの！？
197 = "なんでそこで堂々としてるの！？"

# ダクネス
# これはもう、\nそれがカズマだとしか言いようがないな。
187 = "これはもう、\\nそれがカズマだとしか言いようがないな。"

# アクア
# ねえ、それじゃ、\n今回はいつもの裁判はなし？
199 = "ねえ、それじゃ、\\n今回はいつもの裁判はなし？"

# カズマ
# いいや！\nパンツ裁判はやるぞ！
181 = "いいや！\\nパンツ裁判はやるぞ！"

# クリス
# やるの！？\nだって、もう誰が盗られたのかは\nわかってるんでしょ？
207 = "やるの！？\\nだって、もう誰が盗られたのかは\\nわかってるんでしょ？"

# カズマ
# わかってるさ。\nだが、しかし！
210 = "わかってるさ。\\nだが、しかし！"

# カズマ
# それで満足してしまっては紳士失格！\n間違ったパンツを返してしまうなんて、\n真の紳士とは言えないのだ！
192 = "それで満足してしまっては紳士失格！\\n間違ったパンツを返してしまうなんて、\\n真の紳士とは言えないのだ！"

# カズマ
# つまり今回は、誰が盗まれているのかを\nつきとめるのではなく――
195 = "つまり今回は、誰が盗まれているのかを\\nつきとめるのではなく――"

# カズマ
# どのパンツが誰の物であるか！\nこの真実を明らかにする裁判を開くのだ！！
196 = "どのパンツが誰の物であるか！\\nこの真実を明らかにする裁判を開くのだ！！"

# クリス
# はああああっ！？
202 = "はああああっ！？"

# ゆんゆん
# そ、そんな……！
191 = "そ、そんな……！"

# めぐみん
# 撃っていいですか？\n撃っていいですよね？\nじゃあ撃ちますね？
229 = "撃っていいですか？\\n撃っていいですよね？\\nじゃあ撃ちますね？"

# カズマ
# なんで撃つんだよ！！\n俺は真面目に言ってるんだぞ！？
198 = "なんで撃つんだよ！！\\n俺は真面目に言ってるんだぞ！？"

# カズマ
# お前だって、他の誰かのパンツを\n渡されたら困るだろ！？
186 = "お前だって、他の誰かのパンツを\\n渡されたら困るだろ！？"

# めぐみん
# ……撃ちます。
177 = "……撃ちます。"

# ゆんゆん
# 待って、めぐみん！\nここで撃ったら、みんなが巻きこまれちゃう！
228 = "待って、めぐみん！\\nここで撃ったら、みんなが巻きこまれちゃう！"

# アクア
# はあ……。\nこうなったカズマはもう、\n私達の言うことなんて聞かないでしょ。
201 = "はあ……。\\nこうなったカズマはもう、\\n私達の言うことなんて聞かないでしょ。"

# アクア
# みんな、覚悟を決めて裁判をやりましょう。\n大丈夫よ、まさか誰の物かまで当てるなんて\nできないでしょうし。
204 = "みんな、覚悟を決めて裁判をやりましょう。\\n大丈夫よ、まさか誰の物かまで当てるなんて\\nできないでしょうし。"

# クリス
# はあ……。\nいいよね、アクアさんは。\n他人事なんだから。
200 = "はあ……。\\nいいよね、アクアさんは。\\n他人事なんだから。"

# ウィズ
# あの、ですが、せめて\n街に戻ってからにしませんか？
180 = "あの、ですが、せめて\\n街に戻ってからにしませんか？"

# ウィズ
# みなさん、何事かとこっちを見てますし。\nここでやるのはさすがに……。
203 = "みなさん、何事かとこっちを見てますし。\\nここでやるのはさすがに……。"

# クリス
# っていうかさ、\nドラゴンは浄化されたからもう大丈夫って\nみんなに説明するのが先じゃない？
194 = "っていうかさ、\\nドラゴンは浄化されたからもう大丈夫って\\nみんなに説明するのが先じゃない？"

# カズマ
# ああ、そっか。\nじゃあ、キース達に説明してから\n改めてパンツ裁判開始だ！
178 = "ああ、そっか。\\nじゃあ、キース達に説明してから\\n改めてパンツ裁判開始だ！"

# ゆんゆん
# うう、スカルドラゴンなんて大物を\nみんなで倒したのに、こんな終わり方って……。\n私が思っていた冒険と違う……。
182 = "うう、スカルドラゴンなんて大物を\\nみんなで倒したのに、こんな終わり方って……。\\n私が思っていた冒険と違う……。"

# カズマ
# わかるぜ、ゆんゆん。\n俺もよく思ってるからな、\n思い描いていた生活と違うって。
211 = "わかるぜ、ゆんゆん。\\n俺もよく思ってるからな、\\n思い描いていた生活と違うって。"

# ゆんゆん
# カズマさんに言われたくないですっ！
216 = "カズマさんに言われたくないですっ！"

[selections]
220 = "コーヒーブレイク"
