# st05a_05.txt.scn

[info]
0 = ""

[characters]
218 = "カズマ"
217 = "ウィズ"
223 = "バニル"
207 = "めぐみん"
221 = "カズマ（Ｍ）"
222 = "ダクネス"
216 = "アクア"

[character_subs]
# 218 = "カズマ"

[script]
# lines: 71

# カズマ
# よう、ウィズ。
211 = "よう、ウィズ。"

# ウィズ
# あ……！\nか、カズマさん、いらっしゃいませ。
178 = "あ……！\\nか、カズマさん、いらっしゃいませ。"

# カズマ
# バニルはいるかな。\n話があってきたんだけど。
226 = "バニルはいるかな。\\n話があってきたんだけど。"

# ウィズ
# バニルさんでしたら――
225 = "バニルさんでしたら――"

# バニル
# 我輩に何か用事か、\n５枚の下着を手に目覚めし小僧よ。
238 = "我輩に何か用事か、\\n５枚の下着を手に目覚めし小僧よ。"

# ウィズ
# え？　５枚もですか！？
187 = "え？　５枚もですか！？"

# カズマ
# ああ、先月よりも１枚増えてた。
181 = "ああ、先月よりも１枚増えてた。"

# ウィズ
# なんというか、大変ですね。
206 = "なんというか、大変ですね。"

# めぐみん
# 大変なのはカズマではなく周りですよ。
233 = "大変なのはカズマではなく周りですよ。"

# バニル
# さて、それで？\n我輩に話とは？
190 = "さて、それで？\\n我輩に話とは？"

# カズマ
# わかってんだろ、どうせ。\n顔に出てるんだよ。
213 = "わかってんだろ、どうせ。\\n顔に出てるんだよ。"

# バニル
# 顔？　この仮面の下の顔がわかるのか？\nほほう、やるではないか小僧。
285 = "顔？　この仮面の下の顔がわかるのか？\\nほほう、やるではないか小僧。"

# カズマ
# 物の例えだ。いちいち揚げ足を取らないでくれ。
240 = "物の例えだ。いちいち揚げ足を取らないでくれ。"

# バニル
# それで話とは？\nじっくりと腰を据えて聞いてやろうではないか。
194 = "それで話とは？\\nじっくりと腰を据えて聞いてやろうではないか。"

# カズマ（Ｍ）
# display as カズマ
# （くそっ、こいつ絶対にわかってんな……）
291 = "（くそっ、こいつ絶対にわかってんな……）"

# ダクネス
# カズマ。\n話にくいのなら、私から言おうか？
220 = "カズマ。\\n話にくいのなら、私から言おうか？"

# カズマ
# いや、いいよ。\nこれは俺の問題なんだからな。
183 = "いや、いいよ。\\nこれは俺の問題なんだからな。"

# カズマ
# バニル。\n単刀直入に言う。\n３０００万エリス、少しまけてくれないか？
224 = "バニル。\\n単刀直入に言う。\\n３０００万エリス、少しまけてくれないか？"

# バニル
# フフフフ、ハーハハハハハハ！\nこれは驚いた！　いや、実に驚いた！\nまさか、そんな交渉を持ちかけられるとは！
228 = "フフフフ、ハーハハハハハハ！\\nこれは驚いた！　いや、実に驚いた！\\nまさか、そんな交渉を持ちかけられるとは！"

# バニル
# 答えは決まっている。\n我輩は、まける気は一切ない。\nどんな事情があろうとも、である。
283 = "答えは決まっている。\\n我輩は、まける気は一切ない。\\nどんな事情があろうとも、である。"

# カズマ（Ｍ）
# display as カズマ
# （まあ、そうくるよな。\n　ここまでは予想通り、\n　ここから先、どう説得するかだが……）
296 = "（まあ、そうくるよな。\\n　ここまでは予想通り、\\n　ここから先、どう説得するかだが……）"

# バニル
# 考えるだけ無駄なこと。\nそれくらいはお前もわかっているだろう。
284 = "考えるだけ無駄なこと。\\nそれくらいはお前もわかっているだろう。"

# カズマ
# そ、それはまあ、そうなんだけど……。
192 = "そ、それはまあ、そうなんだけど……。"

# バニル
# それに、すぐにでも３０００万エリスを\n持ってくると言ったのはそちらであるが？
195 = "それに、すぐにでも３０００万エリスを\\n持ってくると言ったのはそちらであるが？"

# カズマ（Ｍ）
# display as カズマ
# （うっ……）
288 = "（うっ……）"

# バニル
# ああ、なるほど！\n口から出任せだったということか！
180 = "ああ、なるほど！\\n口から出任せだったということか！"

# バニル
# やれやれ、どこぞの女神の従者は、\n甘い言葉で人を騙す詐欺師でしかなかったとは、\n残念、きわめて残念であるぞ。
210 = "やれやれ、どこぞの女神の従者は、\\n甘い言葉で人を騙す詐欺師でしかなかったとは、\\n残念、きわめて残念であるぞ。"

# カズマ
# だから従者じゃ――
199 = "だから従者じゃ――"

# アクア
# ！！
286 = "！！"

# カズマ
# って、アクア？
200 = "って、アクア？"

# バニル
# ん？　我輩に何か言いたそうな顔をしているな。
215 = "ん？　我輩に何か言いたそうな顔をしているな。"

# アクア
# 従者を小馬鹿にされて黙っていられるほど、\n女神アクアは寛大じゃないの。
237 = "従者を小馬鹿にされて黙っていられるほど、\\n女神アクアは寛大じゃないの。"

# カズマ（Ｍ）
# display as カズマ
# （お、俺のために怒ってくれてる？\n　あのアクアが？）
289 = "（お、俺のために怒ってくれてる？\\n　あのアクアが？）"

# アクア
# %fsyogen;確かにカズマは、\n変態でヘタレでクズでヒキニートな\n駄目人間だけど――
18 = "%fsyogen;確かにカズマは、\\n変態でヘタレでクズでヒキニートな\\n駄目人間だけど――"

# カズマ
# おい。
188 = "おい。"

# アクア
# でも、決して、人を欺くようなことを平気で\nするような――
204 = "でも、決して、人を欺くようなことを平気で\\nするような――"

# めぐみん
# 人間ですよ。
230 = "人間ですよ。"

# カズマ
# なっ！？
205 = "なっ！？"

# アクア
# た、確かにそうね。
198 = "た、確かにそうね。"

# カズマ
# そんなことしねーよ！\nてか、この駄女神！\nそこまで噛みついたんなら最後までやり抜けよ！
196 = "そんなことしねーよ！\\nてか、この駄女神！\\nそこまで噛みついたんなら最後までやり抜けよ！"

# アクア
# い、嫌よ。\nいくら悪魔相手でも嘘をついてまで勝ちたいなんて\n思わないわ。
182 = "い、嫌よ。\\nいくら悪魔相手でも嘘をついてまで勝ちたいなんて\\n思わないわ。"

# カズマ（Ｍ）
# display as カズマ
# （こいつ、変な所で女神のプライド見せやがって！）
292 = "（こいつ、変な所で女神のプライド見せやがって！）"

# カズマ（Ｍ）
# display as カズマ
# （それに、未遂に終わったとはいえ\n　俺をかばおうとするなんて怪しい！）
295 = "（それに、未遂に終わったとはいえ\\n　俺をかばおうとするなんて怪しい！）"

# カズマ（Ｍ）
# display as カズマ
# （根拠はなんも無いけど、\n　証言として押さえておく！）
300 = "（根拠はなんも無いけど、\\n　証言として押さえておく！）"

# ウィズ
# あ、あの？\nバニルさん、私からもいいですか？
179 = "あ、あの？\\nバニルさん、私からもいいですか？"

# バニル
# んん？\nなんであるか、店主よ。
214 = "んん？\\nなんであるか、店主よ。"

# ウィズ
# やはり３０００万エリスは\nやりすぎだと思うんです。\n少し、オマケしてあげてはどうでしょう？
209 = "やはり３０００万エリスは\\nやりすぎだと思うんです。\\n少し、オマケしてあげてはどうでしょう？"

# カズマ（Ｍ）
# display as カズマ
# （おお！\n　ナイスアシスト、ウィズ！）
290 = "（おお！\\n　ナイスアシスト、ウィズ！）"

# バニル
# いやいや、むしろ破格であるぞ？\nこれほどの呪いを打ち破るなど、\n我輩にしかできないのだからな。
185 = "いやいや、むしろ破格であるぞ？\\nこれほどの呪いを打ち破るなど、\\n我輩にしかできないのだからな。"

# ウィズ
# ですが、カズマさん達は\nまだ冒険者としては駆け出しで、\nお金を儲けるのも大変なんです。
201 = "ですが、カズマさん達は\\nまだ冒険者としては駆け出しで、\\nお金を儲けるのも大変なんです。"

# ウィズ
# もちろん、とっても努力されているんですよ？
208 = "もちろん、とっても努力されているんですよ？"

# ウィズ
# 私もお手伝いして\n苦労している姿を見てきましたから、\nよく知っているんです。
282 = "私もお手伝いして\\n苦労している姿を見てきましたから、\\nよく知っているんです。"

# バニル
# おやおや、店主はいつの間に\nそこまで小僧に入れ込んでいたのであるかな？\nそれとも別の理由でも？
189 = "おやおや、店主はいつの間に\\nそこまで小僧に入れ込んでいたのであるかな？\\nそれとも別の理由でも？"

# ウィズ
# ええっ！？\nい、いえ、別の理由なんてないですよ！？
186 = "ええっ！？\\nい、いえ、別の理由なんてないですよ！？"

# バニル
# そうであるか。\nいやいや、店主も大変であるな。\nこうも続けてでは、落ち着く暇もあるまい。
193 = "そうであるか。\\nいやいや、店主も大変であるな。\\nこうも続けてでは、落ち着く暇もあるまい。"

# ウィズ
# た、大変だなんて、そんな……。
197 = "た、大変だなんて、そんな……。"

# カズマ（Ｍ）
# display as カズマ
# （ああ、なんとなくわかってしまった。\n　今、俺が持っている５枚のパンツ……\n　そのうちの１枚はウィズのなんだな）
287 = "（ああ、なんとなくわかってしまった。\\n　今、俺が持っている５枚のパンツ……\\n　そのうちの１枚はウィズのなんだな）"

# カズマ（Ｍ）
# display as カズマ
# （本当にすまん……ウィズ……）
299 = "（本当にすまん……ウィズ……）"

# アクア
# カズマ、やっぱりこの悪魔に交渉なんて無駄よ。\nここは３０００万エリスを叩きつけて\n私達の実力を見せてやるしかないわ。
219 = "カズマ、やっぱりこの悪魔に交渉なんて無駄よ。\\nここは３０００万エリスを叩きつけて\\n私達の実力を見せてやるしかないわ。"

# カズマ（Ｍ）
# display as カズマ
# （それが無理だから交渉に来たんだろ！？\n　目的を忘れてんじゃねーよ！）
294 = "（それが無理だから交渉に来たんだろ！？\\n　目的を忘れてんじゃねーよ！）"

# バニル
# フハハハハ！\n実に頼もしい主人であるな、小僧よ！
227 = "フハハハハ！\\n実に頼もしい主人であるな、小僧よ！"

# カズマ（Ｍ）
# display as カズマ
# （まったく頼もしくねーし！　主人でもねーし！）
297 = "（まったく頼もしくねーし！　主人でもねーし！）"

# カズマ（Ｍ）
# display as カズマ
# （わかって言ってると思うと\n　ホント腹立つしやりにくいな！）
298 = "（わかって言ってると思うと\\n　ホント腹立つしやりにくいな！）"

# バニル
# では、これで話は終わりだ。
202 = "では、これで話は終わりだ。"

# バニル
# 契約はすでに成立しているものである。\nよって、金額は動かない。\n３０００万エリス、待っているぞ。
234 = "契約はすでに成立しているものである。\\nよって、金額は動かない。\\n３０００万エリス、待っているぞ。"

# カズマ
# わかったよ。
212 = "わかったよ。"

# バニル
# では、我輩は仕事のがあるのでな。\nさらばだ、小僧よ。
203 = "では、我輩は仕事のがあるのでな。\\nさらばだ、小僧よ。"

# ウィズ
# すみません、カズマさん。\nお力になれなくて。
191 = "すみません、カズマさん。\\nお力になれなくて。"

# カズマ
# いや、ウィズが謝ることないって。\nそもそも、ダメ元のつもりだったし。
184 = "いや、ウィズが謝ることないって。\\nそもそも、ダメ元のつもりだったし。"

# カズマ（Ｍ）
# display as カズマ
# （謝りたいのはこっちだぜ。\n　いままで散々、迷惑をかけてきたのに\n　俺の力になろうとしてくるなんて）
301 = "（謝りたいのはこっちだぜ。\\n　いままで散々、迷惑をかけてきたのに\\n　俺の力になろうとしてくるなんて）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、どうするかな。\n　これってもう……完全に手詰まりじゃないか？）
293 = "（しかし、どうするかな。\\n　これってもう……完全に手詰まりじゃないか？）"

