# st05c_04.txt.scn

[info]
0 = ""

[characters]
269 = "カズマ（Ｍ）"
272 = "スカルドラゴン"
271 = "クリス"
259 = "めぐみん"
260 = "ゆんゆん"
266 = "カズマ"
264 = "アクア"
265 = "ウィズ"
274 = "ダクネス"

[character_subs]
# 266 = "カズマ"

[script]
# lines: 121

# カズマ（Ｍ）
# display as カズマ
# （その後、他の冒険者に頼んで、\n　スカルドラゴンとの話し合いは\n　俺達だけでやらせてもらうことにした）
329 = "（その後、他の冒険者に頼んで、\\n　スカルドラゴンとの話し合いは\\n　俺達だけでやらせてもらうことにした）"

# カズマ（Ｍ）
# display as カズマ
# （なにしろ、指輪のことは伏せたままだからな。\n　下手に聞かれるわけにもいかない）
331 = "（なにしろ、指輪のことは伏せたままだからな。\\n　下手に聞かれるわけにもいかない）"

# カズマ（Ｍ）
# display as カズマ
# （みんなには少し離れたところに待機してもらい、\n　俺達は改めて、スカルドラゴンと\n　対峙することになったわけだが……）
333 = "（みんなには少し離れたところに待機してもらい、\\n　俺達は改めて、スカルドラゴンと\\n　対峙することになったわけだが……）"

# スカルドラゴン
# しかし、まさか我の過去を知る者が\nこの時代にいようとは、驚いたな。
220 = "しかし、まさか我の過去を知る者が\\nこの時代にいようとは、驚いたな。"

# クリス
# ってことは、この人、じゃなくてドラゴンは\n例の下着泥棒の弟で間違いないんだ。
237 = "ってことは、この人、じゃなくてドラゴンは\\n例の下着泥棒の弟で間違いないんだ。"

# めぐみん
# そう考えると……\nなんだか、強そうなのに\n全然そう思えなくなってきますね。
225 = "そう考えると……\\nなんだか、強そうなのに\\n全然そう思えなくなってきますね。"

# ゆんゆん
# だ、ダメだよ、めぐみん。\nそういうことを言っちゃ。
231 = "だ、ダメだよ、めぐみん。\\nそういうことを言っちゃ。"

# カズマ
# で？　あんたは兄のためにこの指輪を作ったり、\n自分の魂をドラゴンの屍に憑依せたりしたわけか。
242 = "で？　あんたは兄のためにこの指輪を作ったり、\\n自分の魂をドラゴンの屍に憑依せたりしたわけか。"

# スカルドラゴン
# そうだ！　我は兄の無念を晴らしたかった！\n兄のささやかな幸せを奪い取った者共に、\n思い知らせたかったのだ！
224 = "そうだ！　我は兄の無念を晴らしたかった！\\n兄のささやかな幸せを奪い取った者共に、\\n思い知らせたかったのだ！"

# めぐみん
# ……でもやってたのは下着泥棒なんですよね。
188 = "……でもやってたのは下着泥棒なんですよね。"

# ゆんゆん
# め、めぐみんっ！
258 = "め、めぐみんっ！"

# カズマ
# あのさ、あんたが兄貴の無念を晴らしたいって\n思う気持ちはわかるよ。
196 = "あのさ、あんたが兄貴の無念を晴らしたいって\\n思う気持ちはわかるよ。"

# アクア
# え？　わかるの？\n相手は下着泥棒なのよ？
210 = "え？　わかるの？\\n相手は下着泥棒なのよ？"

# めぐみん
# 変態同士で響き合うものがあるんでしょうか？
292 = "変態同士で響き合うものがあるんでしょうか？"

# カズマ
# …………。
185 = "…………。"

# カズマ
# おい、お前ら。\n頼むからちょっと黙っててくれないか？\nスカルドラゴンが怒り出したらどうするんだよ。
211 = "おい、お前ら。\\n頼むからちょっと黙っててくれないか？\\nスカルドラゴンが怒り出したらどうするんだよ。"

# ウィズ
# せっかく向こうから\n話し合いを提案してくださったのですから、\nここはみなさん、慎重に行きましょう？
222 = "せっかく向こうから\\n話し合いを提案してくださったのですから、\\nここはみなさん、慎重に行きましょう？"

# スカルドラゴン
# どうした？\n何をこそこそ話している？
244 = "どうした？\\n何をこそこそ話している？"

# カズマ
# い、いや！　なんでもない！\nそれよりも――
200 = "い、いや！　なんでもない！\\nそれよりも――"

# カズマ
# あんたはやっぱり、\nこの世界を蹂躙するつもりなのか？
199 = "あんたはやっぱり、\\nこの世界を蹂躙するつもりなのか？"

# スカルドラゴン
# …………。
# 185 = "…………。"

# カズマ
# あんたのことを聞いてから色々考えたんだけど、\nやっぱりそれってちょっと違うと思うんだよな。
197 = "あんたのことを聞いてから色々考えたんだけど、\\nやっぱりそれってちょっと違うと思うんだよな。"

# カズマ
# あんたの兄ちゃんがそんなことを望んでるとは\n思えないし、何よりも――
198 = "あんたの兄ちゃんがそんなことを望んでるとは\\n思えないし、何よりも――"

# カズマ
# 人類が死滅したら、\nお前の兄ちゃんが大好きだったパンツも\nなくなるだろ。
282 = "人類が死滅したら、\\nお前の兄ちゃんが大好きだったパンツも\\nなくなるだろ。"

# めぐみん
# 真剣な顔で何を言ってるんですか、この変態は。
319 = "真剣な顔で何を言ってるんですか、この変態は。"

# クリス
# でも、今の状況では正しいことを\n言ってるんだよね。
240 = "でも、今の状況では正しいことを\\n言ってるんだよね。"

# カズマ
# でも、あんたの気持ちもわかるんだ。
239 = "でも、あんたの気持ちもわかるんだ。"

# カズマ
# 世間から否定されるのって本当にしんどいもんな。
280 = "世間から否定されるのって本当にしんどいもんな。"

# ダクネス
# カズマ？
270 = "カズマ？"

# スカルドラゴン
# 確かに汝の言うとおりだ。\nこの世界を蹂躙したところで、\n兄への慰めにはならない。
321 = "確かに汝の言うとおりだ。\\nこの世界を蹂躙したところで、\\n兄への慰めにはならない。"

# スカルドラゴン
# だが兄の魂は、\n今だこの世界に未練を残しさまよい続けている。
233 = "だが兄の魂は、\\n今だこの世界に未練を残しさまよい続けている。"

# カズマ
# ええと、魂を天に戻すには――
208 = "ええと、魂を天に戻すには――"

# ウィズ
# 思い残したこと、念願の達成が必要ですね。
296 = "思い残したこと、念願の達成が必要ですね。"

# カズマ
# その念願ってなんだったんだ？
227 = "その念願ってなんだったんだ？"

# スカルドラゴン
# 兄は自分の地位を守るために、\n放棄せざるを得なかった。
286 = "兄は自分の地位を守るために、\\n放棄せざるを得なかった。"

# カズマ
# 何を？
283 = "何を？"

# スカルドラゴン
# パンツを、だ。
276 = "パンツを、だ。"

# カズマ
# …………。
# 185 = "…………。"

# スカルドラゴン
# 兄はそれを無念に涙で顔を濡らしていた。\nそして死んでいった。
285 = "兄はそれを無念に涙で顔を濡らしていた。\\nそして死んでいった。"

# スカルドラゴン
# 我は、そんな兄を成仏させてやりたい。
297 = "我は、そんな兄を成仏させてやりたい。"

# カズマ
# でもさ、俺がどんなにパンツを盗んだところで\n兄ちゃんの無念は晴らせないだろう。
241 = "でもさ、俺がどんなにパンツを盗んだところで\\n兄ちゃんの無念は晴らせないだろう。"

# スカルドラゴン
# 汝が持つ物を我に託してはくれないだろうか。
300 = "汝が持つ物を我に託してはくれないだろうか。"

# カズマ
# それって、まさか……これのこと？
228 = "それって、まさか……これのこと？"

# めぐみん
# なっ！？
246 = "なっ！？"

# ゆんゆん
# ひっ！？
249 = "ひっ！？"

# クリス
# ちょぉ！！
235 = "ちょぉ！！"

# スカルドラゴン
# うむ、それだ。\nそれこそが、兄への\nなによりの慰めになる物なのだ。
206 = "うむ、それだ。\\nそれこそが、兄への\\nなによりの慰めになる物なのだ。"

# カズマ
# ああ、やっぱりか。
191 = "ああ、やっぱりか。"

# ウィズ
# ま、待ってください！\nまさか、これを渡す気なのですか？
256 = "ま、待ってください！\\nまさか、これを渡す気なのですか？"

# カズマ
# いや、渡せば大人しく帰ってくれそうだし、\nそれがいいんじゃね？
203 = "いや、渡せば大人しく帰ってくれそうだし、\\nそれがいいんじゃね？"

# ウィズ
# 確かに、正面切って戦うよりは\nいいかもしれませんが……で、でも……！
320 = "確かに、正面切って戦うよりは\\nいいかもしれませんが……で、でも……！"

# スカルドラゴン
# では、どうする。\nどれを我に差し出そうというのだ？
238 = "では、どうする。\\nどれを我に差し出そうというのだ？"

# めぐみん
# 勝手に話が進んでますよ！？
288 = "勝手に話が進んでますよ！？"

# カズマ
# よし、じゃあ……。
263 = "よし、じゃあ……。"

# カズマ
# この、ピンクのひらひらパンツを持っていけ！
215 = "この、ピンクのひらひらパンツを持っていけ！"

# ダクネス
# くうううっ！？
213 = "くうううっ！？"

# スカルドラゴン
# ふむ。\nこれは、なかなかに上等な生地を使った一品。\n気品すら感じさせる作りだな。
254 = "ふむ。\\nこれは、なかなかに上等な生地を使った一品。\\n気品すら感じさせる作りだな。"

# スカルドラゴン
# 高貴なる身分であった兄にふさわしい。\nいいだろう、受け取ろう。
323 = "高貴なる身分であった兄にふさわしい。\\nいいだろう、受け取ろう。"

# カズマ
# この、ヒモのパンツはどうだ？
214 = "この、ヒモのパンツはどうだ？"

# クリス
# ちょっ！？\nそ、それは……！
236 = "ちょっ！？\\nそ、それは……！"

# スカルドラゴン
# これはこれは、なんと大胆な。\n持ち主の顔を見てみたいものだな。
217 = "これはこれは、なんと大胆な。\\n持ち主の顔を見てみたいものだな。"

# クリス
# うう……。
205 = "うう……。"

# スカルドラゴン
# だが、悪くはない。\nこのようなデザイン、兄には良い刺激になろう。\n喜んで受け取ろう。
232 = "だが、悪くはない。\\nこのようなデザイン、兄には良い刺激になろう。\\n喜んで受け取ろう。"

# カズマ
# この緑のパンツはどうだ？
216 = "この緑のパンツはどうだ？"

# ウィズ
# ああっ……！
194 = "ああっ……！"

# スカルドラゴン
# ほほう。\nなんとも清楚な雰囲気を漂わせているな。\n控えめだが、色からさり気ない主張を感じる。
255 = "ほほう。\\nなんとも清楚な雰囲気を漂わせているな。\\n控えめだが、色からさり気ない主張を感じる。"

# ウィズ
# はうう……。
248 = "はうう……。"

# スカルドラゴン
# これは兄が好んでいた雰囲気だ。\n実にいいぞ。
219 = "これは兄が好んでいた雰囲気だ。\\n実にいいぞ。"

# スカルドラゴン
# 黒のパンツ！\nこれを持っていけ！
326 = "黒のパンツ！\\nこれを持っていけ！"

# めぐみん
# うう……。
# 205 = "うう……。"

# スカルドラゴン
# ふむ、黒か。\n選ばれ抜かれた艶のある光沢といい、\nどことなく、こだわりを感じさせるな。
253 = "ふむ、黒か。\\n選ばれ抜かれた艶のある光沢といい、\\nどことなく、こだわりを感じさせるな。"

# スカルドラゴン
# 兄は黒も好んでいた。\nよかろう、受け取ろう。
287 = "兄は黒も好んでいた。\\nよかろう、受け取ろう。"

# カズマ
# これはどうだ？
218 = "これはどうだ？"

# スカルドラゴン
# むむ？\n黒に……青いリボンがついているのか。
257 = "むむ？\\n黒に……青いリボンがついているのか。"

# ゆんゆん
# あああああ……！
193 = "あああああ……！"

# スカルドラゴン
# しとやかさの中に忍ばせた愛らしさ、\n微笑ましさとのギャップもよい。\nいいだろう、受け取ろう。
221 = "しとやかさの中に忍ばせた愛らしさ、\\n微笑ましさとのギャップもよい。\\nいいだろう、受け取ろう。"

# カズマ
# どうだ、これで満足か？
245 = "どうだ、これで満足か？"

# スカルドラゴン
# いいや、まだだ。\n我が望みは未だ満たされていない。\n続けよう。
201 = "いいや、まだだ。\\n我が望みは未だ満たされていない。\\n続けよう。"

# スカルドラゴン
# ……ふむ。\nこれだけあれば充分か。
189 = "……ふむ。\\nこれだけあれば充分か。"

# カズマ（Ｍ）
# display as カズマ
# （充分もなにも、これ以上\n　出せるもんがこっちにはねーし！\n　まさか５枚とも持っていかれると思わなかった！）
337 = "（充分もなにも、これ以上\\n　出せるもんがこっちにはねーし！\\n　まさか５枚とも持っていかれると思わなかった！）"

# ダクネス
# ふ、ふふふふ……。\nまさかこの場で、このような辱めを\n受けることになろうとは……！
250 = "ふ、ふふふふ……。\\nまさかこの場で、このような辱めを\\n受けることになろうとは……！"

# ゆんゆん
# 本当に渡しちゃうなんて……。
299 = "本当に渡しちゃうなんて……。"

# クリス
# ……こんなことで、あのドラゴンが\n納得するとは思えないんだけど、大丈夫なの？
186 = "……こんなことで、あのドラゴンが\\n納得するとは思えないんだけど、大丈夫なの？"

# カズマ（Ｍ）
# display as カズマ
# （そうだよな、パンツを渡すから\n　暴れないでくれって頼んだはいいけど、\n　それを守ってくれるかどうかはわからない）
328 = "（そうだよな、パンツを渡すから\\n　暴れないでくれって頼んだはいいけど、\\n　それを守ってくれるかどうかはわからない）"

# カズマ（Ｍ）
# display as カズマ
# （だいたい世界の危機とパンツ５枚って\n　どう考えても釣り合わないだろ……）
330 = "（だいたい世界の危機とパンツ５枚って\\n　どう考えても釣り合わないだろ……）"

# スカルドラゴン
# ……さて。\nそこのアークプリーストよ。\n我に浄化魔法をかけるがいい。
187 = "……さて。\\nそこのアークプリーストよ。\\n我に浄化魔法をかけるがいい。"

# カズマ
# えっ！？\n浄化魔法って……いいのか？
209 = "えっ！？\\n浄化魔法って……いいのか？"

# スカルドラゴン
# 我はこの通り、望む物を手に入れた。\nその上で、あのような清浄なる光に\n浄化されるというのなら、是非もない。
298 = "我はこの通り、望む物を手に入れた。\\nその上で、あのような清浄なる光に\\n浄化されるというのなら、是非もない。"

# アクア
# あなたがそれを望むのなら、\n喜んで浄化してあげましょう。
195 = "あなたがそれを望むのなら、\\n喜んで浄化してあげましょう。"

# アクア
# そして、女神アクアの名において、\nあなたの罪を許します。
226 = "そして、女神アクアの名において、\\nあなたの罪を許します。"

# スカルドラゴン
# 女神？\nまさか……汝が？
293 = "女神？\\nまさか……汝が？"

# スカルドラゴン
# いや、いい。\n汝が何者であろうが、その言葉を嬉しく思う。\nありがとう。
202 = "いや、いい。\\n汝が何者であろうが、その言葉を嬉しく思う。\\nありがとう。"

# アクア
# セイクリッド・ターンアンデット。
273 = "セイクリッド・ターンアンデット。"

# めぐみん
# ちょ、ちょっと待ってください！\n浄化って、渡した物ごとですか！？
234 = "ちょ、ちょっと待ってください！\\n浄化って、渡した物ごとですか！？"

# クリス
# パ、パンツ返してー！！
275 = "パ、パンツ返してー！！"

# ウィズ
# 困りますっ！\n返してください！
291 = "困りますっ！\\n返してください！"

# カズマ（Ｍ）
# display as カズマ
# （アクアの奴、\n　あなたの罪を許しましょう、とか言ったけど\n　あのドラゴンの罪ってなんだ？）
334 = "（アクアの奴、\\n　あなたの罪を許しましょう、とか言ったけど\\n　あのドラゴンの罪ってなんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （兄貴のために指輪を作って、\n　自分の魂をドラゴンの屍に憑依させただけだよな）
336 = "（兄貴のために指輪を作って、\\n　自分の魂をドラゴンの屍に憑依させただけだよな）"

# カズマ（Ｍ）
# display as カズマ
# （あの駄女神、格好つけて適当なこと\n　言っただけじゃないか？）
327 = "（あの駄女神、格好つけて適当なこと\\n　言っただけじゃないか？）"

# ゆんゆん
# う、うそ……。\n消えちゃいましたよ！？
204 = "う、うそ……。\\n消えちゃいましたよ！？"

# カズマ
# よかったじゃないか。\n無事に浄化されたってことだろ？
262 = "よかったじゃないか。\\n無事に浄化されたってことだろ？"

# ゆんゆん
# そうじゃないですっ！！\nわ、私の、その、し、し、し……。
223 = "そうじゃないですっ！！\\nわ、私の、その、し、し、し……。"

# クリス
# パンツを持ったままだったんだけど！？
277 = "パンツを持ったままだったんだけど！？"

# カズマ
# ああ、天国の兄の元に\n持っていったのかもしれないなぁ。
192 = "ああ、天国の兄の元に\\n持っていったのかもしれないなぁ。"

# ウィズ
# そんな……！
229 = "そんな……！"

# カズマ
# おおっ！\n指輪が割れて……取れた！？
212 = "おおっ！\\n指輪が割れて……取れた！？"

# アクア
# 作った本人が浄化されたことで、\n指輪も役目を終えたのね。
284 = "作った本人が浄化されたことで、\\n指輪も役目を終えたのね。"

# カズマ
# はああ～、やっと呪いから解放されたのか！\nここまで本当に長かったぜ。
247 = "はああ～、やっと呪いから解放されたのか！\\nここまで本当に長かったぜ。"

# カズマ（Ｍ）
# display as カズマ
# （にしても、あのドラゴン、こんな\n　ねちっこい呪いの指輪を作ったやつにしては\n　意外に潔い最期だったな）
332 = "（にしても、あのドラゴン、こんな\\n　ねちっこい呪いの指輪を作ったやつにしては\\n　意外に潔い最期だったな）"

# カズマ（Ｍ）
# display as カズマ
# （今頃、天国で兄貴と仲良く\n　パンツを鑑賞してるのかなぁ。\n　うんうん、よかったよかった）
335 = "（今頃、天国で兄貴と仲良く\\n　パンツを鑑賞してるのかなぁ。\\n　うんうん、よかったよかった）"

# めぐみん
# カズマ。
267 = "カズマ。"

# カズマ
# どうした？
243 = "どうした？"

# ウィズ
# カズマさん。
268 = "カズマさん。"

# カズマ
# うん、だからどうしたんだよ。
207 = "うん、だからどうしたんだよ。"

# ゆんゆん
# カズマさん。
# 268 = "カズマさん。"

# カズマ
# ゆんゆん？
261 = "ゆんゆん？"

# クリス
# カズマ。
# 267 = "カズマ。"

# カズマ
# だ、だから、なんだよ。
230 = "だ、だから、なんだよ。"

# めぐみん
# ふふふ。
251 = "ふふふ。"

# ゆんゆん
# ふふふふ。
252 = "ふふふふ。"

# カズマ
# あ、ええと、もしかして怒ってる？\nパンツを勝手に渡しちゃったこと――
190 = "あ、ええと、もしかして怒ってる？\\nパンツを勝手に渡しちゃったこと――"

[selections]
279 = "ピンクのひらひらパンツ"
278 = "ヒモのパンツ"
322 = "緑のパンツ"
325 = "黒のパンツ"
324 = "黒に青いリボンついたパンツ"
