# st05a_03.txt.scn

[info]
0 = ""

[characters]
263 = "カズマ"
267 = "カズマ（Ｍ）"
272 = "ダクネス"
262 = "アクア"
258 = "めぐみん"
275 = "ルナ"

[character_subs]
# 263 = "カズマ"

[script]
# lines: 69

# カズマ
# うーん……。
222 = "うーん……。"

# カズマ（Ｍ）
# display as カズマ
# （ギルドにやってきた俺達は、\n　さっそく張り出されたクエストを\n　チェックしているのだが――）
335 = "（ギルドにやってきた俺達は、\\n　さっそく張り出されたクエストを\\n　チェックしているのだが――）"

# ダクネス
# カズマ、カズマ！
264 = "カズマ、カズマ！"

# カズマ
# カズマですが？
266 = "カズマですが？"

# ダクネス
# はぐれリザード退治の募集、まだ残っているぞ！\nこれはもう、引き受けるべきという\nエリス様のおぼし召しだろう！
254 = "はぐれリザード退治の募集、まだ残っているぞ！\\nこれはもう、引き受けるべきという\\nエリス様のおぼし召しだろう！"

# カズマ
# 却下だと言っとろーが！\n残ってるってことは、引き受けたがるパーティーが\nいねーってことだぞ！？
282 = "却下だと言っとろーが！\\n残ってるってことは、引き受けたがるパーティーが\\nいねーってことだぞ！？"

# アクア
# でもこれ、報酬すっごくいいわよ？
248 = "でもこれ、報酬すっごくいいわよ？"

# カズマ
# やらねーからな！
259 = "やらねーからな！"

# めぐみん
# カズマ、カズマ！
# 264 = "カズマ、カズマ！"

# カズマ
# はいカズマだよ？
253 = "はいカズマだよ？"

# めぐみん
# これはどうですか？\n一撃熊の討伐！
232 = "これはどうですか？\\n一撃熊の討伐！"

# カズマ
# それ、前にも聞いたぞ。\n明らかに首を撫でられただけで死にそうな\nモンスターには関わる気はない。
242 = "それ、前にも聞いたぞ。\\n明らかに首を撫でられただけで死にそうな\\nモンスターには関わる気はない。"

# めぐみん
# そ、そこをなんとかっ！\n我が爆裂魔法との勝負の機会を、ぜひ！
236 = "そ、そこをなんとかっ！\\n我が爆裂魔法との勝負の機会を、ぜひ！"

# カズマ
# 却下だっ！\nそんな勝負をしてる余裕なんてねーよ！
281 = "却下だっ！\\nそんな勝負をしてる余裕なんてねーよ！"

# アクア
# あっ！\nカズマ、カズマ！
216 = "あっ！\\nカズマ、カズマ！"

# カズマ
# カズマです。
265 = "カズマです。"

# アクア
# これなんてどう？
231 = "これなんてどう？"

# カズマ
# マンティコアが森の中に異常発生しています。\n至急、討伐をお願いします――
274 = "マンティコアが森の中に異常発生しています。\\n至急、討伐をお願いします――"

# カズマ
# お前はバカか！\nこんなクエスト、俺達の手に負えるわけねーだろ！
227 = "お前はバカか！\\nこんなクエスト、俺達の手に負えるわけねーだろ！"

# アクア
# でも、報酬がすごいわよ？\n１００万エリスですって。
247 = "でも、報酬がすごいわよ？\\n１００万エリスですって。"

# カズマ
# 俺は１００万エリスで命を差し出す気はない。\nやるんならお前１人でやれ。
278 = "俺は１００万エリスで命を差し出す気はない。\\nやるんならお前１人でやれ。"

# ダクネス
# おお！\nカズマ、カズマ！
226 = "おお！\\nカズマ、カズマ！"

# カズマ
# はいはいカズマだよ。
252 = "はいはいカズマだよ。"

# ダクネス
# グリフォンの親子が\n廃墟に住み着いて困っています。\n討伐をお願いします――
271 = "グリフォンの親子が\\n廃墟に住み着いて困っています。\\n討伐をお願いします――"

# ダクネス
# わ、私もグリフォンを相手にしたことはないが、\nその逞しい下半身から繰り出される一撃を\n想像しただけで……！
260 = "わ、私もグリフォンを相手にしたことはないが、\\nその逞しい下半身から繰り出される一撃を\\n想像しただけで……！"

# ダクネス
# このクエストを引き受けよう！\n報酬もいいし、こんなチャンスはめったにないぞ！
229 = "このクエストを引き受けよう！\\n報酬もいいし、こんなチャンスはめったにないぞ！"

# カズマ
# 俺達の実力を考えろ！\nグリフォンなんて相手にしたら\n命がいくつあっても足りねーよ！
280 = "俺達の実力を考えろ！\\nグリフォンなんて相手にしたら\\n命がいくつあっても足りねーよ！"

# ダクネス
# しかし、多少は無理をしなければ\n３０００万エリスという金額には届かないぞ？
233 = "しかし、多少は無理をしなければ\\n３０００万エリスという金額には届かないぞ？"

# カズマ
# こういうのは無理じゃなくて無謀って言うんだ。\nよーく覚えておけ。
228 = "こういうのは無理じゃなくて無謀って言うんだ。\\nよーく覚えておけ。"

# カズマ
# まあ焦るなよ。\n確かに報酬はいいけどさ、\n成功しないと何ももらえないんだぞ？
256 = "まあ焦るなよ。\\n確かに報酬はいいけどさ、\\n成功しないと何ももらえないんだぞ？"

# ダクネス
# むう、確かに。\n前回のように赤字だけは避けなくてはならないな。
257 = "むう、確かに。\\n前回のように赤字だけは避けなくてはならないな。"

# カズマ
# だろ？\nここは落ち着いて、少なくても\n確実に収入のあるクエストを選ぼう。
245 = "だろ？\\nここは落ち着いて、少なくても\\n確実に収入のあるクエストを選ぼう。"

# カズマ
# 挑戦したいが……。
288 = "挑戦したいが……。"

# ダクネス
# そうか！\nカズマもグリフォンに興味があるんだな！？
238 = "そうか！\\nカズマもグリフォンに興味があるんだな！？"

# アクア
# え？　そうだったの？\nカズマもそっち系の趣味に目覚めたの？
225 = "え？　そうだったの？\\nカズマもそっち系の趣味に目覚めたの？"

# カズマ
# 違うって。\nダクネスみたいな意味じゃなくて、\n見てみたいんだよ、グリフォンを。
331 = "違うって。\\nダクネスみたいな意味じゃなくて、\\n見てみたいんだよ、グリフォンを。"

# カズマ（Ｍ）
# display as カズマ
# （そんなファンタジーな生き物、\n　元の世界じゃ絶対に拝めなかったもんな）
334 = "（そんなファンタジーな生き物、\\n　元の世界じゃ絶対に拝めなかったもんな）"

# ダクネス
# では、決まりだな！\nこのクエストを引き受けよう！
246 = "では、決まりだな！\\nこのクエストを引き受けよう！"

# カズマ
# いや、引き受けないから。
220 = "いや、引き受けないから。"

# ダクネス
# なっ！　なぜだ！？
250 = "なっ！　なぜだ！？"

# カズマ
# 見るのと退治するのじゃ話が違うだろ。\n俺達の実力じゃ、返り討ちにあって終わりだ。\nだから却下な。
330 = "見るのと退治するのじゃ話が違うだろ。\\n俺達の実力じゃ、返り討ちにあって終わりだ。\\nだから却下な。"

# めぐみん
# ダメですね。\nこれっていうクエストはありませんよ。
273 = "ダメですね。\\nこれっていうクエストはありませんよ。"

# カズマ
# クエストもダメとなると本当に手がないぞ。
270 = "クエストもダメとなると本当に手がないぞ。"

# ルナ
# あら？\nみなさん、今日もクエストをお探しですか？
217 = "あら？\\nみなさん、今日もクエストをお探しですか？"

# カズマ
# あ、どうも。\nええ、そうなんですけど、いいものがなくて。
215 = "あ、どうも。\\nええ、そうなんですけど、いいものがなくて。"

# アクア
# ねえねえ、また紹介してもらえない？\n前みたいな、一攫千金を狙えるような\nクエストを。
251 = "ねえねえ、また紹介してもらえない？\\n前みたいな、一攫千金を狙えるような\\nクエストを。"

# ルナ
# ええと、それは……\nさすがにこれ以上の優遇はできません。
223 = "ええと、それは……\\nさすがにこれ以上の優遇はできません。"

# アクア
# えー！　なんでよ！\nこの街をベルディアやデストロイヤーから\n守ったのは私なのよ！？
224 = "えー！　なんでよ！\\nこの街をベルディアやデストロイヤーから\\n守ったのは私なのよ！？"

# カズマ（Ｍ）
# display as カズマ
# （お前だけじゃなくて、\n　他のみんなの力もあってだろ……）
333 = "（お前だけじゃなくて、\\n　他のみんなの力もあってだろ……）"

# ルナ
# そう言われましても。\n前回が特別だったんです。
241 = "そう言われましても。\\n前回が特別だったんです。"

# ルナ
# ギルドは、すべての冒険者に\n平等であるべき組織ですので。
269 = "ギルドは、すべての冒険者に\\n平等であるべき組織ですので。"

# ダクネス
# そうだな。\n前回の件が特例中の特例だったわけか。
239 = "そうだな。\\n前回の件が特例中の特例だったわけか。"

# カズマ
# そういうことだ。\nアクア、これ以上、お姉さんを困らせるな。
237 = "そういうことだ。\\nアクア、これ以上、お姉さんを困らせるな。"

# アクア
# わかったわよ。
261 = "わかったわよ。"

# ルナ
# それでは、私はこれで。\n何かありましたら、声をかけてください。
243 = "それでは、私はこれで。\\n何かありましたら、声をかけてください。"

# めぐみん
# ギルドから紹介もしてもらえないとなると、\n手を出せそうなのは\n本当に低レベルのクエストしかありませんね。
268 = "ギルドから紹介もしてもらえないとなると、\\n手を出せそうなのは\\n本当に低レベルのクエストしかありませんね。"

# ダクネス
# これでは、３０００万エリスが貯まるまで\n何年かかるかわからないぞ。
230 = "これでは、３０００万エリスが貯まるまで\\n何年かかるかわからないぞ。"

# アクア
# あーあ、なんかもう八方ふさがりねぇ。\n困ったわ。
218 = "あーあ、なんかもう八方ふさがりねぇ。\\n困ったわ。"

# カズマ（Ｍ）
# display as カズマ
# （全然、困ってるように聞こえないんだが？\n　状況わかってるのか、こいつ）
336 = "（全然、困ってるように聞こえないんだが？\\n　状況わかってるのか、こいつ）"

# アクア
# とりあえず腹ごしらえしない？\nお腹が空いてちゃ、いい考えも出てこないわよ。
249 = "とりあえず腹ごしらえしない？\\nお腹が空いてちゃ、いい考えも出てこないわよ。"

# アクア
# すみませーん！\nこっちにメニューと、\nあと、とりあえずシュワシュワお願いしまーす。
235 = "すみませーん！\\nこっちにメニューと、\\nあと、とりあえずシュワシュワお願いしまーす。"

# カズマ
# 金を貯めようって話してるそばから浪費か！
332 = "金を貯めようって話してるそばから浪費か！"

# アクア
# だって、朝から喋り通しで喉渇いたんだもん。
244 = "だって、朝から喋り通しで喉渇いたんだもん。"

# カズマ
# 水を飲め、水を！
289 = "水を飲め、水を！"

# アクア
# いいじゃない。\nいまさらシュワシュワ１杯分節約したって\n何も変わんないわ。
219 = "いいじゃない。\\nいまさらシュワシュワ１杯分節約したって\\n何も変わんないわ。"

# カズマ
# 低レベルのクエストしかできないんだぞ？\nシュワシュワ１杯分でも節約していかないと、\n貯まるもんも貯まらねーんだよ！
277 = "低レベルのクエストしかできないんだぞ？\\nシュワシュワ１杯分でも節約していかないと、\\n貯まるもんも貯まらねーんだよ！"

# ダクネス
# いや、日々の食費や\n武器防具の維持費も考えると、\n低レベルのクエストで稼ぐのは現実的ではないな。
221 = "いや、日々の食費や\\n武器防具の維持費も考えると、\\n低レベルのクエストで稼ぐのは現実的ではないな。"

# めぐみん
# そうですね。\n３０００万なんて、一生かけても無理そうです。
240 = "そうですね。\\n３０００万なんて、一生かけても無理そうです。"

# カズマ
# じゃあ……どうすればいいんだよ。
234 = "じゃあ……どうすればいいんだよ。"

[selections]
279 = "俺達の実力を考えろ！"
255 = "まあ焦るなよ"
287 = "挑戦したいが……"
