# st05b_04.txt.scn

[info]
0 = ""

[characters]
214 = "カズマ"
228 = "ルナ"
217 = "カズマ（Ｍ）"
218 = "キース"
224 = "ダスト"
240 = "戦士風の男冒険者"
280 = "魔術師風の男冒険者"
208 = "めぐみん"
223 = "ダクネス"
220 = "クリス"
209 = "ゆんゆん"
211 = "アクア"
212 = "ウィズ"

[character_subs]
# 214 = "カズマ"
239 = "戦士冒険者"
279 = "魔術師冒険者"

[script]
# lines: 59

# カズマ
# すみません、戻りました。
191 = "すみません、戻りました。"

# ルナ
# サトウさん！\nどうでしたか？\n指輪のことはわかりましたか？
221 = "サトウさん！\\nどうでしたか？\\n指輪のことはわかりましたか？"

# カズマ
# え、えーっと、それは……。
184 = "え、えーっと、それは……。"

# カズマ（Ｍ）
# display as カズマ
# （この指輪が原因だってのは……\n　黙っていたほうがいいか）
286 = "（この指輪が原因だってのは……\\n　黙っていたほうがいいか）"

# カズマ
# 指輪のことはわからなかったんですけど、\nドラゴンの正体とか、その辺について\n話をさせてもらっていいですか？
241 = "指輪のことはわからなかったんですけど、\\nドラゴンの正体とか、その辺について\\n話をさせてもらっていいですか？"

# ルナ
# そんな……。
198 = "そんな……。"

# キース
# 人間の魂がドラゴンにねぇ。\nにわかには信じられない話だな。
230 = "人間の魂がドラゴンにねぇ。\\nにわかには信じられない話だな。"

# ダスト
# それも、下着泥棒の邪魔をされた\n恨みを晴らすためにって……\nバカとなんとかは紙一重ってやつか。
197 = "それも、下着泥棒の邪魔をされた\\n恨みを晴らすためにって……\\nバカとなんとかは紙一重ってやつか。"

# キース
# 有能な変態は迷惑にしかならないな。
243 = "有能な変態は迷惑にしかならないな。"

# ダスト
# まったくだ。
206 = "まったくだ。"

# ルナ
# サトウカズマさん。\n本当に、自分達だけで\n解決するとおっしゃるのですか？
222 = "サトウカズマさん。\\n本当に、自分達だけで\\n解決するとおっしゃるのですか？"

# カズマ
# はい、あのドラゴンを目覚めさせた責任は\nちゃんと取ります。\nていうか、取らせてください。
201 = "はい、あのドラゴンを目覚めさせた責任は\\nちゃんと取ります。\\nていうか、取らせてください。"

# キース
# いや、ダメだ。
181 = "いや、ダメだ。"

# カズマ
# はっ！？\nお前、なにを言ってんだよ。
202 = "はっ！？\\nお前、なにを言ってんだよ。"

# キース
# カズマ。\nお前達がいない間に、こっちでも\n色々を話を進めていたんだ。
215 = "カズマ。\\nお前達がいない間に、こっちでも\\n色々を話を進めていたんだ。"

# ダスト
# いいか？\nお前がこの街を守りたいと思うように\n俺達だって、この街を守りたいんだよ。
180 = "いいか？\\nお前がこの街を守りたいと思うように\\n俺達だって、この街を守りたいんだよ。"

# キース
# この街には世話になってるからな。
189 = "この街には世話になってるからな。"

# ダスト
# 今まで安くお世話になってきた分の恩返し、\nここでもやらなきゃ男が廃るってもんだろ！
231 = "今まで安くお世話になってきた分の恩返し、\\nここでもやらなきゃ男が廃るってもんだろ！"

# キース
# その通りだ。\nだから俺達もやる。\nここにいる全員で、この街を守るんだ！
195 = "その通りだ。\\nだから俺達もやる。\\nここにいる全員で、この街を守るんだ！"

# カズマ
# キース、ダスト……。
219 = "キース、ダスト……。"

# カズマ（Ｍ）
# display as カズマ
# （お前ら、いいこと言ってるけど\n　ポケットからはみ出してるぞ、\n　サキュバスの店のチケットが！）
284 = "（お前ら、いいこと言ってるけど\\n　ポケットからはみ出してるぞ、\\n　サキュバスの店のチケットが！）"

# カズマ（Ｍ）
# display as カズマ
# （つまり、あの店のために\n　冒険者が一致団結したってことか）
288 = "（つまり、あの店のために\\n　冒険者が一致団結したってことか）"

# カズマ（Ｍ）
# display as カズマ
# （まあ、そうと知らずに\n　雰囲気に流されたって人が\n　ほとんどなんだろうけど……でも……）
290 = "（まあ、そうと知らずに\\n　雰囲気に流されたって人が\\n　ほとんどなんだろうけど……でも……）"

# カズマ
# 気持ちは嬉しい。\nでも、この件は俺達で解決すべきなんだ。
244 = "気持ちは嬉しい。\\nでも、この件は俺達で解決すべきなんだ。"

# キース
# その言葉、そっくりそのまま返すぜ。
194 = "その言葉、そっくりそのまま返すぜ。"

# キース
# 責任を取ろうって態度は立派だけどな、\nそれって、人の好意をはねのけてまで\nやるべきことか？
278 = "責任を取ろうって態度は立派だけどな、\\nそれって、人の好意をはねのけてまで\\nやるべきことか？"

# カズマ（Ｍ）
# display as カズマ
# （……格好いいこと言ってるけど、\n　サキュバスの店のチケットが見えてるからな？）
282 = "（……格好いいこと言ってるけど、\\n　サキュバスの店のチケットが見えてるからな？）"

# ルナ
# カズマさん。\nギルドとしても、みなさんだけに\nお任せするわけには行きません。
216 = "カズマさん。\\nギルドとしても、みなさんだけに\\nお任せするわけには行きません。"

# ルナ
# こう言ってしまってはなんですが、\n街を守るためには、みなさんだけでは\n不安がありますし……。
188 = "こう言ってしまってはなんですが、\\n街を守るためには、みなさんだけでは\\n不安がありますし……。"

# ルナ
# それに、ここにいる冒険者のみなさんは\nすでに緊急クエストを\n受けてくださっていますので。
196 = "それに、ここにいる冒険者のみなさんは\\nすでに緊急クエストを\\n受けてくださっていますので。"

# キース
# そうだぜ。\n報酬を全部持っていこうなんて思わないことだな。
192 = "そうだぜ。\\n報酬を全部持っていこうなんて思わないことだな。"

# ダスト
# これは街のためのクエストだ！\nカズマ達だけに任せてなんておけないよな！
190 = "これは街のためのクエストだ！\\nカズマ達だけに任せてなんておけないよな！"

# 戦士風の男冒険者
# display as 戦士冒険者
# そうだそうだ！
193 = "そうだそうだ！"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# 俺達だって、この街が好きなんです！
232 = "俺達だって、この街が好きなんです！"

# キース
# デストロイヤーの時みたいに、\nみんなでやっちまおう！
225 = "デストロイヤーの時みたいに、\\nみんなでやっちまおう！"

# 戦士風の男冒険者
# display as 戦士冒険者
# おおー！
186 = "おおー！"

# めぐみん
# なんだか、勝手に盛り上がってますね。
200 = "なんだか、勝手に盛り上がってますね。"

# ダクネス
# ふふ、いいものじゃないか。\nこの空気こそが、\n冒険者の醍醐味というものだろう。
203 = "ふふ、いいものじゃないか。\\nこの空気こそが、\\n冒険者の醍醐味というものだろう。"

# クリス
# うん、そうかも。
183 = "うん、そうかも。"

# ゆんゆん
# 嬉しいです……！\n私、ずっとこういうのに憧れてたから……。
236 = "嬉しいです……！\\n私、ずっとこういうのに憧れてたから……。"

# ダスト
# よーし、景気づけに乾杯だぁ！\nシュワシュワありったけ持ってこーい！
210 = "よーし、景気づけに乾杯だぁ！\\nシュワシュワありったけ持ってこーい！"

# カズマ
# お、おい！\nそんなことしてる暇なんてないぞ、\n準備しないと！
185 = "お、おい！\\nそんなことしてる暇なんてないぞ、\\n準備しないと！"

# アクア
# まあまあ、いいじゃない！\nこういうのって大事よ、ぱーっといきましょ！
205 = "まあまあ、いいじゃない！\\nこういうのって大事よ、ぱーっといきましょ！"

# アクア
# 景気づけの花鳥風月♪
242 = "景気づけの花鳥風月♪"

# カズマ
# お前はシュワシュワ飲みたいだけだろ！
187 = "お前はシュワシュワ飲みたいだけだろ！"

# ウィズ
# でも、せっかくですから。\nみなさんのお気持ち、受け取りませんか？
199 = "でも、せっかくですから。\\nみなさんのお気持ち、受け取りませんか？"

# カズマ
# ウィズまで……。
213 = "ウィズまで……。"

# ダスト
# ほら、カズマ！\nお前もジョッキ持て！
204 = "ほら、カズマ！\\nお前もジョッキ持て！"

# カズマ
# いや、俺は飲めないんだけど！？
182 = "いや、俺は飲めないんだけど！？"

# キース
# ああ、そっか。\nんじゃ、こっちのジュースにしとけ。
179 = "ああ、そっか。\\nんじゃ、こっちのジュースにしとけ。"

# ダスト
# みんな、いいな！？\nあの店――\nじゃなかった！　この街は俺達が守るぞ！！
207 = "みんな、いいな！？\\nあの店――\\nじゃなかった！　この街は俺達が守るぞ！！"

# キース
# おおー！
# 186 = "おおー！"

# カズマ
# …………。
178 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （ドラゴンがここに来るのは俺達のせいだ。\n　だから、責任は俺達が取るべきだって\n　わかってるんだけど……）
291 = "（ドラゴンがここに来るのは俺達のせいだ。\\n　だから、責任は俺達が取るべきだって\\n　わかってるんだけど……）"

# カズマ（Ｍ）
# display as カズマ
# （でも！　この空気！　この感じ！\n　今、なんかすっげー冒険者っぽい！！）
289 = "（でも！　この空気！　この感じ！\\n　今、なんかすっげー冒険者っぽい！！）"

# カズマ（Ｍ）
# display as カズマ
# （くうう～！　いい！　最高だ！\n　そうだよ、異世界生活と言えば\n　こんな展開が王道だろ！！）
285 = "（くうう～！　いい！　最高だ！\\n　そうだよ、異世界生活と言えば\\n　こんな展開が王道だろ！！）"

# カズマ（Ｍ）
# display as カズマ
# （これならきっと、\n　スカルドラゴンにだって勝てる！\n　それもまた王道ってやつだ！）
287 = "（これならきっと、\\n　スカルドラゴンにだって勝てる！\\n　それもまた王道ってやつだ！）"

# カズマ（Ｍ）
# display as カズマ
# （……でも、全部が\n　この指輪のせいだってみんなが知ったら\n　どうなるだろう）
281 = "（……でも、全部が\\n　この指輪のせいだってみんなが知ったら\\n　どうなるだろう）"

# カズマ（Ｍ）
# display as カズマ
# （いや、怖いことを考えるのは止めだ！\n　今はただ、スカルドラゴンを\n　倒すことだけに集中しよう！）
283 = "（いや、怖いことを考えるのは止めだ！\\n　今はただ、スカルドラゴンを\\n　倒すことだけに集中しよう！）"

