# st05b_01.txt.scn

[info]
0 = ""

[characters]
214 = "カズマ"
225 = "ダクネス"
212 = "ウィズ"
226 = "ダスト"
218 = "キース"
217 = "カズマ（Ｍ）"
227 = "ルナ"
219 = "クリス"
209 = "ゆんゆん"
211 = "アクア"
208 = "めぐみん"

[character_subs]
# 214 = "カズマ"

[script]
# lines: 74

# カズマ
# うおっ！？\nすげー人だな、デストロイヤーの時みたいだ。
179 = "うおっ！？\\nすげー人だな、デストロイヤーの時みたいだ。"

# ダクネス
# 全冒険者が集まるのだから、\nこれからさらに増えるぞ。
234 = "全冒険者が集まるのだから、\\nこれからさらに増えるぞ。"

# ウィズ
# あっ！　カズマさん！
171 = "あっ！　カズマさん！"

# カズマ
# おう、ウィズ！\n来てたんだな。
186 = "おう、ウィズ！\\n来てたんだな。"

# ウィズ
# ええ、私も一応、\n冒険者の資格を持っていますので、\n何かお手伝いできるのではと。
183 = "ええ、私も一応、\\n冒険者の資格を持っていますので、\\n何かお手伝いできるのではと。"

# ウィズ
# それより、カズマさん。\n今度はいったい何をやったんですか？
195 = "それより、カズマさん。\\n今度はいったい何をやったんですか？"

# カズマ
# ウィズまで……。\nいったい俺ってみんなにどう思われてるの。
213 = "ウィズまで……。\\nいったい俺ってみんなにどう思われてるの。"

# ウィズ
# 心当たりはないんですね？
241 = "心当たりはないんですね？"

# カズマ
# いや、パンツの件とか指輪の件とか色々あるけどさ。\nそれって全冒険者を集めてどうこうするって\n問題じゃないだろ。
178 = "いや、パンツの件とか指輪の件とか色々あるけどさ。\\nそれって全冒険者を集めてどうこうするって\\n問題じゃないだろ。"

# ウィズ
# 確かにそうですね。
289 = "確かにそうですね。"

# ダスト
# よう、カズマ！\n今度は何をやったんだ？
210 = "よう、カズマ！\\n今度は何をやったんだ？"

# カズマ
# 何もやってねえよ。
231 = "何もやってねえよ。"

# ダスト
# いや、でも、お前がこの街に来てから\n魔王軍の幹部にデストロイヤーと\n騒ぎが続いたからなぁ。
177 = "いや、でも、お前がこの街に来てから\\n魔王軍の幹部にデストロイヤーと\\n騒ぎが続いたからなぁ。"

# キース
# 二度あることは三度あるか？\nいやいやカズマでも、さすがにもう打ち止めだろ。
229 = "二度あることは三度あるか？\\nいやいやカズマでも、さすがにもう打ち止めだろ。"

# カズマ（Ｍ）
# display as カズマ
# （やめろ、それはフラグになる……）
297 = "（やめろ、それはフラグになる……）"

# ルナ
# 冒険者のみなさん！\nギルドより、事態の説明を行いますので\nお静かにお願いします！
235 = "冒険者のみなさん！\\nギルドより、事態の説明を行いますので\\nお静かにお願いします！"

# キース
# おっと、話が始まるみたいだな。
187 = "おっと、話が始まるみたいだな。"

# ルナ
# それでは、順を追って説明させていただきます。
194 = "それでは、順を追って説明させていただきます。"

# ルナ
# まず、先日、この街の近くの洞窟にて\nスカルドラゴンが発見されたと報告がありました。
206 = "まず、先日、この街の近くの洞窟にて\\nスカルドラゴンが発見されたと報告がありました。"

# ダスト
# スカルドラゴンって、マジかよ！
221 = "スカルドラゴンって、マジかよ！"

# キース
# 身近にそんな大物が潜んでいたなんてな。
292 = "身近にそんな大物が潜んでいたなんてな。"

# ルナ
# ですが、身を潜めていた洞窟が崩落し、\nスカルドラゴンもその場を立ち去りました。
198 = "ですが、身を潜めていた洞窟が崩落し、\\nスカルドラゴンもその場を立ち去りました。"

# ルナ
# その後、念のために\nギルド側でスカルドラゴンの行方を\n追っていたのですが――
193 = "その後、念のために\\nギルド側でスカルドラゴンの行方を\\n追っていたのですが――"

# ルナ
# 現在、そのスカルドラゴンが\nこの街に向かっていると判明したのです。
247 = "現在、そのスカルドラゴンが\\nこの街に向かっていると判明したのです。"

# カズマ
# なああああああああ！？
204 = "なああああああああ！？"

# クリス
# あのドラゴンがここに？
174 = "あのドラゴンがここに？"

# ゆんゆん
# ど、ど、どうしてですか！？\nなんで来るんですか！？
201 = "ど、ど、どうしてですか！？\\nなんで来るんですか！？"

# カズマ
# 俺に聞かれても困るって！
233 = "俺に聞かれても困るって！"

# ダスト
# スカルドラゴンなら\nこの街くらい簡単に壊滅させるぞ！？
222 = "スカルドラゴンなら\\nこの街くらい簡単に壊滅させるぞ！？"

# キース
# ああ。\nデストロイヤーほどではないにしても、まずいな。
170 = "ああ。\\nデストロイヤーほどではないにしても、まずいな。"

# ルナ
# こちらで飛ばしている偵察によると、\nスカルドラゴンは少しずつ\n街に向かってきているようです。
189 = "こちらで飛ばしている偵察によると、\\nスカルドラゴンは少しずつ\\n街に向かってきているようです。"

# ルナ
# ですので、今すぐに\n襲いかかってくるということはありません。\n迎撃準備の時間は作れると思います。
199 = "ですので、今すぐに\\n襲いかかってくるということはありません。\\n迎撃準備の時間は作れると思います。"

# ルナ
# みなさんが、この街に残された最後の砦です。\nもちろん相応の特別報酬はお支払いします。
207 = "みなさんが、この街に残された最後の砦です。\\nもちろん相応の特別報酬はお支払いします。"

# アクア
# 特別報酬！？
246 = "特別報酬！？"

# ルナ
# 緊急クエストとしての報酬に加え、\nスカルドラゴン自体にも\n懸賞金がかけられることが、先ほど決まりました。
291 = "緊急クエストとしての報酬に加え、\\nスカルドラゴン自体にも\\n懸賞金がかけられることが、先ほど決まりました。"

# アクア
# 懸賞金！？
243 = "懸賞金！？"

# カズマ（Ｍ）
# display as カズマ
# （うわぁ……。\n　目がらんらんと輝いたぞ）
293 = "（うわぁ……。\\n　目がらんらんと輝いたぞ）"

# ダスト
# つーか、なんでこの街に来るんだ？
197 = "つーか、なんでこの街に来るんだ？"

# カズマ
# そ、そうだ、なんでだよ。\nあの時はあっさり飛び去っていったのに\nなんで戻ってくるような真似……を。
192 = "そ、そうだ、なんでだよ。\\nあの時はあっさり飛び去っていったのに\\nなんで戻ってくるような真似……を。"

# アクア
# 特別報酬とスカルドラゴンの懸賞金――
245 = "特別報酬とスカルドラゴンの懸賞金――"

# カズマ
# ジー……。
220 = "ジー……。"

# アクア
# いったいいくらになるのかしら。
175 = "いったいいくらになるのかしら。"

# カズマ
# ジー……。
# 220 = "ジー……。"

# アクア
# お金が入ったらまず借金を返して、\nそれで冬に備えて暖かいコートを買って、\nあとは高級シュワシュワも――
188 = "お金が入ったらまず借金を返して、\\nそれで冬に備えて暖かいコートを買って、\\nあとは高級シュワシュワも――"

# カズマ
# ジー……。
# 220 = "ジー……。"

# アクア
# って、さっきからなんなのよ。\nあっ、報酬は私が６でみんなが４だからね。
196 = "って、さっきからなんなのよ。\\nあっ、報酬は私が６でみんなが４だからね。"

# カズマ
# この野郎！\n自分で物騒なもんを引き寄せておいて\nそれを言うか！
190 = "この野郎！\\n自分で物騒なもんを引き寄せておいて\\nそれを言うか！"

# アクア
# ええ、どういう意味よ！
182 = "ええ、どういう意味よ！"

# カズマ
# スカルドラゴンは、\nお前のなんちゃって神気に引き寄せられて\nこの街に向かって来てるんだろうが！
224 = "スカルドラゴンは、\\nお前のなんちゃって神気に引き寄せられて\\nこの街に向かって来てるんだろうが！"

# アクア
# ええ、そうなの！？
181 = "ええ、そうなの！？"

# カズマ
# 他にどんな理由がある！
230 = "他にどんな理由がある！"

# ウィズ
# あの、カズマさん、それはおかしいかと。
173 = "あの、カズマさん、それはおかしいかと。"

# カズマ
# え？　どうしてだ？
185 = "え？　どうしてだ？"

# ウィズ
# 確かにスカルドラゴンはアンデッド族ですが、\nスケルトンやゾンビとは違い自我を持つ存在です。
290 = "確かにスカルドラゴンはアンデッド族ですが、\\nスケルトンやゾンビとは違い自我を持つ存在です。"

# ウィズ
# ですので、無意識に成仏を願い、\nアクア様の神気に引き寄せられて来るというのは\n考えにくいんですよ。
200 = "ですので、無意識に成仏を願い、\\nアクア様の神気に引き寄せられて来るというのは\\n考えにくいんですよ。"

# カズマ（Ｍ）
# display as カズマ
# （確かにウィズもアクアに引き寄せられて\n　ここにいるわけじゃないもんな）
299 = "（確かにウィズもアクアに引き寄せられて\\n　ここにいるわけじゃないもんな）"

# カズマ（Ｍ）
# display as カズマ
# （だったら、いったいどうして――）
296 = "（だったら、いったいどうして――）"

# カズマ
# うわ！？\nな、なんだ！？
180 = "うわ！？\\nな、なんだ！？"

# ルナ
# な、何事ですか！？
203 = "な、何事ですか！？"

# カズマ（Ｍ）
# display as カズマ
# （これって……もしかして！）
294 = "（これって……もしかして！）"

# めぐみん
# カズマ、また指輪が光りましたよ！？
215 = "カズマ、また指輪が光りましたよ！？"

# ダクネス
# どういうことだ？\nなぜ、このタイミングで？
202 = "どういうことだ？\\nなぜ、このタイミングで？"

# カズマ
# 俺に聞かれてもわかんねーんだって。
232 = "俺に聞かれてもわかんねーんだって。"

# ゆんゆん
# あの、これって、スカルドラゴンのところで\n光ったのと同じですよね？
172 = "あの、これって、スカルドラゴンのところで\\n光ったのと同じですよね？"

# ルナ
# スカルドラゴンのところでも？\nそれは、ドラゴンと指輪に\nなんらかの関係があるということでしょうか？
223 = "スカルドラゴンのところでも？\\nそれは、ドラゴンと指輪に\\nなんらかの関係があるということでしょうか？"

# カズマ
# いや、その、本当にわからないんですよ。
176 = "いや、その、本当にわからないんですよ。"

# ウィズ
# カズマさん。\nここは、バニルさんに聞いてみたほうが\nいいのではないでしょうか？
216 = "カズマさん。\\nここは、バニルさんに聞いてみたほうが\\nいいのではないでしょうか？"

# カズマ（Ｍ）
# display as カズマ
# （バニルに？）
298 = "（バニルに？）"

# ウィズ
# 恐らくバニルさんなら\n光った理由も見通せると思います。
242 = "恐らくバニルさんなら\\n光った理由も見通せると思います。"

# カズマ（Ｍ）
# display as カズマ
# （そうだな。\n　確かにあいつなら……）
295 = "（そうだな。\\n　確かにあいつなら……）"

# カズマ
# すみません！\n俺達、ちょっと席を外します！
191 = "すみません！\\n俺達、ちょっと席を外します！"

# ルナ
# えっ！？　そんな！\n確かにスカルドラゴン退治への参加は\n任意ですが……。
184 = "えっ！？　そんな！\\n確かにスカルドラゴン退治への参加は\\n任意ですが……。"

# カズマ
# 大丈夫、逃げたりなんてしませんよ。\nこの指輪が光った理由を調べてくるだけです。
238 = "大丈夫、逃げたりなんてしませんよ。\\nこの指輪が光った理由を調べてくるだけです。"

# ルナ
# は、はあ、わかりました。
205 = "は、はあ、わかりました。"

