# st05a_14.txt.scn

[info]
0 = ""

[characters]
190 = "カズマ（Ｍ）"
188 = "カズマ"
187 = "アクア"
184 = "めぐみん"
191 = "クリス"
192 = "ダクネス"
193 = "ルナ"
186 = "ゆんゆん"

[character_subs]
# 188 = "カズマ"

[script]
# lines: 41

# カズマ（Ｍ）
# display as カズマ
# （そして数日が過ぎました）
232 = "（そして数日が過ぎました）"

# カズマ
# はい、みんな集合。
178 = "はい、みんな集合。"

# アクア
# どうしたのよ。\nめずらしく神妙な顔しちゃって。
172 = "どうしたのよ。\\nめずらしく神妙な顔しちゃって。"

# カズマ
# 俺は今、現実の厳しさを思い知らされている。
196 = "俺は今、現実の厳しさを思い知らされている。"

# めぐみん
# いったい何があったんです。\n早く説明してくださいよ。
158 = "いったい何があったんです。\\n早く説明してくださいよ。"

# カズマ
# これが我々の全財産。\nしめて２０万２千エリスだ。
162 = "これが我々の全財産。\\nしめて２０万２千エリスだ。"

# アクア
# へえ、３日でそんなに貯まったの？
179 = "へえ、３日でそんなに貯まったの？"

# めぐみん
# なかなかいいペースじゃないですか。
174 = "なかなかいいペースじゃないですか。"

# カズマ
# 確かに３日で２０万だ。\n悪い数字じゃない。
230 = "確かに３日で２０万だ。\\n悪い数字じゃない。"

# カズマ
# しかし、この額の半分は、\n初日にダクネスとクリスが傭兵として稼いだ金\nだったりする。
165 = "しかし、この額の半分は、\\n初日にダクネスとクリスが傭兵として稼いだ金\\nだったりする。"

# カズマ
# そしてここ数日、２人に傭兵の依頼はない。
166 = "そしてここ数日、２人に傭兵の依頼はない。"

# クリス
# あはは、申し訳ない。
155 = "あはは、申し訳ない。"

# カズマ
# いいか！！　俺たちは３０００万エリスを\n目指してるんだぞ！
157 = "いいか！！　俺たちは３０００万エリスを\\n目指してるんだぞ！"

# カズマ
# こんなちまちまやってたら、\nそれこそパンツを通して、この街に住む女の子の\n趣味嗜好まで把握することになるわ！
164 = "こんなちまちまやってたら、\\nそれこそパンツを通して、この街に住む女の子の\\n趣味嗜好まで把握することになるわ！"

# めぐみん
# まず、その考えがおかしいということに\n気がついてくださいよ。
181 = "まず、その考えがおかしいということに\\n気がついてくださいよ。"

# クリス
# 盗んだからといって、\n別に直接本人に返す必要はないんだからね。
203 = "盗んだからといって、\\n別に直接本人に返す必要はないんだからね。"

# カズマ
# とにかく地道なんてダメ！　絶対ダメ！
171 = "とにかく地道なんてダメ！　絶対ダメ！"

# ダクネス
# まったく、まずはコツコツと貯めると言ったのは\nどこの誰だ。
183 = "まったく、まずはコツコツと貯めると言ったのは\\nどこの誰だ。"

# カズマ
# 俺ですけど、それがなんですか？\n言うことに一貫性が欠けるって説教したいんですか？
195 = "俺ですけど、それがなんですか？\\n言うことに一貫性が欠けるって説教したいんですか？"

# めぐみん
# カズマ。\nそこまで言うんですから、\nもちろん稼ぐ宛てがあるんですよね。
189 = "カズマ。\\nそこまで言うんですから、\\nもちろん稼ぐ宛てがあるんですよね。"

# カズマ
# ないからこうやってみんなを集めてるんだろ。
173 = "ないからこうやってみんなを集めてるんだろ。"

# ダクネス
# はあ。\nやれやれ、これでは堂々めぐりじゃないか。
177 = "はあ。\\nやれやれ、これでは堂々めぐりじゃないか。"

# ルナ
# 緊急！　緊急！
231 = "緊急！　緊急！"

# カズマ
# うおっ！？\nな、なんだ？
160 = "うおっ！？\\nな、なんだ？"

# ゆんゆん
# これって……ギルドの警報ですよ！？
163 = "これって……ギルドの警報ですよ！？"

# ルナ
# 全冒険者の皆さんは、直ちに武装し、\nギルドに集まってください！
197 = "全冒険者の皆さんは、直ちに武装し、\\nギルドに集まってください！"

# ルナ
# 特に、冒険者サトウカズマさんと\nその一行は大至急でお願いします！
202 = "特に、冒険者サトウカズマさんと\\nその一行は大至急でお願いします！"

# カズマ
# え？　俺？　なんで俺？
161 = "え？　俺？　なんで俺？"

# アクア
# あんた、またなんかやったの？
156 = "あんた、またなんかやったの？"

# カズマ
# またってなんだよ、またって！
182 = "またってなんだよ、またって！"

# アクア
# もういいから早く謝っちゃいなさいよ。\nもし１人でギルドに行くのが怖いって言うなら、\n私も一緒に行ってあげるから。
185 = "もういいから早く謝っちゃいなさいよ。\\nもし１人でギルドに行くのが怖いって言うなら、\\n私も一緒に行ってあげるから。"

# カズマ
# いやいやいや、何もやってねーから！
159 = "いやいやいや、何もやってねーから！"

# ダクネス
# それに招集は、私たちも含んでいただろう。
168 = "それに招集は、私たちも含んでいただろう。"

# アクア
# 確かにそうね。
229 = "確かにそうね。"

# ゆんゆん
# ねえねえ、めぐみん。\nその一行の中には、私も含まれるのかな？
176 = "ねえねえ、めぐみん。\\nその一行の中には、私も含まれるのかな？"

# めぐみん
# なんですその質問は。
175 = "なんですその質問は。"

# ゆんゆん
# だ、だって、最近よく一緒に行動してるし、\nこの前はカズマさんと冒険もしたから、\nもしかしたら仲間って思われてるのかなって。
169 = "だ、だって、最近よく一緒に行動してるし、\\nこの前はカズマさんと冒険もしたから、\\nもしかしたら仲間って思われてるのかなって。"

# めぐみん
# つまり一緒に来たいんでしょ？　来たいんですよね？\nだったらそうすればいいじゃないですか！\n相変わらず、煮え切らない子ですね！
170 = "つまり一緒に来たいんでしょ？　来たいんですよね？\\nだったらそうすればいいじゃないですか！\\n相変わらず、煮え切らない子ですね！"

# クリス
# それだとあたしも行かざるを得ないのかな？
167 = "それだとあたしも行かざるを得ないのかな？"

# ダクネス
# まあ、念のためそうした方がいいだろうな。
180 = "まあ、念のためそうした方がいいだろうな。"

# カズマ（Ｍ）
# display as カズマ
# （緊急事態って、なんなんだよ、いったい）
233 = "（緊急事態って、なんなんだよ、いったい）"

