# st05a_04.txt.scn

[info]
0 = ""

[characters]
236 = "カズマ（Ｍ）"
237 = "キース"
239 = "ダスト"
234 = "カズマ"
238 = "ダクネス"
233 = "アクア"
230 = "めぐみん"

[character_subs]
# 234 = "カズマ"

[script]
# lines: 53

# カズマ（Ｍ）
# display as カズマ
# （さっきから、俺達が囲んだテーブルでは\n　沈黙が続いている）
289 = "（さっきから、俺達が囲んだテーブルでは\\n　沈黙が続いている）"

# カズマ（Ｍ）
# display as カズマ
# （何しろ、話すべきことがない。\n　どうやって金を稼げばいいのか、\n　もう方法が出てこないんだ）
292 = "（何しろ、話すべきことがない。\\n　どうやって金を稼げばいいのか、\\n　もう方法が出てこないんだ）"

# キース
# あれ、カズマじゃないか。\n何してるんだ。
198 = "あれ、カズマじゃないか。\\n何してるんだ。"

# ダスト
# って、なんだこの空気。\n誰か死にでもしたのか？
217 = "って、なんだこの空気。\\n誰か死にでもしたのか？"

# カズマ
# 縁起でもねーこと言うんじゃねーよ。\n今の俺にはシャレに聞こえねーし。
284 = "縁起でもねーこと言うんじゃねーよ。\\n今の俺にはシャレに聞こえねーし。"

# ダスト
# おいおい、マジでどうした？\n聞いてやるから、ちょっと話してみろよ。
206 = "おいおい、マジでどうした？\\n聞いてやるから、ちょっと話してみろよ。"

# カズマ
# 実はな……。
245 = "実はな……。"

# ダスト
# はあ、なるほど。\n金儲けの方法ねぇ。
223 = "はあ、なるほど。\\n金儲けの方法ねぇ。"

# カズマ
# 何か無いか？\nもう藁にでもすがりたい気分なんだ。
241 = "何か無いか？\\nもう藁にでもすがりたい気分なんだ。"

# キース
# いや、そんな期待を込めた目で見られても困る。
200 = "いや、そんな期待を込めた目で見られても困る。"

# ダスト
# ぶっちゃけ、そんな方法があるなら\nこっちだって知りたいっての。
227 = "ぶっちゃけ、そんな方法があるなら\\nこっちだって知りたいっての。"

# カズマ（Ｍ）
# display as カズマ
# （そうだよなぁ）
290 = "（そうだよなぁ）"

# ダスト
# なあ、そもそも３０００万エリスって\n金額が無茶苦茶なんだし、\nそこのところをなんとかしたらどうなんだ？
220 = "なあ、そもそも３０００万エリスって\\n金額が無茶苦茶なんだし、\\nそこのところをなんとかしたらどうなんだ？"

# ダクネス
# なんとか、というのはどういうことだ？
222 = "なんとか、というのはどういうことだ？"

# ダスト
# 話が通じる相手かどうかは知らねーけど、\n割引交渉をしてみたらどうかってこと。
287 = "話が通じる相手かどうかは知らねーけど、\\n割引交渉をしてみたらどうかってこと。"

# カズマ
# うーん、それは確かにありかもな。
204 = "うーん、それは確かにありかもな。"

# アクア
# はあ！？\nあの害虫に頭を下げるなんて、私は絶対に嫌よ！
224 = "はあ！？\\nあの害虫に頭を下げるなんて、私は絶対に嫌よ！"

# カズマ
# いや、俺だって一度やるって言ったことを\n取り下げるなんて、できればしたくねーけど……。
201 = "いや、俺だって一度やるって言ったことを\\n取り下げるなんて、できればしたくねーけど……。"

# キース
# そんな状況でもないんだろ？
214 = "そんな状況でもないんだろ？"

# めぐみん
# でもカズマ、まけてくれとか言う気はないって\n何度も見栄を張っちゃってますよね？\nなのに、いまさら、格好悪すぎません？
218 = "でもカズマ、まけてくれとか言う気はないって\\n何度も見栄を張っちゃってますよね？\\nなのに、いまさら、格好悪すぎません？"

# カズマ
# それは言うな、わかってるから。
213 = "それは言うな、わかってるから。"

# ダスト
# はははっ！\n見栄で金は稼げないもんな！
225 = "はははっ！\\n見栄で金は稼げないもんな！"

# キース
# じゃあ、俺達はこれで。\n頑張って生きろよ、カズマ。
211 = "じゃあ、俺達はこれで。\\n頑張って生きろよ、カズマ。"

# ダクネス
# どうするんだ？\n本当にバニルと交渉する気か？
219 = "どうするんだ？\\n本当にバニルと交渉する気か？"

# アクア
# あいつに頭を下げるなんて、私は反対よ！\nそれに、あの悪魔が話を聞くとは思えないわ。
196 = "あいつに頭を下げるなんて、私は反対よ！\\nそれに、あの悪魔が話を聞くとは思えないわ。"

# カズマ
# まあ、そうだろうけど。\nダメ元で話すだけ話してみようぜ。
228 = "まあ、そうだろうけど。\\nダメ元で話すだけ話してみようぜ。"

# めぐみん
# カズマがそう言うのなら私はいいですよ。\nカズマのプライドと引き替えだから\n私には関係ないですし。
235 = "カズマがそう言うのなら私はいいですよ。\\nカズマのプライドと引き替えだから\\n私には関係ないですし。"

# ダクネス
# まあ、私もカズマがいいのなら構わないが。
229 = "まあ、私もカズマがいいのなら構わないが。"

# アクア
# 私は嫌！\n女神のプライドにかけて、そんなこと許せないわ。
283 = "私は嫌！\\n女神のプライドにかけて、そんなこと許せないわ。"

# カズマ
# じゃあ、お前がなんとかしてくれるのか？\n３０００万エリスを稼ぐ方法を考えてくれるのか？
210 = "じゃあ、お前がなんとかしてくれるのか？\\n３０００万エリスを稼ぐ方法を考えてくれるのか？"

# アクア
# それは私の役割じゃないんですけど？
212 = "それは私の役割じゃないんですけど？"

# カズマ
# ああん？\n俺達の提案に反対するのなら\n代わりの案を出すのが当然だろ？
195 = "ああん？\\n俺達の提案に反対するのなら\\n代わりの案を出すのが当然だろ？"

# アクア
# あんた、女神に命令する気なの！？
199 = "あんた、女神に命令する気なの！？"

# カズマ
# 命令じゃねーよ。\nそれが当然だって言ってんだ！
243 = "命令じゃねーよ。\\nそれが当然だって言ってんだ！"

# アクア
# うう……。
202 = "うう……。"

# カズマ
# 案がないんだったら、大人しく一緒に来い。\nいいな？
248 = "案がないんだったら、大人しく一緒に来い。\\nいいな？"

# アクア
# …………。
194 = "…………。"

# カズマ
# 返事！
288 = "返事！"

# アクア
# わかったわよ。
232 = "わかったわよ。"

# カズマ
# 言いくるめちまおうぜ。\nそれなら、お前だって\nあいつに負けた気はしないだろ？
286 = "言いくるめちまおうぜ。\\nそれなら、お前だって\\nあいつに負けた気はしないだろ？"

# アクア
# うーん、そうねぇ。\nまあ、それだったらいいかしら。
203 = "うーん、そうねぇ。\\nまあ、それだったらいいかしら。"

# ダクネス
# しかし、あのバニルを言いくるめるのは\n相当、骨が折れそうだな。
207 = "しかし、あのバニルを言いくるめるのは\\n相当、骨が折れそうだな。"

# カズマ
# だろうけど、やってみるしかないだろ。
216 = "だろうけど、やってみるしかないだろ。"

# カズマ
# 敵に背を向けるのか、女神様？
247 = "敵に背を向けるのか、女神様？"

# アクア
# なっ！？\nそんなことするわけないじゃない！\n私を誰だと思ってるのよ！
221 = "なっ！？\\nそんなことするわけないじゃない！\\n私を誰だと思ってるのよ！"

# カズマ
# 女神アクア、だろ？
244 = "女神アクア、だろ？"

# アクア
# ふふん、その通りよ！
226 = "ふふん、その通りよ！"

# カズマ
# だよなー！\nだったら、悪魔のバニルなんて\n問題にならないんじゃないか？
215 = "だよなー！\\nだったら、悪魔のバニルなんて\\n問題にならないんじゃないか？"

# アクア
# ええ、そうよね。\nいいわ、格の違いってものを\n見せてあげようじゃない！
205 = "ええ、そうよね。\\nいいわ、格の違いってものを\\n見せてあげようじゃない！"

# カズマ（Ｍ）
# display as カズマ
# （よしよし、やる気を出してくれたな。\n　チョロいぜ、この駄女神）
291 = "（よしよし、やる気を出してくれたな。\\n　チョロいぜ、この駄女神）"

# めぐみん
# あの扱いは正直、アクアをダメにしていく\n一方だと思いますが。
197 = "あの扱いは正直、アクアをダメにしていく\\n一方だと思いますが。"

# ダクネス
# よせ、めぐみん。\nそっとしておいてやれ。
231 = "よせ、めぐみん。\\nそっとしておいてやれ。"

# カズマ
# じゃ、バニルのところへ行くぞ。
208 = "じゃ、バニルのところへ行くぞ。"

[selections]
209 = "じゃあ、お前がなんとかしてくれるのか？"
285 = "言いくるめちまおうぜ"
# 247 = "敵に背を向けるのか、女神様？"
