# st05a_01.txt.scn

[info]
0 = ""

[characters]
253 = "カズマ（Ｍ）"
249 = "カズマ"
248 = "アクア"
244 = "めぐみん"
254 = "ダクネス"

[character_subs]
# 249 = "カズマ"

[script]
# lines: 77

# カズマ（Ｍ）
# display as カズマ
# （……うん？\n　ああ、朝になったのか）
311 = "（……うん？\\n　ああ、朝になったのか）"

# カズマ（Ｍ）
# display as カズマ
# （さて、と。\n　夕べは満月だったわけだが……）
321 = "（さて、と。\\n　夕べは満月だったわけだが……）"

# カズマ（Ｍ）
# display as カズマ
# （いや、もうパンツを盗んでしまうのは\n　想定の範囲内だからいいとして――）
315 = "（いや、もうパンツを盗んでしまうのは\\n　想定の範囲内だからいいとして――）"

# カズマ（Ｍ）
# display as カズマ
# （問題は枚数だ。\n　今回、俺は一体、\n　何枚のパンツをスティールしたんだ？）
335 = "（問題は枚数だ。\\n　今回、俺は一体、\\n　何枚のパンツをスティールしたんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （１枚、２枚、３枚、４枚、５枚……。\n　ちくしょう大量だ！）
339 = "（１枚、２枚、３枚、４枚、５枚……。\\n　ちくしょう大量だ！）"

# カズマ（Ｍ）
# display as カズマ
# （やっぱり、この指輪の効果が\n　どんどん強まってるのか……）
332 = "（やっぱり、この指輪の効果が\\n　どんどん強まってるのか……）"

# カズマ（Ｍ）
# display as カズマ
# （勘弁してくれよ！\n　このままじゃ、本当に死ぬことになる！\n　なんとかしてこの指輪を外さないと！）
334 = "（勘弁してくれよ！\\n　このままじゃ、本当に死ぬことになる！\\n　なんとかしてこの指輪を外さないと！）"

# カズマ（Ｍ）
# display as カズマ
# （って、こう決心するのも何回目なんだよ。\n　我ながら情けなくなってくるぜ）
323 = "（って、こう決心するのも何回目なんだよ。\\n　我ながら情けなくなってくるぜ）"

# カズマ（Ｍ）
# display as カズマ
# （まさか、なんの進展もしないまま\n　数ヶ月を過ごすことになるなんて\n　思いもしなかった……）
329 = "（まさか、なんの進展もしないまま\\n　数ヶ月を過ごすことになるなんて\\n　思いもしなかった……）"

# カズマ（Ｍ）
# display as カズマ
# （進展どころか、むしろ失敗ばかりで\n　事態が悪化しているような気すらしてくる）
338 = "（進展どころか、むしろ失敗ばかりで\\n　事態が悪化しているような気すらしてくる）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、もうダメだ……。\n　俺はこのまま呪いの指輪に殺されるんだ……）
314 = "（ああ、もうダメだ……。\\n　俺はこのまま呪いの指輪に殺されるんだ……）"

# カズマ（Ｍ）
# display as カズマ
# （父さん、母さん。\n　先立つ不孝をお許しください）
337 = "（父さん、母さん。\\n　先立つ不孝をお許しください）"

# カズマ（Ｍ）
# display as カズマ
# （って、そうだ。\n　元の世界じゃ、俺、\n　もうとっくに死んだことになってるんだった）
324 = "（って、そうだ。\\n　元の世界じゃ、俺、\\n　もうとっくに死んだことになってるんだった）"

# カズマ（Ｍ）
# display as カズマ
# （はははは……。\n　そうだよ、俺はそもそも死んだ身じゃないか）
328 = "（はははは……。\\n　そうだよ、俺はそもそも死んだ身じゃないか）"

# カズマ（Ｍ）
# display as カズマ
# （もう、このまま安らかに死を迎え入れよう。\n　眠ったまま、穏やかに……）
331 = "（もう、このまま安らかに死を迎え入れよう。\\n　眠ったまま、穏やかに……）"

# カズマ（Ｍ）
# display as カズマ
# （ああ……。\n　暗闇がとても落ち着く。\n　俺はここで心穏やかにその時を迎えよう）
313 = "（ああ……。\\n　暗闇がとても落ち着く。\\n　俺はここで心穏やかにその時を迎えよう）"

# カズマ（Ｍ）
# display as カズマ
# （このろくでもない世界に\n　さよならを言う時が来るまで、\n　ここに引きこもるんだ）
320 = "（このろくでもない世界に\\n　さよならを言う時が来るまで、\\n　ここに引きこもるんだ）"

# カズマ
# …………。
213 = "…………。"

# カズマ
# ……………。
212 = "……………。"

# カズマ（Ｍ）
# display as カズマ
# （……ん？\n　今、なにか音がしたか？）
312 = "（……ん？\\n　今、なにか音がしたか？）"

# アクア
# まだ寝てるみたいね。
242 = "まだ寝てるみたいね。"

# めぐみん
# では、計画の通りに。
236 = "では、計画の通りに。"

# ダクネス
# ああ、一気にやるぞ。
215 = "ああ、一気にやるぞ。"

# カズマ（Ｍ）
# display as カズマ
# （こいつら――）
319 = "（こいつら――）"

# カズマ
# いったい何をするつもりだ！
218 = "いったい何をするつもりだ！"

# アクア
# ちょっと、なんで起きてるのよ！
232 = "ちょっと、なんで起きてるのよ！"

# カズマ
# 朝だからだよ！
265 = "朝だからだよ！"

# めぐみん
# まあいいです。\nこの程度の計画の狂いは誤差の範囲内。\n今日という今日は覚悟をしてもらいますよ！
241 = "まあいいです。\\nこの程度の計画の狂いは誤差の範囲内。\\n今日という今日は覚悟をしてもらいますよ！"

# カズマ
# か、覚悟ってなんだよ！？\n人の寝込みを襲っておいて\n意味深なことを言うな！
223 = "か、覚悟ってなんだよ！？\\n人の寝込みを襲っておいて\\n意味深なことを言うな！"

# めぐみん
# 襲ってないわい！
309 = "襲ってないわい！"

# カズマ
# 明らかに襲ってんじゃねーか！\n何考えてんだ、俺はお前を\nそんな子に育てた覚えはねーぞ！？
264 = "明らかに襲ってんじゃねーか！\\n何考えてんだ、俺はお前を\\nそんな子に育てた覚えはねーぞ！？"

# めぐみん
# こっちだって\nカズマに育てられた覚えはありませんよ！
225 = "こっちだって\\nカズマに育てられた覚えはありませんよ！"

# アクア
# めぐみん、惑わされちゃダメよ！\n私達の目的を忘れたの！？
245 = "めぐみん、惑わされちゃダメよ！\\n私達の目的を忘れたの！？"

# カズマ（Ｍ）
# display as カズマ
# （も、目的？）
330 = "（も、目的？）"

# めぐみん
# カズマ、またパンツを取りましたよね？
250 = "カズマ、またパンツを取りましたよね？"

# ダクネス
# そうだ！\nまったく、懲りずに何度も何度も……。
228 = "そうだ！\\nまったく、懲りずに何度も何度も……。"

# ダクネス
# い、いや、まあ……\n私としては悪くないのだが……。
217 = "い、いや、まあ……\\n私としては悪くないのだが……。"

# カズマ（Ｍ）
# display as カズマ
# （おい、それって\n　自分がパンツを取られてるって\n　言ってるようなもんじゃねーか）
317 = "（おい、それって\\n　自分がパンツを取られてるって\\n　言ってるようなもんじゃねーか）"

# アクア
# それでどうするの？\n起きてたら縛れないわ。
230 = "それでどうするの？\\n起きてたら縛れないわ。"

# カズマ
# 縛るって、何をするつもりだったんだ！
308 = "縛るって、何をするつもりだったんだ！"

# ダクネス
# お、お前が考えているようなプレイじゃないからな！
220 = "お、お前が考えているようなプレイじゃないからな！"

# カズマ
# なんにも考えてねえから！
237 = "なんにも考えてねえから！"

# めぐみん
# ふっ、縛るのは、身動きを取れなくするための\n手段の１つに過ぎません。
240 = "ふっ、縛るのは、身動きを取れなくするための\\n手段の１つに過ぎません。"

# めぐみん
# つまり、方法は他にもあるということです。
235 = "つまり、方法は他にもあるということです。"

# カズマ
# お前、何をするつもりだ。
221 = "お前、何をするつもりだ。"

# めぐみん
# 黒より黒く、闇より昏き漆黒に――
310 = "黒より黒く、闇より昏き漆黒に――"

# カズマ
# って、待て！\nなんで爆裂魔法の詠唱をしてるんだ！
233 = "って、待て！\\nなんで爆裂魔法の詠唱をしてるんだ！"

# めぐみん
# 決まってるじゃないですか。\nカズマが身動きを取れないようにするためです。
266 = "決まってるじゃないですか。\\nカズマが身動きを取れないようにするためです。"

# カズマ
# 心臓の動きが止まるわ。
263 = "心臓の動きが止まるわ。"

# アクア
# まったく、なんで起きてるのよ。\n少しは空気を読んで欲しいんですけど。
243 = "まったく、なんで起きてるのよ。\\n少しは空気を読んで欲しいんですけど。"

# カズマ（Ｍ）
# display as カズマ
# （いやいや、そんな空気読めねえから）
316 = "（いやいや、そんな空気読めねえから）"

# カズマ
# それよりも寝込みを襲おうとした理由を\n説明してくれ。
231 = "それよりも寝込みを襲おうとした理由を\\n説明してくれ。"

# ダクネス
# お前が寝ている間に盗まれた物を\n取り返そうとしたんだ。
222 = "お前が寝ている間に盗まれた物を\\n取り返そうとしたんだ。"

# カズマ
# ああ、パンツか。
214 = "ああ、パンツか。"

# めぐみん
# さあ、返してください。\nほら、早く、さあさあ。
227 = "さあ、返してください。\\nほら、早く、さあさあ。"

# カズマ（Ｍ）
# display as カズマ
# （やばい、目が据わってる！）
333 = "（やばい、目が据わってる！）"

# カズマ（Ｍ）
# display as カズマ
# （こ、これは多分、めぐみんも\n　パンツを取られてるな）
318 = "（こ、これは多分、めぐみんも\\n　パンツを取られてるな）"

# アクア
# あーあ。\nカズマが寝てれば話は早かったのに。
216 = "あーあ。\\nカズマが寝てれば話は早かったのに。"

# ダクネス
# こちらで盗んだ物を良きように処理し、\n互いに気まずい想いをしないですんだのだが。
224 = "こちらで盗んだ物を良きように処理し、\\n互いに気まずい想いをしないですんだのだが。"

# めぐみん
# カズマ。\n念のために聞きますが、\n今ここでパンツを返す気はないのですよね？
251 = "カズマ。\\n念のために聞きますが、\\n今ここでパンツを返す気はないのですよね？"

# カズマ
# うん、ないけど。
219 = "うん、ないけど。"

# アクア
# なんのためらいもなく言い切ったわね。
238 = "なんのためらいもなく言い切ったわね。"

# カズマ
# 何度でも言ってやる！\n俺は紳士だ！　紳士として、\nすべてのパンツを正しい持ち主に返す！
258 = "何度でも言ってやる！\\n俺は紳士だ！　紳士として、\\nすべてのパンツを正しい持ち主に返す！"

# カズマ
# それが、パンツを盗むという呪いに対する、\n俺のささやかな抵抗なんだっ！
229 = "それが、パンツを盗むという呪いに対する、\\n俺のささやかな抵抗なんだっ！"

# めぐみん
# はあ……。\nわかりました、もうなにも言いません。
239 = "はあ……。\\nわかりました、もうなにも言いません。"

# アクア
# っていうか、言っても無駄よね。
234 = "っていうか、言っても無駄よね。"

# ダクネス
# カズマらしくはあるがな。
252 = "カズマらしくはあるがな。"

# カズマ
# わかってくれて嬉しいぜ。\nさすがは、ここまで苦楽を共にしてきた仲間だ。
247 = "わかってくれて嬉しいぜ。\\nさすがは、ここまで苦楽を共にしてきた仲間だ。"

# ダクネス
# 仲間……。
256 = "仲間……。"

# めぐみん
# 仲間ですか……。
257 = "仲間ですか……。"

# アクア
# これと仲間……。
226 = "これと仲間……。"

# カズマ
# やめて！　その反応やめて！　マジで傷つくから！\nそれにこれってなんだよ！　本当に失礼だな！？
246 = "やめて！　その反応やめて！　マジで傷つくから！\\nそれにこれってなんだよ！　本当に失礼だな！？"

# カズマ（Ｍ）
# display as カズマ
# （それにしても……）
322 = "（それにしても……）"

# カズマ（Ｍ）
# display as カズマ
# （朝から女の子が３人も部屋に押しかけ、\n　しかも寝込みを襲われる）
336 = "（朝から女の子が３人も部屋に押しかけ、\\n　しかも寝込みを襲われる）"

# カズマ（Ｍ）
# display as カズマ
# （どこのギャルゲーだよ！　って\n　言いたくなるようなシチュエーションだってのに\n　ムフフな展開の１つも期待できない！）
325 = "（どこのギャルゲーだよ！　って\\n　言いたくなるようなシチュエーションだってのに\\n　ムフフな展開の１つも期待できない！）"

# カズマ（Ｍ）
# display as カズマ
# （なにもかもが、俺が思う\n　異世界生活と違う、違いすぎる！）
326 = "（なにもかもが、俺が思う\\n　異世界生活と違う、違いすぎる！）"

# カズマ（Ｍ）
# display as カズマ
# （はあああ……。\n　なんだってこんなことになってるんだ）
327 = "（はあああ……。\\n　なんだってこんなことになってるんだ）"

