# st05a_13.txt.scn

[info]
0 = ""

[characters]
186 = "カズマ（Ｍ）"
185 = "カズマ"
187 = "クリス"
189 = "ダクネス"

[character_subs]
# 185 = "カズマ"

[script]
# lines: 50

# カズマ（Ｍ）
# display as カズマ
# （はあ、さすがに疲れてるな。\n　風呂に入ったら一気にどっと来たぜ。\n　今日はもう寝ちまうか）
224 = "（はあ、さすがに疲れてるな。\\n　風呂に入ったら一気にどっと来たぜ。\\n　今日はもう寝ちまうか）"

# カズマ（Ｍ）
# display as カズマ
# （ん、あれは？）
227 = "（ん、あれは？）"

# カズマ
# よお、こんなところで立ち話か？
184 = "よお、こんなところで立ち話か？"

# クリス
# うわっ！？\nび、びっくりした、キミか。
157 = "うわっ！？\\nび、びっくりした、キミか。"

# カズマ
# なんでそんなに驚くんだよ。\nここ、俺達の屋敷だぞ？
179 = "なんでそんなに驚くんだよ。\\nここ、俺達の屋敷だぞ？"

# クリス
# い、いやぁ、ごめんごめん。\n突然だったからびっくりしてね？\nそれに……ちょっとね？
153 = "い、いやぁ、ごめんごめん。\\n突然だったからびっくりしてね？\\nそれに……ちょっとね？"

# カズマ（Ｍ）
# display as カズマ
# （あー、これは、もしかしなくても\n　俺がパンツを盗ってるから警戒してるのか）
220 = "（あー、これは、もしかしなくても\\n　俺がパンツを盗ってるから警戒してるのか）"

# カズマ
# ２人でなにしてたんだ？\n邪魔しちゃったか？
230 = "２人でなにしてたんだ？\\n邪魔しちゃったか？"

# ダクネス
# いや、邪魔なんてことはない。
154 = "いや、邪魔なんてことはない。"

# ダクネス
# こうして、クリスと１つ屋根の下で寝る機会は\nなかなかなくてな。\nつい、話し込んでしまっていたんだ。
164 = "こうして、クリスと１つ屋根の下で寝る機会は\\nなかなかなくてな。\\nつい、話し込んでしまっていたんだ。"

# クリス
# でも、夕食をご馳走になった上に\n泊めてもらっちゃって、本当によかったの？
175 = "でも、夕食をご馳走になった上に\\n泊めてもらっちゃって、本当によかったの？"

# ダクネス
# 気にするな。\n今日の仕事を紹介してくれたのはクリスなんだ。
194 = "気にするな。\\n今日の仕事を紹介してくれたのはクリスなんだ。"

# ダクネス
# それに、これは私個人のわがままだが、\n久し振りにゆっくり話す時間を\n作りたいと思ってな。
170 = "それに、これは私個人のわがままだが、\\n久し振りにゆっくり話す時間を\\n作りたいと思ってな。"

# クリス
# なんだ、そんなの言ってくれたら\nすぐに作るのに。
178 = "なんだ、そんなの言ってくれたら\\nすぐに作るのに。"

# カズマ
# ２人って、本当に仲がいいんだなぁ。\n親友なんだったよな？
229 = "２人って、本当に仲がいいんだなぁ。\\n親友なんだったよな？"

# ダクネス
# ま、まあな。\n少なくとも私は……そう思っている。
181 = "ま、まあな。\\n少なくとも私は……そう思っている。"

# クリス
# もちろん、あたしだって思ってるよ。
183 = "もちろん、あたしだって思ってるよ。"

# ダクネス
# そ、そうか！
167 = "そ、そうか！"

# カズマ（Ｍ）
# display as カズマ
# （おいおい、見ててむずがゆくなるぞ、これ。\n　まあ、悪いもんじゃないけどさ）
222 = "（おいおい、見ててむずがゆくなるぞ、これ。\\n　まあ、悪いもんじゃないけどさ）"

# カズマ
# でも、クリスはよくダクネスについて行けるな。
174 = "でも、クリスはよくダクネスについて行けるな。"

# クリス
# うん？　どうして？
158 = "うん？　どうして？"

# カズマ
# どうしてって……言わなくてもわかるだろ？
176 = "どうしてって……言わなくてもわかるだろ？"

# クリス
# まあね。\nでも別にどってことないよ。\n人には誰しも色々な面があるものだしさ。
182 = "まあね。\\nでも別にどってことないよ。\\n人には誰しも色々な面があるものだしさ。"

# クリス
# ちょっと困ったところも含めて、\n全部が私の親友なんだから。
172 = "ちょっと困ったところも含めて、\\n全部が私の親友なんだから。"

# ダクネス
# クリス……。
188 = "クリス……。"

# カズマ
# けど、ダクネスには色々ありすぎだろ。\nただでさえキャラが濃いのに、\nこの上お嬢様とか、どんだけだってんだよ。
163 = "けど、ダクネスには色々ありすぎだろ。\\nただでさえキャラが濃いのに、\\nこの上お嬢様とか、どんだけだってんだよ。"

# ダクネス
# お、おい！
159 = "お、おい！"

# カズマ
# ひらひらのドレスとか着ちゃってさ。\n初めて見た時、驚いたのなんのって。
180 = "ひらひらのドレスとか着ちゃってさ。\\n初めて見た時、驚いたのなんのって。"

# ダクネス
# なあっ！？\nひ、ひ、ひ、ひらひらひらひらっ！？
177 = "なあっ！？\\nひ、ひ、ひ、ひらひらひらひらっ！？"

# カズマ
# お、おお？\nどうしたんだよ、ダクネス。
160 = "お、おお？\\nどうしたんだよ、ダクネス。"

# ダクネス
# %fsyogen;こ、これはもしや私を辱めているのか？\nひらひらでピンクとか……言う気か！？
12 = "%fsyogen;こ、これはもしや私を辱めているのか？\\nひらひらでピンクとか……言う気か！？"

# カズマ（Ｍ）
# display as カズマ
# （ひらひら……ピンク）
225 = "（ひらひら……ピンク）"

# カズマ（Ｍ）
# display as カズマ
# （うん、証言としてゲット）
221 = "（うん、証言としてゲット）"

# クリス
# ちょ、ちょっと！\nなに口走ってるの、ダクネス！
171 = "ちょ、ちょっと！\\nなに口走ってるの、ダクネス！"

# ダクネス
# 止めてくれるなクリス！\n口撃だろうと受けとめてこそのクルセイダーだ。
193 = "止めてくれるなクリス！\\n口撃だろうと受けとめてこそのクルセイダーだ。"

# カズマ
# いやいや、お前のクルセイダーの認識、\nなんかおかしいぞ。
155 = "いやいや、お前のクルセイダーの認識、\\nなんかおかしいぞ。"

# クリス
# そ、そういえばさ！\n今日はキミ達の仕事も上手くいったんだってね？
166 = "そ、そういえばさ！\\n今日はキミ達の仕事も上手くいったんだってね？"

# カズマ
# あ、ああ、まあな。
151 = "あ、ああ、まあな。"

# クリス
# このままコツコツ頑張っていけば、\n３０００万エリスもいけそうじゃない？
165 = "このままコツコツ頑張っていけば、\\n３０００万エリスもいけそうじゃない？"

# カズマ
# そうだなぁ。\n確かに俺も手ごたえは感じてるよ。
168 = "そうだなぁ。\\n確かに俺も手ごたえは感じてるよ。"

# クリス
# でしょ？\nあたしもなんだよね。
173 = "でしょ？\\nあたしもなんだよね。"

# ダクネス
# うむ、この意気で進もう。\n私も、より危険なクエストでもなんでも\nチャレンジしていくからな。
156 = "うむ、この意気で進もう。\\n私も、より危険なクエストでもなんでも\\nチャレンジしていくからな。"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスの場合は半分くらいは趣味だろ。\n　まあ、その気持ちは……嬉しいけどさ）
228 = "（ダクネスの場合は半分くらいは趣味だろ。\\n　まあ、その気持ちは……嬉しいけどさ）"

# クリス
# それじゃ、あたし達はそろそろ寝るよ。\nキミも、明日があるんだし早く寝たほうがいいよ。
169 = "それじゃ、あたし達はそろそろ寝るよ。\\nキミも、明日があるんだし早く寝たほうがいいよ。"

# カズマ
# ああ、おやすみ。
152 = "ああ、おやすみ。"

# クリス
# おやすみ。
162 = "おやすみ。"

# ダクネス
# おやすみ、カズマ。
161 = "おやすみ、カズマ。"

# カズマ（Ｍ）
# display as カズマ
# （……そうか。\n　やっぱり、コツコツやるのが一番だったんだな。\n　俺達はとんだ遠回りをしていたんだ）
219 = "（……そうか。\\n　やっぱり、コツコツやるのが一番だったんだな。\\n　俺達はとんだ遠回りをしていたんだ）"

# カズマ（Ｍ）
# display as カズマ
# （よし！　明日からも頑張るぞ！\n　そしていつか、この指輪の呪いから\n　解き放たれた時――）
226 = "（よし！　明日からも頑張るぞ！\\n　そしていつか、この指輪の呪いから\\n　解き放たれた時――）"

# カズマ（Ｍ）
# display as カズマ
# （この素晴らしい仲間達と、自由を祝うんだ！）
223 = "（この素晴らしい仲間達と、自由を祝うんだ！）"

