# st05b_03.txt.scn

[info]
0 = ""

[characters]
217 = "ダクネス"
206 = "めぐみん"
209 = "ゆんゆん"
214 = "カズマ"
213 = "ウィズ"
215 = "カズマ（Ｍ）"
216 = "クリス"
219 = "バニル"
212 = "アクア"

[character_subs]
# 214 = "カズマ"

[script]
# lines: 58

# ダクネス
# とにかく、やるしかないようだな。
196 = "とにかく、やるしかないようだな。"

# めぐみん
# はあ、そのようですね。
200 = "はあ、そのようですね。"

# ゆんゆん
# ほ、本当に倒せるんですか？
203 = "ほ、本当に倒せるんですか？"

# カズマ
# 大丈夫だ！\n俺たちにはウィズがいるじゃないか！
227 = "大丈夫だ！\\n俺たちにはウィズがいるじゃないか！"

# ウィズ
# ええ、どうして私なんですか！？
174 = "ええ、どうして私なんですか！？"

# カズマ
# だってウィズならあいつに勝てるんだろ？
192 = "だってウィズならあいつに勝てるんだろ？"

# ウィズ
# 否定はしませんが、相手はスカルドラゴンですよ？
226 = "否定はしませんが、相手はスカルドラゴンですよ？"

# ウィズ
# 力の差はそれほどありませんので、\n戦いが長くなると思います。
223 = "力の差はそれほどありませんので、\\n戦いが長くなると思います。"

# ウィズ
# 当然、街を守りながら戦うなんて余裕も持てません。
230 = "当然、街を守りながら戦うなんて余裕も持てません。"

# カズマ
# そ、そんな……。
184 = "そ、そんな……。"

# めぐみん
# ふっふっふ、何を恐れるというのだ。
202 = "ふっふっふ、何を恐れるというのだ。"

# カズマ
# は？
201 = "は？"

# めぐみん
# 我が力であの呪われた竜を屠る時が来た、\nふっ、それだけのこと！
231 = "我が力であの呪われた竜を屠る時が来た、\\nふっ、それだけのこと！"

# カズマ（Ｍ）
# display as カズマ
# （なんでこんな時に厨二病モードになるんだよ）
273 = "（なんでこんな時に厨二病モードになるんだよ）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、このパターンだとこいつは……）
269 = "（ああ、このパターンだとこいつは……）"

# ダクネス
# それで、どうするんだカズマ。
188 = "それで、どうするんだカズマ。"

# カズマ
# あれ、まともだ。
172 = "あれ、まともだ。"

# ダクネス
# こんなときにふざけていられるか。\n民衆の命が脅かされているのだぞ。
180 = "こんなときにふざけていられるか。\\n民衆の命が脅かされているのだぞ。"

# カズマ
# そうだよな。\nこのままだと街がスカルドラゴンに\n蹂躙されるんだもんな。
186 = "そうだよな。\\nこのままだと街がスカルドラゴンに\\n蹂躙されるんだもんな。"

# ダクネス
# 蹂躙！？
267 = "蹂躙！？"

# カズマ（Ｍ）
# display as カズマ
# （ん？）
274 = "（ん？）"

# ダクネス
# あっ、いや、こほん……な、なんでもない。
170 = "あっ、いや、こほん……な、なんでもない。"

# カズマ（Ｍ）
# display as カズマ
# （この真性ドＭ騎士めっ！）
272 = "（この真性ドＭ騎士めっ！）"

# クリス
# じゃあ、整理するよ。\n街の近くで戦うんだから、もちろん長期戦はダメ。
183 = "じゃあ、整理するよ。\\n街の近くで戦うんだから、もちろん長期戦はダメ。"

# ダクネス
# そうだな、民衆に死者を出すわけにはいかない。
185 = "そうだな、民衆に死者を出すわけにはいかない。"

# クリス
# だったらやっぱり高火力で一発撃破になるか。
190 = "だったらやっぱり高火力で一発撃破になるか。"

# カズマ
# デストロイヤーの時みたいにだな。
218 = "デストロイヤーの時みたいにだな。"

# ゆんゆん
# 相手はアンデッドですから、\n火属性の魔法との相性は悪くないですね。
265 = "相手はアンデッドですから、\\n火属性の魔法との相性は悪くないですね。"

# カズマ
# おお！？\nだったらめぐみんとウィズで\n爆裂魔法をぶち込めば！
177 = "おお！？\\nだったらめぐみんとウィズで\\n爆裂魔法をぶち込めば！"

# ウィズ
# ですが、やはり相手はスカルドラゴンなんです。
195 = "ですが、やはり相手はスカルドラゴンなんです。"

# カズマ
# え、あいつってそんな強いの？
173 = "え、あいつってそんな強いの？"

# バニル
# さらに付け加えるなら、\n生前はエンシェントドラゴンと呼ばれていた。
181 = "さらに付け加えるなら、\\n生前はエンシェントドラゴンと呼ばれていた。"

# めぐみん
# な、なんですとー！
197 = "な、なんですとー！"

# カズマ
# ちょっと待て、あいつってそんなバケモノなのか！
193 = "ちょっと待て、あいつってそんなバケモノなのか！"

# めぐみん
# まさかエンシェントドラゴンに爆裂魔法を\n撃ち込める日が来ようとは、ふふふ、燃えますね！
205 = "まさかエンシェントドラゴンに爆裂魔法を\\n撃ち込める日が来ようとは、ふふふ、燃えますね！"

# カズマ（Ｍ）
# display as カズマ
# （あっ、そっちの驚きね）
270 = "（あっ、そっちの驚きね）"

# ウィズ
# めぐみんさんの盛り上がりは置いておきまして、\n爆裂魔法を２発撃ち込んでも、\n動きを止めることが限界かと思います。
207 = "めぐみんさんの盛り上がりは置いておきまして、\\n爆裂魔法を２発撃ち込んでも、\\n動きを止めることが限界かと思います。"

# カズマ
# じゃあ、どうすれば……。
182 = "じゃあ、どうすれば……。"

# ウィズ
# ええと、悩むことですか？
175 = "ええと、悩むことですか？"

# カズマ
# だって、この街の最大火力は爆裂魔法なんだろ？
191 = "だって、この街の最大火力は爆裂魔法なんだろ？"

# ウィズ
# 確かにスカルドラゴンは強敵ですが、\nアンデッドなんですよ？
266 = "確かにスカルドラゴンは強敵ですが、\\nアンデッドなんですよ？"

# カズマ
# だからなんだよ。
189 = "だからなんだよ。"

# ウィズ
# ですから。
194 = "ですから。"

# アクア
# ねえねえ、カズマ。
199 = "ねえねえ、カズマ。"

# カズマ（Ｍ）
# display as カズマ
# （あ……）
268 = "（あ……）"

# アクア
# これ、レアアイテムが入ってるかもしれない\n古い箱ですって。面白そうだし買ってみない？
179 = "これ、レアアイテムが入ってるかもしれない\\n古い箱ですって。面白そうだし買ってみない？"

# カズマ
# お前がいた……。
178 = "お前がいた……。"

# アクア
# え？　私がどうかしたの？
176 = "え？　私がどうかしたの？"

# カズマ
# そうだよ！\nすっかり忘れてたけどお前がいたじゃないか！
187 = "そうだよ！\\nすっかり忘れてたけどお前がいたじゃないか！"

# アクア
# もう、大声出さないでよ。\n耳が痛くなるじゃない。
208 = "もう、大声出さないでよ。\\n耳が痛くなるじゃない。"

# カズマ
# よし、一気に勝ち目が出てきたぞ！
211 = "よし、一気に勝ち目が出てきたぞ！"

# クリス
# ほら、あんまりここでのんびりもしてられないよ。
204 = "ほら、あんまりここでのんびりもしてられないよ。"

# カズマ（Ｍ）
# display as カズマ
# （おっと、そうだった）
271 = "（おっと、そうだった）"

# ダクネス
# よし、それじゃあギルドに戻るか。
210 = "よし、それじゃあギルドに戻るか。"

# カズマ
# バニル邪魔したな。\nあと、サンキュー、助かったよ。
220 = "バニル邪魔したな。\\nあと、サンキュー、助かったよ。"

# アクア
# ねえ、ちょっとカズマ。\n私がいるからなんなのよ。
198 = "ねえ、ちょっとカズマ。\\n私がいるからなんなのよ。"

# カズマ
# あとで説明するって。
171 = "あとで説明するって。"

# バニル
# 先を見通せないこと。\nそれもまた人間の愚かな所なり。
222 = "先を見通せないこと。\\nそれもまた人間の愚かな所なり。"

