# st05a_06.txt.scn

[info]
0 = ""

[characters]
261 = "ダクネス"
246 = "めぐみん"
256 = "アクア"
257 = "カズマ"
259 = "カズマ（Ｍ）"
260 = "クリス"
252 = "ゆんゆん"

[character_subs]
# 257 = "カズマ"

[script]
# lines: 89

# ダクネス
# やはりバニルを説得するのは無理だったか。
250 = "やはりバニルを説得するのは無理だったか。"

# めぐみん
# どうするんですか？\nこれでは、カズマの呪いを解くなんて\n絶対に無理ですよ。
232 = "どうするんですか？\\nこれでは、カズマの呪いを解くなんて\\n絶対に無理ですよ。"

# アクア
# ねえ、カズマ。\n指なら私が再生させるから、\nもうズバッといっちゃわない？
239 = "ねえ、カズマ。\\n指なら私が再生させるから、\\nもうズバッといっちゃわない？"

# カズマ
# 気軽にとんでもねーことを言うなっ！
275 = "気軽にとんでもねーことを言うなっ！"

# ダクネス
# ……ん？\nあれはクリスじゃないか？
205 = "……ん？\\nあれはクリスじゃないか？"

# カズマ
# ああ、本当だ。\nしかも横にいるのって、ゆんゆんだよな。
210 = "ああ、本当だ。\\nしかも横にいるのって、ゆんゆんだよな。"

# アクア
# へえ、珍しい組み合わせね。\nひょっとして、前の洞窟調査の一件で\n仲良くなったのかしら？
242 = "へえ、珍しい組み合わせね。\\nひょっとして、前の洞窟調査の一件で\\n仲良くなったのかしら？"

# めぐみん
# かもしれませんね。
220 = "かもしれませんね。"

# カズマ
# せっかくだ、声をかけてみるか。
222 = "せっかくだ、声をかけてみるか。"

# めぐみん
# やめておきましょう。\nあのぼっちにようやく友人ができたのですからね。\nええ、そっとしておくべきです。
251 = "やめておきましょう。\\nあのぼっちにようやく友人ができたのですからね。\\nええ、そっとしておくべきです。"

# カズマ（Ｍ）
# display as カズマ
# （とか言いながら、明らかに\n　気になるって顔に書いてあるよなぁ）
344 = "（とか言いながら、明らかに\\n　気になるって顔に書いてあるよなぁ）"

# カズマ
# まあ、いいじゃん。\n挨拶くらいしとこうぜ。
243 = "まあ、いいじゃん。\\n挨拶くらいしとこうぜ。"

# めぐみん
# あ、ちょっと、カズマ！？
209 = "あ、ちょっと、カズマ！？"

# カズマ（Ｍ）
# display as カズマ
# （にしても、なにを話してるんだ？\n　ずいぶん熱心に話しこんでるみたいだけど）
347 = "（にしても、なにを話してるんだ？\\n　ずいぶん熱心に話しこんでるみたいだけど）"

# クリス
# やっぱりここは先手必勝だと思うんだよね。
249 = "やっぱりここは先手必勝だと思うんだよね。"

# ゆんゆん
# つまり、こちらから打って出るってことですか？
231 = "つまり、こちらから打って出るってことですか？"

# クリス
# そう、ここは攻めに転じるべきだよ。\n夜のうちに屋敷に侵入して、\n例の物を持ち出してしまえばいい。
226 = "そう、ここは攻めに転じるべきだよ。\\n夜のうちに屋敷に侵入して、\\n例の物を持ち出してしまえばいい。"

# クリス
# あたし達２人でならやれると思うんだけど、\nどうかな？
211 = "あたし達２人でならやれると思うんだけど、\\nどうかな？"

# カズマ
# ……聞いたか、めぐみん。
206 = "……聞いたか、めぐみん。"

# めぐみん
# ええ、聞きました。\n物騒な話をしてましたね。
216 = "ええ、聞きました。\\n物騒な話をしてましたね。"

# めぐみん
# もしかして、あのぼっちに\n妙なことを吹き込んでいるんじゃ。
248 = "もしかして、あのぼっちに\\n妙なことを吹き込んでいるんじゃ。"

# ゆんゆん
# わかりました！\n私、クリスさんに協力して――
255 = "わかりました！\\n私、クリスさんに協力して――"

# めぐみん
# 協力して、何をするつもりなんですか？\nまさか犯罪に手を染めるつもりなんですか？
265 = "協力して、何をするつもりなんですか？\\nまさか犯罪に手を染めるつもりなんですか？"

# ゆんゆん
# ひゃあああっ！？
241 = "ひゃあああっ！？"

# クリス
# め、めぐみん！\nそれにカズマもっ！　なんで！？
245 = "め、めぐみん！\\nそれにカズマもっ！　なんで！？"

# めぐみん
# なんでもなにも、ここは天下の往来ですよ？\n誰がどこにいても問題はありません。
237 = "なんでもなにも、ここは天下の往来ですよ？\\n誰がどこにいても問題はありません。"

# クリス
# あ、ああ、うん、そうなんだけど。
207 = "あ、ああ、うん、そうなんだけど。"

# ゆんゆん
# あ、そうだ、めぐみん！\nここで会ったが１００年目！\n今日こそ決着の刻よっ！
208 = "あ、そうだ、めぐみん！\\nここで会ったが１００年目！\\n今日こそ決着の刻よっ！"

# めぐみん
# なんですか、その取って付けたような言い方は。\nずいぶんと雑ですね。\n私との勝負はその程度の扱いなわけですか。
235 = "なんですか、その取って付けたような言い方は。\\nずいぶんと雑ですね。\\n私との勝負はその程度の扱いなわけですか。"

# ゆんゆん
# ええっ！？\nそんなつもりはなかったんだけど……\nでも、こうしないと変だって思われそうだし。
217 = "ええっ！？\\nそんなつもりはなかったんだけど……\\nでも、こうしないと変だって思われそうだし。"

# めぐみん
# 何が変なのですか、何が。
263 = "何が変なのですか、何が。"

# ゆんゆん
# それは、その、うう、クリスさん。
230 = "それは、その、うう、クリスさん。"

# クリス
# いや、ごめん。\n今のタイミングで助けを求められても\nフォローのしようがないから。
214 = "いや、ごめん。\\n今のタイミングで助けを求められても\\nフォローのしようがないから。"

# ゆんゆん
# そ、そんなぁ！？
225 = "そ、そんなぁ！？"

# ダクネス
# うーん、めぐみんだけではなく、\nクリスの様子もどことなくおかしいな。
215 = "うーん、めぐみんだけではなく、\\nクリスの様子もどことなくおかしいな。"

# クリス
# そ、そうかな？
223 = "そ、そうかな？"

# カズマ（Ｍ）
# display as カズマ
# （俺は知っているぞ。\n　あのクリスの視線の意味を俺は知っている！）
351 = "（俺は知っているぞ。\\n　あのクリスの視線の意味を俺は知っている！）"

# カズマ（Ｍ）
# display as カズマ
# （そう、それは！\n　前回の満月にパンツを取ってしまった時、\n　俺に向けられていた蔑みの視線と同じだ！）
336 = "（そう、それは！\\n　前回の満月にパンツを取ってしまった時、\\n　俺に向けられていた蔑みの視線と同じだ！）"

# カズマ（Ｍ）
# display as カズマ
# （つまり、この５枚のうちの１枚は\n　クリスの物ってことか）
341 = "（つまり、この５枚のうちの１枚は\\n　クリスの物ってことか）"

# クリス
# ……どうしたの？\nこっちをじっと見て。\n何か言いたいことでもあるの？
203 = "……どうしたの？\\nこっちをじっと見て。\\n何か言いたいことでもあるの？"

# カズマ
# い、いやぁ、なんでもないですよ？
213 = "い、いやぁ、なんでもないですよ？"

# カズマ（Ｍ）
# display as カズマ
# （あ、そうか！\n　さっき、ゆんゆんと言ってたのって、\n　このパンツを取り返す相談か！）
327 = "（あ、そうか！\\n　さっき、ゆんゆんと言ってたのって、\\n　このパンツを取り返す相談か！）"

# カズマ（Ｍ）
# display as カズマ
# （となると、残りの１枚は\n　ゆんゆんの物なんだな）
345 = "（となると、残りの１枚は\\n　ゆんゆんの物なんだな）"

# カズマ（Ｍ）
# display as カズマ
# （つまり、今、俺のポケットに入っている\n　パンツの持ち主のうち、\n　４人が目の前にいるわけか）
342 = "（つまり、今、俺のポケットに入っている\\n　パンツの持ち主のうち、\\n　４人が目の前にいるわけか）"

# カズマ（Ｍ）
# display as カズマ
# （そう思うと……\n　一体なんのプレイだって感じだな、この状況）
337 = "（そう思うと……\\n　一体なんのプレイだって感じだな、この状況）"

# めぐみん
# それで、どこに何を盗りに行くんですか？\n事情によっては全力で通報しますよ？
229 = "それで、どこに何を盗りに行くんですか？\\n事情によっては全力で通報しますよ？"

# ゆんゆん
# そ、それはその、ええと……。
224 = "そ、それはその、ええと……。"

# カズマ（Ｍ）
# display as カズマ
# （き、気まずい！\n　これはマジで気まずい！）
331 = "（き、気まずい！\\n　これはマジで気まずい！）"

# カズマ（Ｍ）
# display as カズマ
# （今までとは違う、お互いに盗ってる、\n　盗られてるわかってる状況だと\n　ここまで気まずくなるものなのか！）
350 = "（今までとは違う、お互いに盗ってる、\\n　盗られてるわかってる状況だと\\n　ここまで気まずくなるものなのか！）"

# カズマ（Ｍ）
# display as カズマ
# （これはもう、パンツ裁判だとか\n　言ってる場合じゃないぞ）
335 = "（これはもう、パンツ裁判だとか\\n　言ってる場合じゃないぞ）"

# カズマ（Ｍ）
# display as カズマ
# （第一、誰の物かはもうバレバレなんだし\n　裁判の意味もない！\n　ここですぐに返して――）
353 = "（第一、誰の物かはもうバレバレなんだし\\n　裁判の意味もない！\\n　ここですぐに返して――）"

# カズマ（Ｍ）
# display as カズマ
# （いや、待て。\n　よく考えるんだ、俺。\n　そこで妥協するのは紳士ではないぞ）
328 = "（いや、待て。\\n　よく考えるんだ、俺。\\n　そこで妥協するのは紳士ではないぞ）"

# カズマ（Ｍ）
# display as カズマ
# （確かに、この５枚のパンツの持ち主は\n　めぐみん、ダクネス、ゆんゆん、\n　それにウィズとクリスで間違いないだろう）
352 = "（確かに、この５枚のパンツの持ち主は\\n　めぐみん、ダクネス、ゆんゆん、\\n　それにウィズとクリスで間違いないだろう）"

# カズマ（Ｍ）
# display as カズマ
# （だが！　どれが誰の物であるかは\n　わからないまま！）
339 = "（だが！　どれが誰の物であるかは\\n　わからないまま！）"

# カズマ（Ｍ）
# display as カズマ
# （紳士カズマ、我は己に問いかける）
354 = "（紳士カズマ、我は己に問いかける）"

# カズマ（Ｍ）
# display as カズマ
# （間違ったパンツを返して、\n　真の紳士と言えるのか！）
355 = "（間違ったパンツを返して、\\n　真の紳士と言えるのか！）"

# カズマ（Ｍ）
# display as カズマ
# （いや、言えない！　言えるわけがない！）
329 = "（いや、言えない！　言えるわけがない！）"

# カズマ（Ｍ）
# display as カズマ
# （つまり今回は、誰が盗まれているのかを\n　突き止めるのではなく――）
343 = "（つまり今回は、誰が盗まれているのかを\\n　突き止めるのではなく――）"

# カズマ（Ｍ）
# display as カズマ
# （どのパンツが誰の物であるか！\n　この真実をつきとめるべき！）
346 = "（どのパンツが誰の物であるか！\\n　この真実をつきとめるべき！）"

# カズマ（Ｍ）
# display as カズマ
# （うむ、そうだ！　そうしよう！\n　そこまでやって初めて俺は\n　真の紳士として胸を張ることができるんだ！）
330 = "（うむ、そうだ！　そうしよう！\\n　そこまでやって初めて俺は\\n　真の紳士として胸を張ることができるんだ！）"

# ダクネス
# おい、カズマが良からぬことを\n考えているようだが。
218 = "おい、カズマが良からぬことを\\n考えているようだが。"

# クリス
# ……なんだろう。\n嫌な予感がひしひしとするよ。
204 = "……なんだろう。\\n嫌な予感がひしひしとするよ。"

# めぐみん
# 同感です。\nいっそ、爆裂魔法で笑顔ごと吹き飛ばしますか？
269 = "同感です。\\nいっそ、爆裂魔法で笑顔ごと吹き飛ばしますか？"

# ゆんゆん
# それって死んじゃうよ！？
228 = "それって死んじゃうよ！？"

# カズマ
# はっ！？\nお前ら、とてつもなく\n物騒な相談をしてなかったか！？
240 = "はっ！？\\nお前ら、とてつもなく\\n物騒な相談をしてなかったか！？"

# アクア
# カズマこそ、変なこと考えてたんじゃないの？
258 = "カズマこそ、変なこと考えてたんじゃないの？"

# カズマ
# な、何も考えてねーし。
233 = "な、何も考えてねーし。"

# ゆんゆん
# なんでもないのにニヤニヤするのって、\nそれはそれで気味が悪いです……。
236 = "なんでもないのにニヤニヤするのって、\\nそれはそれで気味が悪いです……。"

# カズマ
# ゆんゆん、割とひどいこと言うね？
253 = "ゆんゆん、割とひどいこと言うね？"

# ゆんゆん
# あっ、す、すみません！
212 = "あっ、す、すみません！"

# めぐみん
# 謝る必要はありませんよ。\n全て事実なのですから。
325 = "謝る必要はありませんよ。\\n全て事実なのですから。"

# カズマ（Ｍ）
# display as カズマ
# （くっ……。\n　こいつら、どいつもこいつも容赦ないな）
332 = "（くっ……。\\n　こいつら、どいつもこいつも容赦ないな）"

# カズマ（Ｍ）
# display as カズマ
# （だが、そんなことで\n　俺は紳士の行いを諦めはしないぜ？）
338 = "（だが、そんなことで\\n　俺は紳士の行いを諦めはしないぜ？）"

# カズマ（Ｍ）
# display as カズマ
# （ここからは、注意深くみんなを観察して\n　どのパンツが誰の物なのか\n　ヒントを見つけ出さなくては）
334 = "（ここからは、注意深くみんなを観察して\\n　どのパンツが誰の物なのか\\n　ヒントを見つけ出さなくては）"

# カズマ（Ｍ）
# display as カズマ
# （ふふふ、じっくり観察させてもらおう。\n　くくくくく、裁判でお前らが\n　どんな顔をするのかが楽しみだぜ）
348 = "（ふふふ、じっくり観察させてもらおう。\\n　くくくくく、裁判でお前らが\\n　どんな顔をするのかが楽しみだぜ）"

# アクア
# また変な顔してるわよ、あの男。
244 = "また変な顔してるわよ、あの男。"

# クリス
# もう放っておこう。\nそれよりさダクネス、お金の問題ってどうなの？
247 = "もう放っておこう。\\nそれよりさダクネス、お金の問題ってどうなの？"

# クリス
# 前回はあたしも手伝ったけど、\n結局、収入ゼロだったわけだし。
264 = "前回はあたしも手伝ったけど、\\n結局、収入ゼロだったわけだし。"

# ダクネス
# 正直言って手詰まりなんだ。\nバニルに値引き交渉もしたんだが、\nいい返事はもらえなかった。
274 = "正直言って手詰まりなんだ。\\nバニルに値引き交渉もしたんだが、\\nいい返事はもらえなかった。"

# クリス
# なるほど。\nいつになったら呪いが解けるのかわからない、\n相変わらずの状態なわけだね。
234 = "なるほど。\\nいつになったら呪いが解けるのかわからない、\\n相変わらずの状態なわけだね。"

# カズマ（Ｍ）
# display as カズマ
# （……クリスさん、視線が痛いです）
326 = "（……クリスさん、視線が痛いです）"

# クリス
# じゃあ、私も手伝うよ。\n何か思いつくことがあるかもしれないし。
221 = "じゃあ、私も手伝うよ。\\n何か思いつくことがあるかもしれないし。"

# ゆんゆん
# わ、私も！\nお手伝いします！
254 = "わ、私も！\\nお手伝いします！"

# カズマ
# おう、助かるぜ。
219 = "おう、助かるぜ。"

# カズマ（Ｍ）
# display as カズマ
# （よしよし、これでパンツの手がかりが\n　ゲットできそうだな！）
349 = "（よしよし、これでパンツの手がかりが\\n　ゲットできそうだな！）"

# カズマ（Ｍ）
# display as カズマ
# （って、待て？\n　俺、本来の目的を忘れてないか？\n　金を稼がないと呪いが解けないんだぞ！？）
340 = "（って、待て？\\n　俺、本来の目的を忘れてないか？\\n　金を稼がないと呪いが解けないんだぞ！？）"

# カズマ（Ｍ）
# display as カズマ
# （くっ！\n　俺の心を惑わす罪深きパンツめ……）
333 = "（くっ！\\n　俺の心を惑わす罪深きパンツめ……）"

# アクア
# ねえ、また１人で顔芸してるわよ、あの男。
238 = "ねえ、また１人で顔芸してるわよ、あの男。"

# クリス
# そっとしておこう。\nきっと、そんな年頃なんだよ。
227 = "そっとしておこう。\\nきっと、そんな年頃なんだよ。"

