# st05c_02.txt.scn

[info]
0 = ""

[characters]
429 = "カズマ（Ｍ）"
425 = "カズマ"
430 = "キース"
444 = "ダスト"
404 = "めぐみん"
408 = "ゆんゆん"
417 = "アクア"
431 = "クリス"
420 = "ウィズ"
439 = "ダクネス"
435 = "スカルドラゴン"
406 = "めぐみん＆ウィズ"
469 = "戦士風の男冒険者"
544 = "魔術師風の男冒険者"

[character_subs]
# 425 = "カズマ"
468 = "戦士冒険者"
543 = "魔術師冒険者"

[script]
# lines: 159

# カズマ（Ｍ）
# display as カズマ
# （数時間後――\n　迎撃地点になった草原に、\n　冒険者達が勢揃いしていた）
568 = "（数時間後――\\n　迎撃地点になった草原に、\\n　冒険者達が勢揃いしていた）"

# カズマ
# まさか、こんなに集まってくれるとは\n思わなかったぜ。
402 = "まさか、こんなに集まってくれるとは\\n思わなかったぜ。"

# キース
# いや、当然だろ？\nみんな、あの街が好きで\n守りたいって思ってるんだからさ。
339 = "いや、当然だろ？\\nみんな、あの街が好きで\\n守りたいって思ってるんだからさ。"

# カズマ（Ｍ）
# display as カズマ
# （いや、お前が守りたいのは\n　サキュバスの店だろ……）
547 = "（いや、お前が守りたいのは\\n　サキュバスの店だろ……）"

# ダスト
# なあ、スカルドラゴンはまだなのか？\n待ちくたびれちまうよ。
385 = "なあ、スカルドラゴンはまだなのか？\\n待ちくたびれちまうよ。"

# カズマ
# なに格好つけてんだよ。\n本当は来ないでくれーとか思ってんじゃねーのか？
386 = "なに格好つけてんだよ。\\n本当は来ないでくれーとか思ってんじゃねーのか？"

# ダスト
# そ、そんなことない！
364 = "そ、そんなことない！"

# カズマ（Ｍ）
# display as カズマ
# （やれやれ、緊張感の欠片も無いな）
565 = "（やれやれ、緊張感の欠片も無いな）"

# カズマ（Ｍ）
# display as カズマ
# （それに比べて……）
557 = "（それに比べて……）"

# めぐみん
# 私はできる、私はできる。\nそう、私はやれば出来る子……。
536 = "私はできる、私はできる。\\nそう、私はやれば出来る子……。"

# カズマ
# おい、めぐみん。
352 = "おい、めぐみん。"

# めぐみん
# 来ましたか！　来たんですね！
470 = "来ましたか！　来たんですね！"

# カズマ
# 違う、違う。\nお前、そんなに緊張してたらこの先もたないぞ。
541 = "違う、違う。\\nお前、そんなに緊張してたらこの先もたないぞ。"

# めぐみん
# カズマ、もう緊張などという\nレベルじゃないんですよ。
426 = "カズマ、もう緊張などという\\nレベルじゃないんですよ。"

# めぐみん
# なんかもう色々超越していて、\n嘔吐感がやばいです。うぷ。
387 = "なんかもう色々超越していて、\\n嘔吐感がやばいです。うぷ。"

# カズマ
# 吐くなよ？
460 = "吐くなよ？"

# ゆんゆん
# 私はできる、私はできる。\nそう、私はできる子なの。
535 = "私はできる、私はできる。\\nそう、私はできる子なの。"

# カズマ（Ｍ）
# display as カズマ
# （こっちもか……）
555 = "（こっちもか……）"

# めぐみん
# ちょっとゆんゆん大丈夫なんですか？\n爆裂魔法をあてられるかどうかは、\nあなたの活躍にかかっているんですよ。
377 = "ちょっとゆんゆん大丈夫なんですか？\\n爆裂魔法をあてられるかどうかは、\\nあなたの活躍にかかっているんですよ。"

# ゆんゆん
# わ、私の活躍！？
412 = "わ、私の活躍！？"

# めぐみん
# そうです。あなたの活躍です。
367 = "そうです。あなたの活躍です。"

# めぐみん
# ゆんゆんがもししくじれば、\nそこから負の連鎖が始まり、この街は……。
409 = "ゆんゆんがもししくじれば、\\nそこから負の連鎖が始まり、この街は……。"

# ゆんゆん
# うぅ、気持ち悪い。
342 = "うぅ、気持ち悪い。"

# カズマ
# お前はバカかー！\n何やってんだ！
356 = "お前はバカかー！\\n何やってんだ！"

# めぐみん
# 緊張って移るっていうじゃないですか。\nだからゆんゆんを緊張させれば体の強ばりが\n解けるかなと思いまして。
539 = "緊張って移るっていうじゃないですか。\\nだからゆんゆんを緊張させれば体の強ばりが\\n解けるかなと思いまして。"

# カズマ
# ああ、見事に緊張がほぐれてるけどさ。\n代わりにゆんゆんが……。
332 = "ああ、見事に緊張がほぐれてるけどさ。\\n代わりにゆんゆんが……。"

# めぐみん
# この子だったら、大丈夫ですよ。
359 = "この子だったら、大丈夫ですよ。"

# ゆんゆん
# 私を信じてくれてるんだね、めぐみん。
537 = "私を信じてくれてるんだね、めぐみん。"

# めぐみん
# ええ、ぼっちで鍛えた精神力は\n尋常ではないと思いますので。
345 = "ええ、ぼっちで鍛えた精神力は\\n尋常ではないと思いますので。"

# ゆんゆん
# ひどいよ！
394 = "ひどいよ！"

# カズマ（Ｍ）
# display as カズマ
# （こいつ、ゆんゆんには容赦無しだな）
553 = "（こいつ、ゆんゆんには容赦無しだな）"

# カズマ（Ｍ）
# display as カズマ
# （でもまあ、ゆんゆんの緊張がほぐれて良かった）
560 = "（でもまあ、ゆんゆんの緊張がほぐれて良かった）"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんの言うとおり、ゆんゆんがしくじったら\n　それこそ作戦がおじゃんになるからな）
564 = "（めぐみんの言うとおり、ゆんゆんがしくじったら\\n　それこそ作戦がおじゃんになるからな）"

# カズマ
# で、問題はアクアだ。
378 = "で、問題はアクアだ。"

# アクア
# ん？　私がどうかした？
416 = "ん？　私がどうかした？"

# カズマ
# 緊張してるとかないだろうな。
538 = "緊張してるとかないだろうな。"

# アクア
# どうしてこの私が、\nアンデッド相手に緊張しないといけないのよ。
383 = "どうしてこの私が、\\nアンデッド相手に緊張しないといけないのよ。"

# カズマ
# いやだって、仕留められるかわからないって\n言ってただろ。
340 = "いやだって、仕留められるかわからないって\\n言ってただろ。"

# アクア
# ダクネスが言ったとおり、\nみんながダメージを与えてくれるなら\nなんとかなるんじゃない？
442 = "ダクネスが言ったとおり、\\nみんながダメージを与えてくれるなら\\nなんとかなるんじゃない？"

# アクア
# 戦力差は圧倒的ってやつよ。
467 = "戦力差は圧倒的ってやつよ。"

# カズマ
# お前はどうしてそうフラグを立てたがるんだよ！
355 = "お前はどうしてそうフラグを立てたがるんだよ！"

# アクア
# え？
346 = "え？"

# クリス
# みんな、来たよ！！
403 = "みんな、来たよ！！"

# ウィズ
# めぐみんさん、高台へ！
405 = "めぐみんさん、高台へ！"

# めぐみん
# わかりました！
414 = "わかりました！"

# ダクネス
# ハァハァハァハァ、今戻った。
447 = "ハァハァハァハァ、今戻った。"

# カズマ
# おい、そんなに息を切らせて大丈夫なのか。
351 = "おい、そんなに息を切らせて大丈夫なのか。"

# ダクネス
# 大丈夫、何も問題ない。
461 = "大丈夫、何も問題ない。"

# カズマ
# おい、お前まで変なフラグを立てるな。
350 = "おい、お前まで変なフラグを立てるな。"

# ゆんゆん
# ダクネスさん。\n私たちも前線へ！
443 = "ダクネスさん。\\n私たちも前線へ！"

# カズマ
# ２人とも気をつけてな！
570 = "２人とも気をつけてな！"

# ゆんゆん
# はい、わかっています！
392 = "はい、わかっています！"

# クリス
# もうすぐでここの上空を通過するよ！
407 = "もうすぐでここの上空を通過するよ！"

# キース
# お、おお……！　見ろ！　来たぞ！
349 = "お、おお……！　見ろ！　来たぞ！"

# カズマ（Ｍ）
# display as カズマ
# （間違いない。\n　こいつは、あの洞窟にいたドラゴンだ。\n　けど……）
569 = "（間違いない。\\n　こいつは、あの洞窟にいたドラゴンだ。\\n　けど……）"

# カズマ（Ｍ）
# display as カズマ
# （なんか迫力が３割増しくらいなんだけど！）
563 = "（なんか迫力が３割増しくらいなんだけど！）"

# スカルドラゴン
# グル……グルル……。
433 = "グル……グルル……。"

# カズマ（Ｍ）
# display as カズマ
# （くそ、俺を見てやがる。\n　やっぱりこの指輪があいつを引き寄せてるのか）
551 = "（くそ、俺を見てやがる。\\n　やっぱりこの指輪があいつを引き寄せてるのか）"

# クリス
# カズマ、ゆんゆんの準備はＯＫだよ！
427 = "カズマ、ゆんゆんの準備はＯＫだよ！"

# カズマ
# ウィズとめぐみんは！
421 = "ウィズとめぐみんは！"

# クリス
# そっちもスタンバイオッケー！
368 = "そっちもスタンバイオッケー！"

# カズマ
# よしっ、作戦開始だ！
411 = "よしっ、作戦開始だ！"

# クリス
# ふたりとも準備は？
398 = "ふたりとも準備は？"

# ダクネス
# ああ、私は大丈夫だ。\nゆんゆんは。
331 = "ああ、私は大丈夫だ。\\nゆんゆんは。"

# ゆんゆん
# ……はい、落ち着いています。
330 = "……はい、落ち着いています。"

# ダクネス
# いいか、私から決して離れるな。\n危険だと感じたら私を盾に逃げて構わない。
336 = "いいか、私から決して離れるな。\\n危険だと感じたら私を盾に逃げて構わない。"

# ゆんゆん
# でも……。
380 = "でも……。"

# ダクネス
# それが私、クルセイダーの役目だ。
369 = "それが私、クルセイダーの役目だ。"

# ゆんゆん
# わかりました！\nでも帰るときは一緒です！
415 = "わかりました！\\nでも帰るときは一緒です！"

# ダクネス
# では、いくぞ！
379 = "では、いくぞ！"

# クリス
# あっ、こっちの動きに気がついたみたいだよ！
335 = "あっ、こっちの動きに気がついたみたいだよ！"

# ゆんゆん
# （大丈夫、落ち着いて。\n　怖くない、何も怖くない。\n　ダクネスさんが守ってくれてるんだから）
567 = "（大丈夫、落ち着いて。\\n　怖くない、何も怖くない。\\n　ダクネスさんが守ってくれてるんだから）"

# クリス
# ふたりとも危ない！
397 = "ふたりとも危ない！"

# ダクネス
# はぁぁあああああああっ！
389 = "はぁぁあああああああっ！"

# クリス
# すごい、スカルドラゴンの攻撃を弾いた……。
363 = "すごい、スカルドラゴンの攻撃を弾いた……。"

# ダクネス
# ふ、ふふ、伊達に防御スキルに\nポイントを全振りしてないからな！
395 = "ふ、ふふ、伊達に防御スキルに\\nポイントを全振りしてないからな！"

# クリス
# いや、そこは誇るべき所じゃ無いからね？\nって、また来る！
338 = "いや、そこは誇るべき所じゃ無いからね？\\nって、また来る！"

# ダクネス
# はあああああああああ！！
390 = "はあああああああああ！！"

# ダクネス
# たまらん！
373 = "たまらん！"

# クリス
# な、何が！？
384 = "な、何が！？"

# ゆんゆん
# ふぅぅ……いけます。\nダクネスさん、視界を開けてください。
396 = "ふぅぅ……いけます。\\nダクネスさん、視界を開けてください。"

# ダクネス
# わかった！
413 = "わかった！"

# ゆんゆん
# ライト・オブっ！！
451 = "ライト・オブっ！！"

# ゆんゆん
# セイバーーーーーーーーーー！
437 = "セイバーーーーーーーーーー！"

# スカルドラゴン
# グウ、グウウウウウウウウウウウ！！
432 = "グウ、グウウウウウウウウウウウ！！"

# クリス
# あたったっ！
334 = "あたったっ！"

# ダクネス
# だが、きいてはいないかっ！！
375 = "だが、きいてはいないかっ！！"

# ゆんゆん
# うぅ、くぅぅぅぅっ！！\nめぐみん、長くは持たないよ！
341 = "うぅ、くぅぅぅぅっ！！\\nめぐみん、長くは持たないよ！"

# ウィズ
# ゆんゆんさん、すごい魔力ですね。
410 = "ゆんゆんさん、すごい魔力ですね。"

# めぐみん
# 当然じゃないですか。\n私の自称ライバルですよ。
465 = "当然じゃないですか。\\n私の自称ライバルですよ。"

# ウィズ
# それでは、めぐみんさん。
370 = "それでは、めぐみんさん。"

# めぐみん
# はい！
393 = "はい！"

# めぐみん
# 黒より黒く、闇より昏き漆黒に――
545 = "黒より黒く、闇より昏き漆黒に――"

# ウィズ
# 我が真紅の混淆を望みたもう――
466 = "我が真紅の混淆を望みたもう――"

# めぐみん
# 覚醒の時、来たれり――
540 = "覚醒の時、来たれり――"

# ウィズ
# 無謬の境界に堕ちし理――
474 = "無謬の境界に堕ちし理――"

# めぐみん
# 無形の歪みとなりて――
473 = "無形の歪みとなりて――"

# めぐみん＆ウィズ
# 現出せよ！
475 = "現出せよ！"

# めぐみん＆ウィズ
# エクスプローーーージョンッ！
424 = "エクスプローーーージョンッ！"

# クリス
# ダクネス、ゆんゆん来るよ！
441 = "ダクネス、ゆんゆん来るよ！"

# ゆんゆん
# あう、もう動けません。
333 = "あう、もう動けません。"

# ダクネス
# 私はいい、ゆんゆんを！
534 = "私はいい、ゆんゆんを！"

# クリス
# くっ、わかった！
358 = "くっ、わかった！"

# アクア
# 今、ダクネス逃げ遅れてなかった？
453 = "今、ダクネス逃げ遅れてなかった？"

# カズマ
# うん……。
344 = "うん……。"

# アクア
# …………。
329 = "…………。"

# カズマ
# …………。
# 329 = "…………。"

# アクア
# ま、まあ、大丈夫よね、ダクネスだし！
401 = "ま、まあ、大丈夫よね、ダクネスだし！"

# カズマ
# そうだな！　ダクネスだしな！
366 = "そうだな！　ダクネスだしな！"

# アクア
# でもこれどうするの？\n土煙があがって敵が見えないんですけど。
381 = "でもこれどうするの？\\n土煙があがって敵が見えないんですけど。"

# クリス
# ハァハァ、アクアさん！\nもう少し右、距離は約５００メートル。
446 = "ハァハァ、アクアさん！\\nもう少し右、距離は約５００メートル。"

# カズマ（Ｍ）
# display as カズマ
# （土煙が晴れて……見えたっ！）
566 = "（土煙が晴れて……見えたっ！）"

# カズマ
# アクア！　行け！
419 = "アクア！　行け！"

# アクア
# 任されたわ！
454 = "任されたわ！"

# アクア
# セイクリッド～……
436 = "セイクリッド～……"

# アクア
# ターンアンデッドォ！！
438 = "ターンアンデッドォ！！"

# スカルドラゴン
# ウガッ、ウガアアアアアアアアアアア！！
423 = "ウガッ、ウガアアアアアアアアアアア！！"

# カズマ（Ｍ）
# display as カズマ
# （うおおおおっ！？\n　こ、これがアクアの本気か！）
550 = "（うおおおおっ！？\\n　こ、これがアクアの本気か！）"

# カズマ（Ｍ）
# display as カズマ
# （でも……）
558 = "（でも……）"

# カズマ
# 浄化できてねー！
471 = "浄化できてねー！"

# アクア
# ぬぎっ、ぬぎいいいいいいい！！
388 = "ぬぎっ、ぬぎいいいいいいい！！"

# カズマ
# アクア、頑張れ！
418 = "アクア、頑張れ！"

# アクア
# 魔力が……枯れ……るぅぅ！！
542 = "魔力が……枯れ……るぅぅ！！"

# カズマ（Ｍ）
# display as カズマ
# （くそっ、無いよりマシだろ！\n　俺の魔力をくれてやる！）
552 = "（くそっ、無いよりマシだろ！\\n　俺の魔力をくれてやる！）"

# カズマ
# ドレインタッチ！！
445 = "ドレインタッチ！！"

# アクア
# うぅっ、うううっ、んぎいいいいいいい！！\n増し増しーーーーーーーーーーー！！
343 = "うぅっ、うううっ、んぎいいいいいいい！！\\n増し増しーーーーーーーーーーー！！"

# カズマ
# ど、どうなった……。
382 = "ど、どうなった……。"

# アクア
# ぷしゅぅぅ～～、もう何も出ないわ。
399 = "ぷしゅぅぅ～～、もう何も出ないわ。"

# カズマ
# 俺ももうすっからかんだ。
456 = "俺ももうすっからかんだ。"

# ダスト
# す、すっげーな！？\nこんな光、初めて見たぜ。
362 = "す、すっげーな！？\\nこんな光、初めて見たぜ。"

# キース
# これなら、いくらスカルドラゴンでも\n浄化されただろ。
360 = "これなら、いくらスカルドラゴンでも\\n浄化されただろ。"

# 戦士風の男冒険者
# display as 戦士冒険者
# 俺、これが終わったらプロポーズするんだ。\n花束はもう用意してあるし。
455 = "俺、これが終わったらプロポーズするんだ。\\n花束はもう用意してあるし。"

# 魔術師風の男冒険者
# display as 魔術師冒険者
# さあ、帰って乾杯ですね。\n今夜は飲み明かしますよ！！
361 = "さあ、帰って乾杯ですね。\\n今夜は飲み明かしますよ！！"

# カズマ
# だからぁー！\nさっきからどうしてフラグを立てたがるんだよ！
374 = "だからぁー！\\nさっきからどうしてフラグを立てたがるんだよ！"

# ダクネス
# カズマッ！　空を見ろ！
428 = "カズマッ！　空を見ろ！"

# カズマ
# ほら、やっぱり！
400 = "ほら、やっぱり！"

# アクア
# はああああ！？\nなんで浄化されてないのよ！？
391 = "はああああ！？\\nなんで浄化されてないのよ！？"

# カズマ
# それはこっちの台詞だ！
371 = "それはこっちの台詞だ！"

# ダクネス
# いかん！\nめぐみんたちの方に向かってるぞ！
337 = "いかん！\\nめぐみんたちの方に向かってるぞ！"

# スカルドラゴン
# グルルルルルァァ！！
434 = "グルルルルルァァ！！"

# カズマ
# おいアクア、もう一度だ！\n今度こそ浄化しろ！
353 = "おいアクア、もう一度だ！\\n今度こそ浄化しろ！"

# アクア
# そんなすぐに魔力は回復しないったら！
372 = "そんなすぐに魔力は回復しないったら！"

# カズマ
# く……！
357 = "く……！"

# カズマ（Ｍ）
# display as カズマ
# （どうする？\n　このままじゃ、めぐみん達がやられちまうぞ！）
561 = "（どうする？\\n　このままじゃ、めぐみん達がやられちまうぞ！）"

# カズマ（Ｍ）
# display as カズマ
# （でも、めぐみんもウィズも魔力が尽きてるから\n　爆裂魔法はもう使えない。\n　つまり足止めはできない）
559 = "（でも、めぐみんもウィズも魔力が尽きてるから\\n　爆裂魔法はもう使えない。\\n　つまり足止めはできない）"

# カズマ（Ｍ）
# display as カズマ
# （こうなったら……\n　俺ごと、この指輪を渡すしかないか）
554 = "（こうなったら……\\n　俺ごと、この指輪を渡すしかないか）"

# カズマ（Ｍ）
# display as カズマ
# （それでドラゴンが納得するかは\n　わからないが……やってみる価値はあるだろ）
556 = "（それでドラゴンが納得するかは\\n　わからないが……やってみる価値はあるだろ）"

# ダクネス
# バカなことを考えるな、カズマ。
448 = "バカなことを考えるな、カズマ。"

# カズマ
# ダクネス……？
440 = "ダクネス……？"

# ダクネス
# お前が身を差し出すことなど、誰も望んでいない。
354 = "お前が身を差し出すことなど、誰も望んでいない。"

# カズマ
# だけど、このままじゃみんなが！
376 = "だけど、このままじゃみんなが！"

# ダクネス
# %fsyogen;ここは私に任せておけ！\n仲間を守るのがクルセイダーの役割だ！
28 = "%fsyogen;ここは私に任せておけ！\\n仲間を守るのがクルセイダーの役割だ！"

# カズマ（Ｍ）
# display as カズマ
# （ああ、いつもの性癖が！\n　よ、よし、証言としてゲット！）
546 = "（ああ、いつもの性癖が！\\n　よ、よし、証言としてゲット！）"

# カズマ（Ｍ）
# display as カズマ
# （いや、違うな。\n　いつもと違って目が真剣だ！）
549 = "（いや、違うな。\\n　いつもと違って目が真剣だ！）"

# カズマ
# お、おい、ダクネスッ！\nいくらお前でも無理だ、やめ――
348 = "お、おい、ダクネスッ！\\nいくらお前でも無理だ、やめ――"

# カズマ（Ｍ）
# display as カズマ
# （なっ、なんだ、今の爆風は！？）
562 = "（なっ、なんだ、今の爆風は！？）"

# アクア
# え？　え？　どうして？？\nめぐみん日に２発撃てるようになったの？
347 = "え？　え？　どうして？？\\nめぐみん日に２発撃てるようになったの？"

# カズマ（Ｍ）
# display as カズマ
# （いや、体に刺さる風の勢いも肌を焦がすような熱も\n　そして心に響く振動も爆裂魔法のそれとは違う）
548 = "（いや、体に刺さる風の勢いも肌を焦がすような熱も\\n　そして心に響く振動も爆裂魔法のそれとは違う）"

# カズマ
# そうか、ウィズだ！！
365 = "そうか、ウィズだ！！"

