# tr00.txt.scn

[info]
110 = "tr01a_01"
152 = "スキップ"
153 = "チュートリアル"

[characters]
158 = "バニル"

[character_subs]

[script]
# lines: 24

# monologue
# チュートリアルをスキップしますか？
155 = "チュートリアルをスキップしますか？"

# バニル
# ふはははははっ。\nまた会ったな。
149 = "ふはははははっ。\\nまた会ったな。"

# バニル
# 再度自己紹介でもしておいたほうが良いかな。\n我輩こそこの世のすべてを見通す大悪魔、\nバニルである。
164 = "再度自己紹介でもしておいたほうが良いかな。\\n我輩こそこの世のすべてを見通す大悪魔、\\nバニルである。"

# バニル
# 映像を映す機械の前にいる諸君らから\nなぜ、チュートリアルに女の子が出てこないのか！\nとの憤りを感じる、感じるぞ！
168 = "映像を映す機械の前にいる諸君らから\\nなぜ、チュートリアルに女の子が出てこないのか！\\nとの憤りを感じる、感じるぞ！"

# バニル
# この悪感情。\n大変に美味である。
142 = "この悪感情。\\n大変に美味である。"

# バニル
# さて、ここではパンツ裁判について\nレクチャーをしてやろう。\nしっかりと学ぶが良い。
144 = "さて、ここではパンツ裁判について\\nレクチャーをしてやろう。\\nしっかりと学ぶが良い。"

# バニル
# パンツ裁判の目的は、\n小僧が無意識に盗んでしまった下着の持ち主を、\n探すことが目的である。
160 = "パンツ裁判の目的は、\\n小僧が無意識に盗んでしまった下着の持ち主を、\\n探すことが目的である。"

# バニル
# 当然、下着の持ち主は、\nどれが自分の物であるかなど言いはしないだろう。\nそこで――
167 = "当然、下着の持ち主は、\\nどれが自分の物であるかなど言いはしないだろう。\\nそこで――"

# バニル
# 証言の選択。
176 = "証言の選択。"

# バニル
# パンツの選択。
159 = "パンツの選択。"

# バニル
# 人物の選択。
163 = "人物の選択。"

# バニル
# などなど、あらゆる方法を使って、\n容疑者……ではなかった下着の持ち主を\n推理し当たりをつけ、そして論破するのだ。
148 = "などなど、あらゆる方法を使って、\\n容疑者……ではなかった下着の持ち主を\\n推理し当たりをつけ、そして論破するのだ。"

# バニル
# ただし、注意がある。
146 = "ただし、注意がある。"

# バニル
# パンツ裁判中は画面左上に\n３つの星マークが表示される。
161 = "パンツ裁判中は画面左上に\\n３つの星マークが表示される。"

# バニル
# この星マークがゼロになった時、\n推理が失敗したということになる。
143 = "この星マークがゼロになった時、\\n推理が失敗したということになる。"

# バニル
# １度選択を間違えるごとに星マークは１つ減る。\n慎重に選択するようにするがよい。
179 = "１度選択を間違えるごとに星マークは１つ減る。\\n慎重に選択するようにするがよい。"

# monologue
# （次のパンツ裁判については\n　チュートリアルの簡易裁判ですので\n　星マークが減りません）
178 = "（次のパンツ裁判については\\n　チュートリアルの簡易裁判ですので\\n　星マークが減りません）"

# バニル
# 無事パンツの持ち主を当てられた場合は\nご褒美を受けることができる。
169 = "無事パンツの持ち主を当てられた場合は\\nご褒美を受けることができる。"

# バニル
# 当然、パンツの持ち主を当てられなかった\n場合はお仕置きを受けることになる。
166 = "当然、パンツの持ち主を当てられなかった\\n場合はお仕置きを受けることになる。"

# バニル
# なおかつお仕置きが終わると\nゲームオーバーとなるぞ。
147 = "なおかつお仕置きが終わると\\nゲームオーバーとなるぞ。"

# monologue
# （次のパンツ裁判については\n　ご褒美、お仕置き、ゲームオーバーが\n　存在しません）
177 = "（次のパンツ裁判については\\n　ご褒美、お仕置き、ゲームオーバーが\\n　存在しません）"

# バニル
# さて、これで裁判のチュートリアルが\n終了したわけだ。
145 = "さて、これで裁判のチュートリアルが\\n終了したわけだ。"

# バニル
# 呪いを受けてしまったにもかかわらず\n女性のパンツを持っていることに\n興奮してしまっている小僧よ、健闘を祈るぞ！
165 = "呪いを受けてしまったにもかかわらず\\n女性のパンツを持っていることに\\n興奮してしまっている小僧よ、健闘を祈るぞ！"

# バニル
# ふははははははっ。
150 = "ふははははははっ。"

[selections]
154 = "チュートリアルをスキップしない"
156 = "チュートリアルをスキップする"
