# tr01a_05.txt.scn

[info]
96 = "tr01a_05"

[characters]
115 = "カズマ（Ｍ）"

[character_subs]
114 = "カズマ"

[script]
# lines: 7

# カズマ（Ｍ）
# display as カズマ
# （ああ、そういえば、\n　ゆんゆんが気になることを言ってたよな？\n　それは……）
128 = "（ああ、そういえば、\\n　ゆんゆんが気になることを言ってたよな？\\n　それは……）"

# カズマ（Ｍ）
# display as カズマ
# （パンツに見覚えがある――\n　そうだ、そう言ってた！）
132 = "（パンツに見覚えがある――\\n　そうだ、そう言ってた！）"

# カズマ（Ｍ）
# display as カズマ
# （これって実は、すごく重要な証言じゃないか？）
131 = "（これって実は、すごく重要な証言じゃないか？）"

# カズマ（Ｍ）
# display as カズマ
# （今日の夕食はなんだろう……だったかな）
133 = "（今日の夕食はなんだろう……だったかな）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、これが重要な証言なんだろうか？\n　ひとまず自分の勘を信じてみるか）
129 = "（うーん、これが重要な証言なんだろうか？\\n　ひとまず自分の勘を信じてみるか）"

# カズマ（Ｍ）
# display as カズマ
# （友達何人できるかな……だったような）
134 = "（友達何人できるかな……だったような）"

# カズマ（Ｍ）
# display as カズマ
# （これが重要な証言なのか？\n　我ながら不安だ……）
130 = "（これが重要な証言なのか？\\n　我ながら不安だ……）"

[selections]
118 = "パンツに見覚えがある"
120 = "今日の夕食はなんだろう"
121 = "友達何人できるかな"
