# tr01a_09.txt.scn

[info]
178 = "tr01a_09"

[characters]
226 = "カズマ"
221 = "めぐみん"
225 = "アクア"
224 = "ゆんゆん"
228 = "ダクネス"
227 = "クリス"

[character_subs]

[script]
# lines: 20

# カズマ
# めぐみん。\n俺ははっきり覚えてるぞ。\nお前はこう言った。
223 = "めぐみん。\\n俺ははっきり覚えてるぞ。\\nお前はこう言った。"

# カズマ
# 『それによい生地なのですから、\n　傷んだりしたらもったいないでしょう』
204 = "『それによい生地なのですから、\\n　傷んだりしたらもったいないでしょう』"

# めぐみん
# は？　それがなんだって言うんです？
218 = "は？　それがなんだって言うんです？"

# カズマ
# なんで、見ただけで\nよい生地だとわかったんだ？
215 = "なんで、見ただけで\\nよい生地だとわかったんだ？"

# めぐみん
# いや、それは、とっておきの物だったので――
206 = "いや、それは、とっておきの物だったので――"

# めぐみん
# ああっ！？\nち、ちが、違います！　今のは違うんです！
205 = "ああっ！？\\nち、ちが、違います！　今のは違うんです！"

# カズマ
# はーははははぁ！\n何が違うというのかなぁ！？
217 = "はーははははぁ！\\n何が違うというのかなぁ！？"

# めぐみん
# くっ、くううう。\n私としたことが、不覚を取りました。
208 = "くっ、くううう。\\n私としたことが、不覚を取りました。"

# カズマ
# じゃあ、認めるんだな？\nこのパンツはお前の物だって！\nほら、ほら！
211 = "じゃあ、認めるんだな？\\nこのパンツはお前の物だって！\\nほら、ほら！"

# めぐみん
# うう、み、認めます……認めますよぉ。
207 = "うう、み、認めます……認めますよぉ。"

# アクア
# これは、本当に鬼畜の所行ね。\nこの男、優しさってものがないの？
209 = "これは、本当に鬼畜の所行ね。\\nこの男、優しさってものがないの？"

# ゆんゆん
# めぐみん、ごめんね。\n私が余計なことを言わなければ。
222 = "めぐみん、ごめんね。\\n私が余計なことを言わなければ。"

# めぐみん
# へっ、本当ですよ。\nへへっ、どこかの誰かのせいで、\n私はこんな辱めを受ける羽目になったわけですよ。
219 = "へっ、本当ですよ。\\nへへっ、どこかの誰かのせいで、\\n私はこんな辱めを受ける羽目になったわけですよ。"

# ゆんゆん
# ご、ごめんなさいってばー！
210 = "ご、ごめんなさいってばー！"

# ダクネス
# な、なんてうらやましい――
214 = "な、なんてうらやましい――"

# ダクネス
# で、ではなく！\nいたいけな少女になんてことを！\nまったく、許せんぞ！　やるなら私にしろ！
213 = "で、ではなく！\\nいたいけな少女になんてことを！\\nまったく、許せんぞ！　やるなら私にしろ！"

# クリス
# ねえ、確認なんだけどさ。\nキミのその呪いって、満月の夜ごとに\n発動するんだよね？
216 = "ねえ、確認なんだけどさ。\\nキミのその呪いって、満月の夜ごとに\\n発動するんだよね？"

# クリス
# ってことは、これ、毎月やるの？
212 = "ってことは、これ、毎月やるの？"

# カズマ
# まあ、そういうことになるな。\nでも安心しろよ、\n俺の推理力はこれでよくわかっただろ？
220 = "まあ、そういうことになるな。\\nでも安心しろよ、\\n俺の推理力はこれでよくわかっただろ？"

# カズマ
# 紳士として、ちゃんとみんなに\n正しいパンツを返すからな！
243 = "紳士として、ちゃんとみんなに\\n正しいパンツを返すからな！"

