# tr01b_06.txt.scn

[info]
102 = "tr01b_06"

[characters]
123 = "カズマ（Ｍ）"

[character_subs]
122 = "カズマ"

[script]
# lines: 4

# カズマ（Ｍ）
# display as カズマ
# （証拠になりそうなのは、このくらいか）
132 = "（証拠になりそうなのは、このくらいか）"

# カズマ（Ｍ）
# display as カズマ
# （どうだ？\n　この２つの証拠から、\n　パンツの持ち主を当てられるのか？）
131 = "（どうだ？\\n　この２つの証拠から、\\n　パンツの持ち主を当てられるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、当てられる！\n　俺の推理は完ぺきだ！）
130 = "（ああ、当てられる！\\n　俺の推理は完ぺきだ！）"

# カズマ（Ｍ）
# display as カズマ
# （……自信がないな。\n　ここはしくじれない、考え直そう）
129 = "（……自信がないな。\\n　ここはしくじれない、考え直そう）"

