# tr01b_03.txt.scn

[info]
149 = "tr01b_03"

[characters]
196 = "カズマ（Ｍ）"
187 = "めぐみん"
193 = "カズマ"
188 = "ゆんゆん"
192 = "ウィズ"
198 = "ダクネス"
197 = "クリス"
191 = "アクア"

[character_subs]
# 193 = "カズマ"

[script]
# lines: 27

# カズマ（Ｍ）
# display as カズマ
# （いいだろう、\n　そっちがその気ならこっちにだって\n　考えがあるぜ）
230 = "（いいだろう、\\n　そっちがその気ならこっちにだって\\n　考えがあるぜ）"

# めぐみん
# なんだか、嫌ぁな笑みを浮かべているんですが。
186 = "なんだか、嫌ぁな笑みを浮かべているんですが。"

# カズマ
# ゆんゆん。\nお仕置きの反意語はなんだと思う？
189 = "ゆんゆん。\\nお仕置きの反意語はなんだと思う？"

# ゆんゆん
# え、なんだろう……。
174 = "え、なんだろう……。"

# カズマ
# それはね、ご褒美だよ。
183 = "それはね、ご褒美だよ。"

# めぐみん
# カズマ、まさか……。
195 = "カズマ、まさか……。"

# カズマ
# その、まさかだっ！\nお仕置きがあるのなら\nご褒美もあってしかるべきだろう！
182 = "その、まさかだっ！\\nお仕置きがあるのなら\\nご褒美もあってしかるべきだろう！"

# カズマ
# だから、俺の推理が正しかった時は\nご褒美をもらおうじゃないか！
184 = "だから、俺の推理が正しかった時は\\nご褒美をもらおうじゃないか！"

# ウィズ
# ええっ、そんな……。
175 = "ええっ、そんな……。"

# カズマ
# あぁん？　俺はリスクを受け入れたんだ、\nお前らもリスクを受け入れなくて\n交渉と言えるのか？
168 = "あぁん？　俺はリスクを受け入れたんだ、\\nお前らもリスクを受け入れなくて\\n交渉と言えるのか？"

# カズマ
# ハイリスク・ハイリターン！\nそれがこの世の定めだ！
199 = "ハイリスク・ハイリターン！\\nそれがこの世の定めだ！"

# めぐみん
# おのれ、ぐうの音も出ない正論をっ。
176 = "おのれ、ぐうの音も出ない正論をっ。"

# ダクネス
# しかし、カズマが言うことにも一理あるだろう。
180 = "しかし、カズマが言うことにも一理あるだろう。"

# クリス
# くやしいけど、確かにそうだね。
178 = "くやしいけど、確かにそうだね。"

# カズマ
# さあ、どうするんだめぐみん？\nお仕置きをすると決めたからには、\nこっちの要求も飲んでもらうぞ。
179 = "さあ、どうするんだめぐみん？\\nお仕置きをすると決めたからには、\\nこっちの要求も飲んでもらうぞ。"

# めぐみん
# うぅ、ぐぬぬ、それは……。
172 = "うぅ、ぐぬぬ、それは……。"

# アクア
# じゃ、お仕置きはなしでいいんじゃない？\n何をさせるか考えるのも面倒だし。
181 = "じゃ、お仕置きはなしでいいんじゃない？\\n何をさせるか考えるのも面倒だし。"

# カズマ
# お前は、あっさり撤回すんな！
177 = "お前は、あっさり撤回すんな！"

# カズマ
# 崇拝する対象のお前がそんなことだから、\nアクシズ教団は、適当な甘い言葉で人を騙す\n詐欺集団なんて言われんだよ！
202 = "崇拝する対象のお前がそんなことだから、\\nアクシズ教団は、適当な甘い言葉で人を騙す\\n詐欺集団なんて言われんだよ！"

# アクア
# うぅぅぅ～～～～！
173 = "うぅぅぅ～～～～！"

# カズマ
# なんだ、泣くのか！\n泣けばなんでも解決すると思ってんのか！
185 = "なんだ、泣くのか！\\n泣けばなんでも解決すると思ってんのか！"

# アクア
# う、う、うぅぅ～～～～～～～！！
170 = "う、う、うぅぅ～～～～～～～！！"

# めぐみん
# カズマ、そういう逃げ場のない正論はやめた方が\nいいですよ。
194 = "カズマ、そういう逃げ場のない正論はやめた方が\\nいいですよ。"

# ダクネス
# 言われた女は泣くことしかできなくなるからな。
229 = "言われた女は泣くことしかできなくなるからな。"

# アクア
# う、うう、いいわ、受けて立ってやるわよ！\n私の可愛い信徒達をバカにした罪を\n思い知らせてあげるんだから！
171 = "う、うう、いいわ、受けて立ってやるわよ！\\n私の可愛い信徒達をバカにした罪を\\n思い知らせてあげるんだから！"

# カズマ
# よーし、交渉成立だな。
190 = "よーし、交渉成立だな。"

# めぐみん
# ああ、アクアが見事に、カズマの口車に\n乗せられちゃいましたよ。
169 = "ああ、アクアが見事に、カズマの口車に\\n乗せられちゃいましたよ。"

