# tr01b_09.txt.scn

[info]
137 = "tr01b_09"

[characters]
168 = "カズマ"
170 = "クリス"
169 = "カズマ（Ｍ）"

[character_subs]
# 168 = "カズマ"

[script]
# lines: 10

# カズマ
# まだ認めないのか、クリス。\nなら仕方ない、最後の証拠を出そう。
164 = "まだ認めないのか、クリス。\\nなら仕方ない、最後の証拠を出そう。"

# クリス
# 最後の証拠……？
176 = "最後の証拠……？"

# カズマ
# そうだ！\n言い逃れのできない、決定的な証拠になる\n発言があるんだよ！
159 = "そうだ！\\n言い逃れのできない、決定的な証拠になる\\n発言があるんだよ！"

# カズマ
# それは……。
161 = "それは……。"

# カズマ（Ｍ）
# display as カズマ
# （……違うな、この台詞は証拠にはならない。\n　クリスの発言で、もっと決定的なものが\n　あったはずだ！）
184 = "（……違うな、この台詞は証拠にはならない。\\n　クリスの発言で、もっと決定的なものが\\n　あったはずだ！）"

# カズマ（Ｍ）
# display as カズマ
# （うん？　この台詞はクリスのパンツだって\n　証拠にはならないよな？\n　よく考えろ、俺……）
186 = "（うん？　この台詞はクリスのパンツだって\\n　証拠にはならないよな？\\n　よく考えろ、俺……）"

# カズマ（Ｍ）
# display as カズマ
# （いやいや、\n　ダクネスの勘違い発言は関係ないだろ！\n　もっと別の台詞だ！）
185 = "（いやいや、\\n　ダクネスの勘違い発言は関係ないだろ！\\n　もっと別の台詞だ！）"

# カズマ（Ｍ）
# display as カズマ
# （待て、落ち着け俺。\n　この発言のどこが証拠になるんだよ）
188 = "（待て、落ち着け俺。\\n　この発言のどこが証拠になるんだよ）"

# カズマ（Ｍ）
# display as カズマ
# （これはこれでとてもいい台詞だったと思うが、\n　証拠にはならないよな……）
187 = "（これはこれでとてもいい台詞だったと思うが、\\n　証拠にはならないよな……）"

# カズマ（Ｍ）
# display as カズマ
# （駆け出し冒険者の街だからなんだ？\n　クリスには関係ないよな）
189 = "（駆け出し冒険者の街だからなんだ？\\n　クリスには関係ないよな）"

[selections]
156 = "あのさ、前も言ったと思うけど、\\nそんなふうに盗られた下着を返されても、\\nたぶんみんな困ると思うんだよね。"
162 = "ですから、決めた場所にパンツを置いて、\\n持ち主がこっそり回収するというのが\\nもっとも合理的な手段だと思うのです。"
158 = "そうだな。\\nカズマが私に見せる優しさはひと味もふた味も違う。"
173 = "何を言っている！\\n年甲斐も無いこんな格好を男共に晒すなんて、\\n屈辱でしかないだろう！"
163 = "でも、もし見えちゃったら、\\n責任は取ってもらうからね？"
157 = "え、ええと、あの、ご主人様？\\nお料理を冷ます手伝いをさせていただいても\\nよろしいですか？"
160 = "それに、ここは駆け出しの冒険者たちが集まってる\\n街なんですよ？"
