# tr01b_08.txt.scn

[info]
161 = "tr01b_08"

[characters]
205 = "カズマ"
206 = "クリス"
207 = "ダクネス"
199 = "めぐみん"
200 = "ゆんゆん"
203 = "ウィズ"

[character_subs]

[script]
# lines: 23

# カズマ
# よし、推理完了！\n謎はすべて解けたぜ！
201 = "よし、推理完了！\\n謎はすべて解けたぜ！"

# クリス
# ちょ、ちょっと待って！\n本当に？　本当にわかったの？
194 = "ちょ、ちょっと待って！\\n本当に？　本当にわかったの？"

# クリス
# 間違ったらお仕置きだよ？\nそこのところ、ちゃんとわかってるんだよね！？
235 = "間違ったらお仕置きだよ？\\nそこのところ、ちゃんとわかってるんだよね！？"

# カズマ
# ふっ！\nどうしたんだい、クリス。\nそんなに慌てて。
196 = "ふっ！\\nどうしたんだい、クリス。\\nそんなに慌てて。"

# カズマ
# 大丈夫、安心しろよ。\n俺がすべてわかってる。\nこれは、お前のパンツなんだろう？
213 = "大丈夫、安心しろよ。\\n俺がすべてわかってる。\\nこれは、お前のパンツなんだろう？"

# クリス
# えっ！？　ち、違うけど……。
191 = "えっ！？　ち、違うけど……。"

# ダクネス
# そうだぞ、カズマ！\nなにを根拠にこんな羨ましい――
192 = "そうだぞ、カズマ！\\nなにを根拠にこんな羨ましい――"

# ダクネス
# い、いや！\nこのような屈辱を私の友人に与えようというのだ！\n理由次第ではただでは済まさん！
187 = "い、いや！\\nこのような屈辱を私の友人に与えようというのだ！\\n理由次第ではただでは済まさん！"

# クリス
# ダクネス！
208 = "ダクネス！"

# めぐみん
# いいことを言ってますが、\n明らかに趣味が入ってますよね。
188 = "いいことを言ってますが、\\n明らかに趣味が入ってますよね。"

# カズマ
# わかった。\nなら、ダクネスも納得する理由を説明してやる。
202 = "わかった。\\nなら、ダクネスも納得する理由を説明してやる。"

# カズマ
# まず、１つめ！\n俺はこのパンツを知ってるんだ！
198 = "まず、１つめ！\\n俺はこのパンツを知ってるんだ！"

# クリス
# はあっ！？\nな、なにそれ、知ってるって……。
195 = "はあっ！？\\nな、なにそれ、知ってるって……。"

# カズマ
# 覚えてないか？\n俺がクリスからスティールを教えてもらい\n初めて使ったときのことを。
234 = "覚えてないか？\\n俺がクリスからスティールを教えてもらい\\n初めて使ったときのことを。"

# ダクネス
# あっ！\nそうか、それは……\nあの時、クリスが穿いていた物と同じなのか！
185 = "あっ！\\nそうか、それは……\\nあの時、クリスが穿いていた物と同じなのか！"

# カズマ
# その通りだ！\nさらに次！
193 = "その通りだ！\\nさらに次！"

# カズマ
# メイド喫茶の準備をしていたとき、\nクリスは妙に顔を真っ赤にしていた。
209 = "メイド喫茶の準備をしていたとき、\\nクリスは妙に顔を真っ赤にしていた。"

# カズマ
# メイド姿が恥ずかしかったかもしれないが、\nそれにしては過剰だったと思わないか？
210 = "メイド姿が恥ずかしかったかもしれないが、\\nそれにしては過剰だったと思わないか？"

# ゆんゆん
# うーん、言われてみれば\nそんな気もしますけど……でも……。
190 = "うーん、言われてみれば\\nそんな気もしますけど……でも……。"

# カズマ
# ふふん、まあ焦るなよ。\nここにさらにもう１つ、証拠があるのさ。
197 = "ふふん、まあ焦るなよ。\\nここにさらにもう１つ、証拠があるのさ。"

# カズマ
# あのとき、クリスは風を気にしてた。\nでも、それっておかしいよな？\n気にするほどの強い風は吹いていなかった！
186 = "あのとき、クリスは風を気にしてた。\\nでも、それっておかしいよな？\\n気にするほどの強い風は吹いていなかった！"

# ウィズ
# ……確かにそうですね。
184 = "……確かにそうですね。"

# クリス
# うう……。\nで、でも、違うんだってば……。
189 = "うう……。\\nで、でも、違うんだってば……。"

