# tr01a_04.txt.scn

[info]
96 = "tr01a_04"

[characters]
115 = "カズマ（Ｍ）"

[character_subs]
114 = "カズマ"

[script]
# lines: 5

# カズマ（Ｍ）
# display as カズマ
# （次にヒントになりそうなのは、\n　調べてるときのこいつらの態度か）
128 = "（次にヒントになりそうなのは、\\n　調べてるときのこいつらの態度か）"

# カズマ（Ｍ）
# display as カズマ
# （変に動揺したり、\n　怪しい態度をとってたのは……）
127 = "（変に動揺したり、\\n　怪しい態度をとってたのは……）"

# カズマ（Ｍ）
# display as カズマ
# （アクア……かなぁ？）
125 = "（アクア……かなぁ？）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスか？\n　いつも不審な言動ばかりではあるが、\n　今日は特にひどかった……かな）
126 = "（ダクネスか？\\n　いつも不審な言動ばかりではあるが、\\n　今日は特にひどかった……かな）"

# カズマ（Ｍ）
# display as カズマ
# （どう考えてもめぐみんだ！\n　汗をかくほど動揺してたもんな）
124 = "（どう考えてもめぐみんだ！\\n　汗をかくほど動揺してたもんな）"

[selections]
113 = "アクア"
117 = "ダクネス"
111 = "めぐみん"
