# tr01b_04.txt.scn

[info]
104 = "tr01b_04"

[characters]
125 = "カズマ（Ｍ）"

[character_subs]
124 = "カズマ"

[script]
# lines: 5

# カズマ（Ｍ）
# display as カズマ
# （よし、まずは情報の整理だ。\n　今回のパンツの色は……）
137 = "（よし、まずは情報の整理だ。\\n　今回のパンツの色は……）"

# カズマ（Ｍ）
# display as カズマ
# （これはもちろん白だ！\n　自信を持って言えるぜ）
135 = "（これはもちろん白だ！\\n　自信を持って言えるぜ）"

# カズマ（Ｍ）
# display as カズマ
# （それにしても……このパンツ……\n　見覚えがあるような気がするんだよな）
136 = "（それにしても……このパンツ……\\n　見覚えがあるような気がするんだよな）"

# カズマ（Ｍ）
# display as カズマ
# （確か、紫だったよな？）
138 = "（確か、紫だったよな？）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、黒だったよな？）
134 = "（うーん、黒だったよな？）"

[selections]
25 = "0"
26 = "1"
28 = "2"
