# tr01a_06.txt.scn

[info]
99 = "tr01a_06"

[characters]
118 = "カズマ（Ｍ）"

[character_subs]
117 = "カズマ"

[script]
# lines: 4

# カズマ（Ｍ）
# display as カズマ
# （証拠になりそうなのは、このくらいか）
129 = "（証拠になりそうなのは、このくらいか）"

# カズマ（Ｍ）
# display as カズマ
# （どうだ？\n　この３つの証拠から、\n　みんなが納得する推理ができるのか？）
128 = "（どうだ？\\n　この３つの証拠から、\\n　みんなが納得する推理ができるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （……ああ、できる！\n　俺の推理は完ぺきだ！）
126 = "（……ああ、できる！\\n　俺の推理は完ぺきだ！）"

# カズマ（Ｍ）
# display as カズマ
# （……なにか間違ってる気がする。\n　ここはしくじれないからな、考え直そう）
127 = "（……なにか間違ってる気がする。\\n　ここはしくじれないからな、考え直そう）"

