# tr01a_02.txt.scn

[info]
141 = "tr01a_02"

[characters]
178 = "アクア"
176 = "めぐみん"
179 = "カズマ"
181 = "クリス"
182 = "ダクネス"
177 = "ゆんゆん"

[character_subs]

[script]
# lines: 14

# アクア
# ねえ、裁判をするっていうけど、\n何をどうやってやるのよ。
175 = "ねえ、裁判をするっていうけど、\\n何をどうやってやるのよ。"

# めぐみん
# カズマが有罪なのはもう決まっているわけですし、\n議論すべきことがありませんよね。
180 = "カズマが有罪なのはもう決まっているわけですし、\\n議論すべきことがありませんよね。"

# カズマ
# あっははははは……\nバカめ、裁判とは建前だ！
166 = "あっははははは……\\nバカめ、裁判とは建前だ！"

# クリス
# いきなり外道なことを言い出したんだけど。
167 = "いきなり外道なことを言い出したんだけど。"

# ダクネス
# うむ、さすがカズマだ。\n私が見込んだだけはある。
168 = "うむ、さすがカズマだ。\\n私が見込んだだけはある。"

# ゆんゆん
# じゃあ、この裁判の目的ってなんなんですか？
169 = "じゃあ、この裁判の目的ってなんなんですか？"

# カズマ
# それは――
172 = "それは――"

# カズマ
# 俺が、このパンツの持ち主は誰かを\n推理することだっ！
184 = "俺が、このパンツの持ち主は誰かを\\n推理することだっ！"

# めぐみん
# ちょっ！？\nわ、わざわざ全員が揃っているところで\nやるんですか！？
173 = "ちょっ！？\\nわ、わざわざ全員が揃っているところで\\nやるんですか！？"

# カズマ
# ああ、そうでないと\n俺の推理が正しいのかを確認できないだろ？
165 = "ああ、そうでないと\\n俺の推理が正しいのかを確認できないだろ？"

# カズマ
# それに、さっきの証言で大体わかったしな。\nまあ、俺の名推理を堪能しろよ。\nふふふふふ……。
171 = "それに、さっきの証言で大体わかったしな。\\nまあ、俺の名推理を堪能しろよ。\\nふふふふふ……。"

# アクア
# どうしてこんなことに\n闘志を燃やすのかしらね、カズマは。
174 = "どうしてこんなことに\\n闘志を燃やすのかしらね、カズマは。"

# ダクネス
# それがカズマだからな！
170 = "それがカズマだからな！"

# クリス
# 嬉しそうに言うところじゃないからね、ダクネス。
186 = "嬉しそうに言うところじゃないからね、ダクネス。"

