# tr01b_11.txt.scn

[info]
124 = "tr01b_11"

[characters]
153 = "カズマ（Ｍ）"
151 = "アクア"
150 = "めぐみん"
154 = "ダクネス"
152 = "カズマ"

[character_subs]
# 152 = "カズマ"

[script]
# lines: 14

# カズマ（Ｍ）
# display as カズマ
# （くっ……。\n　ダメだ、これ以上の推理はできそうにない）
170 = "（くっ……。\\n　ダメだ、これ以上の推理はできそうにない）"

# アクア
# あら？\nどうしたのかしら、カズマ？\n黙っていられちゃ裁判が進まないんですけど？
139 = "あら？\\nどうしたのかしら、カズマ？\\n黙っていられちゃ裁判が進まないんですけど？"

# めぐみん
# これ以上、続けても無駄ですね。\nカズマの負けですよ。
144 = "これ以上、続けても無駄ですね。\\nカズマの負けですよ。"

# カズマ（Ｍ）
# display as カズマ
# （くそぉ……）
169 = "（くそぉ……）"

# ダクネス
# さあ、その下着を渡してくれ。
145 = "さあ、その下着を渡してくれ。"

# カズマ
# まさかダクネスのだったのか？
149 = "まさかダクネスのだったのか？"

# ダクネス
# いいや違う。\nせっかく名乗り出ずに済んだのだから、\nあとで私から持ち主に返しておこうと思ってな。
140 = "いいや違う。\\nせっかく名乗り出ずに済んだのだから、\\nあとで私から持ち主に返しておこうと思ってな。"

# カズマ
# そうか……。\nじゃあ、よろしく頼むわ。
147 = "そうか……。\\nじゃあ、よろしく頼むわ。"

# ダクネス
# うむ、任された。
141 = "うむ、任された。"

# アクア
# ところでカズマ～、約束覚えてるわよね～？
148 = "ところでカズマ～、約束覚えてるわよね～？"

# カズマ
# お仕置きだろ？　わかってるよ。
143 = "お仕置きだろ？　わかってるよ。"

# アクア
# 女神の情けよ。\n誰にお仕置きされるかはカズマに選ばせてあげるわ。
157 = "女神の情けよ。\\n誰にお仕置きされるかはカズマに選ばせてあげるわ。"

# アクア
# さあ、誰にする？
146 = "さあ、誰にする？"

# カズマ
# え？　ええと……。
142 = "え？　ええと……。"

