# tr01a_07.txt.scn

[info]
162 = "tr01a_07"

[characters]
214 = "カズマ"
209 = "めぐみん"
215 = "ダクネス"
213 = "アクア"
211 = "ゆんゆん"

[character_subs]

[script]
# lines: 22

# カズマ
# ふっ……。\n俺には、このパンツの持ち主がわかったぜ。
207 = "ふっ……。\\n俺には、このパンツの持ち主がわかったぜ。"

# めぐみん
# わかったなら、\nこっそり返せばいいじゃないですか。\nどこまで鬼畜なんですか。
212 = "わかったなら、\\nこっそり返せばいいじゃないですか。\\nどこまで鬼畜なんですか。"

# ダクネス
# そうだ！　まさに鬼畜王の名にふさわしい！\nカズマの向上心には感動すら覚える！
195 = "そうだ！　まさに鬼畜王の名にふさわしい！\\nカズマの向上心には感動すら覚える！"

# めぐみん
# そこ、褒める所じゃありませんよ。
196 = "そこ、褒める所じゃありませんよ。"

# カズマ
# それでは発表しよう！\nこのパンツの持ち主は――
199 = "それでは発表しよう！\\nこのパンツの持ち主は――"

# カズマ
# めぐみん！　お前だ！！
210 = "めぐみん！　お前だ！！"

# めぐみん
# なななっ！？\nな、なな、何を言ってるんですか！？\nわわわ、私のパンツなわけがないでしょう！
203 = "なななっ！？\\nな、なな、何を言ってるんですか！？\\nわわわ、私のパンツなわけがないでしょう！"

# カズマ
# はん、しらを切る気か？\nんじゃ、俺の推理を\n証拠を交えて聞かせてやろうじゃないか。
206 = "はん、しらを切る気か？\\nんじゃ、俺の推理を\\n証拠を交えて聞かせてやろうじゃないか。"

# カズマ
# まず、１つめ！\nこのパンツの色は黒だ！
208 = "まず、１つめ！\\nこのパンツの色は黒だ！"

# カズマ
# 以前、めぐみんのパンツをスティールしたとき、\n同じように黒いのを穿いてたよな？
217 = "以前、めぐみんのパンツをスティールしたとき、\\n同じように黒いのを穿いてたよな？"

# めぐみん
# う、うう……。
191 = "う、うう……。"

# カズマ
# そして２つめ！\nここまでの間、お前は汗をかくほど動揺していた！
198 = "そして２つめ！\\nここまでの間、お前は汗をかくほど動揺していた！"

# カズマ
# なあ、めぐみん？\nなんでそんなに動揺する必要があるんだ？\n隠したいことがあるからじゃないのか？
202 = "なあ、めぐみん？\\nなんでそんなに動揺する必要があるんだ？\\n隠したいことがあるからじゃないのか？"

# めぐみん
# う、うううう……。
192 = "う、うううう……。"

# アクア
# ねえ、これ、一見すると\n小さな子をいじめてる悪い男にしか\n見えないんだけど？
204 = "ねえ、これ、一見すると\\n小さな子をいじめてる悪い男にしか\\n見えないんだけど？"

# カズマ
# そして最後は、ゆんゆん！
197 = "そして最後は、ゆんゆん！"

# ゆんゆん
# はいっ！？\nな、なんですか？
205 = "はいっ！？\\nな、なんですか？"

# カズマ
# さっき、こう言ったよな？\n『その下着に見覚えがあるような気がした』\n『この前出かけた時に買ってた』ってさ。
193 = "さっき、こう言ったよな？\\n『その下着に見覚えがあるような気がした』\\n『この前出かけた時に買ってた』ってさ。"

# ゆんゆん
# そ、それは、え、ええと、言いましたけど。\nでも別に、深い意味はなくて。
194 = "そ、それは、え、ええと、言いましたけど。\\nでも別に、深い意味はなくて。"

# カズマ
# いいや、これこそが決定的な証拠だ。\nつまりこれは、ゆんゆんと一緒に出かけた時に\nめぐみんが買った物ってことだ！
190 = "いいや、これこそが決定的な証拠だ。\\nつまりこれは、ゆんゆんと一緒に出かけた時に\\nめぐみんが買った物ってことだ！"

# めぐみん
# ち、違いますよっ！\nどうして私がそのぼっちと\n買い物に行ったなんて決めつけるんですか！
201 = "ち、違いますよっ！\\nどうして私がそのぼっちと\\n買い物に行ったなんて決めつけるんですか！"

# めぐみん
# それに、他の２つだって\nただの状況証拠にすぎません！\n私は認めませんからね！！
200 = "それに、他の２つだって\\nただの状況証拠にすぎません！\\n私は認めませんからね！！"

