# tr01a_03.txt.scn

[info]
99 = "tr01a_03"

[characters]
121 = "カズマ（Ｍ）"

[character_subs]
120 = "カズマ"

[script]
# lines: 4

# カズマ（Ｍ）
# display as カズマ
# （んじゃ、まずは情報の整理だ。\n　まず、今回のパンツの色は……）
133 = "（んじゃ、まずは情報の整理だ。\\n　まず、今回のパンツの色は……）"

# カズマ（Ｍ）
# display as カズマ
# （そうだ、白だった……よな？）
132 = "（そうだ、白だった……よな？）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、紫だったような……）
130 = "（うーん、紫だったような……）"

# カズマ（Ｍ）
# display as カズマ
# （そう、黒だ！\n　この目にしっかり焼きついてるから\n　間違いない！）
131 = "（そう、黒だ！\\n　この目にしっかり焼きついてるから\\n　間違いない！）"

[selections]
23 = "1"
25 = "2"
22 = "0"
