# tr01b_07.txt.scn

[info]
104 = "tr01b_07"

[characters]
121 = "カズマ（Ｍ）"

[character_subs]
120 = "カズマ"

[script]
# lines: 12

# カズマ（Ｍ）
# display as カズマ
# （それに、さっきも思ったけど\n　このパンツに見覚えがあるような気が\n　するんだよな）
138 = "（それに、さっきも思ったけど\\n　このパンツに見覚えがあるような気が\\n　するんだよな）"

# カズマ（Ｍ）
# display as カズマ
# （……あっ！　そうか、思い出した！\n　このパンツ、前にスティールした\n　クリスのパンツじゃないか？）
133 = "（……あっ！　そうか、思い出した！\\n　このパンツ、前にスティールした\\n　クリスのパンツじゃないか？）"

# カズマ（Ｍ）
# display as カズマ
# （そう、クリスに教えてもらって、\n　初めてスティールしたときに盗んだやつだ！）
137 = "（そう、クリスに教えてもらって、\\n　初めてスティールしたときに盗んだやつだ！）"

# カズマ（Ｍ）
# display as カズマ
# （いや、でも、それだけで\n　クリスと決めつけるのは失礼じゃないか？\n　どこにでも売ってるパンツかもしれないし）
135 = "（いや、でも、それだけで\\n　クリスと決めつけるのは失礼じゃないか？\\n　どこにでも売ってるパンツかもしれないし）"

# カズマ（Ｍ）
# display as カズマ
# （他に、クリスだって言える証拠が\n　ないだろうか？）
143 = "（他に、クリスだって言える証拠が\\n　ないだろうか？）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、そういえばクリスには\n　他におかしな行動があったな！\n　それは……）
134 = "（ああ、そういえばクリスには\\n　他におかしな行動があったな！\\n　それは……）"

# カズマ（Ｍ）
# display as カズマ
# （クリスは風を気にしてた。\n　でも、それっておかしいよな？\n　あの時、気にするほどの風が吹いていたっけ？）
141 = "（クリスは風を気にしてた。\\n　でも、それっておかしいよな？\\n　あの時、気にするほどの風が吹いていたっけ？）"

# カズマ（Ｍ）
# display as カズマ
# （これは怪しい……）
136 = "（これは怪しい……）"

# カズマ（Ｍ）
# display as カズマ
# （確かにスカートを気にしてたけど、\n　別にそれはおかしいことじゃない。\n　メイド服に慣れてなかったんだろうし）
144 = "（確かにスカートを気にしてたけど、\\n　別にそれはおかしいことじゃない。\\n　メイド服に慣れてなかったんだろうし）"

# カズマ（Ｍ）
# display as カズマ
# （なんでスカートを気にしていたのか……\n　その理由ってなんだっけ？）
140 = "（なんでスカートを気にしていたのか……\\n　その理由ってなんだっけ？）"

# カズマ（Ｍ）
# display as カズマ
# （メイド服を気にしてたけど、\n　それは、まあ、着慣れてない服なんだし\n　当然と言えば当然だ）
142 = "（メイド服を気にしてたけど、\\n　それは、まあ、着慣れてない服なんだし\\n　当然と言えば当然だ）"

# カズマ（Ｍ）
# display as カズマ
# （それより、もっと妙だったところが\n　あったよな？）
139 = "（それより、もっと妙だったところが\\n　あったよな？）"

[selections]
132 = "風を気にしていた"
122 = "スカートを気にしていた"
123 = "メイド服を気にしていた"
