# tr01b_05.txt.scn

[info]
108 = "tr01b_05"

[characters]
129 = "カズマ（Ｍ）"

[character_subs]
128 = "カズマ"

[script]
# lines: 5

# カズマ（Ｍ）
# display as カズマ
# （そういえば、\n　メイド喫茶の準備をしていた時に\n　顔が真っ赤だったやつがいたな……）
139 = "（そういえば、\\n　メイド喫茶の準備をしていた時に\\n　顔が真っ赤だったやつがいたな……）"

# カズマ（Ｍ）
# display as カズマ
# （そうだ、クリスだ！\n　真っ赤になって動揺してたよな）
140 = "（そうだ、クリスだ！\\n　真っ赤になって動揺してたよな）"

# カズマ（Ｍ）
# display as カズマ
# （メイド姿が恥ずかしかったのかもしれないが、\n　それにしては過剰だった！）
143 = "（メイド姿が恥ずかしかったのかもしれないが、\\n　それにしては過剰だった！）"

# カズマ（Ｍ）
# display as カズマ
# （アクア……だったか？\n　よく覚えてないが、多分、そうだよな？）
142 = "（アクア……だったか？\\n　よく覚えてないが、多分、そうだよな？）"

# カズマ（Ｍ）
# display as カズマ
# （はっきり覚えてないけど、\n　ゆんゆんだったような……）
141 = "（はっきり覚えてないけど、\\n　ゆんゆんだったような……）"

[selections]
130 = "クリス"
126 = "アクア"
125 = "ゆんゆん"
