# tr01a_08.txt.scn

[info]
110 = "tr01a_08"

[characters]
139 = "カズマ"
135 = "めぐみん"
140 = "カズマ（Ｍ）"

[character_subs]
# 139 = "カズマ"

[script]
# lines: 8

# カズマ
# ほう……。\nならば、とどめの一撃をくれてやろう！
134 = "ほう……。\\nならば、とどめの一撃をくれてやろう！"

# めぐみん
# な、なんです……。
131 = "な、なんです……。"

# カズマ
# 実はな、気がついたんだよ。\n言い逃れのできない、\n決定的な証拠になる発言があるってなぁ！
145 = "実はな、気がついたんだよ。\\n言い逃れのできない、\\n決定的な証拠になる発言があるってなぁ！"

# カズマ
# それは……。
130 = "それは……。"

# カズマ（Ｍ）
# display as カズマ
# （いや、これじゃないはずだ。\n　アクアの匂いなんてどうでもいい！）
155 = "（いや、これじゃないはずだ。\\n　アクアの匂いなんてどうでもいい！）"

# カズマ（Ｍ）
# display as カズマ
# （いやいや、違うだろ！\n　似合ってるからそいつの物だって\n　わけじゃねーし！）
157 = "（いやいや、違うだろ！\\n　似合ってるからそいつの物だって\\n　わけじゃねーし！）"

# カズマ（Ｍ）
# display as カズマ
# （いや、これは決定的な証拠にはならないよな。\n　素材に詳しいってだけだし）
156 = "（いや、これは決定的な証拠にはならないよな。\\n　素材に詳しいってだけだし）"

# カズマ（Ｍ）
# display as カズマ
# （……ん？　素材？\n　そうだ、素材って言えば……）
154 = "（……ん？　素材？\\n　そうだ、素材って言えば……）"

[selections]
133 = "ねえねえ、めぐみん。\\n私って変な匂いがしてるの？"
132 = "に、似合うと思ったということは、\\n私がその下着を着けている姿を\\n想像したと言うことだよな！"
144 = "同じ素材を使ったハンカチは、\\nおそらく数千エリスすると思うんです。"
129 = "それによい生地なのですから、\\n傷んだりしたらもったいないでしょう。"
