# tr01b_02.txt.scn

[info]
183 = "tr01b_02"

[characters]
247 = "カズマ"
250 = "クリス"
244 = "ゆんゆん"
245 = "アクア"
251 = "ダクネス"
242 = "めぐみん"
246 = "ウィズ"

[character_subs]

[script]
# lines: 38

# カズマ
# さぁて！\n裁判を開始するぞぉ！
224 = "さぁて！\\n裁判を開始するぞぉ！"

# クリス
# …………。
211 = "…………。"

# ゆんゆん
# …………。
# 211 = "…………。"

# カズマ
# あれ？\nなんかノリ悪くないか、お前ら。
214 = "あれ？\\nなんかノリ悪くないか、お前ら。"

# アクア
# この状況をどうやって楽しめっていうのよ。
221 = "この状況をどうやって楽しめっていうのよ。"

# ダクネス
# 前回、めぐみんが\nあれだけの目にあわされているしな。
255 = "前回、めぐみんが\\nあれだけの目にあわされているしな。"

# カズマ
# その言い方はやめろ！\n俺が何かやらかしたみたいじゃねーか！
229 = "その言い方はやめろ！\\n俺が何かやらかしたみたいじゃねーか！"

# アクア
# やらかしたでしょ、実際に。
243 = "やらかしたでしょ、実際に。"

# めぐみん
# 困ったことに、カズマは\n変なところで度胸もあるし、頭も回りますからね。\nその上、幸運パラメータは桁違いです。
258 = "困ったことに、カズマは\\n変なところで度胸もあるし、頭も回りますからね。\\nその上、幸運パラメータは桁違いです。"

# めぐみん
# その能力全部が、いま、パンツに向いているかと\n思うと、やるせない気分になります。
228 = "その能力全部が、いま、パンツに向いているかと\\n思うと、やるせない気分になります。"

# カズマ
# ねえ、それって褒めてる？　褒めてるの？
240 = "ねえ、それって褒めてる？　褒めてるの？"

# ウィズ
# ど、どうでしょう？
236 = "ど、どうでしょう？"

# カズマ
# じゃあ、褒めてるってことにしておく！\nさて、今日も俺の名推理を披露するとするかぁ！
226 = "じゃあ、褒めてるってことにしておく！\\nさて、今日も俺の名推理を披露するとするかぁ！"

# ゆんゆん
# すごくポジティブですね。
227 = "すごくポジティブですね。"

# アクア
# ちょっと待って！\nねえカズマ、私から提案があるんだけど。
234 = "ちょっと待って！\\nねえカズマ、私から提案があるんだけど。"

# アクア
# この裁判って、あんたにとって\nなんのリスクもないわよね？
222 = "この裁判って、あんたにとって\\nなんのリスクもないわよね？"

# ダクネス
# ああ、そうだな。\n推理が外れたとしても罰もない。
212 = "ああ、そうだな。\\n推理が外れたとしても罰もない。"

# アクア
# これって不公平じゃない？
223 = "これって不公平じゃない？"

# めぐみん
# 確かにそうですね。
281 = "確かにそうですね。"

# ダクネス
# うむ、カズマも何かリスクを負うべきだ。
216 = "うむ、カズマも何かリスクを負うべきだ。"

# カズマ
# え？　なんで？
218 = "え？　なんで？"

# めぐみん
# こちらは『紳士魂』なんてこれっぽちも\n腹の足しにならないカズマのくだらない自尊心を\n満たすためだけに辱めを受けているんですよ。
220 = "こちらは『紳士魂』なんてこれっぽちも\\n腹の足しにならないカズマのくだらない自尊心を\\n満たすためだけに辱めを受けているんですよ。"

# めぐみん
# カズマはパンツの持ち主を当てて満足するかも\nしれませんが、こちらはただ嫌な思いをするだけ\nなんです。
248 = "カズマはパンツの持ち主を当てて満足するかも\\nしれませんが、こちらはただ嫌な思いをするだけ\\nなんです。"

# カズマ
# でも、パンツを返す必要があるだろう。\nお前たち、ずっとスースーしたままだし。
235 = "でも、パンツを返す必要があるだろう。\\nお前たち、ずっとスースーしたままだし。"

# クリス
# それは、みんなの前で返さなければいけない\n理由にはならないよ。
233 = "それは、みんなの前で返さなければいけない\\n理由にはならないよ。"

# ウィズ
# それこそ前にめぐみんさんが仰ったように\nそっとどこかに置いておけば済む話です。
230 = "それこそ前にめぐみんさんが仰ったように\\nそっとどこかに置いておけば済む話です。"

# めぐみん
# カズマは豚の餌にもならない自尊心を満たすために、\n私たちに辱めを強要している。
249 = "カズマは豚の餌にもならない自尊心を満たすために、\\n私たちに辱めを強要している。"

# ダクネス
# なんか今日のめぐみんは辛辣だな。
239 = "なんか今日のめぐみんは辛辣だな。"

# ウィズ
# それだけみんなの前で下着を返されるのは、\n屈辱的ということなのでは。
231 = "それだけみんなの前で下着を返されるのは、\\n屈辱的ということなのでは。"

# めぐみん
# それならば、あなたもリスクを背負うべきでしょう！\n外したときに、私たちの言いなりになるという\nリスクを！
232 = "それならば、あなたもリスクを背負うべきでしょう！\\n外したときに、私たちの言いなりになるという\\nリスクを！"

# アクア
# ああ、なるほど、お仕置き。\nそれはいいわね、なんか楽しそうだし！
213 = "ああ、なるほど、お仕置き。\\nそれはいいわね、なんか楽しそうだし！"

# カズマ
# いや、ちょっと待て、お仕置きって。\n響きからして嫌なんだけど。
215 = "いや、ちょっと待て、お仕置きって。\\n響きからして嫌なんだけど。"

# めぐみん
# ふふふ、計算通り。
241 = "ふふふ、計算通り。"

# ダクネス
# なるほど、カズマの気の弱さを利用したのか。
238 = "なるほど、カズマの気の弱さを利用したのか。"

# めぐみん
# ええ、へたれなカズマのことですから、\nリスクを背負うとなったら、二の足を踏むだろうと。
217 = "ええ、へたれなカズマのことですから、\\nリスクを背負うとなったら、二の足を踏むだろうと。"

# カズマ
# くっ、この俺の紳士魂をなめるな！\nその程度のリスクを恐れなどしないっ！
219 = "くっ、この俺の紳士魂をなめるな！\\nその程度のリスクを恐れなどしないっ！"

# めぐみん
# なっ！？
237 = "なっ！？"

# アクア
# じゃあ、それで決定ね。\n後でやっぱり嫌だーはなしだから。
225 = "じゃあ、それで決定ね。\\n後でやっぱり嫌だーはなしだから。"

