# tr01b_10.txt.scn

[info]
229 = "tr01b_10"

[characters]
279 = "カズマ"
277 = "アクア"
281 = "クリス"
284 = "ダクネス"
274 = "めぐみん"
280 = "カズマ（Ｍ）"
276 = "ゆんゆん"
278 = "ウィズ"

[character_subs]
# 279 = "カズマ"

[script]
# lines: 33

# カズマ
# クリスはこう言った。\n『でも、もし見えちゃったら、\n　責任は取ってもらうからね？』
283 = "クリスはこう言った。\\n『でも、もし見えちゃったら、\\n　責任は取ってもらうからね？』"

# カズマ
# パンツを見られたぐらいで責任なんて大袈裟な、\nと思ったけど、もしパンツを穿いていないと\nなれば納得だ！
285 = "パンツを見られたぐらいで責任なんて大袈裟な、\\nと思ったけど、もしパンツを穿いていないと\\nなれば納得だ！"

# アクア
# うわ……。\nこの男、いま自分が何を言ったのか\nわかってるのかしら。
257 = "うわ……。\\nこの男、いま自分が何を言ったのか\\nわかってるのかしら。"

# カズマ
# どうだ、クリス？\nまだ認めないのか？\nこれが自分のパンツだと！！
267 = "どうだ、クリス？\\nまだ認めないのか？\\nこれが自分のパンツだと！！"

# クリス
# う、ううう……。
256 = "う、ううう……。"

# ダクネス
# クリス。\n恥ずかしいのなら私が代わりに言うが……。
282 = "クリス。\\n恥ずかしいのなら私が代わりに言うが……。"

# クリス
# ……ううん、いいよ。\nもう認めるしかないみたい。\n悔しいけど、正解だよ。
253 = "……ううん、いいよ。\\nもう認めるしかないみたい。\\n悔しいけど、正解だよ。"

# カズマ
# ふっ、ふふん、やっと認めたか。\nやっぱりこのパンツはクリスのだったんだなぁ。
272 = "ふっ、ふふん、やっと認めたか。\\nやっぱりこのパンツはクリスのだったんだなぁ。"

# クリス
# ちょっと、ジロジロ見てないで返してよ！
265 = "ちょっと、ジロジロ見てないで返してよ！"

# カズマ
# おっと悪い。\nいつまでもスースーしてるのは嫌だよな。
258 = "おっと悪い。\\nいつまでもスースーしてるのは嫌だよな。"

# クリス
# も、もう、カズマのバカ！
275 = "も、もう、カズマのバカ！"

# めぐみん
# 心中察しますよ、クリス。
291 = "心中察しますよ、クリス。"

# カズマ
# これでクリスはパンツを穿けるようになるはずだ。\nうん、いいことをした。
259 = "これでクリスはパンツを穿けるようになるはずだ。\\nうん、いいことをした。"

# ダクネス
# なんだあの達成感に満ちた顔は。
269 = "なんだあの達成感に満ちた顔は。"

# アクア
# 殴りたくなるわね。
292 = "殴りたくなるわね。"

# めぐみん
# あ、クリス、どうでした？
255 = "あ、クリス、どうでした？"

# クリス
# あ、あはは、穿けたよ。
254 = "あ、あはは、穿けたよ。"

# カズマ
# まったく、素直に名乗り出てくれれば、\n余計な手間がかからずに済んだんだぞ。
273 = "まったく、素直に名乗り出てくれれば、\\n余計な手間がかからずに済んだんだぞ。"

# めぐみん
# なんという傲慢な言いぐさ。
270 = "なんという傲慢な言いぐさ。"

# ダクネス
# 自分で辱めておきながら、\n追い打ちまでかけるとは……\nさすが私の見込んだ男だけはある。
320 = "自分で辱めておきながら、\\n追い打ちまでかけるとは……\\nさすが私の見込んだ男だけはある。"

# カズマ
# なんにせよ、これで今回の騒ぎは一段落だな。
271 = "なんにせよ、これで今回の騒ぎは一段落だな。"

# ダクネス
# そうか？\n根本的なところが何も解決していないと思うが？
262 = "そうか？\\n根本的なところが何も解決していないと思うが？"

# めぐみん
# 結局指輪はそのままですしね。
319 = "結局指輪はそのままですしね。"

# アクア
# だから指ごと切っちゃうのが一番楽なんだってば。
264 = "だから指ごと切っちゃうのが一番楽なんだってば。"

# カズマ
# …………。
252 = "…………。"

# カズマ（Ｍ）
# display as カズマ
# （またその話題に戻るわけか）
321 = "（またその話題に戻るわけか）"

# カズマ（Ｍ）
# display as カズマ
# （本当に迷惑な指輪だな。\n　これを外さない限り、こんな騒ぎを\n　毎月繰り返すことになるとか冗談じゃねーぞ）
323 = "（本当に迷惑な指輪だな。\\n　これを外さない限り、こんな騒ぎを\\n　毎月繰り返すことになるとか冗談じゃねーぞ）"

# カズマ（Ｍ）
# display as カズマ
# （早く金をどうにかしないと……）
322 = "（早く金をどうにかしないと……）"

# めぐみん
# それでは、今日はこれで解散としましょう。
263 = "それでは、今日はこれで解散としましょう。"

# ゆんゆん
# そ、そうね！\n私もやることがあるし！
261 = "そ、そうね！\\n私もやることがあるし！"

# カズマ
# ちょっと待て。\nまさか忘れたとは言わせないぞ。
266 = "ちょっと待て。\\nまさか忘れたとは言わせないぞ。"

# ウィズ
# な、何がですか？
268 = "な、何がですか？"

# カズマ
# ご褒美だよ、ご褒美。\nふひひひ、さぁて、誰にご褒美をいただこうかな。
260 = "ご褒美だよ、ご褒美。\\nふひひひ、さぁて、誰にご褒美をいただこうかな。"

