# tr02_05.txt.scn

[info]
0 = ""

[characters]
123 = "カズマ（Ｍ）"

[character_subs]
122 = "カズマ"

[script]
# lines: 5

# カズマ（Ｍ）
# display as カズマ
# （確か、イベント中に\n　妙に様子がおかしかったやつがいたよな。\n　それは……）
135 = "（確か、イベント中に\\n　妙に様子がおかしかったやつがいたよな。\\n　それは……）"

# カズマ（Ｍ）
# display as カズマ
# （そう、ダクネスだ！）
132 = "（そう、ダクネスだ！）"

# カズマ（Ｍ）
# display as カズマ
# （あいつはよく挙動不審になるけど、\n　いつも以上に高ぶっていたというか\n　なんというか……）
131 = "（あいつはよく挙動不審になるけど、\\n　いつも以上に高ぶっていたというか\\n　なんというか……）"

# カズマ（Ｍ）
# display as カズマ
# （アクアかな？\n　うん、そんな気がする）
134 = "（アクアかな？\\n　うん、そんな気がする）"

# カズマ（Ｍ）
# display as カズマ
# （そうだな、めぐみんの様子が\n　おかしかったんだ）
133 = "（そうだな、めぐみんの様子が\\n　おかしかったんだ）"

[selections]
120 = "アクア"
124 = "ダクネス"
118 = "めぐみん"
