# tr02_11.txt.scn

[info]
0 = ""

[characters]
90 = "カズマ（Ｍ）"

[character_subs]
89 = "カズマ"

[script]
# lines: 2

# カズマ（Ｍ）
# display as カズマ
# （問題はもう１つだな。\n　このアダルティな紫のパンツの持ち主は誰だ？）
95 = "（問題はもう１つだな。\\n　このアダルティな紫のパンツの持ち主は誰だ？）"

# カズマ（Ｍ）
# display as カズマ
# （考えろ、この紫パンツの持ち主の名前は！！）
96 = "（考えろ、この紫パンツの持ち主の名前は！！）"

