# tr02_03.txt.scn

[info]
0 = ""

[characters]
131 = "カズマ（Ｍ）"

[character_subs]
130 = "カズマ"

[script]
# lines: 6

# カズマ（Ｍ）
# display as カズマ
# （まずはパンツの再検証だな。\n　今回、持ってないパンツは……）
141 = "（まずはパンツの再検証だな。\\n　今回、持ってないパンツは……）"

# カズマ（Ｍ）
# display as カズマ
# （いや、黒と白のパンツは持ってるだろ）
139 = "（いや、黒と白のパンツは持ってるだろ）"

# カズマ（Ｍ）
# display as カズマ
# （紫のパンツはあったよな）
144 = "（紫のパンツはあったよな）"

# カズマ（Ｍ）
# display as カズマ
# （そうだな、今回は黒じゃない。\n　紫、そして黒白のパンツだ！）
140 = "（そうだな、今回は黒じゃない。\\n　紫、そして黒白のパンツだ！）"

# カズマ（Ｍ）
# display as カズマ
# （白はスポーティな雰囲気、\n　紫のパンツはアダルティな香りを漂わせてる）
143 = "（白はスポーティな雰囲気、\\n　紫のパンツはアダルティな香りを漂わせてる）"

# カズマ（Ｍ）
# display as カズマ
# （当たり前だけど、どっちも\n　今まで見たことがないパンツだ……）
142 = "（当たり前だけど、どっちも\\n　今まで見たことがないパンツだ……）"

[selections]
29 = "3"
25 = "2"
22 = "0"
