# tr02_04.txt.scn

[info]
0 = ""

[characters]
125 = "カズマ（Ｍ）"

[character_subs]
124 = "カズマ"

[script]
# lines: 6

# カズマ（Ｍ）
# display as カズマ
# （そういえば、ウィズの店に行った時、\n　気になることがあったよな）
135 = "（そういえば、ウィズの店に行った時、\\n　気になることがあったよな）"

# カズマ（Ｍ）
# display as カズマ
# （そうだ、ウィズに避けられたんだ）
136 = "（そうだ、ウィズに避けられたんだ）"

# カズマ（Ｍ）
# display as カズマ
# （いったい、その理由はなんなんだ？）
134 = "（いったい、その理由はなんなんだ？）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズが悲しそうに……していたような）
138 = "（ウィズが悲しそうに……していたような）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズの機嫌が悪かった！）
139 = "（ウィズの機嫌が悪かった！）"

# カズマ（Ｍ）
# display as カズマ
# （ような気がするけど、本当か？）
137 = "（ような気がするけど、本当か？）"

[selections]
122 = "ウィズに避けられた"
121 = "ウィズが悲しそうにしていた"
123 = "ウィズの機嫌が悪かった"
