# tr02_02.txt.scn

[info]
0 = ""

[characters]
149 = "カズマ"
148 = "ウィズ"
150 = "ダクネス"
144 = "ゆんゆん"
147 = "アクア"
143 = "めぐみん"

[character_subs]

[script]
# lines: 11

# カズマ
# よーし、裁判開始だな！
145 = "よーし、裁判開始だな！"

# ウィズ
# ああ、やっぱりやるんですね。
137 = "ああ、やっぱりやるんですね。"

# カズマ
# 今回、この通り、\n２枚のパンツが俺の手元にあるわけだが……。
152 = "今回、この通り、\\n２枚のパンツが俺の手元にあるわけだが……。"

# カズマ
# しかし、この程度の困難では俺はくじけない！\n紳士の心は打ち砕けないのだ！
141 = "しかし、この程度の困難では俺はくじけない！\\n紳士の心は打ち砕けないのだ！"

# ダクネス
# ……やれやれ。\nこれがパンツのことでなければ\n少しは様になるのだが。
136 = "……やれやれ。\\nこれがパンツのことでなければ\\n少しは様になるのだが。"

# ゆんゆん
# まったくです。
142 = "まったくです。"

# カズマ
# んじゃ、今回の裁判だけど、\nこの２枚のパンツの持ち主を当てるってことで\nいいよな？
146 = "んじゃ、今回の裁判だけど、\\nこの２枚のパンツの持ち主を当てるってことで\\nいいよな？"

# アクア
# いいよなって言われても、返事に困るんですけど。
139 = "いいよなって言われても、返事に困るんですけど。"

# めぐみん
# ……そんなのどうでもいいですよ。\nとっとと終わらせてください。
135 = "……そんなのどうでもいいですよ。\\nとっとと終わらせてください。"

# カズマ
# おう、任せろ！\n俺の推理でぱぱっと終わらせてやるからな！
140 = "おう、任せろ！\\n俺の推理でぱぱっと終わらせてやるからな！"

# アクア
# あーあ、ヒキニートが\nやる気を出しちゃいましたよ？
138 = "あーあ、ヒキニートが\\nやる気を出しちゃいましたよ？"

