# tr02_07.txt.scn

[info]
0 = ""

[characters]
123 = "カズマ（Ｍ）"

[character_subs]
122 = "カズマ"

[script]
# lines: 4

# カズマ（Ｍ）
# display as カズマ
# （証拠になりそうなのは、このくらいか）
132 = "（証拠になりそうなのは、このくらいか）"

# カズマ（Ｍ）
# display as カズマ
# （どうだ？\n　この４つの証拠から、\n　パンツの持ち主を推理できるのか？）
130 = "（どうだ？\\n　この４つの証拠から、\\n　パンツの持ち主を推理できるのか？）"

# カズマ（Ｍ）
# display as カズマ
# （よし、この証拠で推論を組み立ててみよう）
131 = "（よし、この証拠で推論を組み立ててみよう）"

# カズマ（Ｍ）
# display as カズマ
# （……不安になってきた。\n　じっくり考え直そう）
129 = "（……不安になってきた。\\n　じっくり考え直そう）"

