# tr02_08.txt.scn

[info]
0 = ""

[characters]
110 = "アクア"
108 = "めぐみん"
111 = "カズマ"
112 = "クリス"

[character_subs]

[script]
# lines: 4

# アクア
# あらあらぁ？\n今回はかなり悩んでいらっしゃるみたいねぇ、\nカズマさん？
106 = "あらあらぁ？\\n今回はかなり悩んでいらっしゃるみたいねぇ、\\nカズマさん？"

# めぐみん
# さっさとギブアップしたらどうですか？\nいえ、ギブアップするべきでしょう。\nええ、そうでしょうとも。
107 = "さっさとギブアップしたらどうですか？\\nいえ、ギブアップするべきでしょう。\\nええ、そうでしょうとも。"

# カズマ
# あと少しなんだ！\nあと少しで真実に近づける！
105 = "あと少しなんだ！\\nあと少しで真実に近づける！"

# クリス
# もう、どうしてこの情熱を\n他に向けないんだろうね？
109 = "もう、どうしてこの情熱を\\n他に向けないんだろうね？"

