# tr02_15.txt.scn

[info]
0 = ""

[characters]

[character_subs]

[script]
# lines: 0

[selections]
122 = "アクア"
120 = "めぐみん"
125 = "ダクネス"
123 = "ウィズ"
124 = "クリス"
121 = "ゆんゆん"
# 122 = "アクア"
# 120 = "めぐみん"
# 125 = "ダクネス"
# 123 = "ウィズ"
# 124 = "クリス"
# 121 = "ゆんゆん"
