# tr02_09.txt.scn

[info]
0 = ""

[characters]
235 = "カズマ"
231 = "アクア"
238 = "ダクネス"
236 = "カズマ（Ｍ）"
237 = "クリス"

[character_subs]
# 235 = "カズマ"

[script]
# lines: 24

# カズマ
# よし、まずはこの\nスポーティなパンツについてまとめよう。\n持ち主の見当はついてるからな。
230 = "よし、まずはこの\\nスポーティなパンツについてまとめよう。\\n持ち主の見当はついてるからな。"

# アクア
# え？　本当に？\n見栄張ってるんじゃないでしょうね？
214 = "え？　本当に？\\n見栄張ってるんじゃないでしょうね？"

# カズマ
# そうじゃねーってことをとくと教えてやるよ。\n結論から言う、このパンツの持ち主はダクネスだ！
218 = "そうじゃねーってことをとくと教えてやるよ。\\n結論から言う、このパンツの持ち主はダクネスだ！"

# ダクネス
# はうううっ！\nな、な、なん、だと……！\nで、でたらめを……言うなぁ……！
226 = "はうううっ！\\nな、な、なん、だと……！\\nで、でたらめを……言うなぁ……！"

# カズマ（Ｍ）
# display as カズマ
# （その反応がなによりの証拠な気がするが。\n　まあ、置いといて）
272 = "（その反応がなによりの証拠な気がするが。\\n　まあ、置いといて）"

# カズマ
# でたらめじゃないぜ。\n証拠もあるんだ。
224 = "でたらめじゃないぜ。\\n証拠もあるんだ。"

# ダクネス
# しょ、証拠、だと！？
216 = "しょ、証拠、だと！？"

# カズマ
# このパンツのスポーティさは、\nやっぱり、ダクネスの物だって感じがする。
215 = "このパンツのスポーティさは、\\nやっぱり、ダクネスの物だって感じがする。"

# クリス
# そんなの、キミ個人の感想じゃない。\nとても証拠なんて言えないよ？
222 = "そんなの、キミ個人の感想じゃない。\\nとても証拠なんて言えないよ？"

# カズマ
# ああ、わかってるって。\n俺が気になったのは、ダクネスの態度だよ。
212 = "ああ、わかってるって。\\n俺が気になったのは、ダクネスの態度だよ。"

# カズマ
# イベント中、妙に高ぶった様子だっただろ？\n特にスタートしたときなんか、\nこっちが心配になるほどだったし。
233 = "イベント中、妙に高ぶった様子だっただろ？\\n特にスタートしたときなんか、\\nこっちが心配になるほどだったし。"

# ダクネス
# そ、それは……。
217 = "そ、それは……。"

# クリス
# それだって状況証拠だよ。\nダクネスだって決めつけられないでしょ？
219 = "それだって状況証拠だよ。\\nダクネスだって決めつけられないでしょ？"

# カズマ
# まあ待て、クリス。\n証拠はまだあるんだ、決定的なのがな。
227 = "まあ待て、クリス。\\n証拠はまだあるんだ、決定的なのがな。"

# ダクネス
# な、なにっ！？\nこの上で、さらなる辱めが\n私を待っているというのか！？
225 = "な、なにっ！？\\nこの上で、さらなる辱めが\\n私を待っているというのか！？"

# カズマ
# それは……。
221 = "それは……。"

# カズマ（Ｍ）
# display as カズマ
# （うん、これは間違いなく違うな）
268 = "（うん、これは間違いなく違うな）"

# カズマ（Ｍ）
# display as カズマ
# （くそ、くだらない記憶に翻弄されるな、俺！）
270 = "（くそ、くだらない記憶に翻弄されるな、俺！）"

# カズマ（Ｍ）
# display as カズマ
# （パンツに結界を！\n　違うか）
273 = "（パンツに結界を！\\n　違うか）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、ダクネスの証拠探しなんだし、\n　これも違うか？）
269 = "（うーん、ダクネスの証拠探しなんだし、\\n　これも違うか？）"

# カズマ（Ｍ）
# display as カズマ
# （これは確か、大会の話をするときの言葉だ。\n　パンツとは関係ない）
271 = "（これは確か、大会の話をするときの言葉だ。\\n　パンツとは関係ない）"

# カズマ（Ｍ）
# display as カズマ
# （いつもの優しいダクネスか。\n　おかしいところなんてないよな）
267 = "（いつもの優しいダクネスか。\\n　おかしいところなんてないよな）"

# カズマ（Ｍ）
# display as カズマ
# （当然の感想か。\n　証拠にはならない）
274 = "（当然の感想か。\\n　証拠にはならない）"

# カズマ
# ダクネス、俺は覚えているぞ！\nお前はこう言った！
239 = "ダクネス、俺は覚えているぞ！\\nお前はこう言った！"

[selections]
223 = "そんな警戒しなくてもいいですよ。\\nもう怒ってませんから、"
266 = "腐れアンデッドがどうしてここにいるのよ。"
211 = "あ、結界でしたら、\\n入る時にちょっとピリッとしましたけど――"
245 = "毎月寝込みを襲ってるカズマに言われたく\\nありません。"
228 = "またおかしなことに\\n手を出すのではないだろうな？"
232 = "アクア、めぐみん、\\nそう言わずにカズマに協力してやったらどうだ？"
213 = "ああ。いつまでも、そのくだらない指輪に\\n振り回されるのは御免だからな。"
220 = "それに、今の状態で衆人の前にこの身を晒す\\nというのもなかなか……。"
