# tr02_14.txt.scn

[info]
0 = ""

[characters]
143 = "カズマ（Ｍ）"
138 = "めぐみん"
142 = "カズマ"
141 = "ウィズ"
144 = "クリス"
140 = "アクア"

[character_subs]
# 142 = "カズマ"

[script]
# lines: 11

# カズマ（Ｍ）
# display as カズマ
# （くっ……。\n　ダメだ、これ以上の推理はできそうにない）
156 = "（くっ……。\\n　ダメだ、これ以上の推理はできそうにない）"

# めぐみん
# もう限界のようですね。\nカズマの頭脳はその程度ということですか。
139 = "もう限界のようですね。\\nカズマの頭脳はその程度ということですか。"

# カズマ
# ち、ちくしょう……。\n反論できねぇ……。
136 = "ち、ちくしょう……。\\n反論できねぇ……。"

# ウィズ
# あの……\nそろそろ下着を渡していただけませんか？
130 = "あの……\\nそろそろ下着を渡していただけませんか？"

# カズマ
# え？　このパンツ、ウィズのなのか？
131 = "え？　このパンツ、ウィズのなのか？"

# ウィズ
# け、決してそういうわけでは……。
132 = "け、決してそういうわけでは……。"

# クリス
# あたしたちから\n持ち主に返しておくってことだよ。
129 = "あたしたちから\\n持ち主に返しておくってことだよ。"

# ウィズ
# そうです！\n返しておくので渡してください！\nじょ、常連さんに心当たりがあるんです。
135 = "そうです！\\n返しておくので渡してください！\\nじょ、常連さんに心当たりがあるんです。"

# アクア
# さあ、カズマ？\nあんたが推理を失敗した場合は\nどうなるんだったかしらね？
134 = "さあ、カズマ？\\nあんたが推理を失敗した場合は\\nどうなるんだったかしらね？"

# カズマ
# な、なんだったかなー？
137 = "な、なんだったかなー？"

# アクア
# ごまかそうとしてるんじゃないわよ！\nさあ、お仕置きの時間よ！
133 = "ごまかそうとしてるんじゃないわよ！\\nさあ、お仕置きの時間よ！"

