# tr02_06.txt.scn

[info]
0 = ""

[characters]
128 = "カズマ（Ｍ）"

[character_subs]
127 = "カズマ"

[script]
# lines: 6

# カズマ（Ｍ）
# display as カズマ
# （うーん、これだけじゃまだ推理できないな。\n　他に引っかかることがあったような……）
137 = "（うーん、これだけじゃまだ推理できないな。\\n　他に引っかかることがあったような……）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズが大会への参加に積極的だったけど、\n　なんでなんだろう？）
140 = "（ウィズが大会への参加に積極的だったけど、\\n　なんでなんだろう？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、俺を心配してくれてのことだろうけど、\n　自分の店だって経営が苦しいのに、ここまで\n　協力してくれるのが、なんだか引っかかる）
136 = "（いや、俺を心配してくれてのことだろうけど、\\n　自分の店だって経営が苦しいのに、ここまで\\n　協力してくれるのが、なんだか引っかかる）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズは優しいから、だけでは\n　すませられないような……）
141 = "（ウィズは優しいから、だけでは\\n　すませられないような……）"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんが積極的じゃなかったこと、かな）
138 = "（めぐみんが積極的じゃなかったこと、かな）"

# カズマ（Ｍ）
# display as カズマ
# （アクアは水泳が得意だってことかな。\n　あいつにそんな無駄な特技があったなんて\n　知らなかったぜ）
139 = "（アクアは水泳が得意だってことかな。\\n　あいつにそんな無駄な特技があったなんて\\n　知らなかったぜ）"

[selections]
121 = "めぐみんが運動に積極的ではなかった"
124 = "アクアは水泳が得意"
126 = "ウィズが参加に積極的だった"
