# tr02_10.txt.scn

[info]
0 = ""

[characters]
170 = "カズマ"
172 = "ダクネス"
168 = "めぐみん"
169 = "アクア"
171 = "クリス"

[character_subs]

[script]
# lines: 12

# カズマ
# 『それに、今の状態で衆人の前にこの身を晒す\n　というのもなかなか……』
157 = "『それに、今の状態で衆人の前にこの身を晒す\\n　というのもなかなか……』"

# カズマ
# 他の発言は、正直、いつものダクネスの発言と\n違いが見分けられない。
174 = "他の発言は、正直、いつものダクネスの発言と\\n違いが見分けられない。"

# カズマ
# だが、この台詞は別だ！
164 = "だが、この台詞は別だ！"

# カズマ
# お前が喜ぶ、『今の状況』とは\nいったいどういう状況なんだ。
160 = "お前が喜ぶ、『今の状況』とは\\nいったいどういう状況なんだ。"

# カズマ
# それは下半身に何も穿いていない、そんな状況\nなんじゃないのか？
163 = "それは下半身に何も穿いていない、そんな状況\\nなんじゃないのか？"

# ダクネス
# はっ……！\nし、しまった！
166 = "はっ……！\\nし、しまった！"

# カズマ
# はーはははは！\n後悔しても遅いぞ！\nさあ、なにか言い逃れはあるのかね！？
167 = "はーはははは！\\n後悔しても遅いぞ！\\nさあ、なにか言い逃れはあるのかね！？"

# ダクネス
# くうっ！\nその勝ち誇った笑顔……た、たまらんっ！
161 = "くうっ！\\nその勝ち誇った笑顔……た、たまらんっ！"

# ダクネス
# こんな高揚感を味わっていたなんて……\nずるいぞ、クリス、めぐみん！
162 = "こんな高揚感を味わっていたなんて……\\nずるいぞ、クリス、めぐみん！"

# めぐみん
# ええー……。
159 = "ええー……。"

# アクア
# ねえ、クリス。\n友達は選んだほうがいいわよ？
165 = "ねえ、クリス。\\n友達は選んだほうがいいわよ？"

# クリス
# あ……あははは……。
158 = "あ……あははは……。"

