# tr02_13.txt.scn

[info]
0 = ""

[characters]
255 = "カズマ"
253 = "ウィズ"
252 = "アクア"
257 = "ダクネス"
256 = "カズマ（Ｍ）"
247 = "めぐみん"
249 = "ゆんゆん"

[character_subs]
# 255 = "カズマ"

[script]
# lines: 34

# カズマ
# わかったぞ！\nこれはウィズのパンツだ！
250 = "わかったぞ！\\nこれはウィズのパンツだ！"

# ウィズ
# え、ええええっ！？\nわわわ、私ですかっ！？
228 = "え、ええええっ！？\\nわわわ、私ですかっ！？"

# アクア
# へーえ、このアンデッド、\nこんなの身につけちゃってるの？\nいやらしいわねぇ。
244 = "へーえ、このアンデッド、\\nこんなの身につけちゃってるの？\\nいやらしいわねぇ。"

# ウィズ
# ち、ち、違いますっ！\n私の物ではありません！
240 = "ち、ち、違いますっ！\\n私の物ではありません！"

# カズマ
# いいや、間違いない。\nこのパンツはウィズの物だ。\n証拠だってちゃんとある。
227 = "いいや、間違いない。\\nこのパンツはウィズの物だ。\\n証拠だってちゃんとある。"

# カズマ
# まず、俺が店に行ったとき、\nウィズは俺を避けた。
245 = "まず、俺が店に行ったとき、\\nウィズは俺を避けた。"

# ウィズ
# そ、そうでしたか？
231 = "そ、そうでしたか？"

# カズマ
# 心優しいウィズが、そんなことをする理由。\nそれは俺に近づきたくない、何かの理由があった\nからだ。
263 = "心優しいウィズが、そんなことをする理由。\\nそれは俺に近づきたくない、何かの理由があった\\nからだ。"

# ウィズ
# そ、それは……。
232 = "そ、それは……。"

# カズマ
# そしてもう１点が、\nウィズが大会への参加に積極的だったことだ。
235 = "そしてもう１点が、\\nウィズが大会への参加に積極的だったことだ。"

# カズマ
# 俺を心配してくれてのことだろうけど、\n自分の店のこともそっちのけで\n協力してくれるのはさすがにおかしい。
260 = "俺を心配してくれてのことだろうけど、\\n自分の店のこともそっちのけで\\n協力してくれるのはさすがにおかしい。"

# カズマ
# 何よりも、狂犬モードになったアクアに\n食い下がったことだ。
259 = "何よりも、狂犬モードになったアクアに\\n食い下がったことだ。"

# カズマ
# これはつまり、俺達を優勝させ、\n少しでも早く３０００万エリス貯めて\nもらいたいという――
230 = "これはつまり、俺達を優勝させ、\\n少しでも早く３０００万エリス貯めて\\nもらいたいという――"

# カズマ
# ウィズの願望の現れだったんだよっ！
254 = "ウィズの願望の現れだったんだよっ！"

# ウィズ
# そ、それは……！
233 = "そ、それは……！"

# カズマ
# どうだ、ウィズ。\nここまでの俺の推理は。
241 = "どうだ、ウィズ。\\nここまでの俺の推理は。"

# ウィズ
# わかりました！　認めます！\n認めるからもう返してください！
251 = "わかりました！　認めます！\\n認めるからもう返してください！"

# ダクネス
# 皆の前でこんな辱めを……\nお前は本当に容赦を知らぬ酷い男だな！
267 = "皆の前でこんな辱めを……\\nお前は本当に容赦を知らぬ酷い男だな！"

# カズマ
# そんな嬉しそうに文句言われても……。
237 = "そんな嬉しそうに文句言われても……。"

# ダクネス
# まったく。ただでさえパンツが穿けなくなって\n困ったというのに、さらにこんな追い打ちまで\nかけてくるとはな。
246 = "まったく。ただでさえパンツが穿けなくなって\\n困ったというのに、さらにこんな追い打ちまで\\nかけてくるとはな。"

# ウィズ
# 本当に困ってたんですからね。\nむしろ水着の時の方が安心出来てたくらいです。
264 = "本当に困ってたんですからね。\\nむしろ水着の時の方が安心出来てたくらいです。"

# カズマ
# そういうもんか？
234 = "そういうもんか？"

# カズマ（Ｍ）
# display as カズマ
# （男だったら、パンツなんて無ければ無いで\n　どうとでもなりそうだし、良くわからんな）
294 = "（男だったら、パンツなんて無ければ無いで\\n　どうとでもなりそうだし、良くわからんな）"

# カズマ
# なんにせよ、無事にパンツを\n本人に返すことが出来て良かったよ。
243 = "なんにせよ、無事にパンツを\\n本人に返すことが出来て良かったよ。"

# めぐみん
# この惨状を無事だと言える神経がすごいですね。
229 = "この惨状を無事だと言える神経がすごいですね。"

# ゆんゆん
# 私もいつか、\nこんな目に遭うのかと思うと……うぅ……。
291 = "私もいつか、\\nこんな目に遭うのかと思うと……うぅ……。"

# アクア
# もうさ、カズマを指輪ごと\nどこかに埋めて来ちゃわない？
248 = "もうさ、カズマを指輪ごと\\nどこかに埋めて来ちゃわない？"

# カズマ
# だから！　なんでお前は指輪だけじゃなくて、\n俺までまとめてどうにかしようとするんだよ！
238 = "だから！　なんでお前は指輪だけじゃなくて、\\n俺までまとめてどうにかしようとするんだよ！"

# アクア
# だってその方が楽じゃない。
239 = "だってその方が楽じゃない。"

# カズマ
# 楽とかそういうことじゃなくて、\nお前も女神なんだったら、\nもっと慈悲の心とか持ったらどうなんだ！
265 = "楽とかそういうことじゃなくて、\\nお前も女神なんだったら、\\nもっと慈悲の心とか持ったらどうなんだ！"

# カズマ
# そんなだからお前は駄女神なんだよ！
236 = "そんなだからお前は駄女神なんだよ！"

# アクア
# なんですって！
242 = "なんですって！"

# カズマ（Ｍ）
# display as カズマ
# （こうして始まった低次元な言い合いは、\n　アクアの機嫌が戻るまで続いた）
293 = "（こうして始まった低次元な言い合いは、\\n　アクアの機嫌が戻るまで続いた）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、もっと俺のことを\n　大切に扱ってくれるパーティーに移籍したいと、\n　心から思わずにはいられなかった）
292 = "（ああ、もっと俺のことを\\n　大切に扱ってくれるパーティーに移籍したいと、\\n　心から思わずにはいられなかった）"

