# tr03_02.txt.scn

[info]
0 = ""

[characters]
184 = "カズマ"
185 = "クリス"
183 = "アクア"
180 = "めぐみん"
182 = "ゆんゆん"

[character_subs]

[script]
# lines: 20

# カズマ
# 裁・判・開・始ぃ！
211 = "裁・判・開・始ぃ！"

# クリス
# なんでそんなにハイテンションなのさ。
178 = "なんでそんなにハイテンションなのさ。"

# カズマ
# え？　せっかく軌道に乗りかけた\nアイドルプロジェクトが――
165 = "え？　せっかく軌道に乗りかけた\\nアイドルプロジェクトが――"

# カズマ
# どこかのバカのせいで、頓挫したからだけど？
177 = "どこかのバカのせいで、頓挫したからだけど？"

# アクア
# うぅ……ごめんなさい。
164 = "うぅ……ごめんなさい。"

# クリス
# つまり、やけになってるんだ。
172 = "つまり、やけになってるんだ。"

# めぐみん
# ちょっと待ってください。\nまさかストレス解消も兼ねての裁判なんて\n言いませんよね。
171 = "ちょっと待ってください。\\nまさかストレス解消も兼ねての裁判なんて\\n言いませんよね。"

# カズマ
# 紳士の俺がそんなことをするわけ\nないじゃないか。
210 = "紳士の俺がそんなことをするわけ\\nないじゃないか。"

# ゆんゆん
# ど、どうして視線を逸らすんですか。
176 = "ど、どうして視線を逸らすんですか。"

# カズマ
# しかし、今回は３枚か。\nこいつは推理のやりがいもありそうだな。
167 = "しかし、今回は３枚か。\\nこいつは推理のやりがいもありそうだな。"

# めぐみん
# ふっ、３枚ともなると、\nさすがのカズマも持ち主を言い当てるのに\n苦労しそうですね。
179 = "ふっ、３枚ともなると、\\nさすがのカズマも持ち主を言い当てるのに\\n苦労しそうですね。"

# カズマ
# もちろん、楽にやれるとは思ってねーよ。\nだが俺の推理力も磨かれているはず。
181 = "もちろん、楽にやれるとは思ってねーよ。\\nだが俺の推理力も磨かれているはず。"

# カズマ
# とはいえ、この先、１０枚分を推理するとか\nそんなことになるとさすがにキツいけどなぁ。
175 = "とはいえ、この先、１０枚分を推理するとか\\nそんなことになるとさすがにキツいけどなぁ。"

# アクア
# そうなる前に、私が物理的になんとかしてあげるわ。
168 = "そうなる前に、私が物理的になんとかしてあげるわ。"

# カズマ
# おい！？\nそれってつまり俺のこと亡き者にする気だろ！？
166 = "おい！？\\nそれってつまり俺のこと亡き者にする気だろ！？"

# アクア
# そんなことはないわよぉ？\n女神の慈悲の心でこの世の苦しみから\n解き放ってあげるだけよ、感謝しなさい。
170 = "そんなことはないわよぉ？\\n女神の慈悲の心でこの世の苦しみから\\n解き放ってあげるだけよ、感謝しなさい。"

# カズマ
# てか、立ち直るのはえーよ！\nお前はもっと反省しとけ！
174 = "てか、立ち直るのはえーよ！\\nお前はもっと反省しとけ！"

# めぐみん
# それで、やっぱりやるんです？\nいつもの変態裁判。
169 = "それで、やっぱりやるんです？\\nいつもの変態裁判。"

# カズマ
# 当然！\n俺の紳士の心は止まらないし止められないぜ！！\n今回も見事、持ち主を当ててみせる！
189 = "当然！\\n俺の紳士の心は止まらないし止められないぜ！！\\n今回も見事、持ち主を当ててみせる！"

# カズマ
# てか、変態じゃねえよ！\nむしろ紳士的な行為だ！
173 = "てか、変態じゃねえよ！\\nむしろ紳士的な行為だ！"

