# tr03_03.txt.scn

[info]
0 = ""

[characters]
166 = "ゆんゆん"
169 = "カズマ"
167 = "アクア"
171 = "クリス"
170 = "カズマ（Ｍ）"

[character_subs]
# 169 = "カズマ"

[script]
# lines: 17

# ゆんゆん
# あ、あの！\n待ってくださいっ！
153 = "あ、あの！\\n待ってくださいっ！"

# カズマ
# おわっ！？\nなんだ、どうしたんだ？
155 = "おわっ！？\\nなんだ、どうしたんだ？"

# ゆんゆん
# こ、今回の３枚のうち、\n２枚は私のパンツなんです！！
156 = "こ、今回の３枚のうち、\\n２枚は私のパンツなんです！！"

# カズマ
# はあ！？\nま、まさかの自己申告！？
164 = "はあ！？\\nま、まさかの自己申告！？"

# ゆんゆん
# だ、だって……\nカズマさんに辱められるくらいなら\n自分で言っちゃったほうがいいと思って。
161 = "だ、だって……\\nカズマさんに辱められるくらいなら\\n自分で言っちゃったほうがいいと思って。"

# アクア
# その潔さ、素晴らしいわ！\nこの女神アクアの名において\n祝福を与えたいくらいよ！
159 = "その潔さ、素晴らしいわ！\\nこの女神アクアの名において\\n祝福を与えたいくらいよ！"

# ゆんゆん
# は、はあ。
163 = "は、はあ。"

# クリス
# アクアさん、そこまでにしておいて。\nゆんゆんが困ってるから。
168 = "アクアさん、そこまでにしておいて。\\nゆんゆんが困ってるから。"

# カズマ
# じゃあ、どれとどれがゆんゆんのパンツなんだ？\n正直に言ってくれ。
157 = "じゃあ、どれとどれがゆんゆんのパンツなんだ？\\n正直に言ってくれ。"

# ゆんゆん
# え、えっと、水色以外の２枚です。
154 = "え、えっと、水色以外の２枚です。"

# カズマ（Ｍ）
# display as カズマ
# （これは……素直に信じていいんだろうか？\n　確かに、ゆんゆんは軽々しく\n　嘘をつくような子ではないとは思うけど）
193 = "（これは……素直に信じていいんだろうか？\\n　確かに、ゆんゆんは軽々しく\\n　嘘をつくような子ではないとは思うけど）"

# カズマ
# なあ、ゆんゆん。\n今まで指輪の力で盗んでいたのは\n穿いている物だけだったんだ。
162 = "なあ、ゆんゆん。\\n今まで指輪の力で盗んでいたのは\\n穿いている物だけだったんだ。"

# ゆんゆん
# それがどうしたんですか？
160 = "それがどうしたんですか？"

# カズマ
# ２枚ともゆんゆんの物だって言うのなら、\n少なくとも１枚は、穿いてないのを\n盗んだってことになるだろ？
195 = "２枚ともゆんゆんの物だって言うのなら、\\n少なくとも１枚は、穿いてないのを\\n盗んだってことになるだろ？"

# ゆんゆん
# そ、そ、そうです！\nクローゼットにしまっておいた物を\n盗まれたんです！！
158 = "そ、そ、そうです！\\nクローゼットにしまっておいた物を\\n盗まれたんです！！"

# カズマ（Ｍ）
# display as カズマ
# （この反応、なんだか妙だ。\n　きっとゆんゆんは何か隠しているな）
192 = "（この反応、なんだか妙だ。\\n　きっとゆんゆんは何か隠しているな）"

# カズマ（Ｍ）
# display as カズマ
# （よし、まずは本当に２枚とも\n　ゆんゆんの物かを推理してみるか）
194 = "（よし、まずは本当に２枚とも\\n　ゆんゆんの物かを推理してみるか）"

