# tr03_05.txt.scn

[info]
0 = ""

[characters]
147 = "カズマ（Ｍ）"
146 = "カズマ"

[character_subs]
# 146 = "カズマ"

[script]
# lines: 11

# カズマ（Ｍ）
# display as カズマ
# （それから……\n　ゆんゆんのパンツではないってのは\n　果たして、あり得るのか？）
166 = "（それから……\\n　ゆんゆんのパンツではないってのは\\n　果たして、あり得るのか？）"

# カズマ（Ｍ）
# display as カズマ
# （自分のパンツを取られた、\n　なんて嘘をわざわざ言うなんて\n　ダクネスみたいなドＭでもないとやらないだろ）
167 = "（自分のパンツを取られた、\\n　なんて嘘をわざわざ言うなんて\\n　ダクネスみたいなドＭでもないとやらないだろ）"

# カズマ（Ｍ）
# display as カズマ
# （……いや、待てよ？\n　ゆんゆんは献身的なところがあるし\n　あり得なくもないのか？）
158 = "（……いや、待てよ？\\n　ゆんゆんは献身的なところがあるし\\n　あり得なくもないのか？）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、これは判断が難しいな。\n　なにかヒントになる証言はなかったか？）
161 = "（うーん、これは判断が難しいな。\\n　なにかヒントになる証言はなかったか？）"

# カズマ（Ｍ）
# display as カズマ
# （いや、ダクネスの冷え性は今は関係ないぞ）
160 = "（いや、ダクネスの冷え性は今は関係ないぞ）"

# カズマ（Ｍ）
# display as カズマ
# （これは俺を蔑む言葉だから、\n　ゆんゆんのパンツには関係ないか）
165 = "（これは俺を蔑む言葉だから、\\n　ゆんゆんのパンツには関係ないか）"

# カズマ（Ｍ）
# display as カズマ
# （この発言も気にはなるけど、\n　もっと決定的な証拠になりそうな\n　発言があったような……）
164 = "（この発言も気にはなるけど、\\n　もっと決定的な証拠になりそうな\\n　発言があったような……）"

# カズマ（Ｍ）
# display as カズマ
# （……ここで俺の発言を\n　証拠にするのは難しそうだな）
159 = "（……ここで俺の発言を\\n　証拠にするのは難しそうだな）"

# カズマ（Ｍ）
# display as カズマ
# （この発言は、ゆんゆんのパンツには\n　関係ないだろ。考え直そう）
163 = "（この発言は、ゆんゆんのパンツには\\n　関係ないだろ。考え直そう）"

# カズマ（Ｍ）
# display as カズマ
# （このアクアの発言が証拠になるとは思えないな）
162 = "（このアクアの発言が証拠になるとは思えないな）"

# カズマ
# 実は、気になった発言があるんだよ。
151 = "実は、気になった発言があるんだよ。"

[selections]
139 = "そうですよ。\\nこっちは落としても落とせない憑き物を\\n抱えているんですからね。"
157 = "私、朝起きたらパンツを穿いてないなんて、\\n恥ずかしくて耐えられません！"
143 = "もう……指輪もろとも\\n火口に放り込んじゃいませんか？"
137 = "い、いや、今日は冷えるなと。\\n特に腰のあたりが！"
141 = "へきしっ！！　うーっ、\\n何だが身体が冷えてきちゃったみたい。\\n私も戻ろっと。"
138 = "いや、私はここに残る。\\nそしてぜひ、カズマにも残って欲しい。"
140 = "そのわりに、さっきと全然変わってないじゃないか。\\nモジモジして、動きがぎこちないぞ。"
