# tr03_07.txt.scn

[info]
0 = ""

[characters]
175 = "カズマ"
171 = "ゆんゆん"
178 = "ダクネス"
177 = "クリス"
173 = "アクア"
176 = "カズマ（Ｍ）"

[character_subs]
# 175 = "カズマ"

[script]
# lines: 15

# カズマ
# もちろん、俺はゆんゆんが\n嘘つきだなんて決めつけるつもりはない。
170 = "もちろん、俺はゆんゆんが\\n嘘つきだなんて決めつけるつもりはない。"

# カズマ
# おそらくだが……\nどちらかのパンツはゆんゆんの物なんだ。
160 = "おそらくだが……\\nどちらかのパンツはゆんゆんの物なんだ。"

# ゆんゆん
# ち、違います！\nどちらも私の物なんです！
165 = "ち、違います！\\nどちらも私の物なんです！"

# カズマ
# ゆんゆん。\n俺の身に降りかかった呪いは\n穿いているパンツを奪うものだ。
172 = "ゆんゆん。\\n俺の身に降りかかった呪いは\\n穿いているパンツを奪うものだ。"

# カズマ
# 実際、今まで盗んできたのは\n穿いている物ばかりだったわけだしな。
181 = "実際、今まで盗んできたのは\\n穿いている物ばかりだったわけだしな。"

# ゆんゆん
# でも、そう決まったわけじゃ……。
167 = "でも、そう決まったわけじゃ……。"

# カズマ
# だけどさ、パンツを盗むだけなら\nクローゼットを漁った方がよほど楽なんだ。
164 = "だけどさ、パンツを盗むだけなら\\nクローゼットを漁った方がよほど楽なんだ。"

# カズマ
# けど、あえて穿いている物ばかり盗んできた\n事実から考えて、ほぼ間違いない。
161 = "けど、あえて穿いている物ばかり盗んできた\\n事実から考えて、ほぼ間違いない。"

# カズマ
# しかも、パンツを奪ったが最後、\n相手をパンツを穿けない状態にしてしまう。
162 = "しかも、パンツを奪ったが最後、\\n相手をパンツを穿けない状態にしてしまう。"

# カズマ
# つまり！\n同一人物から、同一時間にパンツを\n２枚奪うことは不可能なんだよっ！
166 = "つまり！\\n同一人物から、同一時間にパンツを\\n２枚奪うことは不可能なんだよっ！"

# ダクネス
# た、確かに……！
163 = "た、確かに……！"

# クリス
# いや、そんなにビックリするところじゃ\nないと思うよ？
158 = "いや、そんなにビックリするところじゃ\\nないと思うよ？"

# ゆんゆん
# ふ、不可能じゃありません！\n実は２枚重ねて穿いていたんです！
168 = "ふ、不可能じゃありません！\\n実は２枚重ねて穿いていたんです！"

# アクア
# ええ？\nそれってどういう状況なの？\nうっかりって問題じゃなくない？
159 = "ええ？\\nそれってどういう状況なの？\\nうっかりって問題じゃなくない？"

# カズマ（Ｍ）
# display as カズマ
# （……アクアのツッコミはともかく\n　ゆんゆん、なかなかごねるな。\n　だが、ここで負けるわけにはいかないぜ！）
195 = "（……アクアのツッコミはともかく\\n　ゆんゆん、なかなかごねるな。\\n　だが、ここで負けるわけにはいかないぜ！）"

