# tr03_09.txt.scn

[info]
0 = ""

[characters]
167 = "カズマ（Ｍ）"

[character_subs]
166 = "カズマ"

[script]
# lines: 10

# カズマ（Ｍ）
# display as カズマ
# （これはつまり、\n　パンツを穿いていなかったからなんだ！）
185 = "（これはつまり、\\n　パンツを穿いていなかったからなんだ！）"

# カズマ（Ｍ）
# display as カズマ
# （うん！\n　いいセンいってるんじゃないか、この推理は）
180 = "（うん！\\n　いいセンいってるんじゃないか、この推理は）"

# カズマ（Ｍ）
# display as カズマ
# （ここでひとつ、\n　だめ押しの証拠が欲しいところだな。\n　なにかなかったか？）
181 = "（ここでひとつ、\\n　だめ押しの証拠が欲しいところだな。\\n　なにかなかったか？）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスの冷え性は、\n　なんの証拠にもならないだろ）
187 = "（ダクネスの冷え性は、\\n　なんの証拠にもならないだろ）"

# カズマ（Ｍ）
# display as カズマ
# （この発言も気にはなるけど、\n　もっと決定的な証拠になりそうな\n　発言があったような……）
183 = "（この発言も気にはなるけど、\\n　もっと決定的な証拠になりそうな\\n　発言があったような……）"

# カズマ（Ｍ）
# display as カズマ
# （いま証明しようとしてるパンツの持ち主は\n　めぐみんとゆんゆんだ。\n　ダクネスは関係ないよな）
179 = "（いま証明しようとしてるパンツの持ち主は\\n　めぐみんとゆんゆんだ。\\n　ダクネスは関係ないよな）"

# カズマ（Ｍ）
# display as カズマ
# （このアクアの発言が証拠になるとは思えないな）
182 = "（このアクアの発言が証拠になるとは思えないな）"

# カズマ（Ｍ）
# display as カズマ
# （これは、今回の証言にはなりそうにないな。\n　別の発言を思い出してみよう）
184 = "（これは、今回の証言にはなりそうにないな。\\n　別の発言を思い出してみよう）"

# カズマ（Ｍ）
# display as カズマ
# （これは、今回の証言にはなりそうにないな。\n　別の発言を思い出してみよう）
# 184 = "（これは、今回の証言にはなりそうにないな。\\n　別の発言を思い出してみよう）"

# カズマ（Ｍ）
# display as カズマ
# （そうだ！\n　外で練習をしている時――）
186 = "（そうだ！\\n　外で練習をしている時――）"

[selections]
162 = "もう……指輪もろとも\\n火口に放り込んじゃいませんか？"
155 = "い、いや、今日は冷えるなと。\\n特に腰のあたりが！"
158 = "とにかく今は都合が悪いんです！\\nやるなら、そうですね、\\nゆんゆんからにしてください！"
157 = "だ、だって、採寸をすると言うことは\\nカズマさんが近づくと言うことですよね？"
159 = "へきしっ！！　うーっ、\\n何だが身体が冷えてきちゃったみたい。\\n私も戻ろっと。"
160 = "ほ、放置プレイか。\\nそういう扱いも嫌いではないぞ。"
156 = "そのわりに、さっきと全然変わってないじゃないか。\\nモジモジして、動きがぎこちないぞ。"
