# tr03_06.txt.scn

[info]
0 = ""

[characters]
166 = "カズマ"
167 = "クリス"
164 = "アクア"
165 = "ウィズ"
162 = "ゆんゆん"
161 = "めぐみん"

[character_subs]

[script]
# lines: 16

# カズマ
# ゆんゆんは言ったよな？\n『指輪もろとも火口に放り込んじゃいませんか？』\nってさ。
163 = "ゆんゆんは言ったよな？\\n『指輪もろとも火口に放り込んじゃいませんか？』\\nってさ。"

# カズマ
# この発言に俺はマジでビビったわけだが……\nおかしいと思わないか？
153 = "この発言に俺はマジでビビったわけだが……\\nおかしいと思わないか？"

# クリス
# え？　どこが？\nキミがしていることを考えれば\n言いたくなる気持ちもわかるけどな。
152 = "え？　どこが？\\nキミがしていることを考えれば\\n言いたくなる気持ちもわかるけどな。"

# カズマ
# いや、まあ、そこは否定しないけど、\nでもゆんゆんだぜ？\nアクアやめぐみんでもない、ゆんゆんが言ったんだ。
150 = "いや、まあ、そこは否定しないけど、\\nでもゆんゆんだぜ？\\nアクアやめぐみんでもない、ゆんゆんが言ったんだ。"

# アクア
# ちょっと？\nその言い方、引っかかるんですけど。
159 = "ちょっと？\\nその言い方、引っかかるんですけど。"

# カズマ
# 俺はこの発言に闇を感じた。\n普段のゆんゆんからは感じられない、\nドス黒い言葉だったからな。
170 = "俺はこの発言に闇を感じた。\\n普段のゆんゆんからは感じられない、\\nドス黒い言葉だったからな。"

# ウィズ
# ああ、言われてみれば確かに\nゆんゆんさんらしくない気がしますね。
149 = "ああ、言われてみれば確かに\\nゆんゆんさんらしくない気がしますね。"

# カズマ
# だろう？
158 = "だろう？"

# ゆんゆん
# そ、そんなことないです！\n私だってそのくらい言いますよっ！\nカズマさんの誤解ですから！
154 = "そ、そんなことないです！\\n私だってそのくらい言いますよっ！\\nカズマさんの誤解ですから！"

# ゆんゆん
# それよりも、早くパンツを返してください！\n２枚とも私の物なんですから！
156 = "それよりも、早くパンツを返してください！\\n２枚とも私の物なんですから！"

# カズマ
# 断るっ！\nなぜなら、２枚のうちどちらかは\nゆんゆんの物ではないからだ！
173 = "断るっ！\\nなぜなら、２枚のうちどちらかは\\nゆんゆんの物ではないからだ！"

# ゆんゆん
# ええっ！？\nな、なにを根拠にそんなことを……。
151 = "ええっ！？\\nな、なにを根拠にそんなことを……。"

# めぐみん
# そうですよ。\nゆんゆんが言っているのですから、\nゆんゆんのことを信じましょう。
155 = "そうですよ。\\nゆんゆんが言っているのですから、\\nゆんゆんのことを信じましょう。"

# ゆんゆん
# だ、だよねっ！\nめぐみんは私のことを信じてくれるよね！
157 = "だ、だよねっ！\\nめぐみんは私のことを信じてくれるよね！"

# カズマ
# ダメだ。\n俺は真実を追求する！\n納得するまでとことん追求させてもらう！
168 = "ダメだ。\\n俺は真実を追求する！\\n納得するまでとことん追求させてもらう！"

# アクア
# なんで、パンツでこんなシリアス展開なのよ。
160 = "なんで、パンツでこんなシリアス展開なのよ。"

