# tr03_11.txt.scn

[info]
0 = ""

[characters]
231 = "カズマ"
220 = "めぐみん"
222 = "ゆんゆん"
232 = "カズマ（Ｍ）"
228 = "アクア"

[character_subs]
# 231 = "カズマ"

[script]
# lines: 33

# カズマ
# ゆんゆん。\nお前とめぐみんの友情は素晴らしいものだと思う。
223 = "ゆんゆん。\\nお前とめぐみんの友情は素晴らしいものだと思う。"

# カズマ
# だか俺は、真実を追い求める者として\n目をそらさずに言わせてもらう。
210 = "だか俺は、真実を追い求める者として\\n目をそらさずに言わせてもらう。"

# カズマ
# この黒パンツと\n黒とピンクの縞々パンツのどちらかは、\nめぐみんの物なんだろう？
206 = "この黒パンツと\\n黒とピンクの縞々パンツのどちらかは、\\nめぐみんの物なんだろう？"

# めぐみん
# は、はあっ！？\nきゅきゅ、急になにを言い出すんですか！！
215 = "は、はあっ！？\\nきゅきゅ、急になにを言い出すんですか！！"

# めぐみん
# わわわ、私のパンツなわけないでしょう！？\nそうですよね、ゆんゆん！
227 = "わわわ、私のパンツなわけないでしょう！？\\nそうですよね、ゆんゆん！"

# ゆんゆん
# う、うん！\n何度も言ってますけど、\nどちらも私のパンツですよっ！
204 = "う、うん！\\n何度も言ってますけど、\\nどちらも私のパンツですよっ！"

# めぐみん
# ほら、本人がこう言ってるんですよ？\nそれ以上の証拠があるというのですか？
217 = "ほら、本人がこう言ってるんですよ？\\nそれ以上の証拠があるというのですか？"

# カズマ
# ああ、あるぜ。\nじっくり聞かせてやろう。
202 = "ああ、あるぜ。\\nじっくり聞かせてやろう。"

# カズマ
# まず１つ目！\nアイドル衣装を作るために採寸をしたとき――
218 = "まず１つ目！\\nアイドル衣装を作るために採寸をしたとき――"

# カズマ
# ゆんゆんもめぐみんも、俺に計測されるのを\nすごく嫌がってたよな？
224 = "ゆんゆんもめぐみんも、俺に計測されるのを\\nすごく嫌がってたよな？"

# めぐみん
# 当たり前ですよ！\nカズマみたいな下着泥棒の変態に触られるなんて\n嫌に決まってます！
242 = "当たり前ですよ！\\nカズマみたいな下着泥棒の変態に触られるなんて\\n嫌に決まってます！"

# カズマ
# 好きで取ってんじゃねーよ！\nそれに俺は紳士としてちゃんと返そうって\n努力をしてるだろ！？
240 = "好きで取ってんじゃねーよ！\\nそれに俺は紳士としてちゃんと返そうって\\n努力をしてるだろ！？"

# カズマ
# それに、触られるのが\n嫌だったわけじゃないよなぁ？
209 = "それに、触られるのが\\n嫌だったわけじゃないよなぁ？"

# めぐみん
# ど、どうしてそんなことが言えるのですか？
214 = "ど、どうしてそんなことが言えるのですか？"

# カズマ
# でなければ、練習の時に\n風やスカートを気にする必要はないもんな？\nそれが２つ目の証拠だ！
213 = "でなければ、練習の時に\\n風やスカートを気にする必要はないもんな？\\nそれが２つ目の証拠だ！"

# めぐみん
# そ、それは……！
208 = "そ、それは……！"

# ゆんゆん
# め、めぐみん、もうダメだよ。\nカズマさんは……\nもう全部、わかっちゃってるんだよ。
219 = "め、めぐみん、もうダメだよ。\\nカズマさんは……\\nもう全部、わかっちゃってるんだよ。"

# めぐみん
# ゆんゆん！？\nま、待ってください、あきらめるのは早いですよ！
226 = "ゆんゆん！？\\nま、待ってください、あきらめるのは早いですよ！"

# ゆんゆん
# で、でも、これ以上、\n問い詰められたら、私、もう……！
211 = "で、でも、これ以上、\\n問い詰められたら、私、もう……！"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんがあと少しでオチそうだ。\n　よし、ここはハッタリをかまして押し込もう！）
278 = "（ゆんゆんがあと少しでオチそうだ。\\n　よし、ここはハッタリをかまして押し込もう！）"

# カズマ
# 俺にはまだいくつも証拠があるんだ。\nこれ以上、追い込まれたくなければ\n素直に認めるべきだな。
236 = "俺にはまだいくつも証拠があるんだ。\\nこれ以上、追い込まれたくなければ\\n素直に認めるべきだな。"

# ゆんゆん
# ひうっ！？\nご、ご、ごめんなさい！　もうやめてください！\n認めます！　認めますから！
216 = "ひうっ！？\\nご、ご、ごめんなさい！　もうやめてください！\\n認めます！　認めますから！"

# カズマ
# 認める？\nそれはなにを認めるってことかな？
276 = "認める？\\nそれはなにを認めるってことかな？"

# ゆんゆん
# そ、その２枚のパンツは\n私とめぐみんの物ですっ！
207 = "そ、その２枚のパンツは\\n私とめぐみんの物ですっ！"

# めぐみん
# ゆんゆん！？
225 = "ゆんゆん！？"

# ゆんゆん
# で、でも、嘘をついたのは私です！
212 = "で、でも、嘘をついたのは私です！"

# ゆんゆん
# めぐみんに、２枚とも私の物だって言って\nカズマさんを誤魔化そうって言いだしたのも\n私なんです！
221 = "めぐみんに、２枚とも私の物だって言って\\nカズマさんを誤魔化そうって言いだしたのも\\n私なんです！"

# カズマ（Ｍ）
# display as カズマ
# （ああ、やっぱりか。\n　それはゆんゆんらしいな）
277 = "（ああ、やっぱりか。\\n　それはゆんゆんらしいな）"

# ゆんゆん
# 全部、私が悪いんです。\n私を罰してください！
237 = "全部、私が悪いんです。\\n私を罰してください！"

# めぐみん
# え、ゆんゆん……。
205 = "え、ゆんゆん……。"

# カズマ
# 大丈夫だ。\n俺は真実を探求していただけで、\n決して２人を蔑んだわけではないんだよ。
239 = "大丈夫だ。\\n俺は真実を探求していただけで、\\n決して２人を蔑んだわけではないんだよ。"

# めぐみん
# ……はあ。
201 = "……はあ。"

# アクア
# いい笑顔でなにを言ってるのかしらねぇ、本当に。
203 = "いい笑顔でなにを言ってるのかしらねぇ、本当に。"

