# tr03_15.txt.scn

[info]
0 = ""

[characters]
157 = "カズマ（Ｍ）"
154 = "アクア"
156 = "カズマ"
155 = "ウィズ"
152 = "めぐみん"
158 = "クリス"
153 = "ゆんゆん"

[character_subs]
# 156 = "カズマ"

[script]
# lines: 14

# カズマ（Ｍ）
# display as カズマ
# （くっ……。\n　ダメだ、これ以上の推理はできそうにない）
174 = "（くっ……。\\n　ダメだ、これ以上の推理はできそうにない）"

# アクア
# あらあら？\n張り切ってたのにもう終わり？
143 = "あらあら？\\n張り切ってたのにもう終わり？"

# カズマ
# うう……。
145 = "うう……。"

# ウィズ
# こ、今回は調子が悪かったんですよ。\n色々ありましたし。
147 = "こ、今回は調子が悪かったんですよ。\\n色々ありましたし。"

# カズマ
# そ、そうだな。\nこういう事もたまにはあるよな。
149 = "そ、そうだな。\\nこういう事もたまにはあるよな。"

# めぐみん
# どうして惜しかった風な流れにしているのですか。\n失敗は失敗ですよ。
150 = "どうして惜しかった風な流れにしているのですか。\\n失敗は失敗ですよ。"

# カズマ（Ｍ）
# display as カズマ
# （ぐぬぬぬぬぅ……）
175 = "（ぐぬぬぬぬぅ……）"

# クリス
# 残念だったね。\nそれじゃ、そろそろパンツ返してもらえる？
163 = "残念だったね。\\nそれじゃ、そろそろパンツ返してもらえる？"

# ゆんゆん
# ……こ、こっちにもお願いします。
142 = "……こ、こっちにもお願いします。"

# カズマ
# はっ！\n今回のパンツの持ち主は\nクリスとゆんゆんだったのか！？
151 = "はっ！\\n今回のパンツの持ち主は\\nクリスとゆんゆんだったのか！？"

# クリス
# いやぁ、違うんだけどね？\nここは私から返そうと思ってさ。
144 = "いやぁ、違うんだけどね？\\nここは私から返そうと思ってさ。"

# クリス
# 構わないでしょ？\nキミは持ち主を当てられなかったんだから。
162 = "構わないでしょ？\\nキミは持ち主を当てられなかったんだから。"

# カズマ
# お、おう。
146 = "お、おう。"

# アクア
# さあて！\nそれじゃ、わかってるでしょうけど\nお待ちかねのお仕置きの時間よ！
148 = "さあて！\\nそれじゃ、わかってるでしょうけど\\nお待ちかねのお仕置きの時間よ！"

