# tr03_04.txt.scn

[info]
0 = ""

[characters]
73 = "カズマ（Ｍ）"

[character_subs]
72 = "カズマ"

[script]
# lines: 6

# カズマ（Ｍ）
# display as カズマ
# （最初はパンツの再検証だ）
81 = "（最初はパンツの再検証だ）"

# カズマ（Ｍ）
# display as カズマ
# （水色のパンツは後回しにするとして、\n　ゆんゆんが自分の物と言い張っているのは\n　黒と、黒とピンクの縞々のパンツ）
82 = "（水色のパンツは後回しにするとして、\\n　ゆんゆんが自分の物と言い張っているのは\\n　黒と、黒とピンクの縞々のパンツ）"

# カズマ（Ｍ）
# display as カズマ
# （この場合、想像できるのは３パターン）
80 = "（この場合、想像できるのは３パターン）"

# カズマ（Ｍ）
# display as カズマ
# （２枚とも本当にゆんゆんのパンツである場合、\n　１枚はゆんゆん、もう１枚は誰かのパンツの場合、\n　そして、どちらもゆんゆんのパンツではない場合）
83 = "（２枚とも本当にゆんゆんのパンツである場合、\\n　１枚はゆんゆん、もう１枚は誰かのパンツの場合、\\n　そして、どちらもゆんゆんのパンツではない場合）"

# カズマ（Ｍ）
# display as カズマ
# （ここで問題になるのは、\n　指輪はいままで穿いているパンツを\n　盗み出していたってことだな）
79 = "（ここで問題になるのは、\\n　指輪はいままで穿いているパンツを\\n　盗み出していたってことだな）"

# カズマ（Ｍ）
# display as カズマ
# （ここで呪いのルールが変わるとは思えない。\n　となると、２枚ともゆんゆんだって\n　パターンは消えるか）
78 = "（ここで呪いのルールが変わるとは思えない。\\n　となると、２枚ともゆんゆんだって\\n　パターンは消えるか）"

