# tr03_12.txt.scn

[info]
0 = ""

[characters]
88 = "カズマ（Ｍ）"

[character_subs]
87 = "カズマ"

[script]
# lines: 3

# カズマ（Ｍ）
# display as カズマ
# （さて、残るは水色のパンツか。\n　誰の物なんだ？\n　いまのところ、見当もつかない）
95 = "（さて、残るは水色のパンツか。\\n　誰の物なんだ？\\n　いまのところ、見当もつかない）"

# カズマ（Ｍ）
# display as カズマ
# （もう一度、冷静に思い返してみよう。\n　めぐみんとゆんゆん以外で\n　おかしな行動を取ってた人の名前は……）
96 = "（もう一度、冷静に思い返してみよう。\\n　めぐみんとゆんゆん以外で\\n　おかしな行動を取ってた人の名前は……）"

# カズマ（Ｍ）
# display as カズマ
# （わかったぞ、こいつだ！）
97 = "（わかったぞ、こいつだ！）"

