# tr03_14.txt.scn

[info]
0 = ""

[characters]
295 = "カズマ"
298 = "ダクネス"
297 = "クリス"
293 = "ウィズ"
284 = "めぐみん"
288 = "ゆんゆん"
292 = "アクア"
296 = "カズマ（Ｍ）"

[character_subs]
# 295 = "カズマ"

[script]
# lines: 48

# カズマ
# わかったぞ！\nこのパンツの持ち主は、ダクネス！　お前だ！
290 = "わかったぞ！\\nこのパンツの持ち主は、ダクネス！　お前だ！"

# ダクネス
# な、なぜだっ！\nなぜそう思うのか説明してみせろ！\nさあ、皆の前で私のすべてを暴いてみせろっ！
277 = "な、なぜだっ！\\nなぜそう思うのか説明してみせろ！\\nさあ、皆の前で私のすべてを暴いてみせろっ！"

# クリス
# ……あの態度がもう正解だって\n語ってるようなものじゃない。
254 = "……あの態度がもう正解だって\\n語ってるようなものじゃない。"

# カズマ
# いいだろう、望み通りに\nお前のすべてを白日の元にさらしてやる！
258 = "いいだろう、望み通りに\\nお前のすべてを白日の元にさらしてやる！"

# ウィズ
# なんだか、カズマさんまでノリノリですね。
280 = "なんだか、カズマさんまでノリノリですね。"

# カズマ
# まず１つめ！\nここ最近、お前のドＭな言動が過剰だったこと！
283 = "まず１つめ！\\nここ最近、お前のドＭな言動が過剰だったこと！"

# カズマ
# 例えば、発声練習の時、\nみんな引き上げようとしているのに\nお前は残るって言ったよな？
302 = "例えば、発声練習の時、\\nみんな引き上げようとしているのに\\nお前は残るって言ったよな？"

# カズマ
# それは、風でスカートがめくれそうなスリルを\n味わっていたんだろう？
271 = "それは、風でスカートがめくれそうなスリルを\\n味わっていたんだろう？"

# カズマ
# そしてお前は、俺に側に居て欲しいと言った！\nそれは、なぜか！
268 = "そしてお前は、俺に側に居て欲しいと言った！\\nそれは、なぜか！"

# ダクネス
# ハァハァ、なぜなんだ、言ってみろ。
299 = "ハァハァ、なぜなんだ、言ってみろ。"

# カズマ
# 俺に見られるかもしれないというスリルを\n味わっていたからだろ！
303 = "俺に見られるかもしれないというスリルを\\n味わっていたからだろ！"

# ダクネス
# にゅ、にゅぅぅっ！！
281 = "にゅ、にゅぅぅっ！！"

# カズマ
# それにもう１つ！\nお前、腰のあたりが冷えるって言ってたよな？
270 = "それにもう１つ！\\nお前、腰のあたりが冷えるって言ってたよな？"

# カズマ
# でも俺も周りのみんなも寒さなんて\nまったく感じていなかった。
276 = "でも俺も周りのみんなも寒さなんて\\nまったく感じていなかった。"

# カズマ
# これはつまり！\nお前が穿いていないから\nスースーしていたってことだ！
265 = "これはつまり！\\nお前が穿いていないから\\nスースーしていたってことだ！"

# ダクネス
# く、にゅぅぅんっ！\nさすがはカズマ……\nこのような仕打ちを平然と……！
262 = "く、にゅぅぅんっ！\\nさすがはカズマ……\\nこのような仕打ちを平然と……！"

# カズマ
# ていうか、\nわかりやすすぎるんだよ、ダクネスは！
275 = "ていうか、\\nわかりやすすぎるんだよ、ダクネスは！"

# ダクネス
# つまり、今まで素知らぬふりをして、\n私を精神的に追い込んでいたということか！
274 = "つまり、今まで素知らぬふりをして、\\n私を精神的に追い込んでいたということか！"

# ダクネス
# な、何という鬼畜！！\nだが、そうとは気づかずに、\nカズマに弄ばれてしまった私は……！
278 = "な、何という鬼畜！！\\nだが、そうとは気づかずに、\\nカズマに弄ばれてしまった私は……！"

# めぐみん
# も、もういいですから！\nそれは私のパンツです！\nだ、だから、返してください！
285 = "も、もういいですから！\\nそれは私のパンツです！\\nだ、だから、返してください！"

# ゆんゆん
# わ、私のも……返してください。
289 = "わ、私のも……返してください。"

# カズマ
# はーははははは！\nどうだ、俺の冴えた推理力は！
282 = "はーははははは！\\nどうだ、俺の冴えた推理力は！"

# カズマ
# わずかな手がかりから\n正解を導き出したこの才能は大したもんだろ？
291 = "わずかな手がかりから\\n正解を導き出したこの才能は大したもんだろ？"

# カズマ
# いやぁ、よかったよかった。\nこれにて一件落着！
259 = "いやぁ、よかったよかった。\\nこれにて一件落着！"

# ゆんゆん
# だ、だから、パンツを返してください！\nなんでずっと握りしめてるんですか！
272 = "だ、だから、パンツを返してください！\\nなんでずっと握りしめてるんですか！"

# めぐみん
# それとも、爆裂魔法を味わいたいのですか？
269 = "それとも、爆裂魔法を味わいたいのですか？"

# カズマ
# ちょ、待て待て！\nちゃんと返すって、ほら！
273 = "ちょ、待て待て！\\nちゃんと返すって、ほら！"

# アクア
# ああ、こんな幼い子供達のパンツを\n取り上げるなんて、なんて非道なのかしら。
257 = "ああ、こんな幼い子供達のパンツを\\n取り上げるなんて、なんて非道なのかしら。"

# めぐみん
# こ、子供じゃないわい！
263 = "こ、子供じゃないわい！"

# クリス
# うん、ちょっとやり過ぎかもしれないね。
261 = "うん、ちょっとやり過ぎかもしれないね。"

# ウィズ
# この前も、こんな感じでしたが……。
264 = "この前も、こんな感じでしたが……。"

# カズマ（Ｍ）
# display as カズマ
# （えっ？　あ、あれっ？\n　なんでみんな、そんな冷たい目で俺を見てるの？）
345 = "（えっ？　あ、あれっ？\\n　なんでみんな、そんな冷たい目で俺を見てるの？）"

# カズマ（Ｍ）
# display as カズマ
# （お、俺は紳士的にパンツを返そうと\n　していただけなのに！？）
346 = "（お、俺は紳士的にパンツを返そうと\\n　していただけなのに！？）"

# ダクネス
# 大丈夫だ、カズマ。\nまだ続けても構わない。
305 = "大丈夫だ、カズマ。\\nまだ続けても構わない。"

# ダクネス
# パンツの持ち主だとわかった上で\n私を弄ぶなら、それはそれで……！
300 = "パンツの持ち主だとわかった上で\\n私を弄ぶなら、それはそれで……！"

# クリス
# そう思ってるのはダクネスだけだから。
267 = "そう思ってるのはダクネスだけだから。"

# カズマ（Ｍ）
# display as カズマ
# （ふう……。\n　にしても、この裁判はいいなぁ）
347 = "（ふう……。\\n　にしても、この裁判はいいなぁ）"

# カズマ（Ｍ）
# display as カズマ
# （パンツの持ち主を当てた時の爽快感！\n　そして、今まで隠し通してきた末の\n　真っ赤に染まるこいつらの顔が特に！）
349 = "（パンツの持ち主を当てた時の爽快感！\\n　そして、今まで隠し通してきた末の\\n　真っ赤に染まるこいつらの顔が特に！）"

# アクア
# ……ねえ、なにニヤニヤしてるのよ。\nすっごく気持ち悪いんですけど？
256 = "……ねえ、なにニヤニヤしてるのよ。\\nすっごく気持ち悪いんですけど？"

# クリス
# 妄想するのはそれぞれの自由だけど、\n今のタイミングではちょっとねぇ。
306 = "妄想するのはそれぞれの自由だけど、\\n今のタイミングではちょっとねぇ。"

# めぐみん
# やっぱり、火口に放り込みましょうか。\n指輪ごと消滅させて、今後このような\n不幸な出来事が起きないようにすべきです。
287 = "やっぱり、火口に放り込みましょうか。\\n指輪ごと消滅させて、今後このような\\n不幸な出来事が起きないようにすべきです。"

# ゆんゆん
# うん、その方が世界が平和になるよね。
260 = "うん、その方が世界が平和になるよね。"

# カズマ
# なに言ってんだよ、\nパンツの持ち主を当てたんだし問題ないだろ？
279 = "なに言ってんだよ、\\nパンツの持ち主を当てたんだし問題ないだろ？"

# ゆんゆん
# もう、これ以上の犠牲者を出さない方が\n世のため人のためです。\n覚悟を決めてください。
286 = "もう、これ以上の犠牲者を出さない方が\\n世のため人のためです。\\n覚悟を決めてください。"

# カズマ
# ……え？　冗談だよな？\nちょっとしたおふざけだよな？
255 = "……え？　冗談だよな？\\nちょっとしたおふざけだよな？"

# アクア
# さあ、どうかしらねぇ？
266 = "さあ、どうかしらねぇ？"

# カズマ（Ｍ）
# display as カズマ
# （正しいパンツを正しい持ち主に返したってのに\n　この仕打ちはなんなんだよ！）
350 = "（正しいパンツを正しい持ち主に返したってのに\\n　この仕打ちはなんなんだよ！）"

# カズマ（Ｍ）
# display as カズマ
# （まさか……\n　ご褒美もなしなんてことはないよな？）
348 = "（まさか……\\n　ご褒美もなしなんてことはないよな？）"

