# tr03_08.txt.scn

[info]
0 = ""

[characters]
167 = "カズマ（Ｍ）"

[character_subs]
166 = "カズマ"

[script]
# lines: 16

# カズマ（Ｍ）
# display as カズマ
# （大体、ゆんゆんが\n　ここまで必死になっている時点で\n　怪しいんだよな）
190 = "（大体、ゆんゆんが\\n　ここまで必死になっている時点で\\n　怪しいんだよな）"

# カズマ（Ｍ）
# display as カズマ
# （……あ、そうだ！\n　ゆんゆんがここまで一所懸命になる理由って\n　めぐみんしかありえなくないか？）
175 = "（……あ、そうだ！\\n　ゆんゆんがここまで一所懸命になる理由って\\n　めぐみんしかありえなくないか？）"

# カズマ（Ｍ）
# display as カズマ
# （となると、こう考えられる。\n　多分、めぐみんもパンツを取られてるんだ）
187 = "（となると、こう考えられる。\\n　多分、めぐみんもパンツを取られてるんだ）"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんはそれを知って、\n　どちらも自分の物だって言い張ると\n　めぐみんに提案したんだろう）
189 = "（ゆんゆんはそれを知って、\\n　どちらも自分の物だって言い張ると\\n　めぐみんに提案したんだろう）"

# カズマ（Ｍ）
# display as カズマ
# （その友情は素晴らしいが、\n　俺は真実を求める紳士！）
185 = "（その友情は素晴らしいが、\\n　俺は真実を求める紳士！）"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆん、悪く思わないでくれよ。\n　俺は自らの手で\n　パンツを本来の持ち主に返したいだけなんだ）
188 = "（ゆんゆん、悪く思わないでくれよ。\\n　俺は自らの手で\\n　パンツを本来の持ち主に返したいだけなんだ）"

# カズマ（Ｍ）
# display as カズマ
# （で、ここで必要なのは推理を証明する証拠か。\n　うーん……）
186 = "（で、ここで必要なのは推理を証明する証拠か。\\n　うーん……）"

# カズマ（Ｍ）
# display as カズマ
# （ああ、そういえば！\n　アイドルの服を作るとき、めぐみんとゆんゆんの\n　採寸をさせてもらえなかったけど――）
176 = "（ああ、そういえば！\\n　アイドルの服を作るとき、めぐみんとゆんゆんの\\n　採寸をさせてもらえなかったけど――）"

# カズマ（Ｍ）
# display as カズマ
# （そのとき、俺は気になる証言を\n　聞いていたはずだ）
184 = "（そのとき、俺は気になる証言を\\n　聞いていたはずだ）"

# カズマ（Ｍ）
# display as カズマ
# （いや、あの時、\n　ダクネスはそんなこと言ってなかっただろ）
177 = "（いや、あの時、\\n　ダクネスはそんなこと言ってなかっただろ）"

# カズマ（Ｍ）
# display as カズマ
# （この発言も気にはなるけど、\n　もっと決定的な証拠になりそうな\n　発言があったような……）
181 = "（この発言も気にはなるけど、\\n　もっと決定的な証拠になりそうな\\n　発言があったような……）"

# カズマ（Ｍ）
# display as カズマ
# （いや、モジモジしていたのは\n　は踊り練習の時だったはず。\n　採寸の時じゃない）
178 = "（いや、モジモジしていたのは\\n　は踊り練習の時だったはず。\\n　採寸の時じゃない）"

# カズマ（Ｍ）
# display as カズマ
# （うん、これはいつものダクネスだ。\n　まったく関係ない）
179 = "（うん、これはいつものダクネスだ。\\n　まったく関係ない）"

# カズマ（Ｍ）
# display as カズマ
# （このアクアの発言が証拠になるとは思えないな）
180 = "（このアクアの発言が証拠になるとは思えないな）"

# カズマ（Ｍ）
# display as カズマ
# （これは、今回の証言にはなりそうにないな。\n　別の発言を思い出してみよう）
182 = "（これは、今回の証言にはなりそうにないな。\\n　別の発言を思い出してみよう）"

# カズマ（Ｍ）
# display as カズマ
# （そうだ、めぐみんとゆんゆんに\n　採寸するのを凄く嫌がられたんだよな）
183 = "（そうだ、めぐみんとゆんゆんに\\n　採寸するのを凄く嫌がられたんだよな）"

[selections]
162 = "もう……指輪もろとも\\n火口に放り込んじゃいませんか？"
155 = "い、いや、今日は冷えるなと。\\n特に腰のあたりが！"
158 = "とにかく今は都合が悪いんです！\\nやるなら、そうですね、\\nゆんゆんからにしてください！"
157 = "だ、だって、採寸をすると言うことは\\nカズマさんが近づくと言うことですよね？"
159 = "へきしっ！！　うーっ、\\n何だが身体が冷えてきちゃったみたい。\\n私も戻ろっと。"
160 = "ほ、放置プレイか。\\nそういう扱いも嫌いではないぞ。"
156 = "そのわりに、さっきと全然変わってないじゃないか。\\nモジモジして、動きがぎこちないぞ。"
