# tr03_16.txt.scn

[info]
0 = ""

[characters]

[character_subs]

[script]
# lines: 0

[selections]
123 = "アクア"
121 = "めぐみん"
126 = "ダクネス"
124 = "ウィズ"
125 = "クリス"
122 = "ゆんゆん"
# 123 = "アクア"
# 121 = "めぐみん"
# 126 = "ダクネス"
# 124 = "ウィズ"
# 125 = "クリス"
# 122 = "ゆんゆん"
