# tr03_10.txt.scn

[info]
0 = ""

[characters]
98 = "カズマ（Ｍ）"

[character_subs]
97 = "カズマ"

[script]
# lines: 4

# カズマ（Ｍ）
# display as カズマ
# （めぐみんとゆんゆんが\n　やけにモジモジして、スカートを気にしてた）
109 = "（めぐみんとゆんゆんが\\n　やけにモジモジして、スカートを気にしてた）"

# カズマ（Ｍ）
# display as カズマ
# （採寸の時といい、やっぱり\n　パンツを穿いてなかったとしか考えられない！）
110 = "（採寸の時といい、やっぱり\\n　パンツを穿いてなかったとしか考えられない！）"

# カズマ（Ｍ）
# display as カズマ
# （ということは、ゆんゆんがめぐみんをかばって\n　どっちも自分のパンツだって言い張ってたって\n　推理も当たりだな！）
108 = "（ということは、ゆんゆんがめぐみんをかばって\\n　どっちも自分のパンツだって言い張ってたって\\n　推理も当たりだな！）"

# カズマ（Ｍ）
# display as カズマ
# （すまん、ゆんゆん。\n　俺は今から真実を暴く。\n　現実とは厳しく、残酷なんだ……）
107 = "（すまん、ゆんゆん。\\n　俺は今から真実を暴く。\\n　現実とは厳しく、残酷なんだ……）"

