# tr04_07.txt.scn

[info]
0 = ""

[characters]
161 = "カズマ"
164 = "ルナ"
163 = "カズマ（Ｍ）"
159 = "めぐみん"

[character_subs]
# 161 = "カズマ"

[script]
# lines: 17

# カズマ
# 閃いたぁ！\nこの４枚のパンツのうち、\n１枚はギルドのお姉さんの物ですね！？
180 = "閃いたぁ！\\nこの４枚のパンツのうち、\\n１枚はギルドのお姉さんの物ですね！？"

# ルナ
# はいっ！？\nわ、私の物だって言うんですか？
158 = "はいっ！？\\nわ、私の物だって言うんですか？"

# カズマ
# そうです！\n根拠もちゃんとあります！
152 = "そうです！\\n根拠もちゃんとあります！"

# カズマ
# お姉さんは、俺達パーティーに\nやけに肩入れしてましたよね？
151 = "お姉さんは、俺達パーティーに\\nやけに肩入れしてましたよね？"

# カズマ
# もちろん嬉しかったんですが、\nギルドの平等性を考えると、ここまで\n親切にしてくれるのは腑に落ちないんですよ。
160 = "もちろん嬉しかったんですが、\\nギルドの平等性を考えると、ここまで\\n親切にしてくれるのは腑に落ちないんですよ。"

# カズマ
# なら、なぜそんなことをしたのか。\nそれは俺達に実入りのいいクエストを紹介して\nお金を稼がせたいから！
157 = "なら、なぜそんなことをしたのか。\\nそれは俺達に実入りのいいクエストを紹介して\\nお金を稼がせたいから！"

# カズマ
# そして、そのお金で早く\n呪いを解いてほしかったから！\nそうじゃないですか？
153 = "そして、そのお金で早く\\n呪いを解いてほしかったから！\\nそうじゃないですか？"

# カズマ
# ついでに言えば、急に裁判に参加したいって\n言い出したことも変ですよね？
155 = "ついでに言えば、急に裁判に参加したいって\\n言い出したことも変ですよね？"

# ルナ
# ……反論のしようがありませんね。\nええ、その通りです。
149 = "……反論のしようがありませんね。\\nええ、その通りです。"

# ルナ
# その、認めましたから……\nこれは返してもらいますね？
154 = "その、認めましたから……\\nこれは返してもらいますね？"

# カズマ（Ｍ）
# display as カズマ
# （それにしても……\n　お姉さんはこんなパンツを穿いて\n　受付の仕事をしてるのか！）
184 = "（それにしても……\\n　お姉さんはこんなパンツを穿いて\\n　受付の仕事をしてるのか！）"

# カズマ
# いいですよ。\nさあ、持っていってください！
150 = "いいですよ。\\nさあ、持っていってください！"

# ルナ
# では……。
156 = "では……。"

# カズマ（Ｍ）
# display as カズマ
# （おおっ！？\n　お姉さんはこんなパンツを穿いて\n　受付の仕事をしているのか！？）
182 = "（おおっ！？\\n　お姉さんはこんなパンツを穿いて\\n　受付の仕事をしているのか！？）"

# カズマ（Ｍ）
# display as カズマ
# （そ、それはそれで、なにか、こう……\n　非常にそそるものがあるな！）
183 = "（そ、それはそれで、なにか、こう……\\n　非常にそそるものがあるな！）"

# めぐみん
# カズマ。\n顔が見るに耐えないものになっていますよ。
162 = "カズマ。\\n顔が見るに耐えないものになっていますよ。"

# カズマ（Ｍ）
# display as カズマ
# （うう、つい顔に出てしまった）
181 = "（うう、つい顔に出てしまった）"

