# tr04_04.txt.scn

[info]
0 = ""

[characters]
82 = "カズマ（Ｍ）"

[character_subs]
81 = "カズマ"

[script]
# lines: 4

# カズマ（Ｍ）
# display as カズマ
# （そうだ、確かバニルが言ってたよな。\n　『この店も、泥棒に気をつけたほうが\n　　いいのではないか？』って）
88 = "（そうだ、確かバニルが言ってたよな。\\n　『この店も、泥棒に気をつけたほうが\\n　　いいのではないか？』って）"

# カズマ（Ｍ）
# display as カズマ
# （でもウィズが元は凄腕のアークウィザードだって\n　みんな知ってるんだぞ？\n　そんな人がいる店に誰が好んで泥棒に入る……）
91 = "（でもウィズが元は凄腕のアークウィザードだって\\n　みんな知ってるんだぞ？\\n　そんな人がいる店に誰が好んで泥棒に入る……）"

# カズマ（Ｍ）
# display as カズマ
# （つまりバニルのあの言葉は何かを示唆している）
90 = "（つまりバニルのあの言葉は何かを示唆している）"

# カズマ（Ｍ）
# display as カズマ
# （それはもちろんパンツ！\n　そしてバニルが示唆したパンツの持ち主は……\n　こいつだ！）
89 = "（それはもちろんパンツ！\\n　そしてバニルが示唆したパンツの持ち主は……\\n　こいつだ！）"

