# tr04_11.txt.scn

[info]
0 = ""

[characters]
203 = "カズマ"
200 = "ゆんゆん"
204 = "クリス"
202 = "アクア"
205 = "ダクネス"

[character_subs]

[script]
# lines: 18

# カズマ
# そうか、わかったぞ！\nこの４枚のパンツのうち、\n１枚はゆんゆんの物だ！
193 = "そうか、わかったぞ！\\nこの４枚のパンツのうち、\\n１枚はゆんゆんの物だ！"

# ゆんゆん
# ち、ちち、違いますっ！\n私の物じゃありません！！
195 = "ち、ちち、違いますっ！\\n私の物じゃありません！！"

# カズマ
# いやいや、否定したところで無駄だぞ？\n俺にはもうすべてが見えているんだからな！
187 = "いやいや、否定したところで無駄だぞ？\\n俺にはもうすべてが見えているんだからな！"

# ゆんゆん
# すべて見えてるってどういうことですか！？\nなにが見えてるんですか！？
191 = "すべて見えてるってどういうことですか！？\\nなにが見えてるんですか！？"

# クリス
# 落ち着いて、ゆんゆん。\n実際に見えてるわけじゃないから。
225 = "落ち着いて、ゆんゆん。\\n実際に見えてるわけじゃないから。"

# カズマ
# パンツの持ち主がゆんゆんである証拠は――
206 = "パンツの持ち主がゆんゆんである証拠は――"

# カズマ
# まず、ウィズの店での態度！\n明らかに挙動不審だった！
199 = "まず、ウィズの店での態度！\\n明らかに挙動不審だった！"

# カズマ
# それに、洞窟を調査している時、\nスカートを気にしたり、俺が後ろに立つのを\n嫌がったりしていたのもおかしい！
194 = "それに、洞窟を調査している時、\\nスカートを気にしたり、俺が後ろに立つのを\\n嫌がったりしていたのもおかしい！"

# ゆんゆん
# う、うううう……。
189 = "う、うううう……。"

# カズマ
# どうだ？\nなにか言い訳はあるのかな？
196 = "どうだ？\\nなにか言い訳はあるのかな？"

# ゆんゆん
# ありません……。
185 = "ありません……。"

# カズマ
# うむ、素直でよろしい。\nじゃあ、パンツ持っていっていいよ。
190 = "うむ、素直でよろしい。\\nじゃあ、パンツ持っていっていいよ。"

# カズマ
# んじゃ、もののついでに\nどのパンツなのか教えてもらえるか？
201 = "んじゃ、もののついでに\\nどのパンツなのか教えてもらえるか？"

# アクア
# あんた、こんな小さな子まで汚すなんて\nどんだけ鬼畜なのよ。
186 = "あんた、こんな小さな子まで汚すなんて\\nどんだけ鬼畜なのよ。"

# ダクネス
# そ、そういうことは、私にすべきだと思うぞ。
192 = "そ、そういうことは、私にすべきだと思うぞ。"

# ゆんゆん
# う、うう、私のは、それ……です……。
188 = "う、うう、私のは、それ……です……。"

# カズマ
# ほうほう、黒のパンツか。\nなるほどね、じゃあ持っていっていいよ。
198 = "ほうほう、黒のパンツか。\\nなるほどね、じゃあ持っていっていいよ。"

# アクア
# なんで上から目線なのよ。
197 = "なんで上から目線なのよ。"

