# tr04_05.txt.scn

[info]
0 = ""

[characters]
182 = "カズマ"
181 = "ウィズ"
184 = "ダクネス"
180 = "アクア"
183 = "カズマ（Ｍ）"

[character_subs]
# 182 = "カズマ"

[script]
# lines: 16

# カズマ
# わかったぞ！\nこの４枚のパンツのうち、１枚はウィズの物だ！
179 = "わかったぞ！\\nこの４枚のパンツのうち、１枚はウィズの物だ！"

# ウィズ
# ええっ！？\nそんな、どうしてわかったんですか！？
169 = "ええっ！？\\nそんな、どうしてわかったんですか！？"

# ダクネス
# 自分の物であることは否定しないのか？
200 = "自分の物であることは否定しないのか？"

# ウィズ
# はっ！！\nそ、それは……驚いて思わず……。
177 = "はっ！！\\nそ、それは……驚いて思わず……。"

# アクア
# まあ、そこまではっきり言っちゃったあとで\n違いますなんて否定もできないわよね。
178 = "まあ、そこまではっきり言っちゃったあとで\\n違いますなんて否定もできないわよね。"

# ウィズ
# はい……。\n私の物だというのは認めます。\nでも、本当にどうしてわかったんですか？
176 = "はい……。\\n私の物だというのは認めます。\\nでも、本当にどうしてわかったんですか？"

# カズマ
# バニルが言っただろ？\n『この店も、泥棒に気をつけたほうが\n　いいのではないか？』ってさ。
185 = "バニルが言っただろ？\\n『この店も、泥棒に気をつけたほうが\\n　いいのではないか？』ってさ。"

# カズマ
# その時、ウィズが妙に過剰に反応してたのが\n気になってたんだよ。
172 = "その時、ウィズが妙に過剰に反応してたのが\\n気になってたんだよ。"

# ウィズ
# それだけでですか？\nさすがはカズマさんですね。
173 = "それだけでですか？\\nさすがはカズマさんですね。"

# ウィズ
# と、言いたいところですが……\n下着、返して頂いていいでしょうか？
175 = "と、言いたいところですが……\\n下着、返して頂いていいでしょうか？"

# カズマ
# ああ。\nそれにしても、このピンクの\nアダルティなパンツがウィズのだったとはなぁ。
167 = "ああ。\\nそれにしても、このピンクの\\nアダルティなパンツがウィズのだったとはなぁ。"

# カズマ
# おう、いいぜ！\n持っていってくれよ。
170 = "おう、いいぜ！\\n持っていってくれよ。"

# ウィズ
# で、では……。
174 = "で、では……。"

# カズマ
# うおお！？\nそ、そのピンクのアダルティなパンツが\nウィズのだったのか！
168 = "うおお！？\\nそ、そのピンクのアダルティなパンツが\\nウィズのだったのか！"

# ウィズ
# その……かがむことが多い仕事ですので、\n線が出ない物を選んでいまして……。
171 = "その……かがむことが多い仕事ですので、\\n線が出ない物を選んでいまして……。"

# カズマ（Ｍ）
# display as カズマ
# （そ、そういう豆知識は\n　童貞には刺激が強すぎますよ！？）
203 = "（そ、そういう豆知識は\\n　童貞には刺激が強すぎますよ！？）"

