# tr04_02.txt.scn

[info]
0 = ""

[characters]
133 = "カズマ"
132 = "アクア"
131 = "ゆんゆん"
135 = "クリス"
134 = "カズマ（Ｍ）"

[character_subs]
# 133 = "カズマ"

[script]
# lines: 10

# カズマ
# で、裁判なわけだけど。
129 = "で、裁判なわけだけど。"

# アクア
# どうしたのよ。\nさっきまではテンション高かったのに。
130 = "どうしたのよ。\\nさっきまではテンション高かったのに。"

# カズマ
# いや、４枚となるとさすがになぁ。\n俺の推理力でも行けるかどうか不安があるんだよ。
125 = "いや、４枚となるとさすがになぁ。\\n俺の推理力でも行けるかどうか不安があるんだよ。"

# アクア
# だったら、いちいち裁判しないで\nまとめて私に預けてくれればいいのよ？\nカズマがわざわざ返す必要ないじゃない。
128 = "だったら、いちいち裁判しないで\\nまとめて私に預けてくれればいいのよ？\\nカズマがわざわざ返す必要ないじゃない。"

# ゆんゆん
# そうですっ！\nここで渡してくれれば\nなんの問題もないんですよ！？
126 = "そうですっ！\\nここで渡してくれれば\\nなんの問題もないんですよ！？"

# クリス
# 本当だよ。\nそもそもキミ以外にこの裁判を\n望んでいる人なんていないんだから。
139 = "本当だよ。\\nそもそもキミ以外にこの裁判を\\n望んでいる人なんていないんだから。"

# カズマ
# それは正論かもしれないが……\n俺の過ちを正すにはこれしかないんだっ！\n頼む！　俺を助けると思って協力してくれ！
127 = "それは正論かもしれないが……\\n俺の過ちを正すにはこれしかないんだっ！\\n頼む！　俺を助けると思って協力してくれ！"

# アクア
# ……格好よく言ってるけど、\nパンツのことと思うとすべてが台無しよね。
124 = "……格好よく言ってるけど、\\nパンツのことと思うとすべてが台無しよね。"

# カズマ（Ｍ）
# display as カズマ
# （さて、今回の推理はどこから行くべきか。\n　４枚となると、より慎重に進めていかないとな）
147 = "（さて、今回の推理はどこから行くべきか。\\n　４枚となると、より慎重に進めていかないとな）"

# カズマ（Ｍ）
# display as カズマ
# （そういえば、誰かが意味深なことを\n　言っていたような気が……）
148 = "（そういえば、誰かが意味深なことを\\n　言っていたような気が……）"

