# tr04_12.txt.scn

[info]
0 = ""

[characters]
165 = "カズマ"
167 = "クリス"
169 = "ルナ"
168 = "ダクネス"
164 = "アクア"
162 = "めぐみん"
166 = "カズマ（Ｍ）"

[character_subs]
# 165 = "カズマ"

[script]
# lines: 17

# カズマ
# よーし！\nこれですべてのパンツを持ち主に返せたな。\nいやぁ、今日もいい仕事をしたぜ！
163 = "よーし！\\nこれですべてのパンツを持ち主に返せたな。\\nいやぁ、今日もいい仕事をしたぜ！"

# クリス
# ……本当になんなの、その勝ち誇った態度は。\n女の子を辱めてなにが楽しいの？
151 = "……本当になんなの、その勝ち誇った態度は。\\n女の子を辱めてなにが楽しいの？"

# カズマ
# なあ、クリス。\nそれは誤解なんだって。
159 = "なあ、クリス。\\nそれは誤解なんだって。"

# カズマ
# 俺も好きでこんなことをしてるんじゃない。\nあくまで紳士として、紳士的に紳士らしく\n行動をしているだけさ。
171 = "俺も好きでこんなことをしてるんじゃない。\\nあくまで紳士として、紳士的に紳士らしく\\n行動をしているだけさ。"

# クリス
# ……キミさ、紳士って言えば\nなんでも許されると思ってない？
150 = "……キミさ、紳士って言えば\\nなんでも許されると思ってない？"

# ルナ
# このようなことが公然と行われているなんて……\nやはり、一刻も早くサトウさんの呪いを\n解除すべきですね。
154 = "このようなことが公然と行われているなんて……\\nやはり、一刻も早くサトウさんの呪いを\\n解除すべきですね。"

# ダクネス
# すまない。\nカズマが迷惑を。
156 = "すまない。\\nカズマが迷惑を。"

# アクア
# ねえ、みんな、聞いて。\nカズマはついに、ギルドの人にまで\n手を出したわけよね？
161 = "ねえ、みんな、聞いて。\\nカズマはついに、ギルドの人にまで\\n手を出したわけよね？"

# アクア
# このままでは、カズマは\nギルドを敵に回すかもしれないわ。
153 = "このままでは、カズマは\\nギルドを敵に回すかもしれないわ。"

# アクア
# そして、私達もそれに\n巻きこまれるかもしれないのよ？
157 = "そして、私達もそれに\\n巻きこまれるかもしれないのよ？"

# アクア
# これはもう悠長なことを\n言っている場合じゃないでしょ！
155 = "これはもう悠長なことを\\n言っている場合じゃないでしょ！"

# めぐみん
# 確かに……。
190 = "確かに……。"

# ルナ
# なんでしたら、今回のような支援ではなく、\n最高難易度のクエストなどご用意しますよ？
160 = "なんでしたら、今回のような支援ではなく、\\n最高難易度のクエストなどご用意しますよ？"

# カズマ
# 待って待って！\nそれってつまり、俺に死んでこいって\n言ってますよね！？
176 = "待って待って！\\nそれってつまり、俺に死んでこいって\\n言ってますよね！？"

# ルナ
# いえいえ、そんな。\n難易度が高ければ高いほど、\n報酬も高額になるじゃないですか。
152 = "いえいえ、そんな。\\n難易度が高ければ高いほど、\\n報酬も高額になるじゃないですか。"

# カズマ（Ｍ）
# display as カズマ
# （いやいやいやいや！\n　笑顔の奥に、ドス黒いになにかを\n　感じるんですけど！？）
191 = "（いやいやいやいや！\\n　笑顔の奥に、ドス黒いになにかを\\n　感じるんですけど！？）"

# カズマ
# と、とにかく、俺はちゃんと持ち主を当てたんだ。\nご褒美は受け取らせてもらうからな！
158 = "と、とにかく、俺はちゃんと持ち主を当てたんだ。\\nご褒美は受け取らせてもらうからな！"

