# tr04_13.txt.scn

[info]
0 = ""

[characters]
142 = "カズマ（Ｍ）"
145 = "ダクネス"
139 = "ゆんゆん"
144 = "クリス"
141 = "カズマ"
147 = "ルナ"
140 = "アクア"

[character_subs]
# 141 = "カズマ"

[script]
# lines: 17

# カズマ（Ｍ）
# display as カズマ
# （くっ……。\n　ダメだ、これ以上の推理はできそうにない）
165 = "（くっ……。\\n　ダメだ、これ以上の推理はできそうにない）"

# ダクネス
# どうした、カズマ。\n頭を抱えてしまって。
136 = "どうした、カズマ。\\n頭を抱えてしまって。"

# ゆんゆん
# もしかして、もう無理ってことですか？\nだったら、ここでお終いにしませんか？
138 = "もしかして、もう無理ってことですか？\\nだったら、ここでお終いにしませんか？"

# クリス
# じゃ、今回はここまででってことで。\nいいよね、キミ。
130 = "じゃ、今回はここまででってことで。\\nいいよね、キミ。"

# カズマ
# ち、ちくしょう！\n俺の限界はこんなものじゃないはずなのに！
133 = "ち、ちくしょう！\\n俺の限界はこんなものじゃないはずなのに！"

# ルナ
# ところで、サトウさん？\nその下着なのですが……。
135 = "ところで、サトウさん？\\nその下着なのですが……。"

# ルナ
# ギルド側で預かり\n持ち主に責任持って返却しますので、\nこちらに渡していただけますか？
143 = "ギルド側で預かり\\n持ち主に責任持って返却しますので、\\nこちらに渡していただけますか？"

# カズマ
# いや、そういうわけにはいきません。\n俺は紳士として、このパンツを\n持ち主に返さなくてはならないのです！
127 = "いや、そういうわけにはいきません。\\n俺は紳士として、このパンツを\\n持ち主に返さなくてはならないのです！"

# クリス
# ドヤ顔で何言ってるの、キミは。
146 = "ドヤ顔で何言ってるの、キミは。"

# ルナ
# ですが、あなたは持ち主を当てることも\nできなかったのですよ？
134 = "ですが、あなたは持ち主を当てることも\\nできなかったのですよ？"

# ルナ
# それで、どうやって返すのですか？\nその方法を、ぜひとも教えて頂きたいですね。
132 = "それで、どうやって返すのですか？\\nその方法を、ぜひとも教えて頂きたいですね。"

# カズマ（Ｍ）
# display as カズマ
# （こ、この威圧感は一体？\n　スカルドラゴンに勝るとも劣らない！？）
166 = "（こ、この威圧感は一体？\\n　スカルドラゴンに勝るとも劣らない！？）"

# カズマ
# 申し訳ございませんでした！\n後のことはよろしくお願いします！
152 = "申し訳ございませんでした！\\n後のことはよろしくお願いします！"

# ルナ
# はい、では確かにお預かりしました。
137 = "はい、では確かにお預かりしました。"

# アクア
# さて、カズマ？\nわかってるわよね？\nこの後に待っているのは……。
129 = "さて、カズマ？\\nわかってるわよね？\\nこの後に待っているのは……。"

# カズマ
# お、お仕置きでございますか？
128 = "お、お仕置きでございますか？"

# アクア
# そうよっ！\n覚悟なさい、カズマ！！
131 = "そうよっ！\\n覚悟なさい、カズマ！！"

