# tr04_08.txt.scn

[info]
0 = ""

[characters]
99 = "カズマ（Ｍ）"

[character_subs]
98 = "カズマ"

[script]
# lines: 4

# カズマ（Ｍ）
# display as カズマ
# （アクアだけに\n　あまり意味のない言葉に思えるかもしれない）
106 = "（アクアだけに\\n　あまり意味のない言葉に思えるかもしれない）"

# カズマ（Ｍ）
# display as カズマ
# （しかし、これは重大な発言だったんだ！）
104 = "（しかし、これは重大な発言だったんだ！）"

# カズマ（Ｍ）
# display as カズマ
# （何が重大なのか！　それはもちろんパンツだ！\n　アクアが感じた違和感の裏にはパンツの持ち主が\n　隠れている！）
107 = "（何が重大なのか！　それはもちろんパンツだ！\\n　アクアが感じた違和感の裏にはパンツの持ち主が\\n　隠れている！）"

# カズマ（Ｍ）
# display as カズマ
# （そしてその違和感の正体。\n　パンツの持ち主は……こいつだ！！）
105 = "（そしてその違和感の正体。\\n　パンツの持ち主は……こいつだ！！）"

