# tr04_06.txt.scn

[info]
0 = ""

[characters]
82 = "カズマ（Ｍ）"

[character_subs]
81 = "カズマ"

[script]
# lines: 4

# カズマ（Ｍ）
# display as カズマ
# （よくよく考えてみると、\n　お姉さんの態度っておかしかったよな）
92 = "（よくよく考えてみると、\\n　お姉さんの態度っておかしかったよな）"

# カズマ（Ｍ）
# display as カズマ
# （そしてこのおかしな態度はパンツ！\n　そうパンツの持ち主を示唆している！）
90 = "（そしてこのおかしな態度はパンツ！\\n　そうパンツの持ち主を示唆している！）"

# カズマ（Ｍ）
# display as カズマ
# （ふっ、簡単な推理だぜ！）
91 = "（ふっ、簡単な推理だぜ！）"

# カズマ（Ｍ）
# display as カズマ
# （そう、お姉さんが示唆したパンツの持ち主は\n　こいつだ！）
89 = "（そう、お姉さんが示唆したパンツの持ち主は\\n　こいつだ！）"

