# tr04_14.txt.scn

[info]
0 = ""

[characters]

[character_subs]

[script]
# lines: 0

[selections]
124 = "アクア"
122 = "めぐみん"
127 = "ダクネス"
125 = "ウィズ"
126 = "クリス"
123 = "ゆんゆん"
# 124 = "アクア"
# 122 = "めぐみん"
# 127 = "ダクネス"
# 125 = "ウィズ"
# 126 = "クリス"
# 123 = "ゆんゆん"
