# tr04_10.txt.scn

[info]
0 = ""

[characters]
86 = "カズマ（Ｍ）"

[character_subs]
85 = "カズマ"

[script]
# lines: 2

# カズマ（Ｍ）
# display as カズマ
# （なるほど、そうか、そういうことか）
91 = "（なるほど、そうか、そういうことか）"

# カズマ（Ｍ）
# display as カズマ
# （わかったぞ、パンツの持ち主は、こいつだ！）
92 = "（わかったぞ、パンツの持ち主は、こいつだ！）"

