# tr04_09.txt.scn

[info]
0 = ""

[characters]
169 = "カズマ"
170 = "クリス"

[character_subs]

[script]
# lines: 15

# カズマ
# なるほどな、わかったぜ。\nこの４枚のパンツのうち、１枚はクリスの物だ！
164 = "なるほどな、わかったぜ。\\nこの４枚のパンツのうち、１枚はクリスの物だ！"

# クリス
# ……なんでわかっちゃうのかなぁ。\nホント、キミっておかしいよ。
155 = "……なんでわかっちゃうのかなぁ。\\nホント、キミっておかしいよ。"

# カズマ
# おかしいとか言うな！\nちゃんと推理した結果だって！
157 = "おかしいとか言うな！\\nちゃんと推理した結果だって！"

# クリス
# じゃあ、その推理を聞かせてもらえる？
160 = "じゃあ、その推理を聞かせてもらえる？"

# カズマ
# ああ、もちろんだ！
156 = "ああ、もちろんだ！"

# カズマ
# まず、俺達が洞窟調査の協力を頼んだ時、\n妙に不機嫌そうだったよな？\nそれに、協力自体も渋ってた。
168 = "まず、俺達が洞窟調査の協力を頼んだ時、\\n妙に不機嫌そうだったよな？\\nそれに、協力自体も渋ってた。"

# カズマ
# 普段は割と協力的なのに、\nなんか変だと思ってたんだよ。
173 = "普段は割と協力的なのに、\\nなんか変だと思ってたんだよ。"

# カズマ
# それから、実際に洞窟に行ったとき、\n俺が後ろにいるのをやたら嫌がってただろ？
161 = "それから、実際に洞窟に行ったとき、\\n俺が後ろにいるのをやたら嫌がってただろ？"

# カズマ
# これもやっぱり、\nパンツを盗まれてたからじゃないのか？
158 = "これもやっぱり、\\nパンツを盗まれてたからじゃないのか？"

# クリス
# はいはい、降参。\n降参だから、早く返してくれない？
166 = "はいはい、降参。\\n降参だから、早く返してくれない？"

# カズマ
# しかし、クリスが\nこんなパンツを穿くとは意外だな。
159 = "しかし、クリスが\\nこんなパンツを穿くとは意外だな。"

# カズマ
# と言われても、\nどのパンツなのかわからないぜ？\n自分で取ってくれよ。
162 = "と言われても、\\nどのパンツなのかわからないぜ？\\n自分で取ってくれよ。"

# クリス
# はあ……。\n本当にキミは意地悪だね。
165 = "はあ……。\\n本当にキミは意地悪だね。"

# カズマ
# へえ～、黄色いパンツかぁ。\nなんか意外だな。
167 = "へえ～、黄色いパンツかぁ。\\nなんか意外だな。"

# クリス
# な、なにを基準に意外って言ってるのよ！\nもうっ！
163 = "な、なにを基準に意外って言ってるのよ！\\nもうっ！"

