# tr04_03.txt.scn

[info]
0 = ""

[characters]
151 = "カズマ"
152 = "カズマ（Ｍ）"

[character_subs]
# 151 = "カズマ"

[script]
# lines: 4

# カズマ
# （よし！　次に怪しいのはどの証言だ？）
165 = "（よし！　次に怪しいのはどの証言だ？）"

# カズマ（Ｍ）
# display as カズマ
# （……駄女神のダメ発言は忘れよう。\n　別の発言を思い出すんだ）
162 = "（……駄女神のダメ発言は忘れよう。\\n　別の発言を思い出すんだ）"

# カズマ（Ｍ）
# display as カズマ
# （これも意味深だが、\n　他の台詞のほうが証拠になりそうだ。\n　よく思い出せ、俺！）
164 = "（これも意味深だが、\\n　他の台詞のほうが証拠になりそうだ。\\n　よく思い出せ、俺！）"

# カズマ（Ｍ）
# display as カズマ
# （これは別に、おかしい発言じゃないな。\n　むしろ冒険者としてめずらしくまともなことを\n　言ってるじゃないか）
163 = "（これは別に、おかしい発言じゃないな。\\n　むしろ冒険者としてめずらしくまともなことを\\n　言ってるじゃないか）"

[selections]
141 = "この店も、泥棒に気をつけたほうが\\nいいのではないか？"
145 = "な、なるほど。\\nだから……なんですね。"
142 = "それで取り分を要求されたら、\\n私の分が減っちゃうわ！\\n絶対に嫌よ！"
146 = "ねえ、カズマ？\\nあんた、クリスに何かしたの？\\n妙に不機嫌じゃない。"
147 = "ふ、２人きりで！？\\n無理！　絶対に無理！　引き受けないから！"
144 = "どうしたのですか、ゆんゆん。\\nなぜカズマを見ているのですか？"
143 = "それよりも明日の準備を進めよう。\\n洞窟まで行くんだ、携帯食なども必要だろう？"
