# tr05_11.txt.scn

[info]
0 = ""

[characters]
133 = "カズマ（Ｍ）"

[character_subs]
132 = "カズマ"

[script]
# lines: 8

# カズマ（Ｍ）
# display as カズマ
# （これがラストだ！\n　緑のパンツは……）
144 = "（これがラストだ！\\n　緑のパンツは……）"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんだったよな？\n　うん、そうだろ）
148 = "（ゆんゆんだったよな？\\n　うん、そうだろ）"

# カズマ（Ｍ）
# display as カズマ
# （めぐみんだ！\n　俺のカンがそう告げている！）
147 = "（めぐみんだ！\\n　俺のカンがそう告げている！）"

# カズマ（Ｍ）
# display as カズマ
# （そうだ、ウィズのパンツだ！\n　これをスカルドラゴンに渡すとき、\n　ウィズがすごく恥ずかしがってたもんな）
146 = "（そうだ、ウィズのパンツだ！\\n　これをスカルドラゴンに渡すとき、\\n　ウィズがすごく恥ずかしがってたもんな）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスだったっけ？\n　あいつはもっとわかりやすい反応を\n　示した物があったような……）
149 = "（ダクネスだったっけ？\\n　あいつはもっとわかりやすい反応を\\n　示した物があったような……）"

# カズマ（Ｍ）
# display as カズマ
# （さて、これで５枚のパンツの持ち主を\n　推理したわけだが……）
145 = "（さて、これで５枚のパンツの持ち主を\\n　推理したわけだが……）"

# カズマ（Ｍ）
# display as カズマ
# （正直言って、この推理には自信があるぜ。\n　あとはみんなに真実を突きつけるだけだ！）
151 = "（正直言って、この推理には自信があるぜ。\\n　あとはみんなに真実を突きつけるだけだ！）"

# カズマ（Ｍ）
# display as カズマ
# （本当にこの推理で正解なのか？\n　ここは慎重に、もう一度じっくり考えてみよう）
150 = "（本当にこの推理で正解なのか？\\n　ここは慎重に、もう一度じっくり考えてみよう）"

[selections]
130 = "ゆんゆん"
129 = "めぐみん"
131 = "ウィズ"
134 = "ダクネス"
