# tr05_03.txt.scn

[info]
0 = ""

[characters]
143 = "カズマ（Ｍ）"

[character_subs]
142 = "カズマ"

[script]
# lines: 9

# カズマ（Ｍ）
# display as カズマ
# （さて、まずは２枚の黒いパンツから\n　考えてみるとするか）
161 = "（さて、まずは２枚の黒いパンツから\\n　考えてみるとするか）"

# カズマ（Ｍ）
# display as カズマ
# （そういえば、誰かが黒いパンツについて\n　話していたような気がするが……）
162 = "（そういえば、誰かが黒いパンツについて\\n　話していたような気がするが……）"

# カズマ（Ｍ）
# display as カズマ
# （確かに青いリボンがついている黒いパンツも\n　あるが、ここはもう１枚の黒いパンツについて\n　考えてみるとしよう）
166 = "（確かに青いリボンがついている黒いパンツも\\n　あるが、ここはもう１枚の黒いパンツについて\\n　考えてみるとしよう）"

# カズマ（Ｍ）
# display as カズマ
# （ピンクのパンツは後回しだ。\n　まずは黒いパンツについて考えるぞ）
165 = "（ピンクのパンツは後回しだ。\\n　まずは黒いパンツについて考えるぞ）"

# カズマ（Ｍ）
# display as カズマ
# （黒とは言ってるけど、パンツとは関係ないよな）
167 = "（黒とは言ってるけど、パンツとは関係ないよな）"

# カズマ（Ｍ）
# display as カズマ
# （これは……黒いパンツには関係ないな。\n　他の発言を思い出してみよう）
160 = "（これは……黒いパンツには関係ないな。\\n　他の発言を思い出してみよう）"

# カズマ（Ｍ）
# display as カズマ
# （うん、これは間違いなく関係ないな）
159 = "（うん、これは間違いなく関係ないな）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスも、いつもこういうまともなことを\n　言ってくれれば文句ないんだけどなぁ……）
164 = "（ダクネスも、いつもこういうまともなことを\\n　言ってくれれば文句ないんだけどなぁ……）"

# カズマ（Ｍ）
# display as カズマ
# （そうだ！\n　俺が黒が好きなのかって聞いたら\n　めぐみんが過剰に反応したんだ）
163 = "（そうだ！\\n　俺が黒が好きなのかって聞いたら\\n　めぐみんが過剰に反応したんだ）"

[selections]
156 = "確かにカズマは、\\n変態でヘタレでクズでヒキニートな\\n駄目人間だけど――"
137 = "だ、だ、だったらなんですか！？\\nまさか黒が好きだから、いつも黒いのを\\n身につけてるとでも思ってるんですか！"
157 = "青いリボン！？\\nど、どうしてそれをっ！？"
134 = "こ、これはもしや私を辱めているのか？\\nひらひらでピンクとか……言う気か！？"
158 = "黒魔術に興味があるのか？\\n孤独に愛される娘よ。"
136 = "し、下着泥棒は犯罪ですよっ！\\nささやかな趣味なんかじゃありませんっ！"
135 = "ここは私に任せておけ！\\n仲間を守るのがクルセイダーの役割だ！"
