# tr05_12.txt.scn

[info]
0 = ""

[characters]
269 = "カズマ"
265 = "ゆんゆん"
268 = "ウィズ"
263 = "めぐみん"
273 = "ダクネス"
271 = "クリス"
267 = "アクア"
270 = "カズマ（Ｍ）"

[character_subs]
# 269 = "カズマ"

[script]
# lines: 35

# カズマ
# すべてわかったぜ。\nあの５枚のパンツの持ち主を、\n今、ここに告げよう！
249 = "すべてわかったぜ。\\nあの５枚のパンツの持ち主を、\\n今、ここに告げよう！"

# カズマ
# 黒いパンツはめぐみん！
306 = "黒いパンツはめぐみん！"

# カズマ
# 同じ黒でも、リボンつきはゆんゆん！
278 = "同じ黒でも、リボンつきはゆんゆん！"

# カズマ
# ピンクのひらひらはダクネス！
275 = "ピンクのひらひらはダクネス！"

# カズマ
# ヒモのパンツはクリス！
274 = "ヒモのパンツはクリス！"

# カズマ
# そして、緑のパンツがウィズだっ！
253 = "そして、緑のパンツがウィズだっ！"

# ゆんゆん
# あああああ……。
242 = "あああああ……。"

# ウィズ
# はうう……。
258 = "はうう……。"

# めぐみん
# な、なんでわかるんですか……！
255 = "な、なんでわかるんですか……！"

# ダクネス
# くううっ……！
245 = "くううっ……！"

# クリス
# ま、待ちなさいっ！\n根拠は！？　当てずっぽうに\n言ってるだけじゃないの！？
261 = "ま、待ちなさいっ！\\n根拠は！？　当てずっぽうに\\n言ってるだけじゃないの！？"

# カズマ
# 焦るなよ、ちゃんと説明してやるって。\nまず、黒のパンツからだ。
283 = "焦るなよ、ちゃんと説明してやるって。\\nまず、黒のパンツからだ。"

# カズマ
# これは、俺の『黒が好きなのか』という質問に\nめぐみんが過剰に反応したことが根拠だ！
246 = "これは、俺の『黒が好きなのか』という質問に\\nめぐみんが過剰に反応したことが根拠だ！"

# カズマ
# ゆんゆんも同じだ！\n俺が、髪のリボンの色が青だと指摘したら\nおかしなぐらいに慌てたよな？
266 = "ゆんゆんも同じだ！\\n俺が、髪のリボンの色が青だと指摘したら\\nおかしなぐらいに慌てたよな？"

# ゆんゆん
# そ、そんな細かいことを覚えているなんて……。
250 = "そ、そんな細かいことを覚えているなんて……。"

# めぐみん
# 変態ですね。
279 = "変態ですね。"

# カズマ
# なんでだよっ！\n逆に、観察眼が鋭いとか\n褒めるところじゃないのか！？
256 = "なんでだよっ！\\n逆に、観察眼が鋭いとか\\n褒めるところじゃないのか！？"

# めぐみん
# 気持ち悪いだけです。
281 = "気持ち悪いだけです。"

# カズマ
# じゃ、じゃあ、次！\nヒモのパンツと緑のパンツは――
247 = "じゃ、じゃあ、次！\\nヒモのパンツと緑のパンツは――"

# カズマ
# スカルドラゴンにパンツを渡すときの\nクリス、ウィズの反応が根拠だ！\n２人とも、すごく恥ずかしがってたからな！
272 = "スカルドラゴンにパンツを渡すときの\\nクリス、ウィズの反応が根拠だ！\\n２人とも、すごく恥ずかしがってたからな！"

# クリス
# へえ～。\nつまりキミは、あたし達が恥ずかしがる姿を\nじっくり観察して脳裏に焼き付けてたわけ？
260 = "へえ～。\\nつまりキミは、あたし達が恥ずかしがる姿を\\nじっくり観察して脳裏に焼き付けてたわけ？"

# めぐみん
# やっぱり変態ですね。
264 = "やっぱり変態ですね。"

# カズマ
# そうじゃねーよ！\nで、そんなことより、認めるのか？\n俺の推理が正解だって。
251 = "そうじゃねーよ！\\nで、そんなことより、認めるのか？\\n俺の推理が正解だって。"

# クリス
# う……。
243 = "う……。"

# めぐみん
# …………。
241 = "…………。"

# ゆんゆん
# それは、その……。
254 = "それは、その……。"

# ウィズ
# …………。
# 241 = "…………。"

# カズマ
# はっはっはっはっはぁ！\nその様子だと、俺の勝ちのようだな！
259 = "はっはっはっはっはぁ！\\nその様子だと、俺の勝ちのようだな！"

# ダクネス
# す、素晴らしいっ！\nこんな責めができるのはカズマだけだ！\n私は今、感動に震えているっ！
248 = "す、素晴らしいっ！\\nこんな責めができるのはカズマだけだ！\\n私は今、感動に震えているっ！"

# クリス
# 褒めるところじゃないよ！
305 = "褒めるところじゃないよ！"

# アクア
# ねえ、今の態度、どう思う？\nやっぱりこの男、呪いなんて関係なく\n埋めてしまったほうがいいんじゃないかしら？
257 = "ねえ、今の態度、どう思う？\\nやっぱりこの男、呪いなんて関係なく\\n埋めてしまったほうがいいんじゃないかしら？"

# ゆんゆん
# そうですね。\nやっぱりどこかの火口に捨ててしまいませんか？
252 = "そうですね。\\nやっぱりどこかの火口に捨ててしまいませんか？"

# めぐみん
# ええ、まったくです。\n簀巻きにして放り込みましょう。
244 = "ええ、まったくです。\\n簀巻きにして放り込みましょう。"

# カズマ
# ま、待ったぁ！\nすみませんすみません、\n調子に乗りました、やめてくださいぃぃ！！
262 = "ま、待ったぁ！\\nすみませんすみません、\\n調子に乗りました、やめてくださいぃぃ！！"

# カズマ（Ｍ）
# display as カズマ
# （これはもう、ご褒美なんて\n　言い出しにくい雰囲気だけど……\n　なしってことはないよな？）
307 = "（これはもう、ご褒美なんて\\n　言い出しにくい雰囲気だけど……\\n　なしってことはないよな？）"

