# tr05_07.txt.scn

[info]
0 = ""

[characters]
115 = "カズマ（Ｍ）"

[character_subs]
114 = "カズマ"

[script]
# lines: 5

# カズマ（Ｍ）
# display as カズマ
# （まず、シンプルな黒のパンツの持ち主は……）
127 = "（まず、シンプルな黒のパンツの持ち主は……）"

# カズマ（Ｍ）
# display as カズマ
# （そうだ、アクアだな！\n　俺はついに、あの駄女神のパンツを\n　盗み出してやったんだ！！）
125 = "（そうだ、アクアだな！\\n　俺はついに、あの駄女神のパンツを\\n　盗み出してやったんだ！！）"

# カズマ（Ｍ）
# display as カズマ
# （そうだな、これはめぐみんで決まりだ）
126 = "（そうだな、これはめぐみんで決まりだ）"

# カズマ（Ｍ）
# display as カズマ
# （うーん、ダクネスかな？\n　多分だけど）
123 = "（うーん、ダクネスかな？\\n　多分だけど）"

# カズマ（Ｍ）
# display as カズマ
# （きっとウィズだろうな）
124 = "（きっとウィズだろうな）"

[selections]
112 = "アクア"
111 = "めぐみん"
116 = "ダクネス"
113 = "ウィズ"
