# tr05_10.txt.scn

[info]
0 = ""

[characters]
109 = "カズマ（Ｍ）"

[character_subs]
108 = "カズマ"

[script]
# lines: 7

# カズマ（Ｍ）
# display as カズマ
# （次の、このヒモのパンツは……）
124 = "（次の、このヒモのパンツは……）"

# カズマ（Ｍ）
# display as カズマ
# （アクアめ、仮にも女神だってのに\n　こんな大胆なパンツを穿いていいのか？）
119 = "（アクアめ、仮にも女神だってのに\\n　こんな大胆なパンツを穿いていいのか？）"

# カズマ（Ｍ）
# display as カズマ
# （うん、クリスだな。\n　なぜなら……）
118 = "（うん、クリスだな。\\n　なぜなら……）"

# カズマ（Ｍ）
# display as カズマ
# （スカルドラゴンにこのパンツ渡すとき、\n　クリスがすっげー恥ずかしがってた！\n　それが根拠だ！）
122 = "（スカルドラゴンにこのパンツ渡すとき、\\n　クリスがすっげー恥ずかしがってた！\\n　それが根拠だ！）"

# カズマ（Ｍ）
# display as カズマ
# （ギルドのお姉さん……だったっけ？\n　まあ、そういうことにしておくか）
121 = "（ギルドのお姉さん……だったっけ？\\n　まあ、そういうことにしておくか）"

# カズマ（Ｍ）
# display as カズマ
# （ウィズ……だったかな？）
120 = "（ウィズ……だったかな？）"

# カズマ（Ｍ）
# display as カズマ
# （スカルドラゴンにパンツを渡すとき\n　ウィズがやけに反応していた覚えはあるが、\n　このパンツにだったか？）
123 = "（スカルドラゴンにパンツを渡すとき\\n　ウィズがやけに反応していた覚えはあるが、\\n　このパンツにだったか？）"

[selections]
106 = "アクア"
111 = "クリス"
110 = "ギルドのお姉さん"
107 = "ウィズ"
