# tr05_14.txt.scn

[info]
0 = ""

[characters]

[character_subs]

[script]
# lines: 0

[selections]
125 = "アクア"
123 = "めぐみん"
128 = "ダクネス"
126 = "ウィズ"
127 = "クリス"
124 = "ゆんゆん"
# 125 = "アクア"
# 123 = "めぐみん"
# 128 = "ダクネス"
# 126 = "ウィズ"
# 127 = "クリス"
# 124 = "ゆんゆん"
