# tr05_08.txt.scn

[info]
0 = ""

[characters]
111 = "カズマ（Ｍ）"

[character_subs]
110 = "カズマ"

[script]
# lines: 5

# カズマ（Ｍ）
# display as カズマ
# （次に、青いリボンのついた黒のパンツの\n　持ち主は……）
123 = "（次に、青いリボンのついた黒のパンツの\\n　持ち主は……）"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんだ！　間違いない！\n　これは自信があるぜ！）
121 = "（ゆんゆんだ！　間違いない！\\n　これは自信があるぜ！）"

# カズマ（Ｍ）
# display as カズマ
# （めぐみん……かな？\n　そんな気がする）
120 = "（めぐみん……かな？\\n　そんな気がする）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスじゃないかと思うんだが……\n　まあ、とりあえずそうしておこう）
122 = "（ダクネスじゃないかと思うんだが……\\n　まあ、とりあえずそうしておこう）"

# カズマ（Ｍ）
# display as カズマ
# （これこそアクアだろ！\n　あの駄女神のパンツがついに公衆の面前に\n　さらされるってわけだ！）
119 = "（これこそアクアだろ！\\n　あの駄女神のパンツがついに公衆の面前に\\n　さらされるってわけだ！）"

[selections]
108 = "ゆんゆん"
107 = "めぐみん"
112 = "ダクネス"
109 = "アクア"
