# tr05_09.txt.scn

[info]
0 = ""

[characters]
110 = "カズマ（Ｍ）"

[character_subs]
109 = "カズマ"

[script]
# lines: 5

# カズマ（Ｍ）
# display as カズマ
# （次だ！\n　この、ピンクのひらひらのパンツは……）
124 = "（次だ！\\n　この、ピンクのひらひらのパンツは……）"

# カズマ（Ｍ）
# display as カズマ
# （……クリスだったっけ？\n　そうだよな？）
120 = "（……クリスだったっけ？\\n　そうだよな？）"

# カズマ（Ｍ）
# display as カズマ
# （ゆんゆんだったはず……だよな？）
122 = "（ゆんゆんだったはず……だよな？）"

# カズマ（Ｍ）
# display as カズマ
# （これはダクネス以外、考えられない。\n　決まりだな）
121 = "（これはダクネス以外、考えられない。\\n　決まりだな）"

# カズマ（Ｍ）
# display as カズマ
# （アクアだ！\n　今まで上手いこと盗まれるのを避けてたが、\n　ついに呪いに負けやがったな駄女神！）
123 = "（アクアだ！\\n　今まで上手いこと盗まれるのを避けてたが、\\n　ついに呪いに負けやがったな駄女神！）"

[selections]
111 = "クリス"
107 = "ゆんゆん"
112 = "ダクネス"
108 = "アクア"
