# tr05_04.txt.scn

[info]
0 = ""

[characters]
139 = "カズマ（Ｍ）"

[character_subs]
138 = "カズマ"

[script]
# lines: 9

# カズマ（Ｍ）
# display as カズマ
# （くくく……。\n　こいつは怪しいよなぁ？）
157 = "（くくく……。\\n　こいつは怪しいよなぁ？）"

# カズマ（Ｍ）
# display as カズマ
# （それと、確かこの青いリボンのついてるほうも\n　心当たりがあったよな？）
161 = "（それと、確かこの青いリボンのついてるほうも\\n　心当たりがあったよな？）"

# カズマ（Ｍ）
# display as カズマ
# （ピンクのパンツは後回しだ。\n　今は、青いリボンがついている\n　パンツについて考えるぞ）
163 = "（ピンクのパンツは後回しだ。\\n　今は、青いリボンがついている\\n　パンツについて考えるぞ）"

# カズマ（Ｍ）
# display as カズマ
# （いや、このバニルの発言は\n　パンツとは関係ないよな？）
156 = "（いや、このバニルの発言は\\n　パンツとは関係ないよな？）"

# カズマ（Ｍ）
# display as カズマ
# （これは……パンツには関係ないな。\n　他の発言を思い出してみよう）
159 = "（これは……パンツには関係ないな。\\n　他の発言を思い出してみよう）"

# カズマ（Ｍ）
# display as カズマ
# （思い出すたびに腹が立つ！）
164 = "（思い出すたびに腹が立つ！）"

# カズマ（Ｍ）
# display as カズマ
# （ダクネスも、いつもこういうまともなことを\n　言ってくれれば文句ないんだけどなぁ……）
162 = "（ダクネスも、いつもこういうまともなことを\\n　言ってくれれば文句ないんだけどなぁ……）"

# カズマ（Ｍ）
# display as カズマ
# （この発言は黒いパンツについてのものだ。\n　もっとはっきり、青いリボンについて\n　発言した奴がいたはずだ）
158 = "（この発言は黒いパンツについてのものだ。\\n　もっとはっきり、青いリボンについて\\n　発言した奴がいたはずだ）"

# カズマ（Ｍ）
# display as カズマ
# （そう、ゆんゆんだ！\n　ゆんゆんは基本的に素直で良い子だから\n　すぐにわかっちまうんだよな）
160 = "（そう、ゆんゆんだ！\\n　ゆんゆんは基本的に素直で良い子だから\\n　すぐにわかっちまうんだよな）"

[selections]
153 = "確かにカズマは、\\n変態でヘタレでクズでヒキニートな\\n駄目人間だけど――"
133 = "だ、だ、だったらなんですか！？\\nまさか黒が好きだから、いつも黒いのを\\n身につけてるとでも思ってるんですか！"
154 = "青いリボン！？\\nど、どうしてそれをっ！？"
130 = "こ、これはもしや私を辱めているのか？\\nひらひらでピンクとか……言う気か！？"
155 = "黒魔術に興味があるのか？\\n孤独に愛される娘よ。"
132 = "し、下着泥棒は犯罪ですよっ！\\nささやかな趣味なんかじゃありませんっ！"
131 = "ここは私に任せておけ！\\n仲間を守るのがクルセイダーの役割だ！"
