# tr05_13.txt.scn

[info]
0 = ""

[characters]
157 = "カズマ（Ｍ）"
155 = "アクア"
159 = "ダクネス"
153 = "めぐみん"
156 = "カズマ"
154 = "ゆんゆん"
158 = "クリス"

[character_subs]
# 156 = "カズマ"

[script]
# lines: 16

# カズマ（Ｍ）
# display as カズマ
# （くっ……。\n　ダメだ、これ以上の推理はできそうにない）
179 = "（くっ……。\\n　ダメだ、これ以上の推理はできそうにない）"

# アクア
# ほら、やっぱり持ち主を当てるなんて\n無理だったじゃない。
151 = "ほら、やっぱり持ち主を当てるなんて\\n無理だったじゃない。"

# ダクネス
# ……残念だ。\nここでどれほどの羞恥を感じられるのか\n楽しみにしていたというのに。
141 = "……残念だ。\\nここでどれほどの羞恥を感じられるのか\\n楽しみにしていたというのに。"

# めぐみん
# ダクネスは本当にブレませんね。
160 = "ダクネスは本当にブレませんね。"

# アクア
# じゃ、パンツは没収よ。\nあんたに女性用下着を持たせておくなんて\n嫌な予感しかしないもの。
146 = "じゃ、パンツは没収よ。\\nあんたに女性用下着を持たせておくなんて\\n嫌な予感しかしないもの。"

# カズマ
# どういう意味だよ！？
149 = "どういう意味だよ！？"

# アクア
# それと、さっき、さらっと\nこのパンツを買ってきたって言ったけど――
148 = "それと、さっき、さらっと\\nこのパンツを買ってきたって言ったけど――"

# アクア
# それって女性下着売り場に\n１人で行ってきたってことよね？
147 = "それって女性下着売り場に\\n１人で行ってきたってことよね？"

# ゆんゆん
# え、ええ、そういうことですよね。\nそういうのって、正直、ちょっと……。
143 = "え、ええ、そういうことですよね。\\nそういうのって、正直、ちょっと……。"

# めぐみん
# この変態、そんなプレイにまで\n目覚めてしまったのですか。\nダクネス、後は頼みます。
145 = "この変態、そんなプレイにまで\\n目覚めてしまったのですか。\\nダクネス、後は頼みます。"

# ダクネス
# い、いや、待て！\n私はそういうプレイは好まないぞ！\n誤解するな！
142 = "い、いや、待て！\\n私はそういうプレイは好まないぞ！\\n誤解するな！"

# クリス
# ねえ、指輪の呪いは解けたけどさ、\nやっぱりどこかに埋めたほうがいいんじゃない？
150 = "ねえ、指輪の呪いは解けたけどさ、\\nやっぱりどこかに埋めたほうがいいんじゃない？"

# ゆんゆん
# 賛成です。\n埋めるか火口に放り込むかしましょう。\nそれが世界のためです。
177 = "賛成です。\\n埋めるか火口に放り込むかしましょう。\\nそれが世界のためです。"

# カズマ
# （うわー、こいつら言いたい放題だ）
178 = "（うわー、こいつら言いたい放題だ）"

# アクア
# まあ、あんたの始末は後で考えるとして――
152 = "まあ、あんたの始末は後で考えるとして――"

# アクア
# お仕置きの時間よ！\n覚悟なさい！
144 = "お仕置きの時間よ！\\n覚悟なさい！"

