# tr05_02.txt.scn

[info]
0 = ""

[characters]
157 = "カズマ"
158 = "クリス"
152 = "めぐみん"
153 = "ゆんゆん"
159 = "ダクネス"
156 = "ウィズ"
155 = "アクア"

[character_subs]

[script]
# lines: 16

# カズマ
# それじゃ、裁判を始めるか！\n今回は５枚だからな、\nさくさく行かないと終わらねーぞ？
146 = "それじゃ、裁判を始めるか！\\n今回は５枚だからな、\\nさくさく行かないと終わらねーぞ？"

# クリス
# でもさ、パンツはもうスカルドラゴンに\n渡しちゃってるんだよ？
150 = "でもさ、パンツはもうスカルドラゴンに\\n渡しちゃってるんだよ？"

# クリス
# 返すこともできないのに、\nわざわざ裁判をやる必要なんてあるのかな？
180 = "返すこともできないのに、\\nわざわざ裁判をやる必要なんてあるのかな？"

# カズマ
# だから、言っただろ？\nどのパンツが誰の物であるか！\nこの真実を明らかにするんだって。
149 = "だから、言っただろ？\\nどのパンツが誰の物であるか！\\nこの真実を明らかにするんだって。"

# めぐみん
# 明らかにしたところで、\n返すべき物がないのにですか？
164 = "明らかにしたところで、\\n返すべき物がないのにですか？"

# カズマ
# ふっ、ふふん、そこは抜かりないぜ？\nほら、見てみろ！
151 = "ふっ、ふふん、そこは抜かりないぜ？\\nほら、見てみろ！"

# ゆんゆん
# ええっ！？\nなんでパンツを持ってるんですか！？\nドラゴンから取り戻していたんですか！？
143 = "ええっ！？\\nなんでパンツを持ってるんですか！？\\nドラゴンから取り戻していたんですか！？"

# カズマ
# 取り戻す隙なんてなかっただろ。\nこれは買って来たんだよ。
161 = "取り戻す隙なんてなかっただろ。\\nこれは買って来たんだよ。"

# ダクネス
# か、買ってきた、だと！？\nカズマがか！？
144 = "か、買ってきた、だと！？\\nカズマがか！？"

# カズマ
# 記憶を頼りに選んできたけど、\n大体、同じ物だよな？
179 = "記憶を頼りに選んできたけど、\\n大体、同じ物だよな？"

# ウィズ
# え、ええ、そうですね。\n色も形も……同じみたいです。\nよく覚えていましたね。
142 = "え、ええ、そうですね。\\n色も形も……同じみたいです。\\nよく覚えていましたね。"

# カズマ
# いやぁ、まさか\n同じ物を揃えられるとは思わなかったぜ。\nこれも俺の幸運パラメーターのおかげだな！
141 = "いやぁ、まさか\\n同じ物を揃えられるとは思わなかったぜ。\\nこれも俺の幸運パラメーターのおかげだな！"

# カズマ
# それとも、この燃え上がる紳士魂が\nパンツを呼び寄せたのかな？\n紳士の神は俺を見ているってことか。
147 = "それとも、この燃え上がる紳士魂が\\nパンツを呼び寄せたのかな？\\n紳士の神は俺を見ているってことか。"

# アクア
# そんな神、聞いたことないんですけどー？
148 = "そんな神、聞いたことないんですけどー？"

# クリス
# ここまでする情熱を\nもっと他に向けられないのかな？
145 = "ここまでする情熱を\\nもっと他に向けられないのかな？"

# カズマ
# よし！\nじゃあ、今回は５枚連続でパンツを返していくぞ！
154 = "よし！\\nじゃあ、今回は５枚連続でパンツを返していくぞ！"

