# tr05_06.txt.scn

[info]
0 = ""

[characters]
87 = "カズマ（Ｍ）"

[character_subs]
86 = "カズマ"

[script]
# lines: 3

# カズマ（Ｍ）
# display as カズマ
# （で、残ったのはヒモのパンツと緑のパンツだな。\n　これはどうやって検証しよう？\n　なにかヒントがあったかな？）
95 = "（で、残ったのはヒモのパンツと緑のパンツだな。\\n　これはどうやって検証しよう？\\n　なにかヒントがあったかな？）"

# カズマ（Ｍ）
# display as カズマ
# （……あ、そうだ！\n　スカルドラゴンにパンツを渡したときの反応で\n　判断できるんじゃないか？）
93 = "（……あ、そうだ！\\n　スカルドラゴンにパンツを渡したときの反応で\\n　判断できるんじゃないか？）"

# カズマ（Ｍ）
# display as カズマ
# （うん、行けそうだな。\n　これで５枚のパンツについて\n　まとめられるんじゃないか？）
94 = "（うん、行けそうだな。\\n　これで５枚のパンツについて\\n　まとめられるんじゃないか？）"

