# voicedummy.txt.scn

[info]
120 = "ボイスダミー"

[characters]
117 = "カズマ"
115 = "アクア"
113 = "めぐみん"
119 = "ダクネス"
118 = "クリス"
116 = "ウィズ"
114 = "ゆんゆん"
121 = "ルナ"

[character_subs]

[script]
# lines: 78

# カズマ
# ボイスダミー
# 120 = "ボイスダミー"

# カズマ
# ボイスダミー
# 120 = "ボイスダミー"

# カズマ
# ボイスダミー
# 120 = "ボイスダミー"

# カズマ
# ボイスダミー
# 120 = "ボイスダミー"

# カズマ
# ボイスダミー
# 120 = "ボイスダミー"

# カズマ
# ボイスダミー
# 120 = "ボイスダミー"

# カズマ
# ボイスダミー
# 120 = "ボイスダミー"

# カズマ
# ボイスダミー
# 120 = "ボイスダミー"

# カズマ
# ボイスダミー
# 120 = "ボイスダミー"

# カズマ
# ボイスダミー
# 120 = "ボイスダミー"

# カズマ
# ボイスダミー
# 120 = "ボイスダミー"

# カズマ
# ボイスダミー
# 120 = "ボイスダミー"

# アクア
# ボイスダミー
# 120 = "ボイスダミー"

# アクア
# ボイスダミー
# 120 = "ボイスダミー"

# アクア
# ボイスダミー
# 120 = "ボイスダミー"

# アクア
# ボイスダミー
# 120 = "ボイスダミー"

# アクア
# ボイスダミー
# 120 = "ボイスダミー"

# アクア
# ボイスダミー
# 120 = "ボイスダミー"

# アクア
# ボイスダミー
# 120 = "ボイスダミー"

# アクア
# ボイスダミー
# 120 = "ボイスダミー"

# アクア
# ボイスダミー
# 120 = "ボイスダミー"

# アクア
# ボイスダミー
# 120 = "ボイスダミー"

# めぐみん
# ボイスダミー
# 120 = "ボイスダミー"

# めぐみん
# ボイスダミー
# 120 = "ボイスダミー"

# めぐみん
# ボイスダミー
# 120 = "ボイスダミー"

# めぐみん
# ボイスダミー
# 120 = "ボイスダミー"

# めぐみん
# ボイスダミー
# 120 = "ボイスダミー"

# めぐみん
# ボイスダミー
# 120 = "ボイスダミー"

# めぐみん
# ボイスダミー
# 120 = "ボイスダミー"

# めぐみん
# ボイスダミー
# 120 = "ボイスダミー"

# めぐみん
# ボイスダミー
# 120 = "ボイスダミー"

# めぐみん
# ボイスダミー
# 120 = "ボイスダミー"

# ダクネス
# ボイスダミー
# 120 = "ボイスダミー"

# ダクネス
# ボイスダミー
# 120 = "ボイスダミー"

# ダクネス
# ボイスダミー
# 120 = "ボイスダミー"

# ダクネス
# ボイスダミー
# 120 = "ボイスダミー"

# ダクネス
# ボイスダミー
# 120 = "ボイスダミー"

# ダクネス
# ボイスダミー
# 120 = "ボイスダミー"

# ダクネス
# ボイスダミー
# 120 = "ボイスダミー"

# ダクネス
# ボイスダミー
# 120 = "ボイスダミー"

# ダクネス
# ボイスダミー
# 120 = "ボイスダミー"

# クリス
# ボイスダミー
# 120 = "ボイスダミー"

# クリス
# ボイスダミー
# 120 = "ボイスダミー"

# クリス
# ボイスダミー
# 120 = "ボイスダミー"

# クリス
# ボイスダミー
# 120 = "ボイスダミー"

# クリス
# ボイスダミー
# 120 = "ボイスダミー"

# クリス
# ボイスダミー
# 120 = "ボイスダミー"

# クリス
# ボイスダミー
# 120 = "ボイスダミー"

# クリス
# ボイスダミー
# 120 = "ボイスダミー"

# クリス
# ボイスダミー
# 120 = "ボイスダミー"

# ウィズ
# ボイスダミー
# 120 = "ボイスダミー"

# ウィズ
# ボイスダミー
# 120 = "ボイスダミー"

# ウィズ
# ボイスダミー
# 120 = "ボイスダミー"

# ウィズ
# ボイスダミー
# 120 = "ボイスダミー"

# ウィズ
# ボイスダミー
# 120 = "ボイスダミー"

# ウィズ
# ボイスダミー
# 120 = "ボイスダミー"

# ウィズ
# ボイスダミー
# 120 = "ボイスダミー"

# ウィズ
# ボイスダミー
# 120 = "ボイスダミー"

# ウィズ
# ボイスダミー
# 120 = "ボイスダミー"

# ゆんゆん
# ボイスダミー
# 120 = "ボイスダミー"

# ゆんゆん
# ボイスダミー
# 120 = "ボイスダミー"

# ゆんゆん
# ボイスダミー
# 120 = "ボイスダミー"

# ゆんゆん
# ボイスダミー
# 120 = "ボイスダミー"

# ゆんゆん
# ボイスダミー
# 120 = "ボイスダミー"

# ゆんゆん
# ボイスダミー
# 120 = "ボイスダミー"

# ゆんゆん
# ボイスダミー
# 120 = "ボイスダミー"

# ゆんゆん
# ボイスダミー
# 120 = "ボイスダミー"

# ゆんゆん
# ボイスダミー
# 120 = "ボイスダミー"

# ゆんゆん
# ボイスダミー
# 120 = "ボイスダミー"

# ルナ
# ボイスダミー
# 120 = "ボイスダミー"

# ルナ
# ボイスダミー
# 120 = "ボイスダミー"

# ルナ
# ボイスダミー
# 120 = "ボイスダミー"

# ルナ
# ボイスダミー
# 120 = "ボイスダミー"

# ルナ
# ボイスダミー
# 120 = "ボイスダミー"

# ルナ
# ボイスダミー
# 120 = "ボイスダミー"

# ルナ
# ボイスダミー
# 120 = "ボイスダミー"

# ルナ
# ボイスダミー
# 120 = "ボイスダミー"

# ルナ
# ボイスダミー
# 120 = "ボイスダミー"

